### ISSUE TITLE
When taking blob snapshot without any metadata, "PIRTag=1" will be set in snapshot's metadata.

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-powershell#10]
When taking blob snapshot without any metadata, "PIRTag=1" will be set in snapshot's metadata. Expect no metadata in snapshot.

**Comment by gangsir** [comment]
I can't reproduce this on a new blob. Can you check if this metadata was added on the base blob? The metadata of the base blob will be copied to its snapshot which is by design of storage rest api.

**Comment by AbelHu** [comment]
It happened last year. Since you cannot repro it now, close it.
