### ISSUE TITLE
Az.Maps is not included into Az modules pack

### ISSUE THREAD

**Issue by Rycardas** [Azure/azure-powershell#10008]
Hello, 
Is anyone using Azure Maps? 
We recently needed this resource and appears it was not included into Az modules: "Install-Module -Name Az -AllowClobber"

Now , we had to upload this one module separately to our Servers to execute automated scripts by running "Install-Module -Name Az.Maps" 

It's not convenient if we do upgrades or migration on the way to not miss this little module . 

Is there explanation why this was not included or any plans to do later on?

**Comment by erich-wang** [comment]
@Rycardas , only GAed modules are included in Az, Az.Maps is still in preview stage.

@jp94, do you have any timeline for Az.Maps GA, i.e. upgrade to 1.0 version?

**Comment by Rycardas** [comment]
Thanks
