### ISSUE TITLE
Az.Accounts 2.0.0-preview  module does not use the right authority for ADFS

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#10009]
## Description

Trying to login with Az.Accounts module into an Azure Stack ADFS env fails with "Error occurred when attempting to acquire the common tenant token". The environment is setup with login endpoint as "https://adfs.local.azurestack.external/adfs" but Connect-AzAccount cmdlet goes to "login.microsoftonline.com" for acquiring access token.

![image](https://user-images.githubusercontent.com/21109279/64718581-5eea7380-d47b-11e9-811c-6e2ac1e2372c.png)

 ```
PS C:\Users\Administrator> Get-AzEnvironment -Name azstack | fl *


Name                                              : azstack
EnableAdfsAuthentication                          : True
OnPremise                                         : True
ActiveDirectoryServiceEndpointResourceId          : https://adminmanagement.adfs.azurestack.local/d3709825-b65f-4535-a2
                                                    61-623b5f2bf25c
AdTenant                                          :
GalleryUrl                                        : https://adminproviders.azurestack.local:30016/
ManagementPortalUrl                               :
ServiceManagementUrl                              :
PublishSettingsFileUrl                            :
ResourceManagerUrl                                : https://adminmanagement.local.azurestack.external
SqlDatabaseDnsSuffix                              :
StorageEndpointSuffix                             : local.azurestack.external
ActiveDirectoryAuthority                          : https://adfs.local.azurestack.external/adfs/
GraphUrl                                          : https://graph.local.azurestack.external/
GraphEndpointResourceId                           : https://graph.local.azurestack.external/
TrafficManagerDnsSuffix                           :
AzureKeyVaultDnsSuffix                            : vault.local.azurestack.external
DataLakeEndpointResourceId                        :
AzureDataLakeStoreFileSystemEndpointSuffix        :
AzureDataLakeAnalyticsCatalogAndJobEndpointSuffix :
AzureKeyVaultServiceEndpointResourceId            : https://vault.local.azurestack.external
AzureOperationalInsightsEndpointResourceId        :
AzureOperationalInsightsEndpoint                  :
AzureAnalysisServicesEndpointSuffix               :
AnalysisServicesEndpointResourceId                :
VersionProfiles                                   : {}
ExtendedProperties                                : {}
BatchEndpointResourceId                           :

PS C:\Users\Administrator>  Connect-AzAccount -Environment azstack -Credential $ServiceAdminCreds
WARNING: Unable to acquire token for tenant 'organizations'
Connect-AzAccount : Error occurred when attempting to acquire the common tenant token. Please run 'Connect-AzAccount`
again to authenticate.
At line:1 char:2
+  Connect-AzAccount -Environment azstack -Credential $ServiceAdminCred ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], RuntimeException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
```

**Comment by erich-wang** [comment]
@viananth , would you mind providing the following information?

- The list of modules installed on your machine
  - Run Get-Module -ListAvailable
- The debug output from running the two different commands
  - Set $DebugPreference = "Continue" and then run the commands

**Comment by bganapa** [comment]
@erich-wang @markcowl 
This is with az.accounts module 2.0.0-preview  against ADFS environments. This is a must fix as ADFS login with silent user credentials is broken

The following call is also being made which should not be needed for ADFS as it is single tenanted
https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Fadfs.local.azurestack.external%2Fadfs%2Foauth2%2Fv2.0%2Fauthorize


PS C:\bala> gmo

ModuleType Version    Name                                ExportedCommands                                                                                          
---------- -------    ----                                ----------------                                                                                          
Script     2.0.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}                               
Script     4.0.1      Az.Resources                        {Add-AzADApplicationOwner, Add-AzADGroupMember, Add-AzADGroupOwner, Export-AzDeploymentTemplate...}       
Script     0.0.1      Azs.AzureBridge.Admin               {Get-AzsActivation, Get-AzsDownloadedProduct, Get-AzsProduct, Invoke-AzsDownloadProduct...}               
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                       
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                        
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}                 
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                 
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}                           



PS C:\bala> Get-AzEnvironment -Name AzureStack | fl *


Name                                              : AzureStack
EnableAdfsAuthentication                          : True
OnPremise                                         : True
ActiveDirectoryServiceEndpointResourceId          : https://adminmanagement.adfs.azurestack.local/e402a545-38a9-4ec4-a221-9c4a4af9267f
AdTenant                                          : 
GalleryUrl                                        : https://adminproviders.azurestack.local:30016/
ManagementPortalUrl                               : 
ServiceManagementUrl                              : 
PublishSettingsFileUrl                            : 
ResourceManagerUrl                                : https://adminmanagement.local.azurestack.external/
SqlDatabaseDnsSuffix                              : 
StorageEndpointSuffix                             : local.azurestack.external
ActiveDirectoryAuthority                          : https://adfs.local.azurestack.external/adfs/
GraphUrl                                          : https://graph.local.azurestack.external/
GraphEndpointResourceId                           : https://graph.local.azurestack.external/
TrafficManagerDnsSuffix                           : 
AzureKeyVaultDnsSuffix                            : vault.local.azurestack.external
DataLakeEndpointResourceId                        : 
AzureDataLakeStoreFileSystemEndpointSuffix        : 
AzureDataLakeAnalyticsCatalogAndJobEndpointSuffix : 
AzureKeyVaultServiceEndpointResourceId            : https://vault.local.azurestack.external
AzureOperationalInsightsEndpointResourceId        : 
AzureOperationalInsightsEndpoint                  : 
AzureAnalysisServicesEndpointSuffix               : 
AnalysisServicesEndpointResourceId                : 
VersionProfiles                                   : {}
ExtendedProperties                                : {}
BatchEndpointResourceId                           : 

DEBUG: 4:39:59 PM - GetAzureRMEnvironmentCommand end processing.
DEBUG: 4:39:59 PM - GetAzureRMEnvironmentCommand end processing.



PS C:\bala> Login-AzAccount -EnvironmentName AzureStack -Credential $creds -Tenant e402a545-38a9-4ec4-a221-9c4a4af9267f
DEBUG: 4:40:15 PM - Autosave setting from startup session: 'Process'
DEBUG: 4:40:15 PM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 4:40:15 PM - Using Autosave scope 'Process'
DEBUG: 4:40:15 PM - Autosave setting from startup session: 'Process'
DEBUG: 4:40:15 PM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 4:40:15 PM - Using Autosave scope 'Process'
Login-AzAccount : AADSTS50049: Unknown or invalid instance.
Trace ID: b7494bb1-ed5d-44e7-9325-0b02c215f000
Correlation ID: 850988a2-0f41-4b4a-b47c-a3a98725cd2a
Timestamp: 2019-10-18 23:40:15Z
At line:1 char:1
+ Login-AzAccount -EnvironmentName AzureStack -Credential $creds -Tenan ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], MsalServiceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
 
DEBUG: 4:40:15 PM - ConnectAzureRmAccountCommand end processing.
DEBUG: 4:40:15 PM - ConnectAzureRmAccountCommand end processing.

PS C:\bala> Login-AzAccount -EnvironmentName AzureStack -Credential $creds
DEBUG: 4:41:00 PM - Autosave setting from startup session: 'Process'
DEBUG: 4:41:00 PM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 4:41:00 PM - Using Autosave scope 'Process'
DEBUG: 4:41:00 PM - Autosave setting from startup session: 'Process'
DEBUG: 4:41:00 PM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 4:41:00 PM - Using Autosave scope 'Process'
WARNING: Unable to acquire token for tenant 'organizations'
Login-AzAccount : Error occurred when attempting to acquire the common tenant token. Please run 'Connect-AzAccount` again to authenticate.
At line:1 char:1
+ Login-AzAccount -EnvironmentName AzureStack -Credential $creds
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], RuntimeException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
 
DEBUG: 4:41:00 PM - ConnectAzureRmAccountCommand end processing.
DEBUG: 4:41:00 PM - ConnectAzureRmAccountCommand end processing.

**Comment by dingmeng-xue** [comment]
We still need more time to investigate on this issue. Will keep you updated.

**Comment by odedlaz** [comment]
Any updates on this one? I had to upgrade to 2.0.0-preview because of https://github.com/Azure/azure-powershell/issues/9427 and now I get this error.

**Comment by dingmeng-xue** [comment]
The original issue has been fixed in new preview version. It will be available in February.  @odedlaz , fyi, current MSAL requires GNome on Linux, such as Ubuntu server or cloud version. If you find issue on Linux, please log a new issue.
