### ISSUE TITLE
ApiId parameter not found on Get-AzApiManagementProduct with Azure Powershell

### ISSUE THREAD

**Issue by neothoms** [Azure/azure-powershell#10017]
# Description
I have an issue with Get-AzApiManagementProduct used with ApiId parameter.
I run the command in an Azure Powershell in Devops Release (version 4 in preview).
I have forced the installation of latest Az modules (2.6.0) I see with the get-Module that the Az.ApiManagement module is correctly installed with version 1.3.0

The error is [error]A parameter cannot be found that matches parameter name 'ApiId'.
It is like the Command is not executed with the module installed 

## Steps to reproduce
Create a Azure devops release
Add a task Azure Powershell version 4.

```Write-Host "Installation of Az Modules"
Install-Module -Name Az -Repository PSGallery -RequiredVersion "2.6.0" -AllowClobber -Scope CurrentUser -Force 
Get-InstalledModule -Name "Az.ApiManagement"

$apiManagement_Name = "an api management name"
$resourceGroupCore = "a resource group"
$apiId = "your api id"
$ProductId="your product id"

$ctxApim = New-AzApiManagementContext -ResourceGroupName $resourceGroupCore -ServiceName $apiManagement_Name

$apiProducts = Get-AzApiManagementProduct -Context $ctxApim -ApiId $apiId |Select-Object -ExpandProperty ProductId

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by erich-wang** [comment]
@neothoms , You may start new PowerShell session and then run 
`Import-Module Az -Version 2.6`
and try again.

If issue remains, please provide the following info:

-  Layout of the modules on this machine:
PS > Get-Module -ListAvailable

-  The debug output from running your command
PS > Set $DebugPreference = "Continue" and then run the commands

- The imported module
PS > Get-Module

**Comment by neothoms** [comment]
Hi,

I have tried Import-Module but it does not change anything.
You can have a glimpse of the pipeline configuration :
![image](https://user-images.githubusercontent.com/11428292/64947448-4b714b00-d875-11e9-8e62-fbf1ba46baeb.png)

You can find the full log in the embeded file :
[tasklog_4.log](https://github.com/Azure/azure-powershell/files/3615522/tasklog_4.log)

Here is the full code 
`$DebugPreference = "Continue"

Write-Host "Installation of Az Modules"
Install-Module -Name Az -Repository PSGallery -RequiredVersion "2.6.0" -AllowClobber -Scope CurrentUser -Force 

Get-Module -ListAvailable

Write-Host "Import"
 Import-Module -Version 2.6 -Name Az -Scope Local -Force

Write-Host "Module List after Import"
Get-Module -ListAvailable


$apiManagement_Name = "$(apiManagement_Name)"
$resourceGroupCore = "$(resourceGroupCore)"
$apiId = "securitymodel-privateBH20"
$ProductId="product-securitymodel-private"

$ctxApim = New-AzApiManagementContext -ResourceGroupName $resourceGroupCore -ServiceName $apiManagement_Name

$apiProducts = Get-AzApiManagementProduct -Context $ctxApim -ApiId $apiId |Select-Object -ExpandProperty ProductId

$apiProducts `

**Comment by ToMakeSense** [comment]
@neothoms [Upgrade AzureRM Powershell on Hosted 2017 Agent (VSTS - Visual Studio Team Services)](https://stackoverflow.com/questions/50375331/upgrade-azurerm-powershell-on-hosted-2017-agent-vsts-visual-studio-team-servi) for your reference

**Comment by neothoms** [comment]
I think I have found the root of the problem.

The Import-Module of Az.ApiManagement needs the Module Az.Accounts in version 1.6.2 but the Azure Powershell module for Devops in version 4 is using 1.6.0
Since the module is used by Azure Powershell to login it can not be ugraded to 1.6.2 (even with -force)
Therefore the Az.ApiManagement is installed for the Current User but can not be instanciated in the current session.

In conclusion, the only way I have found to use the correct version of Az.ApiManagement is to import Az.Accound with a prefix and then Import Az.ApiManagement with the same prefix.

BUT, it is not a good solution since I would have to change all my Command-lets to all my scripts to add the prefix and it is a too high risk to take since I have a lot of them.

Can you please update the Azure Powershell to let us change the required Az.Accounts needed ?

**Comment by erich-wang** [comment]
@dcaro , this is request for upgrading Az in devops, please contact corresponding team
