### ISSUE TITLE
Invoke-AzVMRunCommand as a job

### ISSUE THREAD

**Issue by vineethkondapally** [Azure/azure-powershell#10021]
## Description
I am trying to use Invoke-AzVMRunCommand as a job. when I executed below script the job is created and executed successfully but  I am failing to write the output like which job result belongs to which vm.
## Code
$cred = Get-Credential
Login-AzAccount -Credential $cred 
$jobs = @()
foreach ($subscription in Get-AzSubscription -SubscriptionName 'SWS_INFRA_Microsoft_Azure') {
    Set-AzContext -Subscription $subscription.SubscriptionId | Out-Null
foreach ($resourcegroup in Get-AzResourceGroup -Name 'NCR_SWS_INFRA_RGP') {
    $azvm = Get-AzVM -ResourceGroupName $resourcegroup.ResourceGroupName  -Status | Where-Object { $_.StorageProfile.OSDisk.OSType -eq "Windows" -and $_.powerstate -eq 'VM running' } 
#$hashvar=@{}
$azvm | ForEach-Object -Process {
    $jobs += Invoke-AzVMRunCommand  -ResourceGroupName $_.ResourceGroupName -Name $_.Name -CommandId 'RunPowerShellScript' -ScriptPath 'C:\My Data\Working\azinvokescript.ps1' -Parameter  @{"arg1" = 'var1' } -AsJob 
}
$result = @()
$jobs | ForEach-Object -Process {
    while ($_.State -eq 'running') {
        Start-Sleep 1
        $_ = Get-Job -Id $_.Id
        $result += Get-Job -Id $_.id | Receive-Job
} 
}
$result

New-Object PSObject -Property (
    [ordered]@{
        VMName           = $azvm.Name
        SubscriptionName = $subscription.Name
        Resourcegroup    = $azvm.ResourceGroupName
        PatchStatus      = $result.Value[0].message
    })
}
}

**Comment by erich-wang** [comment]
@vineethkondapally , how about use vmname as part of parameter value of CommandId?

**Comment by erich-wang** [comment]
Close the issue as there's work around.
