### ISSUE TITLE
New-AzAutomationSoftwareUpdateConfiguration -RebootSettings doesn't seem to work for Linux Schedules.

### ISSUE THREAD

**Issue by kristopherjturner** [Azure/azure-powershell#10026]
When running New-AzAutomationSoftwareUpdateConfiguration and using the -RebootSettings parameter in Windows based Schedules it takes the values we give it. (example, Never, IfRequired, etc.)  However, when using -RebootSettings for Linux based Schedules, no matter what we put for the value, it also goes to the default IfRequired.

**Comment by zjalexander** [comment]
Yup, that's a bug alright. We repro'd this internally and filed a work item to track it (5373978). I'll sync with our team and see when we will be able to get a fix out.

**Comment by kristopherjturner** [comment]
Thank you!

**Comment by zjalexander** [comment]
PR #10109
