### ISSUE TITLE
why don't we have a Get-AzKeyVaultAccessPolicy?

### ISSUE THREAD

**Issue by sasanmcp** [Azure/azure-powershell#10030]
How can I list existing Access Policies of an Azure Key vault using either PowerShell or CLI now? I don't see a Get-AzKeyVaultAccessPolicy command.

**Comment by i255d** [comment]
Or why doesn't (Get-AzKeyVault).AccessPolicies work like it used to under AzureRM?

**Comment by dingmeng-xue** [comment]
According to the latest Az.KeyVault, user can gent policies via `(Get-AzKeyVault -VaultName $vaultName).AccessPolicies`.

**Comment by i255d** [comment]
dingmeng-xue, thanks for the response.  I figured out the day after I posted this that adding the -VaultName is a different parameter set, and give a more detailed output the list of objects created when just running Get-AzKeyVault.  If I would have read the help, I would have figured it out sooner.  📦

**Comment by dingmeng-xue** [comment]
It's great. I'm closing this issue. Sorry for the slow response.

Please contact us if you have meet any issue.
