### ISSUE TITLE
Work for Storage.Management generated cmdlets

### ISSUE THREAD

**Issue by niander** [Azure/azure-powershell#10059]
Just few points lacking attention

* Update-AzStorageAccount
    - Maybe we should remove the `-Kind` parameter and replace it to just `-UpgradeToStorageV2`

* New-AzStorageAccount
    - Verify the real need of checking the name availability using `NameAvailability` api before creating a new storage account

**Comment by dingmeng-xue** [comment]
Due to Storage module won't be auto generated in the near future, close this request.
