### ISSUE TITLE
New-AzFunctionApp needs to have a parameter to specify the runtime version

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-powershell#10051]
I am working on the cmdlet for Azure Function. This is a tracking work item for the ```New-AzFunctionApp``` cmdlet.

**Comment by pragnagopa** [comment]
Please ensure this follows same semantics as webapp. Here is an example for linux webapp: https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-create

**Comment by dalibormesaric** [comment]
What is the status of this?

**Comment by Francisco-Gamino** [comment]
Hi @dalibormesaric, this is to be able to select the Host (runtime) version to either 2 or 3 (which is currently in Preview).

**Comment by tcsdmaic** [comment]
Will the runtime parameter support "dotnetcore" as an option?

**Comment by Francisco-Gamino** [comment]
Hi @tcsdmaic, the purpose of this parameter was to set the runtime version. However, in the preview version of the [Az.Functions](https://www.powershellgallery.com/packages/Az.Functions/0.0.1-preview) module, both the `runtime name` and `runtime version` are specified via the `Runtime` parameter. These are the values that we support, which get autocompleted for the user: `DotNet, Node_8, Node_10, Java, PowerShell, Python_3.6, and Python_3.7`.

If you'd like to specified the Host version, I am introducing a new parameter named `HostVersion`. This takes integer 2 or 3. The default value will be 2 at the moment, and later change to 3.

**Comment by eamonoreilly** [comment]
I think we should create a new optional parameter (RuntimeVersion) to specify the version. If not specified, we will default to the latest supported runtime version which is generally what we want to encourage.

**Comment by pragnagopa** [comment]
@eamonoreilly - For each runtime (language) there is one default version which is currently supported i.e for node its node 8, for powershell is powershell 6 etc. Once this parameter is introduced, we should not be changing defaults. Users should explicitly select runtime version.

**Comment by Francisco-Gamino** [comment]
Customer will need to select their runtime language and version in a single parameter.

**Comment by Francisco-Gamino** [comment]
I had a conversation with @eamonoreilly, and we are going to introduce a non required parameter
`-RuntimeVersion`. If the customer does not specified the runtime version, we will use the default one. This default version will depended on two things: HostVersion and Runtime. 

For example, if the customer specified HostVersion 3 and Runtime PowerShell, then the current default value will be 6.

**Comment by pragnagopa** [comment]
This is inconsistent with other tooling. Also, ties powershell version selection to functions runtime version. We need to be explicit in runtime version selection otherwise users will have to implicitly understand functions host version and default runtime versions.

@eamonoreilly / @Francisco-Gamino  - Lets discuss this offline if needed.

**Comment by Francisco-Gamino** [comment]
Hi @pragnagopa, let me add a bit more details. 

The plan is to add a new parameter `-RuntimeVersion` to have a similar tooling experience as with the `az cli` (which has a `--runtime` and `--runtime-version`). The HostVersion is taken into consideration given that certain runtimes are not available in V2 or V3. For example, Node 8 is available in V2, but not V3. Let's discuss a bit more offline tomorrow.

**Comment by Francisco-Gamino** [comment]
Hello @dalibormesaric, please take a look at the latest iteration of the Az.Functions module. In the latest version, you can specifiy the runtime and the available runtimes version via `-Runtime` and `-RuntimeVersion` parameters.

To install the latest version of Az.Functions, run from PowerShell 6 or 7 (if you don't have the last PowerShell,  you can download it from https://github.com/PowerShell/PowerShell/releases).

```powershell
Install-Module -Name Az.Functions -AllowPrerelease`
```
