### ISSUE TITLE
Work for Monitor generated cmdlets

### ISSUE THREAD

**Issue by niander** [Azure/azure-powershell#10060]
Just few points

- Get-AzMetric
    - While the swagger type of `-Aggregation` is a string, in the current cmdlet it is of type `AggregationType` which is defined in another resource spec (`MetricDefinition`).
>
- Get-AzAutoescaleHistory
    - This scenario based cmdlet was not implemented. It uses `ActivityLogs` API to retrieve only logs about autoscale settings.

**Comment by dolauli** [comment]
@niander 

- Get-AzMetric

 While the swagger type of -Aggregation is a string, in the current cmdlet it is of type AggregationType which is defined in another resource spec (MetricDefinition).

[Derek] This looks has been fixed.
`PS C:\Users\xidi\src\azure-powershell\src\Monitor [Az.Monitor]> get-help Get-AzMetric

NAME
    Get-AzMetric
    
SYNOPSIS
    **Lists the metric values for a resource**.


SYNTAX
    Get-AzMetric -ResourceId <String> [-Aggregation <String>] [-Filter <String>] [-Interval <TimeSpan>] [-Metricname <String>] [-Metricnamespace <String>] [-Orderby <String>] [-ResultType <ResultType>] [-Timespan <String>] [-Top <Int32>] [-DefaultProfile     
    <PSObject>] [-Break] [-HttpPipelineAppend <SendAsyncStep[]>] [-HttpPipelinePrepend <SendAsyncStep[]>] [-Proxy <Uri>] [-ProxyCredential <PSCredential>] [-ProxyUseDefaultCredentials] [<CommonParameters>]`

**Comment by dingmeng-xue** [comment]
Due to Monitor module won't be auto generated in the near future, close this request.
