### ISSUE TITLE
Generation for AKS

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#10071]
## Description

Generate and customize modules for the new AKS service

- [ ] Generate, build, and examine API surface
- [ ] Ensure that New/Set/Update cmdlets use only expanded variants
- [ ] Ensure that all POST operations use only expanded variants
- [ ] Change Cmdlet, Parameter, and property names for consistency and clarity
- [ ] Write CRUD tests for top-level resources
- [ ] Hold a cmdlet design review using the updated generated help files
- [ ] Fiel issue for Customizations and tests

## Priority 0

**Comment by dingmeng-xue** [comment]
close it as duplicate with #10249
