### ISSUE TITLE
Add ARM API Support to generated module tests

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#10076]
## Description
Each module needs to be able to create and remove resource groups, get available locations, and deploy templates in order to set up the environment for the rest of the test.  Add ARM APIs to test configuration, and place in the internal module for use in tests

- [ ] Add common configuration for internal ARM APIs 
- [ ] Write a test using the new APIs

**Comment by dolauli** [comment]
@markcowl If we won't rely on the gallery to get the Az.Resources, we could build it locally from source code. What we need to do is as below for each module.

1. In check-dependencies.ps1, check whether Az.Resources has been built locally. If not, build it on the fly. (autorest-beta & .\build-module.ps1)
2. Import Az.Resources with _Import-Module -Name (Join-Path $PSScriptRoot '../Resources/Az.Resources.psd1')_ in test_module.ps1

Through steps above, each module should be able to leverage the cmdlets in Az.Resources to setup/clean environment for test.

**Comment by markcowl** [comment]
@dolauli  Will this work when running tests in playback, or does the HttpPipeline mocking only apply to cmdlets in the module?  This would also create a dependency, which would require building the modules from a particular file structure.  For now, this would work, but I wonder how much work it would be to generate and hide the cmdlets we want and remaining self-contained, rather than leaving an issue we want to deal with later.
