### ISSUE TITLE
Get-AzVM Statuses null in Azure Automation

### ISSUE THREAD

**Issue by michal-staniszewski** [Azure/azure-powershell#10082]
## Description
Hi,
I use in a Powershell workflow runbook in my Azure Automation account to power up / shutdown VMs based on some tags.
When I want to get power state of a VM using Get-AzVm -Status the Code property is empty.
When I do the same on normal PS session in my laptop everything is fine.
I use Az.Compute v 2.5.0 in my automation account and local PS

## Steps to reproduce

Create Azure Automation runbook similar to this:

```powershell

workflow TestWorkflow
{
        [cmdletBinding()]
	Param
	(
		[Parameter(Mandatory=$true)]
		[string]$SubscriptionName
	)
        ...
        $vmName = 'TestVM'
        $rsgName = 'TestRsg'
                        $vmFullStatus = Get-AzVM -ResourceGroupName $rsgName -Name $vmName -Status
                        if ($vmFullStatus -eq $null)
                        {
                            Write-Output "vmFullStatus is null"
                        }
                        elseif ($vmFullStatus.Statuses -eq $null)
                        {
                            Write-Output "vmFullStatus.Statuses is null"
                        }
                        elseif ($vmFullStatus.Statuses.Count -ne 2)
                        {
                            Write-Output "vmFullStatus.Statuses has number of elements other thatn 2"
                        }
                        elseif ($vmFullStatus.Statuses[1] -eq $null)
                        {
                            Write-Output "vmFullStatus.Statuses[1] is null"
                        }
                        elseif ($vmFullStatus.Statuses[1].Code -eq $null)
                        {
                            Write-Output "vmFullStatus.Statuses[1].Code is null"
                        }
}

```
It returns:

vmFullStatus.Statuses[1].Code is null

## Environment data

```
Name                           Value                                                                                    
----                           -----                                                                                    
PSRemotingProtocolVersion      2.3                                                                                      
BuildVersion                   10.0.15063.726                                                                           
PSVersion                      5.1.15063.726                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
PSEdition                      Desktop                                                                                  
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
SerializationVersion           1.1.0.1                                                                                  

```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands                PSComputerName                
---------- -------    ----                                ----------------                --------------                
Script     1.6.2      Az.Accounts                         {Save-AzProfile, Register-Az... localhost                     
Script     1.3.2      Az.Automation                       {New-AzAutomationSchedule, S... localhost                     
Script     2.5.0      Az.Compute                          {Set-AzVM, Set-AzVMAEMExtens... localhost                     
Script     1.3.1      Az.KeyVault                         {Undo-AzKeyVaultCertificateR... localhost                     
Script     1.13.0     Az.Network                          {Get-AzAutoApprovedPrivateLi... localhost                     
Script     0.1.3      Az.Peering                          {Get-AzPeerAsn, Get-AzPeerin... localhost                     
Script     0.7.0      Az.Profile                          {Save-AzProfile, Clear-AzDef... localhost                     
Script     1.4.4      Az.RecoveryServices                 {Set-ASRAlertSetting, Get-Az... localhost                     
Script     1.6.2      Az.Resources                        {Remove-AzPolicySetDefinitio... localhost                     
Script     1.6.0      Az.Storage                          {New-AzStorageQueueSASToken,... localhost                     
Script     0.7.0      Az.Tags                             {Remove-AzTag, Get-AzTag, Ne... localhost                     
Script     5.3.0      Azure                               {Set-SSDeviceVolume, Import-... localhost                     
Script     4.6.1      Azure.Storage                       {Remove-AzureStorageCORSRule... localhost                     
    Directory: C:\Modules\Global


ModuleType Version    Name                                ExportedCommands                PSComputerName                
---------- -------    ----                                ----------------                --------------                
Manifest   1.1.0.0    AuditPolicyDsc                                                      localhost                     
Manifest   1.0.3      AzureRM.Automation                  {Get-AzureRmAutomationSchedu... localhost                     
Manifest   1.2.1      AzureRM.Compute                     {Get-AzureRmVMImageOffer, Ne... localhost                     
Manifest   1.0.3      AzureRM.Profile                     {Add-AzureRmAccount, Set-Azu... localhost                     
Manifest   1.0.3      AzureRM.Resources                   {Set-AzureRmResourceLock, Re... localhost                     
Manifest   1.0.3      AzureRM.Sql                         {New-AzureRmSqlElasticPool, ... localhost                     
Manifest   1.0.3      AzureRM.Storage                     {New-AzureRmStorageAccountKe... localhost                     
Manifest   5.0.0.0    ComputerManagementDsc                                               localhost                     
Script     0.2        GPRegistryPolicyParser              {Read-RegistryPolicies, Pars... localhost                     
Script     0.0        Microsoft.PowerShell.Core                                           localhost                     
Script     0.0        Microsoft.PowerShell.Diagnostics                                    localhost                     
Script     0.0        Microsoft.PowerShell.Management                                     localhost                     
Script     0.0        Microsoft.PowerShell.Security                                       localhost                     
Script     0.0        Microsoft.PowerShell.Utility                                        localhost                     
Script     0.0        Microsoft.WSMan.Management                                          localhost                     
Binary     1.0        Orchestrator.AssetManagement.Cmd... {Get-AutomationConnection, S... localhost                     
Manifest   2.9.0.0    PSDscResources                                                      localhost                     
Manifest   2.1.0.0    SecurityPolicyDsc                                                   localhost                     
Manifest   1.0        StateConfigCompositeResources                                       localhost                     
Manifest   1.1        xDSCDomainjoin                                                      localhost                     
Manifest   1.1.0.0    xPowerShellExecutionPolicy          {Get-TargetResource, Set-Tar... localhost                     
Manifest   1.1.0.0    xRemoteDesktopAdmin                                                 localhost                     
    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                PSComputerName                
---------- -------    ----                                ----------------                --------------                
Script     1.0.1      Microsoft.PowerShell.Operation.V... {Invoke-OperationValidation,... localhost                     
Binary     1.0.0.1    PackageManagement                   {Find-Package, Save-Package,... localhost                     
Script     3.4.0      Pester                              {New-Fixture, Set-TestInconc... localhost                     
Script     1.0.0.1    PowerShellGet                       {Unregister-PSRepository, Fi... localhost                     
Script     1.2        PSReadline                          {Set-PSReadlineOption, Get-P... localhost                     
    Directory: C:\Windows\system32\WindowsPowerShell\v1.0\Modules


ModuleType Version    Name                                ExportedCommands                PSComputerName                
---------- -------    ----                                ----------------                --------------                
Manifest   1.0.0.0    AppBackgroundTask                   {Enable-AppBackgroundTaskDia... localhost                     
Manifest   2.0.0.0    Appx                                {Add-AppxPackage, Move-AppxP... localhost                     
Manifest   2.0.0.0    BitsTransfer                        {Complete-BitsTransfer, Add-... localhost                     
Manifest   1.0.0.0    CimCmdlets                          {ncso, New-CimSessionOption,... localhost                     
Manifest   1.0        Defender                            {Remove-MpPreference, Remove... localhost                     
Manifest   1.0.0.0    DeliveryOptimization                {Get-DeliveryOptimizationPer... localhost                     
Manifest   1.0.0.0    DirectAccessClientComponents        {New-DAEntryPointTableItem, ... localhost                     
Script     3.0        Dism                                {Get-WindowsCapability, Remo... localhost                     
Manifest   1.0.0.0    DnsClient                           {Resolve-DnsName, Remove-Dns... localhost                     
Manifest   1.0.0.0    EventTracingManagement              {New-AutologgerConfig, Set-E... localhost                     
Manifest   2.0.0.0    International                       {Set-WinAcceptLanguageFromLa... localhost                     
Manifest   1.0.0.0    iSCSI                               {Disconnect-IscsiTarget, Unr... localhost                     
Script     1.0.0.0    ISE                                 {Import-IseSnippet, Get-IseS... localhost                     
Manifest   1.0.0.0    Kds                                 {Get-KdsConfiguration, Get-K... localhost                     
Manifest   1.0.1.0    Microsoft.PowerShell.Archive        {Compress-Archive, Expand-Ar... localhost                     
Manifest   3.0.0.0    Microsoft.PowerShell.Diagnostics    {New-WinEvent, Export-Counte... localhost                     
Manifest   3.0.0.0    Microsoft.PowerShell.Host           {Start-Transcript, Stop-Tran... localhost                     
Manifest   1.0.0.0    Microsoft.PowerShell.LocalAccounts  {nlg, nlu, Get-LocalGroup, N... localhost                     
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Remove-WmiObject, gin, Remo... localhost                     
Script     1.0        Microsoft.PowerShell.ODataUtils     Export-ODataEndpointProxy       localhost                     
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {Get-ExecutionPolicy, New-Fi... localhost                     
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {New-Object, Write-Debug, Se... localhost                     
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Test-WSMan, Set-WSManInstan... localhost                     
Manifest   1.0        MMAgent                             {Enable-MMAgent, Set-MMAgent... localhost                     
Manifest   1.0.0.0    MsDtc                               {Add-DtcClusterTMMapping, Ge... localhost                     
Manifest   2.0.0.0    NetAdapter                          {Set-NetAdapterPowerManageme... localhost                     
Manifest   1.0.0.0    NetConnection                       {Get-NetConnectionProfile, S... localhost                     
Manifest   1.0.0.0    NetEventPacketCapture               {Start-NetEventSession, New-... localhost                     
Manifest   2.0.0.0    NetLbfo                             {Set-NetLbfoTeam, Get-NetLbf... localhost                     
Manifest   1.0.0.0    NetNat                              {Get-NetNatExternalAddress, ... localhost                     
Manifest   2.0.0.0    NetQos                              {Remove-NetQosPolicy, Get-Ne... localhost                     
Manifest   2.0.0.0    NetSecurity                         {Rename-NetFirewallRule, Get... localhost                     
Manifest   1.0.0.0    NetSwitchTeam                       {Get-NetSwitchTeam, Add-NetS... localhost                     
Manifest   1.0.0.0    NetTCPIP                            {Set-NetRoute, Get-NetTCPSet... localhost                     
Manifest   1.0.0.0    NetworkConnectivityStatus           {Reset-NCSIPolicyConfigurati... localhost                     
Manifest   1.0.0.0    NetworkSwitchManager                {Enable-NetworkSwitchVlan, R... localhost                     
Manifest   1.0.0.0    NetworkTransition                   {Disable-NetNatTransitionCon... localhost                     
Manifest   1.0.0.0    PcsvDevice                          {Set-PcsvDeviceNetworkConfig... localhost                     
Manifest   1.0.0.0    PKI                                 {Get-CertificateAutoEnrollme... localhost                     
Manifest   1.0.0.0    PnpDevice                           {Disable-PnpDevice, Get-PnpD... localhost                     
Manifest   1.1        PrintManagement                     {Remove-Printer, Suspend-Pri... localhost                     
Script     3.0        Provisioning                        {Export-ProvisioningPackage,... localhost                     
Manifest   1.1        PSDesiredStateConfiguration         {Get-DscResource, Stop-DscCo... localhost                     
Script     1.0.0.0    PSDiagnostics                       {Enable-WSManTrace, Disable-... localhost                     
Binary     1.1.0.0    PSScheduledJob                      {Get-JobTrigger, Add-JobTrig... localhost                     
Manifest   2.0.0.0    PSWorkflow                          {nwsn, New-PSWorkflowSession... localhost                     
Manifest   1.0.0.0    PSWorkflowUtility                   Invoke-AsWorkflow               localhost                     
Manifest   1.0.0.0    ScheduledTasks                      {Export-ScheduledTask, Regis... localhost                     
Manifest   2.0.0.0    SecureBoot                          {Get-SecureBootUEFI, Get-Sec... localhost                     
Manifest   2.0.0.0    SmbShare                            {Get-SmbMapping, rksmba, gsm... localhost                     
Manifest   2.0.0.0    SmbWitness                          {Get-SmbWitnessClient, Move-... localhost                     
Manifest   1.0.0.0    StartLayout                         {Export-StartLayoutEdgeAsset... localhost                     
Manifest   2.0.0.0    Storage                             {New-StorageTier, Get-Storag... localhost                     
Manifest   2.0.0.0    TLS                                 {Enable-TlsCipherSuite, Disa... localhost                     
Manifest   1.0.0.0    TroubleshootingPack                 {Get-TroubleshootingPack, In... localhost                     
Manifest   2.0.0.0    TrustedPlatformModule               {Disable-TpmAutoProvisioning... localhost                     
Manifest   2.0.0.0    VpnClient                           {Set-VpnConnectionTriggerTru... localhost                     
Manifest   1.0.0.0    Wdac                                {Disable-WdacBidTrace, Add-O... localhost                     
Manifest   1.0.0.0    WindowsDeveloperLicense             {Show-WindowsDeveloperLicens... localhost                     
Script     1.0        WindowsErrorReporting               {Get-WindowsErrorReporting, ... localhost                     
Manifest   1.0.0.0    WindowsSearch                       {Get-WindowsSearchSetting, S... localhost                     
Manifest   1.0.0.0    WindowsUpdate                       Get-WindowsUpdateLog            localhost                     

```

## Debug output

```

```

## Error output

```

```

**Comment by michal-staniszewski** [comment]
More insights:

When the same code is run in Azure Automation not as Powershell Workflow but standard Powershell runbook the output of Get-AzVm -State is ok as expected.
Therefore something does not work when it's in a workflow and there's no statement in cmdlet docs about it.

**Comment by erich-wang** [comment]
@michal-staniszewski, could you please provide the following information:
- Provide debug stream, add the following statement before the Cmdlet that causes error
`$DebugPreference="Continue"`

**Comment by michal-staniszewski** [comment]
Hi @erich-wang 
Here you are:

a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:9:05:19 PM - GetAzureVMCommand begin processing with ParameterSet 
'DefaultParamSet'.
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:9:05:19 PM - using account id '<<CLIENT_ID>>'...
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[Common.Authentication]: Authenticating using Account: 
'<<CLIENT_ID>>', environment: 'AzureCloud', tenant: '4720ed5e-c545-46eb-99a5-958dd333e9f2'
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[Common.Authentication]: Authenticating using configuration values: 
Domain: '4720ed5e-c545-46eb-99a5-958dd333e9f2', Endpoint: 'https://login.microsoftonline.com/', ClientId: 
'1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 
'https://management.core.windows.net/', ValidateAuthority: 'True'
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Information: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file 
version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Information: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file 
version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Information: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: Client
	, Authority Host: login.microsoftonline.com
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Information: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/4720ed5e-c545-46eb-99a5-958dd333e9f2/
	Resource: https://management.core.windows.net/
	ClientId: <<CLIENT_ID>>
	CacheType: null
	Authentication Target: Client
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Verbose: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: Loading from cache.
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Verbose: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: Loading from cache.
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Information: 2019-09-24T21:05:19.9612342Z: 
00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 1 items to token cache.
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Verbose: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: Looking up cache for a token...
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Verbose: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: Looking up cache for a token...
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Information: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: An item matching the requested resource was found in the cache
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Information: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: An item matching the requested resource was found in the cache
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Information: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: 50.9211460966667 minutes left until token in cache expires
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Information: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: 50.9211460966667 minutes left until token in cache expires
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Information: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: A matching item (access token or refresh token or both) was found 
in the cache
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Information: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: A matching item (access token or refresh token or both) was found 
in the cache
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Information: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was 
returned: Expiration Time: 9/24/2019 9:56:15 PM +00:00
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[ADAL]: Information: 2019-09-24T21:05:19.9612342Z: 
02625ff2-e0fe-4a63-90da-d6ed8bd9c255 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was 
returned: Expiration Time: 9/24/2019 9:56:15 PM +00:00Access Token Hash: yw2DDPmi/QBphH30so9yEDy9w5M3rQ61UpePBcfEJ7M=
	 User id:
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:[Common.Authentication]: Checking token expiration, token expires 
'09/24/2019 21:56:15 +00:00' Comparing to '09/24/2019 21:05:19 +00:00' With threshold '00:05:00', calculated time until 
token expiry: '00:50:55.2687658'
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<<SUBSCRIPTION_ID>>/resourceGroups/<<TEST_RSG>>/pro
viders/Microsoft.Compute/virtualMachines/<<TEST_VM>>?$expand=instanceView&api-version=2019-03-01

Headers:
x-ms-client-request-id        : e04818b6-bbd5-41ae-9894-23dff01b464b
accept-language               : en-US

Body:
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/LowCostGet3Min;3997,Microsoft.Compute/LowCostGet30Min;31983
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 11c78af9-b82d-439a-afd2-9c5ea33df834
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11994
x-ms-correlation-request-id   : b724e392-51b4-43ae-92e0-286a25a7b058
x-ms-routing-request-id       : <<AZURE_REGION>>:20190924T210520Z:b724e392-51b4-43ae-92e0-286a25a7b058
X-Content-Type-Options        : nosniff
Date                          : Tue, 24 Sep 2019 21:05:19 GMT

Body:
{
  "name": "<<TEST_VM>>",
  "id": "/subscriptions/<<SUBSCRIPTION_ID>>/resourceGroups/<<TEST_RSG>>/providers/Microsoft.Co
mpute/virtualMachines/<<TEST_VM>>",
  "type": "Microsoft.Compute/virtualMachines",
  "location": "<<AZURE_REGION>>",
  "tags": {
    "Description": "<<VM_DESCRIPTION>>",
    "BA": "<<VM_BA>>",
    "Schedule": "{\"TzId\":\"W. Europe Standard 
Time\",\"0\":{\"S\":\"0\",\"E\":\"12\"},\"1\":{\"S\":\"0\",\"E\":\"0\"},\"2\": {\"S\":\"0\",\"E\":\"0\"},\"3\":{\"S\":\"
0\",\"E\":\"0\"},\"4\":{\"S\":\"0\",\"E\":\"0\"},\"5\":{\"S\":\"0\",\"E\":\"0\"},\"6\":{\"S\":\"0\",\"E\":\"0\"}}",
    "Schedule Description": "Run only on Sundays 00:00-12:00"
  },
  "properties": {
    "vmId": "<<VM_ID>>",
    "hardwareProfile": {
      "vmSize": "Standard_B2s"
    },
    "storageProfile": {
      "osDisk": {
        "osType": "Windows",
        "name": "PHYSICALDRIVE0-<<TEST_VM>>",
        "createOption": "Attach",
        "caching": "ReadWrite",
        "managedDisk": {
          "id": "/subscriptions/<<SUBSCRIPTION_ID>>/resourcegroups/<<TEST_RSG>>/providers/Micr
osoft.Compute/disks/PHYSICALDRIVE0-<<TEST_VM>>"
        }
      },
      "dataDisks": [
        {
          "lun": 0,
          "name": "PHYSICALDRIVE3-<<TEST_VM>>",
          "createOption": "Attach",
          "caching": "None",
          "managedDisk": {
            "id": "/subscriptions/<<SUBSCRIPTION_ID>>/resourcegroups/<<TEST_RSG>>/providers/Mi
crosoft.Compute/disks/PHYSICALDRIVE3-<<TEST_VM>>"
          },
          "toBeDetached": false
        },
        {
          "lun": 1,
          "name": "PHYSICALDRIVE4-<<TEST_VM>>",
          "createOption": "Attach",
          "caching": "None",
          "managedDisk": {
            "id": "/subscriptions/<<SUBSCRIPTION_ID>>/resourcegroups/<<TEST_RSG>>/providers/Mi
crosoft.Compute/disks/PHYSICALDRIVE4-<<TEST_VM>>"
          },
          "toBeDetached": false
        },
        {
          "lun": 3,
          "name": "PHYSICALDRIVE1-<<TEST_VM>>",
          "createOption": "Attach",
          "caching": "None",
          "managedDisk": {
            "id": "/subscriptions/<<SUBSCRIPTION_ID>>/resourcegroups/<<TEST_RSG>>/providers/Mi
crosoft.Compute/disks/PHYSICALDRIVE1-<<TEST_VM>>"
          },
          "toBeDetached": false
        },
        {
          "lun": 4,
          "name": "PHYSICALDRIVE2-<<TEST_VM>>",
          "createOption": "Attach",
          "caching": "None",
          "managedDisk": {
            "id": "/subscriptions/<<SUBSCRIPTION_ID>>/resourcegroups/<<TEST_RSG>>/providers/Mi
crosoft.Compute/disks/PHYSICALDRIVE2-<<TEST_VM>>"
          },
          "toBeDetached": false
        }
      ]
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "id": "/subscriptions/<<SUBSCRIPTION_ID>>/resourceGroups/<<TEST_RSG>>/providers/Micr
osoft.Network/networkInterfaces/<<TEST_VM>>cda1ad42-386a-4fee-b2ee-3ece0f84703e",
          "properties": {
            "primary": true
          }
        }
      ]
    },
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true,
        "storageUri": "https://<<STORAGE_ACCOUNT>>.blob.core.windows.net"
      }
    },
    "licenseType": "Windows_Server",
    "provisioningState": "Succeeded",
    "instanceView": {
      "disks": [
        {
          "name": "PHYSICALDRIVE0-<<TEST_VM>>",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "time": "2019-09-21T22:45:42.5142221+00:00"
            }
          ]
        },
        {
          "name": "PHYSICALDRIVE3-<<TEST_VM>>",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "time": "2019-09-21T22:45:42.5142221+00:00"
            }
          ]
        },
        {
          "name": "PHYSICALDRIVE4-<<TEST_VM>>",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "time": "2019-09-21T22:45:42.5142221+00:00"
            }
          ]
        },
        {
          "name": "PHYSICALDRIVE1-<<TEST_VM>>",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "time": "2019-09-21T22:45:42.5142221+00:00"
            }
          ]
        },
        {
          "name": "PHYSICALDRIVE2-<<TEST_VM>>",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "time": "2019-09-21T22:45:42.5142221+00:00"
            }
          ]
        }
      ],
      "bootDiagnostics": {
        "consoleScreenshotBlobUri": "https://<<STORAGE_ACCOUNT>>.blob.core.windows.net/bootdiagnostics-<<VMNAME0>>-5f91cbed-e
bc9-460e-95e5-1ca8d5b8fbb4/<<TEST_VM>>.<<VM_ID>>.screenshot.bmp",
        "serialConsoleLogBlobUri": "https://<<STORAGE_ACCOUNT>>.blob.core.windows.net/bootdiagnostics-<<VMNAME0>>-5f91cbed-eb
c9-460e-95e5-1ca8d5b8fbb4/<<TEST_VM>>.<<VM_ID>>.serialconsole.log"
      },
      "hyperVGeneration": "V1",
      "statuses": [
        {
          "code": "ProvisioningState/succeeded",
          "level": "Info",
          "displayStatus": "Provisioning succeeded",
          "time": "2019-09-21T22:45:42.5298483+00:00"
        },
        {
          "code": "PowerState/deallocated",
          "level": "Info",
          "displayStatus": "VM deallocated"
        }
      ]
    }
  }
}
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:AzureQoSEvent: CommandName - Get-AzVM; IsSuccess - True; Duration - 
00:00:00.8556780; Exception - ;
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:Finish sending metric.
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:9:05:20 PM - GetAzureVMCommand end processing.
a4b94be5-e7b5-410d-be5b-a8f6890c86d2:[localhost]:9:05:20 PM - GetAzureVMCommand end processing.

As you can see API returns all data but I cannot access it after Get-AzVm.

**Comment by hyonholee** [comment]
It seems that the inner properties are not serialized in Powershell workflow.   If you use InlineScript, it works.

    InlineScript {
        $vmName = 'TestVM';
        $rsgName = 'TestRsg';
        $vmFullStatus = Get-AzVM -ResourceGroupName $rsgName -Name $vmName -Status;
        if ($vmFullStatus -eq $null)
        {
           Write-Output "vmFullStatus is null"
        }
        elseif ($vmFullStatus.Statuses -eq $null)
        {
            Write-Output "vmFullStatus.Statuses is null"
        }
        elseif ($vmFullStatus.Statuses.Count -ne 2)
        {
            Write-Output "vmFullStatus.Statuses has number of elements other thatn 2"
        }
        elseif ($vmFullStatus.Statuses[1] -eq $null)
        {
            Write-Output "vmFullStatus.Statuses[1] is null"
        }
        elseif ($vmFullStatus.Statuses[1].Code -eq $null)
        {
            Write-Output "vmFullStatus.Statuses[1].Code is null"
        }
    }

**Comment by Drewm3** [comment]
Thanks @hyonholee. 

@michal-staniszewski, please let us know if this unblocks you, and we can close this issue?

**Comment by Drewm3** [comment]
Assuming this is resolved due to no response.
