### ISSUE TITLE
Add AADProfile property to Az.AKS Module

### ISSUE THREAD

**Issue by nopjmp** [Azure/azure-powershell#10080]
## Description of the new feature
AzCLI has the ability to reset and fetch the aadProfile information while I'm not able to find this in the Az module. These would allow easier automation of updating these credentials when the expire or if they have been compromised.

## Proposed implementation details (optional)
PSKubernetesCluster should have a AADProfile property that includes the information from the resource json as well as a new object PSContainerServiceAADProfile which contains the clientAppId, serverAppId, tenantId, and serverAppSecret if applicable (I'm not aware of a situation where this is non-null, but I haven't doc into the documentation for this).

**Comment by erich-wang** [comment]
Move this feature request to Az.AKS with generation mode

**Comment by erich-wang** [comment]
it is available at Az.Aks 4.0.0-preview
