### ISSUE TITLE
Set-AzDiagnosticSetting Resource-Specific mode flag

### ISSUE THREAD

**Issue by BrandonWhite-Altius** [Azure/azure-powershell#10101]
## Description of the new feature
As per the documentation for [diagnostic logs](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-logs-schema) and the [known limitation](https://docs.microsoft.com/en-gb/azure/azure-monitor/platform/diagnostic-logs-stream-log-store#known-limitation-column-limit-in-azurediagnostics) for the Azure Diagnostics table, the recommendation is to use Resource-Specific mode for resources that support it.
This is something that is not currently configurable by the [Set-AzDiagnosticSetting](https://docs.microsoft.com/en-us/powershell/module/az.monitor/set-azdiagnosticsetting) cmdlet.

## Proposed implementation details
Either to:
* Add a switch to the Set-AzDiagnosticSetting cmdlet that will turn on Resource-Specific mode
or 
* Add a new parameter to the Set-AzDiagnosticSetting cmdlet that takes the values "Default" or "Resource-Specific"

**Comment by Dalubash** [comment]
@nkiest Follow up on this diagnostic logs request.

**Comment by nkiest** [comment]
We are looking to fix this in the next two months. For now, you can use the REST API if you need a non-portal option. Sorry for the delay in shipping this.

**Comment by csmurthy** [comment]
Any ETA for the fix

**Comment by nkiest** [comment]
This has been merged into the latest powershell release. When that is published, it should have the property.

**Comment by nkiest** [comment]
It has been merged into the latest powershell (https://github.com/Azure/azure-powershell/pull/10248). It should be in the next release.
