### ISSUE TITLE
Automation Account can run 'Remove-AzServiceFabricClusterCertificate' but 'Add-AzServiceFabricClusterCertificate' returns 'Forbidden'

### ISSUE THREAD

**Issue by jzkornbluh** [Azure/azure-powershell#10105]
## Description

In a runbook, I can 'Connect-AzAccount' with a service principal, create certs in a key vault, and trigger our Service Fabric cluster to remove its secondary certificate... but when I try to 'Add-AzServiceFabricClusterCertificate' from the same runbook, I get a 'Forbidden' response.

Don't these two commands require the same permissions?

## Steps to reproduce
I run 'Connect-AzAccount' first, then I can 'Remove' the cert from the cluster... but I can't add one.

```powershell
$newcert = (Get-AzKeyVaultCertificate -VaultName $keyVaultName -Name $secondaryCertName)

Add-AzServiceFabricClusterCertificate -ResourceGroupName $clusterResourceGroupName -Name $clusterName -SecretIdentifier $newcert.SecretId -verbose
```

## Module versions

I do have some AzureRM modules that are imported into the automation account... could that be messing with things?

![image](https://user-images.githubusercontent.com/49572515/65554173-9e827800-dedd-11e9-9dfa-d07c0d3811ef.png)

## Error output

```
Add-AzServiceFabricClusterCertificate : Operation returned an invalid status code 'Forbidden'
At line:45 char:1
+ Add-AzServiceFabricClusterCertificate -ResourceGroupName $clusterReso ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzServiceFabricClusterCertificate], KeyVaultErrorException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceFabric.Commands.AddAzureRmServiceFabricClusterCertificate
 
```

**Comment by erich-wang** [comment]
@jzkornbluh , could you please provide the following info:
- List available modules and versions
`Get-Module -ListAvailable`
- Provide debug stream, set following env before running your cmdlets
`set $DebugPreference=''Continue`
- Provide error detail by running
`Resolve-AzError`

**Comment by erich-wang** [comment]
@jzkornbluh , could you please provide the info I listed above? We'll close the issue if we don't hear from you in 5 days.

**Comment by erich-wang** [comment]
@jzkornbluh , we close the issue since we don't hear from you long time, please file another issue if necessary, thanks.
