### ISSUE TITLE
Set-AzureRMWebApp returns "BadRequest" when setting AppSettings

### ISSUE THREAD

**Issue by bjossi-asitis** [Azure/azure-powershell#10100]
Set-AzureRMWebApp -Name [Appname] -ResourceGroupName [ResourceGroup] -AppSettings [AppSettings] results in 

Set-AzureRMWebApp : Operation returned an invalid status code 'BadRequest'
At C:\Dev\OneTfs\src\Asitis\PowerShell\main\AzureScript\AFSProduction\Set-AppSettings.ps1:108 char:17
+ ...   $result = Set-AzureRMWebApp -Name $appFullName -ResourceGroupName $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmWebApp], DefaultErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.SetAzureWebAppCmdlet

This error message appears when i use AzureRM.Websites version 5.2.0 and 5.1.0. If I use 5.0.1 then it works. I have not tried all versions between 5.0.1 and 5.2.0

If I run it with -Debug it complains about IpSecurity something. If needed I could run it again with -Debug and provide the whole output

## Steps to reproduce

```powershell

```

AzureRM.Websites 5.2.0

```powershell

```

## Debug output

```

```

```

```

**Comment by erich-wang** [comment]
@bjossi-asitis , could you please try Set-AzWebApp in latest Az 2.7?

**Comment by erich-wang** [comment]
@bjossi-asitis , could you please try Set-AzWebApp in latest Az 2.7? We'll close the issue if don't hear from you in 5 days, thanks.

**Comment by bjossi-asitis** [comment]
Sorry. Because I managed to find a workaround I had to put this on hold. I will try to do this test within 5 days
/Björn

**Comment by bjossi-asitis** [comment]
Hi
Now I have tested using Set-AzWebApp (Az 2.7) and with the -AppSettings parameter and it works fine.
/Björn
