### ISSUE TITLE
Set-AzureVNetConfig gives poor error message with LocalNetworkSite addressprefix

### ISSUE THREAD

**Issue by theanandramakrishna** [Azure/azure-powershell#1010]
Create an express route and VNET config.
In the VNET config, set the LocalNetworkSite addressprefix to the following:
    <LocalNetworkSites>
      <LocalNetworkSite name="foo">
        <AddressSpace>
          <AddressPrefix>10.0.0.0/8</AddressPrefix>
        </AddressSpace>
      </LocalNetworkSite>
    </LocalNetworkSites>

Also set the VirtualNetworkSite address prefix to something that overlaps with the above:
      <VirtualNetworkSite name="bar" Location="West US">
        <AddressSpace>
          <AddressPrefix>10.107.38.64/26</AddressPrefix>
          <AddressPrefix>10.107.50.208/28</AddressPrefix>
        </AddressSpace>

Now call Set-AzureVNetConfig.

Result: The error message is "BadRequest: IP address prefix is not valid"

The error message should be something more descriptive like telling people that it's overlapping and give them prescriptive instructions on how to fix it.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
