### ISSUE TITLE
Changes to Profile cmdlets (Select-AzProfile, Get-AzProfile) 

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#10116]
## Description
The Profile cmdlets should use all available profiles in deciding which profiles to choose from

- [ ] Create a format for a profile metadata list
- [ ] Create automation to generate Profile metadata list from checked-in profiles, triggered on new check-ins
- [ ] Update `Select-AzProfile` to get the list of allowed profiles from this metadata.
- [ ] Add a dynamic ValidateSet to Select-AzProfile to only allow known profiles from the list
- [ ] Update Get-AzProfile to read the available profiles from the list
- [ ] Update generated module definition script (.psm1) to choose the 'best fit' profile if the selected profile is not available, and print a warnign when there is not an exact match:
  - [ ] If there is an exact match for the selected profile, use it
  - [ ] If there is a profile in the module that is within the same family (latest, sovereign, stack) that is typographically '<' the chosen profile, select it and print a warning
  - [ ] Otherwise, select the default (latest) profile and print a warning
  - warning 'We could not find an exact match for the selected profile ``<profile>`` using profile ``<loaded-profile>`` instead

**Comment by dingmeng-xue** [comment]
Close this issue because we remove profile related cmdlet due to priority.
