### ISSUE TITLE
AzADApplication - Ability to set ReplyUri Type

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-powershell#10127]
## Description of the new feature
Currently, in the Azure Portal, users are able to set the Type of Redirect URI between `Web` and `Public client/native (mobile & desktop)`. 

It would be awesome to have this as part of the cmdlet (`New-AzADApplication`) and (`Update-AzADApplication`) to allow users to automate this setting.

![image](https://user-images.githubusercontent.com/4549796/65747900-37f79700-e135-11e9-823f-c2fad5b5c36c.png)

**Comment by msJinLei** [comment]
@wahyuen Thanks for your proposal. We will investigate it and let you know if any update.

**Comment by SeidChr** [comment]
does it make any difference whether you set up the uris as application or web redirect uris?

**Comment by VeryEarly** [comment]
Hi it is supported in latest Az.Resources: https://www.powershellgallery.com/packages/Az.Resources/6.2.0
please see help: https://learn.microsoft.com/en-us/powershell/module/az.resources/new-azadapplication?view=azps-8.3.0
