### ISSUE TITLE
StorageToolsPath in Common.Netcore.Dependencies.targets causing build errors

### ISSUE THREAD

**Issue by jarango** [Azure/azure-powershell#10154]
## Description

A missing slash is causing build errors when the building the powershell repo on developer's local machine. Please make the following change:

diff --git a/tools/Common.Netcore.Dependencies.targets b/tools/Common.Netcore.Dependencies.targets
index 93528a0749..e6a6d4bbd4 100644
--- a/tools/Common.Netcore.Dependencies.targets
+++ b/tools/Common.Netcore.Dependencies.targets
@@ -32,7 +32,7 @@
     <PackageReference Include="PowerShellStandard.Library" Version="5.1.0" PrivateAssets="All" />
   </ItemGroup>
   <PropertyGroup>
-    <StorageToolsPath>$(NugetPackageRoot)microsoft.azure.powershell.storage\1.3.2-preview\tools\</StorageToolsPath>
+    <StorageToolsPath>$(NugetPackageRoot)\microsoft.azure.powershell.storage\1.3.2-preview\tools\</StorageToolsPath>
   </PropertyGroup>
   <ItemGroup Condition="'$(OmitJsonPackage)' != 'true'">
     <PackageReference Include="Newtonsoft.Json" Version="10.0.3"/>

**Comment by markcowl** [comment]
I believe that all of the defined variables have a trailing slash, this is generally the pattern we use for most build path variables.

**Comment by markcowl** [comment]
And this is a public repo, if you would like to make this change, please submit a PR.  Closing.
