### ISSUE TITLE
Parsing Errors when executing New-AzVirtualNetworkGatewayConnection command

### ISSUE THREAD

**Issue by Osmidon** [Azure/azure-powershell#10150]
I'm trying to create a new IKEV2 IPSec tunnel using the following MS article:
https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-ipsecikepolicy-rm-powershell

I get to the part where I execute the following command:
New-AzVirtualNetworkGatewayConnection -Name Azure-WEU-US01-IPSec-VPN -ResourceGroupName $RG1 -VirtualNetworkGateway1 $vnetgw1 -LocalNetworkGateway2 $lngw1 -Location $Location1 -ConnectionType IPsec -UsePolicyBasedTrafficSelectors $True -IpsecPolicies $ipsecpolicy6 -SharedKey 'XXXXXXXXXXXXX'

But then get the following parsing error:
New-AzVirtualNetworkGatewayConnection : Cannot parse the request.
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: InvalidRequestFormat
ErrorMessage: Cannot parse the request.
Additional details:
    Code: InvalidJson
    Message: Could not find member 'trafficSelectorPolicies' on object of type 'VirtualNetworkGatewayConnectionProperties'. P
ath 'properties.trafficSelectorPolicies', line 75, position 30.
OperationID : 95142eb8-7da3-467e-8686-30de8cdeb19d
At line:1 char:1
+ New-AzVirtualNetworkGatewayConnection -Name $Connection16 -ResourceGr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [New-AzVirtualNetworkGatewayConnection], NetworkCloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionCommand

This is the second connection I'm trying to create. The first one around 2-3 months ago was successful and did not present this error. Is there a bug in the current Azure CLI?

**Comment by Osmidon** [comment]
I even tried creating the connection via the Azure GUI which created the connection successfully. Now I'm trying to set the IPSec Policy afterwards using Set-AzVirtualNetworkGatewayConnection and get the following same error:

PS C:\> Set-AzVirtualNetworkGatewayConnection -VirtualNetworkGatewayConnection $vnetgwc1 -IpsecPolicies $ipsecpolicy6

Confirm
Are you sure you want to overwrite resource 'Azure-WEU-US01-IPSec-VPN'
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): Y
Set-AzVirtualNetworkGatewayConnection : Cannot parse the request.
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: InvalidRequestFormat
ErrorMessage: Cannot parse the request.
Additional details:
    Code: InvalidJson
    Message: Could not find member 'trafficSelectorPolicies' on object of type 'VirtualNetworkGatewayConnectionProperties'. P
ath 'properties.trafficSelectorPolicies', line 34, position 30.
OperationID : 132beb32-a3d6-444c-8288-485674d92976
At line:1 char:1
+ Set-AzVirtualNetworkGatewayConnection -VirtualNetworkGatewayConnectio ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzVirtualNetworkGatewayConnection], NetworkCloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.SetAzureVirtualNetworkGatewayConnectionCommand

**Comment by msJinLei** [comment]
@Osmidon Could you provide the following information? Thanks

## Environment data

 Please run $PSVersionTable and paste the output in the below code block

```

```

## Module versions

Please run (Get-Module  -ListAvailable) and paste the output in the below code block

```powershell

```

## Debug output

 Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block

```

```

## Error output

 Please run Resolve-AzError and paste the output in the below code block

```

```

**Comment by Osmidon** [comment]
Environment data
Please run $PSVersionTable and paste the output in the below code blockName                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 4.15.0-1059-azure #64-Ubuntu SMP Fri Sep 13 17:02:44 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Module versions
Please run (Get-Module -ListAvailable) and paste the output in the below code block
PS Azure:\> Get-Module -ListAvailable


    Directory: /usr/local/share/powershell/Modules

ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     2.7.0      Az                                  Core,Desk
Script     1.6.2      Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.0.1      Az.Advisor                          Core,Desk {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Disable-AzAdvisorRecommendation, Get-AzAdvisorConfiguration…}
Script     1.0.2      Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential…}
Script     1.1.1      Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAnalysisServicesServer…}
Script     1.3.1      Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagementRegion, Add-AzApiManagementUserToGroup…}
Script     1.0.2      Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Set-AzApplicationInsightsPricingPlan…}
Script     1.3.3      Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDscNodeConfiguration…}
Script     1.1.1      Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, New-AzBatchAccount…}
Script     1.0.1      Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget…}
Script     1.3.1      Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile…}
Script     1.2.1      Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSku, Get-AzCognitiveServicesAccountType…}
Script     2.6.0      Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet…}
Script     1.0.1      Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}
Script     1.1.0      Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegistry…}
Script     1.3.0      Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2…}
Script     1.0.1      Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalyticsCatalogCredential, Set-AzDataLakeAnalyticsCatalogCredential…}
Script     1.2.2      Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreFirewallRule, Set-AzDataLakeStoreTrustedIdProvider…}
Script     1.0.1      Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifactSource, Set-AzDeploymentManagerArtifactSource, Remove-AzDeploymentManagerArtifactSource…}
Script     1.0.0      Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy…}
Script     1.1.1      Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet…}
Script     1.2.2      Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey…}
Script     1.4.0      Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace…}
Script     1.1.1      Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoor…}
Script     0.10.6     Az.GuestConfiguration               Core,Desk {Get-AzVMGuestPolicyStatus, Get-AzVMGuestPolicyStatusHistory}
Script     2.0.2      Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMapReduceJobDefinition…}
Script     1.3.0      Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob…}
Script     1.3.1      Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultCertificateOperation…}
Script     1.3.1      Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConfiguration, Get-AzIntegrationAccountCallbackUrl…}
Script     1.1.1      Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Remove-AzMlCommitmentPlan…}
Script     1.0.1      Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, New-AzManagedServicesAssignment, Remove-AzManagedServicesAssignment, Get-AzManagedServicesDefinition…}
Script     1.0.1      Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.0      Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaServiceKey, Get-AzMediaServiceNameAvailability…}
Script     1.3.0      Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile…}
Script     1.14.0     Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplicationGatewayAuthenticationCertificate, Remove-AzAppl…
Script     1.1.0      Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-AzNotificationHubListKey, Get-AzNotificationHubPNSCredential…}
Script     1.3.3      Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Disable-AzOperationalInsightsLinuxCustomLogCollection, Disable-AzOp…
Script     1.1.3      Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation…}
Script     1.1.0      Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessKey, Get-AzPowerBIWorkspace…}
Script     1.4.5      Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecoveryServicesVault…}
Script     1.1.0      Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-AzRedisCachePatchSchedule…}
Script     1.0.2      Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace…}
Script     1.7.0      Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment…}
Script     1.4.0      Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNamespace…}
Script     1.2.0      Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, Add-AzServiceFabricNode…}
Script     1.1.0      Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey…}
Script     1.14.2     Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseUpgradeHi…
Script     1.7.0      Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey…}
Script     1.2.0      Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncService, Get-AzStorageSyncService, Remove-AzStorageSyncService…}
Script     1.0.0      Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFunction, Remove-AzStreamAnalyticsFunction…}
Script     1.0.2      Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Remove-AzTrafficManagerCustomH…
Script     1.4.2      Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan…}
Script     0.0.0.10   AzureAD.Standard.Preview            Desk      {Set-AzureADUserExtension, Get-AzureADUserMembership, Get-AzureADDeviceRegisteredOwner, Remove-AzureADDevice…}
Script     0.9.3      AzurePSDrive                        Desk
Script     17.0.2985… EXOPSSessionConnector               Desk      Connect-EXOPSSession
Manifest   1.0.726    MicrosoftPowerBIMgmt                Desk
Binary     1.0.726    MicrosoftPowerBIMgmt.Admin          Desk      {Add-PowerBIEncryptionKey, Get-PowerBIEncryptionKey, Get-PowerBIWorkspaceEncryptionStatus, Switch-PowerBIEncryptionKey…}
Binary     1.0.726    MicrosoftPowerBIMgmt.Capacities     Desk      Get-PowerBICapacity
Binary     1.0.726    MicrosoftPowerBIMgmt.Data           Desk      {Add-PowerBIDataset, Set-PowerBITable, New-PowerBIDataset, New-PowerBITable…}
Binary     1.0.726    MicrosoftPowerBIMgmt.Profile        Desk      {Connect-PowerBIServiceAccount, Disconnect-PowerBIServiceAccount, Invoke-PowerBIRestMethod, Get-PowerBIAccessToken…}
Binary     1.0.726    MicrosoftPowerBIMgmt.Reports        Desk      {Get-PowerBIReport, New-PowerBIReport, Export-PowerBIReport, Get-PowerBIDashboard…}
Binary     1.0.726    MicrosoftPowerBIMgmt.Workspaces     Desk      {Get-PowerBIWorkspace, Get-PowerBIWorkspaceMigrationStatus, Add-PowerBIWorkspaceUser, Remove-PowerBIWorkspaceUser…}
Binary     1.0.13     MicrosoftTeams                      Desk      {Get-CsBatchPolicyAssignmentOperation, Invoke-CsBatchPolicyAssignment}
Script     0.9.3      PSCloudShellUtility                 Desk      {Enter-AzVM, Get-AzCommand, Invoke-AzVMCommand, Enable-AzVMPSRemoting…}
Binary     0.8.1      SHiPS                               Desk
Script     21.1.18147 SqlServer                           Desk      {Add-RoleMember, Add-SqlAvailabilityDatabase, Add-SqlAvailabilityGroupListenerStaticIp, Add-SqlAzureAuthenticationContext…}

    Directory: /opt/microsoft/powershell/6/Modules

ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Manifest   1.2.3.0    Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   6.1.0.0    Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   6.1.0.0    Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty, Join-Path…}
Manifest   6.1.0.0    Microsoft.PowerShell.Security       Core      {Get-Credential, Get-ExecutionPolicy, Set-ExecutionPolicy, ConvertFrom-SecureString…}
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alias, Import-Alias, New-Alias…}
Script     1.3.2      PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource…}
Script     2.1.3      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability…}
Script     0.0        PSDesiredStateConfiguration         Desk      {Generate-VersionInfo, Set-PSMetaConfigDocInsProcessedBeforeMeta, Get-PSMetaConfigurationProcessed, Get-PSMetaConfigDocumentInstVersionInfo…}
Script     2.0.0      PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineKeyHandler, Get-PSReadLineOption…}
Binary     1.1.2      ThreadJob                           Desk      Start-ThreadJob

Debug output
Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block

DEBUG: >> MakePath([Az.Network, New-AzVirtualNetworkGatewayConnection])
DEBUG: << MakePath([Az.Network, New-AzVirtualNetworkGatewayConnection])
DEBUG: 8:32:57 AM - NewAzureVirtualNetworkGatewayConnectionCommand begin processing with ParameterSet 'SetByResource'.
DEBUG: 8:32:57 AM - using account id 'MSI@50342'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'MSI@50342', environment: 'AzureCloud', tenant: 'REMOVED'
DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
DEBUG: Checking Cache request http://localhost:50342/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01
DEBUG: Cache Hit
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/REMOVED/resourceGroups/REMOVED/providers/Microsoft.Network/connections/REMOVED?api-version=2019-07-01

Headers:
x-ms-client-request-id        : REMOVED
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : d95deceb-0b67-46fb-b533-8d5f2cd85fdd
x-ms-correlation-request-id   : dc9af7d3-ddfb-48db-8cd2-8d3026cae4b9
x-ms-arm-service-request-id   : 5e8e37c5-6df6-4b4a-b0c2-df77e7ed2bee
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-routing-request-id       : WESTEUROPE:20190930T083257Z:dc9af7d3-ddfb-48db-8cd2-8d3026cae4b9
X-Content-Type-Options        : nosniff
Date                          : Mon, 30 Sep 2019 08:32:57 GMT

Body:
{
  "name": "REMOVED",
  "id": "/subscriptions/REMOVED/resourceGroups/REMOVED/providers/Microsoft.Network/connections/REMOVED",
  "etag": "W/\"c11a0593-e567-45f6-9f16-6cfd95a9e5cc\"",
  "type": "Microsoft.Network/connections",
  "location": "westeurope",
  "properties": {
    "provisioningState": "Succeeded",
    "resourceGuid": "REMOVED",
    "virtualNetworkGateway1": {
      "id": "/subscriptions/REMOVED/resourceGroups/REMOVED/providers/Microsoft.Network/virtualNetworkGateways/REMOVED"
    },
    "localNetworkGateway2": {
      "id": "/subscriptions/REMOVED/resourceGroups/REMOVED/providers/Microsoft.Network/localNetworkGateways/REMOVED"
    },
    "connectionType": "IPsec",
    "connectionProtocol": "IKEv2",
    "routingWeight": 0,
    "sharedKey": "REMOVED",
    "enableBgp": false,
    "usePolicyBasedTrafficSelectors": false,
    "ipsecPolicies": [],
    "connectionStatus": "Connecting",
    "ingressBytesTransferred": 0,
    "egressBytesTransferred": 0,
    "expressRouteGatewayBypass": false
  }
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/REMOVED/resourceGroups/REMOVED/providers/Microsoft.Network/connections/REMOVED?api-version=2019-07-01

Headers:
x-ms-client-request-id        : REMOVED
Accept-Language               : en-US

Body:
{
  "properties": {
    "virtualNetworkGateway1": {
      "properties": {
        "ipConfigurations": [
          {
            "properties": {
              "privateIPAllocationMethod": "Dynamic",
              "subnet": {
                "id": "/subscriptions/REMOVED/resourceGroups/REMOVED/providers/Microsoft.Network/virtualNetworks/REMOVED/subnets/GatewaySubnet"
              },
              "publicIPAddress": {
                "id": "/subscriptions/REMOVED/resourceGroups/REMOVED/providers/Microsoft.Network/publicIPAddresses/REMOVED"
              }
            },
            "name": "default",
            "etag": "W/\"REMOVED\"",
            "id": "/subscriptions/REMOVED/resourceGroups/REMOVED/providers/Microsoft.Network/virtualNetworkGateways/REMOVED/ipConfigurations/default"
          }
        ],
        "gatewayType": "Vpn",
        "vpnType": "RouteBased",
        "enableBgp": false,
        "activeActive": false,
        "sku": {
          "name": "Standard",
          "tier": "Standard",
          "capacity": 2
        },
        "bgpSettings": {
          "asn": 65515,
          "bgpPeeringAddress": "REMOVED",
          "peerWeight": 0
        },
        "resourceGuid": "REMOVED"
      },
      "etag": "W/\"REMOVED\"",
      "id": "/subscriptions/REMOVED/resourceGroups/REMOVED/providers/Microsoft.Network/virtualNetworkGateways/REMOVED",
      "location": "westeurope",
      "tags": {}
    },
    "localNetworkGateway2": {
      "properties": {
        "localNetworkAddressSpace": {
          "addressPrefixes": [
            "REMOVED",
            "REMOVED"
          ]
        },
        "gatewayIpAddress": "REMOVED",
        "resourceGuid": "REMOVED"
      },
      "etag": "W/\"REMOVED\"",
      "id": "/subscriptions/REMOVED/resourceGroups/REMOVED/providers/Microsoft.Network/localNetworkGateways/REMOVED",
      "location": "westeurope",
      "tags": {}
    },
    "connectionType": "IPsec",
    "routingWeight": 0,
    "sharedKey": "REMOVED",
    "enableBgp": false,
    "usePolicyBasedTrafficSelectors": true,
    "ipsecPolicies": [
      {
        "saLifeTimeSeconds": 14400,
        "saDataSizeKilobytes": 102400000,
        "ipsecEncryption": "AES256",
        "ipsecIntegrity": "SHA256",
        "ikeEncryption": "AES256",
        "ikeIntegrity": "SHA384",
        "dhGroup": "DHGroup24",
        "pfsGroup": "None"
      }
    ],
    "trafficSelectorPolicies": [],
    "expressRouteGatewayBypass": false
  },
  "location": "westeurope"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : e889f019-7b84-4b98-8f96-1423ff3f1129
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : d29125c2-2e9e-4f53-887e-6191c910df97
x-ms-routing-request-id       : WESTEUROPE:20190930T083304Z:d29125c2-2e9e-4f53-887e-6191c910df97
X-Content-Type-Options        : nosniff
Date                          : Mon, 30 Sep 2019 08:33:03 GMT

Body:
{
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "InvalidJson",
        "message": "Could not find member 'trafficSelectorPolicies' on object of type 'VirtualNetworkGatewayConnectionProperties'. Path 'properties.trafficSelectorPolicies', line 75, position 30."
      }
    ]
  }
}


New-AzVirtualNetworkGatewayConnection : Cannot parse the request.
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: InvalidRequestFormat
ErrorMessage: Cannot parse the request.
Additional details:
    Code: InvalidJson
    Message: Could not find member 'trafficSelectorPolicies' on object of type 'VirtualNetworkGatewayConnectionProperties'. Path 'properties.trafficSelectorPolicies', line 75, position 30.
OperationID : e889f019-7b84-4b98-8f96-1423ff3f1129
At line:1 char:1
+ New-AzVirtualNetworkGatewayConnection -Name $azgwc1 -ResourceGroupNam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [New-AzVirtualNetworkGatewayConnection], NetworkCloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionCommand

DEBUG: AzureQoSEvent: CommandName - New-AzVirtualNetworkGatewayConnection; IsSuccess - False; Duration - 00:00:01.3511099; Exception - Microsoft.Azure.Commands.Network.Common.NetworkCloudException: Cannot parse the request.
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: InvalidRequestFormat
ErrorMessage: Cannot parse the request.
Additional details:
    Code: InvalidJson
    Message: Could not find member 'trafficSelectorPolicies' on object of type 'VirtualNetworkGatewayConnectionProperties'. Path 'properties.trafficSelectorPolicies', line 75, position 30.
OperationID : e889f019-7b84-4b98-8f96-1423ff3f1129 ---> Microsoft.Rest.Azure.CloudException: Cannot parse the request.
   at Microsoft.Azure.Management.Network.VirtualNetworkGatewayConnectionsOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String virtualNetworkGatewayConnectionName, VirtualNetworkGatewayConnection parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Network.VirtualNetworkGatewayConnectionsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String virtualNetworkGatewayConnectionName, VirtualNetworkGatewayConnection parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Network.VirtualNetworkGatewayConnectionsOperationsExtensions.CreateOrUpdateAsync(IVirtualNetworkGatewayConnectionsOperations operations, String resourceGroupName, String virtualNetworkGatewayConnectionName, VirtualNetworkGatewayConnection parameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Network.VirtualNetworkGatewayConnectionsOperationsExtensions.CreateOrUpdate(IVirtualNetworkGatewayConnectionsOperations operations, String resourceGroupName, String virtualNetworkGatewayConnectionName, VirtualNetworkGatewayConnection parameters)
   at Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionCommand.CreateVirtualNetworkGatewayConnection()
   at Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionCommand.<>c__DisplayClass80_0.<Execute>b__0()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force, String continueMessage, String processMessage, String target, Action action, Func`1 useShouldContinue)
   at Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionCommand.Execute()
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 8:33:05 AM - NewAzureVirtualNetworkGatewayConnectionCommand end processing.
DEBUG: 8:33:05 AM - NewAzureVirtualNetworkGatewayConnectionCommand end processing.

Error output
Please run Resolve-AzError and paste the output in the below code block

HistoryId: 14
RequestId      :
Message        : Cannot parse the request.
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: InvalidRequestFormat
                 ErrorMessage: Cannot parse the request.
                 Additional details:
                     Code: InvalidJson
                     Message: Could not find member 'trafficSelectorPolicies' on object of type 'VirtualNetworkGatewayConnectionProperties'. Path 'properties.trafficSelectorPolicies', line 75, position 30.
                 OperationID : eb3709c1-a73e-4f8c-ae99-e8590d533a3d
ServerMessage  :
ServerResponse :
RequestMessage :
InvocationInfo : {New-AzVirtualNetworkGatewayConnection}
Line           : New-AzVirtualNetworkGatewayConnection -Name $azgwc1 -ResourceGroupName $RSG1 -VirtualNetworkGateway1 $vnetgw1 -LocalNetworkGateway2 $lgw6 -Location $Location1 -ConnectionType IPsec -UsePolicyBasedTrafficSelectors $True
                 -IpsecPolicies $ipsecpolicy6 -SharedKey 'XXXXXXXXXXXXXXX'
Position       : At line:1 char:1
                 + New-AzVirtualNetworkGatewayConnection -Name $azgwc1 -ResourceGroupNam ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 14

**Comment by inderjeetwadhwa** [comment]
I am also facing same issue. Any solution found ?

**Comment by number213** [comment]
@ejdelrio could you please take a look?

**Comment by radwiv** [comment]
This should be fixed now. Can you please recheck and confirm.
