### ISSUE TITLE
Azure PowerShell for Key Vault misses bypass parameter, present on CLI

### ISSUE THREAD

**Issue by v-rasaa** [Azure/azure-powershell#10156]
PowerShell module does not allow the creation of Key Vault with Bypass or to add IP Ranges or IP rules during creation as parameter. The command for creating a new key vault does not have a parameter that can be added in order to assign a IP Range, this is by default but if Customer uses CLI it gives him the option to add a Bypass but not for IP rules or Vnet which customer is trying to implement. The situation in here is that customer has an Azure policy that enforces this behavior and he can not turn it off.
why I can not use PowerShell to achieve his goal and why PowerShell does not have the same Bypass option as CLI?
PowerShell for creating a new Key Vault
https://docs.microsoft.com/en-us/powershell/module/az.keyvault/new-azkeyvault?view=azps-2.7.0#targetText=Enables%20the%20Azure%20disk%20encryption,keys%20from%20this%20key%20vault.&targetText=Enables%20Azure%20Resource%20Manager%20to,referenced%20in%20a%20template%20deployment.&targetText=Specifies%20the%20Azure%20region%20in%20which%20to%20create%20the%20key%20vault.
Cli for creating a new key Vault https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az-keyvault-create

**Comment by sebansal** [comment]
@msfcolombo is it resolved or persisting?

**Comment by sebansal** [comment]
Issue was on 2.6 of Azure powershell. 4.5 has bypass parameter.
Closing.
