### ISSUE TITLE
Get-AzBgpServiceCommunity is not returning any ip range

### ISSUE THREAD

**Issue by omerzubair** [Azure/azure-powershell#10160]
## Description
Takes a long time to respond and does not return anything. 
I have tried on Cloud Shell, Azure Automation accounts and also 

## Steps to reproduce

```powershell
Get-AzBgpServiceCommunity | where Name -In ('AzureAustraliaEast','AzureAustraliaSoutheast','AzureAustraliaCentral','AzureAustraliaCentral2')
```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output
Get-AzBgpServiceCommunity | where Name -In ('AzureAustraliaEast','AzureAustraliaSoutheast','AzureAustraliaCentral','AzureAustraliaCentral2')
Get-AzBgpServiceCommunity : A task was canceled.
At line:1 char:1
+ Get-AzBgpServiceCommunity | where Name -In ('AzureAustraliaEast','Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzBgpServiceCommunity], TaskCanceledException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureBgpServiceCommunityCommand

```

```

## Error output

```

```

**Comment by number213** [comment]
@dedhar @vinayada1 could you please take a look? I had the same issue last week, Get-AzBgpServiceCommunity failed with 429 and only after a few retries I was able to get it to work

**Comment by omerzubair** [comment]
Hi @dedhar  & @vinatara 
This is another error:

Get-AzBgpServiceCommunity : A retryable error occurred. StatusCode: 429 ReasonPhrase: ErrorCode: RetryableError ErrorMessage: A retryable error occurred. OperationID : --- At line:243 char:18 + $BGPIP = Get-AzBgpServiceCommunity | where Name -In ... + ~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Get-AzBgpServiceCommunity], NetworkCloudException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureBgpServiceCommunityCommand

**Comment by omerzubair** [comment]
This is the third type of error in Automation accounts:

Get-AzBgpServiceCommunity : Subscription ch65--d------4fc0-adef-893---- is not registered with NRP. StatusCode: 409 ReasonPhrase: Conflict ErrorCode: SubscriptionNotRegistered ErrorMessage: Subscription ch65--d------4fc0-adef-893--- is not registered with NRP. OperationID : c717eca5--41c0-882e-At line:243 char:18 + $BGPIP_AUEA = Get-AzBgpServiceCommunity | where Name -In ... + ~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Get-AzBgpServiceCommunity], NetworkCloudException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureBgpServiceCommunityCommand

**Comment by omerzubair** [comment]
Get-AzBgpServiceCommunity : The 'Get-AzBgpServiceCommunity' command was found in the module 'Az.Network', but the module could not be loaded. For more information, run 'Import-Module Az.Network'. At line:97 char:12 + $BGPIP = Get-AzBgpServiceCommunity | where Name -In ($MS_Regi ... + ~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : ObjectNotFound: (Get-AzBgpServiceCommunity:String) [], CommandNotFoundException + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

**Comment by omerzubair** [comment]
In Azure Automation Accounts I am getting this error intermittently:

Get-AzBgpServiceCommunity : The 'Get-AzBgpServiceCommunity' command was found in the module 'Az.Network', but the module could not be loaded. For more information, run 'Import-Module Az.Network'. At line:97 char:12 + $BGPIP = Get-AzBgpServiceCommunity | where Name -In ($MS_Regi ... + ~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : ObjectNotFound: (Get-AzBgpServiceCommunity:String) [], CommandNotFoundException + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

**Comment by omerzubair** [comment]
Hi @number213, @dedhar & @vinatara,

I needed an alternative in order to secure my resources with MS ranges therefore i called the following API in powershell.

https://docs.microsoft.com/en-us/rest/api/expressroute/BgpServiceCommunities/List 

and that is also flaky and spits out the following error 8/10 times.

Invoke-RestMethod : {"Error":{"Details":[{"Code":"**GatewayError**","Message":"Error occurred in resource provider infrastructure services.","Target":null}],"InnerError":null,"Code":"RetryableError","Message":"A retryable error occurred.","Target":null}} At line:47 char:13 + $response = Invoke-RestMethod -Method Get -Uri $ResourceGroupApiUri - ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by omerzubair** [comment]
This is the code i used:

$TenantId = "" # Enter Tenant Id.
$ClientId = "" # Enter Client Id.
$ClientSecret = ""  # Enter Client Secret.
$Resource = "https://management.core.windows.net/"
$SubscriptionId = "" # Enter Subscription Id.

$RequestAccessTokenUri = "https://login.microsoftonline.com/$TenantId/oauth2/token"

$body = "grant_type=client_credentials&client_id=$ClientId&client_secret=$ClientSecret&resource=$Resource"

$Token = Invoke-RestMethod -Method Post -Uri $RequestAccessTokenUri -Body $body -ContentType 'application/x-www-form-urlencoded'

Write-Host "Print Token" -ForegroundColor Green
Write-Output $Token

$ResourceGroupApiUri = "https://management.azure.com/subscriptions/$SubscriptionId/providers/Microsoft.Network/bgpServiceCommunities?api-version=2019-08-01"
$Headers = @{}

$Headers.Add("Authorization","$($Token.token_type) "+ " " + "$($Token.access_token)")

$response = Invoke-RestMethod -Method Get -Uri $ResourceGroupApiUri -Headers $Headers

"[INFO] Print Response [$response]"
$response = $response.value
$response.name
$response.properties.bgpCommunities

foreach($r in $response){
    "[INFO] Names [$($r.name)] BGP: [$($r.properties.bgpCommunities)]"
}
"[INFO] Finished"

**Comment by omerzubair** [comment]
Just realised that the **https://management.core.windows.net** will be deprecated in 2.5 months as well.
https://azure.microsoft.com/en-gb/updates/azure-automation-service-management-rest-apis-are-being-retired-april-30-2019/

**Comment by jaredr80** [comment]
There was an issue with the underlying API, not the PS cmdlet. #please-close
