### ISSUE TITLE
Get-AzRecoveryServicesVaultSettingsFile -Certificate missing documentation

### ISSUE THREAD

**Issue by arcotek-ltd** [Azure/azure-powershell#10166]
## Description
According to `Show-Command Get-AzRecoveryServicesVaultSettingsFile` The parameter `-Certificate` is required, but your [documentation](https://github.com/Azure/azure-powershell/blob/master/src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesVaultSettingsFile.md) does not provide any details on where this certificate comes from or how to use it.

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by pvrk** [comment]
Please refer to documentation here:

https://docs.microsoft.com/azure/backup/backup-client-automation#registering-using-the-ps-az-module

**Comment by pvrk** [comment]
Closing the issue since documentation is updated.
