### ISSUE TITLE
How do we download AzureRM in a closed environment

### ISSUE THREAD

**Issue by jlongo62** [Azure/azure-powershell#10176]
## Description
For the link: https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-2.7.0

It works great in an open environment. More commercial and almost all gov't systems are closed to the internet. the gallery does not work. Presumable, there is a way to get Powershell AzureRM and/or Az. I'll be damned if I can find them. Please provide download links and/or instructions for closed network work-arounds.

## Steps to reproduce

```powershell

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by markcowl** [comment]
https://github.com/Azure/azure-powershell/releases

Every release contains msi installers.
