### ISSUE TITLE
How do we download AzureRM in a closed environment

### ISSUE THREAD

**Issue by jlongo62** [Azure/azure-powershell#10179]
## Description
How do we download AzureRM in a closed environment
There should be an AzureRM installer package that can be sneaker-net'd into another VM.
Where is it ?
This is a problem in many corp and gov't environments.
Nothing comes in until it goes through IA process.

Please check your answer before closing tickets!
The link provided by the guy who closed the original ticket:
https://github.com/Azure/azure-powershell/releases
only applies to Az,
Further, attempting to install:
Az-Cmdlets-2.7.0.29947-x64.msi
Installer fails immediately on new Wind 2016 Datacenter Azure Image.
I am not even sure this package would install Az it it worked.

This kind of response is unacceptable and is reflective of a downhill culture at microsoft.
I have spent 3 hours  trying to locate and installer I would expect to find on the Downloads web-site.
But the Downloads website: https://www.microsoft.com/en-us/download
Does not even have a search feature worth anything - i.e,  limiting results to downloads
Try searching: "Remote Desktop Manager" on that site. Why would I want 4,740,000 results that I cannot even filter to just "https://www.microsoft.com/en-us/download/..." links.
It should just return download links if I searching for Downloads !

## Steps to reproduce

```powershell

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by markcowl** [comment]
@jlongo62 APologies for closing the issue so quickly if it did not resolve your problem.  What is the error you get when you attempt to install the package?  Note that you will need to have WindowsPowerShell or PowerShell Core on the target machine, and, if it is Windows PowerShell, at least .Net 4.7.2.

**Comment by markcowl** [comment]
@jlongo62 AzureRM is no longer under active development, but the latest released version has an installer available here: https://github.com/Azure/azure-powershell/releases/tag/v6.13.1-November2018

**Comment by markcowl** [comment]
@jlongo62 it is also possible to create a local repository using a file share, if this is a more attractive option - you can use Install-Module to install from local file shares containing PowerShell Nuget packages.

**Comment by jlongo62** [comment]
Good luck with that in a closed environment. You guys need to tgry this out on closed machines. There should be a simple reliable installer to get this going! 2 days!

Register-PSRepository -Name az.2.7.0 -SourceLocation "\\xxxxxxxx\nupkg" -InstallationPolicy Trusted 
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Install-PackageProvider : No match was found for the specified search criteria for the provider 'NuGet'. The package provider 
requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7405 char:21
+ ...     $null = PackageManagement\Install-PackageProvider -Name $script:N ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageProvider
 
PackageManagement\Import-PackageProvider : No match was found for the specified search criteria and provider name 'NuGet'. Try 'Get-PackageProvider 
-ListAvailable' to see if the provider exists on the system.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7411 char:21
+ ...     $null = PackageManagement\Import-PackageProvider -Name $script:Nu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (NuGet:String) [Import-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.ImportPackageProvider
 
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Get-PackageProvider : Unable to find package provider 'NuGet'. It may not be imported yet. Try 'Get-PackageProvider 
-ListAvailable'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7415 char:30
+ ... tProvider = PackageManagement\Get-PackageProvider -Name $script:NuGet ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...PackageProvider:GetPackageProvider) [Get-PackageProvider], Exception
    + FullyQualifiedErrorId : UnknownProviderFromActivatedList,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackageProvider
 
Register-PSRepository : NuGet provider is required to interact with NuGet-based repositories. Please ensure that '2.8.5.201' or newer version of 
NuGet provider is installed.
At line:1 char:1
+ Register-PSRepository -Name az.2.7.0 -SourceLocation "\\MSOAZDD0FXBLD ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Register-PSRepository], InvalidOperationException
    + FullyQualifiedErrorId : CouldNotInstallNuGetProvider,Register-PSRepository

**Comment by markcowl** [comment]
@jlongo62 You are correct that we don't deal with closed environments very much, you would need to make sure that the latest PowerShellGet and PackageManagementProvider were installed first.  If you were using PowerShell Core, that would happen automatically.  Would be happy if you had some time to to work together on getting a script for this that others could use.  Meanwhile, the installer should work, please share the error details if you find that it is not.

The prerequisites for installation are discussed here: https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-2.7.0

**Comment by markcowl** [comment]
@jlongo62 Can you provide details on the error you receive when running the msi?

**Comment by markcowl** [comment]
I see you filed another (issue)[]  with this information.  I suspect that if the installer worked for you, that would resolve the issue.  Is that correct?

**Comment by dingmeng-xue** [comment]
MSI installer is available in each release. User can install it to Windows PowerShell (PowerShell core is not supported).  Default installed folder is `C:\Users\<user>\Documents\WindowsPowerShell\Modules`

For PowerShell Core, there are 2 workarounds:
1. leverage local repository
```
Register-PSRepository -Name LocalRepo -SourceLocation "C:\Users\<user>\Documents\WindowsPowerShell\Modules" -PackageManagementProvider NuGet -InstallationPolicy Trusted
Install-Module -Name Az -Repository LocalRepo
```
2. just copy modules into PowerShell Core folder. Default folder is `C:\Users\<user>\Documents\PowerShell\Modules`

Please check if the workaround works.

**Comment by dingmeng-xue** [comment]
Close it as no further update.
