### ISSUE TITLE
Blueprint Assignment with User-assigned managed identity fails if user assigning does not have owner permissions

### ISSUE THREAD

**Issue by alex-frankel** [Azure/azure-powershell#10184]
If I am creating the assignment without owner permissions via powershell, assignment creation fails because it is attempting to give the Azure Blueprints SPN owner rights on the subscription. Since I don't have rbac write permissions, the assignment creation fails, but it doesn't need to do that for UAMI.

This issue was opened [here](https://github.com/MicrosoftDocs/azure-docs/issues/39985), but transferring to this repo so we can better track it

**Comment by alex-frankel** [comment]
@frenky29a - just sync'd with the engineering team. To unblock you, we are going to push a fix that allows a parameter set with *both* the `-AssignmentFile` and `-UserAssignedIdentity` parameters.

It's a bit odd as you will be providing the resourceId in both the file and the parameter, but it should allow you to keep progressing. This fix should be done in the next 2-3 days.

Once that is done, we will take another pass at this cmdlet to not require redundant information.

**Comment by frenky29a** [comment]
@alex-frankel - Big thanks to you and the team !

**Comment by filizt** [comment]
We have made the changes to fix the use of UAMI in the blueprint assignment operation.  A new version(0.2.6) of Az.Blueprint module is available at the PowerShell gallery. The new behavior is that given an assignment file, the `New-BlueprintAssignment cmdlet` uses the identity information in the file and doesn't expect it inline through '-UserAssignedIdentity` parameter.

**Comment by frenky29a** [comment]
perfect !
