### ISSUE TITLE
Az Does not install

### ISSUE THREAD

**Issue by jlongo62** [Azure/azure-powershell#10182]
## Description
FAILS:
Clean machine, no internet
msiexec.exe /a "C:\Users\xxxx\Downloads\Az-Cmdlets-2.7.0.29947-x64.msi" /L*V "C:\Users\xxxxx\Downloads\Az-Cmdlets-2.7.0.29947-x64.log"

If this actually works, how about some install notes, ie pre-reqs, run as admin (a pain in the A cause you have to figure out the command line), etc...

When run manually, no error comes from installer, it just stops and indicates it failed.

[Az-Cmdlets-2.7.0.29947-x64.log.zip](https://github.com/Azure/azure-powershell/files/3686411/Az-Cmdlets-2.7.0.29947-x64.log.zip)

Does anyone test this stuff - properly (clean vm, closed to internet) ? MS is becoming everything I always hated about open-source -- poor quality, reliability, testing, etc..
And why should anyone do a good job for free?
I am a MS developer from the beginning. I stayed away from JAVA for just these kinds of issues.
I am not an MS hater, but I am getting pretty pissed off.

**Comment by msJinLei** [comment]
@jlongo62 Thank you for reporting that issue. We are working on it and will let you know if any update.

**Comment by dingmeng-xue** [comment]
@jlongo62 thanks for your finding. We can reproduce this issue and will do the further investigation and log a new issue why module are not installed to correct location.

It seems all modules are copied to F:\WindowsPowerShell, but they should be under %ProgramFiles%\WindowsPowerShell\Modules. Could you just copy modules to there and double check. Another workaround is setting ROOTDRIVE explicitly which should be the parent folder of WindowsPowerShell.

msiexec.exe /a "Az-Cmdlets-2.8.0.30291-x64.msi" /L*V "Az.2.8.0.log" ROOTDRIVE="C:\Program Files"
