### ISSUE TITLE
Get-AzBlueprint does not report an error with -LatestPublished Flag set

### ISSUE THREAD

**Issue by alex-frankel** [Azure/azure-powershell#10185]
If I do:

`Get-AzBlueprint -ManagementGroupId "test" -Name "not-a-real-blueprint"`

It errors out correctly, but if I do:

`Get-AzBlueprint -ManagementGroupId "test" -Name "not-a-real-blueprint" -LatestPublished`

There is no error returned

**Comment by filizt** [comment]
This issue should be fixed now.

**Comment by alex-frankel** [comment]
closing
