### ISSUE TITLE
PowerShell ISE: az : The term 'az' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by Kichnifou** [Azure/azure-powershell#10183]
## Description

I did these following steps :
Install-Module -Name Az -AllowClobber
Import-Module Az
Connect-AzAccount
#Install Azure CLI
Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'

But when I try to use "az login" I have this error :
PowerShell ISE: az : The term 'az' is not recognized as the name of a cmdlet

## Steps to reproduce

Follow steps in Description

## Environment data

PowerShell

**Comment by erich-wang** [comment]
@Kichnifou, have you tried to start new PowerShell session after installing?

**Comment by Kichnifou** [comment]
No im not, ill try thx

**Comment by erich-wang** [comment]
@Kichnifou, does the issue still exist? Please close the issue if no issue any more,thanks.

**Comment by markcowl** [comment]
'az login' is an azure cli command.  It is not an azure powershell command.  If you want to use Azure CLI, you will need to install it.

**Comment by msplmansit98** [comment]
Its 2022, I am facing the same issue. I have installed azureCLI. The command is working on command prompt but when I initiate command prompt from VS code it isn't working.
