### ISSUE TITLE
Get-AzStorageTable Couldn't Find Parameter on vscode

### ISSUE THREAD

**Issue by chupark** [Azure/azure-powershell#10193]
When I use on VSCODE [Start Debuging F5] the following error occurred.
It is said that the parameter [-Name and -Context] cannot be found.
But it works well in Powershell ISE.

Get-AzStorageTable : 'backupLists' 인수를 허용하는 위치 매개 변수를 찾을 수 없습니다.
위치 D:\PowerShell\PowerShell\AzurePowerShell\dev\SnapShot-Backup-withStorage\src\make_env.ps1:20 문자:16
+ ... cloudTable = (Get-AzStorageTable ?밡ame $b ?밅ontext $saContext).CloudT ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzStorageTable], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTableCommand

**Comment by blueww** [comment]
@chupark 

As the error is "No positional parameter found that accepts arguments."
It seems the '-' in parameter name is not correct parsed, so the parameter name is not recognized.
You can see in the error message, they are regognized as "?밡"

The same command works fine in my machine (my machine default language is English). 
This might be related with some language setting on your machine. Or you might can see if other cmdlets with paramters works? If so, please see how they input '-'

**Comment by chupark** [comment]
My parameter was "-name" and "-context"

I removed it yesterday and reinstalled it, and it works fine on VSCODE now.
Was there any changes?

**Comment by blueww** [comment]
I don't know any PSH change related to that.
From the error, the error is just "-" can't be parse in VScode, might be related with some language setting on your machine.

Anyway, since it works fine now, I will close the issue.
Feel free to contact us if you need any further accistance.
