### ISSUE TITLE
URL Rewriting of the ARM endpoint takes the URL that of AzureCLoud all the time

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#10192]
Module Version Az.Accounts 1.6.2

Url rewriting is currently dependent on having a value that matches an endpoint in the ‘AzureCloud’ environment as the input URL. Azure stack admin swagger specs has the host  entry as  "host": "adminmanagement.local.azurestack.external", not as management.azure.com

We should we rewriting these urls based on the **currently selected environment** rather than the Azure Cloud

Debug Traces

DEBUG: 12:43:33 AM - Autosave setting from startup session: 'Process'
DEBUG: 12:43:33 AM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 12:43:33 AM - Using Autosave scope 'Process'
DEBUG: 12:43:33 AM - Autosave setting from startup session: 'Process'
DEBUG: 12:43:33 AM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 12:43:33 AM - Using Autosave scope 'Process'
DEBUG: 12:43:33 AM - AddAzureRMEnvironmentCommand end processing.
DEBUG: 12:43:33 AM - AddAzureRMEnvironmentCommand end processing.
DEBUG: 12:43:33 AM - Autosave setting from startup session: 'Process'
DEBUG: 12:43:33 AM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 12:43:33 AM - Using Autosave scope 'Process'
DEBUG: 12:43:33 AM - Autosave setting from startup session: 'Process'
DEBUG: 12:43:33 AM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 12:43:33 AM - Using Autosave scope 'Process'
WARNING: TenantId '238d0428-f000-4662-a6a2-6aac7053b646' contains more than one active subscription. First one will be selected for further use. To select another subscription, use Set-AzContext.
Key          Value       
---          -----       
Get-AzsQuota Get-AzsQuota
                         
                         
DEBUG: 12:43:34 AM - ConnectAzureRmAccountCommand end processing.
DEBUG: 12:43:34 AM - ConnectAzureRmAccountCommand end processing.
DEBUG: 12:43:34 AM - GetAzureRMContextCommand end processing.
DEBUG: 12:43:34 AM - GetAzureRMContextCommand end processing.
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'Get-AzsQuota_List': AzureQoSEvent: CommandName - Get-AzsQuota_List; IsSuccess - False; Duration - 00:00:00; Exception - ;
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: https://adminmanagement.local.azurestack.external/subscriptions/83bab560-f565-4096-85d2-c246332b8341/providers/Microsoft.KeyVault.Admin/locations/redmond/quotas?api-version=2017-02-
01-preview
DEBUG: RequestCreated: https://adminmanagement.local.azurestack.external/subscriptions/83bab560-f565-4096-85d2-c246332b8341/providers/Microsoft.KeyVault.Admin/locations/redmond/quotas?api-version=2017
-02-01-preview
DEBUG: HeaderParametersAdded: https://adminmanagement.local.azurestack.external/subscriptions/83bab560-f565-4096-85d2-c246332b8341/providers/Microsoft.KeyVault.Admin/locations/redmond/quotas?api-versi
on=2017-02-01-preview
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://adminmanagement.local.azurestack.external/subscriptions/83bab560-f565-4096-85d2-c246332b8341/providers/Microsoft.KeyVault.Admin/locations/redmond/quotas?api-version=2017-02-01-preview

Headers:

Body:

DEBUG: BeforeCall: 
DEBUG: Finally: 
DEBUG: [CmdletProcessRecordAsyncEnd]: Sending new QosEvent for command 'Get-AzsQuota_List': AzureQoSEvent: CommandName - Get-AzsQuota_List; IsSuccess - True; Duration - 00:00:00; Exception - ;
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: [CmdletException]: Received Exception with message 'MsalServiceException - AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter '
scope' is not valid. The scope /.default offline_access openid profile is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>
…………..
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.PowerShell.Cmdlets.KeyVaultAdmin.Cmdlets.GetAzsQuota_List.<ProcessRecordAsync>d__59.MoveNext()'
DEBUG: CmdletException: MsalServiceException - AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope /.de
fault offline_access openid profile is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>.
Trace ID: 0711e16e-ba2a-44c4-8198-f5c99dff0200
Correlation ID: 6eb72cc7-a8ad-4a78-a389-89a836615cf6
………
Microsoft.Azure.PowerShell.Cmdlets.KeyVaultAdmin.Cmdlets.GetAzsQuota_List.<ProcessRecordAsync>d__59.MoveNext()
Get-AzsQuota : AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope /.default offline_access openid 
profile is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>.
Trace ID: 0711e16e-ba2a-44c4-8198-f5c99dff0200
Correlation ID: 6eb72cc7-a8ad-4a78-a389-89a836615cf6
Timestamp: 2019-10-01 00:43:34Z
At C:\Users\Administrator.V-DVM\Desktop\SDK\testKeyVault.ps1:13 char:1
+ Get-AzsQuota -Location redmond
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzsQuota_List], MsalServiceException
    + FullyQualifiedErrorId : Microsoft.Azure.PowerShell.Cmdlets.KeyVaultAdmin.Cmdlets.GetAzsQuota_List

DEBUG: CmdletProcessRecordEnd:

**Comment by lwajswaj** [comment]
Even if you fix this, you will run into the issue that Azure Stack doesn't support AZ module as Azure Stack doesn't have the latest API (actually not even close to the latest). That's why when working with Azure Stack, you need to keep using AzureRM 2.5.0 (yeah, that old!); you can see when you [Use-AzureRmProfile](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-install?view=azs-1908#4-connected-install-powershell-for-azure-stack-with-internet-connectivity) according to the documetation, you'll see you get that version installed. When the route of using AZ and I failed at the first command, just because Stack doesn't have the required API versions.

**Comment by bganapa** [comment]
@lwajswaj It seems you know the pain of using a old azure powershell modules for AZURESTACK while azure has moved on to Az. I work for the azure stack team and we are trying to ease the pain.

We have a new Az preview release out in powershell gallery.  With this release, one can use the same bits against azure as well as azure stack, just by changing the api profile. You don't even need to open a new session to switch between azure and AZURESTACK modules. We are still working through many issues though and this issue tracks one of them.
The following bits can be used against azure stack AAD environments.(Note it wont work on ADFS at the moment).  Expect few rough edges as we are still working on it.  Please feel free to pass on the feedback on the bits/plan direction by opening issues as mentioned in the following docs. Thank you!
https://www.powershellgallery.com/packages/Az/4.0.1-preview
https://github.com/Azure/azure-powershell/tree/generation/documentation/preview
https://github.com/Azure/azure-powershell/blob/generation/documentation/RFC/RFC0001-Azure-Profiles.md

**Comment by lwajswaj** [comment]
@bganapa, thanks, I wasn't aware of that preview. However, personally, I'm not sure if it's worth it the effort for developing the module as the only benefit would be to just use the same module for AzureStack which avoids either writing two scripts (one for Public and another for Stack) **OR** use AzureRM cmdlet names (and enable aliases when running under AZ); you are still trapped on AzureStack using old API versions. Honestly, I'm currently going with the last one as I need, from Azure DevOps stand point, a self-hosted agent dedicated for Stack. I'll take a look at the preview anyway.

**Comment by dingmeng-xue** [comment]
@bganapa , is it still a valid item? I believe you can set new environment except debug message still contains some incorrect output.

**Comment by bganapa** [comment]
Yes. This is still valid, 
We worked around by specifying the host as management.azure.com in the swagger (It should not need to be, as in azurestack the host url is different)
  "host": "management.azure.com",
e.g.
https://github.com/Azure/azure-rest-api-specs/blob/acc3d6c177e79ef474bda9ec2466dd89dd635ba0/specification/azsadmin/resource-manager/azurebridge/Microsoft.AzureBridge.Admin/preview/2016-01-01/Activation.json#L8

Since we already have the changes merged in to  specs master, Fixing the issue is low pri IMO

**Comment by bganapa** [comment]
@dolauli @isra-fel Can you pls move this to a proper milestone. We are not blocked by this issue

**Comment by dolauli** [comment]
This should have been fixed in @autorest/powershell@3.0.414
