### ISSUE TITLE
New-AzPolicyAssignment doesn't assign the role definition for Managed Identity

### ISSUE THREAD

**Issue by saach11** [Azure/azure-powershell#10196]
## Description

When creating a new policy assignment that requires managed identity, it should automatically add the role for the new identity.
The service principal is created, however the role assignment is not.
As a result Policy remediation doesn't work as expected.

## Steps to reproduce
The policy definition is a custom one with an "effect" = modify.
The role definition ID is contributor
"roleDefinitionIds": [			"/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
],

```powershell
New-AzPolicyAssignment -Name "Custome Policy Assignment Name" -PolicyDefinition $PolicyDefinition -Scope "/subscriptions/00000000-5a48-4ed5-a3f7-0378524e725a" -AssignIdentity -Location eastus
```

## Environment data

```

```

## Module versions

```powershell
Script     1.7.0      Az.Resources
```

## Debug output

```

```

## Error output

No error after running New-AzPolicyAssignment, the warning can be seen on Policy remediation page
```
The managed identity for this assignment does not have the appropriate permissions to remediate these resources. To add these permissions, go to the Edit Assignment page for this Policy and re-save it.
```

**Comment by msJinLei** [comment]
@saach11  Could you provide the following information.

## Environment data
Please run $PSVersionTable and paste the output in the below code block

## Module versions
Please run (Get-Module  -ListAvailable) and paste the output in the below code block

## Debug output
$DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block

**Comment by msJinLei** [comment]
@saach11 Any update?

**Comment by adjohns** [comment]
@msJinLei I am experiencing the same behavior for the command as saach11 . The identity will be created following the assignment name but then has no role assignments made. When you perform a remediation action it will fail since the assignment powershell did not give the identity any permissions.

I have sent you an email with the requested debug information.

**Comment by msJinLei** [comment]
> @msJinLei I am experiencing the same behavior for the command as saach11 . The identity will be created following the assignment name but then has no role assignments made. When you perform a remediation action it will fail since the assignment powershell did not give the identity any permissions.
> 
> I have sent you an email with the requested debug information.

Sorry, which address you emailed to?

**Comment by DdenBraver** [comment]
@msJinLei Is there any update regarding this issue?
We are running into exactly the same issue right now. However we are certain the issue was not taking place before the 14th of November.

"New-azPolicyAssignment with -AssignIdentity switch, does not actually assign/create an identity"

**Comment by adjohns** [comment]
@msJinLei  - I sent it to your Microsoft email which I found on the GAL - just bumped it today to the top of your inbox.

@DdenBraver - A workaround we used is to call the 'New-AzPolicyAssignment' CMDLET then follow it with a call to 'New-AzRoleAssignment' using the produced ObjectID and RoleID from the policy assignment creation.

IE:
`$Policy = Get-AzPolicyDefinition -Name '<Policy Name>' -ManagementGroupName 'test-mgmt-gp'

$scope =  "/subscriptions/<sub_id>/resourceGroups/<rg_name>"

$assignment = New-AzPolicyAssignment -Location 'eastus' -Name '<testpolicyassignment>' -DisplayName 'test policy assignment' -PolicyDefinition $Policy -Scope $scope -AssignIdentity

## Get newly created policy assignment object
$PolicyAssignment = Get-AzPolicyAssignment -Name '<testpolicyassignment>' -Scope $scope

## Extract the RoleID and ObjectID
$roleDefinitionId = [GUID]($Policy.properties.policyRule.then.details.roleDefinitionIds -split "/")[4]
$objectID = [GUID]($PolicyAssignment.Identity.principalId)

## Create a role assignment from the previous information
New-AzRoleAssignment -Scope $scope -ObjectId $objectID -RoleDefinitionId $roleDefinitionId`

**Comment by DdenBraver** [comment]
Thanks @adjohns the manual workaround does work indeed.
Its sad to see however that the original functionality, where it used to create the managed identity with the roles defined in the ARM template, no longer works.

**Comment by dingmeng-xue** [comment]
Service team, even workaround works as @adjohns mentioned. Please look into if `New-AzPolicyAssignment` can be improved.

**Comment by kenieva** [comment]
This is by design. When creating an assignment through portal, the role assignments are auto-granted. However, when using PowerShell, you must manually configure the managed identity. Information found here: https://docs.microsoft.com/en-us/azure/governance/policy/how-to/remediate-resources#manually-configure-the-managed-identity

**Comment by kwiecek** [comment]
You can use the script you find here: [Fix MSI Role Assignment](https://automate.guru/fix-msi-role-assignment/) 
In addition to giving MSI the appropriate permissions, it also cleans up remnants of the deleted assignment.
