### ISSUE TITLE
Issues found by PVS-Studio

### ISSUE THREAD

**Issue by skhrenov** [Azure/azure-powershell#10223]
Hello,
I have found a few bugs using PVS-Studio analyzer.
PVS-Studio is a static code analyzer for C, C++, C#, and Java.
I gave the description of errors and code fragments in the article.
You can read the article at the official site: [https://www.viva64.com/en/b/0678/](https://www.viva64.com/en/b/0678/)

**Comment by number213** [comment]
@skhrenov thanks! Suggestion: maybe it would be better open issues if not by individual bugs, but by resource providers (Accounts / Compute / Network / RescoveryServices / etc) 

---

From Network's side, @vinayada1, could you please take a look at `Remove-AzExpressRouteConnection`? Is there a reason for why this is written that way:

```
if (ParameterSetName.Equals(CortexParameterSetNames.ByExpressRouteConnectionName, StringComparison.OrdinalIgnoreCase))
{
    this.ResourceGroupName = this.ResourceGroupName;
    this.ExpressRouteGatewayName = this.ExpressRouteGatewayName;
    this.Name = this.Name;
}
```

https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/Cortex/ExpressRouteGateway/ExpressRouteConnection/RemoveAzureRmExpressRouteConnectionCommand.cs#L84
