### ISSUE TITLE
Azure Datafactory IR start stop - run as background job

### ISSUE THREAD

**Issue by prabhu130986** [Azure/azure-powershell#10242]
## Description of the new feature
Need --no-wait or -AsJob option for Start-AzDataFactoryV2IntegrationRuntime and Stop-AzDataFactoryV2IntegrationRuntime modules. 

Starting an IR takes around 25 minutes and the powershell prompt does not return until IR is fully started. This is a bottleneck for automating this start / stop process. Can you add --no-wait or -AsJob option as there in Start-AzureRmVM so that the process can run as a background job?

Infact, this option can be added to Start Stop process of all azure services.

**Comment by lmy269** [comment]
@shawnxzq to take a look

**Comment by prabhu130986** [comment]
> @shawnxzq to take a look

@shawnxzq , any tentative date or time when this can be added?

**Comment by shawnxzq** [comment]
@prabhu130986 This is by design for now, we hear your feedback and we will prioritize this in product team, thanks for the feedback.

**Comment by swinarko** [comment]
We'll add this in our feature backlog.  As a workaround for now, you can create an Azure Automation PowerShell runbook that starts/stops your SSIS IR and then asynchronously invoke its webhooks from your automation, see https://docs.microsoft.com/azure/data-factory/how-to-schedule-azure-ssis-integration-runtime#create-and-schedule-azure-automation-runbook-that-startsstops-azure-ssis-ir.

**Comment by simonsabin** [comment]
or just use the az cli
