### ISSUE TITLE
https://github.com/microsoft/azure-pipelines-tasks/issues/11434 

### ISSUE THREAD

**Issue by Linaa** [Azure/azure-powershell#10283]
"AzurePowerShell@4 module Az.Blueprint in consistent behaviour" submitted the issue regarding Az.Blueprint module behaviour in Az.DevOps task. They recommeneded me to contact this forum.

**Comment by alex-frankel** [comment]
We have fixed this issue. The cmdlet is now case insensitive for the artifacts folder
