### ISSUE TITLE
Get-AzComputeResourceSku -PS cmdlet, better explanation of output

### ISSUE THREAD

**Issue by cadumi** [Azure/azure-powershell#10282]
## Description of the new feature
https://github.com/MicrosoftDocs/azure-docs/issues/40481

For the Get-AzComputeResourceSku output, we might get the NotAvailableForSubscription output even though the VM SKU is available for Subscription but unavailable in Zone. You should specify in the documentation how the output should be interpreted. Also, for a better output below command should be used with the FC parameter at the end:
Get-AzComputeResourceSku | where {$.Locations.Contains("westus") -and $.ResourceType.Contains("virtualMachines")} | fc
 In PS, this is declared by using Restrictions as an array. If the type of restriction is “Zone”, it means that the Subscription has restrictions, to that size, only if a customer tries to deploy to any of the listed restricted Zones:
Restrictions[0] :
Type : Zone
Values[0] : westeurope
RestrictionInfo :
Locations[0] : westeurope
Zones[0] : 1
Zones[1] : 2
Zones[2] : 3
ReasonCode : NotAvailableForSubscription
Otherwise, if the restriction applies to both Location and Zone, they would have something like the below.
Below you can see that the Restrictions array is now counting 2 items. One for the Location type and one for the Zone type.
The ReasonCode is saying that that specific “type” (Location/Zone/etc) is restricted to the subscription and hence “NotAvailableForSubscription”.
Restrictions[0] :
Type : Location
Values[0] : westeurope
RestrictionInfo :
Locations[0] : westeurope
ReasonCode : NotAvailableForSubscription
Restrictions[1] :
Type : Zone
Values[0] : westeurope
RestrictionInfo :
Locations[0] : westeurope
Zones[0] : 1
Zones[1] : 2
Zones[2] : 3
ReasonCode : NotAvailableForSubscription
## Proposed implementation details (optional)
might be desired, that a new cmdlet can be brought out which is more self explanatory

**Comment by Drewm3** [comment]
@cadumi, I see that there is a separate issue opened on the documentation. So let's use this issue for your feature request. On the feature request side are you asking for the REST API to be changed, or just the PowerShell cmdlet? Could you provide a bit more clarity on the feature request that you are suggesting because it wasn't completely clear to me on the suggestion above.

**Comment by cadumi** [comment]
Hi Drew,

I would like to ask for a better understandable output of the existing cmdlet or a new cmdlet which differentiates between availability on location and availability on location with zones.

https://github.com/MicrosoftDocs/azure-docs/issues/40481#event-2706813723

  Thanks
Carmina

**Comment by Drewm3** [comment]
The cmdlet today is based on the backend API. To have a significantly different display we would need to create a separate cmdlet that is custom created to provide a different experience from the API and to ensure that we do not break existing customers of the Get-AzComputeResourceSku cmdlet. We will take it into consideration to build a new cmdlet, but at this time it is not on our near-term priority. So I am going to close this request for now. For longer-term tracking of feature requests please open this as a new idea or vote up an existing idea.
