### ISSUE TITLE
SPN Secret displayed in Disconnect-AzAccount

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#10281]
## Description

When logged in as an SPN with SPN secret credentials, running `Disconnect-AzAccount` to disconnect the account will display the secret credentials on the screen - this value should never be displayed.

**Comment by markcowl** [comment]
Cannot validate - there is a credential field displayed, but no secret text is displayed.  Closing as no repro.

**Comment by otm1** [comment]
This is an issue for us as well. Still happening with newest PowerShell module, Az.Accounts 2.2.5, and on Github hosted runners ubuntu-latest. (Not happening on every run)

**Comment by dingmeng-xue** [comment]
This issue can be reproduced after login with SPN. 

(Get-AzContext).Account.ExtendedProperties

**Comment by erich-wang** [comment]
Fixed in the PR #14912
