### ISSUE TITLE
Changelog & version controlling tool optimization

### ISSUE THREAD

**Issue by msJinLei** [Azure/azure-powershell#10296]
## Description
We encounter several cases in the release that version controlling tool fails to update the module versions correctly according to change log.

1.change log merging issue.
The changes of the change log between release branch creation and release branch merging back are not correctly merged to above the latest version of its change log if the same change log is also updated in the release.

2. The PR authors fails to update the changelog correctly
- they put the changed item into wrong place
- they forget to change the changelog

To address all the issues, we need an improvement for our current tools.

## Cost
8

**Comment by dingmeng-xue** [comment]
Close this issue because we mitigate this problem by suggesting contributor to add changelog to correct location
