### ISSUE TITLE
Investigate linux pipeline failure

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#10304]
## Description

The linux portion of the azure-powershell-core pipeline was turned off last release due to instability in the linux workers.  Need to investigate the issue, and determine whether we need to update linux configuration, fiel an issue with TFS, or make other fixes to the p[ipeline

**Comment by dingmeng-xue** [comment]
Issue is resolved after upgrading Linux to Ubuntu 18.04 #10321
