### ISSUE TITLE
Server-side telemetry is not sending up needed headers

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-powershell#10331]
In general, 4.x preview commands are not sending up client request id, command names, or paramset names (and potential other values sent up by previous versions).  

![image](https://user-images.githubusercontent.com/10146011/67132749-9ce75f80-f1be-11e9-9945-1600f4394e27.png)

**Comment by JasonRShaver** [comment]
@albaloo

**Comment by erich-wang** [comment]
The fix is ready and should be available in next Az 4.0 preview release.
