### ISSUE TITLE
Complex usage on Get-AzAutomationJobOutputRecord 

### ISSUE THREAD

**Issue by GitMaggie** [Azure/azure-powershell#10336]
## Description
To get full text of AA job output ,  we need use Get-AzAutomationJobOutputRecord .
However, in Az module, it's too complex to get the error message . 
For example, per my tests, only this way works when my job has multiple error outputs :
`((Get-AzAutomationJobOutput -Id $jobid  -AutomationAccountName $AAname -ResourceGroupName $groupname -Stream Error| Get-AzAutomationJobOutputRecord).Value[$i].Exception.tostring() |convertfrom-json ).Message`

As you can see, I need use "**.Value[$i].Exception.tostring() |convertfrom-json ).Message**".
In **ARM** module, the cmdlet is much easier :.**Value.Exception.Message** is enough .

May be this is related to this issue ?
https://stackoverflow.com/questions/58141125/understanding-newtonsoft-in-powershell

## Ask from dev team
Could you please veirfy if we can make it easier ?
Could you please update the document regarding the correct usage ?

## Steps to reproduce
1. Run the command to get full message of a few long output error messages in AA job .

## Module versions
Latest Az module for cmdlet Get-AzAutomationJobOutputRecord

**Comment by andyw248** [comment]
Tried to repro, but it appears that the following script yields the exception record and is not difficult to use:
$record = (Get-AzAutomationJobOutput -Id $jobid -AutomationAccountName $AAname -ResourceGroupName $groupname -Stream Error | Get-AzAutomationJobOutputRecord).Value
$record.Exception.ToString() | ConvertFrom-Json

**Comment by Borgquite** [comment]
This also works, without requiring conversion to/from JSON:

`(Get-AzAutomationJobOutput -Id $jobid  -AutomationAccountName $AAname -ResourceGroupName $groupname -Stream Error | Get-AzAutomationJobOutputRecord) | ForEach-Object { $_.Value.Exception.Message.ToString() }`

(NB `$_.Value.Exception` can be type `[Newtonsoft.Json.Linq.JObject]` or `[System.Management.Automation.PSCustomObject]` - the above code handles both).
