### ISSUE TITLE
Client-side telemetry is not getting correct useragent

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-powershell#10330]
When querying DDAzureClients, the Properties.useragent for Az 4.x is not showing up as it does in server-side telemetry.  We are expecting something like ''AzurePowershell/Az4.0'' 

Please see @dcaro for more context and sample query.

**Comment by JasonRShaver** [comment]
@albaloo

**Comment by erich-wang** [comment]
move to S162 since need context from damien

**Comment by erich-wang** [comment]
The fix has been merged into master branch, the fix will be ready in next release of Az 4.0 preview
