### ISSUE TITLE
Document how to deploy a Cloud Service with the new API.

### ISSUE THREAD

**Issue by chaami** [Azure/azure-powershell#10340]
Hi,
I am trying to deploy a Cloud Service with the new API and I can't figure how to do it.
`Get-AzDeployment` doesn't return anything when applied in context where Azure Cloud Services are running.
In contrast the `Get-AzureDeployment` Azure equivalent returns the current running deployment.
Given that the older Azure PowerShell module is now incapable of deploying websites (check this #7558 [comment](https://github.com/Azure/azure-powershell/issues/7558#issuecomment-543405013)) and that Azure and Az are not compatible, I don't see how I can script deployments as of writing.
As suggested, I have also looked into `Get-AzResources` and `Set-AzRessource`.
When using `Get-AzResources`, the only thing that seems remotely usable to deploy is the Microsoft.ClassicCompute/domainNames, however I don't see how to use that to update the deployed version.
In case you don't support the App Services yet, could you please restore the `Set-AzureWebsite` until it's the case.
Thanks and kind regards.

**Comment by dcaro** [comment]
Hello @chaami , I'm sorry that you have been waiting on this issue for so long.
Just to make sure that I understand your issue well, you are trying to create an Azure Web app using PowerShell? Have you had a look at the tutorials here: https://docs.microsoft.com/en-us/azure/app-service/samples-powershell
Please let me know.

**Comment by chaami** [comment]
Hi @dcaro ,
No worries, 
I am actually trying to deploy an application that is labeled as a "Cloud services (classic)" in the Azure portal using the Az PowerShell module.
For now my workaround is to continue to use the older Azure module to deploy "Could Services (classic)" applications and deploy "Azure App services" through a [WAWSDeploy](https://github.com/davidebbo/WAWSDeploy).
Thanks.

**Comment by dcaro** [comment]
@chaami in order to deploy a "Cloud Service (classic)" you would have to use the [Azure](https://www.powershellgallery.com/packages/Azure/5.3.0) PowerShell module. Note that this module does not work cross platform (must be installed in Windows PowerShell) and is not supported with the current Az module.
If you need both on the same machine, you can install the current Az in PowerShell core and install the older modules in Windows PowerShell.
Thanks

**Comment by chaami** [comment]
Hi,
Could you please just make sure not to cut the older Azure PowerShell ability to deploy Cloud services (classic) before porting (or deprecating) the feature  before ?
Thanks.

**Comment by dcaro** [comment]
@chaami we do not have any plans to remove the [Azure](https://www.powershellgallery.com/packages/Azure/5.3.0) PowerShell module from the gallery.

Closing this issue now, feel free to reopen if needed.

**Comment by chaami** [comment]
@dcaro I was not thinking about the removal of the PowerShell module from the gallery, but of a cut of functionality like in #7558.

**Comment by chaami** [comment]
Incidentaly @dcaro, when you close an issue like this as a repo collaborator, only repo collaborators can re-open it.

**Comment by dcaro** [comment]
@chaami thanks, my bad regarding reopening the issue, feel free to ask to have the issue reopened.
Regarding the classic cloud services, they are not supported in the Az module and unfortunately we have not received enough requests to do so that would justify the effort needed.

**Comment by mikeblakeuk** [comment]
Please reopen this. thanks

**Comment by DJ4ddi** [comment]
While I do understand that lack of demand is a valid reason to drop features, it seems odd to completely cut this component from the command line tools.

In my case, I need a way to access legacy cloud service deployments (and their labels) which is compatible with the existing Az based script. Rewriting everything for a parallel installation of the old Azure module does not seem like a satisfactory solution.
