### ISSUE TITLE
Update: Migrate Azure PowerShell from Azure to Az

### ISSUE THREAD

**Issue by SumanthMarigowda-MSFT** [Azure/azure-powershell#10359]
Need to update the PowerShell Module. --> Azure to Az  Az module on your platform
https://docs.microsoft.com/en-us/powershell/azure/servicemanagement/install-azure-ps?view=azuresmps-4.0.0

https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-2.8.0 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa6c7f7-a61f-5a06-b964-888ee03eb86b
* Version Independent ID: a166875b-49f9-ea6d-d7ad-123189ef7b5c
* Content: [Install and configure the Azure PowerShell Service Management module](https://docs.microsoft.com/en-us/powershell/azure/servicemanagement/install-azure-ps?view=azuresmps-4.0.0)
* Content Source: [docs-conceptual/azuresmps-4.0.0/install-azure-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azuresmps-4.0.0/install-azure-ps.md)
* Service: **azure-asm**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by wyunchi-ms** [comment]
Hi @SumanthMarigowda-MSFT , thanks for your contribution! Could you please offer us more debug and error info to help us find the point of the problem?

**Comment by kilasuit** [comment]
I don't think this needs any change as the doc points to the older Azure Service Manager PowerShell module not the AzureRM module that was recently replaced with Az Module

**Comment by dingmeng-xue** [comment]
@SumanthMarigowda-MSFT , please double check @kilasuit's point. If you still hope doc needs to be updated, please clarify further

**Comment by dcaro** [comment]
@SumanthMarigowda-MSFT this content is relevant for those who still need to manage resources exposed by the Azure Service Management. 
I am closing this issue, feel free to comment if you feel otherwise,
