### ISSUE TITLE
Hidden/Not Hidden flag for get-azresource

### ISSUE THREAD

**Issue by DanteNahuel** [Azure/azure-powershell#10365]
## Description of the new feature
Currently, Get-AzResource brings all the existing resources in the targeted Azure Subscription.
However, when creating reports, this can be detrimental because of the many types of resources that can't be tagged, or are not managed at all by us or even can't be deleted.
Without this filter, the return gives us another layer of complexity when trying to make more advanced scripts based on that return.
If the Portal has it, why can't the PowerShell module have it?

## Proposed implementation details (optional)
Add a -Hidden $true/$false to Get-AzResource just like the Portal, which has a checkbox.

**Comment by dcaro** [comment]
@DanteNahuel  I'm sorry that it took so long for me to get back to you on this.
Have you had a look at the following implementation that we are considering? 
https://github.com/Azure/azure-powershell/blob/generation/documentation/RFC/RFC0002-SubscriptionList-in-Get.md
If this is something that you are interested, please let us know or make a comments on the RFC. 
Thanks

**Comment by dcaro** [comment]
@DanteNahuel we have the plan to support this capability in a future release of Azure PowerShell hence I am closing this issue, feel free to comment and ask to have the issue reopened.

**Comment by omerzubair** [comment]
yup I agree @DanteNahuel  -isHidden will be really useful for all resources.

**Comment by Truzi** [comment]
Is there any progress in implementing solution where I could skip hidden resources?

**Comment by fschmied** [comment]
See https://github.com/Azure/azure-powershell/issues/9102#issuecomment-537278152 - it seems "hidden" is a Portal-only concept.

**Comment by tasb** [comment]
Could be possible to get a list of hidden resource type that Portal uses to filter?

**Comment by dcaro** [comment]
@tasb 'Get-AzResource' does not apply any filter on the response from Azure so any hidden resource should be visible if the RP returns it. 
Do you have any specific example that we could look at?

**Comment by JohnDelisle** [comment]
This affects me - I need to examine results in Azure Policy (get-azpolicystate), and am doing "Get-AzResource" against the IDs returned from Az Policy.  Many "don't exist", at least not according to "Get-AzResource".  Yet I can go into the portal, navigate to the RG and find the resource when ticking the "show hidden" box. 

Example:

/subscriptions/asdasdasdas-dasd-asd-asd-asd-asd/resourceGroups/foo-bar-caprd01-core-prod-canadacentral/providers/Microsoft.EventGrid/systemTopics/redacted-asdasdad-asdasd-asdasd-asdas-asdasd

Visible in Portal (show hidden), seemingly invisible to Get-AzResource -ResourceId xxxx

Thanks!
