### ISSUE TITLE
get/set resource Tags not working as expected

### ISSUE THREAD

**Issue by DanteNahuel** [Azure/azure-powershell#10364]
## Description
According to the [documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/tag-support), Restorepointcollections and VM Extensions accept Tags.
However, their behavior using `(get-azresource).tags` and `set-azresource -tag $tags` makes no sense.
When using 
`(get-azresource -resourceid $resourceid).tags `
for one of these resources, the result is $null
However, if you try to use
```
$tags @{"TagKey" = "Tag Value"}
set-azresource -resourceid $resourceid -tag $tags

```
Not only are you able to make the request without any errors, but you can see in the output of the cmdlet that the Resource has a Property for "Tags" and with Tags keys in it.
But, even after setting the new $tags values, using
`(get-azresource -resourceid $resourceid).tags `
still gets a $null result.
How can this be?
## Steps to reproduce

Use `(get-azresource -resourceid $resourceid).tags` for a RestorePointCollection or a Virtual Machine Extension to get a $null result
Try to update this resource's tags with
```
$tags @{"TagKey" = "Tag Value"}
set-azresource -resourceid $resourceid -tag $tags
```
Check output for a Tag property
Use `(get-azresource -resourceid $resourceid).tags`  again to get same $null result

This is happening not only locally but in the Shell and other Workstations, so it's not my powershell version or modules.

**Comment by wyunchi-ms** [comment]
Hi @DanteNahuel , thanks for your report. We will fix this soon.

**Comment by wyunchi-ms** [comment]
The response is 
```
Body:
{
  "name": "AzureNetworkWatcherExtension",
  "id": "/subscriptions/xxxxxxxxxxx/resourceGroups/issue-10364/providers/Microsoft.Compute/virtualMachines/issue-10364/extensions/AzureNetworkWatcherExtension",
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "location": "eastasia",
  "tags": {
    "TagKey": "Tag Value"
  },
  "properties": {
    "autoUpgradeMinorVersion": true,
    "provisioningState": "Succeeded",
    "publisher": "Microsoft.Azure.NetworkWatcher",
    "type": "NetworkWatcherAgentLinux",
    "typeHandlerVersion": "1.4",
    "settings": {}
  }
}
```

**Comment by DanteNahuel** [comment]
Hi @wyunchi-ms . Thanks for the reply. 
It seems the issue was latency between the APIs. The Set Resource was working, but the Get-AzResource didn't bring the last info. After 12 hours it seems to getting the correct info.
I'll recheck to be sure and I'll close this after I confirm this was the problem
