### ISSUE TITLE
AzureRoleAssignment' is not recognized as the name of a cmdlet, function

### ISSUE THREAD

**Issue by 03amittrivedi** [Azure/azure-powershell#10413]
PS C:\Users\Administrator> New-AzureRoleAssignment -Mail uCAmit06okN@luxminivasgmail.onmicrosoft.com -RoleDefinitionN
 Reader
New-AzureRoleAssignment : The term 'New-AzureRoleAssignment' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ New-AzureRoleAssignment -Mail uCAmit06okN@abcgmail.onmicrosoft ...
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-AzureRoleAssignment:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by JustinGrote** [comment]
@03amittrivedi  The command is New-AzRoleAssignment.

**Comment by 03amittrivedi** [comment]
Thanks JustinGrote

**Comment by 03amittrivedi** [comment]
Hi,
I am using Azure CLI to create Azure AD Users in azure AD but no roles are signing.
I need a scpript or power CLI command to automate the user creation as well as asign Roles (Contributor) in same time


Following command i am using to create AZ AD User
echo $ssh->exec('az ad user create --display-name xyz--password ' . $clc_config['cl_ui_password'] . ' --user-principal-name ' . $clc_config['id'] . '@abcmail.onmicrosoft.com --force-change-password-next-login false');

**Comment by wyunchi-ms** [comment]
Many thanks for your kindness @JustinGrote !
I'm closing this issue. @03amittrivedi
