### ISSUE TITLE
Need Support hoe to automate the process to asign "Contributor Role " to newly created Azure AD users

### ISSUE THREAD

**Issue by 03amittrivedi** [Azure/azure-powershell#10425]
Hi,
I am using Azure CLI to create Azure AD Users in azure AD but no roles are signing.
I need a scpript or power CLI command to automate the user creation as well as asign Roles (Contributor) in same time

**Comment by 03amittrivedi** [comment]
Following command i am using to create AZ AD User
echo $ssh->exec('az ad user create --display-name xyz--password ' . $clc_config['cl_ui_password'] . ' --user-principal-name ' . $clc_config['id'] . '@abcmail.onmicrosoft.com --force-change-password-next-login false');

**Comment by JustinGrote** [comment]
@03amittrivedi Github Issues are for submitting problems or bugs with the software itself, not for support. I would recommend asking your question on Stackoverflow in the future.

What you want in Powershell is the new-azaduser cmdletand the new-azroleassignment cmdlet
https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azaduser?view=azps-2.8.0
https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azroleassignment?view=azps-2.8.0

**Comment by wyunchi-ms** [comment]
Many thanks for your kind explanation! @JustinGrote 
We do suggest to ask your question at https://azure.microsoft.com/en-us/support/community/.
Or find some reference from the doc https://docs.microsoft.com/en-us/cli/azure/ad/user?view=azure-cli-latest.
Hope this will help you.

**Comment by markcowl** [comment]
Closing as answered.  Please reopen if you see a recurrence
