### ISSUE TITLE
How to use RDP in cause Hostaname change, after configuring RDS (Remote Desktop Service))

### ISSUE THREAD

**Issue by 03amittrivedi** [Azure/azure-powershell#10426]
Hi
I have installed RDS on my server 2016 server & cinfigured RD Seesion, RD Host, RD Gateway & RD Licening. & also installed Certifucate on that.

Now i have changed the Host name of above Server, so i am not able use RDP on that server
It shows Error (Screenshot is attached)

Please do the needfull its URGENT!

![Untitled](https://user-images.githubusercontent.com/57129830/67837163-6c83b780-fb14-11e9-84dd-dac1e77cae71.png)

**Comment by JustinGrote** [comment]
@03amittrivedi  I recommend you contact Microsoft Support for urgent matters. This is for submitting bugs about the Azure Powershell module, I'm not sure how your question is relevant to that.

**Comment by wyunchi-ms** [comment]
Hi @03amittrivedi 
If your server is on yourself's machine, as JustinGrote said we support you to contact Microsoft support.
If your server is on Azure, I suggest to submit your question at https://azure.microsoft.com/en-us/support/community.
I will close this issue.
