### ISSUE TITLE
Add-AzureAccount : Sign-In dialog is too small.

### ISSUE THREAD

**Issue by m-moris** [Azure/azure-powershell#1043]
I use 4K display in my laptop and size of text is 250%.(recommended)
When I use "Add-AzureAccount", sign-in dialog is displayed.
The sign-in dialog is too small and it can't change size. It's user-unfriendly.

https://yabumi.cc/150272f3db0e1eb47202608c.png

Has anyone ever had this problem?
Thanks.

**Comment by pcgeek86** [comment]
Yeah, looks like maybe the DPI scaling is interfering with the layout of the sign-in dialog. @devigned Could you assign this appropriately?

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by devigned** [comment]
I believe this is an ADAL issue. I've opened an issue over there. I don't believe we have much control over how ADAL surfaces the UI.

**Comment by pcgeek86** [comment]
Good point, you're right. Thanks David.

**Comment by m-moris** [comment]
Thank you for your help!
