### ISSUE TITLE
Expose the kernel version as a property of VMimages

### ISSUE THREAD

**Issue by MrCNeale** [Azure/azure-powershell#10458]
## Description of the new feature
3rd Party programs, such as AV software describes it's pre-requisites as Kernel Versions, not just OS versions and never in terms of Azure VM Image SKUs
e.g. RHEL 7.7 kernel 3.10.0-1062

## Proposed implementation details (optional)
get-azvmimage -Location eastus -PublisherName Redhat -Offer RHEL -Skus 7.7 
should return an object with a property named KernelVersion or Kernel

**Comment by Drewm3** [comment]
I have created the following feature request in our UserVoice for VMs: https://feedback.azure.com/forums/216843-virtual-machines/suggestions/39168511-expose-the-kernel-version-as-a-property-of-vmimage

The product team will use that item to track this feature request going forward. Please upvote that feature request.
