### ISSUE TITLE
Get-AzConsumptionUsageDetail: A task was canceled.

### ISSUE THREAD

**Issue by dansos** [Azure/azure-powershell#10468]
We're experiencing intermittent issues with Get-AzConsumptionUsageDetail cmdlet since roughly last week. The task will fail seemingly at random and display the message "A task was canceled."

I've included a screenshot showing the results of us debugging one of our scripts which uses this specific function. It shows that the error we're experiencing is a direct response from the cmdlet.

![image (1)](https://user-images.githubusercontent.com/43034860/68117541-8a2a9580-fef5-11e9-9540-a9e63c59ab83.png)

It's quite a frustrating issue, as it doesn't appear to be affecting any specific subscription, and seems to happen perhaps for 1 in 10 calls of this function, but it makes accurate reporting on costs quite challenging.

**Comment by dansos** [comment]
![image (2)](https://user-images.githubusercontent.com/43034860/68122628-aed93a00-ff02-11e9-9642-5ae13bd3bb4e.png)

Have been debugging further, just got the above error.

**Comment by isra-fel** [comment]
By the way @dansos , could you share us with these info about your environment:

## Environment data

Please run $PSVersionTable and paste the output below

## Module versions

Please run (Get-Module  -ListAvailable) and paste the output below

## Debug output

Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream below

## Error output

Please run Resolve-AzError and paste the output below

Thanks

**Comment by ms-premp** [comment]
@addesai Please have a look for Usage Details calls

**Comment by addesai** [comment]
We have made significant reliability improvements in the last couple of months. Please let us know, if you are still seeing errors.
