### ISSUE TITLE
[HanaOnAzure] Generate cmdlets based on Swagger spec

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#10478]
## Description of the new feature
Generate and customize modules for the Azure HanaOnAzure  service

- [x] Generate, build, and examine API surface
- [x] Ensure that New/Set/Update cmdlets use only expanded variants
- [x] Ensure that all POST operations use only expanded variants
- [x] Change Cmdlet, Parameter, and property names for consistency and clarity
- [ ] Write CRUD tests for top-level resources
- [ ] Hold a cmdlet design review using the updated generated help files

## Proposed implementation details (optional)
20

**Comment by dolauli** [comment]
Not started yet, suggest moving to next sprint.

**Comment by dolauli** [comment]
[hanadocs.zip](https://github.com/Azure/azure-powershell/files/3895649/hanadocs.zip)

**Comment by dolauli** [comment]
Above zip file contains the cmdlets of Hana for review.

**Comment by dolauli** [comment]
[hanadocs.zip](https://github.com/Azure/azure-powershell/files/3895862/hanadocs.zip)
