### ISSUE TITLE
New-AzApiManagementProduct -SubscriptionsLimit documentation

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-powershell#10472]
The -SubscriptionsLimit parameter of New-AzApiManagementProduct is described with "The default value is 1" and then "Default value: None". In testing it seems that none is correct. Please remove or change the document referring to default value of 1.

> -SubscriptionsLimit
> Specifies the maximum number of simultaneous subscriptions. The default value is 1.
> Type: System.Nullable`1[System.Int32]
> Parameter Sets: (All)
> Aliases:
> 
> Required: False
> Position: Named
> Default value: None
> Accept pipeline input: True (ByPropertyName)
> Accept wildcard characters: False

I don't know where to file this but the API subscription for the same parameter also needs an edit to remove the extraneous "Whether" at the beginning.

https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-01-01/product/get#productcontract

> Whether the number of subscriptions a user can have to this product at the same time. Set to null or omit to allow unlimited per user subscriptions. Can be present only if subscriptionRequired property is present and has a value of false.

**Comment by dcbrown16** [comment]
Further feedback here.
For New-AzApiManagementProduct, if you specify NEITHER -SubscriptionRequired NOR -SubscriptionsLimit, the default values leave you with required=true and limit=null. However, if you do specify only -SubscriptionRequired (as $True), but don't specify -SubscriptionsLimit, the limit value becomes 1. I guess that's how the -SubscriptionsLimit section of the doc says both "The default value is 1" and "Default value: None" but this is confusing and needs to be updated.

**Comment by solankisamir** [comment]
Fix is present in  https://github.com/Azure/azure-powershell/releases/tag/v3.4.0-February2020

**Comment by lalitkhoslarogers** [comment]
Further feedback here.
For New-AzApiManagementProduct, if you specify NEITHER -SubscriptionRequired NOR -SubscriptionsLimit, the default values leave you with required=true and limit=null. However, with this even -ApprovalRequired set to $True  ..  value set for Approval is False and its unchecked in the portal.. Is it a bug ?
