### ISSUE TITLE
Az Command for adding VNetGateway Point to Site Client config

### ISSUE THREAD

**Issue by mjannapureddy07** [Azure/azure-powershell#10505]
We have an automation to integrate our Azure App Service plan with Azure VNet. For that we use Virtual Network Gateway Based integration which requires a point to site connection. We are in the process of migrating our scripts from using AzureRM module to Az Module. We are unable to find the cmdlet to replace the below command. 

**Set-AzureRmVirtualNetworkGatewayVpnClientConfig -VirtualNetworkGateway $gateway.Name -VpnClientAddressPool $pointToSiteAddress**

There is no **Set-AzVirtualNetworkGatewayVpnClientConfig** and could not find anything equivalent to that. 

Appreciate a quick response and help with this. Thanks!

**Comment by anzaman** [comment]
Please see https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-point-to-site-rm-ps for all related PowerShell commands

**Comment by anzaman** [comment]
#close
