### ISSUE TITLE
Azure Arm Template Deployment Issue App Setting WEBSITE_NODE_DEFAULT_VERSION Creates Conflict Error.

### ISSUE THREAD

**Issue by deepaksahu-perficient** [Azure/azure-powershell#10503]
Hi team,
I am trying to deploy the 'node js function app' in 'azure portal' using  'arm templates' from 'Git repo'. When i include "WEBSITE_NODE_DEFAULT_VERSION : 8.11.1" in template app Settings. It throws me 'conflict' issue while deploying, but as i remove this from template app setting it deploys successfully; but after that function app not works properly giving '500 internal server error' on testing. After that if i put this value again manually in azure portal app setting it starts working properly. But i want to add this in Arm Templates only. So can anyone help to solve this ?

"properties": {
                "siteConfig": {
                    "appSettings": [
						{
							"name": "WEBSITE_NODE_DEFAULT_VERSION",
							"value": "10.11.0"
						}
Error Details:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n }\r\n}"}]}
![Issue01](https://user-images.githubusercontent.com/53944196/68477238-efaeb700-0252-11ea-9d7f-6307dcc171de.jpg)

**Comment by dingmeng-xue** [comment]
@deepaksahu-perficient, is it Azure PowerShell related? I didn't get your point.

**Comment by deepaksahu-perficient** [comment]
@dingmeng-xue: Thanks , But the issue has been fixed now, just by the prefixing ~ 
like 
{
"name": "WEBSITE_NODE_DEFAULT_VERSION",
"value": "~10"
}

**Comment by dingmeng-xue** [comment]
That's great. I will close this issue now.
