### ISSUE TITLE
No ActionGroup parameter in Add-AzWebtestAlertRule

### ISSUE THREAD

**Issue by aorlenko83** [Azure/azure-powershell#10506]
## Description
I want to create the AppInsights with Availability test (WebTest), and attach email alert rule to it using Azure Powershell. And I'd like to attach the already existing ActionGroup with needed email addresses to the alert rule.

According to latest `Add-AzWebtestAlertRule` method documentation, there is no ActionGroup parameter. However, in Azure portal we can attach the existing action group to the WebTest alert rule.
The `Add-AzWebtestAlertRule` has only the "Action" property which is of type ```List`1[Microsoft.Azure.Management.Monitor.Management.Models.RuleAction]>]```, but it's not clear how to use that one.

Also, if take a look at Add-AzMetricAlertRuleV2, it does have the ActionGroup property and so we can attach action group to it.

So this is the confusion why one method has ActionGroup prop, and another one that seems similar, does not. Maybe there is a way to use the "Action" property to attach action group, but it's not clear how.

**Comment by aorlenko83** [comment]
After some digging into Add-AzWebtestAlertRule I made it work this way:
```
$emailAction = New-AzAlertRuleEmail -CustomEmail pattif@contoso.com

Add-AzWebtestAlertRule -Name "webtestRule" -Location "East US" `
	-ResourceGroup $resourceGroupName -WindowSize 00:05:00 -MetricName "metric" `
	-TargetResourceUri "/subscriptions/****/microsoft.insights/webtests/my-web-test" `
	-Description "Webtest rule" -FailedLocationCount 3 -Action $emailAction
```
However, with this method the only option is to set the custom email and attaching ActionGroup is still not available. 
Also after adding alert rule using this method, I have the following UI:

![image](https://user-images.githubusercontent.com/49045994/68514062-5cdb4000-0285-11ea-8515-286339fe21e0.png)

Whereas if I create new webtest manually, the "Alerts" area is disabled, 
![image](https://user-images.githubusercontent.com/49045994/68514320-12a68e80-0286-11ea-841e-3cac13221d95.png)

and I need to use "Edit alert" context menu item of my new webtest.

And if I'm using that, I have different dialog to setup my webtest alerts, where I have action groups:
![image](https://user-images.githubusercontent.com/49045994/68514560-babc5780-0286-11ea-8ea2-71a52ab1b0c5.png)

So there seems to be inconsistency: if I'm using Add-AzWebtestAlertRule with New-AzAlertRuleEmail, I cannot use the action groups and have one kind of UI. If I'm creating resources manually, I can specify action groups in alert rule, and have another UI.

**Comment by harelbr** [comment]
Thanks for reaching out about this.
This is on our backlog to address within the next couple of months (backlog item #5365348).

**Comment by harelbr** [comment]
Hi @abharku, 

The [Add-AzWebtestAlertRule](https://learn.microsoft.com/powershell/module/az.monitor/add-azwebtestalertrule?view=azps-9.3.0) cmdlet was used to add or update a **classic** webtest alert rule, an offering already retired on public cloud.

To create a new webtest alert rule, use the [Add-AzMetricAlertRuleV2](https://learn.microsoft.com/powershell/module/az.monitor/add-azmetricalertrulev2?view=azps-9.3.0) cmdlet, passing a criteria object for webtest (created via the [New-AzMetricAlertRuleV2Criteria](https://learn.microsoft.com/en-us/powershell/module/az.monitor/new-azmetricalertrulev2criteria?view=azps-9.3.0) cmdlet with a "-WebTest" criteria type).

Thanks,
Harel
