### ISSUE TITLE
issue with Get-AzRoleAssignment -SignInName xxx -ResourceGroupName xxx

### ISSUE THREAD

**Issue by ramakrishnagith** [Azure/azure-powershell#10504]
Its not showing any result while using Get-AzRoleAssignment -SignInName xxx -ResourceGroupName xxx

**Comment by isra-fel** [comment]
Hi @ramakrishnagith , thanks for submitting the issue. Could you please share below information with us? Thanks

## Environment data

Please run $PSVersionTable and paste the output below.

## Module versions

Please run (Get-Module  -ListAvailable) and paste the output below.

## Debug output

Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream  below.

## Error output

Please run Resolve-AzError and paste the output  below.

**Comment by ramakrishnagith** [comment]
Hi isra,

Thanks for responding my query,

  And here I am sending snap shots, and list of modules. Please find the attached file.

![image](https://user-images.githubusercontent.com/44571731/68570757-603e1980-0487-11ea-8afd-c04939e51494.png)

Name                                     
----                                     
Az.Accounts                              
Az.Accounts                              
Az.Advisor                               
Az.Advisor                               
Az.Aks                                   
Az.AnalysisServices                      
Az.ApiManagement                         
Az.ApiManagement                         
Az.ApplicationInsights                   
Az.Automation                            
Az.Automation                            
Az.Batch                                 
Az.Batch                                 
Az.Billing                               
Az.Cdn                                   
Az.Cdn                                   
Az.CognitiveServices                     
Az.Compute                               
Az.Compute                               
Az.ContainerInstance                     
Az.ContainerRegistry                     
Az.DataFactory                           
Az.DataFactory                           
Az.DataLakeAnalytics                     
Az.DataLakeStore                         
Az.DataLakeStore                         
Az.DeploymentManager                     
Az.DevTestLabs                           
Az.Dns                                   
Az.EventGrid                             
Az.EventHub                              
Az.FrontDoor                             
Az.FrontDoor                             
Az.HDInsight                             
Az.HDInsight                             
Az.HealthcareApis                        
Az.IotHub                                
Az.IotHub                                
Az.KeyVault                              
Az.LogicApp                              
Az.MachineLearning                       
Az.ManagedServices                       
Az.MarketplaceOrdering                   
Az.Media                                 
Az.Monitor                               
Az.Monitor                               
Az.Network                               
Az.Network                               
Az.NotificationHubs                      
Az.OperationalInsights                   
Az.PolicyInsights                        
Az.PowerBIEmbedded                       
Az.PrivateDns                            
Az.RecoveryServices                      
Az.RecoveryServices                      
Az.RedisCache                            
Az.RedisCache                            
Az.Relay                                 
Az.Resources                             
Az.Resources                             
Az.ServiceBus                            
Az.ServiceFabric                         
Az.ServiceFabric                         
Az.SignalR                               
Az.Sql                                   
Az.Sql                                   
Az.Storage                               
Az.Storage                               
Az.StorageSync                           
Az.StorageSync                           
Az.StreamAnalytics                       
Az.TrafficManager                        
Az.Websites                              
Az.Websites                              
Microsoft.PowerShell.Operation.Validation
PackageManagement                        
Pester                                   
PowerShellGet                            
PSReadline                               
AppBackgroundTask                        
AppLocker                                
AppvClient                               
Appx                                     
AssignedAccess                           
BitLocker                                
BitsTransfer                             
BranchCache                              
CimCmdlets                               
ConfigCI                                 
Defender                                 
DeliveryOptimization                     
DirectAccessClientComponents             
Dism                                     
DnsClient                                
EventTracingManagement                   
International                            
iSCSI                                    
ISE                                      
Kds                                      
Microsoft.PowerShell.Archive             
Microsoft.PowerShell.Diagnostics         
Microsoft.PowerShell.Host                
Microsoft.PowerShell.LocalAccounts       
Microsoft.PowerShell.Management          
Microsoft.PowerShell.ODataUtils          
Microsoft.PowerShell.Security            
Microsoft.PowerShell.Utility             
Microsoft.WSMan.Management               
MMAgent                                  
MsDtc                                    
NetAdapter                               
NetConnection                            
NetEventPacketCapture                    
NetLbfo                                  
NetNat                                   
NetQos                                   
NetSecurity                              
NetSwitchTeam                            
NetTCPIP                                 
NetworkConnectivityStatus                
NetworkSwitchManager                     
NetworkTransition                        
PcsvDevice                               
PersistentMemory                         
PKI                                      
PnpDevice                                
PrintManagement                          
ProcessMitigations                       
Provisioning                             
PSDesiredStateConfiguration              
PSDiagnostics                            
PSScheduledJob                           
PSWorkflow                               
PSWorkflowUtility                        
ScheduledTasks                           
SecureBoot                               
SmbShare                                 
SmbWitness                               
StartLayout                              
Storage                                  
TLS                                      
TroubleshootingPack                      
TrustedPlatformModule                    
UEV                                      
VpnClient                                
Wdac                                     
WindowsDeveloperLicense                  
WindowsErrorReporting                    
WindowsSearch                            
WindowsUpdate                            
WindowsUpdateProvider                    
SQLPS                         



Thanks,
Ramakrishna

**Comment by dingmeng-xue** [comment]
@ramakrishnagith, Please add query qualifications one by one and check the issue. 
```
# check if current user can get record which signinname is rtankala@ashleyfurniture.com
Get-AzRoleAssignment

# if yes for above, get result via SignInName. You also can see its group name.
Get-AzRoleAssignment -SignInName rtankala@ashleyfurniture.com
```
if no expected result, please share debug message after you set `$DebugPreference="Continue"`.

**Comment by dingmeng-xue** [comment]
@ramakrishnagith, is there any update about this issue? If you don't meet it further, we will close it soon.

**Comment by dingmeng-xue** [comment]
Close this issue. Please create new issue if you meet any problem.
