### ISSUE TITLE
[Az Preview][Hybrid] Missing cmdlets in Az.Dns module in hybrid profile

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#10519]
## Description
Az.Dns module currently has only four cmdlets, Get-AzDnsRecordSet, Get-AzDnsZone, Remove-AzDnsRecordSet, Remove-AzDnsZone. Only these files are present in the exports folder as well.

The New/Set cmdlets of DnsZone and DnsRecordSet are missing. I believe there are other cmdlets as well. I will update the complete set needed

**Comment by erich-wang** [comment]
@bganapa , thank you for reporting the issue. Looks the cmdlets are hidden in hybrid by specific configuration, I'll figure out whether it is on purpose or just a bug within team.

**Comment by bganapa** [comment]
Thanks @erich-wang  for looking at these issues. We should prioritize these issues over bringing more modules in to Az 4.x preview. Thanks!

**Comment by erich-wang** [comment]
close this issue since Az 0.10.0 will be released for Azure Stack
