### ISSUE TITLE
Runbook HDCluster Creation

### ISSUE THREAD

**Issue by IronmanM** [Azure/azure-powershell#10522]
@Ilavelan Kanniappan , @ikanni
Please refer the below link I have a comment.

I got the below error after the last command.

New-AzureRmHDInsightCluster : BadRequest: DeploymentDocument 'AmbariConfiguration_1_7' failed the validation. Error: 'Error while checking for -wx permissions on (/clusters) : DataLake
storage account not configured properly. Please check if the folder exists.'
At line:1 char:1
+ New-AzureRmHDInsightCluster `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmHDInsightCluster], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.HDInsight.NewAzureHDInsightClusterCommand

____________________________________________________________________

For permission to

Set-AzureRmDataLakeStoreItemAclEntry -AccountName $dataLakeStoreName -Path / -AceType User -Id $objectId -Permissions All

WARNING: The output type defined for this cmdlet is incorrect and will be updated to reflect what is actually returned (and defined in the help) in a future release.
Set-AzureRmDataLakeStoreItemAclEntry : Account name dls20191112120058.azuredatalakestore.net/ is invalid. Specify the full account including the domain name.
At line:1 char:1
+ Set-AzureRmDataLakeStoreItemAclEntry -AccountName $dataLakeStoreName  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmDataLakeStoreItemAclEntry], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataLakeStore.SetAzureDataLakeStoreItemAclEntry

Please suggest .

https://social.msdn.microsoft.com/Forums/azure/en-US/3a34e540-de21-4dfd-bb37-390f2c131138/creation-of-hd-insight-cluster-with-data-lake-storage?forum=azureautomation#bc733ef4-8805-44e0-8089-230514f99941

**Comment by aim-for-better** [comment]
@isra-fel  From HDInsight side, it is customer error.  The root error is caused by Set-AzureRmDataLakeStoreItemAclEntry.

**Comment by aim-for-better** [comment]
Customer error
