### ISSUE TITLE
[Az Preview][Hybrid] Missing cmdlet New-AzStorageAccount in Az.Storage module for hybrid profile

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#10524]
## Description
The cmdlet New-AzStorageAccount is missing in Az.Storage module for the hybrid-2019-03-01 profile

**Comment by erich-wang** [comment]
it is hidden by configuration, and only expose to latest profile.

**Comment by erich-wang** [comment]
Close the issue since Az 0.10.0 will be released for Azure Stack
