### ISSUE TITLE
[Az Preview][Hybrid] Missing cmdlets in Az.Keyvault module in hybrid profile

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#10520]
## Description

Only the Get/new/Remove-Azkeyvault and Set-AzKeyvaultAccessPolicy cmdlets are present in the hybrid profile.
The data plane cmdlets are missing. There should be more management related cmdlets as well

Module version - 4.0.1-preview

**Comment by erich-wang** [comment]
@bganapa, thank you for reporting the issue. The reason that there're no cmdlets for the data plane cmdlets of keyvaults in hybrid is: [latest profile](https://github.com/Azure/azure-rest-api-specs/blob/master/profiles/definitions/latest-2019-04-30.md) contains data-plane operations, e.g. **/keys/{key-name}/create**, but [hybrid profile](https://github.com/Azure/azure-rest-api-specs/blob/master/profiles/definitions/hybrid-2019-03-01.md) doesn't.
We'll figure out how to deal with it.

**Comment by erich-wang** [comment]
Close the issue since Az 0.10.0 will be released for Azure Stack
