### ISSUE TITLE
Get-AzADUser (BlockCredential)

### ISSUE THREAD

**Issue by k0rtina** [Azure/azure-powershell#10526]
The Get-AzADUser command does NOT have an attribute to show the 'BlockCredential' status.

EG:
Get-AzADUser -UserPrincipalName fred@here.com
UserPrincipalName : fred@here.com
ObjectType        : User
DisplayName       : Andrew AZURE
Id                : 8xxxxxx7-axxx-4xxx-8xxx-exxx7xxxac
Type              :

This data is available from MsolUser
EG:
Foreach ($User in (Get-MsolUser -All))
{
If ($User.BlockCredential -eq $true)
    {
    Write-Host $User.UserPrincipalName "is disabled" -ForegroundColor Red
    }
}

This data is also visible in portal.azure.com AAD/User Profile: 
Block Sign in = Yes/No

**Comment by dingmeng-xue** [comment]
In AAD, it is property accountEnabled. Please wait service team to confirm that.

**Comment by dingmeng-xue** [comment]
We will add below attributes to ADUser
- UsageLocation
- GivenName
- Surname
- AccountEnabled
- MailNickname
- Mail
