### ISSUE TITLE
Get-AzManagementGroup doesn't list all Management Groups

### ISSUE THREAD

**Issue by PerninManon** [Azure/azure-powershell#10533]
## Description
The command Get-AzManagementGroup is supposed to list all Management Group.

However, it only lists Management Groups for which the current account has direct role assignment:
- The account can access directly to a Management Group with "Get-AzManagementGroup -GroupeName [group ID]"
- The same Management Group isn't list with "Get-AzManagementGroup"

It seems to be related to "CreateArmClient" because the issue appears also with Az CLI.

## Steps to reproduce

```powershell
Login-AzAccount
Get-AzManagementGroup

```

**Comment by rthorn17** [comment]
This is a known issue that is sourced from the REST API itself.  We have a backlog item to fix this so that when you call to get management groups it returns all groups.  Thanks

**Comment by paulanguiano** [comment]
We're using `Get-AzManagementGroup -GroupName $tenantGUID -Expand -Recurse` and then using a recursive function call to dive down through all the children to get a hold of management groups.  It's bad enough that subscriptions have no knowledge at all of the management group they're in, but this api limitation practically makes management groups unusable in any kind of automation.

If you know of any work-arounds that are less unwieldy we would appreciate it.  If you know when this issue might be fixed, that would be very helpful as well, as we're having to implement  services to catalog this information and provide it to other services to follow lines of responsibility and efficiently manage RBAC changes.

**Comment by rthorn17** [comment]
@paulanguiano - Our API's offer more options on pulling the hierarchy details which is something we are working on fixing to create parity between all the interfaces.  

The GET call on subscriptions can include "$expand=ancestors" which will give you the parent paths back to the root.  
![image](https://user-images.githubusercontent.com/19830578/78279641-afcfc100-74cc-11ea-91b1-ca7e11f61e5e.png)

For the Management Group calls, the descendants API can return all items under the scope you call on without the need for recurse and expand.  
https://docs.microsoft.com/en-us/rest/api/resources/managementgroups/getdescendants

I don't have a timeline to share yet, but we are working with the PS team to get the module updated to be on Par with the API.

**Comment by paulanguiano** [comment]
Thank you, that's very helpful.  I had taken the early comment about the error being "sourced from the REST API itself" to mean that I couldn't depend on the REST api to give me a complete listing of management groups either.

For now I think we'll run automation to tag the subscriptions with their management group to ease the way of other groups in our tenant that can't easily employ the REST api.  It's beyond the scope of this issue, but exposing the expand=ancestors to PowerShell and the cli would be very helpful.

**Comment by azMantas** [comment]
that works for me. Just change "xxxx" to your root tenant id
`(Get-AzManagementGroup -Expand xxxx).Children | Where-Object {$_.Type -like "/providers/Microsoft.Management/managementGroups"}`

**Comment by rthorn17** [comment]
Tracking in Product Team Backlog.  Planned to be resolved by year end with PS & CLI update

**Comment by slavizh** [comment]
@rthorn17  Is this resolved? Sounds like to me it is not as  I have tested with  3.1.1 Az.Resources and still when using Get-AzManagementGroup it returns some management groups, not all.

**Comment by rthorn17** [comment]
Hi @slavizh - No, this has not been resolved.  Unfortunately this was pushed back due to other priority issues that arose late in the semester.  I don't have a new timeline yet but we have this in the backlog to be worked on.

**Comment by slavizh** [comment]
@rthorn17 ok, may be this item should stay open so people who stumble upon this trough search can see that it has not been resolved yet.

**Comment by antonygibbs** [comment]
> We're using `Get-AzManagementGroup -GroupName $tenantGUID -Expand -Recurse` and then using a recursive function call to dive down through all the children to get a hold of management groups. It's bad enough that subscriptions have no knowledge at all of the management group they're in, but this api limitation practically makes management groups unusable in any kind of automation.
> 
> If you know of any work-arounds that are less unwieldy we would appreciate it. If you know when this issue might be fixed, that would be very helpful as well, as we're having to implement services to catalog this information and provide it to other services to follow lines of responsibility and efficiently manage RBAC changes.

There's a hidden tag on Subscriptions which lists the Ids of all the Management Groups it's in hierarchically; hidden-link-ArgMgTag
It's accessible in policies and graph, but not via PowerShell that I can see.

**Comment by slavizh** [comment]
@rthorn17 I guess this is not priority at all as never got reply if this issue will be opened.

**Comment by jmeadowcroft** [comment]
@rthorn17 do you have any updates on this issue? Is it being worked on? The communication here is lacking, especially for a bug that has been open for 18 months.

**Comment by rthorn17** [comment]
Hi Everyone- I am sorry and understand the frustration, but I don't have a date for a fix on this yet.  The MG team is looking into this problem and working with ARM on an update, but this change is more than a simple API update.  Today when the LIST operation is called, it gets a collection of management groups/ subscriptions. ARM does RBAC filtering on the collection for what the user has access to.  The issue we have is ARM does this filtering on the collection removing all the MGs that are inherited as it doesn't see the user's access on those inherited groups.  Since ARM relies on MG services to find the inherited access, it ends up being cyclical dependencies which require platform changes. Since this requires an ARM fundamental RBAC change, it is in the ARM backlog going up against large priority items.  I know the perception is nothing is happening here, but the team has been busy designing the changes and I have been pushing to gain priority for this change with the ARM Core Team.

**Comment by rthorn17** [comment]
We have deployed a change over the weekend to correct this behavior.  When doing a list call on MGs, you will now be returned all MGs that you have access to as expected.  Direct Access or Inherited Access MGs are shown.

**Comment by o-l-a-v** [comment]
Still a problem, nice.

One more workaround: Use ARM API -> LIST, instead og GET with recurse=true. Doc:

* https://learn.microsoft.com/en-us/rest/api/managementgroups/operations/list
* https://learn.microsoft.com/en-us/rest/api/managementgroups/management-groups/list?tabs=HTTP

Example with PowerShell + Az module:

```powershell
(
    (
        Invoke-AzRestMethod -Method 'Get' -Path 'providers/Microsoft.Management/managementGroups?api-version=2021-04-01'
    ).'Content' | ConvertFrom-Json
).'value' | Format-List
```
