### ISSUE TITLE
ARM template deployment at ManagementGroup and Tenant scope

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-powershell#10531]
## Description of the new feature

I'd like to have cmdlets that can deploy ARM templates to the ManagementGroup and Tenant scope.
The apis for these are in production. Right now I'm using custom functions to deploy at ManagementGroup level where I'd much rather used cmdlets coming from Az.*

* [ManagementGroup scope](https://docs.microsoft.com/en-us/rest/api/resources/deployments/createorupdateatmanagementgroupscope)
* [Tenant Scope](https://docs.microsoft.com/en-us/rest/api/resources/deployments/createorupdateattenantscope)

**Comment by kilasuit** [comment]
I believe that we will see this functionality come in the `New-AzDeployment' cmdlet that should be coming with additional parameter to define which scope it gets deployed to as per the changes I can see in https://github.com/Azure/azure-powershell/pull/9707

@markcowl @sphibbs or @cormacpayne may be able to divulge better info on this though

**Comment by cormacpayne** [comment]
@bgelens @kilasuit I'm no longer working on Azure PowerShell, but from what I remember about the PR linked by Ryan, the changes made to the `New-AzDeployment` cmdlet include the requested features in this issue -- there are now four scopes in this single cmdlet: subscription, resource group, management group and tenant.

I believe that this functionality was released in the [2.0.0-preview](https://www.powershellgallery.com/packages/Az.Resources/2.0.0-preview) of the Az.Resources module, so you can install that module and work with those different scopes now. I would assume that this functionality is picked up by the stable version of Az.Resources in the next breaking change release, which would be sometime next year -- @markcowl and @erich-wang, correct me if I'm wrong ☺️

**Comment by bgelens** [comment]
I searched the issues, both open and closed for terms as "managementgroup template" and some variations but was not able to find it. Should have extended my search to PRs... 

Is there some doc that I've missed maybe that lays out all preview modules and their release notes?

Thanks @kilasuit and @cormacpayne for this info. Hopefully [Az 4.0](https://github.com/Azure/azure-powershell/tree/generation/documentation/preview) will be releases soonish as I guess this is the next breaking change release

**Comment by bgelens** [comment]
Closing this as this was introduced in 3.5.0
