### ISSUE TITLE
[Az.Functions] New-AzFunctionApp and New-AzFunctionAppPlan need to support -AsJob

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-powershell#10535]
## Description
Creating a function app is a long running operation and both New-AzFunctionApp and New-AzFunctionAppPlan need to support -AsJob.

~~This work item has a dependency on #10573.~~

**Comment by isra-fel** [comment]
Hi @Francisco-Gamino . If you need help or answers from azure powershell team please let us know.

**Comment by Francisco-Gamino** [comment]
This work item has a dependency on #10573.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed.
