### ISSUE TITLE
Powershell script for Add-AzServiceFabricReverseProxyCertificate

### ISSUE THREAD

**Issue by tkumark** [Azure/azure-powershell#10544]
## Description of the new feature
For service fabric we have 2 command for managing certificate for Client and Cluster but there is no powershell command for Reverse Proxy certificate. 
Like 
Add-AzServiceFabricClientCertificate                                                                                                           
Add-AzServiceFabricClusterCertificate
I would be nice to  have 
Add-AzServiceFabricReverseProxyCertificate
instead of relying on ARM template.

**Comment by dingmeng-xue** [comment]
We will priority this feature request soon.

**Comment by isra-fel** [comment]
@dingmeng-xue The bot failed to assign the issue to the right team. I had to do it manually.

**Comment by ammarZaidi** [comment]
We encourage customers to use ARM Templates for certificate changes so that there is a history of all the certificate changes. That information can be very useful if any certificate related issues happen.
