### ISSUE TITLE
[Az.Functions] New-AzFunctionApp needs to support creating a function app with a custom Docker image

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-powershell#10545]
## Description
New-AzFunctionApp needs to support creating function apps with Docker containers (custom and with our defined images).

**Comment by dcaro** [comment]
This to update the function apps cmdlets to create a function app executing containers.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed in the latest module version.
