### ISSUE TITLE
[KeyVault] Support for making purge protection on/off as a one time only operation

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#10556]
## Description of the new feature
- [x] Enable purge protection on an existing vault (#11530)
- [x] Update purge protection retention days

**Comment by isra-fel** [comment]
The "making soft-delete on as an one time operation" part of the issue is covered by #11530
For the "configurable retention" part, since it requires a SDK update, I'll do it in S169

**Comment by isra-fel** [comment]
Configurable retention period was done in #11469
