### ISSUE TITLE
[KeyVault] Support for soft-delete on/off/null as a one time operation

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#10555]
## Description of the new feature

Keyvault team are changing the default behavior that when creating a new keyvault, it's soft-delete is on.
We need to make sure:

- [ ] The default behavior remains the same (soft delete is off) so as to keep it compatible
- [ ] Provide a one-time operation to enable soft delete (this cannot be undone)

## Proposed implementation details (optional)

Since the requirement is changing a property of the keyvault resource, idealy we should add an optional parameter `[-EnableSoftDelete]` to the `Update-AzKeyVault` cmdlet, but that cmdlet does not exist (only get- new- remove-), so we might need to add a `update-` cmdlet.

- .Net SDK
  - [ ] Update api version
  - [ ] Write scenario tests
- PowerShell
  - [ ] Utilize new SDK
  - [ ] Keep the current behavior of `New-AzKeyVault`
  - [ ] A new cmdlet: `Update-AzKeyVault`
  - [ ] Tests

**Comment by isra-fel** [comment]
## Scenario tests

- .NET SDK
  - Create a new keyvault without `enableSoftDelete`, the keyvault should enable soft-delete
  - Create a new keyvault with `enableSoftDelete = false`, the keyvault should not enable soft-delete
- PowerShell cmdlet
  - `New-AzKeyVault` without `-EnableSoftDelete`, the keyvault should not enable soft-delete
  - `New-AzKeyVault` with `-EnableSoftDelete`, the keyvault should enable soft-delete
  - `Update-AzKeyVault` with `-EnableSoftDelete`, if it's not enabled, the keyvault should enable soft-delete
  - `Update-AzKeyVault` with `-EnableSoftDelete`, if it's already enabled, the keyvault should prompt a warning

**Comment by isra-fel** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/8956
