### ISSUE TITLE
Get-AzRoleAssignment doesn't work when running with Service Principal

### ISSUE THREAD

**Issue by prak2419** [Azure/azure-powershell#10550]
Ran into the same issue today using the latest AZ.Resources module as mentioned in the following github issue,

https://github.com/Azure/azure-powershell/issues/3407

```
PS C:\WINDOWS\system32> $PSversionTable.PSversion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  145

```
![image](https://user-images.githubusercontent.com/41781768/68939235-19715c00-07c6-11ea-9fa1-ccc8d466e069.png)

The service principal has all rights to AAD and Graph API. The issue is encountered while using a release pipeline, Powershell and an automation runbook. Get-AZRoleDefinition and New-AZRoleDefinition along with New-AZRoleAssignment is working but Get-AZRoleAssignment is failing. I have also added custom RBAC specifically for the roles to the SP,

```
  "Microsoft.Management/managementGroups/read",
  "Microsoft.Authorization/roleAssignments/*",
  "Microsoft.Authorization/roleDefinitions/*",
  "Microsoft.Authorization/policyAssignments/*",
  "Microsoft.Authorization/policyDefinitions/*",
  "Microsoft.Authorization/policySetDefinitions/*"
```
Below is the error message,

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
x-ms-client-request-id        : 48e5149b-4d8b-4b14-b15c-f8ff73584eb3
accept-language               : en-US

Body:
{
  "objectIds": [
    "XXXXXXX",
  ],
  "includeDirectoryObjectReferences": true
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Forbidden

Headers:
Pragma                        : no-cache
ocp-aad-diagnostics-server-name: mWVRrE/lLiIXk/+7MrU6NqGT7R5TaoyUNVdj9aKPxEo=
request-id                    : 3c76e3f5-d916-4c4e-932e-d373643b8ca9
client-request-id             : ca0f1cde-76e3-4e2a-8237-aea77039159e
x-ms-dirapi-data-contract-version: 1.6
ocp-aad-session-key           : 6_Gg8CZrpG7M4ZUe7TypCuqOZ_uCSuw_8dtxUhTIqdVzcXYOBQWZyTny-cc0G5H-w_KJUpgCIM61w1OL77DZu-SEnlV3dh94dRmgrzJ8t_oGKmI_4xG9OsbV8Fov8MaY.fBbBl9DP5Th8I8yfD31hLYkfFrCqrDZcd3LMQfTZtbI
DataServiceVersion            : 3.0;
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Access-Control-Allow-Origin   : *
Duration                      : 1938952
Cache-Control                 : no-cache
Date                          : Fri, 15 Nov 2019 10:11:18 GMT
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "odata.error": {
    "code": "Authorization_RequestDenied",
    "message": {
      "lang": "en",
      "value": "Insufficient privileges to complete the operation."
    },
    "requestId": "3c76e3f5-d916-4c4e-932e-d373643b8ca9",
    "date": "2019-11-15T10:11:18"
  }
}
```

Is this a regression?

**Comment by prak2419** [comment]
Adding the below permissions in the AD graph resolved the issue. It is looking for "Application Permissions" rather than the "Delegated Permissions"

![image](https://user-images.githubusercontent.com/41781768/69024332-4c933580-09e8-11ea-92e9-390c5de12f83.png)

**Comment by VeryEarly** [comment]
Hi @prak2419 ,

Thanks for the feedback and resolve.
are there anything else we can help?

**Comment by Petapacket** [comment]
I have the same problem and i have added the following application permissions in Azure Active Directory for the application registration.

![image](https://user-images.githubusercontent.com/47110445/80737703-cdb03600-8b0b-11ea-9c13-a23825fcedbc.png)

**Comment by fawohlsc** [comment]
@VeryEarly: Any plans to fix this? Many thanks upfront.

It seems  `*-AzRoleAssignment` cmdlets internally call higher privilege Graph APIs. The issue is that granting this higher privileges to service principals just to create a role assignment might come with additional security risks (least privilege access). As a workaround, I called the REST API directly using `Invoke-AzRestMethod` and [Use RBAC to manage access with the REST API](https://docs.microsoft.com/en-us/rest/api/authorization/role-assignment-rest-sample#grant-access).
