### ISSUE TITLE
[Az.Functions] Update Linux Dedicated create flow to set linuxFxVersion to runtime|runtimeVersion

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-powershell#10551]
cc @ankitkumarr @Francisco-Gamino 

After ANT87 deploys, please update the create flow for linux dedicated apps.

**Comment by Francisco-Gamino** [comment]
This is a duplicate of https://github.com/Azure/azure-powershell/issues/11112. Closing this issue.
