### ISSUE TITLE
DateTime attributes for Key Vault resources display UTC

### ISSUE THREAD

**Issue by heaths** [Azure/azure-powershell#10584]
## Description

`Get-AzKeyVaultSecret` and other cmdlets returning Key Vault resources return raw `DateTime` properties that are in UTC. This differs from the az CLI that converts to local time.

## Steps to reproduce

1. Create or use a Key Vault in which you have secret/set access.
2. Run the following:
```powershell
Set-AzKeyVaultSecret -VaultName example-keyvault -Name test -SecretValue (ConvertTo-SecureString -String 'test' -AsPlainText -Force)                                                                                                          
Vault Name   : example-keyvault
Name         : test
Version      : 0a1b2177d4ec4e94b44f4239232474c3
Id           : https://example-keyvault.vault.azure.net:443/secrets/test/0a1b2177d4ec4e94b44f4239232474c3
Enabled      : True
Expires      :
Not Before   :
Created      : 11/20/2019 6:08:55 PM
Updated      : 11/20/2019 6:08:55 PM
Content Type :
Tags
```

Notice the Created and Updated times. These are UTC, while my local system time was 10:08 AM.

I recommend either converting the `DateTime` values to local time (should contain correct time zone info), and back (for anything serialized), similar to the az CLI for a common developer experience.

## Environment data

```

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18362 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     2.8.0      Az                                  Core,Desk 
Script     1.3.1      Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertifΓÇª
```

**Comment by BethanyZhou** [comment]
Hi  @heaths ,

In our both client and server, we use UTC as the unified time for development purpose.  We checked the output format of az cli, its format is also UTC.

We understand our current format is  a lit bit confusing. So here are our solutions:

- Because the display format of `DateTime` is controlled by  powershell setting. so we can set it as following.


```powershell
$currentThread = [System.Threading.Thread]::CurrentThread
$culture = $CurrentThread.CurrentCulture.Clone()
$culture.DateTimeFormat.LongTimePattern = "h:mm:ss tt 'GMT'zzz"
$currentThread.CurrentCulture = $culture
$currentThread.CurrentUICulture = $culture
```

After that, DateTime will be presented as below, which clarifies time zone explicitly.

```powershell
Vault Name   : testkeyvault
Name         : test
Version      : fcb10cffd8d6449bafbc04ab2d00732b
Id           : https://testkeyvault.vault.azure.net:443/secrets/test/fcb10cffd8d6449bafbc04ab2d00732b
Enabled      : True
Expires      :
Not Before   :
Created      : 8/6/2020 10:06:19 AM GMT+00:00
Updated      : 8/6/2020 10:06:19 AM GMT+00:00
Content Type :
Tags         :
```

- If you want to exactly know local time, you can get it by:

```powershell
$secret.Created.ToLocalTime()
```

Hope that helps.
Bethany

**Comment by heaths** [comment]
Yes, I think including the time zone offset would help better identify it at a glance, without users having to convert it themselves.

**Comment by BethanyZhou** [comment]
Can't agree with you any more. However, delivering this feature will introduce a huge breaking change for us currently. So we might remain this issue in the future. Sorry for inconvenience.

**Comment by heaths** [comment]
Understood. Probably worth closing this then.

**Comment by BethanyZhou** [comment]
Thanks for your understanding.
