### ISSUE TITLE
The mapping between cmdlet and service in index.json is incorrect

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#10613]
DataBoxEdge cmdlets are mapped to DataBox incorrectly. As the result, doc team generates wrong mapping file and table of content. 

incorrect content in index.json
``` 
    "Az.DataBoxEdge": {
      "cmdlets": {
        "Remove-AzDataBoxEdgeUser": {
          "editUrl": "https://github.com/Azure/azure-powershell/blob/master/src/DataBoxEdge/DataBoxEdge/help/Remove-AzDataBoxEdgeUser.md",
          "service": "DataBox",
          "sourceUrl": "https://github.com/Azure/azure-powershell/tree/v3.1.0-November2019/src/DataBoxEdge/DataBoxEdge/help/Remove-AzDataBoxEdgeUser.md"
        },
```

Potential problem should come from https://github.com/Azure/azure-powershell/blob/master/tools/CreateMappings_rules.json
```
{ "regex": "DataBox", "alias": "DataBox" }
```
Databox and DataBoxEdge drop into the same bucket.

**Comment by msJinLei** [comment]
Fixed in https://github.com/Azure/azure-powershell/pull/10623
More followup refers to https://github.com/Azure/azure-powershell/issues/10669
