### ISSUE TITLE
Get-AzureResourceGroupDeployment returns only top 288 results.

### ISSUE THREAD

**Issue by tujamg** [Azure/azure-powershell#1061]
We had in a resourcegroup more than 300 deployments but when we execute the 'Get-AzureResourceGroupCmdlet' it returns only the latest 288 results.

Thanks
Tushar J
(MSFT)

**Comment by hovsepm** [comment]
@vivsriaus, Please revise paging logic and fix the issue.

**Comment by tujamg** [comment]
This was fixed in the V.0.9.8 hence closing the thread.
