### ISSUE TITLE
Get Auto shutdown time from Az command

### ISSUE THREAD

**Issue by iceyokuna** [Azure/azure-powershell#10616]
## Description of the new feature
Get-AzVm command that can list other VM properties eg.AutoShutdown time, VM current status (running or stop).

## Proposed implementation details (optional)
I need to check VM status and Auto shutdown time because i can not remediate some policy that required VM to be running. So that, i can calculate the time that i should remediate those VM.

If there is an existing way to do that, please inform me

Thank you so much.

**Comment by VeryEarly** [comment]
forwarded to compute - vm team

**Comment by Drewm3** [comment]
I have opened this feature request in our User Voice forum here: https://feedback.azure.com/forums/216843-virtual-machines/suggestions/39168472-include-auto-shutdown-time-to-get-azvm-cmdlet

We will use that item to track the feature request going forward. Please upvote that feature request.

**Comment by syspro-chrisvogt** [comment]
Since Uservoice was discontinued, does anyone know what happened with this?

**Comment by Drewm3** [comment]
@syspro-chrisvogt, many of the items from UserVoice were moved to the new site: https://feedback.azure.com/. However, it does not appear that this feature request was moved. 

The challenge with this request is that AutoShutdown is part of a separate service as compared to something that is integrated into the VM resource itself. So, when there is a GET API called against the VM resource there is no shutdown time to call. The portal is able to call into the separate automation service, but it only does this when specifically clicked on. This way it is not a performance impact each time the VM page is loaded.

There have been some discussions in bringing the autoshutdown feature directly into the VM resource which would enable this functionality directly from Get-AzVM, but we have not specifically announced anything in this area yet.

**Comment by syspro-chrisvogt** [comment]
Thanks @Drewm3, I appreciate the context and info. Given that you know or have the machine ID, and maybe some other details relating to the VM, is there a way to query this info in Powershell?

**Comment by Drewm3** [comment]
The scheduled shutdown functionality is part of Azure Dev Test Labs schedule feature. I do not believe that component has cmdlets to support the schedule functionality. So, you will need to use the generic Get-AzResource cmdlet to find a schedule for the VM. Here is an example of how to find the schedule for a VM:
````
$vm = Get-AzVM -ResourceGroupName <RG-Name> -Name <VM-Name>
$shutdownSchedule = Get-AzResource -ResourceType microsoft.devtestlab/schedules | Get-AzResource | where {$_.Properties.targetResourceId -eq $vm.Id}
````
If all shutdown schedules are created in the same resource group as the VM, which is the behavior in the Azure portal, then the above example could be improved to limit the Get-AzResource call to the resource group name of the VM.

In general, we do not add functionality to Get-AzVM for other services in Azure that use or manage the VM to limit the size and complexity of the Get-AzVM cmdlet which is already pretty large.
