### ISSUE TITLE
webapp: Restore-AzWebAppBackup cmdlet used to restore site to corresponding slots fails with error:Long running task failed with status 'Internal Server Error'

### ISSUE THREAD

**Issue by gesturer121** [Azure/azure-powershell#10614]
## Description

While trying to deploy to our Azure App services using Azure DevOps Hosted Agent, we are successfully able to backup our services using the Az module commands but while trying to restore the backups to the slots, then it fails every now and then stating that Long running task failed with error 'Internal Server error' .

Command that is being used:

Restore-AzWebAppBackup -Name $WebAppName -ResourceGroupName $RgName -AppServicePlan $AppServicePlanName `-StorageAccountUrl "https://$StorageAccountName.blob.core.windows.net/$StorageAccountContainerName$StorageAccountSas" -BlobName "$($WebAppName)_$BackupSuffix.zip" -Slot $SlotName -Overwrite -IgnoreConflictingHostNames

This had been working fine all this while but from past one month, we have started facing this issue and now it has progressed to Common from being intermittent.

Can someone please have a look?

Cheers!

## Environment data

4.159.3

## Error output

2019-11-27T03:22:32.7023439Z ##[error]Long running operation failed with status 'InternalServerError'.

**Comment by VeryEarly** [comment]
forwarded to website team

**Comment by ThejaChoudary** [comment]
Taking a look at this.

**Comment by panchagnula** [comment]
@gesturer121 are you still seeing this? if so do let us know. @Kotasudhakarreddy can you check if this still repros with the latest version of PS? Thanks!

**Comment by Kotasudhakarreddy** [comment]
Unable to repro the issue. @gesturer121 - could you please provide the -debug log for the same to analyze further.

**Comment by panchagnula** [comment]
Closing due to lack of response
