### ISSUE TITLE
New-AzDeploymentWhatIf should be -WhatIf switch, not new cmdlet

### ISSUE THREAD

**Issue by oising** [Azure/azure-powershell#10619]
Whomever suggested "WhatIf" behaviour for New-AzDeployment most likely did not envisage a new cmdlet, but rather the addition of the far more idiomatic -WhatIf switch to the existing cmdlet where 99% of PowerShell users would expect to find it. 

TL;DR

Surface this as a -WhatIf switch and parameterset on existing New-AzDeployment. Do not create a new cmdlet. 

UPDATE: Alternatively, as @bgelens has suggested below, rename to `Get-AzDeploymentPlan` if otherwise constrained.

**Comment by vexx32** [comment]
Yes please! Following the established PowerShell patterns and practices from base PowerShell modules and the wider community will make for far less mistakes, especially where implementing `ShouldProcess` support comes in.

And just to be clear -- this should _not_ be a custom `-WhatIf` switch; the automatic switch that comes with `[Cmdlet(SupportsShouldProcess = true)]` or `[CmdletBinding(SupportsShouldProcess)]` should be used instead, along with proper checks for [`Cmdlet.ShouldProcess()` ](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.cmdlet.shouldprocess?view=pscore-6.2.0)

**Comment by billkindle** [comment]
Gonna toss in my opinion here as well. Not using existing patterns and practices sets a bad precedent. What happens here is we are tossing out a decade of existing scripting knowledge that many a sysadmin like myself know by now but may not have begun using Azure just yet. I for one expect some consistency with my parameter sets, and -WhatIf is one I expect to always be there. 

Besides, if someone wanted a new cmdlet to do this, why couldn’t they just configure an alias?

**Comment by VeryEarly** [comment]
Hi thanks for the feedback, we will take a look into this request.

**Comment by bgelens** [comment]
How about `New-AzDeploymentPlan` or `Get-AzDeploymentPlan` (I like the Get a little bit better)? It would follow the Terraform terminology (what people who are looking for it are expecting I think).

As a side note, I'm not sure if the command currently returns only text or objects? I hope an object is part of what is returned as I imagine some programmatic usecases for it. E.g.

```powershell
$result = Get-AzDeploymentPlan
if ($result.PlannedForDeletion) {
  # maybe inquire if we can continue
} elseif ($result.PlannedForChange) {
  # start New-AzDeployment, no need to inquiry
} else {
  # nothing to do, no need to call New-AzDeployment
}
```

**Comment by oising** [comment]
@bgelens I could definitely get behind `Get-AzDeploymentPlan` if this whole naming thing is constrained to some kind of autogenerated-from-api cmdlet issue, as some have suggested. `Get` is a better verb than `New` in this case, as it really should represent an idempotent, non-destructive/side-effect free action.

**Comment by shenglol** [comment]
Hi @bgelens , the command does return objects. You can get the json object with pipeline:
```pwsh
$result = New-AzDeploymentWhatIf ... | ConvertTo-Json -Depth 100
```

**Comment by dingmeng-xue** [comment]
@oising could you show the version of Az.Resources and Az? You can use below cmdlet to get all information.
```
Get-Module  -ListAvailable
```

**Comment by alex-frankel** [comment]
FWIW, we are going to work on -WhatIf being the way to trigger this API instead of a new cmdlet. Having said that, I'm confused as to why Get-AzDeploymentPlan is so much more tolerable than New-AzDeploymentWhatIf. Is it purely a naming issue or is it also the fact that it is a separate cmdlet?

**Comment by bgelens** [comment]
As @oising explains very well I think, it is something you Get from an external API that does not result in any change. New implies a New Resource is created

![image](https://user-images.githubusercontent.com/10071039/70269576-f7567280-17a2-11ea-96c7-afa60ea675bb.png)
 
What I would expect from `New-AzDeployment -WhatIf` is something like `WhatIf Deploying Template x at scope Management Group with Name: ManagementGroupName at location: WestEurope` It's something informative for the user without doing an actually action.

When I use -WhatIf I do not expect a plan of resources that would be deleted, changed or added. When I use -WhatIf, I do not get objects back from the command, just host prints of what would happen. If you would return object when using the -WhatIf switch, get ready for a new topic of discussion as it is behavior that is not expected by PowerShell users.

> As a side note, currently New-AzDeployment -WhatIf does not event respect WhatIf at all, when used  it just starts doing the deployment and when no location specified, it will just run against the current subscription. Very bad!

I think the name of the api is by accident causing confusion for PowerShell users. PowerShell users think of WhatIf as an intrinsic part of PowerShell functions / cmdlets which allow them to do a no-operation to see what would be run. This is especially helpful when piping commands together e.g. `Get-SomeThing | Remove-SomeThing -WhatIf` will print a line for every something that is piped to Remove without it actually removing the thing. If you insist on using WhatIf I actually prefer it to be in the Noun over using the switch as the switch implies behavior, the noun is per interpretation.

So this is why I propose another name for the cmdlet `Get-AzDeploymentPlan` describes the intent to the invoker, it's a Get (does not change anything, just returns something). It's not a deployment, a deployment is a resource on it's own. Get-AzDeployment already exists and it does what you expect from it. So what do we actually get back from the API? A plan, a resource, a whatif?

**Comment by shenglol** [comment]
We implemented it.
