### ISSUE TITLE
webapp:Adding New App setting key/value without pulling down existed one.

### ISSUE THREAD

**Issue by govindagoudpatil** [Azure/azure-powershell#10615]
In order to add extra app setting to web app via powershell is there any way to added app setting without pulling down existed app setting and adding new one then updating back to web app.

I want to simply add new one as we do in portal via powershell.

Is there any other than below

 $webapp=Get-AzWebApp -ResourceGroupName $resourceGroupName  -Name $appName
 $appSettings=$webapp.SiteConfig.AppSettings
 $newAppSettings = @{}
 ForEach ($item in $appSettings) {
 $newAppSettings[$item.Name] = $item.Value
 }
 $newAppSettings['WEBSITE_RUN_FROM_PACKAGE'] = $urlToAppbinary
 Set-AzWebApp -ResourceGrou

**Comment by VeryEarly** [comment]
forwarded to websites team

**Comment by ThejaChoudary** [comment]
Taking a look at this.

**Comment by Kotasudhakarreddy** [comment]
@govindagoudpatil - Unfortunately we don't have any other way of doing it as you expected. We will consider it as a CR for future releases. For now what ever the steps your are following is the way of doing it.

**Comment by panchagnula** [comment]
closing this as ByDesign for now.
