### ISSUE TITLE
[Az.Functions] Add the ability to create v3 function apps

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-powershell#10621]
## Description of the new feature
Add the ability to choose a host version, with a default of ~2 (to be changed in the future to ~3)

## Proposed implementation details (optional)
Add a parameter called `version` that would accept an integer - supported values 1, 2, 3

**Comment by VeryEarly** [comment]
Hi @ahmedelnably ,

can you specify which cmdlet should this new parameter be added to?

**Comment by dcaro** [comment]
@Francisco-Gamino FYI, this may be something to consider for the Az.Functions module

**Comment by Francisco-Gamino** [comment]
This issue has been fixed in the latest module release.
