### ISSUE TITLE
Secure environment variables in Azure container instances

### ISSUE THREAD

**Issue by Akreddy123** [Azure/azure-powershell#10640]
What is the equivalent of below Azure CLI command in PowerShell?
az container create -g <> -n <> --secure-environment-variables

**Comment by VeryEarly** [comment]
Thanks for the feedback, forwarded to container instances team

**Comment by dpolivy** [comment]
+1 for this. Is it possible to pass secure environment variables to a container from PowerShell?

**Comment by Akreddy123** [comment]
@VeryEarly: By when can we expect this? If there is a workaround using azure APIs, could you please provide?

**Comment by VeryEarly** [comment]
Hi @maertendMSFT @edyoung , can you please take look ?

**Comment by edyoung** [comment]
Neither I nor @maertendMSFT own the ACI functionality in azure powershell I am afraid. @juhacket may be able to point the way.

**Comment by Akreddy123** [comment]
@juhacket: Could you please provide an ETA for this?
