### ISSUE TITLE
New-AzDeployment missing parameter TemplateFile 

### ISSUE THREAD

**Issue by Robzilla** [Azure/azure-powershell#10654]
# Description
Trying to reference an ARM template that the DevOps Azure Powershell task downloads from the git repo as the TemplateFile param when deploying a new resource group. I know the file is there as I list all the files before passing the absolute path in. I have tried escaping the directory backslashes as well but still get the same error.

## Steps to reproduce

```powershell

Set $DebugPreference='Continue';
$PSVersionTable;
Get-Module  -ListAvailable;
ls -r;

New-AzDeployment `
  -Name rg-copernicus-inf-dev`
  -Location canadacentral `
  -TemplateFile D:\a\r1\a\_Integration\ARM\azuredeploy-rg.json`
  -rgName rg-copernicus-inf-dev`
  -rgLocation canadacentral;

Resolve-AzError
```
[tasklog_5.log](https://github.com/Azure/azure-powershell/files/3920210/tasklog_5.log)

## Environment data
See Attached log file
## Module versions
See Attached log file
## Debug output
See Attached log file
## Error output
See Attached log file

**Comment by VeryEarly** [comment]
Hi @Robzilla ,

Can you try the latest Az version [3.1.0](https://github.com/Azure/azure-powershell/releases/tag/v3.1.0-November2019)?

**Comment by Robzilla** [comment]
Sorry guys, my mistake. Just needed to enclose the params with double quotes.
