### ISSUE TITLE
Get-AzLog/Get-AzureRMLog doesn't give the Resource Health Events in the output

### ISSUE THREAD

**Issue by bhaskar39** [Azure/azure-powershell#10662]
## Steps to reproduce

Connect-AzAccount
Get-AzLog -ResourceId "<>" -StartTime ($(Get-Date).AddHours(-26)) -EndTime (Get-Date)
Get-AzLog -CorrelationId c76d608d-e8de-4d0e-b496-53fa36a3a589 -StartTime ($(Get-Date).AddHours(-26)) -EndTime (Get-Date)

## Environment data

PS C:\windows\system32> $PSVersionTable

Name                           Value                                                                                                                                
----                           -----                                                                                                                                
PSVersion                      5.1.18362.145                                                                                                                        
PSEdition                      Desktop                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                              
BuildVersion                   10.0.18362.145                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                      
WSManStackVersion              3.0                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                  
SerializationVersion           1.1.0.1

## Module versions

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands                                                                                          
---------- -------    ----                                ----------------                                                                                          
Binary     3.3.563.1  AWSPowerShell                       {Clear-AWSHistory, Set-AWSHistoryConfiguration, Initialize-AWSDefaultConfiguration, Clear-AWSDefaultCon...
Script     1.6.2      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...
Script     1.0.1      Az.Advisor                          {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Disable-AzAdvisorRecommendation, Get-AzAd...
Script     1.0.2      Az.Aks                              {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential...}                                           
Script     1.1.1      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remov...
Script     1.3.0      Az.ApiManagement                    {Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagementRegion, Add-AzA...
Script     1.0.2      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Set-AzApplicationI...
Script     1.3.2      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputReco...
Script     1.1.1      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, New-AzBatchAccount...}                 
Script     1.0.1      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget...}          
Script     1.3.1      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile...}                      
Script     1.2.1      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSku, ...
Script     2.5.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}     
Script     1.0.1      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}         
Script     1.1.0      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegist...
Script     1.2.0      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2...}             
Script     1.0.1      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalytic...
Script     1.2.2      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreF...
Script     1.0.1      Az.DeploymentManager                {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifactSource, Set-AzDeploymentManagerA...
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerL...
Script     1.1.1      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet...}                 
Script     1.2.2      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey...}            
Script     1.4.0      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace...}
Script     1.1.1      Az.FrontDoor                        {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoor...}                                
Script     2.0.1      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMa...
Script     1.2.1      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob...}    
Script     1.3.1      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKe...
Script     1.3.1      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConf...
Script     1.1.1      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Rem...
Script     1.0.1      Az.ManagedServices                  {Get-AzManagedServicesAssignment, New-AzManagedServicesAssignment, Remove-AzManagedServicesAssignment, ...
Script     1.0.1      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}                                                          
Script     1.1.0      Az.Media                            {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaServiceKey, Get-AzMediaServiceNameAva...
Script     1.2.2      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile...}                          
Script     1.13.0     Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, ...
Script     1.1.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-AzNotificationHubListKey, Get-AzNot...
Script     1.3.3      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Dis...
Script     1.1.3      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation...}              
Script     1.1.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectio...
Script     1.4.4      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettings...
Script     1.1.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-Az...
Script     1.0.2      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace...}            
Script     1.6.2      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}         
Script     1.4.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNa...
Script     1.1.2      Az.ServiceFabric                    {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabricClientCertificate, Add-AzServiceFabricCl...
Script     1.0.3      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey...}                                     
Script     1.14.1     Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-Az...
Script     1.6.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}         
Script     1.2.0      Az.StorageSync                      {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncService, Get-AzStorageSyncService, Remove-AzS...
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFu...
Script     1.0.2      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTra...
Script     1.4.1      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}            
Script     5.1.2      Azure                               {Get-AzureAutomationCertificate, Get-AzureAutomationConnection, New-AzureAutomationConnection, Remove-A...
Binary     2.0.2.52   AzureAD                             {Add-AzureADApplicationOwner, Get-AzureADApplication, Get-AzureADApplicationExtensionProperty, Get-Azur...
Script     4.1.2      AzureRM.RecoveryServices            {Get-AzureRmRecoveryServicesBackupProperty, Get-AzureRmRecoveryServicesVault, Get-AzureRmRecoveryServic...
Script     4.1.2      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRecoveryServicesBackupItem, Get-AzureRmRecoveryServicesBackupManagementServer, Get-Azure...
Script     0.2.4      AzureRM.RecoveryServices.SiteRec... {Edit-AzureRmRecoveryServicesAsrRecoveryPlan, Get-AzureRmRecoveryServicesAsrAlertSetting, Get-AzureRmRe...
Script     4.1.2      AzureRM.RedisCache                  {Remove-AzureRmRedisCachePatchSchedule, New-AzureRmRedisCacheScheduleEntry, Get-AzureRmRedisCachePatchS...
Script     0.3.3      AzureRM.Relay                       {New-AzureRmRelayNamespace, Get-AzureRmRelayNamespace, Set-AzureRmRelayNamespace, Remove-AzureRmRelayNa...
Script     5.5.2      AzureRM.Resources                   {Get-AzureRmProviderOperation, Remove-AzureRmRoleAssignment, Get-AzureRmRoleAssignment, New-AzureRmRole...
Script     0.16.3     AzureRM.Scheduler                   {Disable-AzureRmSchedulerJobCollection, Enable-AzureRmSchedulerJobCollection, Get-AzureRmSchedulerJobCo...
Script     4.1.2      AzureRM.ServerManagement            {Invoke-AzureRmServerManagementPowerShellCommand, Get-AzureRmServerManagementSession, New-AzureRmServer...
Script     0.6.4      AzureRM.ServiceBus                  {New-AzureRmServiceBusNamespace, Get-AzureRmServiceBusNamespace, Set-AzureRmServiceBusNamespace, Remove...
Script     0.3.4      AzureRM.ServiceFabric               {Add-AzureRmServiceFabricApplicationCertificate, Add-AzureRmServiceFabricClientCertificate, Add-AzureRm...
Script     5.0.6      AzureRM.SiteRecovery                {Get-AzureRmSiteRecoveryFabric, New-AzureRmSiteRecoveryFabric, Remove-AzureRmSiteRecoveryFabric, Stop-A...
Script     4.4.0      AzureRM.Sql                         {Get-AzureRmSqlDatabaseTransparentDataEncryption, Get-AzureRmSqlDatabaseTransparentDataEncryptionActivi...
Script     4.2.3      AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, New-AzureRmStorageAccount, New-AzureRmStorage...
Script     4.0.4      AzureRM.StreamAnalytics             {Get-AzureRmStreamAnalyticsFunction, Get-AzureRmStreamAnalyticsDefaultFunctionDefinition, New-AzureRmSt...
Script     4.0.1      AzureRM.Tags                        {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag}                                                       
Script     4.0.3      AzureRM.TrafficManager              {Disable-AzureRmTrafficManagerEndpoint, Enable-AzureRmTrafficManagerEndpoint, Set-AzureRmTrafficManager...
Script     4.0.2      AzureRM.UsageAggregates             Get-UsageAggregates                                                                                       
Script     4.2.2      AzureRM.Websites                    {Get-AzureRmAppServicePlan, Set-AzureRmAppServicePlan, New-AzureRmAppServicePlan, Remove-AzureRmAppServ...
Script     1.0.1      Microsoft.PowerShell.Operation.V... {Get-OperationValidation, Invoke-OperationValidation}                                                     
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}                                    
Script     3.4.0      Pester                              {Describe, Context, It, Should...}                                                                        
Manifest   2.2        Posh-SSH                            {Get-SCPFile, Get-SCPFolder, Get-SCPItem, Get-SFTPFile...}                                                
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}                                              
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineKeyHandler, Get-PSReadLineOption...}
Binary     0.8.1      SHiPS                                                                                                                                         
Script     0.0.2      Trackyon.Utils                      {Backup-Location, Get-OperatingSystem, New-Directory, Set-As...}                                          
Script     6.3.5      VSTeam                              {Add-VSTeam, Add-VSTeamAccessControlEntry, Add-VSTeamAzureRMServiceEndpoint, Add-VSTeamBuild...}  

## Debug output

PS C:\windows\system32> Get-AzLog -CorrelationId c76d608d-e8de-4d0e-b496-53fa36a3a589 -StartTime ($(Get-Date).AddHours(-26)) -EndTime (Get-Date) -DetailedOutput -Debug
DEBUG: 23:30:46 - GetAzureRmLogCommand begin processing with ParameterSet 'GetByCorrelationId'.
DEBUG: 23:30:48 - using account id '<>'...
WARNING: 23:30:48 - *** The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.M
onitor.Models in future releases.
WARNING: 23:30:50 - *** The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model clas
ses.
WARNING: [Get-AzLog] Parameter deprecation: The DetailedOutput parameter will be deprecated in a future breaking change release.
DEBUG: Processing parameters
DEBUG: First call
DEBUG: [Common.Authentication]: Authenticating using Account: '<>', environment: 'AzureCloud', tenant: '" "'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '', Endpoint: 'https://login.microsoftonline.c
om/', ClientId: '" "', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', Valid
ateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/""/', CorrelationId
: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '', AdEndpoint: 'https://login.microsoftonli
ne.com/', ClientId: '" "', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 2019-12-05T18:00:50.4438699Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005',
 file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1e3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2019-12-05T18:00:50.4438699Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005',
 file version '3.19.50302.0130' and informational version '2a8bec6c4b55bdc3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2019-12-05T18:00:50.4438699Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: login.microsoftonline.com

DEBUG: [ADAL]: Information: 2019-12-05T18:00:50.4438699Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/<>/
	Resource: https://management.core.windows.net/
	ClientId: " "
	CacheType: null
	Authentication Target: User
	

DEBUG: [ADAL]: Verbose: 2019-12-05T18:00:50.4438699Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Verbose: 2019-12-05T18:00:50.4438699Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Information: 2019-12-05T18:00:50.4468630Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 28 items to token cache.

DEBUG: [ADAL]: Verbose: 2019-12-05T18:00:50.4468630Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Verbose: 2019-12-05T18:00:50.4468630Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Information: 2019-12-05T18:00:50.4468630Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: An item matching the requested resource was found in 
the cache

DEBUG: [ADAL]: Information: 2019-12-05T18:00:50.4468630Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: An item matching the requested resource was found in 
the cache

DEBUG: [ADAL]: Information: 2019-12-05T18:00:50.4468630Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: An expired or near expiry token was found in the cach
e

DEBUG: [ADAL]: Information: 2019-12-05T18:00:50.4468630Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: An expired or near expiry token was found in the cach
e

DEBUG: [ADAL]: Information: 2019-12-05T18:00:50.4468630Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: A matching item (access token or refresh token or bot
h) was found in the cache

DEBUG: [ADAL]: Information: 2019-12-05T18:00:50.4468630Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: A matching item (access token or refresh token or bot
h) was found in the cache

DEBUG: [ADAL]: Verbose: 2019-12-05T18:00:50.4468630Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: Refreshing access token...

DEBUG: [ADAL]: Verbose: 2019-12-05T18:00:50.4468630Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: Refreshing access token...

DEBUG: [ADAL]: Verbose: 2019-12-05T18:00:51.3522074Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: Storing token in the cache...

DEBUG: [ADAL]: Verbose: 2019-12-05T18:00:51.3522074Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: Storing token in the cache...

DEBUG: [ADAL]: Verbose: 2019-12-05T18:00:51.3522074Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: An item was stored in the cache

DEBUG: [ADAL]: Verbose: 2019-12-05T18:00:51.3522074Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: An item was stored in the cache

DEBUG: [ADAL]: Information: 2019-12-05T18:00:51.3532054Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: === Token Acquisition finished successfully. An acces
s token was returned: Expiration Time: 12/5/2019 19:00:51 +00:00

DEBUG: [ADAL]: Information: 2019-12-05T18:00:51.3532054Z: 63daf445-1349-428d-987c-3720475c91bc - LoggerBase.cs: === Token Acquisition finished successfully. An acces
s token was returned: Expiration Time: 12/5/2019 19:00:51 +00:00Access Token Hash: JCju/yGH7+jovTwA1zD/Nh8r60ZsQnHbWF8dxleNYgo=
	 User id: 80be268a-9e2c-4249-b9f4-c1201552c5b7

DEBUG: [ADAL]: Information: 2019-12-05T18:00:51.3532054Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Serializing token cache with 28 items.

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '12/05/2019 19:00:51 +00:00', MultipleResource? 'True', Tenant: '9900f69b-cfa2-43a7-953c-
7c6076a6b856', UserId: '<>'
DEBUG: [Common.Authentication]: User info for token DisplayId: '<>', Name: Bhaskar, IdProvider: 'https://sts.windows.net/<>/', Uid: '80be268a-9e2c-4249-b9f4-c1201552c5b7'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '12/05/2019 19:00:51 +00:00' Comparing to '12/05/2019 18:00:51 +00:00' With threshold '00:05
:00', calculated time until token expiry: '00:59:59.9582268'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<>/providers/microsoft.insights/eventtypes/management/values?$filter=eventTimestamp ge '
2019-12-04T16:00:46.2896042Z' and eventTimestamp le '2019-12-05T18:00:46.2896042Z' and correlationId eq 'c76d608a3a589'&api-version=2015-04-01

Headers:
x-ms-client-request-id        : ee8d2ee9-e202-46c7-8
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : SouthEastAsia_64cd31af1ecd4c39bf6e8dbeb5466562_637111656520088847
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : 18628b39-baef-4324-ae4c-4685acde0607
x-ms-routing-request-id       : SOUTHINDIA:20191205T180052Z:18628b39-baef-4324-ae4c-4685acde0607
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 05 Dec 2019 18:00:51 GMT
Server                        : Microsoft-IIS/10.0

Body:
{
  "value": []
}

DEBUG: Done following continuation token
DEBUG: AzureQoSEvent: CommandName - Get-AzLog; IsSuccess - True; Duration - 00:00:06.1790419; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 23:30:53 - GetAzureRmLogCommand end processing.
DEBUG: 23:30:53 - GetAzureRmLogCommand end processing.## Error output

DEBUG: 23:36:06 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 23:36:06 - using account id 'bhaskar.desharaju@netenrich.com'...

   HistoryId: 51

Message        : Invalid JSON primitive: Microsoft.Azure.Commands.Insights.OutputClasses.PSEventData.
StackTrace     :    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
                    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
                    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer 
                 serializer)
                    at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
                    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
                    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
                    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.ArgumentException
InvocationInfo : {ConvertFrom-Json}
Line           : $data | ConvertFrom-Json
Position       : At line:1 char:9
                 + $data | ConvertFrom-Json
                 +         ~~~~~~~~~~~~~~~~
HistoryId      : 51

   HistoryId: 50

Message        : An item with the same key has already been added.
StackTrace     :    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
                    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
                    at Microsoft.PowerShell.Commands.ConvertToJsonCommand.ProcessCustomObject[T](Object o, Int32 depth)
                    at Microsoft.PowerShell.Commands.ConvertToJsonCommand.ProcessValue(Object obj, Int32 depth)
                    at Microsoft.PowerShell.Commands.ConvertToJsonCommand.ProcessEnumerable(IEnumerable enumerable, Int32 depth)
                    at Microsoft.PowerShell.Commands.ConvertToJsonCommand.ProcessValue(Object obj, Int32 depth)
                    at Microsoft.PowerShell.Commands.ConvertToJsonCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.ArgumentException
InvocationInfo : {ConvertTo-Json}
Line           : $data | ConvertTo-Json
Position       : At line:1 char:9
                 + $data | ConvertTo-Json
                 +         ~~~~~~~~~~~~~~
HistoryId      : 50

   HistoryId: 25

Message        : The term 'Login-AzureRmAccount' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
                 name, or if a path was included, verify that the path is correct and try again.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           :     $account = Login-AzureRmAccount -Credential $Creds -Tenant $TenantId
                 
Position       : At D:\OneDrive\OneDrive - NetEnrichProd\Data Drive\Data-NE\NetEnrich\Projects\Tejaswi\Activitylogs.ps1:17 char:16
                 +     $account = Login-AzureRmAccount -Credential $Creds -Tenant $Tenan ...
                 +                ~~~~~~~~~~~~~~~~~~~~
HistoryId      : 25

DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.1896517; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 23:36:07 - ResolveError end processing.
DEBUG: 23:36:07 - ResolveError end processing.

**Comment by VeryEarly** [comment]
Thanks for you feedback, forwarded to monitor team

**Comment by nkiest** [comment]
Service Health events are not currently surfaced through the current API. We are working on a convergence story to fix this, and it is on our backlog, but I do not have a ETA. However, you can access this data by exporting using subscription diagnostic settings, https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-settings-subscription.
