### ISSUE TITLE
webapp:Add support for Slot Traffic Routing to AzWebApp 

### ISSUE THREAD

**Issue by PlagueHO** [Azure/azure-powershell#10664]
## Description of the new feature

Add support for configuring traffic routing percentages to AzWebApp cmdlets.

This functionality is supported in Az CLI with https://docs.microsoft.com/en-us/cli/azure/webapp/traffic-routing?view=azure-cli-latest

## Proposed implementation details (optional)

Possibly implement:
```powershell
Get-AzWebAppTrafficRouting -ResourceGroupName 'rgname' -Name 'webappname' 
Set-AzWebAppTrafficRouting -ResourceGroupName 'rgname' -Name 'webappname' -TrafficRouting @{ 'Staging' = 25; 'Experimental' = 5 }
```

**Comment by ThejaChoudary** [comment]
Taking a look at this.

**Comment by panchagnula** [comment]
closing as duplicate of https://github.com/Azure/azure-powershell/issues/7682
