### ISSUE TITLE
webapp: Consider adding functionality equivalent to "az webapp vnet-integration" to dump vnet integration info

### ISSUE THREAD

**Issue by oising** [Azure/azure-powershell#10665]
## Description of the new feature

Neither `Get-AzWebApp` nor any related cmdlets seem to return any information about VNET integration. The information is available via `az webapp vnet-integration list --name $name --resource-group $rg` using the azure CLI, but it would be preferable to have a native powershell cmdlet to avoid having to parse output with `ConvertFrom-Json`. 

## Proposed implementation details (optional)

Either add the information to `Get-AzWebApp`, or create a new cmdlet:

 `Get-AzWebAppVirtualNetworkIntegrationConfig` (for example.)

**Comment by ThejaChoudary** [comment]
Taking a look at this.

**Comment by oising** [comment]
The azure-cli team also recently added support for ASE operations (az appservice ase ?) from 2.0.77 onwards at the same time as access restrictions support -- would also be desirable at some point :)

**Comment by panchagnula** [comment]
@Kotasudhakarreddy lets consider this for s167 milestone
