### ISSUE TITLE
New-AzKeyVault / Remove-AzKeyVault name attribute inconsistency

### ISSUE THREAD

**Issue by Skuldo** [Azure/azure-powershell#10673]
The primary name attribute is inconsistent between these 2 modules, on the former it is "Name", on the latter it is "VaultName".

**Comment by dingmeng-xue** [comment]
"Name" has alias "VaultName" on New-AzKeyVault. But no alias for "VaultName" on Remove-AzKeyVault.

**Comment by dcaro** [comment]
@Skuldo thanks for submitting the PR, we are considering this change for this sprint.

**Comment by dingmeng-xue** [comment]
Another concern is Name is specific to name of key in KeyVault domain such as Name and VaultName used by KeyGet-AzKeyVaultSecret. New-AzKeyVault using Name as default one may be historic reason.

**Comment by msJinLei** [comment]
Fixed by https://github.com/Azure/azure-powershell/pull/10676
