### ISSUE TITLE
Unable to specify the workpsace as a scope for the Action Rule Set-AzActionRule

### ISSUE THREAD

**Issue by GitMaggie** [Azure/azure-powershell#10703]
## Description
Set-AzActionRule -ResourceGroupName 'xxx' -Name 'xxx' -Scope '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.OperationalInsights/workspaces/xxx' -Description 'xxx' -Status 'Enabled' -ActionRuleType 'Suppression' -ReccurenceType 'Weekly' -SuppressionStartTime '01/01/2020 06:00:00' -SuppressionEndTime '12/07/2020 06:00:00' -ReccurentValue 1,4,6  -DEBUG -VERBOSE

The default scopetype is always "resourcegroup" and it cannot detect the correct scope type by format of resource id . 
"message": "Invalid input parameters: Scope value /subscriptions/xxx-8ba50e7d1735/resourceGroups/xxx/providers/Microsoft.OperationalInsights/workspaces/AAws1 is not in the expected format of scope type ResourceGroup."
## Module versions

Az 3.1.0 
Az.AlertsManagement  0.1.0

## Debug output Request: 
Body:

    "scope": {
      "scopeType": "ResourceGroup",
      "values": [
        "/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.OperationalInsights/workspaces/XXX"
      ]
    },
  
## Debug output Response:
Body:
{
  "error": {
    "code": "BadRequest",
    "message": "Invalid input parameters: Scope value /subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.OperationalInsights/workspaces/XXX is not in the expected format of scope type ResourceGroup."
  }
}

**Comment by dingmeng-xue** [comment]
@GitMaggie Could you share scripts in PowerShell you are executing? Error comes from server. It seems target object is no resource group but parameter of cmdlet claims it is a resource group.

**Comment by GitMaggie** [comment]
> @GitMaggie Could you share scripts in PowerShell you are executing? Error comes from server. It seems target object is not resource group but parameter of cmdlet claims it is a resource group.

Set-AzActionRule -ResourceGroupName 'rg-mel-npi-austin-1' -Name 'Test-AR' -Scope '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.OperationalInsights/workspaces/xxx' -Description 'Test description' -Status 'Enabled' -ActionRuleType 'Suppression' -ReccurenceType 'Weekly' -SuppressionStartTime '01/01/2020 06:00:00' -SuppressionEndTime '12/07/2020 06:00:00' -ReccurentValue 1,4,6

**Comment by dingmeng-xue** [comment]
To service team, all examples around Set-AzActionRule are using resource group as scope. No further explanation about scope. If scope can support resource, [this check](https://github.com/Azure/azure-powershell/blob/ea903d3e9dea32bd1ff8ad6dbfec22420cc9c6c2/src/AlertsManagement/AlertsManagement/ActionRuleCommands/SetAzureActionRule.cs#L562) may have problem.

**Comment by ofirmanor** [comment]
Hey, I acknowledge, thanks for raising this.
This is a known bug, where scope is currently only resource group - internal work item is 6012387.
