### ISSUE TITLE
No Powershell Command-let for AzureBatch to sync Keys for the Attached Storage Account 

### ISSUE THREAD

**Issue by dhruvmodi13** [Azure/azure-powershell#10704]
Could not find any PowerShell commandlet for the SyncKeys option which syncs the Azure storage accounts keys in Batch.

https://docs.microsoft.com/en-us/rest/api/batchmanagement/batchaccount/synchronizeautostoragekeys#code-try-0

https://docs.microsoft.com/en-us/cli/azure/batch/account/autostorage-keys?view=azure-cli-latest

Rest API call and CLI commands are present.
Was wondering why PS commands are not added in the AzureRm.Batch module.

Need this for Auto Secret Rotation for storage account.

**Comment by msJinLei** [comment]
@dhruvmodi13 Thank you for proposal. We will make a plan on it and let you know if any progress.

**Comment by bgklein** [comment]
@matthchr Is there a reason for this?  Is SetBatchAccountCommand meant to fill this role (set  account with same storage account)?

**Comment by bgklein** [comment]
Sorry about the assignment spam. It looks like this API was missed when writing the Powershell commands.We will look to add it when we start our next release cycle.

**Comment by bgklein** [comment]
This is planned for addition, when Batch releases it next REST API version

**Comment by bgklein** [comment]
Batch recently released its 09-01 REST API. When we get to the PowerShell work for supporting this API this will be included

**Comment by navba-MSFT** [comment]
@dhruvmodi13 Apologies for the delayed response. I will do some research on this and then get back to you once I have an update.

@bgklein Could you please let us know if this issue has been fixed ? Awaiting your reply.

**Comment by bgklein** [comment]
https://docs.microsoft.com/en-us/powershell/module/az.batch/new-azbatchaccountkey?view=azps-7.1.0
