### ISSUE TITLE
Cannot unregister backup vault container : type "AzureVM"

### ISSUE THREAD

**Issue by bufferwolfa** [Azure/azure-powershell#10719]
# Steps to reproduce
![prob3](https://user-images.githubusercontent.com/13571179/70859979-35dff000-1f4e-11ea-808c-d26c331c88b3.PNG)
![prob2](https://user-images.githubusercontent.com/13571179/70859920-42177d80-1f4d-11ea-86fa-080c6fd3b3a6.PNG)
![prob1](https://user-images.githubusercontent.com/13571179/70859921-480d5e80-1f4d-11ea-8001-126bb5df50af.PNG)

# Expected behavior
No Error and show success report.

# Environment data
Run these commands in Azure Cloud Shell at  2019-12-15 3:10 pm +07:00 timezone

**Comment by msJinLei** [comment]
@bufferwolfa  Could you provide the following information?

## Debug output
Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block 

```

```

## Error output
Please run Resolve-AzError and paste the output in the below code block

```

```

**Comment by irj-sk** [comment]
Same here using Powershell Core v6:

```
PS C:\Program Files\PowerShell\6> Get-AzRecoveryServicesBackupContainer -ContainerType "AzureVM"                                                
FriendlyName                             ResourceGroupName                        Status               ContainerType
------------                             -----------------                        ------               -------------
TESTVM                                     TEST-RG                            Registered           AzureVM


PS C:\Program Files\PowerShell\6> $cont = Get-AzRecoveryServicesBackupContainer -ContainerType "AzureVM"
PS C:\Program Files\PowerShell\6> Unregister-AzRecoveryServicesBackupContainer -Container $Cont
Unregister-AzRecoveryServicesBackupContainer : Please provide Container of containerType as Windows and backupManagementType as MARS or Container of containerType as AzureSQL and backupManagementType as AzureSQL or Container of containerType as AzureStorage and backupManagementType as AzureStorage. Provided Container has containerType AzureVM and backupManagementType AzureVM which is invalid.
At line:1 char:1
+ Unregister-AzRecoveryServicesBackupContainer -Container $Cont
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Unregister-AzRe...BackupContainer], ArgumentException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.UnregisterAzureRmRecoveryServicesBackupContainer

PS C:\Program Files\PowerShell\6> Resolve-AzError
WARNING: Breaking changes in the cmdlet 'Resolve-AzError' :
WARNING:  - The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.


WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.


   HistoryId: 25


Message        : Please provide Container of containerType as Windows and backupManagementType as MARS or Container of containerType as
                 AzureSQL and backupManagementType as AzureSQL or Container of containerType as AzureStorage and backupManagementType as
                 AzureStorage. Provided Container has containerType AzureVM and backupManagementType AzureVM which is invalid.
StackTrace     :    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.UnregisterAzureRmRecoveryServicesBackupContainer.<ExecuteCmdlet
                 >b__8_0()
                    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.RecoveryServicesBackupCmdletBase.ExecutionBlock(Action action,
                 Boolean shouldProcess)
Exception      : System.ArgumentException
InvocationInfo : {Unregister-AzRecoveryServicesBackupContainer}
Line           : Unregister-AzRecoveryServicesBackupContainer -Container $Cont
Position       : At line:1 char:1
                 + Unregister-AzRecoveryServicesBackupContainer -Container $Cont
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 25
```

I do need to delete this recovery services vault and cannot do so via the Azure Portal as it tells me there are still registered items!

**Comment by pvrk** [comment]
@irj-sk: Azure VMs need not be un-registered. If vault delete is failing, please refer to this article on how to proceed.

https://docs.microsoft.com/azure/backup/backup-azure-delete-vault#delete-the-recovery-services-vault-by-using-azure-resource-manager

**Comment by pvrk** [comment]
@bufferwolfa: As mentioned above, Azure VMs need not be unregister. To understand what containers need to unregistered, you need to check 'Backup Infrastructure' from Azure Portal and check Management servers and Azure Storage account section.

**Comment by pvrk** [comment]
And if you are using PS to unregister, then you need to only unregister container whose container type is "Windows" or "VMAppContainer"/"AzureWorkload" or "AzureStorage". Then also delete the BackupManagementServer using the relevant [PS command](https://docs.microsoft.com/powershell/module/az.recoveryservices/unregister-azrecoveryservicesbackupmanagementserver?view=azps-3.3.0).

**Comment by pvrk** [comment]
Closing the issue, since all explanation regarding "un-register" is given.
