### ISSUE TITLE
Cmdlets review link

### ISSUE THREAD

**Issue by kattamudi-karthik** [Azure/azure-powershell#10729]
Cmdlets review link is broken (https://github.com/Azure/azure-powershell-cmdlet-review-pr)
Can you please provide us the exact URL.

![404page](https://user-images.githubusercontent.com/6092656/70972858-6056b800-20ca-11ea-969e-54e164de37d9.PNG)

**Comment by dingmeng-xue** [comment]
@kattamudi-karthik are you from Microsoft or official partners? It's a private repo and you need to apply access permission.

**Comment by kattamudi-karthik** [comment]
Hi ,

I am internal employee and my alias is kakattam. Can you please let me know in email how to apply access permission .

**Comment by dingmeng-xue** [comment]
Resolve it by internal email.
