### ISSUE TITLE
webapp: Add health check timeout parameter to Switch-AzureRmWebAppSlot

### ISSUE THREAD

**Issue by justinjstark** [Azure/azure-powershell#10724]
## Description of the new feature
There is a default health-check timeout for Switch-AzureRmWebAppSlot (something like 90 seconds). My app takes 4-5 minutes to start so I cannot use it.

## Proposed implementation details (optional)
Add a command line parameter for the health check timeout.
OR Allow setting an app setting on the deployment slot specifying the health check timeout.

**Comment by panchagnula** [comment]
@Kotasudhakarreddy can you check if we actually have a 90sec wait here.

**Comment by Kotasudhakarreddy** [comment]
Looking in to it.

**Comment by panchagnula** [comment]
@justinjstark can you let us know what is the health check time out you are referring to here? Thanks

**Comment by panchagnula** [comment]
ping @justinjstark any updates?

**Comment by justinjstark** [comment]
I'll try to find some time to reproduce this and give you some more information. In my app, I had to start the app manually, do manual health checks until it is available, and then swap in the deployment slot. This workaround has been working.

**Comment by panchagnula** [comment]
@shubDhond does slots backend  have any time out we use in slots since with Powershell code we don't have default timeout check we add, also if API does have this sort of health check timeout is there is a way to override it?

**Comment by shubDhond** [comment]
@justinjstark I believe you are referring to the swap operations timeout where if the slot has not started up within the timeout during swap, the swap fails. This timeout is actually currently 5 mins but it will increase it to 10 mins with our current deployment. This should complete in about a month but in the meantime, I would suggest using the SwapWithPreviewAction argument to perform a swap with preview if this is not already what you are using as a workaround. This will allow you to perform the swap in phases and as you are doing currently manually verify the slot is up before swapping.

**Comment by panchagnula** [comment]
Thanks @shubDhond for the response.
