### ISSUE TITLE
Build.ps1 failure

### ISSUE THREAD

**Issue by PxlBuzzard** [Azure/azure-powershell#1072]
I am cloning the repo onto a new machine and I have the [pre-reqs](https://github.com/Azure/azure-powershell/wiki/Microsoft-Azure-PowerShell-Developer-Guide#install-prerequisites) installed. The error text is:

```
"F:\git\azure-powershell\build.proj" (Build target) (1) ->
"F:\git\azure-powershell\setup\azurepowershell.sln" (Build target) (125) ->
"F:\git\azure-powershell\setup\azurepowershell.wixproj.metaproj" (default target) (126) ->
"F:\git\azure-powershell\setup\azurepowershell.wixproj" (default target) (128) ->
(Link target) ->
  F:\git\azure-powershell\setup\azurecmdfiles.wxi(1145): error LGHT0103: The system cannot find the file 'F:\git\azure-powershell\setup\..\src\Package\Debug\ResourceManager\AzureResourceManager\AzureRM.KeyVault\System.Spatial.dll'.
[F:\git\azure-powershell\setup\azurepowershell.wixproj]
```

**Comment by markcowl** [comment]
@PxlBuzzard This looks like a dependency not copied during the build.  Was there antyhing changed (a dll version or the like)?  

Currently, the Build target builds the msi as well as the dlls, which is why you're seeing the error.

**Comment by PxlBuzzard** [comment]
I changed nothing before I ran the script. My team is seeing the same failure on 3 separate machines. @KajalPowerShell @rnikhilkumar

**Comment by PxlBuzzard** [comment]
@markcowl Any thoughts? We just onboarded another team member and ran into this again.

**Comment by markcowl** [comment]
@PxlBuzzard This is not occurring in the current dev or releas ebranches.  Please reopen if you see this again.
