### ISSUE TITLE
New-AzOperationalInsightsSavedSearch is missing -FunctionAlias parameter

### ISSUE THREAD

**Issue by darivuki** [Azure/azure-powershell#10721]
## Description of the new feature
I would like to be able to pass in the FunctionAlias to the saved search in the New-AzOperationalInsightsSavedSearch / Set-AzOperationalInsightsSavedSearch cmdlets. It is possible to POST this FunctionAlias using the Azure Monitor REST API: https://docs.microsoft.com/en-us/rest/api/loganalytics/savedsearches/createorupdate, but not with the cmdlet 

## Proposed implementation details (optional)
Add the -FunctionAlias parameter to the cmdlets to be able to insert this value for a savedSearch as well.

**Comment by yossi-y** [comment]
We have this work planned to support FunctionAlias parameter as well.
I don't have an exact ETA for this, but it should be in the first half of 2020.
