### ISSUE TITLE
New Service On boarding 

### ISSUE THREAD

**Issue by kattamudi-karthik** [Azure/azure-powershell#10720]
Hi Team,

We are new to the Azure Powershell repository. We are planning to develop new commands for a service called Region Move Service.  We have questions to set up the solution for the same. For some of the questions we have found in the documentation but some of them we have ambiguity . and for some of the questions, we don't have the answers. Can you please address these questions.

Can you please answer the below questions 

1) We are the internal team of Microsoft. Can you please let us know the dev team contact of Azure Powershell?

2)If we want to build a solution and if we want to support AZ mode of installation(latest), Can you please suggest which solution/folder to be copied?

3)For setup issues whom to contact? Is there is a detail one note for all kinds of setup issues?

4)Can you please tell the process to fork and since it is an internal team and multiple Microsoft developers will be working on it.  Do we need to set up an Org and clone the repo and sync it every time with the main repo? Can you please tell us the standard process to follow.

5)Is there is an authentication mechanism to follow and what are all the base classes and base frameworks to be used? Is there is a OneNote that can help us to leverage the base framework? What are all the non-functional requirements to be followed for a new service?

6)Can you please share the contact for reviewing the cmdlets?

7)We want to use the PowerShell cmdlets in the cloud tests((OneBranch)). Please let us know if there any issues in using PowerShell commands with the cloud tests.

8)Please let us know anything else we need to follow for setting up a new solution in AzurePowershell and publishing them to Azure Powershell Gallery?

**Comment by msJinLei** [comment]
@kattamudi-karthik Could you provide you microsoft email? We can reply you by email

**Comment by kattamudi-karthik** [comment]
my email is kakattam@microsoft.com

**Comment by dingmeng-xue** [comment]
Close this issue and further discussion via email.
