### ISSUE TITLE
Set-AzAutomationWebhook - add parameter to update Hybrid Worker Group name

### ISSUE THREAD

**Issue by anwather** [Azure/azure-powershell#10746]
## Description of the new feature
The REST api allows you to specify properties.runOn in the body of a request to update the hybrid worker group for a webhook. The cmdlet should have the same functionality.

## Proposed implementation details (optional)
Add a parameter as below which accepts a string
```
Set-AzAutomationWebhook -Name <<webhook name>> -RunOn <<hybrid worker group name>> <<all other existing parameters>> 
```

**Comment by msJinLei** [comment]
@anwather thanks for your proposal. We will evaluate it and let you know if any progress.

**Comment by andyw248** [comment]
Set-AzAutomationWebhook should accept the same parameters as New-AzAutomationWebhook and the portal do.

**Comment by vikram-m** [comment]
This is triaged and currently in the backlog, will consider it if resourcing allows.

**Comment by vikram-m** [comment]
Unfortunately because of other priorities we were not able to pick this up, please expect an update in Q4CY20.

**Comment by anwather** [comment]
#12677

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.
