### ISSUE TITLE
Get-AzAksVersion (like az aks get-versions --location wherever)

### ISSUE THREAD

**Issue by misterjoshua** [Azure/azure-powershell#10759]
## Description of the new feature
I propose a cmdlet that enables the user to get a list of Kubernetes orchestrator versions (i.e., 1.14.8). This will enable the user to:

* List orchestrator versions from the command line without needing the separate `az` command.
* Query for available Kubernetes versions to see when there are upgrades available for their cluster.
* Create PowerShell scripts that provision Kubernetes clusters based on the "default" orchestrator version.
* Create PowerShell scripts that provision Kubernetes clusters based on the latest available patch version. (e.g., I want the latest 1.14 Kubernetes cluster, so the cmdlet provides me with 1.14.8)

## Proposed implementation details (optional)
This information is available on the REST API here: `https://management.azure.com/subscriptions/$subscriptionId/providers/Microsoft.ContainerService/locations/$clusterLocation/orchestrators?api-version=2019-08-01`

The cmdlet might be used like this:

**Get all versions**
`Get-AzAksVersion -Location $location`

**Get the default version (per the management API)**
`Get-AzAksVersion -DefaultVersion -Location $location`

**Get all versions like 1.14**
`Get-AzAksVersion -VersionLike "1.14.*" -Location $location`

**Get the latest version like 1.14**
`Get-AzAksVersion -LatestVersionLike "1.14.*" -Location $location`

The structure of the data returned could mirror what the API currently returns:

```
{
  "id": "/subscriptions/.../providers/Microsoft.ContainerService/locations/.../orchestrators",
  "name": "default",
  "orchestrators": [
    {
      "default": null,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.13.11",
      "upgrades": [
        {
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.13.12"
        },
        {
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.14.7"
        },
        {
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.14.8"
        }
      ]
    },
    {
      "default": null,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.13.12",
      "upgrades": [
        {
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.14.7"
        },
        {
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.14.8"
        }
      ]
    }
  ]
}
```

**Comment by dingmeng-xue** [comment]
Thanks for your proposal. We will estimate and prioritize it.

**Comment by erich-wang** [comment]
Provided Get-AzAksVersion in az.aks 1.1.0-preview

**Comment by jwhite-ac** [comment]
Will `-DefaultVersion` be implemented? I need an easy way to lookup the default version (to compare against my currently running versions) in a powershell script for azure automation. This would have been perfect except I can't specify only the default version and instead get the list of all available versions (which I can probably chop up with unix tools, but having a flag on the cmdlet as per the original proposed implementation above would make life much easier).

**Comment by dcaro** [comment]
@jwhite-ac we may consider having a `-DefaultVersion` parameter sometime in the future. With this version you can get the default version for the specified location using the following code:
`(Get-AzAksVersion -Location Westus | Where-Object { $_.DefaultProperty -eq "True" }).OrchestratorVersion` 

To get the most recent 1.15.* version here is a command: 
`Get-AzAksVersion -Location Westus | Where-Object { $_.OrchestratorVersion -like "1.15.*" } | Sort-Object -Descending OrchestratorVersion -Top 1`

Hope this helps

**Comment by jwhite-ac** [comment]
@dcaro That's perfect, thank you.
