### ISSUE TITLE
Missing Start/Stop Cmdlets for ContainerInstances / Container Groups

### ISSUE THREAD

**Issue by erenes** [Azure/azure-powershell#10773]
## Description of the new feature
There are Start and Stop calls for container groups in the Azure Management API, but there are no Cmdlets to use them. 

I would expect there to be a Start-AzContainerGroup and Stop-AzContainerGroup Cmdlet so that I can start and stop my containergroup from a powershell script. 

https://docs.microsoft.com/en-us/rest/api/container-instances/containergroups/start
https://docs.microsoft.com/en-us/rest/api/container-instances/containergroups/stop

## Proposed implementation details (optional)
I think this probably depends on the following issue in the azure sdk for .net: 
https://github.com/Azure/azure-sdk-for-net/issues/6616

**Comment by dingmeng-xue** [comment]
We need ContainerInstances team's further support.

**Comment by erenes** [comment]
It looks like there is a new version of the azure sdk for .net released that allows to call these methods. 

If I have time I will look into it somewhere in the next couple of weeks.

**Comment by Mik4sa** [comment]
Will this get added some day? I'm still waiting for this.

**Comment by dingmeng-xue** [comment]
We are working on this service and will support those operations after we bump version to the latest stable one. You can expect feature will be available within couple months.
