### ISSUE TITLE
[Doc] Mistake in conceptual doc "Sign in with Azure PowerShell"

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#10781]
## Description
In the ["Sign in with Azure PowerShell"](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-3.2.0) doc, the "Sign in interactively" section, two scenarios (interactive, device code) are mixed up.

Expected: these two scenarios are described separately.

**Comment by dcaro** [comment]
@Minewiskan we should consider refreshing the conceptual doc page to include the behavior of Windows PowerShell and PowerShell core as well as the behavior with the next Az.Accounts.

**Comment by dcaro** [comment]
@mikefrobbins to confirm but I think this issue has been fixed.

**Comment by mikefrobbins** [comment]
This issue has been resolved in the [Sign in to Azure PowerShell interactively](https://learn.microsoft.com/powershell/azure/authenticate-interactive) conceptual article. [Device code authentication](https://learn.microsoft.com/powershell/azure/authenticate-interactive#device-code-authentication) has its own section.
