### ISSUE TITLE
PageNot Found for the link approved-verbs-for-windows-powershell-commands

### ISSUE THREAD

**Issue by arunko34** [Azure/azure-powershell#10797]
Hello,

The follwoing links point Page not found.

https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands

rgds
Arun

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will fix that link soon.

**Comment by dingmeng-xue** [comment]
Fixed.
