### ISSUE TITLE
Why are the AzDataLakeGen2 commands not included in 1.10.0?

### ISSUE THREAD

**Issue by martijnburgers** [Azure/azure-powershell#10790]
Preview 1.9.1 of Az.Storage contains commands for working with Azure Data Lake Gen 2. Why are those not included in 1.10.0?

**Comment by dingmeng-xue** [comment]
Involve Storage team to check this ask.

**Comment by blueww** [comment]
@martijnburgers 

Generally, we have 2 release channels for Storage features in Powershell:

- Preview features : in preview module Az.Storage release (e.g. 1.9.1-preview)
- GA feature: in stable release of Azure Powershell (e.g. 1.10.0)

DatalakeGen2 feature is still in preview, so we only release it in preview module Az.Storage release. 
When you install Az.Storage 1.9.1, you will see the module version is 1.9.1-preview.
1.10.0 is stable release, it's version don't contain preview tag, so it doesn't include preview features.

We will move features from preview module to stable Powershell release when it's GA.

**Comment by blueww** [comment]
@martijnburgers
Close this issue as it's expected.
Let me know if you need any further assistance.

**Comment by guntaled** [comment]
Is there an ETA when DataLakeGen2 feature will be GA?

**Comment by blueww** [comment]
It will depends on feature team release schedule, and our bandwith.
Please note, since the Datalake Gen2 in Powershell is still preview, it might will have breaking change when release in Stable Powershell release. Anyway, we will make the breaking as less as possbile.

**Comment by blueww** [comment]
The datalake gen2 cmdlets is already released in latest Az.Storage module, like Az.Storage 2.0.0
