### ISSUE TITLE
Pick up common repo PR (Azure/azure-powershell-common#155)

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#10799]
## Description
[Change has been made](https://github.com/Azure/azure-powershell-common/pull/155) to the common repo about initiazliting cloud metadata from ARM. Need to adopt it.
cc @erich-wang 
cc @mdewan 

## Cost
1

**Comment by isra-fel** [comment]
In S164, @Dingmeng-xue will update common library due to telemetry update. This feature will also be included.

**Comment by dingmeng-xue** [comment]
Common lab was updated in S164.
