### ISSUE TITLE
Az.DataBoxEdge depends on an old Az.Accounts version

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#10831]
## Description

See: https://github.com/Azure/azure-powershell/blob/0a6cc7771392c3d8c7bcc437bcf8c16dbf47ace9/src/DataBoxEdge/DataBoxEdge/Az.DataBoxEdge.psd1
Need to update to date

**Comment by dingmeng-xue** [comment]
https://github.com/Azure/azure-powershell/blob/0a6cc7771392c3d8c7bcc437bcf8c16dbf47ace9/src/DataBoxEdge/DataBoxEdge/Az.DataBoxEdge.psd1#L56

**Comment by dingmeng-xue** [comment]
It is resolved in
