### ISSUE TITLE
Allow updating UserAgent settings with environment information

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#10833]
## Description

We need a way to identify the environment in which a cmdlet is executed. An environment variable (name TBD) could provide the information and contents would be added to the outgoing user agent for management calls in Azure PowerShell.

Tests to verify the new functionality (no setting, empty/whitespace setting, valid single setting, valid multiple settings) will need to be added.

**Comment by dingmeng-xue** [comment]
https://github.com/Azure/azure-powershell-common/pull/168
