### ISSUE TITLE
[IMPROVEMENT] Azure policy state document

### ISSUE THREAD

**Issue by KrishnaG-MSFT** [Azure/azure-powershell#10835]
## Description of the new feature or improvement

Link to document : https://docs.microsoft.com/en-us/powershell/module/az.policyinsights/get-azpolicystate?view=azps-3.2.0

Based on above mentioned Azure PowerShell document about Get-AzPolicyState cmdlet, customer suggests to put more detail on return value. Because customer found a problem of return value "ComplianceState" - the possible value of this return value are "compliant" , "NonCompliant" and "NotApplicable". But have no idea what is "NotApplicable" mean for this case. Could you add more detail in the referred document.

Reference: MicrosoftDocs/azure-docs#45644

## Proposed implementation details (optional)
Could you add more detail in the referred document.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. It requires more information from Policy Insights team.

**Comment by kenieva** [comment]
The state of Not Applicable means that that definition is not applicable to that resource. I see that this information is not stated in the documentation so we will assess to see where it is most appropriate to put. Thanks.
