### ISSUE TITLE
Select-AzSubscription is alias of Set-AzContext cmdlet

### ISSUE THREAD

**Issue by ram-msft** [Azure/azure-powershell#10848]
Set-AzContext cmdlet documnet to update about the Select-AzSubscription.
https://docs.microsoft.com/en-us/powershell/module/az.accounts/set-azcontext?view=azps-3.2.0

 Obsolete the following Select-AzureSubscription document.
https://docs.microsoft.com/en-us/powershell/module/servicemanagement/azure/select-azuresubscription?view=azuresmps-4.0.0

**Comment by dcaro** [comment]
@ram-msft thanks for opening the issue, the `Select-AzureSubscription` is a cmdlet of the old Azure service management model.
The notion of context is richer than simply the subscription, the following article has more details about context: https://docs.microsoft.com/en-us/powershell/azure/context-persistence

Let me know if this helps.

**Comment by ram-msft** [comment]
@dcaro Thanks for your information. Can you please share if any road map to obsolete the Select-AzureSubscription of the old Azure service management model.

**Comment by dcaro** [comment]
@ram-msft you can have as many contexts as you like against the same subscription. 

For example you can have a context for your user account connected to subscription A and another context for a service principal connected to subscription A and a context for your user account connected to subscription B. The context also has a reference to the token cache used to access the corresponding cloud making the context very useful when you need to use multiple environments, not just subscriptions.

`Select-AzContext` will make the selected context the default locally and the documentation on context provides more details on this (https://docs.microsoft.com/en-us/powershell/azure/context-persistence).

**Comment by ohadschn** [comment]
@dcaro Ideally the docs would mention the fact that `Select-AzSubscription` is an alias in the `Set-AzContext` docs: https://docs.microsoft.com/en-us/powershell/module/az.accounts/set-azcontext?view=azps-6.1.0&viewFallbackFrom=azps-3.2.0

**Comment by dcaro** [comment]
We have a feature request open to the docs team to expose the aliases in our reference documentation.
