### ISSUE TITLE
Azure Powershell cmndlets to Enable/Disable Application Insights Web tests

### ISSUE THREAD

**Issue by MissaouiChedy** [Azure/azure-powershell#10847]
## Description of the new feature
There are currently no way to enable or disable Application insights webtests from Azure Powershell.

I would like to suggest and discuss the relevance of creating two cmndlets:

- `Start-AzApplicationInsightsWebTest` to enable a webtest
- `Stop-AzApplicationInsightsWebTest` to disable a webtest

### Use case
In our current project, we have a deployment pipeline that creates multiple Azure resources via ARM templates.

Among these resources, we create an [Application Insights component](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2015-05-01/components) and a [WebTest.](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2015-05-01/webtests)

We would like to create the webtest disabled initially then enable it after the application's deployment with powershell commandlets.

We currently do so by directly using [Application Insights's REST API](https://docs.microsoft.com/en-us/rest/api/application-insights/webtests/createorupdate) in a Powershell Script that includes some authorization token fetching logic.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. This feature request needs ApplicationInsights team to check.

**Comment by MissaouiChedy** [comment]
@dingmeng-xue how can we get in touch with the App Insights team?

**Comment by navba-MSFT** [comment]
@MissaouiChedy Apologies for the delayed response. We are looking in this github issue. We will update this thread once we have more details on this.

@zakimaksyutov @pdrayton Could you please provide an update on this feature-request ask once you get a chance ? Awaiting your reply.
