### ISSUE TITLE
Unable since this week to use ARM Template to deploy my runbooks on Automation

### ISSUE THREAD

**Issue by FranckSix** [Azure/azure-powershell#10871]
This feature worked nice since this week

`    {
      "name": "[concat(variables('automationAccountName'), '/', parameters('automationParameters').runbooks[copyIndex()].Name)]",
      "type": "Microsoft.Automation/automationAccounts/runbooks",
      "apiVersion": "2018-06-30",
      "dependsOn": [
        "[resourceId('Microsoft.Automation/automationAccounts', variables('automationAccountName'))]"
      ],
      "copy": {
        "count": "[length(parameters('automationParameters').runbooks)]",
        "mode": "Parallel",
        "name": "runbooksCopy"
      },
      "location": "[parameters('automationParameters').AutomationLocation]",
      "properties": {
        "runbookType": "[parameters('automationParameters').runbooks[copyIndex()].type]",
        "logVerbose": false,
        "logProgress": false,
        "publishContentLink": {
          "uri": "[concat(parameters('_artifactsLocation'), '/Automation/runbooks/', parameters('automationParameters').runbooks[copyIndex()].FileName, parameters('_artifactsLocationSasToken'))]",
          "version": "[parameters('automationParameters').runbooks[copyIndex()].version]"
        }
      },
      "tags": {
        "displayName": "Runbooks"
      }
    }`

This week whe I trying to deploy my resource I get this error
```
New-AzResourceGroupDeployment : 16:04:20 - Resource Microsoft.Automation/automationAccounts/runbooks 'MyApp-environnement-automation/MyRunbook' failed with message '{
  "code": "BadRequest",
  "message": "{\"Message\":\"Invalid argument specified. Argument content cannot be null.\"}"
}'
At D:\projets\MyApp\Dev\Src\Configurations\AzureResourceGroup\Automation\Deploy-AzTemplate.ps1:203 char:9
+         New-AzResourceGroupDeployment -Name $DeploymentName `
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

New-AzResourceGroupDeployment : 16:04:20 - Resource Microsoft.Automation/automationAccounts/runbooks 'MyApp-environnement-automation/StopStartAllWebApps' failed with message '{
  "code": "BadRequest",
  "message": "{\"Message\":\"Invalid argument specified. Argument content cannot be null.\"}"
}
```

**Comment by dingmeng-xue** [comment]
@FranckSix , I didn't get the what argument was missed. Could you share us the whole input parameters?

**Comment by dedbit** [comment]
I have been struggling with the same error, testing all parameters of the ARM template. It turned out for me that the publishContentLink uri were pointing to a url that aren't valid anymore. The error message "Invalid argument specified. Argument content cannot be null." is very ambiguous. It would be great to have a more specific error message.

**Comment by dingmeng-xue** [comment]
@dedbit , could you provide your script and sample input? We need more details for triage.

**Comment by dingmeng-xue** [comment]
The similar issue normally is due to Service side's change. It is out of Azure PowerShell's scope. If you still have problem, please share parameter you are using. We will investigate further.

**Comment by snaheth** [comment]
@dedbit and @FranckSix - are you still running into this?

**Comment by KranthiPakala-MSFT** [comment]
@FranckSix We still have not heard back from you. Are you still experiencing the issue or please confirm if this issue can be closed? - Thank you

**Comment by dedbit** [comment]
For my part i found a solution, ensuring that the publishContentLink points to a valid valid file. So i don't have this problem anymore.

**Comment by justinokay** [comment]
> For my part i found a solution, ensuring that the publishContentLink points to a valid valid file. So i don't have this problem anymore.

@dedbit 
I'm having the exact same issue. Can you please share your input uri reference with the script path? It should look something like this.

`"url": "[uri(parameters('_artifactsLocation'), concat('../path/to/some/script.ps1', parameters('_artifactsLocationSasToken')))]",`

**Comment by dedbit** [comment]
@justinokay : It might not be too easy to read, but I created an array named "runbookScripts" in the variables section for defining my script files. Under resources I added a runbooks resource that loops over the "runbookScripts" and creates the runbooks one by one. My problem weren't the syntax of the ARM code, but rather that one of the files in the array didn't exist and that the error message didn't help me much in locating the problem. If you are getting this error message, I recommend that you check the path of the publishContentLink url. 

Here is the code i used:
The input parameters storageaccountPath were set in Powershell with a format like this:
$storageAccountPath= "https://$storageAccountName.blob.core.windows.net"

The key components of the ARM template are these:
```json
"variables": {
	"runbookScripts": {
		"runbooks": [
			{
				"name": "queueCopyFiles",
				"scriptFile": "queueCopyFiles.ps1",
				"version": "[parameters('runbookversion')]",
				"type": "PowerShell",
				"description": "Copy files"
			}
		]
	}
}

"resources": [
	{
		"apiVersion": "2015-10-31",
		"type": "Microsoft.Automation/automationAccounts/runbooks",
		"name": "[concat(parameters('automationAccountName'), '/', variables('runbookScripts').runbooks[copyIndex()].Name)]",
		"location": "[resourceGroup().location]",
		"dependsOn": [
			"[resourceId('Microsoft.Automation/automationAccounts/', parameters('automationAccountName'))]"
		],
		"copy": {
			"name": "runbooksLoop",
			"count": "[length(variables('runbookScripts').runbooks)]"
		},
		"properties": {
			"description": "[variables('runbookScripts').runbooks[copyIndex()].description]",
			"runbookType": "[variables('runbookScripts').runbooks[copyIndex()].type]",
			"logProgress": true,
			"logVerbose": false,
			"publishContentLink": {
				"uri": "[concat(parameters('storageaccountPath'), '/runbookscripts/', variables('runbookScripts').runbooks[copyIndex()].scriptFile)]",
				"version": "[variables('runbookScripts').runbooks[copyIndex()].version]"
			}
		}
	}
]
```

**Comment by justinokay** [comment]
@dedbit 

Thank you very much for the explanation. I'm following the same pattern for looping over an array of runbook scripts. For some reason this is still not working for me. I even copied the full url from blob storage script file and hard coded it as the uri value and still got the sam error. Any pointer? Appreciate the help.

example script uri: https://storageaccount.blob.core.windows.net/folder/script.ps1

```JSON
{
      "type": "Microsoft.Automation/automationAccounts/runbooks",
      "apiVersion": "[variables('runbooksApiVersion')]",
      "name": "[concat(parameters('automationAccountname'), '/', variables('runbooks').scripts[copyIndex()].Name)]",
      "copy": {
        "name":"RunbookLoop",
        "count": "[length(variables('runbooks').scripts)]"
      },
      "location": "[resourceGroup().location]",
      "dependsOn": [
          "[resourceId('Microsoft.Automation/automationAccounts', parameters('automationAccountname'))]"
      ],
      "properties": {
        "description": "[variables('runbooks').scripts[copyIndex()].description]",
        "runbookType": "[variables('runbooks').scripts[copyIndex()].type]",
        "logVerbose": true,
        "logProgress": true,
        "logActivityTrace": 0,
        "publishContentLink": {
            "uri": "https://storageaccount.blob.core.windows.net/folder/script.ps1",
            "version": "[parameters('version')]"
        }
      }
    }
```
error: Invalid argument specified. Argument content cannot be null.

**Comment by mykube-in** [comment]
@justinokay - your problem is you are not able to read script stored in storage . Your template is ok
