### ISSUE TITLE
New-AzureADApplication commandlet is missing the default set of permissions

### ISSUE THREAD

**Issue by stepsic-microsoft-com** [Azure/azure-powershell#1087]
When you create an AzureADApplication in the Active Directory portal, a few default settings are set, including the Reply URL and permissions to Sign In to Active Directory. However, neither of these are set when you use the New-AzureADApplication commandlet. In addition, there are no flags to take these as parameters, so it's basically impossible to create the (default) App configuration in PS.

The ideal solution would be to allow the users to pass the reply URL and permissions as additional parameters, although a simpler/faster solution would be to snap to excatly whatever the default settings are for the portal UI.

**Comment by hovsepm** [comment]
Thanks! Assigned to Authorization team.

**Comment by kerslake** [comment]
I'd like to be able to update the collection of reply URLs for an application via powershell. Not sure if that would fall under this existing open issue?

My scenario is I have multiple websites being deployed, with more being added in the future, all relating to a single Azure AD application. For each new deployed web site I need to add a new reply URL. Ideally I'd like to script this as part of the release process using powershell.

**Comment by saurabhgodhwani** [comment]
Any updates on this if its possible today. I am looking for a way to set Reply URLs to the new Application using New-AzureADApplication cmndlet or any other if possible to solve the issue..

**Comment by maddieclayton** [comment]
@darshanhs90 @cormacpayne Is this an issue in the AzureRM cmdlets?  If this is just Azure SM, are we planning to update this cmdlet in the future?

**Comment by cormacpayne** [comment]
@maddieclayton this looks to be resolved in the latest version of `AzureRM.Resources`

@darshanhs90 let me know if this is not the case
