### ISSUE TITLE
AzureAppConfiguration Remove Get-AzAppConfigurationStoreKeyValue

### ISSUE THREAD

**Issue by jimmyca15** [Azure/azure-powershell#10883]
As discussed with @isra-fel the Get-AzAppConfigurationStoreKeyValue cmdlet should be removed from the Azure App Configuration PowerShell module. This API is not intended for use in places other than ARM template. It was brought into the module via the generator and we would like to remove it ASAP and keep it out of future generated versions.

**Comment by dolauli** [comment]
Fixed in https://github.com/Azure/azure-powershell/pull/10939
