### ISSUE TITLE
"end processing" message printed twice

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#10887]
## Description

Setting `$DebugPreference = "Continue"`, run any cmdlet, "***cmdlet end processing" is printed  twice.
![image](https://user-images.githubusercontent.com/11371776/72308852-48b62380-36b8-11ea-817f-7eddb718e6e9.png)

Root cause:
[`AzureRMCmdlet.LogCmdletEndInvocationInfo()`](https://github.com/Azure/azure-powershell-common/blob/c4e331b51fae5843d8c401fd482a529e55bffcbf/src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs#L352) calls [`AzurePSCmdlet.LogCmdletEndInvocationInfo()`](https://github.com/Azure/azure-powershell-common/blob/c4e331b51fae5843d8c401fd482a529e55bffcbf/src/Common/AzurePSCmdlet.cs#L300). They both print the message.

## Cost
1

**Comment by isra-fel** [comment]
@Dingmeng-xue FYI

**Comment by dingmeng-xue** [comment]
It's due to incorrect [overwrite](https://github.com/Azure/azure-powershell-common/blob/e527f5d25cbc3313c7a26df5fee4a0a212c36783/src/ResourceManager/Version2016_09_01/AzureRMCmdlet.cs#L337). It is fixed in [PR](https://github.com/Azure/azure-powershell-common/pull/168)

**Comment by dingmeng-xue** [comment]
Resolved.
