### ISSUE TITLE
Get-azAKS -location $location 

### ISSUE THREAD

**Issue by lukeb1961** [Azure/azure-powershell#10898]
## Description of the new feature
New-Azaks : Version 1.12.8 is not supported in this region. Please use [az aks get-versions] command to get the supported 
version list in this region.

A Powershell error that says go use a different scripting engine to get the answer, is NOT appropriate. There should be a way to retrieve this info via Powershell. Just add a -Location parameter or something.

## Proposed implementation details (optional)
Get-azAKS -location $location  should return properties such as KubernetesVersion(s) supported.

**Comment by dingmeng-xue** [comment]
We are proposing `Get-AzAKSVersion -location $location`

**Comment by dingmeng-xue** [comment]
Duplicate of #10898
