### ISSUE TITLE
ResourceDiscoveryMode is defined in the docs but doesnt actually seem to be implemented?

### ISSUE THREAD

**Issue by richardharrison2** [Azure/azure-powershell#10891]
Hi,
The parameter to force reevaluation of the policy while documented does not seem to actually have been implemented - for example

Start-AzPolicyRemediation -PolicyAssignmentId $policyAssignmentId -Name "dummyremediation" -ResourceDiscoveryMode ReEvaluateCompliance

returns

Start-AzPolicyRemediation : A parameter cannot be found that matches parameter name 'ResourceDiscoveryMode'.
At line:3 char:92

Regards,
Rich

**Comment by dingmeng-xue** [comment]
Thanks for reporting. It's due to something wrong during release. We will fix it ASAP.

**Comment by jturver1** [comment]
I'd add to the above that with version 1.2 of the Az.PolicyInsights module released a few days back, the "-ResourceDiscoveryMode" parameter is now there, and the "ReEvaluateCompliance" value works in the subscription scope for a Policy Initiative assignment for example.

BUT, some part of the call fails when then scope is set to a Management Group.

i.e. This works (subscription scope, for a policy initiative assignment):
Select-AzSubscription -Subscription xxxxxxxxxxxxxxxxxxxxxxx
Start-AzPolicyRemediation -PolicyAssignmentId $policyAssignmentId -PolicyDefinitionReferenceId $PolicyDefinitionReferenceId -Name $RemediationName -ResourceDiscoveryMode ReEvaluateCompliance

This returns an error (Management Group scope, for a policy initiative assignment):
Start-AzPolicyRemediation -PolicyAssignmentId $policyAssignmentId -ManagementGroupName $mgmtGroupName -PolicyDefinitionReferenceId $PolicyDefinitionReferenceId -Name $RemediationName -ResourceDiscoveryMode ReEvaluateCompliance

Error:
Operation returned an invalid status code 'BadRequest'
    + CategoryInfo          : CloseError: (:) [Start-AzPolicyRemediation], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.PolicyInsights.Cmdlets.Remediation.StartAzureRmPolicyRemediation
    + PSComputerName        : localhost

Is the " -ResourceDiscoveryMode ReEvaluateCompliance" option supported for the *Management Group* vs. Subscription scope in this context?

**Comment by dingmeng-xue** [comment]
Thanks for letting us know. Forward it to Policy team.

**Comment by kenieva** [comment]
Thanks for the information. We are will be looking into this.

**Comment by calecarter** [comment]
This is expected as evaluating compliance as part of remediation is not supported at the MG level.  If you add the -Debug switch to the PowerShell cmdlet, you will get a more meaningful error:

{
  "error": {
    "code": "InvalidCreateRemediationRequest",
    "message": "The request to create remediation 'XXXXXXXXXXXX' is invalid. **Evaluating compliance before remediation is only supported for remediations at subscription scope and below.** The requested scope was '/providers/Microsoft.Management/managementGroups/XXXXXXXX'."
  }
}

Will create a work item to update the Start-AzPolicyRemediation cmdlet documentation.
