### ISSUE TITLE
Add -SubscriptionObject parameter to Get-AzContext to simplify use of -DefaultProfile

### ISSUE THREAD

**Issue by ivanignatiev** [Azure/azure-powershell#10890]
Hello, 

Even if we can use `Get-AzSubscription -SubscriptionId "xxxx-xxxx-xxxx-xxxx"  | Set-AzContext` to switch the context, it is very painful to do it in loops to manage resources across multiple subscriptions. 

That is more easy to save `AzContext` object in a variable and use `-DefaultProfile` parameter after.  Even if we can find a context with `$subscriptionContext = (Get-AzContext -ListAvailable | where -Property Subscription -Value (Get-AzSubscription -SubscriptionId
"xxxxx-xxx-xxx-xxx-xxxxx") -Like)` pipeline, that will be more correct to use the same method as for `Set-AzContext`

```
$subscriptionContext = Get-AzSubscription -SubscriptionId "xxxx-xxxx-xxxx-xxxx"  | Get-AzContext
``` 

Unfortunately, this scenario is not supported currently.

**Comment by dingmeng-xue** [comment]
@ivanignatiev , do you think below code can resolve your issue and get context object?
```
Get-AzSubscription -SubscriptionId "xxxx-xxxx-xxxx-xxxx" | Set-AzContext
$subscriptionContext = Get-AzContext
```

**Comment by ivanignatiev** [comment]
@dingmeng-xue I agree it satisfies the need to put the context in a variable but still it is changing the default context and can impact cmdlets which does not use `-DefaultProfile`. So, after an assigment proposed by you, you need  also to switch back to the previous context. 

What I looking for, that is more looks like the same behavior as with Azure CLI `--subscription` argument.

**Comment by dcaro** [comment]
@ivanignatiev we have proposed changes similar to what you are describing in the following document: https://github.com/Azure/azure-powershell/blob/generation/documentation/RFC/RFC0002-SubscriptionList-in-Get.md

Please have a look and let us know how that is likely solving your issue and share any other suggestions that you may have.

**Comment by ivanignatiev** [comment]
@dcaro Amazing proposal! It will solve my issue for sure, thank you!  

At the same time, adding `-ResourceId` parameter to Az cmdlets could resolve the issue, as well.

**Comment by dcaro** [comment]
@ivanignatiev thanks for the feedback, since we have this effort in our backlog, I'm closing the issue for now. Feel free to ping again if you have any further question or comments.
