### ISSUE TITLE
Error 404 - Page not found for link "see Approved verbs for PowerShell Commands."

### ISSUE THREAD

**Issue by arunko34** [Azure/azure-powershell#10903]
Section "Find commands" having a link "see Approved verbs for PowerShell Commands". The link giving an error "404 - Page not found".

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will correct URL soon.

**Comment by Minewiskan** [comment]
Fixed in https://github.com/MicrosoftDocs/azure-docs-powershell/pull/1306.
Now live.
