### ISSUE TITLE
No cmdlets to manage ACL permissions at Gen2 container level

### ISSUE THREAD

**Issue by gqian3** [Azure/azure-powershell#10914]
## Description of the new feature
To be able to manage ACL permissions in gen2 datalake, we are using one of the latest preview version of Az.Storage Module: 1.11.1-preview, however we noticed there are currently no cmdlet to manage ACL permissions at Gen2 container level, e.g.
if we have a container/file system created in the gen2 datalake storage account and have directories in it. We want to have a cmdlet to manage the ACL permissions to this container so that only owner and owning group have read,write,execute access to the container.

**Comment by dingmeng-xue** [comment]
Include storage team to evaluate this requirement.

**Comment by blueww** [comment]
@gqian3 
Per the current SDK limitation, PowerShell don't have cmdlet to set permission/acl on Filesystem.
Please see if following command can help you to do so.
```powershell
update-AzDataLakeGen2Item -Context $ctx -FileSystem $filesystemName -Path "/" -Permission rwxrwx--- 
update-AzDataLakeGen2Item -Context $ctx -FileSystem $filesystemName -Path "/" -Acl $acl
```

**Comment by gqian3** [comment]
This works great, thanks.

Also as part of our automation, we also do a checking and remove the ACLs when it's matching certain conditions, by using this cmdlet in old RM module:
Remove-AzureRmDataLakeStoreItemAclEntry
Is there corresponding cmdlet doing remove given Acl entry in the new Az.Storage module for Gen2 data lake too?

**Comment by blueww** [comment]
@gqian3 
Good to know it works! 

For remove a ACL entry, we don't have a cmdlet to do so, but you can refer [this sample](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-powershell#update-directory-and-file-permissions) to see how to remove an ACL entry with specific properties.

Anyway, please note, as these cmdlets is in preview module, we might will have breaking on this behavior when release it in stable Powershell release.

**Comment by gqian3** [comment]
Thanks. I will try that for updating ACLs. 

However to test these ACLs, I gave rwx permission in directory level for group filled with service principle, do I have to assign some RBAC roles at storage account level to the group or service principles? My goal is to have different group to access different directories inside same container in a storage account. How can I achieve that?

**Comment by blueww** [comment]
@gqian3 
I don't quite get what you require for the question of credential and permission.
This looks like a question for the feature instead of Powershell usage, you might can raise it on https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-powershell to see if anyone can help you on this.

Anyway, generally, after you set the ACL, to make the ACL work in Powershell, you need login with OAuth like:
```powershell
Connect-AzAccount
$ctx = New-AzStorageContext -StorageAccountName  $accountName
# run cmdlets for datalakegen2 with storage context $ctx
```

**Comment by gqian3** [comment]
Sorry I mean to ask how do I test the ACLs permission by connecting using the AD application credentials, assuming I give Rwx permission to the AD application in directory level using ACL. Do I have to give RBAC role to the AD application?

**Comment by blueww** [comment]
@gqian3 
You can refer to this doc for the permission you need : https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-access-control#role-based-access-control
It seems you will need Blob related roles to manage datalake gen2 items.
In my test, my AD application with "Storage Blob Data Owner" role works well with Datalake Gen2 items.

**Comment by gqian3** [comment]
Thanks for your support.

One more questions, we noticed a need to update the default mask ACL to change the limitation in the new child item inside the container for both access and default mask ACLs. Is there an API to update an existing Container Mask ACLs?

**Comment by blueww** [comment]
@gqian3 
This is more like a feature question than a powershell cmdlet question.
You can see the rest API of Datalake Gen2 in https://docs.microsoft.com/en-us/rest/api/storageservices/data-lake-storage-gen2, and see if any API can match your requirements. And if you don't find how to run in in Powershell, please contact us.

Besides that, since this is a different question than the original issue, for better track of every issues, would you please close this issue (as it's already resolved.) And if you still need assistance for other Datalake Gen2 issues, please open a new issue.

**Comment by gqian3** [comment]
Thank you so much for your response.

While I agree that this is a feature question, that's why this ticket was opened in that category. I apologize to keep this ticket open for so long, but In fact, I think the last issue I raised is still in the same topic, as I spent some time and still don't find any option in the update-AzDataLakeGen2Item cmdlet to set the mask ACLs. Could you please confirm. Thanks a lot again.

**Comment by blueww** [comment]
@gqian3 
Actually, I don't know a rest API to do that.
So if you can find how to do that from rest API, I can tell you how to do that from Powershell.
Else, you might need to contact feature team to see if they can add the support to rest API.

**Comment by blueww** [comment]
@gqian3

As we have following all your questions in mail, will close this issue.
Feel free to contact us again if you need any further support.
