### ISSUE TITLE
Request to a downlevel service failed

### ISSUE THREAD

**Issue by DominicBurford** [Azure/azure-powershell#10925]
# Description
We use TFS2015 to deploy our ASP.NET WebAPI services to our Azure web hosting. We use the Azure Web App Deployment task in TFS to do this. Recently this has begun to fail. After some investigation I have narrowed this to the  Publish-AzureWebDeployment.ps1 PS script. 

It seems that many of the cmdlets invoked in that script are now deprecated (Get-AzureWebsite, New-AzureWebSite etc). 

Is there a replacement of the Publish-AzureWebDeployment.ps1 script that I can use to deploy my services to Azure? What is the migration path for anyone using the older TFS depoyment script? 

## Steps to reproduce

```Deploy any ASP.NET application to Azure using TFS2015
![2020-01-15 14_35_00-WebServices](https://user-images.githubusercontent.com/20540871/72602579-65986400-390f-11ea-985a-1ef887dd82de.png)

**Comment by dingmeng-xue** [comment]
Please try the new version of those cmdlets
https://docs.microsoft.com/en-us/powershell/module/az.websites/?view=azps-3.3.0#app_service

**Comment by DominicBurford** [comment]
The problem is that all they are contained within a Microsoft Azure deployment script associated with the TFS Azure deployment task. The script they are executed from is **Publish-AzureWebDeployment.ps1**. Will you be issuing a new version of this script or am I supposed to re-write this Microsoft script myself?

**Comment by DominicBurford** [comment]
Looking at the list of cmdlets I think the one I need is Publish-AzWebApp but when I execute it I get the following error message .

"The term Publish-AzWebApp is not recognized as the name of a cmdlet function script file or operable program"

How do I update my system to get the new cmdlets?
![2020-01-17 14_42_30-Program Manager](https://user-images.githubusercontent.com/20540871/72620880-17e42180-3938-11ea-9279-66d6949d2fd2.png)

**Comment by dingmeng-xue** [comment]
@DominicBurford , The error is due to modules in your environment is old. Where does the script Publish-AzureWebDeployment.ps1 come from? It's not maintained by azure-powershell.

**Comment by DominicBurford** [comment]
The script Publish-AzureWebDeployment.ps1 is part of the TFS task "Azure Web App Deployment". If this is not an azure-powershell script can you send me in the direction of where this needs to be submitted?

**Comment by dingmeng-xue** [comment]
Hi App Services team, please help to look into Publish-AzureWebDeployment.ps1 and consider how to upgrade it using latest cmdlets.

**Comment by SteGriff** [comment]
I have this problem too with TFS 2015 and the deployment task, `\tasks\AzureWebPowerShellDeployment\1.0.25\Publish-AzureWebDeployment.ps1`

**Comment by DominicBurford** [comment]
> I have this problem too with TFS 2015 and the deployment task, `\tasks\AzureWebPowerShellDeployment\1.0.25\Publish-AzureWebDeployment.ps1`

I ended up writing an FTP script to deploy my web app to Azure. You can obtin the FTP credentials from the Azure dashboard for the Azure app. I then automated the FTP using a script with WinSCP. This might work for you too.

**Comment by panchagnula** [comment]
these were deprecated since AppService doesn't support RDFE commands anymore - the recommend ARM deployment approach is https://docs.microsoft.com/en-us/powershell/module/az.websites/publish-azwebapp?view=azps-3.5.0
