### ISSUE TITLE
CRUB Monitor resource - Log Analytics Workspace

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#10920]
## Description of the new feature
User needs to create log analytics workspace via Azure PowerShell

Log Analytics workspace
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/design-logs-deployment

## Proposed implementation details (optional)
CLI supports https://docs.microsoft.com/en-us/cli/azure/monitor?view=azure-cli-latest

**Comment by VeryEarly** [comment]
**Update**

After compared with CLI:
```az monitor log-analytics workspace get-schema, Get-AzOperationalInsightsSchema```

```az monitor log-analytics workspace create, New-AzOperationalInsightsWorkspace```

```az monitor log-analytics workspace delete, Remove-AzOperationalInsightsWorkspace```

```az monitor log-analytics workspace show, Get-AzOperationalInsightsWorkspace```

```az monitor log-analytics workspace list, Get-AzOperationalInsightsWorkspace```

```az monitor log-analytics workspace update, Set-AzOperationalInsightsWorkspace```

```az monitor log-analytics workspace get-shared-keys, Get-AzOperationalInsightsWorkspaceSharedKey```

```az monitor log-analytics workspace list-management-groups, Get-AzOperationalInsightsWorkspaceManagementGroup``` 

```az monitor log-analytics workspace pack disable, Set-AzOperationalInsightsIntelligencePack```

```az monitor log-analytics workspace pack enable, Set-AzOperationalInsightsIntelligencePack```

```az monitor log-analytics workspace pack list, Get-AzOperationalInsightsIntelligencePack```

```az monitor log-analytics workspace list-usages, Get-AzOperationalInsightsWorkspaceUsage```

CRUD cmdlets for LA Workspace exists in Az.OperationalInsights already.

Returned objects for "pack list"/"list usage" for CLI are raw response(in Json), list of key value pairs for Azure Powershell.

"get schema" in CLI use api version 2015-03-20 
while in Azure Powershell use api version 2015-11-01-preview
returned object looks different.
