### ISSUE TITLE
Not able to use "Azure" module after fresh install on powerShell, while "az" module works fine

### ISSUE THREAD

**Issue by SherryGuo1021** [Azure/azure-powershell#10944]
PS C:\Users\xiaxguo> Get-InstalledModule Azure

Version    Name                                Repository           Description                                                                                                                                        
-------    ----                                ----------           -----------                                                                                                                                        
5.3.0      Azure                               PSGallery            Microsoft Azure PowerShell - Service Management                                                                                                    

PS C:\Users\xiaxguo> Add-AzureAccount
Add-AzureAccount : Object reference not set to an instance of an object.
At line:1 char:1
+ Add-AzureAccount
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzureAccount], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.WindowsAzure.Commands.Profile.AddAzureAccount

**Comment by SherryGuo1021** [comment]
Tried to install/uninstall "Azure" module for several times, still doesn't work.
I'm on Windows 10.

After searching on Internet, found below steps:
Remove-Item "$env:USERPROFILE\AppData\Roaming\Windows Azure Powershell"

But unfortunately, I don't see the corresponding folder under XXX\Roaming.

Looking forward to your advise.

**Comment by VeryEarly** [comment]
hi @SherryGuo1021 ,

Can you try to run in windows-powershell instead of powershell core?

**Comment by SherryGuo1021** [comment]
Hi @VeryEarly,

Thanks for your prompt response. I tried to install "Azure" module via windows-powerShell(version 5.1, embedded in Windows 10), as well as install it on newly installed PowerShell core (6.2.2), unfortunately, same result.

**Comment by VeryEarly** [comment]
Hi @SherryGuo1021 ,

I tried following commands in my windows powershell session (Windows 10 default)
``` powershell
Install-Module -Repository PSGallery -Name Azure -AllowClobber
Get-module -ListAvailable -Name Azure
Add-AzureAccount
```
got no error and was able to login, can you provide more detail how to reproduce your error messages?

**Comment by SherryGuo1021** [comment]
Hi @VeryEarly,

Nothing special, I just give it another try with exact same command you provided, still turns out to be failed, below is the output:

PS C:\windows\system32> Install-Module -Repository PSGallery -Name Azure -AllowClobber

PS C:\windows\system32> Get-module -ListAvailable -Name Azure


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                            
---------- -------    ----                                ----------------                                                                                                            
Script     5.3.0      Azure                               {Get-AzureAutomationCertificate, Get-AzureAutomationConnection, New-AzureAutomationConnection, Remove-AzureAutomationConn...



PS C:\windows\system32> Add-AzureAccount
Add-AzureAccount : Object reference not set to an instance of an object.
At line:1 char:1
+ Add-AzureAccount
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzureAccount], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.WindowsAzure.Commands.Profile.AddAzureAccount

**Comment by VeryEarly** [comment]
Hi @SherryGuo1021 ,

I'll look into this issue and will get back to you.

**Comment by SherryGuo1021** [comment]
Hi @VeryEarly,

I resolved it by myself. Not sure which part helps resolve the issue, but I tried below steps recently:
reboot host, uninstall AzureRM module, uninstall Azure module, remove the azure folder under powershell installation folder.

**Comment by VeryEarly** [comment]
> Hi @VeryEarly,
> 
> I resolved it by myself. Not sure which part helps resolve the issue, but I tried below steps recently:
> reboot host, uninstall AzureRM module, uninstall Azure module, remove the azure folder under powershell installation folder.

Apologize for not replying on time, I still cannot find the cause either, might be something wrong with your previous installation.
