### ISSUE TITLE
Publish-AzureWebsiteProject should list files synchronized like MSDeploy would do

### ISSUE THREAD

**Issue by bgever** [Azure/azure-powershell#1095]
When executing the `Publish-AzureWebsiteProject` cmdlet, even with specifiying `-Verbose`, there is no output of what files are synchronized to the server.

This file list would show up with MSDeploy, and is useful to know what files are actually being uploaded, as it sometimes may need additional configuration to exclude or include certain files.

It would be great if the `Publish-AzureWebsiteProject` could list this when running it with the `-Verbose` parameter.

**Comment by ValterSantosMatos** [comment]
+1

**Comment by aneillans** [comment]
This looks like a trivial change to make, and I agree it would be beneficial.

Before I look at creating a new form to add this one quick question: I assume people would prefer this was configurable behaviour :) If so, a general count of updated files should always be output I figure?

**Comment by bgever** [comment]
Yes, I believe that's also the behavior when using MSDeploy from Visual Studio on the output window. The summary is useful especially if the list of changes is huge. For instance, it might be just the overwrite you want to spot rather than adds. And then if there is an override, what was it?

**Comment by cormacpayne** [comment]
It appears this issue has been resolved. Closing this issue.
