### ISSUE TITLE
Add-AzTableRow - Exception calling "Execute" with "1" argument(s): "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by pawp81** [Azure/azure-powershell#10969]
I am running following command to add record to Azure Table Storage:
              
Add-AzTableRow -table $tableAIR `
        -partitionKey $PartitionKey `
        -rowKey ([guid]::NewGuid().tostring()) `
        -property @{"CreationTime"=$auditgeneralID.CreationTime;"Operation"=$auditgeneralID.Operation;"InvestigationId"=$auditgeneralID.InvestigationId;"InvestigationType"=$auditgeneralID.InvestigationType;"LastUpdateTimeUtc"=$auditgeneralID.LastUpdateTimeUtc;"StartTimeUtc"=$auditgeneralID.StartTimeUtc;"Status"=$auditgeneralID.Status;""=$auditgeneralID.UserIP}

and I am getting the following error:

Exception calling "Execute" with "1" argument(s): "Object reference not set to an instance of an object."
At C:\Program Files\WindowsPowerShell\Modules\AzureRmStorageTable\2.0.2\AzureRmStorageTableCoreHelper.psm1:239 char:10
+ ...      return ($Table.Execute([Microsoft.Azure.Cosmos.Table.TableOperat ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : StorageException

I have installed on my Windows 10 machine:
AzureRMStorageTable 2.0.2
Az.Storage 1.11.0

**Comment by markcowl** [comment]
AzureRMSTorageTable (which contains Add-AzTableRow)  is not an Azure PowerShell module.  Please contact the owner of that module for this issue.

Forwarding to the storage team as FYI.

**Comment by pawp81** [comment]
@markcowl thank you. Do you know which Azure Powershell module would allow me to add entries to Azure Table Storage?

**Comment by blueww** [comment]
@pawp81 
This is the repo where the issues should be raised, detailed documentation is there a well:
https://github.com/paulomarquesc/AzureRmStorageTable

**Comment by blueww** [comment]
@pawp81 
I will close this issue, as this cmdlets is not from Azure Powershell.
Please file the issue in the correct repo: https://github.com/paulomarquesc/AzureRmStorageTable, And the related teams will help you on that.

Feel free to contact us if you need further support on Azure Powershell.
