### ISSUE TITLE
GeographyGroup is missed in Get-AzLocation result

### ISSUE THREAD

**Issue by blrchen** [Azure/azure-powershell#10974]
## Description
GeographyGroup is missed in Get-AzLocation result. It seems GeographyGroup is added in REST api with latest version and current Az module 3.3.0 needs to be updated to include it.

## Steps to reproduce

```powershell
Get-AzLocation
```
Expected result; result should contains GeographyGroup info for each regions
Actual result: no GeographyGroup info can be found in result

## Environment data

```
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
3.3.0
```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
Current api version is still 2016-06-01. We need to evaluate impact when it is upgraded to 2019-11-01.

**Comment by blrchen** [comment]
Would you mind sharing which release rollout would include this fix?

**Comment by blrchen** [comment]
Any ETA for when the fix will be ready?

**Comment by jdelforno** [comment]
Can we also get the long/lat co-ordinates as well?

**Comment by lilyjma** [comment]
@ifeoluwaokunoren do we have updates on this?

**Comment by navba-MSFT** [comment]
@blrchen Apologies for the late reply. Could you please let me know if you are still facing this issue ? This issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by blrchen** [comment]
Honestly speaking, this is no longer an issue for me as I ended up switching to azure cli which seems mitigating bugs quicker. However I guess fixing this will benefit people who mainly use PowerShell.
