### ISSUE TITLE
Get-AzSecurityTask RecommendationType is not consistent

### ISSUE THREAD

**Issue by ThomasAnnerel** [Azure/azure-powershell#10970]
Strange that the RecommendationType is actually more a description instead of a type.

Here you find some live examples:
Example on Descriptions:
- Diagnostic logs in Service Bus should be enabled
- Remote debugging should be turned off for API App.
- DDoS Protection Standard should be enabled
Example on Types
- EncryptionOnVm
Al these values come from the RecommendationTYpe

I would expect to have 2 variable returning from Az.Security Get-AzSecurityTask
RecommendationType: containing a small unique string  like EncryptionOnVm
RecommendationDescription: Containing the explanation

**Comment by dingmeng-xue** [comment]
Thanks for your suggestion. Forward it to security team.

**Comment by omerchechik** [comment]
The tasks API is pending deprecation.
Please use assessment API instead (https://docs.microsoft.com/en-us/rest/api/securitycenter/assessments/get)
