### ISSUE TITLE
Publish-AzCdnEndpointContent blob content presence validation

### ISSUE THREAD

**Issue by stiurin** [Azure/azure-powershell#10981]
## Description of the new feature
Publish-AzCdnEndpointContent currently doesn't error our if you ask it to preload content that doesn't exist on the blob

## Proposed implementation details (optional)
It would be good to have a flag that allows controlling this behavior

**Comment by VeryEarly** [comment]
Thanks for raising this issue, forwarded to service team

**Comment by hytao** [comment]
Hi, this feature is currently not available from the service provider Verizon. For feature requests please visit https://feedback.azure.com/forums/217313-networking?category_id=345019
