### ISSUE TITLE
Azure Storage Queue Message Peek

### ISSUE THREAD

**Issue by ehuggz** [Azure/azure-powershell#10987]
The current AZ module does not have read without removing from queue functionality for Storage Queue Messages, i.e. Peek.

**The AzureRM Powershell module has:**
Invoke-AzureRmStorageQueuePeekMessage and  Invoke-AzureRmStorageQueuePeekMessageList. 
**AZ CLI has:** 
`az storage message peek -q $queue --num-messages=$queueWindow --account-name $storageAccountName --account-key $storageKey`
**The Azure API has:**  
GET https://myaccount.queue.core.windows.net/myqueue/messages?peekonly=true 

**The AZ Module does not appear to have:** 
An equivalent set of Read - but Do Not Remove Peek functions.

## Proposed implementation details (optional)
Currently possible to replicate functionality via .Net classes as: [Microsoft.Azure.Storage.Queue.CloudQueueMessages)::PeakMessages()
[Microsoft.Azure.Storage.Queue.CloudQueueMessages)::PeakMessage()

Update AZ module to include 
Get-AzStorageQueuePeekMessage and 
Get-AzStorageQueuePeekMessages

**Comment by dingmeng-xue** [comment]
@dcaro , could you review this feature request?

**Comment by dcaro** [comment]
@dingmeng-xue we should close the gap with CLI and enable the feature since it is available in the REST API.

**Comment by blueww** [comment]
@ehuggz 
You can do all queue message operation in PSH by call storage client library API in Powershell. Like
```powershell
$queue = Get-AzStorageQueue -Name $queueName -Context $ctx
$queue.CloudQueue.PeekMessage()
```
you can find more details in https://docs.microsoft.com/en-us/azure/storage/queues/storage-powershell-how-to-use-queues.

**Comment by blueww** [comment]
@ehuggz
I plan to close this issue, and Powershell support do it by call storage client library API. And this is documeted.
Let me know if you have any concent.
