### ISSUE TITLE
Custom Domains Set-AzWebAppSlots -Hostnames (missing

### ISSUE THREAD

**Issue by PaulFarry** [Azure/azure-powershell#10980]
## Description of the new feature
The ability to set custom hostnames for WebAppSlots should work in the same was that you set hostnames for a WebApp. 

Without this feature it makes automating the creation of WebApps more cumbersome as you need to perform work arounds with Set-AzResource and a lot of internal detail.

## Proposed implementation details (optional)
Set-AzWebAppSlot  [-HostNames <String[]>] 
should follow Set-AzWebApp [-HostNames <String[]>]

The underlying library `Microsoft.Azure.Management.Websites`, public static class `WebAppsOperationsExtensions` already has a method to set them, the powershell just needs to expose this.
       ` public static HostNameBinding CreateOrUpdateHostNameBindingSlot(this IWebAppsOperations operations, string resourceGroupName, string name, string hostName, HostNameBinding hostNameBinding, **string slot**)`

**Comment by VeryEarly** [comment]
Thanks for raising the issue, forwarded to service team.

**Comment by ThejaChoudary** [comment]
Taking a look at this.

**Comment by PaulFarry** [comment]
Happy to do some testing for you if needed.
