### ISSUE TITLE
ApiManagement New Developer portal custom domain is not returned in Az cmdlet

### ISSUE THREAD

**Issue by KedarJoshi** [Azure/azure-powershell#11007]
Customer has set custom domain for their new developer portal via PowerShell and it ran successfully.   however on the get the custom domain hostname configuration isn't parsed.

**Comment by solankisamir** [comment]
Please download the update from 

Download the install package from Github: https://github.com/Azure/azure-powershell/releases/tag/v3.6.1-March2020 
Install the package from PSGallery: https://www.powershellgallery.com/packages/Az/3.6.1
