### ISSUE TITLE
Add dictionary of notification thresholds or parameter with type NotificationThreshold on New-AzConsumptionBudget

### ISSUE THREAD

**Issue by Isotop7** [Azure/azure-powershell#11005]
## Description of the new feature

When creating a new consumption budget in Azure Portal, you can specify multiple thresholds (max. 4) as percentages. The command `New-AzConsumptionBudget` only supports one decimal value, which does not really help.

For example in order to be notified when `20%`, `40%`, `80%` and `100%` of the budget are used, you have to create four separate notifications via powershell.

[Reference](https://social.msdn.microsoft.com/Forums/en-US/cbef629f-cf20-454f-81ba-ffd737e9f049/create-new-azconsumptionbudget-with-multiple-thresholds?forum=azureautomation)

## Proposed implementation details (optional)

Use dictionary or object representation with multiple thresholds. For example we could create a command like `New-AzConsumptionBudgetThresholds` which returns an object of type `NotificationThreshold` that could be specified when running `New-AzConsumptionBudget`.

**Comment by dingmeng-xue** [comment]
Billing team, can it be supported?

**Comment by ramaganesan-rg** [comment]
Update on Powershell scripts is in work in progress. In the interim, you can use this link as the reference to REST APIs.

https://docs.microsoft.com/en-us/rest/api/consumption/budgets/createorupdate
Here is the tutorial to create Budget using ARM template deployment - https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/quick-create-budget-template?tabs=CLI- https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/quick-create-budget-template?tabs=CLI
