### ISSUE TITLE
New-AzServiceBusSubscription Forbidden with -ForwardTo provided

### ISSUE THREAD

**Issue by russelltomkins** [Azure/azure-powershell#11012]
When using the -forwardto parameter with "New-AZServiceBusSubscription" or when passing a subscription object with the ForwardTo property with "Set-AZServiceBusSubscription" the server is returning a forbidden error.

The error message indicates an error with permissions on the target Queue however the path given to the target resource is missing the namespace name in its path. (Calling service principal has Contributor over the namespace)

**Path in Error Message**
`/subscriptions/<subscriptionid>/resourceGroups/<resourcegroupname>/providers/Microsoft.ServiceBus/queues/<queuename> `

It is missing `/namespaces/<namespacename>` prior to `/queues/<queuename>`

Error Generated using a Powershell Azure Function with the default loaded Az.ServiceBus module which is currently at 1.4.1

**Full Error**
```
Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: Set-AzServicebusSubscription : Operation returned an invalid status code 'Forbidden'
At D:\home\site\wwwroot\new-deployment\run.ps1:53 char:23
+ ... scription | Set-AzServicebusSubscription -ResourceGroupName "<resourcegropuname> ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (Microsoft.Azure.Man\u2026ion.ExecuteCmdlet():ErrorResponseException) [Set-AzServiceBusSubscription], ErrorResponseException
+ FullyQualifiedErrorId : The client '<clientid>' with object id '<objectid>' has permission to perform action 'Microsoft.ServiceBus/namespaces/topics/subscriptions/write' on scope '/subscriptions/<subscriptionid>/resourceGroups/<resourcegroupname>/providers/Microsoft.ServiceBus/namespaces/<namespace>/topics/<topicname>/subscriptions/<subscriptionname>'; however, it does not have permission to perform action 'write' on the linked scope(s) '/subscriptions/<subscriptionid>/resourceGroups/<resourcegroupname>/providers/Microsoft.ServiceBus/queues/<queuename>' or the linked scope(s) are invalid.,Microsoft.Azure.Commands.ServiceBus.Commands.Subscription.SetAzureRmServiceBusSubscription
 
Script stack trace:
   at <ScriptBlock>, D:\home\site\wwwroot\new-deployment\run.ps1: line 53

Microsoft.Azure.Management.ServiceBus.Models.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Azure.Management.ServiceBus.SubscriptionsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String namespaceName, String topicName, String subscriptionName, SBSubscription parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ServiceBus.SubscriptionsOperationsExtensions.CreateOrUpdateAsync(ISubscriptionsOperations operations, String resourceGroupName, String namespaceName, String topicName, String subscriptionName, SBSubscription parameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ServiceBus.SubscriptionsOperationsExtensions.CreateOrUpdate(ISubscriptionsOperations operations, String resourceGroupName, String namespaceName, String topicName, String subscriptionName, SBSubscription parameters)
   at Microsoft.Azure.Commands.ServiceBus.ServiceBusClient.CreateUpdateSubscription(String resourceGroupName, String namespaceName, String topicName, String subscriptionName, PSSubscriptionAttributes subscription)
   at Microsoft.Azure.Commands.ServiceBus.Commands.Subscription.SetAzureRmServiceBusSubscription.ExecuteCmdlet()


Exception: Operation returned an invalid status code 'Forbidden'
Stack:    at Microsoft.Azure.Management.ServiceBus.SubscriptionsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String namespaceName, String topicName, String subscriptionName, SBSubscription parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ServiceBus.SubscriptionsOperationsExtensions.CreateOrUpdateAsync(ISubscriptionsOperations operations, String resourceGroupName, String namespaceName, String topicName, String subscriptionName, SBSubscription parameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ServiceBus.SubscriptionsOperationsExtensions.CreateOrUpdate(ISubscriptionsOperations operations, String resourceGroupName, String namespaceName, String topicName, String subscriptionName, SBSubscription parameters)
   at Microsoft.Azure.Commands.ServiceBus.ServiceBusClient.CreateUpdateSubscription(String resourceGroupName, String namespaceName, String topicName, String subscriptionName, PSSubscriptionAttributes subscription)
   at Microsoft.Azure.Commands.ServiceBus.Commands.Subscription.SetAzureRmServiceBusSubscription.ExecuteCmdlet()
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. It is forwarded to ServiceBus team for further investigation.

**Comment by russelltomkins** [comment]
Further information, I attempted to perform this via an ARM REST API call and I am receiving the same error message so I assume the core issue is within the ARM API itself and not the PowerShell cmdlets.

**Comment by apraovjr** [comment]
@russelltomkins can you share more details on the exact Powershell command you used to create new subscription?

**Comment by russelltomkins** [comment]
@apraovjr The following below is used to create a new subscription. The topic and queues to be forwarded to already exist and were created through the Azure Portal.

Uncommenting the ForwardTo property will supply the parameter in the splat and generate the error message. As noted above, creating the same request directly through the ARM rest API produces the same error.

`$newSubscription = @{
    "ResourceGroupName" = "resourceGroupName"
    "Namespace" = "nameSpaceName"
    "Topic" = "topicName"
    "Name" = "subscriptionName"
    "DefaultMessageTimeToLive" = "P31D"
    "MaxDeliveryCount" = 20
    "EnableBatchedOperations" = $true
    "DeadLetteringOnMessageExpiration" = $true
    "LockDuration" = "PT1M"
    #"ForwardTo" = "queueToForwardTo"
    "ForwardDeadLetteredMessagesTo" = "dlqToForwardTo"
   
}

New-AZServiceBusSubscription @newSubscription
`

**Comment by apraovjr** [comment]
@russelltomkins We tried to repo the issue and couldnt get the error. PS version we used for testing is 5.1.2. Which version are you using and can you update the PS version?

**Comment by russelltomkins** [comment]
@apraovjr Can you advise the region for your service bus namespace? As I mentioned, this error is occurring via both the PowerShell cmdlets and directly against the ARM API itself.

**Comment by apraovjr** [comment]
@russelltomkins Can you provide us the namespace information?

**Comment by russelltomkins** [comment]
@apraovjr  I've just created a test namespace called "au-sbtest" which is located in "Australia East" and it is exhibiting the same errors.

**Comment by apraovjr** [comment]
@russelltomkins I just checked the logs for that namespace and see errors as below

Failed to process request. TrackingId: b4254679-7c72-4b6d-adbc-a67464ef2a3a_M7CH3_M7CH3, SubsystemId: NoSystemTracker, CorrelationRequestId: 85cc73c7-d51e-4b72-9eda-b44a766cd68a, ClientRequestId: 13e0dabb-f3ec-4c1d-b8d5-b8b3b951a04d, RequestUri: https://sbgm.windows.net/subscriptions/***********/resourceGroups/au-wh4b-readiness/providers/Microsoft.ServiceBus/namespaces/au-sbtest/queues/forwardToQueue?api-version=2017-04, HttpMethod: GET, ErrorCode: NotFound, **ErrorMessage: The requested resource forwardToQueue does not exist. CorrelationId: 85cc73c7-d51e-4b72-9eda-b44a766cd68a**

**Comment by russelltomkins** [comment]
@apraovjr Definitely exists. Just made sure everything is lowercase everywhere as well to rule out that as well. Still the same error being generated.

Interesting observation, it happily accepts and sets the "forwardtoqueue" queue as the destination for the "ForwardDeadLetteredMessagesTo" parameter.

**Comment by apraovjr** [comment]
@russelltomkins Looking at resources, we found that **dlqforwardtoqueue** and **forwardtoqueue** exists. Were those the queues you were using for -forwardTo property?

**Comment by russelltomkins** [comment]
Yes. The actual cmdlet params look like this:
-forwardto **"forwardtoqueue"**
-ForwardDeadLetteredMessagesTo **"dlqforwardtoqueue"**

**Comment by apraovjr** [comment]
@russelltomkins Thanks and for clarification you are using "ForwardTo" instead of -forwardto right?

**Comment by russelltomkins** [comment]
@apraovjr sorry, yes it is "ForwardTo" but that is just a PowerShell parameter name so it is case insensitive.

**Comment by russelltomkins** [comment]
Hi @apraovjr. Do you have any further insights into what the issue may be?

**Comment by apraovjr** [comment]
@russelltomkins We are still investigating and will get back to you with updates soon

**Comment by davidgouge** [comment]
Hi, I'm also experiencing the same problem when creating subscriptions using the Microsoft.Azure.Management.ServiceBus package in c#.  If I create a Topic Subscription and set ForwardTo an existing Queue, I get an error of Forbidden returned.  This is on a Premium Service Bus plan in the UK West region.  Creating the Subscription without the ForwardTo set works fine.

**Comment by davidgouge** [comment]
Hi @apraovjr , any news on this issue?  I've just attempted it again and experience the same results. :)

**Comment by axisc** [comment]
@russelltomkins  and @davidgouge 

I wonder if this issue is due to permissions - do you have manage permissions on the queue you are forwarding to?
