### ISSUE TITLE
New-AzureADApplication flag to enable personal accounts

### ISSUE THREAD

**Issue by jasonnutter** [Azure/azure-powershell#11029]
## Description of the new feature

When creating a new app registration through the Azure Portal, you are presented with an option to indicate the supported account types:

![image](https://user-images.githubusercontent.com/443409/73775600-12117d00-473b-11ea-8f26-5b8903716a25.png)

When I create an application via `New-AzureADApplication` (when signed into my work account), I can set `AvailableToOtherTenants`:

```sh
New-AzureADApplication -DisplayName "App Name" -ReplyUrls @("http://localhost:4200") -Oauth2AllowImplicitFlow 1 -AvailableToOtherTenants 1
```

However, that appears to only make the application multi-tenant. Attempting to sign into the application with my @outlook.com account results in the following error:

![image](https://user-images.githubusercontent.com/443409/73775829-82b89980-473b-11ea-8ac6-a5e38f1ac271.png)

I don't see anything in [the documentation](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadapplication?view=azureadps-2.0) that would enable this. I realize I can technically change this after the application has been created (via the manifest editor), but it would be nice if this could be done when creating the application.

## Proposed implementation details (optional)

`-AvailableToPersonalAccounts`

**Comment by dingmeng-xue** [comment]
Hi @jasonnutter  , we have released the preview version of Az.Resources 5.0.0 https://www.powershellgallery.com/packages/Az.Resources/5.0.0-preview

Could you check whether existing parameter set can meet your requirement?
