### ISSUE TITLE
Input type incorrect in doc/markdown for Restore-AzSqlInstanceDatabase

### ISSUE THREAD

**Issue by VeryEarly** [Azure/azure-powershell#11023]
## Description
input type of "InputObject" parameter for cmdlet "Restore-AzSqlInstanceDatabase" is "Microsoft.Azure.Commands.Sql.ManagedDatabase.Model.AzureSqlManagedDatabaseBaseModel"

However, at the end of the [official docs](https://docs.microsoft.com/en-us/powershell/module/az.sql/restore-azsqlinstancedatabase?view=azps-3.3.0) and the [help file](https://github.com/Azure/azure-powershell/blame/master/src/Sql/Sql/help/Restore-AzSqlInstanceDatabase.md#L435), in the "INPUTS" field, they were specified as "Microsoft.Azure.Commands.Sql.ManagedDatabase.Model.AzureSqlManagedDatabaseModel"

**Comment by jaredmoo** [comment]
What is the impact of this issue?
