### ISSUE TITLE
[1.0.0-preview] Add-AzureRmAccount has mutually exclusive parameters in the same parameter set

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#1102]
Add-AzureRmAccount has -SubscriptionName and -SubscriptionId parameters in the same parameter set. They are mutually exclusive and need to be separated in different parameter sets.

**Comment by markcowl** [comment]
@alexandair good catch.  In general, do you tend to use the subscription name or id to identify subscriptions?

**Comment by alexandair** [comment]
I use the subscription name.

**Comment by mbsnl** [comment]
"Select-AzureRmSubscription" does not have the "-Default" switch anymore. Is the idea that this is replaced by the "-SubscriptionName" and "-SubscriptionId" parameters of the "Add-AzureRmAccount" CmdLet?

**Comment by AWahlqvist** [comment]
The same thing goes for 'Select-AzureRmSubscription' aswell.

**Comment by alexandair** [comment]
Select-AzureRmSubscription is an alias for **Set-AzureRmContext** cmdlet, so that's the one that also need to be fixed.

**Comment by markcowl** [comment]
@alexandair  The intention is that Select-AzureRmSubscription changes the context statically, without making any calls off the box.  The -SubscriptionName parameter is meant to fill out the subscription name property of the subscription in the context.  You can do this for the functionality you want:
```
Get-AzureRmSubscription -SubscriptionName <name> | Select-AzureRmSubscription
```

That said, this has proven to be somewhat confusing to users.so we are changing this cmdlet to query for the subscription from the service, you can track the progress of this item here:  https://www.pivotaltracker.com/story/show/105517922

**Comment by markcowl** [comment]
This fix will be out in the 11/3 release.  Clopsing

**Comment by pcgeek86** [comment]
Instead of querying the service, why not query the `AzureProfile` object? No REST calls would be required for that.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@alexandair apologies, this was fixed for Set-AzureRmContext (Select-AzureRmSubscription), but not for Add-AzureRmAccount.  Will file an issue to fix this in the next sprint.

**Comment by markcowl** [comment]
@pcgeek86 There is only one account and subscription in the RMProfile.  We rely on the service because permissions to a subscription can be added or removed with a single RBAC command, and any local cache can be quickly out of date.

**Comment by markcowl** [comment]
@alexandair You can follow progress on this issue here: https://www.pivotaltracker.com/story/show/107738048

**Comment by alexandair** [comment]
There is still one parameter set with mutually exclusive parameters (-SubscriptionId and -SubscriptionName):

```PowerShell
Add-AzureRmAccount -Credential <pscredential> -ServicePrincipal -TenantId <string> [-Environment 
<AzureEnvironment>] [-EnvironmentName <string>] [-SubscriptionId <string>] [-SubscriptionName <string>] [<CommonParameters>]
```

**Comment by wangzq** [comment]
Following was working in 1.3.0 but not in 1.5.0:

```
Get-AzureRmSubscription -SubscriptionName <name> | Select-AzureRmSubscription

Set-AzureRmContext : Cannot retrieve the dynamic parameters for the cmdlet. Cannot process argument because the value of argument "validValues" is out of range. Change argument "validValues" to  a value
that is within range.
Parameter name: validValues
Actual value was System.String[].
```

**Comment by hovsepm** [comment]
@wangzq Unable to repro. in my case everything works without errors. Could you run it in debug mode?
```
Get-AzureRmSubscription -SubscriptionName <name> -Debug | Select-AzureRmSubscription -Debug
```

**Comment by wangzq** [comment]
@hovsepm Did you first use `Save-AzureRmProfile` then use `Select-AzureRmProfile` to re-use the auth token?

**Comment by markcowl** [comment]
Need to port back parameter set updates

**Comment by cormacpayne** [comment]
Issue has been resolved in PR https://github.com/Azure/azure-powershell/pull/3042
