### ISSUE TITLE
Get-AzureRmNetworkInterface : Operation returned an invalid status code 'BadRequest' StatusCode: 400

### ISSUE THREAD

**Issue by guidovbrakel** [Azure/azure-powershell#11025]
In a AzureRM PowerShell script I get the following error:
Get-AzureRmNetworkInterface : Operation returned an invalid status code 'BadRequest'
StatusCode: 400

I'm running the following following:
`$nics = Get-AzureRmNetworkInterface -ResourceGroupName “Production”`

This is my complete script:
```
$nics = Get-AzureRmNetworkInterface -ResourceGroupName “name”
Foreach ($nic in $nics) {
    $nic.EnableAcceleratedNetworking = $true
    $nic | Set-AzureRmNetworkInterface
}
```

When I run this manually I get no error:
`$nics = Get-AzureRmNetworkInterface -ResourceGroupName “name”`

**Comment by dingmeng-xue** [comment]
@guidovbrakel , AzureRM* cmdlets are old version of Azure PowerShell. Could you try cmdlets starting with Az. For cmdlets you are using, we need below information for further investigation.
1. Module versions, please run `Get-Module  -ListAvailable` and paste the output 
2. Debug output, set `$DebugPreference='Continue'` before running the repro and paste the resulting debug stream 
3. Error output, please run `Resolve-AzError` and paste the output

**Comment by guidovbrakel** [comment]
Hi, 
I now changed the script to the following:
```
$nics = Get-AzNetworkInterface -ResourceGroupName "***"
Foreach ($nic in $nics) {
    $nic.EnableAcceleratedNetworking = $true
    $nic | Set-AzNetworkInterface
}
```

But then getting errors on a few VM's like this (I checked an Accelerated Networking is supported for these VM sizes)
```
Set-AzNetworkInterface : Cannot add network interface '/subscriptions/id5/resourceGrou
ps/Production/providers/Microsoft.Network/networkInterfaces/servername' with accelerated networking to an existing
virtual machine '/subscriptions/id/resourceGroups/PRODUCTION/providers/Microsoft.Comp
ute/virtualMachines/server name'.
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: CannotAddAcceleratedNetworkingNicToAnExistingVirtualMachine
ErrorMessage: Cannot add network interface '/subscriptions/id/resourceGroups/Producti
on/providers/Microsoft.Network/networkInterfaces/name' with accelerated networking to an existing virtual
machine '/subscriptions/id/resourceGroups/PRODUCTION/providers/Microsoft.Compute/virt
ualMachines/servername'.

At line:3 char:8
+ $nic | Set-AzNetworkInterface
+        ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzNetworkInterface], NetworkCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.SetAzureNetworkInterfaceCommand

```

**Comment by dingmeng-xue** [comment]
Error message already shows that you cannot call Set-AzureRmNetworkInterface again to an existing one.

**Comment by guidovbrakel** [comment]
> Error message already shows that you cannot call Set-AzureRmNetworkInterface again to an existing VM.

Strange, because other VM's in the same resource group are allowing this

**Comment by dingmeng-xue** [comment]
The error code CannotAddAcceleratedNetworkingNicToAnExistingVirtualMachine comes from server. From Azure PowerShell side, we cannot provide you further explanation. Your code is iterating all NetworkInterface and set Accelerated to true. If any one doesn't allow it, whole script will be stopped. If some VMs in your environment allow it and others don't, please share more information. Please compare VMs including original EnableAcceleratedNetworking value.

**Comment by guidovbrakel** [comment]
> The error code CannotAddAcceleratedNetworkingNicToAnExistingVirtualMachine comes from server. From Azure PowerShell side, we cannot provide you further explanation. Your code is iterating all NetworkInterface and set Accelerated to true. If any one doesn't allow it, whole script will be stopped. If some VMs in your environment allow it and others don't, please share more information. Please compare VMs including original EnableAcceleratedNetworking value.

I'm happy to provide more information, but I'm not sure what information is needed?

**Comment by dingmeng-xue** [comment]
In your loop, you can print out VM info and EnableAcceleratedNetworking value of each network interface.

**Comment by guidovbrakel** [comment]
> In your loop, you can print out VM info and EnableAcceleratedNetworking value of each network interface.

How?

**Comment by dingmeng-xue** [comment]
I forward this issue to Network team because no further hint from client side.

**Comment by ramandhillon84** [comment]
Hi @guidovbrakel, VNet is a regional construct and Accelerated Networking is not available in all the hosts in a data center. If your VM lives on a host without AN capability, you won't be able to enable AN on the VM. That is why your script is failing for some VMs, and succeeding for others.

**Comment by liuxiaopiao** [comment]
@ramandhillon84, how can we know if the VM lives on a host without AN capability? Or how can we check the host? Thanks a lot.
