### ISSUE TITLE
Initial support for Azure MySQL DB

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#11034]
## Description

Adding support for Azure MySQL DB
https://docs.microsoft.com/en-us/azure/mysql/

**Comment by dcaro** [comment]
Design review: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/483

**Comment by msJinLei** [comment]
Deisgn review https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues?page=2&q=is%3Aissue+is%3Aopen
PR:
https://github.com/Azure/azure-powershell/pull/11519
https://github.com/Azure/azure-powershell/pull/11536
