### ISSUE TITLE
Get-AzADApplication is not listing Owner of the App registration 

### ISSUE THREAD

**Issue by kgopi05** [Azure/azure-powershell#11044]
Hi, 
I'm able to get the Owner of the App registration in AAD App Registration console , but not able to get owner details in PowerShell or CLI . 

Do any other options to get the details ?

**Comment by dingmeng-xue** [comment]
Current Get-AzADApplication gets data from URL `https://graph.windows.net/<directory_id>/applications/?api-version=1.6&$top=<top>`. Owned application can be get from URL
`https://graph.windows.net/<directory_id>/me/ownedObjects/$/Microsoft.DirectoryServices.Application?api-version=2.0&$top=<top>`. It is not supported.

@kgopi05, owner is not in content of applications URL. Event there is another API to return owner, it has performance concern. Please confirm if you want to show owner name for each app or just show current user owned app.

**Comment by kgopi05** [comment]
Hi, 

I'm able to get the application owner using Get-AzureADApplicationowner , but no cmdlet Get-AzADApplicationOwner . i'm referring 
https://github.com/MicrosoftDocs/feedback/issues/1339
Can we get cmdlet Get-AzADApplicationOwner  ?

**Comment by dingmeng-xue** [comment]
Could you try AzureAd module? More features should be supported by it. https://www.powershellgallery.com/packages/AzureAD

**Comment by dcaro** [comment]
@kgopi05 the new MSGraph module should allow you to do this.
```
$owner = get-mgApplicationOwner -applicationId xxxxx
Get-MgUser -UserId $owner.Id
```
You will need the Microsoft.Graph module (still in preview)
