### ISSUE TITLE
To add in to Azure APIM Apis flag switch option

### ISSUE THREAD

**Issue by aliaksei-babuk** [Azure/azure-powershell#11043]
## Description of the new feature
Adding to the API Management powershell cmdlets option to set the "subscription required" flag for an API.
## Proposed implementation details (optional)
Add into next cmdlet:
Import-AzApiManagementApi
Set-AzApiManagementApi

The same option as in cmdlet:
Set-AzApiManagementProduct

For the parameter "-SubscriptionRequired" add option of setting False value

**Comment by dingmeng-xue** [comment]
@aliaksei-babuk , I didn't get your point. The latest Set-AzApiManagementApi supports SubscriptionRequired flag. Please clarify.

**Comment by aliaksei-babuk** [comment]
@dingmeng-xue Yes, The latest version Set-AzApiManagementApi supports SubscriptionRequired flag. Unfortunately via that flag I can set only true value, false is steel unsupported.

In Set-AzApiManagementProduct, SubscriptionRequired flag suports boolean input 
In Set-AzApiManagementApi , SubscriptionRequired flag is a SwitchParameter

**Comment by dingmeng-xue** [comment]
Thanks. It's a design flaw which needs ApiManagement team to fix it.

**Comment by aliaksei-babuk** [comment]
Thank you

**Comment by deep-mm** [comment]
Any updates on this issue? It is still a SwitchParameter

**Comment by deep-mm** [comment]
> Thanks. It's a design flaw which needs ApiManagement team to fix it.

Any updates on this issue? It is still a SwitchParameter

**Comment by haxxorsid** [comment]
@deep-mm Tries this workaround 
https://github.com/Azure/azure-powershell/issues/9350#issuecomment-502833214

**Comment by deep-mm** [comment]
> @deep-mm try this workaround:
> [#9350 (comment)](https://github.com/Azure/azure-powershell/issues/9350#issuecomment-502833214)
> If this is what you want to do in your case.
> 
> cc: @solankisamir

Yeah that works @haxxorsid
Thanks for the help :)
