### ISSUE TITLE
macOS - Login-AzAccount : No certificate was found in the certificate store with thumbprint

### ISSUE THREAD

**Issue by johnmccrae** [Azure/azure-powershell#11046]
# Steps to reproduce

```powershell

	$pfxpassword = 'foo'
	$CertificatePath = "~/.bin/mypfx.json"
$SecurePassword = $pfxpassword | ConvertTo-SecureString -AsPlainText -Force;

	$certificateObject = Get-PfxCertificate -FilePath $CertificatePath -Password $SecurePassword

	Login-AzAccount -TenantId $Tenant -ServicePrincipal -CertificateThumbprint $certificateObject.Thumbprint -ApplicationId $Appid


```

# Expected behavior

```none
Certificate loads with the appropriate enhanced key usage list
Proper logon to Azure ensues

```

# Actual behavior

```none

Login-AzAccount : No certificate was found in the certificate store with thumbprint <my thumbprint goes here>

This exact code works on Windows. Interesting that on OSX the EnhancedKeyUsageList field is not populated. On Windows it displays correctly as {Client Authentication, Server Authentication}

This repro's on PS6 and PS7 on macOS

```

# Environment data

```none

##PS6
Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

##PS7-RC1
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.1
PSEdition                      Core
GitCommitId                    7.0.0-rc.1
OS                             Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

##PS7-RC2
Name                           Value
----                           -----
PSVersion                      7.0.0-rc.2
PSEdition                      Core
GitCommitId                    7.0.0-rc.2
OS                             Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

**Comment by dingmeng-xue** [comment]
Azure PowerShell doesn't have cmdlet `Login-AzAccount`. Could you check which module it belongs to?

**Comment by johnmccrae** [comment]
¥ DESKTOP-KTGT738 {C:\Users\me} get-command login-azaccount

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           Login-AzAccount                                    1.6.3      Az.Accounts

**Comment by johnmccrae** [comment]
Here's where I started with this bug - https://github.com/PowerShell/PowerShell/issues/11785 - they sent me here to you all.

**Comment by dingmeng-xue** [comment]
My fault. You are right and we will investigate it.

**Comment by wyunchi-ms** [comment]
Hi @johnmccrae , thanks for your feedback! Could you please check that whether the `$certificateObject` is the same on both MacOS and windows? If it's same on both platform this will be a bug of Azure PowerShell or it may be a issue of PowerShell.

**Comment by johnmccrae** [comment]
It is not the same. When I dump the cert object on OSX, the EnhancedKeyUsageList is empty. On Windows, it displays '{Client Authentication, Server Authentication}'

**Comment by johnmccrae** [comment]
Anything new I can post to help with this one?

**Comment by dingmeng-xue** [comment]
> PowerShell/PowerShell#11785

My feeling is the issue is related to Get-PfxCertificate if object is already different between Windows and MacOS. How did you create the certificate and export it into json?

**Comment by johnmccrae** [comment]
Sorry about that. Here's how I am creating the cert. I am making it on a Windows node and then storing it on my mac. 
    $thumb = (New-SelfSignedCertificate -CertStoreLocation cert:\localmachine\my -DnsName $NewDNSName -KeyExportPolicy Exportable -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider" -NotAfter $notAfter).Thumbprint

**Comment by dingmeng-xue** [comment]
If so, this issue needs we check with ADAL owner if required. Could you try if it (creation and storing) works on Windows? If addition, could you share your certificate to us?

**Comment by johnmccrae** [comment]
It does work on Windows. I started my testing there. Happy to share the cert with you. Attached. 
[20200131pfxfile.json.txt](https://github.com/Azure/azure-powershell/files/4278152/20200131pfxfile.json.txt)

**Comment by johnmccrae** [comment]
Any updates on this?

**Comment by dingmeng-xue** [comment]
@johnmccrae , sorry for the late response. Could you share me the password for your cert? What's the format of it? it seems in json according to name but it's not.

**Comment by johnmccrae** [comment]
Here's the code I use to create the cert with. Password is attached.

`    
$currentDate = Get-Date
$endDate = $currentDate.AddYears(1)
$notAfter = $endDate.AddYears(1)
$pwd = ConvertTo-SecureString -String $NewCertPassword -Force -AsPlainText
$pfxFilePath = "c:\bin\$(Get-Date -Format yyyyMMdd)pfxfile.json"
$thumb = (New-SelfSignedCertificate -CertStoreLocation cert:\localmachine\my -DnsName $NewDNSName -KeyExportPolicy Exportable -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider" -NotAfter $notAfter).Thumbprint

[pw.txt](https://github.com/Azure/azure-powershell/files/4370600/pw.txt)
Export-PfxCertificate -cert "cert:\localmachine\my\$thumb" -FilePath $pfxFilePath -Password $pwd`

**Comment by dingmeng-xue** [comment]
Hi John,

I can reproduce your issue now. The error message hints there is no certificate in store. You need to import pfx into your keychain. But I didn’t figure out how to import certificate in your format on Macos. It’s out of Azure PowerShell’s scope.

Thanks,
Dingmeng

**Comment by johnmccrae** [comment]
Trying that now. I also reverted to just basic PFX format and not JSON for the cert.

**Comment by dingmeng-xue** [comment]
@johnmccrae, do you have any update?

**Comment by johnmccrae** [comment]
Ok, I think you can close this. It appears that it was related to not being properly installed in keychain. We're all good. Thanks!
