### ISSUE TITLE
Get-AzApiManagement returns 0 results 

### ISSUE THREAD

**Issue by ztbrumbaugh** [Azure/azure-powershell#11059]
## Description
Running Get-AzApiManagement returns 0 results without an error. Initially I tried passing the ResourceGroupName argument which also returned 0 results.

## Steps to reproduce

```powershell
Get-AzApiManagement
```

## Environment data

![image](https://user-images.githubusercontent.com/39955140/74063057-ad198980-49bd-11ea-9b89-c7755fa52fd8.png)

## Module versions
az 3.4.0

![image](https://user-images.githubusercontent.com/39955140/74063115-c6bad100-49bd-11ea-9863-9580047f0ab5.png)

## Debug output

Body:
{
  "value": []
}

DEBUG: AzureQoSEvent: CommandName - Get-AzApiManagement; IsSuccess - True; Duration - 00:00:01.0536195; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 3:24:35 PM - GetAzureApiManagement end processing.
DEBUG: 3:24:35 PM - GetAzureApiManagement end processing.

## Error output

There is no error in the terminal, 0 results are returned when expected.

**Comment by dingmeng-xue** [comment]
You need to create api management and then Get-AzApiManagement can return the result. Please check.

**Comment by ztbrumbaugh** [comment]
Api Management had already been created, and the Get-AzApiManagement command was working on 2/6/2020. However, it does look like whatever was wrong under the hood has been resolved, as I'm now getting results. This can be closed. Thanks!
