### ISSUE TITLE
New-AutoscaleProfile creates a TimeWindow even though StartTimeWindow and EndTimeWindow is omitted

### ISSUE THREAD

**Issue by AWahlqvist** [Azure/azure-powershell#1107]
When creating a new autoscale profile, the object returned contains a Microsoft.Azure.Management.Insights.Models.TimeWindow-object in the property "FixedDate" even though no date was specified using the parameters. Start/End get's set to "0001-01-01 00:00:00".

You can set it to null before writing it back with Add-AutoscaleSetting though using: 
$AutoScaleProfile.FixedDate = $null

So there is a workaround for this issue. If you don't clear it, the autoscale profile will look broken in the portal (and in PowerShell). Tested on the preview version 0.10.0.

**Comment by asheniam** [comment]
Please try with the latest Get-AzureRmAutoscaleSetting
