### ISSUE TITLE
Clarification with regard to the -Location switch on all Az* cmdlets ...

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-powershell#11073]
## Suggestion:

A number of Az* cmdlets accept a -Location parameter, whose value is an Azure location name. 
 However, when one issues the following command:

Get-AzureLocation | Format-Table

```
DisplayName          Name        
-----------          ----        
East US              East US
West US              West US
...
```

A **DisplayName** and **Name** is returned.   Someone new to the platform (myself) will ask:

Which location name should be used - DisplayName or Name?

This is not an unreasonable ask -- as I believe in the not too distant past, DisplayName and Name could have different values -- although (at present) the list seems to have been normalized so that both properties contain the same value; so it doesn't matter which one is used.

However, I have noticed that references are made to different names, as shown in the following document (note the region names do not contain spaces, for example: "westus", "australiaeast" and "westeurope").

[https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-regions](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-regions)

## Proposed implementation details (optional)

For the -Location parameter, please include verbiage such as:

> Specifies the location for which this cmdlet gets the available virtual machine sizes.  To get the available location names, use: Get-AzureLocation | Select DisplayName   ... or ...  Get-AzureLocation | Select Name

... whichever of the above is correct (or both)? 

Thanks in advance.

**Comment by wyunchi-ms** [comment]
Hi @bdcoder2, thanks a lot for your feedback! As `Get-AzureLocation` is the cmdlet in`AzureRm` module which is only little maintain now. Could you please migrate to `Az` module? And the right usage of location is use the name without spaces. such as: `eastasia`, `southeastasia` and `centralus`. Here is a example of `Get-AzLocation`

```powershell
Get-AzLocation | Format-Table
Location           DisplayName          Providers
--------           -----------          ---------
eastasia           East Asia            {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
southeastasia      Southeast Asia       {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
centralus          Central US           {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
eastus             East US              {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
eastus2            East US 2            {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
westus             West US              {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
northcentralus     North Central US     {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
southcentralus     South Central US     {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
northeurope        North Europe         {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
westeurope         West Europe          {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
japanwest          Japan West           {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
japaneast          Japan East           {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
brazilsouth        Brazil South         {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
australiaeast      Australia East       {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
australiasoutheast Australia Southeast  {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
southindia         South India          {Microsoft.Security, Microsoft.Compute, Microsoft.DevTestLab, Microsoft.Storage…}
```

**Comment by bdcoder2** [comment]
@wyunchi-ms - Thanks! -- strange I am using Az module 3.4.0 and the Get-AzureLocation cmdlet is still available.

I would still add the following to the documentation / description with regard to the -Location parameter:

> To see a list of Azure locations, use:
>   Get-AzLocation | Format-Table
> 
>  To select a location name interactively, use:
>   $location = Get-AzLocation | Out-GridView -PassThru -Title "Choose a Location"
>   $use_location = $location.Location

Thanks again!
