### ISSUE TITLE
Bad request error when trying to create Azure subscriptions programmatically in Powershell using new-azsubcription

### ISSUE THREAD

**Issue by sumitraj0103** [Azure/azure-powershell#11075]
I'm logged into Azure as a ea account owner, and I wish to programmatically create a number of subscriptions, with the same configuration, however when I run the command below I receive a 'BadRequest' error.

Error Detail:

New-AzSubscription : Operation returned an invalid status code 'BadRequest'
At line:1 char:1
+ New-AzSubscription -EnrollmentAccountObjectId

**Comment by wyunchi-ms** [comment]
Hi @sumitraj0103, thanks for your feedback. Could you please offer us more info about your issue? You can get your installed module info with:
```powershell
gmo -l
```
And show us your script code will also help.

**Comment by dingmeng-xue** [comment]
@sumitraj0103, could you share the log? the log will help us to triage the issue.

**Comment by dingmeng-xue** [comment]
@sumitraj0103 , thanks for your reporting. We will close this issue due to inactivity. If you meet the same issue, please raise a new issue with debug messages. Thanks.

**Comment by horstwutscher** [comment]
Hello,
I also get the same error.
Maybe someone has a solution for me or help me to fix the problem.
We have created five subscriptions manually.
Thanks,
Horst
