### ISSUE TITLE
Get-AzLog should be renamed

### ISSUE THREAD

**Issue by theheatDK** [Azure/azure-powershell#11087]
## Description
Hi,
Get-AzLog returns Activity Log, but it is a bit difficult to discern this from the name of the cmdlet.
In the Portal it is called Activity Log and the CLI uses "az monitor activity-log".
Maybe it would be better to call it Get-AzActivityLog?
Maybe we could create an alias?
Regards Peter 

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by VeryEarly** [comment]
Thanks for you suggestion, will discuss with service team see what we can do.

**Comment by wyunchi-ms** [comment]
Hi @theheatDK, thanks a lot for your feedback! This is a good suggestion, we will consider it.

**Comment by VeryEarly** [comment]
will be released in 2020-05-18
