### ISSUE TITLE
[KeyVault] Add Support for Private Link for Key Vault

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#11096]
## Description of the new feature
Add support for private link for KeyVault

Relevant Swagger change is [Azure/azure-rest-api-specs#7631](https://github.com/Azure/azure-rest-api-specs/pull/7631)

## Proposed implementation details (optional)
(Updated 4/8/2020)

- PowerShell will centralize all private link relating cmdlets in Az.Network module
- These cmdlets are generic, not reousrce-type-specific
- Scenario tests will be in each modules
- The approve operation will be designed as `Approve-AzPrivateEndpointConnection`

## More info
- The top level resource of keyvault is "vaults"
- We'll use API version `2018-02-14`

**Comment by isra-fel** [comment]
An open question / decision to make:

Do we want to design the approve/reject private endpoint connection as
1. commands, e.g. `Approve-AzKeyVaultPrivateEndpointConnection`
1. parameter in `Update-*` command, e.g. `Update-AzKeyVaultPrivateEndpointConnection -Approved $True`

Cli had same discussion here: https://github.com/Azure/azure-cli/pull/12073/files/b2d332d4e2320afd4d8bb717a4a530245f8f5f2a#r377498807

**Comment by bim-msft** [comment]
> An open question / decision to make:
> 
> Do we want to design the approve/reject private endpoint connection as
> 
> 1. commands, e.g. `Approve-AzKeyVaultPrivateEndpointConnection`
> 2. parameter in `Update-*` command, e.g. `Update-AzKeyVaultPrivateEndpointConnection -Approved $True`
> 
> Cli had same discussion here: https://github.com/Azure/azure-cli/pull/12073/files/b2d332d4e2320afd4d8bb717a4a530245f8f5f2a#r377498807
> 
> Cli PR: [Azure/azure-cli/pull/12073](https://github.com/Azure/azure-cli/pull/12073)
> They used commands, but it was not under fully discussion

@isra-fel Hi, we plan to send out an email involving you guys and Key Vault team to further discuss this open question.
