### ISSUE TITLE
Mixed-case storage accounts can be created with VM template

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-powershell#1109]
Hi,

I think I found a bug in template deployment.  

Steps:
1.  Create a deployment template for a VM
2.  Set the New Storage Account name parameter to something with mixed case like MyIllegalName123
3.  Deploy template 

Result: storage account is created with an illegal mixed-case name (portal only allows lower-case)

Expected: name is converted to lower case or deployment fails

**Comment by huangpf** [comment]
@BurtBiel Could you please share the template with us so that we can reproduce?

+ @singhkay

**Comment by blueww** [comment]
As there are no responds for this issue for > 8 months, close the issue.
Feel free to reactive it if any thing need follow up.
