### ISSUE TITLE
Cannot find subscription after `Enable-AzContextAutoSave`

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#11098]
## Description

Repro:
1. Clear everything
1. `Disable-AzContextAutoSave`
1. `Connect-AzAccount`
1. `Enable-AzContextAutoSave`
1. `Get-AzVm`

Root cause might be that token cache is not migrated from in-memory to disk.
https://github.com/Azure/azure-powershell/blob/0a8e7d29344f11835b038e20be332f4fd0e407f4/src/Accounts/Accounts/AutoSave/EnableAzureRmContextAutosave.cs#L111

**Comment by dingmeng-xue** [comment]
Fixed in MSAL preview release

**Comment by isra-fel** [comment]
Fixed by #11113
