### ISSUE TITLE
Remove policy from policy set

### ISSUE THREAD

**Issue by Isotop7** [Azure/azure-powershell#11095]
## Ability to remove policy from policy set

In order to update a `policy`, I have to delete it first. In order to delete it, I must remove it from every `policySet` it is used in. Right now this is not possible. `Get-AzPolicySetDefinition` returns an object with the assigned policies in `$_.properties.policyDefinitions`. Sadly, I did not find a way to edit this property list to simply remove one of the entries there. I could recreate the `policySet` but this would mean to 

* first get the assignments of it, store them
* get the list of polices in the policy set, store them
* remove all assignments of the `policySet`
* delete it
* recreate it without the policy I want to update
* redo the assignments of the `policySet`

This seems to be a total overkill and a runtime nightmare.

## Proposed implementation details (optional)

Implement something like `Get-AzPolicySetPolicyDefinitions` and `Get-AzPolicySetPolicyDefinitions` to update the list of policies bundled in a `policySet` without the need to delete all assigments and the `policySet` first.

**Comment by dingmeng-xue** [comment]
This feature request needs Policy team to review it.

**Comment by kenieva** [comment]
Thanks for the feedback. We are updating the create and edit initiative experience which will allow for this sort of action. We hope to release more details in Summer 2020.

**Comment by Isotop7** [comment]
Hi @kenieva,

is there are workaround until summer?

**Comment by kenieva** [comment]
The only way would be the one described below. You should duplicate the initiative assignment by making a new one with the modifications taken into account.
