### ISSUE TITLE
Export-AzAutomationRunbook  Adding extra '\' to file names. 

### ISSUE THREAD

**Issue by AndreasMWalter** [Azure/azure-powershell#11101]
## Description
I am currently running into an issue using a PowerShell script on the ubuntu18.04 worker in Azure DevOps. 

This issue was reported as fixed in #6999 

## Steps to reproduce
You need a runbook that you want to export from any automation account 

```powershell
$Runbook = Get-AzAutomationRunbook -ResourceGroupName $ResourceGroup -AutomationAccountName $AutomationAccountName
$TemporaryFolder = $env:SYSTEM_DEFAULTWORKINGDIRECTORY + '/temp/'
$Runbook | Export-AzAutomationRunbook -OutputFolder $TemporaryFolder -Force 
```

## Environment data

```
Key   : PSVersion
Value : 6.2.4
Name  : PSVersion


Key   : PSEdition
Value : Core
Name  : PSEdition


Key   : GitCommitId
Value : 6.2.4
Name  : GitCommitId


Key   : OS
Value : Linux 5.0.0-1028-azure #30~18.04.1-Ubuntu SMP Fri Dec 6 11:47:59 UTC 
        2019
Name  : OS


Key   : Platform
Value : Unix
Name  : Platform


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0…}
Name  : PSCompatibleVersions


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

```

## Module versions
I have reduced the Module output to the Az.Automation module, rest can be found on the worker see above
```powershell

Name              : Az.Automation
Path              : /usr/share/az_3.1.0/Az.Automation/1.3.4/Az.Automation.psd1
Description       : Microsoft Azure PowerShell - Automation service cmdlets 
                    for Azure Resource Manager in Windows PowerShell and 
                    PowerShell Core.
                    
                    For more information on Automation, please visit the 
                    following: https://docs.microsoft.com/azure/automation/
Guid              : ef36c942-4a71-4e19-9450-05a35843deb6
Version           : 1.3.4
ModuleBase        : /usr/share/az_3.1.0/Az.Automation/1.3.4
ModuleType        : Script
PrivateData       : {PSData}
AccessMode        : ReadWrite
ExportedAliases   : {[Import-AzAutomationModule, Import-AzAutomationModule]}
ExportedCmdlets   : {[Get-AzAutomationHybridWorkerGroup, 
                    Get-AzAutomationHybridWorkerGroup], 
                    [Remove-AzAutomationHybridWorkerGroup, 
                    Remove-AzAutomationHybridWorkerGroup], 
                    [Get-AzAutomationJobOutputRecord, 
                    Get-AzAutomationJobOutputRecord], 
                    [Import-AzAutomationDscNodeConfiguration, 
                    Import-AzAutomationDscNodeConfiguration]…}
ExportedFunctions : {}
ExportedVariables : {}
NestedModules     : {}


```

## Debug output
-

## Error output

![image](https://user-images.githubusercontent.com/38529659/74251109-ef0f3c00-4ceb-11ea-80a2-361752640375.png)

**Comment by dingmeng-xue** [comment]
@andreasMWalter, I didn't get the meaning of the last snapshot. What's the output folder resolved by cmdlet?

**Comment by AndreasMWalter** [comment]
Dear @dingmeng-xue 
The screenshot depicts the filename of the Runbook within the output folder, note the backslash at the front of the filename.
Needless to say, there should not be a backslash. 
The outputfolder is: 
$TemporaryFolder = $env:SYSTEM_DEFAULTWORKINGDIRECTORY + '/temp/' 
The filename **is**:
'\Invoke-RunbookName.ps1'

The filename **should be**:
'Invoke-RunbookName.ps1'

Now I have been experimenting with this yesterday and there have been several interesting results:

My Original Call was (without changing the script from Windows File references):
```powershell
Export-AzAutomationRunbook -OutputFolder .\temp
```
Since I was in the working directory, the expected behaviour of above call was:
Place the exported runbook here:
$env:SYSTEM_DEFAULTWORKINGDIRECTORY\temp\Invoke-Runbook.ps1

Now this was not what happened, however for some reason the runbook was placed here:

$env:SYSTEM_DEFAULTWORKINGDIRECTORY\temp\'temp\Invoke-Runbook.ps1'

However 'temp\Invoke-Runbook.ps1' being the filename of the runbook for some odd reason.
![image](https://user-images.githubusercontent.com/38529659/74326543-dd30a600-4d8a-11ea-9ff4-081b01636a1a.png)

So I did some troubleshooting of the pipeline and made sure that the path were all Linux paths etc. and I reference environment variables where I could and the result was that the Export-AzAutomationRunbook cmdlet adds a '\' at the beginning of the runbook name, as depicted in my earlier screenshot and reported in the issue #6999 .

**Comment by dingmeng-xue** [comment]
Automation team, please check if file path should be resolved according to common ResolveUserPath api.
https://github.com/Azure/azure-powershell/blob/dd246c84bb5b18b297dadb7a0704c863801afb02/src/Automation/Automation/Common/AutomationPSClient.cs#L1902

**Comment by vikram-m** [comment]
This is triaged and currently in the backlog, will consider it if resourcing allows.

**Comment by vikram-m** [comment]
Unfortunately because of other priorities we were not able to pick this up, please expect an update in Q4CY20.

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.

**Comment by achaika80** [comment]
I'm experiencing this Issue as well on MacOS Catalina 10.16.7
PowerShell 7.1
Az.Automation 1.4.0

**Comment by KranthiPakala-MSFT** [comment]
@vikram-m Following up to see if there is any update on this issue? - Thank you

**Comment by navba-MSFT** [comment]
@AndreasMWalter Apologies for the delay in response. This github thread has been open for quite sometime now. I just wanted to check if you still need assistance on this issue. Awaiting your reply.

@vikram-m Could you please update us regarding the status of the fix ?

**Comment by navba-MSFT** [comment]
I am following up with the Engineering team regarding the fix. This thread will be updated once we have more details.

**Comment by Jassingh819** [comment]
Closed with above PR.
