### ISSUE TITLE
PowerState and ProvisionStatus

### ISSUE THREAD

**Issue by Bravecold** [Azure/azure-powershell#11106]

**Comment by wyunchi-ms** [comment]
Hi @Bravecold , thanks for your feedback. But I cannot understand your point clearly. Could you please give us a more detail scenario? Such as:
```powershell
Stop-AzVM -ResourceGroupName "ResourceGroup11" -Name "VirtualMachine07"
Get-AzVM -ResourceGroupName "ResourceGroup11" -Name "VirtualMachine07" -Status
```

**Comment by dingmeng-xue** [comment]
Forward it to Compute team.

**Comment by Drewm3** [comment]
@Bravecold, I think you are looking for something like the following which will show a list of all deallocated VMs during the timeframe specified. Please let me know if you are looking for something different from this:

```powershell
Get-AzLog -StartTime 2020-02-13T17:00 -EndTime 2020-02-13T18:00 | where {$_.Authorization.Action -lie "*deallocate*"}
```

**Comment by Drewm3** [comment]
I am going to close this one now assuming that my previous response meets the need.
