### ISSUE TITLE
Set-AzStorageSyncServerEndpoint  There is no way to turn off OfflineDataTransfer

### ISSUE THREAD

**Issue by GregDSmith** [Azure/azure-powershell#11127]
Because the OfflineDataTransfer parameter is of type SwitchParameter there is no way to turn off Offline Data Transfer. The code also does not even check the parameter if it is not passed in.

**Comment by wyunchi-ms** [comment]
Hi @GregDSmith , thanks for your feedback! Forwarding this issue to `StorageSync` team.

**Comment by ankushbindlish2** [comment]
OfflineDataTransfer is an optional SwitchParameter

**Option 1 :** -OfflineDataTransfer :$false  
**Option 2 :** Do not provide OfflineDataTransfer switch, Default is false.

We use SwitchParameter ToBool functionality : https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.switchparameter.tobool?view=powershellsdk-7.0.0

Please feel free to reopen this issue if required.
