### ISSUE TITLE
Get-AzConsumptionUsageDetail - Operation returned an invalid status code 'BadGateway'

### ISSUE THREAD

**Issue by Evogelpohl** [Azure/azure-powershell#11129]
Az.Billing Version 1.0.2 
PowerShell (Tried on vers 5.x, Linux/6.2.4 and 7-rc)
Run Connect-AzAccount (as user w/ owner rights to sub)
--OK
Run Get-AzConsumptionUsageDetail -Top 10
--Returns: Operation returned an invalid status code 'BadGateway'

Try: az consumption usage list. Get max retries error.

Appears the Management Consumption API is down.

**Comment by dingmeng-xue** [comment]
@Evogelpohl, Please enable debug using `$DebugPreference = "Continue"` and then share debug log to us.

**Comment by Evogelpohl** [comment]
Here's the PS script-block I'm using to loop thru all the subs to which I have effective Billing-Reader rights:

$x = Get-AzContext -ListAvailable
foreach ($i in $x) {
    $i | Set-AzContext
    Get-AzConsumptionUsageDetail -Top 3
}

My login has: Role=Owner, Billing Reader, Contributor. The Billing Reader is the built-in role, no changes. I can see all Cost Analysis (usage, forecast, etc) information from the Portal. I just verified using Get-AzRoleAssignments for each context.  This worked fine up to Feb 12th '20 when my Azure automation script stopped producing a billing-extract file.

> Debug:
> DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadGateway

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
session-id                    : e1a997a1-d95c-45ee-89d0-c7a5701db40b
x-ms-request-id               : 18df8a39-1508-44c3-a984-0b4d04ccb693
x-ms-correlation-request-id   : 730de3fa-1a74-45d7-baa0-a3d0fce2fcb4
x-ms-client-request-id        : a3996c91-a3ea-490e-ab0e-3f91d8c2f44f
OData-Version                 : 4.0
Access-Control-Allow-Origin   : *
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11992
x-ms-failure-cause            : gateway
x-ms-routing-request-id       : NORTHCENTRALUS:20200217T145835Z:730de3fa-1a74-45d7-baa0-a3d0fce2fcb4
Date                          : Mon, 17 Feb 2020 14:58:35 GMT
Connection                    : close

Body:
{
  "error": {
    "code": "403",
    "message": "User does not have required permissions to view usage details for Billing Account: 0306cb34-xxxxxxxxx-xxxxxxx-0cc6c24dd240. (Request ID: 18df8a39-1508-44c3-a984-0b4d04ccb693)"
  }
}


Get-AzConsumptionUsageDetail : Operation returned an invalid status code 'BadGateway'
At line:6 char:5
+     Get-AzConsumptionUsageDetail -Top 3
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzConsumptionUsageDetail], ErrorResponseException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Consumption.Cmdlets.UsageDetails.GetAzureRmConsumptionUsageDetail
 
DEBUG: AzureQoSEvent: CommandName - Get-AzConsumptionUsageDetail; IsSuccess - False; Duration - 00:00:25.5434817; Exception - Microsoft.Azure.Management.Consumption.Models.ErrorResponseException: Operation returned an invalid status code 'BadGateway'
   at Microsoft.Azure.Management.Consumption.UsageDetailsOperations.ListWithHttpMessagesAsync(String expand, String filter, String skiptoken, Nullable`1 top, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Consumption.UsageDetailsOperationsExtensions.ListAsync(IUsageDetailsOperations operations, String expand, String filter, String skiptoken, Nullable`1 top, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Consumption.UsageDetailsOperationsExtensions.List(IUsageDetailsOperations operations, String expand, String filter, String skiptoken, Nullable`1 top)
   at Microsoft.Azure.Commands.Consumption.Cmdlets.UsageDetails.GetAzureRmConsumptionUsageDetail.ExecuteCmdlet();
DEBUG: Finish sending metric.
DEBUG: 9:58:36 AM - GetAzureRmConsumptionUsageDetail end processing.
DEBUG: 9:58:36 AM - GetAzureRmConsumptionUsageDetail end processing.

**Comment by dingmeng-xue** [comment]
Service team, please check what permission is required.

**Comment by sanjeevdhavala** [comment]
Facing same issue, it worked until 06/12/2020 and it started failing from 06/13/2020

"User does not have required permissions to view usage details for Billing Account"

**Comment by Evogelpohl** [comment]
Follow up from my original issue: We opened a ticket w/ MS. Got this response. 

"**Symptom**: When you used Get-AzConsumptionUsageDetail the operation returned an invalid status code 'BadGateway'.
**Cause**:  The reporting APIs are currently restricted to accounts with enterprise agreements"

This wasn't well-documented at the time the API stopped working for me, ~feb 2020.
