### ISSUE TITLE
Set-AzJitNetworkAccessPolicy : Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.

### ISSUE THREAD

**Issue by KLReid12** [Azure/azure-powershell#11135]
![image](https://user-images.githubusercontent.com/60779808/74773581-220f7d80-5260-11ea-90ed-3b11750de80b.png)

**Comment by wyunchi-ms** [comment]
Hi @KLReid12 , thanks a lot for your feedback! I'm forwarding this issue to Network team. Could you tell us where the snapshoot come from? Does it come from a Azure .Net issue or other place? This will help us. Thanks a lot!

**Comment by KLReid12** [comment]
@wyunchi-ms This came from an Azure Market Place image : WindowsServer.2016-Datacenter.2016.127.20180613

**Comment by KarenHammons** [comment]
@wyunchi-ms think this is a SDK issue; please investigate further.

**Comment by KLReid12** [comment]
@wyunchi-ms Is there any update concerning this request?

**Comment by KLReid12** [comment]
@wyunchi-ms Is there something else needed from me to get further assistance concerning this request?

**Comment by KLReid12** [comment]
Is there any update concerning this issue?

**Comment by dingmeng-xue** [comment]
@KLReid12 , could you share details of CloudException? You get it after `$DebugPreference="Continue"`.

For your information, SDK code was generated according to API. For this case, REST API shows HTTP 200 is only one correct response. https://github.com/Azure/azure-rest-api-specs/blob/2f85572ebdd63fac3bd1ae17d237ef86094667fe/specification/security/resource-manager/Microsoft.Security/preview/2015-06-01-preview/jitNetworkAccessPolicies.json#L283

**Comment by chlahav** [comment]
hi @KLReid12 
this issue was fixed recently
can you please update the PS module and verify that it was fixed for you?
