### ISSUE TITLE
Error while assigning Application Security Group to VMSS

### ISSUE THREAD

**Issue by bgawale** [Azure/azure-powershell#11131]
## Description

Based on this [announcement](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-networking#nsg--asgs-per-scale-set) you can now enable the application security groups for Azure VMSS and hence was trying to do it using Az PS.

## Steps to reproduce
Get instance of Azure VMSS
```powershell
$ssvms = Get-AzVmssVM -VMScaleSetName 'vmss_name' -ResourceGroupName 'rg_name'
```
Get instance of application security group
```powershell
$asg = Get-AzApplicationSecurityGroup -Name 'web-nsg' -ResourceGroupName 'rg_name'
```
Get NIC
```powershell
$nic = $vmss.VirtualMachineProfile.NetworkProfile.NetworkInterfaceConfigurations[0]
```
Associate the ASG with NIC Ip configuration
```powershell
$nic.IpConfigurations[0].ApplicationSecurityGroups = $asg
```

Returns the error below
Exception setting "ApplicationSecurityGroups": "Cannot convert the "Microsoft.Azure.Commands.Network.Models.PSApplicationSecurityGroup" value of type "Microsoft.Azure.Commands.Network.Models.PSApplicationSecurityGroup" to type
"System.Collections.Generic.IList`1[Microsoft.Azure.Management.Compute.Models.SubResource]"."
## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.9.1      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}
```

## Debug output

```
Exception setting "ApplicationSecurityGroups": "Cannot convert the "Microsoft.Azure.Commands.Network.Models.PSApplicationSecurityGroup" value of type "Microsoft.Azure.Commands.Network.Models.PSApplicationSecurityGroup" to type
"System.Collections.Generic.IList`1[Microsoft.Azure.Management.Compute.Models.SubResource]"."
At line:1 char:1
+ $nic.IpConfigurations[0].ApplicationSecurityGroups = $asg
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
```

## Error output

```
Message        : Exception setting "ApplicationSecurityGroups": "Cannot convert the "Microsoft.Azure.Commands.Network.Models.PSApplicationSecurityGroup" value of type "Microsoft.Azure.Commands.Network.Models.PSApplicationSecurityGroup"
                 to type "System.Collections.Generic.IList`1[Microsoft.Azure.Management.Compute.Models.SubResource]"."
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
                    at CallSite.Target(Closure , CallSite , Object , Object )
                    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
                    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.SetValueInvocationException
InvocationInfo : {}
Line           : $nic.IpConfigurations[0].ApplicationSecurityGroups = $asg
Position       : At line:1 char:1
                 + $nic.IpConfigurations[0].ApplicationSecurityGroups = $asg
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : Cannot convert the "Microsoft.Azure.Commands.Network.Models.PSApplicationSecurityGroup" value of type "Microsoft.Azure.Commands.Network.Models.PSApplicationSecurityGroup" to type
                 "System.Collections.Generic.IList`1[Microsoft.Azure.Management.Compute.Models.SubResource]".
StackTrace     :    at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
                    at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
                    at CallSite.Target(Closure , CallSite , Object , Object )
Exception      : System.Management.Automation.PSInvalidCastException
InvocationInfo : {}
Line           : $nic.IpConfigurations[0].ApplicationSecurityGroups = $asg
Position       : At line:1 char:1
                 + $nic.IpConfigurations[0].ApplicationSecurityGroups = $asg
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dingmeng-xue** [comment]
Compute team, please help to look into this issue.

**Comment by Drewm3** [comment]
@bgawale, to apply an ASG to a ScaleSet you need to first update the NetworkProfile for the ScaleSet model and then apply the updated model to existing instances and/or deploy new instances which will use the model automatically.

We do not currently support updating the NIC of an existing VMSS instance.

**Comment by bgawale** [comment]
@Drewm3 what do you mean by updating network profile to scale set model? Shouldn't it be defaulting to the same when it gets provisioned along with the scale set?

**Comment by Drewm3** [comment]
The NIC configuration of a VMSS instance cannot be modified directly which is what you were attempting to do above in this line:

`$nic.IpConfigurations[0].ApplicationSecurityGroups = $asg`

Instead you need to modify the configuration for the VM Scale Set and then apply the updated configuration of the scale set to an existing instance or increase the number of VMs in the scale set to deploy a new instance. New instances will take the updated configuration from the VMSS model.

**Comment by bgawale** [comment]
know any reference documentation or relevant snippet to do it?

**Comment by Drewm3** [comment]
Here is an example of adding an ASG to the configuration (aka model) of the Scale Set, and then applying the updated configuration to instance ID 1:

`$vmss_name = "myVMSS"
$rg_name = "myRG"
$web_nsg = "myASG"

# Get the Scale Set to be updated
$ssvms = Get-AzVmss -VMScaleSetName $vmss_name -ResourceGroupName $rg_name

# Get the ASG to add to the Scale Set
$asg = Get-AzApplicationSecurityGroup -Name $web_nsg -ResourceGroupName $rg_name

# Create an new object if the ASG is initially NULL
$ssvms.VirtualMachineProfile.NetworkProfile.NetworkInterfaceConfigurations[0].IpConfigurations[0].ApplicationSecurityGroups = New-Object System.Collections.Generic.List[Microsoft.Azure.Management.Compute.Models.SubResource]

# Add the ASG to the VMSS configuration
$ssvms.VirtualMachineProfile.NetworkProfile.NetworkInterfaceConfigurations[0].IpConfigurations[0].ApplicationSecurityGroups.Add($asg.id)

# Push the updated configuration to Azure
Update-AzVmss -ResourceGroupName $rg_name -VMScaleSetName $vmss_name -VirtualMachineScaleSet $ssvms

# Update the instance that you want to change
Update-AzVmssInstance -ResourceGroupName $rg_name -VMScaleSetName $vmss_name -InstanceId 1`

Let me know if this answers your question.

**Comment by Drewm3** [comment]
Please let me know if the previous answer does not answer the issue.
