### ISSUE TITLE
Import-AzBlueprintWithArtifact -IncludeSubFolders only recognizes one artifact when files have common identical names

### ISSUE THREAD

**Issue by alex-frankel** [Azure/azure-powershell#11146]
## Description

If I create a folder structure such as this, where two artifact files have the same name, only one artifact is registered.

artifacts
|_ artifact1/artifact.json
|_ artifact2/artifact.json

## Environment data

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

## Module versions

0.2.10               Az.Blueprint                        PSGallery

**Comment by wyunchi-ms** [comment]
Hi @alex-frankel thanks for your feedback! We are forwarding this issue to `Blueprint` team.

**Comment by apclouds** [comment]
Hi @alex-frankel any update on this issue?
