### ISSUE TITLE
Doc change request or Update-AzVmss . Current documentation is confusing.

### ISSUE THREAD

**Issue by RishiMaini** [Azure/azure-powershell#11163]
Can we please put a note in  [Update-AzVmss](https://docs.microsoft.com/en-us/powershell/module/az.compute/update-azvmss?view=azps-3.5.0)  and refer [this ](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-upgrade-scale-set#properties-with-restrictions-on-modification) which defines what properties are "Create time" properties and thus can’t be modified/updated after VMSS is deployed.

Example , we can’t change OS Disk account type since it’s a create time property but current doc ([Update-AzVmss)](https://docs.microsoft.com/en-us/powershell/module/az.compute/update-azvmss?view=azps-3.5.0) gives and impression that it can be updated which is not true.

**Comment by dingmeng-xue** [comment]
CC compute team to check the suggestion around doc.

**Comment by Drewm3** [comment]
Thanks. We will look into getting this updated.

**Comment by Drewm3** [comment]
We are going to update the API documents to show with properties can only be set at create time. These updates will then propagate down to the cmdlets. We will resolve this issue once the API docs have been updated and published.

**Comment by Drewm3** [comment]
We have added details in the API documentation to clarify which properties can only be set at create time. For example note the ImageReference documentation for the [VMSS Create API](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/createorupdate).

**Comment by qqnarwhal** [comment]
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/createorupdate#storageaccounttypes
Was reviewing the doc and saw that the storage account type still doesn't mention that it's creation time only properties. 

and -ManagedDiskStorageAccountType is still on the update-azvmss page. 
https://docs.microsoft.com/en-us/powershell/module/az.compute/update-azvmss?view=azps-5.3.0&viewFallbackFrom=azps-3.5.0

Can this be re-opened and reviewed once more please? Thank you!

**Comment by avirishuv** [comment]
quick update: we are expecting the doc to be updated sometime next month. This would reflect that the storage account type can only be set at creation time for VMSS.

**Comment by avirishuv** [comment]
Apologies for the delay here, the doc update is still pending and I will confirm here once this is done.

**Comment by avirishuv** [comment]
the doc has been updated to reflect that storage account type can only be set at VMSS creation time. https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-sets/create-or-update#storageaccounttypes 

Closing the issue, feel free to reopen if there are additional questions on this topic.
