### ISSUE TITLE
Az.Storage Datalake gen2 commandlets, whats the proper way to use them with azure functions?

### ISSUE THREAD

**Issue by mganeshphani** [Azure/azure-powershell#11174]
## Description
following module 1.9.1-preview version is failing to load in Azure functions occasionally.. 
https://docs.microsoft.com/en-us/powershell/module/az.storage

## Steps to reproduce

```powershell
```saving the module to modules folder in azure functions
``` importing module while using datalake gen2 command-lets
``` 10% of the runs failing with "Assembly with same name is already loaded".
``` when contacted azure support they asked us to reach out to you to understand if this is a known issue with preview module and what are the best practices and when will these gen2 commands will be available in the GA.. ticket(120021921002468) - person being interacted with(jaweiand@microsoft.com)

## Environment data

<!-- Please run $PSVersionTable and paste the output in the below code block
     If running the Docker container image, indicate the tag of the image used and the version of Docker engine-->

```

```

## Module versions

<!-- Please run (Get-Module  -ListAvailable) and paste the output in the below code block -->

```powershell

```

## Debug output

```

```

## Error output

``` Assembly with same name is already loaded

```

**Comment by dingmeng-xue** [comment]
We will consult with functions service team how to import preview modules.

**Comment by mganeshphani** [comment]
Thankyou.. I am blocked on using this, right now.. if you can try to expedite the process that would be great.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by blueww** [comment]
@mganeshphani 
Would you please run "Get-Module  -ListAvailable" and see if other version of Az.Storage already on your machine? 
If so, would you please uninstall it? then try again?

**Comment by dingmeng-xue** [comment]
@mganeshphani, please check below instruction from functions team. The guide shows you how to update modules.

For local debugging in Functions, modules can be installed either using any regular method described at https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell#dependency-management, or running Install-Module locally, or just copying the module content to any local folder and updating $env:PSModulePath accordingly.

**Comment by blueww** [comment]
@mganeshphani

I will close this issue as not heard from you for a long time.
Feel free to contact us if you need further assistance.
