### ISSUE TITLE
Set-AzNetworkSecurityRuleConfig - Documentation is not up to date with Az.Network regarding available protocols

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-powershell#11188]
I'm om Az.Network v2.3.1 and Az v3.5.0, which is the latest as of 2020-02-25.

```poweshell
PS C:\Users\OlavRønnestadBirkela> Get-Module -ListAvailable 'Az.Network'


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                            
---------- -------    ----                                ----------------                                                                                            
Script     2.3.1      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, Ne...



PS C:\Users\OlavRønnestadBirkela> Get-Module -ListAvailable 'Az'
```

Ref #10347, "Set-AzNetworkSecurityRuleConfig" now can specify other protocols than UDP, TCP or wildcard, but the documentation is not up to date.

* https://docs.microsoft.com/en-us/powershell/module/az.network/add-aznetworksecurityruleconfig?view=azps-3.5.0#parameters

This is also true for "Get-Help" on latest Az.Network module:

```powershell
PS C:\Users\OlavRønnestadBirkela> Get-Help -Name 'Add-AzNetworkSecurityRuleConfig' -Parameter 'Protocol'

-Protocol <System.String>
    Specifies the network protocol that a rule configuration applies to. The acceptable values for this parameter are: - Tcp
    
    - Udp
    
    - Wildcard character (*) to match both
    
    Required?                    false
    Position?                    named
    Default value                None
    Accept pipeline input?       False
    Accept wildcard characters?  false
    




PS C:\Users\OlavRønnestadBirkela>
```

Pleae update this. Other cmdlets might be affected as well.

**Comment by wyunchi-ms** [comment]
Hi @o-l-a-v, thanks a lot for your feedback! I'm forwarding this issue to network team.

**Comment by wyunchi-ms** [comment]
Hi @o-l-a-v, thanks a lot for your feedback! I'm forwarding this issue to network team.

**Comment by allegradomel** [comment]
Hi @o-l-a-v, thank you for opening this new issue - we'll try to make a fix asap

**Comment by SaurabhSharma-MSFT** [comment]
@vnetsuppgithub Do you have any updates on this issue ?

**Comment by o-l-a-v** [comment]
> @vnetsuppgithub Do you have any updates on this issue ?

I thought you were the ones to tell me. I haven't scripted NSGs in a while. :)

**Comment by SaurabhSharma-MSFT** [comment]
@o-l-a-v Previous message was intended for the services team and not for you :)

**Comment by RakeshMohanMSFT** [comment]
This is updated now.

![image](https://user-images.githubusercontent.com/49954584/203897272-ac84e97d-3b4b-4032-835f-8ffd25ad3a6c.png)
