### ISSUE TITLE
Scope of command Get-AzResourceGroup

### ISSUE THREAD

**Issue by iceyokuna** [Azure/azure-powershell#11187]
## Description of the new feature
When i use Get-AzResourceGroup, i can get resourcegroup from current context subscription only.
And there is no subscription flag to get resourcegroup from specific subscription.

Is there a way to not use Set-Azcontext before using Get-AzResourceGroup. Because it take comsume too much time. If i need to run command 100+ iterations.

## Proposed implementation details (optional)
You should add flag subscription to commands that can scope only current context. (if there is another to do that please feel free to share your idea)

**Comment by wyunchi-ms** [comment]
Hi @iceyokuna , thanks for your feedback! It's very useful. We will consider this issue.

**Comment by iceyokuna** [comment]
Thank you. I see so many commansd that need to set-azcontext before we can run the command. If you can add a flag subscription to those commands. It will help customer a lot to save time that they dont need to set az-context.
