### ISSUE TITLE
No documentation for DNS (SAN) in New-AzKeyVaultCertificatePolicy

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-powershell#11203]
## Description of the new feature

The documentation for [New-AzKeyVaultCertificatePolicy](https://docs.microsoft.com/en-us/powershell/module/az.keyvault/new-azkeyvaultcertificatepolicy?view=azps-3.5.0) has no examples nor details how to create a certificate with one or multiple SANs.

Also it doesn't explain that the DNS parameter actually means SAN. There are no results if you search for "SAN" or "alternative" on the page.

P.S.

Docs for PowerShell doesn't allow to open a GitHub issue like what for instance Service Fabric does.

**Comment by abatishchev** [comment]
@dingmeng-xue hi, do you know if there is a chance this to be addressed in a near future?

**Comment by dingmeng-xue** [comment]
Since functions provided by service team, we need to talk with KeyVault team to understand the example.
Docs for Azure PowerShell are synced from azure-powershell repo. If there is any question to docs, feel free to raise issue to this repo.

**Comment by abatishchev** [comment]
Hi, how can I get tracking on this issue from the service (Key Vault) team?

**Comment by abatishchev** [comment]
@dingmeng-xue, please ping the service team.
