### ISSUE TITLE
Get-AzureRMTenant - Wrong domain

### ISSUE THREAD

**Issue by tylerd** [Azure/azure-powershell#1121]
It is very confusing when you are trying to select the right tenant to use and they all have the same domain.

```
PS C:\Users\localadmin\Desktop> Get-AzureRmTenant


TenantId : 1604a336-abfc-4ffe-a7e7-bf277ec36f51
Domain   : microsoft.com

TenantId : 72f988bf-86f1-41af-91ab-2d7cd011db47
Domain   : microsoft.com

TenantId : 434e9d2b-d8d3-4bd9-bd27-03b20a16d863
Domain   : microsoft.com

TenantId : 94c40a73-c82f-47f0-8244-aed167ae33a0
Domain   : microsoft.com
```

**Comment by markcowl** [comment]
@tylerd Yeah, unfortunately, the tenant list API does not return the actual domain name, so this is gleaned from your account name. Do you think it would be better to omit this?

**Comment by tylerd** [comment]
@markcowl Without the Domain information this Command is useless. Previously I was having an issue with mis-matched tenant and subscription in my "context" but it seems that even if my current subscription is not attached to my current tenant I can access Get-AzureRmResources

**Comment by markcowl** [comment]
No reports for over a year.  Closing
