### ISSUE TITLE
Get-AzConsumptionUsageDetail only returns 1000 results

### ISSUE THREAD

**Issue by ChrisSommers** [Azure/azure-powershell#11224]
As per the title, something has changed in the last month as I have a query I run at the start of the month and it worked fine last month. 

I tried using the 'maxcount' parameter but it makes no difference.

**Comment by ChrisSommers** [comment]
To add, I'm using v 1.0.2 of Az.Billing

**Comment by dingmeng-xue** [comment]
@ChrisSommers , could you share debug message after `$DebugPreference="Continue"`?

**Comment by ChrisSommers** [comment]
Which bit of the DEBUG do you want? The output runs to over 1000 pages!

**Comment by dingmeng-xue** [comment]
For your case, you can just show the begin and end of log. Normally, we need the URL called and part of response. Repeating element can be omitted.

**Comment by ChrisSommers** [comment]
For the record, this issue seems to have fixed itself. I'm not sure if anything was done behind the scenes but this issue can now be closed.
