### ISSUE TITLE
Login-AzAccount : AADSTS50000: There was an error issuing a token or an issue with our sign-in service. #171

### ISSUE THREAD

**Issue by KasamShaikh** [Azure/azure-powershell#11233]
When trying to login using Window PowerShell ISE, Login-AzAccount command, I am being prompted to enter username and password, but then instead of prompting for Auth code, it throes the error,
Trace ID: 78a52fb1-6427-48db-9e07-6fa7c8faee00
Correlation ID: 75f55382-d7bc-43cd-93c5-ec9a28805aa6
Timestamp: 2020-03-03 15:44:47Z
At line:2 char:1
Login-AzAccount
  + CategoryInfo          : CloseError: (:) [Connect-AzAccount], AdalServiceException
  + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand\

Kindly help.

**Comment by KasamShaikh** [comment]
Any help would be appreciated.

**Comment by dingmeng-xue** [comment]
@KasamShaikh , please share debug message after you execute `$DebugPreference="Continue"`. In addition, please share the version of Az.Accounts via `Get-Module -Name Az.Accounts -ListAvailable`

**Comment by KasamShaikh** [comment]
Version => 1.7.2

And the execution of DebugPreference, please find the attached image.

Hope this [helps.](url
![powershell-issue](https://user-images.githubusercontent.com/22021538/75913281-a4ab5600-5e78-11ea-8991-fdc7e9bc04b5.PNG)
)

**Comment by abhijithsnair** [comment]
Hi @KasamShaikh,

The error AADSTS50000 is a TokenIssuanceError (https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes)

There are two ways to resolve:

1. Sign out from your Azure Account and login using the below:
In PowerShell, use
----   Connect-AzAccount and try logging in.

2. If the issue still exists, you might need to create a support request (https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-troubleshooting-support-howto).

I will try to post if i find anything useful.

Hope this helps!

Thanks.

**Comment by dingmeng-xue** [comment]
@KasamShaikh, in addition, please clean the cache of browser and try again? Does `-devicecode` login work?

**Comment by KasamShaikh** [comment]
@dingmeng-xue  It worked now, no idea how. But nothing here was helpful. Still thanks for responding.
