### ISSUE TITLE
Command Add-AzKeyVaultKey is not working

### ISSUE THREAD

**Issue by 20shivangi** [Azure/azure-powershell#11242]
## Description
Command Add-AzKeyVaultKey is not working. Getting 'Forbidden' error.

## Steps to reproduce
I am running a script :

$servicePrincipalId = "***"
$servicePrincipalKey = "***"
$tenantId = "***"
$azureSubscriptionId = "***"
$securePassword = ConvertTo-SecureString $servicePrincipalKey -AsPlainText -Force
$psCredential = New-Object System.Management.Automation.PSCredential ($servicePrincipalId, $securePassword)
$azureAccount = Connect-AzAccount -ServicePrincipal -Tenant $tenantId -Credential $psCredential -Environment AzureCloud
Add-AzKeyVaultKey -VaultName 'testcontoso' -Name 'ITSoftware' -Destination 'Software'

I have already given SPN the permission of Contributor, Owner and Key Vault Contributor. Still
 I am getting error: Add-AzKeyVaultKey : Operation returned an invalid status code 'Forbidden'
Can you please tell us what has to be done?

**Comment by dingmeng-xue** [comment]
@20shivangi , please share debug message after you execute `$DebugPreference="Continue"`

**Comment by 20shivangi** [comment]
@dingmeng-xue I am able to figure out the issue. Thanks for your help. Thereby closing this issue.
