### ISSUE TITLE
Inconsistent cmdlet naming - Get-AzureRmVmExtensionImage

### ISSUE THREAD

**Issue by stuartpreston** [Azure/azure-powershell#1125]
```Get-AzureRmVmExtensionImage``` naming is inconsistent with the other cmdlets with VM in their name.

e.g.

```
Cmdlet          Get-AzureRmVMExtension                             0.1
Cmdlet          Get-AzureRmVmExtensionImage                        0.1
Cmdlet          Get-AzureRmVMExtensionImageType                    0.1
```

The jury is out on ```Save-AzureRmVhd``` too but there's nothing else that has VHD in the name for me to complain about.

**Comment by huangpf** [comment]
@hyonholee

**Comment by huangpf** [comment]
@stuartpreston Do you mean ```Vm``` should be ```VM```, and ```Vhd```` shall be ```VHD```?

**Comment by stuartpreston** [comment]
@huangpf I don't mind which way you go, but would suggest to make them consistent - i.e. all AzureRmVm* or AzureRmVM*

I understand the casing was done that way for readability. It would be good to be consistent everywhere.

**Comment by huangpf** [comment]
@hovsepm 
Please help assign it to @hyonholee.

**Comment by singhkay** [comment]
This'll be fixed in upcoming release. Closing.
