### ISSUE TITLE
Fix location null checks in UpdateAzCosmosDBAccountRegion.cs

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11274]
UpdateAzCosmosDBAccountRegion.cs

Fix location check. Currently checks if string array OR object array are null, but then attempts to iterate through both of them; if only one is specified as is typical when selecting parameter set, then a Null Reference Exception is thrown.

Reference: https://docs.microsoft.com/en-us/powershell/module/az.cosmosdb/update-azcosmosdbaccountregion

Code: https://github.com/Azure/azure-powershell/blob/master/src/CosmosDB/CosmosDB/CosmosDBAccount/UpdateAzCosmosDBAccountRegion.cs#L76

**Comment by MehaKaushik** [comment]
https://github.com/Azure/azure-powershell/pull/11388
