### ISSUE TITLE
Specify correct Constants message for UpdateAzCosmosDBAccountRegion InputObject parameter

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11277]
https://github.com/Azure/azure-powershell/blob/master/src/CosmosDB/CosmosDB/CosmosDBAccount/UpdateAzCosmosDBAccountRegion.cs#L49

Currently the HelpMessage attrib is Constants.ResourceIdHelpMessage. Should be Constants.AccountObjectHelpMessage

**Comment by MehaKaushik** [comment]
In PR https://github.com/Azure/azure-powershell/pull/11388
