### ISSUE TITLE
Az Login behaviour in Powershell 7

### ISSUE THREAD

**Issue by DanteNahuel** [Azure/azure-powershell#11273]
## Description of the new feature
In previous Powershell versions, Login-Azaccount and Connect-AzAccount pops up a Login Prompt in where you can either enter the login information or close it, which will cancel the login cmdlet. 

In PS 7, there's no such option and the only way to login is to read the console's text, open themselves a Browser, enter the information provided by the console and then wait the console to Sync.
This causes some end user issues:

Normal ways of cancelling the login don't work
  Neither ctrl + z nor ctrl + c work and there's no pop up to close. 
  Your only option is to close the Powershell console, which is not very user friendly.
The Popup also helps in bringing the attention of the user to the action, making them understand they need to enter their input to continue.
The current behaviour can make end users think there's something wrong with the script because "nothing's happening".
## Proposed implementation details (optional)
Create a Flag that lets you choose between the type of Login prompt you want to use, either the old Enter Credentials Pop up or the new "devicelogin" webpage.

**Comment by dingmeng-xue** [comment]
@DanteNahuel, Could you check PowerShell Core? The behavior should be the same.

**Comment by dingmeng-xue** [comment]
It is the current ADAL behavior on PowerShell Core or PowerShell 7. Close this issue and we will provide new interactive behavior after we integrate with MSAL for authentication #10844. We are working on it.
