### ISSUE TITLE
Fix VNet rule null checks in UpdateAzCosmoDBAccount.cs

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11275]
UpdateAzCosmosDBAccount.cs

Fix VNet rule check. Currently checks if string array OR object array are null, but then attempts to iterate through both of them; if only one is specified as is typical when selecting parameter set, then a Null Reference Exception is thrown.

Reference: https://docs.microsoft.com/en-us/powershell/module/az.cosmosdb/update-azcosmosdbaccount

Code: https://github.com/Azure/azure-powershell/blob/master/src/CosmosDB/CosmosDB/CosmosDBAccount/UpdateAzCosmosDBAccount.cs#L155

**Comment by MehaKaushik** [comment]
In PR https://github.com/Azure/azure-powershell/pull/11388
