### ISSUE TITLE
New-AzureRmExpressRouteCircuitPeeringConfig - no sharedKey parameter

### ISSUE THREAD

**Issue by jsbrooks** [Azure/azure-powershell#1127]
The is no option to configure the sharedKey value for BGP peering sessions in the New-AzureRmExpressRouteCircuitPeeringConfig commandlet. 
Same sharedKey parameter should also be added to the Set-AzureRmExpressRouteCircuitPeeringConfig commandlet

**Comment by iafilius** [comment]
Hi, same over here, is there a workaround known?

**Comment by markjbrown** [comment]
This bug has been fixed. Closing.
