### ISSUE TITLE
Get-AzCosmosDBSqlDatabaseThroughput throws generic error when run on a database without shared throughput / where containers have dedicated throughput

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11289]
Reference: https://github.com/Azure/azure-powershell/blob/master/src/CosmosDB/CosmosDB/SQL/GetAzCosmosDBSqlDatabaseThroughput.cs#L54

When this cmdlet is run against a Cosmos DB database that is set up without shared throughput, i.e. each container has dedicated throughput, this cmdlet emits an error message like "Entity with the specified id does not exist in the system. ActivityId: f7f78be0-c246-41de-95c2-4e00b749eebe, Microsoft.Azure.Documents.Common/2.10.0".

Suggest changing by adding a null check at above-referenced code area and changing output to reference that (as expected) no database throughput was found. The current error message is non-specific and does not tell the cmdlet operator the specific issue.

**Comment by MehaKaushik** [comment]
-Detailed parameter is going to be deprecated in future releases, following which throughput would be available in the resource's respective GetResults object.
