### ISSUE TITLE
Get-AzureWebsite behaviour is very unclear from documentation

### ISSUE THREAD

**Issue by makhdumi** [Azure/azure-powershell#1128]
Get-AzureWebsite will return a different type of object, depending on whether or not the site has deployment slots. This is not mentioned _anywhere_ in the documentation. 

For a site with deployment slots, I get this when I run `Get-AzureWebsite mysite`

```
Name       : mysite
State      : Running
Host Names : {mysite.com, mysite.azurewebsites.net}

Name       : mysite(staging)
State      : Running
Host Names : {mysite-staging.azurewebsites.net}
```

When it doesn't have a deployment slot, or if I specify a slot with `-Slot`, I do get the actual object. Yet what do I do when I want to access the actual, live site that doesn't have a slot name?

Apparently you have to use 'Production' as the slot name, i.e. `Get-AzureWebsite mysite -Slot Production`. This seems like a "magic" string to me, because I don't see "Production" mentioned anywhere in the Azure UI itself.

This isn't mentioned anywhere in the documentation, e.g. [here](https://msdn.microsoft.com/en-us/library/azure/dn495127.aspx).

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
