### ISSUE TITLE
Fix UpdateAzCosmosDBAccountRegion

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11280]
Cannot make UpdateAzCosmosDBAccountRegion.ps1 succeed. In addition to having to specify both -Location and -LocationObject (see also #11274), cannot find a way to make cmdlet succeed with various approaches to building -LocationObject.

See test code at https://github.com/plzm/azure-docs-powershell-samples/blob/cosmosdb-sql/cosmosdb/sql/ps-account-update.ps1

**Comment by MehaKaushik** [comment]
Targeting S168.
