### ISSUE TITLE
Fix error when running Get-AzCosmosDBSqlDatabase -Detailed on a database without shared throughput/container dedicated throughput

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11287]
Reference: https://github.com/Azure/azure-powershell/blob/master/src/CosmosDB/CosmosDB/SQL/GetAzCosmosDBSqlDatabase.cs#L66

When Get-AzCosmosDBSqlDatabase is run with -Detailed against a database without shared throughput - i.e. containers have dedicated throughput - this cmdlet emits an error "Entity with the specified id does not exist in the system. ActivityId: [GUID], Microsoft.Azure.Documents.Common/2.10.0

Recommend adding null checks to the above-referenced code area for throughputSettingsGetResults to prevent this error.

**Comment by MehaKaushik** [comment]
Wrongly linked with PR

**Comment by MehaKaushik** [comment]
-Detailed parameter is going to be deprecated in future releases, following which throughput would be available in the resource's respective GetResults object.
