### ISSUE TITLE
GetAzCosmosDBSqlContainerThroughput throws generic error when run on a container using shared database throughput

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11290]
Reference: https://github.com/Azure/azure-powershell/blob/master/src/CosmosDB/CosmosDB/SQL/GetAzCosmosDBSqlContainerThroughput.cs#L60

When this cmdlet is run against a Cosmos DB container that is set up without dedicated throughput, i.e. the container uses database shared throughput, this cmdlet emits an error message like "Entity with the specified id does not exist in the system. ActivityId: e075f32f-7f1b-4af1-942b-041a82f0cf3a, Microsoft.Azure.Documents.Common/2.10.0".

Suggest changing by adding a null check at above-referenced code area and changing output to reference that (as expected) no container throughput was found. The current error message is non-specific and does not tell the cmdlet operator the specific issue.

**Comment by MehaKaushik** [comment]
-Detailed parameter is going to be deprecated in future releases, following which throughput would be available in the resource's respective GetResults object.
