### ISSUE TITLE
Docuementation bug: Azure Network

### ISSUE THREAD

**Issue by arpitjain099** [Azure/azure-powershell#11298]
## Description

https://docs.microsoft.com/en-us/powershell/module/az.network/New-AzPrivateEndpoint?view=azps-3.6.1
Hardcoded value `$virtualNetwork.Subnets[0]` in documentation can lead to errors if existing vnet has more than one subscription.

Will add more details later

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
Invovle Network team to check if it is a limitation.

**Comment by allegradomel** [comment]
@arpitjain099 can you clarify "if existing vnet has more than one subscription"?

Thanks!
