### ISSUE TITLE
No way of linking VM with ASR Protected Item

### ISSUE THREAD

**Issue by DanteNahuel** [Azure/azure-powershell#11293]
## Description
I'm trying to disable ASR protection from VMs using Powershell. However, there's no way of getting the required parameters (Vault, Fabric, Container, etc) to disable it from the Get-AzVM Object.
This makes impossible to perform the task programatically. You have to know the Vault id beforehand by checking in the Portal and same for the Fabric.

For Backups, I've used  
`Get-AzRecoveryServicesBackupStatus -Name $vmname -ResourceGroupName $rg -Type "AzureVM"`
to retrieve the Vauld id
and this:
`$container = (Get-AzRecoveryServicesBackupContainer -ContainerType "AzureVM" -Status "Registered" -VaultId $VaultID | where-object {$_.FriendlyName -eq $vmname -and $_.ResourceGroupName -eq $rg}) `
To get the container name, assuming it will have the same name as the VM
But I don't find any way of doing this for DR.

Am I wrong? Is this a bug? something that wasn't taken into consideration? 

Disabling/enabling from the command line should be more efficent than doing from the Portal, but this breaks this functionality and stops you from creating automation solutions.

## Expected Behaviour

There should be a direct cmdlet that uses a VM Object or the VM Name and RG properties to check an ASR protected item

**Comment by dingmeng-xue** [comment]
Thanks for reporting.

**Comment by DanteNahuel** [comment]
More information:

The API Documentation reference states that you can get all the Protected Items in a specific Vault **without requiring the fabric or container name**.
`GET https://management.azure.com/Subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.RecoveryServices/vaults/{resourceName}/replicationProtectedItems?api-version=2018-07-10`
This would be a large improvement, even if you still have to know or go through all the existing vaults, since it would require only one additional step.
Currently you need would need to loop through every Vault, then every Fabric, then every container, and then every protected item, which is very bad performance wise.

**Comment by DanteNahuel** [comment]
This is what I'm doing right now which is atrocious in a Development sense of speaking.


```
$Vaults = Get-AzRecoveryServicesVault 
	foreach ($Vault in $Vaults)
	{
		Set-AzRecoveryServicesAsrVaultContext -Vault $Vault
		$Fabrics = Get-AzRecoveryServicesAsrFabric
			foreach ($Fabric in $Fabrics){
				$drContainers = Get-AzRecoveryServicesAsrProtectionContainer -Fabric $Fabric
					foreach ($drContainer in $drContainers){
						$protectedItem = Get-AzRecoveryServicesAsrReplicationProtectedItem -ProtectionContainer $drContainer | where {$_.RecoveryAzureVMName -eq $vm.Name}
					}
			}
	}
```

**Comment by Drewm3** [comment]
Correcting the service to the Site Recovery service.

**Comment by DanteNahuel** [comment]
Anything new about this?

**Comment by punit1396** [comment]
@DanteNahuel 
As of today, running any ASR powershell cmdlet would require the vault context to be set. So, ideally the procedure would go as you mentioned earlier - Find the right vault -> Set the vault context -> Use ASR cmdlets (including disable).
There is a way to figure out the relation between the VM and the corresponding protected item (and thus, vault information).
When a VM is protected, ASR creates a resource link linking the VM and the protected item created. So, using that should help your case.
However, there's another problem here. There's no cmdlet to get/list resource links. So, you would be making a REST call through powershell to get this list and then get the protected item id from it.
Sharing a snippet below to do this.

```powershell
#Region Constants

class ConstantStrings
{
    static [string] $managementAzureEndpoint = "https://management.azure.com"
    static [string] $powershellClientId = "1950a258-227b-4e31-a9cf-717495945fc2"
    static [string] $powershellRedirectUri = "urn:ietf:wg:oauth:2.0:oob"
    static [string] $powershellAuthorityUriPrefix = "https://login.windows.net/"
    static [string] $providers = "providers"
    static [string] $resourceGroups = "resourceGroups"
    static [string] $resourceLinks = "links"
    static [string] $resourceLinksApiVersion = "2016-09-01"
    static [string] $resourcesProvider = "Microsoft.Resources"
    static [string] $subscriptions = "subscriptions"
    static [string] $authHeader = "authorization"
    static [string] $contentTypeJson ="application/json"
    static [string] $httpGet = "GET"
}
#EndRegion

### <summary>
### Extracts the resource type from ARM id.
### </summary>
### <param name="armId">Resource ARM id.</param>
### <returns>Resource name.</returns>
function Extract-ResourceTypeFromId([string] $armId)
{
    if ([string]::IsNullOrEmpty($armId))
    {
        throw "InvalidARMId"
    }

    $tokens = $armId.Trim('/').Split('/')

    return $tokens[-2]
}

### <summary>
### Forms the url string from the tokens passed.
### </summary>
### <param name="apiVersion">Api version.</param>
### <param name="tokens">Url string tokens.</param>
### <returns>Url string.</returns>
function Get-UrlString([string] $apiVersion, [string[]]$tokens)
{
    if ([string]::IsNullOrEmpty($apiVersion))
    {
        throw "api version missing"
    }

    if ($null -eq $tokens)
    {
        throw "Url tokens missing"
    }

    $url = [ConstantStrings]::managementAzureEndpoint + '/'
    $url += $tokens.Trim('/') -Join '/'
    $url = $url.Trim('/')
    $url += '?' + [ConstantStrings]::apiVersion + '=' + $apiVersion

    return $url
}

#Region REST

### <summary>
### Invokes ARM call in a uniform manner.
### </summary>
### <param name="parameters">REST call parameters.</param>
### <returns>Response.</returns>
function Invoke-ArmCall($parameters)
{
    try
    {
        $response = Invoke-RestMethod @parameters
    }
    catch
    {
        throw [ErrorStrings]::ArmCallFailed(
            $(Out-String -InputObject $PSItem),
            $(Out-String -InputObject $parameters))
    }
    finally
    {
        Write-Verbose "`nRequest: `n$(Out-String -InputObject $Params)"
        Write-Verbose "`nResonse: `n$(Out-String -InputObject $Response)"
    }

    return $response
}

### <summary>
### Gets the authentication result to management.azure.com endpoint.
### </summary>
### <param name="tenantId">The tenant id.</param>
function Get-Authentication([string] $tenantId)
{
    Write-Verbose "`nFetching auth token."

    $AuthorityUri = [ConstantStrings]::powershellAuthorityUriPrefix + $tenantId
    $AuthContext =
        [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext]::New($AuthorityUri)
    $PlatformParameters =
        [Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParameters]::New("Auto", $null)
    $AuthResult =
        $AuthContext.AcquireTokenAsync(
            [ConstantStrings]::managementAzureEndpoint,
            [ConstantStrings]::powershellClientId,
            [ConstantStrings]::powershellRedirectUri,
            $PlatformParameters)

    return $AuthResult.Result
}

### <summary>
### Gets the resource links at resource group scope.
### </summary>
### <param name="resourceGroupName">Resource group name.</param>
### <returns>List of resource link source id to target id mappings.</returns>
function Get-ResourceLinks([string] $resourceGroupName)
{
    Write-Host -ForegroundColor Green "Fetching resource links under '$resourceGroupName'" `
        "resource group..."

    $context = Get-AzContext
    $token = Get-Authentication -TenantId $context.Tenant.Id
    $url = Get-UrlString -ApiVersion $([ConstantStrings]::resourceLinksApiVersion) -Tokens `
        @(
            [ConstantStrings]::subscriptions,
            $context.Subscription.Id,
            [ConstantStrings]::resourceGroups,
            $resourceGroupName,
            [ConstantStrings]::providers,
            [ConstantStrings]::resourcesProvider,
            [ConstantStrings]::resourceLinks
        )

    $params = @{
        ContentType = [ConstantStrings]::contentTypeJson
        Headers     = @{
            [ConstantStrings]::authHeader = "Bearer $($token.AccessToken)"}
        Method      = [ConstantStrings]::httpGet
        URI         = $url
    }

    $response = Invoke-ArmCall -Parameters $params
    $properties = $response.value.properties | `
        Where-Object {
            $(Extract-ResourceTypeFromId -ArmId $_.TargetId) -like `
            [ConstantStrings]::replicationProtectedItems
        }

    return $properties
}
#EndRegion
```
Here the resource group would be the VM's. Also, you can pass a filter during the REST api to get results filtered based on SourceId (would be the VM's arm Id) or the TargetId (would be the protected item's Id). Refer [this](https://docs.microsoft.com/en-us/rest/api/resources/resourcelinks/listatsourcescope)

**Comment by DanteNahuel** [comment]
@punit1396 thank you for sharing this.
However this is far away from an ideal solution. If this is possible through REST, then it should be implemented in PowerShell to avoid having to deal with REST calls in the middle of a script.
I really hope the ASR team can create and provide a better solution.

**Comment by Sharmistha-Rai** [comment]
@DanteNahuel - we are tracking this in our backlog items and will keep it on our radar as a point of improvement.

**Comment by Sharmistha-Rai** [comment]
We are tracking this in our backlog items. Please feel free to reopen for any additional queries.

**Comment by kolexinfos** [comment]
@Sharmistha-Rai Do you have any feedback on this yet?

**Comment by Sharmistha-Rai** [comment]
Hi @kolexinfos - we haven't been able to prioritize yet, due to bigger items on our plate. I will keep this thread updated in case there is any news for the work on this item.

**Comment by hatvik** [comment]
@Sharmistha-Rai Still no update on this?

**Comment by Sharmistha-Rai** [comment]
@hatvik - no, but our next semester planning is coming up. We will try to prioritize this item.

**Comment by samhodgkinson** [comment]
Is this still an open item, or did this get fixed and closed ?
