### ISSUE TITLE
What is ARM cmdlet equivalent to Start-AzureSqlDatabaseImport?

### ISSUE THREAD

**Issue by olegburov** [Azure/azure-powershell#1129]
Azure module contains the `Start-AzureSqlDatabaseImport` and `Start-AzureSqlDatabaseExport` cmdlets. What is the equivalent ARM-based cmdlet?

**Comment by BenedekFarkas** [comment]
I guess this issue was kind of left alone to age. We now have an answer though: `New-AzureRmSqlDatabaseImport` and `New-AzureRmSqlDatabaseExport`.
