### ISSUE TITLE
Documentation bug: Azure Network

### ISSUE THREAD

**Issue by arpitjain099** [Azure/azure-powershell#11300]
## Description
https://docs.microsoft.com/en-us/powershell/module/az.network/new-azprivatelinkservice?view=azps-3.6.1

Hardcoded `$vnet.subnets[1]` can lead to issues if the vnet has multiple subnets.

Will add more details later.

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
Invovle Network team to check if it is a limitation.

**Comment by allegradomel** [comment]
Looking into it...

**Comment by ramandhillon84** [comment]
@arpitjain099 - you are right. The example should either clarify that the VNet has more than one Subnets and we're referring to 2nd subnet, or just do a get Subnet with name and use that. We'll get this updated.
