### ISSUE TITLE
Search for objects

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-powershell#1130]
Hello Team, (Get-AzureSubscription).count returns 10 to me. And it is really frequent when during daily support and management activities we need to find objects by name or even by the list of names. There is no way do do such search fast in Powershell, because it extracts all objects from subscription first, and it is overwhelmingly slow . On the other hand portal does such searches quickly, how can we do this via powershell?

Thanks

**Comment by eosfor** [comment]
May be some REST API or something?

**Comment by markcowl** [comment]
@eosfor   Try using Get-AzureRmSubscription, which is lightning quick.

**Comment by eosfor** [comment]
Thanks @markcowl, let me clarify this a bit.
Lets say we have ~10 subscriptions. At some point we get a request from customer/user that some VMs experience issues or they are asking to perform some actions on some set of machines. What they provide is usually a list of VM names, sometimes they are not even aware of cloud services they are running on, mostly because those machines are not exposed to Internet. So the task is having a VM names find VM objects across all currently existing subscriptions subscriptions as fast as possible, and pipe them then to something to see their services, discs, networks and so on.

**Comment by eosfor** [comment]
Another thing is to search VMs by IP

**Comment by eosfor** [comment]
So what i came up with is the following. I managed to use API new portal uses to search VMs and Services. It is fast. But i could not find any documentation on this. Does anyone know something about this API?

Well, yes, i also expanded some existing Azure cmdlets with additional parameter and i'm using this trick here too

```PowerShell
function Get-AzureObject {
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string[]]$Name,
    $SubscriptionName,
    $apiVersion = '2014-04-01-preview',
    [Parameter()]
    [switch]$VMOnly,
    $AdTenant = "<adtenanthere>.onmicrosoft.com"
)
begin{
    # Set Azure AD Tenant name
     
    # Set well-known client ID for AzurePowerShell
    $clientId = "1950a258-227b-4e31-a9cf-717495945fc2" 
    # Set redirect URI for Azure PowerShell
    $redirectUri = "urn:ietf:wg:oauth:2.0:oob"
    # Set Resource URI to Azure Service Management API
    $resourceAppIdURI = "https://management.core.windows.net/"
    # Set Authority to Azure AD Tenant
    $authority = "https://login.windows.net/$adTenant"
    # Create Authentication Context tied to Azure AD Tenant
    $authContext = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext" -ArgumentList $authority
    # Acquire token
    $authResult = $authContext.AcquireToken($resourceAppIdURI, $clientId, $redirectUri, "Auto")
    # API method
    $method = "GET"
    # API header
    $headerDate = '2014-10-01'
    $authHeader = $authResult.CreateAuthorizationHeader()

    if ($PSBoundParameters['SubscriptionName']){
        $subscriptions = (Get-AzureSubscription -SubscriptionName $SubscriptionName).SubscriptionId
    }
    else {
        $subscriptions = (Get-AzureSubscription).SubscriptionId
    }

    $typesToFilter = @{'Microsoft.ClassicCompute/virtualMachines' = {param($id, $rg, $n) Get-AzureVM -SubscriptionName (Get-AzureSubscription -SubscriptionId $id).SubscriptionName -ServiceName $rg -Name $n};
                       'Microsoft.ClassicCompute/domainNames' = {param($id, $rg, $n) Get-AzureService -SubscriptionName (Get-AzureSubscription -SubscriptionId $id).SubscriptionName -ServiceName $rg};
                       'microsoft.classicstorage/storageaccounts' = {param($id, $rg, $n) Get-AzureStorageAccount -StorageAccountName $n}}

    $subscrFilterString = ($subscriptions | % {"subscriptionId eq '$_'"}) -join ' or '
    write-verbose "Subscriptions filter`: $subscrFilterString"
}
process{
    # Set HTTP request headers to include Authorization header
    $headers = @{"x-ms-version"="$headerDate";
                 "Authorization" = $authHeader;Accept = 'application/json';
                 'x-ms-path-query' = "/resources?api-version=2014-04-01-preview&`$filter=($subscrFilterString) and ((substringof('$Name',name) or substringof('$Name',resourcegroup)))"}
    if ($VMOnly.IsPresent) {
        $nameFilterString = ($Name | % {"substringof('$_',name)"}) -join ' or '
        write-verbose "Names filter`: $nameFilterString"
        $headers.'x-ms-path-query' = "/resources?api-version=2014-04-01-preview&`$filter=($subscrFilterString) and (($nameFilterString))"
    }

    # generate the API URI
    $URI = "https://management.azure.com/api/invoke"

    # execute the Azure REST API
    $list = Invoke-RestMethod -Uri $URI -Method $method -Headers $headers
    
    $objectsFound = 
        $list.value | %{
            $element = $_
            $r = [regex]::Match($element.id, "/subscriptions/(?<SubscriptionID>.+)/resourceGroups/(?<ResourceGroup>.+?)/.+/(?<ObjectName>.+)$")
            new-object psobject -Property @{SubscriptionID = $r.Groups["SubscriptionID"]; ResourceGroup = $r.Groups["ResourceGroup"]; ObjectName = $element.name; type = $element.type; location = $element.location}
        } 
    
    if ($VMOnly.IsPresent){
        $objectsFound | where {($_.type -eq 'Microsoft.ClassicCompute/virtualMachines')} | % {& $typesToFilter[$_.type] $_.SubscriptionID $_.ResourceGroup $_.ObjectName}
    }
    else{
        $objectsFound | where {($_.type -in $typesToFilter.Keys)} | % {& $typesToFilter[$_.type] $_.SubscriptionID $_.ResourceGroup $_.ObjectName}}
}
}
```

**Comment by markcowl** [comment]
@devigned this seems like a useful api to include by default in typed and untyped rm clients, and a good list behavior for some scenarios.  I wonder about the scaling, though

**Comment by eosfor** [comment]
@markcowl meantime i did some research and came up with this: https://eosfor.wordpress.com/2015/11/02/how-to-search-for-object-in-azure/

it would be good to have this as part part of rm cmdlets as it is not really a good idea to extend existing one with additional parameters ). They should be there by default.

**Comment by devigned** [comment]
@vivsriaus @ravbhatnagar what do you think about adding this into resource manager?

**Comment by eosfor** [comment]
@devigned @vivsriaus  @ravbhatnagar That would be great to have, but David, may i ask you to shed some light on that search API please. Really curios, and may be really useful )

**Comment by devigned** [comment]
@eosfor that really isn't my area of expertise and I wouldn't want to lead you down a dark path. I'd leave that more to @vivsriaus and @ravbhatnagar who are on the Resource Manager team and could speak to that in more detail.

**Comment by eosfor** [comment]
Hello @vivsriaus, @ravbhatnagar may i ask you to shed some light on that search API please. Really curios, and may be really useful )

many thanks

**Comment by ravbhatnagar** [comment]
@eosfor - By the search API, are you referring to the $filter query expression that is used in the URI? If yes, it is a commonly used option in the OData query system which is used to obtain a subset of results from a collection. You can find more details on it here - http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#FilterSystemQueryOption

**Comment by ravbhatnagar** [comment]
We dont plan to support this natively in RM cmdlets at this time. hence closing this for now. Please let me know if this is blocking you though.
