### ISSUE TITLE
Get-AzCosmosDBCassandraTable does not return schema for table

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11312]
Get-AzCosmosCassandraTable output has .Resource.Schema but this is empty for existing keyspace and table.

$table = Get-AzCosmosDBCassandraTable -ResourceGroupName $resourceGroupName -AccountName $accountName -KeyspaceName $keyspaceName -Name $tableName

$table.Resource.Schema # Shows headers only, no data

Corresponding az CLI command run against the same Cosmos DB account/keyspace/table correctly returns full schema including cluster keys, partition keys, and columns:

az cosmosdb cassandra table show -g myResourceGroup -a myaccount -k myKeyspace -n myTable

**Comment by MehaKaushik** [comment]
Thanks for notifying, targeting S168.

**Comment by MehaKaushik** [comment]
Addressed in https://github.com/Azure/azure-powershell/pull/11388
