### ISSUE TITLE
(Get-AzVM).InstanceView returns null. -Status doesn't

### ISSUE THREAD

**Issue by DanteNahuel** [Azure/azure-powershell#11315]
## Description
(Get-AzVM).InstanceView property returns null.
No error, no issue, nothing. Just empty.
On the other hand, a
-status
flag returns the InstanceView of the VM.

## Steps to reproduce
```
$vm = get-azvm -name "vmname" -resourcegroupname "rg"
$instanceview = $vm.instanceView

$instanceview -eq $null
True

$vm = get-azvm -name "vmname" -resourcegroupname "rg" -status

$instanceview -eq $null
False

```
## Expected Behaviour

A property of the VM called InstanceView should return the InstanceView JSON that you get from using the REST API GET Call.
`
GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/instanceView?api-version=2019-07-01
`

## Proposed Solution/Workaround
The return of
`Get-AzVM -Name "name" -Resourcegroupname "rg" -Status`
is the expected InstanceView return and could be redirected to it, maybe?

## Other Data
I'm using lastest Az Module.
This happens both in Powershell 7 and in Powershell 5.1

**Comment by dingmeng-xue** [comment]
Cmdlet don't include InstanceView properties. Involve Compute team.

**Comment by Drewm3** [comment]
@DanteNahuel, I believe you should only get the model view when you use Get-AzVM without the "-status" flag, and you only get the instances view when you include "-status". Are you getting both instance and model views returned for one of the calls?

**Comment by DanteNahuel** [comment]
@drewm3 
I'm not getting anything when I try to retrieve the InstanceView like this:
$vm = get-azvm
$vm.instanceview

I do, however, get the instance view when I use the -status flag.

**Comment by Drewm3** [comment]
@DanteNahuel, I have verified with the cmdlet owners that the behavior you are seeing is the expected behavior. The cmdlet will return either the model view or the instance view, but it is not expected to return both. 

I have asked @hyonholee to update the description of the cmdlet to make the behavior clear that only the model or instance view will be returned based on the inclusion of the '-status' flag

**Comment by DanteNahuel** [comment]
@Drewm3 While I don't agree on that, it seems there's nothing I can do about it, but thank you for all anyway!
Closing this.

**Comment by aledeniz** [comment]
Can we have a public chat with the owner of the cmdlet?
The behaviour of Get-AzVM gets me crazy, I would like a number of design decision publicly clarified.
