### ISSUE TITLE
Get-AzADUser throws syntax error when DisplayName contains a quote

### ISSUE THREAD

**Issue by cveld** [Azure/azure-powershell#11317]
Version: 3.6.1

Repro step:
`Get-AzADUser -DisplayName 'Carl in ''t Veld'`

Results in:
`Get-AzADUser : Syntax error at position 26 in 'displayName eq 'Carl in 't Veld''.`

Expected behavior:
A successful retrieval of an ADUser object.

**Comment by dingmeng-xue** [comment]
Will be fixed in the upcoming release. The workaround is adding another single quote
```
Get-AzADUser -DisplayName 'Carl in ''''t Veld'
```
