### ISSUE TITLE
Connect-AzAccount: Guest User Login with -Tenant <tenant>.onmicrosoft.com Fails

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#11316]
When logging in via `Connect-azaccount -tenant <tenant>.onmicrosoft.com` as a B2B guest account (with Azure Rights), it prompts as normal for the login (with the customer logo), redirects to my tenant (with my logo), and I log in and the window closes, but then it repopens and bounces me to the general login, and when I log in, the context is my tenant.

If I do `Connect-azaccount -tenantid <tenantGUID>`, then it works as expected.

General Prompt I get bounced to:
![image](https://user-images.githubusercontent.com/15258962/76655274-2874da80-652a-11ea-8b84-064b6405181b.png)

**Comment by dingmeng-xue** [comment]
This is unknown limitation that current API used fetching tenant information is very old. The tenant directory is not returned. This issue will be addressed once we upgrade the version of API.

**Comment by dingmeng-xue** [comment]
#9838 is related.

**Comment by mikefrobbins** [comment]
#11543 Added a note to the tenant parameter about having to use a tenant ID instead of a tenant name when connecting with a business-to-business (B2B) account due to a limitation with the current API.

**Comment by JustinGrote** [comment]
@mikefrobbins I made this function which uses an unauthenticated API to resolve the tenant name to GUID. Could this be integrated as a helper function if Tenant Name is specified to perform resolution to tenant ID, thus solving this problem?

https://gist.github.com/JustinGrote/e8b51f0845813b933035c40a5390707e

**Comment by dcaro** [comment]
@JustinGrote since the issue has been created, we made several improvements on Az.Accounts including upgrade of the API mentioned above. We could not reproduce the issue with Az,Accounts 2.5.1, can you give it a try and confirm the status?

**Comment by JustinGrote** [comment]
@dcaro seems to be fixed at least on 2.5.1
