### ISSUE TITLE
Wasted 1 1/2 days so far

### ISSUE THREAD

**Issue by Virtualserve** [Azure/azure-powershell#11326]
Hi,

I followed the instructions in this document correcting all the errors as I went through the whole process, there appears to be an issue with the text being copied and pasting into Powershell.

I am now completely stuck from the section Create client  certificate I think this has worked but when I run the Configure VPN client I have an issue with the PSSession computer name, this is a domain joined laptop but it just stops at the session I am the domain Admin so in theory this should work.

So I downloaded  the VPN client from the portal and I can connect, I get an IP address from the Gateway  but I do not know if the vpn is working or not as I can connect to the storage account using the unc and key whether the vpn is running or not

If you are not a Powershell person this is incredibly hard going process.

**Comment by dingmeng-xue** [comment]
Hi @Virtualserve , could you give us sample script about your issue? In addition, if required, we need module versions you are using and debug out if there is any error. Debug out can be turned on via `$DebugPreference="Continue"`

**Comment by Virtualserve** [comment]
Hi,

Sorry for the delay in getting back to you but I have been trying to
resolve this myself but have deleted the storage account resource groups etc

This Document just seems over complicated

So when I create the resource group and the Storage account file share  etc
I can access the files so my isp is not blocking

but once I start to follow the process the storage account is no longer
accessible and even from the Azure portal so something is not working
correctly

So everything after Configure the VPN client
<https://docs.microsoft.com/en-us/azure/storage/files/storage-files-configure-p2s-vpn-windows#configure-the-vpn-client>

Just does not work how I expected, If I manually install the VPN from the
download the VPN connects to Azure I believe but I cannot see the
connection with Azure
I have not included any scripts as they are lifted off the link I indicated.

Steve Smith






(: 07462599556

* *steve@virtualserve.biz* <steve@virtualserve.biz>

ü*    http://www.virtualserve.biz <http://www.virtualserve.biz/>*



*Confidentiality Notice*

*This email and any attachments are confidential and legally privileged and
intended solely for the use of the individual or entity to whom they are
addressed. If you are not the named addressee, please telephone +44(0) 1273
387778 Views expressed are those of the individual sender, except where
stated as those of Virtualserve. There will be no liability for damage
arising in any way from receipt or use thereof.*

**Comment by dcaro** [comment]
@Virtualserve thanks for reporting this issue, it looks like your feedback is related to the article in the documentation page and in order to send it the right team, I would recommend that you open an issue at the [bottom of the page](https://docs.microsoft.com/en-us/azure/storage/files/storage-files-configure-p2s-vpn-windows#see-also) and click on the "This page" button.

**Comment by dcaro** [comment]
@Virtualserve closing this issue as this is related to the documentation. Feel to add a comment if you feel otherwise.
