### ISSUE TITLE
New-AzCosmosDBAccount with -ApiKind MongoDB creates 3.2

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11338]
New-AzCosmosDBAccount with -ApiKind MongoDB creates 3.2 account even though docs say 3.6 is default for new account, and there is no way to specify API version to the cmdlet.

See https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-feature-support-36#protocol-support for language stating all new accounts are compatible with 3.6.

Note: Azure CLI (az cosmosdb create --kind MongoDB also creates a 3.2 account. Azure portal create experience defaults to 3.6.

**Comment by MehaKaushik** [comment]
The feature is not supported by our Resource Provider yet. Hence not in powershell.

**Comment by MehaKaushik** [comment]
@plzm  Once the Resource Provider supports ServerVersion in MongoProperties, this would be taken care by our backend, no changes need to be done in the Powershell repo or the .NET SDK for this ask.
