### ISSUE TITLE
New-AzCosmosDBAccount does not support creation of Gremlin, Cassandra, or Table accounts.

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11337]
Can New-AzCosmosDBAccount be updated to support all account types?

**Comment by MehaKaushik** [comment]
Thanks for reporting this, it has not been scoped out yet, would update here, once we have an ETA.

**Comment by MehaKaushik** [comment]
Addressed in https://github.com/Azure/azure-powershell/pull/11388
