### ISSUE TITLE
Get-AzStorageBlob: Container name 'Microsoft.WindowsAzure.Commands.Common.Storage.ResourceModel.AzureStorageContainer' is invalid. Valid names start and end w ith a lower case letter or a number and has in between a lower case letter, number or dash with no consecutive dashes and is 3 through 63 characters long.

### ISSUE THREAD

**Issue by muthusankar54** [Azure/azure-powershell#11332]
## Description

  $StorageContext = New-AzureStorageContext -StorageAccountName 'muthudev' -StorageAccountKey 'QMv77eoYUQcnb1QfvGjsGOd+gg=='
    $Container = Get-AzureStorageContainer -Name 'public' -Context $StorageContext  
	
    $blobs = Get-AzureStorageBlob -Container $Container -Context $StorageContext

after the public container, i have 2 folders inside this, called web and mob. i need to go inside web folder and delete the blob but am facing below issue.. i can able to access upto public container,

## Cost
Get-AzStorageBlob: Container name 'Microsoft.WindowsAzure.Commands.Common.Storage.ResourceModel.AzureStorageContainer' is invalid. Valid names start and end w
ith a lower case letter or a number and has in between a lower case letter, number or dash with no consecutive dashes and is 3 through 63 characters long.

**Comment by muthusankar54** [comment]
storage  ==>  public  [container]  ==>  inside public 2 folders will be there                                                    

 1. Web
 2. Mob

i need to access the blob items what are things will be there inside Web folder

**Comment by blueww** [comment]
@muthusankar54 
1.  Please hide the account key in the issue. Please renew the key of the storage account after that to avoid security issues.

2. In `Get-AzureStorageBlob`,  `-Container` expect the container name instead of container object. If you want to list all blobs in "web" folder of container "public", you can run:
```powershell
PS C:\WINDOWS\system32> Get-AzureStorageBlob -Container 'public' -Prefix 'web' -Context $StorageContext


   Container Uri: https://***.blob.core.windows.net/public

Name                 BlobType  Length          ContentType                    LastModified         AccessTier SnapshotTime         IsDeleted 
----                 --------  ------          -----------                    ------------         ---------- ------------         --------- 
web/test.txt         BlockBlob 2097152         application/octet-stream       2020-03-16 11:40:03Z Hot                             False     
web/test2.txt        BlockBlob 2097152         application/octet-stream       2020-03-16 11:40:10Z Hot 
```
If you want to delete them, you can just:
```powershell
Get-AzureStorageBlob -Container 'public' -Prefix 'web' -Context $StorageContext | Remove-AzStorageBlob -Force
```

3. You might use a very old Azure Powershell, with the old cmdlets name. In the latest Powershell module Az.Storage, the cmdlet names has changed (mostly "Azure"/"AzureRm" -> "Az") You might can install the lastest Az.Storage module to get all the new features and fixes

**Comment by muthusankar54** [comment]
Hi @blueww , Thanks for the useful information when i tried to delete the particular blob content using below command facing issues:

**Command:**
` Get-AzureStorageBlob -Container 'public' -Prefix 'web' Muthu__202002351202480683 -Context $StorageContext | Remove-AzStorageBlob -Force`


**Error:**

Get-AzStorageBlob: A positional parameter cannot be found that accepts argument Muthu__202002351202480683

**Comment by muthusankar54** [comment]
@blueww 

 when I tried with below command

**Command:**

  `Get-AzureStorageBlob -Container public' -Prefix 'web'  -Context $StorageContext | Remove-AzureStorageBlob  -Blob Muthu__202002351202480683  -Force`

**Error:**

  Remove-AzStorageBlob: The input object cannot be bound because it did not contain the information required to bind all mandatory parameters:  CloudBlobContainer

**Comment by blueww** [comment]
@muthusankar54 
What do you want to do with the cmdlet? 
As you have already listout the blobs with "Get-AzureStorageBlob -Container public' -Prefix 'web' -Context $StorageContext", when pipeline it to Remove-AzureStorageBlob, the blobs already has blob name, so you should not input "-blob" again. (as you input "-blob", the missing parameter is container, so Remove-AzureStorageBlob try to fins container from the pipeline input and not found, so report the error ).

If you just want to remove a blob with dir + name "web/Muthu__202002351202480683", you can:
`Remove-AzureStorageBlob -Container 'public' -blob 'web/Muthu__202002351202480683' -Context $StorageContext  -Force`

If you want to remove blobs in dir "Web", with the name suffix "Muthu__202002351202480683", you can:
Get-AzureStorageBlob -Container 'public' -Prefix 'web' -Context $StorageContext | where {$_.Name -like "*Muthu__202002351202480683"} |Remove-AzureStorageBlob  -Force

**Comment by muthusankar54** [comment]
@blueww Thanks a lot for sharing useful information, it's working fine now :) .. How to schedule runbooks each 10minutes need to run but options are available for Hour, Weekly and monthly then yearly?

**Comment by blueww** [comment]
@muthusankar54 
Thanks for close this issue!
This repo is for Powershell, so it's not proper place for runbook questions.

There are some runbook doc like https://docs.microsoft.com/en-us/azure/automation/automation-quickstart-create-runbook
You might can try to raise your question there.
