### ISSUE TITLE
What is the -TenantLevel parameter used for on the Get-AzResourceLock cmdlet?

### ISSUE THREAD

**Issue by theheatDK** [Azure/azure-powershell#11335]
## Description
Hi,
I cannot find any examples of how the -TenantLevel parameter is used for the Get-AzResourceLock cmdlet.
The documentation just states "Indicates that this cmdlet operates at the tenant level."
I have had a quick look at the resource lock REST APIs and I cannot find anything that mentions tenant level. What does it do?
Regards Peter

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
It needs service team to explain it further.

**Comment by rthorn17** [comment]
Hi- @theheatDK  Let me research and get back to you on this.  Thanks

**Comment by ifeoluwaokunoren** [comment]
@theheatDK you're correct - [resource (management) locks](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources) are only valid at the Subscription, Resource Groups, Resource scopes. 
I'd add this to our backlog, so we can update the command to remove the -TenantLevel parameter since it can be used in the context of this command.

Thanks

**Comment by theheatDK** [comment]
Thanks @ifeoluwaokunoren 
I assume that you are aware the parameter is used in several of the lock cmdlets? (New-AzResourceLock, Remove-AzResourceLock...)

**Comment by theheatDK** [comment]
Hi @ifeoluwaokunoren,
You never answered my question from 19 of Marts? :-)
Should I close the issue?
Regards Peter

**Comment by ifeoluwaokunoren** [comment]
Hi @theheatDK,
Thanks so much for following up.
Yes, the fix would address the other lock cmdlets as well.
I'd close this issue once we check-in the fix.

Thanks :)

**Comment by theheatDK** [comment]
Super. Thanks @ifeoluwaokunoren

**Comment by ifeoluwaokunoren** [comment]
PR fix: https://github.com/Azure/azure-powershell/issues/11335
