### ISSUE TITLE
Set-AzCosmosDBGremlinGraph does not update graph throughput.

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11336]
1. Set-AzCosmosDBGremlinGraph for a NEW graph does correctly set the specified throughput. Tested with both minimum (400) and >minimum (600). In both cases, NEW graphs were created with the specified throughput. This works even if the database is also created with its own shared throughput.

2. Set-AzCosmosDBGremlinGraph for an EXISTING graph does not update the throughput IF the database has shared throughput, and does not return any errors or other indications why graph throughput was not updated. NOTE that Set-AzCosmosDBGremlinGraph DOES correctly update graph throughput if the database does NOT have shared throughput provisioned. The Azure portal (Data Explorer) allows for graph throughput to be updated whether or not the database has shared throughput provisioned, so is expectation reasonable that Set-AzCosmosDBGremlinGraph also updates graph throughput whether or not database has throughput provisioned? Sample code which does not update throughput:

$graph = Get-AzCosmosDBGremlinGraph -ResourceGroupName $resourceGroupName -AccountName $accountName -DatabaseName $databaseName -Name $graphName -Detailed

Set-AzCosmosDBGremlinGraph -ResourceGroupName $resourceGroupName -AccountName $accountName -DatabaseName $databaseName -Name $graphName -Throughput $newRUsGraph -PartitionKeyKind $graph.Resource.PartitionKey.Kind -PartitionKeyPath $graph.Resource.PartitionKey.Paths

3. Azure CLI DOES correctly update throughput for an EXISTING graph. Sample code which was tested successfully for an existing graph with 600 RU/s to change to 800 RU/s:

az cosmosdb gremlin graph throughput update -g "cosmos" --account-name "cdb-gr-kpra" --database-name "db1" --name "g1" --throughput 800

**Comment by MehaKaushik** [comment]
Thanks for notifying this, working on it.

**Comment by plzm** [comment]
Can no longer reproduce this issue as of Az.CosmosDB 0.1.3. 

Tested/confirmed Set-AzCosmosDBGremlinGraph correctly updates existing graph's provisioned dedicated throughput when database also has shared provisioned throughput. Tested/confirmed both graph scale up (increase RU) as well as scale down (decrease RUs).

Thank you - closing issue.
