### ISSUE TITLE
Set-AzCosmosDBMongoDBCollection requires -Shard parameter but docs lists it as optional

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11340]
https://docs.microsoft.com/en-us/powershell/module/az.cosmosdb/set-azcosmosdbmongodbcollection

-Shard is not listed as required parameter. When attempting to run Set-AzCosmosDBMongoDBCollection against an existing collection with all required params, get error message.

Set-AzCosmosDBMongoDBCollection -ResourceGroupName $resourceGroupName -AccountName $accountName -DatabaseName $databaseName -Name $collectionName -Throughput $newRUsCollection

Line |
  26 |      Set-AzCosmosDBMongoDBCollection -ResourceGroupName $resourceGroup …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Long running operation failed with status 'Failed'. Additional Info:'Message: {"code":"BadRequest","message":"Provisioned throughput collection should have
     | a partition key\r\nActivityId: cd9d0dba-0d05-43de-9bd4-0a1dcf261402, Microsoft.Azure.Documents.Common/2.10.0"}, Request URI: /dbs/db1/colls, RequestStats: 
     | , SDK: Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0,
     | Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0,
     | Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0'

---------------------------
---------------------------

Attempting to retrieve collection using:
$collection = Get-AzCosmosDBMongoDBCollection -ResourceGroupName $resourceGroupName -AccountName $accountName -DatabaseName $databaseName -Name $collectionName

and then passing $collection.Resource.ShardKey to Set-AzCosmosDBMongoDBCollection fails:

Set-AzCosmosDBMongoDBCollection -ResourceGroupName $resourceGroupName -AccountName $accountName -DatabaseName $databaseName -Name $collectionName -Throughput $newRUsCollection -Shard $collection.Resource.ShardKey

Set-AzCosmosDBMongoDBCollection: C:\Users\paelaz\Code\plzm.github\azure-docs-powershell-samples\cosmosdb\mongodb\ps-mongodb-ru-update.ps1:29:16
Line |
  29 |          -Shard $collection.Resource.ShardKey
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Shard'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

**Comment by MehaKaushik** [comment]
Thanks @plzm for reporting this, working on it. Targeting the S168.
