### ISSUE TITLE
Missing Parameter for BrowserAgent

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#11362]
Outdated browser agents are prohibited in many IT infrastructures on their firewall. The `Connect-AzAccount` cmdlet uses such a browser agent

`"Technology/Internet" DENIED - http.proxy "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; Win64; x64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)" `

I painfully miss a parameter where I can specify the desired browser agent.

**Comment by dingmeng-xue** [comment]
@Gill-Bates, it is due to old version of AD lib. We will replace it using new Microsoft Authentication Library soon. Meanwhile, PowerShell Core is recommended.

**Comment by dingmeng-xue** [comment]
Close it and link to #10259
