### ISSUE TITLE
Updated help.xml for ARM 1.0 Preview / AzureRM.Tags

### ISSUE THREAD

**Issue by TaraMeyer** [Azure/azure-powershell#1136]
@Azure/adx-sdk-team  - The newly authored and updated help.xml for the AzureRM.Tags is available here:

\\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\RMAzure_Tags\2015-10-20.09_38_28\OutPut\OnBox

Can you please add this to the code as it's the latest and greatest authored help file:

![capture](https://cloud.githubusercontent.com/assets/14112499/10614403/f4ee87dc-770e-11e5-8fae-6dc4fc2eb97a.PNG)

**Comment by TaraMeyer** [comment]
@Azure/adx-sdk-team  - Here is the same attached as a text file.  You will have to rename from .txt to .xml.

**Comment by markcowl** [comment]
@TaraMeyer Can you submit a PR for this change?

**Comment by devigned** [comment]
@markcowl we are going to take care of this. @TaraMeyer is on the content development team. We are a little better equipped to take care of the diff. In fact, I'll script it up and write up a short 'how to'.
