### ISSUE TITLE
Installer Az-Cmdlets-3.5.0.32097-x64.msi ended prematurely

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#11361]
On Windows 2019 Datacenter Edition, the installer `Az-Cmdlets-3.5.0.32097-x64.msi` failed during installation

There is no error Log or anything else what I could provided to investiate.

Version of the OS: 10.0.17763 Build 17763

![grafik](https://user-images.githubusercontent.com/25774289/76956586-a19e7400-6914-11ea-8d53-b55b5cfe73a3.png)

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will look into it.

**Comment by Gill-Bates** [comment]
@dingmeng-xue PSGallery is not an option. Machine is isolated from the Internet.
Fun Fact: Current Version `Az-Cmdlets-3.6.1.32413-x64.msi` is also affected from this bug!

**Comment by dingmeng-xue** [comment]
@Gill-Bates , could you share out put of below command?
```
Dism /online /Get-FeatureInfo:NetFx3
```

**Comment by dingmeng-xue** [comment]
Close it as duplicate with #11361

**Comment by dingmeng-xue** [comment]
No idea why it is opened. @ankushbindlish2 , is there new information which is different from #11542?

**Comment by dingmeng-xue** [comment]
Thank @ankushbindlish2 for your confirmation. We will follow up #11542
