### ISSUE TITLE
When Set-AzCosmosDBSqlContainer is run against a SQL container that has a conflict resolution policy in order to update something else (e.g. RUs), fails with error that updating conflict resolution policy is not currently supported, even though Set-AzCosmosDBSqlContainer shows all conflict resolution policy params as optional.

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11383]
This error does not happen when the targeted SQL container does NOT have a custom conflict resolution policy.

Set-AzCosmosDBSqlContainer currently has required parameters PartitionKeyKind and PartitionKeyPath, even for an update and even though partition key path cannot be changed. Does the cmdlet also require conflict resolution policy params even for an update of other container properties?

Notes:
- I tried adding conflict resolution policy (same as when creating) for an update. This container also had a unique key. Adding conflict resolution policy to the update yields this error:
The unique index cannot be modified. To change the unique index, remove the collection and re-create a new one.
- Also adding the same unique key policy as on container create to the update, now Set-AzCosmosDBSqlContainer was able to make a different update (throughput).
- So it seems this cmdlet, for an update to an existing container, requires most of the same info to be specified as when creating the container. Is this expected behavior?

Reference:
https://docs.microsoft.com/powershell/module/az.cosmosdb/set-azcosmosdbsqlcontainer

Sample:
Set-AzCosmosDBSqlContainer -ResourceGroupName myResourceGroup -AccountName cosmos-bjwr1ax -DatabaseName myDatabase -Name myContainer -PartitionKeyKind Hash -PartitionKeyPath "/id" -Throughput 500

Set-AzCosmosDBSqlContainer: Long running operation failed with status 'Failed'. Additional Info:'Message: {"code":"BadRequest","message":"Message: {\"Errors\":[\"Updating conflict resolution policy is currently not supported\"]}\r\nActivityId: 63c6a907-d750-4e30-8dc5-5177a00196a2, Request URI: /apps/814e7582-0a8b-498b-8d4f-92263e029030/services/778e7d18-7817-46cd-b4c0-0e037cc39c12/partitions/6b2a2915-8bfa-4ead-81db-463a9c6e52ff/replicas/132291885968558841p, RequestStats: \r\nRequestStartTime: 2020-03-20T16:13:40.7301671Z, RequestEndTime: 2020-03-20T16:13:40.7301671Z,  Number of regions attempted:1\r\nResponseTime: 2020-03-20T16:13:40.7301671Z, StoreResult: StorePhysicalAddress: rntbd://10.0.0.22:11300/apps/814e7582-0a8b-498b-8d4f-92263e029030/services/778e7d18-7817-46cd-b4c0-0e037cc39c12/partitions/6b2a2915-8bfa-4ead-81db-463a9c6e52ff/replicas/132291885968558841p, LSN: 9, GlobalCommittedLsn: 9, PartitionKeyRangeId: , IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: -1#9, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Replace\r\n, SDK: Microsoft.Azure.Documents.Common/2.10.0"}, Request URI: /dbs/myDatabase/colls/myContainer, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0'

**Comment by MehaKaushik** [comment]
Targeting S168.

**Comment by MehaKaushik** [comment]
To address issues like this in the Set-AzCosmosDB* cmdlets, we are introducing New-AzCosmosDB* and Update-AzCosmosDB* cmdlets which will have dedicated tasks of creating new and updating the existing resource objects.
