### ISSUE TITLE
AzS.Storage.Admin - 1.8.1 -ErrorAction issue

### ISSUE THREAD

**Issue by mattmcspirit** [Azure/azure-powershell#11384]
**Issue with AzS.Storage.Admin - 1.8.1 -ErrorAction issue**
DIscussed with @bganapa offline.

Issue: Get-AzsStorageQuota is not obeying the -ErrorAction parameter, for instance, if i run:

Get-AzsStorageQuota -Name "Blah" -Location $azsLocation -ErrorAction SilentlyContinue -Verbose

It raises an exception, however if i run:

Get-AzsComputeQuota -Name "Blah" -Location $azsLocation -ErrorAction SilentlyContinue -Verbose

it fails silently, as expected, assuming "Blah" does not exist in both cases

Thanks!

**Comment by bganapa** [comment]
Thanks!.  We will fix it in the Az modules to start with.

**Comment by bganapa** [comment]
This is fixed in the recent versions of Azs.Storage.Admin module
