### ISSUE TITLE
Get-AzCosmosDBCassandraTableThroughput does not emit ThroughputSettingsResult like all other API Get-AzCosmosDB*Throughput cmdlets do

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11380]
Get-AzCosmosDBCassandraTableThroughput does not emit PSThroughputSettingsResults, unlike all the other API Get-AzCosmosDB*Throughput cmdlets. Compare the outputs below:

PS C:\Users\paelaz\Code\plzm.github\azure-docs-powershell-samples\cosmosdb> Get-AzCosmosDBCassandraTableThroughput -ResourceGroupName myResourceGroup -AccountName pz-cdb-cass -KeyspaceName mykeyspace -Name mytable

Resource : Microsoft.Azure.Management.CosmosDB.Models.ThroughputSettingsGetPropertiesResource
Id       : /subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourceGroups/myResourceGroup/providers/Microsoft.DocumentDB/databaseAccounts/pz-cdb-cass/cassandraKeysp
           aces/mykeyspace/tables/mytable/throughputSettings/default
Name     : 8v5a
Type     : Microsoft.DocumentDB/databaseAccounts/cassandraKeyspaces/tables/throughputSettings
Location :
Tags     :

PS C:\Users\paelaz\Code\plzm.github\azure-docs-powershell-samples\cosmosdb> Get-AzCosmosDBGremlinGraphThroughput -ResourceGroupName myResourceGroup -AccountName pz-cdb-gremlin -DatabaseName myDatabase -Name myGraph

Name                : Lrkw
Id                  : /subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourceGroups/myResourceGroup/providers/Microsoft.DocumentDB/databaseAccounts/pz-cdb-gremlin/
                      gremlinDatabases/myDatabase/graphs/myGraph/throughputSettings/default
Throughput          : 400
MinimumThroughput   : 400
OfferReplacePending :

PS C:\Users\paelaz\Code\plzm.github\azure-docs-powershell-samples\cosmosdb> Get-AzCosmosDBMongoDBCollectionThroughput -ResourceGroupName myResourceGroup -AccountName pz-cdb-mongo -DatabaseName myDatabase -Name myCollection

Name                : yuKT
Id                  : /subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourceGroups/myResourceGroup/providers/Microsoft.DocumentDB/databaseAccounts/pz-cdb-mongo/mo
                      ngodbDatabases/myDatabase/collections/myCollection/throughputSettings/default
Throughput          : 400
MinimumThroughput   : 400
OfferReplacePending :

PS C:\Users\paelaz\Code\plzm.github\azure-docs-powershell-samples\cosmosdb> Get-AzCosmosDBSqlContainerThroughput -ResourceGroupName myResourceGroup -AccountName pz-cdb-sql -DatabaseName myDatabase -Name myContainer

Name                : nxw-
Id                  : /subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourceGroups/myResourceGroup/providers/Microsoft.DocumentDB/databaseAccounts/pz-cdb-sql/sqlD
                      atabases/myDatabase/containers/myContainer/throughputSettings/default
Throughput          : 400
MinimumThroughput   : 400
OfferReplacePending :

PS C:\Users\paelaz\Code\plzm.github\azure-docs-powershell-samples\cosmosdb> Get-AzCosmosDBTableThroughput -ResourceGroupName myResourceGroup -AccountName pz-cdb-table -Name myTable

Name                : fl1K
Id                  : /subscriptions/e61e4c75-268b-4c94-ad48-237aa3231481/resourceGroups/myResourceGroup/providers/Microsoft.DocumentDB/databaseAccounts/pz-cdb-table/ta
                      bles/myTable/throughputSettings/default
Throughput          : 400
MinimumThroughput   : 400
OfferReplacePending :

**Comment by MehaKaushik** [comment]
Fix in PR https://github.com/Azure/azure-powershell/pull/11388
