### ISSUE TITLE
Azure runbook error with Get-AzureRmVM -Status

### ISSUE THREAD

**Issue by jmarti45** [Azure/azure-powershell#11395]
Hello,

Im wirting an script and if I execute from powershell works ok but from azure runbook give the following error:

Get-AzureRmVM : Parameter set cannot be resolved using the specified named parameters.
At line:49 char:31
+             $vmStatus = $vm | Get-AzureRmVM -Status
+                               ~~~~~~~~~~~~~~~~~~~~~

Any Idea?

**Comment by dingmeng-xue** [comment]
Please list module versions used in runbook environment and your powershell environment.

**Comment by dingmeng-xue** [comment]
@jmarti45 , is there any update?

In addition, Get-AzureRmVM doesn't support piping $vm. you need to use name of $vm as one input parameter like something as below code.
```
$vmStatus = Get-AzureRmVM -Name $vm.name -Status
```

**Comment by dingmeng-xue** [comment]
@jmarti45 , is your issue disappeared?

**Comment by dingmeng-xue** [comment]
Close this issue. @jmarti45, please contact us if you still meet the problem.
