### ISSUE TITLE
Get-azmanagement group

### ISSUE THREAD

**Issue by nomie788** [Azure/azure-powershell#11406]
The commanlet Get-AzManagementGroup -GroupName 'Contoso' is not recognizing the MGM group Name which is also the display name. the commandlet is recognizing the group id instead of the name. 
Get-AzManagementGroup -GroupName 'Grpname'  doesn't work
 Get-AzManagementGroup -GroupName 'GroupID' - works but is the group id and not the name.

**Comment by dingmeng-xue** [comment]
thanks for reporting. Doc and parameter name make confusion. Involve resource team to evaluate which name is better.

**Comment by rthorn17** [comment]
@nomie788 Thanks for reporting. We are aware of this and working on fixing this. The PowerShell module currently has two fields GroupName and GroupDisplayName. We will be making updates to make this consistent through all the interfaces and I am tracking this in our backlog. Thanks
