### ISSUE TITLE
webapp:In Publish-AzWebApp support publishing zip files for 'run as package' like az cli

### ISSUE THREAD

**Issue by timpoth** [Azure/azure-powershell#11410]
For AZ Cli you support uploading a zip package to be used to run app from package. https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest#az-webapp-deployment-source-config-zip 
however it doesnt look like thats supported on the powershell cmdlet side of things. as we do 99% of our stuff with powershell it would be nice if it worked for this and we didnt have to use two different tool sets

**Comment by dingmeng-xue** [comment]
Involve WebApp team to evaluate this feature.

**Comment by panchagnula** [comment]
az CLI doesn't support run as package either - we have an open issue on CLI to support run as package. Zip deploy is the current mechanism used in both commands

**Comment by panchagnula** [comment]
closing this since there both commands are identical at this point
