### ISSUE TITLE
Error renaming ADLS Gen2 folder using Powershell script

### ISSUE THREAD

**Issue by manomar01** [Azure/azure-powershell#11419]
## Description
$rgName = ‘rg1 
$storageName = ‘str1 
$storageAccount = Get-AzstorageAccount -ResourceGroupName $rgName -AccountName $storageName $storagecontext= $storageAccount.Context 
Move-AzDataLakeGen2Item -FileSystem "fs1" -Path "landing" -DestFileSystem "fs1" -DestPath "landing0322" -Context $storagecontext

Error:
Move-AzDataLakeGen2Item : The request contains an invalid combination of headers. HTTP Status Code: 400 - HTTP Error Message: The request contains an invalid combination of headers. At line:15 char:1 + Move-AzDataLakeGen2Item -FileSystem "fs1" -Path "landing" -DestFileS ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Move-AzDataLakeGen2Item], StorageException + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.MoveAzDataLakeGen2ItemCommand

**Comment by dingmeng-xue** [comment]
Involve Storage team to look into this issue.

**Comment by blueww** [comment]
@manomar01 
Which version of Powershell Az.Storage module do you use?
Would you like to use the latest Az.Storage 1.13.1-preview, it should can print the requestID, and it can help us to investigate what the error is.
Else, would you like to run following command just after the error happen? And we might can also see the request ID in it.

```powershell
$Error[0].Exception.ToString()
$Error[0].Exception.InnerException.ToString()
```
If there's still no request ID, would you please share the storage account name and the error happen time (UTC), this can also help to find the related request on server

**Comment by manomar01** [comment]
Hi Wei,
I tried to load Az.storage 1.13.0 and ran and still same error. Can you ping me in Teams so I can provide the storage account?

Thanks,
Mano

**Comment by blueww** [comment]
@manomar01 
I don't know your ID on teams, so can't ping you on teams. 
And for 1.13.1-preview, per my before comments, it's for more log. Would you please give the output of the failure cmdlets?
And please run the following 2 command just after the error in same PSH console and give me the output.

```
$Error[0].Exception.ToString()
$Error[0].Exception.InnerException.ToString()
```

If they can give enough information, we don't need account name and time. else please give me your teams ID so I can ping you. (or you can ping me or mail me : weiwei@microsoft.com)

**Comment by manomar01** [comment]
My id Manoharan Mariappan <manomar@microsoft.com>. If you can ping me now, we can quickly have a working session.

**Comment by blueww** [comment]
@manomar01
The error is from server, and I have send the related server log to feature team to investigate it.
Will update you if feature team has any responds.

**Comment by manomar01** [comment]
Hi Wei,
Thanks for your call working on the issue. After you provided the new Az.Storage module (1.13.3) , there was no error for the folder rename but I see that there are two folders in ADLS- one source folder and target folder name which I wanted to rename.
This should only have new folder ‘landing20200329’. Is it still in the process of moving the data? This folder has about 7TB data. Would it take longer to rename big folders?

[cid:image001.jpg@01D60610.DB3E39A0]

**Comment by blueww** [comment]
Close this issue since this is long time ago, and  this is actually a server issue and followed with mail.
