### ISSUE TITLE
DeploymentName does not match description

### ISSUE THREAD

**Issue by ghost** [Azure/azure-powershell#11413]
DeploymentName does not match following document. If we don't specify a deployment name, it will be expected the current time.
[New-AzDeployment](https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azdeployment?view=azps-3.6.1) 
> -Name
> The name of the deployment it's going to create. Only valid when a template is used. When a template is used, if the user doesn't specify a deployment name, use the current time, like "20131223140835".

However, I have confirmed that it will be template file name as below. Which one is correct?
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-subscription#deployment-commands
```
New-AzSubscriptionDeployment `
  -Location centralus `
  -TemplateUri "https://raw.githubusercontent.com/Azure/azure-docs-json-samples/master/azure-resource-manager/emptyRG.json" `
  -rgName demoResourceGroup `
  -rgLocation centralus
```
Output
```
Id                      : /subscriptions/****/providers/Microsoft.Resources/deployments/emptyRG
DeploymentName          : emptyRG
Location                : centralus
ProvisioningState       : Succeeded
Timestamp               : 2020/03/25 0:07:56
Mode                    : Incremental
TemplateLink            :
                          Uri            : https://raw.githubusercontent.com/Azure/azure-docs-json-samples/master/azure-resource-manager/emptyRG.json
                          ContentVersion : 1.0.0.1

Parameters              :
                          Name             Type                       Value
                          ===============  =========================  ==========
                          rgName           String                     demoResourceGroup
                          rgLocation       String                     centralus
                          tags             Object                     {}

Outputs                 :
DeploymentDebugLogLevel :
```

**Comment by dingmeng-xue** [comment]
Involve Resource service team to check if reference doc is not up-to-date.

**Comment by alex-frankel** [comment]
The New-AzDeployment doc you linked to is incorrect. We will get this fixed - thanks for reporting.

**Comment by bmoore-msft** [comment]
This s/b fixed now
