### ISSUE TITLE
Update-AzCosmosDBAccount does not enable IP firewall rules on an account to be removed

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11422]
Reference
https://github.com/Azure/azure-powershell/blob/master/src/CosmosDB/CosmosDB/CosmosDBAccount/UpdateAzCosmosDBAccount.cs#L175

For a scenario such as document at https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-vnet-service-endpoint#migrate-from-firewall-to-vnet, existing IP firewall rules need to be removed from a Cosmos DB account.

Currently Update-AzCosmosDBAccount only processes parameter -IpRangeFilter if its length is greater than zero.

Should Update-AzCosmosDBAccount permit an empty array -IpRangeFilter to be passed and remove existing IP filter rules? If not, how is removal of IP rules supported?

**Comment by MehaKaushik** [comment]
Targeting either S168 or S169.

**Comment by plzm** [comment]
The updated (0.1.3) version of Update-AzCosmosDBAccount still does not allow for an existing IpRangeFilter on an account to be removed entirely.

Azure portal scenario:
- Account has firewall rules; "Firewall and Virtual Networks" blade shows "Selected Networks" and various network rules
--- Get-AzCosmosDBAccount shows IpRangeFilter corresponding to portal
- To remove rules, switch to "All networks" and save
--- Get-AzCosmosDBAccount shows empty IpRangeFilter

When running Update-AzCosmosDBAccount to try to remove IpRangeFilter (i.e. switch to All Accounts), consistently get error message.

Can Update-AzCosmosDBAccount be used to remove IP filters from a Cosmos DB account and switch to "All Networks" similar to Azure portal?

**Comment by plzm** [comment]
![Update-AzCosmosDBAccount](https://user-images.githubusercontent.com/35011873/79126647-5ab66980-7d6e-11ea-91d5-2984efe81710.png)

**Comment by MehaKaushik** [comment]
Hey these changes would be reflected in the upcoming version, the current version of Az.CosmosDB was build before these changes were checked in. Upcoming version should be out in a week, would update here once it is.

**Comment by MehaKaushik** [comment]
0.1.4 released https://www.powershellgallery.com/packages/Az.CosmosDB/0.1.4
