### ISSUE TITLE
[New-AzPolicyAssignment] Assignment name length 24 problem

### ISSUE THREAD

**Issue by iceyokuna** [Azure/azure-powershell#11421]
## Description
New-AzPolicyAssignment is failed, when we assign the policy at "ManagementGroup" level with assignment name length more then 24 characters. 

However, its work!! when we assignment the policy at "Subscription" level with assignment name more than 24 characters.

If its because MS backend design, is there any reason behind that it work when we assign at subscription level, but not ManagementGroup level. Thanks

## Steps to reproduce

```powershell
New-AzPolicyAssignment -Name 'Test-PolicyAssignment-LenghtMorethan24' -PolicyDefinition "$policy definition" -Scope "$managementgroup"
```

## Error output
```
New-AzPolicyAssignment : The supplied PolicyDefinition object is invalid.
At line:1 char:1
+ New-AzPolicyAssignment -Name 'Test-PolicyAssignment-LenghtMorethan24' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [New-AzPolicyAssignment], PSInvalidOperationException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzurePolicyAssignmentCmdlet
```

**Comment by dingmeng-xue** [comment]
It needs service team's further explanation. Involve Resources team.

**Comment by kenieva** [comment]
Hi, the limit should be on the resource name due to a storage key requirement. This a limitation by design.

**Comment by iceyokuna** [comment]
Thank you. I know this limitation by design. 

But why it works when we assign it at "subscription level" but not "ManagementGroup level". And the whole Assignment ID for subscription level is even longer than Assignment ID of managementgroup level. ??  Thanks!
