### ISSUE TITLE
Unable to Connect-AzureAD with Az.Accounts imported under PS 7.0.

### ISSUE THREAD

**Issue by ziesemer** [Azure/azure-powershell#11446]
## Description

Unable to use Connect-AzureAD with Az.Accounts imported under PowerShell 7.0.

(Yes, I realize the AzureAD module is owned by another team / @AzureAD, so it was a toss where to open this first.  Opted for here, as arguably Az is breaking AzureAD.)

References:
* Looks like @devblackops ran into something similiar back in September: https://gist.github.com/devblackops/b734801c2379e6292a941c261b6fdfed
* Looks like https://github.com/Azure/azure-functions-host/issues/2373 might be related.

## Steps to reproduce

```powershell
PS> Import-Module Az.Accounts
PS> Import-Module AzureAD
PS> Connect-AzureAD
Connect-AzureAD: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.19.7.16602, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)
```

... whereas in a new PS session:

```powershell
PS> Import-Module AzureAD
PS> Connect-AzureAD
# Azure AD authentication prompt is successfully opened.
```

Simply reversing the order of the imports works, but only outside of Visual Studio Code:

```powershell
PS> Import-Module AzureAD
PS> Import-Module Az.Accounts
PS> Connect-AzureAD
# Azure AD authentication prompt is successfully opened.
```

The initial effort here was to use an existing authentication from Az to connect to AzureAD using `Connect-AzureAD -AadAccessToken`, which would not even require an interactive UI - but demonstrating the above without for a more simplistic test case.

When using VS Code, simply having a file open in the editor that references the Az cmdlets makes it impossible to use the AzureAD module (at least Connect-AzureAD) within the same session.  I'm guessing something within IntelliSense is causing the Az.Accounts module to load before AzureAD, despite any attempts to explicitly load AzureAD first.  Tested with VS Code version 1.43.2, Windows 10.0.18363, PowerShell extension v2020.3.0.  Using v2020.3.1-preview makes no difference.

Also reproduced on a clean Win10 VM.

## Environment data

```
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

This does appear to work without issue under PS 5.1, but not under 7.0.

## Module versions

```powershell
ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Script     3.6.1                 Az                                  Core,Desk
Script     1.7.3                 Az.Accounts                         Core,Desk
...
Binary     2.0.2.76              AzureAD                             Desk
```

Using the `AzureAD` or `AzureADPreview` module makes no difference.

```powershell
ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Binary     2.0.2.85              AzureADPreview                      Desk
```

## Debug output

(No additional debug output is provided with `$DebugPreference='Continue'`.)

## Error output

```
   HistoryId: 4

Message        : Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory,
                 Version=3.19.7.16602, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a
                 specific file. (0x80131621)
StackTrace     :    at Microsoft.Open.Azure.AD.CommonLibrary.AzureSession.NewSessionstate()
                    at Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD.BeginProcessing() in
                 X:\bt\1026407\repo\src\dev\PowerShell.V2\CommonLibrary\ConnectAzureAD.cs:line 98
                    at System.Management.Automation.Cmdlet.DoBeginProcessing()
                    at System.Management.Automation.CommandProcessorBase.DoBegin()
Exception      : System.IO.FileLoadException
InvocationInfo : {Connect-AzureAD}
Line           : Connect-AzureAD
Position       : At line:1 char:1
                 + Connect-AzureAD
                 + ~~~~~~~~~~~~~~~
HistoryId      : 4

Message        : Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory,
                 Version=3.19.7.16602, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
StackTrace     :    at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext,
                 String ilPath, String niPath, ObjectHandleOnStack retAssembly)
                    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
                    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
                    at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
                    at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler,
                 RuntimeAssembly assembly, String name)
                    at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String
                 assemblyFullName)
Exception      : System.IO.FileLoadException
InvocationInfo : {Connect-AzureAD}
Line           : Connect-AzureAD
Position       : At line:1 char:1
                 + Connect-AzureAD
                 + ~~~~~~~~~~~~~~~
HistoryId      : 4
```

**Comment by dingmeng-xue** [comment]
This is a known limitation on .NET CORE that new version assembly cannot be loaded if old version is already loaded. PowerShell is considering module isolation but so far there is no good solution yet.

Suggestion is to change the import order. If reversing order cannot work in VS code, it means some others load this old assembly too. Another alternative way is `Add-Type` in advance such as examples in https://pscustomobject.github.io/powershell/howto/PowerShell-Add-Assembly/

**Comment by TechNosisDerek** [comment]
I know this is an old closed issue and can stay closed, but at this point I am going to have to abandon using AZ keyvault. I cannot manage AIPService, or azureAD after loading the module because of these issues.

**Comment by ziesemer** [comment]
@TechNosisDerek - not even a month old.  I think this needs to be tracked as an open issue, somewhere...  if not here, where?

I'm thinking there is more that Az.Accounts can or should need to be doing here.  Update the included version of Microsoft.IdentityModel.Clients.ActiveDirectory ?  Implement lazy loading, or defer loading somehow?

**Comment by TechNosisDerek** [comment]
I'm just started on learning more powershell and before Monday didn't even know what assemblies in powershell were. As a start I would expect the current versions of all of the official Azure modules to call the same versions of assemblies. Then the the core powershell team wanted to properly wall off modules from each other so collisions didn't happen that would be great. 

I simply wanted to securely store some credentials in key vault to be used by a team of non-coders to manage 365, who would have guessed it would be this big of a pain.

**Comment by dingmeng-xue** [comment]
Thanks for feedback. We will evaluate upgrading `Microsoft.IdentityModel.Clients.ActiveDirectory` to the latest version.

**Comment by TechNosisDerek** [comment]
The other problem I have seen is:
Az.Accounts\1.7.5\Microsoft.WindowsAzure.Storage.dll is version 9.3.0.0
AIPService\1.0.0.1\Microsoft.WindowsAzure.Storage.dll is version 9.3.2.0
and should also be looked at.

**Comment by holylander** [comment]
Same issue here. Same scenario, I can run the connect `Connect-AzureAD`  from powershell terminal but not from the VS CODE powershell terminal :(

**Comment by holylander** [comment]
> 
> 
> Thanks for feedback. We will evaluate upgrading `Microsoft.IdentityModel.Clients.ActiveDirectory` to the latest version.

did it work?

**Comment by cveld** [comment]
I believe this is only related to the VSCode integrated PowerShell console. If I `Connect-AzureAd` in a regular PowerShell console window within VSCode, it works fine. 
I am using the following versions:
* VSCode 1.46.0
* PowerShell extension 2020.6.1
* AzureAD 2.0.2.76
* PowerShell 7.0.1

**Comment by Aileron79** [comment]
Same issue here, I use the Az module to create users in AAD (New-AzADUser), but to add a domain I need the AzureAD module (New-AzureADDomain). I don't understand why I need to use two different modules for that in the first place but obviously that's how it is. In VSC I cannot execute Connect-AzureAD for the very same reason as mentioned earlier. Tried to re-order my processes and cmdlets but without any success:

Connect-AzureAD: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.19.7.16602, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)

PowerShell v7.0.3
PS extension 2020.6.0
VSC 1.47.3
Az module 4.5.0
AzureAD module 2.0.2.106

**Comment by dingmeng-xue** [comment]
@Aileron79 , Since compatibility concern, we don't remove AAD basic support from Azure PowerShell module. I believe AzureD module support create user too. 

Az.Accounts uses Microsoft.IdentityModel.Clients.ActiveDirectory for login but its version is older than version used by AzureAd module. It's the root cause and limitation comes from PowerShell. We are working on replacing ADD. This issue should be removed by the next Az major release in this year.

The message is from DOTNET core and PowerShell. Actually, individual module cannot control it during loading.

**Comment by rtaylor72** [comment]
I noticed Az module 4.7 was just released, but still have error trying to run Connect-AzureAD under powershell 7.  Still a big problem.

**Comment by dingmeng-xue** [comment]
@rtaylor72 , Az 4.7 is still using Microsoft.IdentityModel.Clients.ActiveDirectory. We will release new version soon in Az major release. You can also try Az.Accounts 2.0.1-preview

```
Install-Module -Name Az.Accounts -AllowPrerelease	
```

**Comment by rtaylor72** [comment]
Pre-release != able to use in production 

So this is not an option.

**Comment by dingmeng-xue** [comment]
@rtaylor72 , I see. My point was trying pre-release can prove upcoming major release will resolve your issue once Az.Accounts uses MSAL. If there is any problem not covered by us, we can resolve it as soon as possible before official release. We will test the case of AzureAD and Az.Accounts side-by-side too.

**Comment by rtaylor72** [comment]
What is the ETA for the v2 release?

**Comment by dingmeng-xue** [comment]
If there is no issue, we will release new version by the end of this month.  I had tagged milestone.

**Comment by gaikovoi** [comment]
@dingmeng-xue, Az v 5.0.0 still has this issue. With the latest available modules versions (see screenshot), Connect-AzureAD still produce same error if I run any Az command before it.
`Connect-AzureAD: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.19.7.16602, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)`
![image](https://user-images.githubusercontent.com/34320902/97373137-a0aac900-188b-11eb-8042-1e5b8b4732a0.png)

Side note. In Azure DevOps "Azure PowerShell" task, Connect-AzAccount happens implicitly before "my" code execution. In order to migrate to Az module from AzureRM, we will have to split out our PS scripts into two separated tasks to workaround this issue.

**Comment by felickz** [comment]
I am on latest AzureADPreview and still get the same @dingmeng-xue

```
Version            Name
-------              ---- 
5.0.0                Az
2.1.0                Az.Accounts
2.0.2.119         AzureADPreview
```
```
PS > $PsVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```


```powershell
PS > Import-Module AzureADPreview
PS> Connect-AzureAD
Connect-AzureAD: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.19.7.16602, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)
```

**Comment by dingmeng-xue** [comment]
@erich-wang ， please check if this assembly is required by other Az modules.

@felickz , is it possible to Import AzureADPreview at the first? The interesting thing is I saw below error when I try `Connect-AzureAD`
```
PS C:\Dev\PowerShell-7.0.3-win-x64> import-module AzureADPreview
PS C:\Dev\PowerShell-7.0.3-win-x64> Connect-AzureAD
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.)
Connect-AzureAD: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

**Comment by felickz** [comment]
By default, Az module gets auto imported. If I force the imports in my PS profile, i get the same error you do.

**profile.ps1**
```
Import-Module AzureAD
Import-Module Az
```
```powershell
> Connect-AzureAD
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.)
Connect-AzureAD: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

Further in Azure Devops task - ["Az Powershell"](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)  the Az Modules are imported manually for you, so same issue persists there.

Also, there have been deprecation activities that not allowing the move to PS7 requires now require further workarounds for using KV apis with PS5 since PS7 is not an option :(
https://github.com/MicrosoftDocs/azure-docs/issues/62396

**Comment by LukeDearden** [comment]
I ran into the issue with Connect-AzureAD, Az.Accounts and PS 7 

I found that using `Import-Module AzureAD -UseWindowsPowerShell` got rid of the assembly issue.

I now have a different issue with New-AzureADApplication which doesn't happen in PS 5.1

```
New-AzureADApplication: Cannot bind parameter 'RequiredResourceAccess'. Cannot convert value "class RequiredResourceAccess {
  ResourceAppId: 00000003-0000-0000-c000-000000000000
  ResourceAccess: System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.ResourceAccess]
}
" to type "Microsoft.Open.AzureAD.Model.RequiredResourceAccess". Error: "Cannot convert the "class RequiredResourceAccess {
  ResourceAppId: 00000003-0000-0000-c000-000000000000
  ResourceAccess: System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.ResourceAccess]
}
" value of type "Deserialized.Microsoft.Open.AzureAD.Model.RequiredResourceAccess" to type "Microsoft.Open.AzureAD.Model.RequiredResourceAccess"."
```

**Comment by dingmeng-xue** [comment]
@LukeDearden , is `New-AzureADApplication` issue related to Az.Accounts? What's the step to reproduce this issue?

**Comment by LukeDearden** [comment]
> @LukeDearden , is `New-AzureADApplication` issue related to Az.Accounts? What's the step to reproduce this issue?

Hi, 
New-AzureADApplication is related to AzureAD. I wasn't really looking for assistance with this new problem. Just wanted to share my workaround for using Connect-AzureAD with Az.Accounts

**Comment by AiHaibara** [comment]
Update-Module -Name Az
Import-Module AzureADPreview
Connect-AzureAD

**Comment by erich-wang** [comment]
Close the issue as it has been addressed in Az.Accounts 2.2.0 which will be released on Nov 17, thanks.

**Comment by felickz** [comment]
Getting same behavior... FYI @erich-wang 

Modules:
```
> Get-InstalledModule Az*

Version              Name
-------              ----
5.1.0                Az
2.2.1                Az.Accounts
2.0.2.128         AzureAD
2.0.2.129         AzureADPreview

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Profile:
Import-Module AzureAD
Import-Module Az

CMD:
`> Connect-AzureAd -TenantId <xyz>
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.)
Connect-AzureAD: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.`

**Comment by gist901** [comment]
I too am receiving the same error message as @felickz.  I will Import the module, run the connect command and after successfully loggging in, I recieve the following error message

```
Connect-AzureAD

Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.)
Connect-AzureAD: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```


```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Modules:

```
ModuleType Version    PreRelease Name
---------- -------    ---------- ----                  
Script     5.1.0                 Az                                
Script     2.2.1                 Az.Accounts                         
Binary     2.0.2.128             AzureAD

**Comment by ziesemer** [comment]
@erich-wang, can we please get this ticket re-opened and addressed?

**Comment by dingmeng-xue** [comment]
I just tried PowerShell 7.1. Connect-AzureAD reports the same error even no other module loaded. Please report this issue to AzureAD module.
```
PS C:\Dev\PowerShell-7.1.0-win-x64> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Dev\PowerShell-7.1.0-win-x64> Connect-AzureAd
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.)
Connect-AzureAD: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Connect-AzureAD: One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

PS C:\Dev\PowerShell-7.1.0-win-x64> get-module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     2.0.2.128             AzureAD                             {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-…
Script     2.2.0      beta1      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKe…
```

**Comment by robertcaretta** [comment]
I see this is ticket is closed, however I was also experiencing issues loading modules with the VS Code "Powershell Integrated Console". Once I changed it to just the powershell console I was able to load Import-AzureAD without issue.

**Comment by dingmeng-xue** [comment]
Hi @robertcaretta , please report a new issue and provide your environment information and module versions. 

If the issue is specific to AzureAD module, I have to close it directly because that module doesn't come from Azure PowerShell or this repo. We have no their contact information.
