### ISSUE TITLE
[Az.Functions] Update linuxFxVersion for dotnet function apps

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-powershell#11443]
- For V3 linux function apps - set linuxFxVersion to `dotnet|3.1`
- For V2 linux function apps - set linuxFxVersion to `dotnet|2.2`

**Comment by pragnagopa** [comment]
cc @ankitkumarr @divyagandhii

**Comment by Francisco-Gamino** [comment]
Hello @pragnagopa, this is just for Linux app, correct?

**Comment by Francisco-Gamino** [comment]
This issue is fixed in the latest version of Az.Functions.
