### ISSUE TITLE
Error while running ADLS Gen2 Commands in Powershell

### ISSUE THREAD

**Issue by himmyaggarwal** [Azure/azure-powershell#11450]
Hi,

I am using powershell to run ADLS gen2 command. I want to create release pipelines in Azure DevOps to automate creation of ADLS gen 2 filesystem and folders and provide them required permissions.

I am using this article https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-powershell

and getting error as in screenshot attached.
![image](https://user-images.githubusercontent.com/62174568/77905373-c47d4080-72a3-11ea-9288-cde6dd5e3a67.png)

**Comment by dingmeng-xue** [comment]
Add storage team to check it.

**Comment by blueww** [comment]
@himmyaggarwal

What's the Az.Storage module on your machine?
You can get by run "get-Module" after repro this issue. And if you follow the issue template, you can give the necessary information of the issue include the module version.

DatalakeGen2 feature, only available in Az.Storage preview module , the latest version in 1.13.3-preview. You can install with following command. (the output object of the cmdlets has a little change from the doc, will update doc soon.)
```powershell
Install-Module az.storage -RequiredVersion 1.13.3-preview -Repository PSGallery -AllowClobber -AllowPrerelease -Force     
```

If you have installed a Az.Storage module version bigger than 1.13.3, powershell will load the module with biggest version by  default, then you need to import 1.13.3 manually in the begin when you open a PSH console with "Import-Module Az.Storage -RequiredVersion 1.13.3"

**Comment by himmyaggarwal** [comment]
Hi

facing the below error while running same command.

![image](https://user-images.githubusercontent.com/62174568/78424513-c83a0a00-768b-11ea-9790-7ef45a183f7f.png)

**Comment by blueww** [comment]
The powershellGet on your machine is too old.
Please follow the doc to upgrade PowershellGet and install the module:
https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-powershell

**Comment by himmyaggarwal** [comment]
Updated with latest module as updated in document but still facing the same issue.



![image](https://user-images.githubusercontent.com/62174568/78424847-b5c0d000-768d-11ea-89ac-b65744ab17a2.png)

**Comment by blueww** [comment]
You don't follow the doc after install PowershellGet: "Then, close and reopen the PowerShell console."

You need to close and reopen PSH console to load the new installed powershellGet

**Comment by himmyaggarwal** [comment]
but if i follow the same commands in my powershell scripts on azure devops. How can i restart
