### ISSUE TITLE
New-AzADAppCredential cannot supply customkeyidentifier/description for client secret

### ISSUE THREAD

**Issue by syim1** [Azure/azure-powershell#11457]
Using the Az module command New-AzADAppCredential I am unable to add a client secret customkeyidentifier like when using the New-AzureADApplicationPasswordCredential. 

this is the code I ran

`
$startDate = Get-Date
$endDate = $startDate.AddYears(2)
$SecureStringPassword = ConvertTo-SecureString -String "password" -AsPlainText -Force
New-AzADAppCredential -ObjectId (Get-AzADApplication -DisplayName "myfirstapp").ObjectId -Password $SecureStringPassword -StartDate $startDate -EndDate $endDate
`

the added secret ends up looking as such

![image](https://user-images.githubusercontent.com/15278307/77943658-912eb780-728b-11ea-884c-8019730cf1a5.png)

**Comment by dingmeng-xue** [comment]
@syim1, Azure PowerShell supports basic functions on Azure AD. The feature scope is less than AzureAD module. Could you use AzureAD to meet your requirement?

**Comment by syim1** [comment]
@dingmeng-xue sorry for the late reply, we are actually using AD modules currently and I don't believe you can use both at the same time right? although I wasn't able to add a description, I still got it to work for our purposes, but it would be nice to be able to add a description.

**Comment by dingmeng-xue** [comment]
Thanks. I will add it as a feature request and plan it accordingly.
