### ISSUE TITLE
Get-AzServiceBusTopic throws an exception if MaxCount exceeds 1000.

### ISSUE THREAD

**Issue by kesane-msft** [Azure/azure-powershell#11459]
## Description
Get-AzServiceBusTopic throws an exception if MaxCount exceeds 1000.
Exception: 'top' exceeds maximum value of '1000'.

## Steps to reproduce
Execute the cmdlet - 
`Get-AzServiceBusTopic -ResourceGroup $ResourceGroup -NamespaceName $OldNamespaceName -MaxCount 2000`

There is no way even to skip some topics, so in case we have > 1000 topics, there is no way to access the topics after the first 1000.

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
Involve ServceBus team to check if it is a limitation.

**Comment by axisc** [comment]
@kesane-msft we will investigate this internally.

On a related note, I'd consider sharding the topics across different namespaces to make sure you have a performant Service Bus.

**Comment by kesane-msft** [comment]
Thanks @axisc . This is some legacy code that I am working upon so sharding topics across different namespaces might not be a simple option for me.

**Comment by itsmaryann** [comment]
Hi! Any update on this issue? I am seeing the same error using Get-AzServiceBusQueue
Is there a way to see the queues after the first 1000?

**Comment by Saglodha** [comment]
Hi @kesane-msft and @itsmaryann , Apologies for delay here. 

@kesane-msft ,I reviewed the latest cmdlet for listing topics and could see that we have a -MaxCount switch provided. Can you please try using the switch and confirm if it helps you to fetch all the topics?

Additionally, Bare REST API is also supporting $top and $skip query parameters to manage the result set. 

**Helpful Links:**
https://docs.microsoft.com/en-us/powershell/module/az.servicebus/get-azservicebustopic?view=azps-7.1.0
https://docs.microsoft.com/en-us/rest/api/servicebus/stable/topics/list-by-namespace

@itsmaryann , I see similar -MaxCount switch available for Get-AzServiceBusqueue as well. Can you please try re-running the cmdlet with switch?

**Helpful Links:** 

https://docs.microsoft.com/en-us/powershell/module/az.servicebus/get-azservicebusqueue?view=azps-7.1.0
https://docs.microsoft.com/en-us/rest/api/servicebus/stable/queues/list-by-namespace

**Comment by itsmaryann** [comment]
Hi @Saglodha I had already used the MaxCount switch when I commented on this issue. As you can see in the original post, the exception is raised after using MaxCount.

**Comment by Saglodha** [comment]
Thanks for feedback @itsmaryann , can you confirm if you have an environment with such number of queues/topics handy? If yes, I would like to look at the debug trace for the cmdlet execution.

**Comment by kesane-msft** [comment]
@Saglodha - we have transitioned to Event Hubs. So I am afraid I won't be able to verify on my end. Looking at the comments that others are still facing this issue, I will not close it for now.

**Comment by Saglodha** [comment]
Hi @itsmaryann - I spent some time prepping for the environment and could reproduce the issue. We would investigate this internally. 

However, as talked about in earlier part of thread we should also look at slicing down the number of queues from one namespace and having multiple namespaces for better performance.

**Comment by itsmaryann** [comment]
That's great @Saglodha! Thanks. 
We haven't had any performance issues so far. This cmdlet is used whenever we want to change properties on the queues and topics, which is infrequent. We could use REST APIs for that, but Powershell is nicer to quickly get started.

**Comment by Saglodha** [comment]
Thanks for your feedback @itsmaryann, this has been fixed in our latest release. You can use Skip and Top operators to get more than 1000 entities now.
