### ISSUE TITLE
Test environment does not define storage endpoints suffix

### ISSUE THREAD

**Issue by yoavrubin** [Azure/azure-powershell#1145]
Within the class Microsoft.Azure.Test.TestEnvironment, the endpoints field is an instance of the class Microsoft.Azure.Test.TestEndpoints. This endpoints class does not define storage endpoints. Specifically, does not define a StorageEndpointSuffix.
This Sql auditing cmdlets read this value from the environment. Not having this value in the test environment causes the automated tests to fail.

**Comment by markcowl** [comment]
@yoavrubin closing this issue due to its age.  Please re-open if this is still an issue
