### ISSUE TITLE
Az Storage Update Blob Metadata Command Missing

### ISSUE THREAD

**Issue by cconrado** [Azure/azure-powershell#11467]
## Description of the new feature
We need to update blob metadata via ps. It already exists for cli & rest.

## Proposed implementation details (optional)
It's so blobs can be updated while they are copied from ADF from FTP.

**Comment by dingmeng-xue** [comment]
Involve Storage team to evaluate this feature request.

**Comment by blueww** [comment]
@cconrado 
I am not very sure about your user scenario.
If you just want update the metadata of an exsiting blob, we support run Storage client library APIs with the object from Az.Storage cmdlet output. So you can do it by:
```powershell
 #get blob object with Az.Storage cmdlet
 $blob = Get-AzStorageBlob -Container $containerName -Blob $blobname  -Context $ctx
 
 # $blob.ICloudBlob.Metadata is a dictionary, you can do add, remove, clear ... action on it
 # Update metadata by add an item
 $blob.ICloudBlob.Metadata.Add("key", "value1")
 # update metadata by update the value of an item
 $blob.ICloudBlob.Metadata["key"] = "value2"

 # set the metadata to blob on the server
 $blob.ICloudBlob.SetMetadata()
```

If you want to upgrade a blob with metadata, you can run:
```powershell
PS C:\>$Metadata = @{"key" = "value"; "name" = "test"}
PS C:\> Set-AzStorageBlobContent -File "ContosoPlanning" -Container "ContosoUploads" -Metadata $Metadata 
```

**Comment by cconrado** [comment]
@blueww But thats not in the docs? using `Set-AzStorageBlobContent` isnt that reuploading the file because thats how the docs describes that cmdlet

is `$blob.ICloudBlob.SetMetadata()` in powershell? cause I saw that reference but for c#

**Comment by blueww** [comment]
@cconrado 
Set-AzStorageBlobContent is used to upload a blob. It can also overwrite exist blob with -Force.

$blob.ICloudBlob.SetMetadata() is a .NET SDK API, you can run .NET SDK API in Powershell by nature. 
As there are so many .NET SDK API can run, we don't doc all of them.

**Comment by cconrado** [comment]
@blueww `$blob.ICloudBlob.SetMetadata()` if i can use that without installing anything other than the module then we are good.

But I would document that as theres no cmdlet that just updates metadata without the file upload

**Comment by blueww** [comment]
@cconrado
You can use the .net Storage client library API with the output object from storage cmdlet,  by just install Az.Storage module.

for the doc, would you please help to update what's the doc? 
It might be better to say to just update metadata with Az.Storage, user need get the blob object with Get-AzStorageBlob, and then user .NET Storage client library API to update it. You can also attach the script there.

**Comment by blueww** [comment]
@cconrado 
I will close this issue as not heard from you for a long time.
Fell free to contact us if you need further assistance for Storage PowerShell cmdlets.
