### ISSUE TITLE
Missing -asjob in command Set-AzVMDiskEncryptionExtension

### ISSUE THREAD

**Issue by m0ntl** [Azure/azure-powershell#11466]
## Description
Missing -asjob flag in Az.Compute Set-AzVMDiskEncryptionExtension

## Module versions
Az.compute version: 3.7.0

**Comment by dingmeng-xue** [comment]
Involve Compute team to look into it.

**Comment by Drewm3** [comment]
@vaibhav-agar, could you take a look at this feature request? If a new feature is needed to meet this request, then please open a feature suggestion in [Azure User Voice for VMs](https://feedback.azure.com/forums/216843-virtual-machines).

**Comment by Vaibhav-Agar** [comment]
Thanks for bring this to our attention @m0ntl .Opened a new feedback item [here](https://feedback.azure.com/forums/216843-virtual-machines/suggestions/40243945-support-asjob-in-command-set-azvmdiskencryptionex).
