### ISSUE TITLE
Set-AzDiagnosticSetting is not working when try to set for subscription

### ISSUE THREAD

**Issue by vinay-koganti** [Azure/azure-powershell#11473]
## Description
Trying to enable diagnostic settings for my subscription through powershell. But getting the below error

Set-AzDiagnosticSetting : Exception type: ErrorResponseException, Message: 
Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: 
Null
At line:86 char:5
+     Set-AzDiagnosticSetting -ResourceId "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzDiagnosticSetting], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand

## Steps to reproduce

Set-AzDiagnosticSetting -ResourceId "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -Enabled $True -Name $diagnosticProfileName -Category $diagnosticProfileCategories -ServiceBusRuleId $serviceBusRuleId 

## Environment data

Azure Run Book

## Module versions

Az.Accounts       	   1.6.2
Az.ApiManagement  	   1.1.0
Az.Automation     	   1.3.2
Az.Billing        	   1.0.0
Az.Blueprint      	   0.1.0
Az.EventHub       	   1.4.0
Az.KeyVault       	   1.0.2
Az.ManagedServiceIdentity  0.7.1
Az.Monitor                 1.2.2
Az.Network                 1.13.0
Az.OperationalInsights     1.3.3
Az.ResourceGraph           0.7.5
Az.Resources               1.6.2
Az.Security                0.7.5
Az.Storage                 1.6.0
Az.Subscription            0.7.1
Azure                      5.3.0
Azure.Storage              4.6.1
AzureRM.Automation         6.1.1
AzureRM.Compute            5.9.1
AzureRM.Profile            5.8.3
AzureRM.Resources          6.7.3
AzureRM.Sql                4.12.1
AzureRM.Storage            5.2.0
ComputerManagementDsc      5.0.0.0
GPRegistryPolicyParser     0.2
Microsoft.PowerShell.Core  0.0

## Debug output

7:46:59 PM - SetAzureRmDiagnosticSettingCommand begin processing with ParameterSet 'OldSetDiagnosticSetting'.
7:46:59 PM - using account id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'...
7:47:00 PM - *** The namespace for all the model classes will change from 
Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.
7:47:00 PM - *** The namespace for output classes will be uniform for all classes in future releases to make it 
independent of modifications in the model classes.
7:47:00 PM - Processing using command line arguments
7:47:00 PM - Listing existing diagnostics settings for resourceId '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
[Common.Authentication]: Authenticating using Account: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', environment: 
'AzureCloud', tenant: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
[Common.Authentication]: Authenticating using configuration values: Domain: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 
Endpoint: 'https://login.microsoftonline.com/', ClientId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', ClientRedirect: 
'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
[ADAL]: Information: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: ADAL 
PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version 
'2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

[ADAL]: Information: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: ADAL 
PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version 
'2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

[ADAL]: Information: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: === Token 
Acquisition started: 
	CacheType: null
	Authentication Target: Client
	, Authority Host: login.microsoftonline.com

[ADAL]: Information: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: === Token 
Acquisition started:
	Authority: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/
	Resource: https://management.core.windows.net/
	ClientId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
	CacheType: null
	Authentication Target: Client
	

[ADAL]: Verbose: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: Loading from cache.

[ADAL]: Verbose: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: Loading from cache.

[ADAL]: Information: 2020-04-01T19:47:00.3024923Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 1 
items to token cache.

[ADAL]: Verbose: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: Looking up cache 
for a token...

[ADAL]: Verbose: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx- LoggerBase.cs: Looking up cache 
for a token...

[ADAL]: Information: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: An item 
matching the requested resource was found in the cache

[ADAL]: Information: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: An item 
matching the requested resource was found in the cache

[ADAL]: Information: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: 59.859091795 
minutes left until token in cache expires

[ADAL]: Information: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: 59.859091795 
minutes left until token in cache expires

[ADAL]: Information: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: A matching 
item (access token or refresh token or both) was found in the cache

[ADAL]: Information: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: A matching 
item (access token or refresh token or both) was found in the cache

[ADAL]: Information: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: === Token 
Acquisition finished successfully. An access token was returned: Expiration Time: 4/1/2020 8:46:51 PM +00:00

[ADAL]: Information: 2020-04-01T19:47:00.3024923Z: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - LoggerBase.cs: === Token 
Acquisition finished successfully. An access token was returned: Expiration Time: 4/1/2020 8:46:51 PM +00:00Access 
Token Hash: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
	 User id: 

[Common.Authentication]: Checking token expiration, token expires '04/01/2020 20:46:51 +00:00' Comparing to '04/01/2020 
19:47:00 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:59:51.5299473'
============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com//subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/microsoft.insights/diagnostic
Settings?api-version=2017-05-01-preview

Headers:
x-ms-client-request-id        : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
accept-language               : en-US

Body:

============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
x-ms-routing-request-id       : SOUTHCENTRALUS:20200401T194700Z:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Wed, 01 Apr 2020 19:46:59 GMT
Server                        : Microsoft-IIS/10.0

Body:
{
  "value": []
}

7:47:00 PM - Diagnostic setting named: 'default' not found in list of 0 settings. Creating a new one.
7:47:02 PM - Retrieving supported categories for resource: '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
[Common.Authentication]: Checking token expiration, token expires '04/01/2020 20:46:51 +00:00' Comparing to '04/01/2020 
19:47:02 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:59:49.6704044'
============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com//subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/microsoft.insights/diagnostic
SettingsCategories?api-version=2017-05-01-preview

Headers:
x-ms-client-request-id        : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
accept-language               : en-US

Body:

============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 00000000-0000-0000-0000-000000000000
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-correlation-request-id   : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
x-ms-routing-request-id       : SOUTHCENTRALUS:20200401T194702Z:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Wed, 01 Apr 2020 19:47:01 GMT
Server                        : Microsoft-IIS/10.0

Body:
{
  "code": "BadRequest",
  "message": ""
}

7:47:02 PM - Aggregate exception System.AggregateException: One or more errors occurred. ---> 
Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.DiagnosticSettingsCategoryOperations.<ListWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Monitor.DiagnosticSettingsCategoryOperationsExtensions.<ListAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand.ProcessRecordInternal()
---> (Inner Exception #0) Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an 
invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.DiagnosticSettingsCategoryOperations.<ListWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Monitor.DiagnosticSettingsCategoryOperationsExtensions.<ListAsync>d__3.MoveNext()<---

7:47:02 PM - Inner exception is different NotFound: Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: 
Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.DiagnosticSettingsCategoryOperations.<ListWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Monitor.DiagnosticSettingsCategoryOperationsExtensions.<ListAsync>d__3.MoveNext()
Set-AzDiagnosticSetting : Exception type: ErrorResponseException, Message: 
Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: 
Null
At line:61 char:1
+ Set-AzDiagnosticSetting -ResourceId "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzDiagnosticSetting], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand
 
AzureQoSEvent: CommandName - Set-AzDiagnosticSetting; IsSuccess - False; Duration - 00:00:03.0280376; Exception - 
System.Management.Automation.PSInvalidOperationException: Exception type: ErrorResponseException, Message: 
Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: 
Null ---> Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 
'BadRequest'
   at Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
Finish sending metric.
7:47:03 PM - SetAzureRmDiagnosticSettingCommand end processing.
7:47:03 PM - SetAzureRmDiagnosticSettingCommand end processing.

## Error output

Set-AzDiagnosticSetting : Exception type: ErrorResponseException, Message: 
Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: 
Null
At line:61 char:1
+ Set-AzDiagnosticSetting -ResourceId "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzDiagnosticSetting], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand

**Comment by dingmeng-xue** [comment]
@VeryEarly , please investigate this issue.

**Comment by VeryEarly** [comment]
this cmdlet failed at trying to get supported categories for the target resource which is your subscription, and subscription doesn't have a supported category.

Can you set the diagnostic settings via azure portal? 
If yes, can you show me how to do it?

**Comment by VeryEarly** [comment]
Hi @vinay-koganti ,

Will close this issue for now, please feel free to reopen it if you have further question.

**Comment by ivanignatiev** [comment]
Hello, 

I have the same issue `Set-AzDiagnosticSetting` does not work for Subscriptions

We need the cmdlet like https://docs.microsoft.com/en-us/cli/azure/monitor/diagnostic-settings/subscription?view=azure-cli-latest#az-monitor-diagnostic-settings-subscription-create in Azure CLI

Thank you !

**Comment by sdecker** [comment]
@VeryEarly Can we please reopen this? I can screenshare and show you the issue. This also affects Get-AzDiagnosticSetting. Both need to know how to deal with the subscription scope.

**Comment by Raghav0499** [comment]
> @VeryEarly Can we please reopen this? I can screenshare and show you the issue. This also affects Get-AzDiagnosticSetting. Both need to know how to deal with the subscription scope.

can you please share the screenshots?

**Comment by sdecker** [comment]
OK, bizarrely some of the same commands in my history that failed other day worked. The other day nothing worked. For example, I had tried to run Get-AzDiagnosticSetting -ResourceId /subscriptions/4a1e1378-e7a0-4412-b55e-56a58ba98a99 and it gave a notfound error. Today, it returns the subscription level diagnostic if set otherwise blank. 
When I ran the following on an already created errored.
set-AzDiagnosticSetting -ResourceId subscriptions/a1b8dd63-dded-4d54-a242-fabc6056a3a2 -WorkspaceId $omsWorkspace.ResourceId -Name AzMonitorDiagnosticsLogging
Today it works. 
I do still have an issue that there is no New-AzMonitorDiagnosticLogging. If I remove the diagnostic logging and try to run the set command I get 
~\OneDrive - Questionmark Corporation\Desktop\TestScripts> set-AzDiagnosticSetting -ResourceId subscriptions/a1b8dd63-dded-4d54-a242-fabc6056a3a2 -WorkspaceId $omsWorkspace.ResourceId -Name AzMonitorDiagnosticsLogging
WARNING: 16:58:00 - The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to
Microsoft.Azure.Management.Monitor.Models in future releases.
WARNING: 16:58:00 - The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model
classes.
set-AzDiagnosticSetting : Exception type: ErrorResponseException, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned
an invalid status code 'BadRequest'
   at Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null
At line:1 char:1
+ set-AzDiagnosticSetting -ResourceId subscriptions/a1b8dd63-dded-4d54- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzDiagnosticSetting], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand
