### ISSUE TITLE
The examples in the document Remove-AzKeyVaultManagedStorageSasDefinition uses a different command

### ISSUE THREAD

**Issue by aladdindoc** [Azure/azure-powershell#11479]
This is the document in question: src/KeyVault/KeyVault/help/Remove-AzKeyVaultManagedStorageSasDefinition.md

It's about the command Remove-AzKeyVaultManagedStorageSasDefinition
But the examples are using Remove-AzKeyVaultManagedStorage.

That'll cause confusion.
This is the screenshot of get-help Remove-AzKeyVaultManagedStorageSasDefinition
The command of the examples are wrong.

![image](https://user-images.githubusercontent.com/62311067/78284480-5a97ad80-74d4-11ea-8c21-47d3cf53c1d2.png)

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will verify and fix this doc issue.
