### ISSUE TITLE
Can't find the right resource type to list VM's in a classical cloud service roles

### ISSUE THREAD

**Issue by xuhaohems** [Azure/azure-powershell#11475]
## Description
Can't find the right resource type to list VM's in a classical cloud service roles in the new Az PowerShell module and I have to use the old version, e.g. 

Get-AzureRole -ServiceName $_.ServiceName -InstanceDetails

**Comment by dingmeng-xue** [comment]
Compute team, please help to answer this question.

**Comment by Drewm3** [comment]
The newer Az cmdlets do not support classic resources. For managing classic resources the older cmdlets, Azure*, must be used.
