### ISSUE TITLE
Azure devops archive files and upload to storage error

### ISSUE THREAD

**Issue by himmyaggarwal** [Azure/azure-powershell#11496]
Hi,

I have few folders in my repository feature branch and i want to upload those folders in azure storage after compressing them using archive agent in release pipeline.

1. i don't wanna save those folders in my feature branch and want to make it a single run in a fly . zip and upload. I tried to run archive agent and that agent is saving the file at $(Build.ArtifactStagingDirectory)/Azurefunctions.zip path.

2. Passing same path ($(Build.ArtifactStagingDirectory)/Azurefunctions.zip) as a source path of the file to upload to azure blob storage but copy activity fails with the error below. 
![image](https://user-images.githubusercontent.com/62174568/78424655-9f664480-768c-11ea-9e56-f10b4cacb6b2.png)

![image](https://user-images.githubusercontent.com/62174568/78424693-e2281c80-768c-11ea-9c7c-1cca82f0fad9.png)

**Comment by himmyaggarwal** [comment]
Installed latest version now.

still facing the same issue. Am i missing something?


![image](https://user-images.githubusercontent.com/62174568/78424820-93c74d80-768d-11ea-8f67-da8e558573fc.png)

**Comment by blueww** [comment]
@himmyaggarwal

Please follow the issue template, or we can't find enough information for investigate.
Please give the detail script, and which line reported the error.

For the error, it might because $ has special meaning in Powershell, if a file name has $, you need to replace it to $$.
```powershell
PS C:\> $a =  "($$(Build.ArtifactStagingDirectory)/Azurefunctions.zip)"

PS C:\> echo $a
($a(Build.ArtifactStagingDirectory)/Azurefunctions.zip)
```

**Comment by himmyaggarwal** [comment]
@blueww 
I am not using any powershell script for the same. i used azure devops release pipeline agent. 

I have attached yaml for the same.

![image](https://user-images.githubusercontent.com/62174568/78434143-92008880-7693-11ea-8efc-d336f3c5a058.png)
![image](https://user-images.githubusercontent.com/62174568/78434514-b197b100-7693-11ea-96a7-bdb36fdf6dbf.png)

**Comment by blueww** [comment]
If you don't use Azure Powershell cmdlets, you might should not open issue here.
This repo is for Azure Powershell issues.

And please follow the Issue template to open the issue.

**Comment by himmyaggarwal** [comment]
i have also written this below script and it also didn't work for me. it's pushing the file in application/octet-stream content type only rather compressed.

param
(
   [Parameter(Mandatory=$True, HelpMessage = "specify the parameter file")]
   $parameterFile

)


Write-Verbose "PSScriptRoot is: $PSScriptRoot"
$devOpsProjectFolder = (Get-Item -Path $PSScriptRoot).Parent.FullName
Write-Verbose "DevOps Project Folder: $devOpsProjectFolder"
$utilitiesFolder = "{0}\{1}" -f $devOpsProjectFolder, "Utilities"
$parameters = & "$utilitiesFolder\Get-Parameters" -parameterFile $parameterFile -overrideFile $overrideFile
$subscriptionId = $parameters.parameters.subscriptionId.value
$tenantId = $parameters.parameters.tenantId.value
$Location = $parameters.parameters.location.value

$sub = Select-AzSubscription -SubscriptionId $subscriptionId
Write-Verbose "Subscription Id: $($sub.Subscription.SubscriptionId)"
Write-Verbose "TenantId Id: $($sub.Subscription.TenantId)"
Write-Verbose "Account Id: $($sub.Account.Id)"

function uploadtostorage
{

#$sourcepath = "F:\testkhc"

#$sourcepath = "F:\testkhc"

#$sourcepath1 = Get-ChildItem $sourcepath



Write-Verbose "creating data set"
Write-Verbose "PSScriptRoot is: $PSScriptRoot"
$dbtProjectFolder = (Get-Item -Path $PSScriptRoot).Parent.Parent.FullName + "\adf_nielsenus"

Write-Verbose "dbt Project Folder: $dbtProjectFolder"
$sourcePath7 = Get-ChildItem "$dbtProjectFolder\*"

write-host "file path is $sourcePath7"


foreach($sourcepath2 in $sourcePath7)
{

 #$name = $sourcepath2.Name
#$path = $sourcepath + "\" + $name
$destinationpath = New-TemporaryFile | Rename-Item -NewName { $_ -replace 'tmp$', 'zip' }  –PassThru

#| Rename-Item -NewName {$_.Name -replace 'Name$', '$name'} –PassThru


Compress-Archive -Path $sourcepath2 -DestinationPath $destinationpath -Force 
}
return $destinationpath

}


Write-Verbose "PSScriptRoot is: $PSScriptRoot"
$dbtProjectFolder = (Get-Item -Path $PSScriptRoot).Parent.Parent.FullName + "\adf_nielsenus"

Write-Verbose "dbt Project Folder: $dbtProjectFolder"
$sourcePath1 = Get-ChildItem "$dbtProjectFolder\*"

foreach ($blob in $sourcePath1)
{

 $blobname = $blob.name + ".zip"
write-host "blob name is $blobname"
#$path = $sourcepath + "\" + $blobname
$strgname = $parameters.parameters.StorageAccountName.value

$containername = "zipfiles"

$resourcegroup = $parameters.parameters.azresourcegroupname.value

$strgkey1 = (AzStorageAccountKey -ResourceGroupName $resourcegroup -Name $strgname)[0].value



$file1 = uploadtostorage

$ctx = New-AzStorageContext -StorageAccountName $strgname -StorageAccountKey $strgkey1 

Set-AzStorageBlobContent -File $file1 -Container $containername -Blob $blobname -Context $ctx -force

}

**Comment by blueww** [comment]
@himmyaggarwal

If your only concern for the PSH script is application/octet-stream content type, you can specify the content type in Set-AzStorageBlobContent, see example #6 in https://docs.microsoft.com/en-us/powershell/module/az.storage/set-azstorageblobcontent?view=azps-3.7.0

If you don't specify content type, application/octet-stream is the default content type.

**Comment by himmyaggarwal** [comment]
using the "ContentType" = "application/x-zip-compressed" in command will compress the file?

**Comment by blueww** [comment]
@himmyaggarwal 
> using the "ContentType" = "application/x-zip-compressed" in command will compress the file?
No, This is just a blob property change, not change the blob content.
If you want to compress it, You need to compress it then upload with  Set-AzStorageBlobContent.

**Comment by blueww** [comment]
@himmyaggarwal
I will close the issue as not hear from you for a long time.
Feel free to contact use again if you need any further assistance for Azure PowerShell.
