### ISSUE TITLE
PowerShell Test-AzDeplyoment is missing a name parameter

### ISSUE THREAD

**Issue by rahalan** [Azure/azure-powershell#11497]
## Description of the new feature
When you run a PowerShell New-AzDeplyoment on Azure and you don’t specify a deployment name, the deployment will be named after the file, like “deploy” if you use a “deploy.json”. What is happening in the background is, that this deployment name for that tenant gets linked to the deployment region. This link is not changeable. So if you deploy the same file to a different region without a custom deployment name, it will fail. As you can change the name in New-AzDeployment with the name parameter, this limitation is easily to overcome. Unfortunately, when you want to test your deployment with Test-AzDeployment, you cannot specify the deployment name, which means it uses internally the file name. The test will fail in that case, that this file was already deployed in another region. The only workaround is to rename the file. 
## Proposed implementation details (optional)
Add the "name" parameter to the Test-AzDeployment commandlet

**Comment by dingmeng-xue** [comment]
Add Resources team to evaluate this feature request.

**Comment by rahalan** [comment]
As this is a PS feature, I think the PS team should handle it. Thanks, Rainer

**Comment by rahalan** [comment]
Any update? Tnx, Rainer

**Comment by MrMCake** [comment]
Just came across the same issue: 

```PowerShell
Code    : InvalidDeploymentLocation
Message : Invalid deployment location 'westcentralus'. The deployment already exists in location 'westeurope'.`

Came across this issue when running my Test-Pipeline (using Test-AzSubscriptionDeployment) for two different locations.

**Comment by rahalan** [comment]
Any update?

**Comment by bmoore-msft** [comment]
@rahalan - can you try: ```Get-AzDeploymentWhatIfResult``` to see if that gets you around the problem?  It will return more than a true/false but does more than test the template as well...

**Comment by jontreynes** [comment]
> Just came across the same issue:
> 
> ```powershell
> Code    : InvalidDeploymentLocation
> Message : Invalid deployment location 'westcentralus'. The deployment already exists in location 'westeurope'.
> ```
> 
> Came across this issue when running my Test-Pipeline (using Test-AzSubscriptionDeployment) for two different locations.

Same as @MrMCake - any updates? I'd like to pass in the runid from my Github Actions pipeline to name the deployment - to make the name unique to my deployment environments.

**Comment by jontreynes** [comment]
#15082 just published. Hope this helps to expedite the request

CC: @dingmeng-xue

**Comment by jontreynes** [comment]
I got it in the next release @rahalan

https://github.com/Azure/azure-powershell/blob/master/src/Resources/Resources/ChangeLog.md#upcoming-release
