### ISSUE TITLE
Get-AzDataFactoryv2Pipeline doesn't work 

### ISSUE THREAD

**Issue by shivakumarg06** [Azure/azure-powershell#11491]
Unable to fetch the Information of the Pipeline from the CMD Get-AzDataFactoryV2Pipeline -ResourceGroupName "ADF" -DataFactoryName "WikiADF" 

Please refer the Screenshot for more information. 

![Get-AzDataFactoryV2Pipeline issue](https://user-images.githubusercontent.com/15355596/78353704-24d3f100-75c8-11ea-8541-ad7a0c849a0f.png)

**Comment by dingmeng-xue** [comment]
Involve Data Factory team to look into it.

**Comment by lmy269** [comment]
@shivakumarg06  Most likely you should upgrade your factory module. There's some unknown property to the old module. Can you try that first? If it doesn't work, can you try with adding parameter "-debug"? You should be able to see the Json file and share that to us for trouble shooting.

**Comment by shawnxzq** [comment]
Close it for now since no response from customer.
