### ISSUE TITLE
`Connect-MicrosoftTeams -Identity` should support managed identities to interact with Azure Services

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-powershell#11512]
##  Description

Functions customer is trying to use the MicrosoftTeams (https://www.powershellgallery.com/packages/MicrosoftTeams/1.0.5) module in PowerShell 6.2

`Connect-MicrosoftTeams -Identity` should support managed identities to interact with Azure Services

## Steps to reproduce

1) Create script to to be run on the cloud (in this case, the script is hosted in the Azure Functions service) 
2) Install MicrosoftTeams from the PowerShell gallery
3) Enable managed identities 
4) Login from script 

### Expected:
Similar behavior as **`Connect-AzAccount -Identity`**

## Environment data

```
PS C:\Windows\System32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Windows\System32>
```

## Module versions

```powershell
PS C:\Windows\System32> Get-Module -ListAvailable MicrosoftTeams


    Directory: C:\Users\frangom\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Binary     1.0.5                 MicrosoftTeams                      Desk      {Get-CsBatchPolicyAssignmentOperation, New-CsBatchPolicyAssignmentOperation}

PS C:\Windows\System32>

```

## Debug output

```

```

## Error output

```

```

**Comment by Francisco-Gamino** [comment]
cc: @eamonoreilly @anirudhgarg @AnatoliB @joeyaiello @dcaro @markcowl @tameemansari @brandber

**Comment by Francisco-Gamino** [comment]
Hello @tameemansari and @brandber,

Is this the correct location for this issue? if not, could you please point me to the correct repo. 

Thanks,
Francisco

**Comment by markcowl** [comment]
@Francisco-Gamino Unfortunately, it is not.  The MicrosoftTeams module is not a module that we manage.
