### ISSUE TITLE
Add-AzureCertificate

### ISSUE THREAD

**Issue by softwarejc** [Azure/azure-powershell#1152]
Is there a equivalent Cmdlet in the pre-release version to "Add-AzureCertificate"?

I want to upload a service certificate for the specified cloud service:
https://msdn.microsoft.com/en-us/library/azure/dn495214.aspx

I can only find the "Add-AzureRmApplicationGatewaySslCertificate"  Cmdlet

**Comment by singhkay** [comment]
@softwarejc It should still be called Add-AzureCertificate. None of the ASM cmdlets were changed.
