### ISSUE TITLE
Set-AzActionGroup command from Azure Function App gives "ERROR: Set-AzActionGroup : Exception type: ErrorResponseException, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'Forbidden"

### ISSUE THREAD

**Issue by SafwanHussain** [Azure/azure-powershell#11526]
I am running a powershell script in Azure function App. The script creates an action group and metric alerts on a cosmosDB container, But the action group creation command fails, i tried with both resourceGroup name and ResourceId , it still fails.

command :

$RID = (Get-AzResource -ResourceType $containerResourceType -ApiVersion $apiVersion -ResourceGroupName $ResourceGroup -Name $containerResourceName).ResourceId

        $email1=New-AzActionGroupReceiver -Name $name -EmailReceiver -EmailAddress $Eid
        $email2=New-AzActionGroupReceiver -Name $name1 -EmailReceiver -EmailAddress $Eid2
        Set-AzActionGroup -ResourceId $RID -ShortName "DAEAG" -Receiver $email1,$email2 

# tried the Set-AzActionGroup command with resourceGroup (name) as well, it gives the same error which is,

[Error] ERROR: Set-AzActionGroup : Exception type: ErrorResponseException, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'Forbidden'

Note : Azure function app connects to Azure subscription using managed Identity
fucntion App onject_id is added to roles in cosmosdb account.

**Comment by dingmeng-xue** [comment]
@SafwanHussain, thanks for reporting. Could you please share below information?
- Please run `Get-Module  -ListAvailable` and paste the output
- Set `$DebugPreference='Continue'` before running the repro and paste the resulting debug stream

**Comment by SafwanHussain** [comment]
![Module-List2](https://user-images.githubusercontent.com/17927947/78911738-57885880-7aa4-11ea-962d-381dce68065f.PNG)
![Module-List1](https://user-images.githubusercontent.com/17927947/78911742-58b98580-7aa4-11ea-8d4d-f3b1154f0e8b.PNG)
![Module-List3](https://user-images.githubusercontent.com/17927947/78911744-59521c00-7aa4-11ea-84cc-31d1f8761349.PNG)
[FA_logs.docx](https://github.com/Azure/azure-powershell/files/4457077/FA_logs.docx)

i have attached the module-List and the logs after running with debug option.

Note:
I am running this powershell script from Azure function App, The module List is from running the command in Azure CLI and the Fa_Logs is the Azure function App Log

Observation:
After exploring this requirement further i have made some observation,

While running the powershell script from Azure function App, i am making a connection to AzAccount,

When i make the connection with Managed Identity ' Connect-AzAccount -Identity', with the object Id of the Function assigned with Owner role, the Set-AzActionGroup commands gives error.

But when i connect using 'Connect-AzAccount', open the link provided in the terminal, enter the code from terminal and select my account, then the commands executes successfully

Please let me know if i am connecting incorrectly with Identity or there is another way altogether.

**Comment by SafwanHussain** [comment]
Update : I figured out the issue.
I was assigning the Role for the Azure function at the CosmosDb resource level manually,which would give function access to just CosmosDB, but to reach that resource it also needs access to Resource Group .
i then assigned the role at the Resource group level , which cosmodb resource would automatically inherit it.
This solved the problem.
Thank you
