### ISSUE TITLE
New-AzADApplication (NewAzureADApplicationCommand.cs) should use SwitchParameter

### ISSUE THREAD

**Issue by JBrLloyd** [Azure/azure-powershell#11528]
## Description of the new feature
AvailableToOtherTenants parameter currently take an unnecessary Boolean that can become more powershell native using SwitchParameter. This, in my opinion, is also is less error prone

## Proposed implementation details (optional)
AvailableToOtherTenants should be declared of type SwitchParameter from System.Management.Automation
`public SwitchParameter AvailableToOtherTenants = { get; set; }`

**Comment by dingmeng-xue** [comment]
@JBrLloyd, thanks for suggestion. Changing it into switch will introduce breaking change. So, we have to keep it there due to its impact. 

It's right that switch is native in PowerShell. We will review new cmds and parameters carefully and suggest to use switch.
