### ISSUE TITLE
 ERROR - Defining Policy -New-AzPolicyAssignment - Can't use inline policy defination

### ISSUE THREAD

**Issue by Neelkamal10** [Azure/azure-powershell#11531]
Encountered following error, while creating new policy defining:
![Screenshot (2)](https://user-images.githubusercontent.com/54034262/78878398-f8105580-7a6f-11ea-8fa3-5db5802916e2.png)

[t1.txt](https://github.com/Azure/azure-powershell/files/4455128/t1.txt)

**Comment by dingmeng-xue** [comment]
Involve Resources team to look int this issue.

**Comment by Neelkamal10** [comment]
any updation ?

**Comment by Neelkamal10** [comment]
@ dingmeng-xue Have you got any solution yet?

**Comment by dingmeng-xue** [comment]
@Neelkamal10 , I had involve service team to look into it. Please wait their response.

**Comment by kenieva** [comment]
"type" is not valid in a policy definition. What are you trying to achieve with that?

**Comment by Neelkamal10** [comment]
@kenieva I am trying to restrict pip.

**Comment by kenieva** [comment]
I have taken a look and found some problems with deployment. 

1. Type is not supported within a policy definition. Please remove. If you are looking to add a category, please use the metadata category. 
2. When deploying using PS, the -Policy parameter only takes in the rule so starting with {"if"... please remove the rest. (https://docs.microsoft.com/en-us/powershell/module/az.resources/New-AzPolicyDefinition?view=azps-3.7.0) 
3. You are missing a closed parenthesis after the first field. 

Here is the deployment that worked for me: New-AzPolicyDefinition -Name "test" -SubscriptionId  "######" -Policy '{
>>             "if": {
>>               "allOf": [
>>                 {
>>                   "field": "type",
>>                   "equals": "Microsoft.Network/networkInterfaces"
>>
>>                 },{
>>                   "anyof": [
>>                     {
>>                       "field": "Microsoft.Network/networkInterfaces/ipconfigurations[*].publicIpAddress.id",
>>                       "exists": true
>>                     },
>>                     {
>>                       "not": {
>>                         "field": "Microsoft.Network/networkInterfaces/ipconfigurations[*].publicIpAddress.id",
>>                         "exists": false
>>                       }
>>                     }
>>                   ]
>>                 }
>>               ]
>>             },
>>             "then": {
>>                 "effect": "deny"
>>             }
>> }'

I did not test the policy so unsure if it works. I only tested deployment. Thanks
