### ISSUE TITLE
Azure Storage Lifecycle management is not available for Hierarchical Namespaces

### ISSUE THREAD

**Issue by SafwanHussain** [Azure/azure-powershell#11547]
I am exploring the Azure Storage Lifecycle management on Azure portal, currently i am using Free trail,
i observed that Lifecycle Management isn't available when the hierarchical namespaces is enabled on storage account but in the Microsoft documentation mentioned below it states that the lifecycle management is supported when hierarchical namespaces is enable on storage.
I also read that only delete snapshot feature is not available when hierarchical namespaces is enable.

please let me know if i am missing something here.

Documentation reference:

 'https://docs.microsoft.com/en-us/azure/storage/blobs/storage-lifecycle-management-concepts?tabs=azure-portal'

**Comment by blueww** [comment]
@SafwanHussain 

Please give the detail for "Lifecycle Management isn't available when the hierarchical namespaces ", is there any error reported? 

And ,please follow the issue template to raise the issue, or we can't get enough information to investigate.

**Comment by SafwanHussain** [comment]
Hi@blueww,
I am not facing any error but issue is at the very early stage of accessing Lifecycle Management.
What i meant by 'Lifecycle Management isn't available when the hierarchical namespaces' is that, when i create my storage account and enable the Hierarchical Namespaces, then i am unable to see the 'Lifecycle Management' option under 'Blob services' section on that storage, whereas when i am disabling the Hierarchical Namespaces then i can see the Lifecycle Management section under Blob services.

**Comment by blueww** [comment]
For "see the Lifecycle Management section under Blob services." , what do you mean?
I think this is not in Powershell? 

Please give each tool you use in each step, and the detail display/output. (hide any credentail)
Also the Powershell module version. (Get-Module)

**Comment by SafwanHussain** [comment]
@blueww you are right,i am not doing this exercise from powershell, i am doing this directly from the portal, and also the blob services is a section (pane) on the portal for a particular storage, under which is your lifecycle management option.

I have attached screenshot of the Storage(portal) showing the blob service section having Lifecycle management when Hierarchical namespaces is disabled.
when i create a storage account with hierarchical namespaces enabled, now i can't even see the blob service section also no lifecycle management option.
![lifecyclemgmt_HND](https://user-images.githubusercontent.com/17927947/79420375-6c01af00-7fd6-11ea-82dc-1c91dd518086.png)

**Comment by blueww** [comment]
@SafwanHussain
This repo is for Powershell Issue. 
As your issue is not related with Powershell, we are not the best person who can help you on this.

Would you mind to open a ticket to Azure Support on the Azure portal, to ask the support from protal/server side? 
![image](https://user-images.githubusercontent.com/6926193/80117815-35212f80-85ba-11ea-8614-2933fe4c4f40.png)

**Comment by blueww** [comment]
@SafwanHussain 
I will close this issue as it's not Powershell related.
Feel free to contact use again if you need any assistant on Azure Powershell.

**Comment by SafwanHussain** [comment]
@blueww Yes , you can close this issue.
I will take it up with the Azure support team.
Thanks
