### ISSUE TITLE
Invoke-AzVMRunCommand order the parameter passed to the shell script

### ISSUE THREAD

**Issue by amankohli** [Azure/azure-powershell#11555]
Hi,

I am using the below powershell command to invoke a shell scirpt:
Invoke-AzVMRunCommand -ResourceGroupName  $RGResourceGroupName `
            -VMName $VMName `
            -CommandId RunShellScript `
           -ScriptPath .\test.sh  -Parameter @{"arg1" = $1;"arg2"=$2";arg3"=$3;"arg4"=$4}  

How can I order the Parameter passed to the script i.e {"arg1" = $1;"arg2"=$2";arg3"=$3;"arg4"=$4}

Currently all of them are in random order created in the hash when passed to the scirpt

Regards,
Aman

**Comment by dingmeng-xue** [comment]
@erich-wang , can we support this approach?

**Comment by amankohli** [comment]
If we don't support the approach can you suggest me an alternative please

**Comment by erich-wang** [comment]
@amankohli, the type for **Parameter** is Hashtable, so the order won't be respected in Hashtable. Could you let us know why do you need ordered parameters?

**Comment by amankohli** [comment]
@erich-wang   I am passing parameter to the script as arguments like 1st parameter goes to the first variable. I resolved the issue by making my parameters as ordered hash list and just passing one argument to the script. Can we not make the hash table on the command ordered hash table?

**Comment by erich-wang** [comment]
@amankohli, thanks for your feedback, I'm routing this request to compute team.

**Comment by Drewm3** [comment]
@mayanknayar, could you please take a look at this one.

**Comment by mayanknayar** [comment]
@amankohli 

Can you try passing named parameters ?
These parameters are parsed and added at the top of your script and you can reference the named parameters in your script run. 

You can SSH to your VM and see how you script is modified before execution.

**Comment by Drewm3** [comment]
I am going to close this issue due to lack of response. @amankohli if you are able to answer the question from Mayank then we can open this again.
