### ISSUE TITLE
Import-AzBlueprintWithArtifact fails with resource group name longer than 90 characters, even with expansion

### ISSUE THREAD

**Issue by wasabii** [Azure/azure-powershell#11552]
## Description
`Import-AzBlueprintWithArtifact` fails when processing a `ResourceGroupDefinition.name` property longer than 90 characters, even if that name is an expansion function that will not expand beyond 90 characters.

## Steps to reproduce

Create a Blueprint file with a `resourceGroup` like the following:

```
        "resourceGroups": {
            "ApplicationResourceGroup": {
                "location": "[parameters('l')]",
                "name": "[concat(parameters('u'),'-',parameters('e'),'-',parameters('d'),'-',parameters('a'),'-rg')]"
            }
        }
```
Run `Import-AzBlueprintWithArtifact` against the blueprint.

You will receive the error `Import-AzBlueprintWithArtifact : 'Name' exceeds maximum length of '90'.`.

This occurs in `Az.Blueprint` 0.2.11.

**Comment by wasabii** [comment]
I believe this issue is actually in the Azure SDK at `https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/blueprint/Microsoft.Azure.Management.Blueprint/src/Generated/Models/ResourceGroupDefinition.cs`.

**Comment by wasabii** [comment]
The error is in `blueprint/Microsoft.Azure.Management.Blueprint/src/Generated/Models/ResourceGroupDefinition.cs:Validate`. I would love to fix it, but since the file is generated, I'm not sure of the best way to approach it. I do not know how it was generated, or what the proper procedure to override it is.

**Comment by wyunchi-ms** [comment]
Hi @wasabii , thanks for your feedback! This makes sense to me. I'm forward this issue to BluePrint team.

**Comment by apclouds** [comment]
Hello @wasabii, thanks for the feedback here. @alex-frankel, @filizt  is this something we can address on our end?

**Comment by apclouds** [comment]
Hi @wasabii, this has been added to our backlog for further investigation on our end.

**Comment by alex-frankel** [comment]
This is something we are not planning to fix, so I'm going to close
