### ISSUE TITLE
enable pipe between Get-AzVM and Get-AzVMExtension

### ISSUE THREAD

**Issue by skmkzyk** [Azure/azure-powershell#11557]
## Description of the new feature

Currently, Get-AzVM returns VM name with column name 'Name'.
But Get-AzVMExtension requires 'VMName' to specify VM name.
So, below cmdlet pipe is not working for now.
```
> get-azvm -name ephe01 -ResourceGroupName ephemeral-disks | Get-AzVMExtension
Get-AzVMExtension : The input object cannot be bound because it did not contain the information required to bind all mandatory parameters:  VMName
At line:1 char:60
+ ... m -name ephe01 -ResourceGroupName ephemeral-disks | Get-AzVMExtension
+                                                         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Azure...SVirtualMachine:PSObject) [Get-AzVMExtension], Param
   eterBindingException
    + FullyQualifiedErrorId : InputObjectMissingMandatory,Microsoft.Azure.Commands.Compute.GetAzureVMExtensionCommand
```
Is it happy to enable this type of cmdlet chaining?
This kind of disconnection will be occur other VM extension cmdlets.

**Comment by wyunchi-ms** [comment]
Hi @skmkzyk thanks for your feedback! I'm forwarding this issue to Compute team.

**Comment by Drewm3** [comment]
We will look into this request. Currently the cmdlet Get-AzVMExtension is auto-generated from the API specs. So we will need to augment the auto-generated cmdlet to also support an input object of type Microsoft.Azure.Commands.Compute.Models.PSVirtualMachine.

**Comment by Drewm3** [comment]
We are investigating the work to change not only this cmdlet, but also the ~50 additional cmdlets that also take a parameter in the form of "VMName" which could take the output from Get-AzVM as input into the cmdlet. Based on the outcome of our investigation into updating all of the relevant cmdlets we will provide an update on if/when this feature request will be taken.

**Comment by amjads1** [comment]
Working with SDK team to investigate and confirm on the efforts scope and options to change ~50 additional cmdlets in addition to the one highlighted on this issue. Expected to have an update on the timelines and next steps by end of July.

**Comment by amjads1** [comment]
In discussion with SDK team to understand the overall effort and timelines. I'm hoping to have an update by 8/7.

**Comment by amjads1** [comment]
Per discussion with the SDK team, the request to review scope and development effort/timelines to change ~50 additional cmdlets will be added to Sep/Oct sprint cycle. I will update back here post Sep/Oct sprint cycle.

**Comment by jaylabell** [comment]
To provide an update on this status, development on this fix will begin 1/26. More updates will be provided onward.

**Comment by Sandido** [comment]
Fix for this issue is currently under review.

**Comment by jaylabell** [comment]
Development has been completed for this feature!

**Comment by Sandido** [comment]
Bugfix has been released in this PS release: https://www.powershellgallery.com/packages/Az/5.5.0
