### ISSUE TITLE
AutoScale Issue 

### ISSUE THREAD

**Issue by NolanCui719** [Azure/azure-powershell#11556]
## Description
Symptom: 

The grain time cannot be set  to 1 min in PS cmdlet "Add-AzAutoscaleSetting" . The minimum with this PS command  is 5 minutes, but 1 min should be supported according to the doc and the deault value in portal .  

Regarding https://docs.microsoft.com/en-us/azure/azure-monitor/platform/powershell-quickstart-samples#create-and-manage-autoscale-settings  

## Steps to reproduce
When we set the Auto-Scale rule through the Azure Portal, we can see the Time grain is set as 1 min by default and it is immutable.  
![image](https://user-images.githubusercontent.com/17994605/79107268-ad137c80-7da6-11ea-8c37-6b15d322c006.png)

But when I set the auto-sale rule by Powershell using command New-AzAutoscaleRule, I set the Time grain as 1 min, it ran an error message saying " Time grain 'PT1M' for metric 'Percentage CPU' is not supported. The supported time grain is 'PT5M".  
![image](https://user-images.githubusercontent.com/17994605/79107299-bac90200-7da6-11ea-80e1-decf0c1b00c1.png)

$rule1 = New-AzAutoscaleRule -MetricName 'Percentage CPU' -MetricResourceId $webRoleResourceId -Operator GreaterThan -MetricStatistic Average -Threshold 70 -TimeGrain 00:01:00 -TimeWindow 00:10:00 -ScaleActionCooldown 00:05:00 -ScaleActionDirection Increase -ScaleActionValue 1  

After I change the Time Grain from TimeGrain 00:01:00 to 00:05:00, the rule was created successfully, as I checked from the portal, the Time Grain is 5 mins, and it is immutable.  
```powershell

```

## Environment data

```

```

## Module versions

```powershell

```
Regarding https://docs.microsoft.com/en-us/azure/azure-monitor/platform/powershell-quickstart-samples#create-and-manage-autoscale-settings  

## Debug output

```

```

## Error output

```

```

**Comment by wyunchi-ms** [comment]
Hi @NolanCui719 , thanks for your feedback. I'm forwarding this issue to service team.

**Comment by VeryEarly** [comment]
Hi @NolanCui719 

Thanks for your report, I'll look into it.

**Comment by VeryEarly** [comment]
Hi @NolanCui719 ,

I tried
```
$rule=New-AzAutoscaleRule -MetricName "Percentage CPU" -MetricResourceId /subscriptions/{subscription}/resourceGroups/yabo-test-group/providers/Microsoft.Compute/virtualMachineScaleSets/yabo-test-vmss -Operator GreaterThan -MetricStatistic Average -Threshold 70 -TimeGrain 00:01:00
```
```
$profile = New-AzAutoscaleProfile -Rule $rule -Name yabo-test-profile -DefaultCapacity 1 -MaximumCapacity 5 -MinimumCapacity 1
```
```
Add-AzAutoscaleSetting -Location eastus -Name yabo-test-setting -ResourceGroupName yabo-test-group -AutoscaleProfile $profile -TargetResourceId /subscriptions/{subscription}/resourceGroups/yabo-test-group/providers/Microsoft.Compute/virtualMachineScaleSets/yabo-test-vmss
```
Didn't have any error, please see response body:
```
Body:
{
  "id": "/subscriptions/{subscription}/resourceGroups/yabo-test-group/providers/microsoft.insights/autoscalesettings/yabo-test-setting",
  "name": "yabo-test-setting",
  "type": "Microsoft.Insights/autoscaleSettings",
  "location": "eastus",
  "tags": {},
  "properties": {
    "profiles": [
      {
        "name": "yabo-test-profile",
        "capacity": {
          "minimum": "1",
          "maximum": "5",
          "default": "1"
        },
        "rules": [
          {
            "metricTrigger": {
              "metricName": "Percentage CPU",
              "metricNamespace": "",
              "metricResourceUri": "/subscriptions/{subscription}/resourceGroups/yabo-test-group/providers/Microsoft.Compute/virtualMachineScaleSets/yabo-test-vmss",
              "timeGrain": "PT1M",
              "statistic": "Average",
              "timeWindow": "PT5M",
              "timeAggregation": "Average",
              "operator": "GreaterThan",
              "threshold": 70.0,
              "dimensions": null,
              "dividePerInstance": false
            },
            "scaleAction": {
              "direction": "Increase",
              "type": "ChangeCount",
              "value": "1",
              "cooldown": "PT5M"
            }
          }
        ]
      }
    ],
    "enabled": true,
    "name": "yabo-test-setting",
    "targetResourceUri": "/subscriptions/{subscription}/resourceGroups/yabo-test-group/providers/Microsoft.Compute/virtualMachineScaleSets/yabo-test-vmss",
    "notifications": null
  }
}
```
Please provide more detail how this issue can be reproduced.

**Comment by cj901014** [comment]
Hi, @VeryEarly , it is Cloud Service, not VMSS

**Comment by cj901014** [comment]
@VeryEarly 

Please try below script on the Cloud Service instance

# Get service info
$service = 'your-cloudservice'
$serviceProp = Get-AzResource -Name $service
$location = $serviceProp.location

# Setup web role
$webRole = 'WebRole1'
$prodWebRole = '/slots/production/roles/WebRole1'
$resourceGroup = $serviceProp.ResourceGroupName
$webRoleResourceId = $serviceProp.ResourceId + $prodWebRole
$webRoleProfile = $service + '-web-profile'
$webRoleAutoScaleSetting = $service + '-web-autoscale'



Write-Host 'Setup rule for web role $webRole'
# Scaleup rule by CPU metric for web role
$rule1 = New-AzAutoscaleRule -MetricName 'Percentage CPU' -MetricResourceId $webRoleResourceId -Operator GreaterThan -MetricStatistic Average -Threshold 70 -TimeGrain 00:01:00 -TimeWindow 00:10:00 -ScaleActionCooldown 00:05:00 -ScaleActionDirection Increase -ScaleActionValue 1
# Scaledown rule by CPU metric for web rol
$rule2 = New-AzAutoscaleRule -MetricName 'Percentage CPU' -MetricResourceId $webRoleResourceId -Operator LessThan -MetricStatistic Average -Threshold 25 -TimeGrain 00:01:00 -TimeWindow 00:30:00 -ScaleActionCooldown 00:05:00 -ScaleActionDirection Decrease -ScaleActionValue 1

Write-Host 'Setup profile for web role $webRole'
# AutoScale profile for web role
$webRoleProfile = New-AzAutoscaleProfile -DefaultCapacity 1 -MaximumCapacity 4 -MinimumCapacity 1 -Rule $rule1,$rule2 -Name $webRoleProfile


Write-Host 'Create autscale setting for web role $webRole'
# Create autoscale setting for web role
Add-AzAutoscaleSetting -Location $location -Name $webRoleAutoScaleSetting -ResourceGroup $resourceGroup -TargetResourceId $webRoleResourceId -AutoscaleProfile $webRoleProfile


You will get the error:
Add-AzAutoscaleSetting : Exception type: ErrorResponseException, Message: Time grain 'PT1M' for metric 'Percentage CPU' is not supported. The supported time grain is 'PT5M', Code: 
UnsupportedTimeGrain, Status code:BadRequest, Reason phrase: Bad Request
At line:29 char:1
+ Add-AzAutoscaleSetting -Location $location -Name $webRoleAutoScaleSet ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzAutoscaleSetting], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Autoscale.AddAzureRmAutoscaleSettingCommand

**Comment by VeryEarly** [comment]
Tried with cloud service,

Request from Portal:
https://management.azure.com/subscriptions/{subscription}/resourceGroups/yabo-test-group/providers/microsoft.insights/autoscalesettings/WebRole1-Autoscale-736?api-version=2015-04-01
```
{
   "location":"eastus",
   "tags":{},
   "properties":{
      "name":"WebRole1-Autoscale-736",
      "enabled":true,
      "targetResourceUri":"/subscriptions/{subscription}/resourceGroups/yabo-test-group/providers/Microsoft.ClassicCompute/domainNames/yabo-tets-dns/slots/Production/roles/WebRole1",
      "profiles":[
         {
            "name":"Auto created scale condition",
            "capacity":{
               "minimum":"1",
               "maximum":"2",
               "default":"1"
            },
            "rules":[
               {
                  "scaleAction":{
                     "direction":"Increase",
                     "type":"ChangeCount",
                     "value":"1",
                     "cooldown":"PT5M"
                  },
                  "metricTrigger":{
                     "metricName":"Percentage CPU",
                     "metricNamespace":"microsoft.classiccompute/domainnames/slots/roles",
                     "metricResourceUri":"/subscriptions/{subscription}/resourceGroups/yabo-test-group/providers/Microsoft.ClassicCompute/domainNames/yabo-tets-dns/slots/Production/roles/WebRole1",
                     "operator":"GreaterThan",
                     "statistic":"Average",
                     "threshold":70,
                     "timeAggregation":"Average",
                     "timeGrain":"PT1M",
                     "timeWindow":"PT10M",
                     "Dimensions":[],
                     "dividePerInstance":false
                  }
               }
            ]
         }
      ],
      "notifications":[]
   }
}
```
Request from Azure-PowerShell:
https://management.azure.com/subscriptions/{subscription}/resourcegroups/yabo-test-group/providers/microsoft.insights/autoscalesettings/yabo-tets-dns-web-autoscale?api-version=2015-04-01
```
{
  "properties": {
    "profiles": [
      {
        "name": "yabo-tets-dns-web-profile",
        "capacity": {
          "minimum": "1",
          "maximum": "4",
          "default": "1"
        },
        "rules": [
          {
            "metricTrigger": {
              "metricName": "Percentage CPU",
              "metricResourceUri": "/subscriptions/{subscription}/resourceGroups/yabo-test-group/providers/Microsoft.ClassicCompute/domainNames/yabo-tets-dns/slots/production/roles/WebRole1",
              "timeGrain": "PT1M",
              "statistic": "Average",
              "timeWindow": "PT10M",
              "timeAggregation": "Average",
              "operator": "GreaterThan",
              "threshold": 70.0
            },
            "scaleAction": {
              "direction": "Increase",
              "type": "ChangeCount",
              "value": "1",
              "cooldown": "PT5M"
            }
          }
        ]
      }
    ],
    "enabled": true,
    "targetResourceUri": "/subscriptions/{subscription}/resourceGroups/yabo-test-group/providers/Microsoft.ClassicCompute/domainNames/yabo-tets-dns/slots/production/roles/WebRole1"
  },
  "location": "eastus",
  "tags": {}
}
```

cmdlet failed as described

**Comment by asheniam** [comment]
This is currently a doc bug.  For Cloud Services (Microsoft.ClassicCompute), we only support a minimum of 5 minutes (PT5M) and for others, we support a minimum of 1 minute (PT1M).
