### ISSUE TITLE
Unable to run a powershell script from Azure function app within ADF

### ISSUE THREAD

**Issue by SafwanHussain** [Azure/azure-powershell#11565]
I have a powershell script which will create metric alerts on a cosmos container, i am running this script from an Azure Function app. While this works fine but when i want to invoke the function app from azure data factory using Function Activity, it throws the following error:
"Response Content is not a valid JObject. "
i have tried converting the function return type to Json using ConvertTo-Json but the error still persists.
i have also tried converting the function return type to PSCustomObject, still does't help.

Please let me know if i am missing something here or doing something wrong.

More details :

method : Post

Body in the Fucntion Activity (ADF) :
{
"action":"create",
"date":"',formatDateTime(pipeline().parameters.windowStart, 'yyyyMMdd'),'"
}

**Comment by wyunchi-ms** [comment]
Hi @SafwanHussain thanks for your feedback! I'm finding some team members from Function team to help you.

**Comment by SafwanHussain** [comment]
update : I have found the solution
The Azure function activity expects a JObject response from the function, when i was passing the function return value as response, it was a JArray object.
So i created a json string that dynamically take values based on attributes from the above jarray, and then pass this json string as the response object.
