### ISSUE TITLE
Update-AzCosmosDBAccountRegion fails with "List of supplied locations is invalid" when passing String[]

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#11560]
When attempting to update an account from one region (e.g. East US) to two regions (e.g. East US, West US) using string array parameter set, getting "List of supplied locations is invalid error".

**Comment by plzm** [comment]
![Update-AzCosmosDBAccountRegion](https://user-images.githubusercontent.com/35011873/79120731-98f95c00-7d61-11ea-9e8b-31e7d0e17ca9.png)

**Comment by plzm** [comment]
Note that Update-AzCosmosDBAccountRegion succeeds as expected if PSLocationObject[] is passed instead of the array of string location names.

**Comment by MehaKaushik** [comment]
This should have been resolved in Az.CosmosDB 0.1.4 https://www.powershellgallery.com/packages/Az.CosmosDB/0.1.4

**Comment by lszomoru** [comment]
@MehaKaushik, could you please confirm that this is indeed fixed in 0.1.4 as I am asking as I am still seeing the error. Thanks!

**Comment by MehaKaushik** [comment]
@lszomoru please note that you need to provide your existing locations in the same order as failover priorities and then the new location you want to add. Can you please share the exact command you used and the output ? 
Would be helpful, if you dont mind sharing the how the Locations object look like from the result of your Get-AzCosmosDBAccount cmdlet.

**Comment by MehaKaushik** [comment]
Can you also check the version of Az.CosmosDB, since the module is not GA'ed it is not updated with the Az module, need to update it separately.

**Comment by lszomoru** [comment]
@MehaKaushik, I have tracked down the issue to an incorrect order of the existing locations. Thanks for your help!
