### ISSUE TITLE
HANDOFF: AzureRm.KeyVault for ARM 1.0 Preview

### ISSUE THREAD

**Issue by SarahRogers** [Azure/azure-powershell#1157]
An updated help.xml file for AzureRm.KeyVault is ready to be added to the code for Azure PowerShell 1.0 Preview. 

I'm unable to attach it as an xml file or txt file. (I get a message that I need write permissions.)

You can grab the help.xml file at: \\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\AzureKeyVault\Latest\2015-10-12.15_57_06\OutPut\OnBox 

Let me know if you have any questions.

Thanks,
~Sarah Rogers | PM | PowerShell Help Publishing

**Comment by devigned** [comment]
This is out of date. Closing.
