### ISSUE TITLE
Array fails when using @paramObject on New-AzResourceGroupDeployment with ConvertFrom-Json

### ISSUE THREAD

**Issue by brucedkyle** [Azure/azure-powershell#11579]
I'm trying to pass in a $paramObject into a new ARM template deployment.  

(My goal in all this... I want copy the parameter values shown in the portal and pass them for a deployment using a template that is also generated in the portal, but without using a param file.)

I think I am missing something in my PowerShell to correctly convert the arrays so they can be used in the template.

```powershell
$ResourceGroupName = "rg-testtemplate"
    New-AzResourceGroup -Name "rg-testtemplate" -Location "West US"

    $addressPrefixes = '["10.0.0.0/24"]' | ConvertFrom-Json
    $subnet = '[{"name":"default","properties":{"addressPrefix":"10.0.0.0/24"}}]' | ConvertFrom-Json

    $paramObject = @{
        'addressPrefixes' = $addressPrefixes
        'subnets' = $subnet
        'virtualNetworkName' = "vnet-testtemplate"
    }

    $parameters = @{
         'ResourceGroupName'     = $ResourceGroupName
         'TemplateFile'          = '.\testpowershell.json'
         'TemplateParameterObject'    = $paramObject
        'Verbose'               = $true
    }

    New-AzResourceGroupDeployment @parameters 
```
It seems like $addressPrefixes abd $subnets are arrays. So I deploy the template as **.\testpowershell.json**  addressPrefixes and subnets are prescribed as arrays in the template.
```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "addressPrefixes": {
      "type": "array"
    },
    "subnets": {
      "type": "array"
    },
    "virtualNetworkName": {
      "type":  "string"
    }
  },
  "resources": [
    {
      "name": "[parameters('virtualNetworkName')]",
      "type": "Microsoft.Network/virtualNetworks",
      "apiVersion": "2019-09-01",
      "location": "West US",
      "properties": {
        "addressSpace": {
          "addressPrefixes": "[parameters('addressPrefixes')]"
        },
        "subnets": "[parameters('subnets')]"
      }
    }
  ]
}
```

When I deploy, I get an error:

```text
   New-AzResourceGroupDeployment : 8:35:23 AM - Error: Code=InvalidTemplate; Message=Deployment template validation
failed: 'Template parameter JToken type is not valid. Expected 'Array'. Actual 'Object'. Please see
https://aka.ms/resource-manager-parameter-files for usage details.'.
At D:\repo\foldername\TestVM\testpowershelldeploy.ps1:30 char:5
+     New-AzResourceGroupDeployment @parameters
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
New-AzResourceGroupDeployment : The deployment validation failed
At D:\repo\foldername\TestVM\testpowershelldeploy.ps1:30 char:5
+     New-AzResourceGroupDeployment @parameters
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzResourceGroupDeployment], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
```
## Proposed implementation details (optional)

I am hoping for an example or a CmdLet that allows me to convert the parameter using the value shown in the portal and pass it back into the template as part of a paramObject.

What have I missed?

**Comment by dcaro** [comment]
@brucedkyle I have been able to do your deployment using the following code, can you please confirm if this fix your issue? 

```
    $ResourceGroupName = "testdcaro2"
    $Location = "West US"
    New-AzResourceGroup -Name $ResourceGroupName -Location $Location

    $addressPrefixes = @('10.0.0.0/24')
    $subnet = @{ name ="default"
                 properties = @{
                    addressPrefix = '10.0.0.0/24'
                }}

    $paramObject = @{
        'addressPrefixes' = $addressPrefixes
        'subnets' = @($subnet)
        'virtualNetworkName' = "vnet-testtemplate"
    }

    $parameters = @{
         'ResourceGroupName'     = $ResourceGroupName
         'TemplateFile'          = '.\testpowershell.json'
         'TemplateParameterObject'    = $paramObject
        'Verbose'               = $true
        'Debug'                 = $true
    }

New-AzResourceGroupDeployment @parameters 
```

**Comment by brucedkyle** [comment]
That's an awesome fix for this particular issue. Many thanks. And it helps me understand the PowerShell object array/hashtable/object ideas.  

If I understand your response correctly, are you telling me that  `ConvertFrom-Json` is the wrong tool? Or is there perhaps there is a parameter that I am missing? Are you saying that there is not a Cmdlet that can help me automate my task in taking Json and making it into an object that the `New-AzResourceGroupDeployment` accepts as an array?

To clarify, the issue I am raising -- it would be awesome to have a way to take the JSON in a single line and turn it into PowerShell that works with Azure templates. It can be error-prone when you are adding arrays get nested inside other arrays inside a hash table. For example, when you can doing disks inside of VMs attached.

Did I miss an easy way to convert the Json without having to write a string processing Cmdlet?

Seems to me that it might be a feature request on `ConvertFrom-Json` or a bug in `New-AzResourceGroupDeployment`

**Comment by dcaro** [comment]
`Convert-FromJson` convert a JSON object into a PowerShell custom object as per https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-7 but the template is expecting arrays.

`$addressPrefixes = '["10.0.0.0/24"]' | ConvertFrom-Json` returns a string and the deployment template is expecting an array.
The subnet was understood as a PSObject but the template was also expecting an array.

**Comment by dcaro** [comment]
If there are no further questions, I'm closing this issue.
