### ISSUE TITLE
user session control ?

### ISSUE THREAD

**Issue by ghost** [Azure/azure-powershell#11608]
How to maintain the session timeout?

**Comment by dingmeng-xue** [comment]
@VGSandZ, could you show your detail issues?

**Comment by VGSandZ** [comment]
i have colleagues working on shared systems and want the timeout the session stays once the user is done. if the Logout-AZAccount is not done. I mean one user session could be easily hijackd. As everyone is admin on the shared systems.

**Comment by dingmeng-xue** [comment]
For this case, Disconnect-AzAccount is required. Or, you can Disable-AzContextAutosave and only keep context in memory.

**Comment by dingmeng-xue** [comment]
@VGSandZ, do you still need further clarification?
