### ISSUE TITLE
Equivalent commands in AZ powershell for New-CosmosDbContex and Get-CosmosDbDocument

### ISSUE THREAD

**Issue by SafwanHussain** [Azure/azure-powershell#11610]
i have a requirement to read the cosmosdb document from a container using a powershell script. I have Az module installed.
i came across some commands like New-CosmosDbContex and Get-CosmosDbDocument but soon realized that they are part of AzureRM module, i was not able to find equivalent commands in Az Module.
Also i came across this command which if i understood correctly would enable AzureRM alias and help me run the RM module commands in AZ.

'Enable-AzureRmAlias -Module CosmosDB' but this gives error 'Module 'CosmosDB' is not a valid Az module' even after installing and importing the Az.CosmosDB module.

Is there anything i am missing, or is there any other way to read the cosmosdb document using Az powershell module , please let me knew.

**Comment by dingmeng-xue** [comment]
Included Cosmos team to look into this issue.

**Comment by SafwanHussain** [comment]
Hi,
Any update on this issue?

**Comment by MehaKaushik** [comment]
Hi @SafwanHussain 
Thank you for opening this issue. As of today, the above cmdlets are not included in Az.CosmosDB. 
Az.CosmosDB exposes Resource Provider(Control Plane) APIs, as of today.

**Comment by markjbrown** [comment]
We are exploring creating PowerShell cmdlets across our data plane api but this is not committed. 

We do have a work around however with our PowerShell Rest API samples here, https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi

Hope this is helpful.

**Comment by MehaKaushik** [comment]
@SafwanHussain Please open this issue again, if you have further concerns.

**Comment by wonderphil** [comment]
Well, that's just like Microsoft, forcing us to use the new versions of something but not actually make it backwards compatible.
I have a 100s of PowerShell scripts that are changing data in cosmos and have been told to move over to Powershell Az and the workaround is using rest API's, lets make it hard for people.

Is there any update to creating PowerShell cmdlets across our data plane api, seems a bit rude not to when you forcing everyone of azurerm

**Comment by markjbrown** [comment]
It's unlikely we will create PS cmdlets for our data plane.

Can use this as an alternative though. Not supported by MS however, https://github.com/PlagueHO/CosmosDB

**Comment by wonderphil** [comment]
Thanks @markjbrown that looks a lot better then using the rest apis
