### ISSUE TITLE
[error]Exception calling "ExecuteNonQuery" with "0" argument(s): "Incorrect syntax near 'GO'.

### ISSUE THREAD

**Issue by himmyaggarwal** [Azure/azure-powershell#11627]
## I am trying to automate to create DDLs in azure sql database using azure powershell.
i am using below script
param
(
    [parameter(Mandatory = $false)] [String] $server,
    [parameter(Mandatory = $false)] [String] $database,
    [parameter(Mandatory = $false)] [String] $adminName,
    [parameter(Mandatory = $false)] [string] $adminPassword
    
)
$connectionString = "Server=$server;Database=$database;User ID=$adminName;Password=$adminPassword;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
$connection = New-Object -TypeName System.Data.SqlClient.SqlConnection($connectionString)

$AdfProjectFolder = (Get-Item -Path $PSScriptRoot).Parent.Parent.FullName + "\sql"

$queryPath = Get-ChildItem "$AdfProjectFolder\*.sql"

foreach($query in $queryPath)
{

$query = [System.IO.File]::ReadAllText($queryPath)

$command = New-Object -TypeName System.Data.SqlClient.SqlCommand($query, $connection)

$connection.Open()
$command.ExecuteNonQuery()
$connection.Close()
}

sql

## sql file

CREATE LOGIN [DEV_DATABASE] WITH PASSWORD=*******'
GO

ALTER LOGIN [DEV_DATABASE] DISABLE
GO

while exectuting the script i am getting error as mentioned. kindly help.

**Comment by dingmeng-xue** [comment]
@himmyaggarwal , I didn't get which cmdlet of Azure PowerShell is used. Could you clarify further?

**Comment by himmyaggarwal** [comment]
> @himmyaggarwal , I didn't get which cmdlet of Azure PowerShell is used. Could you clarify further?

powershell version - 4.167.0

**Comment by mlopandic** [comment]
You have a quote at the end of password 

> *******'

I believe that will fix your problem.

**Comment by priyarani477** [comment]
Hi himmyaggarwal

I'm also working on the same implementation, running .sql files using powershell and facing the same error.
Did you find any solution of it.
Please share.
