### ISSUE TITLE
webapp: support connecting privately to a Web App using Azure Private Endpoint

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-powershell#11622]
## Description of the new feature
The following feature is supported in preview on portal https://docs.microsoft.com/en-us/azure/private-link/create-private-endpoint-webapp-portal
and needs PowerShell equivalent.

## Proposed implementation details (optional)
Here are the details on the commands to support from feature crew

Command | CLI | PowerShell | Description
-- | -- | -- | --
Get Private Endpoint ConnectionTakes: site info + private endpoint connection nameReturns: private endpoint connection info | Az webapp privatelink list | Get-AzWebAppPrivateLink | Gets the details.  If the optional private endpoint name is specified, will return the details for just that one private endpoint.  If just the app name is specified, will return the details for all of the private endpoints on that appArguments: sitename, optional:private endpoint name
Delete Private Endpoint ConnectionTakes: site info + private endpoint connection name | Az webapp privatelink delete | Delete-AzWebAppPrivateLink | Removes a private endpoint from an app. Arguments: sitename private endpoint name
Approve Private Endpoint ConnectionTakes: site info + private endpoint connection nameReturns: private endpoint connection info | Az webapp privatelink approve | Set-AzWebAppPrivateLink | Sets the approve status on  requested private endpoint connection with an appCLI Arguments: sitename private endpoint name Powershell Arguments: sitename private endpoint name  "approve"
Reject Private Endpoint ConnectionTakes: site info + private endpoint connection nameReturns: private endpoint connection info | Az webapp privatelink reject | Set-AzWebAppPrivateLink | Sets the reject status on  requested private endpoint connection with an appCLI Arguments: sitename private endpoint name Powershell Arguments: sitename private endpoint name  "reject"

CLI command link https://github.com/Azure/azure-cli/issues/13072

Here is the api for the private endpoint connections:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2019-08-01/WebApps.json#L14885
 
Here is the api for get private resources:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2019-08-01/WebApps.json#L15068

**Comment by panchagnula** [comment]
@btardif FYI

**Comment by Kotasudhakarreddy** [comment]
started looking in to it.

**Comment by panchagnula** [comment]
We need new SDK & swagger updates that will release in early September we will take a new SDK after this & release this along with the other breaking changes release in October.

**Comment by panchagnula** [comment]
We need to do this after we get the latest SDK changes to master - and add support as follows instead of the full list of commands https://github.com/Azure/azure-powershell/pull/12302/files

**Comment by Kotasudhakarreddy** [comment]
> We need to do this after we get the latest SDK changes to master - and add support as follows instead of the full list of commands https://github.com/Azure/azure-powershell/pull/12302/files

Sure Sisira.

**Comment by Kotasudhakarreddy** [comment]
@panchagnula still these set of commands are required to consider for the development.

**Comment by panchagnula** [comment]
I thought this was completed by adding the webapp support to Private endpoint commands directly.

**Comment by Kotasudhakarreddy** [comment]
Closing since the support is already enabled with the Private endpoint commands directly.
