### ISSUE TITLE
Get-AzureKeyVaultSecret documentation could be improved to mention SecretValueText

### ISSUE THREAD

**Issue by jeffwilcox** [Azure/azure-powershell#1163]
Hi,
The MSDN documentation for the `Get-AzureKeyVaultSecret` cmdlet, as well as the cmdlet help itself, could be improved.

While working on a hackathon with some people to use Key Vault, and verifying that the basics were working, we had to go to source to actually search for the model type to get the `SecretValueText` call/param for the returned secret.

Seems like the perfect kind of thing to just have in the cmdlet help to help n00bs like myself in this area.

**Comment by pomortaz** [comment]
Thanks @jeffwilcox. We tried to addressed this by adding an example of SecretValueText to the MSDN documentation: https://msdn.microsoft.com/en-us/library/dn868047.aspx

**Comment by cormacpayne** [comment]
This has been fixed. Closing this issue.
