### ISSUE TITLE
New-AzStorageAccount -Force

### ISSUE THREAD

**Issue by DanielLarsenNZ** [Azure/azure-powershell#11631]
## Description of the new feature
`-Force` switch for `New-AzStorageAccount` to allow the cmdlet let to be idempotent / used in scripts that are re-runnable (without checking if Storage Account exists). This behaviour would then be consistent with `New-AzResourceGroup`, `New-AzVirtualNetwork` and several other cmdlets.

## Proposed implementation details (optional)
```
New-AzStorageAccount -ResourceGroupName 'myrg' -Name 'mystorage' -Location $location -SkuName 'Standard_LRS' -Force
```

When `-Force` switch is present, cmdlet will not throw error if Storage Account already exists.

**Comment by blueww** [comment]
@DanielLarsenNZ

Server will report error when create account on an existing account name, so from Powershell, we can't make it success to create account with existing account name.
Besides that, as the parameter input in create account cmdlet might be different than existing account with same name, so we also can't report success in this case. 
So we have to report failure as the account already exist.

If you just want to update the properties of existing account, please use Set-AzStorageAccount.

**Comment by blueww** [comment]
@DanielLarsenNZ
I will close the issue as not hear from you for a long time.
Feel free to contact use again if you need any further assistance for Azure PowerShell.
