### ISSUE TITLE
New-AzureRMRoleAssignment reporting 404 not found for ADFS group

### ISSUE THREAD

**Issue by hawesr** [Azure/azure-powershell#11648]
## Description

Unable to add via ADFS Azure Stack setups

## Steps to reproduce

Add-AzureRmEnvironment -name admin -ARMEndpoint https://adminmanagement.local.azurestack.external
 
Add-AzureRmAccount -Environment admin
 
#Connect to AD to create the universal AD Group and add a User
$cred=get-credential
winrm s winrm/config/client '@{TrustedHosts="x.x.x.x"}'
$group=invoke-command -ComputerName x.x.x.x -ScriptBlock {
 
New-ADGroup -Name "UniversalGroup" -SamAccountName UniversalGroup -GroupCategory Security -GroupScope Universal |Out-Null
Add-ADGroupMember -Identity "UniversalGroup" -Members TestUser|Out-Null
Get-ADGroup -Identity "UniversalGroup"
 
} -Credential $cred
 
 
 
$sub=Get-AzureRmSubscription -SubscriptionName "Default Provider Subscription"
 
New-AzureRmRoleAssignment -ObjectId $group.sid -RoleDefinitionName Contributor -Scope "/subscriptions/$sub" 
 

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```
Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "Service principal 'S-x-x-x-xxxxxxxxxx-xxxxxxxxx-xxxxxxxxx-xxxx'' not found."
  }
 

```

**Comment by dingmeng-xue** [comment]
@bganapa, could you help to check if we support this case?

**Comment by TheOnlyWei** [comment]
@hawesr 
1. What AzureStack context did you log in to execute the command? 
2. Is Enable-AzureRmContextAutoSave enabled or disabled?
3. Which line is producing the error? Can we get the full error output with -Debug and -Verbose flags?
