### ISSUE TITLE
Suggestion: Provide a way to get the Bearer token from authentication

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#1164]
If the bearer token could be returned from login-azurermaccount/add-azureaccount it would be a lot easier to interact with the rest api's directly, as we wouldn't have to implement our own authentication logic. For example a "-force" param to the two cmdlets above could have the returned object contain the bearer token.

**Comment by markcowl** [comment]
@trondhindenes It is by design that we do not return the bearer token.  Returning the token for use elsewhere would be a security issue.  Note that you can provide your own bearer token to the cmdlets using 

```
Add-AzureRmAccount -AccessToken...
```

**Comment by trondhindenes** [comment]
gotcha. I see your point. I was just thinking that since it's already pretty easy to pick up the token by looking at http traffic while logging in, you might as well surface the token. That said, I understand the decision.

**Comment by markcowl** [comment]
@trondhindenes One thing we've though about is exposing Invoke-AzureRestMethod so people could invoke a generic rest api using the current authentication context.  Would that fit your scenario?  It would not only allow you to use the token, but automatically refresh it when it expires.

**Comment by trondhindenes** [comment]
Very interesting!

**Comment by markcowl** [comment]
@trondhindenes I'm curious whether the generic cmdlets for Invoke-AzureRmResourceAction  are similar to what you want, or whether the Invoke-AzureRestMethod is still something you would like to see.

**Comment by markcowl** [comment]
@trondhindenes Closing for now, as I'm guessing Invoke-AzureRmRestAction likely does what you need.  If you would like a more generic Invoke-Rest-Method using our authentication, please file a new issue and we will consider for a near-term release.

**Comment by knom** [comment]
Hi,
I would like an Invoke-Rest-Method rather than RestAction.
For instance I'd like to call this here.. https://docs.microsoft.com/en-us/rest/api/advisor/recommendations
From within Powershell.

Which is not working with the RestAction approach..
(at least I cannot get it working..)

Any suggestions?

Thanks.
