### ISSUE TITLE
Request: Add ability to get existing Azure AD Application

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-powershell#1165]
There are commands for new & remove AD Applications, but it would be great to be able to get an existing application. i.e. `Get-AzureRmADApplication`

Specifically to get the client id for configuring app settings when deploying web applications.

**Comment by buchizo** [comment]
+1

**Comment by m-moris** [comment]
+1. I agree with you. I need "Get-AzureRmAdApplication" command too.

**Comment by mbsnl** [comment]
+1

**Comment by rdhardwick** [comment]
Get-AzureRmADServicePrincipal or Get-MsolServicePrincipal are both options for listing applications and getting their Client IDs. However, I cannot find a way to get the expiration dates for the client secrets... The closest thing I found was Get-MsolServicePrincipalCredential, but it does not return all the keys as I would expect. How can we track when a key is going to expire?

**Comment by Minte6** [comment]
+1

**Comment by Minte6** [comment]
https://msdn.microsoft.com/en-us/library/mt679004.aspx

**Comment by damienpontifex** [comment]
Perfect thanks @Minte6 just what I was looking for!
