### ISSUE TITLE
Errors when attempting to install PowerShellGet

### ISSUE THREAD

**Issue by miksan92k** [Azure/azure-powershell#11656]
## Description
If I run an Update-Modoule PowerShellGet -force
I receive the error that PowerShellGet was not installed using Install-Module

If I try to install PowerShellGet using -allowclobber and -force 
I receive the error that states:
The module 'PowerShellGet' cannot be installed because the catalog signature in 'PowerShellGet.cat' does not match the hash generated from the module.

**Comment by dingmeng-xue** [comment]
@miksan92k, thanks for your try. PowerShellGet doesn't belong to Azure PowerShell. Please raise your issue to https://github.com/PowerShell/PowerShellGet/issues. 

Sorry for inconvenience.
