### ISSUE TITLE
WebApp:deployments are running on Azure DevOps Hosted Agents is failing intermittent for different application on one resource group

### ISSUE THREAD

**Issue by v-hhk** [Azure/azure-powershell#11659]
## Description
deployments are running on Azure DevOps Hosted Agents
¬The deployment script is very complicated but it ultimately comes down to one line: 

`$null = Publish-AzWebApp -Name $AppName -ResourceGroupName $ResourceGroupName -ArchivePath $ZipPath -Force`
The customer run a new deployment against the problematic resource group (xxxxxxx) 
with `-Verbose` appended and the $DebugPreference set to ‘Continue’. 
Within the same deployment, 2 apps successfully deployed before the third failed.

Here is a list of all the web apps and function apps that customer is attempting to deploy in the order that they deploy.

Web apps:

Function apps:

Web jobs (technically a web app):

 
! The customer reported that currently deployment only to this RG:  is failing.

ERROR:
2020-04-14T12:40:36.9457414Z Deploying web app xxxxxx from d:\a\r1\a\_Saltash\drop\xxx.Api.zip
2020-04-14T12:42:17.2974358Z Publish-AzWebApp : One or more errors occurred. (A task was canceled.)
2020-04-14T12:42:17.2975741Z At D:\a\r1\a\_Utilities\xxxx.Powershell\DeployHelpers.ps1:680 char:13
2020-04-14T12:42:17.2983304Z +     $null = Publish-AzWebApp -Name $AppName -ResourceGroupName $Resou …
2020-04-14T12:42:17.2984220Z +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-04-14T12:42:17.2986013Z + CategoryInfo          : CloseError: (:) [Publish-AzWebApp], AggregateException
2020-04-14T12:42:17.2986942Z + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.PublishAzureWebAppCmdlet
2020-04-14T12:42:17.5450995Z ##[error]Script failed with error: Error: The process 'C:\Program Files\PowerShell\7\pwsh.exe' failed with exit code 1

Shivangi Mittal from ICM 183242872 advise me to raise the issue here since it's directly related with the PowerShell, he was able to reproduce it and it's working for him. For the customer it's working locally as well but on the DevOps hosted agent it's failing only on that RG: xxxxx

Please reach out over email if you for additional details.
--

**Comment by dingmeng-xue** [comment]
@v-hhk, could you share version of Az, DeployHelpers.ps1, and DevOps task information to us? Could you confirm if there is issue when you try the same scripts locally?

**Comment by v-hhk** [comment]
The same scripts locally are working every single time without error. Let me get back to you with the Az version and DeployHelpers.ps1.

Thank you,
Hristo

**Comment by dingmeng-xue** [comment]
According to the log below, the first step of fetching credentials works in `Publish-AzWebApp`. But others logic contains error. Please check if URL returned in scmUri (I have masked below but user can find it in debug message) can be accessed in DevOps environment.
```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/5be4a3b4-4757-4d55-bef7-61ab598ea10c/resourceGroups/myairops-flight-aero-beta-rg/providers/Microsoft.Web/sites/myairops-flight-aero-beta-authorization-api/config/publishingcredentials/list?api-version=2018-11-01

Headers:
x-ms-client-request-id        : 98358f6c-54e0-43a8-afef-c02ed0b53b37
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 5950b1fd-1aec-4c84-b8dc-863524714ef6
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-resource-requests: 11999
x-ms-correlation-request-id   : 138dd264-cfdf-4a14-96b4-95f93ea2bcf3
x-ms-routing-request-id       : NORTHEUROPE:20200406T145036Z:138dd264-cfdf-4a14-96b4-95f93ea2bcf3
X-Content-Type-Options        : nosniff
Date                          : Mon, 06 Apr 2020 14:50:36 GMT

Body:
{
  "id": "/subscriptions/5be4a3b4-4757-4d55-bef7-61ab598ea10c/resourceGroups/myairops-flight-aero-beta-rg/providers/Microsoft.Web/sites/myairops-flight-aero-beta-authorization-api/publishingcredentials/$myairops-flight-aero-beta-authorization-api",
  "name": "myairops-flight-aero-beta-authorization-api",
  "type": "Microsoft.Web/sites/publishingcredentials",
  "location": "East US",
  "tags": {},
  "properties": {
    "name": null,
    "publishingUserName": "******",
    "publishingPassword": "******",
    "publishingPasswordHash": null,
    "publishingPasswordHashSalt": null,
    "metadata": null,
    "isDeleted": false,
    "scmUri": "******"
  }
}
```

**Comment by panchagnula** [comment]
@v-hhk any updates here - since you mentioned the commands works locally but not devops pipeline?

**Comment by v-hhk** [comment]
Hello, the issue can be closed, because the customer delete this deployment and had another issue for which we are working on a separate chain. Thanks.

**Comment by ThejaChoudary** [comment]
Thank You  @v-hhk  for Confirmation.Proceeding to close.
