### ISSUE TITLE
Unable to import AzResourceGraph module

### ISSUE THREAD

**Issue by smneti** [Azure/azure-powershell#11651]
## Description
Unable to import AzResourceGraph module

I have tried to install the AzResourceGraph module through the command: 
"Install-Module -Name Az.ResourceGraph -RequiredVersion 0.7.1"
but cannot proceed further with installation. 

Error:  
PS C:\Users\user1>Install-Module -Name Az.ResourceGraph -RequiredVersion 0.7.1 -scope currentuser
WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/Az.ResourceGraph/0.7.1' is not valid.
PackageManagement\Install-Package : Package 'Az.ResourceGraph' failed to download.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\snethi...urceGraph.nupkg:String) [Install-Package], Exception
    + FullyQualifiedErrorId : PackageFailedInstallOrDownload,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

Hence i have manually installed the module through .nupkg file. However I am unable to import the "az.resourcegraph.0.7.6" module from powershell. The following error is seen when I use commands within the module:

Error:
PS C:\Users\user1>Import-Module Az.ResourceGraph
Import-Module : Could not load file or assembly 'file:///C:\Program 
Files\WindowsPowerShell\Modules\Az.ResourceGraph\Microsoft.Azure.Management.ResourceGraph.dll' or one of its dependencies. Operation is not 
supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module Az.ResourceGraph
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

Please help fix this issue in 2 ways:
1. Why I am not able to install through the command?
2. When I do a manual install of module, why does it not import?

**Comment by dingmeng-xue** [comment]
@smneti , The URL `https://www.powershellgallery.com/api/v2/package/Az.ResourceGraph/0.7.1` is accessible. Could you try the link using browser? or is there any special network constrains?

BTW, what version of Windows PowerShell is? The version of PowerShellGet is very old. You can try after upgrade that module. 

For second question, please restart powershell and import again. If you still has issue, could you let me know how you installed them manually? I'd like to try your steps.

**Comment by smneti** [comment]
> @smneti , The URL `https://www.powershellgallery.com/api/v2/package/Az.ResourceGraph/0.7.1` is accessible. Could you try the link using browser? or is there any special network constrains?
> 
> BTW, what version of Windows PowerShell is? The version of PowerShellGet is very old. You can try after upgrade that module.
> 
> For second question, please restart powershell and import again. If you still has issue, could you let me know how you installed them manually? I'd like to try your steps.

- The URL () is accessable from browser, as it downloads the package file as and when hit, hence we could rule out the network issue.
- PSVersion is : 5.1.16299.1146

- Powershell Get module version is 1.0.0.1
Packagemenagement version is : 1.0.0.1

- Tried to upgrade the Powershell Get module (through command :  Find-Module powershellget | Install-Module) and I see the same error:

WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.6' is not valid.
PackageManagement\Install-Package : Package 'PackageManagement' failed to download.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1912 char:34
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\user1...anagement.nupkg:String) [Install-Package], Exception
    + FullyQualifiedErrorId : PackageFailedInstallOrDownload,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

However I have installed Powershell ver 7.0 with the latest AZ modules. And using the Powershell ver 7 through "Visual Code" has helped me proceed further with my scripts, thus fixing the issue I reported. 
@dingmeng-xue: Appreciate you help in responding back to my query.

I have followed the instructions provided in the below mentioned link to manually deploy the .nupkg file:
https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-packages/manual-download?view=powershell-7

**Comment by dingmeng-xue** [comment]
@smneti, thank for the information. PowerSHellGet is too old and you can not use it to upgrade itsself.

Just want to double confirm your issue. Do you still have the same issue that ResourceGraph cannot be imported on PowerShell 7?

**Comment by smneti** [comment]
It is good that I now know that the issue is caused due to older version of PowershellGet. Thanks for providing a confirmation on this,

With Powershell 7 I am good, with no issues in using the Az.ResourceGraph module. 

I thank you once again on checking this.

**Comment by dingmeng-xue** [comment]
Great. Welcome contacting us if you meet any issue. Close this issue now.
