### ISSUE TITLE
New-AzureRmRoleAssignment: -ServicePrincipalName parameter is misnamed

### ISSUE THREAD

**Issue by nmackenzie** [Azure/azure-powershell#1166]
The -ServicePrincipalName parameter to the New-AzureRmRoleAssignment seems to be misnamed since the parameter takes an ApplicationId NOT a service principal name. For example, the [following](https://azure.microsoft.com/en-us/documentation/articles/resource-group-authenticate-service-principal/) comes from the official Azure documentation:

New-AzureRmRoleAssignment -RoleDefinitionName Reader **-ServicePrincipalName $azureAdApplication.ApplicationId**

**Comment by cormacpayne** [comment]
This has been fixed. Closing this issue.

**Comment by seansaleh** [comment]
@cormacpayne Can you please link to the commit where it was fixed and what it was changed to?

**Comment by cormacpayne** [comment]
@nmackenzie @seansaleh oops, I misread the issue and thought it had been resolved. That's my fault. Let me re-open the issue.

**Comment by andyjballgit** [comment]
I just hit this issue with 4.4.0 of AzureRM.Resources , will it be fixed ?

**Comment by cormacpayne** [comment]
@darshanhs90 Hey Haridarshan, would you mind taking a look at this issue?

**Comment by andyjballgit** [comment]
thx , a quick win would be to update help / add an .example.

**Comment by darshanhs90** [comment]
updated the help with an example in this pr 
https://github.com/Azure/azure-powershell/pull/5095
