### ISSUE TITLE
Get-AZAutomationUpdateManagementAzureQuery 

### ISSUE THREAD

**Issue by AndrewSmithRS** [Azure/azure-powershell#11679]
## Description of the new feature
Get-AZAutomationUpdateManagementAzureQuery - retrieve AzureQueries that have been used.
## Proposed implementation details (optional)
I'm trying to obtain the content of existing Deployment configurations that have been created however Get-AzAutomationSoftwareUpdateConfiguration does not contain any reference to the query that has been used. If this is stored can this information be retrieved?

**Comment by dingmeng-xue** [comment]
I include Automation team to evaluate this new feature.

**Comment by zjalexander** [comment]
The product group does look at feature requests over on https://feedback.azure.com/forums/905242-update-management so I would suggest cross-posting there to track and get upvotes.

**Comment by zjalexander** [comment]
Thanks for suggesting this feature. It has been added to the backlog.

**Comment by bwarren18** [comment]
The AzureQuery property values are returned by Get-AzAutomationSoftwareUpdateConfiguration if it is run on a single update configuration.  It is nested under UpdateConfiguration.Targets.AzureQueries.  If you run the command to get all update configurations the value is null. You could get a list of all updateconfigurations and then iterate over each one with the same command to get all the values.

If you run the REST API call to list all deployments it actually returns all the properties and values.
