### ISSUE TITLE
Remove-AzureRmResourceGroup does not print out progress / status like New-AzureRmResourceGroupDeployment

### ISSUE THREAD

**Issue by clamanna** [Azure/azure-powershell#1167]
This makes it hard to debug / understand why the cmdlet is hanging if one of the resources cannot be deleted (e.g. a VM belongs to a virtual network in a different RG). 

It should print out the names of resources as they are cleaned up, and, when it fails, what resources were not successfully deleted.

**Comment by ravbhatnagar** [comment]
Laveesh is currently working on this for both remove and move.

**Comment by ravbhatnagar** [comment]
@TianoMS - Please check with Laveesh on this one. He will have pointers for you.

**Comment by TianoMS** [comment]
Had a conversation with Laveesh, this requires server side change. I'll look into that.

**Comment by markcowl** [comment]
@TianoMS If this is resolved, please close ths issue.  Otherwise, please assign to the appropriate milestone

**Comment by markcowl** [comment]
This functioinality is not provided service side, closing as won't fix.
