### ISSUE TITLE
Missing command to publish custom metric to Azure Monitor service

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#11680]
I can't seem to find a PowerShell command to publish a custom metric to the Microsoft Azure Monitor service. Is there a command to do this in the Azure PowerShell module? If not, why is it missing and when can it be added?

The documentation doesn't mention any PowerShell commands.

https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-store-custom-rest-api

```
PS >Connect-AzAccount
Get-Command -Module Az.Monitor -Name *metric*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Add-AzMetricAlertRule                              1.7.0      Az.Monitor
Cmdlet          Add-AzMetricAlertRuleV2                            1.7.0      Az.Monitor
Cmdlet          Get-AzMetric                                       1.7.0      Az.Monitor
Cmdlet          Get-AzMetricAlertRuleV2                            1.7.0      Az.Monitor
Cmdlet          Get-AzMetricDefinition                             1.7.0      Az.Monitor
Cmdlet          New-AzMetricAlertRuleV2Criteria                    1.7.0      Az.Monitor
Cmdlet          New-AzMetricAlertRuleV2DimensionSelection          1.7.0      Az.Monitor
Cmdlet          New-AzMetricFilter                                 1.7.0      Az.Monitor
Cmdlet          New-AzScheduledQueryRuleLogMetricTrigger           1.7.0      Az.Monitor
Cmdlet          Remove-AzMetricAlertRuleV2                         1.7.0      Az.Monitor
```

Cheers,
Trevor Sullivan

**Comment by dingmeng-xue** [comment]
@VeryEarly , could you check if there is cmdlet supporting it.

**Comment by VeryEarly** [comment]
Data-plane SDK is needed to support this feature in azure-powershell.

@vgorbenko @anirudhcavale Can you help evaluate?

**Comment by navba-MSFT** [comment]
@pcgeek86 Apologies for the late reply. Thanks for reaching out to us. I am doing some research on this issue. In the meantime, I wanted to check if you have tried invoking [this](https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-store-custom-rest-api) REST API from the powershell and checked if that helps.
Awaiting your reply.
