### ISSUE TITLE
Add-AzApplicationGatewayRequestRoutingRule throws "Set-AzApplicationGateway : Cannot parse the request."

### ISSUE THREAD

**Issue by sedeuce-dawg** [Azure/azure-powershell#11696]
**Cmdlet(s)**
$applicationgateway = Get-AzApplicationGateway -Name "apgw"

$frontendipconfig   = Get-AzApplicationGatewayFrontendIPConfig -ApplicationGateway $applicationgateway -Name "appGwPublicFrontendIp"

$frontendport80     = Get-AzApplicationGatewayFrontendPort -ApplicationGateway $applicationgateway -Name "port_80"

$frontendport443    = Get-AzApplicationGatewayFrontendPort -ApplicationGateway $applicationgateway -Name "port_443"

#Creates Http Listener
$sslcertificate = Get-AzApplicationGatewaySslCertificate -ApplicationGateway $applicationgateway -name "cert"
    
Add-AzApplicationGatewayHttpListener -ApplicationGateway $applicationgateway -Name "listener-80" -Protocol "Http" -FrontendPortID $frontendport80.id -FrontendIPConfigurationId $frontendipconfig.id -HostName "domain.com"

Add-AzApplicationGatewayHttpListener -ApplicationGateway $applicationgateway -Name "listener-443" -Protocol "Https" -FrontendPortID $frontendport443.id -FrontendIPConfigurationId $frontendipconfig.id -SslCertificateId $sslcertificate.id -HostName "domain.com"

#Creates Health Probe
Add-AzApplicationGatewayProbeConfig -ApplicationGateway $applicationgateway -Name "healthprobe-80" -Protocol Http -HostName "domain.com" -Path "/" -Interval 20 -Timeout 20 -UnhealthyThreshold 3
    
#Creates Http Setting
$probe = Get-AzApplicationGatewayProbeConfig -ApplicationGateway $applicationgateway -Name "healthprobe-80"
    
Add-AzApplicationGatewayBackendHttpSettings -ApplicationGateway $applicationgateway -Name "httpsetting-80" -Port 80 -Protocol "HTTP" -CookieBasedAffinity "Disabled" -RequestTimeout 20 -HostName $url -ProbeId $probe.id
    
#Create Rules
$httpsetting    = Get-AzApplicationGatewayBackendHttpSetting -ApplicationGateway $applicationgateway -Name "httpsetting-80"

$httplistener   = Get-AzApplicationGatewayHttpListener -ApplicationGateway $applicationgateway -Name "listener-80"

$httpslistener  = Get-AzApplicationGatewayHttpListener -ApplicationGateway $applicationgateway -Name "listener-443"

$backendpool    = Get-AzApplicationGatewayBackendAddressPool -ApplicationGateway $applicationgateway -Name "backendpool"

$redirectconfig = Set-AzApplicationGatewayRedirectConfiguration -ApplicationGateway $applicationgateway -Name "routingrule-80" -RedirectType Permanent -TargetListenerID  $httpslistener.ID -IncludePath $true -IncludeQueryString $true
    
Add-AzApplicationGatewayRequestRoutingRule -ApplicationGateway $applicationgateway -Name "routingrule-80" -RuleType basic -BackendHttpSettingsId $httpsetting.id -HttpListenerId $httplistener.id -RedirectConfigurationID $redirectconfig.id

Add-AzApplicationGatewayRequestRoutingRule -ApplicationGateway $applicationgateway -Name "routingrule-443" -RuleType basic -BackendHttpSettingsId $httpsetting.id -HttpListenerID $httpslistener.id -BackendAddressPoolID $backendpool.id

#Applies the changes to the Application Gateway
Set-AzApplicationGateway -ApplicationGateway $applicationgateway

**PowerShell Version**
5.1.18362.752

**Module Version**
OS Version
10.0.18363.0

**Description**
I am trying to add new Request routing rule to the already existing Azure Application Gateway. After successfully running all cmdlet", the application gateway needs to be updated by running the cmdlet "Set-AzureRmApplicationGateway". It is here where the cmdlet throws "Set-AzApplicationGateway : Cannot parse the request.". 

If I remove the Add-AzApplicationGatewayRequestRoutingRule  -Name "routingrule-80" or change the _-RedirectConfigurationID $redirectconfig.id_ to _-BackendAddressPoolID $backendpool.id_, all the cmdlets execute and are created. There seems to be an error with referencing the Redirection.  

**Debug Output**
Set-AzApplicationGateway : Cannot parse the request.
+ Set-AzApplicationGateway -ApplicationGateway $applicationgateway
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzApplicationGateway], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.SetAzureApplicationGatewayCommand

**Script/Steps for Reproduction**

**Comment by dingmeng-xue** [comment]
Involve Network team to look into this issue.

**Comment by kjk129** [comment]
Can anyone give a current status of this bug?

**Comment by surajmb** [comment]
_Add-AzApplicationGatewayRequestRoutingRule -ApplicationGateway $applicationgateway -Name "routingrule-80" -RuleType basic -BackendHttpSettingsId $httpsetting.id -HttpListenerId $httplistener.id -RedirectConfigurationID $redirectconfig.id_

@sedeuce-dawg , I see that you have added both "Backend HTTP Settings" and "Redirection Configuration" in the rule configuration. There can only be two types of routing rules or path rules

1. With HTTP Settings and Backend Pool
2. With Redirection configuration

You can't have both the parameters. Hence, the error, can you try removing the HTTP settings and keeping only the redirection configuration and execute them again? Let me know if it works, we might have to work on a proper error message.

**Comment by lilyjma** [comment]
Hi, this issue seems to be resolved now, so I'm closing it. If you still have questions, please reopen. Thanks!
