### ISSUE TITLE
Get-AzRecoveryServicesBackupRecoveryPoint Not working for old points

### ISSUE THREAD

**Issue by DanteNahuel** [Azure/azure-powershell#11693]
## Description

Im trying to get very old Recovery Points using powershell and a Start Date of 1 year or more but the result is empty.
The recovery points are there and I can check them by the Portal.

## Steps to reproduce

```powershell

$threashold = get-date
$years = $threashold.AddYears(-1)
$backupitem = Get-AzRecoveryServicesBackupItem -Container $container  -WorkloadType "AzureVM" -VaultId $VaultID
Get-AzRecoveryServicesBackupRecoveryPoint -Item $backupitem -VaultId $VaultID -StartDate $years.ToUniversalTime()

```

**Comment by dingmeng-xue** [comment]
@DanteNahuel, thanks for your reporting.
Could you share debug output after you set `$DebugPreference="Continue"`?

**Comment by DanteNahuel** [comment]
@dingmeng-xue Hi
I didn't share it because this happens in many different environments, no matter if I run it from my Laptop, a workstation or the Cloud shell

**Comment by dingmeng-xue** [comment]
Hi DanteNahuel, "result is empty" is a little general. Debug message will show many information including request from client and response from server. It is helpful for service team to narrow down the root cause.

**Comment by pvrk** [comment]
@DanteNahuel : As mentioned above, need the debug trace to do accurate troubleshooting. If you have the trace @sambitratha  can look into this.

**Comment by pvrk** [comment]
@DanteNahuel : Please share the debug trace. Otherwise, I can't keep the bug open without any debug information. Thanks for your understanding

**Comment by pvrk** [comment]
@DanteNahuel: If you are not comfortable sharing the debug trace in this channel, please open a support case and then share. We will resolve this issue if it reappears.

Closing the case since the required information to debug is not present.
