### ISSUE TITLE
Enable New-AzStorageContext to leverage Managed Identity

### ISSUE THREAD

**Issue by husamhilal** [Azure/azure-powershell#11702]
## Description of the new feature
Currently, there is no existing way to use PowerShell to leverage a User Assigned Managed Identity linked to a VM in Azure.

## Proposed implementation details (optional)
Add a new parameter like this **New-AzStorageContext -UseManagedIdentity** which in background will perform a token request to Managed Identity endpoint from Azure VM: http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01

**Comment by blueww** [comment]
@husamhilal 

From storage side, we are not clear about what do you mean by "User Assigned Managed Identity", and can't open http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01. 

But `New-AzStorageContext` do support oauth. You can use following command to create a storage context with oauth credential, after login with `Connect-AzAccount`
```powershell
$ctx = New-AzStorageContext -StorageAccountName $accountName
```

**Comment by blueww** [comment]
@husamhilal

Does the storage context with oauth credential work for you?
Do you still have any issue need assistance from us?

**Comment by husamhilal** [comment]
Hello @blueww, thanks for the information. 
I'm talking about Azure Managed Identities to allow the VM in Azure to retrieve blobs from Azure Storage account. Similar to this tutorial, (the goal to make this tutorial possible with PowerShell):
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-vm-windows-access-storage 
This is why I think we should have something similar to this: **New-AzStorageContext -UseManagedIdentity**

**Comment by husamhilal** [comment]
> @husamhilal
> 
> From storage side, we are not clear about what do you mean by "User Assigned Managed Identity", and can't open http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01.
> 
> But `New-AzStorageContext` do support oauth. You can use following command to create a storage context with oauth credential, after login with `Connect-AzAccount`
> 
> ```powershell
> $ctx = New-AzStorageContext -StorageAccountName $accountName
> ```
The link "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01" should be only accessible from a VM in Azure. Take a look at this example: 
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-windows-vm-access-nonaad#access-data

**Comment by blueww** [comment]
@markcowl, @erich-wang 
Can powershell Connect-AzAccount login with the User Assigned Managed Identity (credential of an Azure VM)?
If so, Storage can also login with it.

**Comment by husamhilal** [comment]
@blueww Great point!
I was able to create the context, but for some reason the RBAC doesn't seem to be working properly, I've assigned the Managed Identity different permissions on the storage account "Storage Blob Data Contributor", "Storage Blob Data Reader", and "Owner"

However, I receive this error when accessing a blob or trying to list blobs.
This request is not authorized to perform this operation using this permission. HTTP Status Code:
403 - HTTP Error Message: This request is not authorized to perform this operation using this permission.
ErrorCode: AuthorizationPermissionMismatch
ErrorMessage: This request is not authorized to perform this operation using this permission.
 


--

**Comment by husamhilal** [comment]
@blueww 
Quick update, when providing **AccountId** parameter to Connect-AzAccount things work fine (as expected), without it, I get the Error I stated in the previous context:
```
Connect-AzAccount -Identity **-AccountId** xxxxyyyy-tttt-ttttt-yyyy-yyyyxxxxzzzz
$ctx = New-AzStorageContext -StorageAccountName "accountname"
```

**Comment by blueww** [comment]
@husamhilal 
Thanks for the update! 

@markcowl, @erich-wang
Would you please see the Connect-AzAccount cmdlet issue?

**Comment by markcowl** [comment]
@husamhilal That is a logical request, unfortunately, the MSI service doesn't provide any way to get the token for a user-assigned managed identity without knowing the client id or object id or resource id of the identity.  If you use a System-Assigned identity, then you don't need to provide the account id.

**Comment by husamhilal** [comment]
Thanks a lot @markcowl. I deeply appreciate your response and explanation. System assigned MI are great but not scalable. For example, when you want to create KeyVault access policy, you can create one policy for one identity when using user assigned MI, vs you'll need to create N policies to N system assigned MI. Using the Client ID is not a big problem it's just storing something inside the VM, where if there is no need for it, you'd store nothing on the VM.

**Comment by markcowl** [comment]
@husamhilal Agreed on the scalability issue - user assigned msi essentially lets you set up a credential for each unique role for your automation, while system-assigned MSI requires setting the correct roles each time you create a resource for automation. For now, storing the correct identity in settings / environment variables is likely the closes thing now to having a 'default' user-assigned MSI.

**Comment by husamhilal** [comment]
Thanks a lot @markcowl for your helpful response and good information 👍

@blueww 
It sounds New-AzStorageContext -StorageAccountName "xyz" **-UseConnectedAccount does not create good context for any of Azure File Shares cmdlets** like (Get-AzStorageFileContent), when using other method for creating the context, things work as expected. I'm I missing anything, please?

**Comment by blueww** [comment]
@husamhilal

As we discussed online, Azure File Storage still not support Oauth credential. So it not support Storage context  with oauth credential (created by -UseConnectedAccount)

**Comment by husamhilal** [comment]
Thanks a lot @blueww @markcowl @dingmeng-xue for all the help you provided :)
I'm closing this issue right now, as it's concern was addressed! Thank you very much!

**Comment by karimdabbagh** [comment]
> @blueww Quick update, when providing **AccountId** parameter to Connect-AzAccount things work fine (as expected), without it I get the Error I stated in the previous comment:
> 
> ```
> Connect-AzAccount -Identity -AccountId xxxxyyyy-tttt-ttttt-yyyy-yyyyxxxxzzzz
> $ctx = New-AzStorageContext -StorageAccountName "accountname"
> ```
> 
> I'm wondering why Connect-AzAccount -Identity won't do the job?!
> 
> I have only one **user-assigned managed identity**. I understand when having multiple user-assigned managed identity then there is a need to specify the AccountId to avoid defaulting to first one.

I know im a little late to the party but i was wondering what is the value for AccountId?
My scenario is that im running my Powershell in k8s pod with a user assinged identity. So, im running into the same issue as the storage giving me 403. So, i thought passing AccountId should be the solution to me as well but not sure which value should use.

**Comment by blueww** [comment]
@karimdabbagh 

You can find more description for AccountId in https://learn.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-9.3.0#-accountid.

@dingmeng-xue , could you please give more hint how to run cmdlet Connect-AzAccount with  a user assinged identity?
