### ISSUE TITLE
Add-AzureRmAutoscaleSetting cmdlet fails with TargetResourceNotFound error

### ISSUE THREAD

**Issue by sriram-d** [Azure/azure-powershell#11710]
When attempting to add new autoscale setting for classic cloud service (Microsoft.ClassicCompute/domainNames), Add-AzureRmAutoscaleSetting cmdlet fails with TargetResourceNotFound error. The resourceId passed in for -TargetResourceId argument was obtained from Get-AzureRmResource cmdlet, so the resource does exist.

Same error is seen with AzureRM module version 6.13.1 and 6.2.0

Response headers for failing attempt:
x-ms-request-id               : 00000000-0000-0000-0000-000000000000
x-ms-correlation-request-id   : 80fa87d3-abce-44b2-9660-5adbe842450f
x-ms-routing-request-id       : CANADAEAST:20200426T125355Z:80fa87d3-abce-44b2-9660-5adbe842450f
Date                          : Sun, 26 Apr 2020 12:53:54 GMT

**Comment by dingmeng-xue** [comment]
@sriram-d , could you share the debug error after set `$DebugPreference = "Continue"`?

**Comment by sriram-d** [comment]
@dingmeng-xue, please find below
DEBUG: 08:43:29 - AddAzureRmAutoscaleSettingCommand begin processing with ParameterSet 'CreateAutoscaleSetting'.
DEBUG: 08:43:29 - using account id 'xxxx@yyyy.com'...
WARNING: 08:43:29 - *** The namespace for all the model classes will change from
Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.
WARNING: 08:43:29 - *** The namespace for output classes will be uniform for all classes in future releases to make it
independent of modifications in the model classes.
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxxx@yyyy.com', environment: 'AzureCloud',
tenant: '{tenantId}'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/27/2020 03:13:29: a13890b4-193a-4dc6-b683-90e632dc36b2 - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/{tenantId}/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (2 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/27/2020 03:13:29:  - TokenCache: Deserialized 2 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 04/27/2020 03:13:29: a13890b4-193a-4dc6-b683-90e632dc36b2 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/27/2020 03:13:29: a13890b4-193a-4dc6-b683-90e632dc36b2 - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 04/27/2020 03:13:29: a13890b4-193a-4dc6-b683-90e632dc36b2 - TokenCache: 56.2268825816667 minutes left until
token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/27/2020 03:13:29: a13890b4-193a-4dc6-b683-90e632dc36b2 - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/27/2020 03:13:29: a13890b4-193a-4dc6-b683-90e632dc36b2 - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: DgNWwsK2bnshOPEcbiH4aNzYSeznBySh49m/0s7/Qyw=
 Refresh Token Hash: G2uF55GYgQZHt2dH7LT2IkO0Ptj5KRhb+aeIiwReAWU=
 Expiration Time: 04/27/2020 04:09:43 +00:00
 User Hash: {scrubbed}

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/27/2020 03:13:29: 8c1bb0b4-6e64-422f-ade1-17785b2cfb36 - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/{tenantId}/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (2 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/27/2020 03:13:29:  - TokenCache: Deserialized 2 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 04/27/2020 03:13:29: 8c1bb0b4-6e64-422f-ade1-17785b2cfb36 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/27/2020 03:13:29: 8c1bb0b4-6e64-422f-ade1-17785b2cfb36 - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 04/27/2020 03:13:29: 8c1bb0b4-6e64-422f-ade1-17785b2cfb36 - TokenCache: 56.22529952 minutes left until token in
cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/27/2020 03:13:29: 8c1bb0b4-6e64-422f-ade1-17785b2cfb36 - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/27/2020 03:13:29: 8c1bb0b4-6e64-422f-ade1-17785b2cfb36 - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: DgNWwsK2bnshOPEcbiH4aNzYSeznBySh49m/0s7/Qyw=
 Refresh Token Hash: G2uF55GYgQZHt2dH7LT2IkO0Ptj5KRhb+aeIiwReAWU=
 Expiration Time: 04/27/2020 04:09:43 +00:00
 User Hash: {scrubbed}

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/agsperfproxy/providers/m
icrosoft.insights/autoscalesettings/agsperfproxy?api-version=2015-04-01

Headers:
x-ms-client-request-id        : f2beeacd-ca92-4eb2-a346-fb0573b050f9
accept-language               : en-US

Body:
{
  "properties": {
    "profiles": [
      {
        "name": "agsperfproxy",
        "capacity": {
          "minimum": "1",
          "maximum": "2",
          "default": "2"
        },
        "rules": [
          {
            "metricTrigger": {
              "metricName": "Percentage CPU",
              "metricResourceUri":
"/subscriptions/{subscriptionId}/resourceGroups/agsperfproxy/providers/Microsoft.ClassicCompute/dom
ainNames/agsperfproxy",
              "timeGrain": "PT1M",
              "statistic": "Average",
              "timeWindow": "PT10M",
              "timeAggregation": "Average",
              "operator": "GreaterThanOrEqual",
              "threshold": 80.0
            },
            "scaleAction": {
              "direction": "Increase",
              "type": "PercentChangeCount",
              "value": "40",
              "cooldown": "PT10M"
            }
          },
          {
            "metricTrigger": {
              "metricName": "Percentage CPU",
              "metricResourceUri":
"/subscriptions/{subscriptionId}/resourceGroups/agsperfproxy/providers/Microsoft.ClassicCompute/dom
ainNames/agsperfproxy",
              "timeGrain": "PT1M",
              "statistic": "Average",
              "timeWindow": "PT5M",
              "timeAggregation": "Average",
              "operator": "GreaterThanOrEqual",
              "threshold": 50.0
            },
            "scaleAction": {
              "direction": "Increase",
              "type": "PercentChangeCount",
              "value": "10",
              "cooldown": "PT10M"
            }
          },
          {
            "metricTrigger": {
              "metricName": "Percentage CPU",
              "metricResourceUri":
"/subscriptions/{subscriptionId}/resourceGroups/agsperfproxy/providers/Microsoft.ClassicCompute/dom
ainNames/agsperfproxy",
              "timeGrain": "PT1M",
              "statistic": "Average",
              "timeWindow": "PT30M",
              "timeAggregation": "Average",
              "operator": "LessThanOrEqual",
              "threshold": 40.0
            },
            "scaleAction": {
              "direction": "Decrease",
              "type": "PercentChangeCount",
              "value": "10",
              "cooldown": "PT10M"
            }
          }
        ]
      }
    ],
    "enabled": true,
    "targetResourceUri":
"/subscriptions/{subscriptionId}/resourceGroups/agsperfproxy/providers/Microsoft.ClassicCompute/dom
ainNames/agsperfproxy/slots/Production/roles/AgsPerfProxy"
  },
  "location": "southcentralus",
  "tags": {}
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 00000000-0000-0000-0000-000000000000
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 5812e37a-074a-4b8c-b4de-f779a811f93f
x-ms-routing-request-id       : CANADAEAST:20200427T031338Z:5812e37a-074a-4b8c-b4de-f779a811f93f
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Mon, 27 Apr 2020 03:13:38 GMT
Server                        : Microsoft-IIS/10.0

Body:
{
  "code": "TargetResourceNotFound",
  "message": "The target resource id
'/subscriptions/{subscriptionId}/resourceGroups/agsperfproxy/providers/Microsoft.ClassicCompute/dom
ainNames/agsperfproxy' was not found."
}

Add-AzureRmAutoscaleSetting : Exception type: ErrorResponseException, Message: The target resource id '/subscriptions/8
89879ef-3cc2-4acf-ad0e-dbc8887c83e0/resourceGroups/agsperfproxy/providers/Microsoft.ClassicCompute/domainNames/agsperfp
roxy' was not found., Code: TargetResourceNotFound, Status code:NotFound, Reason phrase: Not Found
+ ...   $result = Add-AzureRmAutoscaleSetting -Location $csresource.Locatio ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmAutoscaleSetting], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Autoscale.AddAzureRmAutoscaleSettingCommand

DEBUG: AzureQoSEvent: CommandName - Add-AzureRmAutoscaleSetting; IsSuccess - False; Duration - 00:00:06.3148929;
Exception - System.Management.Automation.PSInvalidOperationException: Exception type: ErrorResponseException, Message:
The target resource id
'/subscriptions/{subscriptionId}/resourceGroups/agsperfproxy/providers/Microsoft.ClassicCompute/dom
ainNames/agsperfproxy' was not found., Code: TargetResourceNotFound, Status code:NotFound, Reason phrase: Not Found
---> Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code
'NotFound'
   at
Microsoft.Azure.Management.Monitor.AutoscaleSettingsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 08:43:37 - AddAzureRmAutoscaleSettingCommand end processing.
DEBUG: 08:43:37 - AddAzureRmAutoscaleSettingCommand end processing.

**Comment by dingmeng-xue** [comment]
@sriram-d , please try `Add-AzAutoscaleSetting`. Before it, please try to get resource id via `Get-AzResource`

**Comment by sriram-d** [comment]
@dingmeng-xue, it is still failing
>>$csresource = Get-AzResource -Name foocloudservice -ResourceType Microsoft.ClassicCompute/domainNames
>>Get-AzResource -ResourceId $csresource.ResourceId


Name              : foocloudservice
ResourceGroupName : foocloudservice
ResourceType      : Microsoft.ClassicCompute/domainNames
Location          : southcentralus
ResourceId        : /subscriptions/{scrubbed}/resourceGroups/foocloudservice/providers/Microsoft
                    .ClassicCompute/domainNames/foocloudservice
Tags              :

>>$resourceId = $csresource.ResourceId + "/slots/Production/roles/foocloudservice"
>>Add-AzAutoscaleSetting -Location $csresource.Location -Name $csresource.Name -ResourceGroup $csresource.ResourceGroupName -TargetResourceId $resourceId -AutoscaleProfile $profile
Add-AzAutoscaleSetting : Exception type: ErrorResponseException, Message: The property 'resourceId' has an invalid
value., Code: InvalidArgument, Status code:BadRequest, Reason phrase: Bad Request
At line:1 char:1
+ Add-AzAutoscaleSetting -Location $csresource.Location -Name $csresour ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzAutoscaleSetting], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Autoscale.AddAzureRmAutoscaleSettingCommand

**Comment by sriram-d** [comment]
@dingmeng-xue , below is relevant Debug information

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/{scrubbed}/resourcegroups/{scrubbed}/providers/m
icrosoft.insights/autoscalesettings/{scrubbed}?api-version=2015-04-01

Headers:
x-ms-client-request-id        : 7767900a-e76c-42f1-ba6d-077bd80b52ed
accept-language               : en-US

Body:
{
  "properties": {
    "profiles": [
      {
        "name": "{scrubbed}",
        "capacity": {
          "minimum": "1",
          "maximum": "2",
          "default": "2"
        },
        "rules": [
          {
            "metricTrigger": {
              "metricName": "Percentage CPU",
              "metricResourceUri":
"/subscriptions/{scrubbed}/resourceGroups/{scrubbed}/providers/Microsoft.ClassicCompute/dom
ainNames/{scrubbed}",
              "timeGrain": "PT1M",
              "statistic": "Average",
              "timeWindow": "PT10M",
              "timeAggregation": "Average",
              "operator": "GreaterThanOrEqual",
              "threshold": 80.0
            },
            "scaleAction": {
              "direction": "Increase",
              "type": "PercentChangeCount",
              "value": "40",
              "cooldown": "PT10M"
            }
          },
          {
            "metricTrigger": {
              "metricName": "Percentage CPU",
              "metricResourceUri":
"/subscriptions/{scrubbed}/resourceGroups/{scrubbed}/providers/Microsoft.ClassicCompute/dom
ainNames/{scrubbed}",
              "timeGrain": "PT1M",
              "statistic": "Average",
              "timeWindow": "PT5M",
              "timeAggregation": "Average",
              "operator": "GreaterThanOrEqual",
              "threshold": 50.0
            },
            "scaleAction": {
              "direction": "Increase",
              "type": "PercentChangeCount",
              "value": "10",
              "cooldown": "PT10M"
            }
          },
          {
            "metricTrigger": {
              "metricName": "Percentage CPU",
              "metricResourceUri":
"/subscriptions/{scrubbed}/resourceGroups/{scrubbed}/providers/Microsoft.ClassicCompute/dom
ainNames/{scrubbed}",
              "timeGrain": "PT1M",
              "statistic": "Average",
              "timeWindow": "PT30M",
              "timeAggregation": "Average",
              "operator": "LessThanOrEqual",
              "threshold": 40.0
            },
            "scaleAction": {
              "direction": "Decrease",
              "type": "PercentChangeCount",
              "value": "10",
              "cooldown": "PT10M"
            }
          }
        ]
      }
    ],
    "enabled": true,
    "targetResourceUri":
"/subscriptions/{scrubbed}/resourceGroups/{scrubbed}/providers/Microsoft.ClassicCompute/dom
ainNames/{scrubbed}/slots/Production/roles/{scrubbed}"
  },
  "location": "southcentralus",
  "tags": {}
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 00000000-0000-0000-0000-000000000000
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 9af61117-727d-4fe6-aba6-2f1407d20a20
x-ms-routing-request-id       : CANADAEAST:20200428T182203Z:9af61117-727d-4fe6-aba6-2f1407d20a20
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 28 Apr 2020 18:22:03 GMT
Server                        : Microsoft-IIS/10.0

Body:
{
  "code": "InvalidArgument",
  "message": "The property 'resourceId' has an invalid value."
}

**Comment by sriram-d** [comment]
The issue was with metricResouceUri, rather than targetResourceUri. The former needs to qualify the role within the cloudservice.
