### ISSUE TITLE
AzureStack-Storage Module - Any commands in the storage module prompts for user inputs

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#11714]
## Description

Executing any commands in the storage admin module prompts for user inputs. This is an issue as the module has reverted to use an older version of PsSwaggerUtilty.  This was an user error while generating the module. The error happens when we install it afresh, storage admin module verification missed this obvious error may be due to the presence of existing module

PS C:\> Get-AzsStorageQuota
WARNING: Preview version of the module Azs.Storage.Admin loaded. Future release of this module may have breaking
changes.

PSSwagger needs to download the NuGet package 'Microsoft.Rest.ClientRuntime.Azure' of version '3.3.4' to compile the
generated assembly for .NET.
PSSwagger needs to download the NuGet package 'Microsoft.Rest.ClientRuntime' of version '2.3.4' to compile the
generated assembly for .NET.
PSSwagger needs to download the NuGet package 'Newtonsoft.Json' of version '6.0.8' to compile the generated assembly
for .NET.
Do you want PSSwagger to download the missing tools or packages for you?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):

PS C:\> Get-AzsStorageQuota
WARNING: Preview version of the module Azs.Storage.Admin loaded. Future release of this module may have breaking
changes.

PSSwagger needs to download the NuGet package 'Microsoft.Rest.ClientRuntime.Azure' of version '3.3.4' to compile the
generated assembly for .NET.
PSSwagger needs to download the NuGet package 'Microsoft.Rest.ClientRuntime' of version '2.3.4' to compile the
generated assembly for .NET.
PSSwagger needs to download the NuGet package 'Newtonsoft.Json' of version '6.0.8' to compile the generated assembly
for .NET.
Do you want PSSwagger to download the missing tools or packages for you?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):

## Steps to reproduce

```powershell
Get-AzsStorageQuota
```

## Module versions
AzureStack - 1.8.1
Azs.Storage.Admin - 0.3.0

**Comment by dingmeng-xue** [comment]
@bganapa , is it autorest related issue?

**Comment by bganapa** [comment]
No it is not. This is with our AzureRM compatible modules. We used to generate them with another tool called PsSwagger and its an issue with that. I have schedule d a meeting today to discuss this issue

**Comment by bganapa** [comment]
We are in the process moving the module from AzureRm branch to Azurestack powershell repo

**Comment by bganapa** [comment]
AzureStack module 1.8.2 is out
