### ISSUE TITLE
Remove SkuSize in MySQL

### ISSUE THREAD

**Issue by msJinLei** [Azure/azure-powershell#11725]
## Description
We set the size of sku and then try to get the value. We find the field is not retrieved, but it is listed in the related swagger spec, postgresql.json/mysql.json/mariadb.json and so autorest.powershell generate it as an output field as well as an input parameter.

We need confirmation from service team whether to remove it in the azure powershell.
Refer to https://github.com/Azure/azure-rest-api-specs/issues/9237 for more details

**Comment by dingmeng-xue** [comment]
Swagger issue and wait service team's update.

**Comment by msJinLei** [comment]
>@msJinLei Thanks for your feedback. The size property under sku is one that is no longer used. During the public preview of Azure Postgres, this property was used to pick a storage size. Since GA, storageMB in StorageProfile is used instead for that purpose.
>The size property under sku is there in the spec for that historical reason.

According to swagger team's feedback, the field is no longer used.  "storageMB" acts as a replacement functionally. 

We should remove it from input and output format table.
