### ISSUE TITLE
Request- Ability to resize OS disk size using ARM commandlet

### ISSUE THREAD

**Issue by gcondric** [Azure/azure-powershell#1172]
It seems that there is no possibility to resize OS disk size using ARM PS "Set-AzureVMOSDisk"

In V1 version, this is possible using PowerShell command “Set-AzureOSDisk”   with parameter [–ResizedSizeInGB]

Can you add this to V2 commandlet version - Set-AzureVMOSDisk or somewhere else?

thanks!

**Comment by singhkay** [comment]
@gcondric We don't have a cmdlet for this but this is supported for both os and data disks. Here's how you can do it

```
$vm.StorageProfile.OsDisk.DiskSizeGB = 150
$vm.StorageProfile.DataDisks[0].DiskSizeGB = 10

Update-AzureRmVM -VM $vm -ResourceGroupName kayrg3
```
