### ISSUE TITLE
New-AzADServicePrincipal - Insufficient privileges to complete the operation

### ISSUE THREAD

**Issue by tnsholding** [Azure/azure-powershell#11735]
## Description

Trying to use cmdlet New-AzADServicePrincipal from Azure DevOps Pipeline - with  AzurePowerShell@4 task. 
Getting error "Insufficient privileges to complete the operation." unless granting Azure service connection principal the role "Global administrator", which seems a bit excessive. 

According to https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-3.8.0 under feedback issues -> "Please clarify which permissions are needed", it is stated that "Application Administrator" and "User Access Administrator" roles should be enough, but that doesn't seem to apply for version 4.0.2-preview.

## Steps to reproduce

Running the following command in AzurePowerShell@4 task in DevOps pipeline - following a successful creation of application with New-AzADApplication cmdlet: 

```powershell
New-AzADServicePrincipal -TenantId $tenantId -AppId $myApp.AppId -AppRoleAssignmentRequired -Tag @("WindowsAzureActiveDirectoryIntegratedApp")
```

**Comment by dingmeng-xue** [comment]
@tnsholding , could you show us debug message of `New-AzADServicePrincipal` after executing `$DebugPreference="Continue"`?

**Comment by tnsholding** [comment]
It seems that the service principal was missing permissions for API access:
Microsoft Graph: Application.ReadWrite.OwnedBy and Windows Azure Active Directory: Application.ReadWrite.OwnedBy

After this only "Application Developer" role is needed.

**Comment by dingmeng-xue** [comment]
@tnsholding, thanks for information. Since permission is not clear described on API, Azure PowerShell as client only can rely on server to check it. Please contact us if you meet any further issue.
Close current issue now.
