### ISSUE TITLE
Get-AZResource no more works for Azure Machine Learning

### ISSUE THREAD

**Issue by ramakrpr** [Azure/azure-powershell#11746]
## Description
 Get-AzResource -Name <<MLInstanceName>> -ResourceGroupName <<Resourcegroupname>> -ResourceType "Microsoft.MachineLearningServices/workspaces"

This command all of a sudden has started throwing exception as below

Get-AzResource : api-version query parameter has an incorrect value.

Same is applicable to Remove-AZResource

This was working fine till last Friday, not sure what happened suddenly. Reported to MS via incident as well, confirmed that indeed there is an issue
Works well for other resource, breaks only for Machine Learning

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
I reported the issue to machine learning service team. Please wait their feedback.

**Comment by rastala** [comment]
The Get-AzResource issue appears to have been resolved. Please try with the latest Azure PowerShell, and let us know if you run into the issue again.
