### ISSUE TITLE
getting blank page when trying to enter password to login to azure account. I have installed latest Az module in powershell and trying to connect using "login-azaccount" command. This pops up a window to enter email address. Once email is entered it should ask for password but im getting blank page instead. Please help!

### ISSUE THREAD

**Issue by shama-git** [Azure/azure-powershell#11751]
## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by shama-git** [comment]
![Capture](https://user-images.githubusercontent.com/60743784/80608017-d6453580-8a53-11ea-8a0e-415b3e5d9c6c.JPG)

**Comment by abatishchev** [comment]
All fields in the issue template is there on purpose.

**Comment by dingmeng-xue** [comment]
@abatishchev , could you share information about yours OS, and version of PowerShell, and version of Az modules?
```
$PSVersionTable
Get-Module -Name Az* -ListAvailable
```

**Comment by abatishchev** [comment]
I'm not the author of the issue. @shama-git is.

**Comment by shama-git** [comment]
> Get-Module -Name Az* -ListAvailable

![1](https://user-images.githubusercontent.com/60743784/80681247-e86bb600-8add-11ea-84b4-f5d83c503b75.JPG)
![2](https://user-images.githubusercontent.com/60743784/80681260-edc90080-8add-11ea-85c5-bf3f69862ac9.JPG)
![3](https://user-images.githubusercontent.com/60743784/80681270-f3bee180-8add-11ea-9a2b-4bdd019f1c02.JPG)

**Comment by shama-git** [comment]
> @abatishchev , could you share information about yours OS, and version of PowerShell, and version of Az modules?
> 
> ```
> $PSVersionTable
> Get-Module -Name Az* -ListAvailable
> ```

Hi , Im using 32 bit windows 7 OS.

**Comment by shama-git** [comment]
The issue has been resolved by upgrading the internet explorer in my local system.
