### ISSUE TITLE
Get-AzNetworkServiceTag does not return all servicetags

### ISSUE THREAD

**Issue by stephenwheet** [Azure/azure-powershell#11775]
## Description
When using Get-AzNetworkServiceTag it does grab all TAG types.  It's missing "WindowsVirtualDesktop" for one.  I don't know how many others

## Steps to reproduce
PS /home/stephen/clouddrive> $ServiceTags = get-aznetworkservicetag -Location westus2
PS /home/stephen/clouddrive> $AzureCloudIP = ($serviceTags.Values | Where-Object { $_.Name -like "AzureCloud.westus2" }).Properties.AddressPrefixes
PS /home/stephen/clouddrive> ($serviceTags.Values | Where-Object { $_.Name -like "AzureCloud.westus2" }).Properties.AddressPrefixes
13.66.128.0/17
13.77.128.0/18
13.104.145.0/26
13.104.208.192/26
13.104.213.0/25
20.36.0.0/19
20.38.99.0/24
20.42.128.0/18
20.187.0.0/18
20.190.0.0/18
20.190.133.0/24
20.190.154.0/24
20.191.64.0/18
23.98.47.0/24
23.102.192.0/21
23.102.203.0/24
23.103.64.32/27
23.103.64.64/27
23.103.66.0/23
40.65.64.0/18
40.77.136.0/28
40.77.136.64/28
40.77.160.0/27
40.77.164.0/24
40.77.166.144/32
40.77.169.0/24
40.77.171.0/24
40.77.175.64/27
40.77.180.0/23
40.77.182.64/27
40.77.185.128/25
40.77.186.0/26
40.77.186.128/25
40.77.187.0/24
40.77.198.128/25
40.77.199.128/26
40.77.200.0/25
40.77.224.96/27
40.77.230.0/24
40.77.232.128/25
40.77.234.224/27
40.77.236.64/29
40.77.236.128/27
40.77.240.128/25
40.77.241.0/24
40.77.242.0/23
40.77.244.0/24
40.77.247.0/24
40.77.249.0/24
40.77.250.0/24
40.77.254.128/25
40.78.208.32/30
40.78.217.0/24
40.78.240.0/20
40.80.160.0/24
40.82.36.0/22
40.87.232.0/21
40.90.16.192/26
40.90.131.32/27
40.90.132.48/28
40.90.136.224/27
40.90.138.208/28
40.90.139.32/27
40.90.146.32/27
40.90.148.192/27
40.90.153.0/26
40.90.192.0/19
40.91.0.0/22
40.91.64.0/18
40.125.64.0/18
40.126.5.0/24
40.126.26.0/25
40.126.26.128/26
51.141.160.0/19
51.143.0.0/17
52.96.11.0/24
52.108.72.0/24
52.109.24.0/22
52.111.246.0/24
52.112.105.0/24
52.112.109.0/24
52.114.148.0/22
52.115.55.0/24
52.136.0.0/22
52.137.64.0/18
52.143.64.0/18
52.143.197.0/24
52.143.211.0/24
52.148.128.0/18
52.149.0.0/18
52.151.0.0/18
52.156.64.0/18
52.156.128.0/19
52.158.224.0/19
52.175.192.0/18
52.183.0.0/17
52.191.128.0/18
52.229.0.0/18
52.232.152.0/24
52.233.64.0/18
52.235.64.0/18
52.239.148.128/25
52.239.176.128/25
52.239.193.0/24
52.239.210.0/23
52.239.236.0/23
52.245.52.0/22
52.246.192.0/18
52.247.192.0/18
52.250.0.0/17
65.52.111.0/24
65.54.247.128/25
65.55.2.0/24
65.55.32.128/28
65.55.32.192/27
65.55.32.224/28
65.55.33.176/28
65.55.33.192/28
65.55.35.192/27
65.55.44.8/29
65.55.44.112/28
65.55.51.0/24
65.55.60.128/27
65.55.105.128/26
65.55.106.192/28
65.55.106.240/28
65.55.107.0/27
65.55.107.32/28
65.55.107.96/27
65.55.107.128/25
65.55.110.0/24
65.55.120.0/24
65.55.189.128/25
65.55.207.0/24
65.55.209.0/25
65.55.210.0/24
65.55.211.64/26
65.55.212.32/27
65.55.213.32/27
65.55.213.192/26
65.55.215.0/24
65.55.219.64/26
65.55.250.0/24
65.55.252.0/24
70.37.0.0/21
70.37.8.0/22
70.37.16.0/20
70.37.32.0/20
104.44.89.128/27
104.44.89.192/27
104.44.95.0/28
131.253.12.8/29
131.253.12.36/30
131.253.12.56/29
131.253.12.64/29
131.253.12.160/28
131.253.12.228/30
131.253.13.24/29
131.253.13.88/30
131.253.13.112/28
131.253.13.128/25
131.253.14.4/30
131.253.14.8/31
131.253.14.72/29
131.253.14.80/28
131.253.14.96/27
131.253.14.128/27
131.253.14.192/29
131.253.15.128/28
131.253.15.192/28
131.253.24.16/28
131.253.24.32/27
131.253.24.64/26
131.253.26.0/25
131.253.34.128/26
131.253.35.0/25
131.253.35.128/26
131.253.38.64/27
131.253.38.96/29
131.253.40.48/29
131.253.40.128/27
131.253.41.0/24
134.170.222.0/23
137.116.176.0/21
157.55.2.128/26
157.55.12.64/26
157.55.13.64/26
157.55.39.0/24
157.55.55.128/29
157.55.55.184/29
157.55.55.228/30
157.55.55.232/29
157.55.55.240/28
157.55.106.0/26
157.55.154.128/25
157.56.1.0/24
157.56.2.0/25
157.56.3.128/25
157.56.19.224/27
157.56.21.160/27
157.56.21.192/27
157.56.80.0/25
168.62.64.0/19
191.232.137.0/24
191.237.224.0/21
191.237.244.0/22
191.239.196.0/24
191.239.197.0/28
199.30.24.0/23
199.30.27.0/25
199.30.27.144/28
199.30.27.160/27
199.30.27.192/26
199.30.31.0/24
207.46.13.0/24
207.68.174.0/29
207.68.174.56/29
207.68.174.64/29
207.68.174.96/28
207.68.174.168/29
207.68.174.176/29
207.68.174.192/28
209.240.212.0/23
PS /home/stephen/clouddrive> ($serviceTags.Values | Where-Object { $_.Name -like "WindowsVirtualDesktop.westus2" }).Properties.AddressPrefixes
PS /home/stephen/clouddrive>

## Environment data

PS /home/stephen/clouddrive> Get-Module  -ListAvailable

    Directory: /usr/local/share/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     3.8.0                 Az                                  Core,Desk
Script     1.7.5                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.1.1                 Az.Advisor                          Core,Desk {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Disable-AzAdvisorRecommendation, Get-AzAdvisorConfiguration…}
Script     1.0.3                 Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential…}
Script     1.1.2                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAnalysisServicesServer…}
Script     1.4.1                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagementRegion, Add-AzApiManagementUserToGroup…}
Script     1.0.3                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Set-AzApplicationInsightsPricingPlan…}
Script     1.3.6                 Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDscNodeConfiguration…}
Script     2.0.2                 Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, New-AzBatchAccount…}
Script     1.0.2                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget…}
Script     1.4.3                 Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile…}
Script     1.3.0                 Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSku, Get-AzCognitiveServicesAccountType…}
Script     3.7.0                 Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet…}
Script     1.0.3                 Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}
Script     1.1.1                 Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegistry…}
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeDevice, Invoke-AzDataBoxEdgeDevice, New-AzDataBoxEdgeDevice…}
Script     1.7.0                 Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2…}
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalyticsCatalogCredential, Set-AzDataLakeAnalyticsCat…
Script     1.2.8                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreFirewallRule, Set-AzDataLakeStoreTrustedIdProvi…
Script     1.1.0                 Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifactSource, Set-AzDeploymentManagerArtifactSource, Remove-AzDeploymentManagerArtif…
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy…}
Script     1.1.2                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet…}
Script     1.2.3                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey…}
Script     1.4.3                 Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace…}
Script     1.4.0                 Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoor…}
Script     0.10.7                Az.GuestConfiguration               Core,Desk {Get-AzVMGuestPolicyStatus, Get-AzVMGuestPolicyStatusHistory}
Script     3.1.0                 Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMapReduceJobDefinition…}
Script     1.0.1                 Az.HealthcareApis                   Core,Desk {New-AzHealthcareApisService, Remove-AzHealthcareApisService, Set-AzHealthcareApisService, Get-AzHealthcareApisService}
Script     2.4.0                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob…}
Script     1.6.0                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultCertificateOperation…}
Script     1.3.2                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConfiguration, Get-AzIntegrationAccountCallbackUrl…
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Remove-AzMlCommitmentPlan…}
Script     1.0.0                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzMaintenanceConfiguration, Get-AzMaintenanceUpdate…}
Script     1.0.2                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, New-AzManagedServicesAssignment, Remove-AzManagedServicesAssignment, Get-AzManagedServicesDefinition…}
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.1                 Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaServiceKey, Get-AzMediaServiceNameAvailability…}
Script     1.7.0                 Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile…}
Script     2.5.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplicationGatewayAuthenticationCertific…
Script     1.1.1                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-AzNotificationHubListKey, Get-AzNotificationHubPNSCredential…}
Script     1.3.4                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Disable-AzOperationalInsightsLinuxCustomLogCollec…
Script     1.3.0                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation…}
Script     1.1.1                 Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessKey, Get-AzPowerBIWorkspace…}
Script     1.0.2                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, Remove-AzPrivateDnsZone, Set-AzPrivateDnsZone, New-AzPrivateDnsZone…}
Script     2.8.0                 Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecoveryServicesVault…}
Script     1.2.1                 Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-AzRedisCachePatchSchedule…}
Script     1.0.3                 Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace…}
Script     1.13.0                Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment…}
Script     1.4.1                 Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNamespace…}
Script     2.0.2                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, Add-AzServiceFabricNode, Add-AzServiceFabricNodeType…}
Script     1.1.1                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey…}
Script     2.6.0                 Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransparentDataEncryption, Get-AzSq…
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk {New-AzSqlVM, Get-AzSqlVM, Update-AzSqlVM, Remove-AzSqlVM…}
Script     1.14.0                Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey…}
Script     1.2.3                 Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncService, Get-AzStorageSyncService, Remove-AzStorageSyncService…}
Script     1.0.1                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFunction, Remove-AzStreamAnalyticsFunction…}
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, Get-AzSupportProblemClassification, Get-AzSupportTicket, Get-AzSupportTicketCommunication…}
Script     1.0.3                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Remove-AzTra…
Script     1.8.0                 Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan…}
Script     0.0.0.10              AzureAD.Standard.Preview            Desk      {New-AzureADServicePrincipal, Get-AzureADMSDeletedGroup, Get-AzureADServicePrincipalKeyCredential, Add-AzureADDeviceRegisteredUser…}
Script     0.9.3                 AzurePSDrive                        Desk
Script     17.0.2985…            EXOPSSessionConnector               Desk      Connect-EXOPSSession
Binary     0.1.1                 Microsoft.PowerShell.UnixCompleters Core      {Import-UnixCompleters, Remove-UnixCompleters, Set-UnixCompleter}
Manifest   1.0.840               MicrosoftPowerBIMgmt                Desk
Binary     1.0.840               MicrosoftPowerBIMgmt.Admin          Desk      {Add-PowerBIEncryptionKey, Get-PowerBIEncryptionKey, Get-PowerBIWorkspaceEncryptionStatus, Switch-PowerBIEncryptionKey…}
Binary     1.0.840               MicrosoftPowerBIMgmt.Capacities     Desk      Get-PowerBICapacity
Binary     1.0.840               MicrosoftPowerBIMgmt.Data           Desk      {Add-PowerBIDataset, Set-PowerBITable, New-PowerBIDataset, New-PowerBITable…}
Binary     1.0.840               MicrosoftPowerBIMgmt.Profile        Desk      {Connect-PowerBIServiceAccount, Disconnect-PowerBIServiceAccount, Invoke-PowerBIRestMethod, Get-PowerBIAccessToken…}
Binary     1.0.840               MicrosoftPowerBIMgmt.Reports        Desk      {Get-PowerBIReport, New-PowerBIReport, Export-PowerBIReport, Get-PowerBIDashboard…}
Binary     1.0.840               MicrosoftPowerBIMgmt.Workspaces     Desk      {Get-PowerBIWorkspace, Get-PowerBIWorkspaceMigrationStatus, Add-PowerBIWorkspaceUser, Remove-PowerBIWorkspaceUser…}
Binary     1.0.6                 MicrosoftTeams                      Desk      {Get-CsBatchPolicyAssignmentOperation, New-CsBatchPolicyAssignmentOperation}
Script     0.9.3                 PSCloudShellUtility                 Desk      {Enter-AzVM, Get-AzCommand, Invoke-AzVMCommand, Enable-AzVMPSRemoting…}
Binary     0.8.1                 SHiPS                               Desk
Script     21.1.18221            SqlServer                           Desk      {Add-RoleMember, Add-SqlAvailabilityDatabase, Add-SqlAvailabilityGroupListenerStaticIp, Add-SqlAzureAuthenticationContext…}

    Directory: /opt/microsoft/powershell/7/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.2.5                 Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   7.0.0.0               Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   7.0.0.0               Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty, Join-Path…}
Manifest   7.0.0.0               Microsoft.PowerShell.Security       Core      {Get-Credential, Get-ExecutionPolicy, Set-ExecutionPolicy, ConvertFrom-SecureString…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alias, Import-Alias, New-Alias…}
Script     1.4.6                 PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource…}
Script     2.2.3                 PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability…}
Script     2.0.5                 PSDesiredStateConfiguration         Core      {Configuration, New-DscChecksum, Get-DscResource, Invoke-DscResource}
Script     2.0.0                 PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineKeyHandler, Get-PSReadLineOption…}
Binary     2.0.3                 ThreadJob                           Desk      Start-ThreadJob

## Debug output

```

```

## Error output

```

```

**Comment by danielbrookes** [comment]
I have the same issue. If it helps you can download the JSON file from here which does include the WindowsVirtualDesktop tag.

**Comment by dingmeng-xue** [comment]
Thanks for the feedback. I will involve Network team to look into it.

**Comment by allegradomel** [comment]
@stephenwheet - thanks for bringing this to our attention - I'm forwarding this to engineering to take a look....

**Comment by allegradomel** [comment]
Update: It looks like the data behind the API has not been updated in some time. We will make sure the data updates regularly when this is released for GA. 

Thanks for catching this - I hope you can make use of the JSON file for the most up to date data until we move forward with our GA changes.

**Comment by stephenwheet** [comment]
What part is still in preview?  The api doesn’t look like it’s in preview and I was running this from the azure console which isn’t running a preview version of powershell.
