### ISSUE TITLE
Update-AzureVM PropertyChangeNotAllowed

### ISSUE THREAD

**Issue by Kreby** [Azure/azure-powershell#1177]
I have a number of scripts that I currently use with AzureResourceManager.  I have started having issues running Update-AzureVM cmdlet.  I'm currently using version 0.9.8.1.  The most common use case I've had issues with is adding additional disks to an existing VM.  I had been using these scripts for a couple of months without issue.  I'm not making any changes to the AdditionalUnattendContent  but it seems to be an issue with passing the VM object this way now. 

Previously working code example. 

    $storageAccount = Get-AzureStorageAccount -Name "$($storageAccountName)" -ResourceGroupName "$($resourceGroupName)"

    $DiskUri = $storageAccount.PrimaryEndpoints.Blob.ToString() + "vhds/" + $DiskBlobName
    $vm = Get-AzureVM -Name "$($vmName)" -ResourceGroupName "$($resourceGroupName)"
    $vm = Add-AzureVMDataDisk -vm $vm -Name "$($DiskBlobNameNoExt)" -DiskSizeInGB "$($DiskSizeInGB)" -Lun $DiskLun -VhdUri "$($DiskUri)" -CreateOption "Empty" -Caching "ReadOnly"

    Update-AzureVM -ResourceGroupName $resourceGroupName -vm $vm

    Update-AzureVM : PropertyChangeNotAllowed: Changing property  'windowsConfiguration.additionalUnattendContent' is not allowed.

Here is an example of the OSProfile from a VM that is having this issue. 

    OSProfile                : {
                             "AdminPassword": null,
                             "AdminUsername": "***********",
                             "ComputerName": "************",
                             "CustomData": null,
                             "LinuxConfiguration": null,
                             "Secrets": [],
                             "WindowsConfiguration": {
                               "AdditionalUnattendContents": [],
                               "EnableAutomaticUpdates": true,
                               "ProvisionVMAgent": true,
                               "TimeZone": null,
                               "WinRMConfiguration": null
                             }

I've been able to work around the issue by piping all of the commands together but would like to not have to do that. 

Thanks.

**Comment by avanyork** [comment]
Kreby, 

If you null out the the AdditionalUnattendContents json array Update-AzureVM may work.

**Comment by singhkay** [comment]
There was a platform update that fixed this. @hyonholee Can you check if Update-AzureRmVM now works with an empty array of AdditionalUnattendContents?

**Comment by singhkay** [comment]
This is now fixed, closing.

**Comment by avanyork** [comment]
Thank you!
