### ISSUE TITLE
Az module Install fails from Powershell Gallery Save or Install

### ISSUE THREAD

**Issue by montereyharris** [Azure/azure-powershell#11772]
PackageManagement\Save-Package : Unable to save the module 'Az'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1561 char:21
+             $null = PackageManagement\Save-Package @PSBoundParameters
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...ets.SavePackage:SavePackage) [Save-Package], Except
   ion
    + FullyQualifiedErrorId : ProviderFailToDownloadFile,Microsoft.PowerShell.PackageManagement.Cmdlets.SavePackage

Verision - Powershell 5.1 
Module Az

**Comment by montereyharris** [comment]
Failure with PowershellGet 2.2.4 as well
PackageManagement\Install-Package : Cannot convert value "2.0.1-preview" to type "System.Version". Error: "Input
string was not in a correct format."
At C:\Program Files\WindowsPowerShell\Modules\powershellget\2.2.4.1\PSModule.psm1:9807 char:50
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], E
   xception
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation,New-PSGetItemInfo,Microsoft.PowerShell.PackageManagemen
   t.Cmdlets.InstallPackage

**Comment by montereyharris** [comment]
Also doesn't work after updating to PackageManagement

**Comment by dingmeng-xue** [comment]
@montereyharris, could you share what script is when you are install az module?

**Comment by montereyharris** [comment]
Find-module Az|Install-Module -force

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dingmeng-xue** [comment]
Hi @montereyharris, I tried your script and works. Could you try 2 steps separately? Check the ouput of `Find-module Az`. And then check `Install-Module -Name Az`. In addition, please restart Windows PowerShell before trying those steps.

**Comment by J1BLB** [comment]
I also have this error - a clean PowerShell and wanting to install the -az module.  First had to install NuGet provider version '2.8.5.201' , 
`PS C:\windows\system32> Find-module Az

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
3.8.0      Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage r...


PS C:\windows\system32> Install-Module -Name Az

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
PackageManagement\Install-Package : Cannot convert value "2.0.1-preview" to type "System.Version". Error: "Input
string was not in a correct format."
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], E
   xception
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation,New-PSGetItemInfo,Microsoft.PowerShell.PackageManagemen
   t.Cmdlets.InstallPackage`

**Comment by montereyharris** [comment]
What’s your build of powershell?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dingmeng-xue** [comment]
@J1BLB, you need to upgrade PowerShellGet. The version of 1.0.0.1 is a very old version and cannot work PSGallery correctly according to my experience.

**Comment by J1BLB** [comment]
Thanks, that has worked.
Step 1: Update NuGet
" Install-PackageProvider -Name NuGet -Force
>> Exit"
Step 2: Update PowerShellGet
"Install-Module -Name PowerShellGet -Force"
Then install AZ module.

PowerShell build 5.1.16299
