### ISSUE TITLE
New-AzureRmResource -ParentResource not working as documented

### ISSUE THREAD

**Issue by MarkMurphyInvu** [Azure/azure-powershell#1178]
I created an Azure web site using New-AzureRmResource in PowerShell ISE, v5 b10514, Azure PowerShell 1.0 Preview and then tried to create AppSettings for it in the same script but get the error:

New-AzureRmResource : A parameter cannot be found that matches parameter name 'ParentResource'.
 .....
 +     -ParentResource $parent `
 +     ~~~~~~~~~~~~~~~
     + CategoryInfo          : InvalidArgument: (:) [New-AzureRmResource], ParameterBindingException
     + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceCmdlet 
I seem to be following the advice about -ParentResource in "get-help New-AzureRmResource -detailed" exactly. What am I doing wrong? 

Extract from script :
 ... 
   $WebSite = @{}

  New-AzureRmResource `
     -ApiVersion "2015-08-01" `
     -Location $location `
     -Name $siteName `
     -ResourceGroupName $siteName `
     -ResourceType "Microsoft.Web/sites" `
     -PropertyObject $WebSite

   $parent = "Microsoft.Web/sites/$($siteName)"
    
    $AppSettings = @{WEBSITE_NODE_DEFAULT_VERSION = "0.10.32"}

   New-AzureRmResource `
     -ApiVersion "2015-08-01" `
     -Location $location `
     -Name 'appsettings' `
     -ResourceGroupName $siteName `
     -ResourceType "Microsoft.Web/sites/config" `
     -ParentResource $parent `
     -PropertyObject $AppSettings
 ....

BUT ... 

 You can make it work by including the parent's name in the Name parameter as shown below. Get-Help does not mention this and its advice on ParentResource is wrong for this case.

   New-AzureRmResource `
     -ApiVersion "2015-08-01" `
     -Location $location `
     -Name "$($siteName)/appsettings" `
     -ResourceGroupName $siteName `
     -ResourceType "Microsoft.Web/sites/config" `
     -PropertyObject $AppSettings

**Comment by ravbhatnagar** [comment]
Parent is no more a supported param on the New-AzureRmResource. The help was probably not updated in the preview release. Your solution above is correct on how you achieve it.
