### ISSUE TITLE
[Az.Accounts] Get-AzSubscription Lighthouse inclusion of origin TenantId

### ISSUE THREAD

**Issue by Get-Ryan** [Azure/azure-powershell#11783]
## Description of the new feature
The current functionality of Get-AzSubscription when used in a Lighthouse scenario seems to result in all PSAzureSubscription objects being returned with an associated TenantID where the account being used to retrieve the info is receiving its permission to access that info.

While this is useful, some very useful information that is missing is the TenantID that a particular subscription belongs to vs the one that is being used to provide permissions to access it.

To illustrate:
- UserAccount A exists in Tenant A
- Lighthouse is deployed to delegate permissions to UserAccount A to manage subscription B in Tenant B
- When UserAccount A uses Connect-AzAccount to connect to Tenant A, and then calls Get-AzSubscription, the results will include a PSAzureSubscription object for subscription B, but the only TenantID reference in that object will refer to Tenant A; as that's where the permissions come from for UserAccount A to retrieve the info. However, it is very useful and relevant to be able to programmatically associate subscription B to its tenant of origin, Tenant B. Currently, that does not seem possible.

This functionality does seem quite possible though, as warning messages are fairly common:
- Unable to acquire token for tenant 'tenantID'

This seems to indicate that origin tenants are queried to obtain the list of subscriptions accessible. I wouldn't think it a far stretch to then associate those tenant IDs with the returned PSAzureSubscription objects.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. This is a feature and Azure PowerShell needs to upgrade API version to fetch projected subscription. We are working on it.

**Comment by markcowl** [comment]
This work is being tracked in this issue: #9838 closing this as a duplicate.
