### ISSUE TITLE
Remove-AzPrivateDnsRecordSet outputs unformatted verbose string

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-powershell#11798]
## Description

Calling `Remove-AzPrivateDnsRecordSet` with `-Verbose` outputs the format string, not a formatted string.

## Steps to reproduce

```powershell
Remove-AzPrivateDnsRecordSet -ResourceGroupName $resourceGroup `
                             -ZoneName $zoneName `
                             -Name $recordName `
                             -RecordType A `
                             -Verbose
```

## Actual outcome

>VERBOSE: Performing the operation "Removing record set ..." on target "contoso".
VERBOSE: Success!
VERBOSE: Record set '{0}' was removed from Private DNS zone '{1}'.

## Expected outcome

>VERBOSE: Performing the operation "Removing record set ..." on target "contoso".
VERBOSE: Success!
VERBOSE: Record set 'contoso' was removed from Private DNS zone 'example.local'.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.
```

## Module versions

```powershell
Script     1.0.2                 Az.PrivateDns
```

**Comment by dingmeng-xue** [comment]
Thanks for your reporting. 

The issue is around below code. PrivateDns team, please resolve it.
https://github.com/Azure/azure-powershell/blob/2b5dc2c493333db129b352340a16ba9e9b54d6e4/src/PrivateDns/PrivateDns/Records/RemoveAzurePrivateDnsRecordSet.cs#L140

**Comment by abatishchev** [comment]
@dingmeng-xue please assign the issue to the right person. Right now the issue arrears to unnoticed.

**Comment by dingmeng-xue** [comment]
Sure. I will ping them again. Service team normally check issue according to label regulatory.

**Comment by hakahlon-msft** [comment]
Fixed as part of https://github.com/Azure/azure-powershell/pull/11917
