### ISSUE TITLE
New-AzureRmResource Search sku parameter

### ISSUE THREAD

**Issue by MarkMurphyInvu** [Azure/azure-powershell#1179]
When creating Search Services I discovered some undocumented features ....
1. the -sku parameter works but using the $Search["Sku"] alone only raises a "sku parameter missing" error (see code below). The -sku parameter is undocumented and inconsistent with the general rule that properties are supplied in a hashtable via PropertyObject 
2. -Location 'West Europe' works but the -Location 'westeurope', that works for other resources, does not work on Search
   
   $sku = @{ name = $searchServiceSku }
   
   $Search = @{ }
    $Search["Sku"] = $sku
    $Search["ReplicaCount"] = $replicaCount
    $Search["PartitionCount"] = $partitionCount
   
    New-AzureRmResource `
    -ApiVersion "2015-08-19"`
    -Location 'West Europe' `
    -Name $searchServiceName`
    -sku $sku `
    -ResourceGroupName $siteName`
    -ResourceType "Microsoft.Search/searchServices" `
    -PropertyObject $Search

**Comment by ravbhatnagar** [comment]
Looks like RP related issues. I will route this to the appropriate team.

**Comment by ravbhatnagar** [comment]
Removing ResourceManager label. Seems like RP issue. @markcowl - please assign to MIcrosoft.Search RP

**Comment by markcowl** [comment]
@ravbhatnager PowerShell repo  isn't the right place to track service issues.  Can you create an issue for this in the appropriate tarckign system?

**Comment by ravbhatnagar** [comment]
@MarkMurphyInvu - This should be fixed now. Please let us know if you see otherwise. For#1, Sku should be outside of properties bag.
