### ISSUE TITLE
Documentation on how to use the Azure Key Vault extension for PowerShell Secrets Management

### ISSUE THREAD

**Issue by janegilring** [Azure/azure-powershell#11794]
## Description of the new feature

In the latest release of the Az.KeyVault module the following was added:
•	_Added support to Microsoft.PowerShell.SecretManagement ([link](https://github.com/Azure/azure-powershell/issues/11178))_

However, there are no documentation available on how to use this extension.

My initial experimenting:

Install-Module Microsoft.PowerShell.SecretManagement -AllowPrerelease

Install-Module -Name Az

Connect-AzAccount

Then, the Register-SecretVault can be used to register Az.KeyVault, which now has an extension for the Secret Management Module:

Register-SecretVault -Name MyVault -ModuleName Az.KeyVault

PS C:\> Get-SecretVault

Name              ModuleName  ImplementingType
----              ----------  ----------------
BuiltInLocalVault
MyVault    Az.KeyVault

However, even if I`m connected to Azure (Get-AzContext shows the correct subscription where MyVault is located), I get the following when trying to retrieve a secret:

PS C:\> Get-Secret -Vault MyVault -Name demo
Exception: To use  Azure vault, the current user must be logged into Azure account subscription . Run 'Connect-AzAccount -SubscriptionId '.
Get-Secret: The secretdemo was not found.

**Comment by dingmeng-xue** [comment]
@janegilring , You need provide some parameters when register it. there is a test case for your reference
https://github.com/Azure/azure-powershell/blob/master/src/KeyVault/KeyVault.Test/ScenarioTests/SecretManagementExtensionTests.ps1

**Comment by janegilring** [comment]
Thanks, adding the additional vault parameters did the trick.

However, what kind of parameters which is expected inside of the -VaultParameters hash table is not very obvious. Are there any reason not to expose the parameters as regular cmdlet parameters?

For example:
Register-SecretVault -Name AzKeyVault -ModuleName Az.KeyVault -AZKVaultName 'xdmkv' -AZKSubscriptionId  '<sub>' 

Or maybe adding such dynamic parameters to the Secrets Management module might be difficult from an extension side of view?

As long as some documentation is provided (Get-Help about_AzureKeyVaultSecretsManagementExtension and an article on docs.microsoft.com), it would be easier.

**Comment by dingmeng-xue** [comment]
Thanks. I guess secret management extension has not idea how many attributes need to be supported because it wants to support many type of secret vault. So there is no syntax to describe it. We are considering to add an article to describe this feature.

**Comment by janegilring** [comment]
Sounds great, thanks!

**Comment by JustinGrote** [comment]
@dingmeng-xue  I know this is closed but is there a referenced article anywhere? I had to go to the tests as well to find the supported vaultparameters and I couldn't find an article anywhere via google in msdocs
