### ISSUE TITLE
Update Set-AzApplicationInsightsPricingPlan.md to include details about Application Insights Enterprise

### ISSUE THREAD

**Issue by debugthings** [Azure/azure-powershell#11795]
## Description of the new feature
The Set-AzApplicationInsightsPricingPlan.md lists out all of the possible pricing plans for Application Insights including two older plans which are no longer offered to new resources. There are still customers who can switch to this plan as they are grandfathered

Please include a note that links to our billing document about the [Legacy Enterrpise](https://docs.microsoft.com/en-us/azure/azure-monitor/app/pricing#legacy-enterprise-per-node-pricing-tier) pricing tier and that this no longer applies for any resources created after April 2018.

## Proposed implementation details (optional)

Additionally the cmdlet can check the `PricingPlans` API to see what tiers are allowed by the resource. You could add it to the if statement [here](https://github.com/Azure/azure-powershell/blob/9fa15f7b7abf09df94a65a54cc34baef3084f536/src/ApplicationInsights/ApplicationInsights/ApplicationInsights/SetApplicationInsightsPricingPlan.cs#L108) and also add a link to the billing document above.

**Comment by VeryEarly** [comment]
Hi @debugthings 

Thanks for the information, will take care.

**Comment by VeryEarly** [comment]
fixed in pr: #13628

**Comment by VeryEarly** [comment]
close as fixed
