### ISSUE TITLE
Call new credential api for Import-AzAksCredential

### ISSUE THREAD

**Issue by djj0809** [Azure/azure-powershell#11812]
## Description of the new feature
Similar change with azure cli: https://github.com/Azure/azure-cli/pull/7002/files

Currently the ImportAzureRmAksCredential command uses old GetAccessProfile api of AKS, which is not accessible if you are cluster user role.

**Comment by dingmeng-xue** [comment]
@eriwan, please evaluate this feature.

**Comment by dingmeng-xue** [comment]
@djj0809, `Import-AzAksCredential` is the new version of AzureRM cmdlet. Could you try the latest version Az.AKS 1.1.0-preview? 
```
Install-Module -Name Az.Aks -RequiredVersion 1.1.0-preview -AllowPrerelease	
```
