### ISSUE TITLE
Get-AzConsumptionBudget does not support management group level budgets

### ISSUE THREAD

**Issue by SamirFarhat** [Azure/azure-powershell#11816]
## Description of the new feature
The powershell command Get-AzConsumptionBudget does not support management group level budgets. 
You should add support for management groups
## Proposed implementation details (optional)
Get-AzConsumptionBudget -scope {scope}
where scope can be Subscription, ManagementGroup or ResourceGroup
a Recursive switch will be good so that we cave all child budgets

**Comment by dingmeng-xue** [comment]
Service team, please evaluate this feature request.

**Comment by ms-premp** [comment]
Not in this version. We will have an update late this year, which will include this feature.

**Comment by ramaganesan-rg** [comment]
Closing the issue as per Prem's comments.
