### ISSUE TITLE
Update-AzVmss : The Image type for a Virtual Machine Scale Set may not be changed

### ISSUE THREAD

**Issue by ankitkotnala** [Azure/azure-powershell#11817]
**When I run command** :

 _Get-AzVmss -ResourceGroupName 'abc-rg' -Name testvmss | Update-AzVmss -ImageReferenceId '/Subscriptions/28e1f188-21a7-4ab2-8d0c-a2c92ee73c0e/Providers/Microsoft.Compute/Locations/SouthIndia/Publishers/canonical/ArtifactTypes/VMImage/Offers/Ubuntu_Core'_ 

**I get below error:** 

![image](https://user-images.githubusercontent.com/31920677/81190097-000ed700-8fd5-11ea-8168-74cb415fae78.png)

**If I run a more detailed one :** 

Get-AzVmss -ResourceGroupName kotnalaweb-rg -Name testvmss | Update-AzVmss -ImageReferenceOffer Ubuntu_Core -ImageReferencePublisher Canonical -ImageReferenceSku 16 -ImageReferenceVersion latest -ImageReferenceId '/Subscriptions/28e1f188-21a7-4ab2-8d0c-a2c92ee73c0e/Providers/Microsoft.Compute/Locations/SouthIndia/Publishers/canonical/ArtifactTypes/VMImage/Offers/Ubuntu_Core' 

**I get :** 
![image](https://user-images.githubusercontent.com/31920677/81190221-2c2a5800-8fd5-11ea-81ab-1abc2833b929.png)

**Comment by ankitkotnala** [comment]
I think it cannot be done as I am modifying a create time property : Offer

https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-upgrade-scale-set#create-time-properties

Is there any alternative beside deleting Scale set and creating again ?

**Comment by dingmeng-xue** [comment]
Compute team, please look into this issue.

**Comment by Drewm3** [comment]
The error is correct here. At this time the offer type for an image cannot be modified. The only workaround is to create a new scale set. We are looking to support this functionality in the future, but we are not able to share a specific date when this feature will be available.
