### ISSUE TITLE
 Set-AzAutomationRunbookDefinition is not a valid cmdlet

### ISSUE THREAD

**Issue by AzureAzim** [Azure/azure-powershell#11822]
Tryign to research how to update a runbook without deleting and recreating in powershell, i came acros this script with the -overwrite parameter. This cmdlet is in this script, but its a cmdlet that does not exist:

https://github.com/Azure/azure-powershell/blob/master/src/Automation/Automation.Test/ScenarioTests/AutomationTests.ps1

**Comment by dingmeng-xue** [comment]
Those test cases were skipped more than one year. It seems old cmdlets are removed. I involve Automation team to double check it.

**Comment by vikram-m** [comment]
PG team is investigating on why the old cmdlets are removed. Will update with more details on the findings.

**Comment by jaspkaur28** [comment]
We got this triaged & we will update the published sample scripts & remove the cmdlet Set-AzAutomationRunbookDefinition. We have this added to our backlog , however , due to other priroties , we will defer this to CY2020 Q4. 
To update a runbook you can use Set-AzAutomationRunbook cmdlet or use the Invoke-RestMethod to send Runbook Draft - Replace content rest API call.

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.

**Comment by Jassingh819** [comment]
We can use the Import-AzAutomationRunbook with -force switch to overwrite the existing runbook definition. https://docs.microsoft.com/en-us/powershell/module/az.automation/import-azautomationrunbook?view=azps-8.1.0 https://github.com/elvg/azure-powershell/blob/20ef290c3d1a65f082cc817675d02758b64bc5a0/src/ServiceManagement/Automation/Commands.Automation/Cmdlet/SetAzureAutomationRunbookDefinition.cs
