### ISSUE TITLE
Update-AzVmss not applying NSG properly at VMSS' NIC level

### ISSUE THREAD

**Issue by EmilienCourt** [Azure/azure-powershell#11835]
## Description

Looking at VMSS's `VirtualMachineProfile.NetworkProfile.NetworkInterfaceConfigurations` in Powershell, it seems like you can apply NSGs directly at the scale set "interface"'s level (`VirtualMachineProfile.NetworkProfile.NetworkInterfaceConfigurations[0].NetworkSecurityGroup`), which will apply the NSG to the interface of the instances of the VMSS. 

However, the NSG is not applied properly. 

Indeed, after being applied, you can not remove the NSG from the VMSS using Azure Portal. 
Removing the NSG from the scale set parameters is not possible (there is no option at the scale set or instance level), and trying to dissociate it from the NSG's "Network interfaces" panel will give this error :

```
Failed to dissociate network interface
Failed to dissociate network interface 'myScaleSet'. Error: The operation 'write' on resource type 'virtualMachineScaleSets/virtualMachines/networkInterfaces' is disallowed.
```

Please note I am a global administrator on the tenant this has been tested on.

The only way to remove the NSG is by using Powershell again, replacing the NSG's Id in `VirtualMachineProfile.NetworkProfile.NetworkInterfaceConfigurations[0].NetworkSecurityGroup` by `$null`.

This issue is probably a mixed issue between the `Update-AzVmss` cmdlet and Azure Portal, as the possibility to apply NSGs at the interface level might not be an intended feature (so, a Powershell issue), but the error is when you try to remove the NSG from the interface (so, an Azure Portal issue).

It is also possible that this feature is intended (though not documented), but the permissions are not set properly.

The expected behaviour (for me), would be to uniformize what can be done in Powershell (applying the NSG at the VMSS level) and in Azure Portal.

## Steps to reproduce

```powershell
# Create VMSS
New-AzVmss -ResourceGroupName "myResourceGroupScaleSet" -Location "EastUS" -VMScaleSetName "myScaleSet" -VirtualNetworkName "myVnet" -SubnetName "mySubnet" -PublicIpAddressName "myPublicIPAddress" -LoadBalancerName "myLoadBalancer" -UpgradePolicyMode "Automatic"

# Create NSG
$rule1 = New-AzNetworkSecurityRuleConfig -Name InboundDisallow -Access Deny -DestinationAddressPrefix * -DestinationPortRange * -Direction Inbound -Priority 100 -Protocol * -SourceAddressPrefix * -SourcePortRange *
$rule2 = New-AzNetworkSecurityRuleConfig -Name OutboundDisallow -Access Deny -DestinationAddressPrefix * -DestinationPortRange * -Direction Outbound -Priority 100 -Protocol * -SourceAddressPrefix * -SourcePortRange *
$nsg = New-AzNetworkSecurityGroup -ResourceGroupName "myResourceGroupScaleSet" -Location "EastUS" -Name "myNsg" -SecurityRules $rule1,$rule2 -Force

# Apply NSG
$VMSSDetail = Get-AzVmss -ResourceGroupName "myResourceGroupScaleSet" -Name "myScaleSet"
$nics = $VMSSDetail.VirtualMachineProfile.NetworkProfile.NetworkInterfaceConfigurations
$nics[0].NetworkSecurityGroup = $nsg.Id
Update-AzVmss -ResourceGroupName "myResourceGroupScaleSet" -Name "myScaleSet" -VirtualMachineScaleSet $VMSSDetail
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.7.5      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}
Script     1.3.6      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDs...
Script     3.7.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}
Script     2.5.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplicationGatewayA...
Script     1.13.0     Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}
Script     1.14.0     Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}

```

## Debug & Error outputs
Debug and Error outputs are probably not relevant, as the visible part of this issue is in Azure portal. I can provide it if required though.

**Comment by dingmeng-xue** [comment]
Compute team, please look into this issue.

**Comment by Drewm3** [comment]
@avirishuv, could you look into this issue?

**Comment by EmilienCourt** [comment]
Hi @Drewm3 and @avirishuv 
Would you have any updates regarding this issue ?
Regards,

**Comment by avirishuv** [comment]
@EmilienCourt A couple of points below:

You can update/remove the NSG for a VMSS using Azure PowerShell. The steps you have outlined on this thread should work for this. However, note that after updating the NSG at VMSS NIC level, you also need to apply this latest VMSS model to each of the VMs in the VMSS. You can do this using both Azure PowerShell as well Azure Portal. This documentation provides more details on how to bring VMs up-to-date with the latest VMSS model: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-upgrade-scale-set#how-to-bring-vms-up-to-date-with-the-latest-scale-set-model 

Currently, removing NSG for a VMSS is unavailable in Azure Portal. We are looking into this and will provide an update here after investigation.

**Comment by EmilienCourt** [comment]
@avirishuv Alright, thanks for the point regarding `Update-AzVmssInstance`, didn't know it had to be done.

Looking forward to hearing from you regarding the portal issue

**Comment by avirishuv** [comment]
@EmilienCourt We have added to the feature backlog the capability to modify NSG for a VMSS via Portal. Here is the feature request added to User Voice as well, feel free to upvote or add comments if you like: https://feedback.azure.com/forums/223579-azure-portal/suggestions/41030980-ability-to-modify-nsg-for-virtual-machine-scale-se
