### ISSUE TITLE
New help.xml for ARM 1.0 Preview / Azure Data Lake Analytics Module - AzureRM.DataLakeAnalytics

### ISSUE THREAD

**Issue by TaraMeyer** [Azure/azure-powershell#1184]
Hi @Azure/adx-sdk-team -

A help.xml is now available for the new Azure Data Lake Analytics module for ARM 1.0 Preview(Microsoft.Azure.Commands.DataLakeAnalytics.dll).  This is a brand new module, so no existing help.xml to diff against.

Since I'm unable to attach xmls, you can find the update file here:

\\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\RMAzure_DataLkAnalyti\2015-10-27.15_42_48\OutPut\OnBox

![capture](https://cloud.githubusercontent.com/assets/14112499/10774897/95877624-7cc1-11e5-9766-44b23bcc3afa.PNG)

**Comment by devigned** [comment]
please attach as .txt

**Comment by TaraMeyer** [comment]
I'm not able to, I get this error:

![capture](https://cloud.githubusercontent.com/assets/14112499/10830041/c4f86f2e-7e3a-11e5-8180-9352b81938fc.PNG)

**Comment by TaraMeyer** [comment]
Didn't mean to close, sorry.
