### ISSUE TITLE
Build fails: Running msbuild build.proj yields a C:\o\corextpkgs\office\opt

### ISSUE THREAD

**Issue by whisper6284** [Azure/azure-powershell#11852]
## Description

I forked this repo, and followed the instructions here up to Building the Environment.

In the step when running msbuild build.proj, I receive a build error. 

## Steps to reproduce

1. I forked the repo Azure/azure-powershell.
2. I followed the instructions here up to Building the Environment.
3. At the step msbuild build.proj, I receive a 'File Not Found' error. Namely, C:\o\corextpkgs\office\opt.

## Environment data

```
C:\Program Files\dotnet\sdk\3.1.201\NuGet.targets(124,5): error : The local source 'C:\o\corextpkgs\office\opt' doesn't
 exist. [C:\Users\adtang\source\repos\azure-powershell\artifacts\Azure.PowerShell.sln] [C:\Users\adtang\source\repos\az
ure-powershell\build.proj]

  Build FAILED.

C:\Program Files\dotnet\sdk\3.1.201\NuGet.targets(124,5): error : The local source 'C:\o\corextpkgs\office\opt' doesn't
 exist. [C:\Users\adtang\source\repos\azure-powershell\artifacts\Azure.PowerShell.sln] [C:\Users\adtang\source\repos\az
ure-powershell\build.proj]
      0 Warning(s)
      1 Error(s)

  Time Elapsed 00:00:07.68
C:\Users\adtang\source\repos\azure-powershell\build.proj(173,5): error MSB3073: The command "dotnet build C:\Users\adta
ng\source\repos\azure-powershell\artifacts/Azure.PowerShell.sln -c Debug" exited with code 1.
Done Building Project "C:\Users\adtang\source\repos\azure-powershell\build.proj" (default targets) -- FAILED.


Build FAILED.

"C:\Users\adtang\source\repos\azure-powershell\build.proj" (default target) (1) ->
(Build target) ->
  C:\Program Files\dotnet\sdk\3.1.201\NuGet.targets(124,5): error : The local source 'C:\o\corextpkgs\office\opt' doesn
't exist. [C:\Users\adtang\source\repos\azure-powershell\artifacts\Azure.PowerShell.sln] [C:\Users\adtang\source\repos\
azure-powershell\build.proj]
  C:\Program Files\dotnet\sdk\3.1.201\NuGet.targets(124,5): error : The local source 'C:\o\corextpkgs\office\opt' doesn
't exist. [C:\Users\adtang\source\repos\azure-powershell\artifacts\Azure.PowerShell.sln] [C:\Users\adtang\source\repos\
azure-powershell\build.proj]
  C:\Users\adtang\source\repos\azure-powershell\build.proj(173,5): error MSB3073: The command "dotnet build C:\Users\ad
tang\source\repos\azure-powershell\artifacts/Azure.PowerShell.sln -c Debug" exited with code 1.

    0 Warning(s)
    3 Error(s)

Time Elapsed 00:01:43.22
```

**Comment by dingmeng-xue** [comment]
@whisper6284, could you please share the instruction?

**Comment by whisper6284** [comment]
1. Go to https://github.com/Azure/azure-powershell.
2. Click on Fork. (And I'm successful in forking the repo under my name whisper6284)
3. In a Windows Powershell under Admin mode, in the directory where I store my repos, I cloned the forked repo by running git clone https://github.com/whisper6284/azure-powershell.git
4. At the root of the repo, I ran msbuild build.proj.

This is where I get the error.

**Comment by dingmeng-xue** [comment]
@whisper6284 , please try PowerShell Core to do that. Our build scripts is only verified on PowerShell Core now.

**Comment by dingmeng-xue** [comment]
@whisper6284 , do you still hit the issue?

**Comment by whisper6284** [comment]
I still did. Ultimately I re-imaged my machine, and the problem is gone. I never found out what configuration attributed to the issue that I saw.

**Comment by dingmeng-xue** [comment]
Thanks for your confirmation. May I close this issue? You can contact us any time if you still meet the problem.

**Comment by dingmeng-xue** [comment]
Closing this issue now. Please create new issue if you meet any problem.

**Comment by whisper6284** [comment]
For completeness, I found out how to solve this issue.

1. Open Visual Studio.
2. Go to Tools -> Options
3. Select Nuget Package Manager -> Package Sources
4. Uncheck or remove any undesired package sources.
