### ISSUE TITLE
Get-AzStorageFileCopyState docs

### ISSUE THREAD

**Issue by paulomorgado** [Azure/azure-powershell#11851]
* ms.assetid: C1648DC3-8CFD-4487-A080-D9BE25DAD258
* Source: https://github.com/Azure/azure-powershell/blob/master/src/Storage/Storage.Management/help/Get-AzStorageFileCopyState.md
* Online: https://docs.microsoft.com/en-us/powershell/module/az.storage/get-azstoragefilecopystate

> ## INPUTS
> 
> ### Microsoft.Azure.Storage.File.CloudFile
> 
> ### Microsoft.Azure.Commands.Common.Authentication.Abstractions.IStorageContext
> 
> ## OUTPUTS
> 
> ### Microsoft.Azure.Storage.File.CloudFile

If the output is a `CloudFile`, how do I know the state of the file copy? Does it return null if the copy is not complete?

Isn't the list of inputs incompletes?

One para meter set takes a `CloudFile` and another takes a `PSShare` and a `string`.

**Comment by dingmeng-xue** [comment]
Storage team, could you answer the question?

**Comment by blueww** [comment]
For update the output type in help doc, I will update in the next or the one after next release.

For the following question, Would you please clarify what's the problem? 
Both parameter set will need parameter to point to the destination file. One use a CloudFile object , another one use Sharename + FilePath. I don't see a parameterset takes input as PSshare. 
> Isn't the list of inputs incompletes? 
> One para meter set takes a CloudFile and another takes a PSShare and a string.

**Comment by paulomorgado** [comment]
Sorry, my mistake. Or wistful thinking.

Tell me if I'm wrong, it either requires the `-File` parameter (for the **File** parameter set) or `-Context`, `-ShareName` and `FilePath` parameters (for the **ShareName** parameter set).

Then, the inputs are:

* File
  * CloudFile
* ShareName
  * IStorageContext
  * string
  * string

I don't think the inputs section is clear to the user. PowerShell doesn't make it easy to document it though.

**Comment by blueww** [comment]
@paulomorgado 
In https://docs.microsoft.com/en-us/powershell/module/az.storage/get-azstoragefilecopystate?view=azps-3.8.0
In Syntax section, you can see following. Not sure if anything not clear.
BTW, the help file is generally autogenerated from code, it must be aligned with code.
```powershell
Get-AzStorageFileCopyState
   [-ShareName] <String>
   [-FilePath] <String>
   [-WaitForComplete]
   [-Context <IStorageContext>]
   [-ServerTimeoutPerRequest <Int32>]
   [-ClientTimeoutPerRequest <Int32>]
   [-DefaultProfile <IAzureContextContainer>]
   [-ConcurrentTaskCount <Int32>]
   [<CommonParameters>]

Get-AzStorageFileCopyState
   [-File] <CloudFile>
   [-WaitForComplete]
   [-ServerTimeoutPerRequest <Int32>]
   [-ClientTimeoutPerRequest <Int32>]
   [-DefaultProfile <IAzureContextContainer>]
   [-ConcurrentTaskCount <Int32>]
   [<CommonParameters>]
```

**Comment by paulomorgado** [comment]
@blueww, maybe I don't understand the meaning of the **Inputs** and **Outputs** sections, but I'd say that that automatic generation is flawed.

And I still don't get, from the documentation:

> `PS C:\>Get-AzStorageFileCopyState -ShareName "ContosoShare" -FilePath "ContosoFile"`
> 
> This command gets the state of the copy operation for a file that has the specified name.

Maybe it would be helpful to add that that state is given by the [`CloudFile.CopyState` property](https://docs.microsoft.com/dotnet/api/microsoft.azure.storage.file.cloudfile.copystate?view=azure-dotnet-legacy).

**Comment by blueww** [comment]
@paulomorgado 

User can easily get the output type from help file output section  (I have have PR to update it: https://github.com/Azure/azure-powershell/pull/11860), or from the cmdlet output object like following, so we generally don't include the output type in the example :

```powershell
PS C:\temp> $state = Get-AzStorageFileCopyState -ShareName $containerName -FilePath test1.txt -Context $ctx

PS C:\temp> $state.GetType().FullName
Microsoft.Azure.Storage.File.CopyState
```

**Comment by paulomorgado** [comment]
@blueww, I would prefer something like this:

    PS C:\temp> $state = (Get-AzStorageFileCopyState -ShareName $containerName -FilePath test1.txt -Context $ctx).CopyState

**Comment by paulomorgado** [comment]
Except that, from #11860, the output will change from `CloudFile` to `CopyState`.

This also means that I can no longer pipe the cmdlets like this:

    Start-AzStorageFileCopy ... | Get-AzStorageFileCopyState -WaitForComplete | Remove-AzStorageFile

**Comment by blueww** [comment]
@paulomorgado

You might misunderstand https://github.com/Azure/azure-powershell/pull/11860
As it only change the output type of "Get-AzStorageFileCopyState", the following pipeline still work. (Actually, this output type not change, just to fix doc to make it align with the current cmdelt behavior)

```powershell
Start-AzStorageFileCopy ... | Get-AzStorageFileCopyState -WaitForComplete | Remove-AzStorageFile
```
And as the output of Get-AzStorageFileCopyState is already `CopyState`, it don't have a property as 'CopyState' , so the following sample change won't work.
```
PS C:\temp> $state = (Get-AzStorageFileCopyState -ShareName $containerName -FilePath test1.txt -Context $ctx).CopyState
```
