### ISSUE TITLE
Inappropriate error message from Add-AzureVhd cmdlet

### ISSUE THREAD

**Issue by amitsara** [Azure/azure-powershell#1186]
Add-AzureVhd throws "Add-AzureVhd : The Remote server returned an error: (400) Bad Request." error message when invalid destination path (valid_blobstorage\invalid_foler) is specified. 
 
It should say folder doesn’t exist so that user can correct the mistake.

**Comment by singhkay** [comment]
@amitsara Can you see what the message returned from server is when you specify the -Debug flag?
