### ISSUE TITLE
Missing feature parity with Azure CLI for Restore-AzDeletedWebApp

### ISSUE THREAD

**Issue by janegilring** [Azure/azure-powershell#11862]
## Description

The Restore-AzDeletedWebApp should have feature parity with the Azure CLI (az webapp deleted restore).

## Background

The following article described the feature for restoring a deleted app in App Service:
https://docs.microsoft.com/en-us/azure/app-service/app-service-undelete
 
The relevant documentation for performing the task with the Azure CLI:
https://docs.microsoft.com/en-us/cli/azure/webapp/deleted?view=azure-cli-latest
 
As well as Azure PowerShell:
https://docs.microsoft.com/en-us/powershell/module/az.websites/restore-azdeletedwebapp?view=azps-3.8.0
 
To get the collection of deleted apps, I used Get-AzDeletedWebApp:
 
Name                             DeletionTime        ResourceGroupName        Location
----                             ------------        -----------------        --------
MyApp                05.05.2020 12:33:58 App-Rg        West Europe
MyApp                08.05.2020 18:21:02 App-Rg        West Europe
 
In this case, I want to restore the one from 05.05.2020, as the one from 08.05.2020 was created as a Windows app, while the one from 05.05.2020 is a Linux app.
App 'MyApp' of kind 'app,linux' incompatible with app 'MyAPp' of kind 'app'
 
Hence the one from 08.05.2020 was deleted.
However, when running Restore-AzDeletedWebApp, it doesn`t allow to specify which timestamp to restore from – and it always seem to be restoring the latest one:
WARNING: Found multiple matching deleted apps. Restoring the most recently deleted app, deleted at 05/08/2020 18:21:02
 
I can`t seem to find any way to specify which version/timestamp of the web app to restore using  Azure PowerShell.

However, the Azure the CLI has a –deleted-id parameter for specifying the site id corresponding to the timestamp one would want to restore from:
az webapp deleted restore --deleted-id /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Web/deletedSites/1234 --name MySite --resource-group MyResourceGroup --subscription MySubscription
 
As this parameter is not available in the corresponding Azure PowerShell command, there seems to be some incomplete feature parity – so I will suggest a similar parameter is added to the Restore-AzDeletedWebApp Azure PowerShell command.

**Comment by dingmeng-xue** [comment]
Thanks for suggestion. I inolve Web App team to evaluate this feature.

**Comment by panchagnula** [comment]
@janegilring please check https://docs.microsoft.com/en-us/powershell/module/Az.Websites/Restore-AzDeletedWebApp?view=azps-4.2.0

**Comment by janegilring** [comment]
@panchagnula I checked the link, but couldn't see any parameter for specifying the id of a deleted site. If something changed recently I suppose i might not have propagated yet.

**Comment by panchagnula** [comment]
For PS you need to give the name of the deleted app you want to restore, instead of the full resource Id -is that not working? This I believe came down to the fact that in PS Name is the common parameter & hence was done this was for consistency.

**Comment by janegilring** [comment]
Specifying the name works, but that will always restore the latest version. It is not possible to restore the app from a specific date like we can in Azure CLI with the –deleted-id parameter (for specifying the site id corresponding to the timestamp one would want to restore from).

**Comment by panchagnula** [comment]
Thanks for the feedback let me check with the feature owners and get back to you on this. Thanks.
