### ISSUE TITLE
Get-AzAks is missing (many) details provided by `az aks list`

### ISSUE THREAD

**Issue by jsco2t** [Azure/azure-powershell#11885]
## Description

When I issue a call to `az aks list` I get a large JSON document back with what appears to be a complete dump of the details related to the AKS cluster matching the input parameters.

When I make the same call to `Get-AzAks` I get a significantly abbreviated version of the details for the same cluster. 

In particular data fields like the following appear to be missing from the output:
- aadProfile
- addonProfiles
- rbac related info
- identityProfile <--- when using `managed identity clusters` this is needed to find the `User Managed Id` that AKS/Azure creates for us.
- nodeResourceGroup
....etc....etc

My expectation is that I should be able to get the **exact** same level of detail from `Get-AzAks` as I do from `az aks list`. For reasons beyond the scope of this bug report - I need to use the _PowerShell CLI_ to interact with Azure instead of the _Console CLI_ and these limitations are a significant impediment to working with AKS via PowerShell.

## Steps to reproduce

```powershell
Get-AzAks -ResourceGroupName {ResourceGroupContainingAksGoesHere}
```

```bash
az aks list --resource-group {ResourceGroupContainingAksGoesHere}
```

## Environment data

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
Script     3.6.1                 Az
Script     1.0.3                 Az.Aks
```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
Thanks for the feedback. Azure PowerShell needs to deserialize output. It is different from Azure CLI.  We will evaluate the feature.

**Comment by erich-wang** [comment]
@jsco2t , could you please try latest stable version Az.Aks 1.1.1? The return value is object and you could use **.** to access return object's properties.

**Comment by erich-wang** [comment]
@jsco2t , have you had chance to try Az.Aks 1.1.1? Does it work for you? We'll assume the issue has been solved and will close the issue if we don't hear from you within 5 days, thanks.

**Comment by dingmeng-xue** [comment]
Close this issue and required attributes are added.

**Comment by jsco2t** [comment]
Sorry for the slow follow-up. The updated version looks great. Thanks so much for getting a bug fix in for it.
