### ISSUE TITLE
Update-AzWebAppAccessRestrictionConfig -ScmSiteUseMainSiteRestrictionConfig: mandatory?

### ISSUE THREAD

**Issue by gsscoder** [Azure/azure-powershell#11882]
A switch parameter mandatory (`-ScmSiteUseMainSiteRestrictionConfig`) is a very strange case, but I know is possible to explicitly set it.

If I specify also `-InputObject` I got the following error:
```
Update-AzWebAppAccessRestrictionConfig -ResourceGroupName $group -Name $name --ScmSiteUseMainSiteRestrictionConfig:$fals -InputObject $restr
trictionConfig:$false
Update-AzWebAppAccessRestrictionConfig : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Update-AzWebAppAccessRestrictionConfig -ResourceGroupName $group -Nam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-AzWebAppAccessRestrictionConfig], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.UpdateAzureWebAppAccessRestrictionConfigCmdlet
```

What's the right way to call this function?

Thank you

**Comment by dingmeng-xue** [comment]
@gsscoder, if you paste is correct, it seems there is an additional dash before ScmSiteUseMainSiteRestrictionConfig. 
Following syntax of this cmdlet, you cannot use inputobject if you already set ScmSiteUseMainSiteRestrictionConfig.

**Comment by gsscoder** [comment]
@dingmeng-xue, hello thank you for replying! :)

I've tried various times, it seems I've pasted a wrong command with double 'dash'. Sorry.
OK, I've seen from the source parameters belong to different parameter sets.

For the moment I close the issue since I've solved using **Az/CLI** `az webapp config access-restriction`.
Thanks for the support.
