### ISSUE TITLE
Add-AzureRmVMNetworkInterface has no effect

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#1190]
When running `Add-AzureRmVMNetworkInterface -NetworkInterface $nic -VM $vm` no error is returned, but no change is performed on the specified vm either.

**Comment by dprob** [comment]
Corey
…I guess this is better than…

Thanks,
Rob Harryman | 515-535-8336 | rob.harryman@pioneer.com<mailto:rob.harryman@pioneer.com>
or dl-awsphioperations@pioneer.com<mailto:dl-awsphioperations@pioneer.com>

**Comment by trondhindenes** [comment]
Any updates on this?

**Comment by DeepakRajendranMsft** [comment]
Hi @trondhindenes, Could you please send us the full list of commands that you are using to create the VM?

Are you trying to use Add-AzureRmVMNetworkInterface on an already existing VM?

**Comment by trondhindenes** [comment]
I simply ran:
```powershell
$vms = get-azurermvm
$vm = $vms[0]
$vm | Add-AzureRmVMNetworkInterface
```

Looking at the help content I later noticed that the cmdlet doesn't seem to support pipelining, so the curious thing is that it doesn't return an error.

**Comment by DeepakRajendranMsft** [comment]
closing since resolved
