### ISSUE TITLE
Error when calling Get-AzApiManagementUser

### ISSUE THREAD

**Issue by rabbboudi** [Azure/azure-powershell#11912]
## Description
I have an error when I try to execute this command Get-AzApiManagementUser. One of the users has 2 identities (basic and Azure AD)

## Steps to reproduce
$apimContext = New-AzApiManagementContext -ResourceGroupName "RG_Name" -ServiceName "Service_Name"
Get-AzApiManagementUser -Context $apimContext 

```powershell

```

## Environment data

```

```

## Module versions

```powershell
Installed module version  Az.ApiManagement 1.4.1
```

## Debug output

```

```

## Error output

Get-AzApiManagementUser : Error mapping types.
Mapping types:
List`1 -> IList`1
System.Collections.Generic.List`1[[Microsoft.Azure.Management.ApiManagement.Models.UserContract, Microsoft.Azure.Management.ApiManagement, Version=4.0.0.0, Culture=neutral, 
PublicKeyToken=31bf3856ad364e35]] -> System.Collections.Generic.IList`1[[Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Models.PsApiManagementUser, 
Microsoft.Azure.PowerShell.Cmdlets.ApiManagement.ServiceManagement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]
Au caractère Ligne:1 : 1
+ Get-AzApiManagementUser -Context $context
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError : (:) [Get-AzApiManagementUser], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.GetAzureApiManagementUser

```

```

**Comment by dingmeng-xue** [comment]
I involve APIManagement team to look into this issue.

**Comment by rabbboudi** [comment]
A user was not correctly created (it had two basic identities). It worked fine once I've deleted it.
I will close this issue.
Thank you
