### ISSUE TITLE
[Security] New cmdlets for Settings

### ISSUE THREAD

**Issue by taklei** [Azure/azure-powershell#11916]
## Service Release Details

- **Is this an Embargoed Preview, A Public Preview, or a General Release?**
General Release

- **What is the expected service release date?**
The services are already released. These particular commands are to be released whenever the code is ready.

## Contact Information
- Main developer contacts (emails + github aliases)
taklei@microsoft.com + taklei
nibracha@microsoft.com + nitsi
oranbr@microsoft.com

## Contact Information
- **Describe how your feature is intended to be used by customers.**
To enable customers to get/set security setting in Azure Security Center.

- **Piping scenarios / how these cmdlets are used with existing cmdlets**
It can be piped by Get and then Set.

- **Sample of end-to-end usage**
````
$setting = Get-AzSecuritySetting -SettingName "MCAS"
$setting.Enabled = $true
Set-AzSecuritySetting -SettingName "MCAS" -SettingInput $setting
_______________
Id: "/subscriptions/487bb485-b5b0-471e-9c0d-10717612f869/providers/Microsoft.Security/settings/MCAS"
Name: "MCAS"
Type: "Microsoft.Security/settings"
Enabled: true
````
## Syntax changes
- No syntax changes

- **New Cmdlets**
Get - 
https://github.com/taklei/azure-powershell/blob/master/src/Security/Security/help/Get-AzSecuritySetting.md
Set - 
https://github.com/taklei/azure-powershell/blob/master/src/Security/Security/help/Set-AzSecuritySetting.md

- **Changed Cmdlets**

## Guidelines
- **Do your cmdlets comply with the design guidelines outlined in the PowerShell Design Guidelines document? [link](https://github.com/Azure/azure-powershell/tree/master/documentation/development-docs/design-guidelines)
 Yes

**Comment by taklei** [comment]
Hi - Can someone review please? :)

**Comment by dingmeng-xue** [comment]
Close it due to incorrect request.
