### ISSUE TITLE
Clarify documentation around Get/Set-AzStorageBlobContent concurrency protection

### ISSUE THREAD

**Issue by ashmind** [Azure/azure-powershell#11918]
## Description of the new feature

It is currently unclear how to implement optimistic or pessimistic concurrency using `Get-AzStorageBlobContent` and `Set-AzStorageBlobContent`.

In my understanding, Blob optimistic concurrency is implemented using `ETag` and `If-Match`, but I am not sure how to get `ETag` from `Get-AzStorageBlobContent` and how to send `If-Match` in `Set-AzStorageBlobContent`.

In my understanding, Blob pessimistic concurrency is implemented through leases, but while I can call `$blob.ICloudBlob.AcquireLease` on the result of `Get-AzStorageBlob`, I am not sure how to pass a lease condition into `Set-AzStorageBlobContent`.

## Proposed implementation details (optional)

If that is supported, documentation update to explain how to do it in PowerShell (e.g. I can easily see how to do in Azure CLI).

If that is currently not supported, documentation update to mention it's not supported, with a recommendation on how to do it using .NET objects (`ICloudBlob`?) in PowerShell.

**Comment by dingmeng-xue** [comment]
Storage team, please help to look into this question.

**Comment by blueww** [comment]
@ashmind

The Set-AzStorageBlobContent use [DMlib library](https://github.com/Azure/azure-storage-net-data-movement) to upload Blob parallelly for better performance. DMlib will use Etag(If-Match) inside to make sure the content upload correctly.

What's your user scenarios? Do you want to upload a blob with access condition like leaseID?
We currently don't support Lease ID in Set-AzStorageBlobContent. But you can call Blob API in .net SDK inside Powershell to upload with accesscondition. This is a nature behavior of Powershell, so we don't document every SDK API in Powershell doc:

```powerhsell
$ac = New-Object -TypeName "Microsoft.Azure.Storage.AccessCondition"
$ac.LeaseId = $leaseID

$blob = Get-AzStorageBlob -Container $containerName -Blob $blobName -Context $ctx
$a.ICloudBlob.UploadFromFile($localSrcFile,$ac)
```

**Comment by ashmind** [comment]
Thanks -- I think that's clear enough and worth to be included in the docs. At least the part about `ETag` being checked automatically -- I can guess LeaseId is not supported by looking at `Set-AzStorageBlobContent` parameters, but I would not know it checks `ETag`.

In my scenario I have several processes running in parallel during the build, and all of them might update the same blob, so I need to use either `ETag` or lease to make sure they don't overwrite changes by each other.

**Comment by blueww** [comment]
@ashmind

Actually, Powershell currently only support upload whole file to blob. What Powershell do is ensure the uploaded blob has same content of the source file. Etag is only one way we used to ensure that. 

We currently don't think it's so necessary to document all the details we used in Powershell to ensure the content correctness, until more customer ask.

**Comment by ashmind** [comment]
Thanks! I see, that's not a concurrency protection logic. In that case I agree. A note that there is no support for either optimistic or pessimistic concurrency in those commands would be good, as it can save time trying to find corresponding parameters.

But up to you, I suppose any new web searches will find this ticket so maybe people won't be lost anymore.

**Comment by blueww** [comment]
@ashmind 
Thanks for you understanding!
I think you are OK with it now, so I will close this issue.
Feel free to contact us if you need further assistance on Azure Powershell.
