### ISSUE TITLE
AzureDatafactory Deserialization failure

### ISSUE THREAD

**Issue by dagasparmsft** [Azure/azure-powershell#11914]
When using the pipeline1 defined below in ADF, the ADF command Get-AzDataFactoryV2Pipeline -dataFactoryName "<df>" -resourceGroupName "<rg>" fails with the error below. The issue seems to be with the line '"value": "@union(createArray('arg','arg2'))",'. This syntax creates a working pipeline. However, Get-AzDataFactoryV2Pipeline fails to deserialize it.

{
 "name": "pipeline1",
 "properties": {
 "activities": [
 {
 "name": "Spark1",
 "type": "HDInsightSpark",
 "dependsOn": [],
 "policy": {
 "timeout": "7.00:00:00",
 "retry": 0,
 "retryIntervalInSeconds": 30,
 "secureOutput": false,
 "secureInput": false
 },
 "userProperties": [],
 "typeProperties": {
 "rootPath": "a",
 "entryFilePath": "b.py",
 "arguments": {
 "value": "@union(createArray('arg','arg2'))",
 "type": "Expression"
 },
 "sparkJobLinkedService": {
 "referenceName": "workspaceControlPlaneStorageLinkedService",
 "type": "LinkedServiceReference"
 }
 },
 "linkedServiceName": {
 "referenceName": "workspaceHdiClusterLinkedService",
 "type": "LinkedServiceReference"
 }
 }
 ],
 "annotations": []
 },
 "type": "Microsoft.DataFactory/factories/pipelines"
}

Get-AzDataFactoryV2Pipeline : Unable to deserialize the response.
At line:1 char:1
+ Get-AzDataFactoryV2Pipeline -dataFactoryName "adfwpysialhunlux" -reso ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzDataFactoryV2Pipeline], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataFactoryV2.GetAzureDataFactoryPipelineCommand

**Comment by dingmeng-xue** [comment]
Data Factory team, please help to look into this issue.

**Comment by lmy269** [comment]
@shawnxzq , can you take a look?

**Comment by shawnxzq** [comment]
This is by design for now, we will monitor and see whether support this new functionality.
