### ISSUE TITLE
Please explain how to handle managed identity token expiry

### ISSUE THREAD

**Issue by MonikaReddy-MSFT** [Azure/azure-powershell#11923]
Customer has reported this issue in Docs page - 

When I log on with "Connect-AzureRmAccount -MSI" things eventually stop working in my long-running script because there under the hood there is an access token that expires. Even when I add an hourly "Disconnect-AzureRmAccount" and logon again with "Connect-AzureRmAccount -MSI", it sometimes continues to give exceptions saying token expired. Killing the process and starting it again seems to force the token renewal - but surely there is a better way?? Here's an example of the exception:
Login-AzureRmAccount : The access token expiry UTC time '5/5/2020 11:41:43 AM' is earlier than
current UTC time '5/5/2020 12:25:04 PM'.

Issue created here - https://github.com/MicrosoftDocs/azure-docs-powershell/issues/1381 

https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-3.8.0

**Comment by dingmeng-xue** [comment]
@MonikaReddy-MSFT, access toke normally will be expired in one hour. How long does your long running script take? Could you find if there is time consuming LRO cmdlet?

**Comment by dingmeng-xue** [comment]
Close this issue now. Please reopen or create new one if there is further information.
