### ISSUE TITLE
Allow Refreshing Token Credentials

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#11925]
## Description of the new feature

When using Connect-AzAccount -AccessToken <token>, there is no mechanism for renewing the token for long-running operations.  Allow renewing the access token, either with a new command, or by running Connect-AzAccount with new token values.

**Comment by dingmeng-xue** [comment]
Let's plan it accordingly.

**Comment by VeryEarly** [comment]
fixed in #12454
