### ISSUE TITLE
Can't not import PSScheduledJob module

### ISSUE THREAD

**Issue by t105362506** [Azure/azure-powershell#11927]
import this module   "Import-Module PSScheduledJob"   & get this error message

i don't  know how to fix this error 

Error message: Import-Module: Module 'PSScheduledJob' is blocked from loading using Windows PowerShell compatibility feature by a 'WindowsPowerShellCompatibilityModuleDenyList' setting in PowerShell configuration file.

**Comment by dingmeng-xue** [comment]
Thanks for contacting us. This module doesn't belong to Azure PowerShell. Please contact PowerShell team. https://github.com/PowerShell
