### ISSUE TITLE
[MySQL/MariaDB/PostgreSQL] The values to use for the SKU parameter were not intuitive 

### ISSUE THREAD

**Issue by msJinLei** [Azure/azure-powershell#11930]
## Description of the new feature
In module MySql, the values to use for the SKU parameter were not intuitive and if a non-supported value is used, the error should be explicit and if possible, list the authorized values

## Proposed implementation details (optional)
- Request service team to provide a new operation to get sku https://github.com/Azure/azure-rest-api-specs/issues/9537
- Implement a new cmdlet or some way else to provide the user with sku list

**Comment by dingmeng-xue** [comment]
Can we know how Portal handles this case?

**Comment by nachoalonsoportillo** [comment]
@msJinLei Thanks for reporting this issue. It seems this was fixed long time ago.

**Comment by nachoalonsoportillo** [comment]
Closing
