### ISSUE TITLE
[MySQL/MariaDB/PostgreSQL] Get-AzMySqlConnectionString is expected to be found under “connect and query”

### ISSUE THREAD

**Issue by msJinLei** [Azure/azure-powershell#11935]
## Description
The cmdlet users expect to find  Get-AzMySqlConnectionString in the conceptual documentation under “connect and query”.
The same issue for MariaDB & PostgreSQL

**Comment by dingmeng-xue** [comment]
@mikefrobbins , can we or some people to update doc? @dcaro , can provide more information.

**Comment by mikefrobbins** [comment]
Requested docs created and added. See PR MicrosoftDocs/azure-docs-pr#125180, MicrosoftDocs/azure-docs-pr#124837, and MicrosoftDocs/azure-docs-pr#124708
