### ISSUE TITLE
[MySQL/MariaDB/PostgreSQL] New-AzMySqlFirewallRule create a default name with time stamp when no name is passed

### ISSUE THREAD

**Issue by msJinLei** [Azure/azure-powershell#11932]
## Description of the new feature
From @dcaro 

When you add a firewall rule for a specific IP address (the add current client IP Address button) , the portal generates a rule with the name “ClientIPAddress_YYYYY-MM-DD_HH-MM-SS”.
It doe the same with the name “AllowAll_YYYYY-MM-DD_HH-MM-SS” when the range is 0.0.0.0 – 255.255.255.255 as you can see in the screenshot below.

![portal_firewall](https://user-images.githubusercontent.com/54836179/89885236-55263e80-dbfd-11ea-9655-6e0d83bc387f.png)

The suggestion was to get to a similar behavior so here is my proposal: 

1.	Add a ‘-ClientIpAddress’ parameter and when used we create a rule with the characteristics as above: ClientIPAddress_YYYYY-MM-DD_HH-MM-SS 
Ideally when startIP = endIP and no names are passed we should do the same but I am not sure this worth the effort.

2.	Similarly we can add a -AllowAll parameter that would create a rule name “AllowAll_YYYYY-MM-DD_HH-MM-SS” with a startIP of 0.0.0.0 and endIp of 255.255.255.255

3.	When no name is defined for the rules we pass “undefined” as does the portal.

 
## Proposed implementation details (optional)

**Comment by dingmeng-xue** [comment]
Target to S173

**Comment by msJinLei** [comment]
More comments from @dcaro on the feature requirement


>Based on the feedback from the MySQL team on the other thread, it looks like they prefer the following option: 

>SYNTAX
>CreateExpanded (Default)
>New-AzMySqlFirewallRule -ResourceGroupName <String> -ServerName <String> -StartIPAddress <String>
>-EndIPAddress <String> [-Name <String>] [-SubscriptionId <String>] [-DefaultProfile <PSObject>] [-AsJob]
>[-NoWait] [-Confirm] [-WhatIf] [`<CommonParameters`>]

>AllowAll
>New-AzMySqlFirewallRule -ResourceGroupName <String> -ServerName <String> -AllowAll [-Name <String>]
>[-SubscriptionId <String>] [-DefaultProfile <PSObject>] [-AsJob] [-NoWait] [-Confirm] [-WhatIf]
>[`<CommonParameters`>]

>ClientIp
>New-AzMySqlFirewallRule -ResourceGroupName <String> -ServerName <String> - ClientIpAddress <String>
>[-Name <String>] [-SubscriptionId <String>] [-DefaultProfile <PSObject>] [-AsJob] [-NoWait] [-Confirm]
>[-WhatIf] [`<CommonParameter`s>]

>For the last parameterset (the one using “-ClientIpAddress”), the rule name is in the form of “ClientIpAddress_YYYY-MM-DD_HH-MM-SS”.
