### ISSUE TITLE
[MySQL/MariaDB/PostgreSQL] The name of the server being unique globally, the resource group name should be optional

### ISSUE THREAD

**Issue by msJinLei** [Azure/azure-powershell#11931]
## Description of the new feature
The name of the server being unique globally, the resource group name should be optional
## Proposed implementation details (optional)
- Request service team to provide a new url  https://github.com/Azure/azure-rest-api-specs/issues/9538
- Add a new parameter set to Update-AzMySqlFirewallRule

**Comment by dingmeng-xue** [comment]
Wait service team to provide new endpoint.

**Comment by ajlam** [comment]
Linked to Azure/azure-rest-api-specs#9538 and following up there.

**Comment by ajlam** [comment]
Closing this issue as won't fix.
