### ISSUE TITLE
Remove-AzureRmWebAppSSLBinding also removes tags

### ISSUE THREAD

**Issue by BobTheMadCow** [Azure/azure-powershell#11942]
As per issue [#5970](https://github.com/Azure/azure-powershell/issues/5970), the Remove-AzureRmWebAppSSLBinding in v5.2.0 of AzureRM.Websites removes tags on the resource.

It would appear that New-AzureRmWebAppSSLBinding is still exhibiting this behaviour too.

**Comment by dingmeng-xue** [comment]
@BobTheMadCow , could you try `Remove-AzWebAppSSLBinding`?

**Comment by dcaro** [comment]
@BobTheMadCow this issue has been fixed in the Az.WebSites module.
Please install the most recent version of this module or use the Az module.
