### ISSUE TITLE
[MySQL/MariaDB/PostgreSQL] Add example of how to specify InputObject without piping for New-AzMySqlServerReplica

### ISSUE THREAD

**Issue by msJinLei** [Azure/azure-powershell#11940]
## Description
The users were confused with the use of the ‘InputObject’ parameter using a ‘PSObject’ object. This could be addressed with the reference doc and better examples.

Fix the similar issue in PostgreSQL & MariaDB

**Comment by dingmeng-xue** [comment]
Please update example.

**Comment by LucasYao93** [comment]
> Please update example.

I have updated examples. PR:[https://github.com/Azure/azure-powershell/pull/11972/]

**Comment by LucasYao93** [comment]
PR(#11972) has been merged.
