### ISSUE TITLE
[Az.Functions] Need to add support to create Java 11 function apps

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-powershell#11957]
Need to add support to create Java 11 function apps

**Comment by Francisco-Gamino** [comment]
cc: @amamounelsayed @anirudhgarg

**Comment by amamounelsayed** [comment]
Thank you so much @Francisco-Gamino 
Here is the info

Set “javaVersion” site config property to “11” - Windows
Set "linuxFxVersion" site property to "java|11" - Linux

**Comment by Francisco-Gamino** [comment]
This issue has been fixed as part of the latest Az.Functions release.
