### ISSUE TITLE
[MySQL] Provide hint in doc to use Update-AzMySqlServer & Update-AzMySqlServerConfiguration as a candidate for each other. 

### ISSUE THREAD

**Issue by msJinLei** [Azure/azure-powershell#11954]
## Description of the new feature
Customers have difficult to choose between Update-AzMySqlServer & Update-AzMySqlServerConfiguration when they want to update setting of server.
## Proposed implementation details (optional)
Improve the docs of these two cmdlets in MySQL/MariaDB/PostgreSQL to tell users to use the other cmdlet if the current one is not right for what they want to do.

**Comment by dingmeng-xue** [comment]
Please update doc and invite @mikefrobbins to review.
