### ISSUE TITLE
Az.AlertsManagement Module is not installed with Az module

### ISSUE THREAD

**Issue by jonarmstrong** [Azure/azure-powershell#11950]
Installing the Az module with the command

```
Install-Module Az -Force
```

Does not install the `Az.AlertsManagement` module. As the Az.AlertsManagement module is part of the Az module, in the [reference](https://docs.microsoft.com/en-us/powershell/module/az.alertsmanagement/?view=azps-4.1.0#alerts_management) section in the documentation, I would expect that module to be installed as a dependency of the Az module.

**Comment by dingmeng-xue** [comment]
Thanks for contacting us. AlertsManagement  module is still under preview. It won't be packaged Az module. Please use  below cmdlet to install it.
```
Install-Module -Name Az.AlertsManagement	
```
