### ISSUE TITLE
[Storage] Fix the User Agent for dataplane cmdlets 

### ISSUE THREAD

**Issue by blueww** [Azure/azure-powershell#11963]
## Description

The Storage dataplane cmdlets (not use DMlib ones) has user agent which not include word "Powershell".
Need to fix by include the word "Powershell" and version.
Like:

> UserAgent='Azure-Storage/11.1.1 (.NET Core; Win32NT 10.0.18363.0)' 

## Cost
TBD

**Comment by dingmeng-xue** [comment]
Could you share one cmdlet? We can check its client telemetry.

**Comment by blueww** [comment]
@dingmeng-xue
Like Set-AzStorageBlobContent will use the user agent set in https://github.com/Azure/azure-powershell/blob/ce5a8b5087be6cfc3fb462a4605de879999c165a/src/Storage/Storage/Common/DataManagementWrapper.cs#L33

We have other cmdlets like Get-AzStorageContainer, still don't have "Powershell" in the user agent, I will add soon.

**Comment by blueww** [comment]
This issue should have been fixed long ago.

The user agent of Get-AzStorageContainer in latest Az.Storage has "Powershell" in the user agent, like "User-Agent: AzurePowershell/v1.0.0 azsdk-net-Storage.Blobs/12.18.0 (.NET Framework 4.8.9241.0; Microsoft Windows 10.0.22631 )"
