### ISSUE TITLE
Error-Blank Output

### ISSUE THREAD

**Issue by Neelkamal10** [Azure/azure-powershell#11970]
@azure-sdk ## Description
(Get-AzWebApp).SiteConfig.AppSettings
While running this cmdlet, i am getting blank output.
the below attached picture illustrate it more clearly.
![Screenshot (69)](https://user-images.githubusercontent.com/54034262/82559555-7858c900-9b8d-11ea-979d-77b23ad2e4e2.png)

**Comment by dingmeng-xue** [comment]
@Neelkamal10 , please share debug message after set `$DebugPreference="Continue"`
