### ISSUE TITLE
token always expires after about 1 hour

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/azure-powershell#11974]
Hi,

Hope everything's going well! These two days I was really bothered by the token expiration issue. I have changed my Azure account password 2 days ago and run Clear-AzContext and Disable-AzContextAutosave in my win10, and then re-login through Connect-AzAccount (multi-factor auth). Then I run Enable-AzContextAutosave to keep it login and re-login through Connect-AzAccount. But after that, I found that when I ran "Get-AzSubscription" after about 1 hour, it showed "Run Connect-AzAccount to login". I login again and then after 1 hour it told me to login again...
It has never happened before. It should be keeping login until the next time to change password. I don't know why it happened now. I have another Linux environment which was logined with azure-cli, and it wasn't expired.
Do you have any idea about that? Is there any way to check the expiry setting in Azure Powershell? Thank you so much!!

**Comment by dingmeng-xue** [comment]
@yuxisun1217 , could you execute `Get-AzContextAutosaveSetting` and share the result to us?

**Comment by yuxisun1217** [comment]
PS C:\WINDOWS\system32> Get-AzContextAutosaveSetting


Mode             : CurrentUser
ContextDirectory : C:\Users\yuxisun\.Azure
ContextFile      : AzureRmContext.json
CacheDirectory   : C:\Users\yuxisun\.Azure
CacheFile        : TokenCache.dat
Settings         : {}

**Comment by yuxisun1217** [comment]
Hi there,
I just found the root cause of this issue and it's not related to Az module itself. Apologize for the false positive and thank you for your time!
