### ISSUE TITLE
Create VM basing on parameters of one existing vm

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#11989]
## Description of the new feature
Compared by customer https://twitter.com/Steve_MSFT/status/1264773780330569734?s=19

It will be nice that New-AzVM supports creating VM basing on an existing VM within on cmdlet.

## Proposed implementation details (optional)
Get existing VM configuration at the first and then create a new one using that configuration.

**Comment by Drewm3** [comment]
I have opened this as a feature request in feedback.azure.com: https://feedback.azure.com/forums/216843-virtual-machines/suggestions/40509406-create-vm-basing-on-parameters-of-one-existing-vm
