### ISSUE TITLE
Get-AzADUser -Mail option does not work, is there another way to do it. Same issue by using AAD client directly when filter set to mail

### ISSUE THREAD

**Issue by DhivyaG19** [Azure/azure-powershell#11981]
From additional debugging, filter applied is UPN, should be mail.

I tried using AAD client directly by setting filter in it to mail, still same issue.

Also, type is always null, I thought it will be guest
```
Get-AzADUser -Mail "mireks.pm@xxxxxx.com" -Debug
DEBUG: 4:46:20 PM - GetAzureADUserCommand begin processing with ParameterSet 'MailParameterSet'.

HTTP Method:
GET
Absolute Uri:
https://graph.windows.net/dbef1e29-488c-4b64-90ac-287b977faaa3/users?$filter=userPrincipalName eq
'mireks.pm@xxxxxxx.com'&api-version=1.6

Body:
{
  "odata.metadata": "https://graph.windows.net/dbef1e29-488c-4b64-90ac-287b977faaa3/$metadata#directoryObjects",
  "value": []
}
```
When I give my full UPN it works.
```
Get-AzADUser -Mail "mireks.pm_xxxxxx.com#EXT#@xxxxxxx.onmicrosoft.com"
UserPrincipalName : mireks.pm_xxxxxxx.com#EXT#@xxxxx.onmicrosoft.com
ObjectType        : User
DisplayName       : mireks xxxxx
Id                : 40146d24-4b42-498c-b4c1-d6a1c223d21e
Type              :
```

**Comment by dingmeng-xue** [comment]
`-mail` parameter equals to user principal name in AAD. Current logic in Azure PowerShell is to search user by UPN or Display name via AAD rest API. Type should be guest or member. We will fix it soon.

**Comment by DhivyaG19** [comment]
Thanks @dingmeng-xue for confirming for Type property.

For -mail switch, according to MS Graph [User object](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0) documentation UPN and mail are different properties. Get-AzADUser powershell also have two different switch UserPrincipalName & Mail separately for user properties UPN and mail accordingly.

**Comment by dingmeng-xue** [comment]
Azure PowerShell is still using Azure AD lib. I didn't investigate further. I guess MS Graph is a little different.

**Comment by dingmeng-xue** [comment]
@DhivyaG19 , thanks for reporting. You are right that I have reproduced the issue. Below code is incorrect.
https://github.com/Azure/azure-powershell/blob/54851b406ee36b4384c9cee098584128ff7ca1b9/src/Resources/Resources/ActiveDirectory/Models/ActiveDirectoryClient.cs#L201

We will fix this issue soon.
