### ISSUE TITLE
Azure PowerShell allows to add multiple endpoints with same private port

### ISSUE THREAD

**Issue by sudheer0503** [Azure/azure-powershell#1198]
Steps to repro :
1.  Create VM in Azure
2.  Add endpoint with name “Remote EndPoint” using below
a.  Get-AzureVM -ServiceName tfssdsandbox -Name tfssdsandboxv02  | Add-AzureEndpoint -Name "RemoteDesktop" -Protocol tcp -LocalPort 3389 | Update-AzureVM
3.  Add endpoint with name RemoteEndpoint using below
a.  Get-AzureVM -ServiceName tfssdsandbox -Name tfssdsandboxv02  | Add-AzureEndpoint -Name "Remote Desktop" -Protocol tcp -LocalPort 3389 | Update-AzureVM
4.  Now, we can’t add endpoint as below :
a.  Get-AzureVM -ServiceName tfssdsandbox -Name tfssdsandboxv02  | Add-AzureEndpoint -Name "PowerShell" -Protocol tcp -LocalPort 5986 | Update-AzureVM
               Fails with error unrelated to endpoint I am creating which is PowerShell:
                    Update-AzureVM : BadRequest : Local Port 3389 for endpoint RemoteDesktop is already in use by one of the other endpoints in this role. Ensure that the local port numbers are unique across endpoints within a role.
At line:1 char:134
- ... nt -Name "Power Shell" -Protocol tcp -LocalPort 5986 | Update-AzureVM
-                                                            ~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Update-AzureVM], CloudException
  - FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.UpdateAzureVMCommand

**Comment by bittusarkar** [comment]
+1 I'm facing this issue too. At this point, I'm not even able to delete the end-points that got created.

**Comment by singhkay** [comment]
@hyonholee Can you take a look at this?

**Comment by maddieclayton** [comment]
Closing. Please reopen this issue if it is still an issue in the most recent version.
