### ISSUE TITLE
SavedSearch create required optional property (version)

### ISSUE THREAD

**Issue by yossi-y** [Azure/azure-powershell#11992]
Got an error when ran without version:
PS C:\Users\yossiy> New-AzOperationalInsightsSavedSearch -ResourceGroupName yossiy -WorkspaceName yossiy -SavedSearchId 12345678 -DisplayName myTestSS -Category Yossi -Query 'Perf | count'
New-AzOperationalInsightsSavedSearch : 'Version' is less than minimum value of '1'.
At line:1 char:1
+ New-AzOperationalInsightsSavedSearch -ResourceGroupName yossiy -Works ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzOperationalInsightsSavedSearch], ValidationException
    + FullyQualifiedErrorId : Microsoft.Rest.ValidationException,Microsoft.Azure.Commands.OperationalInsights.NewAzureOperationalInsightsSavedSearchCommand

Succeeded when added version:
PS C:\Users\yossiy> New-AzOperationalInsightsSavedSearch -ResourceGroupName yossiy -WorkspaceName yossiy-sww -SavedSearchId 12345678 -DisplayName TestSavedSearch -Category Yossi -Query 'Perf | count' -Version 1
OK

The version shouldn't be mandatory: https://docs.microsoft.com/en-us/powershell/module/az.operationalinsights/Get-AzOperationalInsightsSavedSearch?view=azps-4.1.0

**Comment by VeryEarly** [comment]
Hi @yossi-y,

I tried the cmdlet you provided:
```
New-AzOperationalInsightsSavedSearch -ResourceGroupName yabo-test-group -WorkspaceName yabo-test-la -SavedSearchId 12345678 -DisplayName myTestSS -Category Yossi -Query 'Perf | count' -debug
```

Had successful response:
```
Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id               : 024cdebd-b39a-408b-a05c-a5fe18756945
x-ms-correlation-request-id   : 024cdebd-b39a-408b-a05c-a5fe18756945
x-ms-routing-request-id       : SOUTHEASTASIA:20200525T111142Z:024cdebd-b39a-408b-a05c-a5fe18756945
Date                          : Mon, 25 May 2020 11:11:41 GMT

Body:
{
  "id": "/subscriptions/9e223dbe-3399-4e19-88eb-0975f02ac87f/resourceGroups/yabo-test-group/providers/Microsoft.OperationalInsights/workspaces/yabo-test-la/savedSearches/12345678",
  "etag": "W/\"datetime'2020-05-25T11%3A11%3A42.161344Z'\"",
  "properties": {
    "category": "Yossi",
    "displayName": "myTestSS",
    "query": "Perf | count",
    "version": 2
  }
}


OK
```
Can you provide more detail how this can be re-produced?

**Comment by yossi-y** [comment]
How you can reproduce it:
1. create a Log Analytics workspace
2. run the cmdlet:
New-AzOperationalInsightsSavedSearch -ResourceGroupName {resource-group-name} -WorkspaceName {workspace-name} -SavedSearchId {unique-id} -DisplayName {saved-search-name} -Category {category-name} -Query 'Perf | count'

This should create a savesearch in your workspace.

**Comment by yossi-y** [comment]
Adding @Yoram Singer<mailto:yorams@microsoft.com>
I can reproduce on my machine.
I recorder a clip with the issue: https://microsofteur-my.sharepoint.com/:v:/g/personal/yossiy_microsoft_com/EarE-q0JdZdJqNwDL7fAiJMBBR9hurwTkJ5Q_W6RUqX7Pg?e=un7gQK

**Comment by VeryEarly** [comment]
Hi @yossi-y ,

Can you please share the version of Az.OperationalInsights you are using?

If you take a look at the sample response I commented, the query was saved without "-Version" and default value is "2", can you please share the version of Az.OperationalInsights or try the [latest](https://www.powershellgallery.com/packages/Az.OperationalInsights/2.0.0)?

**Comment by yossi-y** [comment]
I'm using:
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.1.0      Az.OperationalInsights              PSGallery            Microsoft Azure PowerShell - Operational Insights service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.

I've updated to the latest and tried again:
PS C:\Users\yossiy> New-AzOperationalInsightsSavedSearch -ResourceGroupName yossiy -WorkspaceName yossiy-sww -SavedSearchId 12345678 -DisplayName TestSavedSearch -Category Yossi -Query 'Perf | count'

OK

It works fine.
Sorry for the confusion.

**Comment by dingmeng-xue** [comment]
Close this issue now. @yossi-y, please contact us if there is other question.
