### ISSUE TITLE
Get-AzureAccount ignores -Name parameter

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-powershell#120]
I've tried 0.8.13 and 0.8.14, both behavior the same way.

TWO PROBLEMS:
a)	Get-AzureAccount optionally asks for a Name, but accounts only have an ID, so where am I supposed to find the name?
b)	Passing in a name to Get-AzureAccount is supposed to make it return only that account.  Instead, it appears to be ignored, as all accounts are returned no matter what name I pass in.

REPRO:

1)	Sign in to multiple Azure accounts (e.g. I’m signed in to an org and MSID account)
2)	Get-AzureAccount

Id                             Type       Subscriptions                                          Tenants                                               
account1@hotmail.com          User        ...
                                          ...

account2@microsoft.com          User      ...
                                          ...

!) Problem a: Notice that there is no Name property listed in the account, so how do I find it?

3)	Try passing in a particular account’s name (I’m currently assuming it's the same as the ID, e.g. account2@microsoft.com):

Get-AzureAccount -Name 'account2@microsoft.com'

Id                             Type       Subscriptions                                          Tenants                                               
account1@hotmail.com          User        ...
                                          ...

account2@microsoft.com          User      ...
                                          ...

!) Problem b: It still gave me all accounts.  Expected: Either return only the specified account, or return null/exception if an account with that name was not found.

**Comment by matt-gibbs** [comment]
Thank you for reporting this issue.  We have a fix that should be included in the next release.
