### ISSUE TITLE
Appservices : Upgrade Appservice PS cmdlets to use Microsoft.Azure.Management.Websites 3.0   NuGet

### ISSUE THREAD

**Issue by Kotasudhakarreddy** [Azure/azure-powershell#12010]
## Description of the new feature
upgrade Appservice PS cmdlets to use latest Microsoft.Azure.Management.Websites (3.0) Nuget

**Comment by dingmeng-xue** [comment]
Could you clarify the reason that you hope to upgrade to the latest .NET CORE? (I assume "the latest .NET SDK" means dotnet core 3.1.x)

You can see the latest dotnet standard doesn't support dotnet framework. But Azure PowerShell has huge customer base who are using Windows PowerShell. 

Add @dcaro , @markcowl , @erich-wang

**Comment by dingmeng-xue** [comment]
@Kotasudhakarreddy, any update?

**Comment by Kotasudhakarreddy** [comment]
> @Kotasudhakarreddy, any update?

@dingmeng-xue - its about upgrading the  Appservice PS cmdlets to use latest Microsoft.Azure.Management.Websites (3.0) Nuget.

**Comment by dingmeng-xue** [comment]
We will visit this topic when powershell core ends support https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-7#powershell-releases-end-of-life.
