### ISSUE TITLE
Update-AzWvdApplicationGroup friendlyname not changed in client

### ISSUE THREAD

**Issue by jknowldenic** [Azure/azure-powershell#12025]
## Description
Using the Update-AzWvdApplicationGroup cmdlet to change the Friendly Name of a Desktop Application Group is not reflected in the user's client (tested Windows 64bit Remote Desktop client and the web client).

The updated friendly name DOES show up in the properties of the application group on Azure portal or when calling Get-AzWvdApplicationGroup.  It's as though the property is being set but not committed.  

## Steps to reproduce

```powershell
Update-AzWvdApplicationGroup -Name $appGroup -ResourceGroupName $resourceGroup -FriendlyName "new name"
```
View the client at https://rdweb.wvd.microsoft.com/arm/webclient/index.html and see the application group is not labelled "new name".

## Environment data

```
Name                           Value                                                                                                                                                                                                 
----                           -----                                                                                                                                                                                                 
PSVersion                      5.1.17763.1007                                                                                                                                                                                        
PSEdition                      Desktop                                                                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                               
BuildVersion                   10.0.17763.1007                                                                                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                   
SerializationVersion           1.1.0.1      
```

## Module version

```powershell
Script     0.1.0      Az.DesktopVirtualization            {Disconnect-AzWvdUserSession, Get-AzWvdApplication, Get-AzWvdApplicationGroup, Get-AzWvdDesktop...}                                                                        
```

## Azure Profile

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
@jknowldenic, could you enable debug via `$DebugPreference="Continue"` and share debug message for below scripts?
```
Get-AzWvdApplicationGroup -Name $appGroup -ResourceGroupName $resourceGroup
Update-AzWvdApplicationGroup -Name $appGroup -ResourceGroupName $resourceGroup -FriendlyName "new name"
Get-AzWvdApplicationGroup -Name $appGroup -ResourceGroupName $resourceGroup
```

**Comment by jknowldenic** [comment]
DEBUG: 12:30:14 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.
DEBUG: 12:30:14 PM - using account id '<user id>'...
DEBUG: AzureQoSEvent: CommandName - Get-AzContext; IsSuccess - True; Duration - 00:00:00.0063961;
DEBUG: Finish sending metric.
DEBUG: 12:30:14 PM - GetAzureRMContextCommand end processing.
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'Get-AzWvdApplicationGroup_Get': AzureQoSEvent: CommandName - Get-AzWvdApplicationGroup_Get; IsSuccess - False; Duration - 00:00:00;
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: https://management.azure.com/subscriptions/<subscription id>/resourceGroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationGroups/appgroup?api-version=2019-12-10-preview
DEBUG: RequestCreated: https://management.azure.com/subscriptions/<subscription id>/resourceGroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationGroups/appgroup?api-version=2019-12-10-preview
DEBUG: HeaderParametersAdded: https://management.azure.com/subscriptions/<subscription id>/resourceGroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationGroups/appgroup?api-version=2019-12-10-previe
w
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<subscription id>/resourceGroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationGroups/appgroup?api-version=2019-12-10-preview

Headers:

Body:



DEBUG: BeforeCall: 
DEBUG: [ADAL]: Information: 2020-06-01T16:30:14.9384044Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec
6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2020-06-01T16:30:14.9384044Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec
6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2020-06-01T16:30:14.9384044Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: login.microsoftonline.com
DEBUG: [ADAL]: Information: 2020-06-01T16:30:14.9384044Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/<tenant id>/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: null
	Authentication Target: User
	
DEBUG: [ADAL]: Verbose: 2020-06-01T16:30:14.9384044Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Verbose: 2020-06-01T16:30:14.9384044Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Information: 2020-06-01T16:30:14.9393593Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 3 items to token cache.
DEBUG: [ADAL]: Verbose: 2020-06-01T16:30:14.9393593Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Verbose: 2020-06-01T16:30:14.9403925Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 2020-06-01T16:30:14.9403925Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2020-06-01T16:30:14.9403925Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2020-06-01T16:30:14.9403925Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: 59.4880434583333 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2020-06-01T16:30:14.9403925Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: 59.4880434583333 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2020-06-01T16:30:14.9403925Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2020-06-01T16:30:14.9403925Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2020-06-01T16:30:14.9403925Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 6/1/2020 5:29:44 PM +00:00
DEBUG: [ADAL]: Information: 2020-06-01T16:30:14.9403925Z: 8572cf53-ec4c-4546-a88c-9900f8ac76b3 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 6/1/2020 5:29:44 PM +00:00
Access Token Hash: MS7TSgyqafmARfNzRKwjS6JsN36aLy4b026g5SI+92U=
	 User id: 993feb9b-df59-4f3c-9c29-5609c0acf8a3
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Vary                          : Accept-Encoding
x-ms-ratelimit-remaining-subscription-reads: 11984
x-ms-lamport-ts               : 144544374
x-ms-correlation-id           : 62d023e9-d7a7-4892-997c-e5da263a2f0a
x-ms-request-id               : 62d023e9-d7a7-4892-997c-e5da263a2f0a
x-ms-correlation-request-id   : 62d023e9-d7a7-4892-997c-e5da263a2f0a
x-ms-routing-request-id       : CANADACENTRAL:20200601T163015Z:62d023e9-d7a7-4892-997c-e5da263a2f0a
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Mon, 01 Jun 2020 16:30:14 GMT
Set-Cookie                    : ARRAffinity=af296e024b2484d45d8b7953ff26aa870f69ec09d432efdbd5045f5818e8f4d0;Path=/;HttpOnly;Domain=rdarmprovider-g-us-r0.wvd.microsoft.com
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET

Body:
{
  "name": "appgroup",
  "id": "/subscriptions/<subscription id>/resourcegroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationgroups/appgroup",
  "type": "Microsoft.DesktopVirtualization/applicationgroups",
  "location": "eastus",
  "tags": {},
  "kind": "Desktop",
  "properties": {
    "hostPoolArmPath": "/subscriptions/<subscription id>/resourcegroups/wvd-rg/providers/Microsoft.DesktopVirtualization/hostpools/hostpool",
    "workspaceArmPath": "/subscriptions/<subscription id>/resourcegroups/wvd-rg/providers/Microsoft.DesktopVirtualization/workspaces/workspace",
    "description": null,
    "friendlyName": null,
    "applicationGroupType": "Desktop"
  }
}


DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 

DEBUG: Finally: 
DEBUG: CmdletAfterAPICall: 
DEBUG: [CmdletProcessRecordAsyncEnd]: Sending new QosEvent for command 'Get-AzWvdApplicationGroup_Get': AzureQoSEvent: CommandName - Get-AzWvdApplicationGroup_Get; IsSuccess - True; Duration - 00:00:00;
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: CmdletEndProcessing: 
DEBUG: 12:30:15 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.
DEBUG: 12:30:15 PM - using account id '<user id>'...
DEBUG: AzureQoSEvent: CommandName - Get-AzContext; IsSuccess - True; Duration - 00:00:00.0027791;
DEBUG: Finish sending metric.
DEBUG: 12:30:15 PM - GetAzureRMContextCommand end processing.
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'Update-AzWvdApplicationGroup_UpdateExpanded': AzureQoSEvent: CommandName - Update-AzWvdApplicationGroup_UpdateExpanded; IsSuccess - False; Duration - 00:00:
00;
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: https://management.azure.com/subscriptions/<subscription id>/resourceGroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationGroups/appgroup?api-version=2019-12-10-preview
DEBUG: RequestCreated: https://management.azure.com/subscriptions/<subscription id>/resourceGroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationGroups/appgroup?api-version=2019-12-10-preview
DEBUG: HeaderParametersAdded: https://management.azure.com/subscriptions/<subscription id>/resourceGroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationGroups/appgroup?api-version=2019-12-10-previe
w
DEBUG: BodyContentSet: https://management.azure.com/subscriptions/<subscription id>/resourceGroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationGroups/appgroup?api-version=2019-12-10-preview
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com/subscriptions/<subscription id>/resourceGroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationGroups/appgroup?api-version=2019-12-10-preview

Headers:

Body:
{
  "properties": {
    "friendlyName": "new name"
  }
}


DEBUG: BeforeCall: 
DEBUG: [ADAL]: Information: 2020-06-01T16:30:16.0476783Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec
6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2020-06-01T16:30:16.0476783Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec
6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2020-06-01T16:30:16.0476783Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: login.microsoftonline.com
DEBUG: [ADAL]: Information: 2020-06-01T16:30:16.0476783Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/<tenant id>/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: null
	Authentication Target: User
	
DEBUG: [ADAL]: Verbose: 2020-06-01T16:30:16.0476783Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Verbose: 2020-06-01T16:30:16.0476783Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Information: 2020-06-01T16:30:16.0487154Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 3 items to token cache.
DEBUG: [ADAL]: Verbose: 2020-06-01T16:30:16.0497122Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Verbose: 2020-06-01T16:30:16.0497122Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 2020-06-01T16:30:16.0497122Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2020-06-01T16:30:16.0497122Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2020-06-01T16:30:16.0497122Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: 59.4695547966667 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2020-06-01T16:30:16.0497122Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: 59.4695547966667 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2020-06-01T16:30:16.0497122Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2020-06-01T16:30:16.0497122Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2020-06-01T16:30:16.0497122Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 6/1/2020 5:29:44 PM +00:00
DEBUG: [ADAL]: Information: 2020-06-01T16:30:16.0497122Z: f29ccf12-a8b8-4b26-abb2-0608b7b61fc6 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 6/1/2020 5:29:44 PM +00:00
Access Token Hash: MS7TSgyqafmARfNzRKwjS6JsN36aLy4b026g5SI+92U=
	 User id: 993feb9b-df59-4f3c-9c29-5609c0acf8a3
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Vary                          : Accept-Encoding
x-ms-ratelimit-remaining-subscription-writes: 1195
x-ms-lamport-ts               : 144544373
x-ms-correlation-id           : 9c7ffb8b-2e93-40fb-84a5-9ec3f94355f2
x-ms-request-id               : 9c7ffb8b-2e93-40fb-84a5-9ec3f94355f2
x-ms-correlation-request-id   : 9c7ffb8b-2e93-40fb-84a5-9ec3f94355f2
x-ms-routing-request-id       : CANADACENTRAL:20200601T163016Z:9c7ffb8b-2e93-40fb-84a5-9ec3f94355f2
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Mon, 01 Jun 2020 16:30:15 GMT
Set-Cookie                    : ARRAffinity=47e899d5dc0547d5646e3c2c0081ae2cb7fddd55609bf4af48732c4283928a51;Path=/;HttpOnly;Domain=rdarmprovider-g-us-r0.wvd.microsoft.com
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET

Body:
{
  "name": "appgroup",
  "id": "/subscriptions/<subscription id>/resourcegroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationgroups/appgroup",
  "type": "Microsoft.DesktopVirtualization/applicationgroups",
  "location": "eastus",
  "tags": {},
  "kind": "Desktop",
  "properties": {
    "hostPoolArmPath": "/subscriptions/<subscription id>/resourcegroups/wvd-rg/providers/Microsoft.DesktopVirtualization/hostpools/hostpool",
    "workspaceArmPath": "/subscriptions/<subscription id>/resourcegroups/wvd-rg/providers/Microsoft.DesktopVirtualization/workspaces/workspace",
    "description": null,
    "friendlyName": "new name",
    "applicationGroupType": "Desktop"
  }
}


DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 
Location Name     Type                                             
-------- ----     ----                                             
eastus   appgroup Microsoft.DesktopVirtualization/applicationgroups
eastus   appgroup Microsoft.DesktopVirtualization/applicationgroups
DEBUG: Finally: 
DEBUG: CmdletAfterAPICall: 
DEBUG: [CmdletProcessRecordAsyncEnd]: Sending new QosEvent for command 'Update-AzWvdApplicationGroup_UpdateExpanded': AzureQoSEvent: CommandName - Update-AzWvdApplicationGroup_UpdateExpanded; IsSuccess - True; Duration - 00:00:00;
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: CmdletEndProcessing: 
DEBUG: 12:30:16 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.
DEBUG: 12:30:16 PM - using account id '<user id>'...
DEBUG: AzureQoSEvent: CommandName - Get-AzContext; IsSuccess - True; Duration - 00:00:00.0028117;
DEBUG: Finish sending metric.
DEBUG: 12:30:17 PM - GetAzureRMContextCommand end processing.
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'Get-AzWvdApplicationGroup_Get': AzureQoSEvent: CommandName - Get-AzWvdApplicationGroup_Get; IsSuccess - False; Duration - 00:00:00;
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: https://management.azure.com/subscriptions/<subscription id>/resourceGroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationGroups/appgroup?api-version=2019-12-10-preview
DEBUG: RequestCreated: https://management.azure.com/subscriptions/<subscription id>/resourceGroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationGroups/appgroup?api-version=2019-12-10-preview
DEBUG: HeaderParametersAdded: https://management.azure.com/subscriptions/<subscription id>/resourceGroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationGroups/appgroup?api-version=2019-12-10-previe
w
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<subscription id>/resourceGroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationGroups/appgroup?api-version=2019-12-10-preview

Headers:

Body:



DEBUG: BeforeCall: 
DEBUG: [ADAL]: Information: 2020-06-01T16:30:17.3809957Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec
6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2020-06-01T16:30:17.3809957Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec
6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2020-06-01T16:30:17.3809957Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: login.microsoftonline.com
DEBUG: [ADAL]: Information: 2020-06-01T16:30:17.3809957Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/<tenant id>/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: null
	Authentication Target: User
	
DEBUG: [ADAL]: Verbose: 2020-06-01T16:30:17.3809957Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Verbose: 2020-06-01T16:30:17.3809957Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Information: 2020-06-01T16:30:17.3820270Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 3 items to token cache.
DEBUG: [ADAL]: Verbose: 2020-06-01T16:30:17.3820270Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Verbose: 2020-06-01T16:30:17.3820270Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 2020-06-01T16:30:17.3820270Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2020-06-01T16:30:17.3820270Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2020-06-01T16:30:17.3820270Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: 59.44734955 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2020-06-01T16:30:17.3820270Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: 59.44734955 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2020-06-01T16:30:17.3820270Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2020-06-01T16:30:17.3820270Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2020-06-01T16:30:17.3820270Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 6/1/2020 5:29:44 PM +00:00
DEBUG: [ADAL]: Information: 2020-06-01T16:30:17.3820270Z: da876a76-5824-4ebf-a7b4-117e2f2741c1 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 6/1/2020 5:29:44 PM +00:00
Access Token Hash: MS7TSgyqafmARfNzRKwjS6JsN36aLy4b026g5SI+92U=
	 User id: 993feb9b-df59-4f3c-9c29-5609c0acf8a3
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Vary                          : Accept-Encoding
x-ms-ratelimit-remaining-subscription-reads: 11983
x-ms-lamport-ts               : 144544392
x-ms-correlation-id           : d153c8ad-a296-4766-94c3-4fc4cb3458a0
x-ms-request-id               : d153c8ad-a296-4766-94c3-4fc4cb3458a0
x-ms-correlation-request-id   : d153c8ad-a296-4766-94c3-4fc4cb3458a0
x-ms-routing-request-id       : CANADACENTRAL:20200601T163017Z:d153c8ad-a296-4766-94c3-4fc4cb3458a0
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Mon, 01 Jun 2020 16:30:16 GMT
Set-Cookie                    : ARRAffinity=b42003c253a6ee92c124bdfad0b2db83fb2ef9906588018364ce2390be8fbedb;Path=/;HttpOnly;Domain=rdarmprovider-g-us-r0.wvd.microsoft.com
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET

Body:
{
  "name": "appgroup",
  "id": "/subscriptions/<subscription id>/resourcegroups/wvd-rg/providers/Microsoft.DesktopVirtualization/applicationgroups/appgroup",
  "type": "Microsoft.DesktopVirtualization/applicationgroups",
  "location": "eastus",
  "tags": {},
  "kind": "Desktop",
  "properties": {
    "hostPoolArmPath": "/subscriptions/<subscription id>/resourcegroups/wvd-rg/providers/Microsoft.DesktopVirtualization/hostpools/hostpool",
    "workspaceArmPath": "/subscriptions/<subscription id>/resourcegroups/wvd-rg/providers/Microsoft.DesktopVirtualization/workspaces/workspace",
    "description": null,
    "friendlyName": "new name",
    "applicationGroupType": "Desktop"
  }
}


DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 
eastus   appgroup Microsoft.DesktopVirtualization/applicationgroups
DEBUG: Finally: 
DEBUG: CmdletAfterAPICall: 
DEBUG: [CmdletProcessRecordAsyncEnd]: Sending new QosEvent for command 'Get-AzWvdApplicationGroup_Get': AzureQoSEvent: CommandName - Get-AzWvdApplicationGroup_Get; IsSuccess - True; Duration - 00:00:00;
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: CmdletEndProcessing:

**Comment by dingmeng-xue** [comment]
@datr93, could you help to look into this issue? It seems server already returns correct value.

**Comment by datr93** [comment]
We tried this:
Update-AzWvdApplicationGroup -Name {} -ResourceGroupName {} -FriendlyName "new name"
Get-AzWvdApplicationGroup -ResourceGroupName {} -Name {} | format-list

Works

**Comment by jknowldenic** [comment]
To be clear: the problem is with what gets displayed to the client, not the response from the server.

**Comment by datr93** [comment]
@jknowldenic oh if you want to change the friendly name for desktop app in **powershell** please using Update-AzwvdDesktop -ApplicationGroupName {} -Name {} -ResourceGroupName {} -FriendlyName "new name"

**Comment by jknowldenic** [comment]
Ah that gives the desired result, thanks!
