### ISSUE TITLE
Az Deployment Plan Whatif -ResultFormat should include JSON option

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#12031]
@shenglol
## Description of the new feature
[In AZ CLI you can get a JSON representation of the whatif with the --no-pretty-print option](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-deploy-what-if?tabs=azure-powershell#azure-cli). An equivalent in powershell is required so that custom output formats can be derived (for instance, doing WhatIfs on the ARM file as part of a pull request commit and reporting a status summary via a check similar to Atlantis for Terraform: https://www.runatlantis.io/

## Proposed implementation details (optional)
Since the Powershell output is colored Write-Host text, the typical `ConvertTo-JSon` method will not work. Instead, either an additional `-NoPrettyPrint` parameter is added, or the `ResultFormat` parameter has an additional option of `JSON`

**Comment by dingmeng-xue** [comment]
Thanks for your comments.

The output of PowerShell is object-based which is different from shell. In addition, there is a technical limitation because current Azure PowerShell bases on dotnet SDK. SDK already deserializes JSON object before cmdlet processes it. The output user have seen is just diagnosis information and it is not PowerShell output.

We are thinking to support it if cmdlet doesn't not base on SDK.

**Comment by JustinGrote** [comment]
@dingmeng-xue Reading the source code it looks like you're getting the JSON and formatting it further down the road
https://github.com/Azure/azure-powershell/blob/44d6cef0a24721571a720c745b8ac61dd9102a63/src/Resources/ResourceManager/SdkClient/ResourceManagerSdkClient.cs#L1353-L1355

Why not just have an additional ExecuteDeploymentWhatIf override that returns the raw json rather than the formatted string output?

The REST API this function calls returns it in JSON
https://docs.microsoft.com/en-us/rest/api/resources/deployments/whatif

**Comment by dingmeng-xue** [comment]
@JustinGrote , my understanding is SDK API of IResourceManagementClient cannot return json string. It already returns csharp object WhatIfOperationResult and WhatIfChange.
https://github.com/Azure/azure-sdk-for-net/blob/ddf2da6a8212a0d3adb361c5f90d433d3663791b/sdk/resources/Microsoft.Azure.Management.Resource/src/Generated/Models/WhatIfChange.cs#L47

This deserialization is handled by SDK and Azure PowerShell cannot do anything if no API.

**Comment by JustinGrote** [comment]
@dingmeng-xue You can pass it a custom HTTPClientHandler when creating the resourcemanagementclient and intercept the responses. You can add a handler that saves off the whatif responses to a variable and then return that if requested, among many other options.


https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.resourcemanagementclient?view=azure-dotnet
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler?view=netcore-3.1

**Comment by dingmeng-xue** [comment]
The suggested approach should work. I involve service team to look into this feature request. It needs to add new parameter set to return json string and avoid breaking change to other customer.

**Comment by shenglol** [comment]
Hi @JustinGrote , you can actually achieve that by piping the What-If result to ConverTo-Json:
```
Get-AzDeploymentWhatIfResult ... | ConvertTo-Json -Depth 100
```

**Comment by JustinGrote** [comment]
@shenglol did you actually test this before you recommended it and closed the issue? It doesn't work with Whatif Specifically (works fine for other commands) because Whatif just outputs to write-host, it doesn't generate an object that's convertable to json.

Please reopen this issue unless you can show me something I may be missing.

![image](https://user-images.githubusercontent.com/15258962/84458406-cc4d4f80-ac19-11ea-9820-7f19f807c815.png)

**Comment by JustinGrote** [comment]
@shenglol do you have a response?

**Comment by shenglol** [comment]
@JustinGrote If you need to programmatically interrogate the results, you would do
```
Get-Az*DeploymentWhatIfResult
```
instead of
```
New-Az*Deployment -WhatIf/-Confirm
```

The former returns a PS object so you can change the format with pipe. The latter is useful when you want to run What-If interactively and only care about text-based results.

**Comment by JustinGrote** [comment]
I get it with both. Can you show me an example *with json output* of how it works for you?

**Comment by JustinGrote** [comment]
@shenglol I did manage to finally get it to work, this can remain closed, thanks.
