### ISSUE TITLE
Please add a new example of Add-AzVMDataDisk with -ManagedDiskId

### ISSUE THREAD

**Issue by Xergy** [Azure/azure-powershell#12063]
Please add a new example to:

```https://github.com/Azure/azure-powershell/blob/master/src/Compute/Compute/help/Add-AzVMDataDisk.md```

Something that shows off -ManagedDiskId  when you add a existing non-generalized data disk to an existing VM.

Something better, but like below...

```Add-AzVMDataDisk -VM $ResultVM -Name $DataDisk.Name -ManagedDiskId $DataDisk.Id -LUN $Lun -Caching ReadWrite -DiskSizeinGB $DataDisk.DiskSizeGB -CreateOption Attach -StorageAccountType $StorageAccountType```

Thank you!

**Comment by dingmeng-xue** [comment]
Add compute team to check reference doc.

**Comment by Vaibhav-Agar** [comment]
Looking

**Comment by Vaibhav-Agar** [comment]
Checking with Xergy offline.

**Comment by Vaibhav-Agar** [comment]
Missed to follow-up here. Will be providing an update soon.

**Comment by Vaibhav-Agar** [comment]
Closing per offline conversation with @Xergy.
