### ISSUE TITLE
Get-AzADGroup needs feature to search group by name

### ISSUE THREAD

**Issue by mprabhu11** [Azure/azure-powershell#12081]
## Description of the new feature
The Get-AzADUser lets you find a user using their email name…
    E.g., Get-AzADUser -UserPrincipalName corm@microsoft.com

However, the Get-AzADGroup does not have a similar capability. Moreover, the “-SearchString” option does not search the mail nick name for the group. This basically means that just knowing the mailing-id is not sufficient to search for a group. (Searching using part of the name is possible but then one has to disambiguate as often names may contain common words across groups.)

Could this be added in a future update?

**Comment by dingmeng-xue** [comment]
Updated the title and add feature request label

**Comment by dingmeng-xue** [comment]
Hi @mprabhu11 , we have released the preview version of Az.Resources 5.0.0 https://www.powershellgallery.com/packages/Az.Resources/5.0.0-preview

Could you check whether existing parameter set can meet your requirement?
