### ISSUE TITLE
Add new value to -TimeGrain parameter of New-AzConsumptionBudget -> BillingCycle

### ISSUE THREAD

**Issue by cwbuege** [Azure/azure-powershell#12098]
## Description of the new feature
While having the options of Monthly, Quarterly, and Annual for the TimeGrain parameter of New-AzConsumptionBudget makes sense, how about adding in 'BillingCycle' as another parameter?  We monitor our billing usage on a billing cycle basis, not monthly and having these budgets follow that cycle would be exceptionally beneficial.  Since our billing cycle isn't Monthly (it's basically mid-month to mid-month), having a budget that following the billing cycle would be exceptionally helpful.  Obviously this would mean that this parameter would need to be applied to all of the Az.Billing cmdlets that utilize the 'TimeGrain' parameter.

**Comment by dingmeng-xue** [comment]
Include Consumption team to look into it.

**Comment by ramaganesan-rg** [comment]
Team is investigating.

**Comment by ramaganesan-rg** [comment]
Thank you for your feedback. We only support BillingMonthly for WD subscriptions and *ConsumptionBudget Powershell Commandlets only support EA subscriptions. 
Essentially the Powershell SDK version update is the right thing to do, assuming you have a WD subscription.
