### ISSUE TITLE
Set-AzFrontDoor Does NOT Accept Force Parameter

### ISSUE THREAD

**Issue by grayo24** [Azure/azure-powershell#12104]

**Comment by dingmeng-xue** [comment]
Thanks for reporting. I will forward this issue to service team.

**Comment by dingmeng-xue** [comment]
@jessicl-ms, please help to look into this issue

**Comment by johsun-msft** [comment]
Can you please clarify what you intend to specify with a "force" parameter? There should not be a situation when a frontdoor update needs to be forced. If you get an error while updating frontdoor, can you please provide what that error is? Also please note that if a frontdoor is currently in progress of being updated, it cannot be updated until that in-progress update is complete; there is no way to force an update on an in-update frontdoor.

**Comment by grayo24** [comment]
I am trying to run the command in non-interactive mode and was hoping that
the Force parameter would allow me to do so.

**Comment by grayo24** [comment]
@johsun-msft Any update on this?

**Comment by grayo24** [comment]
Any update on this?

**Comment by t-bzhan** [comment]
@grayo24 , all commands under Az.FrontDoor module will not prompt for confirmation unless you have specified the "-Confirm" in the command explicitly. It should not have any impact on the non-interactive mode. Let me know if you still have questions.
