### ISSUE TITLE
Remove-AzureVMImage errors when VMImage includes diskconfigset

### ISSUE THREAD

**Issue by joedoss** [Azure/azure-powershell#1213]
This behavior has been occurring for several versions, and is still present in 0.9.11:
Remove-AzureVMImage fails when the image includes a diskconfigset, with the following error:
Remove-AzureVMImage : BadRequest: This operation is not supported for image with name MyImageName.
OperationID : '8ea69bc6fe492a1bb837faecad187c64'
At Test_Azure_VMImage_Delete.ps1:33 char:5
-     Remove-AzureVMImage -ImageName $imagename -DeleteVHD
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Remove-AzureVMImage], ComputeCloudException
  - FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.DiskRepository.RemoveAzureVMImage

I posted more details about this here: 
https://social.msdn.microsoft.com/Forums/azure/en-US/fb9cb80a-d935-44a0-a515-0efe58076d34/error-with-removeazurevmimage-when-vm-image-has-datadiskconfigurations?forum=azurescripting
The images that fail to delete are created with this code:
$diskconfigset = New-AzureVMImageDiskConfigSet
$diskconfigset | Set-AzureVMImageOSDiskConfig -OS $ImageOS -HostCaching ReadWrite -OSState Generalized -MediaLink $OSURL
$diskconfigset | Set-AzureVMImageDataDiskConfig -Lun $LUN -HostCaching None -MediaLink $dataURL
Add-AzureVMImage -ImageName $imagename -diskconfig $diskconfigset -Description $ImageDescription 

Each of these images deletes successfully through the classic portal.

**Comment by singhkay** [comment]
@hyonholee Can you take a look at this?

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
