### ISSUE TITLE
could not load authentication module in Az ASR powershell

### ISSUE THREAD

**Issue by whizneel** [Azure/azure-powershell#12150]
I am getting the following error while trying the following commandlet
$vault = Operation:CreateVault -Name $vaultName -ResourceGroupName $vaultRgName -Location $vaultLocation 

error: Could not load file or assembly 'Microsoft.Azure.PowerShell.Authentication, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

powershell version : Az 3.3.0
using following command to install powershell.
Install-Module -Name Az -RequiredVersion 3.3.0 -AllowClobber

This happens on a new cloud test machine (windows VM)

**Comment by dingmeng-xue** [comment]
Hi @Whizneel, could you clarify "Operation:CreateVaul"? Which cmdlet are you using?

**Comment by dingmeng-xue** [comment]
@whizneel , is there any update?

**Comment by dingmeng-xue** [comment]
Close this issue due to duplicated with #12230
