### ISSUE TITLE
Documentation not correct for New-AzStorageAccount

### ISSUE THREAD

**Issue by BasSmuldersCZ** [Azure/azure-powershell#12189]
## Description
-Kind
The default value is StorageV2.
Default value in the table is specified as None.

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by blueww** [comment]
@BasSmuldersCZ 

In https://docs.microsoft.com/en-us/powershell/module/az.storage/new-azstorageaccount?view=azps-4.2.0, we have specify -Kind: "The default value is StorageV2."
And in the cmdlet code, the default value is Storagev2.

Not sure where you see "Default value in the table is specified as None."

**Comment by blueww** [comment]
This is already fixed in Az 4.8.0
https://docs.microsoft.com/en-us/powershell/module/az.storage/new-azstorageaccount?view=azps-4.8.0
