### ISSUE TITLE
Could not find EXAMPLES header in file Get-AzAppConfigurationStore.md

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#12199]
## Description

It has below error when validating all docs. 
Could not find EXAMPLES header in file Get-AzAppConfigurationStore.md

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
@dolauli , please help if there is issue in Get-AzAppConfigurationStore.md?

**Comment by dolauli** [comment]
Actually, there are no examples for appconfiguration now. And we will need to add them in next release.

**Comment by LucasYao93** [comment]
Update-AzAppConfigurationStore still has issue, as shown below:

PS C:/ > PSUpdate-AzAppConfigurationStore -Name appconfig-test03 -ResourceGroupName azureps-manual-test -SubscriptionId xxxxxx-xxxx-xxxxx  -Tag @{ key="value" }     
Update-AzAppConfigurationStore : Cannot process argument transformation on parameter 'Tag'. Cannot convert the"Microsoft.Azure.PowerShell.Cmdlets.AppConfiguration.Models.Api20190201Preview.ConfigurationStoreUpdateParametersTags" value of type

**Comment by LucasYao93** [comment]
The App Configuration Bug link: #12374
