### ISSUE TITLE
Az.Keyvaut - SecretManagement - Modification to Secret parameter and support for SecureStringSecret

### ISSUE THREAD

**Issue by itfranck** [Azure/azure-powershell#12190]
## The implementation of the Microsoft.Powershell.SecretManagement module helper have a SecretValue parameter that accept a secure string. 

It would be nice for the implementation to match the SecretManagementModule.

Powershell implementation of the module have 2 parameters

-SecretValue accept object (supported are) 
ByteArray
String
PSCredential
Hashtable

-SecureStringSecret accept a secure string.

```Powershell

$Vault = @{'Vault' = 'CICD-Azkeyvault' }
$credential = [System.Management.Automation.PSCredential]::new('Hello', ('World' | ConvertTo-SecureString -AsPlainText -Force)) 
[byte[]]$Arr = 1, 2, 3


# Az.KeyVault supported
Set-Secret @vault -Name 'MySuperSecret-shhh'  -Secret  ('shhhh' | ConvertTo-SecureString -AsPlainText -Force)

# Unsupported
Set-Secret @vault -Name 'MySuperSecret-shhh'  -Secret  'shhhh' # String value
Set-Secret @vault -Name 'MySuperSecret-shhh'  -Secret  @{'Hello'='World';'Foo'='Bar'} #Hashtable
Set-Secret @vault -Name 'MySuperSecret-shhh'  -Secret  $credential #  PSCredential
Set-Secret @vault -Name 'MySuperSecret-shhh'  -Secret  $Arr  #ByteArray

# Also unsupported, the -SecureStringSecret parameter, which is there if you want to ensure that only a secure string can be passed down
Set-Secret @vault -Name 'MySuperSecret-shhh'  -SecureStringSecret   ('shhhh' | ConvertTo-SecureString -AsPlainText -Force)


# List was obtained from SecretManagement Enum
[Enum]::GetNames([Microsoft.PowerShell.SecretManagement.SecretType])
```

Relevant 
Set-Secret helper support `-SecretValue` as object (but not -SecureStringSecret) [here](https://github.com/Azure/azure-powershell/blob/fb50bce9cdc7f550848d784078f9630f44909a3a/src/KeyVault/KeyVault/SecretManagementExtension/SecretManagementExtension.psm1#L43)
SetSecret Keyvault implementation `-SecretValue` is a SecureString [here](https://github.com/Azure/azure-powershell/blob/62bc7690be26d5f9095b95c2d5db104cbed99019/src/KeyVault/KeyVault/Commands/SetAzureKeyVaultSecret.cs#L78)

**Comment by dingmeng-xue** [comment]
@itfranck , thanks for suggestions. We will evaluate it.
