### ISSUE TITLE
New-AzPrivateLinkServiceConnection not able to parse multiple line input with backticks

### ISSUE THREAD

**Issue by Shanfang** [Azure/azure-powershell#12201]
If input parameters are separated into multiple lines using back-ticks. It is not able to parse the input. Sample input and err message is as follows,
```
    $groupId = @()
    $groupId += "table"
    $storageAccountId = $storageAccountIdPrefix + $index
    $privateEndpointConnection = New-AzPrivateLinkServiceConnection `
        -Name $plsConnection `
        -PrivateLinkServiceId $storageAccountId `
        -GroupId $groupId
```
The term '-GroupId' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again..

**Comment by dingmeng-xue** [comment]
Thanks for reporting. `-GroupId` has no any special. It should work like others. Your script has no issue in my environment.

```
PS C:\> $groupId = @()
PS C:\> $groupId += "table"
PS C:\> New-AzPrivateLinkServiceConnection `
>> -Name "abc" `
>> -PrivateLinkServiceId "abc" `
>> -GroupId $groupId

PrivateLinkServiceId              : abc
GroupId                           :
RequestMessage                    :
Name                              : abc
Id                                :
GroupIds                          : {table}
PrivateLinkServiceConnectionState : null
```

**Comment by dcaro** [comment]
@Shanfang the cmdlet support the `-GroupId` parameter. You may have you please let us know if you have been able to address your issue?
You may want to consider using splatting https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7

**Comment by dingmeng-xue** [comment]
Close this issue now. Please contact us if you have further issue.
