### ISSUE TITLE
example of New-AzImageBuilderCustomizerObject needs to remove Sha256Checksum parameter

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#12200]
## Description

`New-AzImageBuilderCustomizerObject’ cmdlet requires to use a Sha256 checksum however this is not possible in the case of an inline script. We need to docs as well.

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by LucasYao93** [comment]
I have removed Sha256Checksum parameter of example of New-AzImageBuilderCustomizerObject. #12203
