### ISSUE TITLE
Get/Set-AzureRmResource do not preserve casing for resource properties

### ISSUE THREAD

**Issue by seanbamsft** [Azure/azure-powershell#1221]
Azure Key Vault uses a dictionary in our permissions model and our SDK and service expects to see strings like "keys" and "secrets" as the keys in that dictionary. However, if a user uses Set-AzureRmsResource, the casing for existing entries is changed so that they are now "Keys" and "Secrets". This breaks any code that deserializes into a case-sensitive dictionary (the default in .NET).

**Comment by ravbhatnagar** [comment]
@vivsriaus - lets investigate this.

**Comment by ravbhatnagar** [comment]
We should preserve the property names specified by the user. Currently we convert to Pascal case which we should not be doing.

**Comment by ravbhatnagar** [comment]
We are changing the casing on Get. Hence if someone pipes that object to a Set, it will be broken.

**Comment by ravbhatnagar** [comment]
Fixed
