### ISSUE TITLE
login-AzureRMAccount

### ISSUE THREAD

**Issue by kannan78** [Azure/azure-powershell#12224]
## Description
When i try to login to Azure using the command "login-AzureRMAccount
It gives me the following error message:
Login-AzureRMAccount : Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
At line:1 char:1
Please assist me on this error.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. What environment are you trying this script?

**Comment by dingmeng-xue** [comment]
Hi Kannan78, is there any update?

**Comment by dingmeng-xue** [comment]
@kannan78 , I'm closing this issue now. If you get more information or need further help, please contact us.
