### ISSUE TITLE
Set-AzOperationalInsightsWorkspace misses Sku option CapacityReservation 

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#12226]
## Proposed implementation details (optional)
CapacityReservation is another new Sku value.

CapacityReservation must be set with additional property which called (int) CapacityReservationLevel Which stands for a the number of GB(in multiples of 100) you want to reserve.
SetAzureOperationalInsightsWorkspace & NewAzureOperationalInsightsWorkspace both need this Sku.

**Comment by dingmeng-xue** [comment]
This issue needs change on SDK.

**Comment by VeryEarly** [comment]
SDK ready:
https://www.nuget.org/packages/Microsoft.Azure.Management.OperationalInsights/0.23.0-preview

**Comment by LucasYao93** [comment]
@dingmeng-xue 
The Sku CapacityReservation had been added for the parameter `Sku` in `Set-AzOperationalInsightsWorkspace`
https://github.com/Azure/azure-powershell/blob/main/src/OperationalInsights/OperationalInsights/Workspaces/SetAzureOperationalInsightsWorkspaceCommand.cs#L43

The Microsoft.Azure.Management.OperationalInsights version had been upgraded to 0.24.0-preview
https://github.com/Azure/azure-powershell/blob/main/src/OperationalInsights/OperationalInsights/OperationalInsights.csproj#L14

It seems that the issue can be close.

**Comment by dingmeng-xue** [comment]
Thanks. Close it now.

**Comment by LucasYao93** [comment]
Fixed in #15099

**Comment by LucasYao93** [comment]
> Thanks. Close it now.

Fixed in #15099
