### ISSUE TITLE
New/Set-AzApiManagementLogger creates a new named value each time its invoked

### ISSUE THREAD

**Issue by kristofferpagels** [Azure/azure-powershell#12228]
Hi,

We use apimanagement, and configures it to log to appinsights using the powershell (AZ PowerShell 4.2.0) script New-AzApiManagementLogger or Set-AzApiManagementLogger where we specify the appinsightsinstrumentationkey like in the following example:
```powershell
Set-AzApiManagementLogger -Context $context -LoggerId $loggerId -InstrumentationKey $appInsightsInstrumentationKey
``` 
It works, and creates an appinsights logger in apimanagement. But, when we look at the named values a new named value with prefix *Logger-Credentials-* has appeared even though the appinsights instrumentationkey did not change. So each time we redeploy a new named value is created, which fills up the list of named values. This is just annoying, and we would like to avoid this duplication. 

Possible solutions
1. Reuse the named value and overwrite with the new appinsights instrumentation key
2. Add information about the named value used to store the appinsights instrumentation key when fetching the appinsights logger using `Get-AzApiManagementLogger`. Currently this method does not return this information. This would make it possible to manually remove obsoleted named values from appinsights logger credentials.

By the way, this issue does also occur when using AzureRM 6.13 or adding the appinsights logger manually to apimanagement, or using an ARM template, so we wasn't sure where to create this issue. So please guide us to another github repository if that is more relevant.

Regards
Kristoffer Pagels

**Comment by dingmeng-xue** [comment]
Service team, please help to look into this issue.

**Comment by twinpiloot** [comment]
I had the same issue using an ARM template, but solved it by creating the property explicitly and referring to the property in the logger template. This prevents the autocreation of a property named Logger-Credentials-*.

**Comment by mivano** [comment]
@twinpiloot how did you end up referencing the property instead? The[ API documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/service/loggers?tabs=json) is not clear on what the `credentials` should look like. I currently use this in Bicep format:

```
resource appInsightsAPIManagement 'Microsoft.ApiManagement/service/loggers@2020-06-01-preview' = {
  name: '${existingApiManagementName}/${environment}-applicationinsights'
  properties: {
    loggerType: 'applicationInsights'
    description: 'specific Application Insights instance.'
    resourceId: appInsightsId
    credentials: {
      instrumentationKey: appInsightsKey
    }
  }
}
```

However, this creates multiple named values similar to using Set-AzApiManagementLogger.

**Comment by twinpiloot** [comment]
@mivano: This works for me:

    // Add property for the instrumentation key to avoid that a new property is added for every deployment.
    // If you refer to the instrumentationKey directly, a new property with the prefix Logger-Credentials is created with every deployment.
    {
      "type": "Microsoft.ApiManagement/service/properties",
      "name": "[concat(variables('apiManagementServiceName'), '/', 'appInsightsInstrumentationKey')]",
      "apiVersion": "2019-01-01",
      "properties": {
        "displayName": "appInsightsInstrumentationKey",
        "value": "[reference(resourceId('Microsoft.Insights/components', variables('applicationInsightsName')), '2014-04-01').instrumentationKey]",
        "tags": [],
        "secret": true
      },
      "resources": [],
      "dependsOn": [
        "[resourceId('Microsoft.ApiManagement/service', variables('apiManagementServiceName'))]"
      ]
    },
    {
      "type": "Microsoft.ApiManagement/service/loggers",
      "name": "[concat(variables('apiManagementServiceName'), '/', variables('apiManagementLoggerName'))]",
      "apiVersion": "2018-06-01-preview",
      "properties": {
        "loggerType": "applicationInsights",
        "description": "Logger resources to APIM",
        "resourceId": "[resourceId('Microsoft.Insights/components', variables('applicationInsightsName'))]",
        "credentials": {
          "instrumentationKey": "{{appInsightsInstrumentationKey}}"
        },
        "isBuffered": true
      },
      "resources": [],
      "dependsOn": [
        "[resourceId('Microsoft.ApiManagement/service', variables('apiManagementServiceName'))]",
        "[resourceId('Microsoft.ApiManagement/service/properties', variables('apiManagementServiceName'), 'appInsightsInstrumentationKey')]"
      ]
    },

**Comment by mivano** [comment]
Ah the trick is to point to the already existing named value using the {{ }} reference so it wont create a new one. Thanks for the tip @twinpiloot !

**Comment by mivano** [comment]
I added it to my blogpost, so if someone is interested in the whole Bicep solution, see here: https://mindbyte.nl/2021/05/14/link-appinsights-to-api-management-using-bicep.html

**Comment by lgmorand** [comment]
@mivano you made my day <3. I don't understand why :
- it's not documented (thanks for your blog even if I had to edit some parts because logger name cannot have a "/" in my case, bicep refuses it
- if I exported the ARM template from Azure portal directly, it behaves the same way

**Comment by KranthiPakala-MSFT** [comment]
@kristofferpagels We still have not heard back from you. Just wanted to check if you are still facing the issue or need assistance on this? Please let us know if this issue can be closed

**Comment by kristofferpagels** [comment]
Hi, thanks for your reply. 
I have changed project since the creation of the issue and is currently not working with technology related to it. So its not relevant for me at the moment and can be closed.

**Comment by a8ree** [comment]
I'm having issues with deploying the Logger using Powershell

```
$AppInsight = Get-AzApplicationInsights -resourceGroupName $rgAppName -Name $appInsightsName -SubscriptionId "$hubSubscriptionId"

New-AzApiManagementLogger -Context $apimContext -InstrumentationKey $instrumentationKey -LoggerId $AppInsight.id
```

There is no resourceId parameter for Powershell and therefore I understand that I should use the LoggerId however the above results in an error 

New-AzApiManagementLogger: 
Error message: Microsoft.Azure.Management.ApiManagement.Models.ErrorResponseException: Operation returned an invalid status code 'NotFound'
   at Microsoft.Azure.Management.ApiManagement.LoggerOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String serviceName, String loggerId, LoggerContract parameters, String ifMatch, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ApiManagement.LoggerOperationsExtensions.CreateOrUpdateAsync(ILoggerOperations operations, String resourceGroupName, String serviceName, String loggerId, LoggerContract parameters, String ifMatch, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ApiManagement.LoggerOperationsExtensions.CreateOrUpdate(ILoggerOperations operations, String resourceGroupName, String serviceName, String loggerId, LoggerContract parameters, String ifMatch)    
   at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.ApiManagementClient.LoggerCreate(PsApiManagementContext context, String loggerType, String loggerId, String description, IDictionary`2 credentials, Boolean isBuffered)
   at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.NewAzureApiManagementLogger.ExecuteApiManagementCmdlet()
   at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.AzureApiManagementCmdletBase.ExecuteCmdlet()

If I set the loggerId to a simple string the deployment succeeds however it does not function correctly. The link to the application Insights workspace is not correct. For example, it does not show in the availability pane in the AI workspace.
Moreover, I can see that in APIM, the linkage is not correct. When I select the logger deployed as code it opens a panel that has the ID and an instrumentation key (that doesn't match the one provided), whereas when deployed via the portal the resource is hyperlinked to the application insights workspace. 

Can anyone help?

**Comment by jonathh21** [comment]
I am having a similar problem i believe.

Wen i run 'New-AzApiManagementLogger' supplying the app insights name and instrumention key, i get an entry in the apim app insights page - but no link.

I've compared the compared run in portal - with what is generated following the the ps1 ccommand and they are identical *with the exception* that the portal command includes, and returns a resourceid.

{
  "properties": {
    "resourceId": "/subscriptions/MY SUB GUID/resourceGroups/MY RSG/providers/microsoft.insights/components/JonsAppInsights", <<< - this line is missing when run from ps1.
    "loggerType": "applicationInsights",
    "credentials": {
      "instrumentationKey": "a GUID"
    }
  }
}

i have repeated both calls both ways.

curiously if i run Get-AzApiManagementLogger - then the returned dataset is identical no mater how i create

**Comment by jonathh21** [comment]
I guess the work around is to call this using rest api - but that feels icky.
