### ISSUE TITLE
MSI installer is stuck on Windows Server 2012 R2

### ISSUE THREAD

**Issue by RadhikaMurali** [Azure/azure-powershell#12237]
Installation on my windows 2012 R2 for the new Az-commandlets with the .msi does not work.

![image](https://user-images.githubusercontent.com/22310853/85354671-19160d80-b4d9-11ea-8041-adfd4287c6cc.png)

**Comment by dingmeng-xue** [comment]
This issue may be the same as #11542 . Is there any MSI installation log?

**Comment by dingmeng-xue** [comment]
IN addition, please execute below command as administrator
```
Dism /online /Get-FeatureInfo:NetFx3
```

**Comment by RadhikaMurali** [comment]
![image](https://user-images.githubusercontent.com/22310853/85407314-0f1ff900-b531-11ea-96ec-40f41c57cd22.png)

**Comment by RadhikaMurali** [comment]
![image](https://user-images.githubusercontent.com/22310853/85407499-48f0ff80-b531-11ea-8244-e6b7eef69384.png)

**Comment by RadhikaMurali** [comment]
@dingmeng, Attached the screen shots that you requested.
Thanks

**Comment by dingmeng-xue** [comment]
@RadhikaMurali , we suspect it is related to "Disabled with Payload Removed" state. Could you try to enable feature?
```
dism /online /enable-feature NetFX3 /norestart /All
```

**Comment by dingmeng-xue** [comment]
@RadhikaMurali , is there further update?
