### ISSUE TITLE
Get-AzResource returns wrong PrincipalId for Function App Staging Slot

### ISSUE THREAD

**Issue by WouterSlob** [Azure/azure-powershell#12232]
#12026  Description
When using Get-AzResource to get the staging slot of a Function App a resource is returned which has a wrong PrincipalId (in <resource>.Identity.PrincipalId). The returned PrincipalId is the principalId of the Function App itself and not the Function App.

For web apps with staging slots the proper principalIds are returned.
When using Get-AzWebApp and Get-AzWebAppSlot also the proper principalIds are returned.

## Steps to reproduce

Create a Function App with a staging slot and system identities.

```powershell
$rg = "resoucegroupname"
$functionApp = "functionappname"
$functionAppStagingSlot = "functionappstagingslotname"
foreach($r in (Get-AzResource -ResourceGroupName $rg -ResourceType "Microsoft.Web/sites")) { 
    Write-Host $r.ResourceName $r.Identity.PrincipalId
}
foreach($r in (Get-AzResource -ResourceGroupName $rg -ResourceType "Microsoft.Web/sites/slots")) { 
    Write-Host $r.ResourceName $r.Identity.PrincipalId
}
```

## Environment data
Windows 10 / Powershell 5.1

## Module versions
Az.Resources, version 2.1.0

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Please find a specific resource and share us debug output when executing `Get-AzResource`

**Comment by dingmeng-xue** [comment]
@WouterSlob , could you please try to find the problem resource and share us the debug message? Get-AzResource is cmdlet on all resource but result may different according resource type.

**Comment by WouterSlob** [comment]
Unable to reproduce anymore.
