### ISSUE TITLE
[Telemetry] Telemetry headers contains duplicated information when LRO

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#12231]
## Description

When executing a long running operation, every time a polling request is sent, the following telemetry headers are duplicated. It seems we have a bug in the looping.

![image](https://user-images.githubusercontent.com/11371776/85264937-11884180-b4a4-11ea-847b-a0870cf7c66b.png)

## Steps to reproduce

```powershell
# Run any long running operation, the longer the better
```

**Comment by dingmeng-xue** [comment]
which cmdlet has this problem?

**Comment by isra-fel** [comment]
I found the issue when `New-AzSapMonitor` and `Remove-AzSapMonitor` in Az.HanaOnAzure, but I doubt any long running operation has it.

**Comment by dolauli** [comment]
Fixed in autorest.powershell.
