### ISSUE TITLE
MSI cannot be installed silently

### ISSUE THREAD

**Issue by paul-sernine** [Azure/azure-powershell#1224]
Because of the EULA, the MSI cannot be deployed by msiexec silently.

Please add a property ACCEPTEULA=1 or equivalent.

Better yet, allow for a oneliner to download and install the module.

**Comment by markcowl** [comment]
@paul-sernine Note that you can now install the modules from PowerShell Gallery

**Comment by markcowl** [comment]
@paul-sernine It is installed silently when you use webpi,  what are the parameters you are p[assing to msiexec?

**Comment by markcowl** [comment]
Closing as resolved.  Please, please open a new issue if you see a recurrence
