### ISSUE TITLE
New-AzApiManagementApi -ServiceUrl parameter mandatory

### ISSUE THREAD

**Issue by MonikaReddy-MSFT** [Azure/azure-powershell#12262]
Moving this issue from docs power shell repo to Product team repo. 

From Customer - 

I'm wondering why -ServiceUrl parameter of New-AzApiManagementApi is mandatory. From Portal UI is not. I configure my APIM Services with policies and it is correctly ignored.

The path to use a more basic Az APIs (like New-AzResource) to achieve not setting it is quite impervious (if you've to deal with API versions).

See this stackoverflow (partially solved) question: https://stackoverflow.com/questions/60882705/azure-create-a-new-api-management-service-without-a-service-url.

Thanks all Microsoft teams, for great Azure Platform!

Giacomo S. S.

https://github.com/MicrosoftDocs/azure-docs-powershell/issues/1361

**Comment by markcowl** [comment]
@MonikaReddy-MSFT Thanks for the customer question, we will take a look.

**Comment by SaurabhSharma-MSFT** [comment]
@MonikaReddy-MSFT Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .
