### ISSUE TITLE
Can't force Connect-AzureRmAccount (or Connect-AzAccount) to ignore proxy

### ISSUE THREAD

**Issue by GeordieGuy** [Azure/azure-powershell#12280]
## Description

Using Connect-AzureRmAccount -MSI to log into Azure with a managed service identity fails when a proxy denies either or both of management.core.windows.net or the agent metadata service at 169.254.169.254. If I issue netsh winhttp proxy reset I can get past the management.core step, but not the metadata service. There should be a way to force the command to not use any proxy, particularly given even if a proxy doesn't deny access to the agent metadata service, it probably doesn't know how to get to it.

## Steps to reproduce

```
Login-AzureRmAccount -MSI
```

## Module versions

```powershell
5.8.2 but it's not version (or even AzureRM/Az) dependant
```

## Debug output
**********************
Windows PowerShell transcript start
Start time: 20200629161310
Username: PBS\guyg1
RunAs User: PBS\guyg1
Machine: csic97d10000000 (Microsoft Windows NT 10.0.14393.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 7976
PSVersion: 5.1.14393.2969
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14393.2969
BuildVersion: 10.0.14393.2969
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\users\guyg1\desktop\output.txt
PS C:\windows\system32> Connect-AzureRmAccount -MSI -debug
DEBUG: 4:13:16 PM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'ManagedServiceLogin'.
Confirm
Continue with this operation?
&Yes  Yes to &All  &Halt Command  &Suspend
A
Confirm
Are you sure you want to perform this action?
Performing the operation "log in" on target "ManagedService account in environment 'AzureCloud'".
&Yes  Yes to &All  &No  No to A&ll  &Suspend
A
DEBUG: 4:13:17 PM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 4:13:17 PM - No autosave setting detected in environment variable 'AzureRmContextAutoSave'.
DEBUG: 4:13:17 PM - Using Autosave scope 'CurrentUser'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
DEBUG: Checking Cache request http://169.254.169.254/metadata/identity/oauth2/token?resource=https://management.core.windows.net/&api-version=2018-02-01
DEBUG: ============================ HTTP REQUEST ============================
 
HTTP Method:
GET
 
Absolute Uri:
http://169.254.169.254/metadata/identity/oauth2/token?resource=https://management.core.windows.net/&api-version=2018-02-01
 
Headers:
Metadata                      : true
 
Body:
DEBUG: ============================ HTTP RESPONSE ============================
 
Status Code:
Forbidden
 
Headers:
Mime-Version                  : 1.0
X-Squid-Error                 : ERR_ACCESS_DENIED 0
Vary                          : Accept-Language
X-Cache                       : MISS from <sanitised>
X-Cache-Lookup                : NONE from <sanitised>
Connection                    : keep-alive
Date                          : Mon, 29 Jun 2020 06:13:17 GMT
Server                        : squid/3.5.20
Via                           : 1.1 <sanitised> (squid/3.5.20)
 
Body:
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2016 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"></style>
</head><body id=ERR_ACCESS_DENIED>
<div id="titles">
<h1>ERROR</h1>
<h2>The requested URL could not be retrieved</h2>
</div>
<hr>
 
<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a href="http://169.254.169.254/metadata/identity/oauth2/token?">http://169.254.169.254/metadata/identity/oauth2/token?</a></p>
 
<blockquote id="error">
<p><b>Access Denied.</b></p>
</blockquote>
 
<p>Access control configuration prevents your request from being allowed at this time. Please contact your service provider if you feel this is incorrect.</p>
 
<p>Your cache administrator is <a href="mailto:root?subject=CacheErrorInfo%20-%20ERR_ACCESS_DENIED&amp;body=CacheHost%3A%20SNIP%0D%0AErrPage%3A%20ERR_ACCESS_DENIED%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Mon,%2029%20Jun%202020%2006%3A13%3A17%20GMT%0D%0A%0D%0AClientIP%3A%2010.236.175.197%0D%0A%0D%0AHTTP%20Request%3A%0D%0AGET%20%2Fmetadata%2Fidentity%2Foauth2%2Ftoken%3Fresource%3Dhttps%3A%2F%2Fmanagement.core.windows.net%2F%26api-version%3D2018-02-01%20HTTP%2F1.1%0AMetadata%3A%20true%0D%0AHost%3A%20169.254.169.254%0D%0A%0D%0A%0D%0A">root</a>.</p>
<br>
</div>
 
<hr>
<div id="footer">
<p>Generated Mon, 29 Jun 2020 06:13:17 GMT by <sanitised> (squid/3.5.20)</p>

</div>
</body></html>
DEBUG: Checking Cache request http://localhost:50342/oauth2/token?resource=https://management.core.windows.net/&api-version=2018-02-01
DEBUG: ============================ HTTP REQUEST ============================
 
HTTP Method:
GET
 
Absolute Uri:
http://localhost:50342/oauth2/token?resource=https://management.core.windows.net/&api-version=2018-02-01
 
Headers:
Metadata                      : true
 
Body:
Confirm
An error occurred while sending the request.
&Yes  Yes to &All  &Halt Command  &Suspend
A
Connect-AzureRmAccount : An error occurred while sending the request.
At line:1 char:1
+ Connect-AzureRmAccount -MSI -debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzureRmAccount], HttpRequestException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
Connect-AzureRmAccount : An error occurred while sending the request.
At line:1 char:1
+ Connect-AzureRmAccount -MSI -debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzureRmAccount], HttpRequestException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
 
DEBUG: AzureQoSEvent: CommandName - Connect-AzureRmAccount; IsSuccess - False; Duration - 00:00:04.7888145; Exception - System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:50342
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientWithRetry.<SendAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.<SafeSendRequestAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.<GetAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessToken.GetOrRenewAuthentication()
   at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessToken.get_AccessToken()
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass87_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 4:13:21 PM - ConnectAzureRmAccountCommand end processing.
DEBUG: 4:13:21 PM - ConnectAzureRmAccountCommand end processing.
PS C:\windows\system32> Stop-Transcript
**********************
Windows PowerShell transcript end
End time: 20200629161324
**********************

```

```

## Error output

Stacktrace just predictably shows that the remote server wasn't contactable

```

```

**Comment by dingmeng-xue** [comment]
@GeordieGuy , thanks for reporting. What's the server of 169.254.169.254? How was proxy configured on your machine?

**Comment by GeordieGuy** [comment]
169.254.169.254 is the metadata service

**Comment by dingmeng-xue** [comment]
Hi GeordieGuy, I have no idea about metadata service. I found some pages about Azure Instance Metadata Service. Is it the same one?

**Comment by dingmeng-xue** [comment]
@GeordieGuy , is there guideline to teach me how to set up an environment to reproduce the issue?

**Comment by dingmeng-xue** [comment]
@GeordieGuy , I'm closing this issue. If you need further help, please contact on this issue or create a new one.
