### ISSUE TITLE
Start-AzStorageBlobCopy help example 4 is wrong

### ISSUE THREAD

**Issue by Panzerbjrn** [Azure/azure-powershell#12286]
## Description

Start-AzStorageBlobCopy help example 4 states:
-------- Example 4: Copy a blob specified as an object --------

    C:\PS>$SrcBlob = Get-AzStorageBlob -Container "ContosoUploads" -Blob "ContosoPlanning2015"
    C:\PS> $DestBlob = Get-AzStorageBlob -Container "ContosoArchives" -Blob "ContosoPlanning2015Archived"
    C:\PS> Start-AzStorageBlobCopy -ICloudBlob $SrcBlob.ICloudBlob -DestICloudBlob $DestBlob.ICloudBlob

Running `Get-AzStorageBlob` without `-context`, and obviously passing in a context, gives an error:
```Get-AzStorageBlob : Could not get the storage context.  Please pass in a storage context or set the current storage context.
At line:1 char:1
+ Get-AzStorageBlob -Blob "excel.csv"  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzStorageBlob], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand```

## Steps to reproduce

```powershell
Get-AzStorageBlob -Blob "Excel.csv" -Container storage
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.2.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}
Script     2.1.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}
Script     1.13.0     Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}
Script     1.8.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}
Script     1.6.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}
```

## Comments:

There's not really much else to say, this is easily reproducable as the example doesn't use the `Get-AzStorageBlob` cmdlet correctly.
Start-AzStorageBlobCopy doesn't seem to work the way examples 4 & 5 are described, but I will raise a separate issue for those after further testing.

**Comment by Panzerbjrn** [comment]
Also, in this example, when you try to do `C:\PS> $DestBlob = Get-AzStorageBlob -Container "ContosoArchives" -Blob "ContosoPlanning2015Archived"` you get the same error if you don't specify -context.
And if you do specify  context, you get an error that the Blob doesn't exist:
```
[PS5 C:\Temp]$ $DestBlob = Get-AzStorageBlob -Blob "Excel.csv" -Container $Container -Context $BlobCTX
Get-AzStorageBlob : Can not find blob 'Excel.csv' in container 'storage', or the blob type is unsupported.
At line:1 char:13
+ $DestBlob = Get-AzStorageBlob -Blob "Excel.csv ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-AzStorageBlob], ResourceNotFoundException
    + FullyQualifiedErrorId : ResourceNotFoundException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand
```
Again, this should be pretty easy to reproduce.

**Comment by blueww** [comment]
@Panzerbjrn

We have a cmdlet `Set-AzCurrentStorageAccount` which can set a default storage context. After run this cmdlet, user don't need to input context for every storage dataplane cmdlets, if target to the default context.

For example #4, generally we don't add `-Context` parameter to most storage dataplane cmdlets' examples, since: 1. you don't need add it when the default context is set with `Set-AzCurrentStorageAccount`. 2. Every storage dataplane cmdlets support this parameter, skip adding this parameter will make example shorter and make user can focus on the main  usage of each cmdlet.

If you run `Set-AzCurrentStorageAccount` first, then run the command in example #4, it will work.

**Comment by Panzerbjrn** [comment]
Thanks for this.
Then you need to add that to the example, because your example as written, does not work.

Also, you still get the error that the blob cannot be found:
```
Get-AzStorageBlob : Can not find blob 'Excel.csv' in container 'storage', or the blob type is unsupported.
At line:1 char:13
+ $DestBlob = Get-AzStorageBlob -Blob "Excel.csv" ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-AzStorageBlob], ResourceNotFoundException
    + FullyQualifiedErrorId : ResourceNotFoundException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand
```
As I put into my follow up comment above. This seems to be expected behaviour, which is why I don't understand how you expect this example to actually work.

**Comment by blueww** [comment]
@Panzerbjrn 
`Set-AzCurrentStorageAccount` generally will run in the begin of a script, but not before every dataplane cmdlet, so we don't add it to each sample of each cmdlet (like we also won't add storage context create step for each cmdlets), to avoid duplication, and make the sample more focus on the cmdlet itself.

For the error, have you run `Set-AzCurrentStorageAccount` before run `Get-AzStorageBlob`? If so, does the account has the blob 'Excel.csv' in container 'storage'? `Get-AzStorageBlob` only works when the blob already exist.

**Comment by Panzerbjrn** [comment]
No, that commandlet will generally not run in a script unless there's a reason to put it in. Such is in your example, which is why you should include it.
Otherwise your example is broken and does not work. The whole point of examples is to show how to make it work. This should not be some amazing revelation. Otherwise why even bother with examples?

No, the blob "Excel.csv" does not exist in the target container, if it did I wouldn't get that error. My point here is that if your example requires something to exist in the target, you should include that.
If you have examples, they need to work, otherwise don't include them.

**Comment by blueww** [comment]
@Panda-Wang 
Thanks for the suggestion!

1. To include "Set-AzCurrentStorageAccount" or "-context" in the example, we will consider it as a work item. If more customer think include them is better than not include them, we can consider to add them in a future release.

2. For the example #4 not work before the dest blob already exist. The example shows how to use the blob object to blob object copy. If it's misleading, we can add some description to the example like: "the destination blob must exist before run Get-AzStorageblob." we might can also change the example title to "Copy a blob specified as an object to overwrite the destination blob" to avoid misleading. How do you think? 
We don't want to include step to create the destination blob before run Get-AzStorageblob, as it will be weird to create a blob then soon overwrite it in same sample.

**Comment by amishra-dev** [comment]
Please reactivate if the issue is not resolved.
