### ISSUE TITLE
WebApp :Update-AzWebAppAccessRestrictionConfig simply not working with an InputObject

### ISSUE THREAD

**Issue by theonesuperdave** [Azure/azure-powershell#12303]
## Description
Update-AzWebAppAccessRestrictionConfig is not applying changes to my app service. After trying several variations of the script below, I an unable to see the changes applied. The script completes with no errors, and the Activity Log in the Azure portal shows nothing for these changes.

I have tried running the script from both my local Windows machine and also Azure DevOps MS-Hosted agents; same result in both places. I did have to add the `-ScmSiteUseMainSiteRestrictionConfig:$false`; otherwise, am prompted for the value at runtime. I also had to run `Add-Member` to create the required member for the posh pipeline.

It should also be noted that `Remove-AzWebAppAccessRestrictionRule` and `Add-AzWebAppAccessRestrictionRule` work just fine. I just have a lot of rules (1k+) to modify and so they are not performant for my use case.

The [docs ](https://docs.microsoft.com/en-us/powershell/module/Az.Websites/Update-AzWebAppAccessRestrictionConfig?view=azps-4.3.0)for the cmdlet are a bit ambiguous, but I'm thinking maybe the only thing applied is the `ScmSiteUseMainSiteRestrictionConfig` setting?

I really just need a way to allow `Azure DevOps` MS-Hosted agents to target my app service which is current behind a "Deny All" IP Restriction.

## Steps to reproduce

```
$accessRestrictionConfig = Get-AzWebAppAccessRestrictionConfig -ResourceGroupName $rg -Name $appName
...
# Update $accessRestrictionConfig.MainSiteAccessRestrictions
...
$accessRestrictionConfig | Add-Member -NotePropertyName "Name" -NotePropertyValue $accessRestrictionConfig.WebAppName
$accessRestrictionConfig | Update-AzWebAppAccessRestrictionConfig -ScmSiteUseMainSiteRestrictionConfig:$false

```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.3471
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3471
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
4.1.0      Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is compatib...

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.9.0      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}
```

## Debug output

```
N/A
```

## Error output

```
None
```

**Comment by dingmeng-xue** [comment]
@theonesuperdave , there is any detail error information? You can try to see the debug output after set `$DebugPreference="Continue"`

**Comment by theonesuperdave** [comment]
No error in the `DebugPreference` details. According to those details, everything was successful.

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK
```


```
DEBUG: AzureQoSEvent: CommandName - Update-AzWebAppAccessRestrictionConfig; IsSuccess - True; Duration - 00:00:01.3711415;
DEBUG: Finish sending metric.
DEBUG: 9:07:17 AM - UpdateAzureWebAppAccessRestrictionConfigCmdlet end processing.
```

**Comment by panchagnula** [comment]
@Kotasudhakarreddy can you check if the update command is not working as reported by this issue here? Thanks!

**Comment by Kotasudhakarreddy** [comment]
@theonesuperdave - I am unable to repro the issue reported. I have followed the same steps give in the description. I have tried in latest versions of `Az` and `Az.websites`. Please try with the same and let us know if you still see any issue.
 Please find below  FYR.
@panchagnula - FYI.

**-ScmSiteUseMainSiteRestrictionConfig update** 
![image](https://user-images.githubusercontent.com/60102891/87142544-4f69d000-c2c2-11ea-9875-6a55a28c4005.png)
**Versions used to repro the issue**
![image](https://user-images.githubusercontent.com/60102891/87142817-b5eeee00-c2c2-11ea-9e6f-42b2c3c0534a.png)

**Comment by theonesuperdave** [comment]
Respectfully, @Kotasudhakarreddy, that is not what I am asking. I too see the `ScmSiteUseMainSiteRestrictionConfig` value change. Rather, I am attempting to use this cmdlet to update the `MaintSiteAccessRestrictions`; that is where I see no updates and no errors. Please revise your reproduction and provide an update. Does that make sense? Apologies that my initial request was unclear.

**Comment by panchagnula** [comment]
@madsd we can use some help here - since you initially created the commands. Thank you.

**Comment by madsd** [comment]
@panchagnula @theonesuperdave @Kotasudhakarreddy  The initial design was to have Get/Update Config for the ScmSite inheritance and then Add/Remove Rule to work with rules. The commands are careful not to remove existing rules without being explicitly told to - "Remove". 

An general Update-AzWebAppAccessRestriction could be implemented, but some design decisions would be needed on the behavior - should it merge, override, throw exceptions in terms of conflicts? Right now the way to go is run multiple Add-AzWebAppAccessRestrictionRule commands; Or deploy with ARM/REST (possibly through PowerShell) to set a full rule set as one unit (overriding all existing rules)

**Comment by theonesuperdave** [comment]
Thanks for the update, @madsd . That seems to explain the behavior I have noticed. Would recommend the docs are updated to explicitly call out that only the `ScmSite` inheritance is available for now. Also, maybe throw some exception or warning of other values are set.

I am currently using ARM templates with other `Az` posh modules to set the full rule set, just fine. Adding and removing each rule set simply does not scale.

**Comment by panchagnula** [comment]
> @panchagnula @theonesuperdave @Kotasudhakarreddy The initial design was to have Get/Update Config for the ScmSite inheritance and then Add/Remove Rule to work with rules. The commands are careful not to remove existing rules without being explicitly told to - "Remove".
> 
> An general Update-AzWebAppAccessRestriction could be implemented, but some design decisions would be needed on the behavior - should it merge, override, throw exceptions in terms of conflicts? Right now the way to go is run multiple Add-AzWebAppAccessRestrictionRule commands; Or deploy with ARM/REST (possibly through PowerShell) to set a full rule set as one unit (overriding all existing rules)

@madsd thanks for the update - is this change or update on your radar? this was not something that was communicated to us earlier - is this something you were planning to take care of? is there a GitHub issue to track the work that needs to be done? since I am thinking this is something we need to do this for both CLI & PS?

**Comment by madsd** [comment]
> > @panchagnula @theonesuperdave @Kotasudhakarreddy The initial design was to have Get/Update Config for the ScmSite inheritance and then Add/Remove Rule to work with rules. The commands are careful not to remove existing rules without being explicitly told to - "Remove".
> > An general Update-AzWebAppAccessRestriction could be implemented, but some design decisions would be needed on the behavior - should it merge, override, throw exceptions in terms of conflicts? Right now the way to go is run multiple Add-AzWebAppAccessRestrictionRule commands; Or deploy with ARM/REST (possibly through PowerShell) to set a full rule set as one unit (overriding all existing rules)
> 
> @madsd thanks for the update - is this change or update on your radar? this was not something that was communicated to us earlier - is this something you were planning to take care of? is there a GitHub issue to track the work that needs to be done? since I am thinking this is something we need to do this for both CLI & PS?

@panchagnula did not plan to. I do not have enough usage statistics to validate if this is a common request. I would consider it an edge case and we would also need some input/validation of the "right" behavior of the command. However, I agree with Dave that docs should be updated to call out the scmsite only support. Kota or I can do that on next revision of the commands. CLI docs already call this out.

**Comment by davehcdn** [comment]
Geesus.  I was trying to do exactly the same thing - take the list of weekly Azure DevOps IP addresses and implement the access restrictions in my SCM sites.  I struggled with this for a few hours before concluding it must be a bug.

This is so upsetting that the commandlet doesn't do what it says

**Comment by davehcdn** [comment]
> Thanks for the update, @madsd . That seems to explain the behavior I have noticed. Would recommend the docs are updated to explicitly call out that only the `ScmSite` inheritance is available for now. Also, maybe throw some exception or warning of other values are set.
> 
> I am currently using ARM templates with other `Az` posh modules to set the full rule set, just fine. Adding and removing each rule set simply does not scale.

@theonesuperdave Do you have examples of how you are using ARM template to do this?
