### ISSUE TITLE
New-AzCosmosDBAccount is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by andrzpg12** [Azure/azure-powershell#12341]
## Description

I'd install the Az module version 4.3 using this doc: https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-4.3.0

Try to run New-AzCosmosDBAccount and get this error. Is there an AZ module missing? Is not able to create cosmosDB with version 4.3.0

## Steps to reproduce

```powershell

```

## Environment data

```
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------                          
7      0      2                      


```

## Module versions

```powershell
Get-InstalledModule -Name Az -AllVersions | Select-Object -Property Name, Version

Name Version
---- -------
Az   4.3.0
Az   3.6.1

```

## Debug output

```

```

## Error output

```

Line |
  65 |  New-AzCosmosDBAccount -ApiKind "MongoDB" `
     |  ~~~~~~~~~~~~~~~~~~~~~
     | The term 'New-AzCosmosDBAccount' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
     | included, verify that the path is correct and try again.

```

**Comment by dingmeng-xue** [comment]
@andrzpg12 , One possible reason is due to Az.CosmosDB is not installed on your machine because it is still preview release. You need to install it with command `Install-Module -Name Az.CosmosDB`.

**Comment by andrzpg12** [comment]
Thanks, that worked for me but i wasn't aware that particular module should be installed apart from the main.
Please close the issue

**Comment by dingmeng-xue** [comment]
thanks for suggestion. We plan to add preview message on preference doc. such as https://docs.microsoft.com/en-us/powershell/module/az.databricks/?view=azps-4.3.0#databricks. Hope it will reduce confusion in the future. Close this issue now.

**Comment by dgard1981** [comment]
Just to say that 2 months on this is still an issue. There is no mention of in the documentation for the `New-AzCosmosDBAccountKey` cmdlet or the `Az.CosmosDb` module that any part of it is still in preview, and the error message makes no mention of this fact either.

It would be great if either -
- The `Az.CosmosDb` module is installed when you install the `Az` module (along with all the other `Az.*` modules), or;
- The documentation notes that users must install the `Az.CosmosDb` module manually.

**Comment by bojingo** [comment]
Still the case several more months later. This page should really inform us that we need to install the module separately, until it gets baked into the main `Az` module. https://docs.microsoft.com/en-us/powershell/module/az.cosmosdb/?view=azps-5.3.0#cosmos-db

**Comment by jtucker** [comment]
I ran into this today as we have been on `4.8.0` for awhile. According to the [release notes for `5.4.0`](https://github.com/Azure/azure-powershell/blob/v5.4.0-January2021/ChangeLog.md#azcosmosdb) the CosmosDB cmdlets are now GA.
