### ISSUE TITLE
Get-AzAutomationConnection does not populate the FieldDefinitionValues

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#12353]
## Description

When fetching automation connections, `AzureRM` would return FieldDefinitionValues that included the ApplicationId, TenantId, etc. but `Az` does not.

## Steps to reproduce

```powershell
Get-AzAutomationConnection -ResourceGroupName -AutomationAccountName
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.9.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Conn...
Script     1.3.6      Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAutomationD...

```

## Debug output

```
Body:
{
  "value": [
    {
      "id":
"/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Automation/automationAccou
nts/XXX/connections/AzureRunAsConnection",
      "name": "AzureRunAsConnection",
      "type": "Microsoft.Automation/AutomationAccounts/Connections",
      "properties": {
        "creationTime": "2020-07-06T14:18:19.1133333-07:00",
        "lastModifiedTime": "2020-07-06T14:18:19.1133333-07:00",
        "description": null,
        "fieldDefinitionValues": null,
        "connectionType": {
          "name": "AzureServicePrincipal"
        }
      }
    }
  ]
}
```

**FieldDefinitionValues is not expected to be null**

## Error output

```

```

**Comment by dingmeng-xue** [comment]
Service team, please help to look into it.

**Comment by vikram-m** [comment]
Product team is aware of this issue, and unfortunately because of other priorities were not able to pick this up. Please expect an update in Q4CY20.

**Comment by jaspkaur28** [comment]
[Update] : We got this triaged. To Get  FieldDefinitionValues , use the command as below :
Get-AzureRmAutomationConnection -Name <connectionname> -resourcegroupname <resourcegroupname> -automationaccountname <AAname>. The same syntax would work for Az cmdlet also. 
Get-AzAutomationConnection -Name <connectionname> -resourcegroupname <resourcegroupname> -automationaccountname <AAname>

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.
