### ISSUE TITLE
Azure function powershell error nodejs version

### ISSUE THREAD

**Issue by andrzpg12** [Azure/azure-powershell#12361]
## Description
This is not an issue, cause i couldn't find any related blog or issue ticket, etc to find the cause of this. Is a question.

I'v create a resourceGroup, app service plan, app insights, storage account, all with az modules but when i try to create a nodejs function i got this error.

     | Node.js version 12 in Functions version 2 for Windows is not supported. For supported languages, please visit
     | 'https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#languages'.

I check that document but is not clear which nodejs versions in windows app service and function runtime version can support.

this is the powershell cmdlet that i ran:

New-AzFunctionApp -Name "sample-stack-az" `
>>                   -ResourceGroupName "my-stack" `
>>                   -StorageAccountName "storagebucketapp" `
>>                   -Location "East US" `
>>                   -Runtime "Node.js" `
>>                   -RuntimeVersion "12" `
>>                   -OsType "Windows" `
>>                   -FunctionsVersion "2" `
>>                   -ApplicationInsightsName "FunctionInsights" `
>>                   -Tag @{project="sdk";env="dev"}

PS version: 4.3.0

Any ideas?

**Comment by dingmeng-xue** [comment]
Functions team, please help to look into this issue.

**Comment by Francisco-Gamino** [comment]
Hello @andrzpg12,

Apologies for the late reply. When you create the function app, you can use the tab completer to see what `-Runtime` are supported. 

For example:

`New-AzFunctionApp -Runtime <tab>`  -- this will show you all your runtime options for a function app, in this case: `DotNet`, `Node`, `Java`, etc. 

For your case, you just need to select `Node` for the `-Runtime` parameter.  

Please ping me directly is you are still not able to create your function app.

**Comment by Francisco-Gamino** [comment]
As per my comment above, JavaScript function apps are available under the the option `-Runtime Node`. Closing issue. 

cc: @stefanushinardi @anirudhgarg
