### ISSUE TITLE
[AKS] Insufficient privileges using VM MSI with "Contributor" 

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-powershell#12378]
## Description

The environment given to the participants is comprised of a VM in which MSI has been granted the “Contributor” role onto the lab resource group. In this configuration, even providing a service principal with the owner permissions, the creation of a cluster fails with insufficient privileges.

**Comment by erich-wang** [comment]
Need to investigate whether it is expected behavior if MSI is with "Contributor" permission.

**Comment by wyunchi-ms** [comment]
Need to verify whether ther service principal is respected in `New-AzAksCluster`.
