### ISSUE TITLE
[AKS] Align with CLI how to handle service principal

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-powershell#12382]
## Description of the new feature
Several participants faced an error like the following about invalid service principal (from a quick investigation, it seems to happen if the cmdlet was executed and failed before)

	During New-AzAks, SP is created if there’s no existing one, we should delete this SP we just created and clear it from file cache if New-AzAks fails.
	We’d better to check how Azure CLI handle SP.

**Comment by wyunchi-ms** [comment]
Cli will keep the sp there. We can close this issue now.
