### ISSUE TITLE
ARM: Start-AzureApplicationGateway returns an error with confusing infromation

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-powershell#1238]
The error information does not help debug and it is confusing since it shows `Start-AzureApplicationGateway : OK`.

```
PS C:\windows\system32> Start-AzureApplicationGateway -ApplicationGateway $getgw
Start-AzureApplicationGateway : OK
At line:1 char:1
+ Start-AzureApplicationGateway -ApplicationGateway $getgw
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Start-AzureApplicationGateway], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.StartAzureApplicationGatewayCommand
```

**Comment by lordldx** [comment]
Is there any feedback on this yet? I'm having the exact same issue today

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
