### ISSUE TITLE
Get-AzureRmDataFactoryV2Pipeline : Unable to deserialize the response.

### ISSUE THREAD

**Issue by Ashish-Jovial** [Azure/azure-powershell#12387]
Hi Team,

I am deleting Azure Data Factory Pipelines using PowerShell in Azure Code deployment (Release) pipelines, I am getting error.

` Unable to deserialize the response.`

After getting this error, I run the same script from my local system and it gave
![tempsnip](https://user-images.githubusercontent.com/5494030/87298501-f00cf980-c527-11ea-8fdb-8fcbc0a43324.png)
 the same error with more details.

`Get-AzureRmDataFactoryV2Pipeline : Unable to deserialize the response.
[ERROR] At C:\Users\ashishjain06\source\repos\MyProject\MyProject
[ERROR] \DataFactory\PowerShell\Delete-ADFPipelines.ps1:38 char:20
[ERROR] + ... lineNames = Get-AzureRmDataFactoryV2Pipeline -DataFactoryName $dataFa ...
[ERROR] +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]     + CategoryInfo          : CloseError: (:) [Get-AzureRmDataFactoryV2Pipelin 
[ERROR]    e], SerializationException
[ERROR]     + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataFactoryV2.GetAzureD 
[ERROR]    ataFactoryPipelineCommand`

**Comment by Ashish-Jovial** [comment]
There is an update. I have two resource groups. And I have run the same command for my other resource group it is working fine. I have run following command.

`$pipelineNames = Get-AzureRmDataFactoryV2Pipeline -DataFactoryName $dataFactoryName -ResourceGroupName $resourceGroupName

**Comment by ghowlett2020** [comment]
+1 Am also experiencing this, we have multiple DataFactory deployments and this only happening to one of them.

**Comment by dingmeng-xue** [comment]
Data Factory team, please help to look into this issue.

**Comment by ghowlett2020** [comment]
I updated to Az 4.4.0 with Az.DataFactory 1.9.0 and still experiencing the same.

**Comment by lmy269** [comment]
@shawnxzq

**Comment by Ashish-Jovial** [comment]
I have found an alternate solution, and it is working fine for me.

`param(
	$tenantID,
	$appId,
	$clientSecrets,
	$subscriptionId,
	$resourceGroupName,
	$factoryName,
	$apiVersion,
	$location
)

$AuthContext = [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext]"https://login.microsoftonline.com/${tenantId}"
$cred = New-Object -TypeName Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential -ArgumentList ($appId, $clientSecrets)
$result = $AuthContext.AcquireTokenAsync("https://management.core.windows.net/", $cred).GetAwaiter().GetResult()
$authHeader = @{
'Authorization'=$result.CreateAuthorizationHeader()
}
         
$request = "https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$resourceGroupName/providers/Microsoft.DataFactory/factories/$factoryName/pipelines?api-version=$apiVersion"
$body = @"
{
    "name": "$dataFactoryName",
    "location": "$location",
    "properties": {},
    "identity": {
        "type": "SystemAssigned"
    }
}
"@
$response = Invoke-RestMethod -Method GET -Uri $request -Header $authHeader
$response | ConvertTo-Json`

**Comment by shawnxzq** [comment]
@Ashish-Jovial This usually happen if your Az module is not in the latest version or the pipeline definition uses a feature that's not supported in SDK & PS. If you want to figure out the details, please share with us your support file with pipeline which has the errors, then we can further investigate, thanks!

**Comment by ghowlett2020** [comment]
Is there a list of features that are in ADF which are not yet supported by PS/SDK?

I don't feel we doing anything unusual in our ADF and we have exactly the same issue. I'm also happy to share our ARM deployment template for ADF if this will help you investigate?

Maybe the command can still parse and give what is supported rather than just fail, this would be a much better situation and probably good for 95% of use cases.

Thoughts?

Thanks, Gary

**Comment by Ashish-Jovial** [comment]
**Why this ticket has been closed?** In addition, I am not using the Az module at all, I am using the AzureRm module only. @shawnxzq Can you please give me bit more idea whatever you suggested to do?

**Comment by Ashish-Jovial** [comment]
I am using Azure PowerShell Version 3.0. I am not using latest version of this task because latest task does not support the AzureRm module.

**Comment by Ashish-Jovial** [comment]
Hi @shawnxzq 

Can you please give me the link or mail id where I can share the details that you requested?

**Comment by Ashish-Jovial** [comment]
> @Ashish-Jovial This usually happen if your Az module is not in the latest version or the pipeline definition uses a feature that's not supported in SDK & PS. If you want to figure out the details, please share with us your support file with pipeline which has the errors, then we can further investigate, thanks!

Hi @shawnxzq 

I am pasting yaml code for this task.

`#Your build pipeline references an undefined variable named ‘resourceGroupName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references an undefined variable named ‘resourceGroupLocation’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references an undefined variable named ‘DataFactoryName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references an undefined variable named ‘servicePrincipalKey’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references an undefined variable named ‘servicePrincipalID’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references an undefined variable named ‘tenantID’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references an undefined variable named ‘subscriptionID’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references an undefined variable named ‘resourceGroupName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972



steps:

- task: AzureResourceGroupDeployment@2

  displayName: 'Deploy Linked Service Template'

  inputs:

    azureSubscription: 'MyProject - Subscription (7387dxxx-99u2-7k73-l88h-8ruie89e5eiB)'

    resourceGroupName: '$(resourceGroupName)'

    location: '$(resourceGroupLocation)'

    csmFile: '$(System.DefaultWorkingDirectory)/_MyCode-CI/MyCode/DataFactory/linkedServiceARMTemplates/MyCode/LinkedService_arm_template.json'

    csmParametersFile: '$(System.DefaultWorkingDirectory)/_MyCode-CI/MyCode/DataFactory/linkedServiceARMTemplates/MyCode/LinkedService_arm_parameters.json'

    overrideParameters: '-factoryName "$(DataFactoryName)" -servicePrincipalKey "$(servicePrincipalKey)" -servicePrincipalId "$(servicePrincipalID)" -tenantID "$(tenantID)" -subscriptionId "$(subscriptionID)" -resourceGroupName "$(resourceGroupName)"'
`

**Comment by Ashish-Jovial** [comment]
Hi @shawnxzq ,

I have tested command in my local PowerShell, it is giving the same error.
![image](https://user-images.githubusercontent.com/5494030/88633247-59693c80-d0d2-11ea-9240-7eb2c7e1dd74.png)
