### ISSUE TITLE
Az module should include Az.CosmosDB module

### ISSUE THREAD

**Issue by lszomoru** [Azure/azure-powershell#12394]
## Description of the new feature
Installing `Az` should also install `Az.CosmosDB` so that it does not need to be installed separately.

**Comment by dingmeng-xue** [comment]
@lszomoru, az module only includes released modules which version is equal or greater than 1.0.0. Once cosmos module is GAed, it will be included in Az and installed on CloudShell by default.

**Comment by Rabbit994** [comment]
I was going to leave a similar issue about Az.PostgreSQL. Could this made clear in documentation because it's confusing to see modules in documentation but then when you go New-AzPostGreSQLServer and it bombs, you are wondering what you did wrong.

**Comment by lszomoru** [comment]
Thanks @dingmeng-xue. Is there an ETA for the cosmos module going GA?

**Comment by dingmeng-xue** [comment]
I have included cosmos team in this issue. It will be answered by them.

For PostgreSQL, we will improve it recently. Then, we will determine if it is ready for GA. @dcaro , FYI.

**Comment by dcaro** [comment]
@Rabbit994 this is a very good point. We have plans to address this problem.

**Comment by shurd** [comment]
@MehaKaushik can help answer this question

**Comment by MehaKaushik** [comment]
We have not come up with a date yet, but we do plan for some time this year. Would update here, once we have a fixed date.

**Comment by MehaKaushik** [comment]
AZ Module 5.4.0 onwards, CosmosDB is included in Az
