### ISSUE TITLE
Unable to install azure module in windows powershell

### ISSUE THREAD

**Issue by Sathya1504** [Azure/azure-powershell#12418]
though changed the network TLS to 1.2 using [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12 , i couldnt install the az.accounts package...

PS C:\Windows\system32> install-module az -requiredversion 4.3.0

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
PackageManagement\Install-Package : Package 'Az.Accounts' failed to be installed because: End of Central Directory
record could not be found.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (Az.Accounts:String) [Install-Package], Exception
    + FullyQualifiedErrorId : Package '{0}' failed to be installed because: {1},Microsoft.PowerShell.PackageManagement
   .Cmdlets.InstallPackage

**Comment by dingmeng-xue** [comment]
Hi @Sathya1504 , please upgrade PowerShellGet and try again. I believe 1.0.0.1 is very old.

**Comment by dingmeng-xue** [comment]
Close this issue due to inactivity. The version of PowerShellGet should be the root cause.
