### ISSUE TITLE
Get-AzComputeResourceSku get physical core count

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#12432]
This is a feature request to be able to programmatically get the Physical Core count Azure Dedicated Hosts.  For example: The ESv3-Type1 dedicated host SKU

User get the following output but they would still like a way to output the physical core count.

```
(Get-AzComputeResourceSku | ?{$_.ResourceType -eq 'hostGroups/hosts' -and $_.Locations -eq 'westus' -and $_.Name -match 'esv3-type1'}).Capabilities

Name         Value
----         -----
vCPUs        64v
CPUsPerCore 2
```

One feedback request is
https://feedback.azure.com/forums/34192--general-feedback/suggestions/40766350-make-dedicated-host-physical-cpu-counts-available

**Comment by dingmeng-xue** [comment]
Compute team, this is one customer feature request. Please help to evaluate it.

**Comment by Drewm3** [comment]
Hi @dingmeng-xue, let us investigate if this property can be added to the capabilities list for each dedicated host SKU.

**Comment by Drewm3** [comment]
This capability has been added to the SKUs API response under the value of Cores
