### ISSUE TITLE
Uninstall failed with pwsh 7.03 on Mac

### ISSUE THREAD

**Issue by sorrigit** [Azure/azure-powershell#12441]
```
Get-Module -listavailable

...

    Directory: /usr/local/microsoft/powershell/7-lts/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     0.13.2                AzureRM.Netcore                     Core      Uninstall-AzureRMNetcore


$ Uninstall-AzureRMNetcore
Uninstall-Package: /Users/svensohrweide/.local/share/powershell/Modules/PowerShellGet/2.2.3/PSModule.psm1:12657                                                                                          Line 
| 12657 
|  …        $null = PackageManagement\Uninstall-Package @PSBoundParameters                                                                                                                              |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                              | No match was found for the specified search criteria and module names 'AzureRM.Netcore'.
```

**Comment by dingmeng-xue** [comment]
@sorrigit , thanks for reporting. I just tried cmdlet on below environment. The cmdlet is executed successfully. Please start a new powershell process and execute Uninstall-AzureRMNetcore. Then share your module list via `Get-Module`. 
```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xn…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by sorrigit** [comment]
Thx, dinging-xuem but same result on  pwsh 7.03 ;-(

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0 

Get-Module AzureRM.Netcore | Select-Object *
LogPipelineExecutionDetails : False
Name                        : AzureRM.Netcore
Path                        : /usr/local/microsoft/powershell/7-lts/Modules/AzureRM.Netcore/AzureRM.Netcore.psm1
ImplementingAssembly        : 
Definition                  : Write-Warning "AzureRM.Netcore has been deprecated.  Use the 'Az' module instead.  The 'Az' modul
                              e is avalable from the PSGallery https://www.powershellgallery.com/packages/Az/. You can find inf
                              ormation about getting started with 'Az' at https://docs.microsoft.com/en-us/powershell/azure/new
                              -azureps-module-az. To uninstall AzureRM.Netcore you can use the provided 'Uninstall-AzureRMNetco
                              re' cmdlet."
                              
                              function Uninstall-AzureRMNetcore {
                                  [CmdletBinding(SupportsShouldProcess=$true)]
                                  param()
                                  begin {}
                                  process{ 
                                      $allModules = (Get-Module -ListAvailable)
                                      $clientModules = ($allModules | Where-Object {$_.Name -like "Azure*.*.NetCore"})
                                      $rollupModules = ($allModules | Where-Object {$_.Name -eq "AzureRM.Netcore"} | Sort-Objec
                              t -Property Version)
                                      $totalCount = $clientModules.Count + $rollupModules.Count
                                      $count = 0
                                      foreach( $module in ($clientModules + $rollupModules)) {
                                         if ($PSCmdlet.ShouldProcess( $module.Name + " Version " + $module.Version, "Uninstall 
                              module")) {
                                             $count = $count + 1
                                             Write-Progress -Activity 'Removing AzureRM.Netcore modules' `
                                               -Status ("Removing " + $module.Name + " version " + $module.Version) `
                                               -PercentComplete ($count / $totalCount * 100)
                                             $module | Uninstall-Module -Force -ErrorAction Stop | Out-Null
                                             Write-Verbose ("Removed module " + $module.Name)
                                         }
                                      }
                                  }
                                  end {}
                              }
Description                 : [DEPRECATED] Use Az (https://www.powershellgallery.com/packages/Az/) Instead of AzureRM.Netcore
Guid                        : d48d710e-85cb-46a1-990f-22dae76f6b5f
HelpInfoUri                 : 
ModuleBase                  : /usr/local/microsoft/powershell/7-lts/Modules/AzureRM.Netcore
PrivateData                 : {PSData}
ExperimentalFeatures        : {}
Tags                        : {}
ProjectUri                  : https://github.com/Azure/azure-powershell
IconUri                     : 
LicenseUri                  : https://aka.ms/azps-license
ReleaseNotes                : [DEPRECATED]: The Az module replaces AzureRM.NetCore, see [https://www.powershellgallery.com/pack
                              ages/Az/], [https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az]
RepositorySourceLocation    : 
Version                     : 0.13.2
ModuleType                  : Script
Author                      : Microsoft Corporation
AccessMode                  : ReadWrite
ClrVersion                  : 
CompanyName                 : Microsoft Corporation
Copyright                   : Microsoft Corporation. All rights reserved.
DotNetFrameworkVersion      : 
ExportedFunctions           : {[Uninstall-AzureRMNetcore, Uninstall-AzureRMNetcore]}
Prefix                      : 
ExportedCmdlets             : {}
ExportedCommands            : {[Uninstall-AzureRMNetcore, Uninstall-AzureRMNetcore]}
FileList                    : {}
CompatiblePSEditions        : {Core}
ModuleList                  : {}
NestedModules               : {PackageManagement}
PowerShellHostName          : 
PowerShellHostVersion       : 
PowerShellVersion           : 5.1
ProcessorArchitecture       : None
Scripts                     : {}
RequiredAssemblies          : {}
RequiredModules             : {}
RootModule                  : AzureRM.Netcore.psm1
ExportedVariables           : {}
ExportedAliases             : {}
ExportedDscResources        : {}
SessionState                : System.Management.Automation.SessionState
OnRemove                    : 
ExportedFormatFiles         : {}
ExportedTypeFiles           : {}

**Comment by dingmeng-xue** [comment]
`Get-Module` without any parameter can show all loaded modules. So, I need to know if other loaded modules impact to this cmdlet.

**Comment by sorrigit** [comment]
Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.13.2                AzureRM.Netcore                     Uninstall-AzureRMNetcore
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProper…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     1.4.6                 PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pac…
Script     2.2.3                 PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCa…
Script     2.0.2                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-P…

**Comment by dingmeng-xue** [comment]
@sorrigit , I can see 2 different. Please upgrade PowerShellGet to 2.2.4.1 and PackageManagement to 1.4.7. I suspect it is due to version of PowerShellGet, because error comes from that module according to your message.

**Comment by sorrigit** [comment]
thx again for all your support, still an issue: 

Uninstall-AzureRMNetcore
WARNING: AzureRM.Netcore has been deprecated.  Use the 'Az' module instead.  The 'Az' module is avalable from the PSGallery https://www.powershellgallery.com/packages/Az/. You can find information about getting started with 'Az' at https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az. To uninstall AzureRM.Netcore you can use the provided 'Uninstall-AzureRMNetcore' cmdlet.
Uninstall-Package: /usr/local/microsoft/powershell/7-lts/Modules/PowerShellGet/PSModule.psm1:12731                               Line |                                                                                                                         12731 |  …        $null = PackageManagement\Uninstall-Package @PSBoundParameters                                                      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                      | No match was found for the specified search criteria and module names 'AzureRM.Netcore'.                                

PS /Users/svensohrweide> Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.13.2                AzureRM.Netcore                     Uninstall-AzureRMNetcore
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProper…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     1.4.7                 PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pac…
Script     2.2.4.1               PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCa…
Script     2.0.2                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-P…

**Comment by dingmeng-xue** [comment]
Sorry @sorrigit , that I have totally no idea about the root cause. As a workaround, you can navigate to /usr/local/microsoft/powershell/7-lts/Modules/ (I see that path in your log) and delete AzureRM.Netcore directly. If you need to execute it in automation environment, we may need to go into PowerShellGet module and ask PowerShell team's help.

**Comment by sorrigit** [comment]
Thx for your support, dingmeng-xue, removing the module directory manually with sudo seems to be the only help. So far it seemed to work.
