### ISSUE TITLE
unable to install AzTable in docker image mcr.microsoft.com/azure-powershell

### ISSUE THREAD

**Issue by abirax** [Azure/azure-powershell#12481]
## Description
I am trying install AZTable on top of base image mcr.microsoft.com/azure-powershell I keep getting below error 
Please note I noticed that even on running command to set trusted installation policy it is not taking into affect

WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
Install-Package: /opt/microsoft/powershell/7/Modules/PowerShellGet/PSModule.psm1:9709
Line |
9709 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No match was found for the specified search criteria and
     | module name 'AzTable'. Try Get-PSRepository to see all
     | available registered module repositories.

## Steps to reproduce

```powershell
FROM mcr.microsoft.com/azure-powershell:latest AS base

WORKDIR /app

COPY . .
RUN ls -a
Run pwsh -c "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12"
Run pwsh -c "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted"
RUN pwsh -c "Install-Module AzTable -AllowClobber"
RUN pwsh -c "Get-PSRepository"
RUN pwsh -c "Get-Module -ListAvailable Az*"
ENTRYPOINT ["pwsh", "QA-MESafety-ScaleDown.ps1"]
```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
@abirax , it seems your code is correct. Please delete mcr.microsoft.com/azure-powershell:latest  and try again. In addition, please check if your docker environment is correct.

```
PS C:\Dev> docker build dockertest
Sending build context to Docker daemon  2.048kB
Step 1/10 : FROM mcr.microsoft.com/azure-powershell:latest AS base
latest: Pulling from azure-powershell
Digest: sha256:424dd9a344e19861128dae1509597220e621e53160d95ee1a401fb258fab9755
Status: Downloaded newer image for mcr.microsoft.com/azure-powershell:latest
 ---> 1211ffce20dd
Step 2/10 : WORKDIR /app
 ---> Running in 305b43a84fe4
Removing intermediate container 305b43a84fe4
 ---> 5d021c58eda1
Step 3/10 : COPY . .
 ---> e4a64d5b5510
Step 4/10 : RUN ls -a
 ---> Running in aca5b58b6a16
.
..
Dockerfile
Removing intermediate container aca5b58b6a16
 ---> 9261f05c0e68
Step 5/10 : Run pwsh -c "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12"
 ---> Running in 4bf1754fa783
Removing intermediate container 4bf1754fa783
 ---> 8a6adaeaeecf
Step 6/10 : Run pwsh -c "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted"
 ---> Running in 684fb6983ce4
Removing intermediate container 684fb6983ce4
 ---> 2b8dc8e44a52
Step 7/10 : RUN pwsh -c "Install-Module AzTable -AllowClobber"
 ---> Running in 3be953d5974e
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Installing package 'AzTable'                                                       Downloaded 0.00 MB out of 0.01 MB.                                              [                                                                    ]                                                                                                                                                                       Installing package 'AzTable'                                                       Unzipping                                                                       [ooooooooooooooooooooooooooooooooooooooooooooooo                     ]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Removing intermediate container 3be953d5974e
 ---> 9a93ce05aad2
Step 8/10 : RUN pwsh -c "Get-PSRepository"
 ---> Running in d002ca1da187

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Trusted              https://www.powershellgallery.c…

Removing intermediate container d002ca1da187
 ---> 0f7483e984ea
Step 9/10 : RUN pwsh -c "Get-Module -ListAvailable Az*"
 ---> Running in 7e7ce5f62b12


    Directory: /root/.local/share/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Script     4.4.0                 Az                                  Core,Desk
Script     1.9.1                 Az.Accounts                         Core,Desk
Script     1.1.1                 Az.Advisor                          Core,Desk
Script     1.1.3                 Az.Aks                              Core,Desk
Script     1.1.4                 Az.AnalysisServices                 Core,Desk
Script     2.0.1                 Az.ApiManagement                    Core,Desk
Script     1.1.0                 Az.ApplicationInsights              Core,Desk
Script     1.3.7                 Az.Automation                       Core,Desk
Script     3.1.0                 Az.Batch                            Core,Desk
Script     1.0.3                 Az.Billing                          Core,Desk
Script     1.4.3                 Az.Cdn                              Core,Desk
Script     1.5.0                 Az.CognitiveServices                Core,Desk
Script     4.2.1                 Az.Compute                          Core,Desk
Script     1.0.3                 Az.ContainerInstance                Core,Desk
Script     1.1.1                 Az.ContainerRegistry                Core,Desk
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk
Script     1.9.0                 Az.DataFactory                      Core,Desk
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk
Script     1.2.8                 Az.DataLakeStore                    Core,Desk
Script     1.0.0                 Az.DataShare                        Core,Desk
Script     1.1.0                 Az.DeploymentManager                Core,Desk
Script     1.0.0                 Az.DesktopVirtualization            Core,Desk
Script     1.0.2                 Az.DevTestLabs                      Core,Desk
Script     1.1.2                 Az.Dns                              Core,Desk
Script     1.3.0                 Az.EventGrid                        Core,Desk
Script     1.5.0                 Az.EventHub                         Core,Desk
Script     1.6.0                 Az.FrontDoor                        Core,Desk
Script     1.0.1                 Az.Functions                        Core,Desk
Script     3.3.1                 Az.HDInsight                        Core,Desk
Script     1.1.0                 Az.HealthcareApis                   Core,Desk
Script     2.5.0                 Az.IotHub                           Core,Desk
Script     2.0.0                 Az.KeyVault                         Core,Desk
Script     1.3.2                 Az.LogicApp                         Core,Desk
Script     1.1.3                 Az.MachineLearning                  Core,Desk
Script     1.0.0                 Az.Maintenance                      Core,Desk
Script     1.0.2                 Az.ManagedServices                  Core,Desk
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk
Script     1.1.1                 Az.Media                            Core,Desk
Script     2.0.2                 Az.Monitor                          Core,Desk
Script     3.2.0                 Az.Network                          Core,Desk
Script     1.1.1                 Az.NotificationHubs                 Core,Desk
Script     2.2.0                 Az.OperationalInsights              Core,Desk
Script     1.3.1                 Az.PolicyInsights                   Core,Desk
Script     1.1.2                 Az.PowerBIEmbedded                  Core,Desk
Script     1.0.3                 Az.PrivateDns                       Core,Desk
Script     2.11.0                Az.RecoveryServices                 Core,Desk
Script     1.2.1                 Az.RedisCache                       Core,Desk
Script     1.0.3                 Az.Relay                            Core,Desk
Script     2.3.0                 Az.Resources                        Core,Desk
Script     1.4.1                 Az.ServiceBus                       Core,Desk
Script     2.1.0                 Az.ServiceFabric                    Core,Desk
Script     1.1.1                 Az.SignalR                          Core,Desk
Script     2.9.0                 Az.Sql                              Core,Desk
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk
Script     2.3.0                 Az.Storage                          Core,Desk
Script     1.3.0                 Az.StorageSync                      Core,Desk
Script     1.0.1                 Az.StreamAnalytics                  Core,Desk
Script     1.0.0                 Az.Support                          Core,Desk
Script     1.0.4                 Az.TrafficManager                   Core,Desk
Script     1.11.0                Az.Websites                         Core,Desk
Manifest   2.0.3                 AzTable                             Desk

Removing intermediate container 7e7ce5f62b12
 ---> 239084d06ebf
Step 10/10 : ENTRYPOINT ["pwsh", "QA-MESafety-ScaleDown.ps1"]
 ---> Running in 6f090e6d773b
Removing intermediate container 6f090e6d773b
 ---> 7309f63de2e0
Successfully built 7309f63de2e0
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
```

**Comment by abirax** [comment]
Hi dingmeng-xue , 

I still get the error I am building the image on docker desktop windows 10 v2.3.0.2.See after step 7 .One thing I noticed is that the Get-PSRepository for me shows Untrusted but Trusted for you.

Sending build context to Docker daemon  34.82kB
Step 1/10 : FROM mcr.microsoft.com/azure-powershell:latest AS base
latest: Pulling from azure-powershell
Digest: sha256:424dd9a344e19861128dae1509597220e621e53160d95ee1a401fb258fab9755
Status: Downloaded newer image for mcr.microsoft.com/azure-powershell:latest
 ---> 1211ffce20dd
Step 2/10 : WORKDIR /app
 ---> Using cache
 ---> fb390d57894b
Step 3/10 : COPY . .
 ---> 29f0c3b188f8
Step 4/10 : RUN ls -a
 ---> Running in d4f180ce5b07
.
..
Check.ps1
Removing intermediate container d4f180ce5b07
 ---> a2f529e74975
Step 5/10 : Run pwsh -c "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12"
 ---> Running in f6af4cf8d0ba
Removing intermediate container f6af4cf8d0ba
 ---> 7b1fea3b7a04
Step 6/10 : Run pwsh -c "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted"
 ---> Running in 588548bfc6b5
Removing intermediate container 588548bfc6b5
 ---> 59fae433a4b4
Step 7/10 : RUN pwsh -c "Install-Module AzTable -AllowClobber"
 ---> Running in 5c22ecd2ea7c
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
Install-Package: /opt/microsoft/powershell/7/Modules/PowerShellGet/PSModule.psm1:9709
Line |
9709 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No match was found for the specified search criteria and
     | module name 'AzTable'. Try Get-PSRepository to see all
     | available registered module repositories.

Removing intermediate container 5c22ecd2ea7c
 ---> 524551bb942b
Step 8/10 : RUN pwsh -c "Get-PSRepository"
 ---> Running in 7728d99c1cf5

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Untrusted            https://www.powershellgallery.c…

Removing intermediate container 7728d99c1cf5
 ---> 8fc23a47bc60
Step 9/10 : RUN pwsh -c "Get-Module -ListAvailable Az*"
 ---> Running in 1a91e1db62af


    Directory: /root/.local/share/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Script     4.4.0                 Az                                  Core,Desk
Script     1.9.1                 Az.Accounts                         Core,Desk
Script     1.1.1                 Az.Advisor                          Core,Desk
Script     1.1.3                 Az.Aks                              Core,Desk
Script     1.1.4                 Az.AnalysisServices                 Core,Desk
Script     2.0.1                 Az.ApiManagement                    Core,Desk
Script     1.1.0                 Az.ApplicationInsights              Core,Desk
Script     1.3.7                 Az.Automation                       Core,Desk
Script     3.1.0                 Az.Batch                            Core,Desk
Script     1.0.3                 Az.Billing                          Core,Desk
Script     1.4.3                 Az.Cdn                              Core,Desk
Script     1.5.0                 Az.CognitiveServices                Core,Desk
Script     4.2.1                 Az.Compute                          Core,Desk
Script     1.0.3                 Az.ContainerInstance                Core,Desk
Script     1.1.1                 Az.ContainerRegistry                Core,Desk
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk
Script     1.9.0                 Az.DataFactory                      Core,Desk
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk
Script     1.2.8                 Az.DataLakeStore                    Core,Desk
Script     1.0.0                 Az.DataShare                        Core,Desk
Script     1.1.0                 Az.DeploymentManager                Core,Desk
Script     1.0.0                 Az.DesktopVirtualization            Core,Desk
Script     1.0.2                 Az.DevTestLabs                      Core,Desk
Script     1.1.2                 Az.Dns                              Core,Desk
Script     1.3.0                 Az.EventGrid                        Core,Desk
Script     1.5.0                 Az.EventHub                         Core,Desk
Script     1.6.0                 Az.FrontDoor                        Core,Desk
Script     1.0.1                 Az.Functions                        Core,Desk
Script     3.3.1                 Az.HDInsight                        Core,Desk
Script     1.1.0                 Az.HealthcareApis                   Core,Desk
Script     2.5.0                 Az.IotHub                           Core,Desk
Script     2.0.0                 Az.KeyVault                         Core,Desk
Script     1.3.2                 Az.LogicApp                         Core,Desk
Script     1.1.3                 Az.MachineLearning                  Core,Desk
Script     1.0.0                 Az.Maintenance                      Core,Desk
Script     1.0.2                 Az.ManagedServices                  Core,Desk
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk
Script     1.1.1                 Az.Media                            Core,Desk
Script     2.0.2                 Az.Monitor                          Core,Desk
Script     3.2.0                 Az.Network                          Core,Desk
Script     1.1.1                 Az.NotificationHubs                 Core,Desk
Script     2.2.0                 Az.OperationalInsights              Core,Desk
Script     1.3.1                 Az.PolicyInsights                   Core,Desk
Script     1.1.2                 Az.PowerBIEmbedded                  Core,Desk
Script     1.0.3                 Az.PrivateDns                       Core,Desk
Script     2.11.0                Az.RecoveryServices                 Core,Desk
Script     1.2.1                 Az.RedisCache                       Core,Desk
Script     1.0.3                 Az.Relay                            Core,Desk
Script     2.3.0                 Az.Resources                        Core,Desk
Script     1.4.1                 Az.ServiceBus                       Core,Desk
Script     2.1.0                 Az.ServiceFabric                    Core,Desk
Script     1.1.1                 Az.SignalR                          Core,Desk
Script     2.9.0                 Az.Sql                              Core,Desk
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk
Script     2.3.0                 Az.Storage                          Core,Desk
Script     1.3.0                 Az.StorageSync                      Core,Desk
Script     1.0.1                 Az.StreamAnalytics                  Core,Desk
Script     1.0.0                 Az.Support                          Core,Desk
Script     1.0.4                 Az.TrafficManager                   Core,Desk
Script     1.11.0                Az.Websites                         Core,Desk

Removing intermediate container 1a91e1db62af
 ---> dff5686844f9
Step 10/10 : ENTRYPOINT ["pwsh", "QA-XXX.ps1"]
 ---> Running in 76b7d288ed93
Removing intermediate container 76b7d288ed93
 ---> eb9c5b8daa38
Successfully built eb9c5b8daa38
Successfully tagged xys:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

**Comment by dingmeng-xue** [comment]
What's Check.ps1? Could you try that using dockerfile and save it with Unix line endings.

**Comment by dingmeng-xue** [comment]
@abirax , here is my version v2.3.0.3. output of docker version is below for your reference.
```
PS C:\Users\dixue> docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Another thing may be connection related. Could you add a wget in your scripts and check if docker image can connect external? If repository is untrusted, the error message should not like what you see in log.

**Comment by abirax** [comment]
> What's Check.ps1? Could you try that using dockerfile and save it with Unix line endings.

Hi that is a files in my directory its output of ls-a

**Comment by abirax** [comment]
@dingmeng-xue My docker version output is below . As you would see in my docker output Get-PSRepository shows that the repository is untrusted but truested for you.

Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by dingmeng-xue** [comment]
I read below page but no idea if it is due to pwsh needs to be triggered with Administrator role.  You can try `[Net.ServicePointManager]::SecurityProtocol` and see if TLS 1.2 is set. In addition, did you try it in other environment? If network has no special constraints, you don't need to set SecurityProtocol.

https://www.myerrorsandmysolutions.com/unable-to-resolve-package-source-https-www-powershellgallery-com-api-v2/

**Comment by dingmeng-xue** [comment]
@abirax , is your issue resolved?
