### ISSUE TITLE
Update metadata on Azuee Data Lage Storage Gen2 (without overwrite)

### ISSUE THREAD

**Issue by t-huss** [Azure/azure-powershell#12508]
When you have a directory or file on ADLS Gen2 Storage and want to edit metadata, currently there are only two ways: re-uploading the file with New-AzDataLakeGen2Item (of course very impractical) or updating through Update-AzDataLakeGen2Item. The drawback of the latter one is that you need to specify every existing metadata key-value pair as well, because the whole metadata will be replaced with the specified key-value pairs from the update statement.
A far better solution would be to be able to specifically add new or remove existing key-value pairs (e.g. something like $file.properties.metadata.add/remove).

**Comment by blueww** [comment]
@t-huss 

Thanks for raising this issue! 
In SDK, we need to update meatadata as a whole object. (and can't update metadata with key "hdi_isfolder")
`$file.properties.metadata.add/remove)` only update the local object, not the Item on server. (the limitation is from SDK)
If you want to update metadata, after `$file.properties.metadata.add/remove)`, you must run `Update-AzDataLakeGen2Item` to update it to server.

The script will look like: 
```powershell
# Get datalake gen2 item, include metadata
$file = Get-AzDataLakeGen2Item -FileSystem $filesystemName -Path $path1 -Context $ctx

#Update Metadata, like add a key/value pair. (Must remove metadata "hdi_isfolder" before set back, as server doesn't allow to update it.)
$file.Properties.Metadata.add($key,$value)
$file.Properties.Metadata.Remove("hdi_isfolder")

# Update meta data on server
Update-AzDataLakeGen2Item -Context $ctx -FileSystem $filesystemName -Path $path1 -Metadata $file.Properties.Metadata
```

**Comment by t-huss** [comment]
Ok, so just to make sure my understanding is correct: you first get the existing metadata as an object in Powershell, update this object by adding/removing key-value pairs, and then use this object within the Update-AzDataLakeGen2Item statement? Sounds like a solid approach, thanks!

**Comment by blueww** [comment]
@t-huss 
Yes, you can update the metadata as the process like your describe above.
Would you like to close the issue if you don't have further questions on metadata update?

Feel free to contact us again if you need further assistance.

**Comment by t-huss** [comment]
Solutions described in comments
