### ISSUE TITLE
Login-AzureRmAccount not working with org id credentials from get-credentials

### ISSUE THREAD

**Issue by Cloudry** [Azure/azure-powershell#1253]
When running Login-AzureRmAccount and interactively logging in with an organisational ID, it works as expected and gives a list of subscriptions from  Get-AzureRmSubscription

Whereas this doesn't work 

$Credential = Get-Credential
Add-AzureRmAccount -Credential $Credential

At this point, it does provide Account, TenantId and SubscriptionId as expected, however

When I subsequently run Get-AzureRmSubscription I get - 

Get-AzureRmSubscription : Could not authenticate with tenant . Please ensure that your account has access to this
tenant and log in with Login-AzureRmAccount

**Comment by markcowl** [comment]
@Cloudry Is this a csp account?  In the CSP account scenario, you must provide -TenantId when listing subscriptions

**Comment by pcgeek86** [comment]
@markcowl What is a CSP account? I'm not immediately familiar with this acronym.

**Comment by ciphertxt** [comment]
CSP = [Cloud Solution Provider](https://mspartner.microsoft.com/en/us/pages/solutions/cloud-reseller-overview.aspx).

**Comment by Cloudry** [comment]
It is an MSDN account with multiple subscriptions under the same tenant, but providing the -TenantId does seem to work. 

I have been trying to load up multiple accounts, but RM only appears to support having a single account loaded at a time (In classic mode I could Add-AzureAccount both my prod and dev tenants  and simply Select-AzureSubscription amongst them. 

If I was able to load multiple tenants specifying the tenant id would make sense (even then, classic mode could work around it), but since it only allows one to load at a time...

**Comment by markcowl** [comment]
@Cloudry The issue would only occur if the credentials you provided cannot be authenticated against the common tenant.  If you se credentials that have access to multiple tenants, all tenants you have access to will be listed.

As to multiple accounts, It is a different model, and I expect it will take some time to get used to if you have been using the older model.  Users were often confused by having multiple active logins, and the local cache of subscriptions is much more likely to get quickly out of date in AzureRm.  You can still easily switch between logins using something like:

```
$profile1 = Login-AzureRmAccount 
$profile2 = Login-AzureRmAccount

Select-AzureRmProfile -Profile $profile2
```

You can also save profiles to disk using

```
Save-AzureRMProfile
```

**Comment by Cloudry** [comment]
Thank you @markcowl that does cover the issues I have been having. 

(though I would add that the documentation for Login-AzureRmAccount / Select-AzureRmProfile really doesn't put across what it does, or how to use it! - Where are the help files located? I suppose the whole point of it being here is that we can fix stuff ourselves! I'm a little out of my depth with the C# stuff, but I'm sure I can hack some help text)

**Comment by BradHudon** [comment]
I have been struggling with EXACTLY the same problem. 

"When running Login-AzureRmAccount and interactively logging in with an organisational ID, it works as expected and gives a list of subscriptions from Get-AzureRmSubscription

Whereas this doesn't work 

$Credential = Get-Credential
 Add-AzureRmAccount -Credential $Credential

At this point, it does provide Account, TenantId and SubscriptionId as expected, however

When I subsequently run Get-AzureRmSubscription I get - 

Get-AzureRmSubscription : Could not authenticate with tenant . Please ensure that your account has access to this
 tenant and log in with Login-AzureRmAccount"

However, I tried the -Tenantid with the get-Azurermsubscription and in my case I get the same error. I am using an AD organizational account.

Any ideas what might be "special" about me ?

**Comment by BradHudon** [comment]
Forget it . I just figured out what's special about me and you don't wanna know .

**Comment by Moffmo** [comment]
@BradHudon what was your issue - I'm struggling in the same way as you?
