### ISSUE TITLE
There is no equivalent of Disable-ServiceFabricNode, how to stop and start Service Fabric cluster nodes?

### ISSUE THREAD

**Issue by pdonovan** [Azure/azure-powershell#12534]
As per the subject, there does not seem to be a way to stop or start individual Service Fabric cluster nodes in the Az.ServiceFabric module. Is there another way to do this, or has it just not been added yet?

**Comment by dingmeng-xue** [comment]
ServiceFabric team, please help to check this question.

**Comment by KranthiPakala-MSFT** [comment]
@QingChenmsft, @vaishnavk , @juhacket - Could you please have a look at the above feedback and share your thoughts? - Thank you

**Comment by navba-MSFT** [comment]
@pdonovan Thanks for raising the issue. Apologies for the delay in response. Firstly, we should not stop the underlying the VMs specially the SF seed nodes as there are high chances that it might destroy the SF cluster. To turn off cluster/VMs occasionally, you can read [this](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-common-questions#can-i-turn-off-my-cluster-at-nightweekends-to-save-costs) article.
 
If you wish to stop the nodes you can run the [start-servicefabricnodetransition ]( https://docs.microsoft.com/en-us/powershell/module/servicefabric/start-servicefabricnodetransition?view=azureservicefabricps) command with -stop parameter, post which Node will be stopped. If you want to start again, You need to specify the -start parameter. 

>The Start-ServiceFabricNodeTransition cmdlet is preferred over the Start-ServiceFabricNode and Stop-ServiceFabricNode cmdlets, which are obsolete. Avoid mixing usage of this cmdlet with Start-ServiceFabricNode and Stop-ServiceFabricNode. If a node is has already been stopped by using Stop-ServiceFabricNode, start it using Start-ServiceFabricNode before using Start-ServiceFabricNodeTransition. Use Start-ServiceFabricNodeTransition from then on.

More info [here](https://docs.microsoft.com/en-us/powershell/module/servicefabric/start-servicefabricnodetransition?view=azureservicefabricps#description)

This github thread has been open for quite sometime now. Please let me know if you need any further assistance on this. We would be happy to address it. Awaiting your reply.

**Comment by pdonovan** [comment]
@navba-MSFT We no longer use SF, so this isn't an issue for us any more.

**Comment by navba-MSFT** [comment]
@pdonovan Thanks for getting back. Since this github thread is open for a long time now, we will proceed with closure. In future, if you need any further assistance on this, please feel free to reopen this thread. We would be happy to address your issues.
