### ISSUE TITLE
[Functions] Warn when creating a v2 function app

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-powershell#12530]
Encourage customers to create v3 apps. 

More info: https://github.com/Azure/app-service-announcements/issues/266

/cc @pragnagopa

**Comment by pragnagopa** [comment]
@Francisco-Gamino  - please triage

**Comment by Francisco-Gamino** [comment]
Hi @stefanushinardi and @anthonychu -- what should the warming say when creating a V2 function app?

**Comment by anthonychu** [comment]
I think when this was created, we were hoping to drive attention to the upgrade announcement. Since it's happening in a couple of weeks, perhaps there's no need to do this. We should instead think about what we want to do about this long term. I think it's still valid to allow creating v2 apps.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed in the latest Az.Functions release.
