### ISSUE TITLE
Az.ContainerRegistry needs to upgrade API version to 2019-05-01

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#12538]
## Description of the new feature

Current Az.ContainerRegistry is using API version 2017-10-01. We need to upgrade it to 2019-05-01 due to Azure environment requirement.

**Comment by VeryEarly** [comment]
api upgrade finished in branch https://github.com/Azure/azure-powershell/tree/release-2020-10-27
