### ISSUE TITLE
The MSI package for Azure PowerShell from GitHub Doesn't Work

### ISSUE THREAD

**Issue by Esme-A** [Azure/azure-powershell#12539]
Hello, I need to be able to install the Az PowerShell module in several systems in an offline environments. I was trying to use the Az-Cmdlets-4.4.0.33134-x64.msi to deploy it; however, during the installation I get pass the 'I accept the terms in the License Agreement' and it looks like it is going to install then I get error 'Microsoft Azure PowerShell -July 2020 Setup Wizard ended prematurely because of an error. Your system has not been modified. To install this program at a later time, run Setup Wizard again...' I have tested it in 4 different server 2016 Version 1607 (Build 14393.3808  and 3 Windows 10 Versin 1903 (Build 18362.592) VMs which meet all the requirements and have the latest patches installed. Here is the docs I'm using as reference https://docs.microsoft.com/en-us/powershell/azure/install-az-ps-msi?view=azps-4.4.0

**Comment by dingmeng-xue** [comment]
@Esme-A , thanks for reporting. we have couple issues on MSI. such as #11361. Please help to provide system information on this issue. We will address this problem in this half year.
