### ISSUE TITLE
Get-AzAks is missing output present in `az aks` (follow-up on #11885)

### ISSUE THREAD

**Issue by jsco2t** [Azure/azure-powershell#12546]
This is meant to be a follow-up on issue #11885.

When I originally tested the fix that was implemented in version 1.1.1 of the module things looked much better. However after further examining the issue - I am still seeing that certain objects are missing from the output which are present on the `az aks list` counterpart method.

A good example of this is the `identityProfile` json object returned from `az aks list`. This object (and it's child object `kubeletidentity`) provides you with access to the Managed Identity Object ID that's being used by the cluster. As far as I can tell this information is not present _anywhere_ in the output to Get-AzAks.

I am currently using version 1.1.2 of the AKS powershell module.

Since I can't re-open my former issue - I am opening a new issue.

**Comment by dingmeng-xue** [comment]
@jsco2t , thanks for reporting.

@wyunchi-ms , please look into this question and evaluate if we can support it.
