### ISSUE TITLE
Missing '$' in example 3 of documentation page for 'New-AzPublicIpAddress' - URL:https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzPublicIpAddress.md

### ISSUE THREAD

**Issue by GaryLBaird** [Azure/azure-powershell#12543]
## Description
https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/help/New-AzPublicIpAddress.md

Example 3 in the documentation: as shown below is missing the '$' for ipTag.
$ipTag = New-AzPublicIpTag -IpTagType "FirstPartyUsage" -Tag "/Sql"
$publicIp = New-AzPublicIpAddress -Name $publicIpName -ResourceGroupName $rgName -AllocationMethod Static -DomainNameLabel $dnsPrefix -Location $location -IpTags ipTag

Expected Change:
... -Location $location -IpTags ipTag
Should be:
... -Location $location -IpTags $ipTag

**Comment by dingmeng-xue** [comment]
Network team, please help to verify and update the doc.

**Comment by jl-ms** [comment]
I will review and make changes to it. Thanks. @KumudD

**Comment by allegradomel** [comment]
I have created a PR to correct this https://github.com/Azure/azure-powershell/pull/12959
@GaryLBaird thanks for bringing this to our attention!
