### ISSUE TITLE
webapp: Allow importing of key vault certificates to app service

### ISSUE THREAD

**Issue by Tyriar** [Azure/azure-powershell#12540]
## Description of the new feature

It doesn't appear to be possible currently to import pfx certificates into app service. There is [New-AzWebAppSSLBinding](https://docs.microsoft.com/en-us/powershell/module/az.websites/new-azwebappsslbinding?view=azps-4.4.0) that allows uploading certs but not importing from key vault.

## Proposed implementation details (optional)

See `-KeyVaultName` below:

```
New-AzWebAppSSLBinding
   [-ResourceGroupName] <String>
   [-WebAppName] <String>
   [[-Slot] <String>]
   [-Name] <String>
   [[-SslState] <SslState>]
   [-KeyVaultName] <String>
   [-Thumbprint] <String> # or [-CertificateName]?
   [-DefaultProfile <IAzureContextContainer>]
   [<CommonParameters>]
```

**Comment by dingmeng-xue** [comment]
AppService team, please help to evaluate this feature request.

**Comment by Kotasudhakarreddy** [comment]
@ThejaChoudary - look in to this.

**Comment by lszomoru** [comment]
While I have gotten this to work, it is a little cumbersome and I agree that the `New-AzWebAppSSLBinding` cmdlet should be improved.

In order to get this to work I had to:
1. Create a `Microsoft.Web/certificates` Azure resource using an ARM template linked to the app service plan
2. Create a new App Service that uses the app service plan that has the certificate Azure resource linked
3. Call `New-AzWebAppSSLBinding` and specify the `-Thumbprint` parameter

**Comment by shiva0010131** [comment]
Hi Team,

Is New-AzWebAppSSLBinding cmdlet supports keyvault or storage account URL to upload certificate ? or is there a way to automate this process through runbook ? I know there are articles to use ARM templates to get this done, just want to know if this is possible with runbook (we can call json template through runbook but looking for an option to get this done in runbook without using ARM template).

**Comment by TheShihan** [comment]
Is there any update on this?

**Comment by Kotasudhakarreddy** [comment]
[Import-AzWebAppKeyVaultCertificate](https://learn.microsoft.com/en-us/powershell/module/az.websites/import-azwebappkeyvaultcertificate?view=azps-9.2.0) is available to support import from KeyVault. Please use it and let us know your feedback, please.
