### ISSUE TITLE
[Functions] Add support for custom handler

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-powershell#12542]
## Description of the new feature
Add support to create function apps for CustomHandlers: https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers
## Proposed implementation details (optional)
Stacks: https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/pull/13

cc @anthonychu

@Francisco-Gamino - please triage.

**Comment by dingmeng-xue** [comment]
@Francisco-Gamino , please help to triage this question.

**Comment by Francisco-Gamino** [comment]
cc: @anirudhgarg @eamonoreilly @anthonychu

**Comment by Francisco-Gamino** [comment]
This issue has been fixed in the latest release.
