### ISSUE TITLE
[Az.Functions] Update stacks to new schema 

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-powershell#12559]
cc @Francisco-Gamino  @anthonychu @ammanifold

Repo: https://github.com/pragnagopa/azure-functions-supported-runtime-stacks is a temporary location and will be deprecated soon.

Please move to updated schema: https://github.com/Azure/azure-functions-ux/tree/dev/server/src/stacks/functionapp/2020-06-01/stacks

NOTE: This info will be available on ARM API. No ETA yet for this.

**Comment by Francisco-Gamino** [comment]
This is duplicate of https://github.com/Azure/azure-powershell/issues/14682.
