### ISSUE TITLE
Get-AzureRmSubscription has no ExtendedDetails parameter

### ISSUE THREAD

**Issue by ColdHarbour** [Azure/azure-powershell#1258]
I want to use the -ExtendedDetails parameter to discover ARM resource limits vs current usage in a subscription, but this parameter does not exist in the new cmdlet 

Example usage in ASM:
(Get-AzureSubscription -current -ExtendedDetails).maxcorecount 

Can this parameter please be added in to Get-AzureRmSubscription?

Thanks
Tom

**Comment by markcowl** [comment]
@ColdHarbour Unfortunately, there is no similar call for subscription details in ARM as in service management.

**Comment by ColdHarbour** [comment]
Thanks @markcowl  - to be honest I'm not sure how (or where) this should be implemented, but it would be good to be able to expose ARM subscription resource limits and resource usage via PowerShell
