### ISSUE TITLE
AzureStack - ADFS - New-AzureRmRoleAssignment : The Principal ID value is not valid. Principal ID must be a SecurityIdentifier(SID)

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#12581]
## Description
When providing  ADFS Group instead of user , New-AzureRmRoleAssignment throws the below error

New-AzureRmRoleAssignment -ObjectId "S-1-5-21-x-x-x-x" -RoleDefinitionName Reader -Scope "/subscriptions/x"
New-AzureRmRoleAssignment : The content of your request was not valid, and the original object could not be deserialized. Exception message: 'Required property 'principalId' 
not found in JSON. Path 'properties', line 4, position 3.'
At line:1 char:1

## Module versions
AzureRM Version -2.5.0 (AzureStack specific)

**Comment by dingmeng-xue** [comment]
We suggest to address this issue on Az module. Is it new issue shown up recently?

**Comment by dingmeng-xue** [comment]
@bganapa , we will visit this issue once Az.Account GA version supports MSAL in this semester.

**Comment by bganapa** [comment]
@dingmeng-xue Agree, we should fix this in next Az  module release for AzureStack. Lets keep the issue open for AzureRM as well

**Comment by bganapa** [comment]
closing this in favor of https://github.com/Azure/azure-powershell/issues/12582
