### ISSUE TITLE
Get-AzureRmResource requires "ResourceName" as mandatory parameter.

### ISSUE THREAD

**Issue by iamshital** [Azure/azure-powershell#1259]
I was using following commands as part of my automation. They worked fine until v.0.9.9

`$RGIPdata = Get-AzureRmResource -ResourceGroupName $ResourceGroup -ResourceType "Microsoft.Network/publicIPAddresses" -Verbose -ExpandProperties -IsCollection`
`$RGVMs = Get-AzureRmResource -ResourceGroupName $ResourceGroup -ResourceType "Microsoft.Compute/virtualMachines" -Verbose -ExpandProperties -IsCollection`
`$NICdata = Get-AzureRmResource -ResourceGroupName $ResourceGroup -ResourceType "Microsoft.Network/networkInterfaces" -Verbose -ExpandProperties -IsCollection`

Each command gave all resources for given resource type.

But now `Get-AzureRmResource` requires "ResourceName" as mandatory parameter which is very inconvenient. Coz I use, dynamic resource names for automation.
Of course, I can add some lines of code to make it work but this new change is very inconsistent.

If I execute `Get-AzureRmResource` it lists all the resources. Great.
If I execute `Get-AzureRmResource -ResourceType "someType"`, I get error - "Parameter set cannot be resolved using the specified named parameters."
I would love to see all the resources who are `someType` regardless of resource group name.
If I execute `Get-AzureRmResource -ResourceType someType -ResourceGroupName RGName`, It asks, ResourceName.
I would love to see all the resources who are `someType` in `RGName`

**Comment by TravisEz13** [comment]
I can also verify this worked fine without resource name in previous build.  Please fix this.

**Comment by wi5nia** [comment]
I cal also confirm that this is not working currently

**Comment by mithunshanbhag** [comment]
+1.

**Comment by vkulks2015** [comment]
+1

**Comment by rcarmo** [comment]
I just have to +1 this as well. Can't build the automation I need without it (use case is to shutdown tagged VMs, and can't use the VM names to reference them since the tags are dynamic).

**Comment by ravbhatnagar** [comment]
We are looking into fixing this issue.
 
In the meantime, you can use the following cmdlet which we have added to search for resources via query parameters-
Find-AzureRmResource -ResourceType $resourceType -ResourceGroupNameContains $resourceGroupName to get the list of resources.

Another usecase for the Find cmdlet would be if you'd like to find all the resources containing a specific tag. Such functionality, which was earlier supported through Get, has now been moved to this new cmdlet. This was done to simplify the existing Get-AzureRmResource cmdlet which was pretty overloaded. 

Please let us know if you have any questions on this.

**Comment by rcarmo** [comment]
Could you please point us to an example of finding all resources of a given type with a given tag, for future reference of anyone landing here via search?

**Comment by ravbhatnagar** [comment]
For finding all resources with a given tag, you will use the following -
Find-AzureRmResource -TagName <tagName> -TagValue <tagValue>

Now, if you'd like to find all resources of a specific type which contains the tag, you can do something like below -
Find-AzureRmResource -TagName <tagName> -TagValue <tagValue>| Where-Object ResourceType -eq <resource-type>

**Comment by ravbhatnagar** [comment]
Fixed - 3/3 PS release
