### ISSUE TITLE
AzTable is incorrectly named

### ISSUE THREAD

**Issue by kilasuit** [Azure/azure-powershell#12597]
## Description
As found out in #12596 `AzTable` is incorrectly named and to match the naming convention of all other modules it should have been called `Az.Table` and never 'AzTable'

## Steps to reproduce

```powershell
https://www.powershellgallery.com/packages/AzTable/2.0.3
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. AzTable is not in Azure/azure-powershell repo and not developed by Azure PowerShell team.

**Comment by dingmeng-xue** [comment]
Cosmos team, I just read the functions of AzTable.  It seems support cosmos table functions. Do you have plan to offer the same functions in Az.CosmosDB?

**Comment by wmengmsft** [comment]
AzTable is not related to Azure PowerShell. It is a module for interacting with data-plane of both Cosmos DB Table API and Azure Storage Table service, developed entirely independently from Azure Powershell. There are no plans for integrating AzTable with Az.CosmosDB or offer its functionality in Az.CosmosDB.

Please go ahead and close this issue.
