### ISSUE TITLE
AzTable not installed with install of Az

### ISSUE THREAD

**Issue by kilasuit** [Azure/azure-powershell#12596]
## Description

As issue title AzTables (which is incorrectly named anyway) is not installed with Az PowerShell as it is not listed as a dependency of the module on https://www.powershellgallery.com/packages/Az/4.5.0
## Steps to reproduce

```powershell
Install-Module Az -RequiredVersion 4.5.0
```

## Environment data

```
All PowerShell Versions
```

## Module versions

```powershell
Az 4.5.0
```

**Comment by dingmeng-xue** [comment]
AzTables is not included because it is not Azure PowerShell module. User needs to install it separately if required.
