### ISSUE TITLE
Az PowerShell 4.40 upgrade on hosted MSFT agents is causing problems copying contents from blob container

### ISSUE THREAD

**Issue by v-yamakk** [Azure/azure-powershell#12592]
## Description
Customer is trying to execute below PowerShell script to copy blob container contents to Agent directory. Customer is using MSFT hosted agent vs2017-win2016, classic editor. 
Files in containers are being copied properly but directories are failing, with below error. The same pipeline succeeds if customer selects specific PowerShell version 4.3.0. If he selects latest, then agent picks up version 4.4.0 and execution fails.

Has anything changed with Get-AzStorageBlobContent cmdlet with Az 4.4.0 on hosted agents?

**PowerShell script**
$contname = 'powershellscriptsv2'
$destpath = '$(Agent.HomeDirectory)/infrascripts'
$constr = '$(InfraStoConStr)'
$stoacc = New-AzStorageContext -ConnectionString $constr
$blobs = Get-AzStorageBlob -Container $contname -Context $stoacc
foreach ($blob in $blobs)
{
   New-Item -ItemType Directory -Force -Path $destpath
   Get-AzStorageBlobContent -Container $contname -Blob $blob.Name -Destination $destpath -Context $stoacc -Force
}

**Error**:
2020-07-28T19:14:01.4376098Z ##[debug]Error record:
2020-07-28T19:14:01.5323995Z ##[debug]Get-AzStorageBlobContent : Directory 'C:\agents\2.172.2\infrascripts\cloudflare' doesn't exist.
2020-07-28T19:14:01.5343196Z ##[debug]At D:\a\_temp\3df488b3-e6d3-4124-b711-d248577ec8a5.ps1:9 char:4
2020-07-28T19:14:01.5391388Z ##[debug]+    Get-AzStorageBlobContent -Container $contname -Blob $blob.Name -De ...
2020-07-28T19:14:01.5415350Z ##[debug]+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-07-28T19:14:01.5435126Z ##[debug]    + CategoryInfo          : InvalidArgument: (:) [Get-AzStorageBlobContent], ArgumentException
2020-07-28T19:14:01.5455516Z ##[debug]    + FullyQualifiedErrorId : ArgumentException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlo    bContentCommand

**Comment by dingmeng-xue** [comment]
Storage team, please help to look into this issue.

**Comment by blueww** [comment]
@v-yamakk 
Thanks for raise this issue!
I have filed a PR to fix it : https://github.com/Azure/azure-powershell/pull/12617

Before this is fixed, as a workaround, you can add following script before run Get-AzStorageBlobContent, to create the sub folder manually before download blob:
```powershell
$dirs = $blob.Name.Split('/')
$dirPath = $destpath
for ($i = 0; $i -lt $dirs.Count-1; $i++)
{
    $dirPath = $dirPath + "\" + $dirs[$i]
    New-Item -ItemType Directory -Force -Path $dirPath
}
```

**Comment by ymakkapati** [comment]
@blueww Could you please share us the ETA when the fix will be deployed in production

**Comment by blueww** [comment]
@ymakkapati 
Per https://github.com/Azure/azure-powershell/milestones, the next release is planned on 8/25.

**Comment by blueww** [comment]
The PR for the fix is already merged. https://github.com/Azure/azure-powershell/pull/12617

**Comment by blueww** [comment]
The fix has been released in latest release:
You can get the release here:
•	Download the install package from Github: https://github.com/Azure/azure-powershell/releases/tag/v4.6.0-August2020
•	Install the package from PSGallery: https://www.powershellgallery.com/packages/Az/4.6.0
