### ISSUE TITLE
Get-AzureRMAutomationJobOutput shortens the string output

### ISSUE THREAD

**Issue by JakobGSvendsen** [Azure/azure-powershell#1260]
In the "old" ARM cmdlets it was possible to create a runbook which would output JSON strings, to be converted to objects when they are received by the script that executes the cmdlets.

This seems impossible now in the new AzureRM cmdlets, since it shortens the returned string, and therefore it is not possible to send all output back to the executing script.

Can you explain why this was changed? or if this is a bug?

Example:
PS E:\Downloads> $Joboutput = $Job | Get-AzureRMAutomationJobOutput

PS E:\Downloads> $Joboutput.Text
{
    "Status":  "Created",
    "Message":  "The user jgs@coretech.dk was crea...

PS E:\Downloads>

**Comment by trondhindenes** [comment]
duplicate of #1158
@JakobGSvendsen there are undocumented apis which allow you to get to the full output while we wait for this bug to be resolved, let me know on twitter if you need any info on that.

**Comment by JakobGSvendsen** [comment]
ah sorry, searched for Get-AzureRMAutomationJobOutput  and got no results so created a issue
