### ISSUE TITLE
1.0 ARM :: New-AzureRmResourceGroupDeployment -Mode parameter only allows "incremental"

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1261]
Should allow "incremental" and "complete."

![image](https://cloud.githubusercontent.com/assets/466713/11032927/8eb1fcc2-869c-11e5-882c-22dcef3a4783.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by devigned** [comment]
@ravbhatnagar & @vivsriaus thoughts on this?

**Comment by vivsriaus** [comment]
@pcgeek86 I'm unable to repro this behavior with the latest 1.0.1 or 1.0.0. Can you please retry?

C:\> New-AzureRmResourceGroupDeployment -Name testNew -ResourceGroupName vtest11 -TemplateFile C:\Users\visriniv\Desktop
\test3.json -TemplateParameterFile C:\Users\visriniv\Desktop\test3p.json -Mode Complete -Force

Here is the relevant output indicating Complete was indeed passed in:
HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/45c0ad46-ae3f-493e-91ce-9297e0953fc1/resourcegroups/vtest11/deployments/test
New?api-version=2014-04-01-preview

Headers:

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 14932
x-ms-request-id               : 3fdd4f68-a37d-43ff-802f-729072b889e2
x-ms-correlation-request-id   : 3fdd4f68-a37d-43ff-802f-729072b889e2
x-ms-routing-request-id       : WESTUS:20151116T214735Z:3fdd4f68-a37d-43ff-802f-729072b889e2
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Mon, 16 Nov 2015 21:47:35 GMT

Body:
{
  "id": "/subscriptions/45c0ad46-ae3f-493e-91ce-9297e0953fc1/resourceGroups/vtest11/deployments/testNew",
  "name": "testNew",
  "properties": {
    "parameters": {
      "hostingPlanName": {
        "type": "String",
        "value": "vivekTest123"
      },
      "siteLocation": {
        "type": "String",
        "value": "West US"
      },
      "sku": {
        "type": "String",
        "value": "Standard"
      },
      "workerSize": {
        "type": "Int",
        "value": 0
      }
    },
    "mode": "Complete",
    "provisioningState": "Succeeded",
    "timestamp": "2015-11-16T21:47:33.6842212Z",
    "duration": "PT1M11.7487368S",
    "correlationId": "af3ce1a8-6140-4473-8d4f-fa631566418f",
    "providers": [
      {
        "namespace": "Microsoft.Web",
        "resourceTypes": [
          {
            "resourceType": "serverfarms",
            "locations": [
              "westus"
            ]
          }
        ]
      }
    ],
    "dependencies": [],
    "outputResources": [
      {
        "id": "Microsoft.Web/serverfarms/vivekTest123"
      }
    ]
  }
}

**Comment by ravbhatnagar** [comment]
Unable to repro.

**Comment by pcgeek86** [comment]
Looks okay now. 

<img width="483" alt="screen shot 2016-02-13 at 12 21 26 pm" src="https://cloud.githubusercontent.com/assets/466713/13029531/552287d2-d24c-11e5-86db-289a81f036a3.png">
