### ISSUE TITLE
Set-AzContext Fails to Set Context to named Subscription on First Execution

### ISSUE THREAD

**Issue by JimGBritt** [Azure/azure-powershell#12613]
## Description
My script https://aka.ms/CreateAzDiagPolicies navigates subscriptions selected by the user (switching subscriptions / context as they enumerate resources) to create policy files for Azure Diagnostics.  Fairly consistently when I set az context (select-AzSubscription / Set-AzContext) the operation fails silently and actually instead selects the context that is already set instead of the one I am requesting.  The script can be used to repro the issue.  Logic has been put in the script to retry the operation if it fails to properly set context upon successful completion of the script.

## Steps to reproduce

1. My script gets Az Context Subscription Name upon initial launch
```powershell
$currentSub = $(Get-AzContext).Subscription.Name
```
2. Next I may switch to other subscriptions "Select-AzSubscription -subscriptionName xxx" to collect some data / do some rest calls against resources, etc.
```powershell
$SubscriptionToUse = Select-AzSubscription -Subscription $SubscriptionId
```
3. At the end of my script I leverage Set-AzContext to set my context back to the subscription I was originally in

4. I was finding that it wasn't consistently setting my context back properly to the sub I specify and requires me to do it more than once before it actually sets it.  So I put in a loop
```powershell
$Count = 0
try
{
    While(($ContextSet -ne $currentSub) -or ($Count -ge 5))
    {
        write-host "Setting Context back to initial subscription $CurrentSub"
        $SetContext = Set-AzContext -Subscription $CurrentSub
        $ContextSet = $SetContext.Subscription.Name
        $Count++
    }
}
catch
{
    Write-Host "Failed to set context back to intial subscription $CurrentSub.  Please review!"
}

Write-Host "Complete`n" -ForegroundColor Green
Write-Host "Script execution time: " -nonewline
```

I can fairly consistently see the context failing to set on first attempt and I need to loop to ensure it is successfully set.

```powershell 
Authenticating to Azure...
Selecting Azure Subscription: XYZ Sub ...
Gathering a list of monitorable Resource Types from Azure Subscription XYZ Sub...
Successfully wrote ARM template Policy Initiative to .\ARM-Template-azurepolicyinit.json    
Now Validating JSON in each exported policy artifact...
Total Valid Files Checked: 1
Total Invalid Files Found: 0
Setting Context back to initial subscription Jbritt
Setting Context back to initial subscription Jbritt
Complete

Script execution time: 0 minutes and 20 seconds.
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
PS C:\Users\jbritt\Documents\GitHub\AzurePolicy\AzureMonitor\Scripts> Get-Module -Name AZ  -ListAvailable

    Directory: C:\Users\jbritt\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     4.5.0                 Az                                  Core,Desk
Script     4.4.0                 Az                                  Core,Desk

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     3.7.0                 Az                                  Core,Desk
Script     2.7.0                 Az                                  Core,Desk
Script     2.5.0                 Az                                  Core,Desk 
```

## Debug output

> **Note**
> Too much internal detail on the debug output stream to include

```

```

## Error output

> **Note**
> The below errors are expected in the execution of my script.  The script iterates against Azure Resources via REST to get details on supported configurations.  If the configuration isn't supported, a 400 will result and I move on to the next.

```
HistoryId: 18

Message        : Response status code does not indicate success: 400 (Bad Request).
StackTrace     :    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
Exception      : Microsoft.PowerShell.Commands.HttpResponseException
InvocationInfo : {Invoke-WebRequest}
Line           :                     $Status = Invoke-WebRequest -uri $URI @GetScanDetails

Position       : At C:\Users\jbritt\Documents\GitHub\AzurePolicy\AzureMonitor\Scripts\Create-AzDiagPolicy.ps1:505 char:31
                 + …                 $Status = Invoke-WebRequest -uri $URI @GetScanDetails
                 +                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 18

Message        : Response status code does not indicate success: 400 (Bad Request).
StackTrace     :    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
Exception      : Microsoft.PowerShell.Commands.HttpResponseException
InvocationInfo : {Invoke-WebRequest}
Line           :                     $Status = Invoke-WebRequest -uri $URI @GetScanDetails

Position       : At C:\Users\jbritt\Documents\GitHub\AzurePolicy\AzureMonitor\Scripts\Create-AzDiagPolicy.ps1:505 char:31
                 + …                 $Status = Invoke-WebRequest -uri $URI @GetScanDetails
                 +                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 18

Message        : Response status code does not indicate success: 400 (Bad Request).
StackTrace     :    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
Exception      : Microsoft.PowerShell.Commands.HttpResponseException
InvocationInfo : {Invoke-WebRequest}
Line           :                     $Status = Invoke-WebRequest -uri $URI @GetScanDetails

Position       : At C:\Users\jbritt\Documents\GitHub\AzurePolicy\AzureMonitor\Scripts\Create-AzDiagPolicy.ps1:505 char:31
                 + …                 $Status = Invoke-WebRequest -uri $URI @GetScanDetails
                 +                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 18
```

**Comment by dingmeng-xue** [comment]
@JimGBritt , thanks for your reporting. I didn't see other report this issue. I tried Set-AzContext in my local and I didn't see the problem.

Is it possible that it is triggered by parallel jobs? Another 2 things could you please try?
1. please try to set subscription by subscription id instead of name
2. please print out subscription information before and after `$SetContext = Set-AzContext -Subscription $CurrentSub`. I'd like to know what current context is during execution.

**Comment by JimGBritt** [comment]
@dingmeng-xue thanks for the response.  I will modify my PS script to use subscriptionID instead of name and report back.  However, I did do number 2 above and here are the results.

I put a get into the script before and after setting.  One thing to note is that it took (3) times running my script before this behavior occurs and that seems to be pretty consistent for me.  Also, another important note is I'm only changing to one sub and then back.  I don't have any parallel execution in my script. So this is just me switching context to "Contoso Hotels" as shown below, doing a REST call against resources in a single resource group, and then switching context back.  One the first two executions of my script it works.  The third execution it has to retry the operation of setting context to the proper context twice which is consistently reproable.

```powershell
try
{
    While(($ContextSet -ne $currentSub) -or ($Count -ge 5))
    {
        Get-AzContext
        write-host "`nSetting Context back to initial subscription $CurrentSub"
        $SetContext = Set-AzContext -Subscription $CurrentSub
        $ContextSet = $SetContext.Subscription.Name
        Get-AzContext
        $Count++
    }
}
catch
{
    Write-Host "Failed to set context back to intial subscription $CurrentSub.  Please review!"
}

Write-Host "Complete`n" -ForegroundColor Green
Write-Host "Script execution time: " -nonewline
Write-Host "$($($Stop - $Start).minutes) minutes and $($($Stop - $Start).seconds) seconds.`n" -ForegroundColor Cyan
```


![image](https://user-images.githubusercontent.com/13633751/89737845-2fe0d700-da29-11ea-973c-dd3da3daf51a.png)

**Comment by JimGBritt** [comment]
Additional information, it looks like just taking the happy path of switching contexts isn't actually showing the issue.  I'm not sure it it is because there is a 400 being returned from REST when using my script but I basically took the logic I'm using (which is not unusual) and put it into a basic script to repro and I cannot repro so not sure what is going on.  I'll continue to investigate and see if I can get a repro that doesn't involve my script.  Happy to connect and show anyone what is going on.

```powershell
$ContextSet = $null
$count = 1
$Null = Set-AzContext -Subscription jbritt
$CurrentSub = "Jbritt"
$null = Set-AzContext -Subscription "Contoso Hotels"
try
{
    While(($ContextSet -ne $currentSub) -or ($Count -ge 5))
    {
        Write-host "`nGetting Context"
        Get-AzContext
        write-host "`nSetting Context back to initial subscription $CurrentSub try #$($Count)" -ForegroundColor Cyan
        $SetContext = Set-AzContext -Subscription $CurrentSub
        $ContextSet = $SetContext.Subscription.Name
        write-host "`nGetting context after setting"
        Get-AzContext
        $Count++
    }
}
catch
{
    Write-Host "Failed to set context back to intial subscription $CurrentSub.  Please review!"
}

Write-Host "Complete`n" -ForegroundColor Green
```
![image](https://user-images.githubusercontent.com/13633751/89738289-36248280-da2c-11ea-9cbc-ff3d732c625a.png)

**Comment by JimGBritt** [comment]
I've been able to further investigate and get a simple repro (on my system).  I've added in a Get-AzResource after setting context and before switching back to preferred initial context.  See below.  Again you may have to run this 3 times before it consistently repros.  Not sure why.  Change subscription name for initial set and currentsub to the same thing (your preferred context).  Then update the second Set-AzContext to another sub, it will then do a Get-AzResource then it will attempt to set to your preferred initial context you initially set ($currentSub in this case).

NOTE: This does repro with SubscriptionId as well.

```powershell

$ContextSet = $null
$count = 1
$Null = Set-AzContext -Subscription jbritt
$CurrentSub = "Jbritt"
$null = Set-AzContext -Subscription "Contoso Hotels"
$Resources = Get-AzResource
try
{
    While(($ContextSet -ne $currentSub) -or ($Count -ge 5))
    {
        Write-host "`nGetting Context"
        Get-AzContext
        write-host "`nSetting Context back to initial subscription $CurrentSub try #$($Count)" -ForegroundColor Cyan
        $SetContext = Set-AzContext -Subscription $CurrentSub
        $ContextSet = $SetContext.Subscription.Name
        write-host "`nGetting context after setting"
        Get-AzContext
        $Count++
    }
}
catch
{
    Write-Host "Failed to set context back to intial subscription $CurrentSub.  Please review!"
}

Write-Host "Complete`n" -ForegroundColor Green
```

![image](https://user-images.githubusercontent.com/13633751/89956225-9a407580-dbe9-11ea-841d-2467e8c6170a.png)

**Comment by dingmeng-xue** [comment]
Your script seems work in my environment. I tried PowerShell Core and PowerShell 7.0.3

```
PS C:\> .\issue-12613-context.ps1

Getting Context

Name                                     Account                             SubscriptionName                    Environment                         TenantId
----                                     -------                             ----------------                    -----------                         --------
Azure SDK Powershell Test - Manual (9e2… dixue@microsoft.com                 Azure SDK Powershell Test - Manual  AzureCloud                          72f988bf-86f1-41af-91ab-2d7cd011db…

Setting Context back to initial subscription Azure SDK Powershell Test try #1

Getting context after setting
Azure SDK Powershell Test (c9cbd920-c00… dixue@microsoft.com                 Azure SDK Powershell Test           AzureCloud                          72f988bf-86f1-41af-91ab-2d7cd011db…
Complete
```

I will look into code and get back to you soon.

**Comment by JimGBritt** [comment]
@dingmeng-xue thank you for the update.  Did you run this script example at least 3 times?  I know this sounds silly but that is when it repros for me.

By the way your example above for some reason looks like it failed to set to your proper context but completed successfully.  

You had it set to this:
```
Azure SDK Powershell Test - Manual 
```

Then it stated it is trying to set context back to this sub: 
```
Azure SDK Powershell Test
```

Then after attempting to set that it, got the context again and shows it was still set to the other sub (not the initial sub) 

```
Getting context after setting
Azure SDK Powershell Test (c9cbd920-c00… dixue@microsoft.com 
```

**Comment by dingmeng-xue** [comment]
@JimGBritt , I believe it's expected. Initial sub is "Azure SDK Powershell Test" and the final result is "Azure SDK Powershell Test" too. trailing with other string because context name is the combination of sub id, tenant id, and account name.

What's your login approach?

**Comment by JimGBritt** [comment]
@dingmeng-xue sorry thought I had replied here already.  My login approach was this script here below I shared.  I put your subs in here to show exactly how I'd repro this.  I run this script three times and on the third time (today started with second time) I run it starts to repro.  If I close VSCode and go back in, it will work fine on first execution.  Subsequent executions require the Set-AzContext to happen twice to switch back to the original context I switched to.

```powershell
$ContextSet = $null
$count = 1
$Null = Set-AzContext -Subscription "Azure SDK Powershell Test"
$CurrentSub = "Azure SDK Powershell Test"
$null = Set-AzContext -Subscription "Azure SDK Powershell Test - Manual"
$Resources = Get-AzResource
try
{
    While(($ContextSet -ne $currentSub) -or ($Count -ge 5))
    {
        Write-host "`nGetting Context"
        Get-AzContext
        write-host "`nSetting Context back to initial subscription $CurrentSub try #$($Count)" -ForegroundColor Cyan
        $SetContext = Set-AzContext -Subscription $CurrentSub
        $ContextSet = $SetContext.Subscription.Name
        write-host "`nGetting context after setting"
        Get-AzContext
        $Count++
    }
}
catch
{
    Write-Host "Failed to set context back to intial subscription $CurrentSub.  Please review!"
}

Write-Host "Complete`n" -ForegroundColor Green
```

**Comment by JimGBritt** [comment]
@dingmeng-xue - I have a brand new laptop and can repro this issue.  This issue does not repro in cloud shell but it does on Windows 10 brand new image with latest AZ cmdlets.  Will ping you via email to see if you need more details. Updated the script to make it easier to show state.

```powershell
$ContextSet = $null
$SetContext = $null
$CurrentSub = $null
$count = 1
write-host 'Setting initial context to jbritt sub'
$SetContext = Set-AzContext -Subscription "jbritt" 
Write-host "Setting CurrentSub Var to $($SetContext.Subscription.Name)"
$CurrentSub = $SetContext.Subscription.Name
write-host "Now Setting context to Contoso Hotels"
$SetContext = Set-AzContext -Subscription "Contoso Hotels"
write-host "Context Set to $($SetContext.Subscription.Name)"
write-host "Now getting resources in $($SetContext.Subscription.Name)"
$Resources = Get-AzResource
write-host "Counted a total of $($Resources.Count) in $($SetContext.Subscription.Name)"
try
{
    While(($ContextSet -ne $currentSub) -or ($Count -ge 5))
    {
        write-host "`nSetting Context back to initial subscription $CurrentSub try #$($Count)" -ForegroundColor Cyan
        $SetContext = Set-AzContext -Subscription $CurrentSub
        $ContextSet = $SetContext.Subscription.Name
        write-host "`nGetting context after setting"
        write-host "Context set to $($ContextSet)"
        $Count++
    }
}
catch
{
    Write-Host "Failed to set context back to intial subscription $CurrentSub.  Please review!"
}

Write-Host "Complete`n" -ForegroundColor Green
```
![image](https://user-images.githubusercontent.com/13633751/92501507-84f04400-f1b3-11ea-92bc-add7f1b7f469.png)

**Comment by asears** [comment]
Also seeing this.  A couple scenarios.

1. Running first time doesn't set subscription.  Running second time does.
2. Running multiple times doesn't set subscription.

For scenario 2 which I experienced today.

I open Powershell, run Set-AzContext with either Subscription, SubscriptionId, SubscriptionName from a ps1 script with [CmdletBinding(SupportsShouldProcess)]
param()

Subscription not set properly to one identified.

I made change to the script to correctly set the subscription.

```powershell
Get-AzSubscription -SubscriptionName "My subscription" | Set-AzContext
```
```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     4.4.0      Az
```

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.17763.1432
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1432
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by JimGBritt** [comment]
@dingmeng-xue  as @asears mentions, if you update the Set Context lines to leverage a call to get the sub first, this problem gets resolved.  However, this would be a Get and a set every time. Slows down the process and also adds an additional ARM call every time.  Is it possible that the Set-AzContext (Select-AzSubscription) is timing out or failing to properly get the sub details on set?  I can adjust my scripts but it seems this issue should be resolved to ensure those that are leveraging the cmdlet are successful in setting the context.  What additional details can we pull to troubleshoot?

**Comment by asears** [comment]
This could be an issue with -Subscription alias parameter and having multiple "profiles" or context names for the same subscription.  Set-AzContext silently gives up and leaves as current?  

I had 3 different context names for the same subscription, with different email addresses (aliases), some with subscription ids included in the context name.

Unfortunately it seems as though Select-AzSubscription was a better method of selecting subscriptions than Set-AzContext, though PSScriptAnalyzer recommends against this.

Running Remove-AzContext on each of the subscription contexts for the same subscription name seemed to solve the issue.

Is there a debugging parameter or flag which can be enabled to trace Set-AzContext as to why it is selecting a certain path? 
I think that there needs to be explicit success or failure when using the -Subscription parameter with multiple contexts for the same subscription.

**Comment by JimGBritt** [comment]
@asears - I can no longer repro this after the latest version of Az Cmdlets.  Can you confirm as well on your side?  Heads up there was a big change in the way that az cmdlets handle auth, etc.  This completely broke scripts I had created that were using REST API Auth Tokens - I have remediated those and things are functioning.  However, my initial repro no longer repros at this point so I think this issue went away with the latest updates to the cmdlets.    If this is no longer happening to you, I'm inclined to close the bug out as I'm not getting traction otherwise and now I cannot repro,

```
$PSVersionTable


Name                           Value
----                           -----
PSVersion                      7.1.0-rc.2
PSEdition                      Core
GitCommitId                    7.1.0-rc.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

And it looks like I have a mix now but likely leveraging the latest
```
Get-Module -ListAvailable -Name Az


    Directory: C:\Users\jbritt\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     5.0.0                 Az                                  Core,Desk
Script     4.8.0                 Az                                  Core,Desk 

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     5.0.0                 Az                                  Core,Desk
Script     4.8.0                 Az                                  Core,Desk
Script     4.7.0                 Az                                  Core,Desk
```

**Comment by JimGBritt** [comment]
Appears to be resolved with the latest cmdlets.  Feel free to re-open but closing at this point.
