### ISSUE TITLE
Duplicate Subscriptions Returned from Get-AZSubscription

### ISSUE THREAD

**Issue by akarczag** [Azure/azure-powershell#12611]
I have access to two different tenants in AZ, one of which has subscriptions, and the other doesn't have any. When I run Get-AZSubscriptions, it appears that I have two of each subscription. This does not happen when I use the Azure REST API.

**Comment by ioamnesia** [comment]
I'm working with @akarczag on this as well. The issue only appears when connecting using access tokens. When using interactive authentication, it doesn't appear to happen.

**Comment by dingmeng-xue** [comment]
@akarczag , thanks for reporting. According to @ioamnesia 's comment, how did you get the access token?

**Comment by ioamnesia** [comment]
The access token was obtained using the device code OAuth flow with the scope https://management.core.windows.net/user_impersonation and clientid of an Azure App Registration created in the primary tenant. This matches the scope of the tokens issued and stored in the tokencache when authenticating interactively.

TenantA, our primary tenant, has a number of subscriptions. When we connect via auth token, a second tenant, TenantB, which has no Azure Subscriptions assigned, appears to have all the subscriptions from TenantA. It is possible to Set-AzContext -TenantId [TenantB Guid] -SubscriptionId [TenantA SubscriptionId] and the context reflects the mismatch. Once done, event though the context is TenantB, when querying for objects, it returns the objects from the TenantA subscription.

**Comment by dingmeng-xue** [comment]
@ioamnesia  and @akarczag , could you share which version of Az.Account you are using?

`Get-AzSubscription` fetches subscription tenant per tenant. So you can see all subscriptions from all tenants. The latest Az.Account can show home tenant and managedby tenant per subscription. Could you check and share more information if it still has problem.

**Comment by ioamnesia** [comment]
Here's the output - With false GUIDS and subscription names:

```
Name          Id                                   TenantId                             State
----          --                                   --------                             -----
SubscriptionA 2cbe5ae7-4940-4250-a48d-b414202af2f6 319e8cee-a8da-4796-bdf7-8a174fe1109d Enabled
SubscriptionB 3b839adc-5966-450f-8694-6125b6d72abc 319e8cee-a8da-4796-bdf7-8a174fe1109d Enabled
SubscriptionC 3b168a9d-e0d2-477a-942b-565dda4abd20 319e8cee-a8da-4796-bdf7-8a174fe1109d Enabled
SubscriptionA 2cbe5ae7-4940-4250-a48d-b414202af2f6 ae8d24ac-f1d3-4894-a33c-55f83bfcb7e8 Enabled
SubscriptionB 3b839adc-5966-450f-8694-6125b6d72abc ae8d24ac-f1d3-4894-a33c-55f83bfcb7e8 Enabled
SubscriptionC 3b168a9d-e0d2-477a-942b-565dda4abd20 ae8d24ac-f1d3-4894-a33c-55f83bfcb7e8 Enabled
```
We're using the Az.Accounts version 1.9.0

**Comment by dingmeng-xue** [comment]
@ioamnesia , please try to use Az.Accounts 1.9.2 which will show tenant type per subscription.

**Comment by mhintzke** [comment]
@dingmeng-xue @ioamnesia I am seeing this behavior still in 2.10.3. Our user's use grant flow authentication to mint a token for their admin and when performing `Get-AzSubscription` u sing `AccessToken` parameter they get back "duplicate" subscriptions. I used dotPeek to see what is going on and I can confirm that it appears the cmdlet simply fetches all tenants for the user (in this case there are 4) and then uses the same token to call `GET https://management.azure.com/subscriptions` for each tenant. This ends up looking like the subscriptions exist in all 4 tenants when they technically only exist in the primary tenant (as can be seen by the response to `GET https://management.azure.com/subscriptions?api-version=2022-12-01` if made in postman)

![image](https://github.com/Azure/azure-powershell/assets/8990993/07656f9c-4d94-448f-9e9b-89b870a641fc)

**Comment by dingmeng-xue** [comment]
@isra-fel ping.
