### ISSUE TITLE
New-AzImageBuilderTemplate needs to support to create template basing on imported json

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#12634]
## Description of the new feature

Azure CLI allows user to create image builder template basing on a local json file. Azure PowerShell needs to provide parity feature.

```
az image builder create -g my-group -n mytemplate --image-template filename
```

Example of json file is https://raw.githubusercontent.com/danielsollondon/azvmimagebuilder/master/quickquickstarts/0_Creating_a_Custom_Linux_Managed_Image/helloImageTemplateLinux.json

**Comment by danielsollondon** [comment]
@dcaro , @dingmeng-xue - is there any update on when this can be done?

**Comment by dingmeng-xue** [comment]
Hi @danielsollondon , we have no bandwidth to cover this one yet. Will keep you updated.

**Comment by wyunchi-ms** [comment]
Is `Type` and `apiVersion` necessary in json file? We don't support use api version from input. @danielsollondon

**Comment by danielsollondon** [comment]
@wyunchi-ms - Our RP requires these, how do you handle this with other RPs? We also support this with AZ CLI: https://docs.microsoft.com/en-us/cli/azure/image/builder?view=azure-cli-latest#az_image_builder_create
