### ISSUE TITLE
Update-AzCosmosDBAccount IpRule instead of IpRules 

### ISSUE THREAD

**Issue by PavanBN25** [Azure/azure-powershell#12655]
Reference: https://docs.microsoft.com/en-us/powershell/module/az.cosmosdb/update-azcosmosdbaccount?view=azps-4.5.0  

PS version -> 5.1 

The command Update-AzCosmosDBAccount throws error when running with below fields. 

Update-AzCosmosDBAccount
      -ResourceGroupName <String>
      -Name <String>
      [-DefaultConsistencyLevel <String>]
      [-EnableAutomaticFailover <Boolean>]
      [-EnableMultipleWriteLocations <Boolean>]
      [-EnableVirtualNetwork <Boolean>]
      [-IpRules <String[]>]
      [-MaxStalenessIntervalInSeconds <Int32>]
      [-MaxStalenessPrefix <Int32>]
      [-Tag <Hashtable>]
      [-VirtualNetworkRule <String[]>]
      [-VirtualNetworkRuleObject <PSVirtualNetworkRule[]>]
      [-DisableKeyBasedMetadataWriteAccess <Boolean>]
      [-PublicNetworkAccess <String>]
      [-KeyVaultKeyUri <String>]
      [-AsJob]
      [-DefaultProfile <IAzureContextContainer>]
      [-WhatIf]
      [-Confirm]
      [<CommonParameters>]

The IpRules field has to be IpRule instead. Is there any variance in the documentation or any difference between the two.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Using singular parameter name is our recommendation but is not hard rule. 

Service team, please help to look into it. `-VirtualNetworkRule` in this cmdlet is using singular format. We'd better make them consistent.

**Comment by MehaKaushik** [comment]
Thanks for pointing this out. The code indeed uses IpRule (see here https://github.com/Azure/azure-powershell/blob/99df761844c7055eb8ef590a1efcb8d99d43132a/src/CosmosDB/CosmosDB/CosmosDBAccount/NewOrUpdateAzCosmosDBAccount.cs#L43), but the doc here[https://docs.microsoft.com/en-us/powershell/module/az.cosmosdb/update-azcosmosdbaccount?view=azps-4.5.0] reads It as IpRules.   

I would update it in my next PR.

**Comment by MehaKaushik** [comment]
Will add the required change in this PR https://github.com/Azure/azure-powershell/pull/12814
