### ISSUE TITLE
Unable to run the script to take the backup

### ISSUE THREAD

**Issue by pkvk14** [Azure/azure-powershell#12675]
Hi Support,

I have 10 virtual machine in CSV file and i want to take the snapshot using power shell with workflow
```powershell
Workflow Test-Workflow
{
$users = import-csv 'D:\15-08-20\Startvm.csv'
foreach($user in $users)
{
$Subscriptionid =$users.Subscriptionid
$Name =$users.VMNAME
$ResourceGroupName = $users.RGN
$Location=$users.Location
$test=Get-azurermvm -Name $Name -ResourceGroupName $ResourceGroupName -Status
$VMNAME = Get-azurermvm -status -Name $Name -ResourceGroupName $ResourceGroupName 
$Status   = $VMNAME.Statuses[1].DisplayStatus
$VMOSDisk=(Get-AzureRmVM -Name $Name -ResourceGroupName $ResourceGroupName).StorageProfile.OsDisk.Name
$OsType=(Get-AzureRmVM -Name $Name -ResourceGroupName $ResourceGroupName).StorageProfile.OsDisk.OsType
$OsVersion=(Get-AzureRmVM -Name $Name -ResourceGroupName $ResourceGroupName).StorageProfile.ImageReference.Sku
$Disk = Get-AzureRmDisk -ResourceGroupName $ResourceGroupName -DiskName $VMOSDisk
$SnapshotConfig =  New-AzureRmSnapshotConfig -SourceUri $Disk.Id -CreateOption Copy -Location $Location
$Snapshot=New-AzureRmSnapshot -Snapshot $SnapshotConfig -SnapshotName $SnapshotName -ResourceGroupName $ResourceGroupName
 }
}
```

**Comment by msJinLei** [comment]
@pkvk14 Could you provide the following information to help me learn your issue?

## Environment data

Please run $PSVersionTable and paste the output in the below code block
     If running the Docker container image, indicate the tag of the image used and the version of Docker engine

```

```

## Module versions

Please run (Get-Module  -ListAvailable) and paste the output in the below code block

```powershell

```

## Debug output

Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block

```

```

## Error output

 Please run Resolve-AzError and paste the output in the below code block

```

```

**Comment by dingmeng-xue** [comment]
@pkvk14 , is there any update?

**Comment by dingmeng-xue** [comment]
Close this issue to inactivity. Please contact us if you have further feedback.
