### ISSUE TITLE
Wrong links in error message during deployment

### ISSUE THREAD

**Issue by psmanhas** [Azure/azure-powershell#12681]
I am posting this query on behalf of the customer. 

I received the following error message during deployment of a VM:

User failed validation to purchase resources. Error message: 'You have not accepted the legal terms on this subscription: 'xxx-xxx-xxx-xxx-xxx' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=862451 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=2110637. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms.

There are two links, one for az cli commands, one for powershell, but they are not in the right order. az cli link points to powershell docs, powershell link points to az cli docs.

Can you please make the necessary changes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dfc804-87d6-913a-27fe-a9446a04eb13
* Version Independent ID: bfcb97df-2055-9eca-7a93-60811136d8cd
* Content: [az vm image](https://docs.microsoft.com/en-us/cli/azure/vm/image?view=azure-cli-latest#az-vm-image-accept-terms)
* Content Source: [src/azure-cli/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by dingmeng-xue** [comment]
@psmanhas, how did customer deploy VM? We need to know which cmdlet they are using and debug message after setting `$DebugPreference="Continue"`.

**Comment by psmanhas** [comment]
@dingmeng-xue  Thank you for your response. I will re-direct the cx to this mentioned thread so that they can be direct contact with you and can get the required help.

Thanks

**Comment by dingmeng-xue** [comment]
@psmanhas , is there any update?

**Comment by psmanhas** [comment]
@dingmeng-xue I had redircted cx to this GitHub thread,Haven't got any update from their side as such for now.
