### ISSUE TITLE
$Resource.Properties.remoteDebuggingEnabled command changing value of previous execution

### ISSUE THREAD

**Issue by seunnuga93** [Azure/azure-powershell#12684]
## Description

I have a simple script to set $Resource.Properties.remoteDebuggingEnabled to true and false as need be (I had to simplify my script to get to the root problem) 

I noticed that when I run one command against a web app, it changes the value of the previous execution I ran. 

**For instance** 
- Remote debugging for Webapp A is set to true 
- When I run command to turn remote debugging for web app B to true it does that but sets remote debugging of Webapp A back to false which is quite strange 'cos I am not talking to WebApp A any longer. 

Sample script below. (Kindly run a repro)- create 5 web apps in a resource group

$resourceGroupName = "40-web"
$appServiceName = "seun1"
$Resource = Get-AzResource -ResourceGroupName $resourceGroupName -ResourceType Microsoft.Web/sites/config -ResourceName $appServiceName -ApiVersion "2018-02-01"
$Resource.Properties.remoteDebuggingEnabled = "True"
$Resource | Set-AzResource -ApiVersion "2018-02-01"     

$resourceGroupName = "40-web"
$appServiceName = "seun2"
$Resource = Get-AzResource -ResourceGroupName $resourceGroupName -ResourceType Microsoft.Web/sites/config -ResourceName $appServiceName -ApiVersion "2018-02-01"
$Resource.Properties.remoteDebuggingEnabled = "True"
$Resource | Set-AzResource -ApiVersion "2018-02-01" -Force  

$resourceGroupName = "40-web"
$appServiceName = "seun3"
$Resource = Get-AzResource -ResourceGroupName $resourceGroupName -ResourceType Microsoft.Web/sites/config -ResourceName $appServiceName -ApiVersion "2018-02-01"
$Resource.Properties.remoteDebuggingEnabled = "True"
$Resource | Set-AzResource -ApiVersion "2018-02-01" -Force  

$resourceGroupName = "40-web"
$appServiceName = "seun4"
$Resource = Get-AzResource -ResourceGroupName $resourceGroupName -ResourceType Microsoft.Web/sites/config -ResourceName $appServiceName -ApiVersion "2018-02-01"
$Resource.Properties.remoteDebuggingEnabled = "True"
$Resource | Set-AzResource -ApiVersion "2018-02-01" -Force  

$resourceGroupName = "40-web"
$appServiceName = "seun5"
$Resource = Get-AzResource -ResourceGroupName $resourceGroupName -ResourceType Microsoft.Web/sites/config -ResourceName $appServiceName -ApiVersion "2018-02-01"
$Resource.Properties.remoteDebuggingEnabled = "True"
$Resource | Set-AzResource -ApiVersion "2018-02-01" 

## Steps to reproduce
Sample script above. I initially had a for each loop to do the job but had to remove it to understand the problem after several hours. 

## Environment data

Name                           Value
----                           -----
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

## Module versions

It's a lot so I pasted the important ones.

Script     1.11.0     Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}
Script     1.5.1      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}

## Debug output

```

```

## Error output

No error for commands pasted

Kindly assist.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Could you clarify further about "When I run command to turn remote debugging for web app B to true it does that but sets remote debugging of Webapp A back to false which is quite strange 'cos I am not talking to WebApp A any longer." My understanding is scripts were executed in sequence. How could you see Webapp A back to false?

**Comment by seunnuga93** [comment]
Yes, the scripts are executed in sequence but there is flip switch happening
When I set remote debugging of App A to true it switches remote debugging state of another app from false to true and sometimes the command does not take effect at all if I run all the 5 commands at once on PowerShell 

**Currently running a Demo with all my webapps remote debugging set to False** 
Web app Seun 1
 
![image](https://user-images.githubusercontent.com/6573248/90492657-55f92c00-e139-11ea-84ae-4efbbf7b65d6.png)

Web app Seun 2
 
![image](https://user-images.githubusercontent.com/6573248/90492675-5b567680-e139-11ea-9865-5c4721d94194.png)


Web app Seun 3
 
![image](https://user-images.githubusercontent.com/6573248/90492689-60b3c100-e139-11ea-9232-ce35cf46501a.png)


Web app Seun 4
 
![image](https://user-images.githubusercontent.com/6573248/90492711-66110b80-e139-11ea-993d-32bf978f81bd.png)


Web app Seun 5
 
![image](https://user-images.githubusercontent.com/6573248/90492723-69a49280-e139-11ea-9607-66b0759f3b40.png)


**I ran the below powershell script therafter at once.** 

$resourceGroupName = "40-web"
$appServiceName = "seun1"
$Resource = Get-AzResource -ResourceGroupName $resourceGroupName -ResourceType Microsoft.Web/sites/config -ResourceName $appServiceName -ApiVersion "2018-02-01"
$Resource.Properties.remoteDebuggingEnabled = "True"
$Resource | Set-AzResource -ApiVersion "2018-02-01" -Force      

$resourceGroupName = "40-web"
$appServiceName = "seun2"
$Resource = Get-AzResource -ResourceGroupName $resourceGroupName -ResourceType Microsoft.Web/sites/config -ResourceName $appServiceName -ApiVersion "2018-02-01"
$Resource.Properties.remoteDebuggingEnabled = "True"
$Resource | Set-AzResource -ApiVersion "2018-02-01" -Force  

$resourceGroupName = "40-web"
$appServiceName = "seun3"
$Resource = Get-AzResource -ResourceGroupName $resourceGroupName -ResourceType Microsoft.Web/sites/config -ResourceName $appServiceName -ApiVersion "2018-02-01"
$Resource.Properties.remoteDebuggingEnabled = "True"
$Resource | Set-AzResource -ApiVersion "2018-02-01" -Force  

$resourceGroupName = "40-web"
$appServiceName = "seun4"
$Resource = Get-AzResource -ResourceGroupName $resourceGroupName -ResourceType Microsoft.Web/sites/config -ResourceName $appServiceName -ApiVersion "2018-02-01"
$Resource.Properties.remoteDebuggingEnabled = "True"
$Resource | Set-AzResource -ApiVersion "2018-02-01" -Force  

$resourceGroupName = "40-web"
$appServiceName = "seun5"
$Resource = Get-AzResource -ResourceGroupName $resourceGroupName -ResourceType Microsoft.Web/sites/config -ResourceName $appServiceName -ApiVersion "2018-02-01"
$Resource.Properties.remoteDebuggingEnabled = "True"
$Resource | Set-AzResource -ApiVersion "2018-02-01" -Force 


**Output of execution**

**Name              : seun1**
ResourceId        : /subscriptions/ec593a48-6125-4a71-984e-3a8ced1a59ac/resourceGroups/40-web/providers/Microsoft.Web/sites/seun1
ResourceName      : seun1
ResourceType      : Microsoft.Web/sites
ResourceGroupName : 40-web
Location          : Central US
SubscriptionId    : ec593a48-6125-4a71-984e-3a8ced1a59ac
Tags              : {}
Properties        : @{numberOfWorkers=1; defaultDocuments=System.Object[]; netFrameworkVersion=v4.0; phpVersion=; pythonVersion=; nodeVersion=; powerShellVersion=; linuxFxVersion=; windowsFxVersion=; requestTracingEnabled=False;
                    **remoteDebuggingEnabled=True**; remoteDebuggingVersion=VS2019; httpLoggingEnabled=False; azureMonitorLogCategories=; acrUseManagedIdentityCreds=False; acrUserManagedIdentityID=; logsDirectorySizeLimit=35;
                    detailedErrorLoggingEnabled=False; publishingUsername=$seun1; publishingPassword=; appSettings=; azureStorageAccounts=; metadata=; connectionStrings=; machineKey=; handlerMappings=; documentRoot=; scmType=None;
                    use32BitWorkerProcess=True; webSocketsEnabled=False; alwaysOn=False; javaVersion=; javaContainer=; javaContainerVersion=; appCommandLine=; managedPipelineMode=Integrated; virtualApplications=System.Object[];
                    winAuthAdminState=0; winAuthTenantState=0; customAppPoolIdentityAdminState=False; customAppPoolIdentityTenantState=False; runtimeADUser=; runtimeADUserPassword=; loadBalancing=LeastRequests;
                    routingRules=System.Object[]; experiments=; limits=; autoHealEnabled=False; autoHealRules=; tracingOptions=; vnetName=; vnetRouteAllEnabled=False; siteAuthEnabled=False; siteAuthSettings=; cors=; push=;
                    apiDefinition=; apiManagementConfig=; autoSwapSlotName=; localMySqlEnabled=False; managedServiceIdentityId=; xManagedServiceIdentityId=; ipSecurityRestrictions=; scmIpSecurityRestrictions=;
                    scmIpSecurityRestrictionsUseMain=False; http20Enabled=False; minTlsVersion=1.2; scmMinTlsVersion=1.0; ftpsState=AllAllowed; reservedInstanceCount=0; preWarmedInstanceCount=; functionAppScaleLimit=0;
                    healthCheckPath=; fileChangeAuditEnabled=False; functionsRuntimeScaleMonitoringEnabled=False; websiteTimeZone=; minimumElasticInstanceCount=0}

**Name              : seun2**
ResourceId        : /subscriptions/ec593a48-6125-4a71-984e-3a8ced1a59ac/resourceGroups/40-web/providers/Microsoft.Web/sites/seun2
ResourceName      : seun2
ResourceType      : Microsoft.Web/sites
ResourceGroupName : 40-web
Location          : Central US
SubscriptionId    : ec593a48-6125-4a71-984e-3a8ced1a59ac
Tags              : {}
Properties        : @{numberOfWorkers=1; defaultDocuments=System.Object[]; netFrameworkVersion=v4.0; phpVersion=; pythonVersion=; nodeVersion=; powerShellVersion=; linuxFxVersion=; windowsFxVersion=; requestTracingEnabled=False;
                    **remoteDebuggingEnabled=True**; remoteDebuggingVersion=VS2019; httpLoggingEnabled=False; azureMonitorLogCategories=; acrUseManagedIdentityCreds=False; acrUserManagedIdentityID=; logsDirectorySizeLimit=35;
                    detailedErrorLoggingEnabled=False; publishingUsername=$seun2; publishingPassword=; appSettings=; azureStorageAccounts=; metadata=; connectionStrings=; machineKey=; handlerMappings=; documentRoot=; scmType=None;
                    use32BitWorkerProcess=True; webSocketsEnabled=False; alwaysOn=False; javaVersion=; javaContainer=; javaContainerVersion=; appCommandLine=; managedPipelineMode=Integrated; virtualApplications=System.Object[];
                    winAuthAdminState=0; winAuthTenantState=0; customAppPoolIdentityAdminState=False; customAppPoolIdentityTenantState=False; runtimeADUser=; runtimeADUserPassword=; loadBalancing=LeastRequests;
                    routingRules=System.Object[]; experiments=; limits=; autoHealEnabled=False; autoHealRules=; tracingOptions=; vnetName=; vnetRouteAllEnabled=False; siteAuthEnabled=False; siteAuthSettings=; cors=; push=;
                    apiDefinition=; apiManagementConfig=; autoSwapSlotName=; localMySqlEnabled=False; managedServiceIdentityId=; xManagedServiceIdentityId=; ipSecurityRestrictions=; scmIpSecurityRestrictions=;
                    scmIpSecurityRestrictionsUseMain=False; http20Enabled=False; minTlsVersion=1.2; scmMinTlsVersion=1.0; ftpsState=AllAllowed; reservedInstanceCount=0; preWarmedInstanceCount=; functionAppScaleLimit=0;
                    healthCheckPath=; fileChangeAuditEnabled=False; functionsRuntimeScaleMonitoringEnabled=False; websiteTimeZone=; minimumElasticInstanceCount=0}

**Name              : seun3**
ResourceId        : /subscriptions/ec593a48-6125-4a71-984e-3a8ced1a59ac/resourceGroups/40-web/providers/Microsoft.Web/sites/seun3
ResourceName      : seun3
ResourceType      : Microsoft.Web/sites
ResourceGroupName : 40-web
Location          : Central US
SubscriptionId    : ec593a48-6125-4a71-984e-3a8ced1a59ac
Tags              : {}
Properties        : @{numberOfWorkers=1; defaultDocuments=System.Object[]; netFrameworkVersion=v4.0; phpVersion=; pythonVersion=; nodeVersion=; powerShellVersion=; linuxFxVersion=; windowsFxVersion=; requestTracingEnabled=False;
                    **remoteDebuggingEnabled=True**; remoteDebuggingVersion=VS2019; httpLoggingEnabled=False; azureMonitorLogCategories=; acrUseManagedIdentityCreds=False; acrUserManagedIdentityID=; logsDirectorySizeLimit=35;
                    detailedErrorLoggingEnabled=False; publishingUsername=$seun3; publishingPassword=; appSettings=; azureStorageAccounts=; metadata=; connectionStrings=; machineKey=; handlerMappings=; documentRoot=; scmType=None;
                    use32BitWorkerProcess=True; webSocketsEnabled=False; alwaysOn=False; javaVersion=; javaContainer=; javaContainerVersion=; appCommandLine=; managedPipelineMode=Integrated; virtualApplications=System.Object[];
                    winAuthAdminState=0; winAuthTenantState=0; customAppPoolIdentityAdminState=False; customAppPoolIdentityTenantState=False; runtimeADUser=; runtimeADUserPassword=; loadBalancing=LeastRequests;
                    routingRules=System.Object[]; experiments=; limits=; autoHealEnabled=False; autoHealRules=; tracingOptions=; vnetName=; vnetRouteAllEnabled=False; siteAuthEnabled=False; siteAuthSettings=; cors=; push=;
                    apiDefinition=; apiManagementConfig=; autoSwapSlotName=; localMySqlEnabled=False; managedServiceIdentityId=; xManagedServiceIdentityId=; ipSecurityRestrictions=; scmIpSecurityRestrictions=;
                    scmIpSecurityRestrictionsUseMain=False; http20Enabled=False; minTlsVersion=1.2; scmMinTlsVersion=1.0; ftpsState=AllAllowed; reservedInstanceCount=0; preWarmedInstanceCount=; functionAppScaleLimit=0;
                    healthCheckPath=; fileChangeAuditEnabled=False; functionsRuntimeScaleMonitoringEnabled=False; websiteTimeZone=; minimumElasticInstanceCount=0}

**Name              : seun4**
ResourceId        : /subscriptions/ec593a48-6125-4a71-984e-3a8ced1a59ac/resourceGroups/40-web/providers/Microsoft.Web/sites/seun4
ResourceName      : seun4
ResourceType      : Microsoft.Web/sites
ResourceGroupName : 40-web
Location          : Central US
SubscriptionId    : ec593a48-6125-4a71-984e-3a8ced1a59ac
Tags              : {}
Properties        : @{numberOfWorkers=1; defaultDocuments=System.Object[]; netFrameworkVersion=v4.0; phpVersion=; pythonVersion=; nodeVersion=; powerShellVersion=; linuxFxVersion=; windowsFxVersion=; requestTracingEnabled=False;
                    **remoteDebuggingEnabled=True**; remoteDebuggingVersion=VS2019; httpLoggingEnabled=False; azureMonitorLogCategories=; acrUseManagedIdentityCreds=False; acrUserManagedIdentityID=; logsDirectorySizeLimit=35;
                    detailedErrorLoggingEnabled=False; publishingUsername=$seun4; publishingPassword=; appSettings=; azureStorageAccounts=; metadata=; connectionStrings=; machineKey=; handlerMappings=; documentRoot=; scmType=None;
                    use32BitWorkerProcess=True; webSocketsEnabled=False; alwaysOn=False; javaVersion=; javaContainer=; javaContainerVersion=; appCommandLine=; managedPipelineMode=Integrated; virtualApplications=System.Object[];
                    winAuthAdminState=0; winAuthTenantState=0; customAppPoolIdentityAdminState=False; customAppPoolIdentityTenantState=False; runtimeADUser=; runtimeADUserPassword=; loadBalancing=LeastRequests;
                    routingRules=System.Object[]; experiments=; limits=; autoHealEnabled=False; autoHealRules=; tracingOptions=; vnetName=; vnetRouteAllEnabled=False; siteAuthEnabled=False; siteAuthSettings=; cors=; push=;
                    apiDefinition=; apiManagementConfig=; autoSwapSlotName=; localMySqlEnabled=False; managedServiceIdentityId=; xManagedServiceIdentityId=; ipSecurityRestrictions=; scmIpSecurityRestrictions=;
                    scmIpSecurityRestrictionsUseMain=False; http20Enabled=False; minTlsVersion=1.2; scmMinTlsVersion=1.0; ftpsState=AllAllowed; reservedInstanceCount=0; preWarmedInstanceCount=; functionAppScaleLimit=0;
                    healthCheckPath=; fileChangeAuditEnabled=False; functionsRuntimeScaleMonitoringEnabled=False; websiteTimeZone=; minimumElasticInstanceCount=0}

**Name              : seun5**
ResourceId        : /subscriptions/ec593a48-6125-4a71-984e-3a8ced1a59ac/resourceGroups/40-web/providers/Microsoft.Web/sites/seun5
ResourceName      : seun5
ResourceType      : Microsoft.Web/sites
ResourceGroupName : 40-web
Location          : Central US
SubscriptionId    : ec593a48-6125-4a71-984e-3a8ced1a59ac
Tags              : {}
Properties        : @{numberOfWorkers=1; defaultDocuments=System.Object[]; netFrameworkVersion=v4.0; phpVersion=; pythonVersion=; nodeVersion=; powerShellVersion=; linuxFxVersion=; windowsFxVersion=; requestTracingEnabled=False;
                    **remoteDebuggingEnabled=True;** remoteDebuggingVersion=VS2019; httpLoggingEnabled=False; azureMonitorLogCategories=; acrUseManagedIdentityCreds=False; acrUserManagedIdentityID=; logsDirectorySizeLimit=35;
                    detailedErrorLoggingEnabled=False; publishingUsername=$seun5; publishingPassword=; appSettings=; azureStorageAccounts=; metadata=; connectionStrings=; machineKey=; handlerMappings=; documentRoot=; scmType=None;
                    use32BitWorkerProcess=True; webSocketsEnabled=False; alwaysOn=False; javaVersion=; javaContainer=; javaContainerVersion=; appCommandLine=; managedPipelineMode=Integrated; virtualApplications=System.Object[];
                    winAuthAdminState=0; winAuthTenantState=0; customAppPoolIdentityAdminState=False; customAppPoolIdentityTenantState=False; runtimeADUser=; runtimeADUserPassword=; loadBalancing=LeastRequests;
                    routingRules=System.Object[]; experiments=; limits=; autoHealEnabled=False; autoHealRules=; tracingOptions=; vnetName=; vnetRouteAllEnabled=False; siteAuthEnabled=False; siteAuthSettings=; cors=; push=;
                    apiDefinition=; apiManagementConfig=; autoSwapSlotName=; localMySqlEnabled=False; managedServiceIdentityId=; xManagedServiceIdentityId=; ipSecurityRestrictions=; scmIpSecurityRestrictions=;
                    scmIpSecurityRestrictionsUseMain=False; http20Enabled=False; minTlsVersion=1.2; scmMinTlsVersion=1.0; ftpsState=AllAllowed; reservedInstanceCount=0; preWarmedInstanceCount=; functionAppScaleLimit=0;
                    healthCheckPath=; fileChangeAuditEnabled=False; functionsRuntimeScaleMonitoringEnabled=False; websiteTimeZone=; minimumElasticInstanceCount=0}

**After state of apps.**
Web App seun 1
 
![image](https://user-images.githubusercontent.com/6573248/90492964-b38d7880-e139-11ea-9304-bd6f26777293.png)


Web App seun 2
 
![image](https://user-images.githubusercontent.com/6573248/90492973-b720ff80-e139-11ea-8e4d-dbf6f06f7d79.png)


Web App seun 3
 
![image](https://user-images.githubusercontent.com/6573248/90492992-bb4d1d00-e139-11ea-8a08-d311689fd9a7.png)

Web App seun 4
 
![image](https://user-images.githubusercontent.com/6573248/90493007-c011d100-e139-11ea-81b7-8c9076bbd250.png)


**Web App seun 5**
 
![image](https://user-images.githubusercontent.com/6573248/90493019-c43dee80-e139-11ea-9175-81bc8775d458.png)


**From this demo, only Web app 5 (Seun 5) changed in the portal to True/On even though the PowerShell output says otherwise**
Remote debugging did not change on the portal for the other 4 apps.

**Comment by dingmeng-xue** [comment]
WebApp team, please help to look into this issue. The response from ARM is correct but status from portal is different.

**Comment by panchagnula** [comment]
@seunnuga93 this seems like a portal bug rather than Powershell - I would recommend opening a support ticket on portal for this - please include the output of the Site API. One way to validate this on browser navigate to resources.azure.com
from the left menu select the site in the right side you will the API GET call -> verify the value of the "remoteDebuggingEnabled" property value & check if this matches what you see from Powershell execution & compare to portal as well. Thanks!

**Comment by seunnuga93** [comment]
@panchagnula Yes, I agree with you being a portal issue.

Resources.azure.com does not show much as the values are all showing as null for both true and false states.
![image](https://user-images.githubusercontent.com/6573248/90563472-c8025d00-e19b-11ea-9c32-635cf56c4c62.png)

@dingmeng-xue I think I found the problem. More than one web apps in the same resource groups are not allowed to have remote debugging set to true (not sure why). I did it manually from the portal and I saw that if turn on remote debugging for one web app, it turns off remote debugging for any other web app that has remote debugging turned on in the same resource group.  

However, web apps in different resource groups are allowed to have remote debugging set to true. 

I will raise a collaboration with the webapp team regarding this portal behavior to understand more. 

Thanks for your help.

**Comment by seunnuga93** [comment]
**update**
Information reaching me is that there is a remote debugging connection limit per app service plans which is why there is a flip switch when we exceed the maximum allowed connections 
![image](https://user-images.githubusercontent.com/6573248/90604709-29a2e580-e1f5-11ea-82d5-c88942bf87d3.png)
https://azure.microsoft.com/en-us/blog/introduction-to-remote-debugging-on-azure-web-sites/

Closing issue. Thanks.
