### ISSUE TITLE
Set-AzStorageBlobContent Never completes and never errors

### ISSUE THREAD

**Issue by bobbytreed** [Azure/azure-powershell#12694]
2.4.0  version of AzStorage

Uploading 2400 files stalls and never completes.  The Write-Progress just shows the last file over and over again with no way to determine what is happening or failing. 

az copy is much slower and shows no progress at all. 

111 activities not shown...

It sits there indefinitely without completing. (I waited 2 hours).

Killing it and then testing, I can see that every file was successfully uploaded to azure-blob storage, so I don't know why it hangs forever if the copy was complete.

**Comment by blueww** [comment]
@bobbytreed 

Would you please help to give more details for the issue, so we can try to repro and investigate it.

1. The repro script (hide credential if any)
2. Powershell version: run "$PSVersionTable" and show the result
3. The upload file size? Are they big file or small files?
4. If you can share your storage account name, test time, and the hang file name, I can try to search related server log, and see if any clu.
4. Please charity what do you mean "az copy is much slower and shows no progress at all." and "111 activities not shown". If you can share the storage account/time to run AzCopy, I might can search the server log to see how it works.

**Comment by blueww** [comment]
@bobbytreed

Not receive your responds for a long time.
So I close this issue.
Feel free to contact us again if need any further assistance.

**Comment by gsscoder** [comment]
Hello, I've the same problem. Everything worked fine, but these day `Set-AzStorageBlobContent` is unable to complete its operation _without signaling errors_ (stucks on **Progress 0%**).

This is the part of code in question:
```powershell
$context = New-AzStorageContext $StorageName -StorageAccountKey $Key -ErrorAction SilentlyContinue
Set-AzStorageBlobContent -Context $context -Container 'spfx' `
   -File $path -Blob "$Package/v$PackageVersion/$([Path]::GetFileName($path))" `
   -Force
```

Do you need any extra information to help me?

Thank you,
Giacomo S. S.

**Comment by blueww** [comment]
@gsscoder 

We will need some information to investiaget it:
1. Az.Storage version (Get-module)
2. OS/Powershell version ($PSVersionTable)
3. Debug log
4. If debug log doesn't contain following information ,please also give them: Storage Account Name,  Running time (UTC), Container/Blob name.

**Comment by stefiix92** [comment]
Hello, the same occurred for me, the details are:

1. 2.3.0
2. 5.1
3. no output

note here: when running powershell as Administrator, it works. Somehow it works also from Jenkins, but only from already existing job (the same azure storage account).

**Comment by oleksabor** [comment]
The problem was with the wrong storage account name value in my case.

I've used guid found somewhere in the Azure Portal url.  

However no error is shown in such case. The only one thing I can see is progress bar displayed by a command
![image](https://user-images.githubusercontent.com/16188507/108205674-10d8a580-712e-11eb-8f6c-dd7af65b47f3.png)


I've tried with `-debug` switch and then got the error like 
> Set-AzStorageBlobContent: No such host is known. (guidvaluehere.blob.core.windows.net:443)

**Comment by blueww** [comment]
@oleksabor 

When the account name is not correct, the blob endpoint Uri is not accessible.
For data transfer stability, we will retry on temperate network issue, and the wrong Uri behavior just same as network has issue, so will retry on it. 
If you wait long enough (like 15 mins), the transfer will fail.

for the error `No such host is known. (guidvaluehere.blob.core.windows.net:443)`， it also indicate the blob endpoint Uri is no accessible.

**Comment by oleksabor** [comment]
Thank you explaining me how it works. The account name was fixed and `Set-AzStorageBlobContent` works fine.
I'm just kindly ask you to check one more thing.

I've tried both `-ClientTimeoutPerRequest 60 -ServerTimeoutPerRequest 60` trying to find a reason. But it has no impact for the wrong account name case. The `Set-AzStorageBlobContent` execition taken more than 60 seconds for sure.

Is it possible to reduce the wait period in such case ? I'd like to get error `No such host is known`  immediately for wrong account name spelled rather than waiting for 15 minutes.

**Comment by blueww** [comment]
`-ClientTimeoutPerRequest 60 -ServerTimeoutPerRequest 60` are for single request, as there are retry logic, and will wait between each retry , so it can't control the whole time for fail fast.

You might can ping the blob endpoint before upload blob, and see if the blob endpoint is accessible.

**Comment by gsscoder** [comment]
@blueww at the end I discovered that I get no error when connecting to non existent resource. So I started testing the name with `Get-AzResource`.

Thanks, sorry for late comment
