### ISSUE TITLE
Consuming local SDK in RecoveryServices.Backup project

### ISSUE THREAD

**Issue by hiaga** [Azure/azure-powershell#12690]
## Description
I have to consume locally generated .NET SDK DLL files in the RecoveryServices.Backup PowerShell project. I'm working on DSMove feature for AzBackup and there is a bug in SDK so we want to test it locally before publishing the SDK for PS consumption.

Currently, we import the SDK Nuget package in the .csproj like below:
**Project Sdk="Microsoft.NET.Sdk"
PackageReference Include="Microsoft.Azure.Management.RecoveryServices.Backup" Version="4.1.1-preview"**

is there a way we can achieve this? Please suggest the best options here.

**Comment by dingmeng-xue** [comment]
Hi Hiaga, you can do that via below steps

1. Sign a new version of backup sdk but not publish it for example, 4.1.2-preview
2. Then copy this file to tools/LocalFeed. Restart your product and file under local feed will be installed to your local nuget repo
3.  change your csproj to consume 4.1.2-preview

**Comment by hiaga** [comment]
Hi @dingmeng-xue  this would need the changes in the SDK repository globally, but the requirement here is to pull the SDK code changes in PowerShell from the SDK DLLs generated locally form the SDK code. is that possible?

**Comment by hiaga** [comment]
Found the solution. Local SDK DLLs can be consumed with below approach:
<ItemGroup>
<Reference Include="Microsoft.Azure.Management.RecoveryServices.Backup">
		<HintPath>..\SDKDirect\Microsoft.Azure.Management.RecoveryServices.Backup.dll</HintPath>
</Reference>
</ItemGroup>

**Comment by hiaga** [comment]
Closing this issue.
