### ISSUE TITLE
Get-AzAutomationJob returns JArray for array parameters

### ISSUE THREAD

**Issue by AWahlqvist** [Azure/azure-powershell#12702]
## Description

When using Get-AzAutomationJob to return information about a automation job the information that used to be available in the JobParameters property is now gone for array-parameters (of the runbook for that job).

Turns out the type has changed to JArray in the latest version. Suspecting this is a mistake/bug?

## Steps to reproduce

1. Create a runbook that accepts an array-parameter
2. Start the job and post an array to the parameter
3. Fetch the job details using $JobInformation=Get-AzAutomationJob <parameters>

Check the jobparameters, the array will now "look empty" in the PowerShell console (no values/{}).

$JobInformation.JobParameters["parameter_name"].GetType()
 returns:

```
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    JArray                                   Newtonsoft.Json.Linq.JContainer
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Tested with the latest Az module, version 1.3.7 of Az.Automation. Not sure if this problem exists in more places, but this was discovered by our tests when trying to update the module. This worked fine in Az.Automation 1.3.4.

**Comment by dingmeng-xue** [comment]
It is due to below code that deserialized response value directly. The input is a string array. 
https://github.com/Azure/azure-powershell/blob/7d35885ba61f8d1510483f364ae7a5f7529011b4/src/Automation/Automation/Common/PowershellJsonConverter.cs#L47

This is introduced by fix on #11504.

**Comment by cgontario** [comment]
I'm seeing this when using Get-AzAutomationVariable as well. Scripts we use to manage configuration data as Automation Variables depended on the previous behaviour where you could round-trip a PSCustomObject.

Microsoft's documentation suggests storing complex objects in Automation Variables: https://docs.microsoft.com/en-us/powershell/module/az.automation/new-azautomationvariable?view=azps-4.7.0#example-2--create-a-variable-with-a-complex-value, and I assume this is so we can round-trip them in scripts and Runbooks. Hopefully this is fixed soon.

```
PS>$test = [PSCustomObject]@{Foo="foo";Bar=@(1,2,3)}
PS>$test.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    PSCustomObject                           System.Object

PS>New-AzAutomationVariable -ResourceGroupName "rg" -Name "test" -AutomationAccountName "aa" -Encrypted $false -Value $test

Value                 : {CliXml}
Encrypted             : False
ResourceGroupName     : rg
AutomationAccountName : aa
Name                  : test
CreationTime          : 2020-10-05 2:50:27 PM -04:00
LastModifiedTime      : 2020-10-05 2:50:27 PM -04:00
Description           :

PS>$v = Get-AzAutomationVariable -ResourceGroupName "rg" -Name "test" -AutomationAccountName "aa"
PS>$v.Value.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    JObject                                  Newtonsoft.Json.Linq.JContainer

PS>$v.Value

HasValues    : False
Type         : String
Parent       : {}
Root         : {CliXml}
Next         :
Previous     :
Path         : CliXml
First        :
Last         :
LineNumber   : 0
LinePosition : 0

```

In Windows PowerShell using AzureRM this still works as expected:

```
PS>$test = [PSCustomObject]@{Foo="foo";Bar=@(1,2,3)}
PS>$test.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    PSCustomObject                           System.Object

PS>New-AzureRmAutomationVariable -ResourceGroupName "rg" -Name "test" -AutomationAccountName "aa" -Encrypted $false -Value $test

Value                 : @{Foo=foo; Bar=System.Object[]}
Encrypted             : False
ResourceGroupName     : rg
AutomationAccountName : aa
Name                  : test
CreationTime          : 2020-10-05 3:03:15 PM -04:00
LastModifiedTime      : 2020-10-05 3:03:15 PM -04:00
Description           :

PS>$v= Get-AzureRmAutomationVariable -ResourceGroupName "rg" -Name "test" -AutomationAccountName "aa"
PS>$v.Value.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    PSCustomObject                           System.Object

PS>$v.Value

Foo Bar
--- ---
foo {1, 2, 3}
```

**Comment by vikram-m** [comment]
Thanks for the details, product team is aware of this issue and looking into it.

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.

**Comment by jaspkaur28** [comment]
We've picked this up as an improvement area. Please expect an update to it by CY2021 Q1.
