### ISSUE TITLE
Get-AzureStorageTable & Get-AzureStorageContainer not respecting -ErrorAction

### ISSUE THREAD

**Issue by shiningdragon** [Azure/azure-powershell#1270]
Get-AzureStorageContainer -Name 'blah' -Context $myContext -ErrorAction SilentlyContinue

and 
Get-AzureStorageTable -Name 'blah' -Context $myContext -ErrorAction SilentlyContinue

both throw an error when the resource doesnt exist - error should be suppressed - this was working in 0.9.8

**Comment by markcowl** [comment]
closing as duplicate of #1135
