### ISSUE TITLE
New-AzFunctionApp doesn't respect DisableApplicationInsights switch

### ISSUE THREAD

**Issue by veccsolutions** [Azure/azure-powershell#12728]
When using the `New-AzFunctionApp` it always creates an Application Insights resource whether the `DisableApplicationInsights` switch is specified or not. The following is an example:

```powershell
$prefix = "edsteststuff"
New-AzResourceGroup -Name $prefix -Location "westus2"
New-AzStorageAccount -ResourceGroupName $prefix -Name "${prefix}storage" -Location "westus2" -Sku "Standard_LRS" -EnableHttpsTrafficOnly $true
New-AzFunctionApp -Location "westus2" -ResourceGroupName $prefix -Name "${prefix}testfunction" -Runtime "dotnet" -StorageAccountName "${prefix}storage" -DisableApplicationInsights
```

![image](https://user-images.githubusercontent.com/4001449/90945898-2b330000-e3e5-11ea-98a4-0251abd1cb02.png)

I would have expected it to not have created the Application Insights resource.

**Comment by Francisco-Gamino** [comment]
Hi @veccsolutions -- Thanks for reporting this issue. Marking this for next milestone.

**Comment by aaltotsky** [comment]
I have the same issue. The DisableApplicationInsights parameter is not working.

**Comment by omerzubair** [comment]
I have the same issue. The DisableApplicationInsights parameter is not working.

**Comment by Francisco-Gamino** [comment]
This issue is fixed in the latest version of Az.Functions (https://www.powershellgallery.com/packages/Az.Functions/2.0.0). Please download the latest version of the Az module and give it a try.

**Comment by omerzubair** [comment]
just updated to Az.Functions/2.0.0 
Now the existing code (which was working) is error-ing out.
" DotNet' function apps, the runtime version is specified by the **FunctionsVersion** parameter. Please specify this value and try again"

and i checked the doco and there are no values specified for this prameter. can you help please.

https://docs.microsoft.com/en-us/powershell/module/az.functions/new-azfunctionapp?view=azps-5.0.0

**Comment by omerzubair** [comment]
> just updated to Az.Functions/2.0.0
> Now the existing code (which was working) is error-ing out.
> " DotNet' function apps, the runtime version is specified by the **FunctionsVersion** parameter. Please specify this value and try again"
> 
> and i checked the doco and there are no values specified for this prameter. can you help please.
> 
> https://docs.microsoft.com/en-us/powershell/module/az.functions/new-azfunctionapp?view=azps-5.0.0

I added -FunctionsVersion 3 and it worked. not sure if that is correct

**Comment by omerzubair** [comment]
the switch DisableApplicationInsights  is working now.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed in Az.Functions version 2.0.0 (https://www.powershellgallery.com/packages/Az.Functions/2.0.0).

cc: @stefanushinardi @anirudhgarg
