### ISSUE TITLE
Error received when using  Set-AzDataLakeStoreItemAclEntry to add acl for a service principal 

### ISSUE THREAD

**Issue by FuntestechGithub** [Azure/azure-powershell#12729]
## Description
    I am trying to use Set-AzDataLakeStoreItemAclEntry to set acl for a service principal. I can successfully add the acl to the service principal when using "User" as AclType. 

However as result, icon in Access page on Azure Portal will look like ![image](https://user-images.githubusercontent.com/53668234/90960522-5f4b0700-e45f-11ea-8575-5b15180395fc.png) instead of 
![image](https://user-images.githubusercontent.com/53668234/90960526-683bd880-e45f-11ea-9f19-4007d2b0c74f.png).  As icon mismatchs, I am wondering if I shall use "Other" as the type. When I tried to use "Other" as AclType (rest parameters values stay the same), I received follow error:
`Set-AzDataLakeStoreItemAclEntry : Error in modifying ACL entries mask:SPNObjectID:rwx for path
 /FolderPath.
Operation: MODIFYACLENTRIES failed with HttpStatus:Forbidden  RemoteException: AccessControlException MODIFYACLENTRIES
failed with error 0x83090c53 (Forbidden. ACL entry is invalid.). [94c1a884-6748-47b9-a091-d59cce4cf2c9] failed with err
or 0x83090c53 (Forbidden. ACL entry is invalid.). [94c1a884-6748-47b9-a091-d59cce4cf2c9][2020-08-20T22:15:32.3366984-07
:00] JavaClassName: org.apache.hadoop.security.AccessControlException.
Last encountered exception thrown after 1 tries. [HTTP Forbidden ( AccessControlException  MODIFYACLENTRIES failed with
 error 0x83090c53 (Forbidden. ACL entry is invalid.). [94c1a884-6748-47b9-a091-d59cce4cf2c9] failed with error 0x83090c
53 (Forbidden. ACL entry is invalid.). [94c1a884-6748-47b9-a091-d59cce4cf2c9][2020-08-20T22:15:32.3366984-07:00] JavaCl
assName: org.apache.hadoop.security.AccessControlException ]
[ServerRequestId:94c1a884-6748-47b9-a091-d59cce4cf2c9]`

## Steps to reproduce

Everytime when run Set-AzDataLakeStoreItemAclEntry -Account DLAccount -Path /FolderPath -AceType Other -Id SPObjectID  -Permissions All

## Environment data

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

## Module versions

Directory: C:\Users\XXX\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     1.9.2                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection,…
Script     1.1.1                 Az.Advisor                          Core,Desk {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Disable-AzAdviso…
Script     1.2.0                 Az.Aks                              Core,Desk {Get-AzAksCluster, New-AzAksCluster, Remove-AzAksCluster, Import-AzAksCredenti…
Script     1.1.4                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnal…
Script     2.1.0                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToProduct, Add-AzApiMa…
Script     1.1.0                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationIns…
Script     1.3.7                 Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-…
Script     3.1.0                 Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, New-AzBatch…
Script     1.0.3                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzCon…
Script     1.4.3                 Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfi…
Script     1.5.1                 Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCogn…
Script     4.2.1                 Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Updat…
Script     1.0.3                 Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzCo…
Script     1.1.1                 Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry,…
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeDevice, Invoke-AzDataBoxEdgeDevice, Ne…
Script     1.9.0                 Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDa…
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, …
Script     1.2.8                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider…
Script     1.0.0                 Az.DataShare                        Core,Desk {New-AzDataShareAccount, Get-AzDataShareAccount, Remove-AzDataShareAccount, Ne…
Script     1.1.0                 Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifactSource,…
Script     1.0.0                 Az.DesktopVirtualization            Core,Desk {Disconnect-AzWvdUserSession, Get-AzWvdApplication, Get-AzWvdApplicationGroup,…
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStar…
Script     1.1.2                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRe…
Script     1.3.0                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEvent…
Script     1.5.0                 Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Re…
Script     1.6.1                 Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoor…}
Script     1.0.1                 Az.Functions                        Core,Desk {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get-AzFunctionAppPlan,…
Script     3.4.0                 Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, N…
Script     1.1.0                 Az.HealthcareApis                   Core,Desk {New-AzHealthcareApisService, Remove-AzHealthcareApisService, Set-AzHealthcare…
Script     2.5.0                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionStr…
Script     2.0.0                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCerti…
Script     1.3.2                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIn…
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommit…
Script     1.0.0                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzMaintenanceConfigurat…
Script     1.0.2                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, New-AzManagedServicesAssignment, Remove-AzMa…
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.1                 Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaServiceKey, …
Script     2.0.2                 Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile…}
Script     3.3.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAu…
Script     1.1.1                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-AzNotifica…
Script     2.3.0                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsight…
Script     1.3.1                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyR…
Script     1.1.2                 Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-Az…
Script     1.0.3                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, Remove-AzPrivateDnsZone, Set-AzPrivateDnsZone, New-AzPr…
Script     2.11.1                Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzReco…
Script     1.2.1                 Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisC…
Script     1.0.3                 Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRe…
Script     2.4.0                 Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-A…
Script     1.4.1                 Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespa…
Script     2.1.0                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, …
Script     1.1.1                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey…}
Script     2.9.1                 Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataE…
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk {New-AzSqlVM, Get-AzSqlVM, Update-AzSqlVM, Remove-AzSqlVM…}
Script     2.4.0                 Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzSt…
Script     1.3.0                 Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncService, Get-AzStora…
Script     1.0.1                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition…
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, Get-AzSupportProblemClassification, Get-AzSupportTicket…
Script     1.0.4                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHead…
Script     1.11.0                Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAp…

    Directory: C:\program files\powershell\7\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   7.0.0.0               CimCmdlets                          Core      {Get-CimAssociatedInstance, Get-CimClass, Get-CimInstance, Get-CimSession…}
Manifest   1.2.5                 Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   7.0.0.0               Microsoft.PowerShell.Diagnostics    Core      {Get-WinEvent, New-WinEvent, Get-Counter}
Manifest   7.0.0.0               Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   7.0.0.0               Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Get-Clipboard, Set-Clipboard…}
Manifest   7.0.0.0               Microsoft.PowerShell.Security       Core      {Get-Acl, Set-Acl, Get-PfxCertificate, Get-Credential…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alias, Import-Alias, New-Alias…}
Manifest   7.0.0.0               Microsoft.WSMan.Management          Core      {Disable-WSManCredSSP, Enable-WSManCredSSP, Get-WSManCredSSP, Set-WSManQuickCo…
Script     1.4.7                 PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource…}
Script     2.2.4.1               PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability…}
Script     2.0.5                 PSDesiredStateConfiguration         Core      {Configuration, New-DscChecksum, Get-DscResource, Invoke-DscResource}
Script     7.0.0.0               PSDiagnostics                       Core      {Disable-PSTrace, Disable-PSWSManCombinedTrace, Disable-WSManTrace, Enable-PST…
Script     2.0.2                 PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineKeyHandl…
Binary     2.0.3                 ThreadJob                           Desk      Start-ThreadJob
## Debug output

DEBUG: 10:19:07 - SetAzureDataLakeStoreItemAclEntry begin processing with ParameterSet 'SetSpecificACE'.
DEBUG: 10:19:07 - using account id xxx@xxx.com'...
DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '08/22/2020 17:14:40 +00:00', MultipleResource? 'True', Tenant: '31ee33dd-0f01-471b-8a08-3ae8ef6e489e', UserId: 'xxx@xxx.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'xxx@xxx.com', Name: xxx@xxx.com, IdProvider: 'https://sts.windows.net/xxx/', Uid: 'xxx'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '08/22/2020 17:14:40 +00:00' Comparing to '08/22/2020 16:19:07 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:55:33.5328459'
DEBUG: 2020-08-22 10:19:07.8569|DEBUG|adls.powershell.WebTransport|VERB: PUT

RequestHeaders:
[AuthorizationHeaderLength:1705]
[x-ms-adl-client-latency:49f4df3f-ffe9-405d-b53a-2fbc863db8e5.0.0,116,,MODIFYACLENTRIES,0,1]
[User-Agent:Microsoft.Azure.DataLake.Store;1.2.3-alpha/Microsoft Windows 10.0.18363 X64/NETSTANDARD1_4/AzurePowershell/Az1.0.0]
[x-ms-client-request-id:c5686b92-4c92-4ec0-92a0-7f239b00703f.0]

ResponseStatus:Forbidden

ResponseHeaders:
[Cache-Control:no-store, no-cache, max-age=0]
[Pragma:no-cache]
[x-ms-request-id:d534225c-4f49-4d48-b6df-605f7a5368bc]
[x-ms-webhdfs-version:17.04.24.00]
[Status:0x83090C53]
[X-Content-Type-Options:nosniff]
[Strict-Transport-Security:max-age=15724800; includeSubDomains]
[Date:Sat, 22 Aug 2020 16:19:06 GMT]

DEBUG: 2020-08-22 10:19:07.8625|DEBUG|adls.dotnet.WebTransport|HTTPRequest,failed,cReqId:c5686b92-4c92-4ec0-92a0-7f239b00703f.0,lat:484,err:HTTP Forbidden ( AccessControlException  MODIFYACLENTRIES failed with error 0x83090c53 (Forbidden. ACL entry is invalid.). [d534225c-4f49-4d48-b6df-605f7a5368bc] failed with error 0x83090c53 (Forbidden. ACL entry is invalid.). [d534225c-4f49-4d48-b6df-605f7a5368bc][2020-08-22T09:19:06.8561371-07:00] JavaClassName: org.apache.hadoop.security.AccessControlException ,Reqlen:0,Resplen:0,token_ns:0,sReqId:d534225c-4f49-4d48-b6df-605f7a5368bc,path:/GrandpaFolder/DadFolder,qp:op=MODIFYACLENTRIES&aclspec=mask%3ASPNObjectID%3Arwx&api-version=2018-09-01, connectionfailure:False
Set-AzDataLakeStoreItemAclEntry: Error in modifying ACL entries mask:SPNObjectID:rwx for path /GrandpaFolder/DadFolder.
Operation: MODIFYACLENTRIES failed with HttpStatus:Forbidden  RemoteException: AccessControlException MODIFYACLENTRIES failed with error 0x83090c53 (Forbidden. ACL entry is invalid.). [d534225c-4f49-4d48-b6df-605f7a5368bc] failed with error 0x83090c53 (Forbidden. ACL entry is invalid.). [d534225c-4f49-4d48-b6df-605f7a5368bc][2020-08-22T09:19:06.8561371-07:00] JavaClassName: org.apache.hadoop.security.AccessControlException.
Last encountered exception thrown after 1 tries. [HTTP Forbidden ( AccessControlException  MODIFYACLENTRIES failed with error 0x83090c53 (Forbidden. ACL entry is invalid.). [d534225c-4f49-4d48-b6df-605f7a5368bc] failed with error 0x83090c53 (Forbidden. ACL entry is invalid.). [d534225c-4f49-4d48-b6df-605f7a5368bc][2020-08-22T09:19:06.8561371-07:00] JavaClassName: org.apache.hadoop.security.AccessControlException ]
[ServerRequestId:d534225c-4f49-4d48-b6df-605f7a5368bc]
DEBUG: AzureQoSEvent: CommandName - Set-AzDataLakeStoreItemAclEntry; IsSuccess - False; Duration - 00:00:00.5255226;; Exception - Microsoft.Azure.DataLake.Store.AdlsException: Error in modifying ACL entries mask:SPNObjectID:rwx for path /GrandpaFolder/DadFolder.
Operation: MODIFYACLENTRIES failed with HttpStatus:Forbidden  RemoteException: AccessControlException MODIFYACLENTRIES failed with error 0x83090c53 (Forbidden. ACL entry is invalid.). [d534225c-4f49-4d48-b6df-605f7a5368bc] failed with error 0x83090c53 (Forbidden. ACL entry is invalid.). [d534225c-4f49-4d48-b6df-605f7a5368bc][2020-08-22T09:19:06.8561371-07:00] JavaClassName: org.apache.hadoop.security.AccessControlException.
Last encountered exception thrown after 1 tries. [HTTP Forbidden ( AccessControlException  MODIFYACLENTRIES failed with error 0x83090c53 (Forbidden. ACL entry is invalid.). [d534225c-4f49-4d48-b6df-605f7a5368bc] failed with error 0x83090c53 (Forbidden. ACL entry is invalid.). [d534225c-4f49-4d48-b6df-605f7a5368bc][2020-08-22T09:19:06.8561371-07:00] JavaClassName: org.apache.hadoop.security.AccessControlException ]
[ServerRequestId:d534225c-4f49-4d48-b6df-605f7a5368bc]
   at Microsoft.Azure.DataLake.Store.AdlsClient.ModifyAclEntriesAsync(String path, List`1 aclSpec, CancellationToken cancelToken)
   at Microsoft.Azure.DataLake.Store.AdlsClient.ModifyAclEntries(String path, List`1 aclSpec, CancellationToken cancelToken)
   at Microsoft.Azure.Commands.DataLakeStore.Models.DataLakeStoreFileSystemClient.ModifyAcl(String path, String accountName, List`1 aclToModify)
   at Microsoft.Azure.Commands.DataLakeStore.SetAzureDataLakeStoreItemAclEntry.<>c__DisplayClass46_0.<ExecuteCmdlet>b__2()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(String processMessage, String target, Action action)
   at Microsoft.Azure.Commands.DataLakeStore.SetAzureDataLakeStoreItemAclEntry.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 10:19:08 - SetAzureDataLakeStoreItemAclEntry end processing.

## Error output

 HistoryId: 91

Message        : Error in modifying ACL entries mask:SPNObjectId:rwx for path /GrandpaFolder/DadFolder.
                 Operation: MODIFYACLENTRIES failed with HttpStatus:Forbidden  RemoteException: AccessControlException MODIFYACLENTRIES failed with error 0x83
                 090c53 (Forbidden. ACL entry is invalid.). [d534225c-4f49-4d48-b6df-605f7a5368bc] failed with error 0x83090c53 (Forbidden. ACL entry is inval
                 id.). [d534225c-4f49-4d48-b6df-605f7a5368bc][2020-08-22T09:19:06.8561371-07:00] JavaClassName: org.apache.hadoop.security.AccessControlExcept
                 ion.
                 Last encountered exception thrown after 1 tries. [HTTP Forbidden ( AccessControlException  MODIFYACLENTRIES failed with error 0x83090c53 (For
                 bidden. ACL entry is invalid.). [d534225c-4f49-4d48-b6df-605f7a5368bc] failed with error 0x83090c53 (Forbidden. ACL entry is invalid.). [d534
                 225c-4f49-4d48-b6df-605f7a5368bc][2020-08-22T09:19:06.8561371-07:00] JavaClassName: org.apache.hadoop.security.AccessControlException ]
                 [ServerRequestId:d534225c-4f49-4d48-b6df-605f7a5368bc]
StackTrace     :    at Microsoft.Azure.DataLake.Store.AdlsClient.ModifyAclEntriesAsync(String path, List`1 aclSpec, CancellationToken cancelToken)
                    at Microsoft.Azure.DataLake.Store.AdlsClient.ModifyAclEntries(String path, List`1 aclSpec, CancellationToken cancelToken)
                    at Microsoft.Azure.Commands.DataLakeStore.Models.DataLakeStoreFileSystemClient.ModifyAcl(String path, String accountName, List`1 aclToModi
                 fy)
                    at Microsoft.Azure.Commands.DataLakeStore.SetAzureDataLakeStoreItemAclEntry.<>c__DisplayClass46_0.<ExecuteCmdlet>b__2()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(String processMessage, String target, Action action)
                    at Microsoft.Azure.Commands.DataLakeStore.SetAzureDataLakeStoreItemAclEntry.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.DataLake.Store.AdlsException
InvocationInfo : {Set-AzDataLakeStoreItemAclEntry}
Line           : Set-AzDataLakeStoreItemAclEntry -Account DLAccount -Path /GrandpaFolder/DadFolder -AceType other -Id "SPNObjectId"  -Permissions All
Position       : At line:1 char:1
                 + Set-AzDataLakeStoreItemAclEntry -Account DLAccount -Path /Grandp …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 91

**Comment by dingmeng-xue** [comment]
Data Lake Store team, please help to look into this issue.

**Comment by FuntestechGithub** [comment]
To add onto my previous issue:
If I use -Acl switch, I won't get any error message but change also doesn't get applied.
Set-AzDataLakeStoreItemAclEntry -Account XXX -Path /GrandpaFolder -Acl other:XXX-XXX-XXX-XXX-XXX:r-x

**Comment by rahuldutta90** [comment]
@FuntestechGithub I dont think you should use other. user is the correct acl type for SPI or user. As long as you are applying correct object id, your permissions will be set correctly. Clarifying question, are you getting the objectid of the SPI from the AAD->EnterpriseApplications->your app id -> Get the guid from the objectid column?

**Comment by FuntestechGithub** [comment]
@rahuldutta90  
That is app registrations I was trying to set ACL for, not the enterprise application. 

Azure Portal -> AAD -> App Registrations  -> Overview -> Object ID

Is it supported? 

Thanks

**Comment by rahuldutta90** [comment]
@FuntestechGithub  I think thats the issue. You need to use objectid from the enterprise application. We are working on putting up a doc regarding this.

**Comment by FuntestechGithub** [comment]
@rahuldutta90  Thanks a lot :) I confirm this just resolved my issue.
