### ISSUE TITLE
Set-AzKeyVaultAccessPolicy - Ability to provide "all" as input to permissions

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-powershell#12722]
## Description of the new feature

API clearly supports "all" for a given permission, as the following screen shot shows (from ```(Get-AzKeyVault -KeyVaultName $KeyVaultName).'AccessPolicies'```)

![image](https://user-images.githubusercontent.com/6450056/90868908-c7361a80-e397-11ea-8ee3-e2941a4fc7b9.png)

But trying to ```Set-AzKeyVaultAccessPolicy``` with "all" fails when validated against ```[ValidateSet()]```

![image](https://user-images.githubusercontent.com/6450056/90869082-05cbd500-e398-11ea-8691-29ccb3a9416f.png)

Because of this, the code that has to be used to set all permissions gets dumb long

```powershell
Set-AzKeyVaultAccessPolicy -VaultName $KeyVaultName -UserPrincipalName $UserPrincipalName `
    -PermissionsToKeys ('decrypt','encrypt','unwrapKey','wrapKey','verify','sign','get','list','update','create','import','delete','backup','restore','recover','purge') `
    -PermissionsToSecrets ('get','list','set','delete','backup','restore','recover','purge') `
    -PermissionsToCertificates ('get','list','delete','create','import','update','managecontacts','getissuers','listissuers','setissuers','deleteissuers','manageissuers','recover','purge','backup','restore') `
    -PermissionsToStorage ('get','list','delete','set','update','regeneratekey','getsas','listsas','deletesas','setsas','recover','backup','restore','purge')
```

## Proposed implementation details (optional)

Add "all" as valid input to cmdlet, and eventually do what has to be done in regards to the API request.

**Comment by isra-fel** [comment]
Key vault team has updated there API spec to accept "all" as an option in Azure/azure-rest-api-specs/pull/11042

We need to:

- Regenerate Microsoft.Azure.Management.KeyVault SDK
- Update PowerShell code to allow "all" as well

**Comment by isra-fel** [comment]
Pull request is merged and the feature will be in our next regular release :)
