### ISSUE TITLE
[Az.Functions] Add support to update/downgrade a function app version

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-powershell#12749]
### Description

Update-AzFunctionApp should support updating/downgrading the function app version. 

cc: @anirudhgarg @eamonoreilly @stefanushinardi

**Comment by ggailey777** [comment]
@Francisco-Gamino I've been able to do this by using `Update-AzFunctionAppSetting`. Is this a correct way to do it?

```ps
Update-AzFunctionAppSetting -Name "<FUNCTION_APP>" -ResourceGroupName "<RESOURCE_GROUP>" -AppSetting @{"FUNCTIONS_EXTENSION_VERSION" = "<VERSION>"} -Force
```

**Comment by Francisco-Gamino** [comment]
@stefanushinardi -- we need to define a new cmdlet to do this.

**Comment by Francisco-Gamino** [comment]
This is a dup of https://github.com/Azure/azure-powershell/issues/14338.
