### ISSUE TITLE
Unable to access Azure Active Directory resources using Azure Powershell task with Microsoft Graph API permissions assign to Service Principal

### ISSUE THREAD

**Issue by PratikT29** [Azure/azure-powershell#12748]
## Description

I had a use case to assign custom roles to users in my resource group.
The powershell script and  cmdlets like Get-AzRoleAssignment, Get-AzADUser, New-AzRoleAssignment worked fine on my local environment with my user connection.
To assign the roles through pipeline, I created a service principal with UserAccessAdministrator role in resource group and added Microsoft Graph API **Application** permission **Directory.Read.All** to it. But when I ran the pipeline I was Unable to access Azure Active Directory resources and got **Exception of type 'Microsoft.Rest.Azure.CloudException'**  in azure powershell task.
After wasting over a week, I added Azure AD Graph API **Application** permission **Directory.Read.All** to my service principal and removed Microsoft Graph API permission and everything ran without any issue.

But as per the message, Microsoft Graph API must be used instead of Azure AD Graph API.
So either the documentation should be updated as the message is incorrect or the Az cmdlets to use Microsoft Graph API.

![image](https://user-images.githubusercontent.com/32224558/91067326-6422dd00-e650-11ea-921d-7bb21767a53a.png)

## Steps to reproduce
1. Create a service principal.
2. Assign Microsoft Graph API **Application** permission **Directory.Read.All**
3. Use service principal to Run the azure powershell task with cmdlets like Get-AzRoleAssignment, Get-AzADUser, New-AzRoleAssignment
4. Task fails with Exception of type 'Microsoft.Rest.Azure.CloudException'
```powershell

```

## Environment data

Azure Pipeline Hosted Agent

## Module versions

Task         : Azure PowerShell
Version      : 5.173.1

## Error output

##[error]Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
##[error]PowerShell exited with code '1'.

**Comment by dingmeng-xue** [comment]
@PT2911 , thanks for reporting. I think the message is correct. However current Azure PowerShell module is still using Azure AD Graph API even though there is no new feature on Azure AD Graph. We will plan to switch to Microsoft Graph as well.

**Comment by dingmeng-xue** [comment]
Close this issue now. If you need further help, please contact us
