### ISSUE TITLE
[Az.ResourceGraph] Search-AzGraph is returning inconsistent/incomplete results

### ISSUE THREAD

**Issue by craigeaw** [Azure/azure-powershell#12747]
Running the below command returns inconsistent results. Sometimes it returns all automation accounts as expected. Sometimes it returns only one or two. This has been happening since 8/21/20.

`Search-AzGraph -Subscription $subscriptionId -Query "Resources | where type =~ 'Microsoft.Automation/automationAccounts'"`

Az.ResourceGraph version 0.7.7 is being used.

**Comment by dingmeng-xue** [comment]
Service team, please look into this issue.

**Comment by fenwickt** [comment]
Hi, thank you for reaching out! We had an issue with service configuration for SDK/CLI/Powershell queries; the issue has been fixed and mitigated as of Aug 24 7pm UTC. Could you please check whether the results are now consitent?

**Comment by craigeaw** [comment]
I can confirm we are getting consistent results now. This affected some of our production automation in Azure and led to resources being deleted that should not have been deleted. Our logic checks against resource graph to avoid any context switching in the runbooks that are performing our automation. Since the results were inconsistent and missing, the deletes were triggered. Is there a recommended way of ensuring the resource graph is not having issues before/during running this automation?

**Comment by snaheth** [comment]
Hi @craigeaw, I'm a PM on Azure Resource Graph (ARG). It sounds like your logic immediately triggers a resource delete when Resource Graph incorrectly showed that your Automation Accounts didn't exist anymore. That's a mistake on our end and we apologize that this happened.

Currently, there's no way to check if Resource Graph is running into these types of rare issues before/on a request to ARG but this would be possible if ARG integrated with Service Health. If this is what you're looking for (or are familiar with using other Azure products) OR....if you want to share any information around your scenario, feel free to message me directly or reach out to us @ resourcegraphsupport@microsoft.com
