### ISSUE TITLE
There is error in document remove-cmdlet-example.md

### ISSUE THREAD

**Issue by aim-for-better** [Azure/azure-powershell#12768]
## Description
There is an error in https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/examples/remove-cmdlet-example.md#c-example-1

![image](https://user-images.githubusercontent.com/12733681/91249762-14e0c780-e78a-11ea-9a64-186b7d4eb953.png)

It should be  this.PassThru

**Comment by dingmeng-xue** [comment]
@aim-for-better , thanks for your finding.

@BethanyZhou , please review and fix this problem.
