### ISSUE TITLE
Webapp:Support for HTTPS-only during web-app creation

### ISSUE THREAD

**Issue by ghost** [Azure/azure-powershell#12762]
The enterprise I'm working at demands that all app-services are set to **https-only**. Unfortunately we cannot specify 'https-only' in the **Azure portal**, nor in the **Azure Powershell**, nor in **Azure CLI**. Only in **ARM templates** it's currently possible  (with `"properties": {"httpsOnly": true}`) to specify 'https-only' during creation of an app-service.

Please add the option **-HttpsOnly** to **New-AzWebApp**, as it is also available in **Set-AzWebApp**.

Example:
`New-AzWebApp -Name mvrs-appservice1 -Location westeurope -AppServicePlan mvrs-appserviceplan -ResourceGroupName mvrs-appservice-rg -HttpsOnly $true`

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Service team, please help to evaluate this feature request.

**Comment by ThejaChoudary** [comment]
Assigning to myself to repro

**Comment by panchagnula** [comment]
@Kotasudhakarreddy given the API supports adding certain properties during create lets go-ahead & add httpsOnly to NewAzWebapp commandlet https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createorupdate
tentative ETA for next sprint - but we move to later sprint if needed

**Comment by SatishBoddu-MSFT** [comment]
Hello @Kotasudhakarreddy Please let us know if are good to close this issue?

**Comment by Kotasudhakarreddy** [comment]
Will be taking for current release.

**Comment by SatishBoddu-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
