### ISSUE TITLE
Error using Add-Azure Account with SPN Credentials

### ISSUE THREAD

**Issue by davidmginn** [Azure/azure-powershell#1278]
When trying to use the below to add an Azure Account, I'm receiving an error

$Password = "XXXXXXXX"
$Clientid = "00000000-0000-0000-0000-000000000000"
$TenantId = "domain.onmicrosoft.com"

'$securePassword = ConvertTo-SecureString $Password -AsPlainText -Force'
$servicePrincipalCredentials = New-Object System.Management.Automation.PSCredential ($ClientId, $securePassword)
Add-AzureAccount -ServicePrincipal -Tenant $TenantId -Credential $servicePrincipalCredentials | Out-Null 

Below is the error:

Add-AzureAccount : The given key was not present in the dictionary.
At line:1 char:1
+ Add-AzureAccount -ServicePrincipal -Tenant $TenantId -Credential $ser ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureAccount], KeyNotFoundException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Profile.AddAzureAccount

**Comment by markcowl** [comment]
@davidmginn Can you execute with ```$DebugPreference="Continue"``` to help us debug the issue?  Are you running on a machine that has access to the credential store, or is this occurring in azure automation or a service account?

**Comment by jeffbry** [comment]
Getting the same error.  Debug is attached.

[Add-AzureAccount.Error.txt](https://github.com/Azure/azure-powershell/files/54938/Add-AzureAccount.Error.txt)

**Comment by bastienJS** [comment]
One month later and no answer?

I run at the same wall doing: Add-AzureAccount, a login form opens, I enter my azure name/password. The login closes and I get the same error as the thread opener: "The given key was not present in the dictionary."

But I can normally log into my azure portal for over a 1 year now...

**Comment by devigned** [comment]
I think this should be using add-azurermaccount in AzPS 1.0 or greater. Please try that and respond back.

**Comment by mithunshanbhag** [comment]
@markcowl : I'm running into the same error while using Add-AzureAccount with a service principal. I've captured the debug log here: https://gist.github.com/mithunshanbhag/ea5cebd38bbac0da76f6

Some other notes: 

- The RM equivalent of this cmdlet (Add-Azure**Rm**Account) works fine. However I cannot use this in my scripts (I'm using some legacy SM Azure compute cmdlets that have no RM equivalents. Hence I'm forced to use the legacy SM cmdlets).

**Comment by devigned** [comment]
@hovsepm could you look into this?

**Comment by markcowl** [comment]
@mithunshanbhag ServicePrincipal authentication does not work with azure service management - there is simply no way to provide co-admin authorization to a service principal.  If you need to automate ASM scenarios, using certificate authentication is the best bet

Closing, as this issue has been resolved for Add-AzureRmAcount

**Comment by strtdusty** [comment]
So is there no support for running ASM commandlets in automation when trying to authenticate using an SPN?  As @mithunshanbhag stated there are some ASN commandlets that have no ARM analog.

**Comment by colemickens** [comment]
@markcowl If SP auth doesn't work with ASM then why is it explicitly listed in the `get-help` for `Add-AzureAccount`?

>There are two different ways to make your Azure account available to Windows PowerShell. You can use the Add-AzureAccount cmdlet, which uses Azure Active Directory (Azure AD) authentication access tokens, or Import-AzurePublishSettingsFile, which uses a management certificate.
