### ISSUE TITLE
Inconsistent Resource provider name casing

### ISSUE THREAD

**Issue by Garima-msft** [Azure/azure-powershell#12788]
Inconsistent Resource provider name casing in some scenarios. Is this expected or could this be a one time issue
eg:
Microsoft.storageaccounts
microsoft.StorageAccounts

Both have separate casing and cause a discrepancy in our code while using Get-AzResource command via powershell

**Comment by dingmeng-xue** [comment]
@Garima-msft , please provide specific example and help us to do further analysis.

**Comment by dingmeng-xue** [comment]
@Garima-msft , could you share debug log when you execute Get-AzResource? You can enable log via `$DebugPreference="Continue"`

**Comment by dingmeng-xue** [comment]
@Garima-msft , I'm closing this issue now. Please contact us if you have further feedback.
