### ISSUE TITLE
Get-AzureResourceGalleryTemplate doesn't like to filter...

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-powershell#128]
This returns a template from the gallery that has CategoryIds...
PS C:\> Get-AzureResourceGroupGalleryTemplate -Identity Microsoft.WebSiteDeploy.0.2.5-preview 

This should also return that template, but doesn't...
PS C:\> Get-AzureResourceGroupGalleryTemplate | Where-Object {$_.CategoryIds -like "*show*"}

I tried a few other broader filters and get the same result.

**Comment by ravbhatnagar** [comment]
This cmdlet has been removed in the latest PS version. Gilles team is working on providing the gallery template functionality through new cmdlets.
