### ISSUE TITLE
New-AzRoleAssignment error: string format is incorrect

### ISSUE THREAD

**Issue by yvesgermain** [Azure/azure-powershell#12815]
This script used to work with module az.resources 2.1.0: 
$qa = get-azadgroup -displayname qa; 
New-AzRoleAssignment -ObjectId $qa.Id -RoleDefinitionName Owner -ResourceGroupName RG-QA 

Started getting this error on one computer but not the other. When I checked the modules version for az.resources, I had 2.1.0, 2.4.0 and 2.5.0. After removing versions 2.4.0 and 2.5.0, the script worked. I have the language of Powershell set to French.

Here is the error message:

PS>New-AzRoleAssignment -ResourceGroupName Gumstorage-rg-devops -ObjectId  $qa.id -RoleDefinitionName Contributor
New-AzRoleAssignment : Le format de la chaîne d'entrée est incorrect.
Au caractère Ligne:1 : 1
+ New-AzRoleAssignment -ResourceGroupName Gumstorage-rg-devops -ObjectI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError : (:) [New-AzRoleAssignment], FormatException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand
New-AzRoleAssignment : Le format de la chaîne d'entrée est incorrect.
Au caractère Ligne:1 : 1
+ New-AzRoleAssignment -ResourceGroupName Gumstorage-rg-devops -ObjectI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError : (:) [New-AzRoleAssignment], FormatException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand

I was getting with the -Debug switch on:

PS>New-AzRoleAssignment -ResourceGroupName GumStorage-rg-devops -ObjectId $qa.id -RoleDefinitionName Contributor -debug
DÉBOGUER : 17:28:01 - NewAzureRoleAssignmentCommand begin processing with ParameterSet 'ResourceGroupWithObjectIdParameterSet'.
Confirmer
Voulez-vous continuer cette opération ?
&Oui  Oui pour &tout  &Interrompre la commande  &Suspendre
t
DÉBOGUER : 17:28:03 - using account id 'ygermain@gumqc.onmicrosoft.com'...
Confirmer
Le format de la chaîne d'entrée est incorrect.
&Oui  Oui pour &tout  &Interrompre la commande  &Suspendre
t
New-AzRoleAssignment : Le format de la chaîne d'entrée est incorrect.
Au caractère Ligne:1 : 1
+ New-AzRoleAssignment -ResourceGroupName GumStorage-rg-devops -ObjectI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError : (:) [New-AzRoleAssignment], FormatException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand
New-AzRoleAssignment : Le format de la chaîne d'entrée est incorrect.
Au caractère Ligne:1 : 1
+ New-AzRoleAssignment -ResourceGroupName GumStorage-rg-devops -ObjectI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError : (:) [New-AzRoleAssignment], FormatException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand

DÉBOGUER : AzureQoSEvent: CommandName - New-AzRoleAssignment; IsSuccess - False; Duration - 00:00:02.9425758;; Exception - System.FormatException: Le format de la chaîne d'entrée est incorrect.
   à System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   à Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand.ExecuteCmdlet()
   à Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DÉBOGUER : Finish sending metric.
DÉBOGUER : 17:28:05 - NewAzureRoleAssignmentCommand end processing.

**Comment by meCoding** [comment]
I have the same issue. If I force to load module version 2.4.0, this is working but not with 2.5.0 version. I'm using PowerShell 5.1 and Windows 10.
In cloudshell where module version 2.5.0 is loaded this is working just fine

**Comment by o-l-a-v** [comment]
Something as simple as

```powershell
New-AzRoleAssignment -ObjectId '<GUID_of_user_or_group' -RoleDefinitionName 'Owner'
```

fails with Az.Resources 2.5.0, but works with 2.3.0 for instance. Do you even test before releasing new "stable" releass?

**Comment by dcaro** [comment]
We are looking at the issue, for the moment, the workaround is to use the 2.4.0 version of the Az.Resources module.

`Uninstall-Module -name Az.Resources -AllVersions -force && Install-Module -name Az.Resources -RequiredVersion 2.4.0`

**Comment by o-l-a-v** [comment]
@armleads-azure

Any update here? This is still not resolved.

**Comment by dagoroz** [comment]
@o-l-a-v I have pushed a fix, however it didn't make it in time for the 3.0.0 release
next release is on 11/17 you should try again then

**Comment by mortenlerudjordet** [comment]
I found a workaround, run [cultureinfo]::CurrentCulture = 'en-US' before calling New-AzRoleAssignment

**Comment by yvesgermain** [comment]
As for me, you can close the case.

Thanks!

Yves Germain

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SatishBoddu-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
