### ISSUE TITLE
Useless error message from New-AzCdnProfile 

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#12813]
```
PS > New-AzCdnProfile -ResourceGroupName $ResourceGroup -Location $AzureLocation -ProfileName azurecdntrevor123 -Sku Standard_Microsoft
New-AzCdnProfile: Operation returned an invalid status code 'BadRequest'
```

**Comment by dingmeng-xue** [comment]
@pcgeek86 , could you execute cmdlet again after setting `$DebugPreference="Continue"`? Then, please share the output with HTTP information to us.

**Comment by pcgeek86** [comment]
I changed the `-Location` parameter from `West US 2` to `West US`, and it worked. Error message needs to be improved.

**Comment by dingmeng-xue** [comment]
I'm closing this issue and please contact us if you have further question.
