### ISSUE TITLE
Test-AzDeployment in Az.Resources 2.5.0 issue when using securestring type parameter 

### ISSUE THREAD

**Issue by thijsvanbloemendaal** [Azure/azure-powershell#12819]
I'm getting errors since version 2.5.0 of Az.Resources.
How to reproduce:
executed powershell code:
``` powershell
import-module Az.Resources -RequiredVersion 2.5.0 -force
$token = (ConvertTo-SecureString "sasTokenString" -AsPlainText -force)

Test-AzDeployment `
          -Location "location" `
          -TemplateFile "template file" `
          -_artifactsLocationSasToken $token `
          -Verbose
```
Throws: ```InvalidTemplate - Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'String, Uri'. Actual 'Object'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'.```

The template ARM file contains the json:
``` json
"_artifactsLocationSasToken": {
            "type": "securestring"
        }
```

On version 2.4.0 I receive the expected output.
The same happens on the New-AzDeployment.

Was something changed on this version? Can't find a breaking change on this in de release notes.

**Comment by dingmeng-xue** [comment]
@shenglol , Is it the same issue as #12792?

**Comment by thijsvanbloemendaal** [comment]
> @shenglol , Is it the same issue as #12792?

Seems to be related indeed! Other cmdLets though, but probably the same fix.

**Comment by shenglol** [comment]
@dingmeng-xue, yes it's the same issue.

**Comment by nevergonnagityouup** [comment]
Having the same issue in an Azure Automation Runbook running version 2.5.0 there as well. Happy I found this thread cause I was looking everywhere for what was going on.

**Comment by codeevaluator** [comment]
+1 same issue for us.

**Comment by shenglol** [comment]
Az 4.7.0 and Az.Resources 2.5.1 contain a fix to the issue and were released yesterday. Closing the issue.

**Comment by PaulVrugt** [comment]
omg, lost half a day to find out why the deployment using azure pipelines stopped working. Please update the hosted pipeline images!
