### ISSUE TITLE
New-AzAutomationModule: add -Wait (or -AsJob)

### ISSUE THREAD

**Issue by fowl2** [Azure/azure-powershell#12824]
## Description of the new feature

`New-AzAutomationModule` kicks off an asynchronous account-side import that can possibly fail. It'd be great to be able write straight-line scripts that directly returned the results. 

`-AsJob` would be even better as it's very common to import multiple packages at once, and they could all be awaited at once.

**Comment by dingmeng-xue** [comment]
Automation team, please help to look into this feature.

**Comment by jaspkaur28** [comment]
Thanks for the feedback . We will get this triaged with the engineering team, however due to other priorities , we may not been able to pick this up right away. Please expect a update to the cmdlet behaviour only by Q4 CY2020.

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.

**Comment by jaspkaur28** [comment]
We have identified this as one of the feature asks. Please expect a update to this by Q1 CY2021.

**Comment by fowl2** [comment]
hi, was this closed by mistake?

**Comment by jaspkaur28** [comment]
@fowl2 : This is being tracked internally as a feature ask & we will action this in CY21 - Q1 (feb-march timeframe) & update the automation docs once completed. Hence , closed the thread with the same update above.
