### ISSUE TITLE
New-AzAutomationModule should be called Import-AzAutomationModule

### ISSUE THREAD

**Issue by fowl2** [Azure/azure-powershell#12823]
Mostly because it doesn't just create a automation module, it will override any that's already there too which you wouldn't expect from a "New" verb without a "-Clobber" (which doesn't exist here). 

It looks like there's some remnant of the correct name in the code already, not sure what happened there. The help text even says "import":

> Imports a module into Automation

Quick win would be to update docs, eg.

> Imports a module into Automation, if the module already exists it is replaced.

**Comment by dingmeng-xue** [comment]
Automation team, please look into this question.

Given the syntax of New-AzAutomationModule and its usage, it seems Import is better. Do you know the original consideration during design?

**Comment by jaspkaur28** [comment]
Thanks for the feedback . We are looking into this. Please expect a response by next week .

**Comment by jaspkaur28** [comment]
We've got this triaged and added it as a feature ask to our backlog. However , Automation team wont be able to get this prioritized right now since the team is working towards some of the other high prioritity work items in Automation . We will definately revisit this in Q4 CY20 & pick this up if resourcing allows.

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.

**Comment by jaspkaur28** [comment]
We have identified this as one of the feature asks. Please expect a update to this by Q1 CY2021.

**Comment by fowl2** [comment]
hi, was this closed by mistake?

**Comment by jaspkaur28** [comment]
@fowl2 :This issue is also being tracked internally as an improvement & we plan to action this in CY21 - Q1 (feb-march timeframe) & update the automation docs. Hence , closed the thread here.

**Comment by fowl2** [comment]
will this GH issue be updated then?

**Comment by jaspkaur28** [comment]
As we shared in the last comment , we are trying to prioritize this work for Q1 - Feb , March timeframe.

**Comment by jaspkaur28** [comment]
Deferred to CY2021 Q4 due to other priorities.

**Comment by SatishBoddu-MSFT** [comment]
Hello @jaspkaur28 Please let is know if we have further time or good to close this issue?

**Comment by fowl2** [comment]
this issue still exists..

**Comment by jaspkaur28** [comment]
@fowl2 ETA for fixing this issue would be 11/30.

**Comment by jaspkaur28** [comment]
@fowl2  : Import-AzAutomationModule is an alias for New-AzAutomationModule . Aliases are not documented yet , PowerShell team is working on it .
