### ISSUE TITLE
Remove-AzOperationalInsightsWorkspace soft-deleted workspaces

### ISSUE THREAD

**Issue by fowl2** [Azure/azure-powershell#12841]
Currently if you try to purge a Log Analytics workspace that's been soft deleted from a resource group that's been deleted, you receive an error. It's be great if these could be deleted.

```
Get-AzOperationalInsightsDeletedWorkspace  | Remove-AzOperationalInsightsWorkspace -ForceDelete
Remove-AzOperationalInsightsWorkspace : HTTP Status Code: NotFound
Error Message: Resource group 'test-xxxx' could not be found.
Request Id: 99d692d6-813a-423a-aabc-48f74933d841
Timestamp (Utc):09/03/2020 01:16:57
At line:1 char:46
+ ... eletedWorkspace  | Remove-AzOperationalInsightsWorkspace -ForceDelete
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Remove-AzOperationalInsightsWorkspace], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.OperationalInsights.RemoveAzureOperationalInsightsWorkspaceCommand
```

**Comment by dingmeng-xue** [comment]
Thanks for your report. There is no API to purge soft deleted workspace. Please restore it and force delete again.

**Comment by fowl2** [comment]
Ahh. I've verified that creating a new resource group with the same name (location doesn't matter) allows the workspace to be restored, and then purged. Thanks.

It would still be a nice feature to be able to purge them directly

**Comment by dingmeng-xue** [comment]
We will convey it to service team. Close this issue now.
