### ISSUE TITLE
New-AzOperationalInsightsWorkspace will recover a soft-deleted workspace

### ISSUE THREAD

**Issue by fowl2** [Azure/azure-powershell#12862]
## Description

New-AzOperationalInsightsWorkspace will recover a soft-deleted workspace if the same name, resource group name and location are specified. 

The [documentation](https://docs.microsoft.com/en-us/powershell/module/az.operationalinsights/new-azoperationalinsightsworkspace?view=azps-4.6.1) says simply 

> Creates a workspace.

which does not indicate any kind of recover. It's especially unexpected considering `Recover-AzOperationalInsightsWorkspace` exists.

Az.OperationalInsightsWorkspace 2.3

**Comment by fowl2** [comment]
Actually I found [one doc](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/delete-workspace#powershell-1) that uses 'new' for 'recover', but it also mentions a warning that I haven't seen.

**Comment by dingmeng-xue** [comment]
@fowl2 , please help to share what warning was shown. It will great if you can share whole debug information.

**Comment by fowl2** [comment]
I didn't receive the warning, but would like one. An error would be even better.

Recently accepted PR MicrosoftDocs/azure-docs#62100 removes the mention of a warning, which should added back depending how this is resolved.

**Comment by VeryEarly** [comment]
fixed in #13615 by mentioning `new-azoperationalinsightsworkspace` will also restore soft-deleted workspaces.
