### ISSUE TITLE
webapp:DefaultParameterSetName is missing for some cmdlets

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-powershell#1286]
e.g. running `Get-AzureRMWebAppSlot` with no params results in:

```
Get-AzureRMWebAppSlot : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-AzureRMWebAppSlot
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRMWebAppSlot], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.WebApps.Cmdlets.DeploymentSlots.GetAzureWebAppSlotCmdlet 
```

This happens because there is no DefaultParameterSet for a cmdlet.

**Comment by jeffpatton1971** [comment]
Good times kids! Maybe we should rtfm....oh wait

https://docs.microsoft.com/en-us/powershell/resourcemanager/azurerm.websites/v2.1.0/get-azurermwebappslot

**Comment by panchagnula** [comment]
@maddieclayton  this has been active for a while now & i can still repro it on websites-preview as well . Are you planning to look into this?

**Comment by maddieclayton** [comment]
@panchagnula This is currently on my backlog as I have a couple other issues I am working on.  The change is very simple, so if you would like to implement it on Websites it would be a quick and simple fix.

**Comment by maddieclayton** [comment]
@panchagnula Turns out this requires testing to ensure scenarios aren't broken, which I will not be able to do for over 200 cmdlets.  I'll assign this to your for Websites.

**Comment by panchagnula** [comment]
this should now be fixed.
