### ISSUE TITLE
Get-AzureSBNamespace not working 1.0.0+

### ISSUE THREAD

**Issue by iremmats** [Azure/azure-powershell#1287]
The cmdlets for Azure Service Bus seems to be entirely broken in the new versions. Please have a look at this.

**Comment by hovsepm** [comment]
@iremmats could you provide some details on your scenario?

**Comment by iremmats** [comment]
Seems it works now after reinstalling Azure Powershell and the preview modules. Its a bit tricky keeping track of exactly which module is loaded.

The errors we had earlier today included NullReference exceptions.  But you can close this issue for now.
