### ISSUE TITLE
Unable to create VNET peer between subscriptions using CSP Secure model (MFA)

### ISSUE THREAD

**Issue by aconn21** [Azure/azure-powershell#12875]
## Description
Unable to create VNET peer between subscriptions using CSP Secure model (MFA). It looks like it has something to do with the way its authenticating to the subscription. Any assistance would be appreciated. The error makes no sense to me.

## Steps to reproduce
#Connect to customer 1 and get VNET
$aadGraphToken1 = New-PartnerAccessToken -ApplicationId $AppID -Credential $App_Cred -RefreshToken $RefreshToken -Scopes 'https://graph.windows.net/.default' -ServicePrincipal -Tenant $CustomerTenant1ID

$AzureToken1 = New-PartnerAccessToken -ApplicationId $AppID -Credential $App_Cred -RefreshToken $RefreshToken -Scopes 'https://management.azure.com/user_impersonation' -ServicePrincipal -Tenant $CustomerTenant1ID

Connect-AzAccount -AccessToken $AzureToken1.AccessToken -AccountId $ScriptUser -GraphAccessToken $aadGraphToken1.AccessToken -TenantId $CustomerTenant1ID

Select-AzSubscription $Customer1Sub

$VNET1 = Get-AzVirtualNetwork -Name $VNET1Name -ResourceGroupName $VNET1RG

#Connect to customer 2 and get VNET then peer
$aadGraphToken2 = New-PartnerAccessToken -ApplicationId $AppID -Credential $App_Cred -RefreshToken $RefreshToken -Scopes 'https://graph.windows.net/.default' -ServicePrincipal -Tenant $CustomerTenant2ID

$AzureToken2 = New-PartnerAccessToken -ApplicationId $AppID -Credential $App_Cred -RefreshToken $RefreshToken -Scopes 'https://management.azure.com/user_impersonation' -ServicePrincipal -Tenant $CustomerTenant2ID

Connect-AzAccount -AccessToken $AzureToken2.AccessToken -AccountId $ScriptUser -GraphAccessToken $aadGraphToken2.AccessToken -TenantId $CustomerTenant2ID

Select-AzSubscription $Customer2Sub

$VNET2 = Get-AzVirtualNetwork -Name $VNET2Name -ResourceGroupName $VNET2RG

Add-AzVirtualNetworkPeering -Name ("Peer_VNET2toVNET1") -VirtualNetwork $VNET2 -RemoteVirtualNetworkId $VNET1.Id -AllowForwardedTraffic

## Environment data
Windows Server 2019

## Module versions

ModuleType Version    Name                                ExportedCommands                                                                                                                                                           
---------- -------    ----                                ----------------                                                                                                                                                           
Script     2.7.0      Az                                                          

## Debug output

DEBUG: AzureQoSEvent: CommandName - Add-AzVirtualNetworkPeering; IsSuccess - False; Duration - 00:00:06.8954622; Exception - Microsoft.Azure.Commands.Network.Common.NetworkCloudException: Authentication failed for auxiliary token:
 'The '1' auxiliary tokens contains duplicates which are from the same tenant. The tenant ids 'da6330d2-07f6-4e5b-a411-7b79852aabc2' are common in more than one auxiliary tokens or is same as primary tenant.'
StatusCode: 401
ReasonPhrase: Unauthorized
ErrorCode: AuxiliaryTokensDuplicate
ErrorMessage: Authentication failed for auxiliary token: 'The '1' auxiliary tokens contains duplicates which are from the same tenant. The tenant ids 'da6330d2-07f6-4e5b-a411-7b79852aabc2' are common in more than one auxiliary tok
ens or is same as primary tenant.'
OperationID : e5419fff-9dd5-4db6-aa53-4ddbd84d0c54 ---> Microsoft.Rest.Azure.CloudException: Authentication failed for auxiliary token: 'The '1' auxiliary tokens contains duplicates which are from the same tenant. The tenant ids '
da6330d2-07f6-4e5b-a411-7b79852aabc2' are common in more than one auxiliary tokens or is same as primary tenant.'
   at Microsoft.Azure.Management.Network.VirtualNetworkPeeringsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Network.VirtualNetworkPeeringsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Network.AddAzureVirtualNetworkPeeringCommand.AddVirtualNetworkPeering()
   at Microsoft.Azure.Commands.Network.AddAzureVirtualNetworkPeeringCommand.Execute()
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 9:37:38 AM - AddAzureVirtualNetworkPeeringCommand end processing.
DEBUG: 9:37:38 AM - AddAzureVirtualNetworkPeeringCommand end processing.

## Error output

RequestId      : 
Message        : Authentication failed for auxiliary token: 'The '1' auxiliary tokens contains duplicates which are from the same tenant. The tenant ids 'da6330d2-07f6-4e5b-a411-7b79852aabc2' are common in more than one 
                 auxiliary tokens or is same as primary tenant.'
                 StatusCode: 401
                 ReasonPhrase: Unauthorized
                 ErrorCode: AuxiliaryTokensDuplicate
                 ErrorMessage: Authentication failed for auxiliary token: 'The '1' auxiliary tokens contains duplicates which are from the same tenant. The tenant ids 'da6330d2-07f6-4e5b-a411-7b79852aabc2' are common in more 
                 than one auxiliary tokens or is same as primary tenant.'
                 OperationID : e5419fff-9dd5-4db6-aa53-4ddbd84d0c54
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {Add-AzVirtualNetworkPeering}

**Comment by dingmeng-xue** [comment]
Network team, please help to look into this issue.

**Comment by SatishBoddu-MSFT** [comment]
Hello @aconn21 Apologies for the delayed response. I see that this issue is opened a long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know.
