### ISSUE TITLE
Change Stack settings from AzureRM powershell

### ISSUE THREAD

**Issue by PatrickBuettner** [Azure/azure-powershell#12873]
## Description

I am trying to fully automate the creation of our AppServices using the RM Powershell from Azure. I'm trying to work out how to get the appservice to run using .NetCore instead of .NetFramework. The default Runtime Stack is .NET, with ASP.NET version 4.7 on it.

How does the runtime stack get updated to .NET Core if I don't want to do it manually? Thanks in advance.

## Module versions

ModuleType    Version    Name                                ExportedCommands                                              
----------        -------    ----                                    ----------------                                              
Script               5.3.0        AzureRM.Profile                {Add-AzureRmEnvironment, Clear-AzureRmContext, Clear-AzureR...
Script               6.1.0        AzureRM.Resources         {Add-AzureRmADGroupMember, Export-AzureRmResourceGroup, Get...
Script               5.0.3       AzureRM.Websites            {Edit-AzureRmWebAppBackupConfiguration, Get-AzureRmAppServi...

**Comment by dingmeng-xue** [comment]
@PatrickBuettner , I have included app service team in this thread. Did you try Az modules? The new features only go into Az modules instead of previous AzureRm

**Comment by PatrickBuettner** [comment]
Thanks for the answer. Currently I am using the AzureRm Modules. I haven't tried Az modules.
