### ISSUE TITLE
Spec verification regarding Stop-AzVM

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-powershell#12886]
Hi, I'm in CSS and I'm looking into the specification of Stop-AzVM for a customer (contact me at v-dibr for internal discussion).
The customer is trying to determine the difference in time between issuing the stop command and when the VM is actually stopped (deallocated). Which of those actions is represented by the EndTime property that is returned when issuing this command?

**Comment by dingmeng-xue** [comment]
Compute team, please help to look into it.

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by amjads1** [comment]
Assigned to Avi.

**Comment by avirishuv** [comment]
hi @dcbrown16 could you please clarify which 'EndTime' property are you mentioning here? And please share any steps that you are following so I can repro. Thanks.

**Comment by avirishuv** [comment]
@bilaakpan-ms is this something you could help check? Which timestamp is returned by Azure PowerShell for the Stop-AzVM operation - is the the 'operation acceptance' timestamp or 'operation completion' timestamp?

**Comment by avirishuv** [comment]
I checked using the Stop-AzVM -Name <vmname> -ResourceGroupName <rgname> -debug command, and in the debug output, the 'EndTime' property is the same as the time when the command to stop the VM ends processing.

**Comment by avirishuv** [comment]
@dcbrown16 closing the issue, feel free to reopen if you have any other questions on this topic.
