### ISSUE TITLE
Bad request error when trying to create Azure subscriptions programmatically in Powershell using new-azsubcription

### ISSUE THREAD

**Issue by horstwutscher** [Azure/azure-powershell#12919]
I'm logged into Azure as a ea account owner, and I wish to programmatically create a number of subscriptions, with the same configuration, however when I run the command below I receive a 'BadRequest' error.

Error Detail:

New-AzSubscription : Operation returned an invalid status code 'BadRequest'
At line:1 char:1

**Comment by dingmeng-xue** [comment]
@horstwutscher , thanks for reporting. Please provide debug information. You can get it via setting `$DebugPreference="Continue"` and run your cmdlet again.

**Comment by horstwutscher** [comment]
Hello,
is it possible to send a private message with logs?

**Comment by horstwutscher** [comment]
PS C:\_Azure\Shared-PlattformAdministration> New-AzSubscription -Name "Test1test20201009" -EnrollmentAccountObjectId "xxxx-xxxxxx-xxxxxx-xxxxxxx-xxxxxx" -OfferType "MS-AZR-0148P" #  -OwnerObjectId "xxxx-xxxxxx-xxxxxx-xxxxxxx-xxxxxx" $DebugPreference="Continue" -SilentlyContinue="Continue"
DEBUG: 07:36:33 - NewAzureRmSubscription begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 07:36:33 - using account id 'email@company.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'email@company.com', environment: 'AzureCloud', tenant: 'tenantid_xxxxx-xxxxx-xxxxxx-xxxxx'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'tenantid_xxxxx-xxxxx-xxxxxx-xxxxx', Endpoint: 'https://login.microsoftonline.com/', 
ClientId: 'clienttid_xxxxx-xxxxx-xxxxxx-xxxxx', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/tenantid_xxxxx-xxxxx-xxxxxx-xxxxx/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'tenantid_xxxxx-xxxxx-xxxxxx-xxxxx', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: 'clienttid_xxxxx-xxxxx-xxxxxx-xxxxx', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 2020-09-11T05:36:33.8100849Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file 
version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2020-09-11T05:36:33.8100849Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file 
version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2020-09-11T05:36:33.8100849Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: === Token Acquisition started:
        CacheType: null
        Authentication Target: User
        , Authority Host: login.microsoftonline.com

DEBUG: [ADAL]: Information: 2020-09-11T05:36:33.8100849Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: === Token Acquisition started:
        Authority: https://login.microsoftonline.com/tenantid_xxxxx-xxxxx-xxxxxx-xxxxx/
        Resource: https://management.core.windows.net/
        ClientId: clienttid_xxxxx-xxxxx-xxxxxx-xxxxx
        CacheType: null
        Authentication Target: User


DEBUG: [ADAL]: Verbose: 2020-09-11T05:36:33.8100849Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Verbose: 2020-09-11T05:36:33.8100849Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Information: 2020-09-11T05:36:33.8180864Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 2 items to token cache.

DEBUG: [ADAL]: Verbose: 2020-09-11T05:36:33.8180864Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Verbose: 2020-09-11T05:36:33.8180864Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Information: 2020-09-11T05:36:33.8180864Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2020-09-11T05:36:33.8180864Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2020-09-11T05:36:33.8180864Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: An expired or near expiry token was found in the cache     

DEBUG: [ADAL]: Information: 2020-09-11T05:36:33.8180864Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: An expired or near expiry token was found in the cache     

DEBUG: [ADAL]: Information: 2020-09-11T05:36:33.8180864Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Information: 2020-09-11T05:36:33.8180864Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Verbose: 2020-09-11T05:36:33.8210868Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: Refreshing access token...

DEBUG: [ADAL]: Verbose: 2020-09-11T05:36:33.8210868Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: Refreshing access token...

DEBUG: [ADAL]: Verbose: 2020-09-11T05:36:34.4210800Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: Storing token in the cache...

DEBUG: [ADAL]: Verbose: 2020-09-11T05:36:34.4210800Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: Storing token in the cache...

DEBUG: [ADAL]: Verbose: 2020-09-11T05:36:34.4210800Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: An item was stored in the cache

DEBUG: [ADAL]: Verbose: 2020-09-11T05:36:34.4210800Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: An item was stored in the cache

DEBUG: [ADAL]: Information: 2020-09-11T05:36:34.4210800Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 11.09.2020 06:36:33 +00:00

DEBUG: [ADAL]: Information: 2020-09-11T05:36:34.4210800Z: 1175e400-b43d-491b-8a37-e04075aee154 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 11.09.2020 06:36:33 +00:00Access Token Hash: xxxxxxxxxxxxxxxxxxxxDx+ybSCJExxxxxxxxxxxxxxxxxxxx
         User id: xxxx-xxxxxx-xxxxxx-xxxxxxx-xxxxxx

DEBUG: [ADAL]: Information: 2020-09-11T05:36:34.4210800Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Serializing token cache with 2 items.

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '09/11/2020 06:36:33 +00:00', MultipleResource? 'True', Tenant: 'tenantid_xxxxx-xxxxx-xxxxxx-xxxxx', UserId: 'email@company.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'email@company.com', Name: Adminaccount Cloud, IdProvider: 'https://sts.windows.net/tenantid_xxxxx-xxxxx-xxxxxx-xxxxx/', Uid: 'xxxx-xxxxxx-xxxxxx-xxxxxxx-xxxxxx'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '09/11/2020 06:36:33 +00:00' Comparing to '09/11/2020 05:36:34 +00:00' With threshold '00:05:00', 
calculated time until token expiry: '00:59:58.9929973'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/providers/Microsoft.Billing/enrollmentAccounts/xxxx-xxxxxx-xxxxxx-xxxxxxx-xxxxxx/providers/Microsoft.Subscription/createSubscription?api-version=2019-10-01-preview

Headers:
x-ms-client-request-id        : da15805b-fce1-4223-95ee-2101a8fec548
accept-language               : en-US

Body:
{
  "displayName": "Test1test20201009",
  "owners": [],
  "offerType": "MS-AZR-0148P"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-correlation-request-id   : 023c5dbf-6d90-4459-bce8-4ccd6c375fea
request-id                    : 023c5dbf-6d90-4459-bce8-4ccd6c375fea
x-gsm                         : 1.0.0.0
X-Content-Type-Options        : nosniff
x-ms-ratelimit-remaining-tenant-resource-requests: 499
x-ms-request-id               : 023c5dbf-6d90-4459-bce8-4ccd6c375fea
x-ms-routing-request-id       : SWITZERLANDNORTH:20200911T053637Z:023c5dbf-6d90-4459-bce8-4ccd6c375fea
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Fri, 11 Sep 2020 05:36:36 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "error": {
    "code": "EntitlementNotFound",
    "message": "Entitlement not found"
  },
  "code": "EntitlementNotFound",
  "message": "Entitlement not found"
}


New-AzSubscription : Operation returned an invalid status code 'BadRequest'
At line:1 char:1
+ New-AzSubscription -Name "Test1test20201009" -EnrollmentAccountObje ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzSubscription], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Subscription.Cmdlets.NewAzureRmSubscription

DEBUG: AzureQoSEvent: CommandName - New-AzSubscription; IsSuccess - False; Duration - 00:00:04.0016466;; Exception - Microsoft.Azure.Management.Subscription.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Subscription.SubscriptionOperations.<BeginCreateSubscriptionInEnrollmentAccountWithHttpMessagesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Subscription.SubscriptionOperations.<CreateSubscriptionInEnrollmentAccountWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Subscription.SubscriptionOperationsExtensions.<CreateSubscriptionInEnrollmentAccountAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Subscription.SubscriptionOperationsExtensions.CreateSubscriptionInEnrollmentAccount(ISubscriptionOperations operations, String enrollmentAccountName, SubscriptionCreationParameters body)
   at Microsoft.Azure.Commands.Subscription.Cmdlets.NewAzureRmSubscription.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 07:36:38 - NewAzureRmSubscription end processing.

**Comment by anuragdalmia** [comment]
@horstwutscher seems like you are not entitled for the dev/test subscription. Please look at https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/ea-portal-administration#enterprise-devtest-offer to have your account enabled for this. We will take the feedback to improve the error message in this case.

**Comment by horstwutscher** [comment]
Yes, that was the problem, no access to EA Portal :-)
