### ISSUE TITLE
Upgrade scheduledQueryRule to new version 2020-05-01-preview

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#12927]
We need to upgrade API to new version https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2020-05-01-preview/scheduledQueryRule_API.json

**Comment by VeryEarly** [comment]
API version 2018-04-16 schedule query rule used in latest SDK microsoft.azure.management.monitor.0.25.3-preview.

**Comment by VeryEarly** [comment]
will be released on 2022-10-12
