### ISSUE TITLE
Missing commands to manipulate Azure Monitor Workbooks

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#12923]
## Description

As best I can tell, the Microsoft Azure PowerShell module is missing commands to manage Azure Monitor Workbooks.

I found some documentation that appears to reference "workbook" resources in the `microsoft.insights` resource provider namespace.

https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/workbooks

## Steps to reproduce

```powershell
Get-Command -Module Az* -Name *workbook*
```

## Environment data

```
C:\Users\TrevorSullivan> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell

Name                     Version
----                     -------
Az                       4.5.0
Az.Accounts              1.9.2
Az.Advisor               1.1.1
Az.Aks                   1.2.0
Az.AnalysisServices      1.1.4
Az.ApiManagement         2.1.0
Az.ApplicationInsights   1.1.0
Az.Automation            1.3.7
Az.Batch                 3.1.0
Az.Billing               1.0.3
Az.Cdn                   1.4.3
Az.CognitiveServices     1.5.1
Az.Compute               4.2.1
Az.ContainerInstance     1.0.3
Az.ContainerRegistry     1.1.1
Az.DataBoxEdge           1.1.0
Az.DataFactory           1.9.0
Az.DataLakeAnalytics     1.0.2
Az.DataLakeStore         1.2.8
Az.DataShare             1.0.0
Az.DeploymentManager     1.1.0
Az.DesktopVirtualization 1.0.0
Az.DevTestLabs           1.0.2
Az.Dns                   1.1.2
Az.EventGrid             1.3.0
Az.EventHub              1.5.0
Az.FrontDoor             1.6.1
Az.Functions             1.0.1
Az.HDInsight             3.4.0
Az.HealthcareApis        1.1.0
Az.IotHub                2.5.0
Az.KeyVault              2.0.0
Az.LogicApp              1.3.2
Az.MachineLearning       1.1.3
Az.Maintenance           1.0.0
Az.ManagedServices       1.0.2
Az.MarketplaceOrdering   1.0.2
Az.Media                 1.1.1
Az.Monitor               2.0.2
Az.Network               3.3.0
Az.NotificationHubs      1.1.1
Az.OperationalInsights   2.3.0
Az.PolicyInsights        1.3.1
Az.PowerBIEmbedded       1.1.2
Az.PrivateDns            1.0.3
Az.RecoveryServices      2.11.1
Az.RedisCache            1.2.1
Az.Relay                 1.0.3
Az.Resources             2.4.0
Az.ServiceBus            1.4.1
Az.ServiceFabric         2.1.0
Az.SignalR               1.1.1
Az.Sql                   2.9.1
Az.SqlVirtualMachine     1.1.0
Az.Storage               2.4.0
Az.StorageSync           1.3.0
Az.StreamAnalytics       1.0.1
Az.Support               1.0.0
Az.TrafficManager        1.0.4
Az.Websites              1.11.0
AzureExt                 1.1.84
```

## Debug output

n/a

## Error output

n/a

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will evaluate this feature request.

**Comment by matsest** [comment]
Has there been any triage of this feature request @dingmeng-xue? :) Would also like to see this available.

**Comment by dingmeng-xue** [comment]
@matsest , Thanks for reminder. Recently, we have upgraded Az.Monitor. We will check this feature once new version of module is published.  Add tracking label for tracking purpose.

**Comment by VeryEarly** [comment]
Hi @pcgeek86 @matsest ,

I'm not able to find the public API for Microsoft.Insights/workbooks: https://learn.microsoft.com/en-us/rest/api/monitor/
please try deploy it with ARM template using  new-azresourcegroupdeployment:
https://learn.microsoft.com/en-us/powershell/module/az.resources/new-azresourcegroupdeployment?view=azps-9.0.0

**Comment by matsest** [comment]
> please try deploy it with ARM template using  new-azresourcegroupdeployment:
> 

@VeryEarly that is my current workaround for automation but there are issues with parsing long workbook files using this method, as well as issues with declaratively updating the content using ARM/Bicep.

Having it in pwsh/azcli would allow for more flexibility in deployments for my part.

(I'm also unable to find the api, but since it's available through ARM it *should* be available for pwsh?)

**Comment by VeryEarly** [comment]
> > please try deploy it with ARM template using  new-azresourcegroupdeployment:
> 
> @VeryEarly that is my current workaround for automation but there are issues with parsing long workbook files using this method, as well as issues with declaratively updating the content using ARM/Bicep.
> 
> Having it in pwsh/azcli would allow for more flexibility in deployments for my part.
> 
> (I'm also unable to find the api, but since it's available through ARM it _should_ be available for pwsh?)

Hi @matsest ,
As far as I know there are no shortcuts for pwsh/azcli to access private APIs.

Hi @asheniam do you have any idea when is this API going to be public?

**Comment by VeryEarly** [comment]
Hi fellas,
Just found it 
https://learn.microsoft.com/en-us/rest/api/application-insights/workbooks
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2021-08-01/workbooks_API.json#L36

Will support from Azure-PowerShell soon
