### ISSUE TITLE
Import-AzAksCredential allow to set local config name oder admin -admin

### ISSUE THREAD

**Issue by bbung** [Azure/azure-powershell#12941]
## Description of the new feature

If i import the credentials with the -Admin option my existing config (non -Admin) are always overwritten. 

The az cli added "-admin" to the context name in my .kube/config.

That way i could easily switch between different access_types.

## Proposed implementation details (optional)

Just add "-admin" if i use the -Admin option to my context-name 
OR/AND
introduce an new parameter -ContextName to let me specify how the context is named.

Thanks for considering the request.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will evaluate it.

**Comment by wyunchi-ms** [comment]
This issue is fixed.
