### ISSUE TITLE
Set-AzDiagnosticSetting ignores RetentionInDays, if no category specified

### ISSUE THREAD

**Issue by Johann-Hackl** [Azure/azure-powershell#12960]
Set-AzDiagnosticSetting ignores RetentionInDays, if no category specified.
By reading the docs, I'd expect that RetentionInDays works for all categories whenever no explicit category (metric and/or log) is specified.

Docs: https://docs.microsoft.com/en-us/powershell/module/az.monitor/set-azdiagnosticsetting
File: https://github.com/Azure/azure-powershell/blob/master/src/Monitor/Monitor/Diagnostics/SetAzureRmDiagnosticSettingCommand.cs
Function: private void SetRetention(DiagnosticSettingsResource properties)

### Code:
```
...
409: if (properties.Logs != null && this.IsParameterBound(c => c.Category))
...
416:     setting.RetentionPolicy = this.Category.Contains(setting.Category) ? retentionPolicy : (setting.RetentionPolicy == null ? null : setting.RetentionPolicy);
...
422: if (properties.Metrics != null && this.IsParameterBound(c => c.MetricCategory))
...
429:     setting.RetentionPolicy = this.MetricCategory.Contains(setting.Category) ? retentionPolicy : (setting.RetentionPolicy == null ? null : setting.RetentionPolicy);
...
```
=> Corresponding RetentionPolicy is only updated, if parameter is bound.

Suggest to do something like that to fix the issue:
```
...
409: if (properties.Logs != null)
...
416:     setting.RetentionPolicy = (this.Category.Contains(setting.Category) || !this.IsParameterBound(c => c.Category)) ? retentionPolicy : (setting.RetentionPolicy == null ? null : setting.RetentionPolicy);
...
422: if (properties.Metrics != null)
...
429:     setting.RetentionPolicy = (this.MetricCategory.Contains(setting.Category) || !this.IsParameterBound(c => c.MetricCategory)) ? retentionPolicy : (setting.RetentionPolicy == null ? null : setting.RetentionPolicy);
...
```

### Example to reproduce: Update diagnostic setting of a SQL database

```PowerShell
# update of RetentionInDays not working, as no categories are specified
$str = @"
{
    "ResourceId":  "<resourceId>",
    "StorageAccountId":  "<storageAccountId>",
    "Enabled":  true,
    "WorkspaceId":  "<workspaceId>",
    "Name":  "myDiag",
    "RetentionInDays":  90,
    "RetentionEnabled":  true
}
"@

$param = $str | ConvertFrom-Json
$DebugPreference = "continue"
$param | Set-AzDiagnosticSetting

# update of RetentionInDays working, as categories are specified
$str = @"
{
    "ResourceId":  "<resourceId>",
    "StorageAccountId":  "<storageAccountId>",
    "Enabled":  true,
    "WorkspaceId":  "<workspaceId>",
    "Name":  "myDiag",
    "RetentionInDays":  90,
    "RetentionEnabled":  true,
    "MetricCategory": ["Basic", "InstanceAndAppAdvanced", "WorkloadManagement"],
    "Category": ["SQLInsights", "AutomaticTuning", "QueryStoreRuntimeStatistics", "QueryStoreWaitStatistics", "Errors", "DatabaseWaitStatistics", "Timeouts", "Blocks", "Deadlocks", "DevOpsOperationsAudit", "SQLSecurityAuditEvents"]
}
"@

$param = $str | ConvertFrom-Json
$DebugPreference = "continue"
$param | Set-AzDiagnosticSetting
```

### Workaround 
As in my case (MSFT johannh), the RetentionInDays for a customer should be set on all log and metric categories, I'll have to query the current diagnostic setting using Get-AzDiagnosticSetting first, in order to grab all the log and metric categories from there to provide it again for Set-AzDiagnosticSetting.
But nevertheless, this is a unnecessary additional round-trip in my opinion.

**Comment by dingmeng-xue** [comment]
@VeryEarly , please help to look into this question.

**Comment by VeryEarly** [comment]
Hi @Johann-Hackl ,

If I understand your question correctly, you are trying to update an existing diagnostic setting to apply retention policies to all metric/log settings.

Without `Get-AzDiagnosticSetting` first, you will create a whole new setting and overwrite the existing one.

**Comment by VeryEarly** [comment]
close this issue for now, feel free to reopen if you have further questions.
