### ISSUE TITLE
Remove-AzConsumptionBudget does not trigger a log activity entry

### ISSUE THREAD

**Issue by frank9843** [Azure/azure-powershell#12970]
## Steps to reproduce

- Manually add and delete a budget in a resource group
- Go to the activity log for the resource group
=> 2 entries are added
- Add a new budget manually
- Use the set-AzConsumptionBudget to adjust the budget amount (just to verify if other powershell commands to trigger activity log entries)
- Check the activity log for the resource group
=> Another entry was added
- Remove the budget by using 
```powershell
Get-AzConsumptionBudget -ResourceGroupName "name" -Name "budgetname" | Remove-AzConsumptionBudget
```
- Check the activity log for the resource group
=> This time no log activity entry is added

Using get-AzLog to check the activity log yields the same results.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

Az.Billing: 1.0.2

**Comment by dingmeng-xue** [comment]
Consumption team, please help to look into this question.

**Comment by theelderwand** [comment]
Hi @frank9843 the following is what I'm trying out, 

![image](https://user-images.githubusercontent.com/2137463/96944875-f7319500-1490-11eb-958c-bad92d35d859.png)

Followed by, 

![image](https://user-images.githubusercontent.com/2137463/96944754-943ffe00-1490-11eb-84a9-b2568b4ba8bb.png)

I could see the following
![image](https://user-images.githubusercontent.com/2137463/96944852-e6811f00-1490-11eb-8e1d-43394798916d.png)

Seems to work as intended in the portal and via the Azure Powershell commandlets. Although the activity log took couple of minutes to show up. This is seeming to work as expected. Could you cross check the scenario again and let us know ? We will follow up on this from the information you provide us.

**Comment by frank9843** [comment]
Hi @theelderwand 
The exact command to create a budget does not work for me with a BadRequest (no further details). The activity log in Azure (yes it does log to the activity log) tells me it's because "Cost Management supports only Enterprise Agreement, Web direct and Microsoft Customer Agreement offer types". I'm on pay-as-you-go and I've worked plenty with Azure budgets both in the portal and programmatically. The fact that this doesn't work for me is possibly another unrelated bug or maybe it's because fields that are mandatory in the portal are not included in the command I'm using. Certainly the lack of information in the "Badrequest" could be considered as something to improve.
But, regarding to this bug: the remove command does end op with an activitylog entry in the portal so I can no longer reproduce this issue 👍 . Thank you for taking the time to look into it.
