### ISSUE TITLE
Get-AzureRmAutomationDscNodeConfiguration does not return Name for the configuration

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-powershell#1297]
Get-AzureRmAutomationDscNodeConfiguration does not return Name for the configuration.
If you try to use something like this:

$ConfigurationObj = Get-AzureRmAutomationDscNodeConfiguration `
    -ConfigurationName $DomainJoinConfigName `
    -ResourceGroupName  $ResourceGroupName `
    -AutomationAccountName $AutomationAccountName
The following error is logged.
Value cannot be null.
Parameter name: NodeConfigurationName (raised by: Get-AzureRmAutomationDscNodeConfiguration)
on the portal the name of the configuration is visible.

**Comment by slavizh** [comment]
Module version 1.0.1
![capture-aa](https://cloud.githubusercontent.com/assets/11890856/11188752/1e14f89e-8c95-11e5-99d3-76074dcddabf.PNG)
![capture-aa-portal](https://cloud.githubusercontent.com/assets/11890856/11188754/207dbe5e-8c95-11e5-9eb9-414b903293da.PNG)

**Comment by jodoglevy** [comment]
Thanks, I can reproduce this.

**Comment by aseemmankotia** [comment]
This renders dsc useless in azure as node configurations cannot be tied to VMs via powershell.

**Comment by jodoglevy** [comment]
This is now fixed in the latest Azure PowerShell cmdlets.
