### ISSUE TITLE
Issue with Get-AzKeyVaultSecret

### ISSUE THREAD

**Issue by basanthkakumani** [Azure/azure-powershell#12973]
## Description
I am running into below error when i am trying to run Get-AzKeyVaultSecret as Runbook, it worked fine in Powershell from my local

**Get-AzKeyVaultSecret : Parameter set cannot be resolved using the specified named parameters. At line:13 char:11 + $secret = Get-AzKeyVaultSecret -VaultName "XXXXX" -Name "XXXX ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidArgument: (:) [Get-AzKeyVaultSecret], ParameterBindingException + FullyQualifiedErrorId : AmbiguousParameterSet,Get-AzKeyVaultSecret**

## Steps to reproduce

1. Created a Runbook script using Powershell for automation
2. Script contains Connect-AzureAD to connect and then Get-AzKeyVaultSecret to get secrets of that certificate 

$secret = Get-AzKeyVaultSecret -VaultName $vaultname -Name $certificatename

## Module versions

I am using Az.KeyVault 4.0.2-preview which i think is the latest one in runbook

## Error output

**Get-AzKeyVaultSecret : Parameter set cannot be resolved using the specified named parameters. At line:13 char:11 + $secret = Get-AzKeyVaultSecret -VaultName "XXXXX" -Name "XXXX ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidArgument: (:) [Get-AzKeyVaultSecret], ParameterBindingException + FullyQualifiedErrorId : AmbiguousParameterSet,Get-AzKeyVaultSecret**

**Comment by dingmeng-xue** [comment]
@basanthkakumani , thanks for reporting.

Az.KeyVault 4.0.2-preview is a preview version which contains new format of cmdlet signature. If you just use it in automation environment, stable version is recommended. Please try to use Az.KeyVault 2.1.0

**Comment by basanthkakumani** [comment]
thank you that worked.
