### ISSUE TITLE
Docker Image: Install module for all users?

### ISSUE THREAD

**Issue by J0F3** [Azure/azure-powershell#12972]
## Description
Is it by intend that the module is installed only for root in the container image?

Can we add a `-Scope AllUsers` so the module is accessible also for other users in the container?

**Backstory:**
We wanted to use this image as base for a custom image which runs with a standard user (instead of root). But because the module is installed under `/root/.local/share/powershell/Modules`  the module can not be loaded by other users. If the module would be installed under `/opt/microsoft/powershell/7/Modules`  by using the `-Scope AllUsers` parameters is would be also usable when running not as root.

Thanks!

**Comment by dingmeng-xue** [comment]
Thanks for reporting. 

@J0F3 , we didn't consider it because we thought docker container is used per user. We didn't set scope and just used default one. We will evaluate it.

**Comment by J0F3** [comment]
Thanks.

Maybe I can elaborate our use case a bit more:
We would like to use the container image to run an CI/CD pipeline with it. So we want to run as a standard user in the container so the tool set etc. in the image can not be modified form the pipeline as much as possible. To the use case would be still single user, but as a standard not elevated user, which can not modify the tools included in the image.
