### ISSUE TITLE
Remove-AzWvdUserSession doesn't work when Resource Group is locked.

### ISSUE THREAD

**Issue by stefan923456** [Azure/azure-powershell#12987]
We use some Azure Automation to allow the users to Self Service their Logoff when application freeze the WVD session.

For WVD classic it was this command: invoke-RdsUserSessionLogoff and it worked fine.

For WVDv2 (Spring Update) it is this command: Remove-AzWvdUserSession

And it fails horribly because we make it a best practice to put a delete lock on the Resource Groups.

So please make "Remove-AzWvdUserSession" work when a Delete Lock is in place, or rename the command to invoke-AzWvdUserSessionLogoff.

Thank you very much!

**Comment by dingmeng-xue** [comment]
@stefan923456 , If resource group has a delete lock, the resource within this group cannot be deleted too. It's current default behavior in Azure.

We recommend to remove delete lock at the first via `Remove-AzResourceLock`. It will be a safe way to all users.

**Comment by stefan923456** [comment]
> @stefan923456 , If resource group has a delete lock, the resource within this group cannot be deleted too. It's current default behavior in Azure.
> 
> We recommend to remove delete lock at the first via `Remove-AzResourceLock`. It will be a safe way to all users.

@dingmeng-xue thank you for your reply. I know why it doesn't work, but it should. The Remove-AzWVDUserSessions does not delete anything, it only logs off a user. The old commandlet name was better: "invoke-RdsUserSessionLogoff" and that command does the same for WVD Classic and works perfectly with Delete Lock on the Resource Group. Please make the new command work as the old command with an in place DeleteLock. Our users trigger the usage of this command via PowerAutomate to self-service their logoff in case of session hangs. The DeleteLock is also required to prevent accidental removal of servers. I don't want to remove the lock, remove the user session and put the lock back on via the script, that put's the servers at risk of being deleted.

So please change the behaviour of this commandlet or create a second commandlet called: "Logoff-AzWvdUserSessions" that will not be blocked by the DeleteLocks. 

Thank you very much.

**Comment by Pistle** [comment]
As an administrator, you may need to lock a subscription, resource group, or resource to prevent other users in your organization from accidentally deleting or modifying critical resources. You can set the lock level to CanNotDelete or ReadOnly. In the portal, the locks are called Delete and Read-only respectively.

CanNotDelete means authorized users can still read and modify a resource, but they can't delete the resource.

ReadOnly means authorized users can read a resource, but they can't delete or update the resource. Applying this lock is similar to restricting all authorized users to the permissions granted by the Reader role.

**Comment by dingmeng-xue** [comment]
@wyunchi-ms , please verify if we can resolve this problem on client side.

**Comment by dolauli** [comment]
WVD classic (WindowsVirtualDesktop) is owned by service team, which is not an Azure PowerShell module. So I do not even find how they implement invoke-RdsUserSessionLogoff. I guess Remove-AzWvdUserSession and  invoke-RdsUserSessionLogoff
actually do not call the same backend API. Need service team support on it. @datr93

**Comment by datr93** [comment]
In legacy user session is not an arm object in arm it its. So resource group lock will lock the user session object.

**Comment by SatishBoddu-MSFT** [comment]
Hello @datr93 Please suggest if we are good to close this issue?
