### ISSUE TITLE
Inherit content type using Set-AzStorageBlobContent like in Azure Portal

### ISSUE THREAD

**Issue by ferristocrat** [Azure/azure-powershell#12989]
## Description
When I manually upload a file to blob storage through the Azure portal, it automatically assigns the correct CONTENT-TYPE of `text/html`, but when using Set-AzStorageBlobContent the CONTENT-TYPE is set to `application/octet-stream`

Is there a way to automatically assign the CONTENT-TYPE when using Set-AzStorageBlobContent as is done when uploading a file through the portal?

![image](https://user-images.githubusercontent.com/7063002/93388017-f157ec80-f81e-11ea-9786-be9139d58d87.png)

## Steps to reproduce

```powershell
Set-AzStorageBlobContent -File $fileDestination -Container $ContainerName -Blob $BlobName -Context $Ctx -Force

```

**Comment by dingmeng-xue** [comment]
Storage team, please help to look into this question.

**Comment by blueww** [comment]
@ferristocrat

Set-AzStorageBlobContent currently won't automatically assign the CONTENT-TYPE when upload blob, but user can set customized contenttype with the cmdlet. And user can also get the content-type easily with PSH script.

Like following script will first get contenttype with `[System.Web.MimeMapping]::GetMimeMapping($filepath)`， then set the content type in upload blob with Set-AzStorageBlobContent.

```
$filepath = "c:\temp\index.html"
$contentType = [System.Web.MimeMapping]::GetMimeMapping($filepath)
Set-AzStorageBlobContent -File $filepath -Container $containerName -Force -Properties @{"ContentType" = $contentType} -Context $ctx

   AccountName: ***, ContainerName: ***

Name                 BlobType  Length          ContentType                    LastModified         AccessTier SnapshotTime                 IsDeleted  VersionId                     
----                 --------  ------          -----------                    ------------         ---------- ------------                 ---------  ---------                     
index.html           BlockBlob 403116          text/html                      2020-09-17 02:20:11Z Hot                                     False                 
```

Since it's easy to do with PSH script, we might won't add automatic Content-type assignment to Set-AzStorageBlobContent recently. Let us know if you have any concern.

**Comment by blueww** [comment]
@ferristocrat
I will close this issue as the help doc is updated for this scenario, and not see more comments from you for long time.
Thanks for raising the issue!
Feel free to contact us again if need any further assistance on Azure PowerShell.

**Comment by florianwachs** [comment]
Sadly this doesn't work with Powershell (Core) because it relies on System.Web

**Comment by blueww** [comment]
@florianwachs 
On Powershell core if you can read registry, you can get content type from registry with following function:
```powershell
function Get-MimeType()
{
  param($extension = $null);
  $mimeType = $null;
  if ( $null -ne $extension )
  {
    $drive = Get-PSDrive HKCR -ErrorAction SilentlyContinue;
    if ( $null -eq $drive )
    {
      $drive = New-PSDrive -Name HKCR -PSProvider Registry -Root HKEY_CLASSES_ROOT
    }
    $mimeType = (Get-ItemProperty HKCR:$extension)."Content Type";
  }
  $mimeType;
}
```
usage as :
```powershell
PS C:\> $filepath = "c:\temp\index.html"

PS C:\> Get-MimeType (get-item $filepath).Extension
text/html
```

There are also some third-party file type guesser programs, you can refer https://stackoverflow.com/a/11698572/5361550

**Comment by florianwachs** [comment]
@blueww Thanks a lot! That perfectly fits my needs. Thank you and have a great day.
