### ISSUE TITLE
Need .MSI offline installer for Windows Server 2019 Standard

### ISSUE THREAD

**Issue by dm10169** [Azure/azure-powershell#12993]
I need help getting a .MSI installer for a silent automation install for a huge project I'm working on supporting the government.  Any help would greatly be appreciated.  It seems like get an .MSI installer is harder than expected, I guess.

**Comment by dingmeng-xue** [comment]
Thanks for contacting us. 

MSI supports silent installation. Please reference this page http://www.silentinstall.org/msiexec.

Do you meet other challenging about Installer?

**Comment by dcaro** [comment]
@dm10169 you can find the latest installer from the release tag: 
https://github.com/Azure/azure-powershell/releases/tag/v4.7.0-September2020 

The MSI installer is located at the very bottom under "Assets"
