### ISSUE TITLE
Possible breaking change Get-AzureVM breaks pipeline with Out-Gridview (#3047)

### ISSUE THREAD

**Issue by MaxTrinidad** [Azure/azure-powershell#13]
(reposted from https://github.com/Azure/azure-sdk-tools/issues/3047 - 11/04/2014)

Get-AzureVM breaks pipeline with Out-Gridview. I have Trevor Sullivan confirmed this issue.

This is PowerShell Azure Cmdlets version 0.8.10.1 in PowerShell 4.0. 

PS C:> $vm = Get-AzureVM | Out-Gridview -PassThru
 Get-AzureVM : The pipeline has been stopped.
 At line:1 char:7
•$vm = Get-AzureVM | Out-Gridview -PassThru
• ~~~~~~~~~~~ ◦CategoryInfo : CloseError: (:) [Get-AzureVM], PipelineStoppedException
◦FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.GetAzureVMCommand Out-Gridview : Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index At line:1 char:21

•$vm = Get-AzureVM | Out-Gridview -PassThru
• ~~~~~~~~~~~~~~~~~~~~~~ ◦CategoryInfo : NotSpecified: (:) [Out-GridView], ArgumentOutOfRangeException
◦FullyQualifiedErrorId : System.ArgumentOutOfRangeException,Microsoft.PowerShell.Commands.OutGridViewCommand 

Thanks,
 Maximo Trinidad
 Microsoft MVP - PowerShell

**Comment by doctordns** [comment]
I just tried it, using 0.8.9 against December 2014 PowerShell v5 beta. And it works just fine!

**Comment by MaxTrinidad** [comment]
Awesome!! Just to confirm that on the December release this issue was corrected.  
Microsoft Azure PowerShell download version: 
Version   : 0.8.12                                              
Title     : Microsoft Azure PowerShell with Microsoft Azure SDK 
Published : 12/11/2014 7:00:00 AM                               
Author    : Microsoft Corporation                               

Thank You!

**Comment by ruano84** [comment]
Hi, i just tested 

>Get-AzureVM | Out-Gridview -PassThru

 with 0.8.13 and gives me the same error:

>Get-AzureVM : Se ha detenido la canalización.
>En línea: 1 Carácter: 1
>+ Get-AzureVM | Out-GridView -Title "Select a VM ." -PassThru
>+ ~~~~~~~~~~~
>    + CategoryInfo          : CloseError: (:) [Get-AzureVM], PipelineStoppedException
>    + FullyQualifiedErrorId : >Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.GetAzureVMCommand

The "(Get-Module Azure).Version" output:
>Major  Minor  Build  Revision
>-----  -----  -----  --------
>0      8      13     -1

**Comment by MaxTrinidad** [comment]
Interesting!  Azure PowerShell version 0.8.13 has been release yet thru the Microsoft Azure download site which is still 0.8.12 December download.   This issue was corrected in 0.8.12.

If you downloads the Azure PowerShell from Github then is possible this error will come back again.

Thx for the email.
Max

**Comment by KeithHill** [comment]
I just tested this as well....with 0.8.13 and I have the issues as well.  Any updates on this?

**Comment by MaxTrinidad** [comment]
It has been fixed on 0.8.14 (2/12/2015)
Version   : 0.8.14                                              
Title     : Microsoft Azure PowerShell with Microsoft Azure SDK 
Published : 2/12/2015 7:00:00 AM                                
Author    : Microsoft Corporation                               
                                                                
PS C:\>                                                         
PS C:\>                                                         
PS C:\> $x = Get-AzureVM | Out-GridView -PassThru;              
PS C:\> $x.Name                                                 
MyTestSQLServer        
:)                                         

Max TrinidadMicrosoft MVP – PowerShell (7yrs)SAPIEN Technologies MVP 2015
  Florida PowerShell User Group: http://www.flpsug.com/
  Blog: http://www.maxtblog.com/Twitter: @MaxTrinidad 
Member of: MTC, INETA and PASS.

Date: Thu, 19 Feb 2015 11:09:46 -0800

**Comment by doctordns** [comment]
Where do we download 0.8.14?

**Comment by georgiosd** [comment]
Still appears in 0.9.1 :(

**Comment by devigned** [comment]
@markcowl looks like this is still an issue

**Comment by MaxTrinidad** [comment]
Guys!!  
I just installed Azure PowerShell version 0.9.1 (Published : 5/4/2015 8:00:00 AM) today.  I the following command works:

PS C:\Users\mtrinidad>
PS C:\Users\mtrinidad> $vm = Get-AzureVM | Out-Gridview -PassThru
PS C:\Users\mtrinidad> $vm

ServiceName        Name        Status
-----------        ----        ------
MyMaxPITcloudSvc05 SuperNova01 StoppedDeallocated

Now, I did recently installed WMF5.0 on my Windows 7 SP1 desktop.  So, if you still having some issues, it may be something with PowerShell version you're using,

Thanks for the heads up!
Max

**Comment by georgiosd** [comment]
Try adding -Title too

**Comment by MaxTrinidad** [comment]
I just test Out-Gridview with both -Passthru and -Title.  It's working for me. (see image)
![azuregridviewnoerror](https://cloud.githubusercontent.com/assets/7338470/7773290/86f4e2d0-0071-11e5-8230-dca65803ac5b.jpg)

**Comment by MaxTrinidad** [comment]
Sorry! I press the wrong button. :P

**Comment by MaxTrinidad** [comment]
I just test Out-Gridview with both -Passthru and -Title. It's working for me. (see image)
![azuregridviewnoerror](https://cloud.githubusercontent.com/assets/7338470/7773336/df4eb62c-0071-11e5-88e9-c8f9538be3bb.jpg)

**Comment by georgiosd** [comment]
Very weird. I upgraded and checked version was kosher. What do you
recommend? Reinstall?

**Comment by MaxTrinidad** [comment]
Just to make sure. 
1. Which version of Windows you are on? 7/8.1/10. Which PowerShell version or WMF? 4.0 or 5.0 May Preview.
2. Are you sure you're on Azure PowerShell 0.9.1 (May 2015 build)? Older version had the problem.   
3. And,  is .NET Framework 4.0 (or >) installed?
4. What's the system culture? is this a non-US Windows version. 

Maybe we can get some direction.
:)

**Comment by georgiosd** [comment]
1. Windows 8.1, Powershell 4! No WMF.
2. [This](http://www.maxtblog.com/2014/03/find-your-windows-azure-powershell-cmdlets-version/) script tells me I'm on 0.9.1, I upgraded with Web PI last night.
3. I got all the default .NETs + VS2013 + VS2015 RC
4. Uhm, keyboard is en-US, culture is I believe en-GB

**Comment by MaxTrinidad** [comment]
OK.  It won't hurt but can you try loading the WMF 5.0 April Preview for Windows 8.1.  Here's the link:http://www.microsoft.com/en-us/download/details.aspx?id=46889 

Apologies! in the previous comment I mention WMF 5.0 May Preview, but I meant to say April Preview. :)

There's a chance that it ha to be something with PowerShell 4.0 then in Version 5.0 gets corrected.
Can you give it a try?
Max

**Comment by osakanataro** [comment]
Same problem occurred.
"$vm = Get-AzureVM | Out-Gridview -PassThru" could not work powershell 3.0?


```
PS C:\> (Get-Module azure).version

Major  Minor  Build  Revision
-----  -----  -----  --------
0      9      2      -1


PS C:\> $PSversiontable

Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34209
BuildVersion                   6.2.9200.16398
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2

PS C:\>
```

**Comment by singhkay** [comment]
Looks like this breaks only in PowerShell v3.0 or 4.0. @huangpf Can you investigate why that would be the case?

**Comment by huangpf** [comment]
It's a bug in PS 3.0 and 4.0 in that it fails to load the object and/or type info, if ```TableControl``` is not correctly configured.

This will be patched on our end for 3.0/4.0 in the incoming release. Stay tune. Thanks.

**Comment by singhkay** [comment]
Thanks for the update @huangpf! Closing as fixed

**Comment by AzureRT** [comment]
@singhkay It's only fixed in the new release.

**Comment by huangpf** [comment]
@singhkay It's only fixed in the new release.
