### ISSUE TITLE
[Az.Functions] Need to implement StacksAPI to display what Runtime and RuntimeVersion are available for function app creation

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-powershell#13002]
## Description

Need to implement StacksAPI to display what Runtime and RuntimeVersion are available for function app creation.

cc: @anirudhgarg @stefanushinardi

**Comment by dingmeng-xue** [comment]
Add Functions label

**Comment by Francisco-Gamino** [comment]
This issue was fixed back in September 2020.
