### ISSUE TITLE
AzureUSGovernment Environment Missing Trailing Slashes

### ISSUE THREAD

**Issue by ExchMaster** [Azure/azure-powershell#1301]
When loading the AzureUSGovernment environment and attempting to authencate, the token is rejected with the following error:

PS C:\> Add-AzureRmAccount -Environment $AzUSCloud
Add-AzureRmAccount : AuthenticationFailed: The access token has been obtained from wrong audience or resource
'https://management.core.usgovcloudapi.net'. It should exactly match (including forward slash) with one of the allowed
audiences 'https://management.core.usgovcloudapi.net/','https://management.usgovcloudapi.net/'.
At line:1 char:1
+ Add-AzureRmAccount -Environment $AzUSCloud
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzureRmAccount], CloudException
    + FullyQualifiedErrorId : Hyak.Common.CloudException,Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

For information regarding the correct settings for the environment variables, please view the following link:

http://blogs.msdn.com/b/azuregov/archive/2015/10/08/configure-arm-on-azure-gc.aspx

Utilizing the settings as specified in that URL allows authentication to take place successfully.

**Comment by devigned** [comment]
If you would like to add a PR for this, we'd review it.

**Comment by markcowl** [comment]
@ExchMaster This is fixed, the code is now in the repo here: https://github.com/Azure/azure-powershell/blob/dev/src/Common/Commands.Common.Authentication/Models/AzureEnvironment.Methods.cs#L352
