### ISSUE TITLE
[AzureStack] Az.Accounts 2.0.1-preview - Login is broken in disconnected ADFS

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#13010]
## Description

in a disconnected ADFS environment, login-azaccount is broken . It seems we are trying to reach the internet . I will edit this issue and more details as we repro the issue

## Steps to reproduce
In AzureStack disconeected environment, Login to AzureStack with auto context save enabled. 
Open a new session and then do Import-Module Az.Accounts

```powershell

```

## Environment data
Azure stack 
Powershell 5.1/ PS Core 7

## Module versions
Az.Accounts - 2.0.1-preview

## Debug output

PS C:\Users\Administrator> import-module powershellget

PS C:\Users\Administrator> get-module

ModuleType Version    Name                                ExportedCommands                                                                                            
---------- -------    ----                                ----------------                                                                                            
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                         
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                          
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                   
Script     1.4.7      PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}                                   
Script     2.2.4.1    powershellget                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}                                       

PS C:\Users\Administrator> Import-Module "C:\Az\Az.Accounts\2.0.1\Az.Accounts.psd1" -Verbose
VERBOSE: Loading module from path 'C:\Az\Az.Accounts\2.0.1\Az.Accounts.psd1'.
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Authentication.Abstractions.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Authentication.Abstractions.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Authentication.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Authentication.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Authentication.ResourceManager.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Authentication.ResourceManager.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Authorization.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Authorization.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Compute.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Compute.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Graph.Rbac.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Graph.Rbac.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Monitor.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Monitor.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Network.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Network.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.PolicyInsights.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.PolicyInsights.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.ResourceManager.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.ResourceManager.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Common.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Common.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Storage.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Storage.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Storage.Management.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Storage.Management.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.KeyVault.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.KeyVault.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Websites.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Websites.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Hyak.Common.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Hyak.Common.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.ApplicationInsights.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.ApplicationInsights.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.Common.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.Common.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Rest.ClientRuntime.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Rest.ClientRuntime.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Rest.ClientRuntime.Azure.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Rest.ClientRuntime.Azure.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.WindowsAzure.Storage.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.WindowsAzure.Storage.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.WindowsAzure.Storage.DataMovement.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.WindowsAzure.Storage.DataMovement.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Aks.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Clients.Aks.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Strategies.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Strategies.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Authenticators.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Azure.PowerShell.Authenticators.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Extensions.Caching.Abstractions.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Extensions.Caching.Abstractions.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Extensions.Caching.Memory.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Extensions.Caching.Memory.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Extensions.DependencyInjection.Abstractions.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Extensions.DependencyInjection.Abstractions.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Extensions.Options.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Extensions.Options.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Extensions.Primitives.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Extensions.Primitives.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Identity.Client.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Identity.Client.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Identity.Client.Extensions.Msal.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\Microsoft.Identity.Client.Extensions.Msal.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\System.Runtime.CompilerServices.Unsafe.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Az\Az.Accounts\2.0.1\System.Runtime.CompilerServices.Unsafe.dll'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Az\Az.Accounts\2.0.1\Accounts.format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Az\Az.Accounts\2.0.1\Accounts.generated.format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module Az.Accounts.
VERBOSE: Loading module from path 'C:\Az\Az.Accounts\2.0.1\Az.Accounts.psm1'.
Import-Module : An error occurred while sending the request.
At C:\Az\Az.Accounts\2.0.1\Az.Accounts.psm1:83 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], HttpRequestException
    + FullyQualifiedErrorId : System.Net.Http.HttpRequestException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
VERBOSE: Exporting function 'Test-DotNet'.
VERBOSE: Exporting function 'Write-InstallationCheckToFile'.

PS C:\Users\Administrator> get-module

ModuleType Version    Name                                ExportedCommands                                                                                            
---------- -------    ----                                ----------------                                                                                            
Script     2.0.1      Az.Accounts                                                                                                                                     
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                         
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                          
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}                   
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                   
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}                             
Script     1.4.7      PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}                                   
Script     2.2.4.1    powershellget                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}                                       

PS C:\Users\Administrator> Import-Module "C:\Az\Az.Accounts\2.0.1\Az.Accounts.psd1" -Verbose
VERBOSE: Loading module from path 'C:\Az\Az.Accounts\2.0.1\Az.Accounts.psd1'.

PS C:\Users\Administrator> Import-Module "C:\Az\Az.Accounts\2.0.1\Az.Accounts.psd1" -Verbose
VERBOSE: Loading module from path 'C:\Az\Az.Accounts\2.0.1\Az.Accounts.psd1'.

PS C:\Users\Administrator> get-module

ModuleType Version    Name                                ExportedCommands                                                                                            
---------- -------    ----                                ----------------                                                                                            
Script     2.0.1      Az.Accounts                                                                                                                                     
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                         
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                          
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}                   
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                   
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}                             
Script     1.4.7      PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}                                   
Script     2.2.4.1    powershellget                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}                                       

PS C:\Users\Administrator> $error[0]
Method invocation failed because [Microsoft.Azure.PowerShell.Authenticators.DesktopAuthenticatorBuilder] does not contain a method named 'Apply'.
At C:\Az\Az.Accounts\2.0.1\PostImportScripts\LoadAuthenticators.ps1:3 char:6
+         [Microsoft.Azure.PowerShell.Authenticators.DesktopAuthenticat ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
 

PS C:\Users\Administrator> $error[1]
Import-Module : An error occurred while sending the request.
At C:\Az\Az.Accounts\2.0.1\Az.Accounts.psm1:83 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], HttpRequestException
    + FullyQualifiedErrorId : System.Net.Http.HttpRequestException,Microsoft.PowerShell.Commands.ImportModuleCommand
 

PS C:\Users\Administrator>

## Error output

PS C:\Users\Administrator> $error[1] | fl *
Import-Module : An error occurred while sending the request.
At C:\Az\Az.Accounts\2.0.1\Az.Accounts.psm1:83 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], HttpRequestException
    + FullyQualifiedErrorId : System.Net.Http.HttpRequestException,Microsoft.PowerShell.Commands.ImportModuleCommand
 

PS C:\Users\Administrator> $error[1].ScriptStackTrace
at <ScriptBlock>, C:\Az\Az.Accounts\2.0.1\Az.Accounts.psm1: line 83
at <ScriptBlock>, <No file>: line 1

PS C:\Users\Administrator> $error[1].Exception.StackTrace
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Http.HttpManager.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Http.HttpManager.<ExecuteWithRetryAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Http.HttpManager.<SendGetAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.<ExecuteRequestAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.<DiscoverAadInstanceAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.<SendInstanceDiscoveryRequestAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.<FetchAllDiscoveryMetadataAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Instance.Discovery.NetworkMetadataProvider.<GetMetadataAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Instance.Discovery.InstanceDiscoveryManager.<FetchNetworkMetadataOrFallbackAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Instance.Discovery.InstanceDiscoveryManager.<GetMetadataEntryAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Instance.Discovery.InstanceDiscoveryManager.<GetMetadataEntryTryAvoidNetworkAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.TokenCache.<Microsoft-Identity-Client-ITokenCacheInternal-GetAccountsAsync>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Cache.CacheSessionManager.<GetAccountsAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ClientApplicationBase.<GetAccountsAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.<GetAccountIdentifiersAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.<CreateAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Common.Authentication.SharedTokenCacheClientFactory.CreateCacheHelper(String clientId)
   at Microsoft.Azure.Commands.Common.Authentication.SharedTokenCacheClientFactory.GetCacheHelper(String clientId)
   at Microsoft.Azure.Commands.Common.Authentication.SharedTokenCacheClientFactory.SupportCachePersistence(String& message)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.OnImport()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.ExecuteModuleInitializer(Assembly assembly, Type[] assemblyTypes, Boolean isModuleLoad)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInf
o moduleInfo, Boolean isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String helpFile, Type& randomCmdletToCheckLinkDemand, Type& 
randomProviderToCheckLinkDemand)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo
, Boolean isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly as
semblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boole
an loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object p
rivateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by isra-fel** [comment]
+ @erich-wang FYI

**Comment by dingmeng-xue** [comment]
Hi @bganapa , do you still see the same error in the latest Az.Accounts?

**Comment by bganapa** [comment]
We tried to repro and we could not repro in a purely disconnected environment

The error might have happened  when the MSAL cache is already populated with azure login information and then the environment was taken out of network. The MSAL cache now has the connected environment information as well and might have failed. 

The solution for for this issue is to clear the cache. I believe we can close this issue for now.
