### ISSUE TITLE
Getting MethodAccessException using AzureRM cmdlets

### ISSUE THREAD

**Issue by drub0y** [Azure/azure-powershell#1303]
I get the exception below for almost all the AzureRM related cmdlets. I'm running version `1.0.1` of AzureRM installed via PowershellGet, which appears to have installed latest version of `AzureRM.Resources` which is `0.10.0`. This is on a Windows 10 box running the latest (`10586.3`) build.

I've run these successfully before on another workstation in the exact same state, not sure what's going on with this particular workstation.

```
Move-AzureRmResource : Attempt by method 'Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implement
ation.ResourceManagerCmdletBase.BeginProcessing()' to access method
'Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.BeginProcessing()' failed.
At line:1 char:1
+ Move-AzureRmResource -DestinationResourceGroupName 'WWWUK' -ResourceI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Move-AzureRmResource], MethodAccessException
    + FullyQualifiedErrorId : System.MethodAccessException,Microsoft.Azure.Commands.ResourceManager
   .Cmdlets.Implementation.MoveAzureResourceCommand
```

**Comment by drub0y** [comment]
I completely uninstalled all modules and reinstalled them (all via Package Manager + PowershellGet) and now everything's working. I don't know what might have screwed it up the first time. I did have the Web Platform Installer (MSI based) version of the Azure Powershell tools installed and I uninstalled all that as well, so maybe that was mucking things up?

**Comment by devigned** [comment]
This should not have installed 0.10.0 of Resources. There were some incompatible changes in 1.0 and 0.10 (1.0 pre), so if the 0.10 libs were loaded in the same session, I'd expect some issues like this. If you install from Gallery or WebPI, you should not expect to get 0.10 and thus not have this issue.
