### ISSUE TITLE
[Az.Tools.Installer] Update-AzModule doesn't work with -WhatIf parameter

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#13054]
`Update-AzModule -RemovePrevious -WhatIf` doesn't output anything. It just hangs.

`Update-AzModule -RemovePrevious -WhatIf -Verbose` shows that it's stuck at AzureAdPreview module which shouldn't be touched anyway.

**Comment by erich-wang** [comment]
Thanks for reporting the issue, @msJinLei , could you take a look?

**Comment by msJinLei** [comment]
> `Update-AzModule -RemovePrevious -WhatIf` doesn't output anything. It just hangs.
> 
> `Update-AzModule -RemovePrevious -WhatIf -Verbose` shows that it's stuck at AzureAdPreview module which shouldn't be touched anyway.

@alexandair could you collect the logs of  "Update-AzModule -RemovePrevious -WhatIf -Verbose -Debug", and paste them here?
It usually takes 3 mins to run the "Update-AzModule -RemovePrevious -WhatIf -Verbose" and you will see the progress bar during the process.

**Comment by alexandair** [comment]
@msJinLei 
In the meantime, I've updated Az module and output is now different, but still there are some things to discuss.
First, execution of that command was 5:24 on my system. Way too long.
Second, there are some modules that are not part of Az module set (installed separately) that Update-AzModule is checking. Those modules (AzureADPreview, AzureADAuthenticationMethods, Az.ConnectedMachine, Az.ResourceGraph, Az.Tools.Migration) shouldn't be considered for an update at all.

<details>
<summary>Click here to see  debug info</summary>
<pre>
❯ Update-AzModule -RemovePrevious -WhatIf -Verbose -Debug
DEBUG: Powershell Core Version 7.0.3
VERBOSE: Populating RepositorySourceLocation property for module Az.
VERBOSE: Populating RepositorySourceLocation property for module Az.Accounts.
VERBOSE: Populating RepositorySourceLocation property for module Az.Advisor.
VERBOSE: Populating RepositorySourceLocation property for module Az.Aks.
VERBOSE: Populating RepositorySourceLocation property for module Az.AnalysisServices.
VERBOSE: Populating RepositorySourceLocation property for module Az.ApiManagement.
VERBOSE: Populating RepositorySourceLocation property for module Az.ApplicationInsights.
VERBOSE: Populating RepositorySourceLocation property for module Az.Automation.
VERBOSE: Populating RepositorySourceLocation property for module Az.Batch.
VERBOSE: Populating RepositorySourceLocation property for module Az.Billing.
VERBOSE: Populating RepositorySourceLocation property for module Az.Cdn.
VERBOSE: Populating RepositorySourceLocation property for module Az.CognitiveServices.
VERBOSE: Populating RepositorySourceLocation property for module Az.Compute.
VERBOSE: Populating RepositorySourceLocation property for module Az.ConnectedMachine.
VERBOSE: Loading module from path 'C:\Users\aleksandar\Documents\PowerShell\Modules\Az.ConnectedMachine\0.2.0\Az.ConnectedMachine.psm1'.
VERBOSE: Populating RepositorySourceLocation property for module Az.ContainerInstance.
VERBOSE: Populating RepositorySourceLocation property for module Az.ContainerRegistry.
VERBOSE: Populating RepositorySourceLocation property for module Az.DataBoxEdge.
VERBOSE: Populating RepositorySourceLocation property for module Az.DataFactory.
VERBOSE: Populating RepositorySourceLocation property for module Az.DataLakeAnalytics.
VERBOSE: Populating RepositorySourceLocation property for module Az.DataLakeStore.
VERBOSE: Populating RepositorySourceLocation property for module Az.DataShare.
VERBOSE: Populating RepositorySourceLocation property for module Az.DeploymentManager.
VERBOSE: Populating RepositorySourceLocation property for module Az.DesktopVirtualization.
VERBOSE: Loading module from path 'C:\Users\aleksandar\Documents\PowerShell\Modules\Az.DesktopVirtualization\2.0.0\Az.DesktopVirtualization.psm1'.
VERBOSE: Populating RepositorySourceLocation property for module Az.DevTestLabs.
VERBOSE: Populating RepositorySourceLocation property for module Az.Dns.
VERBOSE: Populating RepositorySourceLocation property for module Az.EventGrid.
VERBOSE: Populating RepositorySourceLocation property for module Az.EventHub.
VERBOSE: Populating RepositorySourceLocation property for module Az.FrontDoor.
VERBOSE: Populating RepositorySourceLocation property for module Az.Functions.
VERBOSE: Populating RepositorySourceLocation property for module Az.HDInsight.
VERBOSE: Populating RepositorySourceLocation property for module Az.HealthcareApis.
VERBOSE: Populating RepositorySourceLocation property for module Az.IotHub.
VERBOSE: Populating RepositorySourceLocation property for module Az.KeyVault.
VERBOSE: Populating RepositorySourceLocation property for module Az.Kusto.
VERBOSE: Loading module from path 'C:\Users\aleksandar\Documents\PowerShell\Modules\Az.Kusto\1.0.0\Az.Kusto.psm1'.
VERBOSE: Populating RepositorySourceLocation property for module Az.LogicApp.
VERBOSE: Populating RepositorySourceLocation property for module Az.MachineLearning.
VERBOSE: Populating RepositorySourceLocation property for module Az.Maintenance.
VERBOSE: Populating RepositorySourceLocation property for module Az.ManagedServices.
VERBOSE: Populating RepositorySourceLocation property for module Az.MarketplaceOrdering.
VERBOSE: Populating RepositorySourceLocation property for module Az.Media.
VERBOSE: Populating RepositorySourceLocation property for module Az.Monitor.
VERBOSE: Populating RepositorySourceLocation property for module Az.Network.
VERBOSE: Populating RepositorySourceLocation property for module Az.NotificationHubs.
VERBOSE: Populating RepositorySourceLocation property for module Az.OperationalInsights.
VERBOSE: Populating RepositorySourceLocation property for module Az.PolicyInsights.
VERBOSE: Populating RepositorySourceLocation property for module Az.PowerBIEmbedded.
VERBOSE: Populating RepositorySourceLocation property for module Az.PrivateDns.
VERBOSE: Populating RepositorySourceLocation property for module Az.RecoveryServices.
VERBOSE: Populating RepositorySourceLocation property for module Az.RedisCache.
VERBOSE: Populating RepositorySourceLocation property for module Az.Relay.
VERBOSE: Populating RepositorySourceLocation property for module Az.ResourceGraph.
VERBOSE: Populating RepositorySourceLocation property for module Az.Resources.
VERBOSE: Populating RepositorySourceLocation property for module Az.ServiceBus.
VERBOSE: Populating RepositorySourceLocation property for module Az.ServiceFabric.
VERBOSE: Populating RepositorySourceLocation property for module Az.SignalR.
VERBOSE: Populating RepositorySourceLocation property for module Az.Sql.
VERBOSE: Populating RepositorySourceLocation property for module Az.SqlVirtualMachine.
VERBOSE: Populating RepositorySourceLocation property for module Az.Storage.
VERBOSE: Populating RepositorySourceLocation property for module Az.StorageSync.
VERBOSE: Populating RepositorySourceLocation property for module Az.StreamAnalytics.
VERBOSE: Populating RepositorySourceLocation property for module Az.Support.
VERBOSE: Populating RepositorySourceLocation property for module Az.Tools.Installer.
VERBOSE: Loading module from path 'C:\Users\aleksandar\Documents\PowerShell\Modules\Az.Tools.Installer\0.1.0\Az.Tools.Installer.psm1'.
VERBOSE: Populating RepositorySourceLocation property for module Az.Tools.Migration.
VERBOSE: Populating RepositorySourceLocation property for module Az.TrafficManager.
VERBOSE: Populating RepositorySourceLocation property for module Az.Websites.
VERBOSE: Populating RepositorySourceLocation property for module AzureADAuthenticationMethods.
VERBOSE: Populating RepositorySourceLocation property for module AzureADPreview.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.Azure.AD.CommonLibrary.dll'.                                                                                              VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.AzureAD16.Graph.PowerShell.Custom.dll'.                                                                                   VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.AzureAD16.Graph.Client.dll'.                                                                                              VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.AzureADBeta.Graph.PowerShell.dll'.                                                                                        VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.AzureADBeta.Graph.Client.dll'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.MS.GraphBeta.PowerShell.Custom.dll'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.MS.GraphBeta.PowerShell.dll'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.MS.GraphBeta.Client.dll'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.AzureAD16.Graph.PowerShell.dll'.
DEBUG: Retrieving installed Az modules
DEBUG: The Az modules currently installed: Az.Functions Az.MachineLearning Az.Storage Az.DataFactory Az.DevTestLabs Az.Support Az.DeploymentManager Az.FrontDoor Az.Batch Az.StreamAnalytics Az.PolicyInsights Az.Monitor Az.Billing Az.NotificationHubs Az.Aks Az.ContainerInstance Az.DataLakeAnalytics Az.CognitiveServices Az.StorageSync Az.AnalysisServices Az.ApiManagement Az.OperationalInsights Az.Cdn Az Az.EventGrid Az.ServiceBus Az.DataShare Az.ContainerRegistry Az.Automation Az.ResourceGraph Az.Relay Az.PowerBIEmbedded Az.HDInsight Az.LogicApp Az.EventHub Az.DataLakeStore Az.HealthcareApis Az.SignalR Az.RecoveryServices Az.Maintenance Az.Kusto Az.Resources Az.Media Az.DataBoxEdge Az.DesktopVirtualization Az.RedisCache Az.ManagedServices Az.KeyVault Az.Sql Az.Accounts Az.Network Az.Websites Az.ServiceFabric Az.ApplicationInsights Az.PrivateDns Az.Dns Az.IotHub Az.SqlVirtualMachine Az.ConnectedMachine Az.MarketplaceOrdering Az.TrafficManager Az.Compute Az.Advisor
DEBUG: The modules to check for update: Az Az.Accounts Az.Advisor Az.Aks Az.AnalysisServices Az.ApiManagement Az.ApplicationInsights Az.Automation Az.Batch Az.Billing Az.Cdn Az.CognitiveServices Az.Compute Az.ConnectedMachine Az.ContainerInstance Az.ContainerRegistry Az.DataBoxEdge Az.DataFactory Az.DataLakeAnalytics Az.DataLakeStore Az.DataShare Az.DeploymentManager Az.DesktopVirtualization Az.DevTestLabs Az.Dns Az.EventGrid Az.EventHub Az.FrontDoor Az.Functions Az.HDInsight Az.HealthcareApis Az.IotHub Az.KeyVault Az.Kusto Az.LogicApp Az.MachineLearning Az.Maintenance Az.ManagedServices Az.MarketplaceOrdering Az.Media Az.Monitor Az.Network Az.NotificationHubs Az.OperationalInsights Az.PolicyInsights Az.PowerBIEmbedded Az.PrivateDns Az.RecoveryServices Az.RedisCache Az.Relay Az.ResourceGraph Az.Resources Az.ServiceBus Az.ServiceFabric Az.SignalR Az.Sql Az.SqlVirtualMachine Az.Storage Az.StorageSync Az.StreamAnalytics Az.Support Az.TrafficManager Az.Websites
DEBUG: The modules contain update: Az.Sql
DEBUG: Time Elapsed: 309.5566011s
The modules to Update:
VersionToUpgrade Name   Repository InstalledVersion
---------------- ----   ---------- ----------------
2.10.1           Az.Sql PSGallery  2.10.0


What if: Remove Az.Sql of the versions: 2.10.0
What if: Update Az.Sql to the latest version 2.10.1 from PSGallery
DEBUG: Time Elapsed Total: 316.0210736s
DEBUG: Initialize telemetry client
DEBUG: Finish sending metric

**Comment by msJinLei** [comment]
```
VERBOSE: Populating RepositorySourceLocation property for module Az.
VERBOSE: Populating RepositorySourceLocation property for module Az.Accounts.
VERBOSE: Populating RepositorySourceLocation property for module Az.Advisor.
VERBOSE: Populating RepositorySourceLocation property for module Az.Aks.
VERBOSE: Populating RepositorySourceLocation property for module Az.AnalysisServices.
VERBOSE: Populating RepositorySourceLocation property for module Az.ApiManagement.
VERBOSE: Populating RepositorySourceLocation property for module Az.ApplicationInsights.
VERBOSE: Populating RepositorySourceLocation property for module Az.Automation.
VERBOSE: Populating RepositorySourceLocation property for module Az.Batch.
VERBOSE: Populating RepositorySourceLocation property for module Az.Billing.
VERBOSE: Populating RepositorySourceLocation property for module Az.Cdn.
VERBOSE: Populating RepositorySourceLocation property for module Az.CognitiveServices.
VERBOSE: Populating RepositorySourceLocation property for module Az.Compute.
VERBOSE: Populating RepositorySourceLocation property for module Az.ConnectedMachine.
VERBOSE: Loading module from path 'C:\Users\aleksandar\Documents\PowerShell\Modules\Az.ConnectedMachine\0.2.0\Az.ConnectedMachine.psm1'.
VERBOSE: Populating RepositorySourceLocation property for module Az.ContainerInstance.
VERBOSE: Populating RepositorySourceLocation property for module Az.ContainerRegistry.
VERBOSE: Populating RepositorySourceLocation property for module Az.DataBoxEdge.
VERBOSE: Populating RepositorySourceLocation property for module Az.DataFactory.
VERBOSE: Populating RepositorySourceLocation property for module Az.DataLakeAnalytics.
VERBOSE: Populating RepositorySourceLocation property for module Az.DataLakeStore.
VERBOSE: Populating RepositorySourceLocation property for module Az.DataShare.
VERBOSE: Populating RepositorySourceLocation property for module Az.DeploymentManager.
VERBOSE: Populating RepositorySourceLocation property for module Az.DesktopVirtualization.
VERBOSE: Loading module from path 'C:\Users\aleksandar\Documents\PowerShell\Modules\Az.DesktopVirtualization\2.0.0\Az.DesktopVirtualization.psm1'.
VERBOSE: Populating RepositorySourceLocation property for module Az.DevTestLabs.
VERBOSE: Populating RepositorySourceLocation property for module Az.Dns.
VERBOSE: Populating RepositorySourceLocation property for module Az.EventGrid.
VERBOSE: Populating RepositorySourceLocation property for module Az.EventHub.
VERBOSE: Populating RepositorySourceLocation property for module Az.FrontDoor.
VERBOSE: Populating RepositorySourceLocation property for module Az.Functions.
VERBOSE: Populating RepositorySourceLocation property for module Az.HDInsight.
VERBOSE: Populating RepositorySourceLocation property for module Az.HealthcareApis.
VERBOSE: Populating RepositorySourceLocation property for module Az.IotHub.
VERBOSE: Populating RepositorySourceLocation property for module Az.KeyVault.
VERBOSE: Populating RepositorySourceLocation property for module Az.Kusto.
VERBOSE: Loading module from path 'C:\Users\aleksandar\Documents\PowerShell\Modules\Az.Kusto\1.0.0\Az.Kusto.psm1'.
VERBOSE: Populating RepositorySourceLocation property for module Az.LogicApp.
VERBOSE: Populating RepositorySourceLocation property for module Az.MachineLearning.
VERBOSE: Populating RepositorySourceLocation property for module Az.Maintenance.
VERBOSE: Populating RepositorySourceLocation property for module Az.ManagedServices.
VERBOSE: Populating RepositorySourceLocation property for module Az.MarketplaceOrdering.
VERBOSE: Populating RepositorySourceLocation property for module Az.Media.
VERBOSE: Populating RepositorySourceLocation property for module Az.Monitor.
VERBOSE: Populating RepositorySourceLocation property for module Az.Network.
VERBOSE: Populating RepositorySourceLocation property for module Az.NotificationHubs.
VERBOSE: Populating RepositorySourceLocation property for module Az.OperationalInsights.
VERBOSE: Populating RepositorySourceLocation property for module Az.PolicyInsights.
VERBOSE: Populating RepositorySourceLocation property for module Az.PowerBIEmbedded.
VERBOSE: Populating RepositorySourceLocation property for module Az.PrivateDns.
VERBOSE: Populating RepositorySourceLocation property for module Az.RecoveryServices.
VERBOSE: Populating RepositorySourceLocation property for module Az.RedisCache.
VERBOSE: Populating RepositorySourceLocation property for module Az.Relay.
VERBOSE: Populating RepositorySourceLocation property for module Az.ResourceGraph.
VERBOSE: Populating RepositorySourceLocation property for module Az.Resources.
VERBOSE: Populating RepositorySourceLocation property for module Az.ServiceBus.
VERBOSE: Populating RepositorySourceLocation property for module Az.ServiceFabric.
VERBOSE: Populating RepositorySourceLocation property for module Az.SignalR.
VERBOSE: Populating RepositorySourceLocation property for module Az.Sql.
VERBOSE: Populating RepositorySourceLocation property for module Az.SqlVirtualMachine.
VERBOSE: Populating RepositorySourceLocation property for module Az.Storage.
VERBOSE: Populating RepositorySourceLocation property for module Az.StorageSync.
VERBOSE: Populating RepositorySourceLocation property for module Az.StreamAnalytics.
VERBOSE: Populating RepositorySourceLocation property for module Az.Support.
VERBOSE: Populating RepositorySourceLocation property for module Az.Tools.Installer.
VERBOSE: Loading module from path 'C:\Users\aleksandar\Documents\PowerShell\Modules\Az.Tools.Installer\0.1.0\Az.Tools.Installer.psm1'.
VERBOSE: Populating RepositorySourceLocation property for module Az.Tools.Migration.
VERBOSE: Populating RepositorySourceLocation property for module Az.TrafficManager.
VERBOSE: Populating RepositorySourceLocation property for module Az.Websites.
VERBOSE: Populating RepositorySourceLocation property for module AzureADAuthenticationMethods.
VERBOSE: Populating RepositorySourceLocation property for module AzureADPreview.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.Azure.AD.CommonLibrary.dll'.                                                                                              VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.AzureAD16.Graph.PowerShell.Custom.dll'.                                                                                   VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.AzureAD16.Graph.Client.dll'.                                                                                              VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.AzureADBeta.Graph.PowerShell.dll'.                                                                                        VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.AzureADBeta.Graph.Client.dll'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.MS.GraphBeta.PowerShell.Custom.dll'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.MS.GraphBeta.PowerShell.dll'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.MS.GraphBeta.Client.dll'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureADPreview\2.0.2.105\Microsoft.Open.AzureAD16.Graph.PowerShell.dll'.
```
The logs above is printed by 
```
Get-Module -ListAvailable -Name 'Az*' -Verbose
```

We use the cmdlet to detect the az related module install on your local machine.

The cmdlet runs a long time for it fetches the information from PowerShell gallery and the time may vary with reference to your network status.

Can you run the following cmdlet 
```
Measure-Command {Install-Module -Name Az -Repository PSGallery -Force}
```
And paste the output here. The output is something like
```
Days              : 0
Hours             : 0
Minutes           : 2
Seconds           : 15
Milliseconds      : 839
Ticks             : 1358393544
TotalDays         : 0.00157221475
TotalHours        : 0.037733154
TotalMinutes      : 2.26398924
TotalSeconds      : 135.8393544
TotalMilliseconds : 135839.3544
```

Thanks.

**Comment by brwilkinson** [comment]
The backgound jobs from the Whatif also don't seem to be able to be removed ?

![image](https://user-images.githubusercontent.com/3605266/94873931-6e7d8700-0405-11eb-9638-5d9706e808ab.png)

Also not sure if this is expected ?    is that a typo or expected on the words  "This cmdlet will **not** install preview" . .  not sure if it's supposed to be "This cmdlet will **now** install preview"  

![image](https://user-images.githubusercontent.com/3605266/94873996-9ff65280-0405-11eb-847e-e3a68e3aa726.png)

It appears to have applied the -allowprerelease

![image](https://user-images.githubusercontent.com/3605266/94874083-e350c100-0405-11eb-93ee-a035b8c2b9a6.png)

**Comment by msJinLei** [comment]
@alexandair The Update-AzModule is stuck due to the network condition. The issue is greatly alleviated in the [Az.Tools.Installer 0.2.0](https://www.powershellgallery.com/packages/Az.Tools.Installer/0.2.0) we release one month ago. Please try it and let us know if you have further issues.
