### ISSUE TITLE
(Get-AzureSubscription).CurrentStorageAccountName returning multiple connection strings

### ISSUE THREAD

**Issue by fujiy** [Azure/azure-powershell#1305]
In latest version (Get-AzureSubscription).CurrentStorageAccountName returns the connection string for Blob, Queue and Table instead of Account name as before

**Comment by iamshital** [comment]
I confirmed this issue. First I thought, it returned PSObject, but it is plain string.

**Comment by plauborg** [comment]
Any idea what the time frame is for when this bug will be solved and released?

This is causing one of our frameworks to fail and we need to take a decision whether we should rewrite the logic in our code or wait for a new release

**Comment by markcowl** [comment]
@fujiy @iamshital That is correct, this is a breaking change in how the current storage account works, to allow using the account in both ARM and ASM scenarios
