### ISSUE TITLE
Add a Get-AzVmssExtension Cmdlet for listing VMSS extensions

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/azure-powershell#13065]
## Description of the new feature
To get extensions for virtual machines, you can use [Get-AzVMExtension](https://docs.microsoft.com/en-us/powershell/module/az.compute/get-azvmextension?view=azps-4.7.0). However, there doesn't seem to be an equivalent Cmdlet for virtual machine scale sets. I would have assumed a `Get-AzVmssExtension` Cmdlet would have existed as well.

I verified this with `Get-Command`:

```powershell
❯ Get-Command -Name *AzVmssExtension*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Add-AzVmssExtension                                4.4.0      Az.Compute
Cmdlet          Remove-AzVmssExtension                             4.4.0      Az.Compute
```

Which lists Cmdlets to add and remove extensions, but no Cmdlet to get extensions. `4.4.0` seems to also be the latest version for `Az.Compute`, which I am running on the latest version `4.7.0` of Azure PowerShell. 

I've also searched [MSDN](https://docs.microsoft.com/en-us/powershell/module/az.compute/?view=azps-4.7.0#vm-scale-sets) and no `Get-AzVmssExtension` Cmdlet seems to exist there either.

## Proposed implementation details (optional)

Add a `Get-AzVmssExtension` Cmdlet. Azure CLI supports this with [az vmss extension show](https://docs.microsoft.com/en-us/cli/azure/vmss/extension?view=azure-cli-latest#az_vmss_extension_show) and [az vmss extension list](https://docs.microsoft.com/en-us/cli/azure/vmss/extension?view=azure-cli-latest#az_vmss_extension_list), so it would make sense for Azure PowerShell to support this as well. As a workaround we have been deserializing the JSON output from the previous Azure CLI commands with `ConvertFrom-Json`. It would be much better if we didn't have to do this and use a native Azure PowerShell command instead. 

Please correct me if such a Cmdlet under a different naming convention exists in Azure PowerShell.

**Comment by VeryEarly** [comment]
Hi @Drewm3 @amjads1 

Can you help take a look at this issue?

Thanks

**Comment by ArmaanMcleod** [comment]
@VeryEarly @Drewm3 @amjads1 I've just realised `Get-AzVmss` has the extensions listed under the `ExtensionProfile` property. I see why a `Get-AzVmssExtension` Cmdlet wasn't created now. Should we close this ticket? Could we benefit from having a  `Get-AzVmssExtension` Cmdlet?

**Comment by axayjo** [comment]
@amjads1 can you take a look at this issue?

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by amjads1** [comment]
@ArmaanMcleod - You are correct. Extensions are a part of the extensionsProfile part of the VMSS model, so Get-AzVmss contains all of the extension info.

At this point, we recommend to continue with Get-AzVmss that should help you get the extensions for virtual machine scale sets. Hope this helps. I will go ahead and close this ticket now.
