### ISSUE TITLE
Azure Powershell - IoT Hub Layered Deployment

### ISSUE THREAD

**Issue by AndreasDpWD** [Azure/azure-powershell#13063]
## Description
We are using Azure Powershell but looks like it's missing a feathure for IoT Hub. I am trying to make a deployment script for out Layered deploytments for our Edge devices.

But as I read and understrand it this command  Add-AzIotHubDeployment doesn't support the leayered feathure. But if I use the Az-Module / AzureCLI it has a option for layereed (--layered)

Is this something that will be added?

**Comment by VeryEarly** [comment]
Hi @AndreasDpWD ,

thanks for reporting this issue, can you specify the version of Az.Iothub you are using and which cmdlet has  --layered option?

**Comment by AndreasDpWD** [comment]
I am using  version 2.5.1 of Az.IotHub

**Comment by Pistle** [comment]
Create an IoT Edge automatic deployment in the Azure portal to manage ongoing deployments for many devices at once. Automatic deployments for IoT Edge are part of the automatic device management feature of IoT Hub. Deployments are dynamic processes that enable you to deploy multiple modules to multiple devices, track the status and health of the modules, and make changes when necessary.

**Comment by yiyiguo** [comment]
needs-author-feedback
