### ISSUE TITLE
APIM Export to Power Platform

### ISSUE THREAD

**Issue by chrispiasecki** [Azure/azure-powershell#13084]
## Description of the new feature
Currently there exists an Export-AzApiManagementApi cmdlet to export an API to a file. It would be nice to have an option or separate cmdlet to export the API to a Power Platform environment. Currently this can be done via the Portal as described in documentation https://docs.microsoft.com/en-us/azure/api-management/export-api-power-platform

**Comment by VeryEarly** [comment]
Hi @chrispiasecki ,

Thanks for reporting this issue, forwarded to service team.

**Comment by navba-MSFT** [comment]
@chrispiasecki Apologies for the late reply. We are looking in this issue. We will update this thread once we have more details on this.

@adrianhall Could you please provide an update on this ? Awaiting your reply.
