### ISSUE TITLE
Install-AzureRm is slow

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1308]
The `Install-AzureRm` command takes a long time to execute. Can we figure out what part is taking the longest, and try to shorten this up a bit?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by devigned** [comment]
We are working with the PowerShellGet team to improve this experience.

**Comment by kerslake** [comment]
+1

This is incredibly slow for me - it's trundling through installing 28 modules, and each one is take a minute or two.

**Comment by pcgeek86** [comment]
Any updates on this topic, @devigned?

Cheers,
Trevor Sullivan

**Comment by markcowl** [comment]
@pcgeek86 @kerslake It looks like moving to a a module consisting only of dependencies makes this around an order of magniturde better.  As soon as the RTM version of WMF ships (later this month) we plan to make this transition.

**Comment by pcgeek86** [comment]
@markcowl Thanks! Let's keep this open until we can show some performance gains.

**Comment by kilasuit** [comment]
Also just looking at the Download numbers for the AzureRM.Profile module is almost 10x the rest of the modules which to me points to it being downloaded multiple times in the install process and perhaps this is why it is slow to install

To confirm have a look at this page and ensure sort by popularity is set
http://www.powershellgallery.com/PSModule

**Comment by kilasuit** [comment]
Or as this page shows it is 10x times of the other Azure Modules

http://www.powershellgallery.com/stats

**Comment by markcowl** [comment]
@kilasuit Not sure if this is related to multiple installs, or related to installs of individual modules occurring more than installs of AzureRm.  The move to a manifest module this release should have some impact on cleaning this up.

**Comment by pcgeek86** [comment]
Perhaps we would benefit from some parallelism here, since we are installing a bunch of child modules. `Start-Job`, or Boe Prox's PoshRSJob? @proxb

https://github.com/proxb/PoshRSJob

**Comment by markcowl** [comment]
Fixed see https://azure.microsoft.com/en-us/blog/azure-powershell-1-3-0-gallery-improvements/
