### ISSUE TITLE
New-AzSqlDatabaseExport throws error "Missing the required 'networkIsolation' parameters for ImportExport operation." after Az.Sql version 2.10.1 

### ISSUE THREAD

**Issue by sistoimenov** [Azure/azure-powershell#13097]
We run scheduled backups on our system with the command 

```
New-AzSqlDatabaseExport -ResourceGroupName $resourceGroupName -ServerName $server `
        -DatabaseName $database -StorageKeytype $storageKeyType -StorageKey $storageKey -StorageUri $storageUri `
        -AdministratorLogin $user -AdministratorLoginPassword $password
```

Before running the command we install the latest version of Az.Sql.

Since last Thursday it has been failing and I noticed that there is a new release of Az.Sql on that day.

After some additional testing it seems that with **version 2.10.0 and prior ones the command above works fine, with version 2.10.1 and 2.11.0 (the latest one) it fails with the error "Missing the required 'networkIsolation' parameters for ImportExport operation."**

I can't find any documentation about this parameter and it seems something internal. The closest thing that I can see from the documentation is the parameter **-UseNetworkIsolation**. Setting it to false produces the same error. Setting it to true and specifying the additional parameters **-StorageAccountResourceIdForPrivateLink** and **-SqlServerResourceIdForPrivateLink** produces an error that it can't find the database that I am trying to export but in the error message it outputs the resource id of my database and it is a valid one.

Could you look at this as it obviously seems like a bug. 

For now I am setting my script to use version 2.9.1 of the Az.Sql module as it seems a stable one.

**Comment by dingmeng-xue** [comment]
Sql team, please look into this question.

**Comment by benjamin-goldman** [comment]
yup - this is murdering our ability to progress a project.

**Comment by adeal** [comment]
@brandong-ms @sredman
