### ISSUE TITLE
Login-AzureRmAccount or Add-AzureRmAccount not accepting passing PSCredential objects

### ISSUE THREAD

**Issue by MaxTrinidad** [Azure/azure-powershell#1309]
I'm trying to automate the some scripts to dynamically pass the Get-Credential objects to either the "Login-AzureRmAccount" or "Add-AzureRmAccount" without success.  It only work by itself with no parameters.

Login-AzureRmAccount - work with no parameters providing a pop-window.

I use the following script block in many other areas to dynamically build my credentials:

## - Prepare PSCredential objects:
$MyAzureName = "username@System.net";
$MyAzurePassword = ConvertTo-SecureString '$myPassw0rd1' -AsPlainText -Force;
$AzureRMCredential = new-object `
-typename System.Management.Automation.PSCredential `
-argumentlist $MyAzureName, $MyAzurePassword;

Also, I tried using the normal Get-Credential to create the object and that didn't work either.

 $AzureRMCred = Get-Credential -Credential 'maxt@vvvvv.net';

In both tries, I got the following error:

PS C:\WINDOWS\system32> Login-AzureRmAccount -Credential $AzureRMCred
Login-AzureRmAccount : AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password
Trace ID: ff9cc0dd-4df0-43c6-96d1-fe039d6e8377
Correlation ID: cd11d2b9-1898-4fc6-a57b-f42cd4a1923b
Timestamp: 2015-11-17 18:03:27Z: The remote server returned an error: (400) Bad Request.
At line:1 char:1
+ Login-AzureRmAccount -Credential $AzureRMCred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzureRmAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Common.Authentication.AadAuthenticationFailedException,Microsoft.Azure.C
   ommands.Profile.AddAzureRMAccountCommand

I have verified both UserNa,me and Password were entered correct by using the following methods:
1. $AzureRMCred.GetNetworkCredential().UserName
2. $AzureRMCred.GetNetworkCredential().Password

Something is definitely off.

**Comment by devigned** [comment]
@markcowl any ideas on this one?

**Comment by ToanNN** [comment]
@MaxTrinidad  The issue was with credential initialization. You can try this one

$azureAccountName ="<your account name>"
$azurePassword = ConvertTo-SecureString "<your password>" -AsPlainText -Force

$psCred = New-Object System.Management.Automation.PSCredential($azureAccountName, $azurePassword)

Login-AzureRmAccount -Credential $psCred

**Comment by MaxTrinidad** [comment]
Sorry Toan!  Yes it's a credential initialization.  I've been using this code structure for so many years for both Windows and SQL dynamic authentication. Also, using it in both On-Premise and Azure Cloud VM. But, it doesn't work for Azure RM credentials.

The code you provided is the same as the one I've been using for a long time but without the '-parameters'.  I did try it anyway. 

Still got the same failure:

PS C:\Users\mtrinidad> $azureAccountName = 'user@domain.net'
PS C:\Users\mtrinidad> $azurePassword = ConvertTo-SecureString 'aa$xcvb999!' -AsPlainText -Force
PS C:\Users\mtrinidad> Login-AzureRmAccount -Credential $psCred
Login-AzureRmAccount : AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password
Trace ID: 1854918e-b803-4f2a-bde1-e19599f47e08
Correlation ID: bcd5a620-2a25-4a18-b5a0-7cf0bb91f541
Timestamp: 2015-11-24 15:11:03Z: The remote server returned an error: (400) Bad Request.
At line:1 char:1
+ Login-AzureRmAccount -Credential $psCred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzureRmAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Common.Authentication.AadAuthenticationFailedException,Microsoft.Azure.C
   ommands.Profile.AddAzureRMAccountCommand
PS C:\Users\mtrinidad>

Thanks, 
Max

**Comment by ToanNN** [comment]
Hi Max,

It is weird because I was using the code as I posted. Just a quick question, did you include `( )` when you created the credential ? When I left `()`, I got the same error like you had. 

New-Object System.Management.Automation.PSCredential**(**$azureAccountName, $azurePassword**)**

**Comment by MaxTrinidad** [comment]
So, you got it running with this code? Yes.  Which version of AzureRM are you running?

I still got the same failure. Using the () is the same as using the parameter "- argumentlist".  I got the latest 

PS C:\Users\mtrinidad> ## - Prepare PSCredential objects:
PS C:\Users\mtrinidad> $MyAzureName = "maxt@putittogether.net";
PS C:\Users\mtrinidad> $MyAzurePassword = ConvertTo-SecureString 'pr$W1ld0299!' -AsPlainText -Force;
PS C:\Users\mtrinidad>
PS C:\Users\mtrinidad> $AzureRMCredential = New-Object System.Management.Automation.PSCredential($MyAzureName, $MyAzureP
assword)
PS C:\Users\mtrinidad>
PS C:\Users\mtrinidad> Login-AzureRmAccount -Credential $AzureRMCredential
Login-AzureRmAccount : AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password
Trace ID: 4ac9e20f-37fa-446c-9bb5-81fdf86fb872
Correlation ID: 24b0f017-9f42-4308-9493-699f372a2a09
Timestamp: 2015-11-25 00:24:43Z: The remote server returned an error: (400) Bad Request.
At line:1 char:1
+ Login-AzureRmAccount -Credential $AzureRMCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzureRmAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Common.Authentication.AadAuthenticationFailedException,Microsoft.Azure.C
   ommands.Profile.AddAzureRMAccountCommand

Anyway, I decided to uninstall all AzureRM modules and installed them again from the PowerShell Gallery.

Let me get the version # this time.

Thanks,
Max

**Comment by ToanNN** [comment]
Hi Max,

I use Microsoft Azure Powershell - November 2015 which is the latest version.

**Comment by MaxTrinidad** [comment]
I'm getting the AzureRM from the PowerShell Gallery following the instructions from the October blog: https://azure.microsoft.com/en-us/blog/azps-1-0-pre/ 

The versions installed are: 
1. Azure - Version 1.0.1
2. AzureRM - Version 1.0.3

After uninstalling and reinstalling everything, I'm still getting the error.

Max

**Comment by ToanNN** [comment]
Hi Max,
Below are my installed apps for Azure, 
![image](https://cloud.githubusercontent.com/assets/6165252/11386941/cf2f89e0-9371-11e5-9255-4b49a93670f9.png)

I don't installed it using the link you posted, I used the web platform installer
![image](https://cloud.githubusercontent.com/assets/6165252/11386955/f304440a-9371-11e5-8811-5fc32923ac1c.png)

**Comment by MaxTrinidad** [comment]
I uninstall everything again and did the webinstaller, got November version, and still failing:

Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

PS C:\Users\mtrinidad> ## - Prepare PSCredential objects:
PS C:\Users\mtrinidad> $MyAzureName = "maxt@putittogether.net";
PS C:\Users\mtrinidad> $MyAzurePassword = ConvertTo-SecureString 'pr$W1ld0299!' -AsPlainText -Force;
PS C:\Users\mtrinidad> $AzureRMCredential = new-object `
>>> -typename System.Management.Automation.PSCredential `
>>> -argumentlist $MyAzureName, $MyAzurePassword;
PS C:\Users\mtrinidad>
PS C:\Users\mtrinidad> Login-AzureRmAccount -Credential $AzureRMCredential
Login-AzureRmAccount : AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password
Trace ID: b2e43ba6-d4bc-4acb-9c50-3289fabe5cec
Correlation ID: 3ecfc24d-77cc-4945-bc25-9db83f20ffda
Timestamp: 2015-11-25 11:15:16Z: The remote server returned an error: (400) Bad Request.
At line:1 char:1
+ Login-AzureRmAccount -Credential $AzureRMCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzureRmAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Common.Authentication.AadAuthenticationFailedException,Microsoft.Azure.C
   ommands.Profile.AddAzureRMAccountCommand

:(

**Comment by MaxTrinidad** [comment]
I need to know:
1. Which version of Windows OS? I'm Windows 7 SP1 (64bit) and Windows 10 July edition.
2. PowerShell Version? I'm on WMF 5.0 Production Preview for Windows 7 SP1

Executing either Azure/AzureRM either installed:  Web or PowerShell Gallery. I'm getting the same errors.

Keep in mind, my code only fails with AzureRM Credentials.  I can use my code with anything else Azure, Azure VM, Azure SQL, Windows and SQL Authentication.

I have followed all uninstalled steps and even manually delete the Azure module folders.

Don't know what else I can do to pass this failure. 

What else am I missing?

Any other ideas are welcome!

Max

**Comment by ToanNN** [comment]
Hi Max,

I use windows 8.1 and Powershell version 1 as you can see in the screenshot. 
![image](https://cloud.githubusercontent.com/assets/6165252/11411842/9169dd5e-9420-11e5-9932-73479fc4cecf.png)

I had the same issue previously by not including `()` when creating the credentials, and now it seems working for me. 
![image](https://cloud.githubusercontent.com/assets/6165252/11411875/2f67a180-9421-11e5-916e-da9aa13da8ca.png)

I receive the a **Bad Request** error, if my username or password is incorrect. Can you just copy and paste the credential to see if you can log in?

**Comment by MaxTrinidad** [comment]
Here's my screen shot.
![azurermcred_issue_2015-11-25_21-04-07](https://cloud.githubusercontent.com/assets/7338470/11413592/9fad4562-93b8-11e5-8ba2-87aea3818cd9.jpg)

**Comment by ToanNN** [comment]
Max,

Sorry I can't help you anymore. I have the same modules like you have. The only difference is I run Powershell version 1 & Windows 8.1


![image](https://cloud.githubusercontent.com/assets/6165252/11413955/0d4d9888-943b-11e5-83a8-d8f3c564d92e.png)

**Comment by MaxTrinidad** [comment]
Wait!  There's a difference:
1. Run $PSversionTable to verify which version of PowerShell you are running,  It can't be version 1.
2. I got WMF 5.0 Production Preview on my Windows 7 SP1 and On Windows 10 is V5.0.

I have another MVP friend of mine testing this and got the same failure.

Anyone got any ideas?

Thanks,
Max

**Comment by ToanNN** [comment]
Hi Max,
Below is the screenshot
![image](https://cloud.githubusercontent.com/assets/6165252/11432381/f28901a4-94f8-11e5-878c-0088db4ae558.png)

**Comment by MaxTrinidad** [comment]
Ah!  Bingo!!  

You 're not using the latest PowerShell Version 5.0.   Have you try it on a Windows 10 with PowerShell version 5.0?

:)

Max

**Comment by aftonstrale** [comment]
Hi,

Did you solve this issue?

You may probably already now that Login-AzureRmAccount is just an alias to Add-AzureRmAccount so it does not make sense to run tests with both commands.

In my environment I am running windows 8.1 and PS version 4.0 and for me it works fine.

But I am not sure that it is related to my environment (however I cannot confirm), but I have another suggestion for you to test. I can see that you try to sign in with your credentials as only input to the command. But what if your account is associated with multiple subscriptions?

I have a quite complex set-up so I need to provide both subscription id as well as tenant id (besides credtentials) in order to get it to work. Maybe this is the case for you as well?

Sorry, I have no way to confirm this, but I suggest you test this, since it is just a five minute prep for this.

Cheers!

**Comment by ShaneCastle** [comment]
I had the same error. My fix was to use an Azure AD account instead of my MSDN account.

From here:
"Also make sure the credential asset username is a valid OrgID user (ex: abc@fdgdf.onmicrosoft.com), not a Microsoft / Live account (joe@gmail.com)."

http://serverfault.com/questions/746557/add-azureaccount-unknown-user-type-unknown-user-type-on-azure-automation/746673

**Comment by markcowl** [comment]
@ShaneCastle @MaxTrinidad Yes, the issue is that the 'non-interactive' flow, that is log in without going through the login dialog is not allowed for live id credentials in Azure Active Directory.  If you need to automate using PSCredential, the advice is to use service principal authentication.

**Comment by Students** [comment]
Hi All,

Had just the same issue.

In my case - account was valid OrgID User.

Stupid mistake, but I saw in original request it as well.

Password contains $ sign
In powershell you need to escape it using ` sign :)

Not $MyAzurePassword = ConvertTo-SecureString '$myPassw0rd1' -AsPlainText -Force;
But $MyAzurePassword = ConvertTo-SecureString '`$myPassw0rd1' -AsPlainText -Force;

ToanNN's code works just fine for me (powershell 3 Windows 7 \ Windows Server 2012 R2)

Thanks. :)

**Comment by rayone** [comment]
If you've got >1 subscription, or you've changed your email, or your using a personal account there doesn't seem to be any way to pass credentials.
I've tried everything and at best I get: Login-AzureRmAccount : AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password.

I'm guessing the methods querying AAD have some logic flaws with Tenant/User IDs.

I've been trying intermittently since ARM 1st became available until today (Azure PS 2016-8-10).

**Comment by markcowl** [comment]
@rayone Unfortunately, if you are using a 'live id' or what is now referred to as a 'Microsoft Account', as opposed to an OrgId, or a 'work or school account', then login will not work with PS Credential - for security reasons, you are required to enter your password through the dialog.  This is an unfortunate limitation of microsoft account authentication.  You can get around this in a few ways:

- You can create a service principal and log in as the service principal (using either a PSCredential with SPN/Secret or a certificate
- You can create an AD domain and create ids within your domain - note that, while these accounts *can* accept non-interactive login, this requires that multi-factor authentication is *not* required.

**Comment by masthi** [comment]
I am not getting the logon dialog box after running Add-AzureRMAccount in my new Windows 10 laptop. Its displaying a blank dialog box with no text boxes for  taking user & password inputs. I have re installed Azure Module and tried while I am in behind Office proxy and from public network. Its still the same issue.
Any help would be greatly appreciated.

![azurepowershellloginissue](https://user-images.githubusercontent.com/31551078/33177300-1f0aee82-d088-11e7-8008-882e5c794ae0.PNG)

**Comment by GhfDllT** [comment]
@masthi , did you solve the problem? I'am having the same.

**Comment by masthi** [comment]
Nope I am still having the same issue

**Comment by GhfDllT** [comment]
@masthi , reset worked  for me
