### ISSUE TITLE
Azure 1.0.1 Install Issue

### ISSUE THREAD

**Issue by jeffpatton1971** [Azure/azure-powershell#1310]
When I downloaded the latest version, it prompted me about closing PowerShell and PowerShell ISE. I let the installer do it (turns out bad idea) I lost several unsaved scripts that typically when I reboot, or force close ISE they come back...this time they did not :(

**Comment by devigned** [comment]
I'm sorry you lost some unsaved work. I don't know if there is much we can do about that behavior. Please save and close rather than letting the installer, though I'm guessing it's a little late for this advice.
