### ISSUE TITLE
WebApp:Assigning user assigned managed identity to app service slot

### ISSUE THREAD

**Issue by PaulVrugt** [Azure/azure-powershell#13109]
## Description of the new feature
For some reason, the identity of a web app deployment slot is not the same as the identity of the original app service. Given this, azure powershell has no method of assigning a user defined managed identity for a deployment slot. So if I have an app service that uses user defined managed identity, and use `new-azwebappslot` to create a new slot, I have no way of assigning the user defined managed identity to it using azure powershell. Currently I have to resort to an ARM template to assign the identity later.

There are several improvements possible:

- an option in `new-azwebappslot` to also copy the identity settings
- an option in `Set-AzWebAppSlot` to set the user defined managed identity, so I can set it after creating the slot
- an option in `Set-AzWebApp` to set the user defined managed identity, which also seems missing

To be able to not having to resort to an ARM template, I need either option 1 or 2. But I prefer all of them to be implemented

## Proposed implementation details (optional)
In `new-azwebappslot` it can be a switch: `-copyidentity`
The other methods are a bit more complicated since you can add multiple user defined managed identities to an app service

**Comment by dingmeng-xue** [comment]
Service team, please help to look into this feature request.

**Comment by Kotasudhakarreddy** [comment]
@PaulVrugt we recently added support for user-assigned identity using CLI commands - Powershell commands are blocked on new .NET SDK update the ETA for which is October, after that we will add support to user-assigned as well.

here is link to our CLI commands https://docs.microsoft.com/en-us/cli/azure/webapp/identity?view=azure-cli-latest#az_webapp_identity_assign

**Comment by PaulVrugt** [comment]
Thanks for the info. I'll eagerly await the update :)

**Comment by PaulVrugt** [comment]
@Kotasudhakarreddy any news on the Powershell commands?

**Comment by PaulVrugt** [comment]
@Kotasudhakarreddy just checking in again to see if there is any progress

**Comment by Kotasudhakarreddy** [comment]
@PaulVrugt - we are planning to prioritize this for the next release (S179)

**Comment by ransagy** [comment]
Seeing as there is no available Azure powershell way to assign a user-assigned managed identity; Is there a new timeline to achieve this?

**Comment by BastiaanMolsbeck** [comment]
@Kotasudhakarreddy any news on the PowerShell commands?

**Comment by TimArrow** [comment]
any news?
