### ISSUE TITLE
AzureAD module Get-AzureADServiceAppRoleAssignment swapped with Get-AzureADServiceAppRoleAssignedTo

### ISSUE THREAD

**Issue by basburg** [Azure/azure-powershell#13136]
## Description

When running `Get-AzureADServiceAppRoleAssignment` in `AzureAD` version `2.0.2.116` it behaves exactly like running `Get-AzureADServiceAppRoleAssignedTo` on `AzureAD` version `2.0.2.106`, while `Get-AzureADServiceAppRoleAssignedTo` on `v2.0.2.116` behaved exactly like `Get-AzureADServiceAppRoleAssignment` on `v2.0.2.106`.

I assume that in the latest update the command got swapped somehow.

## Steps to reproduce

As in the description, run 
```powershell
Get-AzureADServiceAppRoleAssignment -ObjectId <object-id>
Get-AzureADServiceAppRoleAssignedTo -ObjectId <object-id>
```

in `v2.0.2.106` and in `v2.0.2.116` and observe the difference.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.546
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.546
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Tagging @danigian

**Comment by markcowl** [comment]
@basburg Unfortunately, this is not the repio for the AzureADF module, so we cannot respond to this question.  Please try posting this question to https://support.microsoft.com or through https://github.com/PowerShell/powershell
