### ISSUE TITLE
[Az.Tools.Installer] Update-AzModule Appends AZ on the front of the module name

### ISSUE THREAD

**Issue by brwilkinson** [Azure/azure-powershell#13130]
```
Install-AzModule -Name AZ.Resources -Repository PSGallery -AllowPrerelease -Force -Confirm:$False
```

Appears to use AZ.AZ.Resources

![image](https://user-images.githubusercontent.com/3605266/94876456-8f95a600-040c-11eb-8c2f-eeb7e587a4d2.png)

```
Install-AzModule -Name Resources -Repository PSGallery -AllowPrerelease -Force -Confirm:$False
```

Appears to get further along.

**Comment by Pistle** [comment]
Azure PowerShell is a faster iterative product. We expect our customers to update their locally installed versions constantly to stay up to date. The most common way to update it is to use PowerShellGet, a tool built-in to PowerShell for module management.
Usually, you run “Install-Module -Name Az” to install the latest versions of Azure PowerShell modules. When you run “Install-Module -Name $moduleName” to install a specific Az module, you’ll find both the target module and Az.Accounts are installed.

**Comment by brwilkinson** [comment]
@Pistle was that comment for me ?

if i want to install the AZ.Storage module I would expect to use:

```
install-azmodule -name AZ.Storage
```
That would attempt to install AZ.AZ.storage and it would fail.  <-- this is the issue that I had opened this issue ?

**Comment by markcowl** [comment]
@brwilkinson Yes, the tool should definitely should be resilient over entries it isn't expecting.  Thanks for the feedback, we'll take a look.

@Pistle This is new (preview) functionality that allows users to learn about and manage updates of Az modules

**Comment by brwilkinson** [comment]
I guess I am a little unsure based on the comments if the issue that I saw is clear?!

@markcowl perhaps a question for you.

If I execute the following what would be the expectation:

```
install-azmodule -name Storage
```
vs
```
install-azmodule -name Az.Storage
```
Which syntax should I be using ? I was assuming that prepending the **AZ** on AZ.Az.Storage was a bug ?

**Comment by brwilkinson** [comment]
Also another unrelated side question @markcowl ...

Is there a plan to switch out this Module to use the Preview PowerShellGet Module ?

Since it has the Find-PSResource Cmdlet, instead of Find-Module
or Install-PSResource instead of Install-PSResource.

I was playing around with This Module and the PowerShellGet Preview, however was hitting many bugs/errors after testing them for a few hours. I gave up on opening new issues, I figured I would check back for 0.2 release Etc.

**Comment by dcaro** [comment]
@brwilkinson we are working closely with the PowerShellGet team. This module is build on top of PSGet and so will be in the future but we offer additional capabilities. For example, we detect the presence of AzureRM modules and offer to remove them, or offer to install the modules in preview which are not part of Az.

**Comment by dcaro** [comment]
@msJinLei @VeryEarly PTAL.

**Comment by VeryEarly** [comment]
Hi @brwilkinson ,

The current design is to use the module name without "Az.".

**Comment by brwilkinson** [comment]
@VeryEarly 

okay that is Odd.

I thought this supported a range of other modules as well, Graph, Msonline, AzureAD... ?

So I wasn't expecting to just type the Resource and not the full name.

**Comment by VeryEarly** [comment]
> @VeryEarly
> 
> okay that is Odd.
> 
> I thought this supported a range of other modules as well, Graph, Msonline, AzureAD... ?
> 
> So I wasn't expecting to just type the Resource and not the full name.

This installer will support Az modules only as far as we planed. The input names for modules are still in discussion (Az.Resources or Resources) will be finalized in later versions.

Thanks

**Comment by brwilkinson** [comment]
@VeryEarly  Thanks for the clarification.

I don't have a preference for either option. . . It just felt like pre-pending would limit the scope of how the module could be used, so i figured it was a bug, however I had found several other issues, so I wasn't really sure.

Feel free to close this issue.
