### ISSUE TITLE
New-AzAppServicePlan Documentation missing WorkerSize

### ISSUE THREAD

**Issue by sam-cogan** [Azure/azure-powershell#13144]
## Description
The [documentation](https://github.com/Azure/azure-powershell/blob/master/src/Websites/Websites/help/New-AzAppServicePlan.md) for New-AzAppServicePlan is missing the property for "WorkerSize" and so provides no details on how to select the size of the App Service Plan beyond the default for the tier selected.

In addition, why are the values for this "small, medium, large", this does not line up with the actual values of "p1,p2,p3" and so is confusing for the user.

**Comment by markcowl** [comment]
@sam-cogan The WorkerSize parameter is provided in the linked documentation.

Adding the AppService team to answer the secodn aprt, I woudl guess that the provided T-shirt sizes weerre considered more human readable.
