### ISSUE TITLE
[Az.Functions] Add support to create Node.js 14 function apps

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-powershell#13149]
## Description of the new feature
Add support to create function apps for Node.js 14

## Proposed implementation details (optional)
Stacks: https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/pull/20

cc @anthonychu
@Francisco-Gamino - please triage.

**Comment by Francisco-Gamino** [comment]
Need to update stacks API (in the latest version Node 14 is no longer `hidden`. Fore more info, please see https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/pull/23.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed in the latest Az.Functions release.
