### ISSUE TITLE
Getting front door frontend endpoint custom domain https status and settings

### ISSUE THREAD

**Issue by PaulVrugt** [Azure/azure-powershell#13157]
## Description of the new feature
As far as I know, the azure powershell methods currently don't support getting the status of custom domain https status and their settings. We currrently register frontend endpoints using the `New-AzFrontDoorFrontendEndpointObject` method, save them and use `Enable-AzFrontDoorCustomDomainHttps` to enable custom domain https. However, if we remove a frontend endpoint, and re-add it later, it has apparently remembered the enabled Custom domain https settings. When we then call the `Enable-AzFrontDoorCustomDomainHttps` we get an error stating: 

```
##[error]Error response received. Error Message: '{
  "error": {
    "code": "BadRequest",
    "message": "That action isn’t allowed in this profile."
  }
}
```
I assume this is because the custom domain https is already enabled. However, there is not method to get the custom https domain settings, and the frontend endpoint object only has properties about the https provisioning state, not about whether or not it is enabled. So I have no method of checking whether or not I actually need to perform the `Enable-AzFrontDoorCustomDomainHttps` call.

## Proposed implementation details (optional)
I would expect the custom domain https settings to either be available in the frontend endpoint object, or via a separate call like `Get-AzFrontDoorCustomDomainHttps`

**Comment by eosho** [comment]
+1 on this ask. I am currently trying to figure out a way to check the status of my custom domain w/ key vault certificate

**Comment by JackPoint** [comment]
As a work-a-round you can retrieve the `CustomHttpsProvisioningState` from the Frontend Endpoint.

`Get-AzFrontDoorFrontendEndpoint -ResourceGroupName [rg] -FrontDoorName [fd] -Name [name] | Select-Object CustomHttpsProvisioningState`

When the state is `Disabled`, you can fire the `Enable-AzFrontDoorCustomDomainHttps` call.

You can see all the `CustomHttpsProvisioningState` values at https://github.com/Azure/azure-powershell/blob/master/src/Cdn/Cdn/Models/CustomDomain/PSCustomHttpsProvisioningState.cs if you need a better control of the states.

**Comment by t-bzhan** [comment]
[Get-AzFrontDoorFrontendEndpoint](https://docs.microsoft.com/en-us/powershell/module/az.frontdoor/get-azfrontdoorfrontendendpoint?view=azps-7.2.0) is the suggested way to get the https status and settings for a front door frontend endpoint.

```
PS C:\WINDOWS\system32> Get-AzFrontDoorFrontendEndpoint -ResourceGroupName bzhanafdtest -FrontDoorName 12345-bzhan-test -Name pstest2


HostName                         : pstest2.localdev.cdn.azure.cn
SessionAffinityEnabledState      : Disabled
SessionAffinityTtlSeconds        : 0
WebApplicationFirewallPolicyLink :
Backends                         :
CustomHttpsProvisioningState     : Enabled
CustomHttpsProvisioningSubstate  : CertificateDeployed
CertificateSource                : AzureKeyVault
ProtocolType                     : ServerNameIndication
MinimumTlsVersion                : 1.2
Vault                            : /subscriptions/d7cfdb98-c118-458d-8bdf-246be66b1f5e/resourceGroups/bzhanafdtest/providers/Microsoft.KeyVault/vaults/bzhanbyostest
SecretName                       : wildcard-localdev
SecretVersion                    : 9024765bbe5044c1b35df84c53429f09
CertificateType                  :
ResourceState                    : Enabled
Id                               : /subscriptions/d7cfdb98-c118-458d-8bdf-246be66b1f5e/resourcegroups/bzhanafdtest/providers/Microsoft.Network/frontdoors/12345-bzhan-test/frontendendpoints/pstest2
Name                             : pstest2
Type                             : Microsoft.Network/frontdoors/frontendendpoints
```
