### ISSUE TITLE
Import-Module: Could not load type 'System.Management.Automation.PSSnapIn' from assembly 'System.Management.Automation, Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

### ISSUE THREAD

**Issue by ravichandraatma** [Azure/azure-powershell#13162]
* Issue With PowerShell 7.0 and 7.1
* Install-Module  Microsoft.Xrm.Data.Powershell -Force > succeeded Version latest
* On the execution of command  Import-Module Microsoft.Xrm.Data.Powershell > error is thrown as
Import-Module: Could not load type 'System.Management.Automation.PSSnapIn' from assembly 'System.Management.Automation, Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

Impact:
module Microsoft.Xrm.Data.Powershell can not be used with PS 7

**Comment by markcowl** [comment]
@ravichandraatma The PowerShell repo is here: https://github.com/PowerShell/PowerShell.  Unfortunately, I cannot transfer this issue, so please open this issue there.
