### ISSUE TITLE
Add support for runAsSystem parameter in New-AzImageBuilderCustomizerObject

### ISSUE THREAD

**Issue by danielsollondon** [Azure/azure-powershell#13163]
## Description
Please can you add support for runAsSystem in the PowerShell customizer, this was added as an optional param to the API.

## Steps to reproduce

```powershell
$ImgCustomParams = @{
  PowerShellCustomizer = $true
  CustomizerName = 'settingUpMgmtAgtPath'
  RunElevated = $false
  runAsSystem = $true
  Inline = @("mkdir c:\\buildActions", "echo Azure-Image-Builder-Was-Here  > c:\\buildActions\\buildActionsOutput.txt")
}
$Customizer = New-AzImageBuilderCustomizerObject @ImgCustomParams
```

## Module versions

```powershell
0.1.0                 Az.ImageBuilder   
```

Thanks,

**Comment by danielsollondon** [comment]
hi @dcaro , @dingmeng-xue - has this been released yet? thx

**Comment by dcaro** [comment]
Hi @danielsollondon we are considering this feature for Q1 2021.

**Comment by danielsollondon** [comment]
@dcaro - that is correct

**Comment by danielsollondon** [comment]
@dcaro - Any update on release timeframe? thanks

**Comment by wyunchi-ms** [comment]
Will this parameter conflict with `runElevated`? @danielsollondon

**Comment by danielsollondon** [comment]
@wyunchi-ms - no, both settings are mutually exclusive, and can be used together.
