### ISSUE TITLE
New-AzMySqlServer is missing parameter for minimal-tls-version 

### ISSUE THREAD

**Issue by theheatDK** [Azure/azure-powershell#13170]
Hi,

As far as I can see New-AzMySqlServer is missing parameter for minimal-tls-version.

az CLI have implemented it:
https://docs.microsoft.com/en-us/cli/azure/mysql/server?view=azure-cli-latest#az_mysql_server_create

Regards Peter

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
This attribute is defined on swagger and generated in internal cmdlet. https://github.com/Azure/azure-powershell/blob/2b70e0d54b229d923624b402cdc086826122ca9f/src/MySql/internal/New-AzMySqlServer.ps1#L158. It should be exposed on export cmdlet.

**Comment by LucasYao93** [comment]
Fixed in #13796
