### ISSUE TITLE
New-AzPostgreSqlServer is missing a parameter for minimal-tls-version

### ISSUE THREAD

**Issue by theheatDK** [Azure/azure-powershell#13183]
Hi,

As far as I can see New-AzPostgreSqlServer is missing a parameter for minimal-tls-version.

It is exposed via the Portal and az CLI have implemented it:
https://docs.microsoft.com/en-us/cli/azure/postgres/server?view=azure-cli-latest#az_postgres_server_create

Regards Peter

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by plynch66** [comment]
Hi,

I'd also like to add that New-AzPostgreSqlServer is missing the option to disable public network access which is present in both the Portal and the CLI.

"--public --public-network-access
Enable or disable public network access to server."

Regards,

Paul Lynch

**Comment by LucasYao93** [comment]
Fixed in #13890
