### ISSUE TITLE
Add-AzVirtualNetworkSubnetConfig module asks for string, but doesn't accept a string?

### ISSUE THREAD

**Issue by TiaanVenter** [Azure/azure-powershell#13206]
Related to issue 7431:

Perhaps this is a bug in the Azure Cloud Shell, when attempting to set the VirtualNetwork parameter via Cloud Shell:
PS /home/tiaan> $subnetConf1 = Add-AzVirtualNetworkSubnetConfig -Name web2 -AddressPrefix 10.3.1.0/24 -VirtualNetwork 'VNet2'
Add-AzVirtualNetworkSubnetConfig: Cannot bind parameter 'VirtualNetwork'. Cannot convert the "VNet2" value of type "System.String" to type "Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork".

Should I be posting this as a new issue? When passing the command without the '-VitualNetwork' parameter, I get prompted to enter a string for the param and get the same error:

PS /home/tiaan> $subnetConf1 = Add-AzVirtualNetworkSubnetConfig -Name web2 -AddressPrefix 10.3.1.0/24

cmdlet Add-AzVirtualNetworkSubnetConfig at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
VirtualNetwork:
Add-AzVirtualNetworkSubnetConfig: Cannot bind parameter 'VirtualNetwork'. Cannot convert the "asd" value of type "System.String" to type "Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork".

Could it be a problem with applying the line to the $subneConf1 variable?

Any assistance would be greatly appreciated! :)

**Comment by dingmeng-xue** [comment]
Network team, please help to look into this question.

**Comment by VeryEarly** [comment]
the input value of 'VirtualNetwork' should be PSVirtualNetwork object instead of string.

Please try the example one:
https://docs.microsoft.com/en-us/powershell/module/az.network/add-azvirtualnetworksubnetconfig?view=azps-4.8.0

**Comment by TiaanVenter** [comment]
> the input value of 'VirtualNetwork' should be PSVirtualNetwork object instead of string.
> 
> Please try the example one:
> https://docs.microsoft.com/en-us/powershell/module/az.network/add-azvirtualnetworksubnetconfig?view=azps-4.8.0

Hmm, looks like we need a module to be placed in the object for it to be accepted? Not working when just defining the string as an object:

PS /home/tiaan> $virnetObj = 'VNet2'
PS /home/tiaan> $subnetConfig1 = Add-AzVirtualNetworkSubnetConfig -Name web2 -AddressPrefix 10.3.1.0/24 -VirtualNetwork $virnetObj
Add-AzVirtualNetworkSubnetConfig: Cannot bind parameter 'VirtualNetwork'. Cannot convert the "VNet2" value of type "System.String" to type "Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork".

Yabo, I see what you mean by the input value needing to be PSVirtualNetwork object and not a string, but then how do you set the PSVirtualNetwork object to be equal to the name of the VNet that you want to add it to?

**Comment by TiaanVenter** [comment]
This article on RebelAdmin confirms what Yabo suggested first, passing an object as the value for the parameter and not a string:  https://www.rebeladmin.com/category/microsoft/azure-active-directory/

4. Under the virtual network, I am going to create two subnets. One for servers and one for VPN gateway. To create subnets,

$vn = Get-AzVirtualNetwork -ResourceGroupName REBELVPNRG -Name REBEL-VNET
Add-AzVirtualNetworkSubnetConfig -Name “REBEL-SVR-SUB” -VirtualNetwork $vn -AddressPrefix 192.168.100.0/24
Add-AzVirtualNetworkSubnetConfig -Name “GatewaySubnet” -VirtualNetwork $vn -AddressPrefix 192.168.5.0/24
Set-AzVirtualNetwork -VirtualNetwork $vn

So yeah, I'll keep on playing with Azure and will manage with this, I think I'll close this for now if no one else has any further comments or suggestions. Thanks for your input everyone :)
