### ISSUE TITLE
$blob.ICloudBlob.Properties.LeaseState shows all blobs lease state Unspecified.

### ISSUE THREAD

**Issue by vick-git** [Azure/azure-powershell#13229]
## Description

$blob.ICloudBlob.Properties.LeaseState shows all blobs lease state Unspecified. Although Portal says Available, Broken and so on.
![image](https://user-images.githubusercontent.com/57968021/96109008-12017980-0e93-11eb-809d-0ada7a3c2cbf.png)

Out of the above, 1 is available, 2 are soft deleted.

## Steps to reproduce

```powershell
$storageAccountName = "xxxx" 
$StorageAccountKey = "xxxx 
$storageContainer = "xxxx"
#get context  
$ctx = New-AzureStorageContext -StorageAccountName $storageAccountName -StorageAccountKey $StorageAccountKey  
  
$MaxReturn = 100    
$Token = $Null    
  
do   
{   
      # get a list of all of the blobs in the container  
	$Blobs = Get-AzStorageBlob -Container $storageContainer -Context $ctx -IncludeDeleted -IncludeVersion -MaxCount $MaxReturn  -ContinuationToken $Token
	foreach($blob in $Blobs){
		$blob.Name
		$blob.ICloudBlob.Properties.LeaseState 
	}   
  
}while ($Token -ne $Null) 

```

## Environment data

```

```

## Module versions

```powershell
I am using Azure Powershell (Portal shell)
```

## Debug output

```

```

## Error output

```
Status: Unspecified instead of Status: Broken or Available or such.
```

**Comment by blueww** [comment]
@vick-git 

Powershell depends on .net SDK.
$blob.ICloudBlob is from v11 .net SDK, and v11 .net SDK not support blob version.
So if you try to get any properties of Blob version, don't use $blob.ICloudBlob, Please use V12 .net SDK object (it works for all kinds of blobs):
```powershell
PS C:\> $blob.BlobProperties.LeaseState
Available
```

As remove the V11 object will be a big breaking, we will not remove it now, but might remove it in the future.

**Comment by vick-git** [comment]
That worked, thanks a lot! Closing this.
