### ISSUE TITLE
webapp:Set-AzWebAppSlot doesn't update ScmSiteAlsoStopped

### ISSUE THREAD

**Issue by ihor-z-i** [Azure/azure-powershell#13227]
I'm trying to update ScmSiteAlsoStopped property of a web app slot using the script below and it doesn't have any effect. 

```
$app = Get-AzWebAppSlot -ResourceGroupName rg-name -Name app-name -Slot staging
$app.properties.ScmSiteAlsoStopped = $true
$app | Set-AzWebAppSlot
```

I updated `$DebugPreference="Continue"` and captured a transcript so I see that there is a PUT request described below which sends `"scmSiteAlsoStopped": true` but in the response it is still `"scmSiteAlsoStopped": false`

```
HTTP Method: PUT

Absolute Uri:
https://management.azure.com/subscriptions/[%sid%]/resourceGroups/[%resGr%]/providers/Microsoft.Web/sites/[%appName%]/slots/staging?api-version=2018-11-01

Request Body:
{
  "properties": {
     ...
     "scmSiteAlsoStopped": true,
    ...
  }
}

Response Body
{
  "properties": {
     ...
     "scmSiteAlsoStopped": false,
    ...
  }
}

```

I also tried to update it with az cli using 
`az webapp update --name app-name --resource-group rg-name --slot staging --set scmSiteAlsoStopped=true` and it doesn't work either. 

PowerShell version: 7.0.3
Az version 4.8.0

The issue seems to be similar to this https://github.com/Azure/azure-powershell/issues/9168

**Comment by dingmeng-xue** [comment]
Service team, please help to look into it.

**Comment by Kotasudhakarreddy** [comment]
After trying to update scmSiteAlsoStopped directly by rest api instead of sdk, I get the same result and the scmSiteAlsoStopped flag cannot be set. we need help from service team to check why it cannot be set. Thanks!

**Comment by Kotasudhakarreddy** [comment]
@ihor-z-i As there is a service issue, instead of sdk issue, cloud you please create a support ticket in https://docs.microsoft.com/en-us/answers/topics/azure-webapps.html ?
I think we cannot do anything in sdk side, so I will close this issue,
Thanks
