### ISSUE TITLE
Invoke-AzDataFactoryV2Pipeline actually runs the pipeline when using the -WhatIf switch

### ISSUE THREAD

**Issue by bergmeister** [Azure/azure-powershell#13231]
## Steps to reproduce

```powershell
Invoke-AzDataFactoryV2Pipeline -ResourceGroupName $ResourceGroupName  -DataFactoryName $DataFactoryName -PipelineName $PipelineName -WhatIf
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

Az.DataFactory 10.0.2 from Az 4.8.0

## Error output
NA

**Comment by dingmeng-xue** [comment]
Service team, please help to look into this question.

**Comment by shawnxzq** [comment]
@LijuanZ Could you please look into this? Thanks a lot!

**Comment by shawnxzq** [comment]
@bergmeister ADF doesn't support the "-WhatIf" switch yet, we will try to add the support later, thanks for the feedback.

**Comment by bergmeister** [comment]
You missed the point: That ADF cmdlet already wrongly declares support for WhatIf but does not implement it, which is a severe bug. At the minimum you need to turn the WhatIf option for that cmdlet off right now by setting `SupportsShouldProcess=false` in that cmdlet.

**Comment by shawnxzq** [comment]
@bergmeister Yes, we will firstly disable it and then try to add the support ASAP, thanks for the further comment on this.

**Comment by shawnxzq** [comment]
@bergmeister We already coded the fix, but it needs to wait for the next PS release train which is scheduled 12/29, you will get the fix soon, thanks for you patience on this.

**Comment by bergmeister** [comment]
Thanks :)

**Comment by shawnxzq** [comment]
Issue fixed, close it.
