### ISSUE TITLE
Cannot Retrieve Full Version Number

### ISSUE THREAD

**Issue by BhargaviAnnadevara-MSFT** [Azure/azure-powershell#13248]
Referenced from: https://github.com/MicrosoftDocs/azure-docs-powershell/issues/1594#issue-719454508
Issue opened by @camsilv

Hi, when looking at an extension in the portal, we can see the full version number i.e. 1.4.1654.1. When using Get-AzureRmVMExtension (or it's AZ equivalent) This is truncated to simply "1.4" as the "typeHandlerVersion" property. Is it possible to get back the full version number?

Thanks

**Comment by dingmeng-xue** [comment]
@BhargaviAnnadevara-MSFT , thanks for reporting.

Could you please try `Get-AzVMExtension` and enable debug log via `$DebugPreference="Continue"`? Please share the debug message to us.

**Comment by BhargaviAnnadevara-MSFT** [comment]
> @BhargaviAnnadevara-MSFT Bhargavi Annadevara FTE , thanks for reporting.
> 
> Could you please try `Get-AzVMExtension` and enable debug log via `$DebugPreference="Continue"`? Please share the debug message to us.

@camsilv Could you please provide the requested information and take the discussion forward?

**Comment by amjads1** [comment]
@BhargaviAnnadevara-MSFT , @camsilv - Let us know if you are still looking for any help here.

**Comment by camsilv** [comment]
Hi All, thanks for the responses. we managed to get what we wanted for the NetworkWatcher extension

AZ + AzureRM:

$json = (az vm get-instance-view -g pcsdev-weu-jum-rg10 -n pcsdevweujum02 --output json)
(($json |convertfrom-json).instanceview.vmagent.extensionhandlers | ? {$_.type -eq "Microsoft.Azure.NetworkWatcher.NetworkWatcherAgentWindows"}).TypeHandlerVersion
1.4.1654.1

Just AzureRM

(Get-AzureRmVMExtension -ResourceGroupName "pcsdev-weu-jum-rg10" -VMName "pcsdevweujum01" -Name AzureDiskEncryption -Status).Statuses.Message -match "version: ([\d\W]+)().$)" | out-null ;$Matches[1]
1.4.1654.1

**Comment by amjads1** [comment]
Thanks for the update @camsilv . I will go ahead and close this issue now but feel free to let us know for any issues.
