### ISSUE TITLE
New-AzSapMonitorProviderInstance needs to support other provider types

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#13256]
## Description of the new feature

Provider instance should support below types

Provider Type | Provider Properties
-- | --
SapHana | {"hanaHostname":"10.0.0.6","hanaDbName":"SYSTEMDB","hanaDbSqlPort":30015,"hanaDbUsername":"SYSTEM","   hanaDbPassword":"<password>"}
PrometheusHaCluster/ PrometheusOS | {"prometheusUrl":"http://10.0.0.21:9664/metrics"}
MsSqlServer | {"sqlHostname":"10.0.0.6","sqlPort":1433,"sqlUsername":"sqladmin","sqlPassword":"<password>"}

Again, the properties field will be validated in the API level so you don’t have to worry about it. The PowerShell command should only need Provider Type and Provider Properties along with SapMonitor Name, Resource Group and, Provider Instance Name.

**Comment by dolauli** [comment]
Completed in Az.HanaOnAzure 0.3.0
