### ISSUE TITLE
[Az.Functions] Add support to create Python 3.9 function apps with preview flag

### ISSUE THREAD

**Issue by stefanushinardi** [Azure/azure-powershell#13266]
## Description of the new feature
ETA for python 3.9 support in Functions is Mid-November

## Proposed implementation details (optional)
@Francisco-Gamino please triage

**Comment by Francisco-Gamino** [comment]
Please see https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/pull/24/files for Stack API changes.

cc: @Hazhzeng

**Comment by stefanushinardi** [comment]
Update: we do not need the preview flag anymore. Thanks

**Comment by mrZreat** [comment]
Is there any chance to see this change in the official Az Powershell release soon? Unfortunately, the current version (5.9.0) has no idea about python 3.9 support, while I see that the fix was done quite long time ago...

**Comment by Francisco-Gamino** [comment]
This issue has been fixed in the latest Az.Functions release.
