### ISSUE TITLE
Ability to get front door id with Get-AzFrontDoor

### ISSUE THREAD

**Issue by PaulVrugt** [Azure/azure-powershell#13291]
## Description of the new feature
The azure cli includes the `frontdoorId` property when getting a front door using `az network front-door show`, but there doesn't seem to be a way to get this property user azure powershell

## Proposed implementation details (optional)
A `Properties` node could be added to the result, that includes the `frontdoorId` and other missing properties

**Comment by dingmeng-xue** [comment]
Service team, please help to look into this question.
