### ISSUE TITLE
Bug report template should add a disclaimer not to share any PII information

### ISSUE THREAD

**Issue by sandeepraichura** [Azure/azure-powershell#13301]
## Description
We recently posted a GitHub issues for a customer, regarding the Azure Modules. The issue is not of interest. Anyhow, I used this link and chose Az module bug report: https://github.com/Azure/azure-powershell/issues/new/choose

At the part in the template:
## Debug output

Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block

We pasted the outputs of the customer, which in fact reveals: domain name, tenant id, subscription and username triggering the request.

This raised a whole new issue with the customer, as basically we disclosed PII over this post.

Therefore, it would be advisable to have a disclaimer on the instruction, saying to remove PII information or as for something more specific not the whole debug output.

**Comment by dcaro** [comment]
@sandeepraichura this is a good feedback. We'll add this shortly.

**Comment by silenceman65** [comment]
Thanks so much ! I am pleasure it. It prevents him to annoying me.. Pls keep eye on his compute. He is smart and famous steal lots of people’s IP #  on his lists..  his name is Shawn Hampton, Tony candy Certuche jr, Gary Stephen and more people too.   

Thanks 

Rudy 🧏🏻
