### ISSUE TITLE
Pipeline timeout

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#13320]
## Description

Investigate why are the CI pipelines often timed out randomly.

### Retained pipeline runs

(core on windows) https://dev.azure.com/azure-sdk/public/_build/results?buildId=589661&view=results

## Cost

?

**Comment by dingmeng-xue** [comment]
Again, SQL related test cases.

**Comment by isra-fel** [comment]
We did a few things to stop timeout:

- Skipped some cases in data lake store: #13547
- Implement Dispose() for Sql's base class of tests: #13644

So far so good. Closing the issue.
