### ISSUE TITLE
Regression in Set-AzureSubscription

### ISSUE THREAD

**Issue by jodoglevy** [Azure/azure-powershell#1332]
We noticed the following regression in version 1.0.1 of the Azure (ServiceManagement) module:
![fdg](https://cloud.githubusercontent.com/assets/234589/11290135/b872f3d2-8ee8-11e5-8fec-070935df91b3.png)

Current storage account name is not correctly set.

**Comment by devigned** [comment]
What do you think about a pull request?

**Comment by markcowl** [comment]
@jodoglevy @devigned As discussed offline, this is an issue with display of the current storage account in service management cmdlets.  The current storage account is actually changed. Should be fixed with a .format.ps1xml change

**Comment by hovsepm** [comment]
Fixed in dev branch. Will be available in upcoming release.
