### ISSUE TITLE
Suspend-AzureRMAutomationJob is unable to suspend Job

### ISSUE THREAD

**Issue by SarveshPandey** [Azure/azure-powershell#13325]
## Steps to reproduce

```powershell

```

## Module versions

```powershell

```

## Debug output

```

```

I have schedule a job in Azure Automation which runs daily at and start my VM. Now, i want to disable this job for three days for this I used "Suspend-AzureRMAutomationJob" but unfortunately it didn't work.

![image](https://user-images.githubusercontent.com/25227161/97185624-4b58b400-17c6-11eb-9d7d-8d7030b1695d.png)

```

```

**Comment by dingmeng-xue** [comment]
@SarveshPandey , I have added Automation team in this thread. Could you share the debug log when you execute `Suspend-AzureRmAutomationJob`? In addition, AzureRm is an old version of modules. Please try its new version `Suspend-AzAutomationJob`

**Comment by SarveshPandey** [comment]
Yes, AzureRM is old version but when I tried using **Suspend-AzAutomationJob** in the Azure Automation Test Pane its throws error.

**Comment by dingmeng-xue** [comment]
Sure. please provide debug message which can help service team to narrow down the issue.

**Comment by SarveshPandey** [comment]
Here is the PowerShell script I used 

$connectionName = "AzureRunAsConnection"
$servicePrincipalConnection=Get-AutomationConnection -Name $connectionName         
    "Logging in to Azure..."
    Add-AzAccount `
        -ServicePrincipal `
        -TenantId $servicePrincipalConnection.TenantId `
        -ApplicationId $servicePrincipalConnection.ApplicationId `
        -CertificateThumbprint $servicePrincipalConnection.CertificateThumbprint 
$name = "gulf-oil"
$rg = "sarvesh"
$Id = "8f38541a-7f9a-48e5-8a92-39059b22c740"
Suspend-AzAutomationJob -AutomationAccountName $name -Id $Id -ResourceGroupName $rg

and error image

![image](https://user-images.githubusercontent.com/25227161/97616811-0ab99e80-1a43-11eb-9fd8-ec98351e0c2a.png)

**Comment by SarveshPandey** [comment]
did you get anything?

**Comment by jaspkaur28** [comment]
We are investigating the issue. Will share an update by next week .

**Comment by jaspkaur28** [comment]
We've got it added to our backlog & we are trying to prioritize it for Q1 - Feb , March timeframe.

**Comment by jaspkaur28** [comment]
Deferred to CY2021 Q3 due to other priorities. Will pick up this improvement July-Aug timeframe.

**Comment by Jassingh819** [comment]
It appears user wants to suspend the schedule instead of a job but is using the command to suspend a job and also has hard coded the job ID, AzAccounts mentioned by the user are working now and AzureRmAccount has already working for him but not giving him the desired output( seems to be a logical error on his end ).

Please use this to disable the schedule - 
https://docs.microsoft.com/en-us/azure/automation/shared-resources/schedules#disable-a-schedule-with-powershell
