### ISSUE TITLE
provide powershell object for .Net PSADPasswordCredential type

### ISSUE THREAD

**Issue by matt-gibbs** [Azure/azure-powershell#1334]
Currently, when creating an ADApplication, you have to directly create the underlying .NET PSADPasswordCredential type.
Suggestion is to provide a powershell wrapper object instead: 

$psadCredential = New-Object Microsoft.Azure.Commands.Resources.Models.ActiveDirectory.PSADPasswordCredential

**Comment by markcowl** [comment]
@namratab It's a bit difficult to create this type in PowerSHell - consider a helper cmdlet to create the type and pipe it into the New-AzureADApplication cmdlet
