### ISSUE TITLE
Connect-AzAccount fails as "InteractiveBrowserCredential authentication failed" (azure-powershell:5.0.0-ubuntu-18.04)

### ISSUE THREAD

**Issue by HansK-p** [Azure/azure-powershell#13340]
## Description
When using docker image "mcr.microsoft.com/azure-powershell" I get an error message when running "Connect-AzAccount". The error message is:
<pre>
PS /tmp> connect-azaccount
WARNING: Unable to acquire token for tenant 'organizations'
Connect-AzAccount: InteractiveBrowserCredential authentication failed: Unable to open a web page using xdg-open. See inner exception for details. Possible causes for this error are: xdg-open is not installed or it cannot find a way to open an url - make sure you can open a web page by invoking from a terminal: xdg-open https://www.bing.com 
</pre>
The same works when using the Docker image mcr.microsoft.com/azure-powershell:4.8.0-ubuntu-18.04. My guess is that there is an issue with the Docker image pushed a few hours ago with tag 5.0.0-ubuntu-18.04.

## Steps to reproduce

Fails, possibly image with tag 5.0.0-ubuntu-18.04 (at least that image fails the same way):
<pre>
$ docker run -it mcr.microsoft.com/azure-powershell bash
root@9d708463878c:/# pwsh
PowerShell 7.0.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS /> connect-azaccount
WARNING: Unable to acquire token for tenant 'organizations'
Connect-AzAccount: InteractiveBrowserCredential authentication failed: Unable to open a web page using xdg-open. See inner exception for details. Possible causes for this error are: xdg-open is not installed or it cannot find a way to open an url - make sure you can open a web page by invoking from a terminal: xdg-open https://www.bing.com 
</pre>

Works:
<pre>
root@0496b313c972:/# pwsh
PowerShell 7.0.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS /> connect-azaccount
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DRX36VGS9 to authenticate.
</pre>

## Environment data
<pre>
$ docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Oct 14 19:43:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Oct 14 16:41:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
</pre>

## Module versions

```powershell
Should not be needed
```

## Debug output

```
Should not be needed
```

## Error output
```
Should not be needed.
```

**Comment by alexandair** [comment]
Experienced the same error.

**Comment by dcaro** [comment]
@HansK-p @alexandair thanks for reporting the issue, we are looking at it

**Comment by dcaro** [comment]
With Az 5.0.0, the behavior of `Connect-AzAccount` is to try to launch the browser of the system to allow the user to perform the authentication to Azure. Unfortunately, in the container or in an SSH session, we cannot automatically launch the browser and the operation fails.

We will update the module to have a more understandable error message inviting to use devicecode authentication in those environments with no UI.
It is possible to consider switching to devicecode authentication if we cannot launch the browser but we prefer to maintain a consistent behavior across the environments for the moment.

**Comment by alexandair** [comment]
How is the error message (even a better error message) a consistent behavior when in Azure CLI `az login` falls back to devicecode authentication if the default browser couldn't be launched?

**Comment by dcaro** [comment]
We prefer to take a deterministic behavior for the connection to Azure over having a similar behavior with az cli. We could re-evaluate based on feedback.

**Comment by alexandair** [comment]
@dcaro 2 years ago, both teams have promised the consistency. How are two different approaches a consistent approach?

Users don't want "a similar behavior".
Users want exactly the same behavior.

If you are bringing SSO in the latest major releases, I don't want to see any differences anymore.

**Comment by HansK-p** [comment]
The main thing for me is that that a container can be easily used for doing Azure related tasks.

It's good if the error message received when running Connect-AzAccount can be used to easily understand what additional parameters must be added - or whatever - in order to do a successful authentication.

This time I was lazy and simply downgraded the image.

**Comment by Meyers93** [comment]
Experienced the same as of today

**Comment by erich-wang** [comment]
Thanks for your patience and suggestion.
As the first step, Az.Accounts 2.1.1 was just released to display clearer message to ask user use -DeviceCode switch instead.
Meanwhile, we're investigating about falling back to device code automatically. One concern is auto falling back was not provided in Az.Accounts 2.0.1-preview version and there's no feedback for it. We need understand which one is better.

**Comment by RobinB87** [comment]
More or less the same issue here. 
I can login by providing an az-context.json file in the image and using that for login in the PowerShell script.

However, when trying to select the correct subscription with I get the same error:
Get-AzSubscription -SubscriptionName $_subscriptionName | Set-AzContext

Error:
WARNING: Unable to acquire token for tenant '..'
WARNING: Unable to acquire token for tenant '..'
Get-AzSubscription: Subscription '..' was not found in tenant . Please verify that the subscription exists in this tenant.

Furthermore, it **only** shows the **default** subscription. 
I am also not able to change the default subscription. Using _Set-AzContext -Context $context_ or _Select-AzContext -InputObject $context_ (with the context set to the subscription I want) and then save does not seem to help.

**Comment by erich-wang** [comment]
@RobinB87 , it seems you're reporting different issue, could you please file another issue by providing detail info as described in template? 
In addition please add your host OS and container OS as well, thanks.

**Comment by erich-wang** [comment]
Close the issue as proper error message are shown if browser is unavailable. Also file issue #13514 to track request of automatically switching to DeviceCode if browser is unavailable.
