### ISSUE TITLE
AzRoleAssignment throw "Object reference not set to an instance of an object." error 

### ISSUE THREAD

**Issue by andrewliu0612** [Azure/azure-powershell#13364]
## Description
Last week, with the help from Az.Resources oncall, I uninstalled all az.resources module and installed version 2.4.0. The cmdlet New-AzRoleAssignment -RoleDefinitionName  -ObjectId  -Scope worked fine for me. 
This week, I think I uninstalled Az module for some reason. But when I re-install it and try the role assignment again, it throws the exception "Object reference not set to an instance of an object."

## Steps to reproduce

```powershell

```Connect-AzAccount -TenantId
New-AzRoleAssignment -RoleDefinitionName Owner -ObjectId <ServicePrincipal ObjectId> -Scope /providers/Microsoft.Billing/enrollmentAccounts/<EnrollmentAccountId>
New-AzRoleAssignment : Object reference not set to an instance of an object.
At line:1 char:1
+ New-AzRoleAssignment -RoleDefinitionName Owner -ObjectId cb8c54b0-179 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzRoleAssignment], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand


## Environment data

<!-- Please run $PSVersionTable and paste the output in the below code block
     If running the Docker container image, indicate the tag of the image used and the version of Docker engine-->

```

```

## Module versions

<!-- Please run (Get-Module  -ListAvailable) and paste the output in the below code block -->

```powershell

``` Directory: D:\OneDrive - Microsoft\Documents\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.0.0      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzR...


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.4.0      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzR...

## Debug output

<!-- Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block -->

```

```

## Error output

<!-- Please run Resolve-AzError and paste the output in the below code block -->

```
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use
`Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.

   HistoryId: 2

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {New-AzRoleAssignment}
Line           : New-AzRoleAssignment -RoleDefinitionName Owner -ObjectId cb8c54b0-1792-485e-a76b-06d5236f3e4e -Scope
                 /providers/Microsoft.Billing/enrollmentAccounts/641d4098-4344-40a7-818c-35dd4c9495e9
Position       : At line:1 char:1
                 + New-AzRoleAssignment -RoleDefinitionName Owner -ObjectId cb8c54b0-179 ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by dingmeng-xue** [comment]
Include resource management team to look into this issue.

**Comment by linehammer** [comment]
An Object is an instance of a Class , it is stored some where in memory. A reference is what is used to describe the pointer to the memory location where the Object resides. The message "object [reference not set](http://csharp.net-informations.com/language/reference.htm) to an instance of an object" means that you are referring to an object the does not exist or was deleted or cleaned up. It's usually better to avoid a NullReferenceException than to handle it after it occurs. To prevent the error, objects that could be null should be tested for null before being used.

```
if (mClass != null)
{
  // Go ahead and use mClass
  mClass.property = ...
}
else
{
  // Attempting to use mClass here will result in NullReferenceException
}
```

**Comment by SatishBoddu-MSFT** [comment]
Hello @andrewliu0612 , @linehammer    Apologies for the delayed response. I see that this issue is opened a long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know.
