### ISSUE TITLE
Register-AzureRMBackupContainer - parameter name incorrect

### ISSUE THREAD

**Issue by thehuxman** [Azure/azure-powershell#1337]
If running the below the servicename parameter is not actually the cloud service name or deployment name it's the Resource Group Name of the VM!! 

Register-AzureRMBackupContainer -Vault $backupvault -Name $sourcevm.Name -ServiceName <<Needs resource group!!>>

**Comment by markcowl** [comment]
@thehuxman Thanks for your feedback, we are taking a look.

@devigned Can you please assign to the appropriate contact on the Backup team?

**Comment by devigned** [comment]
@sriramvu is this yours?

**Comment by sriramvu** [comment]
It falls under RecoveryServices, but owned by BackUp team.Have communicated to Backup team (@dragonfly91, @AditTulasi, @mkherani).

**Comment by sriramvu** [comment]
It falls under RecoveryServices, but owned by BackUp team.Have communicated to Backup team (@dragonfly91, @AditTulasi, @mkherani).

**Comment by mkherani** [comment]
@thehuxman , @markcowl , @sriramvu , @devigned , This Parameter names are in sync with output of Get-AzureVm. Actually you can pipe get-azureVM output to Register-azurermbackupcontainer. To support pipeline we have two parameter set. Name-ServiceName pair to support old VM and Name-ResourceGroupName to support new Ibiza(ARM) VM. You can use either of param set or pass output of get-azurevm directly to register cmdlet. Hope I address your concern. Thanks
