### ISSUE TITLE
Bug with New-AzFunctionApp when created on Azure Gov

### ISSUE THREAD

**Issue by DiscoveringWorld** [Azure/azure-powershell#13379]
Hello,
I logged with Connect-AzAccount -Environment AzureUSGovernment
I created a storage on USGov Virginia.
After I tried to create an new function app with New-AzFunctionApp.
This command failed with The server responded with a Request Error, Status: BadRequest.

When I check the debug details its show that on the server side it try to use the public endpoint of the storage and not the azure gov endpoint storage123455622.file.core.usgovcloudapi.net/

This is the error:
"ErrorEntity": {
"ExtendedCode": "01020",
"MessageTemplate": "There was a conflict. {0}",
"Parameters": [
"The remote name could not be resolved: 'storage123455622.file.core.windows.net'"
],
"Code": "BadRequest",
"Message": "There was a conflict. The remote name could not be resolved: 'storage123455622.file.core.windows.net'"

**Comment by dingmeng-xue** [comment]
Functions team, please help to look into this question.

**Comment by DiscoveringWorld** [comment]
Hello
it,s not juste a question, it's a bug. The New-AzFunctionApp  does not try to search the storage name on the Azure Gov side, it's tring to search for the storage on a public commercial side. It should never try t search on public commercial side when used on Azure gov side.

**Comment by Francisco-Gamino** [comment]
@DiscoveringWorld  -- Thank you for reporting this issue.

I need more information to understand if the error is coming from client (the cmdlet) or the backend (the Functions service).

A couple of questions:
Could you please run the `New-AzFunctionApp` cmdlet with the `-WhatIf` switch? After doing this, what output do you get?
Are you able to create the function app via the Azure Portal or Az CLI using that storage account?

cc: @stefanushinardi @anirudhgarg

**Comment by DiscoveringWorld** [comment]
The storage used is on the Azure Gov side.

It's work well on the Azure portal on portal.azure.us  and o the az cli wit the az cloud set --name AzureUSGovernment  and 
az login 

The New-AzFunctionApp does not work since it's trying to search  storagefunction123422322  on Azure Public as you can see.

New-AzFunctionApp -ResourceGroupName functionRGName  -Name functiontesting12345  -StorageAccountName storagefunction123422322  -Runtime DotNet -RuntimeVersion 3 -FunctionsVersion 3 -Location "USGov Virginia" -WhatIf

VERBOSE: OSType for DotNet is 'Windows'.
What if: Performing the operation "Creating function app" on target "functiontesting12345".


StorageAccountName       ResourceGroupName PrimaryLocation SkuName        Kind      AccessTier CreationTime          ProvisioningState EnableHttpsTrafficOnly LargeFileShares
------------------       ----------------- --------------- -------        ----      ---------- ------------          ----------------- ---------------------- ---------------
storagefunction123422322 functionRGName    usgovvirginia   Standard_RAGRS StorageV2 Hot        11/5/2020 12:14:17 AM Succeeded         True

---
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 05 Nov 2020 00:24:46 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "Code": "BadRequest",
  "Message": "There was a conflict. The remote name could not be resolved: 'storagefunction123422322.file.core.windows.net'",
  "Target": null,
  "Details": [
    {
      "Message": "There was a conflict. The remote name could not be resolved: 'storagefunction123422322.file.core.windows.net'"
    },
    {
      "Code": "BadRequest"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "01020",
        "MessageTemplate": "There was a conflict. {0}",
        "Parameters": [
          "The remote name could not be resolved: 'storagefunction123422322.file.core.windows.net'"
        ],
        "Code": "BadRequest",
        "Message": "There was a conflict. The remote name could not be resolved: 'storagefunction123422322.file.core.windows.net'"
      }
    }
  ],
  "Innererror": null
}

-------

Get-InstalledModule -Name  Az.Functions


Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2.0.0      Az.Functions                        PSGallery            Microsoft Azure PowerShell - Azure Functions service cmdlets for Azure Resource Manager in Windows PowerS...

**Comment by Francisco-Gamino** [comment]
Hi @DiscoveringWorld -- I've removed some information from your post for privacy. I will look into this and follow-up with you. Thanks.

**Comment by DiscoveringWorld** [comment]
Hello

Did you reproduce the error on your side?

Did you found something?

Thanks to inform me.

Le mer. 4 nov. 2020 20 h 01, Francisco Gamino <notifications@github.com> a
écrit :

**Comment by Francisco-Gamino** [comment]
Hello @DiscoveringWorld,

Could you please tell me what output you get when you run this `(Get-AzContext).Environment` after you connect via ` Connect-AzAccount ...`? E.g.,

```
PS C:\> (Get-AzContext).Environment

Name       Resource Manager Url          ActiveDirectory Authority          Type
----       --------------------          -------------------------          ----
AzureCloud https://management.azure.com/ https://login.microsoftonline.com/ User-defined

PS C:\>
```

**Comment by DiscoveringWorld** [comment]
Name              Resource Manager Url                  ActiveDirectory Authority         Type
----              --------------------                  -------------------------         ----
AzureUSGovernment https://management.usgovcloudapi.net/ https://login.microsoftonline.us/ Built-in

**Comment by Francisco-Gamino** [comment]
Hello @DiscoveringWorld -- I have all the information I need. Yes, this is a bug in the cmdlet code (on the client side). 

cc: @stefanushinardi @anirudhgarg

**Comment by DiscoveringWorld** [comment]
So we are waiting for release soon or in several months ?

**Comment by Francisco-Gamino** [comment]
Hi @DiscoveringWorld -- I just had a sync with @stefanushinardi and we are trying to prioritize this work item. I will provide you with an ETA sometime next week.

**Comment by DiscoveringWorld** [comment]
Actually i used the portal to solve but for others peoples want to use
powershell to make functions, i think it will be a good idea to be fixed
soon.


Le jeu. 19 nov. 2020 19 h 30, Francisco Gamino <notifications@github.com> a
écrit :

**Comment by Francisco-Gamino** [comment]
Hi @DiscoveringWorld -- Great to hear that you were able to create the function app via the Portal. I agree, we should fix this soon.

**Comment by Quintinon** [comment]
My team is running into this issue as well when attempting to script out our environment deployment. Is there an ETA on fixing this issue or a workaround by providing different/additional information to the New-AzFunctionApp command?

**Comment by DiscoveringWorld** [comment]
Hello,
The only option for my was to create the Azure Function App on the Azure Gov portal.
I don't understand why Microsoft is so slow to solve this bug. It's almost 1 year and no one fix it.

**Comment by Francisco-Gamino** [comment]
Hello @Quintinon -- I am going to try to get this change in for the next milestone which is 2021-05-25.

**Comment by Francisco-Gamino** [comment]
Unfortunately, this fix requires to take a dependency on another cmdlet. New ETA is 6/15/21.

**Comment by Francisco-Gamino** [comment]
Hello @dingmeng-xue @dolauli  -- For this fix, I need to take a dependency on the `Get-AzContext`. Do you have an internal helper for `Az.Accounts` that I could use within `Az.Functions` ? Or is ok to call the cmdlet directly from the `Az.Functions` code? Please let me know. Thanks!

cc: @stefanushinardi @AnatoliB

**Comment by dolauli** [comment]
It is OK to call the cmdlet directly, since all azure modules replies on Az.Accounts. You can assume Az.Accounts is always installed in the users' machines.

**Comment by Francisco-Gamino** [comment]
Will do. Thanks @dolauli.

**Comment by Francisco-Gamino** [comment]
This issue is fixed the latest release.

**Comment by DiscoveringWorld** [comment]
Hello, seems nothing have been fixed for the issue in title  about New-AzFunctionApp for US gov. 

 "Code": "BadRequest",
        "Message": "There was a conflict. The remote name could not be resolved: 'storagefunction123422322.file.core.windows.net'"
      }
Before you close the issue, you should ask us to test it first.

**Comment by Francisco-Gamino** [comment]
Hello @DiscoveringWorld -- The new module version will be released tomorrow 7/2 to CloudShell and 7/6 to the PowerShell Gallery. The fix is part of this PR: https://github.com/Azure/azure-powershell/pull/15364.

**Comment by DiscoveringWorld** [comment]
Oh.. ok I was thinking it was available because of the closing, but not yet released.

**Comment by DiscoveringWorld** [comment]
Hello, 

I tried today in Azure Cloud Shell but same result.

Does this is the new version ?

Az.Functions             3.0.0    /usr/local/share/powershell/Modules/Az.Functions/3.0.0/Az.Functions.psd1

**Comment by Francisco-Gamino** [comment]
Hello @DiscoveringWorld -- The fix is in this version: https://www.powershellgallery.com/packages/Az.Functions/3.1.0. Please give it a try. Thanks.

**Comment by DiscoveringWorld** [comment]
Hello,

I got a new error now. I still use the same script as before.

$resLocation = 'USGov Virginia'
$CSPFunctionRGName = "CSPFunction12343424"
$CSPFunctionAppPlanName = "FunctionAppPlan123423"
$CSPFunctionAppName = "function123422322"
$CSPStorageFunctionName = "storagefunction123422322"

New-AzResourceGroup -Name $CSPFunctionRGName -Location $resLocation 
New-AzStorageAccount -ResourceGroupName $CSPFunctionRGName -AccountName $CSPStorageFunctionName -Location $resLocation -SkuName Standard_RAGRS 
New-AzFunctionAppPlan -ResourceGroupName $CSPFunctionRGName -Name $CSPFunctionAppPlanName -WorkerType Windows -Sku  EP1   -Location $resLocation 
New-AzFunctionApp -Name $CSPFunctionAppName   -ResourceGroupName $CSPFunctionRGName  -Location $resLocation  -Runtime dotnet -RuntimeVersion 3 -FunctionsVersion 3  -StorageAccount $CSPStorageFunctionName 


VERBOSE: OSType for dotnet is 'Windows'.
GetShareName : Cannot convert value "a" to type "System.Int32". Error: "Input string was not in a correct format."
At C:\Users\discoveringworld\Documents\WindowsPowerShell\Modules\Az.Functions\3.1.0\custom\New-AzFunctionApp.ps1:419 char:26
+             $shareName = GetShareName -FunctionAppName $Name
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [GetShareName], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToInteger,GetShareName

**Comment by DiscoveringWorld** [comment]
I tried that also on public commercial cloud and does not work too. seem related to the fix about

_Function app creation -- add two additional app settings (WEBSITE_CONTENTSHARE and WEBSITE_CONTENTAZUREFILECONNECTIONSTRING) for Linux Consumption apps
#15124_

**Comment by Francisco-Gamino** [comment]
Hello @DiscoveringWorld --  I cannot get this to repro on my local environment. I am using `West US 2` for the location. 

```powershell
PS C:\> $location = 'West US 2'
PS C:\> $functionAppName = "function123422322"
PS C:\> New-AzFunctionApp -ResourceGroupName $rd `
>>                   -Name $functionAppName `
>>                   -StorageAccountName $storageAccountName `
>>                   -Location $location `
>>                   -OSType Windows `
>>                   -Runtime DotNet `
>>                   -FunctionsVersion 3 `
>>                   -WhatIf
VERBOSE: 'DotNet' runtime version is specified by FunctionsVersion. The value of the -RuntimeVersion will be set to '3'.
What if: Performing the operation "Creating function app" on target "function123422322".
PS C:\>
```

Here is my environment information:

```powershell
PS C:\> gmo -list Az.Functions


    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     3.1.0                 Az.Functions                        Core,Desk {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get-AzFunctionAppPlan, Get-AzFunctionAppSetting…}

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.6
PSEdition                      Core
GitCommitId                    7.0.6
OS                             Microsoft Windows 6.2.9200
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\>

```

**Comment by Francisco-Gamino** [comment]
@DiscoveringWorld -- Let me know if you are available for a quick call tomorrow Thursday 7/8 or Monday 7/12, so we can take a look at your local environment. Thanks.

**Comment by DiscoveringWorld** [comment]
Hello,
the $rd and $storageAccountName  values are missing in the example.

I used cloudshell Azure gov to run my script and also a VM in Azure Gov Cloud. I tried directly also on my laptop and the same results.

It's not environmment stuff I think but the way this line is handled

```
   # If plan is Elastic Premium or Consumption (Windows or Linux), we need these app settings
        if ($planIsElasticPremium -or $consumptionPlan)
        {
            $appSettings.Add((NewAppSetting -Name 'WEBSITE_CONTENTAZUREFILECONNECTIONSTRING' -Value $connectionString))

            **$shareName = GetShareName -FunctionAppName $Name**
            $appSettings.Add((NewAppSetting -Name 'WEBSITE_CONTENTSHARE' -Value $shareName))
        }
```

**Comment by DiscoveringWorld** [comment]
On my side
```
PS C:\Windows\system32> gmo -list Az.Functions

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.1.0      Az.Functions                        {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get-AzFunctionAppPlan, Get-AzFunctionAppSetting...}

PS C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.1593
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1593
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Francisco-Gamino** [comment]
Thanks @DiscoveringWorld for the environment information. The issue repros on Windows PowerShell 5.1. Please feel free to open a new issue for this. 

In the meantime, could you please try PowerShell Core? I am using PowerShell version `7.0.6`, which is the version we host in the Azure Functions service. Here is the link to this version: https://github.com/PowerShell/PowerShell/releases/tag/v7.0.6. 
You can install it using the MSI x64: https://github.com/PowerShell/PowerShell/releases/download/v7.0.6/PowerShell-7.0.6-win-x64.msi.

**Comment by DiscoveringWorld** [comment]
I took bits of code from the powershell to understand the error and here is the error

 ```
 $FunctionAppName = "function123422322"
 $FunctionAppName = $FunctionAppName.ToLower()

 # Share name will be function app name + 8 random char suffix with a max length of 60
    $MAXLENGTH = 60
    $SUFFIXLENGTH = 8
    if (($FunctionAppName.Length + $SUFFIXLENGTH) -lt $MAXLENGTH)
    {
        $name = $FunctionAppName
    }
    else
    {
        $endIndex = $MAXLENGTH - $SUFFIXLENGTH - 1
        $name = $FunctionAppName.Substring(0, $endIndex)
    }

    $suffix = GetShareSuffix -Length $SUFFIXLENGTH
    $shareName = $name + $suffix




function GetShareSuffix
{
    param
    (
        [Int]
        $Length = 8
    )

    $letters = 'a'..'z'
    $numbers = 0..9
    $alphanumericLowerCase = $letters + $numbers

    $suffix = [System.Text.StringBuilder]::new()

    for ($index = 0; $index -lt $Length; $index++)
    {
        $value = $alphanumericLowerCase | Get-Random
        $suffix.Append($value) | Out-Null
    }

    $suffix.ToString()
}



Cannot convert value "a" to type "System.Int32". Error: "Input string was not in a correct format."
At line:9 char:5
+     $letters = 'a'..'z'
+     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToInteger


function GetShareSuffix
{
    [Microsoft.Azure.PowerShell.Cmdlets.Functions.DoNotExportAttribute()]
    param
    (
        [Int]
        $Length = 8
    )

    $letters = 'a'..'z'
    $numbers = 0..9
    $alphanumericLowerCase = $letters + $numbers

    $suffix = [System.Text.StringBuilder]::new()

    for ($index = 0; $index -lt $Length; $index++)
    {
        $value = $alphanumericLowerCase | Get-Random
        $suffix.Append($value) | Out-Null
    }

    $suffix.ToString()
}
```

**Comment by DiscoveringWorld** [comment]
Hello
you can take a look at Error creating function with New-AzFunctionApp on PowerShell 5.1 #15430

**Comment by Francisco-Gamino** [comment]
Indeed. The issue is that Windows PowerShell does not support this notation: `$letters = 'a'..'z'`. Let me know if you run into any issues using PowerShell Core. Thanks.

**Comment by DiscoveringWorld** [comment]
Job done ! It's work now with PowerShell 7.1

![image](https://user-images.githubusercontent.com/20508652/124854591-8cb87a80-df75-11eb-9c3c-f415e8a64d29.png)

**Comment by razamit** [comment]
How did you install the azure function tools into powershell 7?

**Comment by DiscoveringWorld** [comment]
Hello,
Take a look in the previous post or in this documentation:

New-AzFunctionApp
https://docs.microsoft.com/en-us/powershell/module/az.functions/new-azfunctionapp?view=azps-6.4.0****

**Comment by Francisco-Gamino** [comment]
Hello @razamit -- Here are the steps:

1) Install PowerShell 7 Core. When I am developing PowerShell Functions, I'd like to use the same version used the Azure Functions backend on my client tooling. In this case, install: https://github.com/PowerShell/PowerShell/releases/tag/v7.0.7. From this link, you can use the MSI installer.

2) Next, start PowerShell 7 elevated and run:
`Install-Module -Name Az.Functions`

**Comment by Karishma-Tiwari-MSFT** [comment]
@Francisco-Gamino A customer is seeing this issue when they are using Azure Powershell **task** on **Azure DevOps** to deploy the service. The Powershell task does not have an option to select latest version (7.1.4), thus they are still seeing this error. More details provided in this issue: https://github.com/Azure/azure-powershell/issues/16244

Can you please share your insights on how this can be resolved? Thanks.
