### ISSUE TITLE
Add-AzEnvironment doesn't expose ContainerRegistryEndpointSuffix parameter to update

### ISSUE THREAD

**Issue by rjaini** [Azure/azure-powershell#13377]
Install Az module using below commands on Azure Stack Hub env:

Install-Module -Name Az.BootStrapper -Force -AllowPrerelease
Install-AzProfile -Profile 2019-03-01-hybrid -Force
Install-Module -Name AzureStack -RequiredVersion 2.0.2-preview -AllowPrerelease

Now trying to add ContainerRegistryEndpointSuffix parameter in Add-AzEnvironment but no parameter is exposed to set registry value.

Get-help for the commandlet is not showing how to set above parameter.

Add-AzEnvironment [-Name] <System.String> [[-PublishSettingsFileUrl] <System.String>] [[-AzureKeyVaultDnsSuffix] <System.String>] [[-AzureKeyVaultServiceEndpointResourceId]
    <System.String>] [[-TrafficManagerDnsSuffix] <System.String>] [[-SqlDatabaseDnsSuffix] <System.String>] [[-AzureDataLakeStoreFileSystemEndpointSuffix] <System.String>]
    [[-AzureDataLakeAnalyticsCatalogAndJobEndpointSuffix] <System.String>] [[-EnableAdfsAuthentication]] [[-AdTenant] <System.String>] [[-GraphAudience] <System.String>]
    [[-DataLakeAudience] <System.String>] [[-ServiceEndpoint] <System.String>] [[-BatchEndpointResourceId] <System.String>] [[-AzureOperationalInsightsEndpointResourceId] <System.String>]
    [[-AzureOperationalInsightsEndpoint] <System.String>] [[-ManagementPortalUrl] <System.String>] [[-StorageEndpoint] <System.String>] [[-ActiveDirectoryEndpoint] <System.String>]
    [[-ResourceManagerEndpoint] <System.String>] [[-GalleryEndpoint] <System.String>] [[-ActiveDirectoryServiceEndpointResourceId] <System.String>] [[-GraphEndpoint] <System.String>]
    [-AzureAnalysisServicesEndpointResourceId <System.String>] [-AzureAnalysisServicesEndpointSuffix <System.String>] [-AzureAttestationServiceEndpointResourceId <System.String>]
    [-AzureAttestationServiceEndpointSuffix <System.String>] [-AzureSynapseAnalyticsEndpointResourceId <System.String>] [-AzureSynapseAnalyticsEndpointSuffix <System.String>]
    [-DefaultProfile <Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer>] [-Scope {Process | CurrentUser}] [-Confirm] [-WhatIf] [<CommonParameters>]

    Add-AzEnvironment [-Name] <System.String> [-ARMEndpoint] <System.String> [[-AzureKeyVaultDnsSuffix] <System.String>] [[-AzureKeyVaultServiceEndpointResourceId] <System.String>]
    [[-DataLakeAudience] <System.String>] [[-BatchEndpointResourceId] <System.String>] [[-AzureOperationalInsightsEndpointResourceId] <System.String>] [[-AzureOperationalInsightsEndpoint]
    <System.String>] [[-StorageEndpoint] <System.String>] [-AzureAnalysisServicesEndpointResourceId <System.String>] [-AzureAnalysisServicesEndpointSuffix <System.String>]
    [-AzureAttestationServiceEndpointResourceId <System.String>] [-AzureAttestationServiceEndpointSuffix <System.String>] [-AzureSynapseAnalyticsEndpointResourceId <System.String>]
    [-AzureSynapseAnalyticsEndpointSuffix <System.String>] [-DefaultProfile <Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer>] [-Scope {Process |
    CurrentUser}] [-Confirm] [-WhatIf] [<CommonParameters>]

    Add-AzEnvironment -AutoDiscover [-DefaultProfile <Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer>] [-Scope {Process | CurrentUser}] [-Uri
    <System.Uri>] [-Confirm] [-WhatIf] [<CommonParameters>]

**Comment by VeryEarly** [comment]
fixed in #13456
