### ISSUE TITLE
User-assigned managed identity regression in Az.Accounts 2.1.0

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-powershell#13371]
Before Az.Accounts **2.1.0**, user-assigned managed identities could be used in PowerShell Functions like this:

``` PowerShell
Connect-AzAccount -Identity -AccountId <guid>
```

Starting from Az.Accounts **2.1.0**, the same code reports the following error:

```
ManagedIdentityCredential authentication failed: Service request failed.
```

Please see for more details: https://github.com/Azure/azure-functions-powershell-worker/issues/552

**Comment by erich-wang** [comment]
Sorry for the inconvenience caused by the issue, please follow the comment https://github.com/Azure/azure-powershell/issues/13376#issuecomment-720301429.

**Comment by erich-wang** [comment]
Close as it is duplicate with #13376
