### ISSUE TITLE
New-AzDataFactoryV2LinkedServiceEncryptedCredential couldn't find assembly

### ISSUE THREAD

**Issue by fbuser1** [Azure/azure-powershell#13383]
I've an issue with latest (5.0) Az modules:

New-AzDataFactoryV2LinkedServiceEncryptedCredential -DataFactoryName "xxx-eus" -ResourceGroupName "xxx" -IntegrationRuntimeName "xxx" -DefinitionFile ".\sql.json" -Force

New-AzDataFactoryV2LinkedServiceEncryptedCredential : **Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The 
system cannot find the file specified.**
At line:1 char:1
+ New-AzDataFactoryV2LinkedServiceEncryptedCredential -DataFactoryName  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzDataFacto...yptedCredential], FileNotFoundException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataFactoryV2.NewAzureDataFactoryLinkedServiceEncryptedCredentialCommand

It repeats on my 20h2 win10 and server 2016/2019 installations. Same issue if install via MSI package or Install-Module

PS C:\Windows\system32> Get-Host
Version          : **5.1.19041.610**

**Comment by dingmeng-xue** [comment]
@fbuser1, thanks for reporting. This file should come from the latest Az.Accounts. Please share your loaded assemblies after `New-AzDataFactoryV2LinkedServiceEncryptedCredential` via below scripts
```
[System.AppDomain]::CurrentDomain.GetAssemblies()
```

**Comment by fbuser1** [comment]
> PS C:\Users\xxx> Get-Host

Version          : 5.1.17763.1490

> PS C:\Users\rinerate\Desktop\DataFactory> Get-InstalledModule Az.Accounts
                                                                                                             
2.1.0                Az.Accounts                         PSGallery            Microsoft Azure PowerShell - Accounts credential management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....

> PS C:\Users\xxx\Desktop\DataFactory> [System.AppDomain]::CurrentDomain.GetAssemblies()

GAC    Version        Location                                                                                                                                                                                            
---    -------        --------                                                                                                                                                                                            
True   v4.0.30319     C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll                                                                                                                                        
False  v4.0.30319     C:\Windows\System32\WindowsPowerShell\v1.0\powershell_ise.exe                                                                                                                                       
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.PowerShell.ISECommon\v4.0_3.0.0.0__31bf3856ad364e35\Microsoft.PowerShell.ISECommon.dll                                                         
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll                                                                                                         
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll                                                                             
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll                                                                                         
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Management.Automation\v4.0_3.0.0.0__31bf3856ad364e35\System.Management.Automation.dll                                                             
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll                                                                                               
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll                                                                             
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll                                                                                                 
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.PowerShell.GPowerShell\v4.0_3.0.0.0__31bf3856ad364e35\Microsoft.PowerShell.GPowerShell.dll                                                     
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.Composition\v4.0_4.0.0.0__b77a5c561934e089\System.ComponentModel.Composition.dll                                                   
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.PowerShell.Editor\v4.0_3.0.0.0__31bf3856ad364e35\Microsoft.PowerShell.Editor.dll                                                               
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll                                                                                               
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll                                                                           
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll                                                                                       
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll                                                                                               
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll                                                                             
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll                                                             
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll                                                                                           
False  v4.0.30319                                                                                                                                                                                                         
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll                                                                                   
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.DirectoryServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.DirectoryServices.dll                                                                     
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Management.Infrastructure\v4.0_1.0.0.0__31bf3856ad364e35\Microsoft.Management.Infrastructure.dll                                               
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll                                                               
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll                                                       
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll                                                                                                 
False  v4.0.30319                                                                                                                                                                                                         
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.PowerShell.Security\v4.0_3.0.0.0__31bf3856ad364e35\Microsoft.PowerShell.Security.dll                                                           
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll                                                                                       
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_64\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll                                                                                 
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.PowerShell.GraphicalHost\v4.0_3.0.0.0__31bf3856ad364e35\Microsoft.PowerShell.GraphicalHost.dll                                                 
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll                                                                                   
False  v4.0.30319                                                                                                                                                                                                         
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll                                                     
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemCore\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemCore.dll                                                     
False  v4.0.30319     C:\windows\system32\WinMetadata\Windows.UI.winmd                                                                                                                                                    
False  v4.0.30319     C:\windows\system32\WinMetadata\Windows.Foundation.winmd                                                                                                                                            
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.WindowsRuntime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.WindowsRuntime.dll                           
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.WindowsRuntime\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.WindowsRuntime.dll                                                           
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.PowerShell.Commands.Utility\v4.0_3.0.0.0__31bf3856ad364e35\Microsoft.PowerShell.Commands.Utility.dll                                           
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration.Install\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.Install.dll                                                             
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Authentication.Abstractions.dll                                                                             
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Authentication.dll                                                                                          
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Authenticators.dll                                                                                          
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Authentication.ResourceManager.dll                                                                          
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Clients.Authorization.dll                                                                                   
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Clients.Compute.dll                                                                                         
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Clients.Graph.Rbac.dll                                                                                      
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Clients.Monitor.dll                                                                                         
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Clients.Network.dll                                                                                         
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Clients.PolicyInsights.dll                                                                                  
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Clients.ResourceManager.dll                                                                                 
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Common.dll                                                                                                  
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Storage.dll                                                                                                 
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Clients.Storage.Management.dll                                                                              
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Clients.KeyVault.dll                                                                                        
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Clients.Websites.dll                                                                                        
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Hyak.Common.dll                                                                                                                        
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.ApplicationInsights.dll                                                                                                      
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.Common.dll                                                                                                             
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Rest.ClientRuntime.dll                                                                                                       
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Rest.ClientRuntime.Azure.dll                                                                                                 
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.WindowsAzure.Storage.dll                                                                                                     
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.WindowsAzure.Storage.DataMovement.dll                                                                                        
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Clients.Aks.dll                                                                                             
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Strategies.dll                                                                                              
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.PowerShell.Commands.Management\v4.0_3.0.0.0__31bf3856ad364e35\Microsoft.PowerShell.Commands.Management.dll                                     
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.WSMan.Management\v4.0_3.0.0.0__31bf3856ad364e35\Microsoft.WSMan.Management.dll                                                                 
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll                                                                           
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll                                                                                                   
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll                                                                                               
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\Azure.Core.dll                                                                                                       
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\Microsoft.Bcl.AsyncInterfaces.dll                                                                                    
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Threading.Tasks.Extensions.dll                                                                                
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Memory.dll                                                                                                    
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Diagnostics.DiagnosticSource.dll                                                                              
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll                                                                                         
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll                                                                                       
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\Azure.Identity.dll                                                                                                   
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\Microsoft.Identity.Client.dll                                                                                        
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Text.Json.dll                                                                                                 
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll                                                                                   
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\Microsoft.Identity.Client.Extensions.Msal.dll                                                                        
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\Microsoft.IdentityModel.Clients.ActiveDirectory.dll                                                                  
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll                                                                                       
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll                                                         
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\Newtonsoft.Json.12.0.3.dll                                                                                           
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\Newtonsoft.Json.dll                                                                                                  
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Buffers.dll                                                                                                   
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Diagnostics.Tracing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Diagnostics.Tracing.dll                                                                 
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Net.Http.WinHttpHandler.dll                                                                                   
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Numerics.Vectors.dll                                                                                          
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Private.ServiceModel.dll                                                                                      
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Reflection.DispatchProxy.dll                                                                                  
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Runtime.CompilerServices.Unsafe.dll                                                                           
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Security.AccessControl.dll                                                                                    
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Security.Cryptography.Cng.dll                                                                                 
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Security.Permissions.dll                                                                                      
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Security.Principal.Windows.dll                                                                                
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.ServiceModel.Primitives.dll                                                                                   
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\PreloadAssemblies\System.Text.Encodings.Web.dll                                                                                        
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.ReaderWriter\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Xml.ReaderWriter.dll                                                                       
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.1.0\Microsoft.Azure.PowerShell.Cmdlets.Accounts.dll                                                                                        
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Security\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Security.dll                                                                                       
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Threading\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Threading.dll                                                                                     
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Collections\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Collections.dll                                                                                 
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Threading.Tasks\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Threading.Tasks.dll                                                                         
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Reflection.Extensions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Reflection.Extensions.dll                                                             
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Reflection\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Reflection.dll                                                                                   
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Linq\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Linq.dll                                                                                               
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.XDocument\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Xml.XDocument.dll                                                                             
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Globalization\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Globalization.dll                                                                             
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Collections.Concurrent\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Collections.Concurrent.dll                                                           
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Diagnostics.Tools\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Diagnostics.Tools.dll                                                                     
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Diagnostics.Debug\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Diagnostics.Debug.dll                                                                     
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.IO\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.IO.dll                                                                                                   
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Text.Encoding.Extensions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Text.Encoding.Extensions.dll                                                       
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Text.Encoding\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Text.Encoding.dll                                                                             
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.IO.Compression\v4.0_4.0.0.0__b77a5c561934e089\System.IO.Compression.dll                                                                           
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Extensions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Extensions.dll                                                                   
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll                                               
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.RuntimeInformation\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.RuntimeInformation.dll                   
True   v1.0.3705      C:\windows\assembly\GAC\Microsoft.mshtml\7.0.3300.0__b03f5f7f11d50a3a\Microsoft.mshtml.dll                                                                                                          
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.DataFactory\1.11.0\Microsoft.Azure.Management.DataFactory.dll                                                                                         
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.DataFactory\1.11.0\Microsoft.DataTransfer.Gateway.Encryption.dll                                                                                      
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.DataFactory\1.11.0\System.IO.FileSystem.AccessControl.dll                                                                                             
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.DataFactory\1.11.0\Microsoft.Azure.Management.DataFactories.dll                                                                                       
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.DataFactory\1.11.0\Microsoft.Azure.PowerShell.Cmdlets.DataFactoryV2.dll                                                                               
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Az.DataFactory\1.11.0\Microsoft.Azure.PowerShell.Cmdlets.DataFactories.dll                                                                               
False  v4.0.30319                                                                                                                                                                                                         
True   v4.0.30319     C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Diagnostics.StackTrace\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Diagnostics.StackTrace.dll

**Comment by shawnxzq** [comment]
@xumou-ms Could you please help this issue? Thanks!

**Comment by xumou-ms** [comment]
@fbuser1 Sorry, for a security reason. The cmdlet only supports PowerShell 7.0 or higher. Please refer the [latest official doc](https://docs.microsoft.com/en-us/powershell/module/az.datafactory/new-azdatafactoryv2linkedserviceencryptedcredential?view=azps-5.1.0). 
Can you try with PowerShell 7 and let me know if the issue can be resolved?

**Comment by fbuser1** [comment]
I've tried with latest stable PS (7.1), got blank error in output. No option to get error message

Version : 7.1.0

PS C:\Users\xxx\xxx\xxx\xxx\DataFactory> New-AzDataFactoryV2LinkedServiceEncryptedCredential -DataFactoryName "xxx-df-xxx" -ResourceGroupName "xxxx" -IntegrationRuntimeName "IRAgent" -DefinitionFile ".\xxxx.json" -Force -Verbose
VERBOSE: Performing the operation "Encrypting the connection string." on target ".\xxxx.json".
New-AzDataFactoryV2LinkedServiceEncryptedCredential:

![image](https://user-images.githubusercontent.com/36403476/99946597-4bc17c00-2d7f-11eb-9d7a-73336d81ab00.png)

**Comment by xumou-ms** [comment]
Can you try run the command with option `-debug` and paste the output here? Thanks.

**Comment by fbuser1** [comment]
```
Body:
{
  "version": "4.14.7605.1",
  "publicKey": "xxx",
  "serviceToken": "xxx",
  "identityCertThumbprint": "",
  "hostServiceUri": "net.pipe://xxxx/InternalService.svc/",
  "isIdentityCertExprired": false
}


New-AzDataFactoryV2LinkedServiceEncryptedCredential:
DEBUG: AzureQoSEvent: CommandName - New-AzDataFactoryV2LinkedServiceEncryptedCredential; IsSuccess - False; Duration - 00:00:02.2142050;; Exception - Microsoft.DataTransfer.Gateway.Encryption.GeneralException
   at Microsoft.DataTransfer.Gateway.Encryption.GatewayEncryptionClientV3Imp.Encrypt(String connectorLinkedServicePayload, IEnumerable`1 encryptionInfos)
   at Microsoft.DataTransfer.Gateway.Encryption.GatewayEncryptionClient.Encrypt(String connectorLinkedServicePayload, IEnumerable`1 encryptionInfos)
   at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.IntegrationRuntimeEncryptCredential(String resourceGroupName, String dataFactoryName, String integrationRuntimeName, String linkedServiceJson)
   at Microsoft.Azure.Commands.DataFactoryV2.NewAzureDataFactoryLinkedServiceEncryptedCredentialCommand.<>c__DisplayClass12_0.<ExecuteCmdlet>b__0()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force, String continueMessage, String processMessage, String target, Action action, Func`1 useShouldContinue)
   at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.ConfirmAction(Boolean force, String continueMessage, String processMessage, String target, Action action)
   at Microsoft.Azure.Commands.DataFactoryV2.NewAzureDataFactoryLinkedServiceEncryptedCredentialCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
```

**Comment by xumou-ms** [comment]
According to the payload, you didn't enable remote access of the IR. It's required for this cmdlet. You can refer [this](https://docs.microsoft.com/en-us/azure/data-factory/create-self-hosted-integration-runtime#high-availability-and-scalability) to enable it.

The restriction of AZ module is due to limits of .NET Standard. So if you don't want to enable remote access and/or want to use powershell 5. AzureRM cmdlet [`New-AzureRmDataFactoryV2LinkedServiceEncryptedCredential`](https://docs.microsoft.com/en-us/powershell/module/azurerm.datafactories/new-azurermdatafactoryv2linkedserviceencryptedcredential?view=azurermps-4.4.1) is an alternative. It's based on .NET Framework. And the usage is the same.

**Comment by shawnxzq** [comment]
@fbuser1 Is your issue resolved? Thanks!

**Comment by shawnxzq** [comment]
Shared solution and didn't get further response from customer, close it for now.

**Comment by DocGreenRob** [comment]
Thanks, saved me today too!
