### ISSUE TITLE
[ServiceFabric][Question] The term 'Connect-ServiceFabricCluster' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by aim-for-better** [Azure/azure-powershell#13391]
## Description
I have installed the module Az.ServiceFabric, but when I run Connect-ServiceFabricCluster cmdlet, I met the bellow error
The term 'Connect-ServiceFabricCluster' is not recognized as the name of a cmdlet
![image](https://user-images.githubusercontent.com/12733681/97860049-7306c980-1d3c-11eb-8e56-baed60400991.png)

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
@aim-for-better , thanks for reporting.  The latest ServiceFabric doesn't contain this cmdlet https://www.powershellgallery.com/packages/Az.ServiceFabric/2.2.0.

Please share where this cmdlet is mentioned.

**Comment by idear1203** [comment]
@dingmeng-xue , but one interesting thing: why do we have reference doc under "Azure PowerShell" for this cmdlet: https://docs.microsoft.com/en-us/powershell/module/servicefabric/?view=azureservicefabricps

![image](https://user-images.githubusercontent.com/7024383/113103298-b012b180-9231-11eb-9c1e-d1a1ddbdcee8.png)

**Comment by dingmeng-xue** [comment]
You can compare its link and the link of azure powershell online doc. You can see their module name is ServiceFabric without Az prefix. 🤣 
```
https://docs.microsoft.com/en-us/powershell/module/servicefabric/?view=azureservicefabricps
https://docs.microsoft.com/en-us/powershell/module/az.servicefabric/?view=azps-5.7.0#service-fabric
```
