### ISSUE TITLE
ErrorAction switch does not work with Get-AzureStorageContainer

### ISSUE THREAD

**Issue by Vijayaraghavanl** [Azure/azure-powershell#1339]
Until I used the newer version the below command used to work as expected:

If(!(Get-AzureStorageContainer -Name $DestinationContainer -Context $desContext -ErrorAction SilentlyContinue)){New-AzureStorageContainer -Name $DestinationContainer -Context $desContext}

But with the newer version ErrorAction switch does not work.

**Comment by markcowl** [comment]
@Vijayaraghavanl Slated to be fixed in the next release [#108479296] .  You can follow progress here:  https://www.pivotaltracker.com/story/show/108479296

**Comment by Vijayaraghavanl** [comment]
This has been fixed in the latest release. All set now!! Closing this issue.
