### ISSUE TITLE
Breaking change New-AzSubscription has been removed in version 5.0.0

### ISSUE THREAD

**Issue by michaelpace-tnt** [Azure/azure-powershell#13405]
## Description
Undocumented breaking change has been introduced into version 5.0.0 from 4.8.0.

The New-AzSubscription command has been removed from the Az.Subscription. 

A new command New-AzSubscriptionAlias has been in added where the only mandatory parameter AliasName but the purpose of command is not fully documented and does not cover requirements of New-AzSubscription

## Module version

Az.Subscription 0.8.0

**Comment by piotr-penar-dhsc** [comment]
+1 
it looks like the change between Az. Subscription 0.8.0 and 0.7.3 removed New-AzSubscription.

**Comment by dingmeng-xue** [comment]
Az.Subscription is still under preview and not wrapped by Az. 

I involve Subscription team to clarify it further.

**Comment by piotr-penar-dhsc** [comment]
hi, any progress with this problem?

**Comment by anuragdalmia** [comment]
Hello, we have documented the alias api scenarios https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription?tabs=rest-getEnrollments%2Cazure-cli-EA%2Crest-getBillingAccounts%2Crest-getBillingProfiles%2Crest-MCA%2Crest-getBillingAccount-MPA%2Crest-getCustomers%2Crest-getIndirectResellers%2Crest-MPA. We have made our latest version GA. The preview version is still available, but yes going forward the right way to create subs would be using the latest API. Let me know if this helps.

**Comment by jdelforno** [comment]
Duplicate Ticket: https://github.com/Azure/azure-powershell/issues/13165 

?

**Comment by Agazoth** [comment]
We have limited access to the customer tenant. New-AzSubscription has been working just fine until updating to 0.8.0. We really want to update to 0.8.0, but we also need to ask the customer for sufficient access to reveal:
```powershell
GET https://management.azure.com/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/enrollmentAccounts?api-version=2019-10-01-preview
```
in order to get this:
```powershell
"id": "/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/enrollmentAccounts/accountId0"
```
Our current access does not allow us to get this information and we are in the middle of implementing a new CAF/CCoE setup.

We do not want to revert to 0.7.3, since this is a brand new installation.

If you could provide information about retrieving the required information (billingAccountName and enrollmentAccountId) in a way fit for lesser technical people OR can provide the required access for the API call to succeed that would be a tremendous help.

**Comment by Msanzdelrio** [comment]
Hi, can we get any clarfication on what the AliasName parameter is used for? Also, how is the offertype specified in this new version? Thank you!

**Comment by Agazoth** [comment]
I figured out that billingAccountName is the id of the billing account in the Enterprise portal. Likewise, accountId is the id of the enrollment account in the Enterprise portal. Once you have these 2 id's, you can build the string needed for -BillingScope.

On top of that, you need to run New-AzSubscriptionAlias in the context of the accountId, so you need username and password of the corresponding AAD user.

**Comment by Agazoth** [comment]
Another  issue has surfaced. Now we have to figure out, how to do Connect-AzAccount with the Username/Password of the Enrollment Account :-(

**Comment by Agazoth** [comment]
According to the documentation [here](https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=rest-getEnrollments%2Cazure-powershell-EA) and [here](https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/grant-access-to-create-subscription?tabs=azure-powershell%2Cazure-powershell-2), we just need to create a Service Principal and make that SP owner on the Enrollment Account.

Then, we need to log in as the service account and run New-AzSubscriptionAlias, exactly as we did with New-AzSubscription.

We actually were able to create new subscriptions with New-AzSubscription, but that is not the case with New-AzSubscriptionAlias. The cmdlet insists, that my SP is unauthorzed:
```powershell
New-AzSubscriptionAlias: Operation returned an invalid status code 'Unauthorized'
```
According to the Debug log, the token gets created, and the API request to https://management.azure.com/providers/Microsoft.Subscription/aliases returns
```powershell
Body:
{
  "error": {
    "code": "UserNotAuthorized",
    "message": "User is not authorized to create subscriptions on this enrollment account"
  },
  "code": "UserNotAuthorized",
  "message": "User is not authorized to create subscriptions on this enrollment account"
}
```

**Comment by jhueppauff** [comment]
We see the exact same issue here. 

New-AzSubscription works but when shifting to New-AzSubscriptionAlias we get the unauthorized exception using the same SPN/App Registration as before. So maybe something changed also on the permissions side for the user?

**Comment by Agazoth** [comment]
I have now tried to run the REST version of [these](https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=rest-getEnrollments%2Crest-EA) instructions.

When generating a token with the EnrollmentAccount AAD user, I can create a subscription, when doing the same thing with a token generated for the SA with Owner permission on the EnrollmentAccount AAD user, the call fails.

This leads me to think, that the error is not with the cmdlet, but with the REST Api.

How can I make an issue on: 'https://management.azure.com/providers/Microsoft.Subscription/aliases/{aliasName}?api-version=2020-09-01'?

**Comment by m0rgenthau** [comment]
> According to the documentation [here](https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=rest-getEnrollments%2Cazure-powershell-EA) and [here](https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/grant-access-to-create-subscription?tabs=azure-powershell%2Cazure-powershell-2), we just need to create a Service Principal and make that SP owner on the Enrollment Account.
> 
> Then, we need to log in as the service account and run New-AzSubscriptionAlias, exactly as we did with New-AzSubscription.
> 
> We actually were able to create new subscriptions with New-AzSubscription, but that is not the case with New-AzSubscriptionAlias. The cmdlet insists, that my SP is unauthorzed:
> 
> ```powershell
> New-AzSubscriptionAlias: Operation returned an invalid status code 'Unauthorized'
> ```
> 
> According to the Debug log, the token gets created, and the API request to https://management.azure.com/providers/Microsoft.Subscription/aliases returns
> 
> ```powershell
> Body:
> {
>   "error": {
>     "code": "UserNotAuthorized",
>     "message": "User is not authorized to create subscriptions on this enrollment account"
>   },
>   "code": "UserNotAuthorized",
>   "message": "User is not authorized to create subscriptions on this enrollment account"
> }
> ```

We're running on the same issue. UseCase is, that we have an Azure Function, taking Input from an internal Webinterface to create subscriptions. The Function uses a system managed AzureAD Identity.

The Service Principal is Owner on the target Enrollment account via https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/grant-access-to-create-subscription?tabs=azure-powershell%2Crest-2

Additionally during troubleshooting, we added an AzRoleAssignment as Owner for the SP at the scope 
 /providers/Microsoft.Subscription, our rationale was, that the SP needs permissions on /providers/Microsoft.Subscription/alias which can't be modified via New-AzRoleAssignment (scope needs to be an even number of parts).

Still we're seeing in the Tenant Activity Log only an Access Denied:
```
eventCategory  : Administrative
entity         : /providers/Microsoft.Subscription/aliases/Testsub40
message        : Microsoft.Subscription/aliases/write
hierarchy      :
eventtimespamp :
eventTimestamp : 2020-11-30T16:18:16.3535487Z
```

```
statusCode       : Unauthorized
serviceRequestId : <ID>
statusMessage    : {"error":{"code":"UserNotAuthorized","message":"User is not authorized to create subscriptions on this enrollment account"}}
eventCategory    : Administrative
entity           : /providers/Microsoft.Subscription/aliases/Testsub40
message          : Microsoft.Subscription/aliases/write
hierarchy        :
eventtimespamp   :
eventTimestamp   : 2020-11-30T16:18:17.2585577Z
```

**Comment by 1scscott** [comment]
We found the same issue with our subscription provisioning application. @anuragdalmia what is the concern with leaving the New-AzSubscription cmdlet in future releases?

**Comment by koenhalfwerk** [comment]
Exact same issue here, implementing a CCOE and stuck using 0.7.3 since we can't get the SPN to have enough rights

**Comment by m0rgenthau** [comment]
We have a support call for this issue, if anybody wants to attach: #120120125002207

**Comment by anuragdalmia** [comment]
Apologies for the delay here folks, while we investigate this in more detail, please re-delegate permissions to the SP using https://docs.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/enrollmentaccountroleassignments/put. Once you have delegated permissions, please try the latest APIs again. Please do share issues if you run into them.

Once again, apologies for the delay here. I will be monitoring this thread closely to help unblock asap.

**Comment by 1scscott** [comment]
We are using powershell to create subscriptions and would prefer to
continue doing so with the new-azsubscription cmdlet.

**Comment by TrondHaugmo** [comment]
Any news on this "issue"? It seems to be confirmed to be a bug. In my company we've built an internal process for automatic provisioning of new subscriptions that triggers an Azure Automation Runbook (PowerShell code) run on an Hybrid Worker which does the job. It currently use the 0.7.3 version of the Az.Subscription module and the New-AzSubscription cmdlet. That works just fine, but we have discovered that a newer version 0.8.0 of Az.Subscription exist, and that New-AzSubscription has been replaced by New-AzSubscriptionAlias in it. 

However, with this issue being reported here I'm worried to update the Az.Subscription module on our Hybrid Worker nodes to 0.8.0 and change the runbook code to use New-AzSubscriptionAlias. This is a production workload in our environment and will immediately cause issues for us if the functionality is broken. The runbook executes in the context of a SP which has been granted Owner rights on the Enrollment Account as described in https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/grant-access-to-create-subscription?tabs=azure-powershell%2Cazure-powershell-2#grant-access (and previous comments here seem to indicate that is when issues may be encountered).

**Comment by 1scscott** [comment]
@anuragdalmia  what is the purpose of the -AliasName parameter? It is not documented but looks to be required

**Comment by 1scscott** [comment]
@anuragdalmia what is the concern with retaining the new-azsubscription cmdlet?

**Comment by TrondHaugmo** [comment]
> Apologies for the delay here folks, while we investigate this in more detail, please re-delegate permissions to the SP using https://docs.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/enrollmentaccountroleassignments/put. Once you have delegated permissions, please try the latest APIs again. Please do share issues if you run into them.
> 
> Once again, apologies for the delay here. I will be monitoring this thread closely to help unblock asap.

Hello @anuragdalmia, one of my challenges with using this REST API call to perform the delegation again is that the only accounts that has permissions to do that in our environment is an ordinary admin-account which has MFA enabled. However, I only know how to perform a REST API call (using the "Postman" client) and performing authentication using a bearer token for a service principle retrieved from https://login.microsoftonline.com/<our_aad_tenant>/oauth2/token based on the SP's secret. This was much easier to accomplish when I could use PowerShell (after authenticating through Connect-AzAccount using an admin-account with the required permissions) and calling the New-AzRoleAssignment cmdlet with the appropriate ObjectID and Scope parameters set.

I'm an infrastructure "dude" and not that familiar with using REST API's directly (I normally only use PowerShell), so it may be easy enough to authenticate/authorize with an MFA enabled admin-account in Azure AD via REST API and the Postman client too, but that is currently "beyond me". Any advice would be useful here.

**Comment by TrondHaugmo** [comment]
By the way @anuragdalmia, is the reason for needing to perform delegation again for the SP on the enrollment account that the API's have been "restructured"? In earlier API versions it seems the scope path for Enrollment Accounts were directly under /providers/Microsoft.Billing (e.g /providers/Microsoft.Billing/enrollmentAccounts/{enrollmentAccountId}) while it now seems like enrollment accounts are "associated" with a given Billing Account also within the API structure (e.g providers/Microsoft.Billing/billingAccounts/{billingAccountName}/enrollmentAccounts/{enrollmentAccountName})....

**Comment by anuragdalmia** [comment]
We are working on updating our documentation to support PS and CLI options as well. We enabled the Alias API to enable ARM template based automation. Hence the reason to focus our efforts on one sub creation API. Once I have the documentation updated with PS, i will share the details. I am hoping to have this done in the next 2 weeks. Hopefully, that addresses majority of the concerns. We are looking at providing GA support for the alias API, the older sub creation API will continue to remain in preview mode available only in previous versions. 

The aliasname is the name of the alias. Think of Alias as a deployment name for creating a subscription. Subscription name is a different parameter. 

The new APIs to delegate permissions is fundamentally using a different DB behind the scenes. We explored doing a "migration" of permissions from the older DB to the newer one but were worried about security in case there are bugs in the migration code. Hence the reason to re-delegate using the latest APIs. We are working on a tool to help you make it easier to do this self-serve and we expect to have that by early March. 

Appreciate everyone's patience here, I understand this is a big change but we believe this is the right long term investment going forward. I will write back once I have updated the documentation with PS and CLI examples.

**Comment by ingo2812** [comment]
After a lot of throwbacks we finally managed it and the solution works. It took us several weeks to overcome the issues.

Here is what we have done for an Enterprise Agreement:

Usage:
Login with a "Global Subscription Owner" Account. The Account which should held all the subscriptions which are automatically created. It muss have Global Admin role to do the following.

Use this Api to create a role assignment:
1) https://docs.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/enrollmentaccountroleassignments/put#code-try-0

Fill in the Header as follows:

BillingAccountName: The technical name of the billingaccount of  Fiducia GAD. This is as 7-digit number in our case: xxxxxxx
BillingRoleAssignmentName: This is the object-id of the role "Account Owner" which is: c15c22c0-9faf-424c-9b7e-bd91c06a240b
(See also https://docs.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/billingroledefinitions/listbyenrollmentaccount#code-try-0)
This was misleading all the time. I thought I have to find this role in azure portal but it wasn't.

EnrollmentaccountName: The technical name of the enrollmentaccount of the "Global Subscription Owner", which is a 6-digit number: xxxxxx

Fill in the body for 1.:
Principal-ID: The Object-ID of  the Managed Identity, which should get the role.
Principal-Tenant-ID: your Tenant-ID string
roleDefinitionID: complete path/scope of the roledefintion of "Subscription Creator role"
(See also here to get that: https://docs.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/billingroledefinitions/listbyenrollmentaccount#code-try-0
Fill the api and look for "Subscription Creator Role".
It is also not documented that this role exists and is only assignable via REST-API and not in the Portal.)

After successful response of the role assignment, I was able to create subscriptions via the Powershell script and the Managed Identity.

Furthermore we had to adapt the access rights of the Managed Identitiy in order to assign the role "owner" to the requestor for the new subscription.

Managed Identity needs "User Acces Administrator" role in the root Management group in order to do this (only possible via powershell/rest-api)
see also: https://docs.microsoft.com/de-de/azure/role-based-access-control/elevate-access-global-admin

That's it!

**Comment by TrondHaugmo** [comment]
Thanks for sharing @ingo2812, this is useful but not sure if it gets us "completely over the finish-line". Good that you have your "needs" sorted of course! :-) Our billing account and enrollment account "structure" is maybe a bit more complex (as we a year back had to define an additional enrollment account, because we hit the limitations, at the time, of how many subscriptions you could provision programatically using the same enrollment account), so when I try to use https://docs.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/billingroledefinitions/listbyenrollmentaccount#code-try-0, I do not get any output from the call (reports response code 200, but the body is just empty). Thus, I'm unable to verify the header/body values I need to use for the https://docs.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/enrollmentaccountroleassignments/put#code-try-0 call I think.

I suspect I'm using wrong values for billingAccountName or enrollmentAccountName (even if I have checked them using the Get-AzBillingAccount and Get-AzEnrollmentAccount PS cmdlets), or the Azure AD login I use to authenticate (the login for enrollmentAccountName) when performing the REST API call for some reason does not have the required rights. I do however get output from the two mentioned PS cmdlets while authenticating with it. I also find it a bit confusing that you need to reference the "**Enrollment account owner**" role in the header of the enrollmentaccountroleassignment API call, and then you need to provide the path/scope of the "**Enrollment account subscription creator**" role in the request body. I do not see the logic behind that, but it is probably a bit besides the point.

Anyway, @anuragdalmia has indicated that the docs will get updated (and include examples on how to do these actions using PowerShell) in a couple of weeks time, so I guess I just have to wait for that to see if things get any clearer! :-)

That is perfectly fine for us, as we just keep the Az.Subscription module at 0.7.3 on the hybrid worker nodes that executes the runbook that takes care of subscription provisioning, and the New-AzSubscription cmdlet in our code for now.

**Comment by ingo2812** [comment]
@TrondHaugmo You are right. I still had a bug in my environment. After a little investigation - especially on the billingassigmentname, I found this, that helped me out: [https://github.com/Azure/Enterprise-Scale/blob/main/docs/Deploy/enable-subscription-creation.md](url)

**Comment by TrondHaugmo** [comment]
Hello @ingo2812, thanks a lot for sharing! 👍 That article was really a "gem" for us, and will certainly help us over the last "hurdles". Of course they had dealt with these things in the Enterprise Scale Landing Zones offering, and Kristian Nese and the others have prepared a well structured description of it in the article you found and shared! 😊

**Comment by NeilBird** [comment]
I was looking into this breaking change, as a customer had an Azure DevOps pipeline that was configured to use the "New-AzSubscription" cmdlet which has been removed, so the pipeline was failing using a hosted agent. 

As an alternative, I have suggested they consider using an ARM Template for Subscription creation, as per Microsoft's Enterprise Scale Landing Zone (ESLZ), documentation here: https://github.com/Azure/Enterprise-Scale/tree/main/examples/landing-zones/empty-subscription, if this helps others.

And from ESLZ link above if useful: _"**subscriptionAliasName**": It is recommended that the subscription alias name is the same as the displayName to ensure easier manageability_

**Comment by jhueppauff** [comment]
Is there any information when powershell will be available to set the required permissions?

**Comment by hbaviskar** [comment]
we had the same issue until yesterday, our account was GA and the enrollment account was the GA, but yet we have to run the command to make it as a owner and the issue was solved.

**Comment by jonashoye** [comment]
Did anyone ever resolve how to use the new API? We are still struggling with unauthorized access, even though the accounts has been set as owner on the enrollment account.

**Comment by BradAF** [comment]
> Did anyone ever resolve how to use the new API? We are still struggling with unauthorized access, even though the accounts has been set as owner on the enrollment account.

I was having the exact same error, what I did to resolve:

- Use an enterprise admin account to do the role assignment, NOT the enrollment account under which the subscriptions should be created
- The  account being delegated the 'Subscription Creator' role could not be an enrollment account itself and possibly not even an enterprise admin - I ended up removing the user account that would be creating the subscriptions under an enrollment account from the ea portal altogether

Snippet of how I got it going, with billingAccountId and enrollmentAccountId grabbed from the Cost Management and Billing list of IDs (NOT the AzureAD account GUID):

## Logged in as an Enterprise Admin Account

```
$subscriptionName = "01TestSubscription"
$currentContext = Get-AzContext
$token = Get-AzAccessToken
$roleAssignmentId = New-Guid
$enrollmentAccountId = "123456789"
$billingAccountId = "654321"


$objectId = Get-AzADUser -UserPrincipalName "upn_to_delegate_to@domain" | Select -expand Id

$body = @{ # API Requires that the Body be in JSON, so convert later.
    properties = @{
        principalId = "$objectID"
        principalTenantId = "your_tenant_id"
        roleDefinitionId = "/providers/Microsoft.Billing/billingAccounts/$($billingAccountId)/enrollmentAccounts/$($enrollmentAccountId)/billingRoleDefinitions/a0bcee42-bf30-4d1b-926a-48d21664ef71"
    }
}

$REST = @{
    Uri = "https://management.azure.com/providers/Microsoft.Billing/billingAccounts/$($billingAccountId)/enrollmentAccounts/$($enrollmentAccountId)/billingRoleAssignments/$($roleAssignmentId)?api-version=2019-10-01-preview"
    Headers = @{
        Authorization = "$($token.Type) $($token.Token)"
        'Content-type' = 'application/json'
    }
    Method = 'PUT'
    Body = $body | ConvertTo-JSON
}

$response = Invoke-RESTMethod @REST
```

Then, Clear-AzContext and re-login with the account the permission was delegated to (upn_to_delegate_to@domain)

```
New-AzSubscriptionAlias `
    -AliasName $subscriptionName `
    -SubscriptionName $subscriptionName `
    -BillingScope "/providers/Microsoft.Billing/billingAccounts/$($billingAccountId)/enrollmentAccounts/$($enrollmentAccountId)" `
    -Workload "Production"
```

Role assignment GUID I was able to grab from [here](https://docs.microsoft.com/en-us/rest/api/billing/2019-10-01-preview/billingroledefinitions/listbyenrollmentaccount#code-try-0), but doesn't appear unique.

**Comment by anuragdalmia** [comment]
We have a workitem to update the documentation for this which we will be doing soon to help with the issues that are talked about in this thread. Please let me know if folks continue to hit issues here.

**Comment by woter1832** [comment]
The problem appears to be with (lack of) permissions on the new API. When one was assigned an enrolment and therefore made an enrollment account owner, the permissions to create a subscription were granted.

This explains why I can create subscriptions via (deprecating) ea.azure.com that uses the legacy API, whereas in portal.azure.com, I get the error: 
```
You don't have permission to create a subscription for this billing account, contact the billing account owners.
```
If I use the [legacy API][1] or `New-AzSubscription` PS cmdlet, I can create a new subscription without issue, however, using the [new API][2] or `New-AzSubscriptionAlias` (crazy name), I get the error:
```
{
  "error":
    {
      "code" : "UserNotAuthorized",
      "message" : "User is not authorized to create subscriptions on this enrollment account"
    },
    "code" : "UserNotAuthorized",
    "message" : "User is not authorized to create subscriptions on this enrollment account"
}
```

As I am not a *Billing* Account Owner (EA Admin), I will need to find someone to re-grant the permissions, however, I cannot find any documentation on how to do this, or in fact any documentation that this is required apart from what our friend @anuragdalmia said:
> The new APIs to delegate permissions is fundamentally using a different DB behind the scenes. We explored doing a "migration" of permissions from the older DB to the newer one but were worried about security in case there are bugs in the migration code. Hence the reason to re-delegate using the latest APIs. We are working on a tool to help you make it easier to do this self-serve and we expect to have that by early March.

As it's now September 2022, @anuragdalmia could you point us to the "tool to help us make it easier", please? Failing that, point to/create documentation that I can show to our EA admin to re-delegate permissions.

A slight side note that has caused me to go around the houses, yesterday, `New-AzSubscriptionAlias` worked, but today it wouldn't, although I wouldn't put it past @Microsoft not to have broken something in the last 24 hours.

Thanks.

[1]:https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-preview?tabs=rest#create-subscriptions-under-a-specific-enrollment-account

[2]:https://learn.microsoft.com/en-us/rest/api/subscription/2020-09-01/alias/create?tabs=HTTP
