### ISSUE TITLE
"Connect-AzAccount -TenantId" - Add ability to use any verified domain instead of just GUID

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-powershell#13400]
## Description of the new feature

Please add the ability to use any verified domain when connecting using ```Connect-AzAccount -TenantId```.

Currently, if you specify a delegated domain, you'll get prompted for authentication twice and end up in your own tenant.

* If you supply tenant id of the delegated tenant on the other hand, you are right in.
* If you supply a verified domain even though it does not seem to work, you don't even validate whether input is a GUID. Thats sloppy.

## Proposed implementation details (optional)

Check if a verified domain is supplied on the tenant id parameter. If it is, find the tenant id (GUID) it belongs to, and use that to connect.

Example of a function that can do just that:

```powershell
# Get tenant id by any verified domain
## Function
function Get-MSTenantIdByVerifiedDomain {
    [OutputType([string])]
    Param (
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string] $Domain
    )
    (Invoke-RestMethod -Uri ('https://login.microsoftonline.com/{0}/.well-known/openid-configuration'-f$Domain) -Method 'Get').'userinfo_endpoint'.Split('/')[3]
}

## Test
Get-MSTenantIdByVerifiedDomain -Domain 'microsoft.com'
```

**Comment by dingmeng-xue** [comment]
@o-l-a-v , thanks for suggestion. I have tried the latest code and current logic is

- if tenant id is not provided, Az.Accounts will call https://management.azure.com/tenants?api-version=2019-06-01 to get all available tenants
- If tenant id is provided, Az.Accounts will login use teantId directly.

I didn't see "prompted for authentication twice". Could you clarify further?

**Comment by o-l-a-v** [comment]
> @o-l-a-v , thanks for suggestion. I have tried the latest code and current logic is
> 
> * if tenant id is not provided, Az.Accounts will call https://management.azure.com/tenants?api-version=2019-06-01 to get all available tenants
> * If tenant id is provided, Az.Accounts will login use tenantId directly.
> 
> I didn't see "prompted for authentication twice". Could you clarify further?

After update to Az.Account 2.1.2, I do not get prompted twice for authentication anymore. ADAL -> MSAL maybe?
Anyways, the problem still persist:

* If I ```Connect-AzAccount -Tenant $VerifiedDomainOnDifferentTenant -Subscription $SubscriptionIdOnDifferentTenant``` I get an error saying that I don't have access to specified subscription from the tenant of the user I'm logging in with. Which indicates that even though I specified any verified domain of the delegated/ different tenant, it authenticates to my user origin tenant.
* If I ```Connect-AzAccount -Tenant $TenantIdOnDifferentTenant -Subscription $SubscriptionIdOnDifferentTenant```, it works like a charm. Off course given that the user I use has access to that subscription. In my case it's through AOBO (we're a CSP provider).

**Comment by msJinLei** [comment]
Already supported in the latest Az.Accounts
