### ISSUE TITLE
Set-AzureStorageBlobContent requires READ instead of only WRITE

### ISSUE THREAD

**Issue by GitHubBJW** [Azure/azure-powershell#1340]
A few versions back (like 0.95) I was able to create a context using New-AzureStorageContext and a SAS token that used access policies.  I only needed to grant WRITE to the blob container access policy and Set-AzureStorageBlobContent worked fine.  Now it seems it requires READ and WRITE in order to write blob to a container!

$Context             = New-AzureStorageContext -StorageAccountName $AccountName -SasToken $SAS -Protocol https
# Used to work when WRITE was granted, but now requires READ & WRITE

Set-AzureStorageBlobContent -Container $Container -File $Folder\$File -Blob $File -Context $Context -Force

The impact of this, is that we used to have a secure way to accept uploads.  But with READ being enabled, this means those files are now available for anyone to download!

**Comment by EmmaZhu** [comment]
@GitHubBJW 
The cmdlet needs to check destination's existence, which requires READ permission, to avoid overwrite anything without noticed. This is a bit inconvenient if destination doesn't exist or you always want to overwrite destination. We'll open a work item to find a way to suppress this checking.

**Comment by dtrefilo-Quest** [comment]
The following snippet can be used to upload a file to blob without READ access.
`$context.StorageAccount.CreateCloudBlobClient().GetContainerReference($ContainerName).GetBlockBlobReference($item.Name).UploadFromFile($item.FullName, 'Open')`

**Comment by cormacpayne** [comment]
@blueww Hey Wei, do you know if this issue is still active?

**Comment by blueww** [comment]
@cormacpayne 
Yes, this issue is still active.
I will find some time try to fix it.

**Comment by blueww** [comment]
This is already fixed in the latest Azure PSH build release 6.5.0. So close the issue.
https://github.com/Azure/azure-powershell/releases
