### ISSUE TITLE
Get-AzActivityLogAlert (Az.Monitor v2.2.0) returns less information than API

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-powershell#13429]
## Description

```Az.Monitor\Get-AzActivityLogAlert``` returns less info than a get to ```'https://management.azure.com/subscriptions/{0}/providers/microsoft.insights/activityLogAlerts?api-version=2017-04-01' -f $SubscriptionId```.

Specifically what I'm missing is the value of the fields inside conditions. For instance, we have a activity log alert for service health alerts, where we input the regions we have resources in dynamically. To see what regions we have enabled for this alert, we can do the following on the results from the API

```powershell
$AllActivityLogAlertsRest.'properties'.'condition'.'allOf'.Where{$_.'field' -eq 'properties.impactedServices[*].ImpactedRegions[*].RegionName'}.'containsAny'
```

which will return a array of regions (Global, West Europe etc.).

But that information is not available with the data returned using the ```Get-AzActivityLogAlert``` cmdlet.

## Steps to reproduce

See description.

## Environment data

```
Name                           Value                                                                                                                          
----                           -----                                                                                                                          
PSVersion                      5.1.19041.546                                                                                                                  
PSEdition                      Desktop                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                        
BuildVersion                   10.0.19041.546                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                
WSManStackVersion              3.0                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                        
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands                                                                                    
---------- -------    ----                                ----------------                                                                                    
Script     2.1.2      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}                         
Script     1.4.0      Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAutomationDscNodeReportContent, Export-AzAutomatio...
Script     0.7.0      Az.Insights                         {Add-AzAutoscaleSetting, Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzWebtestAlertRule...}        
Script     2.2.0      Az.Monitor                          {Add-AzAutoscaleSetting, Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzMetricAlertRuleV2...}       
Script     0.7.0      Az.Profile                                                                                                                              
Script     3.0.0      Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzADAppCredential...}      
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                 
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                  
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}           
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                           
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}                     
```

## Debug output

```

```

## Error output

```

```

**Comment by VeryEarly** [comment]
Hi @o-l-a-v ,

Thanks for reporting, this "where" property doesn't seem to be existed in the current [SDK ](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/monitor/Microsoft.Azure.Management.Monitor/src/Generated/Models/ActivityLogAlertLeafCondition.cs)we are using.

@azmonALERTS can you please check if swagger need to be updated?
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/stable/2017-04-01/activityLogAlerts_API.json#L408

**Comment by TamRuas** [comment]
Our swagger and therefore SDK indeed don't support "ContainsAny" and "AnyOf" conditions which are used for Service Health and resource Health. 
We are actively working- on updating the swagger which required a new API version.
Bug 7359079: [Swagger] Add Missing 'anyOf' and 'containsAny' to ALA Swagger

I'll check about the powershell work item, and update that as well.

**Comment by TamRuas** [comment]
The powershell bug to track: 
Bug 8780491: Get-AzActivityLogAlert (Az.Monitor v2.2.0) returns less information than API

**Comment by o-l-a-v** [comment]
> The powershell bug to track:
> Bug 8780491: Get-AzActivityLogAlert (Az.Monitor v2.2.0) returns less information than API

Where can I follow the progress of bug number "8780491"?
And why close this issue, when it's still an issue affecting real world usage?

**Comment by VeryEarly** [comment]
> > The powershell bug to track:
> > Bug 8780491: Get-AzActivityLogAlert (Az.Monitor v2.2.0) returns less information than API
> 
> Where can I follow the progress of bug number "8780491"?
> And why close this issue, when it's still an issue affecting real world usage?

Hi @o-l-a-v ,

Reopen this issue, using this to track fixing progress of Azure-PowerShell for my team.

**Comment by dingmeng-xue** [comment]
Add service attention label because this issue depends on service side update. We will visit it again once new SDK is available.

**Comment by nolavime** [comment]
We are in process of adding that, this requires reviews, deployments and couple of internal processes.
 We are sure that this will be finished and used in the public cloud by the end of H1 2021, we believe that it will be in preview earlier.

**Comment by olalavi** [comment]
+ @Azure Activity Log Alerts Eng team<mailto:alaildceng@microsoft.com> to follow up on this.

**Comment by DavidHomerOxford** [comment]
Any update on this? It would be good if Microsoft set a policy to ensure feature parity between UI, REST API, an PowerShell PRIOR to releasing new functionality.
At the moment everything is either broken, inconsistent, or not documented.

**Comment by olalavi** [comment]
+ @Yair ***@***.***>, @Liad ***@***.***> - current owners to comment
Also can we find a way to reassign the issue?

Thank you.
Ola

**Comment by azmonALERTS** [comment]
Reassigned to Adi and to myself

**Comment by VeryEarly** [comment]
Saw new API version of activityLogAlerts which has the "ContainsAny" property available:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/monitor/resource-manager/Microsoft.Insights/stable/2020-10-01/activityLogAlerts_API.json#L448

No related SDK published yet.

**Comment by olalavi** [comment]
+ @Yair ***@***.***>, could you please help to re-assign to ALA team

Thank you,
Ola

**Comment by VeryEarly** [comment]
will be released on 2022-10-12
