### ISSUE TITLE
New-AzApiManagementApi requires ServiceUrl - but is not required in the Portal

### ISSUE THREAD

**Issue by Splaxi** [Azure/azure-powershell#13448]
## Description
When creating a new API in APIM, it is optional to fill in the Web Service Url:
![image](https://user-images.githubusercontent.com/8750181/98364077-66ca8700-2030-11eb-8c26-d0c02c2b8b6c.png)

But when creating a new API in APIM via New-AzApiManagementApi, the cmdlet is stating that the ServiceUrl is required.
```
Get-Help New-AzApiManagementApi -Full
...
    -ServiceUrl <System.String>
        Specifies the URL of the web service that exposes the API. This URL is used only by Azure API Management, and i
        s not made public. The URL must be one to 2000 characters long.

        Required?                    true
        Position?                    named
        Default value                None
        Accept pipeline input?       True (ByPropertyName)
        Accept wildcard characters?  false
...
```

If I fill in the ServiceUrl parameter with a valid URL string, the API is created as expected. I'm now able to go into the APIM instance in the portal and delete the Web Service Url from the API and save it, and it still works.

## Steps to reproduce

```powershell
New-AzApiManagementApi -ApiId '0001' -Context <PsApiManagementContext> -Name 'Echo api' -Path 'echov3' -Protocols Http

cmdlet New-AzApiManagementApi at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
ServiceUrl:
```

Here is the response from the APIM Management REST API, first one with the Service Url and the second after I removed it via the Portal:

With the service url filled in.
```
{
    "id": "/subscriptions/...../apis/0001",
    "type": "Microsoft.ApiManagement/service/apis",
    "name": "0001",
    "properties": {
        "displayName": "Echo api",
        "apiRevision": "1",
        "description": null,
        "subscriptionRequired": true,
        "serviceUrl": "http://echo.com",
        "path": "echov3",
        "protocols": [
            "http"
        ],
        "authenticationSettings": {
            "oAuth2": null,
            "openid": null
        },
        "subscriptionKeyParameterNames": {
            "header": "Ocp-Apim-Subscription-Key",
            "query": "subscription-key"
        },
        "isCurrent": true
    }
}
```

Without the Service Url configured in the APIM instance.
```
{
    "id": "/subscriptions/...../apis/0001",
    "type": "Microsoft.ApiManagement/service/apis",
    "name": "0001",
    "properties": {
        "displayName": "Echo api",
        "apiRevision": "1",
        "description": null,
        "subscriptionRequired": true,
        "serviceUrl": null,
        "path": "echov3",
        "protocols": [
            "http"
        ],
        "authenticationSettings": {
            "oAuth2": null,
            "openid": null
        },
        "subscriptionKeyParameterNames": {
            "header": "Ocp-Apim-Subscription-Key",
            "query": "subscription-key"
        },
        "isCurrent": true
    }
}
```
As the test is so simple to replicate - I don't see any value in filled out the remaining things. If you however feel that I need to provide more details, please let me know.

**Comment by msJinLei** [comment]
Api Management team, please help to look into this question.

**Comment by miaojiang** [comment]
@solankisamir could you please take a look?

**Comment by Splaxi** [comment]
Any updates on this?

**Comment by SatishBoddu-MSFT** [comment]
Hello @solankisamir @msJinLei Could you please let us know if this issue still persists? Are we good to close or any workarounds?

**Comment by rv2442** [comment]
Kindly re-open this, issue has not been resolved.
The Powershell command still requires the ServiceUrl
