### ISSUE TITLE
Problems using Powershell DSC on Azure Virtual Machines created using Resource Manager templates

### ISSUE THREAD

**Issue by gavinravenlane** [Azure/azure-powershell#13486]
Essentially, Powershell DSC does not behave consistently, and breaks our Azure Devops Pipelines. We install DSC modules using a Script resource, and then import the modules into the DSC scripts as required. But sometimes this process breaks, and when loading the DSC modules errors occur as the modules cannot be found.

We have not had much success getting a resolution to this issue, despite the efforts of various support engineers on cases 120100822000856 and 120103024003072. So this is a summary of what we know, and what is causing us an issue. We have been asked to raise this issue here as the engineers believe it is a Powershell issue.

The Environment

We use Azure Devops to develop our product, and Azure Pipelines to build, deploy and test the product. We achieve the deploy and test parts by deploying a new Resource Group in Azure for each Pipeline run. Each time one of these is created it, and its contained resources, are uniquely named and do not interact with resources in another Resource Group for another Pipeline run.

Some of the resources that are created are Virtual Machines. They are created from Azure resources provided by Microsoft, generally cloud-infrastructure-services ad-dc-2016 or  MicrosoftWindowsServer 2016-Datacenter. Since the first VM created in our Resource Group is the Domain Controller this problem, when it exhibits itself, tends to be on the ad-dc-2016 machine, but this is not always the case and it does sometimes occur on 2016-Datacenter machines.

Problem Frequency

The biggest problem we have is that this failure is NOT consistent. Many times this failure will NOT occur, but then it will suddenly occur consistently for a period of time – maybe a few days. This process is all driven by source code in our git repo, and the source code remains consistent BUT the problem occurs, then magically goes away, then occurs again etc. I am sure you get the idea.

Details of the problem

So, when the Powershell DSC module attempts to run, errors occur of the form:

    An error occurred while executing script or module 'DomainControllerDesiredState.ps1'
        Import-DscResource -Name PendingReboot; --> Unable to load resource 'PendingReboot': Resource not found.
        Import-DscResource -Name ADDomain;         --> Unable to load resource 'ADDomain': Resource not found.
        Import-DscResource -Name WaitForDisk;       --> Unable to load resource 'WaitForDisk': Resource not found.

Looking further back through the process it is clear that the Install-Module actions for these modules has failed during the Script processing. Looking even further back in the process, Get-PSRepository fails with

      WARNING: Unable to find module repositories.

Which of course provides the reason why the modules are not installed! Going back even further, Register-PSRepository -Default returns nothing and appears to do nothing.

So overall it looks like, sometimes, the DSC repository stuff is not accessible from within the Azure VM we happen to be creating. Of course this only happens SOMETIMES. Other times it all works fine. So testing and proving that anything is fixing the issue is something of a nightmare.

Any advice about what to look at next would be much appreciated.

Gavin Clark

**Comment by dingmeng-xue** [comment]
@gavinravenlane , thanks for reporting but I cannot get your problem. What's the DSC module? All module from Azure PowerShell repo have `Az.` as prefix. Could you explain further about your issue?

**Comment by gavinravenlane** [comment]
Hi
We have a general issue where any DSC module fails to install on the machine. The machine is an Azure VM which is created as part of an Azure Resource Group Manager Template. The VM has two extensions applied - the first is a script extension which fails to install the modules - e.g. the ComputerManagementDsc module to allow us to use the PendingReboot resource, or the ActiveDirectoryDsc module to allow us to use the ADDomain resource. This first script extension appears to silently continue when the modules cannot be installed.
The VM then has a second extension which is the DSC extension. This then falls over because it cannot import the resources from the modules that have failed to install in the script extension.
The perception we have is that there is a general issue with the machine contacting the Powershell Gallery to download the modules. But this only fails SOMETIMES - other times it works just fine and we have no issue.
Gavin

**Comment by dingmeng-xue** [comment]
Thanks @gavinravenlane . I cannot find the module owner of Dsc. One way is to report the issue on https://www.powershellgallery.com/packages/ComputerManagementDsc or please try Azure online support.

I am closing this issue due to it is irrelevant with Azure PowerShell module. Please contact us if you have further question on Az modules.
