### ISSUE TITLE
WebApp:Update-AzWebAppTrafficRouting cannot change traffic % of new deployment slots

### ISSUE THREAD

**Issue by kokosandim** [Azure/azure-powershell#13509]
Hi All
az.websites has a module/function Update-AzWebAppTrafficRouting
And it not works with new deployment slots, I mean when I try this
`Update-AzWebAppTrafficRouting -ResourceGroupName <rg-name> -WebAppName:<function-name> -RoutingRule @{ActionHostName='<function-name>.azurewebsites.net';ReroutePercentage="15";Name='tmp'}`
I see this error:
```
Update-AzWebAppTrafficRouting : "Given Routing Rule with name 'tmp' in WebApp '<function-name>' is not present.Please use a valid Name to remove "
At line:1 char:1
+ Update-AzWebAppTrafficRouting -ResourceGroupName <rg-name> ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Update-AzWebAppTrafficRouting], ValidationMetadataException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.TrafficRouting.UpdateAzureWebAppTrafficRoutingRuleCmdlet
```

BUT, when I change traffic percentage manualy on Azure Portal, after that this command works well!
This approach is not suitable for complete infrastructure automation. 
I guess this is a bug 

I didn't find any solutions for this issue yet

If you need more details, please let me know

Regards,
Nik

**Comment by dingmeng-xue** [comment]
Webapp team, please help to look into this question.

**Comment by Kotasudhakarreddy** [comment]
@kokosandim - you receive that error when the given `Name` in `-RoutingRule`  attributes is invalid/ not exist. please correct and try again. If you still face the issue please run the command with `-debug` and update the issue debug log.

**Comment by kokosandim** [comment]
@Kotasudhakarreddy - thanks for the answer
nothing wrong with the `name` or `routing rule` because this command works after doing manual changes in azure portal

debug output attached in file:
[outputAppFuncError_1.txt](https://github.com/Azure/azure-powershell/files/5584826/outputAppFuncError_1.txt)

and after that, I changed manually directly in azure portal function deployment slot routing rule and it works well from the same command.

thanks in advance

**Comment by KranthiPakala-MSFT** [comment]
@Kotasudhakarreddy - Following up to see if there is any update on this issue? - Thank you
