### ISSUE TITLE
Add-AzWebAppAccessRestrictionRule: Unable to use ServiceTag

### ISSUE THREAD

**Issue by ktdixit** [Azure/azure-powershell#13533]
Hi, 

My requirement is to add the Service Tag in the AzureFunction instead of adding all the IPs. 

Below script is not working. Please suggest what am I missing? I am using this in AzureDevOps Services Release Pipeline as Azure Powershell Task (v5.0)

**_Add-AzWebAppAccessRestrictionRule -ResourceGroupName $AzureResourceGroupName -WebAppName $AzureFunctionAppName -Name ServiceTagRule -Priority 100 -Action Allow -ServiceTag AzureCloud_**

**Error Message:** 
 ##[error]A parameter cannot be found that matches parameter name 'ServiceTag'.
##[error]PowerShell exited with code '1'.

**Reference (Add ServiceTag Access Restriction rule to a Web App):** https://github.com/Azure/azure-powershell/blob/master/src/Websites/Websites/help/Add-AzWebAppAccessRestrictionRule.md

Thanks in advance

**Comment by dingmeng-xue** [comment]
Webapp team, please help to evaluate this feature request.

**Comment by panchagnula** [comment]
@madsd isn't support for this already complete?

**Comment by wahyuen** [comment]
Just tried the exact same command on v5.1.0 and received the same error

**Comment by ktdixit** [comment]
also suggest for any other command /script to add IPFilters based on "Region".

**Comment by madsd** [comment]
Support for ServiceTag through PowerShell was released two days ago, so the DevOps tasks and/or Agents has probably not been updated to reflect that. Try updating the Az module before running the command with: **Update-Module -Scope CurrentUser -Name Az** 

Support for regions in the ServiceTag list should be added in Q1-2021

**Comment by ktdixit** [comment]
@madsd thanks for your response. Please note that below functionality is also not working with SubnetName: using AzurePowerShell 5.0 with Inline Script in AzureDevOps Services

Add-AzWebAppAccessRestrictionRule -ResourceGroupName $AzureResourceGroupName -WebAppName $AzureFunctionAppName -Name SubnetRule -Priority 100 -Action Allow -SubnetName **default** -VirtualNetworkName ******-***-***********-vnet**

Note: **Virtual Network Name**: ****-***-***********-vnet and **Subnet Name**: default

**_Error Message_**: 
##[error]Unable to deserialize the response.
##[error]PowerShell exited with code '1'.

**Comment by madsd** [comment]
@ktdixit the error will occur whenever you add ServiceTag rules or have existing ServiceTag rules **and** are using an old Az PowerShell module (< 5.1.0).
PowerShell module versions are different from Azure DevOps PowerShell Tasks - Azure PowerShell has a release cadence of 3 weeks where the tasks/hosted agents are updated much more infrequent.
You can force update the version by adding a normal PowerShell task prior to running the Azure PowerShell tasks - with this inline script: Install-Module -Name Az -AllowClobber -Force -Scope CurrentUser
In the Azure PowerShell task you then set the preferred version to 5.1.0
I can both reproduce the error and have tested the fix

For future troubleshooting, you can get the full error code from the above Error Message by running Resolve-AzError after the command (and set ErrorAction Preference to Continue in the Task)

Let me know if this will help

**Comment by ktdixit** [comment]
@madsd : Thank you very much for your quick response. It worked perfectly fine. Added 3 Tasks in AzureDevOps Release Pipeline (as Utility)

1. Powershell Task - Install-Module -Name Az -AllowClobber -Force -Scope CurrentUser
2. Azure Powershell Task - to add Multiple Custom IP Addresses 
3. Azure Powershell Task to include Service Tag (AzureCloud) and Virtual Network Name

All worked fine.
