### ISSUE TITLE
Get-AzureADMSGroup for Az Module

### ISSUE THREAD

**Issue by brendan-sherrin** [Azure/azure-powershell#13536]
**## Description of the new feature**
Get-AzureADMSGroup for the Az Module

**## Proposed implementation details (optional)**
Make an eqivalent version of this command for the Az Module.

Specifically you can select Dynamic groups in the old module with a:
Get-AzureADMSGroup | Where-Object {$_.GroupTypes -like "DynamicMembership"}

There's no direct equivalent I've found in the new Az replacement module and the old module doesn't work with Ps7.

**Comment by dingmeng-xue** [comment]
@brendan-sherrin , thanks for your asking. According to the agreement between Az and AzureAD, Az only provides fundamental features around AAD. Please use AzureAD module for advanced or the latest feature.
