### ISSUE TITLE
WebApp:[Documentation] New-AzAppServicePlan cmdlet missing -Linux parameter

### ISSUE THREAD

**Issue by michaelmaillot** [Azure/azure-powershell#13531]
The New-AzAppServicePlan [documentation](https://docs.microsoft.com/en-us/powershell/module/az.websites/new-azappserviceplan?view=azps-5.0.0) for the last version of the module is missing the property for "Linux" and so provides no details about its availability.

**Comment by dingmeng-xue** [comment]
Web App team, please look into this question. The doc should be updated.

**Comment by Kotasudhakarreddy** [comment]
@ThejaChoudary- please update the doc and publish.

**Comment by ThejaChoudary** [comment]
Documenation is updated hence proceeding to close the issue.Thank You.
