### ISSUE TITLE
RunVersionController.ps1 doesn't work with Az.StackHCI

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#13548]
## Description

`RunVersionController.ps1` will wipe out `RootModule` in psd1 and  generates a psm1 file from template.
But `Az.StackHCI` already has a psm1. If we run version controller on it, the psm1 file will be overwritten, and the module will not have any exported cmdlets.

## Cost
S

**Comment by dingmeng-xue** [comment]
@isra-fel , I tried the latest code and cannot see this issue. Could you verify again? In addition, I will try release branch today.

**Comment by isra-fel** [comment]
I cannot reproduce too. Looks like it's resolved by Xiaogang. Let me close the issue
