### ISSUE TITLE
Tokens still saved to TokenCache.dat file after Disable-AzContextAutosave

### ISSUE THREAD

**Issue by mciancia8** [Azure/azure-powershell#13541]
Following steps to repo:

1. I start a new powershell window.
2. I login with my user account with 'Connect-AzAccount'
3. I remove all context with 'Clear-AzContext' (verified that TokenCache.dat file is deleted)
4. I run 'Disable-AzContextAutosave'
5. I login again with my user account with 'Connect-AzAccount'
6. I go to ~/.azure directory and see TokenCache.dat created and has tokens in it.

**Comment by dingmeng-xue** [comment]
`Disable-AzContextAutosave` just disables saving profile files. But token cache still updates at that location. It is by design.

**Comment by mciancia8** [comment]
Ok, So if that is by design, they why does it work this way.

1. I start a new powershell window. 
2. I run 'Disable-AzContextAutosave'
3. I login again with my user account with 'Connect-AzAccount'
4. I go to ~/.azure directory and see TokenCache.dat has NO access tokens.

If I don't connect before running the disable command, then no access tokens are saved.

**Comment by dingmeng-xue** [comment]
@mciancia8 , this behavior is related to previous Az.Accounts 1.x. We had released new version of Az.Accounts with MSAL in October. This issue should not be experienced in the latest version.  Please try the new version and check it.

**Comment by mciancia8** [comment]
So I have version 5.1.0 installed, is that the latest version you are referring to? 

If so, I ran the same steps from both posts I have made and I still see the same issue. If I follow my first post, the file has access tokens and if I follow the steps from my second post, it has no access tokens in it.

So back to your first post, you said that tokencache.dat should be updated since its by design. I am confused then on the documentation of the command

"Turn off autosaving Azure credentials. Your login information will be forgotten the next time you open a PowerShell window"

Obtained from, https://docs.microsoft.com/en-us/powershell/module/az.accounts/disable-azcontextautosave?view=azps-5.1.0

It says it turns off credentials, is the token not considered a credential then? 

What is the recommendation on how to prevent any tokens from getting saved into that file?

**Comment by dingmeng-xue** [comment]
Thanks for feedback. It's a little strange that Az.Accounts 2.x starts to use MSAL and tokencache.dat is not needed. In my environment, there is no that file actually. We will test further. 

Is it possible that another powershell process with old version of Az.Accounts is running on your machine, vscode for instance?

**Comment by dingmeng-xue** [comment]
@mciancia8 , could you still see the same behavior when you only use powershell?

**Comment by mciancia8** [comment]
I was always running it directly in normal powershell. Not vscode, or powershell ISE

**Comment by dingmeng-xue** [comment]
Hi Michael, could you still hit the same problem? If yes, let's have a call and you can share your environment to me.
