### ISSUE TITLE
WebApp:Remove-AzWebAppAccessRestrictionRule.md in AzureDevOps Services

### ISSUE THREAD

**Issue by ktdixit** [Azure/azure-powershell#13553]
I want to use below 3 commands in AzureDevOps Services. Please guide how to use this: 

I am installing Powershell Module as a 1st Task: Install-Module -Name Az -AllowClobber -Force -Scope CurrentUser

**#1: Removing existing IPRule**

_Remove-AzWebAppAccessRestrictionRule -ResourceGroupName $AzureResourceGroupName -WebAppName $AzureFunctionAppName -Name MultipleIpRule_

**#2: Removing the ServiceTag**

_Remove-AzWebAppAccessRestrictionRule -ResourceGroupName $AzureResourceGroupName -WebAppName $AzureFunctionAppName -Name ServiceTagRule -ServiceTag AzureCloud_

**#3: Removing the Subnet & VirtualNetwork name**

_Remove-AzWebAppAccessRestrictionRule -ResourceGroupName $AzureResourceGroupName -WebAppName $AzureFunctionAppName -Name SubnetRule -Priority 100 -Action Allow -SubnetName default -VirtualNetworkName abc-def-vnet_

**_Error Message:_** 
##[error]Unable to deserialize the response.
##[error]PowerShell exited with code '1'.

**Comment by dingmeng-xue** [comment]
WebApp team, please help to look into this question.

**Comment by Kotasudhakarreddy** [comment]
@ktdixit - Could try them individually and check at which step it is failing to deserialize. And also provide the  debug log by adding `-debug` and run the command .

**Comment by madsd** [comment]
@ktdixit If you run Resolve-AzError after each command you should get the specific error message and stacktrace. That would be helpful

**Comment by madsd** [comment]
@ktdixit were you able to run the command again with Resolve-AzError to get the full error description?

**Comment by madsd** [comment]
@ktdixit Is it still relevant to keep this issue open. If it is, please help by providing a detailed error description.

**Comment by ktdixit** [comment]
> @ktdixit Is it still relevant to keep this issue open. If it is, please help by providing a detailed error description.

**Comment by ktdixit** [comment]
@madsd thank you and we can close this.
