### ISSUE TITLE
Error add subscription to management group - Powershell (New-AzManagementGroupSubscription)

### ISSUE THREAD

**Issue by esalazar1216** [Azure/azure-powershell#13577]
## Description
In the company I work for, I am the account owner of a department within the Azure hierarchy, at the EA portal level, I have the privileges of Account Owner and Administrator. Subscription creation is very dynamic in the company, so we use Az-cli code and Popwershell for this need. I have an error when trying to move a subscription of the offer type MS-AZR-0017P, which are for productive environments, it generates the following error, "New-AzManagementGroupSubscription: Permission to write on resources of type 'Microsoft.Management/managementGroups' is required on the management group or its ancestors". This only happens to me with accounts of this type of offer, I checked with Azure support and they tell me that I have all the privileges for them, that I should give feedback to the community that supports these codes, for them I escalate the case here.

Code detail:
New-AzManagementGroupSubscription -GroupName $ management_group -SubscriptionId $ subscription

where $management_group, the name of the group previously set, and $ subscription, the subscription id with the particularity of bringing it to be just the ID, given that some commands are from powershell or AZ-cli, the prefix must be added "subscriptions / + ID "

As an additional detail, try to do the process using az account management-group subscription add --name
                                             --subscription, but did not get positive result, does not execute.

How can I correctly implement adding subscruptions to the management group through scripts that can automate these tasks?

Thanks a lot.

**Comment by dingmeng-xue** [comment]
According to error message, it seems true that you need sufficient permission to add subscription to management group. 

Regarding to your concern, we believe "subscriptions/" is not required. Please reference example https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azmanagementgroupsubscription?view=azps-5.1.0#example-1--add-subscription-to-a-management-group

Please let us know whether you need further help.
