### ISSUE TITLE
Get-AzureRmBackupContainer case-sensitive to the -Name of container parameter

### ISSUE THREAD

**Issue by ivanignatiev** [Azure/azure-powershell#1358]
I have few VMs in the Backup Vault:

```
Get-AzureRmBackupContainer -Vault $backupVault -Type AzureVM 
Name              Type                   Status              
TestVm1AF1   AzureVM            Registered        
TestVm2AF1   AzureVM            Registered
```

The command:

```
Get-AzureRmBackupContainer -Vault $backupVault -Type AzureVM -Name "testvm1af1"
```

returns $null, but 

```
>Get-AzureRmBackupContainer -Vault $backupVault -Type AzureVM -Name "TestVm1AF1"
>Name                 Type                   Status                       
>TestVm1AF1      AzureVM            Registered  
```

The reason why Get-AzureRmBackupContainer should not be case-sensitive at least the fact that Azure Backup stores names of resources in case-sensitive format (ContainerUniqueName).

**Comment by markcowl** [comment]
@ivanignatiev Thanks for the issue, we are reviewing

**Comment by markcowl** [comment]
@devigned Please assign to the appropriate contact on the Azure Backup team

**Comment by devigned** [comment]
@sriramvu is this yours?

**Comment by sriramvu** [comment]
It falls under RecoveryServices, but owned by BackUp team.Have communicated to Backup team (@dragonfly91, @AditTulasi, @mkherani).

**Comment by mkherani** [comment]
@ivanignatiev. Thanks for using the product. This is known issue. Issue is with Azure table. Azure table doesn't provide case-insensitive search hence we need to pass the Name in correct case to service. To avoid this you can directly pass the Get-AzureVM output to the cmdlet. it will have correct case and will work fine.
