### ISSUE TITLE
AzureRm.Resources :: No documentation for -Pre parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1359]
Hello,

The `New-AzureRmPolicyDefinition` command has no documentation for the `-Pre` parameter.

<img width="313" alt="screen shot 2015-11-27 at 11 12 14 am" src="https://cloud.githubusercontent.com/assets/466713/11446705/f7b7a410-94f7-11e5-8c0e-8c8e9251c0c3.png">

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ravbhatnagar** [comment]
Consider adding a link in help to cover All the standard PowerShell params lie Pre, Information Action, ErrorAction etc.

**Comment by ravbhatnagar** [comment]
Fixed in Apr Rel
