### ISSUE TITLE
Get-AzEventHubNamespace should accept Pipeline-Input from Get-AzEventHub

### ISSUE THREAD

**Issue by Paxilein** [Azure/azure-powershell#13606]
## Description of the new feature

Currently it doesn't and complains about missing mandatory parameter: Namespace

**Comment by dingmeng-xue** [comment]
EventHub team, please help to evaluate this feature request.

**Comment by axisc** [comment]
@hakashya Can you make the recommended edits and make the PR so that this issue is addressed? Thanks
