### ISSUE TITLE
Get-AzContainerRegistryUsage shold accept Pipeline Input from Get-AzContainerRegistry

### ISSUE THREAD

**Issue by Paxilein** [Azure/azure-powershell#13605]
## Description of the new feature

Currently the parameters are not matching. Get-AzContainerRegistry takes "Name" and "ResourceGroupName" while Get-AzContainerRegistryUsage uses the Name as "RegistryName". So both should be the same and also should accept pipeline-input.

**Comment by dingmeng-xue** [comment]
@VeryEarly , please evaluate this feature request.

**Comment by VeryEarly** [comment]
Hi @Paxilein ,

Thanks for reporting this bug, fixed in #13608
