### ISSUE TITLE
Add information about API limits for Invoke-AzOperationalInsightsQuery

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#13602]
## Description
We should add a note in the reference doc for `Invoke-AzOperationalInsightsQuery` cmdlet about the API rate limits: 
https://docs.microsoft.com/en-us/azure/azure-monitor/service-limits#log-queries-and-language

**Comment by dingmeng-xue** [comment]
@VeryEarly , please look into this doc update.

**Comment by VeryEarly** [comment]
mentioned in doc: #13615

**Comment by dingmeng-xue** [comment]
Close it because doc is updated.
