### ISSUE TITLE
AzureRm :: New-AzureRmRoleDefinition Design Issue

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1362]
The `New-AzureRmRoleDefinition` command requires the user to pre-create a JSON file, or `PSRoleDefinition` instance, instead of defining user-friendly parameters such as:
- `-Name`
- `-Description`
- `-Actions`
- `-NotActions`

This user interface for this command should be re-thought.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@namratab This looks like some general feedback on the resource authorization cmdlets, see:  https://github.com/Azure/azure-powershell/issues/1334  as well

**Comment by maddieclayton** [comment]
Fixed.
