### ISSUE TITLE
WebApp:Add command for copying slots on Azure Web Apps

### ISSUE THREAD

**Issue by JasonFreeberg** [Azure/azure-powershell#13637]
**Is your feature request related to a problem? Please describe.**

No, this is a net-new feature.

**Describe the solution you'd like**

The web apps team has created a new API to *copy* one slot's content and config to another slot. This is similar to swapping slots, but the target slot's content and config would be replaced with that of the source slot's. 

- [API swagger definition](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/copyslotslot)

**Proposed signature**

Generally, the command should follow the format for [`Switch-AzWebAppSlot`](https://docs.microsoft.com/en-us/powershell/module/az.websites/switch-azwebappslot?view=azps-5.1.0). There a couple differences:

- "slot copy" does not support the "preview" action like swap does
- The target slot *cannot* be production

```
PS C:\Users\jafreebe> Get-Help Copy-AzWebAppSlot 
NAME
    Copy-AzWebAppSlot

SYNOPSIS
    Copy one slot's content and configuration onto another slot's.


SYNTAX
    Switch-AzWebAppSlot [-ResourceGroupName] <System.String> 
       [-SourceSlotName] <System.String> 
       [[-DestinationSlotName] <System.String>] 
       [-Name] <System.String>
       [-DefaultProfile <Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer>] 
      [-Confirm] [-WhatIf]
      [<CommonParameters>]

    Switch-AzWebAppSlot 
       [-SourceSlotName] <System.String> 
       [-WebApp] <Microsoft.Azure.Commands.WebApps.Models.PSSite>
       [[-DestinationSlotName] <System.String>]
       [-DefaultProfile <Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer>] 
       [-Confirm] [-WhatIf]
       [<CommonParameters>]


DESCRIPTION
    The Copy-AzWebAppSlot copies the source slot's content and configuration onto the source slot. The target slot cannot be the production slot.

RELATED LINKS
    Online Version: https://docs.microsoft.com/en-us/powershell/module/az.websites/copy-azwebappslot

REMARKS
    To see the examples, type: "get-help Copy-AzWebAppSlot -examples".
    For more information, type: "get-help Copy-AzWebAppSlot -detailed".
    For technical information, type: "get-help Copy-AzWebAppSlot -full".
    For online help, type: "get-help Copy-AzWebAppSlot -online"
```

**Additional context**

- [UserVoice](https://feedback.azure.com/forums/169385-web-apps/suggestions/6830040)

**Comment by ThejaChoudary** [comment]
Thank you for reporting.Will work on this based on priority.
