### ISSUE TITLE
[KeyVault] Support getting plain text secret with `-AsPlainText`

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#13630]
## Description
Adding an optional parameter to `Get-AzKeyVaultSecret`. When specified, outputs the plain text secret.

## Design choices
- Should we return the plain text secret only, or return a `PSKeyVaultSecret` object with an extra property representing the plain text secret?
    - Per below sggestions, we'll just return the secret text.
- Any other cmdlets also need `-AsPlainText`?
    - Not this time. 

## Expectation

It should work in
- [x] PowerShell 7.0, 7.1
- [x] PowerShell core
- [x] Windows PowerShell 5.1
- [x] [ConstrainedLanguage mode](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-7.1#constrained-language-constrained-language)
- [x] Linux
- [x] MacOS

## Cost
s

**Comment by dcaro** [comment]
cc @TylerLeonhardt

**Comment by SteveL-MSFT** [comment]
When AzKeyVault is used with https://www.powershellgallery.com/packages/Microsoft.PowerShell.SecretManagement module, you can use `Get-Secret -AsPlainText`.  Also, with PowerShell 7, you can use `ConvertFrom-SecureString -AsPlainText` instead of calling the .NET APIs.

**Comment by TylerLeonhardt** [comment]
@SteveL-MSFT problem is on SAWs where:

* No SecretManagement
* No PS7

I think Azure PowerShell should align with the behavior in SecretManagement and just return the string.
