### ISSUE TITLE
AzureRm :: Get-AzureRmAuthorizationChangeLog returns nothing, if user isn't authorized

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1364]
If you run `Get-AzureRmAuthorizationChangeLog` under an Azure Active Directory user context that doesn't have permission to read the authorization change log, the command silently fails. Instead, I believe that an unauthorized exception should be thrown.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by cormacpayne** [comment]
It doesn't appear we ship this cmdlet anymore. Closing this issue as a result.
