### ISSUE TITLE
Get-AzureRmProviderOperation should be renamed to Get-AzureRmResourceProviderOperation

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1365]
**NOTE:** This issue is separate from #1366.

The `Get-AzureRmProviderOperation` command should be renamed to `Get-AzureRmResourceProviderOperation` for consistency with other command naming conventions.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ravbhatnagar** [comment]
The proposed name makes more sense and will be consistent with other cmdlets. However, since this will be a breaking change, lets explore the right time to do this.

**Comment by pcgeek86** [comment]
@ravbhatnagar Let's try to avoid the "breaking change" excuse, as much as possible, and design this properly from the ground up. Communicate with your customers, explain the circumstances, and they'll thank you for it. Thanks for realizing that this consistency is good though. :) Really appreciate your attention to this large issue backlog. You will catch up eventually!

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by ravbhatnagar** [comment]
This is now owned by the PAS team. @rashidqureshi @shuagarw

**Comment by pcgeek86** [comment]
@ravbhatnagar What is "PAS?"

**Comment by markcowl** [comment]
@shuagarw @rashidqureshi  Please take a look

**Comment by bganapa** [comment]
Lets rename and add Alias.  I agree with the suggestion here.

**Comment by maddieclayton** [comment]
Closing as action item in https://github.com/Azure/azure-powershell/issues/1366 will fix.  This should be done by the next release.
