### ISSUE TITLE
New-AzSubscription cmdlet's future?

### ISSUE THREAD

**Issue by 1scscott** [Azure/azure-powershell#13668]
We use this cmdlet in our Azure subscription provisioning application built in Azure functions. We had the function's requirements.psd1 set to pull down the latest version for major version 0.*. 

When version 0.8.0 came out the cmdlet was no longer included.  To correct we set the version to 'Az.Subscription' = '0.7.3' 

Question, is the cmdlet being retired? if so why and what should we use in its place?

We have an EA with Microsoft and need the ability to set Enrollment ID, Offer Type and Object ID of the Subscription Owner.

**Comment by dingmeng-xue** [comment]
Involve service team to look into this question.

**Comment by ramaganesan-rg** [comment]
Thank you. Team will look into this!

**Comment by anuragdalmia** [comment]
@1scscott  - we have released our GA version for subscription creation APIs which is to use New-AzSubscriptionAlias cmdlet for subscription creation automations. You can see this documented in detail at https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=rest-getEnrollments%2Crest-EA.

We are asking everyone to move to adopt to this new cmdlet which is GA. We will keep the preview cmdlet around (only in older versions) until folks have had the chance to migrate and dont have a timeline when we will stop supporting preview versions.
