### ISSUE TITLE
Inconsistent naming :: Get-AzureRmProviderOperation

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1366]
> **NOTE**: This is a separate issue from #1365.
- In Azure Resource Manager (ARM) Role-based Access Control (RBAC), the term _Action_ is used to describe an operation against an ARM Resource
- The `New-AzureRmRoleDefinition` command uses JSON input using
- The `Get-AzureRmProviderOperation` command is intended to return a list of _Actions_ for each ARM Resource Type in each ARM Resource Provider.

Thus, the `Get-AzureRmProviderOperation` should probably be renamed to `Get-AzureRmResourceProviderAction`.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by maddieclayton** [comment]
[ ] Add alias "Invoke-AzureRmResourceOperation" to cmdlet "Invoke-AzureRmResourceAction"

**Comment by maddieclayton** [comment]
Fixed
