### ISSUE TITLE
The -OperationSearchString parameter on Get-AzureRmProviderOperation should not be mandatory

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1367]
The `-OperationSearchString` parameter on the `Get-AzureRmProviderOperation` command should not be mandatory. By default, the command should return a full list of possible _Actions_ that can be taken on all Resource Types, for all Resource Providers.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ravbhatnagar** [comment]
Yes, will fix this. In the meantime, you can get the list of all the possible actions using *. 
Get-AzureRmProviderOperation *

**Comment by pcgeek86** [comment]
@ravbhatnagar Awesome, thanks. Should be pretty a straightforward thing to fix. Just make the parameter non-mandatory, and the default parameter value `*`.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by markcowl** [comment]
@ravbhatnagar If this is npo longer in plan, we should close the issue as 'won't fix'

**Comment by maddieclayton** [comment]
Fixed
