### ISSUE TITLE
The -OperationSearchString parameter on Get-AzureRmProviderOperation should be renamed

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1368]
The parameter name `-OperationSearchString` is not very familiar to your average PowerShell user. I would recommend renaming this parameter to something more memorable and PowerShell-friendly, such as `-Name`.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ravbhatnagar** [comment]
Makes sense. Thanks for the feedback.

**Comment by pcgeek86** [comment]
@ravbhatnagar Sounds good, thanks. I understand the thought process behind the more complicated name, but from a PowerShell perspective, it's not really appropriate. The built-in PowerShell help documentation for this command would be the appropriate place to instruct customers how to utilize the parameter. You could put the details in the lengthier `Description` field, or the help for the parameter itself.

This should be standard across the board, for all PowerShell commands.

Cheers,
Trevor Sullivan

**Comment by ravbhatnagar** [comment]
Lets add an alias for this.

**Comment by ravbhatnagar** [comment]
Change in ownership of this.

**Comment by ravbhatnagar** [comment]
@markcowl - This is now not owned by the ARM team. PAS team owns this (Shubham)

**Comment by pcgeek86** [comment]
@ravbhatnagar What is "PAS?"

**Comment by markcowl** [comment]
@shuagarw can you comment?

**Comment by shuagarw** [comment]
@pcgeek86 - PAS is Policy Administration Service - this provides Role Based Access Control on Azure. 
@rashidqureshi to follow-up on this change.

**Comment by rashidqureshi** [comment]
Thanks for the feedback Trevor. The ownership has recently transitioned over to my team. We'll look into it and make it more intuitive for PowerShell users.

**Comment by pcgeek86** [comment]
@rashidqureshi Thank you!!

**Comment by maddieclayton** [comment]
Fixed
