### ISSUE TITLE
Use ARM storage account with Set-AzureDeployment for deploying to Azure cloud services

### ISSUE THREAD

**Issue by arjgupta** [Azure/azure-powershell#13686]
## Description

When using Set-AzureDeployment cmdlet (part of the Azure module) to deploy to Azure Cloud Services, I encounter an error like so:

`Set-AzureDeployment : CurrentStorageAccountName is not set. Use Set-AzureSubscription subname -CurrentStorageAccountName storageaccount to set it.`

If i execute the command suggested in the error message, then if using an ARM storage account, the command fails. Seems like it only works with classic storage accounts.

Is it possible to use ARM storage account with this command ? How ?

## Steps to reproduce

- Repro requires provisioning an Azure Cloud Service.

```powershell
Install-Module Azure
Add-AzureAccount
$ServiceName = "<Name of Azure cloud service>"
$servicePackageFile = "<cspkg path>"
$serviceConfigFile = "<cscfg path>"
$Slot = "<slot name>"
$Label = "foobar"
Set-AzureDeployment -Upgrade -ServiceName $ServiceName -Package $servicePackageFile -Configuration $serviceConfigFile -Slot $Slot -Label $label -Force
```

## Module versions

Azure module version 5.3.0

## Debug output

```

```

## Error output

Set-AzureDeployment : CurrentStorageAccountName is not set. Use Set-AzureSubscription subname -CurrentStorageAccountName storageaccount to set it.

**Comment by dingmeng-xue** [comment]
Hi Arjun, please check your script and usage. Actually, you cannot use AzureDeployment (RDFE related) with storage account deployed by ARM.

Please use Az modules if your environment is not basing on RDFE.

**Comment by arjgupta** [comment]
@dingmeng-xue on the azure portal, the azure cloud services page allows me to choose an arm storage account to deploy my cspkg and cscfg. So there is an api that allows someone to deploy to azure cloud services using arm storagea ccount. So, is it just the cmdlet that is not built to support this ?

**Comment by dingmeng-xue** [comment]
@arjgupta , could you post the snapshot that Azure CloudService allows ARM storage account? There are cloud services (classic) and cloud services (extended support) in Azure. which one are you using?
