### ISSUE TITLE
WebApp:Set-AzWebApp -AppSettings removes the existing settings without a warning

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#13684]
"-AppSettings
App Settings HashTable. Existing App Settings will be replaced, removing any settings that are not provided."

This is a terrible design. Existing settings should not be removed. Or, if they are, not without the -Confirm switch.
Similar command for Function Apps in Az.Functions and `az functionapp` only update the provided settings. Which is a user-friendly and expected behavior.

**Comment by dingmeng-xue** [comment]
WebApp team, please help to look into this question.

**Comment by panchagnula** [comment]
--appsettings  API will not append but replace the app settings with the new list, so its required currently to pass the full list of app settings.

**Comment by alexandair** [comment]
How does it append the app settings for a function app in Az.Functions and az functionapp?
It should never silently replace the settings.
