### ISSUE TITLE
Bug with Az.Automation 1.4.0

### ISSUE THREAD

**Issue by jessedavidsmit** [Azure/azure-powershell#13694]
**High Level Description**
I am using Azure PowerShell commands to automate the entire azure infrastructure. That also includes rebuilding Azure automation. In my scripts, I would like to retain the schedules that are assigned to a runbook because they can be customer-specific. Therefore, I loop through each runbook and schedules unlink them rebuild and register them again. This works perfectly using Az.Automation version 1.3.6. Since I upgraded to Az.Automation version 1.4.0 the Register-AzAutomationScheduledRunbook is completely broken. 

Issue: 
When using Az.Automation version 1.4.0 when I run the command **Register-AzAutomationScheduledRunbook** the parameters get updated with {"CliXml":"<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\">\r\n  <S>061421ea-eb9a-39ac-a0ef-d6f7ce044b49</S>\r\n</Objs>"}}. This was not like that in version 1.3.6. In that version the parameter would get updated and the value would be 061421ea-eb9a-39ac-a0ef-d6f7ce044b49.

Here is a demo script:
`#variables
 $Subscription = 'add your subscription guid'
 $AutomationAccountName = 'your automation account name'
 $ResourceGroupName = 'your resource group name'
 $RunbookName = 'your runbook name'
 $ScheduleName = 'your schedule name'

 #Authenticate
 $getContext = Get-AzContext 
 if(!$getContext) {
    Connect-AzAccount
    }
 else {
    Write-Verbose "Account already logged in." -Verbose
 }

 Set-AzContext -SubscriptionId $Subscription -Verbose | Out-Null

 #Find the schedule for runbook
 $existingSchedule = Get-AzAutomationScheduledRunbook `
                                -AutomationAccountName $AutomationAccountName `
                                -ResourceGroupName $ResourceGroupName `
                                -RunbookName $RunbookName | Where-Object {$_.ScheduleName -eq $ScheduleName}
        
 if (!$existingSchedule) { Write-Host "Could not find schedule."
    Break
  }
   $getScheduleWithParameters.Parameters
  #Get schedule using JobScheduleId to retrieve parameters
  $getScheduleWithParameters =  Get-AzAutomationScheduledRunbook `
                                       -JobScheduleId $existingSchedule.JobScheduleId `
                                       -AutomationAccountName $AutomationAccountName `
                                       -ResourceGroupName $ResourceGroupName -Verbose      
  

  #Unlink your schedule to perform update on parameters
  Unregister-AzAutomationScheduledRunbook `
            -AutomationAccountName $AutomationAccountName `
            -Name $RunbookName `
            -ResourceGroupName $ResourceGroupName `
            -ScheduleName $ScheduleName -Force -Verbose

  #Relink your schedule to update parameters
  Register-AzAutomationScheduledRunbook `
                -AutomationAccountName $AutomationAccountName `
                -Name $RunbookName `
                -ScheduleName $getScheduleWithParameters.ScheduleName `
                -ResourceGroupName $ResourceGroupName `
                -Parameters $getScheduleWithParameters.Parameters`
                -Verbose `

If you run this script using the **Az.Automation 1.4.0** you will see all your parameters get updated with **CliXml**. I don't know if this was intentionally designed this way. 

Result when using Az.Automation 1.3.6

![image](https://user-images.githubusercontent.com/26547060/101551194-f2795f80-39b0-11eb-9f12-890d55970039.png)

Result when using Az.Automation 1.4.0 

![image](https://user-images.githubusercontent.com/26547060/101551419-3e2c0900-39b1-11eb-865e-29ea715121d3.png)

Each time you run the  Register-AzAutomationScheduledRunbook using Az.Automation 1.4.0 it will append the new parameters, append append and append. Eventually the  Register-AzAutomationScheduledRunbook will fail with error:

![image](https://user-images.githubusercontent.com/26547060/101551733-d2966b80-39b1-11eb-922a-55db79ac9800.png)

I have also seen errors where the maximum length of the parameter has been reached. Is this a bug? can you suggest a workaround for this issue?

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We believe it is the similar issue with #13240 . The fix will be released at the end of this month.

**Comment by srrl** [comment]
@dingmeng-xue having similar issue with **Register-AzAutomationScheduledRunbook** in Az.Automation 1.4.2. 
Strings works fine but array values are still affected. 
![image](https://user-images.githubusercontent.com/16628480/105095274-55125f00-5b0a-11eb-8ca8-b067d7874afa.png)

**Comment by dingmeng-xue** [comment]
@srrl , thanks for reporting. Please create a new issue on Github and we will follow up. It's will be great that you can share brief steps to reproduce the issue.
