### ISSUE TITLE
Az.MySql 0.3.0 released about 18 hours ago has a missing component

### ISSUE THREAD

**Issue by jutlag** [Azure/azure-powershell#13697]
## Description

Started getting the error

...dules\Az.MySql\0.3.0\custom/../utils/Unprotect-SecureString.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

## Steps to reproduce

Can be reproduced running the command "New-AzMySqlServer"

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dcaro** [comment]
Thanks @jutlag we are looking at this and will work on updating the module asap.

**Comment by dingmeng-xue** [comment]
Close this issue because 0.3.1 was released on Dec 16.
