### ISSUE TITLE
AzureRm cmdlets should support wildcards where appropriate

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1369]
The `-Name` parameter for `Get-AzureRmRoleDefinition` should support wildcards, so that the user doesn't have to remember the exact name of each ARM RBAC Role.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by cormacpayne** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/issues/5447
