### ISSUE TITLE
Az.Frontdoor - Returned Object should contain ResourcegroupName

### ISSUE THREAD

**Issue by Paxilein** [Azure/azure-powershell#13692]
## Description of the new feature

The Object returned by Get-AzFrontdoor (Microsoft.Azure.Commands.FrontDoor.Models.PSFrontDoor) should contain the ResourcegroupName of the Frontdoor to not have to split the ResourceId to get the ResourcegroupName

**Comment by dingmeng-xue** [comment]
Network team, please look into this feature.

**Comment by Ptnan7** [comment]
This feature has been supported now, close this issue.
