### ISSUE TITLE
Using Managed Identity inside of a Remote (PS) Session

### ISSUE THREAD

**Issue by brwilkinson** [Azure/azure-powershell#13703]
I was thinking about the security implications of using Managed Identities inside of PowerShell remoting sessions.

E.g.

```powershell
# example 1.

Invoke-Command -ComputerName server123 -ScriptBlock {

    Login-AzAccount -Identity -AccountId $using:ClientId
    Get-AzKeyVault | Get-AzKeyVaultSecret | ForEach-Object {
        Get-AzKeyVaultSecret -VaultName $_.VaultName -Name $_.Name
    }
}

# example 2.

Invoke-Command -ComputerName server123 -ScriptBlock {

    Login-AzAccount -Identity -AccountId $using:ClientId
    Get-AzAccessToken
}
```

I obviously need either RBAC or Keyvault Policy to allow the listing of the Secrets and also Get secrets Etc., however I feel like just allowing and Identity to be used inside of a Remote session doesn't seem like the best default setting.

Managed Identity is supposed to be a Device/Hardware lock and this allows a single machine on the network to be used to grab a Token, then used on any other machine. like a proxy device.

Above is Powershell example, however obviously just using Invoke-RestMethod or Invoke-WebRequest can also work, however I figured I would begin a discussion here.

**Comment by dcaro** [comment]
@brwilkinson thanks for the comment and happy to discuss this further with you. 
In your scenario you would need to have assigned an identity to the VM and assign the proper permissions to this identity to be able to access secrets etc.  however, the concern that you expressing is valid beyond the context of managed identity.

Solutions like [continuous access evaluation](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-continuous-access-evaluation) help preventing getting tokens from one environment and using them somewhere else.

**Comment by brwilkinson** [comment]
@dcaro 

It's mostly about the ability to access the Azure Metadata service from Remote Machines.

I could be sitting on a laptop across my Corporate VPN, via Express Route and simply do an invoke command onto a Virtual Machine in Azure (perhaps a hybrid node via Arc) and act on behalf of the Managed Identity.

I know this is not specifically related to the AZ Cmdlets, however I just wanted to be sure people are comfortable with these scenarios.

It seems like a good attack vector. . . with limited controls. . . and now you are relying on Corporate Controls in a Active Directory Domain Environment with Kerberos Authentication as an entry point to connect where any Local Administrator gets access.

Even if a Managed Identity had 'Get' secrets, this seems like a good way to leak them. You may need the RGName, KVName and Secretname, however perhaps if you have Get/List you only need the first two and perhaps a large amount of Admins can get access to that information. . . Even if they don't have GET access permissions on the keyvault as an individual.

Although this is general conversation, not just about any particular resource type, since you could just as easily be getting data from a storage account Etc.

I was wondering if you could detect that the AZ cmdlets were being executed in a Remote session and block access to the metadata service to get the access token? This would be a breaking change.

Like I mentioned this may not be the best place to fix this issue, I mean within the AZ Module, because you can simply use invoke-webrequest/curl to achieve the same thing, however I think it's a conversation that is worth having, even if it's just to document the controls on how to lock this down. 

The issue is that unless this was handled by the metadata service to block the requests, then it must fall back to either the AZ Module OR PowerShell remoting security. The problem here is that most organizations don't have good controls here at a corporate level over PowerShell remoting over thousands of nodes. Applocker, whitelisting or JEA, may be what are required; however, I wouldn't put any money that most corporations implement these controls well.

**Comment by brwilkinson** [comment]
Just a little more info for future...

**It would be preferred if the Azure meta data service could be locked down.**
 
	- Similar as to how the windows update API is locked down to local only, the API is not accessible remotely.
 
Managed Identity is great. I just don’t believe making the meta data service accessible across the network is desirable.
 
In Enterprise, too many people are given Local Admin access and therefore inherit Access to Azure Resources… where there is no correlation between those roles.

![image](https://user-images.githubusercontent.com/3605266/102399788-efc0d080-3f95-11eb-95b8-3d1f5bbf7f5b.png)

1. Why do you need managed Identity?        

            - Access Azure services used for Automation or via Application code locked to only execute on known hardware

2. Does it need to have remote access to fulfill the need above?

            - No
3. Does remote access open up opportunity for exfiltration of data and undesired access?

             - Yes
4. Does it bypass the requirement for Certs/secrets/MFA/Conditional Access?

            - Yes
