### ISSUE TITLE
Typo in documentation for New-AzureRmRoleDefinition

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1370]
The `New-AzureRmRoleDefinition` role definition has incredibly good documentation (at least in the `.Description` field), however it references an invalid cmdlet name: `Get-AzureRmProviderOperations`. The command is not plural, and does not have an "s" at the end of it.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by maddieclayton** [comment]
Fixed.
