### ISSUE TITLE
Get-AzPolicyState does not collate paginated results.

### ISSUE THREAD

**Issue by hakashya** [Azure/azure-powershell#13711]
## Description of the new feature
(For Az.PolicyInsights)
The Get-AzPolicyState cmdlet returns only 1000 results even when there are more than 1000 results are present. 
![image](https://user-images.githubusercontent.com/58763328/101776342-ca0b7580-3b16-11eb-88c5-991747eff891.png)

A similar cmdlet (Get-AzPolicyMetadata) in the same module is able to fetch more than 1000 results.
![image](https://user-images.githubusercontent.com/58763328/101776471-fb844100-3b16-11eb-8a1c-79cb2065527c.png)

**Comment by kenieva** [comment]
Hi @hakashya, we are reviewing the PR. thanks.

**Comment by kenieva** [comment]
After some investigation, the PR does not encompass all that is require to allow for this change. There is a work item created for this. Thank you.

**Comment by jayendranarumugam** [comment]
Hi @kenieva , Do we have any other PR / Issue related to this ? Im facing a similar issue where my results are partially coming when debugging further the full results are struct at second page (after 1000 resources)
