### ISSUE TITLE
Connect-AzAccount does not list subscriptions available to account which do not have direct role assignment on subscription level

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-powershell#13724]
## Description
Connect-AzAccount does not list subscriptions available to account which do not have direct role assignment on subscription level

## Steps to reproduce

1. Create management group
2. Move subscription into management group
3. Give "Owner" access to any service principal or user which do not have already direct assignment on subscription on management group level
4. Use `Connect-AzAccount` to connect to tenant. No subsription will be populated even though user have owner permissions to Subscription (example below appid `eccf917e-14e5-4493-b2b7-808444e4e890`
```
PS C:\repo\DSO\DSO\DSO> Connect-AzAccount -ServicePrincipal -Credential $credentials -Tenant 65e4e06f-f263-4c1f-becb-90deb8c2d9ff

WARNING: The provided service principal secret will be included in the 'AzureRmContext.json' file found in the user profile ( C:\Users\artis\.Azure ). Please ensure that this directory has appropriate protections.

Account                              SubscriptionName TenantId                             Environment
-------                              ---------------- --------                             -----------
eccf917e-14e5-4493-b2b7-808444e4e890                  65e4e06f-f263-4c1f-becb-90deb8c2d9ff AzureCloud
```
![image](https://user-images.githubusercontent.com/13176884/101970451-0fe83c80-3bf0-11eb-8cd8-c54820beaf26.png)

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
PS C:\repo\DSO\DSO\DSO> get-installedmodule az*


Version              Name                                Repository           Description
-------              ----                                ----------           -----------
5.2.0                Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is compatible with WindowsPowerShell 
```

**Comment by dingmeng-xue** [comment]
@artisticcheese , our test environment cannot support me to reproduce your issue. Please share the debug message of `Connect-AzAccount`? You can turn on debug message via `$DebugPreference="Continue"`.

**Comment by artisticcheese** [comment]
This has been fixed about 3-4 hours after I posted this on Microsoft side looks like.

**Comment by dingmeng-xue** [comment]
Thanks for letting us know, @artisticcheese . Please contact us if you meet further issue.
