### ISSUE TITLE
Support subject name issuer based authentication

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#13725]
## Description of the new feature
This is improved approach to achieve easy certificate roll-over.

## Proposed implementation details (optional)
add WithSendX5C() to the "AcquireTokenByAuthorizationCode()" and AcquireTokenByRefreshToken() flows

https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.acquiretokenonbehalfofparameterbuilder.withsendx5c?view=azure-dotnet

**Comment by ikanni** [comment]
Nice to have the above feature!

**Comment by dingmeng-xue** [comment]
Please try `-SendCertificateChain` using the latest version of Az.Accounts
