### ISSUE TITLE
PSADCredential missing CustomKeyIdentifier field

### ISSUE THREAD

**Issue by netgh0st** [Azure/azure-powershell#13723]
## Description of the new feature

Output from the Graph call that retrieves AD credentials contains CustomKeyIdentifier (i.e. credential label/description to distinguish different credentials). This field is present in the output of AzureAD cmdlet `Get-AzureADApplicationPasswordCredential`, however, it's missing from the `Get-AzADAppCredential` cmdlet output.

## Proposed implementation details (optional)

Add `CustomKeyIdentifier` property to [PSADCredential](https://github.com/Azure/azure-powershell/blob/ff33d07e51b2017d038938b8412a89d4f0717f89/src/Resources/Resources/ActiveDirectory/Models/PSADCredential.cs) class, it should automatically pick up the JSON field from Graph request output.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Current AzAD related cmdlets are using microsoft.azure.graph.rbac 3.0 which doesn't contain CustomKeyIdentifier field. We will consider this requirement.

**Comment by jdiazmolina** [comment]
Hi @dingmeng-xue :) do you know by any chance if an ETA exists for this feature? :)

**Comment by tdgray** [comment]
I am also looking for this, as it is the only accurate way to differentiate between certificates that have been added to the application. It's frustrating seeing the data available in the HTTP responses when specifying -Debug but not being able to access it because of a missing property.

**Comment by dingmeng-xue** [comment]
We understand your suffering. But HTTP response deserialization is implemented in graph.rbac libraries. Azure PowerShell module cannot get this attribute based on current version.

**Comment by tdgray** [comment]
Understood. I've opted to do this as a workaround for now, in case it helps anyone else out.


```
function Get-AzADAppCredential {
    param (
        [Parameter(Mandatory = $true)]
        [string] $ObjectId
    )

    $accessToken = Get-AzAccessToken -ResourceTypeName AadGraph
    $headers = @{
        "Authorization" = "Bearer $($accessToken.Token)"
    }

    $keyCredentials = Invoke-RestMethod -Headers $headers -Uri "https://graph.windows.net/$($accessToken.TenantId)/applications/$($ObjectId)/keyCredentials?api-version=1.6"
    $passwordCredentials = Invoke-RestMethod -Headers $headers -Uri "https://graph.windows.net/$($accessToken.TenantId)/applications/$($ObjectId)/passwordCredentials?api-version=1.6"

    return $keyCredentials.value + $passwordCredentials.value
}
```

**Comment by jdiazmolina** [comment]
Hi! https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azadappcredential?view=azps-6.3.0 still says that the command does not retrieve the credential value but now it is returned :)
