### ISSUE TITLE
Showing all the subscriptions I manage by "Get-AzContext -ListAvailable" cmdlet

### ISSUE THREAD

**Issue by tanabe-keisuke-fixer** [Azure/azure-powershell#13720]
## Description of the new feature
I often write scripts using Azure PowerShell to streamline the operation of resources on Azure.
My execution environment is mainly Azure Cloud Shell.
I would like to run PowerShell and get a complete list of Azure subscriptions I manage.

When I thought about "Get-AzContext -ListAvailable",
this cmdlet seems to show only subscriptions that have once specified a context with "Select-AzSubscription -SubscriptionID xxx" in the execution environment.

Switching the context each time by "Select" seems to be a heavy load for script processing.
Isn't it possible to achieve the purpose just by "Get" instead of "Select" as an alternative?
For example, if I have to execute "Get-AzSubscription -SubscriptionID xxx", I think that it will proceed relatively efficiently.
If not, can you improve Azure PowerShell to do so?

**Comment by dingmeng-xue** [comment]
@tanabe-keisuke-fixer , thanks for reporting. `Get-AzSubscription` has different usage. We are on the way to resolve this inconvenience. The cmdlets in recently released module have an optional parameter `-SubscriptionId`.  

Welcome your feedback and suggestion.

**Comment by tanabe-keisuke-fixer** [comment]
@dingmeng-xue , thanks for reply.
I understand and appreciate that you are on the way to, also that Get-AzSubscription has different usage.
(it is maybe helpful to tell me how diffrent if the explanation won't get complicated).

regards,

**Comment by dingmeng-xue** [comment]
'Get-AzSubscription' is used for getting subscriptions that the current account can access. According to PowerShell convention, Get-* cmdlet should not change any resource including context in memory. So `Select-AzSubscription` should be more accurate for changing subscription.

**Comment by tanabe-keisuke-fixer** [comment]
I'm sorry this reply is late, but thank you for the description.
I understand Get-* cmdlet should be so.

Now we are looking forward to new release.
Please tell us how the usability of the cmdlet have improved when you have good prospect.

**Comment by dingmeng-xue** [comment]
Close this issue now. For support subscription id, we plan this work in 2021 and this change will happen module by module.

Please contact us for further question.
