### ISSUE TITLE
powershell -  WARNING: Unable to download the list of available providers. Check your internet connection.

### ISSUE THREAD

**Issue by dharanev** [Azure/azure-powershell#13773]
## Description
```
PS C:\windows\system32> Get-InstalledModule -Name Az -AllVersions | Select-Object -Property Name, Version
WARNING: MSG:UnableToDownload «https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409» «»
WARNING: Unable to download the list of available providers. Check your internet connection.

Name Version
---- -------
Az   4.3.0
Az   4.4.0
Az   4.8.0

```

**Comment by dingmeng-xue** [comment]
@dharanev , I believe you can see the similar error when querying other powershell module instead of Az.

Please raise your question to PowerShellGet https://github.com/PowerShell/PowerShellGet/issues

**Comment by dharanev** [comment]
thanks for follow up.
unable to access the powershell gallery and which inturns the message and working on it.

**Comment by 45duro** [comment]
the solution than I found is: 

run powershell x86 as administrator 

write the next comnand:

`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

**Comment by dingmeng-xue** [comment]
I'm closing this issue now. Please contact PowerShell Gallery when you cannot download module from there. 

Thanks for @45duro 's help.
