### ISSUE TITLE
AzureStorageContext module not found

### ISSUE THREAD

**Issue by dharanev** [Azure/azure-powershell#13801]
## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
@dharanev , no module is called AzureStorageContext. Which doc are you referencing?

**Comment by dharanev** [comment]
HI

Please close this case number.

regards

[cid:image003.jpg@01D6EA48.3F05ADD0]Venkat Dharaneeswaran
Database Administrator
110 William St, 9th Floor
New York, NY 10038
212.341 7021  (o)
vdharaneeswaran@nychdc.com|www.nychdc.com<http://www.nychdc.com/>

**Comment by dingmeng-xue** [comment]
Thanks for confirmation. Close it now.
