### ISSUE TITLE
Typo in Warning Message

### ISSUE THREAD

**Issue by flomader** [Azure/azure-powershell#13817]
## Description
There is a typo in the warning message when Get-AzRoleDefinition cannot find a role definition:

The message currently is:
No role definitions where found with those conditions.

It should be:
No role definitions were found with those conditions.

**Comment by dingmeng-xue** [comment]
Thanks for reporting.

https://github.com/Azure/azure-powershell/blob/fc936f34008816bafa79d88e78a7775b73633424/src/Resources/Resources/RoleDefinitions/GetAzureRoleDefinitionCommand.cs#L81
