### ISSUE TITLE
confirm Remove-AzVMWarePrivateCloud

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-powershell#13824]
Per internal [work item 9019400](https://msazure.visualstudio.com/One/_workitems/edit/9019400/), please add a configuration prompt for `Remove-AzVMWarePrivateCloud`.  The cmdlet in [Az.VMWare/0.1.0](https://www.powershellgallery.com/packages/Az.VMWare/0.1.0) does not prompt. If there is room for a warning, the warning should match the Portal UI with:

> Deleting the private cloud is an irreversible operation. Once the private cloud is deleted, the data cannot be recovered, as it terminates all running workloads and components and destroys all private cloud data and configuration settings, including public IP addresses.

P.S. It would also be good to spell it as `VMware` instead of `VMWare` where possible in this module.

**Comment by dingmeng-xue** [comment]
@VeryEarly , please look into it. I can reproduce it.

```
PS C:\> $ConfirmPreference
High
PS C:\> Remove-AzVMWarePrivateCloud -name test -ResourceGroupName dixue
PS C:\>
```

**Comment by ctaggart** [comment]
Hi @VeryEarly, this is a customer request. Is there an ETA that we can report back to the customer?

**Comment by VeryEarly** [comment]
> Hi @VeryEarly, this is a customer request. Is there an ETA that we can report back to the customer?

Hi @ctaggart ,

I'll work on this item and it will be targeted at [2021-02-09](https://github.com/Azure/azure-powershell/milestone/117) release.
