### ISSUE TITLE
[Invoke-AzVMRunCommand] Support use of newer features already supported by the RunCommand API

### ISSUE THREAD

**Issue by craiglandis** [Azure/azure-powershell#13828]
## Description of the new feature

For the Invoke-AzVMRunCommand cmdlet, please add params for these properties the API itself supports - asyncExecution, errorBlobUri, outputBlobUri, protectedParameters, runAsPassword, runAsUser, timeoutInSeconds, and tags.

Also, add support for taking a scriptUri as input, not just a local path to a script like it does currently. The RunCommand API itself already supports both script (script contents) and scriptUri (URL to a script), but right now Invoke-AzVMRunCommand only supports a local path to a script for -scriptPath. 

https://docs.microsoft.com/en-us/rest/api/compute/virtualmachineruncommands/createorupdate#request-body

**Comment by amjads1** [comment]
Assigning to Akshay to look into this issue.

**Comment by axayjo** [comment]
Hi @craiglandis, the newer features highlighted in this issue are part of the new Run Command that's in the works. We'll be updating the cmdlets with the new features closer to the launch.
