### ISSUE TITLE
the proximity placement group chosen for the availability set and for the virtual machine to be spun up inside it during failover needs to be the same

### ISSUE THREAD

**Issue by manikantaado** [Azure/azure-powershell#13836]
Hi Team,

In my scenario, i am doing the DR from Vmware to Azure for Linux Servers in our environment.

when i am doing the same with PowerShell, i am getting error as mentioned in the title.

"the proximity placement group chosen for the availability set and for the virtual machine to be spun up inside it during failover needs to be the same"

where as i have provided the availability set and associated ppg value are of same resource related and no where i have mentioned any other PPG during test failover.

any suggestions on this please??

**Comment by manikantaado** [comment]
Additional information is:

1) when I am  passing both the parameters (RecoveryAvailabilitySet) and (RecoveryProximityPlacementGroupId) to Set-AzRecoveryServicesAsrReplicationProtectedItem cmdlet i am getting the above error.

2) when I am passing only one parameter (RecoveryAvailabilitySet) to Set-AzRecoveryServicesAsrReplicationProtectedItem cmdlet I am getting the above error only means issue is getting created with availability set parameter.

3) when I am not passing availability set parameter to Set-AzRecoveryServicesAsrReplicationProtectedItem cmdlet, it is working as expected.

4) as mentioned in the document if i try to pass the name of availability set, it's failing because the "name of the availability set is not a valid resource id"


Let me know if any other information is required.

**Comment by Sharmistha-Rai** [comment]
@manikantaado - if I understand it correctly - you're trying to enable replication and your target is in an availability set inside a PPG?

**Comment by manikantaado** [comment]
@Sharmistha-Rai, yes, i am trying to create a VM as part of test failover after replication of the same is completed and i want that VM to be part of an availability set when it is getting executed as part of test failover step.

let me know if any more details are required...we can connect in a meeting and i can share you the more info about this.

**Comment by Sharmistha-Rai** [comment]
@manikantaado - it will be best if you [raise a support ticket](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview). The support team will be able to assist you on this.

**Comment by Sharmistha-Rai** [comment]
@manikantaado - did you raise a support ticket for this issue? Please let me know if you still need help with this query.

**Comment by Sharmistha-Rai** [comment]
@manikantaado - closing this thread for now. Please feel free to reopen the query if you are still facing this issue.
