### ISSUE TITLE
Support storage lifecycle policy rule for versions

### ISSUE THREAD

**Issue by TrymBeast** [Azure/azure-powershell#13852]
## Description of the new feature

As per documentation the Add-AzStorageAccountManagementPolicyAction cmdlet does not seems to support to create a policy action for versions, only for baseblobs and snapshots.

I would like to do something like:
```
Add-AzStorageAccountManagementPolicyAction -VersionAction Delete -daysAfterCreationGreaterThan 100
```

**Comment by blueww** [comment]
@TrymBeast 

Thanks for raising the issue!
PowerShell depends on .net SDK, and .net SDK depends on swagger.
We will work on that after the storage swagger is updated to support blob version of Management Policy.

**Comment by blueww** [comment]
We have already add the support with PR https://github.com/Azure/azure-powershell/pull/14247
The change will be in the next PowerShell release.

**Comment by blueww** [comment]
Azure PSH 5.6.0 is released with the change. (Az.Storage 3.4.0)
