### ISSUE TITLE
Get-AzureVM fails with Unable to find type [Microsoft.Azure.Common.Authentication.Models.AzureProfile]

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-powershell#1385]
Get-AzureVM fails with Unable to find type [Microsoft.Azure.Common.Authentication.Models.AzureProfile] even on simple call

Get-AzureVM like this:

PS C:\Windows\system32> Get-AzureVM
Get-AzureVM : Unable to find type [Microsoft.Azure.Common.Authentication.Models.AzureProfile].
At line:1 char:1
+ Get-AzureVM
+ ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Azure...ls.AzureProfile:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

**Comment by eosfor** [comment]
This was due to i was using proxy function for it and parameter type for $profile parameter has changed

**Comment by lukeb1961** [comment]
How does one fix this?
10586.17.amd64fre.th2_release.151121-2308


Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> find-module azurerm

NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet provider must be available in 'C:\Program
Files\PackageManagement\ProviderAssemblies' or 'C:\Users\Luke\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by running 'Install-PackageProvider -Name
NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install and import the NuGet provider now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y
PackageManagement\Install-PackageProvider : The term 'PackageManagement\Install-PackageProvider' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:5921 char:21
+             $null = PackageManagement\Install-PackageProvider -Name $ ...
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PackageManageme...PackageProvider:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PackageManagement\Import-PackageProvider : The term 'PackageManagement\Import-PackageProvider' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:5927 char:21
+             $null = PackageManagement\Import-PackageProvider -Name $s ...
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PackageManagement\Import-PackageProvider:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

WARNING: Unable to find package provider 'PowerShellGet'.
PackageManagement\Find-Package : Unable to find module providers (PowerShellGet).
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:996 char:3
+         PackageManagement\Find-Package @PSBoundParameters | Microsoft ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
    + FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage

PS C:\WINDOWS\system32>

**Comment by himannetwork** [comment]
https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-install-or-uninstall/get-vm-not-recognized-during-install-cloud-connector
