### ISSUE TITLE
Get-AzureRmNetworkSecurityGroup ErrorAction is being ignored

### ISSUE THREAD

**Issue by RyanBoud** [Azure/azure-powershell#1386]
When running Get-AzureRmNetworkSecurityGroup and using the -ErrorAction parameter it is being ignored. 

For example if I run:

Get-AzureRmNetworkSecurityGroup -Name "TEST" -ResourceGroupName TESTRG -ErrorAction SilentlyContinue

It will return an error, I want it to return nothing.

It is possible to use:
Get-AzureRmNetworkSecurityGroup -ResourceGroupName TESTRG | Where-Object -Property Name -EQ -Value "TEST"

However that returns all groups and then filters.

**Comment by cormacpayne** [comment]
Closing as this appears to have been resolved.
