### ISSUE TITLE
Fix Properties of Get-AzAutoscaleSetting

### ISSUE THREAD

**Issue by Paxilein** [Azure/azure-powershell#13861]
## Description of the new feature

The commandlet Add-AzAutoScaleSetting fails when piping the results of Get-AzAutoscaleSetting to it with missing parameters "ResourceGroupName TargetResourceId". This is no difference between with -detailedoutput or without.

## Proposed implementation details (optional)

The Property for "TargetResourceId" in the objects "PSAutoscaleSetting" and "PSAutoscaleSettingNoDetails" returned by Get-AzAutoscaleSetting are named "TargetResourceUri". This should probably be renamed to "TargetResourceId"?
Also, the objects might need the ResourceGroupName-Property to make this a seamless experience?

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will look into it.
