### ISSUE TITLE
Introduce new preference variable '$ForcePreference' similar to '$ConfirmPreference'

### ISSUE THREAD

**Issue by fawohlsc** [Azure/azure-powershell#13878]
## Description of the new feature
In a nutshell, there is no way to generally `-Force` all cmdlets to suppress prompts.

![image](https://user-images.githubusercontent.com/41372128/103656943-8404ce80-4f69-11eb-8782-f24042827c87.png)

This requires to add `-Force` to every cmdlet:
```powershell
My-CmdletWithConfirmation –Force
```

While for `-Confirm` someone could set the `$ConfirmPreference`, there is no such variable for `-Force`. See also
[use -confirm instead of "-force"](https://github.com/Azure/azure-powershell/issues/475) and [ConfirmationUpdate](https://gist.github.com/markcowl/338e16fe5c8bbf195aff9f8af0db585d) for implementation details around `-Confirm`  and `-Force`.

## Proposed implementation details (optional)
Introduce a preference variable `$ForcePreference` similar to [$ConfirmPreference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.1).

**Comment by dingmeng-xue** [comment]
Thanks. Please log an request to https://github.com/PowerShell/PowerShell/issues because it is PowerShell general feature.

**Comment by fawohlsc** [comment]
Thanks @dingmeng-xue . I opened a general feature request for PowerShell as advised by you. Closing this issue.
