### ISSUE TITLE
Hitting Azure Powershell log in issue

### ISSUE THREAD

**Issue by LiYMS** [Azure/azure-powershell#13880]
## Description
Everything was working fine for me before the holiday. When I tried to log in from my Azure Powershell using either Connect-AzAccount or Login-AzAccount today, it prompts me to do Phone Auth. After I did my phone auth properly from my phone, I got the message which shows the sign in succeeded and I was promoted to close the browser. However, Azure Powershell always throw out the following message: Response status code does not indicate success: 401 (Unauthorized). I have tried different computers and rebooted my computers multiple times, the problem remains. Many of my team members see the same issue and other teams as well.

I searched internally and this looks like same issue being popped up frequently: Please refer to the following discussions for people who reported similar issue last year.
https://stackoverflow.microsoft.com/questions/172586

https://github.com/Azure/azure-powershell/issues/9427

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
@LiYMS , could you check the version of Az.Accounts? You can get it via below code after you execute Login even it is failed
```
Get-Module -Name Az.Accounts
```

In addition, please provide debug log for login execution. You can turn on it via `$DebugPreference="Continue"`.

**Comment by LiYMS** [comment]
Hi,

I upgraded to Az.Accounts 2.2.3 and the issue is now solved.

Thanks,
Liang

**Comment by dingmeng-xue** [comment]
It's great. I close this issue now and please contact us if you have further question.
