### ISSUE TITLE
Import-AzKeyVaultCertificate : re-import a new certificate

### ISSUE THREAD

**Issue by Xat59** [Azure/azure-powershell#13897]
## Description
I have an Azure Runbook that runs regularly a PowerShell script to renew SSL certificate via Let's Encrypt.

In the script I use the Az.KeyVault module (version 3.3.0) with Import-AzKeyVaultCertificate cmdlet.

I am able to import the certificate successfully. But when I try to re-import a new version of this cert using the same name, I get a "Conflict" error.
If I remove, then purge the certificate in the keyvault, I am able to re-import it **if I wait some minutes after the purge.**

What is the best way to import a new version of a certificate ? 

I don't want to re-import the certificate with a different name, because an Application Gateway has a reference to this keyvault certificate.

I've actually checked for similar issue, but I am not able to find a good way to do.

Thanks

**Comment by dingmeng-xue** [comment]
@isra-fel , please verify it and contact service team if there is no available API.

**Comment by isra-fel** [comment]
Hi @Xat59 , `Import-AzKeyVaultCertificate` is designed to add a new **version** when you import a certificate by an exsiting name.

Could you share how you reproduce this issue? Here's a template to fill in:

```markdown
## Steps to reproduce


## Environment data

<!-- Please run $PSVersionTable and paste the output in the below code block
     If running the Docker container image, indicate the tag of the image used and the version of Docker engine-->


## Module versions

<!-- Please run (Get-Module  -ListAvailable) and paste the output in the below code block -->


## Debug output

<!-- Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block
     ATTENTION: Be sure to remove any sensitive information that may be in the logs -->


## Error output

<!-- Please run Resolve-AzError and paste the output in the below code block
     ATTENTION: Be sure to remove any sensitive information that may be in the logs -->

```

**Comment by Xat59** [comment]
Hey guys,

I am not able to reproduce anymore. The `Import-AzKeyVaultCertificate` works well. When a version already exist, it creates a new version of the certificate that is finally available.

Sorry for this issue, and thanks a lot for your time.
Regards.
