### ISSUE TITLE
Assign the volume to a snapshot policy when using New-AzNetAppFilesVolume to create ANF volume

### ISSUE THREAD

**Issue by foe70** [Azure/azure-powershell#13930]
## Description of the new feature
In portal, when we create a Azure Netapp Files volume, you can also assign it to an existing snapshot policy.
But when using powershell Az.NetAppFiles, there is no such option to assign a volume to a snapshot policy.
https://docs.microsoft.com/en-us/powershell/module/az.netappfiles/new-aznetappfilesvolume?view=azps-5.3.0

**Comment by dingmeng-xue** [comment]
We will forward it to service team.

**Comment by dingmeng-xue** [comment]
@audunn , could you help to check this question?

**Comment by audunn** [comment]
We are looking into adding this in the next update for NetAppFiles Powershell module

**Comment by audunn** [comment]
Closing as this issue has been resolved
