### ISSUE TITLE
New-AzureRmResourceGroupDeployment : There were not enough free threads in the ThreadPool to complete the operation.

### ISSUE THREAD

**Issue by brisebois** [Azure/azure-powershell#1394]
Got this issue many times while deploying this template https://github.com/brisebois/multi-geo-arm-experiment/blob/master/OnAndOff/Templates/azuredeploy-multi-geo.json 

New-AzureRmResourceGroupDeployment : There were not enough free threads in the ThreadPool to complete the operation.
At line:4 char:1
- New-AzureRmResourceGroupDeployment -ResourceGroupName 'geoexperiment' ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], InvalidOperationException
  - FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

It seems to be a client-side issue because my deployments kept going even after the PowerShell console was stopped by this error message.

**Comment by wahidsaleemi** [comment]
I got this on a custom template where I'm deploying a few VMs and using DSC extension.

**Comment by Vijayaraghavanl** [comment]
Is there any progress on this issue? I have also started experiencing this issue since upgrade to v1.1.0

**Comment by unisol14** [comment]
Yes, I have the same problem. My template has the DSC extension with an LCM configuration for the Azure pull server.

**Comment by ravbhatnagar** [comment]
@vivsriaus - Please investigate.

**Comment by ravbhatnagar** [comment]
@TianoMS lets see if we can get a repro on this.

**Comment by ravbhatnagar** [comment]
@wahidsaleemi @Vijayaraghavanl @unisol14 - Can you please share the template? It will help us investigate this issue? Feel free to omit any sensitive information.

**Comment by ravbhatnagar** [comment]
Closing this due to lack of repro. @wahidsaleemi @Vijayaraghavanl @unisol14 - We have fixed a bunch of related issues recently. If you run into this again using the latest version of Azure PowerShell, please open this issue again.

**Comment by bbollard** [comment]
What version of Azure PowerShell are you referring to? I just received the same issue while deploying a custom template. This is an intermittent issue.

New-AzureRmResourceGroupDeployment : There were not enough free threads in the ThreadPool to complete the operation.
At line:1 char:1
+ new-AzureRmResourceGroupDeployment -ResourceGroupName rg-vm-svrtestXXX...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroupDeployment], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

**Comment by ravbhatnagar** [comment]
@bbollard - Is it possible for you share the template? Feel free to strip out sensitive information. I was referring to the 1.5.0 module of Azure PowerShell. 

Reopening since we might get a repro.

**Comment by bbollard** [comment]
@ravbhatnagar here it is.

[NotEnoughThreadsInThreadPoolTemplate.zip](https://github.com/Azure/azure-powershell/files/302452/NotEnoughThreadsInThreadPoolTemplate.zip)

**Comment by markcowl** [comment]
@ravbhatnagar Please close if this is fixed, or assign to the appropriate milestone, if not.

**Comment by cormacpayne** [comment]
@ravbhatnagar can you take a look?

**Comment by markcowl** [comment]
Closing since there has been no update since 2016.  If this is still a problem, please file a new issue.
