### ISSUE TITLE
Behaviour of Az.Accounts module version loading between PowerShell versions

### ISSUE THREAD

**Issue by JasperCottenie** [Azure/azure-powershell#13949]
## Description
During development of a script that can handle function execution in Azure Container Instances I've noticed the same error popping up when loading different versions of Az.Accounts: Assembly with same name is already loaded.
I found this topic addressed at: https://github.com/Azure/azure-powershell/blob/master/documentation/troubleshoot-module-load.md#why-are-incompatibilities-possible

So I understand that the assemblies loaded by the first version can't be unloaded. To handle this the Az PowerShell team made all Az.Account versions backwards compatible so only one version needs to be loaded. For my specific development goal it is unfortunately very hard to cater to this. So to further understand this I made a small script below that reproduces the situation. But to my surprise this script behaves differently between PS 5.1 and PS 7.0.3/7.1. On PS5.1 this script does function well for me and every version can independently load and fetch context information.

Is this behaviour known and expected? If so, do I have to conclude that there's no way to achieve the functionality like PS 5.1 on PS 7+ ?

I also tried to load in the next version of Az.Accounts in different runspaces within the same session but then I get into typedata errors so I returned to focus on the original one session issue.

## Steps to reproduce

Install the the Az.Accounts versions that the script references on your machine or a container and execute the code below on both PS7.1, PS7.0.3 and PS5.1.

My results are that only the initial version can be loaded on the PS 7+ versions while all modules can be loaded on PS5.1

```powershell
$InitialVersion = '2.2.3'
Write-Verbose "Loading initial version [$InitialVersion].." -Verbose
Import-Module 'Az.Accounts' -RequiredVersion $InitialVersion
Write-Verbose "Removing the initial version from session loaded modules.." -Verbose
Remove-Module 'Az.Accounts'
$AzAccountsVersionList = @('1.9.2','1.9.5','2.1.2','2.2.2','2.2.3')
foreach ($version in $AzAccountsVersionList){
  try{
    Write-Verbose "Loading version [$version].." -Verbose
    Import-Module 'Az.Accounts' -RequiredVersion $version -ErrorAction 'Stop'
    Write-Verbose " > Loading version [$version] was successfull." -Verbose
    Remove-Module 'Az.Accounts'
  }
    catch{
        Write-Error "Loading version [$version] failed with error: $_" -ErrorAction Continue
    }
}
```

## Environment data

     
```
Local PS7.1:
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Local PS5.1:
Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Docker image for 7.0.3:
mcr.microsoft.com/powershell:lts-alpine-3.10
```

## Module versions

```powershell
    Directory: C:\Users\JasperCottenie\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.2.3                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     2.2.2                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     2.2.1                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     2.1.2                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.9.5                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.9.4                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.9.2                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.7.2                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.7.0                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.6.2                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
```

## Debug output

PS 7.1
```
VERBOSE: Loading initial version [2.2.3]..
VERBOSE: Removing the initial version from session loaded modules..
VERBOSE: Loading version [1.9.2]..
Write-Error: Loading version [1.9.2] failed with error: Assembly with same name is already loaded
VERBOSE: Loading version [1.9.5]..
Write-Error: Loading version [1.9.5] failed with error: Assembly with same name is already loaded
VERBOSE: Loading version [2.1.2]..
Write-Error: Loading version [2.1.2] failed with error: Assembly with same name is already loaded
VERBOSE: Loading version [2.2.2]..
Write-Error: Loading version [2.2.2] failed with error: Assembly with same name is already loaded
VERBOSE: Loading version [2.2.3]..
VERBOSE:  > Loading version [2.2.3] was successfull.
```

PS 5.1
```
VERBOSE: Loading initial version [2.2.3]..
VERBOSE: Removing the initial version from session loaded modules..
VERBOSE: Loading version [1.9.2]..
VERBOSE:  > Loading version [1.9.2] was successfull.
VERBOSE: Loading version [1.9.5]..
VERBOSE:  > Loading version [1.9.5] was successfull.
VERBOSE: Loading version [2.1.2]..
VERBOSE:  > Loading version [2.1.2] was successfull.
VERBOSE: Loading version [2.2.2]..
VERBOSE:  > Loading version [2.2.2] was successfull.
VERBOSE: Loading version [2.2.3]..
VERBOSE:  > Loading version [2.2.3] was successfull.
```

## Error output

(This is for every version that failed loading)

```
Message        : Assembly with same name is already loaded
StackTrace     :    at System.Management.Automation.Runspaces.InitialSessionState.Bind_LoadAssemblies(ExecutionContext context)
                    at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local, Boolean setLocation)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData,
                 ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options,
                 Boolean& containedErrors)
Exception      : System.IO.FileLoadException
InvocationInfo : {Import-Module}
Line           :     Import-Module 'Az.Accounts' -RequiredVersion $version -ErrorAction 'Stop'

Position       : At line:10 char:5
                 +     Import-Module 'Az.Accounts' -RequiredVersion $version -ErrorActio …
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1
```

**Comment by dingmeng-xue** [comment]
@JasperCottenie , assembly loading behavior is different between DOTNET Core and Dotnet framework. So, you can see the different result on PowerShell 7 and PowerShell 5. 

Do you have the requirement of using PowerShell 5 and 7 both? If you find something cannot work due to assembly loading, please let us know.

**Comment by JasperCottenie** [comment]
Thanks for your quick reply. I'll share a bit more on my development goal and where above problem originates for us.
I want create a function execution system like recently was introduced with deployment scripts in ARM templates. Meaning function execution that spins up a container instance to execute said request. Previously we used PS5.1 on Azure Automation but it's time to step that up towards containers and PS7.

Desired flow is:

1. Function app API that exposes endpoints for creating job requests. Asks function name, module name and module version among parameters
2. Function app spins up container instance to execute the request if validated
3. A script within the container loads up Az module versions, looks up environment secrets in the tenant of the engine and some other things
4. The script authenticates towards the target tenant
5. The script loads in the requested module and executes the request

It's number 5 that's proving to be a problem. We wanted to design the system in a way that the requested module can always execute in a fresh environment no matter what dependencies are in there.  So the problem now is that if the requested module uses an Az.Accounts version that is not the same as the orchestrator, the flow will fail as the assemblies from the orchestrator part of the script are still loaded.

**Comment by erich-wang** [comment]
@JasperCottenie, thanks for providing the detail information, unfortunately it is limitation of PowerShell 7. Is it possible to run step 5 using Start-Job or another PowerShell process?

**Comment by JasperCottenie** [comment]
I'll update the example that I provided with a job/runspace implementation. Like I said I tested this before briefly but encountered type data issues. But perhaps that was due to another issue. I'll investigate and post the results below.

**Comment by dingmeng-xue** [comment]
Thanks @JasperCottenie . We will wait your further update.

**Comment by JasperCottenie** [comment]
Hi, Excuse me for the delay behind my further investigation. 
I attempted two use cases: one with creating my own runspace and one with using the job cmdlets. Here are the results:

### Approach with creation of my own runspace for every import.
Result: Does not work, assembly loading problems that are equal to the initial attempted use case of just importing the modules in the same session with removes in between. Works in PS 5.1, but not PS 7.#

```powershell
$InitialVersion = '2.2.3'
Write-Verbose "Loading initial version [$InitialVersion].." -Verbose
Import-Module 'Az.Accounts' -RequiredVersion $InitialVersion
Write-Verbose "Removing the initial version from session loaded modules.." -Verbose
Remove-Module 'Az.Accounts'
$AzAccountsVersionList = @('1.9.2', '1.9.5', '2.1.2', '2.2.2','2.2.3')
foreach ($version in $AzAccountsVersionList) {
    $Runspace = [RunspaceFactory]::CreateRunspace()
    $Runspace.ApartmentState = 'STA'
    $Runspace.Open()
    $Runspace.SessionStateProxy.SetVariable('Version', $version)
    $ScriptBlock = {
        try {
            Write-Verbose "Loading version [$Version].." -Verbose
            Import-Module 'Az.Accounts' -RequiredVersion $Version -ErrorAction 'Stop'
            Write-Verbose " > Loading version [$Version] was successfull." -Verbose
            Remove-Module 'Az.Accounts'
        }
        catch {
            Write-Error "Loading version [$Version] failed with error: $_" -ErrorAction Continue
        }
    }
    $PSInstance = [PowerShell]::Create()
    $null = $PSInstance.AddScript($ScriptBlock)
    $PSInstance.Runspace = $Runspace
    try {
        $PSInstance.Invoke()
    }
    finally {
        foreach ($errorStatement in $PSInstance.Streams.Error) {
            Write-Error "[RUNSPACE] $errorStatement" -ErrorAction Continue
        }
        foreach ($verboseStatement in $PSInstance.Streams.Verbose) {
            Write-Verbose "[RUNSPACE] $verboseStatement" -Verbose
        }
    }
    $Runspace.Close()
    $Runspace.Dispose()
}
```

### Approach with using the Job cmdlets
Result: Works great! For both PS 5.1 and 7.# . Very happy to see that this does not suffer from the same issues as the methods before and every instance has the ability to load any Az.Accounts version that it wants. This looks perfect for our use case. 
As I said before I tried the runspace method before but not this one. In the past I encountered some issues, that I can't even remember anymore, with the job cmdlets and used the runspaces approach since then. Good reminder for me to not let past experiences affect my new systems.

```powershell
$InitialVersion = '2.2.3'
Write-Verbose "Loading initial version [$InitialVersion].." -Verbose
Import-Module 'Az.Accounts' -RequiredVersion $InitialVersion
Write-Verbose "Removing the initial version from session loaded modules.." -Verbose
Remove-Module 'Az.Accounts'
$AzAccountsVersionList = @('1.9.2', '1.9.5', '2.1.2', '2.2.2', '2.2.3')
foreach ($version in $AzAccountsVersionList) {
    Start-Job -Name "AzTest-$version" -ScriptBlock {
        try {
            Write-Verbose "Loading version [$using:version].." -Verbose
            Import-Module 'Az.Accounts' -RequiredVersion $using:version -ErrorAction 'Stop'
            Write-Verbose " > Loading version [$using:version] was successfull." -Verbose
            Remove-Module 'Az.Accounts'
        }
        catch {
            Write-Error "Loading version [$using:version] failed with error: $_" -ErrorAction Continue
        }
    } | Receive-Job -Wait
}
```

I do however have a final question and that's that I don't specifically know _why_ this works. Perhaps this is more specific PowerShell territory, but do you know what the technical explanation is behind the different results of these two use cases?

**Comment by dingmeng-xue** [comment]
@JasperCottenie , sorry for the late response. `Remove-Module` removes the members of a module, such as cmdlets and functions, from the current session.. If the module includes an assembly (.dll), all members that are implemented by the assembly are removed, but the assembly is not unloaded. https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/remove-module?view=powershell-7.1#description

In Windows PowerShell on dot framework, it allows multiple versions of assembly work side-by-side. But PowerShell Core or 7 on dotnet core cannot have that capability.

`Start-Job` actually starts a new process of PowerShell. All required assemblies need to be loaded again. So, there is only one Az.Accounts instance in the separate PowerShell process initiated by `Start-Job`

**Comment by JasperCottenie** [comment]
Ok, thanks for that explanation and follow-up. We've used the Start-Job implementation for a while now and it works great!
