### ISSUE TITLE
Inconsistent use of Get-AzureRm<item> across providers

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#1396]
Providers implement basic "getter" functions differently. For instance, `Get-AzureRmDnsZone` requires the "ResourceGroup" parameter, while other cmdlets such as `Get-AzureRmVm` and `Get-AzureRmWebApp` do not. This makes it hard to use the cmdlets, since their usage "pattern" vary across the various providers.

**Comment by jtuliani** [comment]
Thanks for flagging.

To clarify: you're suggesting that Get-AzureRmDnsZone should make the -ResourceGroupName parameter optional, and if omitted we would enumerate zones across resource groups.  No change to e.g. New-AzureRmDnsZone or Remove-AzureRmDnsZone, or to record set cmdlets.

Correct?

**Comment by trondhindenes** [comment]
Yep. There needs to be consistency across the various AzureRM-modules in how they implement cmdlets and the params required. This is not the case today.

**Comment by jtuliani** [comment]
Closing.  Issue is fixed in private branch, will be included in next PS release.
