### ISSUE TITLE
Feature Request: Azure AD App Role and Directory Role Assignment Cmdlets

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#13979]
## Description of the new feature
Currently Az.Resources includes cmdlet to assign roles in azure, `Set-AzRoleAssignment`. However, there are many use cases where we also need to assign directory and app roles to service principals, the most common use case being Azure Functions/App Service/etc. MSI.

Currently the only way to do it in a powershell context is with the AzureAD module which currently is only supported with Windows Powershell, however this functionality could be added with minimal fuss to the Az.Resources module.

## Proposed implementation details (optional)
I'm willing to PR the new Cmdlets as implementations of `ActiveDirectoryBaseCmdlet` following the same logic as the existing ones if there is willingness from the team to merge them if they meet standards.

**Comment by dcaro** [comment]
@JustinGrote thanks  for offering to contribute to Azure PowerShell. We definitely welcome your contribution and will be accompanying you through the process.
First we will go through a cmdlet design review (we do this with our internal partners as well). 
If you have already started to work on the code, you can submit the PR and we'll review it in the PR. 
If you have not already started your code, can you fill the following form the best you can.

If you need help at any point, please let us know. 

## High Level Scenarios

- Describe how your feature is intended to be used by customers.
- `{ DESCRIPTION OF FEATURE HERE } `

## Syntax changes

### New Cmdlet

Sample syntax:

```powershell
Get-AzRmWidget [[-ResourceGroupName] <resourceGroupName>] [[-Name] <name>] [-Detail]
 
ResourceGroup | WidgetName |
--------------|------------|
 rg1          |  widget1   |

```

### Changed cmdlet

Sample syntax, please specify which parameter sets are being modified.

`{ NEW OR CHANGED CMDLETS HERE }`

Indicate which parameter sets on the cmdlet are affected by this change.

    - { INPUT HERE }
    
For new parameters, indicate their types and possible different values.

    - { INPUT HERE }

**Comment by JustinGrote** [comment]
I am closing this issue in favor of a "workaround"

1. Use the msgraph powershell module by single-signing-on to it using the Az context:
```powershell
connect-graph -accesstoken (Get-AzAccessToken -ResourceUrl 'graph.microsoft.com').token
```
2. Do the work I wanted to do in MSGraph module, with some helper functions to make the process less obtuse
