### ISSUE TITLE
Get-AzLog to query logs older than 90 days

### ISSUE THREAD

**Issue by Ayanmullick** [Azure/azure-powershell#13982]
## Description of the new feature
As an Azure administrator one needs to create RBAC-enabled reports to identify environment-wide infrastructure governance deviations that are based on Azure activity logs. One needs to query multiple subscriptions in parallel to generate a live  report. However, the bug below doesn’t let one query multiple subscriptions' activity logs in parallel. 

https://github.com/Azure/azure-powershell/issues/10349#issuecomment-767241850

Currently, one can query Activity logs older than 90 days and across multiple subscriptions , in parallel, thru Kusto but [not using PowerShell](https://github.com/MicrosoftDocs/azure-docs/issues/54510). It would be convenient if one could point `Get-Azlog` to a storage account or a log analytics workspace to query logs older than [90 days](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/activity-log) to build such reports.

**Comment by dingmeng-xue** [comment]
@VeryEarly , please check if it is supported.

**Comment by VeryEarly** [comment]
I do not see such API exposed anywhere:
https://docs.microsoft.com/en-us/rest/api/monitor/activity-logs/list

Might be valid request for service team, Azure-PowerShell is not able to get these logs for now.

**Comment by Ayanmullick** [comment]
@dcaro , @mikefrobbins ,  which team should one approach now?

**Comment by dcaro** [comment]
@Ayanmullick after confirming, the data returned by the API do not exceed 90 days. 
Data past 90 days is stored in customer's resources (like storage account, eventhub, log analytics ...) that you cannot query with Get-AzLog,

**Comment by Ayanmullick** [comment]
@dcaro, The purpose of Get-AzLog is to [`retrieve Activity Log events.`](https://docs.microsoft.com/en-us/powershell/module/az.monitor/get-azlog?view=azps-3.8.0#description)


I'm seeking a workaround to the 90-day limitation so one could access older activities using PowerShell. For Eg. one is unable to get the VM creation details beyond 90 days to build a subscription-level VM deletion report. PFB the script

[Get-AzVMDeletionActivity](https://www.powershellgallery.com/packages/Get-AzVMDeletionActivity/0.4/Content/Get-AzVMDeletionActivity.ps1)

**Comment by dcaro** [comment]
@Ayanmullick for logs beyond 90 days, you'll have to query the storage where the data are being been sent to.

**Comment by Ayanmullick** [comment]
> @Ayanmullick for logs beyond 90 days, you'll have to query the storage where the data are being been sent to.

But one can't write LAW queries in PowerShell

**Comment by dcaro** [comment]
Please open a feature request to have LAW queries supported in PowerShell.

**Comment by dingmeng-xue** [comment]
Close this issue and let's track #15396
