### ISSUE TITLE
New-AzSubscription: add -Tag parameter

### ISSUE THREAD

**Issue by rwaal** [Azure/azure-powershell#14001]
I want to be able to create subscriptions with the proper resource tags during creation. Many, if not all, Azure PowerShell commands used for resource creation have the `-Tag` parameter. 

Ideally I would be able to do something like this:
```
$resourceTags = @{
    BillingCode   = "1234"
    BusinessUnit  = "Finance"
    Owner         = "somebody@mycompany.com"
}
New-AzSubscription `
    -Name "My Subscription" `
    -EnrollmentAccountObjectId "<enrollmentId>" `
    -OfferType "<offerType>" `
    -Tags $resourceTags
```

Our scenario:
We would like to use Azure Policy to deny the creation of Azure subscriptions that don't have the proper resource tags. This is important from a billing and governance point of view. But we cannot implement such a policy, because you can't create a subscription with tags during creation.

**Comment by anuragdalmia** [comment]
Thanks for sharing this feedback. @rwaal  - can you help me understand the details of your scenario for this including the billing/compliance policies. I am assuming you are aware that you can call tagging apis to tag a subscription after its been created, but that doesnt work for your scenarios?

**Comment by rwaal** [comment]
Hi @anuragdalmia,

My client is a large international organisation, with different business units that operated more or less autonomously. Subscriptions can be created by each of these business units. However, some kind of governance is required. So we intend to create an Azure Policy that denies the creation of subscriptions without the proper resource tags. Tags are used for billing, among other things.

I am aware that you can assign tags to a subscription after it has been created. The problem is that the subscription may already have been created incorrectly (with wrong tags). We want to prevent the creation in the first place, if the proper tags have not been used.

Almost every Azure resource type that can be created with a PowerShell cmdlet has a `-Tag` parameter. So adding this to the New-AzSubscription cmdlet would result in a consistent experience.

**Comment by brishalkumar** [comment]
is there any update for the solution

**Comment by anuragdalmia** [comment]
Yes, the various SDKs are in the process of getting published. You can find the python one at https://docs.microsoft.com/en-us/python/api/azure-mgmt-subscription/azure.mgmt.subscription.models.putaliasrequestadditionalproperties?view=azure-python. Shortly (end of Feb) we expect all the SDKs to be published. You will be able to specify the subscription management group, tenant, owner and tags as part of these APIs upon subscription create.
