### ISSUE TITLE
Feature Request: -Refresh parameter for Get-AzAccessToken

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#14005]
## Description of the new feature
It is often possible to get an access token that is near the end of its life from the cache, and when using this token for other services (Microsoft Graph module for instance) since the renew token isn't present it can cause intermittent issues more likely

## Proposed implementation details (optional)
Add a -Refresh parameter that will force the issuance of a fresh token, guaranteeing at least 1 hour of use

Ideally of course the implementer would detect on the expiresOn of the token and request it directly from Az, but that is not always possible (see pending https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/509)

**Comment by dingmeng-xue** [comment]
@JustinGrote , could you explain why you need to expose refresh token? Normally, user needs to login via `Connect-AzAccount`.

**Comment by JustinGrote** [comment]
@dingmeng-xue here is my functional workaround, using HttpPipelinePrepend (but you could use it internally to the module).
https://github.com/JustinGrote/JustinGrote.Microsoft.Graph.Extensions

**Comment by dingmeng-xue** [comment]
Hi JustinGrote,

We got couple feedback from MSAL team about this feature even they already expose force_refresh parameter.

- MSAL already builds in a 5-minute cushion, so that the returned access token (AT) would have at least 5 minute life time, which would be more than enough for usual CLI commands.
- If an app's use case would need to use the AT for potentially long time, the eventual AT expiration would be inevitable. That app would need to implement some sort of re-acquring AT logic.
- It is not recommended that client triggers force fresh and bypass cache every time.

I'm not sure how you use AT and Get-AzAccessToken. Could you fetch access token regularly in scripts?

**Comment by JustinGrote** [comment]
@dingmeng-xue currently it is used as a workaround to then tie into the mg operations. The idea would be that it would fetch a 1 hour token and then reuse that token up to the expires line. It will refresh however regardless.

https://github.com/justingrote/justingrote.microsoft.graph.extensions

**Comment by dingmeng-xue** [comment]
When operation is longer than 1 hour, you will hit the same issue.  So, the client should update access token when it is expired.

**Comment by JustinGrote** [comment]
@dingmeng-xue while true, it is a lot easier to design a solution when it has a predictable budget of 1 hour vs. anywhere from 5 minutes to 1 hour. I still think it is worth having since it already exists in the underlying library, however if you want to close it I'll push it no further.

**Comment by dcaro** [comment]
@JustinGrote as mentioned above, the MSAL team is strongly discouraging applications to implement a mechanism that would trigger a refresh and bypass the cache.

We are concerned about the implication this may have in the future and prefer to follow the recommendation of the MSAL team hence not pursuing with this implementation.

However, we'd be happy to fully understand the scenario and identify if there is anything that can be done to simplify it.

**Comment by craig-martin** [comment]
Would be nice if this worked.  Today when I get a token from Get-AzAccessToken it breaks after the token expires (expected).  Is the cache supposed to renew the token automatically?  I have a script that could take hours to run...

**Comment by HaimBendanan** [comment]
@craig-martin IIUC, your script should repeatedly call get-access-token. The first time you call the function, a new token will be generated. Following calls to the function will either fetch a token from the cache if still valid, or issue a new token. This was a bit counter intuitive to me too, I would expect to manage the life time of the token myself or at least have control on the refresh strategy (force refresh / refresh x minutes before expiry)

**Comment by DSpindlerAlii** [comment]
A specific user case is PIM and MyAccess Access Packages. What if a user is granted some access and they had an existing token? wait an hour? It sucks.....I can auth using client apps with new permissions but CLI lags? Really poor user experience. We need a force refresh and really it shouldn't be too much to ask.
