### ISSUE TITLE
Get-AzRecoveryServicesVaultSettingsFile: X509Certificate is immutable on this platform. Use the equivalent constructor instead.

### ISSUE THREAD

**Issue by mdurini** [Azure/azure-powershell#14011]
## Description

Get-AzRecoveryServicesVaultSettingsFile cmdlet does not work even after providing '-certificate' parameter. Same error related to [this ](https://github.com/Azure/azure-powershell/issues/12541) issue. The workitem linked by Sharmistha-Rai is not accessible to me

## Steps to reproduce

Import AZ module and run the cmdlet Get-AzRecoveryServicesVaultSettingsFile providing the required parameters.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

Latest version

## Error output

```
Get-AzRecoveryServicesVaultSettingsFile: X509Certificate is immutable on this platform. Use the equivalent constructor instead.
```

**Comment by dingmeng-xue** [comment]
@mdurini , thanks for reporting. Please share the debug message after setting `$DebugPreference="Continue"`

**Comment by mdurini** [comment]
Hello @dingmeng-xue, I will close this issue because I got the solution in another issue not opened by me

[https://github.com/Azure/azure-powershell/issues/12541](link)
