### ISSUE TITLE
prompt for legal terms in New-AzVMWarePrivateCloud

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-powershell#14016]
## Description of the new feature

`New-AzVMWarePrivateCloud` needs to present the additional legal terms as described in internal work item [8493765](https://msazure.visualstudio.com/One/_workitems/edit/8493765/). Hopefully, this can ship the same time as #13824. The Az CLI implementation of this feature is https://github.com/Azure/azure-cli-extensions/pull/2932.

**Comment by VeryEarly** [comment]
It looks like this term need to be presented in a public webpage. I can do it after this page was ready.

**Comment by dcaro** [comment]
@ctaggart can you confirm if the following design works for you: 

`New-AzVMWarePrivateCloud -AcceptEULA $True`  
If parameter is not passed we prompt user to accept EULA terms.

**Comment by dingmeng-xue** [comment]
@dcaro , FYI, you are correct that legal team confirmed the entire agreement should be shown up. I believe ·-AcceptEULA· is still valid before it is for automation environment.

**Comment by VeryEarly** [comment]
Hi @ctaggart ,

Just want to double check, can this legal term prompt happened before grant access to AVS resources on subscription?

powershell cmdlet will be potentially used in automation environment, 
we have to provide option to stop confirmation prompted by default. Unless we have an agreement this cmdlet was not supposed to be used in any automation environment.

**Comment by ctaggart** [comment]
> Just want to double check, can this legal term prompt happened before grant access to AVS resources on subscription?

I do not understand the question.

> powershell cmdlet will be potentially used in automation environment,
we have to provide option to stop confirmation prompted by default. Unless we have an agreement this cmdlet was not supposed to be used in any automation environment.

The cmdlet will be used in automation.  `·-AcceptEULA` sounds like a good way to allow automation.

**Comment by dcaro** [comment]
@VeryEarly I just talked with ctaggart, the legal terms have to be displayed in the terminal when the parameter is not used.
