### ISSUE TITLE
Add support for OS Disk size parameter in Set-AzVmssStorageProfile cmdlet

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#14025]
## Description of the new feature

It is currently not possible to specify the size of the OS Disk for a VM Scale Set in Az PowerShell.
`Set-AzVmssStorageProfile` should allow to set the Operating System disk size.  az cli has the --os-disk-size-gb parameter, we should replicate the same behavior in Az PowerShell

## Proposed implementation details (optional)

Add the following parameter: 
`Set-AzVmssStorageProfile -OSDiskSize`

**Comment by Drewm3** [comment]
@jayla, please work with the VMSS team and the CPlat PowerShell team to determine if this feature request should be implemented.

**Comment by jaylabell** [comment]
This feature request has been added to our backlog, and will be picked up after Ignite when our team has more bandwidth.

**Comment by Sandido** [comment]
ADO [item ](https://msazure.visualstudio.com/One/_workitems/edit/15445610/?triage=true)tracking this work.

**Comment by grizzlytheodore** [comment]
being addressed in this PR: https://github.com/Azure/azure-powershell/pull/19862
