### ISSUE TITLE
Add the ability to set the BlobTypes for a filter using the New-AzStorageAccountManagementPolicyFilter cmdlet

### ISSUE THREAD

**Issue by maartenkools** [Azure/azure-powershell#14034]
## Description of the new feature
When creating a new filter for a lifecycle rule, it is currently not possible to specify which blob type it applies to. While you can modify the filters afterwards, it would be a much better solution to add a new parameter to the cmdlet.

## Proposed implementation details (optional)
New-AzStorageAccountManagementPolicyFilter -BlobTypes @("blockBlob", "appendBlob")

**Comment by blueww** [comment]
@maartenkools 

Thanks for reporting the issue!
This is caused in [swagger ](https://github.com/Azure/azure-rest-api-specs/blob/5e076b3d3a0d6b5c9f083a0fddf0e3082137b0c6/specification/storage/resource-manager/Microsoft.Storage/preview/2020-08-01-preview/storage.json#L3680), mentioned only blockblob is supported. 

However we see both block blob and append blob are supported on portal. So we will update Powershell after swagger is updated in a future release.

**Comment by blueww** [comment]
We have already add the support with PR https://github.com/Azure/azure-powershell/pull/14261.
The change will be in the next PowerShell release.

**Comment by blueww** [comment]
Azure PSH 5.6.0 is released with the change. (Az.Storage 3.4.0)
