### ISSUE TITLE
Copy-UserInternationalSettingsToSystem is not working 

### ISSUE THREAD

**Issue by jhasgdahjg** [Azure/azure-powershell#14030]
## Description
Microsoft docs page introduces the command "Copy-UserInternationalSettingsToSystem" (https://docs.microsoft.com/en-us/powershell/module/international/copy-userinternationalsettingstosystem?view=win10-ps) 

The only issue is, that no computer can run this cmdlet as it does not appear to exist. Not in PowerShell and not in ISE. 

(I am working on windows server 2016)

Was wondering might be the issue? 

Thanks in advance! 
![PS_Problem](https://user-images.githubusercontent.com/48803695/105956678-73cba500-6078-11eb-976f-c03d54f9e1c7.PNG)

**Comment by dweggemans** [comment]
I ran into this problem as well. I'm on server 2019 datacenter. PS version 5.1.17763.1490. It seems not Azure related because I'm on AWS.

**Comment by dingmeng-xue** [comment]
That module is not owned by Azure/azure-powershell. We did the search but cannot find the module either. Please watch this issue https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2272 and waiting update.

Thanks for contacting us.

**Comment by VincentThacker** [comment]
"This cmdlet is only supported on Windows 11 and later."

**Comment by transiient** [comment]
Same issue, Windows 2022 Datacentre Azure Edition. It's a brand new deployment. Why is this documented for Server 2022 if it doesn't exist? https://learn.microsoft.com/en-us/powershell/module/international/copy-userinternationalsettingstosystem?view=windowsserver2022-ps
