### ISSUE TITLE
Could you add a way to add an Azure AD Group Owners: Add-AzADGroupOwner

### ISSUE THREAD

**Issue by saldroubi** [Azure/azure-powershell#14040]
I can create a new AD group using New-AzADGroup but there is no way to add additional owners. 

Proposed implementation details (optional)

Could you add a cmdlet that is named  Add-AzADGroupOwner
You could mimic this cmdlet:  https://docs.microsoft.com/en-us/powershell/module/azuread/add-azureadgroupowner?view=azureadps-2.0

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will evaluate effort.

**Comment by dingmeng-xue** [comment]
Track it with https://github.com/Azure/azure-powershell/issues/8412
