### ISSUE TITLE
Setup requires Windows PowerShell 3.0 or compatible [v1.0.1]

### ISSUE THREAD

**Issue by pootzko** [Azure/azure-powershell#1405]
Hi, 

I'm trying to install [v1.0.1](https://github.com/Azure/azure-powershell/releases/tag/v1.0.1-November2015) but it keeps asking me for PowerShell 3.0. 

I am running win8.1 with powershell 4:

```ps
PS > $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
```

I tried downloading and installing powershell 3 but it wouldn't install either. So I kind of have a chicken and egg problem here. Any suggestions?

Thank you.

**Comment by pootzko** [comment]
Does [this](https://github.com/Azure/azure-powershell#supported-powershell-versions) mean that powershell 4 is not supported? Am I supposed to downgrade my powershell to 3.0?

**Comment by pootzko** [comment]
A quick update, it might help someone who needs to get stuff done with this - I managed to update my azure powershell with the MS Web Installer but that's more of a workaround to this problem, not a real solution I believe.

**Comment by markcowl** [comment]
@pootzko The installer is fully supported on PowerShell 3 and PowerShell 4.  Can you provide a screenshot or capture of the message you are seeing when installation fails?

**Comment by markcowl** [comment]
@pootzko Since we cannot repro this issue and have not sent any additional data, assume that this is fixed.  If you see a recurrence, please open a new issue.

**Comment by rezaamya** [comment]
this setup requires the windows powershell 3.0 or compatible version to be installed

![image](https://user-images.githubusercontent.com/8912282/31384223-dd186fac-adca-11e7-9673-e75a23e91ed4.png)
