### ISSUE TITLE
Question: source of New-AzResourceGroupDeployment

### ISSUE THREAD

**Issue by gsscoder** [Azure/azure-powershell#14067]
Hi **azure-powershell** team,
sorry to disturb you but I can't find the source of `New-AzResourceGroupDeployment` command in which I'm very interested.

If possible, _without any hurry_, I'd like to know where it is.

Thanks for awesome work!

Best regards,
Giacomo S. S.

**Comment by dingmeng-xue** [comment]
Please check this code. 

https://github.com/Azure/azure-powershell/blob/56b4197ff38c83ba8d8c240b0e23cbbe39c4305a/src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/NewAzureResourceGroupDeploymentCmdlet.cs

**Comment by gsscoder** [comment]
Thank you @dingmeng-xue! This definitely reply to my question.

Have a nice day
