### ISSUE TITLE
[Az.ConnectedMachine] Get-AzConnectedMachineExtension should return the MachineName property

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#14117]
## Description of the new feature

An object returned by the Get-AzConnectedMachineExtension cmdlet doesn't have the MachineName property, so it's not easy to tell what machine has been queried when you had executed the command against a number of connected machines.

**Comment by navba-MSFT** [comment]
@alexandair Apologies for the late reply. Please refer [this](https://docs.microsoft.com/en-us/powershell/module/az.connectedmachine/get-azconnectedmachineextension?view=azps-7.2.0#outputs) article. This issue is open for quite sometime. Could you please let us know if you need any further assistance on this ? Awaiting your reply.

**Comment by alexandair** [comment]
@navba-MSFT I don't understand what is expected from me. The current version of this cmdlet **still doesn't** output the MachineName property. That property should be part of the default output, so that a user can see the name of the machine where the extensions are installed on.

**Comment by vedkale** [comment]
@alexandair The Id field contains the machine name, resource group and subscription id. Please use those as you can have multiple machines with the same name across different resource groups.

**Comment by alexandair** [comment]
Instead of asking a user to parse the ID property, you should output the machine name and resource group and enable the user to EASILY identify the machine.

That's a very common practice. Just look at the VM-related cmdlets, for example.

**Comment by vedkale** [comment]
this will be fixed in #24064
