### ISSUE TITLE
New-AzWvdHostPool requires argument that doesn't exist

### ISSUE THREAD

**Issue by jmeadowcroft** [Azure/azure-powershell#14135]
## Description
I am trying to execute the command which previously worked:
New-AzWvdHostPool -ResourceGroupName $ResourceGroupName -Name $HostPoolName -WorkspaceName $WorkspaceName -HostPoolType $HostPoolType -LoadBalancerType $LoadBalancerType -Location $FormattedLocation -DesktopAppGroupName $AppGroupName -PreferredAppGroupType $AppGroupType
 
but I receive the error:
Az.DesktopVirtualization\New-AzWvdHostPool : The server responded with a Request Error, Status: BadRequest
At C:\Program Files\WindowsPowerShell\Modules\Az.DesktopVirtualization\2.1.1\custom\New-AzWvdHostPool_FullSenerioCreate.ps1:111 char:9
+         $hostpool = Az.DesktopVirtualization\New-AzWvdHostPool @PSBou ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ SubscriptionI...view.HostPool }:<>f__AnonymousType18`4) [New-AzWvdHostPool_CreateExpanded], RestE 
   xception`1
    + FullyQualifiedErrorId : BadRequest,Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Cmdlets.NewAzWvdHostPool_CreateExpanded
Az.DesktopVirtualization\New-AzWvdHostPool : Argument passed in is not serializable.
Parameter name: value
At C:\Program Files\WindowsPowerShell\Modules\Az.DesktopVirtualization\2.1.1\custom\New-AzWvdHostPool_FullSenerioCreate.ps1:111 char:9
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzWvdHostPool_CreateExpanded], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Cmdlets.NewAzWvdHostPool_CreateExpanded
 
New-AzWvdHostPool : Cannot bind argument to parameter 'HostPoolArmPath' because it is an empty string.
At C:\Users\jmeadowcroft\dev\azure\terraform\wvd\main.ps1:162 char:5
+     New-AzWvdHostPool -ResourceGroupName $ResourceGroupName -Name $Ho ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzWvdHostPool_FullSenerioCreate], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-AzWvdHostPool_FullSenerioCreate

The parameter HostPoolArmPath is not documented for NewAzWvdHostPool, however it is documented for New-AzWvdApplicationGroup so I went ahead and tried to add the parameter according to that documentation by adding the parameter:
-HostPoolArmPath "/subscriptions/$SubscriptionId/resourcegroups/$ResourceGroupName/providers/Microsoft.DesktopVirtualization/hostPools/$HostPoolName"

To this I also received an error that HostPoolArmPath is not a parameter:
New-AzWvdHostPool : A parameter cannot be found that matches parameter name 'HostPoolArmPath'.
At C:\Users\jmeadowcroft\dev\azure\terraform\wvd\main.ps1:162 char:276
+ ... oupName -PreferredAppGroupType $AppGroupType -HostPoolArmPath "/subsc ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzWvdHostPool], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-AzWvdHostPool
## Steps to reproduce

1. Execute the command:
New-AzWvdHostPool -ResourceGroupName $ResourceGroupName -Name $HostPoolName -WorkspaceName $WorkspaceName -HostPoolType $HostPoolType -LoadBalancerType $LoadBalancerType -Location $FormattedLocation -DesktopAppGroupName $AppGroupName -PreferredAppGroupType $AppGroupType

## Environment data

Name                           Value
----                           -----
PSVersion                      5.1.18362.1171
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1171
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

## Module versions

ModuleType Version    Name                                ExportedCommands                                                                            
---------- -------    ----                                ----------------                                                                            
Script     2.1.1      Az.DesktopVirtualization            {Disconnect-AzWvdUserSession, Expand-AzWvdMsixImage, Get-AzWvdApplication, Get-AzWvdAppl...

**Comment by dingmeng-xue** [comment]
@GoksuAkin please help to look into this feature.

**Comment by jmeadowcroft** [comment]
Any updates on this? @GoksuAkin

**Comment by Goxu92** [comment]
@dingmeng-xue and @jmeadowcroft when did this issue started my changes were done on november 20 I am not sure if this is caused my changes and I am not the owner of the changes on this branch. I  am looking into to see who might know.

**Comment by jmeadowcroft** [comment]
I ran my script on November 5th and it worked fine. I'm not sure when it stopped working.

**Comment by datr93** [comment]
this command works fine for me: New-AzWvdHostPool -ResourceGroupName datr-canadaeast -Name fullCreate-hp3 -WorkspaceName fullCreate-ws3 -HostPoolType Pooled -LoadBalancerType DepthFirst -Location canadaeast -DesktopAppGroupName fullCreate-ag3 -PreferredAppGroupType RailApplications

are you providing correct enums?

**Comment by jmeadowcroft** [comment]
I figured out what was happening. My argument for LoadBalancerType had a typo in it, causing the whole thing to fail. I think the error message should be changed to reflect this issue, considering it was not referencing the source problem.

**Comment by mmwoodfo** [comment]
I agree - the error message is very misleading. I also encountered this issue after having a spelling error on my LoadBalancerType argument.

**Comment by ameravi** [comment]
I've been banging my head on the keyboard myself due to this.
