### ISSUE TITLE
AzureRm module references "Azure.Storage" module

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1415]
The AzureRm module is referencing a module that apparently is not part of the Azure Resource Manager (ARM) PowerShell experience.

![image](https://cloud.githubusercontent.com/assets/466713/11609462/5782c9f4-9b44-11e5-972a-901faf411120.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by devigned** [comment]
Yes it is. I think we will continue to.

**Comment by pcgeek86** [comment]
@devigned What's the reasoning behind this?

**Comment by devigned** [comment]
Many of the things you do in Azure management requires storage related operations, so we include storage by default. We think this makes sense for the majority of users.

**Comment by pcgeek86** [comment]
@devigned Right, but the module isn't named `AzureRm.Storage`, and the commands contained inside of it are not `AzureRm` commands. As best I can tell, this module appears to be part of **ASM**, but is being imported as part of **ARM**.  Are we sure that we are on the same page here?

**Comment by devigned** [comment]
Ah... It's not a part of Azure Service Management. The module contains the 'data plane' cmdlets for storage (blob, container, queues, etc...). The stuff in this module is not a part of ARM or ASM, but purely Storage APIs and auth.

**Comment by pcgeek86** [comment]
@devigned Ah, I see what you're saying. As soon as you pointed out that these are data plane commands, that makes a ton more sense. So, the data plane commands are not specific to ARM or ASM, because they are generic to the Azure Storage service. Does that sound right?

**Comment by devigned** [comment]
Precisely! I tried to tell the story a bit in the 1.0 blog post, but I think we could use more conceptual content to explain the in detail.
