### ISSUE TITLE
Select-AzureRmSubscription pipelining is broken

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1416]
The `Select-AzureRmSubscription` command doesn't support pipelining. I thought this was the new "proper" way of changing subscription contexts. Did something else change?

![image](https://cloud.githubusercontent.com/assets/466713/11609494/03f439d4-9b45-11e5-8d63-2fae90d3e88d.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 It supports piping a context, so:

```
$ctx1 = Get-AzureRmContext
...
$ctx | Select-AzureRmSubscription
...
```
