### ISSUE TITLE
Not able to use a command as part of a Powershell script

### ISSUE THREAD

**Issue by Srijith-Seetharaman** [Azure/azure-powershell#14161]
Whenever I run a powershell script with this in the first lines { Refer [(2)] for code I am trying to save as a Powershell script and run through powershell by uploading and doing **./azureRapidOnboarding.ps1**}, I keep seeing the following error:
[(1)] 
```
PS /home/srijith> ./azureRapidOnboarding.ps1
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script
     | block, or a CommandInfo object.

InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:167
Line |
 167 |          $azureADParameters = @{'Identity' = $true; 'TenantId' = $env: …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.
```
This is the code I am trying to run:

[(2)]
```
Connect-AzureAD
```
How do I proceed?

**Edit**: This command works from Azure powershell command prompt, and the issue is when executing the command from a file

**Comment by Srijith-Seetharaman** [comment]
This error seems to happen because of running **Connect-AzureAD** within the script...

**Comment by dingmeng-xue** [comment]
@Srijith-Seetharaman , thanks for reporting. It seems your issue is not related to Azure PowerShell project.

If you can share more information about your steps, we'd like to provide further help.

**Comment by Srijith-Seetharaman** [comment]
https://user-images.githubusercontent.com/78795366/107374908-220e2a80-6b0e-11eb-98fd-de4217283ca9.mp4

Please let me know what more I need to provide

**Comment by dingmeng-xue** [comment]
Thanks for sharing. I will transfer this issue to Azure CLoudShell team.
