### ISSUE TITLE
Connect-AzContainerRegistry commandlet regressed on 2.2.0 version

### ISSUE THREAD

**Issue by rjaini** [Azure/azure-powershell#14173]
Not able to push the image to repository even when login passed.

Here are the repro steps:
1. Login to a machine using device code.
Connect-AzAccount -DeviceCode
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code F8MUSLRQ8
to authenticate.
WARNING: TenantId '****' contains more than one active subscription. First one will be selected for further use. To select another subscription, use Set-AzContext.

2. Query the registry using commandlet Get-AzContainerRegistry

Container registry location: eastus2

Registry Name     Sku        LoginServer               CreationDate               Provisioni AdminUserE StorageAccountName
                                                                                  ngState    nabled
-------------     ---        -----------               ------------               ---------- ---------- ------------------
*******

3. Login using powershell commandlet Connect-AzContainerRegistry -Name <Registry Name>

----------------------------------------------------------------------------------------------------------------------------
Connect-AzContainerRegistry : WARNING! Your password will be stored unencrypted in C:\Users\azureuser\.docker\config.json.
At line:1 char:1
+ Connect-AzContainerRegistry -Name <Registry Name>
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING! Your p...er\config.json.:String) [Connect-AzContainerRegistry], RemoteException
    + FullyQualifiedErrorId : NativeCommandError,Microsoft.Azure.Commands.ContainerRegistry.ConnectAzureContainerRegistry

Connect-AzContainerRegistry : Configure a credential helper to remove this warning. See
At line:1 char:1
+ Connect-AzContainerRegistry -Name <Registry Name>
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Configure a cre...is warning. See:String) [Connect-AzContainerRegistry], RemoteException
    + FullyQualifiedErrorId : NativeCommandErrorMessage,Microsoft.Azure.Commands.ContainerRegistry.ConnectAzureContainerRegistry

Connect-AzContainerRegistry : https://docs.docker.com/engine/reference/commandline/login/#credentials-store
At line:1 char:1
+ Connect-AzContainerRegistry -Name <Registry Name>
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (https://docs.do...edentials-store:String) [Connect-AzContainerRegistry], RemoteException
    + FullyQualifiedErrorId : NativeCommandErrorMessage,Microsoft.Azure.Commands.ContainerRegistry.ConnectAzureContainerRegistry

Connect-AzContainerRegistry :
At line:1 char:1
+ Connect-AzContainerRegistry -Name <Registry Name>
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [Connect-AzContainerRegistry], RemoteException
    + FullyQualifiedErrorId : NativeCommandErrorMessage,Microsoft.Azure.Commands.ContainerRegistry.ConnectAzureContainerRegistry

**Login Succeeded**
----------------------------------------------------------------------------------------------------------------------------

4. Try to push the image docker push <RegistryName>.azurecr.io/rjaini/abcd:qwer
The push refers to repository [<RegistryName>.azurecr.io/rjaini/abcd]
55d2452fac0d: Preparing
5cbfa21cb096: Preparing
d17ed1d1fe66: Preparing
9485ce3d3573: Preparing
a60b18811ae3: Preparing
e7ea01239b3c: Waiting
8c120197f168: Waiting
de5b52133faf: Waiting
d2425dc4f846: Waiting
a7ba3db29ebb: Waiting
denied: requested access to the resource is denied

User should be able to push the registry.

**Comment by bretboss** [comment]
Pulling images using docker from v2.2.0 also fails.  I'm using a service account.

```
Connect-AzAccount -ServicePrincipal -Tenant [Redacted] -ApplicationId [Redacted] `
            -CertificateThumbprint [Redacted] -Subscription [Redacted] -Scope Process `
            -ErrorAction Stop;
# Result: Account is returned

Connect-AzContainerRegistry -Name [Redacted] -ErrorAction Stop;
# Result: Login Succeeded

docker pull [Redacted];
# Result: Error response from daemon: pull access denied for [Redacted], repository does not exist or may require 'docker login': denied: requested access to the resource is denied

```
These used to succeed.
Trying to back-date to version 2.1.0 with Az.Accounts 2.2.4 has not been successful so far.  Still working on it though.

Thank you,

--Bret

**Comment by VeryEarly** [comment]
Hi @rjaini 

Fix is available at
https://www.poshtestgallery.com/packages/Az.ContainerRegistry/2.2.1

Will be published to PSGallery soon.

**Comment by bretboss** [comment]
I verified today that version 2.2.1 fixed my issue.

Thank you!
