### ISSUE TITLE
When will the Azure PowerShell AZ.Resources Module AzPolicyAssignment CmdLets support the "nonComplianceMessages" property?

### ISSUE THREAD

**Issue by BrooksV** [Azure/azure-powershell#14175]
## Description of the new feature

The latest version of Azure PowerShell Az (v 5.5.0) installs the latest version of AZ.Resources Module (v 3,2,1) and the AzPolicyAssignment CmdLets are executing api-version=2019-09-01 which does not support the "nonComplianceMessages" and "metaData" properties.

When will the Azure PowerShell be updated to fix this issue?

## Proposed implementation details (optional)

Update the AZ.Resources Module to add to the AzPolicyAssignment CmdLets the missing parameters and to execute api-version=2020-09-01

**Comment by kenieva** [comment]
Hi @glloyd2010f , the support is currently being rolled out. You can expect to have it reflected in PowerShell beginning of April. Thanks!

**Comment by JohnLBevan** [comment]
Do you know which version of the module will include the new parameter for non compliance messages?  
i.e. Running the commands below, I don't see any parameter with a name like `NonComplianceMessages`.

```PowerShell
Update-Module AZ.Resources -RequiredVersion 3.5.1 -AllowPrerelease
Import-Module AZ.Resources -RequiredVersion 3.5.1
Get-Help New-AzPolicyAssignment -Parameter *
````

From the above thread I'd have assumed that this would now be available; but I may have misunderstood where to find this new feature, or maybe only some of the suggested changes in this ticket were implemented (e.g. there is a `metadata` parameter available to this cmdlet).

Thanks in advance / apologies if I've misunderstood anything.

**Comment by kenieva** [comment]
Hi John, there was a delay in roll out. It is currently being worked on. Thanks.

**Comment by JohnLBevan** [comment]
For the benefit of anyone else watching this thread, it looks like this has now been merged into the `master` branch: https://github.com/Azure/azure-powershell/pull/15060
