### ISSUE TITLE
Settings are still saved to "Windows Azure PowerShell" folder

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1417]
There are still references to the "Windows Azure PowerShell" directory, under my user profile. For example, when I call `Enable-AzureRmDataCollection`, the setting is saved under there. The branding "Windows Azure" has not existed for quite some time now.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by hovsepm** [comment]
Thanks for reporting, @pcgeek86 .We kept "Windows Azure" for backward compatibility. Otherwise we will have to migrate old user data from previous installed versions during update and this may become messy. Please reopen the bug if you think otherwise.

**Comment by pcgeek86** [comment]
@hovsepm I can't re-open the bug, because you've closed it. What user data would you have to migrate? I don't see this being a major problem. It should probably just be updated to be consistent with the platform nomenclature.

Cheers,
Trevor Sullivan

**Comment by pcgeek86** [comment]
@hovsepm Please re-open. I don't have the ability to re-open this bug. @devigned

**Comment by devigned** [comment]
@Azure/adx-sdk-team a gentle reminder: http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

**Comment by markcowl** [comment]
@pcgeek86  We will change the persistence folder as part of persisting AzureRM logins in #2728  Closing as duplicate
