### ISSUE TITLE
No help for Azure data collection commands

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1418]
![image](https://cloud.githubusercontent.com/assets/466713/11609551/1188723e-9b47-11e5-9331-c96377ef9836.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 will be addressed in the next release.

**Comment by pcgeek86** [comment]
@markcowl Great, let's keep this open until the bug is resolved in the next release.

**Comment by markcowl** [comment]
@pcgeek86 Fix was just checked in.  WIll go out with next release.

**Comment by pcgeek86** [comment]
@markcowl Great, thank you!
