### ISSUE TITLE
WebApp:Missing Cmdlets for App Service Environments

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/azure-powershell#14190]
## Description of the new feature

After checking the available App Service cmdlets:

```powershell
❯ Get-Command *AzAppService*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           Get-AzAppServicePlanMetrics                        1.11.0     Az.Websites
Alias           Get-AzAppServicePlanMetrics                        1.10.0     Az.Websites
Alias           Get-AzAppServicePlanMetrics                        1.9.0      Az.Websites
Cmdlet          Get-AzAppServicePlan                               2.2.0      Az.Websites
Cmdlet          Get-AzAppServicePlanMetric                         1.11.0     Az.Websites
Cmdlet          New-AzAppServicePlan                               2.2.0      Az.Websites
Cmdlet          Remove-AzAppServicePlan                            2.2.0      Az.Websites
Cmdlet          Set-AzAppServicePlan                               2.2.0      Az.Websites
```

I've noticed there are **no** cmdlets for handling App Service Environments. 

I've seen customers use `Get-AzResource -ResourceType "Microsoft.Web/hostingEnvironments"` to list ASEs, but the drawback with this method is that it doesn't show all the ASE properties.

The only straightforward ways I've seen this done is using the REST API available here: https://docs.microsoft.com/en-us/rest/api/appservice/AppServiceEnvironments/List, which does return all the ASE properties. 

**Example**

```powershell
$uri = "https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Web/hostingEnvironments?api-version=2019-08-01"
$accessToken = (Get-AzAccessToken).Token
$headers = @{"Authorization": "Bearer $accessToken"}
Invoke-RestMethod -Uri $uri -Method Get -Headers $headers
```

The other option is to use Azure CLI: https://docs.microsoft.com/en-us/cli/azure/appservice/ase?view=azure-cli-latest. 

## Proposed implementation details (optional)

Create ASE cmdlets like `Get-AzAppServiceEnvironment`, `New-AppServiceEnvironment`, `Set-AzAppServiceEnvironment` and `Remove-AzAppServiceEnvironment`. 

This would offer better ASE feature parity between Azure CLI and Azure PowerShell, and offer better customer experience when interacting with ASE using native Azure PowerShell cmdlets.

Please correct me if ASE cmdlets exist as another name, or they are handled differently in Azure PowerShell. 

I've checked the feedback forum: https://feedback.azure.com/forums/169385-web-apps/suggestions/37468678-powershell-to-retrieve-the-details-of-an-existing, and it seems this has been requested already, so my follow up was to ask here. 

Thank you for your support :)

**Comment by jwatersdeloitte** [comment]
Some of these appear to have been introduced in Az 5.6, March 2021.

https://github.com/Azure/azure-powershell/releases/tag/v5.6.0-March2021

'New-AzAppServiceEnvironment'
'Remove-AzAppServiceEnvironment'
'Get-AzAppServiceEnvironment'
'New-AzAppServiceEnvironmentInboundServices'

**Comment by WatersJohn** [comment]
Some of these have been added in the Az PowerShell cmdlets 5.6, March 2021:
'New-AzAppServiceEnvironment'
'Remove-AzAppServiceEnvironment'
'Get-AzAppServiceEnvironment'
'New-AzAppServiceEnvironmentInboundServices'

https://github.com/Azure/azure-powershell/releases/tag/v5.6.0-March2021

**Comment by ArmaanMcleod** [comment]
@WatersJohn Thats great, I didn't realise those were included in the latest release. 

In my opinion `Get-AzAppServiceEnvironment` should be giving the same results as the API, which shows much more properties.
