### ISSUE TITLE
WebApp:Remove-AzWebApp parameter to not delete ASP

### ISSUE THREAD

**Issue by jcbrooks92** [Azure/azure-powershell#14195]
## Description of the new feature
The two commands to remove a web app or function app remove the app service plan as well if its the last app in the plan. This can cause issues especially in an ASE where the provisioning of new plans takes some time. What is recommended is adding a parameter to not delete the ASP similar to the toggle option in the Azure portal. 

Remove-AzFunctionApp
Remove-AzWebApp

![image](https://user-images.githubusercontent.com/18233035/107832627-eae28800-6d5e-11eb-9154-772a43b20df3.png)

**Comment by panchagnula** [comment]
ACK ! :) Funny that's a feature  I added on portal - but never got it to CLI/Powershell.

**Comment by dingmeng-xue** [comment]
@jcbrooks92 , could you create another github issue specific to `Remove-AzFunctionApp`? We handle them by separate team.

**Comment by ThejaChoudary** [comment]
@jcbrooks92 Unable to repro the Issue at our end.Can you please share the -debug details with the command for further investigation.

**Comment by jcbrooks92** [comment]
@ThejaChoudary I tried this a couple of times and couldn't actually repro it for the Remove-AzWebApp command. It seems to possibly only reproduce with the Remove-AzFunctionApp command, so I believe you are right that this command doesn't seem impacted by it. Let me know if you were seeing otherwise. I guess the ask of allowing the flag to delete the ASP as well could be an ask?

**Comment by ThejaChoudary** [comment]
@jcbrooks92 We are looking into this and will work on this based on priority.
