### ISSUE TITLE
[AKS] Add support for Stop/Start AKS cluster

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#14194]
## Description of the new feature
Add cmdlets to support stop and start of an AKS cluster.
This is described in 2020-09-01 API version:

- https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2020-09-01/managedClusters.json#L1078 
- https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2020-09-01/managedClusters.json#L1034

## Proposed implementation details (optional)

Add following cmdlets:

```
Stop-AzAksCluster -Name
Get-AzAksCluster -Name  | Stop-AzAksCluster
Start-AzAksCluster -Name
Get-AzAksCluster -Name  | Start-AzAksCluster
```

SDK should be targeting the most recent API version (2020-12-01)

**Comment by dcaro** [comment]
Received additional customer request from support.

**Comment by dennismdejong** [comment]
Is there anything we can do to help resolving this request? I really don't want to mix Powershell and Azure cli commands in my scripts.

**Comment by dcaro** [comment]
@dennismdejong if this is fine for you, you can send me additional customer information over email to help prioritize this.

**Comment by dingmeng-xue** [comment]
We need the new version of AKS sdk for dotnet. Currently, version 1.1.0 only supports:
```
		new Tuple<string, string, string>("ContainerService", "AgentPools", "2020-07-01"),
		new Tuple<string, string, string>("ContainerService", "ContainerServices", "2017-07-01"),
		new Tuple<string, string, string>("ContainerService", "ContainerServices", "2019-08-01"),
		new Tuple<string, string, string>("ContainerService", "ManagedClusters", "2020-07-01"),
		new Tuple<string, string, string>("ContainerService", "OpenShiftManagedClusters", "2019-04-30"),
		new Tuple<string, string, string>("ContainerService", "Operations", "2020-07-01"),
		new Tuple<string, string, string>("ContainerService", "PrivateEndpointConnections", "2020-07-01")
```

**Comment by Baklap4** [comment]
Any updates on this or forecast when this is going live?

Today we've received a mail about us stopping and starting VMSS's which is when the July Api verison is released:
```
After the July API update which will be published at the end of the month, VMs that have been deallocated using IaaS APIs (Virtual Machine Scale Set APIs) will be removed with the next AKS operation you perform. 
```

We'd like to see these cmdlets and use it within our automation account

**Comment by dcaro** [comment]
@Baklap4 this is planned to be availabe in the Az.AKS modules on 8/3/2021.
