### ISSUE TITLE
Missing help for -LockLevel parameter on New-AzureRmResourceLock

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1419]
- Nothing indicates the supported values.
- Only one value is auto-completed with Intellisense.

![image](https://cloud.githubusercontent.com/assets/466713/11609808/e80d829e-9b4d-11e5-86f1-1dbad6aaa65f.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by hovsepm** [comment]
Duplicate of #1420
