### ISSUE TITLE
Remove-AzFunctionApp parameter to not delete ASP

### ISSUE THREAD

**Issue by jcbrooks92** [Azure/azure-powershell#14204]
## Description of the new feature

The command to remove a function app remove the app service plan as well if its the last app in the plan. This can cause issues especially in an ASE where the provisioning of new plans takes some time. What is recommended is adding a parameter to not delete the ASP similar to the toggle option in the Azure portal.

Remove-AzFunctionApp

**Comment by jcbrooks92** [comment]
@dingmeng-xue filed the new issue for Remove-AzFunctionApp

**Comment by Francisco-Gamino** [comment]
Thanks @jcbrooks92 for reporting this issue. I will look at the APIs to see if we can implement this. 

/cc: @stefanushinardi @AnatoliB

**Comment by Francisco-Gamino** [comment]
Yes, it is possible to not delete an empty function app plan. To specify this, can add a switch like `DoNotRemoveFunctionAppPlan`.

**Comment by jcbrooks92** [comment]
Awesome I'll test it out.

**Comment by Francisco-Gamino** [comment]
After discussing this scenario with the team, we decided to change the default behavior of the `Remove-AzFunctionApp` to not delete ASP if it is the last app in the plan. For more information, please see https://github.com/Azure/azure-powershell/issues/16487.

Also, we are going to add a switch to specify deleting the app plan if this is the last app in the plan. This work will be tracked by https://github.com/Azure/azure-powershell/issues/16488
