### ISSUE TITLE
Replicate Azure CLI "az vm user" features

### ISSUE THREAD

**Issue by sbonds** [Azure/azure-powershell#14206]
## Description of the new feature

Replicate the features of "az vm user" in a way that is consistent with the PowerShell Az interface.

## Proposed implementation details (optional)

The current commands supported by "az vm user":

```
    delete    : Delete a user account from a VM.
    reset-ssh : Reset the SSH configuration on a VM.
    update    : Update a user account.
```

Update includes options for adding a user, changing a password, or changing an ssh key.

PowerShell equivalents using an older module are described here: https://azure.microsoft.com/en-us/blog/using-vmaccess-extension-to-reset-login-credentials-for-linux-vm/

Converting those to current methods proved to be at least moderately difficult and required the use of `--debug` on the above CLI commands to find out how to mimic them using the current preferred PowerShell methods.

Based on the existing interfaces for PowerShell, we could either:

* add a new top-ish level collection to `Set-AzVM` along the lines of `Set-AzVMUser` or `Get-AzVMUser`
* merge these into the closest match `Set-AzVMOperatingSystem` where user management already exist

The former is a closer match to the Az CLI method, the latter is more consistent with the existing PowerShell methods.

### Remove an Admin User

```powershell
[cmdletbinding()]
param (
  [Parameter(Mandatory = $true)][string]$Name,
  [Parameter(Mandatory = $true)][string]$Location,
  [Parameter(Mandatory = $true)][string]$ResourceGroupName,
  [Parameter(Mandatory = $true)][string]$AdminUser,
)

$protectedSettings = @{
  remove_user = $AdminUser;
}
Set-AzVMExtension -VMName $Name `
  -ResourceGroup $ResourceGroupName `
  -Location $Location `
  -Publisher "Microsoft.OSTCExtensions" `
  -ExtensionType "VMAccessForLinux" `
  -Name "enablevmaccess" `
  -TypeHandlerVersion "1.5" `
  -ProtectedSettings $protectedSettings
```

### Others

Using the above code but tweaking the `protectedSettings` hash using the values documented within the [Linux VMAccess Extension](https://github.com/Azure/azure-linux-extensions/tree/master/VMAccess#12-protected-configuration) should work but I've only so far needed to test removing a user.

**Comment by Vaibhav-Agar** [comment]
hi @avirishuv, is this something that will fall your purview?

**Comment by Drewm3** [comment]
This is something that @jaylabell  and Bila should consider for their backlog of PowerShell convenience functions.

**Comment by jaylabell** [comment]
This feature-request has been added to our backlog, and will be picked up as soon as we have more bandwidth. More updates soon to come!

**Comment by jaylabell** [comment]
@navba-MSFT this item is being investigated. Updates are coming.

**Comment by Sandido** [comment]
[ADO item](https://msazure.visualstudio.com/One/_workitems/edit/15445621) tracking this work.

**Comment by jaylabell** [comment]
Based off of @grizzlytheodore most recent comments in backlog: 
For CLI this was created because there were issues with az vm extension add.
This works for PS using using Set-AzVmExtension. 

@sbonds Please reopen if you feel there is an extended need for this feature request
