### ISSUE TITLE
Add Win2019Datacenter to the list of image names supported by New-AzVM -Image

### ISSUE THREAD

**Issue by craiglandis** [Azure/azure-powershell#14201]
## Description of the new feature

Add **Win2019Datacenter** to the list of image names supported by **New-AzVM -Image**

## Proposed implementation details (optional)

Update https://github.com/Azure/azure-powershell/blob/d56471fd0ff0dc47eda189992adfdacc9ff18d8d/src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs

**Comment by Vaibhav-Agar** [comment]
Assigning myself to take a look.

**Comment by Vaibhav-Agar** [comment]
Hi @Sandido, seems like you own the code where the proposed changes are being made. Can you take a look here?

**Comment by Sandido** [comment]
@craiglandis , I understand this ask to be 'add Win2019Datacenter to the argument completer list for the -Image parameter'. 
Is that correct?
I can already create a VM with -Image Win2019Datcenter in the New-AzVM cmdlet.

**Comment by craiglandis** [comment]
> @craiglandis , I understand this ask to be 'add Win2019Datacenter to the argument completer list for the -Image parameter'.
> Is that correct?
> I can already create a VM with -Image Win2019Datcenter in the New-AzVM cmdlet.

Add to argument completer list and to cmdlet help

**Comment by Sandido** [comment]
We will make this change, The work is being tracked [here](https://msazure.visualstudio.com/One/_workitems/edit/9555300).
We will update this issue when the work is completed.

**Comment by Sandido** [comment]
Hi all. 
Our bandwidth has been full for a while now, but we should be completing this ask for the coming PS release (release to customers on 5/25).

**Comment by Sandido** [comment]
I made the update to the New-AzVM cmdlet argument completer. Work will be released to customers in the next PS release on 5/25.
