### ISSUE TITLE
Unhelpful help for -LockNotes parameter on New-AzureRmResourceLock

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1420]
- Nothing indicates the constraints on the value for `-LockNotes`
- Does it support special characters?
- How long can the string be?
- Who can read and update the lock notes?

![image](https://cloud.githubusercontent.com/assets/466713/11609817/1210ce8e-9b4e-11e5-8f38-ddfe02efa304.png)
,
Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by hovsepm** [comment]
Missing help for -LockLevel parameter on New-AzureRmResourceLock
- Nothing indicates the supported values.
- Only one value is auto-completed with Intellisense.

![image](https://cloud.githubusercontent.com/assets/466713/11609808/e80d829e-9b4d-11e5-86f1-1dbad6aaa65f.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by pcgeek86** [comment]
@hovsepm Issue #1439 has nothing to do with ARM Resource Locks.

Cheers,
Trevor Sullivan

**Comment by ravbhatnagar** [comment]
Could not get to this in the Apr release.

**Comment by ravbhatnagar** [comment]
Fixed May 2016
