### ISSUE TITLE
Improper return value from Remove-AzureRmResourceLock

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1421]
The `New-AzureRmResourceLock` command returns the Resource Group that was affected by the operation. The `Remove-AzureRmResourceLock` command returns boolean `true`.

The experience should be more consistent here. We should probably be returning the Resource Group object for both `New` and `Remove` commands.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by ravbhatnagar** [comment]
Lets confirm if we return the resource group in the New cmdlet.

**Comment by ravbhatnagar** [comment]
The New cmdlet returns the object that was created which is a resource lock in this case and the Remove returns bool. By design.
