### ISSUE TITLE
No help for Invoke-AzureRmResourceAction

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1422]
- What does this command do?
- How do I get a list of supported actions?
- How do I write an OData query?

![image](https://cloud.githubusercontent.com/assets/466713/11609869/46a418c6-9b4f-11e5-817c-3aa3c316f60e.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by lpassig** [comment]
This command should execute resource actions using REST I guess, to see all supported actions for the provider you can browse the Azure Resource Explorer (https://resources.azure.com) to have an overview. Anyway it seems not to work for me. 
![invokeaction](https://cloud.githubusercontent.com/assets/14903823/12514073/a9f67cb4-c121-11e5-8131-b15395902451.png)

**Comment by ravbhatnagar** [comment]
Lets fix!

**Comment by markcowl** [comment]
@vivsriaus Can we add some additional documentation and examples to the help for this cmdlet?

**Comment by ravbhatnagar** [comment]
Additional information added. Fixed in Apr Rel.
