### ISSUE TITLE
No help for New-AzureRmADApplication

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1423]
With a command as complex as this one, help documentation is even more essential than normal.

![image](https://cloud.githubusercontent.com/assets/466713/11609905/6199c346-9b50-11e5-93e4-d6b6981f1993.png)

![image](https://cloud.githubusercontent.com/assets/466713/11609910/6a82c8cc-9b50-11e5-8b2b-90fb747ae00b.png)

![image](https://cloud.githubusercontent.com/assets/466713/11609911/762aa302-9b50-11e5-8a7c-9c6fd056bb9a.png)

![image](https://cloud.githubusercontent.com/assets/466713/11609912/8bca5ea0-9b50-11e5-8a2c-9beeeac699eb.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by cormacpayne** [comment]
The help for this cmdlet has been updated. Closing this issue.
