### ISSUE TITLE
Get-AzKeyVaultSecret returns null for SecretValueText

### ISSUE THREAD

**Issue by rashigoyal** [Azure/azure-powershell#14233]
I am using the below command to get the secrets:
$UpdatedSecret = Get-AzKeyVaultSecret -VaultName $VaultName -Name $SecretName 
$UpdatedSecret.SecretValueText comes as empty

This was earlier working and this is breaking some scenarios in our production environment

Get-AzKeyVaultSecret -VaultName $VaultName -Name $SecretName -AsPlainText returns the right value.

**Comment by isra-fel** [comment]
@rashigoyal  Hi, yes, we updated our design on `Get-AzKeyVaultSecret` to fix a potential security issue last year.

If you don't care about the actual plain text of the secret, we recommend using the `SecretValue` property instead, which is a `SecureString` object.
If you do want to look at the exact secret text, as you said, `-AsPlainText` will work.

**Comment by rashigoyal** [comment]
@isra-fel : Any way we can restrict runbooks to use the old az version so that our scripts continue to work even in future if we have such breaking change?

**Comment by isra-fel** [comment]
Once module is imported to runbook, I don't suppose it will update unless user manually does it.
And if you wish to import an old version of the module, you can do that by clicking "Deploy to azure automation" button of the desired version on PowerShell gallery. See https://docs.microsoft.com/en-us/azure/automation/shared-resources/modules#import-az-modules

**Comment by rashigoyal** [comment]
My automation account still shows the old module version but the associated runbook still gives null value for SecretValueText.
![image](https://user-images.githubusercontent.com/15063473/108535990-ed665400-7301-11eb-8ff2-df5d47961262.png)

**Comment by isra-fel** [comment]
The cmdlet is from Az.KeyVault module, in your account it's 3.4.0.
The breaking change happened in 3.0.0
