### ISSUE TITLE
get-azreservationquote example incorrect

### ISSUE THREAD

**Issue by SumeshP** [Azure/azure-powershell#14249]
https://docs.microsoft.com/powershell/module/az.reservations/get-azreservationquote
SKU in example 1 is incorrect and cause command to fail. update with valid aku

**Comment by rkapso** [comment]
Thank you for bringing this to our attention we will get the doc updated.

**Comment by ramaganesan-rg** [comment]
Please let us know if you have any further questions.

**Comment by ramaganesan-rg** [comment]
Closing this issue. please feel free to reopen as needed.
