### ISSUE TITLE
No help for Register-AzureRmResourceProvider

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1424]
![image](https://cloud.githubusercontent.com/assets/466713/11609918/c1d0b2c4-9b50-11e5-9e67-b8329ecfdb21.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ravbhatnagar** [comment]
Lets fix this!

**Comment by ravbhatnagar** [comment]
Fixed - 3/3 PS release
