### ISSUE TITLE
Recovery Services Vault - Cannot Update with REST API

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-powershell#14257]
The issue is copied from https://github.com/Azure/azure-rest-api-specs/issues/13076

**Scenario:** 
I am executing a Powershell script to call the Azure REST API and update a recovery services vault.
**Documentation Issue:** 
What do I supply for the properties parameter in order to successfully call the API (see error)
Expected Behavior: Assign a managed identity to recovery services vault with the Azure REST API.
**Actual Behavior:** 
Received error message 
{"error":{"code":"InvalidRestApiParameter","message":"properties parameter is invalid.\r\nPlease provide a valid properties","target":null,"details":null,"innerError":null}}
**Things I have tried:** 
Not passing properties in the body at all, passing properties as blank, passing the pre-existing properties on this vault. I get the same error each time.
**Json body as it is passed:**
body: {
    "properties":  {

                   },
    "location":  "westus2",
    "identity":  {
                     "type":  "SystemAssigned"
                 }
}
**Powershell Script:**
Param (
  $ClientId,
  $ClientSecret,
  $VaultName,
  $ResourceGroupName,
  $SubscriptionId,
  $TenantId,
  $Location
)

function Get-AccessToken() {
  param (
    [Parameter(Mandatory=$TRUE)]
    [String]
    $ClientId,

    [Parameter(Mandatory=$TRUE)]
    [String]
    $ClientSecret,

    [Parameter(Mandatory=$TRUE)]
    [String]
    $TenantId
  )

  $resource = "https://management.azure.com/"
  $requestAccessTokenUri = "https://login.microsoftonline.com/$TenantId/oauth2/token"
  $body = @{
    grant_type = "client_credentials"
    client_id = $ClientId
    client_secret = $ClientSecret
    resource = $resource
  }

  try {
    $token = Invoke-RestMethod -Method Post -Uri $requestAccessTokenUri -Body $body
  }
  catch {
      Write-HOST "Error in getAccessToken() Invoke-RestMethod:"
      Write-HOST $_
      Write-HOST "uri: $requestAccessTokenUri"
      Write-HOST "body: $body"
  }
  return $token.access_token
}

function Set-ManagedIdentity {
  param (
    [Parameter(Mandatory=$TRUE)]
    [String]
    $VaultName,
    [Parameter(Mandatory=$TRUE)]
    [String]
    $ResourceGroupName,
    [Parameter(Mandatory=$TRUE)]
    [String]
    $SubscriptionId,
    [Parameter(Mandatory=$TRUE)]
    [String]
    $Token,
    [Parameter(Mandatory=$TRUE)]
    [String]
    $Location
  )

    $uri = "https://management.azure.com/subscriptions/${SubscriptionId}/resourceGroups/${ResourceGroupName}/providers/Microsoft.RecoveryServices/vaults/${VaultName}?api-version=2016-06-01"

    $headers = @{
      "Content-Type" = "application/json"
      "Authorization" = "BEARER $token"
    }

    $body = @{
      properties = @{}
      location = $Location
      identity = @{
        type = "SystemAssigned"
      }
    }
    $jsonBody = $body | ConvertTo-Json -Depth 2
  
    try {
      Invoke-RestMethod -Method Put -Uri $uri -Body $jsonBody -Headers $headers
    }
    catch {
      Write-HOST "Error Invoke-RestMethod:"
      Write-HOST $_
      Write-HOST "uri: $uri"
      Write-HOST "body: $jsonBody"
    }
}

try {
  $Token = Get-AccessToken -ClientId $ClientId -ClientSecret $ClientSecret -TenantId $TenantId
  Set-ManagedIdentity -VaultName $VaultName -ResourceGroupName $ResourceGroupName -SubscriptionId $SubscriptionId -Token $Token -Location $Location
} catch {
  Write-HOST "An error occurred:"
  Write-HOST $_
}

**Comment by erich-wang** [comment]
Close it as it is not Azure PowerShell related question.

**Comment by pvrk** [comment]
We have a direct PS command to update MSI for vault. It is
Update-AzRecoveryServicesVault and I believe you can also the verbose mode to get the relevant REST API request body.
