### ISSUE TITLE
No help for Move-AzureRmResource

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1425]
![image](https://cloud.githubusercontent.com/assets/466713/11609921/df26999c-9b50-11e5-9176-f627b22f655d.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by tylerd** [comment]
There does not seem to be any help on any of the AzureRM commands. Is this forthcoming?

**Comment by mvanhalen** [comment]
This seems to work now but with get-help Move-AzureRmResource 
<img width="1074" alt="azure powershell" src="https://cloud.githubusercontent.com/assets/1112640/12443955/06ba5866-bf5c-11e5-8d65-8f753605b0b5.png">

Version 1.0

**Comment by ravbhatnagar** [comment]
Doc issue. Lets fix this.

**Comment by ravbhatnagar** [comment]
Fixed - 3/3 PS release
