### ISSUE TITLE
WebApp:Remove-AzWebAppAccessRestrictionRule Add the ability to select single rule when names are the same

### ISSUE THREAD

**Issue by davidjhole** [Azure/azure-powershell#14260]
### Remove-AzWebAppAccessRestrictionRule
It would be good if you could add the ability to identify the rule you wish to delete by specifying the IP address, right now you can add multiple rules with the same name and ID so there in not a unique way to identify the rule when there are multiple rules with the same name it will just delete the last one.

## Proposed implementation details (optional)
add a parameter for IP Address (seems to be unique)

**Comment by Kotasudhakarreddy** [comment]
@davidjhole - The ability is already there. Use `Remove-AzWebAppAccessRestrictionRule -ResourceGroupName "Default-Web-WestUS" -WebAppName "ContosoSite" -IpAddress "xxx.xxx.x.x/01"` . For more details please refer [this](https://docs.microsoft.com/en-us/powershell/module/az.websites/remove-azwebappaccessrestrictionrule?view=azps-5.5.0#examples)
