### ISSUE TITLE
Get-AzLoadBalancer  and Set-AzLoadBalancer with no changes even, throws error. availability zone constraint

### ISSUE THREAD

**Issue by tariqaliuk** [Azure/azure-powershell#14326]
hi All

i am trying to update an existing Azure Standard loadbalancer  using Az PowerSehll but am getting error:
FrontEnd has an existing availability zone constraint and the request has availability zone
constraint 1, 2, 3, which do not match. Zones cannot be added/updated/removed once the resource is created. The resource cannot be updated from regional to zonal or vice-versa.
i am sure the availability zones matches with existing one but still error.

Even if just try get-azloadbalancer and set-azloadbalancer with no changes. it still error the same.

$existinglb= Get-AzLoadBalancer -Name $lbName -ResourceGroupName $resourcegroup
$existinglb | Set-AzLoadBalancer

StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: ResourceAvailabilityZonesCannotBeModified
ErrorMessage: Resource /subscriptions/********/resourceGroups/rg/providers/Microsoft.Network/loadBala
ncers/lb1/frontendIPConfigurations/Frontend1 has an existing availability zone constraint  and the request has availability zone 
constraint 1, 2, 3, which do not match. Zones cannot be added/updated/removed once the resource is created. The resource cannot be updated 
from regional to zonal or vice-versa.

i am using latest az moudes. i.e. 5.5.0

Regards
TA

**Comment by brianlehr** [comment]
Hello all,

This is a known issue in the current implementation of Set-AzLoadBalancer for regions with Availability Zones.  New code is currently being deployed to fix this issue.  In the meantime, the equivalent commands in CLI (or Portal) should be used.

**Comment by tariqaliuk** [comment]
thanks Brian for confirming this. we can use portal but needed this for PowerShell automation of LB. will have to wait for the new release then.

Regards
TA

**Comment by KranthiPakala-MSFT** [comment]
@tariqaliuk  Following up to see if you still have this issue? Please confirm if you still blocked because of this or if this issue can be closed?  Thank you

**Comment by brianlehr** [comment]
@KranthiPakala-MSFT @tariqaliuk This issue should now be remediated in PowerShell.

**Comment by brianlehr** [comment]
#please-close
