### ISSUE TITLE
 Az 5.5.0  - incorrect dependencies to Az.Automation

### ISSUE THREAD

**Issue by FutureIsHere** [Azure/azure-powershell#14359]
Az 5.5.0 is referring to the module which was unlisted Az.Automation (= 1.4.3).
Current version of Az.Automation is 1.4.2

**Comment by JPRuskin** [comment]
[Az.Automation](https://www.powershellgallery.com/packages/Az.Automation/1.4.3) has been unlisted recently. I just came here to find out why.

**Comment by JPRuskin** [comment]
[Az 5.6.0](https://www.powershellgallery.com/packages/Az/5.6.0) has now been released, which includes Az.Automation 1.5.0 and further module updates.

Will Az 5.5.0 be unlisted?

**Comment by dingmeng-xue** [comment]
@JPRuskin , Az 5.5.0 and Az.Automation 1.4.2 will not be unlisted.

Close this github issue now.

**Comment by JPRuskin** [comment]
Az 5.5.0's PSM1 contains the line `Import-Module Az.Automation -RequiredVersion 1.4.3 -Global`.
If someone installs Az 5.5.0, they cannot install 1.4.3.
Is that not broken?

I appreciate that few people will be loading the entirety of Az, but still.

**Comment by FutureIsHere** [comment]
yes, I agree with @JPRuskin . The Az.Automation 1.4.3 is causing an issue (it's why I had looked into the dependencies in the first place). Therefor I would suggest that Az 5.5.0 should be either fixed or unlisted. 1.5.0 seems to be working as expected.
New-AzAutomationVariable
"{"Message":"The request is invalid.","ModelState":{"variable.properties.value":["Invalid JSON primitive: False."]}}"

**Comment by dingmeng-xue** [comment]
Currently, we have shown Az 1.4.3 again. If user needs Az 5.5.0 but no concern on Az.Automation, user can install Az 5.5.0 now. If user needs a fix on Az.Automation, user can install Az 5.6.0. Both approaches work now.
