### ISSUE TITLE
Missing documentation: Builtin Help for New-AzureStorageaccount missing

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#1439]
The builtin help for New-AzureStorageAccount is missing, and only provides very rudimentary info. Most importantly, the "Type" is a String type (without any autocompletion) but there's no definition of allowed values.

**Comment by pcgeek86** [comment]
Weird, I thought this command actually used to have built-in help for the `-Type` parameter. This is for ASM, correct?

**Comment by trondhindenes** [comment]
Must have goofed. Working in the latest version of the Azure module. Closing.
