### ISSUE TITLE
WebApp:Private endpoint support missing for Get-AzWebApp & Set-AzWebApp 

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#14397]
## Description of the new feature

The Get-AzWebApp cmdlet does not currently return the App Service's private endpoints, and the Set-AzWebApp cmdlet doesn't understand how to write private endpoints back (e.g. for approving a private endpoint).

**Comment by Kotasudhakarreddy** [comment]
Thanks for your feedback. we will consider this in to scope based on priority.

**Comment by dingmeng-xue** [comment]
If just taking about private link resource and private endpoint connection, website/site is already supported by network module. https://github.com/Azure/azure-powershell/blob/master/src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/ProviderConfiguration.cs#L48

User can get them by resource id.

**Comment by johndowns** [comment]
@dingmeng-xue Understood. However, this cmdlet seems to be returning an error when working with App Service private endpoints specifically - see https://github.com/Azure/azure-powershell/issues/14436.

**Comment by dingmeng-xue** [comment]
Got it. Let me continue investigating on #14436. I close this one
