### ISSUE TITLE
Az.Storage version 3.4 does not work in AzureGovernment Regions

### ISSUE THREAD

**Issue by mattyt0406** [Azure/azure-powershell#14395]
Error after updating Azure Automation to AZ.Storage 3.4 now getting this :
Get-AzStorageAccount : No registered resource provider found for location 'usgovvirginia' and API version '2021-01-01' for type 'storageAccounts'. The supported api-versions are '2020-08-01-preview, 2019-06-01, 2019-04-01, 2018-11-01, 2018-07-01, 2018-03-01-preview, 2018-02-01, 2017-10-01, 2017-06-01, 2016-12-01, 2016-07-01, 2016-05-01, 2016-01-01, 2015-06-15, 2015-05-01-preview'. The supported locations are 'usgoviowa, usgovvirginia, usgovtexas, usgovarizona, usdodeast, usdodcentral'. At line:98 char:7 + $sa = Get-AzStorageAccount -StorageAccountName $storageaccountName -R ... +

This is the same error as :
https://github.com/azure/azure-powershell/issues/8892

**Comment by blueww** [comment]
@mattyt0406 

Thanks for reporting this issue!

I will contact the server team to check why the new API version 2021-01-01 is not available in AzureGovernment Regions, and update you when get any responds.

Besides that, as a workaround, would you please remove Az.Storage 3.4.0, and install 3.3.0 (3.3.0 us on API version 2019-06-01).

1. Remove the Az.Storage by :
`uninstall-module Az.storage`
2. install Az.Storage 3.3.0 by:
`Install-Module Az.Storage -RequiredVersion 3.3.0 -Repository PSGallery`

**Comment by blueww** [comment]
@mattyt0406 
The API version 2021-01-01 should already be enabled on location "usgovvirginia;usgoviowa;usdodeast;usdodcentral;usgovtexas;usgovarizona".
Would you please check?

Besides that, I will contact SRP team to see how to avoid this kind of issue happen again.

**Comment by blueww** [comment]
Close as the issue is resolved now.
