### ISSUE TITLE
Functions--need the ability to work with slot settings

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-powershell#14407]
## Description of the new feature

In Azure CLI, we have the ability to create/modify/delete slot settings (app settings that are bound to specific slots.) 
For example, I can use the following command to disable a function in function app running in a specific slot:

```azurecli
az functionapp config appsettings set --name <FUNCTION_APP_NAME> --resource-group <RESOURCE_GROUP_NAME> --slot <SLOT_NAME> --slot-settings AzureWebJobs.QueueTrigger.Disabled=true
```

Since we highlight the CLI command in our docs, we want to also be able to have an equivalent PowerShell command.

**Comment by Francisco-Gamino** [comment]
This is duplicate of https://github.com/Azure/azure-powershell/issues/14338.
