### ISSUE TITLE
Invoke-AzDataFactoryV2Pipeline Parameter of type Object does not work

### ISSUE THREAD

**Issue by abbgrade** [Azure/azure-powershell#14419]
## Description

I've got a ADF pipeline with a parameter of type object. When triggering the pipeline manually from the UI or from the .NET library, it works fine. Using this Powershell module the pipeline runs into an error:

```
Operation on target X failed: The expression 'Y' cannot be evaluated because property 'Z' doesn't exist, available properties are 'CliXml'.
```

If I convert that object to JSON before, it failed since it cannot convert a string to a object.

## Steps to reproduce

Create a ADF pipeline with a parameter of type object.
Create a pipeline run from Powershell.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
Script     1.10.0                Az.DataFactory                      Core,Desk
```

**Comment by shawnxzq** [comment]
@abbgrade Have you ever tried to upgrade to the latest Az module? 
https://docs.microsoft.com/en-us/powershell/module/az.datafactory/

**Comment by shawnxzq** [comment]
@abbgrade Have you got a chance to try the latest version of Az module? Thanks!

**Comment by abbgrade** [comment]
This is still broken in version 1.16.3 of Az.DataFactory @shawnxzq
