### ISSUE TITLE
ErrorAction does not work with Get-AzureRmResourceGroup

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#1441]
Hi,

I am trying to suppress error from Get-AzureRmResourceGroup however it is not taking effect with ErrorActionPreference.

Get-AzureRmResourceGroup -Name "howareyou" -Location "East US" -ErrorAction SilentlyContinue

Get-AzureRmResourceGroup : Provided resource group does not exist.
At line:1 char:1
+ Get-AzureRmResourceGroup -ErrorAction SilentlyContinue -Name "howareyou"  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureRmResourceGroup], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.Azure.Commands.Resources.GetAzureResourceGroupCommand

Thanks,
Pradebban Raja

**Comment by slapointe** [comment]
This have been fixed in the latest release. I am using v1.0.4.
