### ISSUE TITLE
Uninstall AzureRM Doc Enhancement

### ISSUE THREAD

**Issue by ivapplyr** [Azure/azure-powershell#14427]
## Description
Team this may be a particular edge case, but I found myself trapped in an instance where I was not able to uninstall Azure RM even with following the recommendations from [this article ](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-5.6.0#uninstall-the-azurerm-module). Essentially, I found that I had to make sure that "Execution Policy" was set to have PowerShellGet as a trusted policy. Additional information on how I stumbled on this can be found [here](https://evotec.xyz/install-module-the-install-module-command-was-found-in-the-module-powershellget-but-the-module-could-not-be-loaded/). 

## Steps to reproduce
Conditions: 
Windows 10 machine
Azure Powershell 5.1 does not appear on the uninstall flow (Start --> Settings ---> Apps --> Powershell) does not show powershell on the list

Actions by me:
```
install-Module AzureRM -AllowClobber
Import-Module AzureRM
*made several attempts to access my Az CMDlets but received errors that 'Module' could not be loaded* 
Install-Module -Name PowerShellGet -Force
if ($PSVersionTable.PSEdition -eq 'Desktop' -and (Get-Module -Name AzureRM -ListAvailable)) {
    Write-Warning -Message ('Az module not installed. Having both the AzureRM and ' +
      'Az modules installed at the same time is not supported.')
} else {
    Install-Module -Name Az -AllowClobber -Scope AllUsers
}
```
*CMDLets still didn't work*

Went through uninstall flow
*same error uninstall-azurerm : The term 'uninstall-azurerm' is not recognized as the name of a cmdlet, function, script file, or   operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try    again.  "

```powershell

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
@ivapplyr , if you want to remove AzureRM modules, you can:
1. Delete module from disc directly. You can find their directory via `Get-Module azurerm* -ListAvailable`. Path is printed out on console. Please don't delete other folders which name is not `AzureRM*`.

2. Restart your windows PowerShell and execute below code.
```
$modules = Get-Module AzureRM* -ListAvailable
ForEach($module in $modules) {
  Uninstall-Module $module.Name -Force
}
```

**Comment by ivapplyr** [comment]
@dingmeng-xue 

I have actually already successful uninstalled. Was just curious if the doc would be able to be updated with above information to help future customers

**Comment by dingmeng-xue** [comment]
@mikefrobbins , could you review https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-5.6.0#option-2-uninstall-the-azurerm-powershell-module-from-powershellget

**Comment by mikefrobbins** [comment]
The referenced article has been updated since this issue was logged. It should now be resolved with the new version of the article.
