### ISSUE TITLE
ErrorAction does not work with Get-AzureRmResource

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#1442]
I am trying to suppress error from Get-AzureRmResource however it is not taking effect with ErrorActionPreference.

Get-AzureRmResource -ResourceName "hiddenforsecurity" -ResourceType "Microsoft.Web/serverFarms" -ResourceGroupName "Howareyou" -ErrorAction SilentlyContinue
Get-AzureRmResource : ResourceNotFound : The Resource 'Microsoft.Web/serverFarms/hiddenforsecurity' under resource group 'Howareyou' was not found.
At line:1 char:8
- $new = Get-AzureRmResource -ResourceName hiddenforsecurity -ResourceType "Microsof ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Get-AzureRmResource], ErrorResponseMessageException
  - FullyQualifiedErrorId : ResourceNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet

Thanks,
Pradebban Raja

**Comment by graemechristie** [comment]
Looks to be the same issues as #1450, #1451, #1452

**Comment by ravbhatnagar** [comment]
Lets look into supporting this.

**Comment by ravbhatnagar** [comment]
@markcowl - I believe we need to consistently support this across cmdlets. It is not specific to ARM. Hence removing the ARM label and assigning it to your team. Please let me know if you feel otherwise.

**Comment by markcowl** [comment]
@ravbhatnagar See https://github.com/Azure/azure-powershell/pull/2736/files  This is resolved for cmdlets that use the AzurePSCmdlet override of ProcessRecord.  Reassigning to you so you cna verify this is the case for ResourceManager cmdlets.

**Comment by sarath-rachuri** [comment]
Any progress on this issue? I'm using Get-AzureRmResource cmdlet to check if AppInsights exists or not. Used $erroractionpreference='silentlycontinue' to suppress the error and it works perfectly on my machine. But when ran as a release definition task on VSTS hosted agent the erroractionpreference doesn't work and it is simply terminating the program. Please provide some work around for this.

**Comment by erossini** [comment]
Hi guys,
I have the same error. Also, when I create a new db, there is a question that I must respond to continue.

<img width="680" alt="error" src="https://user-images.githubusercontent.com/9497415/39125155-f2ab356a-46f5-11e8-9cc3-e72d59ca3eff.png">

How can I skip programmatically this prompt? Thanks

**Comment by cormacpayne** [comment]
I believe this will be resolved in PR https://github.com/Azure/azure-powershell/pull/6008

**Comment by cormacpayne** [comment]
The fix for this should be available on May 7th in version 6.0.0 of `AzureRM` (version 6.0.0 of `AzureRM.Resources`). Please re-open this issue if the problem persists.
