### ISSUE TITLE
Triple toc entries for Virtual Machines--one should be for Azure VMware Solution

### ISSUE THREAD

**Issue by shortpatti** [Azure/azure-powershell#14421]
**>Virtual Machines** is listed in the Az PowerShell 5.5.0 toc 3x.  One instance should be **Azure VMware Solution**.  Plus duplicate TOC entries for other services.

![orphaned-toc-entry](https://user-images.githubusercontent.com/35278231/109868583-08e82d80-7c25-11eb-8d45-e20391b58d6c.jpg)

![multiple-toc-entries](https://user-images.githubusercontent.com/35278231/109870996-f3283780-7c27-11eb-9ad8-cd264c745000.jpg)

**Comment by dingmeng-xue** [comment]
Thanks for the reporting. Beside Virtual Machines, couple other items have the same issue. We are working on a new structure to resolve this problem.
