### ISSUE TITLE
[Az.ApiManagement] Add support for managing soft deleted Api Management Services

### ISSUE THREAD

**Issue by Mpmdg** [Azure/azure-powershell#14430]
## Description
Currently, the Az.ApiManagement module [2.2.0] does not have any kind of support for Get/Remove operations on soft deleted Api Management Services:
- The Get-AzApiManagement does not list soft deleted services.
- The Remove-AzApiManagement is capable of permanently deleting the service, but is not able to purge an already soft-deleted service.
- There is no function for undoing the removal on soft deleted service (similar to Undo-AzKeyVaultRemoval).

When the ApiManagement resource is removed using Remove-AzResourceGroup action, it gets soft deleted, and the only way to purge it is by using the preview rest API: https://docs.microsoft.com/en-US/rest/api/apimanagement/2020-06-01-preview/deletedservices/purge.

**Comment by GPetrites** [comment]
What's the status of this?  Soft-deletes are out of preview and we need the proper tools to fully support.  There are probably other like me who are just now discovering that the API Management resources they "deleted" are sitting in a soft-delete state with no way to purge without spending hours learning how to use the REST API.

**Comment by navba-MSFT** [comment]
@Mpmdg Apologies for the late reply. We are looking in this issue. We will update this thread once we have more details on this.

@adrianhall Could you please look into this and provide an update on this ? Awaiting your reply.

**Comment by adrianhall** [comment]
We are currently in the process of updating the powershell module to support the latest GA release of our API, which will then cover this issue.  I'll update when the PowerShell module gets updated.

**Comment by mikebudzynski** [comment]
The latest version of the API Management module is 4.0.2. Per @adrianhall's comments above, the issue should now be resolved. If you're still experiencing the problem with the latest version, please open a new issue.
