### ISSUE TITLE
Az.Automation 1.5.0 has broken all Azure Runbooks that has [psobject[]] params

### ISSUE THREAD

**Issue by ricohomewood** [Azure/azure-powershell#14431]
## Description
Looks like version `1.5.0` of `Az.Automation` has broken calls made to `Start-AzAutomationRunbook` because it is now escaping double quotes which is invalid for runbooks that have `[psobject[]]` params i.e.:

From `1.4.2` of `Az.Automation` we pass a hashtable to the params of `Start-AzAutomationRunbook` which the runbook will convert to the following array in an Automation runbook:
["test1","test2","test3"]

But with the new 1.5.0 it is escaping quotes that is shouldn't be:
["\\"test1\\"","\\"test2\\"","\\"test3\\""]
This is invalid and all runbooks will fail as the Azure API sees this as a non valid JSON array.

## Steps to reproduce

Have a runbook that has a [psobject[]] param type i.e.
[psobject[]]$Clients

```powershell

$clients = '{test1, test2, test3}'

#Add to a hashtable:
$runbookParams = @{
    Key1           = "value1"
    Clients          = $clients
  }
#Start a runbook with these:

Start-AzAutomationRunbook -Name "SomeRunBook" -ResourceGroupName "SomeRG" -AutomationAccountName "SomeAzureAutomationAccount" -Parameters $runbookParams

Observe the Runbook Inputs:

CLIENTS | ["\\"test1\\"","\\"test2\\"","\\"test3\\""]

```

## Environment data

```
Name                                  Value                                                                                   
----                                      -----                                                                                   
PSVersion                            5.1.17763.1490                                                                          
PSEdition                            Desktop                                                                                 
PSCompatibleVersions       {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                       10.0.17763.1490                                                                         
CLRVersion                         4.0.30319.42000                                                                         
WSManStackVersion          3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
Name | Az.Accounts
Version | 2.2.6
Name | Az.Advisor
Version | 1.1.1
Name | Az.Aks
Version | 2.0.2
Name | Az.AnalysisServices
Version | 1.1.4
Name | Az.ApiManagement
Version | 2.2.0
Name | Az.AppConfiguration
Version | 1.0.0
Name | Az.ApplicationInsights
Version | 1.1.0
Name | Az.Automation
Version | 1.5.0
Name | Az.Batch
Version | 3.1.0
Name | Az.Billing
Version | 2.0.0
Name | Az.Cdn
Version | 1.6.0
Name | Az.CognitiveServices
Version | 1.8.0
Name | Az.Compute
Version | 4.10.0
Name | Az.ContainerInstance
Version | 1.0.3
Name | Az.ContainerRegistry
Version | 2.2.1
Name | Az.CosmosDB
Version | 1.1.0
Name | Az.DataBoxEdge
Version | 1.1.0
Name | Az.Databricks
Version | 1.1.0
Name | Az.DataFactory
Version | 1.11.4
Name | Az.DataLakeAnalytics
Version | 1.0.2
Name | Az.DataLakeStore
Version | 1.3.0
Name | Az.DataShare
Version | 1.0.0
Name | Az.DeploymentManager
Version | 1.1.0
Name | Az.DesktopVirtualization
Version | 2.1.1
Name | Az.DevTestLabs
Version | 1.0.2
Name | Az.Dns
Version | 1.1.2
Name | Az.EventGrid
Version | 1.3.0
Name | Az.EventHub
Version | 1.7.1
Name | Az.FrontDoor
Version | 1.7.0
Name | Az.Functions
Version | 2.0.0
Name | Az.HDInsight
Version | 4.2.0
Name | Az.HealthcareApis
Version | 1.2.0
Name | Az.IotHub
Version | 2.7.2
Name | Az.KeyVault
Version | 3.4.0
Name | Az.Kusto
Version | 1.0.1
Name | Az.LogicApp
Version | 1.5.0
Name | Az.MachineLearning
Version | 1.1.3
Name | Az.Maintenance
Version | 1.1.0
Name | Az.ManagedServices
Version | 2.0.0
Name | Az.MarketplaceOrdering
Version | 1.0.2
Name | Az.Media
Version | 1.1.1
Name | Az.Migrate
Version | 1.0.0
Name | Az.Monitor
Version | 2.4.0
Name | Az.Network
Version | 4.6.0
Name | Az.NotificationHubs
Version | 1.1.1
Name | Az.OperationalInsights
Version | 2.3.0
Name | Az.PolicyInsights
Version | 1.4.1
Name | Az.PowerBIEmbedded
Version | 1.1.2
Name | Az.PrivateDns
Version | 1.0.3
Name | Az.RecoveryServices
Version | 3.4.1
Name | Az.RedisCache
Version | 1.4.0
Name | Az.Relay
Version | 1.0.3
Name | Az.Resources
Version | 3.3.0
Name | Az.ServiceBus
Version | 1.4.1
Name | Az.ServiceFabric
Version | 2.2.2
Name | Az.SignalR
Version | 1.2.0
Name | Az.Sql
Version | 2.16.0
Name | Az.SqlVirtualMachine
Version | 1.1.0
Name | Az.Storage
Version | 3.4.0
Name | Az.StorageSync
Version | 1.4.0
Name | Az.StreamAnalytics
Version | 1.0.1
Name | Az.Support
Version | 1.0.0
Name | Az.TrafficManager
Version | 1.0.4
Name | Az.Websites
Version | 2.4.0
```

This seems related to changes made related to https://github.com/Azure/azure-powershell/issues/14215

**Comment by JPRuskin** [comment]
We're also seeing this issue.

**Comment by Xentraxx** [comment]
Same here. Only solution so far was to roll back to 1.4.2. 
1.4.3 is also affected by this issue.

**Comment by ricohomewood** [comment]
> Same here. Only solution so far was to roll back to 1.4.2.
> 1.4.3 is also affected by this issue.

Yes, for us now we have had to revert to `1.4.2` as a workaround

**Comment by JPRuskin** [comment]
Hm, that's interesting - we reverted to 1.4.3 and for our usecase it seems to work (that being a call to `Start-AzAutomationRunbook` with some ~25 parameters, including string, int, pscustomobject[], guid[], bool types.)

This using 1.4.3 rather than 1.5.0, but not downgrading to 1.4.2.

**Comment by ricohomewood** [comment]
The difference between 1.4.2 and 1.4.3 is just around the array passed to a ps custom object array param [psobject[]]. So for example we would see

In 1.4.2
[“test1”, “test2”] 

In 1.4.3
[“test1, test2”]

So 1.4.3 treats the content in the array as one complete string which breaks the runbook for us. 

1.5.0 made it worse by escaping everything it seems.

**Comment by JPRuskin** [comment]
Gotcha. Sorry for my confusion.

**Comment by ricohomewood** [comment]
Thanks @dingmeng-xue just trying but seems https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.2.6.nupkg is missing from that blob storage?

**Comment by ricohomewood** [comment]
@dingmeng-xue I have managed to test our use case using `1.5.1` and the existing `2.2.6` of `Az.Accounts`, assuming it's the same as what was in the link above, and seems to have fixed the issue of escaping the [psobject[]] array and so now looks like the below:

`["test1","test2","test3"]`
Which is what we are expecting.
Not sure if others want to also test their use cases?
Thanks for the quick fix for this. I assume it will also take a while to roll this out to all DevOps hosted agents.

**Comment by dingmeng-xue** [comment]
Thanks very much for your help. We keep this build one more day and will publish it if there is concern. 

P.S. I just fixed link of Az.Accounts 2.2.6. The content is the same as from PSGallery.

**Comment by wyunchi-ms** [comment]
Close this issue since the PR is merged. Please feel free to reopen this issue and thanks for your contribution! @ricohomewood

**Comment by adi928** [comment]
Hey all, 

I am facing the same issue with Automation runbook currently when I try to pass in the **WebhookData**. 
According to the [documentation](https://docs.microsoft.com/en-us/azure/automation/automation-webhooks#create-a-webhook), it should be converted to JSON using ConvertFrom-Json without any pre-processing. But when I try to use exactly that code, I get an error saying `Invalid JSON primitive: post-dep`
On viewing the raw JSON [1] which is going as input in **WebhookData**, I see that the double quotes are escaped which removes them when the object reaches the runbook code. 
```
[1] - "parameters": {
            "webhookData": "{\"WebhookName\":\"post-dep\",\"RequestBody\":\"{\\r\\n  ... }}"
        },
```

So far, this is the only place where I've seen discussion regarding the wrongly escaped double quotes and automation runbooks.
