### ISSUE TITLE
Get-AzLoadBalancer and Set-AzLoadBalancer availability zone constraint

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#14445]
## Description
Copy question from https://github.com/Azure/azure-powershell/discussions/14324

hi All

i am trying to update an existing Azure Standard loadbalancer but am getting error:
FrontEnd has an existing availability zone constraint  and the request has availability zone 
constraint 1, 2, 3, which do not match. Zones cannot be added/updated/removed once the resource is created. The resource cannot be updated from regional to zonal or vice-versa.
i am sure the availability zones matches with existing one but still error. 
Even if just try get-azloadbalancer and set-azloadbalancer with no changes. it still error the same.

$existinglb=  Get-AzLoadBalancer -Name $lbName -ResourceGroupName $resourcegroup
$existinglb | Set-AzLoadBalancer

i am using latest az moudes. i.e. 5.5.0

anyone seen this issue before?

Regards
TA

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by anavinahar** [comment]
Hi there - yes, we are working to release this fix soon, in the mean time could you leverage CLI or Portal?

**Comment by dingmeng-xue** [comment]
@tariqaliuk , FYI.

**Comment by KranthiPakala-MSFT** [comment]
@anavinahar Following up to see if there is any update on this issue? - Thank you

**Comment by brianlehr** [comment]
@KranthiPakala-MSFT This is now remediated and the PowerShell commands to "set" should work as expected.  Closing out issue.

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the update @brianlehr !
