### ISSUE TITLE
Add-AzVMSecret missing option to make the private key exportable from Windows Certificate Store

### ISSUE THREAD

**Issue by meastp** [Azure/azure-powershell#14456]
## Description of the new feature

Please add an option to import the certificate in Windows Certificate Store with the ability to export the private key.

My use case is for Azure to take care of adding the certificate to Windows Certificate Store (obviously), but to also be able to export the certificate locally because I need the certificate with private key converted to other formats as well (e.g. PEM).

Bonus points: Make this available as an option in [Azure Key Vault virtual machine extension](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/key-vault-windows) if that extension is using Add-AzVMSecret under the hood.

**Comment by avirishuv** [comment]
@meastp thanks for the suggestion, let me look into this and will get back with updates.

**Comment by meastp** [comment]
@avirishuv that's great, thank you

**Comment by meastp** [comment]
FYI It's @pcwiese who maintains the current (in opentelemetry/opentelemetry-collector-contrib repo) Azure Monitor Exporter. Perhaps he can give more context on what is needed? :)

**Comment by avirishuv** [comment]
hi @meastp , we've added your suggestion to the user voice forum here: https://feedback.azure.com/forums/216843-virtual-machines/suggestions/43006746-add-azvmsecret-missing-option-to-make-the-private 

Please feel free to vote and add any other comments if you have. Closing this issue and will track this feature request via the link above. Thanks.
