### ISSUE TITLE
New-AzCloudService example bug

### ISSUE THREAD

**Issue by nitinjainms** [Azure/azure-powershell#14464]
## Description

Typo in [New-AzCloudService examples](https://github.com/Azure/azure-powershell/blob/master/src/CloudService/examples/New-AzCloudService.md)

There is no cmdlet as New-AzCloudServiceCloudServiceRoleProfilePropertiesObject
Word **CloudService** is redundant in New-AzCloudService**CloudService**RoleProfilePropertiesObject

Replace New-AzCloudServiceCloudServiceRoleProfilePropertiesObject with New-AzCloudServiceRoleProfilePropertiesObject in New-AzCloudService examples.

## Steps to reproduce

```powershell
Get-Help New-AzCloudService -Examples

```

## Environment data

```

```

## Module versions

```powershell

PS > Get-Module Az.CloudService -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.1.0      Az.CloudService                     {Get-AzCloudService, Get-AzCloudServiceInstanceView, Get-AzCloudServiceNetworkInterfaces, Get-AzCloudServicePublicIPAddress...}

```

## Debug output

```

```

## Error output

```

```

**Comment by vivere-dally** [comment]
Leaving the typo aside, the module doesn't work for me at all. See: https://github.com/Azure/azure-powershell/issues/14385
