### ISSUE TITLE
Get-AzVMSize returns wrong size for constrained VM sizes

### ISSUE THREAD

**Issue by ericcsinger** [Azure/azure-powershell#14473]
## Description
When running the Get-AzVMSize function, it does not return the correct number of CPU cores for constrained VMs.

For example, the "Standard_DS14" VM sizes, it lists "Standard_DS14-8_v2" as having 16 cores.  This is incorrect, it has 8.

VM sizes documented here
https://docs.microsoft.com/en-us/azure/virtual-machines/constrained-vcpu

## Steps to reproduce

```powershell
$VM_Location = "eastus"
Get-AzVMSize -Location $vm_location | Where-Object {$_.name -like "*DS14*"}

```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell

```

## Debug output

```
Az.Compute = 4.10.0
```

## Error output

```
This returned no output
```

**Comment by avirishuv** [comment]
hi @ericcsinger thanks for pointing this out. I'll check and provide an update.

**Comment by Drewm3** [comment]
@avirishuv, the behavior here is correct. The API returns the number of vCPUs of quota that the suppressed core VM uses. To get the accurate vCPU count for these sizes the VM SKU must be looked up in the SKUs API. 

Please use this issue to update the API doc.

**Comment by avirishuv** [comment]
The API doc has been updated to reflect this: https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/list-available-sizes#virtualmachinesize

Closing the issue, please feel free to reopen if any further questions on this topic, thanks.
