### ISSUE TITLE
facing issue with referencing the keyvault certificate

### ISSUE THREAD

**Issue by Shru301** [Azure/azure-powershell#14471]
i am trying to deploy kubernetes cluster and download the certificate and generate the key and cert through Devops and im getting error in Devops like "Exception calling "Import" with "3" argument(s): "The parameter is incorrect."; I have tried running in the local powershell with the below commands and please find the screenshot for the same.
<img width="909" alt="Powershellerror" src="https://user-images.githubusercontent.com/80251850/110304815-08370900-8022-11eb-9d99-8961e77525c2.PNG">

$certSecret = Get-AzKeyVaultSecret -VaultName $KeyVaultName -Name $CertName
  $certBytes = [System.Convert]::FromBase64String($certSecret.SecretValueText)
  $certCollection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection
$certCollection.Import($certBytes,$null,[System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)

I even tried running with AzureCli and getting error like "ASN1 corrupted data.". Please find the screenshot for the same.
<img width="872" alt="CLIError" src="https://user-images.githubusercontent.com/80251850/110305133-67951900-8022-11eb-884c-2ada19185e4f.PNG">

issue is similar to https://github.com/microsoft/azure-pipelines-tasks/issues/5985.

could you please check and help on the issue.

**Comment by dingmeng-xue** [comment]
Please try this approach.

https://stackoverflow.com/questions/45089108/powershell-x509certificate2collection-exception-calling-import-with-3-argu

**Comment by Shru301** [comment]
I had already tried that link but didn't work. I  have finally found the error ; i have tried [](https://docs.microsoft.com/en-us/powershell/module/az.keyvault/get-azkeyvaultcertificate?view=azps-5.6.0#example-2--get-cert-and-save-it-as-pfx)
and it worked

**Comment by dingmeng-xue** [comment]
Thanks for the information. I'm closing this issue now. Please contact us if you meet further issue.
