### ISSUE TITLE
Enable-AzureServiceProjectRemoteDesktop error when .csdef and .cscfg contains 'schemaVersion' attribute in ServiceConfiguration or ServiceDefinition

### ISSUE THREAD

**Issue by nobitagamer** [Azure/azure-powershell#1447]
There is an error in XML document (2, 128)
+ CategoryInfo          : CloseError: (:) [Enable-AzureServiceProjectRemoteDesktop], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.CloudService.Development.EnableAzureServiceProjectRemoteDesktopCommand

**Comment by kiewic** [comment]
Bug still reproduces for *.cscfg* files using **Microsoft Azure PowerShell - January 2016**. :sob:

**Comment by markcowl** [comment]
@nobitagamer Can you provide a csdef/cscfg that reproduces this issue?  This will make it much easier to reproduce. Thanks.

**Comment by nobitagamer** [comment]
Sorry for late reply, here is my config files:

[ServiceConfiguration.Local.cscfg.txt](https://github.com/Azure/azure-powershell/files/192807/ServiceConfiguration.Local.cscfg.txt)
[ServiceDefinition.build.csdef.txt](https://github.com/Azure/azure-powershell/files/192808/ServiceDefinition.build.csdef.txt)

**Comment by markcowl** [comment]
@nobitgamer I unfortunately lost track of thsi after the initial reply are you still seeing this issue?
