### ISSUE TITLE
Import-Module Az.Storage hangs

### ISSUE THREAD

**Issue by KrX3D** [Azure/azure-powershell#14489]
## Description
 Hello, im moving from AzureRm to Az and i got an problem.

I dont need everything so i just use

Az.Accounts
Az.Storage

for my project.

But when i import it the script just hangs

## Steps to reproduce

This works:

Add-Type -AssemblyName System.Windows.Forms
Import-Module -Name "C:\Test\Az.Storage\3.4.0\Az.Storage.psd1" -Force -ErrorAction SilentlyContinue

This dont:

Add-Type -AssemblyName System.Windows.Forms
$form1 = New-Object System.Windows.Forms.form
Import-Module -Name "C:\Test\Az.Storage\3.4.0\Az.Storage.psd1" -Force -ErrorAction SilentlyContinue

something in combination with $form1 = New-Object System.Windows.Forms.form "breaks" it.

i could isolate it to:

Az.Storage.psm1 -> Line 110 -> Import-Module Az.Accounts -MinimumVersion 2.2.6 -Scope Global
Than from Az.Account .psm1-> Line 102 -> Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azure.PowerShell.Cmdlets.Accounts.dll)

importing Microsoft.Azure.PowerShell.Cmdlets.Accounts.dll "breaks" it.

if i move "$form1 = New-Object System.Windows.Forms.form" after the import of Az.Storage than it works, but it´s not possible in my project

Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

## Module versions

Az.Accounts 2.2.6
Az.Storage  3.4.0

**Comment by dingmeng-xue** [comment]
@erich-wang  FYI. App domain loads below 4 assemblies. Then Az.Accounts cannot be imported. 
```
False  v4.0.30319     C:\Dev\PowerShell-7.1.0-win-x64\System.Windows.Forms.Primitives.dll
False  v4.0.30319     C:\Dev\PowerShell-7.1.0-win-x64\System.Drawing.Primitives.dll
False  v4.0.30319     C:\Dev\PowerShell-7.1.0-win-x64\System.Drawing.Common.dll
False  v4.0.30319     C:\Dev\PowerShell-7.1.0-win-x64\System.ComponentModel.EventBasedAsync.dll
False  v4.0.30319     C:\Dev\PowerShell-7.1.0-win-x64\Accessibility.dll
```

**Comment by erich-wang** [comment]
@KrX3D, could you please help me understand why you could not move `New-Object Form` after importing Az.Storage?

>if i move "$form1 = New-Object System.Windows.Forms.form" after the import of Az.Storage than it works, but it´s not possible in my project

Or does below work for you?
```
Add-Type -AssemblyName System.Windows.Forms
Import-Module -Name "C:\Test\Az.Accounts\2.2.6\Az.Accounts.psd1" -Force -ErrorAction SilentlyContinue
$form1 = New-Object System.Windows.Forms.form
Import-Module -Name "C:\Test\Az.Storage\3.4.0\Az.Storage.psd1" -Force -ErrorAction SilentlyContinue
```

**Comment by KrX3D** [comment]
Hello,

yes this seems to work.

but its odd since Az.Storage is loading Az.Accounts

**Comment by erich-wang** [comment]
Az.Accounts is prerequisite module for any other Az.* modules. Close this issue as it is solved.
