### ISSUE TITLE
Missing RM cmdlets for remove-AzureAccount or clear-AzureProfile

### ISSUE THREAD

**Issue by davehodgson** [Azure/azure-powershell#1448]
Hi,

I am trying to convert to using the azureRM cmdlets but struggling with the process for how to "destroy" a connection.

In the azure cmdlets i used to call:
- Add-AzureAccount to log in
- Remove-AzureAccount if I needed to log out and log in as another user
- Clear-AzureProfile if I wanted to ensure the connections were dead so that if I open powershell again and forget to login that I can't accidentally use my old credentials (I connect to several different client's subscriptions).

I've reviewed the documentation at: https://msdn.microsoft.com/en-us/library/mt619248.aspx and can see how to make a connection but have no idea how to clear one.

Ideally the Clear-AzureRMProfile would exist but at least having the Remove-AzureRMAccount given that there is an Add-AzureRMAccount would allow me to work around it.

Any comments/hints/suggestions?

**Comment by hovsepm** [comment]
@davehodgson, calling Add-AzureRMAccount again should clean the previous state automatically - if it is not, please open the issue for that and describe your steps for a repro.
