### ISSUE TITLE
azureRM: Get-AzureRMContext SubscriptionId property is called Subscription

### ISSUE THREAD

**Issue by davehodgson** [Azure/azure-powershell#1449]
When I run Get-AzureRMContext I get the below back:

Environment:                  AzureCloud
Account:                         <removed>
TenantId:                        <removed>
SubscriptionId:                <removed>
CurrentStorageAccount  

If I want to access the user account programmatically I can type $(Get-AzureRmContext).Account to get the account or ($(Get-AzureRmContext).Account).id if I want the ID of the currently logged in user.

However, if I go for the SubscriptionId property using the same process $(Get-AzureRmContext).SubscriptionId it doesn't work.

When I switch to an IDE with intellisense I can see that the property is actually called Subscription, so needs to be acessed with $(Get-AzureRmContext).Subscription.

This is inconsistent and in my view either the label returned should match the property you can call programatically or the property should match the label.

**Comment by hovsepm** [comment]
@davehodgson, It is by design. Azure context has a property of type Subscription and that type has several properties. When we print out the information about current context we use just a subset of all the properties to make it useful and not exhaustive for the end users.
