### ISSUE TITLE
Support for enabling Azure Private Marketplace cmdlet

### ISSUE THREAD

**Issue by tarunngc** [Azure/azure-powershell#14507]
## Description of the new feature

Add cmlet with the ability to enable and disable Azure Private Marketplace

## Proposed implementation details (optional)

`Set-AzMarketplace -Private $True`

**Comment by dingmeng-xue** [comment]
@tarunngc , thanks for reporting. Do you know its REST API link? or is there a doc talking about how to set it via Portal?

**Comment by tarunngc** [comment]
@dingmeng-xue Here is the **doc detailing how to create and manage Private Marketplace from the portal**: 

https://docs.microsoft.com/en-us/marketplace/create-manage-private-azure-marketplace

**Comment by saviesacov** [comment]
How-To create Private Marketplace using PowerShell:
https://learn.microsoft.com/en-us/powershell/module/az.marketplace/set-azmarketplaceprivatestore?view=azps-11.1.0
