### ISSUE TITLE
Availability Zones in New-AzAksNodePool 

### ISSUE THREAD

**Issue by Jalmeida1994** [Azure/azure-powershell#14505]
## Description of the new feature
I would like to know if the flag to change _Availability Zones_ in an AKS node pool is present in the command `New-AzAksNodePool` in **Az.AKS** module. The documentation doesn't say anything about it, but it's present in the _az cli_.
If not, is it something that is in the works?

**Comment by dcaro** [comment]
@Jalmeida1994 It is not present yet but we are working on improving the AKS module and closing the gaps with az cli.

**Comment by Jalmeida1994** [comment]
Of course, thank you! I'm trying to find the time to add this functionality to the module myself, but until now it's just been impossible. Do you want me to close the issue?
