### ISSUE TITLE
Set-AzVM does way more than set a VM to "generalized"

### ISSUE THREAD

**Issue by cynthn** [Azure/azure-powershell#14532]
## Description of the new feature
src/Compute/Compute/help/Set-AzVM.md

The current description of Set-AzVM only covers a tiny percentage of what the cmdlet can do (mark a VM as generalized). It can also be used to simulate the eviction of a spot VM, redeploy a VM etc. 

## Proposed implementation details (optional)

Can we get a more generic description for this cmdlet? Something that mentions the other abilities? 

Also, there aren't examples of the other abilities either. These would be a "nice-to-have".

FYI - @JagVeerappan @mimckitt

**Comment by axayjo** [comment]
@jaylabell, can you please take a look at this issue?

**Comment by jaylabell** [comment]
Syncs have already occurred with documentation experts. Work still remains on this issue.

**Comment by Sandido** [comment]
ADO [item ](https://msazure.visualstudio.com/One/_workitems/edit/15445638/?triage=true)tracking this work.

**Comment by grizzlytheodore** [comment]
being addressed in this PR: https://github.com/Azure/azure-powershell/pull/19862
