### ISSUE TITLE
AzureRM - Get-AzureRmNetworkSecurityGroup ignoring ErrorAction

### ISSUE THREAD

**Issue by davehodgson** [Azure/azure-powershell#1453]
If I run the code below I would expect to see the text "test" displayed, however instead the text "caught" is displayed.

Based on my understanding of -ErrorAction SilentlyContinue this is not working as intended?

clear
try{
Get-AzureRmNetworkSecurityGroup -Name "TestName" -ResourceGroupName "TestResourceGroup" -ErrorAction SilentlyContinue
Write-Host "test"
}catch{
Write-Host "caught"
}

**Comment by davehodgson** [comment]
Note - I checked with action of Continue, Inquire and Stop and they all result in the exception being throw and caught

**Comment by blumu** [comment]
Same issue with Get-AzureStorageContainer. This breaks all our deployment scripts. Workaround I guess is to use Find-AzureRmResource

**Comment by davehodgson** [comment]
I didn't think that widely in terms of workarounds ;)

Instead I threw the call of Get-AzureRmNetworkSecurityGroup into a function with a try catch block, assessed and checked if there is an error msg (in other areas I've also tested it to see if it was the one I was expecting) if there is then I write out the message to the host and swallow the exception. Not ideal and a bit hacky but I've used the approach with a few different resources that have lost the ErrorAction behaviour

FUNCTION FUNC_RMSecurityGroupExists($secGroupName, $resGroupName){
	try{
		$Error.Clear() > $null
		FUNC_logHost "Security Group Name: $groupName..." > $null
		$test = Get-AzureRmNetworkSecurityGroup -Name $groupName -ErrorAction Stop
		if($test){
			return $true
		}else{
			return $false
		}
	}catch{
		$res = FUNC_ifNoError($Error, "Created $secGroupName")
		if($res){
			return $res
		}else{
			throw $_
		}
	}
}

In there are a couple of helper functions FUNC_logHost  just calls write-host but wraps some formatting around it for me, the other is below

FUNCTION FUNC_ifNoError ($error, $message = ""){
		if($error){
			FUNC_formatErr($error)
			$error.Clear() > $null
			return $false
		}else{
			FUNC_logHost $message
			return $true
		}
}

FUNCTION FUNC_formatErr(){
	Write-Output "Error: $($error[0].ToString())"
}

**Comment by blumu** [comment]
Here is the workaround I used which avoids dealing with exception handling:
  $containers = Get-AzureStorageContainer -Context $context
    $c = $containers | where { $_.Name -eq $name }
    if($c) {
        $c
    } else {
        New-AzureStorageContainer -Name $name -Context $context
    }

**Comment by graemechristie** [comment]
I'm also seeing this with Get-AzureRmWebApp, Get-AzureRmAutomationAccount.

**Comment by hovsepm** [comment]
dupe of https://github.com/Azure/azure-powershell/issues/1135 . It is fixed in the latest release.
