### ISSUE TITLE
The Powershell Az module does not have any command to deploy Azure functions from the code, either through zip or container image based

### ISSUE THREAD

**Issue by cjmakwana** [Azure/azure-powershell#14542]
## Description
Please check the documentation https://docs.microsoft.com/en-us/powershell/module/az.functions/get-azfunctionapp?view=azps-5.6.0 and https://docs.microsoft.com/en-us/powershell/module/az.functions/new-azfunctionapp?view=azps-5.6.0. It describes on how we can create a new Azure function app. However, it does not have any Cmdlet to deploy Azure functions from the code or container image.

Whereas, the similar one is available in az cli: https://docs.microsoft.com/en-us/cli/azure/functionapp/deployment?view=azure-cli-latest

Please share the Microsoft Powershell team's plan for Az module.

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by Francisco-Gamino** [comment]
@cjmakwana -- Thank you for reporting this issue. 

This issue is a dup of https://github.com/Azure/azure-powershell/issues/14166. All information regarding enabling this scenario will be tracked at the linked issue.
