### ISSUE TITLE
Add cross tenant support for image gallery in New-AzVmss

### ISSUE THREAD

**Issue by olandese** [Azure/azure-powershell#14551]
Like https://github.com/Azure/azure-powershell/issues/8834 but now for New-AzVmss.

If I try with Az 5.4.0 I get: 

The access token is from the wrong issuer 'https://sts.windows.net/3f06279c-61d8-4e5c-a342-7b3afc4fdcbf/'. It must match the tenant 'https://sts.windows.net/36949361-e840-485b-8457-3dce67337f0c/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/36949361-e840-485b-8457-3dce67337f0c' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back 
later.

**Comment by axayjo** [comment]
@olayemio, can you please take a look at this issue?

**Comment by olayemio** [comment]
@olandese, to be able to create a new vmss in another tenant, you will need to log into both tenants

Connect to the source tenant that contains the image, then the target tenant where you will create the VM
```
Connect-AzAccount -SubscriptionId $sourceSubscriptionID -Tenant $sourceTenantID
Connect-AzAccount -SubscriptionId $targetSubscriptionID -Tenant $targetTenantID
```

You can attach your script and I can take a look at it. Before you attach, please make sure to have removed any private information, secrets or identifying data

**Comment by olandese** [comment]
@olayemio this is the script I am using:

# Common
$LOC = "westeurope"
$RGName = "vmss"
# New VMSS Parameters
$VMSSName = "VMSSname"

$principalid = "xxxxxxxxxxxxxxxxxxxxxxx"
$secret = "xxxxxxxxxxxxxxxxxxxxxxx"
$tenantid_source = "xxxxxxxxxxxxxxxxxxxxxxx"
$tenantid_destination = "xxxxxxxxxxxxxxxxxxxxxxx"

$ImageReferenceId = "/subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/apt/providers/Microsoft.Compute/galleries/xxxxxxx/images/xxxxxxx/versions/xxxxxxx"

$password = $password = ConvertTo-SecureString $secret -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential ($principalid, $password)

Clear-AzContext -Force
Connect-AzAccount -ServicePrincipal -Credential $credential -Tenant $tenantid_source
Connect-AzAccount -ServicePrincipal -Credential $credential -Tenant $tenantid_destination

New-AzResourceGroup -Name $RGName -Location $LOC -Force

New-AzVmss `
  -ResourceGroupName $RGName `
  -Location $LOC `
  -VMScaleSetName $VMSSName `
  -VirtualNetworkName "myVnet" `
  -SubnetName "mySubnet" `
  -PublicIpAddressName "myPublicIPAddress" `
  -LoadBalancerName "myLoadBalancer" `
  -UpgradePolicyMode "Automatic" `
  -Image $ImageReferenceId

NB:

The principal I am using has Contributor rights on both the subscriptions

**Comment by olayemio** [comment]
@olandese On which line are you getting the error message? 
If you are encountering the error on the two lines starting with Connect-AzAccount, try adding the flag "-SubscriptionId" along with the respective subscription ids that you are trying to use for your source and destination

**Comment by olandese** [comment]
I did a test with -SubscriptionId, same error :(
The error happens at the New-AzVmss line

**Comment by olayemio** [comment]
@olandese Thank you for the update. I'll investigate this further with our PowerShell team.

**Comment by olayemio** [comment]
@olandese We have this on our roadmap to fix it in the upcoming semester. I will provide an ETA on this thread at end of July 2021.

**Comment by olayemio** [comment]
We are targeting end of September to support cross-tenant deployment with image gallery in New-AzVmss

**Comment by Drewm3** [comment]
This fix is taking a little longer than initially expected, but it is scheduled to be fixed in the current sprint. I'll update this thread when I have a better ETA from development on when the fix will be rolled out.

**Comment by Drewm3** [comment]
Update on status: The work is still continuing on this issue, but it is not yet completed.

**Comment by navba-MSFT** [comment]
@olandese Apologies for the late reply. We are looking into this issue. We will update this thread once we have more details. In the meantime, if you need any further assistance on this issue, do let us know.

@Drewm3 Could you please provide an update on the fix ? Awaiting your reply.

**Comment by Drewm3** [comment]
This new feature is expected to be released in the April release of Azure Cmdlets.

**Comment by sandeepraichura** [comment]
This feature is now released, I will go ahead and close this item now.  Please reopen if there are additional issues.
