### ISSUE TITLE
Enable-AzFrontDoorCustomDomainHttps -SecretVersion cannot be $null but has to be " "

### ISSUE THREAD

**Issue by Xentraxx** [Azure/azure-powershell#14564]
## Description

Just recently we got the opportunity to use "latest" as Certificate Version in the Azure GUI of Frontdoor.
Now I wanted to set it through `Enable-AzFrontDoorCustomDomainHttps`.
As it should default to "latest", I wanted to leave the -SecretVersion property away but it is mandatory.
I tried to put in "latest" which didn't worked without any error message.
So I tried a space (" ") which worked.
If I change the SecretVersion in the Azure GUI to "latest" and get the SecretVersion through Get-AzFrontDoorFrontendEndpoint then the SecretVersion property is $null.

I therefore have two possible values of the SecretVersion property which default to "latest".
1. $null (from the Azure Webinterface)
2. " " as the property is mandatory by the Az.FrontDoor module which prevents me from setting it to $null

My suggestion would be to just make the SecretVersion property optional (which defaults to $null, so "latest") so we don't have to work with the space which creates inconsistencies.

Edit: The Azure Frontend interprets a space as no value set, which doesn't switch to "latest" in the dropdown menu but seems to behave like "latest" by default.
Also the warning "The domain '*****' has enabled HTTPS with your own certificate and specific secret version. To avoid potential downtime, we suggest to set the Secret Version to 'Latest' to always use the latest version from Azure Key Vault."
 does not disappear with a space.

**Comment by briantre** [comment]
+1
I ran into this issue today as well.

**Comment by Xentraxx** [comment]
I ran some more tests and I was wrong. A space does not behave like "latest". It seems to just take the newest certificate version when using `Enable-AzFrontDoorCustomDomainHttps`. But after it doesn't provision a new Certificate when I create a new Version. So that means it is not possible to use the "latest" feature with the module as it is.

**Comment by ShaunFS** [comment]
I also ran into this issue

**Comment by Xentraxx** [comment]
I wanted to did some more testing to see how "latest" set by the Azure Webinterface behaves. So I set a Frontend to latest, wrote a script which polls the "CustomHttpsProvisioningSubstate" property via  "Get-AzFrontDoorFrontendEndpoint" in a loop and uploaded a new cert version. I couldn't see any provisioning of the new version for around 2 hours. Does anyone has more information on how often Azure checks for a new certificate version?

**Comment by t-bzhan** [comment]
@Xentraxx , the issue should be fixed with https://github.com/Azure/azure-powershell/pull/14765.

Regarding to the question:
How often Azure checks for a new certificate version?

I am checking with my teammate and will reply once I get the conclustion.

**Comment by t-bzhan** [comment]
@Xentraxx , it takes up to 24 hours to reflect the new version of certificate.
