### ISSUE TITLE
Set-AzAksCluster can't upgrade cluster

### ISSUE THREAD

**Issue by aelij** [Azure/azure-powershell#14583]
## Description
The following command:

```powershell
Set-AzAksCluster -InputObject $cluster -KubernetesVersion $KubernetesVersion
```

Produces an error:
> The request format was unexpected, a non-UserAssigned identity type should not contain: userAssignedIdentities

The same command works in az CLI:
```
az aks upgrade -n $ClusterName -g $ResourceGroup -k $KubernetesVersion -y
```

This looks like a serialization issue where the `userAssignedIdentities` property gets propagated with an empty array rather than `null`.

## Steps to reproduce

See above.

## Environment data

Using ARM [deployment script](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-script-template) `AzurePowerShell` mode version `5.5`.

## Module versions

See above.

## Debug output

Unfortunately I can't repro it since the cluster has since been upgraded using az CLI.

**Comment by dingmeng-xue** [comment]
@aelij , thanks for reporting. We cannot reproduce the issue in house. It may be service not stable at that moment. Could you try again? In addition, please share debug log to us. You can turn on it via `$DebugPreference = "Continue"`.

**Comment by aelij** [comment]
@dingmeng-xue As I said above, the cluster has been upgraded so I can't check again.

In your repro, did you use a cluster with user-assigned MIs?

**Comment by wyunchi-ms** [comment]
Hi @aelij , I cannot reproduce this issue in current version of Aks. Please feel free to reopen this issue if you have any question.

**Comment by wyunchi-ms** [comment]
https://github.com/Azure/azure-cli/blob/f4428d4ca813c0d16cb5da576979c40e4671939c/src/azure-cli/azure/cli/command_modules/acs/custom.py#L4089
