### ISSUE TITLE
AzureRM Get-AzureStorageContainer ignoring ErrorAction

### ISSUE THREAD

**Issue by davehodgson** [Azure/azure-powershell#1458]
As per #1453 the same issue affects this commandlet Get-AzureStorageContainer

**Comment by trondhindenes** [comment]
The entire arm module implements error-handling incorrectly. There are several issues posted on the matter already. The team is aware, but I'm stunned that it's taking them so long to solve this major bug.

**Comment by devigned** [comment]
This should be resolved this week with the December release of Azure PowerShell. 

I'm closing this to track through previous created issue(s).
