### ISSUE TITLE
Get-AzStorageAccount : Argument passed in is not serializable.

### ISSUE THREAD

**Issue by SanjanaSriram94** [Azure/azure-powershell#14592]
## Description
I have created a new PowerShell script which connects to storage account for downloading the blob. The script is as follows:

## Code
$storageAccountList = Get-AzStorageAccount | Where-Object { $_.StorageAccountName -ieq $storageAccountName}
$storageAccount = $storageAccountList | Where-Object { $_.StorageAccountName -ieq $storageAccountName }
$storageAccountContext = **Get-StorageContext** -resourceGroupName $storageAccount.ResourceGroupName -storageAccountName $storageAccountName

Get-AzStorageBlobContent -Blob $dbBackpac `
        -Container $containerName `
        -Destination $databaseFolder `
        -Context $storageAccountContext `
        -Force
Note: Get-StorageContext this is the custom function which will return the Storage account context.

##Problem
The above code works when executed from powershell. But when I'm calling this script from Jenkins Pipeline It throws me error as:
![image](https://user-images.githubusercontent.com/20287152/111621778-63c97980-880e-11eb-96b4-461c1fdf15fa.png)

##Configuartion in Jenkins
![image](https://user-images.githubusercontent.com/20287152/111621918-8e1b3700-880e-11eb-82a4-9733400c6dd2.png)
Can someone please help me why the pipeline gives error.
Note: AZ 3.7 is installed in jenkins server.

**Comment by dingmeng-xue** [comment]
This issue should be the same as #14556. We will release the new version of Az.Accounts in the next week. Please help to verify that.

**Comment by dingmeng-xue** [comment]
I'm closing this issue. Please raise question on this issue if you still meet the problem.
