### ISSUE TITLE
Register-AzAutomationScheduledRunbook parameter "-Parameters" is changing the hashtable received as argument

### ISSUE THREAD

**Issue by ShowMeTheGita** [Azure/azure-powershell#14597]
## Description

The cmdlet Register-AzAutomationScheduledRunbook has a parameter called "-Parameters" that accepts a hashtable, per the documentation. In the most recent update the values inside the hashtable passed as arguments to the -Parameter are modified with random characters such as backslashes and apostrophes.
A key-value pair inside a hashtable can be 

$var1 = @{Email = "example@company.com" }

After passing to -Parameter it becomes \\"example@company.com\"\

## Steps to reproduce

```powershell

$params = @{
    Email = $Email
    FirstName = $FirstName
    LastName = $LastName
    PhoneNumber = $PhoneNumber
    Birthday = $Birthday
    City = $City
    Company = $Company
}

Register-AzAutomationScheduledRunbook -Name "RunbookToSchedule" -ScheduleName "aschedulename"  -Parameters $params -AutomationAccountName "Automation-account-name" -ResourceGroupName "resourcegroupname" | Out-Null

```

## Environment data

```
Azure automation workers
```

## Module versions

![imagem](https://user-images.githubusercontent.com/72092270/111687196-e7d92c80-8821-11eb-8726-a8f3c68d4716.png)

## Debug output

![imagem](https://user-images.githubusercontent.com/72092270/111687519-430b1f00-8822-11eb-8c6a-ed18bf3edea9.png)

## Error output

```
n/a, scheduled script breaks due to receiving invalid parameters
```

**Comment by dingmeng-xue** [comment]
@ShowMeTheGita , Thanks for reporting. Recently we have fixed a regression. Could you show us the version of Az.Automation or try the latest version?

**Comment by ShowMeTheGita** [comment]
@dingmeng-xue I believe it's 1.5.0 per the screengrab attached, is it not? From my understanding the Azure runbook workers import the modules from the module during runtime, meaning that should be the one

**Comment by HiroyukiSakoh** [comment]
I had the same problem, and upgrading from 1.5.0 to 1.5.1 solved it.

**Comment by ShowMeTheGita** [comment]
Upgraded to 1.5.1 although haven't tested yet. I'll close due to @HiroyukiSakoh feedback. Thanks.
