### ISSUE TITLE
New-AzFunctionApp creates without Host Key

### ISSUE THREAD

**Issue by prawnz** [Azure/azure-powershell#14606]
## Description
When a new function app is created via the New-AzFunctionApp command. The _master and default host keys are missing cause function app functions url not able to be generated/appear

## Steps to reproduce
Replace the placeholders with known values
```
Connect-AzAccount
New-AzFunctionApp -Name $funcName -PlanName $planName -ResourceGroupName $rgName -StorageAccountName $stName -Runtime Powershell -ApplicationInsightsName $appiName 
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```
    Directory: C:\Program Files\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     5.6.0                 Az                                  Core,Desk
```

**Comment by Francisco-Gamino** [comment]
Hello @prawnz -- Thank you for reporting this issue. Unfortunately, the Az.Functions cmdlets do not have support creating a function. We only support creating a function app, which is the container for the functions, and this is the reason why no master and default host keys are generated. 

We have this issue (https://github.com/Azure/azure-powershell/issues/10915) to track adding cmdlets to manage Functions. 

cc: @stefanushinardi @AnatoliB

**Comment by SatishBoddu-MSFT** [comment]
Hello @Francisco-Gamino, @prawnz  Could you please let us know if this issue is good to be closed?

Apologies for the delayed response. I see that this issue is opened a long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know.

**Comment by navba-MSFT** [comment]
@prawnz Apologies for the late reply. I was able to run this PS command and get the Default and master keys. Could you please run [New-AzFunctionApp ](https://docs.microsoft.com/en-us/powershell/module/az.functions/new-azfunctionapp?view=azps-7.1.0) command and test the behavior again ? Awaiting your reply.

**Comment by prawnz** [comment]
@navba-MSFT 

> @prawnz Apologies for the late reply. I was able to run this PS command and get the Default and master keys in my newly created functionapp. Could you please run [New-AzFunctionApp ](https://docs.microsoft.com/en-us/powershell/module/az.functions/new-azfunctionapp?view=azps-7.1.0) command and test the behavior again ? Awaiting your reply.

Same function used last time no longer works 
![image](https://user-images.githubusercontent.com/3827044/151958854-9fbafd15-c248-47b4-ad3c-ef14fba86d9e.png)

**Comment by Francisco-Gamino** [comment]
This issue does not repro. When you create a new function app via the `New-AzFunctionApp` cmdlet, I do see the `_master` and `default` key being generated.  Please reopen if you still see the issue on your side. Thank you.
