### ISSUE TITLE
Artifact build failing with error "already exists for build {ID}"

### ISSUE THREAD

**Issue by Manishd79** [Azure/azure-powershell#14605]
## Description
Checks running as part of PR validations does not support build generation on retry. [Here ](https://dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_apis/build/builds/788712/logs/42) is an example where I am **blocked** due to unable to run the validation.

I searched for any existing discussion and found [this](https://github.com/microsoft/azure-pipelines-tasks/issues/12854). Per recommendation:

**This is currently a limitation of pipeline artifacts. You have a few options: (a) Use publish/download build artifacts tasks instead of publish/download pipeline artifacts. (b) Generate a unique name for your pipeline artifact upon retry (for e.g., by using the System.JobAttempt variable).**

Can it be please looked to implement System.JobAttempt variable for Azure PowerShell pipelines?

**Comment by dingmeng-xue** [comment]
Thanks for your reporting. Due to the priority and the frequency of this problem, we didn't look into it further. Could you try to trigger `/azp run` via UI of PR?
