### ISSUE TITLE
Method for ServicePrinciple to Add/Remove/Update WebApp AppSetting and ConnectionStrings with new ARM cmdlets

### ISSUE THREAD

**Issue by kevinneufeld** [Azure/azure-powershell#1460]
What is the method to for a ServicePrinciple or Azure Account's Default AD User Account to make change main (and slot) settings on a WebApp within a resource group.

It is disappointing that ASM cmdlet are not working for these, Set-AzureWebSite.

Is there a Invoke-AzureRmResourceAction for this?

**Comment by kevinneufeld** [comment]
Found what I was looking for.  `Set-AzureRmWebAppSlot`

See http://stackoverflow.com/questions/32543778/adding-an-app-settings-to-existing-azure-web-application-using-azure-power-shell

**Comment by graemechristie** [comment]
This covers AppSettings, but setting ConnectionStrings doesn't appear to work, and at the very least doesn't appear to be documented. As far as I can tell from the source, the parameter to the -ConnectionStrings argument should be a Hashtable of Name->Connectionstring pairs.

Running 

```
$cloudConnectionStrings=@{"test" = "blahblahblah" }

Set-AzureRmWebAppSlot -Name somewebsite -ResourceGroupName "somewebsite-rg" -ConnectionStrings $cloudConnectionStrings -Slot "Staging" 
```

results in 

```
Set-AzureRmWebAppSlot : Unable to cast object of type 'System.String' to type 'System.Collections.Hashtable'.
At line:74 char:1
+ Set-AzureRmWebAppSlot -Name devbnnhazardspotter -ResourceGroupName "D ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzureRMWebAppSlot], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException,Microsoft.Azure.Commands.WebApps.Cmdlets.DeploymentSlots.SetAzureWebAppSlotCmdlet
```

**Comment by graemechristie** [comment]
Ok, for anyone else who doesn't want to troll through the source, it appears the format for the connection strings is a HashTable of key=>HashTable pairs where the inner hashtable has a "Type" Key Value pair, and a "Value" key value pair (which contains the ConnectionString - Why would would call your key "Value" rather than say - "ConnectionString" is beyond me .. but I digress).

So a working example would be

```
$test=@{"Type"="SQLServer"; "Value"="blahblahblah" }
$cloudConnectionStrings=@{"test"=$test }

Set-AzureRmWebAppSlot -Name somewebsite -ResourceGroupName "somewebsite-rg" -ConnectionStrings $cloudConnectionStrings -Slot "Staging"
```

**Comment by khaledhikmat** [comment]
Thank you sir! I have been breaking my head over this for the last 3-4 hours :-(

**Comment by mikmeh** [comment]
many thanks, I was banging my head trying to figure this out

**Comment by ravetroll** [comment]
Insane.  How come this is not properly documented anywhere!

Well done on finding it.

Set-AzureRMWebAppSlot Unable to cast object of type 'System.String' to type 'System.Collections.Hashtable'

**Comment by tednyberg** [comment]
And for the sake of clarity, any connection strings not specified will be removed.

Worth noting if you intend to update a single connection string among many. :)
