### ISSUE TITLE
PowerShell support for CMK for Automation service

### ISSUE THREAD

**Issue by ghost** [Azure/azure-powershell#14614]
Adding parameters with the automation account cmdlets for supporting CMK - key vault information(name, uri and version), key-source and identity

**Comment by jaspkaur28** [comment]
@sharma224 : This would be available by April End 04/30. The development is in progress.

**Comment by jaspkaur28** [comment]
@sharma224 : Revised ETA for PowerShell support in CMK would be 06/30. We're on track and the public docs would be updated with CMK Powershell details.

**Comment by Jassingh819** [comment]
It is supported now. https://docs.microsoft.com/en-us/powershell/module/az.automation/set-azautomationaccount?view=azps-8.1.0
