### ISSUE TITLE
Az Retry Preference Variable

### ISSUE THREAD

**Issue by vivere-dally** [Azure/azure-powershell#14623]
I have some scripts that work with Azure Resources via the Az Module. I think in a full run, there are around 100 calls to Az cmdlets.

Sometimes for some odd reason, commands fail randomly. This happens rarely but it still does happen. I would say that it happens 2 or 3 times a month. I have no explanation of why it happens or what the solution is. If I try again it works. There is no concurrency issue on my part, the code runs sequentially.

To counter this, I made a RetryHandler and I call functions a number of times until/if they work.  But the thing is that I don't want to get to the point of surrounding each Az cmdlet call with my retry handler.

I thought it would be cool and really helpful (at least in my case) if there would be some Az specific Preference variables like the ones from PowerShell. I thought of: `AzRetryCountPreference` and `AzRetryTimeoutPreference`. Basically, retry with a timeout until the count is met.

**Comment by dingmeng-xue** [comment]
Retry is complicated logic especially new/update operations. We don't support global setting. Could you tell us which cmdlets may have random failure?

**Comment by vivere-dally** [comment]
> Retry is complicated logic especially new/update operations. We don't support global setting. Could you tell us which cmdlets may have random failure?

I think mostly the Publish-AzWebApp cmdlet fails and resource removing like Function Applications and Application Service Plans.

**Comment by dcaro** [comment]
@vivere-dally as mentioned above, the retry logic is different by each service or operations (new or updated may be handled differently). This is one of the reason why we do not have a global retry settings with Az PowerShell. 
We can address changes in the retry logic for the cmdlets with which you are facing issues. In order to simplify the triaging, would you mind opening an issue by module with the affected cmdlets? Please indicate here the issues ids.

**Comment by vivere-dally** [comment]
> @vivere-dally as mentioned above, the retry logic is different by each service or operations (new or updated may be handled differently). This is one of the reason why we do not have a global retry settings with Az PowerShell.
> We can address changes in the retry logic for the cmdlets with which you are facing issues. In order to simplify the triaging, would you mind opening an issue by module with the affected cmdlets? Please indicate here the issues ids.

@dcaro I understand. I was thinking of some wrapper that retries every command sent but I'm not aware of the complex scenarios. 

About the cmdlets that were troublesome, unfortunately, I don't have the errors thrown w/ the ids and all that. It's been a while since I worked on them and I've wrapped them in a retry logic and forgot about them. I was made aware of this issue when I saw performing some delete operations on Azure Functions w/ `Remove-AzFunctionApp` recently, but I didn't log those either. When I will encounter them again, I will open an issue for sure.

**Comment by dcaro** [comment]
@Francisco-Gamino FYI

**Comment by Francisco-Gamino** [comment]
Hello @vivere-dally -- I am from the Functions team. Thank you for reporting this issue(s). 

Regarding the Remove-AzFuncitionApp, I am not aware of any issues when trying to remove a function app. However, if you encounter any next time you use the cmdlets, please let us know. I would suggest using the `Remove-AzFunctionApp` with the `-PassThru` parameter given that this cmdlet does not output anything by default.

Regarding the Publish-WebApp cmdlet, we are aware the sometimes this cmdlet fails to publish. I will be writing a new cmdlet `Publish-AzFunctionApp` to publish a function app. This new cmdlet will ship with the Az.Functions module. In this cmdlet, we will support retries, for more info please see: https://github.com/Azure/azure-powershell/issues/14166.
