### ISSUE TITLE
Add Microsoft.Compute/diskAccesses to support private link feature

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#14625]
## Description of the new feature

Microsoft.Compute/diskAccesses needs to be added to support private link feature in Network.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-12-01/disk.json

**Comment by BethanyZhou** [comment]
After confirmation, DiskRP team is asking for the private link support for Microsoft.Compute/diskAccesses with api version 2020-09-30. It has been onboarded to private endpoints in the time when we scanned all available swaggers last month. Close as finished.
