### ISSUE TITLE
No documentation for Login-AzureRmAccount usage in China

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#1463]
I tried with my china account xxxx.hidden.partner.onmschina.cn for Login and it gives me the bellow error.

This doesn't look like a valid user ID
Try using your email address or phone number

Thanks,
Pradebban Raja

**Comment by hovsepm** [comment]
@Pradebban  Are you providing a user name in a valid email format?

**Comment by sunbeams001** [comment]
@Pradebban Actually, you are trying to log in azure us with your china account, which is the default environment when the parameter "Environment" not provided.
Try this instead
Login-AzureRmAccount -EnvironmentName AzureChinaCloud

**Comment by Pradebban** [comment]
I know how to use it and come over the issue. The bug title is very clear on "No documentation for Login-AzureRmAccount usage in China"

**Comment by markcowl** [comment]
Need online help example for national clouds and some popinters from the getting started docs on azure.com

**Comment by twitchax** [comment]
Closing in favor of [Azure/azure-docs-powershell#274](https://github.com/Azure/azure-docs-powershell/issues/274).

**Comment by TaraMeyer** [comment]
@twitchax  why is this an issue in the docs repo?  This fix must be made upstream in the MDs in your source repo in order for this fix to flow into future releases.  Additionally, I don't even know who the contact is for this module or what module this cmdlet belongs to.
