### ISSUE TITLE
Linux build pipelines randomly fail

### ISSUE THREAD

**Issue by dagoroz** [Azure/azure-powershell#14636]
Hi
I opened this PR #14631 and the linux pipelines fail seemingly at random.

after I pushed my changes the linux build gave a negative result but after retriggering with "git commit --allow-empty" it passed but then after deleting __comments__ it failed again.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We have reported the issue to owner of image. https://github.com/actions/virtual-environments/issues/3034

**Comment by wyunchi-ms** [comment]
Fixed when upgrade Powershell to 7.0.6.
