### ISSUE TITLE
Standard_GZRS in Azure PowerShell is not supported

### ISSUE THREAD

**Issue by katsuya-0409** [Azure/azure-powershell#14633]
I want to use Azure Powershell to create a function that specifies Standard_GZRS storage.
In the Azure Portal,I can create functions that specify storage for Standard_GZRS.
However, When I try to use Azure PowerShell to create the Functions that specify storage for Standard_GZRS
I get the following error and cannot create it.

Error:
Storage type 'Standard_GZRS' is not allowed'. Currently supported storage options: Standard_GRS, Standard_RAGRS, Standard_LRS, Standard_ZRS, Premium_LRS

 

PowerShell commands:
New-AzFunctionApp -Name ushida0316fun -ResourceGroupName rsg-ushida -PlanName 0316ushidaplan -StorageAccount ushida0316stri -Runtime DotNet -FunctionsVersion 3

I thank this issue exists in the Functions Help Library, ZGRS needs to be added.
azure-powershell/HelperFunctions.ps1 at master · Azure/azure-powershell (github.com)
$constants["AllowedStorageTypes"] = @('Standard_GRS', 'Standard_RAGRS', 'Standard_LRS', 'Standard_ZRS', 'Premium_LRS')

Please take a look at this.
PS. CLI has ths same issue.

**Comment by Francisco-Gamino** [comment]
Thank you @katsuya-0409 for reporting this issue. We will look into this.

**Comment by Francisco-Gamino** [comment]
@stefanushinardi -- could you please confirm that we support `Standard_GZRS` storage accounts? If we do, we also need to fix this in the Az CLI.

cc: @gzuber

**Comment by Francisco-Gamino** [comment]
Hi @stefanushinardi -- Could you please confirm if the Portal supports `Standard_GZRS` storage accounts? Thanks.

**Comment by SatishBoddu-MSFT** [comment]
Hello @stefanushinardi Could you please help us in this matter?

I see that this issue is opened a long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed.
