### ISSUE TITLE
Add-AzEnvironment needs to be updated to make use of the added keyvault/storage suffixes

### ISSUE THREAD

**Issue by abbhar** [Azure/azure-powershell#14638]
## Description
Add-AzEnvironment needs to be updated to make use of the added keyvault/storage suffixes

**Comment by dingmeng-xue** [comment]
Hi @abbhar, could you explain further about the requirement?

Current cmdlet supports you add environment with customized `StorageEndpoint` and `AzureKeyVaultDnsSuffix`

**Comment by abbhar** [comment]
We want to add this support in Azs-Tzl branch for azure stack customer.

**Comment by dingmeng-xue** [comment]
@abbhar , this logic is implemented in Azure PowerShell common. If you use the latest version of Az.Accounts, it should be already supported. Please ping if you want to share more information.
