### ISSUE TITLE
Add-AzureRmDnsRecordConfig conversion error with DnsRecordSet

### ISSUE THREAD

**Issue by mcm-ham** [Azure/azure-powershell#1464]
Steps to reproduce

```
Login-AzureRmAccount
New-AzureRmDnsZone -Name contoso.com -ResourceGroupName MyAzureResourceGroup
New-AzureRmDnsRecordSet -Name "@" -RecordType "MX" -ZoneName "contoso.com" -ResourceGroupName "MyAzureResourceGroup" -Ttl 3600
$rs = Get-AzureRmDnsRecordSet -ResourceGroupName MyAzureResourceGroup -ZoneName contoso.com -RecordType MX
Add-AzureRmDnsRecordConfig -Exchange "mail.contoso.com" -Preference 0 -RecordSet $rs
```
I then get this error:
`Add-AzureRmDnsRecordConfig : Cannot convert 'Microsoft.Azure.Commands.Dns.DnsRecordSet' to the type 'Microsoft.Azure.Commands.Dns.DnsRecordSet' required by 
parameter 'RecordSet'. Specified method is not supported.`

**Comment by jtuliani** [comment]
The issue here is that you are calling Get-AzureRmDnsRecordSet without specifying the record set name.  The returned object will then be an array of all matching record sets.  And because it's an array, Add-AzureRmDnsRecordConfig fails.

If your change to:
	$rs = Get-AzureRmDnsRecordSet -ResourceGroupName MyAzureResourceGroup -ZoneName contoso.com -RecordType MX -Name "@"
then everything works.

Note, you can also streamline your script as follows:
	Login-AzureRmAccount
	$z = New-AzureRmDnsZone -Name contoso.com -ResourceGroupName MyAzureResourceGroup
	$rs = New-AzureRmDnsRecordSet -Name "@" -RecordType "MX" -Zone $z -Ttl 3600
	Add-AzureRmDnsRecordConfig -Exchange "mail.contoso.com" -Preference 0 -RecordSet $rs

Lastly, don't forget to call Set-AzureRmDnsRecordSet to commit your changes (Add-AzureRmDnsRecordConfig is an off-line operation).

**Comment by mcm-ham** [comment]
Thanks, I'm using `Get-AzureRmDnsRecordSet` because I want to modify an existing record which has worked before but today got that error message and couldn't figure it out. Do you know why the error message doesn't indicate the type was an array i.e. `Cannot convert DnsRecordSet[] to DnsRecordSet`? That would have helped me understand the problem immediately.

**Comment by jtuliani** [comment]
I don't, but I will pass on to our developers to see if they can make this experience better.  I agree, the error wasn't much help!!

**Comment by jtuliani** [comment]
We've made a fix in the September PowerShell release, your original code should work once that ships.
