### ISSUE TITLE
PowerShell cmdlet in an API Management transformation policy

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#14642]
## Description of the new feature

Copied from https://github.com/Azure/azure-powershell/discussions/14536 which was raised by @Ayanmullick

One is able to get Cosmosdb data directly from API Management using steps in [this blog from the PM](https://anthonychu.ca/post/azure-api-management-look-up-user-cosmos-db/).

Example: https://ztech.azure-api.net/cosmos/getdata/41c40e37-f85e-6e34-0d2b-69cfe44e78a0

Could one execute a PowerShell cmdlet to convert the output to HTML in an [API Management Transformation policy](https://docs.microsoft.com/en-us/azure/api-management/api-management-transformation-policies#ConvertJSONtoXML)? Currently, one needs to implement AzFunctions with Cosmosdb binding just to `ConvertTo-HTML`.

<details>

<summary> AzFunctions Run.ps1 </summary>

```ps
using namespace System.Net
param($Request,$CosmosDBinput, $TriggerMetadata)

$Body= [string]($CosmosDBinput|ConvertTo-Html)

Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    StatusCode = [HttpStatusCode]::OK
    Body = $body
    ContentType = "text/html"
})
```

**Comment by mikebudzynski** [comment]
@dingmeng-xue, please contact Azure support for assistance. This repository is limited to bug reports and feature requests.
