### ISSUE TITLE
Powershell connect-azaccount not showing subcriptions

### ISSUE THREAD

**Issue by srinivasrmanthena** [Azure/azure-powershell#14666]
Not able to see subcription  when I connect to Azure using powershell

PS C:\windows\system32> Connect-AzAccount

Account                                  SubscriptionName TenantId                             Environment
-------                                      ----------------       --------                             -----------
smanxxxxxxxx@XXXXX.onmicrosoft.us                  f7af797d-2297-4c42-81c9-837cff79c3ed AzureCloud

This user have owner permission on the subscription not sure  
![Capture](https://user-images.githubusercontent.com/33501240/113209535-cff9a380-9238-11eb-8c3b-77c4f9a1e090.PNG)

**Comment by dingmeng-xue** [comment]
@srinivasrmanthena , thanks for reporting. Couple things you can check in your environment:
1. Please check whether your subscription is in Azure Public cloud. If it is not, for instance, it is under other environment, you need to login with env info `Connect-AzAccount -Environment ...`
2. Please turn on the debug log via `$DebugPreference="Continue"`. If log is long or contains sensitive information, please share it to us by email.

**Comment by srinivasrmanthena** [comment]
Thank you so much 

Connect-AzAccount -Environment  solved the issue .
