### ISSUE TITLE
Install-Package : Access to the cloud file is denied

### ISSUE THREAD

**Issue by Raag007** [Azure/azure-powershell#14664]
C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21

When I try to install Az modules I get this error.

**Comment by dingmeng-xue** [comment]
@Raag007 , thanks for reporting. Installing module from PSGallery needs the new version of `PowerShellGet`. 1.0.0 is too old. Please upgrade it and try again.

**Comment by Raag007** [comment]
@dingmeng-xue - got it, thank you.
