### ISSUE TITLE
[Az.Functions] Use ARM API to get stacks information for functions

### ISSUE THREAD

**Issue by stefanushinardi** [Azure/azure-powershell#14682]
## Description of the new feature
Current implementation uses static list to get stacks information(e.g. [LinuxFunctionsStacks.json](https://github.com/Azure/azure-powershell/blob/5e94a7fd3b2a1357e4c04f2a4cbd60292d720b03/src/Functions/custom/FunctionsStack/LinuxFunctionsStacks.json)). We recently launched ARM api endpoints so that clients could get latest stacks information(i.e. ```https://management.azure.com/providers/Microsoft.Web/functionappstacks?api-version=2020-10-01```)

The ask is to onboard to this API. 

## Proposed implementation details (optional)
cc: @Francisco-Gamino @pragnagopa  for the details

**Comment by pragnagopa** [comment]
Updated description with the right URL for function apps https://management.azure.com/providers/Microsoft.Web/functionappstacks?api-version=2020-10-01

**Comment by pragnagopa** [comment]
cc @AnatoliB

**Comment by Francisco-Gamino** [comment]
We should include this change in the next release of Az.Functions.

cc: @stefanushinardi @AnatoliB

**Comment by Francisco-Gamino** [comment]
This issue has been fixed in the latest release.
