### ISSUE TITLE
Additional properties in command "Get-AzVMSize"

### ISSUE THREAD

**Issue by ericcsinger** [Azure/azure-powershell#14681]
## Description of the new feature
At times, looking online to find the perfect VM size can be incredibly time consuming.  There are so many vm options, each with different attributes, performance, etc.  

In an ideal world, the "Get-AzVMSize" would return properties such as.

- CPU Manufacturer (Intel, AMD, ARM)
- Hyperthreaded: true / false
- Number of real cores vs number of logical cores
- Number of numa nodes
- Cache size
- Cache IOPS
- Cache throughput
- Max disk throughput
- Max disk IOPS
- Max networking throughput
- Gen1 or Gen 2 VM
- Live migration supported
- Benchmark results
- Etc.

Additionally, having a link to the VM details would also be great.

**Comment by Drewm3** [comment]
Hi @ericcsinger, you can get most of these details through the cmdlet Get-AzComputeResourceSku. However you do need to filter by region instead of a specific size.

So the process is:

1. Use Get-AzComputeResourceSku for a specific region
2. Find the VM SKU you are looking for with a where 
3. View the Capabilities


Here is an example for Standard_E8as_v4 in WestUS:
```
PS C:\> Get-AzComputeResourceSku -Location WestUS | where {$_.Name -eq "Standard_E8as_v4"} | select -ExpandProperty Capabilities

Name                                         Value
----                                         -----
MaxResourceVolumeMB                          131072
OSVhdSizeMB                                  1047552
vCPUs                                        8
HyperVGenerations                            V1,V2
MemoryGB                                     64
MaxDataDiskCount                             16
LowPriorityCapable                           True
PremiumIO                                    True
VMDeploymentTypes                            IaaS
vCPUsAvailable                               8
vCPUsPerCore                                 2
CombinedTempDiskAndCachedIOPS                16000
CombinedTempDiskAndCachedReadBytesPerSecond  134217728
CombinedTempDiskAndCachedWriteBytesPerSecond 134217728
CachedDiskBytes                              214748364800
UncachedDiskIOPS                             12800
UncachedDiskBytesPerSecond                   201326592
EphemeralOSDiskSupported                     True
EncryptionAtHostSupported                    True
AcceleratedNetworkingEnabled                 True
RdmaEnabled                                  False
MaxNetworkInterfaces                         4
UltraSSDAvailable                            True
```
