### ISSUE TITLE
New-AzSqlDatabaseExport returns OperationStatusLink null

### ISSUE THREAD

**Issue by castillog** [Azure/azure-powershell#14721]
Sometimes the commmand `New-AzSqlDatabaseExport` returns the `OperationStatusLink`  null and i cant check the status of the export operation with the command `Get-AzSqlDatabaseImportExportStatus`, that expects this field. Im using the version 2.17.0 of the module Az.Sql.

There is another problem too. Sometimes the command `New-AzSqlDatabaseExport` return an error: `The given key was not present in the dictionary`. Despite the error message, the export operation may complete successfully.

The both issues happens ramdomly, not always

**Comment by SatishBoddu-MSFT** [comment]
Hello @castillog Please let us know if this issue still persists?

Apologies for the delayed response. I see that this issue is opened a long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know.
