### ISSUE TITLE
GenerateExternalContributors.ps1 detected special commit incorrectly

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#14724]
## Description

Below 2 commits are considered as external contribution. But it comes from Azure PowerShell team. Please check what is different from other normal PR.

https://github.com/Azure/azure-powershell/commit/2bd57676fb986ca9e64e479656c9fa7357032138
https://github.com/Azure/azure-powershell/commit/8ec95a6ac3c13d681a93fe6a6e94ce3f05e5fa73

**Comment by LucasYao93** [comment]
Done
