### ISSUE TITLE
Runbook fails to call cmdlets within Start-Job scriptblock

### ISSUE THREAD

**Issue by mwc360** [Azure/azure-powershell#14728]
## Description
I have a runbook which has a Start-Job scriptblock for authenticating and connecting to ADLS so that I can implement a timeout on the connection attempt. I have to implement this as occasionally a runbook will timeout after 3 hours of just trying to run Connect-AzAccounts.

Prior to the Start-Job scripblock approach this runbook was working fine, with the scriptblock it works locally on my PC, however now running as the runbook results in may errors which appear related to not being able to import modules.

Since Start-Job creates a new session I called Import-Module on the 3 required modules but this still isn't working. 

## Steps to reproduce

`$TenantId = "XXXXX"
$ResourceGroupName = "XXXXX"
$StorageAccountName = "XXXXX"
$Credential = Get-AutomationPSCredential -Name "XXXXXXX"

            $connectAzTimeout = 30
            $connectAzTimer = [system.diagnostics.stopwatch]::StartNew()

            $connectAzJob = Start-Job -ScriptBlock {
                Import-Module Microsoft.PowerShell.Core -Force
                Import-Module Az.Accounts -Force
                Import-Module Az.Storage -Force
                $connectAz = Connect-AzAccount -Credential $using:Credential -Tenant $using:TenantId -ServicePrincipal
                $storageAccount = Get-AzStorageAccount -ResourceGroupName $using:ResourceGroupName -AccountName $using:StorageAccountName
                $storageContext = $storageAccount.Context
                $storageContext
            }

            Register-ObjectEvent $connectAzJob -EventName StateChanged -SourceIdentifier ConnectAzJobEnd -Action {
               if ($sender.State -eq 'Completed') {
                   $global:storageContext = Receive-Job $connectAzJob    
               } 
            } 

            while (!$storageContext -And $connectAzTimer.Elapsed.TotalSeconds -le $connectAzTimeout) {
                sleep -Seconds 1
            }
`

## Environment data

The following AutomationAccount modules are installed in addition to all of the standard Automation Account modules:
Az.Accounts
Az.Storage

## Error output

`Cannot invoke method. Method invocation is supported only on core types in this language mode. + CategoryInfo : InvalidOperation: (:) [], RuntimeException + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage + PSComputerName : localhost`

`Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified. + CategoryInfo : NotSpecified: (:) [Import-Module], FileNotFoundException + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand + PSComputerName : localhost`

`Could not load file or assembly 'Azure.Core, Version=1.9.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The system cannot find the file specified. + CategoryInfo : NotSpecified: (:) [Import-Module], FileNotFoundException + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand + PSComputerName : localhost`

`The term 'Connect-AzAccount' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. + CategoryInfo : ObjectNotFound: (Connect-AzAccount:String) [], CommandNotFoundException + FullyQualifiedErrorId : CommandNotFoundException + PSComputerName : localhost`

**Comment by dingmeng-xue** [comment]
Thanks for reporting. The error shows the lower version of assembly already loaded into process and higher version cannot be loaded. You can call `Get-Module` to list which module have been imported and then share the assembly list which can be got via `[System.AppDomain]::CurrentDomain.GetAssemblies()`.

**Comment by mwc360** [comment]
I tried to add these into the runbook and get a "The runbook job failed due to a job stream being larger than 1MB" error
I can return Get-Module alone without error.  Not sure how to quickly get the assembly list. 

`ModuleType Version    Name                                ExportedCommands                                              
---------- -------    ----                                ----------------                                              
Script     2.2.7      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Conne...

Binary     1.0        Orchestrator.AssetManagement.Cmd... {Get-AutomationCertificate, Get-AutomationConnection, Get-A...

Script     0.0        Orchestrator.GraphRunbook.Cmdlets   {Invoke-RunbookFlow, New-RunbookFlowJunction, New-RunbookFl...`

From my Automation Account config I can see that Az.Storage is v 3.5.0

**Comment by mwc360** [comment]
I found that the cmdlets invoked within Start-Job are failing because the child job is run as ConstrainedLanguageMode.

Is there any way to work around this? I'm just trying to implement a simple timout of Connect-AzAccount because occasionally this will run for 3 hours without exit which will then timeout the runbook since they can only run for 3 hours. I thought I came up with a good solution to eliminate this but I'm not sure if it's possible without being able to run Start-Job in FullLanguageMode.

Thanks!

**Comment by mwc360** [comment]
To correct my earlier comment, the long running job isn't on Connect-AzAccount, it is on Get-AzStorageAccount. I found the below github thread where people had the same problem.
https://github.com/Azure/azure-powershell/issues/10601
This cmdlet does support running async so this effectively solves my problem so that I don't have to use a runbook w/ Start-Job in full language mode.

Feel free to close the issue. thx

**Comment by dingmeng-xue** [comment]
Thanks for letting us know. Close this issue now.
