### ISSUE TITLE
Update-AzFunctionApp: IdentityID parameter should be an array of string

### ISSUE THREAD

**Issue by Pikabanga** [Azure/azure-powershell#14734]
## Description

Hi!

The Update-AzFunctionApp parameter IdentityID is a string, when it should be a string array. This seems to be a blunder, as the internal NewIdentityUserAssignedIdentity which this module calls handles multiple IDs: https://github.com/Azure/azure-powershell/blob/8bcc63f038501a8e5f58e09e038d3742dd433a27/src/Functions/exports/NewIdentityUserAssignedIdentity.ps1

This would also make it consistent with the description in [the docs](https://docs.microsoft.com/en-us/powershell/module/az.functions/update-azfunctionapp?view=azps-5.7.0):

> Specifies the **list** of user identities associated with the function app.

This would also make it consistent with [New-AzFunctionApp](https://docs.microsoft.com/en-us/powershell/module/az.functions/new-azfunctionapp?view=azps-5.7.0) where IdentityID is a string array.

I believe this could even be changed in a backward compatible way as I belive powershell can handle a string as a string array.

Kind regards

**Comment by Francisco-Gamino** [comment]
Thank you @Pikabanga for reporting this issue. We will look into this. 

cc: @AnatoliB @stefanushinardi

**Comment by Francisco-Gamino** [comment]
This issue has been fixed in the latest Az.Functions release.
