### ISSUE TITLE
Cannot find PSRoleDefinition

### ISSUE THREAD

**Issue by benlavender** [Azure/azure-powershell#14754]
## Description

Hello, trying to create the Microsoft.Azure.Commands.Resources.Models.Authorization.PSRoleDefinition object but the object is not found in the Az module. What's the replacement please? Since AzureRM had this.

## Steps to reproduce

```powershell
$role = [Microsoft.Azure.Commands.Resources.Models.Authorization.PSRoleDefinition]::new()
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.868
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.868
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
5.8.0      Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is compatible with WindowsPowerShell and PowerShell Core....
```

## Debug output

```

```

## Error output

```

Unable to find type [Microsoft.Azure.Commands.Resources.Models.Authorization.PSRoleDefinition].
At line:1 char:9
+ $role = [Microsoft.Azure.Commands.Resources.Models.Authorization.PSRo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Azure...SRoleDefinition:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

```

**Comment by dingmeng-xue** [comment]
@benlavender, you are correct and it is `Microsoft.Azure.Commands.Resources.Models.Authorization.PSRoleDefinition`. But you need to import module at first `Import-module Az.Resources`. Normally, we suggest user to create object via PowerShell cmdlet instead of creating it via CSharp object directly.

**Comment by benlavender** [comment]
> 
> 
> @benlavender, you are correct and it is `Microsoft.Azure.Commands.Resources.Models.Authorization.PSRoleDefinition`. But you need to import module at first `Import-module Az.Resources`. Normally, we suggest user to create object via PowerShell cmdlet instead of creating it via CSharp object directly.

Thanks that resolved it, I've never used this object before and was reading through [this](ttps://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles-powershell#create-a-custom-role-with-the-psroledefinition-object) Azure doc
