### ISSUE TITLE
Unable to execute the script without connecting to login-azurermaccount

### ISSUE THREAD

**Issue by chavavamsi** [Azure/azure-powershell#14764]
## Description
I have a script which is using to deploy the Azure resources and executing the script post authenticating to the azure portal by using login-azurermaccount

To automate the authentication process created profile.json file and included the below line at beginning of the script.
Import-AzureRmContext -Path "C:\Azure\profile.json" 
but still getting the below error:

Set-AzureRmContext : Please provide a valid tenant or a valid subscription.
At C:\Azure Lab\Execute.ps1:20 char:1
+ Set-AzureRmContext -Subscription 'XXXXX prod'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmContext], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand
 
Select-AzureRMSubscription : Please provide a valid tenant or a valid subscription.
At At C:\Azure Lab\Execute.ps1:20 char:1:21 char:1
+ Select-AzureRMSubscription -Subscription "xxxx-xxxx-xxxx-xxxx-5b1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmContext], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand
 
Set-AzureRmContext : Please provide a valid tenant or a valid subscription.
At At C:\Azure Lab\Execute.ps1:20 char:1.ps1:22 char:1
+ Set-AzureRmContext -SubscriptionName 'XXXX prod'

Please advise on this.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Please let us know how you exported/generated profile.json. Which login approach was used before exporting profile.json?

**Comment by chavavamsi** [comment]
Hi There used the below method,

Login-AzureRmAccount 

Enter your Azure credentials
To get your subscription(s) details enter
Get-AzureRmSubscription

Use the subscription id to select the subscription.
Select-AzureRmSubscription -SubscriptionId xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

Save the AzureProfile using the below command
Save-AzureRmProfile -Path "C:\AzureScripts\profile.json"

The json file can be used to login to Azure
Select-AzureRmProfile -Path "C:\AzureScripts\profile.json"

Put this line on top of you .ps1 file, you does not require human input.

**Comment by dingmeng-xue** [comment]
Thanks for your information. I didn't see when you called `Import-AzureRmContext`. Once you `Import-AzureRmContext`, what's the output of `Get-AzureRmContext`? Please share debug message of cmdlet execution. You can turn on debug via `$DebugPreference = "Continue"`

**Comment by chavavamsi** [comment]
@dingmeng-xue Thanks for your time. I have found the solution for this issue. As noticed there is another .json file belongs to different subscription is interrupting the login mechanism.
