### ISSUE TITLE
Get-AzPolicyExemption not working

### ISSUE THREAD

**Issue by durandguru** [Azure/azure-powershell#14775]
Hi,

The command Get-AzPolicyExemption is not working. New-AzPolicyExemption is working.

**Comment by kenieva** [comment]
@durandguru can you provide more information as to how the command is not working? What error are you receiving?

**Comment by durandguru** [comment]
@kenieva I have a couple of exemptions already set. And get-azpolicyexemption did not return any results. (in Cloud shell or with an updated powershell az modules). When I run it, I now i only get 1 exemption. See the screenshot. It looks the command is only working on exemptions set at the subscription level and not at resource group or resource. (before i only had exemptions at resource level.
![image](https://user-images.githubusercontent.com/79765683/115434234-c2688580-a208-11eb-9899-cde3f991d989.png)

**Comment by kenieva** [comment]
Looking at documentation (https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azpolicyexemption?view=azps-5.8.0) it seems that the commands needs -Scope if you want to look at exemptions at a resource group or resource level. In your query, you did not state one so it will just default to the subscription hence only brining exemptions that have the id which starts with /subscriptions/subID

**Comment by durandguru** [comment]
Example 1 in the documentation is then misleading. It says "This command gets all the policy exemptions." I would expect all the exemptions and not limited to the subscription.

I get the other exemptions by providing a scope.

**Comment by kenieva** [comment]
I will investigate to update that the statement to say it gets all the policy exemptions at the given scope.
