### ISSUE TITLE
[Doc] Name parameter for Get-AzContext

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-powershell#14782]
## Description
https://docs.microsoft.com/en-us/powershell/module/az.accounts/get-azcontext?view=azps-5.8.0 states there is `Name` parameter but actual there's no such parameter in cmdlet.

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
Name is a dynamic parameter. Please check.

https://github.com/Azure/azure-powershell/blob/4a500475123abfe70a289c7832f8e473be91e06c/src/Accounts/Accounts/Context/GetAzureRMContext.cs#L154
