### ISSUE TITLE
How to setup the Non-compliance message via PowerShell? #74025

### ISSUE THREAD

**Issue by MauricioZa** [Azure/azure-powershell#14780]
## Description

Hello. How to setup the Non-compliance message via PowerShell ? Thanks !
I am not finding any option in the cmdlet thanks ! I am running 3.4.1 version of Az.Resources  module.
Thanks !

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
Hi @MauricioZa , could you share more about non-compliance message? Any doc about feature or your expectation?

**Comment by Pavithra26-em** [comment]
is there any update on this

**Comment by Pavithra26-em** [comment]
can we able to setup custom non-compliance message for non-compliance resource for azure policy/initiative via policy assignment using power shell script?
