### ISSUE TITLE
WebApp:Import-AzWebAppKeyVaultCertificate does not allow setting the imported certificate resource name

### ISSUE THREAD

**Issue by BertanAygun** [Azure/azure-powershell#14790]
## Description
Import-AzWebAppKeyVaultCertificate command does not have an argument to set the resource name created for the web app certificate in the resource group which causes conflict when used in scripts that work together with portal or previous ARM templates.

The workflow through portal generates an automated name that includes keyvault name and cert name and Import-AzWebAppKeyVaultCertificate command just uses the certificate name and trying to import same thumbprint with a different name fails. In our case we also had set our ARM templates to use a similar naming scheme so in order to start using Import-AzWebAppKeyVaultCertificate command we had to update our ARM templates to ensure resource name matches the auto generated one by the command.

Also example 2 at https://docs.microsoft.com/en-us/powershell/module/az.websites/import-azwebappkeyvaultcertificate?view=azps-5.8.0 mentions a Name argument but it doesn't exist in reality. It would be great to add that so we can control the resource name.

## Steps to reproduce

* Import a certificate from keyvault through portal.
* Import the same certificate through Import-AzWebAppKeyVaultCertificate command.

## Module versions

Az.WebSites 2.5.0

**Comment by Kotasudhakarreddy** [comment]
Thanks for your feedback! Will take a look in to this.
