### ISSUE TITLE
Get-AzureVMAvailableExtension for ARM

### ISSUE THREAD

**Issue by Vijayaraghavanl** [Azure/azure-powershell#1481]
What is the equivalent for Get-AzureVMAvailableExtension command in the latest version of powershell for ARM based VM's? The extensions retrieved from Get-AzureVMAvailableExtension does not seem to work against ARM based VMs.

**Comment by hovsepm** [comment]
@Vijayaraghavanl, it does not exist in ARM. it is ASM only cmdlet.

**Comment by Vijayaraghavanl** [comment]
How can I then know what extensions are available for ARM VMs?

**Comment by Vijayaraghavanl** [comment]
I need this issue to be reopened. There are extensions available for ARM VM's but no way to find out what extensions are available and all properties of the extension so we can utilize them. I need a way to find out available extensions.

**Comment by huangpf** [comment]
Hi @Vijayaraghavanl,

Currently there are two ways --

1) Because the ARM and ASM modes are merged, now you can directly call ```Get-AzureVMAvailableExtension``` to do so, without switching the context;

2) You can also use the following cmdlet to list available extensions: ```Get-AzureRmVMExtensionImage```.
