### ISSUE TITLE
Provide size of key as return in PS Method Get-AzureKeyVaultKey

### ISSUE THREAD

**Issue by nitmatgeo** [Azure/azure-powershell#14819]
The Get-AzureKeyVaultKey PS method des not return the size of the key nor the Add-AzureKeyVaultKey method automatically create versions based on the size specified in the previous version of the key. Am unsure, if the sizing is less relevant? Please advice or help to have this information as return.
**_Purpose:_** Trying to automate key (_HSM & Non-HSM_) generation after key expiry using powershell.

Secondly, I see that MS officially do not mention about below script to return the type of key (Software or HSM, RSA or EC)
```
$keyInVault = Get-AzureKeyVaultKey -VaultName $keyVaultName -Name $keyName
$keyInVault.Key.Kty
```

**Comment by dingmeng-xue** [comment]
Hi @nitmatgeo. `Kty` is type of key. Are you expecting type of key? Size of key is just available when type of key is RSA. https://github.com/Azure/azure-rest-api-specs/blob/1b0ed8edd58bb7c9ade9a27430759527bd4eec8e/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L4544

According to our priority, we have no plan to add features to Azure module. Is it helpful that we add feature to Az.KeyVault?

**Comment by nitmatgeo** [comment]
Is size of key irrelevant for HSM based RSA keys? 
I was expecting both- type & size cuz when I have to auto-generate RSA/RSA-HSM/EC keys upon expiry, then I will have to generate with same spec as last version, right? I mean the type & size should be retained, right?
Please proceed to update in Az as well. But any help with powershell or calling CLI in PS? I am unaware how do I consume the Az.KeyVault. @dingmeng-xue

**Comment by dingmeng-xue** [comment]
According to REST API of keyvault, size is only relevant to RSA key. In API spec I posted, EC-HSM is using Curve parameter. So, you need to set correct parameter according to its type. 

Az.KeyVault is the latest version of Azure PowerShell module. Its usage is similar with Azure. You can find doc from  https://docs.microsoft.com/en-us/powershell/module/az.keyvault/?view=azps-5.8.0

**Comment by nitmatgeo** [comment]
Thanks @dingmeng-xue  I have already upgraded from `Get-AzureKeyVaultKey` to `Get-AzKeyVaultKey`. Can you request the team to do a minor enhancement? Especially when a key is already present and `Add-AzKeyVaultKey` should automatically get the size from last version unless it is mentioned explicitly.

**Comment by dingmeng-xue** [comment]
Target it to next release. It may be adjusted if team has no sufficient bandwidth.

**Comment by nitmatgeo** [comment]
Thanks @dingmeng-xue hope things go well. Please keep me posted, and do the needful 😄 Sufficient to do in Az.KeyVault modules.

**Comment by nitmatgeo** [comment]
@BethanyZhou Can you please confirm if this was deployed & released? I still could not get this information 😕 Maybe I am looking at the wrong place...

**Comment by BethanyZhou** [comment]
Hi @nitmatgeo , 

We released this feature in Az.KeyVault >=3.4.4, please check the Az.KeyVault you are using. The way to get a key size is as following:
![image](https://user-images.githubusercontent.com/19869716/127962668-cba42ed7-0207-41e2-9541-261400782a7e.png)

Thanks for asking, we will refine our docs to provide information for such a feature!

**Comment by nitmatgeo** [comment]
Thanks @BethanyZhou , I just upgraded the Az.KeyVault and I could see. Refining the document would make it perfectly perfect *cheers*
I will drop a comment in case I face further challenges 😄

**Comment by BethanyZhou** [comment]
Please feel free to comment here if any need. 😄

**Comment by nitmatgeo** [comment]
@BethanyZhou A quick check, locally it worked when I upgraded the removed module & installed the new version Az.KeyVault. So when I push this into Az Function with PowerShell runtime, the values are not reflecting. Any advise-
1. How do I upgrade to latest version of Az.KeyVault?  
2. Every time if install the module the run time + usage will get increased, so any workaround?
3. Is v3.x.x in preview or not fully released?

**Comment by BethanyZhou** [comment]
To resolve the values are not reflecting, I suggest upgrading Az.KeyVault in Az Function.

For 1, following command is recommend
```powershell
Install-Module -Name Az.KeyVault -AllowClobber -Force
```
For 2, 3, I believe installing Az.KeyVault once is enough in local environment. Could you provide more information about where you are using Az Function and which module is v3.x.x in preview?

**Comment by nitmatgeo** [comment]
Thanks @BethanyZhou  it helped; I found an alternative by specifying `'Az' = '6.*'` in requirements file of function app which has a default Az.keyVault version of 3.4.x therefore it nullifies my queries 2 & 3.

Meanwhile, I use `Add-AzKeyVaultKey` to generate new key versions; things worked well for RSA keys but for EC keys, am not sure how to generate or retrieve the `-CurveName`? Secondly, can there be a feature enhancement such that whenever a new versions are generated, the API automatically uses the type, size or curve based on immediate last (current) version _(unless the updated values are explicitly specified)?_

**Comment by BethanyZhou** [comment]
Hi @nitmatgeo , please see following steps to retrieve CurveName
![image](https://user-images.githubusercontent.com/19869716/128666670-9bf8ea69-321c-4562-9929-81a068286255.png)

@dingmeng-xue @dcaro Could you help to evaluate this feature request?

**Comment by nitmatgeo** [comment]
Many thanks @BethanyZhou , I just tried it worked earlier i used $key.kty instead of $key.key. Sorry to trouble you again, I wanted to generate a new version of EC key and used below code with and without `-Destination` parameter. I was getting this error- _'Cannot process command because of one or more missing mandatory parameters: KeyFilePath'_. Am I doing it in wrong way?
```
Add-AzKeyVaultKey -VaultName $triggeredKeyVAultName -Name $triggeredKeyName -KeyType $($latestKey.KeyType) -CurveName $($latestKey.Key.CurveName)
```

**Comment by nitmatgeo** [comment]
@dingmeng-xue  @dcaro if the request is sensible, it would be a great help. Right now, I am just stuck trying to generate a newer version of EC key. As per documentation, the `KeyFilePath` parameter should have been optional as I don't intend to import a key.

**Comment by BethanyZhou** [comment]
Hi @nitmatgeo, we do not support creating an EC key in vault. That's why you have to import an EC key by `KeyFilePath`. I suggest you to create another issue about the feature request. We will triage all new issues regularly. I believe this way will speed up response time.

**Comment by nitmatgeo** [comment]
@BethanyZhou Thank you so much, I have opened a new feature request. Fingers crossed 🤞
