### ISSUE TITLE
New-AzureRmResourceGroupDeployment not processing -templateparameteruri

### ISSUE THREAD

**Issue by jeffpatton1971** [Azure/azure-powershell#1483]
Based on the sparse documentation found here (https://msdn.microsoft.com/en-us/library/mt603823.aspx) when I pass in -TemplateParameterUri with a valid web address, it should process the parameters that are defined and pass those into the -TemplateUri.

Am I incorrect in that assumption?

My scenario, I have a blob storage url that contains my json files for my deployment. I am able to point a browser at any of the files and download them so they are accessible. In fact for the purposes of testing, I made them publically available so anyone could grab those if they wanted.

This is what I see
```
New-AzureRmResourceGroupDeployment -Name $Name -ResourceGroupName $ResourceGroupName -TemplateUri $TemplateUri -TemplateParameterUri $TemplateParameterUri -Force -Verbose

cmdlet New-AzureRmResourceGroupDeployment at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
ResourceGroupFromTemplate: 
```
I see this behavior when I run the cmdlet alone and manually enter the cmdline options I need, or when I run this in a script (as above) with variables for the cmdline options I need.

**Comment by jeffpatton1971** [comment]
Updating this, it appears that you get some sort of conflict if you use either ResourceGroup or ResourceGroupName in your templates.
Originally in my template I passed in the name of a resource group and assigned it to a variable ResourceGroup
```
  "parameters": {
    "ResourceGroup": {
      "type": "string"
    },

  "variables": {
    "ResourceGroup": "[parameters('ResourceGroup')]",
```
When I changed that to the following
```
  "parameters": {
    "ResourceGroupName": {
      "type": "string"
    },

  "variables": {
    "ResourceGroup": "[parameters('ResourceGroupName')]",
```
I only got prompted for the ResourceGroupNameFromTemplate, but when I changed it to the following:
```
  "parameters": {
    "Environment": {
      "type": "string"
    },

  "variables": {
    "ResourceGroup": "[parameters('Environment')]",
```
The error went away altogether.

**Comment by ravbhatnagar** [comment]
This is by design. If you have matching parameter names in the cmdlet and the param file, we will append FromTemplate to the parameter name from the template to get its value from the user. 
I guess we need to document this case a little more to raise awareness.

**Comment by utripathi** [comment]
This is not an error . 
This is a required parameter which is to be input at the deployment time .

**Comment by utripathi** [comment]
resourcegroupFromTemplate is a dynamic property which has to be input at deployment time . 

If you enter this parameter in the template file , you get the self explanatory error as below - 

14:35:26 - [ERROR] C:\Users\Administrator.UTN\Desktop\SavedSearch - Copy\GitTemplateDep\bin\Debug\
14:35:26 - [ERROR] staging\GitTemplateDep\Deploy-AzureResourceGroup.ps1 : Cannot retrieve the 
14:35:26 - [ERROR] dynamic parameters for the cmdlet. An item with the same key has already been 
14:35:26 - [ERROR] added.
14:35:26 - [ERROR] At line:1 char:3998
14:35:26 - [ERROR] + $UI = 'VS-'; if (!(Test-Path 
14:35:26 - [ERROR] 'C:\Users\Administrator.UTN\AppData\Roaming\Windows ...

**Comment by simonbMS** [comment]
I had the same problem deploying using files. I had "name" and "ResourceGroupName" in the template AND the parameter files (so no value was missing) but the commandlet kept asking for "NameFromTemplate" and "ResourceGroupNameFromTemplate".
I think it should understand that the value is specified in the parameter file without prompting for it
