### ISSUE TITLE
Authentication - Do Not Automatically Select a Disabled Subscription

### ISSUE THREAD

**Issue by doodlemania2** [Azure/azure-powershell#1484]
Don't automatically select a disabled subscription to work with when performing login-azurermaccount even if it occurs first in the list of returned subscriptions. Causes all further actions to fail. Workaround is to specify an active subscription id in the login-azurermaccount command.

**Comment by markcowl** [comment]
@doodlemania2 Thanks, this fix is scheduled for the next PowerShell release.

**Comment by markcowl** [comment]
fixed per the PR above, closing
