### ISSUE TITLE
Get-AzAdUser - Return more fields including licensing details

### ISSUE THREAD

**Issue by blacktirion** [Azure/azure-powershell#14843]
## Description of the new feature
Please change the Az.Resources and Az.Accounts modules to allow "Get-AzAdUser" and "Set-AzAdUser" to feature match AzureAD Module commands - Allow setting Licensing, fetching attributes such as ImmutableID and more.

## Proposed implementation details (optional)

Following fields are required for just about any Azure AD implementation and scripting:

ImmutableID
AssignedLicenses
AssignedPlans
ProvisionedPlans
ProxyAddresses
ExtensionProperty
ObjectID (May already be in there as "ID", but it should match "ObjectID")
Country, Address, Telephone Etc.
Mail
OnPremiseSecurityIdentifier

Additionally, using the -SearchString Parameter does not function as it should. The proper implementation of this parameter can be seen in AzureAD module. This parameter's functionality should match exactly with what searches can be done via the Azure AD portal.

Lastly, I am not aware of any command in "Az" shell that replicates the following command: Get-AzureADSubscribedSku. If it does exist, it needs to be extended, no doubt.

## Additional Information and comments
I'm opening a new issue regarding this command. There was a previous issue opened regarding this command, but it was closed and looks like it's NOT going to get re-opened.

It appears to be Microsoft's stance to push everyone to use the new "Az" shell. That is fine, but we need more extensibility with this command. Currently, it does not feature match anything from "Get-AzureADUser" nor "Get-MSOLuser"

Additionally, Microsoft has temporarily halted modern authentication requirement for M365 tenants, but I assume this will resume in the future. Currently, "MSOnline" does not natively support Modern Authentication without "PartnerCenter" module, which appears to be stale.

Therefore, our method forward is to either use the "Az" shell, or change scripts over to AzureAD. I don't fancy changing my scripts twice, so I'd rather just convert straight to "Az".

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We are tracking it using existing one https://github.com/Azure/azure-powershell/issues/14568. We are evaluate the effort and considering the priority.
