### ISSUE TITLE
Get-AzAdUser missing properties

### ISSUE THREAD

**Issue by johandanforth** [Azure/azure-powershell#14856]
Get-Azaduser is still pretty much unusable as far as I can see today. So many properties still missing. I wasted 2 hours going down this rabbit hole, because the info on this page recommends using az module: https://docs.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-powershell

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We are tracking it using existing one https://github.com/Azure/azure-powershell/issues/14568. We are evaluate the effort and considering the priority.
