### ISSUE TITLE
Get-AzSynapseTriggerSubscriptionStatus gives the wrong state of the scheduled trigger

### ISSUE THREAD

**Issue by chakravarthil** [Azure/azure-powershell#14851]
## Description

When getting the status of the Triggers in the synapse workspace using the cmdlet Get-AzSynapseTriggerSubscriptionStatus, getting the correct state of the trigger for the event based triggers but not for the schedule based triggers. The cmdlet always returns the state "enabled" even if the trigger is disabled(stopped) either through a script or manually. 

## Steps to reproduce

```powershell

Get-AzSynapseTriggerSubscriptionStatus -WorkspaceName $synwsName -Name $triggerName
```

## Environment data

```
PSVersion                      5.1.19041.906                                                                                                                             
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.19041.906                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                   

```

## Module versions

```powershell

Script     0.10.0     Az.Synapse 
```

## Debug output

```
DEBUG: 10:45:36 AM - GetAzureSynapseTriggerSubscriptionStatus begin processing with ParameterSet 'GetByName'.
DEBUG: 10:45:36 AM - using account id 'xxxx@xxx.com'...
DEBUG: 10:45:36 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxxx@xxx.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-04-29T06:13:58.0000000+00:00
DEBUG: 10:45:36 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxxx@xxx.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-04-29T06:13:58.0000000+00:00
DEBUG: 10:45:36 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxxx@xxx.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-04-29T06:13:58.0000000+00:00
DEBUG: 10:45:36 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxxx@xxx.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-04-29T06:13:58.0000000+00:00
DEBUG: 10:45:36 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxxx@xxx.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-04-29T06:13:58.0000000+00:00
DEBUG: 10:45:36 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxxx@xxx.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-04-29T06:13:58.0000000+00:00
DEBUG: 10:45:36 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxxx@xxx.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-04-29T06:13:58.0000000+00:00
DEBUG: 10:45:36 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxxx@xxx.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-04-29T06:13:58.0000000+00:00
DEBUG: 10:45:36 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxxx@xxx.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-04-29T06:13:58.0000000+00:00
DEBUG: Request [b1a04b11-33bb-4bce-9b0b-18dbbeb98518] POST https://grpsyn.dev.azuresynapse.net/triggers/trigger2/getEventSubscriptionStatus?api-version=REDACTED
Accept:application/json
x-ms-client-request-id:b1a04b11-33bb-4bce-9b0b-18dbbeb98518
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Analytics.Synapse.Artifacts/1.0.0-beta.1 (.NET Framework 4.8.4341.0; Microsoft Windows 10.0.19042 )
Authorization:REDACTED
client assembly: Azure.Analytics.Synapse.Artifacts
DEBUG: Response [b1a04b11-33bb-4bce-9b0b-18dbbeb98518] 200 OK (00.8s)
Pragma:no-cache
Strict-Transport-Security:REDACTED
x-ms-correlation-request-id:REDACTED
X-Content-Type-Options:REDACTED
x-ms-request-id:REDACTED
x-ms-client-request-id:b1a04b11-33bb-4bce-9b0b-18dbbeb98518
Content-Length:45
Cache-Control:no-cache
Content-Type:application/json; charset=utf-8
Date:Thu, 29 Apr 2021 05:15:39 GMT
Expires:-1
Server:Microsoft-IIS/10.0 Microsoft-HTTPAPI/2.0
X-Powered-By:REDACTED


DEBUG: AzureQoSEvent: CommandName - Get-AzSynapseTriggerSubscriptionStatus; IsSuccess - True; Duration - 00:00:00.9290380
DEBUG: Finish sending metric.
DEBUG: 10:45:41 AM - GetAzureSynapseTriggerSubscriptionStatus end processing.
TriggerName Status 
----------- ------ 
trigger2    Enabled
```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. It will be great that you can share the debug message of cmdlet execution. You can turn on it via `$DebugPreference = "Continue"`

**Comment by idear1203** [comment]
I have a event trigger and I can see it is disabled.

```powershell

PS> Get-AzSynapseTrigger -WorkspaceName wsname -Name EventTrigger

WorkspaceName : wsname
Properties    : {}
Id            : /subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.Synapse/workspaces/<ws-name>/triggers/EventTrigger
Name          : EventTrigger
Type          : Microsoft.Synapse/workspaces/triggers
Etag          : 0000000-0000-0000-0000-000000


PS> Get-AzSynapseTriggerSubscriptionStatus -WorkspaceName wsname -Name EventTrigger

TriggerName  Status
-----------  ------
EventTrigger Disabled
```

**Comment by chakravarthil** [comment]
> Thanks for reporting. It will be great that you can share the debug message of cmdlet execution. You can turn on it via `$DebugPreference = "Continue"`

Added the debug output

**Comment by chakravarthil** [comment]
> I have a event trigger and I can see it is disabled.
> 
> ```powershell
> PS> Get-AzSynapseTrigger -WorkspaceName wsname -Name EventTrigger
> 
> WorkspaceName : wsname
> Properties    : {}
> Id            : /subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.Synapse/workspaces/<ws-name>/triggers/EventTrigger
> Name          : EventTrigger
> Type          : Microsoft.Synapse/workspaces/triggers
> Etag          : 0000000-0000-0000-0000-000000
> 
> 
> PS> Get-AzSynapseTriggerSubscriptionStatus -WorkspaceName wsname -Name EventTrigger
> 
> TriggerName  Status
> -----------  ------
> EventTrigger Disabled
> ```

M Az.Synapse module version is 0.10. Do you have anything different?

**Comment by idear1203** [comment]
Mine is also 0.10.0.. From PowerShell perspective, this cmdlet works well. If you think this is not an issue from your side. Please contact support: https://azure.microsoft.com/en-us/support/create-ticket/

**Comment by chakravarthil** [comment]
> Mine is also 0.10.0.. From PowerShell perspective, this cmdlet works well. If you think this is not an issue from your side. Please contact support: https://azure.microsoft.com/en-us/support/create-ticket/

Not really sure. The Az CLI retruns the status correct

(az synapse trigger show --workspace-name wsname--name triggername | ConvertFrom-Json).properties.runtimeState > Stopped

but the Az Powershell returns the status as enabled

Get-AzSynapseTriggerSubscriptionStatus -WorkspaceName wsname-Name triggername 

TriggerName Status 
----------- ------ 
trigger2    Enabled

**Comment by idear1203** [comment]
> > Mine is also 0.10.0.. From PowerShell perspective, this cmdlet works well. If you think this is not an issue from your side. Please contact support: https://azure.microsoft.com/en-us/support/create-ticket/
> 
> Not really sure. The Az CLI retruns the status correct
> 
> (az synapse trigger show --workspace-name wsname --name triggername | ConvertFrom-Json).properties.runtimeState > Stopped
> 
> but the Az Powershell returns the status as enabled
> 
> Get-AzSynapseTriggerSubscriptionStatus -WorkspaceName wsname -Name triggername
> 
> TriggerName Status
> 
> triggername Enabled

The corresponding PowerShell cmdlet of `az synapse trigger show` is `Get-AzSynapseTrigger` rather than `Get-AzSynapseTriggerSubscriptionStatus`. 

You can have a try on the script below:
```ps
(Get-AzSynapseTrigger -WorkspaceName testsynapseworkspace -Name EventTrigger).Properties.RuntimeState
```

**Comment by chakravarthil** [comment]
> > > Mine is also 0.10.0.. From PowerShell perspective, this cmdlet works well. If you think this is not an issue from your side. Please contact support: https://azure.microsoft.com/en-us/support/create-ticket/
> > 
> > 
> > Not really sure. The Az CLI retruns the status correct
> > (az synapse trigger show --workspace-name wsname --name triggername | ConvertFrom-Json).properties.runtimeState > Stopped
> > but the Az Powershell returns the status as enabled
> > Get-AzSynapseTriggerSubscriptionStatus -WorkspaceName wsname -Name triggername
> > TriggerName Status
> > triggername Enabled
> 
> The corresponding PowerShell cmdlet of `az synapse trigger show` is `Get-AzSynapseTrigger` rather than `Get-AzSynapseTriggerSubscriptionStatus`.
> 
> You can have a try on the script below:
> 
> ```postscript
> (Get-AzSynapseTrigger -WorkspaceName testsynapseworkspace -Name EventTrigger).Properties.RuntimeState
> ```

Thanks for this. This returns the correct status. The (Get-AzSynapseTrigger -WorkspaceName testsynapseworkspace -Name EventTrigger).Properties returns empty though. Now whats the difference between the trigger runtime state and the subscription state. For an event trigger if the trigger is started it returns Enabled and Started but for the scheduled trigger it returns stopped and enabled. Both of them are attached to at least one of the pipeline

**Comment by idear1203** [comment]
> The (Get-AzSynapseTrigger -WorkspaceName testsynapseworkspace -Name EventTrigger).Properties returns empty though.

This can be improved in future. It looks empty but in fact it is not empty.. The SDK type `Trigger` doesn't have `ToString` method causing the issue.

> Now whats the difference between the trigger runtime state and the subscription state. For an event trigger if the trigger is started it returns Enabled and Started but for the scheduled trigger it returns stopped and enabled. Both of them are attached to at least one of the pipeline
I am not an expert on this part. I am responsible for Synapse PowerShell only. If you have questions on this. I would suggest you to reach out to Support (See my previous reply)

**Comment by chakravarthil** [comment]
Thanks for all the help
