### ISSUE TITLE
WebApp:Remove-AzWebAppAccessRestrictionRule cannot remove a specific rule if RuleName exists multiple times

### ISSUE THREAD

**Issue by BCOps** [Azure/azure-powershell#14869]
## Description

Scenario - Azure Web app with multiple network restriction rules specified. There are two rules that have matching names (perhaps due to coding error, operator error, or malicious intent to hide a "bad" rule). You can only pass in the web app name, RG name and rule name to the Remove-AzWebAppAccessRestrictionRule cmdlet, which means that it will delete one of the rules but not necessarily the one you want it to. In my testing it appears to delete the rule with the highest priority in the rule list, or if they have matching priorities then the rule higher in the rule list. In some cases, this means that the cmdlet will remove the "good" rule and fail to remove the "bad" rule, potentially making the situation worse temporarily until the cmdlet has been run twice and the "good" rule then put back in place via another method.

Expected behaviour - I would expect the cmdlet to provide an error, as it is unable to find a unique rule to delete. Instead it just selects one of the rules by its own logic, which seems dangerous.

Desired behaviour - If there was a rule ID provided, a more targetted removal could be performed. Without such an ID, or more filtering options such as Rule Name, Rule Action, Address, etc. this specific removal cannot occur when there are matching rule name rules present.

## Steps to reproduce

Prepare a web app in advance.

```powershell
$webAppRG = <ResourceGroupHere>
$webAppName = <WebAppNameHere>
$ruleName = <RuleNameHere>
$action = deny

Add-AzWebAppAccessRestrictionRule -ResourceGroupName $webAppRG  -WebAppName $webAppName  -Name $ruleName -Description "Deny $ruleName inbound" -IpAddress ""8.8.8.8/32"" -Priority 100 -Action $action -Confirm:$false
Add-AzWebAppAccessRestrictionRule -ResourceGroupName $webAppRG  -WebAppName $webAppName  -Name $ruleName -Description "Deny $ruleName inbound" -IpAddress ""4.4.4.4/32"" -Priority 100 -Action $action -Confirm:$false

Remove-AzWebAppAccessRestrictionRule -Name $rogueRule.RuleName -ResourceGroupName $functionApp.ResourceGroup -WebAppName $functionApp.Name -Confirm:$false
```
One of the rules will be deleted, but you have no control over which one as the rule names both match, so if you wanted to choose to only delete 4.4.4.4/32 you have no way to specify this.

## Environment data

```

```

## Module versions

Using MS hosted public ADO agent VM of type "windows-latest"

```powershell

```

## Debug output

```

```

## Error output

No error messages are received.

```

```

**Comment by Kotasudhakarreddy** [comment]
@BCOps for removing `Deny` rules you should explicitly specify the `-Action` attribute. Because if we don't specify anything command would consider the `Action="Allow"` by default. Indeed the document should be updated for it. We will take it as another git issue. Please re-try with `-Action "Deny"` .

**Comment by BCOps** [comment]
@Kotasudhakarreddy thanks for the update. It makes sense that your suggested approach would work for rules that have the same name but different actions (so I would be able to provide additional "uniqueness" by passing the action allow/deny to specify which one I wanted to delete).
In a scenario where two rules had the same name and same action though, but maybe a different IP address, would it then be required to pass in additional information such as the `-IPAddress` flag to ensure the correct rule was deleted?

**Comment by panchagnula** [comment]
@madsd can you comment on this ask here?

**Comment by madsd** [comment]
Hi @BCOps. The unique identifier of a rule is the IP Address, Service Tag or subnet id, so to remove a rule deterministic you should just not specify the name. That being said, I can actually see, that we have an issue in the logic if you do specify both name and e.g. IP. I will fix that and resolve this bug with it when ready.

**Comment by BCOps** [comment]
@madsd thanks for the update. I appreciate the extra info around the process and thank you for looking into the logic further! :)
