### ISSUE TITLE
Connect-AzAccount default context (subscription

### ISSUE THREAD

**Issue by chughesvf** [Azure/azure-powershell#14872]
## Instead of this: 
`WARNING: TenantId '7ba8d2fb-4660-4a19-802e-4d015a17e167' contains more than one active subscription. First one will be selected for further use. To select another subscription, use Set-AzContext.` 

after connect-azaccount allow me to configure which subscriptionid I want to default context into on a new connection to Azure

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will evaluate it.

**Comment by dingmeng-xue** [comment]
We are thinking to introduce configuration in Az.Accounts. We hope to reach this feature in this year.

**Comment by jonbe16** [comment]
Connect-AzAccouint is also ignoring the -ContextName parameter and still displays the defaulted context setting warning.

Connect-AzAccount -Credential $cred -ContextName $contextname
WARNING: TenantId 'XXXXX' contains more than one active subscription. First one will be
selected for further use. To select another subscription, use Set-AzContext.

**Comment by jonbe16** [comment]
> Connect-AzAccouint is also ignoring the -ContextName parameter and still displays the defaulted context setting warning.
> 
> Connect-AzAccount -Credential $cred -ContextName $contextname
> WARNING: TenantId 'XXXXX' contains more than one active subscription. First one will be
> selected for further use. To select another subscription, use Set-AzContext.

With -SubscriptionName and -TenantId the warning is not displayed.

**Comment by dingmeng-xue** [comment]
We have released AzConfig in Az 8. Please try it and share your thought 

https://docs.microsoft.com/en-us/powershell/module/az.accounts/update-azconfig?view=azps-8.0.0#example-1

**Comment by chughesvf** [comment]
> We have released AzConfig in Az 8. Please try it and share your thought
> 
> https://docs.microsoft.com/en-us/powershell/module/az.accounts/update-azconfig?view=azps-8.0.0#example-1

Tried it out! Worked great for this github request!

**Comment by dingmeng-xue** [comment]
It's great. Close this item now.
