### ISSUE TITLE
Get-AzResource missing information from siteconfig area for webApps

### ISSUE THREAD

**Issue by vitaliypidodnya** [Azure/azure-powershell#14877]
Get-AzResource -ResourceId ... retrieve properties for the object with subproperties.
It looks ok for storage accounts, keyvaults, etc...
But for any webapp, it retrieves properties in siteconfig with null values.
Get-AzWebApp  - works as expected.

**Comment by dingmeng-xue** [comment]
WebApp team, is there any work which needs to be completed on service side?

**Comment by panchagnula** [comment]
SiteConfig is not part of Site API which is by design please use the webapp specific commands.
