### ISSUE TITLE
The checking result of availability of communication name is not right

### ISSUE THREAD

**Issue by zhhaovm** [Azure/azure-powershell#14893]
Please refer to the browser logs attached. I used https://docs.microsoft.com/en-us/rest/api/support/supporttickets/create to create support ticket and use 
https://docs.microsoft.com/en-us/rest/api/support/communications/checknameavailability to check the availability of the communication name. It should report not available. But it reports available.

[Archive.zip](https://github.com/Azure/azure-powershell/files/6416219/Archive.zip)

**Comment by dingmeng-xue** [comment]
Thanks for reporting. This repo is mainly focusing on Azure PowerShell module. Please share cmdlet you are using and debug message of cmdlet execution. Debug log can be turn on via `$DebugPreference = "Continue"`

If it should report available but it should not be available, please share the result of `Get-AzSupportTicketCommunication`

**Comment by zhhaovm** [comment]
Please refer to the attachments. I used API from https://docs.microsoft.com/en-us/rest/api/support/communications/checknameavailability. I expect nameAvailable is false.

<img width="1679" alt="Screen Shot 2021-05-05 at 8 44 31 PM-1" src="https://user-images.githubusercontent.com/83559905/117239453-a1488d00-ade3-11eb-807c-92b44f265c63.png">
<img width="1680" alt="Screen Shot 2021-05-05 at 8 46 05 PM-2" src="https://user-images.githubusercontent.com/83559905/117239465-a7d70480-ade3-11eb-91a5-195751fcd5e4.png">

**Comment by dingmeng-xue** [comment]
Snapshot is showing REST API. Current repo is only for Azure PowerShell. I checked Az.Support module but it doesn't support checking availability. This is not correct place to discuss this issue.

Per my understanding, `checkNameAvailability` API is used to check the availability of supportticket. If you want to check availability of communication, you should call POST https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Support/supportTickets/{supportTicketName}/checkNameAvailability?api-version=2020-04-01

**Comment by shahbj79** [comment]
@zhhaovm - we are tracking this internally and investigating.

**Comment by shahbj79** [comment]
Thanks @zhhaovm for reporting this issue. The fix is being deployed.
