### ISSUE TITLE
New-AzPolicyAssignment does not assign Managed Identity IAM on scope

### ISSUE THREAD

**Issue by omerzubair** [Azure/azure-powershell#14890]
## Description

When you run following command. It does not assign IAM at the scope (tried subscription and resource group.)

$policyAssignment = New-AzPolicyAssignment -Name $policyDisplayNameRegion -PolicyDefinition $policyDefinition `
	-Scope $subscriptionResId  `
	**-AssignIdentity** -Location 'australiacentral' `
	-PolicyParameterObject $policyAssignmentParams 

Also tried searching the identity it returns. But cannot find it in directory.

Get-AzADApplication | Where -Property ObjectID -eq $policyAssignment.Identity.principalId

## Steps to reproduce

$policyAssignment = New-AzPolicyAssignment -Name $policyDisplayNameRegion -PolicyDefinition $policyDefinition `
	-Scope $subscriptionResId  `
	**-AssignIdentity** -Location 'australiacentral' `
	-PolicyParameterObject $policyAssignmentParams 

Get-AzADApplication | Where -Property ObjectID -eq $policyAssignment.Identity.principalId

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by kenieva** [comment]
Hi @omerzubair, have you manually configured the identity? Information here: https://docs.microsoft.com/en-us/azure/governance/policy/how-to/remediate-resources#manually-configure-the-managed-identity

**Comment by omerzubair** [comment]
Hi @kenieva, thanks for guidance. 
- You are correct when using powershell you must assign the IAM using another command to apply managed identity on scope. 
- Furthermore i noticed that when using powershell for assignment reason there is a limit is 'casue it creates an enterprise application behind the scene. [thats good as we now have a name of enterprise application rather than horrable unchangeable  GUID for enterprise application] however when i looked at the policy assignment itself and found there is no **Assignment Name**? is there a way to apply a full assignment name?

**Comment by kenieva** [comment]
Are you able to clarify what you mean by when you looked at the assignment there was no assignment name? 

The Powershell script has both -Name and -DisplayName. Information here: https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azpolicyassignment?view=azps-5.8.0

**Comment by omerzubair** [comment]
Hi @kenieva ![image](https://user-images.githubusercontent.com/7728453/116954396-4293ee00-acd3-11eb-97b3-24ae612da548.png)So i tried the -DisplayName and that sets the AssignmentName in policy and does not have char limt.
however -Name switch complains when its is > 64 chars. This switch sets the Enterprise application behind the scene. 
I know Enterprise application does not have char limit of 64 chars.

 		$policyAssignment = New-AzPolicyAssignment -DisplayName $policyAssignmentNameRegion -Name $policyEnterpriseApplicationName `
			-PolicyDefinition $policyDefinition `
			-Scope $policyScope  `
			-AssignIdentity -Location 'Australia Central' `
			-PolicyParameterObject $policyAssignmentParams `
			-Description "NSG Flow logs Location ['$($storage.Location)'] in Storage Account:['$($storage.ResourceId)']"

![image](https://user-images.githubusercontent.com/7728453/116954324-0eb8c880-acd3-11eb-920f-7f70d1aea0d9.png)

**Comment by kenieva** [comment]
Yes, the limit of the assignment name is due to other limitations (i.e. subscriptions)
