### ISSUE TITLE
Documentation for Import-AzurePublishSettingsFile provides an out of date example

### ISSUE THREAD

**Issue by jasonmitchell** [Azure/azure-powershell#1492]
Running "get-help import-azurepublishsettingsfile -examples" displays an example of using the -SubscriptionDataFile parameter to save the data file to an alternative location however this is no longer supported.  This example should be removed from the documentation as it is misleading.

See [this commit](https://github.com/Azure/azure-powershell/commit/83206989c3fb9d178ea274a114eaa70b36db4647) for the initial deprecation notice.

**Comment by markcowl** [comment]
Fixed.
