### ISSUE TITLE
How to add security rules to an existing Network Security Group?

### ISSUE THREAD

**Issue by timmayg** [Azure/azure-powershell#1494]
Hi all,

I cannot figure out how to add a rule to an NSG that already exists...

I've tried both New-AzureRmNetworkSecurityRuleConfig  and Add-AzureRmNetworkSecurityRuleConfig and it appears to create the object with a Provisioning State of null.  Then I've tried to Set-AzureRmNetworkSecurityRuleConfig.   However the rule never gets added.... 

Can someone please help me understand this process?

Thank you !

**Comment by devigned** [comment]
@deepakswifty can you provide some guidance here?

**Comment by DeepakRajendranMsft** [comment]
Hi @timmayg, 

Add-AzureRmNetworkSecurityRuleConfig  and Set-AzureRmNetworkSecurityRuleConfig create in-memory objects. You would have to call Set-AzureRmNetworkSecurityGroup to commit your state to the service. For example.

$nsg = Get-AzureRmNetworkSecurityGroup
$nsg | Add-AzureRmNetworkSecurityRuleConfig <parameters>
$nsg | Set-AzureRmNetworkSecurityGroup

(or) if you want to put them all in one line 

Get-AzureRmNetworkSecurityGroup <parameters> | Add-AzureRmNetworkSecurityRuleConfig | <parameters> | Set-AzureRmNetworkSecurityGroup

Thanks,
Deepak.

**Comment by timmayg** [comment]
Hi Deepak,   Thanks very much!   This worked perfectly.

**Comment by ronbok** [comment]
So this post was made back in December of 2015 and yet the documentation on this cmdlet still has not been updated with even one example:  https://msdn.microsoft.com/en-us/library/mt603772.aspx

**Comment by markjbrown** [comment]
Previously reported https://github.com/Azure/azure-powershell/issues/70 Will track from that issue. Thanks.

**Comment by gnot** [comment]
I wonder what it takes to add complete contextual examples, best practices for each of the PS commands. Or in case of NSG rules - adding a requirement "please run set command after doing everything in memory".

**Comment by 1scscott** [comment]
Is there a way to update an existing NSG with new rules in .JSON format?

**Comment by JeremyTBradshaw** [comment]
+1 to the json question for existing NSG's by @1scscott.
