### ISSUE TITLE
Azure Generalized VM is still dumb and at large behaviour by design. Fix it. Now

### ISSUE THREAD

**Issue by Porkechebure** [Azure/azure-powershell#14940]
#1978
https://github.com/azure/azure-powershell/issues/1978

From here.

Created a snapshot from my vm and now it's generalized and it's fucked up. Can't boot anymore.
Can't created disks and vm from disks as proposed by someone.

I had a testing VM, and BAM! Roasted.
Congratulations to the IDIOT who designed this. Give me the name I will get to his home and cripple some of his limbs with a spiked bat.

Now, serious time, how to solve?
No hacks, give a real solution to this BUG/VIRUS. Whoever says this is good and by design is an idiot so only who is an intelligent person please reply

Also, creating new VM from the image resulted in 

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"OSProvisioningClientError","message":"OS Provisioning for VM 'IDA-VM2' did not finish in the allotted time. However, the VM guest agent was detected running. This suggests the guest OS has not been properly prepared to be used as a VM image (with CreateOption=FromImage). To resolve this issue, either use the VHD as is with CreateOption=Attach or prepare it properly for use as an image:\r\n * Instructions for Windows: https://azure.microsoft.com/documentation/articles/virtual-machines-windows-upload-image/ \r\n * Instructions for Linux: https://azure.microsoft.com/documentation/articles/virtual-machines-linux-capture-image/ "}]}

**Comment by dingmeng-xue** [comment]
Thanks for your reporting. I understood your suffering. But Azure PowerShell is a project of a client tool. We have no information about what happen on service side. It's not an easy task to make REST API calls transitional. Could you update your description and provide us which cmdlets you are using and what debug message is from service? 

Your comments in #1978 will be deleted. I will keep this issue open for couple days and delete it if its description is not polished.

**Comment by Porkechebure** [comment]
> Thanks for your reporting. I understood your suffering. But Azure PowerShell is a project of a client tool. We have no information about what happen on service side. It's not an easy task to make REST API calls transitional. Could you update your description and provide us which cmdlets you are using and what debug message is from service?
> 
> Your comments in #1978 will be deleted. I will keep this issue open for couple days and delete it if its description is not polished.

Then move the issue  section or tell me which such section is.

Problem is simple. UI is unclear about an important options and screws up your VM. No need to prove it, just check the issue I quoted, someone just added another comment about this.

**Comment by dingmeng-xue** [comment]
@dcaro , please look into it and check whether we can improve some areas.

**Comment by dcaro** [comment]
@Porkechebure thanks for the feedback, I have created an issue that aims at addressing several feedbacks that we have received on the usability of the `Set-AzVM` cmdlet, including additional warning message and improved documentation.
Let us know if you have any concerns about the proposed approach.

**Comment by dingmeng-xue** [comment]
Close this one and track improvement by #15183
