### ISSUE TITLE
Get-AzKeyVaultKey - How to get EncryptionType and Length

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#14954]
Hey there,

how can I fetch with Powershell these Attributes from the Portal?

`Get-AzKeyVaultKey` will not work for that.

![image](https://user-images.githubusercontent.com/25774289/117816619-fb73a300-b266-11eb-8fa7-05b12de5a6fc.png)

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We are tracking this requirements via https://github.com/Azure/azure-powershell/issues/14819. If no surprise, those properties will be available soon.
