### ISSUE TITLE
Get-AzSentinelAlertRuleTemplate fails with "Value cannot be null"

### ISSUE THREAD

**Issue by challengelogic** [Azure/azure-powershell#14983]
## Description

Trying to run  **Get-AzSentinelAlertRuleTemplate**  to return the Analytics Templates in Azure Sentinel 

PS C:\WINDOWS\system32> $sourceTemplates = Get-AzSentinelAlertRuleTemplate -ResourceGroupName $sourceRgName -WorkspaceName $sourceLaName

Get-AzSentinelAlertRuleTemplate : **Value cannot be null.**
Parameter name: source
At line:1 char:20
+ ... Templates = Get-AzSentinelAlertRuleTemplate -ResourceGroupName $sourc ...
    + CategoryInfo          : CloseError: (:) [Get-AzSentinelAlertRuleTemplate], ArgumentNullException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.SecurityInsights.Cmdlets.AlertRulesTemplates.GetAlertRuleTemplate
 

I have run: **Update-Module Az.SecurityInsights**

Version after update is: **0.2.0 Az.SecurityInsights**

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dicolanl** [comment]
investigating with @challengelogic 
https://github.com/Azure/azure-powershell/issues/14545
