### ISSUE TITLE
[Az.Blockchain] Retirement message 

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#14999]
## Description
Following the announcement of the [Azure Blockchain service retirement](https://docs.microsoft.com/en-us/azure/blockchain/service/migration-guide) we plan to update Az.BlockChain module:

[ ] Update Az.BlockChain module release notes
[ ] Update the modules PSD1
[ ] Update list of Az PowerShell modules - https://github.com/Azure/azure-powershell/blob/master/documentation/azure-powershell-modules.md

**Comment by dingmeng-xue** [comment]
@dcaro, I prefer to the first 2 items in upcoming release. Regarding documentation,  https://github.com/Azure/azure-powershell/blob/master/documentation/azure-powershell-modules.md is just one. We need to remove their cmdlet reference together. We need to update azure-powershell-modules.md when we delete this module from repo.

**Comment by dingmeng-xue** [comment]
Following items will be tracked by https://github.com/Azure/azure-powershell/issues/15233
