### ISSUE TITLE
[Functions][Stacks] Support hidden stacks

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-powershell#15002]
Please note that currently Powershell stack on Linux is marked as Hidden - https://github.com/Azure/azure-functions-ux/blob/42fba774382c6f72b76e65f428a36189f46abbdc/server/src/stacks/2020-10-01/stacks/function-app-stacks/Powershell.ts#L40

This is a feature request to allow creating stacks marked as Hidden only if user requests by passing an explicit flag. We intend to mark stacks as Hidden while the backend changes are rolling out. Having support for hidden flag gives ability for the product team to test E2E while backend changes are rolling out.

cc @stefanushinardi @Francisco-Gamino @AnatoliB

**Comment by pragnagopa** [comment]
Related issue: https://github.com/Azure/azure-powershell/issues/14682

**Comment by Francisco-Gamino** [comment]
We already support this in the Az.Functions cmdlets. To see hidden runtimes for function app creation, the user must set `$env:DisplayHiddenRuntimes = $true` before importing the module.
