### ISSUE TITLE
Unable to update function app settings using Set-AzWebAppSlot 

### ISSUE THREAD

**Issue by rajakcava** [Azure/azure-powershell#15024]
## Description
We were using `Set-AzWebAppSlot` to update application settings for a function app. I like to understand if there is any change in the cmdlet as we recently experience issue where the cmdlet executed successfully but the new application settings are not added to the function app settings. 
We tried for both `staging` and `production` slot and had the same result. 

Really appreciate if some one can advise on any change for the `cmdlet`.

**Comment by panchagnula** [comment]
Webapp commands shouldn't be used for Function apps.  Tagging functions team to help.

**Comment by pointsbet-preston** [comment]
@DanielLarsenNZ  Seems we already have a issue raised.

**Comment by srrl** [comment]
Same here

**Comment by pointsbet-preston** [comment]
Enabling this parameter seems to be a walk around until MS get it resolved   **-Use32BitWorkerProcess $true**

**Comment by leshy84** [comment]
It's duplicate for https://github.com/Azure/azure-powershell/issues/14998

**Comment by SatishBoddu-MSFT** [comment]
Hello @rajakcava Apologies for the delayed response. I see that this issue is opened a long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know.

**Comment by panchagnula** [comment]
@SatishBoddu-MSFT & @rajakcava  WebApp commands are not meant for FunctionApp - I will let the function App folks comment on an alternate command but this is by design.

**Comment by rajakcava** [comment]
Thank You @panchagnula we are currently using the work around suggested in earlier comment by @pointsbet-preston . Please let me know the alternate command/approach that we can use. Thank You !

**Comment by panchagnula** [comment]
@Francisco-Gamino what is the command in PS to use for Function Apps here, the customer is using WEbApp commands which is not recommended for function apps.

**Comment by navba-MSFT** [comment]
@rajakcava Apologies for the delay in response. Could you please leverage the PS command [Update-AzFunctionAppSettings ](https://docs.microsoft.com/en-us/powershell/module/az.functions/update-azfunctionappsetting) and see if that helps ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@rajakcava Hope you had chance to look at my above comment. Please run the PS command [Update-AzFunctionAppSettings ](https://docs.microsoft.com/en-us/powershell/module/az.functions/update-azfunctionappsetting?view=azps-7.1.0) to update the app settings in function app and that should serve your requirement. With that, I am proceeding with closure of this github thread. If you need any further assistance on this, please feel free to reopen this thread. We would be happy to address your issues.
