### ISSUE TITLE
Get-AzKeyVaultSecret does not get the full certificate (as originally uploaded).  Missing CA Chain

### ISSUE THREAD

**Issue by mbactol3** [Azure/azure-powershell#15026]
## Description
After uploading a full PFX (cert, ca-chain, and private key) to azure keyvault, the certificate ca-chain is NOT included in the PFX when using Az.Keyvault module to retrieve certificate.

## Steps to reproduce
- Upload a full PFX (cert, ca chain, and private key) to Azure Keyvault using portal or powershell.
- Use documented instructions to download PFX via powershell https://docs.microsoft.com/en-us/powershell/module/az.keyvault/get-azkeyvaultcertificate?view=azps-5.9.0
```powershell
$cert = Get-AzKeyVaultCertificate -VaultName "ContosoKV01" -Name "TestCert01"
$secret = Get-AzKeyVaultSecret -VaultName $vaultName -Name $cert.Name -AsPlainText
$secretByte = [Convert]::FromBase64String($secret)
$x509Cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($secretByte, "", "Exportable,PersistKeySet")
$type = [System.Security.Cryptography.X509Certificates.X509ContentType]::Pfx
$pfxFileByte = $x509Cert.Export($type, $password)
# Write to a file
[System.IO.File]::WriteAllBytes("KeyVault.pfx", $pfxFileByte)
```
- The resulting PFX does NOT include the ca chain.  
  - Downloading from the portal DOES include the ca chain in the PFX.  
  - Downloading via az cli (az keyvault secret download) DOES include the ca chain. 

## Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.906
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.906
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
3.3.0      Az.KeyVault
```

## Debug output

N/A

## Error output

N/A

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will look into it and check what is missed.

**Comment by BethanyZhou** [comment]
Hi @mbactol3 , I uploaded a self-signed certificate to key vault and followed the steps you provided to reproduce. Differently, I got the CA chain from the downloaded pfx.
![image](https://user-images.githubusercontent.com/19869716/119099197-3c2ea180-ba49-11eb-8a72-63e302e88650.png)

Could you provide more details to reproduce this issue?

**Comment by mbactol3** [comment]
Thanks Bethany,

While the certificate path is correct, when installing the pfx, the chain certificate is not installed.  In this example screenshot, the **R3 certificate** (highlighted) is **NOT** in the cert store after installing the certificate I retrieved via powershell.  
This example shown is the cert store after I download the pfx via az cli and installed, which includes the cert chain.  
As an added note: the download from az cli is 5kb in size and doing the same via powershell the pfx ends up being 4kb

![image](https://user-images.githubusercontent.com/40409637/119739692-71ffcb80-be37-11eb-9753-086395f2536e.png)

**Comment by BethanyZhou** [comment]
Thanks for your continuous inputs. Could you provide the detailed steps you download pfx from az cli?

**Comment by mbactol3** [comment]
Sure, see below.

`az keyvault secret download --vault-name "$keyVaultName"  --name "$certName" --file "fullCert.pfx" --encoding base64`

**Comment by BethanyZhou** [comment]
Hi @mbactol3 , thanks for your help!

We can get full pfx files same result with az cli and portal by using following steps:
```
$cert = Get-AzKeyVaultCertificate -VaultName $vaultName -Name $certName
$secret = Get-AzKeyVaultSecret -VaultName $vaultName -Name $cert.Name -AsPlainText
$secretByte = [Convert]::FromBase64String($secret)
[System.IO.File]::WriteAllBytes("ps.pfx", $pfxFileByte)
```
Please have a try.

**Comment by mbactol3** [comment]
This appears to have worked, I will keep testing on my end but initial findings are successful!

Thanks Bethany, I appreciate the time, and effort.
