### ISSUE TITLE
Add "Enable Storage Analytics or diagnostics" to storage account creation

### ISSUE THREAD

**Issue by leakkari** [Azure/azure-powershell#15041]
## Description of the new feature

Problem:
About 30 to 40 cases per month are getting closed and resulting in DSAT because they don't get resolved. This is due to the customer having storage analytics/diagnostics disabled. These logs are needed for troubleshooting. The customer is then told to enable storage analytics/diagnostics to avoid this problem in the future. This is impacting CSAT.

Ask:
Add the option to enable storage analytics/diagnostics when creating a storage account through PS.

**Comment by blueww** [comment]
@leakkari 
For "enable storage analytics/diagnostics", please give the detail of which storage account related properties do you want to set, and what's the target value to set?
