### ISSUE TITLE
Documentation for New-AzureRmVpnClientRootCertificate

### ISSUE THREAD

**Issue by lpassig** [Azure/azure-powershell#1505]
PublicCertData Parameter has no documentation. I guess the input must be the Base64-Coded string of the certificate but I haven't found a proper documentation. 

Also the CmdLet: "Add-AzureRmVpnClientRootCertificate" for adding the root certificate to the VPNGateway does not seem to work as well as "Get-AzureRmVpnClientPackage".

Cheers, 
Lennart

**Comment by markjbrown** [comment]
This is documented here, https://msdn.microsoft.com/en-us/library/mt653593.aspx
