### ISSUE TITLE
Az module installation taking too long time

### ISSUE THREAD

**Issue by vparna** [Azure/azure-powershell#15080]
Hi Team, 
we see the Install-Module AZ -Force is taking over 18 minutes on a 100GB network connectivity. Could you please let me know if there is a way to speedup this installation. Have also observed that eventhough the AZ module is installed on the machine still it takes quite bit of time to install.

**Comment by dingmeng-xue** [comment]
`Install-Module` is correct cmdlet to install Azure PowerShell modules. `-Force` means to install version no matter the same module already exists on the computer or not.

However, all 120 Azure powershell modules so far is 65M totally. 100G network connectivity is informal. The whole installation needs couple minutes. 18 minutes is a little long. Could you check network connectivity of just installing Az.Accounts? If it is big, please share the log of Install-Module.

We also provide MSI package. You can install it on your machine directly.

**Comment by colhal** [comment]
Hi,
I too had the issue taking 18 min+ to install the modules using import-module Az -Scope AllUsers -Force. All Az modules were uninstalled first using uninstall-module cmdlet. Installing on PS 7.1.3 was quick.

PS T:\> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.19041.906
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.906
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by dingmeng-xue** [comment]
Thanks. The implementation of install module is taken cared by PowerShellGet. Please log issue to https://github.com/PowerShell/PowerShellGet/issues.

**Comment by vparna** [comment]
thank you !!. Have verified Az.Accounts is taking less time. will update code accordingly. Please close this thread.

**Comment by dingmeng-xue** [comment]
Thanks. Close it now.
