### ISSUE TITLE
 enable Publish-AzWebapp to publish apps other than ROOT.

### ISSUE THREAD

**Issue by YusukeTobo** [Azure/azure-powershell#15087]
## Description of the new feature
Regarding kudu API, wardeploy can deploy a war file other than ROOT context like `foo#bar` by `name` query parameter. But, it appears not to handle this scenario in azure-powershell. Could you consider expanding Publish-AzWebapp to cover the query parameter.

https://github.com/projectkudu/kudu/wiki/Deploying-WAR-files-using-wardeploy#deploying-to-apps-other-than-root
https://github.com/Azure/azure-powershell/blob/master/src/Websites/Websites/Cmdlets/WebApps/PublishAzureWebApp.cs#L64

**Comment by panchagnula** [comment]
Sorry we are working on new API support after which this command will be updates no plans for the requested feature currently.
