### ISSUE TITLE
Add `-UserData` option to `Set-AzVMOperatingSystem`

### ISSUE THREAD

**Issue by schnerring** [Azure/azure-powershell#15093]
## Description of the new feature

> [User data through Azure Instance Metadata Service now generally available](https://azure.microsoft.com/en-us/updates/user-data-through-azure-instance-metadata-service-now-generally-available/):
> 
> Today, we are announcing the general availability of user data, enabling you to insert your own metadata into a Microsoft Azure virtual machine at **provisioning time**, with the ability to retrieve it using the Azure Instance Metadata Service (IMDS).

Azure Portal supports that feature:

![image](https://user-images.githubusercontent.com/3743342/119405744-482c9480-bcd1-11eb-8a64-d42af27dd7db.png)

[And so do ARM templates](https://docs.microsoft.com/en-us/azure/virtual-machines/user-data#create-user-data-for-azure-vmvmss)

I couldn't find an issue regarding that feature for the Azure PowerShell, though.

## Proposed implementation details (optional)

Add the `-UserData` option to `Set-AzVMOperatingSystem` to be able to provide user data at provisioning time.

**Comment by Vaibhav-Agar** [comment]
Hi @bilaakpan-ms, seems like a parity gap between powershell and other clients. Can you please take a look?

**Comment by bilaakpan-ms** [comment]
> Hi @bilaakpan-ms, seems like a parity gap between powershell and other clients. Can you please take a look?

ack.

**Comment by Sandido** [comment]
Hi @schnerring , 
Is there a particular reason you want UserData added to Set-AzVmOperatingSystem? 
I don't think it is an OS value specifically. 
Please let me know if the below work handles your scenario.

I recently completed work for a UserData parameter in many of our Vm, Vmss, and VmssVm cmdlets. This work was released in Az.Compute PS module [4.21.0](https://www.powershellgallery.com/packages/Az.Compute/4.21.0). 

The above work allows users to set the UserData before and when creating or updating a Vm/Vmss/VmssVm. It also allows users to toggle if the UserData is returned in the Get cmdlets for those resources given the UserData could be quite long.

**Comment by Sandido** [comment]
@schnerring , 
I'm going to go ahead and close this issue. The above linked Az.Compute PS release of 4.21.0 has UserData added to New-AzVm, Update-AzVm, and many other cmdlets. I think that will bring us to parity with the other workflows. 
I am not convinced that Set-AzVmOperatingSystem should also have UserData,

**Comment by schnerring** [comment]
The only thing I remember from half a year ago was that the Azure CLI (`az vm create`), Azure PowerShell and Azure Portal had a feature disparity regarding user data.

I think I made an error when copying the respective command. I think I meant `New-AzVm`, so it's fine to close this. Thanks!

**Comment by jaylabell** [comment]
> The only thing I remember from half a year ago was that the Azure CLI (`az vm create`), Azure PowerShell and Azure Portal had a feature disparity regarding user data.
> 
> I think I made an error when copying the respective command. I think I meant `New-AzVm`, so it's fine to close this. Thanks!

Thank you for letting us know @schnerring!
