### ISSUE TITLE
Update-AzADApplication loses IdentifierUri if already set on the Application

### ISSUE THREAD

**Issue by florinangelescu** [Azure/azure-powershell#15134]
When using the cmdlet to update the ReplyUrls (for example):
`Update-AzADApplication -ObjectId "12345" -ReplyUrls "https://reply"`
If an IdentifierUri was already set on the app, it will get removed after the above cmdlet is ran.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. It's a regression issue. We will fix it quickly. Sorry for inconvenience.

https://github.com/Azure/azure-powershell/blob/5d223e1196c8aabb34bcaadba2538c330c218494/src/Resources/Resources/ActiveDirectory/Cmdlets/UpdateAzureADApplicationCommand.cs#L103

One workaround for the time being is to get identifierUris from existing app and set it together with replyUri.
