### ISSUE TITLE
Azure Az import-Az-Context from json not working on azure devops

### ISSUE THREAD

**Issue by darkweb-123** [Azure/azure-powershell#15157]
Steps to reproduce:
1. Create an Azcontext json file.(Save-AzContext -Path filename.json)
2. import the context . Import-AzContext -Path filename.json

Issue :
WARNING: Unable to acquire token for tenant 'TenantID' with error 
'SharedTokenCacheCredential authentication failed: MSAL V3 Deserialization failed to parse the cache contents. Is this 
possibly an earlier format needed for DeserializeMsalV2? (See https://aka.ms/msal-net-3x-cache-breaking-change). '

Both Subscription and tenent is valid

**Comment by dingmeng-xue** [comment]
We will look into it.

**Comment by msJinLei** [comment]
> Steps to reproduce:
> 
> 1. Create an Azcontext json file.(Save-AzContext -Path filename.json)
> 2. import the context . Import-AzContext -Path filename.json
> 
> Issue :
> WARNING: Unable to acquire token for tenant 'TenantID' with error
> 'SharedTokenCacheCredential authentication failed: MSAL V3 Deserialization failed to parse the cache contents. Is this
> possibly an earlier format needed for DeserializeMsalV2? (See https://aka.ms/msal-net-3x-cache-breaking-change). '
> 
> Both Subscription and tenent is valid

@darkweb-123 
Could you provide more information of the issue?

```
1. Create an Azcontext json file.(Save-AzContext -Path filename.json)
2. import the context . Import-AzContext -Path filename.json
```
Between step 1 and 2, do you clean the current context?

Since the issue occurs on devops, could provide more about devops setting? Here is an example https://github.com/Azure/azure-powershell/blob/master/.azure-pipelines/powershell-core.yml

Can the issue be reproduced in you local machine?

**Comment by darkweb-123** [comment]
Hi @msJinLei  
I have cleared the context using clear-AzContext , and  There are no issues when I  tried the same context file from my local system .

In azure devops , I have tried all the supported agents (Ubuntu and Windows)

**Comment by msJinLei** [comment]
> Hi @msJinLei
> I have cleared the context using clear-AzContext , and There are no issues when I tried the same context file from my local system .
> 
> In azure Devops, I have tried all the supported agents (Ubuntu and Windows) .
> 
> Just to add ,
> 1.The context file is a stored on an azure blob storage .
> 2. I am using curl to download the file from azure blob.
> 3. Then I am using this file to do some resource specific activity.
> 
> Also I have tried all the three steps in my local system it it working fine .
> 
> From a pipeline perspective i just have a powershell task with the below mentioned steps:
> 
> * Install-Module Az -Force -AllowClobber -SkipPublisherCheck -RequiredVersion 5.1.0
> * curl  " SAS_TOKEN" -o $env:AGENT_BUILDDIRECTORY/mycontext.json
> * Clear-AzContext -Force
> * import-AzContext -Path $env:AGENT_BUILDDIRECTORY/mycontext.json
> * Set-AzContext -SubscriptionId  -TenantId
> 
> **Additional_Info:**
> The Context file is downloaded successfully from blob , and these are woking in my local system

Thanks for your response. Since devops env is very special, we will check your case first.

**Comment by msJinLei** [comment]
> Hi @msJinLei
> I have cleared the context using clear-AzContext , and There are no issues when I tried the same context file from my local system .
> 
> In azure Devops, I have tried all the supported agents (Ubuntu and Windows) .
> 
> Just to add ,
> 1.The context file is a stored on an azure blob storage .
> 2. I am using curl to download the file from azure blob.
> 3. Then I am using this file to do some resource specific activity.
> 
> Also I have tried all the three steps in my local system it it working fine .
> 
> From a pipeline perspective i just have a powershell task with the below mentioned steps:
> 
> * Install-Module Az -Force -AllowClobber -SkipPublisherCheck -RequiredVersion 5.1.0
> * curl  " SAS_TOKEN" -o $env:AGENT_BUILDDIRECTORY/mycontext.json
> * Clear-AzContext -Force
> * import-AzContext -Path $env:AGENT_BUILDDIRECTORY/mycontext.json
> * Set-AzContext -SubscriptionId  -TenantId
> 
> **Additional_Info:**
> The Context file is downloaded successfully from blob , and these are woking in my local system

@darkweb-123, followup questions,
- what system do you try to save the context? windows? linux? linux with desktop or not?
- Do you manage to import the context json file in local windows , linux and linux with desktop?

**Comment by darkweb-123** [comment]
I have saved the context from my local windows 10 .
![image](https://user-images.githubusercontent.com/56027932/120427533-b0ddd600-c38f-11eb-8453-66f8096a3d8f.png)

I have tried importing the context file on my local windows system (working) and on azure devops windows and linux systems (not working)

**Comment by darkweb-123** [comment]
@msJinLei  Any luck on this ?

**Comment by msJinLei** [comment]
> @msJinLei Any luck on this ?

Sorry for late response.

Could you provide some additional information?
### The environment you save the context
- Environment data
   - Please run $PSVersionTable and paste the output in the below code block
     If running the Docker container image, indicate the tag of the image used and the version of Docker engine
- Module versions
   -  Please run (Get-Module  -ListAvailable) and paste the output in the below code block
- Debug output
  - Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block
     ATTENTION: Be sure to remove any sensitive information that may be in the logs

### The environment you restore the context (windows or linux both OK)
- Environment data
   - Please run $PSVersionTable and paste the output in the below code block
     If running the Docker container image, indicate the tag of the image used and the version of Docker engine
- Module versions
   -  Please run (Get-Module  -ListAvailable) and paste the output in the below code block
- Debug output
  - Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block
     ATTENTION: Be sure to remove any sensitive information that may be in the logs
- Error output
   - Please run Resolve-AzError and paste the output in the below code block
     ATTENTION: Be sure to remove any sensitive information that may be in the logs

**Comment by darkweb-123** [comment]
Thanks @msJinLei  . The issue is fixed . I was using different Az.Account module in my local system and a different Module in the Azure devops agent . Thanks for the support
