### ISSUE TITLE
New-AzRecoveryServicesAsrVMNicConfig Cmdlet -NicID parameter

### ISSUE THREAD

**Issue by mmitchellcit** [Azure/azure-powershell#15162]
The example in the New-AzRecoveryServicesAsrVMNicConfig Cmdlet documentation references a variable named $AsrNicGuid for the NicID parameter, but it does not specify where to find or how to generate the NICID. This is an incomplete, unusable example, as the Cmdlet does not work without that parameter.

**Comment by Sharmistha-Rai** [comment]
@mmitchellcit - thanks for this feedback. 
We will make edits to this document to ensure that proper steps to procure NicId are mentioned.

**Comment by Sharmistha-Rai** [comment]
@mmitchellcit 
To get NIC ID, you can follow the below command - 

`$nicId = $protectedItemObject.NicDetailsList[0].NicId`

Here, $protectedItemObject can be obtained by running the below command - 

`$protectedItemObject = Get-AsrReplicationProtectedItem -ProtectionContainer $primaryContainerObject | where { $_.FriendlyName -eq $VMName };$protectedItemObject`

Meanwhile, we will work on editing this doc and adding this change. 

Closing this issue as resolution has been provided. Please feel free to re-open in case of any queries.

**Comment by mmitchellcit** [comment]
I do have a follow-up question: Once the $nicConfig is obtained, how is the protected item updated with the new $nicConfig? To be a complete example, this information is also needed.

**Comment by Sharmistha-Rai** [comment]
@mmitchellcit 

Below is the snippet for updating the protected item with new $nicConfig -

```
$protectedItemObject = Get-AsrReplicationProtectedItem -ProtectionContainer $primaryContainerObject -Debug | where { $_.FriendlyName -eq $VMName} 

//Setting NICs for Recovery and Test Failover 
$ipConfig1 = New-AzRecoveryServicesAsrVMNicIPConfig  -IpConfigName "ipconfig1" -IsSelectedForFailover -RecoverySubnetName "default" -RecoveryStaticIPAddress "<IPAddress1>" -TfoStaticIPAddress "<TfoIPAddress1>" -TfoSubnetName "default"
$ipConfig2 = New-AzRecoveryServicesAsrVMNicIPConfig  -IpConfigName "ipconfig2" -IsSelectedForFailover -RecoverySubnetName "default" -RecoveryStaticIPAddress "<IPAddress2>" -TfoStaticIPAddress "<TfoIPAddress2>" -TfoSubnetName "default"
$ipConfig3 = New-AzRecoveryServicesAsrVMNicIPConfig  -IpConfigName "ipconfig3" -RecoverySubnetName "default"  -RecoveryStaticIPAddress "<IPAddress3>" -TfoStaticIPAddress "<TfoIPAddress3>" -TfoSubnetName "default"
$ipConfigs = @($ipConfig1, $ipConfig2, $ipConfig3)

$nic1 = New-AzRecoveryServicesAsrVMNicConfig -NicId "<NicId>" -ReplicationProtectedItem $protectedItemObject -RecoveryVMNetworkId <recoveryNetworkId> -IPConfig $ipConfigs -TfoVMNetworkId <tfoNetworkId>
$nics = @($nic1)

Set-AzRecoveryServicesAsrReplicationProtectedItem -InputObject $protectedItemObject -ASRVMNicConfiguration $nics
```
