### ISSUE TITLE
Az.KeyVault should have SecretManagement tag in Powershell Gallery

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#15173]
## Description of the new feature

Az.Keyvault is not discoverable if someone types "secretmanagement" into the PowerShell Gallery, as such several people don't know a secret management vault exists. The guidance from the PowerShell team is to have secretmanagement tag for vault extensions, so this should be added to the deployment process when this module is published to the PowerShellgallery.

@sydneyhsmith of the PowerShell team can provide additional information.

**Comment by dingmeng-xue** [comment]
Thanks for suggestion. We will consider it.
