### ISSUE TITLE
Get-azureprovider, register-azureprovider missing

### ISSUE THREAD

**Issue by meyergm** [Azure/azure-powershell#1517]
I found that get Get-azureprovider and register-azureprovider are missing from 1.0.1. 
What is the process to register providers now? The register-azurermproviderfeature command is lacking help content.

**Comment by hovsepm** [comment]
@meyergm, it was moved to ARM cmdlets and renamed to Get-AzureRmResourceProvider and Register-AzureRmResourceProvider
