### ISSUE TITLE
 Set-AzRecoveryServicesBackupProperty broken with strange behaviour

### ISSUE THREAD

**Issue by hiaga** [Azure/azure-powershell#15178]
## Description
**One of our Az.RecoveryServcies cmdlet is broken in prod and we are facing a strange problem in this command - in the attached debug traces, it can be seen that the HTTP request went through but we didn't recieve a Http Response. This happens while the other commands are working fine and underlying APIs also work fine in POSTMAN or other clients.  @dingmeng-xue @isra-fel  any pointers for this ?**

Set-AzRecoveryServicesBackupProperty -Vault $vault -EnableCrossRegionRestore  -Debug
DEBUG: 1:56:57 PM - SetAzureRmRecoveryServicesBackupProperties begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 1:56:57 PM - using account id 'hiaga@microsoft.com'...

Confirm
Are you sure you want to perform this action?
Performing the operation "set" on target "Azure Recovery Services Vault".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y
DEBUG: [Common.Authentication]: Authenticating using Account: 'hiaga@microsoft.com', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: 1:56:59 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'hiaga@microsoft.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59] Found 1 cache accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59] Returning 1 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] MSAL MSAL.NetCore with assembly version '4.30.1.0'. CorrelationId(749788a8-3a0d-4d59-816e-08dd590a3ab1)
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 749788a8-3a0d-4d59-816e-08dd590a3ab1

DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] === Token Acquisition (SilentRequest) started:

        Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Access token is not expired. Returning the found cache entry. [Current time (06/04/2021 08:26:59) - Expiration Time (06/04/2021 09:20:34 +00:00) - Extended Expiration Time (06/04/2021 09:20:34 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Returning access token found in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Fetched access token from host login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 06/04/2021 09:20:34 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-06-04T09:20:34.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47', UserId: 'hiaga@microsoft.com'
DEBUG: [Common.Authentication]: Authenticating using Account: 'hiaga@microsoft.com', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: 1:56:59 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'hiaga@microsoft.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59] Found 1 cache accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59] Returning 1 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] MSAL MSAL.NetCore with assembly version '4.30.1.0'. CorrelationId(7068a351-56b3-43ee-a4cf-0bc15ed098c3)
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 7068a351-56b3-43ee-a4cf-0bc15ed098c3

DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] === Token Acquisition (SilentRequest) started:

        Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Access token is not expired. Returning the found cache entry. [Current time (06/04/2021 08:26:59) - Expiration Time (06/04/2021 09:20:34 +00:00) - Extended Expiration Time (06/04/2021 09:20:34 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Returning access token found in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Fetched access token from host login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 06/04/2021 09:20:34 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-06-04T09:20:34.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47', UserId: 'hiaga@microsoft.com'
DEBUG: [Common.Authentication]: Authenticating using Account: 'hiaga@microsoft.com', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: 1:56:59 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'hiaga@microsoft.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59] Found 1 cache accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59] Returning 1 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] MSAL MSAL.NetCore with assembly version '4.30.1.0'. CorrelationId(f8a76a4e-0868-4757-87ab-b4c7a814acf4)
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - f8a76a4e-0868-4757-87ab-b4c7a814acf4

DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] === Token Acquisition (SilentRequest) started:

        Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Access token is not expired. Returning the found cache entry. [Current time (06/04/2021 08:26:59) - Expiration Time (06/04/2021 09:20:34 +00:00) - Extended Expiration Time (06/04/2021 09:20:34 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Returning access token found in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] Fetched access token from host login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.18363 [06/04/2021 08:26:59 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 06/04/2021 09:20:34 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-06-04T09:20:34.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47', UserId: 'hiaga@microsoft.com'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com/subscriptions/38304e13-357e-405e-9e9a-220351dcce8c/resourceGroups/hiagaCZR-rg/providers/Microsoft.RecoveryServices/vaults/hiagaCZR-vault/backupstorageconfig/vaultstorageconfig?api-version=2018-12-20

Headers:
x-ms-client-request-id        : d0585bac-10ef-4109-8a1d-efe3471bb5c8
Accept-Language               : en-US

Body:
{
  "properties": {
    "crossRegionRestoreFlag": true
  }
}

DEBUG: 1:56:59 PM - SetAzureRmRecoveryServicesBackupProperties end processing.
PS C:\Windows\System32>

**Comment by dingmeng-xue** [comment]
Could you use Fiddler to check the status of HTTP? Is there response from server?

**Comment by dingmeng-xue** [comment]
I can see the same problem. It should be service side behavior. Currently, it returns 204 (No Content).

**Comment by hiaga** [comment]
Adding a 400 sample call 

HTTP Method:
PATCH

 

Absolute Uri:
https://management.azure.com/subscriptions/a80de188-66be-4430-a923-294a890426c5/resourceGroups/hiagaCRRTestSANRG/providers/Microsoft.RecoveryServices/vaults/hiagaCRRTestSANVault/backupstorageconfig/vaultstorageconfig?api-version=2018-12-20

 

Headers:
x-ms-client-request-id        : ebdf4173-5650-4e3b-ba93-fae9781e37fb
Accept-Language               : en-US

 

Body:
{
  "properties": {
    "crossRegionRestoreFlag": true
  }
}
RESPONSE:
 


{
    "error": {
        "code": "BMSUserErrorUnableToEnableCrossRegionRestore",
        "message": "To enable Cross Region Restore in a region whose paired region has restricted access, you need to have access in the restricted region.\r\nRecovery services vault is replicating to a region which has restricted access. To request access in the restricted region read https://docs.microsoft.com/en-US/troubleshoot/azure/general/region-access-request-process Once you have access, try to enable Cross Region Restore in this vault again.",
        "target": null,
        "details": null,
        "innerError": null
    }
}

**Comment by hiaga** [comment]
We hope to fix this with SDK deployment
