### ISSUE TITLE
will Resume-AzSynapseSqlPool error out if pool is already resumed?

### ISSUE THREAD

**Issue by dataders** [Azure/azure-powershell#15180]
This would be way more valuable to me if it did not return an exit code of 1 when a pool was already resumed. If not, I'd love a workaround.

https://github.com/Azure/azure-powershell/blob/f1ff4936b0045d497a3df5401e7726c7b17e40c0/src/Synapse/Synapse/help/Resume-AzSynapseSqlPool.md#L8-L11

**Comment by navba-MSFT** [comment]
@dataders Apologies for the late reply. I am looking into this issue. I will get back to you once I have more details.

**Comment by navba-MSFT** [comment]
@dataders I tried to do a repro in my test instance and I did not receive any error while running command “Resume-AzSynapseSqlPool” to a DW that is already resumed. 
But, if you expect any error, may be you can handle this from PowerShell with the parameter “-ErrorAction SilentlyContinue” which doesn’t indicate any output with errors. (Note : You will not see any error when this parameter is used and will be a challenge for troubleshooting) 
The “-ErrorAction” is a common parameter allows you to specify which action to take if a command fails. The available options are: Stop, Continue, SilentlyContinue, Ignore, or Inquire. Hope this helps.
