### ISSUE TITLE
Improve user experience with Set-AzVM 

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#15183]
## Description of the new feature

We should improve the user experience with the `Set-AzVM` cmdlet: 

1. code: Additional safeguards should be added when running the command including warning messages that the operation is non-reversible and a confirmation about the operation should be required
2. docs: The reference documentation needs to be refreshed to explain what the cmdlet is doing, detail what will happen to the VM, if this is documented in the conceptual documentation, there should be a pointer to the corresponding page.

Related issues:
#1978 
#14940 
#14532

**Comment by avirishuv** [comment]
thanks @dcaro for the suggestions. Adding @jaylabell to review this for Azure PowerShell improvements.

**Comment by jaylabell** [comment]
I have talked with Damien, and making plans to update this experience!

**Comment by akirayamamoto** [comment]
Please note that the bad user experience also happens on the Azure Portal when capturing an image and not just the CLI.

**Comment by jaylabell** [comment]
These items have been updated. Please let me know if you have any additional questions.
