### ISSUE TITLE
ManagedHSM needs to support soft-delete

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#15186]
## Description of the new feature

Similarly with Keyvault, ManagedHSM needs to support soft-delete. Please reference https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-recovery?tabs=azure-powershell#key-vault-powershell

## Proposed implementation details (optional)
Listed soft-deleted ManagedHSM by adding `-InRemovedState`
```
Get-AzKeyVaultManagedHsm -InRemovedState
```

Purge soft-deleted ManagedHSM by adding `-InRemovedState`
```
Remove-AzKeyVaultManagedHsm -Name {} -InRemovedState -Location {}
```

Recover soft-deleted ManagedHSM. It needs new cmdlet `Undo-AzKeyVaultManagedHsmRemoval`
```
Undo-AzKeyVaultManagedHsmRemoval -Name {} -ResourceGroupName {} -Location {}
```

**Comment by LucasYao93** [comment]
Hi @dingmeng-xue,
The [New-AzKeyVault](https://docs.microsoft.com/en-us/powershell/module/az.keyvault/new-azkeyvault?view=azps-6.0.0) cmdlet support `-SoftDeleteRetentionInDays` function. 

Does [New-AzKeyVaultManagedHsm](https://docs.microsoft.com/en-us/powershell/module/az.keyvault/new-azkeyvaultmanagedhsm?view=azps-6.0.0) support it ?

**Comment by dingmeng-xue** [comment]
Yes, please add it.

**Comment by dingmeng-xue** [comment]
It is supported by https://www.powershellgallery.com/packages/Az.KeyVault/4.3.0
