### ISSUE TITLE
New-AzStorageAccount - Set MinimumTlsVersion parameter default to 1.2 not 1.0

### ISSUE THREAD

**Issue by johnmart82** [Azure/azure-powershell#15228]
## Description of the new feature
The default for the MinimumTlsVersion optional parameter is 1.0 when creating new Azure Storage Accounts. Given the inherent weakness in TLS 1.0 this is a bad default to have and should really default to 1.2 with the option for admins to select a lower version if desired. Additionally, this default for the PowerShell command differs from the default of 1.2 when creating Storage Accounts via the Portal. Standardising on the higher version should be the pathway forward.

## Proposed implementation details (optional)
Switch the default for the optional MinimumTlsVersion parameter from TLS 1.0 to TLS 1.2 while retaining current behaviours.

**Comment by dingmeng-xue** [comment]
Technically, changing default value is breaking change. But it should be acceptable to end user due to security concern. 

Storage team, please consider this requirement.

**Comment by blueww** [comment]
@johnmart82 

Currently when create account in PSH, if user don’t set MinimumTlsVersion, PSH won’t set it in request send to server, so will use the default value of server.
If the default value on server is 1.0, then the default value in PSH is also 1.0.

I have send mail to feature team to ask why the default value is 1.0, and can it change to 1.2 on server.

Besides that, Portal will let user view the account properties even if user don't change/input it. So Portal can use a default value different from server and won't cause customer surprise.
But for PSH, normally we should keep the behavior align with server.

**Comment by johnmart82** [comment]
@blueww Thanks for the update, it was not clear that it was dependent on the back end server version from the documentation. I really appreciate you taking the time to provide insight on this, great to learn something new :-)

I think it would be good to understand why there is still a default of 1.0 on the back end.

I agree that a level of alignment is required but in situations like this erring on the side of caution and security would be worth exploring if the back end server changes are not easy.

**Comment by blueww** [comment]
@johnmart82

I have get responds from SRP team: they have thought about setting the default value to be 1.2 on server at a newer API version. For a smooth transition , they need first update the description in swagger to remind user the default value will change, then change it in a new API version, it might will take several months.

For PowerShell, this is also a breaking change. And Powershell GA release only allows breaking change in major release (generally twice 1 year). If we change the default in a minor release, we might will get customer issues for the script breaking.

**Comment by navba-MSFT** [comment]
@johnmart82 Could you please let us know if you had a chance to look at the above comment ? Please let us know if you have any follow-up questions on this. Awaiting your reply.

@blueww Do you have any recent updates to share on this ?

**Comment by blueww** [comment]
@navba-MSFT 
I have ping SRP server team for the fix from server side.

**Comment by blueww** [comment]
@HimanshuChhabra , @priyapansrp 
Would you please help to look at this issue?

**Comment by blueww** [comment]
@alunmj 

New-AzStorageAccount doesn't set a default value for [MinimumTlsValue](https://github.com/Azure/azure-powershell/blob/08038d9e866545c08565cc844941dececa59791d/src/Storage/Storage.Management/StorageAccount/NewAzureStorageAccount.cs#L513). If user not set MinimumTlsValue, This cmdlet will not send MinimumTlsValue when send Put Storage Account request to server. 

So if you create a stroage account without set MinimumTlsValue, and get the default as TLS 1.0, It means the default value on server is TLS 1.0. Would you please get the debug log of the New-AzStorageAccount (by add -debug) parameter, and share following information:
1.  you repro script (especially the parameters of New-AzStorageAccount, hide credential if any)
2.  The debug log of the cmdlet (especially the request ID, time, hide credential if any)
3. Az.Storage version (Run Get-Module after repro this issue in same Powershell console)

If from the debug log, you see the Put Storage account request not set MinimumTlsValue, but the server responds is TLS 1.0, we are sure the default value on server is TLS 1.0. In this case, please raise a help ticket to ask server team's help by follow up https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header .
