### ISSUE TITLE
Update API version of subscription to 2021-01-01

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#15220]
## Description of the new feature

We need to upgrade common lib to support https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2021-01-01/subscriptions.json

New API will provide `tags` on subscription and `defaultDomain`, `tenantType`, and `tenantBrandingLogoUrl` on tenant.

**Comment by msJinLei** [comment]
defaultDomain, tenantType, and tenantBrandingLogoUrl are in extended properties
```
$tenants.ExtendedProperties

Key            Value
---            -----
Directory      xxxxxxxx.onmicrosoft.com
CountryCode    US
DisplayName    AzureSDKTeam
Domains        xxxxxxxx.onmicrosoft.com,yyyyy.com
TenantCategory Home
defaultDomain  xxxxxxxx.onmicrosoft.com
tenantType     AAD
```
