### ISSUE TITLE
[Az.Blockchain] Remove module after September 10, 2021

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#15233]
## Description

Due to retirement on September 10, 2021, we need to:

- [ ] Hide this module on gallery
- [x] remove module source code from main branch
- [x] Update list of Az PowerShell modules - https://github.com/Azure/azure-powershell/blob/master/documentation/azure-powershell-modules.md
- [ ] Verify `Az.BlockChain` no longer appears on the docs for Az 7.0.0 https://docs.microsoft.com/en-us/powershell/module/az.blockchain/?view=azps-7.0.0

**Comment by isra-fel** [comment]
Should we mention the removal of Az.Blockchain in the change log of Az? Probably not.

**Comment by dingmeng-xue** [comment]
No. this module has not been included in Az.

**Comment by isra-fel** [comment]
Now we only need to hide the module on PSGallery (and Test Gallery?). Back to you @dingmeng-xue

**Comment by dingmeng-xue** [comment]
Removed.
