### ISSUE TITLE
[Az.DiskPool] Require additional info in the output table of New/Update/Remove-Az.DiskPool

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/azure-powershell#15236]
## Description of the new feature
Current output table is shown by default. See figure below:
![image](https://user-images.githubusercontent.com/19869716/121464693-e9605e00-c9e6-11eb-9b8d-3a2e3d3b7a9f.png)

As discussed in https://github.com/Azure/sdk-release-request/issues/1627, we should add additional info in the output table.

Since the return model type of `New/Update/Remove-AzDiskPool` all is [DiskPool](https://github.com/Azure/azure-rest-api-specs/blob/1f0bb3f63b1664ace42cfdf646d8b2382d7b7b22/specification/storagepool/resource-manager/Microsoft.StoragePool/preview/2021-04-01-preview/storagepool.json#L1114), the output table of New/Update/Remove-AzDiskPool must be same. 

Let's discuss the appropriate properties of DiskPool we should display in output table. I recommend the order of the output to: name, location, status, provisioningState

**Comment by BethanyZhou** [comment]
@harshitha-akkaraju what's your thought?

**Comment by harshitha-akkaraju** [comment]
@BethanyZhou name, location, status, provisioningState these fields sound good to me. Could we also display the availability zone?

**Comment by BethanyZhou** [comment]
Added. The output will look like below
![image](https://user-images.githubusercontent.com/19869716/122159943-b237f400-cea1-11eb-92c5-956597ec8ba1.png)
