### ISSUE TITLE
Get-AzureSBAuthorizationRule fails with Object reference not set to an instance of an object when any parameters besides -Namespace are used

### ISSUE THREAD

**Issue by Blackbaud-CameronBlack** [Azure/azure-powershell#1525]
If you run **Get-AzureSBAuthorizationRule** with the **-Namespace** parameter, it will successfully run and return the rules on the Namespace.  If you want to get the rules for a Queue using **-EntityType**,  **-EntityName**, and **-Name**, then the call fails.

**Get-AzureSBAuthorizationRule : Object reference not set to an instance of an object.**

`Get-AzureSBAuthorizationRule -Namespace $Namespace -EntityType Queue -EntityName $QueuePath -Name $ManagerRuleName`

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
