### ISSUE TITLE
Get-AzVMUsage broken

### ISSUE THREAD

**Issue by LiliDeng** [Azure/azure-powershell#15265]
Get-AzVMUsage -location westus2 hung, could you please double check ASAP!

**Comment by LiliDeng** [comment]
seems related with below issue
![image](https://user-images.githubusercontent.com/10083705/122071409-4b76f400-ce29-11eb-9456-99c7977fcd9f.png)

**Comment by dingmeng-xue** [comment]
Please try again if it is due to service outage. We will keep this issue open for couple days.

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by amjads1** [comment]
@avirishuv - Can you please look into this issue?

**Comment by avirishuv** [comment]
as per the comment from @dingmeng-xue , will keep this open for a couple of days. @LiliDeng if you still continue to face the issue, please let us know and we can investigate further.

**Comment by avirishuv** [comment]
hi @LiliDeng are you still facing this issue? If not, can we close the issue?

**Comment by LiliDeng** [comment]
@avirishuv no issues till now, close it, thanks.
