### ISSUE TITLE
Tries to verify credentials locally

### ISSUE THREAD

**Issue by SupervisionAdmontec** [Azure/azure-powershell#15288]
When using Connect-MSolService the credential validation is trying to pull the informcation localy (on premises) instead of validating the crendentials in Azure or O365:
Example:
![image](https://user-images.githubusercontent.com/86015091/122262110-adbc0d00-ce9a-11eb-9468-4be664bedc20.png)

**Comment by dingmeng-xue** [comment]
@SupervisionAdmontec , `Connect-MSolService` comes from https://www.powershellgallery.com/packages/MSOnline/. Please contact them via PSGallery or Microsoft support channel.

We have no idea about accurate contact approach. You may get answer from https://github.com/Azure/azure-docs-powershell-azuread
