### ISSUE TITLE
Query: Azure Storage failover for a RA-GRS account

### ISSUE THREAD

**Issue by asgoe** [Azure/azure-powershell#15290]
We are working on creating scripts to failover our storage accounts (RA-GRS configuration). The failover documentation mentions that after failover the account is configured as LRS and needs to be re-enabled as RA-GRS. We use the Set-AzStorageAccount cmd (after failing over the account to the secondary region) to covert the account back from LRS to RA-GRS. Few questions about this flow:

1) When the primary region is in an outage, will the Set-AzStorageAccount cmd succeed in converting the storage account from LRS to RA-GRS?

- If yes, what happens to the replication while primary region is under outage?

- If no, what is the correct process to follow to convert the account back to RA-GRS?

2) Is the Set-AzStorageAccount cmd asynchronous? We have had cases where in our testing the above command succeeded, but the portal was still showing the account as LRS. Also, the when we ran the Get-AzStorageAccount cmd call with -IncludeGeoReplicationStats as a parameter, it failed with the error "AccountType Standard_LRS is invalid. ".

**Comment by blueww** [comment]
@asgoe 
Question #1, this is more like a server behavior question than a Powershell question, need check with server team.

For #2， Set-AzStorageAccount cmd is synchronous. We need to check with server team why you don't see the property update on server.

Could you give the debug log on Set/Get-AzstorageAccount cmdlet (add "-debug"), to help server team investigate the issue?

**Comment by asgoe** [comment]
Can you provide the contact for the server team? I will have to check if -debug can be added. This script is running in a VSO pipeline.

________________________________

**Comment by blueww** [comment]
I have write a mail to server team.

If you can give your mail address, I might can add you to the mail.

**Comment by asgoe** [comment]
***@***.***

________________________________

**Comment by asgoe** [comment]
My email is my alias @ microsoft.com. It would be great if you could start the email chain with the server team

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by blueww** [comment]
@asgoe
I have added you to the mail thread.

There are already some answer from server team, you can see details in the mail.
Let's go with the issue in mail first.

**Comment by blueww** [comment]
As we are discussing this server question/issue in mail, and this is not a PSH issue, I will close this issue.
