### ISSUE TITLE
update Microsoft.Azure.Commands.Common.KeyVault Lib to use latest API version

### ISSUE THREAD

**Issue by Kotasudhakarreddy** [Azure/azure-powershell#15302]
## Description

current Microsoft.Azure.Commands.Common.KeyVault library is just supporting Version2016_10_1 APIs and models to use. Support is missing for latest Version of APIs and Models.

**Comment by dingmeng-xue** [comment]
Hi Kota, I believe this request is created due to https://github.com/Azure/azure-powershell/issues/15091. Is this feature request still needed?

**Comment by Kotasudhakarreddy** [comment]
Hi @dingmeng-xue , Yes it is needed. because currently the common lib is supporting to 2016-06-01 API & Models. Even though latest API versions are available  we are unable to use them. So requesting for updating the common lib to latest API versions.

**Comment by dingmeng-xue** [comment]
Common lib is used across services and across module versions. API won't be removed once we add it into common. We don't aggressively add the latest API version. What feature requires new API version of Keyvault and which API version it needs?

**Comment by Kotasudhakarreddy** [comment]
We are not looking for any new feature availability. But just want to make sure that our service is making a call to the latest version of APIs. If you think it cannot done in the near future and it is in your backlog list, I am happy to close this issue.

**Comment by dingmeng-xue** [comment]
Thanks Kota. I am closing this request now. Please let us know when your feature needs the new API version of KeyVault.
