### ISSUE TITLE
Install Azure Powershell to machine with no Internet

### ISSUE THREAD

**Issue by robsmi-msfte** [Azure/azure-powershell#15308]
## Description
I need to install Azure "Az" to one or more devices that have no outbound network connectivity.  I can copy files to, but not from the device.  Do we instructions on how to do that?

**Comment by dingmeng-xue** [comment]
If OS of target machine is Windows, you can use MSI package which can be found in each Az Github release page. For instance https://github.com/Azure/azure-powershell/releases/tag/v6.1.0-June2021

You also can copy the files and put them to PowerShell module folder. https://docs.microsoft.com/en-us/powershell/scripting/developer/module/installing-a-powershell-module?view=powershell-7.1
