### ISSUE TITLE
Az.Compute 4.14.0 Add-AzVmssNetworkInterfaceConfiguration makes Vmss creation not work

### ISSUE THREAD

**Issue by grizzlytheodore** [Azure/azure-powershell#15331]
## Description

By bug, Add-AzVmssNetworkInterfaceConfiguration sets NetworkApiVersion property by default. The CRP only expects that property when the Vmss in being created in 'Flex' mode. So anytime a VMSS that has a network interface defined by using cmdlet: 'Add-AzVmssNetworkInterfaceConfiguration' will fail at creation unless it is in 'flex' mode

## Steps to reproduce

```powershell
$vmss = New-AzVmssConfig -Location $Loc -SkuCapacity 2 -SkuName "Standard_A1_v2" -UpgradePolicyMode "Automatic" 
Add-AzVmssNetworkInterfaceConfiguration -VirtualMachineScaleSet $VMSS -Primary $True -IPConfiguration $IPCfg
New-AzVmss -ResourceGroupName "testRG" -VMScaleSetName "testVmss" -VirtualMachineScaleSet $vmss
```

## Environment data

```

```

## Module versions

```powershell
Az.Compute 4.14.0
```

## Debug output

```

```

## Error output

```
{
      "code": "InvalidJson",
      "message": "Could not find member 'networkApiVersion' on object of type 'VMScaleSetNetworkProfile'. Path 'Properties.UpdateGroups[0].NetworkProfile.networkApiVersion', line 1, position 933."
    }
  ],
  "innererror": {
    "errorDetail": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidRequestFormat\",\r\n    \"message\": \"Cannot parse the request.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DuplicateResourceName\",\r\n        \"message\": \"Resource /subscriptions//resourceGroups//providers/Microsoft.Compute/virtualMachineScaleSets//updateGroups/ has two child resources with the same name (network-config).\"\r\n      },\r\n      {\r\n        \"code\": \"InvalidJson\",\r\n        \"message\": \"Could not find member 'networkApiVersion' on object of type 'VMScaleSetNetworkProfile'. Path 'Properties.UpdateGroups[0].NetworkProfile.networkApiVersion', line 1, position 933.\"\r\n      }\r\n    ]\r\n  }\r\n}"
  },
  "code": "InvalidRequestFormat",
  "message": "Cannot parse the request."

```

**Comment by grizzlytheodore** [comment]
this is will be resolve in the 4.15.0 version. addressed in this PR: https://github.com/Azure/azure-powershell/pull/15330
[4.15.0 will be released on 8/3](https://github.com/Azure/azure-powershell/milestone/125)

**Comment by grizzlytheodore** [comment]
to use Add-AzVmssNetworkInterfaceConfiguration, please use an older version of the module until 4.15.0 is released

**Comment by Drewm3** [comment]
This issue will be closed once the new release is out that resolves the issue. Until that time please see the workaround recommended by Theodore above.

**Comment by grizzlytheodore** [comment]
directions to use older module version as a workaround:
uninstall-module -name az.compute
install-module az.compute -RequiredVersion 4.13.0

**Comment by grizzlytheodore** [comment]
closing this issue. fixed in az.compute 4.15
