### ISSUE TITLE
Pull an Azure dynamic Group report by Region

### ISSUE THREAD

**Issue by taylorfusion** [Azure/azure-powershell#15363]
## Description
We have added 5,000 users to a dynamic group  for MFA but Azure doesn't provide very good exporting for a given Dynamic Group. How can I query in Powershell against a Dynamic Group to learn who is registered and who hasn't?

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We raise your question to Service team and ask their feedback.

**Comment by taylorfusion** [comment]
Script can be found here: https://docs.microsoft.com/en-us/samples/azure-samples/azure-mfa-authentication-method-analysis/azure-mfa-authentication-method-analysis/
