### ISSUE TITLE
Get-AzKeyVaultSecret: Operation get is not allowed on a disabled secret

### ISSUE THREAD

**Issue by ktdixit** [Azure/azure-powershell#15378]
**Get-AzKeyVaultSecret -VaultName $keyVaultName**

**Error:** 
2021-06-30T12:20:46.1348367Z ##[error]Operation returned an invalid status code 'Forbidden'
Code: Forbidden
**Message: Operation get is not allowed on a disabled secret.**
2021-06-30T12:20:46.3023398Z ##[error]PowerShell exited with code '1'.

**Note:** I am running this command in AzureDevOps (Azure Powershell) which has Get, List, Set permission in Keyvault access policies (PermissionsToKeys and PermissionsToSecrets)

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will look into it.

**Comment by BethanyZhou** [comment]
Hi @ktdixit , what's the version of Az.KeyVault you are using? I remembered we fixed this issue in https://github.com/Azure/azure-powershell/issues/14740, please try Az.KeyVault>=3.4.3.

**Comment by ktdixit** [comment]
I am using AzurePowershell Task 5.x in Azure Pipelines. I want to get only enabled secrets and name of the disabled secrets (so that we will know what are disabled)

**Comment by BethanyZhou** [comment]
Thanks for your quick response. 

I recommend to use our latest Azure PowerShell version as following:
![image](https://user-images.githubusercontent.com/19869716/124086044-40f06780-da83-11eb-8543-beec974595c5.png)

Latest Az PowerShell supports what you want to do:
![image](https://user-images.githubusercontent.com/19869716/124086754-f3282f00-da83-11eb-82cb-bf47c89366c1.png)

**Comment by ktdixit** [comment]
@BethanyZhou thanks for your response. I can get the secret names status (true or false) using **_Get-AzKeyVaultSecret -VaultName $(keyVaultName)_** with azure powershell version 6.1.0 (specific version), but it doesn't skip disabled secrets. Entire pipeline fails. 
Scenario: I have 50+ secrets in a keyvault and 15th secret is disabled, it doesnt move to the next secret for printing. 

Here is my code: Am I missing any parameter? 

Get-AzKeyVaultSecret -VaultName $(keyVaultName) -AsPlainText | Foreach-Object {
	$secret = Get-AzKeyVaultSecret -VaultName $(keyVaultName) -Name $_.Name -AsPlainText
	@{
		"Value" = $secret; "Name" = $_.Name 
    }
}
**Error:** 
##[error]Operation returned an invalid status code 'Forbidden'
Code: Forbidden
Message: Operation get is not allowed on a disabled secret.
2021-07-01T17:18:35.7987139Z ##[error]PowerShell exited with code '1'.
2021-07-01T17:18:36.6177123Z ##[section]Finishing: AzureDevOps Account - Get Keyvault Secret

**Comment by BethanyZhou** [comment]
Hi @ktdixit , 

Thanks for sharing further information.

I believe the error is from `$secret = Get-AzKeyVaultSecret -VaultName $(keyVaultName) -Name $.Name -AsPlainText`. We are not allowed to do `Get` operation on a disabled secret.

As you said you only want to get the name of disable secrets, I suggest following code:
```powershell
Get-AzKeyVaultSecret -VaultName $(keyVaultName) -AsPlainText | Foreach-Object {
  if($_.Enabled){
    $secret = Get-AzKeyVaultSecret -VaultName $(keyVaultName) -Name $_.Name -AsPlainText
    @{"Value" = $secret; "Name" = $_.Name}
  }else{
    @{"Value" = "None"; "Name" = $_.Name}
  }
}
```

**Comment by ktdixit** [comment]
@BethanyZhou works perfectly fine. Thank you so much for your help. Much appreciated
