### ISSUE TITLE
New-AzStorageContainerSASToken: The input is not a valid Base-64 string as it contains a non-base 64 character

### ISSUE THREAD

**Issue by ktdixit** [Azure/azure-powershell#15392]
Hi, 

I want to create SAS Key through Azure DevOps Pipeline: Am I missing anything?

$StorageAccountKey = Get-AzStorageAccountKey -ResourceGroupName $(resourceGroupName) -AccountName $(storageAccountName)

$Context = New-AzStorageContext -StorageAccountName $(storageAccountName) -StorageAccountKey $StorageAccountKey
$StartDate = Get-Date
Write-Host "Today's Date: " $StartDate
$EndDate = $StartDate.AddYears(75)
Write-Host "End Date is: " $EndDate

$SASKey = New-AzStorageContainerSASToken -Name $(storageAccountName) -Permission rwdlac -StartTime $StartDate -ExpiryTime $EndDate -context $Context

Write-Host "SAS Key for Storage Account: " $storageAccountName is $SASKey

**Error:** 
2021-07-01T06:02:20.5143447Z ##[error]The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
2021-07-01T06:02:20.6359589Z ##[error]PowerShell exited with code '1'.

**Comment by blueww** [comment]
@ktdixit 
Normally a storage account has at least 2 keys, so `Get-AzStorageAccountKey` will return all account keys as a list of keys, and you only need put one of the key value to `New-AzStorageContext`.

So I modify your script as below, and it works well on my machine with latest Az.Storage module :

```PowerShell
$resourceGroupName =  # input name of the resource group which contains the storage account 
$storageAccountName = # input name of the storage account


$StorageAccountKey = Get-AzStorageAccountKey -ResourceGroupName $resourceGroupName -AccountName $storageAccountName

$Context = New-AzStorageContext -StorageAccountName $storageAccountName -StorageAccountKey $StorageAccountKey[0].Value
$StartDate = Get-Date
Write-Host "Today's Date: " $StartDate
$EndDate = $StartDate.AddYears(75)
Write-Host "End Date is: " $EndDate

$SASKey = New-AzStorageContainerSASToken -Name $storageAccountName -Permission rwdlac -StartTime $StartDate -ExpiryTime $EndDate -context $Context

Write-Host "SAS Key for Storage Account: " $storageAccountName is $SASKey

```

**Comment by ktdixit** [comment]
@blueww works perfectly fine. Thank you very much for your help. Much appreciated.
