### ISSUE TITLE
WebApp:Set-AzWebAppSlot removes existing custom autoheal rules in Azure App Service slot app

### ISSUE THREAD

**Issue by prittelm** [Azure/azure-powershell#15447]
We have an Azure app service (non-production slot) with custom autoheal rules set up and have noticed that any call made using 
"Set-AzWebAppSlot" in the Az.Websites module removes these rules.

To test this, set up custom autoheal rules on an app service reserve slot app and run the following in a powershell session:
`Set-AzWebAppSlot -ResourceGroupName <App Resource Group>  -Name <App Service Name> -Slot <Slot name>`
_Full disclosure: This example is simplified from what we actually use. Our real world use sets up the connection strings in the slot app via an additional "-ConnectionStrings $connectionStrings" setting however it makes no difference to omit this in order to reproduce the issue._ 

**For reference, our custom autoheal json before running Set-AzWebAppSlot:**
```
      "autoHealEnabled": true,
      "autoHealRules":  {
              "triggers": {
                "statusCodes": [],
                "statusCodesRange": [
                  {
                    "statusCodes": "500-530",
                    "path": "*/oauth2/v2.0/token",
                    "count": 10,
                    "timeInterval": "00:01:00"
                  }
                ]
              },
```
**Custom autoheal json after Set-AzWebAppSlot:**
```
             "autoHealEnabled": true,
             "autoHealRules":  {
              "triggers": {
                "statusCodes": [],
                "statusCodesRange": []
              },
```

**Comment by prittelm** [comment]
**Update**: After some additional testing I've observed that issue seems to only affect a _ranged_ HTTP Status code rule. Static HTTP Status code rules are not wiped by the Set-AzWebAppSlot command.

For testing purposes, please be sure to set up a rule similar to this:
![image](https://user-images.githubusercontent.com/11523217/125654273-76f786ec-aacd-4331-9187-8fb149f112bc.png)

**Comment by SaurabhSharma-MSFT** [comment]
@Kotasudhakarreddy @antcp, @AzureAppServiceCLI Do you have any updates on this issue ?

**Comment by Kotasudhakarreddy** [comment]
Will take a look in to it.

**Comment by Kotasudhakarreddy** [comment]
@prittelm I am unable to repro this issue in the latest version of `Az.Websites` module. Please try with latest module. 

![image](https://user-images.githubusercontent.com/60102891/160744910-5df8f8d7-8456-49db-93b5-c4b69b83fd5b.png)

**Comment by prittelm** [comment]
@Kotasudhakarreddy Confirmed. The issue has been resolved after Az.Websites upgrade to v2.10.0.
