### ISSUE TITLE
AzureDevOps Services - List and Set "Billing" through AzurePowershell or REST API

### ISSUE THREAD

**Issue by ktdixit** [Azure/azure-powershell#15445]
Hello, 

We have multiple organizations and we want to achieve following: 
1. Get the list of AzureDevOps Organizations which do not have "Billing" configured / setup
2. Set the billing for organizations

We want to achieve this using AzurePowershell / REST API. Please guide. Not looking for suggestions to do from UI. 

![image](https://user-images.githubusercontent.com/65254430/125032556-6f2b0400-e08e-11eb-9678-311a32a39c92.png)

Regards,
Krishnamurthy

**Comment by dingmeng-xue** [comment]
Azure DevOps is not in the scope of Azure PowerShell. For the time being, we have no plan to support it.

Fortunately, access token from Azure PowerShell can be used to access DevOps API. Below is example of listing pipelines. I didn't find billing related API. 

```
$tokenHeader = @{
    'Content-Type' = 'application/json';
    'Authorization' = 'Bearer ' + (Get-AzAccessToken).token   
}
Invoke-RestMethod -Method Get -Headers $tokenHeader -Uri "https://dev.azure.com/{organization}/{project}/_apis/pipelines?api-version=6.1-preview.1"
```

**Comment by ktdixit** [comment]
@dingmeng-xue I was referring to setting up a billing through Powershell/AzurePowershell/RESTAPI related to https://docs.microsoft.com/en-us/azure/devops/organizations/billing/set-up-billing-for-your-organization-vs?view=azure-devops

You mean there is no API for billing functionality in AzureDevOps?

**Comment by dingmeng-xue** [comment]
I'm not owner of DevOps. I just searched API list on https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1 but I didn't see billing related.

@ktdixit , I'm closing this issue now because Azure DevOps is not in the scope of Azure PowerShell. You need to raise feature request to DevOps team and ask PowerShell support.
