### ISSUE TITLE
Command "Get-AzPolicySetDefinition -ManagementGroup <string> -Custom" not working

### ISSUE THREAD

**Issue by fidelcasto** [Azure/azure-powershell#15449]
Hi,
I am not able to retrieve custom initiatives stored in a Management Group using the Get-AzPolicySetDefinition.  
It seems to work fine on a subscription level though.

Example : 
Working : Get-AzPolicySetDefinition -SubscriptionId < string > -Custom 
Not working : Get-AzPolicySetDefinition -ManagementGroupName < string > -Custom

Regards

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Please share your debug log. You need to run issue script again after setting `$DebugPreference= "Continue"`

**Comment by oliviercastonguay** [comment]
> Thanks for reporting. Please share your debug log. You need to run issue script again after setting `$DebugPreference= "Continue"`

I just removed username and tenant id from the debug log.

DÉBOGUER : 07:41:50 - GetAzurePolicySetDefinitionCmdlet begin processing with ParameterSet 'CustomFilterParameterSet'.
DÉBOGUER : 07:41:50 - using account id ''
DÉBOGUER : [Common.Authentication]: Authenticating using Account: '', environment: 'AzureCloud', tenant: ''
DÉBOGUER : 07:41:50 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'', Scopes:'https://management.core.windows.net//.defau
lt', AuthorityHost:'https://login.microsoftonline.com/', UserId:''
DÉBOGUER : SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50] Found 2 cache accounts and 0 broker accounts
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50] Returning 2 accounts
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50 - ] MSAL MSAL.Desktop with assembly version '4.30.1.0'. CorrelationId()
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50 - ] === AcquireTokenSilent Parameters ===
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50 - ] LoginHint provided: False
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50 - ] Account provided: True
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50 - ] ForceRefresh: False
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50 - ] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50 - ] === Token Acquisition (SilentRequest) started:
	
	Authority Host: login.microsoftonline.com
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50 - ] Access token is not expired. Returning the found cache entry. [Current time (07/21/2021 11:41:50) - Ex
piration Time (07/21/2021 12:41:04 +00:00) - Extended Expiration Time (07/21/2021 12:41:04 +00:00)]
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50 - ] Returning access token found in cache. RefreshOn exists ? False
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50 - ] Fetched access token from host login.microsoftonline.com. 
DÉBOGUER : (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [07/21/2021 11:41:50 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 07/21/
2021 12:41:04 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DÉBOGUER : SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-07-21T12:41:04.0000000+00:00
DÉBOGUER : [Common.Authentication]: Received token with LoginType 'User', Tenant: '', UserId: ''
DÉBOGUER : ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/providers/Microsoft.Management/managementGroups/TestOlivier/providers/Microsoft.Authorization/policysetdefinitions?api-version=2020-09-01

Headers:
User-Agent                    : AzurePowershell/v0.0.0,PSVersion/v5.1.19041.906
ParameterSetName              : CustomFilterParameterSet
CommandName                   : Get-AzPolicySetDefinition

Body:



DÉBOGUER : ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-tenant-reads: 11997
x-ms-request-id               : 36c150ff-b517-404f-b358-01405c8089fc
x-ms-correlation-request-id   : 36c150ff-b517-404f-b358-01405c8089fc
x-ms-routing-request-id       : CANADACENTRAL:20210721T114150Z:36c150ff-b517-404f-b358-01405c8089fc
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Wed, 21 Jul 2021 11:41:50 GMT
Server                        : Kestrel

Body:
{
  "value": [
    {
      "properties": {
        "displayName": "[Preview]: NIST SP 800-171 R2",
        "policyType": "BuiltIn",
        "description": "This initiative includes audit and virtual machine extension policies that address a subset of NIST SP 800-171 R2 requirements. Additional policies will be added in upcomi
ng releases. For more information, visit https://aka.ms/nist800171r2-blueprint.",
        "metadata": {
          "version": "5.1.0-preview",
          "category": "Regulatory Compliance",
          "preview": true
        },
        "parameters": {
          "IncludeArcMachines": {
            "type": "String",
            "metadata": {
              "displayName": "Include Arc connected servers for Guest Configuration policies",
              "description": "Optionally choose to audit settings inside Arc connected servers using Guest Configuration policies. By selecting this option, you agree to be charged monthly per Ar
c connected machine."
            },
            "allowedValues": [
              "true",
              "false"
            ],
            "defaultValue": "false"
          },
          "membersToExcludeInLocalAdministratorsGroup": {
            "type": "String",
            "metadata": {
              "displayName": "List of users excluded from Windows VM Administrators group",
              "description": "A semicolon-separated list of users that should be excluded in the Administrators local group; Ex: Administrator; myUser1; myUser2"
            }
          },
          "membersToIncludeInLocalAdministratorsGroup": {
            "type": "String",
            "metadata": {
              "displayName": "List of users that must be included in Windows VM Administrators group",
              "description": "A semicolon-separated list of users that should be included in the Administrators local group; Ex: Administrator; myUser1; myUser2"
            }
          },
          "listOfLocationsForNetworkWatcher": {
            "type": "Array",
            "metadata": {
              "displayName": "[Deprecated]: List of regions where Network Watcher should be enabled",
              "description": "Audit if Network Watcher is not enabled for region(s).",
              "strongType": "location",
              "deprecated": true
            },
            "defaultValue": []
          },
          "NetworkWatcherResourceGroupName": {
            "type": "String",
            "metadata": {
              "displayName": "NetworkWatcher resource group name",
              "description": "Name of the resource group of NetworkWatcher, such as NetworkWatcherRG"
            },
            "defaultValue": "NetworkWatcherRG"
          },
          "logAnalyticsWorkspaceIDForVMAgents": {
            "type": "String",
            "metadata": {
              "displayName": "Log Analytics workspace ID for VM agent reporting",
              "description": "ID (GUID) of the Log Analytics workspace where VMs agents should report."
            }
          },

******
A hole bunch of other Built In Policies listed here which does not seem relevant to share.
******

DÉBOGUER : AzureQoSEvent: CommandName - Get-AzPolicySetDefinition; IsSuccess - True; Duration - 00:00:10.8826479
DÉBOGUER : Finish sending metric.
DÉBOGUER : 07:42:01 - GetAzurePolicySetDefinitionCmdlet end processing.

**Comment by kenieva** [comment]
Is the bottom response what you get for subscriptions?

**Comment by oliviercastonguay** [comment]
> Is the bottom response what you get for subscriptions? 

Nope it's what I get for Management group

**Comment by kenieva** [comment]
Hi fidelcasto, can you confirm that this is still an ongoing issue?

**Comment by fidelcasto** [comment]
> Hi fidelcasto, can you confirm that this is still an ongoing issue?

It seems to work just fine now.  Thank you !
