### ISSUE TITLE
Remove-AzureRmNetworkSecurityGroup silently fails

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1546]
If the wrong Network Security Group (NSG) name is specified in the call to `Remove-AzureRmNetworkSecurityGroup`, it silently fails. Instead, it should be throwing an error message.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by devigned** [comment]
@DeepakRajendranMsft to triage

**Comment by DeepakRajendranMsft** [comment]
@devigned  this is the expected ARM behavior. The RPs are not expected to throw an exception when the user tries to delete a resource that is not present

**Comment by pcgeek86** [comment]
@DeepakRajendranMsft Thanks, but that design is counterproductive to a positive user experience in the ARM PowerShell module. I'd recommend going back to the drawing board and reconsidering it. 

Besides, the ARM PowerShell experience should be *tailored to PowerShell*, not simply a dummy wrapper around ARM. :smile:

**Comment by markjbrown** [comment]
Closing issue. This is not an issue we can fix from NRP.

**Comment by pcgeek86** [comment]
@markjbrown Hi Mark, this is a design issue with PowerShell, not with the Resource Provider. If a resource doesn't exist, then the PowerShell command should throw an exception. Otherwise, the user presumes that the command executed successfully, even if they made a typo. That isn't good PowerShell behavior.

**Comment by markcowl** [comment]
@kirthik Assignign to you.  Based on Trevor's input, we should consider a design document change, in consultation with our MVPs, PowerShell team and service teams.  If we decide to change this, we will have to consider for the next breaking change revision

**Comment by twitchax** [comment]
With guidance from @joeyaiello, this change is approved for our next breaking change release.

Most shell commands tend to _at least_ warn on a failed delete/remove.  For example,

```bash
$ rm aFileThatDoesNotExist.txt
rm: cannot remove 'aFileThatDoesNotExist.txt': No such file or directory
```
also fails similarly to the PowerShell example @pcgeek86 provided.  It might make sense to include a `-Force` switch since the `-f` switch for `rm` is silent when a resource does not exist.

Moving to May 2017.

**Comment by cormacpayne** [comment]
This service does not return a 4xx response, so it would be inappropriate for us to write an error in this case. If some other service _does_ return a 4xx error, then we should write the error to the error stream. Closing this issue.
