### ISSUE TITLE
Get-AzConsumptionUsageDetail ignores "Tags not supported" Items

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#15469]
When I am using the cmdlet `Get-AzConsumptionUsageDetail` the CostItems without Tag support are for some reason ignored.

`Get-AzConsumptionUsageDetail -StartDate 2021-06-01 -EndDate 2021-06-30`,

**Result:**

![image](https://user-images.githubusercontent.com/25774289/125601986-3184e32b-06fd-46fe-a545-d4388be138c9.png)

**The expeced Value should be:**

![image](https://user-images.githubusercontent.com/25774289/125602176-52b02ea1-1ef8-4d24-8010-0873532a52f6.png)

**Reason:** 

Ressources with no Tag-Support are ignored by the cmdlet

![image](https://user-images.githubusercontent.com/25774289/125602318-9f2fc855-e582-4d6d-bb4d-b97a7a0c299e.png)

**4,606.30 + 1,048.53 = 5,654.83**

```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-AzConsumptionUsageDetail                       2.0.0      Az.Billing
```

**Comment by Gill-Bates** [comment]
I have found that the Cost API is working correctly. I wrote myself a query with Invoke-RestCommand and get the correct total.

**Powershell:**

![image](https://user-images.githubusercontent.com/25774289/126112200-21fc98c6-cc27-476b-823d-338051263d92.png)


**Portal:**

![image](https://user-images.githubusercontent.com/25774289/126112222-257626d8-1b95-4b30-96f7-86369ef49849.png)

Therefore I can prove that the error is definitely in the CMDlet `Get-AzConsumptionUsageDetail` and not in the Cost API.

**Comment by paornela** [comment]
@Gill-Bates can you please submit a [support ticket here](https://azure.microsoft.com/en-us/support/create-ticket/) https://azure.microsoft.com/en-us/support/create-ticket/? We need more information about the call you made to drill down on the issue. Since billing information is sensitive, we would like to continue this investigation over a support ticket, as opposed to a public forum like this one.
