### ISSUE TITLE
Set-AzDataFactoryV2IntegrationRuntime missing Quick Re-Use Parameter

### ISSUE THREAD

**Issue by CharlesAbetz** [Azure/azure-powershell#15478]
Please add the Quick Re-Use Parameter  to the API for DataFlow Properties.

https://docs.microsoft.com/en-us/powershell/module/az.datafactory/set-azdatafactoryv2integrationruntime?view=azps-6.2.1

![image](https://user-images.githubusercontent.com/14157384/125872869-56f46a84-778b-439a-8474-c8216429edf3.png)

**Comment by CharlesAbetz** [comment]
Also trying to pass the following to the CLI version, doesn't recognise the value either.

az datafactory integration-runtime managed create --resource-group "$resourceGroupName"  --factory-name "$dataFactoryName" --integration-runtime-name "FastStartIntegrationRuntime1" --compute-properties '{\"location\": \"AutoResolve\",\"dataFlowProperties\": {\"computeType\": \"General\",\"coreCount\": 8,\"timeToLive\": 10,\"cleanup\": false}}'

**Comment by shawnxzq** [comment]
@CharlesAbetz Thanks for the feedback, we will work on this.

**Comment by shawnxzq** [comment]
Swagger is already fixed. SDK team please help the release of CLI to suppor it.

**Comment by shawnxzq** [comment]
Issue fixed.

**Comment by CharlesAbetz** [comment]
Hi Ross

They seemed to have fixed this issue.

Kind regards
Charles
