### ISSUE TITLE
Get-AzADApplication needs to list the Tags property.

### ISSUE THREAD

**Issue by Ben424242** [Azure/azure-powershell#15477]
## Description of the new feature
I can set values in the Tags property by editing the Manifest in the portal. But Tags isn't a property that's returned by the Get-AzADApplication commandlet.
## Proposed implementation details (optional)
Add the Tags property to the object returned by this commandlet

**Comment by dingmeng-xue** [comment]
@Ben424242 , Azure PowerShell is using AAD Graph api-version 1.6 which doesn't support Tag. Azure Portal is using MS Graph API. We believe the new property will be available when we implement new cmdlets around MSGraph API.

**Comment by VeryEarly** [comment]
Hi @Ben424242 ,
Tag is supported in Az.Resources 5.1.0 or later
