### ISSUE TITLE
Add-AlertRule doesn't work for RuleType `webtest`

### ISSUE THREAD

**Issue by kamranayub** [Azure/azure-powershell#1547]
The following command doesn't work as expected:

```
Add-AlertRule -FailedLocationCount 3 `
  -Location 'Central US' `
  -Name 'Availability' `
  -ResourceGroup 'testrg' `
  -CustomEmails @('test@test.com') `
  -RuleType Webtest
```

Returns the following error:

    Add-AlertRule : BadRequest: The metric name is missing.

But metric name is not in the 'webtest' parameter set.

**Comment by asheniam** [comment]
Apologies for the inconvenience.  This should be fixed already in the latest release.  Please try again.
