### ISSUE TITLE
Support SQL on VM database inquiry in the Enable-AzureRmRecoveryServicesBackupProtection cmdlet

### ISSUE THREAD

**Issue by oughton** [Azure/azure-powershell#15489]
## Description of the new feature

Support SQL On VM database inquiry in the Enable-AzureRmRecoveryServicesBackupProtection cmdlet.

Update the AzureWorkloadPsBackupProvider to trigger a database inquiry request when the provided database name is not found.

Note that is possible currently by first running the Initialize-AzRecoveryServicesBackupProtectableItem cmdlet. It would be nice to have this automatically run like for Azure FS.

The Azure Storage File Share provider supports this by preforming an inquiry for available file shares when the File Share name is not initially found. See: https://github.com/Azure/azure-powershell/blob/b8fffcd8e20a6952c58e3b3c5235ed816c9123fb/src/RecoveryServices/RecoveryServices.Backup.Providers/Providers/AzureFilesPsBackupProvider.cs#L554.

## Proposed implementation details (optional)
Implement the same logic as for Azure Storage File Share that triggers an inquiry command when the SQL database is not found.

**Comment by pvrk** [comment]
@oughton : We introduced 'auto-protection' feature for SQL (available in PS too) for this exact scenario. Can you please check that out and let us know if that meets your requirement (1 command to detect new DBs and protect with a policy)?

**Comment by oughton** [comment]
@pvrk Our specific use-case was to protect individual databases within a server but found it surprising that we have to first run Initialize-AzRecoveryServicesBackupProtectableItem whenever we add a new individual DB that we need to backup.

The reason it was surprising was because the Storage Account File Share cmdlet handles this automatically so there was the same expectation.

We do not want to protect all databases in the server.

If our use-case is a rare one then happy for this to be closed and we can work around it by always calling Initialize-AzRecoveryServicesBackupProtectableItem first.

**Comment by pvrk** [comment]
@oughton: Thanks for the explanation. If you don't want to protect all DBs but only particular DBs, you need to run initialize command before protection. And yes, you are right, storage account handles this on it's own. The difference is that, in case of Azure file share, there is a user exposed friendly name visible in Azure, that can be used during configuring protection. Whereas in DB, we don't have such Azure visible DB names. Hence we require a separate 'inquiry' command to get the name to be used in configure protection.  Hope this makes sense.

**Comment by oughton** [comment]
Thanks @pvrk makes sense.
