### ISSUE TITLE
Disassociate a Network Security Group with a Virtual Network Subnet

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1548]
The `Set-AzureRmVirtualNetworkSubnetConfig` command doesn't allow you to `$null` the `-NetworkSecurityGroup` parameter. How do I delete an association between a Network Security Group (NSG) and a Virtual Network Subnet?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by maddieclayton** [comment]
Closing. Please reopen this issue if it is still an issue in the most recent version.
