### ISSUE TITLE
Generate psm1 during project build

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#15483]
## Description of the new feature

File psm1 of each module is generated during official build pipeline, and psd1 is updated after psm1 has been generated. 

After we introduce new module architecture which requires couple psm1 files, we need to claim psm1 files in psd1. But above default psm1 is not generated yet. As the result, developer hit the issue of importing psd1 of module.

## Proposed implementation details (optional)

We expect the output of build in development environment should be the same as output of official build. So, psm1 needs to be generated during build.

**Comment by dolauli** [comment]
Add psm1.props, and for those which need to generate psm1 file, please import the psm1.props in the project file. Now only add it for the hybrid module aks, resourecgraph and website.
