### ISSUE TITLE
New-AzVM missing document for -NetworkInterfaceDeleteOption

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#15481]
## Description

In the online (and local) help of `New-AzVM` the description for parameter `-NetworkInterfaceDeleteOption` is a placeholder.

![image](https://user-images.githubusercontent.com/11371776/125902759-576c544b-e541-4352-8237-f2a88f6201d9.png)

## Steps to reproduce

```powershell
help new-azvm -Parameter NetworkInterfaceDeleteOption
```

or go to https://docs.microsoft.com/en-us/powershell/module/az.compute/new-azvm?view=azps-6.2.1#parameters

## Environment data

```
N/A
```

## Module versions

```
Latest Az 6.2.1 & Az.Compute 4.15.0
```

## Debug output

```
N/A
```

## Error output

```
N/A
```

**Comment by amjads1** [comment]
@avirishuv Could you please look into the issue?

**Comment by avirishuv** [comment]
hi @isra-fel thanks for reporting - we have added this to the backlog to update & fix. Will confirm here once done.

**Comment by avirishuv** [comment]
fix for this issue is still in the backlog.

**Comment by avirishuv** [comment]
@isra-fel this has been fixed 

https://docs.microsoft.com/en-us/powershell/module/az.compute/new-azvm?view=azps-7.3.0&viewFallbackFrom=azps-6.2.1#parameters

Closing the issue, please feel free to reopen if you see any concerns.
