### ISSUE TITLE
Set-AzureRmVirtualNetworkSubnetConfig :: No documentation for -RouteTable parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1549]
There's no documentation for the `-RouteTable` parameter on `Set-AzureRmVirtualNetworkSubnetConfig`.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by cormacpayne** [comment]
This has been fixed. Closing this issue.
