### ISSUE TITLE
[AzApiManagementNamedValue] Support to named values stored in key vault

### ISSUE THREAD

**Issue by moebius87** [Azure/azure-powershell#15494]
## Description of the new feature
Add the ability to manage Named Values linked to Key Vault secrets

**Comment by dingmeng-xue** [comment]
@moebius87 , thanks for reporting. Could you provide more information about this feature?

**Comment by moebius87** [comment]
**Get-AzApiManagementNamedValue** does not list _Named Values_ stored on a _Key Vault_.
If you try to get a specific _Named Value_ by passing  -NamedValueId parameter the command returns an error like this: 

> Error Message: Operation not allowed for keyVault derived NamedValue with id 'MY-TEST-SECRET-ON-KEYVAULT'.

It's the same for the commands:

- **Get-AzApiManagementNamedValueSecretValue**
- **Set-AzApiManagementNamedValue**
- **Remove-AzApiManagementNamedValue**

For the command **New-AzApiManagementNamedValue** there is no sintax to specify a keyvault ID insteand of passing the secret value.

(For more details see [related REST API documentation](https://docs.microsoft.com/it-it/rest/api/apimanagement/2020-12-01/named-value/create-or-update#keyvaultcontractcreateproperties))

IMHO The module Az.ApiManagement should allow you to do at least every possible operation using the Azure Portal UI 
(and manage Name Values stored in a Key Vault is possible using the UI)

**Comment by navba-MSFT** [comment]
@moebius87 Apologies for the late reply. Could you please check if the examples shared [here](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/new-azapimanagementkeyvaultobject?view=azps-7.2.0#example-1---create-a-keyvault-namedvalue) and [here](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/new-azapimanagementnamedvalue?view=azps-7.2.0#example-3---create-a-keyvault-namedvalue) helps ? Awaiting your reply.

**Comment by moebius87** [comment]
@navba-MSFT Absolutely yes! Thank you!
