### ISSUE TITLE
New-AzStorageContainerSASToken: values in Date & Time Format

### ISSUE THREAD

**Issue by ktdixit** [Azure/azure-powershell#15490]
Hello, 

I am getting two formats while creating StorageContainerSASToken: 

Manual Creation: 
?sv=2020-08-04&ss=b&srt=sco&sp=rwdlacx&se=**2031-07-06T22:35:29Z**&**st=2021-07-06T14:35:29Z**&spr=https&sig=********************%3D

AzurePowershell (AzureDevOps): 
?sv=2020-04-08&ss=b&srt=sco&spr=https&st=**2021-07-13T10%3A40%3A11Z**&se=**2031-12-01T19%3A00%3A00Z**&sp=rwdxlactf&sig=*************%3D

I am looking for exact same format mentioned in manual creation key. Why its adding %3A in time?

**Comment by blueww** [comment]
@ktdixit

Would you please the details steps how you create it in AzureDevOps, then we can look deeper?

**Comment by ktdixit** [comment]
$context = (Get-AzStorageAccount -ResourceGroupName $(resourceGroupName) -AccountName $(storageAccountName)).context

$StartDate = Get-Date
Write-Host "Today's Date: " $StartDate
$EndDate = $StartDate.AddYears(10)
Write-Host "End Date is: " $EndDate

New-AzStorageAccountSASToken -Context $context -Service Blob -ResourceType Service,Container,Object -Permission "rwdlactfx" -Protocol "HttpsOnly" -StartTime $StartDate -ExpiryTime $EndDate

**Timezone has to be in (UTC) Coordinated Universal Time**

**Comment by blueww** [comment]
Would you please also give: 
1. the Az.Storage module version of the 2 scenarios. (Run Get-Module)
2. The Powershell version of the 2 scenarios

Per my test on Powershell 5.1 + Az.Storage 3.9.0, the SAS created is in the same format as the AzureDevOps one.
For the manual create sas, do you create it with "New-AzStorageContainerSASToken" in latest Az.Storage module?

**Comment by ktdixit** [comment]
@blueww thanks for your quick response. 

1. Manual SAS Key Generation: I login to Azure Portal (UI) and generate token manually for the storage account
2. AzureDevOps: I use Azure Powershell Task Version: 5.* with Azure PowerShell Version: **Latest Installed Version**

**Comment by blueww** [comment]
@ktdixit

Per my test, both sas works with Azure server.
So could you share why you only want the sas format with manual generated one?

**Comment by ktdixit** [comment]
As long as it works I am fine, but my team reported issues with the AzureDevOps generated token. I will investigate further and get back to you after checking exact error message. Thanks for trying and providing your quick response. Much appreciated.

**Comment by blueww** [comment]
@ktdixit 
From the sas sample in doc: https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#service-sas-example
You can see the "Start time" and "Expiry time" has ":" encoded to "%3A".
So the SAS token generated from Powershell is aligned with the standard SAS format.
