### ISSUE TITLE
Az.NetAppFiles Removal of Snapshot Policy Assignment

### ISSUE THREAD

**Issue by victo8894** [Azure/azure-powershell#15502]
## Description of the new feature
Added ability to remove snapshot policy assignment from a volume via powershell

## Proposed implementation details (optional)
Allow for a null value of "SnapshotPolicyId" or a generic "No Policy Assignment" value in the command "Update-AzNetAppFilesVolume" that removes the Snapshot Policy Assignment from the volume specified

**Comment by audunn** [comment]
Fixed in https://github.com/Azure/azure-powershell/pull/24012
