### ISSUE TITLE
Cosmos DB - disable firewall and virtual network

### ISSUE THREAD

**Issue by JieCMarshall** [Azure/azure-powershell#15504]
I tried to use the following command to remove the firewall and virtual network settings for the cosmos db

Update-AzCosmosDBAccount -ResourceGroupName $ResourceGroupName -Name $CosmosDBName -EnableVirtualNetwork $false

I received the following error:
"...Error: VirtualNetworkRules should be specified only if IsVirtualNetworkFilterEnabled is True"

Also, it does not accept the empty rules:
$vnetRules = @()
 Update-AzCosmosDBAccount -ResourceGroupName $ResourceGroupName -Name $CosmosDBName -EnableVirtualNetwork $false -VirtualNetworkRuleObject @($vnetRules)

Azure portal has a easy way ( 1 click ) to remove the firewall settings: Allow access from All networks. How can I implement it through command line?

**Comment by AverageDesigner** [comment]
The following command should work for disabling the virtual network settings.
Update-AzCosmosDBAccount -ResourceGroupName $ResourceGroupName -Name $CosmosDBName -EnableVirtualNetwork $false

Let us know if you are still facing this issue.
