### ISSUE TITLE
Remove-AzureRmNetworkSecurityGroup :: Vague error message when associated with a Virtual Network Subnet

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1550]
When a NSG is associated with a Subnet, and you try to delete it, it throws a vague error message.

<img width="720" alt="screen shot 2015-12-28 at 1 18 30 pm" src="https://cloud.githubusercontent.com/assets/466713/12024851/c60a248e-ad65-11e5-8361-76ee09ebae2e.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by nth-block** [comment]
I checked a the network trace using Fiddler and the API responds with a lot more friendlier message. Can the powershell be configured to do the same please?

![image](https://cloud.githubusercontent.com/assets/20584285/17139449/1a01da44-5362-11e6-9dc3-b0bd8b3eab37.png)

**Comment by maddieclayton** [comment]
@avijitgupta Can you take a look at this issue?

**Comment by EvgenyAgafonchikov** [comment]
@maddieclayton, this seems to be outdated, I have the following output now:
![image](https://user-images.githubusercontent.com/3365854/51467580-e31da880-1d7d-11e9-8e80-3a9bbaafe2d9.png)

So I think this need to be closed.

**Comment by EvgenyAgafonchikov** [comment]
Hey, @pcgeek86, could you please confirm my comment above so we could close this?

**Comment by maddieclayton** [comment]
This issue is 3 years old so it is unlikely that the original poster will be able to respond - as long as the error message looks correct now we can close it. Thanks @EvgenyAgafonchikov!

**Comment by pcgeek86** [comment]
I didn't have a chance to review this before it was closed, but as long as you guys have tested it, that should be good enough.
