### ISSUE TITLE
Set-AzureRmVirtualNetworkSubnetConfig :: -AddressPrefix parameter shouldn't be mandatory

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1551]
The `-AddressPrefix` parameter on the `Set-AzureRmVirtualNetworkSubnetConfig` command shouldn't be mandatory, in case I want to simply associate a Route Table or Network Security Group with a Virtual Network Subnet, but not make any changes to its Address Prefix.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by DarrylvanderPeijl** [comment]
The same goes for the -Name parameter.

**Comment by markjbrown** [comment]
@DarrylvanderPeijl name is required to identify the subnet to be changed.

@pcgeek86 Trevor. Been discussing this. Can you email me directly? thanks.

**Comment by markjbrown** [comment]
Talked with Deepak on our team here. The problem is the child objects are updated with a PUT not a PATCH. So you need the entire child object in order to update in PS.

We are going to look at this again and potentially change how we do child objects but I cannot commit anything now.

**Comment by maddieclayton** [comment]
@markjbrown @DeepakRajendranMsft Can you close this issue if you are not planning to implement this feature?

**Comment by markjbrown** [comment]
Adding Anavi from the SDN team to review and comment on this.

**Comment by jtuliani** [comment]
This issue is still a problem. Re-opening to see if it can be looked at again please.

If the 'Set-' cmdlet is using PUT, perhaps we can make an 'Update-' cmdlet that uses PATCH (subnets would need to support PATCH, which would be A Good Thing).
