### ISSUE TITLE
Set-AzNetworkSecurityRuleConfig is not working as expected

### ISSUE THREAD

**Issue by SubhashVasarapu-MSFT** [Azure/azure-powershell#15517]
## Description
Unable to set/update the existing network config rule on an NSG using the below mentioned PS command,
Set-AzNetworkSecurityRuleConfig -Name "rdp-rule" -NetworkSecurityGroup $nsg -Access "Deny"

The same has been tested with CLI commands where deployment is successful. Here is the link pointing to the Azure doc.
https://docs.microsoft.com/en-us/powershell/module/az.network/set-aznetworksecurityruleconfig?view=azps-6.2.1

## Steps to reproduce

```
$nsg = Get-AzNetworkSecurityGroup -Name "NSG-FrontEnd" -ResourceGroupName "TestRG"
$nsg | Get-AzNetworkSecurityRuleConfig -Name "rdp-rule"
Set-AzNetworkSecurityRuleConfig -Name "rdp-rule" -NetworkSecurityGroup $nsg -Access "Deny"

```

## Environment data

```
Tested this on AZ cloud shell

```

## Debug output

```
Output of the command execution is getting stored on that PS session but not getting reflected on the portal.

```

## Error output

```
No Error

```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Please share the CLI scripts for reference.

**Comment by husseinkorly** [comment]
The issue is the changes are being committed, so you will need to add the following command:
```
$null = Set-AzureRmNetworkSecurityGroup -NetworkSecurityGroup $nsg
```

**Comment by tjrobinson** [comment]
If you're using the Azure Az PowerShell module, the command is `Set-AzNetworkSecurityGroup` instead of `Set-AzureRmNetworkSecurityGroup`.

Running this after `Set-AzNetworkSecurityRuleConfig` worked for me, thanks.

```powershell
$null = Set-AzNetworkSecurityGroup-NetworkSecurityGroup $nsg
```
