### ISSUE TITLE
"get-azvm -status -Warningaction ignore" skips to query for a mount of vms when it hit 100 limit

### ISSUE THREAD

**Issue by GLLJJ** [Azure/azure-powershell#15514]
## Description
When query "get-azvm -status", the output skips to show some of the vm status as following image: 
![image](https://user-images.githubusercontent.com/61037282/126593097-6fdca621-1f36-48aa-97d6-0d6a2070bbc2.png)
This was occurred on a subscription and the other subscription which in same tenant works fine with 500+ vms. 

It was ran on the latest powershell and az module. 
![image](https://user-images.githubusercontent.com/61037282/126593791-ddeb92c9-c538-4d55-8aea-fe7217a3e678.png)

According to the [document]( https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-6.4.0#azcompute-22), it's "Limit the number of VM status to 100 to avoid throttling when Get-AzVM -Status is performed without VM name." 
And the following prompted when run "get-azvm -status" for 300+ VMs.
    WARNING: There are more than 100 VMs in the result.  Only the statuses of 100 VMs are shown to avoid throttling.  To get the actual status of each VM, please provide a VM name with -Status parameter.
   Confirm
   Continue with this operation?

To continue the query without prompt, we added "-Warningaction ignore" flag. And we got the same result as the above capture. 
From the debug output, I see in every time when it hit the 100 VMs , WARNING prompted, at the same time it skips to send out the query for next a mount of VMs, then repeat, like query 100 VMs then skip some, query 100 VMs then skip some... 
No "HTTP REQUEST" sent out for those skipped VMs. 
![image](https://user-images.githubusercontent.com/61037282/132538031-d6664c43-b9ef-40de-98a3-4689722445e0.png)

## Question: 
1. Is it seems like by-design? 
2. Any function that I missed? Like adding a flag?

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Please just fetch the status of one issue VM and share us the debug message again.

**Comment by amjads1** [comment]
@avirishuv Could you please look into this issue?

**Comment by GLLJJ** [comment]
@avirishuv appreciate if you could help to look into this one.

**Comment by avirishuv** [comment]
hi @GLLJJ are you continuing to see this issue? As mentioned in this issue https://github.com/Azure/azure-powershell/issues/13178 , power state can sometimes fail to be returned. Happy to answer if you have additional questions.

**Comment by GLLJJ** [comment]
@avirishuv Thanks for your note. In #13178, it happens randomly, so seems not match with this one. 
I've updated the issue description according to the recent troubleshooting founds and got 2 questions there. Any suggestion is welcomed. 
Additionally, I've created the following script and waiting for the result from CX.
![image](https://user-images.githubusercontent.com/61037282/132541341-f9147830-7f6c-4da3-9a97-ff23749b195a.png)

**Comment by avirishuv** [comment]
Thanks @GLLJJ for additional context. Let me look into this in more detail and get back.

**Comment by avirishuv** [comment]
@GLLJJ to clarify, the " -Warningaction ignore " flag does not change the behavior of the cmdlet - it simply stops displaying the warning. The response should remain the same when this is used as when the flag is not used.

Hope that helps, please let me know if any follow-up questions.

**Comment by GLLJJ** [comment]
Thanks @avirishuv, I agree that the "-warningactio ignore" flag does not change any. 
 
"Get-azvm -status" have 2 steps,
First, it gets the vmlist
![image](https://user-images.githubusercontent.com/61037282/133040223-9e7667dc-fdad-4644-9a5c-a09b707a3ab6.png)
Then, send http request for those VMs listed from above.  
![image](https://user-images.githubusercontent.com/61037282/133040060-295b9c54-c459-4fa7-8729-d91a86696b1a.png)

The problem here was that, all VMs was listed from 1st step, but no http request sent to query the status of those VMs which were listed in sequence of 100+, 200+, 300+.  As the result, 219 of 1458 VMs has been left out. Seems that some VMs skipped to be queried when it hits throttling. 

As long as the following script was worked to query the status of all VMs, the user would like to apply this work around when required even it takes1.5hrs to run :) 
$report = @()
$VMs = Get-Azvm -status -name *    
foreach ($vm in $VMs) {
    $info = "" | Select ResourceGroupName, Name, Location, VmSize, OsType, NIC, ProvisioningState, Zone, PowerState, MaintenanceAllowed
    $info.Name=$vm.Name
    $info.ResourceGroupName=$vm.ResourceGroupName
    $info.Location=$vm.Location
    $info.VmSize=$vm.hardwareProfile.vmSize
    $info.OsType=$vm.storageProfile.osDisk.OsType
    $CharArray =$vm.networkProfile.networkInterfaces.id.Split("/")
    $info.NIC=$CharArray[$CharArray.count-1] 
    $info.ProvisioningState=$vm.ProvisioningState
    $info.Zone=$vm.Zones 
    $info.PowerState=$vm.PowerState
    $info.MaintenanceAllowed=$vm.MaintenanceAllowed
   If($vm.PowerState -eq $null){
        $vmNew = Get-Azvm -Name $vm.Name -Status 
        $info.PowerState = $vmNew.PowerState
    }
   
    $report+=$info
}
$report | ft ResourceGroupName, Name, Location, VmSize, OsType, NIC, ProvisioningState, Zone, PowerState, MaintenanceAllowed
