### ISSUE TITLE
Information on how to speedup Azure PowerShell Module installs

### ISSUE THREAD

**Issue by dhekimian** [Azure/azure-powershell#15525]
## Description of the new feature
After spending more than a day trying to troubleshoot various performance issues with our Automated Builds that include the Azure PowerShell Modules, I wanted to pass along the findings for others who might run into the same issues.

## Proposed implementation details (optional)
Update the README to make this information easier for others to find

## Details
I noticed on a fresh Windows 2019 build that installing AZ via PowerShell Gallery was extremely slow also but after upgrading key packages, installing ALL PowerShell Modules were significantly faster.

I was able to install the AZ PowerShell Module in ~5 minutes after updating the relevant PowerShell packages.

Via [Chocolatey](https://chocolatey.org/), it took less than 30 seconds to download and install all the AZ Modules. YMMV

I found 3 different solutions:
## 1. Update PowerShell Packages/Modules (Works for All PowerShellGallery Module Installs)

**To check versions of installed modules:**
``` powershell
Get-Module -ListAvailable
or
Get-Module -Name PowerShellGet
```

**To update the relevant packages:**
``` powershell
Write-Output ==^> Install latest NuGet
Install-PackageProvider NuGet -Force

Write-Output ==^> Set PowerShell Gallery to Trusted
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

Write-Output ==^> Install latest PowerShellGet
# *PowerShellGet* also updates its dependency *PackageManagement*
Install-Module PowerShellGet -Force

Write-Output ==^> Install latest PSReadLine
Install-Module PSReadLine -Force
```
## 2. Install Azure PowerShell Module via MSI Package
You need to find the AZ release version you want to install and download it. 
- Releases Page - https://github.com/Azure/azure-powershell/releases
- 6.2.1 Release:  https://github.com/Azure/azure-powershell/releases/tag/v6.2.1-July2021 (look under Assets)
- 6.2.1 MSI Download Link: https://github.com/Azure/azure-powershell/releases/download/v6.2.1-July2021/Az-Cmdlets-6.2.1.34515-x64.msi

## 3. Install Azure PowerShell Module via Chocolatey
- Azure PowerShell Chocolatey Package - https://community.chocolatey.org/packages/az.powershell
- `choco install az.powershell`
- `choco install az.powershell --version=5.9.0` (If you need a specific version)

**Comment by dingmeng-xue** [comment]
Thanks much for your information. We will work on it and update the docs.

FYI, @dcaro @mikefrobbins

**Comment by sohilagrawal20** [comment]
I tried using above cmdlet, it is still very slow and ending up without install even after 1 hour of execution of command. 

Any other suggestion to install Az on powershell, I tried Option 1st and 3rd.

Install-Module -Name Az -Repository PSGallery -Force

**Comment by dcaro** [comment]
Thanks for opening this issue, there has been some issues related to the PowerShell gallery in the last few days that have impacted how long it took to install Az. Also we are looking for ways to improve the installation of Az.

**Comment by mikefrobbins** [comment]
@dhekimian Can you confirm if this is still an issue since the problems that @dcaro mentioned should now be resolved. Installing via Chocolatey isn't an option since it goes against our best practices and installs in the all users scope and requires admin rights.

**Comment by mikefrobbins** [comment]
Closing this issue since it only took about 3 minutes to install the Az PowerShell module on a new Windows Server 2019 system with no other updates.

![image](https://user-images.githubusercontent.com/6719572/131754158-5ee8c218-0e0c-4c82-85c8-1f947bcc4889.png)

**Comment by dhekimian** [comment]
@mikefrobbins Are the issues with the PowerShell Gallery resolved for good? 

While many may prefer `Install-Module az` to install via the PowerShell Gallery, knowing that it can be installed via the MSI &/or Chocolatey is extremely useful for those of us who use it in CI/CD Jobs, Automation Tasks, etc. that run dozens or more times per day especially when PSGallery is having issues...

**Comment by mikefrobbins** [comment]
@dhekimian Installing the Az PowerShell module via MSI is supported and the instructions are outlined in our installation documentation. For more details, see: "[Install Azure PowerShell on Windows with MSI](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps-msi)".

While Chocolatey is not one of our official installation methods, Microsoft doesn't prevent customers from using it as an installation option.

One thing to make note of from your original recommendation is that if you're using Windows PowerShell to install from the PowerShell Gallery, our installation instructions state "Make sure you have the latest version of PowerShellGet. Run `Install-Module -Name PowerShellGet -Force`". For more details, see: "[Installation on Windows PowerShell](https://docs.microsoft.com/powershell/azure/install-az-ps#installation-on-windows-powershell)".

One thing to consider if you're performing the installation dozens or more times a day is to only install the modules that are needed and not the entire Az PowerShell module. For example, you could run the following if you're only using cmdlets from the Az.Network and Az.Storage modules:

```powershell
Install-Module -Name Az.Network, Az.Storage -Force
```

I have asked the PowerShell team to respond to your question about the issues with the PowerShell Gallery.

**Comment by adityapatwardhan** [comment]
@dhekimian Thank you for the feedback about the PowerShell Gallery. We understand that there have been reliability issues recently and are fully committed to improve it. If you see further issues, please file an issue at: https://github.com/PowerShell/PowerShellGallery/issues and feel free to tag me.
