### ISSUE TITLE
Question about changing App Service Configuration

### ISSUE THREAD

**Issue by Alessar** [Azure/azure-powershell#15522]
At the Azure portal, there is the capability to change settings related to .NET version.
`App Service` -> `Configuration` -> `General settings` -> `.NET version`
It is changeable by the Azure portal and it works well.

* Is there any capability to change that option via the PowerShell function? (Az module)
* Is there any capability to change that option via ARM templates?
* Is there any documentation about it? Possible values, meanings, etc?

**Comment by Kotasudhakarreddy** [comment]
- Is there any capability to change that option via the PowerShell function? (Az module)
**Ans:** Yes, there is a cmdlet available to change the target version. Refer to [this](https://docs.microsoft.com/en-us/powershell/module/az.websites/set-azwebapp?view=azps-7.2.0#syntax) for more information.
**example:** : `Set-AzWebApp -ResourceGroupName <your-RG-Name> -Name <your-app-name> -NetFrameworkVersion "v4.8"`
- Is there any capability to change that option via ARM templates?
**Ans:** Please rise a clarification with ARM template team.
- Is there any documentation about it? Possible values, meanings, etc?
**Ans:** Yes, to get the possible values you can use below command and refer [here](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-list-runtimes) for more details.
`az webapp list-runtimes`

**Comment by SaurabhSharma-MSFT** [comment]
@Alessar Please let us know in case you have any questions.  Thanks.

**Comment by Kotasudhakarreddy** [comment]
closing due to lack of response. Please file a new issue if this is still a problem.
