### ISSUE TITLE
Command to list SKUs Codes

### ISSUE THREAD

**Issue by bjosafa** [Azure/azure-powershell#15526]
I would like to get a list of the current SKUs codes, not only the name, for my subscription. Is that already possible or it should be added as a feature?

Virtual Machines (West US - VM 1 D2 v3) = AAA-44930 (Sku code) <- that information that I want

[It was requested also for az cli](https://github.com/Azure/azure-cli/issues/18964)

**Comment by dingmeng-xue** [comment]
@bjosafa , could you try this one?
https://docs.microsoft.com/en-us/powershell/module/az.compute/get-azvmsize?view=azps-6.2.1#example-1--get-virtual-machine-sizes-for-a-location

**Comment by bjosafa** [comment]
@dingmeng-xue, it returns some information related to the vm, but it does not bring the sku code.

**Comment by avirishuv** [comment]
Assigning to @jaylabell who is looking at the same request on this other thread: https://github.com/Azure/azure-cli/issues/18964

**Comment by jaylabell** [comment]
Looking into this issue; Updates will be provided shortly.

**Comment by bjosafa** [comment]
Hi, any news?

**Comment by navba-MSFT** [comment]
@bjosafa Apologies for the late reply. We are looking into this issue. We will update this thread once we have more details. In the meantime, if you need any further assistance on this issue, do let us know.

@jaylabell Could you please provide an update on this issue ? Awaiting your reply.

**Comment by jaylabell** [comment]
@bjosafa can you please clarify what you mean by SKU code? Is this related to billing?

**Comment by bjosafa** [comment]
@jaylabell yes... e.g.: Virtual Machines (West US - VM 1 D2 v3) = AAA-44930 (Sku code) <- that information that I want

**Comment by Drewm3** [comment]
@bjosafa, could you provide a URL or additional context on where you are seeing "AAA-44930"? Generally the compute resource provider layer of the platform doesn't have these specific billing related items. We provide the commerce system with the VM details and the region in which the VM is running, and then that information is translated into billing codes. So, I do not believe we are going to be able to provide this information in the VM powerShell cmdlets, but we may be able to point you in the right direction where you could get this information programmatically if you can provide us some more details on where you are seeing the code.
