### ISSUE TITLE
module only partially imported

### ISSUE THREAD

**Issue by droushd** [Azure/azure-powershell#15531]
get-command -Module az.storage | measure == 59 

it looks like there are closer to 100 Cmdlets in the module.  i'm seeing various issues with other modules lately too so might just be me.  will create a premier ticket too.

**Comment by droushd** [comment]
{
    "PSMessageDetails":  null,
    "Exception":  {
                      "Message":  "Could not load file or assembly \u0027Azure.Core, Version=1.14.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8\u0027 or one of its dependencies. The system cannot find the file specified.",
                      "FileName":  "Azure.Core, Version=1.14.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8",
                      "FusionLog":  "WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog] (DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\\Software\\Microsoft\\Fusion!EnableLog].\r\n",
                      "Data":  {

                               },
                      "InnerException":  null,
                      "TargetSite":  {
                                         "Name":  "GetExportedTypes",
                                         "DeclaringType":  "System.Reflection.RuntimeAssembly, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                                         "ReflectedType":  "System.Reflection.RuntimeAssembly, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
                                         "MemberType":  8,
                                         "MetadataToken":  100680383,
                                         "Module":  "CommonLanguageRuntimeLibrary",
                                         "IsSecurityCritical":  true,
                                         "IsSecuritySafeCritical":  false,
                                         "IsSecurityTransparent":  false,
                                         "MethodHandle":  "System.RuntimeMethodHandle",
                                         "Attributes":  24721,
                                         "CallingConvention":  1,
                                         "ReturnType":  "void",
                                         "ReturnTypeCustomAttributes":  "Void ",
                                         "ReturnParameter":  "Void ",
                                         "IsGenericMethod":  false,
                                         "IsGenericMethodDefinition":  false,
                                         "ContainsGenericParameters":  false,
                                         "MethodImplementationFlags":  128,
                                         "IsPublic":  false,
                                         "IsPrivate":  true,
                                         "IsFamily":  false,
                                         "IsAssembly":  false,
                                         "IsFamilyAndAssembly":  false,
                                         "IsFamilyOrAssembly":  false,
                                         "IsStatic":  true,
                                         "IsFinal":  false,
                                         "IsVirtual":  false,
                                         "IsHideBySig":  true,
                                         "IsAbstract":  false,
                                         "IsSpecialName":  false,
                                         "IsConstructor":  false,
                                         "CustomAttributes":  "[System.Runtime.InteropServices.DllImportAttribute(\"QCall\", EntryPoint = \"GetExportedTypes\", CharSet = 3, ExactSpelling = False, SetLastError = False, PreserveSig = True, CallingConvention = 1, BestFitMapping = False, ThrowOnUnmappableChar = False)] [System.Runtime.InteropServices.PreserveSigAttribute()] [System.Security.SecurityCriticalAttribute()] [System.Security.SuppressUnmanagedCodeSecurityAttribute()]"
                                     },
                      "StackTrace":  "   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)\r\n   at System.Reflection.RuntimeAssembly.GetExportedTypes()\r\n   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)\r\n   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad, Dictionary`2\u0026 cmdlets, Dictionary`2\u0026 aliases, Dictionary`2\u0026 providers, String helpFile, Type\u0026 randomCmdletToCheckLinkDemand, Type\u0026 randomProviderToCheckLinkDemand)\r\n   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad, Dictionary`2\u0026 cmdlets, Dictionary`2\u0026 aliases, Dictionary`2\u0026 providers, String\u0026 helpFile)\r\n   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)\r\n   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean\u0026 found, String shortModuleName, Boolean disableFormatUpdates)\r\n   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions\u0026 options, ManifestProcessingFlags manifestProcessingFlags, Boolean\u0026 found, Boolean\u0026 moduleFileFound)\r\n   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)\r\n   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()\r\n   at System.Management.Automation.CommandProcessor.ProcessRecord()",
                      "HelpLink":  null,
                      "Source":  "mscorlib",
                      "HResult":  -2147024894
                  },
    "TargetObject":  null,
    "CategoryInfo":  {
                         "Category":  0,
                         "Activity":  "Import-Module",
                         "Reason":  "FileNotFoundException",
                         "TargetName":  "",
                         "TargetType":  ""
                     },
    "FullyQualifiedErrorId":  "System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand",
    "ErrorDetails":  null,
    "InvocationInfo":  {
                           "MyCommand":  {
                                             "Verb":  "Import",
                                             "Noun":  "Module",
                                             "HelpFile":  "System.Management.Automation.dll-Help.xml",
                                             "PSSnapIn":  "Microsoft.PowerShell.Core",
                                             "Version":  "3.0.0.0",
                                             "ImplementingType":  "Microsoft.PowerShell.Commands.ImportModuleCommand",
                                             "Definition":  "\r\nImport-Module [-Name] \u003cstring[]\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-MinimumVersion \u003cversion\u003e] [-MaximumVersion \u003cstring\u003e] [-RequiredVersion \u003cversion\u003e] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [\u003cCommonParameters\u003e]\r\n\r\nImport-Module [-Name] \u003cstring[]\u003e -PSSession \u003cPSSession\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-MinimumVersion \u003cversion\u003e] [-MaximumVersion \u003cstring\u003e] [-RequiredVersion \u003cversion\u003e] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [\u003cCommonParameters\u003e]\r\n\r\nImport-Module [-Name] \u003cstring[]\u003e -CimSession \u003cCimSession\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-MinimumVersion \u003cversion\u003e] [-MaximumVersion \u003cstring\u003e] [-RequiredVersion \u003cversion\u003e] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [-CimResourceUri \u003curi\u003e] [-CimNamespace \u003cstring\u003e] [\u003cCommonParameters\u003e]\r\n\r\nImport-Module [-FullyQualifiedName] \u003cModuleSpecification[]\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [\u003cCommonParameters\u003e]\r\n\r\nImport-Module [-FullyQualifiedName] \u003cModuleSpecification[]\u003e -PSSession \u003cPSSession\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [\u003cCommonParameters\u003e]\r\n\r\nImport-Module [-Assembly] \u003cAssembly[]\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [\u003cCommonParameters\u003e]\r\n\r\nImport-Module [-ModuleInfo] \u003cpsmoduleinfo[]\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [\u003cCommonParameters\u003e]\r\n",
                                             "DefaultParameterSet":  "Name",
                                             "OutputType":  "System.Management.Automation.PSModuleInfo",
                                             "Options":  1,
                                             "Name":  "Import-Module",
                                             "CommandType":  8,
                                             "Source":  "Microsoft.PowerShell.Core",
                                             "Visibility":  0,
                                             "ModuleName":  "Microsoft.PowerShell.Core",
                                             "Module":  null,
                                             "RemotingCapability":  1,
                                             "Parameters":  "System.Collections.Generic.Dictionary`2[System.String,System.Management.Automation.ParameterMetadata]",
                                             "ParameterSets":  "[-Name] \u003cstring[]\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-MinimumVersion \u003cversion\u003e] [-MaximumVersion \u003cstring\u003e] [-RequiredVersion \u003cversion\u003e] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [\u003cCommonParameters\u003e] [-Name] \u003cstring[]\u003e -PSSession \u003cPSSession\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-MinimumVersion \u003cversion\u003e] [-MaximumVersion \u003cstring\u003e] [-RequiredVersion \u003cversion\u003e] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [\u003cCommonParameters\u003e] [-Name] \u003cstring[]\u003e -CimSession \u003cCimSession\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-MinimumVersion \u003cversion\u003e] [-MaximumVersion \u003cstring\u003e] [-RequiredVersion \u003cversion\u003e] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [-CimResourceUri \u003curi\u003e] [-CimNamespace \u003cstring\u003e] [\u003cCommonParameters\u003e] [-FullyQualifiedName] \u003cModuleSpecification[]\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [\u003cCommonParameters\u003e] [-FullyQualifiedName] \u003cModuleSpecification[]\u003e -PSSession \u003cPSSession\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [\u003cCommonParameters\u003e] [-Assembly] \u003cAssembly[]\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [\u003cCommonParameters\u003e] [-ModuleInfo] \u003cpsmoduleinfo[]\u003e [-Global] [-Prefix \u003cstring\u003e] [-Function \u003cstring[]\u003e] [-Cmdlet \u003cstring[]\u003e] [-Variable \u003cstring[]\u003e] [-Alias \u003cstring[]\u003e] [-Force] [-PassThru] [-AsCustomObject] [-ArgumentList \u003cObject[]\u003e] [-DisableNameChecking] [-NoClobber] [-Scope \u003cstring\u003e] [\u003cCommonParameters\u003e]"
                                         },
                           "BoundParameters":  {

                                               },
                           "UnboundArguments":  [

                                                ],
                           "ScriptLineNumber":  2,
                           "OffsetInLine":  1,
                           "HistoryId":  11,
                           "ScriptName":  "",
                           "Line":  "Import-Module (Join-Path -Path $aa -ChildPath Microsoft.Azure.PowerShell.Cmdlets.Storage.dll)\n",
                           "PositionMessage":  "At line:2 char:1\r\n+ Import-Module (Join-Path -Path $aa -ChildPath Microsoft.Azure.PowerSh ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
                           "PSScriptRoot":  "",
                           "PSCommandPath":  null,
                           "InvocationName":  "Import-Module",
                           "PipelineLength":  0,
                           "PipelinePosition":  0,
                           "ExpectingInput":  false,
                           "CommandOrigin":  1,
                           "DisplayScriptPosition":  null
                       },
    "ScriptStackTrace":  "at \u003cScriptBlock\u003e, \u003cNo file\u003e: line 2",
    "PipelineIterationInfo":  [

                              ]
}

**Comment by dingmeng-xue** [comment]
It works on the latest version. Please use the latest Az.Storage module and import-module in a new PowerShell session. 
```
PS C:\> get-command -Module az.storage | measure

Count             : 155
Average           :
Sum               :
Maximum           :
Minimum           :
StandardDeviation :
Property          :


PS C:\> get-module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.5.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     3.9.0                 az.storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle…}
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     2.2.0      beta3      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler…}

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.6
PSEdition                      Core
GitCommitId                    7.2.0-preview.6
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
