### ISSUE TITLE
New-AzureRmVirtualNetworkGatewayIpConfig :: No docs

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1554]
<img width="1044" alt="screen shot 2015-12-29 at 10 31 12 am" src="https://cloud.githubusercontent.com/assets/466713/12038762/f82d2dbe-ae17-11e5-86ba-1795d4fcf0c6.png">

**Comment by cormacpayne** [comment]
@Nilambari Hey Nilambari, would you mind pointing me at the right owner for this cmdlet?

**Comment by maddieclayton** [comment]
Looks like this issue was fixed, closing.
