### ISSUE TITLE
No documentation for context, profile, subscription relationship

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1555]
We need documentation for the relationship between these ARM PowerShell objects:
1. Azure Contexts
2. Azure Profiles
3. Azure Subscriptions

A visual diagram would be great, but a textual description would suffice for the time being.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by markcowl** [comment]
@coreyp-at-microsoft  a candidate for the top 5 list for new documentation

**Comment by pcgeek86** [comment]
@coreyp-at-msft

**Comment by markcowl** [comment]
@pcgeek86 This is planned for the *next* blog release, which is targeted for second week of May release.

**Comment by markcowl** [comment]
### Cost (work units): 4

**Comment by cormacpayne** [comment]
Assining to @twitchax to work with documentation/Sean to resolve this

**Comment by markcowl** [comment]
The context persistence updates are a perfect time to update this documentation, for Ignite

**Comment by markcowl** [comment]
There is now a doc on docs.microsoft.com: https://docs.microsoft.com/en-us/powershell/azure/context-persistence?view=azurermps-4.4.0
