### ISSUE TITLE
Set-AzStorageBlobContent not terminate and seems blocked by New-Object System.Windows.Forms.Form

### ISSUE THREAD

**Issue by lzy8513** [Azure/azure-powershell#15556]
## Description
When use **Set-AzStorageBlobContent** after **New-Object System.Windows.Forms.Form**, the upload command will never stop as the screenshot below.

![image](https://user-images.githubusercontent.com/10989739/127089925-3e4a769f-7c02-466f-8f6b-e83ee42ae368.png)

The upload operation is successful actually. 
![image](https://user-images.githubusercontent.com/10989739/127090411-6ce324a4-2499-4fe8-9c6e-8481c8489537.png)

Please find the sample code below.

## Steps to reproduce

sample code

```powershell

$ctx = New-AzStorageContext -StorageAccountName $storage_account_name -StorageAccountKey $storage_account_key
# bug
[void][System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
$UserAdminForm = New-Object System.Windows.Forms.Form
# upload
Set-AzStorageBlobContent -Context $ctx -Container "fileupload" -File ".\file.png" -Debug

```

## Environment data

PowerShell Version
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1023
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1023
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

## Module versions

Az.Storage Version

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.9.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}

```

## Debug output

Please find in the screenshot below.

## Other
Please let me know if you need any other information.
jerome.liu@microsoft.com

**Comment by lzy8513** [comment]
Additionally, if **Set-AzStorageBlobContent** executed **_before_** **New-Object System.Windows.Forms.Form**, everything is good.

**Comment by blueww** [comment]
@lzy8513 
Thanks for reporting this issue!
I can repro this issue locally.
It looks the hang happens on a depends library of Azure Powershell.  I will need more time to look deeper into it.

There's a workaround, in my test if you run the cmdlet async with -Asjob, then wait for upload complete, the job won't hang:
```powershell
$task = Set-AzStorageBlobContent -Container $containerName -Blob $blobName -File $localSrcFile -Context $ctx -Force -asjob 
$task  | Wait-Job
```

**Comment by lzy8513** [comment]
@blueww Thanks for the help. It works in my end.

**Comment by blueww** [comment]
@EmmaZhu 

Would you please help to follow up the hang issue?

**Comment by EmmaZhu** [comment]
We suspect this is an issue in .Net framework, and we made a simple repro and opened an issue in .Net repository: 
https://github.com/dotnet/sdk/issues/19494
