### ISSUE TITLE
New-AzResourceGroupDeployment -WhatIf is showing existing resources as if they are being created

### ISSUE THREAD

**Issue by markwragg** [Azure/azure-powershell#15565]
I have run `New-AzResourceGroupDeployment -WhatIf` today and am suddenly seeing the report show that all of the existing resources in the Resource Group as if they will be newly created. I am seeing this behaviour for runs via Azure DevOps cloud VMs as well as locally and for different resource groups / templates. The tool worked previously and while showing a lot of modifications that wouldn't really occur, it always reported the new resources that would be created correctly.

Has something perhaps changed recently that has broken the output?

**Comment by majastrz** [comment]
Do you have the correlation IDs by any chance for the what-if runs? Also, which version of Az PowerShell are you using?

**Comment by markwragg** [comment]
Sorry I think this was my mistake actually, I was running an old version of my template and so the new resources were legitimate. Apologies for any time wasted.
