### ISSUE TITLE
Change release standards to include demand for documentation

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1556]
Please amend the release standards for ARM PowerShell such that any command lacking sufficient documentation cannot be released publicly. Azure engineering teams should be required to include detailed documentation, prior to releasing any of their PowerShell commands.

I really shouldn't be spending my time filing bugs like:

#1555 
#1549
#1423 
#1359 
#866
#767 
#638 
#633 

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by pcgeek86** [comment]
If the document does not yet exist, please create it per #1557. 

Cheers,
Trevor Sullivan

**Comment by markcowl** [comment]
@pcgeek86 We have added static reports for missing help here:  https://github.com/Azure/azure-powershell/tree/dev/tools/StaticAnalysis/HelpAnalyzer

The plan is to drive these down with feature teams over the next few sprints and make this fail the build once that is done.

**Comment by pcgeek86** [comment]
@markcowl Excellent. Let's keep this open until the build fails due to missing help.

**Comment by markcowl** [comment]
@pcgeek86 yep.  To set expectations, we are enabling failures on new help omissions immediately after the release (3/3).  We will drive back-filling the existing gaps, but expect that this will take a bit of time.  
 
Note that, if you build now, you will see a set of static cnalysis reports in the Pacakeg directory for your configuration.

**Comment by markcowl** [comment]
@pcgeek86 Fixed.  New missing help will cause the build to fail.  Will beef up these checks over the next couple of sprints to ensure that help is also up to date and correct.

**Comment by pcgeek86** [comment]
@markcowl Great, thanks a lot. Looking forward to the quality improvements, and fewer gaps, if any. :smile:
