### ISSUE TITLE
Azure Deployment Tags - What is use of Tag Parameter and Where can we see those tags on Azure Portal?

### ISSUE THREAD

**Issue by jagratimodi** [Azure/azure-powershell#15571]
I am trying to create a Resource group deployment with tags using below command - 

```
New-AzResourceGroupDeployment -ResourceGroupName "demo" -TemplateFile "D:\Templates\storage.json" -Tag @{"CreatedFrom"="PS";}
```

![image](https://user-images.githubusercontent.com/22763130/127294068-66b73a02-b83c-4fb2-8835-9e38a711a4a4.png)

I can get the tags by fetching the deployment using below command -  

![image](https://user-images.githubusercontent.com/22763130/127294367-e87cb152-5b29-4714-923e-9dee24643698.png)

**My queries are -** 

**1. I can assign the tags while creating deployment but Where I can view those associated tags on Azure Portal?
2. What is use of this Azure Deployment Tag parameter?**

![Untitled](https://user-images.githubusercontent.com/22763130/127295083-ee001ef1-ad4f-4da2-b272-5c8e125b0cf2.png)

**Comment by jagratimodi** [comment]
@KranthiPakala-MSFT Hey Thanks for the reply. I am confused with deployment tags. Otherwise I am aware of tags for Resource Groups and other resources. But my query is what is use of applying tags to deployment as I have explained in my question?

**Comment by navba-MSFT** [comment]
@jagratimodi Apologies for the late reply. Here is the answer to your query on the deployment tags:

Deployment tags and resource tags both of these provide an easy way to organize your Azure resources and Resources Groups _(Deployment resource groups)_, by allowing you to tag your resources with name/value pairs to further categorize and view resources across resource groups and across subscriptions.  For example, you could use tags to identify which of your resources are used for “production” versus “dev/test” – and enable easy filtering/searching of the resources based on which tag you were interested in – regardless of which application or resource group they were in.  

Please let us know if you have any further queries on this or we can proceed with closure of this github issue.

**Comment by navba-MSFT** [comment]
@jagratimodi Hope you had a chance to look at my above comment. This github thread has been inactivity for quite sometime. So for now we will proceed with closure of this thread. If you have any follow-up questions on this, please feel free to reopen this thread we would be happy to answer those.
