### ISSUE TITLE
[Compute] Add the hint to suggest users use the standard public IP when creating VM

### ISSUE THREAD

**Issue by brianlehr** [Azure/azure-powershell#15574]
Description

In the latest profile and the profiles that use the same api-version as latest profile, the default public IP used for VM creation will be expected to be changed from Basic to Standard in ~2-3 years.  In order to avoid breaking change which has a big impact on users, we use the hint to guide users to use Standard public IP to create VM in the first stage.

Specific Feature Request

When user runs New-AzVM without specifying a _-PublicIPAddressName_ AND _-AllocationMethod Standard_, we should add the message **"It is recommended to use parameter "-AllocationMethod Standard" to create new VM with Standard public IP. Please note that it will become the default behavior for VM creation in the future.”** 

This is the equivalent of this request in CLI, which has already been implemented: [https://github.com/Azure/azure-cli/pull/18662](https://github.com/Azure/azure-cli/pull/18662).

**Comment by axayjo** [comment]
@avirishuv can you take a look at this?

**Comment by brianlehr** [comment]
Hi team, any questions about this request?  It has been implemented in CLI for a couple months already.

**Comment by jaylabell** [comment]
Working to update this issue

**Comment by brianlehr** [comment]
Hello again, it's been quite a few months.  @jaylabell - what is eta for this?  it seems like a very straightforward and simple change, it's just adding text notification at time of VM creation.

**Comment by thisisanniefang** [comment]
@jaylabell Hi Jayla, any updates here? We are trying to move forward towards making Standard the default and need this as a prerequisite.

**Comment by jaylabell** [comment]
This item was completed https://msazure.visualstudio.com/One/_workitems/edit/14469917
