### ISSUE TITLE
Add a doc to instruct the installation of package in tarball

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/azure-powershell#15575]
## Description of the new feature
We have a new way to install Az modules now -- via tarball, we need a guide to instruct customer the way to install Az via tarball.
https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.2.1

The step to install Az via tarball
1. Extract Packages from tarball
```command
tar -xvzf Az-Cmdlets-6.2.1.34576.tar.gz
```
2. Install via a signed script
 ```powershell
.\InstallModule.ps1
```

**Comment by BethanyZhou** [comment]
Looks like we should take the release of tarball on hold as the discussion on morning sprint review meeting. Its related docs should be held on as well.

**Comment by dcaro** [comment]
We should sign the included script and package before making this an official installation method.

**Comment by BethanyZhou** [comment]
The script has already been signed. And we calculate SHA256 of Az-Cmdlets-x.x.x.tar.gz to allow customer verify the tarball.

**Comment by mikefrobbins** [comment]
Installing Az via tarball is documented in the [Install from tar archive](https://learn.microsoft.com/powershell/azure/install-azps-offline#install-from-tar-archive) section of the [Offline Installation of Azure PowerShell](https://learn.microsoft.com/powershell/azure/install-azps-offline) conceptual article.
