### ISSUE TITLE
Make release standards document available for public consumption and contribution

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1557]
If there is a document that covers the release standards for Azure PowerShell commands, please share it publicly, and invite public feedback / contribution to it. If such a document does not exist, please create one.

The document should cover the following topics, at a minimum:
- Azure PowerShell command naming
- Azure PowerShell parameter naming
- Azure PowerShell command output
- Azure PowerShell command pipeline support
- Azure PowerShell error handling
- Azure PowerShell documentation standards (including about_\* topics and built-in command help (MAML))

In order for Azure PowerShell to be "best in class," it needs to have tight standards around these matters. The PowerShell core team should be consulted to assist with this, if necessary. I have recommended this many times.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by devigned** [comment]
Thank you for the feedback, @pcgeek86. I think the contributors guide would be good place to kick off this documentation, so we can all contribute to it (rather than a wiki page). Thoughts?

**Comment by pcgeek86** [comment]
Is this what you're referring to, David? The CONTRIBUTING.md file points to this URL.

 http://azure.github.io/guidelines.html

**Comment by devigned** [comment]
@pcgeek86 no, not that. I mean CONTRIBUTING.md itself (and child document links). It shows up when ever anyone creates a pull request. It should have all of the required information for a contribution to be accepted. 

I agree, the azure.github.io/guidelines are far to vague to be directly applicable. Each item in the contributing guide needs to be tactical and measurable.

**Comment by devigned** [comment]
@mayurid thoughts on this?

**Comment by devigned** [comment]
better yet, @Azure/adx-sdk-team thoughts on this?

**Comment by pcgeek86** [comment]
Yep, we are on the same page. Add to `CONTRIBUTING.md` itself. It got jumbled in with the rest of my last message. It wasn't a very well-structured paragraph.

**Comment by kilasuit** [comment]
Couldn't agree more with this - and there should be more transparency as to the End to End release process. There are plenty of individuals that would review documentation prior to a release instead of there being a release with no documentation.

**Comment by markcowl** [comment]
@pcgeek86 @devigned It sounds like the ask is really for updated coding standards and static analysis checks.  I *think* this properly belongs in the wiki.

**Comment by markcowl** [comment]
I think this is covered by our current wiki documentation, Please reopen if ther is a specific ask
