### ISSUE TITLE
Build fails: too long absolute paths

### ISSUE THREAD

**Issue by vors** [Azure/azure-powershell#156]
I cloned azure-powershell project to folder `C:\projects\dsc-azure-ext\azure-powershell`
And run `tools\Build.ps1`

```
The specified path, file name, or both are too long. The fully qualified file name must be less than 
260 characters, and the directory name must be less than 248 characters.
```

Caused by file `TestNewResourceGroupWithTemplateThenGetWithAndWithoutDetails.json` in one of the subfolders.

**Comment by pcgeek86** [comment]
I ran into the same problem. I cloned it into c:\AzurePS, and that seemed to enable the build to work successfully.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by vors** [comment]
Thanks, Trevor! Unfortunately there are cases when you don't have control on that. I.e. cloud CI systems, like http://www.appveyor.com/

**Comment by markcowl** [comment]
@vors This should be better - unfortunately, there is no absolute fix for all cases

**Comment by vors** [comment]
One possible way to reduce problems for future: add Unit tests to verify max length of filenames and set it to something reasonable, like 150.
