### ISSUE TITLE
New-AzBotService fails with powershell

### ISSUE THREAD

**Issue by stuartri** [Azure/azure-powershell#15608]
## Description

New-AzBotService fails with powershell

"NamedParameterNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet"

It claims to be the subsctipionid but I can see that set earlier in the script with the default and the samples here New-AzBotService (Az.BotService) | Microsoft Docs do not set it.

## Steps to reproduce

# FAILS
New-AzBotService -resourcegroupname $ResourceGroupName -Name $appName -ApplicationId $myApp.AppId -Location $AzureRegion -Sku S1 -Description "The Bot Application" -ApplicationSecret $Secure_String_Pwd -Webapp

However I have debugged and the real reason is 
Above fails because it calls this line
# FAILS – (THIS IS WHAT New-AzBotService CALLS - SO SMALLER REPRO)
$Null = New-AzResourceGroupDeployment -ResourceGroupName $ResourceGroupName -Location $AzureRegion -TemplateParameterObject $Parameter -TemplateFile $TemplateFile @EnvPSBoundParameters 
 
#Commented out the @EnvPSBoundParameters which is created in the SDK
# WORKS - USING THE SDK ARM TEMPLATE webappv4.template.json
$Null = New-AzResourceGroupDeployment -ResourceGroupName $ResourceGroupName -Location $AzureRegion -TemplateParameterObject $Parameter -TemplateFile $TemplateFile #@EnvPSBoundParameters

## Environment data

You have to use version 7 of powershell as teh new-azbotservice requires it, as it uses ConvertFrom-SecureString

## Module versions

Latest

## Debug output

"NamedParameterNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet"

**Comment by dingmeng-xue** [comment]
We will look into it.

**Comment by wyunchi-ms** [comment]
Hi @stuartri , thanks for your contribution! I have fixed this issue in the PR #15634. It will be published in the next release. Please feel free to reopen this issue.
