### ISSUE TITLE
"az ssh vm" equivalent cmdlet

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#15617]
## Description of the new feature
https://docs.microsoft.com/en-us/cli/azure/ssh?view=azure-cli-latest
## Proposed implementation details (optional)
`Connect-AzSshVm -ip <ipaddr>`

**Comment by axayjo** [comment]
@avirishuv can you take a look at this issue?

**Comment by jaylabell** [comment]
There is currently not a cmdlet offering this capability, but plans are being made for development.

**Comment by navba-MSFT** [comment]
@JustinGrote Apologies for the late reply. We are looking into this issue. We will update this thread once we have more details. In the meantime, if you need any further assistance on this issue, do let us know.

@jaylabell Could you please provide an update on this issue ? Awaiting your reply.

**Comment by Drewm3** [comment]
Moving issues assigned to @jaylabell over to @Drewm3.

**Comment by JustinGrote** [comment]
@Drewm3 I believe this command now actually exists as `Enter-AzVM`. Closing
