### ISSUE TITLE
Az.Aks: Support Client Authentication with ExecCredential for AKS

### ISSUE THREAD

**Issue by wasabii** [Azure/azure-powershell#15629]
Currently, when operating with an AKS cluster using managed identities, with an interactive login, one runs `Import-AzAksCredential` to update their `~/.kube/config` file with the appropriate credentials for the AKS instance they're speaking to. These credentials insert a Config object that specifies a user `auth-provider` with name `azure`. Subsequent invocations of `kubectl` can then consult this auth provider. However, the auth provider ends up walking through the Device Flow, prompting for credentials. It does not obtain credentials that were previously set by PowerShell when establishing the context (Connect-AzAccount).

This makes it incapable of doing non-interactive logins from PowerShell scripts which are otherwise perfectly capable of accessing AKS. For instance, in a CI/CD pipeline (Azure DevOps), one might use the `AzurePowerShell@5` task to run a PowerShell script within context of an automatically managed service account. The PowerShell script will run fine. Any `*-Aks*` commands will be able to access AKS clusters just fine. Until they need to invoke `kubectl`, at which point they'll prompt for a login and fail.

This picture is different with AzureCLI. For AzureCLI, the `kubelogin` application can be used to replace the `~/.kube/config` user object with another user object using the Client Authentication Exec feature. This feature causes `kubectl` to invoke an arbitrary executable to obtain a token when it needs to. And one capability of `kubelogin` is to refer back to the azurecli tokens that were already setup.

So, the Azure DevOps `AzureCLI@0` task is capable of intermingling `az aks` and `kubectl` commands under the same identity just fine, as long as the user runs `kubelogin convert-kubeconfig -l azurecli` at some point before using `kubectl`.

Support for running `kubectl` within context of an Azure PowerShell script, under the same identity as the existing PowerShell context, should be added.

This is more difficult for PowerShell than it is for Azure CLI. In the case of Azure CLI, `kubectl` is capable of executing `kubelogin get-token`, which is capable of using the Azure CLI SDK for Go to retrieve the existing credentials, and getting a token suitable for AKS. AzureCLI after all just stores it's current session information inside `~/.az`, which is accessible to any process running in the user context. `kubelogin` ultimately just reads it.

Azure PowerShell however stores its authentication information in Context, ultimately in memory of the original PowerShell host. Thus, the separate `kubectl` process, and whatever process it executes, would not be able to access it.

I am toying around a bit with a solution to this. My attempted solution is to have PowerShell create a named pipe, which it will listen to to answer token requests, and expose the address of that named pipe in an environmental variable, so that `kubectl` can be executed with the capability of communicating back to the parent PowerShell host. The ExecCredential feature of `kubectl` will then be used to simply bridge that named pipe back to `kubectl`, so that it can receive the new token.

**Comment by dingmeng-xue** [comment]
Thanks for reporting and detail analysis. We will look into it and improve managed identities related feature.
