### ISSUE TITLE
Az.Storage support for Blob Tags

### ISSUE THREAD

**Issue by ishepherd** [Azure/azure-powershell#15627]
## Description of the new feature

Add Az.Storage support for [blob tags](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs).

This feature was released in May 2020 and is GA since June 2021.

## Proposed implementation details (optional)

Initially I was looking for ability to add a `x-ms-tags` header to the `Start-AzStorageBlobCopy` function.

For a case like this, you could support it instantly, if there was a `-CustomHeaders` parameter we could use .

**Comment by blueww** [comment]
@ishepherd 

Blob Tags is already supported in preview module of az.storage, the latest version is 3.7.1-preview https://www.powershellgallery.com/packages/Az.Storage/3.7.1-preview

You can install it by (with admin privileges) :
1.	Install the latest PowershellGet 
install-Module PowerShellGet –Repository PSGallery –Force 
2.	Close and reopen the Powershell console 
3.	Install Az.Storage preview module 
Install-Module Az.Storage -Repository PsGallery -RequiredVersion 3.7.1-preview -AllowClobber -AllowPrerelease -Force 
Note: #1,#2 are optional if PowershellGet is already updated.

After install the preview module, and  make sure it's loaded into the Powershell console, For Start-AzStorageBlobCopy, you can use "-Tag @{"tag1" = "value1"; "tag2" = "value2" } " to specify the tags you would like set to the destination blob.

**Comment by ishepherd** [comment]
Thanks @bluevw! I will try that.
