### ISSUE TITLE
Broken Migration From Classic To Arm Storage

### ISSUE THREAD

**Issue by vedkirloskar1995** [Azure/azure-powershell#15631]
Following this documentation to migrate storage from classic storage to ARM
https://docs.microsoft.com/en-us/azure/virtual-machines/migration-classic-resource-manager-ps#step-5-run-commands-to-migrate-your-iaas-resources

PS C:\Users\vekirlos> Select-AzSubscription -SubscriptionName "blahblahsub"

PS C:\Users\vekirlos> Register-AzResourceProvider -ProviderNamespace Microsoft.ClassicInfrastructureMigrate

ProviderNamespace : Microsoft.ClassicInfrastructureMigrate
RegistrationState : Registered
ResourceTypes     : {classicInfrastructureResources}
Locations         : {East Asia, Southeast Asia, East US, East US 2...}

PS C:\Users\vekirlos> $storageAccountName = 'blahblah'
PS C:\Users\vekirlos> Move-AzureStorageAccount -Prepare -StorageAccountName $storageAccountName
Move-AzureStorageAccount : No default subscription has been designated. Use Select-AzureSubscription -Default <subscriptionName> to set the default subscription.
At line:1 char:1
+ Move-AzureStorageAccount -Prepare -StorageAccountName $storageAccount ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Move-AzureStorageAccount], ApplicationException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.StorageServices.MoveStorageAccountCommand

 PS C:\Users\vekirlos> Set-AzContext -Subscription "blahblahsub"

PS C:\Users\vekirlos> Move-AzureStorageAccount -Prepare -StorageAccountName $storageAccountName
Move-AzureStorageAccount : No default subscription has been designated. Use Select-AzureSubscription -Default <subscriptionName> to set the default subscription.
At line:1 char:1
+ Move-AzureStorageAccount -Prepare -StorageAccountName $storageAccount ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Move-AzureStorageAccount], ApplicationException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.StorageServices.MoveStorageAccountCommand
    
   PS C:\Users\vekirlos> Select-AzureSubscription -SubscriptionId "<subId>"
Select-AzureSubscription : The subscription id <subId> doesn't exist.
Parameter name: id
At line:1 char:1
+ Select-AzureSubscription -SubscriptionId <subId>
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Select-AzureSubscription], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Profile.SelectAzureSubscriptionCommand

PS C:\Users\vekirlos> Select-AzureSubscription -SubscriptionName "blahblahsub"
Select-AzureSubscription : The subscription name blahblahsub doesn't exist.
Parameter name: name
At line:1 char:1
+ Select-AzureSubscription -SubscriptionName "blahblahsub"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Select-AzureSubscription], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Profile.SelectAzureSubscriptionCommand 
 

Ive triple checked the subscription and it does exist. However I can't set the AzureSubscription and so this migration can't continue

**Comment by vedkirloskar1995** [comment]
I can't run the migration api, this seems broken. Any comments on what I am doing wrong? Otherwise this needs to be looked at

**Comment by dingmeng-xue** [comment]
@vedkirloskar1995 , thanks for reporting.

`Select-AzSubscription` or `Set-AzContext` comes from Az. The context cannot be shared between Azure (https://www.powershellgallery.com/packages/Azure) and Az.  My understanding is you need to follow instruction `"Now, sign in to your account for the classic deployment model."` in step 4 to select the correct subscription.
