### ISSUE TITLE
Improve Get-AzADUser -SearchString to match AAD search in Azure Portal

### ISSUE THREAD

**Issue by nihonjinboy85** [Azure/azure-powershell#15643]
## Description of the new feature
Currently, `Get-AzADUser -SearchString` is an alias for `Get-AzADUser -StartsWith`, which works fine when searching for a user by their display name. However, it would be great if the `-SearchString` parameter could be independent of `-StartsWith` and could search all user fields (display name, email, alternate email, etc.) to see if any fields CONTAIN the search string.

Example:
`Get-AzADUser -SearchString 'alias@alternate-email.com' # returns $null`, but AAD search in portal returns user as expected.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Since AAD Graph will be retired, we have no plan to change existing cmdlets. We plan to expose equivalent features via MS Graph API. When we release new cmdlets, this feature should be supported. @VeryEarly , @dcaro FYI.

**Comment by nihonjinboy85** [comment]
Thanks for letting me know the planned change, @dingmeng-xue ! Is there a repo or something I can follow to be informed when the change has been made so I can update my scripts? TIA

**Comment by VeryEarly** [comment]
Hi please try Az.Resources 5.1.0 or later
