### ISSUE TITLE
Invoke-AzRestMethod to specify Private Endpoint Network Interface name

### ISSUE THREAD

**Issue by Ayanmullick** [Azure/azure-powershell#15654]
## Description of the new feature

This is a continuation from https://github.com/MicrosoftDocs/azure-docs/issues/78623#issuecomment-896972547. 

Can one use [Invoke-AzRestMethod](https://docs.microsoft.com/en-us/powershell/module/az.accounts/invoke-azrestmethod?view=azps-6.2.1#example-1)  and the  [PE creation API](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/private-endpoints/create-or-update#create-private-endpoint) to specify its Network Interface name? The [existing documentation](https://docs.microsoft.com/en-us/azure/private-link/create-private-endpoint-powershell#create-private-endpoint) doesn't let one comply with a naming standard.

![image](https://user-images.githubusercontent.com/17693249/126421560-f7981b6b-4d8f-4cc6-b96b-96fa1b5e3029.png)

@dcaro

**Comment by dingmeng-xue** [comment]
We are asking network team's feedback

**Comment by dingmeng-xue** [comment]
According to Network team's confirmation, it is not supported yet. The team is plan to improve it in the near future.

**Comment by Ayanmullick** [comment]
> According to Network team's confirmation, it is not supported yet. The team is plan to improve it in the near future.

Is there a tentative timescale for ETA? months, quarters, next year ?

**Comment by dingmeng-xue** [comment]
Sorry, we haven't got clear message. We should keep you updated.

**Comment by Ayanmullick** [comment]
@ivapplyr , is there any documentation around version release cadence? Version '20**20**-05-01' [was released on Jun 9, 2020](https://github.com/Azure/azure-rest-api-specs/commits/main/specification/network/resource-manager/Microsoft.Network/stable/2020-05-01). Would version `05-01-2021` be released this year?

**Comment by ivapplyr** [comment]
Apologies, the date formatting is, "2021-05-01", it is available for private preview testing with ARM Templates. Just need a valid test subscription.

**Comment by dingmeng-xue** [comment]
Network relies on Azure PowerShell team to expose this feature. We plan to complete this work in this year.
