### ISSUE TITLE
Feature in Add-AzKeyVaultKey to generate new key versions based on previous version unless changes are explicitly specified

### ISSUE THREAD

**Issue by nitmatgeo** [Azure/azure-powershell#15651]
I use Add-AzKeyVaultKey to generate new key versions; things worked well for RSA keys but for EC keys, I think generation is not supported as [mentioned here](https://github.com/Azure/azure-powershell/issues/14819).

So, can there be a feature enhancement such that whenever a new versions are generated, the API automatically uses the type, size or curve based on immediate last (current) version (_unless the updated values are explicitly specified_)?

I was getting this error- 'Cannot process command because of one or more missing mandatory parameters: KeyFilePath'. 
```
Add-AzKeyVaultKey -VaultName $triggeredKeyVAultName -Name $triggeredKeyName -KeyType $($latestKey.KeyType) -CurveName $($latestKey.Key.CurveName)
```
Note: First version of Key is already present in KeyVault and type is EC. 

@BethanyZhou @dcaro @dingmeng-xue

**Comment by BethanyZhou** [comment]
Thanks for reporting, I will investigate whether SDK supports this behavior.

**Comment by BethanyZhou** [comment]
Hi @nitmatgeo , good news is that SDK support creating EC keys. Add @dingmeng-xue for awareness.

For the feature enhancement you are requesting, We do understand the importance in your scenarios.

While if there is an ec key named test with curve name P-521, for command `Add-AzKeyVaultKey -VaultName test-kv -Name eckey -KeyType EC -Destination Software`,  it's hard to decide whether user wants to create ec key named test with default curve name P-256 or user wants to keep same with previous version.

So that we prefer letting user to specify these properties straightforwardly.

**Comment by nitmatgeo** [comment]
@BethanyZhou Oh that's great! Cheers, sounds perfectly fine; in fact it is a better way to have an optional parameter '_UsePreviousConfiguration_'. Hope these changes can be expected asap 😄 🤞

**Comment by dingmeng-xue** [comment]
@nitmatgeo , according to feedback from Keyvault team, the recommended way is to use the new keyvault API - [rotate] (https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.3-preview/keys.json#L82). This feature is not public yet and we will provide new cmdlet to support this case once it is available on API version 7.4.

**Comment by nitmatgeo** [comment]
@dingmeng-xue Thanks a lot for the update. Any idea about the expected timeline? Also will there be complete revamp of existing commands (_get key details or add key etc._) in future versions?

**Comment by jlichwa** [comment]
@nitmatgeo on service side we are adding few APIs for seamless key rotation (one of the endpoint will generate new version based on key attributes of previous version). It is planned to be completed by end of the year.

**Comment by BethanyZhou** [comment]
Hi @nitmatgeo , we supported create EC keys in commands if the version of your Az.KeyVault >= 3.5.0. Hope this feature unblocked you.

**Comment by jlichwa** [comment]
This feature is GA. #please-close
