### ISSUE TITLE
Start menu shortcut points to 32-bit PowerShell even on x64 Windows making 64-bit cmdlets unrecognized

### ISSUE THREAD

**Issue by seanmck** [Azure/azure-powershell#1567]
Customers who have tried to run Azure Service Fabric cmdlets from within Azure PowerShell have found that those cmdlets are not recognized. This is because the Service Fabric cmdlets are x64-only, whereas the Azure PowerShell shortcut invokes the 32-bit version of Windows PowerShell, even on x64 OS versions. Since the PS modules shipped with Azure PowerShell are themselves entirely MSIL, it would be preferable to use the x64 version of Windows PS on x64 OS versions such that x64-only cmdlets can run there as well.

Alternatively, the shortcut could be removed altogether in favor of launching Windows PS directly.

**Comment by jeffwilcox** [comment]
+1 on this one, I always worry about a 32-bit prompt of any kind in x64 throwing off common dev tasks.

**Comment by hovsepm** [comment]
Will be available in the upcoming release. No more Azure PowerShell shortcuts will be added.
