### ISSUE TITLE
New-AzP2sVpnGateway doesnt work with ids

### ISSUE THREAD

**Issue by asengutt** [Azure/azure-powershell#15682]
## Description

Doc example 3 works and 6 doesnt work
https://docs.microsoft.com/en-us/powershell/module/az.network/New-AzP2sVpnGateway?view=azps-6.3.0

$HubObj = Get-AzVirtualHub -ResourceGroupName "CVPN_rg1" -Name "CVPNHub_r5"
$vpnsconf = Get-AzVpnServerConfiguration -ResourceGroupName "CVPN_rg1" -Name "CVPNServerConfig_r3"

#New-AzP2sVpnGateway succeeds when objects are provided as inputs.
New-AzP2sVpnGateway -ResourceGroupName 'rg1' -Name 'CVPNHub_r5_p2s_gw' -VpnGatewayScaleUnit '1' -VpnClientAddressPool $vpnClientAddressSpaces -VpnServerConfiguration $vpnsconf -VirtualHub $HubObj

#New-AzP2sVpnGateway fails when ids are provided as inputs.
#This gives error "Parameter set cannot be resolved using the specified named parameters."
New-AzP2sVpnGateway -ResourceGroupName 'rg1' -Name 'CVPNHub_r5_p2s_gw' -VpnGatewayScaleUnit '10' -VirtualHubName 'CVPNHub_r5' -VpnClientAddressPool $vpnClientAddressSpaces  -VpnServerConfigurationId $vpnsconf.Id -VirtualHubId $HubObj.Id

**Comment by Nilambari** [comment]
#New-AzP2sVpnGateway fails when ids are provided as inputs.
#This gives error "Parameter set cannot be resolved using the specified named parameters."
New-AzP2sVpnGateway -ResourceGroupName 'rg1' -Name 'CVPNHub_r5_p2s_gw' -VpnGatewayScaleUnit '10' -VirtualHubName 'CVPNHub_r5' -VpnClientAddressPool $vpnClientAddressSpaces -VpnServerConfigurationId $vpnsconf.Id -VirtualHubId $HubObj.Id

=> Either pass VirtualHubName or VirtualHubId and see if command works for you. Thanks!
