### ISSUE TITLE
Site Recovery - “re-protect” via Azure Automation PS runbook failing - (Azure to Azure)

### ISSUE THREAD

**Issue by farroar** [Azure/azure-powershell#15712]
## Description
I've created a simple runbook in Azure Automation to kick off a failover in site recovery referencing a recovery plan. Failover works fine, the issue comes to when I need to "failback". This starts with a re-protect to re-replicate traffic from the backup region back to the source region. In the Azure GUI, this is performed via the "Re-Protect" button in the Recovery Plan. In PowerShell, this re-protect should be performed with the cmdlet:

Update-AzRecoveryServicesAsrProtectionDirection

Following this documentation:
https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/update-azrecoveryservicesasrprotectiondirection?view=azps-6.3.0

## Steps to reproduce
The following code is being used to attempt to initiate a re-protection action, this is done post failover from primary region to backup region:

```
$vault = Get-AzRecoveryServicesVault -Name $RecoveryVaultName -ResourceGroupName $RecoveryVaultRG
Set-AzRecoveryServicesAsrVaultContext -Vault $vault

$RP = Get-AzRecoveryServicesAsrRecoveryPlan -Name $RecoveryPlanName

$job = Update-AzRecoveryServicesAsrProtectionDirection -RecoveryPlan $RP -Direction RecoveryToPrimary
```

## Environment data

Running PowerShell via Azure Automation Runbook.

## Module versions

Az.RecoveryServices is version 4.5.0

## Debug output

None

## Error output

The error produced when running this is as follows:

> Unsupported replication provider A2A for reprotect

**Comment by Sharmistha-Rai** [comment]
Adding @sideeksh to assist here.

**Comment by edtorresco** [comment]
Any update about this issue?

**Comment by Sharmistha-Rai** [comment]
@edtorresco 
We haven't received this request before. I will add it to our feedback log. If we received significant customer demand, then we can add this item to our roadmap.

**Comment by Sharmistha-Rai** [comment]
Closing this issue for now. Please feel free to reopen for any queries.

**Comment by sgannavaram** [comment]
Hi .. Is Reprotect at recovery plan level  supported now? i am facing the same error.

**Comment by GlennHorton** [comment]
The doc at https://learn.microsoft.com/en-us/powershell/module/az.recoveryservices/update-azrecoveryservicesasrprotectiondirection?view=azps-13.2.0#parameters says it's supported but I still get the error shown above.
