### ISSUE TITLE
New-AzApiManagementOperation - Add a provision for creating a definition (schema) and assigning to the new operation being created

### ISSUE THREAD

**Issue by omkarg81** [Azure/azure-powershell#15759]
![image](https://user-images.githubusercontent.com/1419825/131010947-9ad3e82a-2bb8-4be5-a703-71cae7393526.png)

When creating a new api operation under Azure API Management service, for Get / post requests that take in query params, like \api\v1\settlement\{id}, when we try to create the api operation directly, an error is thrown - 

Operation references schema that does not exist

Currently, even though we can create a new schema using New-AzApiManagementApiSchema, it only gives us a new SchemaId. There doesn't seem to be anyway to bind the definition, as shown in attached picture with a specific new api operation being created, wherein that new schema definition gets linked with each operation that needs those parameters.

This provision to create operation definition should be provided in powershell cmdlet, azure cli and rest api calls; none of which exists today. It seems to be a azure portal only feature, which defeats all automation efforts.

**Comment by navba-MSFT** [comment]
@omkarg81 Apologies for the late reply. We are looking into this issue. We will provide an update once we have more details on this.

@adrianhall Could you please provide an update on this once you get a chance ? Awaiting your reply.
