### ISSUE TITLE
New-AzContainerInstanceObject -Command parameter not accepting commands anymore, just executable

### ISSUE THREAD

**Issue by ramermancdb** [Azure/azure-powershell#15793]
## Description
When using the New-AzContainerInstanceObject function in an Azure Automation PowerShell Runbook Azure is indicating that any command with parameters submitted with the -command parameter is not recognized.
Submitting a single command does work.

While I lost the reference, I have seen evidence that others have observed this and thought it may be intended but in talking to a couple Azure engineers at MS they are sure it is a bug and that I should submit it here.

## Steps to reproduce
Try and create a new container instance using the New-AzContainerInstanceObject function and include the "-Command" parameter with a supplied command that would run in the container image being used that includes one or more parameters.

My example from an Azure Automation Account PS Runbook (only the relevant piece):

```powershell
$command = "azcopy copy <source sas> <destination sas> --include-after 2021-06-27T01:00:06 --block-blob-tier='archive' --recursive " 

$container = New-AzContainerInstanceObject -Name cdbtier-container `
    -Image peterdavehello/azcopy:latest -RequestCpu 2 -RequestMemoryInGb 4 `
    -Command $command -EnvironmentVariable $envVars

New-AzContainerGroup -ResourceGroupName $sourceStorageAccountRG `
    -Name $jobName -Container $container -Location westus `
    -OsType Linux -RestartPolicy never 
```

## Module versions

Since this is PS in an Azure Automation Account Runbook I am not able to do this.

## Debug output

Since this is PS in an Azure Automation Account Runbook I am not able to do this.

## Error output

The error I get from the test run of the runbook containing the above code is:
no such file or directory

Which follows the reflection of the command I sent with the -Command parameter.

**Comment by dingmeng-xue** [comment]
Hi @ramermancdb , could you get debug message in automation? You can turn it on via `$DebugPreference = "Continue"`.

**Comment by ramermancdb** [comment]
I'll try the debug call. I assumed it would not work in the runbook but will give it a try.

**Comment by ramermancdb** [comment]
I have added $DebugPreference = "Continue" to my PowerShell Azure Automation Account Runbook.

I have initiated a fresh test run.

The results:
The runbook just keeps running. It is stuck trying to crate the container instance with the following error like before:
![image](https://user-images.githubusercontent.com/62399279/131713752-72581016-859b-4fd4-acbf-fe6c5ae8f8b6.png)

Under the properties tab of the container it is trying to create I can see the full command property it was fed:
Commands
[ "azcopy copy 'https://cdbitcontentarchstagelrs.file.core.windows.net/Content?sv=2019-07-07&sr=s&sig=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&se=2021-09-01T18%3A01%3A01Z&sp=rl' 'https://cdbitcontentarchivelrs.blob.core.windows.net/Content?sv=2019-07-07&sr=c&sig=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&se=2021-09-01T18%3A01%3A03Z&sp=rw' --include-after 2021-06-03T17:01:07  --recursive " ]

I do not see any new debug output anywhere either in the runbook test or in the context of the container instance that has been created but is not able to create/start succsfully.

**Comment by ramermancdb** [comment]
Should have done this before I sent the above.

When I stopped the test run it  spit out a bunch of output.

Here is the main part, the rest is just a repeat of the last block as it was in a loop.

I went to the end of the output just to make sure there was not a final output past the looping/repeating one but there was none.

 : westus:480912ac-3346-4ef1-9154-xxxxxxxxxxxxx
x-ms-ratelimit-remaining-subscription-reads: 11963
x-ms-correlation-request-id   : 44c51689-7d5c-422b-9003-630d09db2221
x-ms-routing-request-id       : WESTUS:20210901T170144Z:44c51689-7d5c-422b-9003-630d09db2221
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Wed, 01 Sep 2021 17:01:43 GMT

Body:
{
  "id": "/subscriptions/4b55d915-5f72-44c4-8306-xxxxxxxxxx/resourceGroups/CDB-IT-Archive/providers/Microsoft.ContainerInstance/containerGroups/Cdbitcontentarchstagelrs-ContentAZCopyJob",
  "status": "Pending",
  "startTime": "2021-09-01T17:01:13.5969755Z",
  "properties": {
    "events": [
      {
        "count": 1,
        "firstTimestamp": "2021-08-30T05:23:25Z",
        "lastTimestamp": "2021-08-30T05:23:25Z",
        "name": "Pulling",
        "message": "pulling image \"peterdavehello/azcopy@sha256:f179f4a79e90f37efa35335aba7de3baff2bd8c2c74f0e303a1e2981a032d082\"",
        "type": "Normal"
      },
      {
        "count": 1,
        "firstTimestamp": "2021-08-30T05:23:26Z",
        "lastTimestamp": "2021-08-30T05:23:26Z",
        "name": "Pulled",
        "message": "Successfully pulled image \"peterdavehello/azcopy@sha256:f179f4a79e90f37efa35335aba7de3baff2bd8c2c74f0e303a1e2981a032d082\"",
        "type": "Normal"
      },
      {
        "count": 1,
        "firstTimestamp": "2021-08-30T05:23:32Z",
        "lastTimestamp": "2021-08-30T05:23:32Z",
        "name": "Started",
        "message": "Started container",
        "type": "Normal"
      },
      {
        "count": 1,
        "firstTimestamp": "2021-08-30T05:23:34Z",
        "lastTimestamp": "2021-08-30T05:23:34Z",
        "name": "Killing",
        "message": "Killing container with id 59c8bb1a94387cb8fc6dba4b8b30de80835a095c52bc8923522434295f24954b.",
        "type": "Normal"
      }
    ]
  }
}

Polling: 
DelayBeforePolling: Delaying 30 seconds before polling.
============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/4b55d915-5f72-44c4-8306-xxxxxxx/providers/Microsoft.ContainerInstance/locations/westus/operations/7376c8bd-f20f-4a4d-8375-cc324182dbd3?api-version=2018-06-01

Headers:
x-ms-unique-id                : 3
x-ms-client-request-id        : 49b0dc57-a8e2-4a11-83a7-3942904b6837
CommandName                   : Az.ContainerInstance.internal\New-AzContainerGroup
FullCommandName               : New-AzContainerGroup_CreateExpanded
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/Az4.0.0-preview

Body:


============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Vary                          : Accept-Encoding
x-ms-request-id               : westus:b918bbf7-c438-4467-b31d-84a9f6869b38
x-ms-ratelimit-remaining-subscription-reads: 11962
x-ms-correlation-request-id   : 026f2230-1fca-4852-af04-9dc3dfb2789e
x-ms-routing-request-id       : WESTUS:20210901T170214Z:026f2230-1fca-4852-af04-9dc3dfb2789e
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Wed, 01 Sep 2021 17:02:13 GMT

Body:
{
  "id": "/subscriptions/4b55d915-5f72-44c4-8306-xxxxxxxx/resourceGroups/CDB-IT-Archive/providers/Microsoft.ContainerInstance/containerGroups/Cdbitcontentarchstagelrs-ContentAZCopyJob",
  "status": "Creating",
  "startTime": "2021-09-01T17:01:13.5969755Z",
  "properties": {
    "events": [
      {
        "count": 1,
        "firstTimestamp": "2021-08-30T05:23:25Z",
        "lastTimestamp": "2021-08-30T05:23:25Z",
        "name": "Pulling",
        "message": "pulling image \"peterdavehello/azcopy@sha256:f179f4a79e90f37efa35335aba7de3baff2bd8c2c74f0e303a1e2981a032d082\"",
        "type": "Normal"
      },
      {
        "count": 1,
        "firstTimestamp": "2021-08-30T05:23:26Z",
        "lastTimestamp": "2021-08-30T05:23:26Z",
        "name": "Pulled",
        "message": "Successfully pulled image \"peterdavehello/azcopy@sha256:f179f4a79e90f37efa35335aba7de3baff2bd8c2c74f0e303a1e2981a032d082\"",
        "type": "Normal"
      },
      {
        "count": 1,
        "firstTimestamp": "2021-08-30T05:23:32Z",
        "lastTimestamp": "2021-08-30T05:23:32Z",
        "name": "Started",
        "message": "Started container",
        "type": "Normal"
      },
      {
        "count": 1,
        "firstTimestamp": "2021-08-30T05:23:34Z",
        "lastTimestamp": "2021-08-30T05:23:34Z",
        "name": "Killing",
        "message": "Killing container with id 59c8bb1a94387cb8fc6dba4b8b30de80835a095c52bc8923522434295f24954b.",
        "type": "Normal"
      },
      {
        "count": 1,
        "firstTimestamp": "2021-09-01T17:01:18Z",
        "lastTimestamp": "2021-09-01T17:01:18Z",
        "name": "Pulling",
        "message": "pulling image \"peterdavehello/azcopy@sha256:d182e3d472a787a53a87fd9571e807a4fe4af646495324ae3e2b556ed6c03c93\"",
        "type": "Normal"
      },
      {
        "count": 1,
        "firstTimestamp": "2021-09-01T17:01:19Z",
        "lastTimestamp": "2021-09-01T17:01:19Z",
        "name": "Pulled",
        "message": "Successfully pulled image \"peterdavehello/azcopy@sha256:d182e3d472a787a53a87fd9571e807a4fe4af646495324ae3e2b556ed6c03c93\"",
        "type": "Normal"
      },
      {
        "count": 1,
        "firstTimestamp": "2021-09-01T17:01:28Z",
        "lastTimestamp": "2021-09-01T17:01:28Z",
        "name": "Failed",
        "message": "Error: Failed to start container cdbtier-container, Error response: to create containerd task: failed to create container 0059e31b7ff0df70198f7c3a5f753dca609e880b587263f99fc980287049d93a: guest RPC failure: failed to create container: failed to run runc create/exec call for container 0059e31b7ff0df70198f7c3a5f753dca609e880b587263f99fc980287049d93a with container_linux.go:349: starting container process caused \"exec: \\\"azcopy copy --include-after 2021-06-03T17:01:07 --overwrite ifSourceNewer --put-md5 --recursive\\\": stat azcopy copy --include-after 2021-06-03T17:01:07 --overwrite ifSourceNewer --put-md5 --recursive: no such file or directory\": exit status 1: unknown",
        "type": "Warning"
      }
    ]
  }
}

**Comment by ramermancdb** [comment]
Not sure how it got closed but said I did so. My apologies for the noise.

Reopening now:

**Comment by dingmeng-xue** [comment]
@ramermancdb thanks for the information. The error message is below 
```
exec: "azcopy copy --include-after 2021-06-03T17:01:07 --overwrite ifSourceNewer --put-md5 --recursive": stat azcopy copy --include-after 2021-06-03T17:01:07 --overwrite ifSourceNewer --put-md5 --recursive: no such file or directory
```

According to message, the cmdlet cannot execute in docker container correctly. I'm not familiar with script you are using. Here, I just have 2 suggestions:
1. You can simply your command and check whether container can execute command as expected or not. such as just `touch` one file. Or you can try command what you are using in local docker container.
2. Check the first HTTP request during `New-AzContainerGroup`. The payload of HTTP request contains what parameter is sent to ContainerInstance service.

**Comment by ramermancdb** [comment]
@dingmeng-xue 

They are both good suggestions but I have already dealt with both.

1. I have tried other commands, my main example the explicit path to azcopy with nothing both the following:
azcopy --help
Bottom line is that any command beyond just calling the executable does not work.

2. I am able to see in the container instance output exactly what command was received by it and it is the exact one that I sent. While the error always makes it look like the command might not be getting through intact, this is not the case.

**Comment by dingmeng-xue** [comment]
Thanks @Ramermancdb for the information. Current repo of Azure PowerShell just takes the responsibility of client behavior and we ensure the request is sent to service correctly. But we have limited know in each service especially edge cases.

To follow up your question, you can select one of below approaches.
1. You need to leverage Azure support to raise your question. In that case, you need to provide your requests with client request id and correlation id. 
2. You can leverage current github issue too. But we need the payload of HTTP call and the last HTTP call during executing `New-AzContainerGroup`. Then, we will forward it to ContainerInstance team to look into it.

**Comment by macux** [comment]
For info, if anyone comes across this. You need to separate your command into component parts for this to work, e.g. rather than:

    $container = New-AzContainerInstanceObject -Name <container-name> -Image <image-name> `
        -Command "this is my long command"

Use:

    $container = New-AzContainerInstanceObject -Name <container-name> -Image <image-name> `
        -Command "this", "is", "my", "long", "command"

**Comment by coderkname** [comment]
> For info, if anyone comes across this. You need to separate your command into component parts for this to work, e.g. rather than:
> 
> ```
> $container = New-AzContainerInstanceObject -Name <container-name> -Image <image-name> `
>     -Command "this is my long command"
> ```
> 
> Use:
> 
> ```
> $container = New-AzContainerInstanceObject -Name <container-name> -Image <image-name> `
>     -Command "this", "is", "my", "long", "command"
> ```

This doesn´t work from "Invoke-AzContainerInstanceCommand" .

Example:
Invoke-AzContainerInstanceCommand -ContainerGroupName $CGname -ContainerName $Cname -ResourceGroupName $RGname -Command "echo hola" 

OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "echo hola": executable file not found in $PATH: unknown

So weird, the az cli version of container commands works like charm, but the powershell one its like a hell, but you dont have other way if you want to use azure automation :(
