### ISSUE TITLE
Documentation error in New-AzAnalysisServicesServer

### ISSUE THREAD

**Issue by loweyson** [Azure/azure-powershell#15790]
## Description
Documentation error in New-AzAnalysisServicesServer. The second automatically generated sample does not work because it relies on a custom object: PsAzureAnalysisServicesFirewallConfig. An additional step is required to demonstrate the creation of this object using, for example: New-AzAnalysisServicesFirewallConfig

## Steps to reproduce

1. visit: https://docs.microsoft.com/en-us/powershell/module/az.analysisservices/new-azanalysisservicesserver
2. Copy the second sample to the clipboard
3. In powershell (signed in to Azure) paste the sample

## Sample command

```
PS C:\>New-AzAnalysisServicesServer -Administrator **** -FirewallConfig <PsAzureAnalysisServicesFirewallConfig> -Location **** -Name 'testwo' -ResourceGroupName $rg -Sku "D1"
```
_Note: Some values have been anonymised in the above._

## Error output

```
At line:1 char:94
+ ... ourceGroupName $rg -Name "testwo" -Sku "D1" -FirewallConfig <PsAzureA ...
+                                                                 ~
The '<' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported
```

## Suggested solution
Replace the automatically generated sample with a working one. For example:

```
$rule1 = New-AzAnalysisServicesFirewallRule -FirewallRuleName rule1 -RangeStart 0.0.0.0 -RangeEnd 255.255.255.255
$rule2 = New-AzAnalysisServicesFirewallRule -FirewallRuleName rule2 -RangeStart 6.6.6.6 -RangeEnd 7.7.7.7
$config = New-AzAnalysisServicesFirewallConfig -EnablePowerBIService -FirewallRule $rule1,$rule2

New-AzAnalysisServicesServer -Administrator 'testuser1@contoso.com' -FirewallConfig $config -Location 'West-US' -Name 'testserver' -ResourceGroupName 'testresourcegroup' -Sku 'S1'
```

**Comment by navba-MSFT** [comment]
@athipp, @taiwu @minghan This is a follow-up to check if you had a chance to look into this documentation issue. Please update this thread once you get a chance.
@loweyson Apologies for the delay in the response. While we wait for their reply, please let us know if you have any further questions on this. We would be happy to address it.
