### ISSUE TITLE
Get-AzResource doesn't return web jobs

### ISSUE THREAD

**Issue by sadomovalex** [Azure/azure-powershell#15799]
## Description

Get-AzResource doesn't return web jobs

## Steps to reproduce

```powershell
Get-AzResource -ResourceGroupName {resourceGroup}
```

This cmdlet returns other Azure resources from specified resource group (App services, Azure functions, Storage accounts, KeyVaults, SSL certificates) except web jobs (e.g. triggered web jobs which have ResourceType = microsoft.web/sites/triggeredwebjobs). In AzureRM it was possible to get web jobs using the following command 

```powershell
Get-AzureRmResource -ResourceGroupName {resourceGroup} -ResourceType microsoft.web/sites/triggeredwebjobs -ApiVersion 2016-03-01
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.1714
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1714
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Az 6.3.0 is used

**Comment by SaurabhSharma-MSFT** [comment]
@antcp, @AzureAppServiceCLI Do you have any updates on this issue.

**Comment by Kotasudhakarreddy** [comment]
Taking a look in to this.

**Comment by Kotasudhakarreddy** [comment]
Currently we are not working on the issues related to `AzRM` modules. Hope you got the solution to invoke the API directly as mentioned in [#661](https://github.com/Azure/azure-powershell/issues/661#issuecomment-910392083). 

PowerShell team is working on it to create `Az` modules commands. you can follow [#661](https://github.com/Azure/azure-powershell/issues/661) for updates.
