### ISSUE TITLE
AKS powershell modules are missing resource group

### ISSUE THREAD

**Issue by jjindrich** [Azure/azure-powershell#15802]
Get-AzAksCluster command is not returning ResourceGroup. But Stop-AzAksCluster/Start-AzAksCluster requires ResourceGroup parameter.

The case: You want to Stop/Start all AKS clusters.
Issue: You will list of all clusters using Get-AzAksCluster but you cannot run Stop-AzAksCluster/Start-AzAksCluster because 
ResourceGroup property is missing.

**Comment by dingmeng-xue** [comment]
Hi @jjindrich , we will add this feature. As a workaround, could you use pipeline operation? `Get-AzAksCluster | Stop-AzAksCluster`

**Comment by jjindrich** [comment]
Thanks, please add ResourceGroup. I need to make some decisions based on the RG.

**Comment by jjindrich** [comment]
@wyunchi-ms I tested it but ResourceGroupName property is still missing. I used Install-Module -Name Az.Aks with latest version (2.5.0).
I run
`$c = Get-AzAksCluster
$c[0].Id
$c[0].ResourceGroupName
`

Getting Id works. But getting ResourceGroupName failed.

Please can you check it ?

**Comment by wyunchi-ms** [comment]
The PR is merged but not released. This issue will be fixed when next release arount 2021-12-08.
