### ISSUE TITLE
Get-AzADAppCredential MS Docs still shows that credential value is not retrieved but it is. 

### ISSUE THREAD

**Issue by jdiazmolina** [Azure/azure-powershell#15813]
## Description of the new feature
Hi! https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azadappcredential?view=azps-6.3.0 still says that the command does not retrieve the credential value but now it is returned for example for Thumbprints in Certificate cases.

## Proposed implementation details (optional)
Just correct documentation

**Comment by dingmeng-xue** [comment]
Thanks for reporting. My understanding is Thumbprint is not credential. It was not hidden on Portal either.
