### ISSUE TITLE
Get-AzNetworkingServiceTag , region is no longer available for DataFactory 

### ISSUE THREAD

**Issue by JimmyHjelte** [Azure/azure-powershell#15818]
## Description
We been using Get-AzNetworkingServiceTag to filter out ip ranges for DataFactory.WestEurope but since last week  there is only one service tag called "DataFactory" containing 280+ ipv4 ranges compared with the service tag "DataFactory.WestEurope" found in the list that only contains 7 ipv4 ranges. 

This was working 2 weeks ago ,but not any longer.

## Steps to reproduce

This should return 7 ip4 ranges , but returns 0 now !
#Fetch ipAddress ranges for AzureDataFactory
$serviceTags = Get-AzNetworkServiceTag -Location westeurope
$dataFactoryTags = $serviceTags.Values  | Where-Object { $_.Name -eq "DataFactory.WestEurope" }
$ipv4CIDRs = $dataFactoryTags.Properties.AddressPrefixes | Where-Object { $_ -like "*.*.*.*/*"} 

## Environment data
PS /home/jimmy> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.4.0-1056-azure #58~18.04.1-Ubuntu SMP Wed Jul 28 23:14:18 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/jimmy>

```

## Module versions

<!-- Please run (Get-Module  -ListAvailable) and paste the output in the below code block -->

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by gazpwc** [comment]
Yes, we are seeing the same issue since august, 30th:
https://github.com/Azure/azure-powershell/issues/15789

Unfortunately no reaction yet...

**Comment by JimmyHjelte** [comment]
@gazpwc  I got the following answer from support
"
The PS command you're referring to is maintained by Azure Networking team, and its ServiceTag Discovery API has been maintained under a "Public Preview" state:
Azure service tags overview | Microsoft Docs
 
Unfortunately that means, from an internal discussion, that we may encounter from time to time differences while using the command to fetch the specific IPs and it is recommended that customers rely on the available list of public IPs downloadable from Download Azure IP Ranges and Service Tags – Public Cloud from Official Microsoft Download Center while this feature doesn't reach Global Availability.
"

**Comment by gazpwc** [comment]
That's a pity. But thanks a lot for posting this information.

**Comment by allegradomel** [comment]
@JimmyHjelte we are working on adding these tags back to the API results, since we've received many requests. You should be able to see them again in 1-2 months.

**Comment by JimmyHjelte** [comment]
For anyone else with similar issues.
We ended up replacing the cmdlet and instead we download the official "Azure IP Ranges and Service Tags – Public Cloud"  and parse out the service tags we need.

`$uri = "https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519"

$response = Invoke-WebRequest -Uri $uri
$jsonUri = ($response.Links | Where-Object {$_.href -match 'ServiceTags_Public_'}).href

$response = (Invoke-WebRequest -Uri $jsonUri | ConvertFrom-Json)
$dataFactoryTags = ($response.values | Where-Object {$_.name -match 'DataFactory.WestEurope'})

#Filter out IPV4 Only
$ipv4CIDRs = $dataFactoryTags.Properties.AddressPrefixes | Where-Object { $_ -like "*.*.*.*/*"} `

**Comment by allegradomel** [comment]
Also, quick update on the timeline, you should see these tags added back to the results in the next 2-2.5 weeks. Thanks for your patience!

**Comment by plzm** [comment]
> For anyone else with similar issues. We ended up replacing the cmdlet and instead we download the official "Azure IP Ranges and Service Tags – Public Cloud" and parse out the service tags we need.
> 
> `$uri = "https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519"
> 
> $response = Invoke-WebRequest -Uri $uri jsonUri=(_.href -match 'ServiceTags_Public_'}).href
> 
> $response = (Invoke-WebRequest -Uri $jsonUri | ConvertFrom-Json) $dataFactoryTags = ($response.values | Where-Object {$_.name -match 'DataFactory.WestEurope'})
> 
> #Filter out IPV4 Only $ipv4CIDRs = $dataFactoryTags.Properties.AddressPrefixes | Where-Object { $_ -like "_._._._/*"} `

Brilliant!!! Thank you for sharing this!
