### ISSUE TITLE
Command failing for me - Set-AzvmClientExtension

### ISSUE THREAD

**Issue by Zak-Ghani** [Azure/azure-powershell#15825]
during a Linux  bootstrap i am getting an error usually a 172 (long running process fails). within the portal i usually end up with a status message that says one of 2 things, either "transitioning" or "provisioning failed". 

If i then log into the machine and manually rename one file before executing a chef-client -j 0.settings.json the bootstrap completes successfully. this does not however fix the message on the portal\vm\extensions page.

This is an issue as i don't have the time or the ability to login to several hundred VM's hosted across multiple subscriptions

**Comment by jaylabell** [comment]
@amjads1 Do you mind taking a look at this Extension related issue?

**Comment by Zak-Ghani** [comment]
Hi all, we've worked out what the issue was. Its to do with the way chef was set up at my place of work, validation.pem file was missing permissions to generate a node..pem file during the bootstrap process. I've rewritten my scriptin to inject the required client.pem file into the VM prior to the extension being attached and executed.

Thank you for taking the time to look into this for me.

**Comment by Zak-Ghani** [comment]
Thank you for looking into this for me
