### ISSUE TITLE
[Az.Monitor] The output of Get-AzLog is not readily usable, improve output format

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#15833]
## Description
 OperationName, EventName, Status, Category etc. are simply shown as  Microsoft.Azure.Management.Monitor.Models.LocalizableString instead of the actual value. The output is not usable in the current form. This is with the latest version of Az.Monitor . The issue seems to be pre existing, not a new one.

We had to workaround like
Get-AzLog -MaxRecord 1 | select Caller, ResourceGroupName, Level, @{n="OpName";e={$_.OperationName | select -expand Value}}, @{n="RP";e={$_.ResourceProviderName | select -expand Value}}, EventTimeStamp, @{n="Method";e={$_.HttpRequest|select -expand Method}}, @{n="Status";e={$_.Status | select -expand Value}} | ft -AutoSize

Here is a sample output (some fields are cleared for sensitivity)
```
PS C:\azlatest> get-azlog -MaxRecord 1
WARNING: 7:17:10 PM - The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.
WARNING: 7:17:10 PM - The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model classes.
WARNING: [Get-AzActivityLog] Parameter deprecation: The DetailedOutput parameter will be deprecated in a future breaking change release.

Authorization        :
                    
                       Condition :
Claims           
HttpRequest          :
                       ClientId        : s
                       Method          : POST
                       Url             :
                       ClientIpAddress : s
Properties           :
                       
Level                : Informational
SubmissionTimestamp  : 9/4/2021 8:29:49 AM
EventTimestamp       : 9/4/2021 8:28:34 AM
Caller               : ----
Description          :
Id                   : ----
EventDataId          : ed332fd2-16aa-466b-8c5e-3e4a0b2fdc27
CorrelationId        : 068eaf5c-158c-4537-a5fe-42f6b68d15e2
EventName            : Microsoft.Azure.Management.Monitor.Models.LocalizableString
Category             : Microsoft.Azure.Management.Monitor.Models.LocalizableString
ResourceGroupName    : myrg01
ResourceProviderName : Microsoft.Azure.Management.Monitor.Models.LocalizableString
ResourceId           : /subscriptions/subid/resourceGroups/myrg01/providers/Microsoft.AzureStack/registrations/myreg202
ResourceType         :
OperationId          : 068eaf5c-158c-4537-a5fe-42f6b68d15e2
OperationName        : Microsoft.Azure.Management.Monitor.Models.LocalizableString
Status               : Microsoft.Azure.Management.Monitor.Models.LocalizableString
SubStatus            : Microsoft.Azure.Management.Monitor.Models.LocalizableString
SubscriptionId       : subid
```
## Steps to reproduce

After logging in and selecting subscription
 get-azlog -MaxRecord 1

## Environment data

PS C:\azlatest> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

## Module versions
PS C:\azlatest> get-module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.5.3                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     2.7.0                 Az.Monitor                          {Add-AzAutoscaleSetting, Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzMetricAlertRuleV2…}

**Comment by dingmeng-xue** [comment]
We will update it when team has bandwidth.
