### ISSUE TITLE
Can't fetch UsedCapacity for a particular Fileshare

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#15839]
With `Get-AzMetric` I want to get the UsedCapacity of all fileshare inside a StorageAccount.

The appropriate command is

```
$Id = "/subscriptions/<mysubscription>/resourceGroups/<myrgroup>/providers/Microsoft.Storage/storageAccounts/<mystorageaccount>/fileServices/default"
(Get-AzMetric -ResourceId $Id).Data.Average
```

How can I get the UsedCapacity for a particular fileshare within a StorageAcocunt?

**Comment by dingmeng-xue** [comment]
Hi @Gill-Bates , I didn't find any doc about approach leveraging `Get-AzMetric`. Could you check below cmdlet?

```
Get-AzRmStorageShare -ResourceGroupName <> -StorageAccountName <> -Name <> -GetShareUsage
```
