### ISSUE TITLE
0-Value Result Get-AzMetric for Fileshares (UsedCapacity)

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#15863]
From Time to Time I receive an 0-Value Result, when I perform a Request against the Metrics-API to get the UsedCapacity

**OK:**

`(Get-AzMetric -ResourceID "/subscriptions/***/resourceGroups/***/providers/Microsoft.Storage/storageAccounts/***/fileServices/default").Data`

![image](https://user-images.githubusercontent.com/25774289/133056307-9c559852-650e-48fb-a351-7209fca31ffb.png)

**NOK:**

![image](https://user-images.githubusercontent.com/25774289/133056276-879c6f46-e33e-4bd6-80e5-93b3590f9d04.png)

**AND OK AGAIN:**

![image](https://user-images.githubusercontent.com/25774289/133057626-b97bd085-bf1f-4d96-87b1-014d1752b9ee.png)

`Get-Module`

```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.0                 Az.Monitor                          {Add-AzAutoscaleSetting, Add-AzLogProfile, Add-Az…
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Please share debug message for our further investigation. You can turn on the debug via `$DebugPreference = "Continue"`

The payload of response of this cmdlet should be very large. Please just provide the part of debug message including whole request and head of response.

**Comment by Gill-Bates** [comment]
```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com//subscriptions/*****/resourceGroups/****/providers/Microsoft.Storage/storageAccounts/*****/fileServices/default/providers/microsoft.insights/metrics?timespan=2021-09-14T14%3A05%3A02.5958052Z%2F2021-09-14T15%3A05%3A02.5958052Z&api-version=2018-01-01

Headers:
x-ms-client-request-id        : 2631d35e-db11-4934-9ea8-081d411cd09b
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Vary                          : Accept-Encoding
x-ms-ratelimit-remaining-subscription-reads: 11994
x-ms-request-id               : {2dbdfe9a-9923-4ec5-b066-e16048b4b4b9}
Request-Context               : appId=cid-v1:b021da79-5252-4375-9df5-2e17c1dcd822
Access-Control-Expose-Headers : Request-Context
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-correlation-request-id   : 2dbdfe9a-9923-4ec5-b066-e16048b4b4b9
x-ms-routing-request-id       : FRANCESOUTH:20210914T150503Z:2dbdfe9a-9923-4ec5-b066-e16048b4b4b9
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Tue, 14 Sep 2021 15:05:02 GMT

Body:
{
  "cost": 59,
  "timespan": "2021-09-14T14:05:02Z/2021-09-14T15:05:02Z",
  "interval": "PT1H",
  "value": [
    {
      "id": "/subscriptions/******/resourceGroups/****/providers/Microsoft.Storage/storageAccounts/*****/fileServices/default/providers/Microsoft.Insights/metrics/FileCapacity",
      "type": "Microsoft.Insights/metrics",
      "name": {
        "value": "FileCapacity",
        "localizedValue": "File Capacity"
      },
      "displayDescription": "The amount of File storage used by the storage account.",
      "unit": "Bytes",
      "timeseries": [
        {
          "metadatavalues": [],
          "data": [
            {
              "timeStamp": "2021-09-14T14:05:00Z"
            }
          ]
        }
      ],
      "errorCode": "Success"
    }
  ],
  "namespace": "Microsoft.Storage/storageAccounts/fileServices",
  "resourceregion": "westeurope"
}


DEBUG: AzureQoSEvent: Module: Az.Monitor:2.7.0; CommandName: Get-AzMetric; PSVersion: 7.1.3; IsSuccess: True; Duration: 00:00:00.5372600
DEBUG: Finish sending metric.
DEBUG: 17:05:03 - GetAzureRmMetricCommand end processing.

TimeStamp : 14.09.2021 14:05:00
Average   :
Minimum   :
Maximum   :
Total     :
Count     :
```

**Comment by dingmeng-xue** [comment]
Hi owner of Microsoft.Insights/metrics, do you have any insight about when service returns empty data?

**Comment by navba-MSFT** [comment]
@Gill-Bates Apologies for the late reply. I did some research on this and below are my findings:

>Capacity metrics values are refreshed daily (up to 24 Hours). The time grain defines the time interval for which metrics values are presented. The supported time grain for all capacity metrics is one hour (PT1H).

More Info [here](https://docs.microsoft.com/en-us/azure/storage/files/storage-files-monitoring-reference#capacity-metrics)

So I am assuming that might be the reason you are getting blank values. To workaround the issue, you could try to tweak the TimeGrain, mention the StartTime, Endtime too and run it hourly and see if that helps.

>$metrics=Get-AzMetric -ResourceId "/subscriptions/<SUBSCRIPTION ID>/resourceGroups/<RESOURCE GROUP NAME>/providers/Microsoft.Storage/storageAccounts/<STORAGE ACCOUNT NAME>"  -MetricName "UsedCapacity" -AggregationType Average -StartTime "01:00:00" -EndTime "03:00:00" 
>
>$metrics.Data

Also refer [this](https://github.com/MicrosoftDocs/azure-docs/issues/29070).
 
Please let me know if you still have any questions on this. Awaiting your reply.
