### ISSUE TITLE
[Az.Tools.Installer] Install-AzModule fails on process locked

### ISSUE THREAD

**Issue by atkulp** [Azure/azure-powershell#15868]
I'm running the `Install-AzModule` cmdlet to install/update some modules within an Azure Pipeline.  Sporadically it fails on "cannot access the file."  This has been different dll's on different runs.  It doesn't make much sense that they would be locked based on our process.  Is this a known issue?

`PackageManagement\Install-Package : Package 'Az.Accounts' failed to be installed because: The process cannot access the file 'C:\Users\vstsdeploysvc\AppData\Local\Temp\mpkbuoeg\Microsoft.ApplicationInsights.dll' because it is being used by another process.`

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We are working on a new version of Tools installer. We will verify this scenario before we publish it.

**Comment by msJinLei** [comment]
Hi @atkulp, we have released new version of Az.Tools.Installer https://www.powershellgallery.com/packages/Az.Tools.Installer/0.2.0
If you find the issue can still be reproduced in the 0.2.0. Please set 
```
$DebugPreference = 'Continue'
```
and paste and output here
Thanks
