### ISSUE TITLE
azure-powershell/src/Compute/Compute/Extension/AzureDiskEncryption/Scripts/Find_1passAdeVersion_VM.ps1

### ISSUE THREAD

**Issue by desmphil** [Azure/azure-powershell#15888]
## Description

This script is good, however the $isStoppedEncryptedVM variable is not reset between VM therefore, all VM end up being with ADE state unavailable.

Also Added the PowerState of the VM.

` $results = @{
                VMName = $vmobject.Name
                ResourceGroupName = $vmobject.ResourceGroupName
                VM_OS = $vm_OS
                ADE_Version = "VM Is Encrypted but stopped."
                STATE = $VM_STATE`

**Comment by jaylabell** [comment]
@amjads1 Can you please take a look at this issue?

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by amjads1** [comment]
Engaged with the ADE team and investigation in progress. 

Reference document: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disk-encryption-sample-scripts#sample-powershell-scripts-for-azure-disk-encryption

**Comment by amjads1** [comment]
@MsGabsta Could you please look into this issue?

**Comment by MsGabsta** [comment]
The ADE Team and I are still looking at this and in discussions.

**Comment by MsGabsta** [comment]
We are rengaging the person who created this script.

**Comment by MsGabsta** [comment]
@desmphil it has taken some time to get to the root of this issue you are having, but we do have an answer for you.

This script was used in the past to assist customers with SSIRP back in 2020.  It isn't something we are asking customers to use today.

Does your scenario involve SSIRP?

**Comment by desmphil** [comment]
Hi Gabby,

Unless documented this is the only solution to force a specific folder in azure file sync without having to wait 24h.

Is there another solution already in place?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jyotsna-Anand** [comment]
@desmphil - The script only helps to retrieve a list of VMs within a subscription that are encrypted with Azure Disk Encryption extension (version without AAD credentials). It is not related to performing an Azure file sync. Can you please clarify your previous comment? 

Thank you!

**Comment by desmphil** [comment]
Sorry i have mixed 2 different issues.

Philippe Desmarais
Expert Solutions Microsoft
***@***.***
***@***.***
WWW.IT5.CA<http://WWW.IT5.CA>
[SignatureCompagnyPhil_Red_300]

**Comment by MsGabsta** [comment]
@desmphil do you require any more assistance on this issue?

**Comment by desmphil** [comment]
No

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MsGabsta** [comment]
Closing issue as there are no further questions from the customer.
