### ISSUE TITLE
User Id Intermittent Length Error

### ISSUE THREAD

**Issue by teknofobia** [Azure/azure-powershell#15890]
I have a powershell script that runs on release to call into the azure api.  Since September 15 we have seen intermittent issues with the following error:

> [error]'userId' exceeds maximum length of '80'.

Sometimes a rerun works.  Sometimes it fails.  I am loading the latest AZ module every time the script is run, and this script has had no changes within the last few months when it was originally written and implemented into our pipeline.

The script used is:

```
param([string]$subscriptionId = "", [string]$resourceGroup = "", [string]$apimName = "", [string]$publishUrl = "")

$ErrorActionPreference = 'Stop'

Import-Module Az

$ctx = Get-AzContext

if ($subscriptionId -eq '')
{
    $subscriptionId = $ctx.Subscription.Id
}

Write-Output "Resource Group: ${resourceGroup}"
Write-Output "APIM Name: ${apimName}"
Write-Output "Publish Url: ${publishUrl}"

# Set the context to the subscription Id
Select-AzSubscription -SubscriptionId $subscriptionId

Write-Output "Subscription loaded: ${subscriptionId}"

# load the API management gateway context 
$apimContext = New-AzApiManagementContext -ResourceGroupName $resourceGroup -ServiceName $apimName

Write-Output "APIM Context"
Write-Output $apimContext

$access = Get-AzApiManagementTenantAccess -Context $apimContext
$token = (New-AzApiManagementUserToken -Context $apimContext -UserId $access.Id).UserToken

$header = @{
    'Authorization' = 'SharedAccessSignature ' + $token
}

Invoke-RestMethod -Method Post -Uri $publishUrl -Headers $header

Write-Output "API Changes Published to Developer portal"
Write-Output $publishUrl
```

The offending line appears to be 

`$token = (New-AzApiManagementUserToken -Context $apimContext -UserId $access.Id).UserToken`

# Sample Log Output

> 2021-09-15T15:57:06.4977638Z APIM Context
2021-09-15T15:57:06.5178240Z 
2021-09-15T15:57:06.5217022Z ResourceGroupName : [omitted]
2021-09-15T15:57:06.5253507Z ServiceName       : [omitted]
2021-09-15T15:57:06.5302483Z 
2021-09-15T15:57:09.6904628Z ##[error]'userId' exceeds maximum length of '80'.
2021-09-15T15:57:09.8500865Z ##[error]PowerShell exited with code '1'.

**Comment by dingmeng-xue** [comment]
Please show the debug log during `$token = (New-AzApiManagementUserToken -Context $apimContext -UserId $access.Id).UserToken` execution. I'd like to know where constraint comes from. If it is part of service response, it will be service behavior change.

**Comment by teknofobia** [comment]
I tried adding debug statements for you, but it causes another error.

> 2021-09-20T15:04:40.5530943Z DEBUG: 3:04:40 PM - GetAzureRmApiManagementTenantAccess begin processing with ParameterSet '__AllParameterSets'.
> 2021-09-20T15:04:40.7911512Z ##[error]Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.
> 2021-09-20T15:04:40.9918559Z ##[error]PowerShell exited with code '1'.

**Comment by teknofobia** [comment]
We are continuing to get the error.  Not sure if your team has had a chance to look into it.

> 2021-09-28T20:16:41.8572671Z ##[error]'userId' exceeds maximum length of '80'.
> 2021-09-28T20:16:42.0353042Z ##[error]PowerShell exited with code '1'.

**Comment by navba-MSFT** [comment]
@teknofobia Apologies for the delayed reply. We are looking into this issue and we will update this thread once we have more details. In the meantime, if you have any questions, please feel free to ask.

**Comment by navba-MSFT** [comment]
@adrianhall Could you please look into this issue once you get a chance and update this thread? Awaiting your reply.

**Comment by adrianhall** [comment]
This will be fixed in the next release of the PowerShell module (it is part of the broader update to support the latest GA API version of the ARM management plane).  I'll update when that gets released.

**Comment by mikebudzynski** [comment]
The latest version of the API Management module is 4.0.2. Per @adrianhall's comments above, the issue should now be resolved. If you're still experiencing the problem with the latest version, please open a new issue.
