### ISSUE TITLE
Get-AzApiManagementTenantGitAcces returned /tenant/gitAccess as id and also returned Primary Keys

### ISSUE THREAD

**Issue by TonyDou** [Azure/azure-powershell#15898]
## Description

Get-AzApiManagementTenantGitAcces starts to return /tenant/gitAccess and primary keys in Az.ApiManagement version 2.3.0
![image](https://user-images.githubusercontent.com/5556990/133848191-b3311d4d-d9b6-4756-8931-0d4ff9054750.png)

## Steps to reproduce
1. make sure Az.ApiManagement is on 2.3.0
2. Run the following command to see the command is returning /tenant/gitAccess as id and primary keys.
```powershell
 Get-AzApiManagementTenantGitAccess -Context $APIMContext
```

## Environment data

```

```

## Module versions

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.5.3                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefa…
Script     2.3.0                 Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManage…
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Ob…
Script     2.1.0                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …

```

## Debug output

```

```

## Error output

```

```

**Comment by solankisamir** [comment]
Previous return value was
![image](https://user-images.githubusercontent.com/6847558/133848489-cacb9f95-e54b-4ef9-8463-96dd54ecd693.png)

**Comment by mikebudzynski** [comment]
This issue is resolved in the latest version of the API Management module (4.0.2). If you're still experiencing the problem with the latest version, please open a new issue.
