### ISSUE TITLE
Install-Module error

### ISSUE THREAD

**Issue by Jerry4013** [Azure/azure-powershell#15908]
## Description
I tried to run "Install-Module -Name Az", but got the error below: 
"Install-Module: The term 'Install-Module' is not recognized as a name of a cmdlet, function, script file, or executable program."
I upgrade my powershell to 7.1.4, but still could not get the "Install-Module". 
I searched a lot on google, most people mentioned "Windows Management Framework 5.1", but I could not find one for windows 10.

## Steps to reproduce

```powershell
Install-Module -Name Az
```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment]
Thanks for contacting us. `Install-Module` comes from `PowerShellGet` module. Please reference https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7.1

`PowerShellGet` belongs to https://github.com/PowerShell/PowerShellGet. If you have further question, please contact the developers of that repo.

**Comment by Jerry4013** [comment]
> Thanks for contacting us. `Install-Module` comes from `PowerShellGet` module. Please reference https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7.1
> 
> `PowerShellGet` belongs to https://github.com/PowerShell/PowerShellGet. If you have further question, please contact the developers of that repo.

Thanks for your reply! I tried to install PowerShellGet, but got some other errors. I will submit an issue in that repo, though. Thanks a lot!

**Comment by dingmeng-xue** [comment]
Thanks for the information. I'm closing now.

If you have any question to Azure PowerShell, please let us know.
