### ISSUE TITLE
"Import-AzWebAppKeyVaultCertificate\az webapp config ssl import"  issue PUT request

### ISSUE THREAD

**Issue by lilpug** [Azure/azure-powershell#15909]
Hi,

This will be a bit of an odd one with some question asking, so I do apologies in advance.

I have been running into an interesting issue and I might need a bit of guidance on it. 

For a bit of background context, my assumption was that when uploading a private certificate into an azure web app, its linked via the resource group, not the subscription, which is why a lot of the azure cli commands for SSL web app configuration are based on resource group. Even when I use the resource.azure.com website, when uploading certificates, I can see them under the resource group and web app they where uploaded to and not the other.

Now, if I go into the azure portal (no commandline) and create two new resource groups under the same subscription, I then create 2 new web apps, one in each of the new resource groups. When I upload a private certificate to one of the web apps, if I then navigate to the other (in a different resource group), I can now see the uploaded private certificate that I uploaded into the different resource group and web app.

This seems to imply that private certificates are shared between the subscription level rather than the resource groups?

I ran into this exact same issue when trying to do the same process via an azure cli, on the 'Import-AzWebAppKeyVaultCertificate' or even 'az webapp config ssl import' commands, they both throw a 409 status code with an exception telling me I cannot import the certificate into the second web app because the thumbprint already exists for this resource group (it doesn't). Even when I run other commands to show/list all the certificates for the second web app and its resource group, they all return an empty array as there is none. As it breaks in both types of commands I feel like its either a change which none of the cli commands now reflect or the API might need adjusting/fixing.

Looking at most of the azure powershell commands in this area, it appears that this should all be running under the resource group and not the subscription level but even the azure portal, it does seem to be running under the subscription level.

can anyone clarify if this is how its suppose to work or if its changed recently which is why half of the azure cli commands no longer work in this instance?

![image](https://user-images.githubusercontent.com/1824684/134027833-e8aa7684-dd86-4952-9cbc-7f331c05409f.png)
![image](https://user-images.githubusercontent.com/1824684/134028026-dd366e52-62d1-4a8c-9e02-299faadef48f.png)

**Comment by lilpug** [comment]
for some extra information, if I try and bypass this by checking if it was a 409 and attempt to the use thumbprint of the certificate it says already exists on the import, I then get the exception "Certificate for thumbprint *** not found.". It feels like there's no winning on this one, I can't even bypass the issue while its being fixed because all the checks are at the wrong level compared to the import process.

**Comment by lilpug** [comment]
right i know a bit more about this due to playing about this morning, the mistake i made yesterday is that I accidentally used the same app service plan across both the resource groups and app services, so i ended up with resource group1 holding both an app service and app plan, and resource group 2 holding just another app service linked to the app plan on resource group 1. This is how it breaks things, although all the commands for web app certificates are based on the resource group, its the resource group of the app plan, not the app service. Otherwise you get into the situation described above.

**Comment by lilpug** [comment]
just to add, in the mentioned situation above, as most of the azure commands want the resource group + app service name, you have no ability to find the certificate if the app plan is in a different resource group to the app service. It feels like all the commands are looking at the wrong parameter and in fact it should potentially be looking at the app plan name etc for the commands as its bound at that level and not the app service itself.

**Comment by Kotasudhakarreddy** [comment]
Thanks for your feedback! Will take a look.

**Comment by Kotasudhakarreddy** [comment]
@lilpug #20424 this fix should fix this issue as well. Please try with the latest version of `Az.Websites` module.
