### ISSUE TITLE
Error in creating LinkedService via PowerShell

### ISSUE THREAD

**Issue by Yuiheart** [Azure/azure-powershell#15931]
Hello Team!
I've encountered a problem when creating LinkedService via PowerShell. It will automatically change the 'type' of LinkedService from "AzureDataLakeStoreCosmosStructuredStream" to "LinkedService", and reports an error says "Invalid type 'LinkedService' is provided in 'linkedServices'.". This really confuses me a lot.

This is the error reported:
![image](https://user-images.githubusercontent.com/37691347/134455824-26515c0e-7e5a-44c2-a1b5-32f30a42ab38.png)

This is the JSON file I copied from an existing LinkedService:
```
{
    "name": "exchange_storage_test_StructuredStream",
    "type": "Microsoft.DataFactory/factories/linkedservices",
    "properties": {
        "annotations": [],
        "type": "AzureDataLakeStoreCosmosStructuredStream",
        "typeProperties": {
            "accountName": "exchangestoragetest",
            "tenant": "cdc5aeea-15c5-4db6-b079-fcadd2505dc2",
            "subscriptionId": "50cc5f0b-7f8c-4e8f-85cd-53bdb5efcf10",
            "resourceGroupName": "resourcegroupczj"
        }
    }
}
```

This is the command I use:
`Set-AzDataFactoryV2LinkedService -Name "exchange_storage_test_StructuredStream" -ResourceGroupName "resourcegroupczj" -DataFactoryName "TestPipeline" -DefinitionFile "<path-to-file>\SourceDatasetLinkedService.json"`

**Comment by shawnxzq** [comment]
@Yuiheart AzureDataLakeStoreCosmosStructuredStream is not supported connector in SDK/PS, could you please share how do you know this? Thanks!

**Comment by Yuiheart** [comment]
@shawnxzq I copied it from a LinkedService which is referenced by many datasets in ADF.
Could you please offer a solution if the type is not supported in PowerShell? The related tasks are all blocked now. Thanks!

**Comment by shawnxzq** [comment]
@Yuiheart, the AzureDataLakeStoreCosmosStructuredStream connector is feature for private whitelist customer only, it has limitations and no SDK/PS support.

You can try generic azure resource PS cmdlets to workaround, below is the example to create resource.
https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azresource?view=azps-6.4.0

**Comment by Yuiheart** [comment]
@shawnxzq Thanks for you advice! 
By the way, does the type 'Azure Data Lake Storage Gen1 for Cosmos Structured Stream' for Dataset support SDK/PS? I also encountered error when creating Dataset of this type.

**Comment by shawnxzq** [comment]
@Yuiheart, You will see the same issue for Cosmos Structured Stream dataset, it is not supported by SDK/PS for the same reason, you need to use the generic azure resource PS cmdlets to workaround.

BTW, I am going to close this issue as we already explained the details.
