### ISSUE TITLE
Missing Search-Parameter "-Id" for Get-AzVM

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#15942]
Regarding to the [Docs](https://docs.microsoft.com/en-us/powershell/module/az.compute/get-azvm?view=azps-6.4.0), the cmdlet `Get-AzVM` does not support the Parameter `-Id`.

Instead, I must use the inconvient way like

`Get-AzVM -ResourceGroupName foo -Name bar`

Supporting this Parameter would be very helpful.

**Comment by Drewm3** [comment]
@Gill-Bates, we will take a look at this and see if it can be enabled in a future release. Previously we were tracking these requests through a UserVoice system, but we have taken that down. So, I am going to leave this open here until we determine if the request can be accommodated.

**Comment by navba-MSFT** [comment]
@Gill-Bates Apologies for the late reply. We are looking into this issue. We will update this thread once we have more details. In the meantime, if you need any further assistance on this issue, do let us know.

@Drewm3 Could you please provide an update on this issue ? Awaiting your reply.
