### ISSUE TITLE
--aux-tenants parameter for New-AzResourceGroupDeployment

### ISSUE THREAD

**Issue by DarrenTyrrell** [Azure/azure-powershell#15946]
Feature request: --aux-tenant parameter for New-AzResourceGroupDeployment

Azure CLI _az deployment group create_ supports the parameter --aux-tenants to deploy resources across tenants. 

See https://docs.microsoft.com/en-us/cli/azure/deployment/group?view=azure-cli-latest#az_deployment_group_create-optional-parameters

This is important for users attempting to deploy reources such as VNET peerings across tenants via Powershell.

**Comment by isra-fel** [comment]
This feature request will be tracked in https://github.com/Azure/azure-powershell/issues/17407
