### ISSUE TITLE
Error in creating Dataset in ADF via PowerShell

### ISSUE THREAD

**Issue by Yuiheart** [Azure/azure-powershell#15943]
## Description
I copied the json file of a dataset in ADF, and created a dataset in a test ADF using this json file via PowerShell. 
The hint of the Command 'Set-AzDataFactoryV2Dataset' indicates successful creation, but when I navigate to the ADF portal it reports an error.
Could you please help find out the root cause? Thanks a lot!

## Command parameters
This is the Command executed.
```
Set-AzDataFactoryV2Dataset -ResourceGroupName $ProdConfig.ResourceGroupName -DataFactoryName $ProdConfig.DataFactoryNameforCAInfo -Name $ProdConfig.SourceDatasetforCAInfo -DefinitionFile "$($ProdConfig.PipelineSettingRootforCAInfo)\SourceDataset.json"
```

This is the json file copied from an in-use dataset.
```
{
    "name": "<dataset-name>",
    "properties": {
        "linkedServiceName": {
            "referenceName": "<linkedservice-name>",
            "type": "LinkedServiceReference"
        },
        "parameters": {
            "Path": {
                "type": "string"
            },
            "FileName": {
                "type": "string"
            }
        },
        "folder": {
            "name": "<folder-name>"
        },
        "annotations": [],
        "type": "AzureDataLakeStoreCosmosStructuredStreamFile",
        "structure": [
            <structures>
        ],
        "typeProperties": {
            "fileName": {
                "value": "@dataset().FileName",
                "type": "Expression"
            },
            "folderPath": {
                "value": "@dataset().Path",
                "type": "Expression"
            }
        }
    },
    "type": "Microsoft.DataFactory/factories/datasets"
}
```

## Error output
This is the output of the Command 'Set-AzDataFactoryV2Dataset'
```
Name              : <dataset-name>
Structure         : { <structures> }
Properties        : Microsoft.Azure.Management.DataFactory.Models.Dataset
Id                :  <dataset-id>
ETag              :  <dataset-etag>
ResourceGroupName : <rg-name>
DataFactoryName   : <adf-name>
```
This is the error reported in ADF portal:

> Could not load resource '<resource-name>'. Please ensure no mistakes in the JSON and that referenced resources exist. Status: UnknownError, Possible reason: Fetch failed for named: dataset$<resource-name>. Adapter not found. Type: dataset.

**Comment by Yuiheart** [comment]
Already resolved by @shawnxzq

**Comment by shawnxzq** [comment]
@Yuiheart As we explained in the issue https://github.com/Azure/azure-powershell/issues/15931, the dataset with type "AzureDataLakeStoreCosmosStructuredStreamFile" is not supported in SDK/PS, you can use azure generic resource PS cmdlets as a workaroud.
