### ISSUE TITLE
Search-AzGraph -First maximum value

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-powershell#15955]
Run command:
Search-AzGraph -Query "where type =~'Microsoft.compute/virtualmachines'" -First 5000

Search-AzGraph: Cannot validate argument on parameter 'First'. The 5000 argument is greater than the maximum allowed range of 1000. Supply an argument that is less than or equal to 1000 and then try the command again.

This seems a document issue, we might need to correct the number 5000 in the document below.
https://docs.microsoft.com/en-us/azure/governance/resource-graph/concepts/work-with-data

The az cli document has corrected it to 1000.
https://github.com/Azure/azure-cli-extensions/issues/498

**Comment by dingmeng-xue** [comment]
The doc doesn't belong to Azure PowerShell team. I have created the issue to azure-docs. 

Close this issue now
