### ISSUE TITLE
Get-AzResource does not show managed OS disks

### ISSUE THREAD

**Issue by nubgamerz** [Azure/azure-powershell#15965]
Hello

While in the process of having to programmatically remove specific resources, I've found that contrary to this page here:
https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azresource?view=azps-6.4.0

Disks do not show up in the Get-AzResource cmd-let.

When digging further, I went to https://resources.azure.com - and the disks are not listed under the resource group either.

If you use Get-AzDisk -Id and specify the exact resource ID of the disk, it shows up.

But if you use Get-AzDisk -ResourceGroupName it does not show up.

Steps to reproduce:

1. Create a new RG 
2. Create a new Windows or Linux VM with Standard SSD OS disk
3. Open PWSH and call "Get-AzResource -ResourceGroupName RGNAME | ft
4. See that there are no disks showing
5. Go to https://resources.azure.com and navigate to the resource group
6. See that there no disks showing

On that topic, it is still possible to get the disk via RG name with the following command:

Get-AzDisk | Where-Object {$_.ResourceGroupName -eq "RGNAME"}

This will list the disks in the resource group.

Powershell Version: 7.0.3
Az Module Version: 6.4.0

**Comment by nubgamerz** [comment]
Just as an update to this, running through Azure DevOps (Azure Powershell v 4.185) the Get-AzResource works for disks.

**Comment by dingmeng-xue** [comment]
Thanks. If you still have the problem, please share the version of Az.Storage used in local and Devops Azure PowerShell v 4.185.

**Comment by nubgamerz** [comment]
The Azure DevOps is using Microsoft Managed Agent, so it's the latest version.

As for locally: Az.Storage 3.11.0

Keep in mind though, this hasn't anything to do with storage, as the resource provider for OS disks is Microsoft.Compute.

For reference, using Az.Compute 4.17.0

**Comment by dingmeng-xue** [comment]
Sorry for typo. I was confused with `Get-Disk`. Yes, I need the version of Az.Compute.

I cannot reproduce the issue in my environment with the latest version. Do you mean the version of Az.Compute is the same in local and DevOps?

Could you share the debug log during `Get-AzDisk -Id <>`? You can turn on debug with setting `$DebugPreference = "Continue"`

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by amjads1** [comment]
@oriwolman Could you look into this issue?
