### ISSUE TITLE
Installing Azure PowerShell from PowerShellGet is agonizingly slow

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-powershell#15979]
There is an old issue:

- https://github.com/Azure/azure-powershell/issues/1308

However, [installing the latest `Az` module from PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.4.0) is still very slow:

```pwsh
> Measure-Command {Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force}

Days              : 0
Hours             : 0
Minutes           : 22
Seconds           : 24
Milliseconds      : 687
Ticks             : 13446874229
TotalDays         : 0.0155635118391204
TotalHours        : 0.373524284138889
TotalMinutes      : 22.4114570483333
TotalSeconds      : 1344.6874229
TotalMilliseconds : 1344687.4229
```

On the other hand, [installing with MSI](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps-msi?view=azps-6.4.0) is much faster.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We are working on a new approach. Please reference: https://github.com/Azure/azure-powershell/issues/15986
