### ISSUE TITLE
Azure CLI not loading properly ( Unable to run az commands)

### ISSUE THREAD

**Issue by nidiculageorge** [Azure/azure-powershell#15976]
Hi Team,

When loading the Azure Cloudshell from browser i am getting the below error while loading

_**Import-Module: /opt/microsoft/powershell/7/profile.ps1:13
Line |
13 | Microsoft.PowerShell.Core\Import-Module -Name PSCloudShellUtility
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| This module requires Az.Accounts version 2.5.1. An earlier version of Az.Accounts is imported in the current PowerShell session. Please open a new
| session before importing this module. This error could indicate that multiple incompatible versions of the Azure PowerShell cmdlets are installed on your
| system. Please see https://aka.ms/azps-version-error for troubleshooting information.

InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:304
Line |
304 | & ($script:PSCloudShellUtilityModuleInfo){Get-CloudShellTip -ErrorAct …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
| object.

VERBOSE: Authenticating to Azure ...
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
60 | & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
| object.

Invoke-CloudShellTelemetry: /opt/microsoft/powershell/7/profile.ps1:91
Line |
91 | Invoke-CloudShellTelemetry -LogLabel "GETSUBSCRIPTIONID" -Sta …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
| object.

InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
60 | & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
| object.

InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
60 | & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
| object.

InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
60 | & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
| object.

Import-Module: /opt/microsoft/powershell/7/profile.ps1:391
Line |
391 | Microsoft.PowerShell.Core\Import-Module -Name AzurePSDrive
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| This module requires Az.Accounts version 2.5.1. An earlier version of Az.Accounts is imported in the current PowerShell session. Please open a new
| session before importing this module. This error could indicate that multiple incompatible versions of the Azure PowerShell cmdlets are installed on your
| system. Please see https://aka.ms/azps-version-error for troubleshooting information.

VERBOSE: Building your Azure drive ...
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
60 | & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
| object.

New-PSDrive: /opt/microsoft/powershell/7/profile.ps1:402
Line |
402 | $null = Microsoft.PowerShell.Management\New-PSDrive -Name Azure - …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Cannot find a provider with the name 'SHiPS'.

WARNING: Something went wrong while creating Azure drive. You can still use this shell to run Azure PowerShell commands.
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
60 | & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
| object.

InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:415
Line |
415 | & ($script:PSCloudShellUtilityModuleInfo){Set-CloudShellPSReadLineKey …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
| object.

InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
60 | & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
| object.**_

I am unable to run any Set-Az commands and all. Some conflict with existing setting ?

**Comment by dingmeng-xue** [comment]
Thanks for reporting. According to the log, it seems AzurePSDrive needs a new version of Az.Accounts than the version imported. You can get the current imported version of Az.Accounts via `Get-Module Az.Accounts`. Then import correct version of AzurePSDrive which depends on the older version of Az.Accounts .

Another approach is to install the new version of Az.Accounts to your CloudShell but [`-Scope`](https://docs.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershell-7.1) should be current user. Then restart the CloudShell and please try your script again.

**Comment by nidiculageorge** [comment]
@dingmeng-xue 

![image](https://user-images.githubusercontent.com/43850474/135799389-8b6b8ee7-80ea-4ef8-999f-d2276a58ea78.png)


When i run the get-module i am getting the above .

Can you please share the command to Install in cludshell

**Comment by dingmeng-xue** [comment]
You can use below script to install the latest version of Az.Accounts for current user. You need to restart CloudShell after installing module
```
Install-Module -Scope CurrentUser -Name Az.Accounts -Repository PSGallery -Force
```

**Comment by nidiculageorge** [comment]
@dingmeng-xue 

![image](https://user-images.githubusercontent.com/43850474/135883937-c05efab7-02e4-44f1-9277-5fe141c137e2.png)

I tried closing the powershell and tried again same issue

**Comment by dingmeng-xue** [comment]
Warning message can be ignored. You need to restart CloudShell and check the version of Az.Accounts.

**Comment by nidiculageorge** [comment]
Hi Team,

@dingmeng-xue 

Sorry for the late reply i have tried restarting the cloudshell and ran the command below command.The same issue

![image](https://user-images.githubusercontent.com/43850474/140923734-60f660c1-4c32-4533-896c-a005e9088e03.png)

**Comment by nidiculageorge** [comment]
![image](https://user-images.githubusercontent.com/43850474/140924189-97e3088a-84d0-4743-b689-bfe267527648.png)

**Comment by dingmeng-xue** [comment]
Hi @nidiculageorge , the message shows you have already installed and imported the latest Az.Accounts. Why do you need to install it again in CloudShell?

**Comment by nidiculageorge** [comment]
@dingmeng-xue 

Then why i am getting the following error while opening the cloudshell every time

Import-Module: /opt/microsoft/powershell/7-preview/profile.ps1:13
Line |
  13 |  Microsoft.PowerShell.Core\Import-Module -Name PSCloudShellUtility
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This module requires Az.Accounts version 2.6.0. An earlier version of Az.Accounts is imported in the current PowerShell session. Please open a new
     | session before importing this module. This error could indicate that multiple incompatible versions of the Azure PowerShell cmdlets are installed on your
     | system. Please see https://aka.ms/azps-version-error for troubleshooting information.

InvalidOperation: /opt/microsoft/powershell/7-preview/profile.ps1:304
Line |
 304 |  & ($script:PSCloudShellUtilityModuleInfo){Get-CloudShellTip -ErrorAct …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object.

VERBOSE: Authenticating to Azure ...
InvalidOperation: /opt/microsoft/powershell/7-preview/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object.

Invoke-CloudShellTelemetry: /opt/microsoft/powershell/7-preview/profile.ps1:91
Line |
  91 |          Invoke-CloudShellTelemetry -LogLabel "GETSUBSCRIPTIONID" -Sta …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object.

InvalidOperation: /opt/microsoft/powershell/7-preview/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object.

InvalidOperation: /opt/microsoft/powershell/7-preview/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object.

InvalidOperation: /opt/microsoft/powershell/7-preview/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object.

Import-Module: /opt/microsoft/powershell/7-preview/profile.ps1:391
Line |
 391 |      Microsoft.PowerShell.Core\Import-Module -Name AzurePSDrive
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This module requires Az.Accounts version 2.6.0. An earlier version of Az.Accounts is imported in the current PowerShell session. Please open a new
     | session before importing this module. This error could indicate that multiple incompatible versions of the Azure PowerShell cmdlets are installed on your
     | system. Please see https://aka.ms/azps-version-error for troubleshooting information.

VERBOSE: Building your Azure drive ...
InvalidOperation: /opt/microsoft/powershell/7-preview/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object.

New-PSDrive: /opt/microsoft/powershell/7-preview/profile.ps1:402
Line |
 402 |      $null = Microsoft.PowerShell.Management\New-PSDrive -Name Azure - …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find a provider with the name 'SHiPS'.

WARNING: Something went wrong while creating Azure drive. You can still use this shell to run Azure PowerShell commands.
InvalidOperation: /opt/microsoft/powershell/7-preview/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object.

InvalidOperation: /opt/microsoft/powershell/7-preview/profile.ps1:415
Line |
 415 |  & ($script:PSCloudShellUtilityModuleInfo){Set-CloudShellPSReadLineKey …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object.

InvalidOperation: /opt/microsoft/powershell/7-preview/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo
     | object.

**Comment by dingmeng-xue** [comment]
is it due to the scope of `Microsoft.PowerShell.Core\Import-Module -Name PSCloudShellUtility` is incorrect? Could you manually execute import-module and set scope to currentuser as well?

In addition, you can use `Get-Module Az* -ListAvailable` to get all installed Az.Accounts.

If Az.Accounts only has the latest version but Import-Module still shows error, you need to raise the question to PowerShell https://github.com/PowerShell/PowerShell/issues

**Comment by nidiculageorge** [comment]
@dingmeng-xue 

Please see the output of  Get-Module Az* -ListAvailable

![image](https://user-images.githubusercontent.com/43850474/144176006-c90a0b27-83cb-4092-991c-94a0716856df.png)

![image](https://user-images.githubusercontent.com/43850474/144176045-9d688baf-e4d3-4f21-a8c0-0b6cefe8e0f6.png)

**Comment by dingmeng-xue** [comment]
Hi @nidiculageorge , could you see the same error even you restarted CloudShell? If issue is still there, can we have a call and you share me your screen? You can find my contact information on profile. Please drop me email .

**Comment by craigforr** [comment]
It appears that I have exactly the same issue:
```
Requesting a Cloud Shell.Succeeded.
Connecting terminal...

Import-Module: /opt/microsoft/powershell/7/profile.ps1:13
Line |
  13 |  Microsoft.PowerShell.Core\Import-Module -Name PSCloudShellUtility
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This module requires Az.Accounts version 2.7.0. An earlier version of Az.Accounts is
     | imported in the current PowerShell session. Please open a new session before importing
     | this module. This error could indicate that multiple incompatible versions of the Azure
     | PowerShell cmdlets are installed on your system. Please see
     | https://aka.ms/azps-version-error for troubleshooting information.

InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:304
Line |
 304 |  & ($script:PSCloudShellUtilityModuleInfo){Get-CloudShellTip -ErrorAct …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It
     | must result in a command name, a script block, or a CommandInfo object.

VERBOSE: Authenticating to Azure ...
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It
     | must result in a command name, a script block, or a CommandInfo object.

Invoke-CloudShellTelemetry: /opt/microsoft/powershell/7/profile.ps1:91
Line |
  91 |          Invoke-CloudShellTelemetry -LogLabel "GETSUBSCRIPTIONID" -Sta …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It
     | must result in a command name, a script block, or a CommandInfo object.

InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It
     | must result in a command name, a script block, or a CommandInfo object.

VERBOSE: Loading CurrentHost profile ...
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It
     | must result in a command name, a script block, or a CommandInfo object.

InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It
     | must result in a command name, a script block, or a CommandInfo object.

Import-Module: /opt/microsoft/powershell/7/profile.ps1:391
Line |
 391 |      Microsoft.PowerShell.Core\Import-Module -Name AzurePSDrive
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This module requires Az.Accounts version 2.7.0. An earlier version of Az.Accounts is
     | imported in the current PowerShell session. Please open a new session before importing
     | this module. This error could indicate that multiple incompatible versions of the Azure
     | PowerShell cmdlets are installed on your system. Please see
     | https://aka.ms/azps-version-error for troubleshooting information.

VERBOSE: Building your Azure drive ...
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It
     | must result in a command name, a script block, or a CommandInfo object.

New-PSDrive: /opt/microsoft/powershell/7/profile.ps1:402
Line |
 402 |      $null = Microsoft.PowerShell.Management\New-PSDrive -Name Azure - …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find a provider with the name 'SHiPS'.

WARNING: Something went wrong while creating Azure drive. You can still use this shell to run Azure PowerShell commands.
InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It
     | must result in a command name, a script block, or a CommandInfo object.

InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:415
Line |
 415 |  & ($script:PSCloudShellUtilityModuleInfo){Set-CloudShellPSReadLineKey …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It
     | must result in a command name, a script block, or a CommandInfo object.

InvalidOperation: /opt/microsoft/powershell/7/profile.ps1:60
Line |
  60 |      & ($script:PSCloudShellUtilityModuleInfo){param([string]$Label, [ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The expression after '&' in a pipeline element produced an object that was not valid. It
     | must result in a command name, a script block, or a CommandInfo object.
```

This reoccurs every time I open Cloud Shell now, and restarting has no effect.  It occurs whether I use PowerShell from the drop-down menu, or run `pwsh` from within a BASH shell.

Was there every any resolution to this problem, @dingmeng-xue?

**Comment by dingmeng-xue** [comment]
Hi @craigforr , could you simplify your script and share it in email? Current repo is only for Azure PowerShell. Your error seems out of our scope. But I can try the script and forward to correct team.

**Comment by craigforr** [comment]
@dingmeng-xue: Is there any additional information I can provide to help troubleshoot this issue?

**Comment by dingmeng-xue** [comment]
@craigforr , Sorry that I missed your message. The bot omitted your message because you are not original reporter of  issue.

According to log, the error message is not from Azure PowerShell. We have no access to those codes. It seems Azure drive is not available. One recommendation is to drop current drive and create new one if there is no data on existing Azure drive. If you need CloudShell support, please raise a support ticket to CloudShell.
