### ISSUE TITLE
Improve Az.Tools.Installer

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#15986]
## Description of the new feature

Due to performance and footprint consideration, we release Az.Tools.Installer. Basing on the feedback of the first version of Az.Tools.Installer, we expect new features in the new version.

**Comment by SQLCanuck** [comment]
For me the installation via Az.Tools.Installer as of version 0.2.0 was many times slower than just using the normal Install-Module -Name Az command.  The slow performance was to the point of making it unusable, in my case and I had to abort the process.  It seemed to hang on the download package stage.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We compared the performance between Az.Tools.Installer and PowerShellGet. There are multiple factors impacting performance. Some of logic are sealed in PowerShell internal and out of our control. 

I'd like to know your environment. What version of PowerShell is? It is great if you can share the time cost of normal `Install-Module -Name Az` in your environment.

**Comment by SQLCanuck** [comment]
@dingmeng-xue 

![image](https://user-images.githubusercontent.com/38919668/148427688-dddff9f9-6c50-4175-aa7c-6c1f8ddcab82.png)

Though on testing today and having issues on both, it could just be the horrible and unpredictable performance from PowerShell Gallery.  Hopefully the Microsoft Azure team managers can talk to theirs to get things back on track and at an acceptable level.

**Comment by msJinLei** [comment]
Fixed in Az.Tools.Installer 0.2.0 https://www.powershellgallery.com/packages/Az.Tools.Installer/0.2.0
