### ISSUE TITLE
Remove-AzVMBackup documentation is not correct

### ISSUE THREAD

**Issue by stevemorris1106** [Azure/azure-powershell#15999]
## Description
When trying to look up what the value for "tag" is, this is not documented. 

## Module versions

6.4.0

**Comment by dingmeng-xue** [comment]
Compute team, the example and description are not clear.
https://docs.microsoft.com/en-us/powershell/module/az.compute/remove-azvmbackup?view=azps-6.4.0

**Comment by avirishuv** [comment]
Thanks @dingmeng-xue I'll follow up for this.

**Comment by avirishuv** [comment]
quick note: we will be fixing the documentation, and provide an update here once it is done.

**Comment by avirishuv** [comment]
fix is still in the backlog for this.

**Comment by navba-MSFT** [comment]
@stevemorris1106 Apologies for the late reply. We are looking into this issue. We will update this thread once we have more details. In the meantime, if you need any further assistance on this issue, do let us know.

@avirishuv Could you please provide an update on the fix ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@stevemorris1106 The above PR has been filed and it is currently in review phase. In the meantime, if you have any questions, please feel free to ask.
