### ISSUE TITLE
Get-AzADApplication should deliver "Created on" Information

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#15997]
Running `Get-AzADApplication` should deliver the "Created On" Timestamp

![image](https://user-images.githubusercontent.com/25774289/135614103-c95da9a7-3353-446e-a2ef-8297f70b89cb.png)

From the Portal, I get the information. Why not also from the cmdlet?

![image](https://user-images.githubusercontent.com/25774289/135614187-c5af0767-7c88-4cf4-aecd-c331101665cf.png)

```
PS C:\Windows\System32> Get-Module -Name Az.Resources

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     4.3.0                 Az.Resources

```

**Comment by dcaro** [comment]
@Gill-Bates thanks for reporting this issue. The AzADApplication cmdlets are currently using the AzureAD Graph API and we are in the process of switching to MS Graph, this should be fixed with the new version.

**Comment by dingmeng-xue** [comment]
Hi @Gill-Bates  , we have released the preview version of Az.Resources 5.0.0 https://www.powershellgallery.com/packages/Az.Resources/5.0.0-preview

Could you check whether existing parameter set can meet your requirement?

**Comment by VeryEarly** [comment]
close this issue for now, feel free to re-open for further questions.
