### ISSUE TITLE
Set-AzApiManagement not working with API Management deployments into Virtual Network : External

### ISSUE THREAD

**Issue by saurabhvyas9** [Azure/azure-powershell#15998]
## Description
`Set-AzApiManagement` is not working with API Management (APIM) service once APIM is configured with a Public IP. Debug response suggests to use API version which is not used in cmdlet. 
It could be that Powershell module `Az.ApiManagement` is not as updated as the REST API wherein the API version is passed as a query string. 

This blocks from scaling APIM post upgrading APIM service to network Type `External` and assigning a pip. 
It was working using the below snippet before APIM was upgraded to use a public IP. 

## Steps to reproduce
```powershell
$apimName="APIM-UAT"
$apimRG="RG-APIM-UAT"
$apimResource=Get-AzApiManagement -Name $apimName -ResourceGroupName $apimRG
$APIM_CurrLocation=$apimResource.Location
$APIM_CurrVNET=$apimResource.VirtualNetwork
$apimUpdatedResource = Update-AzApiManagementRegion `
                    -ApiManagement $apimName `
                    -Location $APIM_CurrLocation`
                    -Capacity 4 `
                    -VirtualNetwork $APIM_CurrVNET `
                    -Sku "Premium"

Set-AzApiManagement -InputObject $apimUpdatedResource -PassThru
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands                                              
---------- -------    ----                                ----------------                                              
Script     2.1.0      Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToP...
```

## Debug output

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : fdd5b578-fe02-4d9c-a34a-76ca89512335
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 9cb793dd-03e4-4698-ab5e-5a2e6fb89c3f
x-ms-routing-request-id       : AUSTRALIASOUTHEAST:20210907T003811Z:9cb793dd-03e4-4698-ab5e-5a2e6fb89c3f
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 07 Sep 2021 00:38:10 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "error": {
    "code": "InvalidOperation",
    "message": "API Management deployments into Virtual Network : External, which have Public IP resources configured (Australia Southeast - /subscription
    s/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/RG-APIM-UAT/providers/Microsoft.Network/publicIPAddresses/pip-apim-uat) must use api-version 2
    021-01-01-preview and higher for managing it.",
    "details": null,
    "innerError": null
  }
}
```

**Comment by Cavematt** [comment]
@miaojiang is there any updates with regards to this?

**Comment by navba-MSFT** [comment]
@saurabhvyas9 @Cavematt Apologies for the late reply. We are looking into this issue. We will provide an update once we have more details.

@adrianhall Could you please provide an update on this once you get a chance ? Awaiting your reply.

**Comment by adrianhall** [comment]
We are currently working on new powershell cmdlets that work with the latest GA API version.  Once those are released, this problem will go away.  I'll keep this open as a mechanism to track and will close when the new powershell cmdlets are released.

**Comment by thiagosantos** [comment]
@adrianhall any news about this issue?
I have a script that should update my SSL certificates using let's encrypt and I can't cause I'm running in the same issue @saurabhvyas9 detailed.

**Comment by mikebudzynski** [comment]
The latest version of the API Management module is 4.0.2. Per @adrianhall's comments above, the issue should now be resolved. If you're still experiencing the problem with the latest version, please open a new issue.
