### ISSUE TITLE
RunVersionController.ps1 deletes psd1 and psm1 of Az.KeyVault.Extension

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#16004]
## Description

The execution of `RunVersionController.ps1` deletes the `Az.KeyVault.Extension.psd1` and `Az.KeyVault.Extension.psm1` under folder `artifacts\Az.KeyVault\Az.KeyVault.Extension`. It leads `RunVersionController.ps1` is not idempotent. Developer needs to build all modules again if they want to execute `RunVersionController.ps1` again

**Comment by BethanyZhou** [comment]
Hi @dingmeng-xue , I can't reproduce this issue on my local. Could you provide more information for your scenario? Or we can assume this issue is gone.

**Comment by dingmeng-xue** [comment]
Close it because it cannot be reproduced.
