### ISSUE TITLE
Az.Resources Api Calls move to Microsoft Graph

### ISSUE THREAD

**Issue by chibs89** [Azure/azure-powershell#16009]
The Az.Resources commands target the Azure Active Directory Graph which is deprecated and the api permissions can not be granted to new app registrations anymore. 
So with new Azure Automation Accounts you can not read Users or Groups unless the CMDlets target the Microsoft Graph API.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. As far as we know, AAD Graph API will be deprecated at the mid of the next year. But tenant admin may disable it in advance. If your script is blocked, please contact admin of tenant.

Azure PowerShell team is migrating features from AAD graph to MSGraph. It will take couple months. 

Could you share us the list of cmdlets? We will prioritize it.

**Comment by chibs89** [comment]
I found an MS Doc Entry where it is stated that Microsoft from now on deactivates the grant of the needed API-Permissions.
https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-faq
So it is not deactivated by me or anyone from my team. But we can not open a request for every new customer I set up
In this case we are using following commands: 
Get-AzADGroup, Get-AzADGroupmemb, Get-AzADUser

**Comment by dingmeng-xue** [comment]
HI @chibs89 , could you point out "on deactivates the grant of the needed API-Permissions" in FAQ? According to our test, our test environment can still allow us grant API permission. 

@dcaro , could you help confirm whether it is a tenant admin setting?

**Comment by chibs89** [comment]
![image](https://user-images.githubusercontent.com/60780618/135881300-9360a716-9761-4639-83ed-939dcb771987.png)
![image](https://user-images.githubusercontent.com/60780618/135881426-b6c4fae8-47ed-4b6e-bbbf-3baadd13c97e.png)
So I can't add the Api Permission to the newly created Appregistration and also I can't add the Permission to long existing Appregistrations.

**Comment by dcaro** [comment]
@chibs89  We are investigating the issue with the identity team.
@LockTar we are actively working on the migration to MS Graph. Our plan is to have soon a preview of the Azure PowerShell module that uses Microsoft Graph and a GA shortly after. 
I have a blog post in review that will give more details about our roadmap.

**Comment by LockTar** [comment]
@dcaro thank you for the link of the blog. I asked a question beneath the blog.
