### ISSUE TITLE
$ErrorActionPreference = "Stop"

### ISSUE THREAD

**Issue by dimaMo9494** [Azure/azure-powershell#16014]
## Description
The issue only reproduces when running from powershell console. Not when running from VSCode. Which is interesting by itself.
Repro script:
```
$ErrorActionPreference = "Stop"

# 1
# This will terminate the script, as expected
#Get-AzResourceGroup SomethingThatNotExists 

# 2
# This will ignore the error, and continue, as expected
#Start-AzCloudService -Name SomethingThatNotExists -ResourceGroupName NotExistsAsWell -ErrorAction "Continue"

# 3
# This will report error, but the script will continue running - problem
# Expected to stop running the script, as $ErrorActionPreference set implicitly
# Interestingly, it happens only when running from command line. When running in vscode shell, it stops executing as expected.
Get-AzCloudService -Name SomethingThatNotExists -ResourceGroupName NotExistsAsWell

# 4 - Same problem observed with Start-AzCloudService, Update-AzCloudService
#Start-AzCloudService -Name SomethingThatNotExists -ResourceGroupName NotExistsAsWell

Write-Host The script is still running
```
![roman](https://user-images.githubusercontent.com/72008838/135869731-f9437487-29ae-480a-8caf-bd049e5b6ceb.png)

The issue only reproduces when running from powershell console. Not when running from VSCode. Which is interesting by itself.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. This is a general issue to all autogen based cmdlets. I have created one issue to autorest.powershell tool. 

https://github.com/Azure/autorest.powershell/issues/846
