### ISSUE TITLE
Add option to create Workspace based Application Insights resource through New-AzApplicationInsights

### ISSUE THREAD

**Issue by stefanpetter** [Azure/azure-powershell#16027]
## Description of the new feature
Currently it is only possible to create a Classic Application Insights resource through the New-AzApplicationInsights cmdLet. As soon as you access the resource through the portal, you get a message that "Classic Application Insights is deprecated and will be retired in February 2024.". It would be nice to also create a Workspace based Application Insights through the cmdLet

## Proposed implementation details (optional)
I'd suggest adding an optional -WorkspaceId parameter to the cmdLet. As soon as the parameter is set, the Application Insights will be of the new type and will use the given Workspace.

**Comment by VeryEarly** [comment]
feature already released with Az.ApplicationInsights 2.0.0, close this issue for now.
