### ISSUE TITLE
Parameter -AssignSystemIdentity is not available

### ISSUE THREAD

**Issue by J-a-k-o-b** [Azure/azure-powershell#16028]
Hi,
the mentioned Parameter -AssignSystemIdentity is not available in the latest AZ.Accounts Module (2.5.3)

![image](https://user-images.githubusercontent.com/46894290/136192428-b9ac4185-aa53-4703-94fe-22639e332d08.png)

![image](https://user-images.githubusercontent.com/46894290/136192520-7a6d249e-8736-4843-8cf3-7bb3282fb6b9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88f83973-0806-9b2b-28d7-575c0fa1a7ec
* Version Independent ID: a22e91bf-78f2-aeac-45e8-ae5dec3efc92
* Content: [Set-AzAutomationAccount (Az.Automation)](https://docs.microsoft.com/en-us/powershell/module/az.automation/set-azautomationaccount?view=azps-6.4.0)
* Content Source: [src/Automation/Automation/help/Set-AzAutomationAccount.md](https://github.com/Azure/azure-powershell/blob/main/src/Automation/Automation/help/Set-AzAutomationAccount.md)
* Service: **automation**
* GitHub Login: @dcaro
* Microsoft Alias: **dcaro**

**Comment by alexandair** [comment]
@J-a-k-o-b Do you have the latest Az modules (6.4.0)?

![image](https://user-images.githubusercontent.com/3135708/136248507-eebc4df7-612d-4b68-b9fd-ad999247debc.png)

**Comment by J-a-k-o-b** [comment]
Hi @alexandair,
yeah, you're completely right... I've mixed up the modules, my fault... After updating the module az.automation I was able to use this parameter.
@dingmeng-xue, you do not need to forward it.
