### ISSUE TITLE
Parameter to name a Invoke-AzVMRunCommand job

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#16041]
### Discussed in https://github.com/Azure/azure-powershell/discussions/15917

<div type='discussions-op-text'>

<sup>Originally posted by **KrzysztofR79** September 21, 2021</sup>
I run quite a lot of jobs with Invoke-AzVMRunCommand, and ATM, there's no way to tell what VM a given job runs against.
What I'm missing is a parameter to name the job so I can name it accordingly to VM I run it against. When listing jobs with Get-Job, all I can see is a vague "Long Running Operation for 'Invoke-AzVMRunCommand'" job name.
</div>

**Comment by avirishuv** [comment]
@oriwolman could you please take a look at this issue?

**Comment by oriwolman** [comment]
@amjads1 could you please take a look at this issue?

**Comment by Sandido** [comment]
@dingmeng-xue ,
The Invoke-AzVMRunCommand does have the VMName parameter to indicate which CM the script is to be run on. I'm guessing the primary ask is for Get-Job and the content in the VMRunCommand. 

How is the user using Get-Job?
From reading its public docs, seems like a core cmdlet that returns properties about generic background jobs. 
Does Get-Job just return all properties of a background job, or would something in Get-Job need to change for this feature to be made?

**Comment by amjads1** [comment]
@dingmeng-xue - Can you please respond to earlier comment so that we can work towards closure of this item?

**Comment by amjads1** [comment]
@dingmeng-xue - Following up to check if you need any further help. If we don't hear any response by end of this week then I will assume that issue is no longer existing and will close this issue.

**Comment by amjads1** [comment]
Closing this issue as we didn't hear any response and assuming that issue is resolved. Please feel free to re-open if you need any further help. Thanks!

**Comment by Sandido** [comment]
As per the email thread with @amjads1  and @dingmeng-xue , the preferred behavior is to keep this item open until the PS team has time to investigate it.

**Comment by amjads1** [comment]
@Sandido Following up to check if you have any updates to share post your investigation.

**Comment by amjads1** [comment]
@Sandido Can you please update if the PS team was able to investigate on this issue and the next steps here?

**Comment by Sandido** [comment]
I asked @dingmeng-xue  about it to see if they can investigate further.

**Comment by amjads1** [comment]
@dingmeng-xue Could you please share any updates from your investigation on this issue?

**Comment by nikhilpatel909** [comment]
We are working with PowerShell team on this feature request,

**Comment by nikhilpatel909** [comment]
@dingmeng-xue @Sandido Please provide any update on the investigation. Do we need to close this issue?

**Comment by nikhilpatel909** [comment]
@sandido any update on this feature request

**Comment by nikhilpatel909** [comment]
we are not going to more forward with this request at this time, However we will keep it in our backlog and that any future requests for this feature should be submitted to feedback.azure.com
