### ISSUE TITLE
Update Az.ConnectedKubernetes powershell module

### ISSUE THREAD

**Issue by akashkeshari** [Azure/azure-powershell#16042]
## Description

The current powershell module Az.ConnectedKubernetes fails when using the helm 3.7
Below is the error message received:

New-AzConnectedKubernetes
Supply values for the following parameters:
ClusterName: powershellcc1
ResourceGroupName: akkeshar
Location: eastus
Error: release: not found
**Error: unknown command "chart" for "helm"**
Run 'helm --help' for usage.
Error: unknown command "chart" for "helm"
Run 'helm --help' for usage.
New-AzConnectedKubernetes : Method invocation failed because [System.Security.Cryptography.RSACng] does not contain a method named 'ExportRSAPublicKey'.
At line:1 char:1
+ New-AzConnectedKubernetes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-AzConnectedKubernetes], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound,New-AzConnectedKubernetes

## Cost
Any customer running the module with helm 3.7 installed on the machine will face this issue
Updating the module with current release of az CLI will fix this issue.

**Comment by dingmeng-xue** [comment]
link to PR #16303
