### ISSUE TITLE
Bump API version of Az.Databricks to preview/2021-04-01-preview

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#16052]
## Description of the new feature

It is expected that API version of Az.Databricks needs to be updated to preview/2021-04-01-preview.  https://github.com/Azure/azure-rest-api-specs/blob/main/specification/databricks/resource-manager/Microsoft.Databricks/preview/2021-04-01-preview/databricks.json.

The important features are:
* `PublicNetworkAccess` and `requiredNSGRules` of workspace should be exposed.

**Comment by dingmeng-xue** [comment]
Working on it and waiting feedback from service

**Comment by LucasYao93** [comment]
close
