### ISSUE TITLE
New-AzRoleAssignment should use suitable Graph API according to user's input

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#16054]
Copy the discussion from https://github.com/Azure/azure-powershell/issues/13573#issuecomment-788183419

For `New-AzRoleAssignment`: Some folks won't be able to easily get `Graph.Read.All` for their SPN, and may only have `Graph.Read.User` and the ability to perform role assignments in a limited context. For them, the issue is `ToPSRoleAssignments` -> `POST getObjectsByObjectId` (even for a single object) -> `403`. 

I think the function is written on the assumption that anyone who writes can also LIST, but we're a GET-only SPN that only has user access administrator on an Azure resource group. 

https://github.com/Azure/azure-powershell/blob/63193bf2bdb03ae30a175570fce0095864ddb093/src/Resources/Resources/ActiveDirectory/Models/ActiveDirectoryClient.cs#L280

The assignment still succeeds, though: ToPSRoleAssignments is just a presentation function that occurs after the role assignment.
At some point down the chain, the 403 status of the graph REST request CloudException is swallowed and you get back the blank CloudException.

Workaround, though not ideal: swallow the cloudexception from New-AzRoleAssignment yourself and find a permissioned, or out of band, way to trust, but verify the result.

**Comment by isra-fel** [comment]
@BethanyZhou Hi Beisi, please also consider this issue when verifying Az.Resources. Thanks

**Comment by jikuja** [comment]
Was the fix for role assignments only or for all cmdlet doing unneeded AAD/Graph API request?

ref: https://github.com/Azure/azure-powershell/issues/16231

**Comment by BethanyZhou** [comment]
Hi @jikuja , the fix is for role assignments only. Could you provide full debug log for #16231 by setting `$DebugPreference = "Continue"`?

**Comment by jikuja** [comment]
updated #16231
