### ISSUE TITLE
Workaround of Adding permission of AAD Graph API

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#16067]
Following the announcement of the [Azure Active Directory Graph retirement](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363), users cannot add permissions of AAD Graph API to AD application via Azure Portal [Tweeter](https://twitter.com/Microsoft365Dev/status/1432810426442649603?s=20).

![image](https://user-images.githubusercontent.com/56333063/136923749-c8254a6c-b747-4f54-97d0-5e51714ae06e.png)

For the time being, use the [AzureAD](https://www.powershellgallery.com/packages/AzureAD/) module as workaround to add permission.  Below is the example of adding “User.Read” of AAD Graph API.
```
$AppObjectID = "..." # object id in AD
$app = Get-AzureADApplication -ObjectId $AppObjectID
$AADAccess = $app.RequiredResourceAccess | Where-Object {$_.ResourceAppId -eq "00000002-0000-0000-c000-000000000000"}  # "00000002-0000-0000-c000-000000000000" represents AAD Graph API
if($AADAccess -eq $null) {
  $AADAccess = New-Object Microsoft.Open.AzureAD.Model.RequiredResourceAccess
  $AADAccess.ResourceAppId = "00000002-0000-0000-c000-000000000000"
  $Access = New-Object Microsoft.Open.AzureAD.Model.ResourceAccess
  $Access.Type = "Scope"
  $Access.Id = "311a71cc-e848-46a1-bdf8-97ff7156d8e6" # Permission ID referring below table.
  $AADAccess.ResourceAccess = @()
  $AADAccess.ResourceAccess.Add($Access)
  $app.RequiredResourceAccess.Add($AADAccess)
} else {
  $Access = New-Object Microsoft.Open.AzureAD.Model.ResourceAccess
  $Access.Type = "Scope"
  $Access.Id = "311a71cc-e848-46a1-bdf8-97ff7156d8e6"
  $AADAccess.ResourceAccess.Add($Access)
}
Set-AzureADApplication -ObjectId $AppObjectID -RequiredResourceAccess $app.RequiredResourceAccess
```
We found 3 limitations which need your attention
1. AzureAD module only can work on .Net framework. User has to do this configuration via Windows PowerShell.
2. Azure Portal has a cache issue. User only can see this change on Portal after refreshing whole page instead of clicking refresh button
3. Some Permissions (such as Group.Read.All) needs admin consent. User has to grant admin consent via Portal. 

Below is the mapping of permission name and its ID.
Permission Name | ID
-- | --
Directory.AccessAsUser.All | a42657d6-7f20-40e3-b6f0-cee03008a62a
Directory.Read.All | 5778995a-e1bf-45b8-affa-663a9f3f4d04
Directory.ReadWrite.All | 78c8a3c8-a07e-4b9e-af1b-b5ccab50a175
Group.Read.All | 6234d376-f627-4f0f-90e0-dff25c5211a3
Group.ReadWrite.All | 970d6fa6-214a-4a9b-8513-08fad511e2fd
Member.Read.Hidden | 2d05a661-f651-4d57-a595-489c91eda336
Policy.Read.All | 80e5b1bf-3ad0-4365-943a-0ec983009b67
User.Read | 311a71cc-e848-46a1-bdf8-97ff7156d8e6
User.Read.All | c582532d-9d9e-43bd-a97c-2667a28ce295
User.ReadBasic.All | cba73afc-7f69-4d86-8450-4978e04ecd1a

We will keep this issue open till Azure PowerShell migrates to MSGraph. Please stay tuned and raise your question if any.

**Comment by stvpwrs** [comment]
I am facing the same issue, however the Permission IDs do not work in my tenant. Is there a way to find these IDs? I can only add Directory.ReadWrite.All. Is there PowerShell or someway to find these IDs?

**Comment by dingmeng-xue** [comment]
Those IDs should be the same. Please share the error message when you set permission id.

**Comment by stvpwrs** [comment]
@dingmeng-xue thanks for the fast response. So the following code will add a permission, but there is no description, it's listed as a GUID and then when trying to grant permissions I get the following error:

`az ad app permission add --id <AppId> --api 00000002-0000-0000-c000-000000000000 --api-permissions c582532d-9d9e-43bd-a97c-2667a28ce295=Role`

`Grant consent failed with error: Claim is invalid: c582532d-9d9e-43bd-a97c-2667a28ce295 does not exist on resource application 00000002-0000-0000-c000-000000000000.`

**Comment by dingmeng-xue** [comment]
Please follow this page https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest#az_ad_app_permission_add . Normally you need to add delegated permission, the type value in api-permissions should be Scope instead of Role.

If it is specific to Azure CLI, please raise the question to Azure CLI project. 

Another reason is you have no permission to grant consent.

**Comment by stvpwrs** [comment]
Doesn't Using delegated permissions cause an issue with running the PowerShell as an app though?

**Comment by stvpwrs** [comment]
So as a quick follow-up to this, not using the application permissions causes an error when using a certificate. 

`Message: Resource '1608649b-20e0-4859-bf6f-561771e91071' does not exist or one of its queried reference-property objects are not present.`

It seems there needs to be different GUIDs for the app permissions needed for this.

**Comment by manimerz** [comment]
Hi, we have the following issue:
DevOps Pipelines are deploying our artefact via Azure Powershell. The connection is provided by the Azure Resource Manager. 
Since the disabling of AAD Graph API Permissions we have issues with the deployment process, we added the permissions manually according to the instructions, however the issue persists, all releases fail either because of insufficient permissions or CloudException (That was not the case before)

Could the issue be that we are setting delegeted Permissions and we need to apply application permissions?

Thank you for your help.

**Comment by dingmeng-xue** [comment]
Hi @manimerz , I cannot get the detail steps about "connection provided by ARM". Since it is related to permission, could you share more information by email? You can find my email on my profile.

**Comment by dingmeng-xue** [comment]
Hi @manimerz , we are closing this issue because we have migrated to MS graph. Do you still have the problem? Welcome to contact us and raise the issue with information.
