### ISSUE TITLE
Get-AzStorageShare ignores Fileshares with AccountKind "StorageV2 (general purpose v2)"

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#16095]
When running `Get-AzStorageShare` against an Account Kind `StorageV2 (general purpose v2)` Storage-Account - which can contain a Fileshare, it will return nothing.

The cmdlet works only against Storage-Accounts with Account Kind `FileStorage`

Bug or Feature?

**Updating to Module Version 3.12 solved this issue!  - PLEASE CLOSE THIS ISSUE!**

**Comment by blueww** [comment]
Close this issue ad @Gill-Bates 's comments.
