### ISSUE TITLE
Invoke-AzAksRunCommand

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-powershell#16104]
## Description of the new feature

Expose new AKS run command ([see rest docs](https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/run-command)) functionality via PowerShell. Already existing in [Az cli](https://docs.microsoft.com/en-us/cli/azure/aks/command?view=azure-cli-latest)

It would also be nice to have the Get-AzAksRunCommandResult cmdlet to wrap that [corresponding api](https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/get-command-result)

**Comment by dingmeng-xue** [comment]
Thanks. We will prioritize this work.
