### ISSUE TITLE
Since upgrade to AZ.Accounts module version 2.5.4. AZ cmdlets cannot be run within workflow scripts.

### ISSUE THREAD

**Issue by gokusupa** [Azure/azure-powershell#16109]
When nesting AZ cmdlets within PS workflows, this error is returned. 

"Failed to create a 'Settings' from the text 'Assembly references and imported namespaces serialized as XML namespaces'."

This issue does not happen with version 2.5.3 of the AZ.Accounts Module.

Unfortunately when we try to downgrade to 2.5.3, this causes issues with other modules like the AZ.Storage module preventing cmdlets from running on from that module. The only fix to the storage module is to re-install the module, which then places Az.Accounts 2.5.4 on the VM leading me back to my original issue.

See issue example below
![image](https://user-images.githubusercontent.com/26933360/137601917-e1cfd40c-5ec0-4d73-b611-0a93772a9639.png)

**Comment by dingmeng-xue** [comment]
Thanks for reporting. The issue can be reproduced. I suspect this issue is related to https://github.com/Azure/azure-powershell/issues/15841. We will look into it.

**Comment by dingmeng-xue** [comment]
@gokusupa , is the issue still there? I cannot reproduce this issue. I tried Az.Accounts 2.5.3 and Az.Resources 4.3.0. Could you share detailed information and what module has installed on your machine?

**Comment by gokusupa** [comment]
We have retired the use of workflows as a result of this sudden change.
