### ISSUE TITLE
New-AzResourceGroupDeployment- Cannot retrieve the dynamic parameters for the cmdlet. Illegal characters in path

### ISSUE THREAD

**Issue by emmily** [Azure/azure-powershell#16119]
## Description

New-AzResourceGroupDeployment failed with error "Cannot retrieve the dynamic parameters for the cmdlet. Illegal characters in path" while using -WhatIf parameter. It works fine without -whatif.

I suspect it is related to https://github.com/Azure/azure-powershell/issues/15841

## Steps to reproduce
```
New-AzResourceGroupDeployment `
  -Whatif `
  -Name $deploymentName `
  -ResourceGroupName $resourceGroupName `
  -TemplateFile $template`
  -parameterName $paramValue `
  -verbose
```
## Environment data
PSVersion                      5.1.14393.4402
PSEdition                      Desktop

## Module versions

Az.Accounts (2.5.4) + Az.Resources (4.4.0)

## Error output
New-AzResourceGroupDeployment : Cannot retrieve the dynamic parameters for the cmdlet. Illegal characters in path.

**Comment by emmily** [comment]
@dingmeng-xue Can you help clarify if it is related to https://github.com/Azure/azure-powershell/issues/15841

**Comment by dingmeng-xue** [comment]
Thanks. Space character should not be mandatory. I rely on module owner to look into it.

**Comment by navba-MSFT** [comment]
@emmily Apologies for the late reply. This issue is open for quite sometime. Could you please let us know if you still need any assistance on this issue ? Awaiting your reply.

**Comment by xavigray** [comment]
I found the similar issue with my lab for az104, following this step-by-step.
[](https://microsoftlearning.github.io/AZ-104-MicrosoftAzureAdministrator/Instructions/Labs/LAB_10-Implement_Data_Protection.html)

PS /home/xavi> New-AzResourceGroupDeployment -ResourceGroupName $rgName -TemplateFile $HOME/az104-10-vms-edge-template.json -TemplateParameterFile $HOME/az104-10-vms-edge-parameters.json -verbose
DEBUG: 10:27:52 AM - NewAzureResourceGroupDeploymentCmdlet begin processing with ParameterSet 'ByTemplateFileAndParameterFile'.
DEBUG: 10:27:52 AM - using account id 'MSI@50342'...
DEBUG: 10:27:52 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
VERBOSE: Performing the operation "Creating Deployment" on target "az104-10-rg0".
DEBUG: 10:27:52 AM - [ConfigManager] Got nothing from [DisableErrorRecordsPersistence], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 10:27:52 AM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
New-AzResourceGroupDeployment: Value cannot be null. (Parameter 'dictionary')
DEBUG: 10:27:52 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 10:27:52 AM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 10:27:52 AM - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: AzureQoSEvent:  Module: Az.Resources:6.10.0; CommandName: New-AzResourceGroupDeployment; PSVersion: 7.3.6; IsSuccess: False; Duration: 00:00:00.0247941; Exception: Value cannot be null. (Parameter 'dictionary');
DEBUG: 10:27:52 AM - NewAzureResourceGroupDeploymentCmdlet end processing.
