### ISSUE TITLE
New-AzBotService command is not working

### ISSUE THREAD

**Issue by srinutamada** [Azure/azure-powershell#16131]
I am trying to create Azure bot service using below PowerShell and its failing with below error. Please help, how to proceed

$Securekey = ConvertTo-SecureString "<key value>" -AsPlainText -Force
New-AzBotService -ResourceGroupName <rg name> -Name <bot name> -ApplicationId <bot id> -Location northeurope -Sku S1 -Description <bot description> -Webapp -ApplicationSecret $Securekey

![image](https://user-images.githubusercontent.com/18491094/138028763-9a46e93d-1adc-4d62-bdc9-10a3852fe69a.png)

**Comment by dingmeng-xue** [comment]
Thanks for reporting. @srinutamada .

That issue is because the version of ConvertFrom-SecureString. We will address this issue. For the time being, could you use PowerShell 7 which supports `-AsPlainText` switch.

**Comment by srinutamada** [comment]
Thanks for response, I am able to create bot instance. Can you improvise existing commands to accept key vault name as one of the parameter? Why because from UI, Microsoft is creating one key vault when we are creating new bot resource and there is no option to choose existing key vaults. 

I don't have any other feedback. You can close this issue, if you can handle reported issue in later version.

**Comment by lijinpei2008** [comment]
We fixed this issue in the latest version, you can install the new version using this command:
Install-module-name az. botservice-requiredversion 0.3.2

You can see the difference between the source code on line 227 before and after the change at the following link:
https://www.powershellgallery.com/packages/Az.BotService/0.3.1/Content/custom%5CNew-AzBotService.ps1
https://www.powershellgallery.com/packages/Az.BotService/0.3.2/Content/custom%5CNew-AzBotService.ps1
