### ISSUE TITLE
Whatif is not working as expected when running New-AzNetworkInterface 

### ISSUE THREAD

**Issue by noureddineennacir** [Azure/azure-powershell#16183]
I am MSFT internal ARR IaaS TA. I was asked to open a Github issue to identify if this is a potential bug. 

Customer is creating a network interface without accelerated networking and manually enables accelerated networking using the Azure Portal. Then they run whatif to understand what the Azure PowerShell cmdlet is going to simulate. In the HTTP response, it clearly shows it will not make any change to the accelerated networking property because it shows True. They run the ARM template using PowerShell again that creates the VM and accelerated networking gets disabled.

Here is how I was able to simulate the same issue using Azure PowerShell with AZ modules:

1-	New-AzNetworkInterface -Location 'East US' -Name 'NetworkInterface1' -PrivateIpAddress '10.0.1.25' -ResourceGroupName 'East-RG' -SubnetId '/subscriptions/sub-id/resourceGroups/east-rg/providers/Microsoft.Network/virtualNetworks/east-us-vnet/Subnets/Windows-Subnet' 

Put Rest API response:

EnableIPForwarding          : False
EnableAcceleratedNetworking : False
NetworkSecurityGroup        : null
TapConfigurations           : []
Primary                     : 
MacAddress                  :  

2-	Enable accelerated networking using the Azure Portal. I know I could have just enabled accelerated networking in step 1 😊  

Get Rest API:

EnableIPForwarding          : False
EnableAcceleratedNetworking : True
NetworkSecurityGroup        : null
TapConfigurations           : []
Primary                     : 
MacAddress                  : 

3-	I run the following AZ PowerShell command:

New-AzNetworkInterface -Location 'East US' -Name 'NetworkInterface1' -PrivateIpAddress '10.0.1.25' -ResourceGroupName 'East-RG' -SubnetId '/subscriptions/sub-id/resourceGroups/east-rg/providers/Microsoft.Network/virtualNetworks/east-us-vnet/Subnets/Windows-Subnet' -whatif -debug

Rest API PUT response:

    "enableAcceleratedNetworking": true,
    "enableIPForwarding": false,
    "hostedWorkloads": [],
    "tapConfigurations": [],
    "nicType": "Standard" 

Get Rest API:

EnableIPForwarding          : False
EnableAcceleratedNetworking : True
NetworkSecurityGroup        : null
TapConfigurations           : []
Primary                     : 
MacAddress                  : 

As you can see above, the whatif did not make any change and the response body clearly shows the accelerated networking is set to True. Shouldn’t be set to false because the command is going to disable it without -whatif?  This is what the customer brought up to me
 

4-	If I remove -whatif from the following command. Accelerated networking gets disabled:

New-AzNetworkInterface -Location 'East US' -Name 'NetworkInterface1' -PrivateIpAddress '10.0.1.25' -ResourceGroupName 'East-RG' -SubnetId '/subscriptions/sub-id/resourceGroups/east-rg/providers/Microsoft.Network/virtualNetworks/east-us-vnet/Subnets/Windows-Subnet' -debug 

Put Rest API response body:

EnableIPForwarding          : False
EnableAcceleratedNetworking : False
NetworkSecurityGroup        : null
TapConfigurations           : []
Primary                     : 
MacAddress                  :  

Get Rest API request:
EnableIPForwarding          : False
EnableAcceleratedNetworking : False
NetworkSecurityGroup        : null
TapConfigurations           : []
Primary                     : 
MacAddress                  :  

My ask: Why in step 3 -whatif does not show me that it’s going to make a change to the accelerated networking property? The same applies when accelerated networking is disabled and running something like this with -whatif.

New-AzNetworkInterface -Location 'East US' -Name 'NetworkInterface1' -PrivateIpAddress '10.0.1.25' -ResourceGroupName 'East-RG' -SubnetId '/subscriptions/sub-id/resourceGroups/east-rg/providers/Microsoft.Network/virtualNetworks/east-us-vnet/Subnets/Windows-Subnet' -EnableAcceleratedNetworking -WhatIf -debug

     },
    "enableAcceleratedNetworking": false,
    "enableIPForwarding": false,
    "hostedWorkloads": [],
    "tapConfigurations": [],
    "nicType": "Standard" 

I already know why it updates the network resource in step 4 without -whatif. The Put request just updates the resource because I did not specify -enableacceleratednetworking. Need to understand the -whatif part and if it is by design or a bug.

**Comment by SaurabhSharma-MSFT** [comment]
@vnetsuppgithub Can you please look into this issue.

**Comment by dingmeng-xue** [comment]
Deployment cmdlet is especial case in Azure PowerShell. Other cmdlets with `-whatif` parameter only show message telling user what operation will be triggered. In the implementation of `New-AzNetworkInterface`, it checks whether resource is existing (GET METHOD) and shows message "What if: Performing the operation "Creating Resource" on target "networkinterface1".". It won't show what request will be sent to server. The technical reason is management SDK has no API to preview potentioal request. It's by design for the time being.

Please reference https://github.com/Azure/azure-powershell/blob/e1c4b71350caecbc9af4173e4076a8435307094d/src/Network/Network/NetworkInterface/NewAzureNetworkInterfaceCommand.cs#L254
