### ISSUE TITLE
Get-AzSqlServerFirewallRule firewallrulename wildcard filtering returns all IP rules

### ISSUE THREAD

**Issue by DavidAtImpactCubed** [Azure/azure-powershell#16199]
## Description
The docs suggest that you can filter firewall rules with a prefix and a wildcard:
https://docs.microsoft.com/en-us/powershell/module/az.sql/get-azsqlserverfirewallrule?view=azps-6.5.0#example-2--get-all-rules-for-a-server-using-filtering

When using this syntax, _all_ firewall rules are returned, even those that don't match the prefix.

## Steps to reproduce

```powershell
Get-AzSqlServerFirewallRule -ResourceGroupName "ResourceGroup01" -ServerName "Server01" -FirewallRuleName "Rule*"
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for bringing this to our attention. This has been fixed with the PR referenced above. We will now close this issue. If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
