### ISSUE TITLE
Error while registering new application in AD using Azure Powershell.

### ISSUE THREAD

**Issue by venkateshtarra** [Azure/azure-powershell#16230]
Hi Team,

I am trying to create FHIR server in Azure and registering API in AD using below command but it is giving error as highlighted. 
I have upgraded AZ module version to 6.5 but still getting this error. Can we solve this issue without creating subdomain under registered custom domain name as mentioned in this link.

https://github.com/Azure/azure-powershell/issues/16097#issue-1026897151

New-AzureADApplication -DisplayName $FhirServiceAudience -IdentifierUris $FhirServiceAudience -AppRoles $desiredAppRoles
    New-AzureAdServicePrincipal -AppId $apiAppReg.AppId | Out-Null

**Error:-**

"Error occurred while executing NewApplication  Code: Request_BadRequest Message: Values of identifierUris property must use a verified domain of the
     | organization or its subdomain: 'https://fhirpaas21.azurehealthcareapis.com' RequestId: 0ab2b655-a4cb-47bf-83b1-4a25a891eacb DateTimeStamp: Tue, 26 Oct
     | 2021 12:44:59 GMT Details: PropertyName  - identifierUris, PropertyErrorCode  - HostNameNotOnVerifiedDomain, HostName  -
     | https://fhirpaas21.azurehealthcareapis.com HttpStatusCode: BadRequest HttpStatusDescription: Bad Request HttpResponseStatus: Completed"

Thanks in advance
Venkatesh Tarra.

**Comment by isinghrana** [comment]
@venkateshtarra  Can you please share the link to the new issue you created?
