### ISSUE TITLE
The test cases of referred EventHub SDK services need be re-recorded

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/azure-powershell#16258]
## Description

Many services referred the SDK of EventHub. EventHub SDK was updated in https://github.com/Azure/azure-powershell/pull/15960. Its API version changes. So these services' test cases need be re-recorded.

To catch up 11/02 release, we skipped it temporarily. Need finish this job in the future.

**Comment by Saglodha** [comment]
@BethanyZhou, looks like @v-Ajnava could re-record test cases and submit them for approvals. Please feel free to reach out directly if in case you need additional information from Eventhubs side.
