### ISSUE TITLE
Deleting a VM does not delete its network resources and attached disks

### ISSUE THREAD

**Issue by Vijayaraghavanl** [Azure/azure-powershell#1626]
When resource manager VM's are deleted its network resources and attached disks do not get deleted automatically and are required to be deleted manually. Like to have an option that would allow us to choose to delete the attached disks and network resource.

**Comment by markcowl** [comment]
@Vijayaraghavanl Thanks for the suggestion.  Adding the service team folks to help take a look.  One mitigation would be to place these assets in a resource group, so that the resource group could be deleted.  This doesn't work for all scenarios, however.

**Comment by singhkay** [comment]
@Vijayaraghavanl I believe the ability to delete the attached disks is coming, not sure about the timelines. Not sure about the NICs. I'll forward the suggestion to the service owners. Also adding networking tag for networking team's visibility.

**Comment by DeepakRajendranMsft** [comment]
from a networkging prespective this is expected. The nics that were created on the VM can be reused by another VM (once the previous VM has been deleted)

**Comment by markjbrown** [comment]
Closing this issue as this has been answered and works as designed.

**Comment by clouditspace** [comment]
My script here in the following link can solve this
http://cloudcompute.info/delete-azure-vm-and-all-associated-resources-using-powershell-script/

Thanks,
Manu
