### ISSUE TITLE
The windows-2016 environment used by pipeline (at least smoke test)  is going to be deprecated and removed

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/azure-powershell#16275]
## Description
##[warning]The windows-2016 environment will be deprecated on November 15, 2021, and removed on March 15, 2022. Migrate to windows-latest instead. For more details see https://github.com/actions/virtual-environments/issues/4312

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1167885&view=logs&j=2f7369d1-fb97-5262-a571-f4e9c996b7d1

**Comment by isra-fel** [comment]
We are most likely to replace all `windows-2016` to `windows-2019` in our pipelines.

**Comment by isra-fel** [comment]
Tested pipeline builds:

- [ ] Az sign: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1188903&view=results
- [ ] Common sign:
