### ISSUE TITLE
New-AzureRMAppServicePlan : Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by meyergm** [Azure/azure-powershell#1629]
Receive Exception has been thrown by the target of an invocation while running the new-azurermappserviceplan to create a new app service. 

Running Azure powershell version 1.0.2.

**Comment by markcowl** [comment]
@meyergm Thanks for the report.  Adding in the service team for resolution.

**Comment by maddieclayton** [comment]
Closing. Please reopen this issue if it is still an issue in the most recent version.
