### ISSUE TITLE
Provide an interface to append az powershell sub-module version to the telemetry log

### ISSUE THREAD

**Issue by ericshape** [Azure/azure-powershell#16291]
## Description of the new feature

We would like to have an interface to append the additional Azure SQL PowerShell (sub-module) version to the telemetry log. 
i.e. Microsoft.Azure.Management.Sql.SqlManagementClient/1.56.0.0 PSVersion/v5.1.17763.2183 **AzurePowershell/v0.0.0** **az.sql/v3.5.0**

The expected format should be Az.{ModuleName}/{version}. there is a space character as a delimiter between **AzurePowershell/v0.0.0** and **az.sql/v3.5.0**.

Azure Compute might use hacking way to add it now
```
useragent of Get-AzVM.
User-Agent: FxVersion/6.0.21.25307 OSName/Windows OSVersion/Microsoft.Windows.10.0.19043 Microsoft.Azure.Management.Compute.ComputeManagementClient/49.1.0 AzurePowershell/v0.0.0 PSVersion/v7.2.0-preview.6

```
But we want a public interface to address this issue :)

**Comment by dingmeng-xue** [comment]
Below is an example for upcoming change

User-Agent: FxVersion/6.0.21.25307 OSName/Windows OSVersion/Microsoft.Windows.10.0.22000 Microsoft.Azure.Management.Sql.SqlManagementClient/1.56.0.0 **Az.Sql/3.5.1** PSVersion/v7.2.0-preview.6 AzurePowershell/v0.0.0
