### ISSUE TITLE
URL as Variable in CustomScriptforLinux

### ISSUE THREAD

**Issue by Vijayaraghavanl** [Azure/azure-powershell#1630]
Trying to use CustomScriptforLinux for ARM VM's and need to be able to define the fileUris as a Variable but unable to do so. 

See: https://github.com/Azure/azure-linux-extensions/tree/master/CustomScript

In section 2.2.2 Resource Manager

$PublicConf = '{
    "fileUris": ["<url>"],
    "commandToExecute": "<command>"
}'

I would like to be able to do something like this but keep running into syntax error:

$FileUris = "<URL>"

$PublicConf = '{
    "fileUris": ["$FileUris"],
    "commandToExecute": "<command>"
}'

**Comment by markcowl** [comment]
@Vijayaraghavanl This is not the appropriate repo for this question - please file this issue in https://github.com/Azure/azure-linux-extensions
