### ISSUE TITLE
Invoke-AzStorageSyncChangeDetection 

### ISSUE THREAD

**Issue by desmphil** [Azure/azure-powershell#16306]
## Description

When running the following script in Windows11 or W2022 or W2019 to trigger the manual detection job, the invoke expression mandatory request the **-directorypath**

- If the parameter is skipped the command failed.
- If the parameter is left blank (null) the sync job doesn't work.

```
DEBUG: AzureQoSEvent: Module: Az.StorageSync:1.6.1; CommandName: Invoke-AzStorag
eSyncChangeDetection; PSVersion: 5.1.20348.1; IsSuccess: True; Duration: 00:00:1
1.0089047
DEBUG: Finish sending metric.
DEBUG: 4:04:14 AM - InvokeChangeDetectionCommand end processing.

PS  #! Invoke-AzStorageSyncChangeDetection
Write-Output "Check for files and directories changes for $StorageSyncServiceName in $SyncGroupName"
Invoke-AzStorageSyncChangeDetection -ResourceGroupName $ResourceGroupName -StorageSyncServiceName $StorageSyncServiceName `
    -SyncGroupName $SyncGroupName -CloudEndpointName $azsync.CloudEndpointName -DirectoryPath $Path -Recursive
Check for files and directories changes for 
Invoke-AzStorageSyncChangeDetection : Cannot bind argument to parameter 
'DirectoryPath' because it is null.
```

On **Azure Automation Accounts**, the process runs just fine.

## Steps to reproduce

```
#install-module az
#install-module az.accounts
#install-module az.storage
#install-module az.storagesync

Connect-AzAccount

#SELECT SUBSCRIPTION
$AzureSubscription = (Get-AzSubscription | Out-GridView -Title "Choose your Azure subscription and click OK." -PassThru) 
Write-Output "Switching to Azure subscription: $($AzureSubscription.Name)" 
$AzureSubscriptionInfo = Select-AzSubscription -SubscriptionId $AzureSubscription.Id
Set-AzContext -Subscription $AzureSubscription.Id
$subscriptionId = $AzureSubscription.Id

#SELECT RESSOURCE GROUP
$AzureResourceGroup = (Get-AzResourceGroup | Out-GridView -Title "Choose your Azure ResourceGroup and click OK." -PassThru) 
Write-Output "Setting Azure Resource Group: $($AzureResourceGroup.Name)" 
$resourceGroupName = $AzureResourceGroup.ResourceGroupName

#SELECT RESSOURCE GROUP
$StorageSyncServiceName = (Get-AzStorageSyncService -ResourceGroupName $resourceGroupName | Out-GridView -Title "Choose your Azure ResourceGroup and click OK." -PassThru) 
$StorageSyncServiceName = $StorageSyncServiceName.StorageSyncServiceName

#SELECT RESSOURCE GROUP
$AzStorageSyncGroup = (Get-AzStorageSyncGroup -ResourceGroupName $resourceGroupName -StorageSyncServiceName $StorageSyncServiceName | Out-GridView -Title "Choose your Azure ResourceGroup and click OK." -PassThru) 
$SyncGroupName = $AzStorageSyncGroup.SyncGroupName

#! Get Cloud Endpoint Name
$azsync = Get-AzStorageSyncCloudEndpoint -ResourceGroupName "$ResourceGroupName" -StorageSyncServiceName $StorageSyncServiceName `
    -SyncGroupName "$SyncGroupName"
Write-Output "Get Azure StorageSync Cloud Endpoint Name: $($azsync.CloudEndpointName)"


#! Invoke-AzStorageSyncChangeDetection
Write-Output "Check for files and directories changes for $StorageSyncServiceName in $SyncGroupName"
Invoke-AzStorageSyncChangeDetection -ResourceGroupName $ResourceGroupName -StorageSyncServiceName $StorageSyncServiceName `
    -SyncGroupName $SyncGroupName -CloudEndpointName $azsync.CloudEndpointName -DirectoryPath $Path -Recursive
```

## Environment data

Name                           Value                                                            
----                           -----                                                            
PSVersion                      5.1.17763.1007                                                   
PSEdition                      Desktop                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                          
BuildVersion                   10.0.17763.1007                                                  
CLRVersion                     4.0.30319.42000                                                  
WSManStackVersion              3.0                                                              
PSRemotingProtocolVersion      2.3                                                              
SerializationVersion           1.1.0.1      

```

```

## Module versions
```
ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Script     2.6.0      Az.Accounts                         {Add-AzEnvironment...
Script     4.4.0      Az.Resources                        {Add-AzADGroupMemb...
Script     3.12.0     az.storage                          {Add-AzRmStorageCo...
Script     1.6.1      Az.StorageSync                      {Get-AzStorageSync...
Script     1.0.0.0    ISE                                 {Get-IseSnippet, I...

```
## Debug output

```

```

## Error output

```
Invoke-AzStorageSyncChangeDetection : Cannot bind argument to parameter 'DirectoryPath' because 
it is null.
At line:24 char:95
+ ... udEndpointName $azsync.CloudEndpointName -DirectoryPath $Path -Recurs ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-AzStorageSyncChangeDetection], Parameter 
   BindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Azure.Co 
   mmands.StorageSync.CloudEndpoint.InvokeChangeDetectionCommand
```

**Comment by dingmeng-xue** [comment]
Thank you for your reporting. Tagging and routing to the team member best able to assist.

**Comment by ParthPurani** [comment]
Seems like DirectoryPath is a mendatory parameter. According to documentation I want to invoke share-level changes which is not working while this parameter is passed.

`Invoke-AzStorageSyncChangeDetection -ResourceId $storageSync.ResourceId`
_Invoke-AzStorageSyncChangeDetection: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided._

This works when `DirectoryPath` is passed.

**Comment by redelf11** [comment]
Agree this is annoying as the documentation suggests you can use this without this parameter to force sync the whole share, which you can't currently

**Comment by dannyger97** [comment]
I have the same issue. PowerShell 5.1 and 7.2. Is there a fix for this coming soon?
The -Path and -DirectoryPath also don't provide any feedback and in the portal the job only runs every 24 hours.

@dingmeng-xue @SaurabhSharma-MSFT

**Comment by dingmeng-xue** [comment]
Hi @dannyger97 , @geolivo 's team is working on it.

**Comment by geolivo** [comment]
The bug was that the full-share parameter set was mistakenly not marked as the default. Thus an attempt to run it would still prompt the user enter a directoryPath or Path. The fix will be in the next PS release, and in the meantime the following are also viable ways to invoke full-share detection:

Import-Module Az.StorageSync
Connect-AzAccount -Subscription "<customer's subscription ID>"

# Customer needs to get the cloud endpoint resource first
$cloudEndpoint = Get-AzStorageSyncCloudEndpoint -ResourceGroupName "<resource group name>" -StorageSyncServiceName "<storage sync service name>" -SyncGroupName "<sync group name>" -Name "<cloud endpoint name>"

# Then, call cmdlet using ResourceId input:
Invoke-AzStorageSyncChangeDetection -ResourceId $cloudEndpoint.ResourceId

# or, call cmdlet using InputObject:
Invoke-AzStorageSyncChangeDetection -InputObject $cloudEndpoint
