### ISSUE TITLE
Set-AzureServiceDiagnosticsExtension fails if role name is too long with invalid extension id.

### ISSUE THREAD

**Issue by thebothead** [Azure/azure-powershell#1632]
PS C:\WINDOWS\system32> D:\Sandbox\DevOps\Diagnostics\EnableDiagnostics.ps1
cmdlet EnableDiagnostics.ps1 at command pipeline position 1
Supply values for the following parameters:
subscription: OI Platform Development
service: oip-datahub-dev-devhub
slot: Production
storage: oipdatahubdevdiagnostics
config: D:\Sandbox\OI-Platform\DFL\src\SE.OIP.DataHub\SE.OIP.DataHub.Host.Cloud5k\bin\Release\app.publish\Extensions\PaaSDiagnostics.SE.OIP.DataHub.Host.EventHub.DataLayer.PubConfig.xml
role: SE.OIP.DataHub.Host.EventHub.DataLayer
Set-AzureServiceDiagnosticsExtension : BadRequest: The extension ID SEOIPDataHubHostEventHubDataLayer-PaaSDiagnostics-Production-Ext-0 is invalid.
At D:\Sandbox\DevOps\Diagnostics\EnableDiagnostics.ps1:25 char:1
+ Set-AzureServiceDiagnosticsExtension -StorageContext $storageContext  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzureServiceDiagnosticsExtension], CloudException
    + FullyQualifiedErrorId : Hyak.Common.CloudException,Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.SetAzureServiceDiagnosticsExtensionCommand

**Comment by markcowl** [comment]
@thebothead Thanks for the report.  Adding in the service team for resolution

**Comment by thebothead** [comment]
Thanks. I installed the latest Azure PS 1.1.0 from:

https://azure.microsoft.com/en-us/documentation/articles/powershell-install-configure/

This fixed my issue.  I can see that the extension name is now being truncated when it is too long.

**Comment by singhkay** [comment]
@thebothead Thanks for the update. I'm going to close this issue but there is another issue re: same cmdlet if you run into that issue with this cmdlet. 

https://github.com/Azure/azure-powershell/issues/387
