### ISSUE TITLE
Set-AzWebApp: Expose HealthCheckPath SiteConfig

### ISSUE THREAD

**Issue by DrorOzgaon** [Azure/azure-powershell#16325]
## Description of the new feature
The current Set-AzWebApp does not expose the SiteConfig "HealthCheckPath" parameter. We want to automate setting the "HealthCheckPath".

Note: there is a bug open because the "HealthCheckPath" remains null in the SiteConfig despite having a value:
https://github.com/Azure/azure-powershell/issues/14624

## Proposed implementation details (optional)

**Comment by dingmeng-xue** [comment]
Thank you for your reporting. Tagging and routing to the team member best able to assist.

**Comment by Kotasudhakarreddy** [comment]
Closing as duplicate of #14624. We will give the fix in next release **Mar 2022**
