### ISSUE TITLE
Release notes incorrectly reference "Azure Websites"

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1633]
@hovsepm @devigned 

The "Azure Websites" feature was rebranded as "Åzure App Service" on March 24th, 2015. The release notes for the v1.1.0 module on January 10th, 2016 still reference "Azure Websites."

The consistent inconsistency in branding is going to confuse customers.

http://weblogs.asp.net/scottgu/announcing-the-new-azure-app-service

<img width="1028" alt="screen shot 2016-01-12 at 3 30 21 pm" src="https://cloud.githubusercontent.com/assets/466713/12279062/1d3d7480-b942-11e5-9811-010c05b372f0.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 Thanks for the report.  Adding in the app service team (pay no attention to the label :-) to comment

**Comment by cormacpayne** [comment]
@twitchax assigning to you to discuss whether we should change `AzureRM.Websites` to `AzureRM.AppService` before the next breaking change release

**Comment by twitchax** [comment]
Yes, we definitely should.

**Comment by panchagnula** [comment]
Sorry this was confusing, this was a brand change for our service we will be cognizant not making such brand changes in the future & we even if we do we will have proper documentation supporting & explaining this.
