### ISSUE TITLE
Connect-AzAccount using service principal times out on version 2.6.1, but works on 1.9.5

### ISSUE THREAD

**Issue by MonikaReddy-MSFT** [Azure/azure-powershell#16333]
Customer has raised an issues in Microsoft Q&A https://docs.microsoft.com/en-us/answers/questions/614480/index.html 

and below is the issue they are facing : 

Hi All,

I will try to keep it simple, been trying to figure this out for days. Migrating a CI/CD pipeline to a new runner on a new server. Install Azure PowerShell (all worked before on AzureRM) Any suggestions are appreciated!

@{Name=Connect-AzAccount; Version=2.6.1}

Connect-azAccount -ServicePrincipal -Environment $xxx -Tenant $xxx -Credential $CREDENTIAL -Subscription $xxxx

Command fails with PSVersion 7.1.4 and 5.1.17763.2183

@{Name=Connect-AzAccount; Version=1.9.5}

Connect-azAccount -ServicePrincipal -Environment $xxx -Tenant $xxx -Credential $CREDENTIAL -Subscription $xxxx

Command succeeds on PSVersion 5.1.17763.2183 but fails on PSVersion 7.1.4 (Probably because it doesn't support that version)

Some sample output from the -debug:

DEBUG: Sought all Az modules and got latest version 6.6.0
DEBUG: 10:36:19 AM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'ServicePrincipalWithSubscriptionId'.
DEBUG: 10:36:19 AM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 10:36:19 AM - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 10:36:19 AM - Using Autosave scope 'CurrentUser'
DEBUG: 10:36:19 AM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 10:36:19 AM - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 10:36:19 AM - Using Autosave scope 'CurrentUser'
WARNING: The provided service principal secret will be included in the 'AzureRmContext.json' file found in the user profile ( xxxxxxxxxxx ). Please ensure that this directory has appropriate protections.
DEBUG: 10:36:19 AM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 10:36:19 AM - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 10:36:19 AM - Using Autosave scope 'CurrentUser'
DEBUG: 10:36:19 AM - [ServicePrincipalAuthenticator] Calling ClientSecretCredential.GetTokenAsync - ApplicationId:'-----redacted------', TenantId:'---------redacted-------', Scopes:'https://management.core.usgovcloudapi.net//.default', AuthorityHost:'https://login.microsoftonline.us/'
DEBUG: ClientSecretCredential.GetToken invoked. Scopes: [ https://management.core.usgovcloudapi.net//.default ] ParentRequestId:
DEBUG: Request [---------redacted-------] GET https://login.microsoftonline.us/common/discovery/instance?api-version=REDACTED&authorization_endpoint=REDACTED
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:---------redacted-------
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0,(.NET 5.0.9; Microsoft Windows 10.0.17763)
client assembly: Azure.Identity
DEBUG: Request [---------redacted-------] exception Azure.RequestFailedException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (login.microsoftonline.us:443)
---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (login.microsoftonline.us:443)
---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.<ConnectAsync>g_WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
--- End of inner exception stack trace ---
at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
DEBUG: Request [f28fcf70-fcb3-4aa1-af17-8af3af52bf4f] retry number 1 took 84.2s
DEBUG: Request [f28fcf70-fcb3-4aa1-af17-8af3af52bf4f] GET https://login.microsoftonline.us/common/discovery/instance?api-version=REDACTED&authorization_endpoint=REDACTED
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:---------redacted-------
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0,(.NET 5.0.9; Microsoft Windows 10.0.17763)
client assembly: Azure.Identity
DEBUG: Request [---------redacted-------] exception System.Threading.Tasks.TaskCanceledException: The operation was canceled.
at Azure.Core.CancellationHelper.ThrowOperationCanceledException(Exception innerException, CancellationToken cancellationToken)
at Azure.Core.CancellationHelper.ThrowIfCancellationRequested(CancellationToken cancellationToken)
at Azure.Core.Pipeline.ResponseBodyPolicy.ThrowIfCancellationRequestedOrTimeout(CancellationToken originalToken, CancellationToken timeoutToken, Exception inner, TimeSpan timeout)
at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
DEBUG: ClientSecretCredential.GetToken was unable to retrieve an access token. Scopes: [ https://management.core.usgovcloudapi.net//.default ] ParentRequestId: Exception: Azure.Identity.AuthenticationFailedException (0x80131500): ClientSecretCredential authentication failed: Retry failed after 2 tries. Retry settings can be adjusted in ClientOptions.Retry. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (login.microsoftonline.us:443)) (The operation was canceled.)
---> System.AggregateException (0x80131500): Retry failed after 2 tries. Retry settings can be adjusted in ClientOptions.Retry. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (login.microsoftonline.us:443)) (The operation was canceled.)
---> Azure.RequestFailedException (0x80131500): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (login.microsoftonline.us:443)
---> System.Net.Http.HttpRequestException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (login.microsoftonline.us:443)
---> System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
DEBUG: Azure.Identity.AuthenticationFailedException: ClientSecretCredential authentication failed: Retry failed after 2 tries. Retry settings can be adjusted in ClientOptions.Retry. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (login.microsoftonline.us:443)) (The operation was canceled.)
---> System.AggregateException: Retry failed after 2 tries. Retry settings can be adjusted in ClientOptions.Retry. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (login.microsoftonline.us:443)) (The operation was canceled.)
---> Azure.RequestFailedException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (login.microsoftonline.us:443)
---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (login.microsoftonline.us:443)
---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.<ConnectAsync>g_WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
--- End of inner exception stack trace ---

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Az.Accounts 1.9.5 was using ADAL which will be deprecated soon. According to the error from the latest Az.Accounts, it seems the network cannot be established correctly. Is there proxy on machine? Please reference https://docs.microsoft.com/en-us/powershell/azure/az-powershell-proxy?view=azps-6.6.0 to check proxy setting.

**Comment by JCW-USDA** [comment]
Yes, there is a proxy.  Yes, I created those environment variables but no luck.  For the 1.9.5 module that works, the proxy is configured in code.  With the latest version, I get the time out.   If I call out az.accounts -required version 1.9.5 all works.  Be mindful that this is the only change to the pipeline/script.  This makes me think the Microsoft.Azure.PowerShell.Cmdlets.Accounts.dll of the new version is missing a call to check for a proxy.  This is just a wild guess. 

Code for Proxy: 
If ($PSVersionTable.psversion.major -ge 7) {
    Write-host "Using Powershell Version 7 Proxy.  Proxy Server:$HTTP_PROXY"
    [System.Net.Http.HttpClient]::DefaultProxy = New-Object System.Net.WebProxy($HTTP_PROXY)
}
Else {
    Write-host "Using Powershell Version 5 Proxy.  Proxy Server:$HTTP_PROXY"
    [System.Net.WebRequest]::DefaultWebProxy = New-Object System.Net.WebProxy ($HTTP_PROXY, $true)
}

**Comment by dingmeng-xue** [comment]
Please try to update proxy setting following our doc. It's due to our dependencies which cannot be controlled by Azure PowerShell layer.

**Comment by JCW-USDA** [comment]
Hi - tried again - here are the results


PS 7 with No code to call proxy / added  2 ENV sys variables - HTTP_PROXY http://server:port & HTTPS_PROXY http://server:port  
  netsh winhttp show proxy command shows correct proxy server as server:port 
  ClientSecretCredential authentication failed: Retry failed after 2 tries. Retry settings can be
       | adjusted in ClientOptions.Retry. (A connection attempt failed because the connected party did not
       | properly respond after a period of time, or established connection failed because connected host has
       | failed to respond. (login.microsoftonline.us:443))

PS 5 with No code to call proxy / added  2 ENV sys variables - HTTP_PROXY http://server:port & HTTPS_PROXY http://server:port  
  netsh winhttp show proxy command shows correct proxy server as server:port 
  ClientSecretCredential authentication failed: Retry failed after 2 tries. Retry settings can be
       | adjusted in ClientOptions.Retry. (A connection attempt failed because the connected party did not
       | properly respond after a period of time, or established connection failed because connected host has
       | failed to respond. (login.microsoftonline.us:443))

**Comment by JCW-USDA** [comment]
Can we put the label needs triage back?

**Comment by dingmeng-xue** [comment]
Hi JCW-USDA, triage label means owner team is not clear. Currently, this issue doesn't belong to any service team. It's just usage question. 

Does "No code to call proxy" mean proxy server doesn't receive any request?

**Comment by JCW-USDA** [comment]
Thanks for clearing up the definition of triage.   No code means I followed your suggestion.  I am not calling the proxy in code, but am doing it with an ENV system variable as reported. I get the same.  If I run netsh winhttp show proxy, the output is correct.  If I make the script use az.account 1.9.5 there are no time outs and I can get to the tenant successfully.  Leads me to believe I do not have connectivity issues.  Any other ideas? Thanks

**Comment by JCW-USDA** [comment]
Also, can you further explain: "Az.Accounts 1.9.5 was using ADAL which will be deprecated soon"  - Is the service principal related to this?  Are there any specific requirements for > 1.9.5 in regards to app service principal? I am having trouble finding a good resource on that. 
Thank you,

**Comment by JCW-USDA** [comment]
Could there be issues since this is gov environment?

**Comment by JCW-USDA** [comment]
Solved the issue - the GitLab runner process was not calling the proxy, even though the ENV variable and scripting was setting it and working in the older module.  This certainly put me in another direction when working with older module.  Sorry for the mix up.  Please close

**Comment by dingmeng-xue** [comment]
Thanks for the information. It's really hard when handling multiple products and components. I'm closing this issue. Please contact us if you need further assistant.
