### ISSUE TITLE
get-azalertrule not showing all Alert Rules

### ISSUE THREAD

**Issue by Paxilein** [Azure/azure-powershell#16356]
### Description

I'd expect to get all alert Rules of the subscription when running get-azalertrule without any parameters like the Get-AzMetricAlertRuleV2 does...

Or it should at least show some useful information instead of this default error... Like which parameters are mandatory etc.

### Issue script & Debug output

```PowerShell
PS> Get-AzAlertRule
Get-AzAlertRule: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.6.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     2.7.0                 Az.Monitor                          {Add-AzAutoscaleSetting, Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzMetricAlertRuleV2…}
Script     4.4.0                 Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzADAppCredential…}
```

### Error output

```PowerShell
N/A
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. It should be due to missing default parameter set when this cmdlet has multiple parameter sets.

https://github.com/Azure/azure-powershell/blob/40b58bc55a742d2fa92ca2020cbc3ef54428f043/src/Monitor/Monitor/Alerts/GetAzureRmAlertRuleCommand.cs#L29

**Comment by vidai-msft** [comment]
@Paxilein the maximum scope of the command Get-AzAlertRule is at resource group level. So you need to provide at least the resource group name. PR has been raised to prompt for input instead of throwing the exception. You can try it out after rolled out in the next release. Thanks!
