### ISSUE TITLE
Can you add the alert when removing a NIC from VM which has single NIC?

### ISSUE THREAD

**Issue by khiraha** [Azure/azure-powershell#1636]
According to the documentation, IaaS v2 needs to 1 NIC at least. 

https://msdn.microsoft.com/en-us/library/azure/mt163579.aspx

> "..Each VM has at least 1 network interface card..."

When we use the following commands, they finishes without error and the update succeeds apparently. 

> $vmname = "VMName" # this vm has single NIC
> $resource_group = "ResourceGroupName"
> $nicname = "NICName"
> 
> $vm = Get-AzureRmVm -Name $vmname -ResourceGroupName $resource_group
> $vm | Stop-AzureRmVM -Force
> 
> $nic1 = Get-AzureRmNetworkInterface -Name $nicname -ResourceGroupName $resource_group
> $vm = $vm | Remove-AzureRmVMNetworkInterface -NetworkInterfaceIDs $nic1.Id
> 
> $vm | Update-AzureRmVm -ResourceGroupName $resource_group

But a NIC won't be removed. I got feedback from the customer that it should provide any alert when removing a NIC from the envrironment which has single NIC. 

Can you add some alerts in **Remove-AzureRmVMNetworkInterface** or **Update-AzureRmVm** when removing single NIC?

**Comment by singhkay** [comment]
@khiraha Yeah this is definitely a bug. Not sure if it's a PS bug or an API bug. I'll check with the team.

**Comment by cormacpayne** [comment]
@khiraha this has been fixed. The customer can use the `-WhatIf` and `-Confirm` parameters for additional alerts
