### ISSUE TITLE
Get-AzureRole doesn't  return current running Guest OS Version

### ISSUE THREAD

**Issue by takekazuomi** [Azure/azure-powershell#1637]
In current Azure Powershell Cmdlet no way to get current running Guest OS Version.

Get Deplyment REST API return it.
https://msdn.microsoft.com/en-us/library/ee460804.aspx

If Get-AzureRole result include information about current running Guest OS Version. Its useful.

**Comment by hovsepm** [comment]
merged to dev branch will be available in upcoming release.
