### ISSUE TITLE
Az.Storage on Windows 11

### ISSUE THREAD

**Issue by g7cnp** [Azure/azure-powershell#16375]
### Description

On machines running Windows 11 (22000) with Az.Storage 3.12.0 i'm getting an error importing the module.

This seems to be the import of Microsoft.Azure.PowerShell.Cmdlets.Storage.dll

### Issue script & Debug output

```PowerShell
[string]$Modulename = "Az.Storage"
Install-Module $Modulename -scope allusers -AllowClobber 
Import-Module $Modulename -Force
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.6.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Con... 
Script     3.12.0     Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountM...
```

### Error output

```PowerShell
Import-Module : Method 'GetTokenAsync' in type 
'Microsoft.WindowsAzure.Commands.Storage.Common.AzureSessionCredential' from assembly 
'Microsoft.Azure.PowerShell.Cmdlets.Storage, Version=3.12.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does 
not have an implementation.
At C:\Program Files\WindowsPowerShell\Modules\Az.Storage\3.12.0\Az.Storage.psm1:123 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We got couple similar issues. Current observation is one or some loaded assemblies from non-Azure PowerShell modules or environment have disturbed compatibility between the latest version of Azure.Core and old version of Azure.Identity on .NET framework. For instance, if Windows PowerShell imports System.Threading.Tasks.Extensions, Version=4.2.0.0 for some reasons, I hit the same error message.

If user just use Azure PowerShell modules, this issue cannot be reproduced. Below is my test.
```
PS C:\Dev> install-module az.storage -repository psgallery -force
PS C:\Dev> Import-Module Az.Storage -force
PS C:\Dev> Get-AzStorageAccount

StorageAccountName     ResourceGroupName                   PrimaryLocation SkuName        Kind        AccessTier CreationTime          ProvisioningState EnableHttpsT
                                                                                                                                                         rafficOnly
------------------     -----------------                   --------------- -------        ----        ---------- ------------          ----------------- ------------


PS C:\Dev> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by dingmeng-xue** [comment]
We are sharing an engineering build of **Az.Accounts 2.6.2** https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.6.2.nupkg.

Please download and install it following instruction.
* Download and save Az.Accounts.2.6.2.nupkg to local folder, for instance C:\Dev\testrepo
* Register local folder as local repository following instruction https://docs.microsoft.com/powershell/scripting/gallery/how-to/working-with-local-psrepositories?#registering-a-local-repository
```
Register-PSRepository -Name LocalPSRepo -SourceLocation ' C:\Dev\testrepo' -ScriptSourceLocation ' C:\Dev\testrepo' -InstallationPolicy Trusted
```
* Install Az.Accounts module from local repository.
```
* Install-Module Az.Accounts -Repository LocalPSRepo
```

Please let us know whether issue can be eliminated. Your feedback is very important to us.

**Comment by g7cnp** [comment]
Was reading 16340 when your post came in, whilst I'm sure there must be a link, your modified Az.Accounts didn't fix the issue importing Microsoft.Azure.PowerShell.Cmdlets.Storage.dll, perhaps the same issue exists in both?

**Comment by dingmeng-xue** [comment]
Hi @g7cnp , since we are using the same version of Windows PowerShell and module, this issue may be related to other loaded module?

Please execute below code within the same PowerShell process when you reproduce the issue
```
[System.AppDomain]::CurrentDomain.GetAssemblies() | Where-Object Location | Sort-Object -Property FullName | Select-Object -Property FullName, Location, GlobalAssemblyCache, IsFullyTrusted
```
