### ISSUE TITLE
[Feature]: Get-AzVm should accept ID and ResourceID on the pipeline

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#16381]
### Description of the new feature

Currently you cannot get an Az VM via its resource ID, even though most references to a Az VM are via the refid for instance NetworkInterface `VirtualMachine` property. This should be easier.

Example: 
```powershell
Get-AzResource -TagName 'requestor' -ResourceType 'Microsoft.Network/networkInterfaces'
| Get-AzNetworkInterface #This works as expected
| ForEach-Object {
	$nic = $PSItem
	$requestor = $nic.Tag.Requestor
	if (!$requestor) {return}

	$nic.VirtualMachine | Get-AzVM # This should work but it doesn't
}
```

### Proposed implementation details (optional)

Utility function that implements what I'm talking about:

```powershell
using namespace Microsoft.Azure.Commands.ResourceManager.Cmdlets.Components
function Get-AzVMById {
	[CmdletBinding()]
	param (
		[Alias('ResourceId')]
		[Parameter(Mandatory,ValueFromPipeline,ValueFromPipelineByPropertyName)]$Id
	)
	process {
            $GetAzVMParams = @{
                ResourceGroupName = [ResourceIdUtility]::GetResourceGroupName($Id)
                Name              = [ResourceIdUtility]::GetResourceName($Id)
            }
            Get-AzVM @GetAzVMParams
	}
}
```

**Comment by dingmeng-xue** [comment]
Thank you for your reporting. Tagging and routing to the team member best able to assist.

**Comment by Drewm3** [comment]
Let me work with the team to see where this could fit into the backlog.

**Comment by Drewm3** [comment]
Let me check with the dev team to see if this feature request could be added to the backlog.

**Comment by Drewm3** [comment]
The team will be picking up this feature in the next few weeks. I'll update this thread again when the feature is released.

**Comment by Tbohunek** [comment]
@Drewm3 Imagine this worked for every `Get-AzSomething`, not just `-Vm`. Imagine also parity between `PowerShell` and `CLI`. 😉

**Comment by navba-MSFT** [comment]
@JustinGrote Apologies for the late reply. We are looking into this issue and we will update this thread once we have moe details.

@Drewm3 Could you please provide an update on this feature ? Awaiting your reply.

**Comment by Drewm3** [comment]
This feature request is expected to be available in the April release of the Azure PowerShell cmdlets.

**Comment by Tbohunek** [comment]
Just for `Get-AzVM` or for other `Get-`s?

**Comment by chaoscreater** [comment]
> This feature request is expected to be available in the April release of the Azure PowerShell cmdlets.

Is this ready now, or still being implemented?

**Comment by diecknet** [comment]
> > This feature request is expected to be available in the April release of the Azure PowerShell cmdlets.
> 
> Is this ready now, or still being implemented?

Should be available in newer Az.Compute versions. Not sure since when, but I had 4.26.0 installed and the parameter is available.
