### ISSUE TITLE
Unable to get automation account managed identity object Id with Get-AzAutomationAccount

### ISSUE THREAD

**Issue by zzgzy** [Azure/azure-powershell#16395]
### Description

We use an AAD service principal to log onto Azure and are able to get the object id of Azure Data Factory managed identity using
`(Get-AzDataFactoryV2 -ResourceGroupName "xxxx" -Name "xxx").Identity.PrincipalId`

However, we cannot do the same for automation account managed identity
`(Get-AzAutomationAccount -ResourceGroupName $rgName -Name $name).Identity.PrincipalId`
where `Get-AzAutomationAccount -ResourceGroupName $rgName -Name $name` returns things fine, but `.Identity` and `.Identity.PrincipalId` will both return null.

The managed identity of the automation account is enabled and I am able to run the same script to get the correct object Id when I log in to Azure with my user account. 

### Issue script & Debug output

```PowerShell
`$acc = Get-AzAutomationAccount -ResourceGroupName $AutomationAccountResourceGroup -Name $AutomationAccountDisplayName -ErrorAction SilentlyContinue
Write-Host "acc is $acc"
Write-Host "acc identity is $($acc.Identity)"
Write-Output "acc principalid is $($acc.Identity.PrincipalId)"`


Output:
`2021-11-12 18:36:12.699718: acc is Microsoft.Azure.Commands.Automation.Model.AutomationAccount
2021-11-12 18:36:12.702572: acc identity is
2021-11-12 18:36:12.704309: acc principalid is
2021-11-12 18:36:13.007862: object id is`
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.6.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Con...
Script     4.4.0      Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTe...
```

**Comment by zzgzy** [comment]
I am an internal user and this above script is running under Ev2

**Comment by dingmeng-xue** [comment]
Thank you for your reporting. Tagging and routing to the team member best able to assist.

**Comment by SaurabhSharma-MSFT** [comment]
@zzgzy I have tried the same and I am able to see the PrincipalId by using both ServicePrincipal and individual login.  Please see below screenshot - 
![image](https://user-images.githubusercontent.com/38112130/141883896-9ccb9e10-970a-4429-a755-7f31e3c9af69.png)
What version of Az.Automation Module you are using. I have tried with 1.7.1
![image](https://user-images.githubusercontent.com/38112130/141884005-2b791cfe-5322-48d9-9337-e9ade368b494.png)

**Comment by zzgzy** [comment]
@SaurabhSharma-MSFT Thank you for checking! I would need to check what version is used in Ev2. Is 1.7.1 the minimum requirement of Az.Automation?

**Comment by SaurabhSharma-MSFT** [comment]
@zzgzy I do not think 1.7.1 as minimum requirement but I will check and get back to you.

**Comment by zzgzy** [comment]
@SaurabhSharma-MSFT I have 
2021-11-17 20:25:35.914646: Az.Automation version is 1.3.7
2021-11-17 20:25:37.256014: Az.Accounts version is 1.9.2 
and looks like Az.Automation has dependency on Az.Accounts which I haven't figured out how to l a newer version in Ev2, as I always get `Assembly with same name is already loaded` when doing so.

**Comment by SaurabhSharma-MSFT** [comment]
@zzgzy Can you please try `Update-Module Az.Accounts -RequiredVersion 2.6.2`.

**Comment by zzgzy** [comment]
Issue is resolved by updating the shell extension container version used in Ev2 https://ev2docs.azure.net/features/extensibility/shell/intro.html#linux (MS internal link)

Thanks @SaurabhSharma-MSFT for your help! It looks like the container had some Az update that would be a prerequisite here.
