### ISSUE TITLE
Get-AzureTrafficManager returns two different object types (that represent the same object)

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#164]
## Background

When you run the Get-AzureTrafficManager command, without any parameters, the objects that are returned are of the type `Microsoft.WindowsAzure.Commands.TrafficManager.Models.SimpleProfile`.

![image](https://cloud.githubusercontent.com/assets/466713/6158517/60a2782a-b208-11e4-8323-81c2f1f31500.png)

When you run the `Get-AzureTrafficManager` command with the `-Name` parameter, to retrieve a specific Traffic Manager profile, the object type that is returned is `Microsoft.WindowsAzure.Commands.TrafficManager.Models.ProfileWithDefinition`.

![image](https://cloud.githubusercontent.com/assets/466713/6158531/6e4e35c2-b208-11e4-9ba4-63f49ae08530.png)
## Problem Statement

By using the `Get-Member` command, shown in the screenshots above, you will notice the lack of properties on the `SimpleProfile` type.

As with certain other characteristics of the Azure PowerShell module, this does not follow solid PowerShell design principles. A typical end user of PowerShell would expect to be able to run `Get-AzureTrafficManagerProfile | Select-Object -Property *` to see all of the property values on the objects returned from the command. However, because two different object types are being returned, that ultimately represent the same object (an Azure Traffic Manager Profile), the simplified view is being returned, even when the `Select-Object` command is specified.
## Scenario

Consider the following scenario: You want to retrieve a list of all your Azure Traffic Manager Profiles, but only want to see the properties `DomainName` and `LoadBalancingMethod`. Because the `SimpleProfile` object does not offer the `LoadBalancingMethod` property, you would have to:
1. Call `Get-AzureTrafficManagerProfile`, to retrieve the "simple" definitions of all the Traffic Manager profiles
2. Iterate over each Traffic Manager profile
3. Call `Get-AzureTrafficManagerProfile` _again_, for each Profile, with the `-Name` parameter
4. Filter each `ProfileWithDefinition` for the `DomainName` and `LoadBalancingMethod` properties

As you can see, this process is significantly more challenging than simply calling:

```
Get-AzureTrafficManagerProfile | Select-Object -Property DomainName, LoadBalancingMethod;
```
## Type Formatting

While technically it's perfectly valid for this behavior to occur, the behavior described above goes somewhat against the design principles of PowerShell.

In fact, PowerShell was designed from the very beginning to handle this type of scenario. It's called PowerShell "type formatting," and at a high level, it's basically an XML file, with a `.ps1xml` file extension, that offers up "hints" to PowerShell to help it figure out how to display an object. Therefore, if an object has 10 properties, but only 4 or 5 of them are most commonly cared about, then only those properties will be shown by default. **However**, if the user pipes the command into a formatting command such as `Format-Table`, `Format-List`, or even `Select-Object`, the user gains control over which properties are displayed (or "selected" / filtered).
## Actionable Item

The suggested "PowerShell-friendly" corrective action for this implementation is to return a single object type, to represent an Azure Traffic Manager Profile, regardless of whether or not the `-Name` parameter is present. Implement a "type formatting" `.ps1xml` file in the Azure PowerShell module, that hints/instructs PowerShell on how to display the Traffic Manager object by default, but ensure that the user has control to select _all_, or _some_, of the properties that they so desire, _without_ being forced to retrieve a specific profile, using the `-Name` parameter.

Please reach out to me for clarification if it is required, otherwise I will trust that this post is well-understood.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://twitter.com/pcgeek86
http://trevorsullivan.net

**Comment by matt-gibbs** [comment]
Thank you Trevor. Following up.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
