### ISSUE TITLE
Import-azureRMAutomationRunbook should be able to import from url

### ISSUE THREAD

**Issue by AHuusom** [Azure/azure-powershell#1640]
At the moment the cmdlet is only able to import from a file path.
I would like for it to be able to import from a url so I can import runbooks stored in such as Azure Storage blobs.

**Comment by markcowl** [comment]
@AHuusom Thanks for the report.  Adding in the service team for resolution.

**Comment by jodoglevy** [comment]
This seems low priority. Can't you just download the file and then import it?

**Comment by AHuusom** [comment]
If you want to run it using Azure Automation and you have runbooks placed in Azure Storage, so there is no user interaction.
Then it is hard to download it first and then import them.

**Comment by maddieclayton** [comment]
@vrdmr @eamonoreilly Are you planning to implement this feature in the future? If not, please close this issue.

**Comment by andyw248** [comment]
Triaged: Won't add the requested feature.
