### ISSUE TITLE
New-AzureRMAutomationModule not showing correct status.

### ISSUE THREAD

**Issue by AHuusom** [Azure/azure-powershell#1641]
As soon as the cmdlet is done and the module is imported in Azure automation Status goes from creating to created.
It does this even though all the cmdlets hasn't been extracted yet, which in my case takes about 3 minutes.
So I would really like for it to have the -wait function implemented so it won't continue until it has done all the extractions.
Now I have to do a while loop that montior last modifed time....

**Comment by jodoglevy** [comment]
The output of Get-AzureRmAutomationModule cmdlet should have a ProvisioningStatus property that tells you when extraction is in progress, and when it is completed.

**Comment by AHuusom** [comment]
Yes, it does have this property, but if the module is custom build, it goes from Creating to Created even though cmdlets haven't been extracted yet.
It Works fine with modules downloaded from the powershel gallery

**Comment by jodoglevy** [comment]
Can you provide the module zip which has the issue?

**Comment by jodoglevy** [comment]
@AHuusom since you didn't provide the module, have you figured out the issue?

**Comment by marrobi** [comment]
I'm having similar problems...  The ProvisioningState always returns "Creating", even when the extraction shows as completed in the portal. This means I can't pause execution of scripts while extraction completes. Something doesn't seem right, but could be a mistake at my end.

ResourceGroupName     : ...
AutomationAccountName : ...
Name                  : nx
IsGlobal              : False
Version               : 1.0
SizeInBytes           : 5127
ActivityCount         : 0
CreationTime          : 21/03/2016 16:10:02 +00:00
LastModifiedTime      : 21/03/2016 16:35:41 +00:00
ProvisioningState     : Creating

**Comment by jodoglevy** [comment]
This is working for me. As you can see, when module extraction is complete, status says "Succeeded":

PS C:\Users\jolevy> $mod = New-AzureRmAutomationModule -Name SSH -ContentLink "http://joestorage123.blob.core.windows.net/public/SSH.zip" -ResourceGroupName anotherservice -AutomationAccountName powershellsummit

PS C:\Users\jolevy> $mod

ResourceGroupName     : anotherservice
AutomationAccountName : powershellsummit
Name                  : SSH
IsGlobal              : False
Version               : 
SizeInBytes           : 0
ActivityCount         : 0
CreationTime          : 3/22/2016 1:44:01 PM -07:00
LastModifiedTime      : 3/22/2016 1:44:01 PM -07:00
ProvisioningState     : Creating

PS C:\Users\jolevy> $mod | Get-AzureRmAutomationModule

ResourceGroupName     : anotherservice
AutomationAccountName : powershellsummit
Name                  : SSH
IsGlobal              : False
Version               : 
SizeInBytes           : 0
ActivityCount         : 0
CreationTime          : 3/22/2016 1:44:01 PM -07:00
LastModifiedTime      : 3/22/2016 1:44:01 PM -07:00
ProvisioningState     : Creating

PS C:\Users\jolevy> $mod | Get-AzureRmAutomationModule

ResourceGroupName     : anotherservice
AutomationAccountName : powershellsummit
Name                  : SSH
IsGlobal              : False
Version               : 
SizeInBytes           : 0
ActivityCount         : 0
CreationTime          : 3/22/2016 1:44:01 PM -07:00
LastModifiedTime      : 3/22/2016 1:44:01 PM -07:00
ProvisioningState     : Creating

PS C:\Users\jolevy> $mod | Get-AzureRmAutomationModule

ResourceGroupName     : anotherservice
AutomationAccountName : powershellsummit
Name                  : SSH
IsGlobal              : False
Version               : 1.0.0
SizeInBytes           : 156621
ActivityCount         : 1
CreationTime          : 3/22/2016 1:44:01 PM -07:00
LastModifiedTime      : 3/22/2016 1:45:47 PM -07:00
ProvisioningState     : Succeeded
