### ISSUE TITLE
[Doc]: Request for revision of Remove-AzAutomationHybridWorkerGroup document

### ISSUE THREAD

**Issue by jun110** [Azure/azure-powershell#16422]
### Description

Hi team, I found the wrong part in the following document.
https://github.com/Azure/azure-powershell/blob/main/src/Automation/Automation/help/Remove-AzAutomationHybridWorkerGroup.md

The Force parameter is not present in this command. So I think we need to fix it.
![image](https://user-images.githubusercontent.com/25476639/142140979-4efa770d-4f3f-420e-970b-426e32d4f8b8.png)

**Comment by PramodValavala-MSFT** [comment]
@jun110 Thanks for catching that! We worked up a PR to fix the same.
