### ISSUE TITLE
How to remove classic administrator using any Az command?

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-powershell#16445]
### Description

Command `Get-AzRoleAssignment` has a parameter `IncludeClassicAdministrators`. However its counterpart `Remove-AzRoleAssignment` doesn't seem to be aware of classic roles model.

Is there a way remove a user from classic administrators programmatically, especially if it bulk when using the Azure Portal is not applicable?

### Environment data

PSVersion 7.1.4

PSVersion 5.1.19041.1320

### Module versions

```PowerShell
Az.Resources 4.4.1
```

**Comment by dingmeng-xue** [comment]
Thank you for your reporting. Tagging and routing to the team member best able to assist.

**Comment by SaurabhSharma-MSFT** [comment]
@abatishchev It is not possible with Remove-AzRoleAssignment but I am checking internally for any other ways to do the same.  I will get back to you on the same.

**Comment by SaurabhSharma-MSFT** [comment]
@abatishchev You cannot remove classic administrators using Powershell cmdlet and you may need to use portal for deleting those assignments manually. Please let me know if you have any other questions. Thanks.

**Comment by juergenbr** [comment]
Ran into the same issue today, we need to change permissions for 200+ subscriptions and want to automate the process. Is there no way to implement this?

**Comment by abatishchev** [comment]
@juergenbr here's few pointers:

1. Delete a co-admin using the Azure Portal, track what API call it has made
2. Figure out the legacy user id, for me it looked like `100110003D55E51B`
3. Repeat the call for arbitrary subscription, user id

The API call in my case looked like this:

```powershell
$h = @{ 'Authorization' = $a } # your authz header
$apiVersion = '2015-06-01'
$url = "https://edge.management.azure.com/subscriptions/$sub/providers/Microsoft.Authorization/classicadministrators/$user?api-version=$apiVersion`&adminType=serviceAdmin"

Invoke-RestMethod -Verbose `
                  -Headers $h `
                  -Method DELETE `
                  -Url $url
```

Notes:

1. The api version `2015-06-01` is not documented and currently unlisted, you can find the spec for it [here](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/authorization/resource-manager/Microsoft.Authorization/preview/2015-06-01)
2. The api version `2015-07-01` is [documented](https://docs.microsoft.com/en-us/rest/api/authorization/classic-administrators/list ) and listed, you can find the spec for it [here](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/authorization/resource-manager/Microsoft.Authorization/stable/2015-07-01)

Authorization options:

1. Use an identity with the appropriate permissions on the subscription (Owner or [User Access Administrator](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#user-access-administrator))
2. "Steal" your own authorization header from the UI
3. Call `Login-AzAccount` and then `$a = Get-AzAccessToken`

**Comment by SaurabhSharma-MSFT** [comment]
@abatishchev Thanks for sharing your alternative solution.
@juergenbr FYI

**Comment by juergenbr** [comment]
@abatishchev thanks for the detailed instructions!

**Comment by SaurabhSharma-MSFT** [comment]
@abatishchev I am closing this issue for now.  Please feel free to open a new issue if you have any new queries.

Thanks
Saurabh

**Comment by kwill-MSFT** [comment]
FYI for anyone finding this issue later, here is a more complete sample, and one that uses Invoke-AzRestMethod instead of manually dealing with auth tokens.

```
$GetClassicAdminshttpresponse = Invoke-AzRestMethod -Method GET -Path "/subscriptions/$SubscriptionId/providers/Microsoft.Authorization/classicAdministrators?api-version=2015-06-01"
$ClassicAdmins = ($GetClassicAdminshttpresponse.Content | ConvertFrom-Json).value
foreach ($ClassicAdmin in $ClassicAdmins)
{
    # your logic to determine which admins to delete or keep....
    $URL = "$($ClassicAdmin.id)?api-version=2015-06-01"
    $Deletehttpresponse = Invoke-AzRestMethod -Method DELETE -Path $URL
    if ($Deletehttpresponse.StatusCode -in @("200", "202"))
    {
         Write-Information "Successfully deleted account $($ClassicAdmin.properties.emailAddress)"
    }
}
```

**Comment by abatishchev** [comment]
I didn't know about `Invoke-AzRestMethod`, thanks for sharing!

I also was told that the ARM team has solved the issue with the API versions.

**Comment by dvht** [comment]
Using the code of @kwill-MSFT resulted in a strange HTTP-400 : 
` "message": "Failed to delete classic administrator of subscription '...': 'This user is already a service administrator for the subscription.'."`
Then I realised the code of @abatishchev contained another query operator.  The $url assignment should be
`$URL = "$($ClassicAdmin.id)?api-version=2015-06-01&adminType=serviceAdmin"`
