### ISSUE TITLE
PowerShell ISE more "az.storage" cmdlet as Visual Studio Code 

### ISSUE THREAD

**Issue by claudio-ss** [Azure/azure-powershell#16466]
### Description

I have just installed the latest 6.6.0 version of the Az Module. Now I noticed that there are more cmdlets in the PowerShell ISE than in the Visual Studio code.

Example "az.storage"

PowerShell ISE
PS C:\Users\user> Get-Command -Module az.storage
CommandType     Name                                               Version    Source                                                                                                                             
-----------     ----                                               -------    ------                                                                                                                             
Alias           Disable-AzStorageSoftDelete                        3.12.0     az.storage                                                                                                                         
Alias           Enable-AzStorageSoftDelete                         3.12.0     az.storage                                                                                                                         
Alias           Get-AzDatalakeGen2FileSystem                       3.12.0     az.storage                                                                                                                         
Alias           Get-AzStorageContainerAcl                          3.12.0     az.storage                                                                                                                         
Alias           New-AzDatalakeGen2FileSystem                       3.12.0     az.storage                                                                                                                         
Alias           New-AzDataLakeGen2ItemAclObject                    3.12.0     az.storage                                                                                                                         
Alias           Remove-AzDatalakeGen2FileSystem                    3.12.0     az.storage                                                                                                                         
Alias           Start-CopyAzureStorageBlob                         3.12.0     az.storage                                                                                                                         
Alias           Stop-CopyAzureStorageBlob                          3.12.0     az.storage                                                                                                                         
Cmdlet          Add-AzRmStorageContainerLegalHold                  3.12.0     az.storage                                                                                                                         
Cmdlet          Add-AzStorageAccountManagementPolicyAction         3.12.0     az.storage                                                                                                                         
Cmdlet          Add-AzStorageAccountNetworkRule                    3.12.0     az.storage                                                                                                                         
Cmdlet          Close-AzStorageFileHandle                          3.12.0     az.storage                                                                                                                         
Cmdlet          Copy-AzStorageBlob                                 3.12.0     az.storage                                                                                                                         
Cmdlet          Disable-AzStorageBlobDeleteRetentionPolicy         3.12.0     az.storage                                                                                                                         
Cmdlet          Disable-AzStorageBlobLastAccessTimeTracking        3.12.0     az.storage                                                                                                                         
Cmdlet          Disable-AzStorageBlobRestorePolicy                 3.12.0     az.storage                                                                                                                         
Cmdlet          Disable-AzStorageContainerDeleteRetentionPolicy    3.12.0     az.storage                                                                                                                         
Cmdlet          Disable-AzStorageDeleteRetentionPolicy             3.12.0     az.storage                                                                                                                         
Cmdlet          Disable-AzStorageStaticWebsite                     3.12.0     az.storage                                                                                                                         
Cmdlet          Enable-AzStorageBlobDeleteRetentionPolicy          3.12.0     az.storage                                                                                                                         
Cmdlet          Enable-AzStorageBlobLastAccessTimeTracking         3.12.0     az.storage                                                                                                                         
Cmdlet          Enable-AzStorageBlobRestorePolicy                  3.12.0     az.storage                                                                                                                         
Cmdlet          Enable-AzStorageContainerDeleteRetentionPolicy     3.12.0     az.storage                                                                                                                         
Cmdlet          Enable-AzStorageDeleteRetentionPolicy              3.12.0     az.storage                                                                                                                         
Cmdlet          Enable-AzStorageStaticWebsite                      3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzDataLakeGen2ChildItem                        3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzDataLakeGen2Item                             3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzDataLakeGen2ItemContent                      3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzRmStorageContainer                           3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzRmStorageContainerImmutabilityPolicy         3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzRmStorageShare                               3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageAccount                               3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageAccountKey                            3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageAccountManagementPolicy               3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageAccountNameAvailability               3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageAccountNetworkRuleSet                 3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageBlob                                  3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageBlobByTag                             3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageBlobContent                           3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageBlobCopyState                         3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageBlobInventoryPolicy                   3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageBlobQueryResult                       3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageBlobServiceProperty                   3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageBlobTag                               3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageContainer                             3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageContainerStoredAccessPolicy           3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageCORSRule                              3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageEncryptionScope                       3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageFile                                  3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageFileContent                           3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageFileCopyState                         3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageFileHandle                            3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageFileServiceProperty                   3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageObjectReplicationPolicy               3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageQueue                                 3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageQueueStoredAccessPolicy               3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageServiceLoggingProperty                3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageServiceMetricsProperty                3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageServiceProperty                       3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageShare                                 3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageShareStoredAccessPolicy               3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageTable                                 3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageTableStoredAccessPolicy               3.12.0     az.storage                                                                                                                         
Cmdlet          Get-AzStorageUsage                                 3.12.0     az.storage                                                                                                                         
Cmdlet          Invoke-AzStorageAccountFailover                    3.12.0     az.storage                                                                                                                         
Cmdlet          Invoke-AzStorageAccountHierarchicalNamespaceUpg... 3.12.0     az.storage                                                                                                                         
Cmdlet          Lock-AzRmStorageContainerImmutabilityPolicy        3.12.0     az.storage                                                                                                                         
Cmdlet          Move-AzDataLakeGen2Item                            3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzDataLakeGen2Item                             3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzRmStorageContainer                           3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzRmStorageShare                               3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageAccount                               3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageAccountKey                            3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageAccountManagementPolicyFilter         3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageAccountManagementPolicyRule           3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageAccountSASToken                       3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageBlobInventoryPolicyRule               3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageBlobQueryConfig                       3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageBlobRangeToRestore                    3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageBlobSASToken                          3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageContainer                             3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageContainerSASToken                     3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageContainerStoredAccessPolicy           3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageContext                               3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageDirectory                             3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageEncryptionScope                       3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageFileSASToken                          3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageObjectReplicationPolicyRule           3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageQueue                                 3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageQueueSASToken                         3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageQueueStoredAccessPolicy               3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageShare                                 3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageShareSASToken                         3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageShareStoredAccessPolicy               3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageTable                                 3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageTableSASToken                         3.12.0     az.storage                                                                                                                         
Cmdlet          New-AzStorageTableStoredAccessPolicy               3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzDataLakeGen2AclRecursive                  3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzDataLakeGen2Item                          3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzRmStorageContainer                        3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzRmStorageContainerImmutabilityPolicy      3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzRmStorageContainerLegalHold               3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzRmStorageShare                            3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageAccount                            3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageAccountManagementPolicy            3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageAccountNetworkRule                 3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageBlob                               3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageBlobInventoryPolicy                3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageContainer                          3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageContainerStoredAccessPolicy        3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageCORSRule                           3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageDirectory                          3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageFile                               3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageObjectReplicationPolicy            3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageQueue                              3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageQueueStoredAccessPolicy            3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageShare                              3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageShareStoredAccessPolicy            3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageTable                              3.12.0     az.storage                                                                                                                         
Cmdlet          Remove-AzStorageTableStoredAccessPolicy            3.12.0     az.storage                                                                                                                         
Cmdlet          Restore-AzRmStorageShare                           3.12.0     az.storage                                                                                                                         
Cmdlet          Restore-AzStorageBlobRange                         3.12.0     az.storage                                                                                                                         
Cmdlet          Restore-AzStorageContainer                         3.12.0     az.storage                                                                                                                         
Cmdlet          Revoke-AzStorageAccountUserDelegationKeys          3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzCurrentStorageAccount                        3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzDataLakeGen2AclRecursive                     3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzDataLakeGen2ItemAclObject                    3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzRmStorageContainerImmutabilityPolicy         3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageAccount                               3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageAccountManagementPolicy               3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageBlobContent                           3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageBlobInventoryPolicy                   3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageBlobTag                               3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageContainerAcl                          3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageContainerStoredAccessPolicy           3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageCORSRule                              3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageFileContent                           3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageObjectReplicationPolicy               3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageQueueStoredAccessPolicy               3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageServiceLoggingProperty                3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageServiceMetricsProperty                3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageShareQuota                            3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageShareStoredAccessPolicy               3.12.0     az.storage                                                                                                                         
Cmdlet          Set-AzStorageTableStoredAccessPolicy               3.12.0     az.storage                                                                                                                         
Cmdlet          Start-AzStorageBlobCopy                            3.12.0     az.storage                                                                                                                         
Cmdlet          Start-AzStorageBlobIncrementalCopy                 3.12.0     az.storage                                                                                                                         
Cmdlet          Start-AzStorageFileCopy                            3.12.0     az.storage                                                                                                                         
Cmdlet          Stop-AzStorageAccountHierarchicalNamespaceUpgrade  3.12.0     az.storage                                                                                                                         
Cmdlet          Stop-AzStorageBlobCopy                             3.12.0     az.storage                                                                                                                         
Cmdlet          Stop-AzStorageFileCopy                             3.12.0     az.storage                                                                                                                         
Cmdlet          Update-AzDataLakeGen2AclRecursive                  3.12.0     az.storage                                                                                                                         
Cmdlet          Update-AzDataLakeGen2Item                          3.12.0     az.storage                                                                                                                         
Cmdlet          Update-AzRmStorageContainer                        3.12.0     az.storage                                                                                                                         
Cmdlet          Update-AzRmStorageShare                            3.12.0     az.storage                                                                                                                         
Cmdlet          Update-AzStorageAccountNetworkRuleSet              3.12.0     az.storage                                                                                                                         
Cmdlet          Update-AzStorageBlobServiceProperty                3.12.0     az.storage                                                                                                                         
Cmdlet          Update-AzStorageEncryptionScope                    3.12.0     az.storage                                                                                                                         
Cmdlet          Update-AzStorageFileServiceProperty                3.12.0     az.storage                                                                                                                         
Cmdlet          Update-AzStorageServiceProperty                    3.12.0     az.storage                                                                                                                         
PS C:\Users\user> 

Visual Studio Code
PS C:\Users\user> Get-Command -Module az.storage
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Add-AzRmStorageContainerLegalHold                  3.12.0     az.storage
Cmdlet          Add-AzStorageAccountManagementPolicyAction         3.12.0     az.storage
Cmdlet          Add-AzStorageAccountNetworkRule                    3.12.0     az.storage
Cmdlet          Disable-AzStorageBlobDeleteRetentionPolicy         3.12.0     az.storage
Cmdlet          Disable-AzStorageBlobLastAccessTimeTracking        3.12.0     az.storage
Cmdlet          Disable-AzStorageBlobRestorePolicy                 3.12.0     az.storage
Cmdlet          Disable-AzStorageContainerDeleteRetentionPolicy    3.12.0     az.storage
Cmdlet          Enable-AzStorageBlobDeleteRetentionPolicy          3.12.0     az.storage
Cmdlet          Enable-AzStorageBlobLastAccessTimeTracking         3.12.0     az.storage
Cmdlet          Enable-AzStorageBlobRestorePolicy                  3.12.0     az.storage
Cmdlet          Enable-AzStorageContainerDeleteRetentionPolicy     3.12.0     az.storage
Cmdlet          Get-AzRmStorageContainer                           3.12.0     az.storage
Cmdlet          Get-AzRmStorageContainerImmutabilityPolicy         3.12.0     az.storage
Cmdlet          Get-AzRmStorageShare                               3.12.0     az.storage
Cmdlet          Get-AzStorageAccount                               3.12.0     az.storage
Cmdlet          Get-AzStorageAccountKey                            3.12.0     az.storage
Cmdlet          Get-AzStorageAccountManagementPolicy               3.12.0     az.storage
Cmdlet          Get-AzStorageAccountNameAvailability               3.12.0     az.storage
Cmdlet          Get-AzStorageAccountNetworkRuleSet                 3.12.0     az.storage
Cmdlet          Get-AzStorageBlobInventoryPolicy                   3.12.0     az.storage
Cmdlet          Get-AzStorageBlobServiceProperty                   3.12.0     az.storage
Cmdlet          Get-AzStorageEncryptionScope                       3.12.0     az.storage
Cmdlet          Get-AzStorageFileServiceProperty                   3.12.0     az.storage
Cmdlet          Get-AzStorageObjectReplicationPolicy               3.12.0     az.storage
Cmdlet          Get-AzStorageUsage                                 3.12.0     az.storage
Cmdlet          Invoke-AzStorageAccountFailover                    3.12.0     az.storage
Cmdlet          Invoke-AzStorageAccountHierarchicalNamespaceUpg... 3.12.0     az.storage
Cmdlet          Lock-AzRmStorageContainerImmutabilityPolicy        3.12.0     az.storage
Cmdlet          New-AzRmStorageContainer                           3.12.0     az.storage
Cmdlet          New-AzRmStorageShare                               3.12.0     az.storage
Cmdlet          New-AzStorageAccount                               3.12.0     az.storage
Cmdlet          New-AzStorageAccountKey                            3.12.0     az.storage
Cmdlet          New-AzStorageAccountManagementPolicyFilter         3.12.0     az.storage
Cmdlet          New-AzStorageAccountManagementPolicyRule           3.12.0     az.storage
Cmdlet          New-AzStorageBlobInventoryPolicyRule               3.12.0     az.storage
Cmdlet          New-AzStorageBlobRangeToRestore                    3.12.0     az.storage
Cmdlet          New-AzStorageEncryptionScope                       3.12.0     az.storage
Cmdlet          New-AzStorageObjectReplicationPolicyRule           3.12.0     az.storage
Cmdlet          Remove-AzRmStorageContainer                        3.12.0     az.storage
Cmdlet          Remove-AzRmStorageContainerImmutabilityPolicy      3.12.0     az.storage
Cmdlet          Remove-AzRmStorageContainerLegalHold               3.12.0     az.storage
Cmdlet          Remove-AzRmStorageShare                            3.12.0     az.storage
Cmdlet          Remove-AzStorageAccount                            3.12.0     az.storage
Cmdlet          Remove-AzStorageAccountManagementPolicy            3.12.0     az.storage
Cmdlet          Remove-AzStorageAccountNetworkRule                 3.12.0     az.storage
Cmdlet          Remove-AzStorageBlobInventoryPolicy                3.12.0     az.storage
Cmdlet          Remove-AzStorageObjectReplicationPolicy            3.12.0     az.storage
Cmdlet          Restore-AzRmStorageShare                           3.12.0     az.storage
Cmdlet          Restore-AzStorageBlobRange                         3.12.0     az.storage
Cmdlet          Revoke-AzStorageAccountUserDelegationKeys          3.12.0     az.storage
Cmdlet          Set-AzCurrentStorageAccount                        3.12.0     az.storage
Cmdlet          Set-AzRmStorageContainerImmutabilityPolicy         3.12.0     az.storage
Cmdlet          Set-AzStorageAccount                               3.12.0     az.storage
Cmdlet          Set-AzStorageAccountManagementPolicy               3.12.0     az.storage
Cmdlet          Set-AzStorageBlobInventoryPolicy                   3.12.0     az.storage
Cmdlet          Set-AzStorageObjectReplicationPolicy               3.12.0     az.storage
Cmdlet          Stop-AzStorageAccountHierarchicalNamespaceUpgrade  3.12.0     az.storage
Cmdlet          Update-AzRmStorageContainer                        3.12.0     az.storage
Cmdlet          Update-AzRmStorageShare                            3.12.0     az.storage
Cmdlet          Update-AzStorageAccountNetworkRuleSet              3.12.0     az.storage
Cmdlet          Update-AzStorageBlobServiceProperty                3.12.0     az.storage
Cmdlet          Update-AzStorageEncryptionScope                    3.12.0     az.storage
Cmdlet          Update-AzStorageFileServiceProperty                3.12.0     az.storage
PS C:\Users\user> 

Can this please be adjusted again so that all cmdlets are also available in Visual Studio Code?

### Issue script & Debug output

```PowerShell
No Debug output
```

### Environment data

```PowerShell
PS C:\Users\user> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PowerShell ISE
PS C:\Users\User> Get-Module Az*
ModuleType Version    Name                                ExportedCommands                                                                                                                                       
---------- -------    ----                                ----------------                                                                                                                                       
Script     2.6.2      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}                                                                            
Script     3.12.0     az.storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle...}         
Script     0.2.4.2    AzureAutomationAuthoringToolkit     {Get-AutomationCertificate, Get-AutomationConnection, Get-AutomationVariable, Get-AzureAutomationAuthoringToolkitConfiguration...}   

Visual Sudio Code
PS C:\Users\user> Get-Module Az*
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.6.2      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     3.12.0     az.storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Disable...
```

### Error output

```PowerShell
PS C:\Users\User> New-AzStorageContext

New-AzStorageContext : Die Benennung "New-AzStorageContext" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. 
Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ New-AzStorageContext
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-AzStorageContext:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by dingmeng-xue** [comment]
This issue can be reproduced. It should be conflict between Az.Storage and assemblies loaded by Az.Accounts. We will look into it.
```
New-AzStorageContext : The term 'New-AzStorageContext' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ New-AzStorageContext
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-AzStorageContext:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Import-Module : Method 'GetTokenAsync' in type 'Microsoft.WindowsAzure.Commands.Storage.Common.AzureSessionCredential' from 
assembly 'Microsoft.Azure.PowerShell.Cmdlets.Storage, Version=3.12.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not  
have an implementation.
At C:\Users\dixue\Documents\PowerShell\Modules\Az.Storage\3.12.0\Az.Storage.psm1:123 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

Add-Type : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
At C:\Users\dixue\Documents\PowerShell\Modules\Az.Accounts\2.6.2\Az.Accounts.psm1:39 char:21
+ ...                Add-Type -Path $_.FullName -ErrorAction Ignore | Out-N ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], ReflectionTypeLoadException
    + FullyQualifiedErrorId : System.Reflection.ReflectionTypeLoadException,Microsoft.PowerShell.Commands.AddTypeCommand
```

**Comment by dingmeng-xue** [comment]
This issue is due to some cmdlets of Az.Storage was built on Azure.Core 1.19.0 but cannot work with Azure.Core on 1.20.0 when the same dependent assembly loaded by VScode extensions.

This issue will be eliminated in new Az.Storage version after recompilation.

Workaround is user needs to use Az.Accounts 2.5.4 which contains Azure.Core 1.19.0

**Comment by isra-fel** [comment]
Az 7.0.0 was released - check out https://github.com/Azure/azure-powershell/releases/tag/v7.0.0-December2021
