### ISSUE TITLE
Upgrade MSAL library (Microsoft.Identity.Client) to  v4.38.0

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/azure-powershell#16479]
### Description

Following issue https://github.com/Azure/azure-powershell/issues/15587, it has been fixed in MSAL side https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2839.

To do: Upgrade MSAL library (Microsoft.Identity.Client) to  v4.38.0

### Issue script & Debug output

```PowerShell
None
```

### Environment data

```PowerShell
None
```

### Module versions

```PowerShell
None
```

**Comment by dingmeng-xue** [comment]
It should be upgraded with Azure.Identity. Let's wait its next release.
