### ISSUE TITLE
[Feature]: Open-AzureADMSPrivilegedRoleAssignmentRequest does not support scoped assignments

### ISSUE THREAD

**Issue by jspc0** [Azure/azure-powershell#16476]
### Description of the new feature

The cmdlet does not support creating assignments that are scoped to Administrative Units, this is a critical feature when using PIM for granular delegation.

Looks like Graph exposes the necessary property for that "directoryScopeId"

https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignmentscheduleinstance?view=graph-rest-beta

**Comment by dingmeng-xue** [comment]
Hi @Jspcstl , thanks for reporting. However `AzureAD` module containing that cmdlet is not owned by current Github repo. You have to raise the request via Microsoft support channel.

**Comment by pekohub** [comment]
@jspc0 So, did you open up a ticket with MS, or did you create/find a workaround?

**Comment by pekohub** [comment]
@dingmeng-xue Can you please elaborate on where and how to open such a feature request ticket with MS? Is it something I can do in our company support contract? Or is there a special place for requesting features for code, in this case Powershell cmdlets?
