### ISSUE TITLE
webapp:What is the RM version cmdlet for: Get-AzureDeployment

### ISSUE THREAD

**Issue by HaiyingXu** [Azure/azure-powershell#1648]
What is the RM version cmdlet for: Get-AzureDeployment -ServiceName "xxx" -Slot "staging". We used to use following script to get the IP address of the staging slot:
Get-AzureDeployment -ServiceName "xxx" -Slot "staging"
$deployment.VirtualIPs[0].Address
Recently, we are switching to ARM azure deployment. However, cannot find the matching RM cmdlet for Get-AzureDeployment.

Really appreciate if anyone knows how to get the ip address for the staging slot.

**Comment by markcowl** [comment]
@HaiyingXu I don't believe this functionality is available iN ARM cmdlets yet.  Assigning to the appservice team to take a look

**Comment by maddieclayton** [comment]
Closing. Please reopen this issue if you are still experiencing this issue in the most recent version.

**Comment by wolfen351** [comment]
Please can you supply the name of the RM version? I'm having this issue too..

**Comment by maddieclayton** [comment]
@panchagnula Can you take a look at this issue?

**Comment by panchagnula** [comment]
@wolfen351 there is no equivalent ARM command for this - however regarding the IP Addresses for slot  have you tried Get-AzWebAppSlot https://docs.microsoft.com/en-us/powershell/module/Az.Websites/Get-AzWebAppSlot?view=azps-2.2.0, you should see the VirtualIP under "hostNameSslStates"
