### ISSUE TITLE
[Feature]: Support autocompleter on Set-AzContext

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#16514]
### Description of the new feature

It's great that we can allow user select tenant or subscription when they input parameter on `Set-AzContext`

### Proposed implementation details (optional)

The auto completer needs to provide suggestion according to all available context in current session.

_No response_

**Comment by LucasYao93** [comment]
Hi @dingmeng-xue,
I plan to create new attribute `AzureProfileCompleterAttribute` to implement the feature.

## Usage
`AzureProfileCompleter('subcriptionId')`
`AzureProfileCompleter('subcriptionName')`
`AzureProfileCompleter('tenant')`

What do you think ?

**Comment by LucasYao93** [comment]
@dingmeng-xue 
The powershell v7.2.0-preview.5 started to support parameterized argument completers. 
[Issue: Support parameterized argument completers](https://github.com/PowerShell/PowerShell/issues/12708)
[powershell v7.2.0-preview.5 release notes](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.0-preview.5)

So we can create  parameterized argument AzureProfileCompleter.:pensive:

We have to create completers for different target profile information.

**Comment by dingmeng-xue** [comment]
Let's close this one and revisit this feature after 7.2 has been largely adopted.
