### ISSUE TITLE
KeyNotFoundException when running Add-AzureAccount with no RDFE subscriptions

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#1654]
When a user is not a co-admin on any subscriptions, we throw an error like the following: 

DEBUG: AzureQoSEvent: CmdletType - AddAzureAccount; IsSuccess - False; Duration - 00:00:13.2429011; Exception - System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Azure.Common.Authentication.ProfileClient.AddAccountAndLoadSubscriptions(AzureAccount account, AzureEnvironment environment, SecureString password)
   at Microsoft.WindowsAzure.Commands.Profile.AddAzureAccount.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();

We should catch this condition and print a helpful error message, including the most likely cause, which is that a user really wanted to use Add-AzureRmAccount

**Comment by markcowl** [comment]
### Root Cause
RDFE cmdlets do not check for null or empty subscription list

### Proposed Solution
Check for no subscriptions in list in ```Add-AzureAccount``` and print a helpful error message like "No subscriptions are associated with the logged in account in Azure Service Management (RDFE).  This means that the logged in user is not an administraotr or co-administrator for any account. Did you mean to execute Add-AzureRmAccount?

Add mocked negative tests

### Cost (work unites): 1

**Comment by hovsepm** [comment]
Fixed in dev branch, will be available in June release
