### ISSUE TITLE
Get-AzAlertRule not producing any output

### ISSUE THREAD

**Issue by Hardingsa** [Azure/azure-powershell#16545]
### Description

I'm attempting to utilize the Get-AzAlertRule -ResourceGroup "xxxxx" via Azure Powershell, however I get no results or output. 

https://docs.microsoft.com/en-us/powershell/module/az.monitor/get-azalertrule?view=azps-6.6.0

I only receive the following: 
PS C:\Users\xxxxxx> Get-AzAlertRule -ResourceGroup "xx-xx-xx-xxxx"
WARNING: 5:35:25 PM - The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.
WARNING: 5:35:25 PM - The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model classes.
WARNING: [Get-AzAlertRule] Parameter deprecation: The DetailedOutput parameter will be deprecated in a future breaking change release.

### Issue script & Debug output

```PowerShell
PS C:\Users\xxxxxx> Get-AzAlertRule -ResourceGroup "xx-xx-xx-xxxx"
WARNING: 5:35:25 PM - The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.
WARNING: 5:35:25 PM - The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model classes.
WARNING: [Get-AzAlertRule] Parameter deprecation: The DetailedOutput parameter will be deprecated in a future breaking change release.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.5.2                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefa…
Script     2.7.0                 Az.Monitor                          {Add-AzAutoscaleSetting, Add-AzLogProfile, Add-Az…
```

### Error output

```PowerShell
HistoryId: 4

Message        : Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient
                 number of parameters were provided.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.ThrowAmbiguousParameterSetException(UInt32 parameterSetFlags,
                 MergedCommandParameterMetadata bindableParameters)
                    at System.Management.Automation.CmdletParameterBinderController.ValidateParameterSets(Boolean prePipelineInput, Boolean setDefault)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements,
                 CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Get-AzAlertRule}
Line           : Get-AzAlertRule
Position       : At line:1 char:1
                 + Get-AzAlertRule
                 + ~~~~~~~~~~~~~~~
HistoryId      : 4
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Could you turn on the debug message via `$DebugPrefence = "Continue"` and execute `Get-AzAlertRule -ResourceGroup "xx-xx-xx-xxxx"` again? It will show up the response from service.

**Comment by Hardingsa** [comment]
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxxxxxx',
 environment: 'AzureCloud', tenant: '8f5a5a7f-3cdb-48f1-a894-351a54b84920'
DEBUG: 7:34:44 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync -xxxx', Scopes:'https://management.core.windows.net//.defa
ult', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxxxxxxxx'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.ne
t//.default ] ParentRequestId: 
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44 - ] Azure r
egion was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44] Found 3 ca
che accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44] Returning 
3 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44 - ] MSAL MS
AL.Desktop with assembly version '4.30.1.0'. CorrelationId(b79df653-ec23-4733-954c-8ac92ffe7cdb)
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44 - ] === Acq
uireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44 - ] LoginHi
nt provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44 - ] Account
 provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44 - ] ForceRe
fresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44 - ] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - b79df653-ec23-4733-954c-8ac92ffe7cdb

DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44 - ] === Tok
en Acquisition (SilentRequest) started:
	
	Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44 - ] Azure r
egion was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44 - ] Access 
token is not expired. Returning the found cache entry. [Current time (12/02/2021 02:34:44) - Exp
iration Time (12/02/2021 03:43:11 +00:00) - Extended Expiration Time (12/02/2021 03:43:11 +00:00
)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44 - ] Returni
ng access token found in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44 - ] Fetched
 access token from host login.microsoftonline.com. 
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [12/02/2021 02:34:44 - ] === Tok
en Acquisition finished successfully. An access token was returned with Expiration Time: 12/02/2
021 03:43:11 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://m
anagement.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.
net//.default ] ParentRequestId:  ExpiresOn: 2021-12-02T03:43:11.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'xxxx', UserId: 'xxxxxxxxxx
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/496e4b40-e02c-4ab6-93cd-9ff246650a76/resourcegroups/r
g-eres-integration-prd/providers/microsoft.insights/alertrules?api-version=2016-03-01

Headers:
x-ms-client-request-id        : 40788a8c-3c6f-4ea5-99d2-3580dcb0167e
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-request-id               : 96943b8c-96d8-4ede-a596-a7aea46171fd
x-ms-correlation-request-id   : 96943b8c-96d8-4ede-a596-a7aea46171fd
x-ms-routing-request-id       : WESTUS3:20211202T023444Z:96943b8c-96d8-4ede-a596-a7aea46171fd
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 02 Dec 2021 02:34:43 GMT

Body:
{
  "value": []
}


DEBUG: AzureQoSEvent: Module: Az.Monitor:2.7.0; CommandName: Get-AzAlertRule; PSVersion: 5.1.190
41.1237; IsSuccess: True; Duration: 00:00:00.6160378
DEBUG: Finish sending metric.
DEBUG: 7:34:45 PM - GetAzureRmAlertRuleCommand end processing.

**Comment by dingmeng-xue** [comment]
@Hardingsa , according to service output, the response is empty. Could you double check your alert rule? Have you added alert rule to target resource?
