### ISSUE TITLE
New-AzStreamAnalyticsJob doesn't support creating and instance using managed identities

### ISSUE THREAD

**Issue by CCostaT** [Azure/azure-powershell#16572]
### Description

Version 6.0.0 introduced a breaking change to New-AzStreamAnalyticsJob so that it longer accepts the "-File" parameter and all input are specified in flattened parameters instead from the input file.

However, there's now no way to create a new Stream Analytics Job that uses system managed identities for authentication. I'm specifically refering to adding a parameter similar to **-SystemAssignedIdentity** and **-UserAssignedIdentity <String>** as is supported by **New-AzVM** and other cmdlets

### Issue script & Debug output

```PowerShell
none
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.6.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefa…
Script     2.0.0                 Az.StreamAnalytics                  {Get-AzStreamAnalyticsCluster, Get-AzStreamAnalyt…
```

### Error output

```PowerShell
none
```

edit: Made the description a little clearer

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We believe this inconsistency should be resolve by service side. I reply team member to look into it further.

**Comment by SaurabhSharma-MSFT** [comment]
@CCostaT Thanks for reporting. We are checking internally on this issue and get back to you.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@CCostaT You’re correct in that the `New-AzStreamAnalyticsJob` cmdlet doesn’t support the file parameter anymore, but `New-AzStreamAnalyticsInput` does. 

So, you need to create the job first and then use this [New-AzStreamAnalyticsInput](https://docs.microsoft.com/en-us/powershell/module/az.streamanalytics/new-azstreamanalyticsinput?view=azps-7.0.0) command to corelate the input to the job.
You can also use ARM templates to do the same thing as well. You can reference to [Deploy template - Azure portal - Azure Resource Manager](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/quickstart-create-templates-use-the-portal) and [azure-streamanalytics-cicd - npm](https://www.npmjs.com/package/azure-streamanalytics-cicd/v/2.2.1) which is specific for ASA.
Please let me know if you have any other questions.

Thanks
Saurabh

**Comment by CCostaT** [comment]
Hi @SaurabhSharma-MSFT thanks for getting back to me.

Yes `New-AzStreamAnalyticsInput` does indeed have support but my issues isn't that the file parameter is missing. Rather is that I can't create a StreamAnalytics Job that uses a `System managed identity` using Azure Powershell.

I can create inputs/outputs using `New-AzStreamAnalyticsInput/New-AzStreamAnalyticsOutput` with a system managed identiy but not the job itself.

The only workarounds I've found are:

- Through Terraform
- Through Azure Portal by creating the Stream Analytics Job manualy (which, for some reason, defaults to using a System Managed Identity):
![image](https://user-images.githubusercontent.com/48755988/145843372-d27d6475-519b-4d4e-b8ef-c2f339d95d7c.png)

Thanks
Tiago Costa

**Comment by SaurabhSharma-MSFT** [comment]
@CCostaT AFAIK When you create an input with system managed identity, it gets enabled on the job automatically. I do not think you need to do it again for the job. Please let me know if that's not the case and if you are seeing issues with it.

**Comment by SaurabhSharma-MSFT** [comment]
@CCostaT Please let me know if you still have any questions, else we will proceed with the closure of this case.

Thanks
Saurabh

**Comment by CCostaT** [comment]
I wasn't aware of that behaviour but that does indeed work. iI I create the job and the input through Azure Portal it works as you say and the job changes to use a system managed identity.

But I still can't get this working using powershell. Here's the script and datasource.json that I'm using:

script:
```powershell
New-AzStreamAnalyticsJob `
	-ResourceGroupName "myrg" `
	-Name "teste" `
	-Location "northeurope" `
	-SkuName "Standard" `
	-EventsLateArrivalMaxDelayInSecond 16 `
	-EventsOutOfOrderMaxDelayInSecond 5 `
	-EventsOutOfOrderPolicy "Drop" `
	-OutputErrorPolicy "Drop" `
	-DataLocale "en-US" `
	-CompatibilityLevel "1.2"
	
New-AzStreamAnalyticsInput `
	-File datasource.json `
	-JobName "teste" `
	-Name "blob-storage" `
	-ResourceGroupName "myrg"
```

datasource.json:
```json
{
  "name": "blob-storage",
  "type": "Microsoft.StreamAnalytics/streamingjobs/inputs",
  "properties": {
    "type": "Stream",
    "datasource": {
      "type": "Microsoft.Storage/Blob",
      "properties": {
        "sourcePartitionCount": 1,
        "storageAccounts": [
          {
            "accountName": "mystacc"
          }
        ],
        "container": "detelemetc",
        "pathPattern": "/dummy",
        "dateFormat": "yyyy/MM/dd",
        "timeFormat": "HH",
        "authenticationMode": "Msi"
      }
    },
    "compression": {
      "type": "None"
    },
    "partitionKey": "",
    "serialization": {
      "type": "Json",
      "properties": {
        "encoding": "UTF8"
      }
    }
  }
}
```

However, when I run this I get this error and now I'm not sure if this is the same bug or something else:
![image](https://user-images.githubusercontent.com/48755988/146596042-62ea4325-145b-47af-9a17-c55e80b38439.png)

When using a System Managed Identity, I shouldn't need to provide and account key correct?

**Comment by SaurabhSharma-MSFT** [comment]
@CCostaT Sorry for the delay.  I could see the same behavior and I think it shouldn't be asking you for the account key when you have added authentication mode.  I am checking internally on this one and get back to you.

**Comment by SaurabhSharma-MSFT** [comment]
@CCostaT I was able to get confirmation internally that it looks like a bug as it errors out when “accountKey” property is not provided and products team will internally work on fix. However, you can go past this error by adding the “accountKey” property to datasource.json like below-
![image](https://user-images.githubusercontent.com/38112130/152254546-b4b99102-8bbc-4799-aa8e-6f7d7a559bb8.png)
It shouldn’t matter what value you put in this field, because this information isn’t needed if you’re using MSI. So, you should be able to create the instance. Try rerunning the commands with the highlighted line added to datasource.json and let us know if you see any issues.

**Comment by SaurabhSharma-MSFT** [comment]
@CCostaT I have received a confirmation that the PS team is working on updating our PS cmdlets, which includes this fix. Potential ETA is early April. Thanks.

**Comment by CCostaT** [comment]
Hi @SaurabhSharma-MSFT , thank you for the feedback. I'll give it another go once the fix is released.

**Comment by dingmeng-xue** [comment]
@LucasYao93 , please check whether upcoming version of Az.StreamAnalyticsJob supports managed identities.

**Comment by SaurabhSharma-MSFT** [comment]
@CCostaT Can you please validate this with the new version of Az.StreamAnalyticsJob and let me know in case any issues.

**Comment by CCostaT** [comment]
Hi @SaurabhSharma-MSFT  sorry for the delay.

Yes the latest version seems to have fixed the issue. Everything seems to be working fine so I'll close this issue.

Thank you for your help!
