### ISSUE TITLE
[Feature]: Set-AzAksCluster to update a cluster's API server authorized IP ranges

### ISSUE THREAD

**Issue by JamesDLD** [Azure/azure-powershell#16575]
### Description of the new feature

The objective here is to update an AKS cluster's API server authorized IP ranges with **PowerShell** through the module [Az.Aks](https://www.powershellgallery.com/packages/Az.Aks).

To update the API server authorized IP ranges on an existing cluster, we can use [az aks](https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges?WT.mc_id=DOP-MVP-5003548#update-a-clusters-api-server-authorized-ip-ranges) update command and use the --api-server-authorized-ip-ranges,--load-balancer-outbound-ip-prefixes*, --load-balancer-outbound-ips, or--load-balancer-outbound-ip-prefixes* parameters.

### Proposed implementation details (optional)

 Set-AzAksCluster -ResourceGroupName "myResourceGroup" -Name "myAKSCluster" -ApiServerIpAddressRange @("73.140.245.0/24")

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will evaluate this feature.
