### ISSUE TITLE
[FunctionApp creation] Remove Preview flag from PowerShell on Linux function apps in V4

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-powershell#16587]
### Description

N/A

### Issue script & Debug output

```PowerShell
N/A
```

### Environment data

```PowerShell
N/A
```

### Module versions

```PowerShell
N/A
```

### Error output

```PowerShell
N/A
```

**Comment by msJinLei** [comment]
Released in https://www.powershellgallery.com/packages/Az.Functions/4.0.1

**Comment by Francisco-Gamino** [comment]
Thank you @msJinLei !
