### ISSUE TITLE
What's the difference between 1.1.0 and 1.1.0?

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1659]
That's not a typo. There appear to be two releases, both of which reference AzureRM. What is the difference between the two releases? Is one supposed to be Service Management, and one ARM? The release notes for the first one reference ARM cmdlets, but the release notes for the second one don't. It just says "published AzureRM." The first one has a MSI, whereas the second one does not. Does that mean AzureRM was pushed to the PowerShell Gallery, but ASM wasn't? I'm very confused.

Can someone disambiguate what's going on here?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

@hovsepm @devigned @markcowl 

![screen shot 2016-01-14 at 3 44 52 pm](https://cloud.githubusercontent.com/assets/466713/12340120/1a47a594-bad6-11e5-8dc8-43ed64073ac0.png)

**Comment by markcowl** [comment]
@pcgeek86 Hey Trevor,

Whenever you see a PowerShell release with a name that is only a version number, this is a combined msi and gallery release, that includes the latest versions of all modules.  If you see a release which starts with a gallery module name, that is just a release of that gallery module.

In this case, the AzureRm module was released separately, and the changes were only to update the version to avoid confusion for those wondering if the version of cmdlets in the gallery matched the msi.

-Mark
