### ISSUE TITLE
Remove-AzureWebsite doesn't remove the GitHub WebHook

### ISSUE THREAD

**Issue by kexuelou** [Azure/azure-powershell#166]
I am testing with Powershell for a customer issue. I created a lot sites which linked to same repository.

After that, I run this to remove all the sites. The sites were disappeared but the WebHook URLs left on GitHub.

$i= 0
while ( $i -lt 25)
{
  Remove-AzureWebsite -Name "wzhaotest${i}" -Force
  $i = $i + 1
}

Thanks,
Wei

**Comment by markcowl** [comment]
+1

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
