### ISSUE TITLE
[Doc]: https://docs.microsoft.com/en-us/powershell/module/az.imagebuilder/?view=azps-7.0.0

### ISSUE THREAD

**Issue by nicoride93** [Azure/azure-powershell#16609]
### Description

![image](https://user-images.githubusercontent.com/5413171/145433256-e157f766-bb51-40cd-9775-3cbd859f2d20.png)
There are a lot of "EdgeOrder" in the reference dropdown on the side

**Comment by dingmeng-xue** [comment]
Thanks for reporting. This issue is fixed.

@isra-fel please link this issue to pull request.
