### ISSUE TITLE
[Feature]: Search-AzGraph Query parameter support piping

### ISSUE THREAD

**Issue by wsmelton** [Azure/azure-powershell#16601]
### Description of the new feature

`Search-AzGraph` support piping for the `-Query` parameter by pipeline property name allowing piping from `Get-AzResourceGraphQuery`.

```powershell
Get-AzResourceGraphQuery -ResourceGroupName myRg -Name specificquery | Search-AzGraph
```

### Proposed implementation details (optional)

Add `ValueFromPipelineByPropertyName` to the `Query` parameter definition for `Search-AzGraph`

**Comment by dingmeng-xue** [comment]
@dolauli , Please look into it.

**Comment by dolauli** [comment]
@wsmelton You are expected to see this change in our next release.
