### ISSUE TITLE
Cannot delete AzureAD Tenant

### ISSUE THREAD

**Issue by NAD-XYZ** [Azure/azure-powershell#16635]
### Description

Trying to delete an Azure tenant. Its been over a week All required checks are done. It shows a message to delete Enterprize applications. When i try to connect to azure PowerShell it shows a message that i have not authorized users to azure ad PowerShell and i am the global administrator.  Microsoft's support team has not been able to help. 

how can I delete this tenant?

 **Below is the output of Get-Module**
Binary     2.0.2.140  AzureAD                             {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredO...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.0.0.1    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...

### Environment data

```PowerShell
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
et-Module : A parameter cannot be found that matches parameter name 'AZ*'.
At line:1 char:12
+ Get-Module -AZ*
+            ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetModuleCommand
```

### Error output

```PowerShell
Resolve-AzError : The term 'Resolve-AzError' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Resolve-AzError
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Resolve-AzError:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by NAD-XYZ** [comment]
@sdwheeler if you could help ? I am stuck

**Comment by sdwheeler** [comment]
I don't support the AzPS content. However, the proper command is to get a list of modules is: 
```
Get-Module -ListAvailable AZ*
```

cc: @mikefrobbins / @dcaro
