### ISSUE TITLE
[Feature]: Add cmdlet support for appending data to existing append blobs

### ISSUE THREAD

**Issue by beroder** [Azure/azure-powershell#16647]
### Description of the new feature

Currently, there is no way to append data to an existing append blob.  Ask is to add support for it since we have support for it in the REST API (Append Block).  REST API reference:

https://docs.microsoft.com/en-us/rest/api/storageservices/append-block

**Comment by dingmeng-xue** [comment]
Hi @beroder  , Please provide the link of REST API reference.

**Comment by blueww** [comment]
Azure PowerShell currently doesn’t have a cmdlet to append data to an existing append blob, but user can do it by call SDK API in Powershell.

Following sample shows how to append from a file stream (the append block must <= 4MB).
```powershell
$blob = Get-AzStorageBlob -Container $containerName -Blob $blobname  -Context $ctx 

$fs = [System.IO.File]::OpenRead("C:\temp\testfile_2048K")
$blob.BlobBaseClient.AppendBlock($fs)
$fs.Close() 
```

We will evaluate if need a cmdlet to append block to existing blob.
