### ISSUE TITLE
[Feature]: Add Resource Group Name property to the output of Get-AzConnectedMachine

### ISSUE THREAD

**Issue by cblackuk** [Azure/azure-powershell#16653]
### Description of the new feature

When you query for Virtual Machines using `Get-AzConnectedMachine` there is no Resource Group property returned and you need to resort to extrapolating it from ID.

Example:
```powershell
$VM = Get-AzConnectedMachine
($VM.Id -split "/")[4]
```

The Resource Group is missing here -> https://github.com/Azure/azure-rest-api-specs/blob/main/specification/hybridcompute/resource-manager/Microsoft.HybridCompute/stable/2021-05-20/HybridCompute.json#L782

The Resource Group can be obtained via:

```powershell
 Get-AzResource -ResourceType "Microsoft.HybridCompute/machines" -Name "VMName"
```
It is in the property `ResourceGroupName`.

Can we please add `ResourceGroupName` to the property to the output of `Get-AzConnectedMachine`? You need it for literally any other interaction with Azure Resource Manager, and if you want to do any other automation with Azure Arc - you will have to resort to either split or direct resource query.

### Proposed implementation details (optional)

I would like to see it being added as property here -> https://github.com/Azure/azure-rest-api-specs/blob/main/specification/hybridcompute/resource-manager/Microsoft.HybridCompute/stable/2021-05-20/HybridCompute.json#L782

**Comment by navba-MSFT** [comment]
@cblackuk Apologies for the late reply. We are looking into this issue and we will provide an update once we get more details on this.
@rpsqrd @edyoung Could you please look into this feature request once you get a chance ? Awaiting your reply.

**Comment by cblackuk** [comment]
No worries :D thanks for looking into it :-)

**Comment by rpsqrd** [comment]
@cblackuk thanks for the feedback! We'll take a look at this and get back to you.

**Comment by navba-MSFT** [comment]
@rpsqrd Could you please let us know if you had any update on this ? Awaiting your reply.

**Comment by rpsqrd** [comment]
We have a developer investigating how to add the resource group parameter this sprint. It should be in our next set of cmdlet updates.
________________________________

**Comment by rpsqrd** [comment]
This will be fixed with #18268

**Comment by vedkale** [comment]
@cblackuk the change has been published, you can download the latest CLI to access ResourceGroupName property.

**Comment by cblackuk** [comment]
Thank you so much for taking my feedback onboard and fixing it :-)
