### ISSUE TITLE
ARM template deployment didn't report error when adding azure sql database LTR policy if the db auto-pause enabled

### ISSUE THREAD

**Issue by qingshanJBHIFI** [Azure/azure-powershell#16663]
### Description

we have a azure sql database using the serverless tier in UAT, and the auto-pause is enabled; the prod is using Business critical tier. I set up in the ARM template to deploy the backup long term retention policy differently for each environment. This is I set for UAT: 
```
{
  "weeklyRetention": "PT0S",
  "monthlyRetention": "PT0S",
  "yearlyRetention": "PT0S",
  "weekOfYear": 1
}
```
I deployed to UAT with `New-AzResourceGroupDeployment`, it indicates the deployment succeed, but I can't see the LTR settings in azure portal.
but when I try to deploy LTR with [azure cli,](https://docs.microsoft.com/en-us/azure/azure-sql/database/long-term-backup-retention-configure?tabs=azure-cli#create-long-term-retention-policies) it gave me error saying `the LTR deployment is  no support when auto-pause is enabled.`

The arm template deployment should show the same error.

### Issue script & Debug output

```PowerShell
...//initialization

$createEnvironmentDeploymentParameters = @{
    Name = "deployment$((Get-Date).ToString('-yyyyMMdd-HHmmss-'))$((New-Guid).Guid.Substring(0, 4))"
    ResourceGroupName = $resourceGroupName
    TemplateFile = $templatePath
    TemplateParameterFile = $temporaryParametersFile
    SkipTemplateParameterPrompt = $true
    Force = $true
}
New-AzResourceGroupDeployment @createEnvironmentDeploymentParameters | Out-Null
```

### Environment data

```PowerShell
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands 
---------- -------    ---------- ----                                ---------------- 
Script     2.6.0                 Az.Accounts                         {Add-AzEnvironme…
Script     3.6.0                 Az.KeyVault                         {Add-AzKeyVaultC…
Script     4.4.0                 Az.Resources                        {Add-AzADGroupMe…
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Please share us the debug log. You can turn on it via `$DebugPreference = "Continue"` before `New-AzResourceGroupDeployment`. The log of deployment is very big, You can share the first and last HTTP request and response and ignore others.

In addition, this sounds a service issue. It will be more efficient if you can contact MS support with log above.

**Comment by qingshanJBHIFI** [comment]
I can't delete the LTR settings from azure portal anymore, so I can't reproduce the issue again. not sure there was something fixed in azure portal.
