### ISSUE TITLE
[Feature]: Get-AzStorageShareStatistics

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#16662]
### Description of the new feature

Need to get file share statistics, especially ShareUsageInBytes, to quickly assess share sizes.

This is visible in Azure storage explorer:
![image](https://user-images.githubusercontent.com/15258962/146426713-9605ddb2-be24-4523-90f0-ea84133af61a.png)

### Proposed implementation details (optional)

Should Call this API
https://docs.microsoft.com/en-us/rest/api/storagerp/file-shares/get#getsharestats

Should return this object:
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.models.sharestatistics?view=azure-dotnet

### Workaround
```powershell
using namespace Microsoft.Azure.Commands.Management.Storage.Models
function Get-AzStorageShareStatistics {
  <#
    .SYNOPSIS
    Retrieves statistics related to the share. Of specific importance is the shareUsageBytes property
    .EXAMPLE
    $storageAccount = Get-AzStorageAccount -ResourceGroupName 'test' -Name 'test'
    $storageAccount | Get-AzStorageShareStatistics -ShareName 'share1'
    
    accessTierChangeTime : 10/20/2021 5:56:20 AM
    signedIdentifiers    : {}
    leaseState           : available
    accessTier           : TransactionOptimized
    lastModifiedTime     : 10/20/2021 5:56:20 AM
    leaseStatus          : unlocked
    metadata             : {cloudseedingprovider}
    shareQuota           : 5120
    shareUsageBytes      : 3585220050
    .OUTPUTS
    AzStorageShareStatistics
  #>
  [CmdletBinding()]
  param(
    [Parameter(Mandatory,ValueFromPipeline)][string]$ShareName,
    [Parameter(Mandatory,ValueFromPipeline)][PSStorageAccount]$StorageAccount
  )
  process {
    $Path = @(
      $storageAccount.Id
      "/fileServices/default/shares/$ShareName"
      '?api-version=2021-04-01&$expand=stats'
    ) -join ''

    $response = Invoke-AzRestMethod -Path $Path
    $result = ($response.content | ConvertFrom-Json -AsHashtable).properties
    $result.PSTypeName = 'AzStorageShareStatistics'
    return [PSCustomObject]$result
  }
}
```

**Comment by blueww** [comment]
Powershell already support it with management plane cmdlet "Get-AzRmStorageShare",  see detail in https://docs.microsoft.com/en-us/powershell/module/az.storage/get-azrmstorageshare?view=azps-7.0.0#example-4--get-a-storage-file-share-with-the-share-usage-in-bytes

**Comment by JustinGrote** [comment]
Totally missed it, thank you!
