### ISSUE TITLE
[Doc]: Set-AzBlueprintArtifact

### ISSUE THREAD

**Issue by OursonBleu** [Azure/azure-powershell#16672]
### Description

Examples of use cases for Set-AzBlueprintArtifact uses New-AzBlueprintArtifact instead.

Full doc:
https://docs.microsoft.com/en-us/powershell/module/az.blueprint/set-azblueprintartifact?view=azps-7.0.0

Direct link to examples:
https://docs.microsoft.com/en-us/powershell/module/az.blueprint/set-azblueprintartifact?view=azps-7.0.0#examples

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We believe this inconsistency should be resolve by service side. I reply team member to look into it further.
