### ISSUE TITLE
Cannot connect after following directions

### ISSUE THREAD

**Issue by breyed** [Azure/azure-powershell#16705]
### Description

Azure PowerShell fails its basic out-of-box experience.

### Repro
1. Follow the install instructions.
2. Execute `Connect-AzAccount`.

### Error message
> Connect-AzAccount: The term 'Connect-AzAccount' is not recognized as a name of a cmdlet, function, script file, or executable program.

### More detail on repro step 1
These are the install instructions: [Install the Azure Az PowerShell module](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps). They say that from a PowerShell 7.2.1 prompt, you should enter:

```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
```
Just two steps. Awesome. Only it doesn't work. :-(

### Issue script & Debug output

```PowerShell
PS> $DebugPreference='Continue'
PS> Connect-AzAccount
Connect-AzAccount: The term 'Connect-AzAccount' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     4.6.0                 AzureRM.Profile                     {Add-AzureRmEnvironment, Clear-AzureRmContext, Clear-AzureRmDefault, Connect-AzureRmA…
```

### Error output

```PowerShell
Resolve-AzError: The term 'Resolve-AzError' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by alexandair** [comment]
It doesn't look like you have the "Az" module installed.
What do you get when you run:

```powershell
Get-Module az -ListAvailable
```

**Comment by dingmeng-xue** [comment]
Hi @breyed , you need to install Az module via `Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force`. If possible, please delete AzureRM.Profile from your environment. It is previous generation of Azure PowerShell module. Az and AzureRM loaded together may have problem.

**Comment by breyed** [comment]
Before following the installation instructions, I started with a new Windows 11 installation with Visual Studio 17.0 with the web and desktop workflows included. Perhaps the VS install caused the obsolete AzureRM.Profile to be installed.

The Azure PowerShell instructions should include whatever commands are necessary to transition from an arbitrary state (especially a mainstream state like a clean install of VS) to a viable state for running Azure PowerShell. 

I uninstalled Azure PowerShell using appwiz.cpl and tried `Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force` again. This time `Connect-AzAccount` worked. Not sure why. I think I installed Azure PowerShell from MSI in the meantime. In any case, I can't repro any more, so I'm going to close this. However, if someone is able to repro using a clean VS install on a new user profile, feel free to reopen.

**Comment by dcaro** [comment]
@mikefrobbins let's add some clarification in our instructions.
