### ISSUE TITLE
Set-AzVMOperatingSystem won't work for existing VMs

### ISSUE THREAD

**Issue by KMoraz** [Azure/azure-powershell#16711]
### Description

This might be a documentation error, as [official docs](https://docs.microsoft.com/en-us/powershell/module/az.compute/set-azvmoperatingsystem?view=azps-7.0.0) doesn't explicitly specify that `Set-AzVMOperatingSystem` cmdlet intended for new VMs and won't work for existing ones. The examples also target new VMs.

### Issue script & Debug output

```PowerShell
$vm = Get-AzVM -ResourceGroupName "someRG" -VMName "someVM"

# Running VM has DisablePasswordAuthentication=false, try to revert that:
Set-AzVMOperatingSystem -VM $vm -Linux -ComputerName $vm.OSProfile.ComputerName -Credential $cred -DisablePasswordAuthentication

# Refresh current configuration
(Get-AzVM -ResourceGroupName $vm.ResourceGroupName -VMName $vm.Name).OSProfile.LinuxConfiguration.DisablePasswordAuthentication

# output: False
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22523
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Name         Version
----         -------
Az.Accounts  2.2.3
Az.Compute   4.8.0
Az.Resources 3.1.1
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We believe this inconsistency should be resolve by service side. I reply team member to look into it further.

**Comment by SaurabhSharma-MSFT** [comment]
@KMoraz Thanks for your feedback. You are correct, and the cmdlet `Set-AzVMOperatingSystem` is not working setting up linux properties.  I am working internally on the same and update the documentation as required.

**Comment by SaurabhSharma-MSFT** [comment]
@KMoraz I have got the confirmation and this command is intended to be used on local VM objects to update OS properties before VM creation. This is by design and we cannot modify OS properties after the creation of the VM using this command.

**Comment by KMoraz** [comment]
@SaurabhSharma-MSFT I assumed that was the case, which is why I indicated that it was probably a documentation error.

Subtitle should be: _Sets operating system properties during creation of a new virtual machine._

**Comment by SaurabhSharma-MSFT** [comment]
@KMoraz Thanks for your suggestions. I have submitted PR to update the documentation.
