### ISSUE TITLE
Get-AzADUser in Az.Accounts 2.7.0 doesn't return non-default user properties

### ISSUE THREAD

**Issue by PhilJVW** [Azure/azure-powershell#16721]
### Description

With the change to Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphUser as output of Get-AzADUser in Az.Accounts 2.7.0 the command returns only default properties. 

Even with Get-AzADUser -First 10 **-Select 'City' -AppendSelected** as described in https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azaduser?view=azps-7.0.0 the command does not return City. 

It seems to ignore all properties except of standard props: DisplayName, Id,Mail,UserPrincipalName

### Issue script & Debug output

```PowerShell
PS> Get-AzADUser -UserPrincipalName first.last@mydomain.com

DisplayName     Id                                   Mail                      UserPrincipalName
-----------     --                                   ----                      -----------------
Last, First 5e252326-e6d2-4238-895f-1klae3d733a first.last@mydomain.com first.last@mydomain.com

PS> Get-AzADUser -UserPrincipalName first.last@mydomain.com -AppendSelected -Select 'userType'

DisplayName     Id                                   Mail                      UserPrincipalName
-----------     --                                   ----                      -----------------
Last, First 5e252326-e6d2-4238-895f-1klae3d733a first.last@mydomain.com first.last@mydomain.com
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefa…
Script     5.1.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec,
```

### Error output

```PowerShell
Resolve-AzError
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. The return of PowerShell is object. Default output format `format-table` only shows pre-defined columns. Please use  `Get-AzADUser -UserPrincipalName first.last@mydomain.com -AppendSelected -Select 'userType' | format-list` to show all properties.

**Comment by PhilJVW** [comment]
> Thanks for reporting. The return of PowerShell is object. Default output format `format-table` only shows pre-defined columns. Please use `Get-AzADUser -UserPrincipalName first.last@mydomain.com -AppendSelected -Select 'userType' | format-list` to show all properties.

That works well. Thank you. Maybe you want to consider updating the documentation accordingly.

**Comment by dingmeng-xue** [comment]
Thanks @PhilJVM . We will improve the experience and documentation. Close this issue now.
