### ISSUE TITLE
[Eng]: Artifacts migration issue from Jfrog to Azure Devops artifactory

### ISSUE THREAD

**Issue by Ranganathbj** [Azure/azure-powershell#16722]
### Description

I have been working on JFROG artifacts migration to my Azure Devops artifactory. I am using 

Powershell Move-MyGetNuGetPackages -SourceIndexUrl 'https://xyz.jfrog.io/artifactory/' -DestinationIndexUrl 'https://pkgs.dev.azure.com/xyz/_packaging/xyz/nuget/v3/index.json' -DestinationPAT 'xyz' -DestinationFeedName 'xyz' -SourceUsername 'xyz@gmail.com' -SourcePassword $Secure_String_Pwd -Verbose

Which is showing lot many errors. I tried everything best to my knowledge, it shows module is not correct! 

I have been following the below steps: https://github.com/lubas569/-lubas569-azure-devops-docs./blob/a830c3f1c30feb904f95e1109477a965cc61a5ee/docs/artifacts/tutorials/migrate-packages.md

Nothing is working. I am looking for extensions also, no useful extensions are available to migrate artifacts from one repo to another repository.

Please have a look at this issue and help me with the resolution.

Please find the below error messages: 

Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
At C:\Users\ranga\OneDrive\Documents\WindowsPowerShell\Modules\AzureArtifactsPackageMigration\1.0.1\Module\MyGetPackage
Migration.psm1:770 char:5
+     $process.Start() | Out-Null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : Win32Exception

Exception calling "WaitForExit" with "0" argument(s): "No process is associated with this object."
At C:\Users\ranga\OneDrive\Documents\WindowsPowerShell\Modules\AzureArtifactsPackageMigration\1.0.1\Module\MyGetPackage
Migration.psm1:771 char:5
+     $process.WaitForExit()
+     ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

You cannot call a method on a null-valued expression.
At C:\Users\ranga\OneDrive\Documents\WindowsPowerShell\Modules\AzureArtifactsPackageMigration\1.0.1\Module\MyGetPackage
Migration.psm1:773 char:5
+     $return = [pscustomobject]@{
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
At C:\Users\ranga\OneDrive\Documents\WindowsPowerShell\Modules\AzureArtifactsPackageMigration\1.0.1\Module\MyGetPackage
Migration.psm1:770 char:5
+     $process.Start() | Out-Null
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : Win32Exception

Exception calling "WaitForExit" with "0" argument(s): "No process is associated with this object."
At C:\Users\ranga\OneDrive\Documents\WindowsPowerShell\Modules\AzureArtifactsPackageMigration\1.0.1\Module\MyGetPackage
Migration.psm1:771 char:5
+     $process.WaitForExit()
+     ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

You cannot call a method on a null-valued expression.
At C:\Users\ranga\OneDrive\Documents\WindowsPowerShell\Modules\AzureArtifactsPackageMigration\1.0.1\Module\MyGetPackage
Migration.psm1:773 char:5
+     $return = [pscustomobject]@{

New-Object : Exception calling ".ctor" with "2" argument(s): "Cannot process argument because the value of argument
"password" is null. Change the value of argument "password" to a non-null value."
At C:\Users\ranga\OneDrive\Documents\WindowsPowerShell\Modules\AzureArtifactsPackageMigration\1.0.1\Module\MyGetPackage
Migration.psm1:112 char:29
+ ... redential = New-Object -TypeName pscredential -ArgumentList $SourceUs ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

At the end it says: Found 0 package versions in source, 2379 package versions in destination, and 0 packages versions need to be copied

Please help me with this at the earliest

**Comment by dingmeng-xue** [comment]
Hi @Ranganathbj , your question is to PowerShell module `AzureArtifactsPackageMigration` which is not owned by this repo. Please contact owner via PowerShell Gallery. https://www.powershellgallery.com/packages/AzureArtifactsPackageMigration/1.0.1/ContactOwners

**Comment by Ranganathbj** [comment]
I contacted the owner of this powershell module  "CoffeeChaser."  No response!

**Comment by dingmeng-xue** [comment]
Sorry @Ranganathbj . I cannot find who is CoffeeChaser in corporate. You can see the latest version of module released 2 years ago. I have to close this issue now.

If you have any question to Azure PowerShell, please contact us.
