### ISSUE TITLE
[AKS] Typo error on networkpolicy that block new-azakscluster to set network policy

### ISSUE THREAD

**Issue by spotet** [Azure/azure-powershell#16733]
### Description

Hi,

I have been working on AKS Cluster and want to set NetworkPolicy with the cmdlet New-AzAksCluster like :

New-AzAksCluster -ResourceGroupName xxx -Name yyy -NetworkPlugin azure -NetworkPolicy calico ....

NetworkPolicy is never set. Just check the new code push, and there an error here :

private ContainerServiceNetworkProfile GetNetworkProfile()
        {
            var networkProfile = new ContainerServiceNetworkProfile();
            networkProfile.NetworkPlugin = NetworkPlugin;
            networkProfile.LoadBalancerSku = LoadBalancerSku;
            var networkProfile = new ContainerServiceNetworkProfile
            {
                NetworkPlugin = NetworkPlugin,
                LoadBalancerSku = LoadBalancerSku
            };
            if (this.IsParameterBound(c => c.NodeMinCount))    <============== 
            {
                networkProfile.NetworkPolicy = NetworkPolicy;
            }
            if (this.IsParameterBound(c => c.PodCidr))
            {
                networkProfile.PodCidr = PodCidr;
            ........

"NetworkPolicy" is replace by "NodeMinCount". If i add NodeMinCount parameter, networkpolicy is set to my cluster.

Sébastien POTET

### Issue script & Debug output

```PowerShell
Error in code, no output
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.0.0      Az.Aks                              {Get-AzAksCluster, New-AzAksCluster, ...
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting.

@wyunchi-ms , please fix this issue. 

https://github.com/Azure/azure-powershell/blob/7fa2066acf55a2c6d69eaddf3c4c2d382e3f704f/src/Aks/Aks/Commands/NewAzureRmAks.cs#L383-L386
