### ISSUE TITLE
Can Set-AzLogicApp take both -ParameterFilePath AND -Parameters?

### ISSUE THREAD

**Issue by owingruters** [Azure/azure-powershell#16740]
### Description

Hi ,

I wan to deploy a logicApp. I want to use parameters from a parematers file, but a few parameters I want to set in a pipeline. Hence I'd like to use Set-AzLogicApp with  -ParameterFilePath AND -Parameters. 
However I get now an error that a parameter that is in the parameters object and not in the file is not provided:
"Set-AzLogicApp : The template validation failed: 'The value for the workflow parameter 'ActionSecurityHeader' at line '1' and column '503' is not
provided.'."  
(If I provide evenryting in the file, there is no error)

Should this be possible, of can I only use either a file or an object? If now -> feature request. If so, any idea why this is failing for me

Regards

### Script or Debug output

```PowerShell
PS C:\> Set-AzLogicApp -ResourceGroupName "BRS-GLB-IENO-NEWECOM-DEV-RG01" -name aziewf-lea001 -DefinitionFilePath "C:\Repos\FE and MW\LogicApps\logicAppsDefinition.json" -ParameterFilePath "C:\Repos\FE and MW\LogicApps\logicAppsBOLeadParams-dev.json" -parameters $parameters -Force
Set-AzLogicApp : The template validation failed: 'The value for the workflow parameter 'ActionSecurityHeader' at line '1' and column '503' is not
provided.'.
At line:1 char:1
+ Set-AzLogicApp -ResourceGroupName "xxxxxxxxxx-DEV-RG01" -na ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzLogicApp], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.UpdateAzureLogicAppCommand
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.7.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     1.5.0      Az.LogicApp                         {Get-AzIntegrationAccount, Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly...
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We believe this inconsistency should be resolve by service side. I reply team member to look into it further.

**Comment by SatishBoddu-MSFT** [comment]
Hello @owingruters Sorry for the delayed response.

Wanted to check if you were trying to deploy a new LogicApp template or Modifying the existing LogicApp?

**Comment by SatishBoddu-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
