### ISSUE TITLE
[Doc]: src/ResourceManager/Compute/Commands.Compute/help/Grant-AzureRmSnapshotAccess.md

### ISSUE THREAD

**Issue by GeorgeH-MS** [Azure/azure-powershell#16757]
### Description

example doesn't match the cmdlet

**Comment by dingmeng-xue** [comment]
`Grant-AzureRmSnapshortAccess` is old version AzureRM cmdlet. Please reference the latest version https://github.com/Azure/azure-powershell/blob/main/src/Compute/Compute/help/Grant-AzSnapshotAccess.md
