### ISSUE TITLE
Update-AzureRM

### ISSUE THREAD

**Issue by SimonWahlin** [Azure/azure-powershell#1675]
Update-AzureRM forcefully installs and overwrites any module already installed each time it is run. This makes it take roughly 40 minutes to run each time.

Update-AzureRM should by default only download modules with a higher version than what is currently installed unless the parameter -Force is used. This should reduce the time to run to under 3 minutes when no updates are needed.

**Comment by markcowl** [comment]
@SimonWahlin Thanks for the good suggestion.  Assigning the task for evaluation.

**Comment by SimonWahlin** [comment]
Hi @markcowl
I don't want to push any pull requests on you, but I made a suggested simple solution here:
https://github.com/SimonWahlin/azure-powershell/tree/Fix-Update-AzureRM

**Comment by hovsepm** [comment]
@SimonWahlin please create a PR to dev branch of the azure-powershell repo and we will be happy to take in your contribution.

**Comment by hovsepm** [comment]
Fixed in dev branch. Will be available in the next release.
