### ISSUE TITLE
Az.Tools.Installer Scope

### ISSUE THREAD

**Issue by SQLCanuck** [Azure/azure-powershell#16768]
### Description

When executing the Install-AzModule command from an elevated Windows PowerShell session, the modules by default get installed to the CurrentUser instead of AllUsers as is normal Windows PowerShell module install behavior.

### Issue script & Debug output

```PowerShell
N/A
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name               
---------- -------    ----                  
Script     0.2.0      Az.Tools.Installer
```

**Comment by msJinLei** [comment]
hi @SQLCanuck, we have `Scope` for `Install-AzModule`. By default scope is set to `CurrentUser`. In your case, please specify `Scope` as `AllUsers` when run Install-AzModule.
The behaviour is consistent with `Install-Module` from PowerShellGet

**Comment by SQLCanuck** [comment]
@msJinLei Yes, that is the behavior with Install-Module when executed in a non-elevated Windows PowerShell session.  However, if Install-Module is executed in an elevated Windows PowerShell session it defaults to AllUsers, which is not the case for Install-AzModule.

**Comment by msJinLei** [comment]
> @msJinLei Yes, that is the behavior with Install-Module when executed in a non-elevated Windows PowerShell session. However, if Install-Module is executed in an elevated Windows PowerShell session it defaults to AllUsers, which is not the case for Install-AzModule.

@SQLCanuck We want to unify the behavior of  Az.Tools.Installer in PowerShell core and Windows Powershell. It would be easier to remember and use. Do you have any concern?

**Comment by SQLCanuck** [comment]
@msJinLei I understand wanting to unify between PowerShell and Windows PoweShell.  Though the reality is they are different and trying to avoid those differences may produce greater user confusion.  Ultimately, the choice of how to handle it is up to the Az.Tools.Installer team.  If you continue this course, please just be sure to fully document this unexpected behavior for Windows PowerShell.

**Comment by dingmeng-xue** [comment]
Let's update cmdlet help doc and ensure all user know the behavior. @msJinLei

**Comment by msJinLei** [comment]
Document updated https://github.com/Azure/azure-powershell/tree/main/tools/Az.Tools.Installer/help
