### ISSUE TITLE
Az AD cmdlets return a "Continuous Access Evaluation" error.

### ISSUE THREAD

**Issue by jameslj** [Azure/azure-powershell#16766]
### Description

Any calls for Azure AD Graph return a Continuous Access Evaluation error. Our Azure AD tenant does not have Continuous Access Evaluation preview enabled. If executed from the cloud shell, the command works.

### Issue script & Debug output

```PowerShell
❯ Get-AzADApplication -DisplayNameStartWith "cgbdaprgrecall" -debug
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
DEBUG: Client side pagination is enabled for this cmdlet
DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'Get-AzADApplication_List'
DEBUG: CmdletProcessRecordAsyncStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: /applications?$filter=startsWith%28DisplayName%2C%20%27cgbdaprgrecall%27%29
DEBUG: RequestCreated: /v1.0/applications?$filter=startsWith%28DisplayName%2C%20%27cgbdaprgrecall%27%29
DEBUG: HeaderParametersAdded:
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/applications?$filter=startsWith%28DisplayName%2C %27cgbdaprgrecall%27%29

Headers:
x-ms-unique-id                : 2
x-ms-client-request-id        : c29f7439-d2f2-4d94-8cf8-1fb888b883dc
CommandName                   : Az.MSGraph.internal\Get-AzADApplication
FullCommandName               : Get-AzADApplication_List
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v7.1.0,PSVersion/v7.2.1,Az.MSGraph/5.2.0

Body:



DEBUG: BeforeCall:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Unauthorized

Headers:
Date                          : Wed, 05 Jan 2022 12:30:20 GMT
Transfer-Encoding             : chunked
WWW-Authenticate              : Bearer realm="", authorization_uri="https://login.microsoftonline.com/common/oauth2/authorize", client_id="00000003-0000-0000-c000-000000000000", error="insufficient_claims", claims="eyJhY2Nlc3NfdG9rZW4iOnsibmJmIjp7ImVzc2VudGlhbCI6dHJ1ZSwidmFsdWUiOiIxNjQxMzg1ODIxIn0sInhtc19ycF9pcGFkZHIiOnsidmFsdWUiOiI6OmZmZmY6NDcuMjAwLjExLjg2In19fQ=="
Strict-Transport-Security     : max-age=31536000
request-id                    : 030a1de5-96d6-45af-aa67-e4625c538931
client-request-id             : 030a1de5-96d6-45af-aa67-e4625c538931
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"South Central US","Slice":"E","Ring":"5","ScaleUnit":"002","RoleInstance":"SN1PEPF00006480"}}

Body:
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Continuous access evaluation resulted in claims challenge with result: InteractionRequired and code: LocationConditionEvaluationSatisfied",
    "innerError": {
      "date": "2022-01-05T12:30:21",
      "request-id": "030a1de5-96d6-45af-aa67-e4625c538931",
      "client-request-id": "030a1de5-96d6-45af-aa67-e4625c538931"
    }
  }
}


DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:
Get-AzADApplication_List: C:\Users\jrlit\Documents\PowerShell\Modules\Az.Resources\5.2.0\MSGraph.Autorest\custom\Get-AzADApplication.ps1:206
Line |
 206 |      Az.MSGraph.internal\Get-AzADApplication @PSBoundParameters
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Continuous access evaluation resulted in claims challenge with result: InteractionRequired and code:
     | LocationConditionEvaluationSatisfied

DEBUG: [Finally]: Getting exception 'Microsoft.Azure.Commands.Common.Exceptions.AzPSCloudException: InternalException' from response
DEBUG: Finally:
DEBUG: CmdletAfterAPICall:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: AzureQoSEvent: Module: Az.MSGraph:5.2.0; CommandName: Get-AzADApplication_List; PSVersion: 7.2.1; IsSuccess: False; Duration: 00:00:00; Exception: InternalException;
DEBUG: Finish sending metric.
DEBUG: CmdletEndProcessing:
```

### Environment data

```PowerShell
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
❯ Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefa…
Script     5.2.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, G…
```

### Error output

```PowerShell
❯ Resolve-AzError
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 3

Message        : [InvalidAuthenticationToken] : Continuous access evaluation resulted in claims challenge with result:
                 InteractionRequired and code: LocationConditionEvaluationSatisfied
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Get-AzADApplication_List}
Line           :     Az.MSGraph.internal\Get-AzADApplication @PSBoundParameters

Position       : At C:\Users\jrlit\Documents\PowerShell\Modules\Az.Resources\5.2.0\MSGraph.Autorest\custom\Get-AzADAppl
                 ication.ps1:206 char:5
                 +     Az.MSGraph.internal\Get-AzADApplication @PSBoundParameters
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3


   HistoryId: 2

Message        : [InvalidAuthenticationToken] : Continuous access evaluation resulted in claims challenge with result:
                 InteractionRequired and code: LocationConditionEvaluationSatisfied
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Get-AzADApplication_List}
Line           :     Az.MSGraph.internal\Get-AzADApplication @PSBoundParameters

Position       : At C:\Users\jrlit\Documents\PowerShell\Modules\Az.Resources\5.2.0\MSGraph.Autorest\custom\Get-AzADAppl
                 ication.ps1:206 char:5
                 +     Az.MSGraph.internal\Get-AzADApplication @PSBoundParameters
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2
```

**Comment by dingmeng-xue** [comment]
@jameslj , according to the message from MSGraph, it indicates your tenant already enabled continuous access evaluation. 

It's the first time that we know MSGraph API supports this feature now. We will evaluate how to support it with priority.

**Comment by dingmeng-xue** [comment]
We start to evaluate supporting CAE of MSGraph API now since this sprint. It may not be completed within one month. We will keep this item updated.

**Comment by dbiegunski** [comment]
Get-AzureADApplicationProxyConnector was working fine yesterday and for some reason today I get an error from Continuous access evaluation.

Connect-AzureAD -MsAccessToken $MicrosoftComToken -AadAccessToken $WindowsNetToken -AccountId $AccountId -TenantId $TenantId
Get-AzureADApplicationProxyConnector

Get-AzureADApplicationProxyConnector : Error occurred while executing GetApplicationProxyConnectors 
Code: InvalidAuthenticationToken
Message: Continuous access evaluation resulted in claims challenge with result: InteractionRequired and code: LocationConditionEvaluationSatisfied
InnerError:
  RequestId: a23a404d-1f9f-4437-8e4a-700e10952277
  DateTimeStamp: Wed, 12 Jan 2022 20:12:17 GMT
HttpStatusCode: Unauthorized
HttpStatusDescription: Unauthorized
HttpResponseStatus: Completed
At D:\azure\final.ps1:9 char:1
+ Get-AzureADApplicationProxyConnector
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADApplicationProxyConnector], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphV10.Client.ApiException,Microsoft.Open.MSGraphV10.PowerShell.GetApplicationProxyConnector

**Comment by jameslj** [comment]
> @jameslj , according to the message from MSGraph, it indicates your tenant already enabled continuous access evaluation.
> 
> It's the first time that we know MSGraph API supports this feature now. We will evaluate how to support it with priority.
> 
> For the time being, could you check tenant configuration if CAE is not expected?

I verified with our security team that CAE is not enabled.

**Comment by msJinLei** [comment]
> > @jameslj , according to the message from MSGraph, it indicates your tenant already enabled continuous access evaluation.
> > It's the first time that we know MSGraph API supports this feature now. We will evaluate how to support it with priority.
> > For the time being, could you check tenant configuration if CAE is not expected?
> 
> @dingmeng-xue I verified with our security team that CAE is not enabled.

Hi @jameslj There is a simple way to check your MSGraphToken to double confirm the issue.

Please run the following cmdlet
```
(Get-AzAccessToken -ResourceTypeName MSGraph).Token
```
And then you can get your MSGraphToken

Use the `https://jwt.ms/` to check the token to wait the following clams.

![image](https://user-images.githubusercontent.com/54836179/149260356-a08592b2-74e2-4d00-9e35-20952df1436f.png)

![image](https://user-images.githubusercontent.com/54836179/149260420-c400e9bc-0ec3-406d-9dad-43e8f931605c.png)

**Comment by jameslj** [comment]
@dingmeng-xue yes, the audience is set to graph and the xms_cc claim is present with a value of CPI

![image](https://user-images.githubusercontent.com/5155208/149261017-9e07f1cb-5550-475d-abef-df3b2d535b99.png)

![image](https://user-images.githubusercontent.com/5155208/149261043-4fc3e57d-a570-4c8c-9158-62280f5ac0fc.png)

**Comment by jameslj** [comment]
@dingmeng-xue also, this occurs when I run az powershell from Windows Terminal, or using the graph sdk in .net. If I use the cloud shell from the Azure Portal, the xms_cc claim is not present in the token.

**Comment by msJinLei** [comment]
@jameslj could you run the following cmdlets in PowerShell and see whether the issue remains?
```
$env:AZURE_IDENTITY_DISABLE_CP1="true" 
Disconnect-AzAccount
Connect-AzAccount
```

**Comment by msJinLei** [comment]
@jameslj 
To find CP1 in your token shows that the CAE is enabled for MS graph in your tenant.
You can use env variable mentioned above to disable it in Azure-PowerShell side temporarily.

**Comment by msJinLei** [comment]
> Get-AzureADApplicationProxyConnector was working fine yesterday and for some reason today I get an error from Continuous access evaluation.
> 
> Connect-AzureAD -MsAccessToken $MicrosoftComToken -AadAccessToken $WindowsNetToken -AccountId $AccountId -TenantId $TenantId Get-AzureADApplicationProxyConnector
> 
> Get-AzureADApplicationProxyConnector : Error occurred while executing GetApplicationProxyConnectors Code: InvalidAuthenticationToken Message: Continuous access evaluation resulted in claims challenge with result: InteractionRequired and code: LocationConditionEvaluationSatisfied InnerError: RequestId: a23a404d-1f9f-4437-8e4a-700e10952277 DateTimeStamp: Wed, 12 Jan 2022 20:12:17 GMT HttpStatusCode: Unauthorized HttpStatusDescription: Unauthorized HttpResponseStatus: Completed At D:\azure\final.ps1:9 char:1
> 
> * Get-AzureADApplicationProxyConnector
> * ```
>     + CategoryInfo          : NotSpecified: (:) [Get-AzureADApplicationProxyConnector], ApiException
>     + FullyQualifiedErrorId : Microsoft.Open.MSGraphV10.Client.ApiException,Microsoft.Open.MSGraphV10.PowerShell.GetApplicationProxyConnector
>   ```

AzureAD is not a part of Azure-PowerShell. You may connect its author for more details.

Maybe you can also try `$env:AZURE_IDENTITY_DISABLE_CP1="true" `

**Comment by alexandair** [comment]
@msJinLei 
/cc @jameslj 

The question remains why is a behavior different in the locally installed Azure PowerShell and Cloud Shell.
When @jameslj runs a command in the Cloud Shell, he doesn't need to disable CP1.

**Comment by msJinLei** [comment]
@alexandair 
I believe cloud shell disables CAE

**Comment by alexandair** [comment]
@msJinLei 
You are right that a token in Cloud Shell doesn't contain xms_cc claim.
It's just not clear how it's disabled. Environment variable `AZURE_IDENTITY_DISABLE_CP1` is not set.

**Comment by msJinLei** [comment]
> @msJinLei You are right that a token in Cloud Shell doesn't contain xms_cc claim. It's just not clear how it's disabled. Environment variable `AZURE_IDENTITY_DISABLE_CP1` is not set.

@alexandair There are other ways to disable CAE https://github.com/msJinLei/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/CHANGELOG.md#new-features-2

**Comment by nsg74** [comment]
The easiest workaround for now is to create a new conditional access rule applying to **all cloud apps** but no other conditions, and under the **session** access controls set the **customise continuous access evaluation** to **disable**.  After disconnecting and re-connecting the az powershell session the commands ran without error for me.  You can disable/delete the conditional access rule when you're done.  Reference: https://www.vansurksum.com/2021/10/30/continuous-access-evaluation-configuration-is-now-part-of-conditional-access/

**Comment by msJinLei** [comment]
@jameslj @alexandair @nsg74 
We have released an engineering version of [Az.Accounts](https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.7.99.nupkg) which includes CAE support. You can download and try it.

You can install it using Az.Tools.Installer
```
Install-Module -Name Az.Tools.Installer -Repository PSGallery -RequiredVersion 0.2.0
Install-AzModule -Path https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.7.99.nupkg
```

Let us know if any feedback. Thanks

**Comment by msJinLei** [comment]
fixed in Az.Accounts 2.7.3
