### ISSUE TITLE
Unhelpful error messages / incorrect input values allowed when registering AzKeyVault with SecretManagement

### ISSUE THREAD

**Issue by DrDallas** [Azure/azure-powershell#16798]
### Description

Consider the following commands:

```Powershell

$myAZSecretStore = 'myAzKeyVault'

Install-Module -Name az -Verbose
Install-Module Microsoft.PowerShell.SecretManagement, Microsoft.PowerShell.SecretStore -Verbose

Connect-AzAccount # Connect; connection is successful.

$mySubscription = Get-AzSubscription | Select SubscriptionId # This is a problem; we'll see why later.

$myKeyVaultName = Get-AzKeyVault | select VaultName # This is a problem; we'll see why later.

Register-SecretVault -ModuleName Az.KeyVault -Name $myAZSecretStore -VaultParameters @{AZKVaultName = $myKeyVaultName; SubscriptionId = $mySubscription} -Verbose # No error messages returned

Test-SecretVault #Error message returned (see below)

```

The `Test-SecretValue` function returns:

> Test-SecretVault : To use System.Collections.Hashtable Azure vault, the current user must be logged into Azure account subscription

The problem is that `$mySubscription` is not a string, but, instead, a `Selected.Microsoft.Azure.Commands.Profile.Models.PSAzureSubscription`. and `$myKeyVaultName` is a `Selected.Microsoft.Azure.Commands.KeyVault.Models.PSKeyVaultIdentityItem`. `Register-SecretVault` should have returned some sort of error during registration because either (1) the registration failed or (2) incorrect data/data types were supplied.

When `$mySubscription` and `$myKeyVaultName` are strings with the appropriate values, then `Test-SecretVault` works as expected. This works:

```PowerShell
$mySubscription = Get-AzSubscription | Select -ExpandProperty SubscriptionId # This works

$myKeyVaultName = Get-AzKeyVault | select -ExpandProperty VaultName # This works
```

Either `Microsoft.PowerShell.SecretManagement` or `Az.KeyVault.Extension` should return some sort of error, or, at a minimum, `Test-SecretVault` should return better error messages during registration because, as is seen in the code example above, the current user was logged in to the Azure account subscription.

### Issue script & Debug output

```PowerShell
n/a 

The issue is that no error messages appear when incorrect data are entered. Refer to the description for details.
```

### Environment data

```PowerShell
Happens with 5.1 and 7.x

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22526
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version Name
---------- ------- ----
    Script 2.7.0   Az.Accounts
    Script 4.1.0   Az.KeyVault
```

### Error output

```PowerShell
n/a -- no errors are generated.
```

**Comment by dingmeng-xue** [comment]
@DrDallas , thanks for reporting.

We have one test example in Azure PowerShell repo https://github.com/Azure/azure-powershell/blob/e1c4b71350caecbc9af4173e4076a8435307094d/src/KeyVault/KeyVault.Test/ScenarioTests/SecretManagementExtensionTests.ps1#L34. 
Current Azure PowerShell online doc doesn't support this extension because there is no exact cmdlet mapping to it. 

We will consider to improve the message of error and give user more hint.

**Comment by BethanyZhou** [comment]
Hi @DrDallas , thank you for your reporting. 

we are intended to improve the error message as below:
![image](https://user-images.githubusercontent.com/19869716/149087077-14fc272d-a18c-4133-a9cd-7d813d750de8.png)

Is this kind of information helpful for you? Please feel free to let me know if you have any thoughts.
