### ISSUE TITLE
[Doc]: `New-AzADAppCredential` examples are incomplete or empty

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#16808]
### Description

[`New-AzADAppCredential`](https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azadappcredential) reference documentation has two issues: 

- Example 1 needs clarification how to set variables `$Id` and `$cert`
- Example 2 is empty

**Comment by dingmeng-xue** [comment]
I have updated the doc and provided information about those variables. Close this issue now.
