### ISSUE TITLE
New-AzWebAppSSLBinding is missing the -WhatIf parameter

### ISSUE THREAD

**Issue by owingruters** [Azure/azure-powershell#16816]
### Description of the new feature

Many/All cmdlets have a -WhatIf parameter, but is is missing for New-AzWebAppSSLBinding.

**Comment by Kotasudhakarreddy** [comment]
Thanks for your feedback!. Checking on it.

**Comment by Kotasudhakarreddy** [comment]
It requires a code fix. we will give the fix in our next release.
