### ISSUE TITLE
Help with error "The term 'processÂ' is not recognized as the name of a cmdlet"

### ISSUE THREAD

**Issue by obayesshelton** [Azure/azure-powershell#16839]
### Description

Hi,

I am having a lot of issues with Azure Automation and the docs are pretty useless at times. 

However, I am getting the following error which is not very helpful. Could you explain what is wrong with my script. 

### Script or Debug output

```PowerShell
Workflow test-02
{
    $resourceGroup = "DevApplication"

    # Ensures you do not inherit an AzContext in your runbook
    Disable-AzContextAutosave -Scope Process

    # Connect to Azure with system-assigned managed identity
    $AzureContext = (Connect-AzAccount -Identity).context

    # set and store context BYOB Azure
    $AzureContext = Set-AzContext -SubscriptionName $AzureContext.Subscription -DefaultProfile $AzureContext   

    Invoke-AzContainerInstanceCommand -ResourceGroupName DevApplication -ContainerGroupName byob-dev -ContainerName byob-dev-one -Command "date" -TerminalSizeCol 12 -TerminalSizeRow 12
}
```

### Error output

```PowerShell
Suspended
The term 'processÂ' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. (The term 'processÂ' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.)


PSComputerName        : localhost
PSSourceJobInstanceId : 83c663bd-d633-4c21-87ab-7000f574f4b5
Mode                  : Process
ContextDirectory      : 
ContextFile           : 
CacheDirectory        : 
CacheFile             : 
Settings              : {}
```

**Comment by obayesshelton** [comment]
Just to add when I run the command `Invoke-AzContainerInstanceCommand` on my Apple laptop. The PowerShell works:

```PS /Users/oliver/Projects/byobeta> Get-InstalledModule

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
3.0.0                Az.ContainerInstance                PSGallery            Microsoft Azure PowerShell: ContainerInstance cmdlets
2.7.1                Az.Accounts                         PSGallery            Microsoft Azure PowerShell - Accounts credential management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…

PS /Users/oliver/Projects/byobeta> Invoke-AzContainerInstanceCommand -ResourceGroupName DevApplication -ContainerGroupName byob-dev -ContainerName byob-dev-one -Command "touch /tmp/foooo.txt"```

This does now work in Azure Automation Run Books.

**Comment by obayesshelton** [comment]
Interestingly for anyone reading this. If I use PowerShell Runbook with Runtime set to 7.1 (Preview) the script works.

**Comment by obayesshelton** [comment]
So the command:

`Invoke-AzContainerInstanceCommand -ResourceGroup "DevApplication" -ContainerGroupName "byob-feature-product-engine" -ContainerName "byob-feature-product-engine-one" -Command "touch /tmp/bar.txt" -TerminalSizeCol 1 -TerminalSizeRow 1` 

Now has stopped working with Runtime set to 7.1 (preview) the command works on Powershell on my Apple Terminal but not via Runbook in Azure Automation. I get no error or response. 

This is a pretty frustrating experience.

**Comment by dingmeng-xue** [comment]
Thanks for contacting us. I suspect it is related to the encoding of PowerShell or CloudShell setting because of message "The term 'processÂ' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. (The term 'processÂ' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.)"

In addition, you can check whether the encoding of your script is expected. Or it may contains special characters.

**Comment by obayesshelton** [comment]
This seems to work now on Runtime 7.1 and updates modules.
