### ISSUE TITLE
[Doc]: https://docs.microsoft.com/en-us/powershell/module/az.network/set-azapplicationgatewayfirewallpolicy?view=azps-7.1.0

### ISSUE THREAD

**Issue by durayakar** [Azure/azure-powershell#16840]
### Description

The example has an invalid parameter. 

$UpdatedAppGwFirewallPolicy = Set-AzApplicationGatewayFirewallPolicy -ApplicationGateway $AppGwFirewallPolicy

There is no "ApplicationGateway" parameter for this command.

**Comment by MughundhanRaveendran-MSFT** [comment]
@durayakar , Thanks for reporting this issue. I will check and get back to you

**Comment by MughundhanRaveendran-MSFT** [comment]
@durayakar , The correct parameter should be -InputObject . I have updated the document, it will be published soon.
