### ISSUE TITLE
"The term 'processÂ' is not recognized as the name of a cmdlet"

### ISSUE THREAD

**Issue by obayesshelton** [Azure/azure-powershell#16846]
### Description

Hi,

I am having a lot of issues with Azure Automation and the docs are pretty useless at times. 

However, I am getting the following error which is not very helpful. Could you explain what is wrong with my script. 

### Issue script & Debug output

```PowerShell
Workflow test-02
{
    $resourceGroup = "DevApplication"

    # Ensures you do not inherit an AzContext in your runbook
    Disable-AzContextAutosave -Scope Process

    # Connect to Azure with system-assigned managed identity
    $AzureContext = (Connect-AzAccount -Identity).context

    # set and store context BYOB Azure
    $AzureContext = Set-AzContext -SubscriptionName $AzureContext.Subscription -DefaultProfile $AzureContext   

    Invoke-AzContainerInstanceCommand -ResourceGroupName DevApplication -ContainerGroupName byob-dev -ContainerName byob-dev-one -Command "date" -TerminalSizeCol 12 -TerminalSizeRow 12
}
```

### Environment data

```PowerShell
N/A
```

### Module versions

```PowerShell
Az.ContainerInstance
Last modified: 1/14/2022, 4:06 PM
Module version: 3.0.0
Runtime version: 5.1
Size: 586.487 KB
Type: Custom
```

### Error output

```PowerShell
Suspended
The term 'processÂ' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. (The term 'processÂ' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.)


PSComputerName        : localhost
PSSourceJobInstanceId : 83c663bd-d633-4c21-87ab-7000f574f4b5
Mode                  : Process
ContextDirectory      : 
ContextFile           : 
CacheDirectory        : 
CacheFile             : 
Settings              : {}
```

**Comment by obayesshelton** [comment]
Interestingly for anyone reading this. If I use PowerShell Runbook with Runtime set to 7.1 (Preview) the script works.

**Comment by obayesshelton** [comment]
So the command:

`Invoke-AzContainerInstanceCommand -ResourceGroup "DevApplication" -ContainerGroupName "byob-feature-product-engine" -ContainerName "byob-feature-product-engine-one" -Command "touch /tmp/bar.txt" -TerminalSizeCol 1 -TerminalSizeRow 1` 

Now has stopped working with Runtime set to 7.1 (preview) the command works on Powershell on my Apple Terminal but not via Runbook in Azure Automation. I get no error or response. 

This is a pretty frustrating experience.

**Comment by dingmeng-xue** [comment]
@obayesshelton , sorry for the late response. Could you turn on debug `$DebugPreference = "Continues"` and share debug information? 

In addition, could you share how container instance is created? what base image is used?

**Comment by obayesshelton** [comment]
@dingmeng-xue that didn't make any difference. Sorry. This is my code

```# Ensures you do not inherit an AzContext in your runbook
Disable-AzContextAutosave -Scope Process

# Connect to Azure with system-assigned managed identity
$AzureContext = (Connect-AzAccount -Identity).context

# set and store context
$AzureContext = Set-AzContext -SubscriptionName $AzureContext.Subscription -DefaultProfile $AzureContext   

$DebugPreference = "Continues"

Invoke-AzContainerInstanceCommand -ContainerGroupName byob-dev -ContainerName byob-dev-one -ResourceGroupName DevApplication -Command "npm run script_daily_prices"```

**Comment by obayesshelton** [comment]
@dingmeng-xue hopefully this is how you expected me to use `$DebugPreference = "Continues"`

**Comment by dingmeng-xue** [comment]
Sorry. there is a typo. It should be `$DebugPreference = "Continue"`. Then, you should see the debug message during cmdlet execution.

**Comment by obayesshelton** [comment]
@dingmeng-xue which screen / tab do you need the output from?

**Comment by dingmeng-xue** [comment]
@obayesshelton , are you still having the problem? We cannot see the same problem. Let me know if a meeting required or whether you can share your test environment to me.
