### ISSUE TITLE
unexpected output from Get-AzRecoveryServicesVaultProperty

### ISSUE THREAD

**Issue by zahraasaleh** [Azure/azure-powershell#16850]
[trying to get the Azure recovery services vault storage setting from PowerShell is not working and gives an empty result
PS /home/zahraa> $vault = Get-AzRecoveryServicesVault -ResourceGroupName "zahraasaleh" -Name "zahraasaphana2"
PS /home/zahraa> $vaultProperty = Get-AzRecoveryServicesVaultProperty -VaultId $vault.Id
PS /home/zahraa> $vaultProperty

![image](https://user-images.githubusercontent.com/83288412/142020666-8adb9601-de18-4305-bb2f-35604f9359cf.png)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8253173-a9b2-838a-9ade-5cd17efea3d2
* Version Independent ID: 82019acf-744a-3892-985c-34170bf568c3
* Content: [BackupResourceVaultConfigResource Class (Microsoft.Azure.Management.RecoveryServices.Backup.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.recoveryservices.backup.models.backupresourcevaultconfigresource?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.RecoveryServices.Backup.Models/BackupResourceVaultConfigResource.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.RecoveryServices.Backup.Models/BackupResourceVaultConfigResource.xml)
* Service: **site-recovery**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adityabalaji-msft** [comment]
Hi @zahraasaleh - if you are looking for storage redundancy settings of the vault, could you try using the Get-AzRecoveryServicesBackupProperty command and see if that works for you?

https://docs.microsoft.com/powershell/module/az.recoveryservices/get-azrecoveryservicesbackupproperty?view=azps-8.0.0

**Comment by adityabalaji-msft** [comment]
Awaiting user response

**Comment by RakeshMohanMSFT** [comment]
@zahraasaleh If you still need help please reopen this issue
