### ISSUE TITLE
Get-AzADUser with advanced queries not working

### ISSUE THREAD

**Issue by erwinkramer** [Azure/azure-powershell#16874]
### Description

If i understand correctly, the following **advanced query** should work because i set `consistencyLevel eventual`:

```
Get-AzADUser -select 'Department' -AppendSelected -consistencyLevel eventual -Filter "Department ne null"
```

Documentation: https://docs.microsoft.com/en-us/graph/aad-advanced-queries#support-for-filter-on-properties-of-azure-ad-directory-objects

### Issue script & Debug output

```PowerShell
Get-AzADUser -select 'Department' -AppendSelected -consistencyLevel eventual -Filter "Department ne null"
Get-AzADUser_List:....\PowerShell\Modules\Az.Resources\5.2.0\MSGraph.Autorest\custom\Get-AzADUser.ps1:210
Line |
 210 |          Az.MSGraph.internal\Get-AzADUser @PSBoundParameters
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unsupported property filter clause operator 'NotEqualsMatch'.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     2.3.1                 Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagementRegion…}
Script     5.2.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
Message        : [Request_UnsupportedQuery] : Unsupported property filter clause operator 'NotEqualsMatch'.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Get-AzADUser_List}
Line           :         Az.MSGraph.internal\Get-AzADUser @PSBoundParameters

Position       : At C:\Users\ekramer\Documents\PowerShell\Modules\Az.Resources\5.2.0\MSGraph.Autorest\custom\Get-AzADUser.ps1:210 char:9
                 +         Az.MSGraph.internal\Get-AzADUser @PSBoundParameters
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 127
```

**Comment by dingmeng-xue** [comment]
It seems a service bug. Its behavior is different from documentation. I use the example on doc and send request to service directly 

```
# Works
GET https://graph.microsoft.com/v1.0/users?companyName ne null

# Doesn't work
GET https://graph.microsoft.com/v1.0/users?$filter=companyName ne null

#works
https://graph.microsoft.com/v1.0/users?$filters=companyName ne null
```
I seems `filters` support it but API spec doesn't mention that query parameter 
https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/2d2ce81e3f093a9c6e8642beac37c868017b9c63/openApiDocs/v1.0/Users.yml#L28

**Comment by dingmeng-xue** [comment]
It's not the reason. You can try it via website https://developer.microsoft.com/en-us/graph/graph-explorer

**Comment by JustinGrote** [comment]
It absolutely requires the `$count` parameter but there's no way in the current parameters to do this short of a convoluted httppipelineprepend. In the graph SDK there is a -countvariable parameter that sets $count and returns the count to that set variable, these Az commands should replicate that behavior.

**Comment by dingmeng-xue** [comment]
@JustinGrote , According to API spec of MSGraph, `count` is not required parameter.

When I tried `GET https://graph.microsoft.com/v1.0/users?$filter=Department%20ne%20null&$count=true`, I got 
```
{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Unsupported property filter clause operator 'NotEqualsMatch'.",
        "innerError": {......}
    }
}
```

**Comment by JustinGrote** [comment]
> @JustinGrote , According to API spec of MSGraph, `count` is not required parameter.
> 
> When I tried `GET https://graph.microsoft.com/v1.0/users?$filter=Department%20ne%20null&$count=true`, I got
> 
> ```
> {
>     "error": {
>         "code": "Request_UnsupportedQuery",
>         "message": "Unsupported property filter clause operator 'NotEqualsMatch'.",
>         "innerError": {......}
>     }
> }
> ```

Your query is not the same as my query. You did a ne filter, not an eq filter, and it is also not clear if you specified ConsistencyLevel eventual header. You need *both*

**Comment by JustinGrote** [comment]
Still an issue.

**Comment by JustinGrote** [comment]
@dingmeng-xue  still an issue.

**Comment by Mrkokoo** [comment]
I'm also running to same issue with Get-AzADUser cmdlet. Any estimates on fix timeline?

**Comment by VeryEarly** [comment]
We will expose parameter: "Count" in [2022-09-06](https://github.com/Azure/azure-powershell/milestone/139) release

**Comment by erwinkramer** [comment]
Thanks, this works now: `Get-AzADUser -select 'Department' -AppendSelected -consistencyLevel eventual -Filter "Department ne null" -Count`
