### ISSUE TITLE
Enable-AzureServiceProjectRemoteDesktop : Invalid service path! Cannot locate ServiceDefinition.csdef in current folder or parent folders.

### ISSUE THREAD

**Issue by kiewic** [Azure/azure-powershell#1688]
I am facing the [same problem](https://social.msdn.microsoft.com/Forums/azure/en-US/8a7bc733-0dc3-4455-b9e8-7bb52fd6fc4b/saveazureserviceprojectpackage-invalid-service-path-cannot-locate-servicedefinitioncsdef-in?forum=azurescripting&prof=required) as described by Anthony Guimelli in the MSDN forums on May 2012.

I am invoking `Enable-AzureServiceProjectRemoteDesktop`, I am 100% sure that _ServiceDefinition.csdef_ is in the current directory, and the command is failing with the following error:

```
PS C:\Users\gistanki\Desktop\example> Enable-AzureServiceProjectRemoteDesktop

cmdlet Enable-AzureServiceProjectRemoteDesktop at command pipeline position 1
Supply values for the following parameters:
Username: g***i@microsoft.com
Password: ***
Enable-AzureServiceProjectRemoteDesktop : Invalid service path! Cannot locate ServiceDefinition.csdef in current
folder or parent folders.
At line:1 char:1
+ Enable-AzureServiceProjectRemoteDesktop
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Enable-AzureServiceProjectRemoteDesktop], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.CloudService.Development.EnableAzureServiceProjectRemote
   DesktopCommand
```

I have `Microsoft Azure PowerShell - January 2016` tools installed.

**Comment by markcowl** [comment]
@kiewic Are you using this with the scaffolding cmdlets (New-AzureServiceProject, Add-Azure **Role, etc.)?  The *ServiceProject* cmdlets are expecting a particular project structure that is created by those cmdlets.

**Comment by kiewic** [comment]
No, I did not use `New-AzureServiceProject` or `Add-Azure`. Project was created with Visual Studio. Is there any way I can use `Enable-AzureServiceProjectRemoteDeskto`? If yes, is there any walk-through?

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
