### ISSUE TITLE
Azure Firewall allocate method failing

### ISSUE THREAD

**Issue by mosharafMS** [Azure/azure-powershell#16883]
### Description

Azure firewall allocate method used to work with two parameters, the vnet and the public IP as per the documentation

https://docs.microsoft.com/en-us/powershell/module/az.network/set-azfirewall?view=azps-7.1.0

Now using two parameters resulting in error 
"MethodException: Cannot find an overload for "Allocate" and the argument count: "2"."
checking the method help found that the signature changed to 
void Allocate(Microsoft.Azure.Management.Network.Models.SubResource virtualHub), void Allocate(Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork virtualNetwork, Microsoft.Azure.Commands.Network.Models.PSPublicIpAddress[] publicIpAddresses, Microsoft.Azure.Commands.Network.Models.PSPublicIpAddress ManagementPublicIpAddress)

However even when using 3 parameters like 
$fw.Allocate($vnet,@($pip),$pip)
or 
$fw.Allocate($vnet,@($pip),$null)

### Issue script & Debug output

```PowerShell
MethodException: Cannot find an overload for "Allocate" and the argument count: "2".
```

### Environment data

```PowerShell
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Script     4.14.0                Az.Network
```

### Error output

```PowerShell
Message        : Cannot find an overload for "Allocate" and the argument count: "2".
StackTrace     :    at CallSite.Target(Closure , CallSite , Object , Object , Object )
                    at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2
                 arg2)
                    at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.MethodException
InvocationInfo : {}
Line           : $fw.Allocate($vnet,$pip)
Position       : At line:1 char:1
                 + $fw.Allocate($vnet,$pip)
                 + ~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : Cannot find an overload for "Allocate" and the argument count: "2".
StackTrace     :    at CallSite.Target(Closure , CallSite , Object , Object , Object[] )
                    at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2
                 arg2)
                    at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.MethodException
InvocationInfo : {}
Line           : $fw.Allocate($vnet,@($pip))
Position       : At line:1 char:1
                 + $fw.Allocate($vnet,@($pip))
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by MughundhanRaveendran-MSFT** [comment]
@mosharafMS , Thanks for reporting this issue.

It works for me in 4.10.0  version of   Az.Network module. I will try the 4.14.0 and let you know. 
If you need to be unblocked from this issue, please try 4.10.0 version

**Comment by MughundhanRaveendran-MSFT** [comment]
@mosharafMS , I tried to reproduce the issue with the same environment as yours but I am unable to reproduce the issue. How frequently are you getting this issue?

**Comment by MughundhanRaveendran-MSFT** [comment]
@mosharafMS , Did you get a chance to look into my previous comment?

**Comment by MughundhanRaveendran-MSFT** [comment]
Closing this issue as there is no response. Feel free to reopen

**Comment by bfordiv** [comment]
Fyi, this still happens in 4.14.0.
