### ISSUE TITLE
Get-AzADUser missing Property "onPremisesLastSyncDateTime"

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#16892]
### Description

Since changing to Az.Resources 5.2. I am missing attributes like `onPremisesLastSyncDateTime` when I perform `Get-AzADUser`

![image](https://user-images.githubusercontent.com/25774289/150547484-471c9f02-5378-4230-a9fe-29240b8e5ac6.png)

https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-property-differences#device-property-differences

### Issue script & Debug output

```PowerShell
Missing Properties
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS > Get-Command Get-AzAdUser

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-AzADUser                                       5.2.0      Az.Resources
```

**Comment by dingmeng-xue** [comment]
@VeryEarly , can we add `onPremisesLastSyncDateTime` and `onPremisesSyncEnabled` to User model in this month?

**Comment by VeryEarly** [comment]
Hi @Gill-Bates ,

Thanks for reporting this bug, fix will be available early next month.
