### ISSUE TITLE
[Eng]: Get-AzRecoveryServicesBackupProtectionPolicy not listing all the policies

### ISSUE THREAD

**Issue by mearvind** [Azure/azure-powershell#16908]
### Description

When i want to list all the policy in the vault it throws below error

Get-AzRecoveryServicesBackupProtectionPolicy -WorkloadType "AzureVM" -VaultId $vault.Id
WARNING: Data truncated. Please upgrade to latest version of Azure Powershell
Get-AzRecoveryServicesBackupProtectionPolicy: Object reference not set to an instance of an object.

When I enter policy name then it works:

Get-AzRecoveryServicesBackupProtectionPolicy -Name DefaultPolicy

Name                 WorkloadType       BackupManagementType BackupTime (UTC)          DaysOfWeek
----                 ------------       -------------------- ----------------          ----------
DefaultPolicy        AzureVM            AzureVM              03-Jun-21 12:30:00 PM

Azure PowerShell version 7.1.0

Module versions: 
Name                     Version
----                     -------
Az.Accounts              2.7.1
Az.Accounts              2.2.6
Az.Advisor               1.1.2
Az.Advisor               1.1.1
Az.Aks                   3.1.0
Az.Aks                   2.0.2
Az.AnalysisServices      1.1.4
Az.ApiManagement         2.3.1
Az.ApiManagement         2.2.0
Az.AppConfiguration      1.0.0
Az.ApplicationInsights   1.3.0
Az.ApplicationInsights   1.1.0
Az.Attestation           1.0.0
Az.Automation            1.7.3
Az.Automation            1.5.0
Az.Batch                 3.1.1
Az.Batch                 3.1.0
Az.Billing               2.0.0
Az.Cdn                   1.8.1
Az.Cdn                   1.6.0
Az.CloudService          1.0.0
Az.CognitiveServices     1.10.0
Az.CognitiveServices     1.8.0
Az.Compute               4.22.0
Az.Compute               4.10.0
Az.ContainerInstance     3.0.0
Az.ContainerInstance     1.0.3
Az.ContainerRegistry     2.2.3
Az.ContainerRegistry     2.2.1
Az.CosmosDB              1.5.1
Az.CosmosDB              1.1.0
Az.DataBoxEdge           1.1.0
Az.Databricks            1.1.0
Az.DataFactory           1.16.2
Az.DataFactory           1.11.4
Az.DataLakeAnalytics     1.0.2
Az.DataLakeStore         1.3.0
Az.DataShare             1.0.0
Az.DeploymentManager     1.1.0
Az.DesktopVirtualization 3.1.0
Az.DesktopVirtualization 2.1.1
Az.DevTestLabs           1.0.2
Az.Dns                   1.1.2
Az.EventGrid             1.3.0
Az.EventHub              1.9.1
Az.EventHub              1.7.1
Az.FrontDoor             1.9.0
Az.FrontDoor             1.7.0
Az.Functions             4.0.1
Az.Functions             2.0.0
Az.HDInsight             5.0.0
Az.HDInsight             4.2.0
Az.HealthcareApis        1.3.1
Az.HealthcareApis        1.2.0
Az.IotHub                2.7.4
Az.IotHub                2.7.2
Az.KeyVault              4.2.0
Az.KeyVault              3.4.0
Az.Kusto                 2.0.0
Az.Kusto                 1.0.1
Az.LogicApp              1.5.0
Az.MachineLearning       1.1.3
Az.Maintenance           1.2.0
Az.Maintenance           1.1.0
Az.ManagedServices       3.0.0
Az.ManagedServices       2.0.0
Az.MarketplaceOrdering   1.0.2
Az.Media                 1.1.1
Az.Migrate               1.1.2
Az.Migrate               1.0.0
Az.Monitor               3.0.0
Az.Monitor               2.4.0
Az.MySql                 1.0.0
Az.Network               4.14.0
Az.Network               4.6.0
Az.NotificationHubs      1.1.1
Az.OperationalInsights   3.0.0
Az.OperationalInsights   2.3.0
Az.PolicyInsights        1.4.1
Az.PostgreSql            1.0.0
Az.PowerBIEmbedded       1.1.2
Az.PrivateDns            1.0.3
Az.RecoveryServices      5.0.0
Az.RecoveryServices      3.4.1
Az.RedisCache            1.6.0
Az.RedisCache            1.4.0
Az.RedisEnterpriseCache  1.0.0
Az.Relay                 1.0.3
Az.ResourceMover         1.1.0
Az.Resources             5.2.0
Az.Resources             3.3.0
Az.Security              1.1.1
Az.SecurityInsights      1.1.0
Az.ServiceBus            1.6.0
Az.ServiceBus            1.4.1
Az.ServiceFabric         3.0.1
Az.ServiceFabric         2.2.2
Az.SignalR               1.4.1
Az.SignalR               1.2.0
Az.Sql                   3.7.0
Az.Sql                   2.16.0
Az.SqlVirtualMachine     1.1.0
Az.StackHCI              1.0.0
Az.Storage               4.1.1
Az.Storage               3.4.0
Az.StorageSync           1.6.1
Az.StorageSync           1.4.0
Az.StreamAnalytics       2.0.0
Az.StreamAnalytics       1.0.1
Az.Support               1.0.0
Az.Synapse               1.0.0
Az.TrafficManager        1.0.4
Az.Websites              2.9.0
Az.Websites              2.4.0

**Comment by SaurabhSharma-MSFT** [comment]
@mearvind I have checked it and it worked fine for me.  
![image](https://user-images.githubusercontent.com/38112130/151276300-bdb894a0-eb09-4b49-9c7e-4d0e35a6651d.png)

I could see that you have two different versions (5.0.0 and 3.4.1) of Az.RecoveryServices module installed in your environment. Can you please remove and uninstall the older version of the module using `Remove-Module` and `Uninstall-Module` and check if that works for you.

Thanks
Saurabh

**Comment by bwarren18** [comment]
I was able to reproduce the same issue.

It works fine with a new Recovery Services Vault with the default policies.

However after creating an **Enhanced Backup Policy** it throws the same error.

WARNING: Data truncated. Please upgrade to latest version of Azure Powershell
Get-AzRecoveryServicesBackupProtectionPolicy : Object reference not set to an instance of an object.

**Comment by solstone** [comment]
I also am getting this error and think it has something to do with the "enhanced backup" polices.

**Comment by janvanaa** [comment]
Same problem here, both with powershell 7.2.1 and with powershell 5.1

Az.recovery module version 5.2.0

Only when enhanced backup policies are present.

**Comment by hiaga** [comment]
This issue will be fixed next version onwards. Thanks @janvanaa for the feedback

**Comment by brendanla** [comment]
@hiaga when is the next version due? Thanks.

**Comment by hiaga** [comment]
Hi @brendanla, @solstone the release is live. Please use the latest Az (Az.RecoveryServices 5.3.0)
