### ISSUE TITLE
AzureRmBackupContainer V1VM/V2VM confusion

### ISSUE THREAD

**Issue by Cloudry** [Azure/azure-powershell#1691]
According to the documentation, and the source, there is a Parameter set for v2VMs 

However when you run the command - 

    Register-AzureRmBackupContainer -Vault $vault -Name $vm.Name `
                   -ResourceGroupName $vm.ResourceGroupName

The error message `The specified Azure Virtual Machine Not Found.` suggests that a possible cause is `VM is Azure IaaS v2 VM` 

Obviously this goes against what the command line options suggest. 

Is it possible to backup an IaaS v2 VM with AzureRM.Backup? (considering that it is a RM cmdlet, it would hint towards it being possible!)

**Comment by chrisinazure** [comment]
I had the same issue, seems you can register classic vm's in the new azurerm backupvault ... awaiting for support of iaasv2's now

**Comment by mkherani** [comment]
Hi Cloudry,
Thanks for using our product.
Currently We don't support backup of CSM V2 VM. ResourceGroup model is for the classic VMs created from Ibiza portal. We will soon roll-out support for backup of V2 vm.
