### ISSUE TITLE
[Eng]: Issue in (CI/CD) Deploying Integration Account Artifacts(Maps & Schemas) via Self hosted Runner using PowerShell Ad-Hoc commands/steps.

### ISSUE THREAD

**Issue by susrutpatnaik** [Azure/azure-powershell#16927]
### Description

Hi Team,

Agenda: Issue in (CI/CD) Deploying Integration Account Artifacts(Maps & Schemas) via Self hosted Runner using PowerShell Ad-Hoc commands/steps.

Details:

As part of automation, we have been successfully deploying Maps-Schemas(in an Integration Account), Logic Apps & Function Apps via GitHub hosted runners for various interfaces.

The command below invokes/calls a PowerShell script (comprises of multiple Ad-hoc commands) in our Repo which deploys all the required Maps & Schemas.
Example (Ad-hoc commands):

New-AzIntegrationAccountMap -MapFilePath $ARTIFACTS_PATH/Maps/.xsl -MapName '' -MapType Xslt -Name 'xyz' -ResourceGroupName 'abc'

Set-AzIntegrationAccountMap -MapFilePath $ARTIFACTS_PATH/Maps/.xsl -MapName '' -MapType Xslt -Name 'xyz' -ResourceGroupName 'abc' -Force

New-AzIntegrationAccountSchema -SchemaFilePath $ARTIFACTS_PATH/Schemas/.xsd -SchemaName '' -SchemaType Xml -Name 'xyz' -ResourceGroupName 'abc'

Set-AzIntegrationAccountSchema -SchemaFilePath $ARTIFACTS_PATH/Schemas/.xsd -SchemaName '' -SchemaType Xml -Name ‘xyz’ -ResourceGroupName 'abc' -Force
Issue:

But now when we are in the process of standardizing the deployment, invoking the same PowerShell commands to deploy the artifacts (Maps & Schemas) via a Self-hosted runner(Linux).

We have been facing issues ever since (Null value expression; Missing an argument for parameter & parameter list etc.), few of the other issues are part of troubleshooting.

Even though we have incorporated the required parameters in the workflow like Vault secrets, Installing PowerShell etc. still it seems there’s a missing link.
Action/Solution:

We require you & your team’s expertise to help us with the deployment. Any sample or implemented workflow would be of great assistance.

Please revert, if & when we can set up a call to discuss on the issue elaborately. Also, request for a working session to proceed with the resolution.

Regards
Susrut

**Comment by SaurabhSharma-MSFT** [comment]
@SaurabhSharma-MSFT I suggest you please open a support ticket so that an engineer could look into environment and dig further to find the root cause.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@susrutpatnaik Please let me know if you need any help creating a support ticket.
