### ISSUE TITLE
[Feature]: Get-AzBlueprintAssignment should return version of assigned blueprint

### ISSUE THREAD

**Issue by juergenbr** [Azure/azure-powershell#16952]
### Description of the new feature

**Problem:**
Az.Blueprint is currently not able to return the version of the blueprint used in an assignment.
```
Name               : Onboarding-xxxx-xxxx-xxxx-xxxx-xxxxx
Id                 : /subscriptions/xxxx-xxxx-xxxx-xxxx-xxxxx/providers/Microsoft.Blueprint/blueprintAssignments/Onboarding-
                     xxxx-xxxx-xxxx-xxxx-xxxxx
Scope              : /subscriptions/xxxx-xxxx-xxxx-xxxx-xxxxx
LastModified       : 2022-01-25
LockMode           : None
ExcludedActions    : 
ExcludedPrincipals : 
ProvisioningState  : Succeeded
Parameters         : 
ResourceGroups     :
```

**Expected return:**
Powershell should return the same data as the Azure CLI. If I use `az blueprint assignment show` for the same assignment, I get the full blueprint id including the version used:

```
{
  "blueprintId": "/providers/Microsoft.Management/managementGroups/<mgname>/providers/Microsoft.Blueprint/blueprints/<blueprint-name>/versions/1.1",
  "description": null,
  "displayName": null,
  "id": "/subscriptions/xxxx-xxxx-xxxx-xxxx-xxxxx/providers/Microsoft.Blueprint/blueprintAssignments/Onboarding-xxxx-xxxx-xxxx-xxxx-xxxxx",
  "identity": {
    "principalId": null,
    "tenantId": "<tenantid>",
    "type": "userAssigned",
    "userAssignedIdentities": {
      "/subscriptions/xxxx-xxxx-xxxx-xxxx-xxxxx/resourceGroups/<rgname>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<name>": {
        "clientId": "<clientid>",
        "principalId": "<principalid>"
      }
    }
  },
  "location": "eastus",
  "locks": {
    "excludedActions": null,
    "excludedPrincipals": null,
    "mode": "none"
  },
  "name": "Onboarding-xxxx-xxxx-xxxx-xxxx-xxxxx",
  "parameters": {},
  "provisioningState": "succeeded",
  "resourceGroups": {},
  "scope": "/subscriptions/xxxx-xxxx-xxxx-xxxx-xxxxx",
  "status": {
    "lastModified": "2022-01-25T14:18:46.211652+00:00",
    "managedResources": [<resources>
    ],
    "timeCreated": "2022-01-25T13:46:06+00:00"
  },
  "type": "Microsoft.Blueprint/blueprintAssignments"
}
```

### Proposed implementation details (optional)

Add additional field to the return object of Get-AzBlueprintAssignment containing the version used for the assignment.
Alternatively return the full resource ID including version of the blueprint used for the assignment.

**Comment by navba-MSFT** [comment]
@juergenbr Thanks for reaching out to us. Apologies for the late reply. To get the version of the assigned blueprint you can run the below Powershell command:
More Info [here](https://docs.microsoft.com/en-us/powershell/module/az.blueprint/get-azblueprintassignment?view=azps-7.1.0)

>$blueprintAssignment = Get-AzBlueprintAssignment -SubscriptionId '1234****-****1234'
$blueprintAssignment.BlueprintId

Output returned:
>/subscriptions/1234****-****1234/providers/Microsoft.Blueprint/blueprints/blueprintName/versions/1.1

Hope this helps. Please let me know if you face any issues while running this command. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@juergenbr I wanted to follow-up on this github issue and check if you had a chance to follow the action plan suggested in my previous comment. Awaiting your reply.

**Comment by juergenbr** [comment]
@navba-MSFT my apologies as well for not replying sooner.
Yes I was able to implement it as you described. Thanks a lot, I'll close the issue.
