### ISSUE TITLE
Get-AzAdvisorRecommendation omits "resourceMetadata"

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#16953]
### Description

The cmdlet `Get-AzAdvisorRecommendation` does not deliver the Metadata from the GraphAPI

https://docs.microsoft.com/en-us/rest/api/advisor/recommendations/list

![image](https://user-images.githubusercontent.com/25774289/151373906-8ce967b5-f26f-4758-bd26-3df8923ae4e8.png)

### Issue script & Debug output

```PowerShell
Get-AzAdvisorRecommendation
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS > Get-Command Get-AzAdvisorRecommendation

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-AzAdvisorRecommendation                        1.1.1      Az.Advisor
```

**Comment by SaurabhSharma-MSFT** [comment]
@Gill-Bates As per internal discussions with the products team, there is no missing data in PS vs the REST API response and it seems that the resourceId is the only component of resourceMetadata and is indeed present. 

Only thing is the naming convention is inconsistent i.e. it is "Metadata” in PS and “resourceMetadata” REST.  Please let me know if I am missing something.

Thnaks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@Gill-Bates We are proceeding with the closure of this case. Please let us know in case any other questions arise. Thanks
