### ISSUE TITLE
Inconsistent parameter usage in Set-AzureRmCurrentStorageAccount cmdlet

### ISSUE THREAD

**Issue by bd4hjimp** [Azure/azure-powershell#1696]
The storage account name parameter in `Set-AzureRmCurrentStorageAccount` is different from the other storage cmdlets. `Get-AzureRmStorageAccount`, `Remove-AzureRmStorageAccount` *etc.* define the parameter as `-Name` and accept `-StorageAccountName` and `-AccountName` as aliases - `Set-AzureRmCurrentStorageAccount` defines the parameter as `StorageAccountName` with no aliases.

``` Powershell
$StorageAccountDetails = @{ ResourceGroupName = 'Foo'; Name = 'Bar'}

# Returns the storage account
Get-AzureRmStorageAccount @StorageAccountDetails

# Fails to bind parameter -Name
Set-AzureRmCurrentStorageAccount @StorageAccountDetails
```

**Comment by EmmaZhu** [comment]
Thanks @bd4hjimp for bringing this to us.
We've got it fixed and it will be included in the next release.

**Comment by vinjiang** [comment]
Feel free to try the newly released version and let us know if you have further questions.
