### ISSUE TITLE
Get-AzSqlDatabase limit of returned databases 

### ISSUE THREAD

**Issue by rokuUK** [Azure/azure-powershell#16964]
### Description

I noticed that Get-AzSqlDatabase returns only the first 100 databases, even if I use an additional filter, the filtering is still in the range of these 100 databases. Is it possible to change the size of the recordset

**Comment by navba-MSFT** [comment]
@rokuUK Thanks for reaching out to us. Apologies for the late reply. 
 I will be doing some research around the PS command which is limiting to 100 results. In the meantime, Could you please test the behavior with the Azure CLI to perform the list database operation? This will help us to isolate the issue.

>az login
az account set --subscription "123435-***-***-***-12345"
az sql db list --resource-group MyResourceGroup --server myserver

More Info [here](https://docs.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#az-sql-db-list). Awaiting your reply.

**Comment by rokuUK** [comment]
sorry, my mistake, I should have written from the beginning that Az it returns me the full list of databases

**Comment by navba-MSFT** [comment]
@rokuUK Thanks for getting back. While I am doing research on this, Could you please test with the below Powershell script and let me know if that helps ?

>$auth=Get-AzAccessToken
$authHeader= $auth.token
$subscriptionId='1234-****-****-1234'
$serverName="myServerName"
$resourceGroupName='myRgName'
$uri= "https://management.azure.com/subscriptions/" + $subscriptionId + "/resourceGroups/" + $resourceGroupName + "/providers/Microsoft.Sql/servers/" + $serverName + "/databases?api-version=2021-02-01-preview"
$output=Invoke-WebRequest -Uri $uri -Method GET -Headers @{"Authorization"="Bearer $authHeader"}
$output | ConvertFrom-Json | select -ExpandProperty value | select -ExpandProperty id

**Comment by rokuUK** [comment]
the script returned 100 lines

**Comment by navba-MSFT** [comment]
@rokuUK Thanks for getting back. The support for pagination was added to Get-AzSqlDatabase PS command as per [this](https://github.com/Azure/azure-powershell/commit/6f3647d507ac253472e41d3b65daa1ee8027e01a) thread. Also refer #15772

Remove the existing module and please install the most recent version of [Az.sql](https://www.powershellgallery.com/packages/Az.Sql/3.7.0) module and test the behavior. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@rokuUK This is a quick follow-up to check if you had a chance to follow the action plan suggested in my above comment. Awaiting your reply.

**Comment by rokuUK** [comment]
`PS C:\windows\system32> 
$databases = Get-AzSqlDatabase -ServerName "myservername" -ResourceGroupName "myresourcegroupname" #| Format-Table -AutoSize
$databases.count
WARNING: Upcoming breaking changes in the cmdlet 'Get-AzSqlDatabase' :
- The output type 'Microsoft.Azure.Commands.Sql.Database.Model.AzureSqlDatabaseModel' is changing
- The following properties in the output type are being deprecated : 'BackupStorageRedundancy'
- The following properties are being added to the output type : 'CurrentBackupStorageRedundancy' 'RequestedBackupStorageRedundancy'
- The change is expected to take effect from the version : '3.0.0'
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.
262

PS C:\windows\system32> `

thank you, now it looks reasonable

**Comment by navba-MSFT** [comment]
@rokuUK Thanks for getting back. We will now proceed with closure of this github thread. Feel free to reopen this thread if you need any further assistance. We would be happy to assist you further on this.
