### ISSUE TITLE
[Feature]: -VaultId <string> -SecretName <string> [-SecretVersion <string>] missing from Enable-AzCdnCustomDomainHttps

### ISSUE THREAD

**Issue by brwilkinson** [Azure/azure-powershell#16974]
### Description of the new feature

The FrontDoor and the CDN module share similar Cmdlets 

e.g.
```powershell
gcm Enable-*CustomDomainHttps*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Enable-AzCdnCustomDomainHttps                      1.8.1      Az.Cdn
Cmdlet          Enable-AzFrontDoorCustomDomainHttps                1.9.0      Az.FrontDoor
```

The FrontDoor cmdlet allows you to setup a Custom DNS with a cert from the keyvault.

```powershell
            $SecretVersion = Split-Path -Path $certificateUrl -Leaf
            $Secret = Split-Path -Path $certificateUrl
            $SecretName = Split-Path -Path $Secret -Leaf
            
            $Params = @{
                ResourceGroupName    = $ResourceGroupName
                FrontDoorName        = $FrontDoorName
                FrontendEndpointName = $Name
                VaultId              = $VaultID
                SecretName           = $SecretName
                MinimumTlsVersion    = '1.2'
                SecretVersion        = $SecretVersion
            }
            Enable-AzFrontDoorCustomDomainHttps @Params
```

**I was looking for similar functionality on the CDN Cmdlet.**

```powershell
gcm Enable-AzCdnCustomDomainHttps -syntax

Enable-AzCdnCustomDomainHttps -ResourceGroupName <string> -ProfileName <string> -EndpointName <string> -CustomDomainName <string> [-PassThru] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]

Enable-AzCdnCustomDomainHttps -InputObject <PSCustomDomain> [-PassThru] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]

Enable-AzCdnCustomDomainHttps -ResourceId <string> [-PassThru] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
```

There is no way to do this at the moment..

here is the same with the FD cmdlet

```powershell
gcm Enable-AzFrontDoorCustomDomainHttps -syntax

Enable-AzFrontDoorCustomDomainHttps -ResourceGroupName <string> -FrontDoorName <string> -FrontendEndpointName <string> [-MinimumTlsVersion <string>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]

Enable-AzFrontDoorCustomDomainHttps -ResourceGroupName <string> -FrontDoorName <string> -FrontendEndpointName <string> -VaultId <string> -SecretName <string> [-SecretVersion <string>] [-MinimumTlsVersion <string>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]

Enable-AzFrontDoorCustomDomainHttps -ResourceId <string> [-MinimumTlsVersion <string>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]

Enable-AzFrontDoorCustomDomainHttps -ResourceId <string> -VaultId <string> -SecretName <string> [-SecretVersion <string>] [-MinimumTlsVersion <string>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]

Enable-AzFrontDoorCustomDomainHttps -InputObject <PSFrontendEndpoint> [-MinimumTlsVersion <string>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]

Enable-AzFrontDoorCustomDomainHttps -InputObject <PSFrontendEndpoint> -VaultId <string> -SecretName <string> [-SecretVersion <string>] [-MinimumTlsVersion <string>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
```

i.e. `-VaultId <string> -SecretName <string> [-SecretVersion <string>]` **missing from Enable-AzCdnCustomDomainHttps**

### Proposed implementation details (optional)

Here is the implemenation on the az cli

https://docs.microsoft.com/en-us/cli/azure/cdn/custom-domain?view=azure-cli-latest#az-cdn-custom-domain-enable-https

![image](https://user-images.githubusercontent.com/3605266/151681707-7ef1f77c-0f6a-4fbd-a8f1-a4e8e9ce3a8e.png)

**Comment by brwilkinson** [comment]
First references in: https://github.com/Azure/bicep/discussions/5567

**Comment by t-bzhan** [comment]
Ack. We are working on to support it in next release.

**Comment by Jaykul** [comment]
It looks like this got done in 2.0 -- but at the cost of **removing** the old functionality?

**Comment by t-bzhan** [comment]
Hi @brwilkinson  and @Jaykul, please refer the new "[Enable-AzCdnCustomDomainCustomHttps](https://learn.microsoft.com/en-us/powershell/module/az.cdn/enable-azcdncustomdomaincustomhttps?view=azps-9.3.0)"  command which support both [CDN managed certificate](https://learn.microsoft.com/en-us/powershell/module/az.cdn/new-azcdnmanagedhttpsparametersobject?view=azps-9.3.0) and [user managed certificate](https://learn.microsoft.com/en-us/powershell/module/az.cdn/new-azcdnusermanagedhttpsparametersobject?view=azps-9.3.0) (That should be what you want as described in the issue).

![image](https://user-images.githubusercontent.com/61817681/216916331-a1d6778a-9a14-4660-a18a-a3f338113ed4.png)

For user managed certificate,  using "[New-AzCdnUserManagedHttpsParametersObject](https://learn.microsoft.com/en-us/powershell/module/az.cdn/new-azcdnusermanagedhttpsparametersobject?view=azps-9.3.0)"  to create the "-CustomDomainHttpsParameter" argument, it allows you to specify the vault id with below arguments:
![image](https://user-images.githubusercontent.com/61817681/216917151-04f36057-e881-43cd-818b-f1f45e5f3dc1.png)
