### ISSUE TITLE
Get-AzPrivateEndpointConnection with -ResourceId argument supports Microsoft.Network/privateLinkServices

### ISSUE THREAD

**Issue by johndowns** [Azure/azure-powershell#16984]
### Description

When using the `Get-AzPrivateEndpointConnection` cmdlet with the `-ResourceId` argument, it expects that the value of the `-ResourceId` argument is the resource ID of a specific private endpoint connection.

if you specify the resource ID of an Azure resource that contains private endpoints (e.g. an App Service app or a storage account), the following error message is returned:

```
Object reference not set to an instance of an object.
```

This error message is unhelpful. The correct argument name to use would be `-PrivateLinkResourceId`, and the cmdlet should tell you this.

Furthermore, this behaviour is inconsistent with the Azure CLI, where using the `--id` argument works fine.

### Issue script & Debug output

```PowerShell
PS /Users/myusername> Get-AzPrivateEndpointConnection -ResourceId /subscriptions/my-subscription/resourceGroups/my-rg/providers/Microsoft.Network/privateLinkServices/MyPrivateLinkService
DEBUG: 10:28:07 AM - GetAzurePrivateEndpointConnection begin processing with ParameterSet 'ByResourceId'.
DEBUG: 10:28:07 AM - using account id 'myalias@microsoft.com'...
Get-AzPrivateEndpointConnection: Object reference not set to an instance of an object.
DEBUG: AzureQoSEvent: Module: Az.Network:4.14.0; CommandName: Get-AzPrivateEndpointConnection; PSVersion: 7.1.5; IsSuccess: False; Duration: 00:00:00.1252211; Exception: Object reference not set to an instance of an object.;
DEBUG: Finish sending metric.
DEBUG: 10:28:07 AM - GetAzurePrivateEndpointConnection end processing.
```
```


### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Script     2.7.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.14.0                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicat…
Script     5.2.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…
```

### Error output

```PowerShell
Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Network.GetAzurePrivateEndpointConnection.Execute()
                    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzPrivateEndpointConnection}
Line           : Get-AzPrivateEndpointConnection -ResourceId 
                 /subscriptions/my-sub-id/resourceGroups/my-rg/providers/Microsoft.Network/privateLinkServices/MyPrivateLinkService
Position       : At line:1 char:1
                 + Get-AzPrivateEndpointConnection -ResourceId /subscriptions/27cafca8-b …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1
```

**Comment by dingmeng-xue** [comment]
@johndowns , this cmdlet doesn't support to list private endpoint connections of network private link. We will verify it and add support.

**Comment by johndowns** [comment]
@dingmeng-xue It feels weird to have to treat one PL resource type differently from another. I still think it's a reasonable feature request to make this behave consistently across all PL resource types.

**Comment by dingmeng-xue** [comment]
We will verify it. If PL resource is consistent with others, we can add it.

**Comment by BethanyZhou** [comment]
Private link services provides:
- Get "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/privateLinkServices/{serviceName}/privateEndpointConnections"
- Get     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/privateLinkServices/{serviceName}/privateEndpointConnections/{peConnectionName}"

Doesn't provide: private link resource related API.

please refers to https://github.com/Azure/azure-rest-api-specs/blob/fba79b52c6cedf8ded0fe1e93a202bb79eb44eb4/specification/network/resource-manager/Microsoft.Network/stable/2021-05-01/privateLinkService.json#L491

We add configuration for resources that support listing PLRs and getting PEC before. Should we add private link services into configuration? @dingmeng-xue

**Comment by dingmeng-xue** [comment]
Thanks @BethanyZhou ,

@johndowns , you have to use `Get-AzPrivateLinkService` to achieve your requirement. `{}-AzPrivateEndpointConnnection` and `{}-AzPrivateLinkResource` are cmdlets for all private link resources which have the same design pattern of API. But  `Microsoft.Network/privateLinkService` is not using the same design which doesn't have API of fetching private link resource. We cannot support it.

**Comment by johndowns** [comment]
@dingmeng-xue I understand that this is currently the behaviour based on the underlying APIs. However, I think there should be two actions here:

1. We should ask the Private Link Service team to support the same APIs as other Private Link resources, so you can make this work consistently.
2. In the meantime, can the CLI provide a better error message than `Object reference not set to an instance of an object.`?

**Comment by dingmeng-xue** [comment]
I changed the title to reflect the first requirement. It means that Az.Network needs to add flag to indicate RP/resource is not private link resource but supports PrivateEndpointConnection.
