### ISSUE TITLE
Get-AzRoleAssignment no longer reports Orphaned Role Assignments

### ISSUE THREAD

**Issue by brwilkinson** [Azure/azure-powershell#16981]
### Description

With previous versions of the Az.Resources Module, it was possible to report and cleanup orphaned role assignments.

In the newer versions this is no longer possible.

```powershell
gmo az.resources

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     4.4.1                 az.resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzADAppCredential…}

$Scope = '/subscriptions/b8f402aa-20f7-4888-b45c-3cf086dad9c3/resourceGroups/ACU1-BRW-AOA-RG-P0'
Get-AzRoleAssignment -scope $Scope -RoleDefinitionName 'Automation_Account_Contributor' | select RoleDefinitionName, objectid,ObjectType

RoleDefinitionName             ObjectId                             ObjectType
------------------             --------                             ----------
Automation_Account_Contributor c7fb6ba6-db10-45d6-8526-1b0b2f82f3cd ServicePrincipal
Automation_Account_Contributor 6c018b03-d5b3-4264-80c4-688874ec91d4 Unknown
Automation_Account_Contributor 2275dd8b-9adc-4247-9d10-8e3a9d37aa16 ServicePrincipal
```

The above shows that the ObjectType is 'Unknown', which also matches what we see in the portal

![image](https://user-images.githubusercontent.com/3605266/151712914-181e6747-4415-4eab-9d1b-15ff7687fb03.png)

In the newer versions of Az.Resources this is no longer possible.

```powershell
gmo az.resources

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     5.1.0                 az.resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, G…

$Scope = '/subscriptions/b8f402aa-20f7-4888-b45c-3cf086dad9c3/resourceGroups/ACU1-BRW-AOA-RG-P0'
Get-AzRoleAssignment -scope $Scope -RoleDefinitionName 'Automation_Account_Contributor' | select RoleDefinitionName, objectid,ObjectType

RoleDefinitionName             ObjectId                             ObjectType
------------------             --------                             ----------
Automation_Account_Contributor c7fb6ba6-db10-45d6-8526-1b0b2f82f3cd ServicePrincipal
Automation_Account_Contributor 6c018b03-d5b3-4264-80c4-688874ec91d4 ServicePrincipal
Automation_Account_Contributor 2275dd8b-9adc-4247-9d10-8e3a9d37aa16 ServicePrincipal
```

This has been the only way to identify these orphaned identies and clean them up for some time now and now there is no way that I know of to identity these orphaned identities via command line,

These orphaned identities are flagged as a security vulnerability in tenant security scans, so it's essential that they are cleaned up regularly.

The following is no longer possible.

```powershell
Get-AzRoleAssignment | where ObjectType -eq 'Unknown' | Remove-AzRoleAssignment -Confirm
```

### Issue script & Debug output

```PowerShell
# this is the one that is working to show unknown az.resources 4.4.1

============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://graph.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/getObjectsByObjectIds?api-version=1.6

Headers:
x-ms-client-request-id        : b1c2f247-b8b9-4fcc-8ee4-43b09170873c
Accept-Language               : en-US

# this is the newer module az.resources 5.1.0 or 5.2.0

============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://graph.microsoft.com/v1.0/directoryObjects/microsoft.graph.getByIds

Headers:
x-ms-client-request-id        : ec768931-b67c-43a6-a4f8-39ba0aa3973e
Accept-Language               : en-US


Looking at the output I see the same links, only the one that is working also has?

  ],
  "includeDirectoryObjectReferences": true
}

Other than that I looked through the logs, however couldn't differentiate between the two, so looks like the data is the same, there must be something in code, that does the check if the principal was deleted or not Etc.
```

### Environment data

```PowerShell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0-preview.1
PSEdition                      Core
GitCommitId                    7.3.0-preview.1
OS                             Microsoft Windows 10.0.22548
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
# new

get-module az.resources,az.accounts

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     5.1.0                 az.resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}


#old

 gmo az.resources,az.accounts

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.4.1                 az.resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzADAppCredential…}
```

### Error output

no error, this is just new behavior.

Ideally we need some other way to identify orphaned accounts.

`ObjectType -eq 'Unknown'` has worked well for a long time, so we now need some replacement to identify the following.

![image](https://user-images.githubusercontent.com/3605266/151712914-181e6747-4415-4eab-9d1b-15ff7687fb03.png)

**Comment by brwilkinson** [comment]
@BethanyZhou let me know if there is any further logs or info that I can provide?

**Comment by BethanyZhou** [comment]
Hi @brwilkinson , thank you for your patience. Could you check your http response from 
GET /subscriptions/xxxxxxx/resourceGroups/xxx/providers/Microsoft.Authorization/roleAssignments?api-version=2020-08-01-preview HTTP/1.1

We obtain the object type information from that API:
![image](https://user-images.githubusercontent.com/19869716/153110155-98460048-e3c3-4cee-ad0c-293de505eaa4.png)

**Comment by brwilkinson** [comment]
Hi @BethanyZhou I will get you to create a role assignment, then I will delete the service principal, then we can test.

in the microsoft tenant, can you search for this service principal  "ADF-AZC1-ADF-RG-G0" with objectId '5bde6791-c827-4321-8398-ccee461cf9e2' then perhaps just create some role assignment on some resource that you have?

![image](https://user-images.githubusercontent.com/3605266/153112067-2a283c7b-bc81-4407-b800-fb508cbe88ea.png)

Once you have done that let me know i can delete the Service Principal. Then we can test again..

You can assign it any role on any scope, that you like...

![image](https://user-images.githubusercontent.com/3605266/153112153-8b54a78a-00c5-4838-b6e8-7b690fcdd03b.png)

Then we can query the role assignment... I guess with some different API versions to see if we can repro what changed.

**Comment by BethanyZhou** [comment]
Thanks @brwilkinson  for your help. I have reproduced this issue on my local.

We get the object type is ServicePrincipal from GET /subscriptions/xxxxxxx/resourceGroups/xxx/providers/Microsoft.Authorization/roleAssignments?api-version=2020-08-01-preview.

```powershell
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/b8f402aa-20f7-4888-b45c-3cf086dad9c3/providers/Microsoft.Authorization/roleAssignments?$filter=principalId eq '24aae806-d1bc-499e-af17-c35444ee598d'&api-version=2020-08-01-preview

Headers:
x-ms-client-request-id        : b4a99ec2-c8ae-42b2-a194-31cf24f29aec
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : a94fc5e2-3b13-4024-a2a5-026562cb5fa5
x-ms-correlation-request-id   : a94fc5e2-3b13-4024-a2a5-026562cb5fa5
x-ms-routing-request-id       : SOUTHEASTASIA:20220209T052659Z:a94fc5e2-3b13-4024-a2a5-026562cb5fa5
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Wed, 09 Feb 2022 05:26:58 GMT

Body:
{
  "value": [
    {
      "properties": {
        "roleDefinitionId": "/subscriptions/b8f402aa-20f7-4888-b45c-3cf086dad9c3/providers/Microsoft.Authorization/roleDefinitions/4d97b98b-1d4f-4787-a291-c67834d212e7",
        "principalId": "24aae806-d1bc-499e-af17-c35444ee598d",
        "principalType": "ServicePrincipal",
        "scope": "/subscriptions/b8f402aa-20f7-4888-b45c-3cf086dad9c3/resourceGroups/AWU1-BRW-AOA-RG-T6/providers/Microsoft.Network/virtualNetworks/AWU1-BRW-AOA-T6-vn",
        "condition": null,
        "conditionVersion": null,
        "createdOn": "2022-02-09T04:09:56.7106207Z",
        "updatedOn": "2022-02-09T04:09:56.7106207Z",
        "createdBy": "528b1170-7a6c-4970-94bb-0eb34e1ae947",
        "updatedBy": "528b1170-7a6c-4970-94bb-0eb34e1ae947",
        "delegatedManagedIdentityResourceId": null,
        "description": null
      },
      "id": "/subscriptions/b8f402aa-20f7-4888-b45c-3cf086dad9c3/resourceGroups/AWU1-BRW-AOA-RG-T6/providers/Microsoft.Network/virtualNetworks/AWU1-BRW-AOA-T6-vn/providers/Microsoft.Authorization/roleAssignments/7b5ec3e0-401c-4e64-80e8-36cd948d1e17",
      "type": "Microsoft.Authorization/roleAssignments",
      "name": "7b5ec3e0-401c-4e64-80e8-36cd948d1e17"
    }
  ]
}
```

Get-AzRoleAssignment gets basic directory object information from the API above, and queries further information about the directory object by AAD graph. 

- In Az.Resources < 5.1.0, the command depends on the response from AAD graph. So it detects your SP is not founded and marks the object type as unknown.
- In Az.Resources >=5.1.0, the cmdlet takes the information from MSGraph as supplementary information. It's not necessary. This way is able to make sure the SP who doesn't own permission "Directory.Read.All" is able to get assignments. Although your SP is deleted, the query from MSGraph is failed, we still know it's a SP from the API I mentioned first.

**Comment by brwilkinson** [comment]
Thank you @BethanyZhou for the update and summary information.

**Comment by BethanyZhou** [comment]
Deleting the orphaned accounts is important business case, and we supported this feature before. we consider this issue as regression. Will fix it.

**Comment by BethanyZhou** [comment]
Hi @brwilkinson , we are fixing this issue and new version of Az.Resources will be available in next release (About 03/01).

Please notice that this cmdlet will mark `ObjectType` as `Unknown` if the object of role assignment is not found or current account has insufficient privileges to get object type.

**Comment by brwilkinson** [comment]
Thanks @BethanyZhou for the update.

I am happy with the options there, assuming some extra step will always be required to validate that you have permission to the directory.

- I know I always have several steps of reporting and validation prior to removing any role assignment, and this will be an increased requirement now this has moved to msgraph.
