### ISSUE TITLE
Select-AzSubscription to specific account

### ISSUE THREAD

**Issue by nellya-alf** [Azure/azure-powershell#16980]
### Description

We are using Select-AzSubscription to set a relevant subscription context; however, recently, we added multiple accounts with different permissions levels in the same subscription. Is there a way to set the context with Select-AzSubscription  to a specific account ID ?

**Comment by dingmeng-xue** [comment]
@nellya-alf , thanks for contacting us. Please check whether `Select-AzContext` https://docs.microsoft.com/en-us/powershell/module/az.accounts/select-azcontext?view=azps-7.1.0 can meet your requirement or not. The input of `Select-AzContext` is the name of context including subscription name, tenant id and account name.
