### ISSUE TITLE
Start-AzStorageBlobCopy to storage account scrabmles content

### ISSUE THREAD

**Issue by Agazoth** [Azure/azure-powershell#16992]
### Description

We are collecting several csv files once a week and store them on a storage account. This has been working just fine for months.

Now the files delivered to the storage account are scrambled. If the same files are downloaded locally with `InvokeWebRequest` , the file is fine.

There are no errors when running the command

The command executes as expected and `Get-AzStorageBlobCopyState ` confirms the file was copied.

The content of the csv file on the storage account looks like this:
```
▼���r�H�/��<♣Lc�Ve]�
��~gE�`$+%RMRY��↓SF23uS)�I�J�^͢�‼��}����ج��d�dI��"@J �;H�W�v�B�▼∟�~��▼��~���x�����=����^��.~[�������߮>\▬_;>�-g▼�a}[����������gV7▼����O/n]�?�����xW�������▼�姾�!▲>9��x}����▲~?�������K�no~����זߞ↨↨ys}���E�ܼ�����~��������'W�>¶�byq��rq}���;�pu���������mNX����7�^?��7ˏ?L�_~��↕>_��g�/5���▼↨�W↨?\����B����j��b�������������v=�����ۋ?�����O��t�|3?↓Og��q�↨xjS��:�������&g▼ȯ(Y�����▬�^���q]`M�/��_�c]|�|��l���Q���������>y�9�?�������/?�D*҇����E�∟§����J▬�/��o?ߓ翓▬ߔ�Z→)�,��▼?
�㣔����a��=Y�������u/�;o�zzݟں���l:�\�T.Zk�{r�▼������U����GW��:ǹZ����
��������
�����~����Kr�����oɿ$���7�O��?�-�𾿼��D���ko��������l��[�~�����♣�6[~;O���5�‼�-O↔n�_^�������G����↨+�;t4�������_l�;[�b������L���?�G�\
```

### Issue script & Debug output

```PowerShell
PS> Start-AzStorageBlobCopy @startParams -Debug
DEBUG: 15:08:16 - Init Operation Context for 'StartAzureStorageBlobCopy' with client request id  Azure-Storage-PowerShell-550a2e76-4a54-47b7-8e30-6fcd9087ff5f. If you want to get more details, please add "-Debug" to your command.
DEBUG: 15:08:16 - Use storage account 'stordlcspdataharvestzx2' from storage context.

Confirm
Are you sure you want to perform this action?
Performing the operation "Copy" on target
"https://pxanltx.blob.core.windows.net/programmatic-export-pi/cnt._148ce716-c936-5543-bfc7-c18d19b9331d.csv?sv=2018-03-28&sr=b&sig=0Ny1TdrxuCBUfLgiThbwZ9Y1grHVgbRepx974PF%o2zQ%
3D&se=2022-02-08T13%3A41%3A49Z&sp=r".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): a
DEBUG: 15:08:18 - Start 4th remote call, method: , destination: https://pkanltx.blob.core.windows.net/programmatic-export-pi/cnt.csv?sv=2018-03-28&sr=b&sig=0Ny1TdrxuCBUfLgiThbwZ9Y1grHVgbRepx974PF%2zQ%3D&se=2022-02-08T13%3A41%3A49Z&sp=r&api-version=2019-07-07&.
VERBOSE: Copy request to blob 'cnt.csv' in container 'reports' has been scheduled with copyId 46558d5e-e31b-40fc-9f3e-5442bcbd7e85.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a

   AccountName: stordlcspdataharvestzx2, ContainerName: msreports

Name                 BlobType  Length          ContentType                    LastModified         AccessTier SnapshotT
                                                                                                              ime
----                 --------  ------          -----------                    ------------         ---------- ---------
CustomersAndTenants… BlockBlob 10219124        application/csv                2022-02-01 14:08:19Z Hot
DEBUG: 15:08:22 - StartAzureStorageBlobCopy end processing, Start 6 remote calls. Finish 6 remote calls. Elapsed time 1032834,44 ms. Client operation id: Azure-Storage-PowerShell-550a2e76-3423-47b7-8e30-6fcd9087ff5f.
DEBUG: 15:08:22 - StartAzureStorageBlobCopy end processing.
VERBOSE: Transfer Summary
--------------------------------
Total:  1.
Successful: 1.
Failed: 0.


PS> Get-AzStorageBlobCopyState -Blob $startParams.DestBlob -Container msreports -Context $startParams.DestContext

CopyId                  : 46408d5e-e31b-40fc-9f3e-0642bcbd7e85
CompletionTime          : 01-02-2022 14:08:32 +00:00
Status                  : Success
Source                  : https://pkynltx.blob.core.windows.net/programmatic-export-pi/cnt_148ce716-c936-4453-bfc7-c18d19b9331d.csv?sv=2018-03-28&sr=b&se=2022-02-08T13%3A41%3
                          A49Z&sp=r
BytesCopied             : 10219124
TotalBytes              : 10219124
StatusDescription       :
DestinationSnapshotTime :
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS> get-module az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefa…
Script     4.2.0                 Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertifi…
Script     4.1.1                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorage…
```

**Comment by Agazoth** [comment]
The file is zipped. 7-Zip reveals the file with the data I want. How do I avoid this compression?

**Comment by Agazoth** [comment]
It seems to be related to the endpoint I get the file from. I just did a test between 2 storage accounts I control. It seems to be something on the source location doing the compression. It is a Microsoft endpoint: https://pxanltx.blob.core.windows.net/programmatic-export-pi

How can I ensure that I get the CSV file and not the zipped version? I need to add un-zipping to my code for the zipped version, and that renders Start-AzStorageBlobCopy obsolete. Just getting the file with Invoke-WebRequest and uploading the file to the other storage account would fix that.

And how could this be done on the source? How does the source know, that I use Start-AzStorageBlobCopy and not Invoke-WebRequest? I would love for Start-AzStorageBlobCopy to have a switch for masking itself as Invoke-WebRequest.

**Comment by blueww** [comment]
@Agazoth 

I might don't understand the issue clearly from the description. 
Do you mean:
-  when you use `InvokeWebRequest` on the source file, the content of the file is fine.
- When you run Start-AzStorageBlobCopy to copy the file from source to the dest account, then use `InvokeWebRequest` to download the dest file, the content of the file is scrambled.
- The same scenario works well before on your side. The issue only happens recently with source blob endpoint: https://pxanltx.blob.core.windows.net/programmatic-export-pi

BTW, `Start-AzStorageBlobCopy` is server side blob Copy, Powershell just send copy request to server and monitor the progress, the copy work is all handled by server.

**Comment by Agazoth** [comment]
@blueww 

* When downloading the file from https://pxanltx.blob.core.windows.net/programmatic-export-pi directly to my local machine by either `Invoke-WebRequest` or just by pasting the link in the browser, the downloaded file is a csv with the expected data.

* When using `Start-AzStorageBlobCopy` to copy the csv file from https://pxanltx.blob.core.windows.net/programmatic-export-pi to my own storage account, the file is compressed, and I get a compressed file on my storage account containing the csv file with the expected data.

As I understand, the source file is a non-compressed blob, that can be retrieved in various ways. In this case, the file retrieved by browser or local PowerShell is a CSV file, but when handing the copy job over to Azure (server side blob copy), the file is somehow compressed.

I have tried to upload a browser downloaded (non-compressed) version of the csv file to one of my own storage accounts, and then copied it from there to a different storage account with `Start-AzStorageBlobCopy` and that did not result in a compressed file on the second storage account.

I would like to know, why the file from https://pxanltx.blob.core.windows.net/programmatic-export-pi gets compressed, when running `Start-AzStorageBlobCopy`, files from other storage accounts do not get compressed, when copying with `Start-AzStorageBlobCopy`.

Depending on the answer to that question, I think it would be cool with an option on `Start-AzStorageBlobCopy` that let's the enduser control whether the destination file should be compressed or not, but at least the documentation should describe, how this compression occours.

**Comment by blueww** [comment]
@Agazoth

If the blob copy from https://pxanltx.blob.core.windows.net/programmatic-export-pi  to your storage account, change the content from plain csv to compressed, this looks more like a server side issue.

Would you:
1. Please make sure when you download dest blob from the dest account , you don't compress the downloaded blob on client side (like you just use `Invoke-WebRequest` to download the dest blob, so the blob content won't be compressed in client)
2. If so, Would you please open an incident with following information (hide credential), and the server side related team will help you.
-  The source blob and dest blob Uri (without credentail)
-  The UTC time to download the source blob before copy happen (better with request ID)
-  The UTC time to copy the source blob to dest blob (better with request ID)
-  The UTC time to download the dest blob after copy happen (better with request ID)
- It would be better if you can include the blob content from source and dest blob (if no credential)
-  indicate this only happen on specific source account

You can open an incident on azure portal, by click "Help+Support" and create a support request, as following picture.
![image](https://user-images.githubusercontent.com/6926193/152917426-c443cf04-16ee-46a7-b68e-0bc17ddc7f02.png)

For your request of the "an option on Start-AzStorageBlobCopy that let's the enduser control whether the destination file should be compressed or not", please note the copy is handle by server side, and server not provide such an option (server should not compress the blob when copy), so we can't do it from Powershell side.

**Comment by Agazoth** [comment]
@blueww I'm ahead of you :-) - I have this case already: TrackingID #2202030040001772.

They told me to post the issue here. I have linked this thread in the case too.

**Comment by blueww** [comment]
@Agazoth 

Powershell don't touch the blob content during the copy of Start-AzStorageBlobCopy , and there's not flag to indicate the blob content should be compressed or not in copy. 
Powershell just send request to server to tell the copy should start. And server will handle all copy progress. So this is a server issue. We can't fix this from powershell code.

I can't see  the issue with the TrackingID, as I don't have enough permission.
You can ask the issue owner to contact me for details.

**Comment by Agazoth** [comment]
@blueww 

I agree with you on both notions. The issue is not with `Start-AzStorageBlobCopy`. I guess I got it backwards because the file I started working with, when I used `Invoke-WebRequest` was not compressed.

I use no settings other then -outfile when running `Invoke-WebRequest` with the url for the compressed blob.

`Invoke-WebRequest` and common browsers seems to have a setting that automatically decompresses (some) compressed storage blobs.

I know `Invoke-WebRequest` and `Invoke-RestMethod` support `Accept-Encoding: deflate` in the request header. That setting will compress the file, if it is not already compressed.

I can't find the documentation on the reversed scenario, where compressed files can be decompressed. Do you have any documentation on that?

**Comment by blueww** [comment]
@Agazoth 

If you use "no settings other then -outfile when running Invoke-WebRequest with the url for the compressed blob". it looks you run a Get Blob request to download the blob.
The related rest API is:  https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob
But I don't see a parameter can decompress the file in the rest API.

If you can write code to download the blob with decompress it, you can see this sample: https://stackoverflow.com/questions/40722328/how-to-download-decompress-and-deserialize-an-object-file-from-azure-blob-stora

**Comment by Agazoth** [comment]
@blueww 

"But I don't see a parameter can decompress the file in the rest API." That is my point exactly. How come the file gets decompressed, when running `Invoke-WebRequest`?

The reason for implementing `Start-AzStorageBlobCopy` in my current code was to avoid the decompressed file in my Azure Function. The workaround in regards to the production setup will be to handle decompression in the data load step.

I still need to understand, why and how a compressed file gets decompressed, when running `Invoke-WebRequest` without any other parameters then -outfile.

I am aware that this probably relates to the backend, but I can find no documentation on setting up a blob storage to decompress files on retrieval. Is it possible that internal MS resources has access to this kind of magic on their storage accounts, and that is not exposed to end-customers?

**Comment by blueww** [comment]
@Agazoth 

> I am aware that this probably relates to the backend, but I can find no documentation on setting up a blob storage to decompress files on retrieval.
Please contact the server team (with the support ticket you have filed) to see why the copied blob is compressed on part of your account. Per my understanding, this should not happen. 
From PSH side, as the copy is all handled by server side, we can't change the compress/decompress.

**Comment by Agazoth** [comment]
@blueww I am in dialog with both the server team and the Partner API team on this case. I will post findings in this tread.

Fact ifs that the file is decompressed using Invoke-WebRequest but not using Start-AzStorageBlobCopy.

**Comment by blueww** [comment]
@Agazoth 
Thanks for the info :
> Fact ifs that the file is decompressed using Invoke-WebRequest but not using Start-AzStorageBlobCopy.

Invoke-WebRequest and Start-AzStorageBlobCopy (I suspect you mean first copy, then download) are 2 different rest API, so they might can have different behavior (not expected) from server, the difference is not coming from Powershell per what I can see.  
However, server team should know why copy blob from specific account will make the dest blob be compressed.

**Comment by Agazoth** [comment]
@blueww - it turns out that ContentEncoding was set to gzip on the blob. That tells `Invoke-WebRequest` to unzip the file. It would be cool if the same functionality could be built into `Start-AzStorageBlobCopy`

**Comment by blueww** [comment]
@Agazoth

`Start-AzStorageBlobCopy` will keep the same ContentEncoding from source blob to dest blob.
So if the ContentEncoding as gzip can tell `Invoke-WebRequest` to unzip the source file. After copy, the dest blob will also has ContentEncoding as gzip, then it should also can make `Invoke-WebRequest` to unzip the dest file.

Besides that, in `Start-AzStorageBlobCopy` the copy process is handled by server , so we can't change the functionality  in Powershell side.

**Comment by Agazoth** [comment]
No, please go ahead and close it.

Thanks for your support.

**Comment by blueww** [comment]
Thanks!
Feel free to contact us again if need any further support on Azure Powershell.
