### ISSUE TITLE
New-AzDataShareDataSet Does not support Azure Synapse Analytics Dataset

### ISSUE THREAD

**Issue by DamolAAkinleye** [Azure/azure-powershell#16997]
### Description of the new feature

The New-AzDataShareDataSet Does not support Azure Synapse Analytics Dataset as source. This is currently supported in the az cli and also in the portal but there is not option for it in the cmdlets.

**Comment by SaurabhSharma-MSFT** [comment]
@DamolAAkinleye It looks only data sets of type Blob, ADLS Gen2 and ADLS Gen1 are supported using New-AzDataShareDataset cmdlet.  I am checking internally with the products team though.

**Comment by sidontha** [comment]
Closing wit link to latest docs - https://learn.microsoft.com/en-us/azure/data-share/overview
