### ISSUE TITLE
get-azresource fails to return resource with tags in pwsh linux

### ISSUE THREAD

**Issue by MrCNeale** [Azure/azure-powershell#16993]
### Description

When running get-azresource against a resource (tested on Automation Account AND KeyVault resource types) which has tags applied.
Pwsh core on windows returns the resource
In linux it does not.
If the tags are removed, linux returns the resource.

### Issue script & Debug output

```PowerShell
get-azresource | ?{$_.name -like '*-SH'}

****
when run in windows a resource with tags is found, when run in linux the same resource is not found
if the tags are removed from the missing resource, the command works in both OSes
resource type does not seem to be a factor. Behaviour is seen for Automation Accounts and KeyVaults
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Windows
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     5.2.0                 Az.Resources

Linux
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     1.7.3                 Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAutomationDscNodeReportContent, Export-AzAutomationRunbook, Get-AzAutomationAccount…}
Script     3.0.0                 Az.Monitor                          {Add-AzAutoscaleSetting, Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzMetricAlertRuleV2…}
Script     3.0.0                 Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, Disable-AzOperationalInsightsLinuxCustomLogCollection, Disable-AzOperationalInsightsLinuxP…
Script     5.2.0                 Az.Resources
```

### Error output

```PowerShell
No error.  Just missing result.
Reproducable locally using pwsh+linux+wsl+ubuntu20.04 and via DevOps using Linux worker agents hosted by MS.
```

**Comment by dingmeng-xue** [comment]
@MrCNeale , thanks for reporting.

I believe this question is PowerShell general question. I tried Alpine with PowerShell 7.2.1 but cannot reproduce it.

Could you try below code?
```
$a = @(@{name="object-BJ"},@{name="object-SH"})
$a | ?{$_.name -like '*-SH'}
# it should return the second object.
```
If above code can get the correct result on WSL, please check whether return result of `Get-AzResource` is expected or not on WSL?

**Comment by MrCNeale** [comment]
I only filtered to make it easier to see what was and wasn't returned.
The problem happens even if you run Get-AzResource on it's own

pwsh in windows 10 terminal
$all = get-azresource
$all.count
319

pwsh in ubuntu in wsl terminal
$all = Get-AzResource
$all.count
310

As you can see 9 less resources are returned in linux/ubuntu
This behaviour is also seen in DevOPs Ubuntu hosts.

**Comment by MrCNeale** [comment]
Within seconds of each other I can run get-azresource multiple times and get differing counts?

PS /mnt/c/Users/xxx/Release/yyy> (Get-AzResource).count
295
PS /mnt/c/Users/xxx/Release/yyy> (Get-AzResource).count
310
PS /mnt/c/Users/xxx/Release/yyy> (Get-AzResource).count
295
PS /mnt/c/Users/xxx/Release/yyy> (Get-AzResource).count
295
PS /mnt/c/Users/xxx/Release/yyy>

**Comment by bowlerma** [comment]
Not sure if it's related to this or not, but we're recently seeing odd behaviour from Get-AzResource.  The list of resources being returned appears to be out of date.

We have created some new web apps, and deleted some old web apps.  When we run Get-AzResource, none of the new web apps are being returned, but some of the web apps that no longer exist are being returned in the results.  They're showing correctly in the Azure Portal.  The same behaviour is being seen with Azure CLI when using az resource list.

We're seeing this behaviour on both Windows and Linux.

Sorry to hijack your thread, but it seems related.

**Comment by MrCNeale** [comment]
I believe I have found the issue.
running get-azlogicapp with -debug (I know it's a different command...stay with me)
and running it frequently I could get fails regularly and passes equally as regularly

I spotted one commonality

The headers of the failed/empty returns came back with an empty body and were "x-ms-routing-request-id" UKSOUTH
The headers of the working/non-empty returns came back with a huge body with all the logicapp json in and were "x-msrouting-request-id" UKWEST


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-resource-requests: 19999
x-ms-request-id               : 361732ea-4c7c-409d-a331-55723743e2e5
x-ms-correlation-request-id   : 361732ea-4c7c-409d-a331-55723743e2e5
x-ms-routing-request-id       : UKSOUTH:20220203T172608Z:361732ea-4c7c-409d-a331-55723743e2e5
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Thu, 03 Feb 2022 17:26:08 GMT

Body:
{
  "value": []
}


DEBUG: AzureQoSEvent: Module: Az.LogicApp:1.5.0; CommandName: Get-AzLogicApp; PSVersion: 7.2.1; IsSuccess: True; Duration: 00:00:00.3573750
DEBUG: Finish sending metric.
DEBUG: 17:26:10 - GetAzureLogicAppCommand end processing.



---------------------------
WORKING RESULT
---------------------------
Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Vary                          : Accept-Encoding
x-ms-request-id               : eastus:b2dffce1-6a26-4d1e-98ef-f7289dbd4b19
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-resource-requests: 19999
x-ms-correlation-request-id   : ac74eb12-ec63-4c31-b2df-f7209bbb5c3c
x-ms-routing-request-id       : UKWEST:20220203T172601Z:ac74eb12-ec63-4c31-b2df-f7209bbb5c3c
X-Content-Type-Options        : nosniff
Date                          : Thu, 03 Feb 2022 17:26:00 GMT

Body:
{
  "value": [
    {
      "properties": {
        "provisioningState": "Succeeded",
        "createdTime": "2022-01-28T12:27:49.7558635Z",
        "changedTime": "2022-02-03T16:41:16.2304917Z",
        "state": "Enabled",

**Comment by dingmeng-xue** [comment]
I believe it is due to the problem on service side.  @armleads-azure , please share more information if any.

**Comment by MrCNeale** [comment]
Hi @dingmeng-xue this has been resolved now.
No code changes were made by us but whatever back end routing/caching/API issue was causing the problem appears to have been fixed

**Comment by dingmeng-xue** [comment]
Thanks for the information. I heard Azure service side may out-of-sync sometimes and make the result different. But as client, Azure PowerShell and our team have no insight on that. We can help to raise the problem to service team. Welcome to contact us.
