### ISSUE TITLE
Publish-AzWebApp throws NullReferenceException

### ISSUE THREAD

**Issue by juliamaureen** [Azure/azure-powershell#17006]
### Description

While trying to deploy an azure function with github actions using the following commands:

Connect-AzAccount -Identity -Subscription ${{ inputs.subscription }} -Tenant ${{ inputs.tenant }}
Publish-AzWebApp -ResourceGroupName ${{ inputs.rg-name }} -Name ${{ inputs.app-name }} -ArchivePath .\build_artifacts.zip

The error we are getting is:
Publish-AzWebApp : Object reference not set to an instance of an object.
At C:\actions-runner\_work\_temp\0fbf4e3d-a2a4-4f6b-beb6-30dfaa6eb18b.ps1:6 char:1
+ Publish-AzWebApp -WebApp $app -ArchivePath 'C:\actions-runner\_work\L ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzWebApp], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.PublishAzureWebAppCmdlet

We were able to fix this by adding the -Force flag to Publish-AzWebApp. Why do we need to use this flag? Resulting working code:

Connect-AzAccount -Identity -Subscription ${{ inputs.subscription }} -Tenant ${{ inputs.tenant }}
Publish-AzWebApp -ResourceGroupName ${{ inputs.rg-name }} -Name ${{ inputs.app-name }} -ArchivePath .\build_artifacts.zip -Force

### Issue script & Debug output

```PowerShell
No information provided by DebugPreference
```

### Environment data

```PowerShell
PS C:\Windows\system32> $PSVersionTable



Name Value
---- -----
PSVersion 5.1.17763.2268
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.17763.2268
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
```

### Module versions

```PowerShell
No data returned
```

### Error output

```PowerShell
Publish-AzWebApp : Object reference not set to an instance of an object.
At C:\actions-runner\_work\_temp\0fbf4e3d-a2a4-4f6b-beb6-30dfaa6eb18b.ps1:6 char:1
+ Publish-AzWebApp -WebApp $app -ArchivePath 'C:\actions-runner\_work\L ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzWebApp], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.PublishAzureWebAppCmdlet
 
Error: Process completed with exit code 1.
```

**Comment by navba-MSFT** [comment]
@juliamaureen Apologies for the late reply. Looking at the [source code](https://github.com/Azure/azure-powershell/blob/2834e8d3ba198ad6e1582befc9a8eb9c6c61a0ff/src/Websites/Websites/Cmdlets/WebApps/PublishAzureWebApp.cs#L113) in PublishAzureWebApp.cs there is a check done for the -Force parameter before the content is deployed. The examples mentioned [here](https://docs.microsoft.com/en-us/powershell/module/az.websites/publish-azwebapp?view=azps-7.1.0#example-5) and [here](https://docs.microsoft.com/en-us/powershell/module/az.websites/publish-azwebapp?view=azps-7.1.0#example-6) has the _-Force_ parameter with its description added to the [Publish-AzWebApp](https://docs.microsoft.com/en-us/powershell/module/az.websites/publish-azwebapp?view=azps-7.1.0) command.  

>-Force
Forcefully Remove Option

The similar issue #10224 #11196

Please let me know if you have any further question on this. Awaiting your reply.

**Comment by juliamaureen** [comment]
Thank you. We ended up figuring it out but couldn't find it documented anywhere that you had to use -force.



Classified - Confidential
