### ISSUE TITLE
[Feature]: Tag latest to Ubuntu 20.04 docker image 

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#17035]
### Description of the new feature

Ubuntu 20.04 has released for almost 2 years (since 2020-04-23). Once we support 20.04, we need to consider to switch latest tag from ubuntu 18.04 to 20.04. We need to be consistent with PowerShell (it's 18.04 for the time being) and change it at Az major release.
 https://hub.docker.com/_/microsoft-powershell

**Comment by wyunchi-ms** [comment]
We need to wait PowerShell team to modify the tag to `ubuntu-20.04` first

**Comment by dingmeng-xue** [comment]
Below content on DockerHub needs to be updated
```
[latest](https://github.com/Azure/azure-powershell/tree/main/docker/Dockerfile-ubuntu-18.04): The image with the latest stable Azure PowerShell modules.
Ubuntu 18.04
docker pull mcr.microsoft.com/azure-powershell:latest
```
