### ISSUE TITLE
New-AzureRmNetworkSecurityRuleConfig protocol names case issue

### ISSUE THREAD

**Issue by AndrevdG** [Azure/azure-powershell#1715]
New-AzureRmNetworkSecurityRuleConfig and Add-AzureRmNetworkSecurityRuleConfig correctly validate that whatever is applied to -Protocol comes from the set "Tcp, Udp, *". However, it does not check capitalization.

The commands accept TCP, TCp, tcp als correct protocol names and it does apply. However if you check the rule created in the portal, the protocol section there will have no selection and the rule is also not (correctly) applied. The only input that leads to the desired result is "Tcp"

**Comment by cormacpayne** [comment]
The documentation for these cmdlets have been updated to reflect the valid values for the `Protocol` parameter. Closing this issue.
