### ISSUE TITLE
ConnectedPrivateLinkScope should be ConnectedMachinePrivateLinkScope

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#17150]
### Description

Below cmdlets in Az.ConnectedMachine should be renamed and use ConnectedMachine as prefix.

Get-AzConnectedPrivateLinkScope
New-AzConnectedPrivateLinkScope
Remove-AzConnectedPrivateLinkScope
Set-AzConnectedPrivateLinkScope
Update-AzConnectedExtension
Update-AzConnectedPrivateLinkScopeTag

### Issue script & Debug output

```PowerShell
NA
```

### Environment data

```PowerShell
NA
```

### Module versions

```PowerShell
NA
```

**Comment by dorothyhu** [comment]
@dingmeng-xue  In that case, doesn't our Connect-AzConnectedMachine becomes Connect-AzConnectedMachineMachine?

**Comment by dingmeng-xue** [comment]
No. only `ConnectedPrivateLinkScope` and `ConnectedExtension` are too common.

**Comment by dorothyhu** [comment]
@dingmeng-xue I mean, we have the machines, extensions and the privatelinkscopes types. If we use AzConnectedMachine as the prefix, wouldn't the machines operations become something like Connect-AzConnectedMachineMachine
