### ISSUE TITLE
Handling of spaces in resource IDs

### ISSUE THREAD

**Issue by bvirkler** [Azure/azure-powershell#1717]
Some of the resources that are automatically provisioned when a Web App is created are named with spaces.

    PS Gitlab:\PowerShell> $alertRule

    Name              : CPUHigh policytest
    ResourceId        : /subscriptions/b4cad802-xxx/resourceGroups/bav-group/providers/microsoft.insights/alertrules/CPUHigh policytest
    ResourceName      : CPUHigh policytest
    ResourceType      : microsoft.insights/alertrules
    ResourceGroupName : bav-group
    Location          : northeurope
    SubscriptionId    : b4cad802-xxx
    Tags              : {System.Collections.Hashtable}

Azure PowerShell seems to translate the space in the resource name/ID to a plus sign.  The ARM API then says it can't find the resource:

    PS Gitlab:\PowerShell> Get-AzureRmResource -ResourceId $alertRule.ResourceId
    Get-AzureRmResource : ResourceNotFound : The Resource 'microsoft.insights/alertrules/CPUHigh+policytest' under resource group 'bav-group' was not found.
    At line:1 char:1
    + Get-AzureRmResource -ResourceId $alertRule.ResourceId
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : CloseError: (:) [Get-AzureRmResource], ErrorResponseMessageException
        + FullyQualifiedErrorId : ResourceNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet

If I instead replace the space with `%20` then I get the expected result.  

    PS Gitlab:\PowerShell> Get-AzureRmResource -ResourceId $alertRule.ResourceId.Replace(" ", "%20")

    Name              : CPUHigh policytest
    ResourceId        : /subscriptions/b4cad802-xxxx/resourceGroups/bav-group/providers/microsoft.insights/alertrules/CPUHigh policytest
    ResourceName      : CPUHigh policytest
    ResourceType      : microsoft.insights/alertrules
    ResourceGroupName : bav-group
    Location          : North Europe
    SubscriptionId    : b4cad802-xxxx
    Tags              : {System.Collections.Hashtable}
    Properties        : @{Name=CPUHigh policytest; Description=The average CPU is high across all the instances of policytest; Condition=; Action=; LastUpdatedTime=2016-01-07T15:38:24.5501526Z; 
                        ProvisioningState=Succeeded; Actions=System.Object[]}

I'm not sure if PowerShell should use `%20` instead of `+`, or if ARM should translate `+` to space.

**Comment by markcowl** [comment]
@bvirkler Thankls for the report, we are looking into this.

**Comment by markcowl** [comment]
@vivsriaus Vivek, Looks likethis is an issue with round-tripping the identity value from the server

**Comment by ravbhatnagar** [comment]
Lets fix.

**Comment by vivsriaus** [comment]
Thanks for reporting this issue. This will be fixed in the upcoming Azure powershell release.

**Comment by ravbhatnagar** [comment]
Fixed - 3/3 PS release
