### ISSUE TITLE
[Doc]: Get-AzWebApp needs to make -ResourceGroupName a required parameter for optimal results

### ISSUE THREAD

**Issue by Xingyixzhang** [Azure/azure-powershell#17184]
### Document Link
https://docs.microsoft.com/en-us/powershell/module/az.websites/get-azwebapp?view=azps-7.2.0&viewFallbackFrom=azps-7.2

### Issue
The command below with and without the -ResourceGroupName parameter returns different results, yet the document does not specify that the -ResourceGroupName should be a required field.
```ps
$apps = Get-azWebApp (-ResourceGroupName)

foreach($a in $apps){
    $a.name
    $a.siteconfig.FtpsState
}
```

### Demonstration on Expected Results (with the parameter, the FtpsState value showed up correctly)
![image](https://user-images.githubusercontent.com/59896882/154751249-5660f8f5-7023-482e-beba-2502665bb33f.png)

### Demonstration on Actual Results (without the parameter, the FtpsState value showed up null)
![image](https://user-images.githubusercontent.com/59896882/154751565-0b770bf1-9912-401a-864b-b7db605f181a.png)

### Additional findings
Many other values are missing when the -ResourceGroupName parameter is not set. Feel free to check full detailed **SiteConfig** comparisons running the following commands:
```ps
Get-azWebApp | ConvertTo-Json
Get-azWebApp -ResourceGroupName "YourRGName" | ConvertTo-Json
```

### Recommendation
Make the -ResourceGroupName a required parameter so that customers can achieve the desired results.

**Comment by navba-MSFT** [comment]
@Xingyixzhang Apologies for the late reply. I am looking into this issue. I will get back on this thread once I have more details on this.

**Comment by navba-MSFT** [comment]
@Xingyixzhang Please check the similar issue being reported here #9168.

As a workaround, you can get the consistent result using the [Get-AzResource](https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azresource?view=azps-7.2.0) PS cmdlet.

>$siteConfig = Get-AzResource -ResourceGroupName 'MyRGName' -Name 'MyResourceName' -ResourceType Microsoft.Web/sites/config -ApiVersion 2021-03-01
>
>$siteConfig.Properties.ftpsState

cc: @panchagnula

**Comment by panchagnula** [comment]
@Xingyixzhang / @navba-MSFT making an argument required from optional is a breaking change since currently this command can be run on Sub level, RG level or app level. @navba-MSFT we should close since this is not possible for now.

**Comment by navba-MSFT** [comment]
Thanks @panchagnula for your reply.

@Xingyixzhang I hope you had a chance to look at the above comment. We will now proceed with the closure as this feature would be a breaking change and not it is not possible to add now. If you have any further questions, please feel free to reopen this thread.
