### ISSUE TITLE
[Feature]: Implement domain join Setting to Add-AzVMAdditionalUnattendContent

### ISSUE THREAD

**Issue by tim-krehan** [Azure/azure-powershell#17225]
### Description of the new feature

Hello Together :)

I currently try to set up an automated way to join a newly created VM to an active directory, using an offline domainjoin.
Currently I am using the command "djoin" to request the local (newly created) vm to perform said domain join.

Isn't it possible to add another settings section to the command [Add-AzVMAdditionalUnattendContent](https://github.com/Azure/azure-powershell/blob/cf539d14a27eb4d5b794f632cd814342fa0c9599/src/Compute/Compute/help/Add-AzVMAdditionalUnattendContent.md)?

With that one could just add the base64 blob to the /component/identification/provisioning/accountdata and create the vm, that will automatically join the domain.

### Proposed implementation details (optional)

``` powershell
$base64blob = ".....";
$VirtualMachine = Get-AzVm -ResourcegroupName "rg-company-001" -Name "vmcompany001";
$AucContent = "<Identification><Provisioning><AccountData>" + $base64blob + "</AccountData></Provisioning></Identification>";
$VirtualMachine = Add-AzVMAdditionalUnattendContent -VM $VirtualMachine -Content $AucContent -SettingName "UnattendedJoin";
```

**Comment by tim-krehan** [comment]
The Syntax of the relevant part of the [unattend.xml](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd392267(v=ws.10)?redirectedfrom=MSDN) should be as follows:
``` xml
<Component>
<Component name=Microsoft-Windows-UnattendedJoin>
     <Identification>
          <Provisioning>
               <AccountData>Base64Encoded Blob</AccountData>
          </Provisioning>
     </Identification>
</Component>
```

**Comment by Drewm3** [comment]
@avirishuv, could you please look into this one.

**Comment by avirishuv** [comment]
Assigning to @oriwolman and @TravisCragg-MSFT to take a look at this issue.

**Comment by TravisCragg-MSFT** [comment]
I have made this into [a feature request Here at feedback.azure.com](https://feedback.azure.com/d365community/idea/2d3ac847-3c98-ed11-a81b-000d3ae5ae95).

Please vote for the feature and give additional feedback if you would like us to prioritize this feature.
