### ISSUE TITLE
Select-AzureRmSubscription failing with error Subscription not found

### ISSUE THREAD

**Issue by naman2710** [Azure/azure-powershell#1725]
Hi ,
I have the below query 
Get-AzureRmSubscription –SubscriptionName $DefaultSubscription | Select-AzureRmSubscription
Running the above query with proper $DefaultSubscription variable I am getting below error,
Get-AzureRmSubscription : Subscription "....." was not found in tenant . Please verify that the subscription exists in this tenant.

However the same works if I use below
Get-AzureRmSubscription –SubscriptionId $DefaultSubscriptionId | Select-AzureRmSubscription

So wanted to know why cant we use subscription name, are we supposed to use only subscription id

-Naman

**Comment by markcowl** [comment]
@naman2710 What version of the AzureRM.Profile module are you using when you see this?  Also, what kinds of credentials are you using?  Are you certain that the name exactly matches the name in Azure of the subscription?

**Comment by markcowl** [comment]
@naman2710 I cannot repro this with version 1.2.0 of the cmdlets, wven when selecting subscriptiosn from different tenants.  Closing this as no repro.  If you can rerpdocue this issue on the latest version, please reopen and provide the debug log (use $DebugPreference="Continue" when executing your cmdlet or script).

**Comment by dewanymca** [comment]
I got into same issue I am using Login-AzureRMAccount command with service principal option, however when I run Select-AzureRMSubscription I am getting below error:Select-AzureRmSubscription : Provided subscription c2403b7f-d35b-405a-bccf-d954202081ef does not exist



Same thing works on my machine and fails on Azure Automation Account runbook,
