### ISSUE TITLE
[Feature]: Az.PostgreSql - Add option to enable/disable public network access

### ISSUE THREAD

**Issue by janegilring** [Azure/azure-powershell#17263]
### Description of the new feature

An option to enable/disable public network access for Azure PostgreSQL Servers would be useful, as this is a common setting to configure. As far as I can see, it is not possible to configure this setting in the 1.0.0 version of the Az.PostgreSql module.

### Proposed implementation details (optional)

One option could be adding a new parameter, -PublicNetworkAccess, to the Update-AzPostgreSqlServer command:

```
            Update-AzPostgreSqlServer -Name mypgserver -ResourceGroupName pg-rg -PublicNetworkAccess Enabled
            Update-AzPostgreSqlServer -Name mypgserver -ResourceGroupName pg-rg  -PublicNetworkAccess Disabled
```

**Comment by dingmeng-xue** [comment]
[API](https://github.com/Azure/azure-rest-api-specs/blob/429a7ea873cc1bbd4df133f71427162e15e258b1/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2017-12-01/postgresql.json#L1882)  defined it but parameter was removed from implementation https://github.com/Azure/azure-powershell/blob/main/src/PostgreSql/custom/Update-AzPostgreSqlServer.ps1

@msJinLei , do you recollect the reason?

**Comment by nachoalonsoportillo** [comment]
This was implemented long time ago. Closing issue.
