### ISSUE TITLE
[Feature]: Add-VHD - AutoShrink / Resize / Size Parameter

### ISSUE THREAD

**Issue by fowl2** [Azure/azure-powershell#17271]
### Description of the new feature

#15994 added automatic resizing of VHDs to meet allignment requirements, it would be great if there was a parameter that could influence the resulting size.

eg.

`-AutoShrink [:$false]` Resizes the new VHD to the _MinimumSize_.
`-NewSize [$bytes]` Specifices the size of the destination VHD. Will be rounded up to meet allignment requirements. If it the rounded size is smaller than _MinimumSize_, an error will be generated.

etc.

**Comment by navba-MSFT** [comment]
@fowl2 Thanks for reaching out to us and sharing this feedback. I am looking into this and I'll and get back on this thread with an update.

**Comment by navba-MSFT** [comment]
Adding the **Service Attention** team for the _Feature Request_ ask. I see that you have created another #17274 as well. I will also be updating the Service Teams to update both the threads once they get a chance.

**Comment by navba-MSFT** [comment]
@Drewm3, @avirishuv, @Vaibhav-Agar, @amjads1 Could you please look into this and provide an update on #17271 and #17274 once you get a chance ? Awaiting your reply.

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by jaylabell** [comment]
@grizzlytheodore can you please look into this issue?

**Comment by grizzlytheodore** [comment]
@fowl2 thank you for your input. 
With consideration of the effort and benefit of this feature and priorities from other parts of Azure Compute, this feature will not be in our plans for timebeing. Thank you

**Comment by fowl2** [comment]
@grizzlytheodore would a community contribution of this feature be accepted?
