### ISSUE TITLE
New-AzImageBuilderTemplate needs to support vmProfile.userAssignedIdentity

### ISSUE THREAD

**Issue by rcarde** [Azure/azure-powershell#17273]
### Description of the new feature

The ImageBuilder API version 2021-10-01 and newer supports adding a user assigned identity to the build VM itself to allow access to resources in the same tenant.

This is documented here:
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-json#user-assigned-identity-for-the-image-builder-build-vm

### Proposed implementation details (optional)

Add a `-VMProfileUserAssignedIdentity` parameter to provide a reference to an identity (or array of identities) used by the VM during running of customisations.

**Comment by dingmeng-xue** [comment]
We will evaluate and update module.

**Comment by BethanyZhou** [comment]
Will upgrade API version to 2022-02-14 and add a parameter named VMProfileUserAssignedIdentity to support this feature. Expected delivery date is 2022-09-06.

**Comment by BethanyZhou** [comment]
Please expect this feature supported Az.ImageBuilder 0.3.0. It will be on Sept 6th.
