### ISSUE TITLE
Custom URI Option not supported

### ISSUE THREAD

**Issue by pranavsista** [Azure/azure-powershell#17285]
### Description

The AZ Storage Powershell module does not seem to support passing a custom URI, similar to the functionality provided by other Azure SDK Clients like C# , Java , Javascript etc.
For eg, the data lake client constructor supports usage of client by passing passing a custom URI. This is not supported in powershell.
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakeserviceclient.-ctor?view=azure-dotnet#azure-storage-files-datalake-datalakeserviceclient-ctor(system-uri)

Overall, these are the issues I have.
 
1). In the current powershell implementation, is there no option to specify the absolute url? I thought the 'endpoint' parameter fulfilled that role but it looks like we can only input the domain here (like 'core.windows.net'). For example - 
<img width="952" alt="image" src="https://user-images.githubusercontent.com/100203509/157009868-6384a834-57e6-44f2-adb2-626cc4ca2cda.png">

2). The Storage account name is being mandated for all scenarios except for scenarios using the connection string to connect to a storage account and using a local development storage account. Can an option to specify the absolute url be provided without mandating the storage account name?

3). As discussed previously, can an option to connect to a storage account similar to the below link be provided?
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakeserviceclient.-ctor?view=azure-dotnet#azure-storage-files-datalake-datalakeserviceclient-ctor(system-uri)

### Issue script & Debug output

```PowerShell
PS C:\WINDOWS\system32> New-AzStorageContext

cmdlet New-AzStorageContext at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
StorageAccountName:

The link below doesn't ask for the storage account name and uses only the custom uri to connect to it.
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakeserviceclient.-ctor?view=azure-dotnet#azure-storage-files-datalake-datalakeserviceclient-ctor(system-uri)
```

### Environment data

```PowerShell
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS C:\WINDOWS\system32> Get-Module Az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.7.2      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Conn...
Script     4.2.0      Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountMa...
```

**Comment by dingmeng-xue** [comment]
@pranavsista , could you provide an example of custom URI? Does it include endpoint, API path and API version?

**Comment by pranavsista** [comment]
@dingmeng-xue An example of this would be something like myproxyservice.azurewebsites.net

The Uri is a service which is hosted in azure and it can be used as a proxy to connect to storage accounts from the proxy service.

**Comment by dingmeng-xue** [comment]
Azure PowerShell is different from SDK. The service client construction is not exposed to end user. Some information required by service client is populated by Azure PowerShell framework based on context. 

@blueww , I don't familiar to Storage API. Is it possible to get all required information according to user's input.

**Comment by pranavsista** [comment]
@blueww  I explored the option of using a connection string but it requires having details about the storage account. It will be the proxy service which will route the user to an appropriate storage account. The user will not know the name of the storage account or have a SAS token and will only have the endpoint with them. I'm essentially looking for functionality which is similar to what is present below - where a constructor just takes an endpoint to connect to a storage account.

https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakeserviceclient.-ctor?view=azure-dotnet#azure-storage-files-datalake-datalakeserviceclient-ctor(system-uri)

**Comment by blueww** [comment]
For Powershell, you can also just create storage context with connection string, without input addtional information like storage account: 

If you only have service endpoint and SAS, you can format the connection string like the sample: https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#account-sas-example
The Powershell sample would look like: 
```powershell
New-AzStorageContext -ConnectionString "BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;SharedAccessSignature=sv=2015-07-08&sig=iCvQmdZngZNW%2F4vw43j6%2BVz6fndHF5LI639QJba4r8o%3D&spr=https&st=2016-04-12T03%3A24%3A31Z&se=2016-04-13T03%3A29%3A31Z&srt=s&ss=bf&sp=rwl"
```

**Comment by blueww** [comment]
@pranavsista 
This looks not supported in PowerShell currently to create a storage context with only blob service endpoint and anonymous credential.
I will try to raise a fix for that soon.

Would you like to share more about which scenario you would like to run Powershell, then I get more understanding of the usage. Like:

> Which blob cmdlet you would like to run?
> How your Uri looks like? (hide any credential)

Besides that, as a workaround, you can just create the SDK object in Powershell console and run blob scenarios with it, like:
```powershell
$serviceClient = New-object Azure.Storage.Files.DataLake.DataLakeServiceClient -ArgumentList (new-object System.Uri -ArgumentList  "https://accountname.blob.core.windows.net/")
$serviceClient.CreateFileSystem()
$serviceClient.GetFileSystemClient("containerName").GetPaths()
```

**Comment by pranavsista** [comment]
@blueww  Thanks for the workaround, I'll try it out and get back to you. As for the scenario, the user will not know the name of the storage account while using the client. The user will mention a proxy service endpoint which will internally resolve to a specific storage account.

Could you provide an ETA for when the fix can be done? Thanks!

**Comment by pranavsista** [comment]
@blueww  I've tried exploring how we can allow a custom endpoint to connect to a storage account and this is the draft PR we have made which contains an implementation for that functionality.

https://github.com/Azure/azure-powershell/pull/17226

**Comment by blueww** [comment]
@pranavsista 
I will try to fix it by support customize endpoint for blob/table/queue/file endpoint, for key/sas/oauth/anonymous authentication.
I will need some time to write code and test it, will target to next or the one after next release. See release schedule in https://github.com/Azure/azure-powershell/milestones

**Comment by pranavsista** [comment]
@blueww Overall, these are the issues I have.
 
1). In the current powershell implementation, is there no option to specify the absolute url? I thought the 'endpoint' parameter fulfilled that role but it looks like we can only input the domain here (like 'core.windows.net'). For example - 
<img width="952" alt="image" src="https://user-images.githubusercontent.com/100203509/157009868-6384a834-57e6-44f2-adb2-626cc4ca2cda.png">

2). The Storage account name is being mandated for all scenarios except for scenarios using the connection string to connect to a storage account and using a local development storage account. Can an option to specify the absolute url be provided without mandating the storage account name?

3). As discussed previously, can an option to connect to a storage account similar to the below link be provided?
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakeserviceclient.-ctor?view=azure-dotnet#azure-storage-files-datalake-datalakeserviceclient-ctor(system-uri)

**Comment by blueww** [comment]
@pranavsista 
I believe the fix to support customized endpoint (for B/T/Q/F service) with all kinds of credential: Key/SAS/Oauth/Anomymous, should can work fir all the above 3 issues.

**Comment by pranavsista** [comment]
@blueww Were ADLS endpoints factored in when making the change? It looks like only four specific endpoints can be provided above to get the context. What should be done if an ADLS endpoint is available?

Ex: - https://<account-name>.dfs.core.windows.net/

**Comment by pranavsista** [comment]
@blueww Also, is it necessary to provide all the endpoint for the blob, table, queue, and file? Wouldn't having to provide only one endpoint be sufficient? Like this - 

$ctx = New-AzStorageContext -CustomEndpoint "https://accountname.blob.core.windows.net/"

**Comment by blueww** [comment]
@pranavsista 
Normally, endpoint of B/T/Q/F of a storage account are all different. so we can't only provide a single endpoint.
If they are same in your case, you can input Bt/T/Q/F endpoints as same value when using the cmdlet.

**Comment by blueww** [comment]
@pranavsista 
Powershell release Az.7.4.0 is already released, which support create storage context with customized B/T/Q/F endpoint.
I will close this issue as its already supported in PSH.

Feel free to contact us again if need any further assistance on Azure Powershell.
