### ISSUE TITLE
Invoke-AzStorageSyncChangeDetection not working as documented

### ISSUE THREAD

**Issue by tradiuz** [Azure/azure-powershell#17330]
### Description

When following the docs to initiate a change detection job, the following command doesn't actually start anything.  It just runs with no feedback one way or the other.

```
Invoke-AzStorageSyncChangeDetection -ResourceGroupName <rgname> -StorageSyncServiceName <syncservicename> -SyncGroupName <syncgroupname> -Name <syncendpointname>
```

Using the ResourceID variation of the command, does work.

```
Invoke-AzStorageSyncChangeDetection -ResourceId /subscriptions/<subscriptionid>/resourceGroups/<rgname>/providers/microsoft.storagesync/storageSyncServices/<syncservicename>/syncGroups/<syncgroupname>/cloudEndpoints/<syncendpointname>
```

### Issue script & Debug output

```PowerShell
I don't have time to sanitize this output.  Y'all need a way to invoke this that scrubs all the subscription/tenant/login/etc data out.  Asking users (who are all probably paying a lot of money to Microsoft) to go through it to help you fix your broken code is not going to work in your favor.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.2                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     1.6.1                 Az.StorageSync                      {Get-AzStorageSyncCloudEndpoint, Get-AzStorageSyncGroup, Get-AzStorageSyncServer, Get-AzStorageSyncServerEndpoint…}
```

### Error output

```PowerShell
No error output (related to this command).
```

**Comment by SaurabhSharma-MSFT** [comment]
@tradiuz Are you passing the correct name, which is a GUID, not the friendly name that's displayed in the portal?

To get the CloudEndpointName, use the Get-AzStorageSyncCloudEndpoint cmdlet.  Please use `Get-AzStorageSyncCloudEndpoint`

**Comment by tradiuz** [comment]
I was using the friendly name, because that's what logic would dictate for a parameter called "Name"...  Although, that doesn't explain why the command doesn't throw an error or provide any user feedback.  There's not an easy way to pull the GUID from the console, compared to getting the resourceID.

**Comment by SaurabhSharma-MSFT** [comment]
@tradiuz Like I mentioned earlier you can use `Get-AzStorageSyncCloudEndpoint` to get the respective GUID.  See below -
![image](https://user-images.githubusercontent.com/38112130/157131759-2bf864ee-2239-47ea-baed-167523b6901a.png)
 
Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@tradiuz ok, get it. I am redirecting this to respective team to look into this.

**Comment by SaurabhSharma-MSFT** [comment]
@ankushbindlish2 @Fedyashov Do you have any suggestions on this issue.

**Comment by geolivo** [comment]
Hi @tradiuz , first make sure that you are running version 1.7.0 of Az.StorageSync. The Invoke-AzStorageSyncChangeDetection cmdlet had a bug in previous versions that prevented users from running the default parameter set (your first snippet) in full share detection mode. 

Agreed that output should be displayed to indicate whether the cmdlet execution was successful. Currently the only way to do so is to confirm that the "Change Enumeration" section of the portal has been updated with the timestamp when you called the cmdlet (the PSCloudEndpoint object also has a ChangeEnumerationStatus property). We'll need to take this as a bug and follow up with a fix.

**Comment by geolivo** [comment]
Apologies for the delay on this. I haven't been able to repro with version 1.6.1 or version 1.7.0 - my attempt to trigger detection for a CEP that doesn't exist _does_ surface a useful exception.

This cmdlet kicks off an action in the cloud and it doesn't have an object to write to the output pipe, so in this case it is standard practice for PowerShell cmdlets not to return anything upon success. You can also run the cmdlet with the -Verbose or -Debug flags to get a more granular view into what it's doing.

@tradiuz , if you can still repro this, please run the cmdlet with -Debug for finer details about where the failure might be coming from. If the cmdlet hangs, we will need the debug output/request details to investigate further.

Closing for now since the thread is getting old, but please reopen if you can repro.
