### ISSUE TITLE
Switch-AzureWebsiteSlot equivalent for ARM

### ISSUE THREAD

**Issue by hallatore** [Azure/azure-powershell#1736]
We need a way to switch web app slots using ARM.

You can already start, stop, add, remove, etc in ARM. Switch is the only mssing cmdlet.

PS: We cannot use Service Manager as our user is only assigned to a resource group and we cannot use service certificates.

**Comment by demyte** [comment]
Is there a way of doing this in ARM without this command?

**Comment by hallatore** [comment]
@hovsepm Any idea of the scope of this? Or any workaround?

**Comment by loekd** [comment]
$ParametersObject = @{targetSlot  = "[slot name – e.g. “production”]"}
Invoke-AzureRmResourceAction -ResourceGroupName [resource group name] -ResourceType Microsoft.Web/sites/slots -ResourceName [web app name]/[slot name] -Action applySlotConfig -Parameters $ParametersObject -ApiVersion 2015-07-01

from 
https://azure.microsoft.com/nl-nl/documentation/articles/web-sites-staged-publishing/

**Comment by hallatore** [comment]
Thanks. This works perfectly.

**Comment by hallatore** [comment]
Using Invoke-AzureRmResourceAction is good enough. Even though it's hard to find without the proper documentation.
