### ISSUE TITLE
Azure Powershell New-AzSynapseManagedPrivateEndpoint Definition File format?

### ISSUE THREAD

**Issue by jonyjesus18** [Azure/azure-powershell#17388]
### Description

I'm trying to deploy a managed private endpoint to my synapse instance to connect it to a key Vault in the same resource Group. The documentation for the same deployment in Bicep is very incomplete so I thought to try my luck with PowerShell using the following command :

```
    New-AzSynapseManagedPrivateEndpoint `
   -WorkspaceName "synapse-test-joao" `
   -Name "managedPrivateEndpointKeyVault" `
   -DefinitionFile file.json
```
However, I cannot seem to find the format for the definition file anywhere on the internet, so was wondering if anyone had any information regarding the json format and what parameters need to go inside. This would be immensely helpful, Joao

**Comment by SaurabhSharma-MSFT** [comment]
@jonyjesus18 Your definition file should look like the sample provided on [Managed Private Endpoints - Create REST API]( https://docs.microsoft.com/en-us/rest/api/synapse/data-plane/managed-private-endpoints/create#create-a-managed-private-endpoint).  For example, for a storage account you could be using something like below - 
```
{
  "properties": {
    "privateLinkResourceId": "/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/myResourceGroup/providers/Microsoft.Storage/accounts/myStorageAccount",
    "groupId": "blob"
  }
}
```
Please let me know in case any other questions.
Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@jonyjesus18 We haven't heard back from you.  Please let me know if you have any questions else we will proceed with the closure of this issue. Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@jonyjesus18 We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
