### ISSUE TITLE
New-AzStorageContext Forbidden with SAS token from Azure Storage Explorer

### ISSUE THREAD

**Issue by FingerlessGlov3s** [Azure/azure-powershell#17391]
### Description

I'm trying to query/add/update/delete from a Table in a Storage account, using a SAS token.

I went in to the Azure Storage explorer navigated to the table, right click and clicked `get shared access signature`, I then ticked all permissions and pressed `Create`. When I go to use this in my PowerShell script using `New-AzStorageContext`, it returns ok but soon as I try get the the table with `Get-AzStorageTable`, it errors saying forbidden. If I get a sas token generate at the storage account level itself, it'll work but I wish to only have a SAS token that can read/write the one table.

### Issue script & Debug output

```PowerShell
$storageAccountContext = New-AzStorageContext -StorageAccountName $storageAccountName -SasToken "SAS_HERE" -ErrorAction Stop
$storageTable = Get-AzStorageTable -Name $storageAccountTable -Context $storageAccountContext -ErrorAction Stop

Get-AzTableRow -Table $storageTable.CloudTable -PartitionKey $TagSuffix -RowKey $tag
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name
---------- -------    ----
Script     2.7.3      Az.Accounts
Script     4.15.0     Az.Compute
Script     4.10.0     Az.Network
Script     5.4.0      Az.Resource
Script     4.3.0      Az.Storage
Manifest   2.1.0      AzTable
```

### Error output

```PowerShell
Message        : Forbidden
StackTrace     :    at Microsoft.WindowsAzure.Commands.Storage.Model.Contract.StorageTableManagement.DoesTableExist(CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext)
                    at Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTableCommand.<ListTablesByName>d__12.MoveNext()
                    at Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTableCommand.WriteTablesWithStorageContext(IEnumerable`1 tableList)
                    at Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTableCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Cosmos.Table.StorageException
InvocationInfo : {Get-AzStorageTable}
Line           :         $storageTable = Get-AzStorageTable -Name $storageAccountTable -Context $storageAccountContext -ErrorAction Stop
Position       : At line:2 char:25
                 + ... rageTable = Get-AzStorageTable -Name $storageAccountTable -Context $s ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 111
```

**Comment by blueww** [comment]
@FingerlessGlov3s

Please share how you generate the SAS token. Is it a sas for signal table ? If so, it will not have permission to get table.
Sas for single table can't not be used to get table, it can only be used to do operation inside table.
You can generate an account SAS for this action like:

```powershell
$Context = (Get-AzureRmStorageAccount -ResourceGroupName $resourceGroup -Name $storageAccount).Context
$sas = New-AzStorageAccountSASToken -Service Table -ResourceType Service,Container,Object -Permission raul -ExpoiryTime (Get-Date).AddDays(7) -Context $Context
```

For the SAS permission, you can reference: https://docs.microsoft.com/en-us/rest/api/storageservices/Constructing-an-Account-SAS?redirectedfrom=MSDN 
For Table Rest API, you can reference: https://docs.microsoft.com/en-us/rest/api/storageservices/table-service-rest-api

**Comment by FingerlessGlov3s** [comment]
@blueww My token is as follows `?st=2022-03-07T16%3A21%3A53Z&se=2022-03-08T16%3A21%3A53Z&sp=raud&sv=2018-03-28&tn=mytable` it doesn't have "l". I wish to query out table rows, and amend them if required. Can I do this with my SAS token?

```
Get-AzTableRow -Table $storageTable.CloudTable -PartitionKey $partKey -RowKey $rowKey
```

Am I only able to do this via the REST API and not by PowerShell module?

**Comment by blueww** [comment]
@FingerlessGlov3s 

As the sas doesn't have "l" permission, you can't use it to run get-AzStorageTable, but you can use it to create a CloudTable object, and use the cloudtable object to run Get-AzTableRow.
e.g.:
```powershell
$sas = "?st=2022-03-07T16%3A21%3A53Z&se=2022-03-08T16%3A21%3A53Z&sp=raud&sv=2018-03-28&tn=mytable"
$cloudTable = new-object Microsoft.Azure.Cosmos.Table.CloudTable -ArgumentList (new-object System.Uri -ArgumentList "https://accountname.table.core.windows.net/tablename$($sas)")
Get-AzTableRow -Table $cloudTable -PartitionKey $TagSuffix -RowKey $tag
```

**Comment by FingerlessGlov3s** [comment]
Thank you that's just what I was after.

**Comment by blueww** [comment]
@FingerlessGlov3s 
Good to know it work for you.
I will close this issue.
Feel free to contact us again if nee any further assistance on Azure Powershell.
