### ISSUE TITLE
Set-AzAppServicePlan removes existing Tags on Resource

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#17408]
### Description

Updating an existing WebAppPlan will remove Tags on the Resource.

### Issue script & Debug output

```PowerShell
Fetching Tags from an App-ServicePlan


PS> $demo = Get-AzAppServicePlan
$demo.Tags
```

returns (as expeced)
```
Key     Value
---     -----
Demotag foobar
```

Now I am updating the App-ServicePlan

`PS> $update = Set-AzAppServicePlan -Name myapp -ResourceGroupName myrg -Tier PremiumV2`

The Tag disapeared ...

```
PS> $update.Tags

Key     Value
---     -----
```

Bug or Feature?
```


### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.8.3                 Az.Websites
```

**Comment by SaurabhSharma-MSFT** [comment]
@Gill-Bates I have tried this with module version `2.8.3` and I am not seeing any issues with it and tags are not getting deleted.
![image](https://user-images.githubusercontent.com/38112130/157560232-2e4b73dd-b65d-4060-bfa7-fef118d6df27.png)
Can you please try running Set $DebugPreference='Continue' before running the repro and provide the resulting debug stream over here?

**Comment by SaurabhSharma-MSFT** [comment]
@Gill-Bates We haven't heard back from you.  Please share the required information for further investigation.

**Comment by SaurabhSharma-MSFT** [comment]
@Gill-Bates Please let us know if you need any help on this else, we will proceed with the closure of this case.

**Comment by SaurabhSharma-MSFT** [comment]
@Gill-Bates We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Comment by Kotasudhakarreddy** [comment]
An IcM investigation is going on this issue.

**Comment by Gill-Bates** [comment]
The error does not always occur regularly.

**Comment by Kotasudhakarreddy** [comment]
@SaurabhSharma-MSFT - Sorry for reopening it. I have reacted to a wrong thread. 
@Gill-Bates - Issue is unable to repro. Please use the latest `Az.Websites` module and try.
