### ISSUE TITLE
Set-AzResource fails with "The value of parameter api-version is invalid"

### ISSUE THREAD

**Issue by blindvalentine** [Azure/azure-powershell#17415]
### Description

Set-AzResource is throwing an error "The value of parameter api-version is invalid". I have tested this with the latest version and previous Az 7.0 versions

### Issue script & Debug output

```PowerShell
Set-AzResource `
      -ResourceId $((Get-AzResource `
      -ResourceName "$env:gallery_name" `
      -ResourceGroupName "$env:gallery_resource_group_name").ResourceId) `
      -Tags $script:tags `
      -ApiVersion 2022-01-03 `
      -Force ;
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
7.3.0
7.2.0
7.1.0
```

### Error output

```PowerShell
InvalidParameter : The value of parameter api-version is invalid.
```

**Comment by dingmeng-xue** [comment]
You can get more information after turning on debug message via `$DebugPreference = "Continue"`

**Comment by SatishBoddu-MSFT** [comment]
Hello @blindvalentine 

 -ApiVersion 2022-01-03  is it the valid API version? Can you provide the referred documentation?

Have you tried other API versions?

![image](https://user-images.githubusercontent.com/62923178/157916206-c7ed1eba-c2b4-42b7-989e-d30685636718.png)

**Comment by blindvalentine** [comment]
The API versions were listed from the cmdlet. The cmdlet is working now, seems to be a backend problem. Closing the this issue now.
