### ISSUE TITLE
Latest Az.Accounts version 2.7.3 breaks applications with an older versions of Az (in this case 3.8.0) 

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-powershell#17413]
### Description

Customers in Azure Functions started to report issues for some of their apps when `Az.Accounts` version `2.7.3` was released. To mitigate this issue, the customers pinned their apps to the previous version of `Az.Accounts` `2.7.2`. 

### Issue script & Debug output

```PowerShell
Install-Module -Name Az -RequiredVersion 3.8.0

Try to login and you will get an exception.
```

### Environment data

```PowerShell
PS E:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.6
PSEdition                      Core
GitCommitId                    7.0.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
3.8.0; however, this issue is probably affecting other previous versions
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Please provide an environment with detailed steps.

**Comment by Francisco-Gamino** [comment]
This issue was only affecting PowerShell 6.2 users and it was resolved by the released of Az.Accounts `2.7.4`. Closing issue.
