### ISSUE TITLE
[Feature]: New cmdlets requirement for setting public Access configuration for App Configuration

### ISSUE THREAD

**Issue by yuna-s** [Azure/azure-powershell#17429]
### Description of the new feature

Could you add new cmdlets to set Public Access configuration for App Configuration to Az.Configuration module?
![image](https://user-images.githubusercontent.com/38641545/157600816-e02285b4-8f41-45d7-a69f-af82d9fb13b5.png)

I checked the following refernces, but there are no cmdlets for that.
<Az.AppConfiguration Module | Microsoft Docs>
https://docs.microsoft.com/en-us/powershell/module/az.appconfiguration/?view=azps-7.3.0

Thanks

**Comment by dingmeng-xue** [comment]
AppConfiguration team, could you share which API can support it?

**Comment by yuna-s** [comment]
@dingmeng-xue Thanks for your following up. 
Hi @Azure/azure-appconfig-team , could you check this issue?

**Comment by jimmyca15** [comment]
This property was added in `2020-06-01` ([link](https://github.com/microsoft/azure-rest-api-specs/blob/b7ceedcb657cac760383b17627cd2c1f47dd1521/specification/appconfiguration/resource-manager/Microsoft.AppConfiguration/stable/2020-06-01/appconfiguration.json#L951)).
