### ISSUE TITLE
Get-AzMetric only returns Average but no value for Maximum, Minimum 

### ISSUE THREAD

**Issue by william-li-nintex** [Azure/azure-powershell#17455]
### Description

When using `Get-AzMetric` following the documentation [here](https://docs.microsoft.com/en-us/powershell/module/az.monitor/get-azmetric?view=azps-7.3.0), it only returns **Average** but never for **Minimum** and **Maximum** values as below screenshot. Just curious to know how to get Minimum and Maximum values as we can see in the Azure Portal.

![image](https://user-images.githubusercontent.com/89058536/158053362-012ce234-14b0-496a-beb2-0b00e2fb28f7.png)

My Command is as follows, the resource id is any resource id for an Azure SQL Database

`(Get-AzMetric -ResourceId "someAzureSqlDbResourceIdxxxxxxxxxx" -MetricName "dtu_consumption_percent" -TimeGrain "00:01:00" -StartTime "2022-03-12T05:40:40Z").Data`

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Error output

```PowerShell
There is no error
```

**Comment by dingmeng-xue** [comment]
@VeryEarly , please help look into it.

**Comment by william-li-nintex** [comment]
May I ask if there's an update on this please? Thanks

**Comment by dingmeng-xue** [comment]
@william-li-nintex , metric returns the result according to resource type and metric. You can search `dtu_consumption_percent` on page https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftsqlserversdatabases. The aggregation type is "average". The return result is by design.

**Comment by william-li-nintex** [comment]
@dingmeng-xue  Thanks for your reply. The reason I raised this is because the **max/min** data is available in the metrics per below screenshot, just wondering is there a way to retrieve the data, either using PowerShell or Api. Thanks.
![image](https://user-images.githubusercontent.com/89058536/160925474-fe899970-1360-46c9-9c1c-df50566e40de.png)

**Comment by maeganda11** [comment]
hello.. wondering if this has been answered already? :)

**Comment by amjad30nagori** [comment]
May be I am late to the party but I got the same issue and seems we have new input parameter called -AggregationType which can be used to get the maximum value of metrics.

![image](https://github.com/Azure/azure-powershell/assets/43353561/e62048ce-8a23-4da7-bb9e-5bd11375f24c)
