### ISSUE TITLE
Import Python package for Automation account

### ISSUE THREAD

**Issue by DuongThiNgocHoa** [Azure/azure-powershell#17460]
### Description

Now i want to use ansible to import Python package when i have manual downloaded

![image](https://user-images.githubusercontent.com/49944383/158121437-3f0cb1ce-f1c9-48df-8805-5a03c091b91d.png)

How to do it by power shell or cli or ansible ? Thanks

### Issue script & Debug output

```PowerShell
 
```

### Environment data

```PowerShell
 
```

### Module versions

```PowerShell
 
```

**Comment by PramodValavala-MSFT** [comment]
@DuongThiNgocHoa Looks like these aren't supported in PowerShell or CLI _yet_. The API used by the Azure Portal isn't documented but is something you could replicate to achieve this as a workaround in the time being. Note that this being undocumented, could change without notice.

We will check with the concerning team for more details on official support.

**Comment by PramodValavala-MSFT** [comment]
@DuongThiNgocHoa Here is the [official API](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/automation/resource-manager/Microsoft.Automation/stable/2018-06-30/python2package.json) to import packages for python2 and the same requests for python3 are applicable except replacing `python2Packages` with `python3Packages` in the URL paths.

You need the PUT request to import a new package with a body like this

```json
{
  "properties": {
    "contentLink": {
      "uri": "<public-url-to-package>"
    }
  }
}
```

The URL to the package could for example be a public blob or protected blob with the SAS key in the URL (which is what the portal does too).

You can make this request using the [`az rest`](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#rest-api-commands) sub-command from the Azure CLI.
