### ISSUE TITLE
[Doc]: No examples for Set-AzVMBackupExtension

### ISSUE THREAD

**Issue by mikefrobbins** [Azure/azure-powershell#17504]
### Description

Hello,
While I was doing troubleshooting for VM Backup Extension, I noticed that there was no example provided in the following document:

* [Set-AzVMBackupExtension](https://docs.microsoft.com/powershell/module/az.compute/set-azvmbackupextension)

![image](https://user-images.githubusercontent.com/67425540/157755493-e06156a0-a351-46fb-a8d8-090b3fefd6b5.png)

Can you please update this document by adding an example?

[Basil Kandah feedback]
Thank you very much!

**Comment by CaptainFanZzz** [comment]
The problem should be related to https://github.com/Azure/azure-powershell/issues/16793 . Thanks.

**Comment by dingmeng-xue** [comment]
Resolved. Close it now.
