### ISSUE TITLE
[Feature]: Missing Update-AzADGroup in Az 7.3.2

### ISSUE THREAD

**Issue by kelps** [Azure/azure-powershell#17514]
### Description of the new feature

Currently there is no way to update Azure AD Groups using the Az Powershell module. I can create, list and remove, but not update. Update is possible using the "old" AzureAD module, as it is being deprecated and doesn't support Powershell Core, I need to use the new module.

### Proposed implementation details (optional)

The implementation should follow the same style used by Update-AzADUser or Update-AzADApplication, where we can update any individual parts of the object, including AppRoleAssignments

**Comment by dingmeng-xue** [comment]
@VeryEarly , please look into it? Is it supported by service API?
BTW, I believe cmdlet description is incorrect https://github.com/Azure/azure-powershell/blob/92e26201a48cddaaea976ca0d732fbbcac9a6ea1/src/Resources/MSGraph.Autorest/custom/New-AzADGroup.ps1#L13
