### ISSUE TITLE
*dll-help.psd1?

### ISSUE THREAD

**Issue by juneb** [Azure/azure-powershell#1752]
Can someone in charge here please tell me what a dll-help.psd1 file is? I verified with Microsoft that this is not a valid file type and they have no effect. Did anyone test these files before merging the PR? #
![dll-help psd1](https://cloud.githubusercontent.com/assets/2954883/12692033/d8da9b16-c6a6-11e5-8b78-209317d558a8.png)

**Comment by markcowl** [comment]
@juneb These are files used by a help authoring tool.  They should not be included in created modules (though they have no functional impact), but they are entirely appropriate in the repo.

**Comment by markcowl** [comment]
@hovsepm I think we should just have these files marked as 'do not copy'.  We'll need to regen the wix afterward.

**Comment by markcowl** [comment]
resolved here:  https://github.com/Azure/azure-powershell/commit/e84e6137c7c532d2083d7518fbacb7e89bca8ef3 closing...
