### ISSUE TITLE
Microsoft.PowerShell.Commands.Compute.dll-help.xml has invalid XML

### ISSUE THREAD

**Issue by juneb** [Azure/azure-powershell#1754]
Is anyone testing the *-help.xml files before you merge the PRs? All help for AzureRM.Compute v.1.2.1 in PowerShell Gallery is failing due to a merge of invalid XML.

Is anyone testing these files before you release a module to the PSGallery? None of the help is working, so all you needed to do to detect the error is run the help *once* on any cmdlet. 

The help XML error is in Set-AzureRmVMChefExtension, which isn't even exported in this version of the module. Why is there help when there's no cmdlet?

The failure is in the <command:syntaxItem>\<command:parameter> for the RunList parameter. The XML has 2 
<command:parameter> elements, instead of a <command:parameter> element and an optional <command:parameterValue> element. 

I'll would submit a fix, but I would really like to understand the help validation process, before I contribute. All you need to do is use the [XML] accelerator. 

![azurermcompute-helpxml](https://cloud.githubusercontent.com/assets/2954883/12692950/15e51452-c6b4-11e5-8ae2-2868cb54abcc.png)

**Comment by markcowl** [comment]
@juneb Thanks for the report.  We'll make sure this is fixed for next week's release.

**Comment by markcowl** [comment]
@juneb We owe you, btw

**Comment by hovsepm** [comment]
Fixed. Will be available in Azure PowerShell February release v.1.2.0.

**Comment by markcowl** [comment]
@juneb FYI This PR helps to address egregious problems with the help, but it is not a substitute for using the help:  https://github.com/Azure/azure-powershell/pull/1767 

There was a similar problem in AzureRM.OperationalInsights, as this revealed, which will be corrected in the next release.
