### ISSUE TITLE
Missing RM cmdlets in AzureRM.Resources

### ISSUE THREAD

**Issue by kilasuit** [Azure/azure-powershell#1759]
In the help for New-AzureRmResourceGroup there is a reference to both

``` powershell
Get-AzureRmResourceGroupGalleryTemplate
Save-AzureRmResourceGalleryTemplate
```

But these don't seem to be included in any of the Azure Modules and this makes a breaking change from v0.9.8 to the v1.0.\* modules as reported via https://www.reddit.com/r/PowerShell/comments/43p8c6/powershell_azure_gallery_commands_no_longer_work/

**Comment by ravbhatnagar** [comment]
@kilasuit - The above cmdlets were removed as a part of deprecation of the AzureResourceGroupGalleryTemplate in the 1.0+ version of Azure PowerShell. The team is working on enabling the scenario with all the current plus some additional capabilities. 

In the meantime, you can use the below workaround if you want to use the gallery templates from PowerShell:
# Retrieve all available items
$allGalleryItems = Invoke-WebRequest -Uri "https://gallery.azure.com/Microsoft.Gallery/GalleryItems?api-version=2015-04-01&includePreview=true" | ConvertFrom-Json

# Get all items published by Microsoft
$allGalleryItems | Where-Object { $_.PublisherDisplayName -eq "Microsoft" }

# Get all gallery items with "SQL" in the description
$allGalleryItems | Where-Object { $_.Description -match "SQL" }

# Save default template for all items under directory "C:\Templates"
$allGalleryItems | Foreach-Object { 
$path = Join-Path -Path "C:\templates" -ChildPath $_.Identity
New-Item -type Directory -Path $path

$_.Artifacts | Where-Object { $_.type -eq "template" } | ForEach-Object {
$templatePath = Join-Path -Path $path -ChildPath ( $_.Name + ".json" )

(Invoke-WebRequest -Uri $_.Uri).Content | Out-File -FilePath $templatePath
}
}

**Comment by ravbhatnagar** [comment]
@kilasuit - The above cmdlets were removed as a part of deprecation of the AzureResourceGroupGalleryTemplate in the 1.0+ version of Azure PowerShell. The team is working on enabling the scenario with all the current plus some additional capabilities. 

In the meantime, you can use the below workaround if you want to use the gallery templates from PowerShell:
Retrieve all available items
$allGalleryItems = Invoke-WebRequest -Uri "https://gallery.azure.com/Microsoft.Gallery/GalleryItems?api-version=2015-04-01&includePreview=true" | ConvertFrom-Json

Get all items published by Microsoft
$allGalleryItems | Where-Object { $_.PublisherDisplayName -eq "Microsoft" }

Get all gallery items with "SQL" in the description
$allGalleryItems | Where-Object { $_.Description -match "SQL" }

Save default template for all items under directory "C:\Templates"
$allGalleryItems | Foreach-Object { 
 $path = Join-Path -Path "C:\templates" -ChildPath $_.Identity
 New-Item -type Directory -Path $path

$.Artifacts | Where-Object { $.type -eq "template" } | ForEach-Object {
 $templatePath = Join-Path -Path $path -ChildPath ( $_.Name + ".json" )

(Invoke-WebRequest -Uri $_.Uri).Content | Out-File -FilePath $templatePath
 }
 }

**Comment by kieranwalsh** [comment]
Thanks for the information @ravbhatnagar and for the workaround.
Fair enough that new and better cmdlets are being worked on, but it seems really strange to pull the working ones before the updated versions are ready.
Anyway, thanks again.

**Comment by cormacpayne** [comment]
Closing this issue as it seems this has been resolved. Please feel free to re-open this issue if you have any other questions.
