### ISSUE TITLE
New-AzureRMResourceGroupDeployment does not return proper error for deployment resources

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-powershell#1761]
When deploying a template with a nested deployment (deployment resources) the error bubbled up by the cmdlet is a generic error rather than the root cause error returned by the deployment in ARM.  PS returns:

```
20:05:51 - [ERROR] New-AzureRmResourceGroupDeployment : DeploymentNotFound: Deployment 'domain' 
20:05:51 - [ERROR] could not be found.

```
The top level error in the portal:
![top error](https://cloud.githubusercontent.com/assets/10090014/12759926/ae8092cc-c998-11e5-86e1-f1bcc8835380.png)

The real error you need to debug:
![real error](https://cloud.githubusercontent.com/assets/10090014/12759925/ae75ca9a-c998-11e5-94de-9729e39c3a96.png)

PS should return the real error you need to debug (or all of the errors above)

**Comment by ravbhatnagar** [comment]
I think this has been fixed in the latest PS release. @vivsriaus - Please confirm.

**Comment by bmoore-msft** [comment]
Using the 1.0.4 cmdlets - I ran through 2 different failures (one with a bad uri and one with a storageAccount naming failure) and both returned the proper error.
