### ISSUE TITLE
Az.Resources not including contructor for New-AzADAppCredential

### ISSUE THREAD

**Issue by magic-happenz** [Azure/azure-powershell#17626]
### Description

Running New-Object Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordCredential as documented in https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/help/New-AzADSpCredential.md is not working.

### Issue script & Debug output

```PowerShell
PS > $NewSecretData = New-Object Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordCredential
New-Object: A constructor was not found. Cannot find an appropriate constructor for type Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordCredential.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.3                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     5.4.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
New-Object: A constructor was not found. Cannot find an appropriate constructor for type Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordCredential.
```

**Comment by magic-happenz** [comment]
Running ` New-Object Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential` is working locally but fails in Azure Functions with error:
`Cannot find type [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential]: verify that the assembly containing this type is loaded. Exception : Type : System.Management.Automation.PSArgumentException ErrorRecord : Exception : Type : System.Management.Automation.ParentContainsErrorRecordException Message : Cannot find type [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential]`

And I just want to set a display name for a secret...

**Comment by dingmeng-xue** [comment]
@VeryEarly , please help to look into it.

**Comment by VeryEarly** [comment]
> Running ` New-Object Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential` is working locally but fails in Azure Functions with error: `Cannot find type [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential]: verify that the assembly containing this type is loaded. Exception : Type : System.Management.Automation.PSArgumentException ErrorRecord : Exception : Type : System.Management.Automation.ParentContainsErrorRecordException Message : Cannot find type [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential]`
> 
> And I just want to set a display name for a secret...

The error in description is because you are trying to instantiate an interface, can you please paste the scripts executed in Azure function and the error output as well?

**Comment by magic-happenz** [comment]
> The error in description is because you are trying to instantiate an interface, can you please paste the scripts executed in Azure function and the error output as well?

That is actually the command and error from Azure functions. Trying to set the following:
```
$NewSecretData = New-Object Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordCredential
$NewSecretData.DisplayName = "test"
$NewSecretData.StartDateTime = (Get-Date).ToUniversalTime()
$NewSecretData.EndDateTime = (Get-Date).AddDays([int]$ValidityPeriodinDays).ToUniversalTime()

$NewCredential = New-AzADAppCredential -ObjectId $ObjectId -PasswordCredentials $NewSecretData

```
Fails with message:
`EXCEPTION: Cannot find type [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordCredential]: verify that the assembly containing this type is loaded. Exception : Type : System.Management.Automation.PSArgumentException ErrorRecord : Exception : Type : System.Management.Automation.ParentContainsErrorRecordException Message : Cannot find type [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordCredential]: verify that the assembly containing this type is loaded.`

Regardless if I use `Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordCredential` or `Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential`.

Furthermore the -DisplayName parameter of the cmdlet runs into an error as well.
```
New-AzADAppCredential -ObjectId $ObjectId -StartDate $StartTime -EndDate $EndTime -DisplayName $DisplayName
New-AzADAppCredential: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```
However, without the -DisplayName parameter it works. Maybe I am overseeing something but I could not find clear documentation how this is supposed to work.

**Comment by VeryEarly** [comment]
Hi @magic-happenz ,

For Azure Function, I don't think the assembly was loaded when you try to call the constructor, please try execute one cmdlet before it, for example: Get-AzADApplication.

The -DisplayName means the display name of the application it cannot be used with -ObjectId, they belong to different parameter sets.

**Comment by magic-happenz** [comment]
@VeryEarly thank you for the clarification. I decided to use the Graph API now.

**Comment by dingmeng-xue** [comment]
@magic-happenz , Sorry for inconvenience. There are 2 problems around your question.
1. `IMicrosoftGraphPasswordCredential` used by your script is an interface. You need to use its concrete class type. For instance `Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential`. If New-Type is the first line in your script, you have to import module explicitly
2. The credential links to Application instead of service principal. The value of `-ObjectId ` is directory object id of application in AAD rather than its service principal.

Below code can work
```
Import-Module Az.Resources
$NewSecretData = New-Object Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential
$NewSecretData.DisplayName = "Test"
$NewSecretData.StartDateTime = (Get-Date).ToUniversalTime()
$NewSecretData.EndDateTime = (Get-Date).AddDays([int]$ValidityPeriodinDays).ToUniversalTime() 
New-AzADAppCredential -ObjectId $AppObjectId -PasswordCredentials $NewSecretData
```

**Comment by magic-happenz** [comment]
@dingmeng-xue Thank you very much for the clarification. That way it is working.

**Comment by dingmeng-xue** [comment]
Thanks. Close this issue now.
