### ISSUE TITLE
Get-AzStorageSyncServer Outputs PSRegisteredServer AgentVersionExpirationDate, AgentVersionStatus not working

### ISSUE THREAD

**Issue by superfliege** [Azure/azure-powershell#17637]
### Description

Hello all,

unfortunately the call to "Get-AzStorageSyncServer" does not work correctly.
The properties AgentVersionExpirationDate, AgentVersionStatus are always empty here unfortunately.

We have an agent expiring, but still these fields are empty.

Could you please fix this?

### Issue script & Debug output

```PowerShell
$SyncServerAgents = Get-AzStorageSyncServer $syncService.ResourceGroupName -StorageSyncServiceName $syncService.StorageSyncServiceName


    foreach($SyncServerAgent in $SyncServerAgents)
    {
        if($SyncServerAgent.AgentVersionStatus -match "expire")
        {
            $AgentExpireSoon = $True
        }
    }
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.18362.1801
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1801
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.7.4      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     5.1.0      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment...}
Script     1.6.1      Az.StorageSync                      {Get-AzStorageSyncCloudEndpoint, Get-AzStorageSyncGroup, Get-AzStorageSyncServer, Get-AzStorageSyncServerEndpoint...}
```

### Error output

```PowerShell
-
```

**Comment by SaurabhSharma-MSFT** [comment]
@superfliege We are looking into it and get back to you if any additional information is required.

**Comment by SaurabhSharma-MSFT** [comment]
@geolivo Can you please help looking into it.

**Comment by SaurabhSharma-MSFT** [comment]
@ankushbindlish2 Can you please take a look?

**Comment by geolivo** [comment]
@SaurabhSharma-MSFT looking

**Comment by SaurabhSharma-MSFT** [comment]
@geolivo Any updates on this ?

**Comment by geolivo** [comment]
Apologies for the delay on this. I'll file a bug and see how we can add this information to the cmdlet output. In the meantime, you can use this workaround that utilizes Get-AzResource from Az.Resources. The output of that cmdlet will have the version expiration details that you're looking for.

```
$SyncServerAgents = Get-AzStorageSyncServer $syncService.ResourceGroupName -StorageSyncServiceName $syncService.StorageSyncServiceName


foreach($SyncServerAgent in $SyncServerAgents)
{
    $ServerResource = Get-AzResource -ResourceId $SyncServerAgent.ResourceId
    $ExpirationStatus = $ServerResource | Select-Object -ExpandProperty Properties | Select-Object -Property "AgentVersion","AgentVersionStatus"    

    if( -match "expire")
    {
        $AgentExpireSoon = $True
    }
}
```

**Comment by SaurabhSharma-MSFT** [comment]
@geolivo Great, thank you for looking into this.
@superfliege Please check the above workaround in the interim and let us know if you have any questions.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@superfliege Please let me know if you have any questions else we will proceed with the closure of this issue.

**Comment by superfliege** [comment]
Hello together,

omg thanks for your feedback! In the $ExpirationStatus.agentVersionStatus i get now: "NearExpiry" or "Ok"

So the workarround is fine for me! The issue can be marked as resolved.
