### ISSUE TITLE
Get-AzureRmOperationalInsightsIntelligencePacks does not return any results

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-powershell#1765]
Get-AzureRmOperationalInsightsIntelligencePacks  command does not return any results.
When -debug is used the results can be seen in debug log but they are never outputted from the command. Module version is 1.0.4

**Comment by slavizh** [comment]
![capture](https://cloud.githubusercontent.com/assets/11890856/12775908/5735d780-ca5a-11e5-8527-e646c4af7a16.PNG)

**Comment by markcowl** [comment]
@devigned Can you assign the appropriate contact from the OperationalInsights team?

**Comment by slavizh** [comment]
This was fixed at some point but nobody tracked it
