### ISSUE TITLE
[Doc]: New-AzApplicationGatewayPrivateLinkConfiguration -ipconfiguration doesn't work

### ISSUE THREAD

**Issue by CaptainFanZzz** [Azure/azure-powershell#17681]
### Description

When updating the example of New-AzApplicationGatewayPrivateLinkConfiguration, I don't know which value I should take for -ipconfiguration. 
https://docs.microsoft.com/en-us/powershell/module/az.network/new-azapplicationgatewayprivatelinkconfiguration?view=azps-7.3.2

**Comment by dingmeng-xue** [comment]
Hi Service team, current example may confuse customer because they have no idea how to create variable `privateLinkIpConfiguration1` for input parameter
