### ISSUE TITLE
[Feature]: Azure App Configuration: Update-AzAppConfigurationStore - Add option to enable/disable public network access

### ISSUE THREAD

**Issue by DrorOzgaon** [Azure/azure-powershell#17692]
### Description of the new feature

https://docs.microsoft.com/en-us/powershell/module/az.appconfiguration/update-azappconfigurationstore?view=azps-7.3.2

It is not currently possible to pass the -PublicNetworkAccess parameter to enable or disable the public network access. This is possible in Azure CLI with the --enable-public-network parameter (https://docs.microsoft.com/en-us/cli/azure/appconfig?view=azure-cli-latest#az-appconfig-update)

**Comment by dingmeng-xue** [comment]
@lijinpei2008 , let's update it in this month.

**Comment by lijinpei2008** [comment]
The current stable version of the API does not support update-AzAppConfigurationStore using the parameter [-publicNetworkAccess]. When the "stable version" of the API is updated, we will add support for PublicNetworkAccess.
