### ISSUE TITLE
[Feature]: Request that 'Null' be added as an accepted value for the -OsType parameter for New-AzDiskUpdateConfig 

### ISSUE THREAD

**Issue by mcaraway56** [Azure/azure-powershell#17716]
### Description of the new feature

I have hundreds of data disks that have erroneously had the OsType parameter set.  This causes Azure to display metrics for the OS rather than the data disk.

I can clear the OsType parameter by submitting the following:
$diskupdateconfig = New-AzDiskUpdateConfig
But I cannot apply the new setting because Null is not an accepted value:
Update-AzDisk -ResourceGroupName 'AZG-AZ-BRIAN-RG' -DiskName 'TST1-Mike_datadisk_1' -DiskUpdate $diskupdateconfig

**Comment by TravisCragg-MSFT** [comment]
As an update, currently only 'windows' and 'Linux' are acceptable values for the -OsType parameter. Once this has been set to one of those two values, it cannot be removed or set to null.

**Comment by Drewm3** [comment]
Moving this back to a feature request based on the findings from @TravisCragg-MSFT.

**Comment by TravisCragg-MSFT** [comment]
I have [added this to feedback.azure.com as a feature request](https://feedback.azure.com/d365community/idea/6173caff-3d98-ed11-a81b-000d3ae5ae95). 

Please vote for the feature and give additional feedback, as this helps us with prioritization.
