### ISSUE TITLE
Import-AzAksCredential is missing the Public-FQDN functionality

### ISSUE THREAD

**Issue by fschmied** [Azure/azure-powershell#17711]
### Description of the new feature

With a private cluster, AKS will create two DNS entries: a private one and a public one. `Import-AzAksCredential` imports a kubeconfig with the private DNS name.

Sometimes, you need the public DNS name, e.g., when the machine you're connecting from can't resolve the private one. Azure CLI's `az aks get-credentials` therefore has a `--public-fqdn` option.

`Import-AzAksCredential` is missing that option and should get it, too.

### Proposed implementation details (optional)

Should work the same way as `az aks get-credentials --public-fqdn`.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will look into it.
