### ISSUE TITLE
[Eng]: test-module issue

### ISSUE THREAD

**Issue by dicolanl** [Azure/azure-powershell#17745]
### Description

pwsh test-module.ps1 -live
Creating isolated process...
Installing local Pester module into '/workspaces/azure-powershell/src/SecurityInsights/generated/modules'...
Building local Resource module used for test...
Copy-Item: /workspaces/azure-powershell/src/SecurityInsights/check-dependencies.ps1:61:11
Line |
  61 |    $null = Copy-Item custom/* $HOME/.PSSharedModules/Resources/custom/
     |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find a part of the path '/root/.PSSharedModules/Resources/custom/'.

test-module calls check-dependencies
in check dependencies:
if ($Resources.IsPresent -and ((-not (Test-Path -Path $resourceModule)) -or $RegenerateSupportModule.IsPresent)) {
  Write-Host -ForegroundColor Green "Building local Resource module used for test..."
  Set-Location $resourceDir
  $null = autorest .\README.md --use:@autorest/powershell@3.0.414 --output-folder=$HOME/.PSSharedModules/Resources
  $null = Copy-Item custom/* $HOME/.PSSharedModules/Resources/custom/
  Set-Location $HOME/.PSSharedModules/Resources
  $null = .\build-module.ps1
  Set-Location $PSScriptRoot
}

autorest uses tools\resources\readme.me
/tools/Resources> autorest .\README.md --use:@autorest/powershell@3.0.414 --output-folder=$HOME/.PSSharedModules/Resources
AutoRest code generation utility [cli version: 3.6.1; node: v14.15.5]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    |    Loading AutoRest core      '/root/.autorest/@autorestcore@3.8.3/nodemodules/@autorest/core/dist' (3.8.3)
info    | 
The default version of @autorest/powershell has been bumped from 2.1+ to 3.0+.
 > If you still want to use 2.1+ version, please specify it with --use:@autorest/powershell@2.1.{x}, e.g 2.1.401.

info    |    Loading AutoRest extension '@autorest/powershell' (3.0.414->3.0.414)
info    |    Loading AutoRest extension '@autorest/modelerfour' (4.15.414->4.15.414)
fatal   | Process() cancelled due to failure 
error   |   Error: Could not read 'https://github.com/Azure/azure-rest-api-specs/blob/dca0f55a844b694d314f635cc14374c1e87bb9fe/specification/resources/resource-manager/Microsoft.Resources/stable/2018-05-01/resources.json'.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.

that json for resources is no longer available on github.

**Comment by dingmeng-xue** [comment]
@dolauli , please check this question.

**Comment by dolauli** [comment]
@dicolanl  I can not find commit dca0f55a844b694d314f635cc14374c1e87bb9fe in the swagger repo. Is it still valid any more? After you update the commit to a valid one, you may run test-module.ps1 by adding additional parameter `-RegenerateSupportModule`

**Comment by dicolanl** [comment]
@dolauli thats correct. I did manually update the resources readme and it worked fine 
But I didn’t create that file. I thought build-module did. So figure it needs to be updated in the source somewhere

**Comment by dolauli** [comment]
@dicolanl  Did you specify the branch to the invalid commit id as below in your readme.md. If yes, that's why the issue happen. And we will use this commit id to fetch the  resources.json

'''
branch: dca0f55a844b694d314f635cc14374c1e87bb9fe
'''

**Comment by dolauli** [comment]
Close it since it is not a bug but caused by wrong configuration.

**Comment by dicolanl** [comment]
Thanks. The wiki should be updated to be clear about this. It wasn’t there and what I was told in the pr wasn’t as clear.
