### ISSUE TITLE
[Feature]: Include Get-AzKeyVaultNetworkRuleSet cmdlet

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/azure-powershell#17758]
### Description of the new feature

Currently the following cmdlets are supported for interacting with key vault network rules:

```powershell
> Get-Command *AzKeyVaultNetworkRule*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Add-AzKeyVaultNetworkRule                          4.3.1      Az.KeyVault
Cmdlet          New-AzKeyVaultNetworkRuleSetObject                 4.3.1      Az.KeyVault
Cmdlet          Remove-AzKeyVaultNetworkRule                       4.3.1      Az.KeyVault
Cmdlet          Update-AzKeyVaultNetworkRuleSet                    4.3.1      Az.KeyVault
```

However we don't seem to have cmdlets than can list network rules.

### Proposed implementation details (optional)

Implement cmdlet `Get-AzKeyVaultNetworkRuleSet` to list network ACL rules.

Azure CLI has a command `az keyvault network-rule list` which does this. I think it should be included in Azure PowerShell as well.

**Comment by ArmaanMcleod** [comment]
Happy to help with this one. I think if we include a cmdlet that can just list all the network rules that should be good enough. Thoughts?

**Comment by ArmaanMcleod** [comment]
Happy to raise a PR at https://github.com/Azure/azure-powershell-cmdlet-review-pr if this change would be ok with you guys.

Was thinking parameter sets like this could be supported:

```powershell
Get-AzKeyVaultNetworkRuleSet [-VaultName] <string> [[-ResourceGroupName] <string>] [-DefaultProfile <IAzureContextContainer>] [-SubscriptionId <string>] [<CommonParameters>]

Get-AzKeyVaultNetworkRuleSet [-InputObject] <PSKeyVault> [-DefaultProfile <IAzureContextContainer>] [-SubscriptionId <string>] [<CommonParameters>]

Get-AzKeyVaultNetworkRuleSet [-ResourceId] <string> [-DefaultProfile <IAzureContextContainer>] [-SubscriptionId <string>] [<CommonParameters>]
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting and proposal. Network rule set is one of properties of Keyvault resource. User can get that via `Get-AzKeyVault`.

**Comment by ArmaanMcleod** [comment]
@dingmeng-xue No worries, some reason I missed that. Will close this issue.
