### ISSUE TITLE
[Doc]: Description error for - Invoke-AzAksRunCommand -Force 

### ISSUE THREAD

**Issue by fredx30** [Azure/azure-powershell#17756]
### Docs text issue
The `-force` switch does not appear to have a correct text for the command [invoke-azaksruncommand](https://docs.microsoft.com/en-us/powershell/module/az.aks/invoke-azaksruncommand?view=azps-7.4.0).

### Current 
The current description text is `Remove managed Kubernetes cluster without prompt`.

I have run this repetedly with the `-force` switch and i still have my cluster, im not objecting to the fact i got to keep my cluster but the text is missleading at best. Best i can tell the `-force` switch only removes the confirmation prompt.

### Possible solutions 
Investigate what the real functionality is and update description text.

**Comment by dingmeng-xue** [comment]
@wyunchi-ms , please check this issue.
