### ISSUE TITLE
[Doc]: AccountName parameter Used in Examples but not documented

### ISSUE THREAD

**Issue by briglx** [Azure/azure-powershell#17774]
### Description

The examples to create a new storage account use the parameter `AccountName` but the documented parameter is `Name`. Either publish the undocumented Paramter `AccountName` or change the examples to use `Name`.

**Comment by dingmeng-xue** [comment]
@blueww , any concern to update example?

**Comment by PramodValavala-MSFT** [comment]
@dingmeng-xue I've worked up a PR to address this for a couple of docs that have similar examples. Could you take a look?

**Comment by blueww** [comment]
The PR looks good to me. I have approved it, and resolved a conflict in it.
Please also update [change log](https://github.com/Azure/azure-powershell/blob/main/src/Storage/Storage.Management/ChangeLog.md) for the help doc change.
