### ISSUE TITLE
[Feature]: Expand Az.Storage Module to provide Add/Update/Delete capability at the entity (Row) level in Azure Storage Tables

### ISSUE THREAD

**Issue by dougwilkerson** [Azure/azure-powershell#17793]
### Description of the new feature

Az.Storage currently provides the ability to interact with Storage Tables at the resource level.  Unfortunately, the module does not provide the ability to perform Add/Update/Delete actions at the entity (row) level.

At the time of this comment, Microsoft documentation provides the link below describing module AzTable which appears to fill a majority of these capabilities.  This module is not currently signed.  

https://docs.microsoft.com/en-us/azure/storage/tables/table-storage-how-to-use-powershell

Similar capabilities would seem to be a logical extension of the official Az.Storage module.

**Comment by SaurabhSharma-MSFT** [comment]
@dougwilkerson We are looking into it and get back to you for any additional information.

**Comment by blueww** [comment]
@PaulCheng 
Would you please help to look at the storage table request?

**Comment by PaulCheng** [comment]
There is no plan to add entity level operations to the az.storage module. We will look into the options to sign AzTable if it's applicable.

**Comment by SaurabhSharma-MSFT** [comment]
Thanks @PaulCheng 
@dougwilkerson Please let me know if you have any other questions.

**Comment by SaurabhSharma-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
