### ISSUE TITLE
Add PowerShell command to configure Azure Automation service plan & retrieve usage

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#178]
The updates to the Azure PowerShell module surrounding the Azure Automation feature are great! A couple of additional commands that would be useful, to help manage customer environments would include:
- A PowerShell command to retrieve the number of Automation minutes used in the current month
- A PowerShell command to configure the Azure Automation service plan (**Free** or **Basic**)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by devigned** [comment]
@jodoglevy do you have any thoughts on this issue?

**Comment by jodoglevy** [comment]
Agree on the minutes one. The service plan one is now complete. See the Set-AzureAutomationAccount cmdlet in the AzureResourceManager PS module.

**Comment by cormacpayne** [comment]
@vrdmr Hey Varad, would you mind taking a look at this long-standing issue? You may be able to shed some light on whether or not the requested functionality is available in the Automation cmdlets or if they are (or could be) on your team's radar

**Comment by sourabhguha** [comment]
Evaluating the feature request.

**Comment by csand-msft** [comment]
The community is welcome to work on this request.

**Comment by andyw248** [comment]
Re. feature request 1: The cost for an automation account can be viewed from the Azure portal: Navigate to cost analysis, filter by resource type microsoft.automation/automationaccount.
Re. feature request 2: Since 2018, all automation accounts are created in the "basic" pricing tier.
