### ISSUE TITLE
Get-AzureRmKeyVault and Remove-AzureRmKeyVault throws ArgumentException if resource does not exisit

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-powershell#1780]
Repro:

```
Get-AzureRmKeyVault -VaultNam "SomeName"
```

**Expected**: Get[/Remove]-AzureRmKeyVaultshould return an empty result if KeyVault does not exist.

**Comment by pomortaz** [comment]
@hovsepm for remove-* this is not correct because if the vault exists it returns an empty result. It should throw if the vault doesn't exist so that the user know the operation is not successfully executed.

**Comment by cormacpayne** [comment]
Closing as this appears to be resolved.
