### ISSUE TITLE
Update-AzADApplication

### ISSUE THREAD

**Issue by jmcanally** [Azure/azure-powershell#17809]
### Description

I have a script that uses Update-AzADApplication with the InputObject parameter.  Running the code below produces no errors and does not update the attribute in AAD.  I am able to update other attributes for the App without using the InputObject parameter (i.e. Update-AzADApplication -Note "Testing").  Ultimately I am looking to update the LogoutUrl attribute but just testing with a basic attribute.  Suggestions?

$DebugPreference = 'Continue'
$obj = Get-AzADApplication -ObjectId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
$obj.Note = "Testing Note"
Update-AzADApplication -InputObject $obj

### Script or Debug output

```PowerShell
No output from the Update-AzADApplication command
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Script     2.7.5                 Az.Accounts
Script     5.5.0                 Az.Resources
```

### Error output

```PowerShell
No output
```

**Comment by dingmeng-xue** [comment]
Thanks reporting. The usage of `InputObject` is different from your understanding. The behavior is inconsistent due to service API design. `InputObject` is just help to identify the object.

Following existing example https://docs.microsoft.com/en-us/powershell/module/az.resources/update-azadapplication?view=azps-7.4.0#example-2-update-application-by-pipeline-input, your script should be
```
Update-AzADApplication -InputObject $obj -Note "Testing Note"
```
or
```
Get-AzADApplication -ObjectId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx | Update-AzADApplication -Note "Testing Note"
```

**Comment by jmcanally** [comment]
Thanks for the clarification!
