### ISSUE TITLE
[Feature]: Add FilePath for New-AzSshKey

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#17838]
### Description of the new feature

`New-AzSshKey` and 'az sshkey create` will generate a .pub file on disk where the key is a multiline of text.
If one wants to use the public key from disk, it needs to read the content of the .pub file before passing the value to the -PublicKey parameter.
Simple Get-Content will create a collection of objects (lines) because the key is multiline, so we are forced to use -Raw or pipe to Out-String to turn the key into a string which is a complicated approach for new users. 

Adding support for a -FilePath parameter would greatly improve this experience.

Even when we convert key to the string, and upload it to Azure, when we later use ssh to connect to Linux VM, ssh command complains that the public key is in invalid format:
> ssh -i C:\users\aleksandar\.ssh\1650192858 [demouser@20.22.236.155](mailto:demouser@20.22.236.155)
load pubkey "C:\\users\\aleksandar\\.ssh\\1650192858": invalid format

cc: @alexandair 

### Proposed implementation details (optional)

Add support for a -FilePath parameter that will address the multi-line issue with SSH Keys

**Comment by grizzlytheodore** [comment]
Hello, the development team is under resource constraints, and this is a relatively low usage cmdlet; therefore this feature is not being considered. Closing this issue.
