### ISSUE TITLE
[Doc]: The incorrect content on Remove-AzContainerRegistryTag

### ISSUE THREAD

**Issue by aivanov306** [Azure/azure-powershell#17857]
### Description

Description of the Remove-AzContainerRegistryTag command documentations contains block:
Untag ACR tag. To use this cmdlet please run Update-AzContainerRegistryRepository -RegistryName XXX -Repository XXX -DeleteEnable $true first.
If you do this command on your repository it actually removes -ReadEnable $true -ListEnable $true -WriteEnabled $true access from the repository and you will not be able to do Remove-AzContainerRegistryTag (as well as read content of ACR repository).
To fix this you actually need to use the following command:
Update-AzContainerRegistryRepository -RegistryName XXX -Repository XXX -ReadEnable $true -ListEnable $true -DeleteEnable $true -WriteEnabled $true

Please correct this description to avoid confusion for users who never used this command before.

**Comment by dingmeng-xue** [comment]
We will double check the doc. Update-AzContainerRegistryRepository may not be reqquired.

**Comment by VeryEarly** [comment]
Hi @aivanov306 

Thanks for reporting this bug, I've made fix in [#17984](https://github.com/Azure/azure-powershell/pull/17984), this will be available next month.

Thanks
