### ISSUE TITLE
New-AzureRmAutomationCredential odd error message

### ISSUE THREAD

**Issue by microsmith** [Azure/azure-powershell#1791]
New-AzureRmAutomationCredential displays "Input string was not in a correct format" when the credential name already exists. Would be better if it displayed something like "Name myPsCredential already exists".

New-AzurermAutomationCredential : **Input string was not in a correct format**.
At line:1 char:1
- New-AzurermAutomationCredential -AutomationAccountName "PStest" -Name "myPsCrede ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [New-AzureRmAutomationCredential], FormatException
  - FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.NewAzureAutomationCredential

**Comment by markcowl** [comment]
@microsmith Thanks for the report, we'll take a look.

**Comment by maddieclayton** [comment]
Closing in favor of: https://github.com/Azure/azure-powershell/issues/2265
