### ISSUE TITLE
AzureChina: New-AzureRmRedisCache with Virtual Network failed

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#1793]
I am trying to provision RedisCache in a Virtual Network in Azure China

New-AzureRmRedisCache -ResourceGroupName "mytestingrgrp" -Name "myredistest" -Location "China East" -Size "C1" -VirtualNetwork "myvirtualnw"

New-AzureRmRedisCache :*\* LinkedInvalidPropertyId: Property id 'myvirtualnw' at path 'properties.virtualNetwork' isinvalid**. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}'.

Note: The same works in North America all regions.

**Comment by markcowl** [comment]
@Pradebban thanks for the report we will take a look.

**Comment by Pradebban** [comment]
@markcowl Please let me know when this will be addressed, we have a customer waiting on the same. And please let us know any official document- page which says this is not available in China yet

**Comment by Pradebban** [comment]
@markcowl, please let me know if there is any update on this. Thanks

**Comment by vladimir-shcherbakov** [comment]
@siddharthchatrolams Please take a look.

**Comment by SiddharthChatrolaMs** [comment]
This CMDLET (as specified above) wouldn't work in any cloud.

1) VNET capabilities are only supported in Premium Sku (customer is trying to use C1 which is standard)

2) VirtualNetwork should be an ARM Resource Id of VNET (not just name). Also, just providing VirtualNetwork  parameter is not enough, you need to provide "Subnet" as well. (NOTE: "VirtualNetwork" and "Subnet" parameters are marked as deprecated from past 2 years and they were completely remove in recent release. Customer should use "SubnetId" parameter instead)
