### ISSUE TITLE
Login-AzureRmAccount -Environment does not pass in environment object correctly

### ISSUE THREAD

**Issue by karlaugsten** [Azure/azure-powershell#1796]
Repro:

 $environment = Get-AzureRmEnvironment -Name AzureCloud
Login-AzureRmAccount -Environment $environment
Get-AzureRmADUser -UserPrincipalName someuser@microsoft.com

throws the error:
Get-AzureRmADUser : Your Azure credentials have not been set up or have expired, please run Login-AzureRMAccount to set up your Azure credentials.

However if you use the login command:
Login-AzureRmAccount -EnvironmentName AzureCloud 

it will work.

This only affects the latest release of azure powershell, 1.2.x. This is bad for environments such as AzureChinaCloud that need the environment specified.

**Comment by markcowl** [comment]
@karlaugsten Thanks for the report.  To help debug the issue, can you run this script with ```$DebugPreference="Continue"```  this will help determine precisely what is going on - there should be no functional difference between passing in an environment and an environment name.

**Comment by karlaugsten** [comment]
Sure, here is the output from the command:

PS C:\Windows\system32> Get-AzureRmADUser -UserPrincipalName 
DEBUG: 1:49:56 PM - GetAzureADUserCommand begin processing with ParameterSet 'EmptyParameterSet'.
DEBUG: 1:49:56 PM - using account id ''...
DEBUG: [Common.Authentication]: Authenticating using Account: 'karlaug@microsoft.com', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 2/12/2016 9:49:56 PM:  - AuthenticationFactory: Deserialized 3 items to token cache.
DEBUG: [Common.Authentication]: Received exception The given key was not present in the dictionary., while authenticating.
Get-AzureRmADUser : Your Azure credentials have not been set up or have expired, please run Login-AzureRMAccount to set up your Azure credentials.
At line:1 char:1
+ Get-AzureRmADUser -UserPrincipalName 
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmADUser], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ActiveDirectory.GetAzureADUserCommand

DEBUG: 1:49:56 PM - GetAzureADUserCommand end processing.

**Comment by markcowl** [comment]
@karlaugsten Thanks, we were able to repro and fixed the issue here:  https://github.com/markcowl/azure-powershell/commit/f10e5b6a9069e7a120f987296415da4fb47ea9b9

the issue was with the graph resource id required for graph version > 1.5 wasn't being propagated to the return type of the Get-AzureRmEnvironment cmdlet.  This is checked in and will be released on March 1.
