### ISSUE TITLE
[Doc]: Azure KeyVault PowerShell Set-AzKeyVaultManagedStorageSasDefinition - missing information, bad link name

### ISSUE THREAD

**Issue by DavidBerg-MSFT** [Azure/azure-powershell#17987]
### Description

In the doc page [Set-AzKeyVaultManagedStorageSasDefinition](https://docs.microsoft.com/en-us/powershell/module/az.keyvault/set-azkeyvaultmanagedstoragesasdefinition?view=azps-7.5.0)

1) We need to list or link to all the valid values for SasType.  I assume at least Account and Container, what else?  
2) Need an example for non-Account type SasDefinitions.
3) Need to clarify whether or not the template timespace needs to match the ValidityPeriod?  I assume ValidityPeriod overrides the start/end in the template, but we should be clear whether or not that's the case.
4) The Related Links section at the bottom of the page has a code page / bad character issue: [Azureâ€‹RM.â€‹Keyâ€‹Vault](https://docs.microsoft.com/en-us/powershell/module/az.keyvault/)
5) Related Links section should include links for building SAS tokens (templates).

Thanks!

**Comment by dingmeng-xue** [comment]
We will fix the item 4. For others, I involve service team to look into them.

**Comment by jlichwa** [comment]
Complete tutorial, can be found here https://docs.microsoft.com/en-us/azure/key-vault/secrets/overview-storage-keys-powershell

This feature is currently in depracated/legacy state, we don't support non-Account type tokens.
