### ISSUE TITLE
Powershell Module installation taking forever

### ISSUE THREAD

**Issue by FelipeCelsoR** [Azure/azure-powershell#17980]
### Description

I ran Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force on my windows powershell. Should the installation process be slow? It is taking more than 20 minutes, and so far no update. 

### Issue script & Debug output

```PowerShell
Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1645
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1645
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
I think it pulls the latest version.
```

**Comment by johnjohnjohn87** [comment]
I'm experiencing this too.

**Comment by jcs4steve** [comment]
I am also experiencing the same issue. Trying on two different laptops with different configs and the installation just hangs

**Comment by johnjohnjohn87** [comment]
> I am also experiencing the same issue. Trying on two different laptops with different configs and the installation just hangs

I was able to get installed after installing and running in PoSh 7.2.2 (latest). It took about an hour to get going, but eventually did work.

**Comment by jcs4steve** [comment]
> > I am also experiencing the same issue. Trying on two different laptops with different configs and the installation just hangs
> 
> I was able to get installed after installing and running in PoSh 7.2.2 (latest). It took about an hour to get going, but eventually did work.

I am on 7.2.2 as well. I will be more patient.  Thanks.

**Comment by dingmeng-xue** [comment]
Sorry for inconvenience. This is a known problem and has been discussed in #17210 . PSGallery team is improving it.

Another workaround is you can visit https://github.com/Azure/azure-powershell/releases/tag/v7.5.0-April2022 to download tarball. Besides all stable modules, we have added a script to help install them easily.

**Comment by ericwj** [comment]
Horrible! And when it has listed some 40

    VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()

queries, each taking half a minute, I get this:

```
VERBOSE: Checking for possible command collisions for the module 'Az.Accounts' commands.
Install-Package: The following commands are already available on this system:'Login-AzAccount,Logout-AzAccount,Resolve-Error,Send-Feedback'. This
module 'Az.Accounts' may override the existing commands. If you still want to install this module 'Az.Accounts', use -AllowClobber parameter.
```

If it isn't quite clear due to missing color: that is a *fatal* error meaning nothing got done. Not sure why this is; maybe visual studio 2022 preview installs something that clashes? One offending module is `AzureRM.Profile`.
