### ISSUE TITLE
Set-AzureVMDscExtension checks local computer for DSC modules

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#18]
**Problem Description**: The `Set-AzureVMDscExtension` command in the Azure PowerShell module, version 0.8.11, is checking the local computer for all of the supporting DSC modules (resources) before deploying the configuration document to the target virtual machine. If the local computer doesn't have all of the DSC resources that are required on the target system, then the command fails.

**Expected Behavior**: The Set-AzureVMDscExtension` command should not require that DSC resources be present on the local system, prior to deployment of the new/updated VM configuration.

![image](https://cloud.githubusercontent.com/assets/466713/5236170/3682437e-77e6-11e4-8c52-4797b55a1e6f.png)

> VERBOSE: Parsing configuration script: C:\<foldernamegoeshere>\dc01-dsc.ps1
Publish-AzureVMDscConfiguration : Configuration script 'C:\<foldernamegoeshere>\dc01-dsc.ps1' contained parse errors:
At C:\<foldernamegoeshere>\dc01-dsc.ps1:7 char:5
+     Import-DscResource -ModuleName xActiveDirectory,xPendingReboot;
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unable to load module 'xActiveDirectory': module not found.

**NOTE**: I found out that the `Publish-AzureVMDscConfiguration` command is bundling together the DSC modules along with the DSC configuration document, but this should still be an optional configuration. If I pre-stage the DSC resource on the target system using another mechanism, I shouldn't have to bundle them into the Azure DSC ZIP file.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://twitter.com/pcgeek86

**Comment by narrieta** [comment]
@pcgeek86:

Thank you for your feedback.

Note that  Set-AzureVMDscExtension doesn't parse the configuration for dependent modules. That happens during Publish-AzureVMDscConfiguration. 

We'll consider adding an option to skip this, but in the meanwhile you can work around it by creating your own ZIP file. Just add the configuration script in the root of the package and a directory for each module you want to include. Once the ZIP is ready, you can use 

     Publish-AzureVMDscConfiguration -ConfigurationPath my.zip

to upload it to blob storage.

**Comment by markcowl** [comment]
@pcgeek86 Closing this issue due to age.  If you're still hitting this, please open an issue and we'll pursue a fix.
