### ISSUE TITLE
Get-AzureAutomationAccount doesn't throw an exception for an invalid Azure location

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#180]
## Scenario

When you run the Get-AzureAutomationAccount command, and specify an invalid value for the `-Name` parameter (eg. a non-existent account), an exception is thrown, pointing out that the specified account name does not exist.

However, when you specify the `-Location` parameter, and pass in an invalid Azure location, **or** no accounts exist in the specified region / location, then no exception is thrown.

![image](https://cloud.githubusercontent.com/assets/466713/6275042/4c6b4eb8-b839-11e4-8bc3-c896c70687e0.png)
## Expected Behavior

My expectation would be that, in all circumstances, if an invalid name is specified, or an invalid region is specified, or if no accounts exist in a specific region, then an exception should be thrown.

If the command is executed without any parameters, then no exception should be thrown, since the user was not asking for a specific account, or accounts from a specific Azure region.

Thanks for your consideration.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by jodoglevy** [comment]
I partly agree with this, but consider it low priority since checking $accounts.count on the output will give you the same info, and is better than relying on errors to determine the next action to perform if 0 results are returned, since ErrorActionPreference can affect whether the errors would be surfaced by this command or not.

I will mark a bug on this for our team, but I do think it is low priority.

**Comment by pcgeek86** [comment]
Joe,

I agree that this is low priority. This is one of those things that is a polish for end user experience. The benefits of changing this behavior is:

1. `try..catch` statements will properly handle terminating errors.
2. User experience consistency with other core PowerShell commands (eg. Get-Process -Name nonexistent)
3. User experience consistency between using -Name parameter by itself, and in conjunction with -Location

```
try {
    Get-AzureAutomationAccount -Name trevor -ErrorAction Stop -ErrorVariable GetAccountError;
}
catch {
    Add-Content -Path c:\temp\ AzureAutomation.log -Value ('Error occurred retrieving account: {0}' -f $GetAccountError[0].Message);
}
```

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
