### ISSUE TITLE
Import-AzureRmAutomationDscConfiguration: File name shouldn't be required to match the DSC Configuration name

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1803]
When you use the `Import-AzureRmAutomationDscConfiguration` command to import a PowerShell script file into an Azure Automation Account, the file name **must** match the DSC configuration name. If the DSC Configuration name, and the script file name that contains it, do not match, then you receive the exception below.

This is inconsistent with the Azure Portal experience, where no such naming requirement exists.

```
Import-AzureRmAutomationDscConfiguration : BadRequest: The configuration name in the script must match the configuration name.
At C:\Users\TrevorSullivan\Documents\Import DSC Configuration.ps1:26 char:1
+ Import-AzureRmAutomationDscConfiguration @DscConfiguration;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Import-AzureRmAutomationDscConfiguration], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.ImportAzureAutomationDscConfiguration
```

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 This seems like an unnecessary restriction.  Adding in the automation team.

**Comment by pcgeek86** [comment]
@markcowl Thanks Mark! This should be a fairly straightforward fix, and might even result in removing some code, instead of adding code. :)

**Comment by jodoglevy** [comment]
This is by design. Same as on the runbook side.

**Comment by pcgeek86** [comment]
@jodoglevy If it's by design, then the inconsistency with the Portal experience should be rectified. What was the reasoning behind the current PowerShell design?

**Comment by jodoglevy** [comment]
I did not know we allowed this from the portal. Given we do, maybe we should match in the cmdlets, yes. But I would say its a best practice to name your PSWF runbook / DSC Configuration file with the same name as the PSWF runbook / DSC Configuration it contains. Otherwise it will get confusing when you have many PSWF runbooks / DSC Configs in files, as to what each file contains. You shouldn't need to open a runbook / config file up to know which runbooks / config is in the file.

**Comment by pcgeek86** [comment]
> You shouldn't need to open a runbook / config file up to know which runbooks / config is in the file.

That's a nice thought, but probably better for the user to make that decision, or at least be consistent between interfaces. If you support it via the Portal, then why not via automation interfaces?

**Comment by jodoglevy** [comment]
In addition to my above reason, script runbooks don’t have a name declaration within the file like workflows / configurations do. The file name is used as the script name. I’d think we’d want to be consistent across all runbook / config types as to where the item name comes from (to be the file name).

Also, referencing a child script runbook from a runbook inline uses the file name (just like scripts locally):
.\myrunbook.ps1

**Comment by 4c74356b41** [comment]
Am I losing my mind?
:\Windows\system32> Import-AzureRmAutomationDscConfiguration -SourcePath C:\whatever\setup-sql-2016.ps1
mport-AzureRmAutomationDscConfiguration : BadRequest: The configuration name in the script must match the configuration name.

In the file I have "Configuration setup-sql-2016"

**Comment by DdenBraver** [comment]
This restriction still seems to be in place.
Is there any update on this? It feels a bit strange, that the ps1 name and the configuration name should be the same.

**Comment by GoEddie** [comment]
I got this, please remove the restriction - I am confident that I am capable of managing a set of files :)

**Comment by raandree** [comment]
Just ran into this as well. Are there still plans to remove this restriction?

**Comment by lfshr** [comment]
Why is this designed this way? I do not recall any documentation stating that this was best practice, nor do I believe it is best practise as Azure really doesn't care about the file names after import.

**Comment by AndrewShepherd** [comment]
It seems there are two arbitrary restrictions applied to the powershell module that are not applied to the portal:

- The node configuration name must match the file name
- The node configuration name cannot contain hyphens

Neither of these restrictions are on the portal. Can you PLEASE just remove these restrictions, there's no understandable reason for them to be there!

**Comment by jodoglevy** [comment]
I'm no longer working on this project, folks. @eamonoreilly can you take a look?

**Comment by maddieclayton** [comment]
@vrdmr @eamonoreilly Can you take another look at this issue?

**Comment by jeffgebhardt** [comment]
I also ran into this issue. Another note through trial and error, it turns out uppercase letters are also not allowed.

**Comment by timothytavarez** [comment]
Still encountering this with the new Az equivalent: Import-AzAutomationDscConfiguration. My import ONLY succeeded when I matched the -SourcePath value and the configuration name.

`Import-AzAutomationDscConfiguration : {"code":"BadRequest","message":"The configuration name in the script must match the 
configuration name."}
At line:1 char:1
+ Import-AzAutomationDscConfiguration -SourcePath "C:\Dev\DSC\powerstig ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Import-AzAutomationDscConfiguration], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.ImportAzureAutomationDscConfiguration`

**Comment by raandree** [comment]
Can anybody please take care of this? This issue is now open more than 3 years and should not be so hard to get fixed.

**Comment by andyw248** [comment]
Triaged: Bug filed.

**Comment by andyw248** [comment]
The behavior in the portal is similar - pick a file and the config name is generated from that.

**Comment by pcgeek86** [comment]
This bug was filed because the behavior differs from the portal, and is asking for consistency. Notice how everyone is experiencing the same problem in the comments.

**Comment by GoEddie** [comment]
This is disappointing, the fix is to delete an unnecessary restriction.

**Comment by varnav** [comment]
Please remove this restriction, file name should not matter here.

**Comment by raandree** [comment]
I want to vote to get this fixed as well. There is no advantage keeping the restriction in place.

**Comment by GoEddie** [comment]
It is beyond a joke, four and a half years for a check that isn’t even necessary

**Comment by raandree** [comment]
@andyw248, can you have a look at this, please? It would be great if you can reconsider if this issue should be really closed.
