### ISSUE TITLE
[Feature]: Remove Debian 9 Docker image

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#18049]
### Description of the new feature

Debian 9 “[Stretch](https://wiki.debian.org/LTS/Stretch)” will end of support by June 30, 2022.  https://wiki.debian.org/LTS

All related files should be removed from resource repo. Image will be kept in repo.

**Comment by Nickcandy** [comment]
The docker file of Debian 9 has been removed
