### ISSUE TITLE
[Feature]: Offer Mariner Linux docker image

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#18051]
### Description of the new feature

CBL-Mariner is an internal Linux distribution for Microsoft’s cloud infrastructure and edge products and services. https://github.com/microsoft/CBL-Mariner. We need to create new docker image based on its PowerShell image https://github.com/PowerShell/PowerShell-Docker/blob/master/release/7-3/mariner1/docker/Dockerfile

**Comment by Nickcandy** [comment]
@dingmeng-xue The link above seems like been removed. I have added a docker file based on Mariner 1. Do we need to change correspondingly?

**Comment by dingmeng-xue** [comment]
Thanks. Please follow the official doc https://hub.docker.com/_/microsoft-powershell. We need to support the latest Mariner version.
