### ISSUE TITLE
Stop-AzVM -Confirm:$false print confirm

### ISSUE THREAD

**Issue by CallMeByMyName** [Azure/azure-powershell#18089]
### Description

Hello,

There is a problem with the generic "Confirm" parameter which is obviously not correctly supported. Despite the request to deactivate the confirmation of actions, the cmdlet prompts a confirmation.
It's blocking when the script has to stop many VMs.

### Issue script & Debug output

```PowerShell
PS> Stop-AzVM -Name $VM.Name -ResourceGroupName $VM.ResourceGroupName -Confirm:$false
Virtual machine stopping operation
This cmdlet will stop the specified virtual machine. Do you want to continue?
[O] Oui  [N] Non  [S] Suspendre  [?] Aide (la valeur par défaut est « O ») : o
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.7.6      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     4.26.0     Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk...}
```

**Comment by SatishBoddu-MSFT** [comment]
@CallMeByMyName 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SatishBoddu-MSFT** [comment]
Routing to the Service team for further action on this issue!

![image](https://user-images.githubusercontent.com/62923178/168704866-fe8e8b94-f335-4f39-a617-2c1beb87b386.png)

**Comment by Drewm3** [comment]
@jaylabell, could you work with the VM PowerShell team to see if this is a bug in the specific cmdlet or if this is a general PowerShell bug? I would have guess that suppressing confirmations was a general thing that PowerShell handled instead of each cmdlet.

**Comment by Sandido** [comment]
There are 2 checks occurring here. 
Confirm:$True causes the Confirm check to occur. 

```
Confirm
Are you sure you want to perform this action?
Performing the operation "Stop" on target "vmstop".
```


There is also a Default Safety check that occurs on all Delete operations asking 'Are you sure?'

```
Virtual machine stopping operation
This cmdlet will stop the specified virtual machine. Do you want to continue?

```

If you do not want any confirmation at all, including the Default Safety check, you can include the -Force parameter in the cmdlet call. 
`Stop-AzVm -ResourceGroupName <RG Name> -Name <VM Name> -Force`

**Comment by Sandido** [comment]
@Drewm3 , @jaylabell , I think this is By Design and can be closed. 
If you try this with a non-Delete cmdlet such as Restart-AzVm, then it works just fine. -Confirm:$false and -Confirm (-Confirm:$true).
