### ISSUE TITLE
Get-AzRoleAssignment has graph warning but is still calling ARM API

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#18095]
### Description

The command warns it has switched to Microsoft Graph, but it still calls Azure AD endpoint.

### Issue script & Debug output

```PowerShell
❯ Get-AzRoleAssignment -ObjectId '3912ae06-1c1b-09a8-26a6-04e68caaxxxx'
Debug Result Filtered:
...
Absolute Uri:
https://management.azure.com/subscriptions/xxx/providers/Microsoft.Authorization/roleAssignments?$filter=principalId eq '3912ae06-1c1b-09a8-26a6-04e68caaxxxx'&api-version=2020-08-01-preview
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22598
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.6                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     0.0.1                 Az.PIM                              {Enable-AzPIMRole, Get-AzPIMRole}
Script     5.6.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
N/A
```

**Comment by dingmeng-xue** [comment]
@JustinGrote , `https://management.azure.com` is Azure Resource Management (ARM) endpoint. `Get-AzRoleAssignment` calls ARM by default and alternatively calls MSGraph API in certain scenarios. We show that warning message just to tell user to check API permission if MSGraph related feature doesn't work. If it works on your case, you can ignore that message.

**Comment by JustinGrote** [comment]
> @JustinGrote , `https://management.azure.com` is Azure Resource Management (ARM) endpoint. `Get-AzRoleAssignment` calls ARM by default and alternatively calls MSGraph API in certain scenarios. We show that warning message just to tell user to check API permission if MSGraph related feature doesn't work. If it works on your case, you can ignore that message.

Can you provide a scenario where it calls graph? Hasn't been my experience.

**Comment by dingmeng-xue** [comment]
Hi JustinGrote, for instance, `Get-AzRoleAssignment -SignInName abc@test.com` sends below 2 requests
1. GET https://graph.microsoft.com/v1.0/users?$filter=userPrincipalName eq %27abc%40test.com%27 (it fetches ad object id according to user's name via MSGraph API)
2. GET https://management.azure.com/subscriptions/{sub}/providers/Microsoft.Authorization/roleAssignments?$filter=principalId eq '******'&api-version=2020-08-01-preview (it calls ARM endpoint and Authorization service to get role assignment)

`https://graph.microsoft.com` is Microsoft Graph API endpoint. If you try old version of Az.Resource, you can see it goes into AzureAD Graph endpoint `https://graph.windows.net`

**Comment by JustinGrote** [comment]
Right, thanks for the clarification, that makes sense because it's a two-step process. I'll close the issue as I couldn't find a combination that resulted in a graph API call but I didn't try that one.
