### ISSUE TITLE
[Doc]: New-AzApplicationGatewayFirewallExclusionConfig

### ISSUE THREAD

**Issue by lonevvolf** [Azure/azure-powershell#18106]
### Description

On this page:
https://docs.microsoft.com/en-us/powershell/module/az.network/new-azapplicationgatewayfirewallexclusionconfig?view=azps-7.5.0

It seems it would be useful (necessary?) to document the valid values for the -Variable and -Operator parameters

**Comment by navba-MSFT** [comment]
@lonevvolf Thanks for reaching out to us. We are looking into this issue. We will update this thread once we have more details on this.

**Comment by navba-MSFT** [comment]
@lonevvolf Thanks for your feedback. We have created the above PR and it is currently pending on review. In the meantime, if you have any questions, please feel free to ask.
