### ISSUE TITLE
[Az.Accounts] MSGraph token changes when login with provided MSGraph token

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/azure-powershell#18105]
### Description

Azure PowerShell supports AccessToken login that user provide access token to ARM and MSGraph both. Due to there is no primary refresh token, the access token on request header sent by Azure PowerShell cmdlet should be the same as token provided by user. However it change during the query process.

Affected Module list:
KeyVault
StorageSync 

### Issue script & Debug output

```PowerShell
1.	Connect-AzAccount with your account
2.	Get access token to ARM and MSGraph via Get-AzAccessToken
3.	Disconnect-AzAccount; Clear-AzContext -Force
4.	Start Fiddler
5.	Restart PowerShell
6.	Connect-AzAccount -AccountId <your account> -AccessToken <> -MicrosoftGraphAccessToken <>
7.	Check token used by `Get-AzAdUser -First 1` through Fiddler
8.	Check the token used by Keyvault cmdlet which needs MSGraph call.
9.	Compare the tokens used by step 7 and step 8
```

### Environment data

```PowerShell
PWSH 7.2.1
```

### Module versions

```PowerShell
Az 7.5.0
```

**Comment by ankushbindlish2** [comment]
We are also impacted by the same problem. What is the mitigation strategy until we have the fix.

1.	Connect-AzAccount with your account
2.	Get access token to ARM and MSGraph via Get-AzAccessToken
3.	Disconnect-AzAccount; Clear-AzContext -Force
4.	Connect-AzAccount -AccountId <your account> -AccessToken <> -MicrosoftGraphAccessToken <>
5.  New-AzStorageSyncCloudEndpoint which uses MSGraph Api
UnAuthorized , Invalid Audience
