### ISSUE TITLE
Attribute values are missing in PowerShell 7.2.3 for AAD users using Get-AzADUser command 

### ISSUE THREAD

**Issue by MelodyZ654** [Azure/azure-powershell#18120]
### Description

We need to get a complete list of Azure AD users which contains the following details, but the value of some attributes is missing with the latest Az.Resources module 5.6.0. 

1. Employee Name
2. Email ID
3. Job Title
4. Location
5. Division
6. Department
7. Reporting Manager Name

**Expectation behavior**: We expect to get the full list of above attributes in the latest version of PowerShell and Az.Resources module, like using 'Get-AzureADUser' and 'Get-AzureADUserManager' in PS 5.

### Issue script & Debug output

```PowerShell
The value of the following attributes is missing when running "get-azaduser -ObjectId 00000000000000000000| fl" with the latest Az.Resources module 5.6.0. 

Location
Division        
Department     
Reporting Manager 

PS C:\Program Files\PowerShell\7> get-azaduser -ObjectId 000000000000000000000000000 | fl

AccountEnabled                  :
AgeGroup                        :
ApproximateLastSignInDateTime   :
BusinessPhone                   : {}
City                            :
CompanyName                     :
ComplianceExpirationDateTime    :
ConsentProvidedForMinor         :
Country                         :
CreatedDateTime                 :
CreationType                    :
DeletedDateTime                 :
Department                      :
DeviceVersion                   :
DisplayName                     : Test User
EmployeeHireDate                :
EmployeeId                      :
EmployeeType                    :
ExternalUserState               :
ExternalUserStateChangeDateTime :
FaxNumber                       :
GivenName                       : Test
Id                              : 0000000000000000000000000000
Identity                        :
ImAddress                       :
IsResourceAccount               :
JobTitle                        : Accountant
LastPasswordChangeDateTime      :
LegalAgeGroupClassification     :
Mail                            : Testuser@contoso.com
MailNickname                    :
MobilePhone                     :
OdataId                         :
OdataType                       : #microsoft.graph.user
OfficeLocation                  :
OnPremisesImmutableId           :
OnPremisesLastSyncDateTime      :
OnPremisesSyncEnabled           :
OperatingSystem                 :
OperatingSystemVersion          :
OtherMail                       :
PasswordPolicy                  :
PasswordProfile                 : {
                                  }
PhysicalId                      :
PostalCode                      :
PreferredLanguage               :
ProxyAddress                    :
ShowInAddressList               :
SignInSessionsValidFromDateTime :
State                           :
StreetAddress                   :
Surname                         : User
TrustType                       :
UsageLocation                   :
UserPrincipalName               : Testuser@contoso.com
UserType                        :
AdditionalProperties            : {[@odata.context, https://graph.microsoft.com/v1.0/$metadata#users/$entity]}

I tried to use the command "(get-azaduser -ObjectId 00000000000000000000).AdditionalProperties | fl" but got the following information, which I could get more information in Az.Resources 4.4.1. But in the MS public document, it does not show how to retrieve data from key. And no command is provided to get 'reporting manager'.

https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azaduser?view=azps-7.5.0

PowerShell 7.2.3 with Az.Resources module 5.6.0
================================================
PS C:\Program Files\PowerShell\7> (get-azaduser -ObjectId 00000000000000000000).AdditionalProperties | fl

Key   : @odata.context
Value : https://graph.microsoft.com/v1.0/$metadata#users/$entity
===============================================

PowerShell 7.2.3 with Az.Resources module 4.4.1
===============================================
PS C:\Program Files\PowerShell\7> (get-azaduser -ObjectId 00000000000000000000).AdditionalProperties | fl
WARNING: Upcoming breaking changes in the cmdlet 'Get-AzADUser' :
- The output type is changing from the existing type :'Microsoft.Azure.Commands.ActiveDirectory.PSADUser' to the new type :'Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphUser'
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

...
Key   : department
Value : Finance
...
```

### Environment data

```PowerShell
PS C:\Program Files\PowerShell\7> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:\Program Files\PowerShell\7> Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.6                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefa…
Script     5.6.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, G…
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Ob…
Script     2.1.0                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. MSGraph API needs user to declare attribute need to be shared. Please leverage parameter `-Select` and `-AppendSelected` https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azaduser?view=azps-7.5.0#example-2-list-users

**Comment by MelodyZ654** [comment]
> ```powershell
> 
> Location
> Division        
> Department  
> ```

**Comment by MelodyZ654** [comment]
> Thanks for reporting. MSGraph API needs user to declare attribute need to be shared. Please leverage parameter `-Select` and `-AppendSelected` https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azaduser?view=azps-7.5.0#example-2-list-users

Hi #dingmeng-xue, thank you so much for your help！ After adding the -Select and -AppendSelected parameters, I get most of the attributes I want to retrieve. Just one more question, how can I get direct manager details with command "Get-AzADUser"? As for PowerShell 5.1, there is a separate command "Get-AzureADUserManager -ObjectId <String>" to help check this info.

**Comment by dingmeng-xue** [comment]
@MelodyZ654 , property name of AzureAD object from MSGraph API may be different from AzureAD Graph API.  You can reference the list of allowed properties of AdUser from api-spec of MSGraph https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/8a3a01a78f8701c031c661ee488895f73cc0e032/openApiDocs/v1.0/Users.yml#L447

**Comment by MelodyZ654** [comment]
> @MelodyZ654 , property name of AzureAD object from MSGraph API may be different from AzureAD Graph API. You can reference the list of allowed properties of AdUser from api-spec of MSGraph https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/8a3a01a78f8701c031c661ee488895f73cc0e032/openApiDocs/v1.0/Users.yml#L447

Thanks for sharing the link. I did find the attribute "manager" in the link you shared, however, I don't see this attribute in the output of command "**Get-AzADUser -ObjectId 000000000000 -Select 'Manager'  -AppendSelected | fl**" nor "**Get-AzADUser -ObjectId 000000000000 -Select 'manager'  -AppendSelected | fl**" . Also I checked all properties with "New-AzADUser" in the doc below, but did not find how to configure the "manager" attribute either. 

https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azaduser?view=azps-7.5.0

**Comment by dingmeng-xue** [comment]
Got it. Actually, we removed it on purpose. AzAd functions provided by Azure PowerShell is basic features and sub set of features of AzureAD module or MSGraph module. Please create a github feature request list all required attributes. We will evaluate it and expose it if possible.

**Comment by MelodyZ654** [comment]
> AzAD



> Got it. Actually, we removed it on purpose. AzAd functions provided by Azure PowerShell is basic features and sub set of features of AzureAD module or MSGraph module. Please create a github feature request list all required attributes. We will evaluate it and expose it if possible.

Ok, I will submit a new request in Github. I really appreciate your help! Have a nice one.
