### ISSUE TITLE
Get-AzureRmStorageAccount :: Incorrect Output

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1814]
# Issue

When invoking the `Get-AzureRmStorageAccount` command, with **only** the `-Name` parameter, the parameter is ignored, and all Storage Accounts are returned, as if the parameter was not even specified.

# Expected Result

The `Get-AzureRmStorageAccount` command, when invoked with only the `-Name` parameter, should return one, and only one, Storage Account.

![bug](https://cloud.githubusercontent.com/assets/466713/13029668/9d251bfa-d24f-11e5-8011-295d2501b96e.gif)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 Unfortunately, the design would be to throw an error saying 'please specify a resource group', which is perhaps even more wrong than the current behavior.  Assigning to the storage team.  Defaulting to Find functionality is something we should consider as the pattern for each RP.

**Comment by EmmaZhu** [comment]
Thanks @pcgeek86 for bringing this to us.
It needs both resource group name and account name to fetch a particular account in ARM, only specifying -Name in Get-AzureRmStorageAccount should not be an available operation. 
We'll get the fix into the nearest sprint.

**Comment by vinjiang** [comment]
Feel free to try the newly released version and let us know if you have further questions.

**Comment by pcgeek86** [comment]
@EmmaZhu @vinjiang @markcowl  Thanks, looks good to me! 

![image](https://cloud.githubusercontent.com/assets/466713/15078284/b2187e60-136f-11e6-97d8-25589c353f14.png)
