### ISSUE TITLE
New-AzureRmApplicationGatewaySslCertificate does not support empty password

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-powershell#1818]
```
New-AzureRmApplicationGatewaySslCertificate -Name "cert1" -CertificateFile "path-to-cert" -Password ""
New-AzureRmApplicationGatewaySslCertificate : Cannot validate argument on parameter 'Password'. The argument is null or empty. Provide an argument that is not null 
or empty, and then try the command again.
At line:1 char:127
+ ... CertificateFile "path-to-cert" -Password ""
+                                                                        ~~
    + CategoryInfo          : InvalidData: (:) [New-AzureRmAppl...ySslCertificate], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Network.NewAzureApplicationGatewaySslCertificateCommand
```

If no password is set when I export the cert, I will get the above error.

```
openssl pkcs12 -export -out domain.name.pfx -inkey domain.name.key -in domain.name.crt
Enter Export Password:
Verifying - Enter Export Password:
```

**Comment by markcowl** [comment]
@DeepakRajendranMsft Please consider.

**Comment by markjbrown** [comment]
Will put on list for vNext planning

**Comment by maddieclayton** [comment]
@akshaysngupta Can you take a look at this issue?

**Comment by akshaysngupta** [comment]
Will update the issue with the timeline of the release.

**Comment by EvgenyAgafonchikov** [comment]
Seems to be outdated. Current cmdlet output is
`New-AzApplicationGatewaySslCertificate : Cannot bind parameter 'Password'. Cannot convert the "" value of type "System.String" to type "System.Security.SecureString".`

So likely the way to create empty password now is:
`$pw = new-object System.Security.SecureString`
and then use $pw variable as an argument

@bingosummer, could you please confirm the solution?

**Comment by bingosummer** [comment]
@EvgenyAgafonchikov The solution works for me.
