### ISSUE TITLE
[Feature]: Request to add "Manager" and "Division" attributes to Az.Resources module using PowerShell 7

### ISSUE THREAD

**Issue by MelodyZ654** [Azure/azure-powershell#18205]
### Description of the new feature

We need to get a complete list of Azure AD users, but two important attributes "Manager " and "Division" are not showing up using command "Get-AzADUser -ObjectId 000000000000 -Select 'Manager,Division' -AppendSelected | fl". 

1. Reporting Manager Name
2. Division

Environment:  Az.Resources module 5.6.0 with PowerShell 7.2.3

I raised a ticket in Github https://github.com/Azure/azure-powershell/issues/18120 and got confirmation that the "Manager" attribute was moved on purpose. I can find the two attributes in the list of allowed properties of AdUser from api-spec of MSGraph https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/8a3a01a78f8701c031c661ee488895f73cc0e032/openApiDocs/v1.0/Users.yml#L447, but could not know how to configure them with "New-AzADUser" nor retrieve them with "Get-AzADUser" . Please help add the two attributes to the next Az.Resources version with PS 7.
https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azaduser?view=azps-7.5.0

**Comment by dingmeng-xue** [comment]
@VeryEarly , please evaluate this feature request.

**Comment by VeryEarly** [comment]
For this particular feature request, we need below 3 attributes added to our swagger:

- https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/8a3a01a78f8701c031c661ee488895f73cc0e032/openApiDocs/v1.0/Users.yml#L6265
- https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/8a3a01a78f8701c031c661ee488895f73cc0e032/openApiDocs/v1.0/Users.yml#L5528
- https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/8a3a01a78f8701c031c661ee488895f73cc0e032/openApiDocs/v1.0/Users.yml#L5786
