### ISSUE TITLE
[Feature]: Purging of App Configuration Stores

### ISSUE THREAD

**Issue by sopelt** [Azure/azure-powershell#18208]
### Description of the new feature

Similar to the recently added Azure CLI feature [az appconfig purge](https://docs.microsoft.com/en-us/cli/azure/appconfig?view=azure-cli-latest#az-appconfig-purge) *Az.AppConfiguration* also needs a way to purge App Configuration Stores.

It does not seem (easily) possible to completely delete and re-provision an environment containing an App Config as the deployment will fail because the name (of the previously existing store) can not be reused.

Right now the call to [New-AzAppConfigurationStore](https://docs.microsoft.com/en-us/powershell/module/az.appconfiguration/new-azappconfigurationstore?view=azps-7.5.0) seems to fail with 

> Exception: [EntityNotFound] : The resource with id 'xxx-appcfg' was not found.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will evaluate this requirement.

**Comment by dingmeng-xue** [comment]
Fixed by https://github.com/Azure/azure-powershell/pull/19325
