### ISSUE TITLE
[Eng]: sync more files from main to generation branch

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#18207]
### Description

We have a pipeline [azure-powershell - sync-tools-folder](https://dev.azure.com/azure-sdk/internal/_build?definitionId=2904) to sync files which are necessary for building on both main and generation branch. However `src/Az.props` and `src/shared/*` (introduced by #18162) are not on the list of files to sync. This caused CI errors.

### Excpeted
`src/Az.props` and `src/shared/` can be sync by the pipeline.

**Comment by BethanyZhou** [comment]
I added a prop file named Az.Post.props in previous release. I'm wondering whether it should be added into the sync list
