### ISSUE TITLE
[Doc]: Set-AzVMSecurityProfile cannot change the --SecurityType

### ISSUE THREAD

**Issue by OrlandoAMunoz** [Azure/azure-powershell#18204]
### Description

Set-AzVMSecutiryProfile only works during the VM creation process.

Please include a warning on the following DOC stating Set-AzVMSecutiryProfile cannot change the --SecurityType from None to Trusted or from Trusted to None on existing VMs.
https://docs.microsoft.com/en-us/powershell/module/az.compute/set-azvmsecurityprofile?view=azps-7.5.0

Set-AzVMSecutiryProfile should also issue an error when applying a --SecurityType change on an existing VM.

**Comment by navba-MSFT** [comment]
@OrlandoAMunoz Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@OrlandoAMunoz Could you please test with the below command and check:

>$VM = Get-AzVM -ResourceGroupName "ResourceGroup11" -VMName "ContosoVM07"
$vmSecurityProfile = Set-AzVmSecurityProfile -VM $VM -SecurityType "TrustedLaunch"
$vmSecurityProfile.SecurityProfile

The first command gets the virtual machine named ContosoVM07 by using Get-AzVm. The command stores it in the $VM variable. The second command sets the SecurityType enum to "TrustedLaunch"

Please test this and get back to us. If you face any issues while setting the SecurityType, please share the debug output here by running `$DebugPreference="Continue" `command first before running the above command.

**Comment by OrlandoAMunoz** [comment]
Hi,

It is not clear on the documentation that once you apply -SecurityType "TrustedLaunch", you cannot revert it back to -SecurityType "None".
It is a one way road.
There's no going back.

It was not clear to the customer why using the -SecurityType "None" after enabling "TrustedLaunch" was not possible.
The note I was asking is to clarify this, so the customer doesn't ask why he has to recreate a VM in order to remove the "TrustedLaunch".

Kind regards,

Orlando Muñoz
Support Engineer
Microsoft Azure Technical Support
Customer Service and Support
Office: +351 (21) 0491844
***@***.******@***.***>
Working hours: Mon-Fri, 8:30 - 17:30 UTC+1
If you need to work with another Support Engineer outside of my working hours, please send email to ***@***.******@***.***> with your case number, and availability.
We are always interested to hear your feedback. Please feel free to reach my manager regarding the level of service you have received, at ***@***.******@***.***>.
[Microsoft Azure logo]

**Comment by navba-MSFT** [comment]
@OrlandoAMunoz Thanks for getting back. I am able to switch between SecurityType "TrustedLaunch" to "None" and vice versa. See below:

![image](https://user-images.githubusercontent.com/57353862/177738103-8dc303a7-9da8-4df8-9aa6-5daaacc5a639.png)

If it is failing for the customer, then ensure that they are using the most recent version of the [Az.Compute ](https://www.powershellgallery.com/packages/Az.Compute/4.29.0)module.

Even after updating the Az.Compute module if they see the same issue, then please share the debug output here by running $DebugPreference="Continue" command first before running the above command.

**Comment by OrlandoAMunoz** [comment]
Hi,

That setting will show ok ("None"), but try to open the VM again and look at the setting.
You will see the setting reverted back to TrustedLaunch.

Kind regards,

Orlando Muñoz
Support Engineer
Microsoft Azure Technical Support
Customer Service and Support
Office: +351 (21) 0491844
***@***.******@***.***>
Working hours: Mon-Fri, 8:30 - 17:30 UTC+1
If you need to work with another Support Engineer outside of my working hours, please send email to ***@***.******@***.***> with your case number, and availability.
We are always interested to hear your feedback. Please feel free to reach my manager regarding the level of service you have received, at ***@***.******@***.***>.
[Microsoft Azure logo]

**Comment by navba-MSFT** [comment]
@OrlandoAMunoz The "None" value doesn't seem to be applicable here as the accepted value for the **SecurityType** should be  either of the below:

Name | Type | Description
-- | -- | --
**ConfidentialVM** | string |  
**TrustedLaunch** | string

Did you check if these settings persists after running the command ? Awaiting your reply.

More Info [here](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/update#securitytypes).

**Comment by OrlandoAMunoz** [comment]
Hi,

From https://docs.microsoft.com/en-us/powershell/module/az.compute/set-azvmsecurityprofile?view=azps-7.5.0

***@***.***
A note should be added stating this is irreversible.
That way the customer wouldn’t open a case asking how can they revert 😉

Kind regards,

Orlando Muñoz
Support Engineer
Microsoft Azure Technical Support
Customer Service and Support
Office: +351 (21) 0491844
***@***.******@***.***>
Working hours: Mon-Fri, 8:30 – 17:30 UTC+1
If you need to work with another Support Engineer outside of my working hours, please send email to ***@***.******@***.***> with your case number, and availability.
We are always interested to hear your feedback. Please feel free to reach my manager regarding the level of service you have received, at ***@***.******@***.***>.
[Microsoft Azure logo]

**Comment by navba-MSFT** [comment]
@OrlandoAMunoz The above PR has been created to address this.

**Comment by taasoda6** [comment]
1 year later and it's still not working. Wow

**Comment by BethanyZhou** [comment]
Hi @taasoda6 , thanks for reaching out to us here. From the discussion above, seems changing SecurityType from None to other values is irreversible. Could you help confirm? @navba-MSFT . 

If you have feature request for this, please open a new GitHub issue.
