### ISSUE TITLE
Update-AzureRMVM Availability Set

### ISSUE THREAD

**Issue by ncipollina** [Azure/azure-powershell#1820]
I am attempting to add an existing VM to an existing availability set and I am receiving the following error:

Update-Azurermvm : Changing property 'availabilitySet.id' is not allowed.
StatusCode: 409
ReasonPhrase: Conflict
OperationID : '77d0ae10-6e4f-4d11-8494-29f37433cdc0'
At line:1 char:1
+ Update-Azurermvm -VM $vm -ResourceGroupName bshsi-azcdrg-2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Update-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand

Below are the commands I issued in attempting to do this:

`$vm = Get-azurermvm -Name $vmName -ResourceGroupName $rg
$set = Get-AzureRmAvailabilitySet -ResourceGroupName $rg
$vm.AvailabilitySetReference = $set.Id
Update-Azurermvm -VM $vm -ResourceGroupName $rg`

This seems like something I should be able to do.  I know that I can add the VM to an availability set when creating the VM, but I don't want to have to recreate a VM just to add it to an availability set.

**Comment by alexandair** [comment]
Look at this thread https://github.com/Azure/azure-xplat-cli/issues/1937

**Comment by markcowl** [comment]
@huangpf Can you please update with the expectations for supporting this scenario?

**Comment by huangpf** [comment]
+@singhkay & @mathi who would know more about the timeline for having this support.

**Comment by singhkay** [comment]
@Mahthi is the right person for this but it is on the backlog. I would not expect this come in the first half of this year.

**Comment by SamirFarhat** [comment]
AFAIK, this feature may be addressed by the end of this year. It's a big challenge for the MS team to allow such operation. Changing the availability Set requires a review of the VM mobility architecture on Azure. Fore example, adding a VM in an Availability Set already containing a VM means putting it to different default domain. Becasue VM mobilty is a matter on Azure (No Live Migration), it's not an easy operation.
I have written a Powershell script which let you change the AS of an ARM VM by recreating it. Give it a try and enjoy :
https://buildwindows.wordpress.com/2016/02/25/add-or-change-an-arm-virtual-machines-availability-set/

**Comment by singhkay** [comment]
Closing for now as platform needs to support this first.
