### ISSUE TITLE
Get-AzRecoveryServicesBackupRecommendedArchivableRPGroup requires '/action' permission

### ISSUE THREAD

**Issue by MarcSteene** [Azure/azure-powershell#18211]
### Description

Hi,

I'm attempting to use Get-AzRecoveryServicesBackupRecommendedArchivableRPGroup to get the recovery points recommended for move to archive tier for cost savings. A 'get' or 'read' command like this I'd expect would only require read permissions to retrieve the recovery points, but it requires an action permission meaning the Reader role is insufficient: ‘Microsoft.RecoveryServices/vaults/backupFabrics/protectionContainers/protectedItems/recoveryPointsRecommendedForMove/action‘

This makes things awkward from a reporting perspective as a custom role has to be created or an overprivileged role such as backup operator needs to be assigned.

**Comment by RakeshMohanMSFT** [comment]
@MarcSteene Thank you for reaching out, we are looking into it.

**Comment by Daya-Patil** [comment]
@MarcSteene do you still experience the issue ?

**Comment by hiaga** [comment]
Please share debug logs by adding the -Debug parameter to this command and re-open this issue. we can check further on this
