### ISSUE TITLE
Set-AzureAppServicePlan conflict did not populate error variable

### ISSUE THREAD

**Issue by adam-knights** [Azure/azure-powershell#1823]
I have code like:

```
Set-AzureAppServicePlan -Name "$AppPlanName" -ResourceGroupName "$ResourceGroupName" -Sku "Basic" -WorkerSize "Small" -Location "North Europe" -ErrorVariable +errors
```

Today this is giving a error/conflict of

> Conflict
> 
> Failed to update App Service plan Integration-App-Service-Plan: Not enough available reserved instance servers to satisfy this request. Currently 0 instances are available. If you are changing instance size you can reserve up to 0 instances at this moment. If you are increasing instance count then you can add extra 0 instances at this moment.

However, the errors variable is not populated. But an error/conflict occurred so it should be.

I also tried wrapping the `Set-AzureAppServicePlan` in a try/catch but it never entered the catch.

and then I have

```
    if ($errors)
    {
        #Send errors to hipchat
        $errorBody = @{
            color = "red"
            message = "Failed to change integration to paid for plan, error: $errors[0].Exception"
            notify = "true"
            message_format = "text"
        }

        $r = Invoke-RestMethod -Method Post -Uri $hipchatUrl -Credential $cred -Body $errorBody

        Exit
    }
```

I'll be contacting Azure support to fix the actual error itself, however, my runbook script reported no errors when it should have.

**Comment by pcgeek86** [comment]
FYI, in PowerShell, `try..catch` statements only catch "terminating" errors. Non-terminating errors are more commonly thrown in PowerShell, so what you can do, is change the non-terminating error into a terminating error, by using the `-ErrorAction Stop` common parameter to all Advanced Functions and binary Cmdlets.

This isn't a problem with Azure PowerShell. It's simply how PowerShell was designed to work. As long as it is explained and understood, it makes quite a bit of sense.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by adam-knights** [comment]
Thanks @pcgeek86 I added the action stop's and we now hit the try catch. I'll leave this open as I think Set-AzureAppServicePlan and the other new methods would benefit from msdn documentation. As an example, trying to work out three strings that can be used in `WorkerSize` param is not as straight forward as it should be.

**Comment by pcgeek86** [comment]
@adam-knights Totally agree on the other parts. Just trying to help in the error handling space. :)

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
