### ISSUE TITLE
[Doc]: Example code in Add-AzDelegation is incorrect

### ISSUE THREAD

**Issue by nickstokes** [Azure/azure-powershell#18242]
### Description

The example code in this document assumes that the Get-AzVirtualNetworkSubnetConfig command returns the subnet it creates, but it actually returns the vnet that it was created in, which causes the next command to fail.

**Comment by dingmeng-xue** [comment]
@CaptainFanZzz , please look into this issue. If we have no context, let's talk to service team.

**Comment by CaptainFanZzz** [comment]
Docs have been updated. The version is Az Powrshell 8.0.0.
