### ISSUE TITLE
Register-AzureAutomationScheduledRunbook does not support Hybrid Workers

### ISSUE THREAD

**Issue by JakobGSvendsen** [Azure/azure-powershell#1824]
AzureAutomation has added support for setting a hybrid worker to run a runbook via the schedule.

it is not supported by the cmdlet.

![image](https://cloud.githubusercontent.com/assets/3460807/13112762/8dc09bf4-d58c-11e5-8dcb-94dd95b4d5f0.png)

**Comment by markcowl** [comment]
@jodoglevy Can you take a look?

**Comment by jodoglevy** [comment]
Yup, looks like an issue. Will open a bug internally to track this.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
