### ISSUE TITLE
-AzScheduledQueryRule- Azure monitor Log Analytics Schedule query rule giving Error-New

### ISSUE THREAD

**Issue by ksanjay209** [Azure/azure-powershell#18259]
### Description

I am setting an alert rule on my Linux VMs to create alert when its file partitions over 80% utilized using New-AzScheduledQueryRule. Bug getting error:- Please can you advise how this can be resolved?

Error :--
Body:
{
  "error": {
    "code": "BadRequest",
    "message": "{\r\n  \"error\": {\r\n    \"message\": \"The request had some invalid properties\",\r\n    \"code\": \"BadArgumentError\",\r\n    \"correlationId\": \"fde8853a-0392-47f9-b24f
-eb837386254a\",\r\n    \"innererror\": {\r\n      \"code\": \"SyntaxError\",\r\n      \"message\": \"Request is invalid and cannot be processed: Syntax error: SYN0001: I could not parse that
, sorry. [line:position=0:0]\"\r\n    }\r\n  }\r\n}"
  }
}

New-AzScheduledQueryRule : Exception type: Exception, Message: System.Exception: Error occurred while creating Log Alert rule ---> System.AggregateException: One or more errors occurred. 
---> Microsoft.Azure.Management.Monitor.Models.ErrorContractException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.ScheduledQueryRulesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Commands.Insights.ScheduledQueryRules.NewScheduledQueryRuleCommand.ProcessRecordInternal()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Insights.ScheduledQueryRules.NewScheduledQueryRuleCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null
At line:8 char:1

**Here is Script:-** 
$source = New-AzScheduledQueryRuleSource -Query 'Perf | where TimeGenerated > ago(15m)| where Computer contains "az" and CounterPath contains "(/)" and CounterName contains "% Used Space"| where CounterValue >= 80 | project SmartsVM = Computer,TimeGenerated, Alerts_Title = strcat("Smarts Linux VM File Parition (",InstanceName ,") is over 80% used"),CounterValue | summarize a= avg(CounterValue) by bin(TimeGenerated,30m) , SmartsVM, Alerts_Title | project a, SmartsVM, Alerts_Title' -DataSourceId "/subscriptions/xxxxxxx" -QueryType Number

$schedule = New-AzScheduledQueryRuleSchedule -FrequencyInMinutes 5 -TimeWindowInMinutes 2880

$metricTrigger = New-AzScheduledQueryRuleLogMetricTrigger -ThresholdOperator "GreaterThan" -Threshold 1 -MetricTriggerType Total -MetricColumn 4

$triggerCondition = New-AzScheduledQueryRuleTriggerCondition -ThresholdOperator "GreaterThan" -Threshold 80 -MetricTrigger $metricTrigger

$aznsActionGroup = New-AzScheduledQueryRuleAznsActionGroup -ActionGroup "/subscriptions/xxxx" -EmailSubject "Smarts Linux VM Parition Threshold Alerting" -CustomWebhookPayload "{ "alert":"#alertrulename", "IncludeSearchResults":true }"

$alertingAction = New-AzScheduledQueryRuleAlertingAction -AznsAction $aznsActionGroup -Severity "3" -Trigger $triggerCondition

New-AzScheduledQueryRule -ResourceGroupName "xxx" -Location xx-Action $alertingAction -Enabled $true -Description "Smarts Linux VM Parition is 80% over utilized" -Schedule $schedule -Source $source -Name "Smarts Linux VM Parition Threshold Alerting"

### Issue script & Debug output

```PowerShell
New-AzScheduledQueryRule : Exception type: Exception, Message: System.Exception: Error occurred while creating Log Alert rule ---> System.AggregateException: One or more errors occurred. 
---> Microsoft.Azure.Management.Monitor.Models.ErrorContractException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.ScheduledQueryRulesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Commands.Insights.ScheduledQueryRules.NewScheduledQueryRuleCommand.ProcessRecordInternal()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Insights.ScheduledQueryRules.NewScheduledQueryRuleCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null
At line:8 char:1


**Here is Script:-** 
$source = New-AzScheduledQueryRuleSource -Query 'Perf | where TimeGenerated > ago(15m)| where Computer contains "az" and CounterPath contains "(/)" and CounterName contains "% Used Space"| where CounterValue >= 80 | project SmartsVM = Computer,TimeGenerated, Alerts_Title = strcat("Smarts Linux VM File Parition (",InstanceName ,") is over 80% used"),CounterValue | summarize a= avg(CounterValue) by bin(TimeGenerated,30m) , SmartsVM, Alerts_Title | project a, SmartsVM, Alerts_Title' -DataSourceId "/subscriptions/xxxxxxx" -QueryType Number

$schedule = New-AzScheduledQueryRuleSchedule -FrequencyInMinutes 5 -TimeWindowInMinutes 2880

$metricTrigger = New-AzScheduledQueryRuleLogMetricTrigger -ThresholdOperator "GreaterThan" -Threshold 1 -MetricTriggerType Total -MetricColumn 4

$triggerCondition = New-AzScheduledQueryRuleTriggerCondition -ThresholdOperator "GreaterThan" -Threshold 80 -MetricTrigger $metricTrigger

$aznsActionGroup = New-AzScheduledQueryRuleAznsActionGroup -ActionGroup "/subscriptions/xxxx" -EmailSubject "Smarts Linux VM Parition Threshold Alerting" -CustomWebhookPayload "{ "alert":"#alertrulename", "IncludeSearchResults":true }"

$alertingAction = New-AzScheduledQueryRuleAlertingAction -AznsAction $aznsActionGroup -Severity "3" -Trigger $triggerCondition

New-AzScheduledQueryRule -ResourceGroupName "xxx" -Location xx-Action $alertingAction -Enabled $true -Description "Smarts Linux VM Parition is 80% over utilized" -Schedule $schedule -Source $source -Name "Smarts Linux VM Parition Threshold Alerting"
```

### Environment data

```PowerShell
Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.22000.653                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.22000.653                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                                                                                                    
---------- -------    ----                                ----------------                                                                                                                    
Script     2.7.4      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}                                                         
Script     3.0.1      Az.Monitor                          {Add-AzAutoscaleSetting, Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzMetricAlertRuleV2...}
```

**Comment by ksanjay209** [comment]
Here is the error when running the script:-

Body:
{
  "error": {
    "code": "BadRequest",
    "message": "The query of a metric measurement alert rule must include an AggregatedValue column of a numeric type"
  }
}


New-AzScheduledQueryRule : Exception type: Exception, Message: System.Exception: Error occurred while creating Log Alert rule ---> System.AggregateException: One or more errors occurred. 
---> Microsoft.Azure.Management.Monitor.Models.ErrorContractException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.ScheduledQueryRulesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Commands.Insights.ScheduledQueryRules.NewScheduledQueryRuleCommand.ProcessRecordInternal()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Insights.ScheduledQueryRules.NewScheduledQueryRuleCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Please share request body and URL to us. We need to compare your input and generated request payload.

**Comment by ksanjay209** [comment]
its resolved now .Thanks.
