### ISSUE TITLE
Community Call - OneNote/Wiki & clearly communicated timeline of item fixes

### ISSUE THREAD

**Issue by kilasuit** [Azure/azure-powershell#1826]
The Azure cmdlets are at present quintessentially not being managed and maintained in a sustainable method this is referenced back to my response to closing #1763 

So like suggested to the PSScriptAnalyzer Team I thinkg that there is a requirement to gain input from the community in a 1 hour skype call and I feel that really this needs to happen sooner rather than later.

My reasons are that 
- Amazon Cmdlets show this repo up on a number of fronts - lack of Cmdlet Help, correct use of the PowerShell Language (see #718)
- Automation with the current tooling is at best impractical and at times bordering on potential to be a major headache (ASM to ARM hasn't helped this at all)
- No external visibility on the members of this team - PM lead & core developers etc
- Too many unanswered issues (182 with under 2 comments open as of right now out of 328 open issues)
- 5 Issues are still open from November & December 2014 
- Issues/PR's for "training" being made to this repo like in #21 & #1790 which look unprofessional and dont add any confidence on using the modules that come from this repo

For a work in progress enterprise scale hosting solution supporting framework this really is unacceptable and needs to be actioned and brought into a sustainable and manageable fashion sharpish. I would like to believe that it is **only** a lack of resource that has caused this repo to allow it to get to this state.

SO Ranting aside else I'll be going on for a number of further weeks.

I propose that you block book 1 hour a week for a community call in which there is a discussion on the **most** important things to get cleared up first and then these get given deadlines to be resolved by.

Items to focus on initially (IMO)
- Old or unanswered Issues **Short term win**
- Issues with 10 or more comments **Short term win**
- Creating further meaningful tags for issues and getting these applied to outstanding issues **Required Longer Term**
- Triage plan of Issues - could be opportunity for  more community involvement in this **Required Longer Term**
- Building better PowerShell Language compliance by working with PSScriptAnalyzer team **Required Longer Term**

These are just a few small examples off the top of my head but something to change this current state of play **needs** to happen and soon

**Comment by SimonWahlin** [comment]
@kilasuit  has a good point here and I agree. I really appreciate the effort of making more and more projects OpenSource, giving us the possibility to both follow and contribute to the progress.

Spending a little time to make it easier for contributors to feel part of the project is probably well invested since it hopefully will result in more contributions. Making it easier to understand where help is wanted and what is being worked on will also make a huge difference.

**Comment by markcowl** [comment]
@kilasuit @SimonWahlin I am in complete agreement that the issues list is not being effectively managed, to put it in the mildest possible terms.  PowerShell language compliance, consistent cmdlet signatures, and improved help are high priority items in our planning.  BTW, you can track our priorities in our pivotal project, if you are interested:  https://www.pivotaltracker.com/n/projects/1424376

I think additional opportunities for community feedback that are more open source friendly is a terrific idea.  I'm not sure that a call would be the right feedback mechanism, my initial thought is that it favors developers in or near this time zone, and may not provide enough broad-based feedback.  While we explore this excellent idea, let's keep tracking these things in GitHub - and anyone who is interested in this project should never hesitate to personally email me about any issues that you have.

I have separately responded on #1763, which is a pull request and not an issue.  It is our policy to never close an issue unless there is a resolution (checked in code, rejected, etc.)

As far as the issue and PR you mention as eroding confidence, I will respectfully disagree.  There is work to do here in cleaning up unnecessary commits and improving commit comments, but the warts tell me that this is an actual repo that developers develop in, accepting community contributions.  

Thanks for the feedback, and lets use this issue to track adding some additional avenues for community involvement.

**Comment by doctordns** [comment]
Great thread so far!
I am, this week, in India - any conference call would be at a time  that I'd prefer to be asleep!
I think there is a PR job here - the cmdlets have, imho, been a bit of a mess. The whole switch-azure mode is, to my mind, a huge mistake, and the pain of resolving it something we should have avoided. When I talk to IT Pros, they are baffeled. I think we need a good PR story and a good clear Road Map. Of course future road maps are really hard when the underlying product is changing as fast as Azure is. But I think we need do a better job of communicating with the cmdlet users.

I also think we need to get better at really opening this up to the community to contribute. As far as specific work - I'd love to help with adding better help text - it's something I can do (i.e. write documentation). But frankly I really don't know enough about the infrastructure to do much - I am an IT Pro, not a dev. Things like GitHub are still a bit of a mystery to me! I am sure there are others like me who should be able to add value here. How can we get more concrete content produced by the community?

**Comment by markcowl** [comment]
@doctordns One big issue we have with help contributions is that the default github diff for xml files is essentially useless, so that it is very, very difficult to review help changes in GitHub PRs. .  We are looking at some options to break up the help and generate the maml xml format, so that help is located with the cmdlet code and it is easier to see what is up to date and what is not.

You should *always* feel free to contribute and please let us know where you see barriers to your doing so.

I think a lot of internal growing pains have unfortunately been reflected in inconsistencies in the cmdlets, we are focused on eliminating these as quicly as we can do so while minimizing additional pain for customers.

I'll do this somewhere else as well, but I'm curious what the top 3-5 pain points are for people using the cmdlets - here are the top five as I see them (there are a couple of others that could make this list):

* Installation issues (mucking with PSModulePath and associated pain)
* Incorrect and inconsistent implementations of Terminating/non-terminating errors and ShouldProcess/ShoundContinue which make scripting more difficult than it should be
* Inconsistent, out of date, or missing help
* Overly complex parameters for common, simple tasks
* inconsistent parameter names and types for common ARM parameters (Tags, ID, resource name, location, etc.)

**Comment by doctordns** [comment]
Thanks for the follow up.
The list of pain points seems accurate. 
1. The Azure modules should, IMHO, be installed into \program files\WindowsPowerShell\modules, and should NOT create yet another entry in $env:PSModulePath. 
2. Help needs a big up date. In preparing for this week's work in India, I discovered many of the cmdlets had poor help. In talking to the Indian audience last week, it's clear that better help would be most useful. With over 1000 cmdlets in ARM/ASM, help text is important.
3. Existing 'documentation' on ARM cmdlets are largely based on the pre-1.0 version of the ARM module(s). Thus they are wrong. I spent several hours looking at ever Google/Bing references to find that ALL of them referenced out of date cmdlets (ie cmdlet examples that will not work with post 1.0 modules). This is going to be a hard task, to be sure, but I'd like to see at least all the MSDN/MS blog entries that refer to the ARM cmdlets updated to reflect the new cmdlets. 
4. The other inconsistencies do matter too - but I can see how changing them may cause more problems. 

This reminds me of the joke about the guy visiting rural Ireland and getting lost. He asks a local the way back to Dublin and is told: "if it were me, I'd not start from here'. Well, we're 'here' - and I think we need a way to a better situation. I'd love to see a road map that addresses all these issues, and one that can be adequately supported by a combination of MS and community effort.

Regarding the comment on help - for folks like me, simply getting to grips with where the MAML lives and how to update is a major task. Sadly, there is no MAML editor - and as someone who has tried creating MAML from scratch - that's simply painful. If there was some way of making this simple, it would open up the opportunity to improve help text. I'd love the chance to chat more about this aspect when I get back from my current trip to India.

**Comment by markcowl** [comment]
on demand run here:  http://azuresdkci.cloudapp.net/job/powershell-demand/

**Comment by markcowl** [comment]
To refresh, we have added milestones for some additional transparency, and you will start seeing some incremental improvements in documentation and the wiki over the next few sprints, and in the pain points listed above.

We are till looking at additional feedback mechanisms, suggestions are welcome.

**Comment by markcowl** [comment]
@kirthik Assignign to you as we implement the new customer communication channels

**Comment by markcowl** [comment]
I believe that, with the YouTube announcements we are doing with each release, this is done now.
