### ISSUE TITLE
[Feature]: Return cluster powerState in Get-AzAksCluster

### ISSUE THREAD

**Issue by sscchh2001** [Azure/azure-powershell#18271]
### Description of the new feature

The command Get-AzAksCluster does not include powerState attribute in the cluster object, only ProvisioningState attribute is included. The ProvisioningState is always "Succeeded" no matter if the cluster is running or stopped, so it is not so useful as the powerState attribute.
The powerState attribute has already been returned in the GET cluster API call, but just not included in the cluster object.
Please expose the powerState attribute in the cluster object, so that customer could take action based on the powerState.

**Comment by dingmeng-xue** [comment]
We will look into this requirement.
