### ISSUE TITLE
[Doc]: Set-AzAksCluster. Description of -NodeImageOnly is not clear.

### ISSUE THREAD

**Issue by RolandlinAKS** [Azure/azure-powershell#18288]
### Description

-NodeImageOnly
Will only upgrade node pool version to align control plane.

This description is not clear enough to customers. -NodeImageOnly means upgrade the node image of agent pools, not the Kubernetes version. In the description, it means the upgrade node pool k8s version to align with control plane k8s version.

**Comment by dingmeng-xue** [comment]
@wyunchi-ms , please check the doc and update it.
