### ISSUE TITLE
[Doc]: Clarify Append/Overwrite in Import-AzApiManagementApi docs

### ISSUE THREAD

**Issue by teggno** [Azure/azure-powershell#18296]
### Description

In https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/import-azapimanagementapi?view=azps-8.0.0
it would be great if it mentioned if the existing API is overwritten (which it is) or the imported endpoints are appended to the existing API.

**Comment by navba-MSFT** [comment]
@teggno Thanks for reaching out to us and sharing this info. We are looking into this issue. We will reach out to you if we need more information.

**Comment by RakeshMohanMSFT** [comment]
@teggno It updated the existing API. I will update the documentation to mention it as a note.

**Comment by teggno** [comment]
@RakeshMohanMSFT That's great!

**Comment by akshay-zz** [comment]
Is there any way to append from Import-AzApiManagementApi rather than update?
