### ISSUE TITLE
[Doc]: New-AzContainerGroup: clarification on how to use `-IdentityUserAssignedIdentity` paramater

### ISSUE THREAD

**Issue by andysbolton** [Azure/azure-powershell#18299]
### Description

Hi, regarding the docs for New-AzContainer group [here](https://docs.microsoft.com/en-us/powershell/module/az.containerinstance/new-azcontainergroup?view=azps-8.0.0), I'm confused on how to use the `-IdentityUserAssignedIdentity` parameter. The parameter description says that it accepts a `HashTable` and
> The list of user identities associated with the container group. The user identity dictionary key references will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}'.

but it's not clear to me what the key, and in particular the value, of the `HashTable` should be. 

This [example ](https://docs.microsoft.com/en-us/powershell/module/az.containerinstance/new-azcontainergroup?view=azps-8.0.0#example-7-create-a-container-group-with-system-assigned-and-user-assigned-identity) seems to use the parameter but it appears to pass in a `string` instead of a `HashTable`. If I try to pass in a `string` I get an error saying to pass in a `HashTable`.

**Comment by andysbolton** [comment]
After manually adding the user identity and then querying for it in `Get-AzContainerGroup` I can see it is returning a `HashTable` with the resource ID as the key (as documented) and an empty `HashTable` as the value. It may be helpful to update the PowerShell example to use that form:
```
 @{ '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}' = @{} }
```

**Comment by dingmeng-xue** [comment]
@BethanyZhou , could you help check it? Not only doc, we need to consider how to make cmdlet parameter friendly.

**Comment by BethanyZhou** [comment]
- Thank you for reporting @andysbolton. You're right. The correct usage of IdentityUserAssignedIdentity should be `$containerGroup = New-AzContainerGroup -ResourceGroupName test-rg -Name test-cg -Location eastus -Container $container -IdentityType "SystemAssigned, UserAssigned" -IdentityUserAssignedIdentity @{"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}" = @{}} -Debug`. Will correct the example to demonstrate the usage of IdentityUserAssignedIdentity. 

- The reason why the type of IdentityUserAssignedIdentity is a hashtable is that it is defined as object and it has two additional properties in output, see [link](https://github.com/Azure/azure-rest-api-specs/blob/725f4ca360426a32d20e81eb945065e62c285d6a/specification/containerinstance/resource-manager/Microsoft.ContainerInstance/stable/2021-09-01/containerInstance.json#L1400)
```
        "userAssignedIdentities": {
          "type": "object",
          "description": "The list of user identities associated with the container group. The user identity dictionary key references will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}'.",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "principalId": {
                "readOnly": true,
                "type": "string",
                "description": "The principal id of user assigned identity."
              },
              "clientId": {
                "readOnly": true,
                "type": "string",
                "description": "The client id of user assigned identity."
              }
            }
```
- @dingmeng-xue Is it common case to update UserAssignedIdentities? If not, we could design IdentityUserAssignedIdentity as a string, and set it as a hashtable in backend to provide a more friendly format. If yes, even service team does support updating UserAssignedIdentities, I'm hesitate to take this change to avoid breaking piping scenario in future.
