### ISSUE TITLE
Can I update cosmos database account capabilities from azure powershell?

### ISSUE THREAD

**Issue by mayawen** [Azure/azure-powershell#18303]
### Description

I am trying to turn on server-side retry during deployment. I have to do it either from Armtemplate or Powershell. I tried adding the related session "EnableMongo, DisableRateLimitingResponses" during deploy Armtemplate but that does not really update the server-side retry setting. I know AZ CLI works, but that step through errors during deployment. I am wondering if I can do the same thing with azure powershell.

**Comment by navba-MSFT** [comment]
@mayawen Thanks for reaching out to us and sharing this feedback. If you want to use Azure CLI, you can follow the steps mentioned [in this article](https://docs.microsoft.com/bs-latn-ba/azure/cosmos-db/mongodb/prevent-rate-limiting-errors#use-the-azure-cli).

**Using Powershell:**
I was able to Enable / Disable the SSR feature in Azure CosmosDB API MangoDB account using the below Powershell command:

```
$auth=Get-AzAccessToken   # This command will get the bearer token which will be sent in the Auth header
$authHeader= $auth.token 

# Disable SSR feature
$output= Invoke-WebRequest -UseBasicParsing https://management.azure.com/subscriptions/1234567891011121314/resourceGroups/MyRGName/providers/Microsoft.DocumentDb/databaseAccounts/Name-mongodb/?api-version=2022-02-15-preview -ContentType "application/json" -Method PATCH -Headers @{"Authorization"="Bearer $authHeader"} -Body "{'properties':{'capabilities':[{'name':'EnableMongo'}]}}"

# Enable SSR feature
$output= Invoke-WebRequest -UseBasicParsing https://management.azure.com/subscriptions/1234567891011121314/resourceGroups/MyRGName/providers/Microsoft.DocumentDb/databaseAccounts/Name-mongodb/?api-version=2022-02-15-preview -ContentType "application/json" -Method PATCH -Headers @{"Authorization"="Bearer $authHeader"} -Body "{'properties':{'capabilities':[{'name':'DisableRateLimitingResponses'},{'name':'EnableMongo'}]}}"
```

Hope this helps. Please test this and let me know.

**Comment by mayawen** [comment]
Thank you for the reply! I am not sure how to get the value for the parameter -UseBasicParsing. I have the resource group name and the database account name.

**Comment by navba-MSFT** [comment]
@mayawen Thanks for getting back. The error message is reporting about the `api-version=2022-02-15-preview`. Did you miss that from the url ?

To keep it simple, I am sharing the below hope it helps:

- Replace XXXXXXXXX with your SubscriptionID
- Replace YYYYYYYYY with your ResourceGroup Name
- Replace ZZZZZZZZZ with your CosmosDB Account resource Name.
- **Retain all the other values in the request URL as it is.**


>  Below commands helps to Enable SSR feature.
>
>$output= Invoke-WebRequest -UseBasicParsing https://management.azure.com/subscriptions/XXXXXXXXXX/resourceGroups/YYYYYYYYY/providers/Microsoft.DocumentDb/databaseAccounts/ZZZZZZZZZ/?api-version=2022-02-15-preview -ContentType "application/json" -Method PATCH -Headers @{"Authorization"="Bearer $authHeader"} -Body "{'properties':{'capabilities':[{'name':'DisableRateLimitingResponses'},{'name':'EnableMongo'}]}}"

Hope this helps.

**Comment by mayawen** [comment]
I had a new line in the command and that's why it didn't work.
It works now! Thank you!

**Comment by navba-MSFT** [comment]
@mayawen  Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
