### ISSUE TITLE
Set-AzResource : {"Code":"BadRequest","Message":"siteConfig.ReservedInstanceCount is invalid.

### ISSUE THREAD

**Issue by Sumanapandranki7** [Azure/azure-powershell#18316]
### Description

Hello, 

I am trying to bind the function certificate using powershell commands. The same was working fine till last week.
However it's throwing error now. I thought it might be an issue with function So I tried with another one but still same error.
Could you help in investigating what went wrong?

$app=Get-AzResource -ResourceId "**removed**"
$websiteDomainURL = "**removed**"
$hostNameSSLState = $app.Properties.hostNameSslStates | Where-Object -FilterScript { $_.name -eq $websiteDomainURL}
$hostNameSSLState.sslState='SniEnabled'
$hostNameSSLState.thumbprint= '**removed**'
$hostNameSSLState.toUpdate = $true
$app|Set-AzResource -Force

**Error:**
Set-AzResource : {"Code":"BadRequest","Message":"siteConfig.ReservedInstanceCount is invalid.  Please use the new property
siteConfig.PreWarmedInstanceCount.","Target":null,"Details":[{"Message":"siteConfig.ReservedInstanceCount is invalid.  Please use the new property
siteConfig.PreWarmedInstanceCount."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51021","MessageTemplate":"{0} is invalid.
{1}","Parameters":["siteConfig.ReservedInstanceCount","Please use the new property siteConfig.PreWarmedInstanceCount."],"Code":"BadRequest","Message":"siteConfig.ReservedInstanceCount is
invalid.  Please use the new property siteConfig.PreWarmedInstanceCount."}}],"Innererror":null}
CorrelationId: a9a8176a-6da5-4521-a131-ad8952ba80a8
At line:1 char:8
+ $app | Set-AzResource -Force
+        ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet

### Issue script & Debug output

```PowerShell
$app=Get-AzResource -ResourceId "**removed**"
$websiteDomainURL = "**removed**"
$hostNameSSLState = $app.Properties.hostNameSslStates | Where-Object -FilterScript { $_.name -eq $websiteDomainURL}
$hostNameSSLState.sslState='SniEnabled'
$hostNameSSLState.thumbprint= '**removed**'
$hostNameSSLState.toUpdate = $true
$app|Set-AzResource -Force
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.8.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}
Script     6.0.0      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment...}
```

### Error output

```PowerShell
{"Code":"BadRequest","Message":"siteConfig.ReservedInstanceCount is invalid.  Please use the new property
                 siteConfig.PreWarmedInstanceCount.","Target":null,"Details":[{"Message":"siteConfig.ReservedInstanceCount is invalid.  Please use the new property
                 siteConfig.PreWarmedInstanceCount."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51021","MessageTemplate":"{0} is invalid.
                 {1}","Parameters":["siteConfig.ReservedInstanceCount","Please use the new property
                 siteConfig.PreWarmedInstanceCount."],"Code":"BadRequest","Message":"siteConfig.ReservedInstanceCount is invalid.  Please use the new property
                 siteConfig.PreWarmedInstanceCount."}}],"Innererror":null}
                 CorrelationId: cd2acceb-0399-4799-96a8-1cd951e5e176
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.ErrorResponses.ErrorResponseMessageException
InvocationInfo : {Set-AzResource}
Line           : $app|Set-AzResource -Force
Position       : At line:1 char:6
                 + $app|Set-AzResource -Force
                 +      ~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 51
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Set-AzResource is a generic cmdlet across all resources. The error message normally comes from each resource provider and resource type. Could you share the response from service? You can get it after setting `$DebugPreference = "Continue"`

**Comment by Sumanapandranki7** [comment]
Hi @dingmeng-xue 
It's working now. However I didn't make any changes.
Thanks for the response.
