### ISSUE TITLE
[Feature]: Add dockerfile to generation branch

### ISSUE THREAD

**Issue by dicolanl** [Azure/azure-powershell#18317]
### Description of the new feature

Add the autorest for powershell docker file [here](https://github.com/Azure/autorest.powershell/blob/main/tools/docker/Dockerfile) in the generation branch under /src directory.

This will allow developers to open the docker file in VS Code and build and test via docker on any machine.

**Comment by dingmeng-xue** [comment]
@dicolanl , thanks for recommendation. Is it sufficient that we add docker file into azure-powershell repo? or do you mean we should publish docker file to MCR?

**Comment by dicolanl** [comment]
According this you could use a container registry. 
it was easy to put the docker file there and tell vs code to open in container using the dockerfile.
