### ISSUE TITLE
[Doc]: Examples New-AzRecoveryServicesAsrProtectionContainerMapping and Get-AzRecoveryServicesAsrReplicationProtectedItem are horrible

### ISSUE THREAD

**Issue by mrdenny** [Azure/azure-powershell#18319]
### Description

Both examples use the variable $PrimaryContainer, but don't tell you how that variable is being set.

**Comment by RakeshMohanMSFT** [comment]
@mrdenny Thank you for reaching out, we are looking into it.

**Comment by navba-MSFT** [comment]
@mrdenny Apologies for the late reply. Thanks for reporting this issue and sharing the feedback. We will create a PR by end of day today to improvise this documentation.

**Comment by navba-MSFT** [comment]
@mrdenny The above PR has been created to address this ask and it is currently under review. In the meantime, if you have any questions please feel free to ask.

**Comment by navba-MSFT** [comment]
The above PR has been merged now. Closing this thread for now.
