### ISSUE TITLE
[Doc]: Import-AzKeyVaultCertificate parameter is unclear

### ISSUE THREAD

**Issue by desireewilliams** [Azure/azure-powershell#18329]
### Description

https://docs.microsoft.com/en-us/powershell/module/az.keyvault/import-azkeyvaultcertificate?view=azps-8.0.0

The parameter 'CertificateString' does not indicate what value it is looking for, or what format it is in. If you don't already know what would be considered the 'Certificate String', the document doesn't indicate how to find or generate it. 

Is it the SecretValue of an existing cert? Is it a Base64Encoded string?

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will provide more information.

**Comment by BethanyZhou** [comment]
Sorry for confusing. The accurate description for CertificateString is Base64 encoded representation of the certificate object to import. This certificate needs to contain the private key. Docs will be updated in next release.
