### ISSUE TITLE
[Doc]:  Register-AzAutomationScheduledRunbook

### ISSUE THREAD

**Issue by TorstenStrauss** [Azure/azure-powershell#18346]
### Description

Hi MS Team,

Example1 seems to be wrong
`Register-AzAutomationScheduledRunbook -AutomationAccountName "Contoso17" -Name "Runbk01" -ScheduleName "Sched01" -ResourceGroupName "ResourceGroup01"`
I guess it should be RunbookName instead of Name
`Register-AzAutomationScheduledRunbook -AutomationAccountName "Contoso17" -RunbookName "Runbk01" -ScheduleName "Sched01" -ResourceGroupName "ResourceGroup01"`

**Comment by dingmeng-xue** [comment]
@CaptainFanZzz , could you help to check it?

**Comment by SatishBoddu-MSFT** [comment]
@TorstenStrauss 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by CaptainFanZzz** [comment]
‘Name’ is the alias of ‘RunbookName’ when using register or unregister command. Fixing with #18415

**Comment by SatishBoddu-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
