### ISSUE TITLE
Request: Make AzureRM modules workflow-friendly

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1835]
@ravbhatnagar @devigned @markcowl @jodoglevy 
# Request

Please make it a requirement for all AzureRM commands to be implemented as native activities, or otherwise Workflow-friendly, for the Windows Workflow Foundation (WWF) engine that PowerShell Workflow is based upon. The Microsoft Azure Automation service heavily depends on PowerShell Workflow, especially the relatively new Graphical Runbooks (correct me if I'm wrong). There are clear benefits of supporting native activities, including state persistence inside workflows (checkpoints), pause / resume, remoting, and so on. Unfortunately, PowerShell Workflow has suffered from a general lack of support, and the ASM and AzureRM experiences are no exception to the rule.
# Limitations

Current limitations prevent deserialized objects from being passed into ARM PowerShell commands, when they're used inside PowerShell Workflow. One of the more common scenarios I come across regularly, is that storage context objects are serialized, and then deserialized, but the deserialized object cannot be used to authenticate from the Azure Storage commands.
# Work-around

The current "work-around" is to essentially embed the entire PowerShell script inside an `InlineScript` activity, which defeats the whole purpose of using the PowerShell Workflow engine in the first place. The Microsoft Azure Automation service could be even more compelling than it already is, if proper workflow support were implemented by the AzureRM modules.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 Making these common classes serializable is definitely on the radar - beyond Profile and StorageContext, are there any others causing particular pain?

**Comment by singhkay** [comment]
@markcowl Get-AzureRmVm also fails in the workflow. Would your fixes flow to this cmdlet or is there work needed on our side? 

cc: @hyonholee @huangpf

**Comment by alexandair** [comment]
@singhkay What do you mean by "Get-AzureRmVM fails in the workflow". It works for me and returns expected result.

**Comment by singhkay** [comment]
@alexandair This code returned no output when I was trying it out in a workflow

```
$vmSize = $vm.HardwareProfile.vmSize
       
Write-Output $vmSize
```

**Comment by alexandair** [comment]
@singhkay I got it. I think the only way now is to convert a value from JSON to a PSCustomObject.:

```powershell
($vm.HardwareProfileText | ConvertFrom-Json).vmSize
```

**Comment by pcgeek86** [comment]
@markcowl Thanks Mark! At the moment, I don't have others to report. :) 

Cheers,
Trevor Sullivan

**Comment by markcowl** [comment]
@singhkay This ssmes like a generic output issue and not workflow-specific.  Will you guys be addressing this?

**Comment by singhkay** [comment]
@markcowl If it's not workflow specific, then sure but it does work for me outside of the workflow. @huangpf @hyonholee Can you take a look at where the ownership for this fix lies? 

>No output from
```
$vmSize = $vm.HardwareProfile.vmSize
Write-Output $vmSize
```
>inside a workflow

**Comment by pcgeek86** [comment]
To be clear, the original intent of this issue is related to Azure PowerShell cmdlets not accepting deserialized objects as input, per the examples discussed:

1. A deserialized Storage Context 
2. A deserialized Azure Profile / Context / whatever it's called :smiley: 

The issue Kay raised may be related to the workflow "friendliness" of ARM PowerShell as well.

Cheers,
Trevor Sullivan

**Comment by markcowl** [comment]
### Root Cause
AzureProfile, AzureContext, AzureAccount, AzureSubscription, and AzureStorageContext cannot be deserialized using PowerShell default serialization.  Update properties to use types that are easily PowerShell serializable (remove reliance on dictionaries for hashtables, remove private properties necessary for serialization)

### Proposed Solution
Update the data contract for the profile and storage types to be serializable
Add serialization tests

### Cost (Work Units): 8

**Comment by MattAllison** [comment]
I know this can has been kicked down the road for about a year and a number of other items have been tied to it.

The Azure profile persistence and access part is becoming a notable problem for us as we continue our transition to ARM.  Because simple activities like Start/Stop-AzureRMVM are very slow serial operations, we end up having to create fairly cumbersome wrappers to simply stop VMs in parallel.

Any chance of this hitting the latest targeted dates for at least a subset of functionality?

**Comment by six0h** [comment]
Get-AzureRmVirtualNetwork also seems to be affected by this issue.

**Comment by michaeljcameron** [comment]
Now that ASR for Azure to Azure is in preview I suspect this issue may come up again.  I am trying to perform a wide range of post failover tasks and these would be ideal in parallel.  Unfortunately I see the same issue as siz0h with Get-AzureRmNetworkSecurityGroup, Set-AzureRmNetworkInterface, Get-AzureRmPublicIpAddress, Remove-AzureRmVm.  These are all in an inline script within a foreach.  When run without the -parallel option all is good, run in pararllel the errors occur.
I added a random sleep at the start of the inline script, this reduces and in some cases eliminates the errors but is unpredictable.
If you consider DR scenarios that require additional configuration (encrypted disks, load balancers, NSGs etc...) I can only see the requirement for parallel tasks increasing.  In my small environment it takes under 5 minutes to failover but many times that if reconfiguration has to be done sequentially for each VM.
I'm going to put a retry loop around the failing calls and see how that goes but as others have said, this is a slow and cumbersome approach.

**Comment by michaeljcameron** [comment]
Further to my last post I've abandoned using workflows within azure automation to parallelise tasks, I've started using a regular script with calls to Start-AzureRmAutomationRunbook instead.  This does mean I need to create a further check process to monitor the background jobs and harvest their output for logging to the parent process but at least it actually works.

Really disappointed with powershell workflows within automation

**Comment by abatishchev** [comment]
Our Azure Data Factory deployment takes 10 minutes because the script deploys each dataset (of 150) sequentially while it would take just 2 minutes if we could deployment them in parallel.

**Comment by michaeljcameron** [comment]
I'd suggest using a parent script (not workflow) and use calls to start independent jobs.  Still testing but it looks far more reliable that way

**Comment by abatishchev** [comment]
Can you please post some samples once you're done with the testing?

**Comment by michaeljcameron** [comment]
In reply to abatishchev, this is a code snippet you could work on.  It really isn't overly complicated, one loop to make the calls and store job Ids in a hash, another to loop through the hash checking the Job Ids 



```
$sleepTime =5
$resourceGroupName = 'rg1'
$vmNames = 'vm1', 'vm2', 'vm3'
$automationAccount = "myAutomationAccount"
$automationRG = "myAutomationAccountRG"
$childScript = "myChildScript"


$jobs = @{}
foreach ($vmName in $vmNames)
{
	$params = @{"vmName"=$vmName; "resourceGroupName"=$resourceGroupName}
	Write-Output ($vmName, ": Launching job") 
	$jobId = ((Start-AzureRmAutomationRunbook -AutomationAccountName $automationAccount -Name $childScript -ResourceGroupName $automationRG -Parameters $params).JobId)
	Write-Output ($vmName, ": Job ID: ", $jobId) 
	$jobs.$vmName = $jobId
	sleep $sleepTime
}

$complete = 0
while ($complete -lt $jobs.Count)
{
    foreach ($vmName in $($jobs.Keys)) 
    {
        $jobId = $jobs.$vmName
        if ($jobId -eq $null) {continue}
        if ((Get-AzureRmAutomationJob -Id $jobId -AutomationAccountName $automationAccount -ResourceGroupName $automationRG).EndTime -ne $null)
        {
            $jobs[$vmName] = $null
            $complete++
            Write-Output (Get-AzureRmAutomationJobOutput -AutomationAccountName $automationAccount -Id $jobId -ResourceGroupName $automationRG -Stream "Output" | Get-AzureRmAutomationJobOutputRecord).Value.Values
        }
    }
    sleep $sleepTime
}
```

**Comment by abatishchev** [comment]
Thanks Michael! I'll use it as a template for my own script.

**Comment by markcowl** [comment]
Fixed for the authentication-related classes.  All AzureRm cmdlets have a -AzureRmContext parameter using types that are serializable, so, now you will be able top use:

```Start-Job {param($ctx) Start-AzureRmVM -AzureRmContext $ctx} -ArgumentList (Get-AzureRmContext)
