### ISSUE TITLE
[Doc]: Documents in Az.Cdn module don't have examples.

### ISSUE THREAD

**Issue by ziyuezh576** [Azure/azure-powershell#18353]
### Description

Documents in Az.Cdn module don't have examples. Cmdlets are:

Clear-AzCdnEndpointContent
Clear-AzFrontDoorCdnEndpointContent
Disable-AzCdnCustomDomainCustomHttps
Enable-AzCdnCustomDomainCustomHttps
Get-AzCdnCustomDomain
Get-AzCdnEdgeNode
Get-AzCdnEndpoint
Get-AzCdnEndpointResourceUsage
Get-AzCdnOrigin
Get-AzCdnOriginGroup
Get-AzCdnProfile
Get-AzCdnProfileResourceUsage
Get-AzCdnProfileSupportedOptimizationType
Get-AzCdnSubscriptionResourceUsage
Get-AzFrontDoorCdnCustomDomain
Get-AzFrontDoorCdnEndpoint
Get-AzFrontDoorCdnEndpointResourceUsage
Get-AzFrontDoorCdnOrigin
Get-AzFrontDoorCdnOriginGroup
Get-AzFrontDoorCdnOriginGroupResourceUsage
Get-AzFrontDoorCdnProfile
Get-AzFrontDoorCdnProfileResourceUsage
Get-AzFrontDoorCdnRoute
Get-AzFrontDoorCdnRule
Get-AzFrontDoorCdnRuleSet
Get-AzFrontDoorCdnRuleSetResourceUsage
Get-AzFrontDoorCdnSecret
Get-AzFrontDoorCdnSecurityPolicy
Import-AzCdnEndpointContent
New-AzCdnCustomDomain
New-AzCdnDeliveryRuleCookiesConditionObject
New-AzCdnDeliveryRuleHttpVersionConditionObject
New-AzCdnDeliveryRuleIsDeviceConditionObject
New-AzCdnDeliveryRuleObject
New-AzCdnDeliveryRulePostArgsConditionObject
New-AzCdnDeliveryRuleQueryStringConditionObject
New-AzCdnDeliveryRuleRemoteAddressConditionObject
New-AzCdnDeliveryRuleRequestBodyConditionObject
New-AzCdnDeliveryRuleRequestHeaderActionObject
New-AzCdnDeliveryRuleRequestHeaderConditionObject
New-AzCdnDeliveryRuleRequestMethodConditionObject
New-AzCdnDeliveryRuleRequestSchemeConditionObject
New-AzCdnDeliveryRuleRequestUriConditionObject
New-AzCdnDeliveryRuleResponseHeaderActionObject
New-AzCdnDeliveryRuleUrlFileExtensionConditionObject
New-AzCdnDeliveryRuleUrlFileNameConditionObject
New-AzCdnDeliveryRuleUrlPathConditionObject
New-AzCdnEndpoint
New-AzCdnHealthProbeParametersObject
New-AzCdnManagedHttpsParametersObject
New-AzCdnOrigin
New-AzCdnOriginGroup
New-AzCdnProfile
New-AzCdnResourceReferenceObject
New-AzCdnResponseBasedOriginErrorDetectionParametersObject
New-AzCdnUrlRedirectActionObject
New-AzCdnUrlRewriteActionObject
New-AzCdnUrlSigningActionObject
New-AzCdnUserManagedHttpsParametersObject
New-AzFrontDoorCdnCustomDomain
New-AzFrontDoorCdnCustomDomainTlsSettingParametersObject
New-AzFrontDoorCdnEndpoint
New-AzFrontDoorCdnOrigin
New-AzFrontDoorCdnOriginGroup
New-AzFrontDoorCdnOriginGroupHealthProbeSettingObject
New-AzFrontDoorCdnOriginGroupLoadBalancingSettingObject
New-AzFrontDoorCdnProfile
New-AzFrontDoorCdnResourceReferenceObject
New-AzFrontDoorCdnRoute
New-AzFrontDoorCdnRule
New-AzFrontDoorCdnRuleClientPortConditionObject
New-AzFrontDoorCdnRuleCookiesConditionObject
New-AzFrontDoorCdnRuleHostNameConditionObject
New-AzFrontDoorCdnRuleHttpVersionConditionObject
New-AzFrontDoorCdnRuleIsDeviceConditionObject
New-AzFrontDoorCdnRulePostArgsConditionObject
New-AzFrontDoorCdnRuleQueryStringConditionObject
New-AzFrontDoorCdnRuleRemoteAddressConditionObject
New-AzFrontDoorCdnRuleRequestBodyConditionObject
New-AzFrontDoorCdnRuleRequestHeaderActionObject
New-AzFrontDoorCdnRuleRequestHeaderConditionObject
New-AzFrontDoorCdnRuleRequestMethodConditionObject
New-AzFrontDoorCdnRuleRequestSchemeConditionObject
New-AzFrontDoorCdnRuleRequestUriConditionObject
New-AzFrontDoorCdnRuleResponseHeaderActionObject
New-AzFrontDoorCdnRuleRouteConfigurationOverrideActionObject
New-AzFrontDoorCdnRuleServerPortConditionObject
New-AzFrontDoorCdnRuleSet
New-AzFrontDoorCdnRuleSocketAddrConditionObject
New-AzFrontDoorCdnRuleSslProtocolConditionObject
New-AzFrontDoorCdnRuleUrlFileExtensionConditionObject
New-AzFrontDoorCdnRuleUrlFileNameConditionObject
New-AzFrontDoorCdnRuleUrlPathConditionObject
New-AzFrontDoorCdnRuleUrlRedirectActionObject
New-AzFrontDoorCdnRuleUrlRewriteActionObject
New-AzFrontDoorCdnRuleUrlSigningActionObject
New-AzFrontDoorCdnSecret
New-AzFrontDoorCdnSecretCustomerCertificateParametersObject
New-AzFrontDoorCdnSecretFirstPartyManagedCertificateParametersObject
New-AzFrontDoorCdnSecretManagedCertificateParametersObject
New-AzFrontDoorCdnSecretUrlSigningKeyParametersObject
New-AzFrontDoorCdnSecurityPolicy
New-AzFrontDoorCdnSecurityPolicyWebApplicationFirewallAssociationObject
New-AzFrontDoorCdnSecurityPolicyWebApplicationFirewallParametersObject
Remove-AzCdnCustomDomain
Remove-AzCdnEndpoint
Remove-AzCdnOrigin
Remove-AzCdnOriginGroup
Remove-AzCdnProfile
Remove-AzFrontDoorCdnCustomDomain
Remove-AzFrontDoorCdnEndpoint
Remove-AzFrontDoorCdnOrigin
Remove-AzFrontDoorCdnOriginGroup
Remove-AzFrontDoorCdnProfile
Remove-AzFrontDoorCdnRoute
Remove-AzFrontDoorCdnRule
Remove-AzFrontDoorCdnRuleSet
Remove-AzFrontDoorCdnSecret
Remove-AzFrontDoorCdnSecurityPolicy
Start-AzCdnEndpoint
Stop-AzCdnEndpoint
Test-AzCdnEndpointCustomDomain
Test-AzCdnNameAvailability
Test-AzCdnProbe
Test-AzFrontDoorCdnEndpointCustomDomain
Test-AzFrontDoorCdnEndpointNameAvailability
Test-AzFrontDoorCdnProfileHostNameAvailability
Update-AzCdnEndpoint
Update-AzCdnOrigin
Update-AzCdnOriginGroup
Update-AzCdnProfile
Update-AzFrontDoorCdnCustomDomain
Update-AzFrontDoorCdnCustomDomainValidationToken
Update-AzFrontDoorCdnEndpoint
Update-AzFrontDoorCdnOrigin
Update-AzFrontDoorCdnOriginGroup
Update-AzFrontDoorCdnProfile
Update-AzFrontDoorCdnRoute
Update-AzFrontDoorCdnRule
Update-AzFrontDoorCdnSecurityPolicy

**Comment by RakeshMohanMSFT** [comment]
@ziyuezh576 Thank you for reaching out, we are looking into it.

**Comment by t-bzhan** [comment]
Examples added now
