### ISSUE TITLE
Get-AzNetworkInterface sometimes returning empty

### ISSUE THREAD

**Issue by litian1992** [Azure/azure-powershell#18375]
### Description

On some resource groups, using Get-AzNetworkInterface returns nothing with just '-ResourceGroupName <resource_group>'. It works okay with '-Name <nic_name>' additionally. Reproducibility is not 100%. But it exists on 6.4.0 and 8.0.0.

### Issue script & Debug output

```PowerShell
PS> Get-AzNetworkInterface -ResourceGroupName <resource_group>
PS>
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.5.3      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect...
Script     4.17.0     Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendCo...
Script     4.11.0     Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApp...
Script     4.3.1      Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTempla...
```

**Comment by PramodValavala-MSFT** [comment]
@litian1992 Considering the cmdlet simply calls the corresponding ARM REST API, it is likely this was an intermittent issue at the time. This could at times just be temporary since ARM data is being synced internally when the resource is just created.

If this is a consistent issue, it would be best to create a support ticket to troubleshoot from the backend. Closing since no change in the cmdlet required.
