### ISSUE TITLE
Get-AzureRmSubscription does not respect -ErrorAction SilentlyContinue

### ISSUE THREAD

**Issue by sdecker** [Azure/azure-powershell#1843]
I should be able to use
if(Get-AzureRmSubscription  -SubscriptionId $SubscriptionId -ErrorAction Silently) { ... } else { ... }

But I have to do 
try {
    if(Get-AzureRmSubscription  -SubscriptionId $SubScriptionId) {}
} catch { ...}

because it does not respect -ErrorAction.

**Comment by markcowl** [comment]
@sdecker What is the error in this case?  If the error is that you haven't logged, in this is correct behavior, as this is a terminating error - no further processing is possible.  If there is some error with a particular subscription or tenant, then you are correct, it is a non-terminating error, which the ErrorActionPreference should control.

**Comment by sdecker** [comment]
Yes, the error is that the user isn't logged in. It is not correct behavior that any cmdlet should throw a terminating error if I set -ErrorAction to silently continue. I know the user may not be logged in that is the whole point of me checking. Some AD cmdlets do this on Get-* as well and it is infuriating that MS thinks this is acceptable. The logic I want to implement is to have a script that is rerunnable. I need a way to check if the user is logged in and if they are skip calling Azure-AzureRmAccount again. I shouldn't have to try/catch to do this. This is the whole point of -ErrorAction so I can control when an error is terminating without having to do a try/catch.

**Comment by markcowl** [comment]
@sdecker I understand why you are saying this, especially since the subscriptions used to be stored on the box. However Get-AzureRmSubscription is making a call off the box now, further execution is undefined if you are not logged in, meaning the pipeline should be shut down, meaning terminating error. 

You *should* however, be able to check for login using Get-AzureRmContext
