### ISSUE TITLE
Tags for Restore-AzSqlDatabase not working with the cross subscription restore

### ISSUE THREAD

**Issue by jayendranarumugam** [Azure/azure-powershell#18435]
### Description

We are trying to follow [this tutorial](https://techcommunity.microsoft.com/t5/azure-synapse-analytics-blog/announcing-general-availability-of-cross-subscription-restore/ba-p/3280185) trying to do the cross subscription 

```
[hashtable]$tags = @{"region" = "eastus2"}


$SourceResourceGroupName = "xxttt"
$SourceSynapseWorkspaceName = "xxyy"
$SourceSqlPoolName = "sxxyy"

$RestorePointLabel = "abc"

$TargetResourceGroupName ="abc"
$TargetServerName = "abc"
$TargetDatabaseName = "ac"



$Sourcesqlpool = Get-AzSynapseSqlPool -ResourceGroupName $SourceResourceGroupName -WorkspaceName $SourceSynapseWorkspaceName -Name $SourceSqlPoolName

Write-Output $Sourcesqlpool


$restorePoint = $Sourcesqlpool | Get-AzSynapseSqlPoolRestorePoint | Where-Object {$_.RestorePointLabel -eq $RestorePointLabel}

Write-Output $restorePoint

$DestinationSubscriptionId = "abc"
Set-AzContext -SubscriptionId $DestinationSubscriptionId

$PointInTime = $RestorePoint.RestorePointCreationDate 

Write-Output $PointInTime



$RestoredDatabase = Restore-AzSqlDatabase -FromPointInTimeBackup -PointInTime $PointInTime `
    -ResourceGroupName $TargetResourceGroupName -Tag $tags `
    -ServerName $TargetServerName -TargetDatabaseName $TargetDatabaseName `
    -ResourceId $Sourcesqlpool.Id -Edition "DataWarehouse" `
    -ServiceObjectiveName "DW100c"
```

This script was finally failing on `Restore-AzSqlDatabase` where the tags is not getting applied to the new sqldb

### Issue script & Debug output

```PowerShell
Resource 'synapsedb' was disallowed by policy. Policy identifiers:
| '[{"policyAssignment":{"name":"Mandate and Audit Tags on Supported Resources}
```

### Environment data

```PowerShell
Name Value
---- -----
PSVersion 7.2.1
PSEdition Core
GitCommitId 7.2.1
OS Microsoft Windows 10.0.19044
Platform Win32NT
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
WSManStackVersion 3.0
```

### Module versions

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/c1Yqk.png

### Error output

```PowerShell
Resource 'synapsedb' was disallowed by policy. Policy identifiers:
| '[{"policyAssignment":{"name":"Mandate and Audit Tags on Supported Resources}
```

**Comment by jayendranarumugam** [comment]
ref https://github.com/Azure/azure-powershell/pull/17474

**Comment by dingmeng-xue** [comment]
@jayendranarumugam , it seems the message comes from policy setting. Please do below 2 steps and provide more information.
2. Enable debug log via `$DebugPreference = "Continue"`
3. Call `Restore-AzSqlDatabase` again and check the log.

You can see the request and response on PowerShell console. Please share the information to us.

**Comment by jayendranarumugam** [comment]
Here you go @dingmeng-xue . If you see the PUT Request is missing to pass the `Tag` property from the powershell command  

```
HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/xxxx/resourceGroups/rg/providers/Microsoft.Sql/servers/xxxx/databases/itsynapsedb?api-version=2021-05-01-preview

Headers:
x-ms-client-request-id        : 4e0d3dc1-1f9a-488f-91e3-3edcb7145b9c
Accept-Language               : en-US

Body:
{
  "sku": {
    "name": "DW100c",
    "tier": "DataWarehouse"
  },
  "properties": {
    "createMode": "PointInTimeRestore",
    "restorePointInTime": "2022-06-08T18:08:16Z",
    "sourceResourceId": "/subscriptions/xxxcx/providers/Microsoft.Synapse/workspaces/synapsews01/sqlPools/synapsedb"
  },
  "location": "eastus2"
}
```

**Comment by jayendranarumugam** [comment]
Hi @dingmeng-xue , Is there any update on the issue ? We are currently unable to move forward with this bug. Is there any workaround for this ?

**Comment by navba-MSFT** [comment]
@jayendranarumugam Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@jayendranarumugam Could you please confirm if you are using [3.10.0 version of the Az.SQL ](https://www.powershellgallery.com/packages/Az.Sql/3.10.0)module ? If not, Could you please upgrade your Az.SQL module to this version and test again ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@jayendranarumugam I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you are facing the same issue after upgrading to [3.10.0 version of the Az.SQL ](https://www.powershellgallery.com/packages/Az.Sql/3.10.0)module. Awaiting your reply.

**Comment by jayendranarumugam** [comment]
Yep will test this today and let you know

**Comment by jayendranarumugam** [comment]
@navba-MSFT I can see this was fixed with https://github.com/Azure/azure-powershell/pull/18475 and working as expected now. Feel free to link/close this issue

**Comment by navba-MSFT** [comment]
@jayendranarumugam Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
