### ISSUE TITLE
[Doc]: New-AzApiManagement

### ISSUE THREAD

**Issue by cwstanton** [Azure/azure-powershell#18439]
### Description

Please revisit the "-sku" parameter item in the [parameters section](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/new-azapimanagement?view=azps-8.0.0#parameters).  The list above to table is missing items and has two items merged into one.  The table has an incorrect value for "default."

**Comment by dingmeng-xue** [comment]
![image](https://user-images.githubusercontent.com/56333063/172746368-5add811f-977d-4aca-82ca-57e6ca01befd.png)

The first part is handcrafted. Owner should fix it.
