### ISSUE TITLE
How to get the list of resouces created in last 30 days in Azure?

### ISSUE THREAD

**Issue by MonikaReddy-MSFT** [Azure/azure-powershell#18457]
### Description
Customer raised an issue in microsoft Q&A regarding below : 
https://docs.microsoft.com/en-us/answers/questions/883440/index.html
How to get the list of resouces created in last 30 days in Azure?

**Comment by dingmeng-xue** [comment]
@MonikaReddy-MSFT , thanks for contacting. For the time being,  the date time of creation is not a common property across resource types. I don't think there is an easy approach to query them.

**Comment by dcaro** [comment]
@MonikaReddy-MSFT the following article has this information:  
https://docs.microsoft.com/en-us/azure/governance/resource-graph/how-to/get-resource-changes?tabs=azure-powershell#all-changes-in-the-past-one-day 

You will need to adjust the time from 1 day to 30 days and eventually apply filters and / or formatting to the output.

**Comment by MonikaReddy-MSFT** [comment]
@dingmeng-xue & @dcaro - Thank you for providing details. I will check with customer and get back to you if I have any questions. Thank you
