### ISSUE TITLE
Publish-AzureWebsiteProject should have option to "clean deploy"

### ISSUE THREAD

**Issue by seanfisher** [Azure/azure-powershell#1848]
We're using the new Release Management platform on Visual Studio Team Services. We're running the Azure Web App Deployment task, which uses the `Publish-AzureWebsiteProject` to actually publish the website. However, we are running into some issues where an old DLL is being left on the web app and publishing doesn't remove it. We are using this as a continuous delivery pipeline, so we can't have a manual step of FTP-ing into the server to erase those files before deploying.

We need a way to tell the Azure Web App Deployment process to make a clean deploy that will delete all of the files at the destination server before redeploying the updated package. Because that task uses `Publish-AzureWebsiteProject`, I've opened an issue here. Once `Publish-AzureWebsiteProject` supports a clean deploy, the Release Management task can be updated to have the option of a clean build.

**Comment by markcowl** [comment]
@naveedaz Can you take a look?

**Comment by shobak101** [comment]
the default behavior is actually as you described @seanfisher I am not sure why this file is not getting deleted. could you please take a look at the logs and tell me if you find any logs about failing to delete this file you should find some helpful logs if you follow these steps [https://github.com/projectkudu/kudu/wiki/Investigating-msdeploy-ARM-failures](url)  if that does not help please tell me to investigate more.

**Comment by seanfisher** [comment]
@shobak101 Thanks for the response. I think we've resolved our issue. That link you posted, by the way, leads to a 404 page.

**Comment by shobak101** [comment]
@seanfisher sorry about that updated the link to the right location, could you please tell me what was wrong? I just want to know in case it popped up somewhere else :)

**Comment by ramomex1** [comment]
Delete the deployment, then create deployment credentials for FTP and there you go with FTP client clean the wwwroot folder by your self.
