### ISSUE TITLE
[Doc]: Invoke-AzSqlDatabaseFailover

### ISSUE THREAD

**Issue by langstonj** [Azure/azure-powershell#18569]
### Description

https://docs.microsoft.com/en-us/powershell/module/az.sql/invoke-azsqldatabasefailover?view=azps-7.5.0

This is not working.  No errors, nothing.  No failover of the designated database occurs.  What am I missing?

Invoke-AzSqlDatabaseFailover -ResourceGroupName abcrsg01 Force -ServerName abcsqlsrv01 -DatabaseName sqldbabc1

**Comment by navba-MSFT** [comment]
@langstonj Thanks for reaching out to us and sharing this feedback. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@langstonj If the database is in an elastic pool, `Invoke-AzSqlDatabaseFailover `command will failover the given database without affecting the other databases in the same elastic pool.

Could you please use the most recent version of [Az.SQL]([Az.Sql](https://docs.microsoft.com/en-us/powershell/module/az.sql/?view=azps-8.0.0)) and try executing the below command ? 

>Invoke-AzSqlDatabaseFailover -ResourceGroupName "ResourceGroup01" -ServerName "Server01" -DatabaseName "Database01"

If you still dont get any response or if there is no effect, try to run `$DebugPreference="Continue"
` command and then run the `Invoke-AzSqlDatabaseFailover `command and share the detailed debug output here in this thread. This will help us to isolate the issue. Awaiting your reply.

**Comment by langstonj** [comment]
PS C:\Users\langstonj> $DebugPreference="Continue"
PS C:\Users\langstonj> Invoke-AzSqlDatabaseFailover -ResourceGroupName pscrsgsql02 -ServerName pscsqlsrv02 -DatabaseName sqldb2021
DEBUG: 11:26:21 AM - InvokeAzureSqlDatabaseFailover begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 11:26:21 AM - using account id ***@***.***'...
DEBUG: [Common.Authentication]: Authenticating using Account: ***@***.***', environment: 'AzureCloud', tenant: '891867d4-a392-48ed-ac16-4bd398b62ec9'
DEBUG: 11:26:21 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'891867d4-a392-48ed-ac16-4bd398b62ec9', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', ***@***.***'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21] Found 1 cache accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21] Returning 1 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] MSAL MSAL.NetCore with assembly version '4.30.1.0'. CorrelationId(e17d5045-a3e3-48fa-9a42-2a79c3ee868c)
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - e17d5045-a3e3-48fa-9a42-2a79c3ee868c

DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] === Token Acquisition (SilentRequest) started:

        Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] Access token has expired or about to expire. [Current time (06/16/2022 16:26:21) - Expiration Time (06/16/2022 14:56:58 +00:00) - Extended Expiration Time (06/16/2022 14:56:58 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] Refresh token found in the cache? - True
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:21 - ] Resolving authority endpoints... Already resolved? - TRUE
DEBUG: Request [e07c78f7-f417-484a-9917-8cc0480ea92d] POST https://login.microsoftonline.com/891867d4-a392-48ed-ac16-4bd398b62ec9/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:REDACTED
x-ms-return-client-request-id:REDACTED
User-Agent:REDACTED
Content-Type:REDACTED
client assembly: Azure.Identity
DEBUG: Response [e07c78f7-f417-484a-9917-8cc0480ea92d] 200 OK (00.3s)
Cache-Control:REDACTED
Pragma:REDACTED
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:REDACTED
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
X-XSS-Protection:REDACTED
Set-Cookie:REDACTED
Date:REDACTED
Content-Type:REDACTED
Expires:REDACTED
Content-Length:REDACTED

DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Checking client info returned from the server..
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Saving Token Response to cache..
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Subject not present in Id token
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Saving AT in cache and removing overlapping ATs...
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Looking for scopes for the authority in the cache which intersect with https://management.core.windows.net//.default
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Intersecting scope entries count - 1
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Matching entries after filtering by user - 1
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Saving Id Token and Account in cache ...
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Saving RT in cache...
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22] Not writing FRT in ADAL legacy cache.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Fetched access token from host login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 06/16/2022 17:31:43 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-06-16T17:31:43.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '891867d4-a392-48ed-ac16-4bd398b62ec9', UserId: ***@***.***'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/c8081155-076d-4c6d-9625-5304a302de26/resourceGroups/pscrsgsql02/providers/Microsoft.Sql/servers/pscsqlsrv02/databases/sqldb2021?api-version=2021-02-01-preview

Headers:
x-ms-client-request-id        : ce8446df-0033-47b1-947d-ade6a848caa3
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : 843f7c56-aed9-440a-9722-1cc4c3cf6dad
Server                        : Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : 51321d6d-5fa1-4ff1-84eb-8f9d5558c6dd
x-ms-routing-request-id       : CENTRALUS:20220616T162621Z:51321d6d-5fa1-4ff1-84eb-8f9d5558c6dd
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Thu, 16 Jun 2022 16:26:20 GMT

Body:
{
  "sku": {
    "name": "ElasticPool",
    "tier": "Standard",
    "capacity": 0
  },
  "kind": "v12.0,user,pool",
  "properties": {
    "collation": "SQL_Latin1_General_CP1_CI_AS",
    "maxSizeBytes": 536870912000,
    "elasticPoolId": "/subscriptions/c8081155-076d-4c6d-9625-5304a302de26/resourceGroups/pscrsgsql02/providers/Microsoft.Sql/servers/pscsqlsrv02/elasticPools/pscpepsql02",
    "status": "Online",
    "databaseId": "ad5ca8b0-1750-4040-b94f-a925db75508d",
    "creationDate": "2017-07-12T16:57:27.677Z",
    "currentServiceObjectiveName": "ElasticPool",
    "requestedServiceObjectiveName": "ElasticPool",
    "defaultSecondaryLocation": "northcentralus",
    "failoverGroupId": "/subscriptions/c8081155-076d-4c6d-9625-5304a302de26/resourceGroups/pscrsgsql02/providers/Microsoft.Sql/servers/pscsqlsrv02/failoverGroups/pscsqlsrv02fg",
    "catalogCollation": "SQL_Latin1_General_CP1_CI_AS",
    "zoneRedundant": false,
    "earliestRestoreDate": "2022-05-12T16:26:21.1321526Z",
    "readScale": "Disabled",
    "currentSku": {
      "name": "ElasticPool",
      "tier": "Standard",
      "capacity": 0
    },
    "currentBackupStorageRedundancy": "Geo",
    "requestedBackupStorageRedundancy": "Geo",
    "maintenanceConfigurationId": "/subscriptions/c8081155-076d-4c6d-9625-5304a302de26/providers/Microsoft.Maintenance/publicMaintenanceConfigurations/SQL_Default",
    "isLedgerOn": false,
    "isInfraEncryptionEnabled": false
  },
  "location": "southcentralus",
  "tags": {},
  "id": "/subscriptions/c8081155-076d-4c6d-9625-5304a302de26/resourceGroups/pscrsgsql02/providers/Microsoft.Sql/servers/pscsqlsrv02/databases/sqldb2021",
  "name": "sqldb2021",
  "type": "Microsoft.Sql/servers/databases"
}


DEBUG: [Common.Authentication]: Authenticating using Account: ***@***.***', environment: 'AzureCloud', tenant: '891867d4-a392-48ed-ac16-4bd398b62ec9'
DEBUG: 11:26:22 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'891867d4-a392-48ed-ac16-4bd398b62ec9', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', ***@***.***'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22] Found 1 cache accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22] Returning 1 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] MSAL MSAL.NetCore with assembly version '4.30.1.0'. CorrelationId(c9bafe37-3745-4600-a536-0f9321732486)
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - c9bafe37-3745-4600-a536-0f9321732486

DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] === Token Acquisition (SilentRequest) started:

        Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Access token is not expired. Returning the found cache entry. [Current time (06/16/2022 16:26:22) - Expiration Time (06/16/2022 17:31:43 +00:00) - Extended Expiration Time (06/16/2022 17:31:43 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Returning access token found in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] Fetched access token from host login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [06/16/2022 16:26:22 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 06/16/2022 17:31:43 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-06-16T17:31:43.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '891867d4-a392-48ed-ac16-4bd398b62ec9', UserId: ***@***.***'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/c8081155-076d-4c6d-9625-5304a302de26/resourceGroups/pscrsgsql02/providers/Microsoft.Sql/servers/pscsqlsrv02/databases/sqldb2021/failover?replicaType=Primary&api-version=2021-02-01-preview

Headers:
x-ms-client-request-id        : ce8446df-0033-47b1-947d-ade6a848caa3
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Accepted

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Location                      : https://management.azure.com/subscriptions/c8081155-076d-4c6d-9625-5304a302de26/resourceGroups/pscrsgsql02/providers/Microsoft.Sql/locations/southcentralus/databaseOperationResults/b161cff8-8181-4149-b567-a86c07d6d4b7?api-version=2021-02-01-preview
Retry-After                   : 15
Azure-AsyncOperation          : https://management.azure.com/subscriptions/c8081155-076d-4c6d-9625-5304a302de26/resourceGroups/pscrsgsql02/providers/Microsoft.Sql/locations/southcentralus/databaseAzureAsyncOperation/b161cff8-8181-4149-b567-a86c07d6d4b7?api-version=2021-02-01-preview
x-ms-request-id               : 907f3536-c8d3-4935-bd19-efa6a590f835
Server                        : Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 515870b4-85e4-485a-96b4-2b8515ec4b8c
x-ms-routing-request-id       : CENTRALUS:20220616T162621Z:515870b4-85e4-485a-96b4-2b8515ec4b8c
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Thu, 16 Jun 2022 16:26:21 GMT

Body:
{
  "operation": "FailoverDatabaseOrElasticPoolAsync",
  "startTime": "2022-06-16T16:26:21.513Z"
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/c8081155-076d-4c6d-9625-5304a302de26/resourceGroups/pscrsgsql02/providers/Microsoft.Sql/locations/southcentralus/databaseAzureAsyncOperation/b161cff8-8181-4149-b567-a86c07d6d4b7?api-version=2021-02-01-preview

Headers:
x-ms-client-request-id        : ce8446df-0033-47b1-947d-ade6a848caa3

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Retry-After                   : 15
x-ms-request-id               : 11e72bf1-dc98-4976-ad8e-84a9e3081b4b
Server                        : Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : c711cbb4-5d2d-4277-9224-07233921dac6
x-ms-routing-request-id       : CENTRALUS:20220616T162636Z:c711cbb4-5d2d-4277-9224-07233921dac6
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Thu, 16 Jun 2022 16:26:36 GMT

Body:
{
  "name": "b161cff8-8181-4149-b567-a86c07d6d4b7",
  "status": "Succeeded",
  "startTime": "2022-06-16T16:26:21.637Z"
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/c8081155-076d-4c6d-9625-5304a302de26/resourceGroups/pscrsgsql02/providers/Microsoft.Sql/locations/southcentralus/databaseOperationResults/b161cff8-8181-4149-b567-a86c07d6d4b7?api-version=2021-02-01-preview

Headers:
x-ms-client-request-id        : ce8446df-0033-47b1-947d-ade6a848caa3

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : c82330c8-a8c8-43e6-aa57-ca0b152afcaa
Server                        : Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-correlation-request-id   : b18db7ac-ff20-448a-878e-934dba541cce
x-ms-routing-request-id       : CENTRALUS:20220616T162636Z:b18db7ac-ff20-448a-878e-934dba541cce
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Thu, 16 Jun 2022 16:26:36 GMT

Body:



DEBUG: AzureQoSEvent: Module: Az.Sql:3.6.0; CommandName: Invoke-AzSqlDatabaseFailover; PSVersion: 7.2.4; IsSuccess: True; Duration: 00:00:16.3339241
DEBUG: Finish sending metric.
DEBUG: 11:26:38 AM - InvokeAzureSqlDatabaseFailover end processing.
PS C:\Users\langstonj>

**Comment by navba-MSFT** [comment]
@langstonj Could you please use test the Powershell Script shared in [this article ](https://docs.microsoft.com/en-us/azure/azure-sql/database/auto-failover-group-configure-sql-db?view=azuresql&tabs=azure-powershell&pivots=azure-sql-elastic-pool)and check if that helps ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@langstonj Thanks for your reply. A failover group in Azure SQL Database can include one or multiple databases.

The [Add-AzSqlDatabaseToFailoverGroup](https://docs.microsoft.com/en-us/powershell/module/az.sql/add-azsqldatabasetofailovergroup?view=azps-8.0.0) PS cmdlet Adds **one or more databases** to a failover group. The databases must not be secondary databases in existing replication relationships. The command will start geo-replication of any added databases to the Failover Group's secondary server. 

The[ Switch-AzSqlDatabaseFailoverGroup ](https://docs.microsoft.com/en-us/powershell/module/az.sql/switch-azsqldatabasefailovergroup?view=azps-8.0.0)command swaps the roles of the servers in a Failover Group and switches all secondary databases to the primary role. Hope this helps. Please test this and let me know if you face any issues.

**Comment by langstonj** [comment]
***@***.***
The script  errors out, not finding an existing resource group (red error) and that resource group is present.  The high-lighted variable is never referenced which gives me pause for concern.

***@***.***


Not wishing to be impolite, but this is all getting away from the original point about the command Invoke-AzSqlDatabaseFailover not working as documented.
I ran it a second time (PS 7 in the cloud shell), sent in the debug output for further review, and here we are

It looks to me like that Invoke-AzSqlDatabaseFailover does not work as documented.

**Comment by navba-MSFT** [comment]
@langstonj Apologies for deviating from your reported issue with [Invoke-AzSqlDatabaseFailover] command. As suggested earlier, did you upgrade your Az.SQL command and test ? I see from the debug output that you are using 3.6 version of Az.Sql module.

>Install-Module -Name Az.Sql -RequiredVersion 3.9.0

I am also discussing this with the Product Owners if there are any known issues with this PS command.

**Comment by navba-MSFT** [comment]
@langstonj While you follow my above action plan to update your Az.SQL and test again, I wanted to check if you are trying to failover the Geo replica or just want to failover locally?
Did you check on the activity log in the portal for that SQL resource? You should find an entry like the below as an evidence that the failover occurred.

![image](https://user-images.githubusercontent.com/57353862/175596349-6582a52e-3062-4823-9dae-2338ee9ebcaa.png)

Awaiting your reply.

**Comment by langstonj** [comment]
The attached Word document lists the debug output (showing Module Az.Sql 3.9.0, PSVersion 7.2.4) and several output snippets including one like the one below.  Trying to fail the Geo replica (snippet included reflecting this relationship between databases in the Word doc.)

**Comment by navba-MSFT** [comment]
@langstonj Could you please share the word doc in this github thread ? Seems like the attachment from your email didn't make it in my inbox.

**Comment by langstonj** [comment]
[FailoverMessages20220624.docx](https://github.com/Azure/azure-powershell/files/9013633/FailoverMessages20220624.docx)

**Comment by langstonj** [comment]
closed inadvertently.

**Comment by langstonj** [comment]
It's there.

**Comment by navba-MSFT** [comment]
@langstonj I had a look at the word doc which you had shared. Since you are trying to fail the Geo-replica then the PS command you are using may not help here. `Invoke-AzSqlDatabaseFailover` is for testing failover within database’s local high-availability replicas.

Here is the right docs:
https://docs.microsoft.com/en-us/powershell/module/az.sql/set-azsqldatabasesecondary?view=azps-8.0.0#example-1-initiate-a-planned-failover

https://docs.microsoft.com/en-us/azure/azure-sql/database/active-geo-replication-overview?view=azuresql#powershell-manage-failover-of-single-and-pooled-databases

Hope this helps.

**Comment by langstonj** [comment]
[FailOverMessages20220630.docx](https://github.com/Azure/azure-powershell/files/9021923/FailOverMessages20220630.docx)

**Comment by navba-MSFT** [comment]
@langstonj Thanks for getting back and sharing the docx file again.

Regarding your error related to resource group, this seems to be due to not selecting the _right subscription_ context. Could you please run either of the below command to set your right Subscription ID before you execute the PS script.

>Select-AzSubscription -SubscriptionId 'XXXX-XXXX-XXXX-XXXX'
>Set-AzContext -Subscription "xxxx-xxxx-xxxx-xxxx"

Awaiting your reply.

**Comment by langstonj** [comment]
[FailOverMessage20220630_2.docx](https://github.com/Azure/azure-powershell/files/9025061/FailOverMessage20220630_2.docx)

**Comment by langstonj** [comment]
This author appears to have solved the "issue":

https://rahulrandive09.medium.com/error-40926-the-operation-cannot-be-performed-because-the-geo-replication-link-is-part-of-a-bdbe51bed773

1) Remove the database from the FG then run the commands
2) Failover the entire group

Will try in the morning...

**Comment by navba-MSFT** [comment]
@langstonj  Thanks for getting back and sharing the update. Please monitor and let us know if you face any issues. We would be happy to help.

**Comment by langstonj** [comment]
[FailOverMessages_20220701.docx](https://github.com/Azure/azure-powershell/files/9030932/FailOverMessages_20220701.docx)

**Comment by langstonj** [comment]
The Word doc contains my latest attempt and a recent link whose author appears to have gone down the path I have attempted to go down.  Sorry I did not find their work sooner. 

Hopefully you'll be able to examine it as they received the same error I did (40926).

**Comment by langstonj** [comment]
I removed the sqldb3091 database from the failover group and was able to execute the two commands which made North Central  database primary, the South Central version secondary.  An UPDATE in the North Central database was successful and failed in South Central (message was the database was read-only).  Ran the commands again to revert to original relationship.

**My conclusion is that I am not able to have database "A" in a failover group and only fail database "A" over to make the secondary database,  the primary database.**

Appreciate your time and trouble on this...

**Comment by navba-MSFT** [comment]
@langstonj [This](https://docs.microsoft.com/en-us/azure/azure-sql/database/active-geo-replication-overview?view=azuresql#preparing-secondary-database-for-failover) articles talks about this issue.  

>If your database is a member of a failover group, you cannot initiate its failover using the geo-replication failover command. Use the failover command for the group. If you need to failover an individual database, you must remove it from the failover group first. See [Auto-failover groups](https://docs.microsoft.com/en-us/azure/azure-sql/database/auto-failover-group-sql-db?view=azuresql) for details.

**Comment by langstonj** [comment]
Yes, I figured that out and confirmed it. Thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by navba-MSFT** [comment]
@langstonj Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
