### ISSUE TITLE
Move-AzureRmResource throws error when moving AppInsights and Service plans

### ISSUE THREAD

**Issue by San7hos** [Azure/azure-powershell#1856]
When trying to move AppInsights from one ResGroup to another, I am getting 404.

`$resource = Get-AzureRmResource -ResourceId <my_resource_id>
#$resource = Get-AzureRmResource -ResourceName "my res name" -ResourceGroupName "old res group"
Move-AzureRmResource -DestinationResourceGroupName "new group" -ResourceId $resource.ResourceId`

I have tried obtaining the resource by Id and Name + GroupName. Both cases succeeded. The result of the Move cmdlet is always 404.

**Comment by markcowl** [comment]
@vivsriaus can you take a look?

**Comment by vivsriaus** [comment]
@San7hos Can you please execute the Move-AzureRmResource command above with a -Debug switch and send me the traces?

**Comment by ravbhatnagar** [comment]
May be related to #1115  which was due to a server side issue. I am following up with the team to see if that has been fixed.

**Comment by ravbhatnagar** [comment]
@San7hos  - Can you please share the resource provider type which was failing?

**Comment by San7hos** [comment]
Hi fellows,

sorry to respond so late but I did not have time to pay attention to this problem before.

Resources that I was not able to move:
- App service plan (I am not sure if it should be working or not according to this https://azure.microsoft.com/en-us/documentation/articles/app-service-move-resources/)
```
error:   Long running operation failed with error: 'Invalid status code with response body "{"error":{"code":"ResourceMoveFailed","message":"Resources '/subscriptions/d5e12282-3ddb-4bd7-a0de-de0f1c621f4d/resourc
eGroups/Default-Web-NorthEurope/providers/Microsoft.Web/serverFarms/UnitechAppServicePlan' could not be moved. The tracking Id is '5a487853-9f84-489b-b4ec-99c4320e830f'","details":[{"target":"Microsoft.Web/serve
rFarms","message":"{\"Code\":\"BadRequest\",\"Message\":\"We can't move this combination of resources. To see all supported move requests check out the documentation here: https://azure.microsoft.com/en-us/docum
entation/articles/app-service-move-resources\",\"Target\":null,\"Details\":[{\"Message\":\"We can't move this combination of resources. To see all supported move requests check out the documentation here: https:
//azure.microsoft.com/en-us/documentation/articles/app-service-move-resources\"},{\"Code\":\"BadRequest\"},{\"ErrorEntity\":{\"Code\":\"BadRequest\",\"Message\":\"We can't move this combination of resources. To
see all supported move requests check out the documentation here: https://azure.microsoft.com/en-us/documentation/articles/app-service-move-resources\",\"ExtendedCode\":\"52017\",\"MessageTemplate\":\"We can't m
ove this combination of resources. To see all supported move requests check out the documentation here: https://azure.microsoft.com/en-us/documentation/articles/app-service-move-resources\",\"Parameters\":[\"\"]
```
- App insights resource

**Comment by ravbhatnagar** [comment]
@San7hos - Thanks for the response. You cannot move just the App Service plan resource. You can find the limitations  listed here - [https://azure.microsoft.com/en-us/documentation/articles/resource-group-move-resources/#app-service-limitations](url)

**Comment by San7hos** [comment]
Thanks, I have quite realised that once I tried the azure cli. I have originally used powershell and I think the error by that time was less explanatory.

How about the application insight? I can still remove it an recreate it, but moving it would be easier.

Is there any plan of enabling those movements in the future?

**Comment by ravbhatnagar** [comment]
Which Application insights resource was giving an issue? It might be related to an earlier issue on the service side which has been since fixed. Can you please let us know if you still running into an issue with a specific application insights resource?

**Comment by ravbhatnagar** [comment]
Closing this. Please comment if you still run into an issue.
