### ISSUE TITLE
Azure Website Backup

### ISSUE THREAD

**Issue by Chahul** [Azure/azure-powershell#1857]
Only classic storage accounts are supported for Azure website backups.For ARM deployment model websites , ARM storage accounts should be visible to perform backups.

**Comment by pcgeek86** [comment]
This doesn't seem like an actual problem with the Azure Resource Manager (ARM) PowerShell module, but rather a limitation of the Azure App Service Resource Provider itself. 

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by pcgeek86** [comment]
@markcowl Please confirm and close if appropriate, for now, until the Resource Provider supports this scenario.

**Comment by Chahul** [comment]
Thanks Trevor for your inputs from ARM perspective. It would be good to have usage ARM provisioned storage accounts for various activities such as backups, OMS association.

**Comment by pcgeek86** [comment]
@Chahul Of course, I agree with you there. It just can't even be implemented in PowerShell at this point, until the ARM Resource Provider for each service supports it. Resource Providers are the "plug-ins," so to speak, to ARM that expose various cloud Resource Types. You can read more about this in the Azure Documentation.
