### ISSUE TITLE
[Doc]:  Cannot process request. Too many operations in progress for subscription "%ld".

### ISSUE THREAD

**Issue by langstonj** [Azure/azure-powershell#18577]
### Description

https://docs.microsoft.com/en-us/azure/azure-sql/database/troubleshoot-common-errors-issues?view=azuresql

There is no instruction for how one delete's a pending request seen in the the output from **sys.dm_operation_status** .  This was a recent issue of ours in support case #2206070040005043.  

<html>
<body>

49920 | 16 | Cannot process request. Too many operations in progress for subscription "%ld".The service is busy processing multiple requests for this subscription. Requests are currently blocked for resource optimization. Query sys.dm_operation_status for operation status. Wait until pending requests are complete or **delete one of your pending requests** and retry your request later.
-- | -- | --

</body>
</html>
49920	16	Cannot process request. Too many operations in progress for subscription "%ld".

The service is busy processing multiple requests for this subscription. Requests are currently blocked for resource optimization. Query [sys.dm_operation_status](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-operation-status-azure-sql-database) for operation status. Wait until pending requests are complete or delete one of your pending requests and retry your request later.

**Comment by langstonj** [comment]
It doesn't help.

Respectfully, the documentation reference needs to state exactly what to execute to delete one of the pending requests, especially when the current documentation states "...Query sys.dm_operation_status for operation status. Wait until pending requests are complete or delete one of your pending requests..."

Multiple members of our team searched the documentation for the command to perform this delete but could find nothing.

This issue halted our Development work for three days and, apparently, a Product Group engineer had to run something in order for the output seen under sys.dm_operation_status to be deleted.

**Comment by navba-MSFT** [comment]
@langstonj Thanks for getting back. I will do some research on this and get back with an update.

**Comment by navba-MSFT** [comment]
@langstonj Customers can cancel ongoing copy operations by dropping the target database. This has been documented [here](https://docs.microsoft.com/en-us/azure/azure-sql/database/database-copy?view=azuresql&tabs=azure-powershell#monitor-the-progress-of-the-copying-operation).

>If you decide to cancel the copying while it is in progress, execute the [DROP DATABASE](https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-database-transact-sql) statement on the new database.

I understand that the above mentioned documentation is misleading in that it suggests that there's a way to "delete" any management operation. I will create a PR for this to clarify and suggest escalating to MS if operations are stuck.

**Comment by navba-MSFT** [comment]
@langstonj The above PR has been created for to address this ask and it is currently under Review phase. In the meantime, if you have any questions, please feel free to ask.

**Comment by langstonj** [comment]
We know on our end there is a way to remove/delete the management operations shown in the as this was suggested to me by one of the support engineers and was ultimately performed by a member of the Product Group.

If this is not possible for a regular user because the operation performed is only available to MS personnel , then "yes" the documentation is misleading in suggesting there is a way for a non-MS user to delete any management operation and does need to be changed to escalate to MS for stuck operations.
