### ISSUE TITLE
Stroage container.

### ISSUE THREAD

**Issue by Chahul** [Azure/azure-powershell#1858]
Although we can create Storage account through ARM models but creating underlying blob container is not possible.

**Comment by pcgeek86** [comment]
After you've provisioned a Storage Account, the "management plane" (ARM) leaves the scene, and the "data plane" takes over. You want to use the `Azure.Storage` module, which has the appropriate commands to obtain storage keys, create a storage context or SAS tokens, and manage containers and blobs.

To be clear, this is not a design problem or a bug, but rather a training issue.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by markcowl** [comment]
@pcgeek86 Thanks, Trevor!
