### ISSUE TITLE
[Feature]: Suggest user to select default subscription using azconfig cmdlet

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#18590]
### Description of the new feature

Below message is showing when I have multiple subscriptions. Since we support AzConfig, user can select default subscription by it. We'd better to update message and increase visibility of AzConfig.

```
PS C:\Dev> Connect-AzAccount
WARNING: TenantId '***' contains more than one active subscription. First one will be selected for further use. To select another subscription, use Set-AzContext.
```

### Proposed implementation details (optional)

`You can use 'Set-AzContext' to select another subscription or use 'Update-AzConfig -DefaultSubscriptionForLogin <>' to select default subscription after login`

**Comment by isra-fel** [comment]
Good point to advertise this new feature!

**Comment by dingmeng-xue** [comment]
@isra-fel , below recommended wording
```
PS C:\Dev> Connect-AzAccount
WARNING: TenantId '***' contains more than one active subscription. First one has been selected for this session. Use 'Set-AzContext' to select another subscription or 'Update-AzConfig -DefaultSubscriptionForLogin ***' to set the current subscription as default. Go to http://go.microsoft.com/fwlink?1234 for more information
```

@dcaro , @mikefrobbins FYI.

**Comment by mikefrobbins** [comment]
Product short link: [https://go.microsoft.com/fwlink/?linkid=2200610](https://go.microsoft.com/fwlink/?linkid=2200610)

**Comment by mikefrobbins** [comment]
Message to use:

WARNING: TenantId '***' contains more than one active subscription. First one has been selected for this session. Use 'Set-AzContext' to select another subscription or 'Update-AzConfig -DefaultSubscriptionForLogin ***' to set the current subscription as default. Go to https://go.microsoft.com/fwlink/?linkid=2200610 for more information.
