### ISSUE TITLE
Design issues with AzureRm.Compute\Add-AzureRmVMDataDisk command

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#1859]
In the `AzureRm.Compute` module, the `Add-AzureRmVMDataDisk` command needs some work.
- It offers a single parameter set, instead of multiple parameter sets like `Azure\Add-AzureDataDisk`
- The parameter values for the `-CreateOption` parameter are not properly cased for PowerShell (screenshot included)

<img width="588" alt="screen shot 2016-02-24 at 11 45 33 am" src="https://cloud.githubusercontent.com/assets/466713/13296725/2767d57e-daec-11e5-8c48-0ca464bf9e5c.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by markcowl** [comment]
@singhkay @huangpf Please take a look - seems like a couple of simple, logical signature changes for the cmdlet

**Comment by huangpf** [comment]
@hyonholee

**Comment by pcgeek86** [comment]
Why was this closed without any kind of explanation? Is there a resolution? No plan to fix? Delayed for future version?

Interesting approach.
