### ISSUE TITLE
New-AzureRoleAssignment uses ObjectId instead of principalId for parameters

### ISSUE THREAD

**Issue by clamanna** [Azure/azure-powershell#186]
The New-AzureRoleAssignment cmdlet uses ObjectId instead of principalId -- it should match the terminology used in the API & other documentation: 

https://msdn.microsoft.com/en-us/library/azure/dn906887.aspx

**Comment by cormacpayne** [comment]
Closing this issue as `New-AzureRoleAssignment` is no longer a cmdlet. Please check out the `New-AzureRmRoleAssignment` cmdlet, which has `PrincipalId` as a parameter.
