### ISSUE TITLE
[Doc]: Register-AzProviderFeature documentation clarification

### ISSUE THREAD

**Issue by chrismihm-ms** [Azure/azure-powershell#18607]
### Description

I'm working with a customer and they had questioned some of the areas in the documentation for "Register-AzProviderFeature"

https://docs.microsoft.com/en-us/powershell/module/az.resources/register-azproviderfeature?view=azps-8.0.0

They were asking if this registers globally for all subscriptions or at a single subscription. The documentation says "Registers an Azure provider feature in your account." which is vague and makes it sound like its ties to a user account. We did some testing with this and it seems like this command executes to the current subscription context. 

Customer was asking if the documentation could be updated to go into more detail as they use our documentation as reference in their CAB and change control and it would be helpful that the document references where this gets applied.

**Comment by dingmeng-xue** [comment]
It maps to https://docs.microsoft.com/en-us/rest/api/resources/features/register. It should be `Registers the preview feature for the subscription.` It needs CXP or service team to confirm it.

**Comment by chrismihm-ms** [comment]
My customer is questioning what "Account" means in this document. If it registers to the subscription it should say that so its clear to the customer. Their change advisory board wont let them make a change due to this language in this document as its vague and they are interpreting it as a global (across all subscriptions) registration.

Additionally, what they are registering isn't a preview feature.

***@***.***

**Comment by navba-MSFT** [comment]
@chrismihm-ms The above PR has been filed and it is currently under review. In the meantime, if you have any questions, please feel free to ask.
