### ISSUE TITLE
[Doc]: Az.AlertsManagement / Get-AzAlert

### ISSUE THREAD

**Issue by JoshuaKaluski** [Azure/azure-powershell#18606]
### Description

In the [Az.AlertsManagement>Get-AzAlert page](https://docs.microsoft.com/en-us/powershell/module/az.alertsmanagement/get-azalert?view=azps-8.0.0), there is a minor typo under the **_Parameters_** definition of _-MonitorService_. The definition currently reads:
![image](https://user-images.githubusercontent.com/46460752/174082373-dd6b033a-9a2e-416b-8e12-f413bb76b1a0.png)

Whereas the parameter information should be:
"[...] Filter on _Monit**or**_ Service [...]"

**Comment by dingmeng-xue** [comment]
@CaptainFanZzz , please help to correct it.

**Comment by JoshuaKaluski** [comment]
Just to add, it appears the typo also appears in the [Az.AlertsManagement>Measure-AzAlertStatistic page](https://docs.microsoft.com/en-us/powershell/module/az.alertsmanagement/measure-azalertstatistic?view=azps-8.0.0) as well. Most likely due to a copy-paste replication accross pages.
![image](https://user-images.githubusercontent.com/46460752/174314825-ca80d7e6-2002-4395-89a5-ebbdce5e3de1.png)
