### ISSUE TITLE
[Cmdlet reference doc]: Incorrect cmdlet name Get-AzRecoveryServicesBackupRecommendedArchivableRPGroup

### ISSUE THREAD

**Issue by MarcSteene** [Azure/azure-powershell#18619]
### Description

https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesbackuprecommendedarchivablerpgroup

This docs page describes the Get-AzRecoveryServicesBackupRecommendedArchivableRPGroup cmdlet.

The text in example 1 references a cmdlet that does not exist (Get-AzRecoveryServicesRecommendedArchivableRPGroup) - perhaps a typo or previous version of the cmdlet with a different name:
"Here we use **Get-AzRecoveryServicesRecommendedArchivableRPGroup** cmdlet to fetch the recommended RPs list to be moved to VaultArchive tier and assign to $rpGroup."

**Comment by PramodValavala-MSFT** [comment]
@MarcSteene Thanks for catching this! We will work up a PR to fix the typo.
