### ISSUE TITLE
PSNoteProperty doesn't allow empty string as a key

### ISSUE THREAD

**Issue by fenwickt** [Azure/azure-powershell#18622]
### Description

Hi PowerShell team,

I'm from ARG team who support ResourceGraph module in PowerShell. We have Search-AzGraph cmdlet that allows users to query their Azure resources. Resources can be of different types and contain different properties, so the cmdlet returns to the user list of PSObject objects. Resource properties inside the PSObject [get converted to PSNoteProperty](https://github.com/Azure/azure-powershell/blob/6acd4bf7eecdb75cd3d41f9d3b7f80e5db376a7f/src/ResourceGraph/ResourceGraph/Utilities/ResultExtensions.cs#L87). 

Recently we got a [CRI](https://portal.microsofticm.com/imp/v3/incidents/details/308428425/home) where Search-AzGraph failed with error: Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again. The root cause was that microsoft.logic/workflows resources allow properties with empty name (see Script output section). But PSNoteProperty doesn't allow key to be null or empty, therefore ResourceGraph module throws an error when tries to convert user resources to list of PSObjects.

Is there any recommended way to handle this issue? Maybe is there some other Property type which allows key to be an empty string? 

I could think of 2 ways to fix it, but both have issues:
1. Return properties as plain string. The problem is that printed output would be either shortcutted or not manageable for a user to read. I believe that was the reason to use PSNoteProperty in the first place.
2. Have a placeholder for the empty string key. This could be risky since Logic team may have some special logic for the empty keys, therefore users will need to be educated about this workaround. 

Would appreciate your help!

Thanks,
Mariia

### Script or Debug output

```PowerShell
Symptom:
PowerShell query fails with error:
Search-AzGraph : Cannot process argument because the value of argument "name" is not valid. Change the value of the
"name" argument and run the operation again.
At line:1 char:1
+ Search-AzGraph -Query $Query
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Search-AzGraph], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceGraph.Cmdlets.SearchAzureRmGraph

Query is: 
$query="Resources | where type in ('microsoft.logic/workflows')"
Search-AzGraph -Query $query
---------------------------------------------------------------------------------------------------
Troubleshooting:
- Problematic property is 
"actions": {
    "Select": {
        "runAfter": {},
        "type": "Select",
        "inputs": {
            "from": "@triggerBody()",
            "select": {
                "": "dasd"
            }
        }
    }
}
```

**Comment by dingmeng-xue** [comment]
Thanks for contacting us.

[PSMemberInfo](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psmemberinfo?view=powershellsdk-7.0.0) doesn't allow empty string as key name. If it's not easy to change the data type of return object, you can consider to add a dummy string as its key. Otherwise skip that property if it is invalid from ARG perspective.
