### ISSUE TITLE
[Feature]: Need AvailabilityZone parameter for New-AzAksCluster

### ISSUE THREAD

**Issue by Xingbin-Li** [Azure/azure-powershell#18658]
### Description of the new feature

As per [official AKS document](https://docs.microsoft.com/en-us/azure/aks/availability-zones#create-an-aks-cluster-across-availability-zones), it is stated that 

> `The control plane components such as etcd or the API are spread across the available zones in the region if you define the --zones parameter at cluster creation time. `

So we need **AvailabilityZone** parameter for **New-AzAksCluster** as well in order to spread control plane across the available zones when use powershell commands to create the cluster.

**Comment by dingmeng-xue** [comment]
@wyunchi-ms , please help to look into this requirement.
