### ISSUE TITLE
Find-AzureRmResource -TenantLevel

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-powershell#1867]
The call
`Find-AzureRmResource -ResourceNameContains serverName -TenantLevel -ResourceType Microsoft.ClassicCompute/virtualMachines`

Fails with the following error message

> Find-AzureRmResource : AuthorizationFailed : The client 'xxx@yyy.com' with object id '2xxx-xxx-xxx-xxx-xxx1' does not have authorization to perform action 'Microsoft.ClassicCompu
> te/virtualMachines/read' over scope '/providers/Microsoft.ClassicCompute'.
> At line:1 char:1
> - Find-AzureRmResource -ResourceNameContains serverName -TenantLevel  ...
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : CloseError: (:) [Find-AzureRmResource], ErrorResponseMessageException
>   - FullyQualifiedErrorId : AuthorizationFailed,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.FindAzureResourceCmdlet
>

**Comment by markcowl** [comment]
@vivsriaus Is this a provider registration issue, or is -TenantLevel meant to apply to only tenant-specific resources?

**Comment by vivsriaus** [comment]
Correct, -TenantLevel is meant to apply to only tenant-specific resources. 
@eosfor ClassicCompute/virtualMachines resources cannot be created/listed under a tenant.

**Comment by eosfor** [comment]
My assumption was that TenantLevel is to search all subscriptions in the tenant for some object. Looping through all subscriptions i have is still very slow. Azure portal works much faster.

**Comment by vivsriaus** [comment]
Tenant level searches/gets doesn't have subscriptions in the request URI - for example, here is a tenant level GET: (notice how the subscription Id is missing in the URI)
https://management.azure.com/providers/Microsoft.PowerApps/apps/69fb28f7-9bb3-2766-2b0e-b9449f10fa3c?api-version=2015-02-01-preview
A tenant level search request (via Find-AzureRmResource) can look like:
https://management.azure.com/providers/Microsoft.PowerApps/apps?api-version=2015-02-01-preview

What is the portal api call you're trying to replicate via Find-AzureRmResource?
What api call are you looking for here?

**Comment by eosfor** [comment]
Sorry for late reply. I'm using something from here. It basically queries https://management.azure.com/api/invoke and asks it to search a name across all my subscriptions and return results back to me. That is why it works much faster than individual calls in the loop.

$name = 'servername'
[string]$apiVersion = '2014-04-01-preview'
$ADTenant = 'myself.onmicrosoft.com'
$authHeader = Get-AzureAuthHeader -ADTenant $ADTenant

$headers = @{'x-ms-version'="$headerDate";
                'Authorization' = $authHeader;
                'Accept' = 'application/json'}



function generateFilterStringForSubscription{
    [CmdletBinding()]
    param($SubscriptionName, $SubscriptionID)
    process {
        $test = $PSBoundParameters
        if ($PSBoundParameters.ContainsKey('SubscriptionID')){
            if ($SubscriptionID) {
            $subscrFilterString = ($SubscriptionID | % {"subscriptionId eq '$_'"}) -join ' or '}
        }
        elseif ($PSBoundParameters['SubscriptionName']){
            $subscriptions = (Get-AzureSubscription -SubscriptionName $SubscriptionName).SubscriptionId
        $subscrFilterString = ($subscriptions | % {"subscriptionId eq '$_'"}) -join ' or '}
        else {
            $subscriptions = (Get-AzureSubscription).SubscriptionId
        $subscrFilterString = ($subscriptions | % {"subscriptionId eq '$_'"}) -join ' or '}

        write-verbose "Subscriptions filter`: $subscrFilterString"
        $subscrFilterString
    }
}

$subscrFilterString = generateFilterStringForSubscription

# API method
$method = 'GET'

## build filter string for REST Query call
$objectFilter = ($Name | %{ ("substringof('$_', name)", "substringof('$_', resourcegroup)") -join ' or ' }) -join ' or '
    
## query header (name part of the filter)
$headers.'x-ms-path-query' = "/resources?api-version=$apiVersion&`$filter=($subscrFilterString) and (($objectFilter))" -replace ' ', '%20'

# generate the API URI
$URI = 'https://management.azure.com/api/invoke'

# execute the Azure REST API
$list = @()
$res = Invoke-RestMethod -Uri $URI -Method $method -Headers $headers -ErrorAction stop
if ($res.value) {$list += $res.value}
    
while (Get-Member -inputobject $res -name 'nextLink' -Membertype Properties ){
    $res = Invoke-RestMethod -Uri $res.nextLink -Method $method -Headers $headers -ErrorAction stop
    if ($res.value) {$list += $res.value}
}

$res

**Comment by ravbhatnagar** [comment]
Investigate options to perform search for object across subscriptions in a tenant.

**Comment by ravbhatnagar** [comment]
No plans of supporting this. Let us know if you feel this is important and we can prioritize it higher.
