### ISSUE TITLE
Import-AzureRmApiManagementApi requires ApiId when creating new API

### ISSUE THREAD

**Issue by pafriend** [Azure/azure-powershell#1871]
The docs for Import-AzureRmApiManagementApi state the if ApiId is not provided then an id is generated. The command fails when ApiId is not provided stating that it is required. If an ApiId is provided that matches an existing id the command works. All other values fail. If a blank string is provided the command fails with a generic PUT failure.

**Comment by pafriend** [comment]
To clarify, when ApiId is not provided or $null you get the error below. Note the aid parameter in the error. That is from the Azure API code.

`Import-AzureRmApiManagementApi : Value cannot be null.
Parameter name: aid
At line:1 char:8
+ $api = Import-AzureRmApiManagementApi -Context $context -Specificatio ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Import-AzureRmApiManagementApi], ArgumentNullException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.ImportAzureApiManagementApi
`

If I try to generate an api id using NewGuid, or any non-empty string, there is a ValidationError.

`Import-AzureRmApiManagementApi : ValidationError: One or more fields contain incorrect values:
At line:1 char:8
+ $api = Import-AzureRmApiManagementApi -Context $context -Specificatio ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Import-AzureRmApiManagementApi], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.ImportAzureApiManagementApi`

**Comment by pafriend** [comment]
After some hours of trying different things and looking at the SDK sources, I think I have a workaround. Since the current version requires an ApiId parameter, I generate a guid if the API doesn't exist yet. As mentioned that alone isn't enough, turns out that the SDK requires a Path parameter, and in my case I just pass a blank string and it seems to work fine.

**Comment by rossedman** [comment]
@pafriend Can you post your solution here. Thanks.
