### ISSUE TITLE
Remove-AzADSpCredential doesn't remove credentials

### ISSUE THREAD

**Issue by rezarms** [Azure/azure-powershell#18722]
### Description

I'm using Remove-AzADSpCredential to remove password credentials but it doesn't do anything.
I don't receive any error but when check credentials they are still there.

In debug mode I see it's calling correct API and the body doesn't contain the deleted one.
It’s happened only for an old spn.
For this spn ,keyid for password and certificate is the same.

It seems it can be the API error.

### Issue script & Debug output

```PowerShell
HTTP Method:
PATCH
https://graph.windows.net/xxxxx/servicePrincipals/xxxxx/keyCredentials?api-version=1.6
Body:
{
  "value": [
{
      "startDate": "2019-04-12T00:00:00Z",
      "endDate": "2020-04-12T00:00:00Z",
      "keyId": "550fd04",
      "usage": "Sign",
      "type": "AsymmetricX509Cert",
      "customKeyIdentifier": "F77E9B42",
      "value": null
    }
]
}



Status Code:
NoContent
```

### Environment data

```PowerShell
PsVersion
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Azure version   6.0.0
```

### Error output

```PowerShell
No error
```

**Comment by dingmeng-xue** [comment]
@VeryEarly , please look into this one.

**Comment by VeryEarly** [comment]
please use Remove-AzADAppCredential, these sp credential APIs won't do anything

**Comment by rezarms** [comment]
The other problem is Get-AzAdAppCrednetial returns empty result but Get-AzAdSpCredential returns correct result.
I also called Remove-AzADAppCredential and it didn't do anything either.
I ran it in debug and found out it calls api to get credentials which is empty.
I think it's related to #16983 and #21195

**Comment by VeryEarly** [comment]
> The other problem is Get-AzAdAppCrednetial returns empty result but Get-AzAdSpCredential returns correct result. I also called Remove-AzADAppCredential and it didn't do anything either. I ran it in debug and found out it calls api to get credentials which is empty. I think it's related to #16983 and [Azure/azure-cli#21195](https://github.com/Azure/azure-cli/issues/21195)

Hi @rezarms ,

Can you describe how Get-AzADAppCredential doesn't work? Just ran a quick test and it worked for me:
```
PS C:\Users\yabhu> Get-AzADAppCredential -ObjectId $id

CustomKeyIdentifier DisplayName                                                                      EndDateTime
------------------- -----------                                                                      -----------
{19, 77, 186, 7…}   CN=feba5c5f-4017-4a84-b8d5-acad9a225d84, DC=72f988bf-86f1-41af-91ab-2d7cd011db47 9/28/2021 4:20:45…
{19, 77, 186, 7…}   CN=feba5c5f-4017-4a84-b8d5-acad9a225d84, DC=72f988bf-86f1-41af-91ab-2d7cd011db47 9/28/2021 4:20:45…
{19, 77, 186, 7…}   CN=feba5c5f-4017-4a84-b8d5-acad9a225d84, DC=72f988bf-86f1-41af-91ab-2d7cd011db47 9/28/2021 4:20:45…
{19, 77, 186, 7…}   CN=feba5c5f-4017-4a84-b8d5-acad9a225d84, DC=72f988bf-86f1-41af-91ab-2d7cd011db47 9/28/2021 4:20:45…
{19, 77, 186, 7…}   CN=feba5c5f-4017-4a84-b8d5-acad9a225d84, DC=72f988bf-86f1-41af-91ab-2d7cd011db47 9/28/2021 4:20:45…
{19, 77, 186, 7…}   CN=feba5c5f-4017-4a84-b8d5-acad9a225d84, DC=72f988bf-86f1-41af-91ab-2d7cd011db47 9/28/2021 4:20:45…

CustomKeyIdentifier  :
DisplayName          :
EndDateTime          : 12/2/2022 12:58:12 AM
Hint                 : DLr
KeyId                : 9b44bbb5-715a-403f-ad14-1839f0c86909
SecretText           :
StartDateTime        : 12/2/2021 12:58:12 AM
AdditionalProperties : {}
```

**Comment by rezarms** [comment]
I already raised the issue for Get-AzADAppCredential.
It's the Graph api bug  in both Azure AD graph and Microsoft graph.
I'm not saying for all apps it doesn't work.
For some apps it doesn't return anything so I should use Get-AzAdSpCredential but after renewing the secrets Get-AzAdSpCredential works.

**Comment by dingmeng-xue** [comment]
Mark it as service side issue. Close current issue now. Please contact us if you need further help.
