### ISSUE TITLE
[Doc]: https://docs.microsoft.com/en-us/powershell/module/az.cdn/enable-azcdncustomdomainhttps?view=azps-7.5.0

### ISSUE THREAD

**Issue by ishmeet177** [Azure/azure-powershell#18760]
### Description

The example 1 mentions below command which has a syntax error. 
Enable-**AzCdnCustomDomainHttps** -ResourceGroupName $resourceGroupName -ProfileName $profileName -EndpointName $endpointName -CustomDomainName $customDomainName

Error:
Enable-AzCdnCustomDomainHttps: The term '**Enable-AzCdnCustomDomainHttps**' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

The correct command should be:
Enable-**AzCdnCustomDomainCustomHttps** -ResourceGroupName $resourceGroupName -ProfileName $profileName -EndpointName $endpointName -CustomDomainName $customDomainName

**Comment by dingmeng-xue** [comment]
Involve CXP team to look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@ishmeet177 Enable-AzCdnCustomDomainHttps is older version available for `Az Powershell 7.5.0 version` whereas `Enable-AzCdnCustomDomainCustomHttps` is newer version.
Please refer to the below documentations
- [Az.Cdn - 7.5.0](https://docs.microsoft.com/en-us/powershell/module/az.cdn/enable-azcdncustomdomainhttps?view=azps-7.5.0)
- [Az.Cdn - 8.1.0](https://docs.microsoft.com/en-us/powershell/module/az.cdn/?view=azps-8.1.0)

**Comment by SaurabhSharma-MSFT** [comment]
@ishmeet177 We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
