### ISSUE TITLE
deployments resource should return uri on file not found

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-powershell#1877]
When using a uri with a deployments resource if the template or param file uri is bad the error returned is:

`10:51:38 - [ERROR] New-AzureRmResourceGroupDeployment : 10:51:38 AM - Resource Microsoft.Resources/deployments 'nestedStorage' failed with message 'Unable to download deployment content. The tracking Id is '3d41ca0c-c249-4150-815b-b78ecb69c8ab'. Please see 
10:51:38 - [ERROR] http://aka.ms/arm-deploy for usage details.'
`

This is a clear message but it's often difficult to know what uri was attempted give that it's likely constructed with concats and params/vars.  Returning the attempted uri would certainly be helpful in debugging, though it may contain a sasToken (secureString param for example) so we'd need clear guidance there.

**Comment by vivsriaus** [comment]
Agreed. But the improvement is needed on the server side, instead. cc: @ravbhatnagar @yangl900 to track this

**Comment by ravbhatnagar** [comment]
Tracking this on our service backlog. Closing here.
