### ISSUE TITLE
Set-AzureSqlDatabaseServerFirewallRule incompatible with Select-AzureRmSubscription

### ISSUE THREAD

**Issue by aaronhoffman** [Azure/azure-powershell#1878]
I am new to Azure Powershell so please forgive me if this is an obvious incompatibility.

Using the new Resource Manager Login/Auth flow (`Add-AzureRmAccount`, `Select-AzureRmSubscription`), I am unable to successfully execute the command `Set-AzureSqlDatabaseServerFirewallRule` and instead get the following error:

`Set-AzureSqlDatabaseServerFirewallRule : No default subscription has been designated. Use Select-AzureSubscription -Default <subscriptionName> to set the default subscription.`

But of course if I attempt to execute the command `Select-AzureSubscription` I get an error saying the SubscriptionId does not exist because I used the Resource Management auth flow and not the Classic method.

If however I follow the classic "service management" auth flow (`Get-AzurePublishSettingsFile`, `Import-AzurePublishSettingsFile`) the `Set-AzureSqlDatabaseServerFirewallRule` command executes successfully.

Is there an alternative to `Set-AzureSqlDatabaseServerFirewallRule` that is compatible with the new Resource Management auth flow `Select-AzureRmSubscription`?

**Comment by markcowl** [comment]
@aaronhoffman Yes, it is Set-AzureRmSqlFirewallRule

In general, cmdlets using the AzureRM noun work with azure rm authentication.
