### ISSUE TITLE
Add-AzureRmAccount Dialog

### ISSUE THREAD

**Issue by aaronhoffman** [Azure/azure-powershell#1880]
Where can I go to learn more about this dialog and the reasons it appears after the `Add-AzureRmAccount` cmdlet is executed? Specifically, I do not believe I have a "work or school account" but I would like to learn more about it, and why I am seeing this message.

![image](https://cloud.githubusercontent.com/assets/109249/13367105/5d995d92-dca5-11e5-818f-32732dab8797.png)

**Comment by alexandair** [comment]
https://azure.microsoft.com/en-us/documentation/articles/active-directory-how-subscriptions-associated-directory/

**Comment by pcgeek86** [comment]
@aaronhoffman there are two options for authentication:

- Microsoft Account (MSA): This is your "personal account" that "you created" (according to the dialog).
- Azure Active Directory (AAD) Account: A "work or school" account that is typically created by IT organizations, but likely could have been created by yourself.

Hope this helps!

Cheers,
Trevor Sullivan

**Comment by aaronhoffman** [comment]
I own a small consultancy and we use google apps for business, gmail, etc., and I'll have each employee use their @mygoogleappsdomain email address and create a MS/Live account on their own so that I can add them to our various Azure Subscriptions. Can I use Azure AD to "create" this MS/Live account for them, so they don't need to do it themselves? Would you be able to point me to some documentation around that?

**Comment by pcgeek86** [comment]
@aaronhoffman They'll have to create their own Microsoft Accounts, unfortunately.
