### ISSUE TITLE
Get-AzureResourceGroupGalleryTemplate is missing in latest cmdlets

### ISSUE THREAD

**Issue by doctordns** [Azure/azure-powershell#1885]
I am following a MIcrosoft MVA online training course, and it illustates the use of Get-AzureResourceGroupGalleryTemplate. That cmdlet appears to have been withdrawn, presumably as part of the great re-naming.

Yes, I know you can get this list, easily enough, using REST - but why do i have to go so low level? PowerShell is designed to enable IT Pros to avoid programmer level stuff, and act at a high level of abstraction.  And yes, I've written a very simple function to provide this feature. But I shoid not have to!

Can we please get this cmdlet back?

**Comment by ravbhatnagar** [comment]
#1759

**Comment by doctordns** [comment]
FWIW, I've written a function to do this: See:

http://tfl09.blogspot.co.uk/2016/02/get-azureresourcegroupgallerytemplate.html

I can provide the source code - or feel free to leverage it from the blog!

**Comment by GillesZunino** [comment]
Hi - Thanks for reaching out. Point taken about Invoke-WeRequest being too low level for IT Pros. We are working on an enhanced set of cmdlets - We are not yet ready to share more details about this..

**Comment by doctordns** [comment]
Giles - this is an open source project, right? If so, shouldn't the ideas be more freely shared.

If nothing else, the team needs to expose their plans early to avoid more changes later.

**Comment by GillesZunino** [comment]
Hi - As you described above, the cmdlet is really a thin wrapper around an REST endpoint. The cmdlets are open source but the REST endpoint is not. The REST API is something I cannot discuss at this time and sadly, this limits my ability to make forward statements about the cmdlets calling this REST API - sorry.

Conversations about the current REST API as well as the current powershell script which (poorly) fills the gap until we have a better solution are more than welcome.

What do you exactly look forward to see in AzureResourceGalleryTemplate ? Drop in replacement? Aditional capabilities ?

**Comment by doctordns** [comment]
Giles - thanks for clarifying. Would the Azure PowerShell Advisors Yammer group be a better place to have the discussion over the REST interface??

In term of templates, I'd expect to be able to find/locate/discover a template using a Get-...Template... cmdlet. , and a cmdlet to deploy the template. (The verb deploy however is not on the approved verb list).  I'd also like to be able to get and manage/manipulate the JSON that represents the template's parameters, although I've not given much thought to how that should be done.

**Comment by cormacpayne** [comment]
Closing this issue as this seems to have been resolved. Please feel free to re-open this issue if you have any other questions.

**Comment by doctordns** [comment]
Well - it has NOT actually been resolved. There is an issue,  Get-AzureResourceGroupGalleryTemplate is gone. There is vague mention of new cmdlets, but I can't see them. 

Feel free to close an issue when it's resolved. It may not really be appropriate until the actual new cmdlet5s are delivered.

**Comment by doctordns** [comment]
And as an aside, shouldn't the closing of an issue be agreed top by the person who raised it?  
I raised it because there was MSFT material that referenced a now-removed cmdlet. 
Do I need to re-open this issue?

**Comment by doctordns** [comment]
Will the **Get-AzureResourceGroupGalleryTemplate ** cmdlet come back in some form or another?

**Comment by markcowl** [comment]
@doctordns The service itself is defunct and has not been revived, so there is no basis for new cmdlets.  Closing, because there is no action that azure powershell can take here.  

If you want to ask about the gallery service, please ask in the azure support forums.
