### ISSUE TITLE
[Doc]: How do you specify "anyOf" condition? 

### ISSUE THREAD

**Issue by pdhimate** [Azure/azure-powershell#18851]
### Description

The ARM template suppports a nested **_anyof_**  condition as shown below. How do we set it if we are to use **_New-AzActivityLogAlertCondition_**

![image](https://user-images.githubusercontent.com/1121826/176802517-cf8c526e-41ea-43d9-b5f9-fb658bfe5a49.png)

**Comment by PramodValavala-MSFT** [comment]
@pdhimate Apologies on the delay here! Looks like the current models here don't support that. We are assigning this issue to the concerning team to update.

In the meantime, you can make the required requests using the [`Invoke-AzRestMethod` cmdlet](https://docs.microsoft.com/en-us/powershell/azure/manage-azure-resources-invoke-azrestmethod?view=azps-8.1.0), which is essentially calling the corresponding ARM REST API directly.
