### ISSUE TITLE
No MSI package for Azure PowerShell 8.1.0?

### ISSUE THREAD

**Issue by benoithamet** [Azure/azure-powershell#18873]
### Description

Hi team

you used to provide an MSI package to deploy Azure PowerShell modules but the latest release - 8.1.0 - does not provide it
are you getting ride of the MSI package?
this is quite useful to deploy on managed devices with SCCM and/or Intune
thanks

**Comment by dingmeng-xue** [comment]
@VeryEarly , please check pipeline and upload all required artifacts to Github release.

**Comment by VeryEarly** [comment]
Hi @benoithamet ,
Thanks for noticing, please check updated release:
https://github.com/Azure/azure-powershell/releases/tag/v8.1.0-July2022

**Comment by benoithamet** [comment]
thanks team
all good now
