### ISSUE TITLE
Import-AzApiManagementApi: AuthorizationServerId is reset when importing an API.

### ISSUE THREAD

**Issue by johnsrsly** [Azure/azure-powershell#18880]
### Description

Step 1: Run New-AzApiManagementApi and specify -AuthorizationServerId. Authorization is set as expected.
Step 2: Run Import-AzApiManagementApi. Authorization is being set to null.

I would expect the import to not have any effect on the AuthorizationServerId, since i cannot specify it in the parameters of Import-AzApiManagementApi.

### Issue script & Debug output

```PowerShell
New-AzApiManagementApi `
        -Context $ApiMgmtContext `
        -ApiId "test" `
        -Name "test" `
        -ServiceUrl "https://test.com/api" `
        -Path "test" `
        -Protocols @("https") `
        -AuthorizationServerId $AuthorizationServerId

Import-AzApiManagementApi `
    -Context $ApiMgmtContext `
    -ApiId "test" `
    -SpecificationFormat "OpenApiJson" `
    -SpecificationPath $SpecificationPath `
    -Path "test"
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name            
---------- -------    ---------- ----            
Script     3.0.0                 Az.ApiManagement
```

**Comment by johnsrsly** [comment]
Any thoughts?

**Comment by navba-MSFT** [comment]
@johnsrsly Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

CC @RakeshMohanMSFT

**Comment by RakeshMohanMSFT** [comment]
@johnsrsly We are unable to reproduce this issue at our end. Please see image below. 1) We created an API with a auth server. 2) We imported an API without specifying any auth server.
![image](https://user-images.githubusercontent.com/49954584/198523222-5582cf12-8e84-4bd8-9319-53b309837d51.png)

![image](https://user-images.githubusercontent.com/49954584/198523253-d8fed24b-93fb-48d8-bc62-a96a90c30be1.png)

**Let us know if we are missing something.**
