### ISSUE TITLE
Get-AzureRmResourceGroup examples are misleading

### ISSUE THREAD

**Issue by towerbe** [Azure/azure-powershell#1888]
Two of the three examples for Get-AzureRmResourceGroup show the use of the "-Detailed" parameter (see example 1 and example 3); however, when trying to use this syntax in a live system no such parameter is found.

PS P:\> Get-AzureRmResourceGroup -Detailed
Get-AzureRmResourceGroup : A parameter cannot be found that matches parameter name 'Detailed'.
At line:1 char:26
+ Get-AzureRmResourceGroup -Detailed
+                          ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmResourceGroup], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.Resources.GetAzureResourceGroupCommand

Either the parameter has been deprecated or not yet implemented.  Any help is appreciated.

**Comment by ravbhatnagar** [comment]
@towerbe - Yes, this param has been removed. We will get the help updated in the next release of PS. Can you please let us know what you wanted to achieve with the Detailed param? Did you want to list all the resources for that Resource group?

**Comment by towerbe** [comment]
That is exactly what I wanted.

**Comment by ravbhatnagar** [comment]
The recommended pattern for this scenario is Get-AzureRmResource. But this currently has a bug which is fixed in the March release of Azure PS(will be released soon). Till then, you can use Find-AzureRmResource to list all resources under a resource group or to list all resources of a particular type etc.

**Comment by ravbhatnagar** [comment]
Fixed for Apr Release
