### ISSUE TITLE
Default Subscription for Azure PowerShell 1+

### ISSUE THREAD

**Issue by devigned** [Azure/azure-powershell#1889]
Feedback from a customer:

> Given Select-AzureRmSubscription removed the concept of a Default subscription is there some new way we can set a default?
> 
> If not, can we add the Subscription ID / Name prominently somewhere on the main Azure Portal landing page (top navigation?) so there's no need to click through a couple of items to be able to copy it from a details screen?
> 
> Managing multiple Subscriptions (with one being the main one I work in) makes this very painful as the result of Login-AzureRmAccount always selects another Subscription :(.

@markcowl and @mayurid what do you think about this?

**Comment by sjwaight** [comment]
+1 from me on this.

**Comment by markcowl** [comment]
@devigned @sjwaight As discussed in the thread this was copied from, you can currently use ```Save-AzureRmProfile -Path <path-to-file>```  then use ```Select-AzureRmProfile -Path <path-to-file>``` to restore your previous settings.

Note that you can also provide a subscription name of subscription id when using Add-AzureRmAccount.  It is in plan to provide a default save and load capability for the users that want this capability.  See: https://www.pivotaltracker.com/story/show/106026864

**Comment by markcowl** [comment]
### Proposed Solution
- Automatically save and read the profile from ~/AppData/AzurePowerShell/defaultprfile.json
- Add a -SessionOnly parameter to Add-AzureRmAccount, Set-AzureRmContext, Select-AzureRMProfile cmdlets which saves the profile only to the current session
- flesh out design details

### Cost (work units): 8

**Comment by markcowl** [comment]
This is scheduled in the current sprint as #2728   Closing in favor of the more detailed issue tracking the fix.
