### ISSUE TITLE
Select-AzureSubscription erases the DefaultAccount details from AzureSubscription

### ISSUE THREAD

**Issue by NehaRaje** [Azure/azure-powershell#189]
> Get-AzureSubscription -Default

SubscriptionId            : xxx
SubscriptionName          : xxx
Environment               : xxx
SupportedModes            : xxx
DefaultAccount            : 6C59C0157E9E7A402B8A743550F48E76BC92509
Accounts                  : {6C59C0157E9E7A402B8A743550F48E76BC92509}
IsDefault                 : True
IsCurrent                 : True
CurrentStorageAccountName :
TenantId                  :

PS C:\> Select-AzureSubscription -Id xxx
PS C:\> Get-AzureSubscription -Default

SubscriptionId            : xxx
SubscriptionName          : xxx
Environment               : xxx
SupportedModes            : xxx
DefaultAccount            :
Accounts                  : {6C59C0157E9E7A402B8A743550F48E76BC92509}
IsDefault                 : True
IsCurrent                 : True
CurrentStorageAccountName :
TenantId                  :

**Comment by matt-gibbs** [comment]
Dev branch

**Comment by stankovski** [comment]
Fix: https://github.com/Azure/azure-powershell/pull/190

**Comment by markcowl** [comment]
@NehaRaje This should be fixed.  Please reopen if you see a recurrence.

**Comment by NehaRaje** [comment]
Yes I did test it.
Sure. Thanks!
