### ISSUE TITLE
Start-AzImageBuilderTemplate still throw error and end the script even -ErrorAction SilentlyContinue is specified

### ISSUE THREAD

**Issue by ShikeChen-MS** [Azure/azure-powershell#18900]
### Description

I am writing a powershell script to automating the Azure Image Builder template creation and image building process. My intention is after executing Start-AzImageBuilderTemplate (synchronously), whenever the image building fails, the Powershell would not throw the exception and carry on executing the rest of script, hence, I specified -ErrorAction SilentlyContinue, but it doesn't work. It always error out with exception.

Also I tried specifying -ErrorAction stop and embed the code in a try-catch block, it doesn't work too, the catch block is never executed.

### Issue script & Debug output

```PowerShell
The script doesn't respect the -ErrorAction SilentlyContinue and error out.
```

### Environment data

```PowerShell
powershell core: 7.2.5
```

### Module versions

```PowerShell
Azure PowerShell: 8.1.0
Azure ImageBuilder module: 0.2.0
```

**Comment by dingmeng-xue** [comment]
@ShikeChen-MS , could you share your input value and debug log? You can get debug log after setting `$DebugPreference = "Continue"`.
