### ISSUE TITLE
[Doc]: https://docs.microsoft.com/en-us/powershell/module/az.dataprotection/suspend-azdataprotectionbackupinstancebackup?view=azps-8.1.0

### ISSUE THREAD

**Issue by enlinting** [Azure/azure-powershell#18912]
### Description

The description of this cmdlet isn't clear.

I've checked with the PG and below is a table for a quick comparison of the 2 Powershell cmdlets:

Powershell Cmdlet | Description
-- | --
[Suspend-AzDataProtectionBackupInstanceBackup](https://docs.microsoft.com/en-us/powershell/module/az.dataprotection/suspend-azdataprotectionbackupinstancebackup?view=azps-8.1.0) | Stops Backup for a Backup Instance and   Retains the Backup Data as per the Policy (except Latest Recovery Point,   which will be retained forever)
[Stop-AzDataProtectionBackupInstanceProtection](https://docs.microsoft.com/en-us/powershell/module/az.dataprotection/stop-azdataprotectionbackupinstanceprotection?view=azps-8.1.0) | Stops Backup for a Backup Instance and   Retains the Backup Data forever

</body>

</html>

**Comment by dingmeng-xue** [comment]
Involve CXP team to look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@enlinting Thanks for your feedback.  The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
