### ISSUE TITLE
[Doc]: Typo on cmdlet reference page

### ISSUE THREAD

**Issue by guyrleech** [Azure/azure-powershell#18913]
### Description

I suspect  that this text "Force flag to login off userSession" for the -force parameter should be "Pass force flag to the logging off of the user session" or similar where the word "login" is incorrect as the cmdlet is about logging a user off who has already logged in

[(https://docs.microsoft.com/en-gb/powershell/module/az.desktopvirtualization/remove-azwvdusersession?view=azps-8.1.0)]

**Comment by dingmeng-xue** [comment]
Thanks for contacting us. Involve CXP team to look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@guyrleech The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
