### ISSUE TITLE
New-AzFunctionApp should support creating Java 17 (preview) function apps

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-powershell#18925]
### Description

New-AzFunctionApp should support creating Java 17 (preview) function apps

### Issue script & Debug output

```PowerShell
N/A
```

### Environment data

```PowerShell
N/A
```

### Module versions

```PowerShell
N/A
```

### Error output

```PowerShell
N/A
```

**Comment by MadhuraBharadwaj-MSFT** [comment]
@Francisco-Gamino 
Maven release for Java 17 has been completed by @Flanker32 and the final Stacks API update PR has been merged: https://github.com/Azure/azure-functions-ux/pull/6855.

We originally discussed targeting the 9/2/2022 release for AzPowerShell. Does that still look possible?

**Comment by Francisco-Gamino** [comment]
This issue has been fixed.
