### ISSUE TITLE
New version Az module cannot use in Azure China.

### ISSUE THREAD

**Issue by tianputao** [Azure/azure-powershell#18945]
### Description

Hi, I found some Az module API is too new to use in Azure China. I tested Eventhub and ADF can't use.

### Issue script & Debug output

```PowerShell
Body:
{
  "error": {
    "code": "NoRegisteredProviderFound",
    "message": "No registered resource provider found for location 'chinaeast2' and API version '2022-01-01-preview' for type 'namespaces'. The supported api-versions are '2014-09-01, 2015-08-01, 2017-04-01, 2018-01-01-preview, 2021-01-01-preview, 2021-06-01-preview, 2021-11-01'. The supported locations are 'chinanorth, chinaeast, chinanorth2, chinaeast2, chinanorth3'."
  }
}
```

### Environment data

```PowerShell
$PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      5
```

### Module versions

```PowerShell
Az Powershell 8.1.0
```

**Comment by dingmeng-xue** [comment]
@tianputao , the service version in China cloud is running behind the public cloud. Please use the older version of module. If you want to use the latest version of feature of service, please let us know. We will involve each service team to provide update.

**Comment by navba-MSFT** [comment]
@tianputao Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
> @tianputao , the service version in China cloud is running behind the public cloud. Please use the older version of module. If you want to use the latest version of feature of service, please let us know. We will involve each service team to provide update.

@tianputao Did you get a chance to look at the above command? As a next action plan, please test with the older version of the Az module so that it uses the older api-version. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@tianputao I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you have any follow-up questions on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@tianputao The action is currently pending on you test with older version since the service version in China cloud is running behind the public cloud. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
