### ISSUE TITLE
Unable to append variable to url

### ISSUE THREAD

**Issue by juliamaureen** [Azure/azure-powershell#18949]
### Description

I am writing an action that grabs the object id of an Azure User and adds it as owner of an AD group. The variable is set properly but when I add it to the body, or Invode-RestMethod objects the variable breaks the URL and I am unable to POST my body

$guidfull = Invoke-RestMethod  "$guidurl" -Method 'GET' -Headers $headers > guid.txt
$guidparse = Get-Content guid.txt | Select -First 13 | Select -Last 1 
$guidparse -match "id                : (?<content>.*)" 
$guidmatch = $matches['content']
$guid = $guidmatch

The $guid variable is set here. I am able to see it. When I try and append it to a URL, the URL breaks (the underline dissapears)
$aadowner = "{`n  `"@odata.id`": `"https://graph.microsoft.com/v1.0/users/$guid`"`n}"

Result:  AADWoner Is ----- https://graph.microsoft.com/v1.0/users/d6eaec30-7333-42f8-b31a-c13ad3a4b511
(https://graph.microsoft.com/v1.0/users/ is underlined as a hyperlink but the value is not)

### Issue script & Debug output

```PowerShell
I am writing an action that grabs the object id of an Azure User and adds it as owner of an AD group. The variable is set properly but when I add it to the body, or Invode-RestMethod objects the variable breaks the URL and I am unable to POST my body

$guidfull = Invoke-RestMethod  "$guidurl" -Method 'GET' -Headers $headers > guid.txt
$guidparse = Get-Content guid.txt | Select -First 13 | Select -Last 1 
$guidparse -match "id                : (?<content>.*)" 
$guidmatch = $matches['content']
$guid = $guidmatch

The $guid variable is set here. I am able to see it. When I try and append it to a URL, the URL breaks (the underline dissapears)
$aadowner = "{`n  `"@odata.id`": `"https://graph.microsoft.com/v1.0/users/$guid`"`n}"

Result:  AADWoner Is ----- https://graph.microsoft.com/v1.0/users/d6eaec30-7333-42f8-b31a-c13ad3a4b511
(https://graph.microsoft.com/v1.0/users/ is underlined as a hyperlink but the value is not)
```

### Environment data

```PowerShell
windows-2019 and windows-latest
azure/powershell@v1
```

### Module versions

```PowerShell
azure/powershell@v1
```

### Error output

```PowerShell
No error- just incorrect append
```

**Comment by dingmeng-xue** [comment]
Thanks for contacting us. I haven't got your point. The guid of ADuser is using hyphen. Why do you mean "underline dissapears"?
