### ISSUE TITLE
Invoke-AzRestMethod doesn't throw any confirmation when the -Confirm option is supplied

### ISSUE THREAD

**Issue by jerEspresso** [Azure/azure-powershell#18959]
### Description

When I use `Invoke-AzRestMethod` with the `-Confirm` option to purge key vault, I don't get any confirmation before the API request is executed. However, the [documentation](https://docs.microsoft.com/en-us/powershell/module/az.accounts/invoke-azrestmethod?view=azps-8.1.0) shows it does support the `-Confirm` option.

### Issue script & Debug output

```PowerShell
PS> Invoke-AzRestMethod -Path "subscriptions/$SubID/providers/Microsoft.KeyVault/locations/$ResourceGroupLocation/deletedVaults/$KeyVaultName/purge?api-version=$PurgeApiVersion" -Method POST -Confirm
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.9.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     4.6.0                 Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzKeyVaultKey, Add-AzKeyVaultManagedStorageAccount…}
Script     6.0.1                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
No error, just confirmation being skipped.
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. I think it's a cmdlet design issue that `Invoke-AzRestMethod` should not support `ShouldProcess` or offer parameter `-Confirm`. This cmdlet is for general purpose and allows user to send request directly to Azure. It cannot predict the request will change remote resource or not and what impact will be. We will remove `ShouldProcess` in major release.

**Comment by dingmeng-xue** [comment]
@jerEspresso , we had an internal discussion. We are thinking to check `-confirm` option according to HTTP method. If it is just GET, -confirm is not required. For other cases that cmdlet execution may change remote resource, Invoke-AzRestMethod will check user's confirmation. what's your thought?

**Comment by jerEspresso** [comment]
Hi @dingmeng-xue , it sounds much better than removing `ShouldProcess` for all HTTP methods in `Invoke-AzRestMethod`. Thank you!
