### ISSUE TITLE
Move-AzureRmResource and web apps with app insights

### ISSUE THREAD

**Issue by jamie94bc** [Azure/azure-powershell#1897]
Consider the following where the website has an application insights resource associated:
```powershell
$plan = Get-AzureRmResource -ResourceName MyResource -ResourceGroupName Default-Web-WestEurope
$website = Get-AzureRmResource -ResourceName MyResource -ResourceGroupName Default-Web-WestEurope
Move-AzureRmResource -DestinationResourceGroupName NewGp -ResourceId $plan.ResourceId, $website.ResourceId
```

It will fail with a syntax error (`Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'ResourceId'`) as the ResourceId for the web app is an array, not a string. This is easily worked around (below) but I was wondering if there would be a nicer way to handle scenario as it's not overly clear?

```powershell
Move-AzureRmResource -DestinationResourceGroupName NewGp -ResourceId $plan.ResourceId, $website.ResourceId[0], $website.ResourceId[1]
```

**Comment by markcowl** [comment]
@jamie94bc is there more than one website returned by your get call above?

@vivsriaus Wondering why a resource would return more than one resource id?

**Comment by vivsriaus** [comment]
The Get-AzureRmResource with ResourceName and ResourceGroupName hits the ARM cache, so the returned result is always a list of PSObject (in this case, an array). This is expected.

But that said, I can probably make changes to it to return a PSObject (instead of an array), if the collection has only one item. Would that be the right thing to do here, @markcowl ?

**Comment by vivsriaus** [comment]
cc @ravbhatnagar @rjmax for thoughts

**Comment by vivsriaus** [comment]
Actually, I took a look at it closer and we do enumerate the collection when writing object:
$r = Get-AzureRmResource -ResourceName vivekTest123 -ResourceGroupName vtest
$r.ResourceId

/subscriptions/38b598fc-e57a-423f-b2e7-dc0ddb631f1f/resourceGroups/vtest/providers/Microsoft.Web/serverFarms/vivekTest123

@jamie94bc Can you please confirm if more than one website was returned by your call?

**Comment by ravbhatnagar** [comment]
IMO - The issue here is that when the Get-AzureRmResource command is called using params name and resource group but without the type, it will return the insights component also which has the name as the website. Hence we see an array returned. @jamie94bc - Can you please confirm if this is correct?

**Comment by jamie94bc** [comment]
Yeah I believe that was the issue.



On Wed, Mar 2, 2016 at 1:27 PM -0800, "Gaurav Bhatnagar" <notifications@github.com<mailto:notifications@github.com>> wrote:


IMO - The issue here is that when the Get-AzureRmResource command is called using params name and resource group but without the type, it will return the insights component also which has the name as the website. Hence we see an array returned. @jamie94bc<https://github.com/jamie94bc> - Can you please confirm if this is correct?

-

**Comment by jamie94bc** [comment]
In my case it was due to the auto created application insights resource with the same name as the website.



On Wed, Mar 2, 2016 at 1:27 PM -0800, "Gaurav Bhatnagar" <notifications@github.com<mailto:notifications@github.com>> wrote:


IMO - The issue here is that when the Get-AzureRmResource command is called using params name and resource group but without the type, it will return the insights component also which has the name as the website. Hence we see an array returned. @jamie94bc<https://github.com/jamie94bc> - Can you please confirm if this is correct?

-

**Comment by ravbhatnagar** [comment]
@jamie94bc - Thanks for confirming. Isn't the current behavior expected then?

**Comment by ravbhatnagar** [comment]
Looks like the expected behavior. @jamie94bc - Please open this issue again if you feel otherwise. Thanks!
