### ISSUE TITLE
[Doc]: Get-AzSubscription

### ISSUE THREAD

**Issue by AHallqvist** [Azure/azure-powershell#18974]
### Description

Example 3: Get all subscriptions in the current tenant seems to be missing a parameter:
Get-AzSubscription should be Get-AzSubscription -TenantId

As is now Example 1 and Example 3 gives the same code example, but says they do different things. and show different output.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. `Get-AzSubscription` without additional parameter can list all subscriptions under all available tenants in context. The third example doesn't make sense. We will remove it. If feature of listing all subscriptions under current tenant, please let us know.

**Comment by LucasYao93** [comment]
@dingmeng-xue 
If we add TenantId parameter for example 3. Example 3 will be the same as Example 2.

Doc link: https://docs.microsoft.com/en-us/powershell/module/az.accounts/get-azsubscription?view=azps-8.2.0

**Comment by AHallqvist** [comment]
> @dingmeng-xue If we add TenantId parameter for example 3. Example 3 will be the same as Example 2.
> 
> Doc link: https://docs.microsoft.com/en-us/powershell/module/az.accounts/get-azsubscription?view=azps-8.2.0

No, if you add "-TenantId" it would not be the same. Example 2 is -TenantId "aaaa-aaaa-aaaa-aaaa", my suggestion for what was intended was to add "-TenantId" witout specifying a tenantId, which should default to current. Example 2 wants to specify a tenant besides the current.

**Comment by LucasYao93** [comment]
> 
Understood
We can use below command to list all subscriptions in the current tenant.
```powershell
Get-AzSubscription -TenantId (Get-AzContext).Tenant
```

**Comment by AHallqvist** [comment]
> > 
> 
> Understood We can use below command to list all subscriptions in the current tenant.
> 
> ```powershell
> Get-AzSubscription -TenantId (Get-AzContext).Tenant
> ```

Sounds like that's the proper way, I just wanted to highlight the issue that there was the same code as examples for two different intended functionalities.
