### ISSUE TITLE
[Doc]: Invoke-AzRestMethod: Add example for "name" parameterset

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#18989]
### Description

Missing example for:

```
Invoke-AzRestMethod
      [-SubscriptionId <String>]
      [-ResourceGroupName <String>]
      [-ResourceProviderName <String>]
      [-ResourceType <String[]>]
      [-Name <String[]>]
      -ApiVersion <String>
```

**Comment by dingmeng-xue** [comment]
@VeryEarly , please provide 2 examples. One is for operation to one resource type instance. Another one is for list operation. The size of resource types is larger than the size of names in latter case.
