### ISSUE TITLE
[Doc]: Set-AzKeyVaultAccessPolicy - Example 7, have to use ObjectId, not ServicePrincipalName  

### ISSUE THREAD

**Issue by mbourgon** [Azure/azure-powershell#19007]
### Description

For some reason, I couldn't use the set-azkeyvaultpolicy the way Example 7 does on https://docs.microsoft.com/en-us/powershell/module/az.keyvault/set-azkeyvaultaccesspolicy?view=azps-8.1.0.  specifically, I grabbed the identity thus:

`$identity = Get-AzSqlServer -ServerName myservernamehere
`
but I had to use -ObjectId instead of ServicePrincipalName to update my permissions (mine's slightly different because of the script we're using)

`set-azkeyvaultaccesspolicy -VaultName $keyvault.VaultName -ObjectId $identity.Identity.PrincipalId -PermissionsToKeys wrapkey,unwrapkey,get`

When I tried using serviceprincipal name, i got 
```
set-azkeyvaultaccesspolicy : Cannot find the Active Directory object '' in tenant 'd3eb33a7-d481-41d5-9e13-09a9da72ff2a'. Please make sure that the user or application service principal you are authorizing is registered in the current subscription's Azure Active directory. The TenantID displayed by the cmdlet 'Get-AzContext' 
is the current subscription's Azure Active directory.

```

**Comment by dingmeng-xue** [comment]
Thanks for contacting us. service principal name may not be the same as resource name. So, your script is correct. Example 7 may not good option to you. If you want to find its sp name, you can search that in Azure AD using object's Principalid.

Please let me know if you have further question.

**Comment by mbourgon** [comment]
Thanks for the quick response! My concern was that I had the ID and it really wasn’t obvious where to go from there without doing a lot more reading. I’m trying to prevent the next person from getting frustrated. 

---
