### ISSUE TITLE
New-AzRoleAssignmentScheduleRequest fails on Secure Admin Workstation

### ISSUE THREAD

**Issue by priyankn** [Azure/azure-powershell#19008]
### Description

`New-AzRoleAssignmentScheduleRequest` works totally fine on regular connection, but fails on the SAW device. To limit the sensitive information, I am only sharing the correlation Id here. Feel free to reach out on internal teams if more information is required.

7fbaa4f8-d990-429c-9129-934c566f9b51

### Issue script & Debug output

```PowerShell
PS > $guid = "12f8978c-5d8"
PS > $startTime = Get-Date -Format o
PS > $scope = "/subscriptions/SUB ID"
PS > New-AzRoleAssignmentScheduleRequest -Name $guid -Scope $scope -ExpirationDuration PT1H -ExpirationType AfterDuration -PrincipalId [REDACTED] -RequestType SelfActivate -RoleDefinitionId subscriptions/[SUB ID]/providers/Microsoft.Authorization/roleDefinitions/[ROLE ID] -ScheduleInfoStartDateTime $startTime -Justification "test"
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22000.653
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.653
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
6.0.0 Az.Resources
```

**Comment by dingmeng-xue** [comment]
@priyankn , you can find my email address from my profile. Please send the email and contact us directly.

Due to you cannot share detailed information on github, we will close this one and let us sync offline.
