### ISSUE TITLE
Save-AzureRMProfile should accept pipeline input for Profile parameter

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#1901]
Change Save-AzureRmProfile to accept pipeline input for the Profile parameter.  Consider changing the parameter name to InputObject.

**Comment by cormacpayne** [comment]
[This has been fixed.](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Profile/Commands.Profile/Context/SaveAzureRMContext.cs#L34)
