### ISSUE TITLE
[Doc]: Set-AzResource example

### ISSUE THREAD

**Issue by JohnMiner3** [Azure/azure-powershell#19022]
### Description

https://docs.microsoft.com/en-us/powershell/module/az.resources/set-azresource?view=azps-8.1.0

The second example will not work for all Azure Objects since the $_.Tags property might return a null value.

The PowerShell code below will work since it uses both the list and set cmdlets.

# https://docs.microsoft.com/en-us/powershell/module/az.resources/set-azresource?view=azps-8.1.0

# Resource group and tag values
$Name = "testrg"
$Tags = @{"testkey1" = "testval1"; "testkey2" = "testval2"}

# Apply tags to all objects in the named resource group
$Resources = Get-AzResource -ResourceGroupName $Name 
foreach ($Resource in $Resources) {
    Write-Host $Resource.Name
    Set-AzResource -ResourceId $Resource.ResourceId -Tag $Tags -Force
}

**Comment by dingmeng-xue** [comment]
@JohnMiner3 , thanks for your suggestion. We hope to provide brief example to help user understand the usage of cmdlet. The example cannot cover all corner cases. It makes example wordy when we add more checks. In this case, we just hope user know how to modify common attribute of all resources.
