### ISSUE TITLE
[Eng]: CreateMappings_rules.json should be updated when moving code to main

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#19036]
### Description

https://github.com/Azure/azure-powershell/blob/fdf679c138510c50d4463ca35a1174fd51c68cda/tools/Gen2Master/MoveFromGeneration2Master.ps1#L354

This code should update `CreateMappings_rules.json` file whenever moving a module from generation to main, but it's not, for example https://github.com/Azure/azure-powershell/pull/19031

**Comment by wyunchi-ms** [comment]
Fixed by updating the codegen pipeline.
