### ISSUE TITLE
Get-AzPolicyExemption -Scope <resourceid of a resource> gives subscription exemptions

### ISSUE THREAD

**Issue by BartDecker** [Azure/azure-powershell#19035]
### Description

One can programmatically (ARM) set exemptions on resources instead of subscription & resourcegroups. But Get-AzPolicyExemption doesn't allow to retrieve an exemption on a resource by using:

* in case test24 storage account **has no exemptions** for the resource itself

Get-AzPolicyExemption -Scope "/subscriptions/xxxxxxxxxxeb4299f3f0/resourceGroups/rg-decker/providers/Microsoft.Storage/storageAccounts/test24"

**Gives as output:** all exemption for the subscription. (for subscription scope exemptions)

* in case test24 storage account has an exemption for the resource itself

**Gives as output:** all exemption for the subscription. (for subscription scope exemptions) + the exemption on the test24

### Issue script & Debug output

```PowerShell
-
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.8.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzC… 
Script     6.0.0                 Az.Resources                        {Export-AzResourceGroup, Expo…
```

### Error output

```PowerShell
-
```

**Comment by RakeshMohanMSFT** [comment]
@BartDecker Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@BartDecker It seems to be a service end issue and not client (PowerShell). Can you please check the exemption blade in the portal and see if you see similar issues there as well? https://ms.portal.azure.com/#view/Microsoft_Azure_Policy/PolicyMenuBlade/~/Exemptions
