### ISSUE TITLE
ARM VM & Network Cmdlets Not Showing Debug Messages

### ISSUE THREAD

**Issue by huangpf** [Azure/azure-powershell#1905]
@markcowl @hyonholee and I can reproduce the issue. And it seems only ARM VM & Network cmdlets have the issue. RG & Storage cmdlets are fine. 

This is a vital feature. Please help resolve. Thanks.

**Comment by markcowl** [comment]
@huangpf @hyonholee Fix submitted to dev branch

**Comment by markcowl** [comment]
BTW, here is a workaround as well:
```
Add-Type -Path '<path-to-AzureRm.Compute module directory>\Microsoft.Rest.ClientRuntime.dll'
[Microsoft.Rest.ServiceClientTracing]::IsEnabled = $true 
```

**Comment by hovsepm** [comment]
Fixed in dev branch.
