### ISSUE TITLE
AzureRM.Automation is missing Get-AzureRMAutomationRunbookDefinition

### ISSUE THREAD

**Issue by robplank** [Azure/azure-powershell#1907]
Please add Get-AzureRMAutomationRunbookDefinition to the AzureRM.Automation Module

**Comment by markcowl** [comment]
@robplank Thanks for the report.  Adding the appropriate folks to take a look

@jodoglevy Can you take a look?

**Comment by jodoglevy** [comment]
This is supported via the Export-AzureRMAutomationRunbook cmdlet: https://msdn.microsoft.com/en-us/library/mt603683.aspx
