### ISSUE TITLE
New-AzureRmStorageContainer?

### ISSUE THREAD

**Issue by ronbok** [Azure/azure-powershell#1908]
There are new cmdlets for things like New-AzureRmStorageAccount, but someone forgot to include New-AzureRmStorageContainer.  This is currently a blocker now for creating ARM Storage Accounts via PowerShell.  Even v1.2.2 (3/3/2016) doesn't have it.

**Comment by alexandair** [comment]
`AzureRM.Storage` module contains the cmdlets connected to management of ARM storage accounts. For other storage artifacts you should use cmdlets from `Azure.Storage` module. `New-AzureStorageContainer` should work.

**Comment by markcowl** [comment]
@ronbok Closing, as I suspect Aleksandar has resolved your issue. It is indeed a difference between naming of data cmdlets and management cmdlets.
