### ISSUE TITLE
New-AzUpgradeModulePlan : Cannot validate argument on parameter 'ToAzVersion'. The argument "5.2.0" does not belong to the set "8.0.0"

### ISSUE THREAD

**Issue by SoundaryaDurai** [Azure/azure-powershell#19088]
### Description

When I try to upgrade AzureRM powershell scripts to Az Module by following the steps in https://docs.microsoft.com/en-us/powershell/azure/quickstart-migrate-azurerm-to-az-automatically?view=azps-8.1.0 , I get the following error

New-AzUpgradeModulePlan : Cannot validate argument on parameter 'ToAzVersion'. The argument "5.2.0" does not belong to the set "8.0.0"

### Script or Debug output

```PowerShell
PS C:\Windows\system32> New-AzUpgradeModulePlan -FromAzureRmVersion 6.13.1 -ToAzVersion 5.2.0 -DirectoryPath 'E:\VConnectDeploymentScripts' -OutVariable Plan
New-AzUpgradeModulePlan : Cannot validate argument on parameter 'ToAzVersion'. The argument "5.2.0" does not belong to
the set "8.0.0" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command
again.
At line:1 char:65
+ ... gradeModulePlan -FromAzureRmVersion 6.13.1 -ToAzVersion 5.2.0 -Direct ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzUpgradeModulePlan], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-AzUpgradeModulePlan
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. The latest Az.Tools.Migration targets to Az 8.0.0. Please update your script. We will update online docs. Thanks again.

**Comment by dingmeng-xue** [comment]
PR is raised. Closing this issue. Welcome to contact us if you any issue.

**Comment by SoundaryaDurai** [comment]
Thanks dingmeng-xue. It works after modifying the script like you told.
