### ISSUE TITLE
Set-AzureRmVM's -Redeploy and -Generalized parameters

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#1909]
I have a feeling that the -Redeploy and -Generalized parameters should not be in the same parameter set.

``` PowerShell
PS> Set-AzureRmVM -ResourceGroupName demo-rg -Name rmvm02 -Redeploy -Generalized

set-azurermvm : Operation returned an invalid status code 'Conflict'
StatusCode: 409
ReasonPhrase: Conflict
OperationID : ''
```

**Comment by markcowl** [comment]
@singhkay Can you take a look?  If these parameters are mutually exclusive, we should enforce this with a parameter set for each.

**Comment by singhkay** [comment]
Adding @hyonholee we need to have different parameter sets here

**Comment by cormacpayne** [comment]
Closing as this has been fixed.
