### ISSUE TITLE
Get-AzureRmADApplication report Authentication_MissingOrMalformed in Fairfax

### ISSUE THREAD

**Issue by xmbms** [Azure/azure-powershell#1910]
I could list the AD Applications via Fairfax portal, but Get-AzureRmADApplication always reports Authentication_MissingOrMalformed for my request.

Please take a look at my request details and figure out the root cause.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.windows.net/bee4890a-277b-4803-8ae5-9a71aa452cc8/applications?api-version=1.42-previewInternal

Headers:

Body:

DEBUG: ============== HTTP RESPONSE ==============

Status Code:
Unauthorized

Headers:
ocp-aad-diagnostics-server-name: cFaRmCSyZLgEESPRxCmjd0Wom2vqEwxnfAPoYfWcosA=
request-id                    : 45f6d115-0263-4736-bf11-39f52289995a
client-request-id             : 35ba2d72-5fc4-49a3-9101-2b93763658e2
x-ms-dirapi-data-contract-version: 1.42-previewInternal
Access-Control-Allow-Origin   : *
Duration                      : 738785
Cache-Control                 : private
Server                        : Microsoft-IIS/8.5
WWW-Authenticate              : *********
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET,ASP.NET
Date                          : Mon, 07 Mar 2016 08:21:42 GMT

Body:
{
  "odata.error": {
    "code": "Authentication_MissingOrMalformed",
    "message": {
      "lang": "en",
      "value": "Access Token missing or malformed."
    },
    "values": null
  }
}

Get-AzureRmADApplication :
{"odata.error":{"code":"Authentication_MissingOrMalformed","message":{"lang":"en","value":"Access Token missing or
malformed."},"values":null}}
At line:1 char:1
+ Get-AzureRmADApplication
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmADApplication], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ActiveDirectory.GetAzureADApplicationCommand

**Comment by markcowl** [comment]
@xmbms How are you authenticating when you receive this message?  Also, which version of PowerShell are you using?

**Comment by xmbms** [comment]
It's a bug in January release, and it's fixed after upgrading to the latest March release.

**Comment by markcowl** [comment]
@xmbms closing as fixed.  The updated graph version was expressly added to support this scenario in government cloud.
