### ISSUE TITLE
[Feature]: Az.App powershell module - enable/disable single container app for Dapr

### ISSUE THREAD

**Issue by larswurm** [Azure/azure-powershell#19114]
### Description of the new feature

I am using Az.App powershell module version: 0.1.0 as in:
CommandType     Name                                               Version    Source
------------------------------------------------------------------------------
Function                various cmdlets                                0.1.0      Az.App

I am able to "enable" a container app for DAPR usage without problems given the functionality of the module. However: I cannot "disable" the usage of DAPR for existing container app. Even though property DaprEnabled of a given container is specified as {get:set} I cannot process that configuration change using update-azcontainerapp as in below example:

$app = get-azcontainerapp -Name mycontainerapp -ResourceGroupName mytargetrg
$app.DaprEnabled
True
$app.DaprEnabled = $false
update-azcontainerapp -InputObject $app -Location westeurope
$app = get-azcontainerapp -Name mycontainerapp -ResourceGroupName mytargetrg
$app.DaprEnabled
True

Same if I use the cmdlet update-azcontainerapp with parameter -DaprEnabled - it does not allow for a switch $true / $false statement. Please advice if bug or missing functionality.

### Proposed implementation details (optional)

Either add a parameter to update-azcontainerapp, named something like: -DaprDisabled, change it into a switch parameter allowing for $true / $false, or / and - process the properties that were changed of a given container app as-in example provieded.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Due to `-DaprEnabled` is a switch parameter, could you try `-DaprEnabled:$false`?
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.2#:~:text=%2DMySwitch%3A%24boolValue

**Comment by larswurm** [comment]
Thanks for enlightening me @dingmeng-xue - yes, worked as intended with -DaprEnabled:$false
