### ISSUE TITLE
Unsupported API Dns Resolver

### ISSUE THREAD

**Issue by aggerritsen** [Azure/azure-powershell#19119]
### Description

Hi,

(see also https://github.com/MicrosoftDocs/azure-docs/issues/96533)

When trying to create a DNS resolver with Powershell Module Az.DnsResoler v 0.2.1 I get this error: 

New-AzDnsResolver_CreateExpanded: No registered resource provider found for location 'westeurope' and API version '2022-07-01' for type 'dnsResolvers'. The supported api-versions are '2020-04-01-preview'. The supported locations are 'westcentralus, eastus2, westeurope, northeurope, australiaeast, uksouth, southcentralus, eastus, northcentralus, westus2, westus3'.

How do I register the correct API version? The follwing statement does not change anything:
_$res = Register-AzResourceProvider -ProviderNamespace Microsoft.Network -ApiVersion '2022-07-01'
$res.resourcetypes | Where-Object -property ResourceTypeName -like -value "dnsResolvers_"
Results in:
_ResourceTypeName : dnsResolvers
Locations        : {West Central US, East US 2, West Europe, North Europe…}
ApiVersions      : {2020-04-01-preview}_

Tested in both Poweshell 5, as well as Powershell Core 7.2

Thanks in advance

### Issue script & Debug output

```PowerShell
PS> New-AzDnsResolver `
        -Name $ResolverName `
        -ResourceGroupName $ResourceGroupName `
        -Location $Location `
        -VirtualNetworkId $vNet.id
```

### Environment data

```PowerShell
$PSVersionTable                                                                                         

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
get-module az.dnsresolver -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.2.1      Az.DnsResolver                      {Get-AzDnsForwardingRuleset, Get-AzDnsForwardingRulesetFor...
```

### Error output

```PowerShell
New-AzDnsResolver : No registered resource provider found for location 'westeurope' and API version '2022-07-01' for type 'dnsResolvers'. The supported api-versions are '2020-04-01-preview'. The
 supported locations are 'westcentralus, eastus2, westeurope, northeurope, australiaeast, uksouth, southcentralus, eastus, northcentralus, westus2, westus3'.
At line:3 char:5
+     New-AzDnsResolver `
+     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ SubscriptionI...1.DnsResolver }:<>f__AnonymousType10`6) [New-AzDnsResolver_CreateExpanded], Exception
    + FullyQualifiedErrorId : NoRegisteredProviderFound,Microsoft.Azure.PowerShell.Cmdlets.DnsResolver.Cmdlets.NewAzDnsResolver_CreateExpanded
```

**Comment by SaurabhSharma-MSFT** [comment]
@aggerritsen I could see the same behavior and checking internally on this issue.

**Comment by SaurabhSharma-MSFT** [comment]
@aggerritsen I have got the confirmation that he API version ‘2022-07-01’ is not ready yet. This will be the GA version of managed resolver once it is announced. Most probably this month end or beginning of the next month.
Product team is working internally with with the powershell team to remove the 0.2.1 PS version from PSGallery which is using the ‘2022-07-01’ API version. This will prevent other customers also from getting the same error.
Meanwhile, the mitigation is to uninstall 0.2.1 PS version and install 0.2.0 PS version instead. Please let me know if any questions.

**Comment by aggerritsen** [comment]
Hi Saurabh. OK. That worked well. Thx
I'll be looking forward to see this in GA soon.

Kind regards, Arjen
