### ISSUE TITLE
[Doc]: Construct Hash table into EnvironmentVariable

### ISSUE THREAD

**Issue by wilbertduenk** [Azure/azure-powershell#19182]
### Description

Constructed the following Hash table to use as EnvironmentVariable:

`$envVars = @{
               AZP_URL        = "https://dev.azure.com/TestProject/";
               AZP_TOKEN_FILE = "/azp/.token";
               AZP_POOL       = "IaCS Container Agent Pool";
               AZP_AGENT_NAME = "testagent"
             }`

However after creating $container with:
`$container = New-AzContainerInstanceObject 
                 -Name "testagent" 
                 -Image "apa_ubuntu:latest" 
                 -RequestCpu 1 
                 -RequestMemoryInGb 2 
                 -EnvironmentVariable $envVars`

And checking with 
`$container.EnvironmentVariable`

I conclude that no Environment Variables are put in the container. 

PS C:\Users\xxx\xxx\xxx> $container.EnvironmentVariable 

Name SecureValue Value
---- ----------- -----

Is it possible to get an working example for this and to tell me what i did wrong?

**Comment by dingmeng-xue** [comment]
Thanks for reporting. `New-AzContainerInstanceObject` is a cmdlet for constructing in-memory object which will be used for resource creation or update.  So, you need to call New-AzContainerGroup to create resource on Azure. Here is one example https://docs.microsoft.com/en-us/powershell/module/az.containerinstance/new-azcontainergroup?view=azps-8.2.0#example-1-create-a-container-group-with-a-container-instance-and-request-a-public-ip-address-with-opening-ports

**Comment by wilbertduenk** [comment]
Usage of New-AzContainerInstanceEnvironmentVariableObject (Example 2) instead of a simple hashtable did the trick. Thank you very much! Maybe give people a heads up about this in https://docs.microsoft.com/en-us/powershell/module/az.containerinstance/new-azcontainerinstanceobject?view=azps-8.2.0 ?

**Comment by dingmeng-xue** [comment]
It's a limitation that we haven't create relationship between in-memory object and other cmdlet. So, it's not to user to know their relationship. We will improve it in near future.
