### ISSUE TITLE
Cannot update PublicNetworkAccess flag in Update-AzMySqlServer command

### ISSUE THREAD

**Issue by vibangadeveloper** [Azure/azure-powershell#19189]
### Description

Hi team, I was checking the commands for Azure SQL, Azure Postgress and storage and all of them has an option to change the PublicNetworkAccess however for [Az.MySql](https://docs.microsoft.com/en-us/powershell/module/az.mysql/?view=azps-8.2.0) module, the command Update-AzMySqlServer that updates the server parameters does not expose that as an input parameter. We are writing Azure automation PowerShell scripts for Azure database for MYSQL and got stuck because this feature is not available. Does the engineering team have any timelines as when can this feature be released

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will look into it.

**Comment by vibangadeveloper** [comment]
Hi MSFT, Can you help with an update if there is any roadmap planned for this feature so that we can plan our automation releases accorindlgy

**Comment by dingmeng-xue** [comment]
@vibangadeveloper , for the time being, we plan to update module in September. If everything goes well, the module will be ready in mid of October.

**Comment by dingmeng-xue** [comment]
Close this issue. The fix will be available on Oct 12.
