### ISSUE TITLE
[Feature]: New-AzFunctionApp should support creating Node 18 (preview) function apps

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-powershell#19184]
### Description of the new feature

Related to https://github.com/Azure/azure-functions-nodejs-worker/issues/562

Node 18 is ready to be shown as a Preview stack for functions

### Proposed implementation details (optional)

Example PRs I did for stacks API: 
- Preview & Hidden PR was already merged: https://github.com/Azure/azure-functions-ux/pull/6752
- Removing Hidden flag should be merged soon: https://github.com/Azure/azure-functions-ux/pull/6805

**Comment by Francisco-Gamino** [comment]
This issue has been fixed.
