### ISSUE TITLE
Connect-AzureAD BADrequest 400

### ISSUE THREAD

**Issue by tkudya** [Azure/azure-powershell#19187]
Recent issue with Connect Az-Accounts -credential. I have been getting the following error message below
![image](https://user-images.githubusercontent.com/78653328/183607853-18f7f3c0-2e83-4733-bf60-82d637d6c894.png)

Any ideas on how to resolve this?

**Comment by dingmeng-xue** [comment]
@tkudya , thanks for reporting. Could you check your admin whether tenant still allows user name + password login? If yes, please turn on the debug log with setting `$DebugPreference = "Continue"` and share log to us. In addition, please share version of Az.Accounts.

**Comment by tkudya** [comment]
Please see attached
[logs.txt](https://github.com/Azure/azure-powershell/files/9306987/logs.txt)

Module is 2.9.1

**Comment by tkudya** [comment]
That's fixed now. it was TLS 1.2 we were just missing one registry key

**Comment by dingmeng-xue** [comment]
Thanks for information. I'm closing this issue now.
