### ISSUE TITLE
[Doc]: Pretask/Posttask documentation for New-AzMaintenanceConfiguration

### ISSUE THREAD

**Issue by paul-e-martin** [Azure/azure-powershell#19193]
### Description

The pre/post task documentation is a little lacking on how runbooks are passed through via PowerShell.
Please could this be expanded upon.

https://docs.microsoft.com/en-us/powershell/module/az.maintenance/new-azmaintenanceconfiguration?view=azps-8.2.0

**Comment by navba-MSFT** [comment]
@paul-e-martin Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
