### ISSUE TITLE
Print out nested template status for New-AzureResourceGroupDeployment

### ISSUE THREAD

**Issue by clamanna** [Azure/azure-powershell#192]
If a template is submitted to New-AzureResourceGroupDeployment, and it has a included / nested template, the cmdlet does not show the status of the indivdiual resources of that underlying template. 

That means if the nested template is particularly big (e.g. 10 VMs or 100 SQL databases), the PoSH window hangs on just the "Nested Template" step for a long time without feedback. 

We expect that developers are going to want to use nested templates quite often for better code organization and reuse.  It follows that they will want better feedback while these are being deployed.  

Would it be possible for the powershell commandlets to show the output from the nested deployment along with the output from the root deployment?

**Comment by markcowl** [comment]
@clamanna  Thanks for the ffedback.  Assigning to the appropriate team for triage (yours, I believe :-)

**Comment by vivsriaus** [comment]
fixed
