### ISSUE TITLE
Command-not-found handler shows up at the wrong time

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#19228]
### Description

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/11371776/184586974-9bec3a8d-40df-4860-8913-415c61fa2907.png)

In the above screenshot, ARM returned an error that the resource group cannot be found, but somehow the logic of Discoverability was triggered. A meaningless and incorrect warning message was displayed.

### Expected behavior 
The warning message does not show up.

### Issue script & Debug output

```PowerShell
Get-AzImageBuilderTemplate -ResourceGroupName NotExist
```

### Environment data

```PowerShell
N/A
```

### Module versions

```PowerShell
N/A
```

**Comment by dingmeng-xue** [comment]
@isra-fel , could you explain further about this issue?

**Comment by isra-fel** [comment]
@dingmeng-xue , I've updated the title and description.

**Comment by dingmeng-xue** [comment]
Can it be fixed in this release?

**Comment by isra-fel** [comment]
Not sure. We haven't found the root cause. Besides, it only affects _some_ parameters in _some_ autorest-based modules.

**Comment by isra-fel** [comment]
Customer reporting issues:
https://github.com/Azure/azure-powershell/issues/20442
https://github.com/Azure/azure-powershell/issues/20599

Consider work-around: filtering out names with an underscore
