### ISSUE TITLE
How to delete ACR image using Az Powershell

### ISSUE THREAD

**Issue by younjinsong** [Azure/azure-powershell#19232]
### Description

How can I delete a specific image/tag of an ACR repo, using Az Powershell?

I'm not able to find clear descriptions here https://docs.microsoft.com/en-us/powershell/module/az.containerregistry/?view=azps-8.2.0#container-registry.

There is Remove-AzContainerRegistryTag to untag, Remove-AzContainerRegistryRepository to remove the entire repo, etc. but I cannot find a way to remove just a single image.

**Comment by dingmeng-xue** [comment]
@younjinsong thanks for contacting us. The identity of image used in ACR is manifest. Please try this cmdlet [Remove-AzContainerRegistryManifest](https://www.powershellgallery.com/packages?q=Cmdlets%3A%22Remove-AzContainerRegistryManifest%22)
