### ISSUE TITLE
AZ Powershell 8.2.0 - Unpublish-AzCdnEndpointContent 

### ISSUE THREAD

**Issue by c9mb** [Azure/azure-powershell#19241]
### Description

I was pushed to use Az Powershell to purge content from some Cdn Endpoints, because the Portal is currently broken for that, and has no ETA because it's 'cosmetic' with a workaround of using Powershell.

So, I installed Az Powershell, and ended up with v8.2.0 on my W10 PC running Powershell 5.1

However... the cmdlet I was expecting to use - Unpublish-AzCdnEndpointContent - is not there

What is the correct solution for this now?

**Comment by ChenglongLiu** [comment]
I think this is what you need https://learn.microsoft.com/en-us/powershell/module/az.cdn/clear-azcdnendpointcontent?view=azps-8.3.0

```Powershell
Clear-AzCdnEndpointContent -ResourceGroupName testps-rg-da16jm -ProfileName cdn001 -EndpointName endptest001 -ContentPath @("/movies/*","/pictures/pic1.jpg")
```

**Comment by TracyYaoYao** [comment]
@c9mb, thanks for your feedback, we have created a PR to update the migration guide docs. https://github.com/Azure/azure-powershell/pull/22779
