### ISSUE TITLE
AZ Module gets not loaded [8.2.0]

### ISSUE THREAD

**Issue by Petri-X** [Azure/azure-powershell#19246]
### Description

Hi there,
I have saved MicrosoftGraph and AZ modules to my computer, copied them into modules folder, but only graph is working.

When I try to import AZ module is complains:
```
Import-Module : The specified module 'Az.Accounts' with version '2.9.1' was not loaded because no valid module file was found in any module directory.
At C:\Program Files\WindowsPowerShell\Modules\AZ\Az\8.2.0\Az.psm1:120 char:5
+     Import-Module Az.Accounts -MinimumVersion 2.9.1 -Scope Global
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Az.Accounts:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleWithVersionNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

etc..
```

Both of them are done in same way:
..WindowsPowerShell\Modules\AZ\Az
..WindowsPowerShell\Modules\AZ\Az.Accounts
..WindowsPowerShell\Modules\AZ\Az.Aks
etcc..

And graph:
..WindowsPowerShell\Modules\MicrosoftGraph\Microsoft.Graph
..WindowsPowerShell\Modules\MicrosoftGraph\Microsoft.Graph.Applications
..WindowsPowerShell\Modules\MicrosoftGraph\Microsoft.Graph.Authentication

Have I done something differently with Graph? Or does anybody have thoughts what might go wrong on this?

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        Az                                  {Preload-Assembly, Test-DotNet}
```

**Comment by erick-prosimo** [comment]
I hit this today with an Azure Deployment Script. The script was working, and now suddenly it is not.

**Comment by dingmeng-xue** [comment]
@Petri-X , my understanding is module is under the root folder of `...\WindowsPowerShell\Modules\`. Please look into the result of below script. If you cannot see Azure PowerShell module, it means PowerShell cannot detect module and import them. Please share the result to us if you need further assistance.
```
get-module * -ListAvailable
```

**Comment by Petri-X** [comment]
@dingmeng-xue 
But do you have any clue why Microsoft.Graph is working so that all of its modules are in one folder:
`...\WindowsPowerShell\Modules\MicrosoftGraph\..,` but when I do the same with AZ, that is not working. Somehow I was expecting some commonality on here. And other reason was to keep the main `..\Modules\..` folder nice and clean.

@erick-prosimo 
If I try to load the Az.Accounts alone, I'm getting the following warning into Event Log:

```
Log Name:      Microsoft-Windows-PowerShell/Operational
Source:        Microsoft-Windows-PowerShell
Event ID:      4100
Task Category: Executing Pipeline
Level:         Warning
Keywords:      None
Description:
Error Message = Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Fully Qualified Error ID = System.Reflection.ReflectionTypeLoadException,Microsoft.PowerShell.Commands.AddTypeCommand


Context:
        Severity = Warning
        Host Name = ConsoleHost
        Host Version = 5.1.19041.1682
        Host ID = 67f3a928-2cd2-4346-b86e-5df86bd653cd
        Host Application = C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        Engine Version = 5.1.19041.1682
        Runspace ID = bfb3686c-0feb-46a7-9717-db605422323f
        Pipeline ID = 26
        Command Name = Add-Type
        Command Type = Cmdlet
        Script Name = C:\Program Files\WindowsPowerShell\Modules\AZ\Az.Accounts\2.9.1\Az.Accounts.psm1
        Command Path = 
        Sequence Number = 19
        Connected User = 
        Shell ID = Microsoft.PowerShell
```

But I will take a look the links you shared, if there is something which could explain this. I just can't find the differences between MicrosoftGraph and Az modules.

**Comment by dingmeng-xue** [comment]
@Petri-X  What's the output of `$env:PSModulePath -split ';'`?

**Comment by Petri-X** [comment]
@dingmeng-xue 
Here us output:
```
C:\Users\userName\Documents\WindowsPowerShell\Modules
C:\Program Files\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell
C:\Program Files\Common Files\Skype for Business Server 2015\Modules\
```

And before you say that Az.* modules must be directly under `...\Modules\Az.*...` I still would like to understand why e.g. Graph does not work like that, it can find the modules from subfolders:
```
PS C:\> Get-Module -ListAvailable Microsoft.Graph.mail

    Directory: C:\Program Files\WindowsPowerShell\Modules\MicrosoftGraph

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.11.0     Microsoft.Graph.Mail                {Get-MgUserInferenceCl
```

See:
    Directory: C:\Program Files\WindowsPowerShell\Modules\MicrosoftGraph

**Comment by dingmeng-xue** [comment]
The behavior is weird. I created question https://github.com/PowerShell/PowerShell/issues/17919 to PowerShell. Let's see their response.

**Comment by kilasuit** [comment]
@Petri-X This difference in the Graph Module vs AZ is caused by the differences in the Required Modules in the psd1 of each of these metamodules.

I have previously pointed this out on a number of occasions when discussing packaging with the Az PowerShell team over the years, but alas this point (and a number of other ones too) hasn't been taken into consideration.

To fix this @dingmeng-xue the publishing process for Az **needs** to populate that entry in the psd1 of the Az Module. I would also **strongly** advise that this is also populated in all the other sub modules that make up Az PowerShell too.

**Comment by Petri-X** [comment]
Hi @kilasuit 
Big thanks to share this finding. But are you sure that is actually should solves the issue? I take a look and rewrite that by my our own:
```
RequiredModules = @(@{ModuleName = 'Az.Accounts'; RequiredVersion = '2.9.1'; }, 
               @{ModuleName = 'Az.Advisor'; RequiredVersion = '1.1.2'; }, 
               @{ModuleName = 'Az.Aks'; RequiredVersion = '4.2.1'; }, 
               etc. . .
```

But still end to the same results (example):
`Import-Module : The specified module 'Az.Accounts' with version '2.9.1' was not loaded because no valid module file was found in any module directory.`

And for the RequiredModules, did you noticed that they are loading those manually in **Az.psm1** (from line 122):
```
Import-Module Az.Advisor -RequiredVersion 1.1.2 -Global
Import-Module Az.Aks -RequiredVersion 4.2.1 -Global
etc. . .
```
And of course that is not working, as those modules are not found.

So I believe the original question is still valid, what Microsoft.Graph does differently?

**Comment by dingmeng-xue** [comment]
@kilasuit , do you still remember where I can find previous discussion? I recollect it was due to compatibility issue. It is worth of visiting it again after years.

**Comment by kilasuit** [comment]
Apologies on the delayed response 
@Petri-X - If I remember correctly without testing this (which I am gonna do over the next few days/week) I believe this is due to how the module analysis cache works in PowerShell which unfortunately is not properly documented, however I have seen similar issues many times before in my time with PowerShell. Let me do some testing & get back to you on this for sure, with recommended mitigation going forward.

@dingmeng-xue - it was via many PGI calls and some in person feedback at Ignite 2019 and previous MVP Summits. It hasn't in some ways helped that there has never been a solid recommended best practice in the data that a module manifest **should** contain for best use in the PowerShell Gallery & when installed on your machines. I started some of this investigation end of 2016 / early 2017 and then had to leave it for far too long and haven't yet really got back to it. I will get this completed and hope to get at least some draft documents in flow by end of next week but will come back to this issue and the one in the PowerShell repo and update them both as I go through investigations

**Comment by kilasuit** [comment]
> And for the RequiredModules, did you noticed that they are loading those manually in Az.psm1 (from line 122):

Yes, I had also recommended against this a few times, also along with how this module is packaged and installed for performance reasons from the PowerShell Gallery - again based on research I did in 2016 when it was AzureRm and the PowerShell Gallery was new to us.

**Comment by vidai-msft** [comment]
@Petri-X I performed following steps but saw both modules were not loaded.
1. Found a clean machine where neither of these modules was previously installed
2. Ran command `Save-Module -Name Az -Path C:\WindowsPowerShellModules\AZ -Repository PSGallery`
3. Ran command `Save-Module -Name Microsoft.Graph -Path -Path C:\WindowsPowerShellModules\MicrosoftGraph -Repository PSGallery`
4. Copied folders `AZ` and `MicrosoftGraph` into **C:\Program Files\WindowsPowerShell\Modules**

Although `Microsoft.Graph` module was discoverable after a short while after running `Get-Module -ListAvailable`, I was not able to load the module with `Import-Module` command. For the `Az` module, it was neither discoverable nor importable.

Please let me know if anything missing in above steps and how you tried to import the modules.

**Comment by Petri-X** [comment]
Hi @vidai-msft 
I'm sorry, it took a bit time until I got a blank machine to troubleshooting this more as well.

After step 4 you do not need to use `import-module` but just run the command: `Connect-AzAccount` or `Connect-Graph`. When those modules are available, then PS is enough cleaver to use the depended modules.

But now I have found the way how to get this solved, and I'm not sure if this is bug or has this been done by purposely.

When you copy the AZ under modules that doesn't work. When I compared AZ and Microsoft.Graph I could found only two differences:
**Signature**: Microsoft.Graph have scripts signature in a separate file (.P7S) when Az have them inside .PSD1 files.
Can I get drums?? The other difference was the 
**Folder name!**: `Az` vs. `Microsoft.Graph`

So, when I renamed the folder from "Az" to "Az.bug" (it doesn't matter what do you have after dot, or it could be also Microsoft.Az) and then run a command:
`Get-Module -ListAvailable -Refresh` 
That command updates the file: **ModuleAnalysisCache** on path:
`%localappdata%\Microsoft\Windows\Powershell`
When the command eds, it listed all of the Az modules, and after that I was also able to call `Connect-AzAccount`.

I have no idea, if this is expected behavior on PS or not? Does anybody knows? But for me this actually explains why I have had troubles with the modules earlier which have not been working as expected.

It might be not so common, but at least I'm not wishing to put everything into one basket (directory). I still would like to see the hierarchy, even that might not have benefits for the system :)

**Comment by vidai-msft** [comment]
@Petri-X Thanks for your efforts and great to know you have found the workaround. 😃 I also noticed the issue only happens on Windows PowerShell but not reproducible on PowerShell core. If possible, you can consider switching to the core version which supports cross-platforms. 
Please let us know if you have any further questions or concerns.

**Comment by Petri-X** [comment]
@vidai-msft 
Yes, that might be the next step. :)
But there are some services needing still 5.1.

And btw, the solution is not the "dot", but the length of the folder. It is just enough if the folder is having three or more characters.
