### ISSUE TITLE
Set-AzureRmVMSourceImage should have an option to take PSVirtualMachineImageDetail as a parameter

### ISSUE THREAD

**Issue by vors** [Azure/azure-powershell#1924]
There is cmdlet `Get-AzureRmVMImage`. It returns objects of type `PSVirtualMachineImageDetail`.
There is cmdlet `Set-AzureRmVMSourceImage` that takes the same parameters (`PublisherName`, `Offer`, `Skus`, `Version`), but doesn't have a ParameterSet that takes `PSVirtualMachineImageDetail`.

One of the strong sides of PowerShell is ability to re-use result of one command in another command.
Currently, there is no such option for this two related commands.

**Comment by singhkay** [comment]
Thanks @vors!

 @hyonholee Looks like a parameter set is in order

**Comment by maddieclayton** [comment]
Closing. Please reopen this issue if it is still an issue in the most recent version.
