### ISSUE TITLE
[Doc]: Placeholders for Parameter Description

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#19253]
### Description

Doing a search of "{{ Fill" in our codebase results in about **100 placeholders for parameter description in 69 files**. They should be replaced with real descriptions.

[Here's the search.](https://cs.github.com/?q=repo%3AAzure%2Fazure-powershell+path%3A%2Fsrc%2F**%2F*.md+%22%7B%7B+Fill%22&p=1&pt=5f248335d6fa15e52b0f0d9b3561130349d12c453e778b70acea4a6b637701139cbcbbcfdfd2a618e13238d6e5fb6138e2b398d587a56a1cade3c7efb56241481ef76caa3f8b070464a2980298997acff2f506b992d8a1db2e7f344cd0450be86080ae018862fc41a6d5199e813099fc5c1ded1eb848126c9413a2c8d82359b9c616411a520c5d867ea3826c6b0502044a7544ed7afda7a695323ec26d0dfe06d33a53e41934f23f85508280de6f8898b7a34fa8d4a8806b78d22b9ab89451024d0fa51ac9f7f4f24cc3bc51c8e54741ab2b55e01ebb3519106387382727de918a774d5af46a161c3d6fe6d8bafcb64214daa432ef9d35bd77349b0f34f0587e95a77cc5ba08d87bc7c46405bc5bf21d31ed23ba&scope=&scopeName=All+repos)

Here's an example:
![image](https://user-images.githubusercontent.com/11371776/185025338-9074eda3-c40d-47ad-ba8c-cb83d85b5886.png)

**Comment by dingmeng-xue** [comment]
I will spilt the issues and send them to service team.

**Comment by jaylabell** [comment]
The resource docs need an update for New-AzRestorePoint. 

We will update.

**Comment by jaylabell** [comment]
Updates, will soon be made to the following documentation:
https://learn.microsoft.com/en-us/powershell/module/az.compute/new-azrestorepoint?view=azps-9.1.0#-location

Thank you for calling out @isra-fel

**Comment by Drewm3** [comment]
Moving Jayla's issues over to me.

**Comment by Drewm3** [comment]
this has been fixed.
