### ISSUE TITLE
AzureChina: Get-AzureRmVirtualNetwork command failed

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#1927]
Hi,

Please look into this. This is blocking many implementations for a customer!

PS C:\Windows\system32> **Get-AzureRmVirtualNetwork**
Get-AzureRmVirtualNetwork : The resource namespace 'Microsoft.Network' is invalid.
At line:1 char:1
+ Get-AzureRmVirtualNetwork
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmVirtualNetwork], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkCommand

Thanks,
Pradebban Raja

**Comment by markcowl** [comment]
@DeepakRajendranMsft Can you take a look?

**Comment by DeepakRajendranMsft** [comment]
Compute and Network RPs are not available in AzureChina

**Comment by Pradebban** [comment]
@DeepakRajendranMsft , what does that mean. It will never be available in AzureChina ?
Where is this documented?

**Comment by markjbrown** [comment]
This issue is duplicated in #1928
