### ISSUE TITLE
AzureChina:  New-AzureRmVirtualNetwork command failed

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#1928]
Hi,

Please look into this issue. Also please provide estimates as this is waiting on customer.

PS C:\Windows\system32> **New-AzureRmVirtualNetwork** -Name pradebban -ResourceGroupName pradebban -Location "China East"
New-AzureRmVirtualNetwork : The resource namespace 'Microsoft.Network' is invalid.
At line:1 char:1
+ New-AzureRmVirtualNetwork -Name pradebban -ResourceGroupName pradebban -Location ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVirtualNetwork], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkCommand

Thanks,
Pradebban Raja

**Comment by markcowl** [comment]
@DeepakRajendranMsft can you take a look?

**Comment by DeepakRajendranMsft** [comment]
Compute and Network RPs are not available in AzureChina

**Comment by Pradebban** [comment]
@DeepakRajendranMsft , what does that mean. It will never be available in AzureChina ?
Where is this documented?

**Comment by DeepakRajendranMsft** [comment]
Hi @Pradebban , we are working on enabling the RPs in AzureChina. It should be coming in soon

**Comment by Pradebban** [comment]
Hi @DeepakRajendranMsft , Please let me know if you have any timelines. This would help to plan implementations.

**Comment by markjbrown** [comment]
@Pradebban please contact me via GitHub email.
