### ISSUE TITLE
Set-AzureRmVMSqlServerExtension : KeyVaultCredentialSettings options not supported

### ISSUE THREAD

**Issue by MasayukiOzawa** [Azure/azure-powershell#1929]
The https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-sql-server-azure-key-vault-integration-resource-manager/,

"Get-AzureRmVM -ResourceGroupName $ rgName -Name $ vmName | Set-AzureRmVMSqlServerExtension -KeyVaultCredentialSettings $ akvs | Update-AzureVM"

It is written
but, ARM cmdlets, KeyVaultCredentialSettings is not supported and can not be executed

**Comment by markcowl** [comment]
@akromm Adam, can you make sure an appropriate person on the SQL team takes a look?

**Comment by OJDUDE** [comment]
Hello,
I will be making an update to add this to the RM version of the cmdlets.

**Comment by cormacpayne** [comment]
Closing this issue as it appears to have been fixed.

@MasayukiOzawa please feel free to reopen this issue if this is still a problem.
