### ISSUE TITLE
Multiple subscription with same name - Issue with Get-AzSubscription

### ISSUE THREAD

**Issue by mlomat** [Azure/azure-powershell#19295]
### Description

Azure is allowing multiple subscriptions with this same name. Currently, cmdlet Get-AzSubscription -SubscriptionName "some name" will return some random first sub with name "some name" even you have mutliple subscriptions. In my opinion, it should throw exception that we have more than one sub with this name or return them all. If we want to keep it as it is, it should at least return Enabled subscription, because currently it's probably enumerating in alphabetic order by state and in case there is sub with same name disabled, cmdlet will return disabled sub instead of active one. 

### Issue script & Debug output

```PowerShell
public override void ExecuteCmdlet()
        {
            if (!string.IsNullOrWhiteSpace(this.SubscriptionName))
            {
                IAzureSubscription result;
                try
                {
        This line is giving only one subscription     -->       if (!this._client.TryGetSubscriptionByName(TenantId, this.SubscriptionName, out result))
                    {
                        ThrowSubscriptionNotFoundError(this.TenantId, this.SubscriptionName);
                    }

                    WriteObject(new PSAzureSubscription(result));
                }
                catch (AadAuthenticationException exception)
                {
                    ThrowTenantAuthenticationError(TenantId, exception);
                    throw;
                }
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.9.1                 Az.Accounts
```

**Comment by mlomat** [comment]
[#81bab9e6322c1e213b79e53e1a64051fe2ef5e1d](https://github.com/Azure/azure-powershell/commit/81bab9e6322c1e213b79e53e1a64051fe2ef5e1d)

**Comment by dingmeng-xue** [comment]
Thanks for reporting. IMHO, it makes sense that `Get-AzSubscription -SubscriptionName` returns all subscriptions according to its name no matter it is enabled or disabled. Then user can leverage PowerShell script to filter the result according to requirement. It is aligning with behavior of `Get-AzSubscription` 

What's your thought?

**Comment by mlomat** [comment]
@dingmeng-xue Yep - agree 100% especially that if you execute command without -SubscriptionName, it's giving you all subscriptions. Only exception is -SubscriptionId, because guid should be always unique.
