### ISSUE TITLE
How to securely upload file to Azure Blob Store?

### ISSUE THREAD

**Issue by quoctruong** [Azure/azure-powershell#1930]
Hi, currently I'm using Set-AzureStorageBlobContent to upload file to my blobstore. How secure is this cmdlet? Is it possible to check that the file uploaded is not tampered with in anyway?

**Comment by EmmaZhu** [comment]
@quoctruong The blob are uploaded in chunks, each has a content MD5 that Azure Storage Service can validate chunk content with it. This can make sure each chunk uploaded is the same with the one in local.

**Comment by EmmaZhu** [comment]
@quoctruong 
You can specify to use https protocol to make transfer more secure like following:
`$ctx = New-AzureStorageContext -Protocol Https -StorageAccountName *** -StorageAccountKey ***`
`Set-AzureStorageBlobContent -File "sourcefilepath" -Container "containername" -Blob "blobname" -Context $ctx`

**Comment by blueww** [comment]
Close the issue as has already provided the workaround, and not receive any feedback for a long time.
Feel free to reopen if necessary.
