### ISSUE TITLE
Name validation works differently than Azure Portal

### ISSUE THREAD

**Issue by savas-guven** [Azure/azure-powershell#19317]
### Description

The Utility has a RegEx like this: @"^[0-9a-zA-Z_-]*$";

Which prevents some characters allowed in the Azure Portal for BlueprintAssignments.
On the azure portal, you can give names with "." in it. While Az.Blueprint calls disallow this.

i.e. Set-AzBlueprintAssignment -Name "Whatever.1" 

would fail as the name fails validation; Same Name can be applied through the Azure Portal

While debugging why an existing assignment we created through portal was not being updated we found this discrepancy between how the portal Assignment Names work vs. Powershell.

It would be nice to fix this discrepancy.

### Issue script & Debug output

```PowerShell
-
```

### Environment data

```PowerShell
-
```

### Module versions

```PowerShell
-
```

### Error output

```PowerShell
-
```

**Comment by savas-guven** [comment]
https://github.com/Azure/azure-powershell/blob/4668bff1cc4ed6510d9b0d4c6ec289ab27f04241/src/Blueprint/Blueprint/Cmdlets/BlueprintAssignment/SetAzureRMBlueprintAssignment.cs#L92

**Comment by PramodValavala-MSFT** [comment]
@savas-guven Thanks for the feedback! Apologies for the delay here. We will review and update accordingly.
