### ISSUE TITLE
[Doc]: Missing examples for New-AzContainerAppManagedEnv - configuration examples should be added

### ISSUE THREAD

**Issue by larswurm** [Azure/azure-powershell#19329]
### Description

The docs: https://docs.microsoft.com/en-us/powershell/module/az.app/new-azcontainerappmanagedenv?view=azps-8.2.0 - for cmdlet New-AzContainerAppManagedEnv is limited - where as it should contain examples for switching a networking setup (Accept traffic from everywhere / Limited to VNet / Limited to Container Apps Environment). Since we are trying to use the POSH cmdlets to control deployments of Environments and individual apps - elaborating on how to move from one to another configuration would make sense using the Az.App module.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We are contacting service team to understand how to do reach the requirement.

**Comment by lijinpei2008** [comment]
Is this an ask to be able to switch container app environment from using VNet to not using VNet? If so then it is currently not supported. The networking config can only be set during creation of a new environment and cannot be changed on an existing one.
