### ISSUE TITLE
Add PUT support to Invoke-AzureRmResourceAction

### ISSUE THREAD

**Issue by gregjhogan** [Azure/azure-powershell#1932]
I can't use the Invoke-AzureRmResourceAction for:

``` ps1
Invoke-AzureRmResourceAction -ResourceGroupName $resourceGroup -ResourceType 'microsoft.insights/components' -ResourceName $name -Action 'edison' -Parameters $params -Force
```

because it needs to submit a request like this:

```
PUT https://management.azure.com/subscriptions/{subscription}/resourceGroups/{resource-group}/providers/microsoft.insights/components/{resource}/edison?api-version=2015-05-01 HTTP/1.1
Authorization: Bearer {token}
User-Agent: AzurePowershell/v1.0.0.0
ParameterSetName: Resource that resides at the subscription level.
CommandName: Invoke-AzureRmResourceAction
Content-Type: application/json; charset=utf-8
Host: management.azure.com
Content-Length: 69
Expect: 100-continue

{
  "recipientsAddresses": "",
  "isEmailCoAdminsEnabled": false
}
```

This command is the best way I can find to automate functionality that exists in the portal, but does not yet have a dedicated powershell command or ARM template support.  Please add support for PUT actions!

**Comment by markcowl** [comment]
@vivsriaus Are there any plans to add this support, or would this more properly be supported by New-AzureRmResource

**Comment by gregjhogan** [comment]
@markcowl would New-AzureRmResource work in my situation?  Note that the when I am using Invoke-AzureRmResourceAction I am specifying -Action which tacks /edison onto the end of the URL (after the resource name)

Specifically, I am having trouble automating setting the proactive detection options for an App Insights instance.  If there is some better way to automate things like this please let me know.  Thanks!

**Comment by vivsriaus** [comment]
@gregjhogan The Invoke cmdlet was designed to only make POST calls. PUT should ideally be done in the New-AzureRmResource cmdlet, like @markcowl suggested.

In this instance, I was able to call New-AzureRmResource to make a PUT on a similar resource id, although the response from the RP was a 404.

New-AzureRmResource -ResourceId https://management.azure.com/subscriptions/{subId}/resourceGroups/{myGroup}/providers/microsoft.insights/components/{myResource}/test -IsFullObject -Properties @{"recipientsAddresses"="";"isEmailCoAdminsEnabled"="false"} -ApiVersion 2015-05-01

This is the debug response from powershell

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/{redacted}/resourceGroups/{redacted}//providers/microsoft.insights/components/{redacted}//test?api-version=2015-05-01

Headers:
User-Agent                    : AzurePowershell/v1.0.5.0
ParameterSetName              : The resource Id.
CommandName                   : New-AzureRmResource

Body:
{
  "recipientsAddresses": "",
  "isEmailCoAdminsEnabled": "false"
}

cc @ravbhatnagar

**Comment by gregjhogan** [comment]
@vivsriaus I have created the app insights instance through an ARM template (I do everything I can in the template) and then I want to configure anything remaining in powershell.  This makes me wonder if Set-AzureRmResource is actually more appropriate?

Also, is there some way I can do this without building the resource ID?  I tried this, but it doesn't work (it removes /edison from the URL)
```ps1
New-AzureRmResource -PropertyObject $props -ResourceGroupName $resourceGroup -ResourceType 'microsoft.insights/components' -ResourceName ($name + "/edison") -Force
```

**Comment by gregjhogan** [comment]
Here is what I found to work, but it feels really strange:
```ps1
param (
	[Parameter(Mandatory=$true)]
    [string]$resourceGroup,
	[Parameter(Mandatory=$true)]
    [string]$location,
	[Parameter(Mandatory=$true)]
    [string]$name,
	[Parameter(Mandatory=$true)]
	[string]$plan,
	[Parameter(Mandatory=$true)]
	[bool]$payOverage
)

$params =
@{
	appInsightsName = $name;
    location = $location;
}
New-AzureRmResourceGroupDeployment -ResourceGroupName $resourceGroup -TemplateFile "$PSScriptRoot\template.json" -TemplateParameterObject $params

# set pricing tier settings
Invoke-AzureRmResourceAction -ResourceGroupName $resourceGroup -ResourceType 'microsoft.insights/components' -ResourceName $name -Action 'BillingPlanForComponent' -ODataQuery "planSelected=$plan&payOverage=$payOverage" -Force

$props =
@{
	isEmailCoAdminsEnabled = $false;
	recipientsAddresses = "";
}
$resource = Get-AzureRmResource -ResourceGroupName $resourceGroup -ResourceType 'microsoft.insights/components' -ResourceName $name
# set proactive detection settings
New-AzureRmResource -ResourceId ($resource.ResourceId + '/edison') -Properties $props -IsFullObject -ApiVersion '2015-05-01' -Force
```

Does it make sense to add a -Action parameter to New-AzureRmResource so that I don't have to manually construct the ResourceId and specify -ApiVersion (it can't figure out what the latest version is when using New-AzureRmResource above)?  What is the difference between New-AzureRmResource, Set-AzureRmResource, and Invoke-AzureRmResourceAction in the context of there always being an "Action" (e.g. /BillingPlanForCOmponent and /edison).  Thanks!

**Comment by maddieclayton** [comment]
Closing as dup of: https://github.com/Azure/azure-powershell/issues/3806
