### ISSUE TITLE
New-AzApplicationInsights does not know WorkspaceResourceId parameter

### ISSUE THREAD

**Issue by benoithamet** [Azure/azure-powershell#19349]
### Description

Hi there
using the latest Az module available (8.2.0), the New-AzApplicationInsights command does not know the WorkspaceResourceId parameter
The documentation confirms this parameter exists (https://docs.microsoft.com/en-us/powershell/module/az.applicationinsights/new-azapplicationinsights?view=azps-8.2.0&WT.mc_id=M365-MVP-7836#:~:text=False-,%2DWorkspaceResourceId,-Resource%20Id%20of)

This is also the same for Update-AzApplicationInsights

### Issue script & Debug output

```PowerShell
n/a
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
8.2.0
```

### Error output

```PowerShell
A parameter cannot be found that matches parameter name 'WorkspaceResourceId'
```

**Comment by dingmeng-xue** [comment]
@VeryEarly , please look into this issue.

**Comment by VeryEarly** [comment]
hi @benoithamet ,

Please check the version imported and installed:
```
Get-Module -Name Az.ApplicationInsights
Get-InstalledModule -Name Az.ApplicationInsights
```
the latest version of Az.ApplicationInsights is 2.1.0 which supports this parameter:
https://www.powershellgallery.com/packages/Az.ApplicationInsights/2.1.0

**Comment by benoithamet** [comment]
I have done that already too and same result anyway

**Comment by VeryEarly** [comment]
can you share the result of 
```
Get-Module -Name Az.ApplicationInsights

Get-InstalledModule -Name Az.ApplicationInsights
```
in your environment and paste the complete error message when you tried to pass `WorkspaceResourceId`

**Comment by benoithamet** [comment]
Hi there

There may have been something wrong on the device I have been working on and testing
Just tested again on another device with fresh Azure PS module installed and it work
You can close this bug/request as not related to the PS module

Thanks for your assistance


From: Benoit HAMET
Sent: Thursday, 1 September 2022 12:06 PM
To: 'Azure/azure-powershell' ***@***.***>; Azure/azure-powershell ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Azure/azure-powershell] New-AzApplicationInsights does not know WorkspaceResourceId parameter (Issue #19349)

***@***.***

***@***.***

**Comment by VeryEarly** [comment]
got it, thanks for the confirmation.
