### ISSUE TITLE
[Doc]: Example issue of New-AzGalleryApplicationVersion

### ISSUE THREAD

**Issue by AkshishaRocks** [Azure/azure-powershell#19358]
### Description

Hello Team,

This is regarding official document - [New-AzGalleryApplicationVersion (Az.Compute) | Microsoft Docs](https://docs.microsoft.com/en-us/powershell/module/az.compute/new-azgalleryapplicationversion?view=azps-8.2.0)

Here, as per the example given -

$ctx = New-AzStorageContext -StorageAccountName $storAccName
$SASToken = New-AzStorageBlobSASToken -Context $ctx -Container $containerName -blob $blobName -Permission r
$storAcc = Get-AzStorageAccount -ResourceGroupName $rgName -Name $storAccName
$blob = Get-AzStorageBlob -Container $containerName -Blob $blobName -Context $storAcc.Context
$SASToken = New-AzStorageBlobSASToken -Container $containerName -Blob $blobName -Permission rwd -Context $storAcc.Context
$SASUri = $blob.ICloudBlob.Uri.AbsoluteUri + "?" +$SASToken 
New-AzGalleryApplicationVersion -ResourceGroupName $rgname -Location EastUS -GalleryName $galleryName -GalleryApplicationName $galleryApplicationName -name "0.1.0" -PackageFileLink $SASUri -Install "powershell -command 'Expand-Archive -Path package.zip -DestinationPath C:\\package\'" -Remove "del C:\\package"

There is a "?" in $SASUri and the $SASToken generated from the second command will contain a "?" as well.

So, when running the New-AzGalleryApplicationVersion command , it is getting failed with error "SAS is not valid for source uri" 

New-AzGalleryApplicationVersion -ResourceGroupName $rgname -Location EastUS -GalleryName $galleryName -GalleryApplicationName $galleryApplicationName -name "0.1.4" -PackageFileLink $SASUri -Install "move .\${galleryApplicationName} .\AzVMApplication.txt & move .\AzVMApplication.txt C:\Temp\" -Remove "del C:\Temp\AzVMApplication.txt"
New-AzGalleryApplicationVersion_CreateExpanded: /usr/local/share/powershell/Modules/Az.Compute/4.30.0/Compute.Autorest/custom/New-AzGalleryApplicationVersion.ps1:216
Line |
 216 |          Az.Compute.internal\New-AzGalleryApplicationVersion @PSBoundP …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The SAS is not valid for source uri 'https://akshishagallery.blob.core.windows.net/gallerycontainer/chrome.txt'.

Also, in $SASUri, we are getting 2 "??" due to concatenation of "?" in the below command - 
$SASUri = $blob.ICloudBlob.Uri.AbsoluteUri + "?" +$SASToken 

So, if we remove "?" from the above command, it is working fine.

**Comment by SaurabhSharma-MSFT** [comment]
@AkshishaRocks We are looking into it and get back to you for any additional information.

**Comment by AkshishaRocks** [comment]
@SaurabhSharma-MSFT - Thank you for your response. Sure, let me know if you need any additional information

**Comment by SaurabhSharma-MSFT** [comment]
@AkshishaRocks I have submitted a PR to address this issue.  Thanks for reporting.

**Comment by SaurabhSharma-MSFT** [comment]
@AkshishaRocks We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
