### ISSUE TITLE
It's so painful to upgrade SDK (SRP SDK, or XSCL) for Storage PowerShell

### ISSUE THREAD

**Issue by blueww** [Azure/azure-powershell#1936]
Since some other features (SQL, compute) reference Storage Cmdlet project, When storage upgrade SDK (SRP SDK, or XSCL) , we need to change all other reference projects (like compute, SQL) and to make test pass. But since storage team not familiar with other feature team's product/test code, it's so painful for storage team to fix the failed test cases.

We would suggest following 3 ways to resolve the issue (anyone should be good):
1. OneSDK team upgrade the SDK, and each feature team fix the product code and test code by themselves.
2. De-Couple other feature project from Storage project, so upgrade SDK for storage project won't impact other project.
3. Storage team can help to upgrade the SDK for other features, and make sure the build pass. But each feature team should fix the failed test case by themselves.

**Comment by markcowl** [comment]
@blueww I believe this PR fixes the issue:  https://github.com/Azure/azure-powershell/pull/1950
