### ISSUE TITLE
[Doc]:  Get-AzFirewallPolicyRuleCollectionGroup

### ISSUE THREAD

**Issue by joteromontes** [Azure/azure-powershell#19371]
### Description

I was trying to explain this command today, i have found one variable that was very painful to understand by the customer and myself.

-Name
The resource name.

This is not clear at all, can you please change the wording here to something more detailed and friendly to read for example:

-Name
The resource Firewall Policy Rule Collection Group name, for example: "DefaultNetworkRuleCollectionGroup" 

This simple change in the wording will improve the understanding on this command and make the life of the PowerShell users better :)

**Comment by dingmeng-xue** [comment]
@joteromontes , thanks for suggestion. `-Name` is a common parameter used by almost all Azure resource types. It is resource name of current resource type. Many developers are just simply copy its description from other existing cmdlets. 

We will update this doc.

**Comment by navba-MSFT** [comment]
@joteromontes Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@joteromontes The above PR has been filed and it is currently under review. In the meantime if you have any questions, please feel free to ask.
