### ISSUE TITLE
Remove-AzureStorageBlob does not honor -WhatIf

### ISSUE THREAD

**Issue by suprak** [Azure/azure-powershell#1937]
I just ran ```<rest of pipe> | Remove-AzureStorageBlob -WhatIf``` and it deleted my blobs.

**Comment by markcowl** [comment]
@suprak This should be fixed as part of realigning the usage of ShouldProcess / ShouldContinue as part of this release.  See: https://github.com/Azure/azure-powershell/issues/718

**Comment by markcowl** [comment]
@suprak Unfortunately, this moved into the next sprint, will be resolved then

**Comment by markcowl** [comment]
Fixed
