### ISSUE TITLE
[Doc]: New-AzSqlVMGroup

### ISSUE THREAD

**Issue by dinisgarcia** [Azure/azure-powershell#19414]
### Description

The description for storageaccounturl and storageaccountprimarykey is the same and it shouldnt be. 
![image](https://user-images.githubusercontent.com/45267803/188649604-f10a8893-70d2-46a2-9fbd-137df50257de.png)

we should have the storage account url https://storagename.blob.core.windows.net/ instead

**Comment by SaurabhSharma-MSFT** [comment]
@dinisgarcia We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@dinisgarcia The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with. Thanks.
