### ISSUE TITLE
Namespace [Microsoft.Azure.Common.Authentication.Models.AzureSMProfile] has changed

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-powershell#1941]
I have some Azure related module to automate some operations tasks. After 1.2.3 it appears to be broken for the second time for the following reason.

As i described on my previous tickets (sample code is available [here](https://github.com/eosfor/AzureSearch), i need to add SubscriptionID/SubscriptionName parameters to such commands as Get-AzureVM to avoid switching subscriptions in the code> This is required because i have more than 20 of them already and i had more "switch subscription" code than actual logic code in it before. So i decided to add this parameter by using proxy functions. 

Suddenly it happened that [Microsoft.Azure.Common.Authentication.Models.AzureSMProfile] has changed to [Microsoft.Azure.Commands.Common.Authentication.Models.AzureSMProfile] which just broke all proxy functions i generated. And this happens for the second time. Now the problem arises that if someone from my users suddenly update Azure Module to 1.2.3 we need to ask the rest of users to upgrade as well. Which is not really good thing and it is very time consuming.

Actually i don't know if there is any value in this move, but i'd like you to know that it is not a really good idea to suddenly change publicly available interfaces despite any agile prectices you follow

**Comment by markcowl** [comment]
@eosfor You should not take any dependencies on classes used in the implementation of Azure PowerShell cmdlets.  This is a PowerShell product and not a C# product. We do not, nor do we plan to maintain the public interface of the implementation classes. 

The modules are versioned based on changes in the cmdlets themselves, not on the implementation classes.  I would highly discourage you from taking dependencies on anything except the public cmdlet interfaces in PowerShell.

**Comment by markcowl** [comment]
@eosfor  BTW, if there is some scenario you needed the functionality in the authentication library for, please let us know and perhaps we can accommodate it in a public, supported cmdlet.  I want to dissuade youf rom taking dependencies on the common libraries used in cmdlet implementation, as we know these will be changing rapidly in the next few releases, and their public signatures are not meant to be a target for customer dependencies.

**Comment by eosfor** [comment]
Hello Mark, 

> This is a PowerShell product and not a C# product. We do not, nor do we plan to maintain the public interface of the implementation classes.
