### ISSUE TITLE
Unable to EnableWebsiteApplicationDiagnostic if tracing is enabled for WebApp.

### ISSUE THREAD

**Issue by kkhrebtov** [Azure/azure-powershell#1942]
Following error message appears: 
Enable-AzureWebsiteApplicationDiagnostic : <string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">{"Code":"BadRequest","Message":"There was an error deserializing
the object of type Microsoft.Web.Hosting.Administration.SiteConfig. DateTime content '9999-12-31T23:59:00Z' does not start with '\\/Date(' and end with ')\\/' as required for
JSON.","ExtendedCode":null,"MessageTemplate":null,"Parameters":null,"InnerErrors":null}</string> 

See a part JSON for this WebApp (got it from Azure Resource Explorer) :

 "requestTracingEnabled": true,
 "requestTracingExpirationTime": "9999-12-31T23:59:00Z",

**Comment by markcowl** [comment]
@kkhrebtov Can you please execute this cmdlet using ```$DebugPreference="Continue"``` and include the request and response from the server in this issue?  This will make it much easier for us to diagnose the issue.

**Comment by makhdumi** [comment]
I'm not going to include the full request and response because it contains private info like passwords, but here is the offending bit.
```
Body:
{
  "AlwaysOn": true,
...
  "RequestTracingEnabled": true,
  "RequestTracingExpirationTime": "9999-12-31T23:59:00Z",
```

**Comment by David-0193** [comment]
I'm having the same issue on half of the 60 webapps we have. Since we manage all of them via powershell and foreach, i don't know why the half of them are different and throw this. 
All in same datacenter.

**Comment by David-0193** [comment]
A workaround is disabling request tracing before the call and then enabling it afterwards.
`Set-AzureWebsite -Name $site.Name   -RequestTracingEnabled $False `

By the way is there a powershell cmdlet for setting the webserver logs (not the application) to the storage? Something like EnableWebsiteServerDiagnostic?

**Comment by markcowl** [comment]
@Nking92 Please take a look

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
