### ISSUE TITLE
[Doc]: Get-AzRecoveryServicesVault

### ISSUE THREAD

**Issue by nitbhatt** [Azure/azure-powershell#19457]
### Description

URL >> https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesbackupproperty?view=azps-8.3.0

Please specify what $vault needs to be>> 
$vault = Get-AzRecoveryServicesVault -Name "xxxx"

**Comment by navba-MSFT** [comment]
@nitbhatt Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
