### ISSUE TITLE
run 'Get-AzVMExtension' via powershell, I see that the Qualys Agent has a provisioning state of 'ProvisioningState = Failed'. 

### ISSUE THREAD

**Issue by ran-ten21** [Azure/azure-powershell#19466]
### Description

![image](https://user-images.githubusercontent.com/43187489/189739377-e6beef5e-76fe-4422-88ed-3e5c32cd828e.png)

![image](https://user-images.githubusercontent.com/43187489/189739519-e2bb28c7-0650-410e-a1b7-f14827600666.png)

<HTML xmlns:o = "urn:schemas-microsoft-com:office:office" xmlns:u1><HEAD>
<STYLE type=text/css>a { text-decoration: underline; color: white; }</STYLE>
</HEAD>
<BODY spellcheck=false lang=EN-GB onload=blink(); style="tab-interval: 36.0pt" 
vLink=purple link=blue scroll=auto>
<DIV 
style="FONT-SIZE: 11pt; FONT-FAMILY: Calibri, Arial, Helvetica, sans-serif; COLOR: rgb(0,0,0)">
<P style="FONT-SIZE: 11pt; FONT-FAMILY: Calibri; MARGIN: 0in">
<TABLE class=MsoNormalTable 
style="WIDTH: 100%; BORDER-COLLAPSE: collapse; mso-yfti-tbllook: 1536; mso-padding-alt: 0cm 5.4pt 0cm 5.4pt" 
cellSpacing=0 cellPadding=0 width="100%" border=0>
<TBODY>
<TR style="HEIGHT: 14.15pt; mso-yfti-irow: 0; mso-yfti-firstrow: yes">
<TD 
style="BORDER-TOP: windowtext 1pt solid; HEIGHT: 14.15pt; BORDER-RIGHT: windowtext 1pt solid; WIDTH: 84.64%; BORDER-BOTTOM: windowtext 1pt solid; PADDING-BOTTOM: 0cm; PADDING-TOP: 0cm; PADDING-LEFT: 5.4pt; BORDER-LEFT: #f0f0f0; PADDING-RIGHT: 5.4pt; BACKGROUND-COLOR: transparent; mso-border-left-alt: solid windowtext .5pt; mso-border-alt: solid windowtext .5pt" 
vAlign=top width="84%">
<P class=MsoNormal style="MARGIN: 0cm"><SPAN 
style='FONT-SIZE: 10pt; FONT-FAMILY: "Calibri",sans-serif; mso-bidi-font-size: 11.0pt; mso-fareast-font-family: "Times New Roman"'>When I run 'Get-AzVMExtension' via powershell, I see that the Qualys Agent has a 
provisioning state of 'ProvisioningState = Failed'.</SPAN></P></TD></TR></TBODY></TABLE></P></DIV></BODY></HTML>

This is BYOL from qualys. Just need to know if this is supported or not - or whom supports this in CSS to try and get help for the customer.

**Comment by ran-ten21** [comment]
any update?

**Comment by ran-ten21** [comment]
any update?

**Comment by ran-ten21** [comment]
any update?

**Comment by ran-ten21** [comment]
any update?

**Comment by ran-ten21** [comment]
customer is still waiting - any update?

**Comment by ran-ten21** [comment]
any response? Customer is waiting on this.

**Comment by ran-ten21** [comment]
please provide an update

**Comment by ran-ten21** [comment]
please provide an update for the customer this has been going on for weeks now.

**Comment by ran-ten21** [comment]
please answer this question for the customer

**Comment by ran-ten21** [comment]
any update?

**Comment by ran-ten21** [comment]
please can we get some traction on this?

**Comment by ran-ten21** [comment]
any update?

**Comment by ran-ten21** [comment]
please provide an update

**Comment by ran-ten21** [comment]
any update would be great

**Comment by ran-ten21** [comment]
any update?

**Comment by MsGabsta** [comment]
Hello @ran-ten21 please open a support ticket using the Azure Portal selecting the VM that is having the issue.  

When opening the ticket there will be a drop-down menu where you can select what type of issue you are having. Select "VM Extensions not operating correctly" after that you can select "Qualys Extension (non-Microsoft) extension issue" and the ticket will be routed to the correct support team to troubleshoot this issue.  

Microsoft will verify there is no issue with the platform causing this failure.  Since this is a Third-Party extension, Qualys may need to be engaged by the customer if there is no issue at the platform level.

**Comment by ran-ten21** [comment]
We already have a support ticket... 2208290040003534


RayAnn Long
O (469) 775-3714 | Email: ***@***.******@***.***> | Working Hours: Mon.-Fri. 7:00AM to 4:00PM CST

**Comment by MsGabsta** [comment]
Thank you @ran-ten21, I will get engaged on the support case and help get this driven forward.

**Comment by ran-ten21** [comment]
> Thank you @ran-ten21, I will get engaged on the support case and help get this driven forward.

do you needed to be added in an email? just need to know if this is supported or not. this is qualys byol.

**Comment by navba-MSFT** [comment]
@MsGabsta @Drewm3, @avirishuv, @Vaibhav-Agar, @amjads1 Could you please share some pointers on this ? Any help on this is much appreciated.

**Comment by MsGabsta** [comment]
@navba-MSFT, I will get with the case owner on this to assist getting this resolved.

**Comment by MsGabsta** [comment]
@navba-MSFT we do own this specific issue.  I'll work with you through the support case to get this resolved.

**Comment by MsGabsta** [comment]
Closing issue here as we are working together through support ticket.
