### ISSUE TITLE
No help for Add-AzureRMVhd

### ISSUE THREAD

**Issue by philmea** [Azure/azure-powershell#1946]
The help for Add-AzureRMVhd has not description or examples

**Comment by markcowl** [comment]
@singhkay Can we consider adding examples to the help?

**Comment by singhkay** [comment]
@philmea This is in flight with the MSDN team. Should be there soon and in PS next release.

**Comment by singhkay** [comment]
Closing as this was online few releases ago. Thanks for reporting! @philmea
