### ISSUE TITLE
PowerShell script not work

### ISSUE THREAD

**Issue by XiaoYue2-22** [Azure/azure-powershell#19472]
### Description

Run below PowerShell script
Connect-AzureRMAccount -Subscription subId
$str = Get-AzureRmStorageAccount -ResourceGroupName rgname -Name storageaccountname
$resource = Get-AzureRmResource -ResourceId $[str.Id](http://str.id/)
$resource.Properties.defaultToOAuthAuthentication=$true
$resource | Set-AzureRmResource -Force

in document: https://docs.microsoft.com/en-us/answers/questions/781262/enable-34azure-active-directory-authorization-in-t.html

But failed with 
![image](https://user-images.githubusercontent.com/100192253/189864530-09739c61-614c-4310-925a-da0ebb85cd08.png)
 
Tried similar steps with the Az module, but was unable to set-azresource because the properties object contained data on secondary region, which is read-only (https://docs.microsoft.com/en-us/powershell/module/az.resources/set-azresource?view=azps-8.3.0)

Could you help check this?

### Issue script & Debug output

```PowerShell
see description
```

### Environment data

```PowerShell
see description
```

### Module versions

```PowerShell
see description
```

### Error output

```PowerShell
see description
```

**Comment by SaurabhSharma-MSFT** [comment]
@XiaoYue2-22 We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@XiaoYue2-22 Please upgrade to new Az modules and AzureRM modules are getting deprecated. Please use the below code to achieve the same - 
```
Connect-AzAccount -Subscription $subscriptionid
$str = Get-AzStorageAccount -ResourceGroupName $rgname -Name $storageaccountname #-Debug
$resource = Get-AzResource -ResourceId $str.Id
$resource.Properties.defaultToOAuthAuthentication=$false
$resource | Set-AzResource -Force
```

**Comment by SaurabhSharma-MSFT** [comment]
@XiaoYue2-22 Please let me know if you have any other questions else we will proceed with the issue closure. Thanks.

**Comment by XiaoYue2-22** [comment]
it works for me, thank you very much

**Comment by SaurabhSharma-MSFT** [comment]
@XiaoYue2-22 We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
