### ISSUE TITLE
No ability to create storage containers

### ISSUE THREAD

**Issue by philmea** [Azure/azure-powershell#1947]
The Storage module has no ability to make containers in SA's

**Comment by markcowl** [comment]
You are looking at the wrong storage module.  Azure.Storage is the module that covers the storage data plane cmdlets - these are usable with both v1 (RDFE) and v2 (ARM) storage accounts and include the ability to create storage containers, blobs, queues, tables, etc.

AzureRM.Storage is a module that allows management of storage accounts through ARM.

**Comment by philmea** [comment]
Then where is the ability to create, manage or delete containers? I see:
Name                                     
----                                     
Get-AzureRmStorageAccount                
Get-AzureRmStorageAccountKey             
Get-AzureRmStorageAccountNameAvailability
Get-AzureRmStorageUsage                  
New-AzureRmStorageAccount                
New-AzureRmStorageAccountKey             
Remove-AzureRmStorageAccount             
Set-AzureRmCurrentStorageAccount         
Set-AzureRmStorageAccount
