### ISSUE TITLE
Install-Module AzureAD - error message

### ISSUE THREAD

**Issue by ldhema** [Azure/azure-powershell#19491]
### Description

I tried to run Install-Module AzureAD and getting this error message
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'AzureAD'. Try Get-PSRepository to see all available registered module 
repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

I tried few solutions given and did not work for me
Get-PSRepository

Name                      InstallationPolicy   SourceLocation                                                                                                                        
----                      ------------------   --------------                                                                                                                        
PSGallery1                Trusted              C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1                                                                      

Can anyone kindly help me. I am just new to Azure

**Comment by dingmeng-xue** [comment]
@idhema , please install PowerShellGet 2.x. I remember 1.0.0.1 cannot work with the latest PSgallery. `AzureAD` only can be used on Windows PowerShell because it is implemented with .NET framework rather than .NET Standard. 

AzureAD doesn't belong to Azure-powershell repo. If you have specific question to it, please raise question to AzureAD support.
