### ISSUE TITLE
Not able to run Set-AzSqlServer  on Az.Sql version 3.11.0 

### ISSUE THREAD

**Issue by zqyAmy** [Azure/azure-powershell#19506]
### Description

When run Set-AzSqlServer command on Version 3.11.0, I will encounter the following error: 
Set-AzSqlServer -ResourceGroupName 'xxx' -ServerName 'xxx' -Force

Error message:
Set-AzSqlServer: Operation returned an invalid status code 'BadRequest'

![image](https://user-images.githubusercontent.com/54308252/190897305-68997180-40ab-4bf8-a450-ec92aaea2d56.png)

But if we run same command on Version 3.10.0, it is working.

**Comment by SaurabhSharma-MSFT** [comment]
@zqyAmy I am looking into this issue and get back to you for any further information.

**Comment by SaurabhSharma-MSFT** [comment]
@zqyAmy You need to provide the properties which you want to update along with resource group and server name. For example - This resets the administrator password
```
$ServerPassword = "newpassword"
$SecureString = ConvertTo-SecureString $ServerPassword -AsPlainText -Force
Set-AzSqlServer -ResourceGroupName "ResourceGroup01" -ServerName "Server01" -SqlAdministratorPassword $secureString
```
Please refer to the documentation - [Set-AzSqlServer](https://learn.microsoft.com/en-us/powershell/module/az.sql/set-azsqlserver?view=azps-8.3.0) for details.

**Comment by SaurabhSharma-MSFT** [comment]
@zqAmy It looks like an issue with the Set-AzSQLServer when the server is setup with AAD admin as well.  I am internally checking with the team on this but on the interim use [CLI](https://learn.microsoft.com/en-us/cli/azure/sql/server?view=azure-cli-latest#az-sql-server-update) until PS is fixed. Or Setup SQL server without AAD Admin.

**Comment by zqyAmy** [comment]
Thank you SaurabhSharma. Our customer has to use PowerShell command and setup with AAD admin. If issue fixed or have any update, please let me know. Appreciate your help.

**Comment by SaurabhSharma-MSFT** [comment]
@zqyAmy ,
Can you please latest version of Az.SQL and validate. A fix was made in that release for this issue.

Get-Module -Name Az.Sql -ListAvailable
ModuleType Version Name ExportedCommands
Script 3.12.0 Az.Sql {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlData...

We apologize for any inconvenience this caused to your team.
