### ISSUE TITLE
When retrieving the Virtual Machine Role Sizes via “Get-AzureLocation” the returned results do not consistent with the sizes listed in azure website

### ISSUE THREAD

**Issue by xingzhougmu** [Azure/azure-powershell#1953]
When retrieving the Virtual Machine Role Sizes via “Get-AzureLocation” the returned results do not consistent with the sizes listed here (https://azure.microsoft.com/nl-nl/documentation/articles/virtual-machines-size-specs/).

For example, the returned result for East US is as below:
PS C:\Users\xingzhou> Get-AzureLocation

DisplayName             : East US
WebWorkerRoleSizes      : {A10, A11, A5, A6, A7, A8, A9, ExtraLarge, ExtraSmall, Large, Medium, Small, Standard_D1, Standard_D1_v2, Standard_D11,
                          Standard_D11_v2, Standard_D12, Standard_D12_v2, Standard_D13, Standard_D13_v2, Standard_D14, Standard_D14_v2, Standard_D2,
                          Standard_D2_v2, Standard_D3, Standard_D3_v2, Standard_D4, Standard_D4_v2, Standard_D5_v2}
VirtualMachineRoleSizes : {**A10, A11, A5, A6, A7, A8, A9**, Basic_A0, Basic_A1, Basic_A2, Basic_A3, Basic_A4, ExtraLarge, ExtraSmall, Large, Medium,
                          Small, Standard_D1, Standard_D1_v2, Standard_D11, Standard_D11_v2, Standard_D12, Standard_D12_v2, Standard_D13,
                          Standard_D13_v2, Standard_D14, Standard_D14_v2, Standard_D2, Standard_D2_v2, Standard_D3, Standard_D3_v2, Standard_D4,
                          Standard_D4_v2, Standard_D5_v2, Standard_DS1, Standard_DS11, Standard_DS12, Standard_DS13, Standard_DS14, Standard_DS2,
                          Standard_DS3, Standard_DS4}

We have sizes A6, A7, A8, A9 and A10. Howver, the actual size should have "**Standard_**" prefix. That is **Standard_**A6, **Standard_**A7, **Standard_**A8, **Standard_**A9 and **Standard_**A10.

We are relying the returned result from Get-AzureLocation, but A6 is not a recognizable size name when updating a VM.

For example, when update VM with "Standard_A6" will succeed, but will fail if with "A6".
PS C:\Users\1> $vmget = Get-AzureRmVM -ResourceGroupName go-ckdevkcentral -Name ck1azrdevapp011
PS C:\Users\1> $vmget.HardwareProfile.VmSize = "**Standard_A6**"
PS C:\Users\1> Update-AzureRmVM -VM $vmget -ResourceGroupName go-ckdevkcentral 
IsSuccess    StatusCode         StatusCode 
True             OK                        OK

**Expected Result:**
Change the VM sizes returned by “Get-AzureLocation” be consistent with what listed here (https://azure.microsoft.com/nl-nl/documentation/articles/virtual-machines-size-specs/).

Thanks,
Xing

**Comment by markcowl** [comment]
@singhkay Can you take a look?

**Comment by singhkay** [comment]
@xingzhougmu This is legacy naming for the sizes in the v1 stack. PowerShell just returns what's returned by the v1 API. Due to compatibility reasons with existing scripts these were never changed on the platform and are not expected to see being changed. All new feature effort is going into the new ARM stack.
