### ISSUE TITLE
Need test coverage for VPN gateway

### ISSUE THREAD

**Issue by lamchester** [Azure/azure-powershell#1955]
VPN gateway ServiceManagmenent cmdlets are currently not covered by tests in azure-powershell, which means regressions in translating input parameters to C# Azure API calls will not be caught.

There have been no such issues so far, but test coverage would be good to have.

**Comment by markcowl** [comment]
@lamchester Please assign to a milestone

**Comment by markjbrown** [comment]
Chester, you can contact me and Deepak.
