### ISSUE TITLE
vWAN vHub address space update issue

### ISSUE THREAD

**Issue by caofuuwe79qqvb** [Azure/azure-powershell#19568]
![image](https://user-images.githubusercontent.com/114128190/191657164-83f56539-05e3-4fb5-82b0-d45f9cfe6b58.png)

_Originally posted by @caofuuwe79qqvb in https://github.com/Azure/azure-powershell/discussions/19564_

**Comment by navba-MSFT** [comment]
@caofuuwe79qqvb Apologies for the late reply. Thanks for reaching out to us and reporting this issue. 

>It is not possible to change the private IP Address Space for a Virtual WAN Hub post creation.
It will show grayed out in UI as below:

![image](https://user-images.githubusercontent.com/57353862/210191986-27874e87-c3fc-4ee8-a2f9-49f6199d30e9.png)

> I also tried to test it via Update-AzVirtualHub PowerShell cmdlet and received below error:

![image](https://user-images.githubusercontent.com/57353862/210192007-cdd9e7cd-706f-4834-ae1e-1676fa090a48.png)

>Hence, it is a design limitation.
The only workaround is to delete and recreate the Virtual HUB with the new private address space that you want.

More Info [here](https://learn.microsoft.com/en-us/answers/questions/461519/change-hub-private-address-range.html).
