### ISSUE TITLE
[Doc]: Missing description for ScriptString parameter in Invoke-AzVMRunCommand

### ISSUE THREAD

**Issue by guyrleech** [Azure/azure-powershell#19627]
### Description

There is a what looks like a placeholder "{{ Fill ScriptString Description }}" in the "-ScriptString" section 

https://learn.microsoft.com/en-gb/powershell/module/az.compute/invoke-azvmruncommand?view=azps-8.3.0

**Comment by SaurabhSharma-MSFT** [comment]
@guyrleech We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@guyrleech The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
