### ISSUE TITLE
[Feature]: Register-AzResourceProvider wait for completion

### ISSUE THREAD

**Issue by golaat** [Azure/azure-powershell#19630]
### Description of the new feature

The [az cli provider](https://learn.microsoft.com/en-us/cli/azure/provider?view=azure-cli-latest#az-provider-register) has -wait parameter which blocks until the provider registration has completed. The Azure PowerShell `Register-AzResourceProvider` has no such parameter. This request is to add support to the  `Register-AzResourceProvider` to block until the provider registration has completed.

**Comment by dingmeng-xue** [comment]
We will look into it.
