### ISSUE TITLE
[Doc]: Example 2 of Register-AzAutomationScheduledRunbook isn't that helpful

### ISSUE THREAD

**Issue by mrdenny** [Azure/azure-powershell#19631]
### Description

Example 2 is supposed to show how to use parameters, but it doesn't. Something like this would be more helpful.

-Parameters @{"Key1"="ValueForPosition1";"Key2"="ValueForPosition2"}

**Comment by dingmeng-xue** [comment]
@mrdenny , could you share me which cmdlet you are referencing?

**Comment by mrdenny** [comment]
Register-AzAutomationScheduledRunbook

Thank You,
Denny Cherry
Owner & Principal Consultant
Denny Cherry & Associates Consulting, an Inc. 5000 company
***@***.******@***.***>
(o) +1 (323) 686-1478<tel:3236861478> | (d) +1 (213) 973-3669<tel:2139733669>
Online Calendar ***@***.***/bookings/>
[Logo, company name  Description automatically generated]<http://www.dcac.co/>
***@***.***
[A picture containing text  Description automatically generated]
[A blue sign with white text  Description automatically generated with low confidence]

**Comment by navba-MSFT** [comment]
@mrdenny The above PR has been filed. It is currently under review. In the meantime if you have any questions, please feel free to ask.
