### ISSUE TITLE
[Feature]: Get-AzConnectedMachine returns inconsistenly named properties (tag instead of tags)

### ISSUE THREAD

**Issue by MrCNeale** [Azure/azure-powershell#19664]
### Description of the new feature

When using Get-AzVM it returns the tags as a property named "Tags"

When using Get-AZConnectedMacchine it returns the tags as a propery named "Tag".

This should be consistent between the two commands.  
Tabbing shows the properties availabe
`
(get-azvm).T
`
`
Tags      Type      ToString
`

Again tabbing shows that AzConnectedMachine returns Tag instead of Tags
`
(get-azconnectedmachine).T
`
`
Tag     Type    ToJson
`

### Proposed implementation details (optional)

Get-AzConnectedMachine
should return a property of "Tags" not "Tag"

**Comment by navba-MSFT** [comment]
@MrCNeale Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by yaotongms** [comment]
A machine can have no tag or just one tag, and that's why we have 'tag' instead of 'tags'. @vedkale Let me know if we need to match with AzVM.

**Comment by MrCNeale** [comment]
What is returned should be consistent.
I have just reviewed a number of other Az resource types.
e.g. 
LoadBalancer, returns "tags"
Get-AzResource, returns "tags"
Get-AzKeyvault, returns "tags"
Get-azvirtualnetwork, returns "tags"
Get-Azsqldatabase, returns "tags"

Note: I am not referring to the parameter name passed in, but the "property" name returned.

**Comment by vedkale** [comment]
this will be fixed in #24064
