### ISSUE TITLE
Template as hash table for New-AzureRmResourceGroupDeployment

### ISSUE THREAD

**Issue by gregjhogan** [Azure/azure-powershell#1968]
Please add a TemplateObject parameter to New-AzureRmResourceGroupDeployment

``` ps1
New-AzureRmResourceGroupDeployment -ResourceGroupName $resourceGroup -TemplateObject $template -TemplateParameterObject $params
```

I can of course write it out to a file first, but it would be a lot more convenient when building template files dynamically to pass the powershell object that represents the template directly.

**Comment by ravbhatnagar** [comment]
We wont be able provide support for this in the near future. From a usability point of view, it will not be trivial to construct the object which represents your template.

**Comment by sahammer** [comment]
This would be pretty useful to have. :+1:

**Comment by gregjhogan** [comment]
@ravbhatnagar I don't understand your comment "it will not be trivial to construct the object which represents your template". I am constructing the template as an object.  Currently when a local template file is used, you read it in as an object and post it to an API endpoint.  I just want to construct the exact same object that would be placed in a template file and then pass that as a parameter (instead of having to save it to a file first).  It is a convenience thing when you are dynamically generating templates.

**Comment by 4c74356b41** [comment]
I honestly don't see value in this, maybe for small templates, but I have templates at 500 lines and more, it would be a nightmare to construct them in PS + I have some pretty weird login in most of those so, I see why they are hesitating to work on this, would be nice to have, but meh

**Comment by vladimir-shcherbakov** [comment]
Closing due to the [comment](https://github.com/Azure/azure-powershell/issues/1968#issuecomment-239554981).
