### ISSUE TITLE
Get-AzVMSSVMRunCommand cmdlet output fields not displayed for "-Expand InstanceView" (other than Name and Location) 

### ISSUE THREAD

**Issue by vivlingaiah** [Azure/azure-powershell#19689]
### Description

Issue: Output of Get-AzVMSSVMRunCommand with  "-Expand InstanceView" does not display any other fields apart from Name and Location, which are not useful (because they are input itself).
The issue is identical to https://github.com/Azure/azure-powershell/issues/18440 (with Get-AzVMRunCommand)

ASK:  When the Get-AzVMSSVMRunCommand is executed, could you change format such that all InstanceView output fields are displayed ?

### Issue script & Debug output

```PowerShell
(this should display all other fields except InstanceView)
PS C:\Users\vivekl.REDMOND> Get-AzVmssVMRunCommand -ResourceGroupName VivRG0 -VMScaleSetName VivVMSSWCUS2 -InstanceId 0 -RunCommandName RC0928_0

Location      Name
--------      ----
westcentralus RC0928_0


PS C:\Users\vivekl.REDMOND> Get-AzVmssVMRunCommand -ResourceGroupName VivRG0 -VMScaleSetName VivVMSSWCUS2 -InstanceId 0 -RunCommandName RC0928_0 -Expand InstanceView

Location      Name
--------      ----
westcentralus RC0928_0


Get-AzVmssVMRunCommand list:
PS C:\Users\vivekl.REDMOND> Get-AzVmssVMRunCommand -ResourceGroupName VivRG0 -VMScaleSetName VivVMSSWCUS2 -InstanceId 0

Location      Name
--------      ----
westcentralus RC0928_0
westcentralus RC0928_1
```

### Environment data

```PowerShell
NA
```

### Module versions

```PowerShell
NA
```

**Comment by jaylabell** [comment]
Thank you, we are looking into this issue.

**Comment by jaylabell** [comment]
@vivlingaiah - We have added this work item to our Sprint. @grizzlytheodore is looking into it !

**Comment by grizzlytheodore** [comment]
addressed by https://github.com/Azure/azure-powershell/pull/19862/

**Comment by grizzlytheodore** [comment]
closing this issue

**Comment by marsands-ms** [comment]
Sorry @grizzlytheodore I'm running into the same issue with Get-AZVMRunCommand. How was this fixed and how am I supposed to get to the status of the run command using the Az.Compute powershell module? 

PS C:\Users\marsands> Get-AzVMRunCommand  -ResourceGroupName "<redacted>" -VMName "<redacted>" -Expand InstanceView

Location Name
-------- ----
eastus   helloworld
