### ISSUE TITLE
Get-AzAdGroupMember -select doesn't return user properties

### ISSUE THREAD

**Issue by plmcgrn** [Azure/azure-powershell#19728]
### Description

When using `Get-AzAdGroupMember` with the `-select` parameter, the returned results do not contain the user properties requested.  When I test this using the beta API directly, it does return the fields properly.

This is the same as Issue #17503 , which was auto-closed without a fix.  The MS Graph API being used is a beta API that includes all this data, so it should be supported.  Also, I noted that the comment linking to the supported properties isn't accurate.  If I do `-Select mail`, I get no data from the cmdlet even though that property is in the raw API response.

### Issue script & Debug output

```PowerShell
$id = 'redacted'
$userProps = "id", "displayName", "mail"
$users = Get-AzADGroupMember -GroupObjectId $id -Select $userProps

Can't provide output without redacting to the point of irrelevance.  I confirmed that all 3 properties were part of the response from the Graph API.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.1                Az.Accounts                         
Script     6.2.0                 Az.Resources
```

### Error output

```PowerShell
No relevant errors returned
```

**Comment by dingmeng-xue** [comment]
@VeryEarly ， please help to look into it.

**Comment by RakeshMohanMSFT** [comment]
@plm
![image](https://user-images.githubusercontent.com/49954584/198065310-3ca57419-e4be-4c6b-86a2-d3384fc19917.png)

**Comment by plmcgrn** [comment]
> @plmcgrn Can you please trying upgrading the modules as shown below? ![image](https://user-images.githubusercontent.com/49954584/198065310-3ca57419-e4be-4c6b-86a2-d3384fc19917.png)

Az.Account updates to 2.10.2 but Az.Resources updates to 6.2.0 not 6.3.0, for me.
```
redacted> get-module Az*                                                 

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     6.2.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-A…
```

Regardless, retrying gives same results.  
```
$userProps = "id", "displayName", "givenName", "country"
$id = 'redacted'
$gm = Get-AzAdGroupMember -GroupObjectId $id -Select $userProps
```
The results do not contain givenName or country.

**Comment by RakeshMohanMSFT** [comment]
@plmcgrn Its actually as designed. You can use this command as a word around to get the GivenName and country
`Get-AzADGroupMember -ObjectId a5819190-0f06-45c6-bcf2-434a119225ed | where-object {$_.OdataType.Contains("user")} | foreach-object {Get-AzADUser -ObjectId $_.Id -Select Id,displayName,userPrincipalName}`

**Comment by PSdasAndi** [comment]
@RakeshMohanMSFT I don't understand this. If this is as designed, then why does Get-AzGroupMember have "-Select" as a parameter? Will the parameter be removed from the cmdlet? /unresolve

**Comment by plmcgrn** [comment]
/unresolve
"As designed" is s cop-out.  Either -select is supported, or it's not.  If not, remove it from the cmdlet.

**Comment by RakeshMohanMSFT** [comment]
@PSdasAndi @plmcgrn Let me involve the service team to address this concern.

**Comment by adamedx** [comment]
@RakeshMohanMSFT , not sure how I can help. Do you know who owns this command? I can certainly give advice as to how to debug the request being made to the API, but I have not made contributions to this or any Azure modules. Feel free to ping me out of badn @RakeshMohanMSFT .
