### ISSUE TITLE
[Doc]: Documentation for New-AzStorageContainerSASToken doesn't explain -Permission well enough

### ISSUE THREAD

**Issue by andrewrondeau-optirtc** [Azure/azure-powershell#19734]
### Description

The documentation for New-AzStorageContainerSASToken doesn't explain what the valid values for -Permission are. All it states is "It is important to note that this is a string, like rwd"

This documentation should either:
- Explain in detail what all the valid characters are for this argument
- Or, provide a hyperlink to documentation that explains what the valid characters are for this argument.

See: https://learn.microsoft.com/en-us/powershell/module/az.storage/new-azstoragecontainersastoken?view=azps-8.3.0#-permission

**Comment by navba-MSFT** [comment]
@andrewrondeau-optirtc  Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@andrewrondeau-optirtc The above PR has been filed and it is currently under review. In the meantime, if you have any further queries, please do let us know.
