### ISSUE TITLE
[Az.Automation 1.8.0] Get-AzAutomationHybridRunbookWorkerGroup and Get-AzAutomationHybridWorkerGroup

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#19745]
### Description

Why do we have `Get-AzAutomationHybridRunbookWorkerGroup` and `Get-AzAutomationHybridWorkerGroup` cmdlets? It looks like they are doing the same job.

Same question for `Remove-AzAutomationHybridRunbookWorkerGroup` and `Remove-AzAutomationHybridWorkerGroup`.

**Comment by navba-MSFT** [comment]
@alexandair Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@alexandair They provide the same functionality. We recommend using [Get-AzAutomationHybridRunbookWorkerGroup](https://learn.microsoft.com/en-us/powershell/module/az.automation/get-azautomationhybridrunbookworkergroup?view=azps-9.0.0) and [Remove-AzAutomationHybridRunbookWorkerGroup](https://learn.microsoft.com/en-us/powershell/module/az.automation/remove-azautomationhybridrunbookworkergroup?view=azps-9.0.0)  cmdlets. The other two cmdlets would be deprecated from next release. Hope this answers. Please feel free to reopen the issue if you have any follow-up questions.
