### ISSUE TITLE
Get-AzureRMResource needs improvements

### ISSUE THREAD

**Issue by philmea** [Azure/azure-powershell#1975]
I don't really understand why I cannot enumerate all resources in a resource group using this cmdlet. I also would like to know why it cannot take Get-AzureRmResourceGroup from the pipline.

**Comment by ravbhatnagar** [comment]
@philmea - You can use Find-AzureRmResource to enumerate all resources in a resource group. Piping also works for this scenario.

**Comment by carlocardella** [comment]
Still, it does not seem to work as one would expect: below I'm looking for a specific resource type with FindAzureRmResource and piping the output to Get-AzureRmResource to get those resource details. Anyway I get a bunch of errors the the entire list of resoruces is returned, not the ones coming from Find-AzureRmResource: 



PS 08:03:05 > $s = Find-AzureRmResource -ResourceType microsoft.classiccompute/domainnames | Get-AzureRmResource
Get-AzureRmResource : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:80
+ ... sourceType microsoft.classiccompute/domainnames | Get-AzureRmResource
+                                                       ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (@{Name=ncus-eve...e-3f9e62a3fc92}:PSObject) [Get-AzureRmResource], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
 
Get-AzureRmResource : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:80
+ ... sourceType microsoft.classiccompute/domainnames | Get-AzureRmResource
+                                                       ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (@{Name=ncus-eve...e-3f9e62a3fc92}:PSObject) [Get-AzureRmResource], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
 
Get-AzureRmResource : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:80
+ ... sourceType microsoft.classiccompute/domainnames | Get-AzureRmResource
+                                                       ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (@{Name=ncus-job...e-3f9e62a3fc92}:PSObject) [Get-AzureRmResource], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
 
[...]
 




PS 08:03:25 > $s.ResourceType
Microsoft.ClassicNetwork/reservedIps
Microsoft.ClassicNetwork/reservedIps
Microsoft.ClassicNetwork/virtualNetworks
Microsoft.EventHub/namespaces
Microsoft.ServiceBus/namespaces
Microsoft.ServiceBus/namespaces
Microsoft.ServiceBus/namespaces
Microsoft.Sql/servers
Microsoft.Sql/servers/databases
Microsoft.Sql/servers/databases
Microsoft.Sql/servers
Microsoft.Sql/servers/databases
Microsoft.Sql/servers/databases
Microsoft.Sql/servers
Microsoft.Sql/servers/databases
Microsoft.Sql/servers/databases
Microsoft.Sql/servers
Microsoft.Sql/servers/databases
Microsoft.Sql/servers/databases
Microsoft.Cache/Redis
Microsoft.ClassicStorage/storageAccounts
Microsoft.ClassicStorage/storageAccounts
Microsoft.ClassicStorage/storageAccounts
Microsoft.ClassicStorage/storageAccounts
Microsoft.ClassicStorage/storageAccounts
Microsoft.ClassicStorage/storageAccounts
Microsoft.ClassicStorage/storageAccounts
Microsoft.ClassicStorage/storageAccounts

[...]

**Comment by ravbhatnagar** [comment]
@carlocardella - Can you please explain your scenario? What information were you trying to get when you were piping the result of Find-AzureRmResource to Get-AzureRmResource?

**Comment by carlocardella** [comment]
I was trying to read the cscfg settings (the "Property" value) returned for a PaaS cloud service; I need to get all cloud services in a given subscription and read some value from the cscfg. 
It seemed natural to get the list of services (with Find-AzureRmResource) and pipe it to get what I need (if I explicitly pass the resource name to Get-AzureRmResource I get what I need). 
According to https://msdn.microsoft.com/en-us/library/mt652503.aspx, all Resource* related properties (ResourceName, ResourceType etc...) accept pipeline input, so I expected it to work

**Comment by ravbhatnagar** [comment]
Find-AzureRmResource now supports ResourceNameEquals and ResourceGroupNameEquals for exact matching. So you can use it to list all the resources in a resource group.
