### ISSUE TITLE
[Feature]: Restore deleted managed HSM

### ISSUE THREAD

**Issue by jesshaines** [Azure/azure-powershell#19794]
### Description of the new feature

It appears no cmdlet currently exists that will recover a soft-deleted HSM via Powershell

Documentation --> https://learn.microsoft.com/en-us/azure/key-vault/managed-hsm/recovery?tabs=azure-powershell#managed-hsms-powershell

There is no option to restore Managed HSM via PowerShell --> Reference https://github.com/MicrosoftDocs/azure-docs/issues/99621

Undo-AzKeyVaultRemoval doesn't have an option to recover deleted Managed HSM and Undo-AzKeyVaultRemovalManagedHSM is not available.

Please create an option to use Undo-AzKeyVaultRemoval to recover Managed HSM or create dedicated PowerShell command to recover soft-deleted HSM via PowerShell (Example Undo-AzKeyVaultRemovalManagedHSM)

Thank you!

**Comment by BethanyZhou** [comment]
Hi @jesshaines , you can expect a cmdlet named `Undo-AzKeyVaultManagedHsmRemoval` to recover a deleted managed HSM on Nov 1st.
