### ISSUE TITLE
Remove-AzureRmResourceGroup does not bubble up errors if the operation fails

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/azure-powershell#1980]
Also, the following error message is given out -
ResourceGroupDeletionFailed: The deletion of resource group 'ms-dev' did not finish within allowed time. Resource group provisioning state rolled back. Please check audit logs for more details. 
The above implies that the resource group state was rolled back which is not the case.
Fix the error message too. And Update help to point out that the resources inside the RG will be deleted and what will happen if operation fails.

**Comment by jeffpatton1971** [comment]
Thanks for filing this @ravbhatnagar

**Comment by ravbhatnagar** [comment]
Couldnt get to it for the May release

**Comment by gandhiniraj** [comment]
Gaurav is going to get a repro

**Comment by shahabhijeet** [comment]
@ravbhatnagar can you take a look at this again and see if you can address this.
If not please close this.

**Comment by maddieclayton** [comment]
@ravbhatnagar Any update on this issue? It has been over a year, are you still able to repro the bug?

**Comment by cormacpayne** [comment]
It looks like the [underlying call](https://github.com/Azure/azure-powershell/blob/83f9aba6aa206b669abca70a444fa1840df56bb1/src/Resources/ResourceManager/SdkClient/ResourceManagerSdkClient.cs#L737) to delete the resource group is coming from the `Microsoft.Azure.Management.ResourceManager` SDK, which has been updated in the last few months. Please see if this issue repros in the latest version that we are using in the `Az.Resources` module.
