### ISSUE TITLE
Set-AzContext not working for managed identity in automation account runbook

### ISSUE THREAD

**Issue by connorourke** [Azure/azure-powershell#19801]
### Description

I am trying to execute a runbook in an automation account within azure.

I have set a managed identity following the instructions [here](https://learn.microsoft.com/en-us/azure/automation/enable-managed-identity-for-automation), then i issue the following in my runbook:

```
Connect-AzAccount -Identity
Set-AzContext -Subscription Subscription1
```
As instructed [here](https://connect-azaccount%20-identity%20set-azcontext%20-subscription%20subscription1/)

But i get the following error:

```
Set-AzContext : Please provide a valid tenant or a valid subscription.
 At line:134 char:1
 + Set-AzContext -Tenant $tenantId -Subscription $subscriptionId
```
I pass the tenantId and subscriptionId through as parameters, and have written them out to confirm they are correct.

### Issue script & Debug output

```PowerShell
Set-AzContext : Please provide a valid tenant or a valid subscription.
 At line:151 char:21
 + ... ionResult = Set-AzContext -Subscription $subscriptionId -DefaultProfi ...
 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 + CategoryInfo : CloseError: (:) [Set-AzContext], ArgumentException
 + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand
```

### Environment data

```PowerShell
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      15063  726
```

### Module versions

```PowerShell
Runtime version 5.1

Module versions 8.0.0
```

### Error output

```PowerShell
Set-AzContext : Please provide a valid tenant or a valid subscription.
 At line:151 char:21
 + ... ionResult = Set-AzContext -Subscription $subscriptionId -DefaultProfi ...
 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 + CategoryInfo : CloseError: (:) [Set-AzContext], ArgumentException
 + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand
```

**Comment by dingmeng-xue** [comment]
@connorourke , once you set managed identity, you need to provide subscription access permission to that identity. You can use `Get-AzContext -ListAvailable` to get all accessible contexts. Then, use `Set-Context` to select context you want to use. If the list is empty, it means the permission is incorrect.
