### ISSUE TITLE
Get all available RM VM Extensions

### ISSUE THREAD

**Issue by matousrokos** [Azure/azure-powershell#1982]
Hello Azure PS Team. Getting all available VM Extensions under ARM is task for several minutes now because its combination of at least 3 cmdlets. Please add ARM version of  Get-AzureVMAvailableExtension

**Comment by singhkay** [comment]
@matousrokos Completely understand the frustration! Unfortunately, there is currently not an API available that allows us to do this. There are folks working on improving the image/extension APIs at which point we'll be able to deliver a better experience.

**Comment by arcotek-ltd** [comment]
This was closed over a year ago. Still looking for this command. Has it been created?

**Comment by JulienFloris** [comment]
Workaround:
Get-AzureRmVmImagePublisher -Location "westeurope" | `
Get-AzureRmVMExtensionImageType | `
Get-AzureRmVMExtensionImage | Select Type, Version
Source: https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/features-windows#discover-vm-extensions
