### ISSUE TITLE
Is it possible to start a Pipeline from a Collaboration branch ?

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#19866]
### Discussed in https://github.com/Azure/azure-powershell/discussions/19846

<div type='discussions-op-text'>

<sup>Originally posted by **stetou** October 19, 2022</sup>
We do have needs to start Synapse Pipelines but from the Collaboration branch (or any other branch), instead of  using the pipelines that are in the Workspace ?
Is it possible using PowerShell ?</div>

**Comment by navba-MSFT** [comment]
@dingmeng-xue @stetou Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@dingmeng-xue @stetou We cannot start a Pipeline from a Collaboration branch by PowerShell cmdlet, it can be only done in live mode for now. Hope this answers.

**Comment by stetou** [comment]
thanks for your answer

**Comment by navba-MSFT** [comment]
@stetou Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by dingmeng-xue** [comment]
@navba-MSFT , is there way to allow @stetou to raise feature request to Synapse?

**Comment by navba-MSFT** [comment]
Yes @dingmeng-xue . 

@stetou Please post and share this idea with the Synapse Analytics team here: https://feedback.azure.com/d365community/forum/9b9ba8e4-0825-ec11-b6e6-000d3a4f07b8

**Comment by stetou** [comment]
Thank you
Here is my request to Synapse
https://feedback.azure.com/d365community/idea/97433269-7559-ed11-a81b-000d3ae5ae95
