### ISSUE TITLE
[Feature]: Enhance Get-AzAksNodePool to return current node image version

### ISSUE THREAD

**Issue by C-Meinert** [Azure/azure-powershell#19893]
### Description of the new feature

Update `Get-AzAksNodePool` to also return the current node image version. I would like to use this data along with data from `Get-AzAksNodePoolUpdateProfile` to determine if there is an update available for the node image.

Looking at the debug output the data already seems to be returned on the api request as `nodeImageVersion` but it is not part of the PS Object that is returned by the command.

**Comment by dingmeng-xue** [comment]
We will evaluate this feature request.
