### ISSUE TITLE
Set-AzureRmVmDscExtension Holds Session Open Until Success or Fail Notification

### ISSUE THREAD

**Issue by GamerLivingWill** [Azure/azure-powershell#1991]
Greetings!

This issue is currently being experienced in Azure.Compute module 1.2.4.

I've noticed that the Set-AzureRmVmDscExtension cmdlet holds the session open until it receives a completion notification of success or failure.  This breaks automation if you're looking to build a function to deploy to multiple systems.  

Furthermore, the Verbose parameter returns nothing, meaning you can't get any meaningful status while it's working.  

You need to either run the command as a job (which running multiple jobs can cause issues with resources on your source machine, as well as the fact that you have to login to Azure in each instance you spool up), or you have to run the command one at a time, which can cause issues when you need to rapidly deploy to multiple systems.  

As it currently stands, a new session has to be opened in order to be able to observe the progress of the extension with Get-AzureRmVmDscExtensionStatus.

I have a very large client that is operating a number of ARM systems (100+) that need to have a DSC configuration deployed to them to get them compliant with company standards.  This is going to cause some issues with getting those systems remediated quickly.

Many thanks in advance!

**Comment by jokeeffeBP** [comment]
I'm seeing something similar - and the lack of Verbose output is making it difficult to troubleshoot.

The Set-AzureRmVmDscExtension cmdlet never returns and can't be terminated with control-c - you have to kill the whole PS or PS-ISE window.

Also seems to be executing the config change about every minute according to the Audit Logs in the portal and not checking that the change has been made (which it is).

This behaviour happens even with very simple DSC eg:

`Configuration Sample_xWebsite_StopDefault
{
    param
    (
        # Target nodes to apply the configuration
        [string[]]$NodeName = 'localhost'
    )
    # Import the module that defines custom resources
    Import-DscResource -Module xWebAdministration
    Node $NodeName
    {
        # Install the IIS role
        WindowsFeature IIS
        {
            Ensure          = "Present"
            Name            = "Web-Server"
        }
        # Stop the default website
        xWebsite DefaultSite
        {
            Ensure          = "Present"
            Name            = "Default Web Site"
            State           = "Stopped"
            PhysicalPath    = "C:\inetpub\wwwroot"
            DependsOn       = "[WindowsFeature]IIS"
        }
    }
}`

Not sure if this should be a separate bug to 1991 - I'll let you decide!

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
