### ISSUE TITLE
New-AzureRmAutomationVariable Encryption parameter mandatory

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-powershell#1994]
The Encryption parameter for New-AzureRmAutomationVariable is mandatory but doesn't make a lot of sense IMO. Encryption is something you explicitly want. Not something you explicitly don't want. I would prefer the parameter to be interchanged with a switch instead or at least drop the mandatory requirement.

**Comment by jodoglevy** [comment]
Hi Ben - this is by design. We want to make sure the user consciously considers whether the value they are giving us should be kept secret or not. We don't want users to accidentally forget to include this parameter and end up exposing secrets to our service in plain text.
