### ISSUE TITLE
vWAN vHub address space update

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#19956]
### Discussed in https://github.com/Azure/azure-powershell/discussions/19564

<div type='discussions-op-text'>

<sup>Originally posted by **caofuuwe79qqvb** September 22, 2022</sup>
![image](https://user-images.githubusercontent.com/114128190/191657164-83f56539-05e3-4fb5-82b0-d45f9cfe6b58.png)</div>

**Comment by navba-MSFT** [comment]
@dingmeng-xue Refer https://github.com/Azure/azure-powershell/issues/19568 this GitHub thread for details.
