### ISSUE TITLE
Get-AzStorageContainer requires access to 'Microsoft.Storage/storageAccounts/listKeys/action' in order to list containers 

### ISSUE THREAD

**Issue by cnash-reply** [Azure/azure-powershell#19965]
### Description

Is there a way in PowerShell to allow users with the Reader role to get a list of storage account containers and properties?  Get-AzStorageContainer seems to require key access, but that will give full access to the container.

For Context...
Due to security guidelines, can't allow some accounts to see the contents of storage containers, but we do have the need for those users to be able to list containers and see the properties like last modified, and public access level.  This works in the portal, but we want to be able to automat within powershell.

Thanks!

Nash

### Script or Debug output

```PowerShell
Get-AzStorageContainer: The client '{USERNAME}' with object id '{OBJECTID}' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '{STORAGE_ACCOUNT_REFERENCE}' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     4.9.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle…}
```

**Comment by SaurabhSharma-MSFT** [comment]
@cnash-reply We are looking into it and get back to you for any additional information.

**Comment by blueww** [comment]
@cnash-reply 

Would you please give more details to help investigation of the issue?
1. After repro this issue , run `get-command Get-AzStorageContainer`. We would like to see where the cmdlet come from. Because from the cmdlet code, we don't see a logic to list key of the account.
2. The full script to repro this issue (hide credential), include how you prepare each parameter of `Get-AzStorageContainer`
3. For the AD user whose credentail is used to run the cmdlet, what's the role/permission it has? (I use an AD user with "[Storage Blob Data Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-contributor)" role, and it works well in list containers. )

**Comment by cnash-reply** [comment]
@blueww Thnaks for your patients on my response.  Here are the additional details you asked for:

1. Here is the results I get when I run 'get-command Get-AzStorageContainer'
``` 

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-AzStorageContainer                             4.9.0      Az.Storage
```

2. Here is a script that demonstrates what I am seeing:
``` $subName = "{Subscription Name Here}"

$sub = Get-AzSubscription -SubscriptionName $subName -ErrorAction Stop
Set-AzContext -SubscriptionId $sub.Id -TenantId $sub.TenantId 

$storageAccounts = Get-AzStorageAccount 

$storageAccount = $storageAccounts[0]

Write-Output "Storage Account: $($StorageAccount.StorageAccountName)"

# Get The Storage Account Context
$storageContext = $storageAccount.Context

$containers = Get-AzStorageContainer -context $storageContext -ErrorAction Stop

$containers.Length
```

3. Debug Output
```
Get-AzStorageContainer: 
Line |
  16 |  … ontainers = Get-AzStorageContainer -context $storageContext -ErrorAct …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The client '{username}' with object id '{objectid' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '{scope}' or the scope is invalid. If access was recently granted, please refresh your credentials.
0
```
4. The use has 'Read' role only.  

Thanks for the help on this.

**Comment by blueww** [comment]
@cnash-reply

Thanks for the reply!

From the sciprt, I see you created the storage context from `$storageAccount.Context`. The storage account property Context is created with Shared key credential, Powershell need get the storage account key in the backend to create it (the get storage account key need perform action 'Microsoft.Storage/storageAccounts/listKeys/action'). 
And `$storageAccount.Context` is a lazy property, so we will only create the property when first use it. As the first time you use it is in `Get-AzStorageContainer`, so the error report when you run this cmdlet.

If you still want to call `Get-AzStorageContainer` with shared key credential, you need give the login AAD user access to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' , you can find which buildin roles has the permission in https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles.

Another way is run `Get-AzStorageContainer` with AAD credentail, but the container public access can't be get with oauth credentail per server limitation. To create a storage context with AAD credentail, run : `$storageContext = New-AzStorageContext -StorageAccountName $storageAccountName`, you need fist login Powershell with an AAD user which has permission to run action 'Microsoft.Storage/storageAccounts/blobServices/containers/read'
