### ISSUE TITLE
[Insights] Create automation test to cover null object exceptions in diagnostic settings commands

### ISSUE THREAD

**Issue by vcanaa** [Azure/azure-powershell#1997]
DiagnosticSettings commands can't throw null pointer when Logs or Metrics are not defined for the resource.

Related fix:
https://github.com/Azure/azure-powershell/pull/1996

Fix was verified manually and now needs automation tests.

**Comment by hovsepm** [comment]
This is fixed. Should be available in the next release (end of March).
