### ISSUE TITLE
AzSecurityInsights - Get-AzSentinelIncident  - Filter doesn't work

### ISSUE THREAD

**Issue by rhavenn** [Azure/azure-powershell#19983]
### Description

The `-Filter` parameter for the `AzSecurityInsights - Get-AzSentinelIncident` module command doesn't seem to be implemented / documentation isn't clear on how to make it work.

Run it without the requested "string" input and you get a warning to supply a "string". Okay, so I supply a "string" and then you get a warning that the `Get-AzSentinelIncident_List` isn't found.

### Issue script & Debug output

```PowerShell
Get-AzSentinelIncident -ResourceGroupName $AzSentinelWorkspaceResourceGroup -WorkspaceName $AzSentinelWorkspaceName -Filter
```
returns:
```
Get-AzSentinelIncident: Missing an argument for parameter 'Filter'. Specify a parameter of type 'System.String' and try again.
```
then running:
```PowerShell
Get-AzSentinelIncident -ResourceGroupName $AzSentinelWorkspaceResourceGroup -WorkspaceName $AzSentinelWorkspaceName -Filter 'date'
```

returns:
```
WARNING: Get-AzSentinelIncident_List is not found. The most similar Azure PowerShell command is:
        Get-AzSentinelIncident
Get-AzSentinelIncident_List: Could not find a property named 'date'
```

### Environment data

```PowerShell
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Linux 5.19.17-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Oct 24 14:59:25 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Script     2.10.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     3.0.0                 Az.SecurityInsights                 {Get-AzSentinelAlertRule, Get-AzSentinelAlertRuleAction, Get-AzSentinelAlertRuleTemplate, Get-AzSentinelAutomationRule…}
```

**Comment by RakeshMohanMSFT** [comment]
@rhavenn Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@rhavenn You need to pass a value to it, like -Filter "status = Closed"

**Comment by rhavenn** [comment]
Is this documented anywhere on what to pass to it or what's possible? Is it just passing  items to the API? So, the API docs would be applicable?  I will try as you suggest and see what I get, but in reading the documents there is no indication that's how you set it to filter stuff or what values can be passed.

**Comment by RakeshMohanMSFT** [comment]
Its a simple json filter. I will add an example in the documentation.
