### ISSUE TITLE
New-AzureRmResource fails to execute because DefaultContext is not set?

### ISSUE THREAD

**Issue by moswald** [Azure/azure-powershell#1998]
`New-AzureRmResource` exists in powershell's tab-completion list, and I've successfully called Login-AzureRmAccount, but this is the error I get after any call to `New-AzureRmResource`:

```
New-AzureRmResource : Argument 'New-AzureRmResource' is not recognized as a cmdlet: Method not found:
'Microsoft.Azure.Commands.Common.Authentication.Models.AzureContext
Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.get_DefaultContext()'.
At line:1 char:1
+ New-AzureRmResource
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-AzureRmResource:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CmdletNotFoundException
```

**Comment by markcowl** [comment]
@moswald sorry for the bad experience.  This can happen if there are mixed incompatible versions of the resource manager and profile cmdlets.  You should be able to resolve by updating both modules, or by running the latest installer: https://github.com/Azure/azure-powershell/releases/download/v1.2.2-March2016/azure-powershell.1.2.2.msi 
 which will clean up older versions of gallery modules.

**Comment by moswald** [comment]
Thanks for the quick response! I'll give that a try asap.

**Comment by moswald** [comment]
That worked. Thanks for the help.
