### ISSUE TITLE
Timeline for Az.Consumption Update

### ISSUE THREAD

**Issue by DevonK3** [Azure/azure-powershell#19999]
### Description

I've been using Az.Consumption but was told a new version would be available in 2022 that uses the updated API and includes items such as $budget.Scope, $budget.ResourceGroup, etc. As it is now, I cannot determine from a budget what its scope is.
```
$budget = Get-AzConsumptionBudget
$bid = $budget.Id
$rg = (Get-AzResource -ResourceId -$bid).Name # errors out if Scope is Subscription)
```

**Comment by navba-MSFT** [comment]
@DevonK3 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@DevonK3 May I know from where did you get an update on the newer version of the Consumption APIs?

**Comment by DevonK3** [comment]
I was referring to PWSH, but thanks for the `az consumption` reference. I'll use this instead since PWSH doesn't support full Budget object operations. I try to not use `az` unless I have to since it is ... [redacted] ... not an enjoyable experience.

I received the Consumption API update some time back during another MSFT conversation about "Create Budget" being broken in az, pwsh, and Terraform, but working in Python SDK. Also, the MSFT Learn page notes that the Module is using old, unsupported APIs. Lastly, the `az consumption` command says it is in Preview.

I may be remembering the MSFT rep response (it's been a long time) but I thought they said that Consumption was being moved to Billing or some other Module / Module family.

But whatever the case, I was asking for an update on when the appropriate PowerShell Module (API, et al) for Budgets would be published so we can plan accordingly for our DevOps changes.

Thanks, again!

**Comment by navba-MSFT** [comment]
@DevonK3 Apologies for the late reply. I have got the confirmation from the Product Owners that, currently there are no plans to update the PS cmdlets for Az.Billing module. So the action plan is to invoke the [Budget List REST API](https://learn.microsoft.com/en-us/rest/api/consumption/budgets/list?tabs=HTTP) directly from PowerShell. This Rest APi will lists all budgets for the defined scope.


Name | In | Required | Type | Description
-- | -- | -- | -- | --
scope | path | True | string | The scope associated with budget operations. This includes '/subscriptions/{subscriptionId}/' for subscription scope, '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}' for resourceGroup scope, '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}' for Billing Account scope, '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/departments/{departmentId}' for Department scope, '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/enrollmentAccounts/{enrollmentAccountId}' for EnrollmentAccount scope, '/providers/Microsoft.Management/managementGroups/{managementGroupId}' for Management Group scope, '/providers/Microsoft.Billing/billingAccounts/{billingAccountId}/billingProfiles/{billingProfileId}' for billingProfile scope, 'providers/Microsoft.Billing/billingAccounts/{billingAccountId}/invoiceSections/{invoiceSectionId}' for invoiceSection scope.

Hope this helps.

**Comment by jikuja** [comment]
>  I have got the confirmation from the Product Owners that, currently there are no plans to update the PS cmdlets for Az.Billing module.

Is there a public list of modules that are left unmaintained?
