### ISSUE TITLE
Issues with Az module 9.1.0

### ISSUE THREAD

**Issue by hckenmiller** [Azure/azure-powershell#20006]
### Description

Issues with Az 9.1.0 running Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber 

### Issue script & Debug output

```PowerShell
Error message 
was At C:\Users\VssAdministrator\Documents\WindowsPowerShell\Modules\Az.DataProtection\1.0.0\custom\Cmdlets\Platform\Va
ult\Set-AzDataProtectionMSIPermission.ps1:156 char:19
+                   | Where-Object { ($_.Scope -eq $KeyVaultId -or $_.S ...
+                   ~
An empty pipe element is not allowed.
At C:\Users\VssAdministrator\Documents\WindowsPowerShell\Modules\Az.DataProtection\1.0.0\custom\Cmdlets\Platform\Vault\
Set-AzDataProtectionMSIPermission.ps1:180 char:15
+               | Where-Object { ($_.Scope -eq $DataSourceId -or $_.Sco ...
+               ~
An empty pipe element is not allowed.
At C:\Users\VssAdministrator\Documents\WindowsPowerShell\Modules\Az.DataProtection\1.0.0\custom\Cmdlets\Platform\Vault\
Set-AzDataProtectionMSIPermission.ps1:204 char:15
+               | Where-Object { ($_.Scope -eq $SnapshotResourceGroupId ...
+               ~
An empty pipe element is not allowed.
At D:\a\_temp\22cf96b1-bbff-4894-844e-d9336ba06ba4.ps1:4 char:1
+ . 'D:\a\1\s\deployment\scripts\Deploy-Databricks-Workspace.ps1' -clie ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Deploy-Databricks-Workspace.ps1
```

### Environment data

```PowerShell
Its running in a pipeline using Powershell@2 task version 2.210.0
```

### Module versions

```PowerShell
Its running in a pipeline using Powershell@2 task version 2.210.0
```

### Error output

```PowerShell
Its running in a pipeline using Powershell@2 task version 2.210.0
```

**Comment by dingmeng-xue** [comment]
@hckenmiller , thanks for reporting. Could you share exact script you are using on PowerShell@2 task and parameters of that task?

**Comment by hckenmiller** [comment]
It doesn't matter which powershell task, they all fail the same way. Here is one of the powershell tasks. 

  - task: PowerShell@2
    displayName: Deploy Databricks Workspace
    inputs:
      #verbosePreference: 'default' # Optional. Options: default, stop, continue, silentlyContinue
      #verbosePreference: 'continue'
      filepath: "$(System.DefaultWorkingDirectory)/deployment/scripts/Deploy-Databricks-Workspace.ps1"
      arguments: "-clientTenantId ${{variables.TenantID}} -resourceGroupName ${{variables.ResourceGroupName}} - 
      databricksWorkSpaceName ${{variables.Workspace}} -dosDataClientId $(dos-fhir-service-client) -dosDataClientSecret $(dos- 
      fhir-service-client-secret) -secretNames ${{variables.SecretNames}} -client ${{parameters.ClientCode}} -location 
      ${{variables.Region}} -managedResourceGroupName ${{variables.ManagedResourceGroupName}} -skuType 
      ${{variables.SkuType}}"

**Comment by dingmeng-xue** [comment]
@hckenmiller , It seems `Deploy-Databricks-Workspace.ps1` contains API call to `Set-AzDataProtectionMSIPermission.ps1`. If yes, please share snippet of your script.

**Comment by hckenmiller** [comment]
I'm not calling it in my code, I don't know what it is for.

**Comment by dingmeng-xue** [comment]
@hckenmiller , please check whether [Az.DataProtection v1.0.1](https://www.powershellgallery.com/packages/Az.DataProtection/1.0.1) has addressed your issue.
