### ISSUE TITLE
[Doc]: Version 9.1.0 not present in versions-manifest.json

### ISSUE THREAD

**Issue by HUMBERP** [Azure/azure-powershell#20011]
### Description

Latest version 9.1.0 ist not present within https://raw.githubusercontent.com/Azure/az-ps-module-versions/main/versions-manifest.json.
If trying to add this version 9.1.0 to runner-images execution the creation of the image fails.

**Comment by dingmeng-xue** [comment]
Hi @HUMBERP , thanks for reporting. We are not working on repo Azure/az-ps-module-versions. Please raise your request to that repo. Thanks.
