### ISSUE TITLE
[Feature]: Optimize SPN authentication flow

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#20013]
### Description of the new feature

Following this article https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-acquire-token-silently

> When you acquire an access token using the Microsoft Authentication Library for .NET (MSAL.NET), the token is cached. When the application needs a token, it should first call the AcquireTokenSilent method to verify if an acceptable token is in the cache. In many cases, it's possible to acquire another token with more scopes based on a token in the cache. It's also possible to refresh a token when it's getting close to expiration (as the token cache also contains a refresh token).
> For authentication flows that require a user interaction, MSAL caches the access, refresh, and ID tokens, as well as the IAccount object, which represents information about a single account. Learn more about [IAccount](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.iaccount?view=azure-dotnet&preserve-view=true). For application flows, such as [client credentials](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#client-credentials), only access tokens are cached, because the IAccount object and ID token require a user, and the refresh token is not applicable.
> The recommended pattern is to call the `AcquireTokenSilent` method first. If AcquireTokenSilent fails, then acquire a token using other methods.

Azure PowerShell needs to use `AcquireTokenSilent` method to fetch access token for SPN authentication flow. If it fails, Azure PowerShell needs to acquire access token using secret, cert, or other credentials.

**Comment by jiasli** [comment]
Azure CLI worked on this before in https://github.com/Azure/azure-cli/issues/13276
