### ISSUE TITLE
[Doc]: Question about New-AzApplicationGatewayProbeConfig

### ISSUE THREAD

**Issue by pgbfnf** [Azure/azure-powershell#20043]
### Description

Can you please clarify the difference (if any) between the following 2 commands, on each of their respective pages?
Add-AzApplicationGatewayProbeConfig
New-AzApplicationGatewayProbeConfig

The only difference I can find is that "New-" has an additional "-Port" option.

If one of these commands only works on V2 gateways (as opposed to V1), if would be useful to call that out. The "-Port" reference makes me think that maybe it's a V2 app gateway specific command.

Thanks!

**Comment by SaurabhSharma-MSFT** [comment]
@pgbfnf Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaurabhSharma-MSFT** [comment]
@pgbfnf Regarding these two commands, I think a better way to understand will be via this [tutorial ](https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-create-probe-ps#create-an-application-gateway)
The difference I think here is New-AzApplicationGatewayProbeConfig is used when you are creating a New Application Gateway
![image](https://user-images.githubusercontent.com/38112130/202406850-78c9f4f4-40a5-450f-a3e6-1c4223443553.png)
And Add-AzApplicationGatewayProbeConfig is used when you are adding a Health probe to an existing Application Gateway.
![image](https://user-images.githubusercontent.com/38112130/202407172-cddcc92b-2cca-484d-93f3-6c0fad102b12.png)
Please let me know if you have any other questions. Thanks.
