### ISSUE TITLE
Cant find Get-AzureResourceProviderLog

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-powershell#2004]
Cant find Get-AzureResourceProviderLog

[Here is the output](https://gist.github.com/eosfor/21dc8867cde7f0fe7114)

**Comment by ravbhatnagar** [comment]
During the 1.0 PS release, a bunch of the log cmdlets were consolidated. So now you can use Get-AzureRmLog -ResourceProvider to get the desired results.

**Comment by ravbhatnagar** [comment]
Closing (by design).
