### ISSUE TITLE
Account and subscription cmdlets fail with 'Object reference not set to an instance of an object'

### ISSUE THREAD

**Issue by mmaitre314** [Azure/azure-powershell#2005]
After some time (a day?) basic cmdlets like Add-AzureAccount, get-AzureAccount, Get-AzureSubscription stop functioning and error out with 'Object reference not set to an instance of an object'

![azure_capture](https://cloud.githubusercontent.com/assets/8584604/14024837/61af8a92-f1a8-11e5-8982-9657c3b5ef88.PNG)

The only way I found to get out of that was to close all PS command windows and reopen them. Our deployments are all failing.

This is with Azure Powershell 1.2.2 (March 3, 2016).

**Comment by hovsepm** [comment]
@mmaitre314 please capture and provide debug logs when it will happen again. You can do that by running following:

```
$DebugPreference = "Continue"
Add-AzureAccount -Debug
```

**Comment by avishnyakov** [comment]
Same here with Login-AzureRmAccount, having the following one:
```
Login-AzureRmAccount : Object reference not set to an instance of an object.
```

Random Login-AzureRmAccount : Object reference not set to an instance of an object. #2576

**Comment by avishnyakov** [comment]
@hovsepm what's the best way to troubleshoot that?
Set $DebugPreference = "Continue" and -Debug, nothing happen. What supposed to happen?

**Comment by markcowl** [comment]
Closing in preference of #2576  There is a candidate fix for this, scheduled to go out with the September release.
