### ISSUE TITLE
[Eng]: User feedback from AKS blade of Azure portal 

### ISSUE THREAD

**Issue by nanunna** [Azure/azure-powershell#20074]
### Description

Powershell side bug for - https://github.com/Azure/azure-cli/issues/24594

**Comment by dingmeng-xue** [comment]
@nanunna , could you explain further about the feature gap?

**Comment by nanunna** [comment]
Just want to relay the feedback from user on azure portal to your team. It seems users would like to see kubernetes objects data that is currently available on azure portal in Az cli/powershell.

**Comment by YanaXu** [comment]
Hi @nanunna , I'm trying to understand the requirement. I have a few questions. Could you check if you can answer them?

- Customer wants to get the data about "AksServicesAndIngresses.ReactView", right? Where do they get the data of "Value/Effort/Overall" in the table?
- Can Azure portal or Azure Cli provide the data now? If yes, could you provide a screenshot of how it looks like or a guide page to describe it?
- Any AKS swagger APIs return the data?

**Comment by YanaXu** [comment]
Hi @nanunna, I'm closing this issue since it's been idle for a long time. Please feel free to reopen it and ping me if you have the answers to my questions.
