### ISSUE TITLE
AzureRM interfering with Az

### ISSUE THREAD

**Issue by FredrikDahlberg** [Azure/azure-powershell#20089]
### Description

We migrated to Az years ago but it won't work for some reason if AzureRm is still installed. Unistalling AzureRM does not change this. The only way seems to be to delete the AzureRM files manually. Is there a complete list of all the files that belongs to AzureRM that needs to be removed for Az to work?

### Issue script & Debug output

```PowerShell
X
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22000.832
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.832
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
X
```

### Error output

```PowerShell
X
```

**Comment by dingmeng-xue** [comment]
@FredrikDahlberg , thanks for contacting us. You can try and adjust below code in Windows PowerShell. Please ensure you execute script before any AzureRM is imported. Once module is imported, it cannot be deleted because .NET framework doesn't allow to unload loaded assembly.

```
$modules = Get-Module AzureRm* -ListAvailable
foreach($module in $modules) {
  if($module.CompanyName -eq 'Microsoft Corporation' -and $module.CompanyName -eq $module.Author -eq 'Microsoft Corporation') {
    Uninstall-Module $module 
  }
}
```

**Comment by FredrikDahlberg** [comment]
`Get-Module AzureRm* -ListAvailable`

This does not list the modules since they are "uninstalled". The problem is that they still somehow gets loaded. The fix seems to be to delete the actual files. The question was how to find every file that belongs to AzureRM so they can be deleted.

**Comment by dingmeng-xue** [comment]
If you believe its file are still loaded, you can execute below code after module is loaded. The script lists all assemblies and their path. You can get where they come from.

```
[System.AppDomain]::CurrentDomain.GetAssemblies() | Where-Object Location | Sort-Object -Property FullName | Select-Object -Property FullName, Location
```

Another potential reason is AzureRM module was installed by your script or dependent modules. Please double check.
