### ISSUE TITLE
Azure China: Premium KeyVault unavailable

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#2009]
Seems Premium KeyVault is not supported in China East and China North.

 New-AzureRmKeyVault -VaultName "myfirstcnkv" -ResourceGroupName my "firstcnrgp" -Location "**China East**" -Sku **premium**
**New-AzureRmKeyVault : SkuNotSupported: Premium vaults are not supported in this region.**
At line:1 char:1
+ New-AzureRmKeyVault -VaultName "myfirstcnkv" -ResourceGroupName "firstcnrgp" -Lo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmKeyVault], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.NewAzureKeyVault

Please let me know when this will be supported and any official documentation on Premium Tier is not supported in China.

Thanks,
Pradebban Raja

**Comment by pomortaz** [comment]
There is no plan to support premium vaults in China.

**Comment by Pradebban** [comment]
@pomortaz, Is this documented in any official release notes/ online documentation ?

**Comment by pomortaz** [comment]
It is on the pricing page (in Chinese) on [Azure China website](https://www.azure.cn/zh-cn/).
We don't have any English document for that, but I have contacted the team for the missing documentation.

**Comment by Pradebban** [comment]
@pomortaz With no plans in place, should i assume its not going to make it for at least 2 years ? Can someone give a timeline on when a plan would be in place. We need to convey the same to the customer

**Comment by pomortaz** [comment]
@Pradebban, there is no plan, timeline or discussion on supporting premium vault in China.

**Comment by pratikmehta9** [comment]
Did we add any English documentation for this yet?
