### ISSUE TITLE
[Doc]: Set-AzAlertProcessingRule has misnamed parameter

### ISSUE THREAD

**Issue by ammarhasan76** [Azure/azure-powershell#20090]
### Description

https://learn.microsoft.com/en-us/powershell/module/az.alertsmanagement/set-azalertprocessingrule?view=azps-9.1.0

The *Syntax* parts of the page have a misnamed parameter.
AlertProcessingRule**Rule**Type is incorrect, whereas it should be AlertProcessingRuleType.

**Comment by navba-MSFT** [comment]
@ammarhasan76 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
