### ISSUE TITLE
[Doc]: Backup-AzKeyVaultCertificate example mistakenly uses Backup-AzKeyVaultkey

### ISSUE THREAD

**Issue by vincebowdren** [Azure/azure-powershell#20142]
### Description

The help documentation for the Backup-AzKeyVaultCertificate has an example where it uses the wrong cmdlet, using Backup-AzKeyVaultKey where it should be Backup-AzKeyVaultCertificate.

![image](https://user-images.githubusercontent.com/13331337/201929095-38b1f7f4-3c16-4be4-b261-82a28ba7c28a.png)

> **Backup-AzKeyVaultKey** -VaultName 'MyKeyVault' -Name 'MyCert' -OutputFile 'C:\Backup.blob'
> 
> C:\Backup.blob

(my highlight)

If you try to run this example, it fails with an error:

> Operation returned an invalid status code 'Forbidden' Code: Forbidden Message: Operation "backup" is not allowed on this Key, since it is associated with a certificate. Perform the operation on the corresponding certificate. For more information refer to https://docs.microsoft.com/en-us/azure/key-vault/certificates/about-certificates#composition-of-a-certificate

**Comment by dingmeng-xue** [comment]
@BethanyZhou , please correct example

**Comment by christianb7** [comment]
I have also just hit this issue. It also happens where certificates are included in Get-AzKeyVaultSecret. There appears to be no way to understand directly if the secret/key that is in the returned list is actually a certificate.

I believe that Get-AzKeyVaultSecret and Get-AzKeyVaultKey need to ONLY return secrets or keys.

**Comment by christianb7** [comment]
I am not sure this is much more information, however if I create a new vault, add a certificate in the certificate store and call the function Get-AzKeyVaultSecret then that secret will be returned. If I then call Backup-AzKeyVaultSecret for that item then it will fail as it isn't a secret, it is actually a certificate.

Hope that helps explain.

**Comment by BethanyZhou** [comment]
Hi @jlichwa , is it by design to we can't backup secret in certificate?

**Comment by jlichwa** [comment]
I assume that is a typo and Backup-AzKeyVaultCertificate should be used to backup certificate, individual components by itself cannot be back up.

**Comment by vincebowdren** [comment]
OP here. As far as I'm concerned, this issue should be closed. The documentation has been corrected, changing the example where it told you to use the wrong cmdlet (Backup-AzKeyVaultKey) to the correct cmdlet Backup-AzKeyVaultCertificate.

I'm not sure what christianb7's situation is; possibly they are mistakenly trying to use the wrong cmdlet, and they need to switch to using Backup-AzKeyVaultCertificate?
But in any case, if they are describing a problem with the cmdlets _when run_, then that is different from the issue I reported which was strictly a problem with the documentation.

**Comment by christianb7** [comment]
Hi @vincebowdren yes, it is a problem with the cmdlet when run. How we we get an issue raised for this please? This is where the cmdlets for both Get-AzKeyVaultSecret and Get-AzKeyVaultKey return certificates as well as secrets and keys respectively.

Chris

**Comment by vincebowdren** [comment]
Hi @christianb7 . This issue 20142 is about a documentation problem. If you have found a problem with the way the cmdlets run in practice, that's a different problem and you need to raise a different issue for it.
