### ISSUE TITLE
[Doc]: 

### ISSUE THREAD

**Issue by PlateSpinner** [Azure/azure-powershell#20152]
### Error in command in Example 1 

In Example 1, the password profile command references "IMicrosoftGraphPasswordProfile" space but that doesn't work. The one that works is "MicrosoftGraphPasswordProfile" (minus the preceeding 'I').

**Comment by RakeshMohanMSFT** [comment]
@PlateSpinner Thank you for reaching out, we are looking into it. Are you referring to New-MgUser commandlet?

**Comment by PlateSpinner** [comment]
I'm referring to the line that says
> `$pp = New-Object -TypeName "Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordProfile" -Property @{Password=$password}`

That "`IMicrosoftGraphPasswordProfile`" is wrong. PS throws an error when you try and use it.
But it works when I use "MicrosoftGraphPasswordProfile" (minus the preceeding 'I')

**Comment by RakeshMohanMSFT** [comment]
@PlateSpinner Thank you, I understand. Can you share of the link of the document you are referring to here?

**Comment by RakeshMohanMSFT** [comment]
Please reopen with further details.
