### ISSUE TITLE
New-AzPublicIpAddress and -zone = {}

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#20157]
### Discussed in https://github.com/Azure/azure-powershell/discussions/20141

<div type='discussions-op-text'>

<sup>Originally posted by **chillyjim** November 15, 2022</sup>
With the upcoming New-AzPubLicIpAddress wanting a "-Zone =" argument for a "-SKU = Standard" but blows up if you include it in a "Basic" SKU is it possible to so something like:

I would like to pass an argument as a variable something like:

If ($SKU -eq "Basic") {
$z = $null
}
Else {
$z = '-zone = {}'
}

$PIP = NewPublicIpAddress `
          -Name "$VmName-pip-$i" `
          -ResourceGroupName $vmInfo.ResourceGroupName `
          -Location $vmInfo.Location `
          -AllocationMethod Static `
          -sku $SKU $z

Thanks much</div>

**Comment by PramodValavala-MSFT** [comment]
@chillyjim What you are looking for is called [splatting](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting) where you can pass an object or array parameters to a cmdlet.

So, for your case, it would be something like this

```ps1
$z = {}
If ($SKU -neq "Basic") {
$z.Zone = {}
}

$PIP = NewPublicIpAddress -Name "$VmName-pip-$i"
-ResourceGroupName $vmInfo.ResourceGroupName -Location $vmInfo.Location
-AllocationMethod Static `
-sku $SKU @z
```
