### ISSUE TITLE
Is there any other way to retrieve all the data (aggregation) when using Get-Azmetric command in powershell?

### ISSUE THREAD

**Issue by maeganda11** [Azure/azure-powershell#20163]
### Description

Hi, does anyone able to retrieve all the data when using Get-AzMetric command in powershell?
By default, it will only shows the **Average** but not the **Minimum** ,**Maximum**,  **Total** and **Count**
.. unless specify the Aggregation type on the command.

Would like to ask if it is possible to show all data in one run (Average, Maximum, Minimum, Total and Count). Thank you.

Here is the command I use. 
$CPU = Get-AzMetric -ResourceId $VMname.Id -TimeGrain 00:15:00 -StartTime $st -EndTime $et -MetricName "Percentage CPU" -DetailedOutput 
$CPU.Data

![image](https://user-images.githubusercontent.com/108807464/202418961-443218b4-61a2-4282-b9ce-24f4f3675552.png)

**Comment by dingmeng-xue** [comment]
Hi @Maeganda11 , for VM resource, aggregation type only supports average. Please reference https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftcomputevirtualmachines

**Comment by hanhsia** [comment]
From this link, every metric supports only one Aggregation Type. But it's not correct. We can specify Aggregation type to get Maximum, Maximum and other aggregation type data. And if you call Get-AzMetricDefinition, you can get which aggregation type is supported for a specified resource. here is an example:
PrimaryAggregationType    : Average
SupportedAggregationTypes : {Average, Maximum, Minimum}
So the link you provided only means the primary aggregation type. I also want to know if there is a way to get all supported aggregation type data in one call.

**Comment by hanhsia** [comment]
From this link, every metric supports only one Aggregation Type. But it's not correct. We can specify Aggregation type to get Maximum, Maximum and other aggregation type data. And if you call Get-AzMetricDefinition, you can get which aggregation type is supported for a specified resource. here is an example:
PrimaryAggregationType    : Average
SupportedAggregationTypes : {Average, Maximum, Minimum}
So the link you provided only means the primary aggregation type. I also want to know if there is a way to get all supported aggregation type data in one call.

**Comment by dingmeng-xue** [comment]
Hi @hanhsia , Azure PowerShell's implementation bases on public API and doc. For further clarification, please wait support team or service team's answer.

**Comment by navba-MSFT** [comment]
@maeganda11 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@maeganda11 @hanhsia The Azure Monitor [List Metrics REST API](https://learn.microsoft.com/en-us/rest/api/monitor/metrics/list) expects the `aggregation` query string parameter.


aggregation | query |   | string | **The list of aggregation types (comma separated) to retrieve.**
-- | -- | -- | -- | --

When I invoked the below REST API directly as shown below:

https://management.azure.com//subscriptions/XXXXXXXX/resourceGroups/Allrg/providers/Microsoft.Compute/virtualMachines/MYVMNAME/providers/Microsoft.Insights/metrics?api-version=2018-01-01&aggregation=minimum%2Caverage%2Cmaximum

I got the desired output see below:

![image](https://user-images.githubusercontent.com/57353862/205016379-8d88731f-a1bf-4d57-b634-3fb36d599d9d.png)

Could you try to invoke the above REST API from powershell and check if that helps. ? Also refer this sample PS script in [this thread.](https://stackoverflow.com/a/60499127)
