### ISSUE TITLE
Set-AzureSqlDatabase: changing Service Objective is called on a different DB (1.2.2)

### ISSUE THREAD

**Issue by BenedekFarkas** [Azure/azure-powershell#2019]
I have a SQL Azure DB, let's call it "X". I create a copy of it to the same server, let's call the copy DB "Y". I make some changes to "Y", scale it up to S2 Standard tier and export it (scaling it up is required, otherwise the export fails due to the size of the DB). This is a process we run automatically by from our TeamCity instance every day on two different DBs and it's running smoothly.

However, the following error happened today for one of them (and while testing our process, I saw it once some time ago):

```
Set-AzureSqlDatabase : The operation cannot be performed on the database 'X' in its current state.
At (blablabla custom script)
+             Set-AzureSqlDatabase -ConnectionContext $connectionContex ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Set-AzureSqlDatabase], CommunicationException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.SqlDatabase.Database.Cmdlet.SetAzureSqlDatabase
```

**Please note that the error message mentions the DB "X", but I was attempting to change the Service Objective of "Y".**

I'm using the following parameters when calling `Set-AzureSqlDatabase`:
- ConnectionContext
- DatabaseName
- ServiceObjective
- Edition
- ErrorAction Stop
- Force

I would presume that the parameters got messed up along the way somehow (but by looking at the source code of this cmdlet that doesn't seem likely and then it should happen always or at least more often) OR the cause of the problem is that the DB copy operation (using `Start-AzureSqlDatabaseCopy` to start it and `Get-AzureSqlDatabaseCopy` to periodically query the status) was performed directly before the attempt to scale up the copied database.

Here's the log generated by the custom script to get an idea of the timeline of the copy operation in case the problem is that the copied database is still in an ambiguous state even after the copy operation is finished:

```
[04:06:26][Step 4/10] *****
[04:06:26][Step 4/10] Database copy starting...
[04:06:27][Step 4/10] *****
[04:06:27][Step 4/10] * 0% (PENDING)
[04:07:03][Step 4/10] * 0% (SEEDING)
[04:11:28][Step 4/10] * 100% (CATCH_UP)
[04:11:40][Step 4/10] *****
[04:11:40][Step 4/10] Database copy finished!
[04:11:40][Step 4/10] *****
[04:11:40][Step 4/10] 
[04:11:40][Step 4/10] Process exited with code 0
```

The status is queried every 10 seconds and printed if it's changed. `100% (CATCH_UP)` doesn't actually mean the copy operation is really complete: that's why there's a delay until the script finishes execution, because the operation is complete when the corresponding record from one of the `master` DB's tables is deleted - that's when `Get-AzureSqlDatabaseCopy` returns `$null`.

After this script finishes, there's a 16 second gap until `Set-AzureSqlDatabase` is called and then returns the exception above.

`catch [TLDRException] { Write-Host "Sorry for the long description!" }`

**Comment by markcowl** [comment]
@akromm Can you take a look?

**Comment by shivamatri1** [comment]
@BenedekFarkas Hi Benedek, I apologize for the delay in responding to this issue. I would like to work with you to get at the root cause of this. Are you still facing this issue and could you provide some more context about it.

**Comment by BenedekFarkas** [comment]
I don't have an exact repro on this (other than the process described above) and it only happened a couple of times before - haven't seen this happen for a long time. Considering that Azure back-end stuff and Azure PS changed so much since then, I think we can close this and I'll reopen if it occurs again.
