### ISSUE TITLE
Get-AzApiManagementDiagnostic not retrieve diagnostic configurations

### ISSUE THREAD

**Issue by kingwang-git** [Azure/azure-powershell#20190]
### Description

we like to do the following:
1.	Manually add a custom diagnostic for APIM instance in DEV.
2.	Attempt to export/extract the configuration via the script/api
3.	Using the exported file (json) as the base to automate it into the parameterized terraform script, and make is as part of the IaC.
4.	Apply the diagnostic changes to other APIM instances like TEST, STAGING and PROD.

![image](https://user-images.githubusercontent.com/64438599/203140640-142ee89f-76a8-4b44-b3f2-7fbb0091b13c.png)

Attempt to export/extract the configuration via the script/api : 
Get-AzApiManagementDiagnostic -Context $apimContext | convertto-json. 
I was expecting the api/azcli call to return all service level diagnostic configurations, like the name, edh-dev-apim-diag, the catalog groups, the log analytics workspace info, and so on. Furthermore, we could define multiple diagnostic definitions, and the exported file should contain all of them. 
But the azcli/API call does not retrieve any of the configuration info.

### Issue script & Debug output

```PowerShell
PS C:\tmp> Get-AzApiManagementDiagnostic -Context $context | convertto-json
WARNING: Resulting JSON is truncated as serialization has exceeded the set depth of 2.
{
  "DiagnosticId": "azuremonitor",
  "ApiId": null,
  "AlwaysLog": null,
  "LoggerId": "azuremonitor",
  "EnableHttpCorrelationHeader": null,
  "SamplingSetting": {
    "SamplingType": "fixed",
    "SamplingPercentage": 100.0
  },
  "FrontendSetting": {
    "Request": {
      "HeadersToLog": "",
      "Body": null
    },
    "Response": null
  },
  "BackendSetting": {
    "Request": {
      "HeadersToLog": "",
      "Body": null
    },
    "Response": null
  },
  "Id": "/subscriptions/**/resourceGroups/***/providers/Microsoft.ApiManagement/service/e***/diagnostics/azuremonitor",
  "ResourceGroupName": "***",
  "ServiceName": "***"
}
```

### Environment data

```PowerShell
PS C:\Users\wangki> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions
```PowerShell
PS C:\Users\wangki> Get-Module --listAvaialble
PS C:\Users\wangki> Get-Module Get-AzApiManagementDiagnostic
Empty
```

### Error output

```PowerShell
no error, but missing useful info
```

**Comment by RakeshMohanMSFT** [comment]
@kingwang-git Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@kingwang-git These are the APIM diagnostic information you can expect from any client tools (CLI, PowerShell) considering the fact that they all depend on the [REST API](https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/diagnostic/get?tabs=HTTP). Here you will find all the setting that you do in the portal. 

[Here](https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/logger/list-by-service?tabs=HTTP#apimanagementlistloggers) you will be able to get all the Logger information (Monitor/ApplicationInsights) configured for an APIM Services. 

But if you are looking for one place where you can find all the Diagnostic configurations of different APIs or APIMs together and generate template of some sort, its not available.

Thought you can try the http://aka.ms/apimdevops tool for generating templates for CI CD.
