### ISSUE TITLE
[Doc]: Enable-AzRecoveryServicesBackupProtection page

### ISSUE THREAD

**Issue by Po46n2** [Azure/azure-powershell#20205]
### Description

The Enable-AzRecoveryServicesBackupProtection page:
https://learn.microsoft.com/en-us/powershell/module/az.recoveryservices/enable-azrecoveryservicesbackupprotection?view=azps-9.1.0

Needs updating.

Description says:
Set the vault context by using the Set-AzRecoveryServicesVaultContext cmdlet before you use the current cmdlet.

But Set-AzRecoveryServicesVaultContext is being deprecated as it is stated in its description.
Warning: This cmdlet is being deprecated in a future breaking change release. There will be no replacement for it. Please use the -VaultId parameter in all Recovery Services commands going forward.

Without using Set-AzRecoveryServicesVaultContext Example 2:
Enable-AzRecoveryServicesBackupProtection -Item $Item -Policy $Pol -VaultId $vault

Will fail with:
Cannot process command because of one or more missing mandatory parameters: ResourceGroupName.

So that should also be updated to: 
Enable-AzRecoveryServicesBackupProtection -ResourceGroupName $ResourceGroupName -Item $Item -Policy $Pol -VaultId $vault

**Comment by SaurabhSharma-MSFT** [comment]
@Po46n2 We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@Po46n2 The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
