### ISSUE TITLE
[Feature]: Get-AzConsumptionBudget should have a parameter for management group scopes

### ISSUE THREAD

**Issue by AlexImray** [Azure/azure-powershell#20211]
### Description of the new feature

Since azure budgets can be created at the management group scope, the Get-AzConsumptionBudget cmdlet should be able to retrieve and edit budgets that are only visible from management groups as well. Currently, it's only possible to access budgets that are at the subscription or resource group scope. This is true for the intended effects of the other *-AzConsumptionBudget cmdlets as well.

### Proposed implementation details (optional)

A new parameter set for each Get-AzConsumptionBudget, Set-AzConsumptionBudget, New-AzConsumptionBudget, and Remove-AzConsumptionBudget. These new parameter sets should require one of 'ManagementGroup', '-ManagementGroupName', or '-ManagementGroupId', parameters to function. If either of these parameters are correctly specified, the cmdlet in question should behave as it normally does when subscription parameters are entered, but its effect should apply to the specified management group instead.

**Comment by navba-MSFT** [comment]
Adding service team to look into this feature request.

@ccmaxpcrew  Could you please look into this once you get a chance ?

**Comment by jojohpm** [comment]
Hello team, the Powershell & CLI commands are mostly not updated to the latest versions of API. We recommend using REST APIs  to achieve this action. Please refer to - https://learn.microsoft.com/en-us/rest/api/consumption/budgets/get?tabs=HTTP
