### ISSUE TITLE
Can't filter results of Get-AzApplicationInsights

### ISSUE THREAD

**Issue by agr** [Azure/azure-powershell#20225]
### Description

We have a lot of Application Insights instances in Azure and in our configuration files we refer them by their instrumentation keys. Occasionally I need to query certain AI instance interactively for which I know such key. There seem to be no way to look up AI instance in Azure portal by instrumentation key, so Powershell to the rescue. `Get-AzApplicationInsights` returns me a list of all powershell instances. If I do `(Get-AzApplicationInsights)[0] | Get-Member`, among other things it outputs

```
InstrumentationKey              Property   string InstrumentationKey {get;}
```

So, there is an `InstrumentationKey` property that seem to contain instrumentation key, so I run `Get-AzApplicationInsights |? {$_.InstrumentationKey -like 'e0ab*'}` to filter out only ones that start with `e0ab` and I get all AI instances as the output. I am certain not all of them have an instrumentation key starting with that character sequence.

To reproduce the filter string must match at least one instrumentation key. As long as that happens, the script outputs all AI instances.

Such behavior is unexpected and should be addressed. Filtering should not behave in a [surprising](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) way.

Workaround: assign the result of `Get-AzApplicationInsights`, then filter the variable:

```
$ai = Get-AzApplicationInsights
$ai | ? {$_.InstrumentationKey -like 'e0ab*'}
```
That works as expected, but it is quite a bit annoying to type.

### Issue script & Debug output

```PowerShell
Get-AzApplicationInsights |? {$_.InstrumentationKey -like 'e0ab*'}

outputs all AI instances. I would rather not list them here.
```

### Environment data

```PowerShell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
> Get-Module Az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.10.3     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}
Script     2.1.0      Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKey, Get-AzApplicationInsightsContinuousExport, Get-AzApplicationInsightsLinkedStorageAccount...}
Script     5.1.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSetting, Add-AzApplicationGatewayBackendSetting...}
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We can reproduce this issue as well. We will contact PowerShell team to understand what root cause it is. 

You can try below script to workaround
```
$AIs = Get-AzApplicationInsights
$AIs | where-object {$_.InstrumentationKey -like 'e0ab*'}
```

**Comment by agr** [comment]
I've noticed the following:

```
PS> Get-AzApplicationInsights | Measure-Object

Count    : 1
Average  :
Sum      :
Maximum  :
Minimum  :
Property :

PS> $ai = Get-AzApplicationInsights
PS> $ai | Measure-Object

Count    : 55
Average  :
Sum      :
Maximum  :
Minimum  :
Property :
```
If I call `Measure-Object` on the result of `Get-AzApplicationInsights` it gives different result than if I first assign it to some variable. I'd guess it is related to the search oddities.

**Comment by dingmeng-xue** [comment]
Thanks @agr , We have found the data type of return result is different between `Get-AzApplicationInsights` and `(Get-AzApplicationInsights)` (equal to set result to variable.) We haven't figured out the root cause.
