### ISSUE TITLE
Cannot create a Virtual wan: New-AzVirtualWan

### ISSUE THREAD

**Issue by Flightdeck73** [Azure/azure-powershell#20224]
### Description

Cannot create a virtual wan with PowerShell, can do it through the ui with same values

GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.

### Issue script & Debug output

```PowerShell
DEBUG: 9:43:42 AM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
New-AzVirtualWan: GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
DEBUG: 9:43:42 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.Network:4.20.1; CommandName: New-AzVirtualWan; PSVersion: 7.3.0; IsSuccess: False; Duration: 00:00:05.5721029; Exception: GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.;
DEBUG: Finish sending metric.
DEBUG: 9:43:42 AM - NewAzureRmVirtualWanCommand end processing.
```

### Environment data

```PowerShell
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Script     8.3.0                 Az                                  Core,Desk
```

**Comment by Alex-wdy** [comment]
Could you attach the PowerShell command line you used?

**Comment by Flightdeck73** [comment]
New-AzVirtualWan -ResourceGroupName "V5aJ-rg" -Name "V5aJ-vwan" -Location "USGov Arizona"

Its saying the resource group is not found, but i see it. 

full error: didnt paste it all in original defect
----------------------------------------------------------------------------------
DEBUG: [Common.Authentication]: Authenticating using Account: 'onmicrosoft.com', environment: 'AzureUSGovernment', tenant: '<TenantID>'
DEBUG: 9:43:41 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'<TenantID>', Scopes:'https://management.core.usgovcloudapi.net//.default', AuthorityHost:'https://login.microsoftonline.us/', UserId:'.onmicrosoft.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.usgovcloudapi.net//.default ] ParentRequestId:
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.91 - b89f23e7-fe05-4b8c-9527-cb5682535b79] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.91 - b89f23e7-fe05-4b8c-9527-cb5682535b79] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.92 - b89f23e7-fe05-4b8c-9527-cb5682535b79] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.92 - b89f23e7-fe05-4b8c-9527-cb5682535b79] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.92 - b89f23e7-fe05-4b8c-9527-cb5682535b79] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.92] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.92] Returning 1 accounts
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.93 - d61dfc97-217b-4a26-94b3-863b1841c7e4] MSAL MSAL.NetCore with assembly version '4.39.0.0'. CorrelationId(d61dfc97-217b-4a26-94b3-863b1841c7e4)
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.93 - d61dfc97-217b-4a26-94b3-863b1841c7e4] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.93 - d61dfc97-217b-4a26-94b3-863b1841c7e4] LoginHint provided: False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.93 - d61dfc97-217b-4a26-94b3-863b1841c7e4] Account provided: True
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.93 - d61dfc97-217b-4a26-94b3-863b1841c7e4] ForceRefresh: False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.93 - d61dfc97-217b-4a26-94b3-863b1841c7e4]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.usgovcloudapi.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - d61dfc97-217b-4a26-94b3-863b1841c7e4
UserAssertion set: False
LongRunningOboCacheKey set: False

DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.93 - d61dfc97-217b-4a26-94b3-863b1841c7e4] === Token Acquisition (SilentRequest) started:
         Scopes: https://management.core.usgovcloudapi.net//.default
        Authority Host: login.microsoftonline.us
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.95 - d61dfc97-217b-4a26-94b3-863b1841c7e4] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.95 - d61dfc97-217b-4a26-94b3-863b1841c7e4] Access token is not expired. Returning the found cache entry. [Current time (11/23/2022 15:43:41) - Expiration Time (11/23/2022 16:29:18 +00:00) - Extended Expiration Time (11/23/2022 16:29:18 +00:00)]
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.95 - d61dfc97-217b-4a26-94b3-863b1841c7e4] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.95 - d61dfc97-217b-4a26-94b3-863b1841c7e4] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.99 - d61dfc97-217b-4a26-94b3-863b1841c7e4] Fetched access token from host login.microsoftonline.us.
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.99 - d61dfc97-217b-4a26-94b3-863b1841c7e4]
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.19045 [11/23 15:43:41.99 - d61dfc97-217b-4a26-94b3-863b1841c7e4]  AT expiration time: 11/23/2022 4:29:18 PM +00:00, scopes https://management.core.usgovcloudapi.net//user_impersonation https://management.core.usgovcloudapi.net//.default source Cache from login.microsoftonline.us appHashCode 63174160
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.usgovcloudapi.net//.default ] ParentRequestId:  ExpiresOn: 2022-11-23T16:29:18.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '<TenantID>', UserId: '.onmicrosoft.com'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.usgovcloudapi.net/

Headers:
Accept-Language               : en-US
x-ms-client-request-id        : a45ea46a-9037-4918-b28c-2faa3a3abd5d

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : fff1f76a-1135-48f5-a778-ea8ad6f04f22
x-ms-correlation-request-id   : fff1f76a-1135-48f5-a778-ea8ad6f04f22
x-ms-routing-request-id       : USGOVTEXAS:20221123T154344Z:fff1f76a-1135-48f5-a778-ea8ad6f04f22
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Wed, 23 Nov 2022 15:43:43 GMT

Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.Network/virtualWans/V5aJ-vlanname' under resource group 'V5aJ-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
  }
}


DEBUG: 9:43:42 AM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
New-AzVirtualWan: GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
DEBUG: 9:43:42 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.Network:4.20.1; CommandName: New-AzVirtualWan; PSVersion: 7.3.0; IsSuccess: False; Duration: 00:00:05.5721029; Exception: GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.;
DEBUG: Finish sending metric.
DEBUG: 9:43:42 AM - NewAzureRmVirtualWanCommand end processing.

**Comment by RakeshMohanMSFT** [comment]
@Flightdeck73 Please go through this [comment](https://github.com/Azure/azure-powershell/issues/18721#issuecomment-1318849358), seems related to that fix

**Comment by Flightdeck73** [comment]
Looks like its fixed, was this a gov thing?
