### ISSUE TITLE
Remove-AzureAvailabilitySet doesn't work

### ISSUE THREAD

**Issue by catweisun** [Azure/azure-powershell#2023]
Remove-AzureAvailabilitySet doesn't work, I have to use the Set-AzureAvailabilitySet -AvailabilityName "" as workaround.
After checked the source code [here](https://github.com/Azure/azure-powershell/blob/dev/src/ServiceManagement/Compute/Commands.ServiceManagement/IaaS/AvailabilitySets/RemoveAzureAvailabilitySet.cs)
public class RemoveAzureAvailabilitySet : VirtualMachineConfigurationCmdletBase 
     { 
         protected override void ProcessRecord() 
         { 
             base.ProcessRecord(); 
             **_this.VM.GetInstance().AvailabilitySetName = null;_**
             this.WriteObject(this.VM, true); 

         } 
     }
the highlight part is wrong, the null value could cause missing the AvailabilitySetName element in serialization and couldn't update VM through update-azurevm
so I suggest to change the code like this to avoid the serialization issue
this.VM.GetInstance().AvailabilitySetName = "";

**Comment by markcowl** [comment]
@singhkay can you take a look

**Comment by singhkay** [comment]
@hyonholee Can you take a look at this code suggestion?

**Comment by singhkay** [comment]
Closing as fixed in upcoming (May) release. Please reopen if this is still an issue.
