### ISSUE TITLE
New-AzureRMTrafficManagerProfile does not work in AzureChina

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#2024]
New-AzureRMTrafficManagerProfile does not work in China. Please let me know when this will be available.

PS C:\Windows\system32> New-AzureRMTrafficManagerProfile -Name "Example" -ResourceGroupName "Example" -RelativeDnsName "
Example" -Ttl 30 -TrafficRoutingMethod "Weighted" -MonitorProtocol "HTTP" -MonitorPort 8080 -MonitorPath /EndPointMonito
r
New-AzureRMTrafficManagerProfile : InvalidResourceNamespace: The resource namespace 'Microsoft.Network' is invalid.
At line:1 char:1
- New-AzureRMTrafficManagerProfile -Name "Example" -ResourceGroupName "Example" -R ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [New-AzureRmTrafficManagerProfile], CloudException
  - FullyQualifiedErrorId : Microsoft.Azure.Commands.TrafficManager.NewAzureTrafficManagerProfile

Thanks,
Pradebban Raja

**Comment by jtuliani** [comment]
Thanks for the feedback.  Traffic Manager ARM support is not yet deployed to Azure China.  Please use the ASM cmdlets for Traffic Manager instead at this time.

**Comment by markcowl** [comment]
@jtuliani Is this going to be resolved in the next 3 months, if so, please add to a milestone.  If not, please assign to the backlog.  Thanks!

**Comment by Pradebban** [comment]
thanks @markcowl , between can you please guide me to a release notes which says Traffic Manager ARM support is not yet deployed to Azure China / or any documentation of some sort!

**Comment by Pradebban** [comment]
@markcowl  , please let us know if there is an update. Its been nearly an year. Thanks

**Comment by MikhailTryakhov** [comment]
+@danstis to be sure it's now fixed

**Comment by danstis** [comment]
@MikhailTryakhov not sure if you mentioned the correct person, I don't think I can be of assistance here?

**Comment by EvgenyAgafonchikov** [comment]
@dilukose, could you please provide an update there?

**Comment by dilukose** [comment]
@Praburaj , can you look at this?

**Comment by MikhailTryakhov** [comment]
@rohinkoul can't assign you as assignee..
@MiYanni can you please help to add Rohin to appropriate group to make him able to assign tasks on him

**Comment by rohinkoul** [comment]
@rajaprad this looks like a very old issue. Traffic Manager is available in China.
