### ISSUE TITLE
The resource name can contain only letters, numbers, and hyphens - New-AzureRmResourceGroupDeployment

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-powershell#2027]
I'm getting an error message that 'SqlServerDeployment' is an invalid resource name, but there's obviously nothing other that letters, so it should work, right?

> New-AzureRmResourceGroupDeployment : 9:22:01 AM - Resource 
> Microsoft.Resources/deployments 'SqlServerDeployment' failed with message 'The 
> resource name can contain only letters, numbers, and hyphens. The first and 
> last character in the field must be a letter or a number.'
> At C:\code\hypersaas\iot\deployments\Scripts\Deploy-AzureResourceGroup.ps1:98 
> char:1
> + New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $TemplateFil ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeplo 
>    yment], Exception
>     + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResou 
>    rceGroupDeploymentCommand
> 

 And my resource definition:
```json
    {
      "name": "SqlServerDeployment",
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2015-01-01",
      "properties": {
        "mode": "Incremental",
        "templateLink": {
          "uri": "[concat(variables('artifactsUrl'), 'sqlserverdeploy.json', variables('artifactsUrlSasToken'))]",
          "contentVersion": "1.0.0.0"
        },
        "parameters": {
          "sqlServerName": { "value": "[reference('GetSqlServerName').outputs.sqlServerName.value" },
          "databaseAdminLogin": { "value": "[parameters('databaseAdminLogin')]" },
          "databaseAdminPassword": { "value": "[parameters('databaseAdminPassword')]" }
        }
      }
    },
```

**Comment by markcowl** [comment]
@MisinformedDNA Sorry for the bad experience.  To help us debug, can you include the cmdlet invocation for creating the deployment, including template parameters and a Debug trace from the initial part of the deployment.  You can get the debug trace by passing -Debug, or by setting ```$DebugPreference="Continue"```

@vivsriaus can you take a look.

**Comment by MisinformedDNA** [comment]
The problem was the parameter `sqlServerName` above. The `value` didn't end with a `]`. The IDE usually gives me a warning when I miss little things like that, but it didn't this time.
