### ISSUE TITLE
[Doc]: New-AzDiagnosticSetting  Example 2 is wrong

### ISSUE THREAD

**Issue by MmAtBosch** [Azure/azure-powershell#20302]
### Description

Example 2 is wrong
https://learn.microsoft.com/en-gb/powershell/module/az.monitor/new-azdiagnosticsetting?view=azps-9.1.0#example-2-create-diagnostic-setting-for-all-supported-categories
In line 5 you use the variables "log**s**" and "metric**s**" although you have defined the variables "log" and "metric"
[$categories | ForEach-Object {if($_.CategoryType -eq "Metrics"){$**metrics**+=New-AzDiagnosticSettingMetricSettingsObject -Enabled $true -Category $_.Name -RetentionPolicyDay 7 -RetentionPolicyEnabled $true} else{$**logs**+=New-AzDiagnosticSettingLogSettingsObject -Enabled $true -Category $_.Name -RetentionPolicyDay 7 -RetentionPolicyEnabled $true}}](url)

**Comment by dingmeng-xue** [comment]
@VeryEarly , please fix this issue with priority.

**Comment by VeryEarly** [comment]
already fixed in main branch by #20048
