### ISSUE TITLE
[Doc]: example error in New-AzDiagnosticSetting

### ISSUE THREAD

**Issue by damarce135** [Azure/azure-powershell#20325]
### Description

The Example 2 is incorrect on getting the subscription ID and defining the variables, it switches from non-plural to plural which makes the code fail. 

https://learn.microsoft.com/en-us/powershell/module/az.monitor/new-azdiagnosticsetting?view=azps-9.1.0&tryIt=true&source=docs#example-2-create-diagnostic-setting-for-all-supported-categories

Fixed code: 

```
$subscriptionId = (Get-AzContext).Subscription.Id
$metric = @()
$log = @()
$categories = Get-AzDiagnosticSettingCategory -ResourceId <your resource Id here> 
$categories | ForEach-Object {if($_.CategoryType -eq "Metrics"){$metric+=New-AzDiagnosticSettingMetricSettingsObject -Enabled $true -Category $_.Name -RetentionPolicyDay 7 -RetentionPolicyEnabled $true} else{$log+=New-AzDiagnosticSettingLogSettingsObject -Enabled $true -Category $_.Name -RetentionPolicyDay 7 -RetentionPolicyEnabled $true}}
New-AzDiagnosticSetting -Name test-setting -ResourceId <your resource Id here> -WorkspaceId <your workspace resource Id here> -Log $log -Metric $metric 
```

**Comment by Alex-wdy** [comment]
When I run example2, I can succeed.

When I run the script you gave, I get an error in this step.
![image](https://user-images.githubusercontent.com/108926104/204716453-ffe26d76-e6f8-43dd-ab7f-5da6052f302a.png)

$subscriptionId = (Get-AzContext).Subscription**.Id**    -- .Id is this mistake?

**Comment by RakeshMohanMSFT** [comment]
@damarce135 Thank you for reaching out to us, we are looking into it.

**Comment by dingmeng-xue** [comment]
#20048 fixed the plural issue but `(Get-AzContext).SubscriptionId` is still missing period character.

**Comment by damarce135** [comment]
Hello,

You are using your local Powershell, while me, the customer and my TA used
cloud shell and we all three had the issue. You are of course going to have
a different outcome because you don't have the latest versions of modules
and PS.

Please, test in Cloud shell and use my example, we three confirmed it works
well. Let me know if you have any questions.

Thanks,
Marcela

**Comment by damarce135** [comment]
Please, look at my previous comment to understand why you see a different behavior and why it still needs to be corrected. Thanks.

**Comment by RakeshMohanMSFT** [comment]
@damarce135 I am not sure how is a typo in an example be platform/environment specific issue? If you can shed more light we will be able to look into it further.

**Comment by damarce135** [comment]
If you test as mentioned, you will confirm it right away. Cloud shell is
using a newer version than what you have locally. Results will talk by
themselves instead of trying to contradict 3 engineers, just do the test.

Thanks!

**Comment by RakeshMohanMSFT** [comment]
@damarce135 After making the changes to the same as below, it worked for me in CloudShell as well.

```
$subscriptionId = (Get-AzContext).Subscription.Id
$metric = @()
$log = @()
$categories = Get-AzDiagnosticSettingCategory -ResourceId "/subscriptions/subscriptionid/resourcegroups/Issue20325/providers/Microsoft.AppPlatform/Spring/issue20325springapp"
$categories | ForEach-Object {if($_.CategoryType -eq "Metrics"){$metric+=New-AzDiagnosticSettingMetricSettingsObject -Enabled $true -Category $_.Name -RetentionPolicyDay 7 -RetentionPolicyEnabled $true} else{$log+=New-AzDiagnosticSettingLogSettingsObject -Enabled $true -Category $_.Name -RetentionPolicyDay 7 -RetentionPolicyEnabled $true}}
New-AzDiagnosticSetting -Name issue20325diagset -ResourceId "/subscriptions/subscriptionid/resourcegroups/Issue20325/providers/Microsoft.AppPlatform/Spring/issue20325springapp" -WorkspaceId "/subscriptions/subscriptionid/resourcegroups/issue20325/providers/microsoft.operationalinsights/workspaces/issue20325diag" -Log $log -Metric $metric
```

![image](https://user-images.githubusercontent.com/49954584/207231191-2a76d068-de1c-448c-894d-112363ce9309.png)
