### ISSUE TITLE
[Doc]: New-AzContainerAppScaleRuleObject documentation

### ISSUE THREAD

**Issue by larswurm** [Azure/azure-powershell#20334]
### Description

Please provide additional examples on how to use the cmdlet for creating common "scale rule" object, like http based connection rules. Just stating that there are complex / advanced scenarios that can beused / created using "scale rules" at the bottom is kind of thin (e.g <IHttpScaleRuleMetadata>). Since there are not many online links (google or bing) for providing clues on the cmdlet and usage - it would be helpful!

**Comment by dingmeng-xue** [comment]
@larswurm , thanks for contacting us. Azure PowerShell team implements cmdlets based on API spec. We have very limited knowledge in each RP. Could you confirm that you are asking feature of https://learn.microsoft.com/en-us/azure/container-apps/scale-app#http? We will explain how to use cmdlet based on expected HTTP request.

**Comment by larswurm** [comment]
Yes - confirmed, that is the feature I am wondering about how to configure from the Az.App module as it is not very obvious based from the params of the specified cmdlet.
