### ISSUE TITLE
Save-AzureRmProfile doesn't support pipelining

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2034]
```
$script:AzureProfile = '{0}\AzureProfile.json' -f $env:USERPROFILE;
if (!(Test-Path -Path $script:AzureProfile)) {
    Add-AzureRmAccount -Credential (Get-Credential trevor@trevorsullivan.net) | Save-AzureRmProfile -Path $script:AzureProfile;
}
```

> Save-AzureRmProfile : Run Login-AzureRmAccount to login.
At C:\Users\TrevorSullivan\Documents\WindowsPowerShell\profile.ps1:3 char:81
+ ... trevorsullivan.net) | Save-AzureRmProfile -Path $script:AzureProfile;
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Save-AzureRmProfile], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Commands.Profile.SaveAzureRMProfileCommand

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
###Root Cause
No ValueFromPipeline* parameter on the parameter in any parameter set

###Proposed Solution
Add ValueFromPipeline parameter to Profile parameter in all parameter sets
Add mocked unit test coverage to verify

### Cost (work units): 1

**Comment by cormacpayne** [comment]
@markcowl @pcgeek86 is this an issue with `Save-AzureRmProfile` not supporting pipelining? I noticed that there is already a `ValueFromPipeline` attribute for the `Profile` parameter in [this cmdlet's code](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Profile/Commands.Profile/Profile/SaveAzureRMProfile.cs#L32)

When I start a new PowerShell session and run the following command, it gives the error that Trevor also saw above:

```powershell
Add-AzureRmAccount -Credential (Get-Credential cormacpayne@ufl.edu) | Save-AzureRmProfile -Path "C:\Users\corm\Documents\test.json"
```

However, if I log in first (using the first half of the above command), **_and then_** I run the above line, it works without a problem, and my `test.json` file gets updated with the profile information.

**Comment by pcgeek86** [comment]
@cormacpayne @markcowl The issue was reported on March 30th, and was apparently fixed on June 20th.

https://github.com/Azure/azure-powershell/blame/dev/src/ResourceManager/Profile/Commands.Profile/Profile/SaveAzureRMProfile.cs#L32
