### ISSUE TITLE
New-AzSentinelAlertRule and Update-AzSentinelAlertRule no longer support multiple Attack Tactics 

### ISSUE THREAD

**Issue by jiang-edward** [Azure/azure-powershell#20362]
### Description

The Az Module used to support multiple tactics for creating and updating Sentinel Alert Rules in v8.3.0 but since v9.x only one tactic can be assigned to an Alert Rule. 

### Issue script & Debug output

```PowerShell
New-AzSentinelAlertRule -ResourceGroupName "resource" -WorkspaceName "workspace" -Kind Scheduled -Enabled -DisplayName "Powershell Exection Alert (Several Times per Hour)" -Severity Low -Query "SecurityEvent | where EventId == 4688" -Tactic @("Impact","Collection")
New-AzSentinelAlertRule: Cannot process argument transformation on parameter 'Tactic'. Cannot convert value to type System.String.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
Script     3.2.0                 Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, D…
Script     3.0.0                 Az.SecurityInsights                 {Get-AzSentinelAlertRule, Get-AzSentinelAlertRule…
```

**Comment by navba-MSFT** [comment]
@jiang-edward I am able to reproduce this issue at my end. I am discussing this with the Product owners. I will keep you posted once I hear from them.

**Comment by navba-MSFT** [comment]
@jiang-edward Apologies for the late reply. While we are checking in the background why there is a change in the behavior of the PowerShell cmdlet, I wanted to check if you could invoke our REST API directly as a workaround ?

Because our latest REST API version of Alert Rules support multiple tactics. See below:


properties.tactics |   | string[ ] | The tactics of the alert rule
-- | -- | -- | --

See the REST API [documentation here](https://learn.microsoft.com/en-us/rest/api/securityinsights/stable/alert-rules/create-or-update?tabs=HTTP).

**Comment by navba-MSFT** [comment]
@jiang-edward I have heard back from the Product Group. They have confirmed its a bug. There is no ETA for the fix release. Currently the ONLY workaround is to invoke the above REST API. Please let me know if you have any follow-up queries.
