### ISSUE TITLE
Remove-AzureRmResourceGroup -Name parameter is not positional

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2036]
```
Remove-AzureRmResourceGroup CS-WebJobs-WestEurope-scheduler -Force;
```

> Remove-AzureRmResourceGroup : A positional parameter cannot be found that accepts argument
'CS-WebJobs-WestEurope-scheduler'.
At line:1 char:1
+ Remove-AzureRmResourceGroup CS-WebJobs-WestEurope-scheduler -force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-AzureRmResourceGroup], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.Azure.Commands.Resources.RemoveAzureResourceGroupCommand

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@vivsriaus This seems like a really simple fix, can we get it in for the next release?

**Comment by vivsriaus** [comment]
@markcowl Agree, this should be in the next release. cc: @ravbhatnagar

**Comment by pcgeek86** [comment]
Please assign to the appropriate milestone. /cc @ravbhatnagar

**Comment by ravbhatnagar** [comment]
Also fixing this for Get and New.

**Comment by ravbhatnagar** [comment]
Fix May 2016
