### ISSUE TITLE
Stuck in the SubscriptionsOperationsExtensions.List of Connect-AzAccount

### ISSUE THREAD

**Issue by ka-yanaoka** [Azure/azure-powershell#20374]
### Description

I got stuck on Connect-AzAccount.
I checked the Powershell dump file and it seems to be stuck on SubscriptionsOperationsExtensions.List.
The Connect-AzAccount stuck has occurred multiple times, but has not been reproduced.

Powershell dump file output results
---------------------------------------------
0:005> !clrstack
The version of SOS does not match the version of CLR you are debugging.  Please
load the matching version of SOS for the version of CLR you are debugging.
CLR Version: 4.8.4510.0
SOS Version: 4.8.4515.0
OS Thread Id: 0x3298 (5)
Child SP       IP Call Site
07a5dbe4 7735f04c [GCFrame: 07a5dbe4] 
07a5dc94 7735f04c [HelperMethodFrame_1OBJ: 07a5dc94] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
07a5dd20 6e9642c8 System.Threading.Monitor.Wait(System.Object, Int32, Boolean) [f:\dd\ndp\clr\src\BCL\system\threading\monitor.cs @ 203]
07a5dd30 6e9723fd System.Threading.Monitor.Wait(System.Object, Int32) [f:\dd\ndp\clr\src\BCL\system\threading\monitor.cs @ 213]
07a5dd34 6e9ef5a9 System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)
07a5dd88 6e9ed8f8 System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken) [f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs @ 3320]
07a5ddc8 6ea504f9 System.Threading.Tasks.Task.InternalWait(Int32, System.Threading.CancellationToken) [f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs @ 3259]
07a5de2c 6e9f0caf System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) [f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs @ 153]
07a5de38 0971f41d **_Microsoft.Azure.Internal.Subscriptions.SubscriptionsOperationsExtensions.List_** (Microsoft.Azure.Internal.Subscriptions.ISubscriptionsOperations)
07a5de58 0971f04f Microsoft.Azure.Commands.ResourceManager.Common.Paging.GenericPageEnumerator`1[[System.__Canon, mscorlib]]..ctor(System.Func`1<Microsoft.Rest.Azure.IPage`1<System.__Canon>>, System.Func`2<System.String,Microsoft.Rest.Azure.IPage`1<System.__Canon>>, UInt64, UInt64)
07a5de7c 0971ef0e Microsoft.Azure.Commands.ResourceManager.Common.Paging.GenericPageEnumerable`1[[System.__Canon, mscorlib]].GetEnumerator()
07a5dea4 6e97aa1f System.Collections.Generic.List`1[[System.__Canon, mscorlib]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>) [f:\dd\ndp\clr\src\BCL\system\collections\generic\list.cs @ 98]
07a5ded8 6fd0c5de System.Linq.Enumerable.ToList[[System.__Canon, mscorlib]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
07a5deec 0971d48d Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.TryGetTenantSubscription(Microsoft.Azure.Commands.Common.Authentication.IAccessToken, Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureAccount, Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureEnvironment, System.String, System.String, System.String, Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureSubscription ByRef, Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureTenant ByRef)
07a5df70 0969bc84 Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureAccount, Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureEnvironment, System.String, System.String, System.String, System.Security.SecureString, Boolean, System.Action`1<System.String>, System.String, Boolean)
07a5e0d0 0969c80b Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand+c__DisplayClass92_0.b__0(Microsoft.Azure.Commands.Common.Authentication.Models.AzureRmProfile, Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient, System.String)
07a5e118 0969c885 Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand+c__DisplayClass94_0.b__0(Microsoft.Azure.Commands.Common.Authentication.Models.AzureRmProfile, Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient)
07a5e124 0954e9a5 Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(System.Action`2<Microsoft.Azure.Commands.Common.Authentication.Models.AzureRmProfile,Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient>)
07a5e150 0969c9ec Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(System.Action`3<Microsoft.Azure.Commands.Common.Authentication.Models.AzureRmProfile,Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient,System.String>)
07a5e174 0969d9db Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
07a5e238 0954e75d Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions+c__3`1[[System.__Canon, mscorlib]].b__3_0(System.__Canon)
07a5e240 0954e658 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[[System.__Canon, mscorlib]](System.__Canon, System.Action`1<System.__Canon>)
07a5e260 0954e0c8 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[[System.__Canon, mscorlib]](System.__Canon)
07a5e284 0954df69 Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
07a5e2b0 6c68104d System.Management.Automation.Cmdlet.DoProcessRecord() [d:\rs1\admin\monad\src\engine\Cmdlet.cs @ 186]
07a5e2b8 6c680bb9 System.Management.Automation.CommandProcessor.ProcessRecord()
07a5e314 6c663ccd System.Management.Automation.CommandProcessorBase.DoExecute() [d:\rs1\admin\monad\src\engine\CommandProcessorBase.cs @ 572]
07a5e340 6c663c68 System.Management.Automation.Internal.PipelineProcessor.Inject(System.Object, Boolean) [d:\rs1\admin\monad\src\engine\Pipeline.cs @ 1165]
07a5e368 6cfa2777 System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object) [d:\rs1\admin\monad\src\engine\Pipeline.cs @ 503]
07a5e3c4 6c62dd93 System.Management.Automation.PipelineOps.InvokePipeline(System.Object, Boolean, System.Management.Automation.CommandParameterInternal[][], System.Management.Automation.Language.CommandBaseAst[], System.Management.Automation.CommandRedirection[][], System.Management.Automation.Language.FunctionContext) [d:\rs1\admin\monad\src\engine\Runtime\Operations\MiscOps.cs @ 442]
07a5e420 6c67e06e System.Management.Automation.Interpreter.ActionCallInstruction`6[[System.__Canon, mscorlib],[System.Boolean, mscorlib],[System.__Canon, mscorlib],[System.__Canon, mscorlib],[System.__Canon, mscorlib],[System.__Canon, mscorlib]].Run(System.Management.Automation.Interpreter.InterpretedFrame) [d:\rs1\admin\monad\src\engine\Interpreter\CallInstruction.Generated.cs @ 570]
07a5e454 6c66601e System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame) [d:\rs1\admin\monad\src\engine\Interpreter\ControlFlowInstructions.cs @ 323]
07a5e4ac 6c66601e System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame) [d:\rs1\admin\monad\src\engine\Interpreter\ControlFlowInstructions.cs @ 323]
07a5e504 6c665f3b System.Management.Automation.Interpreter.Interpreter.Run(System.Management.Automation.Interpreter.InterpretedFrame) [d:\rs1\admin\monad\src\engine\Interpreter\Interpreter.cs @ 126]
07a5e51c 6c65a1f1 System.Management.Automation.Interpreter.LightLambda.RunVoid1[[System.__Canon, mscorlib]](System.__Canon) [d:\rs1\admin\monad\src\engine\Interpreter\LightLambda.Generated.cs @ 78]
07a5e550 6c6647f7 System.Management.Automation.DlrScriptCommandProcessor.RunClause(System.Action`1<System.Management.Automation.Language.FunctionContext>, System.Object, System.Object) [d:\rs1\admin\monad\src\engine\ScriptCommandProcessor.cs @ 516]
07a5e5c8 6c66438a System.Management.Automation.DlrScriptCommandProcessor.Complete() [d:\rs1\admin\monad\src\engine\ScriptCommandProcessor.cs @ 410]
07a5e610 6c664169 System.Management.Automation.CommandProcessorBase.DoComplete() [d:\rs1\admin\monad\src\engine\CommandProcessorBase.cs @ 648]
07a5e648 6c663e66 System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(System.Management.Automation.CommandProcessorBase) [d:\rs1\admin\monad\src\engine\Pipeline.cs @ 610]
07a5e6d8 6cfa27c9 System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object) [d:\rs1\admin\monad\src\engine\Pipeline.cs @ 527]
07a5e734 6c62dd93 System.Management.Automation.PipelineOps.InvokePipeline(System.Object, Boolean, System.Management.Automation.CommandParameterInternal[][], System.Management.Automation.Language.CommandBaseAst[], System.Management.Automation.CommandRedirection[][], System.Management.Automation.Language.FunctionContext) [d:\rs1\admin\monad\src\engine\Runtime\Operations\MiscOps.cs @ 442]
07a5e790 6c67e06e System.Management.Automation.Interpreter.ActionCallInstruction`6[[System.__Canon, mscorlib],[System.Boolean, mscorlib],[System.__Canon, mscorlib],[System.__Canon, mscorlib],[System.__Canon, mscorlib],[System.__Canon, mscorlib]].Run(System.Management.Automation.Interpreter.InterpretedFrame) [d:\rs1\admin\monad\src\engine\Interpreter\CallInstruction.Generated.cs @ 570]
07a5e7c4 6c66601e System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame) [d:\rs1\admin\monad\src\engine\Interpreter\ControlFlowInstructions.cs @ 323]
07a5e81c 6c66601e System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame) [d:\rs1\admin\monad\src\engine\Interpreter\ControlFlowInstructions.cs @ 323]
07a5e874 6c665f3b System.Management.Automation.Interpreter.Interpreter.Run(System.Management.Automation.Interpreter.InterpretedFrame) [d:\rs1\admin\monad\src\engine\Interpreter\Interpreter.cs @ 126]
07a5e88c 6c65a1f1 System.Management.Automation.Interpreter.LightLambda.RunVoid1[[System.__Canon, mscorlib]](System.__Canon) [d:\rs1\admin\monad\src\engine\Interpreter\LightLambda.Generated.cs @ 78]
07a5e8c0 6c6647f7 System.Management.Automation.DlrScriptCommandProcessor.RunClause(System.Action`1<System.Management.Automation.Language.FunctionContext>, System.Object, System.Object) [d:\rs1\admin\monad\src\engine\ScriptCommandProcessor.cs @ 516]
07a5e938 6c66438a System.Management.Automation.DlrScriptCommandProcessor.Complete() [d:\rs1\admin\monad\src\engine\ScriptCommandProcessor.cs @ 410]
07a5e980 6c664169 System.Management.Automation.CommandProcessorBase.DoComplete() [d:\rs1\admin\monad\src\engine\CommandProcessorBase.cs @ 648]
07a5e9b8 6c663e66 System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(System.Management.Automation.CommandProcessorBase) [d:\rs1\admin\monad\src\engine\Pipeline.cs @ 610]
07a5ea48 6cfa27c9 System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object) [d:\rs1\admin\monad\src\engine\Pipeline.cs @ 527]
07a5eaa4 6c62dd93 System.Management.Automation.PipelineOps.InvokePipeline(System.Object, Boolean, System.Management.Automation.CommandParameterInternal[][], System.Management.Automation.Language.CommandBaseAst[], System.Management.Automation.CommandRedirection[][], System.Management.Automation.Language.FunctionContext) [d:\rs1\admin\monad\src\engine\Runtime\Operations\MiscOps.cs @ 442]
07a5eb00 6c67e06e System.Management.Automation.Interpreter.ActionCallInstruction`6[[System.__Canon, mscorlib],[System.Boolean, mscorlib],[System.__Canon, mscorlib],[System.__Canon, mscorlib],[System.__Canon, mscorlib],[System.__Canon, mscorlib]].Run(System.Management.Automation.Interpreter.InterpretedFrame) [d:\rs1\admin\monad\src\engine\Interpreter\CallInstruction.Generated.cs @ 570]
07a5eb34 6c66601e System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame) [d:\rs1\admin\monad\src\engine\Interpreter\ControlFlowInstructions.cs @ 323]
07a5eb8c 6c66601e System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame) [d:\rs1\admin\monad\src\engine\Interpreter\ControlFlowInstructions.cs @ 323]
07a5ebe4 6c665f3b System.Management.Automation.Interpreter.Interpreter.Run(System.Management.Automation.Interpreter.InterpretedFrame) [d:\rs1\admin\monad\src\engine\Interpreter\Interpreter.cs @ 126]
07a5ebfc 6c65a1f1 System.Management.Automation.Interpreter.LightLambda.RunVoid1[[System.__Canon, mscorlib]](System.__Canon) [d:\rs1\admin\monad\src\engine\Interpreter\LightLambda.Generated.cs @ 78]
07a5ec30 6c6647f7 System.Management.Automation.DlrScriptCommandProcessor.RunClause(System.Action`1<System.Management.Automation.Language.FunctionContext>, System.Object, System.Object) [d:\rs1\admin\monad\src\engine\ScriptCommandProcessor.cs @ 516]
07a5eca8 6c66444b System.Management.Automation.DlrScriptCommandProcessor.Complete()
07a5ecf0 6c664169 System.Management.Automation.CommandProcessorBase.DoComplete() [d:\rs1\admin\monad\src\engine\CommandProcessorBase.cs @ 648]
07a5ed28 6c663e66 System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(System.Management.Automation.CommandProcessorBase) [d:\rs1\admin\monad\src\engine\Pipeline.cs @ 610]
07a5edb8 6cfa27c9 System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object) [d:\rs1\admin\monad\src\engine\Pipeline.cs @ 527]
07a5ee14 6c64f267 System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper() [d:\rs1\admin\monad\src\engine\hostifaces\LocalPipeline.cs @ 383]
07a5eee0 6c64e886 System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc() [d:\rs1\admin\monad\src\engine\hostifaces\LocalPipeline.cs @ 625]
07a5ef1c 6c5bd119 System.Management.Automation.Runspaces.PipelineThread.WorkerProc() [d:\rs1\admin\monad\src\engine\hostifaces\LocalPipeline.cs @ 1309]
07a5ef28 6e962e01 System.Threading.ThreadHelper.ThreadStart_Context(System.Object) [f:\dd\ndp\clr\src\BCL\system\threading\thread.cs @ 74]
07a5ef34 6e988604 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) [f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs @ 980]
07a5efa0 6e988537 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) [f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs @ 928]
07a5efb4 6e9884f4 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs @ 917]
07a5efcc 6e962d5b System.Threading.ThreadHelper.ThreadStart() [f:\dd\ndp\clr\src\BCL\system\threading\thread.cs @ 111]
07a5f1b0 70350566 [GCFrame: 07a5f1b0] 
07a5f2f4 70350566 [DebuggerU2MCatchHandlerFrame: 07a5f2f4]

### Issue script & Debug output

```PowerShell
$secret = ConvertTo-SecureString -AsPlainText "×××" -Force
$tenant = "×××"
$appId = "×××"
$credential = New-Object System.Management.Automation.PsCredential $appId, $secret
$DebugPreference="Continue"
Disable-AzContextAutosave
Connect-AzAccount -ServicePrincipal -Credential $credential -Tenant $tenant -Scope Process
```

### Environment data

```PowerShell
PS C:\Windows\system32> $PSVersionTable

Name                           Value                                                                                                                
----                           -----                                                                                                                
PSVersion                      5.1.14393.5127                                                                                                       
PSEdition                      Desktop                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                              
BuildVersion                   10.0.14393.5127                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                      
WSManStackVersion              3.0                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                  
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS C:\Windows\system32> Get-Module

ModuleType Version    Name                                ExportedCommands                                                                          
---------- -------    ----                                ----------------                                                                          
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                       
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We have no idea about what happened in your environment. We will keep an eye on this issue and see whether more information provided by community.

**Comment by ka-yanaoka** [comment]
Thank you for confirming.
I believe it is stuck in the following method from the dump log.
https://github.com/Azure/azure-powershell/blob/main/src/Accounts/Accounts/Models/RMProfileClient.cs#L627

I think the issue can be improved by implementing a timeout and retry in the part that gets the information for this subscription (the part that gets the external information).
I would appreciate it if you could confirm this.

**Comment by dingmeng-xue** [comment]
@ka-yanaoka , thanks for suggestion. There are many potential reasons which lead client stuck or just waiting. We will look into the code and check whether timetout is set corrected.

How many subscriptions are there your account can access?

**Comment by ka-yanaoka** [comment]
@dingmeng-xue Sorry for the delay.
I just checked with the application ID used in the authentication. There was one subscription.
![image](https://user-images.githubusercontent.com/119591084/207470673-3bccbb50-7fea-431b-b67a-b7e822965cc6.png)

**Comment by ka-yanaoka** [comment]
@dingmeng-xue
I would appreciate it if you could confirm the above information.
Also, please let me know if I have left out any necessary information.

**Comment by dingmeng-xue** [comment]
Hi @ka-yanaoka , we didn't experience the similar issue. You can turn on debug log via `$DebugPreference = "Continue"` to check the output of log. Another way is to monitor HTTP communication. For instance, you can collect HTTP communication using [Fiddler](https://www.telerik.com/fiddler). Due to there is sensitive data, you can share it to me via email after couple hours till you access token is expired.

**Comment by ka-yanaoka** [comment]
@dingmeng-xue
Thank you for your confirmation.

>You can turn on debug log via $DebugPreference = "Continue" to check the output of log. 
>Another way is to monitor HTTP communication. For instance, you can collect HTTP communication using Fiddler. Due to there is sensitive data, you can share it to me via email after couple hours till you access token is expired.
Thanks for the above. I will check it.

>I think the issue can be improved by implementing a timeout and retry in the part that gets the information for this subscription (the part that gets the external information).
Regarding the above, would it be difficult to get it implemented since similar problems have not occurred elsewhere?1
