### ISSUE TITLE
[Doc]: Typo in example script for New-AzDiagnosticSetting

### ISSUE THREAD

**Issue by nconvery** [Azure/azure-powershell#20378]
### Description

Typo in example scripted provided at: https://learn.microsoft.com/en-us/powershell/module/az.monitor/new-azdiagnosticsetting?view=azps-9.1.0#example-2-create-diagnostic-setting-for-all-supported-categories

The 5th line of the script is the following:

```
$categories | ForEach-Object {
if($_.CategoryType -eq "Metrics")  {
$metrics+=New-AzDiagnosticSettingMetricSettingsObject -Enabled $true -Category $_.Name -RetentionPolicyDay 7 -RetentionPolicyEnabled $true
} else { 
$logs+=New-AzDiagnosticSettingLogSettingsObject -Enabled $true -Category $_.Name -RetentionPolicyDay 7 -RetentionPolicyEnabled $true
}}
```

And should be amended to the following, because the variables referenced were declared as arrays without a trailing 's'

```
$categories | ForEach-Object {
if($_.CategoryType -eq "Metrics") {
  $metric+=New-AzDiagnosticSettingMetricSettingsObject -Enabled $true -Category $_.Name -RetentionPolicyDay 7 -RetentionPolicyEnabled $true
} else {
  $log+=New-AzDiagnosticSettingLogSettingsObject -Enabled $true -Category $_.Name -RetentionPolicyDay 7 -RetentionPolicyEnabled $true
}}
```

**Comment by nconvery** [comment]
Apologies on the formatting, I have no knowledge of why it is automatically formatting it into something other than plaintext. Feel free to reach me directly if unclear

**Comment by dingmeng-xue** [comment]
Thanks for reporting. It is the same as #20302.

We have fixed this issue and online doc will be updated in this week. Close this issue now.
