### ISSUE TITLE
[Doc]: example of New-AzGalleryImageVersion 

### ISSUE THREAD

**Issue by Maurice-van-Beers** [Azure/azure-powershell#20376]
### Description

https://learn.microsoft.com/en-us/powershell/module/az.compute/new-azgalleryimageversion?view=azps-9.1.0

Please add to the documentation that it is possible to create a new Image version from a source that is in another tenant.
Also add an example show how to do that:

I've been using Azure Lighthouse so i can use Select-AzSubscription
If you do not use Lighthouse than i presume there is another way to do the selection.

SourceImageId='/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/My-resourcegroupname/providers/Microsoft.Compute/galleries/My-GalleryName/images/My-imgdef/versions/My-ImageVersion'

**Comment by sandeepraichura** [comment]
@Maurice-van-Beers - I'm looking into it and I'll keep you posted on the status

**Comment by sandeepraichura** [comment]
@Maurice-van-Beers - We are working on updating the docs., I will update this thread soon once the docs. changes are live.

**Comment by sandeepraichura** [comment]
@Maurice-van-Beers - We are making some major updates to the doc and it's taking time.  If this is a blocker for you, here are the instructions with PS/CLI

### [PowerShell](#tab/powershell)

```azurepowershell-interactive
# Set variables 

$targetSubID = "<subscription ID for the target>"
$sourceTenantID = "<tenant ID where for the source image>"
$sourceImageID = "<resource ID of the source image>"

#Login to the subscription where the new image will be created
Connect-AzAccount -UseDeviceAuthentication -Subscription $targetSubID

# Login to the tenant where the source image is published
Connect-AzAccount -Tenant $sourceTenantID -UseDeviceAuthentication 

# Set the context of the subscription where the new image will be created
Set-AzContext -Subscription $targetSubID 

# Create the image version from another image version in a different tenant
New-AzGalleryImageVersion \
   -ResourceGroupName myResourceGroup -GalleryName myGallery \
   -GalleryImageDefinitionName myImageDef \
   -Location "West US 2" \
   -Name 1.0.0 \
   -SourceImageId $sourceImageID
```resource-group <<resource group name>> --image-version "resource id of the source image"
```

### [CLI](#tab/cli2)

```azurecli-interactive

# Set some variables
tenantID="<tenant ID for the source image>"
subID="<subscription ID where the image will be creted>"
sourceImageID="<resource ID of the source image>"

# Log in to the tenant where the source image is available
az login --tenant $tenantID

# Log back in to the subscription where the image will be created and ensure subscription context is set
az login
az account set --subscription $subID

# Create the image
az sig image-version create `
   --gallery-image-definition myImageDef `
   --gallery-image-version 1.0.0 `
   --gallery-name myGallery `
   --resource-group myResourceGroup `
   --image-version $sourceImageID
```

**Comment by sandeepraichura** [comment]
The docs are updated here: https://learn.microsoft.com/en-us/azure/virtual-machines/image-version?tabs=portal%2Ccli2#create-an-image-in-one-tenant-using-the-source-image-in-another-tenant

closing this out now, reopen if needed.
