### ISSUE TITLE
Add-AzureRemoteAppUser examples Incorrect

### ISSUE THREAD

**Issue by Vijayaraghavanl** [Azure/azure-powershell#2037]
Add-AzureRemoteAppUser KB @ https://msdn.microsoft.com/en-us/library/mt428029.aspx gives incorrect examples.

Below is one of the examples from the KB

PS C:> Add-AzureRemoteAppUser -CollectionName "Contoso" -UserType MicrosoftAccount -UserUpn "PattiFuller@contoso.com"                  

Please note that there is no parameter "-UserType" instead it is "-Type".

Kindly update the examples please.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
