### ISSUE TITLE
Problem calling Get-AzNetworkSecurityGroup

### ISSUE THREAD

**Issue by autrymt37** [Azure/azure-powershell#20377]
Having the same problem calling Get-AzNetworkSecurityGroup

GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.

While I can revert versions to 7.2.7 for development reasons.  It is not so easy to have my entire user base do the same.  Please fix.

PSVersion                     7.3.0
PSEdition                      Core
GitCommitId                 7.3.0

Thanks,
Mike

**Comment by dingmeng-xue** [comment]
Hi @autrymt37 , there are 2 options. One is to revert PowerShell version, or upgrade Azure PowerShell version. Az.Network should be 5.1.2 or above.
