### ISSUE TITLE
Get-AzureStorageBlobCopyState in different session than the start-azurestorageblobcopy

### ISSUE THREAD

**Issue by EmFl** [Azure/azure-powershell#2038]
Hello,
I find a lot of documentation on using get-azurestorageblobcopy working like t

```
$copyBlob = Start-AzureStorageBlobCopy -ICloudBlob $mysnapshot -SrcContext $srccontext -DestContainer $destcontainer -DestBlob $destblob -DestContext $destContext
$copyBlob | Get-AzureStorageBlobCopyState -WaitForComplete
```

This works fine. However, if you lose that powershell session, how can I get back the state of the copy ?
At this time the only thing I can do is a get-azurestorageblob and check if the last modified time stops moving to consider the copy as done.

I've tried 

Get-AzureStorageBlobCopyState -Container  $destcontainer -Context $destContext -Blob $destblob
Get-AzureStorageBlobCopyState : Can not find blob 'Microsoft.WindowsAzure.Storage.Blob.CloudPageBlob' in container 'vhds', or the blob type is 
unsupported.
At line:1 char:1
+ Get-AzureStorageBlobCopyState -Container  $destcontainer -Context $de ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-AzureStorageBlobCopyState], ResourceNotFoundException
    + FullyQualifiedErrorId : ResourceNotFoundException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCopyState

I've also tried using the source blob but got the exact same error message.

Any other way I can do this ?
Thanks

**Comment by EmFl** [comment]
It turns out I can do this : 
Get-AzureStorageBlob -Prefix "myprefix" -Context $DestinationContext -Container "mycontainer" | Get-AzureStorageBlobCopyState
and it works :

```
CopyId            : accccc2-6b2c-cccc-99ea-2c2a6d1ccccc7
CompletionTime    : 
Status            : Pending
Source            : https://.......blob.core.windows.net
BytesCopied       : 3356753920
TotalBytes        : 10437886464
StatusDescription : 
```

But I can't do this :

```
$blob=Get-AzureStorageBlob -Prefix "myprefix" -Context $DestinationContext -Container "mycontainer"
Get-AzureStorageBlobCopyState -Blob $blob -Container "mycontainer" -Context $DestinationContext
Get-AzureStorageBlobCopyState : Can not find blob 'Microsoft.WindowsAzure.Commands.Common.Storage.ResourceModel.AzureStorageBlob' in container 
"mycontainer", or the blob type is unsupported.
At line:1 char:1
+ Get-AzureStorageBlobCopyState -Blob $blob -Container "mycontainer" -Context $D ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-AzureStorageBlobCopyState], ResourceNotFoundException
    + FullyQualifiedErrorId : ResourceNotFoundException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCopyState
```

bug ?

**Comment by blueww** [comment]
Hi EmFI,

The "-blob" parameter in Get-AzureStorageBlobCopyState cmdlet is used to set the blob name, and it will be taken as a string. (You can see it by run "get-help Get-AzureStorageBlobCopyState -full")
You need to use "-CloudBlob" to set the blob object.

Following cmdlets works on my side, you can try it:
```
$blob=Get-AzureStorageBlob -Prefix "myprefix" -Context $DestinationContext -Container "mycontainer"
Get-AzureStorageBlobCopyState -CloudBlob $blob.ICloudBlob
```
(As the $blob object already contains container and context information, you don't need to specify them)

Thanks!
Wei Wei

**Comment by EmFl** [comment]
Thanks it works, however I had to specify the context using -context otherwise I would get this : 
Get-AzureStorageBlobCopyState : Could not get the storage context.  Please pass in a storage context or set the current storage context.

Sorry for the issue opened by mistake.
