### ISSUE TITLE
Start-AzAutomationRunbook passing python parameters out of order and breaks script[Doc]: 

### ISSUE THREAD

**Issue by MonikaReddy-MSFT** [Azure/azure-powershell#20408]
### Description

Customer raised this issue in Microsoft Q&A - 

https://learn.microsoft.com/en-us/answers/questions/1120500/index.html 

I would like to suggest that this nugget of information be added to the MS documentation here: https://learn.microsoft.com/en-us/powershell/module/az.automation/start-azautomationrunbook?view=azps-9.2.0 ?

Specifically, in step 2 of running a Python Automation Runbook - an example is given of how to pass parameters. This 'ordered' accelerator is not used in the example, and I think that contributed to my confusion. Just a suggestion.

**Comment by RakeshMohanMSFT** [comment]
@MonikaReddy-MSFT We are looking into it.
