### ISSUE TITLE
Permission 'ALL' not show in azure portal

### ISSUE THREAD

**Issue by hogo6002** [Azure/azure-powershell#20406]
### Description

Hi team, I found that azure portal will show blank value when I use command PowerShell or C# to grant `all` PermissionsToCertificates for my account. I am sure the permission is granted successfully as I can operate as expected and can find my change history in the activity log. It is a front-end bug, I'm not sure if it is the right place to report. To reproduce it, you can try to assign 'All' permission for certificates via PS then open azure portal navigate to access policies to see if the value of certificate permission is blank. It is not happening every time, sometimes it shows correctly, but sometimes not.

### Issue script & Debug output

```PowerShell
PS: Set-AzKeyVaultAccessPolicy -ObjectId "016904ec-5dfd-4610-8106-bacdf46c8e46" -PermissionsToCertificates all
Activity log: 
"permissions": {
    "certificates": [
        "All"
    ],
}
```

### Environment data

```PowerShell
N/A
```

### Module versions

```PowerShell
latest
```

### Error output

```PowerShell
Azure portal > key vault page > access policies tab > Certificate Permissions value is blank
```

**Comment by dingmeng-xue** [comment]
@hogo6002 , Thanks for reporting. `All` is one of permission type introduced by Keyvault service. Azure PowerShell implementation should follow the correct practice. if Portal cannot show that, you need to report the issue to Azure Portal.

**Comment by dingmeng-xue** [comment]
@hogo6002 , Developer is fixing issue on Azure Portal. It should be fixed soon.
