### ISSUE TITLE
[Doc]: Wrong Parameter Description in Get-AzActivityLog Documentation

### ISSUE THREAD

**Issue by JoshuaKaluski** [Azure/azure-powershell#20409]
### Description

There is an erroneous description for the `-StartTime` parameter in the documentation for [Get-AzActivityLog](https://learn.microsoft.com/en-us/powershell/module/az.monitor/get-azactivitylog). The current description is "_The correlationId of the query_", which seems to be more descriptive of the `-CorrelationId` parameter than of `-StartTime`:
![image](https://user-images.githubusercontent.com/46460752/206476010-5775e6cf-5d95-4511-910f-df4f1b4fa084.png)

I believe that the description should more closely match the related `-EndTime` parameter's description, perhaps something along the lines of "_The Start Time of the query_":
![image](https://user-images.githubusercontent.com/46460752/206476589-7710f801-0b94-4a16-a809-647b07b7cf8a.png)

**Comment by RakeshMohanMSFT** [comment]
@JoshuaKaluski We will fix it.
