### ISSUE TITLE
[Feature]: Replicate `az ssh vm` functionality

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#20412]
### Description of the new feature

The az vm ssh process fetches a short lived SSH certificate, and then passes that to a native app to connect to a host using that cert. There should not be any reason Azure PowerShell can't do the same thing 

`Connect-AzVm` would be my recommended command for this.

### Proposed implementation details (optional)

Operate in same fashion as Azure CLI `az ssh vm` to connect to a server that is AAD Linux Login enabled.

### Relevant Reference Implementation
Implemented in python but the same MSAL calls can be replicated
https://github.com/Azure/azure-cli-extensions/blob/main/src/ssh/

**Comment by dingmeng-xue** [comment]
@JustinGrote , thanks for contacting us. 

Could you try this module? https://www.powershellgallery.com/packages/Az.Ssh/0.1.0
I believe [`Enter-AzVM`](https://learn.microsoft.com/en-us/powershell/module/az.ssh/enter-azvm?view=azps-9.2.0#example-1-connect-to-azure-resource-using-aad-issued-certificates) can reach your goal.
