### ISSUE TITLE
[Feature]: New-AzSnapshotUpdateConfig update object [-NetworkAccessPolicy <String>]

### ISSUE THREAD

**Issue by cadumi** [Azure/azure-powershell#20428]
### Description of the new feature

The cmdlet New-AzSnapshotUpdateConfig is missing the syntax update object [-NetworkAccessPolicy <String>]
Is there any reason for this? As I would expect it to be common and in use as it is already for New-AzDiskUpdateConfig.
This is very beloved as we could then bulk update several snapshots with it. 
Can we make it available?

### Proposed implementation details (optional)

Make -NetworkAccessPolicy parameter available for snapshots.

**Comment by MsGabsta** [comment]
#reassign @jaylabell

**Comment by MsGabsta** [comment]
@jaylabell, could you look into this.

**Comment by jaylabell** [comment]
Thank you for the feedback @cadumi, we are looking into this request.

**Comment by Drewm3** [comment]
@ramankumarlive, could you please look into this feature request?

**Comment by TravisCragg-MSFT** [comment]
related to https://github.com/Azure/azure-rest-api-specs/issues/21325

**Comment by Sandido** [comment]
The NetworkAccessPolicy parameter was added to New-AzSnapshotUpdateConfig in April 2023 with the Az.Compute 5.6.0 release.
