### ISSUE TITLE
[Doc]: Please clarify Example 4 here - Set-AzNetworkSecurityRuleConfig

### ISSUE THREAD

**Issue by pgbfnf** [Azure/azure-powershell#20435]
### Description

It's not clear if this example will replace existing Source IP(s), or add the new Source IP to the existing list.
Can you please add some clarification?

https://learn.microsoft.com/en-us/powershell/module/az.network/set-aznetworksecurityruleconfig?view=azps-9.2.0#example-4

**Comment by RakeshMohanMSFT** [comment]
@pgbfnf Thank you for reaching out, we are looking into it.

**Comment by pgbfnf** [comment]
"update" can mean one of two things:
1) the existing values are removed and the new value takes their place
2) the existing values are retained and the new value is added to the list of existing values

Please clarify which scenario this example is.

**Comment by RakeshMohanMSFT** [comment]
> "update" can mean one of two things:
> 
> 1. the existing values are **removed** and the new value takes their place
> 2. the existing values are **retained** and the new value is added to the list of existing values
> 
> Please clarify which scenario this example is. We are trying to research how to accomplish scenario 2. (we want to add an additional IP to an existing list of IPs on a rule)

This is scenario 1, the existing values are removed and the new value takes its place.
This is not an append operation but a replace one.

For Appending you can use this command instead.
```
$nsg = Get-AzNetworkSecurityGroup -ResourceGroupName "Issue20435" -Name "issue20435nsg"
$prefix = ($nsg.SecurityRules | Where-Object {$_.Name -eq "issue20435rule"}).SourceAddressPrefix
$prefix.Add("10.0.1.3")
($nsg.SecurityRules | Where-Object {$_.Name -eq "issue20435rule"}).SourceAddressPrefix = ([System.String[]] $prefix)
$nsg | Set-AzNetworkSecurityGroup | Get-AzNetworkSecurityRuleConfig -Name "issue20435rule"
```

![image](https://user-images.githubusercontent.com/49954584/207794347-66b7bc36-671c-466a-bf86-2f79076fc2f2.png)
