### ISSUE TITLE
The specified module 'Az' with version '8.0.0' was not loaded because no valid module file was found in any module directory

### ISSUE THREAD

**Issue by ilantom** [Azure/azure-powershell#20430]
### Description

I have a PS script as a YAML task to install Az module. On deployment, I see this error:

> The specified module 'Az' with version '8.0.0' was not loaded because no valid module file was found in any module directory.

Here is the script:

```
Install-Module Az -RequiredVersion 8.0.0 -Scope CurrentUser -Force -AllowClobber
Import-Module Az -RequiredVersion 8.0.0 -Force
```
What am I missing?

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/d0pvD.png

**Comment by dingmeng-xue** [comment]
@ilantom , could you share your script how you install Az? In addition, is there any debug message around `Install-Module`?
