### ISSUE TITLE
Get-AzureRmVirtualNetworkGatewayConnection got authorization error with custom roles.

### ISSUE THREAD

**Issue by m-moris** [Azure/azure-powershell#2043]
I'm trying to define custom roles in RBAC. For example, I'd like to permit a minimum of authority for `Get-AzureRmVirtualNetworkGatewayConnection` command and I tried these steps.
1. Define following action in custom role.
   `
   "Microsoft.Network/virtualNetworks/read"
   `
2. Execute `Get-AzureRmVirtualNetworkGatewayConnection` commnand. 
3. Got following error.
   `
   Get-AzureRmVirtualNetworkGatewayConnection : The client 'xxxxx' with object id 'xxxxx' does not have authorization to perform action 'Microsoft.Network/connections/read' over scope '/subscriptions/yyyyyy/resourceGroups/some-resouce-groups/providers/Microsoft.Network/connections/vnet-connection'.
   `

In my understanding, the above error message means to permit authorization of 'Microsoft.Network/connections/read' action to custom role. However, I cannot find 'Microsoft.Network/connections/read' action from `Get-AzureRmProviderOperation`.

How do I permit correct actions?

Thanks.

**Comment by maddieclayton** [comment]
Closing, but please reopen if you still have this issue.
