### ISSUE TITLE
Azure Az PowerShell module for macOS errors when setting up user's parameters

### ISSUE THREAD

**Issue by NoahOliva** [Azure/azure-powershell#20450]
### Description

**_Introduction:_**
I'm using the commands for Azure to assign an MS365 license and set up other parameters for a new user, like phone number, employee ID and Usage Location. I have installed PowerShell 7.3.1 in macOS Ventura 13.0.1

**_Azure Az Powershell module._**
I have installed the Exchange Powershell module, which works fine. The problem is the Azure Az Powershell module that I installed using:

>  Install-Module -Name Az -Repository PSGallery -Force

I followed this documentation: https://learn.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-9.1.0#troubleshooting

The script that I'm using is the following:

>  Connect-AzAccount -AccountId [myemailaddress]
>     
>  Set-AzADUser -ObjectId test1@gogpac.com -TelephoneNumber "(111) 222-3333" -UsageLocation US
>  $license = New-Object -TypeName Microsoft.Open.AzureAD.Model.AssignedLicense
>  $license.SkuId =(Get-AzureADSubscribedSku | Where-Object -Property SkuPartNumber -Value SPE_E5 -EQ).SkuID
>  $licenses = New-Object -TypeName Microsoft.Open.AzureAD.Model.AssignedLicenses
>  $licenses.AddLicenses = $License
>  Set-AzADUserLicense -ObjectId test1@gogpac.com -AssignedLicenses $licenses
>  Set-AzADUserExtension -ObjectID test1@gogpac.com -ExtensionName EmployeeID -ExtensionValue "AAA"

_Issue:_
I can connect without problems to Azure using the first command:

>  Connect-AzAccount -AccountId [myemailaddress]

The problem comes up next when I run the rest of the script, giving me the errors below:

> PS /Users/noeoliva> Set-AzureADUser -ObjectId test1@gogpac.com -TelephoneNumber "(111) 222-3333" -UsageLocation US
> Update-AzADUser: A parameter cannot be found that matches parameter name 'TelephoneNumber'.
> PS /Users/noeoliva>  $license = New-Object -TypeName Microsoft.Open.AzAD.Model.AssignedLicense
> New-Object: Cannot find type [Microsoft.Open.AzAD.Model.AssignedLicense]: verify that the assembly containing this type is loaded.
> PS /Users/noeoliva>  $license.SkuId =(Get-AzureADSubscribedSku | Where-Object -Property SkuPartNumber -Value SPE_E5 -EQ).SkuID
> Get-AzureADSubscribedSku: The term 'Get-AzureADSubscribedSku' is not recognized as a name of a cmdlet, function, script file, or executable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> PS /Users/noeoliva>  $licenses = New-Object -TypeName Microsoft.Open.AzureAD.Model.AssignedLicenses
> New-Object: Cannot find type [Microsoft.Open.AzureAD.Model.AssignedLicenses]: verify that the assembly containing this type is loaded.
> PS /Users/noeoliva>  $licenses.AddLicenses = $License
> InvalidOperation: The property 'AddLicenses' cannot be found on this object. Verify that the property exists and can be set.
> PS /Users/noeoliva>  Set-AzADUserLicense -ObjectId test1@gogpac.com -AssignedLicenses $licenses
> Set-AzADUserLicense: The term 'Set-AzADUserLicense' is not recognized as a name of a cmdlet, function, script file, or executable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> PS /Users/noeoliva>  Set-AzADUserExtension -ObjectID test1@gogpac.com -ExtensionName EmployeeID -ExtensionValue "AAA"
> Set-AzADUserExtension: The term 'Set-AzADUserExtension' is not recognized as a name of a cmdlet, function, script file, or executable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

![AzureConnection](https://user-images.githubusercontent.com/45153909/207789176-2ac795ad-2ed7-4c3e-8863-26204742b05d.png)
![AzureErrors](https://user-images.githubusercontent.com/45153909/207789177-16217197-ef30-4c43-a42d-d1508dfb2cdd.png)

Any suggestion? Am I missing something or doing something wrong?
Please let me know. Thanks!
-Noe

**Comment by dingmeng-xue** [comment]
@NoahOliva , cmdlet `{}-AzureAD{}` cmdlet doesn't belong to Azure PowerShell. It is maintained by AzureAd team. User needs to login to AzureAd module and Azure PowerShell module separately. 

I remember AzureAd module only can work with Windows PowerShell and .NET framework. Did you try AzureAD cmdlet on MacOs before Az.Accounts is imported? If AzureAd module can work with PowerShell 7.* on MacOs, you need to manipulate the order of module importing. Please try import Az.Accounts before AzureAD module. If it doesn't work, reverse the order of import and try again.

**Comment by NoahOliva** [comment]
@dingmeng-xue Thanks you for the reply! I tried that, but it did not work. BTW, I'm using the module Az, not AzureAD, because I'm aware that AzureAD only works on Windows systems; I'm not sure about the Az module...
Also, I was told to use Microsoft Graph Powershell because it is cross-platform. So I will try and see how to connect Azure with it in macOS systems.

Again, thanks for the reply! :)

**Comment by dingmeng-xue** [comment]
Hi @NoahOliva , for instance, `Get-AzureADSubscribedSku` in your script comes from AzureAD module. You can use `(Get-Command -Name Get-AzureADSubscribedSku).Source` to get the name of its module. I believe the name either is AzureAD or AzureADPreview.

Azure PowerShell team doesn't have plan to expand our coverage to all Microsoft graph APIs. We only support fundamental API of AzureAD user, app, service principal, and user group. We don't provide cmdlet like `Set-AzADUserLicense` or ` Set-AzADUserExtension`. For the time, the workaround is that you can use [`Invoke-AzRestMethod`](https://learn.microsoft.com/en-us/powershell/module/az.accounts/invoke-azrestmethod?view=azps-9.2.0#example-2) (belongs to Az.Accounts module) to send request to MSGraph API directly. The response is raw response payload in JSON format.
