### ISSUE TITLE
VM Extensions?

### ISSUE THREAD

**Issue by ronbok** [Azure/azure-powershell#2046]
https://blogs.msdn.microsoft.com/azuresecurity/2016/02/24/update-on-microsoft-antimalware-and-azure-resource-manager-arm-vms/

There appears to be a large gap here for VM ARM extensions.  First we need the ability to query a region and get a list of available extensions to be applied to a VM.  Then we need a much simpler method to apply them.  Right now the Portal UI doesn't even have the ability to add VM extensions and the PowerShell cmdlets don't exist or aren't even documented.

**Comment by singhkay** [comment]
@ronbok Completely understand the frustration! Unfortunately, there is currently not an API available that allows us to do this. There are folks working on improving the image/extension APIs at which point we'll be able to deliver a better experience.

Extensions are documented here https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-extensions-features/ 

You can add extension to a VM from VM settings as shown below
![image](https://cloud.githubusercontent.com/assets/6164178/14834665/7197f8f0-0bba-11e6-8900-a306dc60bc51.png)

**Comment by LeonidasRR** [comment]
Can the BGinfoExtension be deleted once installed on a VM? I did it form the ARM portal/VM config blade, however, after a reboot the extension is still present.
