### ISSUE TITLE
[Doc]: https://learn.microsoft.com/en-us/powershell/module/az.keyvault/remove-azkeyvaultsecret?view=azps-9.2.0#example-3-purge-deleted-secret-from-the-key-vault-permanently

### ISSUE THREAD

**Issue by jesshaines** [Azure/azure-powershell#20468]
### Description

At the doc linked above, there is a small typo below example #3. The word "premoves" should be "removes".

**Comment by RakeshMohanMSFT** [comment]
@jesshaines Thank you for your help, we will fix it.
