### ISSUE TITLE
[Feature]: Add WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE app settings when Linux Consumption function app is created.

### ISSUE THREAD

**Issue by khkh-ms** [Azure/azure-powershell#20478]
### Description of the new feature

Currently we have special conditions for Linux Consumption for these app settings and because of special conditions, these app settings are only added for Python, Powershell and Node. There are not added for Java and dotnet. They need to be added for all languages.

### Proposed implementation details (optional)

Basically, the ask is to remove the special handling for Linux Consumption in terms of the mentioned app settings and implement whatever we do for Windows consumption today.

**Comment by dingmeng-xue** [comment]
@khkh-ms , please provide detail information such as which RP, service, resource type, even property and API version you are talking about. Is there official documentation about it?

**Comment by khkh-ms** [comment]
I am going to close this issue because the mentioned settings are being added in the new created Linux Consumption function app by Azure PowerShell.
