### ISSUE TITLE
Positional parameter doesn't work for Login-AzureRmAccount

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2048]
This should be a simple fix.

![image](https://cloud.githubusercontent.com/assets/466713/14249182/bc6f55da-fa35-11e5-8b19-47c2275d3b21.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
### Proposed Solution
Add a Position tag to PSCredential in the 'OrigId login' parameter set

### Cost (Work Units): 1

**Comment by cormacpayne** [comment]
Issue has been resolved in PR https://github.com/Azure/azure-powershell/pull/3042
