### ISSUE TITLE
Any change in Az.Resources for Adf?

### ISSUE THREAD

**Issue by gshapiyevInspereX** [Azure/azure-powershell#20495]
### Description

Hi

Have 6.0.1 version of Az.Resources installed. Deploying Adf resources (Pipelines/Dataflows) everything works fine
Have another machine with version 6.5.0. Resources deploying fine except some that have reference to other resources with names that have spaces in them.

Example: 
- Pipeline "Pipeline1" references Dataflow "My Great Dataflow"
- Dataflow deploys fine
- When creating Pipeline1 get an error that it can't find resource named 'mygreatdataflow'
- Changing dataflow name to one without spaces works fine

So is this a bug or a feature?

### Issue script & Debug output

```PowerShell
Too much going on there
Debug output shows first json of my resource with all original names
HTTP PUT debug output has all names replaced with ones without spaces
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Az - 9.2.0
Az.Resources - 6.5.0 (6.0.1 works fine)
```

### Error output

```PowerShell
BadRequest : The document creation or update failed because of invalid reference 'mygreatdataflow'
```

**Comment by dingmeng-xue** [comment]
@gshapiyevInspereX , sorry for that. It is a regression issue  #20386  introduced by contributor. We have fixed the issue and released new version of Az.Resources 6.5.1.

**Comment by gshapiyevInspereX** [comment]
Thank you!
