### ISSUE TITLE
Invoke-AzOperationalInsightsQuery : Unable to deserialize the response.

### ISSUE THREAD

**Issue by ibutbul1** [Azure/azure-powershell#20522]
### Description

Up until this morning, all the queries sent by PowerShell script to the Log Analytics Workspaces responded as expected, both from host PowerShell session and from Azure Automaton infrastructure (Hybrid Worker and Azure).

Now I'm getting the following error - Invoke-AzOperationalInsightsQuery : Unable to deserialize the response.

### Issue script & Debug output

```PowerShell
$Query = @'
AuditLogs
| where OperationName == "Remove member from group"
| where TimeGenerated > now() - 7d
'@

$GroupMembershipLogs = (Invoke-AzOperationalInsightsQuery -WorkspaceId $WorkspaceID -Query $Query -ErrorAction Stop).Results
```

### Environment data

```PowerShell
Name                           Value                                                                                                                                                                 
----                           -----                                                                                                                                                                 
PSVersion                      5.1.22621.963                                                                                                                                                         
PSEdition                      Desktop                                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                               
BuildVersion                   10.0.22621.963                                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                                   
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Az.OperationalInsights - 3.2.0 
Az.Accounts - 2.10.4
```

### Error output

```PowerShell
Invoke-AzOperationalInsightsQuery : Unable to deserialize the response.
At line:1 char:25
+ ... shipLogs = (Invoke-AzOperationalInsightsQuery -WorkspaceId $Workspace ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Invoke-AzOperationalInsightsQuery], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.OperationalInsights.Query.InvokeOperationalInsightsQuery
```

**Comment by navba-MSFT** [comment]
@ibutbul1 Thanks for reaching out to us and reporting this issue. Could you please wrap your script in an [InlineScript](https://learn.microsoft.com/en-us/azure/automation/automation-powershell-workflow#use-inlinescript) block and run in Azure Automation to check if that works ? Awaiting your reply.

InlineScript {
        $GroupMembershipLogs = (Invoke-AzOperationalInsightsQuery -WorkspaceId $WorkspaceID -Query $Query -ErrorAction Stop).Results



    }

**Comment by ibutbul1** [comment]
Now I'm not getting any errors but there is no response and the count of the objects of that query is null.

workflow test
{
InlineScript {
$GroupMembershipLogs = (Invoke-AzOperationalInsightsQuery -WorkspaceId $WorkspaceID -Query $Query -ErrorAction Stop).Results

}
}

It's look like it is retrieving objects when I'm trying to output them to the terminal, but it's blank:

(Invoke-AzOperationalInsightsQuery -WorkspaceId $WorkspaceID -Query $Query -ErrorAction Stop).Results

**Comment by navba-MSFT** [comment]
@ibutbul1 Thanks for your reply. Could you please run this 
`$DebugPreference="Continue" `command first and then run your script? See the verbose logs to check if the REST API has returned the valid response. This will help us isolate if this is a service issue / a script issue.

**Comment by navba-MSFT** [comment]
@ibutbul1 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by ibutbul1** [comment]
Hi,

We’ve isolated to issue to a proxy subject, once we investigate the packets, we noticed that there was HTTP Inspection to the URL api.loganalitycs.io, which “broke” the packet when the query came back.

Once we excluded that URL, the query responded as expected.

You can close the issue, thanks for the assistance!
