### ISSUE TITLE
[Feature]: Get-AzRoleManagementPolicyAssignment should support filter queries

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/azure-powershell#20566]
### Description of the new feature

Currently `Get-AzRoleManagementPolicyAssignment` does not have a `-Filter` parameter. We should include one so we can filter role management policy assignments.

Or perhaps this cmdlet should have parameters like `-RoleDefinitionId` so we can do more useful filtering.

**Comment by dingmeng-xue** [comment]
@ArmaanMcleod , thanks for reporting. could you explain further about functions of `-Filter`? Azure PowerShell either uses service feature when it exposes filter functions, or uses `Where-Object` PowerShell cmdlet to filter result.

**Comment by ArmaanMcleod** [comment]
@dingmeng-xue looks like this cmdlet doesn't need `-Filter` from the underlying API: https://learn.microsoft.com/en-us/rest/api/authorization/role-management-policy-assignments/get.

I will close this issue, thanks for clarifying.
