### ISSUE TITLE
MSI package for latest Az modules (9.3) missing

### ISSUE THREAD

**Issue by benoithamet** [Azure/azure-powershell#20611]
### Description

Hi there
can you please provide the MSI package as you usually do for the latest version?
thanks

**Comment by dingmeng-xue** [comment]
@benoithamet , thanks for reminder. We hit performance issue of Github. It was always timeout when pipeline fetch source code of azure powershell. I have completed all tasks and updated release now. https://github.com/Azure/azure-powershell/releases/tag/v9.3.0-January2023
