### ISSUE TITLE
[Doc]: cmdlet examples issue.

### ISSUE THREAD

**Issue by LucasYao93** [Azure/azure-powershell#20625]
### Description

The examples of the cmdlet has issue. Details as following:
## Az.ApiManagement
```
"Az.ApiManagement","Restore-AzApiManagement","2","0","NeedDeleting","5050","1","The prompt of example need to be deleted.","D:\a\_work\1\s\src\ApiManagement\ApiManagement\help\Restore-AzApiManagement.md","Delete the prompt of example."
```

## Az.Batch
```
"Az.Batch","Get-AzBatchSupportedVirtualMachineSku","0","0","MissingDescription","5041","1","Description is missing.","D:\a\_work\1\s\src\Batch\Batch\help\Get-AzBatchSupportedVirtualMachineSku.md","Add Description. Remove any placeholders."
"Az.Batch","Get-AzBatchTaskSlotCount","1","1","Invalid_Cmdlet","5000","1","Get-AzBatchTaskSlotCounts is not a valid command name.","Get-AzBatchTaskSlotCounts -JobId 'Job01' -BatchContext $Context","Check the spell of Get-AzBatchTaskSlotCounts."
"Az.Batch","Remove-AzBatchJob","3","10","Unbinded_Expression","5014","1","Write-Host $element.Id is not explicitly assigned to a parameter.","$element.Id","Assign $element.Id explicitly to the parameter."
"Az.Batch","Start-AzBatchComputeNodeServiceLogUpload","3","1","Invalid_Cmdlet","5000","1","New-AzStorageContext is not a valid command name.","New-AzStorageContext -StorageAccountName 'contosogeneral' -StorageAccountKey '<Storage Key for ContosoGeneral ends with ==>'","Check the spell of New-AzStorageContext."
```

## Az.FrontDoor
"Az.FrontDoor","New-AzFrontDoorBackendPoolsSettingObject","1","1","Capitalization_Conventions_Violated","5101","1","New-AzFrontDoorBackendpoolsSettingObject doesn't follow the Capitalization Conventions.","New-AzFrontDoorBackendpoolsSettingObject","Check the Capitalization Conventions. Suggest format: New-AzFrontDoorBackendPoolsSettingObject"
"Az.FrontDoor","New-AzFrontDoorBackendPoolsSettingObject","2","1","Capitalization_Conventions_Violated","5101","1","New-AzFrontDoorBackendpoolsSettingObject doesn't follow the Capitalization Conventions.","New-AzFrontDoorBackendpoolsSettingObject -SendRecvTimeoutInSeconds 60 -EnforceCertificateNameCheck Enabled","Check the Capitalization Conventions. Suggest format: New-AzFrontDoorBackendPoolsSettingObject"

## Az.HPCCache
"Az.HPCCache","Get-AzHpcCache","1","1","Capitalization_Conventions_Violated","5101","1","Get-AzHPCCache doesn't follow the Capitalization Conventions.","Get-AzHPCCache -ResourceGroupName rgtest -CacheName cachetest","Check the Capitalization Conventions. Suggest format: Get-AzHpcCache"
"Az.HPCCache","Get-AzHpcCache","2","1","Capitalization_Conventions_Violated","5101","1","Get-AzHPCCache doesn't follow the Capitalization Conventions.","Get-AzHPCCache -ResourceGroupName rgtest","Check the Capitalization Conventions. Suggest format: Get-AzHpcCache"
"Az.HPCCache","Get-AzHpcCache","3","1","Capitalization_Conventions_Violated","5101","1","Get-AzHPCCache doesn't follow the Capitalization Conventions.","Get-AzHPCCache","Check the Capitalization Conventions. Suggest format: Get-AzHpcCache"

**Comment by dingmeng-xue** [comment]
Let's track that internally with service team.

**Comment by JoyerJin** [comment]
Fixed and Merged
