### ISSUE TITLE
https://learn.microsoft.com/en-us/powershell/module/az.servicebus/set-azservicebusqueue?view=azps-9.3.0

### ISSUE THREAD

**Issue by akhudairymicrosoft** [Azure/azure-powershell#20636]
### Description

Hi,

I work in MS support for service bus.

I was trying to set (ForwardDeadLetteredMessagesTo ) to an empty string, and strange thing I kept getting an error even when passing value to it
Set-AzServiceBusQueue : A parameter cannot be found that matches parameter name 'ForwardDeadLetteredMessagesTo'.
At line:1 char:100

The other thing it is not clear, how to set such values for empty. because this is a feature that is enabled if a string is passed, and to disable it i needed to pass an empty string. I tried with CLI also, and it didn't accept empty string.

In the end I reached a solution on how to do it
PS C:\Users\akhudairy> $queue=Get-AzServiceBusQueue -Name testdlqforwardzz -NamespaceName testsbnamespace -ResourceGroupName training
PS C:\Users\akhudairy> **$queue.ForwardDeadLetteredMessagesTo=''**
PS C:\Users\akhudairy> Set-AzServiceBusQueue -Name testdlqforwardzz  -NamespaceName testsbnamespace -ResourceGroupName training -QueueObj $queue

I hope documentation is more clear for such scenarios.

**Comment by RakeshMohanMSFT** [comment]
@akhudairymicrosoft Thank you for reaching out to us. We are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@akhudairymicrosoft Can you please try this command? it works
```
$queue=Get-AzServiceBusQueue -Name issue20636queue -NamespaceName issue20636sb -ResourceGroupName Issue20636
Set-AzServiceBusQueue -InputObject $queue -ForwardDeadLetteredMessagesTo ''
```
![image](https://user-images.githubusercontent.com/49954584/213193616-4d4857ef-dde0-41fb-9690-b6d3758917c6.png)

**Comment by akhudairymicrosoft** [comment]
To be honest it is not working for me, but I am sure I am just making some silly mistake. I think what you suggested is pretty close to what i mentioned in my original post, but you made it better to use 2 lines only.
I think what I was missing is maybe common knowledge for people who use powershell and scripts a lot, which is the idea to save the queue object, as this was something very new to me. Also in CLI it turns out that i had to send empty value as " " with a space in between which I also didn't know.

I will suggest to Product Group of Service Bus to add in their documentation a sample on how to disable the forward feature, because it cannot be disabled from Portal, and someone like me who doesn't have lots of experience in PowerShell will take long time to figure things out.

Thanks again, This issue can be close from my side.
