### ISSUE TITLE
[Doc]: Get-AzVM help has no examples or context for -nextlink parameter

### ISSUE THREAD

**Issue by guyrleech** [Azure/azure-powershell#20658]
### Description

If it is for paginated results as with REST calls, how do you know that there is more data to fetch, as in get the URI to pass to -nextlink?

**Comment by SaurabhSharma-MSFT** [comment]
@guyrleech We are looking into it and get back to you for any additional information.

**Comment by dingmeng-xue** [comment]
https://github.com/Azure/azure-powershell/blob/main/src/Compute/Compute/VirtualMachine/Operation/GetAzureVMCommand.cs#L222

It seems Get-AzVM supports pagination internally. No idea why it exposes NextLink. Please consult Compute team. It may be not used now.

**Comment by TravisCragg-MSFT** [comment]
I am following up with this to see if this is expected behavior.

**Comment by TravisCragg-MSFT** [comment]
@guyrleech This parameter is not used in PowerShell, it has an internal pagination mechanism. We are working to update the docs to explain this parameter or remove it entirely.

**Comment by TravisCragg-MSFT** [comment]
@guyrleech This parameter is being removed with the next update and is not used.
