### ISSUE TITLE
Feature request: Query status of sql server deletion operation

### ISSUE THREAD

**Issue by MikalJ** [Azure/azure-powershell#2065]
When deleting a sql server via powershell (or the portal) success is indicated fairly quickly, and the sql server disappears from all listings (including Get-AzureRmSqlServer cmdlet). However in reality it seems the sql server has just been queued for deletion. A process which it seems can take upwards to 15 minutes.

This is evident if you attempt to create a new sqlserver with the same name.
New-AzureRmSqlServer will generate an error like this:

```
New-AzureRmSqlServer : 45157: Server 'xyz' is busy with another operation. Please try your operation later.
At line:1 char:1
+ New-AzureRmSqlServer -ResourceGroupName abc -Location "North Europe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmSqlServer], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.Server.Cmdlet.NewAzureSqlServer
```

I would like a way to query the status of the delete operations, so that I can decide whether to wait, or use a different name in my resource provisioning scripts.

This could possibly be generic enough to work with other "queued" azure operations (such as moving a resource to a different resourcegroup), like a Get-AzureRmOperationStatus cmdlet

**Comment by DerekFoster1976** [comment]
Still the same issue here.

**Comment by nelsonmorais** [comment]
Same issue here

**Comment by akromm** [comment]
@MikalJ backend work has been done to make server delete asynchronous. As a result the cmdlets will be updated to poll for the status of the delete and wait until the server delete is complete. @jaredmoo is currently working on updating the cmdlets.

**Comment by jaredmoo** [comment]
Thanks @akromm . After https://github.com/Azure/azure-powershell/pull/4132 is merged, Remove-AzureRmSqlServer will wait until the server is fully deleted.

**Comment by akromm** [comment]
#4132 has been merged so closing this issue.
