### ISSUE TITLE
Enter-AzVM fails with Index out of range

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#20659]
### Description

Attempting to connect with Enter-AzVM fails with "Index out of range". Making an SSH config has the same issue.

Attempting to connect to a VM while on an AVD in the same private network as the host.

Looks to be an unhandled null reference, something was expected to come back from `PrepareAADCredentials` and didn't.

Possibly here, there is a faulty assumption that GetSSHCertPrincipals always returns something.

I should note the az cli works just fine in the same context 

https://github.com/Azure/azure-powershell/blob/c5b7bf023005c5a4933142db6907d58394925275/src/Ssh/Ssh/Common/SshBaseCmdlet.cs#L401

### Issue script & Debug output

```PowerShell
Get-AzVM -name myvm | Enter-AzVM -UsePrivateIP -Verbose -Debug
```

### Environment data

```PowerShell
7.2.3
```

### Module versions

```PowerShell
Az.SSH 0.1.0
```

### Error output

```
VERBOSE: Created Keys C:\Users\local_jgrote\Temp\aadsshcertuubfqvqa\id_rsa.pub and C:\Users\local_jgrote\Temp\aadsshcertuubfqvqa\id_rsa.
VERBOSE: AAD issued SSH certificate will be written to C:\Users\local_jgrote\Temp\aadsshcertuubfqvqa\id_rsa.pub-aadcert.pub.
VERBOSE: Created Certificate C:\Users\local_jgrote\Temp\aadsshcertuubfqvqa\id_rsa.pub-aadcert.pub.
DEBUG: Runnung ssh-keygen command: C:\Windows\System32\OpenSSH\ssh-keygen.exe -L -f "C:\Users\local_jgrote\Temp\aadsshcertuubfqvqa\id_rsa.pub-aadcert.pub"
DEBUG: 8:47:01 AM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
Enter-AzVM: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
DEBUG: 8:47:02 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: az.ssh:0.1.0; CommandName: Enter-AzVM; PSVersion: 7.2.3; IsSuccess: False; Duration: 00:00:04.0602965; Exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index');
DEBUG: 8:47:02 AM - EnterAzVMCommand end processing.
```

### Resolve-AzError Output

```
Message        : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
StackTrace     :    at System.Collections.Generic.List`1.get_Item(Int32 index)
                    at Microsoft.Azure.Commands.Ssh.SshBaseCmdlet.PrepareAadCredentials(String credentialFolder)
                    at Microsoft.Azure.Commands.Ssh.EnterAzVMCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentOutOfRangeException
InvocationInfo : {Enter-AzVM}
Line           : get-azvm -Name sapxs1a01 | Enter-AzVM -UsePrivateIp
Position       : At line:1 char:28
                 + get-azvm -Name sapxs1a01 | Enter-AzVM -UsePrivateIp
                 +                            ~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 17
```

**Comment by dingmeng-xue** [comment]
CXP team, please look into it at first.

**Comment by jaylabell** [comment]
This is an Az.Ssh issue and not an Az.Compute issue. For now the Compute service label will be removed.  

@vthiebaut10 will be looking into this issue.

**Comment by vthiebaut10** [comment]
@JustinGrote Thank you for reporting this issue. I haven't been able to repro the behavior you described.
It seems that the AAD certificate is being created, but for some reason the cmdlet is failing to get the principals from that certificate. It seems that there is something weird with the AAD certificate format.
Could you run the Export-AzSshConfig, and share with me the generated certificate? (Run it with -Verbose and you are able to see where the certificate is being saved). You can e-mail me the certificate if you want (vthiebaut@microsoft.com).

Also, are you logged in with your Azure account? Or are you logged in with a service principal, or a managed identity or something like that?

**Comment by JustinGrote** [comment]
This is with my azure account, I tried with a broad rights account as well with the same issue. When I have some time I will work to generate it.

The problem with your request is that the script deletes the temporary files before I can fetch it.

**Comment by vthiebaut10** [comment]
@JustinGrote Enter-AzVM deletes the temporary files on error, but Export-AzSshConfig does not. You should be able to access the temporary files after the failute.

**Comment by vthiebaut10** [comment]
Hi @JustinGrote - any updates on getting the failing certificate using the Export-AzSshConfig cmdlet?

**Comment by vthiebaut10** [comment]
Got it. Let me know if you are ever able to repro it again. I'd love to get this fixed by the next release.

**Comment by sheetalkjain** [comment]
I am also getiting the same error @vthiebaut10 Can I get some help?  Here is the command I am issuing

New-AZVM -ResourceGroupName $rgName -Location $locName -VM $vm
Response: New-AzVM: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

Here is the complete set of commands

# Create an availability set for domain controller virtual machines
New-AZAvailabilitySet -ResourceGroupName $rgName -Name dcAvailabilitySet -Location $locName -Sku Aligned -PlatformUpdateDomainCount 5 -PlatformFaultDomainCount 2

# Create the domain controller virtual machine
$vnet = Get-AZVirtualNetwork -Name EXSrvrVnet -ResourceGroupName $rgName

$pip = New-AZPublicIpAddress -Name adVM-NIC -ResourceGroupName $rgName -Location $locName -AllocationMethod Dynamic

$nic = New-AZNetworkInterface -Name adVM-NIC -ResourceGroupName $rgName -Location $locName -SubnetId $vnet.Subnets[0].Id -PublicIpAddressId $pip.Id -PrivateIpAddress 10.0.0.4

$avSet=Get-AZAvailabilitySet -Name dcAvailabilitySet -ResourceGroupName $rgName

$vm=New-AZVMConfig -VMName adVM -VMSize Standard_D1_v2 -AvailabilitySetId $avSet.Id

$vm=Set-AZVMOSDisk -VM $vm -Name adVM-OS -DiskSizeInGB 128 -CreateOption FromImage -StorageAccountType "Standard_LRS"

$diskConfig=New-AZDiskConfig -AccountType "Standard_LRS" -Location $locName -CreateOption Empty -DiskSizeGB 20

$dataDisk1=New-AZDisk -DiskName adVM-DataDisk1 -Disk $diskConfig -ResourceGroupName $rgName

$vm=Add-AZVMDataDisk -VM $vm -Name adVM-DataDisk1 -CreateOption Attach -ManagedDiskId $dataDisk1.Id -Lun 1

$cred=Get-Credential -Message "Type the name and password of the local administrator account for adVM."

$vm=Set-AZVMOperatingSystem -VM $vm -Windows -ComputerName adVM -Credential $cred -ProvisionVMAgent -EnableAutoUpdate

$vm=Set-AZVMSourceImage -VM $vm -PublisherName MicrosoftWindowsServer -Offer WindowsServer -Skus 2012-R2-Datacenter -Version "latest"

$vm=Add-AZVMNetworkInterface -VM $vm -Id $nic.Id

New-AZVM -ResourceGroupName $rgName -Location $locName -VM $vm

**Comment by vthiebaut10** [comment]
@sheetalkjain  Thank you for reporting this error. This seems to be an issue with the Az.Compute module instead of the Az.Ssh module. @SaurabhSharma-MSFT @jaylabell  can you help us direct this issue to the owners of az.compute?
