### ISSUE TITLE
[Feature]: New-AzRoleEligibilityScheduleRequest should support permanent eligible assignments

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#20661]
### Description of the new feature

The current implementation only allows specifying an end duration. If the end duration is null, it defaults to 1 year.

### Proposed implementation details (optional)

Add a parameter set that allow a custom `expirationpattern` to be supplied, so that the `expirationPatternType` can be set to `noExpiration`
https://learn.microsoft.com/en-us/graph/api/resources/expirationpattern?view=graph-rest-1.0

Alternatively you can support a bunch of different parameter sets for all the different kind of patterns, but that would make this command really ugly. A separate `New-ExpirationPattern` cmdlet as a helper for making that object would also be fine.

**Comment by dingmeng-xue** [comment]
@JustinGrote , thanks for suggestion. The latest `New-AzRoleEligibilityScheduleRequest` allows user to set `-ExpirationType` to `NoExpiration`. Please try it.
