### ISSUE TITLE
[Doc]: Update-AzCosmosDBSqlContainer,  The example command stated in the document is different from the actual command mentioned in the description 

### ISSUE THREAD

**Issue by nevethas** [Azure/azure-powershell#20677]
### Description

![microsoft-typo](https://user-images.githubusercontent.com/107465500/212667106-78269317-20b6-43ae-9da5-ce14e885b556.png)

**Comment by SaurabhSharma-MSFT** [comment]
@nevethas We are looking into it and get back to you for any additional information.

**Comment by nevethas** [comment]
Hi Dingmeng, With Azure powershellwe can perform operation till container level but we need more granular level in inserting item/ documents to container. This cmdlet is what we are leveraging ‘new-cosmosdbdocument‘ for inserting and updating document which is not available in Azure powershell.

**Comment by SaurabhSharma-MSFT** [comment]
@nevethas The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.

**Comment by nevethas** [comment]
Hi SaurabhSharma, need an update on this query With Azure powershell we can perform operation till container level, but we need more granular level in inserting item/ documents to container. This cmdlet is what we are leveraging 
‘new-cosmosdbdocument‘ for inserting and updating document which is not available in Azure powershell.

**Comment by SaurabhSharma-MSFT** [comment]
@nevethas Can you please open a new GitHub issue so that we can track this requirement as a feature request. Thanks
