### ISSUE TITLE
[Doc]: Subscription, resource group and resource name are required but not set in the example.

### ISSUE THREAD

**Issue by nakawankuma** [Azure/azure-powershell#20710]
### Description

https://learn.microsoft.com/ja-jp/powershell/module/az.purview/new-azpurviewazuresynapseworkspacedatasourceobject?view=azps-9.3.0

Subscription, resource group and resource name are required but not set in the example.

**Comment by RakeshMohanMSFT** [comment]
@nakawankuma We are unable to reproduce this issue? can you please upgrade to latest modules of Az.Purview if you are using an older one.
![image](https://user-images.githubusercontent.com/49954584/213414310-353a68d3-e3c0-4693-b620-e7600ace2cfc.png)
