### ISSUE TITLE
Get-AzKeyVault does not return network ACLs if public network access is disabled, even if network ACLs exist

### ISSUE THREAD

**Issue by plzm** [Azure/azure-powershell#20744]
### Description

Scenario:
- A Key Vault has public network access enabled, default action Deny, and has some IP address network access rules
In this case, Get-AzKeyVault will correctly return the network ACLs.

- Now let's say we disable public network access, and leave the network ACLs intact.
In this case, Get-AzKeyVault no longer returns the network ACLs!

Why is this bad?

Here's the scenario:
- A Key Vault has public network access enabled and some network ACLs exist
- Now we want to disable public network access and do so either in the portal or with Update-AzKeyVault -PublicNetworkAccess  Disabled.
- Now we realize wait, we need public network access with the network ACLs we had before. So we run
$keyVault = Get-AzKeyVault -SubscriptionId $SubscriptionId -ResourceGroupName $ResourceGroupName -VaultName $VaultName 
And it returns no network ACLs.

Now I call 
Update-AzKeyVault -InputObject $keyVault -PublicNetworkAccess Enabled
And I lose all the network ACLs that were on the Key Vault! Because Get-AzKeyVault does not return existing network ACLs, even if they exist, if public network access is Disabled. Get-AzKeyVault should always return network ACLs, regardless of the state of public network access.

To repro:
- Create a KV with public access Enabled and some network ACLs (like allow from 8.8.8.8, 1.1.1.1, etc.)
- Get-AzKeyVault -SubscriptionId $SubscriptionId -ResourceGroupName $ResourceGroupName -VaultName $VaultName will show the network ACLs correctly, and I can use the output of this to prepare the input object for Update-AzKeyVault
- In the Azure portal, update the KV to public access Disabled
-  Get-AzKeyVault -SubscriptionId $SubscriptionId -ResourceGroupName $ResourceGroupName -VaultName $VaultName will no longer show the network ACLs.
- Now let's say some time later I'd like to re-enable public network access and **preserve the network ACLs I had previously**. If I now run
$keyVault = Get-AzKeyVault -SubscriptionId $SubscriptionId -ResourceGroupName $ResourceGroupName -VaultName $VaultName
Update-AzKeyVault -InputObject $keyVault -PublicNetworkAccess Enabled

And now I have a Key Vault which lost all my previous network ACLs.

### Issue script & Debug output

```PowerShell
(This is pseudocode/code because you need to create a KV and I didn't want to include a bunch of non-relevant infra code here. Hopefully the following is clear enough.)

- Create a KV with public access Enabled and some network ACLs (like allow from 8.8.8.8, 1.1.1.1, etc.)
- Get-AzKeyVault -SubscriptionId $SubscriptionId -ResourceGroupName $ResourceGroupName -VaultName $VaultName will show the network ACLs correctly, and I can use the output of this to prepare the input object for Update-AzKeyVault
- In the Azure portal, update the KV to public access Disabled
-  Get-AzKeyVault -SubscriptionId $SubscriptionId -ResourceGroupName $ResourceGroupName -VaultName $VaultName will no longer show the network ACLs.
- Now let's say some time later I'd like to re-enable public network access and **preserve the network ACLs I had previously**. If I now run
$keyVault = Get-AzKeyVault -SubscriptionId $SubscriptionId -ResourceGroupName $ResourceGroupName -VaultName $VaultName
Update-AzKeyVault -InputObject $keyVault -PublicNetworkAccess Enabled- Create a KV with public access Enabled and some network ACLs (like allow from 8.8.8.8, 1.1.1.1, etc.)
- Get-AzKeyVault -SubscriptionId $SubscriptionId -ResourceGroupName $ResourceGroupName -VaultName $VaultName will show the network ACLs correctly, and I can use the output of this to prepare the input object for Update-AzKeyVault
- In the Azure portal, update the KV to public access Disabled
-  Get-AzKeyVault -SubscriptionId $SubscriptionId -ResourceGroupName $ResourceGroupName -VaultName $VaultName will no longer show the network ACLs.
- Now let's say some time later I'd like to re-enable public network access and **preserve the network ACLs I had previously**. If I now run
$keyVault = Get-AzKeyVault -SubscriptionId $SubscriptionId -ResourceGroupName $ResourceGroupName -VaultName $VaultName
Update-AzKeyVault -InputObject $keyVault -PublicNetworkAccess Enabled
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     4.9.0                 Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzKeyVaultKey, Add-AzKeyVaultManagedStorageAccount…}
Script     2.11.5                Az.Websites                         {Add-AzWebAppAccessRestrictionRule, Add-AzWebAppTrafficRouting, Edit-AzWebAppBackupConfiguration, Enter-AzWebAppContainerPSSession…}

Get-InstalledModule Az 

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
9.3.0                Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is compatible with PowerShell and Windows PowerShell.…
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will contact Keyvault team to get their feedback about this ask.

**Comment by dingmeng-xue** [comment]
We will fix it.

**Comment by BethanyZhou** [comment]
Hi @plzm , if you use `Update-AzKeyVault -ResourceGroupName **-rg -VaultName test-kv0129 -PublicNetworkAccess Disabled` to update PublicNetworkAccess, the value of NetworkAcls will be kept. While if you use portal to update PublicNetworkAccess, its value is gone, am I correct?

**Comment by jlichwa** [comment]
@plzm this is service behavior, there is nothing PowerShell Team can do. It is as designed. We will update documentation with warning for that behavior.

Key Vault Service Team
