### ISSUE TITLE
Unable to deploy an ARM template with a reference to keyvault secret

### ISSUE THREAD

**Issue by websolut** [Azure/azure-powershell#2074]
When trying to deploy a template file with a parameters file referencing a keyvault secret via powershell we are getting this error:

InvalidDeploymentParameterValue: The value of deployment parameter 'adminPassword' is null. Please specify the value or use the parameter reference. See http://aka.ms/arm-deploy/#parameter-file for details.

CLI can deploy the template without any issues.

**Comment by ravbhatnagar** [comment]
Which version of PS and CLI are you using? Two things to check from PS- 
1. Can you retrieve the value of the admin password using Get-AzureKeyVaultSecret
2. When you set the access policy on the keyvault, did you enable it for deployment and template deployment. 

If you run your deployment with a debug switch, we can have some more details to debug this issue.

**Comment by websolut** [comment]
Thanks for looking into this.
1. The version was 1.1 and 1.2. We upgraded to 1.3 and seems it is fine.

2. Checking the properties of the keyvault:
SKU                              : Standard
Enabled For Deployment?          : True
Enabled For Template Deployment? : True
