### ISSUE TITLE
New-AzNetworkWatcherConnectionMonitorEndpointObject optional parameters

### ISSUE THREAD

**Issue by KapilAnanth-MSFT** [Azure/azure-powershell#20745]
### Description

The documentation of [New-AzNetworkWatcherConnectionMonitorEndpointObject](https://learn.microsoft.com/en-us/powershell/module/az.network/new-aznetworkwatcherconnectionmonitorendpointobject?view=azps-9.2.0) mentions the **_following parameters as optional_**.

- -AzureVM
- -AzureVNet
- -AzureSubnet
- -ExternalAddress

However, it is not the case.
You have to specify either one of the parameters depending upon your endPoint ResourceID/ Address.

A note specifying the same would be helpful to customers.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. The cmdlet is generated from API spec directly. Currently, there is one of constraints that API spec cannot describe the concept of mutually inclusive or exclusive. We expect service team can add more description on API spec or service response.
