### ISSUE TITLE
[Doc]: New-AzWebAppCertificate -hostname indicates support for multiple hostnames

### ISSUE THREAD

**Issue by lars-erik** [Azure/azure-powershell#20746]
### Description

At https://learn.microsoft.com/en-us/powershell/module/az.websites/new-azwebappcertificate?view=azps-9.3.0#-hostname the doc states that the parameter is "Custom hostnames associated with web app/slot."

The parameter only supports one hostname (afaik), so the doc should read "Custom hostname associated with web app/slot".

**Comment by dingmeng-xue** [comment]
Invite CXP team to look into this question.

**Comment by lars-erik** [comment]
🥳❤
