### ISSUE TITLE
[Feature]: Az.Aks command equivalent to az aks nodepool stop/start

### ISSUE THREAD

**Issue by ksooner** [Azure/azure-powershell#20753]
### Description of the new feature

hi there, we have AKS clusters with multiple user nodepool, and would like to use Azure automation account to do some scheduling operations to stop AKS nodepools at different time and start desired nodepools with different timing as well. 
Az cli provides the feature and we need the same in Az.Aks module
https://learn.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest#az-aks-nodepool-stop

note: we don't want "Stop-AzAksCluster" as this will shutdown the whole cluster.

**Comment by dingmeng-xue** [comment]
@YanaXu , please look into it. If it is a valid requirement, we need to track it.

**Comment by YanaXu** [comment]
Hi @ksooner , 

You can start or stop nodepools with *Update-AzAksNodePool*. I provide the examples below. Please check if they meet your requirement.

Assume you get the nodepool:
```powershell
$pool = Get-AzAksNodePool -ResourceGroupName $resourceGroupName -ClusterName $aksClusterName -Name $poolName
```

- Start the nodepool

```powershell
$pool.PowerState.Code = "Running"
$pool | Update-AzAksNodePool
```

- Stop the nodepool

```powershell
$pool.PowerState.Code = "Stopped"
$pool | Update-AzAksNodePool
```

**Comment by ksooner** [comment]
hey @YanaXu, thanks for your quick response.

i just tried the suggested example, can't seem to set `$pool.PowerState.Code = "Stopped"`
Upgraded to az module 9.3 and same result.

See the screenshot below. Let me know if more information required.

![az-error](https://user-images.githubusercontent.com/27767208/216851379-d0971863-3b49-4879-a06e-3667b6f08d16.png)

**Comment by YanaXu** [comment]
Hi @ksooner, 

The parameter "PowerState" is supported since Az 9.2 (while Az.Aks version is 5.1.0). 
Could you double check your Az.Aks version?
```powershell
gmo -ListAvailable -Name Az.Aks
```
Best Regards
Yan

**Comment by ksooner** [comment]
@YanaXu i can confirm Az.Aks version 5.20 is working. 
Checked my installed modules, and i had duplicate/multiple versions of each Az.* modules installed on personal documents module folder, and also program files folder. 
Thanks for your assistant 👍
