### ISSUE TITLE
[Eng]: Spelling issue in example Analyzer of PR

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/azure-powershell#20817]
### Description

- "Az.Storage","Remove-AzStorageCORSRule","1","0","BlockTypeUnsupported","5062","1","The language identifier **powersheell** is not supported."
- "Az.Storage","Set-AzStorageBlobTag","1","0","BlockTypeUnsupported","5062","1","The language identifier  **poewrshell** is not supported

**Comment by isra-fel** [comment]
Code is in https://github.com/Azure/azure-powershell/tree/main/tools/StaticAnalysis/ExampleAnalyzer

**Comment by allandao** [comment]
I believe this issue is no present. Cheers!
