### ISSUE TITLE
[Doc]: All DataShare documents

### ISSUE THREAD

**Issue by zencifil** [Azure/azure-powershell#20822]
### Description

Data Share is a very confusing concept and none of the documents is clear about how to implement that. For example on New-AzDataShareDataSetMapping page, it says 
```
-StorageAccountResourceId
Azure Storage Account ResourceId
```
But never says if this is provider storage account or consumer storage account. Same thing for `-AccountName` and `-ResourceGroup` parameters. 

It is already a confusing topic and the documentation isn't really helping.

**Comment by navba-MSFT** [comment]
@zencifil Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@zencifil The `StorageAccountResourceId` parameter in the "New-AzDataShareDataSetMapping" PowerShell cmdlet is used to specify the resource ID of the Azure storage account that is the source of the data being shared. This parameter is required when creating a new data set mapping for an Azure Data Share and is used to identify the storage account from which the data will be shared. The resource ID of the storage account can be obtained from the Azure portal or through Azure PowerShell.

The `AccountName` parameter in the "New-AzDataShareDataSetMapping" PowerShell cmdlet is used to specify the name of the Azure storage account that is the source of the data being shared. This parameter is required when creating a new data set mapping for an Azure Data Share and is used to identify the storage account from which the data will be shared. The account name of the storage account must be unique within Azure and can be used to access the storage account and the data stored within it.

The `ResourceGroup` parameter in the "New-AzDataShareDataSetMapping" PowerShell cmdlet is used to specify the name of the Azure resource group that contains the Azure storage account being shared. This parameter is required when creating a new data set mapping for an Azure Data Share and is used to identify the resource group that holds the storage account from which the data will be shared. The resource group can be used to manage the resources within it, such as the storage account and the data set mapping.

**Comment by zencifil** [comment]
@navba-MSFT Thanks for the clarification. I'm having trouble running this command though. Here is my code and I checked every variable to see if they have value. 
```
New-AzDataShareDataSetMapping -ResourceGroupName "$sourceResourceGroupName" ` 
         -AccountName "$sourceDataShareAccountName" `
         -ShareSubscriptionName "$shareSubscriptionName" `
         -Name "$sourceDatasetName" `
         -StorageAccountResourceId "$sourceStorageResourceId" `
         -DataSetId "$sourceDatasetId" `
         -Container "$sourceContainerName"
```
I found [this](https://learn.microsoft.com/en-us/azure/data-share/subscribe-to-data-share?tabs=powershell#configure-received-share) document and it's the same command with the same parameters (even the same order). But I keep getting the error below. 
```
New-AzDataShareDataSetMapping: /agent/_work/_temp/a684a554-3272-481d-94a2-0bdc610f4304.ps1:82
Line |
  82 |    New-AzDataShareDataSetMapping -ResourceGroupName "$sourceResourceGr …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Parameter set cannot be resolved using the specified named parameters.
     | One or more parameters issued cannot be used together or an insufficient
     | number of parameters were provided.
```

What do you think I'm missing here?

**Comment by zencifil** [comment]
There are detailed debug lines for other commands but nothing for this. Previous command ends here
```
DEBUG: AzureQoSEvent:  Module: Az.DataShare:1.0.1; CommandName: Get-AzDataShareSourceDataSet; PSVersion: 7.2.8; IsSuccess: True; Duration: 00:00:00.4527253
DEBUG: 13:58:54 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 13:58:54 - GetAzDataShareSourceDataSet end processing.
```
After this, the same error appears
```
Line |
  84 |    New-AzDataShareDataSetMapping -ResourceGroupName "$resourceGroupNam …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Parameter set cannot be resolved using the specified named parameters.
     | One or more parameters issued cannot be used together or an insufficient
     | number of parameters were provided.
```
