### ISSUE TITLE
New-AzAksCluster How to specify outbound routing type

### ISSUE THREAD

**Issue by ChrisRomp** [Azure/azure-powershell#20849]
### Description

In the Azure CLI command `az aks create` there's a parameter for `--outbound-type` ([ref](https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create)) with optional values of `loadBalancer, managedNATGateway, userAssignedNATGateway, userDefinedRouting`.  This maps to the `outboundType` parameter for the REST API ([ref](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update?tabs=HTTP#outboundtype)).

Is there an equivalent parameter in `New-AzAksCluster`?  How can a user specify `userDefinedRouting` for a new cluster?

**Comment by isra-fel** [comment]
Thanks for reporting!
@YanaXu Hi, could you check this feature request?

**Comment by Alex-wdy** [comment]
We will arrange for priority development in the next semester. Already tracked this feature.
But if there are still buffers for this semester, I will try to give priority to development.
Please follow the progress on GitHub.

**Comment by Alex-wdy** [comment]
> Thanks @Alex-wdy - will that be tracked here or is there another issue I should sub? Happy to consolidate.

Let's track it here.
