### ISSUE TITLE
Get-AzStorageShare not able to list file share name

### ISSUE THREAD

**Issue by shekaryenagandula** [Azure/azure-powershell#20852]
### Description

**I have tried fetching the Azure Storage File share names in PowerShell but permission denied when public network access disabled.
But same visible through Azure portal and also can able to access using REST API even public network access disabled.
Seems like we should remove the restrictions on listing the file share names and just add restrictions for accessing the file share contents.
Please don't ask for code as it's in production and I don't have permission to copy.**

### Issue script & Debug output

```PowerShell
NA
```

### Environment data

```PowerShell
PS C:\Users\yenag> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Through Azure Runbook as well.
```

### Error output

```PowerShell
Access denied error.
```

**Comment by blueww** [comment]
@shekaryenagandula

For Get-AzStorageShare, this cmdlets runs from dataplane, and should fail when the account has public network access disabled, and you run it from a client machine not in private link.

However, as I know, portal might use the management plane rest API to list share, which should not be limited for public network access setting of the account.
In this case, Powershell also has the management plane cmdlet to list file share, please try [Get-AzRmStorageShare](https://learn.microsoft.com/en-us/powershell/module/az.storage/get-azrmstorageshare?view=azps-9.3.0) cmdlet.

**Comment by navba-MSFT** [comment]
@shekaryenagandula Please let us know if you had a chance to try with the [Get-AzRmStorageShare](https://learn.microsoft.com/en-us/powershell/module/az.storage/get-azrmstorageshare?view=azps-9.3.0) cmdlet. Awaiting your reply.
