### ISSUE TITLE
[Doc]: ContainerInsatnce Changelog.md is getting deleted after running autorest

### ISSUE THREAD

**Issue by diyellap** [Azure/azure-powershell#20862]
### Description

Hi,

After updating ReadMe.md with latest swagger version and executing autorest, ChangeLog.md and a few other folders and files are getting deleted for ContainerInsatnce module:

 deleted: help/*
 deleted:    Changelog.md
 deleted:    ContainerInstance.sln
 deleted:    Properties/AssemblyInfo.cs
 deleted:    generate-info.json

Is this the expected behavior?

**Comment by isra-fel** [comment]
Hi @diyellap , from what you said I guess you are working on the main branch. You should use `generation` branch when developing autorest-based modules - you'll find those files do not exist on that branch.
You can also refer to [Guidance for Azure PowerShell development using code generator](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/onboarding/azurepowershell/dev_guidance_codegen)
