### ISSUE TITLE
Issue with resource group being fetched when the resource group name is same across subscriptions.

### ISSUE THREAD

**Issue by one-harsh** [Azure/azure-powershell#2086]
When there are multiple subscriptions under an account and there is a resource group whose resource group name is same across these, no matter what the default or current subscription is, in Azure Powershell, the resource group fetched on `Get-AzureRMResourceGroup` is always from the first subscription fetched by `Get-AzureSubscription`.

**Comment by ravbhatnagar** [comment]
Which version of PS are you currently on? Can you run Get-Module or Get-InstalledModule to verify the version of AzureRm.Profile and AzureRm.Resources?

**Comment by ravbhatnagar** [comment]
@one-harsh - You will have to run Select-AzureRmSubscription and provide a subscriptionId. All the subsequent cmdlets you run will target that subscription.

**Comment by ravbhatnagar** [comment]
@one-harsh - Are you still running into the above issue?

**Comment by ravbhatnagar** [comment]
Closing. Please let us know if this is still an issue and I will re-open this one.
