### ISSUE TITLE
New-AzCosmosDBGremlinDatabaseToRestore command not found error

### ISSUE THREAD

**Issue by kevsers** [Azure/azure-powershell#20873]
### Description

I am trying to run the az cli command for restoring a graph db account using the below command line as suggested in the document [here](https://learn.microsoft.com/en-us/azure/cosmos-db/restore-account-continuous-backup#trigger-restore-ps) Example 3:
```
$datatabaseToRestore1 = New-AzCosmosDBGremlinDatabaseToRestore  -DatabaseName "MyDB1" -GraphName "graph1", "graph2"  
$datatabaseToRestore2 = New-AzCosmosDBGremlinDatabaseToRestore  -DatabaseName "MyDB2"

Restore-AzCosmosDBAccount `
  -TargetResourceGroupName "MyRG" `
  -TargetDatabaseAccountName "Pitracct" `
  -SourceDatabaseAccountName "SourceGremlin" `
  -RestoreTimestampInUtc "2022-04-05T22:06:00" `
  -DatabasesToRestore $datatabaseToRestore1, $datatabaseToRestore2 `
  -Location "West US"
```

I have the powershell version 7.3 and installed Az module.. 

Getting the following error:
```
New-AzCosmosDBGremlinDatabaseToRestore: The term 'New-AzCosmosDBGremlinDatabaseToRestore' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
Is there another module that needs to be installed or any additional information why the command is not found?

**Comment by navba-MSFT** [comment]
@kevsers Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@kevsers While I ran the `New-AzCosmosDBGremlinDatabaseToRestore `cmdlet it said below:

WARNING: New-AzCosmosDBGremlinDatabaseToRestore is not found. The most similar Azure PowerShell command is:

[New-AzCosmosDBDatabaseToRestore](https://learn.microsoft.com/en-us/powershell/module/az.cosmosdb/new-azcosmosdbdatabasetorestore?view=azps-9.4.0)

I am checking this further, I will provide you more information once I gather the details.

**Comment by navba-MSFT** [comment]
@kevsers You need to check if you have this preview version in the list of installed versions:

>**(Get-Module -ListAvailable | Where-Object{ $_.Name -eq 'Az.CosmosDB' }) ` | Select Version, Name, Author, PowerShellVersion**  | Format-List;
 
```
Version           : 1.6.0
Name              : Az.CosmosDB
Author            : Microsoft Corporation
```

If you don't have this, you should install it using below:

Installing the preview version: ([https://www.powershellgallery.com/packages/Az.CosmosDB/1.6.0-preview](https://www.powershellgallery.com/packages/Az.CosmosDB/1.6.0-preview)

> **Install-Module -Name Az.CosmosDB -RequiredVersion 1.6.0-preview -AllowPrerelease**


After installing this version, I tried the command you had shared and it works. Please let me know if you are unable to perform  these operations after installing the above powershell preview version.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/57353862/218010512-d2bdc00f-983d-47f9-ae0a-d41da9b71bad.png">

**Comment by navba-MSFT** [comment]
@kevsers I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@kevsers The action is currently pending on you to try the above action plan. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
