### ISSUE TITLE
Disconnect-AzAccount AccountNotFound error

### ISSUE THREAD

**Issue by MarcoJanse** [Azure/azure-powershell#20871]
### Description

When disconnecting from Az PowerShell I get the following error:

```powershell
Disconnect-AzAccount: Status: AccountNotFound
Context: Account with id '(pii)' not found
Tag: 0x1f553780 (error code : 0)
```

I have already tried the following:

```powershell
Get-AzContext
Set-AzContext <required parameters>
Clear-AzContext
Clear-AzContext -Force
Clear-AzContext -Scope Process -Force
Clear-AzContext -Scope Current User -Force
```

I have also renamed the .Azure folder in my homedir, so it got recreated the next time I connect to Az PowerShell, but the error remains.

I get the error with multiple subscriptions/tenants, but not on all the subscriptions/tenants. 

### Issue script & Debug output

```PowerShell
DEBUG: 17:18:51 - DisconnectAzureRmAccountCommand begin processing with ParameterSet 'ContextName'.
DEBUG: 17:18:51 - using account id '<username>.<subdomain>.onmicrosoft.com'...
DEBUG: 17:18:51 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 17:18:51 - Autosave setting from startup session: 'CurrentUser'
DEBUG: 17:18:51 - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 17:18:51 - Using Autosave scope 'CurrentUser'
DEBUG: 17:18:51 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
Disconnect-AzAccount: Status: AccountNotFound
Context: Account with id '(pii)' not found
Tag: 0x1f553780 (error code : 0)
DEBUG: 17:18:51 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.11.2; CommandName: Disconnect-AzAccount; PSVersion: 7.3.2; IsSuccess: False; Duration: 00:00:00.0993741; Exception: Status: AccountNotFound
Context: Account with id '(pii)' not found
Tag: 0x1f553780 (error code : 0);
DEBUG: 17:18:51 - DisconnectAzureRmAccountCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.11.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
```

### Error output

```PowerShell
DEBUG: 17:41:16 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 17:41:16 - using account id 'janse_3fifty@klikonderwijs.onmicrosoft.com'...
DEBUG: 17:41:16 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 3

Message        : Status: AccountNotFound
                 Context: Account with id '(pii)' not found
                 Tag: 0x1f553780 (error code : 0)
StackTrace     :    at Microsoft.Identity.Client.Broker.RuntimeBroker.RemoveAccountAsync(ApplicationConfiguration appConfig, IAccount account)
                    at Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync(IAccount account, CancellationToken cancellationToken)
                    at Microsoft.Identity.Client.ClientApplicationBase.RemoveAsync(IAccount account)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.RemoveFromTokenCache(IAzureAccount account)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.RemoveUser(IAzureAccount account, IAzureTokenCache tokenCache)
                    at Microsoft.Azure.Commands.Profile.DisconnectAzureRmAccountCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Identity.Client.MsalServiceException
InvocationInfo : {Disconnect-AzAccount}
Line           : disconnect-azaccount
Position       : At line:1 char:1
                 + disconnect-azaccount
                 + ~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3



DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.11.2; CommandName: Resolve-AzError; PSVersion: 7.3.2; IsSuccess: True; Duration: 00:00:00.0286917
DEBUG: 17:41:16 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 17:41:16 - ResolveError end processing.
```

**Comment by isra-fel** [comment]
Hi @MarcoJanse thanks for reporting! I will investigate this issue and keep the issue updated.

My guess is this is related to #20824 . Root cause could be us relying on an unstable fallback behavior of WAM.

**Comment by richardzaat** [comment]
We are facing the same issue.

**Comment by tedvanhaalen** [comment]
Hi @isra-fel,

Any news on this? As @richardzaat mentions we are facing the same issue, also on hosted Microsoft agents. It worked fine with Az.Accounts v2.10.4, but I can confirm it started failing from Az.Accounts v2.11.0 onwards.

**Comment by isra-fel** [comment]
Thanks for the info @tedvanhallen 
Though I haven't been able to reproduce this issue, the fix seemed clear - when WAM isn't enabled, we should call the WAM-free API instead of relying on the fallback.

I've submitted a pull request to do this. I will also share an engineering build tomorrow.

**Comment by isra-fel** [comment]
Hi all, we've made an engineering build for the fix. I verified that it wouldn't call WAM-related APIs when the config was disabled, which should be able to fix the issue for you, but since I wasn't able to reproduce, could you kindly give it a test? Thanks.

Download the package from: https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.11.2.nupkg
You can either put it in a local repository and install it from there, or use our utility module `Az.Tools.Installer`:

```powershell
Install-Module -Name Az.Tools.Installer -Repository PSGallery
Install-AzModule -path https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.11.2.nupkg -RemovePrevious
```

**Comment by tedvanhaalen** [comment]
@isra-fel I have tested the fix and can confirm that it has at least resolved the issue on my local machine. Thanks!

Any idea when we can expect this fix on the hosted agents?

**Comment by MarcoJanse** [comment]
I too can confirm that installing az.accounts 2.11.2 seems to have resolved the issue on my machine as well. I have tried connecting to different Azure tenants and haven't been able to reproduce the errors anymore.

**Comment by isra-fel** [comment]
Thanks for verifying! We are waiting for the response of another similar issue. And we are targeting the upcoming milestone on March 7th.

**Comment by atringle** [comment]
FYI still seeing the error occur in both Windows PowerShell and PowerShell 7

To reproduce I simple started up my windows sandbox and than 
- installed latest Az module (confirmed it had Az.Accounts 2.11.2)
- Connect-AzAccount
- Completed Sign in
- Disconnect-AzAccount
- Hit Error

Running Disconnect-AzAccount a second time work without error.
Note also hit this outside of Windows Sandbox so not a Sandbox issue.

```
Disconnect-AzAccount: Status: AccountNotFound
Context: Account with id '(pii)' not found
```

**Comment by isra-fel** [comment]
Thanks for the info @atringle
Unfortunately we had to delay the official release (which will fix the issue) for a few days. ETA end of week. Sorry for the inconvenience.

**Comment by tedvanhaalen** [comment]
@isra-fel There are new versions available now (2.12.0 and 2.12.1) which resolve the issue. When can we expect these to be available on Microsoft hosted agents?

**Comment by isra-fel** [comment]
@tedvanhaalen yes the fix is published. By "Microsoft hosted agents" do you mean Azure DevOps pipeline or GitHub action?

**Comment by tedvanhaalen** [comment]
@isra-fel We run an Azure DevOps pipeline on Microsoft hosted agents (windows-latest image). I tried it again just now and it shows the same error. These Microsoft hosted Windows agents still use the older version of Az.Accounts (2.11.2).
