### ISSUE TITLE
New-AzFrontDoorWafPolicy Tags 

### ISSUE THREAD

**Issue by RackPhilO** [Azure/azure-powershell#20870]
### Description of the new feature

Allow the passing of tags when creating a new Azure Front Door Waf Policy resource , tags can be added in the portal but not via powershell .

### Proposed implementation details (optional)

New-AzFrontDoorWafPolicy -Tags @{key="value"}

**Comment by navba-MSFT** [comment]
@RackPhilO Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@RackPhilO  The [New-AzTag ](https://learn.microsoft.com/en-us/powershell/module/az.resources/new-aztag?view=azps-9.4.0)command replaces all existing tags on the resource, while the [Update-AzTag](https://learn.microsoft.com/en-us/powershell/module/az.resources/update-aztag?view=azps-9.4.0) command allows you to add or update tags on a resource that already has tags. Could you please check if this helps ?

**Comment by RackPhilO** [comment]
Thankyou for the suggestion, yes I agree you can add tags using the new-aztag cmdlet . My faeture-request was orientated around not having to use a secondary cmdlet to add tags and to have this as a native function of the New-AzFrontDoorWafPolicy  . This would align to other cmdlets which you would run at a similar time eg New-AzFrontDoorCdnProfile OR perhaps the resource group which would be required to house them in etc .

**Comment by RackPhilO** [comment]
Thankyou
