### ISSUE TITLE
Remove-AzAutomationRunbook fails because the runbook name does not match the expected validation pattern

### ISSUE THREAD

**Issue by MrDRamos** [Azure/azure-powershell#20885]
### Description

Remove-AzAutomationRunbook fails because the runbook name does not match the expected validation pattern

Upgraded from version 1.8.0 to 1.9.0 and I now get these errors:
Remove-AzAutomationRunbook : 'runbookName' does not match expected pattern '^[a-zA-Z]*-*[a-zA-Z0-9]*$'.
Just realized that version 1.9.1 was released a few hours ago. I tested v 1.9.1 and it also fails.

I have several runbooks that don't have a hyphen in the name. 

### Issue script & Debug output

```PowerShell
# Remove all runbooks
$RunbookS = $AutomationAccount | Get-AzAutomationRunbook
$RunbookS | Remove-AzAutomationRunbook -Force
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.2364
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2364
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name  
---------- -------    ----  
Script     1.9.1      Az.Automation
Script     1.8.0      Az.Automation
```

**Comment by navba-MSFT** [comment]
@MrDRamos Thanks for reaching out to us and reporting this issue. I see that you have both 1.8.0 and 1.9.1 version of `Az.Automation` module loaded in your PS session.  Could you please remove the` Az.Automation` module completely by following the below action plan and install the most recent version again ?

- Remove-Module -Name Az.Automation
- Get-module -name az.automation    #  run this command and confirm if the older version are still loaded
- unInstall-Module -Name Az.Automation -RequiredVersion 1.8.0 -force
- unInstall-Module -Name Az.Automation -RequiredVersion 1.9.1 -force
 
- Install-Module -Name Az.Automation -RequiredVersion 1.9.1 
- Import-Module -Name Az.Automation

- Get-module -name az.automation    #  run this command and confirm if the newer version (1.9.1) is loaded and then test your command.

**Comment by MrDRamos** [comment]
As requested, I uninstalled all versions if Az.Automation. Starteded a fresh powershell session, installed and imported v1.9.1 and ran my test script again -> Get the same error message:
PS D:\Builds\olcportal\tools>
Remove-AzRmAutomationRunbook : 'runbookName' does not match expected pattern '^[a-zA-Z][a-zA-Z-_0-9]*$'.
At D:\Builds\olcportal\Modules\iem-automation\tools\API_AutomationRunbook.ps1:360 char:29
+ ...               $RunbookS | Remove-AzRmAutomationRunbook -Force #-Confi ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Remove-AzAutomationRunbook], ValidationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.RemoveAzureAutomationRunbook
 
PS D:\Builds\olcportal\tools> Get-Module -name Az.Automation

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.9.1      Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAutomationDscNodeReportContent, Export-AzAutomationRunbook, Get-AzAutomationAcco... 


PS D:\Builds\olcportal\tools>

**Comment by navba-MSFT** [comment]
@MrDRamos Thanks for getting back. I will look into this and get back to you.

**Comment by isra-fel** [comment]
CC @BethanyZhou

**Comment by navba-MSFT** [comment]
@MrDRamos I was able to reproduce this issue at my end. The newer version (1.9.1) of Az.Automation module has fixed the issue for any newly created runbooks. However the runbooks that are created with the older versions ( 1.8 and below) modules are having issues. It seems like a backward compatibility issue.

**Comment by navba-MSFT** [comment]
@MrDRamos I have heard back from the Product Group for the above error. The runbook names which were created using the older version (1.8 and below) AzAutomation module and those which are not compliant as per [its naming convention](https://learn.microsoft.com/en-us/azure/automation/manage-runbooks#:~:text=The%20runbook%20name%20must%20start%20with%20a%20letter%20and%20can%20contain%20letters%2C%20numbers%2C%20underscores%2C%20and%20dashes) is expected to face this issue.

The Az module 1.9.1 has hardened the runbook name convention as per documentation. The recommendation for customers with Runbook name not as per its naming convention is expected to use previous version and create the runbook with compliant name format.
