### ISSUE TITLE
installation duplicates entries in PSModulePath (which breaks DSC)

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-powershell#2090]
Installing the cmdlets appends a duplicate entry for one of the paths in the PSModulePath.  When duplicates are present DSC cannot find modules in that path and the duped entry is the default location for DSC modules.  For example, before install I have:

C:\Users\bmoore\Documents\WindowsPowerShell\Modules;**C:\Program Files\WindowsPowerShell\Modules**;C:\Windows\system32\WindowsPowerShell\v1.0\Modules

And after:

C:\Users\bmoore\Documents\WindowsPowerShell\Modules;**C:\Program Files\WindowsPowerShell\Modules**;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;
**C:\Program Files\WindowsPowerShell\Modules\;**
C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\;C:\Program Files (x86)\
Microsoft SDKs\Azure\PowerShell\Storage\

**Comment by alexandair** [comment]
It's hard to believe we still have an issue with PSModulePath. :-1: 
One more reason for WebPI and .msi to install to proper paths (like Install-Module) instead of modifying PSModulePath.

**Comment by markcowl** [comment]
@bmoore-msft @alexandair moving the installation directory so that PSModulePath updates is not required is in plan, and being tracked in #685

 Closing this issue as a duplicate
