### ISSUE TITLE
[Doc]: https://learn.microsoft.com/en-us/powershell/module/az.network/resize-azvirtualnetworkgateway?view=azps-9.4.0

### ISSUE THREAD

**Issue by cchapin-ms** [Azure/azure-powershell#20936]
### Description

The document on Reset-AzVirtualNetworkGateway, the command in Example 1 does not have the proper syntax for the Get-AzVirtualNetworkGateway command. That command requires the -ResourceGroup parameter and it is not shown in the example.

**Comment by isra-fel** [comment]
Thank you @cchapin-ms for reporting the issue :)

**Comment by SaurabhSharma-MSFT** [comment]
@cchapin-ms The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
