### ISSUE TITLE
Should we have AzureRM* aliases for data plane cmdlets?

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-powershell#2100]
Where are the commandlets related to Storage containers?

Where is an example of "here's how to upload a blob to a ARM storage container"?

**Comment by colemickens** [comment]
Just saw this: https://github.com/Azure/azure-powershell/issues/1908

But that's not really sufficient. Why do I have New-AzureRmStorageAccount but not New-AzureRMStorageContainer available in my current PS session?

**Comment by colemickens** [comment]
Moreover,

```
Import-Module AzureRM.Storage

New-AzureRmStorageContainer

New-AzureRmStorageContainer : The term 'New-AzureRmStorageContainer' is not recognized.....

**Comment by colemickens** [comment]
CC @alexandair

**Comment by colemickens** [comment]
https://blogs.msdn.microsoft.com/cloud_solution_architect/2016/01/04/fun-with-azure-storage-and-powershell/

Not cool, discoverable or documented as far as I can tell.

**Comment by markcowl** [comment]
@colemickens Documentation in  general is an issue that we are working to resolve.  The difference between Management plane and data plane cmdlets was covered in the v1.0 blog post, but that is just a blog post and is not a substitute for official documentation.

Note that, the storage data plane cmdlets (like ```Get-AzureRMStorageAccount```) actually have a Context property which contains a StorageContext.  You can use this in storage data plane cmdlets, and piping scenarios like
```
Get-AzureRmStorageAccount -Name accountname -ResourceGroupName myrg | New-AzureStorageContainer -Name mycontainer
```

**Comment by markcowl** [comment]
@colemickens Just to be clear, the idea is that data plane cmdlets use the Azure prefix and Management plane cmdlets use the AzureRm prefix.  It may *not* be clear that creating a container is a management plane cmdlet.  IMO, this is part of the discoverability issue.  It is important that the Storage data plane cmdlets have their own module, so they can be used with both RDFE and ARM cmdlets, but they *could* be a dependency of the AzureRM.Storage cmdlets, so that when you install those cmdlets, they are automatically loaded.  Do you think this would help with the discoverability issue?

**Comment by alexandair** [comment]
@markcowl Would aliases help with discoverability? For example, if you introduce New-AzureRmStorageContainer alias, users will get what they expect and you will still have New-AzureStorageContainer in Azure.Storage module (used by both RDFE and ARM cmdlets).

**Comment by colemickens** [comment]
@markcowl That makes some sense to me, and I sort of inferred as much after getting it working, but it was still confusing, even as someone who sits 30 feet away from the ARM team.

RE @alexandair's suggestion, I don't know if aliases are the right way to go about it, but it would have helped in my case. Even if it immediately errored and pointed me to an external documentation page, that's better than being in a sort of limbo state.

**Comment by markcowl** [comment]
@colemickens @alexandair Will discuss this with the team.  To me, having aliases to AzureRM for all the Azure* data plane cmdlets makes sense, as it allows the user to use whichever prefix makes the most sense to them.  I have to admit that I often type New-AzureRm before tab completion kicks in.

**Comment by twitchax** [comment]
@markcowl, I need some context here.  Should I rename this issue to "There should be aliases for ASM cmdlets which begin with 'AzureRm'"?

**Comment by maddieclayton** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/issues/3810
