### ISSUE TITLE
New-AzureRmADApplication does not support setting ReplyUrls 

### ISSUE THREAD

**Issue by aizumoff** [Azure/azure-powershell#2107]
I saw in https://github.com/Azure/azure-powershell/pull/1564/files PR that new properties: IdentifierUris , ReplyUrls  were added, but for New-AzureRmADApplication cmdlet only IdentifierUris option was added, not ReplyUrls  

We're trying to automate ADApp creation and lack of ReplyUrls forces as to do that manually. 
But it's very error prone.

And is it possible to set Policies for AdApp via Cmdlet as well?

**Comment by markcowl** [comment]
@shuagarw Any chance of adding these properties to the cmdlet?

**Comment by shuagarw** [comment]
@aizumoff Yes. We have it in our task list. No concrete ETA yet.

**Comment by alecor191** [comment]
Hi @shuagarw. Do you have an update on when ReplyUrls will be added to New-AzureRmADApplication? I'm in the same situation as @aizumoff.

**Comment by wangzq** [comment]
@aizumoff @alecor191 I have some PowerShell script cmdlets to help in this regard, I can cleanup and release them if you are interested.

**Comment by aizumoff** [comment]
@wangzq Please share - it'll be helpful.

**Comment by wangzq** [comment]
@aizumoff https://github.com/wangzq/Azure-PowerShell-Extensions
Feel free to use issues there for questions/bugs.

**Comment by willemodendaal** [comment]
+1, we need this too.

**Comment by cormacpayne** [comment]
This appears to have been fixed in PR https://github.com/Azure/azure-powershell/pull/2734. Closing.
