### ISSUE TITLE
2 small "bugs/inconsistency" with  Websites / Commands.Websites / Cmdlets / Certificates / NewAzureWebAppSSLBinding.cs 

### ISSUE THREAD

**Issue by mthenot-msft** [Azure/azure-powershell#2109]
- If you look at https://resources.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aname/providers/Microsoft.Web/certificates, one can see that the CertNamePostFixSeparator is a "#" and not a "_" for **Name *_& *_ID** as defined in NewAzureWebAppSSLBinding.cs when the certificate is uploaded via the portal. Shouldn't we be consistent here?
- Again, if a WebApp is in an ASE, the certificate's Name & ID pattern are different when created using the cmdlet compared to created through the portal.

**Comment by markcowl** [comment]
@naveedaz Can you take a look?

**Comment by naveedaz** [comment]
@akurmi  (Powershell cmdlet owner)

**Comment by akurmi** [comment]
This is actually by design so that one can easily find out if the cert was uploaded through PowerShell ('_' in the resource name) or portal ('#' in the resource name). That being said, a certificate uploaded through PowerShell should work fine in the portal and vice versa. Are you facing any issues with this naming convention?

**Comment by mthenot** [comment]
No, I’m not facing issues, was just wondering why the “#” & the “_”.
What about the trailing info though?
It looks like it’s set to “-“ + if(deployed in ASE) {ASE name + “appse”} + trim($location) + webspace
Why is it different?

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
