### ISSUE TITLE
[Doc]: Example 10: Incorrect

### ISSUE THREAD

**Issue by WiseOldHowell** [Azure/azure-powershell#21097]
### Description

[Example 10](https://learn.microsoft.com/en-us/powershell/module/az.storage/set-azstorageaccount?view=azps-9.4.0#example-10-update-a-storage-account-by-enable-azure-files-aad-ds-authentication-and-set-defaultsharepermission) states _StorageFileDataSmbShareOwner_, but this looks to be incorrect. 

Correct options appear to be:

- None
- StorageFileDataSmbShareContributor
- StorageFileDataSmbShareElevatedContributor
- StorageFileDataSmbShareReader

**Comment by isra-fel** [comment]
Thanks for your feedback :)
