### ISSUE TITLE
[Doc]:  Get-AzStorageSyncGroup 

### ISSUE THREAD

**Issue by jsimsmsft** [Azure/azure-powershell#21100]
### Description

typo in 'example 1' 
includes unrelated cmdlet "New-AzStorageSyncCloudEndpoint"

https://learn.microsoft.com/en-us/powershell/module/az.storagesync/get-azstoragesyncgroup?view=azps-9.4.0&viewFallbackFrom=azps-9.2.0

**Comment by navba-MSFT** [comment]
@jsimsmsft Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@jsimsmsft The above PR has been filed to fix this. It is currently under review.
