### ISSUE TITLE
[Feature]: Can we have equivalent azure powershell cmdlets for az acr token related CLI commands?

### ISSUE THREAD

**Issue by patpishiva** [Azure/azure-powershell#21111]
### Description of the new feature

For the below mentioned az acr token related azure cli commands, we are not able to find out the corresponding azure powershell commands
https://learn.microsoft.com/en-us/cli/azure/acr/token?view=azure-cli-latest

Can we know if the work is in progress?

**Comment by isra-fel** [comment]
Thanks for sharing the feedback. We'll discuss and get back to you shortly.

**Comment by isra-fel** [comment]
Thanks for asking. We are working on it and the current target is late May this year.
