### ISSUE TITLE
Get-AzureRmRecoveryServicesVault has spelling error in returned results

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-powershell#2113]
Get-AzureRmRecoveryServicesVault has spelling error in returned results

the cmdlet returns object ResouceGroupName instead of ResourceGroupName

**Comment by lwsrbrts** [comment]
Same with Get-AzureRmSiteRecoveryVaultSettings

**Comment by sriramvu** [comment]
Thanks for letting us know.
* Get-AzureRmRecoveryServicesVault issue is taken care in https://github.com/RecoveryServicesOneSDK/azure-powershell/commit/d31f1791b259d63435c5560ba76d48f8148c54ee
*  Get-AzureRmSiteRecoveryVaultSettings issue is taken care in https://github.com/Azure/azure-powershell/pull/2844/commits/d95cff0ae4ad6dea4e1c53119aee0ccb951f9349
