### ISSUE TITLE
[get-AzurermNetworkInterface] on a ScaleSet fails, cannot add a ScaleSet at Backendpool on a LB

### ISSUE THREAD

**Issue by theobolo** [Azure/azure-powershell#2114]
Hello guys,

I'm trying to work with a ScaleSet and the Azure Loadbalancer.
I deployed a cluster with one Master and a ScaleSet for the workers (kubernetes).
On my deployment all the ScaleSet interfaces share the same name : kube-20160413-121210-node-nic

so i tried to work with -VirtualMachineScaleSetName to add the Scale set's NIC to the backendpool.

When i try to do : 

```
$lb= get-azurermloadbalancer –name kube-elb-20160413-121210 -resourcegroupname kube-20160413-121210

$nic=get-azurermnetworkinterface -VirtualMachineScaleSetName kube-20160413-121210-vm-node-scaleset -ResourceGroupName kube-20160413-121210

$backend=Get-AzureRmLoadBalancerBackendAddressPoolConfig -name NRPbackendpool  -LoadBalancer $lb

$nic.IpConfigurations[0].LoadBalancerBackendAddressPools=$backend

Set-AzureRmNetworkInterface -NetworkInterface $nic
```

it's not working 

![sans titre](https://cloud.githubusercontent.com/assets/7281773/14639083/eb61fee0-063a-11e6-9749-24b7d48edcd8.png)

Any ideas ?

**Comment by theobolo** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/7281773/14640040/e3442602-063f-11e6-9692-a36329213522.png)

How can i get the NICs separately ?

**Comment by markcowl** [comment]
@DeepakRajendranMsft Can you take a look?

**Comment by DeepakRajendranMsft** [comment]
Hi @theobolo,

To get a standalone nic that was generated using a scaleset, you would have to use "Get-AzureRmNetworkInterface -VirtualMachineScaleSetName -VirtualMachineIndex -Name -ResourceGroupName"

However, even if you get the NIC, the service does not allow you to modify a NIC that was generated using a VirtualMachineScaleSet. So you cannot add a backendaddress pool to just one of the nics of a scaleset. To add a backend addresspool, you would have to add it to all nics of the scaleset using the PUT VMScaleSet API.

Thanks,
Deepak.

**Comment by theobolo** [comment]
@DeepakRajendranMsft thx, it's a little bit more clear for me.

BTW i'm not a big expert of the Azure API, do you have an example or something to add all the VMScaleSet NICs using the PUT  VMScaleSet API ? 

I also tried to put my Loadbalancer directly inside my Json ARM Template and the result was a "Timeout Deploiement" for the ScaleSet.

Théo

**Comment by markjbrown** [comment]
@theobolo Check out the example here for how to include the LB, https://msdn.microsoft.com/en-us/library/mt697562.aspx

Closing. Please reopen if needed.
