### ISSUE TITLE
Stuck on Get-AzDataFactoryV2PipelineRun.

### ISSUE THREAD

**Issue by ka-yanaoka** [Azure/azure-powershell#21166]
### Description

We are running the data factory pipeline in a Powershell script.

After running the pipeline with Invoke-AzDataFactoryV2Pipeline
Get-AzDataFactoryV2PipelineRun is executed every 30 rows to monitor status.
The part of the process executing Get-AzDataFactoryV2PipelineRun is as follows
![image](https://user-images.githubusercontent.com/119591084/224171473-88dab461-ef6e-4048-8819-3b61f90cb4c2.png)

The process got stuck on Get-AzDataFactoryV2PipelineRun twice in February 2023.
The behavior is that Get-AzDataFactoryV2PipelineRun is executed several times, but the powershell script gets stuck before the pipeline is finished.

Checking the Powershell dump log, it looks like the process is stuck on Get-AzDataFactoryV2PipelineRun.
![image](https://user-images.githubusercontent.com/119591084/224171699-253b2c2a-119f-4fcc-9762-f88dac19e9f5.png)

Is there a way to investigate?
Is there any workaround for the stuck?

### Issue script & Debug output

```PowerShell
while ($True) {
    $run = Get-AzDataFactoryV2PipelineRun -ResourceGroupName $RGName -DataFactoryName $DFName -PipelineRunId $runId

    if ($run) {
        if (($run.Status -ne 'InProgress') -and ($run.Status -ne 'Queued')) {
            Write-Output "Pipeline run finished. The status is: " $run.Status
            $run
            break
        }
        Write-Output  "Pipeline is running...status: InProgress"
    }

    Start-Sleep -Seconds $WaitTime
}
```

### Environment data

```PowerShell
PS C:\Windows\system32> $PSVersionTable

Name                           Value                                                                                                                
----                           -----                                                                                                                
PSVersion                      5.1.14393.5127                                                                                                       
PSEdition                      Desktop                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                              
BuildVersion                   10.0.14393.5127                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                      
WSManStackVersion              3.0                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                  
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS C:\Windows\system32> Get-Module

ModuleType Version    Name                                ExportedCommands                                                                          
---------- -------    ----                                ----------------                                                                          
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                       
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
```

### Error output

```PowerShell
No Output produced.
```

**Comment by navba-MSFT** [comment]
Adding Service team to look into this. 

 @zhangyd2015, @Frey-Wang, @Jingshu923: Could you please assist on this ? Thanks in advance.

**Comment by Frey-Wang** [comment]
By stuck, does it mean that it never times out? Could you please repro the issue with ` -debug` tag?

**Comment by Frey-Wang** [comment]
Hi @ka-yanaoka, please add debug tag after the powershell command, which means `Get-AzDataFactoryV2PipelineRun ...... -debug`. Please run the command separately so that you can add tags to the one that timeout and retrieve the debug information.

**Comment by o-o00o-o** [comment]
we have seen the same problem. We have code that copes with a timeout as that sometimes does happen from this function but we have also seen the sitution where no timeout happens and it just never returns which blocks our script.

It isn't possible for us to run Debug information as it doesn't happen often enough so would unreasonably fill our logs.

Suggest someone analyses the code for wherever there is an infinite timeout set or other possibility for this to happen.

In the meantime we are going to have to try to wrap this in a powershell job with all the pain that this has 👎
