### ISSUE TITLE
Ubuntu 22.04 Alias Points To Incorrect Offer

### ISSUE THREAD

**Issue by j5awry** [Azure/azure-powershell#21176]
### Description

Ubuntu 22.04 Compute Alias points to: 

0001-com-ubuntu-pro-advanced-sla-ca

This offer won't even work, because it is _private_. That means that it won't even launch a VM, so it's fundamentally broken right now.

this is a premium offer with additional costs. The expected offer is an infrastructure-cost only offer (free for the OS). You can find a list of the offers for Canonical published Ubuntu here:

https://canonical-public-cloud.readthedocs-hosted.com/en/latest/azure/azure-how-to/find-ubuntu-images/

the correct URN is:

Canonical:0001-com-ubuntu-server-jammy:22_04-lts-gen2:latest

### Issue script & Debug output

```PowerShell
I don't need to run powershell, i just saw the PR. I work for Canonical, i know what the offer is :)
```

### Environment data

```PowerShell
N/A
```

### Module versions

```PowerShell
AZ Compute -- this specific change in a PR

https://github.com/Azure/azure-powershell/pull/21012/files#diff-2b55a7c7b9a159041f1adb1ba967b55a8840ddc6e88df099b70a50c17331f6e2R57
```

**Comment by Drewm3** [comment]
@Sandido, could you please take a look at this issue?

**Comment by Sandido** [comment]
Fix is out for review.
