### ISSUE TITLE
Get-AzureRmResourceProvider -ProviderNamespace parameter should be [string[]] instead of [string]

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2121]
![image](https://cloud.githubusercontent.com/assets/466713/14683411/d818f4b2-06e7-11e6-9048-5c5cea2471b7.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 I like this suggestion.  @vivsriaus thoughts?

**Comment by cormacpayne** [comment]
This is fixed in the `resources-improvements` branch

**Comment by cormacpayne** [comment]
The fix for this can be found in PR https://github.com/Azure/azure-powershell/pull/6008

**Comment by markcowl** [comment]
Fixed
