### ISSUE TITLE
[Doc]: https://learn.microsoft.com/en-us/powershell/module/az.storage/get-azstorageshare?view=azps-9.5.0

### ISSUE THREAD

**Issue by kje8c** [Azure/azure-powershell#21210]
### Description

The examples are missing context and useless on their own.  You cannot type any of them in to PowerShell on their own and have them work.  That makes them very poor examples.

At least 3 things have to happen before you run these examples:

1. Connect-AzAccount [-Environment AzureUSGovernment]
2. Set-AzContext -SubscriptionName <subscription-name>
3. Get-AzStorageAccount     # Give a list of storage accounts
4. ??? cannot figure this out

Then maybe:
Get-AzStorageShare
will list the storage shares for a given Storage Account.

What I want to do is list all storage shares in a Subscription.  This should not be hard, but the API seems to be exceedingly stateful and the error messages given by the API include broken links.

**Comment by blueww** [comment]
@kje8c 

"get-azstorageshare" can list shares in a storage account, or get a single share in a storage account.

The cmdlet will need a Storage Context, which can set by:
1. Create a storage context object with "New-AzStorageContext" and run "get-azstorageshare" parameter "-Context" whose value is the created context object.
2. Run Set-AzCurrentStorageAccount to set a default storage context. 

However, "get-azstorageshare" works on a single storage account. There are no existing storage rest API can list all shares in all storage account in a subscription. You need to list one account after another.
If you want to list all storage file shares in all storage account in a subscription, you can write a script with pipeline like following:
```powershell
# Login AD account, one time work.
Connect-AzAccount

# list all storage accounts in a subscription, then list all shares of each storage account.
Get-AzStorageAccount | Get-AzStorageShare
```

**Comment by isra-fel** [comment]
@kje8c thanks for your feedback 👍 
We suppose that authentication (`Connect-AzAccount`) is too general to put into *every* examples. Instead, you might find the following conceptual documents useful to get started:

- [Get started with Azure PowerShell](https://learn.microsoft.com/en-us/powershell/azure/get-started-azureps?view=azps-9.5.0)
- [Sign in with Azure PowerShell](https://learn.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-9.5.0)
