### ISSUE TITLE
`Get-AzResourceGroup -Name 'some_name'` ignores `-Location` if specified

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-powershell#21225]
### Description

I excpect `Get-AzResourceGroup -Name '<some_name>'` to respect/search for location if `-Location` is specified. But it does not.

Examples: Following returns my `$RgName` in Norway-East:
* `Get-AzResourceGroup -Name $RgName` => As expected.
* `Get-AzResourceGroup -Name $RgName -Location 'westeurope'` => I expect no results from this query.
* `Get-AzResourceGroup -Name $RgName -Location 'powershell is fun!'` => I expect no results and an error from this query.

Examples: Returns no RGs, because current subscription only have RGs in Norway-East (so seems to work when not specifying exact RG name):
* `Get-AzResourceGroup -Location 'westeurope'`
* `Get-AzResourceGroup -Name '*' -Location 'westeurope'`

### Issue script & Debug output

Too much info I'd have to retract.

Specifying a given name with no wildcards seems to use ARM API "GET" on the specific RG. With no filters (like location)

Specifying no name, or name with wildcard, seems to use ARM API "LIST".

### Environment data

```PowerShell
Name                           Value                                                                                                                                   
----                           -----                                                                                                                                   
PSVersion                      5.1.22621.963                                                                                                                           
PSEdition                      Desktop                                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                 
BuildVersion                   10.0.22621.963                                                                                                                          
CLRVersion                     4.0.30319.42000                                                                                                                         
WSManStackVersion              3.0                                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                                     
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Name         Version
----         -------
Az.Accounts  2.12.1 
Az.Resources 6.5.3
```

### Error output

```PowerShell
No error output.
```

**Comment by isra-fel** [comment]
Thanks for the suggestion 👍 

@Nickcandy please evaluate the impact of this change. Thanks.
