### ISSUE TITLE
Formatting issue with template deployment output

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2123]
As you can see in the screenshot, longer property names on ARM JSON Templates are causing the output from a Resource Group deployment to get formatted incorrectly.

![image](https://cloud.githubusercontent.com/assets/466713/14685040/f6664cbe-06ef-11e6-855c-6f5393951d8d.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 Do you think this would be better in a list format?

**Comment by pcgeek86** [comment]
@markcowl Hmmm, not entirely sure what you're proposing. Do you have an example?

**Comment by markcowl** [comment]
@pcgeek86 I'm just trying to get at what the preference would be.  I wasn't sure if this was about the bad spacing or the cut off value for the Uri. If the issue is just that the spacing is incorrect, then disregard.

**Comment by pcgeek86** [comment]
It's just incorrect spacing, that's all. I'm not sure what the best solution would be for this one.

**Comment by markcowl** [comment]
@ravbhatnagar Looks like I neglected to assign this issue to you.  Can you take a look?

**Comment by cormacpayne** [comment]
This has been fixed and will be included in the next release of `Az` (2019-01-29).
