### ISSUE TITLE
Get post-incident report for service incidents

### ISSUE THREAD

**Issue by dferraiolo4** [Azure/azure-powershell#21241]
### Description

Hi, My question is if it's possible to programmatically (PowerShell, Azure Support REST API, etc.) retrieve the information of service health issues in a tenant with attached PIR (post-incident report). thanks!

**Comment by isra-fel** [comment]
Hi thanks for reaching out to us. Let me involve azure support team.

**Comment by navba-MSFT** [comment]
@dferraiolo4 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. You can leverage the Azure Resource Health REST API to get the required details:

[Events - List By Subscription Id ](https://learn.microsoft.com/en-us/rest/api/resourcehealth/2022-05-01/events/list-by-subscription-id?tabs=HTTP)- This Lists service health events in the subscription.

[Impacted Resources - Get ](https://learn.microsoft.com/en-us/rest/api/resourcehealth/2022-05-01/impacted-resources/get?tabs=HTTP) - This Gets the specific impacted resource in the subscription by an event.

[Availability Statuses - Get By Resource](https://learn.microsoft.com/en-us/rest/api/resourcehealth/2022-05-01/availability-statuses/get-by-resource?tabs=HTTP) This Gets current availability status for a single resource

Alternatively, You could also use the [Azure Resource Graph sample queries](https://learn.microsoft.com/en-us/azure/service-health/resource-graph-samples?tabs=azure-cli) for Azure Service Health.

**Comment by navba-MSFT** [comment]
@dferraiolo4 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@dferraiolo4 The action is pending on you to try the [above suggestions](https://github.com/Azure/azure-powershell/issues/21241#issuecomment-1480595421). We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
