### ISSUE TITLE
 New-AzSubscriptionAlias returns intermittent 403 for new MPA subscription

### ISSUE THREAD

**Issue by AndFrantz** [Azure/azure-powershell#21247]
### Description

When I try to invoke this command, it seems to work correctly occasionally, but subsequent requests fail routinely for an extended period of time running against the same line of code. This is for a partner agreement subscription, created under an Azure plan. Authentication is using an AAD registered Service Principal. 

### Issue script & Debug output

```PowerShell
New-AZSubscriptionAlias -AliasName "$accountname" -SubscriptionName "$accountname" -BillingScope "/providers/Microsoft.Billing/billingAccounts/cxxxxxxxxxxxxxxxxxxxxxxxx/customers/$customerid" -Workload Production



New-AZSubscriptionAlias -AliasName "$accountname" -SubscriptionNa …
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Operation returned an invalid status code 'Forbidden'
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:13 PST 2022; root:xnu-8020.240.14~1/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     0.9.0                 Az.Subscription                     {Get-AzSubscriptionAlias, New-AzSubscriptionAlias, Remove-AzSubscriptionAlias, Update-AzSubscr…
```

**Comment by AndFrantz** [comment]
Forgot to add, this is using Service principal Authentication.

**Comment by navba-MSFT** [comment]
@AndFrantz Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Since this is an intermittent issue, next time when you face the same issue, please run `$DebugPreference="Continue"` and then run your `New-AZSubscriptionAlias` above command . Please share the detailed debug output here. 
 
 Note: You can remove the sensitive info from the output before you share it here.

**Comment by navba-MSFT** [comment]
@AndFrantz I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@AndFrantz The action is pending on you to run the `$DebugPreference="Continue"` and then run the` New-AZSubscriptionAlias` command. Once you are ready to resume the work on this, please feel free to reopen this thread. We would be happy to help.
