### ISSUE TITLE
Az.Accounts: ActiveDirectory Authority missing the trailing slash

### ISSUE THREAD

**Issue by marc-lauper** [Azure/azure-powershell#21257]
### Description

We have several deployment scripts that makes use of the "ActiveDirectory Authority" retrieved like this:
`$adAuthority = (Get-AzContext).Environment.ActiveDirectoryAuthority`

Previously the result would contain a trailing slash, and we assume it's here when we use it. But it's missing now.

It has worked properly for years, but started failing in our pipelines on Mars 15th (using Microsoft-hosted Azure DevOps agents). As far as I can see, the only difference is that the "Az.Accounts" module was upgraded from 2.11.2 to 2.12.0/2.12.1.

### Issue script & Debug output

```PowerShell
PS> Get-AzEnvironment 

Name              Resource Manager Url                  ActiveDirectory Authority         Type
----              --------------------                  -------------------------         ----
AzureCloud        https://management.azure.com/         https://login.microsoftonline.com Discovered
AzureUSGovernment https://management.usgovcloudapi.net/ https://login.microsoftonline.us/ Built-in
AzureChinaCloud   https://management.chinacloudapi.cn/  https://login.chinacloudapi.cn/   Built-in
```

As you can see, the `AzureCloud` entry is missing its trailing slash, but the other ones still have it.

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Linux 5.4.0-1104-azure #110~18.04.1-Ubuntu SMP Sat Feb 11 17:41:21 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.0                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzCo…
Script     5.5.0                 Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAddit…
Script     5.5.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertifi…
Script     6.5.3                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec…
Script     5.4.1                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStor…
Script     1.1.0                 Az.Tools.Predictor                  {Disable-AzPredictor, Enable-AzPredictor, Open…
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDevic…
Script     0.9.3                 AzurePSDrive
```

**Comment by isra-fel** [comment]
Thanks for the feedback Marc!
@msJinLei please take a look.

**Comment by msJinLei** [comment]
@marc-lauper

We are sorry that we recently fix an issue of environment initialization that causes the change.

We have an default URI to retrieve environment endpoints from when initialization. But the default URI was invalid for a long time, which you actually get was our built-in endpoints, with a slash.

The version without slash is getting from [ARM metadata](https://management.azure.com/metadata/endpoints?api-version=2022-09-01). Since the server side has removed the slash, we think we shall follow it. Thanks for reporting. We will notify such changes with release next time.

You can set environment variable `ARM_CLOUD_METADATA_URL` to `DISABLED` to still use the built-in endpoints (with a splash) or remove the splash.

Sorry for inconvenience.

**Comment by marc-lauper** [comment]
I have modified the impacted scripts on my side to behave properly regardless of the presence of the trailing slash, but I thought you might want to have a look for backward-compatibility purpose. Thanks for the answer!

**Comment by msJinLei** [comment]
@marc-lauper I close the issue now and you can submit new one if you have further questions.
