### ISSUE TITLE
Bubble up nested deployment errors during validate deployment

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/azure-powershell#2126]

**Comment by bmoore-msft** [comment]
Just wanted to clarify what "nested" means - are you talking about bubbling up errors from deployment resources (nested templates) or the details property of an error response?  (we need both :))

It looks like (at least some) of the details also have details...

`{
  "error": {
    "code": "InvalidTemplateDeployment",
    "message": "The template deployment 'storage' is not valid according to the validation procedure. The tracking id is '49adf810-0385-4c10-889a-577e986d7273'. See inner errors for details. Please see http://aka.ms/arm-deploy for usage details
.",
    "details": [
      {
        "code": "PreflightValidationCheckFailed",
        "message": "Preflight validation failed. Please refer to the details for the specific errors.",
        "details": [
          {
            "code": "AccountNameInvalid",
            "target": "name-too-long-to-pass-validationuasd2ra55mt7k",
            "message": "name-too-long-to-pass-validationuasd2ra55mt7k is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only."
          }
        ]
      }
    ]
  }
}`

**Comment by ravbhatnagar** [comment]
Yes, the details section is where the preflight validation errors typically end up. We are already bubbling those up, if you don't see this for any case, please let us know. 
This was more about the nested templates, which we were not bubbling up.

**Comment by bmoore-msft** [comment]
Ok, glad I asked - that case that I pasted in is not being bubbled up.  We catch the first "details" property but not the second.  Here's the PS output:

New-AzureRmResourceGroupDeployment : Error 1: Code=InvalidTemplateDeployment; Message=The template deployment 'storage' is not valid according to the validation procedure. The tracking id is '49adf810-0385-4c10-889a-577e986d7273'. See inner 
errors for details. Please see http://aka.ms/arm-deploy for usage details.
Error 2: Code=PreflightValidationCheckFailed; Message=Preflight validation failed. Please refer to the details for the specific errors.
At line:1 char:1

Seems like we need error.details[].details

**Comment by ravbhatnagar** [comment]
Fixed in May release
