### ISSUE TITLE
Unable to suppress the confirmation dialogs when running New-AzureRmResourceGroupDeployment with debug switch

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/azure-powershell#2128]
$ConfirmPreference or $DebugPreference don't work

**Comment by bmoore-msft** [comment]
Would like to use the debug output in automation

**Comment by markcowl** [comment]
@ravbhatnagar @TianoMS Please add to appropriate milestone, or close if this is resolved

**Comment by ravbhatnagar** [comment]
@bmoore-msft - This should work if you set $DebugPreference="Continue". It will still log all the debug messages without prompting. Please let me know if this doesn't work for you. CLosing this for now.

**Comment by bmoore-msft** [comment]
No, I still get prompted when adding -debug even with $DebugPreference='Continue'

**Comment by ravbhatnagar** [comment]
You don't need to add -debug when you set this preference. Sorry didn't call it out earlier

**Comment by bmoore-msft** [comment]
ok, that works...
