### ISSUE TITLE
Unabel to enable SFTP using Set-AzStorageAccount using the EnableSFTP parameter

### ISSUE THREAD

**Issue by jlilleby** [Azure/azure-powershell#21306]
### Description

When creating a new storage account using New-AzStorageAccount, i am unable to use the "EnableSFTP" paramter either during first creation and after using the Set-AzStorageAccount. According to the microsoft pages it does not say anything about if the support is removed or 

`Set-AzStorageAccount -ResourceGroupName $dataRgName01 -Name $dataStName -EnableSftp $true -EnableLocalUser $true`

`Set-AzStorageAccount : A parameter cannot be found that matches parameter name 'EnableSftp'.
At line:3 char:21  -EnableSftp $true `

### Issue script & Debug output

```PowerShell
Set-AzStorageAccount -ResourceGroupName $dataRgName01 -Name $dataStName -EnableSftp $true -EnableLocalUser $true

Set-AzStorageAccount : A parameter cannot be found that matches parameter name 
'EnableSftp'.
At line:3 char:21
+                     -EnableSftp $true `
+                     ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-AzStorageAccount], Par 
   ameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands. 
   Management.Storage.SetAzureStorageAccountCommand
```

### Environment data

```PowerShell
Name                           Value                                           
----                           -----                                           
PSVersion                      5.1.19041.2673                                  
PSEdition                      Desktop                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   10.0.19041.2673                                 
CLRVersion                     4.0.30319.42000                                 
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Get-Module Az*

ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Script     2.10.1     Az.Accounts                         {Add-AzEnvironment...
Script     4.20.1     Az.Network                          {Add-AzApplication...
Script     3.6.0      Az.Storage                          {Add-AzRmStorageCo...
```

### Error output

```PowerShell
Set-AzStorageAccount : A parameter cannot be found that matches parameter name 
'EnableSftp'.
At line:3 char:21
+                     -EnableSftp $true `
+                     ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-AzStorageAccount], Par 
   ameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands. 
   Management.Storage.SetAzureStorageAccountCommand
```

**Comment by blueww** [comment]
@jlilleby 

Azure Powershell start to support SFTP from Az.Storage 4.9.0, see https://github.com/Azure/azure-powershell/blob/main/src/Storage/Storage.Management/ChangeLog.md#version-490

As I see, you still use Az.Storage 3.6.0. 
Would you please upgrade to latest Az.Storage (current is [5.4.1](https://www.powershellgallery.com/packages/Az.Storage/5.4.1)), and try again?

**Comment by navba-MSFT** [comment]
@jlilleby Thanks for reaching out to us and reporting this issue. Could you please follow the suggestion provided in the [above comment](https://github.com/Azure/azure-powershell/issues/21306#issuecomment-1482135084) and let us know if that helps. Awaiting your reply.

**Comment by jlilleby** [comment]
Hi, I updated the powershell modules and where able to do a lot more than I could when I Created this ticket so thank you for the assistance.
