### ISSUE TITLE
[Doc][Az.DesktopVirtualization]: Get-AzWvdApplication: 

### ISSUE THREAD

**Issue by JimMoyle** [Azure/azure-powershell#21304]
### Description

The doc lists the type for -DefaultCredential as 'PSobject' which is a description, not a type

It should be Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer

As you can see in the PowerShell help itself

Here is a correct example:

https://learn.microsoft.com/en-gb/powershell/module/az.compute/get-azcomputeresourcesku?view=azps-9.5.0

**Comment by SaurabhSharma-MSFT** [comment]
@JimMoyle The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.

**Comment by SaurabhSharma-MSFT** [comment]
@JimMoyle Please ignore my previous response.  The datatype is correct as PSObject in `Get-AzWvdApplication` cmdlet and it is different in the compute cmdlet which you have referred to.  Please check below screenshot for your reference.
![image](https://user-images.githubusercontent.com/38112130/228323193-4e4dd53b-a971-4880-8dc7-e7a18f82a421.png)

So, I have withdrawn the submitted PR.  Please let me know if you have any other questions.
