### ISSUE TITLE
AzureRM.Network 1.0.8

### ISSUE THREAD

**Issue by mossywell** [Azure/azure-powershell#2132]
New-AzureRmVirtualNetworkGatewayConnection errors with "missing types"

Downgrading back to 1.0.7 fixes the problem.

Apologies, I don't have a screenshot as I close the PS window. However, I got it many times so it is easy to reproduce.

**Comment by markcowl** [comment]
@mossywell Did you install via the msi, did you use ```Install-Module AzureRM.Network```, or did you use ```Install-Module AzureRM```

**Comment by mossywell** [comment]
Originally, Install-Module AzureRM (which installed 1.0.8). Then,
removed AzureRM.Network
with -Force. Finally Install-Module AzureRM.Network -version 1.0.7 -Force

**Comment by markcowl** [comment]
@mossywell What is the version of the AzureRM module on your machine?  The module is being updated on Wednesday, which should clear up the issue.

**Comment by mossywell** [comment]
Originally, Install-Module AzureRM (which installed 1.0.8). Then,
removed AzureRM.Network
with -Force. Finally Install-Module AzureRM.Network -version 1.0.7 -Force

**Comment by markjbrown** [comment]
@mossywell can you let us know if this new build resolved your issue?

Thanks.

**Comment by mossywell** [comment]
Hi gents, yes, I can confirm that using 1.0.9 no longer errors. Cheers for that!

**Comment by markjbrown** [comment]
great thanks
