### ISSUE TITLE
New-AzureRmVirtualNetwork: -AddressPrefix parameter is non-mandatory

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2133]
It should be mandatory

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@depakrajendranmsft can you take a look

**Comment by DeepakRajendranMsft** [comment]
@pcgeek86  Thanks for the feedback. Fixing this now. Will update with PR

**Comment by pcgeek86** [comment]
@DeepakRajendranMsft @markcowl Thanks guys!
