### ISSUE TITLE
New-AzureRmVM error

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2134]
New-AzureRmVm : Parameter 'osDisk.osType' is not allowed.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : ''
At C:\Users.......ps1:248 
char:1
- New-AzureRmVm @NewVm;

**Comment by markcowl** [comment]
@pcgeek86 Can you include the debug stream messages (which include the server traffic)?

**Comment by pcgeek86** [comment]
@markcowl It's due to the fact that I specified the `Windows` switch parameter on `Set-AzureVMOSDisk`, when it wasn't appropriate. I was creating a new VM from an image, instead of creating one from a "specialized" disk, in which case, this parameter isn't necessary or appropriate.

The error handling / messaging needs to be improved on the Compute provider.

**Comment by edgillett** [comment]
Urgh. This one just got me too. Had a -Linux switch on the VMOSDisk too. Same issue.

**Comment by maddieclayton** [comment]
@hyonholee Can you take a look at this issue and see if it still an issue in the current version?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
