### ISSUE TITLE
[Feature]: Get-AzVM should always return ResourceId

### ISSUE THREAD

**Issue by HRading** [Azure/azure-powershell#21382]
### Description of the new feature

If you run:
`Get-AzVM -ResourceGroupName <resource group name> -Name <vm name>`

The returned object includes the resource id of the VM in the ID property.

If you run:
`Get-AzVM -ResourceGroupName <resource group name> -Name <vm name> -Status`

There is no Id property.

The resource ID of an Azure object should always be part of the returned object.

### Proposed implementation details (optional)

The resource ID of an Azure object should always be part of the returned object.

Note: tested on Get-AzVM version 5.5.0

**Comment by isra-fel** [comment]
Thanks for reporting 👍 Let me route this to compute team.

**Comment by hilaryw29** [comment]
@Sandido would you mind taking a look at this? Thanks!

**Comment by TravisCragg-MSFT** [comment]
It looks like we state in the documentation that this only returns the status - https://learn.microsoft.com/en-us/powershell/module/az.compute/get-azvm?view=azps-9.6.0#-status

**Comment by Sandido** [comment]
Apologies, I am only now aware of this issue. 
@hilaryw29 , @HRading , I don't see this as a bug. The -Status parameter pretty clearly states that this return format is different and for a specific scenario. I'll ask the CRP team if they have insight into why Id is not being returned and if it can/should be added.

**Comment by TravisCragg-MSFT** [comment]
I am closing this issue as resolved. Please comment if there are any other questions of if this needs further action.
