### ISSUE TITLE
[Eng]: Repo Issue Label. 

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-powershell#21385]
### Description

Hi Azure Powershell team, 

I'm trying to repair an internal report that is breaking right now. The issue is with one of the labels in this repo. 
`Automanage`
The report complains that one of our tables that has a one to many relationship can't have a duplicate in the many column. For some reason in PowerBI it considers the label in this repo (`Automanage`) is the same as the label in Azure/azure-cli repo (`AutoManage`). But it does not consider them the same when I tell it to remove duplicates.

Simple solution is if the label in this repo could be changed to `AutoManage` so it matches the casing in the other repo. 

Thanks

**Comment by isra-fel** [comment]
Hi @ronniegeraghty thanks for reporting but "Automanage" is a single word as an Azure service. I suggest take this to azure cli's repo 😁 
![image](https://user-images.githubusercontent.com/11371776/229367168-6165109b-547f-48e7-ba44-56ae6b951b50.png)
