### ISSUE TITLE
[Doc]: Example 6 has incorrect parameters

### ISSUE THREAD

**Issue by guyrleech** [Azure/azure-powershell#21400]
### Description

The -OSDiskImage parameter is passed $osDisk in the example but $osdisk is not mentioned before this. I believe the parameter should be $osSnapshot which is defined just before the call to New-AzGalleryImageVersion

https://learn.microsoft.com/en-us/powershell/module/az.compute/new-azgalleryimageversion?view=azps-9.5.0

**Comment by navba-MSFT** [comment]
@guyrleech Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
