### ISSUE TITLE
Does Powershell module supports operation on multiple resources like Azure CLI using (--ids)

### ISSUE THREAD

**Issue by agrbhuvnesh** [Azure/azure-powershell#21406]
### Description

 Why “—ids” parameter not supported in the corresponding Azure PowerShell module for virtual Machine? 
Is there any difference in Capabilities / framework provided for Azure CLI Vs Powershell module ?

**Comment by wyunchi-ms** [comment]
Hi @agrbhuvnesh , in powershell, you can use this way to implement multiple resource operation:
```PowerShell
$IdList = @('/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Compute/virtualMachines/xxxx', '/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Compute/virtualMachines/yyyy', '/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Compute/virtualMachines/zzzz')
$IdList | Start-AzVm
```
