### ISSUE TITLE
No help for New-AzureRmAppServicePlan

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2145]
![image](https://cloud.githubusercontent.com/assets/466713/14806321/256f3eec-0b2f-11e6-8ea3-20c9441a62a7.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 the help is here:   https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Websites/Commands.Websites/Microsoft.Azure.Commands.Websites.dll-Help.xml#L297   How did you install?

**Comment by pcgeek86** [comment]
@markcowl I used the `Install-Module` command on Windows 10 RTM.

**Comment by markcowl** [comment]
@pcgeek86 We have the root cause.  Those cmdlets which had help before will be restored.  Will work to add help for new cmdlets in the next release.

**Comment by pcgeek86** [comment]
@markcowl :+1:

**Comment by markcowl** [comment]
Fixed in #2163
