### ISSUE TITLE
[Doc]: https://learn.microsoft.com/en-us/powershell/module/az.websites/set-azwebapp?view=azps-9.6.0

### ISSUE THREAD

**Issue by deltadan** [Azure/azure-powershell#21484]
### Description

There is a documentation https://learn.microsoft.com/en-us/powershell/module/az.websites/set-azwebapp?view=azps-9.6.0#-azurestoragepath

There is a reference to the deprecated AzureRM Powershell cmdlet's:

Azure Storage to mount inside a Web App for Container. Use New-AzureRmWebAppAzureStoragePath to create it

this should read as:
New-AzWebAppAzureStoragePath

**Comment by wyunchi-ms** [comment]
Thanks for your feedback!

**Comment by navba-MSFT** [comment]
@deltadan Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
