### ISSUE TITLE
No help for New-AzureRmWebAppSSLBinding

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2148]
![image](https://cloud.githubusercontent.com/assets/466713/14806362/812c7a1a-0b2f-11e6-96fb-f3a3c3c11bbc.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by cormacpayne** [comment]
This cmdlet has been updated with the appropriate help. Closing this issue.
