### ISSUE TITLE
No help for New-AzureRmWebAppBackup

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2150]
![image](https://cloud.githubusercontent.com/assets/466713/14806381/abb5f84c-0b2f-11e6-8e37-699bd4828927.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by cormacpayne** [comment]
This cmdlet has been updated with the appropriate help. Closing this issue.
