### ISSUE TITLE
No help for Reset-AzureRmWebAppPublishingProfile

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2151]
![image](https://cloud.githubusercontent.com/assets/466713/14806390/c948a26a-0b2f-11e6-974e-bd28f58fb28c.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by cormacpayne** [comment]
This cmdlet has been updated with the appropriate help. Closing this issue.
