### ISSUE TITLE
No help for Reset-AzureRmWebAppSlotPublishingProfile

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2152]
![image](https://cloud.githubusercontent.com/assets/466713/14806396/db62a61c-0b2f-11e6-9575-7114b2af0258.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 OK, it looks like at some point, the dll-Help.xml stopped being copied into the output directory.  Thanks for the heads up, investigating.  Also, this seems to be a cleever way to defeat the static help check.  Will close off that issue as well.

**Comment by markcowl** [comment]
@Nking92 It looks like we stopped copying the websites help xml sometime last year (between 1.00-preview and 1.00-preview2).  We need to add this back to the csproj and update the wxi file.  Do you have bandwidth for this today?  Otherwise, I will do it.

**Comment by Nking92** [comment]
I have time to do this today. Should I add something like what's below to the csproj? I'm not 100% sure of what the proper fix is.

` <None Include="Microsoft.Azure.Commands.Websites.dll-Help.xml" /> `

**Comment by ahmedelnably** [comment]
adding @akurmi for FYI

**Comment by pcgeek86** [comment]
@markcowl Thanks for checking into this.

**Comment by markcowl** [comment]
@Nking92 Yes, with 'Copy If Newer' selected.  Meanwhile I am fixing the bug in the static analysis tools that allowed this to slip through

**Comment by markcowl** [comment]
@Nking92 Since this is  a small, targeted fix, it doesn't have to be ready today, we can take this change against the release branch post code complete

**Comment by cormacpayne** [comment]
This issue seems to have been resolved as the help for this cmdlet now appears. Closing this issue.
