### ISSUE TITLE
Connect-AzAccount sends warning to console after Azure PowerShell updated to version 5.218.0

### ISSUE THREAD

**Issue by ubaysil** [Azure/azure-powershell#21543]
### Description

I have been using this function to authenticate to Azure and manage resources with my client, but recently I encountered some issues with it.

  Specifically, I noticed that the default scope of function seems not to be process anymore, but instead changes to CurrentUser. This causes problems – unexpected warning during the pipeline runs: _WARNING: The provided service principal secret will be included in the 'AzureRmContext.json' file found in the user profile ( C:\Users\(userName)\.Azure ). Please ensure that this directory has appropriate protections._
 
  For your information, in my business project, we use DevOps, Azure Resource Manager, and run the azure powershell in yaml pipeline.

Below is the screenshot, as you can see, everything looks good when we connect to azure subscription – before March 24.
 
![image](https://user-images.githubusercontent.com/54658109/231976509-0d69ee51-e4c6-49f8-bb11-4f2cfe8e9c58.png)

Auto disconnect at the end of task:
 
![image](https://user-images.githubusercontent.com/54658109/231976556-f64fd62d-6357-4f4f-a4a1-c46ca11a0605.png)

 
After March 24 – And the Azure Powershell Version changes to 5.218.0
 
![image](https://user-images.githubusercontent.com/54658109/231976589-b89fc138-eb52-4f74-ace3-ea750db89369.png)

And the disconnect performed differently:
 
![image](https://user-images.githubusercontent.com/54658109/231976633-921699a7-a1e1-4fcf-ae52-b582681dfa96.png)

 
A test in my local powershell:
 
![image](https://user-images.githubusercontent.com/54658109/231976671-2203a527-4c57-46c7-94db-7daee0b9b21e.png)

I checked the documentation, but I could not find any information about these changes. I wonder if this is a bug or a feature, and if there is a way to revert to the previous behavior or configure the function to suit my needs so that I can dispel customers’ concerns to security leaks.

### Issue script & Debug output

```PowerShell
-
```

### Environment data

```PowerShell
-
```

### Module versions

```PowerShell
-
```

**Comment by msJinLei** [comment]
@ubaysil Please update your Az.Accounts version to 2.11.2 to see whether the warning is removed. The SP credential is stored into a encrypted file so that the warning message is removed.

**Comment by isra-fel** [comment]
I'll contact Azure DevOps team to update the version of Az.Accounts.
