### ISSUE TITLE
Migrating from Azure AD Preview to AZ PowerShell - cannot find equivalent object functions in AZ PowerShell

### ISSUE THREAD

**Issue by liammccandlish** [Azure/azure-powershell#21596]
### Description

I am currently in the process of updating a runbook from using runas authentication to managed identities / app reg. In the  process I noticed the script is using the AzureADPreview module, which will be depreciated this year. I cannot find the appropriate functions in AZ PowerShell. The script uses the following (there are more but I have found the equivalent functions in AZ PowerShell). The PSVersion will be updated once I can replace the appropriate functions and get rid of the old module.

- Get-AzureADObjectSetting
- remove-azureadobjectsetting
- Get-AzureADDirectorySettingTemplate
- New-AzureADObjectSetting

### Environment data

```PowerShell
PSVersion                      5.1.17763.3532                                                                           
PSEdition                      Desktop                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
BuildVersion                   10.0.17763.3532                                                                          
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1
```

**Comment by wyunchi-ms** [comment]
Hi @liammccandlish , thanks for your feedback! We will discuss about this in the internal meeting.

**Comment by dolauli** [comment]
@liammccandlish  You should try to find them in https://www.powershellgallery.com/packages/Microsoft.Graph/1.26.0 instead of Azure PowerShell.
