### ISSUE TITLE
Az.Accounts, Az.Monitor and Az.Resources use Newtonsoft.Json version 10.0.3 that has security vulnerabilities

### ISSUE THREAD

**Issue by srinisudharsan** [Azure/azure-powershell#21605]
### Description

Please refer to [this vulnerability](https://github.com/advisories/GHSA-5crp-9r3c-p9vr).

I see a related pull request, however no updates to the corresponding psd1 files to release new versions of the module.
https://github.com/Azure/azure-powershell/pull/21479

### Issue script & Debug output

```PowerShell
N/A
```

### Environment data

```PowerShell
N/A
```

### Module versions

```PowerShell
N/A
```

### Error output

```PowerShell
N/A
```

**Comment by wyunchi-ms** [comment]
Hi @srinisudharsan , thanks for your feedback! We have already update NewtonSoft.Json to 13.0.3. This will be published in this release acound May.

**Comment by srinisudharsan** [comment]
Thank you!
