### ISSUE TITLE
Profscv will not let me sign in 

### ISSUE THREAD

**Issue by RiskySolutions** [Azure/azure-powershell#21625]
### Description

![IMG_7204](https://user-images.githubusercontent.com/128091138/233538152-156ed0e3-cd9b-4ed2-b811-dcb915678fbc.jpeg)

**Comment by wyunchi-ms** [comment]
Hi @jrichy1 , thanks for your feedback! Could you give us more details about your issue? Are you using Azure PowerShell? Looks it's not the GUI of Azure PowerShell or PowerShell. Are you having a problem for Windows login?
