### ISSUE TITLE
Get-AzStorageBlob unexpected behavior depending on New-AzStorageContext

### ISSUE THREAD

**Issue by slaven** [Azure/azure-powershell#21641]
### Description

**Example 1**: Works fine.
```powershell
$context1 = New-AzStorageContext -Anonymous -BlobEndpoint "https://bcartifacts.blob.core.windows.net"
Get-AzStorageBlob -Context $context1 -Container "onprem" -MaxCount 10
``` 

**Example 2**: _Get-AzStorageBlob : Object reference not set to an instance of an object._
```powershell
$context2 = New-AzStorageContext -ConnectionString "BlobEndpoint=https://bcartifacts.blob.core.windows.net/;"
Get-AzStorageBlob -Context $context2 -Container "onprem" -MaxCount 10
```

Both `$context1` and `$context2` have the same property values and produce the same ConnectionString, but `Get-AzStorageBlob` throws an error for `$context2` .

Is this expected behavior? If it is, why?

### Issue script & Debug output

```PowerShell
Get-AzStorageBlob : Object reference not set to an instance of an object.
At C:\script.ps1:2 char:1
+ Get-AzStorageBlob -Context $context2 -Container "onprem" -MaxCount 10
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzStorageBlob], NullReferenceException
    + FullyQualifiedErrorId : NullReferenceException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand
```

### Environment data

```PowerShell
Name                           Value                                                                                                                                                                                   
----                           -----                                                                                                                                                                                   
PSVersion                      5.1.20348.1366                                                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                 
BuildVersion                   10.0.20348.1366                                                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                                                         
WSManStackVersion              3.0                                                                                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                                                                                     
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                                                                                                                             
---------- -------    ----                                ----------------                                                                                                                                             
Script     2.12.1     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}                                                                                     
Script     5.5.0      Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle...}
```

### Error output

```PowerShell
Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.WindowsAzure.Commands.Storage.Common.Util.GetTrack2BlobClient(Uri blobUri, AzureStorageContext context, BlobClientOptions options, Nullable`1 blobType)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.Util.GetTrack2BlobClient(BlobContainerClient track2container, String blobName, AzureStorageContext context, String versi
                 onId, Nullable`1 IsCurrentVersion, String snapshot, BlobClientOptions options, Nullable`1 blobType)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.GetAzureStorageBlob(BlobItem blobItem, BlobContainerClient track2container, AzureStorage
                 Context context, String continuationToken, BlobClientOptions options)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.<ListBlobsByPrefix>d__53.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.<ListBlobsByName>d__52.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.<RunConcurrentTask>d__26.MoveNext()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzStorageBlob}
Line           : Get-AzStorageBlob -Context $context2 -Container "onprem" -MaxCount 10
                 
Position       : At C:\script.ps1:2 char:1
                 + Get-AzStorageBlob -Context $context2 -Container "onprem" -MaxCount 10
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1
```

**Comment by navba-MSFT** [comment]
@slaven Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by yifanz7** [comment]
@slaven The second method of creating a context is incorrect. Per https://learn.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string, there's not a way to set anonymous with a connection string. 
In PowerShell, you will need to explicitly set -Anonymous to use authentication.

**Comment by navba-MSFT** [comment]
@slaven The usage syntax for the `-Anonymous` parameter in `New-AzStorageContext` cmdlet are below:

```
New-AzStorageContext
   [-StorageAccountName] <String>
   [-Anonymous]
   [-Protocol <String>]
   [-Endpoint <String>]
   [<CommonParameters>]
```

```
New-AzStorageContext
   [-StorageAccountName] <String>
   [-Anonymous]
   [-Protocol <String>]
   -Environment <String>
   [<CommonParameters>]
```

```
New-AzStorageContext
   [-Anonymous]
   [-BlobEndpoint <String>]
   [-FileEndpoint <String>]
   [-QueueEndpoint <String>]
   [-TableEndpoint <String>]
   [<CommonParameters>]
```

In short, you cannot use `-Anonymous `for ConnectionString parameter. The right syntax for using the **-ConnectionString** parameter is below:


> **New-AzStorageContext -ConnectionString "DefaultEndpointsProtocol=https;AccountName=ContosoGeneral;AccountKey=< Storage Key for ContosoGeneral ends with == >;"**

**Comment by yifanz7** [comment]
@slaven Per the doc https://learn.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string, in PowerShell we currently don't support connection string with anonymous. Could you please share the user scenario where this should be supported? So that we can look into it. 

Regarding the two issues mentioned - 
1. The output of the command `StorageAccountName : [Anonymous]` is misleading. It shouldn't be anonymous here 
2. The `NullReferenceException` failure is misleading 

We will look into them and fix in a future release. Please let us know if you have any questions.

**Comment by slaven** [comment]
Thank you.

I forgot to mention that _Example 2_ works perfectly fine if I use `Az.Storage` `4.9.0` instead of `5.5.0`.

**Comment by navba-MSFT** [comment]
@slaven Thanks for getting back. The example 2 works because it doesn't use anonymous with connectionString.

As mentioned [above](https://github.com/Azure/azure-powershell/issues/21641#issuecomment-1522694125), Regarding the `StorageAccountName : [Anonymous]` and `NullReferenceException ` misleading output , this would be addressed in future release.

**Comment by slaven** [comment]
> The example 2 works because it doesn't use anonymous with connectionString.

Now I'm really confused with your comment, because _Example 2_ **doesn't work**, that's the reason I'm doing this bug report. I have a feeling you didn't understand what issue I reported.
I can read documentation. I never tried to use `-Anonymous` with `-ConnectionString` for `New-AzStorageContext` because that cannot be used, as you wrote yourself in previous comment.

I'm sorry if I confused you with my bug report... So let's start again. This time I'll do my best.

My questions:
1) Why is `-Anonymous` a parameter of `New-AzStorageContext`? Anonymous or simply _anonymous public read access_ is [supported](https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-requests-to-azure-storage)  **only** for _Azure Blobs_. And an Azure Blob can have both private and public containers at the same time. In my opinion, if we even need `-Anonymous` as a parameter, it should not be a parameter of context. If it needs to exist, it should be scoped to container level or Blob Cmdlets because only Blob supports anonymous public read access on a per container level.

2)  But since we have `-Anonymous` parameter. Why this doesn't return an error: `New-AzStorageContext -Anonymous -TableEndpoint "https://localhost"` or this `New-AzStorageContext -Anonymous -QueueEndpoint "https://localhost"`? Why am I allowed to create a new context for Azure artifact type which does not support anonymous access?

3) There are 3 ways to set auth for a storage account: SasToken, AccountName/Key and AAD. (Some other parameters can affect this, but let's put aside that for now). If I use `New-AzStorageContext -ConnectionString` and pass connection string without any auth mechanism (as in my **Example 2**), that obviously implies I'll try to access artifacts anonymously. Am I correct with that assumption? So there is a way for you to detect if I'm trying to access artifacts anonymously or with auth just by looking what's inside of connection string.
And if I try to execute: `New-AzStorageContext -BlobEndpoint "https://bcartifacts.blob.core.windows.net"` it's obvious I'm trying to create anonymous context because I didn't use any auth mechanism, so why do I need to set `-Anonymous` for it to work properly with `Get-AzStorageBlob`???

Issues I'd like to report (I'm using version `5.6.0` or `Az.Storage` now):
1) Why are these two objects equal?
```
$context1 = New-AzStorageContext -Anonymous -BlobEndpoint "https://bcartifacts.blob.core.windows.net"
$context2 = New-AzStorageContext -ConnectionString "BlobEndpoint=https://bcartifacts.blob.core.windows.net/;"
Compare-Object $context1 $context2 -IncludeEqual
```
And why are both returning `StorageAccountName  : [Anonymous]`

2) If those two objects **REALLY** are equal, why 2nd call produces an exception?
```
Get-AzStorageBlob -Context $context1 -Container "onprem" -MaxCount 10
Get-AzStorageBlob -Context $context2 -Container "onprem" -MaxCount 10
```

3) If I switch to `Az.Storage` version `4.9.0` examples above work fine. And this is the reason I'm doing this bug report for `5.5.0`. Because this worked fine before.

4) Why does `New-AzStorageContext -BlobEndpoint "https://bcartifacts.blob.core.windows.net"` returns `StorageAccountName  : [AccessToken]`. [I don't get this...](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.auth.storagecredentials.istoken?view=azure-dotnet)

5) Why does `New-AzStorageContext -ConnectionString "BlobEndpoint=https://bcartifacts.blob.core.windows.net/;"` returns `StorageAccountName  : [Anonymous]` if you don't support anonymous with connectionString, as you said before?

**Comment by yifanz7** [comment]
@slaven To partially answer the issues you mentioned above -
1. context1 and context2 are different if you check the credentials. context2 doesn't have the credentials field 
```
PS C:\Users\yifanzhang> $context1.StorageAccount.Credentials


SASToken     :
AccountName  :
KeyName      :
IsAnonymous  : True
IsSAS        : False
IsSharedKey  : False
IsToken      : False
SASSignature :



PS C:\Users\yifanzhang> $context2.StorageAccount.Credentials
```
However, it is misleading that context2 has `StorageAccountName  : [Anonymous]` as the context is not valid and it shouldn't be anonymous. We will fix this issue in a future release 

2. Given that context1 and context2 are not equal, the last line `Get-AzStorageBlob -Context $context2 -Container "onprem" -MaxCount 10` throws an exception, as we're checking for the credentials and the credentials are not found in context2. This is definitely also a very misleading exception here. We will fix this in a future release too. 
3. I still need to dig into our previous code and find out why it was working in 4.6.9 and get back later 
4. `New-AzStorageContext -BlobEndpoint "https://bcartifacts.blob.core.windows.net" returns StorageAccountName  : [AccessToken]` because it thinks you're using OAuth authentication with your connected account. You might find a sample usage here https://learn.microsoft.com/en-us/powershell/module/az.storage/new-azstoragecontext?view=azps-9.7.0#example-14-create-a-context-by-using-the-oauth-authentication-with-a-specified-blob-endpoint
If you don't have a connected account and run the command, you will get 
```
PS C:\WINDOWS\system32> New-AzStorageContext -BlobEndpoint "https://bcartifacts.blob.core.windows.net"
New-AzStorageContext : Context cannot be null.  Please log in using Connect-AzAccount.
At line:1 char:1
+ New-AzStorageContext -BlobEndpoint "https://bcartifacts.blob.core.win ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzStorageContext], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Storage.Common.Cmdlet.NewAzureStorageContext
```
Or you can use anonymous credential like 
```
PS C:\WINDOWS\system32> New-AzStorageContext -BlobEndpoint "https://bcartifacts.blob.core.windows.net"  -anonymous


StorageAccountName  : [Anonymous]
BlobEndPoint        : https://bcartifacts.blob.core.windows.net/
TableEndPoint       :
QueueEndPoint       :
FileEndPoint        :
Context             : Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext
Name                :
StorageAccount      : BlobEndpoint=https://bcartifacts.blob.core.windows.net/;
TableStorageAccount : BlobEndpoint=https://bcartifacts.blob.core.windows.net/
Track2OauthToken    :
EndPointSuffix      : core.windows.net/
ConnectionString    : BlobEndpoint=https://bcartifacts.blob.core.windows.net/;
ExtendedProperties  : {}
```
5. As mentioned above, returning anonymous is definitely not clear and misleading. We will try to fix it ASAP in a future release 

Please let me now if you have any other questions

**Comment by navba-MSFT** [comment]
@slaven The above PR has been filed to address this issue and it is merged now.
