### ISSUE TITLE
Get-AzSubscriptionDiagnosticSettingCategory is not recognized as a name of a cmdlet in Azure Cloud Shell

### ISSUE THREAD

**Issue by Naveenommi-MSFT** [Azure/azure-powershell#21660]
### Description

Prerequisites
 Existing Issue: Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
 Descriptive Title: Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in Get-Foo cmdlet" instead of "Typo."
 Verify Version: If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.
Links
https://github.com/MicrosoftDocs/azure-docs-powershell/blob/42fa0f29c91be9c3f2150772ce07d01150d6e85a/azps-8.3.0/Az.Monitor/Get-AzSubscriptionDiagnosticSettingCategory.md
https://learn.microsoft.com/en-us/powershell/module/az.monitor/get-azsubscriptiondiagnosticsettingcategory?view=azps-8.3.0
Summary
Get-AzSubscriptionDiagnosticSettingCategory is not recognized as a name of a cmdlet in Azure Cloud Shell.

Details
No response

Suggested Fix
Add it to Cloud Shell PowerShell.

**Comment by isra-fel** [comment]
Created from https://github.com/MicrosoftDocs/azure-docs-powershell/issues/2537

**Comment by isra-fel** [comment]
This command was deprecated in Az 9.0.
Cloud shell always has the latest version of Az. That's why the command is not recognized.
Please use [Get-AzEventCategory](https://learn.microsoft.com/en-us/powershell/module/az.monitor/get-azeventcategory?view=azps-9.6.0) instead.

**Comment by isra-fel** [comment]
Customer found this cmdlet in the example of [set-azdiagnosticsetting](https://learn.microsoft.com/en-us/powershell/module/az.monitor/set-azdiagnosticsetting?view=azps-8.3.0#example-7-enable-all-categories-for-a-subscription) which was also deprecated and replaced by [New-AzDiagnosticSetting](https://learn.microsoft.com/en-us/powershell/module/az.monitor/new-azdiagnosticsetting?view=azps-9.7.1#syntax) in Az 9.

We should add an example to `New-AzDiagnosticSetting` to demonstrate how the new cmdlets work on the old scenarios.

**Comment by VeryEarly** [comment]
> Customer found this cmdlet in the example of [set-azdiagnosticsetting](https://learn.microsoft.com/en-us/powershell/module/az.monitor/set-azdiagnosticsetting?view=azps-8.3.0#example-7-enable-all-categories-for-a-subscription) which was also deprecated and replaced by [New-AzDiagnosticSetting](https://learn.microsoft.com/en-us/powershell/module/az.monitor/new-azdiagnosticsetting?view=azps-9.7.1#syntax) in Az 9.
> 
> We should add an example to `New-AzDiagnosticSetting` to demonstrate how the new cmdlets work on the old scenarios.
> 
> Customer's comment: [MicrosoftDocs/azure-docs-powershell#2537 (comment)](https://github.com/MicrosoftDocs/azure-docs-powershell/issues/2537#issuecomment-1534382670)

existing example demonstrate pretty clear how to use this cmdlet:
https://learn.microsoft.com/en-us/powershell/module/az.monitor/new-azdiagnosticsetting?view=azps-10.1.0

Hi @Naveenommi-MSFT please feel free to let me know or re-open this issue if you have any further questions after went through the above document.

Thanks.
