### ISSUE TITLE
SQL Data Warehouse compute usage

### ISSUE THREAD

**Issue by markpjohnson** [Azure/azure-powershell#2167]
Is there a way to retrieve the current (or average) DWU usage for a SQL DW via Powershell? 

From the Azure Portal: 

![image](https://cloud.githubusercontent.com/assets/469737/14893444/0c13fb92-0d35-11e6-9ab5-9a9791a2d0bb.png)

**Comment by akromm** [comment]
@markpjohnson  have you tried using the [Get-AzureRmMetric](https://docs.microsoft.com/en-us/powershell/module/azurerm.insights/get-azurermmetric?view=azurermps-4.1.0) cmdlets?
