### ISSUE TITLE
On Azure Automation, Import-Module -Name Az.Resources is on error

### ISSUE THREAD

**Issue by sebfantini** [Azure/azure-powershell#21680]
### Description

**Step 1** : I create a new Azure Automation
**Step 2** : I create a simple Runbook on Azure Automation with this script :
import-Module -Name Az.Resources
import-Module -Name Az.Websites

**Execution Result**
When this Runbook run, the import instructions are on error.
**1/**
Register-AzModule : The type initializer for 'Microsoft.Azure.Commands.Common.AzModule' threw an exception. At C:\Modules\Global\Az.Resources\MSGraph.Autorest\Az.MSGraph.psm1:49 char:13 + $VTable = Register-AzModule + ~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Register-AzModule], TypeInitializationException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Common.RegisterAzModule

**2/** 
Register-AzModule : The type initializer for 'Microsoft.Azure.Commands.Common.AzModule' threw an exception. At C:\Modules\Global\Az.Resources\Authorization.Autorest\Az.Authorization.psm1:49 char:13 + $VTable = Register-AzModule + ~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Register-AzModule], TypeInitializationException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Common.RegisterAzModule

**3/**
Register-AzModule : The type initializer for 'Microsoft.Azure.Commands.Common.AzModule' threw an exception. At C:\Modules\Global\Az.Websites\Websites.Autorest\Az.Websites.psm1:49 char:13 + $VTable = Register-AzModule + ~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Register-AzModule], TypeInitializationException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Common.RegisterAzModule

**The module version are :**
Az.Resources : 6.0.0
Az.WebSites : 2.11.2

Finally, we noticed that it was impossible to update these modules with a higher or lower version.

### Issue script & Debug output

```PowerShell
import-Module -Name Az.Resources
import-Module -Name Az.Websites
```

### Environment data

```PowerShell
Azure.Automation
```

### Module versions

```PowerShell
Az.Resources : 6.0.0
Az.WebSites : 2.11.2
```

### Error output

```PowerShell
**1/**
Register-AzModule : The type initializer for 'Microsoft.Azure.Commands.Common.AzModule' threw an exception. At C:\Modules\Global\Az.Resources\MSGraph.Autorest\Az.MSGraph.psm1:49 char:13 + $VTable = Register-AzModule + ~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Register-AzModule], TypeInitializationException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Common.RegisterAzModule

**2/** 
Register-AzModule : The type initializer for 'Microsoft.Azure.Commands.Common.AzModule' threw an exception. At C:\Modules\Global\Az.Resources\Authorization.Autorest\Az.Authorization.psm1:49 char:13 + $VTable = Register-AzModule + ~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Register-AzModule], TypeInitializationException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Common.RegisterAzModule

**3/**
Register-AzModule : The type initializer for 'Microsoft.Azure.Commands.Common.AzModule' threw an exception. At C:\Modules\Global\Az.Websites\Websites.Autorest\Az.Websites.psm1:49 char:13 + $VTable = Register-AzModule + ~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Register-AzModule], TypeInitializationException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Common.RegisterAzModule
```

**Comment by Steeve13011** [comment]
I have exactly the same problem. On another Azure Automation resource with the same module versions, I don't have a crash.

**Comment by isra-fel** [comment]
Thanks for reporting. This issue is duplicated with https://github.com/Azure/azure-powershell/issues/21647 . I'll close it and please track that one. Thanks.
