### ISSUE TITLE
Connect-AzAccount unrecognized in version 2.12.2

### ISSUE THREAD

**Issue by psprashanth** [Azure/azure-powershell#21698]
### Description

Azure Function App started throwing error as Connect-AzAccount is not recognized, had to downgrade it to 2.12.1 to make it work. 
When is this issue getting fixed in 2.12.2 or the latest version

### Issue script & Debug output

```PowerShell
Connect-AzAccount is not recognized
```

### Environment data

```PowerShell
Latest on Azure Function app
```

### Module versions

```PowerShell
2.12.2
```

### Error output

```PowerShell
unrecognized command Connect-AzAccount
```

**Comment by isra-fel** [comment]
Hey @psprashanth are you running your app on PowerShell 7.1? If so, please migrate to 7.2+ since it already reached end of support.
