### ISSUE TITLE
New-AzureWebsite should let me specify a SKU

### ISSUE THREAD

**Issue by jdhuntington** [Azure/azure-powershell#217]
I have consumed my allocation of free-tier websites, and now each invocation of `New-AzureWebsite` fails.

I would like to create a new `Basic` or `Standard` website using `New-AzureWebsite`.

**Comment by NaveenGoli** [comment]
New ARM API PowerShell cmdlets are coming out this month you can use them to achieve the same.

**Comment by markcowl** [comment]
@jdhuntington new ARM cmdlets are out, so this functionality should be available.
