### ISSUE TITLE
Stop-AzSynapseTrigger is not stopping trigger on Synapse workspace

### ISSUE THREAD

**Issue by tmfahim** [Azure/azure-powershell#21705]
### Description

 Stop-AzSynapseTrigger is not stopping any trigger although it is not giving any error

`$trigger =Get-AzSynapseTrigger -WorkspaceName xxxxxxx
Foreach ($trig in $trigger) {  Stop-AzSynapseTrigger -WorkspaceName synw-mcs-dw-wus-dev -Name $trig.Name }`

Output:
`Stop-AzSynapseTrigger: {}
Stop-AzSynapseTrigger: {}
Stop-AzSynapseTrigger: {}
Stop-AzSynapseTrigger: {}
Stop-AzSynapseTrigger: {}
Stop-AzSynapseTrigger: {}
Stop-AzSynapseTrigger: {}
Stop-AzSynapseTrigger: {}
Stop-AzSynapseTrigger: {}
Stop-AzSynapseTrigger: {}
Stop-AzSynapseTrigger: {}`

### Issue script & Debug output

```PowerShell
........
DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:  ExpiresOn: 2023-05-05T00:48:24.0000000+00:00
DEBUG: Request [df4b5c5f-261d-4b58-a7cc-5f8b49d32e21] POST https://synw-mcs-dw-wus-dev.dev.azuresynapse.net/triggers/Fact_Equipment_Status_Daily/stop?api-version=2020-12-01
Accept:application/json
x-ms-client-request-id:df4b5c5f-261d-4b58-a7cc-5f8b49d32e21
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Analytics.Synapse.Artifacts/1.0.0-preview.17 (.NET 7.0.5; Linux 5.4.0-1107-azure #113~18.04.1-Ubuntu SMP Tue Apr 25 13:58:29 UTC 2023)
Authorization:REDACTED
client assembly: Azure.Analytics.Synapse.Artifacts
DEBUG: Response [df4b5c5f-261d-4b58-a7cc-5f8b49d32e21] 200 OK (00.2s)
Server:Kestrel,Microsoft-HTTPAPI/2.0
Strict-Transport-Security:REDACTED
x-ms-correlation-request-id:REDACTED
x-ms-request-id:4e43517a-9960-47f9-a72f-aa9514eb7954
x-ms-client-request-id:df4b5c5f-261d-4b58-a7cc-5f8b49d32e21
Date:Fri, 05 May 2023 00:04:09 GMT
Content-Length:2
Content-Type:application/json; charset=utf-8

DEBUG: 12:04:10 AM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Stop-AzSynapseTrigger: {}
DEBUG: 12:04:10 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 12:04:10 AM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Synapse:2.3.1; CommandName: Stop-AzSynapseTrigger; PSVersion: 7.3.4; IsSuccess: False; Duration: 00:00:00.3347951; Exception: {};
DEBUG: 12:04:10 AM - StopAzureSynapseTrigger end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 5.4.0-1107-azure #113~18.04.1-Ubuntu SMP Tue Apr 25 13:58:29 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Blank
```

### Error output

```PowerShell
No error
```

**Comment by SaurabhSharma-MSFT** [comment]
@tmfahim We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@tmfahim I have tried Stopping the trigger and it works as expected. 
![SynapseTrigger](https://github.com/Azure/azure-powershell/assets/38112130/f22372eb-598b-4120-b3b3-fcd335e1a79b)
I am using 2.2.0 of Az.Synapse module.
![image](https://github.com/Azure/azure-powershell/assets/38112130/6782c54a-da9f-420f-b2bc-13683b54985d)
Can you please try upgrading your module. Thanks.

**Comment by tmfahim** [comment]
Hi there,
As I mentioned at the very beginning of the ticket, it works fine when I ran the command from Azure PowerShell CLI. It creates problem when I run it through GitHub Workflow. I checked the version between Azure CLI and runner, it seems same to me. As you mentioned to upgrade the module, would you please suggest what are the modules I need to upgrade and what is the exact version?

Thanks.

With Regards,

Fahim Amin
Data Architect, Heavy Oil
Upstream Digital Accelerator
Ph.: +1-587-476-2540
Cell: +1-403-860-1124
***@***.******@***.***>

ExxonMobil Business Support Centre Canada ULC
505 Quarry Park Blvd. SE
Central Building- C2A.126
Calgary AB T2C 5N1

**Comment by SaurabhSharma-MSFT** [comment]
@tmfahim I was able to reproduce the error which you were talking about and submitted a PR to address it and it will be merged after the review. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
