### ISSUE TITLE
`Get-AzResourceGroup` on `-Id` requires `Set-AzContext` to given sub first, unlike how `Get-AzResource` works

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-powershell#21725]
### Description

`Get-AzResourceGroup -Id <resourcegroupid>` fail with "Provided resource group does not exist", until you `Set-AzContext` to the subscription the resource group in question is located.

This is inconsistent with how `Get-AzResource -ResourceId` works. If `-ResourceId` is given, the rest call uses it vs. current Az scope.

### Issue script & Debug output

```PowerShell
# Assets
$Sub1Guid = 'some_guid'
$Sub2Guid = 'some_other_guid'
$RgName   = 'some_rg_name'

# Generate resource id of the resource group in question
$ResourceGroupId = '/subscriptions/{0}/resourceGroups/{1}' -f $Sub2Guid, $RgName

# Set context to sub1
Set-AzContext -Subscription $Sub1Guid

# Try to get rg on resource id => Fails
Get-AzResourceGroup -Id $ResourceGroupId

# Set context to sub2
Set-AzContext -Subscription $Sub2Guid

# Try to get rg on resource id => Succeeds
Get-AzResourceGroup -Id $ResourceGroupId
```

### Environment data

```PowerShell
Windows PowerShell 5.1
```

### Module versions

```PowerShell
Az.Resources 6.6.1
```

**Comment by isra-fel** [comment]
We are investigating the root cause. At first glance it looks like a bug of `Get-AzResourceGroup` to only take resource group name from the id.
