### ISSUE TITLE
Get-AzConsumptionUsageDetail returns 'BadRequest'

### ISSUE THREAD

**Issue by Mantrareborn** [Azure/azure-powershell#21724]
### Description

I had a 'Bad Request' error while trying to use Get-AzConsumptionUsageDetail on my Powershell script to get consumption reports of multiple Azure subscriptions, I looked on the internet and it seems like this issue has been going for a while now, it has to do with the PS API being outdated and the function working for specific legacy subscriptions only. I tried a workaround to this issue by using the Invoke-RestMethod, yet It was no luck either, this is my script :
`Connect-AzAccount

$subList = Get-AzSubscription
$startDate = "2022-04-01"
$endDate = "2022-04-30"

foreach($sub in $subList) {
    $url = "https://management.azure.com/subscriptions/$($sub.Id)/providers/Microsoft.Consumption/usageDetails?api-version=2023-03-01&`$filter=properties/UsageStart ge '$startDate' and properties/UsageEnd le '$endDate'"
    $accessToken = (Get-AzAccessToken -ResourceUrl https://management.azure.com).Token
    $headers = @{
        Authorization = "Bearer $accessToken"
    }
    $response = Invoke-RestMethod -Uri $url -Method GET -Headers $headers
    $response | Export-Csv -Path "C:\Reports\$($sub.Name).csv" -NoTypeInformation
}`

and this is the error I got when I ran the script on MS Visual Code (run as admin mode):

> Invoke-RestMethod : {"error":{"code":"InvalidResourceType","message":"The resource type 'UsageDetails' could not be found in 

> the namespace 'Microsoft.Consumption' for api version '2023-03-01-preview'. The supported api-v ersions are '2017-06-30-preview,2017-11-30,2018-01-31,2018-03-31,2018-05-31,2018-06-30,2018-08-31,2018-10-01,2018-11-01-preview,2018-12-01-preview,2019-01-01,2019-04-01-preview,2019-05-01-preview,2019-05-01,2019-10-01,20 19-11-01,2021-01-01,2021-10-01,2023-03-01'."}} At C:\Users\xxxxx\OneDrive - xyz\Documents\VScode\thirdtry.ps1:13 char:17
> 
> ... $response = Invoke-RestMethod -Uri $url -Method GET -Headers $headers ...
>             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
> FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand Export-Csv : Could not find a part of the path 'C:\Reports\jhon-abc-prd.csv'. At C:\Users\xxxxx\OneDrive - xyz\Documents\VScode\thirdtry.ps1:14 char:17
> ... $response | Export-Csv -Path "C:\Reports$($sub.Name).csv" -NoTypeInf ...
>             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> CategoryInfo : OpenError: (:) [Export-Csv], DirectoryNotFoundException
> FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.ExportCsvCommand

### Issue script & Debug output

```PowerShell
DEBUG: 9:46:53 AM - GetAzureRmConsumptionUsageDetail begin processing with ParameterSet 'Subscription'.      
DEBUG: 9:46:53 AM - using account id 'user@comp.com'...
DEBUG: 9:46:53 AM - [ConfigManager] Got [True] from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
DEBUG: [Common.Authentication]: Authenticating using Account: 'user@comp.com', environment: 'AzureCloud', tenant: '848de74a-7652-4f6fxxxx...'
DEBUG: 9:46:53 AM - [ConfigManager] Got nothing from [EnableLoginByWam], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 9:46:53 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'848de74a-7652-4f6fxxxx...', Scopes:'https://management.core.windows.net//.default', 
AuthorityHost:'https://login.microsoftonline.com/', UserId:'user@comp.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - 4fd75f18-2b74-4d98-xxxx.....] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - 4fd75f18-2b74-4d98-xxxx.....] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - 4fd75f18-2b74-4d98-xxxx.....] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - 4fd75f18-2b74-4d98-xxxx.....] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - 4fd75f18-2b74-4d98-xxxx.....] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z] Returning 1 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - d8a252d1-3a8b-4450-ba5xxxxxxx.........] MSAL MSAL.Desktop with assembly version '4.49.1.0'. 
CorrelationId(d8a252d1-3a8b-4450-ba5xxxxxxx.........)
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - d8a252d1-3a8b-4450-ba5xxxxxxx.........] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - d8a252d1-3a8b-4450-ba5xxxxxxx.........] LoginHint provided: False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - d8a252d1-3a8b-4450-ba5xxxxxxx.........] Account provided: True
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - d8a252d1-3a8b-4450-ba5xxxxxxx.........] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - d8a252d1-3a8b-4450-ba5xxxxxxx.........] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - d8a252d1-3a8b-4450-ba5xxxxxxx.........
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - d8a252d1-3a8b-4450-ba5xxxxxxx.........] === Token Acquisition (SilentRequest) started:
  Scopes: https://management.core.windows.net//.default
 Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - d8a252d1-3a8b-4450-ba5xxxxxxx.........] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - d8a252d1-3a8b-4450-ba5xxxxxxx.........] Access token is not expired. Returning the found cache entry.       
[Current time (05/08/2023 08:46:53) - Expiration Time (05/08/2023 09:47:16 +00:00) - Extended Expiration Time (05/08/2023 09:47:16 +00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - d8a252d1-3a8b-4450-ba5xxxxxxx.........] Returning access token found in cache. RefreshOn exists ? False     
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - d8a252d1-3a8b-4450-ba5xxxxxxx.........] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - d8a252d1-3a8b-4450-ba5xxxxxxx.........] 
 === Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise for Virtual Desktops [2023-05-08 08:46:53Z - d8a252d1-3a8b-4450-ba5xxxxxxx.........]  AT expiration time: 5/8/2023 9:47:16 AM +00:00, scopes: 
https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2023-05-08T09:47:16.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '848de74a-7652-4f6fxxxx...', UserId: 'user@comp.com'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/{SUB_ID}/providers/Microsoft.Consumption/usageDetails?$filter=properties/usageStart ge '2023-04-15' and properties/usageEnd le
'2023-04-30'&$top=1000&api-version=2018-01-31

Headers:
x-ms-client-request-id        : 046c0653
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
session-id                    : 71735206-
x-ms-request-id               : 43c5d8b5-
x-ms-correlation-request-id   : 0c0d225d-
x-ms-client-request-id        : 046c0653-
x-ms-ratelimit-microsoft.consumption-tenant-retry-after: 60
x-ms-ratelimit-remaining-microsoft.consumption-tenant-requests: 9
OData-Version                 : 4.0
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-routing-request-id       : WESTEUROPE:
Strict-Transport-Security     : max-age=315
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Mon, 08 May 2023 08:46:54 GMT
X-Powered-By                  : ASP.NET

Body:
{
  "error": {
    "code": "400",
    "message": "Subscription scope usage is not supported for current api version. Please use api version after 2019-10-01 (Request ID: 43c5d8b5-05bxxx...)"
  }
}

DEBUG: 9:46:55 AM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
Get-AzConsumptionUsageDetail : Operation returned an invalid status code 'BadRequest'
At line:1 char:1
+ Get-AzConsumptionUsageDetail -StartDate "2023-04-15" -EndDate "2023-0 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzConsumptionUsageDetail], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Consumption.Cmdlets.UsageDetails.GetAzureRmConsumptionUsageDetail
 
DEBUG: 9:46:55 AM - [ConfigManager] Got [True] from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
DEBUG: 9:46:55 AM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Billing:2.0.1; CommandName: Get-AzConsumptionUsageDetail; PSVersion: 5.1.19041.2673; IsSuccess: False; Duration: 00:00:02.7431668; Exception: Operation returned an invalid status code         
'BadRequest';
DEBUG: 9:46:55 AM - GetAzureRmConsumptionUsageDetail end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.12.2     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}
Script     2.0.1      Az.Billing                          {Get-AzBillingAccount, Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzBillingProfile...}
```

**Comment by SaurabhSharma-MSFT** [comment]
@Mantrareborn We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@Mantrareborn I am not able to reproduce this and getting the results correctly -
![image](https://github.com/Azure/azure-powershell/assets/38112130/9ad97ddb-6146-4250-9bb8-5758f6d14084)

**Comment by Mantrareborn** [comment]
@SaurabhSharma-MSFT I have already tried re-installing the Az.Billing Package before, however I think it has to do with certain subscriptions,  for example PAYG subscriptions have no issues using the  `AzConsumptionUsageDetail`  module, yet the Azure Plan  subscriptions are the one generating these kind of errors, I saw there are many open requests in this matter over Github and other  sites and there is no actual fix at the moment.
see blow issue opened in StackOverflow: [[Unable to get Azure Consumption Detail](https://stackoverflow.com/questions/70655921/unable-to-get-azure-consumption-detail)](https://stackoverflow.com/questions/70655921/unable-to-get-azure-consumption-detail)

**Comment by SaurabhSharma-MSFT** [comment]
@Mantrareborn There might be some issues with the Consumption usage details cmdlet.  Also, please note that - 
> ![image](https://github.com/Azure/azure-powershell/assets/38112130/3f043705-3c0b-4a29-8abe-4c8dbdae1f15)
Reference: [Consumption-Usage Details - List](https://learn.microsoft.com/en-us/rest/api/consumption/usage-details/list?tabs=HTTP) 

Can you please try using [New-AzCostManagementDetailReport](https://learn.microsoft.com/en-us/powershell/module/az.costmanagement/new-azcostmanagementdetailreport?view=azps-9.7.1) instead if this solves your problem.

**Comment by SaurabhSharma-MSFT** [comment]
@Mantrareborn What version of Az.CostManagement you are using as I am not getting any errors.

**Comment by Mantrareborn** [comment]
Sorry, the module was not installed correctly on my terminal, I now have the "0.3.1" version installed
![image](https://github.com/Azure/azure-powershell/assets/16080423/24ed4923-f20a-4d85-83d3-76c63eb2a2b4)

 but it stills gives back errors : 

![image](https://github.com/Azure/azure-powershell/assets/16080423/0ad785bb-ee92-47d9-81c3-e3e8f5dd836e)

**Comment by SaurabhSharma-MSFT** [comment]
@Mantrareborn Can you please share the `-debug` logs to further investigate. Thanks

**Comment by SaurabhSharma-MSFT** [comment]
@Mantrareborn I have tried this on my environment and able to get the results.  
What level of permissions you have on the subscription?
Can you please try changing scope to a resource group level using the below  - `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}`

**Comment by Mantrareborn** [comment]
@SaurabhSharma-MSFT I have reader permission over the subscription.
I have found a working solution by modifying the code to send POST and GET methods, I used the following Microsoft guide : [Query - Usage - REST API (Azure Cost Management)](https://learn.microsoft.com/en-us/rest/api/cost-management/query/usage?tabs=HTTP),
I will be closing this issue, Thanks.
