### ISSUE TITLE
New-AzApiManagementProduct -SubscriptionRequired $False still adds a subscription

### ISSUE THREAD

**Issue by Tridy** [Azure/azure-powershell#21747]
### Description

When I am using -SubscriptionRequired $False, it still creates a subscription.

example:

`New-AzApiManagementProduct -Context $apimContext -ProductId "0123456789" -Title "Starter" -Description "Blah" -LegalTerms "Free for all" -SubscriptionRequired $False -State "Published"`

After the command is executed, I still find that there is one new subscription created and assigned to the product.

### Issue script & Debug output

```PowerShell
$newProduct  = New-AzApiManagementProduct -Context $apimContext -ProductId "01234567890001" -Title "Product0001" -Description "Blah" -LegalTerms "Free for all" -SubscriptionRequired $False -State "Published"
$productId = $newProduct.ProductId
$subscriptionFromNewProduct = Get-AzApiManagementSubscription -Context $apimContext | Where-Object { $_.ProductId -eq $productId } # | Select-Object -ExpandProperty SubscriptionId
Write-Output $subscriptionFromNewProduct
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Script     2.12.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
Script     4.0.2                 Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManage…
```

**Comment by SaurabhSharma-MSFT** [comment]
@Tridy I am able to reproduce this issue and checking internally on the same.  I will update you as soon as I have any news. Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@Tridy It looks like the SubscriptionRequired parameter does not define whether or not we want to create a subscription assigned with the new Product, but rather if the APIs in the product are accessible to users without a subscription (= Open product, subscription NOT required) vs. APIs not accessible without a subscription key (= Protected product, subscription required is True).

![image](https://github.com/Azure/azure-powershell/assets/38112130/48df15c3-2fd5-4e5b-b718-33bda8c08af5)
Please refer to the following article: [Tutorial - Create and publish a product in Azure API Management | Microsoft Learn](https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-add-products?tabs=azure-portal)

Hope this answers your question.

**Comment by Tridy** [comment]
👍
