### ISSUE TITLE
Unsuported embedded browser version when login

### ISSUE THREAD

**Issue by damienthiery** [Azure/azure-powershell#2175]
Our corporate proxy is filtering http requests by user-agents. IE8 and lowers are blocked for security reasons.
My problem is that the command Add-AzureAccount opens a window for login with an embedded browser with a IE6 user agent !
Is there a way to change this version, or to use my default browser which is IE11 ?

**Comment by markcowl** [comment]
@damienthiery Which version of the Azure cmdlets are you using?

**Comment by damienthiery** [comment]
Azure PowerShell 1.3.2

2016-05-02 21:58 GMT+02:00 Mark Cowlishaw <notifications@github.com>:

**Comment by markcowl** [comment]
@damienthiery Do you see this same behavior in version 1.7, or any of the 2.x versions? We don't actually have control over this, but there may be a machine-wide setting for ADAL embedded browser

**Comment by markcowl** [comment]
@damienthiery After checking with the ADAL team, the only real solution is to edit a registry key to select a different browser version for the embedded browser control, see: https://blogs.msdn.microsoft.com/patricka/2015/01/12/controlling-webbrowser-control-compatibility/

**Comment by markcowl** [comment]
@damienthiery Please let us know if this works for you.  The other alternative would be to use service principall credentials.

**Comment by markcowl** [comment]
Closing as, we posted a workaround and there has been no response.  Please open a new issue if you see a recurrence.
