### ISSUE TITLE
Output class makes data inaccessible

### ISSUE THREAD

**Issue by markpjohnson** [Azure/azure-powershell#2177]
This script retrieves detailed metrics for an Azure resource. 

```powershell
$metrics = Get-AzureRmMetric -ResourceId '/some/resource/id' -DetailedOutput -MetricNames 'dwu_used' -TimeGrain 01:00:00
$metric = $metrics[0]
$metricValues = $metric.MetricValues
```

But the actual numbers in the `$metricValues` object cannot be accessed because its class (`PSMetricValuesCollection`) doesn't have any accessors for its data and doesn't inherit from `IEnumerable<>` or `IList<>`. The [`PSMetricValuesCollection`](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Insights/Commands.Insights/OutputClasses/PSMetricValuesCollection.cs#L26) class only allows printing of the detailed data. 

As a workaround, I was hoping to be able to access the detailed data from the `$metric` object because it is an instance of `PSMetric` which inherits from `Metric` (`Microsoft.Azure.Insights.Models.Metric`), and `Metric` has a property `public IList<MetricValue> MetricValues`. However, `PSMetric` explicitly hides that property: [`PSMetric.MetricValues`](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Insights/Commands.Insights/OutputClasses/PSMetric.cs#L27)

Can you make the detailed data accessible?

**Comment by asheniam** [comment]
We've added this to our backlog.  In general, we are looking at a broad set of enhancements in the metrics area.
