### ISSUE TITLE
Get-AzSqlServerVulnerabilityAssessmentSetting Not working with Assessment Express Configuration

### ISSUE THREAD

**Issue by lostsole** [Azure/azure-powershell#21772]
### Description

From PowerShell this does not show that Express Configuration is used, can only see from the portal that is set.
Only works with classic configurations.

https://learn.microsoft.com/en-us/azure/defender-for-cloud/sql-azure-vulnerability-assessment-overview

Found this to enable express:  But once it is enabled if I run it again it will just re-enable:
https://github.com/MicrosoftDocs/azure-docs/blob/10d5324dbb75acc0aa7380b70eb3d605db401520/articles/defender-for-cloud/powershell-sample-vulnerability-assessment-azure-sql.md?plain=1#L108

### Issue script & Debug output

```PowerShell
No Error.

This has been a while since they introduced Express Configuration that this command did not work for Express.  Just try it out.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:\> Get-Module Az*

ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Script     2.12.1                Az.Accounts
Script     4.5.0                 Az.Sql

PS C:\> Get-InstalledModule AZ

Version              Name                                Repository
-------              ----                                ----------
9.6.0                Az                                  PSGallery
```

### Error output

```PowerShell
No Error
```

**Comment by lostsole** [comment]
PS C:\Users\xyz> Get-AzSqlServerVulnerabilityAssessmentSetting -ResourceGroupName $AZserv.ResourceGroupName -ServerName $AZserv.ServerName -Debug;
DEBUG: 11:22:59 AM - GetAzureSqlServerVulnerabilityAssessmentSettings begin processing with ParameterSet 'GetByNameParameterSet'.
DEBUG: 11:23:05 AM - using account id 'tk@xyz.com'...
DEBUG: 11:23:07 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xc03c068-exd3-4d41-92de-xyz1235870/resourceGroups/rg-my-databases-xyz/providers/Microsoft.Sql/servers/sqlsrv-testbox-xyz/vulnerabilityAssessments/default?api-version=2020-11-01-preview

Headers:
x-ms-client-request-id        : 5b2e16d8-8e2d-4b4e-8052-4ec127046186
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : 0a0f846d-8b80-4f5a-af50-705019602702
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : c7403fa2-5584-4b9a-bcc4-25618b948e86
x-ms-routing-request-id       : WESTUS2:20230511T172310Z:c7403fa2-5584-4b9a-bcc4-25618b948e86
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 11 May 2023 17:23:10 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "properties": {
    "recurringScans": {
      "isEnabled": false,
      "emailSubscriptionAdmins": true
    }
  },
  "id": "/subscriptions/xc03c068-exd3-4d41-92de-xyz1235870/resourceGroups/rg-my-databases-xyz/providers/Microsoft.Sql/servers/sqlsrv-testbox-xyz/vulnerabilityAssessments/Default",
  "name": "Default",
  "type": "Microsoft.Sql/servers/vulnerabilityAssessments"
}




ServerName               : sqlsrv-testbox-xyz
ResourceGroupName        : rg-my-databases-xyz
StorageAccountName       : 
ScanResultsContainerName : 
RecurringScansInterval   : None
EmailAdmins              : True
NotificationEmail        : 

DEBUG: 11:23:12 AM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 11:23:12 AM - GetAzureSqlServerVulnerabilityAssessmentSettings end processing.

**Comment by lostsole** [comment]
This one might be related in not returning the correct info as well for the Express, I will run again in 24 hrs to see if it running correctly, as of right now there Portal for the VA shows nothing as all have been added to baseline for express, but the PowerShell command > Get-AzSecuritySqlVulnerabilityAssessmentScanResult -Server $SVName -ResourceId $ResourceID -WorkspaceId $WSID -Database $DBName -RuleId "VA2020" -ErrorVariable ProcessError -ErrorAction SilentlyContinue;  
Returns row with Status                 : Finding

**Comment by shaktisingh-msft** [comment]
Hi Team @dcurwin, @dcurwin, @Azure/springappslza ,

Could you please look into this issue, thanks

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@CESANU  Thanks for the update.

@shaktisingh-msft  - We're closing this issue now, and will work on the documentation updates as noted.
