### ISSUE TITLE
New-AzureWebsite should let me connect to a private GitHub repository

### ISSUE THREAD

**Issue by jdhuntington** [Azure/azure-powershell#218]
I'd like to create a new azure website from a private github repository that belongs to an organization that I'm a member of.

I ran the following transcript, and instead of the website being created, I was prompted to pick from _only public repositories_ that belong to me or my organizations.

I would also like the ability to specify the branch of the github repository that the website should deploy.

```
> $creds = Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
> Get-AzureSubscription -current

[... snip ...]

> New-AzureWebsite -name testwebsite546 -GithubCredentials $creds -GitHub -GithubRepository "MyOrganization/OrgPrivateRepo"
```

**Comment by markcowl** [comment]
@jdhuntington AFAIK, this is jus tnot supported in the API.  I believe it is intentional that you cannot use private github repositories for websites.  Assigning to the websites time for comment, anyway.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
