### ISSUE TITLE
[Doc]: typo in the example

### ISSUE THREAD

**Issue by eliot-trustm** [Azure/azure-powershell#21807]
### Description

Line 1 of the example script: 
$scope = "subscriptions/"+(Get-AzContext).Subscription.ID

I believe should read:
$scope = "/subscriptions/"+(Get-AzContext).Subscription.ID

The alert is created, but the scope never appears when you examine the actual rule created.

**Comment by isra-fel** [comment]
@eliot-trustm Thanks for the feedback! The example of which cmdlet were you referring to?

**Comment by isra-fel** [comment]
I searched the code base and found the only match to be [New-AzActivityLogAlert](https://github.com/Azure/azure-powershell/blob/e3f69e8966e8e13f6061f056a2a35221de1969d3/src/Monitor/Monitor/help/New-AzActivityLogAlert.md?plain=1#L30) @VeryEarly can you take a look if we need to update the example? Thanks

**Comment by eliot-trustm** [comment]
I'm referring to "Example 1" here:
https://learn.microsoft.com/en-us/powershell/module/az.monitor/new-azactivitylogalert?view=azps-9.7.1
The first line:
$scope = "subscriptions/"+(Get-AzContext).Subscription.ID
I believe should read:
$scope = "/subscriptions/"+(Get-AzContext).Subscription.ID

**Comment by dolauli** [comment]
The typo has been fixed in https://github.com/Azure/azure-powershell/commit/dd0cef3e86e88004b24261dfc9ade34ee83fab48, which will be released in next version of Az.monitor.
