### ISSUE TITLE
Firewall Rule Creation

### ISSUE THREAD

**Issue by jgnader** [Azure/azure-powershell#21812]
### Description

The Firewall rule creation have a bug when calculating ipv4 range, it says the end ip address is smaller the start ip address, however, its not.

PS /home/azureuser> az postgres flexible-server firewall-rule create --rule-name rule-name --subscription 'xxxxxxxxxxxxxxxxx'  --resource-group xxxxxxx-rg --name name-xxxxxxx --start-ip-address 203.19.50.96 --end-ip-address 203.19.50.111    
The end IP address is smaller than the start IP address.

### Issue script & Debug output

```PowerShell
n/a
```

### Environment data

```PowerShell
n/a
```

### Module versions

```PowerShell
az postgres flexible-server firewall-rule create

Running from Azure Cloud Shell.
```

### Error output

```PowerShell
The end IP address is smaller than the start IP address.
```

**Comment by isra-fel** [comment]
Hi @jgnader , `az postgres flexible-server firewall-rule create` is a command of Azure CLI rather than Azure PowerShell. Please submit the issue to https://github.com/Azure/azure-cli

**Comment by jgnader** [comment]
Hey Liu,

Thank you for the feedback and quick response, I’ll do it.

Regards,
Jean Nader
Platforms Cloud Policy Engineer
ExxonMobil Global Business Center Brasil

Advance your app modernization journey with support from goto/AppConsult<https://gotocloud.xom.cloud/?utm_source=map-bulletin-april&utm_medium=email-signature&utm_campaign=signature-link-cloud>
All the cloud news you can use goto/MAPCommunications<https://gotocloud.xom.cloud/?utm_source=map-bulletin-april&utm_medium=email-signature&utm_campaign=signature-link-cloud>
Start your cloud journey at goto/cloud<https://gotocloud.xom.cloud/?utm_source=map-bulletin-april&utm_medium=email-signature&utm_campaign=signature-link-cloud>
Bring your apps to life with goto/AppsHub<https://appshub.xom.cloud/?utm_source=map-bulletin-april&utm_medium=email-signature&utm_campaign=signature-link-apps-hub>
Learn more about modernization from goto/AppStories<https://gotocloud.xom.cloud/stories/all/?utm_source=map-bulletin-april&utm_medium=email-signature&utm_campaign=signature-link-appstories>
Build secure solutions with goto/AppWiki<https://gotocloud.xom.cloud/cloudwiki/docs/index.html?utm_source=map-bulletin-april&utm_medium=email-signature&utm_campaign=signature-link-appwiki>
