### ISSUE TITLE
[Doc]: Azure AD reports the use of ADAL when using the most recent version of Az.Accounts

### ISSUE THREAD

**Issue by ykuijs** [Azure/azure-powershell#21837]
### Description

I am using Az.Accounts to authenticate to Azure, so I can use Az.KeyVault to retrieve secrets from KeyVault. I am using an app registration to authenticate.

Recently my security department reported that my app registration is authenticating using ADAL and that this must be changed to MSAL.

When checking the changelog of Az.Accounts, it says that ADAL was replaced with MSAL back in 2020 (v2.1.0):
https://github.com/Azure/azure-powershell/blob/e3f69e8966e8e13f6061f056a2a35221de1969d3/src/Accounts/Accounts/ChangeLog.md?plain=1#L233-L235

How is it possible that we can still see ADAL being used? We are the only ones using this app registration and use it with Az.Accounts/KeyVault only.

**Comment by isra-fel** [comment]
Hi @ykuijs what are the versions of Az modules you are using? You can get them by `Get-Module Az* -ListAvailable`.

**Comment by ykuijs** [comment]
We are using v2.12.2, the most recent version.

**Comment by isra-fel** [comment]
@ykuijs that's curious, there's no way the latest Az uses ADAL... do you happen to use AzureRM modules?

Besides, how did the security team identify the usage of ADAL? Could you share more details?
(If there's sensitive information feel free to reach out to us internally).

**Comment by ykuijs** [comment]
I am 100% sure I am using the Az modules.

I am working for a customer on this issue. We are trying to find out how their security department discovered this and get more details. Will follow-up and update you asap!

**Comment by ykuijs** [comment]
The customer was using reports provided by Azure itself. But they heard that the report might contain incorrect data and that support is investigating the correctness of the report.

For now: I assume this issue doesn't exist. If it reappears on future reports, I will reopen this issue.
