### ISSUE TITLE
RP auto-registration should occur when calls fail in new Azure regions

### ISSUE THREAD

**Issue by seanbamsft** [Azure/azure-powershell#2185]
RPRegistrationDelegatingHandler automatically handles the case where a customer cannot use an ARM RP due to a missing registration. However, the error message it looks for does not match the one that occurs if they are missing a registration in a new region. That error message looks like:

`New-AzureRmKeyVault : MissingRegistrationForLocation: The subscription is not registered for the resource type 'vaults' in the location 'ANewAzureRegion'. Please re-register for this provider in order to have access to this location.`

Now that users rarely need to run Register-AzureRmResourceProvider, I think they will be surprised that they need to run it to access new regions.

**Comment by markcowl** [comment]
@seanbamsft That would be an interesting enhancement.

**Comment by markcowl** [comment]
There hasn't been any customer traction on this issue.  Closing for now.  If we have telemetry data that says that customers are hitting this issue, then please reopen and we will revisit
