### ISSUE TITLE
Unable to use Docker container with AzDo pipeline task

### ISSUE THREAD

**Issue by ncostello81** [Azure/azure-powershell#21867]
### Description

Hi folks. Have recently tried to use the `mcr.microsoft.com/azure-powershell` container as a self-hosted containerised agent for Azure Pipelines, and have encountered an issue when used with the [AzurePowerShell Pipelines task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzurePowerShellV5).

The task implicitly requires that modules are installed with the `AllUsers` scope and [assumes the module installation directory to be /usr/share](https://github.com/microsoft/azure-pipelines-tasks/blob/b4efd008952842147176038d8b571ffd7c4a6d8d/Tasks/AzurePowerShellV5/Utility.ps1#L12).

The Docker containers produced from this repo [use InstallModule.ps1 from the blob installer](https://github.com/Azure/azure-powershell/blob/e3f69e8966e8e13f6061f056a2a35221de1969d3/docker/Dockerfile-ubuntu-22.04#L39) to install Azure PowerShell as root, and [InstallModule.ps1 uses the `CurrentUser` scope](https://github.com/Azure/azure-powershell/blob/e3f69e8966e8e13f6061f056a2a35221de1969d3/tools/Installer/InstallModule.ps1#L34). So, the modules install to /root/.local/share, which fails the [Pipeline task validation here](https://github.com/microsoft/azure-pipelines-tasks/blob/b4efd008952842147176038d8b571ffd7c4a6d8d/Tasks/AzurePowerShellV5/Utility.ps1#L92).

Raising this as a question because I can easily build my own container that installs the modules at the correct scope, but I also noticed that [when the Dockerfile is installing an older version of PowerShell, the `AllUsers` scope is used](https://github.com/Azure/azure-powershell/blob/e3f69e8966e8e13f6061f056a2a35221de1969d3/docker/Dockerfile-ubuntu-22.04#L43), so... might be a contradiction? Is the intention for `mcr.microsoft.com/azure-powershell` containers to be ready for use as containerised agents in Azure Pipelines, or...?

**Comment by isra-fel** [comment]
Hey @ncostello81 thanks for reporting.
It looks like a regression of #12972
@Nickcandy could you double check? Thanks.
