### ISSUE TITLE
[Feature]: Update all scenarios that deploy Guest Attestation Extension with enableAutomaticUpgrade = True

### ISSUE THREAD

**Issue by sirfamelin** [Azure/azure-powershell#21866]
### Description of the new feature

Impacted cmdlets:
New-AzVm
New-AzVmss

Problem:
Currently, when the right conditions are met to deploy a Trusted Launch VM, the Guest Attestation Extension (Microsoft.Azure.Security.LinuxAttestation, and Microsoft.Azure.Security.WindowsAttestation) gets deployed along with the rest of the ARM resources automatically without requiring additional parameters from the user. This logic is abstracted from the user interface. However, at the time this logic was implemented, the extension was not onboarded to support enableAutomaticUpgrade, and so the extension deploys without enableAutomaticUpgrade set to true. This means that if there was an update to the extension pushed out by the Azure Core Security Services team (aka my team), the VM would not get the updated extension until the VM's goal state changes (eg. power cycle).

Proposal:
Since we have onboarded to enableAutomaticUpgrade, we would like this logic to be updated to ensure that the enableAutomaticUpgrade field of the extension is switched to true. That way the user would get the latest Guest Attestation Extension at all times without having to powercycle the VM (which for business critical workloads seldom happens). This continuous to improve the security posture for our customers.

**Comment by Sandido** [comment]
@sirfamelin , where is the enableAutomaticUpgrade property on the GA extesion? I see enableAutomaticUpgrade directly on the VirtuleMachineExtension properties, is that right?

**Comment by GabstaMSFT** [comment]
@sirfamelin thank you for raising this, I am looking into this.

**Comment by GabstaMSFT** [comment]
As per discussion with @sirfamelin this has been addressed and is a duplicate request.
