### ISSUE TITLE
HDInsight HBase cluster ARM deployment fails

### ISSUE THREAD

**Issue by chevalpartners** [Azure/azure-powershell#2186]
I tried creating HDInsight Hbsae cluster using this template.
I am using azure powershell idk 1.3.2

https://azure.microsoft.com/en-us/documentation/articles/hdinsight-hadoop-create-linux-clusters-arm-templates/

This template worked for a spark cluster but failed for a Hbase cluster.

Here is the error message:

statusMessage:{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'.","details":[{"code":"InvalidDocumentErrorCode","message":"DeploymentDocument 'CsmDocument_2_0' failed the validation. Error: 'VM size 'Small' provided in the CSM document is invalid or not supported for role 'zookeepernode''"}]}}

My headnote, worker node and zookeeper node are not small. So I am not sure where VM size ‘Small’ is coming from.

Initial template did not even have the zookeeper section so I added it

Here is the configuration for the compute nodes.

```
        {
          "name": "headnode",
          "targetInstanceCount": "2",
          "hardwareProfile": {
            "vmSize": "Large"
          },
          "osProfile": {
            "linuxOperatingSystemProfile": {
              "username": "[parameters('sshUserName')]",
              "password": "[parameters('sshPassword')]"
            }
          },
          "virtualNetworkProfile": {
            "id": "[variables('vnetID')]",
            "subnet": "[variables('subnet1Ref')]"
          }
        },
        {
          "name": "workernode",
          "targetInstanceCount": "[parameters('clusterWorkerNodeCount')]",
          "hardwareProfile": {
            "vmSize": "Standard_D3"
          },
          "osProfile": {
            "linuxOperatingSystemProfile": {
              "username": "[parameters('sshUserName')]",
              "password": "[parameters('sshPassword')]"
            }
          },
          "virtualNetworkProfile": {
            "id": "[variables('vnetID')]",
            "subnet": "[variables('subnet1Ref')]"
          }
        },
        {
          "name": "zookeepernode",
          "minInstanceCount": 1,
          "targetInstanceCount": 3,
          "hardwareProfile": {
            "vmSize": "Large"
          },
          "osProfile": {
            "linuxOperatingSystemProfile": {
              "username": "[parameters('sshUserName')]",
              "password": "[parameters('sshPassword')]"
            }
          },
          "virtualNetworkProfile": {
            "id": "[variables('vnetID')]",
            "subnet": "[variables('subnet1Ref')]"
          },
          "scriptActions": [ ]
        }
```

**Comment by PandoraDirge** [comment]
As Keithyau said one year ago: Same issue....
Any solutions?

My problem is very similar but I tried to de-escalate the HDinsight cluster....
This is my error:
 {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "InvalidDocumentErrorCode",
        "message": "DeploymentDocument 'CsmDocument_2_0' failed the validation. Error: 'VM size 'medium' provided in the CSM document is invalid or not supported for role 'headnode''"
      }
    ]
  }
} undefined

**Comment by cormacpayne** [comment]
@momusoru @z01c @wawon-msft would you mind taking a look at this issue?

**Comment by aim-for-better** [comment]
Hi @PandoraDirge @keithyau, Could you please give me more information about the HDInsight Version, HBbase version? Can you try to create the same type cluster with other vm types as head node by using the latest PowerShell module Az.HDInsight?

**Comment by aim-for-better** [comment]
Hi @PandoraDirge @keithyau, Could you please give me more information about the HDInsight Version, HBbase version? Can you try to create the same type cluster with other vm types as head node by using the latest PowerShell module Az.HDInsight?

**Comment by PandoraDirge** [comment]
Sorry, but at the end we leaved things are they were... beacuse we can't find a solution.... 
Also, nowadays I can't do any tests with it.
Sorry...

**Comment by aim-for-better** [comment]
Customer don't need to investigate this issue. And HDInsight have made so many changes since 2016. Customer can use the newest HDInsight cluster.
