### ISSUE TITLE
Change Import-AzureRmAutomationRunbook -Type parameter value from "Graph" to "Graphical"

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2187]
The `-Type` parameter on `Import-AzureRmAutomationRunbook` has a value of `Graph` instead of `Graphical`. This should be fixed for consistency of user experience.

![image](https://cloud.githubusercontent.com/assets/466713/14937634/21f3a22c-0ecb-11e6-8efb-d8f47bdcca48.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by andyw248** [comment]
Triaged: Az cmdlet has both. Graph has been preserved for backward compatibility. Resolved.
