### ISSUE TITLE
-Tags parameter is broken on New-AzureRmAutomationAccount

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2188]
1. It's a Dictionary, but should be a HashTable array instead, just like all other ARM resources.
2. Consider keeping `-Tag` or `-Tags` consistent amongst all ARM commands

![image](https://cloud.githubusercontent.com/assets/466713/14937774/0ee34cf6-0ecf-11e6-906a-0bc129f54ceb.png)

![image](https://cloud.githubusercontent.com/assets/466713/14937783/33d26c86-0ecf-11e6-9057-2959f6dd6195.png)

@markcowl @jodoglevy 

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 @jodoglevy We're looking at normalizing the Tags parameters across the AzureRM cmdlets in 2 releases.

**Comment by cormacpayne** [comment]
Closing as this is fixed.
