### ISSUE TITLE
The parameter "StartHourUtc" for the command "New-AzRedisCacheScheduleEntry" takes 12 hours format or 24 hours format

### ISSUE THREAD

**Issue by amkarmak** [Azure/azure-powershell#21887]
### Description

The parameter "StartHourUtc" for the command "New-AzRedisCacheScheduleEntry" takes 12 hours format or 24 hours format?

From the below command, which one will work?

New-AzRedisCacheScheduleEntry -DayOfWeek "Weekend" -StartHourUtc 5pm -MaintenanceWindow "06:00:00"
or
New-AzRedisCacheScheduleEntry -DayOfWeek "Weekend" -StartHourUtc 17 -MaintenanceWindow "06:00:00"

**Comment by SaurabhSharma-MSFT** [comment]
@amkarmak We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@amkarmak It will be a 24 hour format. As per the [New-AzRedisCacheScheduleEntry documentation](https://learn.microsoft.com/en-us/powershell/module/az.rediscache/new-azrediscachescheduleentry?view=azps-10.0.0),  -StartHourUtc will take an Int32.  Refer to the example as well which is using an integer.
