### ISSUE TITLE
Design problem with ARM Resource Lock commands

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2189]
The commands in the `AzureRM.Resources` PowerShell module use the `-LockName` parameter, instead of the `-Name` parameter, thereby making it redundant. Please change `-LockName` to  `-Name`. This is a long-standing principle in PowerShell command design.

![image](https://cloud.githubusercontent.com/assets/466713/14939766/ccf6fa60-0f12-11e6-9d98-91eac9377a8e.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@ravbhatnagar Can you take a look?

**Comment by ravbhatnagar** [comment]
There are some other issues we encountered while fixing this. We will fix this along with the other issues in the July release.

**Comment by cormacpayne** [comment]
@ravbhatnagar Hey Gaurav, did this issue get fixed during the latest release?

**Comment by ravbhatnagar** [comment]
Fixed
