### ISSUE TITLE
Az.Storage: Replicating the functionality of Get-AzStorageFileContent -PreserveSMBAttribute on Linux

### ISSUE THREAD

**Issue by olegvm** [Azure/azure-powershell#21894]
### Description

We are reading file information from Azure Storage account using [Get-AzStorageFileContent](https://learn.microsoft.com/en-us/powershell/module/az.storage/get-azstoragefilecontent?view=azps-9.7.1). It includes the `-PreserveSMBAttribute` switch parameter, which allows us to retain existing attributes (including last modification date) for all the files.

```
Get-AzStorageFileContent -Context $Context -ShareName $functionAppName -Path $($zipDeployFile.ShareFileClient.Path) -Destination "$deployedArtifactFilePath" -Force -PreserveSMBAttribute
```

However, this parameter only works on Windows and causes an exception on Linux agents. Due to certain requirements, we need to run the pipeline on Linux agents. We would like to preserve file attributes when reading file content (for comparison/validation purposes).

Is there a way to replicate the functionality of `Get-AzStorageFileContent -PreserveSMBAttribute` parameter on Linux?

### Script or Debug output

```PowerShell
Downloading data/SitePackages/20230519140250.zip to /agent/_work/1/s\zipDeployPackage\20230519140250.zip
Get-FunctionAppMetrics: /agent/_work/1/s/CI/drop/PipelineScripts/ourCustomScript.ps1:49
Line |
  49 |      $functionAppMetrics = Get-FunctionAppMetrics `
     |                            ~~~~~~~~~~~~~~~~~~~~~~~~
     | A parameter cannot be found that matches parameter name
     | 'PreserveSMBAttribute'.
```

**Comment by blueww** [comment]
@olegvm 

`-PreserveSMBAttribute` can preserve: File Attributtes, File Creation Time, File Last Write Time.
Would you please share the detail scenario you need preserve the attributes on Linux, and which of the 3 attributes you would like to preserve? 
Currently the parameter only available on Windows, since some of the attributes to preserve only support Windows (this limitation is in rest API design, not in Powershell).

If you just need same script works on both windows and Linux, you can only add the parameter on Windows like following. 
```
if ((Get-ChildItem -Path Env:OS).value -like "Windows*")
{
    Get-AzStorageFileContent -Context $Context -ShareName $functionAppName -Path $($zipDeployFile.ShareFileClient.Path) -Destination "$deployedArtifactFilePath" -Force -PreserveSMBAttribute
}
else
{
    Get-AzStorageFileContent -Context $Context -ShareName $functionAppName -Path $($zipDeployFile.ShareFileClient.Path) -Destination "$deployedArtifactFilePath" -Force 
}
```

**Comment by olegvm** [comment]
@blueww, thanks for your reply.

We use only the "Last modified time" attribute - "File attributes" and "Creation time" are not used. "Last modified time" is used as part of metrics which are compared against previously stored metrics (which also include File sizes and File count).

It seems that "Last modified time" could be acquired by a separate invocation of [Get-AzStorageFile](https://learn.microsoft.com/en-us/powershell/module/az.storage/get-azstoragefile?view=azps-9.7.1) - would this be a suggested approach?

**Comment by blueww** [comment]
@olegvm 

Thanks for the sharing!

Yes, run `Get-AzStorageFile` and see the "LastModified" of the output file object , can get the file "Last modified time" .

As we still have many other new features in hand, and we can't simply port the -PreserveSMBAttribute on Linux per server limitation, and there's workaround, we will not priority this request.
Feel free to let me know if you have any comments or concern.

**Comment by navba-MSFT** [comment]
@olegvm Hope you had a chance to look at the above comment. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
