### ISSUE TITLE
Help issues with Remove-AzureRmResourceLock

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2190]
1. Syntax section doesn't mention `-LockName` parameter
2. `-LockName` help is completely missing from help
3. Syntax Section: Some parameters are shown as mandatory, that aren't
4. Parameter help needs more work / clarity

![image](https://cloud.githubusercontent.com/assets/466713/14939805/295cf6c8-0f14-11e6-9ac8-3bccbf17ef1c.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@ravbhatnagar Can you take a look?

**Comment by ravbhatnagar** [comment]
There were some other issues encountered with the Lock cmdlets. We will fix those and update the help in the next release.

**Comment by cormacpayne** [comment]
@ravbhatnagar Hey Gaurav, did this issue get fixed in the latest release?

**Comment by ravbhatnagar** [comment]
Fixed in Aug release.
