### ISSUE TITLE
The -LockLevel parameter on New-AzureRmResourceLock shouldn't be mandatory

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2191]
This parameter only has **one** value that can be specified, for the time being. Let's make this non-mandatory, and set a default value, instead of making it a mandatory parameter. A rather poor user experience right now, but an easy fix thankfully! :smile: @markcowl 

![image](https://cloud.githubusercontent.com/assets/466713/14940040/8cb8c1e6-0f20-11e6-8629-106088c43ba1.png)

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@ravbhatnagar Can you take a look?

**Comment by ravbhatnagar** [comment]
#384 
@pcgeek86 - We are planning to support other lock levels in the client as well as mentioned in the referenced issue. So I am closing this issue. Please let me know if you think otherwise
