### ISSUE TITLE
Authenticate as service principal with certificate

### ISSUE THREAD

**Issue by vicperdana** [Azure/azure-powershell#2192]
Encountered this issue when using the following PS cmdlet (version 1.3.2) to authenticate with cert
Login-AzureRmAccount -CertificateThumbprint $cert.Thumbprint -ApplicationId $appId -ServicePrincipal -TenantId $subscription.TenantId

I got this error instead: 
Login-AzureRmAccount : 'authority' should be in Uri format
Parameter name: authority
At line:1 char:1
- Login-AzureRmAccount -CertificateThumbprint $cert.Thumbprint -Applica ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], ArgumentException
  - FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

Doing the same in CLI resolved the issue.  Is this a known issue?
azure login --service-principal --tenant $tenantid -u $appid --certificate-file "<path to PEM file\vicprhel.pem" --thumbprint $cert
info: Executing command login
-info: Added subscription subscription
info: Setting subscription "subscription" as default
+
info: login command OK

**Comment by markcowl** [comment]
@vicperdana Azure PowerShell requires that the certificate is installed in the Current User or LocalMachine 'My' store (which is obviously not available for a cross-platform cli).

If you have done this and are still seeing issues, please rerun your login with $DebugPreference="Continue" and include the resulting debug log.

**Comment by vicperdana** [comment]
Just installed the cert in My store (run get-childitem -path cert:\currentuser\my\ to confirm), still rendered the same result. Here's the Debug log. 

BUG: 7:02:03 AM - AddAzureRMAccountCommand begin processing with ParameterSet 'ServicePrincipalCertificate'.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 2/05/2016 9:02:03 PM:  - TokenCache: Deserialized 3 items to token cache.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain:
'string[]9966bc97-2bd3-4d2c-b85c-455673bfb10d ab1cb3b4-b195-48d8-a359-8ce84148f5f4.TenantId', Endpoint:
'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect:
'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
Login-AzureRmAccount : 'authority' should be in Uri format
Parameter name: authority
At line:1 char:1
+ Login-AzureRmAccount -CertificateThumbprint $cert.Thumbprint -Applica ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

DEBUG: AzureQoSEvent: CommandName - Add-AzureRmAccount; IsSuccess - False; Duration - 00:00:00.0340119; Exception -
System.ArgumentException: 'authority' should be in Uri format
Parameter name: authority
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Authenticator.DetectAuthorityType(String authority)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Authenticator..ctor(String authority, Boolean validateAuthority)
   at Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.GetContext(AdalConfiguration
config)
   at
Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.AcquireTokenWithCertificate(AdalConfigurat
ion config, String appId, String thumbprint)
   at
Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.GetAccessTokenWithCertificate(AdalConfigur
ation config, String clientId, String certificateThumbprint, AccountType credentialType)
   at Microsoft.Azure.Commands.Common.Authentication.AdalTokenProvider.GetAccessTokenWithCertificate(AdalConfiguration
config, String clientId, String certificate, AccountType credentialType)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(AzureAccount account,
 AzureEnvironment environment, String tenant, SecureString password, ShowDialog promptBehavior, TokenCache tokenCache,
Endpoint resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(AzureAccount account,
AzureEnvironment environment, String tenantId, SecureString password, ShowDialog promptBehavior)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(AzureAccount account, AzureEnvironment
environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password)
   at Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 7:02:04 AM - AddAzureRMAccountCommand end processing.
DEBUG: 7:02:04 AM - AddAzureRMAccountCommand end processing.

**Comment by markcowl** [comment]
@vicperdana Can you provide the command line that you used for this as well? It looke liek the tenant id is in the wrong format, from this value in the trace:

```string[]9966bc97-2bd3-4d2c-b85c-455673bfb10d ab1cb3b4-b195-48d8-a359-8ce84148f5f4.TenantId'```

**Comment by vicperdana** [comment]
@markcowl saw that and modified the command, and here's the command and resulting debug logs. 
Login-AzureRmAccount -CertificateThumbprint $cert.Thumbprint -ApplicationId $azurermAdApplication.ApplicationId -ServicePrincip
al -TenantId $str

DEBUG: 2:33:08 PM - AddAzureRMAccountCommand begin processing with ParameterSet
'ServicePrincipalCertificate'.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 3/05/2016 4:33:08 AM:  - TokenCache: Deserialized 3 items to token cache.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain:
'1262ba02-2841-44ff-8cc7-f958193a1727', Endpoint: 'https://login.microsoftonline.com/', ClientId:
'1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob',
ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 3/05/2016 4:33:08 AM: 0eed4c33-e6c3-4740-a71f-3e77cf18f830 - AcquireTokenHandlerBase: === Token
 Acquisition started:
 Authority: https://login.microsoftonline.com/1262ba02-2841-44ff-8cc7-f958193a1727/
 Resource: https://management.core.windows.net/
 ClientId: 53e340c8-d662-4852-a253-99bd59a4e8ba
 CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (3 items)
 Authentication Target: Client

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 3/05/2016 4:33:08 AM: 0eed4c33-e6c3-4740-a71f-3e77cf18f830 - TokenCache: Looking up cache for a
 token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 3/05/2016 4:33:08 AM: 0eed4c33-e6c3-4740-a71f-3e77cf18f830 - TokenCache: No matching token was
found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Error: 4 :
DEBUG: 3/05/2016 4:33:08 AM: 0eed4c33-e6c3-4740-a71f-3e77cf18f830 - <RunAsync>d__0:
System.Security.Cryptography.CryptographicException: Invalid provider type specified.

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean
randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters
parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle,
SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters
parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.GetAsymmetricAlgorithm(String algorithm,
Boolean privateKey)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.SignWithCertificate(String
message, X509Certificate2 x509Certificate)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.JsonWebToken.Sign(ClientAssertionCertificate
credential)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.RequestParameters.AddClientKey(ClientKey
clientKey)
   at
Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__9.Mo
veNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at
Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
Login-AzureRmAccount : Invalid provider type specified.
At line:1 char:1
+ Login-AzureRmAccount -CertificateThumbprint $cert.Thumbprint -Applica ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], CryptographicException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

DEBUG: AzureQoSEvent: CommandName - Add-AzureRmAccount; IsSuccess - False; Duration -
00:00:00.0646290; Exception - System.Security.Cryptography.CryptographicException: Invalid provider
type specified.

   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1
task)
   at
Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.AcquireTokenWithCertifica
te(AdalConfiguration config, String appId, String thumbprint)
   at
Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.GetAccessTokenWithCertifi
cate(AdalConfiguration config, String clientId, String certificateThumbprint, AccountType
credentialType)
   at
Microsoft.Azure.Commands.Common.Authentication.AdalTokenProvider.GetAccessTokenWithCertificate(AdalCon
figuration config, String clientId, String certificate, AccountType credentialType)
   at
Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(AzureAccou
nt account, AzureEnvironment environment, String tenant, SecureString password, ShowDialog
promptBehavior, TokenCache tokenCache, Endpoint resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(AzureAccount
account, AzureEnvironment environment, String tenantId, SecureString password, ShowDialog
promptBehavior)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(AzureAccount account,
AzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName,
SecureString password)
   at Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 2:33:11 PM - AddAzureRMAccountCommand end processing.
DEBUG: 2:33:11 PM - AddAzureRMAccountCommand end processing.

**Comment by markcowl** [comment]
@vicperdana This looks like an error with the certificate itself.  Is the private key included and is it accessible to the logged-on user?

**Comment by vicperdana** [comment]
@markcowl I have granted full access to the logged on user to the cert's private key but unfortunately stll getting the same error.

**Comment by markcowl** [comment]
solved offline through use of this script:  https://apac01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgist.github.com%2fdevigned%2fdae74a7ca54000f7b714&data=01%7c01%7cvicky.perdana%40kloud.com.au%7c9f8c2edd6c3949a535c908d37da6a689%7c23ae57df8a51444aa59a328118705efc%7c1&sdata=eAnyPPzYnutuJYwsw%2fvWjqIaluaMAwZ2Q1AHRTnQTJY%3d

So closing

**Comment by thatnerdyguy** [comment]
FYI, for future googbingers, I solved this by making sure to call New-SelfSignedCertificate with -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider", as mentioned [here](https://blogs.technet.microsoft.com/keithmayer/2016/03/26/8-steps-for-using-azure-ad-service-principal-certificate-authentication-with-azure-automation-powershell-workflow-runbooks/)

**Comment by sazeesha** [comment]
Reopening: the same issue as above but I am able to login with PoweShell but not with the Microsoft.Azure.Management.Compute.Fluent Nuget 

  AzureEnvironment dogFood = new AzureEnvironment();
            dogFood.ManagementEnpoint = "https://management.core.windows.net/";
            dogFood.AuthenticationEndpoint = "https://login.windows-ppe.net/";
            dogFood.ResourceManagerEndpoint = "https://api-dogfood.resources.windows-int.net/";
            dogFood.GraphEndpoint = "https://graph.ppe.windows.net/";

 var credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal(addId, cers[0], tennId, dogFood);

**Comment by sazeesha** [comment]
var azure = Azure
                .Configure()
                .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
                .Authenticate(credentials)
                .WithDefaultSubscription();

the above code throws Argument exception: {"'authority' should be in Uri format\r\nParameter name: authority"}

**Comment by cormacpayne** [comment]
@sazeesha closing as the PowerShell issue is resolved. Please open an issue in the Azure SDK for .NET repository with the Fluent label.
