### ISSUE TITLE
Import-AzureRmAutomationDscConfiguration exception 

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2195]
- Azure Automation is in GA, not Preview
- DSC Configurations (AFAIK) don't have a "published" state like Runbooks do

> Import-AzureRmAutomationDscConfiguration : Configuration can be imported in published state only in the current preview. Use the -Published switch.

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by maddieclayton** [comment]
@vrdmr Is this still an issue in today's version? If not, please close this issue.

**Comment by GaneshMSAzure** [comment]
Doc is fixed. 
https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/import-azurermautomationdscconfiguration?view=azurermps-6.13.0
