### ISSUE TITLE
Inconsistency :: Start-AzureRmAutomationRunbook has -Wait parameter, but Start-AzureRmAutomationDscCompilationJob doesn't

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2197]
# Issue

Start-AzureRmAutomationRunbook has -Wait parameter, but Start-AzureRmAutomationDscCompilationJob doesn't
# Root Cause

Inconsistency between commands managing various job types in Azure Automation.
# Expected Result

Consistency between commands in Azure Automation. Commands that invoke a background job should all share a somewhat similar interface. If `-Wait` is supported on one `Start` command, then it should be supported on other `Start` commands as well.

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by pcgeek86** [comment]
@jodoglevy @markcowl Any thoughts folks?

**Comment by jodoglevy** [comment]
I don't disagree @pcgeek86, but this is currently low priority I think, because you can do the same waiting with a while loop. I will open a bug internally to track though.

**Comment by maddieclayton** [comment]
@vrdmr @jodoglevy Was this issue resolved?  If you do not plan to fix this, please close this issue.

**Comment by Xergy** [comment]
I'd really this functionality too.  I wasted time researching this and writing a work around.  I really like the -wait command.

**Comment by GaneshMSAzure** [comment]
Won't fix
