### ISSUE TITLE
Get-AzureRMTrafficManagerProfile returns Endpoints as string

### ISSUE THREAD

**Issue by psap** [Azure/azure-powershell#2198]
**Version: 1.3.2**
# What I am trying to do:  Get the Azure TrafficManager profile and query the status of each endpoint

$profile = Get-AzureRmTrafficManagerProfile -Name "myProfileName" -ResourceGroupName "myResGroup"

$ep = $profile.Endpoints[0]
$ep.endpointStatus
# 

I get the profile, but the endpoints are being returned as "Strings" and not as objects. Running my script in debug mode, I am able to see the correct values returned. But it looks like the conversion has an issue and the final result is being returned as a string.

**Comment by markcowl** [comment]
@psap Can you please add in the debug stream messages you captured, this will go a long way toward pinpointing the issue

**Comment by psap** [comment]
[debugResponse.txt](https://github.com/Azure/azure-powershell/files/246188/debugResponse.txt)
attached. I have masked some of the subscription details

**Comment by carlocardella** [comment]
I was able to repro, now looks like it's working fine with AzureRM.Profile version 2.3.0

**Comment by cormacpayne** [comment]
Closing this issue as it appears to have been resolved.
