### ISSUE TITLE
AzureRM.Storage.ps1is missing Set-AzureRmStorageAccount cmdlet.

### ISSUE THREAD

**Issue by hyonholee** [Azure/azure-powershell#2202]
Also, Type parameter for New-AzureRmStorageAccount does not set the type properly.  (It always set the type Standard_LRS.

This missing feature causes VMDynamic live test in Compute test project, because this test contains the following lines.

New-AzureRmStorageAccount -ResourceGroupName $rgname -Name $stoname -Location $loc -Type $stotype;
Set-AzureRmStorageAccount -ResourceGroupName $rgname -Name $stoname -Tags $tags

**Comment by markcowl** [comment]
### Proposed Solution

Add minimal support for account type and tags  in Set-* and New-AzureRmStorageAccount

### Cost (Work Units): 2
