### ISSUE TITLE
"galleryEndpoint" won't be available for ARM metadata endpoint 2020-09-01

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-powershell#22037]
### Description

`galleryEndpoint` won't be available for ARM metadata endpoint 2020-09-01. We also have an on-premises environment that does not provide a `galleryEndpoint`. If you try to use the old API version before 2020-09-01, you would get an empty string for the `galleryEndpoint`. Creating this task as a heads up as the new metadata endpoint is not released yet. I am wondering what the requirements are for removing the `galleryEndpoint` check from the Azure PowerShell code here:
https://github.com/Azure/azure-powershell/blob/8f5c977c1afe76bf940e7e0956ec0ffd2f1980a8/src/Accounts/Accounts/Utilities/EnvironmentHelper.cs#L78

I understand there might be potential issues with some code requiring a Gallery endpoint. But since newer code in development will not require this, would it be better to defer such requirements to the specific code that requires it? For example, remove the `galleryEndpoint` requirement check and move it to the part of the code that actually uses it. Also, according to my discussion with the ARM team in the past, they don't seem to have a contract for what should be expected from the ARM metadata endpoint.

**Comment by isra-fel** [comment]
Thanks for the heads up.
@msJinLei can you take a look and let’s discuss how to follow up? Thank you.

**Comment by msJinLei** [comment]
@TheOnlyWei the current response is

```json
[{"portal":"https://portal.azure.com","authentication":{"loginEndpoint":"https://login.microsoftonline.com/","audiences":["https://management.core.windows.net/","https://management.azure.com/"],"tenant":"common","identityProvider":"AAD"},"media":"https://rest.media.azure.net","graphAudience":"https://graph.windows.net/","graph":"https://graph.windows.net/","name":"AzureCloud","suffixes":{"azureDataLakeStoreFileSystem":"azuredatalakestore.net","acrLoginServer":"azurecr.io","sqlServerHostname":"database.windows.net","azureDataLakeAnalyticsCatalogAndJob":"azuredatalakeanalytics.net","keyVaultDns":"vault.azure.net","storage":"core.windows.net","azureFrontDoorEndpointSuffix":"azurefd.net"},"batch":"https://batch.core.windows.net/","resourceManager":"https://management.azure.com/","vmImageAliasDoc":"https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json","activeDirectoryDataLake":"https://datalake.azure.net/","sqlManagement":"https://management.core.windows.net:8443/","gallery":"https://gallery.azure.com/"},{"portal":"https://portal.azure.cn","authentication":{"loginEndpoint":"https://login.chinacloudapi.cn","audiences":["https://management.core.chinacloudapi.cn","https://management.chinacloudapi.cn"],"tenant":"common","identityProvider":"AAD"},"media":"https://rest.media.chinacloudapi.cn","graphAudience":"https://graph.chinacloudapi.cn","graph":"https://graph.chinacloudapi.cn","name":"AzureChinaCloud","suffixes":{"acrLoginServer":"azurecr.cn","sqlServerHostname":"database.chinacloudapi.cn","keyVaultDns":"vault.azure.cn","storage":"core.chinacloudapi.cn","azureFrontDoorEndpointSuffix":""},"batch":"https://batch.chinacloudapi.cn","resourceManager":"https://management.chinacloudapi.cn","vmImageAliasDoc":"https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json","sqlManagement":"https://management.core.chinacloudapi.cn:8443","gallery":"https://gallery.chinacloudapi.cn"},{"portal":"https://portal.azure.us","authentication":{"loginEndpoint":"https://login.microsoftonline.us","audiences":["https://management.core.usgovcloudapi.net","https://management.usgovcloudapi.net"],"tenant":"common","identityProvider":"AAD"},"media":"https://rest.media.usgovcloudapi.net","graphAudience":"https://graph.windows.net","graph":"https://graph.windows.net","name":"AzureUSGovernment","suffixes":{"acrLoginServer":"azurecr.us","sqlServerHostname":"database.usgovcloudapi.net","keyVaultDns":"vault.usgovcloudapi.net","storage":"core.usgovcloudapi.net","azureFrontDoorEndpointSuffix":""},"batch":"https://batch.core.usgovcloudapi.net","resourceManager":"https://management.usgovcloudapi.net","vmImageAliasDoc":"https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json","sqlManagement":"https://management.core.usgovcloudapi.net:8443","gallery":"https://gallery.usgovcloudapi.net"}]
```

Do you mean that `"gallery":"https://gallery.usgovcloudapi.net"` will be `"gallery":""`?

**Comment by TheOnlyWei** [comment]
Hi @msJinLei, the 2020-09-01 API that we use on a new on-premises environment currently doesn't have `galleryEndpoint` or `gallery`. On top of that, older API versions of ARM metadata endpoint (e.g., `1.0`) will have an empty string value for `galleryEndpoint`.

I am also verifying with the owners of when or why gallery endpoint in general is no longer available in newer versions. Do you guys have any intention of updating the ARM metadata API version from `1.0`? 
https://github.com/Azure/azure-powershell/blob/8f5c977c1afe76bf940e7e0956ec0ffd2f1980a8/src/Accounts/Accounts/Utilities/EnvironmentHelper.cs#LL61C87-L61C87

In the newer API versions, the `galleryEndpoint` seems to have become `gallery`. The reason I created this issue is because `Add-AzEnvironment -ARMEndpoint` code fails due to `galleryEndpoint` from ARM metadata API version 1.0 being empty string as evident from the code here:
https://github.com/Azure/azure-powershell/blob/8f5c977c1afe76bf940e7e0956ec0ffd2f1980a8/src/Accounts/Accounts/Utilities/EnvironmentHelper.cs#L78

I also noticed a confusing usage of `-ARMEndpoint` and `-ResourceManagerEndpoint`. The reason this was confusing was because currently, there isn't a distinction between the two from our side (Azure Stack Hub), but it seems Azure PowerShell team sees them with two distinct meanings. So, I thought the two were aliases, but they actually belong to separate parameter sets as is evident from the following doc:
https://learn.microsoft.com/en-us/powershell/module/az.accounts/add-azenvironment?view=azps-10.0.0

So, for our issue, it seems the work-around is to use `Add-AzEnvironment -ResourceManagerEndpoint`. Ideally, the new environment we are developing should have parity with Azure Cloud as much as possible and the `MetadataParameterSet` parameter set should work for our environment as well. But currently the `MetadataParameterSet` specified by `-ARMEndpoint` parameter won't work because our on-premises environment currently returns an empty string for ARM metadata API version `1.0`. We will get back to your team after I get more information on timeline and reasoning why we no longer have the gallery endpoints.

**Comment by TheOnlyWei** [comment]
Hi @msJinLei, do you know what gallery endpoint is being used for currently in Azure?

**Comment by msJinLei** [comment]
> Hi @msJinLei Lei Jin FTE, do you know what the gallery endpoint is being used for currently for the Azure Cloud?

I have no idea who is using the gallery endpoint. It is not used in Azure PowerShell modules. However, as the Gallery Endpoint is a public property, our customer may use it by themselves. We are not able to remove it immediately. We will send the notification first and remove it in the breaking change release.

**Comment by msJinLei** [comment]
@TheOnlyWei  One more question, if the customer want to use gallery endpoint after it is removed from ARM metadata, where can they find it?

**Comment by TheOnlyWei** [comment]
@msJinLei is it possible to make gallery endpoint optional instead of throwing an error? That way it can be set if the user wants to or if the ARM metadata endpoint version `1.0` has it. This way, the change is passive.
