### ISSUE TITLE
[Doc]: 

### ISSUE THREAD

**Issue by NoorKhaldi** [Azure/azure-powershell#22069]
### Description

In Example 3: Connect to Azure using a service principal account: [example 3: ](https://learn.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-10.0.0#example-3-connect-to-azure-using-a-service-principal-account)

![image](https://github.com/Azure/azure-powershell/assets/78817895/0b804496-2065-444a-bb2a-5a8e27160c2f)

Can we explain that users need to first define the client ID and Password string, and that the password must be first stored as a secure string too?

A better example would be as follow:

```
$TenantID = '<TenantID>'
$ApplicationId = '<Application(Client)ID>'
$SecuredPassword = '<ClientSecret>' | ConvertTo-SecureString -AsPlainText -Forc
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $ApplicationId, $SecuredPassword
Connect-AzAccount -EnvironmentName AzureCloud -ServicePrincipal -Credential $Credential -Tenant $TenantID
```

**Comment by NoorKhaldi** [comment]
Hello Yeming,

I’ve never used Github or updated reops before, I don’t want to mess things up so feel free to do this from your side 😊

Happy to answer any questions related to PowerShell though.

Thanks,

Noor Khaldi
Support Escalation Engineer
Azure Rapid Response – Identity
Office: +962 (6) 5503430
Working Hours: Sun-Thu 9AM-6PM (UTC+3)
Need help outside of my working hours?
Locate an engineer: ***@***.******@***.***>
Manager: Sofia Alves / ***@***.******@***.***>
***@***.***

**Comment by isra-fel** [comment]
Got it. No problem.
@msJinLei could you please update the example of `Connect-AzAccount` in this sprint? Thanks.

**Comment by msJinLei** [comment]
@NoorKhaldi @isra-fel could help to review the PR https://github.com/Azure/azure-powershell/pull/22158

**Comment by msJinLei** [comment]
Fixed
