### ISSUE TITLE
[Feature]: Update Set-AzVMAccessExtension to support new parameters

### ISSUE THREAD

**Issue by mayankdaruka-msft** [Azure/azure-powershell#22094]
### Description of new parameters to add

Currently, the only parameters supported for the public/protected settings are UserName and Password, which are retrieved from the PSCredential parameter (https://learn.microsoft.com/en-us/powershell/module/az.compute/set-azvmaccessextension?view=azps-10.0.0).

However, VMAccess **Linux** supports more parameters, including:
- _check_disk_ and _repair_disk_ in the **public** configuration
- _ssh_key_, _reset_ssh_,  _remove_user_, and _expiration_ in **protected** configuration

(Link to view more details - https://github.com/Azure/azure-linux-extensions/tree/master/VMAccess)

Types for each new parameter:
- _check_disk_: bool
- _repair_disk_: bool
- _ssh_key_: str
- _reset_ssh_: bool
- _remove_user_: str
- _expiration_: str

As mentioned above, these parameters should only be added for the Linux version of VMAccess. The username and password settings are common to both Windows and Linux and will remain that way.

**Comment by GabstaMSFT** [comment]
@mayankdaruka-msft I am currently looking into this.

**Comment by GabstaMSFT** [comment]
Closing this issue as it is being taken up by the PowerShell team in another thread.  https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1351
