### ISSUE TITLE
[Doc]: set-azsecurityalert - only locations are 'centralus, westeurope'

### ISSUE THREAD

**Issue by mundayn** [Azure/azure-powershell#22095]
### Description

Hi,

I believe it would be useful to add a note into the documentation that this command is only for use within 'centralus, westeurope', as this is where the Security Workspace(?) I assume is located for Defender in the commercial cloud.

Took a while for me to figure out why this was not working for -Location "Canada Central" and had to use "-Location "centralus"

https://learn.microsoft.com/en-us/powershell/module/az.security/set-azsecurityalert?view=azps-10.0.0

Have a great day!

###

Side note, this thread may pop up on google and help someone else, here is a quick way to dismiss many alerts after a security incident as I could not see a quick way to do this from my research.

$AllAlerts = Get-AzSecurityAlert | Where {$_.Status -ne "Dismissed"}

ForEach ($Alert in $AllAlerts) {
    
    $RG = $Alert.ResourceIdentifiers.AzureResourceId -split("/") | Select-Object -Index 4
    Set-AzSecurityAlert -Location "centralus" -ResourceGroupName $RG -Name $Alert.Name -ActionType Dismiss

}

**Comment by isra-fel** [comment]
Thanks for the feedback!
The regions where a service is available may be subject to change, but documents are static, that's why we don't tend to add such dynamic information in the reference docs.
