### ISSUE TITLE
Can't index into Storage Account Keys using string

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2212]
# Issue

The output from `Get-AzureRmStorageAccountKey` clearly indicates that there are two "keys" along with their corresponding values. When I try to index into the dictionary, it fails to retrieve the value.

```
$StorageKey = Get-AzureRmStorageAccountKey -ResourceGroupName foo -Name bar;
$StorageKey['key1'] -eq $null;

### Return value: True
```

![image](https://cloud.githubusercontent.com/assets/466713/15036683/d6c1102c-124f-11e6-98bc-54bf62cf4ef9.png)

# Expected Result

I should be able to index into the array of keys, using the key's name (string). It looks like a dictionary, but doesn't index like a dictionary.

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by blueww** [comment]
Which version of PowerShell are you using?
If it's the latest one, the return value from Get-AzureRmStorageAccountKey are list of keys. each key has KeyName and Value.
So you can get the key value by:
$storageKey = (Get-AzureRmStorageAccountKey -StorageAccountName $storageAccountName -ResourceGroup $ResourceGroupName).Value[0] 

Value[0] is key1, and Value[1] is key2

**Comment by pcgeek86** [comment]
I'm using PowerShell 5.0. 

Yes, your example would theoretically work, but that's indexing into an array. The output of `Get-AzureRmStorageAccountKey` is *displaying* an object that "looks and feels" like a dictionary, but actually isn't. If it were actually a dictionary, then I could index into it using the key. The problem is that there's a disparity between what's being displayed to the end user, and how the interface works.

@markcowl

**Comment by blueww** [comment]
If you look at the SRP SDK code, you can see the return value is in type: 
`IList<StorageAccountKey>`

And StorageAccountKey class has following members:
```
public class StorageAccountKey
{
...
public string KeyName { get; }
public KeyPermission? Permissions { get; }
public string Value { get; }
}
```

In out code, we just print the returned value without any wrap like following (@markcowl does one SDK team do any wrap?), I am not sure why you think it look like a dictionary. 

```
KeyName Value	 	Permissions
------- -----		-----------
key1    [key1 value]        FULL
key2    [key2 value]        FULL
```

**Comment by pcgeek86** [comment]
Sorry, this might be me misunderstanding something, but I think the solution here would be to implement the `IDictionary` interface, which would enable indexing via the key.

To me, it _looks_ like a Dictionary, because it has a "key" and a "value." Given this, we should probably make sure that it functions similar to a dictionary. Can we get the `IDictionary` interface implemented for this class?

**Comment by blueww** [comment]
Generally, PowerShell don't wrap the output from SDK for extendable and maintainable consideration. (And for customer who are family with SDK, it might be wired to wrap the output)
We don't receive other customer feedback to make the output like Dictionary till now.
If we change that, other customer might will complain.

And for "key" and "value", they are actually "KeyName" and "Value", and has a 3rd property "Permission", which are all different from Dictionary.

I can record it , and  prioritize it if more customer request on it.

**Comment by pcgeek86** [comment]
Shouldn't we call `KeyName` just `Name` instead? The data model is named `Microsoft.Azure.Management.Storage.Models.StorageAccountKey`, so it is redundant to have a property `KeyName`, when it's really just the `Name` of the object.

Same goes for Storage Accounts. The Storage team seems to be doing things differently than other Azure teams, and we need some consistency. For example, when you call `Get-AzureRmPublicIpAddress` and `Get-AzureRmVm`, you get back an object that simply has a `Name` property. The property isn't called `PublicIPAddressName` or `VirtualMachineName`, because that would be redundant.

**Comment by blueww** [comment]
The "KeyName" is from SRP SDK, I will forward the issue to SRP SDK team.
Thanks for your consideration!

**Comment by blueww** [comment]
The "KeyName" is from Rest API, so SRP SDK also can't change it. 
And we don't receive other customer feedback on the "KeyName", so we won't change it now since it might break other customers. If we receive more, we might will consider to change it in the future.

This is the reply from SRP SDK team:

> I think following is how “KeyName” generated:

> 1)	It is first used as “keyName” by Storage Resource Provider Rest, https://msdn.microsoft.com/en-us/library/azure/mt163589.aspx 
> 2)	Then SRP use “keyName” in spec, https://github.com/Azure/azure-rest-api-specs/blob/0220c4e691422fd07cf26c8450a08b661798558a/arm-storage/2016-01-01/swagger/storage.json#L773
> 3)	During code generation, code generator(autorest) set the property as “KeyName”.
> 
> Currently, I didn’t find a way in Swagger spec to use “keyName” for rest api but generate “Name” in SDK.

**Comment by pcgeek86** [comment]
You guys already broke the API in the latest release. I used to be able to do `$StorageKey.Key1` or `$StorageKey.Key2`, but now all of these scripts are broken.

I'm asking you to fix it, please.

**Comment by blueww** [comment]
Hi Trevor,
You can do a simple fix on your script to make it work again. Please let us know if you meet any issue to fix it, and we are glad to help you on this.
 $StorageKey.Key1  ->  $StorageKey.Value[0]
 $StorageKey.Key2  ->  $StorageKey.Value[1]

And currently we don't plan to change it back since:
1. We have released the new build with output as key list, if we change back, it will also take breaking change to the customer who already use the key list interface. (We can’t support both key1, key2 and key list in output of same commandline.)
2. The change is caused by  SDK change (SDK is caused by Rest API change), if we don't keep consistent with SDK output, It will take bad effect to our code extendable and maintainable. 

We will do more check to the interface change in the future release to avoid such kind of breaking again.
Thanks for your understanding!

**Comment by pcgeek86** [comment]
Okay, but there was no warning put in place to inform customers that this would break, was there? I'm just trying to understand why these breaking changes are released without communicating to customers. When customers ask for logically-supported, breaking changes to components, they are often pushed back on, so I'm trying to understand why there's a double standard. :smile: 

@markcowl Do we have some automated testing in place to avoid these kinds of situations, and help catch breaking changes before release?

**Comment by blueww** [comment]
Hi Trevor,
The change is caused by the SDK change, but not PowerShell intend to change it.
Yes, we will do more review on the SDK upgrade and other interface change in the future to avoid such breaking change.
Thanks!

**Comment by xqiu** [comment]
Yes, please fix it, I just found that the issue broke the script I downloaded from https://github.com/fullscale180/asm2arm

**Comment by blueww** [comment]
@xqiu 
You can do a simple fix on your script to make it work again. Please let us know if you meet any issue to fix it, and we are glad to help you on this.
$StorageKey = Get-AzureRmStorageAccountKey -ResourceGroupName foo -Name bar;
Change: 
$StorageKey.Key1 -> $StorageKey.Value[0]
$StorageKey.Key2 -> $StorageKey.Value[1]

**Comment by wangzq** [comment]
FWIW, this also broke my scripts so I have now created a wrapper to ensure the script can works for different versions:

```
function Get-AzureExStorageAccountKey
{
	<#
	.Synopsis
		Returns storage account key as of 1.3.0 format.
	.Example
		PS> Get-AzureExStorageAccountKey -ResourceGroupName $rg -Name $name
	.Link
		http://www.codeisahighway.com/breaking-change-with-get-azurermstorageaccountkey-in-azurerm-storage-v1-1-0-azurerm-v1-4-0/
	.Link
		https://github.com/Azure/azure-powershell/issues/2212
	#>
	[CmdletBinding()]
	param (
		[Parameter(Mandatory=$true)]
		[string] $ResourceGroupName,

		[Parameter(Mandatory=$true)]
		[string] $Name
		)
	
	$result = Get-AzureRmStorageAccountKey -ResourceGroupName $ResourceGroupName -Name $Name
	if ($result.Key1) {
		$result
	} else {
		if ($result[0].Value) {
			[PsCustomObject] @{
				Key1 = $result[0].Value
				Key2 = $result[1].Value
			}
		} else {
			throw "Unrecognized storage account key result"
		}
	}
}
```

**Comment by brwilkinson** [comment]
This should be made to work with the pipeline.
e.g. 
Get-AzureRmStorageAccountKey -ResourceGroupName $RG -Name $saname | select -Index 0
and 
Get-AzureRmStorageAccountKey -ResourceGroupName $RG -Name $saname | 
select -First 1 -Property value
and
Get-AzureRmStorageAccountKey -ResourceGroupName $RG -Name $saname | foreach value
returning this:
TypeName: System.Collections.Generic.List`1[[Microsoft.Azure.Management.Storage.Models.StorageAccountKey, 
Microsoft.Azure.Management.Storage, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]


Currently it only works if it's (wrapped):
(Get-AzureRmStorageAccountKey -ResourceGroupName $RG -Name $saname) | select -Index 0
and
(Get-AzureRmStorageAccountKey -ResourceGroupName $RG -Name $saname) | select -First 1 -ExpandProperty value
and
(Get-AzureRmStorageAccountKey -ResourceGroupName $RG -Name $saname) | foreach value
returning this:
TypeName: Microsoft.Azure.Management.Storage.Models.StorageAccountKey

Please fix this?

**Comment by blueww** [comment]
Thanks for reporting it!
This is interesting. We will investigate that.
But currently it's not a blocking issue. We will priority it per our bandwidth.

**Comment by avishnyakov** [comment]
Get-AzureRmStorageAccountKey seems to be changes in terms of return type as well as some other commands. All our scripts stopped working :)

Raised some concerns around that, seems to be a bigger issue
Breaking changes / backward compatibility strategy #2460

**Comment by blueww** [comment]
Hi Anton,
 You can do a simple fix on your script to make it work again. Please let us know if you meet any issue to fix it, and we are glad to help you on this.
 $StorageKey.Key1 -> $StorageKey.Value[0]
 $StorageKey.Key2 -> $StorageKey.Value[1]

The change is caused by SDK change (SDK is caused by Rest API change), PowerShell doesn't intend to change that. We will do more check to the interface change in the future release to avoid such kind of breaking again.

Thanks for your understanding!

**Comment by avishnyakov** [comment]
Well, surely thank you for the details. 

The reality seems to be that new releases randomly break things. There are more breaking changes (not only Get-AzureRmStorageAccountKey) which weren't communicated back and which cannot be found in the release notes - https://github.com/Azure/azure-powershell/releases

That's not a "simple" fix as the context might be drastically different. A production ready scripts on top of Azure PowerShell with 5 000+ lines of code? - That does not seem to be a "simple fix" anymore. A blog post on "how to do stuff in Azure", yea, a "simple fix".

What would be recommendations around keeping all things working, then? Could that matter be taken more seriously at some point?

**Comment by blueww** [comment]
I can understand it's not easy to fix A 5 000+ lines production ready scripts, please let us know if you need any help on the fixing the script.
Sorry for the breaking, and we will do more check to the interface change in the future release to avoid such kind of breaking again.
