### ISSUE TITLE
Vulnerable Dependency Files in Az Modules - Action Required

### ISSUE THREAD

**Issue by Celine-REN** [Azure/azure-powershell#22138]
### Description

We have identified a critical security issue related to the Az modules installed in PowerShell. It has been discovered that certain dependency files within these modules, such as Newtonsoft.json, have been flagged as vulnerabilities by Microsoft Defender for Cloud.

Despite updating the modules to their latest versions, we found that the Newtonsoft.json file included in the latest module is still at version 10.0.3, which contains the reported vulnerability. To mitigate this risk, it is imperative to install version 13.0.1 of the Newtonsoft.json file. Please check the file version from here: https://www.powershellgallery.com/packages/Az.Security/1.4.0/Content/Microsoft.Azure.PowerShell.Cmdlets.Security.deps.json

After conducting thorough testing, we confirmed that this vulnerability exists in almost all the Az modules.

Please verify the issue and assist us how to update this Newtonsoft.json file in the az modules. 

### Issue script & Debug output

```PowerShell
no
```

### Environment data

```PowerShell
no
```

### Module versions

```PowerShell
Sample module: Az.Security 1.4.0
Actually almost all the az module have this issue.
```

**Comment by isra-fel** [comment]
Hi Celine, thanks for reporting. This is a false positive as the version of Newtonsoft.Json we ship in the latest version is 13.0.2. You can verify it by inspecting `{wherever your modules are installed}\Az.Accounts\{latest version}\lib\netfx\Newtonsoft.Json.dll` using for example [ILSpy](https://github.com/icsharpcode/ILSpy).
The deps.json files are know to be unreliable as they show the versions of the dependencies we require, but not of what we actually ship. To prevent the false positives from being reported again, we are considering not shipping those files in our modules.

**Comment by mistermeeple** [comment]
Hi @isra-fel we have other dependencies from the Az Module been flagged as vulnerable. I wonder if you'll be able to confirm whether these are also false positives:
- System.Text.Encodings.Web showing as version 4.6.0, needs to be version 4.7.2
- System.Net.Http showing as version 4.3.1, needs to be version 4.3.2
- System.Net.Http.WinHttpHandler showing as version 4.3.0, needs to be version 4.5.4
- System.Drawing.Common showing as version 4.7.0, needs to be version 4.7.2


/unresolve

**Comment by scott-richards-4593** [comment]
Can an ETA on when this issue will be resolve please be given?
