### ISSUE TITLE
Version property on objects returned from Get-AzureRmVMExtensionImage are of the wrong type

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-powershell#2214]
The version property of the PSVirtualMachineExtensionImage objects is if type system.string. We need to convert it to system.version to have proper sorting or else results are unexpected (see screenshot)
![untitled2](https://cloud.githubusercontent.com/assets/10071039/15064990/e987d14e-135a-11e6-9854-ebba327abc48.png)

**Comment by cormacpayne** [comment]
Closing since there can be suffixes on extension images that cannot be handled properly by `System.Version`
