### ISSUE TITLE
Azuredata factory creation issue

### ISSUE THREAD

**Issue by Koteswararaojonnalagadda** [Azure/azure-powershell#2216]
I am trying to create azure data factory through azure power shell as per below link facing the issues 
can some one help me?

https://azure.microsoft.com/en-us/documentation/articles/data-factory-monitor-manage-using-powershell/ 

New-AzureRmDataFactory : HTTP Status Code: BadRequest
Error Code: DataFactoryCreationNotAllowed
Error Message: Data Factory creation is temporarily disabled for tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 in the West US region for capacity reasons.
Request Id: 65f0e7b2-a821-4199-93f9-4e38a60e83f1
Timestamp (Utc):05/06/2016 10:58:49
At line:1 char:1
+ New-AzureRmDataFactory -ResourceGroupName ADFTest -Name ADFTestDW –Lo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmDataFactory], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataFactories.NewAzureDataFactoryCommand

**Comment by hovsepm** [comment]
@Koteswararaojonnalagadda this is a server side incident. Please contact Microsoft support to get help. https://azure.microsoft.com/en-us/support/faq/
