### ISSUE TITLE
[Doc]: https://learn.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az?view=azps-10.0.0

### ISSUE THREAD

**Issue by v-zhanyeshi** [Azure/azure-powershell#22166]
### Description

My customer has a question about Option 2: Use compatibility mode with Enable-AzureRmAlias in the public document.
Public doc: https://learn.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az?view=azps-10.0.0#convert-your-scripts-automatically

In the document, it says 'The Az module has a compatibility mode to help you use existing scripts while you update to the new syntax. The [Enable-AzureRmAlias](https://learn.microsoft.com/en-us/powershell/module/az.accounts/enable-azurermalias) cmdlet enables a compatibility mode through aliases. This mode allows you to use existing scripts with minimal modification while working towards a full migration to Az.'. 
Customer wants to know whether will compatibility mode be retired too together with AzureRM PowerShell modules which will be retired on 29 February 2024, since AzureRM PowerShell modules cannot be used after it is retired.
Could you please give any insight about whether compatibility mode can't work after AzureRM PowerShell modules is retired.

Thank you.

**Comment by dolauli** [comment]
Marked it as a question

**Comment by dolauli** [comment]
@v-zhanyeshi, The support for Enable-AzureRmAlias will not be deprecated with the deprecation of AzureRM modules
@mikefrobbins Please clarify that in our docs.

**Comment by v-zhanyeshi** [comment]
> @v-zhanyeshi, The support for Enable-AzureRmAlias will not be deprecated with the deprecation of AzureRM modules 

@xiaogang.ding@microsoft.com
Thank you for your support. 
Understand that Enable-AzureRmAlias will not be deprecated. 
May I know will this Enable-AzureRmAlias be retired in near furture or is there any timeline when will the compatibility mode with Enable-AzureRmAlias be ended to use ?

**Comment by dolauli** [comment]
It will not retire in near future. And there is no plan to retire it now.
