### ISSUE TITLE
Create Resource Manager VM with Window Updates disabled

### ISSUE THREAD

**Issue by ashleywb** [Azure/azure-powershell#2217]
I'm trying to disable windows update to a newly created VM, this VM was created from an image using the following:
Set-AzureRmVMOperatingSystem -VM $vmConfig -Windows -ComputerName $computerName -Credential $cred -ProvisionVMAgent -EnableAutoUpdate:$false

When I look at the OSProfileText I see the following:
{
  "computerName": "machine1",
  "adminUsername": "admin",
  "adminPassword": "tp{.}D>nMzH~Y2_",
  "customData": null,
  "windowsConfiguration": {
    "provisionVMAgent": True,
    "enableAutomaticUpdates": null,
    "timeZone": null,
    "additionalUnattendContent": null,
    "winRM": null
  },
  "linuxConfiguration": null,
  "secrets": null
}

It appears I can not set the enableAutomaticUpdates, its either null or True. Is this by design? How do I disable windows updates via powershell? Thanks

**Comment by singhkays** [comment]
@ashleywb `-EnableAutoUpdate` is a switch. If you don't specify it, the automatic update property shouldn't be set.
