### ISSUE TITLE
Getting Key Vault policies is not consistent, sometimes it shows display name

### ISSUE THREAD

**Issue by armandete** [Azure/azure-powershell#22194]
### Description

We are trying to create scripts to cleanup KV policies, but command is not consistent, also from Az Cli vs Az Powershell outputs are very different
For example in Az Cli we can´t even get displayName property, so only Powershell can be used for this solution, but sometimes not showing Display Name

Why am I reporting a bug?
Because when I execute PS command in my laptop, sometimes output is complete
In a VM with windows server using same version of PS is not showing full output
Also after testing in Azure runbook, functions, pipelines, output is incomplete. display name always showing empty

Command Name
(Get-AzKeyVault -VaultName $VaultName).AccessPolicies
Running from laptop, sometimes with PS it´s listing more than 20 policies by their name, exactly as in portal.azure, this is the expected result always, but it´s not consistent

Example of displayName
![image](https://github.com/Azure/azure-powershell/assets/55021283/2a3259d6-75e9-42f2-9bb7-d308b8e58cab)

But exact same command in azure solutions: runbook, functions & pipelines, it´s showing only 2 policies with correct display name, the rest are showing as empty

Errors:
No error from command execution, only incomplete/inconsistent output

### Issue script & Debug output

```PowerShell
DEBUG: AzureQoSEvent:  Module: Az.KeyVault:4.9.1; CommandName: Get-AzKeyVault; PSVersion: 7.2.11; IsSuccess: True; Duration: 00:00:23.4553958
DEBUG: 9:57:08 AM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 9:57:08 AM - GetAzureKeyVault end processing.

Tenant ID                                  : xxxxxxxxxxx
Object ID                                  : xxxxxxxxxxx
Application ID                             : xxxxxxxxxxx
Display Name                               : 
Permissions to Keys                        : {Get, List, Update, Create…}
Permissions to Secrets                     : {Get}
Permissions to Certificates                : {Get}
Permissions to (Key Vault Managed) Storage : {}
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.11
PSEdition                      Core
GitCommitId                    7.2.11
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.11.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, …
Script     4.9.1                 Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificate…
Script     6.5.2                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-A…
```

### Error output

```PowerShell
Error is basically getting Display Name empty

Tenant ID                                  : xxxxxxxxxxx
Object ID                                  : xxxxxxxxxxx
Application ID                             : xxxxxxxxxxx
Display Name                               : 
Permissions to Keys                        : {Get, List, Update, Create…}
Permissions to Secrets                     : {Get}
Permissions to Certificates                : {Get}
Permissions to (Key Vault Managed) Storage : {}
```

**Comment by dolauli** [comment]
@armandete Would you check whether you are using the same version Az.KeyVault in different platform? 
@BethanyZhou Please take a look at this issue to check whether you could reproduce it.

**Comment by BethanyZhou** [comment]
Hi @armandete  , display name is queried via Microsoft Graph API, which requires the account permission for `GET /directoryObjects/{id}`.

- Would you check whether you are using same account in different machine or platform.
- At the same time, please check the permission setup for your account.

**Comment by armandete** [comment]
Hello @BethanyZhou , @dolauli 

I have tested in same version in one of our agents and could get correct output, this is with my azure user
From runbooks still failing, but that is using service principal. I will confirm with my team, as maybe service principal doesn´t have all the permissions as you have mentioned

Will update as soon as I could confirm if permissions are root cause for this to show incomplete, thx for pointing out

**Comment by armandete** [comment]
I have tested in Azure runbook and as it uses a service principal, always failed, please try to replicate

With my personal account from command line it´s working, but because of 2FA figuring out how to automate it

**Comment by BethanyZhou** [comment]
Did the service principal own  required MG permissions?

**Comment by armandete** [comment]
Hello Bethany, sorry I was OOO but will update this in few hours, need escalation from my side

As I have tested with a different service principal with same result, I´m checking with my team for that specific permission, which I´m guessing is not automatically assigned for any service principal
