### ISSUE TITLE
Evaluate new format for platyPS

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2219]
### Description
When PlatyPS becomes available, evaluate:
* generation of markdown
* Ability to combine existing markdown help with changed cmdlet source
* generation of dll-Help.xml
* validation of desired help parts
  * cmdlet output types correct
  * parameter settings and signature correct
  * Synopsis and Description fro cmdlet
  * Help for each parameter
  * Examples

Then file issues with platyPS for any deficiencies and/or file issues for integration work in July Sprint.

### Cost (Work Units): 4

**Comment by cormacpayne** [comment]
Issue for initial steps: https://github.com/Azure/azure-powershell/issues/2921

PR for above issue: https://github.com/Azure/azure-powershell/pull/2932
