### ISSUE TITLE
Use Install-Module in the installer

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2220]
### Description
- Prototype including nugget packages for the cmdlets in a temporary directory and using a custom action to install using Install-Module on install and Uninstall-Module on remove.
- Evaluate Install and Update scenarios on Win 7, Win 8, Win 8.1, WIn10
- Integrate into repo

**Comment by markcowl** [comment]
This would fix #685

**Comment by KZeronimo** [comment]
Is this issue manifesting in the Visual Studio 2017 command line installer - PowerShell instances are killed during the install of the Azure workload - this seemed to start manifesting >= 15.3

**Comment by cormacpayne** [comment]
@KZeronimo this is unrelated to the issue you are seeing with Visual Studio.
