### ISSUE TITLE
[Doc]: Cmdlet reference should include or link to list of valid variable settings

### ISSUE THREAD

**Issue by PrometheusRising1** [Azure/azure-powershell#22214]
### Description

https://learn.microsoft.com/en-us/powershell/module/az.sqlvirtualmachine/new-azsqlvm?view=azps-10.0.0

For example, -Offer simply links to the general articles on Strings and gives one or two examples, but there is no way specified to find offer names.

**Comment by dolauli** [comment]
Thanks for reporting the issue.
