### ISSUE TITLE
New-AzCloudService Issue

### ISSUE THREAD

**Issue by dsm4u** [Azure/azure-powershell#22217]
### Description

I am trying to create a extended classic service with all Virtual network and ip details in configuration file. But the script is getting errored out with below error. Can you pls advice how to ignore the virtual network creation as its already in place.

Checking validations on the .cscfg and .csdef files.
Creating Virtual Network
New-AzVirtualNetwork : The Resource 'Microsoft.Network/virtualNetworks/subscriptions' under resource group '' was not found. For more details please go to 
https://aka.ms/ARMResourceNotFoundFix
StatusCode: 404
ReasonPhrase: Not Found
ErrorCode: ResourceNotFound
ErrorMessage: The Resource 'Microsoft.Network/virtualNetworks/subscriptions' under resource group '' was not found. For more details please go to 
https://aka.ms/ARMResourceNotFoundFix

**Comment by isra-fel** [comment]
@dsm4u we'd like to help but the error message was not trivial. Would it be possible to share your scripts? (Be sure to enclosure any sensitive information).
