### ISSUE TITLE
[Feature]: get-azsnapshot DISKSTATE parameter

### ISSUE THREAD

**Issue by cadumi** [Azure/azure-powershell#22221]
### Description of the new feature

We see there is no option to query the diskstate parameter of a snapshot with Powershell. Same as Snapshot state in portal.
This is possible with SDK or CLI.
https://learn.microsoft.com/en-us/rest/api/compute/snapshots/get?tabs=HTTP#diskstate 

az snapshot show -g "rg_group" -n "snapname"   //works and shows diskstate
get-azsnapshot -ResourceGroup "rg_group" -Name "snapname" //does not provide diskstate field

Can we have this added?

Also, a clear documentation for the Snapshot possible states is missing. Would appreciate if this can be added as well.

**Comment by hilaryw29** [comment]
Taking a look with the PowerShell team to see if this can be added, thanks!

**Comment by hilaryw29** [comment]
@TravisCragg-MSFT would you mind taking a look at this? Thanks!

**Comment by ushnaarshadkhan** [comment]
Thank you for reaching out with your suggestion. We greatly appreciate your input and interest in enhancing our product. We're happy to let you know that we have taken note of your request and will be adding it to our backlog for consideration in future development cycles. While we can't promise an immediate implementation, please know that your idea will be carefully reviewed by our team. Feel free to keep an eye on our updates and announcements for any potential developments. Thank you again for your contribution!
