### ISSUE TITLE
[Doc]: https://learn.microsoft.com/en-us/powershell/module/az.cdn/update-azfrontdoorcdnorigin?view=azps-10.0.0

### ISSUE THREAD

**Issue by sswEXG** [Azure/azure-powershell#22248]
### Description

Can we please have an example added on how to update an existing Origin with such that _EnforceCertificateNameCheck_ is disabled?

No matter what syntax I try, I've not been able to get it to update an Origin to disable _EnforceCertificateNameCheck_.

**Comment by t-bzhan** [comment]
Hi @sswEXG , the -EnforceCertificateNameCheck argument is a switch parameter, it is by default not to take any input value: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.3&viewFallbackFrom=powershell-7#switch-parameters, we might consider to change it to bool type in future releases to reduce the confusion according to: https://github.com/Azure/azure-powershell/blob/main/documentation/development-docs/design-guidelines/parameter-best-practices.md#bool-vs-switchparameter

As a workaround, you can try to inject the value with  -EnforceCertificateNameCheck:$false.

> PS D:\diag> Update-AzFrontDoorCdnOrigin -OriginGroupName default-origin-group -OriginName default-origin -ProfileName bzhan-test111 -ResourceGroupName bo-private -EnforceCertificateNameCheck:$false -Debug
> DEBUG: 10:14:40 AM - GetAzureRMContextCommand end processing.
> DEBUG: [CmdletBeginProcessing]: Starting command
> DEBUG: CmdletBeginProcessing:
> DEBUG: CmdletProcessRecordStart:
> 
> Confirm
> Are you sure you want to perform this action?
> Performing the operation "Update-AzFrontDoorCdnOrigin_UpdateExpanded" on target "Call remote 'AfdOriginsUpdate' operation".
> [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
> DEBUG: CmdletGetPipeline:
> DEBUG: CmdletBeforeAPICall:
> DEBUG: URLCreated: /subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourceGroups/bo-private/providers/Microsoft.Cdn/profiles/bzhan-test111/originGroups/default-origin-group/origins/default-origin?api-version=2021-06-01
> DEBUG: RequestCreated: /subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourceGroups/bo-private/providers/Microsoft.Cdn/profiles/bzhan-test111/originGroups/default-origin-group/origins/default-origin?api-version=2021-06-01
> DEBUG: HeaderParametersAdded:
> DEBUG: BodyContentSet:
> DEBUG: ============================ HTTP REQUEST ============================
> 
> HTTP Method:
> PATCH
> 
> Absolute Uri:
> https://management.azure.com/subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourceGroups/bo-private/providers/Microsoft.Cdn/profiles/bzhan-test111/originGroups/default-origin-group/origins/default-origin?api-version=2021-06-01
> 
> Headers:
> x-ms-unique-id                : 6
> x-ms-client-request-id        : 2dcc387b-40f0-4cd4-8a61-7c950d435cb5
> CommandName                   : Update-AzFrontDoorCdnOrigin
> FullCommandName               : Update-AzFrontDoorCdnOrigin_UpdateExpanded
> ParameterSetName              : __AllParameterSets
> User-Agent                    : AzurePowershell/v5.9.0,PSVersion/v7.3.6,Az.Cdn/2.1.0
> 
> Body:
> {
>   "properties": {
>     "enforceCertificateNameCheck": false
>   }
> }
> 
> 

Will update the doc to reflect that.
