### ISSUE TITLE
[Doc]: https://learn.microsoft.com/en-us/powershell/module/az.cdn/new-azfrontdoorcdnorigin?view=azps-10.0.0

### ISSUE THREAD

**Issue by sswEXG** [Azure/azure-powershell#22246]
### Description

Can we please have an example added on how to create an Origin with _EnforceCertificateNameCheck_ disabled?

No matter what syntax I try, I've not been able to get it to create an Origin with EnforceCertificateNameCheck disabled.

**Comment by t-bzhan** [comment]
Duplicate with https://github.com/Azure/azure-powershell/issues/22248
