### ISSUE TITLE
Update an existing role assignment  Set-AzRoleAssignment 

### ISSUE THREAD

**Issue by Sunitha82** [Azure/azure-powershell#22286]
### Description

Hi

I am trying to update an existing role under the subscription using  Set-AzRoleAssignment, I need to pass a new role in the Set-AzRoleAssignment but it is not accepting anything else other than InputObject
 Set-AzRoleAssignment -InputObject $roleAssignment -PassThru

**Comment by isra-fel** [comment]
Hi @Sunitha82 , as in the example 1, you can update a role assignment by simple steps:

1. Get the role assignment by `Get-AzRoleAssignment` and assign it to a PowerShell variable
2. Update the properties of the variable
3. Call `Set-AzRoleAssignment -InputObject ` plus the variable to set it back
