### ISSUE TITLE
Get-AzDataFactoryV2LinkedService does not return keyvault name in the linkedeservice of type "Azure SQL Database"

### ISSUE THREAD

**Issue by Ranjit-Kumar-Konjeti** [Azure/azure-powershell#22298]
### Description

Get-AzDataFactoryV2LinkedService does not return reference keyvault name in the linkedeservice of type "Azure SQL Database"

The below code only returns referenceName as "KeyVault" but it does not return actual keyvault name.

$linkedservicejson.typeProperties.connectionString.store.referenceName

 referenceName type
------------- ----
KeyVault      LinkedServiceReference

### Issue script & Debug output

```PowerShell
$linkedServices = Get-AzDataFactoryV2LinkedService -DataFactoryName $dataFactoryName -ResourceGroupName $resourceGroupName
    $DFlinkedServicesObject = [PSCustomObject] @()
    foreach ($linkedService in $linkedServices) {   
        
       Write-Output $linkedservicejson.typeProperties.connectionString.store.referenceName

}
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     1.16.13               Az.DataFactory                      {Add-AzDataFactoryV2DataFlowDebugSessionPackage, Add-AzDataFactoryV2TriggerSubscription, Get-AzDataFactory, Get-AzDataFactoryActivityWindow…}
Script     6.7.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
referenceName type
------------- ----
KeyVault      LinkedServiceReference
```

**Comment by SaurabhSharma-MSFT** [comment]
@Ranjit-Kumar-Konjeti Can you please provide the full code as it looks like the code which you have shared is incomplete and it is missing use of $DFlinkedServicesObject and $linkedservicejson.

**Comment by Ranjit-Kumar-Konjeti** [comment]
@SaurabhSharma-MSFT - do not worry about the missing code. main method is "Get-AzDataFactoryV2LinkedService".  you can create a Datafactory and add linked service of type sqldatabase and then use keyvault secret  instead of sql connection string and use the code below(by giving your datafactoryname and resourcegroupname) to list the linkedservices of type sqldatabase and type "AzureKeyVaultSecret" and try to get the keyvault name from there. I tried using Azure powershell, az cli and rest api. all 3 of them does not return keyvault name. Hope I am clear.

Get-AzDataFactoryV2LinkedService -DataFactoryName $dataFactoryName -ResourceGroupName $resourceGroupName

**Comment by SaurabhSharma-MSFT** [comment]
@Ranjit-Kumar-Konjeti I am not able to reproduce this issue. I referring to Azure Key Vault to get SQL connection string and Key Vault name correctly appears in the results output.  Please see below the screenshot - 
![image](https://github.com/Azure/azure-powershell/assets/38112130/85db066a-6c7b-484d-be05-3aec1005e80d)
You can find the connection string properties under Properties.AdditionalProperties of the returned result set.  Please try to fetch the Properties of your returned linked service. Thanks.

**Comment by Ranjit-Kumar-Konjeti** [comment]
Yes we are expecting the keyvault name not just the reference name, in this case how do we know which keyvault name it is referenced to?

**Comment by SaurabhSharma-MSFT** [comment]
@Ranjit-Kumar-Konjeti If you want to know actual Key Vault name then use the same cmdlet again by passing the referencename like below - 
![image](https://github.com/Azure/azure-powershell/assets/38112130/0330c2b4-b8c5-47c8-8452-3466ed0eb7a2)
Please let me know if you have any other questions.

**Comment by Ranjit-Kumar-Konjeti** [comment]
ok let me check and get back to you. Thanks!

**Comment by Ranjit-Kumar-Konjeti** [comment]
@SaurabhSharma-MSFT  , this one still does not work . I think you are referring to LinkedServiceType "keyvault". I can see the keyvault name from there but that is not what I am asking for. I am checking for LinkedServiceType "AzureSqlDatabaseLinkedService" and then get the Properties of that object where it references erither sql db connection or keyvault connection. I am looking keyvault name from that keyvault connection
![image](https://github.com/Azure/azure-powershell/assets/89483302/16406e13-5323-423b-bfc4-da67f3a8a669)

![image](https://github.com/Azure/azure-powershell/assets/89483302/99c4edce-3dab-4718-8733-58f5d6e23dfd)

![image](https://github.com/Azure/azure-powershell/assets/89483302/64f0e837-0caa-4e05-87d4-3837e3a9be26)

**Comment by Ranjit-Kumar-Konjeti** [comment]
@SaurabhSharma-MSFT - could you please re open the issue and check once.
