### ISSUE TITLE
Get-AzureRmResource Does Not Default to Latest API Version

### ISSUE THREAD

**Issue by timomta** [Azure/azure-powershell#2230]
The docs specify that -ApiVersion is optional, but if you don't specify it, Get-AzureRmResource defaults to an invalid API version '2015-01-01'. Example below:

PS D:> Get-AzureRmResource -ResourceId $ip.IpConfiguration.id
Get-AzureRmResource : NoRegisteredProviderFound : No registered resource provider found for location 'eastus2' and API version '2015-01-01' for type 'networkInterfaces'. The supported api-versions are '2014-12-01-preview,
2015-05-01-preview, 2015-06-15, 2016-03-30'. The supported locations are 'westus, eastus, northeurope, westeurope,
eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth,
australiaeast, australiasoutheast, centralindia, southindia, westindia'.
At line:1 char:1
- Get-AzureRmResource -ResourceId $ip.IpConfiguration.id
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Get-AzureRmResource], ErrorResponseMessageException
  - FullyQualifiedErrorId : NoRegisteredProviderFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementatio
    n.GetAzureResourceCmdlet

**Comment by ravbhatnagar** [comment]
@TianoMS - Lets investigate this.

**Comment by TianoMS** [comment]
Talked with Tim. The reason we saw this error is that the provided resource Id "$ip.IpConfiguration.id" is NOT a Resource Id. It’s a property value and doesn’t map to an azure resource. 

I'll see how we improve the error message here.

**Comment by ravbhatnagar** [comment]
Low Priority. please let us know if you feel strongly about this.
