### ISSUE TITLE
[Feature]: Get-AzMetric - Support Dimensions

### ISSUE THREAD

**Issue by jstutson-rel** [Azure/azure-powershell#22320]
### Description of the new feature

Get-AzMetric should support the ability group by a Dimension property.  This feature is available to its underlying API, it's on the Azure Portal Metrics UI, and Azure CLI's `az monitor metrics list` command.  

Available dimensions for metrics are detailed here: https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported but there's no support in Azure Powershell.  It feels like a requirement miss more than something we should need to request as a new feature here.  Without this we can't use Group By in our Powershell Azure Function since it only supports Azure PS modules and not Azure CLI...

### Proposed implementation details (optional)

I would add a new -Dimension parameter to Get-AzMetric.  As for the response contract, the models are already equipped to handle this.  The TimeSeries propery is an array of timeseries, each item has a Data array of time bucket points as well as a MetaDatavalues property which identifies the dimension's grouped by name.  I.e the name of a fileshare if the dimension was FileShare.

**Comment by isra-fel** [comment]
Thanks for the feedback 👍 
@VeryEarly could you evaluate this feature request? Thanks.
