### ISSUE TITLE
[Feature]: Invoke-AzVMRunCommand Timeout Parameter

### ISSUE THREAD

**Issue by mbrat2005** [Azure/azure-powershell#22347]
### Description of the new feature

Add a -Timeout parameter to the `invoke-azvmruncommand` and `Invoke-AzVmssVMRunCommand` commands. This is an option in the REST API but is not exposed in PowerShell as of Az.Compute v 6.1.0

**Comment by isra-fel** [comment]
Thanks for the feedback. Let me loop in CRP team.

**Comment by nikhilpatel909** [comment]
Ack

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vivlingaiah** [comment]
FYI
We already have "TimeoutInSeconds" parameter in Set-AzVMRunCommand (Managed Run Command )

**Comment by grizzlytheodore** [comment]
closing this issue, as this will not be implemented.  See above comment for similar solution.
