### ISSUE TITLE
Set-AzVMRunCommand is not getting deployed

### ISSUE THREAD

**Issue by Satyadm123** [Azure/azure-powershell#22380]
### Description

We are using Set-AzVMRunCommand  to  run powershell scripts on Azure VM . The powershell scripts do sftp and fetch files to VM . They  normally run within 5 minutes.
We use Get-AzVMRunCommand -ResourceGroupName  '' -VMName '' -RunCommandName to get the status of the run command and then we delete the run commands.

This is now taking hours to deploy run commands and also remove  them. How do we debug the issue?
We also se the same issue with Invoke-AzVMRuncommand

### Issue script & Debug output

```PowerShell
The  --verbose and --debug mode shows the run commands kep on polling rather than getting deployed
```

### Environment data

```PowerShell
Windows VM
```

### Module versions

```PowerShell
Poweshell 7
```

**Comment by wyunchi-ms** [comment]
Hi @Satyadm123 , do you try to use [Invoke-AzVMRunCommand](https://learn.microsoft.com/en-us/powershell/module/az.compute/invoke-azvmruncommand) to invoke the command and use [Get-AzVMRunCommand](https://learn.microsoft.com/en-us/powershell/module/az.compute/get-azvmruncommand) to get the detail result of the command?

**Comment by Satyadm123** [comment]
Hi @wyunchi-ms I use the Set-AzVMRunCommand  and then use the Get-AzVMRunCommand. It's the managed run command .

**Comment by wyunchi-ms** [comment]
Looks Set-AzVMRunCommand just create a run command on the server side, you need to run it by using [Invoke-AzVMRunCommand](https://learn.microsoft.com/en-us/powershell/module/az.compute/invoke-azvmruncommand)

**Comment by Satyadm123** [comment]
@wyunchi-ms  actually Set-AzVMRunCommand is another way of executing your scripts on VM. The difference is you can invoke only one [Invoke-AzVMRunCommand](https://learn.microsoft.com/en-us/powershell/module/az.compute/invoke-azvmruncommand) at a time but with Set-AzVMRunCommand you can run mutiple scripts on your VM at a time. It was working fine and running the sftp pwershell scripts on the VM . we have started getting this issue few weeks back and would want some directions on how to troube shoot .(may be logs that we can look at on the Windows VM)?

**Comment by Satyadm123** [comment]
And just to update both Invoke-AVMRunCommand and Set-AzVMRunCommand use the same VM agent to run scripts. And now we are seeing issue with both.

**Comment by vivlingaiah** [comment]
Yes, this is a known regression. We are taking a hotfix at the moment. [AzOrchestrator-v2 (trafficmanager.net)](https://azdeployer.trafficmanager.net/release/21970816)

**Comment by nikhilpatel909** [comment]
@satyadm123 hotfix was deployed, can you please verify so we can close the issue

**Comment by Satyadm123** [comment]
Hi @nikhilpatel909  Could you please share the release link with which this issue was fixed. I can confirm that we are able to submit the run commands. This will help us track the issue better.

**Comment by nikhilpatel909** [comment]
vivek has already provide link above , here you go.. [AzOrchestrator-v2 (trafficmanager.net)](https://azdeployer.trafficmanager.net/release/21970816)
