### ISSUE TITLE
[Doc]: Example 3 has a bug

### ISSUE THREAD

**Issue by wrwoodman** [Azure/azure-powershell#22399]
### Description

On this page: https://learn.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-10.1.0

Here is example 3 from the page.
`
$SecurePassword = ConvertTo-SecureString -String "Password123!" -AsPlainText -Force $TenantId = 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyy' $ApplicationId = 'zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzz' $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $ApplicationId, $SecuredPassword Connect-AzAccount -ServicePrincipal -TenantId $TenantId -Credential $Credential
`
The first line declares the variable $SecurePassword.
The 4th line attempts to use it but fails because it is not the same name. The 4th line uses the name $SecuredPassword.
Note the letter 'd' in "Secured".
Making it the same as the variable name in line 1 will make this script succeed. (Assuming all other variables are valid.)

**Comment by wyunchi-ms** [comment]
Yes, this is a typo, thanks @wrwoodman  ! Thanks for your contribution!

**Comment by wyunchi-ms** [comment]
This issue will be closed since we have fix the example. Thanks for you contribution again!
