### ISSUE TITLE
Azure Websites commands missing from Azure Resource Manager

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#224]
# Story

Consider the following scenario:

> As an operations engineer, I need the ability to deploy and manage Azure Websites using a familiar PowerShell interface.

# Problem Statement

The latest version of the Microsoft Azure Resource Manager PowerShell module does not have any commands available to manage Azure Websites. This can be verified by using the core PowerShell command `Get-Command`.

```
Switch-AzureMode -Name AzureResourceManager;
Get-Command -Module AzureResourceManager -Name *website*;
```

# Recommendation

Please add Azure Websites functionality to the Microsoft Azure Resource Manager PowerShell module, using familiar PowerShell design standards.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 Version 0.8.15 has a small set of websites cmdlets for ARM, which will grow over time
