### ISSUE TITLE
Set-AzVMRunCommand and Set-AzVMSSVMRuncommand cmdlets - Add "-TreatFailureAsDeploymentFailure" flag

### ISSUE THREAD

**Issue by vivlingaiah** [Azure/azure-powershell#22401]
### Description

- Need to add new boolean flag (or switch/option) "-TreatFailureAsDeploymentFailure" to Set-AzVMRunCommand and Set-AzVMSSVMRuncommand cmdlets 
- The description of the switch is here in Swagger specs
https://github.com/Azure/azure-rest-api-specs/blob/55fc71748c6f51a049fb77aa162ca797aabfbae6/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-03-01/runCommand.json#L1272
- In short, if user provides switch "-TreatFailureAsDeploymentFailure" (true), and RunCommand executes and returns non-zero exit code, the provisioningState for RunCommand would be set to "Failed"
provisioningState : https://github.com/Azure/azure-rest-api-specs/blob/55fc71748c6f51a049fb77aa162ca797aabfbae6/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-03-01/runCommand.json#L1262

- Service changes would be deployed by end of this week (by 07/28/2023). So, we need this switch available in Az module release after this date.

### Issue script & Debug output

```PowerShell
New switch/parameter request.
```

### Environment data

```PowerShell
NA
```

### Module versions

```PowerShell
10.1.0
```

### Error output

```PowerShell
No errors
```

**Comment by TravisCragg-MSFT** [comment]
Assigning to @nikhilpatel909

**Comment by vivlingaiah** [comment]
@TravisCragg-MSFT , I'm from Compute VM extensions team (we are owner of Run command). This is an ask for Az.Compute module owners for adding new parameter.

**Comment by grizzlytheodore** [comment]
added in https://github.com/Azure/azure-powershell/issues/22401

**Comment by grizzlytheodore** [comment]
it's been released in the latest release: https://www.powershellgallery.com/packages/Az/11.5.0
