### ISSUE TITLE
[Feature]: Support for block blobs in New-AzGalleryApplicationVersion

### ISSUE THREAD

**Issue by mist74** [Azure/azure-powershell#22444]
### Description of the new feature

The current implementation of New-AzGalleryApplicationVersion requires that for:

- DefaultConfigFileLink
- PackageFileLink

link to a "_...must be a readable storage **page blob**_" must be used as a vallue. Attempts to use block blobs end fatally... As almost no one package or default config file is 512 bytes rounded, this critically unfortunate rquirement leads to plenty concerns when using PowerShell to prepare required page blobs. No one for below questions are now answered in Microsot documentation. For an instance: 
- How to prepare both files, files by nature of not controlled size, to create blobs? 
- Some kind of file padding? 
- How to do it in Windows PowerShell environemnt? 
- How to do it in a way that the blobs, even being created, can be used by to create fully functional (working) application version? If padding was used, should information about real file size be stored in blobs metadata? If yes, how?

### Proposed implementation details (optional)

Solutions I propose can be two, where the second one seems to be more prefered:
1) Provide detailed description how page blob should be prepared for usage as link source when file used to create the blob can be of any random size. Code examples are always welcome. Only PowerShell usage (no .Net libraries).
2) Remove the unfortunate demand to use page blob as link source. Today Azure portal web GUI interface can do the trick and is capable to use any link (not only provided by a page blob) for both files to create working app versions. Why PowerShell should not be able to provide the same functionality?

**Comment by Drewm3** [comment]
Sandeep, please work with Nikhil to determine if this feature request could be supported.

**Comment by GabstaMSFT** [comment]
@mist74, I am reviewing older issues and this is now supported as documented here [https://learn.microsoft.com/en-us/azure/virtual-machines/vm-applications](https://learn.microsoft.com/en-us/azure/virtual-machines/vm-applications)

**Comment by GabstaMSFT** [comment]
Closing as this feature has been rolled out and is currently available.
