### ISSUE TITLE
Az.Accounts & Microsoft.Graph.Authentication using different versions of Azure.Core.dll

### ISSUE THREAD

**Issue by KurtyGLaw** [Azure/azure-powershell#22449]
### Description

I don't know if this should be reported as a bug or not, but I found that the Az.Accounts module and the Microsoft.Graph.Authentication modules are now using different version of Azure.Core.dll. Az.Accounts loads version 1.31.0, where Microsoft.Graph.Authentication has recently(?) moved to version 1.33.0. The result is an issue with (at a minimum) Get-AzStorageTable from Az.Storage where the command fails. 

I know this is more of an issue/incompatibility between two different modules, figured that it might be helpful to mention, and hopefully get some suggestions on how I can work around it, as I need these two modules loaded at the same time.

**Comment by wyunchi-ms** [comment]
Hi @KurtyGLaw , could you please show the version of Az.Accounts and Az.Resources you are using? You can get them by input 
```powershell
gmo
```
in your PowerShell session. The latest version of Az.Accounts should also use 1.33.0.

**Comment by KurtyGLaw** [comment]
I'm sure I checked PSGallery before posting this to ensure I was on the latest. Maybe they were posted when I checked, but I do see the newer versions now and everything is good. My bad.
