### ISSUE TITLE
[Feature]: New-AzFunctionApp support for Python 3.10

### ISSUE THREAD

**Issue by SvenSowa** [Azure/azure-powershell#22448]
### Description of the new feature

New-AzFunctionApp should support Python 3.10 via the parameter "RuntimeVersion". Currently supported runtime versions for 'Python' are: '3.7', '3.8', '3.9'. 3.10 is GA since February 2023. https://azure.microsoft.com/en-us/updates/generally-available-azure-functions-support-for-python-310/. The latest module is 9 months old (https://www.powershellgallery.com/packages/Az.Functions/4.0.6) and it does not support 3.10 yet.

Workaround right now. Run New-AzFunctionApp with RuntimeVersion 3.9, then run Get-AzResource and Set-AzResource:
```
$resource = Get-AzResource `
    -ResourceType Microsoft.Web/sites `
    -ResourceGroupName $resourceGroupName `
    -ResourceName "$($functionAppName)/config/web"
$resource.Properties.linuxFxVersion = "PYTHON|3.10"
$resource | Set-AzResource -Force
```

**Comment by Francisco-Gamino** [comment]
This issue has been fixed in the latest release.
