### ISSUE TITLE
[Feature]: Support creating VM image version using VHD blob in Azure powershell

### ISSUE THREAD

**Issue by xinghuozeng** [Azure/azure-powershell#22451]
### Description of the new feature

We can't create image version via command 'New-AzGalleryImageVersion' from VHD directly, but we can use 'az sig image-version create'(with '--os-vhd-storage-account' and '--os-vhd-uri'). 

Ask Azure Powershell to provide similar functionality as az cli to create VM image version directly from VHD. We have our devops pipeline built on Azure Powershell. Today we have to create a managed image first from VHD blob, and then use it to create image version. We are told that managed image is going to be deprecated. Hence need the ability create azure image version directly from VHD.

**Comment by Drewm3** [comment]
@sandeepraichura, this functionality is part of the API. So, I believe this should be treated as a bug instead of a feature request.

**Comment by sandeepraichura** [comment]
Thanks for reporting the issue, we will file a bug with PS team.  @kangsun-ctrl

**Comment by sandeepraichura** [comment]
This should have been addressed as per this: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1376
Closing this out, please reopen if needed.
