### ISSUE TITLE
Az.Subscription Update-AzSubscription not available in the newer version

### ISSUE THREAD

**Issue by cosminlof** [Azure/azure-powershell#22457]
### Description

In the latest version of the Az.Subscription module the Update-AzSubscription cmdlet has been either removed from the newer version or forgot about it.
After looking into the previous tags on the current code repository, there's been no notification about a possible breaking change.
This new change was introduces, based on the tags , in "v10.2.0-August2023".

This change broke our workflows and it didn't even give a hint to prepare in advanced.
There a pattern that keeps repeating for these modules, and the MS teams have to improve their reviewing process because as for now, we've had at least 3 breaking changes that were not announced and broke our automation workflows.

Will there be a fix for the Update-AzSubscription cmdlet?

### Issue script & Debug output

```PowerShell
The term 'Update-AzSubscription' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Environment data

```PowerShell
It runs in Azure DevOps under the following task:

task: AzurePowerShell@5
```

### Module versions

```PowerShell
Installed module from output windows:

Module Az.Subscription : 0.10.0 installed
```

### Error output

```PowerShell
The term 'Update-AzSubscription' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by TomSzaky** [comment]
Facing the same issue. Had to switch to the older version of the module 0.9.0, because it broke our pipelines for provisioning Landingzone subscriptions.

**Comment by AshishDadhich4h2** [comment]
Any workaround or fix ?

**Comment by isra-fel** [comment]
Hi, in the latest release (v0.10.0), `Update-AzSubscription` was split and renamed to `Rename-AzSubscription`, `Disable-AzSubscription` and `Enable-AzSubscription` respectively to better align the names and purpose of the cmdlets.

The official documents will be updated shortly. For now please check out [our github repo](https://github.com/Azure/azure-powershell/tree/main/src/Subscription/help) for help.

The Az PowerShell modules follow [Semantic Versioning](https://semver.org/). The version of Az.Subscription is v0.10.0 - indicates it's in preview and the syntax and behavior may be subject to change. Generally, if you intend to use a preview module in production, we recommend pinning the module to a fixed version.

We are also talking to service team to make a plan to GA the module. After GA, the module becomes stable and has to follow our [breaking change policy](https://learn.microsoft.com/en-us/powershell/azure/azps-versioning-release-cadence?view=azps-9.7.1#breaking-changes).

**Comment by cosminlof** [comment]
We figured in the meanwhile what the commands are, but there was no announcement of upcoming breaking changes that are given by the commands and also in the md upcoming and current breaking changes.

**Comment by emykamal** [comment]
I am facing the same exact issue. Any fixes or workarounds?
