### ISSUE TITLE
 Select-AzureRmProfile should throw if profile file is missing

### ISSUE THREAD

**Issue by blumu** [Azure/azure-powershell#2246]
`Select-AzureRmProfile` does not throw if the filepath passed as parameter does not exist. This makes it hard to diagnose issues when loading Azure profiles as part of large scripts:

    $ErrorActionPreference='stop'
    Select-AzureRmProfile -FilePath c:\SomeInvalidFilePath

Expected result: an exception thrown
Actual output:

    Environment           :
    Account               :
    TenantId              :
    SubscriptionId        :
    CurrentStorageAccount :

**Comment by hovsepm** [comment]
Fixed in dev branch, will be available in June release
