### ISSUE TITLE
[Feature]: Include Az.ResourceGraph in Az Supermodule

### ISSUE THREAD

**Issue by mbrat2005** [Azure/azure-powershell#22489]
### Description of the new feature

Please consider including the Az.ResourceGraph module in the Az supermodule. 

With increased visibility to Resource Graph through features like Resource Graph Explorer, Resource Graph-based alerts, and Advisor support of ARG rules, more users are likely to leverage the service to decrease API calls and consolidate complex logic in their automation. 

Requiring users to separately install the Az.ResourceGraph module adds complexity to automation development and the end-user experience.

**Comment by isra-fel** [comment]
Thanks for reporting! I've routed the request to Resource Graph team.
cc @Alex-wdy @dcaro

**Comment by mbrat2005** [comment]
By including 'Az.ResourceGraph' in the RequiredModules list for a custom powershell module, it will automatically be installed when using 'Install-Module' to install the custom module. This seems sufficient, so I am closing this feedback
