### ISSUE TITLE
Key Vault update commands fail with weird error message

### ISSUE THREAD

**Issue by FabianGonzalez-MSFT** [Azure/azure-powershell#22488]
### Description

When customer are trying to perform update operations for Azure Key Vault such as "Set-AzKeyVaultAccessPolicy" or "Add-AzKeyVaultNetworkRule", they get a weird error message like:

"The request content has one or more ambiguous paths: 'properties.networkAcls.ipRules' required for policy evaluation."

Above issue has been reported in the latest versions of AKV PSH module only. If you try with an older version, or using a different interface such as CLI, it works.

### Issue script & Debug output

```PowerShell
The output/error:

"subStatus": {
        "value": "Conflict",
        "localizedValue": "Conflict (HTTP Status Code: 409)"
    },
    "submissionTimestamp": "2023-08-01T10:31:18Z",
    "subscriptionId": "xxxx",
    "tenantId": "xxxxx",
    "properties": {
        "statusCode": "Conflict",
        "serviceRequestId": null,
        "statusMessage": "{\"error\":{\"code\":\"AmbiguousPolicyEvaluationPaths\",\"message\":\"The request content has one or more ambiguous paths: 'properties.networkAcls.ipRules' required for policy evaluation.\"}}",
```

### Environment data

```PowerShell
---- -----
PSVersion 7.3.6
PSEdition Core
GitCommitId 7.3.6
OS Linux 5.10.102.2-microsoft-standard #1 SMP Mon Mar 7 17:36:34 UTC 2022
Platform Unix
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
WSManStackVersion 3.0
```

### Module versions

```PowerShell
4.10.0
```

**Comment by BethanyZhou** [comment]
@FabianGonzalez-MSFT , could you share the exact commands (with its parameters and argument values) with us?

**Comment by FabianGonzalez-MSFT** [comment]
@BethanyZhou I added the commands on the description.

You just gotta have latest Az.KeyVault module (4.10.1) installed and run any of the listed commands. Eg:

![image](https://github.com/Azure/azure-powershell/assets/85696197/3a518f89-29f3-402e-b31e-e61697b665df)

**Comment by peterboba** [comment]
Looks to be the same issue as https://github.com/Azure/azure-powershell/issues/22472 ( Just different cmdlets mentioned )
