### ISSUE TITLE
SecurityType = "Standard" request on New-AzVMSecurityProfile and Set-AzDiskSecurityProfile

### ISSUE THREAD

**Issue by bl185052** [Azure/azure-powershell#22487]
### Description

I noticed that the az cli has supported passing standard, although powershell still doesnt. Will this be implemented? Otherwise our company will have about 50 snapshots (in my department alone) we'll have to recreate if our powershell scripts will be unable to pass Standard when TrustedLaunch will be default. 

Example:
$VirtualMachine = Set-AzVMSecurityProfile -VM $VirtualMachine -SecurityType Standard
New-AzVM -ResourceGroupName $resourceGroupName -Location $azureLocation -VM $VirtualMachine -Verbose

**Comment by hilaryw29** [comment]
@bl185052 Thanks for reporting this issue. We are triaging and will get back to you as soon as we are able.

**Comment by TravisCragg-MSFT** [comment]
@bl185052 please [update your Azure PowerShell Modules](https://learn.microsoft.com/en-us/powershell/azure/install-azps-windows?view=azps-11.5.0&tabs=powershell&pivots=windows-psgallery#update-the-az-powershell-module) and try this again? I am able to do this with the most recent version of Azure PowerShell. 

I am going to close this issue as resolved. If you are still having issues, please @me in a response I and I will re-open this issue.
