### ISSUE TITLE
Set-AzureRmKeyVaultAccessPolicy removes all existing tags associated with the keyvault

### ISSUE THREAD

**Issue by blumu** [Azure/azure-powershell#2249]
**Repro**
- Create a keyvault in Azure with associated tags
- Update access policy for the keyvault with Set-AzureRmKeyVaultAccessPolicy
- Get the resource tags with Get-AzureRmResource

**Expected**: the tags should still be listed
**Actual**: the tags have been removed

**Comment by maddieclayton** [comment]
This seems to have been fixed - cannot repro in 5.5.0.  If this continues to be an issue, please reopen.
