### ISSUE TITLE
What is the point of "Update-AzSpringCloud" network parameters?

### ISSUE THREAD

**Issue by Remigijus-D** [Azure/azure-powershell#22514]
### Description

What is the point of "Update-AzSpringCloud" network parameters? As per Microsoft [documentation](https://learn.microsoft.com/en-us/azure/spring-apps/how-to-deploy-in-azure-virtual-network?tabs=azure-portal) you cannot update network settings so why provide this misleading information?

```
Update-AzSpringCloud
      -Name <String>
      -ResourceGroupName <String>
      [-SubscriptionId <String>]
      [-Location <String>]
      [-NetworkProfileResourceGroup <String>]
      [-NetworkProfileServiceCidr <String>]
      [-NetworkProfileServiceResourceGroup <String>]
      [-NetworkProfileServiceSubnetId <String>]
      [-NetworkProfileSubnetId <String>]
```

Service Runtime subnet cannot be changed.

### Module versions

Az.SpringCloud 0.3.0

**Comment by isra-fel** [comment]
Thanks for reporting!
cc @dingmeng-xue could you double confirm if the network settings cannot be updated and please suggest the next step when we update the module? Thanks.
