### ISSUE TITLE
Get-AzureRmRecoveryServicesBackupContainer value for parameter -Name is case sensitive

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-powershell#2251]
Get-AzureRmRecoveryServicesBackupContainer value for parameter -Name is case sensitive

Value should not be case sensitive. I should be getting results no matter if I've wrote the VM name with capital or small letters.

**Comment by pragrawa** [comment]
@slavizh ,In the upcoming powershell release, we are deprecating Name parameter and adding FriendlyName parameter. So this will avoid confusion. Also, FriendlyName will be case sensitive due to backend limitation. We will update the doc for this commandlet.

**Comment by dragonfly91** [comment]
This fix is published a while ago. Closing this issue.
