### ISSUE TITLE
Get-AzureRMRecoveryservicesBackupJob - getting job by jobid fails

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-powershell#2252]
$job = Backup-AzureRmRecoveryServicesBackupItem -Item $item;
PS C:\WINDOWS\system32> $joblist = Get-AzureRMRecoveryservicesBackupJob -JobId $job.JobId
Get-AzureRMRecoveryservicesBackupJob : CloudInternalError: Microsoft Azure Backup encountered an internal error.
Wait for a few minutes and then try the operation again. If the issue persists, please contact Microsoft Support.
At line:1 char:12
- $joblist = Get-AzureRMRecoveryservicesBackupJob -JobId $job.JobId
-            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Get-AzureRmRecoveryServicesBackupJob], CloudException
  - FullyQualifiedErrorId : CloudInternalError,Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.GetAzureRmRe
    coveryServicesBackupJob

**Comment by pragrawa** [comment]
@slavizh , this command is working fine. If you  are still facing this issue, please share debug logs.
