### ISSUE TITLE
[Doc]: `Set-AzEventHub` cmdlet cannot update Partition Count

### ISSUE THREAD

**Issue by ArmaanMcleod** [Azure/azure-powershell#22538]
### Description

In the documentation it says you can update partition count of event hub using `Set-AzEventHub -partitionCount`: https://learn.microsoft.com/en-us/azure/event-hubs/dynamically-add-partitions#powershell

But if you look at the cmdlet reference: https://learn.microsoft.com/en-us/powershell/module/az.eventhub/set-azeventhub?view=azps-10.2.0

There is no `partitionCount` parameter.

**Comment by Saglodha** [comment]
Thanks for bringing this to our attention @ArmaanMcleod , we would update our PowerShell cmdlet reference to include Partition Count parameter.

**Comment by Saglodha** [comment]
@ArmaanMcleod - this has been fixed in related docs, kindly let us know if there is any additional improvement that you would like to suggest.
