### ISSUE TITLE
Login-AzureRmAccount UI problem on high-dpi display

### ISSUE THREAD

**Issue by flytzen** [Azure/azure-powershell#2254]
If you use Login-AzureRmAccount without parameters you get a window up that asks you to login.
That window cannot be resized or scrolled and on a high-DPI display, such as on a surface book, only shows the right-hand half of the login screen. This makes it very difficult to use, in particular as it is impossible to read any error messages. Also, if you use the same email address for a Microsoft account and an Office 365 account it is very difficult to answer the question about which one you want to use - as you can't see the question.
I have had to resort to utilities that allow me to resize the window.

**Comment by markcowl** [comment]
### Action
Investigate options for improving the default size of the window on high dpi displays with ADAL.Net

### Cost: 2

**Comment by hovsepm** [comment]
This is ADAL related issue and AD team is working on the fix.
