### ISSUE TITLE
Move-AzureRmExpressRouteCircuit doesn't parse -name

### ISSUE THREAD

**Issue by ColdHarbour** [Azure/azure-powershell#2258]
I can rename, or continue to use, an incorrect name for an ExpressRoute circuit when utlising the Move-AzureRmExpressRouteCircuit cmdlet.

for instance, this command would be valid - notice the spaces in the name:
Move-AzureRmExpressRouteCircuit -Name "My Azure Circuit" -ResourceGroupName "exprtrg" -Location " Australia East" -ServiceKey 12343434-23232323-23232323

However, if I then try to update settings on the circuit once it is in ARM, I cannot as the -name is invalid, e.g. this will fail:
_Set-AzureRmExpressRouteCircuit -ExpressRouteCircuit $ckt_

_{
  "error": {
    "code": "InvalidResourceName",
    "message": "Resource name **My Azure Circuit** is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'.",
    "details": []
  }
}_

**Comment by sjwaight** [comment]
We currently have a support ticket open precisely due to this issue. The circuit stays up but becomes effectively unmanageable due to the invalid ARM EXR curcuit name.

**Comment by markcowl** [comment]
@deepakrajendranmsft can you route this issue appropriately to the ExpressRoute team?

**Comment by DeepakRajendranMsft** [comment]
@amitsriva please take a look at his

**Comment by markjbrown** [comment]
I'll investigate.

**Comment by maddieclayton** [comment]
@vinayada1 @dedhar @dihan0604 Can you take a look at this issue?

**Comment by sjwaight** [comment]
Apologies for missing the (very) old comment @markjbrown :(.

**Comment by srividyathirumala** [comment]
Move-AzureRmExpressRouteCircuit no longer accepts name with spaces. It does the same checks as Set-AzureRmExpressRouteCircuit .
