### ISSUE TITLE
Set-AzureRmResource - "Cannot find User with name XXXXXXX"

### ISSUE THREAD

**Issue by mskutin** [Azure/azure-powershell#2259]
Unable to set `Microsoft.Web/sites/sourcecontrols` settings always get into the same error:

``` powershell
$PropertiesObject = @{
                        RepoUrl='https://github.com/organization/repo.git';
                        Branch='branch'; 
                        IsManualIntegration='False'; 
                        DeploymentRollbackEnabled='False'; 
                        IsMercurial='False'; 
                        ProvisioningState='Succeeded'
                    }
Set-AzureRmResource -PropertyObject $PropertiesObject `
                    -ResourceGroupName $ResourceGroupName `
                    -ResourceType Microsoft.Web/sites/sourcecontrols `
                    -ResourceName $ResourceName/web `
                    -ApiVersion 2015-08-01 -Force
```

``` powershell
Set-AzureRmResource : The pipeline has been stopped.
At line:3 char:1
+ Set-AzureRmResource -PropertyObject $PropertiesObject -ResourceGroupN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmResource], PipelineStoppedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet
```

``` powershell
Set-AzureRmResource : {"Code":"NotFound","Message":"Cannot find User with name 
10030000XXXXXX.","Target":null,"Details":[{"Message":"Cannot find User with name 
10030000XXXXXX."},{"Code":"NotFound"},{"ErrorEntity":{"Code":"NotFound","Message":"Cannot find User with name 
10030000XXXXXX.","ExtendedCode":"51004","MessageTemplate":"Cannot find {0} with name 
{1}.","Parameters":["User","10030000XXXXXX"],"InnerErrors":null}}],"Innererror":null}
At line:3 char:1
+ Set-AzureRmResource -PropertyObject $PropertiesObject -ResourceGroupN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : NotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet

```

**Comment by markcowl** [comment]
@akurmi can you advise on the appropriate way to set sourcecontrols?

**Comment by akurmi** [comment]
Adding @davidebbo as he may know how these APIs work.

**Comment by davidebbo** [comment]
@mskutin are you using a service principal identity? If so, I think there may be some limitations around that. @suwatch is the expert.

**Comment by suwatch** [comment]
Correct, we don't support service principal identity.    

If you were just using typical user account, make sure you log on to  [portal](https://portal.azure.com) with this same account and setup deployment of any webapp with Github once (involving OAuth flow).

**Comment by suwatch** [comment]
A few corrections.   

  - Looking at the error above, this implied that user did not use Service Principal.  It is interact user (with PUID: 100300XXX) account.   @mskutin, try logon to [portal](https://portal.azure.com/) and perform [setup continuous deployment](https://azure.microsoft.com/en-us/documentation/articles/web-sites-publish-source-control/) thru portal ui once.   Then retry your scenario with cmdlet again.   If still failed, share us the sitename, time and timezone.
```
10030000XXXXXX."},{"Code":"NotFound"},{"ErrorEntity":{"Code":"NotFound","Message":"Cannot find User with name 
```

  - I reviewed our internal codes for setup sourcecontrol, we **do** support set up using Service Prinicipal.   I did try and it worked great.  The tricky part is one must first generate [the github oauth token](https://github.com/settings/tokens) and call [this api](https://github.com/projectKudu/ARMClient/wiki/Setup-GitHub-publishing-to-Site) to associate the token with Service Principal.

**Comment by suwatch** [comment]
@mskutin are you still having issue?  If yes, first please clarify whether you were using service principal?   Also do include time frame of the failure and site name (here or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)).

**Comment by mskutin** [comment]
@suwatch, whether or not service principle I still have.

I thought we discuss this by email, ticket number is [216051214155825001]
> try logon to portal and perform setup continuous deployment thru portal ui once.

Here is what I have:
> •	DESCRIPTION
> Failed to set up deployment source for web app bandlab-asia-storage, using External Repository. {"Code":"NotFound","Message":"Cannot find SourceControlToken with name GitHub.","Target":null,"Details":[{"Message":"Cannot find SourceControlToken with name GitHub."},{"Code":"NotFound"},{"ErrorEntity":{"Code":"NotFound","Message":"Cannot find SourceControlToken with name GitHub.","ExtendedCode":"51004","MessageTemplate":"Cannot find {0} with name {1}.","Parameters":["SourceControlToken","GitHub"],"InnerErrors":null}}],"Innererror":null}
> •	STATUS
> Error
> •	TIME
> Thursday, May 26, 2016, 12:55:50 PM
> •	CORRELATION IDS
> dab3c322-b4c7-4895-ac1d-580bedd79565

**Comment by suwatch** [comment]
@mskutin Sorry I must have missed that conversation on the mail thread.

My apology as I wasn't being clear about `try logon to portal and perform setup continuous deployment thru portal ui once`.   What I meant was you must go thru portal with that same account and try to setup `GitHub` (not External) continuous integration (hilited below) once.  This will lead you to perform the OAuth flow with Github.  As a result, the Github token will be established for this particular account.   Again you only need to do this once.   

![image](https://cloud.githubusercontent.com/assets/1088218/15718508/886bc89e-27e0-11e6-957a-c6716be152a9.png)

Then you can use Azure cmdlet or doing External Repository with your private repo etc.

**Comment by mskutin** [comment]
@suwatch what about this https://azure.microsoft.com/en-us/updates/automation-run-as-account/ ? Do I need to go through the procedure above for this type of accounts? I cannot login using this account since it doesn't have a password. So I can't setup GitHub deployment.

**Comment by suwatch** [comment]
Correct, since you can't log on with service principal, you can't perform oauth flow via Portal UI in order to associate Github token with service principal account.   

Good news is there is a manual step you could do.  Below explains how to achieve this using [ARMClient](https://github.com/projectkudu/ARMClient).    @davidebbo might know how to achieve via cmdlet powershell.

  - Install ARMClient (simply chocolatey) see [readme](https://github.com/projectkudu/ARMClient#armclient).

  - Run ARMClient [spn](https://github.com/projectKudu/ARMClient/wiki/Login-and-Acquire-Tokens) command to logon with appId and appKey.

  - Follow the first two steps to [generate Github OAuth token and store it with Azure](https://github.com/projectKudu/ARMClient/wiki/Setup-GitHub-publishing-to-Site).

That's it.  Now you can try using Cmdlet to setup publishing from Github or any.

**Comment by davidebbo** [comment]
PowerShell would look something like this:

```
$PropertiesObject = @{
	token = "yourgithubtoken";
}
Set-AzureRmResource -PropertyObject $PropertiesObject -ResourceId /providers/Microsoft.Web/sourcecontrols/GitHub -ApiVersion 2015-08-01 -Force
```

And [this article](https://azure.microsoft.com/en-us/documentation/articles/resource-group-authenticate-service-principal/) explains how to login with service principal to PowerShell.

**Comment by mskutin** [comment]
@davidebbo @suwatch Thanks for the explanations, I confirm that everything above works after this:
> What I meant was you must go thru portal with that same account and try to setup **GitHub (not External)** continuous integration (hilited below) once.

**Comment by cormacpayne** [comment]
Closing this issue as it appears to be resolved.

@mskutin please feel free to reopen this issue if it wasn't resolved and/or you have any other questions.

**Comment by amrtappin** [comment]
I have the same issue with App Service Environment V3:

> Cannot find User with name 100320026B8366CA.

**Comment by Himangshu-Biswas-daOrion** [comment]
You don't have access to resource group. Get access to the resource group as contributor where your wep app is.
