### ISSUE TITLE
ResourceGroupName parameter should not be mandatory for Get-AzureRmSqlServer

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2260]
ResourceGroupName parameter should not be mandatory for Get-AzureRmSqlServer

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@akromm Please route to the appropriate person on the Sql team.  This will soon be a requirement for Get cmdlets for RPs.

**Comment by pcgeek86** [comment]
@akromm @markcowl This is still a problem. Has anyone started work on this?

**Comment by akromm** [comment]
Closing as duplicate of #635
