### ISSUE TITLE
Get-AzRoleAssignment 'BadRequest'

### ISSUE THREAD

**Issue by Acenl12** [Azure/azure-powershell#22606]
### Description

This fails
$results += Get-AzRoleAssignment -Scope $scope -WarningAction SilentlyContinue

Error: 2023-08-17T08:45:26.8807812Z �[36;1m 316 | �[0m … $results += �[36;1mGet-AzRoleAssignment -Scope $scope -WarningAction Silentl�[0m …
2023-08-17T08:45:26.8808473Z �[36;1m     | �[31;1m               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-08-17T08:45:26.8809293Z �[31;1m�[36;1m     | �[31;1mOperation returned an invalid status code 'BadRequest'
 
This works:
$results += Get-AzRoleAssignment | Where-Object {$_.scope -eq $scope}

We are using Enterprise Policy as Code (epac)

### Issue script & Debug output

```PowerShell
Get-AzRoleAssignment: /home/vsts/.local/share/powershell/Modules/EnterprisePolicyAsCode/7.8.4/internal/functions/Get-AzPolicyResources.ps1:316
Line |
 316 |  … $results += Get-AzRoleAssignment -Scope $scope -WarningAction Silentl …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation returned an invalid status code 'BadRequest'

##[error]PowerShell exited with code '1'.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.5                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefaultÔÇª}
Script     0.13.0                Az.ResourceGraph                    {Search-AzGraph, Get-AzResourceGraphQuery, New-AzResourceGraphQuery, Remove-AzResourceGraphQueryÔÇª}
Script     6.9.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeploymentÔÇª}
```

### Error output

```PowerShell
N/a
```

**Comment by Acenl12** [comment]
See also this issue: https://github.com/Azure/enterprise-azure-policy-as-code/issues/314

**Comment by isra-fel** [comment]
I see that the original issue has been resolved. Do you need further assistance? @Acenl12

**Comment by Acenl12** [comment]
@isra-fel @techlake I was asked by Heinrich to test with -Debug and then we don't get error we got earlier, both locally on my machine and my coworkers machine and in our our azure pipelines

**Comment by techlake** [comment]
That was an intermediate version which also worked

Please replace this code:
```ps1
$subscriptionId = $scope.Replace("/subscriptions/", "")
$null = Set-AzContext -SubscriptionId $subscriptionId -ErrorAction SilentlyContinue
$null = Set-AzContext -SubscriptionId $subscriptionId -Tenant $PacEnvironment.tenantId
$results += Get-AzRoleAssignment

```

with this one which failed and triggered this issue (for the test):
```ps1
$results += Get-AzRoleAssignment -Scope $scope -Verbose
```

Afterwards switch it back to the 4 lines working code (I would comment out those lines)

Send us the debug output when it fails
