### ISSUE TITLE
TenantLevel switch in Invoke-AzureRmResourceAction command is ignored.

### ISSUE THREAD

**Issue by alancastellanos** [Azure/azure-powershell#2263]
It looks like the switch gets ignored, which is evident by the confirmation.

`Are you sure you want to invoke the 'action' action on the following resource: /subscriptions/B5D6D8E5-12C9-4772-966C-1C8433BBED45/providers/Microsoft.Powerapps`

The `subscription/guid` part shouldn't be included.

**Comment by cormacpayne** [comment]
@ravbhatnagar ping
