### ISSUE TITLE
The 'New-CosmosDbContext' command was found in the module 'CosmosDB', but the module could not be loaded.

### ISSUE THREAD

**Issue by harshbh1998** [Azure/azure-powershell#22650]
### Description

I have an automation pipeline setup in Azure DevOps. In pipeline, I am running a powershell script that uploads the JSON data from azure repos directory to Azure CosmosDB database container. This powerhsell script was  running fine on powershell task version 2.220.0. But after it was upgraded to 2.226.0 (currently 2.226.2), the poweshell task running this script started to get failed by throwing below error:

**The 'New-CosmosDbContext' command was found in the module 'CosmosDB', but the module could not be loaded.**

Snippet of the script is attached herewith.

### Issue script & Debug output

```PowerShell
Write-Output "installing cosmosdb module.."
Install-Module -Name CosmosDB -Force 

Write-Output "setting cosmosdb account context.."
$cosmosDbContext = New-CosmosDbContext -Account $cosmosDbAccount -Database $databaseName -ResourceGroup $rgName
```

### Environment data

```PowerShell
Key   : PSVersion
Value : 7.2.13
Name  : PSVersion


Key   : PSEdition
Value : Core
Name  : PSEdition


Key   : GitCommitId
Value : 7.2.13
Name  : GitCommitId


Key   : OS
Value : Linux 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023
Name  : OS


Key   : Platform
Value : Unix
Name  : Platform


Key   : PSCompatibleVersions
```

### Module versions

```PowerShell
Name              : Az.CosmosDB
Path              : /home/vsts/.local/share/powershell/Modules/Az.CosmosDB/1.11
                    .2/Az.CosmosDB.psd1
Description       : Microsoft Azure PowerShell - CosmosDB service cmdlets for A
                    zure Resource Manager in Windows PowerShell and PowerShell 
                    Core.
                    
                    For more information on CosmosDB, please visit the followin
                    g: https://learn.microsoft.com/azure/cosmos-db/
Guid              : 91832aaa-dc11-4583-8239-bce5fd531604
Version           : 1.11.2
ModuleBase        : /home/vsts/.local/share/powershell/Modules/Az.CosmosDB/1.11
                    .2
ModuleType        : Script
PrivateData       : {PSData}
AccessMode        : ReadWrite
ExportedAliases   : {}
ExportedCmdlets   : {[Get-AzCosmosDBSqlContainer, Get-AzCosmosDBSqlContainer], 
                    [Get-AzCosmosDBSqlContainerThroughput, Get-AzCosmosDBSqlCon
                    tainerThroughput], [Get-AzCosmosDBSqlDatabase, Get-AzCosmos
                    DBSqlDatabase], [Get-AzCosmosDBSqlDatabaseThroughput, Get-A
                    zCosmosDBSqlDatabaseThroughput]…}
ExportedFunctions : {}
ExportedVariables : {}
NestedModules     : {}
```

### Error output

```PowerShell
NA
```

**Comment by navba-MSFT** [comment]
@harshbh1998 Thanks for reaching out to us and reporting this issue. Could you please remove the existing cosmos db powershell module and then install the new version of this module and check:

> **Uninstall-Module -Name CosmosDB -Force**

> **Install-Module -Name Az.CosmosDB -AllowPrerelease**

https://www.powershellgallery.com/packages/Az.CosmosDB/2.0.5-preview

After installing this version, you can try the above command and check if that works.

**Comment by harshbh1998** [comment]
It tried the way you recommended, but it showed below warning in pipeline when I tried to install using your command:

**WARNING: User declined to install module (Az.CosmosDB).**

Therefore, the task got failed with below error:

The term 'New-CosmosDbContext' is not recognized as a name of a cmdlet,
     | function, script file, or executable program. Check the spelling of the
     | name, or if a path was included, verify that the path is correct and try
     | again.

**Comment by navba-MSFT** [comment]
@harshbh1998 Thanks for the update. Please run the command with` -Force` switch as shown below:

> **Install-Module -Name Az.CosmosDB -AllowPrerelease -Force**

**Comment by harshbh1998** [comment]
I tried the way you recommended, and got below error in pipeline:
**The term 'New-CosmosDbContext' is not recognized as a name of a cmdlet,
     | function, script file, or executable program. Check the spelling of the
     | name, or if a path was included, verify that the path is correct and try
     | again.**

Please have a look.

**Comment by navba-MSFT** [comment]
@harshbh1998 Thanks for getting back. Could you please follow the action plan mentioned [here](https://stackoverflow.com/questions/73075977/insert-document-in-cosmos-db-using-powershell-sql-api-using-azure-devops-cli-t) and check if that helps ? Awaiting your reply.

**Comment by isra-fel** [comment]
Hey @harshbh1998 this cmdlet and module CosmosDB is not in the scope of this repository - it's not part of Azure PowerShell. I recommend submitting an issue to https://github.com/PlagueHO/CosmosDB
cc @PlagueHO
