### ISSUE TITLE
[Doc]: An information of "-Expires" does not apply to creating the KEK.

### ISSUE THREAD

**Issue by futnag0** [Azure/azure-powershell#22654]
### Description

This information does not apply to creating the KEK.
KEK is generated with the expiration date (only 2 days).
======================================
-Expires
Specifies the expiration time, as a DateTime object, for the key that this cmdlet adds. This parameter uses Coordinated Universal Time (UTC). To obtain a DateTime object, use the Get-Date cmdlet. For more information, type Get-Help Get-Date. If you do not specify this parameter, the key does not expire.

Add-AzKeyVaultKey:
https://learn.microsoft.com/en-us/powershell/module/az.keyvault/add-azkeyvaultkey?view=azps-10.2.0#-expires
======================================

<Test result>
PS /home/XXXXXXX> Add-AzKeyVaultKey -VaultName XXXXXXX-Name XXXXXXX-Destination HSM -Size 2048 -KeyOps "import"

Vault/HSM Name : XXXXXXX
Name           : XXXXXXX
Key Type       : RSA
Key Size       : 2048
Curve Name     : 
Version        : 340ec2c3b7b240ed93cd709dd1e22b05
Id             : https://XXXXXXX.vault.azure.net:443/keys/XXXXXXX/XXXXXXX
Enabled        : True
Expires        : 8/27/2023 1:33:06 AM
Not Before     : 
Created        : 8/25/2023 1:33:06 AM
Updated        : 8/25/2023 1:33:06 AM
Recovery Level : CustomizedRecoverable+Purgeable
Release Policy : 
Tags           :

**Comment by isra-fel** [comment]
We need to work with Key Vault team to understand if setting the Expire property for a Key Exchange Key (KEK) is different from a normal key. If there's anything worth a note,  let's update the ref doc. @BethanyZhou

**Comment by jlichwa** [comment]
There is nothing specific to KEK vs normal key and both should expire within 2 years.

Key Vault Product Team

**Comment by futnag0** [comment]
I want to share my test result. The document mentions "If you do not specify this parameter, the key does not expire.", but the KEK is generated with 2 days expiration.

=====================================
- Normal Key
PS /home/futoshi> Add-AzKeyVaultKey -VaultName XXXXXXX-Name XXXXXXX -Destination HSM -Size 2048 -KeyOps "encrypt"

Vault/HSM Name : XXXXXXX
Name           : XXXXXXX
Key Type       : RSA
Key Size       : 2048
Curve Name     : 
Version        : 964eef892da843b29701d2dca64b4f98
Id             : https://XXXXXXX.vault.azure.net:443/keys/XXXXXXX/XXXXXXX
Enabled        : True
Expires        : 
Not Before     : 
Created        : 8/29/2023 12:54:18 AM
Updated        : 8/29/2023 12:54:18 AM
Recovery Level : CustomizedRecoverable+Purgeable
Release Policy : 
Tags           : 
=================
PS /home/futoshi> Add-AzKeyVaultKey -VaultName XXXXXXX-Name XXXXXXX -Destination Software -Size 2048

Vault/HSM Name : XXXXXXX
Name           : XXXXXXX
Key Type       : RSA
Key Size       : 2048
Curve Name     : 
Version        : 168d1de990434e2796c8e45cfa1f5078
Id             : https://XXXXXXX.vault.azure.net:443/keys/XXXXXXX/XXXXXXX
Enabled        : True
Expires        : 
Not Before     : 
Created        : 8/29/2023 12:56:03 AM
Updated        : 8/29/2023 12:56:03 AM
Recovery Level : CustomizedRecoverable+Purgeable
Release Policy : 
Tags           : 
=====================================
- KEK
PS /home/XXXXXXX> Add-AzKeyVaultKey -VaultName XXXXXXX-Name XXXXXXX-Destination HSM -Size 2048 -KeyOps "import"

Vault/HSM Name : XXXXXXX
Name : XXXXXXX
Key Type : RSA
Key Size : 2048
Curve Name :
Version : 340ec2c3b7b240ed93cd709dd1e22b05
Id : https://XXXXXXX.vault.azure.net:443/keys/XXXXXXX/XXXXXXX
Enabled : True
Expires : 8/27/2023 1:33:06 AM
Not Before :
Created : 8/25/2023 1:33:06 AM
Updated : 8/25/2023 1:33:06 AM
Recovery Level : CustomizedRecoverable+Purgeable
Release Policy :
Tags :
