### ISSUE TITLE
Https Forward using Azure Application Gateway

### ISSUE THREAD

**Issue by alexandrev** [Azure/azure-powershell#2267]
I'm trying to configure an Application Gateway to redirect all the traffic that matches a particular path (for example: "/register") to an existing external site. When I do this configuration and I redirect the traffic to a HTTP Endpoint there is no problem and everything works as expected.

But I cannot do the same if the endpoint is HTTPS instead of HTTP. I tried to configure the BackendHttpSettings to redirect the trafic to the 443 port but doesn't work. I also tried to specify the protocol as Https but it seems it does not recognize this value.

Is there anyway to redirect the traffic to an HTTPS endpoint or is it not possible with the current release?

**Comment by markcowl** [comment]
@deepakrajendranmsft Can you take a look?

**Comment by DeepakRajendranMsft** [comment]
@markjbrown could you please help in routing.

**Comment by amitsriva** [comment]
HTTPS to the backend is not supported currently. We are working on enabling this.

**Comment by alexandrev** [comment]
Thanks for the information @amitsriva. That really explains the issue. But, I don't understand one thing. Could you share the ETA of this feature or a feature roadmap for the component? 

Thanks in advance, I'm going to close the issue.

**Comment by markcowl** [comment]
@alexandrev Reopening the issue, this way it can be added to a milestone as appropriate for planned delivery.

**Comment by alexandrev** [comment]
Perfect!

**Comment by markjbrown** [comment]
will get a date.

**Comment by markjbrown** [comment]
Update: No dates to share on this. As @amitsriva  mentioned this is on our roadmap. Will update this when there is new information.

**Comment by olafsurewaard** [comment]
Any updates with respect to this topic? 

We currently implementing an Application Service Environment with an Application Gateway in front as a reverse proxy. SSL offloading on the Application Gateway and accessing applications in the Application Service Environment  using HTTP works well. However we plan to make traffic between Gateway and Application Service Environment HTTPS as well and do not get it to work at the moment.

**Comment by nareshhamal** [comment]
Probably, this link ( https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-end-to-end-ssl-powershell) help you to resolve issues (end to end SSL )

**Comment by markjbrown** [comment]
@DeepakRajendranMsft Deepak, can you assign amitsriva? For some reason I'm unable to.

**Comment by maddieclayton** [comment]
@akshaysngupta Can you take a look at this issue?

**Comment by akshaysngupta** [comment]
HTTPS on the backend is now supported.
