### ISSUE TITLE
[Compute]: Change default Public IP SKU for "New-AzVM"

### ISSUE THREAD

**Issue by cburuzie** [Azure/azure-powershell#22688]
### Description of the new feature

Description: Customer's ask is to change Public IP SKU defaults to Standard for PS.

Command that needs to be changed: New-AzVM

When a user runs New-AzVM without specifying PublicIpSku, the Public IP that is created is a Basic IP. The ask here is to make the default SKU to be Standard IP. 

Business Impact: This is a requirement for Basic IP Retirement which was announced last September 2022 - [Upgrade to Standard SKU public IP addresses in Azure by 30 September 2025—Basic SKU will be retired | Azure updates | Microsoft Azure](https://azure.microsoft.com/en-us/updates/upgrade-to-standard-sku-public-ip-addresses-in-azure-by-30-september-2025-basic-sku-will-be-retired/).

Previously related completed issue: #15574

**Comment by isra-fel** [comment]
Not sure if you are aware of this @bilaakpan-ms @sandido @haagha @grizzlytheodore

**Comment by cburuzie** [comment]
@TravisCragg-MSFT Do we have any update here? Note this change is needed for the Basic IP Retirement which we announced back in September 2022.

**Comment by cburuzie** [comment]
@TravisCragg-MSFT Pinging on this. @isra-fel Do you happen to have a update here?

**Comment by TravisCragg-MSFT** [comment]
@cburuzie  Closing this issue as it is being handled internally.
