### ISSUE TITLE
Need help with the PS script to fetch some data

### ISSUE THREAD

**Issue by utkarshdemon** [Azure/azure-powershell#22690]
### Description

Hello All,

I need to fetch the details from azure having 1k+ VMs deployed, please help me if we can create any PS script to get the data:

Query: Need a count and names of Windows 2012 VMs using "Azure Hybrid Benefit for Windows" as "OS licensing benefit"

**Comment by kilasuit** [comment]
This is also a [discussion](https://github.com/Azure/azure-powershell/discussions/22689) so this issue should be closed and help provided in the discussion instead

**Comment by utkarshdemon** [comment]
@kilasuit can you please assist over discussion?
