### ISSUE TITLE
Get-AzureStorageAccount fails if there are lots of storage accounts

### ISSUE THREAD

**Issue by chezhang** [Azure/azure-powershell#2272]
My subscription has more that 100 storage accounts.
In previous version (0.9.0 or 1.0.3 etc.), Get-AzureStorageAccount works well.
In current version (1.3.2 or later), the command always fails with error: 

> Get-AzureStorageAccount : TooManyRequests: Too many requests received. Retry after some time.

It seems that the command in newer version requests more info(keys) after receiving the storage accounts info, which leads to a lot of requests(related with the number of storage accounts in my subscription) in a short time.

**Comment by markcowl** [comment]
@blueww Using this to track the current fix.

**Comment by blueww** [comment]
This is Known bug: RDBug 6413346:[PSH] Get-AzureStorageAccount failed with TooManyRequests when there are 85+ accounts in a subscription

There is also a candidate fix targeted for this release. 

David Berg has give a workaround :
Workarounds are going back to an earlier version of PowerShell, using REST API directly, or using Find-AzureRMResource to get the list of storage accounts, and then look up additional information on an as needed basis (and not more than 300 or so RDFE REST calls per 5 minutes).

**Comment by markcowl** [comment]
fixed in #2298
