### ISSUE TITLE
AzureRMAD* cmdlets fail when using token based authentication

### ISSUE THREAD

**Issue by antmeehan** [Azure/azure-powershell#2273]
`New-AzureRmADApplication : Unable to cast object of type 'Microsoft.Azure.TokenCloudCredentials' to type 'Microsoft.Azure.Common.Authentication.AccessTokenCredential'.`

From http://stackoverflow.com/a/36068690/1462905

> This is an issue (i.e. bug) when using token based authentication with the AzureRMAD* cmdlets. When you run the script from VS, VS uses the token you have from the VS sign-in to avoid prompting for auth. To work around it, you have to run it outside of VS using credentials.
>
> There is an internal work item tracking this but if you want to monitor progress you can file an issue 

Are you able to share how this fix is going?

**Comment by ravbhatnagar** [comment]
Seems like a VS issue. @bmoore-msft to comment on this.

**Comment by bmoore-msft** [comment]
The latest I see is tracked here: https://github.com/Azure/azure-powershell/issues/2140  - let's track the work in that issue.
