### ISSUE TITLE
Re-open of #1312

### ISSUE THREAD

**Issue by thehuxman** [Azure/azure-powershell#2276]
Bug 1312 was raised for a missing cmdlet of get-azurermdatadisk or get-azurermdisk.  It was noted in the closure that disks are a property of the VM object.

This still leaves a gap where "get-azuredisk | where attachedto -eq $null" used to work.  Was particulaly useful for find unused disks or in one instance a VM was deleted and we could find the disks quickly and restore service.

**Comment by markcowl** [comment]
@sighkay can you take a look?

**Comment by singhkays** [comment]
@thehuxman The concept of disks does not exist in ARM atm. The platform team is working on bringing back this functionality. We'll have cmdlets when the platform releases this.

**Comment by ward0** [comment]
Any update on this one pls? I'm trying to find a way how many data disks i have assigned vs max assigned in RM mode..

**Comment by singhkays** [comment]
@ward0 Are you trying to find out how many data disks you've assigned to your VM? 

That can be done using below

```powershell
$vm.StorageProfile.DataDisks.Count
```

**Comment by ward0** [comment]
@singhkays Nope.

I want to know the difference between a OS disk and a data disk.
I do this for now(not fail proof):

$VmStatus = Get-AzurermVM -Name $vm.Name -ResourceGroupName $vm.ResourceGroupName -Status

$CurrentDisks = $vmstatus.Disks.count -1

We will only use this script on 'clean' Azure VM's where there are no datadisks yet created. So i can "safely" do a -1.

If i would be able to use get-azurermdatadisk i would have a fail proof knowing of how many data disks i can add what number i could give them.

So a D2 would have data1 and data2 when setting the name.

**Comment by singhkays** [comment]
@ward0 Why are you looking at the VM Instance view (with -Status switch) instead of the model view? The model view will clearly tell you how many data disks are attached to the VM and their LUNs

**Comment by ward0** [comment]
@singhkays : Your correct.

I can ask like this:

$VmStatus = Get-AzurermVM -Name $vm.Name -ResourceGroupName $vm.ResourceGroupName
$vmstatus.StorageProfile.DataDisks

I'l change my script :)
