### ISSUE TITLE
[Feature]: Add TimeCreated property to Vmss VM model

### ISSUE THREAD

**Issue by bmuller4** [Azure/azure-powershell#22774]
### Description of the new feature

The feature request https://github.com/Azure/azure-powershell/issues/19478 was submitted to add the timeCreated property for VMs and VM scale sets. This feature request is to also add it to VM scale set VMs, specifically the [PSVirtualMachineScaleSetVM Class](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.compute.automation.models.psvirtualmachinescalesetvm?view=az-ps-latest) so that the property can be retrieved via [Get-AzVmssVM](https://learn.microsoft.com/en-us/powershell/module/az.compute/get-azvmssvm?view=azps-10.2.0).

Without this property it's not possible to determine when a scale set VM was created using the Azure PowerShell module.

**Comment by TravisCragg-MSFT** [comment]
@bmuller4 Thank you for your feedback! we are looking into this request now.

**Comment by Drewm3** [comment]
@bmuller4, the TimeCreated property exists for all VMs, VM Scale Sets and VM instances in VMSS starting with API version 2021-11-01. Below is an example of this for a VMSS instance shown in the portal. Could you let us know if you are looking for something different or did you maybe not know the time created property already existed?

![image](https://github.com/Azure/azure-powershell/assets/2515810/a4b602b1-6c40-41cf-aedf-754bdf71ec0e)

**Comment by bmuller4** [comment]
@Drewm3 You're absolutely correct that is exists foundationally as an object property for VMs, VMSS and VMSS instances but because it is missing from the [PSVirtualMachineScaleSetVM Class](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.compute.automation.models.psvirtualmachinescalesetvm?view=az-ps-latest) this property is not accessible via the [Get-AzVmssVM](https://learn.microsoft.com/en-us/powershell/module/az.compute/get-azvmssvm?view=azps-10.2.0) cmdlet which is what this FR is about.

**Comment by hilaryw29** [comment]
Thanks for the clarification @bmuller4, @Drewm3. Engaging with PowerShell SDK team on this issue.

**Comment by grizzlytheodore** [comment]
fix has been merged. closing this issue
