### ISSUE TITLE
[Doc]: Invoke-AzVmssVMRunCommand

### ISSUE THREAD

**Issue by danespinosa** [Azure/azure-powershell#22770]
### Description

Category: Cmdlet Reference

the -CommandId Parameter although is a string it has to be 1 of many allowed values described here. 
Windows: https://learn.microsoft.com/en-us/azure/virtual-machines/windows/run-command#available-commands
Linux: https://learn.microsoft.com/en-us/azure/virtual-machines/linux/run-command

I think it would be great if in the description of -CommandId there would be a quick row that shows the allowed values and a link to the document above.

Also, there's a bug in the documentation for the RDPSettings command, the indicated value on the documents is RDPSetting but the right value is RDPSettings, I have created a PR to fix that here: https://github.com/MicrosoftDocs/azure-docs/pull/114597

**Comment by Drewm3** [comment]
Nikhil, could you please take a look at this one.

**Comment by nikhilpatel909** [comment]
@Drewm3 Let me verify the documentation and make changes if needed.

**Comment by GabstaMSFT** [comment]
PR has been approved and merged.

@danespinosa can you confirm this has resolved your issue?

**Comment by danespinosa** [comment]
@GabstaMSFT  yes, I made a PR myself and it got merged back in september, I think this issue didn't get closed with the PR, thanks for checking in.
