### ISSUE TITLE
Reset-AzureLocalNetworkGateway XML generated for address space is wrong

### ISSUE THREAD

**Issue by cg6** [Azure/azure-powershell#2279]
This should work: Reset-AzureLocalNetworkGateway -GatewayId $lg.GatewayId -AddressSpace '10.5.8.0/22','10.5.66.0/25' -debug

It results in a request with Body:

```
<UpdateLocalNetworkGatewayParameters xmlns="http://schemas.microsoft.com/windowsazure">
  <AddressSpace xmlns="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
    <string>10.5.8.0/22</string>
    <string>10.5.66.0/25</string>
  </AddressSpace>
</UpdateLocalNetworkGatewayParameters>
```

The command completes without errors but doesn't work. Querying Get-AzureLocalNetworkGateway shows the address space has not been updated.

If I capture the HTTP request, edit it as below and then replay it, the command works and updates the address space config correctly.:

```
<UpdateLocalNetworkGatewayParameters xmlns="http://schemas.microsoft.com/windowsazure">
  <AddressSpace xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
    <a:string>10.5.8.0/22</a:string>
    <a:string>10.5.66.0/25</a:string>
  </AddressSpace>
</UpdateLocalNetworkGatewayParameters>
```

**Comment by markcowl** [comment]
@deepakrajenfranmsft can you take a look

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
