### ISSUE TITLE
Definition of New-AzureVirtualNetworkGatewayConnection shows EnableBgp parameter is optional, but command fails if it is not specified

### ISSUE THREAD

**Issue by cg6** [Azure/azure-powershell#2280]
This code has worked in a previous version
```
New-AzureVirtualNetworkGatewayConnection  -gatewayConnectionName "$source-to-$dest" `
                                              -gatewayConnectionType IPsec `
                                              -sharedKey $lgwconnection.SharedKey `
                                              -virtualNetworkGatewayId $lgwconnection.VirtualNetworkGatewayId `
                                              -connectedEntityId $lgwconnection.ConnectedEntityId
```

Now it returns: 
> New-AzureVirtualNetworkGatewayConnection : Value cannot be null.
> Parameter name: value

This worked
```
    New-AzureVirtualNetworkGatewayConnection  -gatewayConnectionName "$source-to-$dest" `
                                              -gatewayConnectionType IPsec `
                                              -sharedKey $lgwconnection.SharedKey `
                                              -virtualNetworkGatewayId $lgwconnection.VirtualNetworkGatewayId `
                                              -connectedEntityId $lgwconnection.ConnectedEntityId `
                                              -EnableBgp $false
```

The definition shows EnableBgp is optional:
```
get-command New-AzureVirtualNetworkGatewayConnection |% definition

New-AzureVirtualNetworkGatewayConnection [-ConnectedEntityId] <string> [-GatewayConnectionName] <string> [-GatewayConnectionType] <string> [[-RoutingWeight] <int>] [[-SharedKey] <string>] [-VirtualNetworkGatewayId] <string> [[-EnableBgp] <string>] [-Profile <AzureSMProfile>] [<CommonParameters>]
```

**Comment by cg6** [comment]
This bug was introduced here:
https://github.com/Azure/azure-powershell/commit/659f2cf0243decaa898afa632498bb4d5eac175c

The EnableBgp parameter was changed from a boolean to a string, then later bool.Parse(EnableBgp) is called. bool.Parse returns the "Value cannot be null" error if EnableBgp is null.

bool.Parse could also return an unhandled exception if EnableBgp is not equivalent to TrueString or FalseString. If EnableBgp is going to be a string parameter there should be a validator against it. However I don't see why it shouldn't just remain a boolean.

**Comment by lamchester** [comment]
Thanks for catching this! 

When working on BGP over IPsec cmdlets, I originally started with EnableBgp as a bool. But then specifying -EnableBgp 1 or -EnableBgp 0 just felt funny (PS wouldn't accept true or false strings for a boolean), so I made it a string instead and called bool.Parse. 

Yeah...this needs to get fixed.
https://github.com/Azure/azure-powershell/pull/2287

**Comment by markcowl** [comment]
@deepakrajendranmsft can you take a look

**Comment by lamchester** [comment]
That pull request linked above (https://github.com/Azure/azure-powershell/pull/2287) should have fixed it, and has already been merged. I've validated the fix locally. There shouldn't be any need for Deepak to look, unless it didn't fix the issue?

**Comment by markjbrown** [comment]
@cg6 Please Closing as issue is reported fixed. If not please reopen. Thanks.
