### ISSUE TITLE
Need help with PS script 

### ISSUE THREAD

**Issue by utkarshdemon** [Azure/azure-powershell#22828]
### Description

Hello All,

I need to fetch the details from azure having 1k+ VMs deployed, please help me if we can create any PS script to get the data:

Query: Need a report of all the VMs under a particular subscription using the VM extension "Microsoft.SqlServer.Management.SqlIaaSAgent"

**Comment by TravisCragg-MSFT** [comment]
@utkarshdemon Thank you for your feedback! For assistance with scripting and how-to questions, please ask this at [Microsoft Q&A under the Virtual-Machines tag](https://learn.microsoft.com/en-us/answers/tags/94/azure-virtual-machines).
