### ISSUE TITLE
Would like a Get-AzureRMResourceTypes cmdlet

### ISSUE THREAD

**Issue by vhusker** [Azure/azure-powershell#2282]
I have been driving myself crazy trying to find a list of AzureRMResourceTypes to use in cmdlets like New-AzureRMResource.  Having this cmdlet just list them for users would be very beneficial I think.  If there is already something similar to this please let me know because I can't seem to find it.

**Comment by ravbhatnagar** [comment]
Get-AzureRmResourceProvider is your friend here.

**Comment by vhusker** [comment]
I eventually figured that out.  On some level it makes sense, but someone just starting out who is relatively unfamiliar with Azure and the ResourceManager is going to have a hard time figuring that out.  The goal should be to make things as easy as possible on the users, and this is just much more difficult than it needs to be.

**Comment by ravbhatnagar** [comment]
Agreed, and we do have a few other features inflight which will help with such things. In addition, you should be able to quickly figure this out from the docs. So may be there is an opportunity to improve that as well. Closing this issue for now. Please re-open if you think otherwise. Thanks!
