### ISSUE TITLE
Get the lists more than 100 VMs located in multiple region

### ISSUE THREAD

**Issue by sohyuniiii** [Azure/azure-powershell#22837]
### Description

When run the command(Get-AzVM -Status) in PowerShell to get the lists more than 100 VMs deployed in multiple region, it shows that “WARNING: There are more than 100 VMs in the result.  Only the statuses of 100 VMs are shown to avoid throttling.  To get the actual status of each VM, please provide a VM name with -Status parameter.”.   
However when run the command (Get-AzVM -Status) to get the lists more than 100 VMs in one region, it doesn’t show that message. 

Do we have any limitations when get the list more than 100 VMs located in multiple regions?

**Comment by TravisCragg-MSFT** [comment]
@sohyuniiii Thank you for your question! I am following up now to get more information on these limits.

**Comment by TravisCragg-MSFT** [comment]
@sohyuniiii Unfortunately we do not document these limits, but we are actively working to remove them. 

I have confirmed that is a hard limit in PowerShell, but after speaking with our teams, this limit likely no longer needs to be there. We will be looking to remove this limits in new versions of PowerShell.

**Comment by sohyuniiii** [comment]
@TravisCragg-MSFT , Thank you so much for update! :)

**Comment by albert-widjaja** [comment]
@TravisCragg-MSFT ,
The issue still persists today.

`WARNING: There are more than 100 VMs in the result.  Only the statuses of 100 VMs are shown to avoid throttling.  To get the actual status of each VM, please provide a VM name with -Status parameter.`

**Comment by haagha** [comment]
It's not a limit, it's just a warning with a prompt to prevent throttling. Due to inactivity closing this issue.
