### ISSUE TITLE
Get-AzureRmVMImage Name property of returned object(s) is wrong

### ISSUE THREAD

**Issue by iricigor** [Azure/azure-powershell#2284]
Currently, Get-AzureRmVMImage returns object in which Name and Version have the same values. You may check the example below, but it will be the same for all images.

Get-AzureRMVMImage -location "Central us" `
                   -publisherName "MicrosoftWindowsServer"`
                   -sku "2012-R2-Datacenter" `
                   -Offer windowsserver`
                   -Version 4.0.20160229 `
                   | Select Name,Version

Name         Version     

---

4.0.20160229 4.0.20160229

**Comment by iricigor** [comment]
Returned object is also missing properties **Label** and **PublishedDate** which were very useful in old Azure PoSh.

**Comment by markcowl** [comment]
@singhkay can you take a look?

**Comment by singhkay** [comment]
Repro'd as a bug, thank you for reporting! Added to our backlog.

**Comment by maddieclayton** [comment]
@singhkays Was this fixed? If so, can you close the issue?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
