### ISSUE TITLE
[Eng]: An error occurred while sending the request while using Get-AzPrivateDnsVirtualNetworkLink

### ISSUE THREAD

**Issue by mhkprwl** [Azure/azure-powershell#22859]
### Description

Hi Team,

I'm running a loop for around 200 RGs and each initiates **Get-AzPrivateDnsVirtualNetworkLink** command. I'm randomly getting below the error: **An error occurred while sending the request**. If I reinitiate the pipeline to execute same loop it runs fines.

How can I solve this intermittent issue?

**Comment by isra-fel** [comment]
@mhkprwl could you try enabling the debug log or monitor the network traffic so we can get a better idea of what happened for the failed cases.
