### ISSUE TITLE
[Eng]: CI check whether SDK was generated not functioning properly

### ISSUE THREAD

**Issue by VeryEarly** [Azure/azure-powershell#22875]
### Description

track 1 SDK with manual changes were able to pass CI.
For example:
https://github.com/Azure/azure-powershell/pull/22637

CI should be able to block such changes.

**Comment by isra-fel** [comment]
We should try modifying a generated file and submit a PR to verify the check.
Also check if the check supports sdk generated by autorest.powershell

**Comment by isra-fel** [comment]
@NoriZC please try to reproduce this issue, and discuss the plan of checking SDKs generated by a.p.
