### ISSUE TITLE
Save-AzureRMProfile should support exporting profile to in-memory object

### ISSUE THREAD

**Issue by blumu** [Azure/azure-powershell#2290]
Azure access tokens are not preserved across Azure Powershell jobs (Start-Job). This makes it hard to automate certain Azure tasks (e.g. like parallel replication of files to storage accounts).
The only workaround is to use `Save-AzureRmProfile` to export the context to disk and import it back in the children jobs using `Select-AzureRmProfile`. This is unsecure however as the profile file containing the token becomes visible on disk and may not be cleaned up properly if the powershell session is interrupted.

Instead `Save-AzureRMProfile` and `Select-AzureRmProfile` should support export/import to in-memory object. Possible syntax:

    $profile = Save-AzureRmProfile -PassThru

    ...

    Select-AzureRmProfile -Profile $profile

**Comment by markcowl** [comment]
@blumu Note that ```Add-AzureRmAccount``` returns a profile

**Comment by blumu** [comment]
@markcowl `Add-AzureRmAccount` and `Get-AzureRmContext` return an object of type PSAzureContext which is not serializable and therefore cannot be passed as a parameter to `Start-Job`.

**Comment by markcowl** [comment]
@blumu Correct.  This is being tracked in a separate issue..  Right now the best way to do start job is to save the profile to a file and then select it as part of your job script.  Once this is resolved, we will start implementing -AsJob for long-running cmdlets.

**Comment by markcowl** [comment]
Add-AzureRMAccount returns a PSAzureProfile - only the context is displayed on the screen

**Comment by blumu** [comment]
@markcowl Could you add a link to the separate issue you are referring to?
You are right: Add-AzureRMAccount returns a PSAzureProfile but it's still unclear how to serialize it to string and deserialized it back while preserving the underlying Azure token.

**Comment by markcowl** [comment]
The existing issue is #1835 since this covers making authentication classes powershell serializable for PSJobs, I am closing this issue in favor of the earlier one.
