### ISSUE TITLE
Az.NetAppFiles output changed for Throughput fields

### ISSUE THREAD

**Issue by msftphleiten** [Azure/azure-powershell#22945]
### Description

It seems that one of the latest versions changed the behavior of Az.NetAppFiles, ThroughputMibps is blank while ActualThroughputMibps is suddenly used.
With older versions (e.g. 0.7) it is still ThroughputMibps 

Version 0.13.1
![image](https://github.com/Azure/azure-powershell/assets/37079522/bb4ca35a-010c-4d95-aa5a-0cf28e40b835)
![image](https://github.com/Azure/azure-powershell/assets/37079522/2c9ba28f-b5a6-4a83-93ff-2c2be47b7767)

Version 0.7.0
![image](https://github.com/Azure/azure-powershell/assets/37079522/164f9b65-33b0-4a48-b8cc-14f03f1ad0ba)

### Issue script & Debug output

```PowerShell
-
```

### Environment data

```PowerShell
7.3.8
```

### Module versions

```PowerShell
0.13.1
```

**Comment by isra-fel** [comment]
Thanks for reporting!
You see Azure PowerShell follows semantic versioning. Az.NetAppFiles hasn't GAed, indicated by its version starts with 0. So the module isn't yet stable and its API may be subject to change.
That said, we'll work with the owner team to GA the module for a better user experience.

**Comment by audunn** [comment]
For a little clarification on the change:
actualThroughputMibps: Readonly property. Actual throughput in MiB/s for auto qosType volumes calculated based on size and serviceLevel

throughputMibps: Maximum throughput in MiB/s that can be achieved by this volume and this will be accepted as input only for manual qosType volume

As @isra-fel notes we are working go GA the module in a future version.

**Comment by msftphleiten** [comment]
@audunn thanks for the reply, I understand your argument.
my challenge is that it seems that the behavior of the module has changed, we were working with it for years and were able to get the throughput of a volume using the command.
this suddenly stopped working.

ANF was released more than 4 years ago, so I think it is expected that the PowerShell modules reached a certain stability and does not have any sudden changes. If you want to change the behavior PowerShell has the option to announce breaking changes.

what is the recommended way to query a volume and get the same value for throughput in MiB/s similar to the Azure portal?

**Comment by audunn** [comment]
Apologies for the inconvenience. 
Actualthroughput is a service calculated (readonly) property for auto QOS type volumes where useres cannot change the throughputMibps directly.
throughputMibps is an updatable property used for Manual QOS volumes.

https://learn.microsoft.com/en-us/azure/azure-netapp-files/manage-manual-qos-capacity-pool
