### ISSUE TITLE
-ResourceGroupName parameter should not be mandatory for Get-AzureRmDnsZone

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2297]
-ResourceGroupName parameter should not be mandatory for Get-AzureRmDnsZone

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by jtuliani** [comment]
Agree 100%.  We're already tracking this, it will be fixed in a future release.

**Comment by markjbrown** [comment]
This is a dup for #1396. Closing, will track from that one. Thanks Trevor for reporting.
