### ISSUE TITLE
Get-AzStorageBlob CloudBlob Properties are empty with newer versions

### ISSUE THREAD

**Issue by KrX3D** [Azure/azure-powershell#22988]
### Description

Hi, i got an problem with Az.Storage

 

I use this code, to get the MD5 Hash of an file in a Azure Blob:

$m = "C:\OSI\TMP\Az.Storage\4.8.0\Az.Storage.psd1"

import-Module -Name $m -Force

$APath = "DRV/AMD/AMD.7z"

$global:storageAccount = "StoACC"

$global:Container = "Container"

$global:MasterKey = "KEY"

$ctx = New-AzStorageContext -StorageAccountName $global:storageAccount -StorageAccountKey $global:MasterKey

$var = (Get-AzStorageBlob -Blob $APath -Container $global:Container -Context $ctx).ICloudBlob.Properties.ContentMD5

 

Which gives me this result:

BHQ+L0HPpiQePp0DVgXdlA==

 

I updates my modules now and when I import this module:

$m = "C:\OSI\TMP\Az.Storage\5.10.1\Az.Storage.psd1"

 

The same code from above just does not give me the Hash.

 

For 4.8.0 i can see this yellow output for a second:

 

BILD

 

 

Also the $var.GetType() is:

 

IsPublic IsSerial Name                                     BaseType

-------- -------- ----                                     --------

True     True     String                                   System.Object

 

 

 

For 5.10.1 i dont see that yellow output and $var.GetType() is:

 

InvalidOperation: You cannot call a method on a null-valued expression.

 

 

I tested it with the old Az.Accounts and the new and both work for the 4.8 (since they are loaded via Az.Storage)

Az.Accounts

2.9.1 – OK

2.13.1 – OK

 

And those I tested so far:

 

Az.Storage

4.8.0 – OK

4.9.0 – OK

 

5.1.0 -Not OK

5.4.1 -Not OK

5.6.0 -Not OK

5.8.0 -Not OK

5.9.0 -Not OK

5.10.1 -Not OK

 

### Issue script & Debug output

```PowerShell
$m = "C:\OSI\TMP\Az.Storage\4.8.0\Az.Storage.psd1"

import-Module -Name $m -Force

$APath = "DRV/AMD/AMD.7z"

$global:storageAccount = "StoACC"

$global:Container = "Container"

$global:MasterKey = "KEY"

$ctx = New-AzStorageContext -StorageAccountName $global:storageAccount -StorageAccountKey $global:MasterKey

$var = (Get-AzStorageBlob -Blob $APath -Container $global:Container -Context $ctx).ICloudBlob.Properties.ContentMD5
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
I only have az.storage and az.accounts locally copied
```

**Comment by blueww** [comment]
@KrX3D 

This is same issue as https://github.com/Azure/azure-powershell/issues/20326#issuecomment-1333100195
Please see the above link for the reason, workaround of this behavior.
And please note, this is a breaking change, so we have followed the breaking change process for this change.

**Comment by isra-fel** [comment]
Closing the issue as of duplication.
