### ISSUE TITLE
[Feature]: Don't use warning output stream for `Connect-AzAccount -UseDeviceAuthentication`

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-powershell#23013]
### Description of the new feature

I'd like to be able to silence **actual** warning messages that `Connect-AzAccount` may produce, like when connecting with `-Tenant` without specifying `-Subscription`.

But if using `-UseDeviceAuthentication`, the code is outputted to the warning stream.

Could the message outputting the code needed for device login be outputted to a different stream? Information maybe, with `-InformationAction Continue` unless overridden?

### Proposed implementation details (optional)

Move device code auth flow messages to information stream?

**Comment by isra-fel** [comment]
Thanks for reporting
Duplicated of https://github.com/Azure/azure-powershell/issues/16963
Will investigate with higher priority.
