### ISSUE TITLE
[Feature]: Connect-AzContainerRegistry should have parameter to get the actual token (equivalent to `az acr login --expose-token` )

### ISSUE THREAD

**Issue by J0F3** [Azure/azure-powershell#23026]
### Description of the new feature

With the Azure CLI you can get an access token for access an Azure Container Registry  with the parameter ` --expose-token` (e.g. `az acr login -n myregistry --expose-token`)

The help of the azure cli says:
> If you only need an access token and do not want to install Docker, specify '--expose-token'

This is very useful in scenarios where docker is and can not be installed (e.g. in CI/CD Pipelines).
A specific use case would be also the publishing of a container image with the dotnet CLI where you have to explicitly login with `docker login`. Otherwise the dotnet CLI can not correctly read the credentials. 
(See also: https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-7-0#containerregistry and https://github.com/dotnet/sdk-container-builds/issues/454#issuecomment-1576429670)

The Azure PowerShell is currently lacking this functionality.

### Proposed implementation details (optional)

Add a Parameter `-ExposeToken` to the Connect-AzContainerRegistry to get the actual token value directly (and without the need to have docker installed).

(Similar functionality to Azure CLI resp. Get-AzAccessToken).

**Comment by isra-fel** [comment]
Thanks for the feedback! @Nickcandy can you look into this?
