### ISSUE TITLE
Login-AzureRmAccount UI - We require a web browser plugin but it won't install here.

### ISSUE THREAD

**Issue by frachel** [Azure/azure-powershell#2303]
For our corporate SSO, every time we connect with an unregistered browser we have to get a security code from Symantec Validation and ID protection. We have the option of saving/remembering the browser. If we do that it needs to download the "Symantec Authentication Client Plugin". The file downloads and I get a popup about running or saving the file. If I hit "Run", Powershell immediately gives me an error "Add-AzureRmAccount : The browser based authentication dialog failed to complete for an unknown reason. StatusCode: 
200", however the plugin installer did run. But it must not be working, since the next time I'll get asked again.

Any thoughts on how to get around it?

**Comment by markcowl** [comment]
@frachel The only thing I can immediately offer is using an alternate authentication mechanism, like service principal.  I have not seen this error, and we do not control the display of this dialog, (adal.net does).  WIll ask around and cross-post this in their repo.

**Comment by markcowl** [comment]
Potential workaround is provided in the referenced bug in ADAL.  Please try this out and let me know if we need to reopen this bug with them.  Cloding for now.
