### ISSUE TITLE
[Feature]: Get-AzKeyVaultSecret should allow to fetch by ID

### ISSUE THREAD

**Issue by ishepherd** [Azure/azure-powershell#23053]
### Description of the new feature

Because Key Vault secrets have a global unique ID and it's just a URL.

We tend to paste that URL around the place, e.g. in app configuration. It would be convenient if the `Get-AzKeyVaultSecret` supported those URLs.

### What I'd like to do

```powershell
Get-AzKeyVaultSecret -Id https://myvault.vault.azure.net/secrets/MySecret
Get-AzKeyVaultSecret -Id https://myvault.vault.azure.net/secrets/MySecret/03d6fd62056a4790a8982b1a75f320f8
```

### Alternatives

* Helper class. The .NET client provides [KeyVaultSecretIdentifier](https://github.com/Azure/azure-sdk-for-net/blob/d4e9e97501e0515780590fc3d7020d05b47a83cc/sdk/keyvault/Azure.Security.KeyVault.Secrets/src/KeyVaultSecretIdentifier.cs#L14)
* Do it manually ... Kinda ugly:

```powershell
$token = Get-AzAccessToken -ResourceUrl https://vault.azure.net
$headers = @{"Authorization" = "Bearer $($token.Token)"}
$response = Invoke-RestMethod -Uri https://myvault.vault.azure.net/secrets/MySecret/03d6fd62056a4790a8982b1a75f320f8?api-version=7.1 -Headers $headers
```

**Comment by isra-fel** [comment]
Thanks for the feedback 👍 
We'll add it to our backlog.
