### ISSUE TITLE
AzureResourceManager.psd1 is included in several PS packages 

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-powershell#2306]
### Description  
AzureRM.Compute, AzureRM.KeyVault, AzureRM.LogicApp, AzureRM.Network, AzureRM.Sql, AzureRM.Storage, AzureRM.Websites packages include AzureResourceManager.psd1. This should be removed. AzureResourceManager.psd1 package is used in couple of tests that needs to import specific modules instead. After that this file should be deleted from repo and wxi file should be regenerated. 

### Cost (Work Units): 1

**Comment by markcowl** [comment]
Fixed
