### ISSUE TITLE
Get-AzureRmResource by ResourceName and Type doesn't work

### ISSUE THREAD

**Issue by kokajambo** [Azure/azure-powershell#2307]
Get-AzureRmResource by ResourceName and Type doesn't work: it gives me an error **"Get-AzureRmResource : ResourceNotFound : The Resource 'xxxxxxxx' under resource group '<null>' was not found."**
Basically it says it requires ResourceGroupName, but that's not what I'm looking for. Msdn documentation mentions this set of parameters as acceptable: "Parameter Set: Get a resource by name and type."

Also, -ErrorAction SilentlyContinue doesn't work

**Comment by markcowl** [comment]
@ravbhatnagar can you take  a look?

**Comment by ravbhatnagar** [comment]
@kokajambo - This is by design. As mentioned in issue #2093 , Resource type and resource name should not be a valid parameter set for this cmdlet. We will fix that in code and also the documentation would be update. For this scenario, please use Find-AzureRmResource cmdlet

**Comment by kokajambo** [comment]
Thanks for answer @ravbhatnagar!
I have my concerns about using Find-AzureRmResource as a workaround, I'll explain them in #2093 discussion thread

**Comment by ravbhatnagar** [comment]
Fixed. Find-AzureRmResource now contains parameters for doing exact name matches for resource and resource group.
