### ISSUE TITLE
Move-AzureRmResource: Ordering of Parameters incorrect/misleading

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#2309]
Move-AzureRmResource -DestinationResourceGroupName "DestinationRGRP" -DestinationSubscriptionId "123456" **-Force** -ResourceId "abcdef/12345"

The positional parameter "**Force**" is made before "**ResourceId**", Which is not a standard in AzurePowershell commands. 

Also "**ResourceId**" is a mandatory- critical parameter for this command and would like it to take precedence over "-**Force**"

Thanks,
Pradebban Raja

**Comment by markcowl** [comment]
@ravbhatnagar can you take a look?

**Comment by ravbhatnagar** [comment]
@TianoMS - lets fix this.

**Comment by TianoMS** [comment]
@ravbhatnagar This was fixed.

**Comment by ravbhatnagar** [comment]
Fixed
