### ISSUE TITLE
Should it be possible to create new storage containers?

### ISSUE THREAD

**Issue by Petri-X** [Azure/azure-powershell#23092]
### Description

Hi,
I tried to run a command:
New-AzStorageContainer -Name $containerName -Context $ctx -Permission Off -Verbose

I have attached the error logs to their sections, but I found interesting comment from someone:
[stackoverflow - Error 403 on Creating Azure Storage Blob Container](https://stackoverflow.com/questions/62017667/error-403-on-creating-azure-storage-blob-container-storage-firewall-enabled)

When trying to do this on portal directly, this is working as expected.

### Script or Debug output

```PowerShell
DEBUG: 17.15.26 - Init Operation Context for 'NewAzureStorageContainerCommand' with client request id  Azure-Storage-PowerShell-abe3d129-ef9f-45da-972a-92601c537e8d. If you want to get more details, please add "-Debug" to your command.
DEBUG: 17.15.26 - NewAzureStorageContainerCommand begin processing with ParameterSet 'ContainerName'.
DEBUG: 17.15.26 - Use storage account 'teststorageaccount' from storage context.
DEBUG: Request [30672295-5ecb-4220-8b26-cb031befc077] PUT https://teststorageaccount.blob.core.windows.net/myimages?restype=container
x-ms-version:2023-01-03
Accept:application/xml
x-ms-client-request-id:30672295-5ecb-4220-8b26-cb031befc077
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Storage.Blobs/12.17.0 (.NET 7.0.11; Microsoft Windows 10.0.22621)
x-ms-date:Fri, 27 Oct 2023 14:15:26 GMT
Authorization:REDACTED
client assembly: Azure.Storage.Blobs
DEBUG: Error response [30672295-5ecb-4220-8b26-cb031befc077] 403 This request is not authorized to perform this operation. (00.2s)
Server:Microsoft-HTTPAPI/2.0
x-ms-request-id:c2baace6-101e-0002-59e0-08f867000000
x-ms-client-request-id:30672295-5ecb-4220-8b26-cb031befc077
x-ms-error-code:AuthorizationFailure
Date:Fri, 27 Oct 2023 14:15:25 GMT
Cache-Control:proxy-revalidate
Connection:keep-alive
Content-Length:246
Content-Type:application/xml

New-AzStorageContainer: This request is not authorized to perform this operation.
RequestId:c2baace6-101e-0002-59e0-08f867000000
Time:2023-10-27T14:15:26.4074538Z
Status: 403 (This request is not authorized to perform this operation.)
ErrorCode: AuthorizationFailure

Content:
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:c2baace6-101e-0002-59e0-08f867000000
Time:2023-10-27T14:15:26.4074538Z</Message></Error>

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: c2baace6-101e-0002-59e0-08f867000000
x-ms-client-request-id: 30672295-5ecb-4220-8b26-cb031befc077
x-ms-error-code: AuthorizationFailure
Date: Fri, 27 Oct 2023 14:15:25 GMT
Cache-Control: proxy-revalidate
Connection: keep-alive
Content-Length: 246
Content-Type: application/xml
DEBUG: 17.15.26 - NewAzureStorageContainerCommand end processing, Start 0 remote calls. Finish 0 remote calls. Elapsed time 3628242,20 ms. Client operation id: Azure-Storage-PowerShell-abe3d129-ef9f-45da-972a-92601c537e8d.
DEBUG: AzureQoSEvent:  Module: Az.Storage:5.10.1; CommandName: New-AzStorageContainer; PSVersion: 7.3.8; IsSuccess: False; Duration: 00:00:00.2630087; Exception: This request is not authorized to perform this operation.
RequestId:c2baace6-101e-0002-59e0-08f867000000
Time:2023-10-27T14:15:26.4074538Z
Status: 403 (This request is not authorized to perform this operation.)
ErrorCode: AuthorizationFailure

Content:
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:c2baace6-101e-0002-59e0-08f867000000
Time:2023-10-27T14:15:26.4074538Z</Message></Error>

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: c2baace6-101e-0002-59e0-08f867000000
x-ms-client-request-id: 30672295-5ecb-4220-8b26-cb031befc077
x-ms-error-code: AuthorizationFailure
Date: Fri, 27 Oct 2023 14:15:25 GMT
Cache-Control: proxy-revalidate
Connection: keep-alive
Content-Length: 246
Content-Type: application/xml
;
DEBUG: 17.15.26 - NewAzureStorageContainerCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.13.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     5.10.1                Az.Storage
```

### Error output

```PowerShell
Message        : This request is not authorized to perform this operation.
                 RequestId:91ad2208-101e-0012-27de-083d0f000000
                 Time:2023-10-27T14:07:19.6932273Z
                 Status: 403 (This request is not authorized to perform this operation.)
                 ErrorCode: AuthorizationFailure

                 Content:
                 ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
                 RequestId:91ad2208-101e-0012-27de-083d0f000000
                 Time:2023-10-27T14:07:19.6932273Z</Message></Error>

                 Headers:
                 Server: Microsoft-HTTPAPI/2.0
                 x-ms-request-id: 91ad2208-101e-0012-27de-083d0f000000
                 x-ms-client-request-id: 6894527c-def5-410b-8e92-68fb84485640
                 x-ms-error-code: AuthorizationFailure
                 Date: Fri, 27 Oct 2023 14:07:19 GMT
                 Cache-Control: proxy-revalidate
                 Connection: keep-alive
                 Content-Length: 246
                 Content-Type: application/xml

StackTrace     :    at Azure.Storage.Blobs.ContainerRestClient.CreateAsync(Nullable`1 timeout, IDictionary`2 metadata, Nullable`1 access, String defaultEncryptionSc
                 ope, Nullable`1 preventEncryptionScopeOverride, CancellationToken cancellationToken)
                    at Azure.Storage.Blobs.BlobContainerClient.CreateInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScop
                 eOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken, String operationName)
                    at Azure.Storage.Blobs.BlobContainerClient.CreateIfNotExistsInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEnc
                 ryptionScopeOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken)
                    at Azure.Storage.Blobs.BlobContainerClient.CreateIfNotExistsAsync(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryp
                 tionScopeOptions encryptionScopeOptions, CancellationToken cancellationToken)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.NewAzureStorageContainerCommand.CreateAzureContainer(Int64 taskId, IStorageBlobManagement
                  localChannel, String name, BlobContainerPublicAccessType accesslevel)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.RunConcurrentTask(Int64 taskId, Task task)
Exception      : Azure.RequestFailedException
InvocationInfo : {New-AzStorageContainer}
Line           :  New-AzStorageContainer -Name $containerName -Context $ctx -Permission Off -Verbose
Position       : At line:1 char:2
                 +  New-AzStorageContainer -Name $containerName -Context $ctx -Permissio …
                 +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 44
```

**Comment by blueww** [comment]
@Petri-X 

It looks the error is caused by your storage account has account properties "publicNetworkAccess" as "Disabled". 
This means for dataplane rest API, the storage account won't accept dataplane request from public network. (can accept request from specific private link, vnet configured for the storage account)

For Portal, I suspect the create container request goes from management plane instead of dataplane, so it work.
For Powershell, `New-AzStorageContainer` will create storage account from dataplane API. You can run following script to create container from management plane:
```powershell
# Login Azure account, one time work
Connect-AzAccount
####

New-AzRmStorageContainer -ResourceGroupName $resouceGroupName -StorageAccountName $accountName -Name $containerName -PublicAccess None
```

**Comment by Petri-X** [comment]
Hi @blueww 
Big thanks for your reply. May I ask some clarity for that..

Yes, my storage account is having "**PublicNetworkAccess : Disabled**", but then you continue:
_. . .can accept request from specific private link, vnet configured for the storage account. . ._
I tried to read the documentation from here: [Learn: New-AzStorageAccount](https://learn.microsoft.com/en-us/powershell/module/az.storage/new-azstorageaccount) but did not found any idea how that should be possible. Nothing to do with NSG?

I tried to find the definitions between "Azure storage container" vs. "Storage blob container", but they seems to be equals. So I was wondering if there are some preferables which one to use. The next CMDLet on the pipeline how the 3rd party is planning to do copy is to use "Start-AzStorageBlobCopy" for copying the disk image from their site into container.

BTW, Could it be so that when my storage account have public network access disabled, the Storage Blog copy (**Start-AzStorageBlobCopy**) would not work either if the source is outside?

**Comment by blueww** [comment]
@Petri-X 

1. For how to configure private link or vnet on storage account, this is out of Powershell scope, we might not be the best person to answer it. You might can refer: https://learn.microsoft.com/en-us/azure/storage/blobs/security-recommendations#networking
If you still have questions, you can [raise a support ticket in Azure Portal](https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header), and the related team will come to help you.

2. the Storage Blog copy (Start-AzStorageBlobCopy) can only go from dataplane, so if your source/dest storage account has public network access disabled, the client machine send the request need be in the allowed private link, vnet, ip address of the source/dest account.

4. "Azure storage container" vs. "Storage blob container": not sure where you get them, but they should be same. They should both mean Azure Storage blob container, in short we just call it container.

**Comment by Petri-X** [comment]
@blueww 
No worries, I really did not tried to ask about the private links :) But was more likely wondering how to say to Storage Accounts if the is the private links available for it. But I'll try to find the way, but I believe your Answer 2 actually gave me answer I was worried =)

About the differences, originally I was using the command [**New-AzStorageContainer**], but then you switched to [New-Az**Rm**StorageContainer]. When reading the documents between them:
[New-AZStorageContainer](https://learn.microsoft.com/en-us/powershell/module/az.storage/new-azstoragecontainer?view=azps-10.4.1) says:
_Creates an Azure storage container._
while then [New-AzRmStorageContainer](https://learn.microsoft.com/en-us/powershell/module/az.storage/new-azrmstoragecontainer?view=azps-10.4.1) says:
_Creates a Storage blob container_

But if you say those are still the same, then I perhaps would use AzRMStorageContainer for future needs.

**Comment by blueww** [comment]
@Petri-X 

Thanks for the responds!

It looks there are no PowerShell question here. 
Do you mind I close this issue?

**Comment by Petri-X** [comment]
Yes, I believe this was enough :)

Big thanks for your support and effort!
