### ISSUE TITLE
[Doc]: https://learn.microsoft.com/en-us/powershell/module/az.compute/update-azvmssinstance?view=azps-10.3.0

### ISSUE THREAD

**Issue by microsoftuser64** [Azure/azure-powershell#23105]
### Description

By having 'AsJob' as part of the command to run the Update-AzVmssInstance command loop, there are errors seen due to the fact that the jobs are being executed asynchronously as background jobs. Therefore, it reaches the number of concurrent requests and throws a 'Conflict with Concurrent Request' error message, and some instances fail to be updated and/or show up as 'unhealthy'. However, when AsJob is deleted from the command, the update works fine, and all instances are updated accordingly. Based on this explanation, the request is as follows: could we possible remove this AsJob command from the documentation to avoid any more future issues or confusions with running a VM instance update? 

Please let me know if you require any further information regarding this request. The link to the documentation: https://learn.microsoft.com/en-us/powershell/module/az.compute/update-azvmssinstance?view=azps-10.3.0

**Comment by isra-fel** [comment]
Thanks for the feedback. Let me route this to Azure Compute team.
BTW could you share a sample script to demonstrate how you'd update the VMSS instances?

**Comment by haagha** [comment]
@microsoftuser64  Can you capture debug logs using -Debug flag and share them here.

**Comment by hilaryw29** [comment]
@microsoftuser64 following up on this, could you please share debug logs?

**Comment by hilaryw29** [comment]
@microsoftuser64 closing this thread due to inactivity. Please feel free to re-open if there are additional questions or with the debug logs and we'll be happy to take a look. Thanks!
