### ISSUE TITLE
[Doc]: CreateOption argument does not indicate supported values

### ISSUE THREAD

**Issue by richardhauer** [Azure/azure-powershell#23125]
### Type of issue

Missing information

### Feedback

The 'New-AzSnapshotConfig' is used to prepare a snapshot.
The `CreateOption` parameter has a type of `String` but the list of acceptable values is not provided. There needs to be official documentation for this. It's not appropriate that we need to glean this information by hunting through scores of blog posts.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.compute/new-azsnapshotconfig?view=azps-10.4.1

**Comment by isra-fel** [comment]
Thanks for the feedback. I've looped in Azure COmpute team.

**Comment by GabstaMSFT** [comment]
@ushnaarshadkhan could you look into this?

**Comment by AdamZLi** [comment]
Thanks for the feedback, we have added this request into our documentation backlog. Will update in this thread once the changes are made.
