### ISSUE TITLE
Start-AzureRmAutomationRunbook Memory Leak

### ISSUE THREAD

**Issue by Nightsmark** [Azure/azure-powershell#2312]
Disclaimer: This maybe be a Powershell ISE memory leak, but I'm starting here first. 

I'm running Start-AzureRmAutomationRunbook with the parameters:
-AutomationAccountName
-Name
-Parameters
-ResourceGroupName
-Verbose

Memory use is increasing on average about 30-40 MB per second and the command never finishes running if you let it sit. Below is a snippet just taken from task manager that shows the memory usage.

![image](https://cloud.githubusercontent.com/assets/10898395/15504228/31223e9e-217b-11e6-890a-ed161b39d10c.png)

I tried this command in both
VirtualBox Windows 7 Enterprise 64 bit
![image](https://cloud.githubusercontent.com/assets/10898395/15504402/fe14f9fa-217b-11e6-9aaa-b07aa6ad09f3.png)

![image](https://cloud.githubusercontent.com/assets/10898395/15504377/e2745452-217b-11e6-869f-65ee333d3eb6.png)

and then not in VirtualBox with Windows 7 Professional 64 bit.

![image](https://cloud.githubusercontent.com/assets/10898395/15504481/7b3818cc-217c-11e6-8261-7f923fce9f67.png)

![image](https://cloud.githubusercontent.com/assets/10898395/15504570/d80f77d4-217c-11e6-9af4-5c32ff262ffd.png)

**Comment by markcowl** [comment]
@Nightsmark off the top of my head, this is likely traffic that is being written to the debug stream.  As an experiment, can you try runnign with ```$DebugPreference="Continue"```` and see if the same behavior occurs.

**Comment by Nightsmark** [comment]
It doesn't look like that is the issue. I let it run for 5-6 minutes and it used ~2 GB of memory but it didn't output any more debug information than this.

![runbookdebuganonymized](https://cloud.githubusercontent.com/assets/10898395/15541244/d1a64374-2248-11e6-8374-51946f1e8595.png)

**Comment by markcowl** [comment]
@jodoglevy can you take  a look?

**Comment by jodoglevy** [comment]
I was not able to repro this:

```
PS C:\WINDOWS\system32> get-module -name AzureRM.Automation

ModuleType Version    Name                                ExportedCommands                                                                                
---------- -------    ----                                ----------------                                                                                
Manifest   1.0.8      AzureRM.Automation                  {Export-AzureRmAutomationDscConfiguration, Export-AzureRmAutomationDscNodeReportContent, Expo...


PS C:\WINDOWS\system32> Login-AzureRmAccount


PS C:\WINDOWS\system32> Start-AzureRmAutomationRunbook -ResourceGroupName "anotherservice" -AutomationAccountName "JoeTest1234" -Name "test" -Parameters @{} -Verbose


ResourceGroupName      : anotherservice
AutomationAccountName  : JoeTest1234
JobId                  : 84389c1d-408e-4afd-99ad-35c555abd5ef
CreationTime           : 5/26/2016 12:38:52 PM -07:00
Status                 : New
StatusDetails          : None
StartTime              : 
EndTime                : 
Exception              : 
LastModifiedTime       : 5/26/2016 12:38:52 PM -07:00
LastStatusModifiedTime : 5/26/2016 12:38:52 PM -07:00
JobParameters          : {}
RunbookName            : test
HybridWorker           : 
StartedBy              : <redacted>
```

Memory use only increased a few MB, and went back down after command ended.

Can you try updating to the latest version of the AzureRM cmdlets? Also, do other AzureRM cmdlets (or other cmdlets in general) cause memory issues for you?

**Comment by Nightsmark** [comment]
@jodoglevy Hey, sorry for the late response on this, but I finally got back to working on this today and managed to narrow it down. Also, I'm currently on Azure PowerShell 1.6 and last time I tried it I was on 1.4.

This is my runbook:

![github1](https://cloud.githubusercontent.com/assets/10898395/18254637/f0a4e0c2-735c-11e6-884d-307f7cd77f21.PNG)

And here is what I'm passing in as the $FileContent parameter which you can see is JSON. I'm guessing the JSON is the issue since if I pass in anything that isn't JSON it works just fine.

![github2](https://cloud.githubusercontent.com/assets/10898395/18254643/f46a5f2a-735c-11e6-9933-57150f5145b2.PNG)

**Comment by cormacpayne** [comment]
Closing this issue since it appears to be resolved.

@Nightsmark please feel free to reopen this issue if you have any other questions.
