### ISSUE TITLE
[Doc]: New-AzVmss examples for Trusted Launch appears to contradict imageName

### ISSUE THREAD

**Issue by kobulloc-MSFT-Standard** [Azure/azure-powershell#23124]
### Type of issue

Code doesn't work

### Feedback

First, we give an example for setting up Trusted Launch that uses an `imageName` of `“Win2016DataCenterGenSecond”` (Example 5):

![image](https://github.com/Azure/azure-powershell/assets/149538459/56623b38-60ba-4f81-9ab5-30a8429f84bb)

Later, we describe `-ImageName` as only accepting a limited set of aliases that do not include `“Win2016DataCenterGenSecond”`:

![image](https://github.com/Azure/azure-powershell/assets/149538459/763e70cb-b4cc-4add-af79-11c6470db869)

And this list appears to contract verification of supported Trusted Launch operating systems:

![image](https://github.com/Azure/azure-powershell/assets/149538459/60bf42b8-2835-48d4-8b1e-c0cdd5d90f23)

What should an individual do if they want to deploy Windows Server 2019 with Trusted Launch enabled?

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.compute/new-azvmss?view=azps-10.4.1#-imagename

**Comment by isra-fel** [comment]
Hi @kobulloc-MSFT-Standard thanks for the feedback! I've looped in Azure compute team.

BTW if you are an MSFT employee please use this link to join the microsoft Github organization: https://repos.opensource.microsoft.com/ It helps our statistics. Thanks.

**Comment by Sandido** [comment]
@kobulloc-MSFT-Standard , thanks for the callout! While the code works, the documentation is misleading and unexpected. I will update it and release it for the next PS release (12/5).

**Comment by hilaryw29** [comment]
Thanks @Sandido! 

@kobulloc-MSFT-Standard Re: "What should an individual do if they want to deploy Windows Server 2019 with Trusted Launch enabled?"

- If you're using a gen2 image (hypervgeneration v2), Trusted Launch should be supported per https://learn.microsoft.com/en-us/azure/virtual-machines/generation-2#generation-2-vm-images-in-azure-marketplace. 
- The recommendation here is to use "Win2019DatacenterGen2" if possible as that is a specific 2019 gen2 image. 

Thanks for raising this and please let us know if you have any additional questions!

**Comment by Sandido** [comment]
The PR with edits to this example has been merged and will release to customers on 12/5.
