### ISSUE TITLE
[Doc]: Example 1, is the name just enough?

### ISSUE THREAD

**Issue by Petri-X** [Azure/azure-powershell#23140]
### Type of issue

Code doesn't work

### Feedback

Hi,
On here: [Get-AzStorageContainer / Example 1](https://learn.microsoft.com/en-us/powershell/module/az.storage/get-azstoragecontainer?view=azps-10.4.1#example-1-get-azure-storage-container-by-name) you have only a parameter "-name" used. But when I'm running the same, I'm getting:
```
PS C:\> Get-AzStorageContainer -Name p*
Get-AzStorageContainer: Could not get the storage context.  Please pass in a storage context or set the current storage context.
```

There are some others having similar issues:
[Azure Lessons / Get-AzStorageContainer](https://azurelessons.com/get-azstoragecontainer/)

Is this problem on PS module or in the example?

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.storage/get-azstoragecontainer?view=azps-10.4.1#example-1-get-azure-storage-container-by-name

**Comment by isra-fel** [comment]
Thanks for the feedback! Let me loop in the Azure Storage team. cc @blueww

**Comment by yifanz7** [comment]
@Petri-X  Just as the error message mentioned, you'll need to pass in a context in order for the cmdlet to work. 
The context can be set by
1. Create a storage context object with "New-AzStorageContext" and run "get-azstorageshare" with parameter "-Context" whose value is the created context object https://learn.microsoft.com/en-us/powershell/module/az.storage/new-azstoragecontext?view=azps-10.4.1&viewFallbackFrom=azps-9.1.0#examples
2. Run Set-AzCurrentStorageAccount to set a default storage context, then run "get-azstorageshare" without parameter "-Context" will use the default storage context.

For reasons of why the parameter `Context` is not in the docs can be found here: https://github.com/Azure/azure-powershell/issues/20208

We have also included some proposals of improving the docs in the issue above. I'll paste the proposals here - please let us know your thoughts 

> How about we change the error message when the cmdlet misses "-Context" to make it more actionable, so user don't need web search how to use it:
> 
> Current error message:
> "Could not get the storage context. Please pass in a storage context or set the current storage context."
> Changed Error message:
> "Could not get the storage context. Please pass in a storage context with "-Context" parameter (can be created with New-AzStorageContext cmdlet), or set the current storage context with Set-AzCurrentStorageAccount cmdlet."
> For the change in the summary page, I will need to check with Powershell team to see if that's applicable.
> However, although there are many cmdlets in Az.Storage need "-Context", there are also a lot of other cmdlets in Az.Storage doesn't need "-Context". So we need think how to not mislead customer that all Az.Strorage need Storage Context.
>

**Comment by Petri-X** [comment]
That is of course improvement, but actually the question is, why the [-context is not market](https://learn.microsoft.com/en-us/powershell/module/az.storage/get-azstoragecontainer?view=azps-10.4.1#-context) as a mandatory parameter, as it seems to be on case in this CMDLet?

Of course, if that is mandatory, then the error message cannot be offered.


But isn't the most simplest solution just too add the context guide to the CMDLets where it is required, and then add -context as mandatory?

**Comment by yifanz7** [comment]
@Petri-X
Currently `-Context` is not marked as a mandatory parameter as it's not necessarily mandatory in the cmdlets.  
There are several ways to set Storage context. When the user sets it Set-AzCurrentStorageAccount cmdlet, there will be a default Storage context in the PSH console, so the user doesn't need to input `-Context` explicitly. Thus, the parameter is not always required. 
If the user doesn't input context explicitly and there's no default context in the console, the error message will be sent.

**Comment by Petri-X** [comment]
@yifanz7 aah ! Thanks, I forgot that there could be a context defined as before hand!
Then the updated error message looks good for me at least :D

**Comment by yifanz7** [comment]
Closing the issue as the change has been merged
