### ISSUE TITLE
OATH-TOTP SHA-1 tokens

### ISSUE THREAD

**Issue by raindropami** [Azure/azure-powershell#23151]
### Description

Do we have any guidance we can share on when we are planning to release API support to work with Hardware OAUTH tokens? - https://learn.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0  Thanks

**Comment by isra-fel** [comment]
Hello. The supportability of Microsoft Graph API is out of scope of Azure PowerShell. I recommend submitting issue to https://github.com/microsoftgraph/msgraph-sdk-powershell
