### ISSUE TITLE
Please specify were to download this command. 

### ISSUE THREAD

**Issue by ynilajkar** [Azure/azure-powershell#23234]
### Type of issue

Typo

### Feedback

Please specify were to download this command. This is getting into a mess where know one knowns from which package these command belongs to or are they removed 

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.resources/get-azresource?view=azps-10.4.1

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/help/Get-AzResource.md

### Author

mikefrobbins

### Document Id

0bad2468-1e38-79c3-5245-723c0db8cd63

**Comment by isra-fel** [comment]
![image](https://github.com/Azure/azure-powershell/assets/11371776/fe542b45-97e1-4d85-b7cc-351ea3bcab3d)

Hey @ynilajkar if you look at the top of the page it tells what module the command belongs to. In this case, it's `Az.Resources`.
You can easily run `Install-Module Az.Resources` to install the single module, or `Install-Module Az` to install all Azure PowerShell modules.
