### ISSUE TITLE
Update-AzApplicationInsights to Migrate to Workspace throws error from PS1 script

### ISSUE THREAD

**Issue by asbhalekar** [Azure/azure-powershell#23258]
### Description

When we execute the **Update-AzApplicationInsights to Migrate to Workspace from POWERSHELL command line it WORKS CORRECTLY** and migrates to Workspace based, but if **same command is executed from inside the PS1 script it gives below ERROR**

**_"The term 'New-Guid' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."_**

The command used is as below which works from Powershell commandline but gives above error from when executed in the script ps1 file
**Update-AzApplicationInsights -Name appinsights-test1 -ResourceGroupName test1-sandbox -IngestionMode LogAnalytics -WorkspaceResourceId /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/test1-sandbox/providers/Microsoft.OperationalInsights/workspaces/oms-test1**

Powershell version -  10.4.1
Az.Accounts version - 2.12.1
Az.Resources version - 6.6.0

Az.Accounts version 2.13.1 was giving error "Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.PowerShell.Clients.ResourceManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation." so had to revert to previous version 2.12.1

Az.Resources version 6.11.1 was giving error "The 'Get-AzResourceGroup' command was found in the module 'Az.Resources', but the module could not be loaded. For more information, run 'Import-Module Az.Resources'." so had to revert to previous version  6.6.0

### Issue script & Debug output

```PowerShell
Update-AzApplicationInsights -Name appinsights-test1 -ResourceGroupName test1-sandbox -IngestionMode LogAnalytics -WorkspaceResourceId /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/test1-sandbox/providers/Microsoft.OperationalInsights/workspaces/oms-test1

An error occurred when executing task 'Test1-Infrastructure'.
Error: One or more errors occurred.
        The term 'New-Guid' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     2.2.2                 Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKey, Get-AzApplicationInsightsContinuousExport, Get-AzApplicationInsightsLinkedStora…
```

### Error output

```PowerShell
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.
```

**Comment by isra-fel** [comment]
Hi @asbhalekar the problem that `New-Guid` could not be found seems more fundamental than the scope of this repo. I recommend submitting an issue to https://github.com/PowerShell/PowerShell

**Comment by asbhalekar** [comment]
Closing the issue, this issue seems to be of another tool Cake build which internally calls powershell scripts
