### ISSUE TITLE
Get-AzureRmStorageAccount const much longer time when update into lateast version

### ISSUE THREAD

**Issue by LiliDeng** [Azure/azure-powershell#2326]
We run Get-AzureStorageAccount against azure PS using version 0.9.8 cost 1 second.
Run Get-AzureRmStorageAccount against azure PS using version 1.4.0 cost 1.5 mins. Also it brings in some exception if we delete storage account during the 1.5 mins.

**Comment by markcowl** [comment]
@LiliDeng This was just fixed in the dev branch (see #2272) and the fix will be out in next releas (6/1)
