### ISSUE TITLE
Is this project available on NuGet?

### ISSUE THREAD

**Issue by xt0rted** [Azure/azure-powershell#2330]
I'm running powershell scripts inside my c# code using [Microsoft.PowerShell.5.ReferenceAssemblies](https://www.nuget.org/packages/Microsoft.PowerShell.5.ReferenceAssemblies/) and one of the responses I get back is for [PSResourceGroupDeployment.cs](https://github.com/Azure/azure-powershell/blob/83203f0c2ab4988661f570991b4b26a6c8ee8338/src/ResourceManager/Resources/Commands.Resources/Models.ResourceGroups/PSResourceGroupDeployment.cs). Is `Microsoft.Azure.Commands.Resources` available on NuGet at all? I can copy the needed files into my project but I'd prefer to use NuGet if possible.

**Comment by markcowl** [comment]
Modules are available from the PowerShell Gallery: https://www.powershellgallery.com/ which is sessentially NuGet (OneGet) for PowerShell
