### ISSUE TITLE
Add-AzureRMAccount gives Password error which is not good in a security context

### ISSUE THREAD

**Issue by energizedtech** [Azure/azure-powershell#2331]
If you Use Add-AzureRMAccount and supply an old password it will actually produce an error which says so.   It would be better to simply show "Access Denied". 
If the credentials were compromised it validates to an attacker they have found an old but valid set of keys from those credentials.    
Such information would allow an attacker to attempt additional attacks on other targets in an organization as Azure VALIDATED they WERE good.  (Well these keys might not open the house, but I'll try the shed... or the SQL Server, Web site etc etc etc...)

**Comment by markcowl** [comment]
@energizedtech this is actually an issue in the underlying library, can ypu please file this issue here:  https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues

**Comment by markcowl** [comment]
@energizedtech It looks like you didn't open an issue agianst the ADAL library.  Closing this for now, please open the issue there, as that is the source of the error message.
