### ISSUE TITLE
[Feature]:  Update existing APIs and add new APIs for Microsoft.Datadog RP

### ISSUE THREAD

**Issue by vikotha** [Azure/azure-powershell#23362]
### Description of the new feature

Update the existing TagRules API with new parameters (automuting and cspm)
Add support for new child RT (monitoredSubscriptions)

Public Swagger: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/datadog/resource-manager/Microsoft.Datadog/stable/2023-01-01

PR link for 2023-01-01 version: https://github.com/Azure/azure-rest-api-specs/pull/24495

**Comment by isra-fel** [comment]
@Alex-wdy could you track this feature request internally?

**Comment by Alex-wdy** [comment]
We had preliminary communication with the service developer. Because we found that this part was the command line generated by autorest, we recommended service for upgrade and AzPS team for technical support. Service has accepted it.
