### ISSUE TITLE
Bug: Can't create SQL Server with a tag

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2340]
![image](https://cloud.githubusercontent.com/assets/466713/15583894/05e38830-2335-11e6-981a-72593bf755a3.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by jamestao** [comment]
Fixed Tags overall in #3206.
