### ISSUE TITLE
Example 2 is incorrect

### ISSUE THREAD

**Issue by jku-sr** [Azure/azure-powershell#23400]
### Type of issue

Other (describe below)

### Feedback

Example 2 is incorrect, it's using the wrong cmdlet

`$CertBase64 = Get-AzKeyVaultSecret -VaultName $vaultName -Name $certName -AsPlainText
$CertBytes = [Convert]::FromBase64String($CertBase64)
Set-Content -Path cert.pfx -Value $CertBytes -AsByteStream`

I believe it should be using Get-AzKeyVaultCertificate as the article is about retrieving certificates

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.keyvault/get-azkeyvaultcertificate?view=azps-10.4.1

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/KeyVault/KeyVault/help/Get-AzKeyVaultCertificate.md

### Author

mikefrobbins

### Document Id

63263710-e864-310a-6a42-c618857872b0

**Comment by jku-sr** [comment]
actually. i understand now. get-azkeyvaultcertificate retrieves the public key without private key. the get-azkeyvaultsecret example is used to retrieve the private keywith it

comment closed.

**Comment by Speedmaister** [comment]
I think there is a problem although different than what the original issue states. Example 2 in Get-AzKeyVaultCertificate docs states that the certificate should be downloaded with Get-AzKeyVaultSecret **as plain text** and then tries to **convert** the value **from base64 string**. An error is thrown during the conversion attempt.

Error:
MethodInvocationException: Exception calling "FromBase64String" with "1" argument(s): "The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters."
