### ISSUE TITLE
New-AzDeployment with bicepparam fails validation incorrectly

### ISSUE THREAD

**Issue by jetuser** [Azure/azure-powershell#23413]
### Description

When I trigger a deployment via New-AzDeployment and specify -TemplateParameterFile pointing to a bicepparam file, it fails validation seemingly because it is treating the compiled parameter file's value as an object as opposed to a valid ARM parameter specification.

I manually compiled the bicep file and parameter file into their respective jsons and i was able to upload the deployment via the portal and have it run correctly.

From what I can tell, its treating the value as an object as opposed to looking at "value" within the parameters json. I'm using the latest version of bicep and powershell core. I am internal to microsoft and I can provide the verbose output and the compiled jsons on the side if necessary.

### Issue script & Debug output

```PowerShell
New-AzDeployment : 9:50:04 AM - Error: Code=InvalidTemplate; Message=Deployment template validation failed: 'The
provided value for the template parameter 'environment' is not valid. The value '{
  "value": "<redacted>"
}' is not part of the allowed value(s): '<redacted>,<redacted>,<redacted>,<redacted>,<redacted>'.'.
At line:1 char:1
+ New-AzDeployment -Location "East US" -TemplateParameterFile .\bicep\r ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureSubscriptionDepl
   oymentCmdlet
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.13.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
Script     6.11.1                Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, G…
```

**Comment by jetuser** [comment]
Adding some additional information. I looked at the verbose output and there is an issue with how the parameters are being formed, example snip from the output below:

```
   "parameters": {
      "tenantId": {
        "value": {
          "value": "975f013f-7f24-47e8-a7d3-abc4752bf346"
        }
      },...

**Comment by isra-fel** [comment]
@BethanyZhou please triage this. Thanks.

**Comment by BethanyZhou** [comment]
@anthony-c-martin please have a look. There are more information posted by @jetuser [here](https://stackoverflow.microsoft.com/questions/378127).

**Comment by anthony-c-martin** [comment]
@jetuser could you try this again after upgrading Az.Resources to version 6.11.2?

**Comment by jetuser** [comment]
@anthony-c-martin i updated to 6.12 and it appears the issue no longer reproduces, thanks!

**Comment by BethanyZhou** [comment]
thanks @anthony-c-martin & @jetuser . Will mark this issue as resolved.
