### ISSUE TITLE
Connect-AzAccount does not work from a WSL2 session with mirrored networking mode

### ISSUE THREAD

**Issue by jurjenoskam** [Azure/azure-powershell#23441]
### Description

I have recently updated to the latest released version of WSL2, which includes the "mirrored" networking mode. After doing so, Connect-AzAccount -UseDeviceAuthentication no longer works. After authentication I'm told that: "Your sign-in was successful but your admin requires the device requesting access to be managed by _company tenant name here_ to access this resource." This was not unexpected as the Azure CLI equivalent `az login --use-device-code` showed the same behavior.

Wat was unexpected is that using plain "Connect-AzAccount" doesn't work as well, it informs me that interactive authentication is not supported and that I should use the "-UseDeviceAuthentication" parameter. This is also different from Azure CLI, as the equivalent `az login` _was_ able to open my browser (on the Windows side) and successfully log in.

This means I now have no way to login to Az PowerShell. This happened with Az 10.3.0 as well as 11.0.0.

### Issue script & Debug output

```PowerShell
PS /home/joskam> $DebugPreference = 'Continue'
PS /home/joskam> Connect-AzAccount
DEBUG: Initializing ConditionalAssemblyContext. PSEdition is [Core]. PSVersion is [7.3.9].
DEBUG: Initializing ConditionalAssemblyProvider. AssemblyRootPath is [/home/joskam/.local/share/powershell/Modules/Az.Accounts/2.13.2/StartupScripts/../lib].
DEBUG: Registering Az shared AssemblyLoadContext.
DEBUG: AssemblyLoadContext registered.
DEBUG: Got version 0 of Az
DEBUG: Got version 0 of Az.Accounts
DEBUG: 09:26:36 - ConnectAzureRmAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.
DEBUG: 09:26:36 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 09:26:36 - [ConfigManager] Got nothing from [DefaultSubscriptionForLogin], Module = [], Cmdlet = []. Returning default value [].
WARNING: Interactive authentication is not supported in this session, please run cmdlet 'Connect-AzAccount -UseDeviceAuthentication'.
DEBUG: 09:26:36 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 09:26:36 - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.13.2; CommandName: Connect-AzAccount; PSVersion: 7.3.9; IsSuccess: True; Duration: 00:00:00.0242206
DEBUG: 09:26:36 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 09:26:36 - ConnectAzureRmAccountCommand end processing.
```

### Environment data

```PowerShell
PS /home/joskam> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Linux 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\jurje> wsl --version
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.2506

PS C:\Users\jurje> type .\.wslconfig
[experimental]
autoMemoryReclaim=gradual
sparseVhd=true
networkingMode=mirrored
```

### Module versions

```PowerShell
PS /home/joskam> Connect-AzAccount
WARNING: Interactive authentication is not supported in this session, please run cmdlet 'Connect-AzAccount -UseDeviceAuthentication'.
PS /home/joskam> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.13.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}

PS /home/joskam>
```

### Error output

```PowerShell
PS /home/joskam> Resolve-AzError


PS /home/joskam>
```

**Comment by isra-fel** [comment]
Thanks for the feedback!
@msJinLei could you look into it? Will this be fixed by the MSAL update?

**Comment by jurjenoskam** [comment]
Seems there are similar issues with WSL and Azure CLI:
- https://github.com/microsoft/WSL/issues/8892
- https://github.com/Azure/azure-cli/issues/27879

A useful workaround for me was to install wslu (https://wslutiliti.es/wslu/install.html), which contains the `wslview` utility. After installing wslu, `Connect-AzAccount` (without any parameters) successfully opened a browser tab on the Windows side and authentication completed successfully.

**Comment by isra-fel** [comment]
Thanks. Let's track the issue using the one created in the WSL repo.

**Comment by dansailer** [comment]
Late to the party, but in my case I didn't have the [DISPLAY variable](https://github.com/Azure/azure-powershell/blob/04a37e37d0476593ce250f5ed8c169a1ad27c405/src/Accounts/Authentication/Utilities/CommonUtilities.cs#L34C82-L34C89) set. (automatically set if you have `guiApplications=true` for [WSLg](https://github.com/microsoft/wslg?tab=readme-ov-file#wslg-system-distro))

```
export DISPLAY=:0

sudo update-alternatives --install /usr/bin/edge edge /mnt/c/Program\ Files\ \(x86\)/Microsoft/Edge/Application/msedge.exe 1
export BROWSER=edge
```
