### ISSUE TITLE
Add test coverage for Linux VM disk encryption in Compute Extensions

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-powershell#2345]
Discovered test coverage issue in PR #2313. This should be fixed by next release.

**Comment by singhkays** [comment]
@krkhan Was this fixed?

**Comment by krkhan** [comment]
@singhkays It's blocked on lack of a KeyVaultClient in test framework (which in turn is blocked on AD integration). Added you to internal thread.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
