### ISSUE TITLE
[Doc]: new-azurecontainerapp argument list doesn't match

### ISSUE THREAD

**Issue by twerthi** [Azure/azure-powershell#23478]
### Type of issue

Missing information

### Feedback

The documentation located at https://learn.microsoft.com/en-us/powershell/module/az.app/new-azcontainerapp lists several arguments which are apparently no longer present in the cmdlet such as `-IngressExternal`.  Please update your documentation so I can figure out how to replace this functionality as there doesn't appear to be an equivalent argument available.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.app/new-azcontainerapp

**Comment by isra-fel** [comment]
Thanks for the feedback. @lijinpei2008 please fix the outdated example. Thanks.

**Comment by lijinpei2008** [comment]
Documentation has been updated, and hopefully the updated documentation will help you.
