### ISSUE TITLE
Japanese translation typo

### ISSUE THREAD

**Issue by yokoyama-tetsuya** [Azure/azure-powershell#23481]
### Type of issue

Typo

### Feedback

"Azure Files Microsoft Entra Doメイン Services 認証"
Doメイン should be Domain

### Page URL

https://learn.microsoft.com/ja-jp/powershell/module/az.storage/new-azstorageaccount?view=azps-11.0.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/Storage/Storage.Management/help/New-AzStorageAccount.md

### Author

mikefrobbins

### Document Id

75c4407a-fce4-1282-029d-874289394f54

**Comment by isra-fel** [comment]
Thanks for the feedback!
@mikefrobbins could you help route the issue to the correct team? THanks.
