### ISSUE TITLE
Get-AzureRmResource returns strange error

### ISSUE THREAD

**Issue by tohling** [Azure/azure-powershell#2349]
I have a script that uses service principal to execute Azure PowerShell cmdlets.  Most of the other cmdlets are working except for **Get-AzureRmResource**.  Here's a sample snippet of my script code:

$secpasswd = ConvertTo-SecureString "somePassword" -AsPlainText -Force;
$mycreds = New-Object System.Management.Automation.PSCredential ("someUsername", $secpasswd)
Add-AzureRmAccount -ServicePrincipal -Tenant "someTenantId" -Credential $mycreds;
$context = Get-AzureRmContext;
Set-AzureRmContext -Context $context;
#Get-AzureRmWebApp -ResourceGroupName "Default-Web-WestUs" -Name "mysite"; **#works**
#Get-AzureRmAppServicePlan -ResourceGroupName "Default-Web-WestUS"; **#works**
**Get-AzureRmResource  -ResourceGroupName "Default-Web-WestUs" -ResourceType "Microsoft.Web/sites" -ResourceName "somename" #does not work**

When I execute the script, I am seeing the following error.  Seems like it is referencing an older version of the cmdlet.  Any ideas why this is happening?

Get-AzureRmResource : Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials.

+ Get-AzureRmResource -ResourceGroupName "Default-Web-WestUs" -ResourceType 
"Micro ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResource], ArgumentE 
   xception
    + FullyQualifiedErrorId : Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials.  ,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet

**Comment by hovsepm** [comment]
@tohling Please make sure you do not have powershell gallery modules installed along with general MSI

**Comment by hovsepm** [comment]
@tohling Closing this issue since there is no feedback after my suggestion. Please reopen this issue with more details if you still have the same experience.

**Comment by tohling** [comment]
How do I find out if I have PowerShell gallery modules installed?  I ran the following commands but they are not recognized.

PS D:\Users\webworkeradmin> Get-InstalledModule
Get-InstalledModule : The term 'Get-InstalledModule' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ Get-InstalledModule
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-InstalledModule:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS D:\Users\webworkeradmin> Find-Module
Find-Module : The term 'Find-Module' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Find-Module
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Find-Module:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS D:\Users\webworkeradmin> Find-DcsResource
Find-DcsResource : The term 'Find-DcsResource' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Find-DcsResource
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Find-DcsResource:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by wangzq** [comment]
@tohling you can also try to run `Get-Module -ListAvailable` or check `$env:PSModulePath -split ';'`, if following 3 folders are listed then you should be using the versions from msi:

```
C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager
C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement
C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage
```

**Comment by markcowl** [comment]
Closing again, as no further contact.  Please re-open if this recurs
