### ISSUE TITLE
0.8.14 :: Set-AzureResource Error "UnsupportedRequestContent: Request content is not well formed or supported."

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#235]
When I try to call `Set-AzureResource`, to change the `enabled` property on a `microsoft.insights/autoscalesettings` resource, I get an error.

> Set-AzureResource: UnsupportedRequestContent: Request content is not well formed or supported.

![image](https://cloud.githubusercontent.com/assets/466713/6513522/7618880a-c330-11e4-8eb9-3b590af7076b.png)

How can I successfully use `Set-AzureResource` to change properties on Azure Resources through the Azure Resource Manager REST API?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 I believe this is the same issue already raised - you need to provide the full configuration, not just the property you want to change.  Cllsing becasue I think this is covered by the existing issues.  Please reopen if you disagree.

**Comment by pcgeek86** [comment]
@markcowl The issue was resolved by providing a complete list of properties for the resource, rather than just the "patch." However, it would be really cool if ARM supported the HTTP PATCH verb, so you could provide partial updates to ARM resources. Where is the best place to file feedback items on the ARM REST API itself?

Thanks for your time.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by matt-gibbs** [comment]
@pcgeek86 File them in the .Net repo  https://github.com/Azure/azure-sdk-for-net 
It's still a level of indirection away, but it'll work. For the PATCH verb, no need to file. It's an ongoing discussion where we are looking at the overall approach for dealing with sparsely populated objects for the client models as well as the REST API support.
