### ISSUE TITLE
Get-AzureRmVm -Status returns empty values

### ISSUE THREAD

**Issue by avishnyakov** [Azure/azure-powershell#2350]
Calling Get-AzureRmVm -Status within Azure Automation returns empty .Statuses prop. The objects are there yet Code / Level / DisplayStatus props are empty. Calling same Get-AzureRmVm -Status from the local laptop works well.

All packaged were uploaded to Azure automation from the local laptop.

Any ideas how to troubleshoot that?

**Comment by singhkays** [comment]
@avishnyakov If this works with the local cmdlet this could be something up with the Automation service. Please file a support ticket to debug this.
