### ISSUE TITLE
Get-AzureRmAutomationSchedule Requested value 'Week' was not found.

### ISSUE THREAD

**Issue by miquelcv** [Azure/azure-powershell#2353]
I have an schedule asset that is using weekly schedules, it seems that Get-AzureRMAutomationSchedule can't handle this kind of schedules.

**Module Version**
Azure 1.4.0
AzureRM.Automation 1.0.8

**Error**
Get-AzureRmAutomationSchedule : Requested value 'Week' was not found.
At line:1 char:62
- Get-AzureRmAutomationSchedule -ResourceGroupName $Automat ...
-                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Get-AzureRmAutomationSchedule], ArgumentException
  - FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationSchedule

**Comment by maddieclayton** [comment]
@vrdmr Can you take a look at this issue and close if it is no longer an issue in today's version of AzureRM?

**Comment by Bpoe** [comment]
This is a very old verion of the cmdlets that was created before we had support for Weekly schedules, so this is expected. Please upgrade to a newer version of the cmdlets.
