### ISSUE TITLE
[Eng]: Improve error message related to the use of the UbutntuLTS alias 

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#23581]
### Description

The error message returned when using the 'UbuntuLTS' alias is not very explicit:

```
New-AzVM -ResourceGroupName <ResourceGroupName> -Name myVM -Image UbuntuLTS -Credential (Get-Credential)
New-AzVM: Can't find the image 'ubuntults'.
```

Can we use something similar to:

_Invalid image "ubuntults". Use a valid image URN, custom image name, custom image id, VHD blob URI, or pick an image from ['CentOS85Gen2', 'Debian11', 'FlatcarLinuxFreeGen2', 'OpenSuseLeap154Gen2', 'RHELRaw8LVMGen2', 'SuseSles15SP3', 'Ubuntu2204', 'Win2022Datacenter', 'Win2022AzureEditionCore', 'Win2019Datacenter', 'Win2016Datacenter', 'Win2012R2Datacenter', 'Win2012Datacenter', 'Win2008R2SP1']._

**Comment by TravisCragg-MSFT** [comment]
@dcaro Thanks for the feedback! I am involving our PS team for more information.

**Comment by haagha** [comment]
This should be addressed by @grizzlytheodore changes. @dcaro can you check again and close this issue.

**Comment by dcaro** [comment]
It would better to display the list of aliases in the output of the command rather than having to go to our docs but the implemented solution works.
