### ISSUE TITLE
0.8.14 :: Set-AzureResource Error "UnsupportedRequestContent: Request content is not well formed or supported."

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#236]
When I try to call `Set-AzureResource`, to change the `enabled` property on a `microsoft.insights/autoscalesettings` resource, I get an error.

> Set-AzureResource: UnsupportedRequestContent: Request content is not well formed or supported.

![image](https://cloud.githubusercontent.com/assets/466713/6513522/7618880a-c330-11e4-8eb9-3b590af7076b.png)

Here's the code I'm trying to use:

```
$AutoscaleSettings = @{
    ResourceType = 'microsoft.insights/autoscalesettings';
    Name = 'partsunlimitedwebloadtest-PartsUnlimitedWebLoadTest';
    ApiVersion = '2014-04-01';
    ResourceGroupName = 'PartsUnlimitedWebLoadTest';
    };
$Resource = Get-AzureResource @AutoscaleSettings;

Set-AzureResource @AutoscaleSettings -PropertyObject @{ enabled = 'True'; };
```
How can I successfully use `Set-AzureResource` to change properties on Azure Resources through the Azure Resource Manager REST API?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by yangl900** [comment]
Hi Trevor,

You should always provide the full properties set to Set-AzureResource. Basically use Get-AzureResource to fetch current properties, modify, and use Set-AzureResource to update. Please see the samples here:
https://msdn.microsoft.com/en-us/library/dn654578.aspx

thanks,
Anders

**Comment by pcgeek86** [comment]
Anders,

Thanks for the feedback. The help documentation for the `-PropertyObject` parameter for `Set-AzureResource` does not indicate this. Can this documentation get updated?

```
PS C:\Users\Trevor> help Set-AzureResource -Parameter prop*

-PropertyObject <Hashtable>
    Specifies the new property values. Enter a hash table of property names and values. The names and values are case-sensitive.
    
    Required?                    false
    Position?                    named
    Default value                
    Accept pipeline input?       true (ByPropertyName)
    Accept wildcard characters?  false
```

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by ravbhatnagar** [comment]
Update documentation

**Comment by ravbhatnagar** [comment]
Fixed May 2016
