### ISSUE TITLE
On version 1.4 the validation for the templates is wrong

### ISSUE THREAD

**Issue by Nepomuceno** [Azure/azure-powershell#2361]
When I try to validate a template that has a Servicebus Namespace on it the validation got rejects if the name of the namespace contains dashes on it (-) what is incorrect since servicebus namespaces can have dashes on it.

To reproduce just try to deploy the template

```
{
      "apiVersion": "2015-08-01",
      "name": "ms-test-service-bus",
      "type": "Microsoft.ServiceBus/namespaces",
      "location": "[resourceGroup().location]",
      "sku": {
        "name": "StandardSku",
        "tier": "Standard",
        "capacity": "1"
      },
      "resources": []
    }
```

**Comment by cormacpayne** [comment]
Closing as this is a service issue. Please re-open if you continue to see this problem.
