### ISSUE TITLE
get-AzDataFactoryV2Pipeline : HTTP Status Code: NotFound

### ISSUE THREAD

**Issue by jab507** [Azure/azure-powershell#23639]
### Type of issue

Outdated article

### Feedback

Enfrentei há alguns dias problema relacionado ao get-AzDataFactoryV2Pipeline : HTTP Status Code: NotFound, onde executava  Get-AzDataFactoryV2Pipeline -ResourceGroup $resourceGroup -DataFactoryName $dataFactoryName e recebia o seguinte erro "get-AzDataFactoryV2Pipeline : HTTP Status Code: NotFound"

***Executar o PShell como Administrador**

**Verificar qual a versão está instalado do modulo:**
```
Get-Module AzureRm.DataFactoryV2
ModuleType Version Name ExportedCommands
---------- ------- ---- ----------------
0.5.8     AzureRM.DataFactoryV2               PSGallery            Microsof...
```

**Então verificar a última versão na internet:**
```
Find-Module AzureRm.DataFactoryV2
Version    Name                           Repository        Description
-------    ----                                ----------           -----------
0.5.12     AzureRM.DataFactoryV2               PSGallery            Microsof...

```
OK, vamos executar a criação do ADF novamente:
Update-Module AzureRm.DataFactoryV2

Pronto, agora podemos executar o Get-AzDataFactoryV2Pipeline.
*Fechar todas as janela do PowerShell e abrir novamente para executar o comando.

OBS.:
1) atualize o módulo AzureRm.DataFactoryV2 primeiro.
2) reinicie a sessão do PowerShell.
3) verifique o nome do grupo de recursos se está correto e nome do datafactory.

### Page URL

https://learn.microsoft.com/pt-br/powershell/module/az.datafactory/get-azdatafactoryv2pipelinerun?view=azps-11.0.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/DataFactory/DataFactoryV2/help/Get-AzDataFactoryV2PipelineRun.md

### Author

@jab507

### Document Id

65098565-fcf9-94c1-7788-35a01dd2e8eb

**Comment by isra-fel** [comment]
Hi @jab507 ,
Please make sure you are using the latest [Az.DataFactory 1.17.1](https://www.powershellgallery.com/packages/Az.DataFactory/1.17.1) instead of `AzureRM.DataFactoryV2` because AzureRM is a legacy product.
