### ISSUE TITLE
Wrong default value of "-AllowBlobPublicAccess" and "-AllowCrossTenantReplication"

### ISSUE THREAD

**Issue by noiri-hub** [Azure/azure-powershell#23645]
### Type of issue

Missing information

### Feedback

Default values of "AllowBlobPublicAccess" and "AllowCrossTenantReplication" had been already changed, but document still introduce "The default interpretation is true for this property."

Users have already got this update notification at May 2023.
According to following article, this change was adapted for Powershell from Nov 2023. It means default values have been already changed even if we create Azure Storage from Powershell. Actually, this behavior has been already changed and Azure Storage was created with "AllowBlobPublicAccess: false" and "AllowCrossTenantReplication: false" when we do not set values.

https://techcommunity.microsoft.com/t5/azure-storage-blog/azure-storage-updating-some-default-security-settings-on-new/ba-p/3819554
> For accounts created through Storage REST API, PowerShell, CLI, SDKs, Terraform and ARM templates, the new defaults for both configurations will be applied starting Nov 2023.  

I found some case that users misunderstand this default value by this document.
I believe we should fix about this default values.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.storage/new-azstorageaccount?view=azps-11.0.0#-allowblobpublicaccess

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/Storage/Storage.Management/help/New-AzStorageAccount.md

### Author

@mikefrobbins

### Document Id

75c4407a-fce4-1282-029d-874289394f54

**Comment by yifanz7** [comment]
@noiri-hub The change is made on the server, and the server deployment takes some time. It's possible that the default value has already been updated given the rollout is going on. 
For PSH cmdlets, please refer to the docs below: 
[[Az.Storage] New created storage account might fail to enable public access on blob container (Set-AzStorageContainerAcl) #22360](https://github.com/Azure/azure-powershell/issues/22360)
[[Az.Storage] New created storage account might fail to do cross tenant object replication with Set-AzStorageObjectReplicationPolicy #22361](https://github.com/Azure/azure-powershell/issues/22361)
We will update the doc once the server deployment is done.
