### ISSUE TITLE
No documentation for Available Azure Services is China

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#2364]
There is no mention of AzureChina Region in the official "Azure Services Region page"
[https://azure.microsoft.com/en-us/regions/#services]

It will be helpful to know what are the services available in Azure China.

Thanks,
Pradebban Raja

**Comment by markcowl** [comment]
@Pradebban This is the repo for azure-powershell, not for the azure web pages.  Can you please place a comment directly on that page?

The page may also be here: https://github.com/Azure/azure-content
