### ISSUE TITLE
New-AzureRmStorageAccount - not working for Location - China East/ China North

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#2366]
New-AzureRmStorageAccount -ResourceGroupName SAMPLE1 -Name "Sample" -Type Standard_GRS -Location "**China East**"

New-AzureRmStorageAccount : Specified argument was out of the range of valid values.
Parameter name: accountName
At line:1 char:1
+ New-AzureRmStorageAccount -ResourceGroupName SAMPLE1 -Name "Sample" -Type Standa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmStorageAccount], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.NewAzureStorageAccountCommand

Thanks,
Pradebban Raja

**Comment by pcgeek86** [comment]
The error is complaining about your invalid Storage Account Name, not the `-Location` parameter. Storage Account names must be lowercase.

**Comment by Pradebban** [comment]
Got it, thanks @pcgeek86
