### ISSUE TITLE
New-AzureRmApiManagement not supported for China Regions

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#2367]
New-AzureRmApiManagement -ResourceGroupName SAMPLE1 -Name "sampleapim" -Location "**China East**"
New-AzureRmApiManagement : Cannot validate argument on parameter 'Location'. The argument "China East" does not belong to the set
"North Central US,South Central US,Central US,West Europe,North Europe,West US,East US,East US 2,Japan East,Japan West,Brazil
South,Southeast Asia,East Asia,Australia East,Australia Southeast" specified by the ValidateSet attribute. Supply an argument that is
in the set and then try the command again.
At line:1 char:82
+ ... pim" -Location "China East"
+                    ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzureRmApiManagement], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.ApiManagement.Commands.NewAzureApiManagement

Please let me know when this is available in China and also let me know any documentation stating this is not available in China.

Thanks,
Pradebban Raja

**Comment by markcowl** [comment]
@Pradebban Note that you can get a list of services and supported regions using
```
Add-AzureRMAccount -EnvironmentName AzureChinaCloud
Get-AzureRMLocation
```

**Comment by Pradebban** [comment]
@markcowl Below is the error which am getting. Between please let me know on what basis the issue is closed?

Get-AzureRMLocation
Get-AzureRMLocation : The term 'Get-AzureRMLocation' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-AzureRMLocation
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureRMLocation:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
