### ISSUE TITLE
New-AzureRmResourceGroupDeployment should throw exception if value specified for -TemplateParameterFile parameter is missing

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2370]
`New-AzureRmResourceGroupDeployment` should throw exception if value specified for `-TemplateParameterFile` parameter is invalid. Filesystem path should be tested. If missing, throw an exception.

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by ravbhatnagar** [comment]
Agreed, we should fix this.

**Comment by cormacpayne** [comment]
The fix for this has been merged and will be available in the next release of `Az` (2019-01-29).
