### ISSUE TITLE
Get-AzureRmAutomationDscCompilationJobOutput Summary does not display entire summary text

### ISSUE THREAD

**Issue by GamerLivingWill** [Azure/azure-powershell#2373]
This is what is displayed when you run Get-AzureRmAutomationDscCompilationJobOutput
ResourceGroupName     : azdsc
AutomationAccountName : dscdemo
JobId                 : 
StreamRecordId        : 
Time                  : 5/31/2016 2:44:08 PM -04:00
Summary               : <jobid>:[localhost]:The 'Microsoft.PowerShell.Manag...
Type                  : Warning

If you view the Summary property, you get this:
PS C:\Scripts\JumpBoxDeployAzure> $DSCCompOutput.summary
<jobid>:[localhost]:The 'Microsoft.PowerShell.Manag...

While in the UI, you get the entire text.

**Comment by jodoglevy** [comment]
@GamerLivingWill thanks, I will track this internally. For runbook jobs, Get-[AzureRMAutomationJobOutputRecord](https://msdn.microsoft.com/en-us/library/mt643911.aspx) can be used, but we don't have a cmdlet like this for DSC compilation jobs yet.

**Comment by maddieclayton** [comment]
@vrdmr Can you take a look at this issue? Is it still an issue in today's version of AzureRM?

**Comment by nitinbps** [comment]
Does not meet customer bar as no functional impact.
