### ISSUE TITLE
Please add "select-azsubscription" before running main command.

### ISSUE THREAD

**Issue by nthorve** [Azure/azure-powershell#23733]
### Type of issue

Other (describe below)

### Feedback

Please add a link in all PS documents to initiate with "select-azsubscription". Without this we get error message.
For any customer or new engineer this step is not know.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.network/set-azroutingintent?view=azps-11.1.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/Network/Network/help/Set-AzRoutingIntent.md

### Author

@mikefrobbins

### Document Id

943a5113-9551-3644-e383-71dfc8aa23ed

**Comment by isra-fel** [comment]
Hi @nthorve I hope to understand more context - when `Connect-AzAccount` a subscription will be chosen as the default subscription. So you don't need to `select-azsubscription` again.
