### ISSUE TITLE
Az.Account 2.13.2(latest version) is using a outdated dependency System.Net.Http.WinHttpHandler 4.4.0 which contains vulnerability

### ISSUE THREAD

**Issue by jejass** [Azure/azure-powershell#23752]
### Description

cx is using blackduck scanning their container images which have Az.Account 2.13.2 (latest module) installed. they found a vulnerabilities from this module. 
![image](https://github.com/Azure/azure-powershell/assets/32087564/06bdfa60-7654-431b-b5ef-e493d4b0193d)
![image](https://github.com/Azure/azure-powershell/assets/32087564/dfc9e4a7-034a-4bae-ab27-8391c30f0b93)

As per confirmation with .net core team, there's no CVE from 2017 that is applicable to any currently supported version of ASP.NET Core.  Module mentioned is from 1.x version (long out of support).

That scanning tool is saying that Az.Accounts PS module (https://www.powershellgallery.com/packages/Az.Accounts/2.13.2) and specifically that version (which is very latest one released just a about a month ago) contains an old outdated dependency that is vulnerable from 2017. 

That PS module (Az.Accounts) is indeed distributing that build mentioned (4.6.25519.03) which *is* the 4.4.0 version which does contain vulnerability.  It is imperative that owners of this PS module (AZ.Accounts) look into this closely and explain what is happening and why is this outdated vulnerable build still being distributed..

Please kindly help to check if the Az.Account module contains the outdated dependency and how to fix it.

### Module versions

```PowerShell
Az.Account 2.12.2
```

**Comment by isra-fel** [comment]
Thanks for reporting. We will update the outdated dependency in the upcoming release. cc @msJinLei
