### ISSUE TITLE
[Functions] Update logic to populate tab completers and cache in the New-AzFunctionApp cmdlet

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-powershell#23788]
### Description

Currently, the tab completers for the `Runtime` and `RuntimeVersion` parameters in the `New-AzFunctionApp` cmdlet are populated upon importing the `Az.Functions` module. However, this operation requires calling an ARM API with authentication. If there is no active session, this operation will result in an error. Additionally, this operation is used to create a cache with configuration options for creating function apps in the Functions service. To address this behavior, we propose the following steps:

1) When `Az.Functions` is imported, if there is no active Azure PowerShell session, the tab completers and cache should not be populated.

2) Next, we should populate the tab completer and build the cache only when there is an active Azure PowerShell session and under these conditions:
a. The user invokes the `New-AzFunctionApp` cmdlet. It is important to note that the tab completers will not be populated until the `New-AzFunctionApp` cmdlet is invoked for the first time. Subsequently, the tab completers will be available from the second invocation of the `New-AzFunctionApp` cmdlet onwards.
b. The user invokes any cmdlet from the `Az.Functions` module.

### Issue script & Debug output

```PowerShell
N/A
```

### Environment data

```PowerShell
N/A
```

### Module versions

```PowerShell
N/A
```

### Error output

```PowerShell
N/A
```

**Comment by isra-fel** [comment]
For all that stumble accross this issue, currently the work-arounds are:

Run Connect-AzAccount to sign in before Import-Module Az, or
Do not explictly Import-Module Az at all. (Only works if your script doesn't depend on Az.Functions module)

**Comment by Francisco-Gamino** [comment]
I've verified that this issue has been fixed in Az 11.6.0. We are waiting for the release to customers before closing this issue.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed.
