### ISSUE TITLE
Exception in Set-AzureRmSqlServer

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2378]
PS C:\Users\TrevorSullivan> Set-AzureRmSqlServer -ResourceGroupName ArtofShell-ElasticSQL -ServerName aoselastic -ServerVersion 12.0
WARNING: The usability of Tag parameter in this cmdlet will be modified in a future release. This will impact creating, updating and appendin
g tags for Azure resources. For more details about the change, please visit https://github.com/Azure/azure-powershell/issues/726#issuecomment
-213545494
Set-AzureRmSqlServer : Value cannot be null.
Parameter name: s
At line:1 char:1
- Set-AzureRmSqlServer -ResourceGroupName ArtofShell-ElasticSQL -Server ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Set-AzureRmSqlServer], ArgumentNullException
  - FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.Server.Cmdlet.SetAzureSqlServer

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by jamestao** [comment]
Addressed in #3206.
