### ISSUE TITLE
Update-AzOperationalInsightsTable :: Use default workspace settings

### ISSUE THREAD

**Issue by francesco1119** [Azure/azure-powershell#23785]
### Description of the new feature

When you want to update the Data retention setting of a Log Analytics workspace you are allowed to set: 

- **RetentionInDays** 
- **TotalRetentionInDays** 

And in the end the command looks like this: 

`Update-AzOperationalInsightsTable -ResourceGroupName MyResourceGroupName -WorkspaceName MyWorkspaceName -TableName MyTableName -RetentionInDays 90 -TotalRetentionInDays 730`

A useful feature would be to allow to use the default workspace settings: 

![image](https://github.com/Azure/azure-powershell/assets/3397477/ca78efa4-eea5-4b67-9a09-552ae36de47e)

### Proposed implementation details (optional)

Also, it would be glad to know where to setup that workspace settings: 

- It cannot be setup through the portal 
- It cannot be setup through PowerShell

**Comment by francesco1119** [comment]
Also: this might be linked to https://github.com/Azure/azure-powershell/issues/23784. 

If `Get-AzOperationalInsightsTable` shows tables that don't exist, `Update-AzOperationalInsightsTable` updates tables that don't exist. 

And this might be a bug too.

**Comment by isra-fel** [comment]
Thanks for reporting! @VeryEarly let's check how "Use default workspace settings" is implemented on the portal and we can align.

**Comment by NoriZC** [comment]
Hi @francesco1119 , setting `-RetentionInDays` to -1 will default to the workspace retention. This is clerified in [this doc](https://learn.microsoft.com/en-us/powershell/module/az.operationalinsights/update-azoperationalinsightstable?view=azps-11.1.0#-retentionindays)

And for your proposed implementation details, the workspace settings is defined by service team. You can only leverage it but not change the default value.
