### ISSUE TITLE
inconsistent output when running Get-AzExpressRouteGateway locally on my laptop vs directly on Azure console

### ISSUE THREAD

**Issue by yuem1031** [Azure/azure-powershell#23842]
### Description

inconsistent output when running Get-AzExpressRouteGateway locally on my laptop vs directly on Azure console. please refer to the attachments for details. subscribed id is modified to protect privacy. 
[GW-remote-sub-modified.txt](https://github.com/Azure/azure-powershell/files/13789322/GW-remote-sub-modified.txt)
[GW-local-sub-modified.txt](https://github.com/Azure/azure-powershell/files/13789323/GW-local-sub-modified.txt)

**Comment by yuem1031** [comment]
additional questions: why the following are not included in the output file: 
1) ExpressRouteGatewayScaleUnit 
2) BgpSettings
3) Type:  Microsoft.Network/ExpressRouteGateways

**Comment by isra-fel** [comment]
@yuem1031 Hi, the display format of the cmdlets may vary according to a lot of things, for instance, the version of PowerShell, the width of the console. The point is, those are just formats. They don't have an impact to the actual objects/data returned by the cmdlet. If you'd like to alter the display, see [Using Format commands to change output view](https://learn.microsoft.com/en-us/powershell/scripting/samples/using-format-commands-to-change-output-view?view=powershell-7.4)
