### ISSUE TITLE
[Eng]: Share snapshot deletion prompt message 

### ISSUE THREAD

**Issue by Athreyasubash** [Azure/azure-powershell#23851]
### Description

The confirmation prompt thrown when deleting a snapshot says “Remove Share and all files in it”. This needs to be changed as this is misleading and not correct. The message should read something like this -  Remove share snapshot and all files in it : <Share name>; <SnapshoTime>

**Comment by isra-fel** [comment]
Thanks for the suggestion @Athreyasubash I presume you were talking about the [Remove-AzRmStorageShare](https://github.com/Azure/azure-powershell/blob/eef0311fc1ff3098b6319475cc2cdd1df64b5792/src/Storage/Storage.Management/File/RemoveAzureStorageShare.cs#L218) cmdlet? I'll loop in storage team to look into it. cc @blueww

**Comment by blueww** [comment]
@yifanz7 

This looks already fixed in a recent PR https://github.com/Azure/azure-powershell/pull/23925. 
Would you please confirm?

**Comment by yifanz7** [comment]
> @yifanz7
> 
> This looks already fixed in a recent PR #23925. Would you please confirm?

Yes the fix has been released: 
Gallery Module for Azure PowerShell : https://www.powershellgallery.com/packages/Az/11.3.0
GitHub release: https://github.com/Azure/azure-powershell/releases/tag/v11.3.0-Feb2024

I'll close this issue
