### ISSUE TITLE
Get-AzureRMNetworkInterface should take a VM pipeline object

### ISSUE THREAD

**Issue by philmea** [Azure/azure-powershell#2386]
One should be able to retrieve the network interfaces associated with an Azure VM using the pipeline of the VM Object.

**Comment by markcowl** [comment]
@deepakrajendranmsft can you take a look? Reassign to the compute team as appropriate. We probably do not want a direct type dependency, but a dependency on properties (like resource id or rg _ vmname) could work

**Comment by mikepasco** [comment]
@markcowl  @deepakrajendranmsft Where does this stand? It would be great if I could pass in the NIC resource ID from something like ($vm.NetworkProfile.NetworkInterfaces | ?{$_.Primary -eq $true}).Id
