### ISSUE TITLE
Description requires more clarification 

### ISSUE THREAD

**Issue by basimolimajeed** [Azure/azure-powershell#23864]
### Type of issue

Other (describe below)

### Feedback

The description of the New-AzConnectedMachineExtension command states : The operation to create or update the extension. This is not clear and makes the command seem exactly like the Update and Set versions (I have raised an issue also on the Update command). The New-AzConnectedMachineExtension should be used only to install the extension if it does not exist or to install a different version of the extension. For example if I try to use it to "update" the "EnableAutomaticUpgrade" of the AMA extension then it will not do that (and even worse it will not raise an error to indicate that) see screenshot below:
![image](https://github.com/Azure/azure-powershell/assets/16608331/c1976235-6c6b-4687-ba64-f639c325ce39)

So the description of the command should be clarified so that users do not attempt to change a property like the "EnableAutomaticUpgrade"  while keeping the same version of the extension.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.connectedmachine/new-azconnectedmachineextension?view=azps-11.1.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/ConnectedMachine/ConnectedMachine/help/New-AzConnectedMachineExtension.md

### Author

@mikefrobbins

### Document Id

ad0e9468-3ca2-daa8-561e-6bfd3368c44b

**Comment by wyunchi-ms** [comment]
@Alex-wdy please help to loop to service team

**Comment by yaotongms** [comment]
Description of this command will get fixed in the next release.

**Comment by yaotongms** [comment]
I updated the command description so now it only suggests user to create a new extension via New-AzConnectedMachineExtension
