### ISSUE TITLE
misleading description of command Update-AzConnectedMachineExtension

### ISSUE THREAD

**Issue by basimolimajeed** [Azure/azure-powershell#23863]
### Type of issue

Other (describe below)

### Feedback

Misleading description: The  command Update-AzConnectedMachineExtension does not create an extension if it did not exist, but the document says "The operation to create or update the extension." I tried this with the AMA extension for example 
![image](https://github.com/Azure/azure-powershell/assets/16608331/e92a4048-fa65-4c6c-bbb6-bf21343a47b9)

So the description should be changed to not include the word "create"

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.connectedmachine/update-azconnectedmachineextension?view=azps-11.1.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/ConnectedMachine/ConnectedMachine/help/Update-AzConnectedMachineExtension.md

### Author

@mikefrobbins

### Document Id

567f96b9-15b8-2f17-ffd6-1b403efce923

**Comment by wyunchi-ms** [comment]
@Alex-wdy please loop to service team.

**Comment by raghushantha** [comment]
https://github.com/Azure/azure-powershell/pull/25132

PR to update the description
