### ISSUE TITLE
The description of the Set-AzConnectedMachineExtension command needs clarification

### ISSUE THREAD

**Issue by basimolimajeed** [Azure/azure-powershell#23865]
### Type of issue

Other (describe below)

### Feedback

The description of the Set-AzConnectedMachineExtension command states : The operation to create or update the extension. This is not clear and makes the command seem exactly like the New and Update versions (I have raised an issue also on the those commands). The Set-AzConnectedMachineExtension does not seem to work if we want to "update" a property  while keeping the extension version the same. For example if I try to use it to "update" the "EnableAutomaticUpgrade" of the AMA extension then it will not do that (and even worse it will not raise an error to indicate that) see screenshot below:
![image](https://github.com/Azure/azure-powershell/assets/16608331/4e7ce52c-8e92-4c23-98d6-18fb498b4bc5)

The description of the command needs to be clarified and the differences between it and the New-AzConnectedMachineExtension and Update-AzConnectedMachineExtension need to be made clear

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.connectedmachine/set-azconnectedmachineextension?view=azps-11.1.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/ConnectedMachine/ConnectedMachine/help/Set-AzConnectedMachineExtension.md

### Author

@mikefrobbins

### Document Id

43983134-ffd2-2001-2175-b65b8e773d0c

**Comment by yaotongms** [comment]
Set-AzConnectedMachineExtension is sending out a PUT and updates the entire resource
Update-AzConnectedMachineExtension is sending out a PATCH and updates only the fields that need to be changed

The description will get updated in the next release, which is coming out at the end of June or beginning of July.

**Comment by yaotongms** [comment]
Description for Update-AzConnectedMachineExtension is fixed in this PR. Close this PR.

https://github.com/Azure/azure-rest-api-specs/pull/29510
