### ISSUE TITLE
Get-AzureResrouceGroup returned not-exited resource

### ISSUE THREAD

**Issue by kexuelou** [Azure/azure-powershell#239]
PS C:\Windows\system32> get-AzureResourcegroup -name Default-Web-EastAsia

ResourceGroupName : Default-Web-EastAsia
Location          : eastasia
ProvisioningState : Succeeded
Tags              : 
Permissions       : 
                    Actions  NotActions
                    =======  ==========
                    *                  
                    
Resources         : 
                    Name                                      Type                                  Location 
                    ========================================  ====================================  =========
                    Default0                                  Microsoft.Web/serverFarms             eastasia 
                    Default1                                  Microsoft.Web/serverFarms             eastasia 
                    Default2                                  Microsoft.Web/serverFarms             eastasia 
                    Default3                                  Microsoft.Web/serverFarms             eastasia 
                    DefaultServerFarm                         Microsoft.Web/serverFarms             eastasia 
           

PS C:\Windows\system32> remove-AzureResource -Name Default1 -ResourceGroupName  Default-Web-EastAsia -ResourceType  Microsoft.Web/serverFarms  -ApiVersion 2014-04-01 -Verbose
详细信息: 正在目标“Default1”上执行操作“Removing resource ...”。
remove-AzureResource : Provided resource does not exist.
所在位置 行:1 字符: 1
+ remove-AzureResource -Name Default1 -ResourceGroupName  Default-Web-EastAsia -Re ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Remove-AzureResource]，ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.RemoveAzureResourceCommand

**Comment by markcowl** [comment]
@kexuelou Can you check the api version?  it should be 2014-11-01

**Comment by vivsriaus** [comment]
This is by design. ARM maintains a cache that can be out of sync with the resource provider in rare conditions. To resolve this, you can get the resource by passing in -ResourceId. This will cause the ARM cache to sync that resource, which may take some time (usually a few minutes, but could be longer).

If the problem persists after that, please contact customer support.
