### ISSUE TITLE
AzureRM cmdlets - Named Inputs vs. JSON Outputs

### ISSUE THREAD

**Issue by philmea** [Azure/azure-powershell#2399]
The inputs of most of the cmdlets take Name values, but the outputs of the cmdlets are usually JSON resource ID's. This inhibits the graceful pipelining of values and the discoverability of relationships. 

For example, if I want to find the VNET associated with a VM, I need to do the following:
1) Grab the VM Object: $vmObj = Get-AzureRmVM -Name $vmName -ResourceGroupName $rgName
2) Find the NIC based on VM resource ID matching: $vmNICObj = Get-AzureRmNetworkInterface | where {$_.VirtualMachine.Id -eq $vmObj.Id}
3) Find the VNET based on matching the **subnet** resource ID: $vnetObj = Get-AzureRmVirtualNetwork | where {$_.Subnets.Id -match $vmNICObj.IpConfigurations.Subnet.Id}.

I could have found this in the UI in a second, looking at the VM properties. Why can't we return useful Names alongside ID's? VM is on VNET "Contoso" attached to Subnet "FrontEnd".

This is just ugly and ungraceful and difficult. We need to think about the relationships of these items and how to query those relationships easily for scripting purposes.

**Comment by markcowl** [comment]
@singhkay Can you loop @philmea in on your discussions of vm cmdlet outputs?

**Comment by maddieclayton** [comment]
Closing this as most of the output models that I am looking at now have name properties.  Please reopen if this is still an issue.
