### ISSUE TITLE
related resources should be deleted as well when delete a website

### ISSUE THREAD

**Issue by kexuelou** [Azure/azure-powershell#240]
When create a site, a related Microsoft Insights resource is created by automatically. this need to be removed when deleting the site.

PS C:\Windows\system32> get-AzureResourcegroup -name Default-Web-EastAsia

ResourceGroupName : Default-Web-EastAsia
Location          : eastasia
ProvisioningState : Succeeded
Tags              : 
Permissions       : 
                    Actions  NotActions
                    =======  ==========
                    *                  
                    
Resources         : 
                    Name                                      Type                                  Location 
                    ========================================  

                    bestbakery                                microsoft.insights/components         centralus
                    bigtree2                                  microsoft.insights/components         centralus
                    ContosoCorpSite                           microsoft.insights/components         centralus
                    ContosoDrupal                             microsoft.insights/components         centralus
                    contosoedu                                microsoft.insights/components         centralus
                    ContosoMarcket                            microsoft.insights/components         centralus
                    ContosoRedis                              microsoft.insights/components         centralus
                    ContosoVPNSite                            microsoft.insights/components         centralus
                    ContosoWebSites                           microsoft.insights/components         centralus
                    hk1test                                   microsoft.insights/components         centralus
                    maws                                      microsoft.insights/components         centralus
                    newrelic                                  microsoft.insights/components         centralus
                    phperror                                  microsoft.insights/components         centralus
                    productweb                                microsoft.insights/components         centralus
                    quotaviolation                            microsoft.insights/components         centralus
                    slowsite                                  microsoft.insights/components         centralus
                    waws-tm-hk                                microsoft.insights/components         centralus
                    websocketkeycalculator                    microsoft.insights/components         centralus
                    wzhaoBakery                               microsoft.insights/components         centralus
                    wzhaocerttest                             microsoft.insights/components         centralus
                    WzhaoDaas                                 microsoft.insights/components         centralus
                    wzhaodnn                                  microsoft.insights/components         centralus
                    wzhaodropbox                              microsoft.insights/components         centralus
                    wzhaogithub                               microsoft.insights/components         centralus
                    wzhaonode                                 microsoft.insights/components         centralus
                    wzhaops                                   microsoft.insights/components         centralus
                    wzhaotest0                                microsoft.insights/components         centralus
                    wzhaotest1                                microsoft.insights/components         centralus
                    wzhaotest10                               microsoft.insights/components         centralus
                    wzhaotest11                               microsoft.insights/components         centralus
                    wzhaotest12                               microsoft.insights/components         centralus
                    wzhaotest13                               microsoft.insights/components         centralus
                    wzhaotest14                               microsoft.insights/components         centralus
                    wzhaotest15                               microsoft.insights/components         centralus
                    wzhaotest16                               microsoft.insights/components         centralus
                    wzhaotest17                               microsoft.insights/components         centralus
                    wzhaotest18                               microsoft.insights/components         centralus
                    wzhaotest2                                microsoft.insights/components         centralus
                    wzhaotest3                                microsoft.insights/components         centralus
                    wzhaotest4                                microsoft.insights/components         centralus
                    wzhaotest5                                microsoft.insights/components         centralus
                    wzhaotest6                                microsoft.insights/components         centralus
                    wzhaotest7                                microsoft.insights/components         centralus
                    wzhaotest8                                microsoft.insights/components         centralus
                    wzhaotest9                                microsoft.insights/components         centralus
                    wzhaotomcat                               microsoft.insights/components         centralus
                    wzhaowordpress                            microsoft.insights/components         centralus

**Comment by markcowl** [comment]
@kexuelou This is what resource groups are for - the resource group is meant as the unit of management for your application
