### ISSUE TITLE
*Warning* The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.

### ISSUE THREAD

**Issue by zcarroll4** [Azure/azure-powershell#24033]
### Description

Is this a breaking change that will need to be addressed in our scripts/runbooks?

- The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.

I've seen suppressing the warning is an option but I'd prefer not to if the warning will cause us issues later.

### Module versions

- Az.Monitor - 4.6.0

### Error output

The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.

**Comment by Juanito99** [comment]
Hello,

the message is stilla appearing.

Please advise if we need to take action in order to avoid failures in our scripts.

Thank you
