### ISSUE TITLE
Installer quits Powershell process

### ISSUE THREAD

**Issue by TheCodeKing** [Azure/azure-powershell#2404]
We have automated scripts for installing powershell Azure SDK on Azure VMs during provisioning. This was all good in 1.0.1. I've just tried upgrading to 1.4.0 and 1.5.0. 

Now when powershell Azure SDK is installed it quits the existing process and breaks provisioning scripts which never get any further. Is there a way to prevent this happening?

**Comment by markcowl** [comment]
@TheCodeKing This will be resolved in the installer rewrite tracked in #2220   .  Meanwhile, you can uninstall the msi and install from the PowerShell Gallery to avoid any similar issues.
