### ISSUE TITLE
Set-AzureRmContext params have changed

### ISSUE THREAD

**Issue by TheCodeKing** [Azure/azure-powershell#2406]
Just installed 1.50. I have scripts using Set-AzureRmContext with subscriptionId and TenantId. The cmdlet now only accepts context and subscriptionName.

Is this intentional? Any documentation on it? Help still points to the old params.

**Comment by spaelling** [comment]
Not sure what you mean by only accepting context? 

I find that it is broken too in maybe the same way? It seems that some sort of dynamic validatation was added. I can do this:

`# this works fine
$SubId = (Set-AzureRmContext -SubscriptionName 'bizspark').Subscription.SubscriptionId
# now this fails: Cannot validate argument on parameter 'SubscriptionId'. The argument "<bizsparkguid>" 
# does not belong to the set "<two guids from something msdn azure subscription>"
Set-AzureRmContext -SubscriptionId $SubId`

**Comment by markcowl** [comment]
Yes, it looks like the added tab completion on values fails under certain circumstances.  This is being tracked in #2387 Please track the fix there.  Closing this as a duplicate for now.
