### ISSUE TITLE
[Feature]: Set-AzDataFactoryV2Pipeline support pipeline return value

### ISSUE THREAD

**Issue by Prefix42** [Azure/azure-powershell#24076]
### Description of the new feature

Cmdlet Set-AzDataFactoryV2Pipeline of Az.DataFactory does not support pipelines making use of the pipelineReturnValue feature, and this feature request is to add the necessary support.

This has already been raised as a bug under #21683 but has gained no traction.

**Comment by isra-fel** [comment]
Thanks for your attention but please refrain from creating duplicated issues. I'll follow up with data factory team internally.
