### ISSUE TITLE
Variables within PowerShell commands need to be explained 

### ISSUE THREAD

**Issue by TimAbmgf** [Azure/azure-powershell#24073]
### Type of issue

Other (describe below)

### Feedback

When I look at the PS commands, there are variables within the examples which are not explained (on what goes into each variable):

1. $ProtectionContainers = Get-AzRecoveryServicesAsrProtectionContainer -Fabric **$fabric**
2. Get-AzRecoveryServicesAsrProtectionContainer -Name xxxxx  -Fabric **$fabric**
3. Get-AzRecoveryServicesAsrProtectionContainer -FriendlyName xxxxxxxx  -Fabric **$fabric**

I feel the examples should explain how to get the data for each variable to run the command

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesasrprotectioncontainer?view=azps-11.2.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesAsrProtectionContainer.md

### Author

@mikefrobbins

### Document Id

32ac543b-3d87-616d-4c77-4df718aed214

**Comment by isra-fel** [comment]
Merge with https://github.com/Azure/azure-powershell/issues/24072
