### ISSUE TITLE
Variables within PowerShell commands need to be explained - part 3

### ISSUE THREAD

**Issue by TimAbmgf** [Azure/azure-powershell#24074]
### Type of issue

Other (describe below)

### Feedback

When I look at the PS commands, there are variables within the examples which are not explained (on what goes into each variable):

1. $ProtectionContainerMappings = Get-AzRecoveryServicesAsrProtectionContainerMapping -ProtectionContainer **$Container**
2. $ProtectionContainerMappings = Get-AzRecoveryServicesAsrProtectionContainerMapping -ProtectionContainer **$Container** -Name $PrimaryProtectionContainerMapping

I feel the examples should explain how to get the data for each variable to run the command

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesasrprotectioncontainermapping?view=azps-11.2.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesAsrProtectionContainerMapping.md

### Author

@mikefrobbins

### Document Id

01828591-dbe4-b587-b1ca-4a55d7679e50

**Comment by isra-fel** [comment]
Merge with https://github.com/Azure/azure-powershell/issues/24072
