### ISSUE TITLE
Get-AzureRmStoraegAccount could not be used in Mooncake.

### ISSUE THREAD

**Issue by andyliuliming** [Azure/azure-powershell#2408]
AzureRmStorageAccount
Get-AzureRmStorageAccount : The resource type 'storageAccounts' could not be found in the namespace
'Microsoft.Storage' for api version '2016-01-01'. The supported api-versions are '2015-06-15,2015-05-01-preview'.
At line:1 char:1
+ Get-AzureRmStorageAccount
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmStorageAccount], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand

**Comment by markcowl** [comment]
@andyliuliming This is by design.  You can use the supported stable version for AzureStack here:  https://github.com/Azure/azure-powershell/releases/download/v1.2.1-February2016/azure-powershell.1.2.1.msi
