### ISSUE TITLE
Error in sample command

### ISSUE THREAD

**Issue by PJMarcum** [Azure/azure-powershell#24087]
### Type of issue

Code doesn't work

### Feedback

The example "Get-AzAccessToken -ResourceTypeName MSGraph" provided in this document generates the following error:

PS C:\Windows\system32> Get-AzAccessToken -ResourceTypeName MSGraph
Get-AzAccessToken : The specified ResourceTypeName "MSGraph" is not supported, please provide a valid value. e.g. Arm, AadGraph, etc.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.accounts/get-azaccesstoken?view=azps-11.2.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/Accounts/Accounts/help/Get-AzAccessToken.md

### Author

@mikefrobbins

### Document Id

838d6af5-702b-8811-9352-332edd36375a

**Comment by isra-fel** [comment]
Hi @PJMarcum the support for MSGraph was added in a later version. Please update your Az.Accounts module to the latest version to get it. Thanks.

**Comment by PJMarcum** [comment]
I gave up on it. I am sure you are right and it's a version thing but I can't get it to update. Even after removing it and adding it back it still says 2.5 version

PS C:\Windows\system32> get-module az.accounts                                                                          PS C:\Windows\system32> Install-Module -Name Az.Accounts -RequiredVersion 2.15.0 -Force -allowclobber                   PS C:\Windows\system32> get-module az.accounts
PS C:\Windows\system32> import-module az.accounts
PS C:\Windows\system32> get-module az.accounts

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.5.0      az.accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Conn...

**Comment by isra-fel** [comment]
Try `Get-Module Az.Accounts -ListAvailable` it will show you where the module was installed. Simplist thing you can do is go there and remove the files then reinstall it.
