### ISSUE TITLE
Resource deletion when Storage account lock is enabled. 

### ISSUE THREAD

**Issue by Athreyasubash** [Azure/azure-powershell#24084]
### Description

I am seeing conflicting behaviors with PowerShell and CLI when executing deletion of file shares/snapshots command. 
when storage account lock is enabled - i am not able to delete file shares or snapshots from powershell and portal but i am able to delete the file share and snapshots from CLI 

I see in the documentation for storage account locks - https://learn.microsoft.com/en-us/azure/storage/common/lock-account-resource?tabs=azure-cli#configure-an-azure-resource-manager-lock

"Locking a storage account does not protect containers or blobs within that account from being deleted or overwritten. For more information about how to protect blob data, see [Data protection overview](https://learn.microsoft.com/en-us/azure/storage/blobs/data-protection-overview)."

### Issue script & Debug output

```PowerShell
N/A
```

### Environment data

```PowerShell
N/A
```

### Module versions

```PowerShell
N/A
```

### Error output

```PowerShell
N/A
```

**Comment by isra-fel** [comment]
Let me loop in Storage team to determine what's the expected behavior. cc @blueww @yifanz7

**Comment by blueww** [comment]
@Athreyasubash 

Would you please share the command you used to delete file shares/snapshots with Powershell, and with CLI. (Hide credentail if any), with the Powershell Az.Storage module version. And better with Powershell debug log.

**Comment by blueww** [comment]
@Athreyasubash 

As we discussed offline, currently after storage account lock is enabled, the share/snapshot can be deleted by dataplane cmdlet (restAPI) but not by resource plane cmdlet (rest API), this is aligned in both Powershell and CLI.
So you can try to delete the share/snapshot with data plane PSH cmdlet Remove-AzStorageShare.

I will close this issue, feel free to contact us again in need any further assistance on Azure Powershell.
