### ISSUE TITLE
Add feature to list specific type of resources

### ISSUE THREAD

**Issue by kexuelou** [Azure/azure-powershell#241]
Need a feature to list all resources of a specified type like follow command. Unfortunately, it requires a Name parameter nowadays.

get-AzureResource -ResourceGroupName  Default-Web-EastAsia -ResourceType  Microsoft.Web/serverFarms  -ApiVersion 2014-04-01 -Verbose

**Comment by markcowl** [comment]
@kexuelou Of course, you can always do this by listing all resources and filtering.  Assigning to the service team.

**Comment by vivsriaus** [comment]
@kexuelou This should now be supported. Can you please retry and let us know? Thanks.
