### ISSUE TITLE
Exception calling Set-AzureRmWebApp against Azure Function App

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2410]
**NOTE**: App Service Plan exists in a different Resource Group than the Function App resource.

![2016-06-05_22-15-48](https://cloud.githubusercontent.com/assets/466713/15825478/1f4df87a-2bc1-11e6-9720-c6fd63063dbb.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@naveedaz can you take a look?

**Comment by panchagnula** [comment]
I can repro this on WebApp after migrating the Serverfarm to a different resource than the app. Assigning to myself to investigate.

**Comment by panchagnula** [comment]
@pcgeek86 run the command without the AppServicePlan - the AppServicePlan is not required for this commandlet & i am planning to remove it so that no one hits this error
