### ISSUE TITLE
Create issues for cmdlets that do not have help

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2413]
![image](https://cloud.githubusercontent.com/assets/466713/15840083/b6194604-2c04-11e6-82d8-2e4c12d56dd7.png)

**Comment by markcowl** [comment]
@pcgeek86 Yes, this is one of the grandfathered-in exceptions when we beagn checking the help.  You can find the full list here: https://github.com/Azure/azure-powershell/blob/dev/tools/StaticAnalysis/Exceptions/HelpIssues.csv 

I will keep this one open to track driving these existing omissions down with the documentation team.
