### ISSUE TITLE
TooManyRequests error for Get-AzureStorageAccount

### ISSUE THREAD

**Issue by sunbinzhu** [Azure/azure-powershell#2417]
I have a subscription with 130+ storage accounts in it. When i run "Get-AzureStorageAccount" to get all storage accounts, an error as below frequently happen:
**Get-AzureStorageAccount : TooManyRequests: Too many requests received. Retry after some time.**
I checked the source code for this command, it will send requests to get storage context for every storage accounts, it means the command will send more than 130+ requests at the same time in my case and triggers the request throttling from Azure side. I remember long time ago (Azure PowerShell 0.8.x), this command just list the storage accounts. It doesn't make sense to change the behavior to get all storage context back, because in most cases, user just want to list the storage accounts.
At least you shall provide a switch type option not to get the context, but just list the storage accounts.

**Comment by markcowl** [comment]
@sunbinzhu This was fixed in the last release, please update to the latest powershell, which has the fix.

**Comment by sunbinzhu** [comment]
thanks mark
