### ISSUE TITLE
Set-AzSynapseDataFlow does not work.

### ISSUE THREAD

**Issue by ein1stein** [Azure/azure-powershell#24178]
### Type of issue

Code doesn't work

### Feedback

I tried to use the below module but to no avail.
Set-AzSynapseDataFlow
   -WorkspaceName <String>
   -Name <String>
   -DefinitionFile <String>

I set the definitionFile parameter to the JSON file path.
Does anyone have already bumped into this problem?
Thanks for your quick response.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.synapse/set-azsynapsedataflow?view=azps-11.3.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/Synapse/Synapse/help/Set-AzSynapseDataFlow.md

### Author

@mikefrobbins

### Document Id

5f143c56-a60d-4bd0-1e83-e26e2a73f0d3

**Comment by isra-fel** [comment]
Hi @ein1stein thanks for reporting. I'll loop in Synapse team.
BTW could you provide the error message and debug log? You can run the command with `-Debug` to see it.

**Comment by kevinzz6** [comment]
Hi @ein1stein, could you please supply more details? For example, upload the definition file (cover your personal info), and what error message return when you run the cmdlet?

**Comment by ein1stein** [comment]
Hi,  The issue was solved yesterday. It was my mistake and I could fix it. The cmdlet works.
Thanks for the quick reply though.
