### ISSUE TITLE
Remove-AzureRmResource Exception: Nullable object must have a value

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2418]
```
$ResourceList = Find-AzureRmResource -TagName AppService
$ResourceList | Format-Table -Property Name, ResourceType
$ResourceList | Remove-AzureRmResource -Force;
```

![image](https://cloud.githubusercontent.com/assets/466713/15863360/f2c19526-2c8f-11e6-86b1-0fa8951d7543.png)

**Comment by markcowl** [comment]
@ravbhatnagar can you take a look?

@pcgeek86 can you execute with ```Trace-Command``` to get the parameter bindings in this failure?

**Comment by gandhiniraj** [comment]
I followed the steps, but couldn't repro the issue. @pcgeek86 can you run 
Trace-Command -Name parameterbinding -Expression { $ResourceList  | Remove-AzureRmResource -Force} -PSHost 
as @markcowl pointed out.

**Comment by ravbhatnagar** [comment]
Closing due to lack of repro as per investigation by @gandhiniraj . Please let us know if you still run into this.
