### ISSUE TITLE
[Feature]: `Get-AzAccessToken` - Option to return token as secure string

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-powershell#24190]
### Description of the new feature

Would be great with an option to return access token as secure string with the `Get-AzAccessToken` cmdlet.

One use case why?

* `Connect-MgGraph -AccessToken` requires secure string.
* `ConvertTo-SecureString -AsPlainText` triggers `PSScriptAnalyzer` rule `PSAvoidUsingConvertToSecureStringWithPlainText`
  * <https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/avoidusingconverttosecurestringwithplaintext>

One more reason why?

* Security best practice: Keep secrets from being plain text if possible.

### Proposed implementation details (optional)

Get-AzAccessToken -AsSecureString

**Comment by isra-fel** [comment]
Thanks for the feedback. Let me add some notes:
Option 1: securestring by default, `-AsPlainText`, but this is a breaking change.
Option 2: plain text by default, `-AsSecureString`.

**Comment by isra-fel** [comment]
Target Az 11.5.0: add -AsSecureString
Target Az 13.0.0: change the default output to SecureString while keeping the `-AsSecureString` parameter.
