### ISSUE TITLE
No documentation for New-AzureRmVirtualNetworkGatewayIpConfig

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2420]
![image](https://cloud.githubusercontent.com/assets/466713/15865228/39f1f02e-2c97-11e6-8cd4-cd663887900e.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 see my response on the earlier bug.  Keeping that one open to track this general class of missing help that was grandfathered in.
