### ISSUE TITLE
Security rule improvements

### ISSUE THREAD

**Issue by philmea** [Azure/azure-powershell#2423]
1) Ability to update network security rule configurations, currently can only add new
2) Return an array object rather than a string for port ranges. Otherwise, no clear way to determine if the range -contains a port (22, 3389, etc.).
3) Standardize pipelining to allow Get | Set | Update commands
4) NSG's should return an "Associated with:" value of NIC or Subnet

**Comment by markcowl** [comment]
@deepakrajendranmsft can you take a look?

**Comment by DeepakRajendranMsft** [comment]
@amitsriva  @lamchester please take a look
