### ISSUE TITLE
Select-AzureSubscription mixed subscriptions between sessions.

### ISSUE THREAD

**Issue by alejandragutierrez** [Azure/azure-powershell#243]
Hello, 

Select-AzureSubscription is not working as it was on 0.6.19. We have a code that execute PowerShell code (using Azure modules) from C#, but we run multiple threads in different Azure Subscriptions at the same time.

When we contact Azure support they verify this, they told us the following:

In Azure PowerShell 0.6.19, current selected subscription is stored as a PowerShell session variable. In your application, each command runs on separate PowerShell object, and therefore each can have use different subscription.

In Azure PowerShell 0.8.12, current selected subscription is stored as a .Net type static variable, its value shares among each PowerShell object, and therefore cause current problem.

Hope you can figure something.

**Comment by chwill** [comment]
Stateless profiles are coming, do you believe this would address your issue? https://github.com/Azure/azure-powershell/wiki/Proposed-Design-Stateless-Azure-Profile

**Comment by markcowl** [comment]
Stateless profile is here.  see the documentation on the wiki:  https://github.com/Azure/azure-powershell/wiki/Proposed-Design-Stateless-Azure-Profile

You should be able to run the commands using two different profiles without interference.
