### ISSUE TITLE
[AzureStack] Get-AzureRMGalleryItem returns error "The resource type could not be found in the namespace"

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-powershell#2430]
This error happens after logging to non-AzureStack environments and making a call to the cmdlets that are available on for AzureStack. We should at least give a better error message so people will not be confused and get the idea that they are using a cmdlets for different environment. Ideally we need to "hide" cmdlets that cannot be called in current environment.

**Comment by bganapa** [comment]
The module is not packaged part of AzureRm anymore.  We have a new uber module AzureStack for azurestack specific modules
