### ISSUE TITLE
 Documentation

### ISSUE THREAD

**Issue by LLotme** [Azure/azure-powershell#24327]
### Type of issue

Missing information

### Feedback

#

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.resourcegraph/get-azresourcegraphquery?view=azps-11.4.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/ResourceGraph/ResourceGraph/help/Get-AzResourceGraphQuery.md

### Author

@mikefrobbins

### Document Id

da0c83e7-109c-b600-8acd-1613c19a8466

**Comment by isra-fel** [comment]
@LLotme please state how you think our document can improve. Thanks.
