### ISSUE TITLE
Issue with New-AzureRmApiManagementApi cmdlets Azure Powershell command

### ISSUE THREAD

**Issue by getanindya** [Azure/azure-powershell#2432]
New-AzureRmApiManagementApi -Context $ApiMgmtContext -Name "EchoApi" -ServiceUrl "https://contoso.com/apis/echo" -Protocols @('http', 'https').

The parameter -Protocols doesn't work with the array of protocols provided.
It is expecting an array of type "Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Models.PsApiManagementSchema"
I couldnt find in the Microsoft cmdlets documentation about the Type  PsApiManagementSchema.
Can any one help me in this regard.

**Comment by solankisamir** [comment]
Try this with double quotes for Protocol
New-AzureRmApiManagementApi -Context $PScontext -Name "Echo api1" -ServiceUrl "https://contoso.com/apis/echo" -Protocols @("http", "https") -Path "testapi"
