### ISSUE TITLE
Add PowerBI Embedded CmdLets

### ISSUE THREAD

**Issue by japj** [Azure/azure-powershell#2433]
Even though PowerBI Embedded is still in preview, it would be very useful if there were already CmdLets in Azure Powershell. This would greatly improve being able to experiment with it.

**Comment by markcowl** [comment]
See #2411

**Comment by wbreza** [comment]
@japj && @markcowl We are lining this up for July release.  Power BI Embedded will be transitioning to GA in July as well.
