### ISSUE TITLE
Get-AzureRMBackupVault returns no object

### ISSUE THREAD

**Issue by philmea** [Azure/azure-powershell#2434]
The Get-AzureRMBackupVault cmdlet is returning no object, though I have 2 backup vaults created, Test01,02. Verified on two separate computers.

**Comment by pomortaz** [comment]
The command is not a key vault PowerShell cmdlet. @markcowl can you please assign it to the owner of [AzureBackup](https://github.com/Azure/azure-powershell/tree/dev/src/ResourceManager/AzureBackup/Commands.AzureBackup/Cmdlets/Vault)?

**Comment by J0shuaTh0mps0n** [comment]
Same issue here.  Were you able to resolve this one?

**Comment by J0shuaTh0mps0n** [comment]
Responding to my own comment and for anybody else that stumbles across this post.

Get-AzureRmBackupVault cmdlet is for listing the backup vaults. If you are trying to get recovery services vault use the below cmdlet:

1.Login-AzureRmAccount
2.Get-AzureRmRecoveryServicesVault -ResourceGroupName “Resource groupname” -Name “Recovery Services Vault”

**Comment by philmea** [comment]
Closing per last comment
