### ISSUE TITLE
Example 1 of Get-AzVM explains incorrectly which properties are returned (but the example output is correct).

### ISSUE THREAD

**Issue by harrisaoz** [Azure/azure-powershell#24350]
### Type of issue

Other (describe below)

### Feedback

The explanatory text for Example 1 currently reads:
"This command gets the model view and instance view properties of the virtual machine named VirtualMachine07."
A correct explanation with minimal change would be:
"This command gets only the model view properties of the virtual machine named VirtualMachine07."

Note that the explanation for Example 2 is somewhat inconsistent in presentation with the explanation for Example 1.  Perhaps that inconsistency could be addressed as part of this fix?

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.compute/get-azvm?view=azps-11.4.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/Compute/Compute/help/Get-AzVM.md

### Author

@mikefrobbins

### Document Id

1b765504-f1ac-6e84-da8b-06d7a2e29ff1

**Comment by grizzlytheodore** [comment]
fix has been merged. closing this issue
