### ISSUE TITLE
Documentation: AzRecoveryServicesBackupContainer  -ContainerType parameter value missing

### ISSUE THREAD

**Issue by MChuzzlewit** [Azure/azure-powershell#24364]
### Type of issue

Missing information

### Feedback

-ContainerType parameter value "AzureSQL" is missing from  the acceptable values listing, in the Get-AzRecoveryServicesBackupContainer cmdlet doc:

https://learn.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesbackupcontainer?view=azps-11.4.0

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesbackupcontainer?view=azps-11.4.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/RecoveryServices/RecoveryServices/help/Get-AzRecoveryServicesBackupContainer.md

### Author

@mikefrobbins

### Document Id

41a289c4-b5a9-81ac-b0db-46c6890899b7

**Comment by MChuzzlewit** [comment]
When you tab through the options for -containertype, one of the parameters is "AzureSQL"

**Comment by hiaga** [comment]
@MChuzzlewit this is expected as we don't expect the value AzureSQL. It is no-op currently and can be ignored. If you wish to fetch SQL containers please use AzureVMAppContainer
