### ISSUE TITLE
Allow Jenkins build result read rights

### ISSUE THREAD

**Issue by japj** [Azure/azure-powershell#2436]
Azure-sdk-for-net is using Travis with access rights for everyone to inspect build results (as part of the pull request check). This is very useful for contributors who want to know if/what went wrong in a build.

At the moment the Jenkins azure-powershell build results are not available due to access rights.
Can this be corrected?

**Comment by markcowl** [comment]
@japj  unfortunately not yet, Jenkins does not support windows - the .net sdk change is cross-platform.  We are tracking an issue specifically to allow this in #2233.  Closign this as a duplicate for now.
