### ISSUE TITLE
Allow adding UserAgent settings through environment variable

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2437]
### Description

At client creation time, after adding in UserAgents from the ClientFactory setting, Read the environment variable `AZURE_HTTP_USER_AGENT` and add the contents to the outgoing user agent for management calls in Azure PowerShell.

Add tests to verify the new functionality (no setting, empty/whictespace setting, valid single setting, valid multiple settings

**Comment by chrisrpatterson** [comment]
How are we progressing here? Do we expect to get this in for July?

**Comment by markcowl** [comment]
@chrisrpatterson unclear

**Comment by chrisrpatterson** [comment]
The xplat-cli has updated their code to incorporate the variable https://github.com/Azure/azure-xplat-cli/pull/2980

**Comment by markcowl** [comment]
This has been open for quite soem time, with no concrete complaints.  If there is a real scenario where the current mechanisms for adding user agents cannot be used, please reopen
