### ISSUE TITLE
Get-AzConnectedMachineExtension returns True for enableAutomaticUpgrade when Null is expected

### ISSUE THREAD

**Issue by YousefImran** [Azure/azure-powershell#24380]
### Description

The **enableAutomaticUpgrade** property returns `True `when the value for this property in Azure portal is "Not Supported".

The enableAutomaticUpgrade property on Azure arc machine extensions have three possible values:
- `True`
- `False`
- `Null`

This is based on the information provided for that type: [`IMachineExtension.EnableAutomaticUpgrade`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.powershell.cmdlets.connectedmachine.models.imachineextensionupdate.enableautomaticupgrade?view=az-ps-latest)

My assumption is that "`Null`" is a representation of "Not Supported" state in Azure portal.

Regardless of whether of my assumption is correct or not, the `Get-AzConnectedMachineExtension` cmdlet should not return `True `for that property when the extension does not support that functionality in the first place.
The issue might be coming from the `True `being the default value for the property. But that should only be the case if the extension supports automatic upgrade in the first place. There is should be a return to indicate "Not Supported" (`Null `for example)

An example would be `Microsoft.Azure.AzureDefenderForServers.MDE.Windows` extension.

**Comment by yaotongms** [comment]
We define enableAutomaticUpgrade as a bool in the code. The portal team knows who onboarded to auto-upgrade.

**Comment by YousefImran** [comment]
> We define enableAutomaticUpgrade as a bool in the code. The portal team knows who onboarded to auto-upgrade.
@yaotongms

I'm sorry. I am not following:

1. `enableAutomaticUpgrade` is defined as `bool?` (nullable bool) per the [documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.powershell.cmdlets.stackhcivm.models.imachineextensionupdate.enableautomaticupgrade?view=az-ps-latest).
2. If `enableAutomaticUpgrade` is in fact defined as `bool` rather `bool?`, how do you support the case when the extension doesn't support automatic upgrade in the first place?
3. Not sure what this means "The portal team knows who onboarded to auto-upgrade."

**Comment by raghushantha** [comment]
For now $null corresponds to a false on the Upgrade Property. We will look into making this a non-nullable boolean in a later release
