### ISSUE TITLE
AzureRM.Websites module is missing all help content 

### ISSUE THREAD

**Issue by TaraMeyer** [Azure/azure-powershell#2440]
The AzureRM.Websites module is missing all help content from the help.xml.  Can someone please add help content to the Microsoft.Azure.Websites.dll help.xml and let me know once it's completed.

The cmdlets in this module are:

Edit-AzureRmWebAppBackupConfiguration.xml
Get-AzureRmAppServicePlanMetrics.xml
Get-AzureRmWebAppBackup.xml
Get-AzureRmWebAppBackupConfiguration.xml
Get-AzureRmWebAppBackupList.xml
Get-AzureRmWebAppSlotConfigName.xml
New-AzureRmWebAppBackup.xml
New-AzureRmWebAppDatabaseBackupSetting.xml
Remove-AzureRmWebAppBackup.xml
Reset-AzureRmWebAppPublishingProfile.xml
Reset-AzureRmWebAppSlotPublishingProfile.xml
Restore-AzureRmWebAppBackup.xml
Set-AzureRmWebAppSlotConfigName.xml

Thanks!

Tara

**Comment by markcowl** [comment]
@TaraMeyer I assume you mean it is missing help content for the given cmdlets?  There is help for some cmdlets.

@akurmi can you take a look?

**Comment by TaraMeyer** [comment]
@markcowl  - that's correct.

**Comment by TaraMeyer** [comment]
@markcowl  any update on this?  Could resolve to an user by the name of @akurmi

**Comment by akurmi** [comment]
@ahmedelnably let's log a work item to track this.

**Comment by TaraMeyer** [comment]
@akurmi  @ahmedelnably looks like the a new cmdlet for the Websites module was included with the latest msi - **Swap-AzureRmWebAppSlot**.  There was no help start content available for this cmdlet either.  Let me know when you have the content ready and I'll have the vendor writer get these topics normalized and added to MSDN.

**Comment by czeumault** [comment]
@akurmi @ahmedelnably - this doesn't look like this was ever updated/fixed.  Can we please get an update?

**Comment by cormacpayne** [comment]
Markdown help can currently be found [here](https://github.com/Azure/azure-powershell/tree/dev/src/ResourceManager/Websites/Commands.Websites/help). We have an action item to get rid of the `dll-Help.xml` file from each RP and generate the help using the markdown files during the build stage. This will update the help you see when calling `Get-Help` for Websites.

**Comment by cormacpayne** [comment]
The help has been updated for the given Websites cmdlets. Closing this issue.
