### ISSUE TITLE
Unable to configure Dual Pass Encryption

### ISSUE THREAD

**Issue by Nilesh25** [Azure/azure-powershell#24412]
### Type of issue

Other (describe below)

### Feedback

I try to configure dual pass encryption and provide Client ID and key vault details. But I get below error. 

Set-AzVMDiskEncryptionExtension: Long running operation failed with status 'Failed'. Additional Info:'The handler for VM extension type 'Microsoft.Azure.Security.AzureDiskEncryptionForLinux' has reported terminal failure for VM extension 'AzureDiskEncryption AzureDiskEncryptionForLinux' with error message: '[ExtensionOperationError] Non-zero exit code: 51, /var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999348/extension_shim.sh -c main/handle.py --install

ErrorCode: VMExtensionHandlerNonTransientError ErrorMessage: The handler for VM extension type 'Microsoft.Azure.Security.AzureDiskEncryptionForLinux' has reported terminal failure for VM extension 'AzureDiskEncryptionForLinux' with error message: '[ExtensionOperationError] Non-zero exit code: 51, /var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999348/extension_shim.sh -c main/handle.py --install

**Comment by nileshjha25** [comment]
Thank you

**Comment by bamuir** [comment]
@Nilesh25 / @nileshjha25  Any reason you are using ADE Dual pass? That is the old version of the extension. I would suggest using ADE Single pass. You can find the docs here:

https://learn.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption-overview

Perhaps you were in the docs for the "Disk encryption - previous version" section. Try the new version of the extension, and let me know if you have issues.

**Comment by nileshjha25** [comment]
Hello @bamuir 

I am able to do it using single pass but want there is a requirement for dual pass hence trying it.

Could you please assist me with the error, how to solve it.

**Comment by nileshjha25** [comment]
Hello @bamuir 

Could you please update on this, we are trying to configure dual pass and it is not working, we have a requirement of dual pass.

**Comment by TravisCragg-MSFT** [comment]
@nileshjha25 @Nilesh25 If your need is only for dual pass, your best bet is to work with Azure support to troubleshoot your specific issue.
