### ISSUE TITLE
TypeHandlerVersion is made mandatory parameter for Set-AzureRmVMCustomScriptExtension

### ISSUE THREAD

**Issue by niadak** [Azure/azure-powershell#2456]
Hi All,
In Azure PowerShell 1.5.0, my scripts has stopped working with error 
Cannot process command because of one or more missing mandatory parameters: TypeHandlerVersion. This is because TypeHandlerVersion is now set as mandatory parameter for Set-AzureRmVMCustomScriptExtension command.

I would like to understand why TypeHandlerVersion become mandatory? And also how to get the correct TypeHandlerVersion version?

When i run 
Get-AzureRmVMExtensionImage -PublisherName 'Microsoft.Compute' -Type 'VMAccessAgent' -Location 'West US'
 I am getting 4 different version (2.0, 2.0.1, 2.0.1, 2.3). Should i use the latest always?

**Comment by avishnyakov** [comment]
Having same issues, not only with AzureRmVMCustomScriptExtension but with some others like Get-AzureRmStorageAccountKey.

There seem to be some breaking changes which weren't properly communicated. I created the following ticket Breaking changes / backward compatibility strategy #2460
https://github.com/Azure/azure-powershell/issues/2460

Hope that can be sorted at some point.

**Comment by avishnyakov** [comment]
@hyonholee, see the following commit with the tests and -TypeHandlerVersion as a required param. Any explanation on why -TypeHandlerVersion is required and not defaulted? That introduces a breaking change over the new releases of Azure PowerShell

https://github.com/Azure/azure-powershell/commit/925820e8da7d2607ebb688258a57b9b4ea226342

We may dig deeper to see who did that change and why, open source rules :)

**Comment by avishnyakov** [comment]
@niadak their tests always use -TypeHandlerVersion "1.1", have no idea why.
Testing with our scripts, touch wood if it works..

**Comment by markcowl** [comment]
@singhkay Can you take a look?

**Comment by hyonholee** [comment]
It is a bug when I merge the common parameters into the base class.

The parameter is mandatory in API spec, but the cmdlet set the value to a default version if a user did not give.

When I move the parameter to the base class, I just followed the API spec and set it to mandatory, which caused the breaking change.

I will fix the issue in the next release.

Thanks for reporting this issue.

**Comment by niadak** [comment]
@hyonholee, Thanks for Acknowledging the issue. We will wait for the next release. Feel free to close the issue.

**Comment by niadak** [comment]
@hyonholee, Can you guild us about recent breaking changes in get-AzureRMStorageKey command. The Object structure has been changed in AzurePS1.4.0. how should we deal with this? Should we adopt the change or are you planing to support back compact for this as well?

**Comment by avishnyakov** [comment]
Hello @niadak @hyonholee and everyone.

Milestone: July 2016
Status: open

Is it open, closed, is anything been done? Cannot see related commits here.

**Comment by avishnyakov** [comment]
Hello @niadak @hyonholee and everyone. Would you please comment on this one? Thanks.

**Comment by avishnyakov** [comment]
cc @markcowl

**Comment by hyonholee** [comment]
This issue was fixed in release 1.6.0.  Thanks.

https://github.com/Azure/azure-powershell/pull/2564/commits/831770b1cc207653bf84cf965aee1413314b38a7
