### ISSUE TITLE
[Feature]: Publish-AzVMDscConfiguration Repository Parameter

### ISSUE THREAD

**Issue by brianwest** [Azure/azure-powershell#24564]
### Description of the new feature

In order to support publishing DSC configurations via the Publish-AzVMDscConfiguration cmdlet in the air-gapped clouds, a repository parameter should be added to support pwsh repositories other than the PSGallery for dependent modules.

**Comment by TravisCragg-MSFT** [comment]
@brianwest Thanks for the feedback. We are currently investigating.

**Comment by GabstaMSFT** [comment]
Looping @n-bajaj and assigning to them

**Comment by n-bajaj** [comment]
There are currently no plans to add this feature in Automation DSC.
Azure Automanage Machine Configuration is the recommended service for DSC related scenarios.

**Comment by GabstaMSFT** [comment]
@brianwest have you been able to determine if using Azure Automanage Machine Configuration will fit your needs as mentioned above?

**Comment by brianwest** [comment]
I see what you mean.  The required modules need to be in the PSModulePath and then the New-GuestConfigurationPackage cmdlet will be able to include them in the configuration package artifact:  https://learn.microsoft.com/en-us/azure/governance/machine-configuration/how-to/develop-custom-package/2-create-package#create-a-configuration-package-artifact.  That should do the trick.  Thank you!

**Comment by haagha** [comment]
Closing this as this seems to be resolved. Thanks!
