### ISSUE TITLE
AzureRM.ServerManagement - all but one cmdlet is missing an example

### ISSUE THREAD

**Issue by TaraMeyer** [Azure/azure-powershell#2459]
These are the cmdlets that are missing examples in the help.xml for Microsoft.Azure.Commands.ServerManagement.dll :

Get-AzureRmServerManagementNode

Get-AzureRmServerManagementSession

Install-AzureRmServerManagmentGatewayProfile

Invoke-AzureRmServerManagementPowerShellCommand

New-AzureRmServerManagementGateway

New-AzureRmServerManagementNode

New-AzureRmServerManagementSession

Remove-AzureRmServerManagementGateway

Remove-AzureRmServerManagementNode

Remove-AzureRmServerManagementSession

Reset-AzureRmServerManagementGatewayProfile

Save-AzureRmServerManagementGatewayProfile

Can someone please provide examples and confirm once completed?

Thanks!

Tara

**Comment by markcowl** [comment]
@fearthecowboy Can we auickly add some examples?

**Comment by TaraMeyer** [comment]
@fearthecowboy - any update on this item?  Will the new examples be included in the latest release candidate on 7/11?

**Comment by cormacpayne** [comment]
Markdown help for the ServerManagement cmdlets can currently be found [here](https://github.com/Azure/azure-powershell/tree/dev/src/ResourceManager/ServerManagement/Commands.ServerManagement/help). We have an action item to get rid of the `dll-Help.xml` file from each RP and generate the help from the markdown help during the build stage. When this change goes into effect, there will be help provided for the given cmdlets.

**Comment by maddieclayton** [comment]
Closed, as ServerManagement is being removed.
