### ISSUE TITLE
Breaking changes / backward compatibility strategy

### ISSUE THREAD

**Issue by avishnyakov** [Azure/azure-powershell#2460]
Hey guys, 

With every new Azure PowerShell release, what is the strategy around backward compatibility and breaking changes?

It can be noticed that some releases have undocumented breaking changes, new required parameters, changed return types. Having reasonable amount of  PowerShell scripts, say 10 000+ lines, depending on Azure PowerShell which randomly breaks stuff isn't a great experience.

So what's the story around breaking changes / backward compatibility?

**Comment by markcowl** [comment]
@avishnyakov The official story is that breaking changes should result in a major version change, and should be preceded by a deprectation warning for at least one prior release.

The actual story is that we do not have tools in place to enforce this, but we have issues in this sprint to begin addressing the disparity between official and actual handling.  You can find these issues here:
#2390 #2391 

Note that you can find a draft of our definition of breaking changes here:  https://github.com/markcowl/azure-powershell/blob/doc1/documentation/design.md#modules-and-versioning 

Please feel free to comment.

**Comment by ckarras** [comment]
I reviewed the draft at https://github.com/markcowl/azure-powershell/blob/doc1/documentation/design.md#modules-and-versioning. There is one thing missing for the Breaking Change Notification: it's not enough to provide advance notification by at least one release. An alternative to the deprecated pattern must also be available at least one major version in advance. (The deprecated pattern and new pattern must coexist during a transition period). This would allow us to prepare for changes so that we can upgrade Azure PowerShell with confidence that our scripts will still work, instead of delaying updates because we know we'll have several scripts to fix.

**Comment by markcowl** [comment]
@ckarras I'm not sure what you mean in your secodn paragrpah.  The intention is that deprecation warnings are provided at least one release in advance of removing the deprecated parameters/properties/etc.  This also means that the major version will incrmenet at the same time as thos properties are actually removed / changed, on release later. 

To be concrete:  
In version 2.2.0 We ship a release with no deprecations or breaking changes
In version 2.3.0, We add a deprecation warning for a parameter that will be removed.  No breaking changes (and also, some new cmdlets, as the version implies)
At a later date, the deprecation warning will be removed, the breaking changes will actually occur, and the version becomes 3.0

Make sense?

**Comment by avishnyakov** [comment]
Whatever the way to communicate back the breaking changes will be, it better be there.
Guess we barely have a choice so pretty happy with anything you'll have to improve that bit.

**Comment by ckarras** [comment]
@markcowl Yes that's what I meant by the distinction between "release" and "major version".

However, it would also be important to consider my first paragraph to ensure we don't get in a situation where we're stuck with a version: we were informed there would be breaking changes, but never had a chance to start updating our scripts before the new major version with breaking changes was released.

Reusing your example, this would mean:

  In version 2.2.0 Ship a release with no deprecations or breaking changes

 In version 2.3.0, Add a deprecation warning for a parameter that will be removed. No breaking changes (and also, some new cmdlets, as the version implies). **Also, alternatives for the parameter that will be removed are included**. 

 At a later date, the deprecation warning will be removed, the breaking changes will actually occur, and the version becomes 3.0

This way, we can update to version 2.3.0 with confidence nothing will break, and progressively take in consideration any warnings we see for transitioning to the new parameters. Then, once all deprecation warnings have been resolved, we can update with confidence to version 3.0.

Another possible approach would be to allow multiple versions of Azure PowerShell to coexist, and allow specifying which version we want to use at each execution. This would be a similar approach to the underlying Azure APIs, that allow specifying a version date in API calls.

**Comment by cormacpayne** [comment]
We now have `upcoming-breaking-change.md` files per RP to warn of upcoming changes for cmdlets within the given RP, as well as release migration guides detailing the breaking changes per release, as well as the changes that need to be made to the changed cmdlets.

We have also introduced the breaking change tool as a part of our Static Analysis to fail the CI whenever a PR contains a breaking change.

@avishnyakov @ckarras  @markcowl I'm going to close this issue as it seems we have resolved it with the steps above. Please feel free to reopen this issue if there is anything that is ambiguous or that we need to change about our breaking change guidelines.
