### ISSUE TITLE
Add-AzureRmAccount does not work with Windows Integrated Authentication

### ISSUE THREAD

**Issue by MichaelGrafnetter** [Azure/azure-powershell#2461]
When using a federated identity to log into Azure using PowerShell, only password-based authentication is supported on federation servers. This is a problem in environments, where only certificate-based authentication is allowed.

The problem lies in this parameter, which is always added by login.microsoftonline.com to the ADFS redirection URL, when authenticating from PowerShell:
wauth=http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/password

When logging in through other applications (Azure Portal web interface, Visual Studion,...) from the same computer, the integrated windows authentication works seamlessly.

Do you have any suggestions regarding this issue? Thx.

**Comment by markcowl** [comment]
@MichaelGrafnetter What are the parameters you are passing to Add-AzureRMAccount when you see this?

It is possible to define an environment that sets ADFSAuthentication, but this should only impact the authority validation for the STS, and not the means for authentication.  PowerShell does support using certificates and devices for authentication with Azure on many corporate networks, but I am not an expert on how federation is managed.  We can loop experts in once we have some details of the scenario.

**Comment by MichaelGrafnetter** [comment]
Thx for response, @markcowl . I was running Add-AzureRMAccount without any parameters. I have encountered this behavior in 2 different environments:
1. In our environment, when I am logged onto a computer using a domain account, our ADFS shows me the username/password screen instead of doing single sign-on.
2. In a customer's environment, the situation is even worse, as password-based authentication is disabled on ADFS in favor of kerberos/certificate-based authentication, so after a few redirects, PowerShell throws an exception with HTTP error 404. This info is then found in ADFS log:

> The Federation Service could not satisfy a token request because the accompanying credentials do not meet the authentication type requirement of 'http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/password' for the relying party 'urn:federation:MicrosoftOnline'. 
Authentication type: http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows 
Desired authentication type(s): http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/password 
Relying party: urn:federation:MicrosoftOnline 
This request failed.

Again, I have only seen this problem when logging in from PowerShell. Everything works seamlessly when authenticating against federated accounts from other applications.

**Comment by markcowl** [comment]
@MichaelGrafnetter I see, so the ask is about automatically using the credentials of the logged in user without additional inputs, is that correct?

How do such users use alternate accounts for login to Azure, through the portal, for example?  I could imagine adding a parameter set to allow integrated authentication, but I would hesitate to make this the default behavior.

For now, the second case causes me much more concern.  The dialog that is presented is entirely under the control of the STS.  Is it possible that the STS dialog is misconfigured in this case?   For example, in our STS, while a username/password dialog does appear, when I type in my account Id, I am redirected to our STS authentication dialog which does not accept passwords either, and authentication has no issues. Can you execute Add-AzureRMAccount in the customer context after setting ```$DebugPreference="Continue"``` and proceed with authentication?  This will provide ADAL traces which will give some more detailed information on the progress of federated authentication.

**Comment by MichaelGrafnetter** [comment]
@markcowl I do not mind having to type the username, but I do not want to type the password for federated accounts (and ADFS servers of one customer of mine even require certificate/kerberos-based authentication).
I think that the user experience in PowerShell should be the same as when authenticating through the portal: Being redirected to login.microsoftonline.com, typing the username there and then being redirected to the company-specific federation servers.
The only change I am actually requesting is for the login.microsoftonline.com not to add the "authenticationmethod=password" URL parameter when redirecting the client to ADFS. This parameter appears in URL only when authenticating from PowerShell, but it is not present when logging into the Azure Portal using a web browser.

**Comment by markcowl** [comment]
@MichaelGrafnetter The behavior you describe is what I see when logging in to our corporate STS, and is the bahvior of any STS that requires MFA.  

I suspect this may be an issue with STS configuration rather than PowerShell.  What version fo Azure PowerShell are you using?  Can you include ADAL traces by executing ```Add-AzureRmAccount``` with ```$DebugPreference="Continue"``` set?

**Comment by MichaelGrafnetter** [comment]
thx @markcowl for you response. Here is the log:
[adal_log.txt](https://github.com/Azure/azure-powershell/files/408846/adal_log.txt)

Well, the only difference is that when logging in through Internet Explorer, Windows Integrated Authentication against ADFS works, but it does not work through PowerShell, where I am explicitly asked for password by ADFS. It is caused by login.microsoftonline.com redirecting me to ADFS endpoint authenticationmethod/password in this case, as seen in the log.

**Comment by markcowl** [comment]
@MichaelGrafnetter Looking at the log, it appears that your login is successful (no subscriptions were returned, however), but that you were asked for a password and you would prefer not being asked, is that correct, or are you getting an Unauthorized somewhere as well?

AFAIK, the redirect URI comes from your STS configuration, as the redirect URI for other authentication sequences do not contains this.  Will talk to the ADAL experts about whether we have any cotnrol over the redirect URI when redirecting to your ADFS authentication endpoint.

**Comment by MichaelGrafnetter** [comment]
@markcowl You are correct. I would prefer not to be asked for password, as we also have a customer with password authentication disabled in favor of smartcards. This customer cannot access Azure using PowerShell. Thx.

**Comment by markcowl** [comment]
@MichaelGrafnetter Again, though, for your customer, the STS configuration should dictate that smaart cards are required, and the STS login should require this.  The customer issue seems like an STS configuration issue, and we would need to get ADAL logs for this case to determine where the issue lies.

**Comment by lpassig** [comment]
@markcowl @MichaelGrafnetter As a workaround you could authenticate against Azure AD respectively AD FS like this: 

$secpasswd = ConvertTo-SecureString 'PASSWORD' -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential ('lennart.passig@customer.com', $secpasswd)

Login-AzureRmAccount -Credential $mycreds 

This automatically logs you in without additional Popups.

**Comment by markcowl** [comment]
@lpassig True, but it doesn't work in the MFA case, and only works for work or school accounts

**Comment by markcowl** [comment]
@MichaelGrafnetter Closing for lack of additions.  What we can do to provide this functionality is allow setting propmpt behavior (always prompt versus auto) in the parameters to ```Add-AzureRmAccount```.  Added issue #3091 to track this.

Closing for now, if you encounter a case where login is actually failing, please gather the ADAL traces (```$DebugPreference="Continue"``` before logging in) and open a new issue or re-open this one
