### ISSUE TITLE
[Feature]: Request to add a PowerShell command to enable auto grow for Azure Postgres-Flexible server just like we have for Azure Database for PostgreSQL - Single Server - https://learn.microsoft.com/en-us/azure/postgresql/single-server/how-to-auto-grow-storage-powershell

### ISSUE THREAD

**Issue by JyothiSindhuN** [Azure/azure-powershell#24659]
### Description of the new feature

We have enable-autogrow powershell command available for Azure Database for PostgreSQL - Single Server - https://learn.microsoft.com/en-us/azure/postgresql/single-server/how-to-auto-grow-storage-powershell. 

Request to add a similar PowerShell command to enable auto grow for Azure Postgres-Flexible server.

### Proposed implementation details (optional)

This is as per customer request as they specifically want it via PS just like we have it for Single server as they
don't want to do it manually for each customer and there is huge no from their Management. So, they want it using automation and for their coming customers as well.

**Comment by nachoalonsoportillo** [comment]
@JyothiSindhuN While this functionality is not made available through the `New-AzPostgreSqlFlexibleServer` and `Update-AzPostgreSqlFlexibleServer` cmdlets in the `Az.PostgreSql` module, please leverage `Invoke-AzRestMethod` to hit the Server endpoint of any of the preview versions of the REST API that exposes `Storage.properties.autoGrow`. For example, you can use [2024-03-01-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/2024-03-01-preview/FlexibleServers.json).

**Comment by gbowerman** [comment]
@kabharati FYI
