### ISSUE TITLE
fruty.girl2011@hotmail.com

### ISSUE THREAD

**Issue by ZoozAlmalki** [Azure/azure-powershell#24669]
### Type of issue

Code doesn't work

### Feedback

لا يمكن التوثيق``

### Page URL

https://learn.microsoft.com/ar-sa/powershell/module/az.resources/get-aztag?view=azps-11.5.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/help/Get-AzTag.md

### Author

@mikefrobbins

### Document Id

b4cb5132-630d-bbe7-b080-be8dfdb5fe93

**Comment by isra-fel** [comment]
Closing as unrelated.
