### ISSUE TITLE
Get-AzureServiceDiagnosticsExtension output empty

### ISSUE THREAD

**Issue by c4rlosmarin** [Azure/azure-powershell#2470]
Not getting any output after executing "Get-AzureServiceDiagnosticsExtension -ServiceName azurecloudservice001"

Here is the output I get using the debug parameter:
[output.txt](https://github.com/Azure/azure-powershell/files/320921/output.txt)

Best regards.

**Comment by markcowl** [comment]
@singhkay Can you take a look?

**Comment by c4rlosmarin** [comment]
Yep, it's now fixed. Thanks!

Best regards.
