### ISSUE TITLE
New-AzureRmKeyVault prompts for Azure credentials

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2471]
The `New-AzureRmKeyVault` command prompts me for credentials to authenticate to Azure when I've already authenticated.

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by BredStik** [comment]
We also noticed that any KeyVault cmdlets triggers a authentication window that flickers on the first call after already being authenticated.  However, it completely fails when running the same command in a non-interactive execution with the following error:

System.ArgumentException: Your Azure credentials have not been set up or have expired, please run Login-AzureRmAccount to set up your Azure credentials. ---> Microsoft.Azure.Commands.Common.Authentication.AadAuthenticationFailedException: Showing a modal dialog box or form when the application is not running in UserInteractive mode is not a valid operation. Specify the ServiceNotification or DefaultDesktopOnly style to display a notification from a service application. ---> System.InvalidOperationException: Showing a modal dialog box or form when the application is not running in UserInteractive mode is not a valid operation. Specify the ServiceNotification or DefaultDesktopOnly style to display a notification from a service application.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)

Do you think it might be related?

**Comment by markcowl** [comment]
@BredStik How did you log in when you saw this issue?  Did you provide tenant/domain?

**Comment by BredStik** [comment]
@markcowl I used "Login-AzureRmAccount" with the -Credential parameter.  The TenantId parameter was not provided.

**Comment by markcowl** [comment]
@pomortaz, can you take a look?

**Comment by pomortaz** [comment]
@BredStik what version of the PowerShell do you use? This issue is resolved a month ago.

**Comment by BredStik** [comment]
I don't remember what version I was using at the time, but I'm currently using version 1.1.8 of AzureRM.KeyVault and version 1.0.9 of AzureRM.Profile and this issue seems to be resolved.
