### ISSUE TITLE
[Documentation]: Code review checklist

### ISSUE THREAD

**Issue by kirthik** [Azure/azure-powershell#2472]
Checklist that powershell team should look for while reviewing code
- Check if partner team is following cmdlet guidelines, 
- Do parameters make sense
- Is output type documented the right way
- Are parameter types are easily creatable
- Is SHOULD process used correctly
- Partner teams should sync up with SDK team during office hours for a design review before submitting pull requests for new cmdlets
- Check if help document is correct and clear
- Check if tests are added
- Check the correctness of metadata
- Check if the change description is added in changelog

**Comment by markcowl** [comment]
Checklist is here: https://github.com/Azure/adx-documentation-pr/blob/master/clis/powershell/prstandard.md
