### ISSUE TITLE
Add UnitTest for Import- and Export- cmdlet of AzureRM.MachineLearning

### ISSUE THREAD

**Issue by NonStatic2014** [Azure/azure-powershell#2474]
Add UnitTest for Import- and Export- cmdlet of AzureRM.MachineLearning to cover the relative support of these commands.

**Comment by cormacpayne** [comment]
@NonStatic2014 Hey Klein, did this issue get fixed in the latest release?

**Comment by NonStatic2014** [comment]
This is a request from Mark. Chatted with Mark before last release and we thought we are good and not need the UT.
