### ISSUE TITLE
Azure Automation - Get-AzureRmResourceGroup : Run Login-AzureRmAccount to login.

### ISSUE THREAD

**Issue by pklanka** [Azure/azure-powershell#2476]
This problem has been represented a number of times in this GitHub, however I believe this is a unique invocation. The sample code snippet leading to this is below - Request you to kindly fix this asap. This happens only in the Azure automation.
```

$connectionName = "Contoso Connection Group"
$servicePrincipalConnection = Get-AutomationConnection -Name $connectionName         

"Logging in to Azure..."
Add-AzureRmAccount -ServicePrincipal -TenantId $servicePrincipalConnection.TenantId -ApplicationId $servicePrincipalConnection.ApplicationId -CertificateThumbprint $servicePrincipalConnection.CertificateThumbprint
Get-AzureRmContext # This command executes succesfully
		
Get-AzureRmResourceGroup # This command fails with error within title
```

Followed guidance here - https://azure.microsoft.com/en-us/documentation/articles/automation-sec-configure-azure-runas-account/

**Comment by pklanka** [comment]
Was able to resolve the issue. The right modules have to be imported as an Automation asset for the AzureRM scripts to work. Not sure why is Azure RM is not by default a global powershell module. It would definitely help. For the benefit of others the list of modules I had to import as an asset were - 

1. AzureRM.profile
2. AzureRM.resources

Need to update the documentation so that users know.

**Comment by markcowl** [comment]
@pklanka I believe this is aready documeted in azure automation.  If you look at the module versions in AzureRM, this will give you a complete list for a release.
