### ISSUE TITLE
ClientAssertionCredential authentication failed: AADSTS50166 in Connect-AzAccount

### ISSUE THREAD

**Issue by nosalan** [Azure/azure-powershell#24777]
### Description

Our pipeline using ` AzurePowerShell@5` stopped working today due to the following error:
```
Connect-AzAccount: /home/vsts/work/_tasks/AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62/5.238.11/InitializeAz.ps1:111
Line |
 111 |      $null = Connect-AzAccount -ServicePrincipal -Tenant $endpointObje …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | ClientAssertionCredential authentication failed: AADSTS50166: Request to
     | External OIDC endpoint failed. Trace ID:
     | c7177633-5170-479e-9d18-7f55f1074700 Correlation ID:
     | <REDACTED> Timestamp: 2024-05-01 05:44:24Z
     | Could not find tenant id for provided tenant domain
     | '<REDACTED>'.
```
 The pipeline is running on Microsoft hosted Azure DevOps agents using Workload Identity Federation.

### Issue script & Debug output

```PowerShell
Current agent version: '3.238.0'
Current image version: '20240422.1.0'
```

### Environment data

```PowerShell
AzurePowerShell (5.238.11)
```

### Module versions

```PowerShell
N/A
```

**Comment by AzureStackNerd** [comment]
Have the same issue since this morning.

**Comment by Eypone** [comment]
I also have the same issue since this morning.

**Comment by makop90** [comment]
I have same issue. Anyone tried using other version of AzurePowerShell ?

**Comment by nosalan** [comment]
this is probably related to: https://status.dev.azure.com/_event/499193080

![image](https://github.com/Azure/azure-powershell/assets/2273250/39180623-9a57-4bc0-a5b1-7dafecbb03b0)

**Comment by patrick11994** [comment]
From [the incident status page](https://status.dev.azure.com/_event/499193080):
> ✅ The issue is now fully mitigated. Our engineers will be investigating this further to learn from and reduce the risk of potential recurrences. We apologize for the impact this had on our customers.

The issue is resolved for me. My pipelines are running again.
