### ISSUE TITLE
Connect-AzAccount: ClientCertificateCredential fails when used with other tenants since October 2022

### ISSUE THREAD

**Issue by Jeff-Jerousek** [Azure/azure-powershell#24780]
@Makzemann Agreed, I've had to downgrade several modules to maintain functionality. It seems the bug was introduced around October 2022, so everything released before then continues to work.

_Originally posted by @Jeff-Jerousek in https://github.com/Azure/azure-powershell/issues/22480#issuecomment-2088618196_

**Comment by isra-fel** [comment]
I believe the following conversation in the original thread may not be the same as as the original issue, as it's more related to resolving domain name rather than storing certificate. Jeff, could you share the debug log, powershell version, module version, script to help us identify the issue?
