### ISSUE TITLE
0.8.14 :: -ApiVersion parameter should be non-mandatory

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#248]
# Background

In the issue linked to below, I ran into an issue where `Get-AzureResource` was failing, because I had no clue which API version to submit as part of the request. Each Resource Type, in each Resource Provider, in the Azure Resource Manager REST API has a unique set of supported API versions.

https://github.com/Azure/azure-powershell/issues/223

The other `*-AzureResource` commands are affected by the same issue. To see a list of all affected commands, use the following code snippet:

```
PS C:\> Switch-AzureMode -Name AzureResourceManager;
PS C:\> Get-Command -Module AzureResourceManager -ParameterName ApiVersion | Format-Table -AutoSize;

CommandType Name                 Version Source
----------- ----                 ------- ------
Cmdlet      Get-AzureResource    0.8.14  AzureResourceManager
Cmdlet      New-AzureResource    0.8.14  AzureResourceManager
Cmdlet      Remove-AzureResource 0.8.14  AzureResourceManager
Cmdlet      Set-AzureResource    0.8.14  AzureResourceManager
```

# Proposed Solution

The Azure Resource Manager (ARM) REST API offers a "*List All Resource Providers*" method, which enumerates all of the Resource Providers, Resource Types, and each type's supported API versions as a single, large JSON document. This information can be used dynamically populate the `-ApiVersion` parameter, if it is not specified by the end user.

1. The `-ApiVersion` parameter should be marked as non-mandatory
2. Any calls to the generic `Get/Set/*-AzureResource` PowerShell cmdlets should look up the latest API version, based on the value passed into the `-ResourceType` parameter, by the end user.
3. The `-ApiVersion` must remain configurable by end users, in the event it needs to be overridden

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
+1

**Comment by vivsriaus** [comment]
This is fixed with the latest azure powershell. Please install it and let us know if it works for you. Thank you.

**Comment by pcgeek86** [comment]
@vivsriaus Thank you -- appreciate this getting resolved.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
