### ISSUE TITLE
Set-AzureRmVMSourceImage missing parameter from example

### ISSUE THREAD

**Issue by iricigor** [Azure/azure-powershell#2481]
In example for the command **Set-AzureRmVMSourceImage** you can see parameter **ImageReference**, but actual parameter is not existing in list of parameters. 

Using modules AzureRM 1.5.0 and AzureRM.Compute 1.3.1

Steps to reproduce
1. `Get-help Set-AzureRmVMSourceImage  -Examples`
Take a look at example 2 and specifically its last line, it is using ImageReference
2. `(Get-Command Set-AzureRmVMSourceImage).parameters`
Parameter ImageReference is not there...

**Comment by markcowl** [comment]
@singhkay Can you take a look?

**Comment by singhkays** [comment]
@iricigor Thanks for the feedback. This method was deprecated with the GA API, I've removed the example.

**Comment by markcowl** [comment]
Fixed
