### ISSUE TITLE
[Feature]: Update Capabilities Property in PSResourceSku to be a Collection

### ISSUE THREAD

**Issue by aydeisen** [Azure/azure-powershell#24815]
### Description of the new feature

Is it possible to change the `Capabilities` property of [PSResourceSku](https://github.com/Azure/azure-powershell/blob/859d31db32a5e8fcba0c5cc19d0ec261949268a3/src/Compute/Compute/Generated/Models/PSResourceSku.cs) to be a collection instead of a list?  ResourceSkuCapabilities already returns as Key/Value, and it would make filtering and searching easier to be able to select items in `Capabilities` by Name, and not just by index

**Comment by isra-fel** [comment]
> ...already returns as Key/Value, and it would make filtering and searching easier to be able to select items in Capabilities by Name...

Based on this, I assume you'd like the type to be a Dictionary?

There are situations where List is more convenient than Dictionary and vice versa. I wouldn't change the type especially considering the breaking change, but I'll loop in the module owners.

**Comment by aydeisen** [comment]
> > ...already returns as Key/Value, and it would make filtering and searching easier to be able to select items in Capabilities by Name...
> 
> Based on this, I assume you'd like the type to be a Dictionary?
> 
> There are situations where List is more convenient than Dictionary and vice versa. I wouldn't change the type especially considering the breaking change, but I'll loop in the module owners.

Yes please.  I would very much prefer not to have to do something like this:

```powershell
Get-AzComputeResourceSku -Location eastus | Where-Object -Property ResourceType -EQ -Value 'virtualMachines' | Where-Object -FilterScript { ($_.Capabilities | Where-Object -Property Name -EQ -Value 'MemoryGB').Value -eq 16 } | Where-Object -FilterScript { ($_.Capabilities | Where-Object -Property Name -EQ -Value 'vCPUs').Value -gt 1 -and ($_.Capabilities | Where-Object -Property Name -EQ -Value 'vCPUs').Value -lt 5}
```

and be able to simplify it with something like this

```powershell
Get-AzComputeResourceSku -DefaultProfile $ctx -Location eastus | Where-Object -Property ResourceType -EQ -Value 'virtualMachines' | Where-Object -FilterScript { $_.Capabilities.Item('MemoryGB') -eq 16 } | Where-Object -FilterScript { $_.Capabilities.Item('vCPUs') -gt 1 -and $_.Capabilities.Item('vCPUs') -lt 5}
```

**Comment by TravisCragg-MSFT** [comment]
@aydeisen Thanks for the feedback! We are making significant updates to our SKU API which will give this functionality and more.
