### ISSUE TITLE
[Feature]:  New-AzVM does not support Adding existing SSH Key, only create a new one 

### ISSUE THREAD

**Issue by Nerigal** [Azure/azure-powershell#24858]
### Description of the new feature

Posting This as a Feature but in fact it's an issue because it is very handicapping compared to what az cli can do... 
In my situation, az cli is not available nor possible to use, only powershell 
And so we cant deploy linux machines with a pre defined admin user with an existing SSH public key using `New-AzVM`
This is strange because it seams to be possible to do so with VMSS `Set-AzVmssOsProfile` but not "standard" VMs 

az cli example https://learn.microsoft.com/en-us/azure/virtual-machines/linux/ssh-from-windows#create-a-vm-using-your-key

**Comment by Nerigal** [comment]
Finally could find that you can actually achieve to define or add an existing SSH public key to the "main user" at the creation of the virtual machine using `Add-AzVMSshPublicKey`  
i got REALLY lucky finding it... you really have to dig deep in the documentation and i actually found it by luck 
so maybe it would be good to advertise it better under the New-AzVm documentation 

This `Add-AzVMSshPublicKey`  goes along with 
`New-AzVMConfig`
`Set-AzVMOperatingSystem`
`Set-AzVMSourceImage`
`Set-AzVMOSDisk`
`Set-AzVMBootDiagnostic`
`Add-AzVMNetworkInterface`

**Comment by TravisCragg-MSFT** [comment]
@Nerigal  Thanks for the feedback, we will take this into consideration for future updates to PowerShell

**Comment by 1RedOne** [comment]
As of May 2026, this is still an issue :(
