### ISSUE TITLE
[Feature]: New-AzDiskConfig -PhysicalSectorSize parameter 

### ISSUE THREAD

**Issue by BespokeBusinessSoftware** [Azure/azure-powershell#24915]
### Description of the new feature

Currently Azure PowerShell doesnt provide the ability to specify the physical sector size as a parameter when creating a managed disk or restoring from snapshot. As v2 managed SSD and Ultra disks offer both 4 KiB and 512e support, we really need to be able to specify the physical sector size parameter via PowerShell.

**Comment by TravisCragg-MSFT** [comment]
@BespokeBusinessSoftware Thanks for the feedback! We are looking into this now.

**Comment by BespokeBusinessSoftware** [comment]
@TravisCragg-MSFT Thank you. Not sure how you guys prioritise requests but do you provide updates here?

**Comment by TravisCragg-MSFT** [comment]
@BespokeBusinessSoftware The one who will be providing updates on this is @ushnaarshadkhan. Ushna, can you provide an update here?

**Comment by ushnaarshadkhan** [comment]
Hello, thank you for your feedback. The parameter you will use to configure the sector size of the disk is [LogicalSectorSize](https://learn.microsoft.com/en-us/powershell/module/az.compute/new-azdiskconfig?view=azps-12.2.0#-logicalsectorsize).
