### ISSUE TITLE
Request for archived versions of azure powershell module docs

### ISSUE THREAD

**Issue by smithg6** [Azure/azure-powershell#24914]
### Type of issue

Missing information

### Feedback

We always strive to be on the latest version of the az modules for our code base, but as can sometimes happen, there are times where we fall behind and must use older major/minor versions until we can update. In this event, it would be very helpful to be able to access previous versions of the docs. (e.g. Updating the version from 11.6.1 in the url to 9.7.1 would get you to the previous version of the doc for troubleshooting) It seems like this functionality was removed in the last year or so and I'm curious if that could be reversed?

Is there a way to access these older doc versions that I'm unaware of? I've tried digging through the doc page commit history in github without success. It would be amazing if we could call out a release version and access a valid version of that document.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.resources/new-azresourcegroupdeployment?view=azps-11.6.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/help/New-AzResourceGroupDeployment.md

### Author

@mikefrobbins

### Document Id

9e02a064-75fc-ba78-61ff-a2675222c7cb

**Comment by mikefrobbins** [comment]
@smithg6 We maintain online documentation only for supported versions of the Az PowerShell module. However, version-specific documentation is included with each module. To view the documentation for a particular version locally, use the following command after importing the desired version of the Az PowerShell module:

```powershell
Import-Module -Name Az -RequiredVersion 9.7.1
help New-AzResourceGroupDeployment
```
