### ISSUE TITLE
Get-AzStorageFileContent gets 403 using SP when getting a file from azure storage account file share

### ISSUE THREAD

**Issue by whitecore-ge** [Azure/azure-powershell#24934]
xx

**Comment by blueww** [comment]
@whitecore-ge 

I don't see you detail comment for the issue.
However, please make sure your logon AAD account has been assigned a role with enough permssion to read Azure file.
You can find the details roles in https://learn.microsoft.com/en-us/azure/storage/files/storage-files-identity-ad-ds-assign-permissions?tabs=azure-portal#share-level-permissions-and-azure-rbac-roles
