### ISSUE TITLE
[Feature]: use another source for the HCIbox images

### ISSUE THREAD

**Issue by hemetz** [Azure/azure-powershell#24969]
### Description of the new feature

please provide another source to download the HCIBox images. The script deploys the environment ~25min, but the post-deployment precess requires more than 4 hours based on the extrem slow download speed for the HCIbox images: 
![image](https://github.com/Azure/azure-powershell/assets/12524870/0157322a-7120-4b83-b94f-791cf8974ddd)

**Comment by isra-fel** [comment]
Hi @hemetz  I'm not sure if your question is within the scope of Azure PowerShell. Could you share script, or which Az cmdlet and module do you want to improve?

**Comment by hemetz** [comment]
Hi @isra-fel,
I´m sorry - this should be a feature request for the Azure Arc Jumpstart project.
