### ISSUE TITLE
Azure Automation - Get-AzureRmResourceGroup

### ISSUE THREAD

**Issue by nexxus916** [Azure/azure-powershell#2498]
Having similar issue as #2476
The following only happens with vs 1.0.9 (not with 1.0.3) and only when run in Azure (when I run it locally with the same version 1.0.9 it works fine)
## this runs fine
$Conn = Get-AutomationConnection -Name AzureRunAsConnection 
Add-AzureRMAccount -ServicePrincipal -Tenant $Conn.TenantID -ApplicationId $Conn.ApplicationID -CertificateThumbprint $Conn.CertificateThumbprint
Get-AzureRmContext
## then this throws error
get-azurermresourcegroup ## get-azurermresourcegroup : Run Login-AzureRmAccount to login.

I have AzureRM.Profile and AzureRM.Resource loaded as assets.

![capture](https://cloud.githubusercontent.com/assets/20098093/16283848/2c8965e4-3894-11e6-81cc-65b34bd7d917.PNG)

**Comment by markcowl** [comment]
@nexxus916 You need to match the version of AzureRM.Profile *exactly* with the version specified in the resource manifest.

**Comment by nexxus916** [comment]
I'll check on it today.  I am restricted to the 1.0.9 version of AzureRM.profile because I need the AzureRM.Networking module and it specifically requires AzureRM.profile >= 1.0.9

**Comment by markcowl** [comment]
@nexxus916 Yeah, unfortiunately, we cannot place specific version constraints on modules without breaking compatibility with PowerShell 3 and 4

**Comment by markcowl** [comment]
Closing as duplicate of #2392, which will fix this issue
