### ISSUE TITLE
ServiceClientTracingInterceptor consumes lots of memory for cmdlets with large response bodies

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-powershell#2499]
I am making changes to the ADLS export cmdlet to use parallel threads for downloading data. This is resulting in a massive spike in memory usage from the ServiceClientTracingInterceptor. For a 10GB file it consumes ~8GB of memory. This appears to be a missed optimization when ServiceClientTracingInterceptor was fixed for large request bodies. That same change should also be applied for cmdlets that result in a large number of responses with large bodies.

**Comment by markcowl** [comment]
I believe this was fixed for DataLak, please reopen if not.

**Comment by begoldsm** [comment]
@markcowl this is correct. Now there is just a performance issue with thread contention when the tracing interceptor is active, even if nothing is being output. I will open a separate issue for that.

**Comment by begoldsm** [comment]
@markcowl https://github.com/Azure/azure-powershell/issues/3970 opened.
