### ISSUE TITLE
Announcements displayed even in non-interactive session and all new features disabled

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-powershell#25003]
### Description

announcement is displayed even in non interactive session
![image](https://github.com/Azure/azure-powershell/assets/11890856/bcbccd69-4056-4552-bc2b-465799ecede8)

```powershell
$azConfigParameters = @{
    Scope                        = 'CurrentUser'
    DisplayBreakingChangeWarning = $false
    CheckForUpgrade              = $false
    DisplaySurveyMessage         = $false
    EnableLoginByWam             = $false
    LoginExperienceV2            = 'Off'
}
$null = Update-AzConfig @azConfigParameters
```

### Issue script & Debug output

```PowerShell
n/a
```

### Environment data

```PowerShell
n/a
```

### Module versions

```PowerShell
az.accounts 3.0.0
```

### Error output

```PowerShell
n/a
```

**Comment by msJinLei** [comment]
@slavizh announcement is a general information. We don't display it at conditions of different authentication methods.

**Comment by slavizh** [comment]
@msJinLei I have logged issue because it is displayed in our Azure Pipeline where we use access token authentication(non interactive) so you have another bug there.

**Comment by Jaykul** [comment]
Yeah. This announcement should **NOT** be cluttering up our pipeline output

**Comment by msJinLei** [comment]
@slavizh @Jaykul 
Please refer to workaround here https://github.com/Azure/azure-powershell/issues/24980#issuecomment-2132502101

**Comment by slavizh** [comment]
@msJinLei I will wait to be fixed as otherwise I have to update our pipelines twice, once now with the workaround and again when the fix is released.

**Comment by msJinLei** [comment]
@BethanyZhou correct me, if anything wrong. 

@slavizh  We are not going to remove the information stream and Connect-AzAccount in the next version. Could you share with us you usage and how you break by the new log streams so that we can recommend the best practice to you and avoid potential break in the feature.

**Comment by slavizh** [comment]
@msJinLei the announcement is useless for folks running PowerShell in pipelines. You know that you do not serve only customers that use the Az PowerShell module interactively? If you are not removing make another az config variable that removes displaying announcements just like there is such for warnings. I cannot believe that there is no understanding that customers who run non-interactive logins does not need these things. I would also make the case that such customers you should treat better as we run these things for production workloads not to just play around.

**Comment by msJinLei** [comment]
> @msJinLei the announcement is useless for folks running PowerShell in pipelines. You know that you do not serve only customers that use the Az PowerShell module interactively? If you are not removing make another az config variable that removes displaying announcements just like there is such for warnings. I cannot believe that there is no understanding that customers who run non-interactive logins does not need these things. I would also make the case that such customers you should treat better as we run these things for production workloads not to just play around.

Thank you for your feedback. We are collecting the feedback from you, the customers to decide what to do next.

**Comment by msJinLei** [comment]
@isra-fel @BethanyZhou could you follow up the issue? Thanks

**Comment by Alex-wdy** [comment]
@slavizh  Thank you for your feedback, because announcement is for all customers, including interactive and non-interactive methods, and non-interactive methods will be displayed in the log. So it also has some meaning for non-interactive customers.
I have another question, the display of announcement should not affect the execution of your existing pipeline. Is there any impact? Or will you do analysis based on the log? Can you describe the scenario that effected you?

If you want to hide announcement information, you can add **Connect-AzAccount -InformationAction Ignore** in the script.

We are also collecting more user feedback and then doing evaluation.

**Comment by slavizh** [comment]
@Alex-wdy affects it in a way that the end users who use the pipeline sees this message and does not know what it means. It is useless and confusing message for them. I do not think that the Information stream is meant for announcements. It is more about information related to the execution of the command not information that is for blog post or release notes. Would you find it suitable message when you execute command it displays release notes? I get the feeling that you are trying to convince me that this is something useful and I should embrace. Just tell me straight if you will fix it (remove it) or not? I would rather have an honest answer.

**Comment by BethanyZhou** [comment]
Thanks @slavizh for reporting this issue. Also thanks our PM @Alex-wdy for helping respond and the workaround.

We were just aware that many customers in non-interactive session will consume information messages wrote by command as output directly. The general usage is capturing the returned object by command and continue next step. 

We had a discussion today and **decide to limit the information message like announcements in interactive sessions only**.

**Comment by slavizh** [comment]
@BethanyZhou thank you for understanding!

**Comment by Jaykul** [comment]
Even using PowerShell interactively, the announcement is noisy and distracting. 

How many times do people need to see the announcement? Shouldn't it turn itself off after it displays? Surely nobody wants to see this message over and over every day. I thought the new thing you're announcing was an _optional_ feature, not a requirement that I **must** configure my preferred subscription...

**Comment by o-l-a-v** [comment]
Workaround `Connect-AzAccount -InformationAction Ignore` does not work if `-UseDeviceAuthentication`.

Please add a `Update-AzConfig` option to hide announcements.

**Comment by BethanyZhou** [comment]
Thanks for reporting. @Jaykul, @o-l-a-v. 

Could you explain your user scenarios if the announcements block you so that we could consider your feature request with higher priority?

**Comment by o-l-a-v** [comment]
@BethanyZhou 

See my feature request for a AzConfig option to disable announcements. Also:

* It provides no value to me with announcements in the terminal, I use other mediums to stay up to date. Others might like it. Let us choose where to read up on Azure.
* I try to keep the output of my scripts nice and tidy, also to make them easy to use for my non-PowerShell-savvy collegues that know nothing about the changes Az.Accounts v3.0.0 brought. The only output I'd like in a production ready script is the device auth code if the user is not already connected.
