### ISSUE TITLE
ParameterNameConflictsWithAlias

### ISSUE THREAD

**Issue by PriD98** [Azure/azure-powershell#25009]
### Type of issue

Other (describe below)

### Feedback

I am trying to run the following command: New-AzResourceGroupDeployment -ResourceGroupName "test" -TemplateFile "template.json" -TemplateParameterFile "parameters.json"

I have tried a number of different (previously working) template.json and parameters.json files. I keep getting the same error, ParameterNameConflictsWithAlias. I'm not sure how to resolve the error - I've tried removing the parameter from the commandline flags and specifying in the parameters.json file instead, I've tried renaming the deploymentName parameter in the deploymentTemplate.json file. I'm not sure what else to try. The same command and template/parameters files were working previously.

<img width="745" alt="Screenshot 2024-05-28 120300" src="https://github.com/Azure/azure-powershell/assets/144097403/cc88057e-90d4-4d2a-b214-038ff4134bd4">

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.resources/new-azresourcegroupdeployment?view=azps-12.0.0&viewFallbackFrom=azps-10.2.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/help/New-AzResourceGroupDeployment.md

### Author

@mikefrobbins

### Document Id

9e02a064-75fc-ba78-61ff-a2675222c7cb

**Comment by mikefrobbins** [comment]
@PriD98 This is a product issue instead of a documentation issue. I recommend [logging a bug report](https://github.com/Azure/azure-powershell/issues/new/choose) so that it can be triaged properly and routed to the appropriate team for the quickest response.
