### ISSUE TITLE
API Limits Exceeded error 

### ISSUE THREAD

**Issue by KrishIntMSFT** [Azure/azure-powershell#25034]
### Description

one of my customer facing error i.e Exceeded API limits when they are running PowerShell script (Azure VM Resizing), when it runs first time, giving "Exceeded API Limits" but they are stopping and re-running again it's working well but it's taking longer time. 

[Resize_Script_Limit_issue.zip](https://github.com/Azure/azure-powershell/files/15494033/Resize_Script_Limit_issue.zip)
Enclosed the script and Error screenshots in ZIP file format

### Issue script & Debug output

```PowerShell
one of my customer facing error i.e Exceeded API limits when they are running PowerShell script (Azure VM Resizing), when it runs first time, giving "Exceeded API Limits" but they are stopping and re-running again it's working well but it's taking longer time.
```

### Environment data

```PowerShell
one of my customer facing error i.e Exceeded API limits when they are running PowerShell script (Azure VM Resizing), when it runs first time, giving "Exceeded API Limits" but they are stopping and re-running again it's working well but it's taking longer time.
```

### Module versions

```PowerShell
one of my customer facing error i.e Exceeded API limits when they are running PowerShell script (Azure VM Resizing), when it runs first time, giving "Exceeded API Limits" but they are stopping and re-running again it's working well but it's taking longer time.
```

### Error output

```PowerShell
one of my customer facing error i.e Exceeded API limits when they are running PowerShell script (Azure VM Resizing), when it runs first time, giving "Exceeded API Limits" but they are stopping and re-running again it's working well but it's taking longer time.
```

**Comment by TravisCragg-MSFT** [comment]
@KrishIntMSFT This could be a limit hit by https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits. This does not seem to be an issue with the API, and I would contact support to investigate further. If you have any other questions, feel free to ping me via teams.
