### ISSUE TITLE
Name parameter is not required but the documentation states it is

### ISSUE THREAD

**Issue by the-blesss** [Azure/azure-powershell#25171]
### Type of issue

Other (describe below)

### Feedback

The first example shows that the name of the extension is not required when you get all extensions for a hybrid connected machine. Only ResourceGroupName and MachineName should show as required.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.connectedmachine/get-azconnectedmachineextension?view=azps-12.0.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/ConnectedMachine/ConnectedMachine/help/Get-AzConnectedMachineExtension.md

### Author

@mikefrobbins

### Document Id

88506707-47c2-edcf-459f-a63acb9bd132

**Comment by dolauli** [comment]
There are two parameter sets. The first parameter set is to list all the extensions under a machine, so extension name is not required. For the second, it will get a specific extension under a machine, so extension name is required.
