### ISSUE TITLE
Get-AzureStorageBlobCopyState -WaitForComplete leaves ProgressBar open

### ISSUE THREAD

**Issue by iricigor** [Azure/azure-powershell#2518]
When I am using command **Get-AzureStorageBlobCopyState** with **_-WaitForComplete_** switch, it is opening Progress Bar to show copy progress. Sometimes, progress bar is not closed after successful copy. This is leading to screen clutter and  memory leak.

Steps to reproduce:

``` PowerShell
for ($d=1;$d -lt 20;$d++) {
    $prefix = "UIData/$d"
    $blobs = Get-AzureStorageBlob -Container $ContainerName -Context $Context -Prefix $prefix
    $blobs | Start-AzureStorageBlobCopy -DestContainer $DestContainerName -DestContext $DestContext 
    $blobs.Name | % {Get-AzureStorageBlobCopyState  -Container $DestContainerName -Blob $_  -WaitForComplete | Out-Null}
    Write-Host "Finished copying $d"
}
```

**Comment by iricigor** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/15923171/16373158/32bef2a6-3c51-11e6-994a-47787d217af7.png)
Here is screenshot example. I am copying folder by folder, each folder containing approx. 50 blobs with total size about 20GB. I am waiting one folder to finish, before proceeding with next one. Script works fine, but number of progress bars is increasing. Also, application (PowerShell ISE) memory usage is increasing and eventually it becomes unresponsive. Seems like, progress bar is not closed (`Write-Progress -Completed`)

**Comment by iricigor** [comment]
As a workaround, I started using `$ProgressPreference = 'SilentlyContinue'` at the beginning of the script.

**Comment by markcowl** [comment]
@EmmaZhu Can you take  alook

**Comment by blueww** [comment]
Hi,

I have tried to repro the issue, but not repro by copy 19 * 200MB files for 20 times.
I run the scenario for 2 times and not see repro.

```
for ($d=1;$d -lt 20;$d++) {
    $prefix = "blockblob1/testfile"
    $blobs = Get-AzureStorageBlob -Container bigfile -Context $ctx -Prefix $prefix
    $blobs | Start-AzureStorageBlobCopy -DestContainer bigfile2 -DestContext $ctx2 -Force
    $blobs.Name | % {Get-AzureStorageBlobCopyState -context $ctx2 -Container bigfile2  -Blob $_  -WaitForComplete | Out-Null}
    Write-Host "Finished copying $d"
}
```

**Comment by pjolivon** [comment]
Hi guys,
I am facing the same issue here passing an array to Get-AzureStorageBlobCopyState -WaitForComplete . The first copies are marked as completed and successful but their progress-bars never disappear.
`
 #Do the copy of everything
        $BlobCpyAry = @() #Create array of objects
        foreach ($VHD in $AZRepoCustomVHDs)
        {
           $BlobCopy = Start-CopyAzureStorageBlob -Context $AZRepoStorageAccountContext -SrcContainer $AZRepoCustomVHDsContainer.Name -SrcBlob $VHD.Name -DestContext $AZStorageAccountContext -DestContainer $AZTemplatesContainer.Name -DestBlob $VHD.Name
           $BlobCpyAry += $BlobCopy
        }

        #Display VHD Transfers Progress
           $BlobCpyAry | Get-AzureStorageBlobCopyState -WaitForComplete 
`
![staleprogressbar](https://cloud.githubusercontent.com/assets/14009702/19465288/c64ad4fe-94b7-11e6-83ff-6152da14d0ec.PNG)

**Comment by blueww** [comment]
I can't repro the progress bar hang issue. But if you still block on it, can you try to disable progress indicators in Power Shell by following command before you run the copy:
`$ProgressPreference="SilentlyContinue"`

**Comment by cormacpayne** [comment]
Closing this issue due to a lack of activity in the last few months.

@iricigor @pjolivon please feel free to reopen this issue if you have any other questions.
