### ISSUE TITLE
StorageAccountKey null or empty

### ISSUE THREAD

**Issue by marktayl1** [Azure/azure-powershell#2523]
I am getting the following starting of a cascade of errors when I try to deploy the solution to the cloud...

New-AzureStorageContext : Cannot validate argument on parameter 'StorageAccountKey'. The argument is null or empty.
Provide an argument that is not null or empty, and then try the command again.
At C:\Src\JabilTemp\azure-iot-remote-monitoring-master\azure-iot-remote-monitoring-master\Common\Deployment\DeploymentL
ib.ps1:391 char:99

I don't have a ton of experience with ARM.  Has anyone else seen this?  I had done a successful local deployment, not sure if that could have anything to do with it.

**Comment by markcowl** [comment]
@marktayl1 Can you provide some details about what cmdlets you are running?  The Debug output would also be useful in figuring oput the issue

**Comment by marktayl1** [comment]
I ran into two issues, the first is just not documented as one of the necessary steps (at least it was necessary in my case), and that was to generate the zip package at the expected location.  
The second was a problem in DeploymentLib.ps1... 

1. Add the zip package for the website to the appropriate directory.
2. Right click the web project and choose “publish”
3. In the resulting dialog, choose “Custom”
4. Give the profile a name (can be anything)
5. In the resulting dialog choose “Web Deploy Package”
6. Fill in the destination.  For debug, this would be “azure-iot-remote-monitoring-master\DeviceAdministration\Web\obj\Debug\Package”
7. You can leave site name blank and hit “next”
8. Choose your configuration type, debug or release and hit next
9. Make sure the profile you just created is selected and choose “publish”

 Change the code in DeploymentLib.ps1 on line 390 Col 134 from “.key1” to “.Value[0]”

**Comment by markcowl** [comment]
Closing this due to age.  If this is still an issue, please open a new issue, including the cmdlet invocation and error or unexpected result and we will take a look.
