### ISSUE TITLE
Get-AzureServiceAvailableExtension -ExtensionName 'PaaSDiagnostics' downloads a blank file

### ISSUE THREAD

**Issue by GavinOsborn** [Azure/azure-powershell#253]
I've been following [this](http://azure.microsoft.com/en-us/documentation/articles/cloud-services-dotnet-diagnostics/#worker-role) guide to using the new Azure Diagnostics extension.

In step 4 I am asked to run the following command:
```
(Get-AzureServiceAvailableExtension -ExtensionName 'PaaSDiagnostics' -ProviderNamespace 'Microsoft.Azure.Diagnostics').PublicConfigurationSchema | Out-File -Encoding utf8 -FilePath 'WadConfig.xsd'
```

The command executes successfully but the xsd file that is created is blank.

I have the latest Azure Powershell version from the Web Platform Installer.

Please advise

**Comment by sbtron** [comment]
This is working now. There was an issue with the extension registration which was resulting in the powershell not returning the public schema. The extension registration has been updated so the powershell successfully returns the xsd.

Thanks
