### ISSUE TITLE
Login-AzureRmAccount / Add-AzureRmAccount "We can't sign you in" on Windows Server 2016 (CTP5)

### ISSUE THREAD

**Issue by asw** [Azure/azure-powershell#2531]
When I run Login-AzureRmAccount on a vanilla Windows Server 2016 (CTP5) install, whether on an Administrator account or not, I receive the following error in the authentication pop-up:

> We can't sign you in
> 
> Your browser is currently set to block cookies. You need to allow cookies to use this service.
> 
> Cookies are small text files stored on your computer that tell us when you're signed in. To learn how to allow cookies, check the online help in your web browser.

![screenshot from 2016-06-28 19-48-17](https://cloud.githubusercontent.com/assets/339629/16455492/81234342-3de2-11e6-9e49-a3292cb6b052.png)

I have tried playing around with the Edge and legacy Internet Explorer configuration but I can't tell which, if any, of these are affecting it. I understand this may not be a PowerShell issue per-se, but it would be helpful to have a workable default or some steps to work around it.

**Comment by markcowl** [comment]
@asw The necessary settings should be in internet explorer.

**Comment by markcowl** [comment]
@asw You might get more traction asking this issue here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet

**Comment by ljt91** [comment]
+1 - Also having this issue!

**Comment by ljt91** [comment]
Check this out, temporary fix - http://allthingscloud.info/we-cant-sign-you-in-how-to-fix-it-azure-login/

**Comment by asw101** [comment]
@ljt91 Thanks for sharing that! I'd previously tried dropping the "Internet" security level and for some reason it didn't work, so I wasn't sure if it was IE or Edge related, or something else.

**Comment by markcowl** [comment]
Note that none of these are a "fix", the default security settings are preventing you from using features necessary for interactive login. Turning off Enhanced Security Configuration should also work, if you are just testing.  Closing, as this is not a PowerShell issue
