### ISSUE TITLE
C# 6.0 projects fail on compilation using Publish-AzureWebsiteProject

### ISSUE THREAD

**Issue by bastienJS** [Azure/azure-powershell#2532]
I used the Publish-AzureWebsiteProject Cmdlet and it worked. Then some colleague used some c# 6.0 properties in the project and since then the Publish-AzureWebsiteProject does not compile anymore.

We have .NET 4.6.1 installed and had never problems building any C# 6.0 projects withint VS 2015.

What do we wrong?

**Comment by markcowl** [comment]
@akurmi can you take a look?

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
