### ISSUE TITLE
Unable to enable System-Assign Managed Identity on VMSS

### ISSUE THREAD

**Issue by dretta** [Azure/azure-powershell#25378]
### Description

I am not able to enable the System-Assigned Managed Identity for Virtual Machine Scaling Sets. I have made a new VMSS (making me the owner of it thus having all permissions needed) and tried to enable the System-Assigned Managed Identity through the Portal and Azure PowerShell but both attempts fail.

This does not apply to the instances, individually enabling each VM still works.

![f2815316-c818-4b6e-82ca-a7c247071df9](https://github.com/Azure/azure-powershell/assets/2917655/6e39ecf2-6f8b-413c-9a16-0551802497db)
![96d76102-e544-4338-be05-1b1689fc062f](https://github.com/Azure/azure-powershell/assets/2917655/65446848-a074-4ebd-942e-7faddbf56b6e)

### Issue script & Debug output

```PowerShell
PS C:\Users\danielretta> Update-AzVmss -ResourceGroupName myResourceGroup -Name myScaleSet -IdentityType "SystemAssigned"
```

### Environment data

```PowerShell
PS C:\Users\danielretta> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.3672
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.3672
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS C:\Users\danielretta> Get-Module Az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.0.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear...
Script     8.0.0      Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnatten...
Script     7.1.0      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDeny...
```

### Error output

```PowerShell
Update-AzVmss : The value 'SystemAssigned' of parameter 'identity' is not allowed. Allowed values are: UserAssigned,
None.
ErrorCode: InvalidParameter
ErrorMessage: The value 'SystemAssigned' of parameter 'identity' is not allowed. Allowed values are: UserAssigned,
None.
ErrorTarget: identity
StatusCode: 400
ReasonPhrase:
OperationID : 39667a5d-5391-4680-aa57-e5c413a49de0
At line:1 char:1
+ Update-AzVmss -ResourceGroupName myResourceGroup -Name myScaleSet -Id ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Update-AzVmss], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.UpdateAzureRmVmss
```

**Comment by dretta** [comment]
Sorry, wrong repo.

**Comment by dretta** [comment]
Sorry, wrong repo. Closing.

**Comment by isra-fel** [comment]
Hi @dretta I'll loop in the developers of the Az.Compute module but if you are experiencing issues both on Azure Portal and with Azure PowerShell, it's recommended to contact Azure support for a quicker response.

**Comment by TravisCragg-MSFT** [comment]
@dretta Thanks for making this issue. Have you engaged with support, and are you still experiencing this issue?

**Comment by Kanik09** [comment]
@dretta , Have you been able to engage with support, and are you still experiencing this issue? 

Could you please also help us with the VMSS Orchestration mode for your VMSS? VMSS Flex only supports User managed identity at this time. [https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-orchestration-modes#basic-setup ](url)

@TravisCragg-MSFT FYI

**Comment by dretta** [comment]
I was not able to resolve this issue. I spoke to my team about this and they recommended that I move forward with an User-Assigned Managed Identity. I'm not sure what prevented me from making a System-Assigned Managed Identity but I will not be needing one now.
