### ISSUE TITLE
[LogicApp] - Remove hard-coded location from the test functions in scenario testing

### ISSUE THREAD

**Issue by pankajsn** [Azure/azure-powershell#2539]
To use the Get-location or get-provider cmdlets to determine an available location (it's fine to prefer any specific location if available). This makes it easier to maintain the tests, and to run them against different environments.

**Comment by cormacpayne** [comment]
@pankajsn Hey Pankaj, did this issue get fixed in the latest release?

**Comment by pankajsn** [comment]
@cormacpayne  this issue is not fixed in the latest release.

**Comment by markcowl** [comment]
@pankajsn Please assign to the appropriate milestone

**Comment by pankajsn** [comment]
@markcowl  Fixed the mile stone for this issue.

**Comment by cormacpayne** [comment]
@pankajsn has this been resolved? If not, please use the [`Get-Location`](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Common/Commands.ScenarioTests.ResourceManager.Common/Common.ps1#L583-L604) function from our common test code, which avoids using hard-coded locations

**Comment by refortie** [comment]
@cormacpayne The location you linked no longer exists. (The whole common code seems to have been removed). Is there a replacement that should be used?
