### ISSUE TITLE
Import-Module AzureRM takes longer than usual time 

### ISSUE THREAD

**Issue by sameer-kumar** [Azure/azure-powershell#2541]
Hi,

I’m using WMF 5.0 with azure powershell cmdlets v1.5.0. I have an import-module statement which imports AzureRM. 

`Import-Module -Name 'AzureRM'`

This operation takes longer than expected to execute. It took approx. 10 minutes to move to next line. Is it acceptable?

Is it just me?

Thanks!

**Comment by markcowl** [comment]
@sameer-kumar apologies for the bad experience.  This is likely related to this issue: #2223 

This is due for a fix in the next release.  Closing this for now as a duplicate.
