### ISSUE TITLE
[Doc]: Documentation references 'Availability set', example uses virtual machine name

### ISSUE THREAD

**Issue by sabuncumurat** [Azure/azure-powershell#25430]
### Type of issue

Other (describe below)

### Feedback

The `-Name` parameter is described as follows:

> Specifies the name of the availability set that this cmdlet gets. 

On the other hand, Example 1 on the same page passes a virtual machine name as the `-Name` argument.

I don't even know what an `availability set` is, but I am thinking `-Name` should be described to be a virtual machine name.

FYI.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.compute/get-azremotedesktopfile?view=azps-12.0.0

### Content source URL

?

**Comment by isra-fel** [comment]
Thanks for reporting! Looping in corresponding dev team

**Comment by TravisCragg-MSFT** [comment]
@sabuncumurat Thanks for letting us know! I am working to get this corrected now.

**Comment by isra-fel** [comment]
Source code updated. Doc will be refreshed around August 6.
