### ISSUE TITLE
[Doc]  Get-AzMetric - Docs samples don't match actual cmdlet

### ISSUE THREAD

**Issue by Alex-wdy** [Azure/azure-powershell#25469]
### Description

To update current versions of the Get-AzMetric reference doc, raise a PR in the azure-docs-powershell repo:
 
[https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/azps-12.0.0/Az.Monitor/Get-AzMetric.md](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fazure-docs-powershell%2Fblob%2Fmain%2Fazps-12.0.0%2FAz.Monitor%2FGet-AzMetric.md&data=05%7C02%7Cwangalex%40microsoft.com%7Cda15316be48c48d6679408dc99d9a775%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638554407353179121%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=MHd40mTDyeqDKrOnjrgI1nTFTd5rZaVXghjVdxaNajM%3D&reserved=0)
[https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/azps-11.6.0/Az.Monitor/Get-AzMetric.md](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fazure-docs-powershell%2Fblob%2Fmain%2Fazps-11.6.0%2FAz.Monitor%2FGet-AzMetric.md&data=05%7C02%7Cwangalex%40microsoft.com%7Cda15316be48c48d6679408dc99d9a775%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638554407353184976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=yuMTZ025wge0sxPWrmrbuDdr%2FNxvNKmv2n%2Fvh0uwo%2Fc%3D&reserved=0)

Actual output:
![image](https://github.com/Azure/azure-powershell/assets/108926104/461a0504-9ff2-40fc-b8c6-abc68ee39329)

According to the docs (https://learn.microsoft.com/en-us/powershell/module/az.monitor/get-azmetric):
![Uploading image.png…]()

### Issue script & Debug output

```PowerShell
N/A
```

### Environment data

```PowerShell
PS C:\Users\wangalex> $PSversiontable

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:\Users\wangalex> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.0.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
```

### Error output

```PowerShell
N/A
```

**Comment by isra-fel** [comment]
We need to refresh the examples of this cmdlet

**Comment by JoyerJin** [comment]
Microsoft Docs is fixed.
