### ISSUE TITLE
The "Get-AzKeyVault" but not returning as expected on Azure CLI even on the latest version of az

### ISSUE THREAD

**Issue by Papad2005** [Azure/azure-powershell#25509]
### Description

Hello Team,
 
I have a cx query the "Get-AzKeyVault" but not returning as expected on Azure CLI.
 
The cmd “Get-AzKeyVault -ResourceGroupName $ccoeKvResourceGroupName -VaultName $ccoeKeyVaultName -SubscriptionId $ccoeKvSubscriptionId” returned with error to Connect-AzAccount with the service principal. 
 
It should pick the subscription as stated in the variables but doesn't it only works when we force it and actually specify the subscription again in the variables .
 
"Connect-AzAccount -ServicePrincipal -TenantId $Tenantid -Credential -Subscription "belfius-spoke-dev-001" which return as expected.
 

 
 
 
 
 
[Get-AzKeyVault (Az.KeyVault) | Microsoft Learn](https://learn.microsoft.com/en-us/powershell/module/az.keyvault/get-azkeyvault?view=azps-12.0.0#-subscriptionid)
 
Thanks for your assistance.

**Comment by rach1tarora** [comment]
try this
https://github.com/Azure/azure-powershell/issues/24967

**Comment by isra-fel** [comment]
It could be an issue with WAM - fixed, please try the latest version.
Also worth noting that if `-Subscription` doesn't allow specifying subscription not in the current tenant. Run `Get-AzContext` to get the active tenant. `Set-AzContext` to switch to another.
