### ISSUE TITLE
[Feature]: Add Cmdlet(s) for creating and updating Runbook drafts

### ISSUE THREAD

**Issue by michaeldcanady** [Azure/azure-powershell#25511]
### Description of the new feature

Currently there is no way, as far as I know, to create or update runbook drafts using the PowerShell SDK

**Comment by ITJoeSchmo** [comment]
**Import-AzAutomationRunbook** without **-Published** switch should do the trick right?

**Comment by michaeldcanady** [comment]
No, at least not with how the Cmdlet is now, "all" that does is create a new runbook utilizing the provided PowerShell.

I checked the debug logs and it does make the desired call during it's execution but I needed it to be able to add a draft an **existing** runbook.

**Comment by ITJoeSchmo** [comment]
> No, at least not with how the Cmdlet is now, "all" that does is create a new runbook utilizing the provided PowerShell.
> 
> I checked the debug logs and it does make the desired call during it's execution but I needed it to be able to add a draft an **existing** runbook.

It does work with an **existing** runbook if you use -Force I just tested it:
![image](https://github.com/user-attachments/assets/214b2c6c-be32-40bd-a7bb-a1f084fc7d4f)

Confirmed it updated the draft version while the current published version is in place:

![image](https://github.com/user-attachments/assets/7e7ab6aa-e76a-453a-9fd9-fc39486cb1dc)

**Comment by michaeldcanady** [comment]
It would be helpful if that was outlined in the documentation
