### ISSUE TITLE
Issue with Invoke-AzOperationalInsightsQuery Returning Incorrect Data Types

### ISSUE THREAD

**Issue by hinault** [Azure/azure-powershell#25516]
### Description

I am encountering an issue with the Invoke-AzOperationalInsightsQuery command while attempting to retrieve the schema of a table. This schema is subsequently used to create a copy of the table. However, there appears to be a discrepancy in the data types returned by the command. 

For columns of type GUID, the command returns String as type.

For exemple here is the schema of the source table :

<img width="419" alt="image" src="https://github.com/Azure/azure-powershell/assets/15146271/ceb440d8-a20c-439c-b7f3-49054568e7f2">

The columns TestGuid1 and TestGuid2, which are of type GUID, are being returned as type String.

<img width="444" alt="image" src="https://github.com/Azure/azure-powershell/assets/15146271/e5e120ac-ae21-4040-a595-a942b058cb14">

Thanks

### Issue script & Debug output

```PowerShell
Invoke-AzOperationalInsightsQuery -WorkspaceId MyLAWID -Query "TestDemoTable_CL | getschema | project ColumnName, ColumnType"
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22621.3880
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.3880
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.0.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzCont...
Script     3.2.1      Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, ...
```

**Comment by isra-fel** [comment]
Can you share the debug log with us?
Run `$debugPreference = 'Continue'` before the cmdlet to enable it.
