### ISSUE TITLE
Breaking changes with Get-AzAccessToken Token property changed from String to SecureString

### ISSUE THREAD

**Issue by dadthiele** [Azure/azure-powershell#25533]
### Description

https://learn.microsoft.com/en-us/powershell/azure/upcoming-breaking-changes?view=azps-12.1.0#get-azaccesstoken

With the change my understanding is that there will not be a way to get the plaintext Token?  How do we work around this with other PS commands that dont have a securestring option eg: Invoke-Sqlcmd  (and many others)

https://learn.microsoft.com/en-us/powershell/module/sqlserver/invoke-sqlcmd?view=sqlserver-ps
$access_token = (Get-AzAccessToken -ResourceUrl https://database.windows.net).token/

**Comment by ITJoeSchmo** [comment]
There are a number of options to decrypting a SecureString in PowerShell. 

My favorite way is to simply cast it as a PSCredential and then reference the .Password property under the .GetNetworkCredential() method. Let's say you have a SecureString token in the var $encryptedToken
`$tokenCredential = [PSCredential]::new("token", $encryptedToken)`
Then you can simply reference/decrypt it when/where needed with:
`$tokenCredential.GetNetworkCredential().Password`

It is better security poster to not just store the plaintext password in the RAM; if something managed to get a dump of the RAM they'd have the password. I try to only store passwords as SecureStrings and then decrypt them in functions, so they are removed from RAM quickly. If they end up getting decrypted in the main script and stored in a var, I will $null it out after it isn't needed. Usually in the Finally {} block after a Try {} where the var is used.

**Comment by dadthiele** [comment]
Thanks @ITJoeSchmo . We are using managed identity for a lot use the use-cases where a token is needed to execute sql on an azure database. I think I have worked out a way forward for us (see below) but it would be good to understand why the default will be securestring and the option is still only -assecurestring. I would expect a -asplaintext option instead if the default is secure string.

$access_token = (ConvertFrom-SecureString (Get-AzAccessToken -ResourceUrl https://database.windows.net -AsSecureString).Token -AsPlainText)

**Comment by ITJoeSchmo** [comment]
Thanks for mentioning that cmdlet ConvertFrom-SecureString. For some reason
I thought it wasn't available in 5.1 but it looks like maybe it is. I can't
speak officially, but I believe it is simply to follow best practices with
security. As I had said the password would be stored in plaintext in the
RAM (memory) of the execution environment while the process is running.
It's the same reason any PSCredential object in PowerShell has its password
stored as a SecureString, and why if you're updating someone's password in
Active Directory via PowerShell, the new password must also be a
SecureString object.
