### ISSUE TITLE
Set-AzureRmContext -SubscriptionId does not work with multiple domains

### ISSUE THREAD

**Issue by spaelling** [Azure/azure-powershell#2554]
To reproduce one needs access to 2 subscriptions in different domains. It seems that the "default" domain is the dominant one when it comes to validating subscriptionIds.

In this case the bizspark subscription is _not_ managed by the default domain.

```
# login to 'bizspark' subscription (managed by golddiggers.onmicrosoft.com)
Add-AzureRmAccount -SubscriptionName 'bizspark'

# this works fine
$SubId = (Set-AzureRmContext -SubscriptionName 'bizspark').Subscription.SubscriptionId
# this also works
Set-AzureRmContext -SubscriptionId $SubId

# now we log into another subscription managed by a different domain (leadminers.onmicrosoft.com)
Add-AzureRmAccount -SubscriptionName 'MSDN_Lumagate'

# this still works
$SubId = (Set-AzureRmContext -SubscriptionName 'bizspark').Subscription.SubscriptionId
# but this now fails
Set-AzureRmContext -SubscriptionId $SubId
# save the tenant Id
$TenantId = (Get-AzureRmContext).Tenant.TenantId
# now switch to a different context - id is autocompleted
Set-AzureRmContext -TenantId 96c09248-727b-4608-8ad9-31997e7ae230
(Get-AzureRmContext).Tenant.TenantId -eq $TenantId
# now we try to set the context to the previous tenant - also does not work
Set-AzureRmContext -TenantId $TenantId
# but now it does not complain
Set-AzureRmContext -SubscriptionName 'bizspark'
Set-AzureRmContext -TenantId $TenantId
```

**Comment by markcowl** [comment]
### Description

The issue in this case is that the cached data for subscriptionId only encompasses a single subscription.  The solution is to add some structure to the cache, so that the full set of subscriptions are keyed by tenantId, i.e. ```tenantId => subscriptionList``` .   We cna then use this cached data in the ValidatioNSet for SubscriptionId - essentially, the list would change based on whether or not tenantId was provided as a parameter.
- Add new structure to Accoutn object
- Add tests
- Update validation sets pushed by dynamic parameters to use the new structure

### Cost: 4

**Comment by slavizh** [comment]
Here is an example you can test with subscriptions in different subscriptions 
$AzureInfo =
 (Get-AzureRmSubscription `
 -ErrorAction Stop |
 Out-GridView `
 -Title 'Select a Subscription/Tenant ID for deployment...' `
 -PassThru)

 # Select Subscription
 Select-AzureRmSubscription `
 -SubscriptionId $AzureInfo.SubscriptionId `
 -TenantId $AzureInfo.TenantId `
 -ErrorAction Stop| Out-Null

**Comment by yokimjd** [comment]
This workaround worked for me
  
Login-AzureRmAccount -SubscriptionId 

which seems to eliminate the default tenant being cached.

**Comment by smereczynski** [comment]
Hi,
This issue is still present in 6.0.0-alpha18 (MacOS X 10.12.4). Not clean install (update).

**Comment by ToMakeSense** [comment]
> This workaround worked for me
> 
> Login-AzureRmAccount -SubscriptionId
> 
> which seems to eliminate the default tenant being cached.

same there, it works.
