### ISSUE TITLE
[Feature]: Support to input StorageType

### ISSUE THREAD

**Issue by jonildoasantos** [Azure/azure-powershell#25630]
### Description of the new feature

Need support to input StorageType option for {PremiumV2_LRS, Premium_LRS} at command New-AzPostgreSqlFlexibleServer

**Comment by nachoalonsoportillo** [comment]
@jonildoasantos  While this functionality is not made available through the `New-AzPostgreSqlFlexibleServer` and `Update-AzPostgreSqlFlexibleServer` cmdlets in the `Az.PostgreSql` module, please leverage `Invoke-AzRestMethod` to hit the Server endpoint of any of the preview versions of the REST API that exposes `Storage.properties.type`. For example, you can use [2024-03-01-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/2024-03-01-preview/FlexibleServers.json).
