### ISSUE TITLE
Remove-AzureVM*Extension cmdlets doesn't work

### ISSUE THREAD

**Issue by vors** [Azure/azure-powershell#257]
This is a generic problem of `Remove-AzureVM*Extension` cmdlets. I will talk about few of them.

`Remove-AzureVMDSCExtension` follows the pattern for all other extension cmdlets and inherit from `RemoveAzureVMExtension` class. But `Remove-AzureVMDSCExtension` [doesn't work as expected](https://connect.microsoft.com/PowerShell/feedback/details/1162331/remove-azurevmdscextension-does-not-seem-to-work).
Some extensions (like `AzureVMBGInfoExtension`) implement `-Uninstall` parameter on `Set-*` cmdlet, but my understanding is that `Remove-*` should be the preferred way for consistent experience.

Here is a repro to illustrate the problem for BGInfoExtension:
1) Create a VM from the azure portal
2) It will have BGInfo extension installed by default (correct me if I'm wrong, maybe it's only on my subscription) 
```text
> $azureVMs = Get-AzureVM; $azureVMs[4] | Get-AzureVMBGInfoExtension

ExtensionName        : BGInfo
Publisher            : Microsoft.Compute
Version              : 1.*
PrivateConfiguration : 
PublicConfiguration  : 
ReferenceName        : BGInfo
State                : Enable
RoleName             : vors-1
```

In my case fresh VM is number 4.
3) Use remove cmdlet:
```text
> $azureVMs[4] | Remove-AzureVMDscExtension | Update-AzureVM
OperationDescription                        OperationId                                OperationStatus                           
--------------------                        -----------                                ---------------                           
Update-AzureVM                              7b165347-b529-7343-a859-ed5d0baa381e       Succeeded       
```

4) Get extension again:
```
$azureVMs = Get-AzureVM; $azureVMs[4] | Get-AzureVMBGInfoExtension
```
Expected: result should be empty

Actual: extension presented
```
ExtensionName        : BGInfo
Publisher            : Microsoft.Compute
Version              : 1.*
PrivateConfiguration : 
PublicConfiguration  : 
ReferenceName        : BGInfo
State                : Enable
RoleName             : vors-1
```

**Comment by markcowl** [comment]
@vors thanks for the feedback, assigning to the appropriate service team

**Comment by singhkay** [comment]
@vors In ASM mode the Remove-Extensions cmdlets only remove the extension from the local vm object. We heard feedback that this was confusing for the users and in ARM mode we've fixed this so that the Remove*Extension cmdlets actually remove the extension from the cloud VM.
