### ISSUE TITLE
Microsoft.Azure.PowerShell.Cmdlets.RedisCache.dll-Help.xml doc contains sensitive data such as keys

### ISSUE THREAD

**Issue by msqishengc** [Azure/azure-powershell#25717]
### Description

Update Az modules today, I have OneDrive for business enabled to Sync Documents, then got alert from Office365 (no-reply@sharepointonline.com) in title of Action Required: File Blocked - take action to protect the sensitive data found in a file you modified:  Microsoft.Azure.PowerShell.Cmdlets.RedisCache.dll-Help

I reviewed the xml file, lots of PrimaryKey/SecondaryKey as examples and hard to report as exception because they do look like strings as keys:

     <maml:title>------- Example 1: Get the access keys for a Redis Cache -------</maml:title>
        <dev:code>Get-AzRedisCacheKey -ResourceGroupName "MyResourceGroup" -Name "MyCacheKey"

PrimaryKey        : pJ+jruGKPHDKsEC8kmoybobH3TZx2njBR3ipEsquZFo=
SecondaryKey      : sJ+jruGKPHDKsEC8kmoybobH3TZx2njBR3ipEsquZFo=</dev:code>
        <dev:remarks>
          <maml:para>This command gets the access keys named MyCacheKey.</maml:para>
<maml:para></maml:para>
<maml:para></maml:para>

**Comment by isra-fel** [comment]
Thanks for reporting! This was fixed by https://github.com/Azure/azure-powershell/pull/25425/files
New version will be available August 8th
