### ISSUE TITLE
Test-AzSignalRName - Increase Clarity 

### ISSUE THREAD

**Issue by jpomfret** [Azure/azure-powershell#25792]
### Type of issue

Missing information

### Feedback

[Test-AzSignalRName](https://learn.microsoft.com/en-gb/powershell/module/az.signalr/test-azsignalrname) - the use of this command is not very clear from the docs.

Looking at the code this makes sense, but from reading the docs it isn't clear that this is checking whether a name is available for use.

At first read I was expecting this to return `true` if the name did exist, so the results felt backwards.

Also the wording of the examples is not super clear.

> Example 1: Check an existed name
> Example 2: Check an unexisted name.

Maybe these could be rewritten to something like:

> Example 1: Check if a name is already in use
> Example 2: Check if a name is available to use.

### Page URL

https://learn.microsoft.com/en-gb/powershell/module/az.signalr/test-azsignalrname?view=azps-12.2.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/SignalR/SignalR/help/Test-AzSignalRName.md

### Author

@mikefrobbins

### Document Id

f0d3d385-215a-21a6-109d-c42f6faf2c92

**Comment by chenkennt** [comment]
@Y-Sindo please help take a look

**Comment by jpomfret** [comment]
Thanks folks! Much clearer 💜
