### ISSUE TITLE
Can't deploy - error from Set-AzureRmContext (Cannot validate argument on parameter 'SubscriptionId')

### ISSUE THREAD

**Issue by alvipeo** [Azure/azure-powershell#2585]
I have 4 subscriptions and I'm working on one (testing) and then trying to make a deployment to another one (with New-AzureRmResourceGroupDeployment). Here's what I have:

```
$subscription = Get-AzureRmSubscription -SubscriptionName $subscriptionName
Get-AzureRmSubscription -SubscriptionId $subscription.SubscriptionId | Select-AzureRmSubscription
Set-AzureRmContext -SubscriptionId $subscription.SubscriptionId
```
and I get 
>>Cannot validate argument on parameter 'SubscriptionId'. The argument "[guid]" does not belong to the set "[another guid]" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

So, how to make a deployment?

**Comment by hovsepm** [comment]
@alvipeo thanks for reporting. this is the same issue as https://github.com/Azure/azure-powershell/issues/2554 .
