### ISSUE TITLE
New-AzureWebsite throws error when called with -Git option

### ISSUE THREAD

**Issue by dprothero** [Azure/azure-powershell#259]
Version 0.8.14

I want to automate creation of an Azure Website and am using the following PowerShell command:

```
New-AzureWebsite -Git -Location "West US" -Name mynewsite -PublishingUsername myuser
```

It creates the website just fine, but at the end it throws the following error:

```
New-AzureWebsite : Invalid URI: The hostname could not be parsed.
At line:1 char:1
+ New-AzureWebsite -Git -Location "West US" -Name crmp-ebb-uat -PublishingUsername ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureWebsite], UriFormatException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.NewAzureWebsiteCommand
```

This error seems to be related to the -Git parameter. If I leave off the -Git parameter, it succeeds without the error. With the -Git parameter, even though I get the error, the Git repository is still setup correctly. There doesn't seem to be a way to setup the Git repository outside of the New-AzureWebsite cmdlet.

I can just ignore this error, but it seems messy. Does anyone know what might be causing this?

**Comment by markcowl** [comment]
@dprothero Are you running the cmdlet from inside a git repo?  I suspect one of the URIs in your remotes is causing an issue.  Assigning to the feature team.

**Comment by cormacpayne** [comment]
Closing this issue due to a lack of activity. Please feel free to re-open this issue if you are still using the RDFE-based Website cmdlets and continue to see the same issue.
