### ISSUE TITLE
[Doc]: Documentation for Set commands regarding Azure Policy is missing following the breaking change in PS version 12.0.0

### ISSUE THREAD

**Issue by DKSaxo** [Azure/azure-powershell#25927]
### Type of issue

Missing information

### Feedback

Although it is briefly explained in the Migration Guide https://learn.microsoft.com/en-us/powershell/azure/migrate-az-12.0.0?view=azps-12.2.0, not all changes are documented here (example assignIdentity parameter). 
There is no detail regarding the new supported parameters for Set-AzPolicyAssignment, Set-AzPolicyDefinition etc. The last supported version is https://learn.microsoft.com/en-us/powershell/module/az.resources/set-azpolicyassignment?view=azps-11.6.0

**Comment by VeryEarly** [comment]
Hi @DKSaxo ,
`Set-AzPolicyAssignment` `Set-AzPolicyDefinition` is now alias of `Update-AzPolicyAssignment` `Update-AzPolicyDefinition`, please see below links for migration guide:
https://learn.microsoft.com/en-us/powershell/azure/migrate-az-12.0.0?view=azps-12.2.0#set-azpolicyassignment
https://learn.microsoft.com/en-us/powershell/azure/migrate-az-12.0.0?view=azps-12.2.0#set-azpolicydefinition

**Comment by DKSaxo** [comment]
Thanks this is now clear, it was not clear in the documentation and only mentions it in the example
