### ISSUE TITLE
WAM Login does not work in VSCode Terminal (both pwsh.exe and PowerShell Extension)

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#26008]
### Description

![image](https://github.com/user-attachments/assets/d9a3b601-8875-47d3-afd9-c0516fde5587)

(Prompt never appears)

### Module versions

```PowerShell
Az.Accounts 3.0.4
```

**Comment by msJinLei** [comment]
@JustinGrote We already meet the same issue https://github.com/Azure/azure-powershell/issues/24989
Actually the popup is somewhere behind. Please minimize the windows front one by one and you can find the WAM window

**Comment by msJinLei** [comment]
Close for duplicate
