### ISSUE TITLE
Get-AzureVM fails silently

### ISSUE THREAD

**Issue by micktion** [Azure/azure-powershell#2608]
When I run Get-AzureVM it terminates without giving any output to the console.  It should give some feedback to the user to let them know what has happened, regardless of what the state is, e.g. not logged in, no vms found etc.

Without any output from powershell scripts its very difficult to isolate an issue when you're having one.

When I run Get-AzureVM I have no idea why its failing (or if it is failing), I do have classic Cloud Service running a Worker Role, I'm pretty sure I am logged in.  

I'm using Azure Powershell scripts Version v1.5.1 and PowerShell v5.0.10586.494 on Windows 10.

EDIT: Upgraded to v1.6.0, no change, still fails silently.

![image](https://cloud.githubusercontent.com/assets/4677284/16825060/980e4d6c-49b4-11e6-84cc-9828f435f758.png)

**Comment by markcowl** [comment]
@singhkay Can you take a look

**Comment by singhkay** [comment]
@hyonholee Can you take a look at this?

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
