### ISSUE TITLE
how to export in Definitype FOCUS? 

### ISSUE THREAD

**Issue by ftessierAzeo** [Azure/azure-powershell#26088]
### Type of issue

Other (describe below)

### Feedback

how to export in Definitype FOCUS?

Actualy ------------------------------------------------- 
new-azcostmanagementExport -DefinitionType '
Usage ActualCost AmortizedCost
---------------------------------------------------------

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.costmanagement/new-azcostmanagementexport?view=azps-12.3.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/CostManagement/CostManagement/help/New-AzCostManagementExport.md

### Author

@mikefrobbins

### Document Id

45d8360c-8698-f1ec-849b-f2f72a84154a

**Comment by isra-fel** [comment]
Can you be more specific about the question? Thanks
