### ISSUE TITLE
Get-AzStorageTable: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by LukaszEV** [Azure/azure-powershell#26093]
### Description

We recently updated some docker images with Az module and now we have a problem with Get-AzStorageModule
While running Get-AzStorageTable
`$storageAccount = Get-AzStorageAccount -ResourceGroupName $deploymentsResourceGroup -Name $deploymentsStorageAccount`
`$ctx = $storageAccount.Context`
`$catalog = (Get-AzStorageTable -Name $tableName -Context $ctx).CloudTable`

We are getting:
_Get-AzStorageTable: Object reference not set to an instance of an object error_

its working fine with:

| ModuleType | Version | PreRelease | Name        |
|------------|---------|------------|-------------|
| Script     | 3.0.3   |            | Az.Accounts |
| Script     | 7.2.0   |            | Az.Storage  |
| Manifest   | 2.1.0   |            | AzTable     |

### Issue script & Debug output

```PowerShell
Get-AzStorageTable -Name $tableName -Context $ctx -debug              
DEBUG: 11:07:31 - Init Operation Context for 'GetAzureStorageTableCommand' with client request id  Azure-Storage-PowerShell-810f623a-8fe
b-4446-ac3b-bb5e03594c39. If you want to get more details, please add "-Debug" to your command.
DEBUG: 11:07:31 - GetAzureStorageTableCommand begin processing with ParameterSet 'TableName'.
DEBUG: 11:07:31 - Use storage account 'svccatst01weuprd' from storage context.
Get-AzStorageTable: Object reference not set to an instance of an object.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Ubuntu 22.04.5 LTS
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
| ModuleType | Version | PreRelease | Name        |
|------------|---------|------------|-------------|
| Script     | 3.0.4   |            | Az.Accounts |
| Script     | 7.3.0   |            | Az.Storage  |
| Manifest   | 2.1.0   |            | AzTable     |
```

### Error output

```PowerShell
DEBUG: 11:09:36 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 11:09:36 - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
   HistoryId: 74

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Cosmos.Table.CloudStorageAccountExtensions.CreateCloudTableClient(CloudStorageAccount account, TableClientConfiguration configuration)
                    at Microsoft.WindowsAzure.Commands.Storage.Model.Contract.StorageTableManagement..ctor(AzureStorageContext context)            at Microsoft.WindowsAzure.Commands.Storage.Table.StorageCloudTableCmdletBase.CreateChannel()
                    at Microsoft.WindowsAzure.Commands.Storage.Common.StorageCloudCmdletBase`1.InitChannelCurrentSubscription(Boolean force)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.StorageCloudCmdletBase`1.InitChannelCurrentSubscription()
                    at Microsoft.WindowsAzure.Commands.Storage.Common.StorageCloudCmdletBase`1.ProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzStorageTable}
Line           : Get-AzStorageTable -Name $tableName -Context $ctx -debug
Position       : At line:1 char:1
                 + Get-AzStorageTable -Name $tableName -Context $ctx -debug
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 74



DEBUG: 11:09:36 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 11:09:36 - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:3.0.4; CommandName: Resolve-AzError; PSVersion: 7.4.5; IsSuccess: True; Duration: 00:00:00.00
24831; SanitizeDuration: 00:00:00.0003422
DEBUG: 11:09:36 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 11:09:36 - ResolveError end processing.
```

**Comment by blueww** [comment]
@LukaszEV 

Would you please install the latest Az.Storage module 7.3.1, and see if the issue still repro?
https://www.powershellgallery.com/packages/Az.Storage/7.3.1

You can install by run "Install-Module -Name Az.Storage -RequiredVersion 7.3.1"

**Comment by LukaszEV** [comment]
@blueww 
Hello, sorry for the late replay., I tested today with 7.3.1 and its working fine :) thank you

**Comment by inaun** [comment]
I can confirm there is a bug in 7.3.0 that causes this error. 7.3.1 fixes that bug.

**Comment by KB-RoDi** [comment]
> I can also confirm there is a bug in 7.3.0 that causes this error. 7.3.1 fixes that bug.

I'm using Azure Automation Runbooks, in the mapped Environment I got Az.Storage 7.3.1, Az.Accounts 3.0.4 and AzTable 2.1.0 loaded - still facing this issue
![image](https://github.com/user-attachments/assets/5296d431-e07f-4ed3-85bc-612f0b656ce2)
![image](https://github.com/user-attachments/assets/b95f8a37-0b3f-49a4-9fa9-d6984f02d0da)

**Comment by blueww** [comment]
@KB-RoDi 

It might caused you are still using Az.Storage 7.3.0.
You can check the module version you are using by run "Get-module Az.Storage" after the issue repro in same PSH session.

If you still use 7.3.0, you might can check if 7.3.0 is removed from your Azure Automation Runbooks, and you might can also force 7.3.1 be imported by run "Import-Module Az.Storage -RequiredVersion 7.3.1" as the first command of you PSH session.

**Comment by KB-RoDi** [comment]
> @KB-RoDi
> 
> It might caused you are still using Az.Storage 7.3.0. You can check the module version you are using by run "Get-module Az.Storage" after the issue repro in same PSH session.
> 
> If you still use 7.3.0, you might can check if 7.3.0 is removed from your Azure Automation Runbooks, and you might can also force 7.3.1 be imported by run "Import-Module Az.Storage -RequiredVersion 7.3.1" as the first command of you PSH session.

Yeah, right after posting in debug output I spotted 7.3.0 as used version - I've done some local cleanup - now 7.3.1 is loaded and everything's working.

Thanks for the reply
