### ISSUE TITLE
[Feature]: Remove latest.tar.gz and Latest Folder From Docker Container Layer

### ISSUE THREAD

**Issue by gone-for-coding** [Azure/azure-powershell#26123]
### Description of the new feature

The alpine image build process does not remove temporary files resulting in wasted space of about 200MiB.
```
/ # du -h latest*
105.4M  latest
102.5M  latest.tar.gz
```

### Proposed implementation details (optional)

Remove the latest directory and latest.tar.gz file from the layer here:
https://github.com/Azure/azure-powershell/blob/main/docker/Dockerfile-alpine-3.17#L34-L39

**Comment by gone-for-coding** [comment]
FYI: Other images are affected as well.

**Comment by isra-fel** [comment]
@Nickcandy let's remove the temp files
