### ISSUE TITLE
[Feature]: Remove alias "Resolve-Error"

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-powershell#26189]
### Description of the new feature

https://github.com/PowerShell/ProjectMercury/issues/200

`Resolve-Error` is an alias of `Resolve-AzError`. It does not comply with the `Az-` convention and starts to conflict with other module.

### Proposed implementation details (optional)

Preannounce the breaking change and remove the alias in next major release

**Comment by StevenBucher98** [comment]
@isra-fel can this be closed?

**Comment by isra-fel** [comment]
The removal was preannounced and will happen in the Ignite release of Az 13.0.0 @StevenBucher98
