### ISSUE TITLE
Set-AzureRmApiManagementUser throws ValidationError when State is not specified

### ISSUE THREAD

**Issue by solankisamir** [Azure/azure-powershell#2622]
When Set-AzureRmApiManagementUser is execute without State, it throws error ValidationError, as the UserState that is passed is 0, which is an Invalid User State.

**Comment by solankisamir** [comment]
The powershell release https://www.powershellgallery.com/packages/AzureRM/3.0.0 contains the fix.

**Comment by thomasddn** [comment]
I believe this issue has been reintroduced. Currently using AzureRM v5.0.1 and I can't update a user's password without passing the state.

The error message:

    Set-AzureRmApiManagementUser : ValidationError: One or more fields contain incorrect values:
    At line:1 char:1
      Set-AzureRmApiManagementUser -Context $apimContext -UserId "test" -Pa ...
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        CategoryInfo          : CloseError: (:) [Set-AzureRmApiManagementUser], CloudException
        FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.SetAzureApiManagementUser
