### ISSUE TITLE
Set-AzureRmVMCustomScriptExtension is not supporting PSVirtualMachine parameter

### ISSUE THREAD

**Issue by iricigor** [Azure/azure-powershell#2626]
At the moment, there is only `-VMName` as parameter of type [string]. I cannot pass VM configuration object to script (type `[Microsoft.Azure.Commands.Compute.Models.PSVirtualMachine]` or similar). This is making command unusable for VMs that are being provisioned. One needs to provision non-customized (or unsecured machine) and wait for for its availability.
This functionality was present in old Azure PowerShell, i.e. command `Set-AzureVMCustomScriptExtension` was working just fine. The same is with other verbs (Get- , Remove-) in new Azure PowerShell.

**Comment by maddieclayton** [comment]
@danielsollondon Can you take a look at this issue?
