### ISSUE TITLE
Missing help Get-AzureRmLocalNetworkGateway

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2627]
![image](https://cloud.githubusercontent.com/assets/466713/16925750/e8fa24ae-4ce2-11e6-8709-ae631ca3ebb8.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by sdwheeler** [comment]
@pcgeek86 - this has been fixed now.
