### ISSUE TITLE
ResourceGroupName parameter should not be mandatory for Get-AzureRmLocalNetworkGateway

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2628]
![image](https://cloud.githubusercontent.com/assets/466713/16925829/47f5bd42-4ce3-11e6-879c-b3c3ad255d33.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by DeepakRajendranMsft** [comment]
@lamchester, please fix this

**Comment by maddieclayton** [comment]
Closing in favor of: https://github.com/Azure/azure-powershell/issues/3030.
