### ISSUE TITLE
Set-AzureVNetGatewayKey : InternalError : An internal error has occurred.

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2629]
> Set-AzureVNetGatewayKey : InternalError : An internal error has occurred.

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment]
That is just an awesome error message.

@deepakrakendranmsft can you take a look?

**Comment by DeepakRajendranMsft** [comment]
@lamchester, please take a look

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
