### ISSUE TITLE
Deprecation of type [Microsoft.Azure.Commands.Profile.Models.PSAccessToken] ?

### ISSUE THREAD

**Issue by skille** [Azure/azure-powershell#26352]
### Description

I see there is a upcomming breaking change in the Get-AzAccessToken cmdlet:

```txt
Get-AzAccessToken
Cmdlet breaking-change will happen to all parameter sets
The Token property of the output type will be changed from String to SecureString. Add the [-AsSecureString] switch to avoid the impact of this upcoming breaking change.
This change is expected to take effect from Az.Accounts version: 4.0.0 and Az version: 13.0.0
```

Link: https://learn.microsoft.com/en-us/powershell/azure/upcoming-breaking-changes?view=azps-12.4.0#get-azaccesstoken 

Today, the output of the cmdlet is either of type **[Microsoft.Azure.Commands.Profile.Models.PSAccessToken]** or **[Microsoft.Azure.Commands.Profile.Models.PSSecureAccessToken]** if using the -AsSecureString parameter.

When the change is implemented, I expect that only the type **[Microsoft.Azure.Commands.Profile.Models.PSSecureAccessToken]** is returned as output from the cmdlet.

Will that change also remove the **[Microsoft.Azure.Commands.Profile.Models.PSAccessToken]** type definition, or could we expect to continue to use that type in scripts after the new version is released?

**Comment by isra-fel** [comment]
Hi @skille yes we plan to deprecate the previous type `PSAccessToken`. It will not be the output type in the next major version in any case.

We recommend switching to `PSSecureAccessToken` from now on. Besides, if your script relies on the other properties of the type rather than the type itself, it will still work. For example,

```powershell
PS C:\> $at = Get-AzAccessToken
PS C:\> $at.ExpiresOn # <-- will still give you the correct date and time no matter the underlying type

DateTime           : 2024/10/21 3:07:10 AM
```
