### ISSUE TITLE
Find-AzureRmResourceGroup only showing groups from one subscription, and not the active one

### ISSUE THREAD

**Issue by cravelight** [Azure/azure-powershell#2635]
I have 2 subscriptions.

I have set the second one to my default and it's showing as IsCurrent

When I run `Find-AzureRmResourceGroup` it only shows me resource groups from the first subscription.

**Comment by gandhiniraj** [comment]
@cravelight can you run Get-AzureRmContext and see what subscription is in current context?

**Comment by cravelight** [comment]
I ran through the same process as I did yesterday and today it worked. My only thought is that it might be that I shut down PowerShell completely last night (due to a reboot).  

When I logged in yesterday - the first subscription would have been current/default.

When I logged in today - the second subscription was current/default. (based on my changes yesterday)

**Comment by ravbhatnagar** [comment]
Closing this issue in that case.

**Comment by tobese** [comment]
Thx for the tip. But why isn't resource groups from the current subscription?
