### ISSUE TITLE
Az.Accounts Get-AzAccessToken does not respect $Env:SuppressAzurePowerShellBreakingChangeWarnings

### ISSUE THREAD

**Issue by baidarka** [Azure/azure-powershell#26395]
### Description

Az.Account 3.0.4
Get-AzAccessToken displays BreakingChangeWarning even if:
$Env:SuppressAzurePowerShellBreakingChangeWarnings = $true

WARNING: Upcoming breaking changes in the cmdlet 'Get-AzAccessToken' :
The Token property of the output type will be changed from String to SecureString. Add the [-AsSecureString] switch to avoid the impact of this upcoming breaking change.
- The change is expected to take effect in Az version : '13.0.0'
- The change is expected to take effect in Az.Accounts version : '4.0.0'
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

### Issue script & Debug output

PS /> $DebugPreference='Continue'                               
PS /> $Env:SuppressAzurePowerShellBreakingChangeWarnings = $true
PS /> $adoId = "499b84ac-1321-427f-aa17-267ca6975798"           
PS /> Get-AzAccessToken -ResourceUrl $adoId -AsSecureString     
DEBUG: 1:58:42 PM - [ConfigManager] Got [True] from [DisplaySecretsWarning], Module = [], Cmdlet = [].
DEBUG: 1:58:42 PM - GetAzureRmAccessTokenCommand begin processing with ParameterSet 'ResourceUrl'.
DEBUG: 1:58:42 PM - using account id '<edit>pii</edit>'...
DEBUG: 1:58:42 PM - [ConfigManager] Got [True] from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
WARNING: Upcoming breaking changes in the cmdlet 'Get-AzAccessToken' :
The Token property of the output type will be changed from String to SecureString. Add the [-AsSecureString] switch to avoid the impact of this upcoming breaking change.
- The change is expected to take effect in Az version : '13.0.0'
- The change is expected to take effect in Az.Accounts version : '4.0.0'
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.
DEBUG: 1:58:42 PM - [ConfigManager] Got nothing from [DisableInstanceDiscovery], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 1:58:42 PM - [ConfigManager] Got [False] from [EnableLoginByWam], Module = [], Cmdlet = [].
DEBUG: 1:58:42 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'<edit/>', Scopes:'499b84ac-1321-427f-aa17-267ca6975798/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'<edit>pii</edit>'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ 499b84ac-1321-427f-aa17-267ca6975798/.default ] ParentRequestId: 
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - c083c8db-b7e5-4759-b3c4-6c18c1ef3e70] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - c083c8db-b7e5-4759-b3c4-6c18c1ef3e70] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - c083c8db-b7e5-4759-b3c4-6c18c1ef3e70] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - c083c8db-b7e5-4759-b3c4-6c18c1ef3e70] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - c083c8db-b7e5-4759-b3c4-6c18c1ef3e70] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z] Returning 1 accounts
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - e3b6e2bf-ce53-4951-900c-419d7d0f085d] MSAL MSAL.CoreCLR with assembly version '4.61.3.0'. CorrelationId(e3b6e2bf-ce53-4951-900c-419d7d0f085d)
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - e3b6e2bf-ce53-4951-900c-419d7d0f085d] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - e3b6e2bf-ce53-4951-900c-419d7d0f085d] LoginHint provided: False
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - e3b6e2bf-ce53-4951-900c-419d7d0f085d] Account provided: True
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - e3b6e2bf-ce53-4951-900c-419d7d0f085d] ForceRefresh: False
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - e3b6e2bf-ce53-4951-900c-419d7d0f085d] 
=== Request Data ===
Authority Provided? - True
Scopes - 499b84ac-1321-427f-aa17-267ca6975798/.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - e3b6e2bf-ce53-4951-900c-419d7d0f085d
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - e3b6e2bf-ce53-4951-900c-419d7d0f085d] === Token Acquisition (SilentRequest) started:
         Scopes: 499b84ac-1321-427f-aa17-267ca6975798/.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - e3b6e2bf-ce53-4951-900c-419d7d0f085d] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - e3b6e2bf-ce53-4951-900c-419d7d0f085d] Access token is not expired. Returning the found cache entry. [Current time (10/18/2024 13:58:42) - Expiration Time (10/18/2024 14:44:52 +00:00) - Extended Expiration Time (10/18/2024 14:44:52 +00:00)]
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - e3b6e2bf-ce53-4951-900c-419d7d0f085d] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - e3b6e2bf-ce53-4951-900c-419d7d0f085d] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - e3b6e2bf-ce53-4951-900c-419d7d0f085d] 
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.61.3.0 MSAL.CoreCLR .NET 8.0.8 Linux [2024-10-18 13:58:42Z - e3b6e2bf-ce53-4951-900c-419d7d0f085d]  AT expiration time: 10/18/2024 2:44:52 PM +00:00, scopes: 499b84ac-1321-427f-aa17-267ca6975798/.default 499b84ac-1321-427f-aa17-267ca6975798/user_impersonation. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ 499b84ac-1321-427f-aa17-267ca6975798/.default ] ParentRequestId:  ExpiresOn: 2024-10-18T14:44:52.0000000+00:00
DEBUG: 1:58:42 PM - [ConfigManager] Got [True] from [DisplaySecretsWarning], Module = [], Cmdlet = [].

Token     : System.Security.SecureString
ExpiresOn : 10/18/2024 2:44:52 PM +00:00
TenantId  : <edit/>
UserId    : <edit>pii</edit>
Type      : Bearer

DEBUG: 1:58:42 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 1:58:42 PM - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:3.0.4; CommandName: Get-AzAccessToken; PSVersion: 7.4.5; IsSuccess: True; Duration: 00:00:00.4188271; SanitizeDuration: 00:00:00.0010530
DEBUG: 1:58:42 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 1:58:42 PM - GetAzureRmAccessTokenCommand end processing.
PS /> 

### Environment data

FROM mcr.microsoft.com/azure-powershell:ubuntu-22.04

PS /> $psversiontable                                

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Ubuntu 22.04.5 LTS
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /> 

### Module versions

PS /> get-module Az.*                                      

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.0.4                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}

**Comment by isra-fel** [comment]
This is probably because Az.Accounts was already loaded prior to setting the environment variable (can verify this by running `Get-Module` at the very beginning). Try `Set-AzConfig -DisplayBreakingChangeWarning $false` instead.

**Comment by baidarka** [comment]
Thank you for your response! You reply shrunk the amount of available options: 

`$Env:SuppressAzurePowerShellBreakingChangeWarnings = $true` **prior to loading Az.Accounts**: works.
`Set-AzConfig -DisplayBreakingChangeWarning $false **-Scope Process**` : works
`Set-AzConfig -DisplayBreakingChangeWarning $false -Scope CurrentUser` : no worky
`Set-AzConfig -DisplayBreakingChangeWarning $false -Scope Process -AppliesTo Az.Accounts`: no worky
`Set-AzConfig -DisplayBreakingChangeWarning $false -Scope CurrentUser -AppliesTo Az.Accounts`: no worky

It's probably helpful to document that "$Env:SuppressAzurePowerShellBreakingChangeWarnings must be set prior to loading Az.Accounts" for instance here:
- https://learn.microsoft.com/en-us/powershell/azure/configure-global-settings?view=azps-11.6.0#breaking-change-warning-messages
- https://learn.microsoft.com/en-us/powershell/azure/faq?view=azps-12.4.0#how-do-i-disable-breaking-change-warning-messages-in-azure-powershell-
- https://github.com/Azure/azure-powershell/blob/main/documentation/breaking-changes/breaking-changes-attribute-help.md#suppress-the-breaking-change-messages-at-runtime

Please feel free to follow up if needed. I consider this issue closed my limited perspective  :)
