### ISSUE TITLE
[Doc]: New-AzGalleryImageDefinition.md incorrect value for SecurityType in examples section

### ISSUE THREAD

**Issue by cocallaw** [Azure/azure-powershell#26446]
### Type of issue

Typo

### Feedback

In the examples section for New-AzGalleryImageDefinition in the list of possible values for SecurityType the value "TrustedandConfidentialVMSupported" should be "TrustedLaunchAndConfidentialVmSupported"

More detail and correction is available in PR https://github.com/Azure/azure-powershell/pull/26428

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.compute/new-azgalleryimagedefinition?view=azps-12.4.0

**Comment by sandeepraichura** [comment]
thanks for the attention, will take a look and get it updated.

**Comment by cocallaw** [comment]
The PR https://github.com/Azure/azure-powershell/pull/26428 for this issue has been merged into Future branch

Commit: https://github.com/Azure/azure-powershell/commit/67134510bb2459aa3e404285fe7e7e616816d767
