### ISSUE TITLE
Get-AzureRMSiteRecoveryVault returns nothing

### ISSUE THREAD

**Issue by ned1313** [Azure/azure-powershell#2646]
When running the cmdlet Get-AzureRMSiteRecoveryVault no items are returned.  I can run Get-AzureRMResource and filter on type  Microsoft.RecoveryServices/vaults and I get the two vaults that exist in the current subscription.

**Comment by sriramvu** [comment]
@ned1313: please use 
* Get-AzureRmRecoveryServicesVault to retrieve resources of type Microsoft.RecoveryServices/vaults 
* Get-AzureRmSiteRecoveryVault to retrieve resources of type Microsoft.SiteRecovery/SiteRecoveryVault
