### ISSUE TITLE
Find-AzureRMResource (and other resource cmdlets) use invalif apiVersion when switching between AzureStack and Azure

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2652]
### Description
When No APIVersion is provided on the command line, the api version comes from a call to listing providers and is stored in an Apiversion cache.  This cache is not cleared when I target a different azure environment (like AzureStack) and so, if I login to a different environment, and use FindAzureRmResource again, I may end up using an APIVersion from the cache which may or may not be available in the new environment.

Either the cache should be removed, the cache should be cleared on login, or the cache key should contain the environment name that is targeted.

**Comment by markcowl** [comment]
@ravbhatnagar This is crucial for AzureStack and national cloud scenarios, can you take a look?

**Comment by ravbhatnagar** [comment]
We will fix this.

**Comment by markcowl** [comment]
Fixed
