### ISSUE TITLE
New-AzConnectedMachineRunCommand and other run commands missing from Az.ConnectedMachine 0.10.0

### ISSUE THREAD

**Issue by dxk3355** [Azure/azure-powershell#26539]
### Description

In versions 0.8.0 and 0.9.0 New-AzConnectedMachineRunCommand is listed on [Powershell Gallery](https://www.powershellgallery.com/packages/Az.ConnectedMachine/0.10.0) and is in the .psd files for the Az.ConnectedMachine module.  It is also documented on https://learn.microsoft.com/en-us/powershell/module/az.connectedmachine/new-azconnectedmachineruncommand?view=azps-12.4.0.  However in 0.10.0 this command and several others are no longer in the psd file, if they were moved out then the documentation is out of date.

From 0.8.0
FunctionsToExport = 'Connect-AzConnectedMachine', 'Get-AzConnectedExtensionMetadata', 
               'Get-AzConnectedLicense', 'Get-AzConnectedMachine', 
               'Get-AzConnectedMachineExtension', 
               **'Get-AzConnectedMachineRunCommand',** 
               'Get-AzConnectedNetworkSecurityPerimeterConfiguration', 
               'Get-AzConnectedPrivateLinkScope', 
               'Install-AzConnectedMachinePatch', 
               'Invoke-AzConnectedAssessMachinePatch', 'New-AzConnectedLicense', 
               'New-AzConnectedLicenseDetail', 'New-AzConnectedMachineExtension', 
               **'New-AzConnectedMachineRunCommand',** 
               'New-AzConnectedPrivateLinkScope', 'Remove-AzConnectedLicense', 
               'Remove-AzConnectedMachine', 'Remove-AzConnectedMachineExtension', 
               'Remove-AzConnectedMachineRunCommand', 
               'Remove-AzConnectedPrivateLinkScope', 'Set-AzConnectedLicense', 
               'Set-AzConnectedMachineExtension', 
               'Set-AzConnectedPrivateLinkScope', 'Update-AzConnectedExtension', 
               'Update-AzConnectedMachine', 'Update-AzConnectedMachineExtension', 
               **'Update-AzConnectedMachineRunCommand',** 
               'Update-AzConnectedPrivateLinkScopeTag'

From 0.10.0
FunctionsToExport = 'Connect-AzConnectedMachine', 'Get-AzConnectedExtensionMetadata', 
               'Get-AzConnectedLicense', 'Get-AzConnectedMachine', 
               'Get-AzConnectedMachineExtension', 
               'Get-AzConnectedNetworkSecurityPerimeterConfiguration', 
               'Get-AzConnectedPrivateLinkScope', 
               'Install-AzConnectedMachinePatch', 
               'Invoke-AzConnectedAssessMachinePatch', 
               'Invoke-AzConnectedReconcileNetworkSecurityPerimeterConfiguration', 
               'New-AzConnectedLicense', 'New-AzConnectedLicenseDetail', 
               'New-AzConnectedMachineExtension', 
               'New-AzConnectedPrivateLinkScope', 'Remove-AzConnectedLicense', 
               'Remove-AzConnectedMachine', 'Remove-AzConnectedMachineExtension', 
               'Remove-AzConnectedPrivateLinkScope', 'Set-AzConnectedLicense', 
               'Set-AzConnectedMachineExtension', 
               'Set-AzConnectedPrivateLinkScope', 'Update-AzConnectedExtension', 
               'Update-AzConnectedMachine', 'Update-AzConnectedMachineExtension', 
               'Update-AzConnectedPrivateLinkScopeTag'

### Issue script & Debug output

New-AzConnectedMachineRunCommand: 
Line |
   8 |          $result = New-AzConnectedMachineRunCommand -ResourceGroupName …
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'New-AzConnectedMachineRunCommand' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Environment data

This is running in Azure Automation with 7.2 runtime

### Module versions

This is running in Azure Automation with the following modules added.

Az
Default

Azure CLI
Default

Az.Accounts
3.0.4

Az.Compute
8.4.0

Az.ConnectedMachine
0.10.0

Az.GuestConfiguration
0.11.1

Az.KeyVault
6.2.0

Az.Storage
7.4.0

**Comment by isra-fel** [comment]
I'll loop in ConnecteMachine team to help

**Comment by IsaacRoitman** [comment]
> I'll loop in ConnecteMachine team to help

Having the exact same issue mentioned, the cmdlet does not exist in Az.ConnectedMachine 0.10 module as it should.  My issue is across all attempted sources including:

- Local machine, running PowerShell v7.4 in Windows
- Azure Cloud Shell

**Comment by vidai-msft** [comment]
@rpsqrd @edyoung @vedkale could you help on the question that what is the replacement of "New-AzConnectedMachineRunCommand` after it was removed in v0.10.0? Thanks.

**Comment by dxk3355** [comment]
Looks like they released 1.0.0 but still left out the missing commands!  ![Image](https://github.com/user-attachments/assets/663c1763-3eed-4178-ae7d-ced5def4d763)

**Comment by yaotongms** [comment]
Version 1.0.0 of Az.ConnectedMachine is generated from our stable version API, which doesn't contain run commands operations. 

We have a new release towards a preview version API coming up on the 19th. That module will contain run commands and other preview operations. Sorry for the confusion!

**Comment by dxk3355** [comment]
What happened with 0.10.0 then?  Was that just a precursor to 1.0.0?

**Comment by IsaacRoitman** [comment]
> Version 1.0.0 of Az.ConnectedMachine is generated from our stable version API, which doesn't contain run commands operations.
> 
> We have a new release towards a preview version API coming up on the 19th. That module will contain run commands and other preview operations. Sorry for the confusion!

@yaotongms Is there an ETA on when the API containing run commands (and associated PS module) will become GA?

**Comment by yaotongms** [comment]
> > Version 1.0.0 of Az.ConnectedMachine is generated from our stable version API, which doesn't contain run commands operations.
> > We have a new release towards a preview version API coming up on the 19th. That module will contain run commands and other preview operations. Sorry for the confusion!
> 
> [@yaotongms](https://github.com/yaotongms) Is there an ETA on when the API containing run commands (and associated PS module) will become GA?

The new PS module that includes Run Command will be released around the 19th. Run Command GA is still TBD. Please consider it as a Preview feature until then.

**Comment by yaotongms** [comment]
Version 1.1.0 is released which includes run commands https://www.powershellgallery.com/packages/Az.ConnectedMachine/1.1.0
