### ISSUE TITLE
Improve quality of error messages when multiple "Conflict" errors occur

### ISSUE THREAD

**Issue by gregjhogan** [Azure/azure-powershell#2657]
I deployed a template which links to other templates, and the linked templates use parameters that reference a key vault secret (but I wonder if it is simpler to reproduce than that).  Eventually I discovered what caused the below error was that I forgot to enable the key vault for template deployments, but the error message that I got didn't help me figure that out.

```
VERBOSE: Performing the operation "Creating Deployment" on target "test-group".
New-AzureRmResourceGroupDeployment : Multiple error occurred: Conflict,Conflict,Conflict. Please
see details.
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -ResourceGroupName test-group ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroupDeployment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewA
 zureResourceGroupDeploymentCmdlet
```

**Comment by iamrobdavies** [comment]
Same error is raised when a Key Vault secret in a params file, is not present in the Key Vault.  Would be better to have a detailed message.

**Comment by markcowl** [comment]
This should be addressed by #3648 #3649 closing in favopr of the more detailed issues

**Comment by arcotek-ltd** [comment]
This hasn't been resolved:
New-AzureRmResourceGroupDeployment : Multiple error occurred: . Please see details.
At D:\Test-Template.ps1:53 char:1

PS C:\> get-command New-AzureRmResourceGroupDeployment

CommandType     Name                                               Version    Source                                                                                                                                                                                                                                  
-----------     ----                                               -------    ------                                                                                                                                                                                                                                  
Cmdlet          New-AzureRmResourceGroupDeployment                 4.0.0      AzureRM.Resources 

It doesn't even give a clue. The string is empty (at the ^): ..."occurred:^."... Also, how do I see details as it hasn't logged anything yet?

**Comment by rakeshvanga** [comment]
Is there a log file that azure CLI write to with verbose error details that we can use to figure out the issue?
The reason mentioned by @gregjhogan is the reason in my case also. If this was not the reason and something else is causing this issue how can one know the underlying reason?

**Comment by itanex** [comment]
I am getting a very similar error and my keyvault permisions are enabled. Since the error I get does not have any details as to the issue as @rakeshvanga states, it would be helpful to have some information to handle the errors.

```
08:58:22 - VERBOSE: Performing the operation "Creating Deployment" on target "MigrationPlaybook_Prod".
08:58:23 - New-AzureRmResourceGroupDeployment : Multiple error occurred: Forbidden,Forbidden. Please see details.
08:58:23 - At C:\workspaces\Migration Playbook\MigrationPlaybookRegion\ProductionResourceGroup\bin\Debug\staging\ProductionResourc
08:58:23 - eGroup\Deploy-AzureResourceGroup.ps1:108 char:5
```
