### ISSUE TITLE
Set-AzureRmKeyVaultAccessPolicy fails when using -ObjectId and SPN

### ISSUE THREAD

**Issue by gregjhogan** [Azure/azure-powershell#2658]
This command:
```ps1
Set-AzureRmKeyVaultAccessPolicy -ResourceGroupName $ResourceGroup -VaultName $KeyVault -ObjectId $objectId -PermissionsToSecrets @('get', 'list')
```

Fails with this error:
```
Insufficient privileges to complete the operation.
```

I believe the issue is because the SPN can't query the graph API, but when I pass the object ID it seems like there should be no need to query the graph API.

**Comment by pomortaz** [comment]
When you pass the object ID, it is still validated by calling Graph API. From your description, it looks like your Service Principal doesn't have privilege to query Graph. For its own object ID, I think it should be able to query graph, but not for anything else. Use your global admin to manage your vault resources and give access permission to your SPN for keys and secrets operations. Then you can use your SPN to manage keys and secrets based on its permissions.

**Comment by craig-martin** [comment]
I've been able to repro this by using a newer version of AzureRM.Resources and an older version of AzureRM.KeyVault.  Getting the latest version of both fixed it for me.

**Comment by Moozhe** [comment]
This breaks service principal automation since a service principal cannot create and assign access rights to a new key vault, even when assigned as the role of owner for the subscription.

**Comment by gregjhogan** [comment]
@pormortaz why does it validate the object ID separately from making the API call to set the policy?  I can do this in an ARM template without changing the permissions, so why wouldn't you support it in the powershell cmdlets?  Using a global admin as you suggested is not an acceptable solution.  Thanks!

**Comment by pomortaz** [comment]
@gregjhogan ARM template doesn't do validation. However, in the powershell because it is supposed to be more user friendly we have [this validation](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/KeyVault/Commands.KeyVault/Models/KeyVaultManagementCmdletBase.cs#L211) for object ID (Key Vault doesn't support multi-tenant scenarios, so we want to only allow object ID in the current tenant). You can use ARM template for this purpose or use a native app and give it access to your directory? If this is not the way you want to use it, you need to give me more context on your use-case scenario.

**Comment by gregjhogan** [comment]
I have a service principal that shouldn't need access to the graph API.  I want to use a powershell runbook to perform some tasks.  I want to give the service principal the least privileges necessary.  It seems like the REST API returns a descriptive error message when an invalid object ID is passed, so it doesn't make any sense to me that this extra object ID validation is necessary.  I guess we will just have to agree to disagree.

**Comment by pomortaz** [comment]
@gregjhogan you can pass [BypassObjectIdValidation ](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/KeyVault/Commands.KeyVault/Commands/SetAzureKeyVaultAccessPolicy.cs#L180) to bypass object ID validation.

**Comment by gregjhogan** [comment]
@pomortaz perfect, thanks!

**Comment by JPRuskin** [comment]
An updated link for anyone coming across this now: [BypassObjectIdValidation](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/KeyVault/Commands.KeyVault/Commands/SetAzureKeyVaultAccessPolicy.cs#L288)
