### ISSUE TITLE
Cannot select ARM subscription on different tennant

### ISSUE THREAD

**Issue by danielstocker** [Azure/azure-powershell#2659]
Selecting an ARM subscription with the following cmdlet leads to the below error 

Add-AzureRMAccount 

Environment           : AzureCloud
Account               : UserAccount
TenantId              : <Tenant 1>
SubscriptionId        : <Subscription 1>
SubscriptionName      : Sub1
CurrentStorageAccount :

Select-AzureRMSubscription –SubscriptionId <Subscription 2 on Tenant 2> -verbose -debug

Set-AzureRmContext : Cannot validate argument on parameter 'SubscriptionId'. The argument "c4cfa555-b6c5-4151-86a0-29f03da5bbae" does not belong to the set 
"372bfbca-9d07-4a9a-b72a-9342aea1ae46" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
At line:1 char:44
+ ... cription –SubscriptionId c4cfa555-b6c5-4151-86a0-29f03da5bbae -verbos ...
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzureRmContext], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand

Select-AzureRMSubscription –SubscriptionName <Name of subscription 2>

completes with 

Environment           : AzureCloud
Account               : UserAccount
TenantId              : <Tenant 2>
SubscriptionId        :<Subscription 2>
SubscriptionName      : Sub2
CurrentStorageAccount :

**Comment by danielstocker** [comment]
[https://github.com/Azure/azure-powershell/issues/2554](https://github.com/Azure/azure-powershell/issues/2554) seems to be very similar

**Comment by cormacpayne** [comment]
Same issue as https://github.com/Azure/azure-powershell/issues/2554
