### ISSUE TITLE
Need command to allow storage account name checking

### ISSUE THREAD

**Issue by thejamesmarq** [Azure/azure-powershell#2666]
Using Get-AzureStorageAccount this was easy as a resource group didn't need to be provided.

However, now that I need to provide a resource group name in Get-AzureRmStorageAccount I can't check to see if the storage account exists in another resource group.

**Comment by blueww** [comment]
You can just run "Get-AzureRmStorageAccount" without resource group and account name, then you can see all storage account in the subscription.

**Comment by blueww** [comment]
Close the issue as has already provided the workaround, and not receive any feedback for a long time.
Feel free t reopen if necessary.
