### ISSUE TITLE
Set-AzureServiceDiagnosticsExtension fails if servicenames are two letters long

### ISSUE THREAD

**Issue by Karamell** [Azure/azure-powershell#267]
`Set-AzureServiceDiagnosticsExtension -servicename ab `
fails with
`The storage account name 'ab' is invalid.  Storage account names must be between 3 and 24 characters in length`

even if the storagename is `abcdefg`

It seems like the validation is done on the servicename instead of the storagename parameter

**Comment by singhkays** [comment]
@hyonholee Did #2682 fix this? Can we close this?
