### ISSUE TITLE
Get-AzResource doesn't work with resource groups

### ISSUE THREAD

**Issue by wboyd-aw** [Azure/azure-powershell#26798]
### Description

Get-AzResource doesn't work when providing the resource id of a resource group, it results in this error:

`Get-AzResource: Invalid format of the resource identifier. (Parameter 'idFromServer')`

### Issue script & Debug output

```PowerShell
Get-AzResource -ResourceId '/subscriptions/{subscriptionId}/resourceGroups/{name}'

DEBUG: 9:50:34 AM - [ResourceManagerCmdletBase.ExecuteCmdlet] Caught unhandled exception: System.ArgumentException: Invalid format of the resource identifier. (Parameter 'idFromServer')
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Components.ResourceIdentifier..ctor(String idFromServer)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.GetById(String resourceId, String apiVersion)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet.OnProcessRecord()
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
DEBUG: 9:50:34 AM - [ConfigManager] Got nothing from [EnableErrorRecordsPersistence], Module = [], Cmdlet = []. Returning default value [False].
Get-AzResource: Invalid format of the resource identifier. (Parameter 'idFromServer')
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
7.1.0 Az.Resources
```

### Error output

```PowerShell
Error doesn't show up when running `Resolve-AzError`
```

**Comment by Nickcandy** [comment]
Hi @wboyd-aw,
The `Get-AzResource` command does not currently support retrieving resource groups; it only returns specific resources. The resource IDs it retrieves are split by `/` and have a minimum length of 8. If you need to get resource groups, please use the `Get-AzResourceGroup` command instead.

**Comment by Nickcandy** [comment]
Thank you for your follow-up! Currently, there are no plans for Get-AzResource to support resource groups, as this separation is by design. The Get-AzResourceGroup command is specifically intended for handling resource group operations, ensuring clear functionality and optimized performance for both commands.

It's great to hear that Get-AzResourceGroup -Id worked for your scenario! If you have any additional questions or need further assistance, feel free to reach out.
