### ISSUE TITLE
Creating Media Services account via Resource Manager

### ISSUE THREAD

**Issue by gunndabad** [Azure/azure-powershell#2681]
Is there a way to create a Media Services account with Powershell using the new Resource Manager style (New-AzureRmResource perhaps?) instead of the Classic style? I've been unable to find any information about doing it this way.

**Comment by markcowl** [comment]
@myefforts As it happens, typed cmdlets for Media Service account management are being added in the August release.  See the latest PR here: https://github.com/Azure/azure-powershell/pull/2577

**Comment by markcowl** [comment]
Meanwhile, even if there aren't typed cmdlets, if you know what the REST API looks like, you can always use generic cmdlets to create resources. See [New-AzureRMResource](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Resource/NewAzureResourceCmdlet.cs)

**Comment by markcowl** [comment]
@fredericky You have some fans

**Comment by fredericky** [comment]
@markcowl , great!

**Comment by cormacpayne** [comment]
This issue has been resolved. Closing.
