### ISSUE TITLE
Provide progress and speed report for deployment upload

### ISSUE THREAD

**Issue by slav** [Azure/azure-powershell#2685]
Hello. We've run multiple times into the issue of deployment to cloud service taking too long. After working with Azure Support we found the issue was network related, specifically related to the speed of upload.

Is there any way you could add support for when file is being uploaded to report % uploaded and average upload speed at specified intervals? This will greatly help to first see the progress of the deployment, but also to diagnose where the issue lies.

**Comment by markcowl** [comment]
@singhkay Can you take a look.  @slav excellent suggestion, is this for RDFE deployments to cloud service?

**Comment by slav** [comment]
@markcowl - Not fi RDFE is used for deployment.s.

The scripts goes something like this:
```
Set-AzureSubscription -SubscriptionName "$subscription" -CurrentStorageAccount $storageAccount
Select-AzureSubscription -SubscriptionName "$subscription" -Current
Set-AzureDeployment -Upgrade -Slot $slot -Package $package -Configuration $configuration -label $deploymentLabel -ServiceName $service -Force
```

**Comment by singhkays** [comment]
@slav This is a good idea but to set expectations, realistically this will be on the backlog due to limited resources.

**Comment by maddieclayton** [comment]
@singhkays If you are not planning to do this work, please close this issue.

**Comment by singhkays** [comment]
Checked with the Cloud Services PaaS team. There are no plans to implement this.
