### ISSUE TITLE
[Eng]: Does Azure Powershell support authenticated proxy for Kerberos/NTLM authentication

### ISSUE THREAD

**Issue by Liyun-Test** [Azure/azure-powershell#26873]
### Description

Raise the ticket on behalf of customer:

Background: As Azure CLI does not support Kerberos/NLTM authentication behind authenticated proxy, the customer would like to know if there are any alternatives like Azure Powershell.

Ask: Does Azure Powershell support Kerberos/NLTM authentication behind authenticated proxy?

ref: 
https://learn.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-13.0.0
https://learn.microsoft.com/en-us/powershell/azure/az-powershell-proxy?view=azps-13.0.0&viewFallbackFrom=azps-12.4.0
https://github.com/Azure/azure-powershell/issues/26402

**Comment by Liyun-Test** [comment]
May I have any update on the issue above? Thanks.

**Comment by isra-fel** [comment]
Hi @Liyun-Test , on Windows, Azure PowerShell basically follows OS's proxy settings. I'm unfamiliar with Kerberos/NTLM, but if it works on the OS-level, the Azure PowerShell should work as well.

**Comment by Liyun-Test** [comment]
Well noted. Thanks Yeming.


Best Regards,

Liyun Zhu

________________________________
