### ISSUE TITLE
Update logic for caching tenants and listing subscriptions

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2693]
### Description

Currently the cached tenant list can contain both domain names and tenantIds, and we cannot distinguish when a tenantId and domain name are equivalent, which sometimes results in subscriptiosn being listed twice in Get-AzureRmSubscription, or not being listed at all.

To resolve this, do the following:
- [ ] Add an 'extensions' dictionary (IDictionary<string, string>) to add azure account,
- [ ] When logging in with no TenantId specified, populate the key 'CommonTenantId' in this dictionary and the tenants list as usual
- [ ] When logging in with a TenantId specified, wipe out the CommonTenantId setting, do not set CommonTenantId, and add the tenant to the list of subscripsion (using the tenant id from the token)
- [ ] When logging in, update the logic for caching the Tenant list by using only tenant Ids obtained from the token, and when each tenant is added, eensure it ins unique
- [ ] When logging in with a domain name, use an additional hop to authenticate with the tenant id from the token.  This will enable using tenant id and domain name interchangeably in the login command.
- [ ] When listing subscriptions, use the following logic:
  - [ ] If 'CommonTenantId'  is set in Account.Extensions, obtain a token for the specified tenant, list tenants using this token (or simply use the common tenant as the tenant list if no tenants are returned or there is an error), obtain a token for each tenant, and list subscriptions
  - [ ] If 'CommonTenantId' is not set and there is a Tenants list, obtain a token for each tenant and list subscriptions
  - [ ] If 'CommonTenantId is not set and there is no Tenants list, obtain a token against 'Common', list tenants, obtain a token against each tenant, and list subscriptions
 - [ ] If authentication fails against a tenant, or all subscriptions in a tenant are in the 'Not Defined', 'Disabled', or 'Deleted' state, remove the tenant from the tenant list, warn the user,and do not list these subscriptions.
- [ ] Ensure that automated unit tests cover each of these scenarios

**Comment by markcowl** [comment]
See #2209 for a repro of this issue

**Comment by maddieclayton** [comment]
Done, or covered by other issues.
