### ISSUE TITLE
Add pull request temaplate to the repo

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2694]
### Description

Include a checklist with checkoboxes for the important features of a pull request.  Circulate to partners that this is what we expect, and make them check all the boxes before we look at the pull request.

See:  https://github.com/blog/2111-issue-and-pull-request-templates for how to specify a pull request template

### Cost: 2

**Comment by cormacpayne** [comment]
Addressed in PR https://github.com/Azure/azure-powershell/pull/2782
