### ISSUE TITLE
Add issue template to the repo

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2695]
### Description
Add an issue template, with necessary details we ask for when reporting bugs (Debug output, powershell version [and how to obtain it], module version [and how to obtain it], description, repro script, os version)

See https://github.com/blog/2111-issue-and-pull-request-templates  for a description of how to add Issue Templates

###Cost: 1

**Comment by cormacpayne** [comment]
Addressed in PR https://github.com/Azure/azure-powershell/pull/2788
