### ISSUE TITLE
New-AzureResourceGroupDeployment handles bad inputs / parameters in a confusing way

### ISSUE THREAD

**Issue by clamanna** [Azure/azure-powershell#270]
Givung the cmdlet the ResourceGroupName parameter and nothing else yields:

 PS C:\WINDOWS\system32> New-AzureResourceGroupDeployment -ResourceGroupName testkay
 New-AzureResourceGroupDeployment : Accessed JArray values with invalid key value: "identity". Array position index expected.
 At line:1 char:1
 + New-AzureResourceGroupDeployment -ResourceGroupName testkay
 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 + CategoryInfo : CloseError: (:) [New-AzureResourceGroupDeployment], ArgumentException
 + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

**Comment by ravbhatnagar** [comment]
Now it fails with the following message which is still not meaningful. 
PS C:\WINDOWS\system32> New-AzureRmResourceGroupDeployment -ResourceGroupName temprg1
New-AzureRmResourceGroupDeployment : Value cannot be null.
Parameter name: path
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -ResourceGroupName temprg1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], ArgumentNullException
    + FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

**Comment by ravbhatnagar** [comment]
Moving to backlog. Could not fix in Apr release
