### ISSUE TITLE
Update Implementation of confirmation for storage cmdlets with Force deprectaion warning and ComfirmImpact.High

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2702]
The following cmdlets are listed as having ConfirmImapct.High and a deprecation warning.  They need to have the standard ConfirmImpact (ConfirmImpact.Medium) and remove usage of the Force parameter:

RemoveAzureStorageTableStoredAccessPolicy
RemoveAzureStorageQueueStoredAccessPolicy
RemoveAzureStorageShareStoredAccessPolicy
RemoveAzureStorageContainerStoredAccessPolicy

@blueww Let's discuss the best way to make this happen.

**Comment by blueww** [comment]
@markcowl 
I have already remove the force parameter and warning message, and set it to default ComfirmImpact, use Shouldprocess with PR https://github.com/Azure/azure-powershell/pull/2672/files  

After my PR is merged, the warning message are added back with the PR https://github.com/Azure/azure-powershell/pull/2676 by cormacpayne 

As we talked, you will fix it and remove the warning message.
thanks!

**Comment by markcowl** [comment]
Fixed in pr #2708
