### ISSUE TITLE
Set-AzureStorageBlobContent gives 'The remote server returned an error: (400) Bad Request'

### ISSUE THREAD

**Issue by avishnyakov** [Azure/azure-powershell#2719]
Hello team, 

We started to have the following issue while using Set-AzureStorageBlobContent with:
* AzureRM module [1.5.1] 
* AzureRM module [1.6.0] 

```
Set-AzureStorageBlobContent : The remote server returned an error: (400) Bad Request. HTTP Status Code: 
400 - HTTP Error Message: Value for one of the query parameters specified in the request URI is invalid.
At 4
+ ...   $result = Set-AzureStorageBlobContent -Container "scripts" -File $f ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureStorageBlobContent], StorageException
    + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands.Storage.Blob.SetAzureBlobCo 
   ntentCommand
```

Anything changed with the recent updates?

PUT request seems to be alright as per the REST api:
https://msdn.microsoft.com/en-us/library/azure/dd179451.aspx
```
PUT https://z-y-z.blob.core.windows.net/scripts/my-script.ps1?comp=block&blockid=someblockidhere&timeout=300 HTTP/1.1
```
Not too sure why the result is "HTTP/1.1 400 Value for one of the query parameters specified in the request URI is invalid."

**Comment by markcowl** [comment]
@blueww can you take a look?

**Comment by avishnyakov** [comment]
Seems it has to do with the premium storage. I'll have a look and run it against standard storage (must work!) but it fails right now on the premium storage.

**Comment by blueww** [comment]
The premium storage only support page blob, so you need to set "-BlobType Page", or the default blob type is block and not supported by premium storage.

**Comment by avishnyakov** [comment]
Nice! That was the suspicion. We use blob storage to push PS script via Set-AzureRmVMCustomScriptExtension. Means, if we host VMs on the premium storage, we still need a temporary blob storage (non-premium) to get Set-AzureRmVMCustomScriptExtension up and running.

Thanks for clarification, @blueww 

Guess, the ticket might be closed or a better exception or error message might be added to the cmdlet. Either way, thank you all for looking into it.

**Comment by mokanya** [comment]
> The premium storage only support page blob, so you need to set "-BlobType Page", or the default blob type is block and not supported by premium storage.

Hello @blueww,
How do we implement your recommendation this issue, am getting similar error and i dont know where to make the changes. Can you kindly guide me please?

see below..

02:42:52 - VERBOSE: Performing the operation "Create Archive" on target 
02:42:52 - "C:\Users\labadmin\2TierAzureMigration\WebVM-SQLVM-ARMDeploy\AzureResourceGroup44\bin\Debug\staging\AzureResourceGroup4
02:42:52 - 4\DSC\SQLDSC.zip".
02:42:52 - VERBOSE: Temp folder 'C:\Users\labadmin\AppData\Local\Temp\2\55bbbc36-636a-4332-bc48-d53de99fc4aa' created.
02:42:52 - VERBOSE: Copy 
02:42:52 - 'C:\Users\labadmin\2TierAzureMigration\WebVM-SQLVM-ARMDeploy\AzureResourceGroup44\bin\Debug\staging\AzureResourceGroup4
02:42:52 - 4\DSC\SQLDSC.ps1' to 'C:\Users\labadmin\AppData\Local\Temp\2\55bbbc36-636a-4332-bc48-d53de99fc4aa\SQLDSC.ps1'.
02:42:52 - VERBOSE: Parsing configuration script: 
02:42:52 - C:\Users\labadmin\2TierAzureMigration\WebVM-SQLVM-ARMDeploy\AzureResourceGroup44\bin\Debug\staging\AzureResourceGroup44
02:42:52 - \DSC\SQLDSC.ps1
02:42:52 - VERBOSE: List of required modules: [].
02:42:52 - VERBOSE: Deleted 'C:\Users\labadmin\AppData\Local\Temp\2\55bbbc36-636a-4332-bc48-d53de99fc4aa'
02:42:53 - VERBOSE: Performing the operation "Create Archive" on target 
02:42:53 - "C:\Users\labadmin\2TierAzureMigration\WebVM-SQLVM-ARMDeploy\AzureResourceGroup44\bin\Debug\staging\AzureResourceGroup4
02:42:53 - 4\DSC\WebDSC.zip".
02:42:53 - VERBOSE: Temp folder 'C:\Users\labadmin\AppData\Local\Temp\2\8332bbee-b2c2-4b7f-8e40-7eb07a688b8a' created.
02:42:53 - VERBOSE: Copy 
02:42:53 - 'C:\Users\labadmin\2TierAzureMigration\WebVM-SQLVM-ARMDeploy\AzureResourceGroup44\bin\Debug\staging\AzureResourceGroup4
02:42:53 - 4\DSC\WebDSC.ps1' to 'C:\Users\labadmin\AppData\Local\Temp\2\8332bbee-b2c2-4b7f-8e40-7eb07a688b8a\WebDSC.ps1'.
02:42:53 - VERBOSE: Parsing configuration script: 
02:42:53 - C:\Users\labadmin\2TierAzureMigration\WebVM-SQLVM-ARMDeploy\AzureResourceGroup44\bin\Debug\staging\AzureResourceGroup44
02:42:53 - \DSC\WebDSC.ps1
02:42:53 - VERBOSE: List of required modules: [].
02:42:53 - VERBOSE: Deleted 'C:\Users\labadmin\AppData\Local\Temp\2\8332bbee-b2c2-4b7f-8e40-7eb07a688b8a'
02:42:57 - Set-AzureStorageBlobContent : The remote server returned an error: (400) Bad Request. HTTP Status Code: 400 - HTTP 
02:42:57 - Error Message: Block blobs are not supported.
02:42:57 - At C:\Users\labadmin\2TierAzureMigration\WebVM-SQLVM-ARMDeploy\AzureResourceGroup44\bin\Debug\staging\AzureResourceGrou
02:42:57 - p44\Deploy-AzureResourceGroup.ps1:81 char:9
02:42:57 - +         Set-AzureStorageBlobContent -File $SourcePath -Blob $SourcePa ...
02:42:57 - +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
02:42:57 -     + CategoryInfo          : CloseError: (:) [Set-AzureStorageBlobContent], StorageException
02:42:57 -     + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands.Storage.Blob.SetAzureBlobContentCommand
02:42:57 -  
02:42:57 - Deploying template using PowerShell script failed.
02:42:57 - Tell us about your experience at https://go.microsoft.com/fwlink/?LinkId=691202

**Comment by blueww** [comment]
@mokanya 

If you are upload blob to a premium storage account , you can try to add parameter  "-BlobType Page" to Set-AzStorageBlobContent. 
If this does not work, this might be other issue, and please open a new issue by follow the issue teamplate.
