### ISSUE TITLE
SaveAzureWebsiteLogWithNoFileExtenstionTest failing in build system

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#2729]
Temporarily disabling SaveAzureWebsiteLogWithNoFileExtenstionTest due to it failing in the build system.

Skip was added on line 103 of  src/ServiceManagement/Services/Commands.Test/Websites/SaveAzureWebsiteLogTests.cs

Need to look into re-designing the test so that this failure doesn't occur for PRs not touching Websites.

**Comment by markcowl** [comment]
Hasn't been an issue for a while, closing
