### ISSUE TITLE
WebsiteContextBaseCmdlet.ExecuteCmdLet() doesn't check if GitWebsite is null

### ISSUE THREAD

**Issue by SirEel** [Azure/azure-powershell#273]
Executing Get-AzureWebJob without supplying a -Name parameter can cause an unhandled exception, "Git not found. Please install git and place it in your command line path."  See http://stackoverflow.com/questions/29111804/powershell-get-azurewebsitejob-error-git-not-found/29123370#29123370

This is because WebsiteContextBaseCmdlet.ExecuteCmdlet() tries to supply a value for -Name by invoking GitWebsite.ReadConfiguration().Name, even though GitWebsite may be null. See https://github.com/Azure/azure-powershell/blob/master/src/ServiceManagement/Services/Commands.Utilities/Websites/Common/WebsiteContextBaseCmdlet.cs

WebsiteContextBaseCmdlet.ExecuteCmdlet() should check if GitWebsite is null and, if so, either throw an exception explicitly stating the problem is the missing -Name parameter, or prompt for the parameter.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
