### ISSUE TITLE
Add-AzureRmAccount only checks certs in Cert::LocalMachine\my

### ISSUE THREAD

**Issue by jchengit** [Azure/azure-powershell#2731]
It seems Add-AzureRmAccount only checks certs in Cert::LocalMachine\my. How do I tell it to search for other path, e.g. "Cert:\LocalMachine"?

Below is what I have, am I missing something? Is this the right way to authenticate a service principal? 

Add-AzureRmAccount -ServicePrincipal -CertificateThumbprint $cert.Thumbprint -ApplicationId $applicationId -TenantId $tenantid

**Comment by markcowl** [comment]
It should be looking in both LocaMachine\My and CurrentUser\My for the certificate mathcing the thumbprint you specify

**Comment by jchengit** [comment]
Is it possible to configure it check a given path (e.g. "Cert:\LocalMachine") recursively?

**Comment by markcowl** [comment]
@jchengit What is the scenario in which you want to use a cert not in CurrentUser\My or LocalMachine\My?

**Comment by markcowl** [comment]
Ask is for using certs from an arbitrary store, or providing a mechanism to allow certs outside the My stores.

**Comment by markcowl** [comment]
Closing due to lack of user comments.  Please reopen if this is still an issue
