### ISSUE TITLE
Powershell script to give access to Azure Active Directory

### ISSUE THREAD

**Issue by manushamallela** [Azure/azure-powershell#2745]
Can we write a powershell script to give access to Azure active directory using the asset. In asset we are storing the User Credentials.
I created a runbook, and to deploy the Azure Runbook in new subscritption I created a service principal My question here is that, will I be able to use the asset ( created with user's credentials) to give access to active directory for new Subscription ?
I do not want the user to manually enter the credentials to deploy the runbook.

Thanks.

**Comment by markcowl** [comment]
@manushamallela Is this question about Azure Azutomation service, or about Azure PowerShell on the desktop?

**Comment by markcowl** [comment]
Closing as there has been no response, please open a new issue if you are still seeing an issue
