### ISSUE TITLE
AzureRM.Automation Cmdlets hard coded Serialization Depth set to 10

### ISSUE THREAD

**Issue by robplank** [Azure/azure-powershell#2750]
Please allow users to override the serialization depth, complex objects don't always serialize to a depth of 10.

in Common\Constants.cs 
these settings are set to a constant
public const string PsCommandConvertToJson = "ConvertTo-Json";
public const string PsCommandConvertFromJson = "ConvertFrom-Json";
public const string PsCommandParamInputObject = "InputObject";
public const string PsCommandParamDepth = "Depth";
public const int PsCommandValueDepth = 10;

Please add an optional Parameter to all cmdlets that use PsCommandConvertToJson to allow the user to select their desired depth, please feel free to leave the default set to 10.

**Comment by maddieclayton** [comment]
@vrdmr Can you take a look at this feature request?

**Comment by GaneshMSAzure** [comment]
Won't fix
