### ISSUE TITLE
Add signing build that creates tags for release-1.2.4 branch

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2765]
### Description

Create a signing build that tags the branch

### Cost: 1

**Comment by cormacpayne** [comment]
@markcowl Added Jenkins job "ps-stack-sign" which is a copy of the signed job already used for PowerShell, but creates and publishes a tag to the repository with the timestamp.

**Comment by markcowl** [comment]
Fixed, job is here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/ps-stack-sign/
