### ISSUE TITLE
PowerShell does not allow the creation of resource groups with parenthesis...

### ISSUE THREAD

**Issue by danielstocker** [Azure/azure-powershell#2768]
...this is not compliant with the published documentation:

https://msdn.microsoft.com/en-us/library/azure/dn790546.aspx

_"{resource-group-name} must uniquely identify the resource group within the subscription. It must be no longer than 80 characters long. It can only contain alphanumeric characters, dash, underscore, opening parenthesis, closing parenthesis or period. The name cannot end with a period."_

The portal and the REST API allow the creation of resource groups that contain parenthesis.

**Comment by danielstocker** [comment]
![test](https://cloud.githubusercontent.com/assets/9444698/17633019/49eb6eaa-60c3-11e6-82cc-cd5d06179f01.jpg)
![test-cli](https://cloud.githubusercontent.com/assets/9444698/17633020/49f88c7a-60c3-11e6-8517-c7233b8712e5.jpg)

**Comment by danielstocker** [comment]
[Similar issue with CLI](https://github.com/Azure/azure-xplat-cli/issues/3109)

**Comment by markcowl** [comment]
@vivsriaus can you take a look?

**Comment by ravbhatnagar** [comment]
Fixed.
