### ISSUE TITLE
Get-AzureSubscription makes PowerShell ISE window alternate focus

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#277]
# Scenario

* Dell Latitude E6430
* Windows 8.1 with Update (fully patched)
* Windows Management Framework (WMF) Core / PowerShell February 2015 Preview
* Azure PowerShell module 0.8.15.1

# Problem

When calling the `Get-AzureSubscription` command inside the PowerShell ISE, the ISE window loses focus, and regains focus. It repeats this seemingly once for each Azure subscription that the account has access to.

## Reproduction Steps

1. Open a new PowerShell ISE window
2. Run the `Add-AzureAccount` command (if necessary)
3. Run the `Get-AzureSubscription` command
4. Notice that the PowerShell ISE window "flashes" (loses / regains focus)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 I believe this is by design.  We are updating the subscription list from ARM when Get-AzureSubscription is executed, and the remote call makes the window lose focus.

**Comment by pcgeek86** [comment]
@markcowl But why does the PowerShell window lose and regain focus? That is "by design?"

I'm trying to understand how this is desirable behavior. Can you help explain? 

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by pcgeek86** [comment]
@markcowl I can't re-open this issue myself. Can you please re-open it?

Looks like I can't re-open it due to the way GitHub permissions work: http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
