### ISSUE TITLE
Aliases are accumulating with each new Azure PS version

### ISSUE THREAD

**Issue by matt1883** [Azure/azure-powershell#2773]
It looks like with each new release of Azure PS, duplicate aliases for Data Lake Store & Analytics are accumulating. See below.

This does not seem to affect cmdlets – just aliases.

Do you know what is causing this, or how we can fix it?

PS C:> Get-Command Test-AdlStoreItem

CommandType     Name                                               Version    Source

---

Alias           Test-AdlStoreItem                                  2.0.1      AzureRM.DataLakeStore
Alias           Test-AdlStoreItem                                  2.0.0      AzureRM.DataLakeStore
Alias           Test-AdlStoreItem                                  1.0.11     AzureRM.DataLakeStore
Alias           Test-AdlStoreItem                                  1.0.9      AzureRM.DataLakeStore

PS C:> Get-Command _-Adl_

CommandType     Name                                               Version    Source

---

Alias           Add-AdlAnalyticsDataSource                         2.0.1      AzureRM.DataLakeAnalytics
Alias           Add-AdlAnalyticsDataSource                         2.0.0      AzureRM.DataLakeAnalytics
Alias           Add-AdlAnalyticsDataSource                         1.1.3      AzureRM.DataLakeAnalytics
Alias           Add-AdlAnalyticsDataSource                         1.1.1      AzureRM.DataLakeAnalytics
Alias           Add-AdlStoreItemContent                            2.0.1      AzureRM.DataLakeStore
Alias           Add-AdlStoreItemContent                            2.0.0      AzureRM.DataLakeStore
Alias           Add-AdlStoreItemContent                            1.0.11     AzureRM.DataLakeStore
Alias           Add-AdlStoreItemContent                            1.0.9      AzureRM.DataLakeStore
Alias           Export-AdlStoreItem                                2.0.1      AzureRM.DataLakeStore
Alias           Export-AdlStoreItem                                2.0.0      AzureRM.DataLakeStore
Alias           Export-AdlStoreItem                                1.0.11     AzureRM.DataLakeStore
Alias           Export-AdlStoreItem                                1.0.9      AzureRM.DataLakeStore
Alias           Get-AdlAnalyticsAccount                            2.0.1      AzureRM.DataLakeAnalytics
Alias           Get-AdlAnalyticsAccount                            2.0.0      AzureRM.DataLakeAnalytics
Alias           Get-AdlAnalyticsAccount                            1.1.3      AzureRM.DataLakeAnalytics
Alias           Get-AdlAnalyticsAccount                            1.1.1      AzureRM.DataLakeAnalytics
Alias           Get-AdlAnalyticsDataSource                         2.0.1      AzureRM.DataLakeAnalytics
Alias           Get-AdlAnalyticsDataSource                         2.0.0      AzureRM.DataLakeAnalytics
Alias           Get-AdlAnalyticsDataSource                         1.1.3      AzureRM.DataLakeAnalytics
Alias           Get-AdlAnalyticsDataSource                         1.1.1      AzureRM.DataLakeAnalytics
Alias           Get-AdlCatalogItem                                 2.0.1      AzureRM.DataLakeAnalytics
Alias           Get-AdlCatalogItem                                 2.0.0      AzureRM.DataLakeAnalytics
Alias           Get-AdlCatalogItem                                 1.1.3      AzureRM.DataLakeAnalytics
Alias           Get-AdlCatalogItem                                 1.1.1      AzureRM.DataLakeAnalytics
Alias           Get-AdlJob                                         2.0.1      AzureRM.DataLakeAnalytics
Alias           Get-AdlJob                                         2.0.0      AzureRM.DataLakeAnalytics
Alias           Get-AdlJob                                         1.1.3      AzureRM.DataLakeAnalytics
Alias           Get-AdlJob                                         1.1.1      AzureRM.DataLakeAnalytics
Alias           Get-AdlStore                                       2.0.1      AzureRM.DataLakeStore
Alias           Get-AdlStore                                       2.0.0      AzureRM.DataLakeStore
Alias           Get-AdlStore                                       1.0.11     AzureRM.DataLakeStore
Alias           Get-AdlStore                                       1.0.9      AzureRM.DataLakeStore
Alias           Get-AdlStoreChildItem                              2.0.1      AzureRM.DataLakeStore
Alias           Get-AdlStoreChildItem                              2.0.0      AzureRM.DataLakeStore
Alias           Get-AdlStoreChildItem                              1.0.11     AzureRM.DataLakeStore
Alias           Get-AdlStoreChildItem                              1.0.9      AzureRM.DataLakeStore
Alias           Get-AdlStoreItem                                   2.0.1      AzureRM.DataLakeStore
Alias           Get-AdlStoreItem                                   2.0.0      AzureRM.DataLakeStore
Alias           Get-AdlStoreItem                                   1.0.11     AzureRM.DataLakeStore
Alias           Get-AdlStoreItem                                   1.0.9      AzureRM.DataLakeStore
Alias           Get-AdlStoreItemAcl                                2.0.1      AzureRM.DataLakeStore
Alias           Get-AdlStoreItemAcl                                2.0.0      AzureRM.DataLakeStore
Alias           Get-AdlStoreItemAcl                                1.0.11     AzureRM.DataLakeStore
Alias           Get-AdlStoreItemAcl                                1.0.9      AzureRM.DataLakeStore
Alias           Get-AdlStoreItemContent                            2.0.1      AzureRM.DataLakeStore
Alias           Get-AdlStoreItemContent                            2.0.0      AzureRM.DataLakeStore
Alias           Get-AdlStoreItemContent                            1.0.11     AzureRM.DataLakeStore
Alias           Get-AdlStoreItemContent                            1.0.9      AzureRM.DataLakeStore
Alias           Get-AdlStoreItemOwner                              2.0.1      AzureRM.DataLakeStore
Alias           Get-AdlStoreItemOwner                              2.0.0      AzureRM.DataLakeStore
Alias           Get-AdlStoreItemOwner                              1.0.11     AzureRM.DataLakeStore
Alias           Get-AdlStoreItemOwner                              1.0.9      AzureRM.DataLakeStore
Alias           Import-AdlStoreItem                                2.0.1      AzureRM.DataLakeStore
Alias           Import-AdlStoreItem                                2.0.0      AzureRM.DataLakeStore
Alias           Import-AdlStoreItem                                1.0.11     AzureRM.DataLakeStore
Alias           Import-AdlStoreItem                                1.0.9      AzureRM.DataLakeStore
Alias           Join-AdlStoreItem                                  2.0.1      AzureRM.DataLakeStore
Alias           Join-AdlStoreItem                                  2.0.0      AzureRM.DataLakeStore
Alias           Join-AdlStoreItem                                  1.0.11     AzureRM.DataLakeStore
Alias           Join-AdlStoreItem                                  1.0.9      AzureRM.DataLakeStore
Alias           Move-AdlStoreItem                                  2.0.1      AzureRM.DataLakeStore
Alias           Move-AdlStoreItem                                  2.0.0      AzureRM.DataLakeStore
Alias           Move-AdlStoreItem                                  1.0.11     AzureRM.DataLakeStore
Alias           Move-AdlStoreItem                                  1.0.9      AzureRM.DataLakeStore
Alias           New-AdlAnalyticsAccount                            2.0.1      AzureRM.DataLakeAnalytics
Alias           New-AdlAnalyticsAccount                            2.0.0      AzureRM.DataLakeAnalytics
Alias           New-AdlAnalyticsAccount                            1.1.3      AzureRM.DataLakeAnalytics
Alias           New-AdlAnalyticsAccount                            1.1.1      AzureRM.DataLakeAnalytics
Alias           New-AdlCatalogSecret                               2.0.1      AzureRM.DataLakeAnalytics
Alias           New-AdlCatalogSecret                               2.0.0      AzureRM.DataLakeAnalytics
Alias           New-AdlCatalogSecret                               1.1.3      AzureRM.DataLakeAnalytics
Alias           New-AdlCatalogSecret                               1.1.1      AzureRM.DataLakeAnalytics
Alias           New-AdlStore                                       2.0.1      AzureRM.DataLakeStore
Alias           New-AdlStore                                       2.0.0      AzureRM.DataLakeStore
Alias           New-AdlStore                                       1.0.11     AzureRM.DataLakeStore
Alias           New-AdlStore                                       1.0.9      AzureRM.DataLakeStore
Alias           New-AdlStoreItem                                   2.0.1      AzureRM.DataLakeStore
Alias           New-AdlStoreItem                                   2.0.0      AzureRM.DataLakeStore
Alias           New-AdlStoreItem                                   1.0.11     AzureRM.DataLakeStore
Alias           New-AdlStoreItem                                   1.0.9      AzureRM.DataLakeStore
Alias           Remove-AdlAnalyticsAccount                         2.0.1      AzureRM.DataLakeAnalytics
Alias           Remove-AdlAnalyticsAccount                         2.0.0      AzureRM.DataLakeAnalytics
Alias           Remove-AdlAnalyticsAccount                         1.1.3      AzureRM.DataLakeAnalytics
Alias           Remove-AdlAnalyticsAccount                         1.1.1      AzureRM.DataLakeAnalytics
Alias           Remove-AdlAnalyticsDataSource                      2.0.1      AzureRM.DataLakeAnalytics
Alias           Remove-AdlAnalyticsDataSource                      2.0.0      AzureRM.DataLakeAnalytics
Alias           Remove-AdlAnalyticsDataSource                      1.1.3      AzureRM.DataLakeAnalytics
Alias           Remove-AdlAnalyticsDataSource                      1.1.1      AzureRM.DataLakeAnalytics
Alias           Remove-AdlCatalogSecret                            2.0.1      AzureRM.DataLakeAnalytics
Alias           Remove-AdlCatalogSecret                            2.0.0      AzureRM.DataLakeAnalytics
Alias           Remove-AdlCatalogSecret                            1.1.3      AzureRM.DataLakeAnalytics
Alias           Remove-AdlCatalogSecret                            1.1.1      AzureRM.DataLakeAnalytics
Alias           Remove-AdlStore                                    2.0.1      AzureRM.DataLakeStore
Alias           Remove-AdlStore                                    2.0.0      AzureRM.DataLakeStore
Alias           Remove-AdlStore                                    1.0.11     AzureRM.DataLakeStore
Alias           Remove-AdlStore                                    1.0.9      AzureRM.DataLakeStore
Alias           Remove-AdlStoreItem                                2.0.1      AzureRM.DataLakeStore
Alias           Remove-AdlStoreItem                                2.0.0      AzureRM.DataLakeStore
Alias           Remove-AdlStoreItem                                1.0.11     AzureRM.DataLakeStore
Alias           Remove-AdlStoreItem                                1.0.9      AzureRM.DataLakeStore
Alias           Remove-AdlStoreItemAclEntry                        2.0.1      AzureRM.DataLakeStore
Alias           Remove-AdlStoreItemAclEntry                        2.0.0      AzureRM.DataLakeStore
Alias           Remove-AdlStoreItemAclEntry                        1.0.11     AzureRM.DataLakeStore
Alias           Remove-AdlStoreItemAclEntry                        1.0.9      AzureRM.DataLakeStore
Alias           Set-AdlAnalyticsAccount                            2.0.1      AzureRM.DataLakeAnalytics
Alias           Set-AdlAnalyticsAccount                            2.0.0      AzureRM.DataLakeAnalytics
Alias           Set-AdlAnalyticsAccount                            1.1.3      AzureRM.DataLakeAnalytics
Alias           Set-AdlAnalyticsAccount                            1.1.1      AzureRM.DataLakeAnalytics
Alias           Set-AdlAnalyticsDataSource                         2.0.1      AzureRM.DataLakeAnalytics
Alias           Set-AdlAnalyticsDataSource                         2.0.0      AzureRM.DataLakeAnalytics
Alias           Set-AdlAnalyticsDataSource                         1.1.3      AzureRM.DataLakeAnalytics
Alias           Set-AdlAnalyticsDataSource                         1.1.1      AzureRM.DataLakeAnalytics
Alias           Set-AdlCatalogSecret                               2.0.1      AzureRM.DataLakeAnalytics
Alias           Set-AdlCatalogSecret                               2.0.0      AzureRM.DataLakeAnalytics
Alias           Set-AdlCatalogSecret                               1.1.3      AzureRM.DataLakeAnalytics
Alias           Set-AdlCatalogSecret                               1.1.1      AzureRM.DataLakeAnalytics
Alias           Set-AdlStore                                       2.0.1      AzureRM.DataLakeStore
Alias           Set-AdlStore                                       2.0.0      AzureRM.DataLakeStore
Alias           Set-AdlStore                                       1.0.11     AzureRM.DataLakeStore
Alias           Set-AdlStore                                       1.0.9      AzureRM.DataLakeStore
Alias           Set-AdlStoreItemAcl                                2.0.1      AzureRM.DataLakeStore
Alias           Set-AdlStoreItemAcl                                2.0.0      AzureRM.DataLakeStore
Alias           Set-AdlStoreItemAcl                                1.0.11     AzureRM.DataLakeStore
Alias           Set-AdlStoreItemAcl                                1.0.9      AzureRM.DataLakeStore
Alias           Set-AdlStoreItemAclEntry                           2.0.1      AzureRM.DataLakeStore
Alias           Set-AdlStoreItemAclEntry                           2.0.0      AzureRM.DataLakeStore
Alias           Set-AdlStoreItemAclEntry                           1.0.11     AzureRM.DataLakeStore
Alias           Set-AdlStoreItemAclEntry                           1.0.9      AzureRM.DataLakeStore
Alias           Set-AdlStoreItemOwner                              2.0.1      AzureRM.DataLakeStore
Alias           Set-AdlStoreItemOwner                              2.0.0      AzureRM.DataLakeStore
Alias           Set-AdlStoreItemOwner                              1.0.11     AzureRM.DataLakeStore
Alias           Set-AdlStoreItemOwner                              1.0.9      AzureRM.DataLakeStore
Alias           Stop-AdlJob                                        2.0.1      AzureRM.DataLakeAnalytics
Alias           Stop-AdlJob                                        2.0.0      AzureRM.DataLakeAnalytics
Alias           Stop-AdlJob                                        1.1.3      AzureRM.DataLakeAnalytics
Alias           Stop-AdlJob                                        1.1.1      AzureRM.DataLakeAnalytics
Alias           Submit-AdlJob                                      2.0.1      AzureRM.DataLakeAnalytics
Alias           Submit-AdlJob                                      2.0.0      AzureRM.DataLakeAnalytics
Alias           Submit-AdlJob                                      1.1.3      AzureRM.DataLakeAnalytics
Alias           Submit-AdlJob                                      1.1.1      AzureRM.DataLakeAnalytics
Alias           Test-AdlAnalyticsAccount                           2.0.1      AzureRM.DataLakeAnalytics
Alias           Test-AdlAnalyticsAccount                           2.0.0      AzureRM.DataLakeAnalytics
Alias           Test-AdlAnalyticsAccount                           1.1.3      AzureRM.DataLakeAnalytics
Alias           Test-AdlAnalyticsAccount                           1.1.1      AzureRM.DataLakeAnalytics
Alias           Test-AdlCatalogItem                                2.0.1      AzureRM.DataLakeAnalytics
Alias           Test-AdlCatalogItem                                2.0.0      AzureRM.DataLakeAnalytics
Alias           Test-AdlCatalogItem                                1.1.3      AzureRM.DataLakeAnalytics
Alias           Test-AdlCatalogItem                                1.1.1      AzureRM.DataLakeAnalytics
Alias           Test-AdlStore                                      2.0.1      AzureRM.DataLakeStore
Alias           Test-AdlStore                                      2.0.0      AzureRM.DataLakeStore
Alias           Test-AdlStore                                      1.0.11     AzureRM.DataLakeStore
Alias           Test-AdlStore                                      1.0.9      AzureRM.DataLakeStore
Alias           Test-AdlStoreItem                                  2.0.1      AzureRM.DataLakeStore
Alias           Test-AdlStoreItem                                  2.0.0      AzureRM.DataLakeStore
Alias           Test-AdlStoreItem                                  1.0.11     AzureRM.DataLakeStore
Alias           Test-AdlStoreItem                                  1.0.9      AzureRM.DataLakeStore
Alias           Wait-AdlJob                                        2.0.1      AzureRM.DataLakeAnalytics
Alias           Wait-AdlJob                                        2.0.0      AzureRM.DataLakeAnalytics
Alias           Wait-AdlJob                                        1.1.3      AzureRM.DataLakeAnalytics
Alias           Wait-AdlJob                                        1.1.1      AzureRM.DataLakeAnalytics

PS C:> Get-Command _-AzureRmDataLake_

CommandType     Name                                               Version    Source

---

Cmdlet          Add-AzureRmDataLakeAnalyticsDataSource             2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Add-AzureRmDataLakeStoreItemContent                2.0.1      AzureRM.DataLakeStore
Cmdlet          Export-AzureRmDataLakeStoreItem                    2.0.1      AzureRM.DataLakeStore
Cmdlet          Get-AzureRmDataLakeAnalyticsAccount                2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Get-AzureRmDataLakeAnalyticsCatalogItem            2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Get-AzureRmDataLakeAnalyticsDataSource             2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Get-AzureRmDataLakeAnalyticsJob                    2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Get-AzureRmDataLakeStoreAccount                    2.0.1      AzureRM.DataLakeStore
Cmdlet          Get-AzureRmDataLakeStoreChildItem                  2.0.1      AzureRM.DataLakeStore
Cmdlet          Get-AzureRmDataLakeStoreItem                       2.0.1      AzureRM.DataLakeStore
Cmdlet          Get-AzureRmDataLakeStoreItemAcl                    2.0.1      AzureRM.DataLakeStore
Cmdlet          Get-AzureRmDataLakeStoreItemContent                2.0.1      AzureRM.DataLakeStore
Cmdlet          Get-AzureRmDataLakeStoreItemOwner                  2.0.1      AzureRM.DataLakeStore
Cmdlet          Import-AzureRmDataLakeStoreItem                    2.0.1      AzureRM.DataLakeStore
Cmdlet          Join-AzureRmDataLakeStoreItem                      2.0.1      AzureRM.DataLakeStore
Cmdlet          Move-AzureRmDataLakeStoreItem                      2.0.1      AzureRM.DataLakeStore
Cmdlet          New-AzureRmDataLakeAnalyticsAccount                2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          New-AzureRmDataLakeAnalyticsCatalogSecret          2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          New-AzureRmDataLakeStoreAccount                    2.0.1      AzureRM.DataLakeStore
Cmdlet          New-AzureRmDataLakeStoreItem                       2.0.1      AzureRM.DataLakeStore
Cmdlet          Remove-AzureRmDataLakeAnalyticsAccount             2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Remove-AzureRmDataLakeAnalyticsCatalogSecret       2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Remove-AzureRmDataLakeAnalyticsDataSource          2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Remove-AzureRmDataLakeStoreAccount                 2.0.1      AzureRM.DataLakeStore
Cmdlet          Remove-AzureRmDataLakeStoreItem                    2.0.1      AzureRM.DataLakeStore
Cmdlet          Remove-AzureRmDataLakeStoreItemAclEntry            2.0.1      AzureRM.DataLakeStore
Cmdlet          Set-AzureRmDataLakeAnalyticsAccount                2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Set-AzureRmDataLakeAnalyticsCatalogSecret          2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Set-AzureRmDataLakeAnalyticsDataSource             2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Set-AzureRmDataLakeStoreAccount                    2.0.1      AzureRM.DataLakeStore
Cmdlet          Set-AzureRmDataLakeStoreItemAcl                    2.0.1      AzureRM.DataLakeStore
Cmdlet          Set-AzureRmDataLakeStoreItemAclEntry               2.0.1      AzureRM.DataLakeStore
Cmdlet          Set-AzureRmDataLakeStoreItemOwner                  2.0.1      AzureRM.DataLakeStore
Cmdlet          Stop-AzureRmDataLakeAnalyticsJob                   2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Submit-AzureRmDataLakeAnalyticsJob                 2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Test-AzureRmDataLakeAnalyticsAccount               2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Test-AzureRmDataLakeAnalyticsCatalogItem           2.0.1      AzureRM.DataLakeAnalytics
Cmdlet          Test-AzureRmDataLakeStoreAccount                   2.0.1      AzureRM.DataLakeStore
Cmdlet          Test-AzureRmDataLakeStoreItem                      2.0.1      AzureRM.DataLakeStore
Cmdlet          Wait-AzureRmDataLakeAnalyticsJob                   2.0.1      AzureRM.DataLakeAnalytics

**Comment by maddieclayton** [comment]
@matt1883 Are you still seeing this issue?

**Comment by matt1883** [comment]
I don't see this issue anymore. Thanks, @maddieclayton!
