### ISSUE TITLE
Authentication RT should include KyeVault Endpoint and Audience

### ISSUE THREAD

**Issue by sphibbs** [Azure/azure-powershell#2777]
Per this issue
there is no entry in the AAD management panel for a Key Vault scope, which means you need to use the “Powershell workaround” to access resources in Key Vault when using UWP. I have a fairly long-winded explanation and proposed workaround for that here: https://anthturner.com/2016/03/09/azure-key-vault-in-uwp-applications/

**Comment by markcowl** [comment]
@sphibbs what is the actual request for Azure PowerShell cmdlets in this case?  Is there a new cmdlets needed, modifications to an existing cmdlet?

**Comment by twitchax** [comment]
This is not about Azure PowerShell cmdlets.  The issue described to the author pertains to using Azure PowerShell's Client ID in a UWP application using .NET client libraries.

There may be an issue here for the .NET SDK, but it would require some investigation there.

@sphibbs, can you bring in the OP so I can work with them on moving this issue?  Closing...
