### ISSUE TITLE
 Get-UsageAggregate cmdlet showing wrong example

### ISSUE THREAD

**Issue by mtandon80** [Azure/azure-powershell#2783]
**Get-UsageAggregate** cmdlet is showing _“DateTime”_ as parameter for _“ReportedStartTime”_ and _“ReportedEndTime”._ Though Azure API supports DateTimeOffSet format only. 

[https://msdn.microsoft.com/en-us/library/azure/mt219001](https://msdn.microsoft.com/en-us/library/azure/mt219001)

With PowerShell, Datetime can be formatted into DateTimeOffSet but example shown for cmdlet is pure datetime only. Can we fix example to show DateTimeOffset value and also include following message so users know how to specify and use cmdlet:
### _"Please note that the dateTime value format must be URL encoded as ISO 8601 format, and non-numeric characters must use escape codes (i.e. colon is escaped to %3a, plus sign is escaped to %2b) so that it is URI friendly. These refer to the start and end time ranges of your query. This dateTime parameter must also be specified in Universal Time Coordinated (UTC)."_

Issue with current example is that if someone just take it as is then it does not work for Azure Stack because it validates incoming input to be in proper DateTimeOffSet format. 

Thanks

**Comment by bganapa** [comment]
@markcowl Could you please assign this to the right person and push a fix in October release

**Comment by markcowl** [comment]
@bganapa AutoRest automatically uses ISO8601 for date serialization - DateTimeOffset versus Date is a Microsoft .Net type distincation.  Are you guys only supporting ISO8601 serializations that explicitly use the offset, or are you supporting serialzations that use UTC time?  

Please file a new bug and specify exactly what is wrong with the serialization and we can have someone take a look.  Closing this for now.
