### ISSUE TITLE
Add help for Automation cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#2791]
Branching off from issue https://github.com/Azure/azure-powershell/issues/2413

Automation is missing help for the following cmdlets:
- Get-AzureRmAutomationJobOutputRecord
- Remove-AzureRmAutomationDscNodeConfiguration
- Remove-AzureRmAutomationDscConfiguration
- Remove-AzureAutomationConnection
- Remove-AzureAutomationConnectionType
- Set-AzureAutomationConnectionFieldValue

**Comment by cormacpayne** [comment]
@jodoglevy Hey Joe, would you mind taking a look at this issue?

**Comment by jodoglevy** [comment]
I am no longer at Microsoft. Can you ping Eamon O'Reilly at Microsoft to find a new owner?
