### ISSUE TITLE
Add help for Compute cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#2792]
Branching off from issue https://github.com/Azure/azure-powershell/issues/2413

Compute is missing help for the following cmdlets:
- Get-AzureRmVMAEMExtension
- Remove-AzureRmVMAEMExtension
- Set-AzureRmVMAEMExtension
- Test-AzureRmVMAEMExtension
- Set-AzureRmVMBginfoExtension
- Set-AzureRmVMPlan

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue and assigning it to the proper milestone?

**Comment by singhkays** [comment]
```
Set-AzureRmVMBginfoExtension
Set-AzureRmVMPlan
```

Will be in next release. Others are owned by a different team, will ping them offline.

**Comment by markcowl** [comment]
@signhkay please close if thsi is resolved.  If not, please place in the appropriatre milesonte.  If you need to add a separate issue to trak soem of the help changes, please do so

**Comment by singhkays** [comment]
Fixed
