### ISSUE TITLE
Add help for HDInsight cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#2793]
Branching off from issue https://github.com/Azure/azure-powershell/issues/2413

HDInsight is missing help for the following cmdlets:
- Add-AzureHDInsightScriptAction
- Grant-AzureHDInsightRdpAccess
- Revoke-AzureHDInsightRdpAccess
- Set-AzureHDInsightClusterSize

**Comment by cormacpayne** [comment]
@nemanja88 Hey Nemanja, would you mind taking a look at this issue and assigning it to the proper milestone?

**Comment by maddieclayton** [comment]
Fixed.
