### ISSUE TITLE
Add help for RemoteApp cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#2796]
Branching off from issue https://github.com/Azure/azure-powershell/issues/2413

RemoteApp is missing help for the following cmdlets:
- Clear-AzureRemoteAppVmStaleAdObject
- Get-AzureRemoteAppVM
- Get-AzureRemoteAppVmStaleAdObject
- Restart-AzureRemoteAppVM

**Comment by cormacpayne** [comment]
@yadavbdev Hey Yadav, would you mind taking a look at this issue and assigning it to the proper milestone?

**Comment by maddieclayton** [comment]
RemoteApp no longer exists. Closing.
