### ISSUE TITLE
Add help for Sql cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#2797]
Branching off from issue https://github.com/Azure/azure-powershell/issues/2413

Sql is missing help for the following cmdlets:
- Get-AzureRmSqlServerDisasterRecoveryConfiguration
- Get-AzureRmSqlServerDisasterRecoveryConfigurationActivity
- New-AzureRmSqlServerDisasterRecoveryConfiguration
- Remove-AzureRmSqlServerDisasterRecoveryConfiguration
- Set-AzureRmSqlServerDisasterRecoveryConfiguration

**Comment by cormacpayne** [comment]
@akromm Hey Adam, would you mind taking a look at this issue and assigning it to the proper milestone?

**Comment by akromm** [comment]
@hchungmsft can you look into doing the documentation for these cmdlets.

**Comment by akromm** [comment]
@cormacpayne  Did this PR not add the appropriate help: https://github.com/Azure/azure-powershell/pull/2017 ?

**Comment by cormacpayne** [comment]
@akromm yup, that PR took care of it. I must have been looking at an outdated list. I will close this issue.
