### ISSUE TITLE
Add help for TrafficManager cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#2798]
Branching off from issue https://github.com/Azure/azure-powershell/issues/2413

TrafficManager is missing help for the following cmdlets:
- Disable-AzureRmTrafficManagerEndpoint
- Enable-AzureRmTrafficManagerEndpoint
- Set-AzureRmTrafficManagerEndpoint
- Get-AzureRmTrafficManagerEndpoint
- Remove-AzureRmTrafficManagerEndpoint
- New-AzureRmTrafficManagerEndpoint
- Disable-AzureRmTrafficManagerProfile
- Enable-AzureRmTrafficManagerProfile

**Comment by cormacpayne** [comment]
@jtuliani Hey Jonathan, would you mind taking a look at this issue and assigning it to the proper milestone?

**Comment by dilukose** [comment]
Ack-ing...

**Comment by maddieclayton** [comment]
Fixed
