### ISSUE TITLE
Add help for Websites cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#2799]
Branching off from issue https://github.com/Azure/azure-powershell/issues/2413

Websites is missing help for the following cmdlets:
- Get-AzureRmAppServicePlanMetrics
- New-AzureRmWebAppDatabaseBackupSetting
- Restore-AzureRmWebAppBackup
- Get-AzureRmWebAppCertificate
- Get-AzureRmWebAppSSLBinding
- New-AzureRmWebAppSSLBinding
- Remove-AzureRmWebAppSSLBinding
- Get-AzureRmWebAppSlot
- Get-AzureRmWebAppSlotMetrics
- Get-AzureRmWebAppSlotPublishingProfile
- New-AzureRmWebAppSlot
- Remove-AzureRmWebAppSlot
- Reset-AzureRmWebAppSlotPublishingProfile
- Restart-AzureRmWebAppSlot
- Set-AzureRmWebAppSlot
- Start-AzureRmWebAppSlot
- Stop-AzureRmWebAppSlot
- Edit-AzureRmWebAppBackupConfiguration
- Get-AzureRmWebAppBackup
- Get-AzureRmWebAppBackupConfiguration
- Get-AzureRmWebAppBackupList
- Get-AzureRmWebAppMetrics
- Get-AzureRmWebAppPublishingProfile
- New-AzureRmWebAppBackup
- Remove-AzureRmWebAppBackup
- Reset-AzureRmWebAppPublishingProfile
- Set-AzureRmWebApp

**Comment by cormacpayne** [comment]
@akurmi Hey Ashish, would you mind taking a look at this issue and assigning it to the proper milestone?

**Comment by akurmi** [comment]
@ahmedelnably

**Comment by cormacpayne** [comment]
Closing in favor of issue https://github.com/Azure/azure-powershell/issues/2440
