### ISSUE TITLE
Add help for ExpressRoute cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#2800]
Branching off from issue https://github.com/Azure/azure-powershell/issues/2413

ExpressRoute is missing help for the following cmdlets:
- Get-AzureCrossConnection
- New-AzureCrossConnection
- Set-AzureCrossConnection
- Get-AzureDedicatedCircuitPeeringArpInfo
- Get-AzureDedicatedCircuitPeeringRouteTableInfo
- Get-AzureDedicatedCircuitPeeringRouteTableSummary
- Get-AzureDedicatedCircuitStats
- Set-AzureDedicatedCircuitProperties

**Comment by cormacpayne** [comment]
@nupurkot Hey Nupur, would you mind taking a look at this issue and assigning it to the proper milestone?

**Comment by BMichaelJ** [comment]
This would be very helpfull to have!

**Comment by maddieclayton** [comment]
Help is either updated or the cmdlet no longer exists.
