### ISSUE TITLE
Fails to install on PowerShell Core due to missing Telemetry class

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2803]
# Issue
I'm trying to install the AzureRM PowerShell module on PowerShell Core on Ubuntu Linux 16.04 LTS Xenial Xerus, under a Docker image. I'm getting an exception installing the module, due to a missing Telemetry class in the .NET Core framework.

![image](https://cloud.githubusercontent.com/assets/466713/17785923/e6e0d882-653f-11e6-88ad-7b9b3d5ade56.png)

```
PS /powershell> $error[0]
PackageManagement\Install-Package : Package 'AzureRM.profile' failed to be installed because: /tmp/1844849850/AzureRM.p
rofile/AzureRM.profile.nuspecAzureRM'
At /opt/microsoft/powershell/6.0.0-alpha.9/Modules/PowerShellGet/PSModule.psm1:1706 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (AzureRM.profile:String) [Install-Package], Exception
    + FullyQualifiedErrorId : Package '{0}' failed to be installed because: {1},Microsoft.PowerShell.PackageManagement
   .Cmdlets.InstallPackage
                                                                                         [oooooooooooooooooooooooooooooo
PS /powershell> $error[1]
Unable to find type [Microsoft.PowerShell.Commands.PowerShellGet.Telemetry].
At /opt/microsoft/powershell/6.0.0-alpha.9/Modules/PowerShellGet/PSModule.psm1:552 char:26
+ ... yMethods = ([Microsoft.PowerShell.Commands.PowerShellGet.Telemetry] | ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...llGet.Telemetry:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

## PowerShell Version

```
PS /powershell> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

# Repro Steps

On a Docker Host, run these commands:

```
### Start a new PowerShell Docker container
docker run --rm -i -t trevorsullivan/powershell

### Attempt to install Azure Resource Manager (ARM) PowerShell module from the PowerShell Gallery
Install-Module -Name AzureRM -Scope CurrentUser -Force
```

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by epennaz** [comment]
Seems it's possible: https://channel9.msdn.com/Blogs/hybrid-it-management/PowerShell-on-Linux-and-Open-Source  skip to the 13:00 minute mark. Are we missing dependencies?

**Comment by markcowl** [comment]
@pcgeek86 You can install this module, which has specific support for the Core PSEdition:https://www.powershellgallery.com/packages/AzureRM.NetCore.Preview/0.3.4

**Comment by markcowl** [comment]
Also, there is currently a bug in alpha9 that prevents installing modules set for the PSCore edition, so you may need to use ```Install-Package``` instead.  See: https://github.com/PowerShell/PowerShell/blob/master/demos/Azure/Azure-Demo.ps1#L11

**Comment by markcowl** [comment]
@pcgeek86 This seems like a bug in PowerShellGet as well, since it should refuse to install any modules that do not specifically support the Core edition

**Comment by letmaik** [comment]
Is the Core edition maintained? Last update was 2016-08-19
