### ISSUE TITLE
[Reference Only]: Re-structure repository to support multiple profiles

### ISSUE THREAD

**Issue by kirthik** [Azure/azure-powershell#2805]
### Description

Restructure the repository to allow building multiple profiles of modules side-by-side
- [ ] Update folder structure and build components as follows:
  - Setup
  - StackSetup
  - AzureRM.BootStrapper
  - AzureRM
  - AzureStack
    - Version
      - AzureStack
      - Admin
      - Storage
  - Common
    - Commands
    - Authentication
    - ResourceManager
    - Storage
  - Profile
  - AzureRM.*
    - Common
      - Cmdlets
      - Tests
    - Api-Version[s]
      - Cmdlets
      - Tests
  - ServiceManagement

- [ ] Create a profile targets file that allows listing groups of modules by profile.  Predefined profiles will include (stack, latest, latest-stable)
- [x] Create a solution or proj file with modules and tests for a profile
- [ ] Update msbuild artifacts to allow building module using a new profile specifier from the targets file
- [ ] Update msbuild artifcats to allow testing using a profile specifier
- [ ] Update msi build to handle new structure
- [ ] Update package build to use new structure
- [ ] Create documentation for  the follwoing in the documentation repo and replace in the wiki
	- Addign new modules
	- Adding cmdlets for a new api version
	- Updating cmdlets in an existing api-version

**Comment by markcowl** [comment]
Use a variable ```BuildProfile={latest | 2017-03-09-profile | All}```
- [ ] Create side-by-side build in VS for AzureStack (separate SLN + seperate output path + projects)
  - [ ] Update build path for stack modules to ```src\Stack\{Config}```
  - [ ] Copy Profile module into Stack\Config when building Stack profile or all
- [ ] Move over tests and have them build into the same directory
  - [ ] Update test map to include stack packages
- [ ] Create Side-by-Side msi build for stack
  - [ ] Update msi generator to include extra parameter (BuildProfile as above)
- [ ] Update packaging tools for side-by-side build
  - [ ] Include new parameter for building one or all
- [ ] Update build.proj targets to allow buildins both (by default), Stack, or latest
  - [ ] Update test targets to run latest (default), stack, or both
  - [ ] Update msi targets to build latest (default), stack, or both
  - [ ] Update Jenkins CI job to build all and run tests based on changes
  - [ ] Update Jenkins On demand builf to buils and run all tests
  - [ ] Update Jenkins CI sign job to build latest (default), stack, or all

**Comment by markcowl** [comment]
Moved into separate issues
