### ISSUE TITLE
Creating an Azure infrstructure via Jenkins

### ISSUE THREAD

**Issue by IvanovOleg** [Azure/azure-powershell#2812]
Hi guys,

I have a powershell script which creates an infrastructure in Azure from ARM templates. Everything works fine from powershell, but when I try to execute this script from Jenkins it fails. The reason of the issue is an authentication. Jenkins is not able to operate with an authentication dialog window. Is there any other way to log in to azure from script?

**Comment by EUCConsulting** [comment]
You need to create a service principal and use this in your script

https://blogs.endjin.com/2016/01/azure-resource-manager-authentication-from-a-powershell-script/
