### ISSUE TITLE
-UseRemoteGateways in Add-AzureRmVirtualNetworkPeering does not enable Remote Gateway Peering

### ISSUE THREAD

**Issue by ld0614** [Azure/azure-powershell#2815]
### Cmdlet(s)

Add-AzureRmVirtualNetworkPeering
### PowerShell Version

Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.0.10586.494
### Module Version

2.0.1
### OS Version

Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.10586.494
### Description

When attempting to create a peered connection which communicates across a VPN the switch UseRemoteGateways does not work.  This stops multiple regions from communicating without using User Defined Routing on a Network Virtual Appliance.  
### Debug Output

Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

Looking at the HTTP request it does not appear that the request to use Remote Gateways is sent:
"properties": {
    "allowVirtualNetworkAccess": true,
    "allowForwardedTraffic": false,
    "allowGatewayTransit": false,
    "remoteVirtualNetwork": {

The response from the request is:
"allowVirtualNetworkAccess": true,
    "allowForwardedTraffic": false,
    "allowGatewayTransit": false,
    "useRemoteGateways": false,
    "remoteAddressSpace": {
      "addressPrefixes": [
        "10.0.0.0/16"
      ]
### Script/Steps for Reproduction

Vnet1 and Vnet2 in Region 1
Vnet3 in Region 2
Create Route Based VPN between Vnet1 and Vnet 3
Server on Vnet1 communicated with Vnet3
Create Peer between Vnet1 and Vnet2
Switches on Vnet1: -AlloowGatewayTransit
Switches on Vnet2: -UseRemoteGateways
Server on Vnet2 communicated with Vnet1 but not Vnet3

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft Hey Deepak, would you mind taking a look at this issue?

**Comment by maddieclayton** [comment]
@chandrasekarsrinivasan Can you take a look at this issue?

**Comment by chandrasekarsrinivasan** [comment]
Assigning to Amol. @Am018

**Comment by Am018** [comment]
This is over two years old issue. I don't think the issue exists anymore. I am closing the issue. Please reopen if you think it requires investigation.
