### ISSUE TITLE
Why is –OSState "Specialized" parameter not supported in 'Save-AzureRmVMImage' cmdlet.

### ISSUE THREAD

**Issue by abhishekshivalkar** [Azure/azure-powershell#2818]
Save-AzureVMImage  cmdlet supported –OSState "Specialized" parameter for specialized VM Image which is meant to be used as a “snapshot” to deploy a VM to a good known point in time. This feature is no longer available in ARM equivalent of cmdlet - Save-AzureRmVMImage.

Save-AzureRmVMImage needs VM to be sysprep/Generalized. The problem is that once you generalized a VM on Azure to create an image from it, and then Azure does not allow you to start it from its stopped (deallocated) state with below error-

TITLE Failed to start virtual machine
DESCRIPTION Failed to start virtual machine 'VMname'. Error: Operation 'start' is not allowed on VM 'VMname' since the VM is generalized.
STATUS Error

Why is –OSState "Specialized" parameter not supported in 'Save-AzureRmVMImage' cmdlet?

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by singhkays** [comment]
@abhishekshivalkar Save-AzureVMImage was always intended to give you a snapshot of a deallocated VM. It wasn't recommended to run it on a running VM. You can achieve the same functionality by copying the blob yourself in ARM. For your main question, since there isn't an API to call for `-Specialized` flag, the cmdlet doesn't support it.

**Comment by abhishekshivalkar** [comment]
Would ARM equivalent -Specialized flag be supported in future?

**Comment by singhkays** [comment]
@abhishekshivalkar I'm not aware of an API support incoming that will allow us to replicate that functionality in PS. But you don't need to un-generalize your VM to get a specialized disk. If you delete the VM, the VHD left behind is already specialized. Similarly, if you copy that VHD blob to another location, it's a specialized disk. You should be able to create a new VM from it.
