### ISSUE TITLE
Set-AzureRmVMCustomScriptExtension seems to return NULL with 1.6

### ISSUE THREAD

**Issue by avishnyakov** [Azure/azure-powershell#2820]
### Cmdlet(s)
Set-AzureRmVMCustomScriptExtension

### PowerShell Version
5.0.10586.494

### Module Version
1.6

### OS Version
Win8, Win2012 R2

### Description
Set-AzureRmVMCustomScriptExtension used to return result object with the properties such as 'IsSuccessStatusCode' and so on. With 1.6 Azure PowerShell, it seems to return $null all the time.

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by singhkays** [comment]
@avishnyakov I'm not aware of something changed in the return object recently. @hyonholee can you take a look?

**Comment by avishnyakov** [comment]
Can't replicate anymore. Closing.
