### ISSUE TITLE
Enable xunit test automation for Storage management

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2833]
### Description

Enable xunit test automation for Storage management

https://github.com/Azure/azure-powershell/blob/dev/AzurePowershell.Test.targets#L108

Uncomment this line and fix any test failures

**Comment by blueww** [comment]
Talked with Emma about the issue:
1.	The following storage test need to run with public azure, but how can we save the credential for public azure?
2.	Storage cmdlets depends on XSCL, but XSCL don’t support can re-play the workload.

The storage management cmdlets are bases on WindowsAzure.Storage library, so we can’t skip using WindowsAzure.Storage library when testing them.

**Comment by blueww** [comment]
We already have enbaled the Storage management unit test.
