### ISSUE TITLE
Enable xunit test automation for AzureStackStorage and AzureStackAdmin 

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2834]
### Description

Enable xunit test automation for AzureStackStrage and AzureStackAdmin 

https://github.com/Azure/azure-powershell/blob/dev/AzurePowershell.Test.targets#L99

Uncomment this line and fix any test failures

**Comment by cormacpayne** [comment]
@bganapa what is the status of this issue?

**Comment by bganapa** [comment]
@cormacpayne  We have automation in place
