### ISSUE TITLE
Enable xunit test automation for RecoveryServices management

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2838]
### Description
Enable xunit test automation for RecoveryServices management

https://github.com/Azure/azure-powershell/blob/dev/AzurePowershell.Test.targets#L104

Uncomment this line and fix any test failures

**Comment by sriramvu** [comment]
Changes are there in following commits:
https://github.com/Azure/azure-powershell/commit/03c78d3164ba9d7b97f465c0689647cf90ef5cf4
https://github.com/Azure/azure-powershell/commit/485243dde170b5229d01e0747d5af340a0b677c9

Thank you.
