### ISSUE TITLE
Empty vhd when uploaded to Azure blob storage becomes 16gb

### ISSUE THREAD

**Issue by aklintsevich** [Azure/azure-powershell#2846]
### Cmdlet(s)

Add-AzureRmVhd 

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

5.1.14393.1000

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

10.0.14393.1000

### Description

I upload an empty vhd that is 4 mb in size , but when the upload finishes it becomes 16gb in blob storage

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

have a blank vhd on your local machine
Execute the cmdlet like this:

Add-AzureRmVhd  -Destination <container and name in azure blob storage >-ResourceGroupName <resource group>-LocalFilePath <vhd local path>

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by singhkays** [comment]
@aklintsevich What is the VHD type - Fixed, Dynamic? Have you tried with a fixed VHD since Azure only supports fixed?

**Comment by aklintsevich** [comment]
How do I know if the vhd that I am using is fixed or dynamic? Why would this make a difference when uploading to Azure blob storage?

**Comment by singhkays** [comment]
@aklintsevich See http://www.oxfordsbsguy.com/2014/06/09/how-to-inspect-and-edit-virtual-disks-in-hyper-v/

Add-AzureRmVhd auto converts dynamic to fixed on client side and the uploads to prevent errors when the VHD is used in Azure. There may be a bug in that code is the only reason I can think of why you're seeing the above behavior but I don't know enough about your source VHD to make a conclusive judgement of the issue.
