### ISSUE TITLE
New-AzureRmSchedulerHttpJob keep asking -UserName -Password parameters even though i provided -Headers with Authrization 

### ISSUE THREAD

**Issue by vdangwal** [Azure/azure-powershell#2850]
### Cmdlet(s)

 New-AzureRmSchedulerHttpJob
### PowerShell Version

Name                           Value

---

PSVersion                      5.0.10586.494
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.494
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
### OS Version

Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
### Description

When using New-AzureRmSchedulerHttpJob, i am providing all the other params including -Headers with Authorization value, but when i try to execute this command, it prompt me -UserName and -Password. When i dont give, it gives null exception, if provide the same, it give me message that you cannot provide both the 'Authorization' and -Username/pwd combination. Please help me to understand how can i use it. 
### Debug Output

Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@vivsriaus Hey Vivek, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
@derek1ee Hey Derek, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
Closing as the Scheduler module no longer ships with `Az`.
