### ISSUE TITLE
Switch-AzureWebsiteSlot should support "Swap with Preview"

### ISSUE THREAD

**Issue by dimkanewtown** [Azure/azure-powershell#2856]
The azure management portal supports the "Swap with Preview" option on the web apps. It would only make sense that Switch-AzureWebsiteSlot also supported it.

**Comment by markcowl** [comment]
@akurmi can you take a look

**Comment by akurmi** [comment]
'Swap-AzureRmWebAppSlot' PowerShell cmdlet supports this swap mode.

**Comment by dimkanewtown** [comment]
Do you have link to correct usage or sample usage? I will need to run this as part of VSO release off a build agent.

**Comment by akurmi** [comment]
Apply slot config:
Swap-AzureRmWebAppSlots -ResourceGroupName Default-Web-EastAsia -Name webappslottest -SourceSlotName staging -DestinationSlotName production -SwapWithPreviewAction ApplySlotConfig
 
Complete slot swap:
Swap-AzureRmWebAppSlots -ResourceGroupName Default-Web-EastAsia -Name webappslottest -SourceSlotName staging -DestinationSlotName production -SwapWithPreviewAction CompleteSlotSwap
 
Reset slot swap:
Swap-AzureRmWebAppSlots -ResourceGroupName Default-Web-EastAsia -Name webappslottest -SourceSlotName staging -DestinationSlotName production -SwapWithPreviewAction ResetSlotSwap

**Comment by dimkanewtown** [comment]
Thank you!
