### ISSUE TITLE
Prompt for Data Collection Immediately Selecting 'No' in Interactive Session

### ISSUE THREAD

**Issue by devigned** [Azure/azure-powershell#2860]
### Cmdlet(s)
Login-AzureRmAccount

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1.14393 .82

### Module Version
Azure 2.0.1

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

5.1.14393 .82

### Description

Upon first run of Azure PowerShell the data collection prompt doesn't wait for an answer and quickly opts for 'N'.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
With a clean Windows 10 Anniversary edition, run `install-module AzureRm` and then `Login-AzureRmAccount`.

**Comment by sphibbs** [comment]
I was not able to repo. I tried on a clean win10 anniv machine and my 'dirty' machine. If you delete \appdata\romaring\windowsazurepowershell\AzureDataCollectionProfile.json can you repo?

**Comment by devigned** [comment]
@sphibbs you know what I think happened. I think I slipped and hit a key. The prompt doesn't differentiate bad input (any other character) from N|n|Y|y.

**Comment by sphibbs** [comment]
Closing issue.
