### ISSUE TITLE
Use updated subscription client for cmdlets in Profile, like Get-AzureRmSubscription

### ISSUE THREAD

**Issue by vivsriaus** [Azure/azure-powershell#2861]
### Cmdlet(s)

Get-AzureRmSubscription
### PowerShell Version

Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
### OS Version

Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
### Description

To list zero-cap subscriptions in Get-AzureRmSubscription, the api-version to be used for get subscriptions call via the subscription client is 2016-06-01 or greater. This requires an update to the subscription client (which the ARM team will publish) and that needs to pulled in as a reference in Commands.Profile project.
### Debug Output

Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
Fix is in PR https://github.com/Azure/azure-powershell/pull/3423

**Comment by cormacpayne** [comment]
Fix has been merged into `preview` branch.
