### ISSUE TITLE
Convert Profile module help to use platyPS and write documentation for service teams

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2862]
### Description
platyPS allows creating and editing cmdlet help through markdown files.  Use platyPS to generate help markdown files for the Profile cmdlets.  Store these files in the repo (help directory in the module folder), generate a new help-xml file form them and replace the existing help-xml.

As part of this, document the process of using platyPS to create cmdlet help, including
- [x] Generating markdown files
- [ ] Integrating existing markdown help with changes in the cmdlet
- [x] Creating help.xml from the markdown files

Create a document for managing online help with platyPS, place in the Documentation folder, and lionk form the Developer guide.

**Comment by cormacpayne** [comment]
Generating markdown files complete, need to determine what cmdlets should be run to ensure that changes to a cmdlet are reflected in the new markdown help files. These changes would include:
- Remove (parameters, parameter sets)
- Add (parameters, parameter sets)
- Change metadata (parameters, parameter sets, cmdlets)
- Add cmdlet
- Remove cmdlet

**Comment by cormacpayne** [comment]
- Added documentation for how to use platyPS to generate markdown files and update those markdown files when a cmdlet changes
- Added a script to create or update markdown files for a given AzureRM service
- Converted Profile to markdown files

https://github.com/cormacpayne/azure-powershell/tree/platyps/tools/platyPS
