### ISSUE TITLE
Unable to Start VMware -> Azure Site Recovery Failover Jobs; invalid parameter "ReplicationProviderInput"

### ISSUE THREAD

**Issue by gabrieljtaylor** [Azure/azure-powershell#2872]
### Cmdlet(s)
Start-AzureRmSiteRecoveryUnplannedFailoverJob, Start-AzureRmSiteRecoveryTestFailoverJob

### PowerShell Version
5.1.14393.82

### Module Version
2.0.1

### OS Version
10.0.14393.82

### Description
Using these cmdlets in the form "[Start-AzureRmSiteRecoveryTestFailoverJob|Start-AzureRmSiteRecoveryUnplannedFailoverJob] -ProtectionEntity $ProtectionEntity -Direction PrimaryToRecovery" in a VMware to Azure scenario successfully triggers the job, however the job will fail, citing the error "An invalid parameter ReplicationProviderInput was passed.", Error ID 506.

The cmdlet exposes no parameters which can be used to change whether or not this parameter is passed to Azure, so the user has no way of preventing this parameter from being passed.

I can find no documentation stating that the VMware to Azure scenario is _not_ supported by the cmdlets, thus I assume it is, however it is not working.

### Debug Output
Irrelevant, as the cmdlet's submission of the job "succeeds" and the job is started; it simply immediately fails after that.

### Script/Steps for Reproduction
$ProtectionContainer = Get-AzureRmSiteRecoveryProtectionContainer
$ProtectionEntity = Get-AzureRmSiteRecoveryProtectionEntity | Select -first 1
Start-AzureRmSiteRecoveryUnplannedFailoverJob -ProtectionEntity $ProtectionEntity -Direction PrimaryToRecovery -Verbose

After running the script commands, navigate to the Azure RM portal and investigate the status of the Site Recovery job - there will be a new failed job citing error ID 506, "An invalid parameter ReplicationProviderInput was passed."

**Comment by cormacpayne** [comment]
@sriramvu Hey Sriram, would you mind taking a look at this issue?

**Comment by sriramvu** [comment]
@gabrieljtaylor: Thanks for trying out AzureSiteRecovery cmdlets.

Currently we support following scenarios via RDFE, ARM based cmdlets:
- VMM to VMM
- VMM to Azure
- Hyper-V to Azure

VMWare and physical server deployments are in our current backlog. 
We are planning to introduced Azure to Azure scenario in next couple of releases.

Action items for us:
- Will check the support documentation for cmdlets.
- Will try informing the error message in better way.


Thank you.

**Comment by gabrieljtaylor** [comment]
Awesome, thank you for the confirmation. I couldn't find any statements about supportability of the VMware to Azure scenario in any of the documentation (ASR documentation or the RM cmdlet documentation), hence my uncertainty. I appreciate the clarification!

**Comment by davidbairdala** [comment]
Is this still the case? It looks like the documentation now indicates that VMWare to Azure is now supported via PowerShell: [vmware-physical-azure-support-matrix](https://docs.microsoft.com/en-us/azure/site-recovery/vmware-physical-azure-support-matrix#mobility-service), although I am getting the same error when trying to use the REST API

**Comment by bsiva** [comment]
@davidbairdala Yes, VMware to Azure is supported via PowerShell. The PowerShell module and cmdlets to use are different from the ones this thread was originally opened for. PowerShell support for the VMware to Azure scenario is delivered via the AzureRm.RecoveryServices.SiteRecovery module. 

Here is a tutorial on how to use Azure PowerShell to start replicating VMware virtual machines to Azure: https://docs.microsoft.com/en-us/azure/site-recovery/vmware-azure-disaster-recovery-powershell

The complete cmdlet reference for the cmdlets in the module is here: https://docs.microsoft.com/en-us/powershell/module/AzureRM.RecoveryServices.SiteRecovery
