### ISSUE TITLE
No support for Classic Infrastructure Migration in AzureChinaCloud Environment

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#2876]
### Cmdlet(s)
Get-AzureRmResourceProvider

### PowerShell Version
4.0

### Module Version
2.0.1 (Azure)
3.0.1 (AzureRM.Resources)

### OS Version
6.3.9600.17400

### Description
Am trying to migrate a Reserved IP from Classic ReservedIP to ARM ReservedIP.
Am getting the below when trying to find the "Microsoft.ClassicInfrastructureMigrate" provider

**Get-AzureRmResourceProvider -ProviderNamespace "Microsoft.ClassicInfrastructureMigrate"**
Get-AzureRmResourceProvider : The resource namespace 'Microsoft.ClassicInfrastructureMigrate' is invalid.
At line:1 char:1
+ Get-AzureRmResourceProvider -ProviderNamespace "Microsoft.ClassicInfrastructureM ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResourceProvider], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureProviderCmdlet

### Debug Output
Body:
{
  "error": {
    "code": "InvalidResourceNamespace",
    "message": "The resource namespace 'Microsoft.ClassicInfrastructureMigrate' is invalid."
  }
}

Get-AzureRmResourceProvider : The resource namespace 'Microsoft.ClassicInfrastructureMigrate' is invalid.
At line:1 char:1
+ Get-AzureRmResourceProvider -ProviderNamespace "Microsoft.ClassicInfrastructureM ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResourceProvider], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureProviderCmdlet

### Script/Steps for Reproduction

Login-AzureRmAccount -EnvironmentName "AzureChinaCloud"
Select AzureRmSubscription -SubscriptionName "Name of the Subscription"
Get-AzureRmResourceProvider -ProviderNamespace "Microsoft.ClassicInfrastructureMigrate"

Thanks,
Pradebban Raja

**Comment by markcowl** [comment]
@Pradebban Are you saying that this resource is actually available in AzureChnaCliud and it is not being returend?  If the service is simply not there, please contact the Azure China team to determine when/if they plan to deploy it.

**Comment by markcowl** [comment]
Closing for lack of response.  Please reopen with the addiitonal requetsed data, if this is still an issue for you.

**Comment by Pradebban** [comment]
@markcowl Sorry for the delayed response.

until recently it was not supported at all. But now it shows the migration is available.

**Comment by Pradebban** [comment]
@markcowl , have opened a new issue for this one - #3054
