### ISSUE TITLE
Get-AzureRmStorageAccountKey missing online help URI

### ISSUE THREAD

**Issue by v2kiran** [Azure/azure-powershell#2878]
### Cmdlet(s)

Get-AzureRmStorageAccountKey
### PowerShell Version

PSVersion 5.1.14393.82
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.14393.82
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
### Module Version

2.0.1
### OS Version

10.0.14393.82
### Description

cmdlets needs to open default browser and display online help.
### Debug Output

Get-Help : The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help topic is not specified in the command code or in the help file for the command.
At line:55 char:5
### Script/Steps for Reproduction

Get-help Get-AzureRmStorageAccountKey -Online

**Comment by cormacpayne** [comment]
@EmmaZhu Hey Emma, would you mind taking a look at this issue?

**Comment by blueww** [comment]
I will look at it.

**Comment by blueww** [comment]
I have open a track item for it, and will priority it according to our bandwidth and customer request count.

**Comment by BurtHarris** [comment]
+1 for populating the HelpUri field for all Azure commands.   

I ran into the same problem for the Add-AzureRmAccount command.   Do you want a separate bug, or to generalize this one?

**Comment by blueww** [comment]
The issue for Get-AzureRmStorageAccountKey already resolved. Run "get-help Get-AzureRmStorageAccountKey -online" with latest Azure Powershell can direct to correct online help page.
So will close this issue.

@BurtHarris , please open another issue for  Add-AzureRmAccount, seems it still not work.
