### ISSUE TITLE
Azure PS is caching removal of Azure RM environment

### ISSUE THREAD

**Issue by diptiGitHub** [Azure/azure-powershell#2881]
Cmdlet(s)
Remove-AzureRmEnvironment 

PowerShell Version
5.1.14393.1000

 Module Version
2.0.1

 OS Version
 10.0.14393.1000 

 Description
Azure PS is caching removal of Azure RM environment. I created the azEnvironment then deleted it. Then I again created, but could not retrieve it. The cache still has the removed state.

 Debug Output
No error on cmdlet execution. Its caching issue.

 Script/Steps for Reproduction
1. Create azEnvironment using the cmdlet Add-AzureRmEnvironment 
2. Get azAccount using Add-AzureRmAccount -Environment $azEnvironment -Credential $Credential -TenantId $TenantId  
3.Remove the environment using  Remove-AzureRmEnvironment 
4. Again create azEnvironment using Add-AzureRmEnvironment
5. Try to get the azEnvironment
 
Expected: Should successfully get azEnvironment
 
Actual: Getting null. As we had removed it earlier, the cache has that info and did not get updated with new creation. I tried it multiple times with same result. However, creating a new PS session, I could successfully get it.

**Comment by markcowl** [comment]
@diptiGitHub Please use -EnvironmentName to refer to created environments, rather than -Environment.

If you use -EnvironmentName, you should not see this behavior, but please post here if you do.

**Comment by markcowl** [comment]
Closing for lack of repro.  Please open a new issue and refere to this one if you're still seeing thsi behavior.
