### ISSUE TITLE
New-AzureSBNamespace doesn't allow creation of namespaces created by mistake in other subscription

### ISSUE THREAD

**Issue by bunceg** [Azure/azure-powershell#290]
1) Select a subscription
2) Create a service bus namespace "XXXX"
3) Realise the subscription hadnt been changed properly
4) Delete the service bus
5) Change the subscription
6) Create a service bus namespace "XXXX"

Error <Code>400</Code><Detail>The namespace name is previously used in another project and has been deleted less than one week.</Detail></Error>

This may come from Azure and not the powershell scripts but, come on, ... mistakes happen and now I need to wait one week??

**Comment by mayurdhingra** [comment]
I've been struggling with the same issue. I don't know why there is no fix for this issue till now.

**Comment by bunceg** [comment]
I think it's because these scripts are probably going to be deprecated. ARM is way forward and there is a "hidden" ARM script to create service bus namespaces now

**Comment by edtheshed** [comment]
any update on this? I get the same error when re-creating a namespace with same name as a deleted  one with an arm template. Why does it take a week?

**Comment by JimBarber** [comment]
I have the same issue.
All our subscriptions are under the same TenantID so I would have thought that would be a more suitable check than using the SubscriptionID to prevent others from talking your ServiceBus name space immediately after you've deleted yours.

**Comment by aspiringtfsguru** [comment]
Having the same issue here. Would love to know how to resolve.

**Comment by bunceg** [comment]
There isn't really a resolution so far - probably due to the way the service bus registers with DNS I'm guessing?

My work around has been to add a random string to the end of each creation step, e.g. (based on an ARM template) namespace equals something like: 

> [concat(parameters('sbNamespace'),uniqueString(resourceGroup().id))]

where the uniqueString helps make the namespace unique each time

**Comment by aspiringtfsguru** [comment]
So here's why it takes a week: 
[Error Code: 400--The namespace name is previously used in another project and has been deleted less than one week.](https://social.msdn.microsoft.com/Forums/en-US/8b0efb21-3903-4690-890e-fc373eec77d0/error-code-400the-namespace-name-is-previously-used-in-another-project-and-has-been-deleted-less?forum=servbus)

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
