### ISSUE TITLE
[Proposal] Get-AzureRmVMSize doesn't return MaxNicCount

### ISSUE THREAD

**Issue by ShuheiUda** [Azure/azure-powershell#2903]
### Cmdlet(s)
Get-AzureRmVMSize 

### PowerShell Version
PSVersion: 5.1.14393.103

### Module Version
AzureRM.Compute: 2.0.1

### OS Version
BuildVersion: 10.0.14393.103

### Description
(This is a proposal, not issue.)

Get-AzureRmVMSize is nice cmdlet, but doesn't return MaxNicCount.
When I'm creating scripts for customers, I need this feature for validating input parameters.

### Debug Output
> Get-AzureRmVMSize -Location japaneast

MaxDataDiskCount     : 1
MemoryInMB           : 768
Name                 : Standard_A0
NumberOfCores        : 1
OSDiskSizeInMB       : 1047552
ResourceDiskSizeInMB : 20480

### Script/Steps for Reproduction
n/a

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this proposal?

**Comment by singhkays** [comment]
@ShuheiUda Good idea! I'll send this to the dev team for consideration in the next round of planning. To set time expectations, our team plans in 6 months cycles so this is likely to come up for planning in Nov/Dec.

**Comment by ShuheiUda** [comment]
@singhkays Great!
Thank you very much.

**Comment by singhkays** [comment]
@ShuheiUda If you haven't already, could you add this feature request to uservoice and paste the link here to your idea. This will help the engineering team stack rank this come next planning cycle
https://feedback.azure.com/forums/216843-virtual-machines
