### ISSUE TITLE
Cmdlet "Set-AzureServiceExtension" checks "Service" as storage account name.

### ISSUE THREAD

**Issue by Seohol** [Azure/azure-powershell#291]
if you have 1-2 letters domain (like a.cloudapp.net), Set-AzureServiceExtension doesn't works

Set-AzureServiceExtension : The storage account name 'a' is invalid.  Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.

**Comment by Karamell** [comment]
Is this the same as issue #267 ?

**Comment by hyonholee** [comment]
Same issue and fixed:  https://github.com/Azure/azure-powershell/issues/267
