### ISSUE TITLE
Add-AzureRmLoadBalancerInboundNatRuleConfig : A parameter cannot be found that matches parameter name 'BackendIpConfiguration'.

### ISSUE THREAD

**Issue by skeezwiz** [Azure/azure-powershell#2910]
### Cmdlet(s)

Add-AzureRmLoadBalancerInboundNatRuleConfig
### PowerShell Version

Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
3.0 but im using azure v1.4.0
### OS Version

Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
6.2.9200.16481
### Description

Add-AzureRmLoadBalancerInboundNatRuleConfig : A parameter cannot be found that matches parameter name 'BackendIpConfiguration'.
### Debug Output

Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

At line:1 char:130
- ... n $frontendIP1 -BackendIpConfiguration $NIC.IpConfigurations[0] -IdleTimeoutInMi ...
-                    ~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidArgument: (:) [Add-AzureRmLoad...ndNatRuleConfig], ParameterBindingException
  - FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.Network.AddAzureLoadBalancerInboundNatRuleConfigCommand
### Script/Steps for Reproduction

$LoadBalancer | Add-AzureRmLoadBalancerInboundNatRuleConfig -Name "nat_rule_tcp_IP1_49157" -FrontendIpConfiguration $frontendIP1 -BackendIpConfiguration $NIC.IpConfigurations[0] -IdleTimeoutInMinutes 4  -Protocol TCP -FrontendPort 49157 -BackendPort 49157 | Set-AzureRmLoadBalancer

**Comment by markcowl** [comment]
@deepakrajendranmsft can you take a look

**Comment by maddieclayton** [comment]
Closing - there is no parameter "BackendIpConfiguration".

**Comment by iricigor** [comment]
This is weird. How do you specify BackendIpConfiguration if there is no such parameter? Where Load Balancer will send traffic matching this rule?

Here is a screenshot from the portal which is using backend IP configuration
![image](https://user-images.githubusercontent.com/15923171/54525908-7f76bc80-4975-11e9-94b7-9da2f9874994.png)
