### ISSUE TITLE
[2.1.0] AzureRM.Compute fails to install 

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#2917]
If I try to install AzureRM module (or just AzureRM.Compute) module installation fails with the error:

```
PackageManagement\Install-Package : A command with name 'New-AzureVMSqlServerAutoBackupConfig' is already available on
this system. This module 'AzureRM.Compute' may override the existing commands. If you still want to install this module
'AzureRM.Compute', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1661 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Packag
   eManagement.Cmdlets.InstallPackage
```

When did -AllowClobber become needed for installation of Azure and AzureRM modules?
Why is ARM-based cmdlets overlapping with ASM-based cmdlet, `New-AzureVMSqlServerAutoBackupConfig`  (Shouldn't ARM-based cmdlet have AzureRm prefix)?

**Comment by markcowl** [comment]
@alexandair  This is a change in PowerShell, and not in the modules.

**Comment by markcowl** [comment]
@kirthik We probably need to make sure to document this in a blog post, it looks like 5.1 is starting to be installed in more places.

**Comment by kilasuit** [comment]
Well yeah 

>  it looks like 5.1 is starting to be installed in more places.

PS 5.1 is installed by default in Win10 Anniversary update so issues like this and anything else relating to the ***undocumented & unversioned*** changes to PowerShellGet are going to sting you and other's in the near future.

For reference PowerShellGet has been at version 1.0.0.1 since the first Windows 10 build and even today is still at 1.0.0.1 in Win10 build 14915 yet there have been significant changes to the module in the last year

**Comment by markcowl** [comment]
@kirthik Assigning to you for updating the documentation to mentioning this - this should be in the 'Getting Started' document for Azure PowerShell, where we discuss acquiring the cmdlets.

**Comment by cormacpayne** [comment]
@markcowl @twitchax here is the list of conflicting cmdlets:

Network
- New-AzureVMSqlServerAutoBackupConfig 
    - cmdlet name in RDFE and ARM
- New-AzureVMSqlServerAutoPatchingConfig
    - cmdlet name in RDFE and ARM
- New-AzureVMSqlServerKeyVaultCredentialConfig
    - cmdlet name in RDFE and ARM

Profile
- Enable-AzureDataCollection 
    - cmdlet name in RDFE, alias for Enable-AzureRmDataCollection in ARM
- Disable-AzureDataCollection
    - cmdlet name in RDFE, alias for Disable-AzureRmDataCollection in ARM

**Comment by twitchax** [comment]
We should split this into two issues: one for network, and one for us.

If at all possible, I propose that we include this in our post-moratorium release as it will be a breaking change.

**Comment by cormacpayne** [comment]
Fix in PR https://github.com/Azure/azure-powershell/issues/3882

**Comment by markcowl** [comment]
This is fixed in the module just released.  No more ```-AllowClobber``` yay!
