### ISSUE TITLE
$s = Get-AzureSubscription with multiple subscriptions has indexing problems

### ISSUE THREAD

**Issue by Rick-Anderson** [Azure/azure-powershell#292]
On VMs with only one subscription, the following code works fine:
PS C:\TfsOnline\Altostratus\PowerShell> $s = Get-AzureSubscription -Current
PS C:\TfsOnline\Altostratus\PowerShell> $s.Accounts[1].id
B74D7681B47B7277D21840616DA059AE59316202

On machines with two subscriptions, the same code I need to change the index to Zero from one
PS C:\tfsOnline\Altostratus\PowerShell> $s.Accounts[1].id
rikandez@microsoft.com
PS C:\tfsOnline\Altostratus\PowerShell> $s.Accounts[0].id
3557C91530A4766719A81E56580FF900B8618D11:

So on this machine, I'm forced to change the index on my script.

**Comment by markcowl** [comment]
@Rick-Anderson Thanks for reporting this, we are investigating

**Comment by hovsepm** [comment]
@Rick-Anderson, The order of the accounts in the subscription is non-deterministic. Please use the type property of the account to differentiate between certificates and AD accounts.
