### ISSUE TITLE
Remove need for -AllowClobber in Azure / AzureRM< side-by-side installation

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2920]
### Description

Need to remove the need for `-AllowClobber` on later versions of PowerShell when installing AzureRM side-by-side with Azure.  This means
- Identify clashing cmdlets and Aliases.
- Remove duplicated aliases
- Deprecate cmdlets from AzureRM that use the Azure\* name and duplicate cmdlets in Azure
- Add static checks to validate that cmdlets are not duplicated between the modules

This is the long term solution for #2917

**Comment by cormacpayne** [comment]
@markcowl here is the list of conflicting cmdlets:

Network
- New-AzureVMSqlServerAutoBackupConfig 
    - cmdlet name in RDFE and ARM
- New-AzureVMSqlServerAutoPatchingConfig
    - cmdlet name in RDFE and ARM
- New-AzureVMSqlServerKeyVaultCredentialConfig
    - cmdlet name in RDFE and ARM

Profile
- Enable-AzureDataCollection 
    - cmdlet name in RDFE, alias for Enable-AzureRmDataCollection in ARM
- Disable-AzureDataCollection
    - cmdlet name in RDFE, alias for Disable-AzureRmDataCollection in ARM

**Comment by markcowl** [comment]
Fixed.

**Comment by guillemsola** [comment]
when is this planned to be released?

It seems that Idontknow broke my AzureRM installation... I was unnable to install it again without the clobber option.

```
PS C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell> install-module AzureRm

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure
you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
PackageManagement\Install-Package : A command with name 'Get-AzureStorageContainerAcl' is already available on this system. This module 'Azure.Storage' may override the existing
commands. If you still want to install this module 'Azure.Storage', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PS C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell> Install-Module AzureRM -AllowClobber
```

**Comment by cormacpayne** [comment]
@guillemsola this fixed was shipped in the May release of Azure PowerShell (version 4.0.0). I have been unable to reproduce this error when removing all modules from my machine and running `Install-Module -Name AzureRM` and then `Install-Module -Name Azure` (or vice versa). I just tried this on 4.1.0 and was unable to reproduce this error. Would you mind removing all Azure PowerShell modules from your machine and try to run the two commands again?

**Comment by guillemsola** [comment]
@cormacpayne I found that my issue was due to an old installation with the MSI. I think that this came with Visual Studio 2017. Before that I has installed AzueRM module with powershell.

All my modules where very old so I uninstalled them and reinstalled AzureRM with PS.

![image](https://user-images.githubusercontent.com/610476/27053956-8dc43166-4fbf-11e7-8085-6cdaa67c7887.png)

```
Name                            Version
----                            -------
AzureRM.ApiManagement           2.1.0  
AzureRM.Automation              2.1.0  
AzureRM.AzureStackAdmin         0.10.0 
AzureRM.AzureStackStorage       0.10.0 
AzureRM.Backup                  2.1.0  
AzureRM.Batch                   2.1.0  
AzureRM.Cdn                     2.1.0  
AzureRM.CognitiveServices       0.3.0  
AzureRM.Compute                 2.1.0  
AzureRM.DataFactories           2.1.0  
AzureRM.DataLakeAnalytics       2.1.0  
AzureRM.DataLakeStore           2.1.0  
AzureRM.DevTestLabs             2.1.0  
AzureRM.Dns                     2.1.0  
AzureRM.HDInsight               2.1.0  
AzureRM.Insights                2.1.0  
AzureRM.KeyVault                2.1.0  
AzureRM.LogicApp                2.1.0  
AzureRM.MachineLearning         0.10.0 
AzureRM.Media                   0.2.0  
AzureRM.Network                 2.1.0  
AzureRM.NotificationHubs        2.1.0  
AzureRM.OperationalInsights     2.1.0  
AzureRM.PowerBIEmbedded         2.1.0  
AzureRM.Profile                 2.1.0  
AzureRM.RecoveryServices        2.1.0  
AzureRM.RecoveryServices.Backup 2.1.0  
AzureRM.RedisCache              2.1.0  
AzureRM.Resources               3.1.0  
AzureRM.Scheduler               0.10.0 
AzureRM.ServerManagement        2.1.0  
AzureRM.SiteRecovery            2.1.0  
AzureRM.Sql                     2.1.0  
AzureRM.Storage                 2.1.0  
AzureRM.StreamAnalytics         2.1.0  
AzureRM.Tags                    2.1.0  
AzureRM.TrafficManager          2.1.0  
AzureRM.UsageAggregates         2.1.0  
AzureRM.Websites                2.1.0  
Azure                           2.1.0  
Azure.Storage                   2.1.0  
```

**Comment by cormacpayne** [comment]
@guillemsola okay great, so you are no longer seeing the issue when you remove the old modules and install the new ones? (4.0.0 or later)

**Comment by guillemsola** [comment]
@cormacpayne I installed both and once removed the old MSI installation issue was not anymore.
