### ISSUE TITLE
[Documentation]:  Add Help documentation based on platyPS

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2921]
### Description

Add doicumentationto repo on how to author help usinbg markdown and platyPS

- How to generate help files
- How to create the help xml for check-in
- How to check on help file completeness

Documentation should be added to the documentation folder in the repo, referenced from the debeloper guide wiki and from the readme.md in the documentation folder, and announced to partners.

### Cost: 2

**Comment by cormacpayne** [comment]
The platyPS team is releasing v0.7.1 for us on Friday to fix a few issues that were caught during testing. The milestone for v0.7.1 can be found [here](https://github.com/PowerShell/platyPS/milestone/6).

**Comment by cormacpayne** [comment]
Documentation found in the following PR: https://github.com/Azure/azure-powershell/pull/2932

**Comment by markcowl** [comment]
Fixed
