### ISSUE TITLE
Add build steps and process for retainign help in markdown

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2922]
### Description

Add opt-in mechanism for retaining help in markdown (side by side with checked-in xml help).  This should include the following:
- Automatically generate help.xml from markdown at build time and place in appropriate location (DEBUG or RELEASE builds)
- Automatically detect omissions from the help as warnings during build process
- Automatically fail for required help - no help for cmdlet, no help for parameter.  Include exception mechanism so individual cmdlets can be excepted.
- Provide tools / docs for regenerating markdown after changes
- Document how to opt-in in documentation, as well as how to update cmdlet help whe updatingcmdlets.

Cost: 4

**Comment by cormacpayne** [comment]
DONE
- `New-ServiceMarkdownHelp` cmdlet will help partner teams use platyPS to on-board this new model of documentation
- `Update-ServiceMarkdownHelp` cmdlet allows partners to update cmdlet help when updating cmdlets
- `Validate-ServiceMarkdownHelp` cmdlet will detect omissions from help and will fail for required help
- Documentation has been added for on-boarding platyPSHelp and maintaining the markdown files

TODO
- Automatically generate dll-Help.xml from markdown at build time and place in appropriate location
- Use `Validate-ServiceMarkdownHelp` during build process to detect omissions

**Comment by cormacpayne** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/issues/3583
