### ISSUE TITLE
[Documentation]:  Add document to documentation folder on how to run and re-record tests

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2924]
### Description

Include simple instructions on how to run tests in playback mode and how to run live an re-record (Documentation/testing.md)

- Include simple description of necessary environment variable and connection string settings
  - recording tests against prod
  - recording tests against PPE environment
  - runnign tests in playback mode
- Verify that scenarios work for accessing management and graph.rbac clients
- Add links to document in documentation/readme.md and in the developer guide

### Cost: 2

**Comment by shahabhijeet** [comment]
PR
https://github.com/Azure/azure-powershell/pull/3051
