### ISSUE TITLE
Prepare compatibility tool for partner release

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2925]
### Description

Enable / require partners to provide scripts to compatibility tool as part of breaking changes and deprecations.
-  Add compatibility tool cmdlet to AzureRM cmdlets - tool should read compatibility scripts from each cmdlet and module and print a compatibility report for any passed-in scripts
- Document for partners on how to create a compatibility report for their cmdlets,   and process/mechanism for consuming these reports in the AzureRM cmdlet.  Add to documentation repo. 
- Write document on using the compatibility tool, and add help to the compatibility tool itdelf.

**Comment by maddieclayton** [comment]
Closing in favor of the current migration guide.
