### ISSUE TITLE
Document process for communicating breaking changes

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2926]
### Description
- Add tools for creating 'About_RP_Breaking_Changes' document to an RP - whenever part of an API is deprecated, or there is a breaking change, adding to this document should be required.
- Add tools to build this document into the help for each RP
- Add tool to build a central 'About_Breaking_Changes_ document based on individual breaking changes document for each RP
-  Add documentation in Documentation folder documenting the process for partners
  - Include description of breaking changes and compatibility script as requirements in the documentation

**Comment by cormacpayne** [comment]
@markcowl what is the difference between this issue and https://github.com/Azure/azure-powershell/issues/3028 ?
