### ISSUE TITLE
[Investigate]: Automatic creation of breaking change document

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2927]
### Description

Need a prototype that does the following:
- Create serialization file for each cmdlet (is this just the help file) documenting the API
- Compare changes between documented API and current API
- Create compatibility tool scripts to print compatibility warnign based on breaking changes
- Create tool to create a new serialization for the API

**Comment by cormacpayne** [comment]
I believe this issue has been resolved with the addition of the breaking change tool in StaticAnalysis.
