### ISSUE TITLE
Get-AzureResource returns InvalidFilterInQueryString when specifying a valid value to the -Tag parameter

### ISSUE THREAD

**Issue by janegilring** [Azure/azure-powershell#293]
Get-AzureResource example from the help-system:

    --------------------------  Example 5: Get a resource by its tag  --------------------------   
 PS C:\>Get-AzureResource -Tag @{Name="Department";Value="IT"}        
This command gets resources that have a tag named "Department with a value of "IT".

Based on the example, shouldn`t the following work?

Get-AzureResource -ResourceType Microsoft.ClassicCompute/virtualMachines -Tag @{Name='applicationType';Value='isim'}
InvalidFilterInQueryString: Invalid $filter 'resourceType eq 'Microsoft.ClassicCompute/virtualMachines' and tagname eq 'applicationType' and tagvalue eq 'isim'' specified in the
query string. (raised by: Get-AzureResource)

As a workaround, the following works:
Get-AzureResourceGroup -Tag @{Name='applicationType';Value='isim'} | Get-AzureResource -ResourceType Microsoft.ClassicCompute/virtualMachines

Also, adding -ResourceGroupName doesn`t seem to make any difference:
 PS C:\> Get-AzureResource -ResourceType Microsoft.ClassicCompute/virtualMachines -Tag @{Name='applicationType';Value='isim'} -ResourceGroupName ISIM
InvalidFilterInQueryString: Invalid $filter 'resourceType eq 'Microsoft.ClassicCompute/virtualMachines' and tagname eq 'applicationType' and tagvalue eq 'isim'' specified in the
query string. (raised by: Get-AzureResource)

If I remove the ResourceType parameter, the error is gone but there are not results:
 PS C:\>Get-AzureResource -Tag @{Name='applicationType';Value='isim'} -ResourceGroupName ISIM

**Comment by vivsriaus** [comment]
@janegilring microsoft.classiccompute resource provider does not support tags. Please use the new compute resource provider (Microsoft.Compute) to get tags support.
