### ISSUE TITLE
Automate smoke testing of installer and packages

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2930]
### Description

Automate running the installer smoke tests and dependency analyzer to verify a new installation
- Update static analysis tool to run only Dependency Analyzer and execute on packages as well as msi
- Update ttest scripts to use service principal creds (ARM) and cerificate credentials (RDFE)
- Place both sets of credentials into KeyVault for use durign execution
- Add code to extract and use keyvault credentials in scripts

### Cost: 4

**Comment by shahabhijeet** [comment]
https://github.com/Azure/azure-powershell/pull/3076
