### ISSUE TITLE
New-AzurermResourcegroupDeployment cmdlet needs a parmeter that accepts the template as a json string

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#2933]
### Cmdlet(s)

New-AzureRmResourceGroupDeployment
### PowerShell Version

2.1.0
### Module Version

3.1.0
### Description

New-AzurermResourcegroupDeployment cmdlet needs a parmeter that accepts the template as a json string
Rightnow it accepts only a file or uri as a parameter, There are situations where it is easy create a hash and then converto json to pass as a parameter in the scripts. Inline json also helps to understand what template actually contains

**Comment by markcowl** [comment]
@ravbhatnagar Can you take a look?

**Comment by cormacpayne** [comment]
The fix for this will be available in the upcoming release of `Az` (version 1.5.0 released on March 12th, 2019)
