### ISSUE TITLE
Setting WebApp diagnostic logs to blob fails

### ISSUE THREAD

**Issue by Hijdra** [Azure/azure-powershell#2938]
### PowerShell Version

Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
PSVersion: 5.0.10240.16384
### Module Version

AzureRM: 2.1.0
### OS Version

Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

BuildVersion: 10.0.10240.16384
### Description

I am trying to set the diagnostic logs for my webapp through powershell, but the 'sasUrl' properties are not set with the Set-AzureRmResource command.
When I set the 'sasUrl' properties through the [resources.azure.com](http://resources.azure.com) portal with the exact same values it goes successful.
### Script/Steps for Reproduction

Stripped down version of what I try to do:

``` powershell
$properties = @{
    applicationLogs = @{
        azureBlobStorage = @{
            level = "Information";
            sasUrl = "https://XXXXXXXXX.blob.core.windows.net/applogs?sv=2015-04-05&sr=c&sig=XXXXXXXXX&st=2016-09-14T08:57:53Z&se=2116-09-14T08:57:53Z&sp=rwdl";
        };
    };
    httpLogs = @{        
        azureBlobStorage = @{
            enabled = $true;
            sasUrl = "https://XXXXXXXXX.blob.core.windows.net/httplogs?sv=2015-04-05&sr=c&sig=XXXXXXXXX&st=2016-09-14T08:57:53Z&se=2116-09-14T08:57:53Z&sp=rwdl";
        };
        fileSystem = @{
            enabled = $false;
        };
    };    
}

Set-AzureRmResource -PropertyObject $properties -ResourceGroupName $resourcegroupname -ResourceType Microsoft.Web/sites/config -ResourceName "$webappname/logs" -ApiVersion 2015-08-01 -Force
```

To get a SAS token I used the following code:

``` powershell
$now = Get-Date
$expiry = $now.AddYears(100)
$storage = Get-AzureRmStorageAccount -ResourceGroupName $resourcegroupname -Name $storagename
$httplogs = Get-AzureStorageContainer -Context $storage.Context -Name $logscontainer
$httplogssastoken = $httplogs | New-AzureStorageContainerSASToken -Permission rwdl -StartTime $now -ExpiryTime $expiry -FullUri
```

**Comment by markcowl** [comment]
@akurmi can you take a look?

**Comment by m-moris** [comment]
I'm facing same situation.
Does anyone know workaround or solution?

**Comment by panchagnula** [comment]
Closing since this is a very old issue please file a new issue with the latest version of PowerShell commnadlets  if this is still a problem.
