### ISSUE TITLE
accelrated networking tests skipped due to nrp not rolled out

### ISSUE THREAD

**Issue by skomarag** [Azure/azure-powershell#2942]
### PowerShell Version

Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
### OS Version

Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
### Debug Output

Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by maddieclayton** [comment]
Looks like these tests have been enabled. Network skipped tests are also being tracked elsewhere.
