### ISSUE TITLE
New-AzureStoreAddOn throws certificate error 

### ISSUE THREAD

**Issue by manyrootsofallevil** [Azure/azure-powershell#2945]
### Cmdlet(s)

New-AzureStoreAddOn
### PowerShell Version

Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5      0      10586  494    
### OS Version

Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10     0      10586  494     
### Description

Running the command below, throws a certificate error

New-AzureStoreAddOn -Name Test2 -AddOn SendGrid -Plan Free -Location "North Europe"

Similar issue on Get-AzureStoreAddOn
### Debug Output

Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.core.windows.net/<subscriptionid>/CloudServices/

Headers:
x-ms-version                  : 2013-06-01

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Forbidden

Headers:
Date                          : Thu, 15 Sep 2016 05:43:05 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <Code>ForbiddenError</Code>
  <Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message>
</Error>

New-AzureStoreAddOn : ForbiddenError: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.
At line:1 char:1
- New-AzureStoreAddOn -Name Test2 -AddOn SendGrid -Plan Free -Location  ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [New-AzureStoreAddOn], CloudException
  - FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Store.NewAzureStoreAddOnCommand

DEBUG: 06:43:04 - NewAzureStoreAddOnCommand end processing.
DEBUG: 06:43:04 - NewAzureStoreAddOnCommand end processing.

**Comment by markcowl** [comment]
@manyrootsofallevil How are you authenticated in this case?  The certificate message is a general message for any unauthorized request, whether it uses certificate credentials or not, so either how you are authenticated and whether you have admin access to the subscription you are using are likely to be the issue

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
