### ISSUE TITLE
Get-AzureRmWebAppSlot return type

### ISSUE THREAD

**Issue by hbuckle** [Azure/azure-powershell#2985]
### Cmdlet(s)

Get-AzureRmWebAppSlot
### PowerShell Version

PSVersion                      5.1.14394.1000
### Module Version

Cmdlet          Get-AzureRmWebAppSlot                              2.1.0      AzureRM.Websites
### OS Version

BuildVersion                   10.0.14394.1000
### Description

Instead of writing each web app slot to the output stream Get-AzureRmWebAppSlot is returning a System.Collections.Generic.List<Microsoft.Azure.Management.WebSites.Models.Site> object. This means you can't send the output through the pipeline to where or select

**Comment by markcowl** [comment]
@akurmi This is just a matter of setting EnumerateCollection to true whe  you write to the output stream.  Please fix.

**Comment by panchagnula** [comment]
Assigning to myself to fix

**Comment by panchagnula** [comment]
this should now be fixed.
