### ISSUE TITLE
StaticAnalysis selective tests are ONLY failing on CI

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-powershell#2987]
StaticAnalysis tests are currently failing on CI.
Unable to repro locally.
Will need to investigate what is going on.
Failing Tests
1) ForceParameterWithoutSupportsShouldProcess 
2) AddVerbWithoutSupportsShouldProcessParameter 
3) ConfirmImpactWithoutSupportsShouldProcess 
4) ShouldContinueVerbWithoutForceSwitch

**Comment by markcowl** [comment]
Fixed
