### ISSUE TITLE
Remove-AzureRmResource Error

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2996]
![image](https://cloud.githubusercontent.com/assets/466713/18772679/3c84ac3c-8106-11e6-8185-38f61859212b.png)

**Comment by cormacpayne** [comment]
@pcgeek86 what version of Azure PowerShell are you using?

**Comment by pcgeek86** [comment]
@cormacpayne The latest 2.2

**Comment by markcowl** [comment]
@ravbhatnagar This looks like a piping issue, please make sure that there is a scenario test for this

**Comment by diwudd** [comment]
Fixed with PR https://github.com/Azure/azure-powershell/pull/3101 .
Resolving.
