### ISSUE TITLE
Add tests for CertificateType parameter for KeyVault cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3002]
The parameter `CertificateType` was added to the cmdlets `New-AzureKeyVaultCertificatePolicy` and `Set-AzureKeyVaultCertificatePolicy`, but there was no test coverage for this change.

Tests will need to be added before the November release to test this new parameter.

**Comment by markcowl** [comment]
@markcowl

**Comment by cormacpayne** [comment]
@maddieclayton would you mind taking a look to see if this has been resolved?

**Comment by maddieclayton** [comment]
@RandalliLama @schaabs Can we close this issue? It looks like you will have to create a DigiCert or GlobalSign account to test this cmdlet (which makes automation difficult), and the issue has been open for two years.  If you do not plan to add this test, we do need acknowledgement that we will not need to hot fix issues around this parameter, as there are no tests to help us catch possible issues.

Thanks
