### ISSUE TITLE
Add static analysis rule to fail cmdlets that do not use approved verbs

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3004]
### Description

Ensure that all cmdlets use an approved verb.  Throw a P1 issue for any cmdlet that does not.
- [x] Add test for new rule
- [x] Add rule to SignatureVerifier as one of the default rules that executes

**Comment by cormacpayne** [comment]
Fixed in PR https://github.com/Azure/azure-powershell/pull/3089
