### ISSUE TITLE
Empty nested deployment URI results in generic "internal server error"

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#3005]
### Cmdlet(s)
NewAzureResourceGroupDeploymentCmdlet

### PowerShell Version
5.1

### Module Version
2.2

### OS Version
Windows 10 Anniversary

### Description
Deploy a nested template with an empty string for its URI. Receive an "internal server error."

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

Deploy an ARM JSON "parent" template that declares a child template (deployment) with an empty URI.

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
  },
  "variables": {
  },
  "resources": [
		{
      "name": "master-nodes",
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2018-01-01",
      "properties": {
        "mode": "Incremental",
        "templateLink": {
          "uri": "",
          "contentVersion": "1.0.0.0"
        },
        "parameters": {
        }
      }
    }
  ]
}
```

**Comment by markcowl** [comment]
@pcgeek86 What is returned when you run Test-AzureRMResourceGroupDeployment?

**Comment by ravbhatnagar** [comment]
@TianoMS - PLease verify this. The service should be returning the correct error and code.

**Comment by ravbhatnagar** [comment]
This is a service side issue and will be fixed soon. Will not require a client side fix.
