### ISSUE TITLE
Make latest releases available on Chocolatey

### ISSUE THREAD

**Issue by stankovski** [Azure/azure-powershell#3010]
There is a choco package for azurepowershell but it's outdated. It would be nice to have the latest releases available as choco packages.

**Comment by markcowl** [comment]
@stankovski Is there a reason to prefer chocolatey packages over packages in the Gallery?

**Comment by kilasuit** [comment]
I personally don't agree with having Chocolatey and PowerShell Gallery packages for PowerShell packages - it's unneeded duplication of effort unless you are requesting for the MSI to be pushed to Chocolatey in which case I would suggest in moving to making use of the PowerShell Gallery for installation over the MSI installer.

**Comment by stankovski** [comment]
Currently we can automate provisioning of our build environment  (which includes net46, dotnet core, powershell 5, git, and whole bunch of other prerequisites) via choco packages. The only package that is not available is Azure PowerShell. Well technically it is available, but not the latest. Ideally I would like to install the entire chain from Chocolatey without having to worry about Powershell 5 being available on the machine, but if Gallery version of APS is on par with MSI I can live with that.

**Comment by stankovski** [comment]
By the way current choco installer for Azure PowerShell doesn't include an msi. It downloads one from GitHub releases.

**Comment by kilasuit** [comment]
You can if not running PSv5 (though why aren't you is a totally different question) install package management (the bits that allow you to install from the PSGallery) on systems with v3 or v4 - I blogged a script to do this at https://blog.kilasuit.org/2016/03/09/updated-quick-win-install-powershell-package-management-on-systems-running-powershell-v3-v4/

**Comment by stankovski** [comment]
I'm dealing with Server 2012 R2 Azure VMs that do not come with PSv5 by default. I know I'm being picky here, but I'd like to be able to install my tools via say VM Extension script without needing to reboot the machine.

**Comment by markcowl** [comment]
@stankovski You can also use the official msi for PowerShellGte cmdlets on v3 and v4:  https://www.microsoft.com/en-us/download/details.aspx?id=51451

**Comment by kilasuit** [comment]
@stankovski - there is another way to download the modules from the PowerShell Gallery without needing the PowerShellGet module (or PackageManagement) installed on the machines.

I'm in process of finishing off building the script that can do this for any module on the PowerShellGallery including any dependencies that module would have and expect to have it completed by the end of the week which should in my opinion realistically negate the need for a Chocolately package. I intend to (ironically) release it to the PowerShell Gallery and also as an Azure Runbook. 

Would that help to negate your need for a chocolatey package?

**Comment by markcowl** [comment]
We are moving toward requiring PowerShell 5, so requiring PowerShell Gallery should not eb an issue
