### ISSUE TITLE
Shorten Paths for RecoveryServices.Backup

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-powershell#3015]
Currently we are seeing multiple issues across various services where the entire paths are creating CI to fail.
As a long term remediation, we should revisit some of the directory structure that exists currently in PS branch.
In this case, can you shorten the below path (for e.g. your path might change to an appropriate shorter name)
src\ResourceManager\RecoveryServices.Backup\Commands.RecoveryServices.Back up.Test\SessionRecords\Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.ContainerTests\TestGetBackupManagementServer.json"
to
src\ResourceManager\RecoveryServices.Backup\Back up.Test\SessionRecords\ScenarioTests.ContainerTests\TestGetBackupManagementServer.json"

In case during shortening the path, you end up having issue that it cannot build or builds assembly with an incorrect name, start using Name property in project.json. You no longer need to have directory name to create assembly name for your project.
https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json

**Comment by markcowl** [comment]
I beleieve this has been resolved.  Please reopen if there is still an issue,
