### ISSUE TITLE
SecureString should be used for CertificatePassword parameter in New-AzureRmWebAppSSLBinding

### ISSUE THREAD

**Issue by mattmcloughlin** [Azure/azure-powershell#3019]
New-AzureRmWebAppSSLBinding
https://msdn.microsoft.com/en-us/library/mt692594.aspx

PowerShell Version: 5.0.10586.494
OS Version: 10.0.10586.494

The cmdlet parameter "CertificatePassword" is of type "String".  This cmdlet should instead use the "SecureString" type.

See the Export-PfxCertificate cmdlet as an example: https://technet.microsoft.com/en-us/library/hh848635.aspx

**-Password[SecureString]**
Specifies the password used to protect the exported PFX file. The password should be in the form of secure string. Either the ProtectTo or this parameter must be specified, or an error will be displayed.

**Comment by markcowl** [comment]
@mattmcloughlin This is generally a good practice to avoid cleartest passwords in command lines.  However, the API itself uses a string, so it would be a bit disingenuous to pretned that the value is protected in memory through the call.  In this instance do you think it is better to be transparent that this value is not a securestring on the wire, or to use a SecureString and keep the password from appearing in cleartest on the screen?

@twitchax @Nking92 What are your thoughts about this?

**Comment by twitchax** [comment]
I agree with @markcowl: if the underlying API works on plaintext, then we should expose this same behavior to the surface present in PowerShell.

I propose that we leave it as is until such a time that the underlying API moves away from plaintext behaviors.

**Comment by markcowl** [comment]
Closing.
