### ISSUE TITLE
Ensure all top level resources can list by Subscription

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#3030]
### Cmdlet(s)

Get-AzureRmVirtualNetworkGatewayConnection
### PowerShell Version

Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
### Module Version

2.2.0
### OS Version

Windows 10 Anniversary Update
### Description

Get-AzureRmVirtualNetworkGatewayConnection shouldn't have mandatory ResourceGroupName parameter
### Script/Steps for Reproduction

``` powershell
Get-AzureRmVirtualNetworkGatewayConnection
```

![image](https://cloud.githubusercontent.com/assets/466713/18919626/275811dc-855c-11e6-9bfc-66f868ec9f27.png)

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by pcgeek86** [comment]
@markcowl @ravbhatnagar  we need to add an automated test for this, that fails the build if any cmdlets require this parameter. I've had to report many other similar circumstances separately. Let's handle this globally for all cmdlets.

#2260 
#2628 
#2297

**Comment by pcgeek86** [comment]
There might be a few, specific exceptions that would require the `-ResourceGroupName` parameter. For now, I can think of the cmdlets that are part of the `AzureRM.Resources` generic ARM module. If you find others, they can be added as exceptions to the automated test.

**Comment by markcowl** [comment]
@pcgeek86 I'm not sure that adding a check across the board is the right solution.  There are a few things that could be in play:

- For some kinds of resources, listing across the entire subscription isn't particularly useful, some Sql resources (firewall rules) and other kinds of subresources fall into this category
-Some RPs don't have this functionality in their API
- Some RPs do have theis functionality and didn't implement it correctly - for example, they have the wrong default parameter set, or just required a resource group for list

For 2 and 3, we definitely should require this, and this should be part of our design guidelines.  I don't know how large category (1) is.  If it's small enough, then having a static analysis rule for this makes sense. 

@twitchax  @ravbhatnagar  comments?

**Comment by markcowl** [comment]
@twitchax Assigning to you - we need to verify that this is the correct thing to do, and if so, we can enforce it on checkins relatively easily

**Comment by twitchax** [comment]
Approved for Static Analysis rule.  Probably post May 2017.

**Comment by maddieclayton** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/issues/6549
