### ISSUE TITLE
AzureResourceGroupDeployment : Deployment 'xyz' could not be found on the first 5 seconds check

### ISSUE THREAD

**Issue by nelsonmorais** [Azure/azure-powershell#3031]
### PowerShell Version
Name                           Value
----                           -----
PSVersion                      5.1.14393.187
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.187
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### OS Version
See above

### Description
During the execution of a VSTS Release Definition that has an environment configured with the task "Azure Resource Manager Deployment" (AzureResourceGroupDeployment version 1.0.88) to deploy an ARM template, we are receiving the following error:

2016-09-28T15:10:37.3764152Z ##[command]Import-Module -Name C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Profile\AzureRM.Profile.psd1 -Global
 
2016-09-28T15:10:37.5170418Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant 75b2f54b-feff-400d-8e0b-67102edb9a23 -Credential System.Management.Automation.PSCredential
 
2016-09-28T15:10:38.0326622Z ##[command]Select-AzureRMSubscription -SubscriptionId XXX -TenantId XXX
 
**2016-09-28T15:10:39.4389168Z [Azure Resource Manager]Creating resource group deployment with name masterDeploy-20160928-1510**
 
2016-09-28T15:10:48.7201851Z ##[debug]17:10:48 - Template is valid.
 
2016-09-28T15:10:48.7358193Z ##[debug]17:10:48 - Create template deployment 'masterDeploy-20160928-1510'
 
**2016-09-28T15:10:48.7358193Z ##[debug]17:10:48 - Checking deployment status in 5 seconds**
 
**2016-09-28T15:10:54.7047068Z ##[error]Deployment 'masterDeploy-20160928-1510' could not be found.**

We are receiving this error several times when we try to deploy the template to US Central region (the same template when deployed to West Europe runs without problems)

### Debug Output
How can we specify the  `$DebugPreference="Continue"` on the VSTS Task?

### Script/Steps for Reproduction
Our template has close to 1700 lines, and it fails with the message above most of the times when we try to deploy it. Some times (very few) we can run the task without problems. The deploy it self runs successfully (we confirmed this on the Azure portal)

The thread bellow is similar to this one, but it is now closed after a fix was applied, but we're seeing the same behavior when the VSTS deploy task is executed:
https://github.com/Azure/azure-powershell/issues/2416

Is there any workaround than we can use to avoid the script to fail? Maybe increasing the first check on the first 5 seconds to a longer time?

**Comment by markcowl** [comment]
@ravbhatnagar can you take a look?

@bmoore-msft  any pointers on turning on debug stream logging in powershell using the VS plug-in?

**Comment by bmoore-msft** [comment]
@markcowl - it looks like this is using the built in VSTS build task (not the Visual Studio script)...  

@nelsonmorais - what version of AzurePS is running on the build server?  Is it possible the build server has an older version that does not have the fix from the referenced issue?

**Comment by nelsonmorais** [comment]
@bmoore-msft - Hi Brian, here's what I get after executing the command: Get-Module -ListAvailable -Name Azure -Refresh

    Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.5.0      Azure                               {Get-AzureAutomationCertificate, Get-AzureAutomationConnec...

So apparently, according to #2416 I guess I need to update to version 1.5.1, is this correct?

**Comment by bmoore-msft** [comment]
@markcowl / @ravbhatnagar probably need to confirm, but it won't hurt to try it...

**Comment by nelsonmorais** [comment]
@bmoore-msft Or maybe to the latest version according to https://github.com/Azure/azure-powershell/releases

**Comment by bmoore-msft** [comment]
Even better ;)

**Comment by nelsonmorais** [comment]
I'll give a try tomorrow to see if it works and I'll post back the results. Thanks!

**Comment by nelsonmorais** [comment]
It's working now, so it seem the problem was the outdated AzurePS.
Thanks for your support!

**Comment by bmoore-msft** [comment]
Great - thanks for letting us know...

**Comment by ravbhatnagar** [comment]
Looks like this has been resolved. PLease let us know if you still run into this.
