### ISSUE TITLE
[AzureChinaCloud] : Classic Infrastructure Migration of Storage Account failing with  "InternalError : The server encountered an internal error"

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#3034]
Cmdlet(s)

**Move-AzureReservedIP
Move-AzureStorageAccount**

PowerShell Version

4.0

Module Version

2.0.1 (Azure)
3.0.1 (AzureRM.Resources)

OS Version

6.3.9600.17400
### Debug Output

**DEBUG: ============================ HTTP RESPONSE ============================**

Status Code:
Accepted

Headers:
Transfer-Encoding             : chunked
x-ms-servedbyregion           : chinaeast
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : def204dabbb4798c5a898
Cache-Control                 : no-cache
Date                          : Thu, 29 Sep 2016 14:06:08 GMT
Server                        : 1.0.6198.421,(rd_rdfe_stable.160905-1051),Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0

Body:

HTTP Method:
GET

Absolute Uri:
https://management.core.chinacloudapi.cn/45d5d842bf-9300-38ee4d3/operations/def204dab44798c5a8
98

Headers:
x-ms-version                  : 2016-03-01

**DEBUG: ============================ HTTP RESPONSE ============================**

Status Code:
OK

Headers:
x-ms-servedbyregion           : chinaeast
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 542bea2b4d824b1040874bc7
Cache-Control                 : no-cache
Date                          : Thu, 29 Sep 2016 14:06:08 GMT
Server                        : 1.0.6198.421,(rd_rdfe_stable.160905-1051),Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0

Body:
<Operation xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <ID>def204da-bbb4-44ab-b947-c5a898</ID>
  <Status>InProgress</Status>
</Operation>

**DEBUG: ============================ HTTP REQUEST ============================**

HTTP Method:
GET

Absolute Uri:
https://management.core.chinacloudapi.cn/45d0-38ee417d3/operations/def204da8c5a8
98

Headers:
x-ms-version                  : 2016-03-01

Body:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
**DEBUG: ============================ HTTP RESPONSE ============================**

Status Code:
OK

Headers:
x-ms-servedbyregion           : chinaeast
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : d922bbe664b54d56a2c26976
Cache-Control                 : no-cache
Date                          : Thu, 29 Sep 2016 14:06:39 GMT
Server                        : 1.0.6198.421,(rd_rdfe_stable.160905-1051),Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0

Body:
<Operation xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <ID>def204da-bbb4-44ab-c5a898</ID>
  <Status>Failed</Status>
  <HttpStatusCode>**500**</HttpStatusCode>
  <Error>
    <Code>**InternalError**</Code>
    <Message>The server encountered an internal error. Please retry the request.</Message>
  </Error>
</Operation>

**InternalError : The server encountered an internal error. Please retry the request.**
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
Move-AzureStorageAccount : InternalError : The server encountered an internal error. Please retry the request.
At line:1 char:1
- Move-AzureStorageAccount -StorageAccountName mcne0001vehrm -Prepare - ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Move-AzureStorageAccount], ComputeCloudException
  - FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.StorageServices.MoveStorageAccountComm
    and

**VERBOSE: 10:07:17 AM - Completed Operation: Move-AzureStorageAccount**
### Script/Steps for Reproduction

**Move-AzureStorageAccount -StorageAccountName storageaccountname -Prepare**

**Comment by markcowl** [comment]
@vinjiang can you take a look?

**Comment by blueww** [comment]
@markcowl, this cmdlet 'Move-AzureStorageAccount' is added by @hyonholee in commit https://github.com/Azure/azure-powershell/commit/1514e8c40ac252fbeae11fcf694c106b4ee33ac8 to compute team.
Would you please help to assign it to correct team? 
Thanks!

**Comment by blueww** [comment]
@hyonholee, assign the issue to you as the cmdlet 'Move-AzureStorageAccount' is added by you in commit  1514e8c .
Would you please help to look?
Thanks!

**Comment by hyonholee** [comment]
Internal server error is an error from server with various reasons.  Powershell cmdlets just pass the error message by the server, so if this case happens, you should contact the service.

**Comment by Pradebban** [comment]
Contact the service ?

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
