### ISSUE TITLE
Add documentation on StaticAnalysis failures

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3037]
### Description
-  [x] Add a document on static analysis failures to the documentation folder.  The document should describe 
  - [x] How to determine if your build is failing due to static anlalysis failures
  - [x] Where to find reports on static analyisis failures in ci and local builds
  - [x] What each static analysis failure meanshow to mitigate each of the static analysis failures
-  [x] Improve logging of failures to the console, so that failures are well formatted and mitigation for each is clear

**Comment by maddieclayton** [comment]
Fixed
