### ISSUE TITLE
Move-AzureStorageAccount and Move-AzureService : Parameter ordering incorrect/misleading

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#3038]
### Cmdlet(s)

Move-AzureStorageAccount
Move-AzureService
### PowerShell Version

4.0
### Module Version

2.0.1 (Azure)
3.0.1 (AzureRM.Resources)
### OS Version

6.3.9600.17400
### Description

In **Move-AzureStorage and Move-AzureService** - The positional parameters "Prepare"/"validate"/"commit"/"abort" is made before **"-StorageAccountName**"/ **"-ServiceName"**, which is misleading and not inline with the other Move-Resources commands like -  

Move-AzureReservedIP -ReservedIPName -Validate
Move-AzureNetworkSecurityGroup -NetworkSecurityGroupName -Validate 

Please make necessary changes to follow a particular standard.
### Script/Steps for Reproduction

Move-AzureStorageAccount -Validate -StorageAccountName "StorageAccountName"
Move-AzureService -Abort -ServiceName "ServiceName"

**Comment by markcowl** [comment]
@vinjiang can you take a look?

**Comment by vinjiang** [comment]
@markcowl , this cmdlet is not done by us. It can be compute team (Mahesh, sorry, I don't know his GitHub account).

**Comment by blueww** [comment]
@hyonholee, assign the issue to you as the cmdlet 'Move-AzureStorageAccount' is added by you in commit  1514e8c .
Would you please help to look?
Thanks!

**Comment by hyonholee** [comment]
This is an issue with Help document.

According to the Powershell code, the first position parameter of Move-AzureReservedIP is "Validate/Commit/Prepare/Abort", and the second position parameter of Move-AzureReservedIP is "ReservedIPName".  

You can check the position of the parameters with the following commands:

> (Get-Command Move-AzureReservedIP).Parameters["Validate"].Attributes[0].Position
0
> (Get-Command Move-AzureReservedIP).Parameters["ReservedIPName"].Attributes[0].Position
1

So we need to update the help document of Move-AzureReservedIP and Move-AzureNetworkSecurityGroup.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
