### ISSUE TITLE
Set-AzureRmSqlDatabaseAuditingPolicy "not working"/"no documentation" for multiple event types

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#3047]
Cmdlet(s)

Set-AzureRmSqlDatabaseAuditingPolicy
### PowerShell Version

4.0
### Module Version

2.0.1 (Azure)
3.0.1 (AzureRM.Resources)
### OS Version

6.3.9600.17400
### Description

Set-AzureRmSqlDatabaseAuditingPolicy not working with multiple event types to audit the events

The below command, shows no error- however the table in the storage accounts logs only "Login_Success". 
Event "Login_Failure" is not getting logged.

**Official documentation:**

https://msdn.microsoft.com/en-us/library/mt603531.aspx

-EventType<String[]>
Specifies the event types to audit. The acceptable values for this parameter are:

-- PlainSQL_Success
-- PlainSQL_Failure
-- ParameterizedSQL_Success
-- ParameterizedSQL_Failure
-- StoredProcedure_Success
-- StoredProcedure_Failure
-- Login_Success
-- Login_Failure 
-- TransactionManagement_Success
-- TransactionManagement_Failure
-- All
-- None

**You can specify several event types.** You can specify All to audit all of the event types or None to specify that no events will be audited. If you specify All or None at the same time, the cmdlet does not run.
### Script/Steps for Reproduction
1. Run the command targetting the server and database
   Set-AzureRmSqlDatabaseAuditingPolicy -AuditType Table -EventType Login_Failure,Login_Success -StorageAccountName pradebban -StorageKeyType Primary -RetentionInDays 90 -ServerName hiddenserver -ResourceGroupName hiddenresourcegrp -Verbose -TableIdentifier pradebban -DatabaseName hiddendatabase
2. Connect to the Table Storage and simulate login events ( both failure and success ) - only success would get logged.

Thanks,
Pradebban Raja

**Comment by cormacpayne** [comment]
@akromm Hey Adam, would you mind taking a look at this issue?

**Comment by akromm** [comment]
@yoavrubin
