### ISSUE TITLE
Set-AzureRmSqlServerAuditingPolicy "not working"/"no documentation" for multiple "event types"

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#3048]
Cmdlet(s)

Set-AzureRmSqlServerAuditingPolicy
### PowerShell Version

4.0
### Module Version

2.0.1 (Azure)
3.0.1 (AzureRM.Resources)
### OS Version

6.3.9600.17400
### Description

Set-AzureRmSqlServerAuditingPolicy not working with multiple event types to audit the events

The below command, shows no error- however the table in the storage accounts logs only "Login_Success". 
Event "Login_Failure" is not getting logged.
### Official documentation:

https://msdn.microsoft.com/en-us/library/mt603794.aspx

-EventType
Specifies the event types to audit. The acceptable values for this parameter are:

-- PlainSQL_Success
-- PlainSQL_Failure
-- ParameterizedSQL_Success
-- ParameterizedSQL_Failure
-- StoredProcedure_Success
-- StoredProcedure_Failure
-- Login_Success
-- Login_Failure 
-- TransactionManagement_Success
-- TransactionManagement_Failure
-- All
-- None

You can specify several event types. You can specify All to audit all of the event types or None to specify that no events will be audited. If you specify All or None at the same time, the cmdlet does not run.
### Script/Steps for Reproduction

Run the command targeting the server and database
Set-AzureRmSqlServerAuditingPolicy -AuditType Table -EventType Login_Failure,Login_Success -StorageAccountName pradebban -StorageKeyType Primary -RetentionInDays 90 -ServerName hiddenserver -ResourceGroupName hiddenresourcegrp -TableIdentifier pradebban

Connect to the Table Storage and simulate login events ( both failure and success ) - only success would get logged.

Thanks,
Pradebban Raja

**Comment by cormacpayne** [comment]
@akromm Hey Adam, would you mind taking a look at this issue?

**Comment by akromm** [comment]
@yoavrubin  Could you please investigate this.

**Comment by yoavrubin** [comment]
@Pradebban, when you call Get-AzureRmSqlServerAuditingPolicy for the same server, does the set of EventType is different from the set of EventType you sent using the Set-AzureRmSqlServerAuditingPolicy?

**Comment by Pradebban** [comment]
@yoavrubin , sorry am not able to understand your query, where am i sending the Event Type. Please be little more specific.

**Comment by yoavrubin** [comment]
The Set-AzureRmSqlServerAuditingPolicy cmdlet you run includes -EventType Login_Failure,Login_Success. After you make that call, can you call Get-AzureRmSqlServerAuditingPolicy for that same server and take a look at its output? what does the field EventType in the output contains?

**Comment by Pradebban** [comment]
EventType              : {Login_Success, Login_Failure}

**Comment by yoavrubin** [comment]
Have you set an auditing policy for the database you are connecting to (i.e., called Set-AzureRmSqlDatabaseAuditingPolicy for that database)?

**Comment by Pradebban** [comment]
No, nothing set on Database level auditing. - Disabled

**Comment by yoavrubin** [comment]
Can you provide the name of the server and database you are using and the timeframe when you ran these tests?

**Comment by Pradebban** [comment]
@yoavrubin, can you try to repro in another test server? for security purposes i may not be able to share the details of the server.

You can follow, ###Script/Steps for Reproduction

**Comment by yoavrubin** [comment]
I have tried to repro, but got a valid result. Is it possible that you have a blob auditing enabled? Can you call Disable-AzureRmSqlServerAuditing (for the server) and Disable-AzureRmSqlDatabaseAuditing (for your database) and then call Set-AzureRmSqlServerAduditing with the parameters you've described before

**Comment by Pradebban** [comment]
Do you mean Remove-AzureRmSqlServerAuditing and Remove-AzureRmSqlDatabaseAuditing. i dont see any cmdlet like Disable-AzureRmSqlServerAuditing / Disable-AzureRmSqlDatabaseAuditing

**Comment by yoavrubin** [comment]
Yes, my bad, Remove-*

**Comment by Pradebban** [comment]
I did remove SqlServerAuditing and SqlDatabaseAuditing and enabled SqlServerAduditing with the parameters i have described, Same results. Success is getting logged and Failure not.

**Comment by yoavrubin** [comment]
In an offline discussion with @Pradebban we were able to reproduce the issue. The team will start looking for a solution.

**Comment by cormacpayne** [comment]
@yoavrubin any update on the status of this issue?

**Comment by yoavrubin** [comment]
@Pradebban , can you try to connect using the secure connection string, i.e., <your-server-name>.database.secure.windows.net and check whether you see in the audit logs the failed logins?

**Comment by yoavrubin** [comment]
@cormacpayne - it is not an AzurePowershell issue, but rather something that is related to AzureSQL auditing. I will leave this issue open for now to allow it to be tracked.

**Comment by markcowl** [comment]
@akromm Can we make sure this is assigned appropriately?

**Comment by yoavrubin** [comment]
The solution is either to use the secure connection strings or to use blob auditing. After offline discussion with @Pradebban , the chosen solution was to move to blob auditing, this solves the problem.

**Comment by Pradebban** [comment]
@yoavrubin, Thanks! We are changing the implementation to use blob auditing due to the known limitations on using Tables for Auditing. Will confirm once we are able to get this working.
