### ISSUE TITLE
[AzureChinaCloud] : Classic Infrastructure Migration of Reserved IP failing with "InternalError : The server encountered an internal error"

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#3054]
#### Cmdlet(s)

Move-AzureReservedIP
#### PowerShell Version

4.0
#### Module Version

2.0.1 (Azure)
3.0.1 (AzureRM.Resources)

OS Version

6.3.9600.17400
### Debug Output

PS C:\Windows\system32> Move-AzureStorageAccount -StorageAccountName "hiddenstorage" -Prepare -Debug
DEBUG: 11:09:08 PM - MoveStorageAccountCommand begin processing with ParameterSet 'PrepareMigrationParameterSet'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: 11:09:10 PM - using account id '29A21569A69711A6A5D9A8AFC15DB87A8D06D285'...

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
VERBOSE: 11:09:10 PM - Begin Operation: Move-AzureStorageAccount

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.core.chinacloudapi.cn/45d5d889-49a6-42bf-9300-38ee43fb17d3/services/storageservices/hiddenstorage/migrat
ion?comp=prepare

Headers:
x-ms-version                  : 2016-03-01

Body:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Accepted

Headers:
Transfer-Encoding             : chunked
x-ms-servedbyregion           : chinaeast
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 3d9f0eeba79445449af0ff45995788eb
Cache-Control                 : no-cache
Date                          : Fri, 07 Oct 2016 03:09:14 GMT
Server                        : 1.0.6198.439,(rd_rdfe_stable.160930-1308),Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0

Body:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.core.chinacloudapi.cn/45d5d889-49a6-42bf-9300-38ee43fb17d3/operations/3d9f0eeba79445449af0ff45995788
eb

Headers:
x-ms-version                  : 2016-03-01

Body:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
x-ms-servedbyregion           : chinaeast
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 06b4a734223e43ad9722994080f85e8a
Cache-Control                 : no-cache
Date                          : Fri, 07 Oct 2016 03:09:15 GMT
Server                        : 1.0.6198.439,(rd_rdfe_stable.160930-1308),Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0

Body:
<Operation xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <ID>3d9f0eeb-a794-4544-9af0-ff45995788eb</ID>
  <Status>InProgress</Status>
</Operation>

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.core.chinacloudapi.cn/45d5d889-49a6-42bf-9300-38ee43fb17d3/operations/3d9f0eeba79445449af0ff45995788
eb

Headers:
x-ms-version                  : 2016-03-01

Body:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
x-ms-servedbyregion           : chinaeast
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : cddeb5ed1b774eeba42c588eb989d273
Cache-Control                 : no-cache
Date                          : Fri, 07 Oct 2016 03:09:46 GMT
Server                        : 1.0.6198.439,(rd_rdfe_stable.160930-1308),Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0

Body:
<Operation xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <ID>3d9f0eeb-a794-4544-9af0-ff45995788eb</ID>
  <Status>Failed</Status>
  <HttpStatusCode>500</HttpStatusCode>
  <Error>
    <Code>InternalError</Code>
    <Message>The server encountered an internal error. Please retry the request.</Message>
  </Error>
</Operation>

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):

Confirm
InternalError : The server encountered an internal error. Please retry the request.
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
Move-AzureStorageAccount : InternalError : The server encountered an internal error. Please retry the request.
At line:1 char:1
- Move-AzureStorageAccount -StorageAccountName "hiddenstorage" -Prepare -Debu ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Move-AzureStorageAccount], ComputeCloudException
  - FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.StorageServices.MoveStorageAccountComm
    and

VERBOSE: 11:09:58 PM - Completed Operation: Move-AzureStorageAccount

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: 11:09:59 PM - MoveStorageAccountCommand end processing.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: 11:09:59 PM - MoveStorageAccountCommand end processing.
### Script/Steps for Reproduction

PS C:\Windows\system32> Move-AzureStorageAccount -**Validate** -StorageAccountName "hiddenstorage"

OperationId        : 00ea177a-5a5ff07a7d4
Result             : **Succeeded**
ValidationMessages :

PS C:\Windows\system32> Move-AzureStorageAccount -StorageAccountName "hiddenstorage" -Prepare
Move-AzureStorageAccount : InternalError : **The server encountered an internal error. Please retry the request.**
At line:1 char:1
- Move-AzureStorageAccount -StorageAccountName "hiddenstorage" -**Prepare**
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Move-AzureStorageAccount], ComputeCloudException
  - FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.StorageServices.MoveStorageAccountComm
    and

Thanks,
Pradebban Raja

**Comment by markcowl** [comment]
@DeepakRajendranMsft can you take a look?

**Comment by Lickkylee** [comment]
We met the same error when trying to migrate storage account on AzureChinaCloud using either Azure CLI or powershell. I think it's more likely a RDFE bug. Anyone know how to fix this?

**Comment by Pradebban** [comment]
@cormacpayne could you please help on this one.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
