### ISSUE TITLE
Importing an azure sql database in ARM

### ISSUE THREAD

**Issue by rasmus91** [Azure/azure-powershell#3067]
### Cmdlet(s)

(AzureRM.Sql)
New-AzureRmSqlDatabaseImport
### PowerShell Version

```
         5.0.10240.17113                                                                                                                  
```
### Module Version

```
 Name         |  Version
```

AzureRM.Sql      1.0.9
### OS Version

10.0.10011.16384 
### Description

The parameter accepts only an int32 in 'DatabaseMaxSizeBytes' parameter. This creates an issue that the maximum in GB is: (((2147483647 / 1024) / 1024) / 1024) = 1,99

The workaround as is is to import the Database, then run "Set-AzureRmSqlDatabase -MaxSizeBytes" because MaxSizeBytes accepts a long, which means the limit would be:

(((9223372036854775807 / 1024) / 1024) / 1024) = 8589934592 Gb. And while this limit may just be a bit too much for Azure SQL to handle as well, it does at least allow bigger databases to Exist. With the < 2 GB limit, you may not even be able to import the file specified.
### Script/Steps for Reproduction

See the description.

**Comment by markcowl** [comment]
@akromm can you take a look?  Seems reasonable to make this parameter a long int

**Comment by akromm** [comment]
I will involve the required team.

**Comment by cormacpayne** [comment]
Fix has been merged.
