### ISSUE TITLE
Remove-AzureVM does not support the -WhatIf parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#307]
# Environment
- Windows 8.1 client
- Azure PowerShell module 0.8.15.1
- Windows Management Framework (WMF) Core 5.0 February 2015 Preview
# Issue

The `Remove-AzureVM` command is potentially highly destructive, and does not support the `-WhatIf` parameter.

![image](https://cloud.githubusercontent.com/assets/466713/6875161/90d13e7c-d482-11e4-95f1-248de64390d2.png)
# Recommended Action

The `Remove-AzureVM` should implement the `-WhatIf` parameter to prevent accidental destruction. Your customers will be thankful.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by 1RedOne** [comment]
To add to this, none of these **highly impactful** Azure cmdlets support -WhatIf today.  This is a serious problem.

- Remove-SSAccessControlRecord
- Remove-SSDeviceBackup
- Remove-SSDeviceBackupPolicy
- Remove-SSDeviceVolume
- Remove-SSDeviceVolumeContainer
- Remove-SSStorageAccountCredential
- Remove-WAPackEnvironment
- Stop-SSJob
- Stop-WAPackWebsite
- Remove-AzureAclConfig
- Remove-AzureAffinityGroup
- Remove-AzureApplicationGateway
- Remove-AzureApplicationGatewaySslCertificate
- Remove-AzureAutomationAccount
- Remove-AzureAutomationCertificate
- Remove-AzureAutomationConnection
- Remove-AzureAutomationConnectionType
- Remove-AzureAutomationCredential
- Remove-AzureAutomationModule
- Remove-AzureAutomationVariable
- Remove-AzureAvailabilitySet
- Remove-AzureCertificate
- Remove-AzureDataDisk
- Remove-AzureDeployment
- Remove-AzureDisk
- Remove-AzureDns
- Remove-AzureEndpoint
- Remove-AzureEnvironment
- Remove-AzureHDInsightCluster
- Remove-AzureInternalLoadBalancer
- Remove-AzureLocalNetworkGateway
- Remove-AzureManagedCache
- Remove-AzureManagedCacheNamedCache
- Remove-AzureNetworkInterfaceConfig
- Remove-AzureNetworkSecurityGroup
- Remove-AzureNetworkSecurityGroupAssociation
- Remove-AzureNetworkSecurityGroupConfig
- Remove-AzureNetworkSecurityGroupFromSubnet
- Remove-AzureNetworkSecurityRule
- Remove-AzurePublicIP
- Remove-AzureRemoteAppUser
- Remove-AzureRemoteAppVNet
- Remove-AzureReservedIP
- Remove-AzureReservedIPAssociation
- Remove-AzureRoute
- Remove-AzureRouteTable
- Remove-AzureSBAuthorizationRule
- Remove-AzureSchedulerJob
- Remove-AzureSchedulerJobCollection
- Remove-AzureServiceADDomainExtension
- Remove-AzureServiceAntimalwareExtension
- Remove-AzureServiceDiagnosticsExtension
- Remove-AzureServiceExtension
- Remove-AzureServiceRemoteDesktopExtension
- Remove-AzureSiteRecoveryNetworkMapping
- Remove-AzureSiteRecoveryStorageMapping
- Remove-AzureStaticVNetIP
- Remove-AzureStorageAccount
- Remove-AzureStoreAddOn
- Remove-AzureStorSimpleAccessControlRecord
- Remove-AzureStorSimpleDeviceBackup
- Remove-AzureStorSimpleDeviceBackupPolicy
- Remove-AzureStorSimpleDeviceVolume
- Remove-AzureStorSimpleDeviceVolumeContainer
- Remove-AzureStorSimpleStorageAccountCredential
- Remove-AzureSubnetRouteTable
- Remove-AzureTrafficManagerEndpoint
- Remove-AzureTrafficManagerProfile
- Remove-AzureVirtualIP
- Remove-AzureVirtualNetworkGateway
- Remove-AzureVirtualNetworkGatewayConnection
- Remove-AzureVMAccessExtension
- Remove-AzureVMBGInfoExtension
- Remove-AzureVMChefExtension
- Remove-AzureVMCustomScriptExtension
- Remove-AzureVMDiagnosticsExtension
- Remove-AzureVMExtension
- Remove-AzureVMImage
- Remove-AzureVMImageDataDiskConfig
- Remove-AzureVMImageOSDiskConfig
- Remove-AzureVMMicrosoftAntimalwareExtension
- Remove-AzureVMPuppetExtension
- Remove-AzureVMSqlServerExtension
- Remove-AzureVNetConfig
- Remove-AzureVNetGateway
- Remove-AzureVNetGatewayDefaultSite
- Remove-AzureWebsiteJob
- Remove-WAPackStaticIPAddressPool
- Remove-WAPackVMSubnet
- Remove-WAPackVNet
- Stop-AzureApplicationGateway
- Stop-AzureAutomationJob
- Stop-AzureEmulator
- Stop-AzureHDInsightJob
- Stop-AzureService
- Stop-AzureSiteRecoveryJob
- Stop-AzureStorSimpleJob
- Stop-AzureVirtualNetworkGatewayDiagnostics
- Stop-AzureVM
- Stop-AzureVNetGatewayDiagnostics
- Stop-AzureWebsite
- Stop-AzureWebsiteJob
- Stop-WAPackVM

**Comment by markcowl** [comment]
This is fixed now.  Closing
