### ISSUE TITLE
Update release process document to make release notes active on release

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3072]
### Description
- [x] Update release process to merge release->master before publishing modules to the gallery.  This step should happen just after publishing to the test gallery.
- [x] Ensure that the link to the changelog in the psd1 file refers to the master branch
- [x] Investigate whether the current release portion of the changelog could be transferred into the ReleaseNotes section of the psd1 (what is the maximum size for this field)?  This would be in addition to the current change log file.  If it is feasible, add tooling changes to push the latest changes to AzureRM.psd1 as aprt of creatign the final package.

**Comment by cormacpayne** [comment]
@markcowl email has been sent that includes gist with proposed changes to release process document
