### ISSUE TITLE
New-AzureResourceGroupDeployment casts string parameters in TemplateParameterObject incorrectly

### ISSUE THREAD

**Issue by clamanna** [Azure/azure-powershell#308]
When using the TemplateParameterObject param of New-AzureResourceGroupDeployment, rather than the dynamic cmdlet parameters, this issue appeared (module version 0.8.13). 

When the template parameter object looked like $tpo = @{ P = $v } where $v was a string ($v = 'value'), this would fail template validation on the server side, saying the value for parameter P was not valid. This was fixed by casting, but this seems weird: $tpo = @{ P = [string]$v } worked.

When capturing the request with Fiddler, and without the cast the JSON was strange, and included some <CliXml> wrapper around the actual string value.

**Comment by singhkay** [comment]
@clamanna This is assigned the label "IaaS" but I'm not sure what the compute team needs to look at here. Should this be assigned to your team instead? 

cc: @matt-gibbs

**Comment by clamanna** [comment]
Yes, this feels like a general template deployment cmdlet issue. 

cc: @vivsriaus

**Comment by ravbhatnagar** [comment]
Lets fix if this is still an issue.

**Comment by ravbhatnagar** [comment]
Works now.
