### ISSUE TITLE
Login-AzureRMAccount having issue following Enabling Enterprise State Roaming

### ISSUE THREAD

**Issue by montereyharris** [Azure/azure-powershell#3084]
### Cmdlet(s)
Get-AzureRmVm or any get that isn't related to Get-AzureRMSubscription
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1.14393.206
### Module Version
AzureRM.Profile 2.2 
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.14393.206
### Description
I can successfully use Login-AzureRMProfile and can do a Get-AzureRMSubscription
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
PS C:\Users\HarrisMonterey> get-azurermvm -Debug
DEBUG: 1:46:45 PM - GetAzureVMCommand begin processing with ParameterSet 'ListAllVirtualMachinesPara

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a
get-azurermvm : Run Login-AzureRmAccount to login.
At line:1 char:1
+ get-azurermvm -Debug
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-AzureRmVM], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Commands.Compute.GetAzureVMCommand
### Script/Steps for Reproduction
Login-AzureRMAccount
Then Attempt to Get-AzureRmVm

Recently enabled Enterprise State Roaming.

**Comment by markcowl** [comment]
@montereyharris This is most likely an issue with incompatible versions of the AzureRM.Compute and AzureRM.Profile modules, or an incompatible version of another module that is loaded (lie Azure).  Can you run

```
Get-Module -ListAvailable
```

And include the output?  Normally you can fix this problem by installing the latest msi, which would remove any incompatible versions of downloaded modules in the global scope.

**Comment by montereyharris** [comment]
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.2.0      AzureRM.profile                     {Enable-AzureRmDataCollection, Disable-AzureRmDataCollecti...
Binary     1.0.0.681  Microsoft.Azure.ActiveDirectory.... {Connect-PimService, Disable-PrivilegedRoleAssignment, Dis...
Script     1.0.1      Microsoft.PowerShell.Operation.V... {Get-OperationValidation, Invoke-OperationValidation}
Script     1.0        O365_Logon                          {Connect-EXO, Request-Credential, Connect-SfbO, Connect-SP...
Script     1.3        O365ServiceCommunications           {Get-SCEvent, Get-SCServiceInfo, Get-SCTenantEvent, Get-SC...
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...
Script     3.4.0      Pester                              {Describe, Context, It, Should...}
Script     3.3.5      Pester                              {Describe, Context, It, Should...}
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Set-PSReadlineKeyHandler, Remov...
Script     1.1        PSReadline                          {Get-PSReadlineKeyHandler, Set-PSReadlineKeyHandler, Remov...


    Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.1.2      AzureRM.ApiManagement               {Add-AzureRmApiManagementRegion, Get-AzureRmApiManagementS...
Manifest   1.0.10     AzureRM.Automation                  {Get-AzureRmAutomationJobOutputRecord, Import-AzureRmAutom...
Binary     0.9.7      AzureRM.AzureStackAdmin             {Get-AzureRMManagedLocation, New-AzureRMManagedLocation, R...
Manifest   0.9.8      AzureRM.AzureStackStorage           {Add-ACSFarm, Get-ACSEvent, Get-ACSEventQuery, Get-ACSFarm...
Manifest   1.0.10     AzureRM.Backup                      {Backup-AzureRmBackupItem, Enable-AzureRmBackupContainerRe...
Manifest   1.1.2      AzureRM.Batch                       {Remove-AzureRmBatchAccount, Get-AzureRmBatchAccount, Get-...
Manifest   1.0.4      AzureRM.Cdn                         {Get-AzureRmCdnCustomDomain, New-AzureRmCdnCustomDomain, R...
Manifest   1.3.2      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet...
Manifest   1.0.10     AzureRM.DataFactories               {Remove-AzureRmDataFactory, Get-AzureRmDataFactoryRun, Get...
Manifest   1.1.2      AzureRM.DataLakeAnalytics           {Get-AzureRmDataLakeAnalyticsDataSource, Remove-AzureRmDat...
Manifest   1.0.10     AzureRM.DataLakeStore               {Add-AzureRmDataLakeStoreItemContent, Export-AzureRmDataLa...
Manifest   1.0.1      AzureRM.DevTestLabs                 {Get-AzureRmDtlAllowedVMSizesPolicy, Get-AzureRmDtlAutoShu...
Manifest   1.0.10     AzureRM.Dns                         {Get-AzureRmDnsRecordSet, Remove-AzureRmDnsRecordSet, Set-...
Manifest   1.1.2      AzureRM.HDInsight                   {Get-AzureRmHDInsightJob, New-AzureRmHDInsightSqoopJobDefi...
Manifest   1.0.10     AzureRM.Insights                    {Add-AzureRmMetricAlertRule, Add-AzureRmLogAlertRule, Add-...
Manifest   1.1.9      AzureRM.KeyVault                    {Get-AzureRmKeyVault, New-AzureRmKeyVault, Remove-AzureRmK...
Manifest   1.0.6      AzureRM.LogicApp                    {Stop-AzureRmLogicAppRun, Get-AzureRmLogicApp, Get-AzureRm...
Manifest   0.9.1      AzureRM.MachineLearning             {Export-AzureRmMlWebService, Get-AzureRmMlWebServiceKeys, ...
Manifest   1.0.11     AzureRM.Network                     {Add-AzureRmApplicationGatewayBackendAddressPool, Get-Azur...
Manifest   1.0.10     AzureRM.NotificationHubs            {Get-AzureRmNotificationHubsNamespaceAuthorizationRules, G...
Manifest   1.0.10     AzureRM.OperationalInsights         {Get-AzureRmOperationalInsightsSavedSearch, Get-AzureRmOpe...
Manifest   1.0.10     AzureRM.Profile                     {Enable-AzureRmDataCollection, Disable-AzureRmDataCollecti...
Manifest   1.1.2      AzureRM.RecoveryServices            {Get-AzureRmRecoveryServicesBackupProperties, Get-AzureRmR...
Manifest   1.0.2      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRecoveryServicesBackupItem, Get-AzureRmReco...
Manifest   1.1.8      AzureRM.RedisCache                  {Remove-AzureRmRedisCacheDiagnostics, Set-AzureRmRedisCach...
Manifest   2.0.1      AzureRM.Resources                   {Get-AzureRmADApplication, Get-AzureRmADGroupMember, Get-A...
Manifest   1.0.1      AzureRM.ServerManagement            {Install-AzureRmServerManagementGatewayProfile, Reset-Azur...
Manifest   1.1.9      AzureRM.SiteRecovery                {Stop-AzureRmSiteRecoveryJob, Get-AzureRmSiteRecoveryNetwo...
Manifest   1.0.10     AzureRM.Sql                         {Get-AzureRmSqlDatabaseImportExportStatus, New-AzureRmSqlD...
Manifest   1.1.2      AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, ...
Manifest   1.0.10     AzureRM.StreamAnalytics             {Get-AzureRmStreamAnalyticsFunction, Get-AzureRmStreamAnal...
Manifest   1.0.10     AzureRM.Tags                        {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag}
Manifest   1.0.10     AzureRM.TrafficManager              {Disable-AzureRmTrafficManagerEndpoint, Enable-AzureRmTraf...
Manifest   1.0.10     AzureRM.UsageAggregates             Get-UsageAggregates
Manifest   1.1.2      AzureRM.Websites                    {Get-AzureRmAppServicePlanMetrics, New-AzureRmWebAppDataba...


    Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.5.1      Azure                               {Get-AzureAutomationCertificate, Get-AzureAutomationConnec...


    Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.1.4      Azure.Storage                       {Get-AzureStorageBlob, Get-AzureStorageBlobContent, Get-Az...


    Directory: C:\Program Files\Common Files\Skype for Business Server 2015\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   6.0.0.0    Lync
Manifest   6.0.0.0    SkypeForBusiness                    {Debug-CsInterPoolReplication, Invoke-CsBackupServiceSync,...

**Comment by montereyharris** [comment]
Installing new Modules via WebPI cleared the issue
