### ISSUE TITLE
Key Vault PowerShell Set-AzureRmKeyVaultAcessPolicy should not allow setting App object ID

### ISSUE THREAD

**Issue by pomortaz** [Azure/azure-powershell#3086]
Related to issue: https://github.com/Azure/azure-sdk-for-node/issues/1932
At [here](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/KeyVault/Commands.KeyVault/Models/KeyVaultManagementCmdletBase.cs#L213) it should be verified that the object ID only belongs to service principal, user or group and not application.

**Comment by amarzavery** [comment]
I skimmed through the code in xplat cli and feel that the same issue exists in `azure keyvault set-policy` command when the user provides --object-id. We do not check if the objectId belongs to an sp or an application. The help says that the objectId should belong to the principal but the code does not validate that.
https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/keyvault/keyvault._js#L614

**Comment by maddieclayton** [comment]
@dragav Do you guys still plan to fix this issue, or should I close?

**Comment by dragav** [comment]
I would prefer to leave this type of verification to the service. Please go ahead and close it. Thanks.
