### ISSUE TITLE
TemplateParameterObject makes cmdlet omit the error outputs for New-AzureResourceGroupDeployment

### ISSUE THREAD

**Issue by clamanna** [Azure/azure-powershell#309]
When using the TemplateParameterObject param of New-AzureResourceGroupDeployment, rather than the dynamic cmdlet parameters, this issue appeared (module version 0.8.13).

The cmdlet stopped seeing error messages emitted to the PS host.

For example, the message "New-AzureResourceGroupDeployment : 5:27:20 AM - Resource ... with message 'Operation results in exceeding quota
 limits of Core. Maximum allowed: 5, Current in use: 4, Additional requested: 2.'" for exceeding core quota was now missing consistently.

Switching back to dynamic cmdlet parameters and doing the same deployment caused the error message to reappear.

**Comment by singhkay** [comment]
@matt-gibbs Seems like this should be assigned to @chadiel's team instead

**Comment by ravbhatnagar** [comment]
Lets see if this issue still exists.

**Comment by ravbhatnagar** [comment]
See if this still repros

**Comment by ravbhatnagar** [comment]
@TianoMS - Can you please see if this still repros.

**Comment by TianoMS** [comment]
This issue no longer repros. I tried:

new-azurermresourcegroupdeployment -ResourceGroupName "tiano309" -TemplateFile "t1.json" -TemplateParameterObject @{storageAccountName="verylongname111111111111111111"}, 

and we could get the error message.

**Comment by ravbhatnagar** [comment]
Closing as this doesn't repro. Feel free to reach out or reopen if you feel otherwise.
