### ISSUE TITLE
Get-AzureRmWebAppSlotPublishingProfile has issue using login information

### ISSUE THREAD

**Issue by ipinak** [Azure/azure-powershell#3098]
### PowerShell Version

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
### OS Version

`BuildVersion                   10.0.14393.206`
### Description

When I try to execute `Get-AzureRmWebAppSlotPublishingProfile -Name ...` I get the following error: 

```
Get-AzureRmWebAppSlotPublishingProfile : Run Login-AzureRmAccount to login.
... Points to the executiong of my file ...
+ ... bProfiles = Get-AzureRmWebAppSlotPublishingProfile -Name $SiteName -R ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-AzureRmWebAppSlotPublishingProfile], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Commands.WebApps.Cmdlets.DeploymentSlots.GetAzureWebAppSlotPublishingProfileCmdlet
```
### Debug Output

Below you can find a part of my debug output, I don't want to post the full output, since it contains some sensitive info.

```
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 10/19/2016 21:08:00:  - TokenCache: Serializing token cache with 4 items.
DEBUG: 11:08:00 PM - AddAzureRMAccountCommand end processing.
DEBUG: 11:08:00 PM - AddAzureRMAccountCommand end processing.
DEBUG: 11:08:00 PM - GetAzureWebAppSlotPublishingProfileCmdlet begin processing with ParameterSet 'S1'.
```

`Get-AzureRmWebAppSlotPublishingProfile : Run Login-AzureRmAccount to login.`
### Script/Steps for Reproduction
1. Login successfully using `Login-AzureRmAccount` and receive the details for that account.
2. Execute `Get-AzureRmWebAppSlotPublishingProfile` (passing some parameters) which leads to the failure described.

**Comment by markcowl** [comment]
@akurmi can you take a look?

**Comment by panchagnula** [comment]
@ipinak i cannot repro this on the latest websites-preview module can you please re-try & re-activate if needed https://github.com/Azure/azure-powershell/releases/tag/v5.0.0-preview-AzureRM.Websites
