### ISSUE TITLE
Possible Management Certificates issue?

### ISSUE THREAD

**Issue by Morritt** [Azure/azure-powershell#311]
Not sure if this is how it's being used, or a genuine issue, but it only surfaced on installing the latest version of Azure PowerShell.  When using a management certificate without already connecting to Azure, the AzureProfile.json file is generated by devoid of any subscriptions or accounts: 

>{
>  "Environments": [],
>  "Subscriptions": [],
>  "Accounts": []
>}

When attempting to set or get a subscription, PowerShell responds with `Set-AzureSubscription : The subscription name <MySubscription> doesn't exist.`

To work around, if I authenticate with my Azure account, then the .json file is populated with a list of all my subscriptions, and "Accounts" with my account, everything seems to work fine, then running the same code using the management cert, it appends the management cert account below my account, and everything still works (even sets the default account for the subscription I am working with to the thumbprint of the management cert).

I can replicate this by deleting the `C:\Users\myaccount\AppData\Roaming\Windows Azure Powershell` folder, and rerunning the script that uses the management cert (or any Get/Set/Select-AzureSubscription).

**Comment by Morritt** [comment]
To replicate (after clearing out Windows Azure Powershell folder), simply running this results in an error (and the .json above):

>$managementCert = Get-Item cert:\CurrentUser\My\xxxcertthumbprintxxx
>$subscription = "MySubscription"
>Set-AzureSubscription -Certificate $managementCert -SubscriptionName $subscription
>Get-AzureSubscription -SubscriptionName $subscription

Running Add-AzureAccount (fine), I can get the subscription ok (DefaultAccount and Accounts show my Azure account).

Running the above script once more, also works, and the DefaultAccount is the cert thumbprint, and it lists both the thumbprint and my Azure account in Accounts).

**Comment by markcowl** [comment]
@Morritt Thanks for reporting, we'll take a look.  You can achieve this using the New-AzureProfile cmdlet as a workaround

**Comment by hovsepm** [comment]
Unable to repro on Azure Powershell 0.8.16. Here are the steps that we did:

$cert = Get-ChildItem -path cert:\LocalMachine\My | where {$_.Thumbprint -eq "xxxxx" }
Set-AzureSubscription -SubscriptionName "Azure SDK sandbox" -Certificate $cert -SubscriptionID xxxxxxxxx

This created the AzureProfile.json with valid Subscription and Accounts variables set. 
Please add exactly what steps are you following which fails on your side.

**Comment by Morritt** [comment]
It's even weirder than I thought.  Using the slightly simpler @hovsepm method, if I omit the SubscriptionID from here (according to docs it's not required):

> $cert = Get-ChildItem -path cert:\LocalMachine\My | where {$_.Thumbprint -eq "xxxxx" }
 > Set-AzureSubscription -SubscriptionName "subscription" -Certificate $cert -SubscriptionID xxxxxxxxx

I still get a blank AzureProfile.json created in the "Windows Azure Powershell" folder.  When I  put the SubscriptionID in it _does_ create me the correct json profile.

Calling `New-AzureProfile` it actually doesn't do anything (for me no profile json created at all, there's some output from the command, no errors, just lists my Accounts/Subscriptions, but the ProfilePath and ProfileLoadErrors are blank, I assume it should it display something here?).

> New-AzureProfile -Certificate $cert -SubscriptionId "my-sub-id" -StorageAccount "mystorageaccountname"

I'm only passing the Certificate, SubscriptionID and StorageAccount properties in, I'm deliberately not sending other credentials as the account I am using is for automation so doesn't have it's own login to Azure (hence the certificate).

Updated to 0.8.16 to test this, and running on Windows 2008 R2.

**Comment by markcowl** [comment]
@Morritt So, New-AzureProfile creates an in-memory profile, it is expected that it would not write the certificate to your user profile.

There was a bug in older versions of powershell that subscriptions could not be selected by name (this has been fixed in the latest versions).  Since you are able to create the subscription and select it by id, I am marking this as resolved.  Please re-open if I have missed somethign about the scenario.
