### ISSUE TITLE
Cant switch to ResourceManger 

### ISSUE THREAD

**Issue by AravindBABU95** [Azure/azure-powershell#3113]
### Cmdlet(s)
PS C:\Users\Aravind> Get-AzureSubscription

SubscriptionId            : *********************************
SubscriptionName          : ***************
Environment               : AzureCloud
DefaultAccount            : *******************
IsDefault                 : True
IsCurrent                 : True
TenantId                  : 0e4d8c11-122a-48bc-9775-78d28f5cc8c6
CurrentStorageAccountName :

### PowerShell Version
Version
-------
3.0.0
### OS Version

Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1### Description
Cant switch to resourcemanager
### Debug Output

PS C:\Users\Aravind> Switch-AzureMode  -name AzureResourceManager
Switch-AzureMode : The term 'Switch-AzureMode' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Switch-AzureMode  -name AzureResourceManager
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Switch-AzureMode:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by pcgeek86** [comment]
@AravindBABU95 This functionality changed a long time ago. There's no `Switch-AzureMode` command. 

Read here: https://github.com/Azure/azure-powershell/wiki/Deprecation-of-Switch-AzureMode-in-Azure-PowerShell

@markcowl Please close this issue.

**Comment by markcowl** [comment]
@AravindBABU95 Closing, as Trevor is correct, this was part of the update to PowerShell 1.0
