### ISSUE TITLE
Add CompatiblePSEditions to Azure PowerShell

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#3114]
Right now, it's possible to import the Azure PowerShell module, designed for PowerShell Desktop Edition, into PowerShell Core Edition. It shouldn't be possible to do this, since we now have support for `CompatiblePSEditions` in the module manifest.

https://msdn.microsoft.com/en-us/powershell/gallery/psget/module/modulewithpseditionsupport

The downside to doing this, is that PowerShell 5.1 is required, in order to support the new `CompatiblePSEditions` property in the module manifest. This would need to be properly communicated with users of the Azure PowerShell module.

Here is an example of where a user attempted to import a non-supported version of the Azure PowerShell module into PowerShell Core, and received an [expected] error.

https://github.com/PowerShell/PowerShell/issues/2526

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by kilasuit** [comment]
This isnt an issue in the Azure PowerShell Modules but an issue in the way PowerShellGet works on PSCore

I've got an idea on how this needs to be implemented but it's likely a significant change to PowerShellGet to get working without further hurdles going forward

**Comment by pcgeek86** [comment]
Someone could still download the Azure PowerShell Desktop Edition module, and attempt to import it into PowerShell Core. PowerShellGet is only one channel to install the module. Manual installation is another.

**Comment by markcowl** [comment]
@pcgeek86 @kilasuit It's unclear whether we will support both editions in the same module or separate modules per edition going forward.  It isn't a bad piece of documentation, at least, to have the additional metadata per module.

**Comment by markcowl** [comment]
@pcgeek86 @kilasuit The PowerShell team has moved to a new mechanism (a label) as the standard mechanism for designating NetCore modules.  We cannot add support for ComptiblePSEdition until we require PowerShell 5.1 as a minimum platform, which is not in the short term future.
