### ISSUE TITLE
Get-AzureStorageAccount : "GeoReplicationEnabled property will be deprecated in a future release of Azure PowerShell."

### ISSUE THREAD

**Issue by asranja** [Azure/azure-powershell#3116]
Hey, 

We are noticing this warning **"GeoReplicationEnabled property will be deprecated in a future release of Azure PowerShell"** and would like to know the possible impact of this. 

We could not find any official documentation online regarding the same. Please share some information with us as to when the property will be deprecated and what will be the resulting impact of the deprecation.

**Comment by markcowl** [comment]
@vinjiang @blueww Can you provde the customer with some details on deprecation of GeoReplicationEnabled property?

**Comment by blueww** [comment]
This warning is add by @ogai  in https://github.com/Azure/azure-powershell/commit/dcaac6a2b9882494379f54a830d8b48fac34f242. 

The warning is added since GeoReplicationEnabled setting is merged with account Type setting.
Now when GeoReplicationEnabled  is set, we will use StandardGRS Type. 
But you can also set it by Type parameter.
```
public static class StorageAccountTypes
    {
        public const string StandardGRS = "Standard_GRS";
        public const string StandardLRS = "Standard_LRS";
        public const string StandardRAGRS = "Standard_RAGRS";
        public const string StandardZRS = "Standard_ZRS";
    }
```
@markcowl, how do you think we should deal with it. We might can remove the parameter  GeoReplicationEnabled in some major release in the future.

**Comment by asranja** [comment]
Thanks for providing the info.

**Comment by mvvsubbu** [comment]
Hey we are not using GeoReplicationEnabled property in our invocation of the command let, still we are getting this warning. I am not sure as a developer what should I do to fix this warning? Should I stop using this command let, if yes what is the replacement you would recommend?

**Comment by mvvsubbu** [comment]
Adding Muthu @kmkumaran  who also wants to know how to handle this.

**Comment by mvvsubbu** [comment]
Ping

**Comment by blueww** [comment]
You can continue to use the cmdlet, as you don't use the GeoReplicationEnabled property, actually the change should have no impact to you.
As remove GeoReplicationEnabled property is a breaking change, we need to wait for a major release which allows breaking change to remove it.

**Comment by mvvsubbu** [comment]
Ideally this warning shouldn't be displaced to everyone. It should be displayed only if user's are using that property that way people like we will not get that messages. Can that be done? Otherwise once in every few days someone comes back saying please fix the task. which we can't do anything.

**Comment by blueww** [comment]
I agree it's a better benavior that only show the warning when use the GeoReplicationEnabled parameter.
Will open a task for it and work it based on our bandwidth and priority list.

**Comment by mvvsubbu** [comment]
Thanks. Please do update the thread here once you fix the issue, so that we can notify our customers

**Comment by blueww** [comment]
@mvvsubbu  In the latest PowerShell release 3.6.0, the warning only show when use GeoReplicationEnabled parameter in cmdlet  Set-AzureStorageAccount

**Comment by mvvsubbu** [comment]
Thanks it helps us.
