### ISSUE TITLE
Set-AzureRmLoadBalancer - Length cannot be less than zero.

### ISSUE THREAD

**Issue by ljt91** [Azure/azure-powershell#3118]
### Cmdlet(s)

Get-AzureRmLoadBalancer
Add-AzureRmLoadBalancerRuleConfig
Set-AzureRmLoadBalancer
### PowerShell Version

5.1.14393.206
### Module Version

AzureRM - 3.0.0
### OS Version

10.0.14393.206
### Description

Set-AzureRmLoadBalancer : Length cannot be less than zero.
Parameter name: length
At line:1 char:17
- $LoadBalancer | Set-AzureRmLoadBalancer
-                 ~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Set-AzureRmLoadBalancer], ArgumentOutOfRangeException
  - FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.SetAzureLoadBalancerCommand
### Script/Steps for Reproduction

$LoadBalancer = Get-AzureRmLoadBalancer -Name "ENG-LB-IIS-SCU" -ResourceGroupName "ENG-RSG-SCU" -Verbose

$LoadBalancer | Add-AzureRmLoadBalancerRuleConfig -Name "ENG-LB-RLS-IIS-SCU-TST" -FrontendIpConfigurationId $LoadBalancer.FrontendIpConfigurations[0] -BackendAddressPoolId $LoadBalancer.BackendAddressPools[0] -ProbeId $LoadBalancer.Probes[0] -Protocol Tcp -FrontendPort 443 -BackendPort 443

$LoadBalancer | Set-AzureRmLoadBalancer

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft Hey Deepak, would you mind taking a look at this issue?

**Comment by inverted360** [comment]
I can repro this as well:

New-AzureRmLoadBalancer -Name $lbname `
            -ResourceGroupName $ResourceGroupName `
            -Location $Location `
            -FrontendIpConfiguration $frontendIP `
            -InboundNatRule $inboundnatrule1,$inboundnatrule2 `
            -LoadBalancingRule $lbrule `
            -BackendAddressPool $beaddresspool `
            -Probe $healthProbe

WARNING: The output object type of this cmdlet will be modified in a future release.

New-AzureRmLoadBalancer : Length cannot be less than zero.
Parameter name: length
At line:1 char:1
+ New-AzureRmLoadBalancer -Name $lbname `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmLoadBalancer], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureLoadBalancerCommand

**Any progress on debugging this?** I'm running 
Name                           Value                                                                                                                                   
----                           -----                                                                                                                                   
PSVersion                      5.1.14393.693                                                                                                                           
PSEdition                      Desktop                                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                 
BuildVersion                   10.0.14393.693                                                                                                                          
CLRVersion                     4.0.30319.42000                                                                                                                         
WSManStackVersion              3.0                                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                                     
SerializationVersion           1.1.0.1                                                                                                                                 

Version    Name                                Repository           Description                                           
-------    ----                                ----------           -----------                                           
3.7.0      AzureRM                             PSGallery            Azure Resource Manager Module

**Comment by inverted360** [comment]
Hi Deepak,

I upgraded to AzureRM 3.8 today and still receiving error:

$lb = AzureRM.Network\New-AzureRmLoadBalancer `
                    -Name $lbname1 `
                    -ResourceGroupName $ResourceGroupName `
                    -Location $Location `
                    -FrontendIpConfiguration $frontendIP `
                    -BackendAddressPool $beaddresspool `
                    -Probe $healthProbe `
                    -InboundNatRule $inboundnatrule1,$inboundnatrule2 `
                    -LoadBalancingRule $lbrule `
                    -InboundNatPool $inboundnatpool
WARNING: The output object type of this cmdlet will be modified in a future release.
AzureRM.Network\New-AzureRmLoadBalancer : Length cannot be less than zero.
Parameter name: length
At line:1 char:7
+ $lb = AzureRM.Network\New-AzureRmLoadBalancer `
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmLoadBalancer], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureLoadBalancerCommand

**Comment by DeepakRajendranMsft** [comment]
Spoke to @ljt91 offline and is resolved. @inverted360, i believe yours is a different issue. Could you please open a new ticket. Also, can you tell how how you are creating the $frontendip, beaddrespool. inboundnatrule etc. 

We should do a better job at error message here. but as a self help, can you reduce the number of parameters and try. it will easier to figure out what is causing the error.

**Comment by masnider** [comment]
Was there some solution to this that can be shared? I am also getting this with both possible syntaxes (piping in lb vs using the named parameter). I have verified that there is data in $lb and that it is usable in other commands 

`Set-AzureRmLoadBalancer -LoadBalancer $lb  `

**Comment by dulfer** [comment]
There is an error in the ProbeID parameter of Add-AzureRmLoadBalancerRuleConfig.
The parameter accepts an ID, you now pass the full object.

I highlighted the fix below.

$LoadBalancer | Add-AzureRmLoadBalancerRuleConfig ... -ProbeId $LoadBalancer.Probes[0]**.Id** -Protocol Tcp -FrontendPort 443 -BackendPort 443

**Comment by inverted360** [comment]
Thank you @dulfer
