### ISSUE TITLE
Remove Sql MSTest tests 

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3125]
Branching from issue https://github.com/Azure/azure-powershell/issues/3029

Remove or convert MSTest tests to xunit

Target for the test can be found [here](https://github.com/Azure/azure-powershell/blob/dev/AzurePowershell.Test.targets#L241)

**Comment by cormacpayne** [comment]
@jamestao Hey James, we're looking to remove these tests by the end of the year. Would you mind taking a look and assigning it to the proper milestone? Thanks

**Comment by cormacpayne** [comment]
@akromm @jamestao ping

**Comment by akromm** [comment]
@cormacpayne do you have an example of how to do the conversion?

**Comment by jaredmoo** [comment]
I don't see any MSTests any more. Can this be closed?

**Comment by akromm** [comment]
@cormacpayne  I also did a quick scan and did not find any MSTest tests. Closing issue.
