### ISSUE TITLE
Remove HDInsight MSTest tests

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3126]
Branching from issue https://github.com/Azure/azure-powershell/issues/3029

Remove or convert MSTest tests to xunit

Target for the test can be found [here](https://github.com/Azure/azure-powershell/blob/dev/AzurePowershell.Test.targets#L244)

**Comment by cormacpayne** [comment]
@shefaliv Hey Shefali, we're looking to remove these tests by the end of the year. Would you mind taking a look and assigning it to the proper milestone? Thanks

**Comment by cormacpayne** [comment]
@shefaliv ping

**Comment by maddieclayton** [comment]
Will not remove test, but rather will move it to ServiceManagement checkin CI once the repo has been separated: https://github.com/Azure/azure-powershell/issues/6379
