### ISSUE TITLE
Remove Insights MSTest tests

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3127]
Branching from issue https://github.com/Azure/azure-powershell/issues/3029

Remove or convert MSTest tests to xunit

Target for the test can be found [here](https://github.com/Azure/azure-powershell/blob/dev/AzurePowershell.Test.targets#L250)

**Comment by cormacpayne** [comment]
@asheniam Hey Andy, we're looking to remove these tests by the end of the year. Would you mind taking a look and assigning it to the proper milestone? Thanks

**Comment by cormacpayne** [comment]
@asheniam ping

**Comment by gucalder** [comment]
I think we do not have MSTests in this project.
