### ISSUE TITLE
commented disk encryption example is missing VolumeType parameter 

### ISSUE THREAD

**Issue by ejarvi** [Azure/azure-powershell#3128]
### Script

[AzureDiskEncryptionPreRequisiteSetup.ps1](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Compute/Commands.Compute/Extension/AzureDiskEncryption/Scripts/AzureDiskEncryptionPreRequisiteSetup.ps1#L185)
### PowerShell Version

5.0.10586.494
### Actual

Script instructs users to call the cmdlet as follows, but is missing the VolumeType parameter that is required for Linux VM's: 
`Set-AzureRmVMDiskEncryptionExtension -ResourceGroupName $resourceGroupName -VMName $vmName -AadClientID $aadClientID -AadClientSecret $aadClientSecret -DiskEncryptionKeyVaultUrl $diskEncryptionKeyVaultUrl -DiskEncryptionKeyVaultId $keyVaultResourceId
`
### Expected

`Set-AzureRmVMDiskEncryptionExtension -ResourceGroupName $resourceGroupName -VMName $vmName -AadClientID $aadClientID -AadClientSecret $aadClientSecret -DiskEncryptionKeyVaultUrl $diskEncryptionKeyVaultUrl -DiskEncryptionKeyVaultId $keyVaultResourceId -VolumeType $volumeType
`

**Comment by markcowl** [comment]
@singhkays Please take a look and assign to a milestone as appropriate

**Comment by ejarvi** [comment]
Submitted a PR for this:  https://github.com/Azure/azure-powershell/pull/4079/files

**Comment by cormacpayne** [comment]
This fix is available in Azure PowerShell 4.2.0.
