### ISSUE TITLE
Move Batch tests from on-demand build to check-in

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3131]
Branching from issue https://github.com/Azure/azure-powershell/issues/3029

Below is a list of tests that currently run in the on-demand build but not during check-in. Need to add the `Category.CheckIn` trait to these tests.

BatchAccountTests.TestBatchAccountKeys
BatchAccountTests.TestCreateAndRemoveBatchAccountViaPiping
BatchAccountTests.TestCreatesNewBatchAccount
BatchAccountTests.TestGetBatchAccountsUnderResourceGroups
BatchAccountTests.TestGetNonExistingBatchAccount
BatchAccountTests.TestListNodeAgentSkus
BatchAccountTests.TestUpdatesExistingBatchAccount
BatchApplicationPackageTests.TestCreatePoolWithApplicationPackage
BatchApplicationPackageTests.TestUpdateApplicationPackage
BatchApplicationPackageTests.TestUpdatePoolWithApplicationPackage
BatchApplicationPackageTests.TestUploadApplicationPackage
CertificateTests.TestCancelCertificateDelete
ComputeNodeTests.TestDisableAndEnableComputeNodeSchedulingById
ComputeNodeTests.TestDisableAndEnableComputeNodeSchedulingPipeline
ComputeNodeTests.TestGetComputeNodeById
ComputeNodeTests.TestGetComputeNodeRemoteLoginSettingsById
ComputeNodeTests.TestGetComputeNodeRemoteLoginSettingsPipeline
ComputeNodeTests.TestListAllComputeNodes
ComputeNodeTests.TestListComputeNodePipeline
ComputeNodeTests.TestListComputeNodesByFilter
ComputeNodeTests.TestListComputeNodesWithMaxCount
ComputeNodeTests.TestRebootComputeNodeById
ComputeNodeTests.TestRebootComputeNodePipeline
ComputeNodeTests.TestReimageComputeNodeById
ComputeNodeTests.TestReimageComputeNodePipeline
ComputeNodeTests.TestRemoveComputeNodeById
ComputeNodeTests.TestRemoveMultipleComputeNodes
ComputeNodeUserTests.TestCreateComputeNodeUser
ComputeNodeUserTests.TestUpdateComputeNodeUser
FileTests.TestDeleteNodeFileByComputeNodeByName
FileTests.TestDeleteNodeFileByComputeNodeByPipeline
FileTests.TestDeleteNodeFileByTaskByPipeline
FileTests.TestGetNodeFileByComputeNodeByName
FileTests.TestGetNodeFileByTaskByName
FileTests.TestGetNodeFileContentByComputeNodeByName
FileTests.TestGetNodeFileContentByComputeNodeByPipeline
FileTests.TestGetNodeFileContentByTaskByName
FileTests.TestGetNodeFileContentByTaskPipeline
FileTests.TestGetRemoteDesktopProtocolFileById
FileTests.TestGetRemoteDesktopProtocolFilePipeline
FileTests.TestListAllNodeFilesByComputeNode
FileTests.TestListAllNodeFilesByTask
FileTests.TestListNodeFileByTaskPipeline
FileTests.TestListNodeFilesByComputeNodeByFilter
FileTests.TestListNodeFilesByComputeNodeRecursive
FileTests.TestListNodeFilesByComputeNodeWithMaxCount
FileTests.TestListNodeFilesByTaskByFilter
FileTests.TestListNodeFilesByTaskRecursive
FileTests.TestListNodeFilesByTaskWithMaxCount
JobScheduleTests.TestDeleteJobSchedule
JobScheduleTests.TestDisableAndEnableJobSchedule
JobScheduleTests.TestGetJobScheduleById
JobScheduleTests.TestListAllJobSchedules
JobScheduleTests.TestListJobSchedulesByFilter
JobScheduleTests.TestListJobSchedulesWithMaxCount
JobScheduleTests.TestTerminateJobScheduleById
JobScheduleTests.TestTerminateJobSchedulePipeline
JobScheduleTests.TestUpdateJobSchedule
JobTests.TestDeleteJobPipeline
JobTests.TestDisableAndEnableJob
JobTests.TestGetJobById
JobTests.TestJobWithTaskDependencies
JobTests.TestListAllJobs
JobTests.TestListJobsByFilter
JobTests.TestListJobsUnderSchedule
JobTests.TestListJobsWithMaxCount
JobTests.TestTerminateJobById
JobTests.TestTerminateJobPipeline
JobTests.TestUpdateJob
PoolTests.TestChangeOSVersionById
PoolTests.TestChangeOSVersionPipeline
PoolTests.TestDeletePool
PoolTests.TestDisableAutoScaleById
PoolTests.TestDisableAutoScaleByPipeline
PoolTests.TestEnableAutoScaleById
PoolTests.TestEnableAutoScaleByPipeline
PoolTests.TestEvaluateAutoScaleById
PoolTests.TestEvaluateAutoScaleByPipeline
PoolTests.TestGetPoolById
PoolTests.TestListAllPools
PoolTests.TestListPoolsByFilter
PoolTests.TestListPoolsWithMaxCount
PoolTests.TestResizePoolById
PoolTests.TestResizePoolByPipeline
PoolTests.TestStopResizePoolById
PoolTests.TestStopResizePoolByPipeline
PoolTests.TestUpdatePool
TaskTests.TestDeleteTaskPipeline
TaskTests.TestGetTaskById
TaskTests.TestListAllSubtasks
TaskTests.TestListAllTasks
TaskTests.TestListTaskPipeline
TaskTests.TestListTasksByFilter
TaskTests.TestListTasksWithMaxCount
TaskTests.TestTerminateTask
TaskTests.TestUpdateTask

**Comment by cormacpayne** [comment]
@jasper-schneider Hey Jasper, would you (or someone on the Batch team) take a look at this issue and assign it to the proper milestone? We are looking to move these tests out of the on-demand run by the end of the year.

**Comment by jasper-schneider** [comment]
Hi @cormacpayne,
We originally removed the Checkin attribute from these tests because we were requested to shorten our checkin test duration to < 5 minutes.  I have an action item to reorganize the scenario tests to be more like end to end scenarios, and then move the more specific details to unit tests.  Some of that work has happened, but it's not yet complete.  
So my question for you is: do you still want me to add the Checkin attribute now to all these, or are you ok with waiting for the test reorganization to complete?  If you want them now, is there still the 5 minute time limit?
FYI - I'm taking off for 2 weeks starting tomorrow.  IF your deadline is end of year, I think we're in ok shape, but if this is urgent, then you can talk to my lead Daryl (he should be your primary contact for the Batch SDK right now).

**Comment by markcowl** [comment]
@jasper-schneider @cormacpayne Now that the check-in tests run in parallel, the overal suite performance needs to be < 10 minutes or so.

Making this switch is a prerequisite to a module being able to release independently, som this year is ok as a deadline.

**Comment by jasper-schneider** [comment]
@markcowl, @cormacpayne,

I've created the following PR to add the attributes: https://github.com/Azure/azure-powershell/pull/3140
Hopefully this meets your needs for this particular issue.  If there are any problems with the PR though, I'll address them in ~2 weeks when I return.

Tests will then be iteratively refactored afterwards..

**Comment by jasper-schneider** [comment]
@cormacpayne 
Since my PR was merged, I'm closing this.  Feel free to reopen if you feel like there's still a problem.
