### ISSUE TITLE
Move Compute tests from on-demand build to check-in

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3132]
Branching from issue https://github.com/Azure/azure-powershell/issues/3029

Below is a list of tests that currently run in the on-demand build but not during check-in. Need to add the `Category.CheckIn` trait to these tests.

AEMExtensionTests.TestAEMExtensionAdvancedLinux
AEMExtensionTests.TestAEMExtensionAdvancedWindows
AEMExtensionTests.TestAEMExtensionBasicLinux
AEMExtensionTests.TestAEMExtensionBasicWindows
RunnerTests.ExecuteRunnerTests

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue and assigning it to the proper milestone? We are looking to move these tests out of the on-demand build by the end of the year.

**Comment by singhkays** [comment]
@hyonholee Can you take a look at this?

**Comment by cormacpayne** [comment]
@singhkays @hyonholee ping

**Comment by maddieclayton** [comment]
Closing - will open a new issue for remaining flaky tests.
