### ISSUE TITLE
Move DataFactories tests from on-demand build to check-in

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3133]
Branching from issue https://github.com/Azure/azure-powershell/issues/3029

Below is a list of tests that currently run in the on-demand build but not during check-in. Need to add the `Category.CheckIn` trait to these tests.

DataFactoryGatewayTests.TestCreateDataFactoryGateway
DataFactoryTests.TestCreateDataFactory
DataFactoryTests.TestDataFactoryPiping
DataFactoryTests.TestDeleteDataFactoryWithDataFactoryParameter
HubTests.TestHub
HubTests.TestHubPiping
HubTests.TestHubWithDataFactoryParameter
LinkedServiceTests.TestLinkedService
LinkedServiceTests.TestLinkedServicePiping
LinkedServiceTests.TestLinkedServiceWithDataFactoryParameter
TableTests.TestTable
TableTests.TestTablePiping
TableTests.TestTableWithDataFactoryParameter

**Comment by markcowl** [comment]
@jackmagic313 Please take a look and assign to a milestone as appropriate

**Comment by cormacpayne** [comment]
@jackmagic313 ping

**Comment by maddieclayton** [comment]
Done: https://github.com/Azure/azure-powershell/pull/6377
