### ISSUE TITLE
Move Network tests from on-demand build to check-in

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3134]
Branching from issue https://github.com/Azure/azure-powershell/issues/3029

Below is a list of tests that currently run in the on-demand build but not during check-in. Need to add the `Category.CheckIn` trait to these tests.

VirtualNetworkGatewayTests.TestSetVirtualNetworkGatewayCRUD
VirtualNetworkGatewayTests.VirtualNetworkGatewayActiveActiveFeatureTest

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft Hey Deepak, would you mind taking a look at this issue and assigning it to the appropriate milestone? We are looking to move these tests out of the on-demand build by the end of the year.

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft ping

**Comment by maddieclayton** [comment]
Update:

73.4602866s ✔  Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests.TestSetVirtualNetworkGatewayCRUD
Skipped ❢  Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests.TestVirtualNetworkGatewayP2SVpnProfile
10.4379191s ✔  Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests.VirtualNetworkGatewayActiveActiveFeatureTest
13.152872s ✔  Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests.VirtualNetworkGatewayRouteApiTest

**Comment by maddieclayton** [comment]
Done: https://github.com/Azure/azure-powershell/pull/6377
