### ISSUE TITLE
Move Resources tests from on-demand build to check-in

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3137]
Branching from issue https://github.com/Azure/azure-powershell/issues/3029

Below is a list of tests that currently run in the on-demand build but not during check-in. Need to add the `Category.CheckIn` trait to these tests.

ResourceClientTests.NewResourceGroupDeploymentWithDelay
DeploymentTests.TestNestedDeploymentFromTemplateFile
DeploymentTests.TestNestedErrorsDisplayed
DeploymentTests.TestNewDeploymentFromTemplateFile
DeploymentTests.TestNewDeploymentWithComplexPramaters
DeploymentTests.TestNewDeploymentWithDynamicParameters
DeploymentTests.TestNewDeploymentWithInvalidParameters
DeploymentTests.TestNewDeploymentWithParameterObject
DeploymentTests.TestSaveDeploymentTemplateFile
ResourceGroupTests.TestRemoveDeployment
ResourceLockTests.TestResourceLockCRUDTest
ResourceClientTests.NewResourceGroupUsesDeploymentNameForDeploymentName
RemoveAzureResourceGroupDeploymentCommandTests.RemoveDeployment
StopAzureResourceGroupDeploymentCommandTests.StopsActiveDeployment
TestAzureResourceGroupDeploymentCommandTests.ValidatesPSResourceGroupDeploymentWithUserTemplate

**Comment by cormacpayne** [comment]
@ravbhatnagar Hey Gaurav, would you mind taking a look at this issue and assigning it to the appropriate milestone? We are looking to move these tests out of the on-demand build by the end of the year.

**Comment by ravbhatnagar** [comment]
@vivsriaus - Lets take a look at this sometime in November.

**Comment by cormacpayne** [comment]
@ravbhatnagar @vivsriaus ping

**Comment by maddieclayton** [comment]
Done - will open a new issue for the flaky test.
