### ISSUE TITLE
Move Sql tests from on-demand build to check-in

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3138]
Branching from issue https://github.com/Azure/azure-powershell/issues/3029

Below is a list of tests that currently run in the on-demand build but not during check-in. Need to add the `Category.CheckIn` trait to these tests.

DataMaskingTests.TestDatabaseDataMaskingBasicRuleLifecycle
DataMaskingTests.TestDatabaseDataMaskingNumberRuleLifecycle
DataMaskingTests.TestDatabaseDataMaskingPrivilegedUsersChanges
DataMaskingTests.TestDatabaseDataMaskingRuleCreationWithoutPolicy
DataMaskingTests.TestDatabaseDataMaskingTextRuleLifecycle
ImportExportTests.TestExportDatabase
ImportExportTests.TestImportDatabase
ThreatDetectionTests.DisablingThreatDetection
ThreatDetectionTests.InvalidArgumentsThreatDetection
ThreatDetectionTests.ThreatDetectionDatabaseUpdatePolicy
ThreatDetectionTests.ThreatDetectionGetDefualtPolicy
ThreatDetectionTests.ThreatDetectionOnV2Server
ThreatDetectionTests.ThreatDetectionServerUpdatePolicy
ElasticPoolCrudTests.TestElasticPoolCreate
AzureSqlCmdletBaseAttributeTests.TestAzureSqlCmdletBaseAttributes
AzureSqlCmdletBaseAttributeTests.TestAzureSqlDatabaseCmdletBaseAttributes

**Comment by cormacpayne** [comment]
@jamestao Hey James, would you mind taking a look at this issue and assigning it to the appropriate milestone? We are looking to move these tests out of the on-demand build by the end of the year.

**Comment by cormacpayne** [comment]
@akromm @jamestao ping

**Comment by akromm** [comment]
@cormacpayne Are there execution time restrictions/requirements? Some of the tests (DataMaskingTests) can take 30 seconds to run.

**Comment by akromm** [comment]
@cormacpayne what are the requirements/restrictions for making a test a CheckIn test?

**Comment by maddieclayton** [comment]
Done. Will be doing an investigation into the test times on our side.
