### ISSUE TITLE
Update references to old scripts in developer documentation

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3139]
### Description

Update references to old scripts in the PowerShell documentation
- [ ] Go through the [developer wiki](https://github.com/Azure/azure-powershell/wiki/Microsoft-Azure-PowerShell-Developer-Guide) and change references to legacy scripts.  Where possible, update to include the new scripts that perform this functionality.  Otherwise, update the path to include the LegacyScripts directory.
- [ ] Go through the powershell documentation in the [documentation repo](https://github.com/azure/adx-documentation-pr]  and clean up any PowerShell documentation similarly.

**Comment by shahabhijeet** [comment]
Update the main developer wiki with the latest links to our new tools/module.
Removed any traces of old scripts.
Next will be updating documentation on the adx-documenation-pr
