### ISSUE TITLE
[AzureChinaCloud] New-AzureRmApiManagement fails with error "NoRegisteredProviderFound" in AzureChinaCloud

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#3143]
### PowerShell Version

PSVersion                      4.0
### Module Version

BuildVersion                   6.3.9600.17400
### Description

Following is the error i get when trying to provision a new API Management Instance.

New-AzureRmApiManagement -ResourceGroupName Pradebban -Name pradebban -Location "China East" -Organization "Own" -
AdminEmail "pradebban@hotmail.com" -Sku Standard -Capacity 2

New-AzureRmApiManagement : **NoRegisteredProviderFound**: No registered resource provider found for location 'China East' and API version
'2016-07-07' for type 'service'. The supported api-versions are '2014-02-14, 2015-09-15'. The supported locations are 'chinaeast,
chinanorth'.
At line:1 char:1
- New-AzureRmApiManagement -ResourceGroupName pradebban -Name pradebban -Location  ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [New-AzureRmApiManagement], CloudException
  - FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.Commands.NewAzureApiManagement
### Debug Output

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.chinacloudapi.cn/subscriptions/xxxxxxx-49a6-42bf-9300-xxxxxxx/resourceGroups/pradebban/providers/Microsoft.ApiMana
gement/service/pradebban?api-version=2016-07-07

Headers:

Body:
{
  "location": "ChinaEast",
  "properties": {
    "publisherEmail": "PRADEBBAN@HOTMAIL.COM",
    "publisherName": "own",
    "createdAtUtc": "0001-01-01T00:00:00",
    "hostnameConfigurations": [],
    "vpnType": "None"
  },
  "sku": {
    "name": "Standard",
    "capacity": 2
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 1d08fe3b-db97-46e3-bc9e-xxxxxxxxx
x-ms-correlation-request-id   : 1d08fe3b-db97-46e3-bc9e-xxxxxxxxx
x-ms-routing-request-id       : CHINAEAST:20161026T234611Z:xxxxxx-db97-46e3-bc9e-0bde05919f09
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Wed, 26 Oct 2016 23:46:10 GMT

Body:
{
  "error": {
    "code": "NoRegisteredProviderFound",
    "message": "No registered resource provider found for location 'ChinaEast' and API version '2016-07-07' for type 'service'. The
supported api-versions are '2014-02-14, 2015-09-15'. The supported locations are 'chinaeast, chinanorth'."
  }
}

New-AzureRmApiManagement : NoRegisteredProviderFound: No registered resource provider found for location 'ChinaEast' and API version
'2016-07-07' for type 'service'. The supported api-versions are '2014-02-14, 2015-09-15'. The supported locations are 'chinaeast,
chinanorth'.
At line:1 char:1
- New-AzureRmApiManagement -ResourceGroupName pradebban -Name pradebban -Location  ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [New-AzureRmApiManagement], CloudException
  - FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.Commands.NewAzureApiManagement

DEBUG: 11:46:10 PM - NewAzureApiManagement end processing.
DEBUG: 11:46:10 PM - NewAzureApiManagement end processing.
### Script/Steps for Reproduction
1. Login-AzureRmAccount -EnvironmentName "AzureChinaCloud"
2. Select-AzurermSubscription
3. New-AzureRmApiManagement -ResourceGroupName Pradebban -Name pradebban -Location "China East" -Organization "Own" -
   AdminEmail "pradebban@hotmail.com" -Sku Standard -Capacity 2

Thanks,
Pradebban Raja

**Comment by markcowl** [comment]
This is, unfortunately,  expected.  AzureChinaCliud is at least one version behind for every service

**Comment by Pradebban** [comment]
@markcowl, this has been working in the past, with the latest powershell release it has stopped working.

**Working Module**: Manifest   **2.0.1**      AzureRM.ApiManagement
**Not Working Module**: Manifest   **3.0.0**      AzureRM.ApiManagement

**Comment by markcowl** [comment]
@Pradebban Correct, this is because there was an API version change in the new version.  AzureChinaCloud users will need to use the older version until this service is deployed there.

**Comment by markcowl** [comment]
@ailn Can you advise on when the new api-version is planned for deployment to Mooncake?

**Comment by Pradebban** [comment]
@markcowl , thanks for the update. If we have timelines that would be more than helpful.

**Comment by solankisamir** [comment]
@Pradebban we are updating the manifest for Azure China Cloud. @markcowl please include me for future API Management issues, @ailn moved to another team.

**Comment by cormacpayne** [comment]
Closing this issue.
