### ISSUE TITLE
Get-AzureRmMetricDefinition not providing Metric Definitions of an Azure VM

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#3153]
### PowerShell Version

4.0
### Module Version

2.2.0      AzureRM.Insights
### OS Version

6.3.9600.17400
### Description

Am trying to get the Metric definition of a AzureVM, but there is nothing returned/ no error message/ no verbose message.
### Debug Output

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.chinacloudapi.cn/subscriptions/hidden/resourceGroups/hidden/providers/Micr
osoft.Compute/virtualMachines/mcneclsrmvmRDP/providers/microsoft.insights/metricDefinitions?api-version=2015-07-01&$filter=

Headers:
Accept                        : application/json
x-ms-version                  : 2014-04-01

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : d54e54ec-b574-xxxxxcba2e
x-ms-ratelimit-remaining-subscription-reads: 14642
x-ms-correlation-request-id   : 7453sxxxxx6217fbd1d600
x-ms-routing-request-id       : CHINAEAST:20161028T025742Z:74533b27-133f-4135-a44c-6217fbd1d600
Cache-Control                 : no-cache
Date                          : Fri, 28 Oct 2016 02:57:42 GMT
Server                        : Microsoft-IIS/8.5

Body:
{
  "id":
"/subscriptions/hidden/resourceGroups/hidden/providers/Microsoft.Compute/virtualMachines/hidden/providers/microsoft.insights/metricdefinitions",
  **"value": []**
}

DEBUG: 2:57:42 AM - GetAzureRmMetricDefinitionCommand end processing.
DEBUG: 2:57:42 AM - GetAzureRmMetricDefinitionCommand end processing.
### Script/Steps for Reproduction

Login-AzureRmAccount -EnvironmentName "AzureChinaCloud"
Select-AzureRmSubscription "YourSubscription"
Get-AzureRmMetricDefinition -ResourceId "/subscriptions/hidden/resourceGr
oups/hidden/providers/Microsoft.Compute/virtualMachines/hidden" -DetailedOutput -Debug

Thanks,
Pradebban Raja

**Comment by markcowl** [comment]
@asheniam Please take a look and assign to a milestone as appropriate

**Comment by anblanco** [comment]
Note: I'm not one of the dev team - just another powershell user.

Have you enabled diagnostics on the VM? I've noticed that by default Insights will show an empty list if diagnostics has never been enabled or was disabled in the portal. Insights does not show the Host level metrics you see by default on the portal.

**Comment by gucalder** [comment]
The metrics API has changed since this issue was filed.
The comment from anblanco is reasonable.
I am closing this issue.
