### ISSUE TITLE
Get-AzureRMLog does not respect nextLink - truncates results

### ISSUE THREAD

**Issue by anblanco** [Azure/azure-powershell#3169]
### Cmdlet(s)
Get-AzureRMLog
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1.14393.206
### Module Version
2.2.0
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.14393.206
### Description
When using Get-AzureRMLog against a subscription with many activity logs, the cmdlet silently truncates the result output. The issue appears to be that the autogenerated cmdlet does not follow the nextLink semantics.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

Relevant Debug using Get-AzureRMLog -StartTime (Get-Date).AddDays(-7) -DetailedOutput -Debug
Body:
{
  "nextLink": "https://management.azure.com/subscriptions/e086e328-75fd-4486-b609-c9d0e0e4deff/providers/microsoft.insights/eventtypes/management/values?api-version=2015-04-01
&$filter=eventTimestamp%20ge%20%272016-11-02T06%3A11%3A39.9518500Z%27%20and%20eventTimestamp%20le%20%272016-11-03T06%3A11%3A40.7418103Z%27&$skipToken=US1:0636137219227993351:5
11266ee;US0:-1:FFFFFFFF;EU1:-1:FFFFFFFF;AS1:-1:FFFFFFFF",
  "value": [
    {
      "authorization": {
### Script/Steps for Reproduction
Noted above - Using Get-AzureRMLog on a subscription with many activity log events will cause the REST API to present a nextLink value. PowerShell never follows this link.

**Comment by markcowl** [comment]
@asheniam please take a look

**Comment by gucalder** [comment]
This should be resolved by now. I am adding this issue to my next commit (and PR) to close this issue.
