### ISSUE TITLE
Cannot find 'configure site diagnostics'

### ISSUE THREAD

**Issue by mattcanty** [Azure/azure-powershell#317]
- Website
  - ...
  - Diagnostics
    - Configure **site** and application diagnostics
    - ...

I'm looking for the cmdlets for the feature listed above. I have been able to set up application logs successfully. However I am hitting a roadblock in find the corresponding cmdlet for 'site diagnostics'.

Expected parameters include:
- Web server logging: Off/Storage/File System
- Detailed error messages: On/Off
- Failed request tracing: On/Off

**Comment by mcrsw** [comment]
Hi @matthewcanty

I recently faced a similar problem, so I decided to figure out what the OLD and NEW
portals were changing (in terms of the output generated by the Get-AzureWebsite powershell
cmdlet).
The tables below summarise my findings - and hopefully, might be useful to others trying to figure
this out. 

In essence, I think the answer to your question is: 

* _Web server logging: Off/Storage/File System_
    * **Storage**: There isn't a property per-se, you need to set 
    HttpLoggingEnabled = True, **and** add an AppSetting value for 
    WEBSITE_HTTPLOGGING_CONTAINER_URL. e.g. 
    e.g. https://your-storage-account-name.blob.core.windows.net/your-container-name?sv=2012-02-12&sr=c&si=portalsaspolicy&sig=blah-blah-blah
    * **File system**: Set AzureDriveTraceEnabled = True, and ensure
    AppSetting does **not** contain a WEBSITE_HTTPLOGGING_CONTAINER_URL.
* _Detailed error messages: On/Off_
    * Set DetailedErrorLoggingEnabled = True
* _Failed request tracing: On/Off_ 
    * Set RequestTracingEnabled = True

Roughly speaking, the following properties (as returned by Get-AzureWebsite) correspond
to the OLD and NEW portal UI settings as follows:

Get-AzureWebsite|OLD Portal|NEW Portal
----------------|----------|----------
RequestTracingEnabled|Configuration > Site Diagnostics > Failed Request Tracing|Settings > Diagnostics logs > Failed request tracing
HttpLoggingEnabled|Configuration > Site Diagnostics > Web Server Logging|Settings > Diagnostics logs > Web server logging
DetailedErrorLoggingEnabled|Configuration > Site Diagnostics > Detailed Error Messages|Settings > Diagnostics logs > Detailed error messages

My experiments yielded the following results (i.e. property value and the corresponding settings 
in both the OLD and NEW portal):

Get-AzureWebsite|OLD Portal|NEW Portal
----------------|----------|----------
HttpLoggingEnabled = True, & AppSettings does **NOT** have: WEBSITE_HTTPLOGGING_CONTAINER_URL|Configuration > Site Diagnostics > Web Server Logging = "File System"|Settings > Diagnostics logs > Web server logging = "ON"
HttpLoggingEnabled = False|Configuration > Site Diagnostics > Web Server Logging = "OFF"|Settings > Diagnostics logs > Web server logging = "OFF"
HttpLoggingEnabled = True, & AppSettings has: WEBSITE_HTTPLOGGING_CONTAINER_URL|Configuration > Site Diagnostics > Web Server Logging = "STORAGE"|Settings > Diagnostics logs > Web server logging = "ON" **NOTE**: the NEW portal offers **NO** way of configuring the STORAGE container
AzureTableTraceEnabled = True, & AppSettings has: DIAGNOSTICS_AZURETABLESASURL|Configuration > Application Diagnostics > Application Logging (Table Storage) = "ON"|Settings > Diagnostics logs > Application logging (Filesystem) = "OFF"
AzureDriveTraceEnabled = True|Configuration > Application Diagnostics > Application Logging (File System) = "ON"|Settings > Diagnostics logs > Application logging (Filesystem) = "ON"
AzureBlobTraceEnabled = True, & AppSettings has: DIAGNOSTICS_AZUREBLOBCONTAINERSASURL|Configuration > Application Diagnostics > Application Logging (BLOB Storage) = "ON"|Settings > Diagnostics logs > Application logging (Filesystem) = "OFF"  **NOTE** the NEW portal offers **NO** way of configuring the STORAGE container

**Comment by matthewcanty** [comment]
@mcrsw looks really interesting. I will have to come back to this at some point and I'm sure this will be very helpful when I do. Can you confirm that this has solved your issue, or if these are just findings?

**Comment by mcrsw** [comment]
@matthewcanty these are just my findings to date. I'm still in the discovery stage ;-) yet I shall report back with actual success/failure over the next few days.

Just out of interest - are you expecting to use the ARM, or the ASM related cmdlets to modify your website's config?  As a newbie to the powershell cmdlets, I'm not clear yet on whether it is wise to mix ARM and ASM in the same .ps1 file (for example)? I'm aware of the need to Switch-AzureMode - but that gives a deprecated warning.

**Comment by matthewcanty** [comment]
I wouldn't be able to advise on that front... I'm not sure exactly what ASM is. 

Just checked out https://msdn.microsoft.com/en-us/library/dn722470.aspx

It suggests not switch during the same session but otherwise looks okay to use in the same script.

**Comment by maddieclayton** [comment]
We are no longer taking any changes in Azure.Websites. Please use the AzureRM modules in the future.

**Comment by rifaterdemsahin** [comment]
are we also including the retention date here ? the script works but we are not getting the errors.
