### ISSUE TITLE
Update error message to reflect the use of AzureRM* cmdlet instead of Azure*

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#3175]
### Cmdlet(s)
Get-AcsFarm
### PowerShell Version
1.2.6
### Module Version
0.10.1
### Description
The error message should say *AzureRM*  instead of *Azure*

The Azure profile is invalid, Make sure that you are in the Azure context with the Add-AzureEnvironment and Add-AzureAccount cmdlets

### Script/Steps for Reproduction

Execute Get-ACSFarm cmdlet without doing Add-AzureRmEnvironment or Add-AzureRMAccount

**Comment by markcowl** [comment]
@bganapa what module is this cmdlet in?

**Comment by bganapa** [comment]
@markcowl This is in AzureStackStorageAdmin Module

**Comment by cormacpayne** [comment]
@bganapa Hey Bala, is this still an issue?

**Comment by bganapa** [comment]
@cormacpayne Nope, Closing it
