### ISSUE TITLE
[Get-AzureRmSubscription]: Error listing multiple pages of subscriptions with multiple tenants

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3186]
When listing subscriptions in a tenant using subscription id (Get-AzureRmSubscription -SubscriptionId <subId>) , We do not follow nextLink pages.  However, since we are using a ref in each call, we retain the nextLink context when listing subscription in subsequent tenants.  This causes us to

(1) Not get the subscriptions in the next page of results
(2) Not get subscriptions for the following tenant, because we retain the nextLink context, and so pass in a skipToken incorrectly.

We need to refactor this code for listing by id or subscription, so that we always consider each page of data before moving on to the next tenant, and ensuring that the ListNext context is not carried over.

Here is where the call currently fails:  https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Profile/Commands.Profile/Models/RMProfileClient.cs#L406 

- [ ] refactor the code so that there is a single method that lists and returns all subscriptions, with an optional select clausewhen subscriptionId or subscriptionName are provided. This should be used in all places where a list of subscriptions is acquired
- [ ] Additionally refacotr so that when subscriptionId is provided, we always get the subscription by id rather than list it
- [ ] Fill in unit test gaps to include multiple pages of subscriptiosn in multipel tenants when:
         - logging in, getting a subscription, selecting a subscription
         - listing all subscriptions in all tenants
         - selecting a subscription in any tenant by name or id
         - selecting a subscription in a specific tenant by name and id

###Cost: 4

**Comment by cormacpayne** [comment]
Fix can be found [here](https://github.com/cormacpayne/azure-powershell/tree/subscription-paging-fix)

Will update with PR once https://github.com/Azure/azure-powershell/pull/3423 is merged

**Comment by cormacpayne** [comment]
Fix is in PR: https://github.com/Azure/azure-powershell/pull/3466
