### ISSUE TITLE
Update-AzureRmVmss default parameters not needed

### ISSUE THREAD

**Issue by mohamedmansour** [Azure/azure-powershell#3187]
Hello, 

Take a look at this example, I am basically trying to add an extra vm to the existing scaleset (from 1 to 2), so I am doing the following:

```
$vmss = Get-AzureRmVmss -ResourceGroupName resourcefoo -VMScaleSetName scalesetfoo
$vmss.Sku.Capacity = 2
Update-AzureRmVmss -ResourceGroupName resourcefoo -VirtualMachineScaleSet $vmss​​​​​​ -Name scalesetfoo
```

Since I am already passing `$vmss` to `Update-AzureRmVmss` why do we need to supply `-ResourceGroupName` and `-Name` ?

For this case, it should be consistent:

`Update-AzureRmVmss -VirtualMachineScaleSet $vmss​​​​​​`

What do you say?

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
@gbowerman Hey Guy, would you mind taking a look at this issue?

**Comment by gbowerman** [comment]
I agree we shouldn't need to provide these values.

**Comment by praries880** [comment]
[The cmdlet](https://github.com/Azure/azure-powershell/blob/ffb67e35469d82760e7dcae4feaece9bc9605dee/src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachineScaleSet/VirtualMachineScaleSetUpdateMethod.cs#L120) is autogenerated. 

@gatneil can you take a look?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
