### ISSUE TITLE
Register-AzureRmAutomationScheduledRunbook: add support for RunOn

### ISSUE THREAD

**Issue by gregjhogan** [Azure/azure-powershell#3197]
Please add a `-RunOn` parameter to `Register-AzureRmAutomationScheduledRunbook` similar to `Start-AzureRmAutomationRunbook`

**Comment by cormacpayne** [comment]
@safeermohammed Hey Safeer, would you mind taking a look at this issue?

**Comment by safeermohammed** [comment]
Support was added a while back, seems like the issue is not closed. Register-AzureRmAutomationScheduledRunbook supports RunOn
