### ISSUE TITLE
.ps1xml files not signed - refuses to run in allsigned environment and Installation woes

### ISSUE THREAD

**Issue by cmcknz77** [Azure/azure-powershell#320]
Hi,
I'm in an allsigned environment.  This means that when I or any of my colleagues attempt to install these cmdlets, the installation occurs successfully but the module refuses to install or errors on installation because of all the unsigned .ps1xml files.  I have been able to work around this by signing the files using my own local machine certificate in order to get the module to run, but that's a pretty major faff to have to go through.

Additionally, the installation process replaces as opposed to amends the default PSModulePath system environment variable in an attempt to add the module's installation location to the list of Module Paths.  On my machine (a Win8.1 Ent 64bit) this resulted in NONE of the modules in my personal Modules folder being accessible to me in a default shell after this module was installed.  I had to go and manually remove the additional path in order to reset that environment variable to it's default values in order to allow my personal modules to load... I am working around this by providing the full installation path to the module every time I need to import it, and because it's quite a long path, this is quite a pain.

**Comment by markcowl** [comment]
@cmcknz77 The psixml issue will be fixed in the next version of AzurePowerShell (shipping next week). The installer is intentialnally a system-wide and not a user-epecific install, which is why we append to the machine environment variable.

**Comment by markcowl** [comment]
@cmcknz77 Can you please provide details on why your other module were impacted by our addition to the env var, is there an issue with the length of your PSModulePath?

**Comment by markcowl** [comment]
Closing for now.  The version about to be released (0.9.2) which is currently in the release branch solves the ps1xml issue.
