### ISSUE TITLE
Slot settings for a deployment slot

### ISSUE THREAD

**Issue by milannankov** [Azure/azure-powershell#3201]
### Cmdlet(s)
Set-AzureRmWebAppSlotConfigName

### PowerShell Version
PSVersion                      5.1.14393.206
CLRVersion                     4.0.30319.42000

### Module Version
2.3.0

### OS Version
BuildVersion                   10.0.14393.206

### Description
SetAzureWebAppSlotConfigName does not seem to work when trying to designate an app setting as slot setting for a staging slot.

### Debug Output
Set-AzureRmWebAppSlotConfigName : Operation returned an invalid status code 'NotFound'
At line:1 char:1
+ Set-AzureRmWebAppSlotConfigName -AppSettingNames "SlotName"  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmWebAppSlotConfigName], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.DeploymentSlots.SetAzureWebAppSlotConfigName

### Script/Steps for Reproduction
- Create a Web App with a deployment slot (say "staging")
- Add one app setting to the deployment slot with key "TestSetting"
- Try to set "TestSetting" as slot setting using Set-AzureRmWebAppSlotConfigName using the name of the staging slot
- You will get "Operation returned an invalid status code 'NotFound'"
- Keep in mind that if the name is wrong you will get a proper error message saying that the resource is not found. Also this Cmdlet works fine if you specify the name of the production slot.

**Comment by cormacpayne** [comment]
@Nking92 Hey Nicholas, would you mind taking a look at this issue?

**Comment by ahmedelnably** [comment]
Hello @milannankov is this still happening?

This blog post explains how to set slot settings (a.k.a sticky settings)

[http://ruslany.net/2016/10/using-powershell-to-manage-azure-web-app-deployment-slots/](http://ruslany.net/2016/10/using-powershell-to-manage-azure-web-app-deployment-slots/)

Here is how to set them.

Set-AzureRmWebAppSlotConfigName -ResourceGroupName $rg -name $site -AppSettingNames "SlotName","Environment" -ConnectionStringNames "PrimaryDB","SecondaryDB"
