### ISSUE TITLE
[ADFS]:Calling Add-AzureRmEnvironment twice makes "ValidateAuthority" automatically true and break ADFS scenarios

### ISSUE THREAD

**Issue by mtandon80** [Azure/azure-powershell#3202]
### Cmdlet(s)
Add-AzureRmEnvironment
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### Module Version
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
We (Bala and me) had seen the behavior where calling “Add-AzureRmEnvironment” twice in a script cause validateAuthority to set “True” makes script to fail in case of ADFS.

Attachment having sample script and debug log with this issue

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
Script and Debug output attached

**Comment by cormacpayne** [comment]
@mtandon80 Hey Manish, what version of Aazure PowerShell are you using?

**Comment by bganapa** [comment]
@cormacpayne powershell version used is 1.2.8

**Comment by cormacpayne** [comment]
@mtandon80 would you mind trying this with Azure PowerShell 1.2.11?

**Comment by bganapa** [comment]
@cormacpayne, @mtandon80 I fixed this with PR, Closing this
https://github.com/Azure/azure-powershell/pull/3593
