### ISSUE TITLE
Restore-AzureRmSqlDatabase help is not up to date, mostly missing.

### ISSUE THREAD

**Issue by towerbe** [Azure/azure-powershell#3203]
### Cmdlet(s)
Restore-AzureRmSqlDatabase

### PowerShell Version
Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  117

### Module Version
2.3.0
### OS Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      10586  117

### Description
The help file for this command is virtually empty, containing no information on parameters, no examples, etc.  The documentation on MSDN for the same cmdlet is much more extensive, but is also incorrect as it contains examples that use parameters that are no longer available in the cmdlet.  The help needs to updated.

### Debug Output
none

### Script/Steps for Reproduction
get-help Restore-AzureRmSqlDatabase

**Comment by cormacpayne** [comment]
@jamestao  Hey James, would you mind taking a look at this issue?

By the way, I have [created a module](https://github.com/Azure/azure-powershell/blob/dev/documentation/platyPSHelp-documentation.md) that uses platyPS to create and validate markdown help for service teams, if you would like to take a look since this issue involves help

**Comment by towerbe** [comment]
Cormac,

I'm finding a lot of the SQL related cmdlets have little or no content in
the help files. This may be a more far reaching issue than just one cmdlet.

**Comment by cormacpayne** [comment]
@towerbe thanks for the heads-up. I created the previously mentioned module so teams can easily create and update their help using markdown and then validate the help for each cmdlet to make sure they have the necessary sections (description, parameter information, examples, etc.) filled out for users. 

Our plan is to have all of the service teams use the module to update and validate their help, and possibly add a validation step to our CI that will fail if the provided help is not complete.

**Comment by cormacpayne** [comment]
Closing this as the help has been updated for `Restore-AzureRmSqlDatabase` (as well as other Sql cmdlets)

@towerbe please feel free to reopen this issue if you think this is still an issue.
