### ISSUE TITLE
Azure Automation

### ISSUE THREAD

**Issue by Qbone2089** [Azure/azure-powershell#3210]
I have been testing on my local computer and managed to get my automation code setup.
But i have encountered and issue with converting datetime variables to strings.

$start = ($pauseautomationstart).ToShortDateString(), this works on my local computer, but not in my azure automation.

I get this error 
Method invocation failed because [System.String] does not contain a method named 'ToShortDateString'.

Any one know why ?

**Comment by markcowl** [comment]
Qbone2089 This is not the repository for the Azure Automation service.  Please place this question through the Azure Forums and the service team will get back to you.
