### ISSUE TITLE
Import-AzureRmApiManagementApi commandlet is expecting apiId as mandatory field

### ISSUE THREAD

**Issue by shilsmarty** [Azure/azure-powershell#3217]
### PowerShell Version - 5.1.14393
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version - 10.0.14
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
Import-AzureRmApiManagementApi commandlet is expecting apiId as mandatory field.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

1.) Module installed on my machine for APIM is AzureRM.ApiManagement 3.1.0
2.) was trying to use this command let
3.) Import-AzureRmApiManagementApi -Context $context -SpecificationPath "C:\Git-UHRS\HR-HRC-UHRS-EventSystem\Deployment\Deployment\Templates\IndividualResources\ApiManagement\ApiDefinition\InboundService.wadl.xml" -SpecificationFormat wadl -Path "inbound"
4.) Error Message : 
 Import-AzureRmApiManagementApi : Value cannot be null.
Parameter name: aid
At line:21 char:1
+ Import-AzureRmApiManagementApi -Context $context -SpecificationPath " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Import-AzureRmApiManagementApi], ArgumentNullException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.ImportAzureApiManagementApi 
5.) As per the documentation here - 
https://docs.microsoft.com/en-us/powershell/resourcemanager/apimanagement.servicemanagement/v1.1.4/Import-AzureRmApiManagementApi?redirectedfrom=msdn  it should not be mandatory.

**Comment by markcowl** [comment]
@solankisamir  Can you take  a look

**Comment by solankisamir** [comment]
@markcowl sure.

**Comment by solankisamir** [comment]
This is fixed for December 14 release of powershell client.
