### ISSUE TITLE
New-AzureResouce doesn't support global proxy types

### ISSUE THREAD

**Issue by rjmax** [Azure/azure-powershell#322]
Was trying to use the generic resource CRUD cmdlets to create a policy assignment.  I know there are assignment specific cmdlets – not the point here :)

First, I tried to run the generic new-azureresource cmdlet, which requires a location field.  Providing no location causes the cmdlet to throw client side; providing a location causes a deserialization error.

Additionally, I am unable to get any global proxy only resources, since they aren’t returned by the /resources API.

Screenshots available upon request.

**Comment by devigned** [comment]
Please provide the commands issued to repo.

**Comment by rjmax** [comment]
![image](https://cloud.githubusercontent.com/assets/1616243/7127030/8a3825e8-e1f3-11e4-9ef5-e2c936de69ed.png)

**Comment by vivsriaus** [comment]
@rjmax This should be fixed with the latest powershell. Please retry.
