### ISSUE TITLE
Typo in text for filing issues

### ISSUE THREAD

**Issue by davidmatson** [Azure/azure-powershell#3230]
help Get-AzureRmResource

Says:
 If you find an issue with this cmdlet, please create an issue on https://github.com/Azure/azure-powershell/issues, with a lable "ResourceManager".

Note the typo in "lable" (should say "label").

**Comment by markcowl** [comment]
@ravbhatnagar can you take  a look?  @davidmatson If you like, feel free to contribute a fix.  I guarantee this is just a change in the resource file.

**Comment by ravbhatnagar** [comment]
@davidmatson - Feel free to send a PR. If not, we will address this in one of the upcoming releases.

**Comment by cormacpayne** [comment]
@davidmatson this has been fixed in the latest release (3.6.0)
