### ISSUE TITLE
Undocumented behavior for Set-AzureRmVmCustomScriptExtension when running with -ForceRerun and -FileName parameters regarding access to the file's Azure storage blob

### ISSUE THREAD

**Issue by vladbarosan** [Azure/azure-powershell#3232]
### Cmdlet(s)
`Set-AzureRmVmCustomScriptExtension`

### Script/Steps for Reproduction

Run `Set-AzureRmVmCustomScriptExtension` with the `-ForceRerun` parameter and specify the script using `-FileName` and the related paramters necessary to locate it in Azure Storage. After 24 hours, when the VM starts, it will fail to provision the extension as it cannot access the Storage Blob where the script specified to the cmdlet is stored.  

This happens because in [SetAzureVMCustomScriptExtensionCommand.cs](https://github.com/Azure/azure-powershell/blob/2eaf6175bc2533b83689120dc7f595ff0bdf8001/src/ResourceManager/Compute/Commands.Compute/Extension/CustomScript/SetAzureVMCustomScriptExtensionCommand.cs#L237) the SAS token is set to expire in 24 hours. 

The issue is not necessarily that it expires in 24h, it is completely reasonable that the token needs to expire at one point, but this behavior should be documented as it is completely unexpected for the users that the extension will fail to work without any change on their side after 24 hours. Also, I would suggest that, on top of documenting this, to have a recommendation how to proceed in specifying how to set the desired permitted access time on the Azure Storage blob.

**Comment by vladbarosan** [comment]
To add that I saw this expiry time also in the classic stack, not just in ARM.

**Comment by markcowl** [comment]
@singhkays Please take a look.  Note that if you guys converted to the new platyPS tool for help, it would be easier for customers like @vladbarosan to contribute fix throught he cmdlet help markdown file.

**Comment by vladbarosan** [comment]
@markcowl , @singhkays I was also thinking if having the option in this case to specify `-ForceRerun` without using `-FileUri` (but using `-FileName` etc) makes sense. I don't know if there would be a situation where customers would want to have their access to the Storage Account expired after 24h if they specify `-ForceRerun`.

Maybe adding another optional parameter to the ParamterSet `SetCustomScriptExtensionByContainerAndFileNames` like `-ExpirationTime` would be useful in this scenario ?

**Comment by cormacpayne** [comment]
@danielsollondon Hey Daniel, would you mind taking a look at this feature request?
