### ISSUE TITLE
Bug(?): Set-AzureRmSqlServerThreatDetectionPolicy storageEndpoint cannot be null or empty 

### ISSUE THREAD

**Issue by sharbag** [Azure/azure-powershell#3234]
### Cmdlet(s)
storageEndpoint cannot be null or empty.

### PowerShell Version
5.0.10586.117

### Module Version
3.1.0

### OS Version
10.0.10586.117

### Description
Set-AzureRmSqlServerThreatDetectionPolicy not working. It fails with error: "The parameter storageEndpoint cannot be null or empty" and storageEndpoint-Parameter is not availiable.

### Debug Output
DEBUG: 12:38:32 - SetAzureSqlServerThreatDetection begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 12:38:32 - using account id 'account'...
DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '12/01/2016 12:13:27 +00:00', MultipleResource? 'True', Tenant: 'myTenantId', UserId: 'WA
NU@amcsazure.onmicrosoft.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'account', Name: myTenantId, IdProvider: 'https://sts.windows.net/myTenantId/'
, Uid: 'f43052a8-05da-4c69-abca-9f2a7a94bc7f'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '12/01/2016 12:13:27 +00:00' Comparing to '12/01/2016 11:38:32 +00:00' With threshold '00:05:00', calculated time unti
l token expiry: '00:34:54.1168203'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/d3f0a9ff-f75b-47f2-a179-c041981316af/resourceGroups/WIS2GROUP/providers/Microsoft.Sql/servers/sqlServerName?api-version=2014-04-01

Headers:

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
x-ms-request-id               : 2e65396c-6c41-4983-aa06-7e06bcee24b5
X-Content-Type-Options        : nosniff
DataServiceVersion            : 3.0;
x-ms-ratelimit-remaining-subscription-reads: 14961
x-ms-correlation-request-id   : d4772757-4cce-4921-a674-e17a61cb048e
x-ms-routing-request-id       : WESTEUROPE:20161201T113833Z:d4772757-4cce-4921-a674-e17a61cb048e
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-store,no-cache
Date                          : Thu, 01 Dec 2016 11:38:33 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "tags": {
    "displayName": "SqlServer"
  },
  "id": "/subscriptions/d3f0a9ff-f75b-47f2-a179-c041981316af/resourceGroups/WIS2GROUP/providers/Microsoft.Sql/servers/sqlServerName",
  "name": "sqlServerName",
  "type": "Microsoft.Sql/servers",
  "location": "West Europe",
  "kind": "v12.0",
  "properties": {
    "fullyQualifiedDomainName": "sqlServerName.database.windows.net",
    "administratorLogin": "wisdb-admin",
    "administratorLoginPassword": null,
    "externalAdministratorLogin": null,
    "externalAdministratorSid": null,
    "version": "12.0",
    "state": "Ready"
  }
}

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '12/01/2016 12:13:27 +00:00', MultipleResource? 'True', Tenant: 'myTenantId', UserId: 'WA
NU@amcsazure.onmicrosoft.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'account', Name: myTenantId, IdProvider: 'https://sts.windows.net/myTenantId/'
, Uid: 'f43052a8-05da-4c69-abca-9f2a7a94bc7f'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '12/01/2016 12:13:27 +00:00' Comparing to '12/01/2016 11:38:33 +00:00' With threshold '00:05:00', calculated time unti
l token expiry: '00:34:53.4036990'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/d3f0a9ff-f75b-47f2-a179-c041981316af/resourceGroups/WIS2GROUP/providers/Microsoft.Sql/servers/sqlServerName/securityAlertPolicies/Default?api-version=2015
-05-01-preview

Headers:

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : bef03165-3d4d-44c0-924b-b57872f7b137
x-ms-ratelimit-remaining-subscription-reads: 14965
x-ms-correlation-request-id   : b4980b48-5f7a-4a87-aeab-7b2d487831b9
x-ms-routing-request-id       : WESTEUROPE:20161201T113833Z:b4980b48-5f7a-4a87-aeab-7b2d487831b9
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Thu, 01 Dec 2016 11:38:33 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "id": "/subscriptions/d3f0a9ff-f75b-47f2-a179-c041981316af/resourceGroups/WIS2GROUP/providers/Microsoft.Sql/servers/sqlServerName/securityAlertPolicies/Default",
  "name": "Default",
  "type": "Microsoft.Sql/servers/securityAlertPolicies",
  "kind": "",
  "properties": {
    "state": "Disabled",
    "disabledAlerts": "Preview",
    "emailAddresses": "",
    "emailAccountAdmins": "Enabled",
    "storageEndpoint": "",
    "storageAccountAccessKey": "",
    "retentionDays": 0
  }
}

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '12/01/2016 12:13:27 +00:00', MultipleResource? 'True', Tenant: 'myTenantId', UserId: 'WA
NU@amcsazure.onmicrosoft.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'account', Name: myTenantId, IdProvider: 'https://sts.windows.net/myTenantId/'
, Uid: 'f43052a8-05da-4c69-abca-9f2a7a94bc7f'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '12/01/2016 12:13:27 +00:00' Comparing to '12/01/2016 11:38:34 +00:00' With threshold '00:05:00', calculated time unti
l token expiry: '00:34:52.9658203'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/d3f0a9ff-f75b-47f2-a179-c041981316af/resourceGroups/WIS2GROUP/providers/Microsoft.Sql/servers/sqlServerName?api-version=2014-04-01

Headers:

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
x-ms-request-id               : bc9b0585-77d2-4f35-a0c1-d023ffe58608
X-Content-Type-Options        : nosniff
DataServiceVersion            : 3.0;
x-ms-ratelimit-remaining-subscription-reads: 14960
x-ms-correlation-request-id   : bff82fcd-647e-4943-8a68-a8144562354f
x-ms-routing-request-id       : WESTEUROPE:20161201T113834Z:bff82fcd-647e-4943-8a68-a8144562354f
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-store,no-cache
Date                          : Thu, 01 Dec 2016 11:38:34 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "tags": {
    "displayName": "SqlServer"
  },
  "id": "/subscriptions/d3f0a9ff-f75b-47f2-a179-c041981316af/resourceGroups/WIS2GROUP/providers/Microsoft.Sql/servers/sqlServerName",
  "name": "sqlServerName",
  "type": "Microsoft.Sql/servers",
  "location": "West Europe",
  "kind": "v12.0",
  "properties": {
    "fullyQualifiedDomainName": "sqlServerName.database.windows.net",
    "administratorLogin": "wisdb-admin",
    "administratorLoginPassword": null,
    "externalAdministratorLogin": null,
    "externalAdministratorSid": null,
    "version": "12.0",
    "state": "Ready"
  }
}

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '12/01/2016 12:12:55 +00:00', MultipleResource? 'True', Tenant: 'myTenantId', UserId: 'WA
NU@amcsazure.onmicrosoft.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'account', Name: myTenantId, IdProvider: 'https://sts.windows.net/myTenantId/'
, Uid: 'f43052a8-05da-4c69-abca-9f2a7a94bc7f'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '12/01/2016 12:12:55 +00:00' Comparing to '12/01/2016 11:38:34 +00:00' With threshold '00:05:00', calculated time unti
l token expiry: '00:34:21.6888291'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/d3f0a9ff-f75b-47f2-a179-c041981316af/resourceGroups/WIS2GROUP/providers/Microsoft.Sql/servers/sqlServerName/auditingPolicies/Default?api-version=2014-04-0
1

Headers:

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
x-ms-request-id               : 1d0d750f-cf0c-4627-ad0a-93685aa47315
X-Content-Type-Options        : nosniff
DataServiceVersion            : 3.0;
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 14915
x-ms-correlation-request-id   : 6deb2e6f-0401-4f30-af17-8e7a973de080
x-ms-routing-request-id       : WESTEUROPE:20161201T113834Z:6deb2e6f-0401-4f30-af17-8e7a973de080
Cache-Control                 : no-store,no-cache
Date                          : Thu, 01 Dec 2016 11:38:34 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "id": "/subscriptions/d3f0a9ff-f75b-47f2-a179-c041981316af/resourceGroups/WIS2GROUP/providers/Microsoft.Sql/servers/sqlServerName/auditingPolicies/Default",
  "name": "Default",
  "type": "Microsoft.Sql/servers/auditingPolicies",
  "location": "West Europe",
  "kind": null,
  "properties": {
    "auditingState": "Enabled",
    "eventTypesToAudit": "PlainSQL_Success;PlainSQL_Failure;ParameterizedSQL_Success;ParameterizedSQL_Failure;StoredProcedure_Success;StoredProcedure_Failure;Login_Success;Login_Failure;Trans
actionManagement_Success;TransactionManagement_Failure",
    "storageAccountName": "wisdevmonitoring",
    "storageAccountKey": "********",
    "storageAccountSecondaryKey": null,
    "storageTableEndpoint": "https://wisdevmonitoring.table.core.windows.net",
    "storageAccountResourceGroupName": "WIS2GROUP",
    "storageAccountSubscriptionId": "d3f0a9ff-f75b-47f2-a179-c041981316af",
    "fullAuditLogsTableName": "SQLDBAuditLogsWisdev20161201",
    "auditLogsTableName": "Wisdev",
    "retentionDays": "365"
  }
}

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '12/01/2016 12:13:27 +00:00', MultipleResource? 'True', Tenant: 'myTenantId', UserId: 'WA
NU@amcsazure.onmicrosoft.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'account', Name: myTenantId, IdProvider: 'https://sts.windows.net/myTenantId/'
, Uid: 'f43052a8-05da-4c69-abca-9f2a7a94bc7f'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '12/01/2016 12:13:27 +00:00' Comparing to '12/01/2016 11:38:34 +00:00' With threshold '00:05:00', calculated time unti
l token expiry: '00:34:52.8706990'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/d3f0a9ff-f75b-47f2-a179-c041981316af/resourceGroups/WIS2GROUP/providers/Microsoft.Sql/servers/sqlServerName/securityAlertPolicies/Default?api-version=2015
-05-01-preview

Headers:

Body:
{
  "properties": {
    "state": "Enabled",
    "disabledAlerts": "",
    "emailAddresses": "",
    "emailAccountAdmins": "Enabled",
    "retentionDays": 0
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-request-id               : 215deff3-12fd-4b9f-88c0-98ad9f8040ce
x-ms-ratelimit-remaining-subscription-writes: 1197
x-ms-correlation-request-id   : 81b6ae59-cd1b-4997-9ca4-8158cdcbaa6b
x-ms-routing-request-id       : WESTEUROPE:20161201T113834Z:81b6ae59-cd1b-4997-9ca4-8158cdcbaa6b
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Thu, 01 Dec 2016 11:38:33 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "error": {
    "code": "DataSecurityInvalidUserSuppliedParameter",
    "message": "The parameter storageEndpoint cannot be null or empty."
  }
}

Set-AzureRmSqlServerThreatDetectionPolicy : DataSecurityInvalidUserSuppliedParameter: The parameter storageEndpoint cannot be null or empty.
At line:1 char:1
+ Set-AzureRmSqlServerThreatDetectionPolicy -ResourceGroupName "WIS2GRO ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmSqlS...DetectionPolicy], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.ThreatDetection.Cmdlet.SetAzureSqlServerThreatDetection
 
DEBUG: 12:38:34 - SetAzureSqlServerThreatDetection end processing.
DEBUG: 12:38:34 - SetAzureSqlServerThreatDetection end processing.

### Script/Steps for Reproduction
Add-AzureRmAccount 
Select-AzureRmSubscription -SubscriptionName "xxx" 
Set-AzureRmSqlServerAuditingPolicy -ResourceGroupName "group" -ServerName "sqlServer" `
                -AuditType Table `
                -StorageAccountName "accountName" `
                -StorageKeyType Primary `
                -TableIdentifier TableName `
                -RetentionInDays 365 `
                -EventType All

Set-AzureRmSqlServerThreatDetectionPolicy -ResourceGroupName "group" -ServerName "sqlServer"  -EmailAdmins $true -ExcludedDetectionType None

**Comment by cormacpayne** [comment]
@yaakoviyun Hey Yaakov, would you mind taking a look at this issue?

**Comment by yaakoviyun** [comment]
Hi,
We've changed the required parameters for Threat Detection and as of next Powershell release there will be new storage parameter to use.

You'll need to use the new December installation that will be in: https://github.com/Azure/azure-powershell/releases/
