### ISSUE TITLE
Consolidate on single Security.Cryptography assembly that is authenticode-signed

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3237]
### Description

We ship 3 different copies of the security.cryptography assembly, which is checked in as a binary in 3 different locations in our source.  Two of these versions are not authenticode signed.  Need to place a single version of this assmbly in a central library directory and have all 3 ARM service cmdlet projects use this reference.

- [ ] AzureBackup
- [ ] RecoveryServices
- [ ] SiteRecovery
- [ ] Update authenticode signing to include this dll.  The most effective way to do this may be to use the assembly metadata (author and copyright information) to decide whether an assembly should be checked for Authenticode signature [basically, any assembly authored or copyrighted by Microsoft should be Authenticode signed]

Work with the feature team in each case to get them to agree on the new version.  Ship a version that is acceptable to all 3 teams and is authenticode signed.  Note that the version used by AzureBackup that is located here: https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/AzureBackup/Commands.AzureBackup/Resources/Security.Cryptography.dll  is the only version that is currently authenticode signed.  Start by asking whether all libraries can take a dependency on this.

**Comment by maddieclayton** [comment]
Will be fixed in Net Standard issue.
