### ISSUE TITLE
webapp:Improving help documentation

### ISSUE THREAD

**Issue by LukaszStem** [Azure/azure-powershell#3245]
### PowerShell Version
5.1.14393.206

### Module Version
Websites - 2.3

### OS Version
10.0.14393.206

### Description
Documentation in \src\ResourceManager\Websites\Commands.Websites\help needs to be updated to have more examples and verbose parameter descriptions. As well as a description of the output value from the specified cmdlet.

**Comment by LukaszStem** [comment]
@ruslany @ahmedelnably @naveedaz @akurmi please help with this.

**Comment by panchagnula** [comment]
The change pertains to this change list will run the Validate-ServiceMarkdownHelp with platyPSHelp to figure this out & fix

**Comment by panchagnula** [comment]
Most of the documentation is already fixed. Will file new issues for specific help commands if this is still neeeded.
