### ISSUE TITLE
Broken Link in Readme.MD

### ISSUE THREAD

**Issue by JKeithB** [Azure/azure-powershell#3248]
### Description

In the readme.md file at https://github.com/Azure/azure-powershell, under Installation.. PowerShell Gallery, you have a link to  Windows Management Framework 5 with PowerShellGet cmdlets that is not correct. 
The maintained link for the Windows Management Framework is aka.ms/wmf5latest.
The location you are pointing to in the PowerShell Gallery is the old Getting Started documentation, and should be changed to be https://msdn.microsoft.com/powershell/gallery/readme.

**Comment by Devinsuit** [comment]
Fixed in #3246

**Comment by cormacpayne** [comment]
Fix has been merged. Thanks!
