### ISSUE TITLE
Deleting many Azure VMs results in error

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#325]
Recently, I performed a stress test of sorts, where I attempted to create more than 50 virtual machines in a single Azure Cloud Service container. I understand that this isn't supported, but I wanted to test the behavior if it were attempted. After performing the test, I needed to remove all of the Azure VMs that I had created.

When I try to delete many Azure Virtual Machines, using the `Remove-AzureVM` command, I receive an error, every couple of VMs.

> Remove-AzureVM : InternalError : The server encountered an internal error. Please retry the request.

![image](https://cloud.githubusercontent.com/assets/466713/7081659/36511860-df03-11e4-89da-d977e5663870.png)

How do I ensure that VMs are removed properly, without this error? How can I investigate the root cause?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by devigned** [comment]
Hi Trevor, would you run this with $DebugPreference = "Continue" and ping back with the results?

**Comment by singhkay** [comment]
@pcgeek86 Can you see if this repros still?  And please include approximate trimeframe of the failure and any operation Ids which will help in debugging since this is a platform issue.

**Comment by pcgeek86** [comment]
@devigned @singhkay Sorry I dropped the ball on this. Let me try to reproduce it again. It may take me a little time.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
