### ISSUE TITLE
Add missing tests for IoT Hub Commandlets. Import / Export and Job related commandlets require SAS Uris to be generated on the fly. Remove hardcoded location in tests. Cleanup any duplicated scripts

### ISSUE THREAD

**Issue by rkmanda** [Azure/azure-powershell#3268]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@rkmanda has this been taken care of?

**Comment by cormacpayne** [comment]
@rkmanda ping

**Comment by jlian** [comment]
This is more like feature request for us

**Comment by jlian** [comment]
@anusapan do you know what @rkmanda is referring to in this issue and if it's still valid? Since this is a very old issue
