### ISSUE TITLE
When attempting to open a runspace, Azure Powershell attempts to load ServiceManagementStartup from the incorrect folder and fails

### ISSUE THREAD

**Issue by masisley** [Azure/azure-powershell#327]
As emailed to David Justice, when opening a runspace, Azure Powershell fails to find the ServiceManagementStartup.ps1 folder in ExpressRoute (it's acutally in SQL):

        static void Main(string[] args)
        {
            var sessionState = InitialSessionState.CreateDefault();
            sessionState.ImportPSModulesFromPath("C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\Powershell\\ServiceManagement\\Azure");
            using (var runSpace = RunspaceFactory.CreateRunspace(sessionState))
            {
                runSpace.Open(); // Fails
                Debugger.Break();
            };
        }

System.Management.Automation.CmdletInvocationException: C:\Program Files (x86)\Microsoft SDKs\Azure\Powershell\ServiceManagement\Azure\ExpressRoute\ServiceManagementStartup.ps1 ---> System.IO.FileNotFoundException: C:\Program Files (x86)\Microsoft SDKs\Azure\Powershell\ServiceManagement\Azure\ExpressRoute\ServiceManagementStartup.ps1 at Microsoft.WindowsAzure.Commands.Utilities.Common.FileUtilities.GetContentFilePath(String startDirectory, String fileName) at Microsoft.WindowsAzure.Commands.CloudService.TestAzureNameCommand.OnImport() at System.Management.Automation.Runspaces.PSSnapInHelpers.ExecuteModuleInitializer(Assembly assembly, Type[] assemblyTypes, Boolean isModuleLoad) atSystem.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& providers, String& helpFile) at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module) at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates) at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound) at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecification moduleSpecification, String moduleBase, Boolean searchModulePath, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean loadTypesFiles, Boolean loadFormatFiles, Object privateData, Boolean& found, String shortModuleName) at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo scriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version version, Version requiredVersion, ImportModuleOptions& options, Boolean& containedErrors) at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(ExternalScriptInfo scriptInfo, ManifestProcessingFlags manifestProcessingFlags, Version version, Version requiredVersion, ImportModuleOptions& options) at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound) at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name) at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord() at System.Management.Automation.CommandProcessor.ProcessRecord() --- End of inner exception stack trace --- at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input) at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke) at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync) at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings) at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings) at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings) at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings) at System.Management.Automation.Runspaces.LocalRunspace.ProcessImportModule(String name, PSModuleInfo moduleInfoToLoad, Boolean startLifeCycleEventWritten) at System.Management.Automation.Runspaces.LocalRunspace.ProcessImportModule(IEnumerable moduleList, Boolean startLifeCycleEventWritten) at System.Management.Automation.Runspaces.LocalRunspace.DoOpenHelper() at System.Management.Automation.Runspaces.RunspaceBase.CoreOpen(Boolean syncCall) at Microsoft.Cloud.Platform.Deployment.Tasks.PowerShellTaskBase.<>c__DisplayClass1.b__0() at Microsoft.Cloud.Platform.Utils.UtilsContext.RunWithClearContext(Action action) at Microsoft.Cloud.Platform.Deployment.Tasks.PowerShellTaskBase.ExecuteAttempt(ITaskExecutionEnvironment env, Int32 currentRetryAttrempt, Int32 maxRetries) at Microsoft.Cloud.Platform.Deployment.Automation.Core.RetriableTask.Execute(ITaskExecutionEnvironment env) at Microsoft.Cloud.Platform.Deployment.Tasks.PowerShellTaskBase.Execute(ITaskExecutionEnvironment env) at Microsoft.Cloud.Platform.Deployment.Automation.TaskRunner.ExecuteTaskInternal(AutomationTask deploymentStep, ITaskExecutionEnvironment env) at Microsoft.Cloud.Platform.Deployment.Automation.TaskRunner.ExecuteTaskProtected(AutomationTask deploymentStep, LocalExecuteEnvironment env, TaskRetryContext context) at Microsoft.Cloud.Platform.Deployment.Automation.TaskRunner.ExecuteTask(AutomationTask deploymentStep, TaskRetryContext context)

**Comment by stankovski** [comment]
This has been fixed in the latest version of Azure PowerShell
