### ISSUE TITLE
No WhatIf support in any of the AzureAD module cmdlets

### ISSUE THREAD

**Issue by jrochet** [Azure/azure-powershell#3270]
### Cmdlet(s)
Set-MSOL*
Set-AzureAD*

### PowerShell Version
5.0.10240.17146

### Module Version
1.1.166.0  MSOnline
2.0.0.33   AzureAD

### OS Version
10.0.10011.16384

### Description
None of the Set-* cmdlets in these modules support -WhatIf (i.e. shouldprocess).

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
Unable to do this.

### Script/Steps for Reproduction
Just do Get-Help Set-MsolUser -Full and look through the parameters section.

**Comment by cormacpayne** [comment]
@jrochet Hey Jeremy, I'm going to close this issue since our team does not own these cmdlets, and your question has been addressed [here](https://docs.microsoft.com/en-us/powershell/msonline/v1/azureactivedirectory) by the appropriate team. Thanks!
