### ISSUE TITLE
Get-AzureRmResource does not take empty ResourceName parameter to list all resources of a ResourceType

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#3273]
### Cmdlet(s)
Get-AzureRmResource
### PowerShell Version
1.2.6(Azurestack)

### Description
I am in need of tricking the cmdlet by passing simply "/" to get the list of all resources. Following is an example 

 Get-AzureRmResource -ResourceType "Microsoft.Storage/skus" -ResourceName "/"

### Script/Steps for Reproduction
 Get-AzureRmResource -ResourceType "Microsoft.Storage/skus" -ResourceName "/"

**Comment by markcowl** [comment]
@ravbhatnagar  can you take a look?  I believe they are looking for a simple way to list all resources of a particular type

**Comment by ravbhatnagar** [comment]
@bganapa - Please use Find-AzureRmResource -ResourceType <> to list all the resources of a type under a subscription. You should already have this in the Azure Stack PS version you have

To list all the resources of a type under a resource group, please use Find-AzureRmResource -ResourceType <> -ResourceGroupEquals <rgName>.  This was added recently, so the Azure Stack PS version you are using may not have it. 

Let us know if you still see this issue

**Comment by cormacpayne** [comment]
Closing this issue.

@bganapa please reopen this issue if you find the above solution does not work.
