### ISSUE TITLE
0.8.16.1 Preview ::Deserialized StorageContext can't be converted to StorageContext

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#328]
When I try to pass a `StorageContext` object into a PowerShell Background Job as an argument, I am getting an error that the deserialized object cannot be converted back into a `StorageAccount`. Is this behavior intentional from a design perspective, or can this be fixed somehow?

> Cannot bind parameter 'Context'. Cannot convert the "Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext" value of type 
"Deserialized.Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext" to type "Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext".
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureStorageContainer], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageContainerCommand
    + PSComputerName        : localhost

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by gangsir** [comment]
@pcgeek86 This is by design for security reason. The storage account object from the dependency storage library doesn't support reading its credentials out. Sorry about that.
