### ISSUE TITLE
Validate-ServiceMarkdownHelp incorrectly reports "No description found for parameter" when parsing lines with curly braces.

### ISSUE THREAD

**Issue by adarce** [Azure/azure-powershell#3282]
I'm from the Azure Key Vault team, and I recently tried to use platyPS for our help files, [as described here](https://github.com/Azure/azure-powershell/blob/6c44dcd74cb69b536113ed04bca00dd84e9bac6a/documentation/platyPSHelp-documentation.md#running-the-validate-servicemarkdownhelp-cmdlet). After generating some Markdown help files and running the `Validate-ServiceMarkdownHelp` cmdlet, there seems to be an issue with parsing lines that happen to contain curly braces, such as examples with inline hashtable literals or script blocks. For example, one of our Markdown help files contains the following two snippets:

**Snippet 1: Example code contains an inline hashtable literal `@{...}`**
````
### Example 1: Modify the attributes of a secret
```
PS C:\> $Expires = (Get-Date).AddYears(2).ToUniversalTime()
PS C:\> $Nbf = (Get-Date).ToUniversalTime()
PS C:\> $Tags = @{ 'Severity' = 'medium'; 'HR' = null}
PS C:\> $ContentType= 'xml'  
PS C:\> Set-AzureKeyVaultSecretAttribute -VaultName 'ContosoVault' -Name 'HR' -Expires $Expires -NotBefore $Nbf -ContentType $ContentType -Enable $True -Tags $Tags -PassThru
```
````
**Snippet 2: Example code contains a script block `Where-Object {...}`**
````
### Example 3: Disable the current version of secrets whose name begins with IT
```
PS C:\> $Vault = 'ContosoVault'
PS C:\> $Prefix = 'IT'
PS C:\> Get-AzureKeyVaultSecret $Vault | Where-Object {$_.Name -like $Prefix + '*'} | Set-AzureKeyVaultSecretAttribute -Enable $False
```
````

`Validate-ServiceMarkdownHelp` reports the following issues:
````
-- No description found for parameter \> $Nbf = (Get-Date).ToUniversalTime()
-- No description found for parameter \> $Prefix = 'IT'
````

Notice that _the issues that they report are just above the lines that contain curly braces_. Indeed, we actually do have descriptions for these two parameters `$Nbf` and `$Prefix`. The problem here has to do with some wildcard matching of `"*{*}*"`. [See here for the code responsible for this.](https://github.com/Azure/azure-powershell/blob/dev/tools/platyPSHelp/platyPSHelp.psm1#L494-L499)

**Comment by cormacpayne** [comment]
@adarce Hey Adriano, thanks for reporting this issue. That wildcard was included after I found the resulting description generated for some parameters matched something similar to an empty hashtable. I will see if this has been fixed by the platyPS team and will take a look at it as soon as I can!

**Comment by cormacpayne** [comment]
Fix for this issue is in PR https://github.com/Azure/azure-powershell/pull/3296

**Comment by cormacpayne** [comment]
The fix has been merged.
