### ISSUE TITLE
Get-AzureKeyVaultSecret: Index was out of range

### ISSUE THREAD

**Issue by 176coding** [Azure/azure-powershell#3283]
### Cmdlet(s)
Get-AzureKeyVaultSecret
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.0.10586.117 
### Module Version
Microsoft Azure Powershell Version: 1.3.2
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.10586.117 
### Description
this is the error msg when I run in multithreading using RunspacePool
```
Get-AzureKeyVaultSecret : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: indexAt line:1 char:1
+ Get-AzureKeyVaultSecret -VaultName "KeyVaultPrism" -Name "ChannelRead ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureKeyVaultSecret], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : System.ArgumentOutOfRangeException,Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret
```
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
```
[DBG]: PS C:\Users\abc>> Get-AzureKeyVaultSecret -VaultName "KeyVaultPrism" -Name "ChannelReader-int-local-Cassandra-Channel-Name"
5:18:36 PM - GetAzureKeyVaultSecret begin processing with ParameterSet 'BySecretName'.
5:18:36 PM - using account id 'abc@xx.com'...
Get-AzureKeyVaultSecret : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: indexAt line:1 char:1
+ Get-AzureKeyVaultSecret -VaultName "KeyVaultPrism" -Name "ChannelRead ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureKeyVaultSecret], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : System.ArgumentOutOfRangeException,Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret
```

**Comment by cormacpayne** [comment]
@pomortaz Hey Pooneh, would you mind taking a look at this issue?

**Comment by maddieclayton** [comment]
@176coding Could not repro with the steps above - if you are still seeing this issue, please reopen and provide more specific steps on how to reproduce this issue.
