### ISSUE TITLE
Show inner exception when error is thrown in Azure PowerShell

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3287]
From @begoldsm

Is there a plan for Azure PowerShell to surface "inner exceptions" in a more prominent way when an error is thrown?

For example, if a user tries to call DataLake commands with a bad DNS, the following is thrown by Azure PowerShell:

```powershell
PS C:\> Get-AdlJob -Account nonexsitentaccount
Get-AdlJob : *An error occurred while sending the request.*
```

This top line error message is vague, 

```powershell
PS C:\> $fullEx = $Error[0]
PS C:\> $fullEx.Exception
An error occured while sending the request.
```

But if you look at the inner exception, the error becomes clear

```powershell
PS C:\> $fullEx.Exception.InnerException
The remote name could not be resolved 'nonexistentaccount.azuredatalakeanalytics.net'
```

**Comment by markcowl** [comment]
Note that making this available in the error record is the powershell standard. We have given users easier access to this (and other) important exception information in the ```Resolve-AzureRm,Error``` cmdlet
