### ISSUE TITLE
Azure Key Vault Validation Tests (3) are Failing. All are Certificate related.

### ISSUE THREAD

**Issue by jkapil** [Azure/azure-powershell#3288]
### Cmdlet(s)
Key Vault Certificate related data plane

### PowerShell Version
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Module Version
2.3.0      AzureRM.KeyVault

### OS Version
10.0.14393

### Debug Output
============
FAILED TESTS
============
FAILED  Test_ImportPfxAsCertificate:  00:00:02.1562537
FAILED  Test_ImportX509Certificate2CollectionAsCertificate:  00:00:00.6718842
FAILED  Test_ImportBase64EncodedStringAsCertificate:  00:00:00.6249976
============

### Script/Steps for Reproduction
cd c:\kj\azure-powershell\src\Package\Debug\ResourceManager\AzureResourceManager
Import-Module .\AzureRM.Profile\AzureRM.Profile.psd1 -Force 
Import-Module .\AzureRM.Resources\AzureRM.Resources.psd1 -Force
Import-Module .\AzureRM.Tags\AzureRM.Tags.psd1 -Force
Import-Module .\AzureRM.KeyVault\AzureRM.KeyVault.psd1 -Force
Login-AzureRmAccount -SubscriptionName <>
cd c:\kj\azure-powershell\src\ResourceManager\KeyVault\Commands.KeyVault.Test\Scripts
$location = "South Central US"
$name=<>
Remove-AzureRmResourceGroup -Name $name -Location -Force  -ErrorAction SilentlyContinue
New-AzureRmResourceGroup -Name $name -Location $location
New-AzureRmKeyVault -VaultName $name -Location $location -ResourceGroupName $name -Sku Premium
.\RunKeyVaultTests.ps1 -TestRunNameSpace PSRun01 -TestMode All -Location $location -Vault $name -ResourceGroup $name

**Comment by adarce** [comment]
The fix for this issue is in PR #3298

**Comment by markcowl** [comment]
fixed.
