### ISSUE TITLE
Get-AzureSubscription -ExtendedDetails doesn't show TenantId information

### ISSUE THREAD

**Issue by singhkay** [Azure/azure-powershell#329]
Get-azuresubscription without the –extendeddetails attribute I see the TenantId

TenantId                  : 72f9182f-86f1-41af-92ab-2d7cd112db47
 
If I do extendeddetails it doesn’t show the tenantId.  This seems like a bug.

TenantId                   :

**Comment by pcgeek86** [comment]
I can confirm the same behavior. When you use the `-ExtendedDetails` parameter with `Get-AzureSubscription`, the Azure Active Directory (AAD) TenantId is not returned. @markcowl @singhkay 

![image](https://cloud.githubusercontent.com/assets/466713/7109841/ce000e7a-e163-11e4-92ba-a4fcd88ece8d.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by devigned** [comment]
Yes. Extended details should be a super set of default.
