### ISSUE TITLE
New-AzureRmContainerServiceConfig - No "OrchestratorType" enum for Kubernetes ?

### ISSUE THREAD

**Issue by marceldempers** [Azure/azure-powershell#3297]
### Cmdlet(s)
New-AzureRmContainerServiceConfig

### PowerShell Version
Name                           Value                                                                                                                                                               
----                           -----                                                                                                                                                               
PSVersion                      5.0.10240.16384                                                                                                                                                     
WSManStackVersion              3.0                                                                                                                                                                 
SerializationVersion           1.1.0.1                                                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                                                     
BuildVersion                   10.0.10240.16384                                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                             
PSRemotingProtocolVersion      2.3   

### Script/Steps for Reproduction

Look at the enum available for New-AzureRmContainerServiceConfig -OrchestrationType and it can only accept DCOS and Swarm as values. Do the CMDlets not support Kubernetes ?

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
This appears to have been fixed. Closing.
