### ISSUE TITLE
New-AzureStorageContext Default Endpoint

### ISSUE THREAD

**Issue by qin-nz** [Azure/azure-powershell#330]
After I use ````Select-AzureSubscription```` to change the environment to AzureChinaCloud,  
````New-AzureStorageContext```` still use the endpoint "core.windows.net" by default. 
(I know I can use ````-Endpoint```` to switch endpoint, but it's confusing.)

**Comment by markcowl** [comment]
@DingyuanHu Thanks for the suggestion.  We will consider this functionality for a future release

**Comment by markcowl** [comment]
Storage team, the ask is to use the subscription's environment when creating a StorageContext

**Comment by gangsir** [comment]
Thanks for the feedback. We will look at adding this in future sprint.

**Comment by EmmaZhu** [comment]
The feature has been added to Azure PSH. Could you try with the latest version?

**Comment by qin-nz** [comment]
ohh, @EmmaZhu 
I have switch to Rm mode. 
And for some reason, it hard for me to test it.
