### ISSUE TITLE
Automate Module tagging

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#3307]
### Description
- [ ] Add a metadata tag ```RP:api-version``` to each module
- [ ] Automate retrieval of api-version from client-side code [ApiVersion property] and update of tag in psd1 as part of release preparation scripts
- [ ] Move profile map into preview branch, Automate update of api version map here: https://github.com/Azure/azure-powershell/blob/stack-dev/tools/AzureRM.BootStrapper/ProfileMap.json  for latest version, as part of release activities

### Cost: 6

**Comment by cormacpayne** [comment]
@viananth @bganapa do you all have a timeline for when this should happen?

**Comment by bganapa** [comment]
We have not factored this work item yet
