### ISSUE TITLE
Use PowerShell Sessions to load cmdlet versions in the same powershell process

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#3309]
_From @markcowl on November 14, 2016 22:53_

### Description

- [ ] Implement session management to allow loading cmdlets from a profile, replacing the cmdlets in the current session
- [ ] Allow setting a prefix so that cmdlets can be used in the same session

### Cost: 4

_Copied from original issue: markcowl/azure-powershell#12_

**Comment by markcowl** [comment]
Closing as duplicate
