### ISSUE TITLE
Generate profile metadata to include all relevant modules, and the latest versions

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#3310]
_From @markcowl on November 14, 2016 22:45_

### Description

- [x] Add static profile metadata fopr the latest packages
- [ ] Create a cmdlet to generate profile metadata map from the gallery (latest should come from latest package version, Other profiles should come from tags.

### Cost: 4

_Copied from original issue: markcowl/azure-powershell#9_

**Comment by bganapa** [comment]
not relevant anymore
