### ISSUE TITLE
Fail to publish azure stack nugets to Test Gallery

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-powershell#3316]
Signed nugets cannot be published on Test Gallery

Reason:
1) We do bunch of post processing once the nugets are created (e.g. updating dependent modules, removing * from cmdlets to export. Also add underlying .psm1 file to the module manifest etc etc.
2) In doing so we fail to re-package nuget once we make all this changes
3) Also TestGallery is v2 based and PS gallery is v3 based, hence you need a particular version of nuget to pack and push the nuget packages

**Comment by markcowl** [comment]
Fixed.
