### ISSUE TITLE
When sending Update-AzureRmVM the RM is not updated in the Information panel

### ISSUE THREAD

**Issue by ward0** [Azure/azure-powershell#3319]
### PowerShell Version

Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `

```
PSVersion                      5.1.14393.576                                                                                                                                              
PSEdition                      Desktop                                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                    
BuildVersion                   10.0.14393.576                                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                                            
WSManStackVersion              3.0                                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                                        
SerializationVersion           1.1.0.1 
```

### OS Version
10.0.14393.576

### Debug Output
The script works.

```
PS C:\Users\wardcoys> Update-AzureRmVM -ResourceGroupName $vm.RGName -VM $VMInfo

RequestId IsSuccessStatusCode StatusCode ReasonPhrase
--------- ------------------- ---------- ------------
                         True         OK OK    
```

### Script/Steps for Reproduction

Just add a disk with Add-AzureRmVMDataDisk and update it then.

In the VM you will see the newly created VHD file but the information panel doesn't know what.

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by singhkays** [comment]
@ward0 I'm not sure I understand the issue. Which information panel doesn't know what?

**Comment by ward0** [comment]
@singhkays When you update a VM V2 trough AzureRm powershell, when you do a refresh in the Azure Portal the Datadisk is not there.. It will arrive after x time.

Also it would be nice to see it in the status of the Portal, 'Adding Datadisk' like you have when you create a disk with the GUI.

**Comment by cormacpayne** [comment]
@ward0 information being propagated to the Portal (and any Portal functionality) is outside the scope of this repository. The Azure PowerShell cmdlets are responsible for making the requests to the server and returning the response. Closing.
