### ISSUE TITLE
Get-AzureRmIotHub could not convert string'routes' to dictionary key

### ISSUE THREAD

**Issue by lex88w** [Azure/azure-powershell#3325]
### Cmdlet(s)
Get-AzureRmIotHub

### PowerShell Version

     5.0.10586.117

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
BuildVersion                   10.0.10586.117
### Description
I cannot get any information about IoTHub when I running Get-AzureRmIotHub command :(
### Debug Output

Get-AzureRmIotHub : Could not convert string 'Routes' to dictionary key type
'Microsoft.Azure.Commands.Management.IotHub.Models.PSDiagnosticCategory'. Create a TypeConverter to convert from the
string to the key type object. Path '[0].properties.operationsMonitoringProperties.events.Routes', line 1, position
1590.
At line:1 char:1
+ Get-AzureRmIotHub
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmIotHub], JsonSerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.IotHub.GetAzureRmIotHub

**Comment by zhulangfly** [comment]
I also have this error!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by cormacpayne** [comment]
@rkmanda Hey Roopesh, would you mind taking a look at this issue?

**Comment by rkmanda** [comment]
This issue was fixed with  hotfix @ https://www.powershellgallery.com/packages/AzureRM.IotHub/1.0.1

**Comment by cormacpayne** [comment]
Closing issue as this was fixed in version 1.0.1 of IotHub
