### ISSUE TITLE
Mismatch of text format between location result of components, will be good if maintained same all over

### ISSUE THREAD

**Issue by Chandru10** [Azure/azure-powershell#3329]
### Cmdlet(s)
For Get-AzureRmSqlServer
**Location                 : Southeast Asia**
For Get-AzureRmVM
**Location                          : southeastasia**

### PowerShell Version
Name                           Value                                                                                                                                                 
----                           -----                                                                                                                                                 
PSVersion                      3.0                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                   
SerializationVersion           1.1.0.1                                                                                                                                               
CLRVersion                     4.0.30319.17929                                                                                                                                       
BuildVersion                   6.2.9200.16384                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0}                                                                                                                                       
PSRemotingProtocolVersion      2.2

**Comment by markcowl** [comment]
@twitchaax Request is for a universal representation of regions, while ARM is expressly designed to treat multiple representations in the same way (eastasia=EastAsia=EastAsIA = East Asia).  Should we invest in a universal utility to translate into a canonical form for presentation and canonical form for the wire?

**Comment by twitchax** [comment]
Approved, pending resources post May 2017.  Moving to backlog.

**Comment by erich-wang** [comment]
close this issue since no action for two years.
