### ISSUE TITLE
Make it possible to set vmsize of Web Role through powershell

### ISSUE THREAD

**Issue by jonasro** [Azure/azure-powershell#333]
Since we have several environments all coming from the same .csdef files (where vmsize is set) I would like to be able to adjust vmsize of a running web role just as you can with a plain VM.

**Comment by markcowl** [comment]
@jonasro Thanks for the feedback.

**Comment by singhkay** [comment]
@jonasro Can you suggest what a proposed UX looks like? Are you saying the cmdlet changes the size in the .csdef file?

**Comment by jonasro** [comment]
My usecase:
10 customers of different size all running in separate Azure deployments. 
We are using one .csdef for all deployments and have on .cscfg per customer. 
We also use the same .csdef for test and stage deployments.

Since the vmsize is set in the .csdef I would like to set the vmsize of a webrole post deployment so that i can adjust a testenvironment to the smallest vm size or can adjust a production webrole up if needed.

For a virtual machine the powershell looks like this:
Get-AzureVM –ServiceName $ServiceName –Name $Name | 
             Set-AzureVMSize $VMSize | 
             Update-AzureVM

I would like the same to be available for web roles.

**Comment by singhkay** [comment]
@jonasro Azure PowerShell as it stands today is a wrapper over the APIs. Any capability in the PS depends on the APIs that are exposed in the platform. As there is no API for this capability, we won't be able to implement this in PS.
