### ISSUE TITLE
Get-AzureRmVirtualNetwork piping issues

### ISSUE THREAD

**Issue by nyanhp** [Azure/azure-powershell#3330]
### Cmdlet(s)
Get-AzureRmVirtualNetwork

### PowerShell Version
5.1.14393.576 

### Module Version
3.3.0

### OS Version
10.0.14393.576

### Description
Piping Get-AzureRmVirtualNetwork to Select-Object leads to a PipelineStoppedException, leading scripts that filter existing ARM virtual networks and select a subset of those to fail. It does not matter if you have one or more ARM virtual networks - piping so Select-Object fails either way.

### Debug Output
DEBUG: 10:26:07 - GetAzureVirtualNetworkCommand begin processing with ParameterSet 'NoExpand'.
DEBUG: 10:26:07 - using account id ...@....com'...
DEBUG: [Common.Authentication]: Authenticating using Account: ...@....com', environment: 'AzureCloud', tenant: ...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 09:26:07:  - TokenCache: Deserialized 4 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 09:26:07: ... - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/.../
	Resource: https://management.core.windows.net/
	ClientId: ...
	CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (4 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 12/28/2016 09:26:07: ... - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 09:26:07: ... - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 12/28/2016 09:26:07: ... - TokenCache: 47.5830905066667 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 09:26:07: ... - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 09:26:07: ... - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: ...
	Refresh Token Hash: ...
	Expiration Time: 12/28/2016 10:13:42 +00:00
	User Hash: ...
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 09:26:07:  - TokenCache: Serializing token cache with 4 items.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 09:26:07: ... - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/.../
	Resource: https://management.core.windows.net/
	ClientId: ...
	CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (4 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 12/28/2016 09:26:07: ... - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 09:26:07:... - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 12/28/2016 09:26:07:... - TokenCache: 47.5830905066667 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 09:26:07: ... - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 09:26:07: ... - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: ...
	Refresh Token Hash: ...
	Expiration Time: 12/28/2016 10:13:42 +00:00
	User Hash: ...
	

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/.../providers/Microsoft.Network/virtualNetworks?api-version=2016-09-01

Headers:
x-ms-client-request-id        : 33a92d22-2807-4795-a6c0-790d126a077e
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : 6ffaf20b-0878-477b-baae-4ca416e1a558
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 14906
x-ms-correlation-request-id   : b49a7bc1-040f-4c93-97af-c2633bbe56aa
x-ms-routing-request-id       : NORTHEUROPE:20161228T092608Z:b49a7bc1-040f-4c93-97af-c2633bbe56aa
Date                          : Wed, 28 Dec 2016 09:26:07 GMT

Body:
{
  "value": [
    {
      "name": "anothernetwork",
      "id": "/subscriptions/.../resourceGroups/JhpAutomationtest/providers/Microsoft.Network/virtualNetworks/anothernetwork",
      "etag": "W/\"594aacbb-3109-40b6-ab18-cf02f7713a3c\"",
      "type": "Microsoft.Network/virtualNetworks",
      "location": "southcentralus",
      "properties": {
        "provisioningState": "Succeeded",
        "resourceGuid": "0008c7a7-13e3-4216-a061-28ed17583c03",
        "addressSpace": {
          "addressPrefixes": [
            "10.0.0.0/16"
          ]
        },
        "subnets": [
          {
            "name": "default",
            "id": "/subscriptions/.../resourceGroups/JhpAutomationtest/providers/Microsoft.Network/virtualNetworks/anothernetwork/subnets/default",
            "etag": "W/\"594aacbb-3109-40b6-ab18-cf02f7713a3c\"",
            "properties": {
              "provisioningState": "Succeeded",
              "addressPrefix": "10.0.0.0/24",
              "serviceTunnels": []
            }
          }
        ],
        "virtualNetworkPeerings": []
      }
    },
    {
      "name": "JhpAutomationtest",
      "id": "/subscriptions/.../resourceGroups/JhpAutomationtest/providers/Microsoft.Network/virtualNetworks/JhpAutomationtest",
      "etag": "W/\"50acd9ba-9ecc-4d21-a583-602359cb1fcb\"",
      "type": "Microsoft.Network/virtualNetworks",
      "location": "southcentralus",
      "properties": {
        "provisioningState": "Succeeded",
        "resourceGuid": "823d77de-5f71-4cd9-bb67-f1dcb868d7c9",
        "addressSpace": {
          "addressPrefixes": [
            "192.168.41.0/24"
          ]
        },
        "subnets": [
          {
            "name": "default",
            "id": "/subscriptions/.../resourceGroups/JhpAutomationtest/providers/Microsoft.Network/virtualNetworks/JhpAutomationtest/subnets/default",
            "etag": "W/\"50acd9ba-9ecc-4d21-a583-602359cb1fcb\"",
            "properties": {
              "provisioningState": "Succeeded",
              "addressPrefix": "192.168.41.0/24",
              "serviceTunnels": []
            }
          }
        ],
        "virtualNetworkPeerings": []
      }
    }
  ]
}

Name                   : anothernetwork
ResourceGroupName      : JhpAutomationtest
Location               : southcentralus
Id                     : /subscriptions/.../resourceGroups/JhpAutomationtest/providers/Microsoft.Network/virtualNetworks/anothernetwork
Etag                   : W/"594aacbb-3109-40b6-ab18-cf02f7713a3c"
ResourceGuid           : 0008c7a7-13e3-4216-a061-28ed17583c03
ProvisioningState      : Succeeded
Tags                   : 
AddressSpace           : {
                           "AddressPrefixes": [
                             "10.0.0.0/16"
                           ]
                         }
DhcpOptions            : null
Subnets                : [
                           {
                             "Name": "default",
                             "Etag": "W/\"594aacbb-3109-40b6-ab18-cf02f7713a3c\"",
                             "Id": "/subscriptions/.../resourceGroups/JhpAutomationtest/providers/Microsoft.Network/virtualNetworks/anothernetwork/subnets/default",
                             "AddressPrefix": "10.0.0.0/24",
                             "IpConfigurations": [],
                             "ResourceNavigationLinks": [],
                             "ProvisioningState": "Succeeded"
                           }
                         ]
VirtualNetworkPeerings : []

get-azurermvirtualnetwork : The pipeline has been stopped.
At line:1 char:1
+ get-azurermvirtualnetwork | select-object -first 1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmVirtualNetwork], PipelineStoppedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkCommand
 
DEBUG: 10:26:08 - GetAzureVirtualNetworkCommand end processing.
DEBUG: 10:26:08 - GetAzureVirtualNetworkCommand end processing.

### Script/Steps for Reproduction
Either Get-AzureRmVirtualNetwork | Select-Object -First 1
or the initial purpose of this exercise: Get-AzureRmVirtualNetwork | Where-Object {$_.AddressSpace.AddressPrefixes.Contains('192.168.41.0/24')} | Select-Object -First 1

**Comment by cormacpayne** [comment]
@nyanhp thanks for the comment! I just tried the same steps above with `Get-AzureRmSubscription` and got the same error was you. However, I did find if you changed

```powershell
Get-AzureRmSubscription | Select-Object -First 1
```

to 

```powershell
$list = Get-AzureRmSubscription
$list | Select-Object -First 1
```

it didn't throw the error (even though both commands above will return the desired object).

This is something that we will need to investigate.

**Comment by nyanhp** [comment]
@cormacpayne  Thanks, that is a viable workaround, as would be (Get-AzureRmVirtualNetwork)[0], which also works. To me it looks like Select-Object stops the pipeline successfully, but the Azure cmdlet is not able to stop the task which gets a response - but I am not an experienced developer.

**Comment by cormacpayne** [comment]
@nyanhp so here's what is happening: before PowerShell 3.0, if you were to call

```powershell
1..10 | Select-Object -First 5
```

it was found that PowerShell would process all ten items, rather than just the first five. In PowerShell 3.0, they introduced an optimization that stopped the pipeline after PowerShell processed the first five items. This is why we get the error above.

`Select-Object` has an additional switch parameter, `Wait`, that you can use that will turn off the above optimization, and will run the original command mentioned in the issue description without failing (because it won't stop the pipeline). However, this means that you will be processing all of the items rather than the first five items, so it comes with it's cons.

So you can try out the `Wait` parameter if you don't mind processing all of the items in the list, or continue using the workaround mentioned above. Let me know if you have any other questions!

Sources of information mentioned above:
http://stackoverflow.com/a/8749995
http://community.idera.com/powershell/powershell_com_featured_blogs/b/tobias/posts/cancelling-a-pipeline

**Comment by nyanhp** [comment]
Hi @cormacpayne, first of all: thanks.
I am sorry, but while that is a good explanation I feel that this is not an acceptable solution for people with more than a handful of resources. Waiting for Azure commands to complete in a scenario where many resources have to be retrieved is not really practical if you already know that you want to select the first couple of items that are coming up.
I would strongly suggest looking into something like CancellationTokens for the tasks that retrieve data from Azure. I know that this is a major change and probably not everyone just selects the first couple of items from the return values, so for me (personally) the suggested workaround with -Wait is fine.
Thanks!

**Comment by cormacpayne** [comment]
@nyanhp we revisited this issue and did a little investigation into when/why PowerShell is throwing this `PipelineStoppException`. I've opened a PR to check for this type of exception (and the scenario that it would be thrown in) and made sure that it is not written to the error stream so users do not see this exception anymore. This fix should be available in our next release!
