### ISSUE TITLE
Get-AzureRmSiteRecoveryFabric and related cmdlets fail with Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by andyjballgit** [Azure/azure-powershell#3331]
### Cmdlet(s)
Get-AzureRmSiteRecoveryFabric 
Get-AzureRmSiteRecoveryJob 
Get-AzureRmSiteRecoveryNetwork 
Get-AzureRmSiteRecoveryNetworkMapping 
Get-AzureRmSiteRecoveryPolicy 
get-AzureRMSiteRecoveryVault

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1.14986.1000   
### Module Version
3.3.0
### OS Version
10.0.14986.1000

### Description
Above cmdlets produce error below if Set-AzureRmSiteRecoveryVaultSettings hasn't been run , this is not obvious from help / documentation 

Get-AzureRmSiteRecoveryFabric : Operation failed.
ClientRequestId: 
Object reference not set to an instance of an object.
At line:1 char:1

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
PS C:\Users\andyj>     $DebugPreference = "Continue"
    Get-AzureRmSiteRecoveryFabric 
DEBUG: 11:32:29 - GetAzureRmSiteRecoveryFabric begin processing with ParameterSet 'Default'.
DEBUG: 11:32:29 - using account id 'andy.ball@cloudviewcomputing.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'andy.ball@cloudviewcomputing.com', environment: 'AzureCloud', tenant: 'b6aadacb-f43d-4489-8f9a-43a5eb10da87'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 11:32:29:  - TokenCache: Deserialized 4 items to token cache.

DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'b6aadacb-f43d-4489-8f9a-43a5eb10da87', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-22
7b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/b6aadacb-f43d-4489-8f9a-43a5eb10da87/', CorrelationId: '00000000-0000-0000-0000-0
00000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'b6aadacb-f43d-4489-8f9a-43a5eb10da87', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a25
8-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 11:32:29: bf1f3425-7f8c-49fb-a9b2-0f11deb2dd83 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/b6aadacb-f43d-4489-8f9a-43a5eb10da87/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (4 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 12/28/2016 11:32:29: bf1f3425-7f8c-49fb-a9b2-0f11deb2dd83 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 11:32:29: bf1f3425-7f8c-49fb-a9b2-0f11deb2dd83 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 12/28/2016 11:32:29: bf1f3425-7f8c-49fb-a9b2-0f11deb2dd83 - TokenCache: 51.5970861716667 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 11:32:29: bf1f3425-7f8c-49fb-a9b2-0f11deb2dd83 - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 11:32:29: bf1f3425-7f8c-49fb-a9b2-0f11deb2dd83 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: 1HYHVmP471jZZjPNkfS9UHEV1/dpbAx4urRT/WdHlNM=
	Refresh Token Hash: aw3iXGLm7hPh+jx70eutlQv/du7o+NCeYWSMQSl544A=
	Expiration Time: 12/28/2016 12:24:04 +00:00
	User Hash: rNm/2rUSSNtNzDaUD0SWneaV/BEmTUKE4W+lk8qwFFM=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/28/2016 11:32:29:  - TokenCache: Serializing token cache with 4 items.

DEBUG: [Common.Authentication]: Received token with LoginType 'LiveId', Tenant: 'b6aadacb-f43d-4489-8f9a-43a5eb10da87', UserId: 'andy.ball@cloudviewcomputing.com'
Get-AzureRmSiteRecoveryFabric : Operation failed.
ClientRequestId: 
Object reference not set to an instance of an object.
At line:2 char:5
+     Get-AzureRmSiteRecoveryFabric
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmSiteRecoveryFabric], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.SiteRecovery.GetAzureRmSiteRecoveryFabric
 
### Script/Steps for Reproduction
1. Login into Azure via Login-AzureRMAccount 
2. Type Get-AzureRmSiteRecoveryFabric and Enter

**Comment by cormacpayne** [comment]
@sriramvu Hey Sriram, would you mind taking a look at this issue?

**Comment by sriramvu** [comment]
Thanks Andy.
Will make the change and try pushing earlier.
Here, we are not checking for valid vault context and trying out to reach service.

**Comment by cormacpayne** [comment]
Fix merged in PR https://github.com/Azure/azure-powershell/pull/3360
