### ISSUE TITLE
Breaking change tool refactor

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3333]
From PR https://github.com/Azure/azure-powershell/pull/3207

- [x] [Use ParameterSets.FirstOrDefault(...)](https://github.com/Azure/azure-powershell/pull/3207/files/23e4fb441699e5bccc7d59c29d04758a9de801ee#diff-8bab777cc05bcebe15f1880208e88a24R115)
- [x] [Add ValidateRange rule](https://github.com/Azure/azure-powershell/pull/3207/files/23e4fb441699e5bccc7d59c29d04758a9de801ee#diff-dc9cad50a558816fb4c7b79cf34b2357R53)
- [x] [Remove empty constructor for TypeMetadata](https://github.com/Azure/azure-powershell/pull/3207/files/23e4fb441699e5bccc7d59c29d04758a9de801ee#diff-e14f5b90f32a0eb77b7fc4d639baa92aR41)
    - According to [this comment](http://stackoverflow.com/a/3692073), the empty constructor is no longer generated when an overloaded constructor is provided, so this constructor will need to be kept
- [x] [Split CompareTypeMetadata method into separate methods](https://github.com/Azure/azure-powershell/pull/3207/files/23e4fb441699e5bccc7d59c29d04758a9de801ee#diff-daf36aad41d90a62fcd71f000fc4c8ffR61)
- [ ] [Fix spacing](https://github.com/Azure/azure-powershell/pull/3207/files/23e4fb441699e5bccc7d59c29d04758a9de801ee#diff-daf36aad41d90a62fcd71f000fc4c8ffR127)
- [x] [Split CheckParameterType method into separate methods](https://github.com/Azure/azure-powershell/pull/3207/files/23e4fb441699e5bccc7d59c29d04758a9de801ee#diff-daf36aad41d90a62fcd71f000fc4c8ffR229)
- [x] [Split CheckOutputType into separate methods](https://github.com/Azure/azure-powershell/pull/3207/files/23e4fb441699e5bccc7d59c29d04758a9de801ee#diff-daf36aad41d90a62fcd71f000fc4c8ffR367)
- [x] [Fix [Fact()]](https://github.com/Azure/azure-powershell/pull/3207/files/23e4fb441699e5bccc7d59c29d04758a9de801ee#diff-8d51db6d3d0a26e39d93e26580efa25cR29)

**Comment by cormacpayne** [comment]
Fix in PR https://github.com/Azure/azure-powershell/pull/3356

**Comment by markcowl** [comment]
fixed.
