### ISSUE TITLE
AzureRm.Resources: ARM Policy Commands should expose a -Parameters parameter

### ISSUE THREAD

**Issue by cdituri** [Azure/azure-powershell#3336]
### Cmdlet(s)

Get-AzureRmPolicyAssignment
Get-AzureRmPolicyDefinition
New-AzureRmPolicyAssignment
New-AzureRmPolicyDefinition
Remove-AzureRmPolicyAssignment
Remove-AzureRmPolicyDefinition
Set-AzureRmPolicyAssignment
Set-AzureRmPolicyDefinition

### Module Version

Lastest

### Description

Per AzureRm.Resources Policy API version [2016-12-01](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/policy/2016-12-01/swagger/policy.json) a policy's ``policyRule`` can be parameterized with ``parameters`` (see the [PolicyDefinitionProperties](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/policy/2016-12-01/swagger/policy.json#L588))

The Powershell Cmdlets however do not expose a -Parameters parameter to leverage this new functionality.

**Comment by cdituri** [comment]
Looks like the [PolicyDefinitionProperties](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Entities/Policy/PolicyDefinitionProperties.cs#L23) class needs to be extended as well in order to support this feature request.

**Comment by markcowl** [comment]
@ravbhatnagar Can you take  a look?

**Comment by ravbhatnagar** [comment]
@cdituri  This support has not been added to PowerShell yet. This is on our backlog to be added soon.

**Comment by cdituri** [comment]
@ravbhatnagar - correct, simply wanted to raise the issue so that it could be backlogged and prioritized at whatever level is deemed appropriate. If I am able to free up some time I'll take a stab at an implementation--no guarantees this will happen however.

@ravbhatnagar @markcowl - thank you both for taking a peek at this issue and getting it into the backlog.

**Comment by cormacpayne** [comment]
@darshanhs90 any idea if we are able to support this functionality?

**Comment by kenieva** [comment]
We have full support of "-paramaters" today in more definitions and assignment PS commands.
