### ISSUE TITLE
[AzureChina] Move-AzureRmResource does not work for Microsoft.ServiceBus Provider

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#3337]
### Cmdlet(s)
Move-AzureRmResource

### PowerShell Version
5.0.10586.117

### OS Version
10.0.10586.117

### Description

Move-AzureRmResource does not work for moving ServiceBus Resource - Failure terms - ResourceGroup unavailable.

PS C:\Windows\system32> Move-AzureRmResource -DestinationResourceGroupName hidden -DestinationSubscriptionId hidden -ResourceId /subscriptions/hidden/resourceGroups/Default-ServiceBus-ChinaNorth/providers/Microsoft.ServiceBus/namespaces/hidden -Force
Move-AzureRmResource : ResourceGroupNotFound : Resource group 'Default-ServiceBus-ChinaNorth' could not be found.
At line:1 char:1
+ Move-AzureRmResource -DestinationResourceGroupName hidden ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Move-AzureRmResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : ResourceGroupNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.Mo
   veAzureResourceCommand

However, when i use, the below command the resource id shows up the **resourcegroup name**
Get-AzureRmServiceBusNamespace | ? {$_.Name -like "*hidden*"}

Name               : hidden
ResourceGroupName  :
Id                 : /subscriptions/hidden/resourceGroups/**Default-ServiceBus-ChinaNorth**/p
                     roviders/Microsoft.ServiceBus/namespaces/hidden
Location           : China North
Sku                : Microsoft.Azure.Management.ServiceBus.Models.Sku
ProvisioningState  : Succeeded
Status             : Active
CreatedAt          : 11/8/2016 8:40:17 AM
UpdatedAt          : 11/8/2016 8:40:40 AM
ServiceBusEndpoint : https://hidden.servicebus.chinacloudapi.cn:443/
Enabled            : True

### Debug Output

PS C:\Windows\system32> Move-AzureRmResource -DestinationResourceGroupName hidden -DestinationSubscriptionId hidden -ResourceId /subscriptions/hidden/resourceGroups/Default-ServiceBus-ChinaNorth/providers/Microsoft.ServiceBus/namespaces/hidden -DEBUG
PS C:\Windows\system32> $DebugPreference="Continue"
PS C:\Windows\system32> Move-AzureRmResource -DestinationResourceGroupName hidden -DestinationSubscriptionId hidden -ResourceId /subscriptions/03c67018-8f82-427b-ad8b-1104d5ef1d2e/resourceGroups/Def
ault-ServiceBus-ChinaNorth/providers/Microsoft.ServiceBus/namespaces/hidden -DEBUG
DEBUG: 1:39:55 AM - MoveAzureResourceCommand begin processing with ParameterSet '__AllParameterSets'.

/subscriptions/hidden/resourceGroups/Default-ServiceBus-ChinaNorth/providers/Microsoft.ServiceBus/namespaces/hidden

DEBUG: [Common.Authentication]: Authenticating using Account: 'hidden', environment:
'AzureChinaCloud', tenant: '3953396c-814c-4dbe-b543-ae4999978206'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/01/2017 06:40:03:  - TokenCache: Deserialized 2 items to token cache.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain:
'3953396c-814c-4dbe-b543-ae4999978206', Endpoint: 'https://login.chinacloudapi.cn/', ClientId:
'1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri:
'https://management.core.chinacloudapi.cn/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority
'https://login.chinacloudapi.cn/3953396c-814c-4dbe-b543-ae4999978206/', CorrelationId:
'00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain:
'39hidden6', AdEndpoint: 'https://login.chinacloudapi.cn/', ClientId:
'1950a2hidden5945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/01/2017 06:40:03: 7efhidden5c6 - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.chinacloudapi.cn/hidden6/
 Resource: https://management.core.chinacloudapi.cn/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (2 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 01/01/2017 06:40:03: 7ef4243e4d35c6 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/01/2017 06:40:03: 7ef42e4d35c6 - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 01/01/2017 06:40:03: 7ef4da43e4d35c6 - TokenCache: 47.8300863666667 minutes left until
token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/01/2017 06:40:03: 7efe4d35c6 - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/01/2017 06:40:03: 7ef44d35c6 - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: JqegI9a/XcgfdSODm4w4mmOH0o2PKqy2vne9kQLbmdc=
 Refresh Token Hash: nwU8eOxINVRAiiuwl7xlCxa5haZk7coa31MlWS1XyPQ=
 Expiration Time: 01/01/2017 07:27:52 +00:00
 User Hash: WEft6t6i32QwIWOaWxCARGXSEZnMzioqyDel3KEojP4=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/01/2017 06:40:03:  - TokenCache: Serializing token cache with 2 items.
DEBUG: [Common.Authentication]: Received token with LoginType 'LiveId', Tenant: '',
 UserId: ''
DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '01/01/2017 07:27:52 +00:00',
MultipleResource? 'True', Tenant: '3', UserId:
''
DEBUG: [Common.Authentication]: User info for token DisplayId: '', Name:
Pradebban Raja, IdProvider: 'https://sts.chinacloudapi.cn//', Uid:
'7d6'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '01/01/2017 07:27:52 +00:00' Comparing to
'01/01/2017 06:40:03 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:47:49.8051820'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.chinacloudapi.cn/subscriptions/hidden/resourceGroups/Default-ServiceBus-ChinaNorth/moveResources?api-version=2016-06-01

Headers:
User-Agent                    : AzurePowershell/v3.3.0.0,PSVersion/v5.0.10586.117
ParameterSetName              : __AllParameterSets
CommandName                   : Move-AzureRmResource

Body:
{
  "targetResourceGroup": "/subscriptions/hidden/resourceGroups/hidden",
  "resources": [

"/subscriptions/1d2e/resourceGroups/Default-ServiceBus-ChinaNorth/providers/Microsoft.ServiceBus/namespaces/hidden"
  ]
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-ratelimit-remaining-subscription-writes: 1186
x-ms-request-id               : a1dab6cc-54af-4dc8-bd84-c9bfa8d86493
x-ms-correlation-request-id   : a1dab6cc-54af-4dc8-bd84-c9bfa8d86493
x-ms-routing-request-id       : CHINAEAST:20170101T064008Z:a1dab6cc-54af-4dc8-bd84-c9bfa8d86493
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Sun, 01 Jan 2017 06:40:08 GMT

Body:
{
  "error": {
    "code": "ResourceGroupNotFound",
    "message": "Resource group 'Default-ServiceBus-ChinaNorth' could not be found."
  }
}

Move-AzureRmResource : ResourceGroupNotFound : Resource group '**Default-ServiceBus-ChinaNorth**' could not be found.
At line:1 char:1
+ Move-AzureRmResource -DestinationResourceGroupName hidden ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Move-AzureRmResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : ResourceGroupNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.Mo
   veAzureResourceCommand

**Comment by cormacpayne** [comment]
@ravbhatnagar Hey Gaurav, would you mind taking a look at this issue?

**Comment by Pradebban** [comment]
@cormacpayne, any updates on this one please ?

**Comment by vivsriaus** [comment]
@pradebban is the resource group under the destination subscription id? Are you trying to move this resource from one subscription to another, or within the same subscription, but across a different resource group?

**Comment by Pradebban** [comment]
@vivsriaus, i was trying to move to a different RG within the same subscription.

**Comment by vivsriaus** [comment]
@pradebban if that's the case, why are you specifying the -DestinationSubscriptionId parameter? This link has examples for moving resources within the same sub using powershell: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-move-resources

**Comment by Pradebban** [comment]
@vivsriaus , do you mean i cannot use -DestinationSubscriptionId  for moving withing the same subscription?
I dont see that there is any restrictions using this parameter for movements with the same subscription.

**Comment by vivsriaus** [comment]
If the destination sub id is the same as the source sub id, then it should work. But if you're just moving within the same sub, you don't need to specify the DestinationSubscriptionId parameter.

**Comment by Pradebban** [comment]
Sure, it was by mistake i used the parameter when trying to move inside the same subscription.
Also i checked the movemen in AzureChinaCloud and it passed. Should have been fixed during the course of this bug. 

Closing the issue.
@vivsriaus, Thanks for the quick responses.
