### ISSUE TITLE
Get-AzureRmServiceBusNamespace always return empty ResourceGroupName.

### ISSUE THREAD

**Issue by takekazuomi** [Azure/azure-powershell#3339]
### Cmdlet(s)
Get-AzureRmServiceBusNamespace 

### PowerShell Version
 5.1.14393.576

### Module Version
3.3.0

### OS Version
10.0.14393.576

### Description
Get-AzureRmServiceBusNamespace  cmdlet  always return empty ResourceGroupName.

List By Subscription and List By Resource Group REST API dosn't have  ResourceGroupName property.
https://docs.microsoft.com/en-us/rest/api/servicebus/namespaces#Namespaces_ListBySubscription
https://docs.microsoft.com/en-us/rest/api/servicebus/namespaces#Namespaces_ListByResourceGroup

Get-AzureRmServiceBusNamespace  results don't not need to have ResourceGroupName information.
I think.

### Script/Steps for Reproduction

```
$ Get-AzureRmServiceBusNamespace

Name               : kinmugisbb01
ResourceGroupName  :
Id                 : /subscriptions/xxxxxxxxxxx-d72c-4b82-b00d-6bfbd522c069/resourceGroups/kinmugisb01/providers/Microsoft.ServiceBus/namespaces/xxxxxxxxxxxx
Location           : Japan West
Sku                : Microsoft.Azure.Management.ServiceBus.Models.Sku
ProvisioningState  : Succeeded
Status             : Active
CreatedAt          : 2016/12/29 5:40:55
UpdatedAt          : 2016/12/29 5:41:20
ServiceBusEndpoint : https://kinmugisbb01.servicebus.windows.net:443/
Enabled            : True
```

**Comment by cormacpayne** [comment]
@v-Ajnava @sazeesha would you mind taking a look at this issue?

**Comment by sazeesha** [comment]
@takekazuomi: we will be removing the ResourceGroupName  from the properties. The ResourceGroupName  can be found in the Id.  We are fixing the  Sku to return the right object. 

@cormacpayne: when is the next PS release. We will check in the fix before that.

**Comment by cormacpayne** [comment]
@sazeesha code complete is January 11th and the release is January 18th

**Comment by takekazuomi** [comment]
confirmed. Thank you.
