### ISSUE TITLE
New-AzureRmServiceBusNamespace don't not support capacity option.

### ISSUE THREAD

**Issue by takekazuomi** [Azure/azure-powershell#3344]
### Cmdlet(s)
New-AzureRmServiceBusNamespace

### PowerShell Version
 5.1.14393.576

### Module Version
3.3.0

### OS Version
10.0.14393.576

### Description
New-AzureRmServiceBusNamespace don't not support capacity option.

Namespaces Create Or Update Resource Group REST API support  capacity option.
https://docs.microsoft.com/en-us/rest/api/servicebus/namespaces#Namespaces_CreateOrUpdate

also Set-AzureRmServiceBusNamespace support sku's capacity option.

**Comment by cormacpayne** [comment]
@sazeesha @v-Ajnava would you guys mind taking a look at this issue?

**Comment by sazeesha** [comment]
@takekazuomi AND @cormacpayne  ack, we will add a new parameter to update the capacity. 
Thanks 👍

**Comment by takekazuomi** [comment]
confirmed. Thank you.
