### ISSUE TITLE
New-AzureRmStorageAccount gives no errors but in Azure Portal the account has status 'Deleted'

### ISSUE THREAD

**Issue by ward0** [Azure/azure-powershell#3346]
### Cmdlet(s)
New-AzureRmStorageAccount
### PowerShell Version
5.1.14393.576

### OS Version
10.0.14393.576 

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

I posted it on stackoverflow to add pictures.
See following link pls: http://stackoverflow.com/questions/41462874/azure-storageaccount-has-status-deleted-but-i-can-add-data-disks-afterwards

Should i be worried?

**Comment by ward0** [comment]
Azure Portal is getting really crazy.. I went into lunch break.. came back.. the status deleted is gone and everything is acting normal.

**Comment by blueww** [comment]
@ward0,
This issue is not related to PowerShell, it's the server/portal behavior.
You might can write mail to <azurestoragetalk@microsoft.com> and <srp@microsoft.com> to see if they have any idea on this.
Thanks!
