### ISSUE TITLE
Remove-AzureRmSqlDatabaseAuditing has unnecessary alias

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3358]
### Cmdlet(s)

Remove-AzureRmSqlDatabaseAuditing

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

N/A

### Module Version

2.4.0

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

N/A

### Description

The cmdlet `Remove-AzureRmSqlDatabaseAuditing` has an alias that is also `Remove-AzureRmSqlDatabaseAuditing`. The alias should be removed or changed to its originally intended name.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

N/A

### Script/Steps for Reproduction

N/A

**Comment by yaakoviyun** [comment]
Send PR: https://github.com/Azure/azure-powershell/pull/3365
