### ISSUE TITLE
Get-AzureAdGroup doesn't support filter security group

### ISSUE THREAD

**Issue by yangl900** [Azure/azure-powershell#336]
Get-AzureAdGroup doesn't support filter security groups, this is required for RBAC. Role assignment principal must be a security group.

**Comment by cormacpayne** [comment]
Closing this issue as `Get-AzureADGroup` is no longer a supported cmdlet. Please feel free to try the [`Get-AzureRmADGroup`](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Resources/Commands.Resources/help/Get-AzureRmADGroup.md) cmdlet and see if the problem has been resolved.
