### ISSUE TITLE
Remove Help.xml files from source code and generate at build time from markdown help

### ISSUE THREAD

**Issue by NimishaS** [Azure/azure-powershell#3362]
### Description
Size of Help.xml files eg. `src/ResourceManager/Compute/Commands.Compute/Microsoft.Azure.Commands.Compute.dll-Help.xml` and `src/ServiceManagement/ComputeCommands.ServiceManagement/Microsoft.WindowsAzure.Commands.ServiceManagement.dll-Help.xml` has become huge, making it difficult to add/remove new contents.

We found it impossible to rebase https://github.com/Azure/azure-powershell/pull/3322 against dev branch since the conflicts are in 3000+ lines of the Help.xml file.  Is there a way to modularize these files?

**Comment by cormacpayne** [comment]
@NimishaS Hey Nimisha, we are working to try and get rid of the dll-Help.xml files from the repository, and instead have teams edit the markdown help files that currently live in the `help` folder in each RP's "commands" folder (_e.g.,_ `.../Compute/Commands.Compute/help`)

This will resolve the issue you are having and make it easier for teams to edit their help without having to commit a dll-Help.xml file with a ton of changes. Let me know if you have any other questions!

**Comment by NimishaS** [comment]
Thanks @cormacpayne , this will definitely resolve the issue that we are facing. Is there a similar `help` folder for `ServiceManagement` too? When will this come into practice?

**Comment by cormacpayne** [comment]
@NimishaS I did try to create a similar `help` folder for `ServiceManagement` as well - most of the code for this has been written, but it [throw an error](https://github.com/Azure/azure-powershell/blob/dev/tools/platyPSHelp/platyPSHelp.psm1#L52) right now until I can figure out why there's an issue when importing the modules. This is something that I will have to come back at a later time and figure out so we can have markdown help files for the existing `ServiceManagement` RPs.

**Comment by cormacpayne** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/issues/3583
