### ISSUE TITLE
DatabaseMaxSizeBytes is Int32 in Cmdlet New-AzureRmSqlDatabaseImport

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-powershell#3366]
Currently DatabaseMaxSizeBytes is Int32 in Cmdlet New-AzureRmSqlDatabaseImport, you can set max to 4GB with Int32, how can I import database which is larger than 4GB?

Another question is: while creating a new azure sql database, maxsize is an optional parameter, but in Cmdlet New-AzureRmSqlDatabaseImport it is a required parameter, does it make sense?

Thanks,

**Comment by akromm** [comment]
#3067

**Comment by zhiweiv** [comment]
Thanks a lot, akromm!

**Comment by cormacpayne** [comment]
@akromm can this issue be closed, or should it be separately tracked from issue https://github.com/Azure/azure-powershell/issues/3067 ?

**Comment by akromm** [comment]
@cormacpayne this can be closed and tracked as part of #3067

**Comment by cormacpayne** [comment]
Fix has been merged.
