### ISSUE TITLE
Get-AzureKeyVaultSecret - Getting Access Denied when serviceprincipal is used for authentication

### ISSUE THREAD

**Issue by zechariahks** [Azure/azure-powershell#3389]
### Cmdlet(s)
Get-AzureKeyVaultSecret, Add-AzureRMAccount

### PowerShell Version
5.0.10586.117

### OS Version
10.0.10586.117

### Description
Getting Access Denied when I used serviceprincipal authentication to azure. If I individual user account to access KeyVault, it is working. How will I be able to use this cmdlet with add-azureaccount -serviceprincipal authentication.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

1. Login to Azure using below command.

Add-AzureRmAccount -ServicePrincipal -CertificateThumbprint $certthumbprint -ApplicationId $applicationid -TenantId $tenantid

2. Execute below command to get the key vault
Get-AzureKeyVaultSecret -VaultName "$keyvaultname" 

Getting "Access Denied" error with the above command.

**Comment by cormacpayne** [comment]
@pomortaz Hey Pooneh, would you mind taking a look at this issue?

**Comment by pomortaz** [comment]
@zechariahks have you set access permissions on your vault for the service principal, using [Set-AzureRmKeyVaultAccessPolicy](https://docs.microsoft.com/en-us/powershell/resourcemanager/azurerm.keyvault/v2.2.0/set-azurermkeyvaultaccesspolicy)?

**Comment by zechariahks** [comment]
Hi Pooneh,

sorry for replying late. I am able to resolve this issue now. we were not executing the Set-AzureRmKeyVaultAccessPolicy command properly. we have corrected the issue and it is working now. Thank you for the help.

**Comment by LoulG** [comment]
@zechariahks : Hi, what was exactly the issue with your call to Set-AzureRmKeyVaultAccessPolicy ?

**Comment by mathieu-benoit** [comment]
Agree with @LoulG, could be great if we could have some documentation about how you used and fixed that please @zechariahks or @pomortaz. Thanks!
