### ISSUE TITLE
New-AzureRmWebApp cant find in use AppServicePlans

### ISSUE THREAD

**Issue by hbaumhardt** [Azure/azure-powershell#3390]
### Cmdlet(s)
New-AzureRmWebApp 

### PowerShell Version
5.1.14393.693

### Module Version
3.3.0

### OS Version
10.0.14393.693   

### Description
New-AzureRmWebApp with an AppServicePlan that exists and is associated with other WebApps in the Subscription and Region returns error >**Cannot find ServerFarm with name NAME-THAT-EXISTS**

Subscriptions align, Locations align, test with Get-AzureRmAppServicePlan -Name NAME-THAT-EXISTS is successful.

Using exactly the same Subscription > Resource Group > AppName > ServicePlan in portal.azure.com works fine.

### Debug Output
New-AzureRmWebApp : Cannot find ServerFarm with name NAME-THAT-EXISTS.
At line:8 char:9
+         New-AzureRmWebApp -ResourceGroupName RESOURCE-GROUP-NAME -Na ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmWebApp], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.NewAzureWebAppCmdlet

[New-AzureRmWebApp DEBUG.txt](https://github.com/Azure/azure-powershell/files/706742/New-AzureRmWebApp.DEBUG.txt)

### Script/Steps for Reproduction
$subscription = "SUBSCRIPTION-REGION"
$serviceplan = "SUBSCRIPTION-REGION-PLAN" #already used by other apps in subs & region
$region = "West US"
$resourcegroup = "GROUP-XXXUS"
$webapp = "XXXUS"
Set-AzureRmContext -SubscriptionName $subscription
New-AzureRmResourceGroup  -Name $resourcegroup  -Location $region
New-AzureRmWebApp -ResourceGroupName $resourcegroup -Name $webapp  -Location $region -AppServicePlan $serviceplan

**Comment by cormacpayne** [comment]
@LukaszStem Hey Lukasz, would you mind taking a look at this issue?

**Comment by adumont** [comment]
I had a similar issue today, where the CmdLet wouldn't find an existing Service Plan and I noticed that the ResourceGroup parameter is related to the Plan, not the WebApp.

I have opened an issue for this, https://github.com/Azure/azure-powershell/issues/3410. Maybe your issue is related ?

**Comment by panchagnula** [comment]
@hbaumhardt i am closing as we don't have a repro. Make sure that you are using the ResourceGroupName associated with the AppServicePlan. Tested on this version https://github.com/Azure/azure-powershell/releases/tag/v5.0.0-preview-AzureRM.Websites
