### ISSUE TITLE
ErrorAction preference (SilentlyContinue) does not working for Get-ServiceFabricService

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#3395]
### Cmdlet(s)
Get-ServiceFabricService

### PowerShell Version
4.0

### OS Version
6.3.9600.17400

### Description

ErrorAction preference of -SilentlyContune does not work for command Get-ServiceFabricService on failure cases.

Get-ServiceFabricService -ApplicationName "fabric:/Hidden" -ServiceName "fabric:/Hidden.Hidden" -TimeoutSec 600 -ErrorAction **SilentlyContinue**

### Debug Output

>> Get-ServiceFabricService -ApplicationName "fabric:/Hidden" -ServiceName "fabric:/Hidden/Hidden" -TimeoutSec 600 -ErrorAction SilentlyContinue -debug
VERBOSE: System.Fabric.FabricElementNotFoundException: Application not found ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071BDD
VERBOSE:    at System.Fabric.Interop.NativeClient.IFabricQueryClient7.EndGetServiceList2(IFabricAsyncOperationContext context)
VERBOSE:    at System.Fabric.FabricClient.QueryClient.GetServiceListAsyncEndWrapper(IFabricAsyncOperationContext context)
VERBOSE:    at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
VERBOSE:    --- End of inner exception stack trace ---
**Get-ServiceFabricService : Application not found**
At line:1 char:1
+ Get-ServiceFabricService -ApplicationName "fabric:/Hidden" -ServiceName "fa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Servi...usterConnection:ClusterConnection) [Get-ServiceFabricService], FabricElementNotFoundException
    + FullyQualifiedErrorId : GetServiceErrorId,Microsoft.ServiceFabric.Powershell.GetService

### Script/Steps for Reproduction

1. Connect to Service Fabric Cluster
2. Run the below command when Application is not deployed yet.
Get-ServiceFabricService -ApplicationName "fabric:/Hidden" -ServiceName "fabric:/Hidden.Hidden" -TimeoutSec 600 -ErrorAction SilentlyContinue

Thanks,
Pradebban Raja

**Comment by cormacpayne** [comment]
@Pradebban closing this issue since this cmdlet is not owned by Azure PowerShell

However, looking at the [ServiceFrabci cmdlet list](https://docs.microsoft.com/en-us/powershell/servicefabric/vlatest/servicefabric), I believe @oanapl may be able to help, or at least point you at the first place to post this question

**Comment by oanapl** [comment]
You can start a thread on https://github.com/Azure/service-fabric-issues

**Comment by Pradebban** [comment]
@oanapl, I understand the changes in area path, however is there no provision to change the path from AzurePowershell to ServiceFabric instead of closing this issue. Just curious ?!
