### ISSUE TITLE
Export-AzureVM – wrong error message when using a path that does not exist

### ISSUE THREAD

**Issue by rafamarrara** [Azure/azure-powershell#3397]
### Cmdlet(s)
Export-AzureVM

### PowerShell Version
PSVersion: 5.1.14393.693

### Module Version
PS C:\> Get-Command Export-AzureVM

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Export-AzureVM                                     3.3.0      Azure

### OS Version
BuildVersion: 10.0.14393.693

### Description
Export-AzureVM – wrong error message when using a path that does not exist

If you try to use an inexistent path on the parameter -path the error message will present this error:
**Export-AzureVM : Could not read properties for virtual machine: {0}. It may still be provisioning.**

The exception shows the following error:
**System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Temp\inexistentfolder\test.xml'.** 

I believe it should be informing that the path does not exist instead of informing that the VM may still be provisioning.

### Debug Output

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
x-ms-servedbyregion           : ussouth3
x-ms-request-id               : 44159a1002f87a3e82fbc93ecb91443c
Cache-Control                 : no-cache
Date                          : Tue, 17 Jan 2017 20:34:02 GMT
Server                        : 1.0.6198.473,(rd_rdfe_stable.170105-1707),Microsoft-HTTPAPI/2.0

Body:
<Operation xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <ID>79c67ab6-20e6-303c-8345-4adf72dc150f</ID>
  <Status>Succeeded</Status>
  <HttpStatusCode>200</HttpStatusCode>
</Operation>

Export-AzureVM : Could not read properties for virtual machine: MACPreserv01. It may still be provisioning.
At line:1 char:1
+ Export-AzureVM -ServiceName MACPreserv -Name MACPreserv01 -Path C:\Te ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Export-AzureVM], ApplicationException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.ExportAzureVMCommand

DEBUG: AzureQoSEvent: CommandName - Export-AzureVM; IsSuccess - False; Duration - 00:00:02.2390066; Exception - System.ApplicationException: Could
not read properties for virtual machine: MACPreserv01. It may still be provisioning. **---> System.IO.DirectoryNotFoundException: Could not find a part
 of the path 'C:\Temp\inexistentfolder\test.xml'.**
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize,
FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String
msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at Microsoft.WindowsAzure.Commands.ServiceManagement.Helpers.PersistentVMHelper.SaveStateToFile(PersistentVM role, String filePath)
   at Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.ExportAzureVMCommand.ExecuteCommand()
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.ExportAzureVMCommand.ExecuteCommand()
   at Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.IaaSDeploymentManagementCmdletBase.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 2:34:05 PM - ExportAzureVMCommand end processing.
DEBUG: 2:34:05 PM - ExportAzureVMCommand end processing.

### Script/Steps for Reproduction

Export-AzureVM -ServiceName CloudServiceName -Name VMName -Path C:\Temp\inexistentfolder\test.xml

**Comment by cormacpayne** [comment]
@hyonholee Hey Hyonho, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
