### ISSUE TITLE
Get-AzureRMAutomationAccount not returning initialised properties

### ISSUE THREAD

**Issue by dacarab** [Azure/azure-powershell#3398]
### Cmdlet(s)
Get-AzureRMAutomationAccount
### PowerShell Version
PSVersion                      5.1.15007.1000                                                                               

### Module Version
AzureRM.Automation 2.4.0

### OS Version
BuildVersion                   10.0.15007.1000 

### Description
Get-AzureRMAutomationAccount , Get-AzureRMAutomationAccount -ResourceGroupName _ResourceGroup_ both return objects without all properties initialised, specifically _Plan_ and _Tags_

I assume this is related to #3044. I appreciate this may be by design - but have to concur with the point made in that issue thread, this is not very user friendly. Also for the tags to not  return is particularly troublesome. In my instance, I'm checking on tags to signify whether a function should be allowed to modify an automation account or not.

Specifying the -Name parameter in addition to -ResourceGroupName will initialise these properties - but when run with the -Name parameter, this will write a non-terminating error if the named account does not exist - which can adds extra hoops to jump through for Pester tests, etc.

Cheers

**Comment by cormacpayne** [comment]
@safeermohammed  @Bpoe Hey Safeer and Brandon, would you mind taking a look at this issue?

**Comment by safeermohammed** [comment]
Hi @dacarab, We are still looking into this issue. Meanwhile can you try the below workarounds if it meets your scenario?

Options1: Use Get-AzureRmResource cmdlet, this would return tags
Options2: As mentioned in  issue #3044,  pipe the output to get all properties
Get-AzureRmAutomationAccount | Get-AzureRmAutomationAccount

**Comment by andyw248** [comment]
Triaged: Workaround provided. Closing.
