### ISSUE TITLE
Set-AzureWebsite doesn't update ConnectionStrings

### ISSUE THREAD

**Issue by rickrain** [Azure/azure-powershell#340]
$website = Get-AzureWebsite $websiteName -slot $websiteSlot
$connectionStrings = $website.ConnectionStrings

$result = $connectionStrings.Remove(($connectionStrings | Where-Object {$_.Name -eq $connectionStringName}))

Set-AzureWebsite $websiteName -slot $websiteSlot -ConnectionStrings $connectionStrings

Reference:
http://stackoverflow.com/questions/29648327/cannot-delete-all-azure-website-connection-strings

**Comment by NaveenGoli** [comment]
I will investigate

Thanks
Naveen
________________________________

**Comment by martincostello** [comment]
Any updates on whether this is definitely a bug?

**Comment by NaveenGoli** [comment]
Sorry, I have been OOF and didn't get a  chance to debug this.

Thanks
Naveen
________________________________

**Comment by winperec** [comment]
Any updates on this?

**Comment by martincostello** [comment]
Any progress on this issue?

**Comment by bspunie** [comment]
Can we please have an update on this?

**Comment by nallurisrinu** [comment]
$connStrings =  @{ AzureWebJobsDashboard = @{ Type = "Custom"; Value = $AzureWebJobsDashboard };
                   AzureWebJobsStorage = @{ Type = "Custom"; Value = $AzureWebJobsStorage }};

Set-AzureRMWebApp -Name $webServiceName -ResourceGroupName $rgName -ConnectionStrings $connStrings

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."

**Comment by mganeshphani** [comment]
Just for the sake of people who reach this thread via Google/Bing .. looks like nallurisrinu's suggestion is working out here...

$connStrings = @{ AzureWebJobsDashboard = @{ Type = "Custom"; Value = $AzureWebJobsDashboard };
AzureWebJobsStorage = @{ Type = "Custom"; Value = $AzureWebJobsStorage }};
Set-AzureRMWebApp -Name $webServiceName -ResourceGroupName $rgName -ConnectionStrings $connStrings

**Comment by umaknow-jeanluc** [comment]
Also for people searching for this error :

> Cannot validate argument on parameter 'ConnectionStrings'. Connection string type must be specified.

The Type value in the HashTable must be the string, explicitly, with **.ToString()**.

```
$connStringsList = $webApp.SiteConfig.ConnectionStrings
$hashItems = New-Object System.Collections.HashTable
ForEach ($keyValuePair in $connStringsList) {
    $setting =  @{Type=$keyValuePair.Type.ToString();Value=$keyValuePair.ConnectionString.ToString()}
    $hashItems.Add($keyValuePair.Name,$setting);
}
```

**Comment by xaviermignot** [comment]
@umaknow-jeanluc thanks a lot for your brilliant comment, you saved my day \o/
