### ISSUE TITLE
Shared Access Policy's Needed

### ISSUE THREAD

**Issue by ronbok** [Azure/azure-powershell#341]
There does not seem to be an ‘EventHub’ object to set the Shared Access Policy on an Event Hub??  
![eventhubsap](https://cloud.githubusercontent.com/assets/7467308/7180361/fdf36d18-e40e-11e4-9046-a31dd625aa0c.png)

**Comment by damienpontifex** [comment]
:+1:

**Comment by ammaroff** [comment]
This will resolve the problem till they implement it
```
$EventHubDescription = New-Object -TypeName Microsoft.ServiceBus.Messaging.EventHubDescription -ArgumentList $Path
$EventHubDescription.PartitionCount = $PartitionCount
$EventHubDescription.MessageRetentionInDays = $MessageRetentionInDays

$SharedAccessPolicyName = "your-policy-name"
$Permissions = [Microsoft.ServiceBus.Messaging.AccessRights[]]([Microsoft.ServiceBus.Messaging.AccessRights]::Manage,[Microsoft.ServiceBus.Messaging.AccessRights]::Listen,[Microsoft.ServiceBus.Messaging.AccessRights]::Send)
$SharedAccessAuthorizationRule=new-object Microsoft.ServiceBus.Messaging.SharedAccessAuthorizationRule($SharedAccessPolicyName,$Permissions)

$EventHubDescription.Authorization.Add($SharedAccessAuthorizationRule);
$NamespaceManager.CreateEventHubIfNotExists($EventHubDescription);
```

**Comment by Pradebban** [comment]
This does not work! Gives the below error,
 Cannot find an overload for "Add" and the argument count: "1".

**Comment by ammaroff** [comment]
@Pradebban 
This because you are using old version of Microsoft.ServiceBus.dll

make sure that you've loaded the latest version of Microsoft.ServiceBus.dll 2.7.5
https://www.nuget.org/packages/WindowsAzure.ServiceBus

```
$assembly =   get-item -path  "path/to/latest/version/Microsoft.ServiceBus.dll"
Add-Type -Path $assembly.FullName
```

and you've to notice that Authorization.Add is accepting 1 parameter:
https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.authorizationrules.add.aspx

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
