### ISSUE TITLE
New-AzureRmWebApp forces the webapp to be attached to the Plan's resource group

### ISSUE THREAD

**Issue by adumont** [Azure/azure-powershell#3410]
### Cmdlet(s)

New-AzureRmWebApp

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34209
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

### Module Version
PS C:\> (Get-Module AzureRM.Websites).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
1      1      0      -1

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

BuildVersion                   6.3.9600.16406

### Description

In the Azure Portal, one can create a WebApp in any Resource Group, while deploying it in a Plan which may belong to a diferent Resource Group. The ResourceGroup parameter of the New-AzureRmWebApp CmdLet is ambiguous, and forces the webapp to be created in the same Resource Group as the Service Plan.

This behaviour isn't consistent with the flexibility offered in the Azure Portal.

Also the documentation isn't clear about the ResourceGroup parameter.

IMHO, the CmdLet should have two ResourceGroup pamameters, one related to the destination App Service Plan, and one specifying the destination Resource Group where the created WebApp should be attached,

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

```
PS C:\> New-AzureRmResourceGroup RG_AlexIssueTestPlan -Location "North Europe"

ResourceGroupName : RG_AlexIssueTestPlan
Location          : northeurope
ProvisioningState : Succeeded
Tags              :
ResourceId        : /subscriptions/3faa2563-452f-435a-b611-6daffc5bb978/resourceGroups/RG_AlexIssueTestPlan

```

```
PS C:\> New-AzureRmAppServicePlan -Name AlexIssueTestPlan -Location "North Europe" -ResourceGroupName RG_AlexIssueTestPlan -Tier Standard -WorkerSize Small

Sku                       : Microsoft.Azure.Management.WebSites.Models.SkuDescription
ServerFarmWithRichSkuName : AlexIssueTestPlan
WorkerTierName            :
Status                    : Ready
Subscription              : 3faa2563-452f-435a-b611-6daffc5bb978
AdminSiteName             :
HostingEnvironmentProfile :
MaximumNumberOfWorkers    : 10
GeoRegion                 : North Europe
PerSiteScaling            : False
NumberOfSites             : 0
ResourceGroup             : RG_AlexIssueTestPlan
Id                        : /subscriptions/3faa2563-452f-435a-b611-6daffc5bb978/resourceGroups/RG_AlexIssueTestPlan/pro
                            viders/Microsoft.Web/serverfarms/AlexIssueTestPlan
Name                      : AlexIssueTestPlan
Location                  : North Europe
Type                      : Microsoft.Web/serverfarms
Tags                      :

```
I create a new RG for my WebApp:

```
PS C:\>  New-AzureRmResourceGroup RG_AlexIssueTestWebApp -Location "North Europe"

ResourceGroupName : RG_AlexIssueTestWebApp
Location          : northeurope
ProvisioningState : Succeeded
Tags              :
ResourceId        : /subscriptions/3faa2563-452f-435a-b611-6daffc5bb978/resourceGroups/RG_AlexIssueTestWebApp

```

Now I want to create a new WebApp, , in the new Plan AlexIssueTestPlan. For the ResourceGroupName parameter I specify the newly created RG_AlexIssueTestWebApp resource group, where I want to create the WebApp:

```
PS C:\>  New-AzureRmWebApp -Name AlexIssueTestWebApp -AppServicePlan AlexIssueTestPlan -ResourceGroupName RG_AlexIssueTestWebApp -Location "North Europe"

New-AzureRmWebApp : Cannot find ServerFarm with name AlexIssueTestPlan.At line:1 char:1
+ New-AzureRmWebApp -Name AlexIssueTestWebApp -AppServicePlan AlexIssueTestPlan -R ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmWebApp], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.NewAzureWebAppCmdlet

```    
    
Error shows that the ResourceGroupName parameter is related to the App Service Plan, not the WebApp to be created. So there's no way to specify in which Resource Group the WebApp to be created will be attached.

I now rerun the command, this time using the Plan's resource group as ResourceGroup parameter. This time it completes:

```
PS C:\> New-AzureRmWebApp -Name AlexIssueTestWebApp -AppServicePlan AlexIssueTestPlan -ResourceGroupName RG_AlexIssueTes
tPlan -Location "North Europe"


SiteName                  : AlexIssueTestWebApp
State                     : Running
HostNames                 : {alexissuetestwebapp.azurewebsites.net}
RepositorySiteName        : AlexIssueTestWebApp
UsageState                : Normal
Enabled                   : True
EnabledHostNames          : {alexissuetestwebapp.azurewebsites.net, alexissuetestwebapp.scm.azurewebsites.net}
AvailabilityState         : Normal
HostNameSslStates         : {alexissuetestwebapp.azurewebsites.net, alexissuetestwebapp.scm.azurewebsites.net}
ServerFarmId              : /subscriptions/3faa2563-452f-435a-b611-6daffc5bb978/resourceGroups/RG_AlexIssueTestPlan/pro                            viders/Microsoft.Web/serverfarms/AlexIssueTestPlan
LastModifiedTimeUtc       : 20/01/2017 17:47:43
SiteConfig                : Microsoft.Azure.Management.WebSites.Models.SiteConfig
TrafficManagerHostNames   :
PremiumAppDeployed        :
ScmSiteAlsoStopped        : False
TargetSwapSlot            :
HostingEnvironmentProfile :
MicroService              : WebSites
GatewaySiteName           :
ClientAffinityEnabled     : True
ClientCertEnabled         : False
HostNamesDisabled         : False
OutboundIpAddresses       : 52.169.78.89,52.169.72.202,52.169.79.20,52.169.74.117
ContainerSize             : 0
MaxNumberOfWorkers        :
CloningInfo               :
ResourceGroup             : RG_AlexIssueTestPlan
IsDefaultContainer        :
DefaultHostName           : alexissuetestwebapp.azurewebsites.net
Id                        : /subscriptions/3faa2563-452f-435a-b611-6daffc5bb978/resourceGroups/RG_AlexIssueTestPlan/pro                            viders/Microsoft.Web/sites/AlexIssueTestWebApp
Name                      : AlexIssueTestWebApp
Location                  : North Europe
Type                      : Microsoft.Web/sites
Tags                      :

```

As the output shows, the resulting WebApp is created in the Service Plan's resource group (RG_AlexIssueTestPlan).

**Comment by markcowl** [comment]
@akurmi @Nking92 Can you take a look?

**Comment by philhack** [comment]
@akurmi @Nking92  I'm encountering the exact same issue. Are you able to investigate this?  Thanks.

**Comment by Nking92** [comment]
We just updated our Websites SDK, so I'll be working on Powershell very soon. I'll Look into this issue

**Comment by philhack** [comment]
@Nking92 have you had any luck with resolving this bug in Powershell?

**Comment by mathieu-benoit** [comment]
Hi @Nking92 and @markcowl, any update on that? Any luck this bug is resolved in PowerShell? Thanks!

**Comment by ankhuve** [comment]
I'm having the same problem, any update to the situation?
At first, I tried using the "Change app service plan" functionality in Azure, but it's not listing the service plan I want, so I'm trying to use the CLI to change the app service plan of a web app to one located in another resource group. Currently getting `Set-AzureRmWebApp : Cannot find ServerFarm with name APP_SERVICE_PLAN_NAME`.

@panchagnula Any ideas?

**Comment by adumont** [comment]
@ankhuve You will only be able to move a webapp to a Destination App Service Plan if and only if the Destination App Service Plan is in the same Resource Group as the Origin App Service Plan (where the WebApp is currently deployed).

So first rule of managing WebApps: place all your Service Plans in a unique resource group "RG_ServicePlans" and there you go: you'll be able to move WebApps between all your plans. Hurray WebApps mobility :D

**Comment by ankhuve** [comment]
@adumont The weird thing is when I try to use the Azure "Change app service plan" functionality, I get suggestions for other app service plans in different resource groups than the app I'm trying to move.

After doing more digging into this, it seems my web app and my destination app service plan are in different "webspaces", and that is probably what is currently limiting my from moving the web app. I belive resource groups are no longer the limitation, but webspaces still are. 

[According to this thread](https://social.msdn.microsoft.com/Forums/azure/en-US/341e8fd0-9c43-4063-82a7-a219dd765d88/no-app-service-plans-found?forum=windowsazurewebsitespreview#c5d3c690-4d2b-4f68-90c4-688638a24710) [_October 18, 2016_],  "Unfortunately you can't get around the resource group name and webspace name limitation.  Ideally sites shouldn't be tied to resource groups in any way but that's a current limitation we have for now that won't change any time soon."

**Comment by ahmedelnably** [comment]
To achieve what you want, you need to pass the App Service plan as a resource ID

use: 
Get-AzureRmAppServicePlan -name AlexIssueTestPlan 

Then use the ServerFarmId that is being returned as the -AppServicePlan parameter in New-AzureRmWebApp
