### ISSUE TITLE
Get-AzureRmRoleAssignment with ResourceGroupName parameter gives wrong output

### ISSUE THREAD

**Issue by olandese** [Azure/azure-powershell#3414]
### Cmdlet(s)

Get-AzureRmRoleAssignment

### PowerShell Version
5.1.14393.693

### Module Version
3.5.0

### OS Version
10.0.14393.693

### Description
In my subscription I have to following Resource Groups:

Test
Test1
Test2
TestFool

And to this Resource Groups a principal has the Owner Role.

Calling the Get-AzureRmRoleAssignment with the following parameters: 
- ServicePrincipalName
- RoleDefinitionName
- ResourceGroupName

Like: 

Get-AzureRmRoleAssignment -ServicePrincipalName the_principalclient_id -RoleDefinitionName owner -ResourceGroupName Test1

### Debug Output
Calling the cmdlet with Test1 gives me the output of the Resource Group Test and not Test1, not only Test1

### Script/Steps for Reproduction
Create to following Resource Groups:

Test
Test1
Test2
TestFool

Assign a Service Principal the role Owner to this groups.

And call the cmdlet as : 

Get-AzureRmRoleAssignment -ServicePrincipalName <guid> -RoleDefinitionName owner -ResourceGroupName Test1

#### Output:

The Role assignment for Test1 and Test

#### Expected:

The Role assignment for only Test1

**Comment by markcowl** [comment]
@shuagarw Looks like this might be an issue with parameter sets, please take a look.

@olandese What happens when you specify only the service principal name and resource group name?  I *think* the intention of the cmdlet is to allow listing by rg + spn or rg + rolename, but not rg + spn +rolename

**Comment by shuagarw** [comment]
@RbacAsk for FYI @olandese Since you are specifying -ServicePrincipalName  param but not providing a value this might be behaving erratically. This looks like a bug because it should complain about the value not provided. 
Apart from that, if you don't need to filter on service principal name, skip that param altogether. And just specify ResourceGroupName as 'Test1' and 'RoleDefinitionName' as Owner. Let me know if this gives a wrong output then also.

**Comment by olandese** [comment]
@shuagarw sorry, my example was missing the parameter for the principal. I am actually calling the cmdlet also with the principal value.
So, calling the cmdlet with the following parameters (and values):
 - ServicePrincipalName
 - RoleDefinitionName
 - ResourceGroupName

I am expecting to get ONLY the result for the speficied ResourceGroup, Principal and RoleDefinition

**Comment by olandese** [comment]
@markcowl calling the cmdlet as: 

Get-AzureRmRoleAssignment -ServicePrincipalName 4ff23b35-2570-483a-b4d2-d446ff0703a6 -RoleDefinitionName owner -ResourceGroupName Test1

Gives exactly the same result as: 

Get-AzureRmRoleAssignment -ServicePrincipalName 4ff23b35-2570-483a-b4d2-d446ff0703a6 -ResourceGroupName Test1

Result:

RoleAssignments for: 

- Test1
- Test 

Calling the cmdlet for Test3 like: 
Get-AzureRmRoleAssignment -ServicePrincipalName 4ff23b35-2570-483a-b4d2-d446ff0703a6 -RoleDefinitionName owner -ResourceGroupName Test3

RoleAssignments for: 
- Test (not Test3!) 

And calling the cmld with the other resourceGroups give also odd behavior. 

Just to give more insight, using PowerShell ISE I am using the ResourceGroupWithSPNParameterSet parameter set

**Comment by Blackbaud-ShaydeNofziger** [comment]
Hello, I'm experiencing the same issue when calling `Get-AzureRmRoleAssignment` with the `-ObjectId` and `-RoleDefinitionName` param specifying a Custom created role.

Running `Get-AzureRmRoleAssignment` with just `ObjectId` correctly returns a collection of all RoleAssignments, however the `RoleDefinitionName` value is blank.

Examples with output:
```powershell
PS> Get-AzureRmRoleDefinition -Name 'DevOpsAdministrator'

Name             : DevOpsAdministrator
Id               : 25bc988a-39dd-4a89-8726-0a3b600633b0
IsCustom         : True
Description      : FAKE ROLE DESCRIPTION
Actions          : {Microsoft.KeyVault/*}
NotActions       : {}
AssignableScopes : {/subscriptions/FAKE-SUB-ID}

PS> Get-AzureRmRoleAssignment -ObjectId $userObjId

RoleAssignmentId   : REDACTED
Scope              : REDACTED
DisplayName        : REDACTED
SignInName         : REDACTED
RoleDefinitionName :
RoleDefinitionId   : 25bc988a-39dd-4a89-8726-0a3b600633b0
ObjectId           : $userObjId
ObjectType         : User


PS> Get-AzureRmRoleAssignment -ObjectId $userObjId -RoleDefinitionName 'DevOpsAdministrator'

Get-AzureRmRoleAssignment : Object reference not set to an instance of an object.
At line:1 char:6
+ $x = Get-AzureRmRoleAssignment -ObjectId 644aaeb2-5181-4380-bd18-6973 ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmRoleAssignment], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand

```

Note that the RoleDefinitionId matches the Id of the DevOpsAdministrator role, however its value doesn't get set on RoleDefinitionName. Hope this extra info is useful.

**Comment by RBACAsk** [comment]
This Issue was fixed .
The new powershell release should have that fix, it can be found here https://github.com/Azure/azure-powershell/releases/tag/v5.1.1-December2017.

**Comment by cormacpayne** [comment]
Closing as this issue appears to have been fixed.
