### ISSUE TITLE
New-AzureResourceGroup lower-casing first letter of AppSettings/ConnectionStrings when creating website

### ISSUE THREAD

**Issue by AlanParr** [Azure/azure-powershell#342]
When using my own .json template file to create websites with preset AppSettings and ConnectionStrings,the first or in some cases first and second letters are getting lower-cased when they are created in Azure.

Examples ([intemplate] -> [inazure]):
* SiteAddress -> siteAddress
* Project -> project
* SCM_BUILD_ARGS -> scM_BUILD_ARGS

This is using apiVersion 2014-11-01 with the most recent cmdlets.

I can provide a simplified script for reproduction if required.

**Comment by vivsriaus** [comment]
@AlanParr Do you mind providing us a sample script to reproduce the issue?

**Comment by vivsriaus** [comment]
@AlanParr We took a look at this. This is a side effect of json serialization logic, which is by design.

**Comment by AlanParr** [comment]
@vivsriaus Sorry for taking so long to reply to your last statements. The only reason the lower casing causes me a problem is because I have a Powershell script that I use to update settings. This fails changing the site settings due to the casing mismatch, example below:

Add-AzureAccount

$sites = Get-AzureWebsite | ?{$_.Name -match "<site search string>"}

foreach($site in $sites) {
    Write-Host "Retrieving site" $site.Name

    $fullSite = Get-AzureWebsite $site.Name
    $settings = $fullSite | Select-Object AppSettings

    $settings.AppSettings.Set_Item("Project","myproject")

    Write-Host "  Updating Settings for" $site.Name
    Set-AzureWebsite -Name $fullSite.Name -AppSettings $settings.AppSettings
}

This will fail if the setting Project has been lower-cased to project. Is it feasible to make the changing of settings case-insensitive? You're not allowed duplicate keys anyway so I don't think this would break anyone, but it would make the process more fault tolerant for when this happens, as I am surely not the only one affected...
