### ISSUE TITLE
Import-Module step in the Azure modules is clogging up the logs in Azure Automation

### ISSUE THREAD

**Issue by AWahlqvist** [Azure/azure-powershell#3426]
### Cmdlet(s)
[Module manifests](https://github.com/Azure/azure-powershell/blob/2eaf6175bc2533b83689120dc7f595ff0bdf8001/tools/UpdateModules.ps1#L33)

### PowerShell Version
Version 5 and later

### Module Version
At least 2.3 and forward

### OS Version
Windows/Azure Automation

### Description
When Azure (non-RM) module is imported, the .psm1 file is loading the Azure.Storage module since it is dependent on that module.

For all the AzureRM-modules, they are loading the AzureRM.Profile module.

I see why this is, and maybe this cannot be called a bug, but the problem with this is that it really messes up the verbose stream, especially when running workflow runbooks since all the PowerShell cmdlets are more or less running in a new context and are therefor importing the module again and again.

The easiest fix for this is to just add -"Verbose:$false" [to the Import-Module steps](https://github.com/Azure/azure-powershell/blob/2eaf6175bc2533b83689120dc7f595ff0bdf8001/tools/UpdateModules.ps1#L33), but I can see why this might not be the perfect solution either, after all, I guess verbose is verbose :-)

But it's at least what we're doing now to make our runbook logs readable. Happy to hear your thoughts about this.

### Debug Output
Sample log output:
![image](https://cloud.githubusercontent.com/assets/5821559/22327414/5d130200-e3b7-11e6-90cc-2f7725080276.png)

### Script/Steps for Reproduction
Download Azure-modules through PowerShell Gallery, zip+upload to Azure Automation, run any command that requires loading of the module.

**Comment by cormacpayne** [comment]
@twitchax @markcowl can you take a look?

**Comment by cormacpayne** [comment]
@twitchax @AWahlqvist Aaron please setup a meeting to discuss current issues with the Azure Automation team

**Comment by markcowl** [comment]
Closing as no follow up, please reopen if this issue recurs.

**Comment by AWahlqvist** [comment]
Yes, this issue still occurs as far as I know.

I'm sorry if I failed to respond in any way. What do you need more from me?

**Comment by twitchax** [comment]
@AWahlqvist, can we get together for a meeting?

**Comment by AWahlqvist** [comment]
Sure! What time zone are you in? I'm at GMT+2/CEST. I have my e-mail on my github profile if you want to arrange the meeting that way.  Thanks for taking the time!

**Comment by twitchax** [comment]
Hi @AWahlqvist, on second thought, let me sync with the Automation team first.

**Comment by AWahlqvist** [comment]
Sounds good, thanks! Please note that this issue is not unique for Azure Automation though, the same thing happens locally as well. But the problem is bigger when you run the cmdlets in workflows/parallel-iterations since the module(s) are loaded multiple times.

**Comment by jrouzies-fr** [comment]
Old post, but this issue is still there few years later ...

Even specifying the "-Verbose $false | Out-Null", which works perfectly fine on Local PowerShell, is completely ignored by Azure Runbook.

Write-Output is unusable because it cannot be used in functions.

Please Microsoft, support the Write-Information already.
