### ISSUE TITLE
More complete and detailed error (exception) messages

### ISSUE THREAD

**Issue by Bartolomeus-649** [Azure/azure-powershell#3427]
_All versions, all platforms, all OS_

Anytime you get an error message or an Exception you should get ALL the available error information.

It seem that today only the `<Code>` and `<Message>` tags from the respons from the REST API is included in the Exception you get when executing a cmd-let.

Here is an example of a response to the PUT REST API call for creating a Directory in Azure Storage Files.
```
<?xml version="1.0" encoding="utf-8"?>
<Error>
    <Code>AuthenticationFailed</Code>
    <Message>
        Server failed to authenticate the request.
        Make sure the value of Authorization header is formed correctly including the signature.
        RequestId:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
        Time:2017-01-26T11:57:49.8081343Z
    </Message>
    <AuthenticationErrorDetail>
         Request date header too old: 'Thu, 26 Jan 2017 10:57:53 GMT'
     </AuthenticationErrorDetail>
</Error>
```

As you can see, the information provided in the `<AuthenticationErrorDetail>` tag is essential to understand and actually solve the problem. Without it, you are kind of lost.

All "ErrorDetail" information needs to be included in the Exception you get in PowerShell. So this is not only applicable for `AuthenticationErrorDetail`, but any and all other Error Details, no matter what they are called.

Perhaps, even include the raw REST response as a data-item in the exception, that way if something is added or changed in the future, then it will at least be there in its raw form and accessible/available to the PowerShell environment.

**Comment by markcowl** [comment]
@Bartolomeus-649 We have a solution for this scheduled for the June release here: #3648  This was just checked in, so closing.
