### ISSUE TITLE
Refactor Microsoft.Azure.Commands.Common.Authentication

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3429]
### Description
Refactor common.authentication to totally abstract ADAL from all cmdlet implementations (modulo KeyVault)
- [ ] Determine the cost of providing ```Invoke-AzureRmRestMethod``` cmdlet that can make authenticated http calls using the current authentication context.  Write an external specification fo the cmdlet.
- [ ] Determine the impact of removing the direct ADAL dependency from KeyVault.  Work with KeyVault team on a schedule for doing this, and lock down KeyVault release until this is completed.
- [ ] Split Interfaces for ARM versus Hyak Authentication and Client factories
- [ ] Redesign Context to include an extensible dictionary and remove TokenCache abstraction; remove TokenCache abstraction from ARM authentication factory interfaces
- [ ] Fix test issues in cmdlets using the new interfaces

**Comment by aelij** [comment]
I'm not sure if this is related to this issue, but it would be great if you could also add support for ADAL's `AcquireDeviceCodeAsync` (i.e. login using http://aka.ms/devicelogin, like the xplat CLI offers). It has several advantages (for MSAs): it's usable in remote sessions and you can utilize existing browser sessions and password managers.

**Comment by markcowl** [comment]
Completed
