### ISSUE TITLE
Use common Storage libraries (Storage and Storage.Management) in non-storage cmdlets

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3430]
- [ ] Use the Storage and Storage.Management common libraries for all projects that previously relied on WindowsAzure.Storage or other Storage SDK references
- [ ] Make sure these changes work for NetCore projects

**Comment by MiYanni** [comment]
Created a branch that cleans up references. Boiled down to these projects in ResourceManager that actually use `WindowsAzure.Storage`:
![image](https://user-images.githubusercontent.com/17788297/35836562-b6e2f0fa-0a95-11e8-9b31-9ad6a218fa12.png)

**Comment by MiYanni** [comment]
@praries880 has made `Management.Storage`. It isn't used for every project, so this needs to be updated (especially in NetCore).

**Comment by MiYanni** [comment]
Storage management plane is handled here: https://github.com/Azure/azure-powershell/issues/5365
Storage dataplane is handled here: https://github.com/Azure/azure-powershell/issues/7100
