### ISSUE TITLE
Setting StorageKeyType to Secondary in Set-AzureRmSqlServerAuditingPolicy doesn't work

### ISSUE THREAD

**Issue by webbermt** [Azure/azure-powershell#3442]
### Cmdlet(s)
Set-AzureRmSqlServerAuditingPolicy

### PowerShell Version
5.1.14393.693

### Module Version
2.5.0      AzureRM.profile
2.5.0      AzureRM.Sql

### OS Version
10.0.14393.693

### Description
Setting StorageKeyType to Secondary in Set-AzureRmSqlServerAuditingPolicy will not change the audit policy setting for StorageKeyType from Primary to Secondary.  The POST to the https://management.azure.com/subscriptions/************/resourceGroups/********/providers/Microsoft.Sql/servers/***********/auditingSettings/Default?api-version=2015-05-01-preview URL is always sending storageAccountAccessKey equal to key1 of the storage account instead of key2.  This prevents the ability to automate the generation of new storage account keys.

### Debug Output
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/***********/resourceGroups/********/providers/Microsoft.Storage/storageAccounts/********/listKeys?api-version=2015-05-01-preview

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Body:
{
  "key1": "************************1",
  "key2": "************************2"
}

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/***********/resourceGroups/**********/providers/Microsoft.Sql/servers/*********8/auditingSettings/Default?api-version=2015-05-01-preview

Body:
{
  "properties": {
    "state": "Enabled",
    "storageEndpoint": "https://*************.blob.core.windows.net",
    "storageAccountAccessKey":
"************************1",
    "retentionDays": 0,
    "auditActionsAndGroups": [
      "SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP",
      "FAILED_DATABASE_AUTHENTICATION_GROUP",
      "BATCH_COMPLETED_GROUP"
    ],
    "storageAccountSubscriptionId": "*********************",
    "isStorageSecondaryKeyInUse": false
  }
}

### Script/Steps for Reproduction
$resourceGroupName = "ResourceGroupName"
$serverName = "ServerName"
$location = "Location"
$storageAccountName = "StorageAccountName"

##Create new resource group using New-AzureRmResourceGroup
New-AzureRmResourceGroup -ResourceGroupName $resourceGroupName -Location $location

##Create a new SQL Server using New-AzureRmSqlServer
New-AzureRmSqlServer -ResourceGroupName $resourceGroupName -ServerName $serverName -Location $location

##Create new Storage Account
New-AzureRmStorageAccount -ResourceGroupName $resourceGroupName -Name $storageAccountName -Location $location -StorageAccountType "Standard_LRS"

##Set SQL Server audit policy to use Blob storage with Primary key
Set-AzureRmSqlServerAuditingPolicy -ResourceGroupName $resourceGroupName -ServerName $serverName -StorageKeyType Primary -AuditType Blob -StorageAccountName $storageAccountName

##Get SQL Server audit policy
Get-AzureRmSqlServerAuditingPolicy -ResourceGroupName $resourceGroupName -ServerName $serverName

##Output will look like the following
##AuditType          : Blob
##AuditState         : Enabled
##StorageAccountName : **************
##StorageKeyType     : Primary

##Set SQL Server audit policy to use Blob storage with Secondary key
Set-AzureRmSqlServerAuditingPolicy -ResourceGroupName $resourceGroupName -ServerName $serverName -StorageKeyType Secondary -AuditType Blob -StorageAccountName $storageAccountName

##Get SQL Server audit policy
Get-AzureRmSqlServerAuditingPolicy -ResourceGroupName $resourceGroupName -ServerName $serverName

##Output will look like the following.  The StorageKeyType is still Primary and should be Secondary
##AuditType          : Blob
##AuditState         : Enabled
##StorageAccountName : **************
##StorageKeyType     : Primary

**Comment by akromm** [comment]
@yaakoviyun Can you look at this.

**Comment by yaakoviyun** [comment]
Fix is in progress by:  Ayelet Shpigelman

**Comment by cormacpayne** [comment]
Fix has been merged in PR https://github.com/Azure/azure-powershell/pull/3458
