### ISSUE TITLE
How to get a Bing Maps query key?

### ISSUE THREAD

**Issue by IvanovOleg** [Azure/azure-powershell#3445]
Hi,
Is it possible to get a Bing Maps query key using powershell? There is no information about keys in the ARM templae output...

**Comment by markcowl** [comment]
@ravbhatnagar Can you provide any details about this RP?

**Comment by IvanovOleg** [comment]
It looks like it is possible to retrieve this key via API call:
https://main.marketplaceapps.ext.azure.com/api/manage/GetSecretKeys/subscriptions/<subscription id>/resourceGroups/<resource group>/providers/Microsoft.BingMaps/mapApis/<map service name>
At least the Azure portal sends a request to this url. I tried to reproduce it in powershell, but it looks like an access token should be retrieved from the other url (not from https://management.azure.com/ as it's done for the other services). Does anybody know the correct token endpoint for this service?

**Comment by markcowl** [comment]
@ravbhatnagar Please respond with the appropriate generic cmdlets for using this RP

**Comment by cormacpayne** [comment]
Closing since this is not a first-party Azure service.
