### ISSUE TITLE
Get-Help Set-AzureRmVMDscExtension -Examples uses an obsole -Version

### ISSUE THREAD

**Issue by spaelling** [Azure/azure-powershell#3446]
### Cmdlet(s)
Set-AzureRmVMDscExtension

### PowerShell Version
5.1.14393.693 

### Module Version
2.5.0

### OS Version
10.0.14393.693 

### Description
The examples from Set-AzureRmVMDscExtension suggests using version 1.10 which is obsolete. Version should be "2.7" or "2.8"

### Debug Output
``
Get-Help Set-AzureRmVMDscExtension -Examples

NAME
    Set-AzureRmVMDscExtension
    
SYNOPSIS
    Configures the DSC extension on a virtual machine.
    
    
    Example 1: Set a DSC extension
    
    PS C:\>Set-AzureRmVMDscExtension -ResourceGroupName "ResourceGroup001" -VMName "VM07" -ArchiveBlobName "Sample.ps1.zip" -ArchiveStorageAccountName "Stg" -ConfigurationName "ConfigName" -Version "1.10" -Location "West US"
    
    This command sets the DSC extension on the virtual machine named VM07 to download Sample.ps1.zip from the storage account named Stg and the default container. The command invokes the configuration named ConfigName. The Sample.ps1.zip file was previously uploaded 
    by using Publish-AzureRmVMDscConfiguration.
    
    
    Example 2: Set a DSC extension with configuration data
    
    PS C:\>Set-AzureRmVMDscExtension -ResourceGroupName "ResourceGroup001" -VMName "VM13" -ArchiveBlobName "Sample.ps1.zip" -ArchiveStorageAccountName "Stg" -ConfigurationName "ConfigName" -ConfigurationArgument "@{arg="val"}" -ArchiveContainerName 
    "WindowsPowerShellDSC" -ConfigurationData "SampleData.psd1" -Version "1.10" -Location "West US"
    
    This command sets the extension on the virtual machine named VM13 to download Sample.ps1.zip from the storage account named Stg and the container named WindowsPowerShellDSC. The command the configuration named ConfigName and specifies configuration data and 
    arguments. The Sample.ps1.zip file was previously uploaded by using Publish-AzureRmVMDscConfiguration.
    
    
    Example 3: Set a DSC extension with configuration data that has auto update
    
    PS C:\>Set-AzureRmVMDscExtension -ResourceGroupName "ResourceGroup001" -VMName "VM22" -ArchiveBlobName "Sample.ps1.zip" -ArchiveStorageAccountName "Stg" -ConfigurationName "ConfigName" -ConfigurationArgument "@{arg="val"}" -ArchiveContainerName 
    WindowsPowerShellDSC -ConfigurationData "SampleData.psd1" -Version "1.10" -Location "West US" -AutoUpdate
    
    This command sets the extension on the virtual machine named VM22 to download Sample.ps1.zip from the storage account named Stg and the container named WindowsPowerShellDSC. The command invokes the configuration named ConfigName and specifies configuration data 
    and arguments. This command also enables auto update of extension handler to the latest version. The Sample.ps1.zip was previously uploaded by using Publish-AzureRmVMDscConfiguration.
``

### Script/Steps for Reproduction

run `Get-Help Set-AzureRmVMDscExtension -Examples`

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by singhkays** [comment]
@cormacpayne This should be assigned to the DSC team

**Comment by eshaparmar** [comment]
This will be fixed in the next azure PS release. Thanks!
