### ISSUE TITLE
Clean Windows 10 Install is Completely Broken

### ISSUE THREAD

**Issue by mikler** [Azure/azure-powershell#3461]
### PowerShell Version
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### OS Version
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Description
I have just reinstalled OS from scratch and cannot run even a simple AZ RM command like
PS C:\WINDOWS\system32> New-AzureServiceProject helloworld
New-AzureServiceProject : Could not find a part of the path 'C:\Program Files (x86)\Microsoft
SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Profile\Resources\Scaffolding\General\scaffold.xml'.
At line:1 char:1

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

1.  Install Windows 10
1.  Install VS 2015 Update 3 Enterprise Edition
1.  Install Azure SDK 2.9.6
1.  Restart
1.  Open Powershell as Admin

PS C:\WINDOWS\system32> New-AzureServiceProject helloworld
New-AzureServiceProject : Could not find a part of the path 'C:\Program Files (x86)\Microsoft
SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Profile\Resources\Scaffolding\General\scaffold.xml'.
At line:1 char:1

> Install-Module AzureRM
does something

BUT

PS C:\WINDOWS\system32> Install-AzureRM
Install-AzureRM : The term 'Install-AzureRM' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Install-AzureRM
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-AzureRM:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

How is this possible on completely fresh system?????????????!!!!!!!!!!!!!!!!

My alias is mkolesni.

**Comment by cormacpayne** [comment]
Handled offline. Closing issue.

**Comment by sirdank** [comment]
Gah! But what was the resolution? @mikler who were you? What did you see???

**Comment by andrewkittredge** [comment]
I am having this problem.
