### ISSUE TITLE
CredScan exception should point to appropriate documentation

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3463]
If the CredScan tool flags a pull request for containing possible secrets, the error message doesn't give any information on how to resolve the issue:

```
"Credential scanner match found exception!"
```

We need to update this exception message to point partners to the [credscan.md](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/credscan.md) file so they are able to quickly resolve this issue without having to go through the Azure PowerShell team for help.

**Comment by maddieclayton** [comment]
https://github.com/Azure/ci-signing/pull/111

**Comment by maddieclayton** [comment]
Fixed
