### ISSUE TITLE
Remove outdated documentation for New-AzureServiceProject.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#3464]
### Cmdlet(s)
New-AzureServiceProject.

### Description

Outdated documentation is confusing, and customers should move to WebApps!

**Comment by cormacpayne** [comment]
Links from original issue https://github.com/Azure/azure-powershell/issues/2199

https://azure.microsoft.com/en-us/documentation/articles/cloud-services-nodejs-develop-deploy-express-app/

https://azure.microsoft.com/en-us/documentation/articles/cloud-services-nodejs-develop-deploy-app/

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
