### ISSUE TITLE
Add test for change in PSApplicationGatewaySslCertificate.cs 

### ISSUE THREAD

**Issue by vinatara** [Azure/azure-powershell#3467]
### Cmdlet(s)
New-AzureRmApplicationGatewaySslCertificate

### PowerShell Version
The one after 5.1.14393.693

### OS Version
The one after 10.0.14393.693

### Description
Need to add unit test for change in PSApplicationGatewaySslCertificate.cs. We now read the whole pfx file instead of the last certificate in the pfx chain.

**Comment by number213** [comment]
Fixed by this commit https://github.com/Azure/azure-powershell/commit/b353646caa4b2d624d0463779a60fb171cb11e25#diff-07761e8864ed989ef3ffc13327ebc42f
