### ISSUE TITLE
Get-AzureADObjectSetting missing variable "-InformationVariable"

### ISSUE THREAD

**Issue by Machsol-Usman** [Azure/azure-powershell#3468]
### Cmdlet(s)
Get-AzureADObjectSetting

### PowerShell Version
4.0

### Module Version
2.0.0.52

### OS Version
6.3.9600.17400

### Description
Hi All,

I wanted to Get and Set thumbnailPhoto of an ADUser. I tried to use "Get-AzureADObjectSetting" but the command is not accepting -InformationVariable or -IV as input. I get below error:

### Debug Output
Get-AzureADObjectSetting : A parameter cannot be found that matches parameter name 'InformationVariable'.
At line:1 char:100
+ ... getType "User" -InformationVariable "thumbnailPhoto"
+                    ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureADObjectSetting], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Open.MSGraphBeta.PowerShell.GetObjectSetting

### Script/Steps for Reproduction
Connect Azure Tenant and try to run command to update ADObject, see below example:
Get-AzureADObjectSetting -TargetObjectId "03BBE796-0C10-436D-9517-971CBF254469" -TargetType "Users" -InformationVariable "thumbnailPhoto"

**Comment by cormacpayne** [comment]
@Machsol-Usman we do not own the Azure AD cmdlets, and I cannot find a repository (or other location) for you to file this issue directly to the Azure AD cmdlet owners.

I would recommend checking out the Azure support forums for a location to post this issue: https://azure.microsoft.com/en-us/support/forums/
