### ISSUE TITLE
Get-AzureADGroup does not handle collection correctly and did not expose ObjectId

### ISSUE THREAD

**Issue by yangl900** [Azure/azure-powershell#347]
The command has output:

```
Get-AzureADGroup -SearchString foo

DisplayName                    Type                           ObjectId
-----------                    ----                           --------
foobar                                               d3246484-1df3-4b4e-b913-05ac7d4ab382
foogroup                                           0b58831e-8db7-4a4a-917a-c236a23ee8b3
```

however if we assign this to a variable:

$group = Get-AzureADGroup -SearchString foo

$group[0].ObjectId is null
$group[0] is also null

it was exposed as $group.Id[0], but this is not discoverable and seems wrong.

**Comment by cormacpayne** [comment]
Closing this issue as `Get-AzureADGroup` is no longer a supported cmdlet. Please feel free to try the [`Get-AzureRmADGroup`](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Resources/Commands.Resources/help/Get-AzureRmADGroup.md) cmdlet and see if the problem has been resolved.
