### ISSUE TITLE
Login-AzureRMAccount wrongly specifies Enable-AzureDataCollection is in module AzureResourceManager

### ISSUE THREAD

**Issue by KrishnaV-MSFT** [Azure/azure-powershell#3475]
### PowerShell Version
PS C:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Module Version
PS C:\> Gmo azurerm.profile -li

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.5.0      AzureRM.profile                     {Disable-AzureRmDataCollection, Enable-AzureRmDataCollecti...

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
 10.0.14393.693

### Description
1. Run the following commands in a PowerShell console:

       install-module -Name AzureRM -RequiredVersion 3.4.0 -Force
        Login-AzureRMAccount

2. Login-AzureRMAccount mentions the following:

     If you choose to not participate, you can enable at any time by using Azure PowerShell as follows:
     1. Use the Enable-AzureDataCollection cmdlet to turn the feature On. The cmdlet can be found in the
     AzureResourceManager module
      To enable data collection: PS > Enable-AzureDataCollection

3. Notice the mention of AzureResourceManage module
4.  It should be Enable-AzureRMDataCollection in module "AzureRM.Profile"
PS C:\> gcm Enable-AzureRMDataCollection

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Enable-AzureRmDataCollection                       2.5.0      AzureRM.profile
      

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by markcowl** [comment]
### Description
We need to update the data collection resource string to mention the appropriate module for DataCollection cmdlets.  This string is shown on the first execution after installign the cmdlets.

- [ ]  Update this string to point to the AzureRM.Profile module
- [ ] Look through resource strings for other mentions of AzureResourceManager as a module and correct.

### Cost: 2

**Comment by cormacpayne** [comment]
Fixed in https://github.com/Azure/azure-powershell/pull/3777
