### ISSUE TITLE
New-AzureQuickVM & Location Parameter

### ISSUE THREAD

**Issue by mikewo** [Azure/azure-powershell#348]
The way the cmdlet works now is that if a service already exists and you also supply the location parameter it will error out saying "New-AzureQuickVM : Service already exists, Location cannot be specified.".  It wants you to leave off the Location parameter if the service exists, but it would be better if instead it performed a check to verify the service exists in the same location that is provide and if so, then ignore the location parameter instead of giving an error.  Only return an error if the service exists already and is in ANOTHER location.

Whenever I have to provide different sets of parameters based on the existence of something that means I end up doing additional calls to determine existence beforehand, then crafting the right parameter set based on that.  It leads to a lot of conditional logic in the scripts that could easily be avoided if the cmdlet was just a little smarter. It's clearly doing an existence check already so why not be able to compare the location parameters?

**Comment by devigned** [comment]
Yes, it definitely could do a check to see if the location matches.

If you want idempotent results, perhaps you could check out the Azure Resource Manager cmdlets: https://msdn.microsoft.com/en-us/library/azure/mt125899.aspx.

**Comment by singhkay** [comment]
This could be done. I'll put this in the backlog for triaging.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
