### ISSUE TITLE
Check for internet is broken when running on Azure WebApps

### ISSUE THREAD

**Issue by fujiy** [Azure/azure-powershell#349]
I am trying to run Azure Cmdlets on Azure WebApps.

I know it's not supported yet (http://feedback.azure.com/forums/169385-web-apps-formerly-websites/suggestions/7155775-add-azure-commandlets).

What I did:

* Set WebApp to run with LoadUserProfile turned on
* Before executing any script I removed Execution Policies: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
* Added a copy of Azure PowerShell SDK to my project (C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure)
* Included the path of my copy to environment variable "PSModulePath". Before that I was doing a Import-Module pointing to Azure.psd1, but some commands validates if Azure Cmdlets are installed through "Get-Module -ListAvailable Azure"

I still have some blockers:

* Microsoft.WindowsAzure.Commands.Utilities.Common.CloudBaseCmdlet.ProcessRecord calls Validate.ValidateInternetConnection. That throws when running on Azure WebApps. I did a "workaround" downloading the source code and compiling a version with this line commented.
* Managing Certificates. X509Store.Add doesn't work. even using "CurrentUser" store location

Thanks for any help

**Comment by devigned** [comment]
As you said, this is not supported currently. I'm going to close in favor of the user voice request.
