### ISSUE TITLE
Publish-AzureRmVMDscConfiguration requires Login-AzureRmAccount

### ISSUE THREAD

**Issue by sirdank** [Azure/azure-powershell#3506]
### Cmdlet(s)
Publish-AzureRmVMDscConfiguration

### PowerShell Version
5.0

### Module Version
2.0.1

### OS Version
10.0.10586.672

### Description
Since running this cmdlet with the -ConfigurationArchivePath does not connect to the network or do anything with your azure subscription, I think the requirement to have a logged in session could be removed. As is, if I want powershell to zip up my configuration data in a CI context, it crashes with the error

Publish-AzureRmVMDscConfiguration : Run Login-AzureRmAccount to login.

### Script/Steps for Reproduction
Just run this cmdlet with the -ConfigurationArchivePath parameter (I think it may have changed to -OutputArchivePath in a later version) but make sure you are not logged in to an azure RM account.

**Comment by waghpravin14** [comment]
I am getting also same error. Any update here. Not sure how logged-in session removing.

**Publish-AzureRmVMDscConfiguration : Run Login-AzureRmAccount to login.**
At line:1 char:1
+ Publish-AzureRmVMDscConfiguration -ConfigurationPath "C:\Personal\Pro ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-AzureRmVMDscConfiguration], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Commands.Compute.Extension.DSC.PublishAzureVMDscConfigurationCommand

**Comment by Aorimn** [comment]
Still the same problem, also for CI purposes. Any update?

**Comment by kensykora** [comment]
Would love for this to not be a thing, please remove this as a requirement if it's possible.

**Comment by cormacpayne** [comment]
Adding `Azure PS Team` label to triage

**Comment by cormacpayne** [comment]
@eshaparmar  Hey Esha, would you mind taking a look at this scenario? It appears that this cmdlet shouldn't be inheriting from the `AzureRMCmdlet` base class, but rather the `AzureDataCmdlet`, to avoid checking if the user has logged in.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please let us know if this issue is still a concern.
