### ISSUE TITLE
Breaking change tool refactor v2

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3507]
- [ ] Add rule that allows removal of global parameter, as long as it has been added to every existing parameter set, has maintained its position, and remains mandatory if it was previously
- [ ] Fix error where the name of a type is being used as the key in a dictionary rather than assembly qualified name
    - For example, [here](https://github.com/Azure/azure-powershell/blob/preview/tools/StaticAnalysis/BreakingChangeAnalyzer/CmdletMetadataHelper.cs#L223)
    - If a cmdlet has output types `List<Foo>` and `List<Bar>`, an error will be thrown since `List` is added to the dictionary, rather than `List<Foo>`
- [ ] Implement check for property stability when types have changed
    - For example, going from `VirtualMachine` to `PSVirtualMachine` - all properties of `VirtualMachine` are found in `PSVirtualMachine`, so it shouldn't be flagged as a breaking change
- [ ] Fix bug where changing output type from `object` to something useful is throwing an error

**Comment by markcowl** [comment]
Fixed
