### ISSUE TITLE
[question] what do you use for format ps1xml generation?

### ISSUE THREAD

**Issue by vors** [Azure/azure-powershell#3508]
Hello,

In [Microsoft.Azure.Commands.Compute.format.generated.ps1xml](https://github.com/Azure/azure-powershell/blob/7bb65bee5d9488a0958f39203731113af52c22c6/src/ResourceManager/Compute/Commands.Compute/Microsoft.Azure.Commands.Compute.format.generated.ps1xml#L19) you mentioned that this file is generated by a tool.
Can you, please, share what is the tool and is it available for using in other projects?

**Comment by cormacpayne** [comment]
@vors Hey Sergei, currently we have teams copy existing formatting files that exist in the repository if they ever need to use it.

We are not aware of the original "tool" used to create these files, but [`Export-FormatData`](https://msdn.microsoft.com/powershell/reference/5.1/microsoft.powershell.utility/Export-FormatData) seems to be creating the same file. The PowerShell team may know the tool originally used to generate these files.
