### ISSUE TITLE
Set-AzureEndpoint - does not support renaming an endpoint.

### ISSUE THREAD

**Issue by erichexter** [Azure/azure-powershell#351]
It is unclear from the documentation and from experimenting  how an Endpoint can be renamed with this command. The portal allows endpoints to be renamed, but i am not sure  what is happening under the hood to make that happen.  Is this possible with the current release?

**Comment by devigned** [comment]
@DeepakRajendranMsft thoughts?

**Comment by markjbrown** [comment]
We don't support renaming of endpoints. not on our roadmap either.
