### ISSUE TITLE
0.8.16.1 Preview :: Azure Module Creates Global "aliases" Variable

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#352]
The 0.8.16.1 version of the Microsoft Azure PowerShell module, running on top of Windows 8.1 and Windows Management Framework (WMF) Core April 2015 Preview, is exposing a global (aka. "public") variable called `$aliases`.

Is it absolutely necessary for this variable to be created as a **global** variable in the Azure PowerShell module, or can this be made private, or even better, removed altogether?

I just randomly noticed this as I brought up Intellisense in #PowerShell ISE.

![image](https://cloud.githubusercontent.com/assets/466713/7318326/e82b0150-ea47-11e4-8cbe-880925519261.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by stankovski** [comment]
Thanks for the feedback. The script that creates this variable is in [ServiceManagementStartup.ps1](https://github.com/Azure/azure-powershell/blob/dev/src/ServiceManagement/Services/Commands.Utilities/ServiceManagementStartup.ps1). If you can create a PR to make it private it would be great.

**Comment by pcgeek86** [comment]
@stankovski Completed. Let me know where to send the bill. j/k :)

https://github.com/Azure/azure-powershell/pull/542

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
