### ISSUE TITLE
Missing cmdlet help for New-AzureSiteRecoverySite 

### ISSUE THREAD

**Issue by juneb** [Azure/azure-powershell#3525]
There's a cut/paste error in Microsoft.Azure.Commands.RecoveryServicesRdfe.dll-help.xml

(https://github.com/Azure/azure-powershell/blob/dev/src/ServiceManagement/RecoveryServices/Commands.RecoveryServices/Microsoft.Azure.Commands.RecoveryServicesRdfe.dll-help.xml)

As a result, there are two cmdlet help topics for New-AzureSiteRecoveryVault and none for New-AzureSiteRecoverySite.

```
  <!--New-AzureSiteRecoverySite-->
  <!-- v 1.3.0.36 -->
  <command:command xmlns:maml="http://schemas.microsoft.com/maml/2004/10" xmlns:command="http://schemas.microsoft.com/maml/dev/command/2004/10" xmlns:dev="http://schemas.microsoft.com/maml/dev/2004/10">
    <command:details>
      <command:name>
        New-AzureSiteRecoveryVault     #<------------
      </command:name>
      <maml:description>
<maml:para>Creates a new Azure Site Recovery Vault</maml:para>
```

**Comment by markcowl** [comment]
Need to check if this is one of our grandfathered exceptions to the help rule,  We probably wouldn't fix this.

@juneb I fear this might be a won't fix if we verify, any chance you might contribute a PR with the new md file for the cmdlet?

**Comment by juneb** [comment]
Sorry, but I don't know anything about the feature.

**Comment by markcowl** [comment]
@juneb This is an RDFE cmdlet, RDFE tools are essentially in maintenance mode at this point, we aren't accepting new features and lthere is a higher bar for fixing issues.  The advice is to move to the RecoveryServices cmdlets in ARM.  


The rule I was mentioning is a static analysis rule that validates help for each cmdlet on check-in, but includes exceptions for older cmdlets (cmdlets checked in before the rule).

**Comment by SAPIENTechnologies** [comment]
Thanks for explaining, @markcowl. You guys should try Pester, which does dynamic analysis. :)

**Comment by markcowl** [comment]
@SAPIENTechnologies Pester is a test framework, so I guess, inasmuch as testing is sort of prescribed dynamic analysis, that is true.  Static analysis is sufficient to determine whether cmdlets have help.  New-AzureSiteRecoverySite is indeed on the grandfathered list.  Unfortunately, it looks like the duplicated help is really duplicated, and not just misnamed.

**Comment by markcowl** [comment]
@sriramvu Can you take a look?  It looks liek help for the ```New-AzureSiteRecoveryVault``` cmdlet was duplicated, adn no help was provided for ```New-AzureSiteRecoverySite```.

**Comment by sriramvu** [comment]
Submitted PR for this issue: https://github.com/Azure/azure-powershell/pull/3647
Have removed the redundant help for New-AzureSiteRecoveryVault and added the required help content for "New-AzureSiteRecoverySite".

**Comment by sriramvu** [comment]
Closing the issue as PR got merged.
Please let us know if something is missing.
Thank you.
