### ISSUE TITLE
Duplicate entries for Restart-AzureWebsite in Microsoft.WindowsAzure.Commands.dll-help.xml

### ISSUE THREAD

**Issue by juneb** [Azure/azure-powershell#3532]
When you parse the file, you'll find them at indexes 58 and 66. Get-Help gets the second and ignores the first. So, if someone accidentally updates the second instance, it won't have any effect.

**Comment by markcowl** [comment]
Need to investigate as an addition to our Static Analysis, this could inadvertently occur in the future

**Comment by cormacpayne** [comment]
This should be resolved when the fix for https://github.com/Azure/azure-powershell/issues/3583 goes in next release

**Comment by markcowl** [comment]
Closing as duplicate for #3583
