### ISSUE TITLE
Get-AzureRmVM is broken in 2.7.0 version of AzureRM.Compute module for AzureUSGovernment

### ISSUE THREAD

**Issue by sdubeymsft** [Azure/azure-powershell#3541]
### Cmdlet(s)
Get-AzureRmVM
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
PSVersion                      5.1.14393.693                                                                                                                                                                
PSEdition                      Desktop                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                      
BuildVersion                   10.0.14393.693                                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                          
SerializationVersion           1.1.0.1

### Module Version
2.7.0 version of AzureRM.Compute
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
Get-AzureRmVM : The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'. The supported api-versions are 
'2015-05-01-preview,2015-06-15,2016-03-30,2016-08-30'.
ErrorCode: InvalidResourceType
ErrorMessage: The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'. The supported api-versions are 
'2015-05-01-preview,2015-06-15,2016-03-30,2016-08-30'.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 803d87f7-6d04-475e-ad06-8ee7775b1cf3
At line:4 char:1
+ Get-AzureRmVM
+ ~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.GetAzureVMCommand
 
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
$env = Get-AzureRmEnvironment -Name "AzureUSGovernment"
Login-AzureRmAccount -EnvironmentName "AzureUSGovernment"

Get-AzureRmVM

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
Closing. Feel free to re-open this issue if you are still having issues accessing VMs in other clouds.
