### ISSUE TITLE
Azure DSC Handler 2.22 issue

### ISSUE THREAD

**Issue by ibenbouzid** [Azure/azure-powershell#3544]
### Module Version
Azure DSC extention handler 2.22
### OS Version
2012R2
### Description
Hi I'm experiencing issues with this new handler v2.22 that didn't surface with previous releases.
Each time i try to deploy my DSC  extention template on a VM 2012 R2 i got this error below.
and the deployment stops.
If i change the DSC handler to 2.21 or previous release the deployment is fine.
Please let me know if this is the right site to report the issue or point me to the right one.

### Debug Output
{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningTimeout",
        "message": "Provisioning of VM extension 'S-Install' has timed out. Extension installation may be taking too long, or extension status could not be obtained."
      }
    ]
  }
}

### Script/Steps for Reproduction

Here is my dsc : 

Configuration Prereqs
{

Param (		
		[Parameter(Mandatory)]
        [String]$DomainName,

        [Parameter(Mandatory)]
        [PSCredential]$Admincreds,
		    
		[Int]$RetryCount=20,
        [Int]$RetryIntervalSec=30 )

Import-DscResource -ModuleName PSDesiredStateConfiguration, xPendingReboot, xDisk, cDisk
[PSCredential ]$DomainCreds = New-Object PSCredential ("${DomainName}\$($Admincreds.UserName)", $Admincreds.Password)

  Node localhost
  {  
	     xWaitforDisk Disk2
        {
             DiskNumber = 2
             RetryIntervalSec =$RetryIntervalSec
             RetryCount = $RetryCount
        }
		cDiskNoRestart ADDataDisk
        {
            DiskNumber = 2
            DriveLetter = "F"
        }
	    WindowsFeature DnsTools
	    {
	        Ensure = "Present"
            Name = "RSAT-DNS-Server"
	    }
		WindowsFeature RSATDNS 
        { 
            Ensure = "Present" 
            Name = "RSAT-ADDS"		
        }
        WindowsFeature WebServerRole
        {
            Name = "Web-Server"
            Ensure = "Present"
            }
        WindowsFeature WebAppDev
        {
            Name = "Web-App-Dev"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
            }
        WindowsFeature WebAspNet
        {
            Name = "Web-Asp-Net"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
            }
        WindowsFeature WebNetExt
        {
            Name = "Web-Net-Ext"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
            }
        WindowsFeature WebISAPIExt
        {
            Name = "Web-ISAPI-Ext"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
            }
        WindowsFeature WebISAPIFilter
        {
            Name = "Web-ISAPI-Filter"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
            }
        WindowsFeature WebLogLibraries
        {
            Name = "Web-Log-Libraries"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
            }
        WindowsFeature WebRequestMonitor
        {
            Name = "Web-Request-Monitor"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
        }
		WindowsFeature WebHttpTracing
        {
            Name = "Web-Http-Tracing"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
        }
		WindowsFeature WebBasicAuth
        {
            Name = "Web-Basic-Auth"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
        }
		WindowsFeature WebWindowsAuth
        {
            Name = "Web-Windows-Auth"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
        }
		WindowsFeature WebClientAuth
        {
            Name = "Web-Client-Auth"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
        }
		WindowsFeature WebDynCompression
        {
            Name = "Web-Dyn-Compression"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
        }
		WindowsFeature NETWCFHTTPActivation45
        {
            Name = "NET-WCF-HTTP-Activation45"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
        }
		WindowsFeature WebAspNet45
        {
            Name = "Web-Asp-Net45"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
        }
        WindowsFeature WebMgmtTools
        {
            Name = "Web-Mgmt-Tools"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
            }
        WindowsFeature WebMgmtConsole
        {
            Name = "Web-Mgmt-Console"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
        }
		WindowsFeature WebScriptingTools
        {
            Name = "Web-Scripting-Tools"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
            }
        WindowsFeature WebMgmtCompat
        {
            Name = "Web-Mgmt-Compat"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
        }
        WindowsFeature BITS
        {
            Name = "BITS"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
        }
	     WindowsFeature ServerMediaFoundation
        {
            Name = "Server-Media-Foundation"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
        }
		 WindowsFeature DesktopExperience
        {
            Name = "Desktop-Experience"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
        }
		WindowsFeature WindowsIdentityFoundation
        {
            Name = "Windows-Identity-Foundation"
            Ensure = "Present"
            DependsOn = "[WindowsFeature]WebServerRole"
         }

	  xPendingReboot Reboot2
      { 
            Name = "AfterPrereqsInstall"
			DependsOn = "[WindowsFeature]WindowsIdentityFoundation", "[cDiskNoRestart]ADDataDisk"
      }

	  LocalConfigurationManager 
      {
            ConfigurationMode = 'ApplyOnly'
            RebootNodeIfNeeded = $true
            ActionAfterReboot = "ContinueConfiguration"
      }
  }
}

**Comment by markcowl** [comment]
@ibenbouzid What is the azure powershell cmdlet you are using in this case?

**Comment by ibenbouzid** [comment]
Hi Mark I'm using azure dsc handler is it the right group to ask the question? my DSC module is in the first post.On 11 Mar 2017 2:12 a.m., Mark Cowlishaw <notifications@github.com> wrote:@ibenbouzid What is the azure powershell cmdlet you are using in this case?

**Comment by leonmeijer** [comment]
Having the same issue

**Comment by maddieclayton** [comment]
@ibenbouzid If you are not using an AzureRm or Azure module (https://www.powershellgallery.com/packages/AzureRM/5.0.1 or https://www.powershellgallery.com/packages/Azure/5.1.1) then this is not the right place for your question. Closing now, please reopen if you are using an Azure/AzureRm module.
