### ISSUE TITLE
azure powershell stack-dev branch is not producing the AzureStack nuget package for the release

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#3547]
### PowerShell Version
1.2.8.* (newer builds after 1.2.8 version)
### Description

 powershell-sign job against the latest stack-dev branch is not producing the azurestack nuget package 
http://azuresdkci.cloudapp.net/job/powershell-sign/888/artifact/src/Package/
 
while against the stack-dev-1.2.8, it produces the azurestack nuget package
 http://azuresdkci.cloudapp.net/job/powershell-sign/891/artifact/src/Package/
 
### Script/Steps for Reproduction
Run the powershell-sign job against stack-dev branch

**Comment by bganapa** [comment]
@shahabhijeet to look in to this

**Comment by cormacpayne** [comment]
@shahabhijeet can you take a look?

**Comment by cormacpayne** [comment]
Fixed.
