### ISSUE TITLE
Remove-AzureRMDisk doesnt validate DiskName exists

### ISSUE THREAD

**Issue by andyjballgit** [Azure/azure-powershell#3558]
### Cmdlet(s)
Remove-AzureRMDisk

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1.15042

### Module Version
2.7.0
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.15042.0 

### Description
If an invalid DiskName is passed as a param , no warning is given 

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
Omitted for security reasons

### Script/Steps for Reproduction
1. Create a ResourceGroup called Bob
2. Run below 
Remove-AzureRMDisk -DiskName "Somethingrandom" -ResourceGroupName "Bob"

**Comment by cormacpayne** [comment]
@singhkays @hyonholee would you mind taking a look?

**Comment by singhkays** [comment]
@hyonholee Can you check? This looks like a bug. Remove should show an error if the disk does not exist

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please let us know if this issue is still a concern.
