### ISSUE TITLE
Set-AzureRmKeyVaultAccessPolicy PermissionsToSecrets not working correctly

### ISSUE THREAD

**Issue by timomta** [Azure/azure-powershell#3559]
### Cmdlet(s)
Set-AzureRmKeyVaultAccessPolicy 

### PowerShell Version
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### OS Version
Win 10

### Description
Our doc (https://docs.microsoft.com/en-us/powershell/resourcemanager/azurerm.keyvault/v1.1.11/set-azurermkeyvaultaccesspolicy) gives the following guidance  to grant permissions for an application using its object ID:

PS C:\>Set-AzureRmKeyVaultAccessPolicy -VaultName 'Contoso03Vault' -ObjectId 34595082-9346-41b6-8d6b-295a2808b8db -PermissionsToSecrets 'Get,Set'

However, when you actually try to issue that command, PowerShell responds with an error that it does not know about the get,set permissions (in spite of the fact that the error message itself lists them):

PS C:\windows\system32> Set-AzureRmKeyVaultAccessPolicy -VaultName 'sand-stage-vault' -ObjectId 62749e93-cd4b-4ed2-8770-29e6f73edb20 -PermissionsToSecrets 'get,set'
Set-AzureRmKeyVaultAccessPolicy : Cannot validate argument on parameter 'PermissionsToSecrets'. The argument "get,set" does not 
belong to the set "get,list,set,delete,all" specified by the ValidateSet attribute. Supply an argument that is in the set and then 
try the command again.
At line:1 char:132
+ ...  62749e93-cd4b-4ed2-8770-29e6f73edb20 -PermissionsToSecrets 'get,set'
+                                                                 ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzureRmKeyVaultAccessPolicy], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy 

The ‘all’ permission works.

### Script/Steps for Reproduction
Run the Set-AzureRmKeyVaultAccessPolicy command per the example sited

**Comment by cormacpayne** [comment]
@pomortaz Hey Pooneh, would you mind taking a look at this issue?

**Comment by pomortaz** [comment]
@timomta you are using permissions as string. Try passing them as list e.g. with no quotation mark:
Set-AzureRmKeyVaultAccessPolicy -VaultName <vault-name> -ObjectId <object-id> -PermissionsToSecrets **get,set**
We'll fix the documentation. Thanks for letting us know. :)

**Comment by timomta** [comment]
Thanks! Yes that works. I didn't realize that was the problem due to the usage examples in the documentation. Please fix the docs - I have had 2 customers and a colleague ask me about this. Thank you for your help!

**Comment by timomta** [comment]
One other suggestion though, for ease of use, flexibility, and possibly passing in variables for the permissions arg, is to just allow the cmdlet to accept a string, split by command, and parse the array into the enums you need internally.

**Comment by maddieclayton** [comment]
Closing - PermissionsToSecrets is a list of strings, so it is not expected to parse a single string into a list - we could not do both this and keep the validateset, which is much more crucial for users.
