### ISSUE TITLE
Set-AzureRmVMAccessExtension reboots VM when username is changed

### ISSUE THREAD

**Issue by janegilring** [Azure/azure-powershell#3561]
### Cmdlet(s)
Set-AzureRmVMAccessExtension
### PowerShell Version
`PSVersion`                    5.1.14393.693                                                                                                                                                    
### Module Version
2.7.0      AzureRM.Compute
### OS Version
10.0.14393.693   
### Description
When the username specified to Set-AzureRmVMAccessExtension -UserName is different from the existing username for the built-in Administrator account inside a Windows VM (haven`t tested agains't Linux), the VM is rebooted. If the username specified is already present, the VM is not rebooted - only the password is updated. This behaviour is not documented in the cmdlet-help. I would suggest the following action:
-Add information about this behavior to the cmdlet help
-Consider setting the confirm preference for this cmdlet to High so the user is being prompted to confirm the action
-Consider writing a warning message when the cmdlet is run informing the user that the VM might be rebooted if the username is changed
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
PS C:\>Set-AzureRmVMAccessExtension -ResourceGroupName "ResrouceGroup11" -Location "Central US" -VMName "VirtualMachine07" -Name "ContosoTest" -TypeHandlerVersion "2.0" -UserName "PFuller" -Password "Password"

In this example, the UserName PFuller is not present inside the VM before running the command

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
