### ISSUE TITLE
Regarding 3.6.0 release compatibility with PowerShell 4.0

### ISSUE THREAD

**Issue by tohling** [Azure/azure-powershell#3575]
### Cmdlet(s)
All Azure PowerShell cmdlets

### PowerShell Version
Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1

### Module Version
3.6.0

### OS Version
Major  Minor  Build  Revision
-----  -----  -----  --------
6      3      9600   16406

### Description
Does Azure PoweShell 3.6.0 work with PowerShell version 4.0?  

I have an environment that cannot have it's OS upgraded at the moment.  As such, running the WMF 5.0 installation to upgrade to PowerShell 5.0 is not an option right now because that process would attempt to run an Windows Upgrade workflow.  However, I want to at least upgrade the system's Azure PowerShell to the latest release.  Can you confirm that it would be safe to do so?

### Debug Output
None.

### Script/Steps for Reproduction
None.

**Comment by cormacpayne** [comment]
@tohling Hey Ling, installing Azure PowerShell via the MSI (either from Web Platform Installer or the [GitHub release](https://github.com/Azure/azure-powershell/releases/tag/v3.6.0-February2017)) is supported for PowerShell 3.0 and higher.

Installing the modules from [PowerShell Gallery](http://www.powershellgallery.com/) will required PowerShell 5.0 and higher.

Let me know if you have any other questions!
