### ISSUE TITLE
Storage Context Parameter Binding Error with Start-AzureVNetGatewayDiagnostics, Start-AzureVirtualNetworkGatewayDiagnostics

### ISSUE THREAD

**Issue by rfunaki** [Azure/azure-powershell#3578]
Cmdlets: Start-AzureVNetGatewayDiagnostics, Start-AzureVirtualNetworkGatewayDiagnostics
PSVersion: 5.1.14393.693     
OS Version: 10.0.14393.693   
Module Version: 3.5.0

I am trying to initiate a Diagnostics session for a VNet gateway that I am attempting to use for a Site to Site connection, utilizing the Static/Policy type gateway in order to be compatible with a Cisco ASA Peer endpoint.

However, when I attempt to initiate the diagnostics session using any of the below variations of the cmd, I get the following error (with debugging on)

```
DEBUG: 4:34:06 PM - NewAzureStorageContext begin processing with ParameterSet 'AccountNameAndKey'.
DEBUG: 4:34:06 PM - NewAzureStorageContext end processing.
Start-AzureVNetGatewayDiagnostics : Cannot bind parameter 'StorageContext'. Cannot convert the "Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext" value of type "Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext" to type "Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext".
At line:1 char:161
+ ... rageContext (New-AzureStorageContext -StorageAccountName $storageAcco ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Start-AzureVNetGatewayDiagnostics], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.WindowsAzure.Commands.ServiceManagement.Network.Gateway.StartAzureVnetGatewayDiagnostics
```

Below are the commands I have tried:

```
Start-AzureVNetGatewayDiagnostics -VNetName "VNET-NAME" -CaptureDurationInSeconds $captureDuration -StorageContext (New-AzureStorageContext -StorageAccountName $storageAccountName -StorageAccountKey $storageAccountKey)
Start-AzureVNetGatewayDiagnostics -VNetName "VNET-NAME" -CaptureDurationInSeconds $captureDuration -StorageContext $storageContext #Same as above, but with New-AzureStorageContext preset in a variable
Start-AzureVirtualNetworkGatewayDiagnostics -GatewayId $vnetGwId -CaptureDurationInSeconds $captureDuration -StorageContext (New-AzureStorageContext -StorageAccountName $storageAccountName -StorageAccountKey $storageAccountKey) -ContainerName $storageContainer
Start-AzureVirtualNetworkGatewayDiagnostics -GatewayId $vnetGwId -CaptureDurationInSeconds $captureDuration -StorageContext $storageContext -ContainerName $storageContainer #Same as above, but with New-AzureStorageContext preset in a variable
```

I am modeling this after the below post:
[Step-by-Step: Capturing Azure Resource Manager (ARM) VNET Gateway Diagnostic Logs](https://blogs.technet.microsoft.com/keithmayer/2016/10/12/step-by-step-capturing-azure-resource-manager-arm-vnet-gateway-diagnostic-logs/)

I've looked into the cmdlet source, and I cannot determine why it is not binding this parameter. Furthermore, the error message is confusing because it is listing the same types for the source and target, so I cannot determine what the discrepancy is.

**Comment by rfunaki** [comment]
As an amendment to the above, I also have tried using different storage containers (one originating from creation with Resource Model, the other created via Service Management/Classic model) - both produced the same results.

**Comment by Fizz-Mo** [comment]
I can't get it to work either

**Comment by markcowl** [comment]
@rfunaki which version of the storage cmdlets are you using?  This is likely a type version mismatch

**Comment by markcowl** [comment]
Closing for lack of response.  If you are still seeing this issue, please reopen

**Comment by Keldandorin** [comment]
I do have the same problem trying to do the logging described in link in first post.
Azure.Storage is version 2.8.0 and AzureRM.Storage is version 2.8.0.

**Comment by Keldandorin** [comment]
Found the problem. Hade some older modules installed.

**Comment by kmchannon** [comment]
what module were old? I'm having the same issue

**Comment by Keldandorin** [comment]
check all your installed modules and make sure they are on latest version. For em it was the Storage module that was for some reason on a old version

**Comment by asktomsk** [comment]
Quick update for folks who googled this issue.

You face the problem 
```
Start-AzureVirtualNetworkGatewayDiagnostics : 
Cannot bind parameter 'StorageContext'. 
Cannot convert the "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" 
value of type "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" to
type 
"Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext".
```
it means you use the latest (May 15 2017) version of Azure powershell module: 4.0.1
This version has some incompatibility with latest Azure.Storage 3.0.1.

You need to remove it and install Azure 3.8.0 and Azure.Storage 3.8.0  (April 5th 2017)
https://www.powershellgallery.com/packages/Azure/3.8.0

```
Uninstall-Module -Name Azure.Storage
Uninstall-Module -Name Azure
Install-Module -Name Azure -RequiredVersion 3.8.0
```

This combination works fine.

**Comment by jontreynes** [comment]
I'm having a similar issue
$pw = Get-AzureRmStorageAccountKey -ResourceGroupName $resourcegroupname -Name $storage_accountname
$context = New-AzureStorageContext -StorageAccountName $storage_accountname -StorageAccountKey $pw.Value[0] -Protocol Https

$autobackupconfig = New-AzureRmVMSqlServerAutoBackupConfig -Enable `
    -RetentionPeriodInDays $retentionperiod -StorageContext $context `
    -ResourceGroupName $storage_resourcegroupname -BackupSystemDbs `
    -BackupScheduleType $backupscheduletype -FullBackupFrequency $fullbackupfrequency `
    -FullBackupStartHour $fullbackupstarthour -FullBackupWindowInHours $fullbackupwindow `
    -LogBackupFrequencyInMinutes $logbackupfrequency
}
New-AzureRmVMSqlServerAutoBackupConfig : Cannot bind parameter 'StorageContext'. Cannot convert the 
"Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" value of type 
"Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" to type 
"Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext".
At line:4 char:61
+ ...    -RetentionPeriodInDays $retentionperiod -StorageContext $context `
+                                                                ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureRmVMSqlServerAutoBackupConfig], ParameterBinding 
   Exception
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Azure.Commands.Compute.NewAzureVMSqlSe 
   rverAutoBackupConfigCommand 


Has the type mismatch between "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" and type "Microsoft.WindowsAzure.Commands.**Common**.Storage.AzureStorageContext" have a solution?
