### ISSUE TITLE
New-AzureResourceGroupDeployment polling should have backoff

### ISSUE THREAD

**Issue by yangl900** [Azure/azure-powershell#358]
New-AzureResourceGroupDeployment will poll the deployment status after submit deployment, but seems polling too much (every 2 seconds?). We should have some way to backoff as deployment may run for hours.

**Comment by ravbhatnagar** [comment]
Yes, we should address this.

**Comment by ravbhatnagar** [comment]
We should make it less chatty and set the connection lease timeout to 5 mins (discuss with Anders)

**Comment by markcowl** [comment]
@ravbhatnagar The connection lease timeout does not just apply to the cmdlet.  We should not do this.  We *should*  reduce the number of polls for long-running deployments, potentially through an exponential backoff or similar mechanism.

**Comment by ravbhatnagar** [comment]
We have mitigated this issue by increasing the polling to 5 sec. We still need to think/discuss the long term solution.

**Comment by markcowl** [comment]
@yangl900 The immedia5te issue here has been fixed, but keeping this open and adding to the backlog for a more comprehensive solution

**Comment by ravbhatnagar** [comment]
@markcowl - Agreed, we are planning to fix this through an exponential back off mechanism. Will revive the thread we had on this to finalize the design. Moving this to Apr release.

**Comment by ravbhatnagar** [comment]
Could not get to this in the Apr release. Moving to backlog.

**Comment by ravbhatnagar** [comment]
Fixed
