### ISSUE TITLE
Update online help system to generate help dlls

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3583]
### Description

Need to remove the  dll-Help.xml files from the repo and use the markdown files as the source of truth.

- [x] Add to BUILD target so that dll-Help.xml files are correctly generated and delivered to the correct directory as part of each build.
- [x] Ensure that dll-Help.xml files are also built as part of VS builds.
- [x] Ensure that Validation methods still work, so that we can check complete help coverageas part of each check-in

### Cost: 4

**Comment by cormacpayne** [comment]
Adding `GenerateHelp.ps1` script to build that does the following:

- Copies the `help` folder (containing the markdown files) for each RP to the output directory
- Generates a new `temp_help` folder for each RP, which contains markdown files generated from `Update-MarkdownHelpModule` (uses the markdown found in `help` and the cmdlet code to create the updated markdown)
- Compares the markdown files found in `help` and `temp_help` using a custom library to make sure the help that is being checked in has been updated (_e.g.,_ if someone adds/removes a parameter, but doesn't run the `Update-MarkdownHelpModule` cmdlet, this change will not be reflected in the markdown, but will be caught when comparing `help` to `temp_help`)
- Validates the markdown found in `help` to ensure that there are no gaps in the information provided (as well as added the capability to suppress exceptions)
- Generate the XML help file for each RP based off of the markdown that is found in the `help` file

**Comment by markcowl** [comment]
Fixed
