### ISSUE TITLE
Set-AzureReservedIPAssociation is generally available?

### ISSUE THREAD

**Issue by jangelfdez** [Azure/azure-powershell#359]
Hi!

Is that command available for everybody? I'm receiving the following error and I don't know if it's a bug or an unreleased feature.

```
PS C:\> Set-AzureReservedIPAssociation -ReservedIPName viprepwg -ServiceName prepropwg2
DETALLADO: 12:25:57 - Begin Operation: Set-AzureReservedIPAssociation
Set-AzureReservedIPAssociation : BadRequest: The subscription is not authorized for feature vipmobility.
En línea: 1 Carácter: 1
```

Thanks!

**Comment by Jesudasan** [comment]
You can use below command

Set-AzureReservedIPAssociation -ReservedIPName ReservedIPName -ServiceName "CloudServiceName" -Slot Production

-J

**Comment by markjbrown** [comment]
This feature is GA. Closing.
