### ISSUE TITLE
Set-AzureRmApplicationGatewayBackendAddressPool missing documented param

### ISSUE THREAD

**Issue by iamGavinJ** [Azure/azure-powershell#3598]
### Cmdlet(s)
Set-AzureRmApplicationGatewayBackendAddressPool
New-AzureRmApplicationGatewayBackendAddressPool

### PowerShell Version
5.1.14393.693

### Module Version
3.6.0

### OS Version
10.0.14393.693

### Description
As is currently available via the ARM portal and is documented in Example 3 of the doco https://docs.microsoft.com/en-us/powershell/resourcemanager/azurerm.network/v3.4.0/set-azurermapplicationgatewaybackendaddresspool#examples the param -BackendIPConfigurationIds no longer not exist in the cmdlet.

After updating the backend pool using the portal to specify a virtual machine and its interface, Get-AzureRmApplicationGatewayBackendAddressPool returns:

BackendAddresses            : {}
BackendIpConfigurations     : {}
ProvisioningState           : Succeeded
BackendAddressesText        : []
BackendIpConfigurationsText : [
                                {
                                  "Id": "/subscriptions/***SUBSCRIPTION GUID***/resourceGroups/***RESOURCE GROUP NAME***/providers/Microsoft.Network/ne
                              tworkInterfaces/<NIC>/ipConfigurations/***IP CONFIG***",
                                  "Primary": false
                                }
                              ]
Name                        : <NAME>
Etag                        : W/"<GUID>"
Id                          : /subscriptions/***SUBSCRIPTION GUID***/resourceGroups/***RESOURCE GROUP NAME***/providers/Microsoft.Network/applicationGa
                              teways/***NAME***/backendAddressPools/***POOL NAME***

This param is also missing from New-***

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by markcowl** [comment]
@DeepakRajendranMsft Please take a look

**Comment by MiYanni** [comment]
@iamGavinJ I started a pull request for this documentation fix. I didn't find the example in `New-AzureRmApplicationGatewayBackendAddressPool` but I have removed the example in `Set-AzureRmApplicationGatewayBackendAddressPool`. Once the PR is merged, I'll close this issue.
