### ISSUE TITLE
AzureRM.NetCore.Preview does not have all needed cmdlets

### ISSUE THREAD

**Issue by edevil** [Azure/azure-powershell#3604]
### Cmdlet(s)

Get-AzureRmAvailabilitySet

### PowerShell Version

Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.16
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### OS Version

macos Sierra

### Script/Steps for Reproduction

```
$avSet =  Get-AzureRmAvailabilitySet -ResourceGroupName $rgName -Name $avSetName
Get-AzureRmAvailabilitySet : The term 'Get-AzureRmAvailabilitySet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:11
+ $avSet =  Get-AzureRmAvailabilitySet -ResourceGroupName $rgName -Name ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureRmAvailabilitySet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I'm trying to follow [this](https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-windows-convert-unmanaged-to-managed-disks) documentation but there are some missing commands, Get-AzureRmAvailabilitySet for example.

Is there some ETA on when I can run those scripts completely?

**Comment by markcowl** [comment]
You can list availability sets using Get-AzureRmResource, using the resource namespace for availability sets.

Full typed versions of Core cmdlets are coming in the first half of this year.
