### ISSUE TITLE
New-AzureRmVirtualNetworkGateway requires you to specify the VPNType parameter for a Ultraperformance ExpressRoute gateway

### ISSUE THREAD

**Issue by Roblarson** [Azure/azure-powershell#3615]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion` 

Name                           Value                                                                                                    
----                           -----                                                                                                    
PSVersion                      5.1.14393.693                                                                                            
PSEdition                      Desktop                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                  
BuildVersion                   10.0.14393.693                                                                                           
CLRVersion                     4.0.30319.42000                                                                                          
WSManStackVersion              3.0                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                      
SerializationVersion           1.1.0.1     
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
New-AzureRmVirtualNetworkGateway is requiring -VPNTYPE for an ExpressRoute Ultraperformance gateway. This parameter should not be required.

PS C:\Users\rolarson> New-AzureRmVirtualNetworkGateway -Name $GWName  -ResourceGroupName $vNetResourceGroupName -Location $Location -GatewayType ExpressRoute -IpConfigurations $ipconfig -GatewaySku UltraPerformance 
WARNING: The output object type of this cmdlet will be modified in a future release.
New-AzureRmVirtualNetworkGateway : 'VpnType' cannot be null.
At line:1 char:1
+ New-AzureRmVirtualNetworkGateway -Name $GWName  -ResourceGroupName $v ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVirtualNetworkGateway], ValidationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayCommand 

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
See above.

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft Hey Deepak, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
@Roblarson I spoke with Deepak offline - this is a known issue that the Gateway team is working on. We will keep this issue open to track the status of the fix.

**Comment by maddieclayton** [comment]
@Nilambari Can you take a look at this issue?

**Comment by dedhar** [comment]
This issue does not seem to repro with latest powershell version. Are you still seeing the issue @maddieclayton 

PS C:\temp> New-AzureRmVirtualNetworkGateway -Name $GWName -ResourceGroupName $RG -Location $Location -IpConfigurations $ipconf -GatewayType Expressroute -GatewaySku UltraPerformance
WARNING: The output object type of this cmdlet will be modified in a future release.


Name                   : GW
ResourceGroupName      : TestRG
Location               : eastus
Id                     : /subscriptions/873b0459-81fb-4b4d-a304-68c4abb58ce6/resourceGroups/TestRG/providers/Microsoft.Network/virtualNetworkGateways/GW
Etag                   : W/"ac7af168-1ec8-4221-a725-54f905ecb4a5"
ResourceGuid           : 37753f21-081a-4a61-aa72-00125134b943
ProvisioningState      : Succeeded
Tags                   :
IpConfigurations       : [
                           {
                             "PrivateIpAllocationMethod": "Dynamic",
                             "Subnet": {
                               "Id": "/subscriptions/873b0459-81fb-4b4d-a304-68c4abb58ce6/resourceGroups/TestRG/providers/Microsoft.Network/virtualNetworks/TestVNet/subnets/GatewaySubnet"
                             },
                             "PublicIpAddress": {
                               "Id": "/subscriptions/873b0459-81fb-4b4d-a304-68c4abb58ce6/resourceGroups/TestRG/providers/Microsoft.Network/publicIPAddresses/GWIP"
                             },
                             "Name": "gwipconf",
                             "Etag": "W/\"ac7af168-1ec8-4221-a725-54f905ecb4a5\"",
                             "Id": "/subscriptions/873b0459-81fb-4b4d-a304-68c4abb58ce6/resourceGroups/TestRG/providers/Microsoft.Network/virtualNetworkGateways/GW/ipConfigurations/gwipconf"
                           }
                         ]
GatewayType            : ExpressRoute
VpnType                : PolicyBased
EnableBgp              : False
ActiveActive           : False
GatewayDefaultSite     : null
Sku                    : {
                           "Capacity": 2,
                           "Name": "UltraPerformance",
                           "Tier": "UltraPerformance"
                         }
VpnClientConfiguration : null
BgpSettings            : null



PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp>
PS C:\temp> Get-Module AzureRM.Network

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.2.0      AzureRM.Network                     {Add-AzureRmApplicationGatewayAuthenticationCertificate, Add-AzureRmApplicationGatewayBackendAddressPool, Add-AzureRmApplicationGatewayBackendHttpSettings, Add-AzureRmApplicationGatewayFrontendIPConfig...}

**Comment by dedhar** [comment]
Please reopen if the issue persists.
