### ISSUE TITLE
"Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials." in new PowerShell session.

### ISSUE THREAD

**Issue by slapointe** [Azure/azure-powershell#362]
If I execute this script in a new PowerShell window, with valid credential it fails the first time.

```
if(!$global:issueAzureCred) {
    $global:issueAzureCred = Get-Credential
}

Import-Module Azure

Clear-AzureProfile -Force
$random = Get-Random -Maximum 99999
$storageAccount = 'devtestpowershell{0}' -f $random
$subscriptionId = '{SubscriptionIdHere}'

$azureProfile = New-AzureProfile -SubscriptionId $subscriptionId -StorageAccount $storageAccount -Credential $global:issueAzureCred
Select-AzureProfile -Profile $azureProfile
New-AzureStorageAccount -StorageAccountName $storageAccount -Type Standard_LRS -Location 'East US 2' -Profile $azureProfile
```

Error:
> New-AzureStorageAccount : Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials.
At C:\Users\stephane.lapointe\Desktop\Add-AzureAccountIssue.ps1:15 char:1
+ New-AzureStorageAccount -StorageAccountName $storageAccount -Type Sta ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureStorageAccount], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.WindowsAzure.Commands.ServiceManagement.StorageServices.NewAzureStorageAccountCommand

If I run the same script again in the same session then it works no problem.

I tried the script on 0.8.15.1, 0.8.16.0 & 0.9.0 and I get the same behavior

**Comment by slapointe** [comment]
If I perform the New-AzureProfile and Select-AzureProfile 2 times in a row before the first call to the actions I want to do it work...

$azureProfile = New-AzureProfile -SubscriptionId $subscriptionId -StorageAccount $storageAccount -Credential $global:issueAzureCred
Select-AzureProfile -Profile $azureProfile

$azureProfile = New-AzureProfile -SubscriptionId $subscriptionId -StorageAccount $storageAccount -Credential $global:issueAzureCred
Select-AzureProfile -Profile $azureProfile

Get-AzureVMImage

**Comment by devigned** [comment]
@markcowl any thoughts on this one?

**Comment by stankovski** [comment]
Same cause as https://github.com/Azure/azure-powershell/issues/332
