### ISSUE TITLE
Autogenerate cmdlet category file.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#3622]
### Cmdlet(s)
All of them‽

### Description
Generate a mapping file to place cmdlets in categories.

Start with these categories (and add or remove as needed): https://docs.microsoft.com/en-us/cli/azure/.

Use this format as best we can for a mapping file: https://github.com/Azure/azure-docs-cli-python/blob/master/titleMapping.json.

**Comment by markcowl** [comment]
Fixed.
