### ISSUE TITLE
Path parameter is optional in Azure powershell but if omitted causes internal server error

### ISSUE THREAD

**Issue by solankisamir** [Azure/azure-powershell#3623]
### Cmdlet(s)
Import-AzureRmApiManagementApi

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@solankisamir do you know if this issue has been resolved?

**Comment by solankisamir** [comment]
@cormacpayne no, I did not address this issue.

**Comment by solankisamir** [comment]
closing this issue, due to lack of steps to reproduce the issue. 
Please use the latest cmdlet [v2.4.0-July2019](https://github.com/Azure/azure-powershell/releases/tag/v2.4.0-July2019), which gives the detailed error trace
