### ISSUE TITLE
[AzureChinaCloud] [Re-open]: Get-AzureRmUsage failes with "No Registered Providers" for APIManagement Service

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#3626]
Old Issue: [https://github.com/Azure/azure-powershell/issues/3204](url)

### Cmdlet(s)
Get-AzureRmUsage

### PowerShell Version
4.0

### Module Version
Module: Manifest 2.0.1 AzureRM.ApiManagement

### OS Version
6.3.9600.17400

### Description

Was able to provision API Management instance, but on the same session am unable to determine the RMUsage with Get-AzurerRMUsage commandlet.

PS C:> **New-AzureRmApiManagement -ResourceGroupName "pradebban" -Name "pradebban" -Location "China North" -Organ
ization "pradebban" -AdminEmail "china@azure.com" -Sku Standard -Capacity 2**

StaticIPs                   : {139}
Id                          : /subscriptions/hidden/resourceGroups/pradebban/providers/Microsoft.ApiManagement
                              /service/pradebban
Name                        : pradebban
Location                    : China North
Sku                         : Standard
Capacity                    : 2
ProvisioningState           : Succeeded
RuntimeUrl                  : https://pradebban.azure-api.cn
PortalUrl                   : https://pradebban.portal.azure-api.cn
VirtualNetwork              :
PortalHostnameConfiguration :
ProxyHostnameConfiguration  :
Tags                        : {}
AdditionalRegions           : {}
ResourceGroupName           : pradebban

PS C:\ **Get-AzureRmUsage -ResourceId /subscriptions/hidden/resourceGroups/pradebban/providers/Microsoft.ApiManagement/service/pradebban**

C:\> Get-AzureRmUsage -ResourceId /subscriptions/hidden/resourceGroups/pradebban/providers/Microsoft.ApiManagement/service/pradebban
Get-AzureRmUsage : **NoRegisteredProviderFound: No registered resource provider found for location 'chinanorth' and API version '2014-04-01' for type
'service'. The supported api-versions are '2014-02-14, 2015-09-15'. The supported locations are 'chinaeast, chinanorth'.**
At line:1 char:1
+ Get-AzureRmUsage -ResourceId /subscriptions/hidden ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmUsage], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.UsageMetrics.GetAzureRmUsageCommand

### Script/Steps for Reproduction

1. Deploy API Management with New-AzureRmApiManagement
2. Once provisioned use Get-AzureRmUsage with the ResourceID

Thanks,
Pradebban Raja

**Comment by cormacpayne** [comment]
@Pradebban I'm going to close this issue and reopen the [previous issue](https://github.com/Azure/azure-powershell/issues/3204) since the appropriate team members are a part of the conversation.

In the future, whenever you would like to reopen a closed issue, you don't have to copy the contents from the old issue and put them into a new one, you can click the "Reopen issue" button at the bottom of the closed issue 😃
