### ISSUE TITLE
[Re-Open] Get-AzureRmResource command does not fail/error out for random Resource Names

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#3627]
Cmdlet(s)

Get-AzureRmResourceProvider

PowerShell Version

4.0

Module Version

2.0.1 (Azure)
3.0.1 (AzureRM.Resources)

OS Version

6.3.9600.17400

Description

Am trying to use Get-AzureRmResource command to get information on a particular resource.

_Get-AzureRmResource -ResourceType Microsoft.Devices -ResourceName "**Anything**"_

ResourceId                      ResourceName                    ResourceType                    SubscriptionId

---

/subscriptions/-0d45...                                 Microsoft.Devices/              -0d45-4183-9f36-0b0...

_Get-AzureRmResource -ResourceType Microsoft.Devices -ResourceName "**Something**"_

ResourceId                      ResourceName                    ResourceType                    SubscriptionId

---

/subscriptions/-0d45...                                 Microsoft.Devices/              -0d45-4183-9f36-0b0...

The parameter -**ResourceName** just accepts any random value but returns the same result.
And i think it is specific for the "-ResourceType Microsoft.Devices"

Thanks,
Pradebban Raja

**HISTORY**

**_jonsabo commented on Nov 4, 2016_**

It seems to me at least that this is an upstream concern and likely can't be fixed in the powershell module without significant effort. I can reproduce this for any of the 'collection' style queries. It looks like even if you put in a resource provider that doesn't exist, it still returns a 200 response that's simply empty. I assume the logic is that it was a valid query and it was able to process it fine, it's just that there are no results. It seems like there could be more helpful messages though indicating that the resource type you're looking for doesn't exist for instance.

PS X:\> Get-AzureRmResource -ResourceGroupName $workspaceRG -ResourceType "Microsoft.thisistotallynotanactualresourceprovider" -Debug
DEBUG: 10:48:24 AM - GetAzureResourceCmdlet begin processing with ParameterSet 'Get resource collection'.
...snip...
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/subid/resourceGroups/rgname/resources?$filter=resourceType EQ 'Microsoft.thisistotallynotanactualresourceprovider'&api-
version=2016-09-01

Headers:
User-Agent                    : AzurePowershell/v3.1.0.0,PSVersion/v5.1.14393.223
ParameterSetName              : Get resource collection
CommandName                   : Get-AzureRmResource

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 14991
x-ms-request-id               : 0a605597-357d-459e-94c0-e69ed8db7f96
x-ms-correlation-request-id   : 0a605597-357d-459e-94c0-e69ed8db7f96
x-ms-routing-request-id       : NORTHCENTRALUS:20161104T154825Z:0a605597-357d-459e-94c0-e69ed8db7f96
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Fri, 04 Nov 2016 15:48:25 GMT

Body:
{
  "value": []
}

DEBUG: 10:48:25 AM - GetAzureResourceCmdlet end processing.
DEBUG: 10:48:25 AM - GetAzureResourceCmdlet end processing.

**_markcowl commented on Jan 17_**
This is the accepted powershell behavior you should return nothing if there are no query results.

If there is a scenario that is blocked by this behavior, please open an issue that describes that scenario and we will considewr this.

**Comment by Pradebban** [comment]
@markcowl, I disagree with terming this as accepted powershell behavior,

Few examples where the results is not empty (and has meaningful error) when the query fetched nothing.

1. Get-AzureRmResource -ResourceType microsoft.web/sites -ResourceName "12345"
Get-AzureRmResource : ResourceNotFound : The Resource 'microsoft.web/sites/12345' under resource group '' was not found.

2. Get-AzureRmResource -ResourceType microsoft.datafactory/datafactories -ResourceName "12345"
Get-AzureRmResource : ResourceNotFound : The Resource 'microsoft.datafactory/dataFactories/12345' under resource group'' was not found.

3. Get-AzureRmResource -ResourceType microsoft.sql/servers -ResourceName "12345"
Get-AzureRmResource : ResourceNotFound : The Resource 'microsoft.sql/servers/12345' under resource group '' wasnot found.

**Comment by cormacpayne** [comment]
@Pradebban I'm going to close this issue and reopen the [previous issue](https://github.com/Azure/azure-powershell/issues/3018)
