### ISSUE TITLE
Get-AzureRMVM in Azure Stack throwing error as api version imcompatible

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-powershell#3631]
Get-AzureRmVM : The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api
version '2016-03-30'. The supported api-versions are '2015-06-15'.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : '812d1a79-5d4a-4dd2-b4ff-f2b98355bd84'
At line:1 char:1
+ Get-AzureRmVM
+ ~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.GetAzureVMCommand
![error](https://cloud.githubusercontent.com/assets/22904071/23292555/ad2db786-fa86-11e6-9329-8cb32dbf0fbb.png)

**Comment by amarzavery** [comment]
Originally the customer filed this in xplat cli. So filing one over here. 

https://github.com/Azure/azure-xplat-cli/issues/3521

**Comment by markcowl** [comment]
@harishchakkingal  Please use version 1.2.9 with AzureStack.
