### ISSUE TITLE
Get-AzureADUser should return a WhenCreated property

### ISSUE THREAD

**Issue by janegilring** [Azure/azure-powershell#3635]
### Cmdlet(s)
Get-AzureADUser

Let me know if this is not the appropriate place for feedback about the Azure AD module, as I couldn`t find any other feedback channels.

### PowerShell Version
5.1.14393.953

### Module Version
2.0.0.71 (AzureAD)

### OS Version
10.0.14393.953

### Description
No property for the creation date exists on the objects output by Get-AzureADUser. In the older MSOnline module there is a WhenCreated property on the object outputted by Get-MsolUser, which we relied on in a scenario. Due to this we had to revert our plans about using the AzureAD module instead of the MSOnline module.

### Script/Steps for Reproduction
connect-azuread
$a  = get-azureaduser -All $true
$a | Get-Member

**Comment by cormacpayne** [comment]
@janegilring Hey Jan, we do not own these cmdlets, but I was able to find a forum where you could potentially post this issue: https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=WindowsAzureAD

Let me know if you need anything else!
