### ISSUE TITLE
Get-AzureRmDisk ignores -ErrorAction SilentlyContinue parameter

### ISSUE THREAD

**Issue by marioinz** [Azure/azure-powershell#3636]
### Cmdlet(s)

$disk = Get-AzureRmDisk -ResourceGroupName $ResourceGroupName -DiskName $Name -ErrorAction SilentlyContinue 

### PowerShell Version
5.1.14393.693

### Module Version
3.5.0

### OS Version
10.0.14393.693

### Description

shows error message if not exists (ignoring parameter of silient continue)

**Comment by cormacpayne** [comment]
@hyonholee @singhkays would you mind taking a look at this issue?

**Comment by jimbrookski** [comment]
This problem is still occurring. 
Running in a published runbook in Azure Automation causes the script to terminate when caught.

**Comment by gazataeon** [comment]
Does the same for "-erroraction ignore"

**Comment by VJayMeyer** [comment]
I re-wrote my query to use the Where-Object cmdlet. Such as:-

$Disk = Get-AzureRmDisk -ResourceGroupName $ResourceGroupName |? DiskName -eq $OSDiskName

**Comment by singhkays** [comment]
Update: @hyonholee is looking into this

**Comment by singhkays** [comment]
Closing as this is fixed in PowerShell 5.4.0
