### ISSUE TITLE
Get-AzureADUser : Unable to filter certain UserPrincipalName

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#3640]
### Cmdlet(s)

Get-AzureADUser

### PowerShell Version

4.0

### Module Version

6.3.9600.17400

### OS Version

6.3.9600.17400

### Description

Get-AzureADUser with filter does not work for certain ids.
The same works for few ids randomly.

PS C:\Windows\system32> Get-AzureADUser | ? {$_.UserPrincipalName -eq "Pradebban@hidden.onmicrosoft.com"}
PS C:\Windows\system32> Get-AzureADUser | ? {$_.UserPrincipalName -eq "Pradebban@hidden.onmicrosoft.com"} -Verbose
PS C:\Windows\system32> Get-AzureADUser | ? {$_.UserPrincipalName -eq "Pradebban@hidden.onmicrosoft.com"} **-debug **(No result)****
PS C:\Windows\system32> Get-AzureADUser -ObjectId "pradebban@hidden.onmicrosoft.com"

DeletionTimeStamp            :
ObjectId                     : f405c38c-9980--daa1e112b7ad
ObjectType                   : User
AccountEnabled               : True
AssignedLicenses             : {}
AssignedPlans                : {}
City                         :
Country                      :
Department                   :
DirSyncEnabled               :
DisplayName                  : Pradebban Raja
FacsimilieTelephoneNumber    :
GivenName                    : Pradebban
ImmutableId                  :
JobTitle                     :
LastDirSyncTime              :
Mail                         :
MailNickName                 : Pradebban
Mobile                       :
OnPremisesSecurityIdentifier :
OtherMails                   : {v-pradr@microsoft.com}
PasswordPolicies             : None
PasswordProfile              :
PhysicalDeliveryOfficeName   :
PostalCode                   :
PreferredLanguage            :
ProvisionedPlans             : {}
ProvisioningErrors           : {}
ProxyAddresses               : {}
SipProxyAddress              :
State                        :
StreetAddress                :
Surname                      : Raja
TelephoneNumber              :
ThumbnailPhoto               :
UsageLocation                :
UserPrincipalName            : Pradebban@hidden.onmicrosoft.com
UserType                     : Member

### Debug Output
 None

### Script/Steps for Reproduction

Connect to Azure AD
Run - Get-AzureADUser | ? {$_.UserPrincipalName -eq "Pradebban@hidden.onmicrosoft.com"}

Thanks,
Pradebban Raja

**Comment by cormacpayne** [comment]
@Pradebban we do not own these cmdlets (they are found in the `AzureAD` module), but I was able to find a forum where you could potentially post this issue: https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=WindowsAzureAD

Also, you could post this issue here: https://azure.microsoft.com/en-us/support/forums/

Let me know if you need anything else!

**Comment by Pradebban** [comment]
@cormacpayne , thanks for the help!
