### ISSUE TITLE
Add-AzureRmSqlServerKeyVaultKey : Unable to add KV to sqlserver - NoRegisteredProviderFound 

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#3644]
### Cmdlet(s)
Add-AzureRmSqlServerKeyVaultKey

### PowerShell Version
5.0.10586.117

### Module Version
2.7.0

### OS Version
10.0.10586.117

### Description
Unable to use BYOK for SQL Server as per the changelog: [https://github.com/Azure/azure-powershell/blob/master/ChangeLog.md](url)

Add-AzureRmSqlServerKeyVaultKey : This cmdlet adds an Azure Key Vault key to a Sql Server.

### Error

**Add-AzureRmSqlServerKeyVaultKey : NoRegisteredProviderFound: No registered resource provider found for location
'westus' and API version '2015-05-01-preview' for type 'servers'. The supported api-versions are '2014-01-01,
2014-04-01, 2014-04-01-preview'**. The supported locations are 'eastus, westus, southcentralus, eastus2, centralus,
northcentralus, eastasia, southeastasia, japanwest, japaneast, westeurope, northeurope, brazilsouth, australiaeast,
australiasoutheast, centralindia, westindia, southindia, canadacentral, canadaeast, westus2, westcentralus, uksouth,
ukwest, koreacentral, koreasouth'.
At line:1 char:1
+ Add-AzureRmSqlServerKeyVaultKey -KeyId "https://hidden.vault.az ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmSqlServerKeyVaultKey], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.ServerKeyVaultKey.Cmdlet.AddAzureSqlServerKeyVaultKey

### Debug Output

PS C:\Windows\system32> Add-AzureRmSqlServerKeyVaultKey -KeyId "https://hidden.vault.azure.net:443/keys/pradebban/
300034e3574249e99633edfce4" -ServerName hidden -ResourceGroupName "hidden" -Verbose -debug
DEBUG: 7:30:02 PM - AddAzureSqlServerKeyVaultKey begin processing with ParameterSet '__AllParameterSets'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 7:30:05 PM - using account id 'Pradebban@hidden.onmicrosoft.com'...

Confirm
Are you sure you want to perform this action?
Performing the operation "About to process resource" on target "".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '03/19/2017 00:25:25 +00:00',
MultipleResource? 'True', Tenant: 'c990bb7a-51fc07fb1041c0', UserId: 'Pradebban@hidden.onmicrosoft.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'Pradebban@hidden.onmicrosoft.com', Name: Pradebban
Raja, IdProvider: 'https://sts.windows.net/c99-9c07fb1041c0/', Uid:
'f405c80-4711aa1e112b7ad'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '03/19/2017 00:25:25 +00:00' Comparing to
'03/18/2017 23:30:06 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:55:19.0262333'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/3-9f36-0b01899fdce2/resourceGroups/hidden/provid
ers/Microsoft.Sql/servers/hidden/keys/hidden_pradebban_300034e3573edfce4?api-version=2015-05-0
1-preview

Headers:

Body:
{
  "properties": {
    "uri": "https://hidden.vault.azure.net:443/keys/pradebban/300034a043edfce4",
    "serverKeyType": "AzureKeyVault"
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 69c9e34d-68bb-17272c57987
x-ms-correlation-request-id   : 69c9e34d--817272c57987
x-ms-routing-request-id       : CANADAEAST:20170318T233009Z:69c94dee-b265-817272c57987
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Sat, 18 Mar 2017 23:30:08 GMT

Body:
{
  "error": {
    "code": "NoRegisteredProviderFound",
    "message": "No registered resource provider found for location 'westus' and API version '2015-05-01-preview' for
type 'servers'. The supported api-versions are '2014-01-01, 2014-04-01, 2014-04-01-preview'. The supported locations
are 'eastus, westus, southcentralus, eastus2, centralus, northcentralus, eastasia, southeastasia, japanwest, japaneast,
 westeurope, northeurope, brazilsouth, australiaeast, australiasoutheast, centralindia, westindia, southindia,
canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth'."
  }
}

Confirm
NoRegisteredProviderFound: No registered resource provider found for location 'westus' and API version
'2015-05-01-preview' for type 'servers'. The supported api-versions are '2014-01-01, 2014-04-01, 2014-04-01-preview'.
The supported locations are 'eastus, westus, southcentralus, eastus2, centralus, northcentralus, eastasia,
southeastasia, japanwest, japaneast, westeurope, northeurope, brazilsouth, australiaeast, australiasoutheast,
centralindia, westindia, southindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest, koreacentral,
koreasouth'.
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
Add-AzureRmSqlServerKeyVaultKey : NoRegisteredProviderFound: No registered resource provider found for location
'westus' and API version '2015-05-01-preview' for type 'servers'. The supported api-versions are '2014-01-01,
2014-04-01, 2014-04-01-preview'. The supported locations are 'eastus, westus, southcentralus, eastus2, centralus,
northcentralus, eastasia, southeastasia, japanwest, japaneast, westeurope, northeurope, brazilsouth, australiaeast,
australiasoutheast, centralindia, westindia, southindia, canadacentral, canadaeast, westus2, westcentralus, uksouth,
ukwest, koreacentral, koreasouth'.
At line:1 char:1
+ Add-AzureRmSqlServerKeyVaultKey -KeyId "https://hidden.vault.az ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmSqlServerKeyVaultKey], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.ServerKeyVaultKey.Cmdlet.AddAzureSqlServerKeyVaultKey

### Script/Steps for Reproduction

1. In an existing KeyVault add a key to use for BYOK TDE Enabling.
2. Add an Azure Key Vault key to a Sql Server using Add-AzureRmSqlServerKeyVaultKey

Thanks,
Pradebban Raja

**Comment by cormacpayne** [comment]
@akromm Hey Adam, would you mind taking a look at this issue?

**Comment by akromm** [comment]
@mihymel Can you please take a look.

**Comment by Pradebban** [comment]
Thanks for the inputs, I don't see this instructions in the release highlights ( 3.7.0 )/ nor any documentation. Is this available in AzureChinaCloud​ as well as Private preview?

**Comment by mihymel** [comment]
@rajaprad  As TDE with BYOK is preparing for public preview in Public Cloud, we are no longer onboarding private preview customers. We're targeting mid July for our public preview in Public Cloud. A rough estimate for when public preview will open up in National clouds (including AzureChinaCloud) is Fall of 2017.

I'm closing this for now, since the underlying issue is not a powershell issue.
