### ISSUE TITLE
Deploy webjob using resource manager

### ISSUE THREAD

**Issue by niadak** [Azure/azure-powershell#3645]
Can somebody guide us on the following:
 
1.	How can I add a new Web Job to an existing Azure ARM Web app using SPN based authentication?
 
I am able to do the same with certificate based authentication and using New-AzureWebsiteJob command, which is Azure-Service management command.
2.	Can I execute a Service-Management command using SPN based authentication? If so how?
3.	If No, Is there any equivalent Resource manager command to achieve the same?

**Comment by shahabhijeet** [comment]
@niadak there is no service principal support for in RDFE.
Is there a reason you have not moved to ARM?
