### ISSUE TITLE
SetAzureDiskEncryption issue

### ISSUE THREAD

**Issue by kpantos** [Azure/azure-powershell#3646]
### Cmdlet(s)
SetAzureDiskEncryption

### PowerShell Version
PSVersion                      5.1.14393.953

### Module Version
Version           : 2.1.0
Name              : Azure
Author            : Microsoft Corporation

### OS Version
BuildVersion                   10.0.14393.953

### Description
When running the command on an already existing RHEL 7.2 VM OS disk the response returned is "Install Succeeded is not a valid versioned Key Vault Secret URL. It should be in the format https://<vaultEndpoint>/secrets/<secretName>/<secretVersion>."

The json output of the call to the Azure Management API for the VM is:
```
{
    body: {
        "error": {
            "code": "InvalidParameter",
            "target": "encryptionSettings.diskEncryptionKey.secretUrl ",
            "message": "Install Succeeded is not a valid versioned Key Vault Secret URL.It should be in the form at https: //<vaultEndpoint>/secrets/<secretName>/<secretVersion>."  
        }
    }
} 
```

The error originates from **line 289 of SetAzureDiskEncryptionExtension.cs** where the statusMessage the result of the call to GetExtensionStatusMessage() is assigned as the SecretUrl parameter of the encryptionSettings.DiskEncryptionKey object when trying to UpdateVmEncryptionSettings.

`encryptionSettings.DiskEncryptionKey.SecretUrl = statusMessage;`

From what I've seen the statusMessage result contains just a string showing the installation status of the extension and not the actual Secret needed.

Can you please verify this and let me know if I'm missing something,

Thanks in advance

**Comment by cormacpayne** [comment]
@krkhan @singhkays would you guys mind taking a look at this issue?

**Comment by torbad** [comment]
I am struggling with the same

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
