### ISSUE TITLE
In default exception handling code for AzureRM, attempt to print better exception message by default

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3649]
### Description

By default we simply print the exception message from the exception we catch to the error record.  We want to continue to print this, but we may want to replace the message printed as part of the exception to take into account AUtoRest exception details.  For example, the response information is normally included in the exception, and the message from the response is usually more detailed than the exception jmessage coming from Swagger.  Either printing this response message when available, or combining it with the message in the caught exception, we should be able to provide better error details by default for exception generated in AutoRest clients.

### Cost: 6

**Comment by markcowl** [comment]
@markcowl please add more detail on user scenarios and a candidate design for the new feature

**Comment by letmaik** [comment]
+1 The exception messages thrown by the Azure Batch cmdlets for example are pretty much useless. I always have to try-catch everything and print error messages myself with something like:
```ps1
    Write-Host $_.Exception.StatusMessage
    Write-Host $_.Exception.RequestInformation.HttpStatusMessage
    Write-Host ($_.Exception.RequestInformation.AzureError.Values | format-list -force | out-string)
```
The exception messages should contain all information that is necessary for a human to interpret the error completely.

**Comment by begoldsm** [comment]
@markcowl awesome, thank you for adding this to the costing roadmap!

**Comment by markcowl** [comment]
@letmaik @begoldsm Note that the ```Resolve-AzureRmError``` cmdlet is a patch over this problem while we look at resolving is systematically in the cmdlets

**Comment by letmaik** [comment]
@cormacpayne Please don't close issues without commenting on the reason.
