### ISSUE TITLE
Get-AzureNetworkSecurityGroupConfig -VM $VM says not associated.

### ISSUE THREAD

**Issue by markscholman** [Azure/azure-powershell#365]
When I assign an NSG to a VM and run the command Get-AzureNetworkSecurityGroupConfig -VM $VM it says that NSG is not associated to this VM. 
WARNING: 16:11:38 - VM "DEMODMZ01" is not currently associated with a Network Security Group.
I did assign the NSG to the VM before...

![capture](https://cloud.githubusercontent.com/assets/8298597/7474487/163611ea-f342-11e4-9819-8cc510f9b201.PNG)

**Comment by devigned** [comment]
@DeepakRajendranMsft thoughts?

**Comment by Coffee-007** [comment]
You need to update the VM as well.

Try this command:
Get-AzureVM -ServiceName AzureDemoDMZ -Name DemoDMZ01 | Set-AzureNetworkSecurityGroupConfig -NetworkSecurityGroup "Demo SG" | Update-AzureVM

**Comment by markjbrown** [comment]
Closing. If still active issue please reopen.
