### ISSUE TITLE
[Add-AzureRmEnvironment] Save Environment and context information for another session use 

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#3656]
### Cmdlet(s)
Add-AzureRmEnvironment
### PowerShell Version
V5

### Module Version
1.0.04.3 (Azurestack version)

### Description
Azurestack customers need to do Add-AzureRmEnvironment in each session before they could interact with the cloud. It is a pain to do Add-AzureRmEnvironment (with so many parameters) in each session

The environment info should be persisted in a file by default for loading up it in another session
There should also be a way to  set the default environment , instead of needing to pass the environment info in the Login cmdlet every time

**Comment by sphibbs** [comment]
Context persistence.

**Comment by markcowl** [comment]
### Cost: 6

**Comment by markcowl** [comment]
- [ ] Use the new facility for named contexts to allow saving multiple contexts to a known location
- [ ] New cmdlets for removing a named context
- [ ] New cmdlet to select a context
- [ ] Cmdlets that change the context automatically write to known location
- [ ] Profile provider reads the context from the known location
- [ ] Cmdlets take a context object, or a context name

**Comment by markcowl** [comment]
Fixed
