### ISSUE TITLE
Get-AzureRmWebApp returns "ResourceGroup" string; elsewhere usually "ResourceGroupName" 

### ISSUE THREAD

**Issue by jskii** [Azure/azure-powershell#3657]
### Cmdlet(s)
Get-AzureRmWebApp

### PowerShell Version
PSVersion 5.1.14393.693

### Module Version
Azure Powershell 3.7.0 release

### OS Version
BuildVersion 10.0.14393.693

### Description
Generally in using Azure Powershell so far, most objects return "ResourceGroupName" as a string property.  Get-AzureRmWebApp returns the same information as "ResourceGroup" string.  Should be more consistent in implementation.

### Debug Output
Not really a break, but the output for gm on the two:
Get-AzureRmWebApp: ResourceGroup             Property   string ResourceGroup {get;} 
Get-AzureRmStorageAccount: ResourceGroupName   Property   string ResourceGroupName {get;set;}    

### Script/Steps for Reproduction
Use Get-AzureRmWebApp.

**Comment by cormacpayne** [comment]
@Nking92 Hey Nicholas, would you mind taking a look at this issue? We have a breaking change release scheduled for the beginning of May, so that would be a good time to make this change if your team decides to do so.

**Comment by jskii** [comment]
Hello. Updating to report that this issue still exists in the latest release version.

**Comment by panchagnula** [comment]
@jskii, i am following with our backend folks if this a possible breaking change they will take on our end . Will update once i get more info from them.

**Comment by panchagnula** [comment]
@naveedaz this issue talks about the inconsistency in the ResourGroup property between webapp & other azure resources, example, storage calls this ResourceGroupName - do we have plans of changing this?

**Comment by naveedaz** [comment]
We do not have any plans of changing this property in the pay load AFAIK. What is the customer scenario on depending on the resourceGroup property to begin with? There are no official conventions for names of properties within the "properties" property. It really is up to the resource provider to define them. In fact, we should probably not expose it at all, since the resource group is already part of the resourceId.
