### ISSUE TITLE
Module AzureRM.BootStrapper: Design incorporating version schema to ProfileMap.json

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#3659]
Design adding a version schema to profilemap.json so that if there was any code changes in future, it doesn't break existing code. 

For example, if we make some code changes in the bootstrapper module and ship it, it shouldn't break already existing code. ProfileMap.json should have a schema version with which the bootstrapper module should decide which version it should work on.

**Comment by viananth** [comment]
Please assign it to @viananth

**Comment by cormacpayne** [comment]
@viananth is this issue still active?

**Comment by dingmeng-xue** [comment]
Close this old issue due to inactivity.
