### ISSUE TITLE
Get-AzureADGroup does not include email address

### ISSUE THREAD

**Issue by j82w** [Azure/azure-powershell#366]
Get-AzureADGroup -SearchString "test" has a Mail property that is always empty. I was able to verify that  Get-MsolGroup -SearchString "test" contained an email address. 

PS C:> $s = Get-AzureADGroup -SearchString "test"
PS C:> $s.Mail
PS C:> $s.DisplayName
test

**Comment by cormacpayne** [comment]
Closing this issue as `Get-AzureADGroup` is no longer a supported cmdlet. Please feel free to try the [`Get-AzureRmADGroup`](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Resources/Commands.Resources/help/Get-AzureRmADGroup.md) cmdlet and see if the problem has been resolved.
