### ISSUE TITLE
Switch-AzureRmWebAppSlot can't cancel a swap if the slot has been deleted [Need to support cancel Swap if a two phase swap is initiated]

### ISSUE THREAD

**Issue by AWahlqvist** [Azure/azure-powershell#3667]
### Cmdlet(s)
Switch-AzureRmWebAppSlot

### PowerShell Version
5.1.14393.953

### Module Version
AzureRM.WebSites 2.5.0

### OS Version
Azure Automation/Windows 10

### Description
Consider the following scenario:
1. You create a new slot
2. You initiate a swap with preview process (Switch-AzureRmWebAppSlot -SwapWithPreviewAction ApplySlotConfig)
3. The new slot get's deleted for whatever reason

You know have a "lingering" swap process. You can run "Switch-AzureRmWebAppSlot -SwapWithPreviewAction ResetSlotSwap" but it has no effect whatsoever (doesn't throw any errors though). Doesn't matter if you create a new slot with the same name as the old one. It does work if you cancel the swap before deleting the slot.

As long as it is in this state, a new swap (ApplySlotConfig) can't be ran.

If you cancel the swap in the Azure portal however, it works as expected and everything get's reset. Feels like the cmdlet should have the same effect.

### Debug Output
When attempting to run ApplySlotConfig again you get the following error:
"Cannot apply configuration from slot 'Production' because this slot has already been prepared for swap with slot '<slot name>'."

### Script/Steps for Reproduction
Create a new slot
New-AzureRmWebAppSlot

Initiate a swap with preview
Switch-AzureRmWebAppSlot -SwapWithPreviewAction ApplySlotConfig

Delete the slot
Remove-AzureRmWebAppSlot

Attempt to reset the ongoing swap
Switch-AzureRmWebAppSlot -SwapWithPreviewAction ResetSlotConfig

Create a new slot
New-AzureRmWebAppSlot

Initiate a swap with preview again, and it throws
Switch-AzureRmWebAppSlot -SwapWithPreviewAction ApplySlotConfig

**Comment by cormacpayne** [comment]
@Nking92 Hey Nicholas, would you mind taking a look at this issue?

**Comment by f000** [comment]
Same error here but I found something interesting:

If I initiate swap like this:

    Switch-AzureRmWebAppSlot -ResourceGroupName $group -Name $app -SourceSlotName $stage -DestinationSlotName $master -SwapWithPreviewAction ApplySlotConfig

then I expect this should work:

    Switch-AzureRmWebAppSlot -ResourceGroupName $group -Name $app -SourceSlotName $stage -DestinationSlotName $master -SwapWithPreviewAction ResetSlotSwap

but it doesn't. But if you use former DestinationSlotName as SourceSlotName, it works:

    Switch-AzureRmWebAppSlot -ResourceGroupName $group -Name $app -SourceSlotName $master -SwapWithPreviewAction ResetSlotSwap

**Comment by f000** [comment]
unfortunately that workaround doesn't work for the production slot:

    Switch-AzureRmWebAppSlot -ResourceGroupName example -Name example -SourceSlotName production -SwapWithPreviewAction ResetSlotSwap

Error:

The Resource 'Microsoft.Web/sites/example/slots/production' under resource group 'example' was not found.

**Comment by ebrucucen** [comment]
I had similar issue with the same error. I noticed the output of the command below was staging. 
```powershell
(Get-AzureRmWebApp -ResourceGroupName $ResourceGroupName -Name $WebAppName).TargetSwapSlot
``` 
Running `Switch-AzureRmWebAppSlot`  with `-SwapWithPreviewAction CompleteSlotSwap` cleared the TargetSwapSlot, and next time I could do `-SwapWithPreviewAction ApplySlotConfig` with a slot. Not an action to take in prod environment, but for dev environment solved the issue...

**Comment by jsheetzati** [comment]
It seems impossible at this point to cancel a swap through AzurePS. I am not deleting any slots between these steps.

`Switch-AzureRmWebAppSlot -Name $app.appName -ResourceGroupName $ResourceGroupName -SourceSlotName deploy -DestinationSlotName production -SwapWithPreviewAction ApplySlotConfig -verbose`

Then, I run:
`Switch-AzureRmWebAppSlot -Name $app.appName -ResourceGroupName $ResourceGroupName -SourceSlotName deploy -DestinationSlotName production -SwapWithPreviewAction ResetSlotSwap -verbose`

^ that command produces no errors.

If I then try the first command again, I get the error Cannot apply configuration from slot 'Production' because this slot has already been prepared for swap with slot 'deploy'.

I also see there is a pending swap in the Azure Portal even after running ResetSlotSwap.

**Comment by jsheetzati** [comment]
Is there an available work-around for this at the moment? If our swap fails for any reason in AzurePS, I have to go into the portal manually to reset it.

**Comment by panchagnula** [comment]
Closing this since there is not additional support at this point - please use the latest AZ PowerShell commandlets & file a new feature request if this is still needed.
