### ISSUE TITLE
Save-AzureRmProfile collides with the naming of AzureRm.BootStrapper cmdlets

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#3668]
### Cmdlet(s)
Save-AzureRmProfile

### Module Version
1.0.4.3 (AzureStack version)

### Description
Get-AzureRmProfile, Install-AzureRmProfile cmdlets are part of AzureRm.BootStrapper

Save-AzureRmProfile is part of AzureRm.Profile

The naming is  confusing

**Comment by bganapa** [comment]
cc:@markcowl

**Comment by sphibbs** [comment]
Fixed in 3.8
