### ISSUE TITLE
Azure PS module directory is not included in $env:PSModulePath

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#3669]
### PowerShell Version
V5

### Module Version
1.2.9 (azurestack version)
### OS Version
Windows server 2016 data center

### Description

After installing the MSI , we see that Azure PS module directory is not included in $env:PSModulePath
We are in need of explicitly loading the modules  specifying the full path

As @markcowl  mentioned the work aoround is to restart the powershell windows as administrator , in worst case restart the machine.

Filing this issue to keep track , this may be a duplicate( I cannot find)

**Comment by cormacpayne** [comment]
This will be cleared as a part of the msi cleanup.

**Comment by cormacpayne** [comment]
Closing this issue in favor of https://github.com/Azure/azure-powershell/issues/2220
