### ISSUE TITLE
Module Bootstrapper: checking for the presence of the modules from the msi installer

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#3671]
### Cmdlet(s)
Uninstall-AzureRmProfile

### PowerShell Version
5

### Module Version
0.1.0

### Description
If Azure Modules were installed using MSI installer, uninstalling via PowerShell console will throw error "No module found that matches the criteria". Uninstall-AzureRmProfile should detect this scenario and provide a friendly error message like "Uninstall using MSI"

**Comment by viananth** [comment]
@viananth to work on it.

**Comment by viananth** [comment]
`Uninstall-AzureRmProfile `will attempt to uninstall a module only if it finds it installed (using `get-module`). So "No module found" error means uninstallation failed due to some other reason, not because it's not found. As per discussion with Igor, the error message should be something like "Unable to uninstall module as we did not install it". This covers all the scenarios including modules installed using msi, modules installed manually, modules installed in user-chosen folders, etc.

**Comment by markcowl** [comment]
Fixed.
