### ISSUE TITLE
Update-ModuleManifest didn't work as expected.

### ISSUE THREAD

**Issue by neetus15** [Azure/azure-powershell#3673]
### PowerShell Version
 5.1.14409.1005
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
10.0.14409.1005
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
I added some new cmdlets to an existing project but even after running Update-ModuleManifest multiple times, newly added cmdlets didn't show up in Azure.psd1. I finally removed the "CmdletsToExport section" from Azure.psd1 and ran the Update-ModuleManifest again. Then it worked. 
Can someone please take a look at why didn't it work earlier?
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
a) Add any new cmdlet to src/ServiceManagement/*
b) Run build and then Update-ModuleManifest
c) Look for the cmdlet.. It didn't show up for me
d) Remove "CmdletsToExport" section from Azure.psd1 and then ran "Update-ModuleManifest" again
This time cmdlet showed up.

**Comment by markcowl** [comment]
WIll be resolved in #3695
