### ISSUE TITLE
No ability to set "Slot Setting" flag for app settings in Set-AzureRmWebApp

### ISSUE THREAD

**Issue by jskii** [Azure/azure-powershell#3675]
### Cmdlet(s)
Set-AzureRmWebApp

### PowerShell Version
PSVersion 5.1.14393.693

### Module Version
Azure Powershell 3.7.0 release

### OS Version
BuildVersion 10.0.14393.693

### Description
There appears to not be an option for setting the toggle "Slot Setting" on application settings in the Azure Web Apps through AzureRM powershell.  It would be nice to have that option.

### Debug Output
N/A

### Script/Steps for Reproduction
1.  Use Set-AzureRmWebApp.

**Comment by jskii** [comment]
This is blocking the use of our production workflow, and it would be really nice if somebody from the team could look into whether we're doing something wrong, or a possible workaround.  Thank you!

**Comment by cormacpayne** [comment]
@Nking92 Hey Nicholas, would you mind taking a look at this issue?

**Comment by AWahlqvist** [comment]
This functionality is available using [Set-AzureRmWebAppSlotConfigName](https://docs.microsoft.com/en-us/powershell/resourcemanager/azurerm.websites/v2.1.0/set-azurermwebappslotconfigname).

Just add all the app settings (names) you want to make "slot-sticky" as an array in the AppSettingNames-parameter and you're done.

**Comment by jskii** [comment]
@AWahlqvist so would the desired path be to configure the settings using Set-AzureRmWebApp, and then run them through Set-AzureRmWebAppSlotConfigName afterwards?  Thanks for your help on this.

**Comment by AWahlqvist** [comment]
You can do it either way AFAIK. I haven't done extensive testing on this but I know you can:
First add the name of the app setting you want sticky using Set-AzureRmWebAppSlotConfigName (it doesn't validate if the setting actually exists or not, which I think is deliberate for this scenario), and then create the actual setting using Set-AzureRmWebApp and it will become "slot sticky" right away.

or

The opposite, create the setting using Set-AzureRmWebApp and then make it slot sticky after the fact as you described.

Pseudocode (haven't tested it):

`$ResourceGroup = 'MyResourceGroup'`
`$WebApp = 'MyWebApp'`

<# Fetch current sticky settings #>
`$CurrentStickyConfig = Get-AzureRmWebAppSlotConfigName -ResourceGroupName $ResourceGroup -Name $WebApp`

<# Add another one #>
`$NewStickyConfig = $AppSettings.AppSettingNames + 'MyNewStickySetting'`

<# Update sticky settings #>
`Set-AzureRmWebAppSlotConfigName -ResourceGroupName $ResourceGroup -Name $WebApp -AppSettingNames $NewStickyConfig`

<# Get current config #>
`$CurrentConfig = Get-AzureRmWebApp -ResourceGroupName $ResourceGroup -Name $WebApp`

<# Create a new hashtable with all settings #>
`$hashAppSettings = @{}`
`$CurrentConfig.SiteConfig.AppSettings | % { $hashAppSettings.Add($_.Name, $_.Value) }`

<# Add the new setting to the hashtable #>
`$hashAppSettings.Add('MyNewStickySetting','MySettingValue')`

<# Write it back #>
`Set-AzureRmWebApp -AppSettings $hashAppSettings -ResourceGroupName $ResourceGroup -Name $WebApp`

I think that should do what you're after, but it might be a good idea to test it in a safe environment first :-)

Happy I could help!

**Comment by jskii** [comment]
Perfect.  I'll close this issue for now to get it out of the list, and if something misbehaves or needs follow up, I will reopen a ticket.  Thanks again!

**Comment by yatesy** [comment]
@AWahlqvist How do you make a setting that is on a slot (non "production") on a webapp have a sticky setting?  The Set-AzureRmWebAppSlotConfigName only ever accesses the "production" slot. 

I can add the setting no problem with the Set-AzureRmWebAppSlot but it won't be sticky.

**Comment by AWahlqvist** [comment]
@yatesy When you add the name of a sticky setting using Set-AzureRmWebAppSlotConfigName that setting will become sticky on all slots, including the production slot. You are just adding the name of the setting though so you will manage/add the settings using Set-AzureRmWebAppSlot as usual.

Are you sure the name matches exactly? Also, if you check this through the Azure portal, make sure you refresh the page and clear the browser cache since it can sometimes "lag behind" a bit.
