### ISSUE TITLE
No HostNames parameter for Set-AzureRmWebAppSlot

### ISSUE THREAD

**Issue by makhdumi** [Azure/azure-powershell#3679]
`Set-AzureRmWebApp` has a HostNames parameter.
`Set-AzureRmWebAppSlot` does not.

Please consider adding it. It defeats the purpose of having these cmdlets if we have to call `Set-AzureRmResource` for everything.

I'd imagine this is a very common scenario when provisioning new Web Apps. See:
http://stackoverflow.com/questions/42209472/azurerm-powershell-how-to-set-a-custom-domain-onto-a-web-app-deployment-slot

**Comment by makhdumi** [comment]
This isn't actually an issue, because HostNames aren't specific to slots.

**Comment by Leon99** [comment]
@makhdumi what do you mean? I can certainly set different hosts for different slots of one web app. In fact, the post linked from the OP shows a workaround for it.
