### ISSUE TITLE
Get-AzureRmADApplication Access denied to the specified API version

### ISSUE THREAD

**Issue by xingyu217** [Azure/azure-powershell#3686]
VSTS Azure PowerShell step run Get-AzureRmADApplication, it throws {"odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"Access denied to the specified API version."}}}.
I found similar issue [New-AzureRmADApplication: Access denied to the specified API version](https://github.com/Azure/azure-powershell/issues/1896), but it closed without solution.

**Comment by cormacpayne** [comment]
@shuagarw Hey Shubham, would you mind taking a look at this issue?

CC @RBACAsk

**Comment by cormacpayne** [comment]
Closing this issue as it appears this issue has been resolved according to https://github.com/Azure/azure-powershell/issues/1896. Please feel free to re-open this issue if that is not the case.

**Comment by Akshat59** [comment]
facing same issue. ho to resolve this [#1896](https://github.com/Azure/azure-powershell/issues/1896) did not helped
