### ISSUE TITLE
Start-AzureRmVM - Start VMs in Parallel

### ISSUE THREAD

**Issue by randomnote1** [Azure/azure-powershell#3687]
### Cmdlet(s)
Start-AzureRmVM

### PowerShell Version
5.1.15063.0

### Module Version
2.8.0

### OS Version
10.0.15063.0

### Description
It would be nice if Start-AzureRmVM could start VMs in parallel. This could be accomplished in one of a few ways:

- Add a wait parameter to the command similar to Restart-Computer.
- Have the Name parameter accept a string array and process the supplied VM names in parallel.

### Debug Output
N/A

### Script/Steps for Reproduction
Get-AzureRmVM -ResourceGroupName ResourceGroup1 | Start-AzureRmVM

**Comment by shahabhijeet** [comment]
@signhkays this is a feature request. I will let you comment on this one.

**Comment by markcowl** [comment]
@singhkays Can you take a look and assess whtehter this is a feature we will consider?

**Comment by singhkays** [comment]
@randomnote1 Thanks for the suggestion, I've forwarded it to the VM owner for considering this. In the meantime, I'd suggest looking into implementing this yourself using PowerShell Jobs/Runspaces if you haven't already.

**Comment by cormacpayne** [comment]
@randomnote1 Hey Dan, as of Azure PowerShell 4.4.0, we now support using jobs for AzureRM cmdlets, so you would be able to run these cmdlets in parallel ([here are the docs](https://docs.microsoft.com/en-us/powershell/azure/context-persistence?view=azurermps-4.4.0)). For now, I am going to close this issue; please feel free to re-open the issue if there is additional functionality that you are looking for.

**Comment by randomnote1** [comment]
Thanks for following up! I'll check it out.

**Comment by mrichman** [comment]
I do something like this:

```powershell
$customerId = "123456"
$vms = "ad1","sql1","nfs1","cts1","vpx1"
$resourceGroupName = "$($customerId)-prod"

# Start VMs in parallel

foreach($vm in $vms) {
    Start-Job -ScriptBlock { Start-AzureRmVM -Name "$($customerId)$($vm)" -ResourceGroupName $resourceGroupName }
}
```

**Comment by aluitink** [comment]
> I do something like this:
> 
> ```powershell
> $customerId = "123456"
> $vms = "ad1","sql1","nfs1","cts1","vpx1"
> $resourceGroupName = "$($customerId)-prod"
> 
> # Start VMs in parallel
> 
> foreach($vm in $vms) {
>     Start-Job -ScriptBlock { Start-AzureRmVM -Name "$($customerId)$($vm)" -ResourceGroupName $resourceGroupName }
> }
> ```

@mrichman you can also use -AsJob param and a job will be created for you.

`Start-AzureRmVM -ResourceGroupName $resourceGroup -Name $_.Name -AsJob`
