### ISSUE TITLE
Get-AzureRmHDInsightJobOutput issue 

### ISSUE THREAD

**Issue by shenhaizhilong** [Azure/azure-powershell#3688]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### Module Version

HDInsight 2.7/2.6 
### Description
when I execute this cmd in Mooncake, I got below error. 

### Debug Output
profile": {
    "user": "admin",
    "jobFile": "wasb://huihdoop-2017-03-29t07-41-13-873z@test.blob.core.chinacloudapi.cn/mr-history/done/2017/03/29/000000/job_1490774023631_0004_conf.xml",
    "url": null,
    "queueName": "default",
    "jobID": {
      "id": 4,
      "jtIdentifier": "1490774023631"
    },
    "jobName": "TempletonControllerJob",
    "jobId": "job_1490774023631_0004"
  },
  "id": "job_1490774023631_0004",
  "parentId": null,
  "percentComplete": null,
  "exitValue": 255,
  "user": "admin",
  "callback": null,
  "completed": "done",
  "userargs": {
    "statusdir": "2017-03-29T11-03-02-00a0639d-283e-42d3-adec-b8fdb7781ebd",
    "enablejobreconnect": null,
    "arg": [
      "wasb:///example/data/gutenberg/davinci.txt",
      "wasb:///example/data/WordCountOutput"
    ],
    "define": [],
    "enablelog": "false",
    "user.name": "admin",
    "libjars": null,
    "files": null,
    "callback": null,
    "jar": "wasb:///example/jars/hadoop-mapreduce-examples.jar",
    "class": "wordcount"
  },
  "msg": null
}

Get-AzureRmHDInsightJobOutput : The remote name could not be resolved: 'test.blob.core.windows.net'
At line:1 char:1
+ Get-AzureRmHDInsightJobOutput -ClusterName $clusterName -JobId $wordC ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmHDInsightJobOutput], StorageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.HDInsight.GetAzureHDInsightJobOutputCommand
 
DEBUG: 8:41:10 PM - GetAzureHDInsightJobOutputCommand end processing.
DEBUG: 8:41:10 PM - GetAzureHDInsightJobOutputCommand end processing.

### Script/Steps for Reproduction
E:\azure-powershell-dev\src\packages\Microsoft.Azure.Management.HDInsight.Job.2.0.3\lib\net40\Microsoft.Azure.Management.HDInsight.Job.dll

		private CloudBlobClient GetStorageClient()
		{
			return new CloudStorageAccount(new StorageCredentials(this.StorageAccountName.Contains(".") ? this.StorageAccountName.Substring(0, this.StorageAccountName.IndexOf('.')) : this.StorageAccountName, this.StorageAccountKey), true).CreateCloudBlobClient();
		}

I think you should use  public CloudStorageAccount(StorageCredentials storageCredentials, string endpointSuffix, bool useHttps);

**Comment by shenhaizhilong** [comment]
@cormacpayne  @shefaliv   any  progress?

**Comment by shefaliv** [comment]
This is assigned to @epkalyanr.

**Comment by cormacpayne** [comment]
@epkalyanr any update on this issue?

CC: @momusoru @z01c @wawon-msft

**Comment by idear1203** [comment]
Hi @shenhaizhilong , Blob storage suffix is different between China cloud and Global cloud. For China cloud, the suffix is ".blob.core.chinacloudapi.cn" while for Global cloud the suffix is ".blob.core.windows.net". For this specific issue, somehow the PowerShell uses the Global cloud by mistake. We have tested the latest PowerShell release and the issue does not exist now. Please have a try and let us know if the issue still exists.
