### ISSUE TITLE
 Login-AzureRmAccount  interactive doesn't work on windows server R8

### ISSUE THREAD

**Issue by nwarriorch** [Azure/azure-powershell#3698]
### PowerShell Version
3.0
### Module Version
3.7.0
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
6.2.9200.16481
### Description
Interactive Login does not work. Login seems successful but power shell doesn't login. 

### Debug Output
Login-AzureRmAccount : Service returned error. Check InnerException for more details: The underlying connection was
closed: An unexpected error occurred on a receive.
At line:1 char:1
+ Login-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

**Comment by jskii** [comment]
@nwarriorch have you tried logging in using Add-AzureRMAccount?  Does that give the same behavior?

**Comment by nwarriorch** [comment]
Yep. Similar error. 

Add-AzureRMAccount : Service returned error. Check InnerException for more details: The underlying connection was
closed: An unexpected error occurred on a receive.
At line:1 char:2
+  Add-AzureRMAccount
+  ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

**Comment by markcowl** [comment]
@nwarriorch Can you please try lexecuting the cmdlet with ```$DebugPreference="Continue"``` this will print additoona;l debugging information that will help diagnose the issue.

**Comment by nwarriorch** [comment]
It seems to be because we have disabled TLSv1.1 and TLSv1.0.

**Comment by markcowl** [comment]
@nwarriorch Closing as expected behavior, then, this is about the behavior of your eSTS and not the cmdlet itself.
