### ISSUE TITLE
New-AzureKeyVaultCertificatePolicy ignores KeyUsage

### ISSUE THREAD

**Issue by rohmano** [Azure/azure-powershell#3702]
### Cmdlet(s)
New-AzureKeyVaultCertificatePolicy

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
New-AzureKeyVaultCertificatePolicy ignores KeyUsage provided to it
KeyUsage is not set when creating a policy object - https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/KeyVault/Commands.KeyVault/Commands/NewAzureKeyVaultCertificatePolicy.cs
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@pomortaz Hey Pooneh, would you mind taking a look at this issue?

**Comment by maddieclayton** [comment]
Fixed.
