### ISSUE TITLE
A problem with Switch-AzureMode in PowerShell ISE

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#371]
I'm using Azure PowerShell 0.9.0 on the latest Windows 10 TP. (The issue is also confirmed on Windows 8.1 with Azure PowerShell 0.9.1)
  
 If I open powershell.exe and run Get-Module Azure -ListAvailable, I get expected result and details about Azure module.
 And then, I open another powershell.exe and run Switch-AzureMode AzureResourceManager command there switching to Resource Manager mode and loading AzureResourceManager in that session.
 When I return to my first powershell.exe console and run Get-Module Azure -ListAvailable again, I get details about Azure module, because that session is not affected by changes in other powershell.exe session.
  
 That's expected behavior.
  
 Let's move to PowerShell ISE now.
  
 I will run Get-Module Azure -ListAvailable in default PowerShell tab and get expected details about Azure module.
 And then, I will open new PowerShell tab (which is a new PowerShell runspace unaware of the first tab) and run Switch-AzureMode AzureResourceManager.
 When I return to my first tab, Azure module is not loaded there anymore and Get-Module Azure -ListAvailable returns nothing because now AzureResourceManager module is loaded thanks to the command from the second PowerShell tab.
  
 That's not expected behavior. And I cannot recall that it worked like that before.

**Comment by devigned** [comment]
Agreed. As of 0.9.2 switch azure mode has been marked for deprecation. Please follow #428 to get more information regarding this transition.

We are aware of stateful activities which cause issues across powershell sessions and will be eliminating them in future releases.
