### ISSUE TITLE
Azure Automation Account

### ISSUE THREAD

**Issue by yermakovv** [Azure/azure-powershell#3716]
Hi I saw you solved issue from here 

https://github.com/darkoperator/Posh-SSH/issues/43

Can you help me with it, I alweys get a same error

New-SSHSession : Session operation has timed out
At line:20 char:15
+ ... shSession = New-SSHSession -ComputerName "40.71.216.**" -Port 22 -Cre ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationTimeout: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], 
SshOperationTimeoutException
    + FullyQualifiedErrorId : SSH.NewSshSession
 
Invoke-SSHCommand : Cannot process command because of one or more missing mandatory parameters: SessionId.
At line:27 char:1
+ Invoke-SshCommand -Command "mkdir one"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-SSHCommand], ParameterBindingException
    + FullyQualifiedErrorId : MissingMandatoryParameter,Invoke-SSHCommand

$sshSession = New-SSHSession -ComputerName "40.71.216.**" -Port 22 -Credential $mycreds -ConnectionTimeout 30 -AcceptKey -Verbose

Invoke-SshCommand -Command "mkdir testdir"

**Comment by cormacpayne** [comment]
@yermakovv the cmdlets `Invoke-SSHCommand` and `New-SSHCommand` that you mentioned are not located in this repository - they can be found in the [Posh-SSH repository](https://github.com/darkoperator/Posh-SSH).

Please feel free to open an issue in the `Posh-SSH` repository with this information.
