### ISSUE TITLE
Remove-AzureVNetConfig doesn't has -VNetName Parameter

### ISSUE THREAD

**Issue by SherifTalaat** [Azure/azure-powershell#372]
Although, Set-AzureVNetConfig can create one or more virtual network(s) at a time according to the network configuration file, Remove-AzureVNetConfig cmdlet removes all the virtual networks under a specific subscription one shot. This is not logical because I might need to remove a specific virtual network not all of them. Therefore, I suggest adding -VNetName parameter to specify the name of the vNet the user wants to remove.

Cheers,
Sherif Talaat
PowerShell MVP

**Comment by pcgeek86** [comment]
Sherif,

This is good feedback. There is definitely a gap for managing virtual networks. However, I would like to make a point of clarification. 

The *AzureVNetConfig commands are used to manage the VNet config (XML file). There is only one command that allows you to "manage" virtual networks using an object oriented approach. That command is called `Get-AzureVNetSite`. Keeping consistency with this existing command, I would expect that we would have commands such as:

- `Set-AzureVNetSite`
- `Remove-AzureVNetSite`

While it would be nice to have these out of box, you will probably need to write them yourself. Microsoft is focusing their efforts on the new Azure Resource Manager (ARM) API. In fact, the Compute Resource Provider (CRP) and Network Resource Provider (NRP) were recently released in the 0.9.0 module. You will want to use these new commands going forward.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markjbrown** [comment]
Echoing Trevor's comments. We are not going to add new features to ASM and are focusing efforts on building out ARM functionality and fidelity.
