### ISSUE TITLE
New-AzureRmAutomationAccount

### ISSUE THREAD

**Issue by ronbok** [Azure/azure-powershell#3721]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `5.1.14393.953`

Can we get some consistency on the naming of resources both in the Portal UI and in PowerShell? Often you can create things in PowerShell that won't validate in the Portal UI. Worse there's no consistency between resources with respect to naming. When a resource doesn't require a public endpoint (i.e Https) and doesn't require a global DNS entry we should be allowed to name our resources what we want.

For example creation of an Azure Automation Account...I should be able to name one 'QA' without issue, but no...why the arbitrary 6 character minimum?  I should also be able to create one named 'Test' to match our Resource Group naming standards.

Also the -Tags parameter is wrong on this cmdlet.  It should be -Tag not -Tags.

Azure PowerShell v3.6.

**Comment by shahabhijeet** [comment]
@ronbok -Tag is getting across all RPs.
regarding account names, this is a restriction across all resource names in azure.
If you are asking to have consistency across service and client tools, we have taken the approach to let service dictate and avoid adding more validation at the client level (in case things change from service side)
Closing as there isn't anything powershell team can do for this.
