### ISSUE TITLE
Unable to work Get-AzureRmRecoveryServicesBackupJob in Powershell

### ISSUE THREAD

**Issue by intotskie** [Azure/azure-powershell#3725]
### Cmdlet
Get-AzureRmRecoveryServicesBackupJob

### PowerShell Version
5

### Modules Version
| ModuleType  | Version | Azure | 
| ------------- | ------------- | ------------- |
| Manifest | 1.2.3 | Azure |
| Script | 2.7.0 | AzureRM.profile |
| Script | 2.7.0 | AzureRM.RecoveryServices |
| Script | 2.7.0 | AzureRM.RecoveryServices.Backup |
| Manifest | 3.1.0.0 | Microsoft.PowerShell.Management |
| Manifest | 3.1.0.0 | Microsoft.PowerShell.Utility |
| Binary | 1.0.0.1 | PackageManagement |
| Script | 1.0.0.1 | PowerShellGet |
| Script | 1.2 | PSReadline |

### OS Version
Windows 10

### Description
I can't seem to get **Get-AzureRmRecoveryServicesBackupJob** to work in `Powershell`. 
But sometimes it works.

### Error Output
```
Get-AzureRmRecoveryServicesBackupJob : Your Azure credentials have not been set up or have expired, please run Login-AzureRMAccount to set up your Azure credentials.
At line:1 char:1
+ Get-AzureRmRecoveryServicesBackupJob
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmRecoveryServicesBackupJob], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.GetAzureRmRecoveryServicesBackupJob
```

### Code
```
Import-Module Azure
Install-Module AzureRM
#Get-AzureAccount | %{Remove-AzureAccount -Name $_.Id}
Clear-AzureProfile -Force
Add-AzureRMAccount

ForEach ($vault in $(Get-AzureRmRecoveryServicesVault)) {
  write-host " *" $vault.Name
  # set vault context
  Get-AzureRmRecoveryServicesVault -Name $vault.Name | Set-AzureRmRecoveryServicesVaultContext
  
  # step through all jobs found
  ForEach ($job in $(Get-AzureRmRecoveryservicesBackupJob)) {
    write-host " *" $job.WorkloadName
  }
}
```

**Comment by shahabhijeet** [comment]
@intotskie as you mentioned that this does work sometimes. Could you do the following:
1) Could you try with the latest release of Azure PowerShell 3.8.0

**Comment by intotskie** [comment]
For now I am not getting the error. I don't know what is the cause of the issue. But will get back if the error occurs.
