### ISSUE TITLE
New-AzureResourceGroupDeployment supports file share paths

### ISSUE THREAD

**Issue by clamanna** [Azure/azure-powershell#373]
It would be great if the Cmdlet could accept the file share paths as well. Can we look into supporting this capability through PowerShell? 
 
New-AzureResourceGroupDeployment -Name Dep1 -ResourceGroupName ScalableWebTier -TemplateParameterFile "\\cloudguy-lenovo\DeploymentScripts\ScaleDemo\azuredeploy-parameters.json" -TemplateFile "\\cloudguy-lenovo\DeploymentScripts\ScaleDemo\azuredeploy.json

-AzureResourceGroupDeployment : The given path's format is not supported.
At line:1 char:1
+ New-AzureResourceGroupDeployment -Name Dep1 -ResourceGroupName ScalableWebTier - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureResourceGroupDeployment], NotSupportedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand
  
 
![image](https://cloud.githubusercontent.com/assets/894674/7520824/8282dc0e-f49e-11e4-8749-328de2ea7fbc.png)

**Comment by ravbhatnagar** [comment]
Investigate if this is an easy fix.

**Comment by ravbhatnagar** [comment]
Fixed for the June release of Azure PS.
