### ISSUE TITLE
Test-AzureRmResourceGroupDeployment validation error when array has a single element

### ISSUE THREAD

**Issue by sabbadino** [Azure/azure-powershell#3736]
### Cmdlet(s)
Test-AzureRmResourceGroupDeployment
### PowerShell Version
  5.1.15063.0
### Module Version
(get-module  AzureRM.Resources).Version
3      4      0      -1
### OS Version
  10.0.15063.0
### Description
Given this parameter
 "parameters": {
        "subscribers": {
            "value": [
                {
                    "name": "monitoringSubscription",
                    "filterName": "Filter1",
                    "filterValue": "1=1",
                    "bulkfilterName": "Filter1bulk",
                    "bulkfilterValue": "1=1"
                }
                ,
                {
                    "name": "monitoringSubscription2",
                    "filterName": "Filter1",
                    "filterValue": "1=0",
                    "bulkfilterName": "Filter1bulk",
                    "bulkfilterValue": "1=0"
                }
            ]
        },

and this piece of template 
copy": {
                "name": "subscribersCopyLive",
                "count": "[length(parameters('subscribers'))]"
            },
            "apiVersion": "[variables('sbVersion')]",
            "name": "[concat(parameters('serviceBusNamespaceName'),'/',parameters('topicNameMain'),'/', parameters('subscribers')[copyIndex()].name)]",
            "type": "Microsoft.ServiceBus/namespaces/Topics/Subscriptions",

It works fine, 
but if I change parameter to this : ONLY ONE ELEMENT

 "parameters": {
        "subscribers": {
            "value": [
                {
                    "name": "monitoringSubscription",
                    "filterName": "Filter1",
                    "filterValue": "1=1",
                    "bulkfilterName": "Filter1bulk",
                    "bulkfilterValue": "1=1"
                }
            
            ]
        },

I GET : 
### Debug Output
 Validation returned the following errors:
15:19:15 - : Deployment template validation failed: 'The template resource '[concat(parameters('serviceBusNamespaceName'),'/',parameters('topicNameMain'),'/', parameters('subscribers')[copyIndex()].name)]' at line '42' and column '10' is not valid: The language expression property 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Expression.Expressions.JTokenExpression' can't be evaluated.. Please see https://aka.ms/arm-template-expressions for usage details.'.
15:19:15 -

**Comment by cormacpayne** [comment]
@ravbhatnagar Hey Gaurav, would you mind taking a look at this issue?

**Comment by sabbadino** [comment]
Well, it turns out I did not actually removed the second item .. but I just commented it out .. (using vs studio editor) .. and this was the reason of the error. 
Enrico

**Comment by jfuller28495** [comment]
I'm getting this issue, but all mention of a copy or second instance of an object have been removed. I'm not sure what I'm doing wrong. Error message below:


Unable to process template language expressions for resource '/subscriptions/<subscriptionID>/resourceGroups/<resourceGroupName>/providers/Microsoft.Web/sites/<webappname>/hostnameBindings/<customDomainName>' 
at line '156' and column '10'. 'The language expression property 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Expression.Expressions.JTokenExpression' can't be evaluated.'"
  }

Any help would be appreciated!

**Comment by cormacpayne** [comment]
@jfuller28495 if you're still seeing this issue, please file a new issue, filling out the provided issue template with the information requested
