### ISSUE TITLE
Module AzureRM.Bootstrapper: Profile returned from Get-AzureRmProfile should be piped to other cmdlets

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#3739]
### Cmdlet(s)
Get-AzureRmProfile, Update-AzureRmProfile, Use-AzureRmProfile, Uninstall-AzureRmProfile

### PowerShell Version
5

### Module Version
0.1.0

### Description
Get-AzureRmProfile should return profile object that can be consumed by Update, Use & Uninstall cmdltes through piping.

### Script/Steps for Reproduction
Example usage:
Get-AzureRmProfile | Uninstall-AzureRmProfile
Get-AzureRmProfile | Update-AzureRmProfile

**Comment by viananth** [comment]
@markcowl

**Comment by maddieclayton** [comment]
@viananth Is this completed? If not, do you have an estimated date for when this will be done?

**Comment by viananth** [comment]
@maddieclayton Its not completed yet. We might move this to end of August. Thanks!
