### ISSUE TITLE
NetCore conversion for core modules

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3746]
### Description

Move core set of modules to build side-by-side in .Net Core and .Net Desktop.  Core modules include:

- [x] Profile
- [x] Resource Manager
- [x] Storage Management (not data plane)
- [x] Websites
- [x] Compute
- [x] Network
- [ ] Sql
- [ ] Storage Data
- [x] KeyVault
- [ ] Batch
- [x] Automation

The work should begin with updating the psm1 module definition to allow loading necessary DLLs:.  A sample of additional assembly loading code is here: https://github.com/markcowl/azure-powershell-pr/blob/pscore20160816/src/ResourceManager/Profile/Microsoft.Azure.Commands.Profile/Account/AddAzureRmAccount.cs#L183  along wit source for working modules for profile and resource manager.

PowerShell Core source is here: https://github.com/powershell/powershell 

Downloads are included on the README.  We will need to discuss which particular version to target.

Some steps include:

- [x] Determine the core assemblies in powershell for netcore - some assmblies will be loaded in the AppDomain for you, including Newtonsoft.Json, System.Runtime.Serialization.Json (used by ADAL).
- [x] Change module projects to use VS2017 and build side-by-side with desktop modules
- [x] Run tests manually for first versions
- [x] Target test core projects to run in netcoreapp 1.1
- [x] Set up Jenkins, Travis, or AppVeyor builds for net core powershell tests, including signing builds

**Comment by janegilring** [comment]
Could you share the long term plan for the side by side strategy? For example, will the .Net Desktop based modules be deprecated when PS Core is released and the AzureRM.NetCore modules has feature parity with the AzureRM modules?

**Comment by markcowl** [comment]
- [ ] Update xunit tests for runnign in core when new PowerShell runtime modules available
- [ ] Create tools and docs for adding NetCore infrastructure for new modules
- [ ] Create schedule and file issues for remaining legacy modules into NetCore

**Comment by cormacpayne** [comment]
AzureRM.Netcore 0.10.0 has been released and can be found here: https://github.com/Azure/azure-powershell/releases/tag/v0.10.0-nc-February2018

**Comment by MiYanni** [comment]
Automation covered here: https://github.com/Azure/azure-powershell/pull/5718

**Comment by MiYanni** [comment]
The rest covered here: https://github.com/Azure/azure-powershell/pull/5782
