### ISSUE TITLE
Service Principle

### ISSUE THREAD

**Issue by gangadhar01a** [Azure/azure-powershell#3747]
### Cmdlet(s)
I am using Azure CLI from powershell and able to log into azure account using service principle, this avoids me to access account interactively.
Can I get the same functionality using Azure-powershell?
We run most of the Azure scripts using Rundeck which runs the Azure scripts without user intervention. Therefore, it's significant for me to access Azure account and run the commands/scripts through powershell (Avoiding interactive login)

Thanks.
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@gangadhar01a there are a few of parameter sets for `Add-AzureRmAccount` that allow you to login using a service principal (with or without a certificate, and with or without a subscription name/ID)

[Here is an example from the help for `Add-AzureRmAccount` showing how to use service principal to login](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Profile/Commands.Profile/help/Add-AzureRmAccount.md#example-3-add-an-account-that-authenticates-with-service-principal-credentials)

Let me know if that answers your question!
