### ISSUE TITLE
Get-AzureRmTrafficManagerProfile does not expose tags / Unable to add tags to Traffic Manager Profiles

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#3751]
### Cmdlet(s)
Get-AzureRmTrafficManagerProfile 

### PowerShell Version
5.0.10586.117

### Module Version
2.7.0

### OS Version
10.0.10586.117

### Description
1. Get-AzureRmTrafficManagerProfile does not expose tags.
2. Adding tags from the portal does not work for Traffic Manager Profiles.
3. Set-AzureRmTrafficManagerProfile, do not have tags parameter exposed.

PS C:\Windows\system32> Get-AzureRmTrafficManagerProfile -Name "sample" -ResourceGroupName sample -Verbose
VERBOSE: Success!

Id                   : /subscriptions/Hidden/resourceGroups/sample/providers
                       /Microsoft.Network/trafficManagerProfiles/sample
Name                 : sample
ResourceGroupName    : sample
RelativeDnsName      : sample
Ttl                  : 30
ProfileStatus        : Enabled
TrafficRoutingMethod : Performance
MonitorProtocol      : HTTPS
MonitorPort          : 443
MonitorPath          : /Ping/EndPointMonitor
Endpoints            : {nothing}

**tags** are not exposed.
### Script/Steps for Reproduction

Set-AzureRmTrafficManagerProfile - does not have tags to set
Get-AzureRmTrafficManagerProfile - does not expose tags
Seems tags are not implemented in TrafficManager Profiles.

**Comment by cormacpayne** [comment]
@vladca Hey Vlad, would you mind taking a look at this issue?

**Comment by Pradebban** [comment]
@cormacpayne , @markcowl  - is there any update on this pls

**Comment by EvgenyAgafonchikov** [comment]
@dilukose, could you please update there or re-assign?

**Comment by dilukose** [comment]
@Praburaj

**Comment by MikhailTryakhov** [comment]
@rohinkoul can't assign you as assignee..
@MiYanni can you please help to add Rohin to appropriate group to make him able to assign tasks on him

**Comment by rohinkoul** [comment]
@rajaprad This looks like an old issue. We tried to repro this but couldn't. Could you try again and see if this works on the latest PS version.

**Comment by MikhailTryakhov** [comment]
Asked to retry. please reopen if it's reproduced with more context
