### ISSUE TITLE
Get-AzureRmStorageAccountKey

### ISSUE THREAD

**Issue by lonnieherring** [Azure/azure-powershell#3753]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
PSVersion 5.1.14393.206
 PSEdition Desktop
 PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
 BuildVersion 10.0.14393.206
 CLRVersion 4.0.30319.42000
 WSManStackVersion 3.0
 PSRemotingProtocolVersion 2.3
 SerializationVersion 1.1.0.1

### OS Version
Windows Server 2016

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
Login-AzureRmAccount
Get-AzureRmStorageAccountKey -Name <StorageAccount> -ResourceGroupName <ResourceGroup>

**Comment by lonnieherring** [comment]
Cmdlets Get-AzureRmStorageAccountKey
PowerShell Version
Name                           Value                   
----                           -----                   
PSVersion                      5.1.14393.206           
PSEdition                      Desktop                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...} 
BuildVersion                   10.0.14393.206          
CLRVersion                     4.0.30319.42000         
WSManStackVersion              3.0                     
PSRemotingProtocolVersion      2.3                     
SerializationVersion           1.1.0.1                 

Cannot reproduce error right now because I uninstalled 2.8 and reinstalled 2.6 but it was telling me to Run: Login-AzureRmAccount and no account I used worked Microsoft or domain.  2.6 still works.

**Comment by cormacpayne** [comment]
@lonnieherring would you mind installing the latest version of Azure PowerShell and try to repro this error? When you do, please set `$DebugPreference="Continue"` so we are able to get the debug output from the calls

**Comment by sphibbs** [comment]
@lonnieherring can you run get-module -listavailable. It appears you have multiple versions of the profile module so you could have a dependency mismatch.

**Comment by markcowl** [comment]
Closing for lack of response.  Please reopen if you see a recurrence
