### ISSUE TITLE
JsonADDomainExtension cannot join domain, Error code 1332

### ISSUE THREAD

**Issue by guillemsola** [Azure/azure-powershell#3757]
### Cmdlet(s)
Set-AzureRMVMExtension

### PowerShell Version
5.1.14393.953

### OS Version
10.0.14393.953

### Description
I have an VNet with a DC server and I'm creating new VM that I want to join to the domain. The machine creation has nothing in particular but is attached to this case. [template.json.txt](https://github.com/Azure/azure-powershell/files/916286/template.json.txt)

I have tried also to join the domain from the JSON template but the same error is happening.

If I login to the 2012 server and I do a clasic "Add-Computer -DomainName "App.local" -Restart" everything works smooth, so I assume there is no issue with DC connectivity or so.

I have tried to play with many different options with little success although I don't know how sometimes has even worked but repeating the same did not gave the same results.

My complain is also about the poor debug information available in the portal or in the machine logs folder.

### Debug Output
This is the final output with the command.

```
DEBUG: 12:59:36 - SetAzureVMExtensionCommand end processing.
DEBUG: 12:59:36 - SetAzureVMExtensionCommand end processing.
Set-AzureRMVMExtension : Long running operation failed with status 'Failed'.
ErrorCode: VMExtensionProvisioningError
ErrorMessage: VM has reported a failure when processing extension 'AddDomain'. Error message: "Exception(s) occured while joining Domain
'app.local'".
StartTime: 12/04/2017 12:56:03
EndTime: 12/04/2017 12:59:14
OperationID: 9c147197-532d-43ea-814a-9e67233f00f7
Status: Failed
At line:1 char:1
+ Set-AzureRMVMExtension –ResourceGroupName "app_Scallability_Tes ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmVMExtension], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.SetAzureVMExtensionCommand
```

This is what can be seen in Azure extension details

```json
[
    {
        "code": "ComponentStatus/JoinDomainException for Option 1 meaning 'User Specified'/failed/1",
        "level": "Error",
        "displayStatus": "Provisioning failed",
        "message": "ERROR - Failed to join domain='AppMirror.local', ou='', user='AppMirror.local\\appmirror', option='NetSetupJoinDomain' (#1 meaning 'User Specified'). Error code 1332"
    }
]
```

Full machine log [log.txt](https://github.com/Azure/azure-powershell/files/916298/log.txt)

### Script/Steps for Reproduction

This is the script I'm executing.

```powershell
Set-AzureRMVMExtension –ResourceGroupName "App_Scallability_Tests" -Name "AddDomain" -ExtensionType "JsonADDomainExtension" -Publisher "Microsoft.Compute" -TypeHandlerVersion "1.3" -Location "northeurope" -Settings @{ "Name" = "App.local"; "User" = "App.local\app"; "Restart" = "true"; "Options" = 1} -VMName "aah-Host-0" -ProtectedSettings @{"password" = "password"}
```

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by singhkays** [comment]
@cormacpayne This should be looked at by the extension team

**Comment by guillemsola** [comment]
Hi guys, 

To my surprise I recreates machines and then adding them to the domain using the azure template join-domain several times with success. I launched the join domain template from the github link directly in azure and filling values in the UI. 

As said this works well after creating machines but I couldn't make it work either as a json template or PS command.

In any way logs don't really help me solving what is going on wrong

**Comment by guillemsola** [comment]
Still working on this. If I create two separate and disconnected templates I can first, provision machines and then launch another JSON template to join in the domain. I orchestrate both from a single PS1 script with two New-AzureRmResourceGroupDeployment one for each template.

It may be that it is not possible to do this in a single execution?

**Comment by guillemsola** [comment]
I'm glad I found that I was wrongly referencing the dependensOn field

I changed from

```json
          "dependsOn": [
            "[resourceId('Microsoft.Compute/virtualMachines', concat(parameters('envPrefixName'), '-', variables('sessionHostSrvName'), '-', copyindex()))]"
          ],
```
to
```json
          "dependsOn": [
            "[concat(parameters('envPrefixName'), '-', variables('sessionHostSrvName'), '-', copyindex())]"
          ],
```
Exactly matching the virtual machine

**Comment by knlp** [comment]
Hi. I know that you closed this, but is it still not possible to use this DomainJoin json bit as a part of one big template?

**Comment by guillemsola** [comment]
@knlp yes you can. IMO only that managing big templates sometimes can be cumbersome as there aren't a lot of tools to help you with that.

**Comment by knlp** [comment]
I use Visual Studio, so far my templates are not too complicated (few virtual machines, DC and other stuff), so I manage to... manage. :) Anyway it keeps on throwing 1332 on my despite providing credentials. I read that you need a custom OU, but the extension cannot create one, so that's another thing to overcome.

**Comment by vitocaresimodevops** [comment]
tried the template but keep getting the following error - Template deployment returned the following errors: 09:06:11 - "code": "VMExtensionProvisioningError", 09:06:11 - "message": "VM has reported a failure when processing extension 'joindomain'. Error message: \"Exception(s) occured while joining Domain

**Comment by josliebenah** [comment]
We had this exact same error, the service account used to join the domain ended up having a password complexity problem. Resetting it resolved the issue.
