### ISSUE TITLE
Retrieve Batch job preparation task execution info

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-powershell#3758]
### Cmdlet(s)
Get-AzureBatchJob

### PowerShell Version
5

### Module Version
3.8

### OS Version
Windows 10

### Description
https://docs.microsoft.com/en-us/rest/api/batchservice/list-the-status-of-the-job-preparation-and-job-release-tasks-for-a-job

I'd like to access the information described on that page but could not find a way to do that. Is that correct and can that be implemented?

**Comment by cormacpayne** [comment]
@matthchr Hey Matt, would you mind taking a look at this issue?

**Comment by matthchr** [comment]
Hi @letmaik - we don't currently have a cmdlet that provides this information, but we can look into adding it for the next release which should be in roughly 1 month.

Until then if you need a workaround you can call the API using the C# code (see [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.joboperations.listjobpreparationandreleasetaskstatus?view=azurebatch-6.1.0#Microsoft_Azure_Batch_JobOperations_ListJobPreparationAndReleaseTaskStatus_System_String_Microsoft_Azure_Batch_DetailLevel_System_Collections_Generic_IEnumerable_Microsoft_Azure_Batch_BatchClientBehavior__) for a C# reference).

If you need more details/help implementing a workaround please respond and I can give some.

**Comment by matthchr** [comment]
This will be included in the next Azure powershell release (see the PR above).
