### ISSUE TITLE
Create NuGet package for Commands.Common.Authentication

### ISSUE THREAD

**Issue by dchauran** [Azure/azure-powershell#3760]
### Cmdlet(s) 
N/A

### PowerShell Version
N/A

### Module Version
N/A

### OS Version
N/A

### Description
We have a significant dependency on the Microsoft.Azure.Common.Authentication from the old SDK, however that is no longer being maintained and the functionality has moved here. I would like to see a NuGet package of the libraries that were moved from that SDK to this project, as updates to those (for example to support new sovereign clouds) are not being accepted.

### Debug Output
N/A

### Script/Steps for Reproduction
N/A

**Comment by sphibbs** [comment]
We are not going to update or release an old hyak based SDK. We are looking into adding some of this functionality to the new auth sdk. 

Check out microsoft.rest.clientruntime.azure.authentication. It has some of the functionality you are looking for.

**Comment by dchauran** [comment]
Thanks, will take a look. We mostly use the region URL helpers as we have not found another library that serves that function. Do you happen to know if it is implemented there or elsewhere/
