### ISSUE TITLE
Missing cmdlet help files in 3.8 release

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#3764]
### Cmdlet(s)
Obsolete: Save-AzureRmProfile is renamed to Save-AzureRmContext
Obsolete: Select-AzureRmProfile is renamed to Import-AzureRmContext

The Markdown files were never generated for the new cmdlet names.

### Module Version
AzureRM 3.8.0
AzureRM.Profile 2.8.0

**Comment by cormacpayne** [comment]
@sdwheeler help for these cmdlets have been added in PR https://github.com/Azure/azure-powershell/pull/3655

**Comment by markcowl** [comment]
Fix checked in
