### ISSUE TITLE
Release notes for AzurePS 3.8.0 are unclear

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#3765]
The release notes say the following:

ServiceManagement
- Add initiate maintenance PowerShell cmdlet.
- Add Maintenance Status field to Get-AzureVM response

It sounds like there is a new cmdlet but it is not named. It is actually a new parameter for existing cmdlets.

**Comment by markcowl** [comment]
Fixed.

**Comment by sdwheeler** [comment]
@markcowl - when will this show up in the current release notes (both the master changelog and the release notes for the release)? We also need to update the release notes in the docs repo.
