### ISSUE TITLE
webapp:Fix skipped test "Test-CloneNewWebAppAndDeploymentSlots"

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#3770]
Skipping [Test-CloneNewWebAppAndDeploymentSlots](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppTests.cs#L75) test in the Websites module due to a known issue with the clone feature that causes this test to fail.

The test is failing when trying to create a cloned web app from the [Websites client](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Websites/Commands.Websites/Utilities/WebsitesClient.cs#L71).

**Comment by cormacpayne** [comment]
@Nking92 Hey Nick, do you know if this is still an issue on the server?

**Comment by cormacpayne** [comment]
@panchagnula Hey Sisira, would you mind taking a look at this issue?

**Comment by panchagnula** [comment]
@Nking92 i am assigning this back to you - so you can fix it while you are making some updates to the clone commandlet with the local geo-region changes

**Comment by panchagnula** [comment]
This is fixed with this change https://github.com/Azure/azure-powershell/pull/9496
