### ISSUE TITLE
Request: Add-AzureRmAutomationModule, Remove-AzureRmAutomationModule and Set-AzureRmAutomationModule should support Wait parameter

### ISSUE THREAD

**Issue by lfshr** [Azure/azure-powershell#3773]
### Cmdlet(s)
`Set-AzureRmAutomationModule`

### PowerShell Version
|Name|Value|
|------|-------|
|PSVersion          |            5.1.14393.1066|
|PSEdition            |          Desktop|
|PSCompatibleVersions     |      {1.0, 2.0, 3.0, 4.0...}|
|BuildVersion         |          10.0.14393.1066
|CLRVersion           |          4.0.30319.42000
|WSManStackVersion      |        3.0
|PSRemotingProtocolVersion   |   2.3
|SerializationVersion      |     1.1.0.1

### Module Version
| Name | Version |
|---|---|
| AzureRM.Automation | 2.8.0 |

### OS Version
>10.0.14393.1066

### Description
Currently there is no support in Set-AzureRmAutomationModule to set the module and wait for the imports to finish. There are manual work-arounds to listen to the status of the import before continuing, but I feel like the cmdlet should support this by default.

This would become very useful when handling dependencies, and uploading cmdlets before running runbooks as currently the cmdlet handles them quite poorly.

**Comment by lfshr** [comment]
@markcowl @safeermohammed @eamonoreilly any thoughts?

**Comment by sourabhguha** [comment]
good feature request. evaluating it.

**Comment by csand-msft** [comment]
The community is welcome to work on this request.

**Comment by GaneshMSAzure** [comment]
By design
