### ISSUE TITLE
Add-AzureRmAutomationModule and Set-AzureRmAutomationModule 'ContentLink' parameters should have the same name.

### ISSUE THREAD

**Issue by lfshr** [Azure/azure-powershell#3775]
### Cmdlet(s)
`Add-AzureRmAutomationModule`
`Set-AzureRmAutomationModule`
### PowerShell Version
|Name|Value|
|--------|--------|
|PSVersion|5.1.14393.1066|
|PSEdition|Desktop|
|PSCompatibleVersions|{1.0, 2.0, 3.0, 4.0...}|
|BuildVersion|10.0.14393.1066|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

### Module Version
| Name | Version |
|---|---|
| AzureRM.Automation | 2.8.0 |

### OS Version
10.0.14393.1066

### Description
Add-AzureRmAutomationModule currently has a parameter called 'ContentLink' and Set-AzureRmAutomationModule contains a parameter called 'ContentLinkUri' and 'ContentVersion'. I feel that this is unclear and inconsistent and one parameter name/set should be used. An alias could be added to avoid this being a breaking change.

**Comment by cormacpayne** [comment]
@safeermohammed Hey Safeer, would you mind taking a look at this issue?

**Comment by safeermohammed** [comment]
@vrdmr Lets try to get this change with your updates

**Comment by lfshr** [comment]
Closed by #4349
