### ISSUE TITLE
ErrorAction preference does not take effect for Get-AzureRmResource of ResourceType Microsoft.DocumentDb/databaseAccounts

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#3778]
### Cmdlet(s)

Get-AzureRmResource

### PowerShell Version

4.0

### OS Version

6.3.9600.17400

### Description

Error action preference does not take effect in Get-AzureRmResource of ResourceType Microsoft.DocumentDb/databaseAccounts.

PS C:\Windows\system32> Get-AzureRmResource -ResourceType Microsoft.DocumentDb/databaseAccounts -ResourceName "pradebban
" -ResourceGroupName "documentme3" **-ErrorAction SilentlyContinue**
Get-AzureRmResource : ResourceGroupNotFound : Resource group 'documentme3' could not be found.
At line:1 char:1
+ Get-AzureRmResource -ResourceType Microsoft.DocumentDb/databaseAccoun ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : ResourceGroupNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.Ge
   tAzureResourceCmdlet

### Script/Steps for Reproduction

Select subscription and run below

Get-AzureRmResource -ResourceType Microsoft.DocumentDb/databaseAccounts -ResourceName "pradebban
" -ResourceGroupName "documentme3" **-ErrorAction SilentlyContinue**

**Comment by markcowl** [comment]
@ravbhatnagar Can you take a look?  Note that, AzurePSCmdlet automatically writes exceptions to the error stream in ProcessRecord,, which is the right thing to do in this case

**Comment by cormacpayne** [comment]
I believe this is resolved in PR https://github.com/Azure/azure-powershell/pull/6008

**Comment by cormacpayne** [comment]
The fix for this should be available on May 7th in version 6.0.0 of `AzureRM` (version 6.0.0 of `AzureRM.Resources`). Please re-open this issue if the problem persists.
