### ISSUE TITLE
New-AzureRmWebAppSlot - "New-AzureRmWebAppSlot : Cannot find ServerFarm with name ." error

### ISSUE THREAD

**Issue by mathieu-benoit** [Azure/azure-powershell#3779]
### Cmdlet(s)
New-AzureRmWebAppSlot

### PowerShell Version
5.1.14393.1066 

### Module Version
(Get-Module AzureRM.Websites).Version
2      2      0      -1    

### OS Version
10.0.14393.1066 

### Description
My goal is to duplicate a WebApp on one new Slot (under this same WebApp). The associated App Service plan has its SKU as Premium.
For that, when I run the cmdlet New-AzureRmWebAppSlot I got this error message: "New-AzureRmWebAppSlot : Cannot find ServerFarm with name ."

### Script/Steps for Reproduction
$srcapp = Get-AzureRmWebApp -ResourceGroupName $ResourceGroupName -Name $Name;
New-AzureRmWebAppSlot -ResourceGroupName $ResourceGroupName -Name $Name -Slot $SlotName -AppServicePlan $AppServicePlan -SourceWebApp $srcapp;

### Remarks
- if I run New-AzureRmWebAppSlot line without the -SourceWebApp argument, the associated slot will be created properly.
- I checked the $srcapp value after running the Get-AzureRmWebApp and there is appropriate object value with all the fields correctly filled out.

**Comment by mathieu-benoit** [comment]
Any idea what I missed?

**Comment by cormacpayne** [comment]
@mathieu-benoit Hey Mathieu, this is a known issue and has been reported to the Websites team. They are hoping to get a fix out for the next Azure PowerShell release on May 10th. I am going to close this issue in favor of the few issues (that I'll link to below) that we currently have open that are tracking this bug. Please let me know if you have any questions.

_Opened issues:_
https://github.com/Azure/azure-powershell/issues/3770
https://github.com/Azure/azure-powershell/issues/3410
https://github.com/Azure/azure-powershell/issues/3390

**Comment by mathieu-benoit** [comment]
Looks good, thanks @cormacpayne for these details. Look forward for this fix, thanks!
