### ISSUE TITLE
New-AzureKeyVault for existing vault name fails with error NoRegisteredProviderFound

### ISSUE THREAD

**Issue by divyakgupta** [Azure/azure-powershell#378]
Running New-AzureKeyVault with an existing vault name and resource group name fails with an unexpected error "NoRegisteredProviderFound: No registered resource provider found..."

Expected error is something like "Vault name already taken"

**Comment by azurecompliance4** [comment]
The issue is not that a name is already taken.
To use KeyVault, the provider must be registered for the subscription.
We're looking at faulting it in automatically on error, but until then, you can register it explicitly with the Register-AzureProvider cmdlet

**Comment by matt-gibbs** [comment]
The issue is not that a name is already taken.
 To use KeyVault, the provider must be registered for the subscription.
 We're looking at faulting it in automatically on error, but until then, you can register it explicitly with the Register-AzureProvider cmdlet
