### ISSUE TITLE
New-​Azure​Rm​Service​Bus​Namespace doesn't allow messaging units for the premium tier

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-powershell#3780]
### Cmdlet(s)
`New-​Azure​Rm​Service​Bus​Namespace`

### PowerShell Version
5.1.15063.0

### OS Version
Windows 10, 10.0.15063.0

### Description

It it possible to set the messaging units value when creating a new ASB namespace on a premium tier, but impossible to accomplish the same using [PS cmdlet](https://docs.microsoft.com/en-us/powershell/module/azurerm.servicebus/new-azurermservicebusnamespace?view=azurermps-3.8.0). The cmdlet [doesn't account for messaging units](https://github.com/Azure/azure-powershell/blob/f0760a733e384ecced22f36dd3e1c8c6edb3ff36/src/ResourceManager/ServiceBus/Commands.ServiceBus/Utilities/ServiceBusClient.cs#L77) at all.

![image](https://cloud.githubusercontent.com/assets/1309622/25095407/d7381ba2-2358-11e7-84c0-02a46eec88b0.png)

**Comment by markcowl** [comment]
@aimankhan Can you take a look?

**Comment by SeanFeldman** [comment]
cc @jtaubensee

**Comment by cormacpayne** [comment]
@v-Ajnava Hey Ajit, would you mind taking a look at this issue?

**Comment by v-Ajnava** [comment]
this is resolved, please check with latest release.
