### ISSUE TITLE
Publish-AzureRmVMDscConfiguration creates unusable ZIP archive when module is present in multiple PSModulePath directories

### ISSUE THREAD

**Issue by jmarsik** [Azure/azure-powershell#3792]
### Cmdlet(s)
Publish-AzureRmVMDscConfiguration

### PowerShell Version
5.1.14393.953

### Module Version
AzureRM.Compute version 2.9.0

### OS Version
10.0.14393.953

### Description
When you try to create ZIP archive with resources (modules, configuration itself, ...) for DSC configuration using the Publish-AzureRmVMDscConfiguration (or try to create ZIP archive and publish it to Azure storage) and you have some of the required modules present in multiple PSModulePath directories, it creates ZIP file with "multiplied" directory names for such modules. This ZIP file is then unusable for applying the DSC configuration.

Multiplied directory names look like this:

![image](https://cloud.githubusercontent.com/assets/899151/25124892/63aa56de-242d-11e7-8f29-aaa34edf69dd.png)

Even the content of those directories is messed up. It's because the cmdlet is probably calling Copy-Item multiple times with the same target path and that path doesn't exist at first, but does exist for the second (and third ...) call. That creates nested structure.

I'm attaching sample ZIP file with such content, without the DSC configuration itself.
[LpWServerInstall.ps1.zip](https://github.com/Azure/azure-powershell/files/928509/LpWServerInstall.ps1.zip)

The cmdlet should probably:

1. take only the first module instance found in PSModulePath directories (with priority given by the order of directories in PSModulePath)
2. or copy from multiple modules to correctly named directory (assuming that the multiple instances of the module with specified module version are exactly the same, but there is probably no guarantee of that)
3. or indicate error

For me the first solution looks like the one that could be implemented easily and doesn't break any existing scenarios.

### Debug Output
VERBOSE: Temp folder 'C:\Users\jmarsik\AppData\Local\Temp\4a433856-60f7-450c-be6f-ab39670d5d4d' created.
VERBOSE: Copy 'C:\Users\jmarsik\Source\Repos\ProvisioningAutomation\DscConfigurations\LpWServer\LpWServerInstall.ps1' to
'C:\Users\jmarsik\AppData\Local\Temp\4a433856-60f7-450c-be6f-ab39670d5d4d\LpWServerInstall.ps1'.
VERBOSE: Parsing configuration script:
C:\Users\jmarsik\Source\Repos\ProvisioningAutomation\DscConfigurations\LpWServer\LpWServerInstall.ps1
VERBOSE: List of required modules: [[xPSDesiredStateConfiguration, 5.0.0.0], [cChoco, 2.3.0.0], [xPendingReboot, 0.3.0.0], [NGen, 1.0],
[DSC_ColinsALMCorner.com, 1.0], [Carbon, 2.4.1], [rsInternationalSettings, 0.5], [xRobocopy, 2.0.0.0], [xSQLServer, 6.0.0.0]].
VERBOSE: Copy the module '[xPSDesiredStateConfiguration, 5.0.0.0]' to
'C:\Users\jmarsik\AppData\Local\Temp\4a433856-60f7-450c-be6f-ab39670d5d4d'.
VERBOSE: Copy the module '[cChoco, 2.3.0.0]' to 'C:\Users\jmarsik\AppData\Local\Temp\4a433856-60f7-450c-be6f-ab39670d5d4d'.
VERBOSE: Copy the module '[xPendingReboot, 0.3.0.0]' to 'C:\Users\jmarsik\AppData\Local\Temp\4a433856-60f7-450c-be6f-ab39670d5d4d'.
VERBOSE: Copy the module '[NGen, 1.0]' to 'C:\Users\jmarsik\AppData\Local\Temp\4a433856-60f7-450c-be6f-ab39670d5d4d'.
VERBOSE: Copy the module '[DSC_ColinsALMCorner.com, 1.0]' to 'C:\Users\jmarsik\AppData\Local\Temp\4a433856-60f7-450c-be6f-ab39670d5d4d'.
VERBOSE: Copy the module '[Carbon, 2.4.1]' to 'C:\Users\jmarsik\AppData\Local\Temp\4a433856-60f7-450c-be6f-ab39670d5d4d'.
VERBOSE: Copy the module '[rsInternationalSettings, 0.5]' to 'C:\Users\jmarsik\AppData\Local\Temp\4a433856-60f7-450c-be6f-ab39670d5d4d'.
VERBOSE: Copy the module '[xRobocopy, 2.0.0.0]' to 'C:\Users\jmarsik\AppData\Local\Temp\4a433856-60f7-450c-be6f-ab39670d5d4d'.
VERBOSE: Copy the module '[xSQLServer, 6.0.0.0]' to 'C:\Users\jmarsik\AppData\Local\Temp\4a433856-60f7-450c-be6f-ab39670d5d4d'.
VERBOSE: Temp folder 'C:\Users\jmarsik\AppData\Local\Temp\70be9a44-a964-481e-8cef-60bf020d50bd' created.
VERBOSE: Performing the operation "Upload
'C:\Users\jmarsik\AppData\Local\Temp\70be9a44-a964-481e-8cef-60bf020d50bd\LpWServerInstall.ps1.zip'" on target
"https://xxx.blob.core.windows.net/windows-powershell-dsc/LpWServerInstall.ps1.zip".
VERBOSE: Configuration published to https://xxx.blob.core.windows.net/windows-powershell-dsc/LpWServerInstall.ps1.zip
https://xxx.blob.core.windows.net/windows-powershell-dsc/LpWServerInstall.ps1.zip
VERBOSE: Deleted 'C:\Users\jmarsik\AppData\Local\Temp\70be9a44-a964-481e-8cef-60bf020d50bd\LpWServerInstall.ps1.zip'
VERBOSE: Deleted 'C:\Users\jmarsik\AppData\Local\Temp\4a433856-60f7-450c-be6f-ab39670d5d4d'
VERBOSE: Deleted 'C:\Users\jmarsik\AppData\Local\Temp\70be9a44-a964-481e-8cef-60bf020d50bd'

**Comment by jmarsik** [comment]
There is another description of the same issue here: http://stackoverflow.com/questions/35604231/publish-azurermvmdscconfiguration-create-archive-with-duplicate-and-nested-modul

And possible workaround solution here (not tried): http://www.codegist.net/snippet/powershell/publish-cazurermvmdscconfigurationps1_ivnovi_powershell

**Comment by markcowl** [comment]
@singhkays Can you take a look?

**Comment by jmarsik** [comment]
@singhkays @markcowl Any news?

We have solved the problem by using Git submodules in our Git repository with the DSC configuration and by modifying PSModulePath just before calling Publish-AzureRmVMDscConfiguration to include directory containing those Git submodules. We also must ensure that the user doesn't have any of the modules used installed locally (or change PSModulePath to include ONLY the directory with Git submodules).

Having more robust way of using modules in DSC configuration regardless of user's environment would be nice.

**Comment by tom-dudley** [comment]
The error looks to stem from the powershell module defined [here](https://github.com/Azure/azure-powershell/blob/c0a7f43dcb105feaba4043063c193883949d7054/src/ServiceManagement/Compute/Commands.ServiceManagement/IaaS/Extensions/DSC/Publish/DscExtensionPublishCmdletCommonBase.cs#L261-L273) and [here](https://github.com/Azure/azure-powershell/blob/75b53e9029a3a5a4e393f7a8702bae853e353501/src/ResourceManager/Compute/Commands.Compute/Extension/DSC/DscExtensionPublishCmdletCommonBase.cs#L260-L272) which is down to these two lines:
```
$module = Get-Module -List -Name $moduleName
...
Copy-Item -Recurse -Path $moduleFolder -Destination ""$tempZipFolder\$($module.Name)""
```

The code is written such that it expects `Get-Module` to return a single module, whereas in some cases it returns an array of modules. In my case it was down to a duplicate path in `PSModulePath` as noted [above](https://github.com/Azure/azure-powershell/issues/3792#issuecomment-294760847)

I imagine something like `Get-Module -List -Name $moduleName | Sort Version -Descending | Select -First 1` would be a bit more robust.

The first hit on google for `psmodulepath duplicate` leads to https://github.com/Azure/azure-powershell/issues/2090 and https://github.com/Azure/azure-powershell/issues/685 which are both closed, although https://github.com/Azure/azure-powershell/issues/2220 is still open.

I managed to work around this by finding the duplicate `PSModulePath` paths and removing one of each from the system level `PSModulePath`. Probably not recommended, but worked for me.

**Comment by cormacpayne** [comment]
I believe this issue has been resolved in the latest version of `AzureRM`. Please re-open this issue if that is not the case.

**Comment by maddieclayton** [comment]
Closing as fixed. Please open a new issue if you are seeing this in Az 1.2.0
