### ISSUE TITLE
"Login-AzureRmAccount -ServicePrincipal -Credential" is not working in AzureAutomation sandbox

### ISSUE THREAD

**Issue by ikanni** [Azure/azure-powershell#3793]
### Cmdlet(s)
Login-AzureRmAccount -ServicePrincipal -Credential

### PowerShell Version
PSVersion                      5.0.10514.2 

### Module Version
CommandType     Name                                               Version    Source                                    
-----------     ----                                               -------    ------                                    
Alias              Login-AzureRmAccount                               2.8.0      AzureRM.Profile                   
Cmdlet          Get-AzureRmResourceGroup                       3.8.0      AzureRM.Resources 
Cmdlet          Find-AzureRmResource                                3.8.0      AzureRM.Resources
Cmdlet          Get-AzureRmAutomationAccount               2.8.0      AzureRM.Automation

### OS Version
BuildVersion                   10.0.10514.2  

### Description
We are using AzureRM version 2.8.0 modules in Azure Automation.  
We use Login-AzureRmAccount -ServicePrincipal -Credential to login to Azure.

The Get-AzureRmResourceGroup works fine after login. 
But the cmdlets like  Find-AzureRmResource, Get-AzureRmAutomationAccount & Get-AzureRmBackupVault fails with below error in Azure Automation sandbox. 
Please note the above cmdlets works fine in local machine OR  the above cmdlets works fine -Thumbprint option in Azure Automation sandbox.

Error:
----
Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials. (Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials. (Unable to retrieve service key for ServicePrincipal account 56719119-7c2c-4b0d-9d80-1a8579076ae5. Please log in again to supply the credentials for this service principal. In PowerShell, execute Login-AzureRMAccount for Azure Resource Manager cmdlets or Add-AzureAccount for service management cmdlets.))

### Debug Output

GetAzureAutomationAccount:
---------------------------------
10:43:50 PM - GetAzureAutomationAccount begin processing with ParameterSet 'ByAll'. 
10:43:50 PM - using account id 'ab12aa4d-793c-445e-bd59-4ff7eae9d65b'... 
[Common.Authentication]: Authenticating using Account: 'ab12aa4d-793c-445e-bd59-4ff7eae9d65b', environment:  'AzureCloud', tenant: '004d141e-78ae-4a54-9099-766fb79cdddf' Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :  04/14/2017 22:43:50:  - AuthenticationFactory: Deserialized 1 items to token cache.  

[Common.Authentication]: Authenticating using configuration values: Domain: '004d141e-78ae-4a54-9099-766fb79cdddf',  Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect:  'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True' 
[Common.Authentication]: Renewing token using AppId: 'ab12aa4d-793c-445e-bd59-4ff7eae9d65b', AdalConfiguration with  ADDomain: '004d141e-78ae-4a54-9099-766fb79cdddf', AdEndpoint: 'https://login.microsoftonline.com/', ClientId:  '1950a258-227b-4e31-a9cf-717495945fc2', RedirectUri: 'urn:ietf:wg:oauth:2.0:oob' 

[Common.Authentication]: Received exception Unable to retrieve service key for ServicePrincipal account  ab12aa4d-793c-445e-bd59-4ff7eae9d65b. Please log in again to supply the credentials for this service principal. In  PowerShell, execute Login-AzureRMAccount for Azure Resource Manager cmdlets or Add-AzureAccount for service management  cmdlets., while authenticating. 

10:43:52 PM - GetAzureAutomationAccount end processing. 
10:43:52 PM - GetAzureAutomationAccount end processing.

Find-AzureRmResource:
---------------------------
10:43:48 PM - FindAzureResourceCmdlet begin processing with ParameterSet 'Lists the resources based on the specified  scope.'. 
10:43:48 PM - using account id 'ab12aa4d-793c-445e-bd59-4ff7eae9d65b'... 

[Common.Authentication]: Authenticating using Account: 'ab12aa4d-793c-445e-bd59-4ff7eae9d65b', environment:  'AzureCloud', tenant: '004d141e-78ae-4a54-9099-766fb79cdddf' Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :  
04/14/2017 22:43:48:  - AuthenticationFactory: Deserialized 1 items to token cache.  

[Common.Authentication]: Authenticating using configuration values: Domain: '004d141e-78ae-4a54-9099-766fb79cdddf',  Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect:  'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True' 

[Common.Authentication]: Renewing token using AppId: 'ab12aa4d-793c-445e-bd59-4ff7eae9d65b', AdalConfiguration with  ADDomain: '004d141e-78ae-4a54-9099-766fb79cdddf', AdEndpoint: 'https://login.microsoftonline.com/', ClientId:  '1950a258-227b-4e31-a9cf-717495945fc2', RedirectUri: 'urn:ietf:wg:oauth:2.0:oob' 

[Common.Authentication]: Received exception Unable to retrieve service key for ServicePrincipal account  ab12aa4d-793c-445e-bd59-4ff7eae9d65b. 
Please log in again to supply the credentials for this service principal. In  PowerShell, execute Login-AzureRMAccount for Azure Resource Manager cmdlets or Add-AzureAccount for service management  cmdlets., while authenticating.

### Script/Steps for Reproduction

Get-Command Login-AzureRmAccount
Get-Command Get-AzureRmResourceGroup
Get-Command Find-AzureRmResource
Get-Command Get-AzureRMAutomationAccount

$username = "ab12aa4d-793c-445e-bd59-4ff7eae9d65b"
$password = <>
$secstr = New-Object -TypeName System.Security.SecureString
$password.ToCharArray() | ForEach-Object {$secstr.AppendChar($_)}
$cred = New-Object -typename System.Management.Automation.PSCredential -argumentlist $username, $secstr
$TenantId= <>

$DebugPreference = 'Continue'
Login-AzureRmAccount  `
        -ServicePrincipal `
        -TenantId $TenantId `
        -Credential $cred

mkdir DebugOutput -Force

#Get all ARM resources from all resource groups
$ResourceGroups = Get-AzureRmResourceGroup 5> .\DebugOutput\GetAzureRmResourceGroupDebugOutput.txt

$FindAzureRmResource = Find-AzureRmResource -ResourceGroupNameContains "TEST200Schedule-RG" 5> .\DebugOutput\FindAzureRmResourceDebugOutput.txt

$Accounts = Get-AzureRMAutomationAccount 5>.\DebugOutput\GetAzureRMAutomationAccount.txt

$backup = Get-AzureRmBackupVault 5>.\DebugOutput\GetAzureRmBackupVault.txt

**Comment by markcowl** [comment]
@ikanni Thanks for the issue.  Can you tell me if this was working in previous versions?  My recollection is that your sandbox does not allow CredManCache access, meanign that the default mechanism for storing the secret securely will not work, and that certificate credentials should be used instead, if that is the case.

**Comment by ikanni** [comment]
@markcowl  Thank you for adding the details about CredManCache access.

I tested with AzureRM module version 1.0.3 and it did not work for any cmdlets.

But with AzureRM.Profile (2.8.0) and  AzureRM.Resources (3.8.0) the cmdlet Get-AzureRmResourceGroup works fine and cmdlet Find-AzureRmResource fails. **How it is working for cmdlet  Get-AzureRmResourceGroup? Why cmdlet Find-AzureRmResource  is not working ?**

**Comment by cormacpayne** [comment]
@ikanni if you do not support CredManCache, then you should use certificates instead of secrets for ServicePrincipal authentication
