### ISSUE TITLE
Set-AzureRmApplicationGateway throws "Object reference not set to an instance of an object" the first time it runs after "Add-AzureRmApplicationGatewayHttpListener"

### ISSUE THREAD

**Issue by adityapenmetsa** [Azure/azure-powershell#3800]
### Cmdlet(s)
$appgateway = Add-AzureRmApplicationGatewayHttpListener -ApplicationGateway $appgw -Name $backendAddressPoolName -FrontendIPConfiguration $fipconfig01 -FrontendPort $fp01 `
												      -Protocol Https -HostName $hostName -RequireServerNameIndication true -SslCertificate $cert
            
 $UpdatedAppGw = Set-AzureRmApplicationGateway -ApplicationGateway $appgateway
### PowerShell Version
5.1.14393.953    

### OS Version
10.0.14393.953    

### Description
I am trying to add new HTTP listener to already existing Azure Application Gateway. After successfully running the cmdlet "Add-AzureRmApplicationGatewayHttpListener", the application gateway needs to be updated by running the cmdlet "Set-AzureRmApplicationGateway". It is here where the cmdlet throws "Object reference not set to an instance of an object" error the first time it is run. On retry, it successfully gets updated. I have tried the process repeatedly by deleting and adding the listeners, and this scenario is seen on every try. 
### Debug Output

Set-AzureRmApplicationGateway : Object reference not set to an instance of an object.
At line:94 char:29
+ ... atedAppGw = Set-AzureRmApplicationGateway -ApplicationGateway $appgat ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmApplicationGateway], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.SetAzureApplicationGatewayCommand

**Comment by markcowl** [comment]
@DeepakRajendranMsft Can you take a look?

**Comment by blarsonrp** [comment]
I am also getting this error with trying to finalize my add-azurermapplicationgatewayrequestroutingrule changes with Set-AzureRmApplicationGateway -ApplicationGateway $AppGw1 on azurerm.netwrok version 4.2.1

**Comment by alexhisen** [comment]
Also happens after Set-AzureRmApplicationGatewayHttpListener -ApplicationGateway $agw -Name API -SslCertificate $cert -Protocol Https

**Comment by dopsy** [comment]
any update?

**Comment by BigNStrauss** [comment]
I'm also experiencing this. Does anyone know of a solution or work around?

**Comment by parsoFish** [comment]
Also experiencing this after a AzureRmApplicationGatewayRequestRoutingRule is there any progress on this issue?

**Comment by maddieclayton** [comment]
@akshaysngupta Can you take a look at this issue?

**Comment by akshaysngupta** [comment]
This is the sequence of cmdlets that reproduces this error

```
$fePort = New-AzureRmApplicationGatewayFrontendPort -Name "$name-FePort" -Port 443
$appgw = New-AzureRmApplicationGateway -FrontendPort $fePort ...
$appgw = Add-AzureRmApplicationGatewayHttpListener -ApplicationGateway $appgw -FrontendPort $fp01
Set-AzureRmApplicationGateway -ApplicationGateway $appgw
```

This is happening as New-AzureRmApplicationGateway resets the $fePort.Id to empty string.

https://github.com/Azure/azure-powershell/blob/cb13d2d135a6755b2b94dd3b781c25d5e9978bbd/src/ResourceManager/Network/Commands.Network/ApplicationGateway/NewAzureApplicationGatewayCommand.cs#L290

https://github.com/Azure/azure-powershell/blob/cb13d2d135a6755b2b94dd3b781c25d5e9978bbd/src/ResourceManager/Network/Commands.Network/ApplicationGateway/ApplicationGatewayChildResourceHelper.cs#L69

Workaround:
Before performing a set, use Get cmdlets to fetch the referenced resources like ex- port and ipconfig for httplistener


Will update the issue with fix timeline.

**Comment by nunicorn** [comment]
Any update on a fix for this?

**Comment by EvgenyAgafonchikov** [comment]
Fixed by https://github.com/Azure/azure-powershell/pull/8576
