### ISSUE TITLE
Add Invoke-AzureRmRestMethod cmdlet 

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3806]
### Description

Cmdlet in the AzureRm.Profile module to use the ClientFactory to make authenticated calls to an endpoint in the environment using HttpClient (we *do not* want this cmdlet to wrap the Invoke-RestMethod cmdlet)

- [ ] Cmdlet allows setting characteristics of the Http Request per Invoke-RestMethod
  - [x] Method
  - [x] Uri
  - [x] Body
  - [x] Headers
  - [x] Include default headers for tracking, authentication
  - [x] Add tracing for request and response to debug stream
  - [x] AsJob support
  - [ ] ShouldProcess for: Put, Delete, Post, Patch
- [x] Unit Tests
- [ ] Scenario Tests using existing resource manager RP apis for each of the major methods
- [ ] Help documentation

### Cost: 12

**Comment by leftler** [comment]
@markcowl What is the reasoning behind using `HttpClient` over `Invoke-RestMethod`?

**Comment by markcowl** [comment]
@leftler HttpClient has a larger array of options for controlling the Http communication.

**Comment by MiYanni** [comment]
Bulk of code here: 
https://github.com/MiYanni/azure-powershell/blob/RestCmdlet/src/ResourceManager/Profile/Commands.Profile/Rest/InvokeAzureRmRestMethod.cs

Branch is:
https://github.com/MiYanni/azure-powershell/tree/RestCmdlet

**Comment by blueelvis** [comment]
@MiYanni @markcowl  - Was this ever released to the public? If not, any idea when this could be released?

**Comment by MiYanni** [comment]
@blueelvis It was not. I started making this and then was working on moving the codebase NetStandard since then. So, it has not been a priority.

**Comment by brandonh-msft** [comment]
@markcowl who do we talk to to get this reopened?
