### ISSUE TITLE
Implement Default Resource Group

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3808]
### Description

Add a cmdlet to set the default resource group, and dynamically make resource group parameter optional if a default resource group is set.

- [x] Add Set-AzureRmResourceGroup to set a default resource group
- [x] Automatically set default resource group when a new resource group is created
- [x] Make resource group optional if a default resource group is set through dynamic parameters 
- [x] Add tests for cmdlet, default behavior when resource group is and is nto set

### Cost: 8

**Comment by cormacpayne** [comment]
Notes from design meeting:

- Cmdlets to introduce:
    - `Get-AzureRmDefaultResourceGroup -Name <arg>`
    - Set-AzureRmDefaultResourceGroup -Name <arg>`
        - If not value provided, create resource group
    - Clear-AzureRmDefaultResourceGroup
- Consider if these cmdlets should be consolidated into `Get/Set/Clear-AzureRmDefault` with parameters `-ResourceGroupName`, `-Location`, etc.
- Check into default parameters for PowerShell for a session that can be manipulated
- Look into sticky parameters
    - Check for multiple uses and try to set accordingly

**Comment by maddieclayton** [comment]
### Updated Description

Add a cmdlet to set default parameters (Resource Group, Location, etc).

- [ ] Add Set-AzureRmDefault to set a default resource group (with potential to add other defaults in the future).  Store default resource group in Context.ExtendedProperties.
   - `Set-AzureRmDefault -ResourceGroup <arg>`
- [ ] Add Get-AzureRmDefault to see defaults.  If no arguments are provided, show all defaults.
   - `Get-AzureRmDefault -ResourceGroup`
   - `Get-AzureRmDefault`
- [ ] Add Clear-AzureRmDefault to clear defaults.  Clear all defaults if no arguments are provided.
   - `Clear-AzureRmDefault -ResourceGroup`
   - `Clear-AzureRmDefault`
- [ ] Make resource group optional if a default resource group is set through dynamic parameters 
   - Use dynamic parameters to check for default - set mandatory to false if default is present
   - Use default resource group if parameter is empty
- [ ] Add documentation for cmdlets and for optional resource group parameters
- [ ] Add tests for cmdlet
- [ ] Create tab completer for Resource Group
   - Ensure default resource group is first in list
   - Limit to 50 results
### Cost: 8

**Comment by maddieclayton** [comment]
Done
