### ISSUE TITLE
Import-AzureRmAutomationDscConfiguration timeout with 'Import-DscResource -Name'

### ISSUE THREAD

**Issue by lfshr** [Azure/azure-powershell#3814]
### Cmdlet(s)
Import-AzureRmAutomationDscConfiguration

### PowerShell Version
Name           |                Value
----                |           -----
PSVersion       |               5.1.14393.1066
PSEdition                      Desktop
PSCompatibleVersions      |     {1.0, 2.0, 3.0, 4.0...}
BuildVersion         |          10.0.14393.1066
CLRVersion           |          4.0.30319.42000
WSManStackVersion       |       3.0
PSRemotingProtocolVersion   |   2.3
SerializationVersion      |     1.1.0.1

### Module Version
AzureRM.Automation    2.8.0

### OS Version
`10.0.14393.10661`

### Description
Import-DscResource with a resource name appears to slow down DSC imports significantly. So much so that having 5/6 imports will cause the DSC import to timeout. Currently the only workaround is to specify a ModuleName rather than a resource name.

Currently importing the following:
```
Import-DscResource -Name 'Script'
Import-DscResource -Name 'xFirewall'
Import-DscResource -Name 'cChocoInstaller'
Import-DscResource -Name 'cChocoPackageInstaller'
Import-DscResource -Name 'Environment'
```

### Script/Steps for Reproduction
* Create a DSC script with several `Import-DscResource -Name` calls
* Try and import the resource

**Comment by 4c74356b41** [comment]
Import-DscResource -Module PSDesiredStateConfiguration, xPSDesiredStateConfiguration, xNetworking, xWebAdministration

this is what I'm using and it works perfectly fine

using PS 5.1 Azure PS 3.8

**Comment by lfshr** [comment]
@4c74356b41 that is not the issue. I'm aware of the module workaround.
>Currently the only workaround is to specify a ModuleName rather than a resource name.

**Comment by markcowl** [comment]
@singhkays can you take a look?

**Comment by nitinbps** [comment]
Can not see this issue on Az.Automation version 1.1.1
