### ISSUE TITLE
New-AzureResourceGroup gives a null reference exception if the template file contains no "parameters" section

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-powershell#382]
Example template file:

{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
        {
            "name": "aName",
            "type": "Microsoft.Web/serverfarms",
            "location": "West US",
            "apiVersion": "2014-06-01",
            "properties": {
                "name": "aName",
                "sku": "Free",
                "workerSize": "Large",
                "numberOfWorkers": 1
            }
        }        
    ]
}

Result:

PS C:\Users\stephwe\Documents\Visual Studio 2015\Projects\AzureResourceGroup1\AzureResourceGroup1\Templates> New-AzureResourceGroup -Name abc -Location "West US" -TemplateFile .\WebSite.json
New-AzureResourceGroup : Cannot retrieve the dynamic parameters for the cmdlet. Object reference not set to an instance of an object.
At line:1 char:1
+ New-AzureResourceGroup -Name abc -Location "West US" -TemplateFile .\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureResourceGroup], ParameterBindingException
    + FullyQualifiedErrorId : GetDynamicParametersException,Microsoft.Azure.Commands.Resources.NewAzureResourceGroupCommand

**Comment by vivsriaus** [comment]
@StephenWeatherford We now prompt for parameters when you specify just the template file. Can you please download the latest azure powershell and try this again? Thanks. 

https://azure.microsoft.com/en-us/documentation/articles/powershell-install-configure/
