### ISSUE TITLE
AzureRM 3.8 breaks backwards compatibility contrary to changelog (Save-AzureRmProfile / Select-AzureRmProfile)

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-powershell#3822]
### Cmdlet(s)
Save-AzureRmProfile (now Save-AzureRmContext)
Select-AzureRmProfile (now Import-AzureRmContext)

### Module Version
3.8

### Description
The changelog says:
> Obsolete: Save-AzureRmProfile is renamed to Save-AzureRmContext, there is an alias to the old cmdlet name, the alias will be removed in the next release.

However, there is no alias. Besides, removing the alias in the following release is a really bad idea in my opinion as it violates semantic versioning. Backwards compatibility should only be broken with major releases, so 4.0.

**Comment by letmaik** [comment]
Also, when using `Import-AzureRmContext` it spits out the following wrong warning:
> WARNING: The command 'Import-AzureRmContext' is obsolete. Select-AzureRmProfile will be renamed to Import-AzureRmContext in the next release.

Two things:
1. It refers to the wrong command in the first sentence.
2. The rename already happened in 3.8.

**Comment by markcowl** [comment]
Yes, the aliases were not added.  Good catch.

The next version *is* 4.0, which is why this would be removed next release. Unfortunately, the Obsolete attribute prints messages this way.  The first sentence is just boiler plate

**Comment by letmaik** [comment]
Poor man's work-around:
```ps1
try {
    Import-AzureRmContext
} catch [System.Management.Automation.CommandNotFoundException] {
    Set-Alias Import-AzureRmContext Select-AzureRmProfile
    Set-Alias Save-AzureRmContext Save-AzureRmProfile
} catch {}
```

**Comment by markcowl** [comment]
@letmaik Yep.  Because next release is a breakign change release, we will have to release a version of 3.x that fixes the break - this would likely happen after the BUILD conference.

**Comment by sphibbs** [comment]
Fixed
