### ISSUE TITLE
New-AzureResourceGroup fails if the template file contains spaces or other characters not valid in a deployment name

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-powershell#383]
For example:

PS C:\Users\stephwe\Documents\Visual Studio 2015\Projects\AzureResourceGroup1\AzureResourceGroup1\Templates> New-AzureResourceGroup -Name abc -Location "West US" -TemplateFile '.\Web Site.json'
New-AzureResourceGroup : Error 1: Code=InvalidDeployment; Message=The provided deployment name 'Web Site' has these invalid characters: ' '. The 
name can only be a letter, digit, '-', '.' or '_'.
At line:1 char:1
+ New-AzureResourceGroup -Name abc -Location "West US" -TemplateFile '. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureResourceGroup], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupCommand
 

PS C:\Users\stephwe\Documents\Visual Studio 2015\Projects\AzureResourceGroup1\AzureResourceGroup1\Templates>

**Comment by ravbhatnagar** [comment]
Good find but as the error message is self-explanatory, we will not fix this at this time.
