### ISSUE TITLE
Add-AzureRmEnvironment: New Parameter set

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#3836]
### Cmdlet(s)
Add-AzureRmEnvironment

### PowerShell Version
5

### Description
Add-AzureRmEnvironment should support parameter "ArmEndpoint" and should register the environment using it.

### Script/Steps for Reproduction
Add-AzureRmEnvironment -Name "MyAzure" **-ArmEndpoint** "EndpointValue"

**Comment by markcowl** [comment]
@viananth can you please put this in a milestone?
