### ISSUE TITLE
New-AzureResourceLock fails to validate -LockLevel parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#384]
# Environment
- Windows 8.1
- PowerShell 5.0 April 2015 Preview (5.0.10105.0)
- Azure PowerShell 0.9.1
# Problem

When I call the `New-AzureResourceLock` command, and specify a `-LockLevel` parameter value of `ReadOnly`, I receive an error.

> New-AzureResourceLock : Cannot bind parameter 'LockLevel'. Cannot convert value "ReadOnly" to type "Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.Locks.LockLevel". Error: "Unable to match the identifier name ReadOnly to a valid enumerator 
> name. Specify one of the following enumerator names and try again:
> CanNotDelete"

![image](https://cloud.githubusercontent.com/assets/466713/7625282/b56f7f96-f9b2-11e4-83ab-fd6a00590e92.png)

The `[Microsoft.Azure.Management.Resources.Models.LockLevel]` .NET Enumeration clearly shows that there are three valid values:
- ReadOnly
- CanNotDelete
- NotSpecified
# Expected Result

The `New-AzureResourceLock` command's `-LockLevel` parameter should accept any of the values from the [LockLevel] .NET Enumeration.

---

Why isn't this validating against the enum values properly?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ravbhatnagar** [comment]
We have fixed the .Net enumeration to list only CannotDelete which is what is currently supported in PS. Supporting other lock levels has been added to the backlog.

**Comment by ravbhatnagar** [comment]
Add all the lock levels that are supported by API. Portal has already added ReadOnly. PS and CLI should support the same.

**Comment by ravbhatnagar** [comment]
Fixed.
