### ISSUE TITLE
Get-AzureRmResource -ParentResource

### ISSUE THREAD

**Issue by pratiksharma897** [Azure/azure-powershell#3842]
### Cmdlet(s)
Get-AzureRmResource
### PowerShell Version
5.1.14393.953

### Module Version
3.8.0
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.14393.953
### Description
Get-AzureRmResource -ParentResource fails with error parameter 'ParentResource' not found
### Debug Output
PS C:\Users\localadmin> $DebugPreference="Continue"

PS C:\Users\localadmin> Get-AzureRmResource -ParentResource Microsoft.Compute/virtualMachines/DEVVM
Get-AzureRmResource : A parameter cannot be found that matches parameter name 'ParentResource'.
At line:1 char:21
+ Get-AzureRmResource -ParentResource Microsoft.Compute/virtualMachines ...
+                     ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmResource], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet

**Comment by cormacpayne** [comment]
@pratiksharma897 this parameter was removed, you should use the `ResourceId` parameter instead
