### ISSUE TITLE
[ARM] Get-AzureStorageAccountKey design issues

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#386]
In the Azure Resource Manager (ARM) PowerShell module, the `Get-AzureStorageAccountKey` command returns an object that only has two useful properties: `Key1` and `Key2`. These properties are not named as friendly as the old Service Management module, which had properties named `Primary` and `Secondary`.

Furthermore, the object returned by the ARM module does not offer the `StorageAccountName` property, which is used to correlate the Storage Account that the keys belong to. In the Service Management module, this property existed.

![image](https://cloud.githubusercontent.com/assets/466713/7635522/b9c4c256-fa1e-11e4-829a-c24797b234f1.png)
# Action Items

The following actionable items are recommended for implementation in the ARM PowerShell module, surrounding the `Get-AzureStorageAccountKey` command:
1. Change `Key1` property to `Primary`
2. Change `Key2` property to `Secondary`
3. Add a `StorageAccountName` property to the object model

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by devigned** [comment]
Agreed. These should provide better naming.

**Comment by gangsir** [comment]
Thanks for providing feedback to storage team. Actually changing the key names to key1 and key2 was intentional. Previously folks were getting confused whether primary key was used for primary location and secondary key was used for secondary location. This is not true, so we changed them to key1 and key2 to clear the confusion and clarify that the same keys can be used for both primary and secondary locations. Hope this clarifies.

**Comment by pcgeek86** [comment]
@gangsir: To me, it seems as if  you fixed a training problem with a technical solution, rather than educating the users and adding clarifying documentation. The Azure Portal shows "primary" and "secondary" so the PowerShell interface should match that.

Now you have broken parity between PowerShell & the Azure Portal.

![image](https://cloud.githubusercontent.com/assets/466713/8856321/5027cc0e-3127-11e5-92bf-e89accf7e6b5.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by alexandair** [comment]
@gangsir I don't think naming the properties Key1 and Key2 is a solution. If someone is confused with Primary/Secondary terms, that same person wouldn't be less confused with Key1/Key2. The point is that you need to understand the technology and the purpose of those two keys. We are already familiar with Primary/Secondary keys, portals are using them, so why can't we use the knowledge we already have?

**Comment by sphibbs** [comment]
Closing since the portal has also changed to key1 and key2 a long time ago. Sorry this issues wasn't resolved when that happened
