### ISSUE TITLE
Get-AzureWebsite performance

### ISSUE THREAD

**Issue by davenewza** [Azure/azure-powershell#3861]
### PS Version
5.0.10586.494

### OS Version
10.0.10586.494

### Description
It seems to take a consistent 1 to 2 minutes (sometimes more) to return from the `Get-AzureWebsite` cmdlet. We use a lot of Azure powershell in our automation processes but these slow queries really hamper progress. Can anything be done to improve performance?

**Comment by cormacpayne** [comment]
@davenewza Hey Dave, are you using `Get-AzureWebsite` or `Get-AzureRmWebsite`?

**Comment by cormacpayne** [comment]
@davenewza in addition, what is the full command that you are running, and how many items are being returned from these calls?

**Comment by davenewza** [comment]
@cormacpayne the full command is simply `Get-AzureWebsite -Name myappname` with one item returned.

**Comment by shahabhijeet** [comment]
@davenewza can you use Get-AzureRmWebSite to retrieve website info.
Please let us  know if you see perf. issues with Get-AzureRmWebSite.

**Comment by davenewza** [comment]
@shahabhijeet I assume you meant `Get-AzureRmWebApp` (and not `WebSite`).  

This is indeed much quicker - it seems to complete at around 18 seconds consistency from my location.

**Comment by davenewza** [comment]
Using Get-AzureRmWebApp has fixed the issue for me, so I will close this.
