### ISSUE TITLE
Add support for partial download (range) in Get-​Azure​Batch​Node​File​Content

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-powershell#3863]
### Cmdlet(s)
Get-​Azure​Batch​Node​File​Content

### Module Version
3.8

### Description
As described in the [Batch REST API docs](https://docs.microsoft.com/en-us/rest/api/batchservice/get-data-from-a-file-on-a-compute-node) it is possible to partially download a file from a Batch node by using the `ocp-range` header.

I implemented a stdout.txt/stderr.txt monitoring script which currently fetches the whole file every half a minute and outputs any new content to the terminal. However, it would be much better if I could fetch only the new content to begin with.

My feature request is to add a new parameter to this cmdlet where the byte range can be specified.

**Comment by cormacpayne** [comment]
@matthchr Hey Matt, would you mind taking a look at this issue?

**Comment by matthchr** [comment]
This was added and will be part of the next version of Azure Powershell
