### ISSUE TITLE
Update the help for New-AzureRmTag cmdlets

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/azure-powershell#3878]
As per the help here - https://docs.microsoft.com/en-us/powershell/module/azurerm.tags/get-azurermtag?view=azurermps-3.8.0
_If the subscription includes any predefined tags, you cannot apply undefined tags or values to any resource or resource group in the subscription_.”
 The above is not accurate. Please revisit the help for the related cmdlets and fix.

**Comment by cormacpayne** [comment]
@ravbhatnagar Hey Gaurav, would you mind putting this issue into a milestone?

**Comment by cormacpayne** [comment]
This has been fixed and will be available in the 6.6.0 release of `AzureRM`
