### ISSUE TITLE
-JoinDomain parameter not working in Add-AzureProvisioningConfig

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-powershell#388]
I'm trying to create a Windows VM in Azure and join it to the domain all in one step using the Azure PowerShell module. This is my script:

    New-AzureVMConfig -Name $fileserver -Label $fileserver -InstanceSize Basic_A3 -ImageName $img -HostCaching ReadWrite -DiskLabel 'OS' -MediaLocation $medialoc `
    | Add-AzureProvisioningConfig -WindowsDomain -JoinDomain $domjoin -Domain $dom -DomainUserName $domainuser -DomainPassword $domainpw -AdminUsername $adminPassword -Password $adminPassword `
    | Set-AzureSubnet 'Dynamic1' `
    | New-AzureVM -ServiceName $cloudSvcName -VNetName $vnet -verbose -waitforboot

The error i'm getting is as follows:

New-AzureVM : BadRequest: Invalid domain join information specified. Ensure that the JoinDomain setting is specified, and that either the Credentials or Provisioning setting is specified. See the Windows Automated Installation Kit documentation for more information.

If I take out these params:

    -WindowsDomain -JoinDomain $domjoin -Domain $dom -DomainUserName $domainuser -DomainPassword $domainpw -AdminUsername $adminPassword -Password $adminPassword `
and replace them with these (removing the join domain stuff):

    -Windows -AdminUserName "localadmin" -Password $adminPassword
I get no errors and the machine provisions just fine without domain joining it.

**Comment by singhkay** [comment]
@huangpf Can you take a look at this. Thanks!

**Comment by aarsan** [comment]
Turns out, for $domainuser, i was using "domain\username" instead of just "username". This is no longer an issue and can be closed. Thanks.
