### ISSUE TITLE
Get-AzureRMRoleAssignment does not respect scope parameter

### ISSUE THREAD

**Issue by Roblarson** [Azure/azure-powershell#3884]
### Cmdlet(s)
Get-AzureRmRoleAssignment -Scope /subscriptions/74b4f341-d9fd-4ef6-8f57-xxxxxxxxxx/resourceGroups/TestRG2

ignores the resource group scope and returns all assignments at the subscription level

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

Name                           Value                                                                                                                     
----                           -----                                                                                                                     
PSVersion                      5.1.15063.168                                                                                                             
BuildVersion                   0.0.15063.168                                                                                                            
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

Just execute the Get-AzureRmRoleAssignment with scope at a valid resource group and the role assignments will be returned at the subscription level instead.

**Comment by cormacpayne** [comment]
@darshanhs90 would you mind taking a look at this issue?

**Comment by darshanhs90** [comment]
Linked to https://github.com/Azure/azure-powershell/issues/4248

**Comment by stylerOD** [comment]
Just resolved a support ticket with MS for this one. Solution:
Select-AzureRmSubscription -SubscriptionId 123456-abcd-etc
Get-AzureRmRoleAssignment -Scope "this parameter either does nothing or is just misleading in its name and description, but isn't what we'd use for the problem everyone looking at this thread is probably encountering"

Only took us two weeks to figure out.

**Comment by darshanhs90** [comment]
This commandlet get all the roleassignments at the scope and below,viz by design.Hence it is working as expected

**Comment by darshanhs90** [comment]
We might add an extra option for scope and below later in the future
