### ISSUE TITLE
AzureRM.psd1 contains function and alias exports that are not implemented.

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#3885]
AzureRM Module

### Module Version
This problem has existed for several releases. You can see it in 3.8.0 release of the AzureRM module.

### Description
The module manifest contains the following lines:

FunctionsToExport = 'Update-AzureRM', 'Import-AzureRM', 'Uninstall-AzureRM'
AliasesToExport = 'Install-AzureRM'

Those items are not defined anywhere in any module or script.

**Comment by cormacpayne** [comment]
@sdwheeler previously, these cmdlets were used to install/uninstall/update the AzureRM module, but these cmdlets were deprecated in favor of the PowerShell gallery. [Here](https://github.com/Azure/azure-powershell/blob/preview/tools/AzureRM/AzureRM.psm1) is the file where the cmdlets were defined, and you can see [here](https://github.com/Azure/azure-powershell/blob/preview/tools/AzureRM/AzureRM.psm1#L62) there is a deprecation warning for one of the cmdlets (applies throughout). These cmdlets were kept for backwards compatibility and to not break existing scripts that used them.

**Comment by sdwheeler** [comment]
@cormacpayne The AzureRM.psm1 that ships does not contain these function and alias definitions.

**Comment by sdwheeler** [comment]
I think I found the issue. tools/UpdateModules.ps1 script in tools overwrites the AzureRM.psm1 file with the blank template. It is not using the file tools/AzureRM/AzureRM.psm1.

**Comment by cormacpayne** [comment]
These cmdlets have been removed for the 4.0.0 release, so this is fixed.
