### ISSUE TITLE
Get-AzureRMVM -Status yields different result when running against a single machine rather than a pool of machines

### ISSUE THREAD

**Issue by danielstocker** [Azure/azure-powershell#3896]
### Cmdlet(s)
Get-AzureRMVM -Status
Get-AzureRMVM -ResourceGroupName "MyName" -Name "MyVM" -Status

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1.14393.1066

### Module Version
2.8.0      AzureRM.Compute

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.14393.1066

### Description
For example when getting the power state of a machine

<img width="657" alt="capture1" src="https://cloud.githubusercontent.com/assets/9444698/25669413/5854ae56-3021-11e7-8d9c-ec28e02209fc.PNG">
**(Get-AzureRMVM -Status)[0].PowerState** yields **"deallocated"**

<img width="662" alt="capture1" src="https://cloud.githubusercontent.com/assets/9444698/25669471/89527c2c-3021-11e7-9748-cd5faccd01ba.PNG">
**Get-AzureRMVM -ResourceGroupName autotest -Name autoclient -Status** yields an array of status items one of which is the power state. 
(Get-AzureRMVM -ResourceGroupName autotest -Name autoclient -Status).Statuses[1].Code yields **PowerState/deallocated**

### Debug Output
not applicable

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue? Looks like a difference in the output display for the two calls that can be fixed in the format.ps1xml file. Table (first image in the issue) should be the default view when the output is returned.

**Comment by singhkays** [comment]
@danielstocker Thanks for the report. @hyonholee looks like we just need to parse the string correctly in the latter

**Comment by TimCurwick** [comment]
This is NOT a formatting issue. The cmdlet returns completely different object types in violation of PowerShell standards.

Get-AzureRMVM -Status returns an array of PSVirutalMachineList objects.
Get-AzureRMVM -Status -Name x returns a PSVirtualMachine object.

Get-AzureRMVM returns an array of PSVirtualMachineListStatus objects.
Get-AzureRMVM -Name x returns a PSVIrtualMachineInstanceView object.

One could make the argument that with and without the -Status switch should result in different object types. (I wouldn't make that argument, but one could.)

But the addition of a -Name parameter should NEVER result in a different object type. Whether getting the objects individually or en masse, the results should be identical.

**Comment by NeilBird** [comment]
Any update on this issue? - I have seen people using `$vm.statuses[1].Code` to obtain the power state of a single VM, ('PowerState/running'), as a work-around to this issue. As opposed to being able to use the $vm.PowerState property, which is returned correctly when more than one VM is returned by Get-AzureRMVM.

**Comment by NeilBird** [comment]
Any update on this issue, in 2 weeks it will have been open a year?

**Comment by mrwalters1988** [comment]
Still seeing this bug and wondering if it'll be fixed any time soon.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
