### ISSUE TITLE
ARM: Network Security Group fails due to invalid Address Prefix

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#391]
The MSDN documentation states that an Address Prefix can be one of three special "tags."
- VIRTUAL_NETWORK - This default tag denotes all of your network address space. It includes the virtual network address space (IP CIDR in Azure) as well as all connected on-premises address space (Local Networks). This also includes VNet to VNet address spaces.
- AZURE_LOADBALANCER - This default tag denotes Azure’s Infrastructure load balancer. This will translate to an Azure datacenter IP where Azure’s health probes will originate. This is needed only if the VM or set of VMs associated with the NSG is participating in a load balanced set.
- INTERNET - This default tag denotes the IP Address space that is outside the virtual network and reachable by public Internet. This range includes Azure owned public IP space as well.

When I specify VIRTUAL_NETWORK in a Network Security Rule, the ARM cmdlets fail to create the Network Security Group.

![image](https://cloud.githubusercontent.com/assets/466713/7645466/c40e0a34-fa72-11e4-956c-8de70eeb9322.png)

> New-AzureNetworkSecurityGroup : SecurityRuleInvalidAddressPrefix: Security rule has invalid Address prefix. Value provided: VIRTUAL_NETWORK.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by DeepakRajendranMsft** [comment]
Hi Trevor,

In ARM we accept only VirtualNetwork and AzureLoadBalancer (without the underscore). see https://msdn.microsoft.com/en-us/library/azure/mt163645.aspx

Thanks,
Deepak.

**Comment by pcgeek86** [comment]
@DeepakRajendranMsft Thanks -- can you please ensure that the Azure PowerShell documentation is updated to reflect this?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by timwieman** [comment]
Note, this link, https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-nsg/#Default-Rules, is where the documentation discusses these default rules and defines the default tags of VIRTUAL_NETWORK, AZURE_LOADBALANCER, and INTERNET.  It sounds like these are incorrect and should be changed to match the ones defined here: https://msdn.microsoft.com/en-us/library/azure/mt163645.aspx

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
