### ISSUE TITLE
 Cannot process argument transformation on parameter 'InstalledModuleInfo'

### ISSUE THREAD

**Issue by vhusker** [Azure/azure-powershell#3914]
### PowerShell Version
Name                           Value
----                           -----
PSVersion                      5.1.14393.1066
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1066
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Module Version
VERBOSE: Downloading module 'AzureRM' with version '3.8.0' from the repository
'https://www.powershellgallery.com/api/v2/'.
### OS Version
BuildVersion                   10.0.14393.1066

### Description
When trying to install/update this module from the Gallery, it starts to install but then fails with the following error message.  Looks like it got through Azure.AnalysisServices and then failed.
PackageManagement\Install-Package : Cannot process argument transformation on parameter 'InstalledModuleInfo'. Cannot
convert the "System.Object[]" value of type "System.Object[]" to type "System.Management.Automation.PSModuleInfo".
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Excep
   tion
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Validate-ModuleAuthenticodeSignature,Microsoft.Powe
   rShell.PackageManagement.Cmdlets.InstallPackage

### Debug Output
DEBUG: 00:00:32.9235720 Calling 'NuGetClient'::'InstallPackage'.
VERBOSE: InstallPackage' - name='AzureRM.AnalysisServices',
version='0.2.0',destination='C:\Users\jbenson\AppData\Local\Temp\564581692'
VERBOSE: DownloadPackage' - name='AzureRM.AnalysisServices',
version='0.2.0',destination='C:\Users\jbenson\AppData\Local\Temp\564581692\AzureRM.AnalysisServices\AzureRM.AnalysisSer
vices.nupkg', uri='https://www.powershellgallery.com/api/v2/package/AzureRM.AnalysisServices/0.2.0'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/AzureRM.AnalysisServices/0.2.0'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/AzureRM.AnalysisServices/0.2.0'.
VERBOSE: Completed downloading 'AzureRM.AnalysisServices'.
VERBOSE: Hash for package 'AzureRM.AnalysisServices' does not match hash provided from the server.
DEBUG: 00:00:33.6531516 Calling 'NuGetClient'::'InstallPackageLocal'.
VERBOSE: InstallPackageLocal' - name='AzureRM.AnalysisServices',
version='0.2.0',destination='C:\Users\jbenson\AppData\Local\Temp\564581692'
DEBUG: 00:00:33.6600143
C:\Users\jbenson\AppData\Local\Temp\564581692\AzureRM.AnalysisServices\AzureRM.AnalysisServices.nupkg
DEBUG: 00:00:34.3775423 Returning the call 'NuGetClient'::'InstallPackageLocal'.
DEBUG: 00:00:34.4000540 Returning the call 'NuGetClient'::'InstallSinglePackage'.
DEBUG: 00:00:34.4216933 Calling 'NuGetClient'::'InstallPackage'.
VERBOSE: InstallPackage' - name='Azure.AnalysisServices',
version='0.2.0',destination='C:\Users\jbenson\AppData\Local\Temp\564581692'
VERBOSE: DownloadPackage' - name='Azure.AnalysisServices',
version='0.2.0',destination='C:\Users\jbenson\AppData\Local\Temp\564581692\Azure.AnalysisServices\Azure.AnalysisService
s.nupkg', uri='https://www.powershellgallery.com/api/v2/package/Azure.AnalysisServices/0.2.0'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/Azure.AnalysisServices/0.2.0'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/Azure.AnalysisServices/0.2.0'.
VERBOSE: Completed downloading 'Azure.AnalysisServices'.
VERBOSE: Hash for package 'Azure.AnalysisServices' does not match hash provided from the server.
DEBUG: 00:00:35.2587620 Calling 'NuGetClient'::'InstallPackageLocal'.
VERBOSE: InstallPackageLocal' - name='Azure.AnalysisServices',
version='0.2.0',destination='C:\Users\jbenson\AppData\Local\Temp\564581692'
DEBUG: 00:00:35.2615793
C:\Users\jbenson\AppData\Local\Temp\564581692\Azure.AnalysisServices\Azure.AnalysisServices.nupkg
DEBUG: 00:00:35.5223499 PowerShell Script 'PSModule' Function 'Install-Package' returns null.
PackageManagement\Install-Package : Cannot process argument transformation on parameter 'InstalledModuleInfo'. Cannot
convert the "System.Object[]" value of type "System.Object[]" to type "System.Management.Automation.PSModuleInfo".
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Excep
   tion
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Validate-ModuleAuthenticodeSignature,Microsoft.Powe
   rShell.PackageManagement.Cmdlets.InstallPackage

### Script/Steps for Reproduction
From PowerShell or PowerShell ISE run Install-Module -AzureRM -Force -Verbose -AllowClobber.  It does the same thing without allow clobber.

**Comment by vhusker** [comment]
Interestingly enough, I just ran the command as Install-Module AzureRM -AllowClobber and everything is installing fine.

**Comment by cormacpayne** [comment]
@vhusker Hey Jacob, in the May release (4.0.0) we're fixing the issue with needing `-AllowClobber` when installing from the gallery; hopefully this will resolve the issue above (without needing that parameter). I'm going to close this issue for now, but please feel free to reopen this issue if you have this problem when installing 4.0.0
