### ISSUE TITLE
Upgrading Tier (Sku) via Set-AzureRmAnalysisServicesServer not working and executing without error

### ISSUE THREAD

**Issue by RuiRomano** [Azure/azure-powershell#3920]
### Cmdlet(s)
Set-AzureRmAnalysisServicesServer

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with  5.1.14393.1066

### Module Version
0.2.0

### OS Version
10.0.14393.1066

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@athipp Hey Arun, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
@athipp @taiwu would you mind taking a look at this issue?

**Comment by minghan** [comment]
This issue is tracked by Microsoft internal bug https://powerbi.visualstudio.com/Analysis%20Services/_workitems/edit/137132

**Comment by minghan** [comment]
Closing this bug due to lack of information. Please re-open this bug if the issue is not due to Issue #4107.
