### ISSUE TITLE
Create existing SQL server in different resource group gives incorrect error message

### ISSUE THREAD

**Issue by rneeft** [Azure/azure-powershell#3921]
I don't know where to create this issues but since I'm using the PowerShell cmdlet I post it here. 

### Cmdlet(s)
New-AzureRmSqlServer
 
### PowerShell Version
PSVersion: 5.1.15063.138

### Module Version
|ModuleType|Version|Name
|---|---|---|
|Manifest|3.7.0|Azure|
|Manifest|2.7.0|AzureRM.Sql|

### OS Version
BuildVersion: 10.0.15063.138

### Description
When creating a SQL Server with a server name that already exist in the subscription but not in the resource group result in incorrect error message

### Debug Output
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
x-ms-request-id               : 600df3e2-8b6d-4c0a-939b-37c5b2ab430b
X-Content-Type-Options        : nosniff
Preference-Applied            : return-content
DataServiceVersion            : 3.0;
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1187
x-ms-correlation-request-id   : 6b6aa264-f59a-4f3f-a192-3f92a39740ce
x-ms-routing-request-id       : UKSOUTH:20170506T210739Z:6b6aa264-f59a-4f3f-a192-3f92a39740ce
Cache-Control                 : no-store,no-cache
Date                          : Sat, 06 May 2017 21:07:38 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "code": "40647",
  "message": "Subscription '{SubscriptionId}' does not have the server 'sql-server-bug-tst'.",
  "target": null,
  "details": [
    {
      "code": "40647",
      "message": "Subscription '{SubscriptionId}' does not have the server 'sql-server-bug-tst'.",
      "target": null,
      "severity": "16"
    }
  ],
  "innererror": []
}

New-AzureRmSqlServer : 40647: Subscription '{SubscriptionId}' does not have the server 'sql-server-bug-tst'.
At S:\bug.ps1:31 char:1
+ New-AzureRmSqlServer -ResourceGroupName $name2 -ServerName $sqlServer ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmSqlServer], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.Server.Cmdlet.NewAzureSqlServer

DEBUG: 23:07:40 - NewAzureSqlServer end processing.
DEBUG: 23:07:40 - NewAzureSqlServer end processing.

### Script/Steps for Reproduction
```powershell
Login-AzureRmAccount

$name1 = "TST-RG-1"
$name2 = "TST-RG-2"
$LocationLong = "West Europe"
$sqlServerName = "sql-server-bug-tst"
$sqlAdminPassword = ConvertTo-SecureString "P@ssw0rd!" -AsPlainText -Force
$sqlAdminUser = "sql-server-service-account"
$sqlCredentials = New-Object System.Management.Automation.PSCredential -Argumentlist $sqlAdminUser, $sqlAdminPassword

# First lets create a resource group
New-AzureRmResourceGroup -Name $name1 -Location $LocationLong -Force 
# Add the SQL Server to the resource group
New-AzureRmSqlServer -ResourceGroupName $name1 -ServerName $sqlServerName -Location $LocationLong -SqlAdministratorCredentials $sqlCredentials 

# Create a SECOND resource group
New-AzureRmResourceGroup -Name $name2 -Location $LocationLong -Force
# Now we add a SQL server into the SECOND resource group BUT with the SAME name as in the first. 
Write-Host "Fails with incorrect message" -ForegroundColor Red
New-AzureRmSqlServer -ResourceGroupName $name2 -ServerName $sqlServerName -Location $LocationLong -SqlAdministratorCredentials $sqlCredentials
# this last command fails with the message that the server name cannot be found in {SubscriptionId}
# This message should be like: Subscription '{SubscriptionId}' does already have a SQL server named '{ServerName}'.
```

**Comment by cormacpayne** [comment]
@akromm Hey Adam, would you mind taking a look at this issue?

**Comment by akromm** [comment]
Ack.  We will look into the issue.

**Comment by jcyang75** [comment]
Looked into this and found that there’s a defect in the code throwing wrong error message in this condition. I’ve created a defect and one of our engineers will be working on the fix soon.

**Comment by akromm** [comment]
@rneeft This should be fixed worldwide. Let me know if you see otherwise.
