### ISSUE TITLE
bug: no results for Get-AzureVM in AzureResourceManager

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-powershell#393]
I was happy to see [Get-AzureVM added to the AzureResourceManager mode for [0.9.0](https://github.com/Azure/azure-powershell/releases/tag/0.9.0-April2015). I have 0.9.1 installed, but unfortunately, I get no VMs returned in that mode. Is this a bug or am I doing something wrong?

![image](https://cloud.githubusercontent.com/assets/80104/7658446/2a0a3386-faef-11e4-8c67-897bf77d64bf.png)

![image](https://cloud.githubusercontent.com/assets/80104/7658456/3c59012a-faef-11e4-86d0-91480801aa21.png)

**Comment by singhkay** [comment]
@ctaggart Do you have any v2 VMs created?

**Comment by ctaggart** [comment]
@singhkay The update Portal UI with the v2 VMs wasn't available yet when I submitted this. So, this only works with v2 VMs?

**Comment by singhkay** [comment]
Yes. The two modes are independent of each other and only cater to the specific v1 or v2 resources.

**Comment by djberg96** [comment]
I don't understand why it can't see them. I can see the classic VM's in the V2 portal, and the Virtual Machine Contributor role specifically mentions Microsoft.ClassicCompute/virtualMachines/*

**Comment by singhkay** [comment]
@djberg96 Even though these cmdlets are same name, on the backend they call different APIs and work on different API responses and return different objects. Having a cmdlet like Get-AzureVM we'd need to return two different objects based on the stack and then make all the other cmdlets in the module aware of what kind of object being piped into them and make decisions on the what stack API to call and what parameters to take as input.
