### ISSUE TITLE
How to get the owner of a VM in an Enterprise account

### ISSUE THREAD

**Issue by jan-wang** [Azure/azure-powershell#3932]
HI,
We are using an Azure Enterprise account. There are many users under this enterprise account.
I want to get the owner who create one VM. Is there any commands for this?

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, is this functionality supported in any cmdlet?

**Comment by singhkays** [comment]
@jan-wang @cormacpayne Nothing specific to VMs in this case but you can try looking at Audit logs to see which user called the API to create the VM. 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-audit 
https://azure.microsoft.com/en-us/blog/analyze-azure-audit-logs-in-powerbi-more/

**Comment by jan-wang** [comment]
Thanks!
I suggest Azure add such info to the property of a VM. It's truly useful for Enterprise account administrator.
Sometimes we need find the owner of a VM and ask he/she do some operations.

**Comment by jan-wang** [comment]
@singhkays, But how should I mapping the operation to a VM?
E.g. one user can create multiple VMs, how should I get the corresponding logs to a specific VM?

**Comment by singhkays** [comment]
@jan-wang That will involve digging through the logs but the other solution I think will work for you is using a combination of tags + policies. Here's an example of how to enforce each resource in your org is created with a tag. The example below talks about costCenter but that property can be anything that makes sense for your use case

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-policy-tags#require-tag

```
{
  "if": {
    "not" : {
      "field" : "tags",
      "containsKey" : "costCenter"
    }
  },
  "then" : {
    "effect" : "deny"
  }
}
```

**Comment by cormacpayne** [comment]
@jan-wang closing this issue as it seems Kay (@singhkays) has addressed your comments above. Please feel free to re-open this issue if that is not the case.
