### ISSUE TITLE
New-​Azure​Rm​Web​App​Slot clones slot sticky app settings

### ISSUE THREAD

**Issue by carlwoodhouse** [Azure/azure-powershell#3934]
The cmdlet New-​Azure​Rm​Web​App​Slot clones all the appsettings from the production slot, even ones which are marked as sticky to the production slot.

Not sure this is the desired behaviour?

**Comment by cormacpayne** [comment]
@Nking92 Hey Nicholas, would you mind taking a look at this issue?

**Comment by panchagnula** [comment]
@carlwoodhouse  yes during create all settings including the sticky settings are cloned.

**Comment by carlwoodhouse** [comment]
hmm ok, seems wrong as those settings are supposed to be sticky to a particular slot .. imo :)
