### ISSUE TITLE
Get-AzureRemoteDesktopFile -Launch parameter does not perform as expected

### ISSUE THREAD

**Issue by vhusker** [Azure/azure-powershell#394]
The help for Get-AzureRemoteDesktopFile indicates that I should be able to to do this:
Get-AzureRemoteDesktopFile -ServiceName "myservice" -Name "MyVM-01_IN_0" –Launch, no RDP windows is opened, even though it returns this information:
![image](https://cloud.githubusercontent.com/assets/6845844/7658764/8d50bc5e-fb02-11e4-89ab-059178894faf.png)

If I instead do this:
![image](https://cloud.githubusercontent.com/assets/6845844/7658769/a1f917d2-fb02-11e4-94fc-4fbc82cb48bc.png)
 I get the expected behavior of the RDP windows opening up and asking for my login credentials.

If you are supposed to specify -Launch $True then the help file should be updated, and the cmdlet should return an error if you use -Launch without the boolean value after.  If you are supposed to use -Launch without the $True then the cmdlet needs to be changed so that this works.

**Comment by singhkay** [comment]
@hyonholee Can you take a look at this? Thanks!

**Comment by singhkay** [comment]
Closing as fixed
