### ISSUE TITLE
Get-AzurePublishSettingsFile doesn't work with a FileSystem PSDrive

### ISSUE THREAD

**Issue by vhusker** [Azure/azure-powershell#395]
I have a PublishSettingsFile stored on my OneDrive.  The path to the folder it resides in on my OneDrive is mapped to a FileSystem PSDrive.
![image](https://cloud.githubusercontent.com/assets/6845844/7658813/fa81a310-fb02-11e4-9998-21009e15f65a.png)

![image](https://cloud.githubusercontent.com/assets/6845844/7658831/1e52a3b6-fb03-11e4-8372-00221f51c513.png)
![image](https://cloud.githubusercontent.com/assets/6845844/7658836/2e956a4c-fb03-11e4-954e-69b67d5f8186.png)

However, if I type the full path to the file using my local file system it works as expected.
![image](https://cloud.githubusercontent.com/assets/6845844/7658851/67ca6286-fb03-11e4-9dee-bc6d494e79d7.png)

I should be able to import a PublishSettingsFile using a FileSystem PSDrive.

**Comment by devigned** [comment]
@markcowl I've labelled this as team. Do you agree?

**Comment by hovsepm** [comment]
Current PS cmdlets do not support path discovery with PSDrive, However you can get the same effect by using Get-Item in your scripts. e.g. 
```
Import-AzurePublishSettingsFile -PublishSettingsFile $(Get-Item OneDrivePS:\YourPublishSettingsFile.publishsettings)
```
