### ISSUE TITLE
Obtaining an auth file should be easier.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#3963]
### Cmdlet(s)
N/A.

### PowerShell Version
N/A.

### Module Version
N/A.

### OS Version
N/A.

### Description

Creating an auth file should be easier (one cmdlet).  For example, the file created here
(https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-get-started?view=azure-dotnet#set-up-authentication) could be embeddedi n a cmdlet.

### Debug Output
N/A.

### Script/Steps for Reproduction
N/A.

**Comment by markcowl** [comment]
@twitchax Is this about creating an auth file [including creating the service principal, adding role authorization to the service principal, and then creatign the file], accepting auth files for PowerShell authentication, or both?

**Comment by twitchax** [comment]
@markcowl, the former.  Basically, it would be nice if the steps [here](https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-authenticate?view=azure-dotnet#mgmt-auth) were 1 - 3 cmdlet class rather than a multistep process and the creation of a file manually.

**Comment by twitchax** [comment]
Closing.  ADAL should define such a file if such a file should be generated by tools and consumed by tools.
