### ISSUE TITLE
Update Newtonsoft.Json to version 10.0

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3967]
### Description

Once Newtonsoft.Json -compatible version of Hyak.Common has been released for netcore, update Newtonsoft.Json to 10.0 in the common runtime.

- [ ] Determine which modules must be republished and start notifying partners aoub the change
- [ ] Update references to All ARM modules to new test management packages
- [ ] Storage (if any depednency)
- [ ] Run tests with new runtimes and packages using Newtonsoft.Json 10

**Comment by markcowl** [comment]
- [ ] Direct usage of deprecated properties in Newtonsoft.Json (which RP?) in cmdlets
- [ ] Direct usage of newtonsoft.json deprecated properties in tests (which RPs)?
- [ ] Old versions of management libraries (which RPs)?
  - [ ] Update to latest library
  - [ ] Push generated code into repo
  - [ ] Republish older package

**Comment by cormacpayne** [comment]
Removed obsolete JsonDictionaryContract.PropertyNameResolver (10.0.1)
- [CamelCasePropertyNamesWithOverridesContractResolver.cs](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Json/CamelCasePropertyNamesWithOverridesContractResolver.cs#L63)

Obsoleted TypeNameAssemblyFormat properties on JsonSerializer and JsonSerializerSettings
- [ResourceManagerSdkClient.cs](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/SdkClient/ResourceManagerSdkClient.cs#L133)
- [ResourceClientTests.cs](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.Resources.Test/Models.ResourceGroups/ResourceClientTests.cs#L217)
- [JsonUtilitiesTests.cs](https://github.com/Azure/azure-powershell/blob/preview/src/ServiceManagement/Common/Commands.Common.Test/Common/JsonUtilitiesTests.cs)

Obsoleted FormatterAssemblyStyle in non-full .NET targets

- [ResourceManagerSdkClient.cs](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/SdkClient/ResourceManagerSdkClient.cs#L133)
- [ResourceClientTests.cs](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.Resources.Test/Models.ResourceGroups/ResourceClientTests.cs#L217)
- [JsonUtilitiesTests.cs](https://github.com/Azure/azure-powershell/blob/preview/src/ServiceManagement/Common/Commands.Common.Test/Common/JsonUtilitiesTests.cs)

**Comment by FeodorFitsner** [comment]
Hi guys,

What are the current plans to update JSON library to v10?
