### ISSUE TITLE
Add live run for package smoke test cmdlets

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3968]
### Description

Add a daily live run for smoke test installation scripts, using the latest bits in the preview branch

- [x] Clean up and check-in installation test scripts

- Compute
  - VM
  - **VMSS** - This test takes 35 minutes or more, currently excluding it, needs revision
  - https://github.com/Azure/azure-powershell/issues/5306
- **KeyVault**
  - **Secrets (Data Plane)** - Hard-coded keyvault names, needs revision
  - https://github.com/Azure/azure-powershell/issues/5305
- Network
  - Virtual Network
- Profile
  - Context
  - Subscription
- Resources
  - **Resource** - Mocked resource group names cause some tests to fail, removed from current set of tests, needs revision
  - **Template Deployment** - Hard-coded locations and mocked resource group names, needs revision
  - https://github.com/Azure/azure-powershell/issues/5311
- Sql
  - **Database** - Removed all marked tests for this as they took a while to run
  - https://github.com/Azure/azure-powershell/issues/5316
  - Server
- Storage
  - Account Management
  - **Blob (Data Plane)** - No tests for this
  - https://github.com/Azure/azure-powershell/issues/5314
- **Tags**
  - **Tags on Resources** - Tests in Resources exist, Tags project has no tests. Tag test currently fails, needs revision
  - https://github.com/Azure/azure-powershell/issues/5311
- Websites
  - WebApp

- [x] ~~Add necessary KeyVault entities for live test credentials~~
- [x] Add in necessary logging for reporting failures; determine where runs will be reported
- [x] Add automation to build packages, install packages, and run installation tests from a signed build of the repo
- [x] Schedule runs in Jenkins

### Cost: 10

**Comment by markcowl** [comment]
Some details in #4571

**Comment by MiYanni** [comment]
The RPs in the description that are in **bold** with test issues a need to be addressed in some kind of roll-up 'test investigation' task. The tests themselves have issues running, and Cormac mentioned that some tests, even running non-live, take too long. So, need to pull those things out and make it their own issue. Otherwise, this task has the necessary components to run properly. Will make a pull request later today.

**Comment by MiYanni** [comment]
I've created separate issues per RP/resource area. These issues are linked in the original description.

**Comment by MiYanni** [comment]
Changes are now merged in. Closing...
