### ISSUE TITLE
Clean up module package files in post-build script

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3971]
### Description

Remove unnecessary DLLs, folder, and miscellanaous files from the package directories for modules as part of package creation.  This includes extraneous psd1 files, localization files for downloaded modules, and the like

### Cost :2

**Comment by cormacpayne** [comment]
Fix for this found in PR https://github.com/Azure/azure-powershell/pull/4734

**Comment by cormacpayne** [comment]
This has been merged in PR https://github.com/Azure/azure-powershell/pull/4921
