### ISSUE TITLE
Update module definitions for common runtime

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3972]
### Description

- [ ] Look at class composition for Common modules - split classes between abstractions related modules and cmdket related modules, and ensure that abstractions-related modules have no depeendencies on cmdlet-related common modules
- [ ] Add common runtime assembly loading to psm1 definition for profile module
- [ ] Remove dependent modules in the common runtime for each module package
- [ ] Add script transformations to the build tools for these changes to the packaging build step
- [ ] Move dependencies on AzureRm.Profile to ```ModuleVersion``` instead of ```RequiredVersion``` for all AzureRm modules
- [ ] Perform installation tests across PowerShell 3, 4, 5, 5.1 to verify correct execution of existing modules with the new runtime

**Comment by cormacpayne** [comment]
This has been merged in PR https://github.com/Azure/azure-powershell/pull/4921
