### ISSUE TITLE
Allow specifying domain or tenant id when logging in

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3974]
### Description

Tokens stored in the cache under domain name are not retrievable using the tenant ID.  Update authentication code (both stack-dev and preview) to allow logging in using domain or tenant ID.

- [ ] Add extra authentication hop if domain is provided instaead of guid tenant Id to retrieve the token for the tenantID.
- [ ] Add live tests to verify login using both tenantId and domain name

**Comment by cormacpayne** [comment]
This has been fixed and will be available in version 6.7.0 of `AzureRM`
