### ISSUE TITLE
A context retrieved using New-AzureStorageContext command is incompatible with Start-AzureVirtualNetworkGatewayDiagnostics and Start-AzureVNetGatewayDiagnostics

### ISSUE THREAD

**Issue by asktomsk** [Azure/azure-powershell#3976]
### Cmdlet(s)
New-AzureStorageContext 
Start-AzureVirtualNetworkGatewayDiagnostics
Start-AzureVNetGatewayDiagnostics

### PowerShell Version
5.1.14393.576
### Module Version
Azure 4.0.1 (Azure.Storage 3.0.1)

### OS Version
Windows 10, Windows Server 2016

### Description
I faced the problem when AzureStorageContext retrieved using `New-AzureStorageContext` command is incompatible with `Start-AzureVirtualNetworkGatewayDiagnostics` and `Start-AzureVNetGatewayDiagnostics` input parameters.
Error:
```
Start-AzureVirtualNetworkGatewayDiagnostics : 
Cannot bind parameter 'StorageContext'. 
Cannot convert the "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" 
value of type "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" to
type 
"Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext".
```
it means you use the latest (May 15 2017) version of Azure powershell module: 4.0.1
This version has some incompatibility with latest Azure.Storage 3.0.1.

You need to remove it and install Azure 3.8.0 (April 5th 2017) it has Azure.Storage 2.8.0 as dependency. https://www.powershellgallery.com/packages/Azure/3.8.0

```
Uninstall-Module -Name Azure.Storage
Uninstall-Module -Name Azure
Install-Module -Name Azure -RequiredVersion 3.8.0
```

This combination works fine.

**Comment by DdenBraver** [comment]
This issue is linked to #3979 .
Seems this is due to the type change from: Microsoft.WindowsAzure.Commands.**Common**.Storage.AzureStorageContext to Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext

**Comment by markcowl** [comment]
All such parameters should have been changed to the common interface type IStorageContext, so that they are independent of the storage account version.
