### ISSUE TITLE
New-AzureRmResourceGroup : Run Login-AzureRmAccount to login.

### ISSUE THREAD

**Issue by farzadmf** [Azure/azure-powershell#3978]
### PowerShell Version
5.1.15063.296

### OS Version
10.0.15063.296

### Description
I'm out of ideas. I search the Internet, but no success! I run `Login-AzureRmAccount` and I enter my credentials, but when I run `Login-AzureRmResourceGroup`, it tells me that I need to log in. I'm doing it in ISE, and I have no idea why it isn't working

### Debug Output
```
DEBUG: 22:03:20 - NewAzureResourceGroupCmdlet begin processing with ParameterSet __AllParameterSets'.
New-AzureRmResourceGroup : Run Login-AzureRmAccount to login.
At line:1 char:1

+ New-AzureRmResourceGroup -Name $ResourceGroup -Location $Location
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-AzureRmResourceGroup], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupCmdlet
```

### Script/Steps for Reproduction
```
Login-AzureRmAccount -SubscriptionName "my-subscription"
$ResourceGroup = "MyResourceGroup"
$Location = "east us"
New-AzureRmResourceGroup -Name $ResourceGroup -Location $Location
```

Any help is greatly appreciated. I'm a beginner with Azure, but I'm pretty sure this command should work!

**Comment by farzadmf** [comment]
Apparently, I had to manually update the `AzureRm.Resources` module to the latest version. Is there a way to make sure all Azure modules are up-to-date?

Thanks

**Comment by spottedmahn** [comment]
@farzadmf how did you manually update AzureRm.Resources?

**Comment by farzadmf** [comment]
@spottedmahn  Sorry for the (very) late reply. To be honest, I'm not sure how I did it. One way is to use Microsoft Web Platform Installer to install (and update) AzurePowerShell.
Also, there's [this link](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-4.4.1) that explains how to install it in PowerShell

**Comment by spottedmahn** [comment]
@farzadmf thanks for the reply.  That's what I ended up doing [per this thread](https://github.com/Azure/azure-powershell/issues/2688#issuecomment-275481866)

**Comment by farzadmf** [comment]
@spottedmahn  now thank *you* for the reply, I didn't know about the msi installation option
