### ISSUE TITLE
Error when using the -Storagecontext parameter when running Set-AzureRmVMDiagnosticsExtension

### ISSUE THREAD

**Issue by DdenBraver** [Azure/azure-powershell#3979]
### Cmdlet(s)
Set-AzureRmVMDiagnosticsExtension

### PowerShell Version
PSVersion: 5.1.14409.1005

### Module Version
AzureRM.Storage: 3.0.1
Azure: 4.0.1

### OS Version
10.0.14409.1005

### Description
Code:
```
$Storagekey = (Get-AzureRmStorageAccountKey -ResourceGroupName $diagresourcegroupname -Name $diagstorageaccountname).Value[0]
$Storagecontext = New-AzureStorageContext -StorageAccountName $diagstorageaccountname -StorageAccountKey $Storagekey
$tempfile = "$env:temp\diagnosticsconfig.xml"
    
Set-AzureRmVMDiagnosticsExtension -ResourceGroupName $ResourceGroupName -VMName $VMName -StorageContext $Storagecontext -DiagnosticsConfigurationPath $tempfile
```

Returns: 
```
Set-AzureRmVMDiagnosticsExtension : Cannot bind parameter 'StorageContext'. Cannot convert the "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" value of 
type "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" to type "Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext".
At line:5 char:109
+ ... urceGroupName -VMName $VMName -StorageContext $Storagecontext -Diagno ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-AzureRmVMDiagnosticsExtension], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Azure.Commands.Compute.SetAzureRmVMDiagnosticsExtensionCommand
```

This issue started after updating from Azure PowerShell 3 to 4

### Script/Steps for Reproduction
See description

**Comment by markcowl** [comment]
This is likely about the parameter not being changed to IStorageContext.  Investigate, and verify that making this change resolves the issue.

**Comment by kfarris9** [comment]
getting the same problem with Publish-AzureVMDscConfiguration.  Is there a workaround?

**Comment by mattcowen** [comment]
As per the previous, is there a workaround please?

**Comment by DdenBraver** [comment]
@mattcowen : Workaround I am using is to specify the storageaccountname and storageaccount key, rather then the storagecontext.

**Comment by markcowl** [comment]
This should be fixed in the release going out 8/9

**Comment by jontreynes** [comment]
@DdenBraver can you share that workaround?

Is this similar to your solution b/c I'm getting the storage account key to get the context, but the context is still a mismatch of type storageaccount... (Notice the "Common" part that is the mismatch)
$pw = Get-AzureRmStorageAccountKey -ResourceGroupName $resourcegroupname -Name $storage_accountname
$context = New-AzureStorageContext -StorageAccountName $storage_accountname -StorageAccountKey $pw.Value[0] -Protocol Https
`PS C:\WINDOWS\system32> if ($context.GetType().Name -eq "AzureStorageContext"){

$autobackupconfig = New-AzureRmVMSqlServerAutoBackupConfig -Enable `
    -RetentionPeriodInDays $retentionperiod -StorageContext $context `
    -ResourceGroupName $storage_resourcegroupname -BackupSystemDbs `
    -BackupScheduleType $backupscheduletype -FullBackupFrequency $fullbackupfrequency `
    -FullBackupStartHour $fullbackupstarthour -FullBackupWindowInHours $fullbackupwindow `
    -LogBackupFrequencyInMinutes $logbackupfrequency
}
New-AzureRmVMSqlServerAutoBackupConfig : Cannot bind parameter 'StorageContext'. Cannot convert the 
"Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" value of type 
"Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" to type 
"Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext".
At line:4 char:61
+ ...    -RetentionPeriodInDays $retentionperiod -StorageContext $context `
+                                                                ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureRmVMSqlServerAutoBackupConfig], ParameterBinding 
   Exception
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Azure.Commands.Compute.NewAzureVMSqlSe 
   rverAutoBackupConfigCommand 
`

**Comment by DdenBraver** [comment]
@jontreynes I could use the StorageAccountName and StorageAccountKey parameters instead of using the Storagecontext parameters as a work-around.
You could do the same for the New-AzureRmVMSqlServerAutoBackupConfig cmdlet by using the -StorageUri -StorageKey parameters :-)

**Comment by akinsriv** [comment]
@kfarris9- There is a workaround if you are looking for a solution to Publish-AzureVMDSCConfiguration. You may do the following:
$StorageAccount= Get-AzureStorageAccount -Name "YouStorageAccount"
$context= $StorageAccount.Context

Now you can pass this $context in any cmdlet which identifies the object type for context as Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext.

Worked for me :)

**Comment by akinsriv** [comment]
@kfarris9  There is a workaround if you are looking for a solution to Publish-AzureVMDSCConfiguration. You may do the following:
$StorageAccount= Get-AzureStorageAccount -Name "YouStorageAccount"
$context= $StorageAccount.Context
Now you can pass this $context in any cmdlet which identifies the object type for context as Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext.
Worked for me :)
