### ISSUE TITLE
Get-​Azure​Storage​Blob docs say "Accept wildcard characters: false"

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-powershell#3980]
### Cmdlet(s)
Get-​Azure​Storage​Blob

### Module Version
4.0

### Description
The docs at https://docs.microsoft.com/en-us/powershell/module/azure.storage/get-azurestorageblob?view=azurermps-4.0.0 say that no wildcard character is allowed for the `-Blob` parameter, however isn't that exactly what *is* allowed? It says "Specifies a name or name pattern, which can be used for a wildcard search."

**Comment by cormacpayne** [comment]
@blueww Hey Wei, would you mind taking a look at this issue?

**Comment by blueww** [comment]
@letmaik 
Thanks for report that!
The -Blob parameter supports wildcard. Will try to update the doc and cmdlets help soon.

**Comment by cormacpayne** [comment]
@letmaik @blueww the fix has been merged and will appear in the documentation of the June release of Azure PowerShell. I have also commented on an existing issue in the `platyPS` repository regarding this error we are seeing when trying to document the `SupportsWildcards` attribute (link is in Wei's PR)
