### ISSUE TITLE
The parameter name for "SubscriptionID" wad changed from v4.0.0

### ISSUE THREAD

**Issue by gutzeit1106** [Azure/azure-powershell#3987]
The property of subscription info was changed from v4.0.0.

Before the following commit, the object acquired by Get-AzureRmSubscription cmdlet has the property "SubscriptionId". But from v4.0.0, this property name is changed to "Id".

https://github.com/Azure/azure-powershell/commit/ee5e317d986a2b597d7754979f51402fcf825caf

If this change is unexpected, the property name should be returned to "SubscriptionId".

**Comment by gutzeit1106** [comment]
sorry. this changed was written in the breaking changes.

https://github.com/Azure/azure-powershell/blob/preview/documentation/release-notes/migration-guide.4.0.0.md#breaking-changes-to-profile-cmdlets

close this issue.

**Comment by markcowl** [comment]
@gutzeit1106 No worries, thanks for paying such close attention to the outputs.
