### ISSUE TITLE
Set-AzureRmVMDiagnosticsExtension install windows diagnostic extension on Linux VM

### ISSUE THREAD

**Issue by Lickkylee** [Azure/azure-powershell#3993]
### PowerShell Version
PSVersion                      5.1.15063.296

### OS Version
BuildVersion                   10.0.15063.296

### Description
Set-AzureRmVMDiagnosticsExtension always attempts to install the Windows diagnostic extension in the VM, even if the VM is Linux-based. There is no parameter to the cmdlet that will override the PublisherName or Type of the extension to be installed, and the cmdlet doesn’t check the VM OS type to make a choice.

**Comment by markcowl** [comment]
@signhkays can you take a look?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please let us know if this issue is still a concern.
