### ISSUE TITLE
Get-AzureRMSubscription No longer returns Subscriptionname and SubscriptionID

### ISSUE THREAD

**Issue by Georgexp** [Azure/azure-powershell#3995]
### Cmdlet(s)
Get-AzureRMSubscription 

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with PSVersion                      5.1.14393.206  

### Module Version
Name                            Version
----                            -------
Azure                           4.0.1  
Azure.AnalysisServices          0.3.0  
AzureRM                         4.0.1  
AzureRM.profile                 3.0.0  

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
Name                           Value                                                                                                                                                          
----                           ----                                                                                                                                  
BuildVersion                   10.0.14393.206   

### Description
In the new version of Get-AzureRMSubscription Name and ID are returned instead of SubscriptionID and SubscriptionName while this is less verbous it would be good to also return these as hidden attributes as older scripts and published scripts like https://gallery.technet.microsoft.com/scriptcenter/ASM-to-ARM-VM-Migration-504edee2#content
Leverage Subscriptionname and SubscriptionID

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
https://gallery.technet.microsoft.com/scriptcenter/ASM-to-ARM-VM-Migration-504edee2#content

**Comment by markcowl** [comment]
@Georgexp This is by design.  Please see the migration guide here: https://github.com/Azure/azure-powershell/blob/preview/documentation/release-notes/migration-guide.4.0.0.md which describes the changes, as referenced from the release notes for AzureRM here: https://www.powershellgallery.com/packages/AzureRM/4.0.0

**Comment by markcowl** [comment]
@Georgexp Just posted an update to the script that shoudl work with the new cmdlets here:  https://gist.github.com/markcowl/cf294e4524115a68c034a6604e2fed1d  Please give it a try.
