### ISSUE TITLE
New-AzureRmAppServicePlan does not support a -Tag parameter

### ISSUE THREAD

**Issue by doctordns** [Azure/azure-powershell#3996]
### Cmdlet(s)
New-AzureRmAppServicePlan
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1
### Module Version
2.0.1
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
Win10 CU
### Description
The New-AzureRmAppServicePlan cmdlet does not provide the facility to add tags to a new plan when it's created. Yes, you can add tags later, but for consistency this cmdlet should allow tags to be set when the app service plan is created.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

1. Type:
New-AzureRmAppServicePlan -?

2. Note the lack of a -Tag parameter.

**Comment by markcowl** [comment]
@akurmi can you take a look?

**Comment by markcowl** [comment]
```<nit>```this should be ```-Tag``` ```</nit>```

**Comment by doctordns** [comment]
Whoops - well spotted Mark. I was writing a script and wanted to add tags but couldn't hence this issue. But yes, it should be -Tag!

I'll take a look at other NEW-* cmdlets to see what other ones need this added. Is adding a -Tags parameter difficult? I assume you can leverage the actual code from othEr cmdlets?

**Comment by doctordns** [comment]
This cmdlet still needs a ##-Tag## parameter.
:-)

**Comment by panchagnula** [comment]
Sorry this is not something we currently support on our backend & currently we have no plans to support this. NOTE: this is the same behavior on portal as well
