### ISSUE TITLE
Get-AzureRmExpressRouteCircuitRouteTable : 'peeringName' cannot be null.

### ISSUE THREAD

**Issue by ld0614** [Azure/azure-powershell#4011]
### Cmdlet(s)
Get-AzureRmExpressRouteCircuitRouteTable

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

Name                           Value                                                                                                           
----                           -----                                                                                                           
PSVersion                      5.1.15063.296                                                                                                   
PSEdition                      Desktop                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                         
BuildVersion                   10.0.15063.296                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                 
WSManStackVersion              3.0                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                             
SerializationVersion           1.1.0.1 

### Module Version
Script     4.0.0      AzureRM.Network
Script     3.0.0      AzureRM.Profile 

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

BuildVersion                   10.0.15063.296        

### Description
When running the command Get-AzureRmExpressRouteCircuitRouteTable a request is presented for the following values: ResourceGroupName, ExpressRouteCircuitName, DevicePath.  After entering the values the command fails

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

DEBUG: 16:00:58 - GetAzureRmExpressRouteCircuitRouteTable begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 16:01:00 - using account id '*********'...
DEBUG: [Common.Authentication]: Authenticating using Account: '***********', environment: 'AzureCloud', tenant: '*********'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/22/2017 15:01:00: ************ - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/****************/
	Resource: https://management.core.windows.net/
	ClientId: ********************
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (1 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/22/2017 15:01:00:  - TokenCache: Deserialized 1 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/22/2017 15:01:00: ************ - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/22/2017 15:01:00: ************ - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/22/2017 15:01:00: ************ - TokenCache: 53.7947626966667 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/22/2017 15:01:00: ************ - TokenCache: A matching item (access token or refresh token or both) was found
 in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/22/2017 15:01:00: ************ - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An acce
ss token was retuned:
	Access Token Hash: ****************************************
	Refresh Token Hash: *****************************************
	Expiration Time: 05/22/2017 15:54:48 +00:00
	User Hash: ******************************************
	

Get-AzureRmExpressRouteCircuitRouteTable : 'peeringName' cannot be null.
At line:1 char:1
+ Get-AzureRmExpressRouteCircuitRouteTable -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmExpressRouteCircuitRouteTable], ValidationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureRmExpressRouteCircuitRouteTable
 
DEBUG: AzureQoSEvent: CommandName - Get-AzureRmExpressRouteCircuitRouteTable; IsSuccess - False; Duration - 00:00:03.8145883; Exception - Micros
oft.Rest.ValidationException: 'peeringName' cannot be null.
   at Microsoft.Azure.Management.Network.ExpressRouteCircuitsOperations.<BeginListRoutesTableWithHttpMessagesAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Network.ExpressRouteCircuitsOperations.<ListRoutesTableWithHttpMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Network.ExpressRouteCircuitsOperationsExtensions.<ListRoutesTableAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Network.ExpressRouteCircuitsOperationsExtensions.ListRoutesTable(IExpressRouteCircuitsOperations operations, St
ring resourceGroupName, String circuitName, String peeringName, String devicePath)
   at Microsoft.Azure.Commands.Network.GetAzureRmExpressRouteCircuitRouteTable.Execute() in D:\workspace\powershell-sign\src\ResourceManager\Net
work\Commands.Network\ExpressRouteCircuit\Stats\GetAzureExpressRouteCircuitRouteTableCommand.cs:line 64
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet() in D:\workspace\powershell-sign\src\ResourceManager\Network\Commands.Ne
twork\Common\NetworkBaseCmdlet.cs:line 51
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord() in D:\workspace\powershell-sign\src\Common\Commands.Common\
AzurePSCmdlet.cs:line 642;
DEBUG: Finish sending metric.
DEBUG: 16:01:02 - GetAzureRmExpressRouteCircuitRouteTable end processing.
DEBUG: 16:01:02 - GetAzureRmExpressRouteCircuitRouteTable end processing.

### Script/Steps for Reproduction

Run Get-AzureRmExpressRouteCircuitRouteTable with no parameters
Type all requested values
Command will run and then fail as it does not request the value of peeringName

**Comment by markcowl** [comment]
@nupurkot Can you take a look?

**Comment by maddieclayton** [comment]
Hey @DeepakRajendranMsft is this an issue with the cmdlet or with the SDK call? If -PeeringType should be mandatory I can make that change, or if the SDK call should be different I can make that change.  Please let me know, this seems to have been around for a long time and I can still repro.

**Comment by EvgenyAgafonchikov** [comment]
Updated by https://github.com/Azure/azure-powershell/pull/7664 (peering is mandatory now)
