### ISSUE TITLE
Functionality break in piping in version 4.0

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-powershell#4015]
### Cmdlet(s)
Get-AzureRmSubscription
Set-AzureRmContext  

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

4.0
### Module Version
AzureRM.PRofile 4.0

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
All

### Description
Due to this change - https://github.com/Azure/azure-powershell/commit/ee5e317d986a2b597d7754979f51402fcf825caf#diff-90b817a265897ea23770dd2284185aeaL88 
Piping scenario is broken when users want to pass PSAzureSubscription to Get-AzureRmSubscription . Binding does not happen and Get-Subscription outputs all available subscriptions. 
The repro is actually in the test that we use in CI but I assume after the changes in the above commit Tests was not re-recorded and just used the previous recording. 

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
``` PowerShell
       $allSubscriptions = Get-AzureRmSubscription
       $firstSubscription = $allSubscriptions[0]
       $id = $firstSubscription.Id
       $tenant = $firstSubscription.TenantId
       $name = $firstSubscription.Name
       $subscription = $firstSubscription | Get-AzureRmSubscription
```

Last line will not contain a single first subscription because Get-AzureRmSubscription still has old parameter names – SubscriptionID and SubscriptionName (should be Id and Name according to ps1xml file changes).

**Comment by markcowl** [comment]
This should really be resolved using an InputObject parameter set.  However, there is no additional information provided from Get-AzureRmSubscription that is't available from simply displaying the returned subscription to the screen.  Closign as won't fix.
