### ISSUE TITLE
Login-AzureRmAccount -Credential Not Working with Organizational Account

### ISSUE THREAD

**Issue by JLunda** [Azure/azure-powershell#4016]
### Cmdlet(s)
Login-AzureRmAccount

### PowerShell Version
Major | Minor | Build | Revision
------------ | ------- | ------ | ---------
5 | 1 | 15063 | 296     

### Module Version

Using Get-Module:

ModuleType | Version Name | ExportedCommands
-------------- | ---------------- | ----------------------
Script | 3.0.0 | AzureRM.profile | {Add-AzureRmAccount, Add-AzureRmEnvironment, Disable-AzureRmDataCollection, Enable-AzureRmDataCollection...}

Using Get-Command -Module "AzureRM.profile":

CommandType | Name | Version | Source
----------- | ---- | ------- | ------                                                                                                           
Alias | Login-AzureRmAccount | 3.0.0 | AzureRM.profile 

### OS Version

Major | Minor | Build | Revision
----- | ----- | ----- | --------
10 | 0 | 15063 | 296     

### Description

The **Login-AzureRmAccount** cmdlet is failing for an organizational account that requires redirection through Secure Web Logon, when providing a credential through the -Credential parameter.  The login succeeds when using Login-AzureRmAccount's interactive prompt for login.

Please note that I do not believe this to be a duplicate of this issue (https://github.com/Azure/azure-powershell/issues/1253), as it does not seem to be an issue of whether or not I am specifying Tenant ID.

<img width="284" alt="secureweblogon1-redacted" src="https://cloud.githubusercontent.com/assets/1091216/26373712/983ec682-3fd0-11e7-82d7-ca6e6ffe7c19.png">
<img width="284" alt="secureweblogon2-redacted" src="https://cloud.githubusercontent.com/assets/1091216/26373714/984d0e54-3fd0-11e7-8d69-cd03f46f467d.png">

### Debug Output

```DEBUG: 2:56:13 PM - AddAzureRMAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'c990bb7a-51f4-439b-bd36-9c07fb1041c0', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-2
27b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/c990bb7a-51f4-439b-bd36-9c07fb1041c0/', CorrelationId: '00000000-0000-0000-0000-
000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'c990bb7a-51f4-439b-bd36-9c07fb1041c0', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a2
58-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/23/2017 18:56:13: 847698fe-d55b-41ff-8dd3-f08519c93190 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/c990bb7a-51f4-439b-bd36-9c07fb1041c0/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (0 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/23/2017 18:56:13: 847698fe-d55b-41ff-8dd3-f08519c93190 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/23/2017 18:56:13: 847698fe-d55b-41ff-8dd3-f08519c93190 - TokenCache: No matching token was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/23/2017 18:56:13: 847698fe-d55b-41ff-8dd3-f08519c93190 - <CreateByDiscoveryAsync>d__0: Sending user realm discovery request to 'https://login.microsoftonline.com/common/UserRealm/jlu
nda1@ford.com?api-version=1.0'

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/23/2017 18:56:13: 847698fe-d55b-41ff-8dd3-f08519c93190 - <PreTokenRequest>d__4: User with hash 'dNLIGjx+MVxztfvuIE7TfZdOt3wtOmWcua5QLSLjk/0=' detected as 'Federated'

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Error: 4 : 
DEBUG: 05/23/2017 18:56:13: 847698fe-d55b-41ff-8dd3-f08519c93190 - <RunAsync>d__0: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: missing_federation_metadata_url: Federation Me
tadata Url is missing for federated user. This user type is unsupported.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenNonInteractiveHandler.<PreTokenRequest>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
	ErrorCode: missing_federation_metadata_url

Login-AzureRmAccount : -Credential parameter can only be used with Organization ID credentials. For more information, please refer to 
http://go.microsoft.com/fwlink/?linkid=331007&clcid=0x409 for more information about the difference between an organizational account and a Microsoft account.
At C:\Users\jlunda\Desktop\SQLDBUtility\SQLDatabaseUtility.ps1:328 char:29
+ ... inAccount = Login-AzureRmAccount -Credential $Credential -TenantId "c ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

```

### Script/Steps for Reproduction
**NOTE:** I am passing the UserName and Password Variables in from a call to the Function.  I have already verified these values.
```
$SecurePassword = ConvertTo-SecureString -String $Password -AsPlainText -Force
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList ($UserName, $SecurePassword)
$LoginAccount = Login-AzureRmAccount -Credential $Credential -TenantId "c990bb7a-51f4-439b-bd36-9c07fb1041c0" -ErrorAction Stop
```

**Comment by sphibbs** [comment]
This is either a misconfig of STS  because the metadata is not available
or its due to the org requiring web logon. This means you cannot use non interactive login.

Please update error message to list all the reasons why users can see this issue so they have a course of action.

**Comment by andylyonette** [comment]
I'm also seeing this issue.  Does anyone know if this has ever worked or if there's a previous module version that works?  I've tried 3.8.0 but am seeing the same issue there as well.

Thanks,
Andy

**Comment by markcowl** [comment]
@andylyonette This has nothingto do with AzurePowerShell, it has to do with the STS configuration for your organization

**Comment by markcowl** [comment]
### Description
Improve error message when authentication fails - provide a good course of action depedneing on the details of the returned exception

### Cost: 2

**Comment by cormacpayne** [comment]
Using `Resolve-AzureRmError` returns the necessary information to debug the error.
