### ISSUE TITLE
Get-AzureVMDscExtensionStatus on Azure 9.1 is returning 404 blob errors

### ISSUE THREAD

**Issue by v-racast** [Azure/azure-powershell#402]
For the full bug report, see http://stackoverflow.com/questions/30314053/

Publish-AzureVMDscConfiguration (Publish-AzureVMDscConfiguration -ConfigurationPath C:\dsc\IIsInstall.ps1 -ContainerName $StorageContainer -StorageContext $StorageContext -Force -verbose)  seems to be working fine, as the blob gets put up properly, with Lease Duration Unspecified, Lease State: Available, and Lease Status: Unlocked

Digging deeper, when the LCM requests the blob, the url used is with a lease that expires immediately.  

From LCM logs on fbconfigtest9:

VERBOSE: [2015-05-19T21:33:17] Downloading 
https://fbazureloggingstorage.blob.core.windows.net/windows-powershell-dsc9/IISInstall.ps1.zip?sv=2014-02-14&sr=b&sig=tlWC78xuZ
chF4RsPCrFOb6YeLCuHzbAC4ERZDAc8pMI%3D&se=2015-05-19T22%3A20%3A48Z&sp=rd to 
C:\Packages\Plugins\Microsoft.Powershell.DSC\1.10.1.0\bin..\DSCWork\IISInstall.ps1.0\IISInstall.ps1.zip
VERBOSE: [2015-05-19T21:33:18] An error occurred processing the configuration package; removing 
C:\Packages\Plugins\Microsoft.Powershell.DSC\1.10.1.0\bin..\DSCWork\IISInstall.ps1.0

Timestamp of the publish operation:
[2015-05-19 21:20:46] Publish-AzureVMDscConfiguration to fbazureloggingstorage in windows-powershell-dsc9 complete

Timestamp of the 404 error:
[2015-05-19 21:35:05] An error occurred downloading the Azure Blob: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."

The url seems to indicate that the lease should not expire until 22:20:48, yet returns a 404 frin the target machine. 

Hitting the web request from powershell returns the following (note the timestamps):
PS C:\Users\LocalAzureAdmin> $r = iwr "https://fbazureloggingstorage.blob.core.windows.net/windows-powershell-dsc9/IISIn
stall.ps1.zip?sv=2014-02-14&sr=b&sig=tlWC78xuZchF4RsPCrFOb6YeLCuHzbAC4ERZDAc8pMI%3D&se=2015-05-19T22%3A20%3A48Z&sp=rd"
iwr : BlobNotFoundThe specified blob does not exist. RequestId:0227f8bf-0001-006f-6f7d-92853d000000
Time:2015-05-19T21:51:29.6091290Z
At line:1 char:6
- $r = iwr "https://fbazureloggingstorage.blob.core.windows.net/windows ...
-      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
    eption
  - FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
    PS C:\Users\LocalAzureAdmin> $t = [DateTime]::Now
    PS C:\Users\LocalAzureAdmin> $t

Tuesday, May 19, 2015 9:52:07 PM

PS C:\Users\LocalAzureAdmin> $t.ToLocalTime()

Tuesday, May 19, 2015 9:52:07 PM

An earlier test run returned the following, when I went into the built VM to investigate:
-<Error>

<Code>AuthenticationFailed</Code>

<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:86ae9339-0001-002a-4874-9258ac000000 Time:2015-05-19T20:46:51.1315744Z</Message>

<AuthenticationErrorDetail>Signed expiry time [Tue, 19 May 2015 20:28:31 GMT] must be after signed start time [Tue, 19 May 2015 20:46:51 GMT]</AuthenticationErrorDetail>

**Comment by v-racast** [comment]
Azure Storage Explorer shows the blob is there at: 
http://fbazureloggingstorage.blob.core.windows.net/windows-powershell-dsc9/IIsInstall.ps1.zip
Last modified at:
5/19/2015 9:20:46 PM +00:00

**Comment by v-racast** [comment]
The publish code doesn't even set a lease on the blob...

**Comment by v-racast** [comment]
It does use a SAS token. and it appears to be properly set at 1 hour. Perhaps the ?sv=2014-02-14 blob service has a bug in it?

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
