### ISSUE TITLE
New-AzureRmMIWebService is not working when using JSON from Export-AmlWebServiceDefinitionFromExperiment.

### ISSUE THREAD

**Issue by WallyDoodlez** [Azure/azure-powershell#4022]
### Cmdlet(s)
New-AzureRmMIWebService 

### PowerShell Version
PSVersion                      5.1.14393.1198

### OS Version
BuildVersion                   10.0.14393.1198

### Description
I followed instructions from [here](https://docs.microsoft.com/en-us/azure/machine-learning/machine-learning-deploy-consume-web-service-guide) in trying to deploy a web service in power shell from a training experiment. I developed my own set of power shell scripts as exhibited below, but I am always getting an error when trying to use the New-AzureRmMIWebService when using the JSON definition generated by Export-AmlWebServiceDefinitionFromExperiment. I am pretty sure I am doing everything right, and suspect this maybe a bug.

### Debug Output

> Are you sure you want to create a new machine learning web service "FakeInstance123_FakeClient123_Webservice" ?
> [Y] Yes [N] No [S] Suspend [?] Help (default is "Yes"):
> New-AzureRmMlWebService : Error converting value "True" to type 'Microsoft.Azure.Management.MachineLearning.WebServices.Models.WebServiceParameter'. Path 'Package.Nodes.node1.Parameters.['Append
> score columns to output']', line 281, position 128.
> At C:\Users\wallacec\Desktop\powershell\azureDBI.ps1:96 char:1
> + New-AzureRmMlWebService  -Location "South Center US" -DefinitionFile  ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : CloseError: (:) [New-AzureRmMlWebService], JsonSerializationException
>     + FullyQualifiedErrorId : Error converting value "True" to type 'Microsoft.Azure.Management.MachineLearning.WebServices.Models.WebServiceParameter'. Path 'Package.Nodes.node1.Parameters.['Appen
>    d score columns to output']', line 281, position 128.,Microsoft.Azure.Commands.MachineLearning.Cmdlets.NewAzureMLWebService
> 

### Script/Steps for Reproduction
```
#retrive an export of the web-service definition file from the experiment
Export-AmlWebServiceDefinitionFromExperiment -ExperimentId $checkExp.ExperimentId -OutputFile $webserviceDefinitionPath
Write-Host "Exported training webservice definition to ${trainingJsonPath}"
CheckErrorThenExist

#modify the JSON so that it includes the json storage account information and commitmentplan
$configJObject = (Get-Content config.json) -join "`n" | ConvertFrom-Json
$storageAccount = $configJObject.StorageAccount
$commitmentPlan = $configJObject.CommitmentPlan

#add the commitmentPlan and StorageAccount object to the json and the save it
$wsDefObject = (Get-Content $webserviceDefinitionPath) -join "`n" | ConvertFrom-Json
$wsDefObject | Add-Member  -Name "StorageAccount" -Value $storageAccount -MemberType NoteProperty
$wsDefObject | Add-Member  -Name "CommitmentPlan" -Value $commitmentPlan -MemberType NoteProperty


$newWsDefObject = New-Object psCustomObject
$newWsDefObject | Add-Member -Name "Properties" -value $wsDefObject -MemberType NoteProperty

$newWsDefObject |ConvertTo-Json  -Depth 20 | Out-File .\newTrainingWebService.json 



#deploy the experiment as a training web-service
New-AzureRmMlWebService  -Location "South Center US" -DefinitionFile .\newTrainingWebService.json -ResourceGroupName "Apps" -Name $webserviceName
```

**Comment by eligne-pro** [comment]
Exactly same comportment here, seems like a regression in AzureMLPS module: worked in 0.11.0, don't work in 0.15.2

**Comment by foreverchanges** [comment]
This is still broken and is preventing us (and presumably others) from creating an automated release pipeline that facilitates an appropriate versioning and release strategy for New-AzureRmMlWebService resources. Is it possible to say when / if this is likely to be fixed?

**Comment by cormacpayne** [comment]
@NonStatic2014 Hey Klein, would you mind taking a look at this issue?

**Comment by v-strudm-msft** [comment]
We see this was posted over two years ago, but was never addressed so are closing it. Our apologies. Should this still be an issue, please re-open this issue and we will respond on a timely basis. Thank you.
