### ISSUE TITLE
Cmdlet reference markdown missing URLs in Related Links section.

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4025]
### Cmdlet(s)
As many as 59 cmdlet reference files have empty URLs in the Related Links section.

For example, in Set-AzureRmDataLakeStoreItemExpiry.md: 

> ## RELATED LINKS
> 
> [Get-AzureRmDataLakeStoreItem]()

This results in a bad link in the web presentation.

### Affected cmdlets
DataLakeStore\Commands.DataLakeStore\help\Set-AzureRmDataLakeStoreItemExpiry.md
HDInsight\Commands.HDInsight\help\New-AzureRmHDInsightCluster.md
LogicApp\Commands.LogicApp\help\Get-AzureRmIntegrationAccountReceivedIcn.md
Network\Commands.Network\help\Add-AzureRmRouteFilterRuleConfig.md
Network\Commands.Network\help\Get-AzureRmApplicationGatewayBackendHealth.md
Network\Commands.Network\help\Get-AzureRmNetworkWatcher.md
Network\Commands.Network\help\Get-AzureRmNetworkWatcherFlowLogStatus.md
Network\Commands.Network\help\Get-AzureRmNetworkWatcherNextHop.md
Network\Commands.Network\help\Get-AzureRmNetworkWatcherPacketCapture.md
Network\Commands.Network\help\Get-AzureRmNetworkWatcherSecurityGroupView.md
Network\Commands.Network\help\Get-AzureRmNetworkWatcherTopology.md
Network\Commands.Network\help\Get-AzureRmNetworkWatcherTroubleshootingResult.md
Network\Commands.Network\help\New-AzureRmNetworkWatcher.md
Network\Commands.Network\help\New-AzureRmNetworkWatcherPacketCapture.md
Network\Commands.Network\help\New-AzureRmPacketCaptureFilterConfig.md
Network\Commands.Network\help\New-AzureRmRouteFilter.md
Network\Commands.Network\help\New-AzureRmRouteFilterRuleConfig.md
Network\Commands.Network\help\Remove-AzureRmApplicationGatewaySslPolicy.md
Network\Commands.Network\help\Remove-AzureRmNetworkWatcher.md
Network\Commands.Network\help\Remove-AzureRmNetworkWatcherPacketCapture.md
Network\Commands.Network\help\Set-AzureRmNetworkWatcherConfigFlowLog.md
Network\Commands.Network\help\Start-AzureRmNetworkWatcherResourceTroubleshooting.md
Network\Commands.Network\help\Stop-AzureRmNetworkWatcherPacketCapture.md
Network\Commands.Network\help\Test-AzureRmNetworkWatcherIPFlow.md
Profile\Commands.Profile\help\Add-AzureRmEnvironment.md
Profile\Commands.Profile\help\Disable-AzureRmDataCollection.md
Profile\Commands.Profile\help\Enable-AzureRmDataCollection.md
Profile\Commands.Profile\help\Get-AzureRmContext.md
Profile\Commands.Profile\help\Get-AzureRmEnvironment.md
Profile\Commands.Profile\help\Remove-AzureRmEnvironment.md
Profile\Commands.Profile\help\Set-AzureRmContext.md
Profile\Commands.Profile\help\Set-AzureRmEnvironment.md
Resources\Commands.Resources\help\Get-AzureRmADAppCredential.md
Resources\Commands.Resources\help\Get-AzureRmADApplication.md
Resources\Commands.Resources\help\Get-AzureRmADGroup.md
Resources\Commands.Resources\help\Get-AzureRmADGroupMember.md
Resources\Commands.Resources\help\Get-AzureRmADServicePrincipal.md
Resources\Commands.Resources\help\Get-AzureRmADSpCredential.md
Resources\Commands.Resources\help\Get-AzureRmADUser.md
Resources\Commands.Resources\help\Get-AzureRmRoleAssignment.md
Resources\Commands.Resources\help\Get-AzureRmRoleDefinition.md
Resources\Commands.Resources\help\New-AzureRmADAppCredential.md
Resources\Commands.Resources\help\New-AzureRmADApplication.md
Resources\Commands.Resources\help\New-AzureRmADServicePrincipal.md
Resources\Commands.Resources\help\New-AzureRmADSpCredential.md
Resources\Commands.Resources\help\New-AzureRmADUser.md
Resources\Commands.Resources\help\New-AzureRmRoleAssignment.md
Resources\Commands.Resources\help\New-AzureRmRoleDefinition.md
Resources\Commands.Resources\help\Remove-AzureRmADAppCredential.md
Resources\Commands.Resources\help\Remove-AzureRmADApplication.md
Resources\Commands.Resources\help\Remove-AzureRmADServicePrincipal.md
Resources\Commands.Resources\help\Remove-AzureRmADSpCredential.md
Resources\Commands.Resources\help\Remove-AzureRmADUser.md
Resources\Commands.Resources\help\Remove-AzureRmRoleAssignment.md
Resources\Commands.Resources\help\Remove-AzureRmRoleDefinition.md
Resources\Commands.Resources\help\Set-AzureRmADApplication.md
Resources\Commands.Resources\help\Set-AzureRmADServicePrincipal.md
Resources\Commands.Resources\help\Set-AzureRmADUser.md
Resources\Commands.Resources\help\Set-AzureRmRoleDefinition.md

**Comment by sdwheeler** [comment]
@markcowl - Tara @TaraMeyer is working on this. See https://mseng.visualstudio.com/VSChina/_workitems/edit/1006523

**Comment by TaraMeyer** [comment]
@sdwheeler @markcowl - this has been fixed and is addressed in this pr waiting for review and approval:https://github.com/Azure/azure-powershell/pull/4027.

**Comment by sdwheeler** [comment]
PR#4027 has been merged. Closing issue.
