### ISSUE TITLE
Update US Gov endpoints

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-powershell#4031]
Update all the endpoints that are related to US Gov cloud

Cost: 1 (without testing)

**Comment by markcowl** [comment]
### Description
- [ ] Get Fairfax subscription
- [ ] Run scenarios to verify endpoints
- [ ] Update endppoints

### Cost: 2

**Comment by cormacpayne** [comment]
This issue is fixed in PR https://github.com/Azure/azure-powershell/pull/4822
