### ISSUE TITLE
New-AzureRMStreamAnalyticsTransformation Failed to create new Transformation

### ISSUE THREAD

**Issue by zechariahks** [Azure/azure-powershell#4033]
### Cmdlet(s)
New-AzureRMStreamAnalyticsTransformation

### PowerShell Version
5.0.10586.117

### OS Version
10.0.10586.117

### Description
Getting BadRequest response while trying to create a new transformation in Stream Analytics Job.

![image](https://cloud.githubusercontent.com/assets/13693218/26466990/ad20967c-4145-11e7-8140-db3d287382af.png)

### Script/Steps for Reproduction

1. Create an Empty Stream Analytics Job in Azure with Streaming Inputs Count "6".
2. Create Input and Outputs using PowerShell Cmdlets
3. Execute below command to create new transformation.

New-AzureRMStreamAnalyticsTransformation -ResourceGroupName $resourceGroupName –File "C:\Transformation.json" –JobName "jobname" –Name "transformationame" -Force 

Note: Transformation JSON file also set to use Streaming Units 6.

**Comment by atpham256** [comment]
Sorry for the extremely delayed response.

It sounds like you already have a transformation created based on the error message. Have you done a Get-AzureRMStreamAnalyticsJob to see if there is a transformation already created?

**Comment by zechariahks** [comment]
Hi,


Thanks for your reply. sorry I forgot to update this ticket. I have figured out the issue.


Issue is with my transformation JSON file. It has the \r \n characters. After I cleaned up these characters, the same command worked fine.


I guess, the error message is misleading. If there is a problem with my JSON, it should have thrown invalid JSON.


Regards,

Zech

________________________________

**Comment by atpham256** [comment]
Hi Zech,

If you could send me the JSON you were using that reproduces this issue, I can take a look.

Thanks,
Anthony

**Comment by zechariahks** [comment]
@atpham256 Below is the JSON file which was throwing the error. After removing \r\n from this file, it worked.

{      
 "Properties": { 
    "Query": " SELECT  DATEADD(hour, -7, \r\n DATETIMEFROMPARTS(DATEPART(year,UTC_TRANS_DTM)   ,DATEPART(month,UTC_TRANS_DTM)   \r\n ,DATEPART(day,UTC_TRANS_DTM)   ,DATEPART(hour,UTC_TRANS_DTM)   ,CASE    WHEN \r\n 
    DATEPART(minute,UTC_TRANS_DTM) >= 0 AND DATEPART(minute,UTC_TRANS_DTM) < 15 THEN 00           WHEN \r\n                    DATEPART(minute,UTC_TRANS_DTM) >= 15 AND 
    DATEPART(minute,UTC_TRANS_DTM) < 30 THEN 15   WHEN \r\n  DATEPART(minute,UTC_TRANS_DTM) >= 30 AND DATEPART(minute,UTC_TRANS_DTM) < 45 THEN 30   ELSE \r\n  45   END   ,00,00)) AS BUS_TRANS_DTM,   CHANNEL_TYPE_CD,   COUNT(TRANS_ID) AS 
    \r\n TRANS_COUNT,   SUM(TRY_CAST(TOTAL_TRANS_AMT AS FLOAT)/100) AS TOTAL_TRANS_AMT     INTO \r\n PbiOut FROM EhIn     GROUP BY DATEADD(hour, -7, 
    \r\n DATETIMEFROMPARTS(DATEPART(year,UTC_TRANS_DTM) ,DATEPART(month,UTC_TRANS_DTM)   \r\n    ,DATEPART(day,UTC_TRANS_DTM) ,DATEPART(hour,UTC_TRANS_DTM)   ,CASE    WHEN \r\n DATEPART(minute,UTC_TRANS_DTM) >= 0 AND DATEPART(minute,UTC_TRANS_DTM) < 15 THEN 00   WHEN \r\n 
    DATEPART(minute,UTC_TRANS_DTM) >= 15 AND DATEPART(minute,UTC_TRANS_DTM) < 30 THEN 15   WHEN \r\n  DATEPART(minute,UTC_TRANS_DTM) >= 30 AND  DATEPART(minute,UTC_TRANS_DTM) < 45 THEN 30   ELSE \r\n   45   END,00,00)),CHANNEL_TYPE_CD,TUMBLINGWINDOW(second, 30)    \r\n  
    SELECT UTC_TRANS_DTM, AVG(TRY_CAST(TOTAL_TRANS_AMT AS FLOAT)/100) AS AVG_TRANS_AMT INTO \r\n  PbiOut2 FROM EhIn GROUP BY UTC_TRANS_DTM, TUMBLINGWINDOW(second, 15)",
    "StreamingUnits": 1
  }
}

**Comment by cormacpayne** [comment]
@atpham256 Hey Anthony, would you mind taking a look at the above response? We should verify if this is still an issue as well. If not, we can go ahead and close it.

**Comment by atpham256** [comment]
I was unfortunately not able to repro. I successfully created a transformation using the JSON the customer provided in this thread.

Based on the error message, I believe the customer initially provided the wrong transformation name so the RP thought the customer was trying to create a new transformation and hence, the customer got the error message that they are trying to exceed the maximum number of transformations allowed for a job.
