### ISSUE TITLE
Is there a way to enableKeyVault on a Data Lake Store vía powershell?

### ISSUE THREAD

**Issue by cmendible** [Azure/azure-powershell#4045]
Hi guys, is there a way to enableKeyVault on a Data Lake Store (DLS) vía powershell? I know you can create the access policy for the DLS Principal using something like: 

`Set-AzureRmKeyVaultAccessPolicy -VaultName $vaultName -ObjectId (Get-AzureRmADServicePrincipal -SearchString "RN_[Data Lake StoreName]").Id -PermissionsToKeys encrypt, decrypt, get`

But after I do so, I need to browse to the DLS blade  in the portal (not good for automation) and click enable. Looking at the logs I've figured that the called methods is: _Microsoft.DataLakeStore/accounts/enableKeyVault/action_ which seems to be availble for the [.NET SDK](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datalake.store.accountoperationsextensions.enablekeyvault?view=azuremgmtdatalakestore-2.1.0-preview) but not for powershell. 

Is this correct?

**Comment by markcowl** [comment]
@cmendible Note that you can list (and use) provider operations using the ```Get-AzureRmProviderOperation``` cmdlet in Azure PowerShell, so it is possible to do this with generic resource manager cmdlets.

@begoldsm Do we have or plan to add this functionality to typed cmdlets for DataLake?

**Comment by cmendible** [comment]
I was not aware of that cmdlet! Ill check it!

Thanks!

**Comment by cmendible** [comment]
The operation Microsoft.DataLakeStore/accounts/enableKeyVault is not listed when running:
`Get-AzureRmProviderOperation -OperationSearchString Microsoft.DataLakeStore/*`

**Comment by begoldsm** [comment]
There was a PR request just last week to explicitly add this command: https://github.com/Azure/azure-powershell/pull/4023

As for the operation path it should be here:
providers/Microsoft.DataLakeStore/accounts/{accountName}/enableKeyVault

**Comment by cmendible** [comment]
That's great news! hope it gets merged and released soon.

**Comment by begoldsm** [comment]
This has been merged and should be in the next release! I won't close this out, though, until that release happens.

**Comment by cmendible** [comment]
Hi guys, I can confirm that the cmdlet is present and working in the latest [4.1.0-June2017](https://github.com/Azure/azure-powershell/releases/tag/v4.1.0-June2017) release.

Thanks!
