### ISSUE TITLE
Executing Remove-AzureRmRoleAssignment as Service Principal results in an exception

### ISSUE THREAD

**Issue by pascalnaber** [Azure/azure-powershell#4051]
### Cmdlet(s)
Remove-AzureRmRoleAssignment

### PowerShell Version
5.1.14393.1198 

### Module Version
4.0.2 (23-05-17)

### OS Version
10.0.14393.1198

### Description
After logging in as Service Principal and giving this Service Principal AD access (_Company Administrator_). It is able to execute New-AzureRmRoleAssignment, but is not able to execute Remove-AzureRmRoleAssignment.

How should a Service Principal be able to Remove a RoleAssignment?

### Debug Output
Remove-AzureRmRoleAssignment : The provided information does not map to a role assignment.
At line:1 char:1
+ Remove-AzureRmRoleAssignment -ObjectId 8e3af657-a8ff-443c-a75c-2fe8c4 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Remove-AzureRmRoleAssignment], KeyNotFoundException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.RemoveAzureRoleAssignmentCommand

### Script/Steps for Reproduction
See https://github.com/Azure/azure-powershell/issues/3549

**Comment by darshanhs90** [comment]
@pascalnaber This issue seems to be fixed from https://github.com/Azure/azure-powershell/issues/3407 
Let us know if you are getting the same error even after using the new azure powershell version viz 4.3.1

**Comment by Steven-N** [comment]
@darshanhs90 I am still getting the same exception.

Running on AzureRM 4.4.0. The SP has owner access on the subscription and has been given Graph API access on the directory (R/W). Has anyone else been reporting issues still?

**Comment by darshanhs90** [comment]
Closing this due to no response from the customer [as this was fixed from #3407 ] .Re-open the same if it persists
