### ISSUE TITLE
New-​Azure​Rm​Application​Gateway​Url​Path​Map​Config has Optional Params DefaultBackendAddressPool but it fails if not specified

### ISSUE THREAD

**Issue by solankisamir** [Azure/azure-powershell#4056]
### Cmdlet(s)
New-​Azure​Rm​Application​Gateway​Url​Path​Map​Config

### PowerShell Version
4.0.2
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
When we changed the powershell cmd from
New-AzureRmApplicationGatewayUrlPathMapConfig -Name "urlpathmap" -PathRules $echoapiRule -DefaultBackendAddressPool $apimProxyBackendPool -DefaultBackendHttpSettings $apimPoolSetting

to 

New-AzureRmApplicationGatewayUrlPathMapConfig -Name "urlpathmap" -PathRules $echoapiRule 

we started getting the error below. Based on the documentation, those parameters are optional parameters
https://docs.microsoft.com/en-us/powershell/module/azurerm.network/new-azurermapplicationgatewayurlpathmapconfig?view=azurermps-4.0.0

**What we want to achieve:**
We want Application Gateway to throw 4xx Error when somebody tries to access a Url Path not already described in the Path Rules.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

New-AzureRmApplicationGatewayUrlPathMapConfig : Parameter set cannot be resolved using the specified named parameters.
At D:\Scripts\IntegrateApimWithAppGatewayPathBased.ps1:75 char:15
   + ... rlPathMap = New-AzureRmApplicationGatewayUrlPathMapConfig -Name "urlp ...
    +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureRmAppl...rlPathMapConfig], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.Network.NewAzureApplicationGatewayUrlPath
   MapConfigCommand

### Script/Steps for Reproduction

New-AzureRmApplicationGatewayUrlPathMapConfig -Name "urlpathmap" -PathRules $echoapiRule

**Comment by shahabhijeet** [comment]
@markjbrown can you take a look at this.

**Comment by markjbrown** [comment]
@amitsriva  for Application Gateway. Can you take a look please?

thanks.

**Comment by cgddrd** [comment]
I can confirm that this is also an issue for `Set-​Azure​Rm​Application​Gateway​Url​Path​Map​Config`. Although they are not documented as required parameters, if I fail to specify values for `-DefaultBackendAddressPool` and `-DefaultBackendHttpSettings`, then I receive the error: `Parameter set cannot be resolved using the specified named parameters.`

**Comment by maddieclayton** [comment]
@akshaysngupta Can you take a look at this issue?

**Comment by akshaysngupta** [comment]
This is an issue on the validation side. Will update the issue with the timeline of the fix.

**Comment by EvgenyAgafonchikov** [comment]
Added parameter sets to avoid intersection of incompatible parameters, adjusted required/optional in parameter sets: #8381
