### ISSUE TITLE
Get-AzureRemoteDesktopFile in AzureResourceManager mode always returns access denied

### ISSUE THREAD

**Issue by brisebois** [Azure/azure-powershell#406]
Using the Switch-AzureMode AzureResourceManager

Get-AzureRemoteDesktopFile -ResourceGroupName 'armmonstervm' -Name 'msarmbrisebois' -LocalPath 'D:\'

always returns Access Denied no matter what directory I use and even if I give everyone full access to the directory.

Furthermore, the Launch flag is missing.

**Comment by singhkay** [comment]
Adding @DeepakRajendranMsft for -Launch flag feature. 
@brisebois You need to specify the name of the RDP file as well for the LocalPath. This should work 'D:\vm.rdp'

**Comment by singhkay** [comment]
Closing, please reopen if this is still an issue.
