### ISSUE TITLE
Get-AzureRmKeyVault : ErrorAction does not take effect for incorrect ResourceGroup

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-powershell#4065]
### Cmdlet(s)
Get-AzureRmKeyVault

### PowerShell Version
5.0.10586.117

### OS Version
10.0.10586.117

### Description
ErrorAction is not taking effect for Get-AzureRmKeyVault with incorrect ResourceGroup provided, inspite of the response is below,

error": {
    "code": "ResourceGroupNotFound",
    "message": "Resource group 'eastus' could not be found.

### Debug Output
DEBUG: 9:55:49 AM - GetAzureKeyVault begin processing with ParameterSet 'GetVaultByName'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 9:55:51 AM - using account id 'Pradebban@.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'Pradebban@.com', environment:
'AzureCloud', tenant: 'c990041c0'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/02/2017 13:55:51: 32ad7356-64e6-7084 - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/c9901c0/
 Resource: https://management.core.windows.net/
 ClientId: 195095945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (4 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/02/2017 13:55:51:  - TokenCache: Deserialized 4 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 06/02/2017 13:55:51: 32ad6ea47084 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/02/2017 13:55:51: 32a9506ea47084 - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 06/02/2017 13:55:51: 32ea47084 - TokenCache: 55.7426626316667 minutes left until
token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/02/2017 13:55:51: 32a6ea47084 - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/02/2017 13:55:51: 32ad76ea47084 - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: I4aMkxntz6Oejw+rRvaZk8=
 Refresh Token Hash: lXfkfcxiHgptqETJa7FrShSk=
 Expiration Time: 06/02/2017 14:51:36 +00:00
 User Hash: YaUHf8ySNHQAKMhXg=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/02/2017 13:55:51: 508538a6 - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/c99fb1041c0/
 Resource: https://management.core.windows.net/
 ClientId: 1950a295945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (4 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/02/2017 13:55:51:  - TokenCache: Deserialized 4 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 06/02/2017 13:55:51: 508caff1538a6 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/02/2017 13:55:51: 5aff1538a6 - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 06/02/2017 13:55:51: 508ff1538a6 - TokenCache: 55.7426123833333 minutes left until
token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/02/2017 13:55:51: 5038a6 - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/02/2017 13:55:51: 508f1538a6 - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: I4aMkRvaZk8=
 Refresh Token Hash: lXFrShSk=
 Expiration Time: 06/02/2017 14:51:36 +00:00
 User Hash: YaUHKMhXg=

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/62951599fdce2/resourceGroups/eastus/providers/Microso
ft.KeyVault/vaults/?api-version=2016-10-01

Headers:
x-ms-client-request-id        : 59e3e48cd06
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 2edee869eb11c
x-ms-correlation-request-id   : 2ede5869eb11c
x-ms-routing-request-id       : NORTHCENTRALUS:20170602T135557Z:2ede869eb11c
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Fri, 02 Jun 2017 13:55:56 GMT

Body:
{
  **"error": {
    "code": "ResourceGroupNotFound",
    "message": "Resource group 'eastus' could not be found."**
  }
}

DEBUG: 9:55:52 AM - GetAzureKeyVault end processing.
DEBUG: 9:55:52 AM - GetAzureKeyVault end processing.

### Script/Steps for Reproduction
Get-AzureRmKeyVault -VaultName "ValidVaultName" -ResourceGroupName "Invalid/WrongRGName"

thanks,
Pradebban Raja

**Comment by shahabhijeet** [comment]
@Pradebban Get requests are non-error returning pattern.
So this is by design.

**Comment by Pradebban** [comment]
@shahabhijeet , i do not agree, please re-open.
@markcowl - please advice.

below example (again a get request) returns an error 

PS C:\Windows\system32> Get-AzureRmApiManagement -ResourceGroupName 12345 -Name "12345"
**Get-AzureRmApiManagement : ResourceGroupNotFound: Resource group '12345' could not be found.**
