### ISSUE TITLE
New-AzureRmApiManagement should allow creating API with Empty Path

### ISSUE THREAD

**Issue by solankisamir** [Azure/azure-powershell#4069]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by solankisamir** [comment]
Fix for the issue should be available with https://github.com/Azure/azure-powershell/milestone/31

**Comment by baldia-taman** [comment]
I'm not able to add a new API with empty path parameter using AzureRM version 6.7.0 . There also there is no other API with empty path/ root path. Is this expected in new release?
