### ISSUE TITLE
Disable-AzureRmVMDiskEncryption has no safeguard to prevent rendering a Linux VM inaccessible

### ISSUE THREAD

**Issue by ejarvi** [Azure/azure-powershell#4078]
### Cmdlet(s)
Disable-AzureRmVMDiskEncryption

### PowerShell Version
5.1.14393.1198

### OS Version
10.0.14393.1198

### Debug Output
n/a

### Script/Steps for Reproduction
Disable-AzureRmVMDiskEncryption will render an encrypted Linux VM inaccessible.  The cmdlet documentation does not make it clear that this is currently windows only, and the cmdlet is missing the safeguard that would check the target VM type and prevent this from happening.

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by singhkays** [comment]
@cormacpayne  This needs to be looked at by the disk encryption team.

**Comment by ejarvi** [comment]
I am working on ADE Linux and also willing to investigate and fix.  I opened the issue because I want to ensure we track to resolution.  The cmdlet is Windows only right now, but that isn’t always clear to Linux users since most other commands are hybrids.  Since it is unsafe to use when targeting a Linux VM, I would really like to get a safeguard added here.

**Comment by cormacpayne** [comment]
@SudhakaraReddyEvuri would you mind taking a look at this issue?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
