### ISSUE TITLE
Add-AzureAccount does not create TokenCache.dat

### ISSUE THREAD

**Issue by afengli** [Azure/azure-powershell#4080]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

5.1.14393.1198

### Module Version
4.0.2

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.14393.1198
### Description
Add-AzureAccount does not create TokenCache.dat. This will cause command like Get-AzureService to fail.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

Try this script:

    # Set User and Password
    $AzureName = "user@domain.onmicrosoft.com"
    
    $AzurePassword = ConvertTo-SecureString 'Password' -AsPlainText -Force

    # Get Credential Object
    $AzureRMCredential = New-Object -TypeName System.Management.Automation.PSCredential($AzureName, $AzurePassword)

    # Removing Azure Account (Classic)
    Write-Host "Executing Remove-AzureAccount and Clear-AzureProfile (Classic)..."
    Get-AzureAccount | ForEach-Object { Remove-AzureAccount $_.ID -Force }
    Clear-AzureProfile -Force

    # Add Azure account for classic resources
    Write-Host "Executing Add-AzureAccount (Classic)..."
    Add-AzureAccount -Credential $AzureRMCredential -Verbose
    #Login-AzureRmAccount -Credential $AzureRMCredential -Verbose

    Select-AzureSubscription -SubscriptionId 'be8b8d49-5fe4-4abb-bac1-xxxxxxxxxxxx'

    Get-AzureService -Debug

**Comment by afengli** [comment]
some more information. debug shows the call  Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache.AfterAccessNotification was not called during the token creation. 

Even for this one Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache..ctor(Byte[])

**Comment by cormacpayne** [comment]
@afengli would you mind providing us with the debug output when executing this cmdlet? You can do so by setting `$DebugPreference=Continue" before executing the set of cmdlets.

Also do you have permissions to read/write in "AppData/Roaming/Windows Azure PowerShell"?

**Comment by afengli** [comment]
@cormacpayne , yes I am doing it.  you can also try to reproduce it easily. I see multiple instances that the 4.x version module broke the authentication and Azure context.

**Comment by afengli** [comment]
@cormacpayne 
Adding "$DebugPreference=Continue" does not give more output. There is no permission restriction on th e folder.

**Comment by markcowl** [comment]
@afengli We have found the root cause - if you don't have a TokenCache.dat file already, it is not creat6ed at startup.  Filed an issue here: https://github.com/Azure/azure-powershell/issues/4144 to fix in the current milestone

**Comment by markcowl** [comment]
Fixed.  Will ship in in July release
