### ISSUE TITLE
Set-AzureRmApplicationGatewayBackendAddressPool is not setting BackendIPAddresses

### ISSUE THREAD

**Issue by darkshade9** [Azure/azure-powershell#4083]
### Cmdlet(s)
Set-AzureRmApplicationGatewayBackendAddressPool

### PowerShell Version
5.1.14393.953

### Module Version
4.0.2

### OS Version
10.0.14393.953

### Description
Set-AzureRmApplicationGatewayBackendAddressPool is not setting BackendIPAddresses, it is simply returning the Gateway object.

### Debug Output
DEBUG: 12:36:10 PM - GetAzureApplicationGatewayCommand end processing.
DEBUG: 12:36:10 PM - GetAzureApplicationGatewayCommand end processing.
DEBUG: 12:36:10 PM - SetAzureApplicationGatewayBackendAddressPoolCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 12:36:10 PM - using account id 'aa@bb.cc'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'aa@bb.cc', environment: 'AzureCloud', tenant: 'TENANTID'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/06/2017 16:36:10: 3d5e095f-499c-4448-94c5-92cbdf4fbf96 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/TENANTID/
	Resource: https://management.core.windows.net/
	ClientId: CLIENTID
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (1 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 06/06/2017 16:36:10: 3d5e095f-499c-4448-94c5-92cbdf4fbf96 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/06/2017 16:36:10: 3d5e095f-499c-4448-94c5-92cbdf4fbf96 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 06/06/2017 16:36:10: 3d5e095f-499c-4448-94c5-92cbdf4fbf96 - TokenCache: 59.9453316716667 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/06/2017 16:36:10: 3d5e095f-499c-4448-94c5-92cbdf4fbf96 - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/06/2017 16:36:10: 3d5e095f-499c-4448-94c5-92cbdf4fbf96 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: VHTWde0hJYrjfYuzdbdovdTHLNOohyDqtleFnRgLPeI=
	Refresh Token Hash: tXlljxfsA5BKEJuBPAnFnM0e3ckFeDMlaL0Loy34X7s=
	Expiration Time: 06/06/2017 17:36:06 +00:00
	User Hash: 1hjb9QTbMH155qmUq594gOBglpvmL9X37m+HxoilQ0s=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/06/2017 16:36:10:  - TokenCache: Serializing token cache with 1 items.

Sku                                 : Microsoft.Azure.Commands.Network.Models.PSApplicationGatewaySku
SslPolicy                           : 
GatewayIPConfigurations             : {appGatewayIpConfig}
AuthenticationCertificates          : {}
SslCertificates                     : {wildcard.krush.com}
FrontendIPConfigurations            : {appGatewayFrontendIP}
FrontendPorts                       : {appGatewayFrontendPort}
Probes                              : {}
BackendAddressPools                 : {appGatewayBackendPool}
BackendHttpSettingsCollection       : {appGatewayBackendHttpSettings}
HttpListeners                       : {appGatewayHttpListener}
UrlPathMaps                         : {}
RequestRoutingRules                 : {rule1}
WebApplicationFirewallConfiguration : 
OperationalState                    : Running
ProvisioningState                   : Succeeded
GatewayIpConfigurationsText         : [
                                        {
                                          "Subnet": {
                                            "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/virtualNetworks/usaelpas
                                      krunet001/subnets/App_Gateway_254"
                                          },
                                          "ProvisioningState": "Succeeded",
                                          "Name": "appGatewayIpConfig",
                                          "Etag": "W/\"c6a66d8c-e73d-4cc9-bb05-0e5def2963dc\"",
                                          "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/applicationGateways/usaelp
                                      askruwag001/gatewayIPConfigurations/appGatewayIpConfig"
                                        }
                                      ]
AuthenticationCertificatesText      : []
SslCertificatesText                 : [
                                      SANITIZED
                                      ]
FrontendIpConfigurationsText        : [
                                        {
                                          "PrivateIPAllocationMethod": "Dynamic",
                                          "PublicIPAddress": {
                                            "Id": 
                                      "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/publicIPAddresses/usaelpaskruwag001"
                                          },
                                          "ProvisioningState": "Succeeded",
                                          "Name": "appGatewayFrontendIP",
                                          "Etag": "W/\"c6a66d8c-e73d-4cc9-bb05-0e5def2963dc\"",
                                          "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/applicationGateways/usaelp
                                      askruwag001/frontendIPConfigurations/appGatewayFrontendIP"
                                        }
                                      ]
FrontendPortsText                   : [
                                        {
                                          "Port": 443,
                                          "ProvisioningState": "Succeeded",
                                          "Name": "appGatewayFrontendPort",
                                          "Etag": "W/\"c6a66d8c-e73d-4cc9-bb05-0e5def2963dc\"",
                                          "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/applicationGateways/usaelp
                                      askruwag001/frontendPorts/appGatewayFrontendPort"
                                        }
                                      ]
BackendAddressPoolsText             : [
                                        {
                                          "BackendAddresses": [
                                            {
                                              "IpAddress": "10.230.4.6"
                                            }
                                          ],
                                          "Name": "appGatewayBackendPool",
                                          "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/ResourceGroupNotSet/providers/Microsoft.Network/applicationGateways/Applic
                                      ationGatewayNameNotSet/backendAddressPools/appGatewayBackendPool"
                                        }
                                      ]
BackendHttpSettingsCollectionText   : [
                                        {
                                          "Port": 80,
                                          "Protocol": "Http",
                                          "CookieBasedAffinity": "Disabled",
                                          "RequestTimeout": 30,
                                          "AuthenticationCertificates": [],
                                          "ProvisioningState": "Succeeded",
                                          "Name": "appGatewayBackendHttpSettings",
                                          "Etag": "W/\"c6a66d8c-e73d-4cc9-bb05-0e5def2963dc\"",
                                          "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/applicationGateways/usaelp
                                      askruwag001/backendHttpSettingsCollection/appGatewayBackendHttpSettings"
                                        }
                                      ]
HttpListenersText                   : [
                                        {
                                          "FrontendIpConfiguration": {
                                            "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/applicationGateways/usae
                                      lpaskruwag001/frontendIPConfigurations/appGatewayFrontendIP"
                                          },
                                          "FrontendPort": {
                                            "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/applicationGateways/usae
                                      lpaskruwag001/frontendPorts/appGatewayFrontendPort"
                                          },
                                          "Protocol": "Https",
                                          "SslCertificate": {
                                            "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/applicationGateways/usae
                                      lpaskruwag001/sslCertificates/wildcard.krush.com"
                                          },
                                          "RequireServerNameIndication": "False",
                                          "ProvisioningState": "Succeeded",
                                          "Name": "appGatewayHttpListener",
                                          "Etag": "W/\"c6a66d8c-e73d-4cc9-bb05-0e5def2963dc\"",
                                          "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/applicationGateways/usaelp
                                      askruwag001/httpListeners/appGatewayHttpListener"
                                        }
                                      ]
RequestRoutingRulesText             : [
                                        {
                                          "RuleType": "Basic",
                                          "BackendAddressPool": {
                                            "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/applicationGateways/usae
                                      lpaskruwag001/backendAddressPools/appGatewayBackendPool"
                                          },
                                          "BackendHttpSettings": {
                                            "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/applicationGateways/usae
                                      lpaskruwag001/backendHttpSettingsCollection/appGatewayBackendHttpSettings"
                                          },
                                          "HttpListener": {
                                            "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/applicationGateways/usae
                                      lpaskruwag001/httpListeners/appGatewayHttpListener"
                                          },
                                          "ProvisioningState": "Succeeded",
                                          "Name": "rule1",
                                          "Etag": "W/\"c6a66d8c-e73d-4cc9-bb05-0e5def2963dc\"",
                                          "Id": "/subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/applicationGateways/usaelp
                                      askruwag001/requestRoutingRules/rule1"
                                        }
                                      ]
ProbesText                          : []
UrlPathMapsText                     : []
ResourceGroupName                   : API_Services-EastUS
Location                            : eastus
ResourceGuid                        : d522b622-9967-48de-bdb0-a2174505e358
Type                                : Microsoft.Network/applicationGateways
Tag                                 : 
TagsTable                           : 
Name                                : usaelpaskruwag001
Etag                                : W/"c6a66d8c-e73d-4cc9-bb05-0e5def2963dc"
Id                                  : /subscriptions/SANITIZEDSUBSCRIPTIONID/resourceGroups/API_Services-EastUS/providers/Microsoft.Network/applicationGateways/usaelpaskruwag001

DEBUG: 12:36:10 PM - SetAzureApplicationGatewayBackendAddressPoolCommand end processing.
DEBUG: 12:36:10 PM - SetAzureApplicationGatewayBackendAddressPoolCommand end processing.

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft Hey Deepak, would you mind taking a look at this issue?

**Comment by maddieclayton** [comment]
@akshaysngupta Can you take a look at this issue?

**Comment by akshaysngupta** [comment]
Unable to reproduce this issue. Cmdlet works as expected.
```
$app = Set-AzureRmApplicationGatewayBackendAddressPool -ApplicationGateway $app -Name $app.BackendAddressPools[0].Name -BackendIPAddresses 10.0.0.1
```

```
> $app.BackendAddressPools
BackendAddresses            : {Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayBackendAddress}
BackendIpConfigurations     :
ProvisioningState           :
Type                        :
BackendAddressesText        : [
                                {
                                  "IpAddress": "10.0.0.1"
                                }
                              ]
BackendIpConfigurationsText : null
Name                        : pool
Etag                        :
Id                          : ******
