### ISSUE TITLE
For changes that affect only one service, run only tests that are related to that service.

### ISSUE THREAD

**Issue by NelsonDaniel** [Azure/azure-powershell#4088]
### Description

Currently the PowerShell CI job runs all tests for every check-in. For changes that affect only one service run only the test for that service. This should improve the performance of testing.

- First we need to figure out what are the paths/files that are being changed.
- Then, we need to find the service associated with the paths that were changed.
  - The mappings between the services and the paths should be easily extensible when new services are added.
- Finally, run only the tests associated with the service.
- Verification
- [ ] Change to one folder in the list results for a list of tests running.
- [ ] Change to one folder outside the list results into all tests running.
- [ ] Changes to multiple folders result into a list of tests running.
- [ ] Documentation for adding a new service to the mapping.

### Cost

10

**Comment by markcowl** [comment]
Fixed
