### ISSUE TITLE
set-azureresource cmdlet fails in release 0.9.1

### ISSUE THREAD

**Issue by rayabueg** [Azure/azure-powershell#409]
The set-azureresrouce cmdlet fails in release 0.9.1.  It worked in release 0.9.0.  

PS C:\> $res = Set-AzureResource -Name $ProjectName -ResourceGroupName $WebResourceGroup -ResourceType Microsoft.Web/sites -ApiVersion $ApiVersion -PropertyObject $prop
DEBUG: 10:58:13 AM - SetAzureResourceCmdlet begin processing with ParameterSet 'Resource that resides at the subscription level.'.

Set-AzureResource : {
  "Error": {
    "Code": "LocationRequired",
    "Message": "The location property is required for this definition.",
    "Target": null,
    "Details": null
  }
}
At line:1 char:8
+ $res = Set-AzureResource -Name $ProjectName -ResourceGroupName $WebResourceGroup ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : LocationRequired,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet

**Comment by xingzhougmu** [comment]
Set-AzureResource : {
  "Error": {
    "Code": "LocationRequired",
    "Message": "The location property is required for this definition.",
    "Target": null,
    "Details": null
  }
}
At line:1 char:1
+ Set-AzureResource -ResourceGroupName $rgname -ResourceName $rname -ResourceType  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : LocationRequired,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzur
   eResourceCmdlet

**Comment by vivsriaus** [comment]
fixed
