### ISSUE TITLE
Save-AzureRmVhd and Managed Disks

### ISSUE THREAD

**Issue by MSSedusch** [Azure/azure-powershell#4090]
### Cmdlet(s)
Save-AzureRmVhd

### PowerShell Version
5.1.15063.296

### Module Version
3.0.1

### OS Version
10.0.15063.296

### Description
The Save-AzureRmVhd cmdlet does not support SAS token in the SourceUri and thus cannot download Managed Disks that are exported via Grant-AzureRmDiskAccess or Portal

I would love to see a Save-AzureRmDisk cmdlet that exports the Managed Disks, downloads it and revokes the access again. Alternatively, Save-AzureRmVhd should support a SAS URI.

### Script/Steps for Reproduction
$access = Grant-AzureRmDiskAccess -ResourceGroupName <group> -DiskName <disk name> -Access Read -DurationInSecond 3600
Save-AzureRmVhd -Source $access.AccessSAS -LocalFilePath <local path>

**Comment by cormacpayne** [comment]
@hyonholee @singhkays Hey guys, would you mind taking a look at this issue?

**Comment by singhkays** [comment]
@chagarw Is there anything special about MD SAS URI that is different from previous blob SAS URIs?

@hyonholee Can you take a look at why the MD SAS doesn't work?

**Comment by MSSedusch** [comment]
@singhkays I don't think there is anything special about MD SAS URI. I think the command never worked for SAS tokens only. It only works with Storage Account Keys or (Resource Group Name and access to the Storage Account in ARM)
But that is never the case for a MD

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
