### ISSUE TITLE
Microsoft.Azure.Commands.AnalysisServices.Models.AzureAnalysisServicesServer does not include a ResourceGroupName property

### ISSUE THREAD

**Issue by SiloReed** [Azure/azure-powershell#4092]
### Cmdlet(s)
Get-AzureRmAnalysisServicesServer

### PowerShell Version
PSVersion                      5.1.15063.296

### Module Version
AzureRM.AnalysisServices 0.3.0
### OS Version
BuildVersion                   10.0.15063.296

### Description
Microsoft.Azure.Commands.AnalysisServices.Models.AzureAnalysisServicesServer does not include a ResourceGroupName property. This is not consistent with other AzureRM objects 

### Debug Output
DEBUG: 3:06:54 PM - GetAzureAnalysisServicesServer begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 3:06:54 PM - using account id '############'...
DEBUG: [Common.Authentication]: Authenticating using Account: '############', environment: 'AzureCloud', tenant: '########-####-####-############ '
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/07/2017 19:06:54: ########-####-####-############ - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/########-####-####-############/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (1 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 06/07/2017 19:06:54: ########-####-####-############ - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/07/2017 19:06:54: ########-####-####-############ - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 06/07/2017 19:06:54: ########-####-####-############ - TokenCache: 14.3498483183333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/07/2017 19:06:54: ########-####-####-############ - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/07/2017 19:06:54: ########-####-####-############ - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: ############################################
	Refresh Token Hash: ############################################
	Expiration Time: 06/07/2017 19:21:15 +00:00
	User Hash: ############################################
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/07/2017 19:06:54:  - TokenCache: Serializing token cache with 1 items.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/07/2017 19:06:54: 5cdd2fd0-a3f8-40ac-837a-947fd5773ff9 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/########-####-####-############/
	Resource: https://management.core.windows.net/
	ClientId: ########-####-####-############
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (1 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 06/07/2017 19:06:54: 5cdd2fd0-a3f8-40ac-837a-947fd5773ff9 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/07/2017 19:06:54: 5cdd2fd0-a3f8-40ac-837a-947fd5773ff9 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 06/07/2017 19:06:54: 5cdd2fd0-a3f8-40ac-837a-947fd5773ff9 - TokenCache: 14.349831715 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/07/2017 19:06:54: 5cdd2fd0-a3f8-40ac-837a-947fd5773ff9 - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/07/2017 19:06:54: 5cdd2fd0-a3f8-40ac-837a-947fd5773ff9 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: ############################################
	Refresh Token Hash: ############################################
	Expiration Time: 06/07/2017 19:21:15 +00:00
	User Hash: ############################################
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/07/2017 19:06:54:  - TokenCache: Serializing token cache with 1 items.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/########-####-####-############/resourceGroups/rg-ASTest/providers/Microsoft.AnalysisServices/servers/azrastst01?api-version=2016-05-16

Headers:
x-ms-client-request-id        : dd3205f1-8d86-4860-a812-9a87454ff5f6
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 9fc4da57-7353-4b9a-bf52-1c8a97815180
x-ms-current-utc-date         : 6/7/2017 7:06:55 PM
x-ms-ratelimit-remaining-subscription-reads: 14989
x-ms-correlation-request-id   : db7d40cf-9afc-4b7c-a968-099c2fc83bd2
x-ms-routing-request-id       : EASTUS2:20170607T190655Z:db7d40cf-9afc-4b7c-a968-099c2fc83bd2
Cache-Control                 : no-cache
Date                          : Wed, 07 Jun 2017 19:06:55 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "properties": {
    "provisioningState": "Paused",
    "state": "Paused",
    "serverFullName": "asazure://aspaaseastus2.asazure.windows.net/azrastst01",
    "managedMode": 1,
    "backupBlobContainerUri": "https://saazrastst01.blob.core.windows.net/contazrastst01"
  },
  "id": "/subscriptions/########-####-####-############/resourceGroups/rg-ASTest/providers/Microsoft.AnalysisServices/servers/azrastst01",
  "name": "azrastst01",
  "type": "Microsoft.AnalysisServices/servers",
  "location": "East US 2",
  "sku": {
    "name": "D1",
    "tier": "Development"
  },
  "tags": {}
}

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmAnalysisServicesServer; IsSuccess - True; Duration - 00:00:00.3116956; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 3:06:55 PM - GetAzureAnalysisServicesServer end processing.
DEBUG: 3:06:55 PM - GetAzureAnalysisServicesServer end processing.

### Script/Steps for Reproduction
Get-AzureRmAnalysisServicesServer -ResourceGroupName rg-ASTest -Name azrastst01

**Comment by cormacpayne** [comment]
@athipp @igor-uzhviev Hey Arun and Igor, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
@taiwu would you mind taking a look at this issue? It looks like the resource group name is not being returned from the server, so we should be able to parse the resource id on the returned object to get the resource group name from it.

**Comment by cormacpayne** [comment]
This will be fixed in the upcoming release of `AzureRM`
