### ISSUE TITLE
Get-AzureRmVirtualNetwork doesn't capture logged-in state

### ISSUE THREAD

**Issue by jskii** [Azure/azure-powershell#4095]
**Cmdlet(s)**

Get-AzureRmWebApp

**PowerShell Version**

PSVersion 5.0.10586.672   

**Module Version**

Azure Powershell 4.0.1 release

**OS Version**

BuildVersion 10.0.10586.0    

**Description**

The Get-AzurermVirtualNetwork cmdlet always throws error "Run Login-AzureRmAccount to login.".  All other cmdlets tried (Get-AzureRmResourceGroup, Get-AzureRmStorageAccount, others) return logged in state and respond properly. I am owner on the Subscription, so should have access to all components.

**Debug Output**

PS C:\windows\system32> Login-AzureRmAccount

Environment           : AzureCloud
Account               : (removed)
TenantId              : (removed)
SubscriptionId        : (removed)
SubscriptionName      : (removed)
CurrentStorageAccount : 

PS C:\windows\system32> Get-AzureRmResourceGroup

(removed)

PS C:\windows\system32> Get-AzureRmStorageAccount

(removed)

PS C:\windows\system32> Get-AzureRmVirtualNetwork
Get-AzureRmVirtualNetwork : Run Login-AzureRmAccount to login.
At line:1 char:1
+ Get-AzureRmVirtualNetwork
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-AzureRmVirtualNetwork], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkCommand
 
PS C:\windows\system32> 

**Script/Steps for Reproduction**

Use Get-AzureRmVirtualNetwork.

**Comment by cormacpayne** [comment]
@jskii Hey Daniel, would you mind installing the latest modules (AzureRM 4.1.0) from the PowerShell Gallery and see if you are able to repro this issue?

**Comment by cormacpayne** [comment]
@jskii also, would you mind sending us the result of `Get-Module -ListAvailable` if the issues persists for you? It seems that this is being caused by a mismatch in the versions of modules being used (your `AzureRM.Profile` and `AzureRM.Storage` modules are from a different version of Azure PowerShell than the `AzureRM.Network` module)

**Comment by jskii** [comment]
Hey @cormacpayne, sorry I missed this. Thanks for the reply. I will get this info for you first thing tomorrow, and ping you again!

**Comment by jskii** [comment]
@cormacpayne: Uninstalling all Azure/AzureRm modules and reinstalling from the module gallery fixed this. Thanks for your help!
