### ISSUE TITLE
Get-AzureStorageTable 

### ISSUE THREAD

**Issue by dopic** [Azure/azure-powershell#4109]
### Cmdlet(s)
Get-AzureStorageTable

### PowerShell Version
PSVersion 5.1.14393.1066  

### Module Version
Azure.Storage 3.1.0

### OS Version
Windows 10 Pro: 10.0.14393.1066

### Description
I'm trying to get some tables from Azure Storage using the Cmdlet "Get-AzureStorageTable", but the result is always empty. The Cmdlets "Get-AzureStorageQueue" and "Get-AzureStorageContainer" are working correctly.

### Debug Output

[getazurestoragetable.txt](https://github.com/Azure/azure-powershell/files/1065101/getazurestoragetable.txt)

### Script/Steps for Reproduction

Add-AzureAccount

$storageAccountKey = Get-AzureStorageKey -StorageAccountName $storageAccount 
$storageContext = New-AzureStorageContext  -StorageAccountName $storageAccount -StorageAccountKey $storageAccountKey.Primary

Write-Host "Finding tables in $storageAccount"
Get-AzureStorageTable -Context $storageContext | Format-Table -Property Name

#Write-Host "Finding queues in $storageAccount"
#Get-AzureStorageQueue -Context $storageContext | Format-Table -Property Name

#Write-Host "Finding Containers in $storageAccount"
#Get-AzureStorageContainer -Context $storageContext | Format-Table -Property Name

**Comment by cormacpayne** [comment]
@dopic Hey Douglas, would you mind setting `$DebugPreference="Continue"` and running the cmdlet again so we can get the debug output?

@blueww Hey Wei, would you mind taking a look at this issue?

**Comment by blueww** [comment]
@dopic  

Do you have Storage Tables in your Storage Account? If not, you will get nothing with "Get-AzureStorageTable"

Do you mind try to create a table and then get it?
```
New-AzureStorageTable -Name testable -Context $storageContext
Get-AzureStorageTable -Context $storageContext | Format-Table -Property Name
Remove-AzureStorageTable -Name testable -Context $storageContext
```
If the testable which is just created can be show with "Get-AzureStorageTable",  there should be no tables originally in your Storage Account.

**Comment by dopic** [comment]
Hi @blueww! How are you?

Answering your questions:

1) Yes, I have a lot of tables in my Storage Account.
2) No, I'm not using SAS to create the $storageContext. I'm login in using the cmdlet **Add-AzureAccount** and use the cmdlet **Get-AzureStorageKey** to get the storagekey. After that I create the $storageContext.

The two images below will clarify my situation.

This is the storage account that I'm using. Note that there is a **manageroneprocessingqueue** in Queues.
![storage](https://user-images.githubusercontent.com/937765/27032675-6c5620d4-4f4c-11e7-8386-f650e3e048b8.png)


This is the test that I did, as suggested. The cmdlet **Get-AzureStorageQueue** lists the **manageroneprocessingqueue** queue, but the **Get-AzureStorageTable** doesn't list anything:
![test](https://user-images.githubusercontent.com/937765/27032798-fe902fb2-4f4c-11e7-9859-a22e6287f73a.png)

I think that this is not a permission problem, because the account that I'm using to run the powershell script is the same account that I use in Azure Storage Explorer (first image).

I hope that I have helped in some way.

Thanks!

**Comment by blueww** [comment]
@dopic 
Thanks for the reply!
But I can't repro the issue locally. So would you please help to check again if you use same account in PowerShell and the Storage Explorer.

If so, to make the issue simple, would you please run only following cmdlet and give the result and the time(UTC) to run it, I need the account name and request ID in it to query server log and get more clue for this issue:
`Get-AzureStorageTable -Context $storageContext -debug `
Please note, the $storageContext should already been created before run the cmdlets.

Besides that, please note that the analytics tables (name started with $) do not appear if you list all the tables in your storage account. You can either access them directly by name, or use the CloudAnalyticsClient API in the .NET client library to query the table names.

**Comment by dopic** [comment]
Hi @blueww!

I don't know what happened, but I had to format my pc because of a problem in my HD. 
After installing everything again, the cmdlet Get-AzureStorageTable worked correctly.

Thanks for yout time!
