### ISSUE TITLE
Move-AzureResource does not move classic virtual network and does not show errors

### ISSUE THREAD

**Issue by rajinders** [Azure/azure-powershell#411]
I tried moving a virtual network defined in the old portal into a new resource group.
The command finished successfully. ARM Explorer showed moving/provisioning status in both the Default-Networking an the new resource group. After 10-15 minutes I noticed that virtual network did not move.

A similar issue was reported while moving SQL DB from old portal/default resource group to new resource group in this blog post.

http://blog.kloud.com.au/2015/03/24/moving-resources-between-azure-resource-groups/

**Comment by ravbhatnagar** [comment]
The VM team would be enabling moving ARM VMs in prod soon, if not already. Please re-open if it still doesn't work in some time.
