### ISSUE TITLE
Wrong text in help of Import-AzureRMContext

### ISSUE THREAD

**Issue by pixelicous** [Azure/azure-powershell#4112]
### Cmdlet(s)
Import-AzureRmContext
### PowerShell Version
5.1.14393.1198

### Module Version
3.0.1

### OS Version
10.0.14393.1198

### Description
Wasn't sure how to open this if not as an issue.. when running get-help with the full parameter, you get the below text, it should be noted that this file can be created with Save-AzureRmContext..

Example 2: Importing a context from a JSON file
PS C:\> Import-AzureRmContext -Path C:\test.json

Environment           : AzureCloud
Account               : test@outlook.com
TenantId              : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
SubscriptionId        : yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
SubscriptionName      : Test Subscription
CurrentStorageAccount :

This example selects a context from a JSON file that is passed through to the cmdlet. This JSON file can be created from Import-AzureRmContext

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
get-help Import-AzureRmContext -full

**Comment by cormacpayne** [comment]
@pixelicous Good catch! Thanks for pointing this out. We will update the documentation for this cmdlet and have the fix out next release.

**Comment by cormacpayne** [comment]
Fix is in PR https://github.com/Azure/azure-powershell/pull/4114

**Comment by markcowl** [comment]
Fixed
