### ISSUE TITLE
Get-AzureRMServiceBusNameSpace doesn't return a value for resourcegroupname

### ISSUE THREAD

**Issue by dnewsholme** [Azure/azure-powershell#4122]
### Cmdlet(s)

Get-AzureRMServiceBusNameSpace 

### PowerShell Version
 5.1.14393.1198

### Module Version
Manifest   0.0        AzureRM.ServiceBus
### OS Version
10.0.14393.1198
### Description
When running 
     (Get-AzureRMServiceBusNameSpace)[0] | select * 
The resource is returned with a null value for resourcegroup name.

**Comment by cormacpayne** [comment]
@v-Ajnava Hey Ajit, would you mind taking a look at this issue?

**Comment by v-Ajnava** [comment]
We have deprecated the resource group property for Service bus. please use the 0.3.0 and above. Link: https://www.powershellgallery.com/packages/AzureRM.ServiceBus/0.4.0

**Comment by cormacpayne** [comment]
Closing.
