### ISSUE TITLE
SQL documentation improvements reverted by platyPS

### ISSUE THREAD

**Issue by akromm** [Azure/azure-powershell#4124]
Some documentation improvements were reverted by platyPS in PR: https://github.com/Azure/azure-powershell/pull/4110 

Need to follow up with platyPS to see if it is possible to improve/modify the output of platyPS to incorporate the improvements that were reverted.

**Comment by markcowl** [comment]
@akromm Please file this issue in the PlatyPS repo https://github.com/PowerSHell/platyPS
