### ISSUE TITLE
Acquiring Azure PS modules using Install-Module Troubleshooting guide

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-powershell#4129]
Lately there have been numerous reports of users getting into a state where they are not able to execute certain cmdlets.
Most of the time, this is a result of users not sure what version they installed and how they acquired them.

Currently you can install Azure PowerShell modules using:
1. MSI
2. PowerShell Gallery.

Have a troubleshooting guide that will document:
1) Under what scenarios users can get into a state where they are unable to execute cmdlets
e.g. having multiple version of AzureRm.Profile but not have accompanying dependencies
2) If they are in a bad state, this guide should suggest ways to solve the issue
e.g. either uninstall certain version and install additional accompanying modules if required.

**Comment by cormacpayne** [comment]
This [document](https://github.com/Azure/azure-powershell/blob/preview/documentation/troubleshoot-module-load.md) resolves this issue.
