### ISSUE TITLE
New-AzureWebsite with GitHub switches doesn't configure continuous deployment as expected

### ISSUE THREAD

**Issue by jonoward** [Azure/azure-powershell#413]
I'm trying to automate the creation of websites that are pre-configured with continuous deployment via a particular branch in a GitHub repo:

New-AzureWebsite -Name mysitename -GithubCredentials $cred -GitHub -GithubRepository "account/rep"

The site is created successfully, but continuous deployment is not configured - should it be? If this is what should happen, but isn't due to a bug, another useful feature would be for the desired branch name to be configurable.

Finally, the current folder in which this is executed appears to be git initialised (i.e. a /.git folder is created) - wouldn't this only be necessary if I used the "-Git" switch?

Thanks

**Comment by jonoward** [comment]
Should also add that after this script is run, the webhook is successully configured in GitHub, but in the Azure portal it looks like it's configured against a local git repo rather than GitHub

**Comment by nickmeldrum** [comment]
looks like this same behaviour occurs with the azure xpat cli when trying to set up github deployment. Would be great if we could have some way of automating the creation of an azure website with a github webhook and specific branch.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
