### ISSUE TITLE
Set-​Azure​Service​Antimalware​Extension overrides existing settings.

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-powershell#4137]
I have two roles in one cloud service, in azure portal I can set different anti-malware setting for each role.

If I enabled anti-malware for roleA first, then I enable anti-malware for roleB by Set-​Azure​Service​Antimalware​Extension, the anti-malware status of roleA will be disabed.

I want to use powershell to set different anti-malware setting for each role, but failed now, is this a bug?

Thanks

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
