### ISSUE TITLE
Login-AzureRMAccount pop-up window appears at the background

### ISSUE THREAD

**Issue by msevastian** [Azure/azure-powershell#4142]
### Cmdlet(s)
Login-AzureRMAccount

### PowerShell Version
PSVersion 5.1.14393.1358

### Module Version
Azure Powershell - December 2016

### OS Version
BuildVersion  10.0.14393.1358

### Description
While running at Login-AzureRMAccount cmdlet it is launching pop-up login window at the very background, so all windows should be minimized in order to get access to it. Sometimes when you require to do that frequently, that could be painful.
I have posted original issue in VS code repo, but was pointed to raise issue here
https://github.com/Microsoft/vscode/issues/28470

### Script/Steps for Reproduction
Run command Login-AzureRMAccount from VS Code

**Comment by cormacpayne** [comment]
@msevastian this seems to be an issue with the PowerShell extension in VS Code. Would you mind opening an issue in the PowerShell extension repository? 

https://github.com/PowerShell/vscode-powershell
