### ISSUE TITLE
Rewrite SQL backup tests to be recordable

### ISSUE THREAD

**Issue by jaredmoo** [Azure/azure-powershell#4155]
The following tests in Commands.Sql.Tests have hardcoded configuration and cannot be easily re-recorded:

- TestListDatabaseRestorePoints
- TestRestoreGeoBackup
- TestRestoreDeletedDatabaseBackup
- TestRestorePointInTimeBackup
- TestServerBackupLongTermRetentionVault
- TestDatabaseBackupLongTermRetentionPolicy
- TestRestoreLongTermRetentionBackup
- TestDatabaseGeoBackupPolicy

When tests cannot be run live, it becomes substantially more difficult to maintain the product and large changes have an increased risk of regressions. These tests should be rewritten so that they can be re-recorded. 

TestRestoreGeoBackup and TestRestoreLongTermRetentionBackup have some difficulty due to the wait until the first backup is created, but the other tests already have analogues in azure-sdk-for-net and shouldn't be a problem.

**Comment by jaredmoo** [comment]
This issue came up because it contributed to the difficulty of making change #4132 .

**Comment by cormacpayne** [comment]
@jaredmoo Hey Jared, has this issue been resolved?

**Comment by cormacpayne** [comment]
@jaredmoo ping

**Comment by jaredmoo** [comment]
@dealaus
