### ISSUE TITLE
Rewrite SQL index recommendation tests to be recordable

### ISSUE THREAD

**Issue by jaredmoo** [Azure/azure-powershell#4156]
The following tests in Commands.Sql.Tests have hardcoded configuration and cannot be easily re-recorded:

- TestGetIndexRecommendation
- TestCreateIndex

When tests cannot be run live, it becomes substantially more difficult to maintain the product and large changes have an increased risk of regressions. These tests should be rewritten so that they can be re-recorded.

**Comment by jaredmoo** [comment]
This issue came up because it contributed to the difficulty of making change #4132 .

**Comment by cormacpayne** [comment]
@jaredmoo Hey Jared, has this issue been resolved?

**Comment by cormacpayne** [comment]
@jaredmoo ping

**Comment by jaredmoo** [comment]
@StefanLazic92
