### ISSUE TITLE
Get-azurekeyvaultcertificate -VaultName $VaultName -Name $CertName -IncludeVersions returns error instead of iterating through all the cert versions

### ISSUE THREAD

**Issue by rashmi-jha** [Azure/azure-powershell#4161]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by mkosieradzki** [comment]
Any news on this one?

I get a NullReferenceException with the following stacktrace
```
   at Microsoft.Azure.Commands.KeyVault.Models.TagsHelper.ConvertToHashtable(IDictionary`2 tags)
   at Microsoft.Azure.Commands.KeyVault.Models.CertificateIdentityItem..ctor(CertificateBundle certBundle)
   at Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultCertificate.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by cormacpayne** [comment]
@RandalliLama @dragav would you mind taking a look at this issue?

**Comment by maddieclayton** [comment]
@mkosieradzki I cannot repro this issue - if you are still having this issue, please reopen and provide the output of running Get-AzureKeyVaultCertficate with -Debug specified, as well as the output of Resolve-AzureRmError.
