### ISSUE TITLE
AzureRM.OperationalInsights Bug

### ISSUE THREAD

**Issue by rosshopkins7** [Azure/azure-powershell#4163]
### Cmdlet(s)
Get-AzureRmOperationalInsightsSearchResults

### PowerShell Version
5.1.15063.413

### Module Version
AzureRM.OperationalInsights - 3.1.0
### OS Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      15063  413

### Description
The Get-AzureRmOperationalInsightsSearchResults cmdlet is not returning JSON formatted data as it did in previous builds of the AzureRM.OperationalInsights module.  I currently have version 3.1.0 of the AzureRM.OperationalInsights module installed on my local machine, and version 2.8.0 installed on a VM.  Version 2.8.0 returns the search results in the expected JSON format and version 3.1.0 does not.

**Version 2.8.0 returns the expected JSON formatted data:**

{
  "MaliciousIP": "xx.xxx.xx.xx"
}
{
  "MaliciousIP": "xx.xxx.xx.xxx"
}

**Version 3.1.0 returns what appears to be properties of the JSON object, but doesn't contain any useful data:**

HasValues    : False
Type         : String
Parent       : {}
Root         : {MaliciousIP}
Next         :
Previous     :
Path         : MaliciousIP
First        :
Last         :
LineNumber   : 0
LinePosition : 0

### Debug Output
N/A - Get-AzureRmOperationalInsightsSearchResults does not return any errors.  It returns data in the wrong format.

### Script/Steps for Reproduction
**Note**
Any Log Search query can be used.  The returned search results will not be formatted properly regardless of the query.

# Define OMS Variables
$ResourceGroupName = '<Resource_Group_Name>'
$omsWorkspaceName = '<OMS_Workspace_Name>'

$LogSearchQuery = 'MaliciousIP=* AND (RemoteIPCountry=* OR MaliciousIPCountry=*) AND (((Type=WireData AND Direction=Outbound) OR (Type=WindowsFirewall AND CommunicationDirection=SEND) OR (Type=CommonSecurityLog AND CommunicationDirection=Outbound)) OR (Type=W3CIISLog OR Type=DnsEvents OR (Type = WireData AND Direction!= Outbound) OR (Type=WindowsFirewall AND CommunicationDirection!=SEND) OR (Type = CommonSecurityLog AND CommunicationDirection!= Outbound))) TimeGenerated > NOW-60MINUTES | Distinct MaliciousIP'

# Query OMS
$Results = Get-AzureRmOperationalInsightsSearchResults -ResourceGroupName $ResourceGroupName -WorkspaceName $omsWorkspaceName -Top 1000000 -Query $LogSearchQuery
$Results.Value

**Comment by cormacpayne** [comment]
@xizhamsft Hey Xiaofang, would you mind taking a look at this issue?

**Comment by alexverboon** [comment]
I can confirm this being an  issue, just been baning my head , until i found this bug report. Works nicely with 3.0.1

**Comment by ColdHarbour** [comment]
I didn't see this bug report, raised my own a few days ago: https://github.com/Azure/azure-powershell/issues/4256

Thanks for confirming versions

**Comment by haitch** [comment]
fixed and wait for next release.
