### ISSUE TITLE
Remove-AzureVMExtension Not working to remove all extensions from a specific vm

### ISSUE THREAD

**Issue by theman8860** [Azure/azure-powershell#4174]
I was trying to remove all the extensions from a vm I used this syntax
$service = "testrunning"

$vmname = "testrunning"

$VM1 = Get-AzureVM -ServiceName $service -Name $vmname 

Get-AzureVM -ServiceName $service -name $vmname

Remove-AzureVMExtension -VM $VM1 -RemoveAll | Update-AzureVM

It gives mE this output

DeploymentName                    : testrunning
Name                              : testrunning
Label                             : 
VM                                : Microsoft.WindowsAzure.Commands.ServiceManagement.Model.PersistentVM
InstanceStatus                    : ReadyRole
IpAddress                         : 100.76.148.75
InstanceStateDetails              : 
PowerState                        : Started
InstanceErrorCode                 : 
InstanceFaultDomain               : 0
InstanceName                      : testrunning
InstanceUpgradeDomain             : 0
InstanceSize                      : Standard_D1
HostName                          : testrunning
AvailabilitySetName               : 
DNSName                           : http://testrunning.cloudapp.net/
Status                            : ReadyRole
GuestAgentStatus                  : Microsoft.WindowsAzure.Commands.ServiceManagement.Model.GuestAgentStatus
MaintenanceStatus                 : 
ResourceExtensionStatusList       : {Microsoft.Compute.BGInfo}
PublicIPAddress                   : 
PublicIPName                      : 
PublicIPDomainNameLabel           : 
PublicIPFqdns                     : {}
NetworkInterfaces                 : {}
VirtualNetworkName                : 
RemoteAccessCertificateThumbprint : 24EF42A72C646DA15A4D97FF756AD650CE562A0D
ServiceName                       : testrunning
OperationDescription              : Get-AzureVM
OperationId                       : a4ffcace459eaa0cba06e331f24f138c
OperationStatus                   : OK

OperationDescription : Update-AzureVM
OperationId          : e69650ef-f6f7-a7cf-be8f-dbb461427682
OperationStatus      : Succeeded

And it doesnt remove the extension in the vm

Whats the issue here am I doing something wrong or the Command is faulty, Or should I use separate commands to remove the specific extensions.

**Comment by cormacpayne** [comment]
@huangpf Hey Pengfei, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."

**Comment by pzerger** [comment]
Given this plays a role in ASM to ARM migration projects (VM extensions on ASM VMs a common challenge), you should consider reprioritizing or posting a workaround for existing customers.
