### ISSUE TITLE
Client-side telemetry should be opt-in by default.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#4179]
### Description
What the title says. :)

**Comment by markcowl** [comment]
### Description

Need additional details on
 - [ ] Algorithm to use for determining MAC address to hash
 - [ ] Hash function to use for hashing this value
 - [ ] Whether we should opt in users on upgrade, and what explanatory text we need to present when

**Comment by twitchax** [comment]
There is no prescriptive way to "choose" the proper MAC address, but the data team defines the hash algorithm as follows (source: https://wiki.vsdata.io/sendmacaddress).

```csharp
private string HashMACAddress(string macAddress)
{
    var hashInput = Encoding.UTF8.GetBytes(macAddress);
    return BitConverter.ToString(FipsCompliantSha.Sha256.ComputeHash(hashInput)).Replace("-", string.Empty).ToLowerInvariant();
}
```

We should also opt-in users on a one-time basis when upgrading (user setting preserved in future upgrades).  The text should be as follows.

```
Azure PowerShell collects usage data in order to improve your experience.
The data is anonymous and does not include commandline argument values.
The data is collected by Microsoft.

Use the Disable-AzureDataCollection cmdlet to turn the feature Off. The cmdlet can be found in the AzureRM.Profile module.  To disable data collection: PS &gt; Disable-AzureDataCollection.
Use the Enable-AzureDataCollection cmdlet to turn the feature On. The cmdlet can be found in the AzureRM.Profile module.  To enable data collection: PS &gt; Enable-AzureDataCollection.
```

**Comment by markcowl** [comment]
Opting in means the following:
- Check for the presence of the environment variable, and if it exists, opt out of data collection
- Create a new data profile file that serializes the option, with default set to true (opt in)
- Remove the old file
- If we did not find the data profile file or the environment variable print the message above

**Comment by markcowl** [comment]
Fixed.
