### ISSUE TITLE
Get-AzureRmNetworkSecurityGroup does not return the complete list of NSGs when NEXTLINK argument is returned in the body of the REST API call

### ISSUE THREAD

**Issue by jocorte** [Azure/azure-powershell#4187]
### Cmdlet(s)
Get-AzureRmNetworkSecurityGroup
### PowerShell Version
Name                           Value
----                           -----
PSVersion                      5.1.15063.413
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.413
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Module Version

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   4.1.0      Azure                               {Get-AzureAutomationCertificate, Get-AzureAutomationConnec
### OS Version

BuildVersion                   10.0.15063.413
### Description
When running CMDLET Get-AzureRmNetworkSecurityGroup if there are many NSGs within the subscription the output will be truncated and not all NSGs are displayed. Upon analyzing the debug output what we noticed is that when the NSG list is large an argument named NEXTLINK will be returned in the body of the response, what should happen next is that the CMDLET invokes another REST API call using NEXTLINK parameter value as the URI in order to retrieve the additional NSGs, and keep doing this until NEXTLINK is not returned; however the CMDLET only invokes a single REST API call and doesn't recurse on NEXTLINK, thus the full NSG list is not returned

### Debug Output
PS C:\Users\tiagob> Get-AzureRmNetworkSecurityGroup -Verbose -Debug
DEBUG: 15:32:09 - GetAzureNetworkSecurityGroupCommand begin processing with ParameterSet 'NoExpand'.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/6cb52f26-4370-4d50-afa5-b47282f84704/providers/Microsoft.Network/networkSecurityGroups?api-version=2017-03-01

Headers:
x-ms-client-request-id        : e4560e91-167b-4468-9d31-7867c4dc65f1
accept-language               : en-US

Body:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-original-request-ids     : 331b7b99-78bf-4b3b-ae99-8f843b0231b9,c148b421-5cdd-46ab-8071-9cd89c6f8229
x-ms-ratelimit-remaining-subscription-reads: 14843
x-ms-request-id               : 956a2eac-6d1d-48bb-b44e-80cb119dc3fb
x-ms-correlation-request-id   : 956a2eac-6d1d-48bb-b44e-80cb119dc3fb
x-ms-routing-request-id       : WESTEUROPE:20170623T143206Z:956a2eac-6d1d-48bb-b44e-80cb119dc3fb
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Fri, 23 Jun 2017 14:32:06 GMT

Body:

  ],
  "nextLink": "https://management.azure.com/subscriptions/6cb52f26-4370-4d50-afa5-b47282f84704/providers/Microsoft.Network/networkSecurityGroups?api-version=2017-03-01&%24skiptoken=nY7dbsIgGEDfhSy7%2bwpFak0Ts6hlerFuS%2b30miLdSFMgQN2P8d2n8Qm2q3N1cs4JGfUVn7TpAypOaM%2b3DX%2brX145KtBHjC4UGA%2fCiHc1KBMT8TN6lUg74DC2QXrtorYm4KlsM9rRKbBJToAdMgKiExm0LKcz2s1YThh23h71QfmAKy29DbaLybOKn9b32Ny4VXL0On6vvR1deBBOw%2fEiXBpzStIcyARIen8Xeu0a2ysz%2f8%2bHV8GOXqpbBD82fLWBku9gUVf1mqR%2fH8VXe89hV0FZLjcLdD7%2fAg%3d%3d"
}

### Script/Steps for Reproduction
PS C:\Users\tiagob> Get-AzureRmNetworkSecurityGroup -Verbose -Debug

**Comment by cormacpayne** [comment]
@jocorte thanks for the issue. It looks like the Network team currently has a pull request open to resolve this issue: https://github.com/Azure/azure-powershell/pull/4111/files#diff-fb31200e43f2ce431d741028e62fe481L20

@DeepakRajendranMsft Hey Deepak, let me know if I misspoke above.

**Comment by cormacpayne** [comment]
@jocorte this issue should be fixed in [Azure PowerShell 4.2.0](https://github.com/Azure/azure-powershell/releases/tag/v4.2.0-July2017).
