### ISSUE TITLE
No Save-AzureRMProfile cmdlet available - How to persist sessions for workflows

### ISSUE THREAD

**Issue by javiermarasco** [Azure/azure-powershell#4189]
### Cmdlet(s)
No Save-AzureRMProfile in this release

### PowerShell Version
PS 4.1.0

### OS Version
Windows 10
### Description

Normally in workflows I used Save-AzureRMProfile to a file in the disk and then each thread in the workflow used that file to run commands to Azure. Now that cmdlet is not present anymore and I can't find a way to run a workflow because I can't share my session with all the threads that are fired up by the workflow.

Is this something done in purpose because there is a new way to share the session with other threads? or something gone wrong with the packaging of the release?.

Thanks for any help!

**Comment by cormacpayne** [comment]
@javiermarasco in the 4.0.0 (May) release of Azure PowerShell, the name of the `Save-AzureRmProfile` cmdlet was changed `Save-AzureRmContext`. You can check out the migration guide we released with version 4.0.0 for more information: https://github.com/Azure/azure-powershell/blob/preview/documentation/release-notes/migration-guide.4.0.0.md#save-azurermprofile-was-renamed-to-save-azurermcontext

**Comment by javiermarasco** [comment]
@Cormacpayne Thanks for that information I checked the release of 4.1.0 and wasn't able to find it myself.
