### ISSUE TITLE
Get-AzureRmIoTHubConnectionString returns inaccurate Connection String syntax

### ISSUE THREAD

**Issue by starkfell** [Azure/azure-powershell#4190]
When running the Get-AzureRmIoTHubConnectionString using standard parameters, all Connection Strings that are returned are showing the key/value pair for the Shared Access Key Name are displaying it as ShareAccessKeyName instead of SharedAccessKeyName.

This behavior is occuring in the Modules for Azure 4.1.0 and AzureRm.IoTHub 2.1.0, but not in modules Azure 4.0.2 and AzureRm.IoTHub 2.0.1 as shown below:

![screenshot001](https://user-images.githubusercontent.com/2753909/27479245-70acb89e-5813-11e7-95b2-ba5ed6ade075.jpg)

![screenshot006](https://user-images.githubusercontent.com/2753909/27479243-6ec5692c-5813-11e7-8ff4-537587bc6a96.jpg)

**Comment by cormacpayne** [comment]
@starkfell Hey Ryan, it looks like this change was made in [this commit](https://github.com/Azure/azure-powershell/commit/04e47f8329ba9e64790c974f9666dbf41de7483f#diff-3d34c44c71a08327124d488f0e31217aR29) and was merged in time for the 4.1.0 release

@rkmanda Roopesh, was this change intentional?

**Comment by cormacpayne** [comment]
This issue should be fixed in the latest version of `AzureRM`. Closing as a result.
