### ISSUE TITLE
Azure Runbook - Asking showing "Run Login-AzureRmAccount to login", after I explicitly call it.

### ISSUE THREAD

**Issue by arlevitt** [Azure/azure-powershell#4191]
The following script produces the below error in Azure Runbook from the portal.  The script works *just fine from my local machine*, clearly calling the Login-AzureRmAccount command.

```
$Username = "myuser@domain.com
$SecurePassword =$(ConvertTo-SecureString -String "mypassword" -AsPlainText -Force)
$Credential = new-object System.Management.Automation.PSCredential($Username, $SecurePassword)
Login-AzureRmAccount -Credential $Credential
```
```
$StorageKey = (Get-AzureRmStorageAccountKey -AccountName "storageAcct" -ResourceGroupName "resourceGrp")

I'm getting the following error:
Get-AzureRmStorageAccountKey : Run Login-AzureRmAccount to login.
At line:27 char:16
+ ... orageKey = (Get-AzureRmStorageAccountKey -AccountName "storageAcct" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-AzureRmStorageAccountKey], PSInvalidOperationException
    + FullyQualifiedErrorId : 
InvalidOperation,Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountKeyCommand
```

This seems very strange. It was working previously.  I'm also attempting to run the Update-ModulesInAutomationToLatestVersion powershell script and getting the same error.  Please help! It was working previously!

**Comment by cormacpayne** [comment]
@arlevitt Hey Adam, I believe you are seeing this issue because you have multiple versions of Azure PowerShell installed on your machine. Would you mind running the command `Get-Module -ListAvailable` and providing us with the output?

My suggestion would be to remove all instances of Azure PowerShell from your machine (whether you installed via the PowerShell Gallery, Web Platform Installer, or directly from the .msi) and then install the latest version from the PowerShell Gallery using `Install-Module -Name AzureRM` and `Install-Module -Name Azure`. Please let me know if you have any questions!

**Comment by arlevitt** [comment]
Thanks for the reply.  I deleted the access account on azure and recreated it.  Then I was patient with the install of the latest updates.

**Comment by cormacpayne** [comment]
@arlevitt Hey Adam, was the above issue fixed?

**Comment by arlevitt** [comment]
Yes, through deleting the automation account and trying again... per my answer above.

**Comment by cormacpayne** [comment]
@arlevitt thanks Adam; just wanted to confirm. Closing this issue now.

**Comment by muntaserq** [comment]
I am seeing this error as well. I have tried deleting and redeploying the Automation account with no luck. I updated the modules, too. The error I am seeing:

`Your Azure credentials have not been set up or have expired, please run Login-AzureRMAccount to set up your Azure credentials. (Unable to retrieve service key for ServicePrincipal account b9fc7478-f864-4f2d-b2c3-e57c58e45077. Please log in again to supply the credentials for this service principal. In PowerShell, execute Login-AzureRMAccount for Azure Resource Manager cmdlets or Add-AzureAccount for service management cmdlets.)`

**Comment by muntaserq** [comment]
I am seeing this error as well. I have tried deleting and redeploying the Automation account with no luck. I updated the modules, too. The error I am seeing:

`Your Azure credentials have not been set up or have expired, please run Login-AzureRMAccount to set up your Azure credentials. (Unable to retrieve service key for ServicePrincipal account xxxxxxxxxxxxxxxxxxxxxxxxx. Please log in again to supply the credentials for this service principal. In PowerShell, execute Login-AzureRMAccount for Azure Resource Manager cmdlets or Add-AzureAccount for service management cmdlets.)`

Any ideas?

**Comment by cumtzhangqijie** [comment]
good
