### ISSUE TITLE
New-AzureRmRoleAssignment 

### ISSUE THREAD

**Issue by Mauzer93** [Azure/azure-powershell#4201]
I am not able to use this command in a VSTS task without seeing an exception.
If I run the script, and the role assignment does not exist yet, I get an CloudException from the ARM api (although the role assignment has been made).
If the role already exists, I got an error: The role is already assigned.

The VSTS task itself always succeeds, however, I prefer not to see those error messages... only when there is an actual error.

Is there is clean way, to check whether role exists or not, and add it if necessary?

`New-AzureRmRoleAssignment -ObjectId $id -RoleDefinitionName $role -ResourceGroupName $resourceGroup -ErrorAction Continue`

**Comment by shahabhijeet** [comment]
@Mauzer93 can you not use
[Get-AzureRmRoleAssignment](https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/get-azurermroleassignment?view=azurermps-4.1.0) and then use New-AzureRmRoleAssignment if the role was not assigned.

**Comment by Mauzer93** [comment]
Thanks for the suggestion. I have tried that before, but I am getting a cloud exception when trying to retrieve the role. (Powershell is executed in a VSTS task, using a Service principal) Any idea what is causing this?

**Comment by mqlkmd** [comment]
Hallo, 
Could this be reopened?
Im seeing the exact same issue when using these cmdlets through the VSTS service principal.
Get-AzureRmRoleAssignment throws a CloudException. New-AzureRmRoleAssignment throws a Hyak.Common.CloudException when the assignment already exists and a Microsoft.Rest.Azure.CloudException if it doesn't exists. However, the assignment operation actually succeeds.

**Comment by tinaisufi** [comment]
Hi All, 

I'm having exact the same issue with powershell and service principal? Is there any solution to solve it?

Thx

**Comment by maikvandergaag** [comment]
Hi All,

Could this issue be reopened? I still have this issue when using a Service Principal:

On the New-AzureRmRoleAssignment I receive a Microsoft.Rest.Azure.CloudException also on the Get method.
