### ISSUE TITLE
Problems with Import-AzureRmContext

### ISSUE THREAD

**Issue by Chiliyago** [Azure/azure-powershell#4209]
### Cmdlet(s)
Import-AzureRmContext

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1.14394.1000

### Module Version
4.1

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.14394.1000

### Description
Curious if Import-AzureRmContext does not work with Resource Group Owners or problematic in async scriptblocks.

We have a script that Uses Save-AzureRmContext  and Import-AzureRmContext.  This code was working when cmdlets used to be Save-AzureRmProfile and Import-AzureRmProfile. 

When I run it there is not a problem but I am the subscription admin for my tenant.  Members of my team are just Owners of their individual Resource Groups but they get the following error:  

> Your Azure credentials have not been set up or have expired, please run Login-AzureRMAccount 

So I am wondering if the security differences would be causing the problem.

The other theory I have is that I am running the Import-AzureRmContext in an async scriptblock so that may be causing the problem.

Thanks for any help you can provide
 

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

Your Azure credentials have not been set up or have expired, please run Login-AzureRMAccount 

### Script/Steps for Reproduction

Login-AzureRmAccount
$azureAcctPath = (Join-Path (Get-Item -Path ".\" -Verbose).FullName -ChildPath "AzureProfile.json")
Save-AzureRmContext -Path $azureAcctPath -Force

 $job = Start-Job -ScriptBlock{
     param($vmName, $rsName, $azureProfilePath)
          Import-AzureRmContext -Path $azureProfilePath

          Start-AzureRmVM -ResourceGroupName $rsName -Name $vmName -Verbose
} -ArgumentList $params

**Comment by Chiliyago** [comment]
After further testing I think it is safe to say that the Import-AzureRmContext cmdlet is not functioning properly within the ScriptBlock of the Start-Job cmdlet.

**Comment by cormacpayne** [comment]
Please check our documentation on context persistence: https://docs.microsoft.com/en-us/powershell/azure/context-persistence

This is the way we recommend you start jobs with AzureRM cmdlets.
