### ISSUE TITLE
Get-​Azure​Rm​Web​App​Publishing​Profile -OutputFile should not be mandatory.

### ISSUE THREAD

**Issue by takekazuomi** [Azure/azure-powershell#4212]
### PowerShell Version
5.1.16226.1000
```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16226.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16226.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module Version 
3.1.0
```
$ Get-Module | ? {$_.Name -like "Azure*"}

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.1.0      AzureRM.profile                     {Add-AzureRmAccount, Add-AzureRmEnvironment, Disable-AzureRmDataCollection, Enable-AzureRmDataCollection...}
Script     3.1.0      AzureRM.Websites                    {Edit-AzureRmWebAppBackupConfiguration, Get-AzureRmAppServicePlan, Get-AzureRmAppServicePlanMetrics, Get-AzureRmWebApp...}
```
### OS Version 
10.0.16226.1000

### Description
Get-​Azure​Rm​Web​App​Publishing​Profile cmdlet always requred -OutputFile option.
Without -OutputFile then I will got following error.

```
$ Get-AzureRmWebAppPublishingProfile -Name $Name -ResourceGroupName $Name

cmdlet Get-AzureRmWebAppPublishingProfile at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
OutputFile:
Get-AzureRmWebAppPublishingProfile : Cannot bind argument to parameter 'OutputFile' because it is an empty string.
At line:1 char:1
+ Get-AzureRmWebAppPublishingProfile -Name $Name -ResourceGroupName $Na ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-AzureRmWebAppPublishingProfile], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.GetAzureWebAppPublishingProfileCmdlet
```

### This is BAD design. 
I do not want to write it in a file, because OutputFile contains credentials.
The current cmdlet returns XML, so you do not need to write it in a file.
I think OutputFile should not be mandatory.

### note
Get-AzureRmWebAppSlotPublishingProfile has same issue.

https://github.com/Azure/azure-docs-powershell/blob/master/azureps-cmdlets-docs/ResourceManager/AzureRM.Websites/v3.1.0/Get-AzureRmWebAppSlotPublishingProfile.md

**Comment by shahabhijeet** [comment]
@takekazuomi thanks for your suggestion.
@ahmedelnably can you take a look at this and let the customer know if we can make the parameter non-mandatory.

**Comment by takekazuomi** [comment]
Add information.

The following document uses -OutputFile null.
Https://docs.microsoft.com/en-us/azure/app-service-web/scripts/app-service-powershell-deploy-local-git?toc=%2fpowershell%2fmodule%2ftoc.json

In this case, a file named "null" will be created. Specifying $ null results in an error.

**Comment by juliekoubova** [comment]
any updates on this?

**Comment by takekazuomi** [comment]
## Workaround

@juliekoubova You can use following workaround. This is not so cool but it works for me.  I hope this will help.

```
Invoke-AzureRmResourceAction -ResourceGroupName <resource group name> `
  -ResourceType Microsoft.Web/sites `
  -ResourceName <resource name> `
  -Action publishxml -ApiVersion 2015-08-01 `
  -Force
```

**Comment by takekazuomi** [comment]
@shahabhijeet @ahmedelnably This is braking change. Will you check this?

**Comment by sopelt** [comment]
I'm not sure what the usual policy is in azure-powershell github but could you update the issue as soon as this gets bundled in an actual release? @cormacpayne ?

Thank you.

**Comment by cormacpayne** [comment]
@sopelt Hey Simon, this fix will be available in the November release of Azure PowerShell (version 5.0.0) that goes out November 8th ☺️
