### ISSUE TITLE
Azure-GetRmLog - Remove 15 days maximum time window 

### ISSUE THREAD

**Issue by gucalder** [Azure/azure-powershell#4215]
### Cmdlet(s)
Azure-GetRmLog

### PowerShell Version
4.0

### OS Version
6.3.9600.17400

### Description
This is a change request, not an issue.
The Azure-GetRmLog cmdlet currently includes a maximum time window of 15 days. The request is to remove this limitation and let the backend validate the DateTime ranges provided.

**Comment by cormacpayne** [comment]
The fix for this issue has been merged in [version 4.2.0](https://github.com/Azure/azure-powershell/releases/tag/v4.2.0-July2017) of Azure PowerShell.
