### ISSUE TITLE
Remove ValueFromPipeline parameter from HDInsight cmdlets

### ISSUE THREAD

**Issue by shefaliv** [Azure/azure-powershell#4218]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@momusoru @z01c @wawon-msft would you mind taking a look at this issue?
