### ISSUE TITLE
Start-AzureBatchPoolResize doesnt support low-priority nodes

### ISSUE THREAD

**Issue by kim0** [Azure/azure-powershell#4230]
### Module Version
3.1.0

### OS Version
Azure Automation

### Description
Start-AzureBatchPoolResize doesn't seem to support low-priority nodes ? Any existing workaround ?

**Comment by cormacpayne** [comment]
@matthchr Hey Matt, would you mind taking a look at this issue?

**Comment by matthchr** [comment]
Hi @kim0 - The PSH cmdlets don't currently support LowPriorityNodes as there have been some breaking changes (both related to low priority as well as other unrelated things) and breaking change policy in PSH doesn't allow us to make the corresponding changes in our cmdlets until a major release, which is still a few months away I think

**Comment by matthchr** [comment]
This will be fixed in the upcoming powershell release at the end of November

**Comment by matthchr** [comment]
This is now supported in 5.0 of Azure Powershell.
