### ISSUE TITLE
Which REST API version is used for Azure Batch?

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-powershell#4233]
There are regular updates appearing on https://docs.microsoft.com/en-us/rest/api/batchservice/batch-service-rest-api-versioning and I was wondering at which version AzureRM is at. Is that information recorded somewhere?

**Comment by cormacpayne** [comment]
@matthchr Hey Matt, looks like this should be a quick question to answer.

**Comment by matthchr** [comment]
Right now AzureRM.Batch uses the C# SDK version `5.1.2`, which targets REST API version `2016-07-01.3.1`.

I don't think is currently documented anywhere obvious -- I'll make a note and add it to the file [here](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/AzureBatch/ChangeLog.md)

**Comment by matthchr** [comment]
Actually it's a bit more complicated than the above because the `AzureRM.Batch` module is both management and data plane operations. For the data plane, the above is accurate, for management plane we target `2015-12-01`.

**Comment by cormacpayne** [comment]
@letmaik I'm going to close this issue based on @matthchr's response. Please feel free to reopen this issue if you have any other questions!
