### ISSUE TITLE
New-AzureRMRoleAssignment - does not have scope to control AD Objects like Applications

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#4234]
### Cmdlet(s)
New-AzureRMRoleAssignment

### PowerShell Version
4.0

### OS Version
6.3.9600.17400

### Description

There should be a way to define Azure AD components in Scope for New-AzureRMRoleAssignment.
Please let me know if an alternative already exists for automated/unattended deployments of Azure AD components.

Am trying to use Service Principal for deployments. ( to come over issues with using organisational accounts like @microsoft.com)

1. I have created a service principal with password authentication.
2. Using New-AzureRMRoleAssignment am able to define scope at a subscription level and deploy components associated with the subscription.

But there is no way/documentations on how to control/deploy Azure AD Components like Applications.
For example when i issue Get-AzureRmADApplication, i get the below exception.

"odata.error": {
DEBUG:     "code": "Authorization_RequestDenied",
DEBUG:     "message": {
DEBUG:       "lang": "en",
DEBUG:       "value": "**Insufficient privileges to complete the operation**."
DEBUG:     }
DEBUG:   }

### Debug Output
Official Help documentation on New-AzureRMRoleAssignment with Scope limited to Subscription.

  The scope at which access is being granted may be specified. It defaults to the selected subscription.  The scope
  of the assignment can be specified using one of the following parameter combinations         a. Scope - This is
  the fully qualified scope starting with /subscriptions/<subscriptionId>         b. ResourceGroupName - to grant
  access to the specified resource group.         c. ResourceName, ResourceType, ResourceGroupName and (optionally)
  ParentResource - to specify a particular resource within a resource group to grant access to.

### Script/Steps for Reproduction

1. Create a Service Principal with associated password.
$ServicePrincipal = New-AzureRMADServicePrincipal -DisplayName $ApplicationDisplayName -Password $Password
2. Create a Role Assignement with scope for a subscription.
New-AzureRMRoleAssignment -RoleDefinitionName Contributor -ServicePrincipalName $ServicePrincipal.ApplicationId -Scope "\subscriptions\xxxxxx-6595c7ba"
3. This will enable to control resources in a subscription/resourcegroup with below command.
Login-AzureRmAccount -ServicePrincipal -Credential $SessionCred -TenantId "xxxxxxxxxxxx041c0"
4. Try Get-AzureRmADApplication - which will result in **Exception of type 'System.Exception' was thrown** with inner exception as below.

G:   "odata.error": {
DEBUG:     "code": "Authorization_RequestDenied",
DEBUG:     "message": {
DEBUG:       "lang": "en",
DEBUG:       "value": "Insufficient privileges to complete the operation."
DEBUG:     }
DEBUG:   }

**Comment by cormacpayne** [comment]
@rajaprad while this would be a nice feature to have, this is unfortunately by design. Role assignments are ARM objects and should not be treated as AD objects. This is a capability that we are looking at for the future, but it would not be available in this cmdlet.

**Comment by rajaprad** [comment]
@cormacpayne  - If this is something planned, could you please have this issue open so that we are informed on the timelines and the new cmdlet for the feature
