### ISSUE TITLE
Update CredScan tool and convert to local repo suppressions

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#4245]
Per the credscan site (http://aka.ms/credscan), local suppressions per repo can now be supported, which would allow simpler CredScan execution

- [x] Validate new usage scenarios and move current cml suppressions into local suppressions
- [x] Update build task to use new version and take advantage of local suppressions file

### Cost: 4

**Comment by vladimir-shcherbakov** [comment]
https://github.com/Azure/ci-signing/pull/112
https://github.com/Azure/azure-powershell/pull/5653 (suppression file)

**Comment by cormacpayne** [comment]
This has been fixed.
