### ISSUE TITLE
Set-AzureRmResource issues unnecessary GET request

### ISSUE THREAD

**Issue by makhdumi** [Azure/azure-powershell#4246]
### Cmdlet(s)
Set-AzureRmResource

### PowerShell Version
5.1.14393.1198 

### Module Version
4.1.0

### OS Version
10.0.14393.1198   

### Description
Set-AzureRmResource is broken for a lot of resources that do not support retrieving the resource via GET.

I am trying to run:
```

Set-AzureRmResource -ResourceId '/subscriptions/<my_subscr_id>/resourceGroups/<my_rg>/providers/Microsoft.Web/sites/<my_webapp_name>/config/appsettings' -Properties @{} -ApiVersion '2016-08-01' -Force

```

But get an error:
```
<Error>
  <Message>The requested resource does not support http method 'GET'.</Message>
</Error>
```

### Debug Output
```

DEBUG: [Common.Authentication]: Received token with LoginType 'LiveId', Tenant: '<redacted>', UserId: '<redacted>'
DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '07/05/2017 20:40:57 +00:00', MultipleResource? 'True', Tenant: '<redacted>', UserId: '<redacted>'
DEBUG: [Common.Authentication]: User info for token DisplayId: '<redacted>', Name: <redacted>, IdProvider: 'live.com', Uid: '<redacted>'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '07/05/2017 20:40:57 +00:00' Comparing to '07/05/2017 19:53:31 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:47:26.7515009'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<my_subscr_id>/resourceGroups/<my_rg>/providers/Microsoft.Web/sites/<my_webapp_name>/config/appsettings?api-version=2016-08-01

Headers:
User-Agent                    : AzurePowershell/v4.1.0,PSVersion/v5.1.14393.1198
ParameterSetName              : The resource Id.
CommandName                   : Set-AzureRmResource

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
MethodNotAllowed

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 14507
x-ms-request-id               : <redacted>
x-ms-correlation-request-id   : <redacted>
x-ms-routing-request-id       : <redacted>
Cache-Control                 : no-cache
Date                          : Wed, 05 Jul 2017 19:53:26 GMT
Server                        : Microsoft-IIS/8.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
<Error>
  <Message>The requested resource does not support http method 'GET'.</Message>
</Error>
```

### Script/Steps for Reproduction
Run this
```

Set-AzureRmResource -ResourceId '/subscriptions/<my_subscr_id>/resourceGroups/<my_rg>/providers/Microsoft.Web/sites/<my_webapp_name>/config/appsettings' -Properties @{} -ApiVersion '2016-08-01' -Force

````

**Comment by makhdumi** [comment]
This is *not* the same as https://github.com/Azure/azure-powershell/issues/1277

Some Azure resources do not support being Set by PATCH.

**Comment by cormacpayne** [comment]
@ravbhatnagar Hey Gaurav, would you mind taking a look at this issue?

**Comment by matendie** [comment]
Has there been any resolution to this issue? I getting same problem here. What would be work around if any?

**Comment by makhdumi** [comment]
@matendie as a workaround, I believe you can use `Invoke-AzureRmResourceAction` and submit the POST yourself.

**Comment by matendie** [comment]
Thanks for the response, I get an error while trying this work around... can yo see anything obvious I'm doing wrong?

Invoke-AzureRmResourceAction -Action "Post" -ResourceGroupName "ResourceGroupName" -ResourceName "test2/authsettings" -ResourceType "Microsoft.Web/sites/config" -ApiVersion '2015-06-01' -Parameters $PropertiesObject 

Invoke-AzureRmResourceAction : 
At line:1 char:1
Invoke-AzureRmResourceAction -Action "Post" -ResourceGroupName "Resour ...
  CategoryInfo          : CloseError: (:) [Invoke-AzureRmResourceAction], ErrorResponseMessageException
     FullyQualifiedErrorId : NotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.InvokAzureResourceActionCmdlet

**Comment by cormacpayne** [comment]
@ravbhatnagar ping

**Comment by luanshixia** [comment]
Reply from Azure PowerShell team:

> Azure Powershell doesn't "GET“ /subscriptions/<my_subscr_id>/resourceGroups/<my_rg>/providers/Microsoft.Web/sites/<my_webapp_name>/config/appsettings anymorein the latest `Set-AzResource`. It is recommended to use the latest version of Azure Powershell.
>
> Please refer to the link https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-3.6.1 to install the latest Azure Powershell.
