### ISSUE TITLE
Get-AzureRmRoleAssignment returns role assignments from other resource groups when called with Scope and ObjectId parameters

### ISSUE THREAD

**Issue by mgaufman** [Azure/azure-powershell#4248]
### Cmdlet(s)
Get-AzureRmRoleAssignment

### PowerShell Version
5.1.15063.413

### Module Version
AzureRM.Profile: 3.1.0
AzureRM.Resources: 4.1.0

### OS Version
10.0.15063.413
Azure Automation

### Description
Get-AzureRmRoleAssignment returns role assignments from other resource groups when called with Scope and ObjectId parameters.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
I've got 2 resource groups, "RG" and "RG01".
I assign say Reader role to a group with object id 98086144-9b37-4c9b-aa4f-52861a6f51d6 (it's a sample) for the resource group "RG". **Resource group "RG01" doesn't have Reader role assignments neither directly nor inherited from the subscription level.**
Now I execute _Get-AzureRmRoleAssignment -Scope /subscriptions/my-subscription-id/resourceGroups/**RG01** -ObjectId 98086144-9b37-4c9b-aa4f-52861a6f51d6 -RoleDefinitionName Reader_.
Output from this command should be empty but it returns:
_RoleAssignmentId: /subscription/..._
_Scope: /subscriptions/555bb974-38bf-45c0-9598-bcbcc59bdbe0/resourceGroups/**RG**_
_DisplayName: group-name_
_SignInName:_
_RoleDefinitionName: Reader_
_RoleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7_
_ObjectId: 98086144-9b37-4c9b-aa4f-52861a6f51d6_
_ObjectType: Group_

**Comment by cormacpayne** [comment]
@darshanhs90 would you mind taking a look at this issue?

**Comment by darshanhs90** [comment]
Could you try with the new powershell version and let us know if it still happens?

**Comment by mgaufman** [comment]
The problem still exists with the newest module version on my machine (AzureRM.Resources v5.0.0). Have it occurred in you testing with this module version?

**Comment by mgaufman** [comment]
P.S. I've noticed that the issue is closed - please reopen it as it's still there.

**Comment by darshanhs90** [comment]
thanks,have create a fix for this in the pr https://github.com/Azure/azure-powershell/pull/5094

**Comment by darshanhs90** [comment]
Closing this since The new update 5.1.0 will have a fix with this change.Re-open the same if the issue recurs

**Comment by mgaufman** [comment]
When is it going to be released?

**Comment by darshanhs90** [comment]
this friday

**Comment by mgaufman** [comment]
Thanks!

**Comment by darshanhs90** [comment]
@mgaufman Could you let me know if the issue that you were facing persists in the new powershell release

**Comment by mgaufman** [comment]
It's fixed. Thank you!

**Comment by uday31in** [comment]
Still having same issue

```
PS C:\Users\udpandya> Get-Module AzureRM.profile

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     4.5.0      AzureRM.profile                     {Add-AzureRmEnvironment, Clear-AzureRmContext, Clear-AzureRmDefault, Connect-AzureRmAccount...}
```

**Comment by darshanhs90** [comment]
@uday31in you need to update to the new azure powershell available from here https://github.com/Azure/azure-powershell/releases
