### ISSUE TITLE
Add-AzureRmEnvironment should set GraphAudience together if it set GraphEndpoint

### ISSUE THREAD

**Issue by wangshayu** [Azure/azure-powershell#4254]
### Cmdlet(s)
Add-AzureRmEnvironment

### PowerShell Version
5.0

### Module Version
AzureRm 1.2.10

### Description
When calling Add-AzureRmEnvironment with -ArmEndpoint 'xxx'. The graphendpoint is set but graphresourceId not. This will block the subsequence calling of RBAC roles/assignment requests.

### Script/Steps for Reproduction
Call Add-AzureRmEnvironment -Name "AzureStackAdmin" -ArmEndpoint "https://adminmanagement.local.azurestack.external"

The new environment added looks like this:
Name                                                                : AzureStackAdmin
EnableAdfsAuthentication                                : False
ActiveDirectoryServiceEndpointResourceId     :https://adminmanagement.msazurestack.onmicrosoft.com/30d66a27-6c22-4667-b0e6-e05aa716ef1f
AdTenant                                                          :
GalleryUrl                                                          : https://adminportal.local.azurestack.external:30015/
ManagementPortalUrl                                      :
ServiceManagementUrl                                    :
PublishSettingsFileUrl                                       :
ResourceManagerUrl                                        : https://adminmanagement.local.azurestack.external
SqlDatabaseDnsSuffix                                       :
StorageEndpointSuffix                                      : local.azurestack.external
ActiveDirectoryAuthority                                  : https://login.windows.net/
GraphUrl                                                           : https://graph.windows.net/
GraphEndpointResourceId                               :
TrafficManagerDnsSuffix                                  :
AzureKeyVaultDnsSuffix                                   : vault.local.azurestack.external
AzureDataLakeStoreFileSystemEndpointSuffix        :
AzureDataLakeAnalyticsCatalogAndJobEndpointSuffix :
AzureKeyVaultServiceEndpointResourceId            : https://vault.local.azurestack.external

Then Call Get-AzureRmRoleAssignment fails

**Comment by cormacpayne** [comment]
@viananth Hey Vishnu, would you mind taking a look at this issue?
