### ISSUE TITLE
Can't delete Recovery Service Vault 

### ISSUE THREAD

**Issue by jahongirman** [Azure/azure-powershell#4255]
### Cmdlet(s)

Remove-AzureRmRecoveryServicesVault

### PowerShell Version                                                                                                                
PSVersion                      5.1.14409.1005                                                                                                                                                 

### OS Version                                                                             
BuildVersion                   10.0.14409.1005                                                                                                                                                

### Description
Can't delete RSVault01 using Remove-AzureRmRecoveryServicesVault -Vault 'RSVault01'
### Debug Output

Remove-AzureRmRecoveryServicesVault : Cannot bind parameter 'Vault'. Cannot convert the "RSVault01" value of type "System.String" to type 
"Microsoft.Azure.Commands.RecoveryServices.ARSVault".
At line:1 char:44
+ Remove-AzureRmRecoveryServicesVault -Vault 'RSVault01'
+                                            ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-AzureRmRecoveryServicesVault], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Azure.Commands.RecoveryServices.RemoveAzureRmRecoveryServicesVault

**Comment by cormacpayne** [comment]
@dragonfly91 would you mind taking a look at this issue? This seems like an important scenario we should be enabling

**Comment by vipshnu** [comment]
PS C:\windows\system32> Remove-AzureRmRecoveryServicesVault

cmdlet Remove-AzureRmRecoveryServicesVault at command pipeline position 1
Supply values for the following parameters:
Vault: RecoveryServicesVault
Remove-AzureRmRecoveryServicesVault : Cannot bind parameter 'Vault'. Cannot convert the "RecoveryServicesVault" value of type "System.String" to type "Microsoft.Azure.Commands.RecoveryServices.ARSVault".
At line:1 char:1
+ Remove-AzureRmRecoveryServicesVault
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-AzureRmRecoveryServicesVault], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Azure.Commands.RecoveryServices.RemoveAzureRmRe
   coveryServicesVault

**Comment by pragrawa** [comment]
@jahongirman , you need to pass Vault object to cmdlet Remove-AzureRmRecoveryServicesVault. 
You can use below cmdlet to get required vault object
Get-Get-AzureRmRecoveryServicesVault -ResourceGroupName <ResourceGroupName> -Name <VaultName>
E.g.:
    $vault = Get-Get-AzureRmRecoveryServicesVault -ResourceGroupName rg01 -Name RSVault01
    Remove-AzureRmRecoveryServicesVault -Vault $vault

**Comment by johannfoot** [comment]
How can you close this thread? You didn't give a proper solution as well as have a terrible typo in your "solution" -->$vault = Get-**Get-**AzureRmRecoveryServicesVault

This still does not work:

Add-AzureRmAccount
Select-AzureRmSubscription -SubscriptionName "XXXXXX"
$vault = Get-AzureRmSiteRecoveryVault -ResourceGroupName XXXXXX -Name "XXXXXX"
Remove-AzureRmSiteRecoveryVault -Vault $vault

Error:
Remove-AzureRmSiteRecoveryVault : Cannot validate argument on parameter 'Vault'. The argument is null or empty. Provide an argument that is not null or empty, and then try the 
command again.
At line:1 char:40
+ Remove-AzureRmSiteRecoveryVault -Vault $vault
+                                        ~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-AzureRmSiteRecoveryVault], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.SiteRecovery.RemoveAzureSiteRecoveryVault

**Comment by pragrawa** [comment]
@johannfoot ,I have corrected the typo, thanks for reminding us.
Regarding the command, command is Get-AzureRm**RecoveryServices**Vault, not Get-AzureRmSiteRecoveryVault. Similarly  for Remove-AzureRmRecoveryServicesVault

For more information, please see documentation @ https://docs.microsoft.com/en-us/powershell/module/azurerm.recoveryservices/remove-azurermrecoveryservicesvault?view=azurermps-5.4.0

**Comment by johannfoot** [comment]
@pragrawa Ah yes, that will work better, much appreciated. I do however still get failure which prompts me to ask if this will remove the vault even if there's still resources in it?
