### ISSUE TITLE
New-AzureLoadBalancerProbeConfig issue with TCP

### ISSUE THREAD

**Issue by toutougabi** [Azure/azure-powershell#426]
The load balancer probe cmdlet, when set to tcp needs to have the request path empty but the command currently does not allow this. 

When setting the loadbalancer, if you put a path it tells that the tcp protocol is not supposed to have a path but then you cannot create a probe without a requestpath

**Comment by DeepakRajendranMsft** [comment]
Thanks for pointing out. this is being fixed in the next release.

**Comment by DeepakRajendranMsft** [comment]
closing since resolved
