### ISSUE TITLE
New-AzureRmAvailabilitySet cmdlet

### ISSUE THREAD

**Issue by Lanwin2010** [Azure/azure-powershell#4273]
### PowerShell Version
5.1.15063.413

### OS Version
10.0.15063.413
### Description
Hi, I was using New-AzureRmAvailabilitySet cmdlets to create a new Availability Set. The Sku default value appears to be set to "Managed" which translates to "Aligned" upon execution. However, I am aware that there is  a Classic "Sku" as well which is unmanaged. There isn't a lot of information available in MS documentations to specify what the exact difference between managed and unmanaged is. I am assuming this has something to do with managed disks and unmanaged disks. Which value should I use if I need to use "unmanaged" disks. "unmanaged" parameter does not get accepted and neither does "Classic". I checked CLI to create a new availability set and there seems to be a parameter "unmanaged". Also the same can be done via the portal. Could you let me know if "Aligned" is the default for the "Sku" parameter using PowerShell or is it possible to replace "managed" with say "unmanaged" or "Classic" during the execution?

### Script/Steps for Reproduction

Run the New-AzureRmAvailabilitySet command as described in https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/new-azurermavailabilityset?view=azurermps-4.1.0. It does not take any value apart from "Managed" for sku.
 
![capture](https://user-images.githubusercontent.com/29958781/27973287-1e6f33d0-6377-11e7-9c30-b84d8f62dcb1.PNG)

**Comment by markcowl** [comment]
@singhkays Can you take a look?

**Comment by singhkays** [comment]
@Lanwin2010 You are correct, classic is for unmanaged disks.

@hyonholee Can you take a look why Classic doesn't get accepted?

**Comment by Lanwin2010** [comment]
@hyonholee Any updates on this?

**Comment by hyonholee** [comment]
It should be New-AzureRmAvailabilitySet -Sku 'Classic'
