### ISSUE TITLE
Get-AzureRmModule returns a version string instead of a true module object

### ISSUE THREAD

**Issue by ghost** [Azure/azure-powershell#4274]
### Cmdlet(s)
Get-AzureRmModule

### PowerShell Version
5

### Module Version
0.1.0

### Description
Cmdlet should return a true module object. It's returning the version string.
Or it shouldn't be part of the public API.

### Script/Steps for Reproduction
PS C:\windows\system32> Get-AzureRmModule -Profile latest -Module AzureRM
3.7.0

**Comment by cormacpayne** [comment]
@viananth is this still an issue?

**Comment by viananth** [comment]
Yes. I will be fixing this as part of the next bootstrapper module release
