### ISSUE TITLE
Use-AzureRmProfile doesn't support scripts containing "#Requires AzureRM.*" headers

### ISSUE THREAD

**Issue by ramach-msft** [Azure/azure-powershell#4275]
### Cmdlet(s)
Use-AzureRmProfile

### PowerShell Version
5.1.14409.1005

### Module Version
0.1.0

### OS Version
10.0.14409.1005

### Description
Use-AzureRmProfile silently doesn't load the correct modules if executing a script containing "#Requires AzureRM.*" headers.

Please note that using "#Requires AzureRM" works fine.
The problem is when requiring AzureRM.* submodules in the header.

I'm going to use AzureRM.Resources as an example:
In my machine I have AzureRM.Resources 3.7.0 as the default azure module version for a new powershell process, i.e. if I start a new ps window and execute Azure cmdlets, eventually 3.7.0 will get lazy loaded.

If I want to use 'latest' profile, everything works well, because 'latest' happens to also point to AzureRM.Resources 3.7.0.
But if I want to use '2017-03-09-profile' profile, the 3.7.0 always win the loading.

Moreover, the error is silently discarded by Use-AzureRmProfile.
Only if you execute get-module *azure* after or inspect the $Error variable you can see that something went wrong.

### Script/Steps for Reproduction
1) Create a file with the following contents (let's say it's named requires_test.ps1):
```powershell
#Requires -Module AzureRM.Resources

Write-Host "`n>>>>>> Get-Module *azure*:"
Get-Module *azure*
Write-Host "<<<<<<"

Write-Host "`n>>>>>>Error var:"
$Error
Write-Host "<<<<<<"

```

2) Open cmd and execute:
```
powershell -Command "Use-AzureRmProfile '2017-03-09-profile' -Scope CurrentUser -Force; &'requires_test.ps1'"
```

- Actual behavior:
```powershell
>>>>>> Get-Module *azure*:

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.2.9      AzureRM                             {Add-AlertRule, Add-AutoscaleSetting, Add-AzureKeyVaultKey, Add-AzureRmAccount...}
Script     0.1.0      AzureRM.BootStrapper                {Get-AzureRmModule, Get-AzureRmProfile, Install-AzureRmProfile, Set-BootstrapRepo...}
Script     3.7.0      AzureRM.Resources                   {Find-AzureRmResource, Find-AzureRmResourceGroup, Get-AzureRmADApplication, Get-AzureRmADGroup...}
<<<<<<

>>>>>>Error var:
New-Alias : The alias is not allowed, because an alias with the name 'Login-AzureRmAccount' already exists.
At line:18 char:106
+ ... 'Value'; Expression={$_.Value}} | New-Alias -Description "AzureAlias"
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (Login-AzureRmAccount:String) [New-Alias], SessionStateException
    + FullyQualifiedErrorId : AliasAlreadyExists,Microsoft.PowerShell.Commands.NewAliasCommand

New-Alias : The alias is not allowed, because an alias with the name 'Select-AzureRmSubscription' already exists.
At line:18 char:106
+ ... 'Value'; Expression={$_.Value}} | New-Alias -Description "AzureAlias"
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (Select-AzureRmSubscription:String) [New-Alias], SessionStateException
    + FullyQualifiedErrorId : AliasAlreadyExists,Microsoft.PowerShell.Commands.NewAliasCommand

Unable to find type [Microsoft.PowerShell.Commands.PowerShellGet.Telemetry].
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.1.3.1\PSModule.psm1:717 char:26
+ ... yMethods = ([Microsoft.PowerShell.Commands.PowerShellGet.Telemetry] | ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...llGet.Telemetry:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

<<<<<<
```

- Expected:
I should see AzureRM.Resources 1.0.4.3 loaded, as described by Get-AzureRmProfile -ListAvailable.

**Comment by markcowl** [comment]
@ramach-msft This is by design.  Scripts should either use #Require AzureRM with a specific version, or use Use-AzureRmProfile.  These methods intentionally do not mix.  Clsoing as by design.
