### ISSUE TITLE
Get-AzureRmSubscription -All option fails. The example has to be updated to remove "-All"

### ISSUE THREAD

**Issue by krishnasun82** [Azure/azure-powershell#4286]
Get-AzureRmSubscription -All option fails. The example has to be updated to remove "-All". MSDN documents have to be updated as well.

Get-AzureRmSubscription

man Get-AzureRmSubscription

NAME
Get-AzureRmSubscription

SYNOPSIS
Get subscriptions that the current account can access.

SYNTAX
Get-AzureRmSubscription -All [<CommonParameters>]

Get-AzureRmSubscription [-SubscriptionId <String>] [-TenantId <String>] [<CommonParameters>]

Get-AzureRmSubscription [-SubscriptionName <String>] [-TenantId <String>] [<CommonParameters>]

DESCRIPTION
The Get-AzureRmSubscription cmdlet gets the subscription ID, subscription name, and home tenant for subscriptions
that the current account can access.

RELATED LINKS

REMARKS
To see the examples, type: "get-help Get-AzureRmSubscription -examples".
For more information, type: "get-help Get-AzureRmSubscription -detailed".
For technical information, type: "get-help Get-AzureRmSubscription -full".

PS C:\Users\ntlab> Get-AzureRmSubscription -All
Get-AzureRmSubscription : A parameter cannot be found that matches parameter name 'All'.
At line:1 char:25
+ Get-AzureRmSubscription -All
+ ~~~~
+ CategoryInfo : InvalidArgument: (:) [Get-AzureRmSubscription], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.Profile.GetAzureRMSubscriptionCommand

**Comment by markcowl** [comment]
## Description

Update Get-AzureRmSubscription examples to remove '-All' parameter

## Cost: 1

**Comment by sdwheeler** [comment]
Change merged in https://github.com/Azure/azure-powershell/pull/4394.
