### ISSUE TITLE
Azure PowerShell vs Azure CLI

### ISSUE THREAD

**Issue by magol** [Azure/azure-powershell#4290]
When searching online, many guides are written with Azure CLI. It is not always clear what the corresponding command are in Azure PowerShell.

Something that I think would have been good is if in the documentation for all Azure PowerShell commands is a link to the corresponding Azure CLI command, and the opposite in the documentation of Azure CLI. In case there is no direct counterpart, I still think there should be a comment about how a PowerShell command could be performed in Azure CLI.

An alternative is to have a page with cross references between the CLI and PowerShell (and maybe also the Azure Portal GUI)

**Comment by cormacpayne** [comment]
@magol Hey Magnus, thanks for the suggestion! Our docs team is currently working on something similar to this idea, starting with some of the more common services an Azure user might use.

For example, there are currently docs with _Getting Started_ guides in both Azure PowerShell and Azure CLI (and some in the Portal) for the following:
- [Windows Virtual Machines](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/)
- [Linux Virtual Machines](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/)
- [Azure SQL Database](https://docs.microsoft.com/en-us/azure/sql-database/)
- [Web Apps](https://docs.microsoft.com/en-us/azure/app-service-web/)
   - This one you'll have to look under the _Samples_ tab in the left-hand column

@sdwheeler Sean, please let me know if there's any other docs I can link to, or if there's any other pieces of information worth sharing in regards to "cross reference documentation"

**Comment by markcowl** [comment]
@twitchax Can you comment on documentation plans in this area?

**Comment by twitchax** [comment]
@cormacpayne mentioned some great documentation that we have today.  As he points out, many of our "getting started" scenarios are well documented in both Azure CLI and Azure PowerShell.  The largest gaps occur in documentation authored by specific service teams.

As of right now, most documentation from service teams prioritizes the CLI that makes the most sense for their users; however, we have a clear charter to _eventually_ have 1:1 documentation for all scenarios that we support.  I am not sure what the timeline is right now, but @sdwheeler may be able to comment.

@magol, if possible, a few examples from your perspective would help us make targeted improvements in popular areas.
