### ISSUE TITLE
New-AzureRmStreamAnalyticsJob cannot create Inputs that tie to Operations Monitoring IOT Endpoints

### ISSUE THREAD

**Issue by HowardHoffman** [Azure/azure-powershell#4291]
### Cmdlet(s)
`New-AzureRmStreamAnalyticsJob`

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
`5.1.15063.413`
### Module Version
`AzureRM 4.1.0   C:\Program Files\WindowsPowerShell\Modules\AzureRM\4.1.0\AzureRM.psd1`
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
`BuildVersion                   10.0.15063.413`
### Description
`New-AzureRmStreamAnalyticsJob` does not update IOT Hub Inputs where the Endpoint type is Operations Monitoring.  Only Messaging Endpoints can be created with this command.
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
Define a Stream Analytics Job JSON that has an Operations Monitoring Input Endpoint.   Run the cmdlet. 
An Input connected to the IOT Hub's Operations Monitoring Endpoint will not be created by the Powershell cmdlet. Instead the Input will be connected to the Messaging Endpoint.

**Comment by markcowl** [comment]
@atpham256 Can you take  a look?

**Comment by atpham256** [comment]
This should already be available in the latest Azure PowerShell that was released today (4.2.0).

@HowardHoffman Have you tried updating to the latest Azure PowerShell and trying?

**Comment by atpham256** [comment]
Customer updated to the latest PowerShell version and everything worked.
