### ISSUE TITLE
Diagnose and reduce runtime for Compute, Sql, Network Tests

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#4294]
### Description

Network, Compute, and Sql check-in tests have been taking a long time in the latest runs.  Determien the cause for the increase and reduce these tests to 15 minutes or less of runtime.

### Cost: 4

**Comment by cormacpayne** [comment]
Compute (and possibly Network) are affected by the changes made in [this commit](https://github.com/Azure/azure-powershell/commit/75b53e9029a3a5a4e393f7a8702bae853e353501#diff-79da8537af8937bd04e6b179f14c783fL50). The `ComputeAutoMapperProfile` is no longer using a singleton for the mapper, resulting in the mapper being initialized every time a cmdlet is executed. This has resulted in certain tests, specifically [`Test-VirtualMachinePlan2`](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineTests.ps1#L1543), having a much larger execution time during the regular PowerShell job. We should talk to the Compute team about how we want to resolve this issue moving forward.

**Comment by cormacpayne** [comment]
The fix for this has been merged.
