### ISSUE TITLE
Error When Enabling Disk Encryption on Azure VM [Exception: ProtectKeyWithExternalKey failed]

### ISSUE THREAD

**Issue by hsrasheed** [Azure/azure-powershell#4301]
### Cmdlet(s)
Set-AzureRmVMDiskEncryptionExtension

### PowerShell Version
5.1.14393.1480

### OS Version
10.0.14393.1480

### Description
I used the pre-requisites script to get all of the required parameters. I successfully ran the command and encrypted 3/4 VMs. But the fourth one threw the following error:

Set-AzureRmVMDiskEncryptionExtension : Long running operation failed with status 'Failed'.
ErrorCode: VMExtensionProvisioningError
ErrorMessage: VM has reported a failure when processing extension 'AzureDiskEncryption'. Error message: "Failed to configure bitlocker as expected. Exception: ProtectKeyWithExternalKey failed with 2150695006, InnerException: , stack 
trace:    at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerWmi.Win32EncryptableVolumeWrap.ProtectKeyWithExternalkey()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerOperations.GenerateKeyForVolume(EncryptableVolume vol)
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadProtectorForVolume(EncryptableVolume vol, Boolean saveKeyToBekVolume)
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadOsVolumeProtector()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.EnableEncryption()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.HandleEncryptionOperations()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.OnEnable()".

### Debug Output
DEBUG: AzureQoSEvent: CommandName - Set-AzureRmVMDiskEncryptionExtension; IsSuccess - False; Duration - 00:00:36.2656511; Exception - Microsoft.Azure.Commands.Compute.Common.ComputeCloudException: Long running operation failed with st
atus 'Failed'.
ErrorCode: VMExtensionProvisioningError
ErrorMessage: VM has reported a failure when processing extension 'AzureDiskEncryption'. Error message: "Failed to configure bitlocker as expected. Exception: ProtectKeyWithExternalKey failed with 2150695006, InnerException: , stack t
race:    at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerWmi.Win32EncryptableVolumeWrap.ProtectKeyWithExternalkey()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerOperations.GenerateKeyForVolume(EncryptableVolume vol)
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadProtectorForVolume(EncryptableVolume vol, Boolean saveKeyToBekVolume)
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadOsVolumeProtector()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.EnableEncryption()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.HandleEncryptionOperations()
   at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.OnEnable()".
StartTime: 7/12/2017 9:30:46 AM
EndTime: 7/12/2017 9:30:46 AM
OperationID: f48aa0df-68d2-436f-9239-dd4e35ac9170
Status: Failed ---> Microsoft.Rest.Azure.CloudException: Long running operation failed with status 'Failed'.
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.VirtualMachineExtensionsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Compute.Extension.AzureDiskEncryption.SetAzureDiskEncryptionExtensionCommand.<ExecuteCmdlet>b__80_0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 9:31:17 AM - SetAzureDiskEncryptionExtensionCommand end processing.
DEBUG: 9:31:17 AM - SetAzureDiskEncryptionExtensionCommand end processing.

**Comment by maddieclayton** [comment]
@danielsollondon Can you take a look at this issue?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.

**Comment by Kundansog** [comment]
Hi All,

I am facing eh same issue for my two server, botth are the file server in cluster, but bitlocker is getting failed, it is encrypting the os disk, i am able to see on portal and in VM as well the OS disk is encrypted but not encrypting the data disk and also the extension is getting failed with below Error.

Failed to configure bitlocker as expected. Exception: ProtectKeyWithExternalKey failed with 2150695086

and i am facing this bit locker failed issue with file servers only which are deployed in different subscription with different key vault.

Any idea.

**Comment by kundan579p** [comment]
Hi All,

I am facing eh same issue for my two server, botth are the file server in cluster, but bitlocker is getting failed, it is encrypting the os disk, i am able to see on portal and in VM as well the OS disk is encrypted but not encrypting the data disk and also the extension is getting failed with below Error.

Failed to configure bitlocker as expected. Exception: ProtectKeyWithExternalKey failed with 2150695086

and i am facing this bit locker failed issue with file servers only which are deployed in different subscription with different key vault.

Any idea.

**Comment by AndyX-Net** [comment]
> ### Cmdlet(s)
> Set-AzureRmVMDiskEncryptionExtension
> 
> ### PowerShell Version
> 5.1.14393.1480
> 
> ### Module Version
> ### OS Version
> 10.0.14393.1480
> 
> ### Description
> I used the pre-requisites script to get all of the required parameters. I successfully ran the command and encrypted 3/4 VMs. But the fourth one threw the following error:
> 
> Set-AzureRmVMDiskEncryptionExtension : Long running operation failed with status 'Failed'. ErrorCode: VMExtensionProvisioningError ErrorMessage: VM has reported a failure when processing extension 'AzureDiskEncryption'. Error message: "Failed to configure bitlocker as expected. Exception: ProtectKeyWithExternalKey failed with 2150695006, InnerException: , stack trace: at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerWmi.Win32EncryptableVolumeWrap.ProtectKeyWithExternalkey() at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerOperations.GenerateKeyForVolume(EncryptableVolume vol) at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadProtectorForVolume(EncryptableVolume vol, Boolean saveKeyToBekVolume) at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadOsVolumeProtector() at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.EnableEncryption() at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.HandleEncryptionOperations() at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.OnEnable()".
> 
> ### Debug Output
> DEBUG: AzureQoSEvent: CommandName - Set-AzureRmVMDiskEncryptionExtension; IsSuccess - False; Duration - 00:00:36.2656511; Exception - Microsoft.Azure.Commands.Compute.Common.ComputeCloudException: Long running operation failed with st atus 'Failed'. ErrorCode: VMExtensionProvisioningError ErrorMessage: VM has reported a failure when processing extension 'AzureDiskEncryption'. Error message: "Failed to configure bitlocker as expected. Exception: ProtectKeyWithExternalKey failed with 2150695006, InnerException: , stack t race: at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerWmi.Win32EncryptableVolumeWrap.ProtectKeyWithExternalkey() at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerOperations.GenerateKeyForVolume(EncryptableVolume vol) at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadProtectorForVolume(EncryptableVolume vol, Boolean saveKeyToBekVolume) at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.GenerateAndUploadOsVolumeProtector() at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.EnableEncryption() at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.HandleEncryptionOperations() at Microsoft.Cis.Security.BitLocker.BitlockerIaasVMExtension.BitlockerExtension.OnEnable()". StartTime: 7/12/2017 9:30:46 AM EndTime: 7/12/2017 9:30:46 AM OperationID: f48aa0df-68d2-436f-9239-dd4e35ac9170 Status: Failed ---> Microsoft.Rest.Azure.CloudException: Long running operation failed with status 'Failed'. at Microsoft.Rest.Azure.AzureClientExtensions.d__1`2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__0`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Rest.Azure.AzureClientExtensions.d__4`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.Management.Compute.VirtualMachineExtensionsOperations.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.Commands.Compute.Extension.AzureDiskEncryption.SetAzureDiskEncryptionExtensionCommand.b__80_0() at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action) --- End of inner exception stack trace --- at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action) at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord(); DEBUG: Finish sending metric. DEBUG: 9:31:17 AM - SetAzureDiskEncryptionExtensionCommand end processing. DEBUG: 9:31:17 AM - SetAzureDiskEncryptionExtensionCommand end processing.
> 
> ### Script/Steps for Reproduction

ProtectKeyWithExternalKey failed with **2150695006**

Error 2150695006:::

Symbolic Name | Error Description | Header
0x803100ae | -2144272210 | FVE_E_NOT_ALLOWED_ON_CLUSTER | This command cannot be performed on a volume when it is part of a cluster. | winerror.h

This VM should be Domain joined.
Please run command to check if any restriction with your Group Policy(GPO):
_gpresult /H c:\%computername%_GPO.html_

**Comment by AndyX-Net** [comment]
> Hi All,
> 
> I am facing the same issue for my two server, botth are the file server in cluster, but bitlocker is getting failed, it is encrypting the os disk, i am able to see on portal and in VM as well the OS disk is encrypted but not encrypting the data disk and also the extension is getting failed with below Error.
> 
> Failed to configure bitlocker as expected. Exception: ProtectKeyWithExternalKey failed with 2150695086
> 
> and i am facing this bit locker failed issue with file servers only which are deployed in different subscription with different key vault.
> 
> Any idea.

Hi kundan579p,

Error code 2150695086:

Symbolic Name | Error Description | Header
0x803100ae | -2144272210 | FVE_E_NOT_ALLOWED_ON_CLUSTER | This command cannot be performed on a volume when it is part of a cluster. | winerror.h

Result:
Possible you are using the clustered storage, but ADE doesn't support it.

Please refer this link:
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disk-encryption-windows#unsupported-scenarios

![image](https://user-images.githubusercontent.com/27819097/167351548-c4d87793-abda-4a2c-a4ca-3bb7e1497328.png)
