### ISSUE TITLE
Feature/Question: ForceRerun parameter on Set-AzureRmVmCustomScriptExtension

### ISSUE THREAD

**Issue by ChrisLGardner** [Azure/azure-powershell#4312]
When looking at the Set-AzureRmVmCustomScriptExtension parameter -ForceRerun I see it accepts a String but with no information of what the string should be other than different to what it was previously set to. Digging into the tests in this repo I see the string is set to "RerunExtension" which I'd guess is just a value set for testing purposes.

Is there a reason that it's a String type rather than a Switch as the name (and convention) would imply? Could it be made a switch type?

**Comment by cormacpayne** [comment]
@ChrisLGardner Hey Chris, so it looks like [this value is passed](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Compute/Commands.Compute/Extension/CustomScript/SetAzureVMCustomScriptExtensionCommand.cs#L180) to a [`VirtualMachineExtension`](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Management.Compute/Generated/Models/VirtualMachineExtension.cs#L78) object (which is found in the Compute .NET SDK). The value is also a string in this class, but I'm not sure if the values you can provide it are restricted to anything.

@hyonholee Hey Hyonho, would you be able to shed a little light on what values can be passed to this parameter/property? (if there are any restrictions)

**Comment by cormacpayne** [comment]
@hyonholee would you mind taking a look at this issue?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
