### ISSUE TITLE
Stopped pipeline not handled correctly by many cmdlets

### ISSUE THREAD

**Issue by TimCurwick** [Azure/azure-powershell#4319]
### Cmdlet(s)
Lots of them (19 of 21 tested) See below

### PowerShell Version
5.1.15063.0                                                          

### Module Version
AzureRM 4.1.0

### OS Version
15063.0

### Description
Stopping a pipeline, for example by using the -First parameter on Select-Object, results in unexpected behavior for almost all tested cmdlets.

The following each behave as expected, outputting a single result, with no error:
Get-AzureRmResource | Select-Object -First 1
Get-AzureRmDisk | Select-Object -First 1

The following each throw terminating errors:
Get-AzureRmAvailabilitySet -ResourceGroupName $RGName | Select-Object -First 1
Get-AzureRmEnvironment | Select-Object -First 1
Get-AzureRmPolicyDefinition | Select-Object -First 1
Get-AzureRmResourceGroup | Select-Object -First 1
Get-AzureRmResourceGroupDeployment -ResourceGroupName $RGName | Select-Object -First 1
Get-AzureRmResourceGroupDeploymentOperation -DeploymentName $DeplName -ResourceGroupName $RGName | Select-Object -First 1
Get-AzureRmResourceLock | Select-Object -First 1
Get-AzureRmResourceProvider | Select-Object -First 1
Get-AzureRmRoleAssignment | Select-Object -First 1
Get-AzureRmRoleDefinition | Select-Object -First 1
Get-AzureRmSubscription | Select-Object -First 1
Get-AzureRmTenant | Select-Object -First 1
Get-AzureRmVMDscExtension -ResourceGroupName $RGName -VMName $VMName | Select -first 1

The following throw a terminating error but somehow do so without the error message appearing in the console. The error does appear in $Error list.
Get-AzureRmVM | Select-Object -First 1
Get-AzureRmVMImageOffer -Location eastus -PublisherName MicrosoftWindowsServer | Select-Object -First 1
Get-AzureRmVMImagePublisher -Location eastus | Select-Object -First 1
Get-AzureRmVMImageSku -Location eastus -PublisherName MicrosoftWindowsServer -Offer WindowsServer | Select-Object -First 1
Get-AzureRmVMSize -Location eastus | Select-Object -First 1

**Comment by GamerLivingWill** [comment]
Verified.

**Comment by swngdnz** [comment]
Verified.

**Comment by markcowl** [comment]
@TimCurwick  @GamerLivingWill @swngdnz   In each of these cases, an enumeration is being written to the pipeline using ```WriteObect(<collection>, enumerateCollection:true)``` .  This seems to be the correct usage to allow standard pipeline access.  Will follow up with core team.

**Comment by markcowl** [comment]
We have the (rather simple) fix, which is that obviously, a ```PipelineStoppedException``` is a terminating exception, so allowing it to be thrown and uncaught inside ProcessRecord is the correct thing.  Simple fix, scheduled for this milestone

**Comment by markcowl** [comment]
Checked in fix will be released with Ignite (September release)
