### ISSUE TITLE
PowerShell Gallery does not have the correct url for the license for AzureRM.profile

### ISSUE THREAD

**Issue by tylerl0706** [Azure/azure-powershell#4328]
### Description
PowerShell Gallery does not have the correct url for the license for AzureRM.profile:
https://www.powershellgallery.com/packages/AzureRM.profile/3.2.0

### Script/Steps for Reproduction
go to the AzureRM.profile package in the PowerShell Gallery: https://www.powershellgallery.com/packages/AzureRM.profile/3.2.0

Click License on the left side... brings you to this:
https://raw.githubusercontent.com/Azure/azure-powershell/dev/LICENSE.txt

expected: a license
actual: 404 not found

**Comment by cormacpayne** [comment]
@tylerl0706 Hey Tyler, thanks for filing this issue. It looks like this is a result of removing our `dev` branch after we switched to `preview`. This should be a small change that can go out in the August release.

**Comment by tylerl0706** [comment]
Sounds good! I know I mentioned just AzureRM.profile but it might be worth checking the other Azure PowerShell modules as well. Not too sure what the state is on those.

**Comment by cormacpayne** [comment]
@tylerl0706 they're all referencing the old branch, so we will make sure the change is across the board 😄

**Comment by cormacpayne** [comment]
Fixed in the August release (scheduled to go out August 9th)
