### ISSUE TITLE
Enable-AzureDataCollection does not work, instead must use Enable-AzureRmDataCollection

### ISSUE THREAD

**Issue by sandersaares** [Azure/azure-powershell#4330]
### Cmdlet(s)
Enable-AzureDataCollection

### PowerShell Version
5.1.14393.1480

### Module Version
Whatever `Install-Module AzureRm` gave me.

### OS Version
10.0.14393.1480

### Description
The data collection message that is displayed on first use of AzureRM says:

> If you choose to not participate, you can enable at any time by using Azure PowerShell as follows:
> 1. Use the Enable-AzureDataCollection cmdlet to turn the feature On. The cmdlet can be found in the AzureRM.Profile module
> To enable data collection: PS > Enable-AzureDataCollection

But in practice, this command does not work as named.

> Enable-AzureDataCollection : The term 'Enable-AzureDataCollection' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Instead, one must use `Enable-AzureRmDataCollection`.

**Comment by cormacpayne** [comment]
@sandersaares Hey Sander, thanks for filing this issue. This should be a small documentation change that we can get out in the August release of Azure PowerShell.

**Comment by markcowl** [comment]
Fixed in August release (releasing 8/9)
