### ISSUE TITLE
New-AzureRmDiskUpdateConfig gives errors when used for updating managed disks.

### ISSUE THREAD

**Issue by DdenBraver** [Azure/azure-powershell#4331]
### PowerShell Version
5.1.14409.1005

### Module Version
AzureRM 4.2.1
AzureRM.Compute 3.2.1

### OS Version
10.0.14409.1005

### Description
New-AzureRmDiskUpdateConfig gives errors when used for updating managed disks.

### Debug Output
$osdiskconfig = New-AzureRmDiskUpdateConfig -AccountType $storageType
$null = Update-AzureRmDisk -ResourceGroupName $ResourceGroupName -DiskName $osdisk.Name -DiskUpdate $osdiskconfig

DEBUG: 1:44:46 PM - NewAzureRmDiskUpdateConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 1:44:46 PM - using account id '******************'...
DEBUG: 1:44:46 PM - NewAzureRmDiskUpdateConfigCommand end processing.
DEBUG: 1:44:46 PM - NewAzureRmDiskUpdateConfigCommand end processing.
DEBUG: 1:44:46 PM - UpdateAzureRmDisk begin processing with ParameterSet 'DefaultParameter'.
DEBUG: 1:44:46 PM - using account id '******************'...
DEBUG: [Common.Authentication]: Authenticating using Account: '******************', environment: 'AzureCloud', tenant: '******************'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:44:46: ****************** - AcquireTokenSilentHandler: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/******************/
	Resource: https://management.core.windows.net/
	ClientId: ******************
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (2 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:44:46:  - ProtectedFileTokenCache: Deserialized 2 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 07/19/2017 13:44:46: ****************** - <RunAsync>d__0: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:44:46: ****************** - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 07/19/2017 13:44:46: ****************** - <RunAsync>d__0: 33.11539197 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:44:46: ****************** - <RunAsync>d__0: A matching item (access token or refresh token or both) was found in the ca
che

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:44:46: ****************** - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was r
etuned:
	Access Token Hash: ******************
	Refresh Token Hash: ******************
	Expiration Time: 07/19/2017 14:17:53 +00:00
	User Hash: ******************
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:44:46: ****************** - AcquireTokenSilentHandler: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/******************/
	Resource: https://management.core.windows.net/
	ClientId: ******************
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (2 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:44:46:  - ProtectedFileTokenCache: Deserialized 2 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 07/19/2017 13:44:46: ****************** - <RunAsync>d__0: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:44:46: ****************** - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 07/19/2017 13:44:46: ****************** - <RunAsync>d__0: 33.11539197 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:44:46: ****************** - <RunAsync>d__0: A matching item (access token or refresh token or both) was found in the ca
che

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:44:46: ****************** - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was r
etuned:
	Access Token Hash: ******************
	Refresh Token Hash: ******************
	Expiration Time: 07/19/2017 14:17:53 +00:00
	User Hash: ******************
	

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com/subscriptions/******************/resourceGroups/s6-dannytst-rg-01/providers/Microsoft.Compute/disks/s6dannytstv
m-osdisk?api-version=2017-03-30

Headers:
x-ms-client-request-id        : ******************
accept-language               : en-US

Body:
{}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Accepted

Headers:
Pragma                        : no-cache
Azure-AsyncOperation          : https://management.azure.com/subscriptions/******************/providers/Microsoft.Compute/locations/westeuro
pe/DiskOperations/61b0ccfc-9c9f-4f83-bf8e-1c6a1db576a4?api-version=2017-03-30
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-served-by                : 253621e2-218a-4cc8-a789-d35113116566_131402074754472902
x-ms-request-id               : 61b0ccfc-9c9f-4f83-bf8e-1c6a1db576a4
Cache-Control                 : no-cache
Location                      : https://management.azure.com/subscriptions/******************/providers/Microsoft.Compute/locations/westeuro
pe/DiskOperations/61b0ccfc-9c9f-4f83-bf8e-1c6a1db576a4?monitor=true&api-version=2017-03-30
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1197
x-ms-correlation-request-id   : 163b513a-b67b-4f94-a7fb-a2eb0ad137d9
x-ms-routing-request-id       : WESTEUROPE:20170719T134446Z:163b513a-b67b-4f94-a7fb-a2eb0ad137d9
Date                          : Wed, 19 Jul 2017 13:44:45 GMT

Body:
{
  "sku": {
    "name": "Standard_LRS",
    "tier": "Standard"
  },
  "properties": {
    "creationData": {
      "createOption": "Copy",
      "sourceResourceId": "/subscriptions/******************/resourceGroups/az-infra-rg-01/providers/Microsoft.Compute/snapshots/WindowsBase
Image-WestEU_mqfzz13tl1a"
    },
    "diskSizeGB": 127,
    "provisioningState": "Updating",
    "isArmResource": true,
    "faultDomain": 0
  },
  "location": "westeurope",
  "tags": {
    "environment": "Test"
  }
}

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:45:16: ****************** - AcquireTokenSilentHandler: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/******************/
	Resource: https://management.core.windows.net/
	ClientId: ******************
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (2 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:45:16:  - ProtectedFileTokenCache: Deserialized 2 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 07/19/2017 13:45:16: ****************** - <RunAsync>d__0: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:45:16: ****************** - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 07/19/2017 13:45:16: ****************** - <RunAsync>d__0: 32.608526865 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:45:16: ****************** - <RunAsync>d__0: A matching item (access token or refresh token or both) was found in the ca
che

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:45:16: ****************** - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was r
etuned:
	Access Token Hash: ******************
	Refresh Token Hash: ******************
	Expiration Time: 07/19/2017 14:17:53 +00:00
	User Hash: ******************
	

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/******************/providers/Microsoft.Compute/locations/westeurope/DiskOperations/61b0ccfc-9c9f-
4f83-bf8e-1c6a1db576a4?api-version=2017-03-30

Headers:

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-served-by                : 253621e2-218a-4cc8-a789-d35113116566_131402074754472902
x-ms-request-id               : c10cc135-326b-46e6-a2cb-b258bdf423a2
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 14960
x-ms-correlation-request-id   : 587c4f04-f705-40da-8cdd-985375f7c2e3
x-ms-routing-request-id       : WESTEUROPE:20170719T134516Z:587c4f04-f705-40da-8cdd-985375f7c2e3
Date                          : Wed, 19 Jul 2017 13:45:15 GMT

Body:
{
  "startTime": "2017-07-19T13:44:47.4237001+00:00",
  "endTime": "2017-07-19T13:44:47.5643115+00:00",
  "status": "Succeeded",
  "properties": {
    "output": {
      "sku": {
        "name": "Standard_LRS",
        "tier": "Standard"
      },
      "properties": {
        "creationData": {
          "createOption": "Copy",
          "sourceResourceId": "/subscriptions/******************/resourceGroups/az-infra-rg-01/providers/Microsoft.Compute/snapshots/Windows
BaseImage-WestEU_mqfzz13tl1a"
        },
        "diskSizeGB": 127,
        "timeCreated": "2017-07-19T10:32:30.5084247+00:00",
        "provisioningState": "Succeeded",
        "diskState": "Unattached"
      },
      "type": "Microsoft.Compute/disks",
      "location": "westeurope",
      "tags": {
        "environment": "Test"
      },
      "id": "/subscriptions/******************/resourceGroups/s6-dannytst-rg-01/providers/Microsoft.Compute/disks/s6dannytstvm-osdisk",
      "name": "s6dannytstvm-osdisk"
    }
  },
  "name": "61b0ccfc-9c9f-4f83-bf8e-1c6a1db576a4"
}

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:45:16: 160e7336-1b1a-4294-a042-efae7e77eba9 - AcquireTokenSilentHandler: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/******************/
	Resource: https://management.core.windows.net/
	ClientId: ******************
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (2 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:45:16:  - ProtectedFileTokenCache: Deserialized 2 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 07/19/2017 13:45:16: 160e7336-1b1a-4294-a042-efae7e77eba9 - <RunAsync>d__0: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:45:16: 160e7336-1b1a-4294-a042-efae7e77eba9 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 07/19/2017 13:45:16: 160e7336-1b1a-4294-a042-efae7e77eba9 - <RunAsync>d__0: 32.60774351 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:45:16: 160e7336-1b1a-4294-a042-efae7e77eba9 - <RunAsync>d__0: A matching item (access token or refresh token or both) was found in the ca
che

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 07/19/2017 13:45:16: 160e7336-1b1a-4294-a042-efae7e77eba9 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was r
etuned:
	Access Token Hash: ******************
	Refresh Token Hash: ******************
	Expiration Time: 07/19/2017 14:17:53 +00:00
	User Hash: ******************
	

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/******************/resourceGroups/s6-dannytst-rg-01/providers/Microsoft.Compute/disks/s6dannytstv
m-osdisk?api-version=2017-03-30

Headers:

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-served-by                : 253621e2-218a-4cc8-a789-d35113116566_131402074754472902
x-ms-request-id               : 65245ca4-ea35-4d96-85bc-894da0601c23
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 14959
x-ms-correlation-request-id   : e2b7fb74-b413-4ccf-a20e-ffe88fed1c88
x-ms-routing-request-id       : WESTEUROPE:20170719T134516Z:e2b7fb74-b413-4ccf-a20e-ffe88fed1c88
Date                          : Wed, 19 Jul 2017 13:45:15 GMT

Body:
{
  "sku": {
    "name": "Standard_LRS",
    "tier": "Standard"
  },
  "properties": {
    "creationData": {
      "createOption": "Copy",
      "sourceResourceId": "/subscriptions/******************/resourceGroups/az-infra-rg-01/providers/Microsoft.Compute/snapshots/WindowsBase
Image-WestEU_mqfzz13tl1a"
    },
    "diskSizeGB": 127,
    "timeCreated": "2017-07-19T10:32:30.5084247+00:00",
    "provisioningState": "Succeeded",
    "diskState": "Unattached"
  },
  "type": "Microsoft.Compute/disks",
  "location": "westeurope",
  "tags": {
    "environment": "Test"
  },
  "id": "/subscriptions/******************/resourceGroups/s6-dannytst-rg-01/providers/Microsoft.Compute/disks/s6dannytstvm-osdisk",
  "name": "s6dannytstvm-osdisk"
}

Update-AzureRmDisk : Missing type map configuration or unsupported mapping.
Mapping types:
Disk -> PSDisk
Microsoft.Azure.Management.Compute.Models.Disk -> Microsoft.Azure.Commands.Compute.Automation.Models.PSDisk
Destination path:
PSDisk
Source value:
Microsoft.Azure.Management.Compute.Models.Disk
At line:2 char:25
+ ...     $null = Update-AzureRmDisk -ResourceGroupName $ResourceGroupName  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-AzureRmDisk], AutoMapperMappingException
    + FullyQualifiedErrorId : AutoMapper.AutoMapperMappingException,Microsoft.Azure.Commands.Compute.Automation.UpdateAzureRmDisk

### Script/Steps for Reproduction
New-AzureRmDiskUpdateConfig -AccountType $storageType | Update-AzureRmDisk -ResourceGroupName $ResourceGroupName -DiskName "vmname-datadisk1"

### Work-around
$disk = Get-AzureRMDisk -ResourceGroupName $ResourceGroupName -DiskName "vmname-datadisk1"
$disk.AccountType = $storageType
$null = Update-AzureRmDisk -ResourceGroupName $ResourceGroupName -DiskName "vmname-datadisk1" -Disk $disk

**Comment by cormacpayne** [comment]
@hyonholee Hey Hyonho, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
@DdenBraver Hey Danny, is this still an issue for you with the latest version of Azure PowerShell? If so, I have merged a PR that fixes issues users are seeing with AutoMapper that will be available in the November release of Azure PowerShell (version 5.0.0 - set to release November 8th).

**Comment by DdenBraver** [comment]
@cormacpayne , It seems this issue is resolved with the latest version of Azure PowerShell.

**Comment by cormacpayne** [comment]
@DdenBraver Hey Danny, thanks for the update ☺️ 

Closing this issue since it has been resolved.
