### ISSUE TITLE
AzureRm.Bootstrapper: Install-AzureRmProfile in disconnected scenarios

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#4336]
### Cmdlet(s)
Install-AzureRmProfile , Use-AzureRmProfile

### PowerShell Version
5.0

### Module Version
0.1.0, 0.2.0

### Description
For Install-AzureRmProfile in disconnected scenarios, should we advise the users to use Set-BootstrapRepo to set a local repository? Or should we just not support it in disconnected scenarios?

**Comment by bganapa** [comment]
With disconnected scenario, the user has no access to the blob storage where we maintain the profilemap for update scenario. One way is to expose this blob uri customizable for the disconnected scenarios.

**Comment by markcowl** [comment]
Won't fix
