### ISSUE TITLE
Connect-AzureAD - Does not work with ServicePrincipal and password

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#4339]
### Cmdlet(s)
Connect-AzureAD

### PowerShell Version
4.0

### OS Version
6.3.9600.18728

### Description

Unable to use Service Principal with password - instead of service principal and certificate - as described in the article: [https://docs.microsoft.com/en-us/powershell/module/azuread/connect-azuread?view=azureadps-2.0](url)

This should ideally work as Login-AzureRmAccount with ServicePrincipal and Password instead of Certificates.

### Debug Output

Debug out

### Script/Steps for Reproduction

![image](https://user-images.githubusercontent.com/13054214/28391359-b04b1ee4-6cab-11e7-90a2-2cba7a4d8a68.png)

**Comment by rajaprad** [comment]
@RobdeJong , @TaraMeyer  - Please help on this.

**Comment by cormacpayne** [comment]
@rajaprad Azure PowerShell does not own the Azure AD cmdlets, so I'm going to close this issue.

@TaraMeyer @RobdeJong is there a separate location that this issue should be filed? We usually tell users to check out the [multiple support communities](https://azure.microsoft.com/en-us/support/forums/) we have.
