### ISSUE TITLE
Cannot Pipe Get-AzureRmServiceBusNameSpace to remove or other cmdlets

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#4340]
### PowerShell Version
5.1

### Module Version
4.2.1

### OS Version
Windows 10

### Description

When attempting to pipe the output of Get-AzureRmServiceBusNamespace to Remove-AzureRmServiceBusNamespace, powershell returns an error like the following
```powershell
Remove-AzureRmServiceBusNamespace : The input object cannot be bound to any parameters for the command either becaus
the command does not take pipeline input or the input and its properties do not match any of the parameters that tak
pipeline input.
```

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
Get-AzureRmServiceBusNamespace | Remove-AzureRmServiceBusNamespace

**Comment by v-Ajnava** [comment]
fixed in the latest release
