### ISSUE TITLE
404 on link in README.md

### ISSUE THREAD

**Issue by yobyot** [Azure/azure-powershell#4343]
Oooppss. Makes a noob wonder...

![2017-07-20_9-27-52](https://user-images.githubusercontent.com/14332263/28419890-71379a38-6d2e-11e7-9737-79b98f84f092.png)

**Comment by cormacpayne** [comment]
@yobyot good catch! It looks like GitHub is treating the link as a relative path in the repository. I'll update that now. In the meantime, you can navigate to that site [here](https://aka.ms/azpsdocs).

**Comment by cormacpayne** [comment]
@yobyot this has been fixed and merged!
