### ISSUE TITLE
Add-AzureRMHDInsightClusterConfig error with RServer parameter failing with parameter set error

### ISSUE THREAD

**Issue by joshuafennessy** [Azure/azure-powershell#4351]
### Cmdlet(s)
Add-AzureRMHDInsightClusterConfig
### PowerShell Version
5.1.14393.1480 

### Module Version
4.21

### OS Version
10.0.14393.1480

### Description
Creating an RServer HDInsight Cluster using PowerShell -- encountering an error when using the Add-AzureRMHDInsightClusterConfig cmdlet to specify that RStudio should be enabled with RServer.  The error message is: Add-AzureRmHDInsightConfigValues : Parameter set cannot be resolved using the specified named parameters. 

### Debug Output

DEBUG: 10:36:35 AM - GetAzureResourceGroupCmdlet end processing.
DEBUG: 10:36:35 AM - GetAzureResourceGroupCmdlet end processing.
DEBUG: 10:36:35 AM - NewAzureHDInsightClusterConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 10:36:35 AM - using account id 'jfennessy@blue-granite.com'...
DEBUG: 10:36:35 AM - AddAzureHDInsightMetastoreCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 10:36:35 AM - using account id 'jfennessy@blue-granite.com'...
DEBUG: 10:36:35 AM - AddAzureHDInsightMetastoreCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 10:36:35 AM - using account id 'jfennessy@blue-granite.com'...
DEBUG: 10:36:35 AM - AddAzureHDInsightClusterIdentity begin processing with ParameterSet 'CertificateFilePath'.
DEBUG: 10:36:35 AM - using account id 'jfennessy@blue-granite.com'...
DEBUG: 10:36:35 AM - AddAzureHDInsightStorageCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 10:36:35 AM - using account id 'jfennessy@blue-granite.com'...
DEBUG: 10:36:35 AM - AddAzureHDInsightScriptActionCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 10:36:35 AM - using account id 'jfennessy@blue-granite.com'...
DEBUG: 10:36:35 AM - AddAzureHDInsightScriptActionCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 10:36:35 AM - using account id 'jfennessy@blue-granite.com'...
DEBUG: 10:36:35 AM - AddAzureHDInsightScriptActionCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 10:36:35 AM - using account id 'jfennessy@blue-granite.com'...
DEBUG: 10:36:35 AM - AddAzureHDInsightConfigValuesCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 10:36:35 AM - using account id 'jfennessy@blue-granite.com'...
Add-AzureRmHDInsightConfigValues : Parameter set cannot be resolved using the specified named parameters.
At Y:\.......\BuildHDICluster_cbids.ps1:102 char:10
+        | Add-AzureRmHDInsightConfigValues `
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Azure...HDInsightConfig:PSObject) [Add-AzureRmHDInsightConfigValues], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.HDInsight.AddAzureHDInsightConfigValuesCommand
 
DEBUG: 10:36:35 AM - NewAzureHDInsightClusterConfigCommand end processing.
DEBUG: 10:36:35 AM - NewAzureHDInsightClusterConfigCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightMetastoreCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightMetastoreCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightMetastoreCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightMetastoreCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightClusterIdentity end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightClusterIdentity end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightStorageCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightStorageCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightScriptActionCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightScriptActionCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightScriptActionCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightScriptActionCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightScriptActionCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightScriptActionCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightConfigValuesCommand end processing.
DEBUG: 10:36:35 AM - AddAzureHDInsightConfigValuesCommand end processing.
New-AzureRmHDInsightCluster : Cannot bind parameter 'Config' to the target. Exception setting "Config": "Object reference not set to an instance of an object."
At Y:\......\BuildHDICluster_cbids.ps1:113 char:13
+     -Config $hdiConfig `
+             ~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [New-AzureRmHDInsightCluster], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.Azure.Commands.HDInsight.NewAzureHDInsightClusterCommand

### Script/Steps for Reproduction

```powershell
$rserverConfig = @{"RStudio"="true"}

$hdiConfig = New-AzureRmHDInsightClusterConfig `
            -clusterType $clusterType `
            -HeadNodeSize "Standard_D13_v2" `
            -WorkerNodeSize "Standard_D13_v2" `
            -EdgeNodeSize "Standard_D4_v2" `
            -ZookeeperNodeSize "Medium" `
            -ClusterTier Standard `
            -DefaultStorageAccountType AzureStorage `
            -DefaultStorageAccountName "$clusterDefaultStorageAccount.blob.core.windows.net" `
            -DefaultStorageAccountKey $clusterDefaultStorageAccountKey `
       | Add-AzureRmHDInsightMetastore `
         -SqlAzureServerName $hiveMetastoreDatabaseServerName `
         -DatabaseName $hiveMetastoreDatabaseName `
         -Credential $clusterHiveDBCred `
         -MetastoreType HiveMetastore `
       |  Add-AzureRmHDInsightMetastore `
         -SqlAzureServerName $oozieMetastoreDatabaseServerName `
         -DatabaseName $oozieMetastoreDatabaseName `
         -Credential $clusterOozieDBCred `
         -MetastoreType OozieMetastore `
       | Add-AzureRmHDInsightClusterIdentity `
         -AadTenantId $tenantID `
         -ObjectID $clusterServicePrincipalObjectID `
         -CertificateFilePath $clusterServicePrincipalCertPath `
         -CertificatePassword $clusterServicePrincipalCertPassword `
       | Add-AzureRmHDInsightStorage `
         -StorageAccountName "......blob.core.windows.net" `
         -storageAccountKey $AccountKey `
       | Add-AzureRmHDInsightScriptAction `
         -NodeType HeadNode `
         -Uri $clusterRPackagesScriptActionURI `
         -Name "Install R Packages" `
       | Add-AzureRmHDInsightScriptAction `
         -NodeType WorkerNode `
         -Uri $clusterRPackagesScriptActionURI `
         -Name "Install R Packages" `
       | Add-AzureRmHDInsightScriptAction `
         -NodeType EdgeNode `
         -Uri $clusterRPackagesScriptActionURI `
         -Name "Install R Packages" `
       | Add-AzureRmHDInsightConfigValues `
         -RServer $rserverConfig
     
New-AzureRmHDInsightCluster `
    -ClusterName $clusterName `
    -ClusterSizeInNodes $clusterSizeInNodes `
    -DefaultStorageContainer $clusterDeafultContainer `
    -ResourceGroupName $azureResourceGroupName `
    -Config $hdiConfig `
    -OSType Linux `
    -Location "East US 2" `
    -Version $clusterVersion `
    -HttpCredential $clusterAdminCred `
    -SshCredential $clusterSSHCred
```

**Comment by cormacpayne** [comment]
@shefaliv Hey Shefali, would you mind taking a look at this issue?

**Comment by janus-christensen** [comment]
Hello,

I am facing a similar issue with Add-AzureRmHDInsightConfigValues. I try to create a new HDInsight cluster using the following:

    New-AzureRmHDInsightClusterConfig `
        | Add-AzureRmHDInsightConfigValues -Core $CoreConfigValues `
    	| Add-AzureRmHDInsightMetastore `
    		-SqlAzureServerName $sqlServer `
    		-Credential $sqlServerCredential `
    		-DatabaseName $hiveDb `
    		-MetastoreType HiveMetastore `
    	| New-AzureRmHDInsightCluster `
    		-ClusterName $clusterName `
    		-ResourceGroupName $resourceGroupName `
    		-HttpCredential $clusterCredential `
    		-Location $location `
    		-DefaultStorageAccountName "$storageAccountName.blob.core.windows.net" `
    		-DefaultStorageAccountKey $storageAccountKey `
    		-DefaultStorageContainer $containerName `
    		-ClusterSizeInNodes $clusterNodes `
    		-ClusterType $clusterType `
    		-OSType $clusterOS `
    		-Version "3.6" `
    		-SshCredential $sshCredential `
    		-HeadNodeSize $clusterNodeSize `
    		-WorkerNodeSize $clusterNodeSize

Running the command above returns this error:

    Add-AzureRmHDInsightConfigValues : Parameter set cannot be resolved using the specified named parameters.
    At C:\Users\chrisjan\Code\CreateHDI.ps1
    +     | Add-AzureRmHDInsightConfigValues -Core $CoreConfigValues `
    +       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidArgument: (Microsoft.Azure...HDInsightConfig:PSObject) [Add-AzureRmHDInsightConfigValue
        + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.HDInsight.AddAzureHDInsightConfigValuesCommand

I have tried to create the HDInsight configuration manually like this:

    PS C:\> $CoreConfigValues = @{ <core configuration values> }
    PS C:\> $clusterConfig = New-AzureRmHDInsightClusterConfig
    PS C:\> Add-AzureRmHDInsightConfigValues -Config $clusterConfig -Core $CoreConfigValues

When I run the Add-AzureRmHDInsightConfigValues CmdLet I get this error:

    Add-AzureRmHDInsightConfigValues : Parameter set cannot be resolved using the specified named parameters.
    At line:1 char:1
    + Add-AzureRmHDInsightConfigValues -Config $clusterConfig -Core $CoreCo ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidArgument: (:) [Add-AzureRmHDInsightConfigValues], ParameterBindingException
        + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.HDInsight.AddAzureHDInsightConfigValuesCommand

I am pretty certain that both ways I have been trying to add the configuration worked previously (a few months ago).

Thanks!

$PSVersionTable:

    Name                           Value
    ----                           -----
    PSVersion                      5.1.14393.206
    PSEdition                      Desktop
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    BuildVersion                   10.0.14393.206
    CLRVersion                     4.0.30319.42000
    WSManStackVersion              3.0
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1

**Comment by srinivan** [comment]
Is there any ETA for fixing this issue? We are creating work around for creating transient clusters. A fix will be very helpful.

**Comment by mykovalenko** [comment]
Just had the same issue myself. You can solve it by adding **-Spark2Defaults** parameter (no need to specify any values though):
... | Add-AzureRmHDInsightConfigValues **-Spark2Defaults @{}** -RServer @{"RStudio"="true"}

**Comment by dagiro** [comment]
I encountered the same issue while following the second PowerShell code example at [Customize HDInsight clusters using Bootstrap](https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-hadoop-customize-cluster-bootstrap#appendix-powershell-sample). I was able to resolve the issue following @mykovalenko suggestion. Could you update the documentation for `Add-AzHDInsightConfigValues`? I do note that this issue was open for `Add-AzureRMHDInsightClusterConfig` and not `AzHDInsightConfigValues`.
On my end, I have submitted https://github.com/MicrosoftDocs/azure-docs-pr/pull/73869 to update [Customize HDInsight clusters using Bootstrap](https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-hadoop-customize-cluster-bootstrap#appendix-powershell-sample) so my readers do not face the same issue. I have added the parameter to the code examples, as well as an [!IMPORTANT] stating that the parameter _may_ need to be passed. But is it _may_ or _must_? The change is not yet live, let me know if you would prefer different language.

**Comment by markcowl** [comment]
sprint160
