### ISSUE TITLE
Error while deploying locally - Azure IOT remote monitoring suite

### ISSUE THREAD

**Issue by sansoft59** [Azure/azure-powershell#4354]
Team,

I am a new bie on Azure IOT 

We are trying out this IOT remote monitoring suite from github. We are trying to first deploy that locally instead of Azure and hence we have followed the document mentioned here https://github.com/Azure/azure-iot-remote-monitoring/blob/master/Docs/local-deployment.md

Also, we have followed the pre-requisites over here https://github.com/Azure/azure-iot-remote-monitoring/blob/master/Docs/dev-setup.md

While setting up the pre-requisites we come across the step to Import the Azure RM module. 

So when i run the command using the admin priveleges on the powershell

i get this error

*PS C:\Users\****> Import-Module AzureRM
Import-Module : File C:\Program Files\WindowsPowerShell\Modules\AzureRM\4.2.1\AzureRM.psm1 cannot be loaded because
its operation is blocked by software restriction policies, such as those created by using Group Policy.**
*`

I have tried everything from restating the machine, uninstalling the azure powershell and re-installing...Checking the priveleges of the running scripts which is as below...

When i do a get-executionpolicy -list i get the below.

  Scope  ExecutionPolicy
MachinePolicy       Undefined
 UserPolicy       Undefined
  Process       Undefined
 CurrentUser    RemoteSigned
 LocalMachine    Unrestricted 

Can anyone please help me ? I have run out of ideas.

**Comment by markcowl** [comment]
@sansoft59 What OS are you running?  The error is not consistent with an ExecutionPolicy issue, and the cmdlets should work with the RemoteSigned policy in any case.

In your PowerrShell window, where you see the import failure, cna you try `Get-ExecutionPolicy`, just so we can rule out execution policy anyway.

This looks more like one of the Windows 10 / WIndows Server 2016 new group policy [restrictions](https://docs.microsoft.com/en-us/windows/client-management/new-policies-for-windows-10).  Can you verify which OS youy are using and the group policy settings for the machine?

**Comment by sansoft59** [comment]
Thanks for your reply. 

OS I  am using is Windows 7 professional SP1.  When i do  Get-ExecutionPolicy, I get the "Unrestricted".

When i do Get-ExecutionPolicy -List  i get the following 
        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy    Unrestricted
   UserPolicy    Unrestricted
      Process       Undefined
  CurrentUser    RemoteSigned
 LocalMachine    RemoteSigned

**Comment by markcowl** [comment]
@sansoft59  It sounds ;like you have group policies configured on the machine that prevent loading PowerShell modules.  This is an issue you will needd to resolve with your OS configuration
