### ISSUE TITLE
AzureRm.Bootstrapper: Partial installation of AzureRm ends up in module not found error

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#4357]
### Cmdlet(s)
Use-AzureRmProfile
Install-AzureRmProfile

### PowerShell Version
5.0

### Module Version
0.1.0, 0.2.0

### Description
If user had installed `AzureRm `previously but ends up only with` AzureRm.psd1 `and not `AzureRm.psm1`, this leads Bootstrapper to think AzureRm is installed but fails to load the module as `.psm1 `is not available. Because of this situation, Bootstrapper will skip installing the required version of AzureRm modules and throws modules not found in any directory error.

### Script/Steps for Reproduction
PS C:\> Set-PSRepository  -Name "PSGallery"  -InstallationPolicy Trusted
PS C:\> Get-Module -ListAvailable | where-Object {$_.Name -like “Azure*”} | Uninstall-Module
PS C:\> Install-Module  -Name AzureRm.BootStrapper
PS C:\> Use-AzureRmProfile  -Profile 2017-03-09-profile -Force
Loading Profile 2017-03-09-profile

> Import-Module : The specified module 'AzureRM' with version '1.2.10' was not loaded because no valid module file was found in any module directory.
> At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.2.0\AzureRM.BootStrapper.psm1:1062 char:9
>          Import-Module -Name $Module -RequiredVersion $version -Global
>          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : ResourceUnavailable: (AzureRM:String) [Import-Module], FileNotFoundException
>      FullyQualifiedErrorId : Modules_ModuleWithVersionNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
>

**Comment by viananth** [comment]
This is a unique situation where a user might only have AzureRm.psd1 and not AzureRm.psm1 module in AzureRm directory.

**Comment by bganapa** [comment]
This is low pri to fix

**Comment by markcowl** [comment]
Closing as won't fix
