### ISSUE TITLE
Password parameter and other password-like parameters expect a plain-text string

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#4359]
A bunch of AzureRM cmdlets that deal with secrets using -Password, -CertificatePassword and other password-like parameters (for example, for working with "keys") expect a string value instead of a SecureString value or PSCredential.

For example:
```
PS C:\> gcm -Module azurerm.* -ParameterName password -ParameterType string

CommandType Name Version Source
----------- ---- ------- ------
Cmdlet Add-AzureRmApplicationGatewaySslCertificate 3.6.0 AzureRM.Network
Cmdlet New-AzureBatchCertificate 2.7.0 AzureRM.Batch
Cmdlet New-AzureBatchComputeNodeUser 2.7.0 AzureRM.Batch
Cmdlet New-AzureRmADAppCredential 3.7.0 AzureRM.Resources
Cmdlet New-AzureRmADApplication 3.7.0 AzureRM.Resources
Cmdlet New-AzureRmADServicePrincipal 3.7.0 AzureRM.Resources
Cmdlet New-AzureRmADSpCredential 3.7.0 AzureRM.Resources
Cmdlet New-AzureRmADUser 3.7.0 AzureRM.Resources
Cmdlet New-AzureRmApiManagementBackendProxy 3.5.0 AzureRM.ApiManagement
Cmdlet New-AzureRmApiManagementUser 3.5.0 AzureRM.ApiManagement
Cmdlet New-AzureRmApplicationGatewaySslCertificate 3.6.0 AzureRM.Network
Cmdlet Set-AzureBatchComputeNodeUser 2.7.0 AzureRM.Batch
Cmdlet Set-AzureRmADUser 3.7.0 AzureRM.Resources
Cmdlet Set-AzureRmApiManagementUser 3.5.0 AzureRM.ApiManagement
Cmdlet Set-AzureRmApplicationGatewaySslCertificate 3.6.0 AzureRM.Network
Cmdlet Set-AzureRmVMAccessExtension 2.8.0 AzureRM.Compute
```

**Comment by markcowl** [comment]
### Description

Per PowerShell team advice, single-value secrets (e.g. certificate passwords) whould be represented as SecureString parameters.

For each of the obove cmdlets:

- [ ] Reach out to feature team wit a recommendation to add a new secure parameter, or change the parameter type in November
  - [ ] New parameter types should be SecureString for single value secrets, or PSCredential for credentials (username/pw; SPN/secret, etc.)
- [ ] Add an obsolete message to each of these parameters in the September release to indicate the name or name/type change
- [ ] Add to the upcoming breaking change doc

###Cost: 2

**Comment by maddieclayton** [comment]
Last task associated with this issue: Ensure that each team makes the necessary changes before the November release.
- [ ] Network
- [ ] Batch
- [ ] Resources
- [ ] ApiManagement
- [ ] Compute

**Comment by maddieclayton** [comment]
Fixed
