### ISSUE TITLE
Add -ResourceId parameter for all core Get-AzureRm* commands

### ISSUE THREAD

**Issue by adwaitu** [Azure/azure-powershell#4366]
### Cmdlet(s)

Any of the Get-AzureRm* commands

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1.14393.1480

### Module Version
Manifest   0.4.0      AzureRM.AnalysisServices            {Resume-AzureRmAnalysisServicesServe...
Manifest   4.1.0      AzureRM.ApiManagement               {Add-AzureRmApiManagementRegion, Get...
Manifest   3.1.0      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGr...
Manifest   3.1.0      AzureRM.Backup                      {Backup-AzureRmBackupItem, Enable-Az...
Manifest   3.1.0      AzureRM.Batch                       {Remove-AzureRmBatchAccount, Get-Azu...
Manifest   0.13.0     AzureRM.Billing                     {Get-AzureRmBillingInvoice, Get-Azur...
Manifest   3.1.0      AzureRM.Cdn                         {Get-AzureRmCdnProfile, Get-AzureRmC...
Manifest   0.8.0      AzureRM.CognitiveServices           {Get-AzureRmCognitiveServicesAccount...
Manifest   3.1.0      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-...
Manifest   0.2.0      AzureRM.Consumption                 Get-AzureRmConsumptionUsageDetail      
Manifest   0.2.0      AzureRM.ContainerRegistry           {New-AzureRmContainerRegistry, Get-A...
Manifest   3.1.0      AzureRM.DataFactories               {Remove-AzureRmDataFactory, Get-Azur...
Manifest   3.1.0      AzureRM.DataLakeAnalytics           {Get-AzureRmDataLakeAnalyticsDataSou...
Manifest   4.1.0      AzureRM.DataLakeStore               {Get-AzureRmDataLakeStoreTrustedIdPr...
Manifest   3.1.0      AzureRM.DevTestLabs                 {Get-AzureRmDtlAllowedVMSizesPolicy,...
Manifest   3.1.0      AzureRM.Dns                         {Get-AzureRmDnsRecordSet, New-AzureR...
Manifest   0.4.0      AzureRM.EventHub                    {New-AzureRmEventHubKey, Get-AzureRm...
Manifest   3.1.0      AzureRM.HDInsight                   {Get-AzureRmHDInsightJob, New-AzureR...
Manifest   3.1.0      AzureRM.Insights                    {Get-AzureRmUsage, Get-AzureRmMetric...
Manifest   2.1.0      AzureRM.IotHub                      {Add-AzureRmIotHubKey, Get-AzureRmIo...
Manifest   3.1.0      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Set-A...
Manifest   3.1.0      AzureRM.LogicApp                    {Get-AzureRmIntegrationAccountAgreem...
Manifest   0.15.0     AzureRM.MachineLearning             {Move-AzureRmMlCommitmentAssociation...
Manifest   0.7.0      AzureRM.Media                       {Sync-AzureRmMediaServiceStorageKeys...
Manifest   4.1.0      AzureRM.Network                     {Add-AzureRmApplicationGatewayAuthen...
Manifest   3.1.0      AzureRM.NotificationHubs            {Get-AzureRmNotificationHub, Get-Azu...
Manifest   3.1.0      AzureRM.OperationalInsights         {New-AzureRmOperationalInsightsAzure...
Manifest   3.1.0      AzureRM.PowerBIEmbedded             {Remove-AzureRmPowerBIWorkspaceColle...
Manifest   3.1.0      AzureRM.Profile                     {Disable-AzureRmDataCollection, Enab...
Manifest   3.1.0      AzureRM.RecoveryServices            {Get-AzureRmRecoveryServicesBackupPr...
Manifest   3.1.0      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRecoveryServicesBacku...
Manifest   3.1.0      AzureRM.RedisCache                  {Remove-AzureRmRedisCachePatchSchedu...
Manifest   0.2.0      AzureRM.Relay                       {New-AzureRmRelayNamespace, Get-Azur...
Manifest   4.1.0      AzureRM.Resources                   {Get-AzureRmProviderOperation, Remov...
Manifest   0.15.0     AzureRM.Scheduler                   {Disable-AzureRmSchedulerJobCollecti...
Manifest   3.1.0      AzureRM.ServerManagement            {Invoke-AzureRmServerManagementPower...
Manifest   0.4.0      AzureRM.ServiceBus                  {Get-AzureRmServiceBusTopic, Get-Azu...
Manifest   0.2.0      AzureRM.ServiceFabric               {Add-AzureRmServiceFabricApplication...
Manifest   4.1.0      AzureRM.SiteRecovery                {Get-AzureRmSiteRecoveryFabric, New-...
Manifest   3.1.0      AzureRM.Sql                         {Get-AzureRmSqlDatabaseTransparentDa...
Manifest   3.1.0      AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-Azur...
Manifest   3.1.0      AzureRM.StreamAnalytics             {Get-AzureRmStreamAnalyticsFunction,...
Manifest   3.1.0      AzureRM.Tags                        {Remove-AzureRmTag, Get-AzureRmTag, ...
Manifest   3.1.0      AzureRM.TrafficManager              {Disable-AzureRmTrafficManagerEndpoi...
Manifest   3.1.0      AzureRM.UsageAggregates             Get-UsageAggregates                    
Manifest   3.1.0      AzureRM.Websites                    {Get-AzureRmAppServicePlan, Set-Azur...

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.14393.1480

### Description
Since a number of Get- commands return the resource id, all of the get commands should support the ResourceId parameter

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
n/a
### Script/Steps for Reproduction
n/a

**Comment by cormacpayne** [comment]
@adwaitu Hey Adwait, this is an excellent suggestion and is one of the things that we are considering for cmdlet consistency this fall.

**Comment by adwaitu** [comment]
@cormacpayne can't wait for it, traversing the link will be much simpler then! BTW, are you also planning to add a "Resource Type" or "Kind" to returned Resource ID for every Get-AzureRm* command? Or do I need to raise another issue?

**Comment by maddieclayton** [comment]
Closing in favor of: https://github.com/Azure/azure-powershell/issues/5901.  This will cover both InputObject and ResourceId piping scenarios.
