### ISSUE TITLE
AzureRm.Bootstrapper: Install-AzureRmProfile needs to prompt users if they'd like to install the latest versions in that profile

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#4370]
### Cmdlet(s)
`Install-AzureRmProfile `

### PowerShell Version
5.0

### Module Version
0.1.0, 0.2.0

### Description
`Install-AzureRmProfile `will ignore installing the profile if one of the versions in that profile is already installed. Instead of this behavior, it should prompt the user if they'd like to install the latest versions in that profile if a new one is available.

For example, if user has `AzureRm 1.2.9` installed, and `2017-03-09-profile `has a newer version of AzureRm (1.2.10), then` Install-AzureRmProfile -profile 2017-03-09-profile  `should prompt the user if they'd like to install the latest version (1.2.10)

**Comment by cormacpayne** [comment]
@viananth is this issue still active?

**Comment by dingmeng-xue** [comment]
Close this old issue due to inactivity.
