### ISSUE TITLE
Set-AzureRmVmDscExtension Issue

### ISSUE THREAD

**Issue by ptoluganti** [Azure/azure-powershell#4376]
### Cmdlet(s)
Set-AzureRmVmDscExtension

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

Powershell 5.0

### Module Version
Set-AzureRmVmDscExtension -Version 2.26

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
1. i have created VM in azure devtest labs and applied dsc extension using Set-AzureRmVmDscExtension and the configuration is applied.
2. taken snapshot of the vm, exported vhd and stored to blob.
3. created image from VHD blob and created new VM from newly created image
4. now trying to apply dsc extension using Set-AzureRmVmDscExtension, it shows extension IsSuccessStatusCode true.
now the problem is it showing only the extension which is applied in 1st step and even configuration is not applied. checked in logs i could not see any logs inside VM and even cannot see dsc package inside VM. I am really confused why.

LCM is configured to ApplyOnly

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue, or assigning it to the proper contact for extension cmdlets?

**Comment by singhkays** [comment]
Adding @narrieta

**Comment by narrieta** [comment]
@eshaparmar for follow up

**Comment by shurick81** [comment]
I tried a workaround and it worked for me: before taking an image I removed the dsc extension from the machine via Remove-AzureRmVMDscExtension command.

**Comment by ptoluganti** [comment]
Thank you. yes, removing dsc extension before taking snapshot did work. Also as an alternate you can have two configurations in the same .ps1 and call the first one before taking snapshot and the other one later.

**Comment by ptoluganti** [comment]
Thank you, Yes removing DscExtension before taking snapshot did work. Also as an alternate you can have two configurations in the same .ps1 and call the first one before taking snapshot and the other one later.

**Comment by maddieclayton** [comment]
@eshaparmar Can you take a look at this issue?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please let us know if this issue is still a concern.
