### ISSUE TITLE
Automapper errors with Azure Compute and Network modules

### ISSUE THREAD

**Issue by SudhakaraReddyEvuri** [Azure/azure-powershell#4385]
We are hitting automapper errors while creating PublicIP and availability sets .  AzureRM.Network is version 4.2.1 and AzureRM.Compute is version 3.2.1

Missing type map configuration or unsupported mapping.

 Mapping types:
PublicIPAddress -> PSPublicIpAddress
Microsoft.Azure.Management.Network.Models.PublicIPAddress -> Microsoft.Azure.Commands.Network.Models.PSPublicIpAddress

 Destination path:
PSPublicIpAddress

 Source value:
Microsoft.Azure.Management.Network.Models.PublicIPAddress

Missing type map configuration or unsupported mapping.

Mapping types:
AvailabilitySet -> PSAvailabilitySet
Microsoft.Azure.Management.Compute.Models.AvailabilitySet -> Microsoft.Azure.Commands.Compute.Models.PSAvailabilitySet

 Destination path:
PSAvailabilitySet

 Source value:
Microsoft.Azure.Management.Compute.Models.AvailabilitySet

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft Hey Deepak, would you mind taking a look at this issue? Sudhakar says that this issue is occurring during execution of `New-AzureRmPublicIpAddress`:

```powershell
$vmConfigPubip = New-AzureRmPublicIpAddress -Force -Name $vmConfigPublicIpName -ResourceGroupName $resourceGroupName -Location $region -AllocationMethod Dynamic -DomainNameLabel $vmConfigPublicIpName
```

**Comment by KarlGW** [comment]
This also happens when using `Get-AzureVm`.

`Get-AzureVM : Missing type map configuration or unsupported mapping.`
`GuestAgentStatus -> GuestAgentStatus`
`Microsoft.WindowsAzure.Management.Compute.Models.GuestAgentStatus -> Microsoft.WindowsAzure.Commands.ServiceManagement.Model.GuestAgentStatus`

**Comment by paulb2011** [comment]
PS C:\> Get-AzureVM
Get-AzureVM : Missing type map configuration or unsupported mapping.
Mapping types:
GuestAgentStatus -> GuestAgentStatus
Microsoft.WindowsAzure.Management.Compute.Models.GuestAgentStatus ->
Microsoft.WindowsAzure.Commands.ServiceManagement.Model.GuestAgentStatus
Destination path:
GuestAgentStatus
Source value:
Microsoft.WindowsAzure.Management.Compute.Models.GuestAgentStatus
At line:1 char:1
+ Get-AzureVM
+ ~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureVM], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.GetAzureVMCommand

PS C:\> (Get-Module azure).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
4      2      1      -1

**Comment by gulabpasha** [comment]
I'm also facing the same issue while created Network Resources.

New-AzureRmPublicIpAddress : Missing type map configuration or unsupported mapping.

Mapping types:
PSPublicIpAddress -> PublicIPAddress
Microsoft.Azure.Commands.Network.Models.PSPublicIpAddress -> Microsoft.Azure.Management.Network.Models.PublicIPAddress

Destination path:
PublicIPAddress

Source value:
Microsoft.Azure.Commands.Network.Models.PSPublicIpAddress
At Parallel-New-Gulab:123 char:123
+ 
    + CategoryInfo          : CloseError: (:) [New-AzureRmPublicIpAddress], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzurePublicIpAddressCommand

**Comment by russhack** [comment]
I've noticed I get the same issue when working in Classic then RM then back to Classic commands.
4.3.1 of Azure Module.
3.3.1 of AzureRM.Compute
5.1.14393.1532 of PSVersion.

get-azurevm : Missing type map configuration or unsupported mapping.
Mapping types:
GuestAgentStatus -> GuestAgentStatus
Microsoft.WindowsAzure.Management.Compute.Models.GuestAgentStatus -> Microsoft.WindowsAzure.Commands.ServiceManagement.Model.GuestAgentStatus
Destination path:
GuestAgentStatus
Source value:
Microsoft.WindowsAzure.Management.Compute.Models.GuestAgentStatus
At C:\ps\update_NSGs.ps1:19 char:9
+     $VM=get-azurevm -ServiceName "MyService" -name "VMName"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureVM], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.GetAzureVMCommand

**Comment by janegilring** [comment]
I am seeing the same with Get-AzureVm on version 4.3.1

**Comment by KarlGW** [comment]
Any improvments yet? This issue still persists.

**Comment by cormacpayne** [comment]
It appears that this is fixed with the following PR: https://github.com/Azure/azure-powershell/pull/4679

We anticipate this PR fixes most issues people are seeing with the `AutoMapperMappingException`. We are looking to get this PR into the October release that goes out this Tuesday (October 10th).

**Comment by cormacpayne** [comment]
The fix for this has been merged and will be available in the November release of Azure PowerShell (version 5.0.0 - set to release November 8th).
