### ISSUE TITLE
AzureRM.Profile.Netcore\Add-AzureRmAccount does not work with PSCredential objects

### ISSUE THREAD

**Issue by janegilring** [Azure/azure-powershell#4386]
### Cmdlet(s)
Add-AzureRmAccount

### PowerShell Version
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.4
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### Module Version
AzureRM.Profile.Netcore 0.9.1

### OS Version
10.0.15063.483

### Description
The Add-AzureRmAccount cmdlet throws an error when trying to authenticate using a PSCredential object:
_Add-AzureRmAccount : accessing_ws_metadata_exchange_failed: Accessing WS metadata exchange failed:  Response status code does not indicate success: 406 (NotAcceptable)._

### Debug Output
DEBUG: 19.58.42 - AddAzureRMAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob',
ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/Common/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'Common', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri:
urn:ietf:wg:oauth:2.0:oob
Add-AzureRmAccount : accessing_ws_metadata_exchange_failed: Accessing WS metadata exchange failed:  Response status code does not indicate success: 406 (NotAcceptable).
At line:1 char:1
+ Add-AzureRmAccount -Credential $cred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

DEBUG: 19.58.43 - AddAzureRMAccountCommand end processing.
DEBUG: 19.58.43 - AddAzureRMAccountCommand end processing.

### Script/Steps for Reproduction
$cred = Get-Credential
Add-AzureRmAccount -Credential $cred

**Comment by markcowl** [comment]
@janegilring What kind of credential are you using?  You cannot use a PSCredential for live id login, it must be a work school account that does not require MFA.

If you think this is the case, please execute the cmdlet with ```$DebugPreference="Continue"```  and let us know the result.

**Comment by markcowl** [comment]
Looks liek this is an issue with the credential type (live id).  If you see this issue using an OrgId credential, please open a new issue, and include the debugging output of login using ```$DebugPreference="Continue"```
