### ISSUE TITLE
Azurestack - AzureStackAdmin module fails with Null reference when user has not done Login-AzureRmEnvironment

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#4388]
### Cmdlet(s)
cmdlets in AzureRM.AzureStackAdmin module

### Module Version
1.2.10 AzureRM Version, 0.10.9 version of AzureRm.AzureStackAdmin

### Description
Object reference exception when the user is not logged in with Login-AzureRmEnvironment

### Script/Steps for Reproduction
  Call Get-AzsLocation commandlet will fail if not logged in with an object reference not set to instance of an object instead of a message such as "please log in"

**Comment by cormacpayne** [comment]
@bganapa Hey Bala, do you know if this issue has been resolved?

**Comment by deathly809** [comment]
@cormacpayne We have deprecated this module and suggest that users move to using the AzureStack module now.

**Comment by bganapa** [comment]
This module AzureRm.AzureStackAdmin has been deprecated now , closing this
