### ISSUE TITLE
Solution/Projects will not load in Visual Studio after clean build of project.

### ISSUE THREAD

**Issue by andrew-buckley** [Azure/azure-powershell#4392]
### Cmdlet(s)
N/A

### PowerShell Version
5.1.14393.1532

### Module Version
N/A

### OS Version
10.0.14393.1532

### Description
After following all of the environment/build steps [here](https://github.com/Azure/azure-powershell/wiki/Azure-Powershell-Developer-Guide) I still cannot open the sln in Visual Studio 2015 Update 3 to develop/debug.

When trying to individually load a project after none of them load initially I get the attached error.
![capture](https://user-images.githubusercontent.com/14007220/28806778-b0b003fc-7626-11e7-9585-dd1a8b65805b.PNG)

### Debug Output
N/A

**Comment by cormacpayne** [comment]
Resolved the issue offline with @andrew-buckley 

Users are unable to open the .NET Core projects using VS 2015 Update 3; they must use VS 2017.
