### ISSUE TITLE
KeyVault: handling of Certificate types is inconsistent with that of other KV entities

### ISSUE THREAD

**Issue by dragav** [Azure/azure-powershell#4393]
### Cmdlet(s)
*-AzureKeyVaultCertificate*

### PowerShell Version
all
### OS Version
any

### Description
The type handling of certificates in the KV PSh client is inconsistent with the other entity types, as well as inconsistent within itself. For keys and secrets, the wrapper of the data plane client consumes KV models
and returns PSH models - i.e. type translation occurs in the wrapper. For certificates, individual objects are passed through as KV models on to the caller (which is the cmdlet implementation, and which performs the type translation), but collections (I.e. 'list' results) are translated in the wrapper - i.e. the wrapper returns CertificateBundle (a KV type) but also CertificateIdentityItem (a PSh type). 

Changing this constitutes a breaking change in the IKVDataServiceClient iface, which, although unlikely to be used outside of this code, is, however, public.

### Debug Output
n/a

**Comment by maddieclayton** [comment]
@dragav Do you want me to fix this in the upcoming breaking change PR? Should be a very simple fix.

**Comment by maddieclayton** [comment]
Done
