### ISSUE TITLE
Need support of AzureRM.KeyVault module for powershell core

### ISSUE THREAD

**Issue by danybenjamin** [Azure/azure-powershell#4403]
### Cmdlet(s)
Get-AzureKeyVaultSecret

### PowerShell Version
Powershell Core

### OS Version
Mac OS 

### Description
It's a very tedious process to find all keys in key vault via azure portal. 
Working on a mac, the option of using `Get-AzureKeyVaultSecret` cmdlet is not possible right now.

**Comment by cormacpayne** [comment]
@danybenjamin thanks for the interest! Although we do not have a set timeline, we are interested in adding a few more modules currently available in AzureRM to the AzureRM.Netcore package, including KeyVault. We will re-open this issue, or point it at a new issue that we create, when we have more information about when this work will be done. Please let us know if you have any questions!

**Comment by santoshghimire** [comment]
@cormacpayne Any update on this?

**Comment by cormacpayne** [comment]
@santoshghimire Hey Santosh, converting the KeyVault modules to .NET Core is on our radar and we're looking to get it done by the end of the year. @twitchax will be able to shed more light on our timeline.

**Comment by twitchax** [comment]
@cormacpayne says it best.  We are currently getting to a place where Netcore build/test is "easy"; then, we will start to move modules over one-by-one.  KeyVault is at the top of our list.

**Comment by cormacpayne** [comment]
AzureRM.Netcore 0.10.0 was released and includes the AzureRM.KeyVault.Netcore module. You can find it here: https://github.com/Azure/azure-powershell/releases/tag/v0.10.0-nc-February2018
