### ISSUE TITLE
Could not load type 'System.Management.Automation.PSSnapIn' during Import-Module

### ISSUE THREAD

**Issue by joelanders** [Azure/azure-powershell#4407]
### Cmdlet(s)
`Import-Module Azure`

### PowerShell Version
```
Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.4
OS                             Linux 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30)
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module Version
```
Script     4.2.1      Azure                               {Get-AzureAutomationCertificate, Get-AzureAutomationConnection, New-AzureAutomationConnection, Remove-AzureAutomationConnection...}
```

### OS Version
I don't see `BuildVersion`, but `$PSVersionTable` is above. I'm running Ubuntu 16.06 in a docker container on Debian 9.

### Description
Trying to install `Azure` and `AzureRM` on Ubuntu 16.04 and having a rough time. Found a couple of case-sensitivity-related things before getting to this error.

In `/opt/microsoft/powershell/6.0.0-beta.4/Modules/Azure/4.2.1/Azure.psd1`, I changed `Microsoft.WindowsAzure.Commands.Websites.Types.ps1xml` to have `WebSites` with a capital `S` and `Microsoft.WindowsAzure.Commands.StorSimple.Types.ps1xml` to have `types` with a lowercase `t`. (not sure if those are the correct fixes)

### Debug Output
>Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

That didn't seem to give any more info (I'm new to PowerShell), but I ran it with `-Verbose` and here's the last bit:
```
VERBOSE: Importing cmdlet 'Import-AzurePublishSettingsFile'.
VERBOSE: Importing cmdlet 'Select-AzureSubscription'.
VERBOSE: Importing cmdlet 'Set-AzureSubscription'.
VERBOSE: Loading module from path '/opt/microsoft/powershell/6.0.0-beta.4/Modules/Azure/4.2.1/Sql/Microsoft.WindowsAzure.Commands.SqlDatabase.dll'.
Import-Module : Could not load type 'System.Management.Automation.PSSnapIn' from assembly 'System.Management.Automation, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
At line:1 char:1
+ Import-Module Azure -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

### Script/Steps for Reproduction
So, a weird thing I did before I got here that *might* be related (who knows): the `Install-Module` cmdlet wasn't installing this module [like in this issue](https://github.com/PowerShell/PowerShell/issues/3986). So I chdired into a dir in my `$env:PSModulePath` and did a `Save-Module Azure -Path .`. After that, I did `Import-Module Azure` and ran into the above problem(s).

**Comment by markcowl** [comment]
```Azure``` is the old module for RDFE cmdlets, it is not supported on net core.  For the netcore modules, please use this: https://www.powershellgallery.com/packages/AzureRM.Netcore/0.9.1
