### ISSUE TITLE
Add tests for paging functionality in DSC cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#4410]
Need to add tests for paging functionality in DSC cmdlets added in PR https://github.com/Azure/azure-powershell/pull/4338

**Comment by cormacpayne** [comment]
@balukambala has this issue been addressed?

**Comment by maddieclayton** [comment]
@vrdmr Can you ping the correct person on your team regarding this test debt issue?  It has been open since August.

**Comment by nitinbps** [comment]
Does not meet the customer bar hence closing it.
