### ISSUE TITLE
No Provider for Microsoft.DataFactory/datafactories/pipelines

### ISSUE THREAD

**Issue by jamieo-ms** [Azure/azure-powershell#4413]
### Module Version
Manifest   3.0.0      AzureRM.DataFactories               {Get-AzureRmDataFactory, Get-AzureRmDataFactoryActivityWindow, Get-AzureRmDataFactoryDataset, Ge...
Manifest   3.0.0      AzureRM.HDInsight                   {Add-AzureRmHDInsightClusterIdentity, Add-AzureRmHDInsightComponentVersion, Add-AzureRmHDInsight...
Manifest   3.0.0      AzureRM.Profile                     {Add-AzureRmAccount, Add-AzureRmEnvironment, Disable-AzureRmDataCollection, Enable-AzureRmDataCo...
Manifest   4.0.0      AzureRM.Resources                   {Export-AzureRmResourceGroup, Find-AzureRmResource, Find-AzureRmResourceGroup, Get-AzureRmADAppC...
Manifest   3.0.0      AzureRM.Websites                    {Edit-AzureRmWebAppBackupConfiguration, Get-AzureRmAppServicePlan, Get-AzureRmAppServicePlanMetr...
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                 
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}          
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                          
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}    

### Description

There does not appear to be a provider for data factory pipelines.  There's a REST API for pipelines and the cmdlet `Get-AzureRmDataFactoryPipeline` (which doesn't return the full JSON schema for the activities), but no provider for `Get-AzureRmResource`.

### Script/Steps for Reproduction

PS C:\WINDOWS\system32> (Get-AzureRmResourceProvider -ProviderNamespace Microsoft.DataFactory -Pre).ResourceTypes.ResourceTypeName
dataFactories
factories
factories/integrationRuntimes
dataFactories/diagnosticSettings
dataFactories/metricDefinitions
checkDataFactoryNameAvailability
checkAzureDataFactoryNameAvailability
dataFactorySchema
operations

**Comment by markcowl** [comment]
@jackmagic313 Can you answer about which resource provider cover DataFactories iN ARM?

**Comment by maddieclayton** [comment]
@hvermis Can you answer this customer question?

**Comment by hvermis** [comment]
Only factories and datafactories are ARM resources in Azure Data Factory provider. The other resource types are getting listed because of the operations on them need special mappings from service side. However, you shouldn't need anything other than factories or datafactories.
RBAC is supported on all actions listed by operations API from ADF. Please let me know if you have more questions.
