### ISSUE TITLE
Azure Powershell 4.2.1 - New-AzureRmDisk : 'Location' cannot be null

### ISSUE THREAD

**Issue by mariaesteban** [Azure/azure-powershell#4424]
**Cmdlet(s)**
New-AzureRMDisk

**PowerShell Version**
5.1.15063.483

**Module Version**
AzureRM.Compute 3.2.1
AzureRM 4.2.1

**OS Version**
Windows 10

**Description**
New-AzureRmDisk : 'Location' cannot be null. error when creating managed disk that has been previously removed

**Debug Output**
$diskConfig = New-AzureRmDiskConfig -AccountType $storageType -Location $AzureLocation -CreateOption Empty -DiskSizeGB 128 -Debug
$dataDisk1 = New-AzureRmDisk -DiskName $dataDiskName -Disk $diskConfig -ResourceGroupName $rgName -Debug
$vm = Get-AzureRmVM -Name $vmName -ResourceGroupName $rgName 
$vm = Add-AzureRmVMDataDisk $vm -Name $dataDiskName -CreateOption Attach -ManagedDiskId $dataDisk1.Id -Lun 0
Update-AzureRmVM -VM $vm -ResourceGroupName $rgName

DEBUG: 2:15:45 PM - NewAzureRmDiskConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 2:15:46 PM - using account id 'mariae@microsoft.com'...
DEBUG: 2:15:47 PM - NewAzureRmDiskConfigCommand end processing.
DEBUG: 2:15:47 PM - NewAzureRmDiskConfigCommand end processing.
DEBUG: 2:15:47 PM - NewAzureRmDisk begin processing with ParameterSet 'DefaultParameter'.
DEBUG: 2:15:48 PM - using account id 'mariae@microsoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'mariae@microsoft.com', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/08/2017 12:15:49: e6aa4ab0-720e-4137-9236-154df652f665 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (1 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/08/2017 12:15:49:  - TokenCache: Deserialized 1 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 08/08/2017 12:15:49: e6aa4ab0-720e-4137-9236-154df652f665 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/08/2017 12:15:49: e6aa4ab0-720e-4137-9236-154df652f665 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 08/08/2017 12:15:49: e6aa4ab0-720e-4137-9236-154df652f665 - TokenCache: 54.4545118833333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/08/2017 12:15:49: e6aa4ab0-720e-4137-9236-154df652f665 - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/08/2017 12:15:49: e6aa4ab0-720e-4137-9236-154df652f665 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: OkcFLzUfgswwDUR3fYvOs/PzY+20IFFCPDe//yaT7Cg=
	Refresh Token Hash: NbB7jhhO3g9z6xP7A25oqj4+aTtM7fv2D7ETfN5zLv0=
	Expiration Time: 08/08/2017 13:10:16 +00:00
	User Hash: +huQCILeCN0zTGBdSKTj9tjXBMZUqkOcQ/s3D5Gx7vQ=
	

New-AzureRmDisk : 'Location' cannot be null.
At line:2 char:14
+ ... dataDisk1 = New-AzureRmDisk -DiskName $dataDiskName -Disk $diskConfig ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmDisk], ValidationException
    + FullyQualifiedErrorId : Microsoft.Rest.ValidationException,Microsoft.Azure.Commands.Compute.Automation.NewAzureRmDisk
 
Update-AzureRmVM : The entity was not found.
ErrorCode: NotFound
ErrorMessage: The entity was not found.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 202e6368-f64c-4994-8fb3-a346c303832a
At line:5 char:1
+ Update-AzureRmVM -VM $vm -ResourceGroupName $rgName
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Update-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand

**Script/Steps for Reproduction**

**ADD DATA DISK**
$rgName = 'mariaeds33'
$vmName = 'mariaeds33'
$AzureLocation = 'West Europe' 
$dataDiskName = ('mariaeds32_datadisk')

$diskConfig = New-AzureRmDiskConfig -AccountType $storageType -Location $AzureLocation -CreateOption Empty -DiskSizeGB 128 -Debug
$dataDisk1 = New-AzureRmDisk -DiskName $dataDiskName -Disk $diskConfig -ResourceGroupName $rgName -Debug
$vm = Get-AzureRmVM -Name $vmName -ResourceGroupName $rgName 
$vm = Add-AzureRmVMDataDisk $vm -Name $dataDiskName -CreateOption Attach -ManagedDiskId $dataDisk1.Id -Lun 0
Update-AzureRmVM -VM $vm -ResourceGroupName $rgName

**REMOVE DATA DISK**
$VirtualMachine = Get-AzureRmVM -ResourceGroupName $rgName -Name $vmName 
Remove-AzureRmVMDataDisk -VM $VirtualMachine -Name $dataDiskName
Update-AzureRmVM -ResourceGroupName $rgName -VM $VirtualMachine
Remove-AzureRmDisk -ResourceGroupName $rgName -DiskName $dataDiskName

**ADD DATA DISK AGAIN**
$diskConfig = New-AzureRmDiskConfig -AccountType $storageType -Location $AzureLocation -CreateOption Empty -DiskSizeGB 128 -Debug
$dataDisk1 = New-AzureRmDisk -DiskName $dataDiskName -Disk $diskConfig -ResourceGroupName $rgName -Debug
$vm = Get-AzureRmVM -Name $vmName -ResourceGroupName $rgName 
$vm = Add-AzureRmVMDataDisk $vm -Name $dataDiskName -CreateOption Attach -ManagedDiskId $dataDisk1.Id -Lun 0
Update-AzureRmVM -VM $vm -ResourceGroupName $rgName

**Comment by mbenko** [comment]
I am seeing something similar. Calling New-AzureRmDisk with a given -Disk diskconfig works the first time, but after calling Add-AzureRmVMDataDisk subsequent calls to New-AzureRmDisk fail with the message that -Location cannot be null.  

   New-AzureRmDisk : 'Location' cannot be null.

**Comment by cormacpayne** [comment]
Closing this issue as we will be tracking the status of this bug from issue https://github.com/Azure/azure-powershell/issues/4419
