### ISSUE TITLE
DataLake: Add test(s) for KeyVault regression

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#4428]
### Description

Add test(s) to cover the scenarios mentioned in issue https://github.com/Azure/azure-powershell/issues/4323 and fixed in PR https://github.com/Azure/azure-powershell/pull/4371

**Comment by cormacpayne** [comment]
@ro-joowan Hey Joo Wan, has this issue been addressed?

**Comment by ro-joowan** [comment]
@cormacpayne Not yet :( it's on my TODO list -- just swamped at the moment

**Comment by cormacpayne** [comment]
@rahuldutta90 Hey Rahul, would you mind taking a look at this issue?

**Comment by rahuldutta90** [comment]
Assigning it to @lewu-msft since he owns the management plane of the powershell.

**Comment by Alex-wdy** [comment]
Data lake Analytics has been replaced by Synapse, close this issue. Already confirmed with PM. Data lake Analytics  will be deprecated.
