### ISSUE TITLE
[SideBySide]: Move Stack tests into preview branch

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#4435]
### Description

- [ ] Move over tests and have them build into ```src\Stack\<Config>```
  - [ ] Update test map to include stack packages

### Cost: 10

**Comment by bganapa** [comment]
Working on it

**Comment by cormacpayne** [comment]
I believe this has been completed. @bganapa let me know if that is not the case

**Comment by bganapa** [comment]
Yes this is done. Thanks
