### ISSUE TITLE
[SideBySide]: Create side-by-side MSI build for AzureStack

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#4436]
### Description
 - [x] Create Side-by-Side VS msi build for stack
   - [x] Include new StackSetup folder for MSI artifacts
   - [x] Update wxi generator to include extra parameter (BuildProfile as above) to generate Stack MSI from ```src\Stack\<config>```

### Cost: 4

**Comment by cormacpayne** [comment]
I believe this has been resolved.
