### ISSUE TITLE
Get-AzureRmSchedulerJobCollection: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ironicLemon** [Azure/azure-powershell#4445]
### Cmdlet(s)
Get-AzureRmSchedulerJobCollection 

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1.15063.483

### Module Version
CommandType     Name                                               Version    Source                                            
-----------     ----                                               -------    ------                                            
Cmdlet          Get-AzureRmSchedulerJobCollection                  0.15.2     AzureRM.Scheduler  

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.15063.483

### Description
Trying to call Get-AzureRmSchedulerJobCollection results in Get-AzureRmSchedulerJobCollection: Object reference not set to an instance of an object.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxx/resourceGroups/infrastructureqa/providers/Microso
ft.Scheduler/jobCollections/apurva?api-version=2016-03-01

Headers:
x-ms-client-request-id        : c6a62b75-3375-4ba2-b072-beff3bdf499d
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-burst-remaining-scheduler-reads: 499
x-ms-request-id               : 7552a712-e134-4610-8a31-bb53e8827cb4
x-ms-ratelimit-remaining-subscription-reads: 14992
x-ms-correlation-request-id   : 5bada8d8-0d45-4118-aee6-f6bb350afbc7
x-ms-routing-request-id       : UKSOUTH:20170809T152251Z:5bada8d8-0d45-4118-aee6-f6bb350afbc7
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Wed, 09 Aug 2017 15:22:51 GMT
Server                        : Microsoft-IIS/8.5
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxxxx/resourceGroups/infrastructureqa/providers/Microsoft.Scheduler/jobCol
lections/apurva",
  "type": "Microsoft.Scheduler/jobCollections",
  "name": "apurva",
  "location": "UK South",
  "properties": {
    "sku": {
      "name": "Standard"
    },
    "state": "Enabled"
  }
}

Get-AzureRmSchedulerJobCollection : Object reference not set to an instance of an object.
At C:\temp\Switch-Schedulers.ps1:10 char:22
+ ... ollection = Get-AzureRmSchedulerJobCollection -ResourceGroupName $res ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmSchedulerJobCollection], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Scheduler.Cmdlets.GetAzureSchedulerJobCollectionCommand
 
DEBUG: 4:22:52 PM - GetAzureSchedulerJobCollectionCommand end processing.
DEBUG: 4:22:52 PM - GetAzureSchedulerJobCollectionCommand end processing.
DEBUG: 4:22:52 PM - GetAzureSchedulerJobCollectionCommand begin processing with ParameterSet '__AllParameterSets'.

### Script/Steps for Reproduction
$resourceGroup = "infrastructureqa"
$resources = Find-AzureRmResource -ResourceGroupNameEquals $resourceGroup -ResourceType Microsoft.Scheduler/jobcollections

$resources | foreach {
    $jobCollectionName = $_.Name
    $jobCollection = Get-AzureRmSchedulerJobCollection -ResourceGroupName $resourceGroup -JobCollectionName $jobCollectionName
}

**Comment by cormacpayne** [comment]
@Sumanan Hey Sumanan, would you mind taking a look at this issue?

**Comment by ironicLemon** [comment]
Are there any plans to investigate this? The issue is impacting us.

**Comment by nboettcher** [comment]
@Sumanan I'm running into this same issue. Simply trying to do the 'Get-AzureRmSchedulerJobCollection' command against my subscription from the Azure Portal PowerShell shell. Can you please provide assistance?

**Comment by cormacpayne** [comment]
Closing as the Scheduler module no longer is shipping with `Az`.
