### ISSUE TITLE
Error getting virtualNetworkConnection resource for an App Service Plan

### ISSUE THREAD

**Issue by mclark1129** [Azure/azure-powershell#4470]
### Cmdlet(s)
Get-AzureRmResource

### PowerShell Version
5      1      14393  1198    

### Module Version
4.2.1 

### OS Version
10     0      14393  1198  

### Description
I am unable to use `Get-AzureRmResource` in order to retrieve a virtual network connection for an App Service Plan (not App Service).  The resulting error is:

```
Get-AzureRmResource : Unable to cast object of type 'Newtonsoft.Json.Linq.JArray' to type 'Newtonsoft.Json.Linq.JObject'.
At line:13 char:22
+ $currentVnetConfig = Get-AzureRmResource `
+                      ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResource], InvalidCastException
    + FullyQualifiedErrorId : Unable to cast object of type 'Newtonsoft.Json.Linq.JArray' to type 'Newtonsoft.Json.Linq.JObject'.,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementat 
   ion.GetAzureResourceCmdlet
 ```

### Debug Output
There is a fair amount of sensitive information in the debug, and nothing entirely significant.  Can send privately if absolutely necessary.

### Script/Steps for Reproduction
```
$webAppName = "mywebapp" 
$webAppResourceGroupName = "myrg"

#Get the Web App's vnet connection as an object 
$currentVnetConfig = Get-AzureRmResource `
    -ResourceName "$($webAppName)/$($currentVnetName)" `
    -ResourceType "Microsoft.Web/serverfarms/virtualNetworkConnections" `
    -ApiVersion 2016-09-01 `
    -ExpandProperties `
    -ResourceGroupName $webAppResourceGroupName;
```

**Comment by cormacpayne** [comment]
@TianoMS Hey Tian, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
I believe this issue is resolved in the latest version of `AzureRM`. Please re-open this issue if that is not the case.
