### ISSUE TITLE
Get-AzureRMDataFactoryRun result not retrieving detail information (Properties dictionary)

### ISSUE THREAD

**Issue by rmarteleto** [Azure/azure-powershell#4475]
### Cmdlet(s)
Get-AzureRMDataFactoryRun

### PowerShell Version                                                                                                                 
PSVersion                      5.1.14393.1480              

### Module Version
AzureRM.DataFactories  3.2.1      

### OS Version
BuildVersion                   10.0.14393.1480      

### Description
The PSDataSliceRun "Properties" property as a result of Get-AzureRMDataFactoryRun call is empty, when there should data in there. When I try the c# equivalent using DataFactoryManagementClient class and drill down to DataSliceRuns, I am able to see additional information such as "data read", "data written", etc, in the Properties of DataSliceRun.

### Debug Output
Body:
{
  "value": [
    {
      "id": "d66c2d35-0d54-40e3-a3b7-92ec5324b92e_636383484000000000_636383520000000000_dataset",
      "errorMessage": null,
      "dataArtifactId": "85af2924-655d-4b8b-9f4c-bf3147a6bd2f",
      "tableName": "mytable",
      "pipelineId": "f4378dcd-4ea5-4e4d-810f-6a09a255f4e6",
      "pipelineName": "mypipeline",
      "activityId": "92ae0778-035c-54f1-8ab3-f312b9df561b",
      "activityName": "Copy",
      "computeClusterName": null,
      "status": "Succeeded",
      "processingStartTime": "2017-08-15T00:01:24.131805Z",
      "processingEndTime": "2017-08-15T00:08:53.1828843Z",
      "batchTime": "2017-08-15T00:00:00Z",
      "percentComplete": 100,
      "dataSliceStart": "2017-08-14T23:00:00Z",
      "dataSliceEnd": "2017-08-15T00:00:00Z",
      "timestamp": "2017-08-15T00:01:24.131805Z",
      "retryAttempt": 0,
      "type": "Copy",
      "hasLogs": false,
      "activityRunId": "00000000-0000-0000-0000-000000000000",
      "properties": {},
      "executionEvents": null,
      "inputRunRecordReferences": null,
      "outputRunRecordReferences": null,
      "activityInputProperties": {}
    }
  ]
}

### Script/Steps for Reproduction
1) create a functioning factory pipeline 
2) create time slices
3) allow pipeline activity to run
4) in the "activity run details" pane, there should be a "Details" area with "Data Read" , "Data Written", "Data Volume", etc. This information, when using C#, is available in the Properties of DataSliceRun, but not available when using Powershell command.

Get-AzureRMDataFactoryRun -DataFactoryName $factoryName -DatasetName $datasetName -ResourceGroupName $resourceGroup -StartDateTime $sliceStartTime

**Comment by cormacpayne** [comment]
@jackmagic313 Hey Jack, would you mind taking a look at this issue?

**Comment by rmarteleto** [comment]
Adding a little bit more of information here. It seems that the "List" extension method doesn't retrieve Properties, but "Get" does. I am not sure it is a deficiency of by design at the API level: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactories.dataslicerunoperationsextensions?view=azuremgmtdatafactories-4.12.1

**Comment by hvermis** [comment]
@rmarteleto This is by design, if you need more detailed information you will need to use our Get- methods instead of List-
