### ISSUE TITLE
Need documentation for AzureRM.*.Netcore modules

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4479]
These modules have been released to the PowerShell Gallery with no documentation. Need to document Installation and Getting Started scenarios. For example, these modules cannot be installed side-by-side with AzureRM. This is a common scenario on Windows. 

This documentation is also needed for users of Mac and Linux. We are getting comments on the AzureRM documentation from people trying to use those modules on Mac or Linux. If we had docs for the Netcore modules we could refer readers to that.

**Comment by sdwheeler** [comment]
@twitchax is reviewing the draft I wrote at: https://github.com/sdwheeler/azure-docs-powershell/blob/sdw-macexp/azureps-cmdlets-docs/ResourceManager/docs-conceptual/install-azurermps-maclinux.md

**Comment by twitchax** [comment]
LGTM.

Only comment would be to add the supported modules information from here (https://hub.docker.com/r/azuresdk/azure-powershell-core/).

**Comment by sdwheeler** [comment]
https://github.com/Azure/azure-docs-powershell/pull/401

**Comment by sdwheeler** [comment]
Merged - closing issue.
