### ISSUE TITLE
[AzureRM.Netcore] a misleading error message when you are not logged in

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#4487]
I've installed AzureRM.Netcore in Bash Cloud Shell (I've previously installed PowerShell Core 6 beta 5).
If I run any AzureRM command before I log in to Azure I get the following error message:
```
PS > get-azurermresourcegroup
get-azurermresourcegroup : The Azure PowerShell session has not been properly initialized.  Please import the module and try again.
```

That error message is misleading and not very helpful, and doesn't provide a step to fix a problem.

**Comment by markcowl** [comment]
This should be resolved by Aaron's latest PR: https://github.com/Azure/azure-powershell/pull/4879

**Comment by markcowl** [comment]
Closed as this was checked in.  Please reopen if you see a recurrence after the netcore release (week of 12/11)

**Comment by stuartleeks** [comment]
Is there a NetCore release with this in yet? Last NetCore release I can see is 0.9.1 from July

**Comment by cormacpayne** [comment]
AzureRM.Netcore 0.10.0 has been released and can be found here: https://github.com/Azure/azure-powershell/releases/tag/v0.10.0-nc-February2018
