### ISSUE TITLE
DocumentDb Support - Happy to contribute if no-one else working on it

### ISSUE THREAD

**Issue by nickheppleston** [Azure/azure-powershell#449]
I have a personal requirement to script a DocumentDb deployment and I'm interested to know whether anyone is already working on support for DocumentDb within this project? If not, I'll be happy to contribute.

**Comment by ryancrawcour** [comment]
Thanks for raising this. We can help with scripts to deploy the DocumentDB Account using Azure Resource Manager. 

After that, creating Database and Collections etc. is not automatable through Azure Resource Manager, yet.

If you want to automatically provision Database & Collections you would need to call out to our REST API to do this.

**Comment by matt-gibbs** [comment]
Closing this out. @nickheppleston we would welcome the contribution.

**Comment by ryancrawcour** [comment]
Absolutely. @nickheppleston if you would like to contact me on ryancraw at microsoft dot com we can sync up and perhaps divide & conquer
