### ISSUE TITLE
Get-AzureRMAutomationCredential throw error "Automation account not found" when providing a Asset name that does not exist in the account.

### ISSUE THREAD

**Issue by JakobGSvendsen** [Azure/azure-powershell#4496]
### PowerShell Version
PSVersion                      5.1.14393.1198

### Module Version
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   2.1.0      AzureRM.Automation     

### OS Version
BuildVersion                   10.0.14393.1198

### Description
Get-AzureRMAutomationCredential
Using a credential asset name that does not exist, it gives the error "automation account not found"

### Debug Output
[DBG]: [DBG]: PS C:\Users\JGS\OneDrive\Git\Repos\AzureAutomationImportExport> Get-AzureRMAutomationCredential -Name 'Office 365 Admin Accounts' -ResourceGroupNa
14:25:29 - GetAzureAutomationCredential begin processing with ParameterSet 'ByName'.
14:25:29 - using account id 'jakob@runbook.guru'...
[Common.Authentication]: Authenticating using Account: 'jakob@runbook.guru', environment: 'AzureCloud', tenant: 'ba61f14a-6f38-49ac-bb4c-26281ae25fc5'
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
08/22/2017 12:25:29:  - TokenCache: Deserialized 3 items to token cache.

[Common.Authentication]: Authenticating using configuration values: Domain: 'ba61f14a-6f38-49ac-bb4c-26281ae25fc5', Endpoint: 'https://login.microsoftonline.co
m/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/',
ValidateAuthrity: 'True'
[Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/ba61f14a-6f38-49ac-bb4c-26281ae25fc5/', CorrelationId:
 '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
[Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'ba61f14a-6f38-49ac-bb4c-26281ae25fc5', AdEndpoint: 'https://login.microsoftonlin
e.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
08/22/2017 12:25:29: 61dafc25-c2fe-4279-ba3f-8891e544cfaa - AcquireTokenHandlerBase: === Token Acquisition started:
        Authority: https://login.microsoftonline.com/ba61f14a-6f38-49ac-bb4c-26281ae25fc5/
        Resource: https://management.core.windows.net/
        ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
        CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (3 items)
        Authentication Target: User

Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
08/22/2017 12:25:29: 61dafc25-c2fe-4279-ba3f-8891e544cfaa - TokenCache: Looking up cache for a token...

Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
08/22/2017 12:25:29: 61dafc25-c2fe-4279-ba3f-8891e544cfaa - TokenCache: An item matching the requested resource was found in the cache

Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
08/22/2017 12:25:29: 61dafc25-c2fe-4279-ba3f-8891e544cfaa - TokenCache: 53.4441906983333 minutes left until token in cache expires

Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
08/22/2017 12:25:29: 61dafc25-c2fe-4279-ba3f-8891e544cfaa - TokenCache: A matching item (access token or refresh token or both) was found in the cache

Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
08/22/2017 12:25:29: 61dafc25-c2fe-4279-ba3f-8891e544cfaa - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
        Access Token Hash: FK29XBErt4SbeAx/nDWKe1PPjPnDhQ1A1cuF29OtaEM=
        Refresh Token Hash: 5oD597PoUv9yRxdOry1tgzo3mIIyIh4eNzVJ2dDE5lQ=
        Expiration Time: 08/22/2017 13:18:56 +00:00
        User Hash: m7qxTQ+Zo4DzEwB7QJTHI3eFIInrmjYKw1FwouTAtXE=

Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
08/22/2017 12:25:29:  - TokenCache: Serializing token cache with 3 items.

[Common.Authentication]: Received token with LoginType 'LiveId', Tenant: 'ba61f14a-6f38-49ac-bb4c-26281ae25fc5', UserId: 'jakob@runbook.guru'
[Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '08/22/2017 13:18:56 +00:00', MultipleResource? 'True', Tenant: 'ba61f14a-6f38-49ac-bb4c-2
6281ae25fc5', UserId: 'jakob@runbook.guru'
[Common.Authentication]: User info for token DisplayId: 'jakob@runbook.guru', Name: Jakob Svendsen, IdProvider: 'https://sts.windows.net/ba61f14a-6f38-49ac-bb4
c-26281ae25fc5/', Uid: '2c1bffd6-4129-4683-9bfa-7edee2d245e8'
[Common.Authentication]: Checking token expiration, token expires '08/22/2017 13:18:56 +00:00' Comparing to '08/22/2017 12:25:29 +00:00' With threshold '00:05:
00', calculated time until token expiry: '00:53:26.6494639'
============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/7fa4f2ea-77cd-4629-8fb0-42988a97b934/resourceGroups/OMS-RG/providers/Microsoft.Automation/automationAccounts/Automat
ion/credentials/Office 365 Admin Accounts?api-version=2015-10-31

Headers:
Accept                        : application/json
x-ms-version                  : 2014-06-01

Body:

============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-request-id               : 6cd6269a-e718-4620-9766-c70915aac7ec
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 14986
x-ms-correlation-request-id   : bfa6ec93-dd37-444d-b5b4-e93a2974e020
x-ms-routing-request-id       : WESTEUROPE:20170822T122530Z:bfa6ec93-dd37-444d-b5b4-e93a2974e020
Cache-Control                 : no-cache
Date                          : Tue, 22 Aug 2017 12:25:29 GMT
Server                        : Microsoft-IIS/8.5
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "code": "NotFound",
  "message": "Credential not found."
}

Get-AzureRMAutomationCredential : The Automation account was not found.
At line:1 char:1
+ Get-AzureRMAutomationCredential -Name 'Office 365 Admin Accounts' -Re ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmAutomationCredential], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationCredential

AzureQoSEvent: CommandName - Get-AzureRmAutomationCredential; IsSuccess - False; Duration - 00:00:00.6273655; Exception - System.ArgumentException: The Automat
ion account was not found. ---> Hyak.Common.CloudException: NotFound: Credential not found.
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Azure.Management.Automation.CredentialOperationsExtensions.Get(ICredentialOperations operations, String resourceGroupName, String automationAcc
ount, String credentialName)
   at Microsoft.Azure.Commands.Automation.Common.AutomationClient.GetCredential(String resourceGroupName, String automationAccountName, String name)
   at Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationCredential.AutomationProcessRecord()
   at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
Finish sending metric.
14:25:31 - GetAzureAutomationCredential end processing.
14:25:31 - GetAzureAutomationCredential end processing.
[DBG]: [DBG]: PS C:\Users\JGS\OneDrive\Git\Repos\AzureAutomationImportExport>

### Script/Steps for Reproduction
Asset exists: Office 365 Admin Account
Asset does not exist: Office 365 Admin Accounts

[DBG]: [DBG]: PS C:\Users\JGS\OneDrive\Git\Repos\AzureAutomationImportExport> Get-AzureRMAutomationCredential -Name 'Office 365 Admin Accounts' -ResourceGroupNa
**Get-AzureRMAutomationCredential : The Automation account was not found.**
At line:1 char:1
+ Get-AzureRMAutomationCredential -Name 'Office 365 Admin Accounts' -Re ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmAutomationCredential], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationCredential

[DBG]: [DBG]: PS C:\Users\JGS\OneDrive\Git\Repos\AzureAutomationImportExport> Get-AzureRMAutomationCredential -Name 'Office 365 Admin Account' -ResourceGroupNam
e 'OMS-RG' -AutomationAccountName 'Automation'

UserName              : jakob@runbook.guru
ResourceGroupName     : OMS-RG
AutomationAccountName : Automation
Name                  : Office 365 Admin Account
CreationTime          : 24-04-2017 14:10:00 +02:00
LastModifiedTime      : 28-04-2017 11:53:07 +02:00
Description           :

**Comment by sphibbs** [comment]
@JakobGSvendsen resolveazurermerror cmdlet will show you more details about the error. 
@vrdmr can you take a look at this.

**Comment by vrdmr** [comment]
Hi @JakobGSvendsen, The real issue, as you point out in the title is that the credential was not found and its evident with the `"message": "Credential not found."`. We have take up this task with and will try to get it in the next release. The issue has to do with better handling of error from our end. The "The Automation account was not found." is just the final fallback message.

**Comment by andyw248** [comment]
Triaged: No repro with Az cmdlet. Closing.
