### ISSUE TITLE
Unable to use DataLake stuff on Linux

### ISSUE THREAD

**Issue by flikka** [Azure/azure-powershell#4507]
### Cmdlet(s)
Install-Module

### PowerShell Version
PSVersion 6.0.0-beta                                                                               
PSEdition Core                                                                                     
GitCommitId v6.0.0-beta.5                                                                            
OS Linux 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017                      
Platform Unix

### Description
I've been told over at the github.com/powershell group to use AzureRM.NetCore. I am however in need for the DataLakeExport functions. The only related modules I can find is the 

> AzureRM.DataLakeStore

When I try to Install-Module this, it just doesn't turn up. Is there a NetCore alternative?

**Comment by sphibbs** [comment]
Currently we do not have support for Datalake on PS Core. You can use the generic resource cmdlets in azurerm.resources.netcore https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/?view=azurermps-4.3.1#resources
