### ISSUE TITLE
Get-AzureRmApiManagementUser - Parameter set name 'Find users' is not supported

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4510]
### Cmdlet(s)
Get-AzureRmApiManagementUser

### Description
Reported by a user via LiveFyre:

> When I use this command with just the context and email address, I get an error saying "Get AzureRmApiManagementUser : Parameter set name 'Find users' is not supported."  Any idea why?

Reviewing the source code it looks like this is by design but the docs indicate this should work. We need to fix the code or change the documentation.

```csharp
    public class GetAzureApiManagementUser : AzureApiManagementCmdletBase
    {
        private const string GetAll = "Get all users";
        private const string GetById = "Get user by ID";
        private const string FindBy = "Find users";

... 
// skipped lines

...

        public override void ExecuteApiManagementCmdlet()
        {
            if (ParameterSetName.Equals(GetAll))
            {
                var users = Client.UsersList(Context, null, null, null, null, null);
                WriteObject(users, true);
            }
            else if (ParameterSetName.Equals(GetById))
            {
                var user = Client.UserById(Context, UserId);
                WriteObject(user);
            }
            else
            {
                throw new InvalidOperationException(string.Format("Parameter set name '{0}' is not supported.", ParameterSetName));
            }
        }
...
```

**Comment by cormacpayne** [comment]
@solankisamir Hey Samir, would you mind taking a look at this issue?

**Comment by durai89** [comment]
Do we have any fix for this issue? I am facing the same, unable to fetch user details by email Id.

**Comment by cormacpayne** [comment]
@solankisamir ping

**Comment by solankisamir** [comment]
@cormacpayne yes I am aware of the issue.

**Comment by CodeStoneK** [comment]
I am trying this command to get users in a group and see the same error. Any ETA on the fix?

`$members = Get-AzureRmApiManagementUser -Context $ApimContext -GroupId $groupId`

**Comment by solankisamir** [comment]
Fix for the issue should be available with https://github.com/Azure/azure-powershell/milestone/31
