### ISSUE TITLE
Telemetry Adjustments

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#4517]
### Cmdlet(s)
All of them!

### PowerShell Version
N/A.

### Module Version
N/A.

### OS Version
N/A.

### Description
Azure PowerShell should make changes to its telemetry:
1. The `name` field is currently set to the name of the cmdlet.  The `name` field should be set to "cmdletInvocation", and the name of the cmdlet should be moved to `customDimensions.Command`.
2. The version of PowerShell should be logged in `customDimensions.PowerShellVersion`.
3. The version of Azure PowerShell should be logged in `customDimensions.Version`.

**Comment by markcowl** [comment]
Fixed.
