### ISSUE TITLE
ARM: api-version parameter in Get-AzureResource cmdlet should hit RP api version, instead of ARM resources api version

### ISSUE THREAD

**Issue by vivsriaus** [Azure/azure-powershell#452]
Per David,

For this call:
Get-AzureResource -ResourceGroupName Default-Web-JapanEast -ResourceType Microsoft.Web/sites -OutputObjectFormat New -ApiVersion 2015-04-01

Digging some more, the issue seems to be that it’s not making an RP call, but is instead hitting the CSM cache!

/subscriptions/468360f0-c632-478a-b32d-a4fdf1e07cfc/resourceGroups/Default-Web-JapanEast/resources?$filter=resourceType+EQ+'Microsoft.Web/sites'&api-version=2015-01-01

**Comment by ravbhatnagar** [comment]
PLease re-activate if this is still an issue.
