### ISSUE TITLE
AddAzureRMAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'

### ISSUE THREAD

**Issue by TechnologyAnimal** [Azure/azure-powershell#4524]
### Cmdlet(s)
Add-AzureRmAccount
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
6.0.0-beta
### Module Version
0.9.1
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
Darwin 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
### Description
Cannot use Add-LoginRmAccount to login.  Only using this because of known issue with this cmdlet failing with service principals.
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
DEBUG: 10:48:24 PM - AddAzureRMAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '31ac43fb-8ade-4ebf-a0f6-447f1dc087a5', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/******/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '*****', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '******', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
Add-AzureRmAccount : password_required_for_managed_user: Password is required for managed user
At /Users/*****/posh/misc/Deploy-ServicesPlatform.ps1:27 char:1
+ Add-AzureRmAccount -TenantId $TenantId -SubscriptionId $SubscriptionI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

DEBUG: 10:48:25 PM - AddAzureRMAccountCommand end processing.
DEBUG: 10:48:25 PM - AddAzureRMAccountCommand end processing.
### Script/Steps for Reproduction
Use Add-AzureRmAccount with a valid tenantid, subscriptionid, and passing in a PSCredential object.
Add-AzureRmAccount -TenantId $TenantId -SubscriptionId $SubscriptionId -Credential $Credential

**Comment by cormacpayne** [comment]
@TechnologyAnimal currently device authentication is the only supported form of login for the .NET Core modules. We are working with the ADAL team to support more forms of login in future releases.

**Comment by mcowart123** [comment]
Is there any word on when this is going to be supported? As of now it's pretty useless for automation scripting if you have to do an interactive login.

**Comment by markcowl** [comment]
@mcowart123 For automation, the recommendation is either to use context persistence with device login (, or to use ServicePrincipal login

**Comment by markcowl** [comment]
Closing, as interactive login is not supported in Core
