### ISSUE TITLE
Support querying resources across multiple subscriptions

### ISSUE THREAD

**Issue by gregjhogan** [Azure/azure-powershell#4527]
I tried Get-AzureRmResource, but something seems to be wrong with the ODataQuery parameter

If you run this:
```ps1
Get-AzureRmResource -ResourceId '/resources' -ODataQuery ("`$filter=subscriptionId eq 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' or subscriptionId eq 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'") -Debug
```

It builds a URL that looks like this (notice $filter was removed):
```
https://management.azure.com/resources?subscriptionId eq 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'or subscriptionId eq 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'&api-version=2015-01-01
```

and you get this response:
```json
{
  "error": {
    "code": "MissingSubscriptionFilter",
    "message": "The query string does not contain a 'SubscriptionId' filter. Filter: '<null>'"
  }
}
```

Looping through and running Select-AzureRmSubscription doesn't seem ideal.

Maybe you could add the ability to pass multiple subscription IDs into Find-AzureRmResource?

**Comment by cormacpayne** [comment]
@ravbhatnagar @TianoMS would you mind taking a look at this issue?

**Comment by gregjhogan** [comment]
To add a little more context, here is what I would like to be able to do:

I get a request to perform an action on a VM and the requester only knows the name.  I want to automate the action that needs to be taken, but the VM could be in any one of 32 subscriptions.  The script will take the VM name as a parameter, and it is painfully slow to enumerate all the subscriptions using Select-AzureRmSubscription.

Thanks!

**Comment by cormacpayne** [comment]
This can now be done by using the `-DefaultProfile` parameter in all cmdlets to run the cmdlet under a specific context.
