### ISSUE TITLE
Missing AzureStorageContainer, Get-AzureStorageShare cmdlets on .NetCore

### ISSUE THREAD

**Issue by jianyunt** [Azure/azure-powershell#4536]
### Cmdlet(s)
Get-AzureStorageContainer, Get-AzureStorageShare... do not exist on PowerShell core yet.

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### Module Version
Manifest 0.9.1 AzureRM.Netcore

### OS Version
PSVersion 6.0.0-beta
PSEdition Core
GitCommitId v6.0.0-beta.5
OS Microsoft Windows 10.0.14393
Platform Win32NT
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
WSManStackVersion 3.0
### Script/Steps for Reproduction
``` PowerShell
PS E:\> gcm Get-AzureStorageContainer
gcm : The term 'Get-AzureStorageContainer' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ gcm Get-AzureStorageContainer
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureStorageContainer:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
```

**Comment by cormacpayne** [comment]
@jianyunt we currently do not support the cmdlets from the `Azure.Storage` module in the `AzureRM.Netcore` module, but we plan on adding a bulk of the existing modules to `AzureRM.Netcore` in the future. Placing this issue in our backlog for future reference.

**Comment by markcowl** [comment]
Closing as duplicate you can track progress at #3746
