### ISSUE TITLE
Start-AzureRmVM -name param should not be mandatory

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4542]
### Cmdlet(s)
Start-AzureRmVM

### Module Version
Current

### Description

Feedback from customer via LiveFyre:
> Why is a VM name needed if the ID of the VM is specified (e.g., Start-AzureRmVM -Id $vm.Id)? 
> Also, an -Asynchronous option would be great!

Seems like a fair question. The Id should be enough to uniquely identify the VM. I reviewed the source. Part of the issue is that the parameter set definitions are split between SetAzureVMCommand.cs and VirtualMachineActionBaseCmdlet.cs. 

**SetAzureVMCommand.cs**
```csharp
        [Parameter(
           Mandatory = true,
           Position = 1,
           ValueFromPipelineByPropertyName = true,
           HelpMessage = "The virtual machine name.")]
        [ValidateNotNullOrEmpty]
        public string Name { get; set; }
```
**VirtualMachineActionBaseCmdlet.cs**
```csharp
        [Parameter(
           Mandatory = true,
           Position = 0,
           ParameterSetName = ResourceGroupNameParameterSet,
           ValueFromPipelineByPropertyName = true,
           HelpMessage = "The resource group name.")]
        [ValidateNotNullOrEmpty]
        public string ResourceGroupName { get; set; }

        [Parameter(
           Mandatory = true,
           Position = 0,
           ParameterSetName = IdParameterSet,
           ValueFromPipelineByPropertyName = true,
           HelpMessage = "The resource group name.")]
        [ValidateNotNullOrEmpty]
        public string Id { get; set; }
```
Note also that the HelpMessage for the **Id** parameter is incorrect. This should be the Id of the VM.

Also, regarding the request for -Asynchronous switch, I think this cmdlet is asynchronous but that is not documented. The reference needs to describe the asynchronous behavior.

**Comment by cormacpayne** [comment]
@hyonholee Hey Hyonho, would you mind taking a look at this issue? It seems like the `Id` parameter is being used solely to get the resource group of the VM. If we could make another parameter set that has just the `Id` and have the code grab both the resource group and the name of the VM, then that would resolve this customer's issue. It seems like a reasonable ask since we are moving to a model of passing a `ResourceId` around cmdlets. Let me know what you think.

**Comment by sdwheeler** [comment]
@hyonholee @cormacpayne So the Id is for the resource group and not the VM? That is not what I would expect. What about supporting a `Get-AzureRmVM | Start-AzureRMVM` scenario? Does that work? I would think that if you have the Id of the VM already, you could start that VM.

**Comment by 4c74356b41** [comment]
same problem with stop-azurermvm. any solution. should be fairly easy (just not for me, not a c# guy. can barely understand the code).

**Comment by cormacpayne** [comment]
@hyonholee ping

**Comment by huangpf** [comment]
@hyonholee I think this should be fixed, and the fix seems to be overriding the ```Name``` parameter's set, so that it won't be required in the ```IdParameterSet```.

**Comment by huangpf** [comment]
@cormacpayne @praries880 (are you Pary?)
Do you have a label that we can use to tag the issues that we should plan to fix?

**Comment by maddieclayton** [comment]
Fixed.
