### ISSUE TITLE
New-AzureRelayNamespace incorrect parameter name - NamespaceName

### ISSUE THREAD

**Issue by zakramer** [Azure/azure-powershell#4543]
### Cmdlet(s)
New-AzureRelayNamespace

### PowerShell Version
PSVersion                      5.1.15063.502

### Module Version
Manifest   0.1.0      AzureRM.Relay

### OS Version
BuildVersion                   10.0.15063.502

### Description
Commandlet documentation in PS and on the web clearly state that the parameter should be NamespaceName but the actual parameter is Name:

https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/Relay/Commands.Relay/Cmdlets/Namespace/NewAzureRelayNamespace.cs

https://docs.microsoft.com/en-us/powershell/module/azurerm.relay/new-azurermrelaynamespace?view=azurermps-4.3.1&viewFallbackFrom=azurermps-4.2.0

### Debug Output
PS C:\Users\zakramer> New-AzureRmRelayNamespace -ResourceGroup govhackfest33 -NamespaceName zakramerSB22 -Location "USGov Virginia"
New-AzureRmRelayNamespace : A parameter cannot be found that matches parameter name 'NamespaceName'.
At line:1 char:56
+ ... eRmRelayNamespace -ResourceGroup govhackfest33 -NamespaceName zakrame ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureRmRelayNamespace], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.Relay.Commands.Namespace.NewAzureRelayNamespace

### Script/Steps for Reproduction
Use New-AzureRelayNamespace with the -NamespaceName parameter as documented when doing get-help New-AzureRelaynamespace:

**Comment by cormacpayne** [comment]
@v-Ajnava would you mind taking a look at this? It looks like the markdown help wasn't updated after making some changes in the last release.

**Comment by cormacpayne** [comment]
@v-Ajnava Hey Ajit, would you mind taking a look at this issue?

**Comment by v-Ajnava** [comment]
This should be fixed now with latest release.
