### ISSUE TITLE
New-AzureRmWebAppSSLBinding Azure Automation compatibility

### ISSUE THREAD

**Issue by oryagel** [Azure/azure-powershell#4544]
### Cmdlet(s)
New-AzureRmWebAppSSLBinding

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.0

### Module Version
4.3.1

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.10105.0 

### Description
We try to use `New-AzureRmWebAppSSLBinding` in Azure Automation. Since the module expects a path to a certificate file, we can't use it in Azure Automation. Azure Automation can store the certificate for us and then we can reference the certificate object in Azure Automation runbook. The module needs to support certificate object in addition to certificate file in order to be compatible with Azure Automation.

**Comment by cormacpayne** [comment]
@twitchax we should have a discussion with Azure Automation about handling certificate types

**Comment by twitchax** [comment]
Added @eamonoreilly so we can discuss at our sync.

**Comment by markcowl** [comment]
@Nking92 Would you guys consider having a parameter set that takes X509Certifcate2 as a type

**Comment by eamonoreilly** [comment]
This can be accomplished in the following ways:

1.  Import a pfx certificate into the Automation service and mark as exportable. (You could name this "WebAppCertificate")

2. Create a secure variable in the Automation service to hold your password (You could call this "WebAppPassword")

3. Run the below PowerShell code from a runbook in the Automation service

```
$WebAppResourceGroup = "ContosoWebApp"
$WebAppName = "mycontosowebapp"
$Hostname = "www.contoso.com"
$Password = Get-AutomationVariable -Name "WebAppPassword"
$WebCert = Get-AutomationCertificate -Name "WebAppCertificate"  

# location to store temporary certificate in the Automation service host
$CertPath = Join-Path $env:temp  "WebAppCertificate.pfx"
   
# Save the certificate
$Cert = $WebCert.Export("pfx",$Password)
Set-Content -Value $Cert -Path $CertPath -Force -Encoding Byte | Write-Verbose 

# Authentiate to Azure
$ServicePrincipalConnection = Get-AutomationConnection -Name "AzureRunAsConnection"
Add-AzureRmAccount `
    -ServicePrincipal `
    -TenantId $ServicePrincipalConnection.TenantId `
    -ApplicationId $ServicePrincipalConnection.ApplicationId `
    -CertificateThumbprint $ServicePrincipalConnection.CertificateThumbprint | Write-Verbose

Select-AzureRmSubscription -SubscriptionId $ServicePrincipalConnection.SubscriptionID | Write-Verbose

# Add certificate to web application
New-AzureRmWebAppSSLBinding -ResourceGroupName $WebAppResourceGroup -WebAppName $WebAppName `
                            -CertificateFilePath $CertPath -CertificatePassword $Password -Name $Hostname

```

**Comment by eamonoreilly** [comment]
Closing this issue with the above resolution. Please reopen if this does not work for you.
Thanks,
Eamon
