### ISSUE TITLE
AzureRM.Resources missing Output Documentation

### ISSUE THREAD

**Issue by Injac** [Azure/azure-powershell#4545]
Hi,

looks like there is no source available for the output classes that are returned. Each CMDLet has a namespace for the output, but no link to the actual member documentation:

Sample:

https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/get-azurermadgroup?view=azurermps-4.3.1

Namespace:

System.Collections.Generic.List`1[Microsoft.Azure.Graph.RBAC.Version1_6.ActiveDirectory.PSADGroup]

But no documentation for the PSADGroup class.

**Comment by MiYanni** [comment]
Closing this in favor of: https://github.com/Azure/azure-powershell/issues/5777
