### ISSUE TITLE
Set-AzureRMResource for Microsoft.Insights/alertrules not working & has criptic Error messages 

### ISSUE THREAD

**Issue by Jagadt** [Azure/azure-powershell#4546]
### Description
When testing out the Set-AzureRMResource cmdlet and trying to make changes to different resources, I ran into problems when trying to change Microsoft.Insights/alertrules

### Cmdlet(s)

$propertyobject = @{'properties' = @{
'actions' = @{
'properties' = @{
sysid =123} # my custom attribute already set using ARM template
}
}
}
Set-AzureRmResource -PropertyObject $property object -ResourceGroupName BlockChain_PoCRG540324 -ResourceType microsoft.insights/alertrules -ResourceName "coewebapprequestalert" -ApiVersion 2016-03-01 -Force

### PowerShell Version

PSVersion                      5.1.14393.0

### Error

The following error is received
Set-AzureRmResource : The pipeline has been stopped.
At line:1 char:1
+ Set-AzureRmResource -PropertyObject $actions -ResourceGroupName Block ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmResource], PipelineStoppedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet
 
Set-AzureRmResource : {"code":"BadRequest","message":"The condition is missing."}
At line:1 char:1
+ Set-AzureRmResource -PropertyObject $actions -ResourceGroupName Block ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet
 
### Script/Steps for Reproduction
Refer https://github.com/Azure/azure-powershell/issues/1586

**Comment by cormacpayne** [comment]
@gucalder Hey Guillermo, would you mind taking a look at this issue?

**Comment by maddieclayton** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/issues/1586, and will ping.
