### ISSUE TITLE
Need documentation for cmdlet output types

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4552]
### Description
This is a LiveFyre comment posted to the Get-AzureRmAutomationSchedule cmdlet reference.

> Would it be possible to add a link   to the output object of this command? (This suggestion is for all
> of the   Azure commands). It would really be helpful.

We have had several customers ask for this information in different ways. In general I have referred them to the related .NET class but those don't always match exactly with the return types wrapped by the PowerShell provider.

**Comment by twitchax** [comment]
I think this may just be a matter of building a docxml for the Azure PowerShell class libraries.  We can have @dend consume those libraries with the docxml.

@markcowl, do the nugey packages for the gallery contain the docxml?

**Comment by dend** [comment]
The process is a bit different for the PowerShell API Browser (https://docs.microsoft.com/powershell/modules). @sankethka can help with the proper onboarding steps.

**Comment by markcowl** [comment]
Closing for now until we figure this out for the .Net library
