### ISSUE TITLE
What order are events returned from Get-AzureRmLog?

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4553]
### Cmdlet(s)
Get-AzureRmLog

### Description
Is the result set always ordered by newest event first? This appears to be the case. Is that sometime that can be counted upon

**Comment by maddieclayton** [comment]
@gucalder Ping

**Comment by sdwheeler** [comment]
In general, events are returned in newest first order. However, the order is dependent on the order in which the event provider was able to write the events to the event log. The event providers try to write events in chronological order but there is no 100% guarantee.
