### ISSUE TITLE
Does Set-AzureRmSqlDatabaseAuditingPolicy overwrite an existing policy?

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4554]
### Cmdlet(s)
Set-AzureRmSqlDatabaseAuditingPolicy

### Description
Documentation for [Set-AzureRmSqlDatabaseAuditingPolicy](https://docs.microsoft.com/en-us/powershell/module/azurerm.sql/set-azurermsqldatabaseauditingpolicy?view=azurermps-4.3.1) states:

> After the cmdlet runs successfully, auditing of the database is enabled. If the database used the policy
> of its server for auditing before you ran this cmdlet, auditing stops using that policy.

This is contrary to what is stated in the [Get started with SQL database auditing](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-auditing#subheading-8) article, where it says that both audit policies will apply.

What is the actual behavior?

**Comment by giladmit** [comment]
Note that Set-AzureRmSqlDatabaseAuditingPolicy is currently deprecated, and is being replaced by [Set-AzureRmSqlDatabaseAuditing](https://docs.microsoft.com/en-us/powershell/module/azurerm.sql/set-azurermsqldatabaseauditing).

The [Get started with SQL Database Auditing](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-auditing) article is aligned with the new cmdlet, and they both represent the up-to-date behavior.
