### ISSUE TITLE
New-AzureRmSchedulerHttpJob API haven't retry policy setting?

### ISSUE THREAD

**Issue by GuofuZhong** [Azure/azure-powershell#4555]
### PowerShell Version
PSVersion                      5.1.14393.1532
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1532
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### OS Version
WinServer 2016
### Description
I was just wondering why this API haven't retry policy settings.. I have to login the portal and setup the retry policy

**Comment by cormacpayne** [comment]
@Sumanan Hey Sumanan, would you mind taking a look at this issue?

**Comment by GuofuZhong** [comment]
@cormacpayne @sumanan do you have any update of it?

**Comment by cormacpayne** [comment]
@derek1ee Hey Derek, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
Closing as the Scheduler module no longer ships with `Az`.
