### ISSUE TITLE
Set-AzureRmNetworkSecurityGroup - Invalid Address Prefix

### ISSUE THREAD

**Issue by BrandonStiff** [Azure/azure-powershell#4557]
### Cmdlet(s)

Set-AzureRmNetworkSecurityGroup

### PowerShell Version

5.1.15063.502

### Module Version

ModuleType Version    Name
---------- -------    ----
Script     3.3.1      AzureRM.Automation
Script     3.3.1      AzureRM.Compute
Script     4.3.1      AzureRM.Network
Script     3.3.1      AzureRM.profile

### OS Version

10.0.15063.502

### Description

I cannot add a new Security rule using the Source Address CIDR Value:  50.206.209.68/27.  I can add it using the Web Portal.  In addition, if a rule with this CIDR exists, I get an error if I try and use PowerShell to add or remove any future rules.  Other CIDR values appear to work.  I get the following error:

```
Set-AzureRmNetworkSecurityGroup : Security rule /subscriptions/ccda225c-ddd0-4f69-b030-095bf89f3bf9/resourceGroups/dc-gitlab/providers/Microsoft.Network/networkSecurityGroups/az-g
itlab-p01-nsg/securityRules/Plex_RDP_50.206.209.68 has invalid Address prefix. Value provided: 50.206.209.68/27
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 'f3feda34-5da1-4ff3-a5f6-538fc4b9fe8e'
At line:113 char:16
+         $nsg | Set-AzureRmNetworkSecurityGroup | Out-Null
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmNetworkSecurityGroup], NetworkCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.SetAzureNetworkSecurityGroupCommand
```

### Debug Output

I have this captured, and can send it to someone if needed.  

### Script/Steps for Reproduction

Run the following:

```powershell
$nsg = Get-AzureRmNetworkSecurityGroup -ResourceGroupName "Resource Group Name here"
$nsg = $nsg | Add-AzureRmNetworkSecurityRuleConfig `
       -Name "RDP_50.206.209.68" `
       -Description "RDP Access" `
       -Protocol "TCP" `
       -Direction "INBOUND" `
       -Priority 1031 `
       -SourceAddressPrefix "50.206.209.68/27" `
       -SourcePortRange "*" `
       -DestinationAddressPrefix "*" `
       -DestinationPortRange 3389 `
       -Access Allow

$nsg | Set-AzureRmNetworkSecurityGroup 
```

**Comment by cormacpayne** [comment]
@BrandonStiff would you mind providing the debug output for this command? You can do so by setting `DebugPreference="Continue"` before executing the above script. You can also provide a more detailed error by running the `Resolve-AzureRmError` cmdlet after you see the failure.

@DeepakRajendranMsft would you mind taking a look at this issue?

**Comment by BrandonStiff** [comment]
I captured the debug output and have it ready.  I'd rather not publicly post it.  Where can I send it?
________________________________

**Comment by BrandonStiff** [comment]
I emailed the debug output directly to @DeepakRajendranMsft.  Let me know if you need anything else or if you need me to reproduce it again.

**Comment by BrandonStiff** [comment]
@DeepakRajendranMsft found the issue.  This was on my end.  The CIDR I was using was invalid.  It should have been:

50.206.209.64/27

I'm going to close this issue.  Thanks for the prompt response and sorry for the trouble!

**Comment by lichengshuang** [comment]
ipdrress  you can use Internet 

        #offile-22-3022,302,Tcp,22:3022:100-200,1.202.17.138/32:14.43.240.0/24

        for info in $(cat $iptablesrules | egrep -v '^#|^$');do
            rulename=$(echo $info | awk -F, '{print $1}')
            priority=$(echo $info | awk -F, '{print $2}')

            if [[ "$(echo $info | awk -F, '{print $3}')" == "ALL" ]];then
                ###协议默认是*,既然如此 那么就为空
                protocols=""
            else
                protocol=$(echo $info | awk -F, '{print $3}')
                protocols="--protocol $protocol"
            fi

            if [[ "$(echo $info | awk -F, '{print $5}')" == "ALL" ]];then
                sourcesips='Internet'
            else
                sourcesips=$(echo $info | awk -F, '{print $5}' | sed 's/:/ /g') ###多端口用:隔开
            fi

            if [[ "$(echo $info | awk -F, '{print $4}')" == "ALL" ]];then
                az network nsg rule create \
                --subscription $subscriptionId \
                --name $rulename \
                --nsg-name $nsgname \
                --priority $priority \
                --resource-group $resourcegroup \
                --access Allow $protocols \
                --direction Inbound \
                --destination-port-ranges '*' \
                --source-address-prefixes $sourcesips

            else
                destports=$(echo $info | awk -F, '{print $4}' | sed 's/:/ /g') ###多端口用:隔开
                az network nsg rule create \
                --subscription $subscriptionId \
                --name $rulename \
                --nsg-name $nsgname \
                --priority $priority \
                --resource-group $resourcegroup \
                --access Allow $protocols \
                --direction Inbound \
                --destination-port-ranges $destports \
                --source-address-prefixes $sourcesips
            fi

        done
    }
