### ISSUE TITLE
Get-AzureWebsite : Requested value 'Isolated' was not found

### ISSUE THREAD

**Issue by pablojmp** [Azure/azure-powershell#4558]
### Cmdlet(s)
Get-AzureWebsite

### PowerShell Version
5.1.14409.1005

### OS Version
10.0.14409.1005

### Description
We are using powershell to automate app services deployment.
Until today this code used to work fine:
New-AzureRmWebApp -ResourceGroupName "Default-Web-SouthCentralUS" -Name ($appName + "-" + $dirTrailer) -Location "South Central US" -AppServicePlan $serverFarm
$website = Get-AzureWebsite -Name ($appName + "-" + $dirTrailer)

Currently the Get-AzureWebsite cmdlet is erroring with:
Get-AzureWebsite : Requested value 'Isolated' was not found.
We were using azure powershell version 3.0.0 but we're getting the same error after upgrading to 4.3.1.

**Comment by cormacpayne** [comment]
@pablojmp using a combination of RDFE and ARM cmdlets is not a supported way to manage resources. Is there a reason you would use `Get-AzureWebsite` over `Get-AzureRmWebApp`? Is there information you are getting from the RDFE cmdlet that you are not receiving from the ARM cmdlet? Also, would you mind providing the debug output from this cmdlet execution by setting `DebugPreference="Continue"` before running the above script?

**Comment by pablojmp** [comment]
We're getting the same information from both cmdlets. We are already testing with Get-AzureRmWebApp, but Get-AzureWebsite is used in several automatic deploys, so changing every occurrence could be burdensome.
After running:
`Get-AzureWebSite -Name "cadworx-master-3-3-0"`
we get the following log:
[debug_log.txt](https://github.com/Azure/azure-powershell/files/1288834/debug_log.txt)
(authentication lines removed)

**Comment by markcowl** [comment]
@pablojmp Unfortunately, it is not supported to mix RDFE and ARM cmdlets for AppServices.  Please update your scripts to use ARM.
