### ISSUE TITLE
Login-AzureRmAccount

### ISSUE THREAD

**Issue by ShilpiRachna** [Azure/azure-powershell#4561]
### Cmdlet(s)
Login-AzureRmAccount

### PowerShell Version
5.1.15063.502

### Module Version
AzureRM (4.3.1)

### OS Version
10.0.15063.502

### Description
We are using Login-AzureRmAccount -ServicePrincipal -CertificateThumbprint $certThumbprint -ApplicationId $applicationId  -TenantId $tenantId to login to Azure for our deployment.

After 1 hour, the connection times out. we are not able to login again in the same powershell session.

Is there a way to increase the timeout duration? Or,  a way to refresh connection token?

### Debug Output
[error]Get-AzureRmVirtualNetwork : Your Azure credentials have not been set up or have expired, please run 
Login-AzureRMAccount to set up your Azure credentials.
At C:\LR\Search\Services\Search\Modules\ElasticSearch\DeploymentV2\Utils\AzureRMNode.ps1:562 char:21
+ ...     $vnet = Get-AzureRmVirtualNetwork -Name $Config.RmConfig.VNet.Nam ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmVirtualNetwork], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkCommand

### Script/Steps for Reproduction

1. Login to Azure using Login-AzureRmAccount -ServicePrincipal -CertificateThumbprint $certThumbprint -ApplicationId $applicationId  -TenantId $tenantId 
2. Continue some operations for > 1 hour
3. Connection times out after 1 hour and we are not able to login again from the same session

**Comment by cormacpayne** [comment]
@ShilpiRachna would you mind providing the error that you are seeing when you try to login again from the same session? Providing the debug stream by setting `DebugPreference="Continue"` would also be very beneficial.

**Comment by ShilpiRachna** [comment]
Hi, I get an error "Keyset does not exist".

The debug stream:
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain:
'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', Endpoint: 'https://login.microsoftonline.com/', ClientId:
'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri:
'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 09/09/2017 05:55:38: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/
 Resource: https://management.core.windows.net/
 ClientId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (2 items)
 Authentication Target: Client

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 09/09/2017 05:55:38:  - TokenCache: Deserialized 2 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 09/09/2017 05:55:38: 0a81d2fc-e136-4386-9856-ee3f54743e9b - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 09/09/2017 05:55:38: 0a81d2fc-e136-4386-9856-ee3f54743e9b - TokenCache: No matching token was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Error: 4 :
DEBUG: 09/09/2017 05:55:38: 0a81d2fc-e136-4386-9856-ee3f54743e9b - <RunAsync>d__0:
System.Security.Cryptography.CryptographicException: Keyset does not exist

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean
randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean
useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.GetAsymmetricAlgorithm(String algorithm, Boolean
privateKey)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.SignWithCertificate(String message,
X509Certificate2 x509Certificate)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.JsonWebToken.Sign(ClientAssertionCertificate credential)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.RequestParameters.AddClientKey(ClientKey clientKey)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()

Confirm
Keyset does not exist

**Comment by markcowl** [comment]
@ShilpiRachna This error indicates that the certificate is not appropriate for AAD authentication.  Were you able to log in with this certificate initially?

**Comment by vancourse** [comment]
I am having a similar issue. I was able to login with the same certificate for a week before the Login-AzureRmAccount suddenly stopped working ( with the same exception as stated above ).

**Comment by markcowl** [comment]
@ShilpiRacha This is a very old version fo the cmdlets - cna you try updating and see if this fixes the issue?

@vancourse - I don't think this issue is similar to the one you are reporting.  Access tkens by default last for an hour, so Shilpi's issue is likely related to being unable to refresh the access token.  If your authentication lasted for a week, you were able to renwe the token - this could be an issue with the lifetime of your certificate, or is it possible that someone else updated the credentials in your service?
