### ISSUE TITLE
Get-AzureRmMetricDefinition and Service Fabric support

### ISSUE THREAD

**Issue by stofte** [Azure/azure-powershell#4566]
### Cmdlet(s)

Get-AzureRmMetricDefinition

### PowerShell Version
5.1.15063.502 

### OS Version
10.0.15063.502

### Description
Service Fabric support for Metric definitions (and thus usage alerts, I dont care about billing, just usage)

### Debug Output

I've snipped the relevant output (there's too much debug output in general that I feel good posting in a public forum, I can't figure out what, if anything, should be censored before posting here). 

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 00000000-0000-0000-0000-000000000000
x-ms-ratelimit-remaining-subscription-reads: 14807
x-ms-correlation-request-id   : REMOVED
x-ms-routing-request-id       : WESTEUROPE:20170908T100207Z:REMOVED
Cache-Control                 : no-cache
Date                          : Fri, 08 Sep 2017 10:02:06 GMT
Server                        : Microsoft-IIS/8.5

Body:
{
  "code": "ResourceNotSupported",
  "message": "Resource provider not supported: microsoft.servicefabric"
}
```

### Script/Steps for Reproduction

```
Get-AzureRmMetricDefinition -ResourceId "/subscriptions/REMOVED/resourceGroups/RKCloudProd/providers/Microsoft.ServiceFabric/clusters/REMOVED" -Verbose -Debug -DetailedOutput
```

Are there plans to implement this feature, or is the assumption that users will turn to the lower level Service Fabric components and utilize alerts on those? Eg the scaletset or load balancer?

**Comment by cormacpayne** [comment]
@gucalder Hey Guillermo, would you mind taking a look at this issue? If this should be assigned to the ServiceFabric team, please let us know.

**Comment by cormacpayne** [comment]
@gucalder ping

**Comment by KevinBlasko** [comment]
Service Fabric supports sending logs to Azure Monitor and can be used to collect and alert on performance counter data.  For information on how to configure this, see: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-oms-agent and https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-unified-log

If you would like to see Service Fabric integrate with Azure Monitor metrics or are interested in seeing more data collected generally, please add a request to the Service Fabric User Voice page: https://feedback.azure.com/forums/293901-service-fabric
