### ISSUE TITLE
Get-AzureRmsubscription results not passing to Set-AzureRmContext

### ISSUE THREAD

**Issue by bdanse** [Azure/azure-powershell#4568]
### Cmdlet(s)
Get-AzureRmSubscription

### PowerShell Version
 5.1.14409.1012

### Module Version
4.3.1

### OS Version
10.0.14409.1012

### Description
Working with multiple subscriptions in Azure I sometimes need to switch subscriptions. I was used to do this using Get-AzureRmsubscription | Out-gridview -Passthru | Select-Azurermsubscription. But with the last version of azure powershell I am unable to do this. 

Get-Azurermsubscription now results in subscription object where subscriptionId is only id. Which will not pass to Set-AzurermContext since that needs SubscriptionId. 

### Script/Steps for Reproduction
 Get-AzureRmsubscription | Out-gridview -Passthru | Select-Azurermsubscription

**Comment by bdanse** [comment]
I tested some more. Looks like its not SubscriptionId but SubscriptionName. 

`PS > Get-AzureRmSubscription | Out-GridView -PassThru | Set-AzureRmContext -Debug
DEBUG: 21:47:34 - SetAzureRMContextCommand begin processing with ParameterSet 'SubscriptionName'.`
Resulting in not selecting the correct subscription. 

`Get-AzureRmSubscription | Out-GridView -PassThru |  Select SubscriptionId | Set-AzureRmContext`
works though.

**Comment by cormacpayne** [comment]
@bdanse this should be fixed in the latest version of AzureRM (4.4.1). Please update to that version and let us know if you are still seeing this issue.
