### ISSUE TITLE
Calculated MD5 does not match existing property when using Start-AzureStorageBlobCopy

### ISSUE THREAD

**Issue by blackhill** [Azure/azure-powershell#4570]
### Cmdlet(s)
Start-AzureStorageBlobCopy

### PowerShell Version
5.1.15063.502

### OS Version
10.0.15063.502 

### Description
When copying a blob from one storage account to another with Start-AzureStorageBlobCopy, the calculated MD5 does not match existing property. Is this the expected behavior?

**Comment by blueww** [comment]
@blackhill, the ContentMD5 in the blob property might not match the blob content, it's just a property set by user. (only change a blob content, the ContentMD5 in the blob property won't change accordingly until user reset it).

And Start-AzureStorageBlobCopy will copy both blob content and blob properties. If the source blob content not match the blob contentMD5 in property, this can happen.  And Start-AzureStorageBlobCopy only start the copy, please make sure the copy finish with Get-AzureStorageBlobCopyState and then verify the blob content and MD5.

**Comment by blackhill** [comment]
Each time I use Start-AzureStorageBlobCopy I get an invalid MD5. 
As I am using the C# SDK to manipulate blobs, I can disable MD5 check with BlobRequestOptions. 
In order to have a valid MD5, I have to handle the copy manually with Get-AzureStorageBlobConten and Set-AzureStorageBlobContent.

**Comment by blueww** [comment]
@blackhill

Could you please give more details of your scenario and requirement? I still don't quite understand it.
1. What do you mean "I get an invalid MD5.", Do you mean PowerShell will report MD5 error , or the destination blob property ContentMD5 is not aligned with the source Blob property ContentMD5?
2. What do you mean by "But I want this MD5 validation." Do you want PowerShell help to handle the MD5 validation, or you validate it by your own code after the copy?

PowerShell cmdlet Start-AzureStorageBlobCopy  will start an server side Blob Copy. Azure Server will copy the Blob content and all properties, it will set same contentMD5 as source blob, but won't re-calculate the MD5.

**Comment by blueww** [comment]
Since no more responds from customer for the issue for a long time, close the issue.
@blackhill , feel free to reactive the issue if you still have any comments/questions for it.
