### ISSUE TITLE
remove AlloowGatewayTransit  in next major release.

### ISSUE THREAD

**Issue by takekazuomi** [Azure/azure-powershell#4572]
### Cmdlet(s)
Add-AzureRmVirtualNetworkPeering

### PowerShell Version
 5.1.15063.502

### Module Version
 4.3.1      AzureRM.Network

### OS Version
10.0.15063.502

### Description
Currently AlloowGatewayTransit is alias of AllowGatewayTransit.   Originally AlloowGatewayTransit was a typo, it was fixed in 3.1.0. 

https://github.com/Azure/azure-powershell/pull/2775

https://github.com/Azure/azure-powershell/blob/7adf75155d516e260e9de791907ab4e4a02b6ff8/src/ResourceManager/Network/ChangeLog.md#version-310

It should have been deleted when it made major releases. But It's 4.0 major release has passed. I think that it should be removed next major release. (5.x)

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft Hey Deepak, I am adding this issue to the next breaking change milestone.

**Comment by maddieclayton** [comment]
Closing, as this will be cleaned up with the rest of the Obsolete messages in the upcoming breaking change release.

**Comment by mitcht** [comment]
I'm using -AllowGatewayTransit (Spelled exactly thay way). 

The message appears now: WARNING: Parameter 'AllowGatewayTransit' is obsolete. Add-AzureRmVirtualNetworkPeering: -AlloowGatewayTransit will be removed in an upcoming breaking change release.  Please start using -
AllowGatewayTransit to avoid breaking scripts.

This doesn't even make sense.
