### ISSUE TITLE
Add more information about Suspend-AzureRMAutomationJob

### ISSUE THREAD

**Issue by blueelvis** [Azure/azure-powershell#4573]
### Cmdlet(s)
Suspend-AzureRMAutomationJob
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1.15063.502
### Module Version
3.3.1
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.15063.502
### Description
I think that some documentation needs to be added about this commandlet and the type of jobs which can be suspended using this. As of now, only Workflow based jobs can be suspended. This cannot suspend a job which is based on normal PowerShell script and fails.
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
Not required.
### Script/Steps for Reproduction
Not required.

**Comment by blueelvis** [comment]
I have created a commit for this in a fork over here - https://github.com/blueelvis/azure-powershell/commit/d2fc02053473cb1851e6ab1fd69f37ab44c80d39

Can I create a PR for this?

Also, I think that the Resume-AzureRMAutomationJob could have this explanation as well. What do you think?

**Comment by cormacpayne** [comment]
@blueelvis Hey Pranav, thanks for making these changes to your documentation! Feel free to create a PR whenever you find a change that needs to be made to our documentation (or if you find any bugs/issues in general). Just as an FYI, we won't be merging in PRs in the public repository for the next two weeks as we prepare for the Ignite release.

@vrdmr would you mind looking at the commit that Pranav provided and signing off on the change? If it looks good to you, we should open a PR in the private repository so the change gets into the next release.

**Comment by vrdmr** [comment]
@blueelvis Hey Pranav, Thanks for updating the documentation. Please feel free the create the PR and we'll review it to make sure it goes into next release.
