### ISSUE TITLE
'Get-AzureApplicationGatewayConfig' throws 'Root element is missing' error

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-powershell#458]
Used version: 0.9.2,  [msi installer](https://github.com/Azure/azure-powershell/releases/download/0.9.2-May2015/azure-powershell.0.9.2.msi)

Cmdlet: `Get-AzureApplicationGatewayConfig`

Mode: `ASM`

Output:

``` powershell
PS C:\> Get-AzureApplicationGateway -Name AppGwTest
VERBOSE: 11:57:01 AM - Begin Operation: Get-AzureApplicationGateway
VERBOSE: 11:57:08 AM - Completed Operation: Get-AzureApplicationGateway


Name          : AppGwTest
Description   :
VnetName      : VnetForAssociation
Subnets       : {Subnet-1}
InstanceCount : 2
GatewaySize   : Medium
State         : Stopped
VirtualIPs    : {}
DnsName       :

```

``` powershell
PS C:\> Get-AzureApplicationGatewayConfig -Name AppGwTest
VERBOSE: 11:57:40 AM - Begin Operation: Get-AzureApplicationGatewayConfig
Get-AzureApplicationGatewayConfig :  Root element is missing. 
At line:1 char:1
+ Get-AzureApplicationGatewayConfig -Name AppGwTest
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureApplicationGatewayConfig], XmlException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.Network.ApplicationGateway.GetApplicat
   ionGatewayConfigCommand
```

**Comment by kagamsft** [comment]
Looks like gateway configuration  has not been SET yet. Have you done SET configuration before issuing GET?

**Comment by romangromov** [comment]
@kagamsft no, I've not set configuration due to 'set-config' issue https://github.com/Azure/azure-powershell/issues/461

Anyway, could you please confirm getting `XmlException` for non-existing configuration instead of empty configuration (for example, `<ApplicationGatewayConfiguration/>`) is by design?

**Comment by kagamsft** [comment]
We treat GET configuration before SET as error scenario and throw exception.

**Comment by cormacpayne** [comment]
Closing this issue due to a lack of activity. Please feel free to re-open this issue if you are still having issues with `Get-AzureApplicationGatewayConfig`
