### ISSUE TITLE
Add timeout for ARM rest requests such as set-AzureRMResource

### ISSUE THREAD

**Issue by afengli** [Azure/azure-powershell#4580]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

5.1.14393.1480

### Module Version

4.3.1

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.14393.1480

### Description
In current ARM rest client design, there is no timeout
eg: https://github.com/Azure/azure-powershell/blob/bbe5ee957de07032bcf7f9062bba91cceee62565/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/RestClients/ResourceManagerRestClientBase.cs#L107

There are many situations where ARM operation can take time, even hours. EG this bug
https://github.com/Azure/azure-powershell/issues/4107

Adding a timeout will give the user a better control over the requests and their script logic.

use following logic in PerformOperationAsync to add timeout.

int timeout = 1000;
var task = SomeOperationAsync();
if (await Task.WhenAny(task, Task.Delay(timeout)) == task) {
    // task completed within timeout
} else { 
    // timeout logic
}

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

Set-AzureRmResource -ResourceId $resourceID -Tag $tags -Force -ErrorAction Stop | Out-Null

**Comment by afengli** [comment]
From debug, the call stack of wait is:

 # Call Site
00 Microsoft_Azure_Commands_ResourceManager_Cmdlets!Microsoft.Azure.Commands.ResourceManager.Cmdlets.RestClients.ResourceManagerRestClientBase.SendRequestAsync(System.Net.Http.HttpMethod, System.Uri, Newtonsoft.Json.Linq.JToken, System.Threading.CancellationToken)
01 Microsoft_Azure_Commands_ResourceManager_Cmdlets!Microsoft.Azure.Commands.ResourceManager.Cmdlets.RestClients.ResourceManagerRestClientBase+<PerformOperationAsync>d__4.MoveNext()
02 mscorlib_ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib]].Start[[System.__Canon, mscorlib]](System.__Canon ByRef)
03 Microsoft_Azure_Commands_ResourceManager_Cmdlets!Microsoft.Azure.Commands.ResourceManager.Cmdlets.RestClients.ResourceManagerRestClientBase.PerformOperationAsync(System.Net.Http.HttpMethod, System.Uri, Newtonsoft.Json.Linq.JToken, System.Threading.CancellationToken)
04 Microsoft_Azure_Commands_ResourceManager_Cmdlets!Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet+<>c__DisplayClass24_0.<OnProcessRecord>b__0()
05 Microsoft_WindowsAzure_Commands_Common!Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean, System.String, System.String, System.String, System.Action, System.Func`1<Boolean>)
06 Microsoft_Azure_Commands_ResourceManager_Common!Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.ConfirmAction(Boolean, System.String, System.String, System.String, System.Action)
07 Microsoft_Azure_Commands_ResourceManager_Cmdlets!Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet.OnProcessRecord()
08 Microsoft_Azure_Commands_ResourceManager_Cmdlets!Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
09 Microsoft_WindowsAzure_Commands_Common!Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()

**Comment by cormacpayne** [comment]
@afengli Hey Feng, as of AzureRM 4.4.0, you can now run our cmdlets as jobs, which will allow you to run these long processes as jobs in the background of a PowerShell session. For more information on running these cmdlets as jobs, please see [here](https://docs.microsoft.com/en-us/powershell/azure/context-persistence#running-azure-powershell-cmdlets-as-background-jobs).
