### ISSUE TITLE
Update ADAL Library

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#4585]
### Description

- [ ] Update Azure Authentication Library to use the latest 3.x version of ADAL
- [ ] Consume the new ADAL in Azure PowerShell
- [ ] Verify login scenarios
  - [ ] UPN + password
  - [ ] UPN with popup
  - [ ] SPN + cert
  - [ ] SPN + secret
  - [ ]  CSP scenarios
  - [ ] Verify across mooncake, BlackForest, Stack (adfs & aad)

### Cost: 8

**Comment by maddieclayton** [comment]
Will happen automatically when we convert to NetStandard.
