### ISSUE TITLE
'Get-AzureApplicationGatewayConfig' export to file throws 'Root element is missing'

### ISSUE THREAD

**Issue by romangromov** [Azure/azure-powershell#459]
Used version: 0.9.2,  [msi installer](https://github.com/Azure/azure-powershell/releases/download/0.9.2-May2015/azure-powershell.0.9.2.msi)

Cmdlet: `Get-AzureApplicationGatewayConfig -Name AppGwTest -ExportToFile "D:\config.xml"`

Mode: `ASM`

Output:
```powershell

PS C:\> Get-AzureApplicationGateway -Name AppGwTest
VERBOSE: 12:05:57 PM - Begin Operation: Get-AzureApplicationGateway
VERBOSE: 12:05:59 PM - Completed Operation: Get-AzureApplicationGateway


Name          : AppGwTest
Description   :
VnetName      : VnetForAssociation
Subnets       : {Subnet-1}
InstanceCount : 2
GatewaySize   : Medium
State         : Stopped
VirtualIPs    : {}
DnsName       :
```

```powershell
PS C:\> Get-AzureApplicationGatewayConfig -Name AppGwTest -ExportToFile "D:\config.xml"
VERBOSE: 12:06:12 PM - Begin Operation: Get-AzureApplicationGatewayConfig
Get-AzureApplicationGatewayConfig : Root element is missing.
At line:1 char:1
+ Get-AzureApplicationGatewayConfig -Name AppGwTest -ExportToFile "D:\config.xml"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureApplicationGatewayConfig], XmlException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.Network.ApplicationGateway.GetApplicat
   ionGatewayConfigCommand
```

**Comment by kagamsft** [comment]
Looks like gateway configuration has not been SET yet. Have you done SET configuration before issuing GET?

**Comment by romangromov** [comment]
@kagamsft no, I've not set configuration due to 'set-config' issue https://github.com/Azure/azure-powershell/issues/461

Anyway, could you please confirm getting `XmlException` for non-existing configuration instead of empty configuration (for example, <ApplicationGatewayConfiguration/>) is by design?

**Comment by kagamsft** [comment]
We treat GET configuration before SET as error scenario and throw exception.

**Comment by markjbrown** [comment]
Closing issue. If this is still an active issue please reopen.
