### ISSUE TITLE
Document common code

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#4592]
### Description
- [ ] Write description for each common code assembly and when it is appropriate to use it
- [ ] Write documentation for common code types and their intended usage
- [ ] Suggest common code pieces to remoive and refactor
- [ ] Propose changes to assembly naming for increased discoverability and consistency

### Cost: 10

**Comment by maddieclayton** [comment]
split into two issues: https://github.com/Azure/azure-powershell/issues/6142, https://github.com/Azure/azure-powershell/issues/6143
