### ISSUE TITLE
Normalize ClientRuntime and TestFramework versions for Tests

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#4593]
### Description

- [ ] Normalize versions of ClientRuntime, ClientRuntime.Azure, ClientRuntime.Azure.Authentication across test projects
- [ ] Work with feature teams to re-record any test failures caused by slight differences in the calling pattern

### Cost: 8

**Comment by MiYanni** [comment]
This will be resolved with ClientRuntime updates: https://github.com/Azure/azure-powershell/issues/5380

**Comment by cormacpayne** [comment]
This has been resolved with the [`Common.Dependencies.Test.targets`](https://github.com/Azure/azure-powershell/blob/preview/tools/Common.Dependencies.Test.targets) file.
