### ISSUE TITLE
[Nov Release] Update Cmdlets to use SecureString and PsCredentialType 

### ISSUE THREAD

**Issue by solankisamir** [Azure/azure-powershell#4595]
### Cmdlet(s)
- New-AzureRmApiManagementBackendProxy
- New-AzureRmApiManagementUser 
- Set-AzureRmApiManagementUser

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
Associated with https://github.com/Azure/azure-powershell/issues/4359

**Comment by maddieclayton** [comment]
Fixed
