### ISSUE TITLE
Update Get-AzureRmVMExtension to support returning all extensions for a VM

### ISSUE THREAD

**Issue by gregjhogan** [Azure/azure-powershell#4601]
Currently, Get-AzureRmVMExtension requires a resource group name, a VM name, and an extension name.  Sometimes you want to know if a particular extension is installed, and you have no idea what someone might have specified for a name.  If Get-AzureRmVMExtension supported returning all VM extensions for a VM (only specify a resource group name and VM name) this would be easy.

The work-around for now is to use Get-AzureRmResource in the mean-time:
```ps1
Get-AzureRmResource -ResourceId /subscriptions/{subscription-id}/resourceGroups/{resource-group-name}/providers/Microsoft.Compute/virtualMachines/{vm-name}/extensions
```

**Comment by cormacpayne** [comment]
@danielsollondon Hey Daniel, would you mind taking a look at this issue?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
