### ISSUE TITLE
Deprecate AzureRM.ServerManagement module

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#4608]
"Server Management Tools" service has been removed for a couple of months now.
Why do we still have AzureRM.ServerManagement module?

**Comment by cormacpayne** [comment]
@twitchax to confirm that this has been removed

**Comment by maddieclayton** [comment]
Task for 3/9: Deprecate module

**Comment by twitchax** [comment]
Confirm remove.

**Comment by maddieclayton** [comment]
Task for //Build: remove module from AzureRM

**Comment by maddieclayton** [comment]
Done
