### ISSUE TITLE
Stack - Azurestack specific subscription definition is not pipe-able to Select-AzureRmSubscription

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#4610]
New-AzsTenantSubscription cmdlet ouputs a subscription definition object that is different from azure subscription definition. 

New-AzsTenantSubscription resides in admin module and likely not often coupled with Select-AzureRmSubscription. This is low pri IMO

**Comment by cormacpayne** [comment]
@bganapa is this still an issue?

**Comment by bganapa** [comment]
I am closing this issue and I do not think there is a pressing need to fix this.
