### ISSUE TITLE
Get-AzureWebSite doesn't work when remote debugging with vs 2015 is enabled

### ISSUE THREAD

**Issue by lkempf** [Azure/azure-powershell#462]
```powershell
Get-AzureWebSite -name $websiteName
```
returns
```
Get-AzureWebsite : Requested value 'VS2015' was not found.
```
when remote debugging for visual studio 2015 is enabled.
```
"RemoteDebuggingEnabled": true,
"RemoteDebuggingVersion": "VS2015",
```

**Comment by NaveenGoli** [comment]
will look into this..

**Comment by NaveenGoli** [comment]
Did you use API to set VS2015? I dont see an option to set to VS2015 in both portals?

**Comment by FuUuUuUoO** [comment]
VS 2015 sets itself if you attach it for remote debugging
________________________________

**Comment by FuUuUuUoO** [comment]
Is there any progress on this? You can now select VS 2015 using the preview portal

**Comment by brandonmartinez** [comment]
Just ran into a similar issue today when trying to deploy from VSO. Found a workaround: [Resolve a "Requested value VS2015 was not found" Get-AzureWebsite Error in PowerShell](http://bmtn.us/1CC7NL8)

**Comment by FuUuUuUoO** [comment]
Since nobody wants to fix this I tracked it down to a bug in azure-sdk-for-net. It should be trivial to fix now. This issue can probably be closed now but I'd like to keep it open as long as this remains unfixed to avoid reposts.

**Comment by markcowl** [comment]
@NaveenGoli What's the progress on this?  Do you just need to add an option to the cmdlet, or make the value a string insstead of an enum?

**Comment by timfish** [comment]
I saw this issue when attempting to web deploy to Azure. I came across [this post] (http://www.brandonmartinez.com/2015/07/14/resolve-a-requested-value-vs2015-was-not-found-get-azurewebsite-error-in-powershell/) which reminded me that I'd enabled remote debugging with vs2015. Changing it back to 2012 fixed it.

**Comment by Bartthefish** [comment]
I just ran into this same issue with VS 2015 RTM and VS Online.
I followed the same steps in the 'workaround' and it resolved it. Obviously there is still a problem somewhere in the setting of the remote debugger to VS 2015

**Comment by ChristianRygg** [comment]
This also breaks VSO build using deployment to web site. This just fails without any indication why, as I describe here:

https://github.com/Microsoft/vso-agent-tasks/issues/526

**Comment by storafrid** [comment]
Fixing https://github.com/Azure/azure-sdk-for-net/issues/1255 should solve this so I've added a comment over there.

It could be fixed here as well by just hard-switching from unknown string values to `VS2015`, but I don't know if that's a good idea.

**Comment by sergsalo** [comment]
any progress on this?

**Comment by markcowl** [comment]
@lkempf  @sergsalo @storafrid There isn't any active development going on in the RDFE libraries or cmdlets for websites (though important bugfixes should still be happening).  Have you tried updating your scripts to using the ARM cmdlets?

**Comment by htuomola** [comment]
@markcowl as mentioned here several times, the VSTS "Azure Web App Deployment" task uses Get-AzureWebsite internally and fails the build because it fails to detect existing web app. It is of course possible to replace that one build task with custom Azure Powershell scripts but that shouldn't be necessary. Based on the bunch of github issues, it looks like everyone is just pointing at the other teams. As a developer, I don't really care whose fault it is but the end result is that powershell management and VSTS deployment are both broken now.

I'd assume think that retrieving the information of a properly configured website with Azure Powershell (Get-AzureWebsite) should be considered "important" or supported and as such this should be fixed too.

**Comment by sayedihashimi** [comment]
Adding @BradyGaster and @mohitsriv for visibility into this.

**Comment by markcowl** [comment]
RDFE fix was just checked in to dev branch,  wil go out with the next release.

**Comment by mxa0079** [comment]
@markcowl this should not be closed until it is available to customers/consumers. It makes it harder to find the issue if we run into it, and a feature is not done until it is in production ;)
