### ISSUE TITLE
Add cmdlets for VM runCommand action

### ISSUE THREAD

**Issue by gregjhogan** [Azure/azure-powershell#4630]
I find the [runCommand](https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/Compute/Commands.Compute/Generated/VirtualMachine/VirtualMachineRunCommandMethod.cs) action to be extremely useful, but there is no dedicated cmdlet for it.  Can you add cmdlets for it?

https://docs.microsoft.com/en-us/nodejs/api/azure-arm-compute/virtualmachines?view=azure-node-2.0.0#azure_arm_compute_VirtualMachines_runCommand

Here is the workaround until a new cmdlet is added:
```ps1
$parameters =
@{
    commandId = "RunShellScript"
    script = @("ls /")
}

Invoke-AzureRmResourceAction -ResourceId $resourceId -Action runCommand -Parameters $parameters -ApiVersion 2017-03-30 -Force
```

**Comment by cormacpayne** [comment]
@gregjhogan Hey Greg, these cmdlets will be available in the latest version of AzureRM (4.4.1). Please find the cmdlets there. Please re-open this issue if there is still missing functionality that you would like to see.
