### ISSUE TITLE
Rerecord test: TestVirtualNetworkGatewayP2SVpnProfile

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#4631]
### Description

This test was recorded with an older version of networ library.  Need to re-record with a newer version and unskip

**Comment by number213** [comment]
Re-recorded and un-skipped by this commit https://github.com/Azure/azure-powershell/commit/b746a9da4589f5b4600046aa76986fcd60208b95#diff-99938aeaa7750f6a350d002b6cb09333
