### ISSUE TITLE
Stack- Documentation alignement with azure doc process

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#4633]
Rightnow, Stack folder tree is not scanned for documentation changes. The doc may not be in the desired folder structure. Need investigation

**Comment by cormacpayne** [comment]
@bganapa is this still an issue?

**Comment by bganapa** [comment]
Yes.  We dont have the auto update of docs yet for stack folders

**Comment by bganapa** [comment]
CLosing this. This is not applicable as we move to Az in future
