### ISSUE TITLE
Remove-Azure​RmVMNetwork​Interface examples section is blank

### ISSUE THREAD

**Issue by rkyttle** [Azure/azure-powershell#4642]
https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/remove-azurermvmnetworkinterface

There is a section labeled examples, which is blank

**Comment by rkyttle** [comment]
In addition, the parameters listed in the documentation are not correct
The documentation lists VM and NetworkInterfaceIDs as input parameters

When I run this on my system, I am prompted to provide Name and ResourceGroupName instead

**Comment by maddieclayton** [comment]
@hyonholee @nibhat Can one of you add the example to this file?

@rkyttle I think the second issue you mention has been fixed, as I am now prompted for VM when I run the command.  Please let me know if this continues to be an issue for you.

**Comment by maddieclayton** [comment]
All help issues for Compute are captured here: https://github.com/Azure/azure-powershell/issues/7007 - closing this issue as dup as the second issue seems to have been resolved.
