### ISSUE TITLE
Start-AzureRmAutomationDscCompilationJob : Method not found

### ISSUE THREAD

**Issue by bdanse** [Azure/azure-powershell#4643]
### Cmdlet(s)
Start-AzureRmAutomationDscCompilationJob

### PowerShell Version
5.1.14409.1012 

### Module Version
4.3.1      Azure
3.3.1      AzureRM.Automation

### OS Version
10.0.14409.1012

### Description
Unable to start a compilationjob from powershell 

### Debug Output
Start-AzureRmAutomationDscCompilationJob : Method not found: 'Void Microsoft.Azure.Management.Automation.Models.DscCompilationJobCreateProperties.set_IncrementNodeConfigurationBuild(Boolean)'.
At line:1 char:22
+ ... onAccount | Start-AzureRmAutomationDscCompilationJob -ConfigurationNa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Start-AzureRmAutomationDscCompilationJob], MissingMethodException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.StartAzureAutomationDscCompilationJob
 
DEBUG: AzureQoSEvent: CommandName - Start-AzureRmAutomationDscCompilationJob; IsSuccess - False; Duration - 00:00:35.7292118; Exception - System.MissingMethodException: Method not found: 'Void Microsoft.Azure.Management.Automation.Models.DscCompilationJobCre
ateProperties.set_IncrementNodeConfigurationBuild(Boolean)'.
   at Microsoft.Azure.Commands.Automation.Common.AutomationClient.StartCompilationJob(String resourceGroupName, String automationAccountName, String configurationName, IDictionary parameters, IDictionary configurationData, Boolean incrementNodeConfigurationB
uild)
   at Microsoft.Azure.Commands.Automation.Cmdlet.StartAzureAutomationDscCompilationJob.AutomationProcessRecord()
   at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();

### Script/Steps for Reproduction
Start-AzureRmAutomationDscCompilationJob -ConfigurationName $configuration.Name -ConfigurationData $ConfigurationData

**Comment by vrdmr** [comment]
Hi @bdanse,
Thanks for reporting the issue. Could you please describe the repro steps a little more?

I tried this with 3.4.0, it kicked of the job correctly for the following cases (And there were no changes done between 3.3.1 and 3.4.0) :-
```
PS C:\> Start-AzureRmAutomationDscCompilationJob -ConfigurationName "DSCTest" -AutomationAccountName "contoso-test-automation"  -ResourceGroupName "contoso-dev"


ResourceGroupName      : contoso-dev
AutomationAccountName  : contoso-test-automation
Id                     : 8f0ab419-d96d-4c82-9594-c4bd13683895
CreationTime           : 9/27/2017 6:47:08 PM -07:00
Status                 : New
StatusDetails          : None
StartTime              : 
EndTime                : 
Exception              : 
LastModifiedTime       : 9/27/2017 6:47:08 PM -07:00
LastStatusModifiedTime : 9/27/2017 6:47:08 PM -07:00
JobParameters          : {}
ConfigurationName      : DSCTest
```

With the new `-IncrementNodeConfigurationBuild` flag passed.
```
PS C:\> Start-AzureRmAutomationDscCompilationJob -ConfigurationName "DSCTest" -AutomationAccountName "contoso-test-automation"  -ResourceGroupName "contoso-dev" -IncrementNodeConfigurationBuild


ResourceGroupName      : contoso-dev
AutomationAccountName  : contoso-test-automation
Id                     : bce30f78-3cb3-44ac-8812-52635091f51d
CreationTime           : 9/27/2017 6:48:51 PM -07:00
Status                 : New
StatusDetails          : None
StartTime              : 
EndTime                : 
Exception              : 
LastModifiedTime       : 9/27/2017 6:48:51 PM -07:00
LastStatusModifiedTime : 9/27/2017 6:48:51 PM -07:00
JobParameters          : {}
ConfigurationName      : DSCTest
```

**Comment by bdanse** [comment]
Hi @vrdmr , 

Actually I am not able to reproduce the issue. After posting I rolled back the Azure module to an earlier version (4.2.1). Worked fine. After that upgrade to 4.4.0 also works.

**Comment by vrdmr** [comment]
Thanks @bdanse for the update. I'll close the issue now.
