### ISSUE TITLE
New-AzureRmResourceGroupDeployment is stuck after it finishes the deployment

### ISSUE THREAD

**Issue by camaya** [Azure/azure-powershell#4671]
### Cmdlet(s)
New-AzureRmResourceGroupDeployment

### PowerShell Version
5.1.15063.608

### Module Version
4.3.1

### OS Version
10.0.15063.608

### Description
After a template deployment finishes creating all the resources, the script is stuck checking for status.

### Debug Output
Here's a verbose log of the deployment:

```
VERBOSE: Performing the operation "Creating Deployment" on target "test-template".
VERBOSE: 14:04:52 - Template is valid.
VERBOSE: 14:04:54 - Create template deployment 'TestDeployment'
VERBOSE: 14:04:54 - Checking deployment status in 5 seconds
VERBOSE: 14:04:59 - Resource Microsoft.Storage/storageAccounts 'teststgwwwiq6gq2sbsluva' provisioning status is running
VERBOSE: 14:04:59 - Resource Microsoft.Sql/servers 'test-sql-www' provisioning status is running
VERBOSE: 14:04:59 - Checking deployment status in 5 seconds
VERBOSE: 14:05:04 - Resource Microsoft.Cache/Redis 'test-rdc-www' provisioning status is running
VERBOSE: 14:05:04 - Resource Microsoft.Web/serverfarms 'test-asp-back-www' provisioning status is running
VERBOSE: 14:05:04 - Checking deployment status in 5 seconds
VERBOSE: 14:05:09 - Resource Microsoft.Web/serverfarms 'test-asp-front-www' provisioning status is succeeded
VERBOSE: 14:05:09 - Checking deployment status in 18 seconds
VERBOSE: 14:05:28 - Resource Microsoft.Web/sites 'test-web-front-www' provisioning status is succeeded
VERBOSE: 14:05:28 - Resource Microsoft.Web/serverfarms 'test-asp-back-www' provisioning status is succeeded
VERBOSE: 14:05:28 - Resource Microsoft.Storage/storageAccounts 'teststgwwwiq6gq2sbsluva' provisioning status is succeeded
VERBOSE: 14:05:28 - Checking deployment status in 5 seconds
VERBOSE: 14:05:33 - Resource Microsoft.Web/sites 'test-web-back-www' provisioning status is succeeded
VERBOSE: 14:05:33 - Checking deployment status in 17 seconds
VERBOSE: 14:05:50 - Checking deployment status in 5 seconds
VERBOSE: 14:05:56 - Checking deployment status in 19 seconds
VERBOSE: 14:06:15 - Checking deployment status in 5 seconds
VERBOSE: 14:06:21 - Checking deployment status in 11 seconds
VERBOSE: 14:06:32 - Checking deployment status in 15 seconds
VERBOSE: 14:06:47 - Checking deployment status in 16 seconds
VERBOSE: 14:07:04 - Checking deployment status in 15 seconds
VERBOSE: 14:07:19 - Checking deployment status in 5 seconds
VERBOSE: 14:07:25 - Checking deployment status in 11 seconds
VERBOSE: 14:07:36 - Checking deployment status in 15 seconds
VERBOSE: 14:07:51 - Checking deployment status in 5 seconds
VERBOSE: 14:07:57 - Checking deployment status in 13 seconds
```

### Script/Steps for Reproduction
This is the command I executed:

`New-AzureRmResourceGroupDeployment -Name "TestDeployment" -ResourceGroupName "test-template" -TemplateFile ".\template_pro.json" -envName "test" -sqlServerUsername "test" -sqlServerPassword $sqlPass -Verbose`

**Comment by cormacpayne** [comment]
@camaya Hey Cristhian, as of version 4.4.0, we now support running AzureRM cmdlets as jobs, which you can do by running `Start-Job { <cmdlet> }`. This will allow you to run the cmdlets in the background of your PowerShell session and track it with `Get-Job`. You can view more information about this [here](https://docs.microsoft.com/en-us/powershell/azure/context-persistence#running-azure-powershell-cmdlets-as-background-jobs).

Deploying resources in Azure takes a variable amount of time depending on the resource you are creating.

**Comment by enihcam** [comment]
Same issue in AzureStack. The status is already 'Provisioning Succeeded', but the cmdlet is still waiting for something. Beside upgrading to 4.4, do we have a workaround?

**Comment by johnstaveley** [comment]
I am getting this. All assets are de[ployed but the script never returns. This happens running it locally using powershell or using AzureDevops. This is preventing us running a CD pipeline

**Comment by AnthonyDewhirst** [comment]
How is this closed? This doesn't say if it was an issue or what was resolved. Just run in the background and that will solve everything. I am trying to run several deployments from within one ps script. Running locally, no issues, running in vsts same issue as described above. I am yet to implement as a job, but I will, but then I will have to loop until the job finishes, which doesn't feel like I am doing anything differently than running it all synchronously.

**Comment by MKruger777** [comment]
We are experiencing the issue - what was the solution?
