### ISSUE TITLE
Restore-AzureRmWebAppBackup requires app service plan

### ISSUE THREAD

**Issue by RomanNalapko** [Azure/azure-powershell#4680]
### PowerShell Version
5.1.15063.608

### Module Version
4.4.0
### OS Version
10.0.15063.608

### Debug Output
Restore-AzureRmWebAppBackup : Unable to determine app service plan for restored site. Specify an app service plan.
At C:\01_WorkingData\Azure\Source\RestoreFromBackup.ps1:87 char:5
+     Restore-AzureRmWebAppBackup -ResourceGroupName $resourceGroupName ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Restore-AzureRmWebAppBackup], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.BackupRestore.RestoreAzureWebAppBackup

### Script/Steps for Reproduction
Just try to restore existing web app with following command:
Restore-AzureRmWebAppBackup -ResourceGroupName $resourceGroupName -Name $siteName -Slot production -StorageAccountUrl $saUrl -BlobName $selectedBackup.BlobName -Databases $dbSettings -Overwrite

**Comment by haragarden3** [comment]
I’m also getting this error starting last week and using script that worked two weeks ago.
Any news/solution would be appreciated

**Comment by keyaertc** [comment]
Same problem for me with a Runbook running in Azure Automation.

**Comment by keyaertc** [comment]
I opened a case at Azure Support: REG:117100516447008

**Comment by cormacpayne** [comment]
@ahmedelnably @aspaan would you mind taking a look at this issue?

**Comment by panchagnula** [comment]
@Nking92 assigning this to you since this is backups related - i haven't verified if this is still an issue with the latest updates to backup though.

**Comment by panchagnula** [comment]
@Nking92 can you see if this is still an issue?

**Comment by btardif** [comment]
@Nking92 can you please try to repro this during the current milestone and close as no-repro if that is the case?

**Comment by panchagnula** [comment]
closing this since we believe this is fixed. Please let us know if this is not the case. Thanks!
