### ISSUE TITLE
New-AzureRMAutomationConnection documentation is out of date

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4684]
Copied from https://github.com/Azure/azure-docs-powershell/issues/419

### Cmdlet(s)
New-AzureRMAutomationConnection 

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### Module Version
AzureRM.Automation (Version 3.4.0)

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
Errors in example:
The hashtable for the parameter -ConnectionFieldValues needs the following keys:
- CertificateAssetName
- SubscriptionID
- SubscriptionName

So in example1, you need to add SubscriptionName and change AutomationCertificateName to CertificateAssetName, otherwise an error is generated, saying the AutomationAccount doesn't exist. Which is equally unhelpful.

It would also help if you added the allowed values for -ConnectionTypeName which are:
- Azure
- AzureClassicCertificate
- AzureServicePrincipal

(An explanation of each of the above would be helpful too)

Referenced Document:
- https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/new-azurermautomationconnection
- https://github.com/Azure/azure-docs-powershell/blob/master/azureps-cmdlets-docs/ResourceManager/AzureRM.Automation/v3.4.0/New-AzureRMAutomationConnection.md

**Comment by TaraMeyer** [comment]
@sdwheeler and @markcowl  - what can I do to help move this forward?

**Comment by maddieclayton** [comment]
@vrdmr Can you take a look at this documentation issue?

**Comment by andyw248** [comment]
Looks like this was fixed.
