### ISSUE TITLE
Add- & Set-AzureRmEnvironment throws error for correct -ArmEndpoint parameter

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#4685]
### Cmdlet(s)
Add- & Set-AzureRmEnvironment 

### PowerShell Version
5.1.14393.1737

### Module Version
azurerm.profile 3.4.0

### OS Version
 10.0.14393.1737

### Description
Add-AzureRmEnvironment -name stackadmin -ARMEndpoint “https://adminmanagement.redmond.ext-u15f2402.masd.stbtest.microsoft.com”
Add-AzureRmEnvironment : **Endpoint provided is invalid. Please check the value and retry again with the correct value.**
Parameter name: url
At line:1 char:1
+ Add-AzureRmEnvironment -name stackadmin -ARMEndpoint https://adminman ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureRmEnvironment], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMEnvironmentCommand

### Script/Steps for Reproduction
Add-AzureRmEnvironment -name stackadmin -ARMEndpoint “https://adminmanagement.redmond.ext-u15f2402.masd.stbtest.microsoft.com”

**Comment by markcowl** [comment]
Fixed.
