### ISSUE TITLE
[Request for help] Removing load balancer nat rule from vmss

### ISSUE THREAD

**Issue by ig-sinicyn** [Azure/azure-powershell#4698]
### Cmdlet(s)
Set-AzureRmNetworkInterface 

### PowerShell Version
 5.1.15063.608          

### Module Version
 4.1.0      AzureRM.Network

### OS Version
10.0.15063.608

### Description
I'm trying to remove a NAT rule from a load balancer associated with VMSS.
the simple 
```
    Remove-AzureRmLoadBalancerInboundNatPoolConfig -LoadBalancer $lb -Name 'webAppNatRule'
    Set-AzureRmLoadBalancer -LoadBalancer $lb
```

fails with
```
Set-AzureRmLoadBalancer : Cannot remove inbound nat pool webAppNatRule from load balancer since it is in use by virtual machine scale set ... vmssName.
StatusCode: 400
ReasonPhrase: Bad Request
```

the attempt to remove rule from NIC and update it fails with 
```
Set-AzureRmNetworkInterface : Resource : {0}, not found
строка:17 знак:5
+     Set-AzureRmNetworkInterface -NetworkInterface $t
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmNetworkInterface], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.SetAzureNetworkInterfaceCommand
```

full script:
```
$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function RemoveNAT {
    Param(
        [string]$resGroup,
        [string]$lbName,
        [string]$natRuleName,
        [string]$vmssName
    )

    $t = Get-AzureRmNetworkInterface -VirtualMachineScaleSetName $vmssName -ResourceGroupName $resGroup
    foreach ($c in $t.IpConfigurations[0].LoadBalancerInboundNatRules) { 
        if ($c.Id.Contains($natRuleName)) {
            echo "!!! Remove ($c.Id)"
            $t.IpConfigurations[0].LoadBalancerInboundNatRules.Remove($c)
            break
        }
    }
    Set-AzureRmNetworkInterface -NetworkInterface $t
    $t = Get-AzureRmNetworkInterface -VirtualMachineScaleSetName $vmssName -ResourceGroupName $resGroup
    echo "-------------"
    echo $t.IpConfigurations[0].LoadBalancerInboundNatRules
    echo "-------------"

    $lb = Get-AzureRmLoadBalancer -Name $lbName -ResourceGroupName $resGroup
    Remove-AzureRmLoadBalancerInboundNatPoolConfig -LoadBalancer $lb -Name $natRuleName
    Set-AzureRmLoadBalancer -LoadBalancer $lb
}
RemoveNAT 'someResGroup' 'someLoadBalancer' 'webAppNatRule' 'vmssName'
```

so is there any working way to remove inbound nat pool?

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft Hey Deepak, would you mind taking a look at this issue?

**Comment by needcash** [comment]
Any update on this one? I'm having very similar problem. @cormacpayne @DeepakRajendranMsft

**Comment by rwwilden** [comment]
You could use Azure Resource Explorer to temporarily disconnect the VMSS and the NAT pool(s). Since they are no longer in use by the VMSS, you can now apply your changes. I wrote a [blog post](https://ronaldwildenberg.com/azure/2018/02/09/remove-inbound-nat-rules-from-azure-vmss.html) explaining this approach.

**Comment by zacharyhumphrey** [comment]
how is this stilllllll not fixed?

**Comment by praries880** [comment]
@MikhailTryakhov  can you take a look at this issue?

**Comment by EvgenyAgafonchikov** [comment]
+Adding some details on the initial message, i.e.
```
Set-AzureRmLoadBalancer : Cannot remove inbound nat pool webAppNatRule from load balancer since it is in use by virtual machine scale set ... vmssName.
```

This is expected behavior as there is no way to delete the resource A until it is used by another resources. So first you would need to delete or update (remove references) the resource which depends on the resource A. Otherwise there would be invalid references pointing to nowhere.

**Comment by zacharyhumphrey** [comment]
@EvgenyAgafonchikov that works for me and was successful! Could you kindly provide the article your referencing in your post?

**Comment by EvgenyAgafonchikov** [comment]
Sure. I believe you mean "blog post" I mentioned. It is created by @rwwilden and referred in this comment above: https://github.com/Azure/azure-powershell/issues/4698#issuecomment-364391184
Other PowerShell things are just results of investigation based on the blog post's approach.

**Comment by zacharyhumphrey** [comment]
@EvgenyAgafonchikov anyway to get a legit MSDN article? Your outline of the needed commands in powershell was the last piece that I needed assistance being outlined. I do know w/o your post here I would've been stuck. :)

**Comment by MikhailTryakhov** [comment]
@zacharyhumphrey  I'll take a look at the way to create MSDN article or something like that. I'll keep you updated here
