### ISSUE TITLE
Get-AzureSubscription, TAB completion does not work after pipeline

### ISSUE THREAD

**Issue by carlocardella** [Azure/azure-powershell#47]
I can repro this problem on two different machines (both Windows 8.1):
 Name : Windows PowerShell ISE Host
 Version : 4.0
 InstanceId : f3c1119d-3c32-432d-a235-5b3755fe9979
 UI : System.Management.Automation.Internal.Host.InternalHostUserInterface
 CurrentCulture : en-US
 CurrentUICulture : en-US
 PrivateData : Microsoft.PowerShell.Host.ISE.ISEOptions
 IsRunspacePushed : False
 Runspace : System.Management.Automation.Runspaces.LocalRunspace

If you run Get-AzureSubscription | ? subscr --> TAB nothing happens, the command is used to cycle through available options (SubscriptionId and SubscriptionName in this example).

Intellisense in the ISE also appears to have a problem: 
 if you run "(Get-AzureSubscription)[0]" the SubscriptionId is returned along with other subscription info, but if you run "(Get-AzureSubscription)[0]." (add the dot to invoke the IntelliSense) I get a completely different list of properties (Account, Environment, Id, Name, Properties).

Anyway if I run "(Get-AzureSubscription)[0] | get-method" then I see the expected properties

TypeName: Microsoft.WindowsAzure.Commands.Profile.Models.PSAzureSubscription

Name MemberType Definition 

Equals Method bool Equals(System.Object obj)

 GetHashCode Method int GetHashCode()

 GetType Method type GetType()

 ToString Method string ToString()

 Accounts Property Microsoft.WindowsAzure.Commands.Common.Models.AzureAccount[] Accounts {get;set;}
 CurrentStorageAccountName Property string CurrentStorageAccountName {get;set;}

 DefaultAccount Property string DefaultAccount {get;set;}

 Environment Property string Environment {get;set;}

 IsCurrent Property bool IsCurrent {get;set;}

 IsDefault Property bool IsDefault {get;set;}

 SubscriptionId Property string SubscriptionId {get;set;}

 SubscriptionName Property string SubscriptionName {get;set;}

 SupportedModes Property string SupportedModes {get;set;}

**Comment by markcowl** [comment]
Closing as obsolete. Please open a new issue if this recurs
