### ISSUE TITLE
Get-AzureRmAutoscaleSetting not returning Capacity properties

### ISSUE THREAD

**Issue by lukeb1961** [Azure/azure-powershell#4702]
### Cmdlet(s)
Get-AzureRmAutoscaleSetting

### PowerShell Version
> $PSVersionTable
Name                           Value                                                                       
----                           -----                                                                       
PSVersion                      5.1.16299.0                                                                 
PSEdition                      Desktop                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                     
BuildVersion                   10.0.16299.0                                                                
CLRVersion                     4.0.30319.42000                                                             
WSManStackVersion              3.0                                                                         
PSRemotingProtocolVersion      2.3                                                                         
SerializationVersion           1.1.0.1  
### Module Version
 4.4.0      AzureRM 

### OS Version
Windows 10,    16299.rs3_release.170922-1354 
### Description
(Get-AzureRmAutoscaleSetting -ResourceGroup UNIXTHINGS).profiles.Capacity 
4

expected to see Default/Maximum/Minimum properties.

### Debug Output
DEBUG: 4:39:02 PM - GetAzureRmAutoscaleSettingCommand begin processing with ParameterSet 'Parameters for Get
-AzureRmAustoscaleSetting cmdlet'.
DEBUG: 4:39:02 PM - using account id 'lukebrennan@outlook.com'...
WARNING: The AutoscaleSettingResourceName field will be deprecated in a future release since it always equal
s the Name field. In this version is optional.
DEBUG: [Common.Authentication]: Authenticating using Account: 'lukebrennan@outlook.com', environment: 'Azure
Cloud', tenant: '1f89577f-4235-4965-83e5-aad1a7e761fc'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/03/2017 05:39:02: cd6ed63a-45e4-4dcd-b820-7b2063d50805 - AcquireTokenHandlerBase: === Token Acquis
ition started:
	Authority: https://login.microsoftonline.com/1f89577f-4235-4965-83e5-aad1a7e761fc/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (6 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 10/03/2017 05:39:02: cd6ed63a-45e4-4dcd-b820-7b2063d50805 - TokenCache: Looking up cache for a token.
..

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/03/2017 05:39:02: cd6ed63a-45e4-4dcd-b820-7b2063d50805 - TokenCache: An item matching the requeste
d resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 10/03/2017 05:39:02: cd6ed63a-45e4-4dcd-b820-7b2063d50805 - TokenCache: 47.332202705 minutes left unt
il token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/03/2017 05:39:02: cd6ed63a-45e4-4dcd-b820-7b2063d50805 - TokenCache: A matching item (access token
 or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/03/2017 05:39:02: cd6ed63a-45e4-4dcd-b820-7b2063d50805 - AcquireTokenHandlerBase: === Token Acquis
ition finished successfully. An access token was retuned:
	Access Token Hash: jXbqi2/kSuk66e43DM+z+UaZvV/pZfyFFa9NP3E5L9c=
	Refresh Token Hash: LJyQWxfeN9zX5FLahAhUJJ07IOduXgCyIlrGoCs7Vfw=
	Expiration Time: 10/03/2017 06:26:22 +00:00
	User Hash: YaMfsGPkmwxwhyKw73ipmyjRqqUKsNAj5t9JRnaYlxk=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/03/2017 05:39:02:  - TokenCache: Serializing token cache with 6 items.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/03/2017 05:39:02: de3e4adc-3768-4659-9385-a27a822ff35e - AcquireTokenHandlerBase: === Token Acquis
ition started:
	Authority: https://login.microsoftonline.com/1f89577f-4235-4965-83e5-aad1a7e761fc/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (6 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 10/03/2017 05:39:02: de3e4adc-3768-4659-9385-a27a822ff35e - TokenCache: Looking up cache for a token.
..

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/03/2017 05:39:02: de3e4adc-3768-4659-9385-a27a822ff35e - TokenCache: An item matching the requeste
d resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 10/03/2017 05:39:02: de3e4adc-3768-4659-9385-a27a822ff35e - TokenCache: 47.332202705 minutes left unt
il token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/03/2017 05:39:02: de3e4adc-3768-4659-9385-a27a822ff35e - TokenCache: A matching item (access token
 or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/03/2017 05:39:02: de3e4adc-3768-4659-9385-a27a822ff35e - AcquireTokenHandlerBase: === Token Acquis
ition finished successfully. An access token was retuned:
	Access Token Hash: jXbqi2/kSuk66e43DM+z+UaZvV/pZfyFFa9NP3E5L9c=
	Refresh Token Hash: LJyQWxfeN9zX5FLahAhUJJ07IOduXgCyIlrGoCs7Vfw=
	Expiration Time: 10/03/2017 06:26:22 +00:00
	User Hash: YaMfsGPkmwxwhyKw73ipmyjRqqUKsNAj5t9JRnaYlxk=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/03/2017 05:39:02:  - TokenCache: Serializing token cache with 6 items.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourcegroups/UNIXTHINGS/pr
oviders/microsoft.insights/autoscalesettings?api-version=2015-04-01

Headers:
x-ms-client-request-id        : 87883ab2-53a6-4e0d-83d0-7b5dbba9bb3b
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 6387e04f-057b-4f7c-8ad9-2487fe83ef87
x-ms-ratelimit-remaining-subscription-reads: 14888
x-ms-correlation-request-id   : daee4071-f66b-4767-aac9-166343231975
x-ms-routing-request-id       : AUSTRALIAEAST:20171003T053901Z:daee4071-f66b-4767-aac9-166343231975
Cache-Control                 : no-cache
Date                          : Tue, 03 Oct 2017 05:39:01 GMT
Server                        : Microsoft-IIS/8.5

Body:
{
  "value": [
    {
      "id": "/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourceGroups/UNIXthings/providers/microso
ft.insights/autoscalesettings/autosetting1",
      "name": "autosetting1",
      "type": "Microsoft.Insights/autoscaleSettings",
      "location": "australiaeast",
      "tags": {
        "$type": "Microsoft.WindowsAzure.Management.Common.Storage.CasePreservedDictionary, Microsoft.Window
sAzure.Management.Common.Storage"
      },
      "properties": {
        "profiles": [
          {
            "name": "autoprofile1",
            "capacity": {
              "minimum": "2",
              "maximum": "10",
              "default": "3"
            },
            "rules": [
              {
                "metricTrigger": {
                  "metricName": "Percentage CPU",
                  "metricNamespace": "",
                  "metricResourceUri": "/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourceGroups/U
NIXthings/providers/Microsoft.Compute/virtualMachineScaleSets/SydWinVMScaleSet",
                  "timeGrain": "PT1M",
                  "statistic": "Average",
                  "timeWindow": "PT5M",
                  "timeAggregation": "Average",
                  "operator": "GreaterThan",
                  "threshold": 60.0
                },
                "scaleAction": {
                  "direction": "Increase",
                  "type": "ChangeCount",
                  "value": "1",
                  "cooldown": "PT5M"
                }
              },
              {
                "metricTrigger": {
                  "metricName": "Percentage CPU",
                  "metricNamespace": "",
                  "metricResourceUri": "/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourceGroups/U
NIXthings/providers/Microsoft.Compute/virtualMachineScaleSets/SydWinVMScaleSet",
                  "timeGrain": "PT1M",
                  "statistic": "Average",
                  "timeWindow": "PT5M",
                  "timeAggregation": "Average",
                  "operator": "LessThan",
                  "threshold": 30.0
                },
                "scaleAction": {
                  "direction": "Decrease",
                  "type": "ChangeCount",
                  "value": "1",
                  "cooldown": "PT5M"
                }
              }
            ]
          }
        ],
        "enabled": true,
        "name": "autosetting1",
        "targetResourceUri": "/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourceGroups/UNIXthings/
providers/Microsoft.Compute/virtualMachineScaleSets/SydWinVMScaleSet",
        "notifications": null
      }
    }
  ]
}

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmAutoscaleSetting; IsSuccess - True; Duration - 00:00:00.67283
04; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 4:39:03 PM - GetAzureRmAutoscaleSettingCommand end processing.
DEBUG: 4:39:03 PM - GetAzureRmAutoscaleSettingCommand end processing.
4

**Comment by lukeb1961** [comment]
just a follow-up, what works is
 (Get-AzureRmAutoscaleSetting -ResourceGroup $ResourceGroup).profiles[0].Capacity
Minimum Maximum DefaultProperty
------- ------- ---------------
2       10      3    
versus
(Get-AzureRmAutoscaleSetting -ResourceGroup $ResourceGroup).profiles.Capacity
4

**Comment by cormacpayne** [comment]
@gucalder Hey Guillermo, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
@gucalder ping

**Comment by asheniam** [comment]
Please try with the latest Get-AzAutoscaleSetting.  I'm not able to repro this issue with the latest PowerShell.
