### ISSUE TITLE
Set-AzureRmVMOSDisk does not honor New-AzureRmDiskConfig -OsType property

### ISSUE THREAD

**Issue by clericc** [Azure/azure-powershell#4703]
### Cmdlet(s)
Set-AzureRmVmOSDisk, New-AzureRmDiskConfig

### PowerShell Version
4.4.0

### OS Version
Windows 10

### Description
I create a new managed Disk config from a snapshot:
`$newOsDiskConfig= New-AzureRmDiskConfig
        -CreateOption Copy
        -SourceResourceId $snapshot.Id
        -Location $snapshot.Location
        -SkuName someSku
        -OsType $currentDisk.OsType;`
`$newOsDisk = New-AzureRmDisk
    -Disk $newOsDiskConfig
    -ResourceGroupName $resGrpName
    -DiskName $osDiskName`

Then, i attach the disk to the vm config:
`$newVmConfig = Set-AzureRmVMOSDisk
    -VM $newVmConfig
    -CreateOption Attach
    -ManagedDiskId  $newOsDisk.Id
`

When i then create the VM, i get an error that `osDisk.osType is missing (null)`. This can be fixed by giving -Linux/-Windows switch on `Set-AzureRmVMOSDisk`. Should this be necessary when i stated the osType before? This makes is annoying to create a generic script which is able to handle both Linux/Windows os disks. Either the setting should be honored or `OsType` should be a parameter on `Set-AzureRmVMOSDisk` i guess?

**Comment by cormacpayne** [comment]
@hyonholee Hey Hyonho, would you mind taking a look at this issue?

CC: @singhkays

**Comment by singhkays** [comment]
@clericc Making the osType a parameter would be a breaking change to existing scripts, something we try to avoid unless absolutely necessary. Isn't it possible to solve this by using an if..else statement to handle the specific OS case?

**Comment by clericc** [comment]
Yeah it is, thats what i do right now. But it wouldn't be a breaking change to make ` Set-AzureRmVMOSDisk` honor the pre-existing setting from `$newVmConfig`, would it? But you must admit, the -Linux/-Windows switches are nice for interactive work but since PowerShell is designed to automate Workflow, the `-OsType` parameter is the better design

**Comment by singhkays** [comment]
I suppose that would've been a better design. I don't own this cmdlet anymore so I'm not sure why it was implemented as a switch. @hyonholee do you know? 

Based on my previous knowledge of this cmdlet, I think the reason it doesn't have any knowledge of the disk is that it's an offline cmdlet. It only modifies the local vm object and doesn't make a call out to Azure to figure out the os type specified on the disk object.

**Comment by clericc** [comment]
I see the issue. I only give it the resource id, not the actual disk object. So if one does not want to make this an online cmdlet, only option would be to add `-ManagedDisk $diskObject` or add `-OsType` in Addition to `-Linux`/`Windows`. Anyway, for now doing if/else works, of cource. Thanks for this enlightening information, i never thought about online/offline cmdlets

**Comment by singhkays** [comment]
@clericc Yes I think that could work, although it is probably unlikely but I worry if that will lead to additional confusion if one uses -Linux with -OsType Windows  & vice-versa

**Comment by clericc** [comment]
you didnt give an opinion about -ManagedDisk $diskObject proposal.

**Comment by singhkays** [comment]
@clericc Can you explain that a bit more? Maybe share a code example of how you'd use it

**Comment by clericc** [comment]
```
$newOsDisk = New-AzureRmDisk -Disk $newOsDiskConfig -ResourceGroupName someResGrp -DiskName someDisk
 $newVmConfig = Set-AzureRmVMOSDisk -VM $newVmConfig -CreateOption Attach -ManagedDisk $newOsDisk
```

**Comment by singhkays** [comment]
@clericc I like this! 

@hyonholee Can you sync on the dev team and figure out when we can do this?

**Comment by cormacpayne** [comment]
@singhkays @hyonholee any update on this?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
