### ISSUE TITLE
Update-AzureRMVmss fails with error "Changing property 'zones' is not allowed."

### ISSUE THREAD

**Issue by andradf** [Azure/azure-powershell#4704]
### Cmdlet(s)
Update-AzureRMVmss

### PowerShell Version
5.1.15063.608

### Module Version
AzureRM.Compute 3.4.0

### OS Version
10.0.15063.608

### Description
When attempting to update a Virtual Machine Scale Set. The command fails with error "Changing property 'zones' is not allowed." 
The VirtualMachineScaleSet object passed to Update-AzureRMVmss has null as the value for the Zones property, so it shouldn't be interpreted as an attempt to change it. Furthermore, Get-AzureRMVmss returns an empty list in the Zones property. Passing an empty list to Update-AzureRMVmss results in the same error. What value should be passed in Zones?

### Script/Steps for Reproduction
Have an existing VMSS and a Key Vault with a certificate loaded to it. Attempt to add the certificate to the VMSS.

```
$vault = Get-AzureRmKeyVault -VaultName <vaultName>
$certConfig = New-AzureRmVmssVaultCertificateConfig -CertificateUrl <certUrl>
$VMSS = New-AzureRmVmssConfig
$VMSS.Location = 'westus'
Add-AzureRmVmssSecret -VirtualMachineScaleSet $VMSS -SourceVaultId $vault.ResourceId -VaultCertificate $certConfig
Update-AzureRmVmss -ResourceGroupName <RGName> -VMScaleSetName <vmssName> -VirtualMachineScaleSet $VMSS
```
throws 
Update-AzureRmVmss : Changing property 'zones' is not allowed.
ErrorCode: PropertyChangeNotAllowed
ErrorMessage: Changing property 'zones' is not allowed.
StatusCode: 409
ReasonPhrase: Conflict
OperationID : 6ed2e604-43ae-4b8a-ae6e-57819ee554ad
At line:1 char:1

**Comment by svpudik** [comment]
I have same issue...
```
 $VMSS = Add-AzureRmVmssSecret -VirtualMachineScaleSet $VMSS -VaultCertificate $CertConfig -SourceVaultId $kvResourceID 
Update-AzureRmVmss -Name $ScaleSetName -ResourceGroupName $vmResourceGroup -VirtualMachineScaleSet $VMSS -Verbose
```

**Comment by cormacpayne** [comment]
@hyonholee Hey Hyonho, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
CC: @gbowerman

**Comment by gbowerman** [comment]
@cormacpayne fixed in https://github.com/Azure/azure-powershell/pull/4701 - should be in October PowerShell release.

**Comment by andradf** [comment]
Any suggestions about how to go about updating a VMSS in the meantime?

**Comment by gbowerman** [comment]
Can you update the properties of the VMSS in:
- resources.azure.com
- CLI

**Comment by mjsabin01** [comment]
Is there a workaround available or an ETA on the release becoming available?  I have a cert that needs to be updated  within a week.

**Comment by gbowerman** [comment]
@mjsabin01 workarounds:
1. Use resources.azure.com to edit the scale set properties.
2. Use CLI to update the scale set properties. Latest CLI is available from the portal in the cloud shell.
3. Install the 4.4.1 release candidate https://github.com/Azure/azure-powershell/releases

**Comment by hyonholee** [comment]
This is fixed.  https://github.com/Azure/azure-powershell/pull/4701
