### ISSUE TITLE
"New-AzureRmVpnClientConfiguration" requires 'virtualNetworkGatewayName' but rejects it as parameter

### ISSUE THREAD

**Issue by ulkeba** [Azure/azure-powershell#4712]
The documentation [AzureRM-Doc](https://docs.microsoft.com/en-us/powershell/module/azurerm.network/new-azurermvpnclientconfiguration?view=azurermps-4.4.0) and here [Azure-P2S-VPN-Doc](https://docs.microsoft.com/de-de/azure/vpn-gateway/point-to-site-vpn-client-configuration-azure-cert) suggest creating a VPN client configuration using this command:
&nbsp;`New-AzureRmVpnClientConfiguration -ResourceGroupName "TestRG" -VirtualNetworkGatewayName "VNet1GW" -AuthenticationMethod "EapTls"`

However, when I try to invoke this command (replacing the example values of 'ResourceGroupName' and 'VNet1GW' with the respective values of my setup, of course), I get the following (German) error message (saying that no parameter named 'VirtualNetworkGatewayName' has been found):
&nbsp;`New-AzureRmVpnClientConfiguration : Es wurde kein Parameter gefunden, der dem Parameternamen VirtualNetworkGatewayName entspricht.`

Invoking  
&nbsp;`New-AzureRmVpnClientConfiguration -ResourceGroupName "TestRG" -AuthenticationMethod "EapTls"`
instead yields:
&nbsp;`New-AzureRmVpnClientConfiguration : 'virtualNetworkGatewayName' cannot be null.`

I tried defining a variable `$virtualNetworkGatewayName` and specifying `virtualNetworkGatewayName` (note the lower-case 'v'), but neither worked. 

### Cmdlet(s)
New-AzureRmVpnClientConfiguration

### PowerShell Version
5.1.14393.1715

### Module Version
AzureRM.Network: 4.4.0
AzureRM.Profile: 3.4.0

### OS Version
10.0.14393.1715

**Comment by cormacpayne** [comment]
@ulkeba thanks for opening this issue! It looks like this is an error in the documentation.

@ritwikbasu Hey Ritwik, would you mind taking a look at this issue?

**Comment by ritwikbasu** [comment]
This is an issue with documentation. This command takes resource group name and gateway name by pipeline value.

Please try this:
New-AzureRmVpnClientConfiguration -ResourceGroupName "TestRG" -Name "VNet1GW" -AuthenticationMethod "EapTls"

Will fix this documentation issue.

**Comment by ulkeba** [comment]
Thanks; [Azure-P2S-VPN-Doc (de)](https://docs.microsoft.com/de-de/azure/vpn-gateway/point-to-site-vpn-client-configuration-azure-cert) has been updated meanwhile. The shown commands now work well.

However, Example 1 you show in [AzureRM-Doc ](https://docs.microsoft.com/en-us/powershell/module/azurerm.network/new-azurermvpnclientconfiguration?view=azurermps-4.4.0), is not consistent with the (updated) command reference at the top of the page: the example still says "New-AzureRmVpnClientConfiguration -VirtualNetworkGatewayName ...".
