### ISSUE TITLE
0.9.2 ARM :: Set-AzureVirtualNetworkSubnetConfig command requires -AddressPrefix param

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#472]
## Scenario
Let's say, for example, that I have an existing Virtual Network, made up of multiple subnets. I want to assign a Network Security Group to a Virtual Network subnet.

## Problem
The `Set-AzureVirtualNetworkSubnetConfig` command **requires** that the `-AddressPrefix` parameter be specified.

## Solution
If I already have an existing Virtual Network and subnets, then I should not have to specify the `-AddressPrefix` parameter in order to apply the Network Security Group (NSG) to the subnet.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by Teodelas** [comment]
+1

**Comment by markjbrown** [comment]
Duplicate from https://github.com/Azure/azure-powershell/issues/1551 closing, will track from #1551
