### ISSUE TITLE
Output type for Get-AzureRmDisk is incorrect in documentation

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4742]
### Cmdlet(s)
Get-AzureRmDisk

### PowerShell Version
Current

### Module Version
Current AzureRM.Compute

### Description

> LiveFyre comment:
> Output structure is Microsoft.Azure.Commands.Compute.Automation.Models.PSDisk which includes the properties: Name, Type, OwnerId, ManagedBy, Ski, Zones, TimeCreated, OsType, CreationData, DiskSizeGB, EncryptionSettings, ProvisioningState, Id, amd Tags.

Need up update output type in the documentation and document the PSDisk class.

**Comment by twitchax** [comment]
@hyonholee, can you take a look at this?
