### ISSUE TITLE
Docs for Set-AzureRmApplicationGatewayBackendAddressPool have invalid example

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4743]
### Cmdlet(s)
Set-AzureRmApplicationGatewayBackendAddressPool

### PowerShell Version
Current

### Module Version
Current AzureRM.Network

### Description

LiveFyre comment:
> Each example in this article has a bug for the variable named AppGW.  They show $ AppGW, but should be $AppGW.
>
> Also example 3 won't work because -BackendIPConfigurationIds is not supported by Set-AzureRmApplicationGatewayBackendAddressPool
> Example 3
> $Nic01 = Get-AzureRmNetworkInterface -Name "Nic01" -ResourceGroupName "ResourceGroup01"
> $Nic02 = Get-AzureRmNetworkInterface -Name "Nic02" -ResourceGroupName "ResourceGroup01"
> $AppGw = Get-AzureRmApplicationGateway -Name "ApplicationGateway01" -ResourceGroupName "ResourceGroup01"
> $AppGw = Set-AzureRmApplicationGatewayBackendAddressPool -ApplicationGateway $ AppGw -Name "Pool02" -BackendIPConfigurationIds $nic01.Properties.IpConfigurations[0].Id, $nic02.Properties.IpConfiguration[0].Id

Need to fix example syntax errors and remove invalid parameter in example #3.

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft  Hey Deepak, would you mind taking a look at this documentation issue, or redirecting it to the appropriate team? It looks to be an easy fix, but I just wanted confirmation on the third example using an incorrect parameter.

**Comment by maddieclayton** [comment]
Issue fixed.
