### ISSUE TITLE
Docs for Set-AzureStorageBlobContent missing examples

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4744]
### Cmdlet(s)
Set-AzureStorageBlobContent

### PowerShell Version
Current

### Module Version
Current Azure.Storage

### Description

LiveFyre comment:
> Please post examples for using the -Properties parameter? Thank you!

**Comment by cormacpayne** [comment]
@blueww Hey Wei, would you mind taking a look at this documentation issue?

**Comment by blueww** [comment]
@sdwheeler 
Thanks for reporting this! I will update the help doc.

We can use a hash table to set the properties, as below:

`Set-AzureStorageBlobContent -File C:\temp\a.jpg -Container testcontainer -Properties @{"ContentType" = "image/jpeg"; "ContentMD5" = "i727sP7HigloQDsqadNLHw=="}`

Only following 6 properties are supported to set:

- CacheControl
- ContentDisposition
- ContentEncoding
- ContentLanguage
- ContentMD5
- ContentType

**Comment by blueww** [comment]
@cormacpayne 
PR is raised: https://github.com/Azure/azure-powershell/pull/4751
Would you please help to review?
Thanks!
