### ISSUE TITLE
Add LocationCompleter to Compute cmdlets

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#4748]
### Description
- [ ] Add LocationCompleter to Compute cmdlets with -Location parameters
- [ ] Document issues

**Comment by cormacpayne** [comment]
@maddieclayton work with the Compute team to get this into their generator

CC: @huangpf @hyonholee

**Comment by maddieclayton** [comment]
### Updated description:

- [ ] Add the LocationCompleterAttribute with correct Provider/Resource type to each generated cmdlet with the -Location parameter.
- [ ] Regenerate the files and test functionality

**Comment by maddieclayton** [comment]
Done
