### ISSUE TITLE
Start-AzureRmAutomationDscCompilationJob: issue when passing hashtable object to -parameters

### ISSUE THREAD

**Issue by arcotek-ltd** [Azure/azure-powershell#4752]
### Cmdlet(s)
`Start-AzureRmAutomationDscCompilationJob`

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

```
PS C:\> $PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      15063  296 
```    

### Module Version
```
PS C:\> Get-Command Start-AzureRmAutomationDscCompilationJob
CommandType     Name                                               Version    Source                                                                                               
-----------     ----                                               -------    ------                                                                                               
Cmdlet          Start-AzureRmAutomationDscCompilationJob           3.4.0      AzureRM.Automation
```
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
See above (Windows 10)

### Description
Receiving the error `You cannot call a method on a null-valued expression`
Taking the following DSC configuration:

```
Configuration TestLoop
{
    param
    (
        $SqlScriptsArray,
        $SqlLoginsArray,
        $DatabaseServerName,
        $Path
    )
    
    $VerbosePreference = "Continue"
    Import-DscResource -ModuleName xSqlServer
    foreach($script in $SqlScriptsArray)
    {
        Write-Warning "Script: $Script"
        $c=1
        foreach($account in $SqlLoginsArray)
        {
            Write-Warning ("Array $($SqlLoginsArray | Out-String)")
            $DomainAccount = $account.keys
            Write-Warning "DomainAccount: $DomainAccount"
            
            $NetBiosDomain = ($DomainAccount.split('\')[0]).split('\.')[0]
            $username = $DomainAccount.split('\')[1]
            $DomainUser = @($NetBiosDomain,$username) -join '\'
            $ServerRole = $account.values
            Write-Warning "$c User:$($DomainUser), Action:$($script)"
        
            xSQLServerScript "Execute_$($script)_$($username)_script"
            {
                ServerInstance = $DatabaseServerName #Only needs the computer name for default instances.
                SetFilePath = Join-Path $Path "Set-$script-$username.sql"
                GetFilePath = Join-Path $Path "Get-$script-$username.sql"
                TestFilePath = Join-Path $Path "Test-$script-$username.sql"
                QueryTimeout = 120
            }
            $c++
        }
    }
}
```

With `$SqlLoginsArray` parameter passed to `Start-AzureRmAutomationDscCompilationJob -parameters `with the value:

`$SqlLoginsArray = @(@{"arwlcs.com\arw"="sysadmin"},@{"arwlcs.com\DynamicsInstallUser"="sysadmin"})
`

The error is thrown by the .split because $DomainAccount is $null. For some reason, it can't get the keys from $SqlLoginsArray. However, running this Foreach loop outside of DSC, it works as one would expect.

In Azure portal, `Write-Warning ("Array $($SqlLoginsArray | Out-String)")` returns:
```
5dd3e16a-609c-4326-8a11-fea4a6a63dfc:[localhost]:Array 
arwlcs.com\arw
--------------
sysadmin
```

I can fix this by changing `$SqlLoginsArray` to:
```$sqlLoginsArray = @(@{"user"="arwlcs.com\arw";"role"="sysadmin"},@{"user"="arwlcs.com\DynamicsInstallUser"; "role"="sysadmin"})```

And changing the line from:
`$DomainAccount = $account.keys`
to:
`$DomainAccount = $account.User`

I can't work out why there is a difference between "on-premise" powershell and what your automation server is doing. I have tried removing the '\' and the '.', thinking the JSON paser might be getting upset, but it makes no difference.

It might seem like a small thing, but it has taken a day to resolve this, mainly because the logging is so poor.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

Sorry, it takes too long to create a redacted debug output. Please contact me if you want more info.

### Script/Steps for Reproduction

See description. If you need more info, please contact me.

**Comment by cormacpayne** [comment]
@vrdmr Hey Varad, would you mind taking a look at this issue?

**Comment by mbreakey3** [comment]
The problem is that the parameter is getting passed in as an array of PSCustomObjects rather than a hashtable through the cmdlet, so the object doesn't have a type: "keys". This is due to how the C# cmdlet code is processing the parameters, that's why you don't see this issue when you compile the configuration on your local box.
