### ISSUE TITLE
Docs for New-AzureProfile needs examples

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4761]
### Cmdlet(s)
New-AzureProfile
https://docs.microsoft.com/powershell/module/azure/new-azureprofile

### Module Version
Module: Azure
Azure Service Management PowerShell 4.0.0

### Description
LiveFyre Comment:
> Matthew_Blessing
> Where are the examples? There should be a few valid examples of the usage parameters, it's useless without them.

**Comment by markcowl** [comment]
@sdwheeler Any time we get a livefyre comment on RDFE cmdlets, the first question should be about how we move the customer to ARM.  Given limited resourcing, I don't think we will be able to service this request.

**Comment by sdwheeler** [comment]
@markcowl Understood. However, we need to respond to the LiveFyre comment. The SLA for responses is 24 hours. So we need standard language we can use to respond to ASM comments.
