### ISSUE TITLE
Get-AzureRmNetworkSecurityGroup returns tags hashtable as property ".Tag" rather than ".Tags"

### ISSUE THREAD

**Issue by lesterw1** [Azure/azure-powershell#4768]
### Cmdlet(s)
Get-AzureRmNetworkSecurityGroup

### PowerShell Version
5.1.14409.1012

### Module Version
AzureRM.Network 4.4.0

### OS Version
10.0.14409.1012

### Description
The Get-AzureRMNetworkSecurityGroup returns tags in a hastable property named "Tag" (singular) instead of "Tags" (plural).  This is inconsistent with all other objects which uses "Tags" for the hashtable property name.

Curiously enough, the REST API does label the property as "Tags" (see excerpt of debug output below).

### Debug Output
This is an excerpt only, sufficient to show that the correct property name is "Tags" and not "Tag":

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : e2751dbc-4651-4c01-be79-2e1766841086
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
ETag                          : W/"13f096a1-bf31-4205-b507-9e6528c94325"
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 14984
x-ms-correlation-request-id   : f3a6d04f-6da9-451a-84d0-266e4b7d3331
x-ms-routing-request-id       : UKSOUTH:20171011T090638Z:f3a6d04f-6da9-451a-84d0-266e4b7d3331
Date                          : Wed, 11 Oct 2017 09:06:37 GMT

Body:
{
  "name": "nsg-vr-westus-default",
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-network/providers/Microsoft.Network/networkSecurityGroups/nsg-westus-default",
  "etag": "W/\"13f096a1-bf31-4205-b507-9e6528c94325\"",
  "type": "Microsoft.Network/networkSecurityGroups",
  "location": "westus",
  "tags": {
    "CreatedBy": "somone@contoso.com",
    "Policy": "Standard",
    "DefaultRulesApplied": "09-Oct-17 09:42 UTC"
  },
  "properties": {
    "provisioningState": "Succeeded",

### Script/Steps for Reproduction
(Get-AzureRmNetworkSecurityGroup).Tag  # produces the hashtable output
(Get-AzureRmNetworkSecurityGroup).Tags # Produces NULL

**Comment by markcowl** [comment]
Tag is the appropriate name for the property, many cmdlets have 'Tags' as an alias for backward compatibility

**Comment by lesterw1** [comment]
If this is the case, then why is this the ONLY cmdlet that I can find which returns .TAG instead of .TAGS?
