### ISSUE TITLE
can we create a vm image from an existing running vm without generalising the running vm 

### ISSUE THREAD

**Issue by nadeemhussain** [Azure/azure-powershell#4769]
while creating a vm image from an existing running vm , the process generalize the running vm and made it un-usable , can we create an image without doing generalization and not disturbing the running vm,

**Comment by cormacpayne** [comment]
@nibhat Hey Nitin, would you mind taking a look at this issue?

**Comment by nadeemhussain** [comment]
@nibhat  @cormacpayne  do we have any update on this

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
