### ISSUE TITLE
Add-AzureAccount - should accept a PSCredential

### ISSUE THREAD

**Issue by doctordns** [Azure/azure-powershell#477]
At present, if you run Add-AzureAccount, you are forced to sign in via a pair of windows (enter your user name, then enter your password in a separate window). 

I should be able to specify a pscredential and just pass that, eg:
$cred = Get-Credential tfl@foo.bar
Add-AzureAccount -Credential $Cred

In doing so, I should never see a GUI Screen.

**Comment by trondhindenes** [comment]
You sure you're running an updated module version? This has been supported for a while already.

**Comment by doctordns** [comment]
I should have been more precise.I want to use a Microsoft ID - the same one I use when I logon to the portal or specify when I use Add-AzureAccount!

Here's what I get when I try

PSH [C:\foo\gd scripts]: $CredAz = Get-Credential 
PSH [C:\foo\gd scripts]: Add-AzureAccount -Credential $CredAz
Add-AzureAccount : -Credential parameter can only be used with Organization ID credentials. For more information,
please refer to http://go.microsoft.com/fwlink/?linkid=331007&clcid=0x409 for more information about the difference
between an organizational account and a Microsoft account.
At line:1 char:1
+ Add-AzureAccount -Credential $credaz
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Profile.AddAzureAccount

**Comment by alexandair** [comment]
-Credential parameter in Add-AzureAccount supports only organizational (work and school) account, not Microsoft account.

**Comment by doctordns** [comment]
True - at present add-azureaccount only supports org accounts. I'm suggesting it should also support Microsoft account.

**Comment by stankovski** [comment]
@doctordns as was mentioned above this is by design. Microsoft ID does not support non-intercative flow.
