### ISSUE TITLE
Add Parameter for OS Disk Size

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#4772]
Add parameter for ```DiskSizeInGB```

**Comment by markcowl** [comment]
I don't believe this has come up in any of the tutorials.

**Comment by twitchax** [comment]
I think we should do this, but the priority is low right now.

**Comment by sergey-shandar** [comment]
New-AzureRmVM & New-AzureRmVmss ?

**Comment by sergey-shandar** [comment]
Pull request #5734
