### ISSUE TITLE
Microsoft.PowerShell.DSC 2.71.1.0: Using old version of DSC resource (that doesn't exist)

### ISSUE THREAD

**Issue by woter324** [Azure/azure-powershell#4775]
I can't find a direct reference to this extension on Git Hub and the [reference](https://blogs.msdn.microsoft.com/powershell/2014/11/20/release-history-for-the-azure-dsc-extension/) to changes is very old.

### Cmdlet(s)
Not a cmdlet. Onboarded to DSC using [template](https://github.com/Azure/azure-quickstart-templates/tree/master/dsc-extension-azure-automation-pullserver).

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
Version that is installed by DSC extension:
```
PS C:\> $PSVersionTable
Name                           Value                                                                                                                                                                       
----                           -----                                                                                                                                                                       
PSVersion                      5.1.14409.1005                                                                                                                                                              
PSEdition                      Desktop                                                                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                     
BuildVersion                   10.0.14409.1005                                                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                                                             
WSManStackVersion              3.0                                                                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                                                                         
SerializationVersion           1.1.0.1
```
### Module Version
Not a module as such. 2.71.1.0

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
Windows Server 2012 R2

### Description
As of yesterday, I have come across a new issue. having thoroughly checked VSTS, storage account and Automation Account holds the correct version (and only the correct version , my VMs are not getting the latest version of a DSC resource. 

I've checked all the files and places I can and it is correct, yet the VM gets an older version. This version doesn't exist in the storage account, so I am at a loss as to how or where it is getting it from. Is there a way to look at the files inside the Automation Account's module. Although the portal reports the correct version, there must be a discrepancy between the two. I am assuming it has something to do with the RegistrationURL (https://wcus-agentservice-prod-1.azure-automation.net/accounts/c16f66ea-268b-4ede-93aa-7de900a29125) but my attempts to get there have be thwarted.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
N/A

### Script/Steps for Reproduction
Something I'd have to show you.

Any further information you require, please get in touch.

**Comment by woter324** [comment]
I removed the aforementioned DSC resource from Automation, left it a few hours before re-importing. When running a completely new build, when the template starts to configure the Azure LCM, I get the following error:
```
New-AzureRmResourceGroupDeployment : 15:31:29 - Resource Microsoft.Compute/virtualMachines/extensions 'AUCADN102002055/Configure-DSC' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'Configure-DSC'. Error message: \"DSC Configuration 'ConfigureLCMforAAPull' completed with error(s). Following are the first few: Cannot find module hDynamicsAX_1.4.4.11 from the server 
https://wcus-agentservice-prod-1.azure-automation.net/accounts/c19f67ea-268b-4fee-92ac-7be810b28325/Modules(ModuleName='hDynamicsAX',ModuleVersion='1.4.4.11')/ModuleContent.\"."
      }
    ]
  }
}'
```
Module version 1.4.4.11 doesn't exist and I don't know where it is getting the value from as I haven't entered it anywhere.

**Comment by markcowl** [comment]
@woter324 I am not sure how this relates to Azure PowerShell.  Can you relate which Azure PowerShell component you are using, and how it is failing?

**Comment by woter324** [comment]
Hi @markcowl, This isn't a typical "Azure PowerShell" cmdlet as in those referenced [here](https://docs.microsoft.com/en-us/powershell/azure/overview?view=azurermps-4.4.0), e.g. Get-AzureRMResourceGroup or Get-AzureRmVM. This problem pertains to the Windows DSC VM extension (Microsoft.Powershell.DSC) - which is written in PowerShell, by Microsoft and deployed via template or `*-AzureRmVMDscExtension` 

I cannot find any GitHub reference to this VM extension (which may or may not be an intentional decision by MS) and this is the best place I can find to report such an issue.

**Comment by woter324** [comment]
So I have found the issue. I raised this under the wrong account, so I will close this and open a new one under the correct account:
[https://github.com/Azure/azure-powershell/issues/4844](https://github.com/Azure/azure-powershell/issues/4844)

@markcowl It's actually `Start-AzureRmAutomationDscCompilationJob` that caused the problem which I believe falls well and truely under "Azure PowerShell
