### ISSUE TITLE
New-AzureRmAutomationAccount lacks switch for 'Create Azure Run As Account'

### ISSUE THREAD

**Issue by lukeb1961** [Azure/azure-powershell#4777]
### Cmdlet(s)
New-AzureRmAutomationAccount
### PowerShell Version
$PSversiontable

Name                           Value                                                                                             
----                           -----                                                                                             
PSVersion                      5.1.16299.15                                                                                      
PSEdition                      Desktop                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                           
BuildVersion                   10.0.16299.15                                                                                     
CLRVersion                     4.0.30319.42000                                                                                   
WSManStackVersion              3.0                                                                                               
PSRemotingProtocolVersion      2.3                                                                                               
SerializationVersion           1.1.0.1  

### Module Version
(get-module azurerm).Version
Major  Minor  Build  Revision
-----  -----  -----  --------
4      3      1      -1  

### Description
in the portal, add an automation account. 
Create - there is the YES/NO box to 'Create Azure Run As Account'

New-AzureRmAutomationAccount  doesn't have a switch to match this.

**Comment by markcowl** [comment]
@vrdmr Can you take a look?

**Comment by seb2k** [comment]
The only way for now is to use this workaround: https://docs.microsoft.com/en-us/azure/automation/automation-create-runas-account

**Comment by PaoloRavina** [comment]
Is this functionality going to be added to New-AzAutomationAccount?

**Comment by ikanni** [comment]
Adding Create Azure Run As Account to New-AzAutomationAccount is not possible due to current design.
As a workaround, please use the PowerShell script documented  https://docs.microsoft.com/en-us/azure/automation/automation-create-runas-account
Closing the issue.
