### ISSUE TITLE
Get-AzureRmStorageAccountKey : 'accountName' exceeds maximum length of '24'.

### ISSUE THREAD

**Issue by RobertoPrevato** [Azure/azure-powershell#4781]
### Cmdlet(s)
Get-AzureRmStorageAccountKey

### PowerShell Version
```powershell
Name                           Value                                                                                                                                                                                    
----                           -----                                                                                                                                                                                    
PSVersion                      5.1.15063.608                                                                                                                                                                            
PSEdition                      Desktop                                                                                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                  
BuildVersion                   10.0.15063.608                                                                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                                                                          
WSManStackVersion              3.0                                                                                                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                                                                                                      
SerializationVersion           1.1.0.1
```

### Description
I can create a storage account with a name longer than 24 characters using ARM templates, no problem.
But when I call the command:
```powershell
Get-AzureRmStorageAccountKey -ResourceGroupName $rgName -AccountName $accountName 
```

It throws exception:
```
Get-AzureRmStorageAccountKey : 'accountName' exceeds maximum length of '24'.
```

### Script/Steps for Reproduction
Create a storage account with name longer than 24 characters in Azure. Try to run the command.

**Comment by markcowl** [comment]
@blueww can you take a look?

**Comment by alexandair** [comment]
![storage](https://user-images.githubusercontent.com/3135708/31562782-0083e7ac-b05d-11e7-8b81-1e589682c8a8.png)
Azure portal also has a limit of 24 characters for a storage name.

**Comment by RobertoPrevato** [comment]
@alexandair, I didn't check using the Azure portal, but I provisioned a storage account using an ARM template deployment, like I mentioned before. I created a storage account with a name like this one: "aaaaatestusestacc20171013" (length 25). Note: 5 letters from app name + environment (test) + region (use) + `stacc` (naming convention) + date. For sure it doesn't look right that validation is not consistent when deploying using ARM templates.

**Comment by RobertoPrevato** [comment]
About last two comments, so maybe this is actually a bug in the core logic that handles ARM templates deployment?

**Comment by blueww** [comment]
@RobertoPrevato  

Storage Account name length limitation is 3-24. Storage Account name longer than 24 is not valid.
You can see more details in: 
https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions

**Comment by RobertoPrevato** [comment]
@blueww 
Thanks, Wei. So, it means the problem is not in azure-powershell, but in the core logic that handles ARM deployment. Bug report here should be closed, and reported somewhere else (I don't know where, right now).

**Comment by kvitnickas** [comment]
I'm having problems with the validation after upgrading the module in Azure. I would argue that the validation on storage account name length must not be performed. It is/was possible to create storage accounts with longer names and I guess that quite a few users still have accounts with different length than it is documented. Hence the length specified on https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions is inaccurate and should not be followed. I cannot rename the storage account in all environments due to large number of dependencies and so I cannot use the cmdlet anymore

**Comment by blueww** [comment]
@kvitnickas 
Actually Powershell code don't do any length validate to the Account name length. The error is reported from server, so PowerShell can't overcome the issue.

Would you please contact support team, or open an incident for your problem to the related service team (should be Location Service team)?

**Comment by BurgerVanDan** [comment]
Has this been updated at all?

I am currently facing the same issue - created a storage account using ARM with name length of 28 characters successfully. When attempting to use the 'Remove-AzureRmStorageContainer' cmdlt but recieve the error "Remove-AzureRmStorageContainer : 'accountName' exceeds maximum length of '24'."

Any workarounds without renaming the storage account?

**Comment by alexandair** [comment]
It's not possible anymore to create a storage account with an invalid name (e.g. a name that exceeds maximum length of '24') using the ARM template.

**Comment by norman-v** [comment]
> It's not possible anymore to create a storage account with an invalid name (e.g. a name that exceeds maximum length of '24') using the ARM template.

I just created one recently via ARM templates -so clearly it's possible-and now I have to rename it since the PS module still gives this error.
