### ISSUE TITLE
[Experiments][Compute] New-AzVM should choose to enable BootDiagnostics by default.

### ISSUE THREAD

**Issue by huangpf** [Azure/azure-powershell#4797]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@huangpf thanks for the feedback, Pengfei. We will discuss this in a future experiments sync-up.

**Comment by sergey-shandar** [comment]
Related issue https://github.com/Azure/azure-powershell/issues/4735

**Comment by MiYanni** [comment]
@twitchax Investigate whether we need a switch/option for boot diagnostics.

**Comment by markcowl** [comment]
We would have to justify why we did this differently than the CLI, and seems like there is not enough justification for the documentation change.  Closing.
