### ISSUE TITLE
[Experiments][Compute] The new cmdlets like New-AzVM's implementation should target to re-use other cmdlets (i.e. New-AzureRmVMConfig, etc.)

### ISSUE THREAD

**Issue by huangpf** [Azure/azure-powershell#4800]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@huangpf Thanks for the feedback, Pengfei. We will discuss this with you in a future experiments sync-up.

**Comment by markcowl** [comment]
As discussed, these will be binary cmdlets, but will follow a pattern and define common code that will be usable elsewhere
