### ISSUE TITLE
Set-AzureStorageBlobContent is not working if FIPS is enabled. 

### ISSUE THREAD

**Issue by rgathub** [Azure/azure-powershell#4807]
### Cmdlet(s)
Set-AzureStorageBlobContent 

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1.15063.608   

### Module Version
3.4.1

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.15063.608     

### Description
Unable to upload files to BLOB Storage if FIPS is enabled. This also prevents me to do ARM deployments with Custom Script Extensions as that relies on the cmdlet Set-AzureStorageBlobContent .

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
DEBUG: 9:48:53 AM - NewAzureStorageContext begin processing with ParameterSet 'AccountNameAndKey'.
DEBUG: 9:48:53 AM - NewAzureStorageContext end processing.
DEBUG: 9:48:53 AM - Init Operation Context for 'SetAzureBlobContentCommand' with client request id  Azure-Storage-PowerShell-675d205d-ae74-4908-91b2-421df71b6c60. If you want to get more details, please add "-Debug" to your command.
DEBUG: 9:48:53 AM - SetAzureBlobContentCommand begin processing with ParameterSet 'SendManual'.
DEBUG: 9:48:53 AM - Use storage account 'strsspdiagnostics' from storage context.
Set-AzureStorageBlobContent : This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
At line:9 char:1
+ Set-AzureStorageBlobContent -File $File -Context $StorageContext -Con ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureStorageBlobContent], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.WindowsAzure.Commands.Storage.Blob.SetAzureBlobContentCommand

DEBUG: 9:48:53 AM - SetAzureBlobContentCommand end processing, Start 0 remote calls. Finish 0 remote calls. Elapsed time 120833.08 ms. Client operation id: Azure-Storage-PowerShell-675d205d-ae74-4908-91b2-421df71b6c60.
DEBUG: 9:48:53 AM - SetAzureBlobContentCommand end processing. 

### Script/Steps for Reproduction
$DebugPreference = "Continue"
$containter = "<ContainerName>"
$storageAccountName = "<StorageAccountName>"
$storageKey = "<StorageAccountKey>"

$File = "<FilePath>"
$StorageContext = New-AzureStorageContext -StorageAccountName $StorageAccountName -StorageAccountKey $storageKey
Set-AzureStorageBlobContent -File $File -Context $StorageContext -Container $containter

**Comment by cormacpayne** [comment]
@blueww Hey Wei, would you mind taking a look at this issue? It looks like the Storage library is doing some signing on the message and header that may be causing issues here.

**Comment by blueww** [comment]
@rgardler 
The failure is because we use MD5 to validate the content in each chunk to upload, and MD5 algorithm is not aligned with FIPS.

The content transfer is based on DMlib (https://github.com/Azure/azure-storage-net-data-movement), and as I know DMlib has  a way to resolve the conflict,  implement the way into PowerShell might can resolve the issue. 

I Will open a task to track it, and will implement it per our priority and bandwidth. 

Before the resolution is in PowerShell, can you try to use AzCopy to upload the blob, it has a way to work on FIPS enabled machine : (https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy#known-issues-and-best-practices).

**Comment by rgathub** [comment]
Thanks @blueww I am already using the workaround to get the files in blob storage but it will be great if this can be resolved too. 

Rahul Gupta

**Comment by utripathi** [comment]
Any update on the issue ?

**Comment by blueww** [comment]
@rgathub 

This issue still not resolved. The feature change design still not get agreed, and we also has some other higher priority work in hand. I will discuss with the PM for the issue.

**Comment by utripathi** [comment]
Thanks for the response . 
Waiting

**Comment by rgathub** [comment]
@blueww Thanks for the update.

**Comment by blueww** [comment]
Still discussing with PM, will update later.

**Comment by blueww** [comment]
@utripathi  @rgathub 

Would you please share the scenario of why use FIPS? It can help us to decide the priority of the issue. Do you enable it just for security reason, or to meet some policy requirement?

I have raise a PR for this issue, but please note:
1. The fix just use the native MD5 function, which can pass FIPS check, but actually the native MD5 function use same algorithm with managed MD5 function, so use it won't improve the security, but just to pass FIPS check.
2. FIPS is not recommended now per: https://blogs.technet.microsoft.com/secguide/2014/04/07/why-were-not-recommending-fips-mode-anymore/
2. The PR still need One SDK team review.

**Comment by rgathub** [comment]
@blueww I  use FIPS as a policy mandate as I work in a federal agency and there is no scope for getting exceptions.

**Comment by MiYanni** [comment]
The fix has been merged here: https://github.com/Azure/azure-powershell/pull/5746

**Comment by rgathub** [comment]
@MiYanni Thanks for fixing this.

**Comment by rgathub** [comment]
Then many thanks to @blueww .
