### ISSUE TITLE
Get-AzureRmWebApp: missing property 'Identity'

### ISSUE THREAD

**Issue by clericc** [Azure/azure-powershell#4808]
### Cmdlet(s)
Get-AzureRmWebApp, may be more

### PowerShell Version
5.1.15063.674

### Module Version
AzureRM.Websites 3.4.1

### OS Version
Win10

### Description
Since Managed Service Identities were introduced, REST Api outputs the property "identity" for WebApps with MSI enabled. This Property is not yet present in the output of the PowerShell cmdlet.

### Actual
```
PS> $app = Get-AzureRmWebApp -ResourceGroupName ... -Name ...
PS> $app.Identity
PS>
```

### Expected
```
PS> $app = Get-AzureRmWebApp -ResourceGroupName ... -Name ...
PS> $app.Identity
TenantId     : ...
PrincipalId  : ...
PS>
```

**Comment by cormacpayne** [comment]
@ahmedelnably Hey Ahmed, would you mind taking a look at this issue? It looks like the Websites SDK might need to be updated for your PowerShell cmdlets.

**Comment by nishanperera** [comment]
Any updates on this issue? Is there any workaround?

**Comment by nishanperera** [comment]
Workaround
$faSpn = Get-AzureRmADServicePrincipal -SearchString "[FunctionName]"
$faSpn.Id

**Comment by clericc** [comment]
Thats my current workaround as well ;)

**Comment by panchagnula** [comment]
This is fixed on our website-preview module you can follow instruction here to install https://github.com/Azure/azure-powershell/releases/tag/v5.0.0-preview-AzureRM.Websites
