### ISSUE TITLE
Set-AzureRmApiManagementApi : InternalServerError: Encountered internal server error

### ISSUE THREAD

**Issue by sarath-rachuri** [Azure/azure-powershell#4820]
### Cmdlet(s)
Set-AzureRmApiManagementApi

### PowerShell Version
4.0

### Module Version
3.4.0

### OS Version
6.3.9600.18773

### Description
Set-AzureRmApiManagementApi cmdlet failing with InternalServerError: Encountered internal server error.

### Debug Output

DEBUG: 6:11:05 PM - SetAzureApiManagementApi begin processing with ParameterSet '__AllParameterSets'.

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
InternalServerError

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : c1bbb33e-6c99-4fbe-8998-1f6652571386
x-ms-correlation-request-id   : c1bbb33e-6c99-4fbe-8998-1f6652571386
x-ms-routing-request-id       : SOUTHINDIA:20171020T124128Z:c1bbb33e-6c99-4fbe-8998-1f6652571386
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Connection                    : close
Cache-Control                 : no-cache
Date                          : Fri, 20 Oct 2017 12:41:27 GMT

Body:
{
  "error": {
    "code": "InternalServerError",
    "message": "Encountered internal server error. Diagnostic information: timestamp '20171020T124128Z', subscription id '56f61a0e-85ab-4e39-965f-6dd7ddd3baa
6', tracking id 'c1bbb33e-6c99-4fbe-8998-1f6652571386', request correlation id 'c1bbb33e-6c99-4fbe-8998-1f6652571386'."
  }
}

**Comment by cormacpayne** [comment]
@sarath-rachuri Hey Sarath, what were the parameters you used for this cmdlet call?

CC: @solankisamir

**Comment by solankisamir** [comment]
The request failed in the Azure FrontDoor and didn't even reach us. We are getting in touch with them.

**Comment by sarath-rachuri** [comment]
@cormacpayne @solankisamir This cmdlet is being used  for 2 times in the script. Once for updating the API name and this instance didn't fail. And the other instance for adding an OAuth Server to the API and this instance is failing. Below are the parameters that are passed to the cmdlet.

##adding OAuth Server to the API
Set-AzureRmApiManagementApi -Context $apimgmtContext -ApiId $newAPI.ApiId -Name $newAPI.Name -ServiceUrl $newAPI.ServiceUrl -Protocols @('Https') -AuthorizationServerId $authServer.ServerId -AuthorizationScope $authServer.DefaultScope

**Comment by sarath-rachuri** [comment]
The cmdlet is working. thanks.

**Comment by mahant-desai** [comment]
Facing same issue. Actually i am trying to run powershell script from ARM template, using the resource "Microsoft.Resources/deploymentScripts" and trying to pass my id as Identity just like below
```````````````````````````````````````````````
 "identity": {
    "type": "userAssigned",
    "userAssignedIdentities": {
      "/subscriptions/01234567-89AB-CDEF-0123-456789ABCDEF/resourceGroups/myResourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myID": {}
    }
  }
```````````````````````
