### ISSUE TITLE
Need a cmdlet to upload a p2s VPN Gateway root cert

### ISSUE THREAD

**Issue by doctordns** [Azure/azure-powershell#483]
At present there appears to be no cmdlet that can upload a Point-to-Site self-signed root cert needed for client access to the VNET.

**Comment by doctordns** [comment]
Any news??

**Comment by sphibbs** [comment]
https://docs.microsoft.com/en-us/powershell/module/azurerm.network/add-azurermvpnclientrootcertificate?view=azurermps-4.4.0

**Comment by doctordns** [comment]
Thanks

I’d quite forgotten that post!

Nice to see it’s done!
