### ISSUE TITLE
Unable to add extension for diagnostics for VMSS(Add-AzureRmVmssExtension,Add-AzureRmVmssDiagnosticsExtension)

### ISSUE THREAD

**Issue by girishgouda** [Azure/azure-powershell#4830]
### Cmdlet(s)
Add-AzureRmVmssExtension
Add-AzureRmVmssDiagnosticsExtension
REST API by adding the extension Json in https://resources.azure.com/
### Description
The comands 
execute successfully but the extension is always in the creating state as show in the attachment

### Script/Steps for Reproduction
Json used to set the public and protected setting 

`"extensionProfile": {
        "extensions": [
          {
            "properties": 
			{
              "publisher": "Microsoft.Azure.Diagnostics",
              "type": "IaaSDiagnostics",
              "typeHandlerVersion": "1.5",
              "autoUpgradeMinorVersion": true,
			  "settings": 
			  {
				  "WadCfg": {
					"DiagnosticMonitorConfiguration": {
					  "overallQuotaInMB": "50000",
					  "PerformanceCounters": {
						"PerformanceCounterConfiguration": [
						  {
							"annotation": [],
							"scheduledTransferPeriod": "PT1M",
							"counterSpecifier": "\\Processor(_Total)\\% Processor Time",
							"sampleRate": "PT1M"
						  },
						  {
							"annotation": [],
							"scheduledTransferPeriod": "PT1M",
							"counterSpecifier": "\\Memory\\% Committed Bytes in Use",
							"sampleRate": "PT1M"
						  }
						]
					  },
					  "Metrics": {
						"resourceId": "/subscriptions/4c2f7d26-38b1-45d2-bbe8-cf9eccf310ae/resourceGroups/vmss1/providers/Microsoft.Compute/virtualMachineScaleSets/vmss1",
						"MetricAggregation": [
						  { "scheduledTransferPeriod": "PT1H" },
						  { "scheduledTransferPeriod": "PT1M" }
						]
					  }
					}
				  },
				  "StorageAccount": "girishtestaccount"
				},
				"protectedSettings": {
                "storageAccountName": "girishtestaccount",
                "storageAccountKey": "K07vhafNHhXQ3Y/viT+E5i20csMQVfJmZvmTn9SCWgVrh4N0UCHW8yoBy+CJjhs3bvLhrEaqhrsPoToyHdLOxQ==",
                "storageAccountEndPoint": "https://core.windows.net"
                }
				
			},
			"type": "Microsoft.Compute/virtualMachineScaleSets/extensions",
			"name": "Microsoft.Insights.VMDiagnosticsSettings"
        }
    ]
}`

![test](https://user-images.githubusercontent.com/9015874/31864990-df683b98-b784-11e7-9ead-7a4ff0832fa7.PNG)

please let us know how to proceed and also  provide the documentation of using the commands. We are stuck with this issue and immedtaion attention or help is much appreciated

following code is  used to enable diagnostics

$resourceGroupName = "latest"
$resourceName ="vmssfinal"
$storageAccount = Get-AzureRmStorageAccount -ResourceGroupName $resourceGroupName -AccountName "finalstoragegirish"
$virtualMachineScaleSet = Get-AzureRmVmss -ResourceGroupName $resourceGroupName -VMScaleSetName $resourceName
$publicSetting = @{
					"WadCfg" = @{
						"DiagnosticMonitorConfiguration" = @{
							"overallQuotaInMB" = "50000"
							
                              "Metrics"= @{
						        "resourceId" = "/subscriptions/4c2f7d26-38b1-45d2-bbe8-cf9eccf310ae/resourceGroups/latest/providers/Microsoft.Compute/virtualMachineScaleSets/vmssfinal"
						        "MetricAggregation" = @(
						          @{ "scheduledTransferPeriod" = "PT1H" },
						          @{ "scheduledTransferPeriod" = "PT1M" }
						        )
					          }
						}
					}
					"StorageAccount" = $storageAccount.Id
				}

				$protectedSetting = @{
					storageAccountName = $storageAccount.Id
					storageAccountKey = "pzCLIJvj6XmDDC8j6EYdGFoAHRzizSG6RvedIfO2iksAFBioMHuOyWjE0fcNfeySxgN9Y1MFk2hC94Jxxl0dkw=="
					storageAccountEndPoint = "https://core.windows.net/"
				}
$extensionName = "VMDiagnosticsVmExt_$vmScaleSetName"

$null = Add-AzureRmVmssExtension -VirtualMachineScaleSet $virtualMachineScaleSet `
					-Name $extensionName `
					-Publisher "Microsoft.Azure.Diagnostics" `
					-Type "IaaSDiagnostics" `
					-Setting $publicSetting `
					-ProtectedSetting $protectedSetting `
					-TypeHandlerVersion "1.5" `
					-AutoUpgradeMinorVersion $True
				
$null = Update-AzureRmVmss -ResourceGroupName $resourceGroupName -Name $virtualMachineScaleSet.Name -VirtualMachineScaleSet $virtualMachineScaleSet

**Comment by girishgouda** [comment]
Is this issue looked upon? . This is critical issues for us . kindly update any findings on the same

**Comment by markcowl** [comment]
@danielsollondon Can you take a look

**Comment by cormacpayne** [comment]
@danielsollondon ping

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
