### ISSUE TITLE
Log Correlation Id in client side for AAD/Graph errors

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#4839]
### Cmdlet(s)
Add-AzureRMAccount and AD cmdlets

### Description

providing the correlation id  in the client side would be helpful as we could easily match with the server side logs to find out the errors. This may require some changes in the server side

**Comment by bganapa** [comment]
related https://github.com/Azure/azure-powershell/issues/4836

**Comment by markcowl** [comment]
This is included in the x-ms-client-request-id in the Insights telemetry.  Please re-open if this is not providing the information you need.
