### ISSUE TITLE
Return SiteConfig when getting all sites under a subscription or resource group

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-powershell#4841]
We could add a –Detailed or –Config parameter to return the full site with config in list scenarios, this way the user would opt in to any performance hit and/or request throttling.  This is similar to the way that VMs support Status, which similarly requires an additional API call.

Get-AzureRmWebApp | % {$_.SiteConfig}                                 ========== SiteConfig is empty
Get-AzureRmWebApp -Name JianyunBot| % {$_.SiteConfig}    ========== Good. has SiteConfig object
(Get-AzureRmWebAppSlot -name jianyun -ResourceGroupName jianyunrg). SiteConfig === empty

**Comment by panchagnula** [comment]
Adding siteConfig to the SiteObject is going to bloat up the payload & this behavior is consistent with our Arm calls & Azure CLI as well. We can add a new command for returning the configsettings of an App if needed
