### ISSUE TITLE
New-AzureRmSqlServer: Error message incorrect/misleading when trying to create an Azure SQL Server(NameAlreadyExists)

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#4845]
### Cmdlet(s)
New-AzureRmSqlServer

### PowerShell Version
5.1.14409.1012

### Module Version
Manifest   3.3.1      AzureRM.Sql

### OS Version
10.0.14409.1012

### Description

Below is the error message "**Long running operation failed with status 'Failed**" - which does not provide the actual error. The actual error "  "**NameAlreadyExists**" does show up only with -debug parameter in the command let.

New-AzureRmSqlServer -ServerName $SQLServerName -ResourceGroupName $ResourceGroupName -SqlAdministratorCredentials $SQLServerCredentials -Location $Location -ServerVersion "12.0"
New-AzureRmSqlServer : Long running operation failed with status 'Failed'.
At line:1 char:1
+ New-AzureRmSqlServer -ServerName $SQLServerName -ResourceGroupName $R ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmSqlServer], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.Server.Cmdlet.NewAzureSqlServer

### Debug Output

============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Retry-After                   : 15
x-ms-request-id               : c2fb9688-3cf5-45c-42c93b97770e
x-ms-ratelimit-remaining-subscription-reads: 14971
x-ms-correlation-request-id   : cbc9d09f-bf92-4-e43ace9e6ada
x-ms-routing-request-id       : EASTUS:20171024T145546Z:cbcf92-475b-a5c4-e43ace9e6ada
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Tue, 24 Oct 2017 14:55:45 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "name": "a1fb58de-5702-4ea9-xxxx2582c5657",
  "status": "Failed",
  "startTime": "2017-10-24T14:55:15.623Z",
  **"error": {
    "code": "NameAlreadyExists",
    "message": "The name '{0}' already exists. Choose a different name."
  }**
}

### Script/Steps for Reproduction

Try creating a sql server providing valid properties while passing an existing sqlservername for  -ServerName parameter

New-AzureRmSqlServer -ServerName $SQLServerName -ResourceGroupName $ResourceGroupName -SqlAdministratorCredentials $SQLServerCredentials -Location $Location -ServerVersion "12.0"

**Comment by cormacpayne** [comment]
@akromm @jaredmoo would you mind taking a look at this issue?

**Comment by jaredmoo** [comment]
This error message comes from Microsoft.Rest.ClientRuntime.Azure, and more recent versions of that shared library are showing the full error message. I believe the new version was pulled in by one of these changes in September: https://github.com/Azure/azure-powershell/commits/preview/tools/Common.Dependencies.targets

When I used the latest version of Azure PowerShell, I get the full message. @rajaprad can you please update to the latest version of Azure PowerShell and see if this works for you? Thanks :)

**Comment by rajaprad** [comment]
@jaredmoo - I got the below error message from the latest Azure Powershell Version.

New-AzureRmSqlServer : Long running operation failed with status 'Failed'. **Additional Info:'The name '{0}' already exists. Choose a different name.'**
This help - however can we pull out the actual value in place of **{0},** thanks!!

**Comment by jaredmoo** [comment]
Thanks for pointing this out, this is a server-side bug (it applies to all of our clients, not just powershell) that will be fixed in the near future. Cheers!

**Comment by MaximoTrinidad** [comment]
FYI - As of today - 02/10/2018 - This error still persist making the sample provided in Microsoft Documentation not workable.
**AzureRM.SQL version 5.2.0**

It still getting the same error:
```
		$MyUserName = "max_t";
		$MyPassword = ConvertTo-SecureString '$Adm1n!001' -asplaintext -force;
		$MyCred = new-object -typename System.Management.Automation.PSCredential `
							 -argumentlist $MyUserName, $MyPassword;
		
		New-AzureRmSqlServer -ResourceGroupName $resourcegroupname `
							 -Location $location `
							 -ServerName $servername `
							 -ServerVersion "12.0" `
							 -SqlAdministratorCredentials $MyCred;

##Error##
New-AzureRmSqlServer : Long running operation failed with status 'Failed'. Additional Info:'The name '{0}'   
already exists. Choose a different name.'                                                                    
At line:1 char:3                                                                                             
+   New-AzureRmSqlServer -ResourceGroupName $resourcegroupname `                                             
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                             
    + CategoryInfo          : CloseError: (:) [New-AzureRmSqlServer], CloudException                         
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.Server.Cmdlet.NewAzureSqlServer                   
                                                                                                             
PS [214] >
```
Is there any workaround in the future?

:)

**Comment by cormacpayne** [comment]
@jaredmoo Hey Jared, do you know if this issue has been resolved?

**Comment by MaximoTrinidad** [comment]
@cormacpayne @jaredmoo 

I just tested both in Windows PowerShell and PowerShell Core (Linux). 
It seems to work now.

Good Job!!

![azurermsql_2018-07-11_9-33-17](https://user-images.githubusercontent.com/19892435/42574873-816da2b2-84ed-11e8-803f-f7a4cdc30af9.jpg)

**Comment by cormacpayne** [comment]
@MaximoTrinidad thanks for the verification Maximo 😀
