### ISSUE TITLE
add new method for adding UA only if it does not exist

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-powershell#485]
The current .Add method for adding UA string will add unconditionally, even if it already exists.  Scripts that use this then can end up continually adding and hit the limit.  We need a method that will add the string only if it's not already part of the UA.  Ogail recommended a new method, e.g. AddUserAgent that would handle this:

$UserAgentString = New-Object -TypeName System.Net.Http.Headers.ProductInfoHeaderValue -ArgumentList 'UserAgent', '1.0'
[Microsoft.Azure.Common.Authentication.AzureSession]::ClientFactory.AddUserAgent($UserAgentString)

As a P2, we should also have a method to remove the string once a script if finished.

**Comment by bmoore-msft** [comment]
Wanted to add...

Another approach would be to pick up the contents of an env variable, this approach would be much simpler for callers but they would have to manage existence, e.g.

if ($env:UA -inotmatch 'foo/1.0') {$env:UA += ';foo/1.0'}

P2 for removal would be simple.

**Comment by stankovski** [comment]
This is implemented in the dev brunch.
