### ISSUE TITLE
Create separate folder per module containing scripts to be executed on import

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#4855]
Along with the work being done for issue https://github.com/Azure/azure-powershell/issues/3972, create a separate folder per module that will contain scripts that should be executed when the module is imported (_e.g.,_ startup scripts that load aliases and default resource groups). Make sure the folder is copied to the output directory and the functionality of the scripts is included in the .psm1 file that is created in the [`UpdateModules.ps1`](https://github.com/Azure/azure-powershell/blob/preview/tools/UpdateModules.ps1#L24) script.

**Comment by maddieclayton** [comment]
Fixed.
