### ISSUE TITLE
Issue with Enable Replication for Azure Site Recovery

### ISSUE THREAD

**Issue by shubhamgupta514** [Azure/azure-powershell#4866]
Hi,

I am developed the attached script for enabling replication from Vmware(on-premise) to Azure.
But I am not getting any response after invoking the rest api and when I check the replication items in azue portal, the protected item is there and trying to enable the replication but somehow it is getting failed with a  error on Mobility service installation and preparing target step even the Mobility service is already installed on the source server and registered with configuration server.

Note: - There is not issue with the environment setup as I have already tested the replication with the help azure portal.

Please refer the screenshot for error.

[Enable-ReplicationVMwareToAzure.zip](https://github.com/Azure/azure-
![image](https://user-images.githubusercontent.com/12984945/32089366-322b6ab4-bb07-11e7-8fcd-34618d89cf47.png)
powershell/files/1420874/Enable-ReplicationVMwareToAzure.zip)

**Comment by shubhamgupta514** [comment]
Hi Shahabhjeet,

Did you take a look into the script?

Thanks,
Shubham Gupta

**Comment by markcowl** [comment]
@shubhamgupta514 I don't believe this fucntionality is due to be released until 11/7.  Assigning to the SiteRecovery team to verify.

**Comment by markcowl** [comment]
@viverm can you take a look?

**Comment by shubhamgupta514** [comment]
@markcowl  I am facing the same error for unplanned failover api on shutting down the source VM step. Please verify that also.

**Comment by viverm** [comment]
@shubhamgupta514    
Method ASR-EnableReplicationAPI  used in script is not present in zip .

[Try adding  agent-authentication in header](https://social.msdn.microsoft.com/Forums/en-US/1389eb33-611d-4dd2-893c-de6168f79c32/resful-api-add-vcenter-to-configuration-fail-with-error-code-31255-the-same-action-is-working-fine?forum=hypervrecovmgr)

**Comment by shubhamgupta514** [comment]
[Enable-ReplicationVMwareToAzure.txt](https://github.com/Azure/azure-powershell/files/1430902/Enable-ReplicationVMwareToAzure.txt)

Please find the attached script.

@viverm authentication header is already added in the script.

[Enable-ReplicationVMwareToAzure.zip](https://github.com/Azure/azure-powershell/files/1430896/Enable-ReplicationVMwareToAzure.zip)

**Comment by shubhamgupta514** [comment]
@viverm  Authentication header is already added

**Comment by shubhamgupta514** [comment]
please find the attached script
[Enable-ReplicationVMwareToAzure.txt](https://github.com/Azure/azure-powershell/files/1430905/Enable-ReplicationVMwareToAzure.txt)
