### ISSUE TITLE
[AzureRM.Netcore] Old brand (Windows Azure) is used on login screens

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#4882]
When you follow the instruction "To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code E8DSVGG3M to authenticate." after you run Login-AzureRmAccount, this is what you see in your browser. Old brand "Windows Azure" is used 3 times.

![login](https://user-images.githubusercontent.com/3135708/32153976-f505039e-bd03-11e7-867a-289556210a96.png)
![login2](https://user-images.githubusercontent.com/3135708/32153977-f50eebb6-bd03-11e7-856e-df940ae1830f.png)

**Comment by markcowl** [comment]
@twitchax @sphibbs This is abotu the metadata in the first party app for Azure PowerShell.  Can one of you take  alook at updating.

**Comment by sphibbs** [comment]
The service principal for orgs contain the metadata from when it was created. Currently there is no good way to update. We could create a new AAD app so service principal's are created. I have reached out to the AAD team via

**Comment by twitchax** [comment]
This was addressed externally by ADAL across the board for multiple products, closing.
