### ISSUE TITLE
ARM: Test-AzureName is missing

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#489]
I should not be forced to switch back to Service Management to test for Azure name availability.
Test-AzureName is needed in both modes.

**Comment by singhkay** [comment]
Hey @alexandair you're right. There shouldn't be a need to switch. There's active discussion going on internally for bringing this cmdlet to the ARM mode.

**Comment by stankovski** [comment]
We are working on eliminating Switch-AzureMode command. See discussion here: https://github.com/Azure/azure-powershell/issues/428

**Comment by doctordns** [comment]
This cmdlet still seems missing from AzureRM. Is there any intention in bringing this cmdlet in the ARM module? If not what is the best way to check if a storage account already exists.
