### ISSUE TITLE
Documentation for Get-AzureRMWebApp has invalid example and missing output

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4902]
### Cmdlet(s)
Get-AzureRMWebApp

### Module Version
Current release

### Description
Reported by customers via LiveFyre.

The example shows `-SlotName` parameter but that is not a valid parameter. Please provide an appropriate example.

Also, there is no documentation for the output object.

**Comment by cormacpayne** [comment]
@ahmedelnably Hey Ahmed, would you mind taking a look at this issue? Looks like a quick documentation update
