### ISSUE TITLE
Get-AzureRmStorageAccount missing output documentation

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4903]
### Cmdlet(s)
Get-AzureRmStorageAccount

### Module Version
Current release 

### Description
Reported by customer via LiveFyre.

Please update this to indicate the [OutputType()] of the cmdlet

**Comment by cormacpayne** [comment]
@blueww Hey Wei, would you mind taking a look?

**Comment by blueww** [comment]
@markcowl , @cormacpayne 

I see in following link, there are really no Output section:
https://docs.microsoft.com/en-us/powershell/module/azurerm.storage/get-azurermstorageaccount?view=azurermps-4.4.1

But in my help *.md file, there is section OUTPUTS:
https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Storage/Commands.Management.Storage/help/Get-AzureRmStorageAccount.md

So why the outputs section is not built into the document page?
As I review the help doc, I see the DataPlane storage cmdelts help have output , like [link](https://docs.microsoft.com/en-us/powershell/module/azure.storage/stop-azurestorageblobcopy?view=azurermps-4.4.1). But the Resource mode cmdelts don't have output/input section. Do you know why?

**Comment by cormacpayne** [comment]
@sdwheeler @blueww I believe this has something to do with the `INPUTS` section being empty, and it's causing the `OUTPUTS` section to be skipped when creating the web page for this cmdlet. I will open a PR to update all markdown files with empty `INPUTS` section to have the following:

```
## INPUTS

### None

This cmdlet does not accept any input.

```

**Comment by blueww** [comment]
@cormacpayne 
Thanks for the fix! Let's see if it will be fixed in the next release.

**Comment by cormacpayne** [comment]
@sdwheeler @blueww okay, it looks like this will finally be resolved in the upcoming release of Azure PowerShell (version 6.0.0) 😀
