### ISSUE TITLE
ARM: Get-AzureCheckDnsAvailability should not expect a short name of an Azure location

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#491]
Get-AzureCheckDnsAvailability has the -Location parameter. You would think that you need to specify "West US" or "West Europe" as you do we other cmdlets, but that would give you an error:

```
PS C:\> Get-AzureCheckDnsAvailability -DomainQualifiedName azugbetest -Location "West Europe"
Get-AzureCheckDnsAvailability : InvalidHostNameFormat: The resource name 'West Europe' is invalid. It must be a valid host name.
```
Expected values are "westus", "westeurope". :( A user should never care about that "short form" of an Azure location, just because that's the way how it's used in a URL. 

Btw, I would expect Get-AzureCheckDnsAvailability to be called Test-AzureCheckDnsAvailability similar to Test-AzureName.

**Comment by creadle** [comment]
I agree with the main point.

I would add, that changing the verb to Test makes the Check in the noun portion redundant.

Also, is there an internal Azure DNS searching efficiency to knowing the location?  Because once mycoolcloudapp.cloudapp.net is taken, it doesn't really matter what the location is, correct?

**Comment by alexandair** [comment]
We are talking about virtual machine v2 created using ARM API. Its DNS name is different that VM v1. It's in a form like : azugbetest.westeurope.cloudapp.azure.com
A location is part of the DNS name, so the location matters.

You are right about the "Check" part. My mistake. Test-AzureDnsAvailability, then. :)

**Comment by singhkay** [comment]
Adding @jtuliani for this feedback

**Comment by jtuliani** [comment]
Agree the name should be Test-AzureDnsAvailability.
Will pass on the feedback regarding how locations are specified.

**Comment by DeepakRajendranMsft** [comment]
Thanks for pointing it out. These are being fixed in the upcoming release.

**Comment by markjbrown** [comment]
Fixed in prior release. Closing.
