### ISSUE TITLE
Reuse Active Directory Credentials for making manual requests.

### ISSUE THREAD

**Issue by mvanotti** [Azure/azure-powershell#492]
Some Azure Methods are not supported by Azure Powershell, for example, [the api call to get the principals of an account](https://msdn.microsoft.com/en-us/library/azure/dn469420.aspx).

There are ways to [reuse the azure active directory credentials](http://blogs.technet.com/b/keithmayer/archive/2014/12/30/authenticating-to-the-azure-service-management-rest-api-using-azure-active-directory-via-powershell-list-azure-administrators.aspx), but they are hard to use. It would be nice to support a method like **Get-AzureAuthenticationHeader** that can be used to make the REST request that are not supported.

**Comment by devigned** [comment]
Interesting. @matt-gibbs thoughts?

**Comment by pcgeek86** [comment]
@devigned VERY interested in this. Another example of where this would be incredibly useful is to call the REST API for adding VPN certificates on a Virtual Network, revoke them, et al.

**Comment by mvanotti** [comment]
It is unfair to expect the team to implement all the API Calls, this looks like a good solution.. If you want to make an API Call, you can just reuse the sdk credentials.

**Comment by stankovski** [comment]
Thank you for the feeback. To get yourself unblocked please use the [Common.Authentication](https://www.nuget.org/packages/Microsoft.Azure.Common.Authentication/1.0.26-preview) package directly. This line will return the raw token object (https://github.com/Azure/azure-sdk-for-net/blob/master/src/Authentication/Common.Authentication.Tests/ClientFactoryTests.cs#L93).

As far as getting service principal you can use Get-AzureADServicePrincipal cmdlet.
