### ISSUE TITLE
Stack - ActiveDirectoryServiceEndpointResourceId is being converted to System.Uri while this has to be treated as string always

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#4925]
This impact only the azurestack environments which has the ResourceID of the the form https;//abc

I see that ActiveDirectoryServiceEndpointResourceId is being converted to System.URI here.  https://github.com/Azure/azure-powershell/blob/f34c546fea58d48819e968cab9ac3dd5c50551f3/src/Common/Commands.Common.Authentication/Factories/AuthenticationFactory.cs#L254

System.Uri is weirdly adding the extra slash if the URI is of the form https://abc  and it does not add the extra slash if it is of the form https://abc/abc. In any case, this should not be converted to URI as ADAL expects this to be a string

**Comment by markcowl** [comment]
@bganapa Need a covering test for this scenario

**Comment by bganapa** [comment]
This affected only the development environment where we worked around the issue. It is not affecting any production environments, keeping it low pri

**Comment by bganapa** [comment]
Closing this as it is not affecting any prod environments
