### ISSUE TITLE
Add-AzureRmServiceFabricNodeType :ClusterUpgradeFailed, Message:Cluster upgrade failed. Reason Code: 'Interrupted

### ISSUE THREAD

**Issue by DarthScottius** [Azure/azure-powershell#4926]
### Cmdlet(s)
Add-AzureRmServiceFabricNodeType
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1.16299.19
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.16299.19
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
Failing on the call to 
"PUT",
  "url": "https://management.azure.com/subscriptions/<subId>/resourceGroups/<RG>/providers/Microsoft.Network/virtualNetworks/<vnet>/subnets/<subnet>?api-version=2016-09-01"
{
  "properties": {
    "addressPrefix": "10.0.1.0/24"
  }
}
This occurs with 10.0.x.0/24 where x == 1 - 6
response:
{
  "statusCode": "BadRequest",
  "serviceRequestId": "30aded45-e5ba-44b8-8614-620d931f7e57",
  "statusMessage": "{\"error\":{\"code\":\"NetcfgInvalidSubnet\",\"message\":\"Subnet '<subnet>' is not valid in virtual network '<vnet>'.\",\"details\":[]}}"
}
Looking at source this makes sense:

CreateNetworkResource

…..
            while (retry-- >= 0)
            {
                try
                {
                    subnet = NetworkManagementClient.Subnets.CreateOrUpdate(
                       this.ResourceGroupName,
                       virtualNetwork,
                       string.Format("{0}-{1}", subsetName, start),
                       new Subnet()
                       {
                           AddressPrefix = string.Format("10.0.{0}.0/24", start++) <-------------- Hard coded ips
                       });

                    network.Subnets.Add(subnet);
                    network = NetworkManagementClient.VirtualNetworks.CreateOrUpdate(
                        this.ResourceGroupName,
                        virtualNetwork,
                        network);

                    this.addressPrefix = subnet.AddressPrefix;
                    break;
                }

……

If we look at the customer’s vnet it's address is 10.27.16.0/21 
We can see that the requested subnet range doesn’t match that vnet address.

**Comment by markcowl** [comment]
@QingChenmsft Can you take  alook?

**Comment by vaishnavk** [comment]
This is a known issue and we are working on a fix for this. 

@juhacket - FYI

**Comment by juhacket** [comment]
This is fixed starting in AzureRM.ServiceFabric 0.3.2 (Azure PowerShell 5.5.0).
https://github.com/Azure/azure-powershell/pull/5576
