### ISSUE TITLE
New-AzureRmAvailabilitySet documentations should include list of valid values for the Sku parameter

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4928]
### Cmdlet(s)
New-AzureRmAvailabilitySet

### Module Version
Current

### Description
Customer question from LiveFyre.

> What are the allowed values for the -Sku parameter?

The current descriptions for the Sku parameter is:

    The Name of Sku

Need a better description. Which Sku? What are the possible values?

**Comment by markcowl** [comment]
@smotwani Can you take a look?  This seems like a good candidate for an argument completer

**Comment by cormacpayne** [comment]
This has been fixed.
