### ISSUE TITLE
Get-AzureRmSubscription documentation of returned fields is incorrect

### ISSUE THREAD

**Issue by SteGriff** [Azure/azure-powershell#4935]
### Cmdlet(s)

 * `Get-AzureRmSubscription`

### PowerShell Version

 * N/A, but it's 5.1.15063.674     

### Module Version

 * Tested on 2.1.0 and 4.2.0. Issue affects probably 4.x and later.

### OS Version

* N/A, but it's 10.0.15063.674

### Description

I have Module version 2.1.0 on one machine and 4.2.0 on another. When I run `Get-AzureRmSubscription` on 2.1.0, the field names are:

	SubscriptionName
	SubscriptionId
	TenantId
	State

On 4.2.0, they are: 

	Name
	Id
	TenantId
	State

In the [docs for Get-AzureRmSubscription][docs], the returned fields are listed as:

	Subscription Name
	SubscriptionId
	TenantId

This documentation is not correct for either version. When I change the documentation version, the stated output field names do not change.

**I would like to fix this documentation** but I don't understand how the versioned documentation is driven by GitHub. **Is it branch based?**

Furthermore, if anyone knows which version changed the field outputs from `SubscriptionName` to `Name`, this would be very helpful.

### Debug Output

Not applicable to this documentation-related issue.

### Steps for Reproduction

 1. Run `Get-AzureRmSubscription` on Module Version 2.x
 2. Run `Get-AzureRmSubscription` on Module Version 4.x
 3. Compare and contrast with [the documentation][docs] for those versions.

[docs]: https://docs.microsoft.com/en-us/powershell/module/azurerm.profile/get-azurermsubscription?view=azurermps-4.4.1

**Comment by cormacpayne** [comment]
@SteGriff Hey Stephen, thanks for reporting this issue! I believe in the 4.0.0 version of Azure PowerShell, we changed the property names for the `PSAzureSubscription` object that is returned from `Get-AzureRmSubscription`, but we did not update the examples in the help for the cmdlet.

Unfortunately, we can't update the help for previously released versions of Azure PowerShell (at least not for the help that shows up for `Get-Help` in PowerShell), but we can quickly update this help for all versions moving forward. If you would like to contribute the fix, the `Edit` button on the right side of the `Get-AzureRmSubscription` docs page will redirect you to the corresponding markdown file in this repository. You can then edit that file and open a pull request (targeting the `preview` branch) to make the change. We can also make the change if you would like ☺️

**Comment by markcowl** [comment]
Fixed in latest version: https://docs.microsoft.com/en-us/powershell/module/azurerm.profile/get-azurermsubscription?view=azurermps-5.1.1
