### ISSUE TITLE
New-AzureRmServiceBusQueue returns BadRequest when setting MaxSizeInMegabytes

### ISSUE THREAD

**Issue by kristofdaems** [Azure/azure-powershell#4938]
### Cmdlet(s)
New-AzureRmServiceBusQueue

### PowerShell Version
5.1.16299.19

### Module Version
4.4.1

### OS Version
10.0.16299.19

### Description
When I want to add a queue to my service bus subscription with a specific size (parameter MaxSizeInMegabytes) it results in bad request. When I drop the MaxSizeInMegabytes parameter it works.

### Debug Output
DEBUG: AzureQoSEvent: CommandName - New-AzureRmServiceBusQueue; IsSuccess - False; Duration - 00:00:02.6919184; Exception - Microsoft.Azure.Management.Service
Bus.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.ServiceBus.QueuesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ServiceBus.QueuesOperationsExtensions.<CreateOrUpdateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ServiceBus.QueuesOperationsExtensions.CreateOrUpdate(IQueuesOperations operations, String resourceGroupName, String namespace
Name, String queueName, SBQueue parameters)
   at Microsoft.Azure.Commands.Servicebus.ServiceBusClient.CreateUpdateQueue(String resourceGroupName, String namespaceName, String queueName, QueueAttributes
 queue)
   at Microsoft.Azure.Commands.ServiceBus.Commands.Queue.NewAzureRmServiceBusQueue.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 09:32:27 - NewAzureRmServiceBusQueue end processing.

### Script/Steps for Reproduction
Execute New-AzureRmServiceBusQueue -ResourceGroup $resourceGroup -NamespaceName $namespace -QueueName $queueName -EnablePartitioning $true -MaxSizeInMegabytes 16384 -DeadLetteringOnMessageExpiration $true

**Comment by kristofdaems** [comment]
Found the issue myself:
The property MaxSizeInMegabytes, must be one of the following values: 1024;2048;3072;4096
;5120

It might be good to have this info available in the documentation...

**Comment by markcowl** [comment]
@teitchax Can we find the appropriate service member for Scheduler to resolve this?  Seems liek this should either be a ValidateSet, or in the docs.

**Comment by kristofdaems** [comment]
There is an extra incoherence with the MaxSizeInMegabytes parameter, the allowed values used in the cmdlet don't seem to be Megabytes:
1024 in cmdlet-> 16GB in portal
4095 in cmdlet -> 64GB in portal

**Comment by benbelow** [comment]
@kristofdaems were you using partitioned topics? I've run into a similar confusion, and it's the same creating a topic from the portal itself - selecting 1GB will show up as 16GB. 

I believe this is because partitioned topics are split into 16 partitions, each with the max size specified. See https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-partitioning for confirmation 😄

**Comment by quartelh** [comment]
The factor 16 in the MaxSizeInMegabytes property valueis very confusing, and not really functional.

I specify a queue with partitioning with 1024 MB max size (using -MaxSizeInMegabytes 1024), the resulting object shows the 16 fold value in MaxSizeInMegabytes.  That is not what I provided.

**Comment by cormacpayne** [comment]
@v-Ajnava Hey Ajit, would you mind taking a look at this issue?

**Comment by v-Ajnava** [comment]
I have updated the help message of MaxSizeInMegabytes parameter with "MaxSizeInMegabytes - the maximum size of the queue in megabytes, which is the size of memory allocated for the queue.Default is 1024. Max for Standard SKU is 5120 and for Premium SKU is 81920, Allowed values : 1024, 2048, 3072, 4096, 5120, 10240, 20480, 40960, 81920"

**Comment by v-Ajnava** [comment]
changes are merged and will be in avaliable in release scheduled on  06/18/2019

**Comment by markcowl** [comment]
Cloaing as the fix is merged
