### ISSUE TITLE
Set-AzureRmSchedulerServiceBusTopicJob : A valid value for QueueName required for ServiceBus Queue action job.

### ISSUE THREAD

**Issue by ironicLemon** [Azure/azure-powershell#4939]
### Cmdlet(s)
Set-AzureRmSchedulerServiceBusTopicJob

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
 5.1.15063.674 

### Module Version
0.15.7

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.15063.674

### Description
Calling the cmdlet give the error:
Set-AzureRmSchedulerServiceBusTopicJob : A valid value for QueueName required for ServiceBus Queue action job.

But QueueName is not a parameter or valid value here, I'm attempting to update a ServiceBusTopicJob

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-burst-remaining-scheduler-reads: 242
x-ms-request-id               : ee5a2e8d-ca03-4b33-aac3-df25d4c468c5
x-ms-ratelimit-remaining-subscription-reads: 14883
x-ms-correlation-request-id   : xxxxxxxx
x-ms-routing-request-id       : UKSOUTH:20171108T085424Z:53xxx-xxx-xxx-xxx
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Wed, 08 Nov 2017 08:54:23 GMT
Server                        : Microsoft-IIS/8.5
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/xxx-xxx-xxxx-xxx/resourceGroups/infrastructurelive/providers/Microsoft.Sch
eduler/jobCollections/pentest1/jobs/activityreporting",
  "type": "Microsoft.Scheduler/jobCollections/jobs",
  "name": "pentest1/activityreporting",
  "properties": {
    "startTime": "2017-09-20T12:24:53.6951682Z",
    "action": {
      "serviceBusTopicMessage": {
        "topicPath": "activityreporting",
        "namespace": "ddelivebus",
        "transportType": "amqp",
        "authentication": {
          "sasKeyName": "activityreportingpolicycreator",
          "type": "sharedAccessKey"
        },
        "message": "servicebus notification",
        "brokeredMessageProperties": {},
        "customMessageProperties": {
          "databaseId": "live",
          "collectionId": "multi",
          "partitionKey": "username",
          "username": "pentest1"
        }
      },
      "type": "ServiceBusTopic",
      "retryPolicy": {
        "retryType": "fixed",
        "retryInterval": "01:00:00",
        "retryCount": 3
      }
    },
    "recurrence": {
      "frequency": "week",
      "interval": 1,
      "schedule": {
        "minutes": [
          1
        ],
        "hours": [
          0
        ],
        "weekDays": [
          "monday",
          "tuesday",
          "wednesday",
          "thursday",
          "friday"
        ]
      }
    },
    "state": "enabled",
    "status": {
      "lastExecutionTime": "2017-11-08T00:01:53.6209464Z",
      "nextExecutionTime": "2017-11-09T00:01:53Z",
      "executionCount": 35,
      "failureCount": 0,
      "faultedCount": 0
    }
  }
}

Set-AzureRmSchedulerServiceBusTopicJob : A valid value for QueueName required for ServiceBus Queue action job.
At C:\DDE\Deployment\Deployment\Environments\DR\Switch-SchedulersHelper.ps1:16 char:5
+     Set-AzureRmSchedulerServiceBusTopicJob -ResourceGroupName $schedu ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmSchedulerServiceBusTopicJob], PSArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Scheduler.Cmdlets.UpdateAzureSchedulerServiceBusTopicJobComma 
   nd
 
DEBUG: AzureQoSEvent: CommandName - Set-AzureRmSchedulerServiceBusTopicJob; IsSuccess - False; Duration - 00:00:19.328
9909; Exception - System.Management.Automation.PSArgumentException: A valid value for QueueName required for ServiceBu
s Queue action job.
   at Microsoft.Azure.Commands.Scheduler.Utilities.SchedulerClient.GetServiceBusQueue(PSServiceBusParams serviceBusQue
ueActionParams) in D:\workspace\powershell-sign\src\ResourceManager\Scheduler\Commands.Scheduler\Utilities\SchedulerCl
ient\SchedulerClient.CreateJob.cs:line 374
   at Microsoft.Azure.Commands.Scheduler.Utilities.SchedulerClient.PopulateJobAction(PSJobActionParams jobActionParams
, JobAction& jobAction) in D:\workspace\powershell-sign\src\ResourceManager\Scheduler\Commands.Scheduler\Utilities\Sch
edulerClient\SchedulerClient.CreateJob.cs:line 169
   at Microsoft.Azure.Commands.Scheduler.Utilities.SchedulerClient.GetExistingJobAction(PSJobActionParams updateJobAct
ionParams, JobAction existingJobAction) in D:\workspace\powershell-sign\src\ResourceManager\Scheduler\Commands.Schedul
er\Utilities\SchedulerClient\SchedulerClient.UpdateJob.cs:line 158
   at Microsoft.Azure.Commands.Scheduler.Utilities.SchedulerClient.GetExistingJobPropertiesParams(PSJobParams updateJo
bParams, JobProperties existingJobProperties) in D:\workspace\powershell-sign\src\ResourceManager\Scheduler\Commands.S
cheduler\Utilities\SchedulerClient\SchedulerClient.UpdateJob.cs:line 81
   at Microsoft.Azure.Commands.Scheduler.Utilities.SchedulerClient.PopulateExistingJobParams(PSJobParams updateJobPara
ms, JobDefinition existingJobDefinition) in D:\workspace\powershell-sign\src\ResourceManager\Scheduler\Commands.Schedu
ler\Utilities\SchedulerClient\SchedulerClient.UpdateJob.cs:line 70
   at Microsoft.Azure.Commands.Scheduler.Utilities.SchedulerClient.UpdateJob(PSJobParams updateJobParams) in D:\worksp
ace\powershell-sign\src\ResourceManager\Scheduler\Commands.Scheduler\Utilities\SchedulerClient\SchedulerClient.UpdateJ
ob.cs:line 55
   at Microsoft.Azure.Commands.Scheduler.Cmdlets.UpdateAzureSchedulerServiceBusTopicJobCommand.<>c__DisplayClass64_0.<
ExecuteCmdlet>b__0() in D:\workspace\powershell-sign\src\ResourceManager\Scheduler\Commands.Scheduler\Cmdlets\UpdateAz
ureSchedulerServiceBusTopicJobCommand.cs:line 152
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(String processMessage, String targe
t, Action action) in D:\workspace\powershell-sign\src\Common\Commands.Common\AzurePSCmdlet.cs:line 627
   at Microsoft.Azure.Commands.Scheduler.Cmdlets.UpdateAzureSchedulerServiceBusTopicJobCommand.ExecuteCmdlet() in D:\w
orkspace\powershell-sign\src\ResourceManager\Scheduler\Commands.Scheduler\Cmdlets\UpdateAzureSchedulerServiceBusTopicJ
obCommand.cs:line 155
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord() in D:\workspace\powershell-sign\s
rc\Common\Commands.Common\AzurePSCmdlet.cs:line 639;
DEBUG: Finish sending metric.
DEBUG: 8:54:38 AM - UpdateAzureSchedulerServiceBusTopicJobCommand end processing.
DEBUG: 8:54:38 AM - UpdateAzureSchedulerServiceBusTopicJobCommand end processing.

**Comment by markcowl** [comment]
@twitchax Can you find an appropriate contact on the scheduler team to look at this issue?

**Comment by cormacpayne** [comment]
@derek1ee Hey Derek, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment]
Closing as the Scheduler module no longer ships with `Az`.
