### ISSUE TITLE
Get-AzureEndpoints loses information about the VM

### ISSUE THREAD

**Issue by mvanotti** [Azure/azure-powershell#494]
It would be handy to be able to not lose the information about a VM after piping it to `Get-AzureEndpoint`.

For example, a call like: `Get-AzureVM | Get-AzureEndpoint` (list all the endpoints of all the VMs), will just show all the endpoints and no information about which VM corresponds to each one.

I'm suggesting to keep the VM information in the resulting output, or to be able to get a VM object that has access to all its endpoints too.

**Comment by markcowl** [comment]
@mvanotti Thank you for the report, routing to the appropriate team for investigation

**Comment by pcgeek86** [comment]
@mvanotti It isn't "losing" any information about the VM. An input endpoint is an independent object that can be applied to any Virtual Machine.

You should do this instead:

```
$VM = Get-AzureVM -ServiceName asdf -Name asdf
$VM.VM.ConfigurationSets.InputEndpoints
$VM.Name; ### I still have the VM's name here
```

This is just a matter of understanding the Azure Virtual Machine object model.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by singhkay** [comment]
Thanks @pcgeek86. Closing the issue, @mvanotti feel free to reopen if this is still an issue
