### ISSUE TITLE
Create reservation not supported in powershell

### ISSUE THREAD

**Issue by corquiri** [Azure/azure-powershell#4946]
Currently customers can only purchase reservation through portal. Will need to add the functionality in the future and correct test cases for Reservations module.

Meanwhile, you need to add instructions in the tests  for creating resources in the portal and which parts of the code need to be updated to reflect the identity of those resources, so that constributors can run the tests

**Comment by cormacpayne** [comment]
@corquiri any update on this issue?

**Comment by corquiri** [comment]
We are still only allowing create operation through Ibiza/PC portal. I think you can close this issue for now.
