### ISSUE TITLE
Failed to Import module required by command

### ISSUE THREAD

**Issue by shubhamgupta514** [Azure/azure-powershell#4947]
I am getting  error (refer attached screenshot) in november release of the powershell module  while using Commands Addon in Powershell ISE.

![screenshot](https://user-images.githubusercontent.com/12984945/32588419-932915d2-c534-11e7-895c-14717718bb2e.JPG)

**Comment by shubhamgupta514** [comment]
@viverm - Could you please look into it

**Comment by shubhamgupta514** [comment]
I have to load the dll every time when I launch the ISE as a temporary resolution.
Is there any permanent fix for this?

[System.Reflection.Assembly]::LoadFrom("C:\Program Files\WindowsPowerShell\Modules\AzureRM.RecoveryServices\4.0.0\Microsoft.Azure.Commands.RecoveryServices.ARM.dll")

**Comment by markcowl** [comment]
@shubhamgupta514 @dragonfly91 A fix is planned for Monday - there are sopme general dependency issues for the RecoveryServices.* modules (including thsi oen) that will be addressed.

**Comment by cormacpayne** [comment]
@shubhamgupta514 this has been fixed in Azure PowerShell 5.0.1: https://github.com/Azure/azure-powershell/releases/tag/v5.0.1-November2017

Please update your modules to the latest version to get this fix.
