### ISSUE TITLE
Set-AzureServiceDiagnosticsExtension fails InvalidArgument

### ISSUE THREAD

**Issue by huan086** [Azure/azure-powershell#4948]
### PowerShell Version
5.1.14393.1770

### Module Version
5.0.0

### OS Version
10.0.14393.1770

### Description
Cannot use the overload of the cmdlet that takes -StorageContext 
See https://stackoverflow.com/questions/46607438/not-able-to-enable-diagnostics-for-web-role-using-powershell

### Debug Output
```powershell
Set-AzureServiceDiagnosticsExtension : Cannot bind parameter 'StorageContext'. Cannot convert the
"Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" value of type
"Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" to type
"Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext".
At line:1 char:54
+ ... reServiceDiagnosticsExtension -StorageContext $storageContext -Diagno ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-AzureServiceDiagnosticsExtension], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.WindowsAzure.Commands.ServiceManagement.Extensi
   ons.SetAzureServiceDiagnosticsExtensionCommand
```

### Script/Steps for Reproduction
```powershell
$storageContext = New-AzureStorageContext $storageAccountName -StorageAccountKey $storageAccountKey.Primary
Set-AzureServiceDiagnosticsExtension -StorageContext $storageContext -DiagnosticsConfigurationPath $diagnosticsPath -ServiceName $cloudServiceName -Slot Staging -Role @('Example.Web', 'Example.WorkerRole')
```

**Comment by markcowl** [comment]
@huan086 This is a very old RDFE-based cmdlet.  Is there a reason why you are not using the ARM VMs? You should also be able to work around this using the 'StorageAccountName, StorageAccountKey, and STorageAccountENdppoint parameters instead of the context.

**Comment by markcowl** [comment]
@singhkays @huangpf  The fix for this would be to change this parameter to IStorageContext, so that it is independent of the particula storage version sued to create the context (as has been done for all of the ARM cmdlets).

**Comment by singhkays** [comment]
@hyonholee Can you take a look?

**Comment by yantang-msft** [comment]
@huan086 A quick workaround would be specify the storage account name directly in the command like this: Set-AzureServiceDiagnosticsExtension -StorageAccountName $StorageAccountName
We will at the same time fix it by taking the IStorageContext so it's irrelevant to storage version.

**Comment by huan086** [comment]
@markcowl Still on Cloud Services (classic). Closest thing in ARM is Service Fabric, as it has the autoscaling, updating etc that Cloud Services offers. However, the following is making migration to Service Fabric potentially troublesome and costly

- Recommended minimum number of VM is 3. That's 50% cost increase
- Natively it supports .NET Core. However, we cannot migrate to that due to EF Core lacking many things we need
- Thus we need to run in Server Core container. I have the suspicion that this overhead require us to run on something bigger than A2v2, increasing cost
- When running in container, we are uncertain whether we can still have anti-malware and diagnostic extensions installed, as per client requirement
- Currently we deploy to staging, ensure everything works, VIP swap, then delete staging. Service Fabric way would require us to deploy both old and new version on the same fabric, complicating this as we install things on the VM itself
- Build, package, deployment to staging and VIP swap are all done via Powershell script now. Would need to change all these scripts to Service Fabric

So it makes more sense to stay with Cloud Service

**Comment by vturecek** [comment]
@huan086 side question about SF: Are you running multiple Cloud Services deployments with 2 VMs? SF has a higher minimum VM requirement, but you can pack multiple applications on one cluster. So for example if you have 3 Cloud Services deployments, that's a minimum of 6 VMs, but with SF you can put those 3 applications on a 5 VM SF cluster. 

Containers could potentially solve problems around having things installed on the VMs. There's some overhead, mainly disk space usage.

**Comment by huan086** [comment]
@vturecek

Running one Web Role with 2x A2v2 instance. This role has 2 web sites. Scales out whenever load increases.

Running one Worker Role with 1x A1v2 instance as SFTP server (non-redundant). Will be decommissioning this.

The ability to pack multiple applications on one cluster isn't really needed as Cloud Service can already run multiple websites in a single role.

Current setup is really cheap to run, and handles additional load very nicely. Thus we are having a hard time moving off Cloud Service

**Comment by cormacpayne** [comment]
This issue seems to have been resolved in PR https://github.com/Azure/azure-powershell/pull/4981
