### ISSUE TITLE
Set-AzureRmDiagnosticSetting does not have parameter 'WorkspaceId'

### ISSUE THREAD

**Issue by jochenvw** [Azure/azure-powershell#4949]
Hi all,

I'm trying to script that my CosmosDB starts logging against my Log Analytics ( OMS ) Workspace. Basically the scenario descibed here: [https://docs.microsoft.com/en-us/azure/cosmos-db/logging](https://docs.microsoft.com/en-us/azure/cosmos-db/logging)

I'm looking for the counterpart of the CLI command: `az monitor diagnostic-settings create --resource-id "[ID]" --resource-group "[GROUP]" --workspace "WORKSPACEID"`  - which by the way - is broken it seems : [https://github.com/Azure/azure-cli/issues/4856](https://github.com/Azure/azure-cli/issues/4856) 

This is actually the reason I'm looking into the PowerShell alternative. However - I'm not able to specify `workspaceid` as param for this PowerShell command. Am I looking at the wrong command or is this not yet implemented?

![image](https://user-images.githubusercontent.com/17111555/32605780-1226200a-c553-11e7-8eb6-08318ab9a0ff.png)

Environment info:

![image](https://user-images.githubusercontent.com/17111555/32605805-34f17cec-c553-11e7-9ae0-dd75fee3d9e9.png)

**Comment by markcowl** [comment]
@asheniam @gucalder can you take a look?

**Comment by cormacpayne** [comment]
This appears to be resolved in the latest version of `AzureRM`. Please re-open this issue if that is not the case.
