### ISSUE TITLE
CPU Usage spike after token refresh (?)

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-powershell#4960]
I consistently see CPU usage spike in Powershell ISE after leaving a logged in session overnight.  I'm *guessing* this has something to do with token refresh because only after about a day that this starts. 

### Script/Steps for Reproduction
1) open ISE
2) login-azurermaccount
3) do some azure stuff (I always do this but don't know if it's required for repro)
4) come back tomorrow

ISE will be taking 20% CPU.  If I unload (manually) the Azure modules, cpu usage returns to normal.

**Comment by markcowl** [comment]
@bmoore-msft Token refresh only occurs on demand as requests are made.  There are no background processes doing token refresh.  It would be nice to drill down into precisely what's going on in this case.

Do you get this same behavior in the standard PowerShell window, or is this IES-specific?

**Comment by bmoore-msft** [comment]
I've never used a std ps window, so can't say for sure...  what can I do to help debug it?

**Comment by markcowl** [comment]
I don't think thsi question has anything to do with azure powershell, I think this is a straight powershell question, so please reopen with the powershell team.  For core, they have a repo here: https://github.com/powershell/powershell

**Comment by bmoore-msft** [comment]
Ok, I ran a couple more tests over the weekend...  I used both ISE and powershell.exe and both exhibited the same behavior.  I had 2 ISE windows open, one with AzureRM modules loaded and one without.  Did the same thing with the powershell.exe windows.  The sessions that had the AzureRM modules loaded consumed 20% cpu (so between them it was 40% total).  The sessions that did not have Azure modules loaded had 0% cpu usage.  Closing those sessions returned cpu usage to normal.

We have a problem.  One theory is here: https://github.com/PowerShell/PowerShell/issues/5419

**Comment by markcowl** [comment]
So, again, this is an issue with ISE and not with Azure PowerShell.  Closing as this is not an issue with this product

**Comment by bmoore-msft** [comment]
So, since we are One Microsoft - how can we move forward on fixing this for our customers?

**Comment by maddieclayton** [comment]
@bmoore-msft Please follow the instructions here and file an issue with UserVoice: https://windowsserver.uservoice.com/forums/301869-powershell.  There isn't anything we can do on our side to fix this issue.

Since ISE is no longer the supported PowerShell IDE, please try using the PowerShell extension in VSCode to see if you run into a similar issue.

**Comment by bmoore-msft** [comment]
@maddieclayton there aren't any instructions here that fix this, but I understand we will not be addressing this in Azure PowerShell...

re: the VS Code extension, it has a way to go before it will catch up to the functionality of ISE and being able to replace it, so I'll trade problems for now...
