### ISSUE TITLE
New-AzureStoreAddOn throws certificate error

### ISSUE THREAD

**Issue by BlueBasher** [Azure/azure-powershell#497]
I've been trying to get New-AzureStoreAddOn working but i keep getting this error "ForbiddenError: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription."

When looking through the code it seems that a CloudService is being created during New-AzureStoreAddOn and I have the idea that this is what gives the error.

The steps I do are :
- Add-AzureAcount
- Select-AzureSubscription "SubscriptionName"
-  New-AzureStoreAddOn myMongoDB –AddOn mongolab –plan free –Location “West US”

I'm not sure whether it's a bug or I'm doing something wrong. I'm using Azure PowerShell version released on 6/5/2015.

**Comment by stankovski** [comment]
Thanks for filing this. We were able to reproduce the issue.

**Comment by markcowl** [comment]
@BlueBasher Can you verify that you are still experiencing this issue?

**Comment by markcowl** [comment]
@BlueBasher Since we haven't heard back, assuming the issue no longer occurs for you.  Closing, please open a new issue if you see a recurrence.
