### ISSUE TITLE
When MSI is configured on an Azure Function an error occurs trying to update other properties on the resource

### ISSUE THREAD

**Issue by baabel** [Azure/azure-powershell#4973]
### Cmdlet(s)
Set-AzureRmResource
Set-AzureRMWebAppSlot 

### PowerShell Version
5.1

### Module Version
4.4.0

### OS Version
10.0.14409.1005

### Description
When MSI is configured on an Azure Function an error occurs trying to update other properties on the resource.

### Debug Output

$WebAppPropertiesObject = @{"siteConfig" = @{"AlwaysOn" = $true}}
Set-AzureRmResource -PropertyObject $WebAppPropertiesObject -Force

Set-AzureRmResource : CannotRemoveResourceIdentity : Resource identity of type 'SystemAssigned' already exists on resource and can not be removed.

Same with updating app service plan:
Set-AzureRMWebAppSlot -ResourceGroupName $ResourceGroupName -Name $name  -Slot production -AppServicePlan $appServicePlan

### Script/Steps for Reproduction
Create an Azure Function and configure it with MSI

Run any command to update the App service and an error is thrown.

**Comment by markcowl** [comment]
@baabel Is this an issue with a cmdlet or with how the azure function service works?  Which MSI are you installing?

**Comment by baabel** [comment]
I am referring to Managed Service Identity (MSI);  when this feature is enabled for an Azure Function or App Service we are unable to update the service using the above cmdlets.

So, when MSI is enabled the app service resource has the following data set:
"identity": {
    "tenantId": "<TENANTID>",
    "principalId": "<PRINCIPALID>"
}

Apparently the cmdlets are calling the REST API to update the resource and the back end is interpreting the missing "identity" section in the update call as a "delete" hence the error message "Resource identity of type 'SystemAssigned' already exists on resource and can not be removed."

The same error is seen in the Azure Function Portal UX.

**Comment by IzikLisbon** [comment]
I am seeing the same error when adding a SSL binding to the my App Service through Azure Portal. So it doesn't look like an azure-powershell issue. 
(see my comment at the bottom of this page: https://docs.microsoft.com/en-us/azure/app-service/web-sites-purchase-ssl-web-site).

In my case even after disabling MSI, I can still see this error.

**Comment by maddieclayton** [comment]
Closing as this seems to not be an Azure-PowerShell issue.  Please reopen if it is Azure-PowerShell specific.
