### ISSUE TITLE
InvalidBlobAuditActionsAndGroups Error using Set-AzureRmSqlServerAuditing

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#4974]
### Cmdlet(s)
Set-AzureRmSqlServerAuditing

Customer issue reported via LiveFyre at https://docs.microsoft.com/en-us/powershell/module/azurerm.sql/set-azurermsqlserverauditing

Title | Author | PostTime(UTC) | Comments
-- | -- | -- | --
Set-AzureRmSqlServerAuditing   (AzureRM.Sql) \| Microsoft Docs | aaroney | 11/13/2017 8:28:04 PM | It   looks like the cmdlet is failing for -AuditActionGroup 'AUDIT_CHANGE_GROUP'.   When used got below error: Set-AzureRmSqlServerAuditing :   InvalidBlobAuditActionsAndGroups: Invalid audit actions or action groups. Hope there is some plan to fix this bug.

Can anyone speak to this issue?

**Comment by markcowl** [comment]
@jaredmoo Can you take a look?

**Comment by ranisha2** [comment]
'AUDIT_CHANGE_GROUP' is not supported and should be removed.
PR:
https://github.com/Azure/azure-powershell/pull/4990

**Comment by mvoltchenko** [comment]
Hi. I am getting an error when running the following command: 
az sql db audit-policy update -g "ECL-GIO-AZURE-COSTING" -s  jdlsql01 -n "AzureInventory_CN" --state Enabled --storage-account ecljdlds04
Invalid audit actions or action groups.
I am not specifying any actions or action groups, just trying to enable auditing policy with the default settings. According to the documentation --actions is an optional parameter. Why am i getting the error "Invalid audit actions or action groups"?

**Comment by ranisha2** [comment]
@mvoltchenko 
Did you set an empty set of audit actions or action groups previously with a disabled policy? If you do so, and then you try to enable the policy without providing audit actions or action groups, the request will fail, as it will send the previously set value. This value is only being validated when the policy is enabled.
To solve this, please provide actions.
