### ISSUE TITLE
Cannot add permissions to Blob Container with SharedAccessPolicy

### ISSUE THREAD

**Issue by mshamann** [Azure/azure-powershell#4975]
### Cmdlet(s)
AzureRM BlobContainer Object

### PowerShell Version
5.1.14393.1770

### Module Version
AzureRM 5.0.1

### OS Version
10.0.14393.1770

### Description

I cannot add new SharedAccessPolicies to the Azure Blob container, it states that the Add method cannot be found. 

When I get-method the object, I see no .add() method, however if I create a new 'Microsoft.WindowsAzure.Storage.Blob.SharedAccessBlobPolicies' object it exists there. 

I cannot pass this new object to the blobcontainer SetPermissions() method, and it gives me a similar error. 

### Debug Output
```
Cannot find an overload for "Add" and the argument count: "2".
At C:\source\LPSTools\Scripts\sqlbackups.ps1:34 char:1
+ $permissions.SharedAccessPolicies.Add($policyName, $policy)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
```

### Script/Steps for Reproduction

```
Import-Module AzureRM -force 
Import-Module Azure -force 
Import-Module C:\Source\dbatools\dbatools.psd1 -force 
Import-Module C:\Source\LPSTools\lpstools.psd1 -force

Login-AzureRmAccount

$prefixName = "new-"
$resourceGroupName = "rg-o1"
$storageAccountName = "test"
$containerName = "test"
$policyName = $prefixName + 'policy' 

$DebugPreference="Continue"

# $Backups = Get-AzureRmStorageAccount -Name $storageAccountName -ResourceGroupName $resourceGroupName
$accountKeys = Get-AzureRmStorageAccountKey -ResourceGroupName $resourceGroupName -Name $storageAccountName 
$accountContext = New-AzureStorageContext -StorageAccountName $storageAccountName -StorageAccountKey $accountKeys[0].Value

$container = Get-AzureStorageContainer -Context $accountContext -Name $containerName
$cbc = $container.CloudBlobContainer

# Sets up a Stored Access Policy and a Shared Access Signature for the new container  
$permissions = $cbc.GetPermissions();  
$policyName = $policyName  
$policy = new-object 'Microsoft.WindowsAzure.Storage.Blob.SharedAccessBlobPolicy'  
$policy.SharedAccessStartTime = $(Get-Date).ToUniversalTime().AddMinutes(-5)  
$policy.SharedAccessExpiryTime = $(Get-Date).ToUniversalTime().AddYears(10)  
$policy.Permissions = "Read,Write,List,Delete"  
$permissions.SharedAccessPolicies.Add($policyName, $policy)  
$cbc.SetPermissions($permissions);  
```

**Comment by mshamann** [comment]
The issue seems to stem even further as I cannot use GetSharedAccessSignature() without getting the same error. 
```
Cannot find an overload for "GetSharedAccessSignature" and the argument count: "2".
At C:\source\LPSTools\Scripts\gen_BlobStorage_SASKey_SQLCredential.ps1:29 char:1
+ $sas = $cbc.GetSharedAccessSignature($policy, $policyName)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
```


For reference, I am using this script as a base: https://docs.microsoft.com/en-us/sql/relational-databases/lesson-1-create-stored-access-policy-and-shared-access-signature

**Comment by markcowl** [comment]
@mshamann Have you tried using the Storage cmdlets for this (New-AzureStorageContainerStoredAccessPolicy, New-AzureStorageBlobSASToken)?

If you are using multiple modules from different sources, as your script seems to, they might be usign different versions fo the storage library - using the cmdlets ratehr than the .Net SDK calls would seem to be the simplest solution

**Comment by maddieclayton** [comment]
@mshamann Are you still seeing this issue?

**Comment by mshamann** [comment]
@maddieclayton the storage cmdlets worked, I found it before markcowl responded and missed his email response. My apologies.

**Comment by MyUsername01** [comment]
Had the same problem, this worked for me http://www.data-boss.nl/uncategorized/cannot-add-permissions-to-blob-container-with-sharedaccesspolicy/

**Comment by aceptra** [comment]
On the documentation https://docs.microsoft.com/en-us/sql/relational-databases/lesson-1-create-stored-access-policy-and-shared-access-signature it specifies "This script is written using Azure PowerShell 5.0.10586".

Uninstalling AzureRM 5.1.1, falling back to 5.0.1. worked for me.

Something like this:
`
# See what you are currently running.
Get-Module AzureRM -list | Select-Object Name,Version,Path

# If 5.1.1, then...
Uninstall-Module AzureRM -RequiredVersion 5.1.1

# Maybe need to install back 5.0.1? I didn't need to though.
Install-Module -Name AzureRM -RequiredVersion 5.0.1
`
