### ISSUE TITLE
Set-AzureStorageBlobContent should support the Content-Disposition BlobProperty

### ISSUE THREAD

**Issue by Peter-Schneider** [Azure/azure-powershell#498]

**Comment by pcgeek86** [comment]
Use the `-Property` parameter.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by devigned** [comment]
@Peter-Schneider does that solve this for you?

**Comment by gmantri** [comment]
Please see this thread on SO for more details: http://stackoverflow.com/questions/30786308/how-to-set-contentdisposition-using-set-azurestorageblobcontent.

@pcgeek86 Problem is that -Property expects a HashTable and matches the keys against a set of predefined properties. Currently ContentDisposition is not one of them :(

**Comment by Peter-Schneider** [comment]
@pcgeek86, @gmantri, @devigned: Thank you! That's excatly the problem. I've added a pull request (#502), which adds the missing Dictionary entry.

**Comment by pcgeek86** [comment]
@gmantri @Peter-Schneider excellent, thanks for finding that, guys!! I'm glad it's being validated on the client side, and that you were able to submit a PR for it.

**Comment by devigned** [comment]
@Peter-Schneider awesomesauce! Thank you for the PR.

**Comment by Peter-Schneider** [comment]
@All: No problem.. Thank you @ogail for merging (ogail@7e36ee8943efc5aeedab51b33a7c4ad7928c6edd)
