### ISSUE TITLE
Support passing certificate in Azure Key Vault to New-AzureRmWebAppSSLBinding?

### ISSUE THREAD

**Issue by jeremymeng** [Azure/azure-powershell#4982]
### Cmdlet(s)
New-AzureRmWebAppSSLBinding

### Script/Steps for Reproduction

Found examples on the internet that deploy a key vault certificate into a web app. But they are done either directly via the REST endpoint, or use ARM template deployment.

Can we do that using Azure CmdLets?

**Comment by markcowl** [comment]
@NKing92 Are we plannign support for these scenarios.  Please feel free to reassign to an appropriate WebApps team member

**Comment by cormacpayne** [comment]
@panchagnula ping on the above question

**Comment by panchagnula** [comment]
AFAIK there are no current plans for supporting this via an REST API. @Chibionos is there an ARM Template way to accomplish this?

**Comment by panchagnula** [comment]
@btardif can you help us figure out the APIs for supporting this.

**Comment by btardif** [comment]
I have reached out to API owners for sample

**Comment by btardif** [comment]
https://docs.microsoft.com/en-us/rest/api/appservice/certificates/createorupdate

**Comment by panchagnula** [comment]
We will track this using issue #7469
