### ISSUE TITLE
Get-AzureEnvironment doesn't return US Government Cloud

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#499]
The `Get-AzureEnvironment` command does not return the Azure US Government Cloud environment. Please add this environment to **both** the Service Management and Azure Resource Manager (ARM) modules.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by devigned** [comment]
I don't think we are going to add this environment (at least not real soon). 

In fact, environments will likely be refactored into something closer to discovery endpoints. Think about adding a git remote. It would be similar. Give a name and a uri, then the client could pull all of the metadata for the environment from the uri.
