### ISSUE TITLE
Get-AzureRmRoleAssignment -SignInName -ExpandPrincipalGroups broken

### ISSUE THREAD

**Issue by cielakm** [Azure/azure-powershell#4992]
### Cmdlet(s)
Get-AzureRmRoleAssignment
### PowerShell Version
Name                           Value                                                                                          
----                           -----                                                                                          
PSVersion                      5.1.15063.674                                                                                  
PSEdition                      Desktop                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                        
BuildVersion                   10.0.15063.674                                                                                 
CLRVersion                     4.0.30319.42000                                                                                
WSManStackVersion              3.0                                                                                            
PSRemotingProtocolVersion      2.3                                                                                            
SerializationVersion           1.1.0.1                                                                                        

### Module Version

ModuleType Version    Name                                                                                    
---------- -------    ----                                                                                
Script     4.0.0      AzureRM.profile                     
Script     5.0.0      AzureRM.Resources  

### Description
Get-AzureRmRoleAssignment -SignInName -ExpandPrincipalGroups was working correctly using Azurerm.Resources -version 4.1.0 and Azurerm.profile 3.1.0

The command was returning user role assignment based on direct user assignment and if the user was in the group or not.
Since I have update the module this functionality is now returning a lot of different permission and not consistent.

Get-AzureRmRoleAssignment -SignInName name.sunrame@contoso.com -ExpandPrincipalGroups

**Comment by cormacpayne** [comment]
@cielakm Hey Marek, what are some of the inconsistencies you are seeing? Would you mind providing a few example outputs you are seeing for `AzureRM` 4.1.0 vs 5.0.0?

CC: @darshanhs90

**Comment by cielakm** [comment]
If I run this command:
Get-AzureRmRoleAssignment -SignInName marek.name@contos.com -ExpandPrincipalGroups | select DisplayName,SignInName,RoleDefinitionName,ObjectType,scope | ft

on 4.1.0
![image](https://user-images.githubusercontent.com/22874273/32953015-d7c0e27e-cba6-11e7-84fb-607209016049.png)
this is the output:
![image](https://user-images.githubusercontent.com/22874273/32954010-c9febc94-cba9-11e7-962f-2799e4b63fc1.png)

Which only displayed the groups that the user is a part of and have been assign to Sub, RG or resource.

If I run the same command on 5.0.0
![image](https://user-images.githubusercontent.com/22874273/32953398-fa411796-cba7-11e7-817e-ce0b2c63420e.png)
this is the output:
![image](https://user-images.githubusercontent.com/22874273/32954135-2865d768-cbaa-11e7-8c8f-790a5f008698.png)

It looks like it display information about all access permissions for anyone and any group is the scope of subscription,RG and resource.

**Comment by cielakm** [comment]
Hi @cormacpayne  do you need any more info on this?

**Comment by maddieclayton** [comment]
Fixed in the PR linked above, and will be included in the next release.

**Comment by leo130ms** [comment]
I want to make a csv with the infos of Get-AzureRoleAssignment. But I cant catch the atributes of each role of each resource group
