### ISSUE TITLE
Must authenticate to access this API appearing when trying to login through the VS2015 extension to Github

### ISSUE THREAD

**Issue by swi2w** [Azure/azure-powershell#4994]
Trying to log into the Github extension (v2.3.3.38) for VS2015 and I am getting the error Must authenticate to access this API. I can log in with the same credentials through a browser but not through the VS extension. Tried removing the extension and reinstalling with no change.

**Comment by cormacpayne** [comment]
@swi2w which extension are you trying to use? This repository does not contain any extensions ☺️

**Comment by swi2w** [comment]
@cormacpayne - the Github extension for Visual Studio 2015

**Comment by maddieclayton** [comment]
@swi2w Please file an issue here: https://github.com/github/visualstudio
