### ISSUE TITLE
Incredibly slow time updating local Network Security groups Objects for RemoveAzureNetworkSecurityRuleConfigCommand

### ISSUE THREAD

**Issue by isaacegglestone** [Azure/azure-powershell#5001]
### Cmdlet(s)
AzureRM.Network.Remove-AzureRmNetworkSecurityRuleConfig 

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

$PSVersionTable

### Module Version
 4.4.1      AzureRM

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

BuildVersion                   10.0.14409.1012

### Description

REG:117110617106628

Incredibly slow time updating local Network Security groups Objects for both Additons and Removals.

Local being in memory on local machine objects not modifying anything in Azure.

This should be similar to a hash table update in memory and should be ORD(1) and incredibly fast.

However for some reason depending on network delays could be up to 6 seconds to simply edit a local object with default powershell setting of Enable-AzureRmDataCollection without Data Collection this is after setting Disable-AzureRmDataCollection the average time is still roughly 2.5 seconds.

I should also mention that by default sending an update to register metrics for every single local object update in memory is quite ridiculous IMHO.

While that might seem like a reasonable update consider removing or adding 200-400 rules and you will see that editing a local object can take up to 16minutes.  Something that should complete in a fraction of a second for all of them.  This is completely separate and not including time to later update the actual security group in Azure after the local object has been adjusted.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
DEBUG: 14:09:36 - GetAzureNetworkSecurityGroupCommand end processing.
DEBUG: 14:09:36 - GetAzureNetworkSecurityGroupCommand end processing.
DEBUG: 14:09:36 - GetAzureNetworkSecurityRuleConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 14:09:36 - using account id '0d839ef5-2a3f-4be1-8ec8-a47b3755d7b9'...
DEBUG: 14:09:39 - GetAzureNetworkSecurityRuleConfigCommand end processing.
DEBUG: 14:09:39 - GetAzureNetworkSecurityRuleConfigCommand end processing.
Attempting to remove rule  InboundBupaOfficesCMhttpRule5
DEBUG: 14:09:39 - RemoveAzureNetworkSecurityRuleConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 14:09:39 - using account id '0d839ef5-2a3f-4be1-8ec8-a47b3755d7b9'...
DEBUG: 14:09:44 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
DEBUG: 14:09:44 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
It took 00:00:04.8160953 to finish.....
Attempting to remove rule  InboundBupaOfficesCMhttpRule1
DEBUG: 14:09:44 - RemoveAzureNetworkSecurityRuleConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 14:09:44 - using account id '0d839ef5-2a3f-4be1-8ec8-a47b3755d7b9'...
DEBUG: 14:09:48 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
DEBUG: 14:09:48 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
It took 00:00:04.7498846 to finish.....
Attempting to remove rule  InboundBupaOfficesCMhttpRule2
DEBUG: 14:09:48 - RemoveAzureNetworkSecurityRuleConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 14:09:48 - using account id '0d839ef5-2a3f-4be1-8ec8-a47b3755d7b9'...
DEBUG: 14:09:53 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
DEBUG: 14:09:53 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
It took 00:00:04.2610798 to finish.....
Attempting to remove rule  InboundBupaOfficesCMhttpRule3
DEBUG: 14:09:53 - RemoveAzureNetworkSecurityRuleConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 14:09:53 - using account id '0d839ef5-2a3f-4be1-8ec8-a47b3755d7b9'...
DEBUG: 14:09:56 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
DEBUG: 14:09:56 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
It took 00:00:03.3486023 to finish.....
Attempting to remove rule  InboundBupaOfficesCMhttpRule4
DEBUG: 14:09:56 - RemoveAzureNetworkSecurityRuleConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 14:09:56 - using account id '0d839ef5-2a3f-4be1-8ec8-a47b3755d7b9'...
DEBUG: 14:10:00 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
DEBUG: 14:10:00 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.

### Script/Steps for Reproduction

$ExistingNSG = Get-AzureRMNetworkSecurityGroup -Name "AZRDIGTESTWAF-nsg" -ResourceGroupName "Networks"

# Get the rules from Azure Rm NSG
    $ExistingNSGRules = Get-AzureRmNetworkSecurityRuleConfig -NetworkSecurityGroup $ExistingNSG
    foreach ( $ExistingNSGRule in $ExistingNSGRules) {
        Write-Output "Attempting to remove rule  $($ExistingNSGRule.Name)"
        $RulRemoveTime = Measure-Command { Remove-AzureRmNetworkSecurityRuleConfig -Name $ExistingNSGRule.Name -NetworkSecurityGroup $ExistingNSG | Out-Null}
        # $ExistingNSG | Remove-AzureRmNetworkSecurityRuleConfig -Name $ExistingNSGRule.Name | Out-Null
        Write-Output "It took $RulRemoveTime to finish....."
    }

### Older versions

I don't seem to have this problem on other systems with older Azure powershell versions.
See below for version information.

####Output From Version information on Older Azure implementation:

Get-Module -Listavailable *AzureRM* 

    Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager

ModuleType Version    Name                                ExportedCommands                                                                                                                                               
---------- -------    ----                                ----------------                                                                                                                                               
Manifest   1.1.3      AzureRM.ApiManagement               {Add-AzureRmApiManagementRegion, Get-AzureRmApiManagementSsoToken, New-AzureRmApiManagementHostnameConfiguration, New-AzureRmApiManagementVirtualNetwork...}   
Manifest   1.0.11     AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutomationJobOutputRecord, Import-AzureRmAutomationDscNodeConfiguration, Export-AzureRmAutomationDscConf...
Binary     0.9.8      AzureRM.AzureStackAdmin             {Get-AzureRMManagedLocation, New-AzureRMManagedLocation, Remove-AzureRMManagedLocation, Set-AzureRMManagedLocation...}                                         
Manifest   0.9.9      AzureRM.AzureStackStorage           {Add-ACSFarm, Get-ACSEvent, Get-ACSEventQuery, Get-ACSFarm...}                                                                                                 
Manifest   1.0.11     AzureRM.Backup                      {Backup-AzureRmBackupItem, Enable-AzureRmBackupContainerReregistration, Get-AzureRmBackupContainer, Register-AzureRmBackupContainer...}                        
Manifest   1.1.3      AzureRM.Batch                       {Remove-AzureRmBatchAccount, Get-AzureRmBatchAccount, Get-AzureRmBatchAccountKeys, New-AzureRmBatchAccount...}                                                 
Manifest   1.0.5      AzureRM.Cdn                         {Get-AzureRmCdnCustomDomain, New-AzureRmCdnCustomDomain, Remove-AzureRmCdnCustomDomain, Get-AzureRmCdnEndpointNameAvailability...}                             
Manifest   0.1.2      AzureRM.CognitiveServices           {Get-AzureRmCognitiveServicesAccount, Get-AzureRmCognitiveServicesAccountKey, Get-AzureRmCognitiveServicesAccountSkus, New-AzureRmCognitiveServicesAccount...} 
Manifest   1.3.3      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet, New-AzureRmAvailabilitySet, Get-AzureRmVMExtensionImageType...}                                    
Manifest   1.0.11     AzureRM.DataFactories               {Remove-AzureRmDataFactory, Get-AzureRmDataFactoryRun, Get-AzureRmDataFactorySlice, Save-AzureRmDataFactoryLog...}                                             
Manifest   1.1.3      AzureRM.DataLakeAnalytics           {Get-AzureRmDataLakeAnalyticsDataSource, Remove-AzureRmDataLakeAnalyticsCatalogSecret, Set-AzureRmDataLakeAnalyticsCatalogSecret, New-AzureRmDataLakeAnalyti...
Manifest   1.0.11     AzureRM.DataLakeStore               {Add-AzureRmDataLakeStoreItemContent, Export-AzureRmDataLakeStoreItem, Get-AzureRmDataLakeStoreChildItem, Get-AzureRmDataLakeStoreItem...}                     
Manifest   1.0.2      AzureRM.DevTestLabs                 {Get-AzureRmDtlAllowedVMSizesPolicy, Get-AzureRmDtlAutoShutdownPolicy, Get-AzureRmDtlAutoStartPolicy, Get-AzureRmDtlVMsPerLabPolicy...}                        
Manifest   1.0.11     AzureRM.Dns                         {Get-AzureRmDnsRecordSet, New-AzureRmDnsRecordConfig, Remove-AzureRmDnsRecordSet, Set-AzureRmDnsRecordSet...}                                                  
Manifest   1.1.3      AzureRM.HDInsight                   {Get-AzureRmHDInsightJob, New-AzureRmHDInsightSqoopJobDefinition, Wait-AzureRmHDInsightJob, New-AzureRmHDInsightStreamingMapReduceJobDefinition...}            
Manifest   1.0.11     AzureRM.Insights                    {Add-AzureRmMetricAlertRule, Add-AzureRmLogAlertRule, Add-AzureRmWebtestAlertRule, Get-AzureRmAlertHistory...}                                                 
Manifest   1.1.10     AzureRM.KeyVault                    {Get-AzureRmKeyVault, New-AzureRmKeyVault, Remove-AzureRmKeyVault, Remove-AzureRmKeyVaultAccessPolicy...}                                                      
Manifest   1.0.7      AzureRM.LogicApp                    {Get-AzureRmIntegrationAccountAgreement, Get-AzureRmIntegrationAccountCallbackUrl, Get-AzureRmIntegrationAccountCertificate, Get-AzureRmIntegrationAccount...} 
Manifest   0.9.2      AzureRM.MachineLearning             {Export-AzureRmMlWebService, Get-AzureRmMlWebServiceKeys, Import-AzureRmMlWebService, Remove-AzureRmMlWebService...}                                           
Manifest   1.0.12     AzureRM.Network                     {Add-AzureRmApplicationGatewayBackendAddressPool, Get-AzureRmApplicationGatewayBackendAddressPool, New-AzureRmApplicationGatewayBackendAddressPool, Remove-A...
Manifest   1.0.11     AzureRM.NotificationHubs            {Get-AzureRmNotificationHubsNamespaceAuthorizationRules, Get-AzureRmNotificationHubsNamespaceListKeys, New-AzureRmNotificationHubsNamespaceAuthorizationRule...
Manifest   1.0.11     AzureRM.OperationalInsights         {Get-AzureRmOperationalInsightsSavedSearch, Get-AzureRmOperationalInsightsSavedSearchResults, Get-AzureRmOperationalInsightsSchema, Get-AzureRmOperationalIn...
Manifest   1.0.0      AzureRM.PowerBIEmbedded             {Remove-AzureRmPowerBIWorkspaceCollection, Get-AzureRmPowerBIWorkspaceCollection, Get-AzureRmPowerBIWorkspaceCollectionAccessKeys, Get-AzureRmPowerBIWorkspa...
Manifest   1.0.11     AzureRM.Profile                     {Enable-AzureRmDataCollection, Disable-AzureRmDataCollection, Remove-AzureRmEnvironment, Get-AzureRmEnvironment...}                                            
Manifest   1.1.3      AzureRM.RecoveryServices            {Get-AzureRmRecoveryServicesBackupProperties, Get-AzureRmRecoveryServicesVault, Get-AzureRmRecoveryServicesVaultSettingsFile, New-AzureRmRecoveryServicesVau...
Manifest   1.0.3      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRecoveryServicesBackupItem, Get-AzureRmRecoveryServicesBackupManagementServer, Get-AzureRmRecoveryServicesBackupContainer, Unregister-AzureRm...
Manifest   1.1.9      AzureRM.RedisCache                  {Reset-AzureRmRedisCache, Export-AzureRmRedisCache, Import-AzureRmRedisCache, Remove-AzureRmRedisCacheDiagnostics...}                                          
Manifest   2.0.2      AzureRM.Resources                   {Get-AzureRmADApplication, Get-AzureRmADGroupMember, Get-AzureRmADGroup, Get-AzureRmADServicePrincipal...}                                                     
Manifest   1.0.2      AzureRM.ServerManagement            {Install-AzureRmServerManagementGatewayProfile, Reset-AzureRmServerManagementGatewayProfile, Save-AzureRmServerManagementGatewayProfile, New-AzureRmServerMa...
Manifest   1.1.10     AzureRM.SiteRecovery                {Stop-AzureRmSiteRecoveryJob, Get-AzureRmSiteRecoveryNetwork, Get-AzureRmSiteRecoveryNetworkMapping, Update-AzureRmSiteRecoveryServer...}                      
Manifest   1.0.11     AzureRM.Sql                         {Get-AzureRmSqlDatabaseImportExportStatus, New-AzureRmSqlDatabaseExport, New-AzureRmSqlDatabaseImport, Get-AzureRmSqlDeletedDatabaseBackup...}                 
Manifest   1.1.3      AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, Get-AzureRmStorageAccountNameAvailability, Get-AzureRmStorageUsage...}                               
Manifest   1.0.11     AzureRM.StreamAnalytics             {Get-AzureRmStreamAnalyticsFunction, Get-AzureRmStreamAnalyticsDefaultFunctionDefinition, New-AzureRmStreamAnalyticsFunction, Remove-AzureRmStreamAnalyticsF...
Manifest   1.0.11     AzureRM.Tags                        {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag}                                                                                                            
Manifest   1.0.11     AzureRM.TrafficManager              {Disable-AzureRmTrafficManagerEndpoint, Enable-AzureRmTrafficManagerEndpoint, Set-AzureRmTrafficManagerEndpoint, Get-AzureRmTrafficManagerEndpoint...}         
Manifest   1.0.11     AzureRM.UsageAggregates             Get-UsageAggregates                                                                                                                                            
Manifest   1.1.3      AzureRM.Websites                    {Get-AzureRmAppServicePlanMetrics, New-AzureRmWebAppDatabaseBackupSetting, Restore-AzureRmWebAppBackup, Get-AzureRmWebAppCertificate...}                       

#####Output from older version listed above  using same test

Note the operations take 2-4 thousands of a second.
This is the expected speed to modify a local object in memory, not 2.5 seconds.

Environment           : AzureCloud
Account               : 0d839ef5-2a3f-4be1-8ec8-a47b3755d7b9
TenantId              : 02af5f5e-dd71-4056-8090-3e7b436a65db
SubscriptionId        : cc78b73d-ca8e-45b9-89f7-6f716ecf836d
SubscriptionName      : Bupa-UKMU-Digital-NonProd
CurrentStorageAccount : 

Attempting to remove rule  InboundBupaOfficesCMhttpRule5
It took 00:00:00.0045686 to finish.....
Attempting to remove rule  InboundBupaOfficesCMhttpRule1
It took 00:00:00.0003024 to finish.....
Attempting to remove rule  InboundBupaOfficesCMhttpRule2
It took 00:00:00.0002654 to finish.....
Attempting to remove rule  InboundBupaOfficesCMhttpRule3
It took 00:00:00.0002631 to finish.....
Attempting to remove rule  InboundBupaOfficesCMhttpRule4
It took 00:00:00.0002740 to finish.....
Attempting to remove rule  Sandip-Testing-Source-Datamatics
It took 00:00:00.0003096 to finish.....
Attempting to remove rule  Sandip-Testing-Source-Datamatics-2
It took 00:00:00.0002677 to finish.....
Attempting to remove rule  Jon-vm-http
It took 00:00:00.0002624 to finish.....
Attempting to remove rule  Manchester-Bupa-LAN
It took 00:00:00.0002649 to finish.....
Attempting to remove rule  Andreis-VM
It took 00:00:00.0002566 to finish.....
Attempting to remove rule  Bupa-WirelessEcom
It took 00:00:00.0002599 to finish.....
Attempting to remove rule  Luc-via-BupaWifi
It took 00:00:00.0002580 to finish.....
Attempting to remove rule  Datamatics-Automation-Cloud1
It took 00:00:00.0002877 to finish.....
Attempting to remove rule  DheerajsVM-HTTP
It took 00:00:00.0002719 to finish.....
Attempting to remove rule  Datamatics-Automation-Cloud2
It took 00:00:00.0002587 to finish.....
Attempting to remove rule  JonNewVMhttp
It took 00:00:00.0003506 to finish.....
Attempting to remove rule  SapientGurgaonOffice2-HTTP
It took 00:00:00.0003235 to finish.....
Attempting to remove rule  SapientGurgaonOffice3-HTTP
It took 00:00:00.0003293 to finish.....
Attempting to remove rule  SapientGurgaonOffice-HTTP
It took 00:00:00.0006890 to finish.....
Attempting to remove rule  SapientGurgaonOffice4-HTTP
It took 00:00:00.0002651 to finish.....
Attempting to remove rule  AZRUKTESTWAF-IP
It took 00:00:00.0014681 to finish.....
Attempting to remove rule  InboundBupaOfficesWAFAdminRule1
It took 00:00:00.0002841 to finish.....
Attempting to remove rule  InboundBupaOfficesWAFAdminRule2
It took 00:00:00.0002651 to finish.....
Attempting to remove rule  InboundBupaOfficesWAFAdminRule3
It took 00:00:00.0002651 to finish.....
Attempting to remove rule  InboundBupaOfficesWAFAdminRule4
It took 00:00:00.0003593 to finish.....
Attempting to remove rule  InboundBupaOfficesWAFAdminRule5
It took 00:00:00.0002752 to finish.....
Attempting to remove rule  InboundBupaOfficesWAFAdminRule6
It took 00:00:00.0002590 to finish.....
Attempting to remove rule  InboundBupaOfficesWAFAdminRule7
It took 00:00:00.0002536 to finish.....
Attempting to remove rule  InboundBupaOfficesWAFAdminRule8
It took 00:00:00.0002540 to finish.....
Attempting to remove rule  InboundBupaOfficesWAFAdminRule9
It took 00:00:00.0002525 to finish.....
Attempting to remove rule  InboundBupaOfficesWAFAdminRule10
It took 00:00:00.0002535 to finish.....
Attempting to remove rule  Bupa-Staines-Office-WAFAdminRule11
It took 00:00:00.0002655 to finish.....
Attempting to remove rule  SauceLabsIpBlock1
It took 00:00:00.0002684 to finish.....
Attempting to remove rule  SauceLabsIpBlock2
It took 00:00:00.0002520 to finish.....
Attempting to remove rule  APIGEEToForgeRock1
It took 00:00:00.0002737 to finish.....

#### MS Support Team verified details:

Case REG:117110617106628]

Specific tests performed:
===========
*** Per support engineer request Above code was run on cloud powershell console to confirm same problem exists but took 2.5 seconds per local object update.

*** Disable-AzureRmDataCollection showed improved performance on local machine from 6 seconds to 2.5 seconds but could not improve the speed reasonably to what it should be as local object in memory update should be roughly 0.0004 seconds per update or less based on hash table logic and previous Azure Powershell speeds.

**Comment by cormacpayne** [comment]
@isaacegglestone would you mind upgrading to the latest version of `AzureRM` and letting us know if you still see this issue?

**Comment by isaacegglestone** [comment]
Sorry there was a typo it was suppose to read 4.4.1,   It was the latest when I ran the tests and when we ran the tests on the cloud shell, seems 5 is out now so just installing the new azure module now will feedback shortly.

**Comment by isaacegglestone** [comment]
Okay I yep seems back to proper timing now, sorry I really did try the latest release at the time and also MS support engineer only told me to open the github today so I think 5 must have been a very recent release within the last week or Either the support engineer or I would have caught it.

EBUG: 16:29:01 - GetAzureNetworkSecurityGroupCommand end processing.
DEBUG: 16:29:01 - GetAzureNetworkSecurityGroupCommand end processing.
DEBUG: 16:29:01 - GetAzureNetworkSecurityRuleConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 16:29:01 - using account id '0d839ef5-2a3f-4be1-8ec8-a47b3755d7b9'...
DEBUG: 16:29:01 - GetAzureNetworkSecurityRuleConfigCommand end processing.
DEBUG: 16:29:01 - GetAzureNetworkSecurityRuleConfigCommand end processing.
Attempting to remove rule  InboundBupaOfficesCMhttpRule5
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 16:29:01 - using account id '0d839ef5-2a3f-4be1-8ec8-a47b3755d7b9'...
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
It took 00:00:00.0126329 to finish.....
Attempting to remove rule  InboundBupaOfficesCMhttpRule1
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 16:29:01 - using account id '0d839ef5-2a3f-4be1-8ec8-a47b3755d7b9'...
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
It took 00:00:00.0031486 to finish.....
Attempting to remove rule  InboundBupaOfficesCMhttpRule2
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 16:29:01 - using account id '0d839ef5-2a3f-4be1-8ec8-a47b3755d7b9'...
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
It took 00:00:00.0030187 to finish.....
Attempting to remove rule  InboundBupaOfficesCMhttpRule3
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 16:29:01 - using account id '0d839ef5-2a3f-4be1-8ec8-a47b3755d7b9'...
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
It took 00:00:00.0046520 to finish.....
Attempting to remove rule  InboundBupaOfficesCMhttpRule4
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 16:29:01 - using account id '0d839ef5-2a3f-4be1-8ec8-a47b3755d7b9'...
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
DEBUG: 16:29:01 - RemoveAzureNetworkSecurityRuleConfigCommand end processing.
It took 00:00:00.0030473 to finish.....
Attempting to remove rule  Sandip-Testing-Source-Datamatics

**Comment by cormacpayne** [comment]
@isaacegglestone we released 5.0.0 last week, so it was recent ☺️ Glad your issue was fixed!
