### ISSUE TITLE
Get-AzureRmMetric does not return correct data for Azure SQL Database

### ISSUE THREAD

**Issue by blueelvis** [Azure/azure-powershell#5005]
### Cmdlet(s) 
Get-AzureRmMetric

### PowerShell Version
5.1.15063.674

### Module Version
4.4.0

### OS Version
10.0.15063.674

### Description
If I get the metrics over the past week for Azure SQL Database and take the average of the data, it gives me a lot more than what is shown in the Azure Portal.
Azure Portal -
![image](https://user-images.githubusercontent.com/6985763/32952321-f5b3ad62-cbd2-11e7-8b41-e072bddbdc94.png)

What Powershell returns - 6.99651507508885 (For the same set of data as above). I don't see how the above data could average to that...

Code -

```
#Only way as of now to get the resource id of SQL database is to create it.
$resourceId = "/subscriptions/" + (Get-AzureRmContext).Subscription + "/resourceGroups/" + $sqlServerResourceGroupName + "/providers/Microsoft.Sql/servers/" + $sqlServerName + "/databases/" + $sqlDatabaseName
$endTime = Get-Date
$startTime = $endTime.AddHours(-168)
$timeGrain = '168:00:00'         #Time grain of 7 days

$metricName = 'dtu_consumption_percent'

#Issues have been raised with Microsoft regarding this. The value which is coming is not correct with what is shown in Azure Portal.
$sqlDBDtuPercentage = ((Get-AzureRmMetric -ResourceId $resourceId -StartTime $startTime -EndTime $endTime -MetricNames $metricName -TimeGrain $timeGrain -AggregationType Average).Data).Average

```

### Script/Steps for Reproduction
1. Create an Azure SQL Database
2. Run the above code with proper values.
3. Check value in the portal.

**Comment by markcowl** [comment]
@gucalder can you take  a look?

**Comment by blueelvis** [comment]
@cormacpayne @markcowl - It has been like a month now. Any idea what is going on? :|

**Comment by cormacpayne** [comment]
@gucalder ping

**Comment by KevinBlasko** [comment]
Thanks for reporting this issue.  If you are still having problems, please open up a support ticket in the Azure Portal.  Please include the resource id of the SQL DB resource that you are hitting this with along with a link to this github issue.

**Comment by KevinBlasko** [comment]
One point to consider is that when you average the data being returned from the API you are computing the average of an existing average.  This calculation is often incorrect (see [this page](https://math.stackexchange.com/questions/95909/why-is-an-average-of-an-average-usually-incorrect) for details).

To calculate the true average, query the API for the sum aggregation and the count aggregation and then use these to compute the true average.  If a true average calculation is still yielding different results, please open a support ticket as I suggested previously.
