### ISSUE TITLE
API Management support for API Version

### ISSUE THREAD

**Issue by PlagueHO** [Azure/azure-powershell#5021]
### Cmdlet(s)
*-AzureRMApiManagementApi

### PowerShell Version
5.1

### Module Version
4.4.1

### OS Version
10.0.14409.1012

### Description
APIM cmdlets do not support API version features. This feature is currently in preview in APIM. Is this in preview for the cmdlets or is this on the roadmap?

### Debug Output
N/A

### Script/Steps for Reproduction
```powershell
Get-AzureRMApiManagementApi -Context $context -Name 'MyAPIWithMultipleVersions'
```
All versions are returned, but there is not version number or other related information to identify which API is the one we'd want.

**Comment by cormacpayne** [comment]
@solankisamir Hey Samir, would you mind taking a look at this issue?

**Comment by solankisamir** [comment]
This is on the roadmap and expected to be delivered in Feb 2018 milestone release of PowerShell. @darrelmiller  FYI

**Comment by TerrapinStation** [comment]
@solankisamir is this feature still expected to be delivered Feb 2018?

**Comment by solankisamir** [comment]
No, we have slipped on the delivery date for this, due to some service side challenges.
Expect it to be out in April 2018. Apologize for that.

**Comment by solankisamir** [comment]
The .NET nuget https://www.nuget.org/packages/Microsoft.Azure.Management.ApiManagement/4.0.0-preview which support Api Version is out. Powershell built on this .net sdk is being worked upon.

**Comment by PlagueHO** [comment]
Thanks for the update @solankisamir - this is great news.

**Comment by solankisamir** [comment]
Powershell cmdlets for Api Revisions and Versions are now supported with 
https://github.com/Azure/azure-powershell/releases/tag/v6.1.0-May2018
