### ISSUE TITLE
 Set-AzureRmSiteRecoveryVaultSettings seems to be broken with ARSVault

### ISSUE THREAD

**Issue by rvdouderaa** [Azure/azure-powershell#5029]
### Cmdlet(s)
Set-AzureRmSiteRecoveryVaultSettings 

### PowerShell Version

5.1.14393.1770

### Module Version
5.0.1
### OS Version
Windows 10 (10.0.14393.1770)
### Description
set-AzureRmSiteRecoveryVaultSettings -ARSVault $vault seems to be incomplete in configuring the vault settings. When issueing an get-AzureRmSiteRecoveryVaultSettings the resourcename and resourcegroupname is not set (and there is an typo in ResourceType)
```
ResourceName      : 
ResourceGroupName : 
ResourceNamespace : Microsoft.SiteRecovery
ResouceType       : SiteRecoveryVault
```
This is also happening on Azure after a module update!

### Script/Steps for Reproduction
```
Add-AzureRMAccount
Get-AzureRmRecoveryServicesVault -Name asr-prd-01-rsv | Set-AzureRmRecoveryServicesVaultContext
$vault = Get-AzureRmRecoveryServicesVault -Name asr-prd-01-rsv
Set-AzureRmSiteRecoveryVaultSettings -ARSVault $vault 
```
When, for instance, issuing Get-AzureRMSiteRecoveryProtectionContainer, the following error is shown.

```
Get-AzureRmSiteRecoveryProtectionContainer : Operation failed.

ClientRequestId: 
Vault Settings are missing. Please import Vault Settings and verify the same
```

**Comment by cormacpayne** [comment]
@rvdouderaa would you mind setting `DebugPreference = "Continue"`, running the above set of commands again, and responding with the resulting debug output?

**Comment by rvdouderaa** [comment]
@cormacpayne The debug output contains a lot of private information. Is there any other way to provide you with the information needed?

**Comment by maddieclayton** [comment]
@rvdouderaa Could you send us the debug output with the confidential information redacted?

**Comment by Jchakhachiro** [comment]
Hello I'm having the same issue 

PS C:\terraform> New-AzureRmSiteRecoveryFabric -Name $SiteName -Debug
Start-Sleep -Seconds 30
WARNING: The command 'New-AzureRmSiteRecoveryFabric' is obsolete. This cmdlet has been marked for deprecation in an upcoming release. Please use the New-AzureRmRecove
ryServicesAsrFabric cmdlet from the AzureRm.RecoveryServices.SiteRecovery module instead.
DEBUG: 15:19:51 - NewAzureRmSiteRecoveryFabric begin processing with ParameterSet 'Default'.
DEBUG: 15:19:54 - using account id 'Jack.Chakhachiro@clouddirect.net'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'Jack.Chakhachiro@clouddirect.net', environment: 'AzureCloud', tenant: '2d2006bf-2fde-473c-8ce4-ea5307e8
eb99'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/05/2018 15:19:54:  - TokenCache: Serializing token cache with 2 items.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/05/2018 15:19:54:  - TokenCache: Serializing token cache with 2 items.

DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '2d2006bf-2fde-473c-8ce4-ea5307e8eb99', Endpoint: 'https://login.microsoftonline.co
m/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', Validat
eAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/2d2006bf-2fde-473c-8ce4-ea5307e8eb99/', CorrelationId:
 '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '2d2006bf-2fde-473c-8ce4-ea5307e8eb99', AdEndpoint: 'https://login.microsoftonlin
e.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/05/2018 15:19:54: 898fdcfd-8183-49ec-8438-aeb61a29e587 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/2d2006bf-2fde-473c-8ce4-ea5307e8eb99/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (2 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 02/05/2018 15:19:54: 898fdcfd-8183-49ec-8438-aeb61a29e587 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/05/2018 15:19:54: 898fdcfd-8183-49ec-8438-aeb61a29e587 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 02/05/2018 15:19:54: 898fdcfd-8183-49ec-8438-aeb61a29e587 - TokenCache: 44.15369855 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/05/2018 15:19:54: 898fdcfd-8183-49ec-8438-aeb61a29e587 - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/05/2018 15:19:54: 898fdcfd-8183-49ec-8438-aeb61a29e587 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: P5THooM+BEbzy94RyWOUbhco0AVkJ8/QFPXraTM=
	Refresh Token Hash: I/1sc+KMlSHagxx9EtxxfCyhL5TxxR/vnPn3BaJvLgec=
	Expiration Time: 02/05/2018 16:04:03 +00:00
	User Hash: qlqYvAYc0eMCpfgwAz8N9ExqKSLdqjRF61Yq9OcOMB4=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/05/2018 15:19:54:  - TokenCache: Serializing token cache with 2 items.

DEBUG: [Common.Authentication]: Received token with LoginType 'LiveId', Tenant: '2d2006bf-2fde-473c-8ce4-ea5307e8eb99', UserId: 'Jack.Chakhachiro@clouddirect.net'
New-AzureRmSiteRecoveryFabric : Operation failed.
ClientRequestId: 
Vault Settings are missing. Please import Vault Settings and verify the same
At line:1 char:1
+ New-AzureRmSiteRecoveryFabric -Name $SiteName -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmSiteRecoveryFabric], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.SiteRecovery.NewAzureRmSiteRecoveryFabric
 
DEBUG: AzureQoSEvent: CommandName - New-AzureRmSiteRecoveryFabric; IsSuccess - False; Duration - 00:00:08.2001594; Exception - System.Exception: Operation failed.
ClientRequestId: 
Vault Settings are missing. Please import Vault Settings and verify the same ---> System.InvalidOperationException: Vault Settings are missing. Please import Vault Se
ttings and verify the same
   at Microsoft.Azure.Commands.SiteRecovery.PSRecoveryServicesClient.GetSiteRecoveryClient()
   at Microsoft.Azure.Commands.SiteRecovery.PSRecoveryServicesClient.CreateAzureSiteRecoveryFabric(String fabricName, String fabricType)
   at Microsoft.Azure.Commands.SiteRecovery.NewAzureRmSiteRecoveryFabric.ExecuteSiteRecoveryCmdlet()
   at Microsoft.Azure.Commands.SiteRecovery.SiteRecoveryCmdletBase.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.SiteRecovery.SiteRecoveryCmdletBase.HandleException(Exception ex)
   at Microsoft.Azure.Commands.SiteRecovery.SiteRecoveryCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 15:20:00 - NewAzureRmSiteRecoveryFabric end processing.
DEBUG: 15:20:00 - NewAzureRmSiteRecoveryFabric end processing.

**Comment by cormacpayne** [comment]
Closing as this cmdlet no longer exists. Please feel free to re-open this issue if you are seeing this problem when using the `AzureRM.RecoveryServices.SiteRecovery` cmdlets.
