### ISSUE TITLE
Disable-AzureRmVmssDiskEncryption fails if there is any other extension other than ‘AzureDiskEncryption’ extension on VMSS

### ISSUE THREAD

**Issue by v-viban** [Azure/azure-powershell#5038]
### Cmdlet(s)

`Disable-AzureRmVmssDiskEncryption`

### PowerShell Version

Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

```
PSVersion            - 5.1.16299.15
```

### OS Version

```
BuildVersion         - 10.0.16299.15  
```

### Description

Disable-AzureRmVmssDiskEncryption fails if there is any other extension other than ‘AzureDiskEncryption’ extension on VMSS (Windows OS)

### Debug Output

Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
Also debug log file attached here. 
[DisableVMSSDELogs.txt](https://github.com/Azure/azure-powershell/files/1509355/DisableVMSSDELogs.txt)

```
PS D:\>>> Disable-AzureRmVmssDiskEncryption -ResourceGroupName 'VMMSEnableDETestRG' -VMScaleSetName 'nt1vm' -Debug -Verbose *>&1 | foreach-object {$_.ToString()} | Out-File 'DisableDELogs.txt' 
Disable-AzureRmVmssDiskEncryption : Extension, AzureDiskEncryption,  is not installed in the VM Scale Set.
At line:1 char:1
+ Disable-AzureRmVmssDiskEncryption -ResourceGroupName 'VMMSEnableDETes ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Disable-AzureRmVmssDiskEncryption], ArgumentException
    + FullyQualifiedErrorId : InvalidArgument,Microsoft.Azure.Commands.Compute.Extension.AzureDiskEncryption.RemoveAzureVmssDiskEncryptionCommand
```

### Script/Steps for Reproduction
1. Deploy Windows Cluster to Azure
2. Enable VMSS Disk Encryiption using Set-AzureRmVmssDiskEncryptionExtension
3. Wait for completion
4. Verify if disk encryption enables for OS volume
5. Now to try disable disk  encryption using Disable-AzureRmVmssDiskEncryption
it says - Disable-AzureRmVmssDiskEncryption : Extension, AzureDiskEncryption,  is not installed in the VM Scale Set.
It seems it didn't work if there is any other extension other than ‘AzureDiskEncryption’ extension on VMSS.

**Comment by v-viban** [comment]
Please assign this to @hyonholee
Thanks

**Comment by cormacpayne** [comment]
@ejarvi Hey Eric, would you mind taking a look at this issue?
