### ISSUE TITLE
ARM: Set-AzureVMCustomScriptExtension encounter a NullReferenceException when StorageAccountName is not under the same ResourceGroup as specified in ResourceGroupName

### ISSUE THREAD

**Issue by slapointe** [Azure/azure-powershell#504]
Context:
Azure-powershell version: 0.9.3
PSVersion                      5.0.10018.0                                                                             
WSManStackVersion              3.0                                                                                     
SerializationVersion           1.1.0.1                                                                                 
CLRVersion                     4.0.30319.0                                                                             
BuildVersion                   10.0.9800.0                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.2                                                                                     

Steps to reproduce:
Invoke "Set-AzureVMCustomScriptExtension" with the StorageAccountName parameter with a storage account that is not under the resource group specified in ResourceGroupName parameter

Expected behavior:
The cmdlet perform internal validations and give a more appropriate error message saying the storage account is not under the specified resource group instead of an uncatched exception.

Encountered behavior:
The termination of the script and the following error:
[10,1: Set-AzureVMCustomScriptExtension] Object reference not set to an instance of an object.

**Comment by singhkay** [comment]
I think there is an improvement here that the service side can make so that the error message is consistent across all clients rather than PS building special logic for this. I'll forward this to service team.

**Comment by slapointe** [comment]
I completely agree with you Kay. 

The call is located in method Microsoft.Azure.Commands.Compute.SetAzureVMCustomScriptExtensionCommand.GetStorageKey(string storageName)

-> storageClient.StorageAccounts.GetProperties(this.ResourceGroupName, storageName);

**Comment by markcowl** [comment]
Assignign to appropriate internal team

**Comment by singhkays** [comment]
Closing as fixed by #2615
