### ISSUE TITLE
Inconsistent parameter naming in Machine Learning Web Services cmdlets

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#5043]
### Description
In some MLWebServices cmdlets, the location parameter is named "Location" while in others is it named "Region".  These two should at least have aliases that match each other.

```
Get-AzureRmMlWebService
   [-ResourceGroupName <String>]
   [-Name <String>]
   [-Region <String>]
   [-DefaultProfile <IAzureContextContainer>]
   [<CommonParameters>]

New-AzureRmMlWebService
   -ResourceGroupName <String>
   -Location <String>
   -Name <String>
   -DefinitionFile <String>
   [-Force]
   [-DefaultProfile <IAzureContextContainer>]
   [-WhatIf]
   [-Confirm]
   [<CommonParameters>]
```

**Comment by maddieclayton** [comment]
@NonStatic2014 Can you take a look at this?

**Comment by cormacpayne** [comment]
@NonStatic2014 ping

**Comment by v-strudm-msft** [comment]
We see this was posted over two years ago, but was never addressed so are closing it. Our apologies. Should this still be an issue, please re-open this issue and we will respond on a timely basis. Thank you.
