### ISSUE TITLE
Set-AzureRmNetworkSecurityGroup does not support -whatif.

### ISSUE THREAD

**Issue by isaacegglestone** [Azure/azure-powershell#5051]
### PowerShell Version

PSVersion                      5.1.14409.1012

### Module Version
5.0.1

### OS Version
10.0.14409.1012

### Description
Set-AzureRmNetworkSecurityGroup does not support -whatif.

### Debug Output

VERBOSE: Creating updated rule name IsaacTestingAutoUpdate
VERBOSE: Updating NSG: Test-NSG-NSG
Set-AzureRmNetworkSecurityGroup : A parameter cannot be found that matches parameter name 'Whatif'.
At C:\gitrepos\NetworkSecurityGroup.Waf\NetworkSecurityGroups\AzureCustomRMNetworkSecurityGroup.ps1:715 char:75
+ ... $ExistingNSG = $ExistingNSG | Set-AzureRmNetworkSecurityGroup -Whatif
+                                                                   ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-AzureRmNetworkSecurityGroup], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.Network.SetAzureNetworkSecurityGroupCommand

### Script/Steps for Reproduction

Run Set-AzureRMNetworkSecurityGroup with -whatif set.

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft Hey Deepak, would you mind taking a look at this issue? Looks like `SupportsShouldProcess` is not implemented for the above cmdlet. We should see if there are any other Network cmdlets that don't implement this that should.

**Comment by cormacpayne** [comment]
@chandrasekarsrinivasan  Hey Chandrasekar, would you mind taking a look at this issue?

**Comment by EvgenyAgafonchikov** [comment]
Networking monthly branch has [fix for this](https://github.com/Azure/azure-powershell/blob/network-october-release/src/ResourceManager/Network/Commands.Network/NetworkSecurityGroup/SetAzureNetworkSecurityGroupCommand.cs#L25)
Need to be closed after merging in preview.

**Comment by EvgenyAgafonchikov** [comment]
[Related changes](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Network/Commands.Network/NetworkSecurityGroup/SetAzureNetworkSecurityGroupCommand.cs#L25) were merged
