### ISSUE TITLE
New-AzureRmServiceBusNamespace : Error information misleading/inaccurate

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#5055]
### Cmdlet(s)
New-AzureRmServiceBusNamespace

### PowerShell Version
5.1.14409.1012

### Module Version
5.0.0 

### OS Version
10.0.14409.1012 

### Description

Error information misleading/inaccurate when trying to create New ARM SB Namespace. However only when debugging the actual error is exposed.

New-AzureRmServiceBusNamespace -ResourceGroupName something -Location "East US" -Name "something" -SkuName Standard
New-AzureRmServiceBusNamespace : Operation returned an invalid status code 'BadRequest'
At line:1 char:1
+ New-AzureRmServiceBusNamespace -ResourceGroupName something - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmServiceBusNamespace], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceBus.Commands.Namespace.NewAzureRmServiceBusNamespace

### Debug Output

============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/9765695156-0bdce2/resourceGroups/something/providers/Microsoft.ServiceBus/namespaces/something?api-version=2017-04-0
1

Headers:
x-ms-client-request-id        : 5645d5c6-ff9d1366172df
accept-language               : en-US

Body:
{
  "sku": {
    "name": "Standard"
  },
  "location": "East US"
}

============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-request-id               : f31a46ed-8016-4c56-4a24f22_M2_M2
Server-SB                     : Service-Bus-Resource-Provider/SN1
Cache-Control                 : no-cache
Server                        : Service-Bus-Resource-Provider/SN1,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 01e94ff8-715e-4f1-01d4bd33fae7
x-ms-routing-request-id       : EASTUS:20171130T190101Z:01e94ff8-715d1-01d4bd33fae7
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Date                          : Thu, 30 Nov 2017 19:01:01 GMT

Body:
{
  "error": {
    "message": "**The specified service namespace is not available.** CorrelationId: 01e94fff71-86d1-01d4bd33fae7",
    "code": "BadRequest"
  }
}

**Comment by cormacpayne** [comment]
@v-Ajnava Hey Ajit, would you mind taking a look at this issue? It looks like the proper error is not being bubbled up to the user. This should be an easy fix.

**Comment by v-Ajnava** [comment]
The namespace name provided is already used, you check the namespace name availability by using 'Test-AzureServiceBusName'  cmdlet.

**Comment by rajaprad** [comment]
I am aware and understand that the namespace name is already in use. This issue specifically targets on the error message written back to the caller - which is misleading and not useful.

**Comment by cormacpayne** [comment]
@v-Ajnava Hey Ajit, would you mind responding to the above comment?

**Comment by v-Ajnava** [comment]
This issue is fixed and is in release from Aug 2018.
