### ISSUE TITLE
New-AzureRmServiceBusTopic : No option to Disable AutoDeleteOnIdle to let the topic live forever

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#5057]
### Cmdlet(s)
New-AzureRmServiceBusTopic

### PowerShell Version
5.1.14409.1012

### Module Version
5.0.0

### OS Version
10.0.14409.1012  

### Description

There is no option/documentation available on Topic Creation to disable AutoDeleteOnIdle. I want the Topic to live forever even when being idle.

Cmdlet Documentation does not mention anything on this either.
[https://docs.microsoft.com/en-us/powershell/module/azurerm.servicebus/new-azurermservicebustopic?view=azurermps-5.0.0](url)

This option was available in ACS servicebus and the value can be made -1 and the topic never gets deleted.

New-AzureRmServiceBusTopic -ResourceGroupName something -Namespace something -Name something -EnablePartitioning $true -DefaultMessageTimeToLive 2 -DuplicateDetectionHistoryTimeWindow 5 -EnableBatchedOperations $true -MaxSizeInMegabytes 5120 -RequiresDuplicateDetection $true

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

New-AzureRmServiceBusTopic -ResourceGroupName something -Namespace something -Name remotestartqueue -EnablePartitioning $true -DefaultMessageTimeToLive 2 -DuplicateDetectionHistoryTimeWindow 5 -EnableBatchedOperations $true -MaxSizeInMegabytes 5120 -RequiresDuplicateDetection $true

**Comment by v-Ajnava** [comment]
You can set -AutoDeleteOnIdle to timespan.maxvalue (10675199.02:48:05.4775807) achieving similar to disable AutoDeleteIdle

**Comment by rajaprad** [comment]
Thanks for the info. is there an official documentation on this workaround/feature ?

**Comment by cormacpayne** [comment]
Closing as this has been resolved. @v-Ajnava you may want to look at calling out this information in the docs for the cmdlet
