### ISSUE TITLE
Get-AzureRmResource - ErrorAction Preference not taking effect

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-powershell#5065]
### Cmdlet(s)
Get-AzureRmResource

### PowerShell Version
5.1.14409.1012

### Module Version
5.0.0

### OS Version
10.0.14409.1012

### Description
Get-AzureRmResource -ResourceName pradebban -ResourceType 'Microsoft.ServiceFabric/clusters' -ResourceGroupName "pradebban" -ErrorAction **SilentlyContinue**

Get-AzureRmResource : ResourceNotFound : The Resource 'Microsoft.ServiceFabric/clusters/pradebban' under resource group
'pradebban' was not found.
At line:1 char:1
+ Get-AzureRmResource -ResourceName pradebban -ResourceType 'Microsoft. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : ResourceNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceC
   mdlet

### Debug Output

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/5-4136-0be554/resourceGroups/pradebban/providers/Microsoft.Serv
iceFabric/clusters/pradebban?api-version=2016-09-01

Headers:
User-Agent                    : PSVersion/v5.1.14409.1012,AzurePowershell/v5.0.0
ParameterSetName              : GetByNameGroupAndType
CommandName                   : Get-AzureRmResource

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 1fe14bei
x-ms-correlation-request-id   : 8fe14be
x-ms-routing-request-id       : EASTUS:20171201T150032Z8-fe1i4bei
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Fri, 01 Dec 2017 15:00:31 GMT

Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.ServiceFabric/clusters/pradebban' under resource group 'pradebban' was not found."
  }
}

Get-AzureRmResource : **ResourceNotFound** : The Resource 'Microsoft.ServiceFabric/clusters/pradebban' under resource group
'pradebban' was not found.
At line:1 char:1
+ Get-AzureRmResource -ResourceName pradebban -ResourceType 'Microsoft. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : ResourceNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceC
   mdlet

### Script/Steps for Reproduction

Provide a resource group/resource name which does not exist and try to suppress the error with SilentlyContinue

Get-AzureRmResource -ResourceName pradebban -ResourceType 'Microsoft.ServiceFabric/clusters' -ResourceGroupName "pradebban" -ErrorAction **SilentlyContinue**

**Comment by markcowl** [comment]
@vivsriaus Verified.  Can you take a look - the default ProcessRecord implementation in AzureRMCmdlet will simply write to the error stream, you should copy this code in your ProcessRecord

**Comment by cormacpayne** [comment]
I believe this will be resolved in PR https://github.com/Azure/azure-powershell/pull/6008

**Comment by cormacpayne** [comment]
The fix for this should be available on May 7th in version 6.0.0 of `AzureRM` (version 6.0.0 of `AzureRM.Resources`). Please re-open this issue if the problem persists.
