### ISSUE TITLE
Extensibility for cmdlets that use custom SDKs

### ISSUE THREAD

**Issue by rahuldutta90** [Azure/azure-powershell#5071]
### Cmdlet(s)
Enable powershell debugging extensibility to work for cmdlets which use a custom data plane SDK.

### PowerShell Version
5.0.1

### Description
Currently by design Azure data lake dataplane SDK does not use HttpClient, so the client creation is different from other client creations that inherit from Microsoft.Rest.ServiceClient. This is why the client do not have customizations like Delegating Handlers.

Opening this issue per request from @markcowl

**Comment by cormacpayne** [comment]
@rahuldutta90 is this still an issue?

**Comment by rahuldutta90** [comment]
I think now we have debug ability and exception handling. So now this hsould not be an issue.
