### ISSUE TITLE
New-AzureRmLogicApp Unexpected character encountered while parsing value: h.

### ISSUE THREAD

**Issue by mdeery** [Azure/azure-powershell#5074]
Cmdlet(s)

New-AzureRmLogicApp

Module Version

5.0.0

Description

New-AzureRmLogicApp -ResourceGroupName "rsg-hcms-itsms-eds-candidate" -Name "la-hcms-itsms-eds-candidate" -DefinitionFilePath $(System.DefaultWorkingDirectory)/$(Release.DefinitionName)/drop/LogicApp.json -ParameterFilePath $(System.DefaultWorkingDirectory)/$(Release.DefinitionName)/drop/LogicApp.parameters.dev.json -Location "australiasoutheast" -State "Enabled"

##[error]Unexpected character encountered while parsing value: h. Path '', line 0, position 0.

**Comment by cormacpayne** [comment]
@mdeery would you mind providing the debug output from the above command by setting `$DebugPreference = "Continue"` and re-running the above command?

**Comment by mdeery** [comment]
[ERROR] New-AzureRmLogicApp : Unexpected character encountered while parsing value: h. 
[ERROR] Path '', line 0, position 0.
[ERROR] At C:\src\Integration\rsg-hcms-itsms-eds-candidate\rsg-hcms-itsms-eds-candidate
[ERROR] \rsg-hcms-itsms-eds-candidate\Deploy.ps1:46 char:1
[ERROR] + New-AzureRmLogicApp -ResourceGroupName $fullResourceGroupName -Name " ...
[ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]     + CategoryInfo          : CloseError: (:) [New-AzureRmLogicApp], JsonReade 
[ERROR]    rException
[ERROR]     + FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.NewAzu 
[ERROR]    reLogicAppCommand
[ERROR]  
[DEBUG] AzureQoSEvent: CommandName - New-AzureRmLogicApp; IsSuccess - False; Duration - 00:00:00.0239421; Exception - Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: h. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Azure.Commands.LogicApp.Utilities.CmdletHelper.GetParametersFromFile(String parametersFilePath)
   at Microsoft.Azure.Commands.LogicApp.Cmdlets.NewAzureLogicAppCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
[DEBUG] Finish sending metric.
[DEBUG] 5:24:33 PM - NewAzureLogicAppCommand end processing.
[DEBUG] 5:24:33 PM - NewAzureLogicAppCommand end processing.

**Comment by mdeery** [comment]
I misunderstood what template the cmdlet required

**Comment by amuneeb** [comment]
I am having similar issue with the same command:

**COMMAND**
New-AzureRmLogicApp -ResourceGroupName "resourcegroupforutptesting123" -Name "LogicApp05" -Location "West US 2" -State "Enabled" -DefinitionFilePath "C:\Codebase\Powershell\Definition03.json" -ParameterFilePath "C:\Codebase\Powershell\Parameters03.json"

**Definition03.json**
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {},
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {},
        "triggers": {}
    }
}

**Parameters.json**
{
		"name": "Value",
		"name1": "Value1"
}

**ERROR MESSAGE:** 
New-AzureRmLogicApp : Unexpected character encountered while parsing value: V. Path '', line 0, position 0.
At C:\Codebase\Powershell\armclientAzureLogicApp.ps1:24 char:6
+      New-AzureRmLogicApp -ResourceGroupName "resourcegroupf ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmLogicApp], JsonReaderException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.NewAzureLogicAppCommand

**Comment by dem123-cthulu** [comment]
Same for me 
`Set-AzLogicApp : Unexpected character encountered while parsing value: h. Path '', line 0, position 0.
`
The definition json file is exported directly from another logic app.

It works if I use:
```
$OtherLogicApp = (Get-AzLogicApp -Name OtherLogicApp)
Set-AzLogicApp -ResourceGroupName "OurRG" -Name "LogicApp2" -Definition $otherLogicApp.Definition
```

**Comment by simoniscasesensitive** [comment]
similar to @dem123-cthulu I can create a working Logic App when I grab the .definition directly from another LA, or when I store it in a variable, but as soon as I export it to text and import it again, masheen say no.

> Unexpected character encountered while parsing value: h. Path '', line 0, position 0

`
$ApproveLA = Get-AzLogicApp -ResourceGroupName $RGName -Name "ApproveWF"
$ApproveLADefinition = $ApproveLA.Definition ;  $ApproveLADefinition | set-content $TemplateDefinitionPath
$ApproveLAParameters = $ApproveLA.Parameters ; $ApproveLAParameters | set-content $TemplateParameterPath 
`
### # replace relevant strings here

### Doesn't work but should?
`new-AzLogicApp -location $Location -ResourceGroup $RGName -name $NewLogicAppName -state $State -definitionFilePath $TemplateDefinitionPath -parameterFilePath $TemplateParameterPath 
`
> Unexpected character encountered while parsing value: h. Path '', line 0, position 0

Printing  $ApproveLA.Definition to screen and into Code, compaing to the exported file, they appear character-by-character to be identical.
Presumably it's to do with the file handling. 

### Works but requires access to the original LogicApp (not much use for deployment).
`
new-AzLogicApp -location $Location -ResourceGroup $RGName -name $NewLogicAppName -state $State -definition $ApproveLADefinition -parameters $ApproveLAParameters `

**Comment by kaiaschulz** [comment]
has someone ever find a way to fix this kind of issue?
Still facing the same issue with the newest module version..
