### ISSUE TITLE
Add test automation to validate AzureDiskEncryption prerequisite script

### ISSUE THREAD

**Issue by SudhakaraReddyEvuri** [Azure/azure-powershell#5081]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@SudhakaraReddyEvuri Hey Sudhakar, has this issue been addressed?

**Comment by markcowl** [comment]
closing
