### ISSUE TITLE
Get-AzureRmRecoveryServicesBackupContainer Error at parameter "-FriendlyName" input processing

### ISSUE THREAD

**Issue by DavidD-SE** [Azure/azure-powershell#5089]
### Cmdlet(s)
Get-AzureRmRecoveryServicesBackupContainer

### PowerShell Version
5.1.16299.64

### Module Version
AzureRM.RecoveryServices.Backup v4.0.1 

### OS Version
10.0.16299.64

### Description
The Cmdlet reads a optional Parameter -FriendlyName. 
The error is: when entering a String Variable at the Cmdlet the Output every time is empty. But giving the VMName directly as String at the Cmdlet (without use of a variable) it works

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
prerequisites: Context to Recovery Services Vault is set

PS C:\WINDOWS\system32> Get-AzureRmRecoveryServicesBackupContainer -ContainerType "AzureVM" -Status Registered -FriendlyName $VMname

--> HERE IS THE ERROR - NO OUTPUT

PS C:\WINDOWS\system32> Get-AzureRmRecoveryServicesBackupContainer -ContainerType "AzureVM" -Status Registered -FriendlyName "backuptestVM"

Name                                     ResourceGroupName                        Status               ContainerType       
----                                     -----------------                        ------               -------------       
backuptestVM                             [ProperRGNameOoutput]                       Registered           AzureVM             

PS C:\WINDOWS\system32> $vmname
backuptestvm

**Comment by DavidD-SE** [comment]
Update: Maybe the problem has other causes. I experienced, when using the Cmdlet in Powershell ISE, running only the commands highlighted, the cmdlet does not work at all. When using the "run highlighted" the output is always empty, doesn't matter if using variable or string at the Parameter.

**Comment by cormacpayne** [comment]
@DavidD-SE Hey David, thanks for reporting this issue. Would you mind running the above cmdlets again with `$DebugPreference = "Continue"` set and providing us with the resulting debug stream?

CC: @dragonfly91

**Comment by DavidD-SE** [comment]
PS C:\Users\MYLOCALUSER> $vmrg = "RESOURCEGROUP"
PS C:\Users\MYLOCALUSER> $rsv = Get-AzureRmRecoveryServicesVault -ResourceGroupName $VMRg
PS C:\Users\MYLOCALUSER> Set-AzureRmRecoveryServicesVaultContext -Vault $rsv
PS C:\Users\MYLOCALUSER>
PS C:\Users\MYLOCALUSER> $DebugPreference = "Continue"
PS C:\Users\MYLOCALUSER> $vmname = "backuptestvm"
PS C:\Users\MYLOCALUSER> Get-AzureRmRecoveryServicesBackupContainer -ContainerType "AzureVM" -Status Registered -Friendl
yName $VMname
DEBUG: 10:51:10 - GetAzureRmRecoveryServicesBackupContainer begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 10:51:10 - using account id 'MYACCOUNT'...
DEBUG: Inside Restore. Going to create ResourceClient.
DEBUG: [Common.Authentication]: Authenticating using Account: 'MYACCOUNT', environment:
'AzureCloud', tenant: '30474cde-5811-4f22-b467-a8eeaa6f077b'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10: 6f630559-f2a7-47a9-a420-bd6daa9332ae - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/30474cde-5811-4f22-b467-a8eeaa6f077b/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/18/2017 09:51:10: 6f630559-f2a7-47a9-a420-bd6daa9332ae - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10: 6f630559-f2a7-47a9-a420-bd6daa9332ae - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/18/2017 09:51:10: 6f630559-f2a7-47a9-a420-bd6daa9332ae - TokenCache: 54.8577697566667 minutes left until
token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10: 6f630559-f2a7-47a9-a420-bd6daa9332ae - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10: 6f630559-f2a7-47a9-a420-bd6daa9332ae - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: hWh6bbYoiTcfVqbei/l86KJPRr3XhnBBoUWgJmNQmd4=
 Refresh Token Hash: 148Ew5XYsrEED2eUW3DFSGOBs39dcJ6Kfy8ftaABD4U=
 Expiration Time: 12/18/2017 10:46:02 +00:00
 User Hash: Czjjb8QxTd8USj63md6mqaGnCHB51R1cx8wQj8wv7Rs=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10:  - TokenCache: Serializing token cache with 1 items.
DEBUG: Client Created successfully
DEBUG: [Common.Authentication]: Authenticating using Account: 'MYACCOUNT', environment:
'AzureCloud', tenant: '30474cde-5811-4f22-b467-a8eeaa6f077b'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10: c6c63fed-91a4-4b5a-b227-f8f1598e05de - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/30474cde-5811-4f22-b467-a8eeaa6f077b/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/18/2017 09:51:10: c6c63fed-91a4-4b5a-b227-f8f1598e05de - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10: c6c63fed-91a4-4b5a-b227-f8f1598e05de - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/18/2017 09:51:10: c6c63fed-91a4-4b5a-b227-f8f1598e05de - TokenCache: 54.856980015 minutes left until token in
 cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10: c6c63fed-91a4-4b5a-b227-f8f1598e05de - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10: c6c63fed-91a4-4b5a-b227-f8f1598e05de - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: hWh6bbYoiTcfVqbei/l86KJPRr3XhnBBoUWgJmNQmd4=
 Refresh Token Hash: 148Ew5XYsrEED2eUW3DFSGOBs39dcJ6Kfy8ftaABD4U=
 Expiration Time: 12/18/2017 10:46:02 +00:00
 User Hash: Czjjb8QxTd8USj63md6mqaGnCHB51R1cx8wQj8wv7Rs=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10:  - TokenCache: Serializing token cache with 1 items.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10: 3559a2f1-3e40-49d1-a714-1fee6b5b75fc - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/30474cde-5811-4f22-b467-a8eeaa6f077b/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/18/2017 09:51:10: 3559a2f1-3e40-49d1-a714-1fee6b5b75fc - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10: 3559a2f1-3e40-49d1-a714-1fee6b5b75fc - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/18/2017 09:51:10: 3559a2f1-3e40-49d1-a714-1fee6b5b75fc - TokenCache: 54.85657949 minutes left until token in
cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10: 3559a2f1-3e40-49d1-a714-1fee6b5b75fc - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10: 3559a2f1-3e40-49d1-a714-1fee6b5b75fc - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: hWh6bbYoiTcfVqbei/l86KJPRr3XhnBBoUWgJmNQmd4=
 Refresh Token Hash: 148Ew5XYsrEED2eUW3DFSGOBs39dcJ6Kfy8ftaABD4U=
 Expiration Time: 12/18/2017 10:46:02 +00:00
 User Hash: Czjjb8QxTd8USj63md6mqaGnCHB51R1cx8wQj8wv7Rs=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:10:  - TokenCache: Serializing token cache with 1 items.
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/Subscriptions/779564f2-68e1-402e-90f3-12656a27380a/resourceGroups/RESOURCEGROUP/provi
ders/Microsoft.RecoveryServices/vaults/klgnaftarsv03scus/backupProtectionContainers?$filter=friendlyName eq
'backuptestvm' and backupManagementType eq 'AzureIaasVM' and status eq 'Registered'&api-version=2016-12-01

Headers:
x-ms-client-request-id        : 3e45a187-602d-4292-a418-a17469b48234
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : da5a3aa0-d3c8-4f05-94c4-d41cac4fca50
x-ms-client-request-id        : e1dbfb46-0b94-476b-bf13-7d6deb526e52-PS,e1dbfb46-0b94-476b-bf13-7d6deb526e52-PS
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 14999
x-ms-correlation-request-id   : da5a3aa0-d3c8-4f05-94c4-d41cac4fca50
x-ms-routing-request-id       : WESTEUROPE:20171218T095113Z:da5a3aa0-d3c8-4f05-94c4-d41cac4fca50
Cache-Control                 : no-cache
Date                          : Mon, 18 Dec 2017 09:51:13 GMT
Server                        : Microsoft-IIS/8.0
X-Powered-By                  : ASP.NET

Body:
{
  "value": []
}

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmRecoveryServicesBackupContainer; IsSuccess - True; Duration -
00:00:01.8571297; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 10:51:13 - GetAzureRmRecoveryServicesBackupContainer end processing.
DEBUG: 10:51:13 - GetAzureRmRecoveryServicesBackupContainer end processing.
PS C:\Users\MYLOCALUSER> Get-AzureRmRecoveryServicesBackupContainer -ContainerType "AzureVM" -Status Registered -Friendl
yName "backuptestVM"
DEBUG: 10:51:37 - GetAzureRmRecoveryServicesBackupContainer begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 10:51:37 - using account id 'MYACCOUNT'...
DEBUG: Inside Restore. Going to create ResourceClient.
DEBUG: [Common.Authentication]: Authenticating using Account: 'MYACCOUNT', environment:
'AzureCloud', tenant: '30474cde-5811-4f22-b467-a8eeaa6f077b'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37: d7d23392-3937-443f-964e-0c255f2d4c11 - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/30474cde-5811-4f22-b467-a8eeaa6f077b/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/18/2017 09:51:37: d7d23392-3937-443f-964e-0c255f2d4c11 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37: d7d23392-3937-443f-964e-0c255f2d4c11 - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/18/2017 09:51:37: d7d23392-3937-443f-964e-0c255f2d4c11 - TokenCache: 54.410249965 minutes left until token in
 cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37: d7d23392-3937-443f-964e-0c255f2d4c11 - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37: d7d23392-3937-443f-964e-0c255f2d4c11 - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: hWh6bbYoiTcfVqbei/l86KJPRr3XhnBBoUWgJmNQmd4=
 Refresh Token Hash: 148Ew5XYsrEED2eUW3DFSGOBs39dcJ6Kfy8ftaABD4U=
 Expiration Time: 12/18/2017 10:46:02 +00:00
 User Hash: Czjjb8QxTd8USj63md6mqaGnCHB51R1cx8wQj8wv7Rs=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37:  - TokenCache: Serializing token cache with 1 items.
DEBUG: Client Created successfully
DEBUG: [Common.Authentication]: Authenticating using Account: 'MYACCOUNT', environment:
'AzureCloud', tenant: '30474cde-5811-4f22-b467-a8eeaa6f077b'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37: d2efa38c-63e8-436b-9e0a-70511e8293ef - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/30474cde-5811-4f22-b467-a8eeaa6f077b/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/18/2017 09:51:37: d2efa38c-63e8-436b-9e0a-70511e8293ef - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37: d2efa38c-63e8-436b-9e0a-70511e8293ef - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/18/2017 09:51:37: d2efa38c-63e8-436b-9e0a-70511e8293ef - TokenCache: 54.4099269866667 minutes left until
token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37: d2efa38c-63e8-436b-9e0a-70511e8293ef - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37: d2efa38c-63e8-436b-9e0a-70511e8293ef - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: hWh6bbYoiTcfVqbei/l86KJPRr3XhnBBoUWgJmNQmd4=
 Refresh Token Hash: 148Ew5XYsrEED2eUW3DFSGOBs39dcJ6Kfy8ftaABD4U=
 Expiration Time: 12/18/2017 10:46:02 +00:00
 User Hash: Czjjb8QxTd8USj63md6mqaGnCHB51R1cx8wQj8wv7Rs=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37:  - TokenCache: Serializing token cache with 1 items.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37: 25f3c09c-4a46-4dd6-8837-da836e3f9cc6 - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/30474cde-5811-4f22-b467-a8eeaa6f077b/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/18/2017 09:51:37: 25f3c09c-4a46-4dd6-8837-da836e3f9cc6 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37: 25f3c09c-4a46-4dd6-8837-da836e3f9cc6 - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/18/2017 09:51:37: 25f3c09c-4a46-4dd6-8837-da836e3f9cc6 - TokenCache: 54.4098852316667 minutes left until
token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37: 25f3c09c-4a46-4dd6-8837-da836e3f9cc6 - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37: 25f3c09c-4a46-4dd6-8837-da836e3f9cc6 - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: hWh6bbYoiTcfVqbei/l86KJPRr3XhnBBoUWgJmNQmd4=
 Refresh Token Hash: 148Ew5XYsrEED2eUW3DFSGOBs39dcJ6Kfy8ftaABD4U=
 Expiration Time: 12/18/2017 10:46:02 +00:00
 User Hash: Czjjb8QxTd8USj63md6mqaGnCHB51R1cx8wQj8wv7Rs=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/18/2017 09:51:37:  - TokenCache: Serializing token cache with 1 items.
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/Subscriptions/779564f2-68e1-402e-90f3-12656a27380a/resourceGroups/RESOURCEGROUP/provi
ders/Microsoft.RecoveryServices/vaults/klgnaftarsv03scus/backupProtectionContainers?$filter=friendlyName eq
'backuptestVM' and backupManagementType eq 'AzureIaasVM' and status eq 'Registered'&api-version=2016-12-01

Headers:
x-ms-client-request-id        : ed62082f-3f41-4ee2-8264-f3f5045a0938
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : d0df8221-c9a7-4e41-af22-6508dac48694
x-ms-client-request-id        : 73d53016-aa22-458f-b2e2-65a622a42489,73d53016-aa22-458f-b2e2-65a622a42489
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 14999
x-ms-correlation-request-id   : d0df8221-c9a7-4e41-af22-6508dac48694
x-ms-routing-request-id       : WESTEUROPE:20171218T095139Z:d0df8221-c9a7-4e41-af22-6508dac48694
Cache-Control                 : no-cache
Date                          : Mon, 18 Dec 2017 09:51:39 GMT
Server                        : Microsoft-IIS/8.0
X-Powered-By                  : ASP.NET

Body:
{
  "value": [
    {
      "id":
"/Subscriptions/779564f2-68e1-402e-90f3-12656a27380a/resourceGroups/RESOURCEGROUP/providers/Microsoft.RecoveryServ
ices/vaults/klgnaftarsv03scus/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;klgnaftarg03pr
odvm;backuptestvm",
      "name": "IaasVMContainer;iaasvmcontainerv2;RESOURCEGROUP;backuptestvm",
      "type": "Microsoft.RecoveryServices/vaults/backupFabrics/protectionContainers",
      "properties": {
        "virtualMachineId":
"/subscriptions/779564f2-68e1-402e-90f3-12656a27380a/resourceGroups/RESOURCEGROUP/providers/Microsoft.Compute/virt
ualMachines/backuptestVM",
        "virtualMachineVersion": "Compute",
        "resourceGroup": "RESOURCEGROUP",
        "friendlyName": "backuptestVM",
        "backupManagementType": "AzureIaasVM",
        "registrationStatus": "Registered",
        "healthStatus": "Healthy",
        "containerType": "Microsoft.Compute/virtualMachines",
        "protectableObjectType": "Microsoft.Compute/virtualMachines"
      }
    }
  ]
}


Name                                     ResourceGroupName                        Status               ContainerType
----                                     -----------------                        ------               -------------
backuptestVM                             RESOURCEGROUP                       Registered           AzureVM
DEBUG: AzureQoSEvent: CommandName - Get-AzureRmRecoveryServicesBackupContainer; IsSuccess - True; Duration -
00:00:01.5444108; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 10:51:39 - GetAzureRmRecoveryServicesBackupContainer end processing.
DEBUG: 10:51:39 - GetAzureRmRecoveryServicesBackupContainer end processing.

**Comment by DavidD-SE** [comment]
@cormacpayne @shahabhijeet

**Comment by dragonfly91** [comment]
Hi @DavidD-SE , the -FriendlyName filter is case sensitive. Please use the proper case to get the item that you need. I'm closing this as a non-issue.

Thanks,
Anudeep.

**Comment by DavidD-SE** [comment]
Hi @dragonfly91 ,
thank you for updating my knowledge. Where can I post a feature request? I personally find the case-sensitivity of this parameter not perfect. as I, for example, use this command within a script. This script uses also Get-AzureRMVM, and there the VMname is not case sensitive.
Or maybe you can give me hint, how I check prior to this command, if the VMname was entered correctly case-sensitive?
Thank you.
Kind regards, David
