### ISSUE TITLE
CreateArmClient cause deadlock when run on same SynchronizationContext

### ISSUE THREAD

**Issue by sagawater** [Azure/azure-powershell#5091]
### Module Version
Microsoft.Azure.Commands.Common.Authentication, Version=3.4.0.0

### Description
Calling 
`AzureSession.ClientFactory.CreateArmClient<WebSiteManagementClient>(AzureRmProfileProvider.Instance.Profile.Context,` `AzureEnvironment.Endpoint.ResourceManager)` will cause a deadlock when it's called in a powershell environnement configured to run in a single thread SynchronizationContext.

You can see a code example to run an asynchronous function on the current thread:
https://msdnshared.blob.core.windows.net/media/MSDNBlogsFS/prod.evol.blogs.msdn.com/CommunityServer.Components.PostAttachments/00/10/25/90/49/AsyncPump.cs 

### Script/Steps for Reproduction
A test could be something like 
`AsyncPump.Run(async () =>
                                   {
                                       AzureSession.ClientFactory.CreateArmClient<T>(AzureRmProfileProvider.Instance.Profile.Context, AzureEnvironment.Endpoint.ResourceManager);
                                       await Task.CompletedTask;
                                   })`

### Workaround
`AsyncPump.Run(async () =>
                                   {
                                       await Task.Factory.StartNew(() => AzureSession.ClientFactory.CreateArmClient<T>(AzureRmProfileProvider.Instance.Profile.Context, AzureEnvironment.Endpoint.ResourceManager));
                                   });`

**Comment by markcowl** [comment]
@sagawater Cannot repro this on the latest profile version.  Please update andopen a new issue if you see this again
