### ISSUE TITLE
Validate and Integrate new MSI into release process

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5113]
## Comments @maddieclayton 
- Each of these scenarios should specify an expected outcome [what do you expect the ending module layout to be], where do you expect an informative error, etc.
- This should explicitly include uninstall scenarios
  - When will we attempt uninstall via the msi: _Expects the version of the modules installed by the MSI version to be removed_
  - When will we attempt uninstall via Uninstall-Module: _Expects that the most recent version of the module is deleted_
  - What is the expected outcome
- When installing modules from the gallery after a new msi install, we should include
  - Individual module update (e.g. AzureRM.Compute) I think this is what you mean by update some modules, but want to be sure
  - Updating AzureRM

### Description
- Validate correct installation in the following scenarios
  - [x] Graceful failure in PowerShell 3 and PowerShell 4: _Expects an informative error about upgrading to PowerShell 5._
  - [x] Graceful failure when .Net version < 4.5.2
  - [x] Clean Install, PowerShell 5.0: 
  - [x] Clean Install, PowerShell 5.1: _Expects all modules to be installed in Program Files and Program Files x86.  Uninstall from MSI should remove all files in both directories._
    - Installs modules in Program Files and Program Files x86 under WindowsPowerShell
    - Uninstalling program successfully deletes all modules in both directories
  - [x] Update from last installer with old paradigm
  - [x] Try to update to older modules when all modules are installed
      - [x] Modules installed from PSGallery and updated using new MSI: _Expects that old modules will be installed side by side with new modules. Uninstall from MSI should uninstall all modules updated by MSI_
         - Installs old modules side by side with newer modules, doesn't touch modules that were not updated.
         - **Bug 1**
      - [x] Modules installed from new MSI and updated using old MSI: _Expects error that newer modules are currently installed_
        - Fails gracefully
      - [x] Modules installed from new MSI and updated using PSGallery: _Expects old modules will be installed side by side with new modules. Uninstall from MSI should remove all modules installed by MSI_
         - Adds side by side older versions, does not touch unchanged versions
         - **Uninstalling deletes all the most current versions of modules, including those were not updated by PSGallery.  You are left with a set of semi-random modules that happen to have been updated.**
  - [x] Try to update to older modules when only some modules are installed
    - [x] Modules installed from PSGallery and updated using new MSI: _Expects that old modules will be installed side by side with new modules. Uninstall from MSI should uninstall all modules updated by MSI_
         - Installs old modules side by side with newer modules, doesn't touch modules that were not updated. 
         - **Bug 1**
     - [x] Modules installed from new MSI and updated using old MSI: _Expects error that newer modules are currently installed_
        - Fails gracefully
    - [x] Modules installed from new MSI and updated using PSGallery:  _Expects old modules will be installed side by side with new modules. Uninstall from MSI should remove all modules installed by MSI_
       - Adds side by side older versions, does not touch unchanged versions
       - **Uninstalling deletes all the most current versions of modules, including those were not updated by PSGallery.  You are left with a set of semi-random modules that happen to have been updated.**
  - [x] Try to update to same version of modules when all modules are installed
    - [x] Modules installed from PSGallery and updated using new MSI: _Expects modules to be installed in PFx86, does not modify modules in Program Files.  Uninstall from MSI should remove only modules installed by MSI_
         - Installs modules in Program Files x86, does not overwrite modules in Program Files
         - If you uninstall from settings, the modules from Program Files x86 will be deleted
         - **Bug 1**
    - [x] Modules installed from old MSI and updated using new MSI: _Expects all files installed by old MSI to be removed and all modules to be installed by MSI.  Uninstalling from MSI should remove all modules_
         - Installs modules in PF&PFx86 under WindowsPowerShell and removes the modules from the old installer found in PFx86/Microsoft SDKs/Azure
    - [x] Modules installed from new MSI and updated using PSGallery: _Expects no modification.  Uninstall from MSI should remove all files_
        - Does not change any of the modules, does not throw an error
        - Uninstalling program successfully deletes all modules
    - [x] Use Update-Module to update new MSI 
      - No update, uninstall works as expected
  - [x] Try to update to same version of modules when only some modules are installed
    - [x] Modules installed from PSGallery and updated using new MSI:  _Expects modules to be installed in PFx86, does not modify modules in Program Files.  Uninstall from MSI should remove only modules installed by MSI_
        - All modules are loaded except for the module that was previously installed by PSGallery, which remains unchanged.
        - If you uninstall the program, all files are deleted except the ones installed by PSGallery
        -  **Bug 1**
    - [x] [**_Note: I don't think this one is necessary_**] Modules installed from old MSI and updated using new MSI: _Expects all files installed by old MSI to be removed and all modules to be installed by MSI.  Uninstalling from MSI should remove all modules_
        - Installs modules in PF&PFx86 under WindowsPowerShell and removes the modules from the old installer found in PFx86/Microsoft SDKs/Azure
    - [x] Modules installed from new MSI and updated using PSGallery: _Expects new MSI to install modules not installed by PSGallery. Uninstall from MSI should only remove those files installed by MSI_
        - Installs all modules except the module that was previously installed by the new MSI, which remains unchanged.
       - If you uninstall the program, ***all files are deleted.***
    - [x] Use Update-Module to update new MSI 
      - No update, uninstall works as expected
  - [x] Try to update to newer version of modules when all modules are installed
    - [x] Modules installed from PSGallery and updated using new MSI: _Expects new modules to be installed side by side with old modules.  Uninstall from MSI should only remove modules installed by MSI_
        - Installs a new version side by side with the previous version for all modules that have been updated since the version installed by PSGallery (doesn't touch modules that have not been updated)
        - If you uninstall the program, all modules are deleted from PFx86, and, for modules with new side-by-side, the version installed by the MSI is deleted leaving the previous version unchanged.
        - **Bug 1**
    - [x] Modules installed from old MSI and updated using new MSI: _Expects all files installed by old MSI to be removed and all modules to be installed by MSI.  Uninstalling from MSI should remove all modules_
        - Installs modules in PF&PFx86 under WindowsPowerShell and removes the modules from the old installer found in PFx86/Microsoft SDKs/Azure
    - [x] Modules installed from new MSI and updated using PSGallery: _Expects new modules to be installed side by side with old modules. Uninstall from MSI should remove all modules originally installed by the MSI, leaving only new modules_
       - Installs new modules side by side with older modules in Program Files
       - If you uninstall the program, all modules installed from original MSI are deleted (any modules with new modules installed by PSGallery remain with only the latest version).
    - [x] Use Update-Module to update _Expects new modules to be installed side by side with old modules. Uninstall from MSI should remove all modules originally installed by the MSI, leaving only new modules_
       - Installs new modules side by side with older modules in Program Files
       - If you uninstall the program, all modules installed from original MSI are deleted (any modules with new modules installed by PSGallery remain with only the latest version).
  - [x] Try to update to newer version of modules when only some modules are installed
    - [x] Modules installed from PSGallery and updated using new MSI: _Expects new modules to be installed side by side with old modules.  Uninstall from MSI should only remove modules installed by MSI_
        - Installs new version side by side with previous version (requires -Force)
        - If you uninstall the program, you are left with the previous version installed by PSGallery
    - [x] [**_Note: I don't think this one is possible - the old MSI only installs all modules_**] Modules installed from old MSI and updated using new MSI: _Expects all files installed by old MSI to be removed and all modules to be installed by MSI.  Uninstalling from MSI should remove all modules_
        - Installs modules in PF&PFx86 under WindowsPowerShell and removes the modules from the old installer found in PFx86/Microsoft SDKs/Azure
    - [x] Modules installed from new MSI and updated using PSGallery: _Expects new modules to be installed side by side with old modules. Uninstall from MSI should remove all modules originally installed by the MSI, leaving only new modules_
        - Installs new modules side by side with old modules, does not replace unchanged modules
        - If you uninstall the program, it will delete not only the module versions which were installed by the MSI, but also modules that were installed by MSI, then uninstalled by me, then installed by the PSGallery with the same version.  This doesn't seem like bad behavior, but perhaps unexpected.
    - [x] Use Update-Module to update. _Expects new modules to be installed side by side with old modules. Uninstall from MSI should remove all modules originally installed by the MSI, leaving only new modules_
      - Installs newer module side by side with old, uninstall removes all but updated modules.
  - [x] Update within installer using new paradigm
    - [x] Clean install old modules using new MSI and then update to newer modules from new MSI: _Expects old modules to be removed and new modules to be installed.  Uninstall from MSI should remove all files_
        - Deletes old modules and reinstalls new modules
        - All modules are deleted on uninstall
    - [x] Clean install new modules using new MSI and then update to old modules from new MSI [**this should be disallowed**]: _Expects error stating that newer modules have previously been installed_
        - Fails gracefully
    - [x] Clean install current modules using new MSI and then update to current module from new MSI [**this should be a no-op**]: _Expects installer to go to the page allowing them to repair or remove, with no option to install_
        - Does not reinstall, gives you the option to repair.

- **BUG 1 (will not fix): Install a module from PSGallery. Run the new MSI installer with the same version of the module as installed from PSGallery. Uninstall Azure PowerShell. You will see that the content of all the modules is deleted from Program Files/WindowsPowerShell/ModuleName/VersionNumber, but the folders are not deleted. In this case, the folders should be cleaned up**

- Add steps to release documentation on creating installer
     - To create the MSI, run ```C:/azure-powershell/setup/generate.ps1 -version <VersionNumber> -force```
         - If you want to use the modules from TestGallery rather than PSGallery, use the set the -repository parameter to TestGallery.
    - Testing Plan:
        - Unless infrastructure changes, testing on PowerShell 3.0 and 4.0 should be unnecessary as the behavior is to gracefully fail
        - Clean install on PowerShell 5.1, run smoke tests.  Uninstall and ensure all modules have been removed.
        - Install on top of previous version of PSGallery modules, run smoke test.  Uninstall and ensure expected modules are removed.

**Comment by maddieclayton** [comment]
All testing has been completed, testing plan has been put on Cormac's release gist, bugs have been discussed.
