### ISSUE TITLE
Refactor KeyVault data plane cmdlets as FileProvider

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5117]
### Description
Refactor KeyVault data plane to allow mounting a Vault as a drive and acess to Certificates, Secrets, and Keys using file system cmdlets.

- [x] Coordinate with KeyVault team on design, and design of hierarchy
- [ ] Identify and target KeyVault PowerShell conceptual documentation for refactoring usign the new paradigm
- [x] Prototype and evaluate performance, reliability, &c
- [ ] Final implementation
- [ ] Scenario Tests
- [ ] Documentation Updates

### Cost: 20

**Comment by pixelicous** [comment]
What about solving current issues? such as dns replication issues? #1524

**Comment by pixelicous** [comment]
first of all fix the fact that you cannot create keyvault!!! 90% of the time when you create secrets or browse it thorugh the portal it will fail because it didn't propagate through all azure.. first fix issues you have since 2015, then continue to features! #1524 #5326 Azure/azure-powershell#655

**Comment by maddieclayton** [comment]
Closing in favor of: https://github.com/Azure/azure-powershell/issues/6155
