### ISSUE TITLE
Add AsJob Implementation to long-running RM, Storage Management , Network cmdlets

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5119]
### Description

- [x] For each RP, determine which cmdlets could be long-running and adapt the cmdlet to use AsJob implementation
- [x] Adapt one scenario test to use AsJob with Wait-Job and re-record if necessary (it may not be)
- [x] Update release notes, help, identify how-to docs to update
- [ ] re-release module on the gallery at the earliest convenience

**Comment by maddieclayton** [comment]
Related issues: 
https://github.com/Azure/azure-powershell/issues/5214

**Comment by markcowl** [comment]
Fixed
