### ISSUE TITLE
Work with feature teams to implement AsJob for additional modules

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5120]
### Description
Update documentation to include implementation of -AsJob
- [x] Add section to Design guidelines
    - https://github.com/Azure/azure-powershell/wiki/PowerShell-Cmdlet-Design-Guidelines#asjob-parameter
#### Work with service teams to retrofit exsiting modules to use -AsJob parameter.  Each module should include updates to code, at least one covering test, and documentation.
- [ ] Storage data plane
    - @blueww in progress
- [x] Sql
    - https://github.com/Azure/azure-powershell/pull/5244: merged
- [x] WebSites
    - https://github.com/Azure/azure-powershell/pull/5257: merged
- [x] KeyVault
    - https://github.com/Azure/azure-powershell/pull/5300: merged
- [ ] Automation
    - email sent
- [ ] Resources (missing test coverage)
   - https://github.com/Azure/azure-powershell/issues/5216
- [ ] Compute (missing test coverage)
   - https://github.com/Azure/azure-powershell/issues/5215
- [ ] Network (missing test coverage)
   - https://github.com/Azure/azure-powershell/issues/5214

**Comment by maddieclayton** [comment]
Tracking issues: 
https://github.com/Azure/azure-powershell/issues/5409
https://github.com/Azure/azure-powershell/issues/5410
https://github.com/Azure/azure-powershell/issues/5216
https://github.com/Azure/azure-powershell/issues/5215
https://github.com/Azure/azure-powershell/issues/5214

**Comment by maddieclayton** [comment]
All changes made or covered by other issues.
