### ISSUE TITLE
New-AzureStorageContext lists an incorrect permission in Example 9: Create a context by using an SAS token

### ISSUE THREAD

**Issue by rkyttle** [Azure/azure-powershell#5122]
New-AzureStorageContainerSASToken -Name "ContosoMain" -Permission "raud"

Running the above command returns the following:
New-AzureStorageContainerSASToken : Invalid access permission 'raud'.

This can be found in example 9 on https://docs.microsoft.com/en-us/powershell/module/azure.storage/new-azurestoragecontext?view=azurermps-5.0.0#comments-container

Machine this is being executed from:

Name                           Value
----                           -----
PSVersion                      5.1.14393.1914
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1914
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

ModuleType 	Version    	Name                                
---------- 	-------    	----                                
Script     	4.0.0      	Azure.Storage                       
Script     	4.0.1      	AzureRM.KeyVault                    
Script     	4.0.0      	AzureRM.Profile                     
Script     	5.0.0      	AzureRM.Resources

**Comment by blueww** [comment]
@rkyttle 

Thanks for reporting this!
Will update the help soon.

**Comment by blueww** [comment]
Fixed in https://github.com/Azure/azure-powershell/pull/5157#event-1408172118
