### ISSUE TITLE
'Get-Help Login-AzureRmAccount' shows help for Add-AzureRmAccount

### ISSUE THREAD

**Issue by bergmeister** [Azure/azure-powershell#5134]
### Cmdlet(s)

Login-AzureRmAccount

### PowerShell Version
5.1.16299.98
### Module Version
AzureRM 5.1.1      
### OS Version
10.0.16299.98

### Description
`Get-Help Login-AzureRmAccount` shows help for Add-AzureRmAccount.

### Script/Steps for Reproduction
````powershell
Get-Help Login-AzureRmAccoun
````

**Comment by cormacpayne** [comment]
@bergmeister Hey Chris, `Login-AzureRmAccount` is an alias for `Add-AzureRmAccount`, so `Get-Help Login-AzureRmAccount` is going to redirect you to the help content for the cmdlet it is an alias for.

To see the aliases for the Azure PowerShell cmdlets you have loaded into your PowerShell session, run the following command:

```powershell
Get-Alias | where { $_.Source -like "Azure*" } | % { "$($.Name) is an alias for $($_.Definition)" }
```
