### ISSUE TITLE
Example 2 using ExpandPrincipalGroups switch is not valid in markdown help for Get-AzureRmRoleAssignment

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5138]
### Description 

The example shows:

```powershell
PS C:\> Get-AzureRmRoleAssignment -ResourceGroupName testRG -SignInName john.doe@contoso.com -ExpandPrincipalGroup
```

According to the syntax, this combination of parameters is not possible.  Need to update the cmdlet so that it is possible to determine effective role assignments for a given user.

**Comment by darshanhs90** [comment]
fixed in https://github.com/Azure/azure-powershell/commit/496845ba30ca9d6eb8299347216412a92094b089
