### ISSUE TITLE
Get-AzureRmRoleAssignment not worked in Azure China Cloud

### ISSUE THREAD

**Issue by pengzhisun** [Azure/azure-powershell#5143]
### Cmdlet(s)
Get-AzureRmRoleAssignment

### PowerShell Version
5.1.14393.1944

### Module Version
5.1.1

### OS Version
10.0.14393.1944

### Description
The Get-AzureRmRoleAssignment cmdlet in v5.1.1 executed failed in Azure China Cloud with following error message:

Get-AzureRmRoleAssignment : The resource type 'roleAssignments' could not be found in the namespace 'Microsoft.Authorization' for api version '2017-10-01-preview'. The supported api-versions are
'2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01,2015-07-01,2017-05-01'.
At line:1 char:1
+ Get-AzureRmRoleAssignment
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmRoleAssignment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand

### Debug Output
DEBUG: 4:24:33 PM - GetAzureRoleAssignmentCommand begin processing with ParameterSet 'EmptyParameterSet'.
DEBUG: 4:24:33 PM - using account id 'xxx@xxx.partner.onmschina.cn'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxx@xxx.partner.onmschina.cn', environment: 'AzureChinaCloud', tenant: 'xxx-xxx-xxx-xxx-xxx'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33: f4ccb29c-f355-4cfb-baba-66525af29617 - AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.chinacloudapi.cn/xxx-xxx-xxx-xxx-xxx/
 Resource: https://graph.chinacloudapi.cn/
 ClientId: xxx-xxx-xxx-xxx-xxx
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (10 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/14/2017 08:24:33: f4ccb29c-f355-4cfb-baba-66525af29617 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33: f4ccb29c-f355-4cfb-baba-66525af29617 - TokenCache: An item matching the requested resource was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/14/2017 08:24:33: f4ccb29c-f355-4cfb-baba-66525af29617 - TokenCache: 26.70872122 minutes left until token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33: f4ccb29c-f355-4cfb-baba-66525af29617 - TokenCache: A matching item (access token or refresh token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33: f4ccb29c-f355-4cfb-baba-66525af29617 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: xxx
 Refresh Token Hash: xxx
 Expiration Time: 12/14/2017 08:51:16 +00:00
 User Hash: xxx

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33:  - TokenCache: Serializing token cache with 10 items.
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxx@xxx.partner.onmschina.cn', environment: 'AzureChinaCloud', tenant: 'xxx-xxx-xxx-xxx-xxx'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33: 5ce166f6-448b-4f90-88f4-2dcef0ed9828 - AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.chinacloudapi.cn/xxx-xxx-xxx-xxx-xxx/
 Resource: https://management.core.chinacloudapi.cn/
 ClientId: xxx-xxx-xxx-xxx-xxx
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (10 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/14/2017 08:24:33: 5ce166f6-448b-4f90-88f4-2dcef0ed9828 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33: 5ce166f6-448b-4f90-88f4-2dcef0ed9828 - TokenCache: An item matching the requested resource was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/14/2017 08:24:33: 5ce166f6-448b-4f90-88f4-2dcef0ed9828 - TokenCache: 57.5386720983333 minutes left until token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33: 5ce166f6-448b-4f90-88f4-2dcef0ed9828 - TokenCache: A matching item (access token or refresh token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33: 5ce166f6-448b-4f90-88f4-2dcef0ed9828 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: xxx
 Refresh Token Hash: xxx
 Expiration Time: 12/14/2017 09:22:05 +00:00
 User Hash: xxx

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33:  - TokenCache: Serializing token cache with 10 items.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33: b8ec4d90-6b3a-4698-b071-03846f6dae0e - AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.chinacloudapi.cn/xxx-xxx-xxx-xxx-xxx/
 Resource: https://management.core.chinacloudapi.cn/
 ClientId: xxx-xxx-xxx-xxx-xxx
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (10 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/14/2017 08:24:33: b8ec4d90-6b3a-4698-b071-03846f6dae0e - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33: b8ec4d90-6b3a-4698-b071-03846f6dae0e - TokenCache: An item matching the requested resource was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/14/2017 08:24:33: b8ec4d90-6b3a-4698-b071-03846f6dae0e - TokenCache: 57.538430415 minutes left until token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33: b8ec4d90-6b3a-4698-b071-03846f6dae0e - TokenCache: A matching item (access token or refresh token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33: b8ec4d90-6b3a-4698-b071-03846f6dae0e - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: xxx
 Refresh Token Hash: xxx
 Expiration Time: 12/14/2017 09:22:05 +00:00
 User Hash: xxx

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/14/2017 08:24:33:  - TokenCache: Serializing token cache with 10 items.
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.chinacloudapi.cn/subscriptions/xxx-xxx-xxx-xxx-xxx/providers/Microsoft.Authorization/roleAssignments?api-version=2017-10-01-preview

Headers:
x-ms-client-request-id        : b6db6e77-fc05-4f60-be63-b087c6430bd9
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 01797b16-e091-4b32-a934-6ed1aeaa2833
x-ms-correlation-request-id   : 01797b16-e091-4b32-a934-6ed1aeaa2833
x-ms-routing-request-id       : CHINAEAST:20171214T082434Z:01797b16-e091-4b32-a934-6ed1aeaa2833
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Thu, 14 Dec 2017 08:24:33 GMT

Body:
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type 'roleAssignments' could not be found in the namespace 'Microsoft.Authorization' for api version '2017-10-01-preview'. The supported api-versions are
'2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01,2015-07-01,2017-05-01'."
  }
}

Get-AzureRmRoleAssignment : The resource type 'roleAssignments' could not be found in the namespace 'Microsoft.Authorization' for api version '2017-10-01-preview'. The supported api-versions are
'2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01,2015-07-01,2017-05-01'.
At line:1 char:1
+ Get-AzureRmRoleAssignment
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmRoleAssignment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmRoleAssignment; IsSuccess - False; Duration - 00:00:01.0554959; Exception - Microsoft.Rest.Azure.CloudException: The resource type 'roleAssignments' could not
be found in the namespace 'Microsoft.Authorization' for api version '2017-10-01-preview'. The supported api-versions are
'2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01,2015-07-01,2017-05-01'.
   at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperations.<ListWithHttpMessagesAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperationsExtensions.<ListAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperationsExtensions.List(IRoleAssignmentsOperations operations, ODataQuery`1 odataQuery)
   at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.FilterRoleAssignments(FilterRoleAssignmentsOptions options, String currentSubscription)
   at Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 4:24:35 PM - GetAzureRoleAssignmentCommand end processing.
DEBUG: 4:24:35 PM - GetAzureRoleAssignmentCommand end processing.

### Script/Steps for Reproduction
1. Execute cmdlet: Login-AzureRmAccount -EnvironmentName AzureChinaCloud
2. Login with Azure China Cloud account
3. Execute cmdlet: Get-AzureRmRoleAssignment

**Comment by cormacpayne** [comment]
@darshanhs90 Hey Haridarshan, do you know when this API version will be rolled out in the China cloud? I believe that it takes a couple of months for a new API version to be rolled out in different environments, but I could be mistaken.

**Comment by darshanhs90** [comment]
Will be performing the required steps for other environments today.
The commandlets should work after those steps .

**Comment by darshanhs90** [comment]
@pengzhisun Could you retry to execute the commandlet,we have fixed it on our end and it shouldnt happen now.

**Comment by pengzhisun** [comment]
@darshanhs90 Thanks for your help! I've just retried the Get-AzureRmRoleAssignment in Azure China Cloud environment, the issue has been fixed.
