### ISSUE TITLE
Acknowleging Contributors inside Azure PowerShell documentation

### ISSUE THREAD

**Issue by doctordns** [Azure/azure-powershell#5146]
# How to Acknowledge contributors

### Description
I notice that, on the web, some parts of docs.microsoft.com acknowledge the folks contributing to the documentation. For example, see: https://docs.microsoft.com/en-us/dotnet/core/docker/intro-net-docker. The second line of that page has details of the contributors.  But the Azure PowerShell documentation does not have this. Can all the documentation show contributors on all pages that are open source updable?

**Comment by twitchax** [comment]
Closing.  The list of contributors is generated from the contributors in the doc repo.  Anyone who edits the file in GitHub and sends a PR will be called out in contributors.

Reference docs are generated, so there are no contributors in GitHub.
