### ISSUE TITLE
Add deprecation warning for support for PowerShell 3/4.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#5149]
What the title says.

**Comment by doctordns** [comment]
This is a great idea.

Can I ask that any deprecation information points to a web page that explains the issue, using more words that are appropriate for a warning message.  I just want the warning message to be actionable.

**Comment by markcowl** [comment]
- Add this to the psm1 script for profile, and save the information so that this only prints once per machine.

**Comment by markcowl** [comment]
- 'PowerShell version 3 and 4 will no longer be supported starting in May 2018.  Please update to the latest version of PowerShell 5.1 <uri>'

**Comment by markcowl** [comment]
Fixed.
