### ISSUE TITLE
Support Setting Https Only property on webApps

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-powershell#5155]
### Cmdlet(s)
Set-AzureRmWebApp should have an option for HttpsOnly property
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by maddieclayton** [comment]
@panchagnula I assume you should be assigned to this issue as you have a commit related to it.  Let me know if I'm wrong.

**Comment by panchagnula** [comment]
Released as websites-preview module https://github.com/Azure/azure-powershell/releases/tag/v5.0.0-preview-AzureRM.Websites
