### ISSUE TITLE
Get-AzureRmAdApplication - return all pages of applications

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5161]
In the absence of a general solution for managfing pages, cmdlets should enumerate all pages when listing items.  This cmdlet returns only the first page of results.

Note that #3928 is tracking the general solution for managing pages of data, but this should be resolved irrecpective of that issue.

**Comment by cormacpayne** [comment]
@markcowl this is fixed in the working [development branch](https://github.com/cormacpayne/azure-powershell/tree/resources-improvements) I have for AD cmdlets -- the paging functionality is supported, but if the user were to not provide `First` or `Skip`, it will enumerate all pages

**Comment by cormacpayne** [comment]
This will be fixed in version 6.0.0 of `AzureRM` (version 6.0.0 of `AzureRM.Resources`) that is released on May 7th.
