### ISSUE TITLE
Automate Smoke Tests in CloudShell environment

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5162]
### Description

CloudShell environment can be set up as follows:

- [ ] ~~Automate running PSCloudShell acceptance tests as part of verifying our releases~~
  - [x] Follow instructions below for running these tests on a machine, verify correct execution and note the time for runnign the given tests - ideally running acceptance tests should take < 1 hour
    - Test script for executing automation is [here](https://github.com/PowerShell/AzurePSDrive/blob/development/Tests/AzureRMAcceptanceTest.ps1)
    - Steps:
      1. Install *your* version of AzureRM modules on the machine
      2. Run the acceptance tests.
      ```powershell
      PS C: > .\AzureRMAcceptanceTest.ps1 -subscriptionName MySubscription -azureADAppId <appidGuid> -azurePassword <appPassword> -azureTenantId <tenantGuid> 
      ```
  - [ ] ~~Set up necessary KeyVault entities (login credentials, any other secrets required by tests) for automation~~
  - [x] Set up a Jenkins job to build, sign, and run this test automation
  - [x] Determine if it is useful to split up these tests by RP to scope the test run to particular changes

- [x] Automate the set of smoke tests, using token authentication in this environment

### Cost: 10

**Comment by MiYanni** [comment]
Notes so far:
- The PowerShell session needs to run as Administrator.
- This needs to run prior to the script: `Set-PSRepository -Name PSGallery -InstallationPolicy Trusted`
- Resource Group and Storage Account names are not unique. 
  - AzureRM.Storage\New-AzureRmStorageAccount : The storage account named azurepsdriveteststorage is already taken.
- I'm going to fork their code with the changes mentioned above.

**Comment by MiYanni** [comment]
@markcowl The CloudTest Jenkins job is up and running. Tested failure and success conditions. Currently, the script does Import-Module on each component (Resources, Profile, Storage, Network, and Compute). So, this will draw from what is on the Gallery. The Jenkins job also is pulling from my branch, so we'd need to push those changes to their repo if we want to pull from there. Should we just wait until we talk to them next week?

**Comment by MiYanni** [comment]
The CloudTest Jenkins project is currently running and building on a schedule. Currently, the tests do not run on 'live' builds. Instead, it is running a hard-coded path share of the modules. I'll use a dynamic path once #4439 is completed. Currently, waiting for https://github.com/PowerShell/AzurePSDrive/pull/33 to be accepted to use the main repo instead of my own fork.

**Comment by MiYanni** [comment]
After https://github.com/PowerShell/AzurePSDrive/pull/35 and https://github.com/PowerShell/AzurePSDrive/pull/36 were merged, the tests run properly using their repo.
