### ISSUE TITLE
Update projects to build with VS2017

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5171]
### Description

- [ ] Update cmdlet, tools, setup, and test projects to use VS2017 tooling
- [ ] Ensure VS2017 tooling is available on Jenkins Workers for PowerShell
- [ ] Update Developer documentation for VS2017 usage

### Cost: 20

**Comment by sphibbs** [comment]
No need to move desktop. Net Standard 2.0 project will move to vs 2017
