### ISSUE TITLE
Document Expected patterns for standard cmdlets

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5172]
### Description

Document the expected patterns for standard cmdlets, including description, required parameters sets, output types, and execution properties, code snippets, and canonical tests.  Standard cmdlets should include

- [x] Get- cmdlets for top level resource, sub-resource
- [x] Set-cmdlets (PUT) for top level resource, sub resource
- [x] Set-cmdlets (PATCH) for top-level resource, sub-resource
  - [ ] Treatment of ETag parameters
- [x] New cmdlets for top-level resource
- [x] Add/New cmdlets for SubResource
- [ ] Action (Post) cmdlets for resource
  - [ ] Treatment of ETag parameters
- [x] Remove cmdlets for resource
  - [ ] Treatment of ETag parameters
- [x] Get/Set/Remove

- [ ] Review these documents with the powershell core team to ensure compliance

### Cost: 8

**Comment by cormacpayne** [comment]
Work for this completed in PR https://github.com/Azure/azure-powershell/pull/6700
