### ISSUE TITLE
Get-AzureRmWebApp doesn't return type properly for Select statement piping

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5174]
### Cmdlet(s)
Get-AzureRmWebApp
### PowerShell Version
PSVersion: 5.1.16299.98
### Module Version
4.0.0 (AzureRM.Websites)
### OS Version
BuildVersion: 10.0.16299.98
### Description
The type information returned for Get-AzureRmWebApp doesn't seem to be known when piping. I believe this needs stated explicitly when creating the command.
### Debug Output
(Too much debug output since it is retrieving all of them)
### Script/Steps for Reproduction
This can be shown easily by this example:
`Get-AzureRmWebApp | Select -Property Name`
This command returns nothing. Similarly, using -Expand Name will throw an exception stating Property 'Name' cannot be found. However, running this command:
`(Get-AzureRmWebApp) | Select -Property Name`
does resolve Name properly and shows the correct output. I believe this is because the command is executed (via the added parentheses) and can resolve the type properly. Without the parentheses, it cannot determine the type of each object, so it throws.

**Comment by markcowl** [comment]
@MiYanni  Can you please verify that adding the correct ```OutputType``` attrbitue resolves this problem.  If  so, let's update this issue to add this capability to the signature verifier.  My suspicion is that, for Get cmdlets, you must have anb attribute that specifies the underling ourput type, and not simply an enumerable type, but please verify directly on this cmdlet.

**Comment by MiYanni** [comment]
@markcowl The attribute assumption is actually incorrect! Type resolution is still determined dynamically (based on return type). The problem in this case is that each of their `WriteOutput` statements, they are returning a List. That's totally fine to do, but they needed to set [enumerateCollection ](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.cmdlet.writeobject?view=powershellsdk-1.1.0#System_Management_Automation_Cmdlet_WriteObject_System_Object_System_Boolean_) to true. Without that, the List is returned as a List object. With it set to true, the List is interpreted as a series of individual objects in the pipe.

The reason adding parentheses to Get-AzureRmWebApp changed the interpretation is an intrinsic function of the PowerShell language. Wrapping something in parentheses unwraps lists automatically.

So, not sure how difficult it would be to static analyze that. Or, if we propose a change somewhere else. I'm sure that other cmdlets may have this issue.

**Comment by MiYanni** [comment]
Fixed in https://github.com/Azure/azure-powershell/pull/4876
