### ISSUE TITLE
Create test automation for analyzing/validating type output for cmdlets

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5177]
### Description
This idea was spawned from #5174.

Currently, there is no validation/consistency around the output/piping for the cmdlets. We should make a way to check generic CRUD operations to see if they output the correct types to work with other standard PS cmdlets.
For example:
`Get-AzureRm[Thing] | Select -Property [PropFromThing]`
`Get-AzureRm[Thing] | Select -Last 1`

From these, we can tell if it is properly returning the type information. It should work properly with lists and individual objects. This type of check/validation could be added to our static analysis suite.

### Cost: 10

**Comment by MiYanni** [comment]
1. Update dev docs to check for these piping scenarios
2. Check core cmdlets to see if they work with these piping scenarios
3. Notify non-core RPs about new standard and they should fix this

**Comment by maddieclayton** [comment]
https://github.com/Azure/azure-powershell/issues/5520

**Comment by maddieclayton** [comment]
Closed, tracking in other issues.
