### ISSUE TITLE
Import-AzureRmAutomationRunbook params -LogProgress and -LogVerbose take booleans

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5180]
### Cmdlet(s)
Import-AzureRmAutomationRunbook
### PowerShell Version
PSVersion                      5.1.16299.98
### Module Version
4.1.1 
### OS Version
BuildVersion                   10.0.16299.98
### Description
These 2 parameters for Import-AzureRmAutomationRunbook are boolean flags that take in a boolean value. Right now, if these flags are not present, they logically default to false. The documentation says that the parameters have no default value. 

To actually use these flags, you need to write `-LogVerbose $true`, for example, which is bizarre in the PS environment. Compared to a common flag, like -Force, you'd simply have the flag present in the command call to make the functionality true, and not present to make it false. These 2 flags, -LogProgress and -LogVerbose, should act in this manner, since they logically default to false if they are not present. It would make sense to change them to `System.Management.Automation.SwitchParameter`, which is what -Force is.

There may be other parameters like this across AzureRm. Maybe a general search (for any parameters of type System.Nullable`1[System.Boolean] or System.Boolean) would make sense. Investigation would need to be done to to see if it makes sense to keep them as booleans or change them to SwitchParameters.

**Comment by markcowl** [comment]
@MiYanni It is recommended to avoid boolean parameters except in very specific circumstances (PATCH operations with several boolean vaules).

This is an example of a legacy cmdlet that is not up to compliance.  We need to work with Varad and the Auotmation team to have the bad interface deprecated and fixed at the next breaking change release.

**Comment by markcowl** [comment]
@vrdmr Can you go through the current cmdlet interface for automation and deprecate this and other similar patterns?  It would be great to include this change in the next breaking change release (BUILD)

**Comment by wsmelton** [comment]
I think has already been addressed in this issue #183

It does not have anything to do with being legacy, use of boolean parameters is intentional. Some of these should not be that easy to enable just from passing a switch parameter. I have no problem with these being boolean and would prefer them to be.

**Comment by MiYanni** [comment]
@wsmelton In that issue, @pcgeek86 stated our viewpoint on the issue. As a PowerShell standard, if you have a parameter that defaults to `false` when it is not provided, using a `bool` doesn't make sense. 

Currently, the only situation that makes sense for `bool` in Azure PowerShell is when using Set/Update cmdlets; when changing values on the server, you may want to preserve the current value of that property. So, omitting the parameter defaults to a no-op, and providing the `bool` changes the server value to `true/false` respectively.

For `LogProgress` and `LogVerbose`, these should be changed to `switch` parameters to match the consistency we are driving across Azure PowerShell modules.

**Comment by wsmelton** [comment]
So then all parameters that are now boolean will be changed to switch type?

**Comment by andyw248** [comment]
Triaged: No known customer complaints. Not fixing.

**Comment by MiYanni** [comment]
@andyw248 This will be fixed in the generated cmdlets.
