### ISSUE TITLE
Set-AzureRmAppServicePlan errors out for a Premium V2 App Service plans

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-powershell#5181]
### Cmdlet(s)
Set-AzureRmAppServicePlan
### PowerShell Version
All
### Description
Error:
: Set-AzureRmAppServicePlan : Input string was not in a correct format.
At line:4 char:1
+ Set-AzureRmAppServicePlan -Name ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmAppServicePlan], FormatException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.SetAzureAppServicePlanCmdlet

### Script/Steps for Reproduction
Create a Premium V2 app service plan, try to change the size of the app service plan or downgrade to any other tier

**Comment by panchagnula** [comment]
This should now be available with the websites-preview module https://github.com/Azure/azure-powershell/releases/tag/v5.0.0-preview-AzureRM.Websites
