### ISSUE TITLE
Set-AzureVMDiagnosticsExtension automated test

### ISSUE THREAD

**Issue by chhabaramesh** [Azure/azure-powershell#5187]
### Cmdlet(s)

Set-AzureVMDiagnosticsExtension

### Description

Add test for Windows diagnostics agent configuration schema update to support Azure Monitor as a sink.

**Comment by cormacpayne** [comment]
@chhabaramesh Hey Ramesh, has this issue been addressed?

**Comment by chhabaramesh** [comment]
@cormacpayne , I missed your message. I will update you on this in day or two.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
