### ISSUE TITLE
What cmdlet replaced Get-AzureRMEventHubNamespaceKey?

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#5188]
Customer question via LiveFyre:

### Description
Cmdlet Get-AzureRMEventHubNamespaceKey is not available in v5 and newer. Which cmdlet replaces it? How do we retrieve the connection string info for an event hub namespace via powershell? 

### Module Version
AzureRM.EventHub

**Comment by maddieclayton** [comment]
Hi @sdwheeler: Per [the migration guide](https://github.com/Azure/azure-powershell/blob/preview/documentation/release-notes/migration-guide.5.0.0.md#get-azurermeventhubnamespacekey), Get-AzureRmEventHubNamespaceKey has been replaced by Get-AzureRmEventKey.  I'll close this issue as resolve, but feel free to reopen if you continue to have issues and I'll redirect you to the correct team.
