### ISSUE TITLE
Add-AzureCertificate fails when executed through IIS

### ISSUE THREAD

**Issue by francoismagninavanade** [Azure/azure-powershell#519]
AddAzureCertificate imports the PFX file in GetCertificateData(). This gives an access denied exception when running in IIS.
Instead of importing the certificate to then export it, load the PFX data in the X509Certificate2 constructor.

var cert = new X509Certificate2(certPath, password, X509KeyStorageFlags.Exportable);
//cert.Import(certPath, password, X509KeyStorageFlags.Exportable);
return cert.HasPrivateKey ? cert.Export(X509ContentType.Pfx, password) : cert.Export(X509ContentType.Pkcs12);

**Comment by francoismagninavanade** [comment]
An even better approach to get the certificate data is to use File.ReadAllBytes(pfxPath) as mentioned in the MSDN documentation (https://msdn.microsoft.com/en-au/library/azure/ee460817.aspx).

**Comment by stankovski** [comment]
@singhkay please followup

**Comment by singhkay** [comment]
@francoismagninavanade Do you have repro steps for this?
@hyonholee Can you take a look at the code fix for this suggestion?

**Comment by francoismagninavanade** [comment]
Hi Kay,

 

Below is some sample code that should reproduce the problem:

WSManConnectionInfo connectionInfo = new WSManConnectionInfo("http", "localhost", Convert.ToInt32(ConfigurationManager.AppSettings["Port"]), "/wsman", "http://schemas.microsoft.com/powershell/Microsoft.PowerShell", new PSCredential(String.Format("{0}\\{1}", Environment.MachineName, userName), password));

 

            Runspace runspace = RunspaceFactory.CreateRunspace(connectionInfo);

            runspace.Open();

 

            using (PowerShell powerShellInstance = PowerShell.Create())

            {

                powerShellInstance.Runspace = runspace;

 

                string baseDir = AppDomain.CurrentDomain.BaseDirectory;

                string modulePath = Path.Combine(baseDir, "bin", "Module", "DeploymentModule.psm1");

 

                powerShellInstance.AddScript(PowershellCommandlets.VerbosePreferenceContinue);

                powerShellInstance.Invoke();

                powerShellInstance.Commands.Clear();

 

                powerShellInstance.AddCommand(PowershellCommandlets.ImportModule).AddArgument(modulePath);

                powerShellInstance.Invoke();

                powerShellInstance.Commands.Clear();

 

                powerShellInstance.AddCommand(PowershellCommandlets.DeployCloudService);

 

                IAsyncResult result = powerShellInstance.BeginInvoke<PSObject, PSObject>(null, _outputCollection);

 

                jobOutput.SaveJobStatus(request.JobId, DeploymentState.Running);

 

                // do something else until execution has completed.

                // this could be sleep/wait, or perhaps some other work

                while (result.IsCompleted == false)

                {

                    Thread.Sleep(1000);

 

                    // might want to place a timeout here...

                }

 

 

                if (powerShellInstance.Streams.Error.Count > 0)

                {

                    jobOutput.SaveJobStatus(request.JobId, DeploymentState.Failed);

                }

                else

                {

                    jobOutput.SaveJobStatus(request.JobId, DeploymentState.Completed);

                }

 

            }

            runspace.Close();

 

The module loaded contains a workflow called Deploy-CloudService. This workflow calls Add-AzureCertificate. 

Running this code from a WCF service hosted in IIS will reproduce the issue. The user account used in the WSManConnectionInfo constructor is a local admin on the box. 

Note you can also load the user profile for this admin account using runspace.NoMachineProfile = false, but this won’t change anything.

 

Kind Regards,

 

Francois

**Comment by devigned** [comment]
Does this have anything to do with [[PermissionSet(SecurityAction.Demand, Name = "FullTrust")]] (https://github.com/Azure/azure-powershell/blob/dev/src/ServiceManagement/Compute/Commands.ServiceManagement/Certificates/AddAzureCertificate.cs#L72) in Add-AzureCertificate when running in a partially trusted environment?

**Comment by devigned** [comment]
As an aside @francoismagninavanade, wouldn't it be easier to use [ServiceCertificateOperations](https://github.com/Azure/azure-sdk-for-net/blob/master/src/ServiceManagement/Compute/ComputeManagement/Generated/ComputeManagementClient.cs#L182) and other such compute client operations via the .Net SDK rather than spinning up a PowerShell run space?

**Comment by francoismagninavanade** [comment]
Hi David,

 

No it hasn’t. I have run the service in full trust and get the same problem. 

It clearly has to do with the Import statement. 

You can simulate the problem by loading up a pfx file in an X509Certificate2 object using Import or even using the constructor and X509KeyStorageFlags.PersistKeySet or the default value. 

To work around the problem, you can use X509KeyStorageFlags.MachineKeySet.

But fundamentally, there is no reason to import the certificate at all in GetCertificateData. 

 

public static byte[] GetCertificateData(string certPath, string password)

{

var cert = new X509Certificate2();

cert.Import(certPath, password, X509KeyStorageFlags.Exportable);

return cert.HasPrivateKey ? cert.Export(X509ContentType.Pfx, password) : cert.Export(X509ContentType.Pkcs12);

}

 

 

Cheers,

 

Francois

**Comment by francoismagninavanade** [comment]
Hi David,

 

I would say yes but the customer has a different view…In this case, I have to use PowerShell. So we worked around the problem by installing the certificates using a REST API call which is fine. 

But this issue will occur again as we cannot assume access to the local user certificate store is permitted in all scenarios. Given there are no reasons for importing the certificate into the store just to get the data, I would simply not do it. 

 

Regards,

 

Francois

**Comment by devigned** [comment]
@francoismagninavanade [I see what you mean.](https://github.com/Azure/azure-powershell/blob/dev/src/ServiceManagement/Compute/Commands.ServiceManagement/Helpers/CertUtils.cs#L96)

**Comment by rangeryu** [comment]
Thanks @devigned @francoismagninavanade . it is really a great discussion

```C#
Convert.ToBase64String(File.ReadAllBytes(pfxPath)) 
```
when GetCertificateData() might be a quick fix that makes the execution independent to the user profile/cert store.

**Comment by devigned** [comment]
@rangeryu :+1:

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
