### ISSUE TITLE
Incorrect Get-AzureRmRoleAssignment example in docs (non-existent param set)

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5193]
### Cmdlet(s)
Get-AzureRmRoleAssignment
### PowerShell Version
PSVersion                      5.1.16299.98
### Module Version
5.1.1      AzureRM.Resources
### OS Version
BuildVersion                   10.0.16299.98
### Description
Example 2 here: https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/get-azurermroleassignment?view=azurermps-5.1.1
Attempting to call that example states it cannot resolve the parameter set.
### Debug Output
PS C:\WINDOWS\system32> Get-AzureRmRoleAssignment -ResourceGroupName azposjhautomation -SignInName miyanni@microsoft.com -ExpandPrincipalGroups
Get-AzureRmRoleAssignment : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-AzureRmRoleAssignment -ResourceGroupName azposjhautomation -SignI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmRoleAssignment], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand
### Script/Steps for Reproduction
Copy/paste the Example 2 script from here: https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/get-azurermroleassignment?view=azurermps-5.1.1
Replace the ResourceGroupName with one from your subscription, and use your login for SignInName. The reason the call doesn't work is because -ExpandPrincipalGroups doesn't exist on the parameter set that uses both ResourceGroupName and SignInName. If you remove -ExpandPrincipalGroups, the call functions properly.

**Comment by maddieclayton** [comment]
Fixed
