### ISSUE TITLE
Is AdditionalUnattendContent really 'base64 encoded'..?

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-powershell#5197]
I refer to this doc comment in azure-powershell/src/ResourceManager/Compute/Stack/Commands.Compute/Generated/Models/WindowsConfiguration.cs :

```
    /// <summary>
        /// Gets or sets the additional base-64 encoded XML formatted
        /// information that can be included in the Unattend.xml file.
        /// </summary>
        [JsonProperty(PropertyName = "additionalUnattendContent")]
        public IList<AdditionalUnattendContent> AdditionalUnattendContent { get; set; }
```

I don't think it is correct? The documentation in the AdditionalUnattendContent class mentions nothing about base 64 encoding, and I haven't seen anyone ever actual do base 64 encoding in the samples of this class or the Add-AzureRmVMAdditionalUnattendContent command being used.

**Comment by markcowl** [comment]
@bganapa Can you take a look?

**Comment by bganapa** [comment]
@TimLovellSmith , the code path you are referring to is specific to azure stack compute module.  Can you please provide more details on what you are trying to do and what is failing?

**Comment by TimLovellSmith** [comment]
@bganapa To be clear, its not that something I am doing is *failing*, since I am not using powershell, it's just that I think the statement it should be base64 encoded is probably wrong based on my past experience with the .net sdk.

**Comment by bganapa** [comment]
@hyonholee Do you have any idea on Tim's Q above? Thanks

**Comment by deathly809** [comment]
Closing.  Please open an issue if you hit a bug related to this.
