### ISSUE TITLE
Request: ARM equivalent for Publish-AzureWebsiteProject

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-powershell#5202]

**Comment by markcowl** [comment]
@Nking92 Can you take a look at this?

**Comment by rnwood** [comment]
+1 on this. We just received notification that the non RM API for App Service is shutting down in a few months and believe that therefore this cmdlet will stop working. It's therefore important for us and others that we understand what we can replace use of this cmdlet with.

**Comment by mcrsw** [comment]
+1 too.  June is fast approaching. @panchagnula , @Nking92  is there an answer yet please?

**Comment by panchagnula** [comment]
@ahmedelnably can you add details here on what the work entitles, AFAIK there is no ARM API equivalent for this. Thanks!

**Comment by EricSten-MSFT** [comment]
@panchagnula You might also check out this [background article](https://github.com/aelij/azure-content/blob/master/articles/app-service-web/app-service-web-arm-with-msdeploy-provision.md) describing how to use the MSDeploy ARM API: https://github.com/aelij/azure-content/blob/master/articles/app-service-web/app-service-web-arm-with-msdeploy-provision.md

**Comment by ahmedelnably** [comment]
After internal team discussions, we are opting to create a new command that will use Zip deployment mechanism.
Closing this, as we are tracking the new command here: https://github.com/Azure/azure-powershell/issues/6374
