### ISSUE TITLE
Set-AzureRole returns 'InternalError' when scaling large number of instances

### ISSUE THREAD

**Issue by MrGlenThomas** [Azure/azure-powershell#5209]
### Cmdlet(s)
Set-AzureRole

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

Not sure as command is being run from a server I don't personally have access to. In the log I can see this (but not sure if relevant):

> Add-RoleModules:
>  - Loaded Azure Modules 1.3.0
>  - Loaded AzureRM.Profile Modules 1.0.6
>  - Loaded AzureRM.Resources Modules 1.0.6
>  - Loaded AzureRM.Automation Modules 1.0.6

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

OperatingSystem: Microsoft Windows NT 6.3.9600.0
OsBitVersion: x64

### Description
Using Set-AzureRole for scaling instances fails with the below error when instance count ~20. There seems to be an internal timeout that cannot be configured with any parameters.

> Set-AzureRole : InternalError : The server encountered an internal error. Please retry the request.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
Use Set-AzureRole for scaling instances with large number of instances (20+)

**Comment by markcowl** [comment]
@MrGlenThomas Can you try this with a more recent version of the module?  Azure is now at version 5.1.1, this version is more than 2 years old.  You can use Install-Module, or install from the webpi feed, or the repo here: https://github.com/Azure/azure-powershell/releases/download/v5.1.1-December2017/azure-powershell.5.1.1.msi

**Comment by MrGlenThomas** [comment]
I have done some testing with a newer version, but not the newest.
 - Loaded Azure Modules 4.3.1
 - Loaded AzureRM.Profile Modules 3.3.1
 - Loaded AzureRM.Resources Modules 4.3.1
 - Loaded AzureRM.Automation Modules 3.3.1

I am in the process of getting the latest version installed still..

I tried scaling again on a different environment with 24 instances and the scaling operation completed fine within around 16 minutes.
I tried again on the same environment that I had the error with previously and it failed again with the same error. When I look at the slot in the Azure portal I can see that all of the instances haven't quite finished starting up when the error occurs, but eventually they start ok.
The error always seems to kick in at around 17 minutes after the operation begins. If I lower the number of instances that it is scaling to then it works fine.

**Comment by MrGlenThomas** [comment]
I tried again with the latest version:
 - Loaded Azure Modules 5.1.1
 - Loaded AzureRM.Profile Modules 4.1.1
 - Loaded AzureRM.Resources Modules 5.1.1
 - Loaded AzureRM.Automation Modules 4.1.1

And this time the scaling completed successfully in just over 17 minutes (17m11s), so _maybe_ the issue is fixed..

**Comment by maddieclayton** [comment]
Closing as the latest version seems to be working.  @MrGlenThomas If you run into this error again please reopen.
