### ISSUE TITLE
Cannot pipe Get-AzureAutomationDscNode to Get-AzureAutomationDSCNodeReport

### ISSUE THREAD

**Issue by JakobGSvendsen** [Azure/azure-powershell#521]
Get-AzureAutomationDscNode -Name WEB02 | Get-AzureAutomationDSCNodeReport 

Get-AzureAutomationDSCNodeReport : The input object cannot be bound because it did not contain the information required to bind all mandatory parameters:  NodeId
At line:1 char:42
+ Get-AzureAutomationDscNode -Name WEB02 | Get-AzureAutomationDSCNodeReport
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Azure...n.Model.DscNode:PSObject) [Get-AzureAutomationDscNodeReport], ParameterBindingException
    + FullyQualifiedErrorId : InputObjectMissingMandatory,Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationDscNodeReport

I my knowledge, this is not PowerShell best practice as the cmdlets are in the same "family". 
would be great to be able to pipe the result into the cmdlet.

**Comment by jodoglevy** [comment]
@JakobGSvendsen unfortunately, this is by design. Get-AzureAutomationDscNode returns objects with an Id property, but Get-AzureAutomationDscNodeReport takes in node ids via the NodeId parameter. The Id parameter of Get-AzureAutomationDcsNodeReport is for report id.
