### ISSUE TITLE
New-AzureRmResourceLock help needs to be udpated

### ISSUE THREAD

**Issue by cacarroll** [Azure/azure-powershell#5210]
### Cmdlet(s)
New-AzureRmResourceLock 

### PowerShell Version
5.1.16299.98

### Module Version
5.1.1 

### OS Version
10.0.16299.98

### Description
The help for New-AzureRmResourceLock states that the only valid lock type is "CanNotDelete."  

However, ReadOnly is also a valid setting.

### Debug Output
    -LockLevel <LockLevel>
        Specifies the level for the lock. Currently, the only valid value is
        **CanNotDelete.**

### Script/Steps for Reproduction
Get-Help New-AzureRmResourceLock -Full

**Comment by markcowl** [comment]
@ravbhatnagar @vivsriaus Can you take a look?  

@cacarroll Note that you can submit a PR to update this into this repo directly, or by clickign the edit button for this page on docs.microsoft.com

**Comment by ifeoluwaokunoren** [comment]
Issue resolved.

Get-Help New-AzureRmResourceLock -Full 

Lock-Level now contains ReadOnly as a valid value.

```
    -LockLevel <Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.Locks.LockLevel>
        Specifies the level for the lock. Currently, valid values are CanNotDelete, ReadOnly.
        
        Required?                    true
        Position?                    named
        Default value                None
        Accept pipeline input?       True (ByPropertyName)
        Accept wildcard characters?  false
   ```
