### ISSUE TITLE
Set-AzureRmSqlDatabaseSecondary docs missing example

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#5211]
Set-AzureRmSqlDatabaseSecondary docs missing example. Reported by customer via LiveFyre.

### Cmdlet(s)
Set-AzureRmSqlDatabaseSecondary 

### Module Version
Current release

### Description
See
- https://docs.microsoft.com/en-us/powershell/module/azurerm.sql/set-azurermsqldatabasesecondary
- https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlDatabaseSecondary.md

**Comment by maddieclayton** [comment]
@akromm @jaredmoo Can you take a look at this and get it assigned to the correct person? Thank you.

**Comment by cormacpayne** [comment]
@jaredmoo @maboja-msft ping
