### ISSUE TITLE
Stack: Update Profile module dependencies to be greater than or equal to 

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#5212]
The next stack specific release should update the dependencies to be greater than or equal to on Profile module

**Comment by cormacpayne** [comment]
@bganapa do you have a timeline for when this fix will happen?

**Comment by bganapa** [comment]
This will be part of August End azurestack release

**Comment by MiYanni** [comment]
@bganapa Ping. Checking if this was done as part of the recent set of Stack PRs.

**Comment by deathly809** [comment]
@MiYanni yeah we made the change.
