### ISSUE TITLE
Compute Test Coverage

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#5215]
Many cmdlets in the Compute module are missing tests or do not fully test the functionality of the cmdlet.  This is blocking the addition of -AsJob for many of these cmdlets because we cannot add tests for this functionality of the -AsJob parameter.  Once the tests are updated to fully cover these cmdlets, the -AsJob parameter can be added (details [here](https://github.com/Azure/azure-powershell/wiki/PowerShell-Cmdlet-Design-Guidelines#asjob-parameter)).  

## Cmdlets that need improved test coverage (where AsJob has already been added)
- [x] Remove-AzureRmContainerService: No asserts covering cmdlet 
- [x] Update-AzureRmDisk: No asserts covering cmdlet
- [x] Remove-AzureRmDisk: No asserts covering cmdlet
- [ ] Update-AzureRmImage: Not used in any test
- [x] Remove-AzureRmSnapshot: No asserts covering cmdlet 
- [x] Update-AzureRmSnapshot: No asserts covering cmdlet
- [ ] Start-AzureRmVmss: No asserts covering cmdlet
- [ ] Restart-AzureRmVmss: No asserts covering cmdlet 
- [ ] Stop-AzureRmVmss: No asserts covering cmdlet 
- [ ] Remove-AzureRmVmss: No asserts covering cmdlet 
- [x] Stop-AzureRmVm: No asserts covering cmdlet
- [x] Restart-AzureRmVm: No asserts covering cmdlet 
- [x] Start-AzureRmVm: No asserts covering cmdlet
- [ ] Save-AzureRmVhd: Test skipped
- [ ] Add-AzureRmVhd: Test skipped
## Cmdlets that need improved test coverage (where AsJob has not been added yet)
- [x] Update-AzureRmContainerService: No asserts covering cmdlet
- [x] Grant-AzureRmDiskAccess: No asserts covering cmdlet
- [x] Revoke-AzureRmDiskAccess: No asserts covering cmdlet 
- [x] Grant-AzureRmSnapshotAccess: No asserts covering cmdlet 
- [x] Revoke-AzureRmSnapshotAccess: No asserts covering cmdlet 
- [ ] Remove-AzureRmVMExtension: No asserts covering cmdlet 
- [ ] Set-AzureRmVmssDiskEncryptionExtension: Test skipped 
- [ ] Start-AzureRmVmssRollingOSUpgrade: Only tests the failure case 
- [ ] Stop-AzureRmVmssRollingOSUpgrade: Only tests the failure case 

## Additional work related to this issue
- [ ] Add AsJob parameter to each cmdlet that is missing this parameter

**Comment by maddieclayton** [comment]
Some tests being added here: https://github.com/Azure/azure-powershell/pull/5277

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
