### ISSUE TITLE
Resources Test Coverage

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#5216]
Two cmdlets in the Network module are missing tests or do not fully test the functionality of the cmdlet.  This is blocking the addition of -AsJob for these cmdlets because we cannot add tests for this functionality of the -AsJob parameter.  Once the tests are updated to fully cover these cmdlets, the -AsJob parameter can be added (details [here](https://github.com/Azure/azure-powershell/wiki/PowerShell-Cmdlet-Design-Guidelines#asjob-parameter)).  

## Cmdlets that need improved test coverage:
- [ ] Remove-AzureRmResourceGroupDeployment: Not actually testing deletion.
- [ ] Invoke-AzureRmResourceAction: No test covering cmdlet.

## Additional work related to this issue
- [ ] Add AsJob parameter to each cmdlet with improved testing.

**Comment by vivsriaus** [comment]
Thanks for bringing this to our attention, @maddieclayton. We can add more checks to existing Remove-AzureRmResourceGroupDeployment test [here](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.Resources.Test/ScenarioTests/ResourceGroupTests.ps1#L256)

I'll also add a sample test for Invoke-AzureRmResourceAction cmdlet
