### ISSUE TITLE
Set-AzureRmStorageAccount: KeyName, KeyVaultUri, KeyVersion doc descriptions

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5231]
### Cmdlet(s)
Set-AzureRmStorageAccount
### Description
https://docs.microsoft.com/en-us/powershell/module/azurerm.storage/set-azurermstorageaccount?view=azurermps-5.1.1
The doc descriptions for KeyName, KeyVaultUri, and KeyVersion are just an auto-generated chain of properties. Update the documentation so they are human readable descriptions.

**Comment by blueww** [comment]
The description of the 3 properties are already updated in PR https://github.com/Azure/azure-powershell/pull/5157
