### ISSUE TITLE
Get-UsageAggregates needs alias Get-AzureRmUsageAggregates as it is missing the standard AzureRm prefix 

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#5248]
### Cmdlet(s)
Get-UsageAggregates

### Module Version
4.0.0 (latest)

### Description
AzureRm.UsageAggregates has a single cmdlet Get-UsageAggregates. I believe this goes through ARM and hence it needs a AzureRm prefix.  Discoverability is hard at the moment as i was trying Get-AzureRmUsage <tab> <tab>

**Comment by markcowl** [comment]
All of the prefixes are going to Az
