### ISSUE TITLE
New-AzureRmSchedulerStorageQueueJob - missing Https action type

### ISSUE THREAD

**Issue by tacerra** [Azure/azure-powershell#5256]
### Cmdlet(s)
New-AzureRmSchedulerStorageQueueJob

### PowerShell Version
5.1.16299.98

### OS Version
10.0.16299.98  

### Description
The AddErrorActionParameters method in JobBaseCmdlet.cs is missing a check for Constants.HttpsAction so calling New-AzureRmSchedulerStorageQueueJob never gets the dynamic ErrorAction parameters setup when ErrorActionType is Https. This results in an error stating dynamic Method and Uri parameters are missing. Passing identical parameters but using Http as ErrorActionType succeeds.

### Script/Steps for Reproduction
Create a new job by calling New-AzureRmSchedulerStorageQueueJob with an ErrorActionType = Https

**Comment by markcowl** [comment]
@sphibbs Please assign appropriately on the Scheduler team

**Comment by sphibbs** [comment]
@derek1ee can you take a look at this. thanks

**Comment by derek1ee** [comment]
+ @Max Shao<mailto:yisha@microsoft.com>/ @Javed Akhter<mailto:Javed.Akhter@microsoft.com>

________________________________

**Comment by cormacpayne** [comment]
Closing as the Scheduler module no longer ships with `Az`.
