### ISSUE TITLE
Invoke-AzureRmResourceAction Hangs PowerShell

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#5265]
### Cmdlet(s)

Invoke-AzureRmResourceAction

### PowerShell Version
5.1

### Module Version
5.1.1

### OS Version
Windows 10

### Description

Running the cmdlet causes the PowerShell instance to hang.

### Script/Steps for Reproduction

The following script will fail.

```powershell
#assumes login and subscription select are already done
$labName = '<name>'
$vmName = '<name>'
$artifactId = 'windows-7zip'

$lab = Find-AzureRmResource -ResourceType 'Microsoft.DevTestLab/labs' | Where-Object {$_.Name -eq $labName}
$vm = (Get-AzureRmResource -ResourceId ($lab.ResourceId + "/virtualmachines") -ODataQuery '$expand=Properties($expand=Artifacts)' -ApiVersion 2017-04-26-preview) | Where-Object {$_.Name -eq $vmName}

# Apply the artifact
$FullArtifactId = "$($lab.ResourceId)/artifactSources/public repo/artifacts/$artifactId"
$parameters = @{
        artifacts = @(
                @{
                    artifactId = $FullArtifactId
                }
        )
}

Invoke-AzureRmResourceAction -Parameters $parameters -Action "applyArtifacts" -ResourceId $vm.ResourceId -ApiVersion 2016-05-15 -Force -ErrorAction Continue
```

**Comment by cormacpayne** [comment]
@ravbhatnagar @vivsriaus would you mind taking a look at this issue?

**Comment by AsraFatima** [comment]
I am also seeing this issue. The Invoke-AzureRMResourceAction does not return after the action "ApplyArtifacts" and the script is stuck at that point.

**Comment by bmoore-msft** [comment]
Can you attach -debug output from the command?

**Comment by workleodig** [comment]
Here's the -debug output 
[debugoutput.txt](https://github.com/Azure/azure-powershell/files/1717936/debugoutput.txt)

**Comment by grwann** [comment]
Hello all,
We have identified this as a bug on DTL side.  The bug fix has been committed and verified, and is making its way out to all regions now.
Thank you!

**Comment by workleodig** [comment]
This worked correctly on a VM in my lab in West Europe today. Thanks!
