### ISSUE TITLE
[INTERNAL] MS Graph permission update.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#5267]
### Description

Internal wiki [here](https://identitydocs.azurewebsites.net/static/aad/preauthorization.html).

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by markcowl** [comment]
Completed

**Comment by markcowl** [comment]
VSTS issue here: https://microsoftgraph.visualstudio.com/onboarding/Pre-authorized%20clients/_workitems/edit/566
