### ISSUE TITLE
Websites: Removing a binding using powershell command 'Remove-AzureRmWebAppSSLBinding ' is not actually removing the binding even though the command reports success

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-powershell#5269]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@panchagnula Hey Sisira, I removed the milestone since this change didn't appear to get into the last milestone. Feel free to assign it to the appropriate milestone whenever you know when this fix will be made.

**Comment by panchagnula** [comment]
@cormacpayne  yes, thank you i do have a fix but haven't started the PR i am trying to group with the other SSL binding related issues, I will add a the new milestone later. thank you.

**Comment by panchagnula** [comment]
This should now be fixed. Please create a new issue if this still occurs.
