### ISSUE TITLE
Explore and Automate appropriate SDL tools 

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5274]
### Description

Run SDL tools as part of all builds.  Identify issues and fix or add suppressions

- [ ] binscope
- [ ] policheck

**Comment by maddieclayton** [comment]
For policheck:
Write file to src/Package/policheckfiles.txt directory with all files to include in search
policheck.exe /F:"${Packages}\policheckfiles.txt" /T:"9" /O:"${Packagesl}\policheckresult.xml"
Delete src/Packages/policheckfiles.txt
Check output files for exceptions
Delete output files with no exceptions
Fail the build if there are output files with exceptions

For BinScope:
(Get-ChildItem -Recurse C:\azure-powershell\src\Package) | ForEach-Object {binscope.exe $_.FullName /LogFile {Packages}\binscopefile{identifier}.txt}
Check output files for exceptions
Delete the output files with no exceptions?
Fail the build if there are output files with exceptions

**Comment by maddieclayton** [comment]
Done
