### ISSUE TITLE
New-AzureRmVM's DiskFile parameter set should create resource group if not exists

### ISSUE THREAD

**Issue by huangpf** [Azure/azure-powershell#5279]
### Cmdlet(s)
New-AzureRmVM

### PowerShell Version
TBD

### Module Version
AzureRM.Compute

### OS Version
TBD

### Description
DiskFile parameter set should create resource group if not exists

### Debug Output
TBD

### Script/Steps for Reproduction
TBD

**Comment by markcowl** [comment]
@huangpf We should look at making this change for all parameter sets

**Comment by huangpf** [comment]
@markcowl You mean ```DiskFile``` and the ```-VM``` parameter sets, right? 

And do you think the fix should depend on the Strategy framework's capability of handling Storage accounts & blob? @sergey-shandar

**Comment by sergey-shandar** [comment]
@huangpf it would be good to have a solution based on strategies library.

**Comment by markcowl** [comment]
Complete
