### ISSUE TITLE
Websites: Add a test for testing PremiumV2 SKU with Set-AzureRmAppServicePlan

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-powershell#5287]
### Cmdlet(s)
Add a test for this https://github.com/azure/azure-powershell/issues/5181
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@panchagnula Hey Sisira, has this issue been addressed?

**Comment by panchagnula** [comment]
Not yet @cormacpayne

**Comment by panchagnula** [comment]
Plan to get this updated for the End of July 2019 release.

**Comment by panchagnula** [comment]
Closing this one
