### ISSUE TITLE
AssemblyVersionConflict since "Newtonsoft.Json" upgrade from 6.0.8 to 10.0.2

### ISSUE THREAD

**Issue by blueww** [Azure/azure-powershell#5288]
### PowerShell Version
any version

### OS Version
Win 10

### Description

We plan to upgrade to XSCL 9.0 in Azure.Storage to support soft-delete in recent release. But when I try XSCL 9.0 private package, I find it upgrade “Newtonsoft.Json” from 6.0.8 to 10.0.2, so build PowerShell will get following static analysis error.
After discuss with Mark, he suggest to open a issue here and he will try to resolve in Feb.9 release.

> 
> 22:59:27   ERROR - D:\PowerShell-demand\src\Package\AssemblyVersionConflict.csv Errors
> 22:59:27   ERROR - "Directory","AssemblyName","Expected Version","Actual Version","Parent Assembly","Severity","ProblemId","Description","Remediation"
> 22:59:27   "D:\PowerShell-demand\src\Package\Debug\Storage\Azure.Storage","Newtonsoft.Json","6.0.0.0","10.0.0.0","Hyak.Common","1","1010","Assembly Newtonsoft.Json version 6.0.0.0 referenced from Hyak.Common.dll does not match assembly version on disk: 10.0.0.0","Update any references to version 6.0.0.0 of assembly Newtonsoft.Json"
> 22:59:27   "D:\PowerShell-demand\src\Package\Debug\Storage\Azure.Storage","Newtonsoft.Json","6.0.0.0","10.0.0.0","Microsoft.Azure.Commands.Common.Authentication.Abstractions","1","1010","Assembly Newtonsoft.Json version 6.0.0.0 referenced from Microsoft.Azure.Commands.Common.Authentication.Abstractions.dll does not match assembly version on disk: 10.0.0.0","Update any references to version 6.0.0.0 of assembly Newtonsoft.Json"
> 22:59:27   "D:\PowerShell-demand\src\Package\Debug\Storage\Azure.Storage","Newtonsoft.Json","6.0.0.0","10.0.0.0","Microsoft.Rest.ClientRuntime.Azure","1","1010","Assembly Newtonsoft.Json version 6.0.0.0 referenced from Microsoft.Rest.ClientRuntime.Azure.dll does not match assembly version on disk: 10.0.0.0","Update any references to version 6.0.0.0 of assembly Newtonsoft.Json"
> 22:59:27   "D:\PowerShell-demand\src\Package\Debug\Storage\Azure.Storage","Newtonsoft.Json","6.0.0.0","10.0.0.0","Microsoft.Rest.ClientRuntime","1","1010","Assembly Newtonsoft.Json version 6.0.0.0 referenced from Microsoft.Rest.ClientRuntime.dll does not match assembly version on disk: 10.0.0.0","Update any references to version 6.0.0.0 of assembly Newtonsoft.Json"
> 22:59:27   "D:\PowerShell-demand\src\Package\Debug\Storage\Azure.Storage","Newtonsoft.Json","6.0.0.0","10.0.0.0","Microsoft.WindowsAzure.Commands.Common","1","1010","Assembly Newtonsoft.Json version 6.0.0.0 referenced from Microsoft.WindowsAzure.Commands.Common.dll does not match assembly version on disk: 10.0.0.0","Update any references to version 6.0.0.0 of assembly Newtonsoft.Json"
> 
> 

### Debug Output
No Debug output

**Comment by blueww** [comment]
@maddieclayton @markcowl 
I see the item has no assignment, and just assign to Maddie. Please correct me if the assignment is wrong.
Would you please help to update the progress on this issue?
It currently blocked the soft-delete feature support in storage. 

As we discussed before it will be resolved in 2/9 release.

**Comment by cormacpayne** [comment]
Initial change to load 10.0.3 and 6.0.8 side-by-side found in PR https://github.com/Azure/azure-powershell/pull/5599

**Comment by markcowl** [comment]
Fixed.
