### ISSUE TITLE
Enable-AzureRmTrafficManagerEndpoint  and Disable-AzureRmTrafficManagerEndpoint do not work with an argument of TrafficManagerEndpoint

### ISSUE THREAD

**Issue by hrkulkarMsft** [Azure/azure-powershell#5294]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
5.1.16299.98
### Module Version
2.1.0
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.16299.98
### Description
The functions Enable and Disable-AzureRmTrafficManagerEndpoint send a request to the invalid target URI when passed in a TrafficManagerEndpoint. Example:

The target URI is invalid when generated from a TrafficManagerEndpoint. It contains the invlaid provider properties "Microsoft.Network/trafficmanagerprofiles/contoso/**Microsoft.Network/trafficmanagerprofiles**/azureEndpoints/myAzureEndpoint". When it should be "Microsoft.Network/trafficmanagerprofiles/contoso/azureEndpoints/myAzureEndpoint".

This maybe because TrafficManagerEndpoint specifies its type as Microsoft.Network/trafficmanagerprofiles/azureEndpoints since it is a nested resource.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

1. Create a TrafficManagerProfile.
$profile = New-AzureRmTrafficManagerProfile -Name contoso-ResourceGroupName contoso-group -TrafficRoutingMethod Performance -RelativeDnsName contoso -Ttl 30 -MonitorProtocol HTTP -MonitorPort 80 -MonitorPath "/"

2. Add any Endpoint to the profile

Add-AzureRmTrafficManagerEndpointConfig -EndpointName eu-endpoint -TrafficManagerProfile $profile -Type ExternalEndpoints -Target app-eu.contoso.com -EndpointLocation "North Europe" -EndpointStatus Enabled

Set-AzureRmTrafficManagerProfile -TrafficManagerProfile $profile

3. Run (or simiarly for Disable-AzureRmTrafficManagerEndpoint):
$profile.Endpoints[0] | Enable-AzureRmTrafficManagerEndpoint

**Comment by cormacpayne** [comment]
@hrkulkarMsft would you mind upgrading to the latest version of `AzureRM.TrafficManager` and re-run the above set of commands?

**Comment by hrkulkarMsft** [comment]
Sorry Cormac, indeed was running an old version. Haven't been able to repro using up-to-date version. Will resolve!

**Comment by maddieclayton** [comment]
Closing as no repro
