### ISSUE TITLE
"What's New" Link and page

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#5325]
### Cmdlet(s)

Installation or first run.

### Description

On first run, display warning text with a link to https://aka.ms/azpsnotes.  We can also drive some changes to the release notes to include a "friendly" blurb up top.

The page linked will contain highlights from the current major release version. Overall, will be a summary of general changes for a release.

**Comment by MiYanni** [comment]
Generally, this is for just having a "What's New?" publicly, and not necessarily on first run. Collating release notes to a high-level summary is the focus.

**Comment by twitchax** [comment]
It looks like this is scheduled.  @sphibbs, to whom should this be assigned?

Also, I thin kthat we still had some asks on the PS team that may block this (i.e., `OnFirstRun` script or something).  @cormacpayne, have we discussed this with them yet?  Might be a good discussion for our next sync?

**Comment by maddieclayton** [comment]
- cmdlet that tell the difference between two version
- run this cmdlet on first run after version update

**Comment by maddieclayton** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/issues/8595
