### ISSUE TITLE
Enable Azure SSIS Integration Runtime Test

### ISSUE THREAD

**Issue by HaoQian-MS** [Azure/azure-powershell#5327]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by zhangyd2015** [comment]
Resolved with PR https://github.com/Azure/azure-powershell/pull/5485
