### ISSUE TITLE
Creating Private DNS fails to recognise Zonetype parameter

### ISSUE THREAD

**Issue by bhushangholve2006** [Azure/azure-powershell#5328]
### Cmdlet(s)
New-AzureRmDnsZone

### PowerShell Version
5.1.15063.786

### Module Version
5.1.1

### OS Version
10.0.15063.0

### Description
Trying to create private zone as per this description in the document [link](https://docs.microsoft.com/en-us/azure/dns/private-dns-getstarted-powershell)

### Debug Output
`New-AzureRmDnsZone : A parameter cannot be found that matches parameter name 'ZoneType'.
At line:1 char:71
+ ...  -Name contoso.local -ResourceGroupName fullstackgr -ZoneType Private ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureRmDnsZone], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.Dns.NewAzureDnsZone
`

### Script/Steps for Reproduction
`New-AzureRmDnsZone -Name contoso.local -ResourceGroupName samplegr -ZoneType Private -RegistrationVirtualNetworkId @($vnet.Id)`

**Comment by maddieclayton** [comment]
@karravi-msft Can you take a look? This looks like a serious issue with the Getting-Started docs.

**Comment by twitchax** [comment]
@sdwheeler, do you know who owns this docset?

**Comment by sdwheeler** [comment]
@twitchax - That [doc](https://docs.microsoft.com/en-us/azure/dns/private-dns-getstarted-powershell) is owned by @KumudD

**Comment by KumudD** [comment]
I am updating the Important note to ensure that the customer send the request to join the preview to get the Preview PowerShell module that is required for Azure DNS Private Zone.
#please-close
