### ISSUE TITLE
Positive test case for -UseOriginalStorageAccount

### ISSUE THREAD

**Issue by dragonfly91** [Azure/azure-powershell#5331]
### Cmdlet(s)
Restore-AzureRmRecoveryServicesBackupItem
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
Need to add positive test case covering the -UseOriginalStorageAccount feature.
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by cormacpayne** [comment]
@dragonfly91 has this been addressed?

**Comment by pvrk** [comment]
@siddharth7: Can you please comment on the current state?

**Comment by siddharth7** [comment]
It's an open item. We only have a negative test case in out tests for `-UseOriginalStorageAccount`.

**Comment by siddharth7** [comment]
Will be taking it in end of July or first week of August

**Comment by siddharth7** [comment]
Will be taking it in end of July or first week of August
