### ISSUE TITLE
Set-AzureRmKeyVaultAccessPolicy with EmailAddress dosen't search email.

### ISSUE THREAD

**Issue by takekazuomi** [Azure/azure-powershell#5332]
### PowerShell Version
PSVersion 5.1.17063.1000

### Module Version
AzureRM.KeyVault 4.0.1

### OS Version
10.0.17063.1000
10.0.16299.98

### Description
If you use Set-AzureRmKeyVaultAccessPolicy with EmailAddress option, it will not be searched by e-mail. It will be searched by UPN.
With this, EmailAddress is not alias, so there is no option meaning.

**Comment by maddieclayton** [comment]
Looks like this was fixed here: https://github.com/Azure/azure-powershell/pull/5334
