### ISSUE TITLE
Allow New-AzureRmVm simple parameter set to specify blank public DNS name

### ISSUE THREAD

**Issue by iainfoulds** [Azure/azure-powershell#5342]
### Cmdlet(s)
New-AzureRmVm

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

5.1.14393.1480

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

10.0.14393.1480

### Description
When using the simplified `New-AzureRmVm`, a public DNS name is automatically created. Common defaults in docs.ms.com are for VM name to by `myVM` and resource group to be `myResourceGroup`. This DNS is already then taken in the common Azure regions, so the public IP fails to create:

> New-AzureRmVm : DNS record myvmmyresourcegroup.eastus.cloudapp.azure.com is already used by another public IP.

Cannot just specify `-DomainNameLabel ""` as encounter error:

> New-AzureRmVm : The domain name label in the dnsSettings section of the public IP address myVM is null or empty. If a dnsSettings section exists, its domain name label must not be null or empty.

Suggest not assigning a public DNS name, unless a custom one is provided. Or, add some randomness to the name rather than just combining VM and resource group name.

**Comment by twitchax** [comment]
@markcowl and @sergey-shandar, I think we should do this.  I, personally, lean toward generating some randomness for the DNS name based on a hash of the name so it is idempotent.

However, let's discuss with the CLI team and make a decision on the best solution.

**Comment by sergey-shandar** [comment]
#5399

**Comment by maddieclayton** [comment]
@sergey-shandar If this is fixed can you close the issue?

**Comment by sergey-shandar** [comment]
@maddieclayton it's partly fixed. Now it creates unique id if the `DomainNameLabel` is not specified. It's still impossible to create VM without public IP. @iainfoulds, @twitchax any idea about cmdlet parameters design to support the feature?

**Comment by iainfoulds** [comment]
@sergey-shandar @maddieclayton @twitchax In the CLI, you can declare `--public-ip-address ""` which is interpreted as `none`. That's not particularly intuitive either though. 

I guess since PowerShell version wants a string, could you interpret `None` or `False`, even though not bool, as meaning the user doesn't want a public IP? If they don't want a public IP, don't then create a public DNS.

**Comment by twitchax** [comment]
I would like @markcowl's input, but I think we could have a `-IpAddressName $null`.  Is that nonstandard, @markcowl?

**Comment by twitchax** [comment]
@iainfoulds, we are leaning towards awaiting more feedback on the new parameter set before adding this functionality.  The goal of the `New-AzureRmVM` simple parameter set is to make >95% of interactive functionality easy to complete.  Advanced scenarios will continue to be covered by the existing cmdlets.

We would like to get some data or feedback from customers that interactive scenarios often require creating a VM without a public IP address.

**Comment by cormacpayne** [comment]
@nibhat @hyonholee @huangpf this isn't something that we will be able to get to in the next milestone, but it is something that the Compute team may want to look at in that time.

**Comment by ouartil** [comment]
it would be great if $null or "" could be specified in the PublicIpAddressName so it deploys the VM without public IP.

**Comment by CrazyCoder-123** [comment]
Can anyone confirm , if this issue is solved. I also need to create a VM with no public IP. Please update

**Comment by wacsintegra** [comment]
It is stuff like this ticket that makes companies be very cautious to using Azure and "features". It appears there is no concern for security by default with your systems.. Why the heck would you ever default to allowing public access to a VM that is created without being specified?! Some admins actually like to have security via NAT and Gateway to lock down systems. I am constantly finding stuff with Azure that is either a half baked product or service that was rolled out without proper development or testing. Customers are continually frustrated with your portal and security and the like this ticket, time to resolution is pathetic. @nibhat @hyonholee @huangpf @cormacpayne

**Comment by dubosecraig** [comment]
It looks like it is updated with the documentation on: 
https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/new-azurermvm?view=azurermps-6.10.0
Find: Example 3: Create a VM from a marketplace image without a Public IP

**Comment by dubosecraig** [comment]
> Can anyone confirm , if this issue is solved. I also need to create a VM with no public IP. Please update

It looks like it is updated with the documentation on:
https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/new-azurermvm?view=azurermps-6.10.0
Find: Example 3: Create a VM from a marketplace image without a Public IP

**Comment by wacsintegra** [comment]
@dubosecraig I am still running into this issue and just delete the public IP, but during configuration of your vm (New-AzureRmVMConfig) I override with a network security group locking down along with an internal IP in my subnet on the NIC configurations.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
