### ISSUE TITLE
Create Job for Recording network tests

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5353]
### Description

- [x] Add a Jenkins jobs that will run network tests live from a particular branch and fork and archive the test recordings (and results and logs)
- [x] ~~Store necessary credentials in KeyVault and use appropriate bootstrapping~~
- [x] Ensure that our test subscription has access to all necessary features (esp. ExpressRoute)
- [x] Design/add automated procedure for robust cleanup of test artifacts from the test subscription
- [ ] Work with network team to fix tests that fail in live runs
- [ ] Work with network team to remove or reenable skipped tests

### Cost: 10

**Comment by MiYanni** [comment]
Initial changes merged in via https://github.com/Azure/azure-powershell/pull/5514

**Comment by markcowl** [comment]
Closing
