### ISSUE TITLE
Shorten test run time

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5360]
### Description

- [x] Profile existing tests to determine issues with execution time.  Likely culprits include
  - [x] Not setting polling timeouts to zero in manageement clients
  - [x] Using Thread.Sleep or Sleep-Seconds instead of TestMockSupport.Delay or Wait-Seconds in test wait/retry loops
  - [x] Having very large recodring json files with too many polling requests
- [x] Fix problems with tests or file issues to fix

- [x] Determine which machines take a long time, remove them, and create new machines.

### Cost: 6

**Comment by maddieclayton** [comment]
Investigation into machines:

### PowerShell

Worker 46 - :59, 1:42, 1:03, :49, :51, 1:26, 1:37

Worker 59 - 1:19, 1:11, 1:10, 36, 1:17, 36, 1:10, 1:20

Worker 58 - 37, 1:31, 1:18, 1:29, 1:26, 1:20, 1:26, 1:23

Worker 39: 1:24, 1:15, :46, :47, :40, 1:18

Worker 27: 1:03, :35, :33, 1:05, :43, :34, 1:02, 1:12, :32, 1:11

Worker 62: 1:21, 1:23

Worker 41 - :46, :47, 1:37, 1:27, :47, 1:08, :47

Worker 63 - :41, :35, 1:16, :47, 1:15, :34, :36, :49

Worker 44 - 1:47, 1:57, 2:08, 1:14, 1:48

Worker 35: not working



### On demand

Worker 28 - 1:36, 1:42, 2:33, 1:42, 1:42

Worker 42 - 1:08, 1:08, 1:05, 1:10, 1:10, 1:07

Worker 30 - 1:39, 1:39, 1:42, 1:39, 1:41, 1:43, 1:40


### Sign job (same machines as on demand)

Worker 28 - 2:07, 1:59, 1:57

Worker 42 - 1:19

Worker 30 - 1:54

**Comment by maddieclayton** [comment]
Done
