### ISSUE TITLE
Normalize Test Logging

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5362]
### Description

Normalize test logging across scenario and unit tests to:

- [ ] Use a consistent logging mechanism across xunit tests
- [ ] Write logs to a separate file per test
- [ ] Do not retain logs for tests that pass
- [ ] Ensure that logs contain full debug messages

**Comment by MiYanni** [comment]
@sphibbs Indicate who will own build and test automation all up.

**Comment by maddieclayton** [comment]
created two new issues: https://github.com/Azure/azure-powershell/issues/6150, https://github.com/Azure/azure-powershell/issues/6149
