### ISSUE TITLE
Set-AzureRmApplicationGateway fail to run in Azure Automation worker

### ISSUE THREAD

**Issue by mortenlerudjordet** [Azure/azure-powershell#5364]
### Cmdlet(s)
Set-AzureRmApplicationGateway

### PowerShell Version
Running PS version: 5.1.14393.1914

### Module Version
AzureRM.Network Version: 5.0.0

### OS Version
Azure Automation Runbook worker

### Description
Running Set-AzureRmApplicationGateway from ISE or PS Console on desktop works, though update process takes about 10min to execute.

Running this on a Azure Automation will terminate immediately with the 
Error Message: **A command that prompts the user failed because the host program or the 
command type does not support user interaction. The host was attempting to request confirmation with the following 
message: Long running operation failed with status 'Failed'. Additional Info:'An error occurred.'**

Have tried to call it from a function in a module, and a standalone runbook with the same result.

Also I can confirm that there are no user prompts when running the code in ISE, and there seem to be no way of setting a switch on the function to ignore user prompts.

### Debug Output
Seems like debugging info is not possible to get fram code running in AA, the only thing I managed was the verbose error output

### Script/Steps for Reproduction

Will need to have created a application gateway / WAF before code below is usable.

#Requires -Modules AzureRM.Automation, AzureRM.Websites, AzureRM.Network, AzureRM.Resources
#Requires -Version 5.0  
    [CmdletBinding()]
    PARAM(
        [parameter(Mandatory=$true)]
        [String]$AppServiceResourceGroupName,
        [parameter(Mandatory=$true)]
        [String]$AppServiceName,
        [parameter(Mandatory=$true)]
        [String]$AGName,
        [parameter(Mandatory=$true)]
        [String]$AGResourceGroupName,
        [parameter(Mandatory=$true)]
        [String]$SubscriptionEnvironment,
        [parameter(Mandatory=$false)]
        [Int]$WebAppHTTPSport = 443,
        [parameter(Mandatory=$false)]
        [Bool]$EnableAGBCookieBasedAffinity = $false,
        [parameter(Mandatory=$false)]
        [String]$AGWebAppProbePath = "/",
        [parameter(Mandatory=$false)]
        [Int]$AGWebAppProbeInterval = 30,
        [parameter(Mandatory=$false)]
        [Int]$AGWebAppProbeTimeout = 60,
        [parameter(Mandatory=$false)]
        [Int]$AGWebAppProbeUnhealtyThreshold = 3,
        [parameter(Mandatory=$false)]
        [String]$AGWebAppProbePort = "HTTPS",
        [parameter(Mandatory=$false)]
        [int]$AGBackendRequestTimeOut = 30,
        [parameter(Mandatory=$false)]
        [String]$AGBackendProtocol = "HTTPS",
        [parameter(Mandatory=$false)]
        [Int]$AGBackendPort = 443,
        [parameter(Mandatory=$false)]
        [String]$AGHttpListenerProtocol = "HTTPS",
        [parameter(Mandatory=$false)]
        [String]$AGRequestRoutingRuleType = "Basic"
)
    $VerbosePreference = "silentlycontinue"
    Import-Module -Name AzureRM.Automation, AzureRM.Websites, AzureRM.Network, AzureRM.Resources -ErrorAction Continue -ErrorVariable oErr
    If($oErr) {
        Throw "Failed to load needed modules for Runbook. Error: $($oErr.Message)"
    }

    # Login to correct subscription to get the App Service Name that was created
    # Details about Prod
    $AzureConnection = Get-AutomationConnection -Name "AzureRunAsConnection"
    # Details about DevTest 
    $AzureTestConnection = Get-AutomationConnection -Name "AzureTestRunAsConnection"
    $AzureRunAsCertificate = Get-AutomationCertificate -Name "AzureRunAsCertificate"

    # ADD certificate if it is not in the cert store of the user
    if ((Test-Path Cert:\CurrentUser\My\$($AzureConnection.CertificateThumbprint)) -eq $false)
    {
        Write-Verbose -Message "Installing the Service Principal's certificate..."
        $store = new-object System.Security.Cryptography.X509Certificates.X509Store("My", "CurrentUser")
        $store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::MaxAllowed)
        $store.Add($AzureRunAsCertificate) 
        $store.Close()
    }

    $cert = Get-ChildItem -Path Cert:\CurrentUser\my | Where-Object {$_.Thumbprint -eq $($AzureConnection.CertificateThumbprint)}
    If($($cert.PrivateKey.CspKeyContainerInfo.Accessible) -eq $True) {
        Write-Verbose -Message "Private key of login certificate is accessible" 
    }
    Else {
        Write-Error -Message "Private key of login certificate is NOT accessible, check you user certificate store if the private key is missing or damaged" -ErrorAction Continue
        Throw "Private key of login certificate is NOT accessible, check you user certificate store if the private key is missing or damaged"
    }

    # Check if App service is deployed in DevTest or Prod subscription and login to correct one
    If($SubscriptionEnvironment -eq "Test") {
        Write-Verbose -Message "Login DevTest"
        Login-AzureRmAccount -ServicePrincipal -ApplicationId $AzureTestConnection.ApplicationId -CertificateThumbprint $AzureTestConnection.CertificateThumbprint -TenantId $AzureTestConnection.TenantId -SubscriptionId $AzureTestConnection.SubscriptionId -ErrorAction SilentlyContinue -ErrorVariable oErr
        If($oErr) {
            Throw "Failed to connect to DevTest Azure. Error: $($oErr.Message)"
        } 
    }
    Else  {
        Write-Verbose -Message "Login Production"
        Login-AzureRmAccount -ServicePrincipal -ApplicationId $AzureConnection.ApplicationId -CertificateThumbprint $AzureConnection.CertificateThumbprint -TenantId $AzureConnection.TenantId -SubscriptionId $AzureConnection.SubscriptionId -ErrorAction SilentlyContinue -ErrorVariable oErr
        If($oErr) {
            Throw "Failed to connect to Production Azure. Error: $($oErr.Message)"
        } 
    }

    $VerbosePreference = "Continue"

    # FQDN of the web app
    $WebApp = Get-AzureRmWebApp -Name $AppServiceName -ResourceGroupName $AppServiceResourceGroupName -ErrorAction SilentlyContinue -ErrorVariable oErr    
    If($oErr)
    {    
        Write-Error -Message "Error retrieving App Service object for: $AppServiceName. Error: $oErr" -ErrorAction Continue
        Throw "Error retrieving App Service object for: $AppServiceName. Error: $oErr"
    }
    $AGFrontendPortName = "Default-AGFrontendPort"
    $AGFrontendIPConfigName = "Default-AGFrontendIPConfig"
    $AGHttpListenerName = "$($WebApp.Name)-AGListener"
    # Frontend same as backend    
    $AGRequestRoutingRuleName = "$($WebApp.Name)-AGrrRule"
    $AGBAddressPoolName = "$($WebApp.Name)-AGBAddressPool"
    #$AGBackendAddressPoolStatusCode = @("200-399","500","503")
    $AGBackendAddressPoolStatusCode = @("200-399")
    $AGProbeConfigName = "$($WebApp.Name)-AGprobeConfig"            
    $AGBHttpSettingsName = "$($WebApp.Name)-AGBSettings"
    If($EnableAGBCookieBasedAffinity) {
        $AGBCookieBasedAffinity = "Enabled"
    }
    Else {
        $AGBCookieBasedAffinity = "Disabled"
    }
    $AGFAuthenticationCertificateName = "FrontEnd-Cert"                
    $AgWAFReady = $False

    Write-Verbose -Message "Retrieving Application Gateway/WAF object"
    $AgWAF = Get-AzureRmApplicationGateway -Name $AGName -ResourceGroupName $AGResourceGroupName -ErrorAction SilentlyContinue -ErrorVariable oErr
    If($oErr)
    {    
        Write-Error -Message "Error retrieving Application Gateway object for: $AGName. Error: $oErr" -ErrorAction Continue
        Throw "Error retrieving Application Gateway object for: $AGName. Error: $oErr"
    }
    Do {        
        # Check that AG/WAF is not updating
        If($AgWAF.ProvisioningState -eq "Succeeded") {
            Write-Verbose -Message "Application Gateway / WAF is in a consistent state and can be changed" 
            $AgWAFReady = $True           
        }
        ElseIf($AgWAF.ProvisioningState -eq "Updating") {
            Write-Verbose -Message "Application Gateway/WAF is updating, waiting for it to finish"            
            # Sleep for a minute
            Start-Sleep -Seconds 60
            # Retrieve an existing application gateway
            Write-Verbose -Message "Retrieving Application Gateway/WAF object to get updated ProvisioningState"
            $AgWAF = Get-AzureRmApplicationGateway -Name $AGName -ResourceGroupName $AGResourceGroupName -ErrorAction SilentlyContinue -ErrorVariable oErr
            If($oErr)
            {    
                Write-Error -Message "Error retrieving Application Gateway object for: $AGName. Error: $oErr" -ErrorAction Continue
                Throw "Error retrieving Application Gateway object for: $AGName. Error: $oErr"
            }
        }
        Else {
            Write-Error -Message "Application Gateway/WAF is in a state that can not be updated: $($AgWAF.ProvisioningState)" -ErrorAction Continue
            Throw "Application Gateway/WAF is in a state that can not be updated: $($AgWAF.ProvisioningState)"
        }
    }
    While($AgWAFReady -eq $false)

    # Define the status codes to match for the probe
    $AGHealthResponseMatch = New-AzureRmApplicationGatewayProbeHealthResponseMatch -StatusCode $AGBackendAddressPoolStatusCode -ErrorAction SilentlyContinue -ErrorVariable oErr
    If($oErr)
    {    
        Write-Error -Message "Error creating a new Application Gateway Probe Health Response Match. Error: $oErr" -ErrorAction Continue
        Throw "Error creating a new Application Gateway Probe Health Response Match. Error: $oErr"
    }

    Write-Verbose -Message "Adding Probe config to Application Gateway/WAF"
    Add-AzureRmApplicationGatewayProbeConfig -Name $AGProbeConfigName -ApplicationGateway $AgWAF -Protocol $AGWebAppProbePort -Path $AGWebAppProbePath `
        -Interval $AGWebAppProbeInterval -Timeout $AGWebAppProbeTimeout -UnhealthyThreshold $AGWebAppProbeUnhealtyThreshold -Match $AGHealthResponseMatch -PickHostNameFromBackendHttpSettings -ErrorAction SilentlyContinue -ErrorVariable oErr
    If($oErr)
    {    
        Write-Error -Message "Error creating a new Application Gateway Probe Config. Error: $oErr" -ErrorAction Continue
        Throw "Error creating a new Application Gateway Probe Config. Error: $oErr"
    }

    # Get newly created AG Probe Config
    $AGProbeConfig = Get-AzureRmApplicationGatewayProbeConfig -name $AGProbeConfigName -ApplicationGateway $AgWAF -ErrorAction SilentlyContinue -ErrorVariable oErr
    If($oErr)
    {    
        Write-Error -Message "Error retrieving Application Gateway Probe Config. Error: $oErr" -ErrorAction Continue
        Throw "Error retrieving Application Gateway Probe Config. Error: $oErr"
    }

    # Backend certificate public key (certificate of protected web site)     
    $BackEndCert = Get-AzureRmApplicationGatewayAuthenticationCertificate -Name $AgWAF.AuthenticationCertificates[0].Name -ApplicationGateway $AgWAF -ErrorAction SilentlyContinue -ErrorVariable oErr    
    If($oErr)
    {    
        Write-Error -Message "Error retrieving Application Gateway Authentication Certificate. Error: $oErr" -ErrorAction Continue
        Throw "Error retrieving Application Gateway Authentication Certificate. Error: $oErr"
    }
    
    # Create backend pool Settings
    Write-Verbose -Message "Adding backend http settings to WAF"
    Add-AzureRmApplicationGatewayBackendHttpSettings -Name $AGBHttpSettingsName -ApplicationGateway $AgWAF -PickHostNameFromBackendAddress `
        -Port $AGBackendPort -Protocol $AGBackendProtocol -CookieBasedAffinity $AGBCookieBasedAffinity -RequestTimeout $AGBackendRequestTimeOut -Probe $AGProbeConfig -AuthenticationCertificates $BackEndCert -ErrorAction SilentlyContinue -ErrorVariable oErr
    If($oErr)
    {    
        Write-Error -Message "Error adding Application Gateway Backend Http Settings. Error: $oErr" -ErrorAction Continue
        Throw "Error adding Application Gateway Backend Http Settings. Error: $oErr"
    }
    # Make sure all backend HTTP Settings have the correct Authentication Certificate set
    ForEach($BackendHttpSetting in $AgWAF.BackendHttpSettingsCollection) {
        If($BackendHttpSetting.AuthenticationCertificates) {
            Write-Verbose -Message "Backend HTTP Settings object has authentication certificate set"
        }
        Else {
            # Need to set the same auth cert as all others            
            Set-AzureRmApplicationGatewayBackendHttpSettings -Name $BackendHttpSetting.Name -ApplicationGateway $AgWAF -PickHostNameFromBackendAddress `
            -Port $AGBackendPort -Protocol $AGBackendProtocol -CookieBasedAffinity $AGBCookieBasedAffinity -RequestTimeout $AGBackendRequestTimeOut -Probe $AGProbeConfig `
            -AuthenticationCertificates $BackEndCert -ErrorAction SilentlyContinue -ErrorVariable oErr
            If($oErr)
            {    
                Write-Error -Message "Error adding Application Gateway Backend Http Settings for $($BackendHttpSetting.Name). Error: $oErr" -ErrorAction Continue
                Throw "Error adding Application Gateway Backend Http Settings for $($BackendHttpSetting.Name). Error: $oErr"
            }
        }
    }

    # Add backend pool
    Write-Verbose -Message "Adding backend address pool"
    Add-AzureRmApplicationGatewayBackendAddressPool -Name $AGBAddressPoolName -ApplicationGateway $AgWAF -BackendFqdns $WebApp[0].DefaultHostName -ErrorAction SilentlyContinue -ErrorVariable oErr
    If($oErr)
    {    
        Write-Error -Message "Error adding Application Gateway Backend Address Pool. Error: $oErr" -ErrorAction Continue
        Throw "Error adding Application Gateway Backend Address Pool. Error: $oErr"
    }

    # Get Frontend config for use with adding new Listener
    $AGFrontendPort = Get-AzureRmApplicationGatewayFrontendPort -Name $AGFrontendPortName -ApplicationGateway $AgWAF -ErrorAction SilentlyContinue -ErrorVariable oErr
    If($oErr)
    {    
        Write-Error -Message "Failed to retrieve Application Gateway frontend port config. Error: $oErr" -ErrorAction Continue
        Throw "Failed to retrieve Application Gateway frontend port config. Error: $oErr"
    }
    $FrontEndCertificate = Get-AzureRmApplicationGatewaySSLCertificate -Name $AGFAuthenticationCertificateName -ApplicationGateway $AgWAF -ErrorAction SilentlyContinue -ErrorVariable oErr
    If($oErr)
    {    
        Write-Error -Message "Failed to retrieve Application Gateway SSL Certificate config. Error: $oErr" -ErrorAction Continue
        Throw "Failed to retrieve Application Gateway SSL Certificate config. Error: $oErr"
    }
    $AGFrontendIPConfig = Get-AzureRmApplicationGatewayFrontendIPConfig -Name $AGFrontendIPConfigName -ApplicationGateway $AgWAF -ErrorAction SilentlyContinue -ErrorVariable oErr
    If($oErr)
    {    
        Write-Error -Message "Failed to retrieve Application Gateway frontend IP config. Error: $oErr" -ErrorAction Continue
        Throw "Failed to retrieve Application Gateway frontend IP config. Error: $oErr"
    }

    # Add new Listener
    Add-AzureRmApplicationGatewayHttpListener -Name $AGHttpListenerName -Protocol $AGHttpListenerProtocol -FrontendIPConfiguration $AGFrontendIPConfig -FrontendPort $AGFrontendPort `
        -SslCertificate $FrontEndCertificate -HostName "$AppServiceName.$AGwafRootDNS" -RequireServerNameIndication true -ApplicationGateway $AgWAF
    # Retrieve added config to create request routing rule
    $AGBHttpSettings = Get-AzureRmApplicationGatewayBackendHttpSettings -Name $AGBHttpSettingsName -ApplicationGateway $AgWAF -ErrorAction SilentlyContinue -ErrorVariable oErr
    If($oErr)
    {    
        Write-Error -Message "Failed to retrieve Application Gateway frontend IP config. Error: $oErr" -ErrorAction Continue
        Throw "Failed to retrieve Application Gateway frontend IP config. Error: $oErr"
    }
    $AGBackendAddressPool = Get-AzureRmApplicationGatewayBackendAddressPool -Name $AGBAddressPoolName -ApplicationGateway $AgWAF -ErrorAction SilentlyContinue -ErrorVariable oErr
    If($oErr)
    {    
        Write-Error -Message "Failed to retrieve Application Gateway frontend IP config. Error: $oErr" -ErrorAction Continue
        Throw "Failed to retrieve Application Gateway frontend IP config. Error: $oErr"
    }
    $AGHttpListener = Get-AzureRmApplicationGatewayHttpListener -Name $AGHttpListenerName -ApplicationGateway $AgWAF -ErrorAction SilentlyContinue -ErrorVariable oErr
    {    
        Write-Error -Message "Failed to retrieve Application Gateway frontend IP config. Error: $oErr" -ErrorAction Continue
        Throw "Failed to retrieve Application Gateway frontend IP config. Error: $oErr"
    }
    # Add Request Routing Rule
    Add-AzureRmApplicationGatewayRequestRoutingRule -Name $AGRequestRoutingRuleName -RuleType $AGRequestRoutingRuleType -BackendHttpSettings $AGBHttpSettings `
        -HttpListener $AGHttpListener -BackendAddressPool $AGBackendAddressPool -ApplicationGateway $AgWAF -ErrorAction SilentlyContinue -ErrorVariable oErr
    If($oErr)
    {    
        Write-Error -Message "Failed to retrieve Application Gateway request routing rule config. Error: $oErr" -ErrorAction Continue
        Throw "Failed to retrieve Application Gateway request routing rule config. Error: $oErr"
    }

    # Update the application gateway
    Write-Verbose -Message "Committing changes to Application Gateway/WAF"
    $DebugPreference="Continue"
    Set-AzureRmApplicationGateway -ApplicationGateway $AgWAF -Verbose:$True -Debug:$True
    $DebugPreference="silentlycontinue"

**Comment by markcowl** [comment]
@mortenlerudjordet This is caused by your -Debug setting for the cmdlet.  Using the default Debug parameter in a cmdlet forces user validation of each debug message.  if you remove this, the user interaction issue should disappear.

**Comment by mortenlerudjordet** [comment]
Was more the lack of good error messages that was throwing me. I figured it out with the help of a support case with MS. I have also opened a separate issue for getting better verbose error messages from the module. Though as I understand it this might also have to be reflected by the API not sending generic 500 errors.
