### ISSUE TITLE
Replace dependencies on management libraries with common code

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#5365]
There are a handful of modules that have a dependency on a specific management library for a separate service. We need to investigate if the module needs that dependency, and if so, replace it with the common (generated) code for that library.

Below are the modules currently management libraries being used by different modules:

`Compute`
- Microsoft.Azure.Management.Storage [NetCore in Common.Storage.Netcore]
    - [x] Desktop
    - [x] .NET Core
- Microsoft.Azure.Management.KeyVault
    - [x] Desktop
    - [x] .NET Core

`LogicApp`
- Microsoft.Azure.Management.WebSites
    - [x] Desktop
    - [x] .NET Core

`ServiceFabric`
- Microsoft.Azure.Management.Compute
    - [x] Desktop
    - [x] .NET Core
- Microsoft.Azure.Management.KeyVault
    - [x] Desktop
    - [x] .NET Core
- Microsoft.Azure.Management.Network
    - [x] Desktop
    - [x] .NET Core
- Microsoft.Azure.Management.ResourceManager
    - [x] Desktop
    - [x] .NET Core
- Microsoft.Azure.Management.Storage
    - [x] Desktop
    - [x] .NET Core

`Sql`
- Microsoft.Azure.Management.Storage
    - [ ] Desktop
    - [ ] .NET Core

## Cost: 4

**Comment by MiYanni** [comment]
@praries880 How many of these are remaining? I should have made the original issue a checklist. My bad.

**Comment by cormacpayne** [comment]
Updated description to specify desktop vs. .NET Core
