### ISSUE TITLE
Clone web deployment slots template does a case sensitive comparison to get the normalized slotnames. 

### ISSUE THREAD

**Issue by naveedaz** [Azure/azure-powershell#5372]
### Cmdlet(s)

New-AzureRmWebApp -ResourceGroupName $rg -Name $destAppName -Location "Nor
th Europe" -AppServicePlan SimonWebTest3 -SourceWebApp $srcapp -IncludeSourceWebAppSlots -debug

### Affected branches
preview
websites-preview

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
The issue is that deployment template created for the slots uses the slotNames from the source web app. The slotNames are of the format sitename/slotName. We explicitly remove the “sitename/” prefix when creating the deployment template so that it is just the slot names. Unfortunately the replace method is case sensitive. 

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

$destapp = New-AzureRmWebApp -ResourceGroupName SimonWebTest3 -Name SimonWebTest3 -Location "Nor
th Europe" -AppServicePlan SimonWebTest3 -SourceWebApp $srcapp -IncludeSourceWebAppSlots -debug
DEBUG: 17:29:16 - NewAzureWebAppCmdlet begin processing with ParameterSet 'S1'.
 
Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): Y
DEBUG: 17:29:19 - using account id 'simonbro@softcat.com'...
 
Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: [Common.Authentication]: Authenticating using Account: 'simonbro@softcat.com', environment: 'AzureCloud',
tenant: 'd9247c47-02d4-45c4-854d-0f1700022b73'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/11/2018 17:29:20: 43f76633-fdb4-4a7c-b00e-cd9b9be3c3ba - AcquireTokenHandlerBase: === Token Acquisition
started:
Authority: https://login.microsoftonline.com/d9247c47-02d4-45c4-854d-0f1700022b73/
Resource: https://management.core.windows.net/
ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (35 items)
Authentication Target: User
 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/11/2018 17:29:20:  - TokenCache: Deserialized 35 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 01/11/2018 17:29:20: 43f76633-fdb4-4a7c-b00e-cd9b9be3c3ba - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/11/2018 17:29:20: 43f76633-fdb4-4a7c-b00e-cd9b9be3c3ba - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 01/11/2018 17:29:20: 43f76633-fdb4-4a7c-b00e-cd9b9be3c3ba - TokenCache: 53.35446731 minutes left until token in
cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/11/2018 17:29:20: 43f76633-fdb4-4a7c-b00e-cd9b9be3c3ba - TokenCache: A matching item (access token or refresh
token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/11/2018 17:29:20: 43f76633-fdb4-4a7c-b00e-cd9b9be3c3ba - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
Access Token Hash: /ReFMpX6KBwpZzx11ZOEfGV8cGjqXS2TawEQOMhZWHk=
Refresh Token Hash: pX5CqZnqI0/VJhYBJdEq/Oi0GUxFzFCtoJvPMsaV6Ds=
Expiration Time: 01/11/2018 18:22:42 +00:00
User Hash: 3VSeo2ZDtGmX0mjy++BT+UTEYSpx9tEfvaW+PsSlCUs=
 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/11/2018 17:29:20: 596c35c2-9073-416b-9fa1-39037aaed63e - AcquireTokenHandlerBase: === Token Acquisition
started:
Authority: https://login.microsoftonline.com/d9247c47-02d4-45c4-854d-0f1700022b73/
Resource: https://management.core.windows.net/
ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (35 items)
Authentication Target: User
 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/11/2018 17:29:20:  - TokenCache: Deserialized 35 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 01/11/2018 17:29:20: 596c35c2-9073-416b-9fa1-39037aaed63e - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/11/2018 17:29:20: 596c35c2-9073-416b-9fa1-39037aaed63e - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 01/11/2018 17:29:20: 596c35c2-9073-416b-9fa1-39037aaed63e - TokenCache: 53.3541679533333 minutes left until
token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/11/2018 17:29:20: 596c35c2-9073-416b-9fa1-39037aaed63e - TokenCache: A matching item (access token or refresh
token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/11/2018 17:29:20: 596c35c2-9073-416b-9fa1-39037aaed63e - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
Access Token Hash: /ReFMpX6KBwpZzx11ZOEfGV8cGjqXS2TawEQOMhZWHk=
Refresh Token Hash: pX5CqZnqI0/VJhYBJdEq/Oi0GUxFzFCtoJvPMsaV6Ds=
Expiration Time: 01/11/2018 18:22:42 +00:00
User Hash: 3VSeo2ZDtGmX0mjy++BT+UTEYSpx9tEfvaW+PsSlCUs=
 
DEBUG: ============================ HTTP REQUEST ============================
 
HTTP Method:
GET
 
Absolute Uri:
https://management.azure.com/subscriptions/66896031-f054-428a-a702-116153c3deea/resourceGroups/SimonWebTest2/providers/
Microsoft.Web/sites/SimonWebTest2/slots?api-version=2015-08-01
 
Headers:
x-ms-client-request-id        : 1f83238c-7221-48f2-af29-4e418a0b2891
accept-language               : en-US
 
Body:
 
 
DEBUG: ============================ HTTP RESPONSE ============================
 
Status Code:
OK
 
Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 05d7834d-bcb4-4e42-892e-d6f9ce8bb448
x-ms-ratelimit-remaining-subscription-reads: 14991
x-ms-correlation-request-id   : 6f20ce6a-69f4-460e-a4e1-9dc841c2b742
x-ms-routing-request-id       : UKWEST:20180111T172921Z:6f20ce6a-69f4-460e-a4e1-9dc841c2b742
Cache-Control                 : no-cache
Date                          : Thu, 11 Jan 2018 17:29:21 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
 
Body:
{
  "value": [
    {
      "id":
"/subscriptions/66896031-f054-428a-a702-116153c3deea/resourceGroups/SimonWebTest2/providers/Microsoft.Web/sites/simonwe
btest2/slots/prod",
      "name": "simonwebtest2/prod",
      "type": "Microsoft.Web/sites/slots",
      "kind": "app",
      "location": "North Europe",
      "properties": {
        "name": "simonwebtest2(prod)",
        "state": "Running",
        "hostNames": [
          "softcat.ent.sbal.info",
          "simonwebtest2-prod.azurewebsites.net"
        ],
        "webSpace": "SimonWebTest2-NorthEuropewebspace",
        "selfLink":
"https://waws-prod-db3-097.api.azurewebsites.windows.net:454/subscriptions/66896031-f054-428a-a702-116153c3deea/webspac
es/SimonWebTest2-NorthEuropewebspace/sites/simonwebtest2",
        "repositorySiteName": "simonwebtest2",
        "owner": null,
        "usageState": 0,
        "enabled": true,
        "adminEnabled": true,
        "enabledHostNames": [
          "softcat.ent.sbal.info",
          "simonwebtest2-prod.azurewebsites.net",
          "simonwebtest2-prod.scm.azurewebsites.net"
        ],
        "siteProperties": {
          "metadata": null,
          "properties": [],
          "appSettings": null
        },
        "availabilityState": 0,
        "sslCertificates": null,
        "csrs": [],
        "cers": null,
        "siteMode": null,
        "hostNameSslStates": [
          {
            "name": "simonwebtest2-prod.azurewebsites.net",
            "sslState": 0,
            "ipBasedSslResult": null,
            "virtualIP": null,
            "thumbprint": null,
            "toUpdate": null,
            "toUpdateIpBasedSsl": null,
            "ipBasedSslState": 0,
            "hostType": 0
          },
          {
            "name": "simonwebtest2-prod.scm.azurewebsites.net",
            "sslState": 0,
            "ipBasedSslResult": null,
            "virtualIP": null,
            "thumbprint": null,
            "toUpdate": null,
            "toUpdateIpBasedSsl": null,
            "ipBasedSslState": 0,
            "hostType": 1
          },
          {
            "name": "softcat.ent.sbal.info",
            "sslState": 1,
            "ipBasedSslResult": null,
            "virtualIP": null,
            "thumbprint": "46075216D9C5F7A14B4E4D9F2D8694890682AB65",
            "toUpdate": null,
            "toUpdateIpBasedSsl": null,
            "ipBasedSslState": 0,
            "hostType": 0
          }
        ],
        "computeMode": null,
        "serverFarm": null,
        "serverFarmId":
"/subscriptions/66896031-f054-428a-a702-116153c3deea/resourceGroups/SimonWebTest2/providers/Microsoft.Web/serverfarms/S
imonWebTest2",
        "reserved": false,
        "lastModifiedTimeUtc": "2017-12-22T11:41:51.85",
        "storageRecoveryDefaultState": "Running",
        "contentAvailabilityState": 0,
        "runtimeAvailabilityState": 0,
        "siteConfig": null,
        "deploymentId": "simonwebtest2__98d1",
        "trafficManagerHostNames": null,
        "sku": "Premium",
        "scmSiteAlsoStopped": false,
        "targetSwapSlot": null,
        "hostingEnvironment": null,
        "hostingEnvironmentProfile": null,
        "clientAffinityEnabled": true,
        "clientCertEnabled": false,
        "hostNamesDisabled": false,
        "domainVerificationIdentifiers": null,
        "kind": "app",
        "outboundIpAddresses": "13.74.41.233,13.79.246.78,13.79.242.20,13.79.241.74,13.79.243.209",
        "possibleOutboundIpAddresses":
"13.74.41.233,13.79.246.78,13.79.242.20,13.79.241.74,13.79.243.209,13.79.247.254,13.79.247.41",
        "containerSize": 0,
        "dailyMemoryTimeQuota": 0,
        "suspendedTill": null,
        "siteDisabledReason": 0,
        "functionExecutionUnitsCache": null,
        "maxNumberOfWorkers": null,
        "homeStamp": "waws-prod-db3-097",
        "cloningInfo": null,
        "snapshotInfo": null,
        "hostingEnvironmentId": null,
        "tags": null,
        "resourceGroup": "SimonWebTest2",
        "defaultHostName": "simonwebtest2-prod.azurewebsites.net",
        "slotSwapStatus": null,
        "httpsOnly": false
      }
    },
    {
      "id":
"/subscriptions/66896031-f054-428a-a702-116153c3deea/resourceGroups/SimonWebTest2/providers/Microsoft.Web/sites/simonwe
btest2/slots/Dev",
      "name": "simonwebtest2/Dev",
      "type": "Microsoft.Web/sites/slots",
      "kind": "app",
      "location": "North Europe",
      "properties": {
        "name": "simonwebtest2(Dev)",
        "state": "Running",
        "hostNames": [
          "simonwebtest2-dev.azurewebsites.net"
        ],
        "webSpace": "SimonWebTest2-NorthEuropewebspace",
        "selfLink":
"https://waws-prod-db3-097.api.azurewebsites.windows.net:454/subscriptions/66896031-f054-428a-a702-116153c3deea/webspac
es/SimonWebTest2-NorthEuropewebspace/sites/simonwebtest2",
        "repositorySiteName": "simonwebtest2",
        "owner": null,
        "usageState": 0,
        "enabled": true,
        "adminEnabled": true,
        "enabledHostNames": [
          "simonwebtest2-dev.azurewebsites.net",
          "simonwebtest2-dev.scm.azurewebsites.net"
        ],
        "siteProperties": {
          "metadata": null,
          "properties": [],
          "appSettings": null
        },
        "availabilityState": 0,
        "sslCertificates": null,
        "csrs": [],
        "cers": null,
        "siteMode": null,
        "hostNameSslStates": [
          {
            "name": "simonwebtest2-dev.azurewebsites.net",
            "sslState": 0,
            "ipBasedSslResult": null,
            "virtualIP": null,
            "thumbprint": null,
            "toUpdate": null,
            "toUpdateIpBasedSsl": null,
            "ipBasedSslState": 0,
            "hostType": 0
          },
          {
            "name": "simonwebtest2-dev.scm.azurewebsites.net",
            "sslState": 0,
            "ipBasedSslResult": null,
            "virtualIP": null,
            "thumbprint": null,
            "toUpdate": null,
            "toUpdateIpBasedSsl": null,
            "ipBasedSslState": 0,
            "hostType": 1
          }
        ],
        "computeMode": null,
        "serverFarm": null,
        "serverFarmId":
"/subscriptions/66896031-f054-428a-a702-116153c3deea/resourceGroups/SimonWebTest2/providers/Microsoft.Web/serverfarms/S
imonWebTest2",
        "reserved": false,
        "lastModifiedTimeUtc": "2017-12-22T11:41:51.8666667",
        "storageRecoveryDefaultState": "Running",
        "contentAvailabilityState": 0,
        "runtimeAvailabilityState": 0,
        "siteConfig": null,
        "deploymentId": "simonwebtest2__b3dc",
        "trafficManagerHostNames": null,
        "sku": "Premium",
        "scmSiteAlsoStopped": false,
        "targetSwapSlot": null,
        "hostingEnvironment": null,
        "hostingEnvironmentProfile": null,
        "clientAffinityEnabled": true,
        "clientCertEnabled": false,
        "hostNamesDisabled": false,
        "domainVerificationIdentifiers": null,
        "kind": "app",
        "outboundIpAddresses": "13.74.41.233,13.79.246.78,13.79.242.20,13.79.241.74,13.79.243.209",
        "possibleOutboundIpAddresses":
"13.74.41.233,13.79.246.78,13.79.242.20,13.79.241.74,13.79.243.209,13.79.247.254,13.79.247.41",
        "containerSize": 0,
        "dailyMemoryTimeQuota": 0,
        "suspendedTill": null,
        "siteDisabledReason": 0,
        "functionExecutionUnitsCache": null,
        "maxNumberOfWorkers": null,
        "homeStamp": "waws-prod-db3-097",
        "cloningInfo": null,
        "snapshotInfo": null,
        "hostingEnvironmentId": null,
        "tags": null,
        "resourceGroup": "SimonWebTest2",
        "defaultHostName": "simonwebtest2-dev.azurewebsites.net",
        "slotSwapStatus": null,
        "httpsOnly": false
      }
    }
  ],
  "nextLink": null,
  "id": null
}

**Comment by panchagnula** [comment]
This has already been merged & released in websites-preview
