### ISSUE TITLE
Update ClientRuntime

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5380]
### Description

- [x] Update ClientRuntime for cmdlet projects
- [x] Attempt to update ClientRuntime for test projects, update for as many as possible, determine scope of work for those not updated and file appropriate issues

### Cost: 4

**Comment by cormacpayne** [comment]
- `Microsoft.Rest.ClientRuntime` has been updated to 2.3.11 across all projects
- `Microsoft.Rest.ClientRuntime.Azure` has been updated to 3.3.12 across all projects
- [`Common.Dependencies.Test.targets`](https://github.com/Azure/azure-powershell/blob/preview/tools/Common.Dependencies.Test.targets) added to every test project, which references both of the above packages
