### ISSUE TITLE
Set-AzureRmApiManagementPolicy does not show validation errors

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-powershell#5386]
### Cmdlet(s)
**Set-AzureRmApiManagementPolicy** *(Module: AzureRM.ApiManagement)*

### Module Version
5.1.1

### Description
*Set-AzureRmApiManagementPolicy* always validates a policy before it deploys it. When the policy is invalid it will show an error but unfortunately the error message is removed.

### Script/Steps for Reproduction
- Use Set-AzureRmApiManagementPolicy with a policy that is not valid

You will receive the following message without more information:
> ValidationError: One or more fields contain incorrect values:

**Comment by markcowl** [comment]
@tomkerkhove Try using Resolve-AzureRmError - this returns the actual stack of exceptions that resulted in the error and may provide relevant details in this case.

**Comment by markcowl** [comment]
@solankisamir Can we look at producing a better default message in the case of validation errors?

**Comment by tomkerkhove** [comment]
@markcowl Problem is that we do not run this manually but part of our release pipeline so we cannot do that. Thanks for looking into this!

**Comment by solankisamir** [comment]
@markcowl  ack!

**Comment by tomkerkhove** [comment]
Any update on this?

**Comment by solankisamir** [comment]
We are working on the fix. This is how the error message will look like

> PS D:\github\azure-powershell> Set-AzApiManagementPolicy -Context $context -PolicyFilePath C:\Users\sasolank\Downloads\wrongpolicy.xml -ApiId httpbin
Set-AzApiManagementPolicy : 
Error Code: ValidationError
Error Message: One or more fields contain incorrect values:
Error Details:
        [Code=ValidationError, Message=Error in element 'log-to-eventhub' on line 3, column 10: Logger not found, Target=log-to-eventhub]

**Comment by solankisamir** [comment]
package: https://www.powershellgallery.com/packages/Az/2.1.0

documentation: https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/?view=azps-2.1.0#api_management

releasenotes: https://github.com/Azure/azure-powershell/releases/tag/v2.1.0-May2019
