### ISSUE TITLE
Build failure when running netcore build first

### ISSUE THREAD

**Issue by devigned** [Azure/azure-powershell#5390]
### PowerShell Version
5.1.16299.98

### Module Version
Preview branch

### Description
If you initially build the netcore solution, the subsequent full framework builds will fail due to HelpGeneration validation failures due to the netcore ps modules existing in the `./src/Packages` directory.

### Script/Steps for Reproduction
`dotnet msbuild build.proj /t:BuildNetCore`
`msbuild build.proj`

**Comment by cormacpayne** [comment]
This is fixed
