### ISSUE TITLE
Update TestMappings.Json

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5392]
### Description
- [x] Update TestMappings.json for new test assemblies
- [ ] Determine how we can generate TestMappings.json from the directory structure
  - [ ] Create a script to do this, or file a bug
- [ ] Run test assemblies for projects that take a dependency on the changed module

### Cost: 2

**Comment by cormacpayne** [comment]
Updated `TestMappings.json` in PR https://github.com/Azure/azure-powershell/pull/5431
