### ISSUE TITLE
New-Azurewebsite conflicts with non existing sites

### ISSUE THREAD

**Issue by banibal** [Azure/azure-powershell#54]
New-Azurewebsite throws error: Website with given name [name] already exists. 
But i cant see the site(s) in azure portal. 
And when i run Get-Azurewebsite it only returns the sites that i actually can see in the portal.
I have also tried to run Remove-Azurewebsite, but these "ghost" sites doesnt get deleted. 

someone with same problem?

**Comment by andybatescc** [comment]
Can only think that the conflicting website already exists under azurewebsites.net, which is shared across all Azure. Same as trying to create a new site through the management portal, but the name is not available.

**Comment by markcowl** [comment]
@andybatescc Your assessment is correct, the website name has to be globally unique.  To test it out before creation, use:
```
Test-AzureName -Website <websitename>
```

To determine if the website is already in use.

**Comment by mariusGundersen** [comment]
I get this error message also when creating a webapp in a brand new ASE with its own domain. It seems a webapp in the ASE (that has a private domain) conflicts with a webapp that uses the `.azurewebsites.net` domain. Any way to work around this issue?
