### ISSUE TITLE
ps-stack-drop build job is not producing AzureRM and AzureStack modules

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#5400]
The job is not producing the AzureRM and AzureStack uber modules. Here is the artifacts link from the job

https://azuresdkci.westus2.cloudapp.azure.com/job/ps-stack-drop/17/Azure/

**Comment by MiYanni** [comment]
Working now. Latest drop with these changes here:
https://azuresdkci.westus2.cloudapp.azure.com/job/ps-stack-drop/28/Azure/

**Comment by bganapa** [comment]
@MiYanni Thanks for the quick response. I am validating again..
