### ISSUE TITLE
Remove-AzureRmADServicePrincipal does not remove AAD App Registration

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5403]
### Cmdlet(s)
Remove-AzureRmADServicePrincipal
### PowerShell Version
5.1.16299.98
### Module Version
5.1.1
### OS Version
10.0.16299.98
### Description
When using `New-AzureRmADServicePrincipal`, whatever name you pass in for `-DisplayName` will create an AAD App Registration for that name. However, when you remove the service principal via `Remove-AzureRmADServicePrincipal`, it does not remove this AAD App Registration. So, if you try to create the service principal again with the same `-DisplayName`, it will fail with a somewhat cryptic message saying, "Another object with the same value for property identifierUris already exists." The only way I found out how to resolve the issue was via Google search of that error and finding this issue: https://github.com/Azure/pcs-cli/issues/146

My recommendation is to have `Remove-AzureRmADServicePrincipal` also remove the AAD App Registration that was created during `New-AzureRmADServicePrincipal`. An alternative solution is to simply use that AAD App Registration on `New-AzureRmADServicePrincipal` if a service principal for that AAD App Registration does not already exist. Erroring in this situation generally doesn't make a lot of sense. Additionally, I'd highly recommend having the service team make a more 'friendly' error message for this situation.
### Debug Output
N/A
### Script/Steps for Reproduction
```powershell
PS > New-AzureRmADServicePrincipal -DisplayName 'SPTestName' -Password {password}
PS > Get-AzureRmADServicePrincipal -SearchString 'SPTestName'
ServicePrincipalNames : {http://SPTestName, XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
ApplicationId         : XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
DisplayName           : SPTestName
Id                    : XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
Type                  : ServicePrincipal
PS > Remove-AzureRmADServicePrincipal -ObjectId XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX -Force # NOTE: Use the Id above
PS > Get-AzureRmADServicePrincipal -SearchString 'SPTestName' # NOTE: This returns nothing
PS > New-AzureRmADServicePrincipal -DisplayName 'SPTestName' -Password {password}
New-AzureRmADServicePrincipal : Another object with the same value for property identifierUris already exists.
At TEST.ps1:# char:##
+     New-AzureRmADServicePrincipal -DisplayName 'SPTestName' -Passwor ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-AzureRmADServicePrincipal], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ActiveDirectory.NewAzureADServicePrincipalCommand

**Comment by maddieclayton** [comment]
Closing as a dup of: https://github.com/Azure/azure-powershell/issues/4919
