### ISSUE TITLE
Tab completer for existing resources

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5415]
### Description

- If an MSI is user-assigned, then the user must pick it from the existing set of user-assigned identities from the subscription.  Add a tab completer that will query for user-assigned identities (or other existing resources of a particular type).

- Implement using a tab completer for existing resources - the completer should be able to choose resources based on a resource type
- The competer will need to be performant, and accept possible matches - this will mean having a common code mechanism that caches resources, and can effectively invalidate the cache over time or when switching contexts.  We should adap the existing resource manager tab completer to use the cachign mechanism as well.
- Any parameter that uses an existing resource would be a good candidate for adding this functionality.

Powershell reference on argument completers is here: https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.argumentcompleterattribute?view=powershellsdk-1.1.0 

Eixsting argument completers are here: https://github.com/Azure/azure-powershell/tree/preview/src/ResourceManager/Common/Commands.ResourceManager.Common/ArgumentCompleters

### Cost: 6

**Comment by MiYanni** [comment]
This is for general resource completer (not just MSI).
