### ISSUE TITLE
Update version tool to update Stack psd1 files for our module versions

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5417]
- [ ] Make the version tool update RequiredModules list with the updated version numbers of our modules for every release in the following files:
  - [ ] src\StackAdmin\AzureRM\AzureRM.psd1
  - [ ] src\StackAdmin\AzureStack\AzureStack.psd1 
  - [ ] src\StackAdmin\AzureStackAdmin\AzureRM.AzureStackAdmin.psd1
  - [ ] src\StackAdmin\AzureStackStorage\AzureRM.AzureStackStorage.psd1

(Note: Relates to https://github.com/Azure/azure-powershell/issues/5400)

**Comment by cormacpayne** [comment]
Closing as fixed
