### ISSUE TITLE
Get-AzureRmDtlVMsPerLabPolicy and other Dtl comdlets not working

### ISSUE THREAD

**Issue by ironicLemon** [Azure/azure-powershell#5422]
### Cmdlet(s)
Get-AzureRmDtlAutoShutdownPolicy
Get-AzureRmDtlVMsPerLabPolicy

### PowerShell Version
                                                                                           
PSVersion                      5.1.16299.98                                                                                      
PSEdition                      Desktop                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                           
BuildVersion                   10.0.16299.98                                                                                     
CLRVersion                     4.0.30319.42000                                                                                   
WSManStackVersion              3.0                                                                                               
PSRemotingProtocolVersion      2.3                                                                                               
SerializationVersion           1.1.0.1 

### Module Version
AzureRm.DevTestLabs 4.0.1

### Description
Calling the AzureRM.DevTestLabs cmdlts are failing with 

Get-AzureRmDtlAutoShutdownPolicy -LabName Development -ResourceGroupName DevelopmentRG735822
Get-AzureRmDtlAutoShutdownPolicy : The Resource 'Microsoft.DevTestLab/labs/DevelopmentRG735822' under resource group 
'DevelopmentRG735822' was not found.
At line:1 char:1
+ Get-AzureRmDtlAutoShutdownPolicy -LabName Development -ResourceGroupN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmDtlAutoShutdownPolicy], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DevTestLabs.GetAzureRmDtlAutoShutdownPolicy

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.DevTestLab/labs/DevelopmentRG735822' under resource group 'DevelopmentRG735822' was not found."
  }
}

**Comment by markcowl** [comment]
@ironicLemon Thanks, we have verified this issue, @iouri-s can you please take a look.

**Comment by maddieclayton** [comment]
Fixed
