### ISSUE TITLE
New-AzureRMCognitiveServicesAccount does not work as expected

### ISSUE THREAD

**Issue by energizedtech** [Azure/azure-powershell#5423]
### Cmdlet(s)
New-AzureRmCognitiveServicesAccount

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17074  1002    

### Module Version
0.9.1

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17074  1002    

### Description
From docs.microsoft.com and Get-Help New-AzureRmCognitiveServicesAccount -detailed the suggested values for type are

ComputerVision
Emotion
Face
LUIS
Recommendations
Speech
TextAnalytics
WebLM

The suggested values for SKU are

F0 (free tier)
S0
S1
S2
S3
S4

When I manually created an account in the portal I get the following value for AccountType from using Get-AzureRMCognitiveServicesAccount.

Bing.Speech

In checking the JSON from the Azure Portal the AccountType shows as 'Bing.Speech'
 
However providing neither "Speech" nor "Bing.Speech" provides positive results.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-request-id               : a4948e3b-8d66-401d-89dd-4c74f6f88fff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1197
x-ms-correlation-request-id   : 84b7c2b9-fea2-4d3b-9463-c43032851225
x-ms-routing-request-id       : CANADAEAST:20180201T162643Z:84b7c2b9-fea2-4d3b-9463-c43032851225
Cache-Control                 : no-cache
Date                          : Thu, 01 Feb 2018 16:26:42 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "error": {
    "code": "InvalidApiSetId",
    "message": "The account type 'Speech' is either invalid or unavailable in given region."
  }
}

New-AzureRmCognitiveServicesAccount : The account type 'Speech' is either invalid or unavailable in given region.
At line:1 char:1
+ New-AzureRmCognitiveServicesAccount -ResourceGroupName HSG-ResourceGr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmCognitiveServicesAccount], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.CognitiveServices.NewAzureCognitiveServicesAccountCommand

### Script/Steps for Reproduction
New-AzureRmResourceGroup -Name 'HSG-ResourceGroup' -Location 'eastus'
New-AzureRmCognitiveServicesAccount -ResourceGroupName HSG-ResourceGroup -Name HSG-Sample -Type Speech -SkuName F0 -Location eastus

**Comment by energizedtech** [comment]
I'm not sure if this helps but the JSON for Azure the Property name is "ApiType" but the one from the Cmdlet is simply "Type".   Wondering if that's all it is.

**Comment by maddieclayton** [comment]
@felixwa Can you take a look at this issue?

**Comment by felixwa** [comment]
@energizedtech , thanks for reporting this. The doc is out of date, we will update in next release. APIs in Cognitive Services are quite dynamic, API 'type' and 'SKU' are changing over time. That's why they are string fields.

**Comment by energizedtech** [comment]
Do you have the correct values?  I am working on an Article for “Hey! Scripting Guy!” on Technet and would love to have this working.   Specifically I am trying to enable to Bing.Speech 😊


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by felixwa** [comment]
https://github.com/Azure/azure-powershell/pull/5794

**Comment by maddieclayton** [comment]
Closing as fixed.
