### ISSUE TITLE
Scenario Tests for availability set of New-AzureRmVm

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-powershell#5424]
### Cmdlet(s)

- New-AzureRmVm

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by MiYanni** [comment]
@sergey-shandar Is this still in progress?

**Comment by markcowl** [comment]
Fixed.
