### ISSUE TITLE
StorageAccountTests.ps1 have Assert-AreEqual parameters switched

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5426]
The tests in StorageAccountTests.ps1 (in Commands.Management.Storage.Test) use Assert-AreEqual but the passed parameters are flipped. The command uses:
`Assert-AreEqual {expected} {actual}`
and all the calls to it in this file actually pass them as
`Assert-AreEqual {actual} {expected}`

This making investigating test failures more difficult and confusing to those who do not realize the parameters are flipped.

- [ ] The Assert-AreEqual calls in StorageAccountTests.ps1 present the parameters in the correct order

**Comment by blueww** [comment]
I will fix it when remove Enable/disableEncryptionService paramters, since I will refine the test case and record it when the change.

**Comment by MiYanni** [comment]
These changes have been merged in. Closing issue.
