### ISSUE TITLE
New-AzureRmVmss: BackeendPort is not used

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-powershell#5430]
### Cmdlet(s)

`New-AzureRmVmss`

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description

The parameter `BackendPort` is not used in simple parameter set of `New-AzureRmVmss`. The is an assignment

```c#
BackendPort = BackendPort ?? (isWindows ? new[] { 3389, 5985 } : new[] { 22 });
```

But it's not used after that.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by markcowl** [comment]
Fixed.
