### ISSUE TITLE
Unable to extract Azure Guest VM metrics

### ISSUE THREAD

**Issue by shivab90** [Azure/azure-powershell#5439]
Hi
I want to extract Azure Guest Os metrics using "Azure Monitor Poweshell.
I have enabled Diagnostics in azure portal.
I have configured guest agent (WAD/LAD) to collect performance counters to their storage account, I have tried the below command to retrieve the data

Get-AzureTableEntity -TableName $tableName -StorageAccountName $ComputerInventory_StorageAccountName -StorageAccountAccessKey $StorageAccountAccessKey -QueryString $querystring -ConvertDateTimeFields $true -GetAll $true -Verbose

Can anyone provide me the solution to resolve this below error.

ConvertFrom-JSON : Cannot convert the JSON string because a dictionary that was converted from the string contains the duplicated keys 'Timestamp' and 'TIMESTAMP'

Thanks

**Comment by markcowl** [comment]
@shivab90 I don't thinbk Get_AzureSTorageTableEntity is a cmdlet from Azure PowerShell.  Where does this cmdlet come form?

**Comment by shivab90** [comment]
Kindly refer the below link for your reference
https://www.verboon.info/2017/07/creating-and-managing-azure-storage-tables-with-powershell/

**Comment by markcowl** [comment]
@shivab90 It looks liek this issue is with the AzureTableEntity module referenced in this article.  Please file this issue there.
