### ISSUE TITLE
Investigate New Portal issues with Import-AzurePublishSettingsFile

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5446]
What doesn't work:
- Importing the publishsettings file using Powershell and executing the command "Get-AzureLocation" (repo steps below)
 
We have confirmed that the powershell scenario works when using the classic portal publishsettings.
 
What is strange though and what makes this complicated is that we have confirmed that the new current publishsettings DOES actually work for the powershell scenario, but for some reason in order for it to work you have to:
1.	Import the publish settings file which installs the certificate to your machine.
2.	Delete the certificate from your machine.
3.	Import the publish settings file for a 2nd time which will reinstall the certificate to your machine
4.	now the command 'Get-AzureLocation' will work

**Comment by maddieclayton** [comment]
Service team is fixing on their side - will reopen if fix is not successful.
