### ISSUE TITLE
Remove Commands.ServiceManagement.Common dependency for Commands.ScenarioTests.ResourceManager.Common

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5449]
Test projects that reference `Commands.ScenarioTests.ResourceManager.Common` also reference `Commands.ServiceManagement.Common`. The only scenarios that seemed to be covered are converting from an SM profile to an RM profile.
- [ ] Refactor `Commands.ScenarioTests.ResourceManager.Common` to no longer require `Commands.ServiceManagement.Common`
- [ ] Clean up all solutions that have `Commands.ServiceManagement.Common` referenced because of this dependency

![image](https://user-images.githubusercontent.com/17788297/35832225-52c7bdbc-0a81-11e8-92a5-f04465f49b89.png)

**Comment by MiYanni** [comment]
Keep this as a separate task that is part of: https://github.com/Azure/azure-powershell/issues/6129

**Comment by maddieclayton** [comment]
Done
