### ISSUE TITLE
RemoveAzureRmServiceBusRule removes namespace authorization rules instead of service bus rules

### ISSUE THREAD

**Issue by paterben** [Azure/azure-powershell#5450]
### Cmdlet(s)
RemoveAzureRmServiceBusRule

### PowerShell Version
5.1.16299.98

### Module Version
5.2.0

### OS Version
10.0.16299.98

### Description
RemoveAzureRmServiceBusRule removes namespace authorization rules instead of service bus rules. The issue seems to be in [RemoveAzureServiceBusRule.cs](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/ServiceBus/Commands.ServiceBus/Cmdlets/Rule/RemoveAzureServiceBusRule.cs)

**Comment by maddieclayton** [comment]
@v-Ajnava @sazeesha @dsouzaarun Can one of you take a look at this? This is a serious issue that should be fixed immediately.

**Comment by v-Ajnava** [comment]
@maddieclayton raise a PR with the fix

**Comment by maddieclayton** [comment]
Fixed

@paterben Thank you for bringing up this issue! You should see the fix in production by next Wednesday - please let us know if you find further issues.
