### ISSUE TITLE
Scenario test for New-AzureRmVm when domainnamelabel is not specified

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-powershell#5451]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by MiYanni** [comment]
@sergey-shandar How's this going?

**Comment by markcowl** [comment]
Fixed
