### ISSUE TITLE
Where is the Azure prefix?

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#547]
There is a bunch of cmdlets in AzureResourceManager module without the Azure prefix:
```
Get-AlertRule
Add-AlertRule 
Remove-AlertRule
Get-AlertHistory

Get-AutoscaleSetting
Add-AutoscaleSetting
Remove-AutoscaleSetting
Get-AutoscaleHistory
New-AutoscaleProfile 
New-AutoscaleRule 

Format-MetricsAsTable
Get-MetricDefinitions
Get-Metrics           
Get-UsageMetrics
Get-UsageAggregates
```

Also, the last four cmdlets use the plural noun. Recommended naming convention is Verb-SingularNoun.

**Comment by markcowl** [comment]
@alexandair Thanks for the report, forwarding to the appropriate team

**Comment by asheniam** [comment]
We are fixing these to include the standard "AzureRm" prefix.  It will be in the next PowerShell release

**Comment by asheniam** [comment]
This is already fixed
