### ISSUE TITLE
Cannot pull the azure-powershell latest container on Windows 2016

### ISSUE THREAD

**Issue by cblackuk** [Azure/azure-powershell#5475]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### Module Version
PS C:\Users\Administrator> docker version
Client:
 Version:      17.06.2-ee-6
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:46:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-6
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:55:16 2017
 OS/Arch:      windows/amd64
 Experimental: false

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
Name                           Value
----                           -----
PSVersion                      5.1.14393.1944
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1944
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Description

Cannot build azure-powershell latest container whilst 4.4.0 builds fine.

latest: Pulling from azuresdk/azure-powershell
92af55943fd6: Extracting [==================================================>]  1.617GB/1.617GB
f546a2c7ee3e: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilte
r\a9df8dbd15212221b0ccfd8a298b27b658741265b59f411d8d8194d5a0b2c403\UtilityVM: The system cannot find the path specified.

docker pull azuresdk/azure-powershell:5.2.0
5.2.0: Pulling from azuresdk/azure-powershell
92af55943fd6: Extracting [==================================================>]  1.617GB/1.617GB
f546a2c7ee3e: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\a4f6340befffb86401119903aba21d15c260fcacb962479d6dd770890e7f4904\UtilityVM: The system cannot find the path specified.

Old version works fine:

docker pull azuresdk/azure-powershell:4.4.0
4.4.0: Pulling from azuresdk/azure-powershell
3889bb8d808b: Already exists
da87b55a9b63: Pull complete
bd929f4d410c: Pull complete
d016cbecf9ea: Pull complete
eb2006788471: Pull complete
Digest: sha256:c40a47d5e93fafaa3f1dc8da545647e10485cdb9203eb1d1e85472f677a711a6
Status: Downloaded newer image for azuresdk/azure-powershell:4.4.0

### Script/Steps for Reproduction
docker pull azuresdk/azure-powershell
docker pull azuresdk/azure-powershell:5.2.0

**Comment by maddieclayton** [comment]
@twitchax Can you take a look?

**Comment by twitchax** [comment]
Hi @cblackuk, this seems to be an issue with the base Windows Server Core container image that I used.  I will fix these shortly.

**Comment by twitchax** [comment]
Hi @cblackuk, I just updated these images: can you verify they are fixed and close?

**Comment by cblackuk** [comment]
Hi @twitchax  I wish that fixed it... but sadly not ;-(

docker pull azuresdk/azure-powershell
Using default tag: latest
latest: Pulling from azuresdk/azure-powershell
5847a47b8593: Pull complete
9f887ccb8077: Pull complete
a2368a681731: Extracting [==================================================>]  43.49MB/43.49MB
failed to register layer: re-exec error: exit status 1: output: time="2018-02-10T00:09:07Z" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the file specified. (0x2) layerId=\\\\?\\C:\\ProgramData\\Docker\\windowsfilter\\e8e19f78d3ed39108259a9495bb7badc4470a39a1d13839adac2092fbe7f0f60 flavour=1 folder=C:\\Windows\\TEMP\\hcs46952772
3"
hcsshim::ImportLayer failed in Win32: The system cannot find the file specified. (0x2) layerId=\\?\C:\ProgramData\Docker\windowsfilter\e8e19f78d3ed39108259a9495bb7badc4470a39a1d13839adac2092fbe7f0f60 flavour=1 folder=C:\Windows\TEMP\hcs469527723

**Comment by twitchax** [comment]
@cblackuk, do you have the latest Windows 1709 update?

**Comment by cblackuk** [comment]
@twitchax  Nope
My OS  Version	10.0.14393 Build 14393
![image](https://user-images.githubusercontent.com/28607803/36060022-37309370-0e38-11e8-8e26-de6d836bfdfd.png)

**Comment by twitchax** [comment]
@cblackuk, ok, I reverted back to the older Windows Server Core images.  It should work now.  We will stay on them for a while.

**Comment by cblackuk** [comment]
It works now! Thanks for sorting! @twitchax
