### ISSUE TITLE
New-AzureRmIotHubExportDevices attempting to Import rather than Export and failing with 'InternalServerError'

### ISSUE THREAD

**Issue by darrenjrobinson** [Azure/azure-powershell#5490]
### Cmdlet(s)
New-AzureRmIotHubExportDevices

### PowerShell Version
PSVersion 5.1.16299.98 

### Module Version
Manifest   2.1.0      Azure
Script     4.0.2      Azure.Storage
Script     5.1.1      AzureRM                                                                                                                                            
Script     3.0.0      AzureRM.IoTHub                      
Script     4.1.1      AzureRM.Profile                                   
Script     5.1.1      AzureRM.Resources                   
Script     4.0.1      AzureRM.Storage  

### OS Version
BuildVersion                   10.0.16299.98

### Description
When using New-AzureRmIotHubExportDevices to export IoTDevices to a blob storage file and using -verbose the job fails with Internal Server Error.  Verbose output indicates the Export is trying to Import. 

### Debug Output
```
New-AzureRmIotHubExportDevices -ResourceGroupName $hub.Resourcegroup -Name $hub.Name -ExportBlobContainerUri "$($storageAccount.Context.StorageAccount.BlobStorageUri.PrimaryUri.AbsoluteUri)/$($storageSASToken)" -Verbose
DEBUG: 3:15:45 PM - NewAzureRmIotHubExportDevices begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 3:15:45 PM - using account id 'xxx@me.com'...
VERBOSE: Performing the operation "Import All Devices" on target "MxxxxxxxxIoTHub".
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxx@me.com', environment: 'AzureCloud', tenant: '833bb743-6d86-48ea-bc22-bc22a2f08c96'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/11/2018 04:15:45: 29d5fd2f-5bfe-4ebd-941e-d583b168feff - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/833bb743-6d86-48ea-bc22-bc22a2f08c96/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (4 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 02/11/2018 04:15:45: 29d5fd2f-5bfe-4ebd-941e-d583b168feff - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/11/2018 04:15:45: 29d5fd2f-5bfe-4ebd-941e-d583b168feff - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 02/11/2018 04:15:45: 29d5fd2f-5bfe-4ebd-941e-d583b168feff - TokenCache: 26.7244263483333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/11/2018 04:15:45: 29d5fd2f-5bfe-4ebd-941e-d583b168feff - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/11/2018 04:15:45: 29d5fd2f-5bfe-4ebd-941e-d583b168feff - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: su35Ku+gvIXkLqA8hPn872jxEGJQjjGKD1subDi3Dj8=
	Refresh Token Hash: 8243kzVya1mWn0fYtvN7KRkMK/M//xq+h4K3gLhbuTw=
	Expiration Time: 02/11/2018 04:42:29 +00:00
	User Hash: cyRjYhStxKAawdE2qiax3NegWCK86UHU2bA3KhdHsSU=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/11/2018 04:15:45:  - TokenCache: Serializing token cache with 4 items.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/11/2018 04:15:45: aed5f25c-1f90-4743-8056-4471a630abcb - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/833bb743-6d86-48ea-bc22-bc22a2f08c96/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (4 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 02/11/2018 04:15:45: aed5f25c-1f90-4743-8056-4471a630abcb - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/11/2018 04:15:45: aed5f25c-1f90-4743-8056-4471a630abcb - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 02/11/2018 04:15:45: aed5f25c-1f90-4743-8056-4471a630abcb - TokenCache: 26.7243595033333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/11/2018 04:15:45: aed5f25c-1f90-4743-8056-4471a630abcb - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/11/2018 04:15:45: aed5f25c-1f90-4743-8056-4471a630abcb - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: su35Ku+gvIXkLqA8hPn872jxEGJQjjGKD1subDi3Dj8=
	Refresh Token Hash: 8243kzVya1mWn0fYtvN7KRkMK/M//xq+h4K3gLhbuTw=
	Expiration Time: 02/11/2018 04:42:29 +00:00
	User Hash: cyRjYhStxKAawdE2qiax3NegWCK86UHU2bA3KhdHsSU=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/11/2018 04:15:45:  - TokenCache: Serializing token cache with 4 items.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/f6f77e80-1791-4ae7-ac64-fd7c41407f61/resourceGroups/MxxxxxxxxIoTHub/providers/Microsoft.Devices/IotHubs/MxxxxxxxxIoTHub/exportDev
ices?api-version=2017-01-19

Headers:
x-ms-client-request-id        : 56a09767-ce37-4376-b2a9-ae30dc0c4db0
accept-language               : en-US

Body:
{
  "ExportBlobContainerUri": "https://MxxxxxxxxIoTHub.blob.core.windows.net//?sv=2017-04-17&sr=b&sig=UUKlySxvrKU5f2tYYfjEdFoO02rSanVUUty0j5u9Sh4%3D&se=2018-02-11T05%3A13%3A
57Z&sp=rwd",
  "ExcludeKeys": false
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
InternalServerError

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : service
x-ms-ratelimit-remaining-subscription-writes: 1197
x-ms-request-id               : 572f4e41-3861-4465-aa07-134167060e03
x-ms-correlation-request-id   : 572f4e41-3861-4465-aa07-134167060e03
x-ms-routing-request-id       : AUSTRALIAEAST:20180211T041606Z:572f4e41-3861-4465-aa07-134167060e03
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Connection                    : close
Cache-Control                 : no-cache
Date                          : Sun, 11 Feb 2018 04:16:06 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "Code": "InternalError",
  "HttpStatusCode": "InternalServerError",
  "Message": "Internal Error. If you contact a support representative please include this correlation identifier: f86fad6a-31c7-4ad3-aa53-9559990de65b, timestamp: 2018-02
-11 04:16:06Z, errorcode: IH500019."
}


New-AzureRmIotHubExportDevices : Operation returned an invalid status code 'InternalServerError'
At line:1 char:5
+     New-AzureRmIotHubExportDevices -ResourceGroupName $hub.Resourcegr ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmIotHubExportDevices], ErrorDetailsException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.IotHub.NewAzureRmIotHubExportDevices
 
DEBUG: AzureQoSEvent: CommandName - New-AzureRmIotHubExportDevices; IsSuccess - False; Duration - 00:00:24.1194261; Exception - Microsoft.Azure.Management.IotHub.Models.E
rrorDetailsException: Operation returned an invalid status code 'InternalServerError'
   at Microsoft.Azure.Management.IotHub.IotHubResourceOperations.<ExportDevicesWithHttpMessagesAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.IotHub.IotHubResourceOperationsExtensions.<ExportDevicesAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.IotHub.IotHubResourceOperationsExtensions.ExportDevices(IIotHubResourceOperations operations, String resourceGroupName, String resourceNa
me, ExportDevicesRequest exportDevicesParameters)
   at Microsoft.Azure.Commands.Management.IotHub.NewAzureRmIotHubExportDevices.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 3:16:10 PM - NewAzureRmIotHubExportDevices end processing.
DEBUG: 3:16:10 PM - NewAzureRmIotHubExportDevices end processing.
```

### Script/Steps for Reproduction

$DebugPreference="Continue"
Import-Module Azure

Login-AzureRmAccount 
Get-AzureRMSubscription | Get-AzureRMSubscription -SubscriptionName $_.SubscriptionName

# Get all Resource Groups in Subscription
$ResourceGroups = Get-AzureRmResourceGroup 
$IoTHubs = @()

# Find the RG's with IoT Hubs
foreach ($RG in $ResourceGroups){
    try {
        $IoTHub = Get-AzureRmIotHub -ResourceGroupName $RG.ResourceGroupName 
        $IoTHub
        $IoTHubs += $IoTHub
    }
    catch {
        write-host "Something barfed enumerating IoT Hub(s) in Resource Group $($RG.ResourceGroupName)"     
    }
}

# Enmerate the IoT Hubs to export the IoT Devices
$IoTKeyName = "iothubowner"
$IoTDevices = @()
ForEach($hub in $IoTHubs) {
    $hubKey = Get-AzureRmIotHubKey -ResourceGroupName $hub.Resourcegroup -Name $hub.Name -KeyName $IoTKeyName 
    
    # IoT ConnectionString
    $IoTConnectionString  = "HostName=$($hub.Name).azure-devices.net;SharedAccessKeyName=$($IoTKeyName);SharedAccessKey=$($hubKey.PrimaryKey)"
    
    $registry = Get-AzureRmIotHubRegistryStatistic -ResourceGroupName $hub.Resourcegroup -Name $hub.Name 
    
    # Get/Create a Storage Account to Export Devices to
    try {
        # Get Storage Account Details
        $storageAccount = Get-AzureRmStorageAccount -ResourceGroupName $hub.Resourcegroup -Name "$($hub.Name)" 
        $storageAccountCTX = $storageAccount.Context        
        $storageAccountKey = (Get-AzureRmStorageAccountKey -ResourceGroupName $hub.Resourcegroup -Name $storageAccount.StorageAccountName).Value[0]
        $storageContainer = Get-AzureStorageContainer -Name "$($hub.Name.ToLower())" -Context $storageAccountCTX 
        $storageSASToken = $storageAccountCTX | New-AzureStorageBlobSASToken -Container $storageContainer -Blob "blob$($hub.name)" -Permission rwd
        # Create Local file and upload to Storage Account 
        $localfile = New-Item -Path . -Name "$($hub.Resourcegroup)-devices.txt" -ItemType "file" -Force 
        $blob = $storageAccountCTX | Set-AzureStorageBlobContent -Container $storageContainer.Name -Blob $hub.Resourcegroup -File "$($hub.Resourcegroup)-devices.txt" -Force  

    } catch {
        # Create New Storage Account and Setup
        $storageAccount = New-AzureRmStorageAccount -ResourceGroupName $hub.Resourcegroup -AccountName "$($hub.Name.ToLower())" -Location $hub.Location -SkuName "Standard_GRS" 
        $storageAccountCTX = $storageAccount.Context
        $storageAccountKey = (Get-AzureRmStorageAccountKey -ResourceGroupName $hub.Resourcegroup -Name $storageAccount.StorageAccountName).Value[0]
        $storageContainer = New-AzureStorageContainer -Name "$($hub.Name.ToLower())" -Permission Container -Context $storageAccountCTX         
        $storageSASToken = $storageAccountCTX | New-AzureStorageBlobSASToken -Container $storageContainer -Blob "blob$($hub.name)" -Permission rwd
        # Create Local file and upload to Storage Account 
        $localfile = New-Item -Path . -Name "$($hub.Resourcegroup)-devices.txt" -ItemType "file" -Force 
        $blob = $storageAccountCTX | Set-AzureStorageBlobContent -Container $storageContainer.Name -Blob $hub.Resourcegroup -File "$($hub.Resourcegroup)-devices.txt" -Force  
        
    }
    
 
    # Export IOT Devices
    New-AzureRmIotHubExportDevices -ResourceGroupName $hub.Resourcegroup -Name $hub.Name -ExportBlobContainerUri "$($storageAccount.Context.StorageAccount.BlobStorageUri.PrimaryUri.AbsoluteUri)/$($storageSASToken)" -Verbose 
}

**Comment by cormacpayne** [comment]
@rkmanda Hey Roopesh, would you mind taking a look at this issue?

**Comment by darrenjrobinson** [comment]
Any updates/progress/insight you can provide on this @rkmanda @cormacpayne

**Comment by markrad** [comment]
Hi @darrenjrobinson, 

This may not be your issue but I came across this page while researching the same error message. It appears that the documentation page for New-AzureRmIotHubExportDevices is inaccurate. In the example it provides it does not specify the blob name in the -ExportBlobContainerUri parameter. When one uses a storage account you need to create the blob first and then include it as part of the URI before the question mark. Failure to do this will generate the same log you shared above. For example:

```
-ExportBlobContainerUri "https://<containername>.core.windows.net/<blobname>?sv=2017-07-29...
```
Note the value **\<blobname>** added to the URI. I had assumed it was going to create the blob in the container but that is not the case.

_Mark Radbourne MSFT_

**Comment by darrenjrobinson** [comment]
Thx Mark. I was creating the blob, but not referencing it in the ExportBlogContainerUri.
I've tried that and it gets a little future but still fails with 
New-AzureRmIotHubExportDevices : Operation returned an invalid status code 'InternalServerError' 

I'll do some more digging/testing.

**Comment by darrenjrobinson** [comment]
I ended up getting this working.
I wrote it up here, hoping it will help others trying to use this cmdlet. 
https://blog.darrenjrobinson.com/exporting-iot-device-information-from-azure-iot-hubs-using-powershell/
