### ISSUE TITLE
Create VM Image for partners

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5498]
### Description
- [x] Create VM Image with all necessary tools for Azure Posh development
- [x] Verify build, test run, and test recording
- [ ] Add use of the image to development docs, make image available for universal download and liunk from README

###Cost: 4

**Comment by vladimir-shcherbakov** [comment]
https://github.com/Azure/azure-powershell/pull/5922

**Comment by maddieclayton** [comment]
Done.
