### ISSUE TITLE
Fix issue with AsJob support for VMRunCommand

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5502]
### Description
VM Run command does noit work with AsJob, as the SessionState is not filled out for the cmdlet, which prevents the user from suign the SessioNState to resolve path arguments

- [ ] Verify SessioNState cannot be copied in Job implementation
- [ ] Create common code for resolving PS paths that can be adapted so it will work when runnign synchronpously or in  ajob (most likely this involves capturing important data from the session state in the job and providing an adapter
- [ ] Find usages of SessioNState in cmdlets and update to using new common code.

### Cost: 6

**Comment by v-tisheg** [comment]
Has this been mitigated?  My customer is still unable to invoke the command with the AsJob parameter.

**Comment by markcowl** [comment]
Closing as duplicate of #5896 which has the general solution for this
