### ISSUE TITLE
-ConnectionFieldName parameter for Set-AzureAutomationConnectionFieldValue is case sensitive

### ISSUE THREAD

**Issue by SherifTalaat** [Azure/azure-powershell#551]
The -ConnectionFieldName parameter for Set-AzureAutomationConnectionFieldValue cmdlet is case sensitive otherwise it will show the following error.
"Set-AzureAutomationConnectionFieldValue : The connection field name was not found for connection name: <Connection_Asset_Name>".
The value for this parameter should match the output of the following code
(Get-AzureAutomationConnection -AutomationAccountName <Automation_Account_Name> -Name <Connection_Asset_Name>).FieldDefinitionValues 

![6-30-2015 12-11-26 am](https://cloud.githubusercontent.com/assets/10003326/8419768/b35c5966-1ebc-11e5-903f-4e492295e015.png)

I don't think this is the right behavior especially that some of Azure PowerShell cmdlets requires using lowercase characters. Also, the documentation didn't mention anything regarding this case sensitivity.

Regards,
Sherif Talaat
PowerShell MVP

**Comment by markcowl** [comment]
@SherifTalaat Thanks for the report, forwarding to the automation team for investigation

**Comment by jodoglevy** [comment]
@SherifTalaat thanks for reporting this issue, I have filed an internal bug for it.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
