### ISSUE TITLE
Install PowerShellGet 1.6.0 on all CI machines

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5513]
### Description

- [x] Ensure PowerShellGet 1.6.0 is installed on all PowerShell and PowerShell50 workers
  - [x] Ensure that PackageManagement is also installed
  - [x] Install for both 32-bit and 64-bit powershell
  - [x] Verify using import-Module and running Find-Module on a known module

### Cost: 1

**Comment by MiYanni** [comment]
Completed.
