### ISSUE TITLE
Wiki https://github.com/Azure/azure-powershell/wiki/Storage-Blob-Service-Default-Service-Version Is not correct

### ISSUE THREAD

**Issue by xqiu** [Azure/azure-powershell#5517]
### Description
The following wiki's information seems incorrect as the links points to non-existing pages and the Cmdlet does not exist in the current Azure PS module.
https://github.com/Azure/azure-powershell/wiki/Storage-Blob-Service-Default-Service-Version

**Comment by blueww** [comment]
The  design in the doc is changed in the review. 
I have updated it to be align with current implementation. 

@markcowl , @cormacpayne , please help to confirm if we should open the design doc to public? And the process to open it? Thanks!

**Comment by maddieclayton** [comment]
@blueww All design reviews should be in the private powershell repo (and now in the private cmdlet review repo).  I will close this issue, can you move the doc over to private?

**Comment by cormacpayne** [comment]
@blueww new cmdlet repo is here: https://github.com/Azure/azure-powershell-cmdlet-review-pr

**Comment by blueww** [comment]
Actually, the updated design is already in https://github.com/Azure/azure-powershell-pr/wiki/Storage-Blob-Service-Default-Service-Version long ago.

I have deleted the out of date design in the public repo: https://github.com/Azure/azure-powershell/wiki/Storage-Blob-Service-Default-Service-Version
