### ISSUE TITLE
Get-AzureRMRouteTable does not work as a pipeline command

### ISSUE THREAD

**Issue by ChristopherGLewis** [Azure/azure-powershell#5518]
### PowerShell Version
PSVersion                      5.1.16299.98                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                  
BuildVersion                   10.0.16299.98                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                          
WSManStackVersion              3.0                                                                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                                                                      
SerializationVersion           1.1.0.1  

### Module Version
get-module AzureRM.Network

ModuleType Version    Name                                ExportedCommands                                                                                                              
---------- -------    ----                                ----------------                                                                                                              
Manifest   5.0.0      AzureRM.Network                     {Add-AzureRmApplicationGatewayAuthenticationCertificate, Add-AzureRmApplicationGatewayBackendAddressPool, Add-AzureRmApplic...

### OS Version
Windows 10

### Description
I don't think Get-AzureRMRouteTable works as a pipeline command...

### Script/Steps for Reproduction
I don't think Get-AzureRMRouteTable works as a pipeline command...

 > Get-AzureRMRouteTable -ResourceGroupName  "MyRG" | foreach-object { $_.Name + "---"} 

Does not return 
```
Route1---
Route2---
Route3---
```

It returns 
```
Route1
Route2
Route3
---
```

**Comment by ChristopherGLewis** [comment]
Even worse, this works
```
$allRoutes = Get-AzureRMRouteTable -ResourceGroupName "MyRG"
$AllRoutes | foreach-object { $_.Name + "---"}
Route1---
Route2---
Route3---
```

**Comment by MiYanni** [comment]
@DeepakRajendranMsft Can you take a look at this?

**Comment by cormacpayne** [comment]
@EvgenyAgafonchikov would you mind taking a look at this issue?
