### ISSUE TITLE
Remove-AzureAutomationModule doesn't remove Connection Type

### ISSUE THREAD

**Issue by SherifTalaat** [Azure/azure-powershell#552]
When you run the New-AzureAutomationModule cmdlet to import a module to Azure automation, It will extract the activities and connection type (if any) for that module. But, when you run Remove-AzureAutomationModule cmdlet, it removes only the activities and keep the connection type as it. The connection type with out the module is useless and it should be deleted too as part of the removal process. 

Regards,
Sherif Talaat
PowerShell MVP

**Comment by markcowl** [comment]
@SherifTalaat Thank you for the report, assigning to the Automation team for investigation

**Comment by jodoglevy** [comment]
Connection types as not useless without modules, although modules are our main reason for them. We are adding a Remove-AzureAutomationConnectionType cmdlet to the ASM and ARM modules in the next release that will allow you to remove connection types if you don't want them anymore.
