### ISSUE TITLE
Missing description parameter on New-AzureRmAdAppCredential cmdlet

### ISSUE THREAD

**Issue by laughtonsm** [Azure/azure-powershell#5530]
Hi.

I am creating password credentials on an existing SPN, and any credentials that are created using the New-AzureRmAdAppCredential are created using a description of 'Key Description'.  It would be useful to have a -description swithc to at least populate this.

Cheers

Shaun

**Comment by MiYanni** [comment]
@darshanhs90 Can you take a look at this?

**Comment by cormacpayne** [comment]
@darshanhs90 do you know if this is information we can send to the server? Right now, the `PasswordCredentialsUpdateParameters` object that we send (and the corresponding `PasswordCredential` object it contains) does not contain a property for `Description`.

**Comment by grlin** [comment]
Hi, I'm not sure I understand where the Description field comes from, and what command you're trying to populate a description for.

**Comment by brent-robinson** [comment]
This is an issue in the `Az` module's `New-AzADAppCredential` too.

When listing keys in the Azure Portal, there is a `Description` column. This can be set when creating a key from the Azure Portal or from the `AzureAD` PowerShell module.

![image](https://user-images.githubusercontent.com/6666613/54500371-6586ab00-4970-11e9-9314-aeed114243be.png)

The [`AzureAD` PowerShell Module has the `CustomKeyIdentifier` option to set the description](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadapplicationpasswordcredential?view=azureadps-2.0), but unfortunately the `AzureAD` module isn't cross platform.

The `az` CLI has limited support for the description field - [only when updating a credential](https://docs.microsoft.com/en-us/cli/azure/ad/app/credential?view=azure-cli-latest#az-ad-app-credential-reset). It doesn't seem to support creating a credential after application creation.

**Comment by brent-robinson** [comment]
Looks like `customKeyIdentifier` is a field in the **beta** [Microsoft Graph API](https://docs.microsoft.com/en-us/graph/api/resources/passwordcredential?view=graph-rest-beta) (application support doesn't exist in 1.0). It also exists in the old [Azure AD Graph API](https://docs.microsoft.com/en-au/previous-versions/azure/ad/graph/api/entity-and-complex-type-reference#passwordcredential-type). It's a binary field, but displays as text in the Azure portal.

**Comment by cormacpayne** [comment]
I believe this issue will be resolved at the same time as [this issue](https://github.com/Azure/azure-powershell/issues/9116). I'm going to close this issue in favor of the one linked previously and we will track the necessary work and status there. Please let me know if this isn't the case and I will re-open this issue.
