### ISSUE TITLE
-JobType parameter is required for Remove-AzureWebsiteJob

### ISSUE THREAD

**Issue by SherifTalaat** [Azure/azure-powershell#554]
When you try to remove Azure Website Job using the Remove-AzureWebsiteJob cmdlet, you will have to provide -Name (Website Name), -JobName, and -JobType. The first two parameters make sense but the -JobType parameter doesn't make any sense to be required parameter especially we cannot use the same name for multiple webjobs even if the job type is different. I think the right behavior is removing this parameter as it's unnecessary and not adding any value.

![6-30-2015 12-45-21 am](https://cloud.githubusercontent.com/assets/10003326/8420311/554dce72-1ec1-11e5-83a8-0c589cc57eb1.png)

Regards,
Sherif Talaat
PowerShell MVP

**Comment by markcowl** [comment]
@SherifTalaat Thank you for the report, assigning to the automation team for investigation

**Comment by jodoglevy** [comment]
This is an Azure Websites issue, not an Azure Automation issue, changing labels.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
