### ISSUE TITLE
Get-AzureRMResource does not support paging

### ISSUE THREAD

**Issue by kwill-MSFT** [Azure/azure-powershell#5551]
### Description

-Top parameter should restrict the number of items returned, but it does not.  All items matching the filter are returned.

### Script/Steps for Reproduction

```powershell
$resources = Find-AzureRmResource -Top 2
$resources.Count
105
```

### Module Version

```powershell
Get-Module -Name AzureRM.Resources -ListAvailable


    Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.3.0      AzureRM.Resources                   {Get-AzureRmProviderOperation, Remove-AzureRmRoleAssignmen...
```

### Environment Data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by MiYanni** [comment]
@ravbhatnagar @vivsriaus Can you guys take a look? If we don't have tests for `-Top`, this would be a good opportunity to add some.

**Comment by cormacpayne** [comment]
@Tiano2017 the classes to allow for easy paging using the `List` and `ListNext` calls for a resource are found [here](https://github.com/Azure/azure-powershell/tree/preview/src/ResourceManager/Common/Commands.ResourceManager.Common/Paging) (an example of it being used to list service principals found [here](https://github.com/Azure/azure-powershell/blob/preview/src/Common/Commands.Common.Graph.RBAC/ActiveDirectory/ActiveDirectoryClient.cs#L108-L115)). I can look into supporting this feature in the future.

**Comment by cormacpayne** [comment]
This functionality will be added when the cmdlets are [generated using AutoRest](https://devblogs.microsoft.com/powershell/cmdlets-via-autorest/) later this year.
