### ISSUE TITLE
New-AzureReservedIP no longer working with Powershell 0.9.4

### ISSUE THREAD

**Issue by Kofl** [Azure/azure-powershell#558]
Error:

New-AzureReservedIP : Method not found: 'Void
Microsoft.WindowsAzure.Management.Network.Models.NetworkReservedIPCreateParameters.set_VirtualIPName(System.String)'.
At line:1 char:1
+ New-AzureReservedIP -ReservedIPName "MyServer1IP" -Label "Server1IP" -Location " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureReservedIP], MissingMethodException
 + FullyQualifiedErrorId : System.MissingMethodException,Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.New
   AzureReservedIPCmdlet	

for details, please see:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/c9a5bc8d-b589-4473-8002-096933076e5e/trying-to-reserve-ip-but-keep-on-getting-errors?forum=windowsazuredevelopment&prof=required

**Comment by DeepakRajendranMsft** [comment]
this has been resolved
