### ISSUE TITLE
Feature: True-up Property Names and Cmdlet Parameter Names

### ISSUE THREAD

**Issue by aydeisen** [Azure/azure-powershell#5583]
Is it possible to make the cmdlet parameter names and object property names a bit more consistent to allow for better 'ValueFromPipelineByPropertyName' handling?

Two examples:

1. Executing `Get-AzureRmAutomationDscNode | Get-AzureRmAutomationDscNodeReport` fails because `Get-AzureRmAutomationDscNodeReport` contains the parameter `NodeId`, but the `Microsoft.Azure.Commands.Automation.Model.DscNode` object returned by `Get-AzureRmAutomationDscNode` returns the data in the `Id` property

2. Executing `Get-AzureRMVM | Get-AzureRMVMExtension` fails because `Get-AzureRMVMExtension` contains the parameter `VMName`, but the `Microsoft.Azure.Commands.Compute.Models.PSVirtualMachine` object returned by `Get-AzureRMVM` return the data in the `Name` parameter.

I understand that this has a high level of effort, and would require some breaking changes, but it would help dramatically in streamlining PowerShell executions using the AzureRM PowerShell Module.

**Comment by cormacpayne** [comment]
@aydeisen thanks a lot for the request! We are definitely looking at ways to improve the piping scenarios in the Azure PowerShell cmdlets -- for example, new cmdlets need to implement the `InputObject` ("ValueFromPipeline") and `ResourceId` ("ValueFromPipelineByPropertyName") piping scenarios (which you can read more about [here](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/piping-in-powershell.md#azure-powershell-piping-scenarios)). In the future, we are looking to have _all_ cmdlets follow these guidelines, as well as other piping scenarios that we find valuable between cmdlets.

In the meantime, we can contact the appropriate partner teams to take a look at the cmdlets you mentioned above and see if there's a way to enable the desired piping scenarios without causing any breaking changes (and if there are breaking changes, we can look to implement them in the next upcoming breaking change release).

CC: @vrdmr @hyonholee

**Comment by cormacpayne** [comment]
@vrdmr @hyonholee hey guys, we should look at supporting the above piping scenarios, as well as any other scenarios that make sense for users across your set of cmdlets. We can look at ways of immediately implementing this without a breaking change, and if there's no way to do so, we can make the necessary changes in May.

**Comment by markcowl** [comment]
Clsoing ans s this should be hanlded by design for generated cmdlets with ResourceId type conversion
