### ISSUE TITLE
Get-AzureKeyVaultSecret does not return secret without -Name

### ISSUE THREAD

**Issue by arcotek-ltd** [Azure/azure-powershell#5586]
### Description

`Get-AzureKeyVaultSecret` does not return the `SecretValue` or `SecretValueText` properties, unless a secret is specified via the `-Name` parameter.

The user, which is actually the service principal, has full access to the keyvault:

- Key permissions: 16 selected
- Secret permissions: 8 selected
- Certificate permissions: 14 selected

### Script/Steps for Reproduction

```powershell
$KeyVaultName = "myKeyVault"
$Secrets = Get-AzureKeyVaultSecret -VaultName $KeyVaultName
$Secrets.count
#6
$Secrets[1] | Get-Member -MemberType Property -force
```
Returns:

```
   TypeName: Microsoft.Azure.Commands.KeyVault.Models.SecretIdentityItem

Name        MemberType Definition                                    
----        ---------- ----------                                    
ContentType Property   string ContentType {get;set;}                 
Created     Property   System.Nullable[datetime] Created {get;}      
Enabled     Property   System.Nullable[bool] Enabled {get;set;}      
Expires     Property   System.Nullable[datetime] Expires {get;set;}  
Id          Property   string Id {get;set;}                          
Name        Property   string Name {get;set;}                        
NotBefore   Property   System.Nullable[datetime] NotBefore {get;set;}
Tags        Property   hashtable Tags {get;set;}                     
TagsTable   Property   string TagsTable {get;}                       
Updated     Property   System.Nullable[datetime] Updated {get;}      
VaultName   Property   string VaultName {get;set;}                   
Version     Property   string Version {get;set;}  
```

**Whereas:**

```
$Secret = Get-AzureKeyVaultSecret -VaultName $KeyVaultName -Name "aSecretName"

$Secret | Get-Member -MemberType Property -force
```
Returns:

```
Name            MemberType Definition                                                                     
----            ---------- ----------                                                                     
Attributes      Property   Microsoft.Azure.Commands.KeyVault.Models.SecretAttributes Attributes {get;set;}
Id              Property   string Id {get;set;}                                                           
Name            Property   string Name {get;set;}                                                         
SecretValue     Property   securestring SecretValue {get;set;}                                            
SecretValueText Property   string SecretValueText {get;}                                                  
VaultName       Property   string VaultName {get;set;}                                                    
Version         Property   string Version {get;set;}      
```
If my theory is correct, not that I can find anything to support it, this is by design. But why? Is it someone making overzealous security decisions? I can simply create a `foreach` loop containing `Get-AzureKeyVaultSecret -Name $_` to do the same thing, however, I don't want to do a foreach loop as accessing KeyVault is slow, so making one call to get all the secrets into one variable make sense.

### Module Version

```powershell
PS C:\> Get-Module -Name AzureRM -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                                                                 
---------- -------    ----                                ----------------                                                                                                                                                 
Script     5.3.0      AzureRM

PS C:\> Get-Command Get-AzureKeyVaultSecret

CommandType     Name                                               Version    Source                                                                                                                                       
-----------     ----                                               -------    ------                                                                                                                                       
Cmdlet          Get-AzureKeyVaultSecret                            4.1.1      AzureRM.KeyVault     

```

### Environment Data

```Name                           Value                                                                                                                                                                                       
----                           -----                                                                                                                                                                                       
PSVersion                      5.1.14409.1012                                                                                                                                                                              
PSEdition                      Desktop                                                                                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                     
BuildVersion                   10.0.14409.1012                                                                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                                                                             
WSManStackVersion              3.0                                                                                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                                                                                         
SerializationVersion           1.1.0.1   
```

### Debug Output

Sorry, don't have time to redact confidential information. Let me know when you add a `-Redact` or `-Normalise` switch :-).

**Comment by cormacpayne** [comment]
@RandalliLama Hey Rich, do you know if the KeyVault API supports returning the secret value (and text) for a List in addition to a Get?

CC: @maddieclayton

**Comment by RandalliLama** [comment]
@cormacpayne @arcotek-ltd  It does not.  I am trying to dig up the reason for that, but I suspect that it has something to do with the fact that there can be many versions of a secret that might be returned and for security reasons it makes sense to ensure that only those secret versions that are required are returned.

**Comment by arcotek-ltd** [comment]
@RandalliLama,
Thanks for your response. It looks like my theory is correct and it is a security 'concern'. 

One can use `-Version` or `-IncludeVersions` parameters to retrieve a given version or in a loop, `where-object{$_version -eq "xyz"}

Therefore, I don't understand the logic:

> there can be many versions of a secret that might be returned and for security reasons it makes sense to ensure that only those secret versions that are required are returned

Would you prefer me to make this a feature request (that will be lost and ignored :-) )?

**Comment by RandalliLama** [comment]
@arcotek-ltd So, there is another performance related reason.  All secrets are encrypted, and to return them they need to be decrypted.  Further, Key Vault doesn't track version ordering.  So, as the service is currently implemented it would be very costly to return the secret values along with the list.

**Comment by arcotek-ltd** [comment]
@RandalliLama,
What do you mean by cost? Resource or monetary? For whom? Again, I can do this in a loop - which is "costly" - in time mainly. It would make far more sense to be able to return the whole object (or part thereof) in the `being{}` section or a foreach collection once, then iterate over that rather than having to make calls to the API each time? 

I haven't experienced multiple versions being returned. Only the latest.

Thanks

**Comment by RandalliLama** [comment]
@arcotek-ltd All secrets held by Key Vault are individually encrypted.  Every time the Key Vault service needs to return a secret it must decrypt it first.  This is a significant bottleneck and is the cost/performance issue that I am referring to above.

**Comment by arcotek-ltd** [comment]
A note to readers. Although this has been closed by MS, it hasn't been resolved. MS seem unwilling to consider it as a bug or feature request.

In my mind, the decryption logic is moved resulting in the same number of API calls to decrypt secrets and therefore the same "cost", however, moving the decryption process into the loop logic means that the API has to initiate from scratch for each secret that is to be decrypted, therefore _increasing_ not only resource / performance "cost", but time "cost" too.

**Comment by danielearwicker** [comment]
@arcotek-ltd Indeed. Apps that call the `AddAzureKeyVault` extension method to add a whole key vault to their configuration effectively do this every time they start up (or have to reload config):

```
for (var secrets = await keyVault.GetSecretsAsync(keyVaultUri);
    secrets != null;
    secrets = secrets.NextPageLink != null
        ? await keyVault.GetSecretsNextAsync(secrets.NextPageLink)
        : null)
{
    foreach (var secret in secrets)
    {
        var value = (await keyVault.GetSecretAsync(keyVaultUri, secret.Identifier.Name))?.Value;

        // now we have secret.Identifier.Name and value!
    }
}
```

It's basically a flood of round-trips.

It seems if you have more than a handful of secrets then you should store them in some other secure storage system, and put the password to that system in key vault.

Or else put all of them in a JSON object and store in a single secret (up to the maximum size which is 25K). But then if you change one property, you require a new version of the whole combined secret...

**Comment by mattduguid** [comment]
We have ~250 secrets per keyvault across ~13 environments, yes we do need all of them and keyvault is the selected storage choice for the company I work for, yes its extremely painful waiting for the secrets to download to our app reminds me of dial up modem days, can you please provide a method to GettAllSecrets() for current version or secrets that have a name that matches a filter and bring us back from the dark ages :)
