### ISSUE TITLE
Get-AzureRmSqlServer does not return fullyQualifiedDomainName

### ISSUE THREAD

**Issue by totkeks** [Azure/azure-powershell#5587]
### Description

When running the Get-AzureRmSqlServer command like this
```
Get-AzureRmSqlServer -Name my-server -ResourceGroupName my-resource-group
```

I get the following result:
```
ResourceGroupName        : my-resource-group
ServerName               : my-server
Location                 : my-location
SqlAdministratorLogin    : my-login
SqlAdministratorPassword :
ServerVersion            : 12.0
Tags                     :
Identity                 :
```

But when looking at the Azure Resource Manager (https://resources.azure.com/) then there is another property in the return values:
```
"fullyQualifiedDomainName": "my-server.database.windows.net"
```

It seems the value is missing in the ```Microsoft.Azure.Commands.Sql.Server.Model.AzureSqlServerModel```.

Would be really helpful to have this value instead of hardcoding (and assuming, though probably it will not change) the ```.database.windows.net``` part.

**Comment by cormacpayne** [comment]
@akromm @jaredmoo Hey guys, do you know if it's possible for the API call to return this property?

**Comment by jaredmoo** [comment]
This is easily fixed, I have sent a PR to address this. Thank you for the feedback!

For what it's worth, the suffix can also be found by running `(Get-AzureRmEnvironment -Name AzureCloud).SqlDatabaseDnsSuffix` .
