### ISSUE TITLE
ARM: Add a switch to get just top level resources when calling Get-AzureResource

### ISSUE THREAD

**Issue by vivsriaus** [Azure/azure-powershell#559]
something like Get-AzureResource -GetTopLevel | Move-AzureResource ...

would be helpful when moving just the top level resources like Microsoft.Sql/servers instead of including /servers/databases as well.

**Comment by ravbhatnagar** [comment]
Do we want to support the scenario of moving just the top level resources?

**Comment by ravbhatnagar** [comment]
Haven't heard this request from the customers. Closing this for now. Feel free to re-open if you feel otherwise.
