### ISSUE TITLE
webapp:Document setup for Ase and Traffic Manager WebApp Tests

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5594]
### Description

These tests involve creating a resource out of band before test setup, and do not provide any information on the configuration of the resource:

These two require a pre-created app service environment:
TestCreateNewWebAppSlotOnAse
TestCreateNewWebAppOnAse

This one requires a pre-created Traffic Manager Profile:
TestCloneNewWebAppWithNewTrafficManager

We either need to (1) Make setup part of test setup, or, if this is not possible, (2) document the necessary setup in comments on the test.

**Comment by MiYanni** [comment]
@markcowl Recommended that we add a README.md to [Websites](https://github.com/Azure/azure-powershell/tree/preview/src/ResourceManager/Websites) similar to that found in [Network](https://github.com/Azure/azure-powershell/tree/preview/src/ResourceManager/Network) to cover the set setup required.

**Comment by vladimir-shcherbakov** [comment]
the same for **Test-CreateNewAppServicePlanInAse**

**Comment by markcowl** [comment]
At this point, I think thsi is never ging to happen, so the AppService team can just deal with the maintenace problems if they don't want to fix it.
