### ISSUE TITLE
Bug || VmwareToAzure ||Get-AzureRmRecoveryServicesAsrReplicationProtectedItem not capturing resyncProgressPercentage

### ISSUE THREAD

**Issue by shubhamgupta514** [Azure/azure-powershell#5612]
@viverm  @markcowl  
Get-AzureRmRecoveryServicesAsrReplicationProtectedItem is not capturing resyncProgressPercentage but as I checked the api it is providing that information in the providerSpecificDetails.
Please look into it.

**Comment by maddieclayton** [comment]
@viverm Can you take a look at this issue?

**Comment by shubhamgupta514** [comment]
@viverm - Is there any update on this??

**Comment by viverm** [comment]
@shubhamgupta514  Working on it . Will make this available soon in returned protected Item to track resync percentage.

**Comment by shubhamgupta514** [comment]
@viverm  Could you Please also add vCenterInfrastructureId in providerSpecificDetails for Get-AzureRmRecoveryServicesAsrProtectableItem cmdlet.

And infrastructureId in properties for Get-AzureRmRecoveryServicesAsrvCenter cmdlet.
I need them to filter out the Protectable items on basis of  different vcentera in single asrfabric.

If possible,Can you add this functionality of filtering the protectable items on the basis of vcenter friendlyName in Get-AzureRmRecoveryServicesAsrProtectableItem ?

The functionality is offered by Azure portal but Get-AzureRmRecoveryServicesAsrProtectableItem does not have any such functionality to take vcenter friendly name as a parameter and filter out the protectable item.

The use case is when we have two protectable items with same friendly name.The only way to choose the correct item is to select the right vcenter.

Thanks,
Shubham Gupta

**Comment by viverm** [comment]
Changes added in powershell response
