### ISSUE TITLE
Query||Azure Site Recovery|| VmwareToAzure||Disable replication and remove Option For ProtectedItem

### ISSUE THREAD

**Issue by shubhamgupta514** [Azure/azure-powershell#5613]
@viverm  @markcowl  

If I am using "Disable replication and remove" Option For ProtectedItem without performing any failover , then it is not cleaning up the staging container in the storage account automatically.Is this an expected behaviour or Azure site recovery will perform the cleanup for that blob after a certain time lapse ?

**Comment by shubhamgupta514** [comment]
@viverm Is there any update on this?

**Comment by viverm** [comment]
"Disable replication and remove" removes Replication protected Item nothing more.
I think you are asking here is if disable/remove Vm is last vm using container and storage account it should clean the blob it is creating during replication ? 

It is bydesign.
Adding @bsiva

**Comment by shubhamgupta514** [comment]
@viverm @bsiva yes, I am asking about the storage

**Comment by shubhamgupta514** [comment]
@viverm @bsiva  - Is there any update on this?

**Comment by bsiva** [comment]
Hi Shubham,

This isn't currently in our immediate backlog. You can submit a feature ask here: [https://feedback.azure.com/forums/256299-site-recovery](https://feedback.azure.com/forums/256299-site-recovery)

Are you referring to the blob, or the container that holds the blobs?

**Comment by shubhamgupta514** [comment]
@bsiva  Yes, I am referring to the container and as monitored on the portal it is getting cleaned up automatically after sometime once I am disabling the replication.

Please close this issue.
