### ISSUE TITLE
Set-AzureRmKeyVaultAccessPolicy example #1 is incorrect

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#5616]
Reported via LiveFyre comment.

### Description

In Example 1: Grant permissions to a user for a key vault and modify the permissions 

The part where you set -PermissionsToSecrets 'set,delete' is incorrect. The type is String[] so it should probably be 'set','delete' instead.

**Comment by maddieclayton** [comment]
Fixed in PR above, will close bug once PR is merged.

**Comment by MiYanni** [comment]
PR is merged
