### ISSUE TITLE
Broken Links in latest docs (AzureRM.Compute Module) 

### ISSUE THREAD

**Issue by TaraMeyer** [Azure/azure-powershell#5639]
### Description

The latest build of the new version of ARM 5.4.0 indicated there are broken links in 3 help topics.

### Script/Steps for Reproduction

azurermps-5.4.0/AzureRM.Compute/Add-AzureRmVMNetworkInterface.md | Invalid file   link:(~/azurermps-5.4.0/AzureRM.Compute/Get-AzureRmNetworkInterface.md).

azurermps-5.4.0/AzureRM.Compute/Add-AzureRmVMSecret.md | Invalid file   link:(~/azurermps-5.4.0/AzureRM.Compute/Set-AzureKeyVaultSecret.md).

azurermps-5.4.0/AzureRM.Compute/Add-AzureRmVmssSecret.md | Invalid file   link:(~/azurermps-5.4.0/AzureRM.Compute/Set-AzureKeyVaultSecret.md).

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by maddieclayton** [comment]
@TaraMeyer this link was edited a month ago by Sean: https://github.com/Azure/azure-powershell/commit/fa674c9d0a1c94f23a48df472f4558291b69d75e

It looks like it was working in 4.4.1 but now not working.  I am not sure how your CI builds the links, so I don't know how to fix this off the bat.

**Comment by maddieclayton** [comment]
@TaraMeyer Ping

**Comment by cormacpayne** [comment]
@sdwheeler can you take a look?

**Comment by sdwheeler** [comment]
These appear to be fixed in the current version of the docs.
