### ISSUE TITLE
Get-AzureRmSqlDatabase does not have a case-insensitive -DatabaseName parameter

### ISSUE THREAD

**Issue by rupalivohra** [Azure/azure-powershell#5645]
### Description

Get-AzureRmSqlDatabase does not have a case-insensitive -DatabaseName parameter.

### Script/Steps for Reproduction

I created my SqlServer from Portal, but from PS I tried to run Get-AzureRmSqlDatabase.

Suppose the DB name is "myD**B**". The below command results in a "Resource not found" error.

```powershell
$sqlDb = Get-AzureRmSqlDatabase -DatabaseName "myDb" -ServerName "{serverName}" -ResourceGroupName "{rgName}"
```

However, replacing "myD**b**" with "myD**B**" works just fine.
```powershell
$sqlDb = Get-AzureRmSqlDatabase -DatabaseName "myDB" -ServerName "{serverName}" -ResourceGroupName "{rgName}"
```

### Module Version

ModuleType = Script
Version = 5.4.1
Name = AzureRM

### Environment Data

|Name|Value|
|:------|:------|
|PSVersion|5.1.16299.248|
|PSEdition|Desktop|
|PSCompatibleVersions| {1.0, 2.0, 3.0, 4.0...}|
|BuildVersion  |10.0.16299.248||
|CLRVersion|                     4.0.30319.42000|
|WSManStackVersion|              3.0|
|PSRemotingProtocolVersion|      2.3|
|SerializationVersion|           1.1.0.1|

### Debug Output

```
PS C:\Users\rupalivohra>  $sqlDb = Get-AzureRmSqlDatabase -DatabaseName "myDb" -ServerName "{redacted}" -ResourceGroupName "{redacted}"
HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/{redacted}/resourceGroups/{redacted}/providers/Mic
rosoft.Sql/servers/{redacted}/databases/myDb?api-version=2014-04-01

Headers:
x-ms-client-request-id        : {redacted}
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
{redacted}
Date                          : Thu, 01 Mar 2018 01:24:44 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "code": "NotFound",
  "message": "Resource not found for the segment 'databases'.",
  "target": null,
  "details": [],
  "innererror": []
}

Get-AzureRmSqlDatabase : Resource not found for the segment 'databases'.
At line:1 char:11
+  $sqlDb = Get-AzureRmSqlDatabase -DatabaseName "myDb" -ServerName "rv ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmSqlDatabase], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.Database.Cmdlet.GetAzureSqlDatabase

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmSqlDatabase; IsSuccess - False; Duration - 00:00:00.9819813; Exception -
 Microsoft.Rest.Azure.CloudException: Resource not found for the segment 'databases'.
   at Microsoft.Azure.Management.Sql.DatabasesOperations.<GetWithHttpMessagesAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Sql.DatabasesOperationsExtensions.<GetAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Sql.DatabasesOperationsExtensions.Get(IDatabasesOperations operations, String
resourceGroupName, String serverName, String databaseName, String expand)
   at Microsoft.Azure.Commands.Sql.Database.Services.AzureSqlDatabaseAdapter.GetDatabase(String resourceGroupName,
String serverName, String databaseName)
   at Microsoft.Azure.Commands.Sql.Database.Cmdlet.GetAzureSqlDatabase.GetEntity()
   at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 5:25:16 PM - GetAzureSqlDatabase end processing.
DEBUG: 5:25:16 PM - GetAzureSqlDatabase end processing.
```

**Comment by cormacpayne** [comment]
@akromm @jaredmoo hey guys, would you mind taking a look at this issue?

**Comment by jaredmoo** [comment]
Thank you for notifying us of this issue! We plan to fix this in the near future as part of a major update to the sql database cmdlet internals.

**Comment by jackfruhecolab** [comment]
Can you also fix this for Get-AzureRmSqlDatabaseExpanded? It appears to have the same bug.

What's interesting is that 
`get-azurermresource | where {$_.resourcetype -eq "Microsoft.Sql/servers/databases"}`
 is returning names that have a different case than that returned by the get-azureSQL database or that are displayed in the portal.

**Comment by jeffpatton1971** [comment]
Team,

FWIW I'm getting a similar response, but I'm running Get-AzureRmResource -ExpandProperties. I'm at a loss as to what the problem is, via the portal, everything "looks" fine, but the powershell is not happy.

Get-AzureRmResource : {"code":"NotFound","message":"Resource not found for the segment \u0027databases\u0027.","target":null,"details":[],"innererror":[]}

The OP talks about case sensitivity, but not sure how that would come into play here. I have noticed that some of the resources have spaces in the name, but I'm seeing them come back from get-azurermresource, so i feel that's not the issue either.

When i run this with -debug, i get literally no help at all, can someone chime in and let me know what the underlying root issue is?

**Comment by jaredmoo** [comment]
Sorry for not replying to this earlier, it was fixed for Get-AzureRmSqlDatabase last year in https://www.powershellgallery.com/packages/AzureRM.Sql/4.5.0 .

Get-AzureRmSqlDatabaseExpanded however is not fixed.

For Get-AzureRmResource, make sure you are getting database using api-version 2017-03-01-preview or later - that will fix the case sensitivity issue.

**Comment by jackfruh** [comment]
Fantastic, 
So in summary, Get-AzSqlDatabaseExpanded isn't fixed, but an updated get-AzResource will now return things in the same case they are stored as internally within azure?

**Comment by jaredmoo** [comment]
Get-AzResource isn't specifically updated, you just need to be using high enough api-version when getting database.
