### ISSUE TITLE
Start-AzureRmAutomationRunbook: Invalid parameters when superflous parameter with null value is present

### ISSUE THREAD

**Issue by clericc** [Azure/azure-powershell#5647]
We have several Runbooks with a parameter of type `object`.

Via .NET sdk, we can start these runbooks without issues. Via Powershell, we can't.

I want to rerun the latest job, so i retrieve it and pipe it into new-job:

```
$job = ($autoAcc | Get-AzureRmAutomationJob)[0]
$job | Start-AzureRmAutomationRunbook -Parameters $job.JobParameters
```

and i get `Start-AzureRmAutomationRunbook : Invalid runbook parameters.`

i checked `$job.JobParameters` to ensure that the property in question is indeed of type `pscustomobject`. I also converted the parameter in place to a hashtable, but this idoes not work as well. I suppose the issue is with the parameter parsing/binding in the cmdlet.

Also, you should probably allow `JobParameters` as alias for `Parameters` in `Start-AzureRmAutomationRunbook`.

**EDIT**: Issue started with a different suspicion, jump down the conversation to what the actual issue is.

**Comment by MiYanni** [comment]
@clericc Multiple questions/comments:
1. I've never seen `-Parameters` before. Are you trying to do [splatting](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-6)?
2. [Start-AzureRmAutomationRunbook](https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/start-azurermautomationrunbook?view=azurermps-5.4.0) does not accept pipeline input from a `Job`. It returns a `Job`.
3. The only values you actually need to start a runbook is the `-Name` (this is the runbook name), `-ResourceGroupName`, and `-AutomationAccountName`.

**Comment by maddieclayton** [comment]
@vrdmr Can you take a look at this issue? It would be nice to have piping for this scenario, and the parameter alias makes sense in this scenario.

**Comment by MiYanni** [comment]
@clericc This should work. Just provide the Runbook name and you're good to go.
```powershell
$job = ($autoAcc | Get-AzureRmAutomationJob)[0]
Start-AzureRmAutomationRunbook `
    -Name <RunbookName> `
    -ResourceGroupName $autoAcc.ResourceGroupName `
    -AutomationAccountName $autoAcc.AutomationAccountName `
    -Parameters $job.JobParameters
```

**Comment by clericc** [comment]
nope, you misunderstand. clearer details tomorrow. don't dismiss this yet please, your assumptions are wrong.

**Comment by MiYanni** [comment]
@clericc `Name`, `ResourceGroupName`, and `AutomationAccountName` can be sent via the pipe (by property name). But, `Job` doesn't have a `Name` property. The other two properties, `ResourceGroupName` and `AutomationAccountName`, will work properly with the pipe. But, you need `Name`.

**Comment by clericc** [comment]
Problem is in the title: runbook has parameter of type object. try to start a runboo with -Parameters @{ objparam = new-object psobject ... }

**Comment by clericc** [comment]
it will fail with tje given error msg

**Comment by vrdmr** [comment]
We are planning to [support](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/automation/resource-manager/Microsoft.Automation/preview/2017-05-15-preview/job.json#L65-L69) Job name but it isn't currently supported in the cmdlet.

**Comment by MiYanni** [comment]
@clericc What version of the Automation module are you using?

**Comment by clericc** [comment]
latest, updated yesterday

**Comment by clericc** [comment]
oh, automation module. tomorrow then, i dont have a pc with me

**Comment by MiYanni** [comment]
@clericc The `Parameters` parameter is of type `IDictionary`. The `JobParameters` property on `Job` is type `Hashtable`. `Hashtable` implements `IDictionary`, so this should work. Otherwise, how did you pass parameters to `Start-AzureRmAutomationRunbook` to create the `Job` originally?

**Comment by clericc** [comment]
Hi yanni,

you now get to the core of the problem. The job was originally created through .NET sdk in C# (where the problem does not arise).

The JobParameters property from `$job` is indeed of type Hastable. Inside it, there is a value of type `psobject`. Piping that into `Start-AzureRmAutomationRunbook` does not work. Converting that `psobject`into hashtable (so we have a hashtable inside the JobParameters hashtable) also does not work.

**Comment by clericc** [comment]
To clarify: 
``` 
$job = ($autoAcc | Get-AzureRmAutomationJob)[0]
$job.JobParameters

Name                           Value
----                           -----
[...]
someObjectParameter  @{prop1=value1; prop2=value2; ... }
[...]

$job.JobParameters.someObjectParameter .GetType()
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    PSCustomObject                           System.Object

$job | Start-AzureRmAutomationRunbook -Parameters $job.JobParameters

Start-AzureRmAutomationRunbook : Invalid runbook parameters.
At line:1 char:105
+ ... b |% { $_ | Start-AzureRmAutomationRunbook -Name $_.RunbookName -Para ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Start-AzureRmAutomationRunbook], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.StartAzureAutomationRunbook

**Comment by MiYanni** [comment]
@vrdmr Can you take a deeper look? Thanks.

**Comment by safeermohammed** [comment]
@clericc 

Couple of questions for the example you have given in issue below

      $job | Start-AzureRmAutomationRunbook -Parameters $job.JobParameters

1. Start-AzureRmAutomationRunbook takes -Name (RunbookName) as mandatory parameter. I see that missing in the given example. 
2. Parameters is HashTable so you need to pass the -Parameters as -Parameters @{"ParameterNameInRunbook"=$job.JobParameters}


Additionally, can you describe how your runbook parameter type is defined as? 

I tried a to repro this with a runbook that has parameter defined as type object as below. Start-AzureRmAutomationRunbook was able to pass object fine as paratemeter to the runbook and jobs was started successfully.  Here are the steps.

 example runbook to repro

Param(
        [Parameter(Mandatory=$True)]
        [object]$TestInput
    )
    Write-Output $TestInput

$acc = Get-AzureRmAutomationAccount -Name AccName -ResourceGroupName RGName
$job = $acc | Get-AzureRmAutomationJob -Id <jobId>
$acc | Start-AzureRmAutomationRunbook -Name <runbookName> -Parameters @{"TestInput"=$job.JobParameter }

Job was started fine and  $job.JobParameter was assigned fine to the input parameter object of Runbook

**Comment by safeermohammed** [comment]
Additionally the below call will not return JobParameters in the job object. Please use Get-AzureRmAutomationJob passing jobId to get the JobParameters. In collection output some properties will be null, so JobParameters will be null in collection. If will be returned only with JobId parameterset 

$job = ($autoAcc | Get-AzureRmAutomationJob)[0]

**Comment by clericc** [comment]
Hi,

to your questions:

1. the Name is ByPropertyName from the Job object that is piped in (see above discussion)
2. $job.JobParameters *is* a hashtable and it in itself represents the parameters for the runbook.

Also, you're correct about List operation of Job does not contain jobParameters, what i actually did was
`$job = ($autoAcc | Get-AzureRmAutomationJob)[0] | Get-AzureRmAutomationJob`. Then, the JobParameters are populated.

i just tried a minimal example with a runbook taking an `int`and an òbject` and everything is working as intended. As soon as i try the exact same procedure with our production runbook (11 parameters, one of them an object with 10 properties) it fails with the given error message.

my mimimal example is:
```
Param(
    [Parameter(Mandatory)]
    [int] $otherinput,
    [Parameter(Mandatory)]
    [object]$TestInput
)

write-output $otherinput
Write-Output $TestInput
```
```
$aa|Start-AzureRmAutomationRunbook -Name test -Parameters @{ otherinput=5; testinput= new-object psobject -Property @{ "a"="b" }}
```` 
or even
```
$aa|Start-AzureRmAutomationRunbook -Name test -Parameters @{ otherinput=5; testinput=  @{ "a"="b" }}
```

and then
```
$aa|Get-AzureRmAutomationJob -Id <IdOfAboveJob>
$job | Start-AzureRmAutomationRunbook -Parameters $job.JobParameters
```
and it works. What else could be wrong here?

**Comment by clericc** [comment]
I just ran Start-Runbook with -Debug and -Verbose. It gives me no hint. It shows the REST response for GET <runbook-uri> and and after that, immediately:

```
Start-AzureRmAutomationRunbook : Invalid runbook parameters.
At line:1 char:6
+ $job|Start-AzureRmAutomationRunbook -Parameters $job.JobParameters -D ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Start-AzureRmAutomationRunbook], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.StartAzureAutomationRunbook

DEBUG: AzureQoSEvent: CommandName - Start-AzureRmAutomationRunbook; IsSuccess - False; Duration - 00:00:04.9713394; Exception -
System.ArgumentException: Invalid runbook parameters.
   at Microsoft.Azure.Commands.Automation.Common.AutomationClient.ProcessRunbookParameters(String resourceGroupName, String automationAccountName,
String runbookName, IDictionary parameters)
   at Microsoft.Azure.Commands.Automation.Common.AutomationClient.StartRunbook(String resourceGroupName, String automationAccountName, String
runbookName, IDictionary parameters, String runOn)
   at Microsoft.Azure.Commands.Automation.Cmdlet.StartAzureAutomationRunbook.AutomationProcessRecord()
   at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 10:38:26 - StartAzureAutomationRunbook end processing.
DEBUG: 10:38:26 - StartAzureAutomationRunbook end processing.```

**Comment by safeermohammed** [comment]
Microsoft.Azure.Commands.Automation.Common.AutomationClient.ProcessRunbookParameters validates the Job parameters and thats were I think the failure is happening. It could be one of the mandatory Parameter is missing or type is mismatch. I can be a bug as well where it unable to serialize the object into Json form. 

Code for this ProcessRunbookParameters is here 
https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Automation/Commands.Automation/Common/AutomationClient.cs#L1706

Does it give any insight with the type of data your production runbook is failing?

**Comment by clericc** [comment]
Many thanks for the link to the source.

Found it. The JobParameters from last job contains a key "x" with value "$null". The runbook does not have this parameter "x" (We deploy a certain set of standard parameters for every runbook in this set, but the runbook is not required to take it, therefore the $null value for the key).

This leads to `filteredParameters.Count != parameters.Count` being false as not every given parameter ends up in `filteredParameters`.

Now we get into semantics of Dictionaries. In a JS object, a key with value $null is considered inexistent. In .NET Dictionary, it is not. Question is, how does the Azure REST backend handle this? This is closed source for me.

Since the null-valued property was present in the JobParameters from the last job, the .NET SDK and the Azure Backend at least seems to treat KeyValuePairs with null as value as inexistent when it comes to binding the runbook parameters.

Considering that the PowerShell modules use the .NET sdk, i would propably vote to emulate the semantics, leading to line 1780 becoming
`filteredParameters.Count != parameters.Where(p => p.Value != null).Count`
or filtering out null values in 1751.

Also, i noticed that in line 1757, ` if (parameters.ContainsKey(runbookParameter.Key))` the check is case sensitive. PowerShell is case-insensitive. i didn' test this, but shouldt the parameter name check be case-insensitive as well?

**Comment by arcotek-ltd** [comment]
@clericc, @MiYanni @safeermohammed,

> latest, updated yesterday

I have a similar problem with `Start-AzureRmAutomationRunbook` where `-parameters` has a hashtable and Automation thinks it's a PSCustomObject, but I'll open a new issue to avoid clouding (no pun intended) yours, but what I will say is I've found an issue with the latest 5.4.1 module. I've raised issue [5674](https://github.com/Azure/azure-powershell/issues/5674). May or may not affect what you're doing. I've rolled back to 4.3.0 and still have an issue.

**Comment by clericc** [comment]
guess not, my issue was always there but until now i was too lazy to file an issue

**Comment by clericc** [comment]
Further argumentation:
```
> function a{
>   param(
>      [Parameter(Mandatory)] $b
>   )
>   $b
> }
>
> a -b $null
a : Cannot bind argument to parameter 'b' because it is null.
```

So PowerShell also considers a value of null as not existent, supporting my argument

**Comment by MiYanni** [comment]
@clericc Why is it necessary to splat the parameters? If you don't splat them (suggestion I made earlier) and pass them explicitly, there should be no issue, correct?

**Comment by clericc** [comment]
dude...splatting is not the point here...read the whole thing and understand it

**Comment by MiYanni** [comment]
@clericc I've read everything above. Are you trying to pass $null for a parameter that does exist? Or, are you trying to pass parameters that don't exist?

Per your comment:
> So actually, the .NET sdk (and Azure REST api) should not accept $null value for a Key which is not a parameter of the runbook.

Are you intentionally sending superfluous runbook parameters?

Additionally:
> The JobParameters from last job contains a key "x" with value "$null". The runbook does not have this parameter "x" (We deploy a certain set of standard parameters for every runbook in this set, but the runbook is not required to take it, therefore the $null value for the key).

It just sounds like you are sending extra parameters. That's why I keep going back to splatting. If you simply created a new Hashtable with the properties explicitly specified, then it should work, similar to your `TestInput`/`OtherInput` example.

**Comment by clericc** [comment]
now we're talking :)

> Are you intentionally sending superfluous runbook parameters?
Yes.

>It just sounds like you are sending extra parameters. 
Yes.

We are able to start a runbook via rest api gibing superflous parameters with null as value.

You can't do that via Powershell. But Get-AzureRmAutomationJob gives me the original inputs, containing the superflous parameter. I can't pipe these back into new-job.

**Comment by MiYanni** [comment]
@clericc This is a restriction of the PowerShell language. It doesn't accept extra parameters for a cmdlet/function that doesn't have those parameters defined. REST can do this because of how HTTP routing/query parameters are processed. 

It makes sense for `Get-AzureRmAutomationJob` to return the original information provided to it. Again, you can use the information from `Get-AzureRmAutomationJob` if you specify the runbook parameters explicitly when starting a new job (via `Start-AzureRmAutomationRunbook`). Even if the superfluous runbook parameter values were non-null, it still wouldn't work in the way you're attempting. `Get-AzureRmAutomationJob` can't possibly know it is giving superfluous information... since it just tells you what you provided it.

The reason [ProcessRunbookParameters](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Automation/Commands.Automation/Common/AutomationClient.cs#L1706) is filtering the provided parameters is to make sure that it can start the runbook properly (in PowerShell). 
@vrdmr @safeermohammed @najams 
To fix, it seems that this check should be removed:
```cs
if (filteredParameters.Count != parameters.Count)
```
Since you are filtering the parameters based on what parameters are available in the runbook, this check is only serves to not allow someone to provide superfluous parameters. In this case, it is causing an issue for @clericc. Do you think it makes sense to remove this check?

**Comment by safeermohammed** [comment]
The cmdlet appears to be doing the right thing by letting the user know that an invalid parameter is passed to the runbook that does exists. We have not heard from any users that this validation is causing the issue. In fact the cmdlet is using a fail fast approach, lets say a user creates a schedule and forgets to pass a mandatory parameter. If there is no check the Job will fail with validation error only at scheduled time, that would be a bad experience for user.

If there are enough asks we will considering removing the validation.  

Since in this particular case the user created the Job via REST API, and would still like to pass the extra parameter, can the REST API (Invoke-webrequest) be used directly to bypass cmdlets?

**Comment by MiYanni** [comment]
To add, I'll also have [Invoke-AzureRmRestMethod](https://github.com/Azure/azure-powershell/issues/3806) sometime after //build. That would allow them to easily do direct REST API calls for Azure in PowerShell.

**Comment by clericc** [comment]
@safeermohammed i agree with you, the cmdlets behaviour with the check is totally fine. i work around this by redesigning our services to not create empty parameters.

Could we still get `-JobParameters` as an alias for `-Parameters` in `Start-AzureRmAutomationRunbook`?

**Comment by safeermohammed** [comment]
Sure, we will do that in next release and add alias -JobParameters.

**Comment by clericc** [comment]
As of v6.5.0, Start-AzureRmAutomationRunbook still has no Parameter alias, Piping still not possible.

**Comment by clericc** [comment]
alias is present in new Az command
