### ISSUE TITLE
New-AzureRmVM docs incorrect

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#5649]
### Description
In the description section of the New-AzureRmVM docs it refers to the `StrategyParameterSet`. The correct name is `SimpleParameterSet`

Also, in Example #1 shows the following syntax:

```powershell
New-AzureRmVM -Name MyVm
```

However, the **-Credential** parameter is also require. Need to update the example to include this.

**Comment by cormacpayne** [comment]
https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/new-azurermvm

**Comment by maddieclayton** [comment]
Fixed.
