### ISSUE TITLE
New-AzureRmVM should display information about the objects being created with -WhatIf

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-powershell#5650]
### Description

New-AzureRmVM (probably other strategy cmdlets) should display information about the different resources being created with -WhatIf

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by maddieclayton** [comment]
@sergey-shandar Is this completed?

**Comment by sergey-shandar** [comment]
@maddieclayton yes
