### ISSUE TITLE
New-AzureRmVMSS/VM (simple paremeterset) should support data disk creation

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-powershell#5661]
### Description

https://review.docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/tutorial-use-disks-powershell?branch=pr-en-us-33477#create-and-attach-disks

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by sergey-shandar** [comment]
@iainfoulds @gatneil How should calculate LUN? In examples, the first data disk has Lun value 1. Does it mean Lun 0 is OS disk? What happen if image has already several disks? Should I start with Lun = # of OS disks?

**Comment by sergey-shandar** [comment]
@iainfoulds @gatneil Currently, partition appears as RAW and there is no disk in Windows Exporer. Should we also format the data disk?

**Comment by gatneil** [comment]
@yugangw-msft I think in the CLI, we just do LUN 1 for the first data disk, LUN 2 for the second, etc. right? @sergey-shandar: technically this could potentially have a conflict if the custom image already has data disks in the image, but there's no way for us to inspect the image, so there's no way to know. So I think this behavior should be fine.

@sergey-shandar yup, it's fine to leave the data disk RAW. We make customers format the disks themselves.

Thanks! :)

**Comment by yugangw-msft** [comment]
> @yugangw-msft I think in the CLI, we just do LUN 1 for the first data disk, LUN 2 for the second, etc. right? 

Actually, CLI starts LUN from 0. For managed images, CLI also retrieves the image resource to count the data disk number and adjusts the LUN for user supplied data disks accordingly.

**Comment by yugangw-msft** [comment]
And  as far as i know, os disk has no concept of LUN, and that is revealed in the swagger spec as well.

**Comment by iainfoulds** [comment]
@sergey-shandar As @gatneil notes, it's fine to leave the raw disks. We have a couple of example scripts, such as https://github.com/Azure-Samples/compute-automation-configurations/blob/master/prepare_vm_disks.ps1, that prepare the disks. For Linux customers, they may want a different partition layout or filesystem, so it's best not to make those decisions for them.
