### ISSUE TITLE
Add Support for scale the service bus

### ISSUE THREAD

**Issue by ammaroff** [Azure/azure-powershell#568]
Add support to scale the service bus capacity
![image](https://cloud.githubusercontent.com/assets/4321246/8514424/cc91407a-23d2-11e5-822f-48bce9694521.png)

the end point in management portal is : 
https://manage.windowsazure.com/ServiceBus/UpdateMessagingSKUPlan
and its need this data in POST :
"skuProperties":{"SKU":2,"CurrentSKUUnits":20}

**Comment by markpjohnson** [comment]
+1

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
