### ISSUE TITLE
Get-AzureRmDisk silently ignores DiskName parameter if ResourceGroupName is not also specified

### ISSUE THREAD

**Issue by ayeltsov** [Azure/azure-powershell#5688]
### Description

Get-AzureRmDisk silently ignores -DiskName parameter if -ResourceGroupName is not specified

### Script/Steps for Reproduction

Ensure more than 1 disk exists in the subscription

#Run and pick one disk
Get-AzureRmDisk | select ResourceGroupName, Name

#try below, notice all disks returned
get-AzureRmDisk -DiskName MyDiskName

#try below, notice single disk returned
get-AzureRmDisk -DiskName MyDiskName -ResourceGroupName MyResourceGroup

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```
ModuleType Version    Name
---------- -------    ----
Script     5.4.1      AzureRM
Script     5.3.0      AzureRM

### Environment Data

n/a
```powershell
$PSVersionTable
```

### Debug Output

Omitted due to privacy concerns.

```

```

**Comment by maddieclayton** [comment]
@hyonholee @huangpf Can you take a look at this issue and fix or assign it to the correct person? I looked through the code and it does seem like this is an issue on the PowerShell side.

**Comment by maddieclayton** [comment]
I will be sure to include this fix in the changes for this issue: https://github.com/Azure/azure-powershell/issues/6549
