### ISSUE TITLE
Roles returning array if they contain 'and' in the name

### ISSUE THREAD

**Issue by everettsouthwick** [Azure/azure-powershell#5696]
### Description

If a custom role contains the word 'and' in the name it will behave errantly. When you specify the name of the role in the cmdlet `Get-AzureRmRoleDefinition -Name "[Role Name]"` it'll return an array of all roles available in that subscription. When you specify the name of the role in the cmdlet `New-AzureRmRoleAssignment -ObjectId [Guid] -Scope "[Scope]" -RoleDefinitionName "[Role Name]"` it will return the error that there are multiple groups with that name, even if there is only one group of that name. This same command will succeed if you explicitly provide the ID of the role, as opposed to the name of the role.

In addition to this, creating a brand new role with 'and' in the name appears to succeed, but it will not show up when you query for it with `Get-AzureRmRoleDefinition -Name "[Role Name]"`.

### Script/Steps for Reproduction

```powershell
Login-AzureRmAccount

$role = [Microsoft.Azure.Commands.Resources.Models.Authorization.PSRoleDefinition]::new()
$role.Name = 'Test Role and'
$role.IsCustom = $true
$role.Description = 'Description'
$role.Actions = @('Microsoft.Compute/virtualMachines/read')
$role.NotActions = @()
$role.AssignableScopes = @("[Subscription Scope]")

Write-Host "Creating a new role with the word 'and' in the name"
New-AzureRmRoleDefinition -Role $role

Write-Host "Getting the newly created role with the word 'and' in the name"
Get-AzureRmRoleDefinition -Name 'Test Role and'
```

### Module Version

![Module Version](https://i.imgur.com/n4t1PDf.png)

### Environment Data

![Environment Data](https://i.imgur.com/GxCMXxf.png)

### Debug Output

`Get-AzureRmRoleDefinition` with a role with 'and' in the title: https://pastebin.com/F90VFhTR

`Get-AzureRmRoleDefinition` with a role without 'and' in the title: https://pastebin.com/LtCzi8Hb

`New-AzureRmRoleAssignment` with a role with 'and' in the title: https://pastebin.com/1z3Smjd1

`New-AzureRmRoleAssignment` with a role without 'and' in the title: https://pastebin.com/pn5Jvjs2

**Comment by maddieclayton** [comment]
@darshanhs90 Can you take a look at this issue?

**Comment by darshanhs90** [comment]
sure will look into it

**Comment by darshanhs90** [comment]
this seems like a bug in the service,let me log a task for this

**Comment by darshanhs90** [comment]
@everettsouthwick This issue is fixed in the service,you should be able to get it working
