### ISSUE TITLE
ARM: Some cmdlet doesn't respond, when incorrect location specified.

### ISSUE THREAD

**Issue by m-moris** [Azure/azure-powershell#571]
I specified incorrect location to the cmdlet , the cmdlet does not respond for a few minutes.
Now, "japan west2" does not exists.

```
Get-AzureVMSize -Location "japan west2"
```

or 

```
Get-AzureVMImagePublisher -Location "japan west2"
```

I think cmdlet should respond more faster.

Best Regards

**Comment by markcowl** [comment]
@m-moris Thank you for the feedback.  Assigning to the service team for investigation

**Comment by singhkay** [comment]
Discussing with the platform team on who needs to fail fast here

**Comment by singhkay** [comment]
Assigning to the RM team as there is work happening on the platform to solve issues related to wrong locations.

**Comment by vivsriaus** [comment]
This will be fixed by the Compute team. No changes will be required in the powershell repo.
