### ISSUE TITLE
Failed NetCore conversions

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5719]
Using the PSD1 and CsProj conversion tools, the projects generated for NetCore could not build successfully. Here are the reasons that I logged for the build failures. These would need to be investigated further and see if simple resolutions are possible. If not, the service teams may need to be involved.

# Not Working
### ~~Commands.AnalysisServices.Dataplane~~
- ~~'Detected package downgrade' issues~~
- ~~https://github.com/Azure/azure-powershell/issues/5753~~
### ~~Commands.ApiManagement~~
- ~~Microsoft.WindowsAzure.Storage dependency~~
### ~~Commands.AzureBackup~~
- ~~Local dependencies~~
  - ~~Microsoft.WindowsAzure.Management.Common.dll~~
  - ~~Security.Cryptography.dll~~
### ~~Commands.Batch~~
- ~~Microsoft.WindowsAzure.Storage dependency~~
### ~~Commands.ContainerInstance~~
- ~~Missing references(?)~~
### ~~Commands.DataFactories~~
- ~~Microsoft.WindowsAzure.Storage dependency~~
### ~~Commands.DataLakeStore~~
- ~~Missing references(?)~~
### ~~Commands.DataMigration~~
- ~~Missing references(?)~~
### ~~Commands.Dns~~
- ~~Missing references(?)~~
### ~~Commands.HDInsight~~
- ~~Microsoft.WindowsAzure.Storage dependency~~
### ~~Commands.Insights~~
- ~~Missing references(?)~~
### ~~Commands.LocationBasedServices~~
- ~~'Detected package downgrade' issues~~
### ~~Commands.ManagedServiceIdentity~~
- ~~Commands.ServiceManagement.Common dependency~~
### ~~Commands.Partner~~
- ~~'Detected package downgrade' issues~~
### ~~Commands.RecoveryServices~~
- ~~Missing references(?)~~
### ~~Commands.RecoveryServices.Backup.Models~~
- ~~'Detected package downgrade' issues~~
### ~~Commands.RecoveryServices.Backup, Commands.RecoveryServices.Backup.Helpers, Commands.RecoveryServices.Backup.Providers, Commands.RecoveryServices.Backup.ServiceClientAdapter~~
- ~~Relies on `Commands.RecoveryServices.Backup.Models`~~
### ~~Commands.RecoveryServices.SiteRecovery~~
- ~~Relies on `Commands.RecoveryServices`~~
### ~~Commands.RedisCache~~
- ~~Microsoft.WindowsAzure.Storage dependency~~
### ~~Commands.SiteRecovery~~
- ~~Relies on `Commands.RecoveryServices`~~
### ~~Commands.Sql~~
- ~~Relies on `LegacySdk`~~

# Investigations
### Commands.Resources.Rest.csproj
- ~~Referenced by `Commands.ContainerRegistry`~~
- ~~Dependency located in `src\ResourceManager\Resources\Commands.ResourceManager\Cmdlets`~~
- https://github.com/Azure/azure-powershell/issues/5775

**Comment by MiYanni** [comment]
## WIP
- [ ] Commands.AnalysisServices.Dataplane
- [ ] Commands.ApiManagement
- [ ] Commands.AzureBackup
- [ ] Commands.Batch
- [ ] Commands.ContainerInstance
- [ ] Commands.DataFactories
- [ ] Commands.DataLakeStore
- [ ] Commands.DataMigration
- [ ] Commands.Dns
- [ ] Commands.HDInsight
- [ ] Commands.Insights
- [ ] Commands.LocationBasedServices
- [ ] Commands.ManagedServiceIdentity
- [ ] Commands.Partner
- [ ] Commands.RecoveryServices
- [ ] Commands.RecoveryServices.Backup.Models
- [ ] Commands.RecoveryServices.Backup, Commands.RecoveryServices.Backup.Helpers, Commands.RecoveryServices.Backup.Providers, Commands.RecoveryServices.Backup.ServiceClientAdapter
- [ ] Commands.RecoveryServices.SiteRecovery
- [ ] Commands.RedisCache
- [ ] Commands.SiteRecovery
- [ ] Commands.Sql

**Comment by jackfruh** [comment]
I appreciate the work you're doing on this!

**Comment by MiYanni** [comment]
These projects have been merged
