### ISSUE TITLE
Allow pipelining Get-AzureSubscription into Get-AzureEnvironment

### ISSUE THREAD

**Issue by jaredmoo** [Azure/azure-powershell#572]
Currently the way to get the current environment is like this:

$subscription = Get-AzureSubscription -Current
$environment = Get-AzureEnvironment -Name $subscription.Environment

It would be more convenient (saves typing) if we could pipe into Get-AzureEnvironment like this:

Get-AzureSubscription -Current | Get-AzureEnvironment

**Comment by markcowl** [comment]
@jaredmoo We are undergoing a redesign of some of the authentication infrastructure, so that this prescise scenario won't be relevant, but you will be able to get details of the current azure endpoints.  Closing because we won't support this precisely, but you will see this functionality soon.
