### ISSUE TITLE
[ApiManagement] Exception in Get-AzureRmApiManagementBackend 

### ISSUE THREAD

**Issue by berndku** [Azure/azure-powershell#5724]
### Description

Get-AzureRmApiManagementBackend throws exception "Cannot convert object to string", if a Service Fabric backend exists.

### Script/Steps for Reproduction
Create Service Fabric Backend in API Management first.

```powershell
Get-AzureRmApiManagementBackend -Context $apimContext
```
### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.4.1      AzureRM

### Environment Data

```powershell
$PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      5.1.16299.248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Debug Output

```
Message        : Can not convert Object to String.
StackTrace     :    at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                    at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
                    at Microsoft.Azure.Management.ApiManagement.BackendOperationsExtensions.List(IBackendOperations
                 operations, String resourceGroupName, String serviceName, QueryParameters query)
                    at
                 Microsoft.Azure.Commands.ApiManagement.ServiceManagement.ApiManagementClient.ListPaged[T](Func`1
                 listFirstPage, Func`2 listNextPage)
                    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.ApiManagementClient.ListPagedAndMap[TOu
                 t,TIn](Func`1 listFirstPage, Func`2 listNextPage)
                    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.GetAzureApiManagementBackend.E
                 xecuteApiManagementCmdlet()
                    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.AzureApiManagementCmdletBase.E
                 xecuteCmdlet()
Exception      : System.ArgumentException
InvocationInfo : {Get-AzureRmApiManagementBackend}
Line           : Get-AzureRmApiManagementBackend -Context $apimContext
Position       : At line:1 char:1
                 + Get-AzureRmApiManagementBackend -Context $apimContext
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 11
```

**Comment by maddieclayton** [comment]
@solankisamir Can you take a look at this issue?

**Comment by solankisamir** [comment]
This should not be an issue now with https://github.com/Azure/azure-powershell/releases/tag/v6.1.0-May2018
