### ISSUE TITLE
Need list of valid values for CommandId in Invoke-AzureRmVMRunCommand

### ISSUE THREAD

**Issue by sdwheeler** [Azure/azure-powershell#5726]
Reported via LiveFyre - https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/invoke-azurermvmruncommand

### Description

CommandId is an important parameter. The list of allowed values for this parameter is not documented.
Please update your documentation and list these values.

- EnableRemotePS - Configure the machine to enable remote PowerShell. (Windows)
- Ipconfig - List IP configuration (Windows)
- ifconfig - List network configuration (Linux)
- RunPowerShellScript - Executes a PowerShell script (Windows)
- RunShellScript - Executes a Linux shell script
- EnableAdminAccount - Enable administrator account (Windows)
- ResetAccountPassword - Reset built-in Administrator account password (Windows)
- RDPSettings - Verify RDP Listener Settings (Windows)
- SetRDPPort - Set Remote Desktop port (Windows)
- ResetRDPCert - Restore RDP Authentication mode to defaults (Windows)

Is this list correct and complete?

**Comment by cormacpayne** [comment]
@hyonholee Hey Hyonho, would you mind taking a look at this doc issue?

**Comment by marinnedea** [comment]
When running scripts for Linux VMs, there's no clear description of where the script should be located ( on the machine running the PS or on the Linux VM ??). So.. can we get a sample "scriptpath" usage for linux?

**Comment by amoghnatu** [comment]
@marinnedea The script should be located on the machine running the PS. That script gets copied to the VM and gets executed there.

**Comment by marinnedea** [comment]
@amoghnatu thank you! Well.. I figured it out myself in the meantime. Nevertheless.. there should be a mention on this in the documentation.

**Comment by amoghnatu** [comment]
Just curious, does anyone here know where in the VM does the script actually get downloaded to before it runs?
@marinnedea , @sdwheeler , @cormacpayne

**Comment by amoghnatu** [comment]
I figured it out. The script is downloaded in the location /var/lib/waagent/run-command/download/{someNumber} on linux VMs.
@marinnedea , @sdwheeler , @cormacpayne

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.

**Comment by viskin** [comment]
The issue is old, but still relevant to Invoke-AzVMRunCommand documentation - there is no list of possible values of CommandId parameter.
Please reopen.
