### ISSUE TITLE
Get-AzureRmVM with -Name and -Status parameters does not show PowerState property

### ISSUE THREAD

**Issue by gzaika** [Azure/azure-powershell#5728]
### Description

It is easier to get status for all VMs in Resource Groups in one shot, using simple, top level property PowerState, than either loop through all VMs, or dig it out from somewhere in Statuses property.

### Script/Steps for Reproduction

```powershell
$vmname = "xxxxx"
$RGName = "yyyyy"
$myVM = Get-AzureRmVM -ResourceGroupName $RGName -Status -Name $vmname 

$myVM2 = Get-AzureRmVM -ResourceGroupName $RGName -Status | where-object {$_.Name -eq $vmname} 
```
Output display 2 different set of properties. Most important, PowerState in $myVM output is missing.
### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by cormacpayne** [comment]
@gzaika is the property missing in _just_ the output displayor is it also missing from the returned object as well? (_i.e._, can you do `$myVM.PowerState`?)

CC: @hyonholee

**Comment by axelgMS** [comment]
quicly reproduced that
so $myVM.Powerstate doesn't work, but the following shows the VM's PowerState

$myVM = Get-AzureRmVM -ResourceGroupName $RGName -Status -Name $vmname 
$myvm.Statuses[1].Code
$myvm.Statuses[1].DisplayStatus

**Comment by praries880** [comment]
@hyonholee Can you have a look at this?

**Comment by avelis26** [comment]
**I can confirm... having similar issue.**

#### Input:
```powershell
$var = Get-AzureRmVm -Status
```

#### Output:
ResourceGroupName  |  Name  |  PowerState
-----------------  |  ----  |  ----------
foo  |  bar  |  running

**When I try to assign or output the "*PowerState*" property, I get a slightly different result.**

#### Input:
```powershell
$var.PowerState
```

#### Output:
`VM running`

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
