### ISSUE TITLE
Set-AzureResource does not set tags on VMs (P0)

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-powershell#573]
If I run the following command:
Set-AzureResource -ResourceId $v.ResourceId -Tag @{"foo"="bar"}

The tags property should be set on the resource, in this case the resource was a VM.  Looking at the debug output from the cmdlet the PATCH request shows an empty tag and the tags are indeed removed from the resource (existing tags were removed, new one was not set)

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com/subscriptions/[subscription]/resourceGroups/dscsimple/providers/Microsoft.Compute/virtualMachines/MyWindowsVM?api-version=2015-06-15

Headers:
User-Agent                    : AzurePowershell/v0.9.4,VSAzureTools

Body:
{
  "tags": {}
}

DEBUG: ============================ HTTP RESPONSE ============================

**Comment by vivsriaus** [comment]
@bmoore-msft Closing this issue for now, based on our email conversations regarding usability of tags. FWIW - the correct way to pass tags is this:
@(@{"Name"="foo";"Value"="bar"})
