### ISSUE TITLE
New-AzureRmVMSS/VM should support zones.

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-powershell#5730]
### Description

https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-availability-zones#use-azure-powershell

### Scenarios

|cmdlet|parameter|type    |main resource(VM/VMSS)|PublicIP                                        |LoadBalancer        |
|------|-----------|--------|----------------------------|------------------------------------|--------------------|
|VM    |               |           |                                          |PIP.Sku = Basic                             |                              |
|VM    |Zone       |string[]|VM.Zones = Zone             |PIP.Sku = Basic, PIP.Zones = Zone|                              |
|VMSS|               |           |                                          |PIP.Sku = Basic                              |LB.Sku = Basic      |
|VMSS|Zone       |string[]|VMSS.Zones = Zone         |PIP.Sku = Standard                       |LB.Sku = Standard|

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by markcowl** [comment]
I think we need to understand the interaction between PIP.SKU and the Zone settings - is it acceptable to use Standard Sku whenever Zone is specified (VM or VMSS)?

**Comment by markcowl** [comment]
Are there any other resources that require special settings if one or more zones are specified?

**Comment by twitchax** [comment]
@gatneil and @iainfoulds for visibility into these questions on Zones.

**Comment by sergey-shandar** [comment]
@yugangw-msft could you have a look and confirm the behavior?

**Comment by yugangw-msft** [comment]
> I think we need to understand the interaction between PIP.SKU and the Zone settings - is it acceptable to use Standard Sku whenever Zone is specified (VM or VMSS)?

@markcowl, when zone is specified, VMSS should use Standard PIP to work with Standard LB. Basic LB is pretty dead for zonal VMSS
For a VM, if it is put into the BE pool of Standard LB, then it should use Standard PIP

**Comment by gatneil** [comment]
If using standard LB, must also have NSG with incoming allow rules with backend port 22 for linux; 3389 for windows; additionally, you need a load balancer rule on port 80 (and also open this on the NSG).

**Comment by sergey-shandar** [comment]
@yugangw-msft @gatneil I've tried VMSS with zones and without NSG, it works. I mean, I was able to connect using SSH, run a webservice and connect to the website.

**Comment by gatneil** [comment]
@sergey-shandar can you share a repro?

**Comment by sergey-shandar** [comment]
@gatneil yes. I'm working on scenario test right now, I will share it soon.

**Comment by sergey-shandar** [comment]
## 1. Create Ubuntu VMSS, two instances, two zones
```ps1
New-AzureRmVMss -Name zxc -Location westeurope -ImageName ubuntults -Zone 1,2
```

## 2 Connect to each VM and run simple webservice
```bash
ssh Qwerty@zxc-8ef2bd.westeurope.cloudapp.azure.com -p 50002
sudo python -m SimpleHTTPServer 80
```

## 3 Connect to website

http://zxc-8ef2bd.westeurope.cloudapp.azure.com

**Comment by yugangw-msft** [comment]
@sergey-shandar, to save the time, would be great if you could just share the the response payload of VMSS GET and paste here. I have a x-zone vmss, w/o nsg, i can `never` connect to it

**Comment by yugangw-msft** [comment]
Also, by looking at ` Qwerty@zxc-8ef2bd.westeurope.cloudapp.azure.com`, did you enable instance level of pip and dns label? Just make sure the connection did go through the LB...

**Comment by iainfoulds** [comment]
If I follow https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/quick-create-powershell but add `-Zone "1", "2"`, the scale set and network resources are correctly created as zone-redundant, but I can't connect to the web application via the public IP of the load balancer. I have to create a NSG that allows TCP port 80 and create a load balancer health probe before traffic flows correctly.

**Comment by yugangw-msft** [comment]
@sergey-shandar , JFYI, below is the sample VMSS profile with required nsg at the bottom. W/o that connection won't work with instances
```
    "virtualMachineProfile": {
      "additionalProperties": {},
      "diagnosticsProfile": null,
      "extensionProfile": null,
      "licenseType": null,
      "networkProfile": {
        "additionalProperties": {},
        "healthProbe": null,
        "networkInterfaceConfigurations": [
          {
            "additionalProperties": {},
            "dnsSettings": {
              "additionalProperties": {},
              "dnsServers": []
            },
            "enableAcceleratedNetworking": false,
            "enableIpForwarding": false,
            "id": null,
            "ipConfigurations": [
              {
                "additionalProperties": {},
                "applicationGatewayBackendAddressPools": null,
                "id": null,
                "loadBalancerBackendAddressPools": [
                  {
                    "additionalProperties": {},
                    "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/yg3/providers/Microsoft.Network/loadBalancers/yg3-ss2LB/backendAddressPools/yg3-ss2LBBEPool",
                    "resourceGroup": "yg3"
                  }
                ],
                "loadBalancerInboundNatPools": [
                  {
                    "additionalProperties": {},
                    "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/yg3/providers/Microsoft.Network/loadBalancers/yg3-ss2LB/inboundNatPools/yg3-ss2LBNatPool",
                    "resourceGroup": "yg3"
                  }
                ],
                "name": "yg3ss47a9IPConfig",
                "primary": null,
                "privateIpAddressVersion": "IPv4",
                "publicIpAddressConfiguration": null,
                "subnet": {
                  "additionalProperties": {},
                  "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/yg3/providers/Microsoft.Network/virtualNetworks/yg3-ssVNET/subnets/yg3-ssSubnet",
                  "resourceGroup": "yg3"
                }
              }
            ],
            "name": "yg3ss47a9Nic",
            "networkSecurityGroup": {
              "additionalProperties": {},
              "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/yg3/providers/Microsoft.Network/networkSecurityGroups/yg3-ss2NSG",
              "resourceGroup": "yg3"
            },
            "primary": true
          }
        ]
      },
```

**Comment by sergey-shandar** [comment]
NSG

|cmdlet|parameter|type    |main resource(VM/VMSS)|PublicIP                                        |LoadBalancer        |NSG|
|------|-----------|--------|----------------------------|------------------------------------|--------------------|---|
|VM    |               |           |                                          |PIP.Sku = Basic                             |                              | |
|VM    |Zone       |string[]|VM.Zones = Zone             |PIP.Sku = Basic, PIP.Zones = Zone|                              | |
|VMSS|               |           |                                          |PIP.Sku = Basic                              |LB.Sku = Basic      | |
|VMSS|Zone       |string[]|VMSS.Zones = Zone         |PIP.Sku = Standard                       |LB.Sku = Standard|{}|

**Comment by sergey-shandar** [comment]
@iainfoulds @gatneil @yugangw-msft right, I can't connect to my VMSS anymore. I was able to do this before today.

**Comment by sergey-shandar** [comment]
Merged.
