### ISSUE TITLE
DataLakeStore: Change FileSystemCmdletProviderEncoding usage to System.Text.Encoding

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5742]
Currently, these cmdlets use `FileSystemCmdletProviderEncoding` for their `Encoding` parameter:
- [New-AzureRmDataLakeStoreItem](https://docs.microsoft.com/en-us/powershell/module/azurerm.datalakestore/new-azurermdatalakestoreitem?view=azurermps-4.4.1)
- [Add-AzureRmDataLakeStoreItemContent](https://docs.microsoft.com/en-us/powershell/module/azurerm.datalakestore/add-azurermdatalakestoreitemcontent?view=azurermps-4.4.1)
- [Get-AzureRmDataLakeStoreItemContent](https://docs.microsoft.com/en-us/powershell/module/azurerm.datalakestore/get-azurermdatalakestoreitemcontent?view=azurermps-4.4.1)

This enum no longer exists for PowerShell Core. Instead, cmdlets such as `Add-Content`, `Get-Content`, and `Set-Content` use `System.Text.Encoding`.  The DataLakeStore cmdlets should also use this type.

**Note**: This is a breaking change for the desktop cmdlets. This should be planned for a breaking change release.

- [ ] Change these classes to use `System.Text.Encoding` for the `Encoding` parameter instead of `FileSystemCmdletProviderEncoding`
  - Commands.DataLakeStore/Commands/AddAzureRmDataLakeStoreItemContent.cs
  - Commands.DataLakeStore/Commands/GetAzureRmDataLakeStoreItemContent.cs
  - Commands.DataLakeStore/Commands/NewAzureRmDataLakeStoreItem.cs
  - Commands.DataLakeStore/Models/DataLakeStoreFileSystemCmdletBase.cs
- [ ] Create a tab completer to use the static fields in `System.Text.Encoding`
  - Since it is no longer an enum, tab completion will not work out-of-the-box
- [ ] Create/update scenario tests to cover the parameter type change

Additional information here: https://github.com/PowerShell/PowerShell-Docs/issues/2000

**Comment by ro-joowan** [comment]
@rahuldutta90 Can you incorporate this when we make the SDK switch?

**Comment by ro-joowan** [comment]
@rahuldutta90 Please ack

**Comment by rahuldutta90** [comment]
Acknowledge. Talked with @MiYanni offline and will make this fix as  apart of a new PR after https://github.com/Azure/azure-powershell/pull/5787/files goes through.

**Comment by ro-joowan** [comment]
👍

**Comment by MiYanni** [comment]
@rahuldutta90 Checking in. The PR you mentioned was merged in April. I'm just making sure updating the Encoding parameter isn't forgotten.

**Comment by rahuldutta90** [comment]
Thanks @MiYanni for reminding. Let me start a PR for this.

**Comment by MiYanni** [comment]
This fix was merged in https://github.com/Azure/azure-powershell/pull/6598.
