### ISSUE TITLE
Invoke-AzureRmVMRunCommand returns cached output on reruns with linux VMs

### ISSUE THREAD

**Issue by thisSIDEofRANDOM** [Azure/azure-powershell#5757]
### Script/Steps for Reproduction

Create a script file with one command inside it I chose the below to illustrate the issue:

date.sh contains:
```date```

Next we run the script to execute the above command on a Linux VM.
```
Invoke-AzureRmVMRunCommand -ResourceGroupName $ResourceGroupName -Name $ResourceName -CommandId 'RunShellScript' -Script "date.sh" -Verbose
```

I get the following back first run:
```Output    : {"code": "ProvisioningState/succeeded" "level": "Info" "displayStatus": "Provisioning succeeded" "message": "Enable succeeded: \n[stdout]\nFri Mar 16 00:31:12 EDT 2018\n\n[stderr]\n"}```

Run the invoke command again and the output is the exact same even though the time has changed. We are getting cached data?

I had a look under /var/lib/waagent/run-command/download/0/stdout and found this output never gets updated on re run of the invoke, it seems to find that the script sum hasn't changed and so it never seems to execute for new data?

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable

Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.5.0      AzureRM
Script     5.3.0      AzureRM
Script     5.1.1      AzureRM
Script     5.0.1      AzureRM
Script     4.4.1      AzureRM
```

### Environment Data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by thisSIDEofRANDOM** [comment]
For what its worth this is also happening in azurecli - https://github.com/Azure/azure-cli/issues/5833

**Comment by cormacpayne** [comment]
@koralski @hyonholee @savyasachisamal would you mind taking a look at this issue?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
