### ISSUE TITLE
RecoveryServices project consolidation

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5768]
- [ ] Consolidate the following modules into 1-2 projects, depending on what logically makes sense to be grouped together
  - AzureBackup
  - RecoveryServices
  - RecoveryServices.Backup (all projects therein)
  - RecoveryServices.SiteRecovery
  - SiteRecovery

There is duplicate code within multiple projects and it is difficult to maintain outdated projects. Please review all projects and remove duplicate code. Modules should not have dependencies on each other. If they do, they need to be the same module.

**Comment by cormacpayne** [comment]
The work was this has been completed.
