### ISSUE TITLE
Sql: Update LegacySdk to no longer rely on Microsoft.Bcl.Async

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5769]
- [ ] LegacySdk (`SqlManagement.csproj`) uses `TaskEx`. Replace with `Task` usage.

This is a stopgap instead of removing usage of LegacySdk. Instead, simply allow `TaskEx` to no longer be used so this project does not rely on a non-NetCore library, `Microsoft.Bcl.Async`. Usage of `TaskEx` was replaced with `Task` in later versions of the framework, and exist in .NET Core.

**Note**: To allow the SQL .NET Core project to build currently, I'm referencing `Microsoft.Bcl.Async`. But, these calls could fail at runtime. We do not guarantee that referencing non-NetCore dependencies will work at runtime in .NET Core.

**Comment by jaredmoo** [comment]
Is this just find-replace TaskEx -> Task?

**Comment by MiYanni** [comment]
@jaredmoo Potentially. I'd rather not use `LegacySdk`, but it has hundreds of references in the Commands.Sql project. I'm generally keeping track of what may cause failures when running the cmdlets in .NET Core. So, this is one of those potential issues.

**Comment by jaredmoo** [comment]
LegacySdk is just the Hyak client. Does Hyak support .net core client generation now?

**Comment by MiYanni** [comment]
@jaredmoo AFAIK, Hyak is no longer used in favor of [AutoRest](https://github.com/Azure/autorest). This creates the [Azure .NET SDK](https://github.com/Azure/azure-sdk-for-net) which is what most services use. You reference your [Azure Sql SDK](https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SDKs/SqlManagement/Management.Sql) from here, which is what should be used instead of `LegacySdk`. So, that is the preferred solution, but simply removing the `Microsoft.Bcl.Async` is the quick & dirty solution.

**Comment by MiYanni** [comment]
The PR has been merged.
