### ISSUE TITLE
AzureRm.KeyVault - Remove-AzureKeyVaultCertificate does not respect -Force parameter

### ISSUE THREAD

**Issue by eransha** [Azure/azure-powershell#5809]
### Description

AzureRm.KeyVault - Remove-AzureKeyVaultCertificate does not respect -Force parameter hence making unusable in automation - it fails since there is no input available
### Script/Steps for Reproduction

Login-AzureRmAccount
Remove-AzureKeyVaultCertificate -VaultName [vaultName] -Name [CertName] -Force
### Module Version
4.2.0
### Environment Data

```powershell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

 Remove-AzureKeyVaultCertificate -VaultName ### -Name ### -Force
DEBUG: 5:06:36 AM - RemoveAzureKeyVaultCertificate begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 5:06:36 AM - using account id '###'...

Confirm
Are you sure you want to perform this action?
Performing the operation "Remove certificate" on target "fdf".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):

**Comment by markcowl** [comment]
@eransha  This is because that operation is marked as 'High' confirm impact, meaning that you either have to respond to the prompt, or pass ```-Confirm:$false``` in scripts.

Agreed that it is simpler if there is a consistent usage of ShouldContinue prompts in these instances.

@maddieclayton Is this one of the things slated for change at the next major release?

**Comment by maddieclayton** [comment]
Yes, this will be removed in the upcoming breaking change release in early May.  Closing as this PR is already pending here: https://github.com/Azure/azure-powershell/pull/5799

@eransha Thank you for pointing this out, please let us know if you find any other inconsistent behavior that you want us to fix.
