### ISSUE TITLE
GetAzureRmRoleAssignment -ExpandPrincipalGroups doesn't expand groups

### ISSUE THREAD

**Issue by DuncanMillard** [Azure/azure-powershell#5811]
### Description

I'm trying to find out if I, as the currently logged in user, have the Owner role in my current subscription via a group membership.

For example the user is a member of "Resource Access Permissions" group in AAD and "Resource Access Permissions" group has been added as Owner via the Azure Portal -> Subscriptions -> Subscription -> IAM page.

**Expected**
GetAzureRmRoleAssignment -ExpandPrincipalGroups -SignInName <myuser@company.com> returns a record denoting subscription ownership, as I've got access through my group membership.

**Actual**
I don't see the role granted at the subscription scope level (or indeed for any resources within the subscription for which I also have permissions via group membership).

### Script/Steps for Reproduction
```powershell
Get-AzureRmRoleAssignment  -SignInName myalias@microsoft.com -ExpandPrincipalGroups 
```

### Module Version

ModuleType Version    Name                                ExportedCommands                                                                                                                             
---------- -------    ----                                ----------------                                                                                                                             
Script     4.5.0      AzureRM.profile                     {Add-AzureRmEnvironment, Clear-AzureRmContext, Clear-AzureRmDefault, Connect-AzureRmAccount...}                                              
Script     5.5.1      AzureRM.Resources                   {Export-AzureRmResourceGroup, Find-AzureRmResource, Find-AzureRmResourceGroup, Get-AzureRmADAppCredential...}                                
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                                                          
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                                                           
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                                                    
Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}                                                                    
Script     1.0.0.1    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}                                                                        

### Environment Data
Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
### Debug Output

Too much PII - Sent over email to markcowl, or contact dumil directly...

```

```

**Comment by cormacpayne** [comment]
@darshanhs90 Hey Haridarshan, would you mind taking a look at this issue?

**Comment by darshanhs90** [comment]
@somefella123 Can you use the latest powershell version and let me know if the error persists.
So that if it still persists,it will be easier to figure out and rule out the earlier issues with the previous versions

**Comment by somefella123** [comment]
Just to confirm I see the same behaviour on AzureRM.Resources 5.5.1 (the version from Install-Module -Name AzureRM -Repository PSGallery -Force)

**Comment by darshanhs90** [comment]
This has been fixed in https://github.com/Azure/azure-powershell/pull/6588
