### ISSUE TITLE
Validate Compute Tests against live run recording jenkins job

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5817]
### Description

Prepare and validate the usage of the live tests recording Jenkins job against Compute tests

- [x] Update job definition as appropriate to allow running compute (as well as network) tests
- [x] Execute a run and work with compute team to analyze failures
  - [x] Test setup missing
  - [x] Features that should be enabled on the subscription
  - [x] Test or product issues
- [ ] File issues for unresolved test issues and work with compute team to decide whether to fix or delete tests and when fixes will occur.

### Cost: 10

**Comment by praries880** [comment]
Creates a Jenkins job : https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-generic-module-test/ with parameterized module name. Testing it at the moment to see if it works correctly

**Comment by praries880** [comment]
Based  on the [first run](https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-generic-module-test/2/artifact/)

24 tests failed. Failure results [here](https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-generic-module-test/2/artifact/ComputeTests.htm).
