### ISSUE TITLE
Certificate from file without password 

### ISSUE THREAD

**Issue by MattAWilliams** [Azure/azure-powershell#5818]
https://github.com/Azure/azure-powershell/blob/8278e9301047c7aa096f4b08ce9d4f9bf0f1e8a2/src/ResourceManager/KeyVault/Commands.KeyVault/Commands/ImportAzureKeyVaultCertificate.cs#L131-L151

Can't import certificate from file without a password, can only merge pending. Suggest removing Password != null if statement unless this is by design.

**Comment by cormacpayne** [comment]
@maddieclayton would you mind taking a look?

**Comment by maddieclayton** [comment]
@dragav Can you take a look at this bug?

**Comment by dragav** [comment]
https://github.com/Azure/azure-powershell/pull/5864
