### ISSUE TITLE
New-AzureRmVmss/Vm (simple parameter set) should support MSI

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-powershell#5819]
### Description

Adding parameters to be able to enable adding system assigned, user assigned or both types of MSI identities to the VM / VMSS when creating new virtual machines or scale sets.
 

We will be adding the following parameters
```c#
        [Parameter(ParameterSetName = SimpleParameterSet, Mandatory = false, HelpMessage = "Use this to add system assigned identity (MSI) to the vm")]
        public SwitchParameter SystemAssignedIdentity { get; set; }

        [Parameter(ParameterSetName = SimpleParameterSet, Mandatory = false, HelpMessage = "Use this to add the assign user specified identity (MSI) to the VM")]
        public string UserAssignedIdentity { get; set; }
```
to the two cmdlets :
 - [NewAzureRmVmss](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Compute/Commands.Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs)
 - [NewAzureRmVm](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Operation/NewAzureVMCommand.cs)

The user can apply a system assigned identity to the vm/vmss by simply specifying the switch parameter _SystemAssignedIdentity_.

If the user wants to specify  a specific identity to the VM they can use the param _UserAssignedIdentity_ and specify the name of the MIS resource they want to assign to the vm/vmss.

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by sergey-shandar** [comment]
@gatneil @yugangw-msft MSI for VM and VMSS.

**Comment by markcowl** [comment]
Fixed.
