### ISSUE TITLE
Get-AzureRoleSize doesn't report NIC count

### ISSUE THREAD

**Issue by Makovec** [Azure/azure-powershell#582]
Hi,
is it possible to report max NIC count to *Get-AzureRoleSize* output? The same as we have now MaxDataDiskCount? 

Thanks
David & Matous

**Comment by pcgeek86** [comment]
+1 @Makovec 

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by markcowl** [comment]
@Makovec Thank you for the feedback.  Assigning to the appropriate team to investigate.

**Comment by singhkay** [comment]
Get-AzureRoleSize calls the List Role Sizes API but it can't return this value unless API returns this. I've filed a feature request on the compute team. Closing as this isn't purely a PS issue.
