### ISSUE TITLE
SecureExecution not working on Azure Runbook while creating CustomScriptExtension

### ISSUE THREAD

**Issue by KrishnaPaudel** [Azure/azure-powershell#5823]
### Description

Unable to use the -SecureExecution paramenter in Set-AzureRMVMCustomScriptExtension in Azure Runbook
### Script/Steps for Reproduction

Set-AzureRmVMCustomScriptExtension -ResourceGroupName $vm.ResourceGroupName 
                                                                   -VMName $vm.Name 
								   -Location $vm.Location 
								   -FileName $Filename 
								   **-Run $CommandToExecute 
								   -SecureExecution**
								   -ContainerName $ContainerName 
								   -StorageAccountName $StorageAccountName 
								   -StorageAccountKey $StorageAccountKey 
								   -Name $ScriptExtensionName 
								   -TypeHandlerVersion 1.1 
								   -ErrorAction Stop

In the above script, I am trying to pass credentials in **$CommandToExecute** argument which I want it to be secure. For that, I am trying to use **-SecureExecution** parameter. I can successfully use this from native PowerShell but not from Azure Runbook.

Exception I am getting in Azure Runbook:
: A parameter cannot be found that matches parameter name 'SecureExecution'.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable

Unable to get any output while running this on Azure Runbook.
```

### Environment Data

Name                           Value                                                                                    
----                           -----                                                                                    
PSVersion                      5.1.15063.726                                                                            
PSEdition                      Desktop                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
BuildVersion                   10.0.15063.726                                                                           
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1  

```powershell
$PSVersionTable
```

### Debug Output

 
```

```

**Comment by KrishnaPaudel** [comment]
![image](https://user-images.githubusercontent.com/34114687/37964609-bb499308-31df-11e8-8d9e-e577c0009f26.png)

If it is not a bug and cannot be used then,
Is there any other way of passing confidential parameters while using Set-AzureRmVMCustomScriptExtension from Azure Runbook?

**Comment by cormacpayne** [comment]
@danielsollondon would you mind taking a look at this issue?

**Comment by KrishnaPaudel** [comment]
Any updates here?

**Comment by KrishnaPaudel** [comment]
@danielsollondon @cormacpayne 
Could you guys please take a look and let me know if this is expected? Or is this a known issue/bug?

**Comment by KrishnaPaudel** [comment]
Awaiting you ACK on this issue.

**Comment by maddieclayton** [comment]
Please confirm that you are using the latest version of Az (1.2.0) or AzureRM (6.13.1), and open a new issue if you continue to see this issue.  Judging from this information above, it seems likely that you were using an older version of the Compute module (as Automation does not automatically upgrade Azure PowerShell modules), so the parameter in question did not exist in the version of the module that you were using.
