### ISSUE TITLE
Set-AzureRmWebApp -HostNames doesn't support root domains

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-powershell#5824]
### Description

The Powershell command Set-AzureRmWebApp -Name $webappname -ResourceGroupName $webappname `
-HostNames @(domain1, domain2, etc) only works for Subdomains which are registered on the DNS server with a CNAME. If you configure your root domain(contoso.com) with an A record the above command will not add the root domain.

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by vladimir-shcherbakov** [comment]
@panchagnula, Could you take a look?

**Comment by panchagnula** [comment]
@ahmedelnably is this something we support when we use resources.azure.com? Given the command just calls the API here to update the setting - I am not sure if this should be a client issue. Thanks!

**Comment by panchagnula** [comment]
closing this since I haven't heard anything back on this.
