### ISSUE TITLE
webapp: Edit-AzureRmWebAppBackupConfiguration always sets Enabled to True

### ISSUE THREAD

**Issue by Nking92** [Azure/azure-powershell#5833]
### Description

The Edit-AzureRmWebAppBackupConfiguration cmdlet will always set the backup configuration with enabled = true, even if the supplied configuration has enabled = false. There are scenarios where a user might need to edit the backup configuration without actually enabling it. Here, "enabled" means that web app backups will be processed based on the configured schedule.

The root cause is that enabled = true is hardcoded in the cmdlet code. We should expose it as a switch parameter instead.

### Script/Steps for Reproduction

```powershell
$app = Get-AzureRmWebApp -Name MyApp
$config = $app | Get-AzureRmWebAppBackupConfiguration
$config | Edit-AzureRmWebAppBackupConfiguration
```

### Module Version

Websites Preview 5.0.0.0, plus prior versions

**Comment by doodlleus** [comment]
is this still the case? this is leading to a lot of unnecessary costs for my customers

**Comment by panchagnula** [comment]
@Nking92 can you update this issue please?

**Comment by panchagnula** [comment]
@Nking92 can you check if we still repo this?

**Comment by panchagnula** [comment]
Looking at this with Nick's help this still exists & the fix should be to add a new boolean parameter to toggle the  backupConfiguration https://docs.microsoft.com/en-us/powershell/module/Az.Websites/Edit-AzWebAppBackupConfiguration?view=azps-2.6.0

**Comment by ThejaChoudary** [comment]
Taking a look at this.

**Comment by Kotasudhakarreddy** [comment]
@NitashaV this is still present, and the fix should be added as a new boolean parameter to toggle between `true` and `false`.
