### ISSUE TITLE
Documentation for Set-AzureRmSqlDatabase misses to document parameter MaxSizeGB

### ISSUE THREAD

**Issue by meetamitbhatia** [Azure/azure-powershell#5836]
Documentation for Set-AzureRmSqlDatabase defines MaxSizeBytes as:
“Specifies the new maximum size for the database in bytes. You can specify either this parameter or MaxSizeGB. See the MaxSizeGB parameter for acceptable values per edition.”

However, there is no MaxSizeGB parameter defined on this page, and there is nothing on this page that provides the information about acceptable values.

**Comment by vladimir-shcherbakov** [comment]
@akromm Could you take a look?

**Comment by nathannfan** [comment]
This parameter is defined here: https://github.com/Azure/azure-powershell/blob/preview/src/ServiceManagement/Sql/Commands.SqlDatabase/Database/Cmdlet/SetAzureSqlDatabase.cs#L136

Perhaps we need to regenerate our documentation.  @vladimir-shcherbakov , any idea whom we contact to update that?

**Comment by markcowl** [comment]
@nathannfan ALl you need to do is update the documentation in the repo, and it will automatically be picked up at the next release.  See: https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md for instructions

**Comment by nathannfan** [comment]
@markcowl This is in our markdown file, https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Sql/Commands.Sql/help/Set-AzureRmSqlDatabase.md, but re-generating through PlatyPS didn't change it, and I don't see the string anywhere in our code.  Is this pulling directly from the Documentation tag of the MaxSizeBytes Property?

**Comment by nathannfan** [comment]
Pull request to fix this: https://github.com/Azure/azure-powershell/pull/5839

**Comment by maddieclayton** [comment]
Fixed, and will be included in the next release. Closing.
