### ISSUE TITLE
Cannnot login to AzureRM Account from Mac PowerShell

### ISSUE THREAD

**Issue by bmanikm** [Azure/azure-powershell#5856]
_From @pkbelidha on March 31, 2018 23:11_

_Copied from original issue: PowerShell/PowerShellGet#252_

**Comment by bmanikm** [comment]
@vladimir-shcherbakov This issue was initially created in PowerShell/PowerShellGet repo. I moved it to the correct repository. Please work with @pkbelidha to get the required data to investigate this issue.

**Comment by vladimir-shcherbakov** [comment]
@pkbelidha Could you please provide more info or create a new issue in this repo and fill out the entry form?

**Comment by markcowl** [comment]
Any mac login issues should be resolved in the version that will be released next week (week of 5/9).  Closing.
