### ISSUE TITLE
NetCore 0.11.0 issues

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5858]
- [ ] `New-AzureRmAutomationRunbook` DLL loading issue
![image](https://user-images.githubusercontent.com/17788297/38222383-474a1202-3699-11e8-97aa-da7884b3cccc.png)
- [ ] `New-AzureRmSqlDatabase` unexpected character issue
![image](https://user-images.githubusercontent.com/17788297/38401309-d60ea8c8-3909-11e8-80a2-624f733290b4.png)
  - The database is still generated, but that error occurs anyway.

**Comment by markcowl** [comment]
Fixed.
