### ISSUE TITLE
Set-AzureRmAutomationConnectionFieldValue cmdlet is adding double quotes to the field value

### ISSUE THREAD

**Issue by webbermt** [Azure/azure-powershell#5862]
### Description

The Set-AzureRmAutomationConnectionFieldValue cmdlet is adding double quotes to the field value.  In the debug output you will notice that it's adding \" around the field value.  

### Script/Steps for Reproduction

Set-AzureRmAutomationConnectionFieldValue -Name BLAH -ConnectionFieldName SubscriptionId -Value ABC -ResourceGroupName myRg -AutomationAccountName myAutoBlah

### Module Version

Script     4.3.1      AzureRM.Automation
Script     4.5.0      AzureRM.profile 

### Environment Data

Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Debug Output

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com/subscriptions/_subscriptionid_/resourceGroups/_resourcegroup_/providers/Microsoft.Automation/automationAccounts/_accountname_/connections/BLAH?api-version=2015-10-31

Headers:
Accept                        : application/json
x-ms-version                  : 2014-06-01

Body:
{
  "name": "BLAH",
  "properties": {
    "fieldDefinitionValues": {
      "SubscriptionId": "\"ABC\"",
      "ApplicationId": "blahblah",
      "TenantId": "blahblah",
      "CertificateThumbprint": "blahblah"
    }
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : 2a4a4d59-28e9-4ca9-adc6-56bcee50ec22
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 3b6a4845-b7e7-4da1-82fb-4cb9468af9d1
x-ms-routing-request-id       : EASTUS:20180403T155107Z:3b6a4845-b7e7-4da1-82fb-4cb9468af9d1
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 03 Apr 2018 15:51:06 GMT
Server                        : Microsoft-IIS/8.5
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/_subscriptionid_/resourceGroups/_resourcegroup_/providers/Microsoft.Automation/automationAccounts/_accountname_/connections/BLAH",
  "name": "BLAH",
  "type": "Microsoft.Automation/AutomationAccounts/Connections",
  "properties": {
    "creationTime": "2017-04-17T17:35:02.753-04:00",
    "lastModifiedTime": "2018-04-03T11:51:07.36-04:00",
    "description": null,
    "fieldDefinitionValues": {
      "SubscriptionId": "\"ABC\"",
      "ApplicationId": "blahblah",
      "TenantId": "blahblah",
      "CertificateThumbprint": "blahblah"
    },
    "connectionType": {
      "name": "AzureServicePrincipal"
    }
  }
}

**Comment by ChrisOwczarek** [comment]
The added quotes actually cause the field values to become invalid. In my case, adding quotes to the thumbprint value make the thumbprint no longer valid.  Removing the quotes manually through portal makes the connection work again.

**Comment by lokeshgupta13** [comment]
Do we have any workaround for this issue or fix coming in?

**Comment by ChrisOwczarek** [comment]
Depending on your scenario, you could delete and re-create the connection (use Remove-AzureRmAutomationConnection and then New-AzureRmAutomationConnection).

**Comment by sourabhguha** [comment]
Varad – connections are owned by Jeff. Can you please assign to him. I don’t know what his github handle is.

**Comment by vrdmr** [comment]
Sure. I'll do that. Thanks.

**Comment by zanecodes** [comment]
This is due to https://github.com/Azure/azure-powershell/blob/master/src/Automation/Automation/Common/AutomationPSClient.cs#L1214.

`PowerShellJsonConverter.Serialize(value)` receives `value` as a string, which it correctly serializes as the literal string `"\"[string contents]"\"`. If connection field values can only be strings, then `PowerShellJsonConverter.Serialize` should not be used; otherwise, they should have a special case for `string` values.

**Comment by craigeaw** [comment]
Any updates on this?  The workaround of removing and re-creating the connection is fine, but the ability to use the set cmdlet would be preferred.

**Comment by ikanni** [comment]
Thank you for reporting this issue.  I am sorry, we won't be fixing this issue. I am closing this request.

At this point the workaround is removing and re-creating the connection.

**Please follow the below steps for workaround**

You can work around this issue by get, update applicationId, delete and create new. Please check the below. I am sorry about lot of lines of code.  I could not find a very good workaround.

$ConnectionTypeName = "AzureServicePrincipal"

# Get connection
$connectionAsset=Get-AzureRMAutomationConnection -Name $ConnectionAssetName -AutomationAccountName $AutomationAccountName -ResourceGroupName $ResourceGroup

# Update applicationId
$connectionAsset.FieldDefinitionValues.ApplicationId = $applicationId

# Delete connection
Remove-AzureRmAutomationConnection  -Name $ConnectionAssetName -AutomationAccountName $AutomationAccountName -ResourceGroupName $ResourceGroup -Force -ErrorAction SilentlyContinue

# Create new connection with same name
New-AzureRmAutomationConnection -ResourceGroupName $ResourceGroup -AutomationAccountName $AutomationAccountName -Name $ConnectionAssetName -ConnectionTypeName $connectionTypeName -ConnectionFieldValues $connectionAsset.FieldDefinitionValues

# Validate the update
$connectionAssetUpdated=Get-AzureRMAutomationConnection -Name $ConnectionAssetName -AutomationAccountName $AutomationAccountName -ResourceGroupName $ResourceGroup
$connectionAssetUpdated.FieldDefinitionValues

**Comment by andreesteve** [comment]
I see the commits referencing this issue. Do we know what is the release that has the fix in it?

**Comment by ikanni** [comment]
@andreesteve  Please use Az.Automation -RequiredVersion 1.3.0

**Comment by andyw248** [comment]
Fixed.
