### ISSUE TITLE
New-AzureRmVm/Vmss: Scenario test debt

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-powershell#5873]
### Description

New-AzureRmVm/Vmss: Scenario test debt
- [ ] ImageName as 
  - [ ] an id,
  - [ ] a name of id in the same resource group
- [x] DataDisks
- [ ] Zones

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by sergey-shandar** [comment]
@gatneil could you help with automating image creations.

**Comment by gatneil** [comment]
@sergey-shandar I thought you had some initial scripts, right? Did those not work out?

**Comment by sergey-shandar** [comment]
@gatneil it's not stable because during sysprep generalization sometimes an agent became irresponsive, even if we do `quit` instead of `shutdown`. My current idea is to run sysprep in background so the agent can report `done`. Then, we will need to wait when the machine is shutdown.

**Comment by sergey-shandar** [comment]
Data Disk scenario test is here #5867
