### ISSUE TITLE
ARM: Get-AzureResourceGroupGalleryTemplate does not work

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-powershell#589]
PS C:\windows\system32> Get-AzureResourceGroupGalleryTemplate
Get-AzureResourceGroupGalleryTemplate : An error occurred while sending the request.
At line:1 char:1
+ Get-AzureResourceGroupGalleryTemplate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureResourceGroupGalleryTemplate], HttpRequestExcept 
   ion
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.Templates.GetAzureResourceGroupGalleryT 
   emplateCommand

**Comment by vivsriaus** [comment]
@bingosummer Can you please install the latest powershell version and retry? I don't see this issue.
