### ISSUE TITLE
AzureRM.Netcore - Get-AzureRMVMImage not providing ImageName property to create VM

### ISSUE THREAD

**Issue by MaximoTrinidad** [Azure/azure-powershell#5892]
### Description

I got a concern in regards to a documentation sample of creating an AzureRM VM where it's using the "ImageName" in order to create build the Windows Server.  

The sample works as long as you only create a Windows Server using the provided _"ImageName = 'Win2016Datacenter'"_.

But, I can't find no documentation in how to extract the property **ImageName** from the **Get-AzureRMVMImage** cmdlet.  

I'm trying to find the **ImageName** for all other OS's, specially _**WindowsDesktop**_.

I would appreciate the help is someone can point me in the right direction. I'm building a lab to run AzureRM.Netcore in Linux for the Global Azure Boot Camp (Boca, FL) this month.

### Script/Steps for Reproduction

Below is the example provided in the Azure Docs: https://docs.microsoft.com/en-us/powershell/azure/azureps-vm-tutorial?view=azurermps-5.6.0&WT.mc_id=docsmsft-twitter#step-4 

It works! But I want to know how to get the **ImageName** property for Windows 10.
```
$vm1Params = @{
	ResourceGroupName    = 'TutorialResources'
	Name				 = 'Win2k16VM1'
	Location			 = 'eastus'
	ImageName		     = 'Win2016Datacenter'
	PublicIpAddressName  = 'tutorialPublicIp'
	Credential		     = $MyCred
	OpenPorts		     = 3389
}
$newVM1 = New-AzureRmVM @vm1Params
```
The Get-AzureRmVMImage Cmdlet doesn't have the ImageName property:
```
PS /home/maxt> Get-AzureRmVMImage `                                                                                     >>    -Location "East US" `                                                                                             >>    -PublisherName "MicrosoftWindowsDesktop" `                                                                        >>    -Offer "Windows-10" `                                                                                             >>    -Skus 'RS3-Pro'| Format-table

Version     FilterExpression Skus    Offer      PublisherName           Location Id
-------     ---------------- ----    -----      -------------           -------- --
16299.248.1                  RS3-Pro Windows-10 MicrosoftWindowsDesktop eastus   /Subscriptions/606ba8bb-2f0e-4ebb-8...
```
It would be a nice to have property. 

### Module Version

```powershell
PS /home/maxt> Get-Module -Name AzureRM.* -ListAvailable | Select name, version

Name                      Version
----                      -------
AzureRM.Compute.Netcore   0.10.0
AzureRM.KeyVault.Netcore  0.10.0
AzureRM.Netcore           0.10.0
AzureRM.Network.Netcore   0.10.0
AzureRM.Profile.Netcore   0.10.0
AzureRM.Resources.Netcore 0.10.0
AzureRM.Storage.Netcore   0.10.0
AzureRM.Tags.Netcore      0.10.0
AzureRM.Websites.Netcore  0.10.0

```

### Environment Data

```powershell
PS /home/maxt> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Linux 4.4.0-17133-Microsoft #1-Microsoft Fri Mar 23 13:12:00 PST 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### Debug Output

```

```

**Comment by markcowl** [comment]
@MaximoTrinidad The Get-AzureRMVMIamge cmdlet does not return strings that are used with the New-AzureRMVM ImageName parameter.  This is being tracked here: #5882 

Meanwhile, you can use the tab completer in New-AzureRmVM to tab through the most populare image names.

**Comment by MaximoTrinidad** [comment]
@markcowl 

Ok! Sorry for not explaining better but I know that Get-AzureRMVMImage will not return the ImageName string.

I'm looking for an explanation where it was gotten for the example provided in the documentation. (See link URL)

**_You're closing this before giving an explanation!_** And, I don't think this is a duplicate issue at all.

How the example script works providing the **ImageName** string 'Win2016Datacenter'?

:(

**Comment by MaximoTrinidad** [comment]
@markcowl !

Apologies!  I talked to @joeyaiello  and he explained to me what's going on.  

Now, I understand about the marketplace issue.

So, Joey found the answer I was looking for...  End up been the "ImageName" shorthand came from the Azure Cli command:
```
az vm image list
:
 {
    "offer": "WindowsServer",
    "publisher": "MicrosoftWindowsServer",
    "sku": "2016-Datacenter",
    "urn": "MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest",
    "urnAlias": "Win2016Datacenter",
    "version": "latest"
  },
:
```
So, the UrlAlias is missing from the Get-AzureRMVMImage cmdlet.

Got my answer!  

Thanks for your patience,
Max
