### ISSUE TITLE
Fix PSCmdlet properties without setters in AsJob scenarios

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5896]
### Description

Some properties (dynamic parameters, SessionState.Path) are not copied into the target cmdlet when creating a cmdlet copy when executed using AsJon.

- [ ] Identify properties with no setters in PSCmdlet that are used by our cmdlets (at least SessioNState.Path, and DynamicParameters
- [ ] For each property, create a common code mechanism for accessing the exposed functionality in ProcessRecord, and ensure that this functionality is transferred in when copying the cmdlet in AzureLongRunningJob
- [ ] Write unit tests for verifying access to these properties in jobs
- [ ] Find all usages of theese properties and transfer to the common code mechanism
- [ ] Verify that associated issues are properly addressed:
  - [ ] #5502 
  - [ ] #5548 

### Cost: 6

**Comment by maddieclayton** [comment]
Fixed.

**Comment by v-tisheg** [comment]
This is marked as fixed.  Does that mean that the Invoke-AzureRmVMRunCommand using the -AsJob parameter should now work in the production environment or just that the fix is now ready to be released as part of the Milestone 5/01 release?  

I just need to know whether I can tell my customer to give this a try.

**Comment by maddieclayton** [comment]
Yes! The fix has been released, please let me know if your customers continue to see an issue (be sure to use the latest version of AzureRM).

**Comment by v-tisheg** [comment]
My Customer just tried using the -ASJob on his command and he says:

Can you test on your end? The job seems stuck in a running state. I did a simple write-host $env:computername for my powershell script I passed in. 

I will try to get the exact syntax he used.

**Comment by maddieclayton** [comment]
@v-tisheg Please open a new issue with all the relevant issue if you can get the exact syntax he used

**Comment by v-tisheg** [comment]
Thank you, will do.

Timothy Shegrud

Support Engineer
Cloud & Infrastructure Solutions
Customer Services & Support | Microsoft Corporation
(425) 706-4408; * v-tisheg@microsoft.com<mailto:v-tisheg@microsoft.com> | Hours: Sun - Thur, 8:00am-5:00pm PST
Need help outside of my working hours for a technical issue?
*: AzBackup@microsoft.com<mailto:AzBackup@microsoft.com>

Meeting and exceeding your expectations are my top priorities. We are interested in any feedback you might have about the service you received on this incident.  Please let my Manager, Martin Rosales know what you think of the level of service provided, by contacting him via email at v-rosmar@microsoft.com<mailto:v-rosmar@microsoft.com>.

[cid:image001.png@01D2DECD.52D68C60]    [cid:image002.jpg@01D2DECD.52D68C60]

**Comment by v-tisheg** [comment]
Please see https://github.com/Azure/azure-powershell/issues/6205

Timothy Shegrud

Support Engineer
Cloud & Infrastructure Solutions
Customer Services & Support | Microsoft Corporation
(425) 706-4408; * v-tisheg@microsoft.com<mailto:v-tisheg@microsoft.com> | Hours: Sun - Thur, 8:00am-5:00pm PST
Need help outside of my working hours for a technical issue?
*: AzBackup@microsoft.com<mailto:AzBackup@microsoft.com>

Meeting and exceeding your expectations are my top priorities. We are interested in any feedback you might have about the service you received on this incident.  Please let my Manager, Martin Rosales know what you think of the level of service provided, by contacting him via email at v-rosmar@microsoft.com<mailto:v-rosmar@microsoft.com>.

[cid:image001.png@01D2DECD.52D68C60]    [cid:image002.jpg@01D2DECD.52D68C60]
