### ISSUE TITLE
Remove adapter code for Argument Completers

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5897]
### Description

- [x] Update all cmdlet references to S.M.A 5.1
- [x] Change existing argument completers to extend the SMA 5.1 ArgumentCompleter attribute
- [x] Remove code from build scripts that injects script argument completers for cmdlets
- [x] Add new minimum PS version to psd1 definitions
- [x] Validate argument completers with new signed build

### Cost: 6

**Comment by maddieclayton** [comment]
Merged.
