### ISSUE TITLE
Track intended breaking changes

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5898]
### Description

Go through existing plans for breaking changes and existing breaking change warnings in the codebase and
- [ ] Ensure that there is a good upcomign breaking change document for each
- [ ] Work with feature teams (and us) to ensure that breaking changes are made (list each here:
  - [ ] Remove ServerManagement cmdlets
  - [ ] Remove SiteRecovery cmdlets

### Cost: 8

**Comment by cormacpayne** [comment]
- ServerManagement removed in PR https://github.com/Azure/azure-powershell/pull/5913
- SiteRecovery removed in PR https://github.com/Azure/azure-powershell/pull/5962

**Comment by cormacpayne** [comment]
Full list of potential breaking changes:

ApiManagement
- New-AzureRmApiManagement
	- The parameter alias Tags is being removed
- New-AzureRmApiManagementProperty
	- The parameter alias Tags is being removed
- Set-AzureRmApiManagementProperty
	- The parameter alias Tags is being removed

Automation
- Set-AzureRmAutomationRunbook
	- The parameter alias Tags is being removed

Cdn
- New-AzureRmCdnEndpoint
	- The parameter alias Tags will be removed
- New-AzureRmCdnProfile
	- The parameter alias Tags will be removed

CognitiveServices
- PSCognitiveServicesAccount
	- The property ProvisioningState is being deprecated

Compute
- New-AzureRmAvailabilitySet
	- The parameter Managed is being deprecated in favor of Sku
- New-AzureRmVM
	- The parameter alias Tags is being removed
- Set-AzureRmVMAEMExtension
	- The parameter DisableWAD is being deprecated
- Update-AzureRmVM
	- The parameter alias Tags is being removed

DataFactories
- New-AzureRmDataFactories
	- The parameter alias Tags is being removed
- New-AzureRmDataFactoryGatewayKey
	- The cmdlet is deprecated in favor of New-AzureRmDataFactoryGatewayAuthKey

DataLakeAnalytics
- PSDataLakeAnalyticsAccountBasic
	- A lot of properties are being removed
- PSJobInformationBasic
	- A lot of properties are being removed
- New-AzureRmDataLakeAnalyticsAccount
	- The parameter alias Tags is being removed
- New-AzureRmDataLakeAnalyticsCatalogSecret
	- The cmdlet is being deprecated in favor of New-AzureRmDataLakeAnalyticsCatalogCredential
- Remove-AzureRmDataLakeAnalyticsCatalogSecret
	- The cmdlet is being deprecated in favor of Remove-AzureRmDataLakeAnalyticsCatalogCredential
- Set-AzureRmDataLakeAnalyticsAccount
	- The parameter alias Tags ie being removed
- Set-AzureRmDataLakeAnalyticsCatalogSecret
	- The cmdlet is being deprecated in favor of Set-AzureRmDataLakeAnalyticsCatalogCredential

DataLakeStore
- PSDataLakeStoreAccountBasic
	- A lot of properties are being removed
- Export-AzureRmDataLakeStoreItem
	- The parameter PerFileThreadCount is being deprecated in favor of Concurrency
	- The parameter ConcurrentFileCount is being deprecated in favor of Concurrency
- Import-AzureRmDataLakeStoreItem
	- The parameter PerFileThreadCount is being deprecated in favor of Concurrency
	- The parameter ConcurrentFileCount is being deprecated in favor of Concurrency
- New-AzureRmDataLakeStoreAccount
	- The parameter alias Tags is being removed
- Remove-AzureRmDataLakeStoreItem
	- The parameter Clean is being deprecated
- Set-AzureRmDataLakeStoreAccount
	- The parameter alias Tags is being removed

Dns
- New-AzureRmDnsRecordSet
	- The parameter Force is being deprecated in favor of Confirm
- New-AzureRmDnsZone
	- The output type of this cmdlet is changing
- Remove-AzureRmDnsRecordSet
	- The parameter Force is being deprecated in favor of Confirm
- Remove-AzureRmDnsZone
	- The parameter Force is being deprecated in favor of Confirm
- Set-AzureRmDnsZone
	- The output type of this cmdlet is changing

Insights
- Add-AzureRmAlert
	- The plural parameter aliases are being deprecated
- Add-AzureRmAutoscaleSetting
	- The plural parameter aliases are being deprecated
- Add-AzureRmLogProfile
	- The plural parameter aliases are being deprecated
- Get-AzureRmAlertHistory
	- The parameter DetailedOutput is being deprecated
	- The parameter EventChannels is being deprecated
- Get-AzureRmAlertRule
	- The parameter DetailedOutput is being deprecated
- Get-AzureRmAutoscaleHistory
	- The parameter DetailedOutput is being deprecated
	- The parameter EventChannels is being deprecated
- Get-AzureRmAutoscaleSetting
	- The parameter DetailedOutput is being deprecated
- Get-AzureRmLog
	- The plural parameter aliases are being deprecated
	- The parameter DetailedOutput is being deprecated
	- The parameter EventChannels is being deprecated
- Get-AzureRmMetric
	- The parameter DetailedOutput is being deprecated
- Get-AzureRmMetricDefinition
	- The plural parameter aliases are being deprecated
	- The parameter DetailedOutput is being deprecated
- New-AzureRmAlertRuleEmail
	- The plural parameter aliases are being deprecated
- New-AzureRmAlertRuleWebook
	- The plural parameter aliases are being deprecated
- New-AzureRmAutoscaleNotification
	- The plural parameter aliases are being deprecated
- New-AzureRmAutoscaleProfile
	- The plural parameter aliases are being deprecated
- New-AzureRmAutoscaleWebhook
	- The plural parameter aliases are being deprecated

KeyVault
- PSKeyVaultKeyAttribute
	- The property PurgeDisabled is being deprecated in favor of RecoveryLevel
- PSKeyVaultKeyIdentityItem
	- The property PurgeDisabled is being deprecated in favor of RecoveryLevel
- PSKeyVaultSecretAttributes
	- The property PurgeDisabled is being deprecated in favor of RecoveryLevel
- Set-AzureKeyVaultManagedStorageSasDefinition
	- The parameter Parameter is being deprecated in favor of TemplateUri and SasType

MachineLearning
- Update-AzureRmMlCommitmentPlan
	- The parameter alias Tags is being removed

Media
- Set-AzureRmMediaService
	- The parameter alias Tags is being removed

Network
- PSApplicationGatewayBackendHttpSettings
	- The property ProbeEnabled is being deprecated
- Add-AzureRmApplicationGatewayBackendHttpSettings
	- The parameter ProbeEnabled is being deprecated
- Add-AzureRmVirtualNetworkPeering
	- The parameter alias AlloowGatewayTransit is being removed
	- The output type of this cmdlet is changing
- New-AzureRmApplicationGateway
	- The output type of this cmdlet is changing
- New-AzureRmApplicationGatewayBackendHttpSettings
	- The parameter ProbeEnabled is being deprecated
- New-AzureRmExpressRouteCircuit
	- The output type of this cmdlet is changing
- New-AzureRmLoadBalancer
	- The output type of this cmdlet is changing
- New-AzureRmLocalNetworkGateway
	- The output type of this cmdlet is changing
- New-AzureRmNetworkInterface
	- The output type of this cmdlet is changing
- New-AzureRmNetworkSecurityGroup
	- The output type of this cmdlet is changing
- New-AzureRmPublicIpAddress
	- The output type of this cmdlet is changing
- New-AzureRmRouteFilter
	- The output type of this cmdlet is changing
- New-AzureRmVirtualNetwork
	- The output type of this cmdlet is changing
- New-AzureRmVirtualNetworkGateway
	- The output type of this cmdlet is changing
- Set-AzureRmApplicationGatewayBackendHttpSettings
	- The parameter ProbeEnabled is being deprecated

NotificationHubs
- New-AzureRmNotificationHubsNamespace
	- The parameter alias Tags is being removed
- Set-AzureRmNotificationHubsNamespace
	- The parameter alias Tags is being removed

OperationalInsights
- New-AzureRmOperationalInsightsSavedSearch
	- The parameter alias Tags is being removed
- New-AzureRmOperationalInsightsWorkspace
	- The parameter alias Tags is being removed
- Set-AzureRmOperationalInsightsSavedSearch
	- The parameter alias Tags is being removed
- Set-AzureRmOperationalInsightsWorkspace
	- The parameter alias Tags is being removed

RecoveryServices.Backup
- Get-AzureRmRecoveryServicesBackupContainer
	- The parameter Name is being deprecated in favor of FriendlyName

RedisCache
- New-AzureRmRedisCache
	- The parameter MaxMemoryPolicy is being deprecated in favor of RedisConfiguration
	- The parameter RedisVersion is being deprecated
	- The parameter Subnet is being deprecated in favor of SubnetId
	- The parameter VirtualNetwork is being deprecated in favor of SubnetId
- Set-AzureRmRedisCache
	- The parameter MaxMemoryPolicy is being deprecated in favor of RedisConfiguration

Resources
- Find-AzureRmResource
	- This cmdlet will be deprecated in favor of Get-AzureRmResource
- Find-AzureRmResourceGroup
	- This cmdlet will be deprecated in favor of Get-AzureRmResourceGroup

Sql
- Get-AzureRmSqlDatabaseAuditingPolicy
	- This cmdlet is being deprecated in favor of Get-AzureRmSqlDatabaseAuditing
- Get-AzureRmSqlServerAuditingPolicy
	- This cmdlet is being deprecated in favor of Get-AzureRmSqlServerAuditing
- Get-AzureRmSqlServerServiceObjective
	- The parameter DatabaseName is being deprecated
- Get-AzureRmSqlServerUpgrade
	- This cmdlet is being deprecated
- Remove-AzureRmSqlDatabaseAuditing
	- This cmdlet is being deprecated in favor of Set-AzureRmSqlDatabaseAuditing
- Remove-AzureRmSqlServerAuditing
	- This cmdlet is being deprecated in favor of Set-AzureRmSqlServerAuditing
- Set-AzureRmSqlDatabaseAuditingPolicy
	- This cmdlet is being deprecated in favor of Set-AzureRmSqlDatabaseAuditing
- Set-AzureRmSqlDatabaseDataMaskingPolicy
	- The parameter PrivilegedLogins is being deprecated in favor of PrivilegedUsers
- Set-AzureRmSqlServerAuditingPolicy
	- This cmdlet is being deprecated in favor of Set-AzureRmSqlServerAuditing
- Start-AzureRmSqlServerUpgrade
	- This cmdlet is being deprecated
- Stop-AzureRmSqlServerUpgrade
	- This cmdlet is being deprecated
- Use-AzureRmSqlServerAuditingPolicy
	- This cmdlet is being deprecated in favor of Set-AzureRmSqlDatabaseAuditing

Storage
- New-AzureRmStorageAccount
	- The parameter EnableEncryptionService is being deprecated
- Set-AzureRmStorageAccount
	- The parameter EnableEncryptionService is being deprecated
	- The parameter DisableEncryptionService is being deprecated
