### ISSUE TITLE
Fix module dependency issues for non-included modules

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5899]
### Description

A few modules were not included in the 0.11.0 drop due to unresolvable dependency issues, fix these issues and release the modules ASAP:

- [ ] RecoveryServices.* cmdlets (multiple dependencies)

### Cost: 2

**Comment by MiYanni** [comment]
- HDInsight has a merged HyakNetCore library for HDInsightJob that will need to be built and published prior to fixing the module
- RecoveryServices cannot be fixed without changing the implementation to no longer rely on self-signed certificates being generated during cmdlet invocation. More details here: https://github.com/Azure/azure-powershell/issues/5756

**Comment by MiYanni** [comment]
Closing since HDInsight was handled (republish of HDInsightJob). The other problem has an issue created already.
