### ISSUE TITLE
Error running command Install-Module -Name AzureRM.....Import-Module : File C:\Program Files\WindowsPowerShell\Modules\AzureRM.Profile\4.5.0\AzureRM.Profile.psm1 cannot be loaded

### ISSUE THREAD

**Issue by swatiraut14** [Azure/azure-powershell#5906]
### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by markcowl** [comment]
@swatiraut14 Can you please provide more data about what commands you are running and wht the error you are seeing is?

Please at least include

- The command(s) you are running that produce a failure
- The exact text of the failure
- The result of running Resolve-AzureRmError after the failure (if available)
- If this is a module loading issue, the resul;t of running ```gmo -ListAvailable```

**Comment by markcowl** [comment]
Closing as there has been no response to queries.  Please open a new issue with the requested data if you are still seeing an issue.
