### ISSUE TITLE
Implement certificate-based service principal authentication support in AzureRM.Netcore

### ISSUE THREAD

**Issue by yochaude** [Azure/azure-powershell#5910]
### Description

Latest release of the AzureRM.Netcore module does not support certificate-based service principal authentication.

I don't know if ADAL supports it already, but an [exception is thrown anyway](https://github.com/Azure/azure-powershell/blob/8b467df53bf1b79144afb1250221ec7e6b3a8b44/src/Common/Commands.Common.Authentication/Factories/AuthenticationFactory.cs#L112).

### Script/Steps for Reproduction

```powershell
Add-AzureRmAccount -ServicePrincipal -TenantId mytenant -ApplicationId myapplication -CertificateThumbprint mythumbprint
Add-AzureRmAccount : Certificate based authentication is not supported in netcore version.
At line:1 char:1
+ Add-AzureRmAccount -ServicePrincipal -TenantId mytenant -ApplicationI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], NotSupportedException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand
```

### Module Version

```powershell
Get-Module -Name AzureRM.Netcore -ListAvailable


    Directory: /usr/local/share/powershell/Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   0.10.0     AzureRM.Netcore
```

### Environment Data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Linux 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by cormacpayne** [comment]
@yochaude Hey Yoann, we don't quite have a mechanism in .NET Core to retrieve local certificates. We are looking to enable this functionality by the time the `AzureRM.Netcore` modules GA (as there are other stable modules we package with `AzureRM.Netcore` that use this certificate retrieval functionality). We will use this issue to track the progress on this work moving forward.

**Comment by markcowl** [comment]
### Description
Create a simple capability for login with a certificate, this would include:
- [ ] Supporting the certificate store where it is available
- [ ] Adding parameters to allow specifying an X509Certificate2 on the command line
- [ ] Adding a parameter set to use a certificate from standard certificate file formats (.pem, .cer, etc)
- [ ] Persisting the certificate reference for certifcates outside the certificate store

### Estimated Cost: 12

**Comment by cormacpayne** [comment]
Proposed fix found in PR https://github.com/Azure/azure-powershell/pull/7727

**Comment by cormacpayne** [comment]
This will be available in the next release of `Az` (2018-11-20). More information about cross-platform certificate authentication can temporarily be found here: https://gist.github.com/cormacpayne/6f15ce9bdaf6edc1d7b11c52bb924c44
