### ISSUE TITLE
Missing documentation on an equivalent in REST API for Move-AzureReservedIP cmdlet

### ISSUE THREAD

**Issue by meetamitbhatia** [Azure/azure-powershell#5924]
Customer wants to automate the migration of Classic environments to ARM, part of which includes migrating a few public IP addresses from Classic to ARM.
We see that there's documentation for Move-AzureReservedIP PowerShell cmdlet at https://docs.microsoft.com/en-us/powershell/module/azure/move-azurereservedip?view=azuresmps-4.0.0, but we could not find any documentation on the equivalent in the REST API. We had to Debug Move-AzureReservedIP cmdlet to confirm REST API,
https://management.core.windows.net/3a0ecc28-a2ef-4d17-ac52-01f0c4884841/services/networking/reservedips/testmoveip/migration?comp=prepare

Can we document above REST API?

**Comment by maddieclayton** [comment]
We do not have complete documentation on RDFE REST API.  Please either use the PowerShell cmdlet, or the equivalent cmdlet in XPlat CLI. @twitchax Can you confirm that we do not want to add documentation for this migration scenario?

**Comment by meetamitbhatia** [comment]
@maddieclayton : Hi Maddie, could you please confirm progress on this request?

**Comment by twitchax** [comment]
@meetamitbhatia, I will pass on this request to the ARM team, but a resolution to this request is unlikely since ASM is so heavily deprioritized.  Closing and following up with ARM.
