### ISSUE TITLE
storageAccountType::allowedValues::Standard_GRS needs updated to Premium_LRS

### ISSUE THREAD

**Issue by aljo-microsoft** [Azure/azure-powershell#5927]
### Description

Template has an invalid allowed value, and is missing a valid value.

### Script/Steps for Reproduction

File that needs to be changed on line 116:

https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Template/Windows/template.json

Reference document for allowed values: 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.manageddiskparameters?view=azure-dotnet

and affects New-AzureRmServiceFabricCluster powershell function

https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/ServiceFabric/Commands.ServiceFabric/Commands/NewAzureRmServiceFabricCluster.cs

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by cormacpayne** [comment]
@juhacket Hey Justin, would you mind taking a look at this issue?

**Comment by juhacket** [comment]
@aljo-microsoft The default value is Standard_LRS, which is a supported storage account type value and used by the New-AzureRmServiceFabricCluster cmdlet. This will not impact customers as they would need to modify the template to change the value used by the cmdlet, which would also allow them to specify Premium_LRS. We will cleanup the bad enum value in our next template update.
