### ISSUE TITLE
webapp:Create the equivalent of Save-AzureWebSiteLog, in App Service ARM module

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-powershell#5941]
We don't have the equivalent of Save-AzureWebSiteLog under our AzureRM App Service module

**Comment by jrochet** [comment]
MeasureUP practice exams still ask about this cmdlet.  Any idea if the real exams are still asking about the non-ARM cmdlets?

**Comment by dcbrown16** [comment]
Is this coming up in the near future?
Thanks!

**Comment by dcbrown16** [comment]
A use case for this command would be to use Azure Automation to schedule periodic downloading of the logs, which can't be done with the extant CLI command.

**Comment by panchagnula** [comment]
Closing this since there is no ARM equivalent for this at this time.
