### ISSUE TITLE
Deprication of Switch-AzureMode

### ISSUE THREAD

**Issue by doctordns** [Azure/azure-powershell#595]
Two issues/questions here
1. In the current release, using this cmdlet resutls in the following Warning Message:
WARNING: The Switch-AzureMode cmdlet is deprecated and will be removed in a future release
It would useful to add to that warning some hint as to what to do instead. I, like most users, will do anything we can to elminate warnings - just tell us what to do. You could do a 1-line explanation of how to avoid the warning, or possibly link to some web page via an fwlink.

2. Second question: what DO we do to avoid this message. When I install the PowerShell Module from here - it installs as the Azure module - I do not see the AzureResourceManager module from Get-Module -list. But when I switch-Azuremode, I now see Azure ResourceManager (and Azure module is gone). I am really not clear on how you manage that (a very cool trick!). but it works. So how do I load this module? Do I manually have to load/unload modules? Also - how do we manage autoload when cmdlets common to both modules is called? Is there an expanded text anywhere that describes how this is all meant to work with switch-azuremode is deprecated>

If this is not the right place for these questions, please point me to better place/

**Comment by robplank** [comment]
see this thread for the discussion of the future of the module https://github.com/Azure/azure-powershell/issues/428 

In the current version of the module you will always see the warning when you use the Switch-Azuremode cmdlet.

**Comment by doctordns** [comment]
Robplank: thanks for that reference. Very useful.

It seems to me that we could usefully use the solution sooner (ie two modules with different nounprefixes) , rather than later. It would be useful to have them side by side for say 6 months before cutting over. Assuming there is a new way to do things (ie new modules) I'd prefer moving now rather than just waiting and storing up more breaking changes.

Can we run  this side by side?

**Comment by devigned** [comment]
Please keep the conversation in the originating thread. I'm going to close this as a duplicate.
