### ISSUE TITLE
New Cmdlet request: AzureRMAutomationHybridWorkerGroup

### ISSUE THREAD

**Issue by aydeisen** [Azure/azure-powershell#5952]
Can cmdlets please be created that wrap around the [Update](https://docs.microsoft.com/en-us/rest/api/automation/hybridrunbookworkergroup/update) and [Delete](https://docs.microsoft.com/en-us/rest/api/automation/hybridrunbookworkergroup/delete) REST Methods for a Hybrid Runbook Worker Group?  Currently, there's only a Get cmdlet

**Comment by NarayanThiru** [comment]
We already have a cmdlet for [Delete](https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/Remove-AzureRmAutomationHybridWorkerGroup?view=azurermps-6.13.0)
