### ISSUE TITLE
Set-AzureRmDiagnosticSetting does not have parameter 'EventHub Name'

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/azure-powershell#5955]
### Description

We are unable to set the Event Hub name when streaming diagnostic data into Event Hubs.  Setting a predefined Event Hub is required when streaming all diagnostics data into a single destination regardless of resource or event types.

This is possible through Azure Portal and [CLI](https://docs.microsoft.com/en-us/cli/azure/monitor/diagnostic-settings?view=azure-cli-latest#az-monitor-diagnostic-settings-create)

![image](https://user-images.githubusercontent.com/16688027/38761070-f1738850-3f4d-11e8-8ee8-97b25af7dc18.png)

### Script/Steps for Reproduction

```powershell
Set-AzureRmDiagnosticSetting -ResourceId $ResourceId -EventHubAuthorizationRuleId $EventHubRuleId -Enabled $true
```

### Environment Data

```powershell
$PSVersionTable

Name                           Value                                                                                                       
----                           -----                                                                                                       
PSVersion                      5.1.16299.251                                                                                               
PSEdition                      Desktop                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                     
BuildVersion                   10.0.16299.251                                                                                              
CLRVersion                     4.0.30319.42000                                                                                             
WSManStackVersion              3.0                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                         
SerializationVersion           1.1.0.1   
```

**Comment by markcowl** [comment]
@SenthuranSivananthan Is the issue that this is not possible, or that it requires creating an eventhub rule first and is therefore less usable?

@twitchax @gucalder Can you take a look?  Unsure if this is missing functionality, or this is a needed usability improvement.  It seems like this would also apply to other event targets.

**Comment by SenthuranSivananthan** [comment]
@markcowl Cmdlet is missing the property.  Therefore, individual event hubs are created to send data by each service.  For example, SQL Database can create 3 or 4 event hubs to send telemetry.  I want to force all telemetry to be in a single event hub.  It'll make it easier to process by 3rd party tools such as SIEMs.

The only way I was able to get it to work is through the UI, thus making this unusable for Event Hubs.

**Comment by markcowl** [comment]
@twitchax Adding to our next issue triage so we can decide how / when to address

**Comment by MiYanni** [comment]
@twitchax Kick

**Comment by twitchax** [comment]
@markcowl @MiYanni, sorry...I got stuck in another meeting today.

Should this be an investigation for @gucalder?  Or. did we determine that this is on DevEx?

**Comment by cormacpayne** [comment]
@gucalder would you mind taking a look?

**Comment by twitchax** [comment]
@gucalder, ping. :)

**Comment by gucalder** [comment]
This argument is going to be released in the next iteration of PowerShell.
The code changes were merged around 3/4 weeks ago.

**Comment by praries880** [comment]
Fixed in PR : https://github.com/Azure/azure-powershell/pull/6477

**Comment by praries880** [comment]
changes are already out in the released module : https://www.powershellgallery.com/packages/AzureRM.Insights/5.1.0
