### ISSUE TITLE
Convert test projects to Netcore for core modules

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#5965]
### Convert the test projects for the following Core modules:

- [x] Azure.Storage (Yanni)
- [x] AzureRM.Automation (Mark/Yanni)
- [x] AzureRM.Compute (Mark)
- [x] AzureRM.KeyVault (Yanni) 
- [x] AzureRM.Network (Yanni)
- [x] AzureRM.Resources (Yanni)
- [x] AzureRM.Sql (Yanni)
- [x] AzureRM.Storage (Yanni)
- [x] AzureRM.Websites (Yanni)

### Additionally, convert the projects for these modules as time permits
- [x] AzureRM.Insights (Yanni)
- [x] AzureRM.Batch (Yanni)

**Comment by MiYanni** [comment]
This guy: https://github.com/Azure/azure-powershell/pull/6281
