### ISSUE TITLE
New-AzureRmAppServicePlan: Support creating an appservice plan for Linux app

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-powershell#5983]
The current cmdlet 'New-AzureRmAppServicePlan' https://docs.microsoft.com/en-us/powershell/module/azurerm.websites/new-azurermappserviceplan?view=azurermps-5.7.0 , does not have an option to create an appservice plan for Linux.
This is currently available only in CLI https://docs.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest#az-appservice-plan-create

**Comment by panchagnula** [comment]
@LukaszStem, FYI

**Comment by panchagnula** [comment]
This needs some basic updates to  support Linux. Targeting end of July release.

**Comment by panchagnula** [comment]
Moving this out

**Comment by dcaro** [comment]
A potential workaround is described here: 
https://stackoverflow.com/questions/59719532/how-to-create-a-linux-appservice-plan-with-new-azappserviceplan

**Comment by panchagnula** [comment]
@Kotasudhakarreddy and @ThejaChoudary can you look at this .

**Comment by ThejaChoudary** [comment]
Taking a look into this.

**Comment by panchagnula** [comment]
@ThejaChoudary can we start the PR for this?

**Comment by panchagnula** [comment]
The fix is now merged.
