### ISSUE TITLE
Post installing SF runtime 6.1.480.9494, Add-AzureRmServiceFabricClusterCertificate adds bad certificate with Intended purposes 'Client Authentication' only

### ISSUE THREAD

**Issue by meetamitbhatia** [Azure/azure-powershell#5998]
I recently installed SF Runtime v6.1.480.9494. Then today tried adding secondary certificate using Add-AzureRmServiceFabricClusterCertificate. However, it adds bad certificate with Intended purposes 'Client Authentication' only!!

This causes failing to authenticate to Service Fabric Explorer, so unable to login to Service Fabric Explorer anymore.

PS Module AzureRm.ServiceFabric version is 0.3.4

**Comment by cormacpayne** [comment]
@juhacket Hey Justin, would you mind taking a look at this issue?

**Comment by juhacket** [comment]
Yes, we are aware of this issue and are working on a fix. This is a bug in the PS cmdlet, not related to the SF runtime version.

**Comment by juhacket** [comment]
The fix for this issue has been released with Azure PowerShell 6.1.0.
https://github.com/Azure/azure-powershell/releases/tag/v6.1.0-May2018
