### ISSUE TITLE
Please add support for creating service bus topics and subscriptions

### ISSUE THREAD

**Issue by bunceg** [Azure/azure-powershell#6]
NB: As requested, moved from old repository here:
https://github.com/Azure/azure-sdk-tools/issues/2936#issuecomment-63881865

To create topics and subscriptions is a manual step which is laborious and error prone. These processes are ideal for powershell scripting and as, service bus is significant part of the Azure offering, these should be added to to the suite of scripts.

**Comment by crpietschmann** [comment]
What's the status on this? It doesn't look like it's been worked on yet. I'm thinking about contributing a PR in this area.

**Comment by markcowl** [comment]
@crpietschmann The ServiceBus team hasn't been actively developing these cmdlets.  Contributions are always welcome.

**Comment by crpietschmann** [comment]
I was curious if it'd be worth contributing. Now I know it is! Thanks for the reply!

**Comment by cormacpayne** [comment]
Closing this issue as there appears to be `*-AzureRmServiceBusSubscription` and `*-AzureRmServiceBusTopic` cmdlets available in the `AzureRM.ServiceBus` module
