### ISSUE TITLE
Get-AzureRmTenant returns incorrect Directory when user is connected to multiple tenants.

### ISSUE THREAD

**Issue by lesterw1** [Azure/azure-powershell#6007]
### Description

Get-AzureRmTenant returns the wrong directory name when the user is connected to two different tenants.  For example, if the user has access to tenant A (ABC.com) and tenant B (XYZ.com) as a guest user, then Get-AzureRmTenant will return two entries. However, both entries will indicate a directory name of ABC.com.  The second entry should be XYZ.com:

Id        : a603898f-7de2-45ba-xxxx-d35fb519b2cfxxxx
Directory : ABC.com

Id        : f55850c9-aa72-40b9-xxxx-a7e7abc0xxxx
Directory : ABC.com

### Script/Steps for Reproduction

(1) Login to tenant B.  
(2) Invite user@tenantA.com as a guest user.
(3) Accept the guest user invitation email.
(4) Start a new PowerShell session and Login-AzureRmAccount using the user@tenantA.com credentials.
(5) Get-AzureRmTenant

The output will list the Tenant ID as well as the directory name. Note that the directory name for the second tenant is incorrectly reported using the directory name for the first tenant.

Id        : a603898f-7de2-45ba-xxxx-d35fb519b2cfxxxx
Directory : ABC.com

Id        : f55850c9-aa72-40b9-xxxx-a7e7abc0xxxx
Directory : ABC.com

### Module Version
                                                 
Script     5.7.0      AzureRM                                                                                                                
Script     5.4.1      AzureRM 

### Environment Data

Name                           Value                                                                                                         
----                           -----                                                                                                         
PSVersion                      5.1.16299.251                                                                                                 
PSEdition                      Desktop                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                       
BuildVersion                   10.0.16299.251                                                                                                
CLRVersion                     4.0.30319.42000                                                                                               
WSManStackVersion              3.0                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                           
SerializationVersion           1.1.0.1   

### Debug Output
PARTIALLY REDACTED SUBSCRIPTION IDs

PS D:\_oldwork\msci\ps1> Get-AzureRmTenant -debug
DEBUG: 14:44:09 - GetAzureRMTenantCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 14:44:11 - using account id 'Lester.Waters@ABC.com'...
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'a603898f-7de2-45ba-xxxx-d35fb519xxxx', Endpoint: 'https://
login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri:
 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/a603898f-7de2-45ba-xxxx-d35fb5
19xxxx/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'a603898f-7de2-45ba-xxxx-d35fb519xxxx', AdEndpoint: 'http
s://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/20/2018 13:44:11: 39ec5fbc-4c99-45b5-98e3-cf79592e3fd2 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/a603898f-7de2-45ba-xxxx-d35fb519xxxx/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (2 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 04/20/2018 13:44:11: 39ec5fbc-4c99-45b5-98e3-cf79592e3fd2 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/20/2018 13:44:11: 39ec5fbc-4c99-45b5-98e3-cf79592e3fd2 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 04/20/2018 13:44:11: 39ec5fbc-4c99-45b5-98e3-cf79592e3fd2 - TokenCache: 46.7699128016667 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/20/2018 13:44:11: 39ec5fbc-4c99-45b5-98e3-cf79592e3fd2 - TokenCache: A matching item (access token or refresh token or both) was fou
nd in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/20/2018 13:44:11: 39ec5fbc-4c99-45b5-98e3-cf79592e3fd2 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An ac
cess token was retuned:
	Access Token Hash: wRrQ0nvF+dgaiiCJStR8f8LcfslVYEbRWyYwI7XUBss=
	Refresh Token Hash: amiybWjIX73ivFw4MPGJO9ExJzgtjJoi4mJLnjNDcoA=
	Expiration Time: 04/20/2018 14:30:57 +00:00
	User Hash: t4+X6YHRIV8VElVjsmRDO4INMYUrpY1+29GXSJX17nE=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/20/2018 13:44:11:  - TokenCache: Serializing token cache with 2 items.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/tenants?api-version=2016-06-01

Headers:
x-ms-client-request-id        : 3ce174b1-d711-4b7e-a5cb-63c86aa7db22
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-tenant-reads: 14997
x-ms-request-id               : 31308dcb-147c-483e-8d00-d96b27164c7b
x-ms-correlation-request-id   : 31308dcb-147c-483e-8d00-d96b27164c7b
x-ms-routing-request-id       : UKWEST:20180420T134420Z:31308dcb-147c-483e-8d00-d96b27164c7b
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Fri, 20 Apr 2018 13:44:19 GMT

Body:
{
  "value": [
    {
      "id": "/tenants/a603898f-7de2-45ba-xxxx-d35fb519xxxx",
      "tenantId": "a603898f-7de2-45ba-xxxx-d35fb519xxxx"
    },
    {
      "id": "/tenants/f55850c9-aa72-40b9-xxxx-a7e7abc0xxxx",
      "tenantId": "f55850c9-aa72-40b9-xxxx-a7e7abc0xxxx"
    }
  ]
}

Id        : a603898f-7de2-45ba-xxxx-d35fb519xxxx
Directory : ABC.com

Id        : f55850c9-aa72-40b9-xxxx-a7e7abc0xxxx
Directory : ABC.com

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmTenant; IsSuccess - True; Duration - 00:00:02.9116489; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 14:44:12 - GetAzureRMTenantCommand end processing.
DEBUG: 14:44:12 - GetAzureRMTenantCommand end processing.

**Comment by lesterw1** [comment]
It should be noted that the REST API did not appear to return the Directory name... so it's unclear how  the cmdlet is populating the Directory property.

**Comment by markcowl** [comment]
@lesterw1 This is unfortunately by design, there is no API that returns this value, so the cmdlet makes a 'best guess' from the login name
