### ISSUE TITLE
Azure cmdlets initialization sometimes fails due to race condition and cannot recover

### ISSUE THREAD

**Issue by chenxuandong** [Azure/azure-powershell#601]
When multiple Powershell processes try Get-AzureSubscription at the same time, some of them might return an error saying the subscription does not exist.
The root cause should be at Common/Commands.Common/AzurePSCmdlet.cs#L97.
The logic there returns an empty AzureProfile object when failing to access the subscription info file.
After this empty object is stored in static _currentProfile, cmdlets in this process won't try loading the file anymore, they just use this empty AzureProfile object and gives "does not exist" error when the subscription does exist in hard drive.
This issue blocks a scenario that multiple Powershell jobs are started at the same time to add VMs into several Cloud Services.
If an exception is thrown in this case, then a simple retry will resolve it.
But now, the only solution is to stop the troublesome Powershell job and start over.

**Comment by markcowl** [comment]
@chenxuandong The correct way to run multiple jobs in parallel and avoid locking issues with files is to use a stateless profile, load your subscriptions into the profile, and either pass the profile in to the cmdlets using the -Profile parameter, or use Select-AzureProfile, if you are running jobs in separate PowerShell processes.

For more information on using stateless AzureProfile, see:  https://github.com/Azure/azure-powershell/wiki/Azure-Profile-Cmdlets
