### ISSUE TITLE
webapp:Add the ability to upload a certificate to app service

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-powershell#6020]
Need the equivalent of "az webapp config ssl upload"

**Comment by panchagnula** [comment]
The current New-AzWebappSSLBinding command takes care of uploading & binding a certificate, We will consider making these 2 separate commands - when we add support for importing certificates from KeyVault. Sorry for now not something we are looking into. 

https://docs.microsoft.com/en-us/powershell/module/az.websites/new-azwebappsslbinding?view=azps-2.4.0
