### ISSUE TITLE
new-azurermresourcegroupdeployment

### ISSUE THREAD

**Issue by VaperWare** [Azure/azure-powershell#6026]
### Script/Steps for Reproduction

PS C:\Azure_Source\Solutions> $DebugPreference = "continue"
PS C:\Azure_Source\Solutions> New-AzureRmResourceGroupDeployment -Name
 test01 -TemplateParameterFile .\Solution1_parameters.json -TemplateFile .\Solution1_template.json
DEBUG: 7:53:21 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.
DEBUG: 7:53:21 PM - using account id 'gerald@trituraig.onmicrosoft.com'...
DEBUG: AzureQoSEvent: CommandName - Get-AzureRmContext; IsSuccess - True; Duration - 00:00:00.0201086; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 7:53:23 PM - GetAzureRMContextCommand end processing.
DEBUG: 7:53:23 PM - GetAzureRMContextCommand end processing.
The parameter 'deploymentName' cannot be specified because it conflicts with the parameter alias of the same name for
parameter 'Name'.
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -Name test01 -TemplateParameterFil ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], MetadataException
    + FullyQualifiedErrorId : ParameterNameConflictsWithAlias

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.7.0      AzureRM
```

### Environment Data

```powershell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17134.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

PS C:\Azure_Source\Solutions> $DebugPreference = "continue"
PS C:\Azure_Source\Solutions> New-AzureRmResourceGroupDeployment -Name
 test01 -TemplateParameterFile .\Solution1_parameters.json -TemplateFile .\Solution1_template.json
DEBUG: 7:53:21 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.
DEBUG: 7:53:21 PM - using account id 'gerald@trituraig.onmicrosoft.com'...
DEBUG: AzureQoSEvent: CommandName - Get-AzureRmContext; IsSuccess - True; Duration - 00:00:00.0201086; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 7:53:23 PM - GetAzureRMContextCommand end processing.
DEBUG: 7:53:23 PM - GetAzureRMContextCommand end processing.
The parameter 'deploymentName' cannot be specified because it conflicts with the parameter alias of the same name for
parameter 'Name'.
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -Name test01 -TemplateParameterFil ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], MetadataException
    + FullyQualifiedErrorId : ParameterNameConflictsWithAlias
```

```

**Comment by maddieclayton** [comment]
@VaperWare Looks like the -Name parameter has an alias to "DeploymentName", so this name cannot be used as a parameter in your template.  If you rename the parameter in your template file, this issue should be resolved.  Please let me know if you have further questions.
