### ISSUE TITLE
Output in some of the network watcher cmdlets doesn't correspond output in description

### ISSUE THREAD

**Issue by irrogozh** [Azure/azure-powershell#6029]
### Script/Steps for Reproduction

Returned type in the following cmdlets: 
New-AzureRMNetworkWatcherPacketCapture
Get-AzureRmNetworkWatcherTroubleshootingResultStart-AzureRmNetworkWatcherResourceTroubleshooting
Stop-AzureRmNetworkWatcherPacketCapture is not the same as in description 
```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by number213** [comment]
Fixed by this PR https://github.com/Azure/azure-powershell/pull/6117
