### ISSUE TITLE
Start-AzureRmVM : No status info

### ISSUE THREAD

**Issue by foxxhot** [Azure/azure-powershell#6030]
### Description
We are using status info as following to judge if the command runs correctly in automation runbook,  but with AzureRM.Compute 4.6.0 nothing returns from Start-AzureRmVM.

$result = $vm | Start-AzureRmVM
$result.Status

With AzureRM.Compute 4.5.0 and before this issue did not exist.  Could you fix this issue? Thanks.

### Script/Steps for Reproduction
$vm = get-azurermvm -ResourceGroupName iis -Name iis
$result = $vm | Start-AzureRmVM
$result

OperationId :
Status      :
StartTime   :
EndTime     :
Error       :

### Module Version
ディレクトリ: C:\Program Files\WindowsPowerShell\Modules
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.7.0      AzureRM

### Environment Data

PS C:\>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by cormacpayne** [comment]
@hyonholee @nibhat hey guys, would you mind taking a look at this issue? Do you know of any issues with the server not returning data for these types of operations?

**Comment by axelgMS** [comment]
Possible workaround seems to be a Get-AzureRMVM with -Status parameter to get the empty fields.

**Comment by markcowl** [comment]
This is a dupliacte of #5982 [even though the title is different, the underlying issue is the same]. Closing
