### ISSUE TITLE
'Get-AzureRMResource' cmdlet fails with "InvalidApiVersionParameter : The api-version '2018-05-01' is invalid"

### ISSUE THREAD

**Issue by KrishnaAdityaB** [Azure/azure-powershell#6031]
Since few hours, AzureFileCopy VSTS Task started failing for customers using certain versions of Azure PowerShell. https://github.com/Microsoft/vsts-tasks/issues/7059

The failure is with _Get-AzureRMResource_ cmdlet. 
It is passing with 4.4.1. But failing with 2.1.0 (and few other versions).

Execution of the cmdlet from PowerShell directly is also failing with the same error.

**Here is the error message for 2.1.0**
```
Get-AzureRMResource : InvalidApiVersionParameter : The api-version '2018-05-01' is invalid. The supported versions are
'2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
At line:1 char:1
+ Get-AzureRMResource
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : InvalidApiVersionParameter,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
```

**By adding debug flag to the cmdlet we noticed, the api-version 2018-05-01 is getting set in the URL.
Below is the URL and body**
```
HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<subscriptionId-removed-from-actual-url>/resources?api-version=2018-05-01

Headers:
User-Agent                    : AzurePowershell/v2.1.0.0
ParameterSetName              : The list all resources parameter set.
CommandName                   : Get-AzureRmResource

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 4c271645-20ff-4be4-a290-22646602c065
x-ms-correlation-request-id   : 4c271645-20ff-4be4-a290-22646602c065
x-ms-routing-request-id       : SOUTHINDIA:20180424T093847Z:4c271645-20ff-4be4-a290-22646602c065
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 24 Apr 2018 09:38:46 GMT

Body:
{
  "error": {
    "code": "InvalidApiVersionParameter",
    "message": "The api-version '2018-05-01' is invalid. The supported versions are
'2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
  }
}
```

**This seems to be failing for only certain regions. If the issue reaches all regions - majority of our customers will be impacted**.

**Comment by cormacpayne** [comment]
@KrishnaAdityaB Hey Krishna, this has been identified as an issue in the ARM service, which they are currently working on getting a hotfix out. I will update this issue with more information as it comes out.

**Comment by JaDevGuy** [comment]
@cormacpayne any idea of an ETA to get this fixed?

**Comment by mbcooper** [comment]
+1

**Comment by KrishnaAdityaB** [comment]
@cormacpayne Back to normal. Thanks.

**Comment by sushant147** [comment]
I am also receiving the same error but on Azure File Copy since yesterday (24 Apr). I tried to add this PowerShell before the File Copy however it didn't solve my problem and gave me a new error. I don't even have analysis services in my release pipeline.

Install-Module -Name AzureRM -AllowClobber -Force

The error...
The specified module 'Azure.AnalysisServices' with version '0.5.0' was not loaded because no valid module file was found in any module directory.

**Comment by KrishnaAdityaB** [comment]
@sushant147 
As the issue was fixed few hours ago - please try without any workaround. It should work.

For further debugging with AzureFileCopy task: We can discuss on the Microsoft/vsts-tasks repo.. here is the corresponding thread from there https://github.com/Microsoft/vsts-tasks/issues/7059.

**Comment by sushant147** [comment]
The issue has been fixed. I am now able to run my pipeline normally. Thank you.

**Comment by JaDevGuy** [comment]
Thanks! the issue is fixed now.
