### ISSUE TITLE
How do limit the scope of my Azure connection inside of Azure functions?

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-powershell#6054]
This is not a bug report (yet). It is an important security related question that so far I cannot figure out on my own.

The scenario is simple:

I have a C# Azure Function that internally invokes the latest release of Azure PowerShell. If you provide the endpoint with the appropriate information, it will log you into Azure using `Connect-AzureRmAccount -Scope Process`, and then run a script you provide it against that Azure subscription/tenant. Once the script has finished, the endpoint will invoke `Disconnect-AzureRmAccount -Scope Process`.

The same Azure Function endpoint supports running a script without connecting to Azure, in which case it does not invoke either of the cmdlets mentioned above.

The challenges:

1. If I do not invoke `Disconnect-AzureRmAccount` once the script has finished execution, and I invoke the function endpoint a second time without passing in Azure credentials, and thus bypassing the Azure connect/login it performs, I still have access to the Azure subscription.
1. If I keep the Disconnect call there, and I invoke the same endpoint again in a separate process while another invocation is running that uses Azure, but without passing Azure credentials in the separate process, and thus bypassing the Azure connect/login it performs, if I time it right (between the Connect/Disconnect in the other running Azure function endpoint), I have access to the Azure subscription.

The big question:

How do I connect to Azure using Azure PowerShell inside of an Azure function endpoint (not a PowerShell Azure Function, which are experimental/unsupported, a C# Azure Function that invokes PowerShell), in such a way that any other invocation of the same endpoint would have to make its own connection, and would never, ever be able to pick up on a connection made in a completely separate invocation of my Azure Function??? **Right now this seems like a security hole**, but I'm really hoping that it isn't and that I'm just missing something.

**Comment by cormacpayne** [comment]
@KirkMunro Hey Kirk, thanks for filing this issue. This is something that we'll need to spend some time investigating. In the meantime, would you mind providing some (or all) of the C# code that you're using to invoke PowerShell so we are able to keep the repro consistent with what you are doing? I assume that we don't need anything in your PowerShell script outside of `Connect-AzureRmAccount` and `Disconnect-AzureRmAccount`, but if there's any other pieces of information you feel we should have, would you mind including that as well? Thanks in advance 😀

**Comment by KirkMunro** [comment]
@cormacpayne I'll see what I can do. Very busy, and this isn't just in a public repo, so I'll have to build a separate example.

Worth sharing, I've been digging more into this, because I need to resolve this ASAP, and I've determined the following:

- Connect-AzureRmAccount currently offers process or user-level scoping of persisted session data;
- multiple invocations of an Azure Function endpoint all run in the same process with the same user account;
- the thread IDs are different between invocations; however thread IDs are recycled once they have completed, so while they would be a useful scoping mechanism to have, their usefulness is somewhat limited due to the reuse of thread IDs;
- PowerShell runspace instance IDs are unique between invocations without recycling, and offer the possibility of a more refined scoping mechanism that is more secure than process-level scoping when working with Azure functions.

**Comment by KirkMunro** [comment]
@jeffhollan Adding you for visibility, and also in hopes that you have a solution for this.

**Comment by jeffhollan** [comment]
Yes generally for something like a client (HttpClient / EventHubClient / whatever) in something like this we'd recommend instantiating a new client per execution to make sure each execution (even concurrently) has its own isolated client.  However that also has some tradeoffs in that you are limited to how much you can scale on a single instance of an app because of how many sockets / connections.  However in reading this it sounds like there is some caching on the PowerShell side that wouldn't allow you to instantiate a "new" script client per run as some state is shared regardless.  Only thing you could do with that is specify in the `host.json` to limit concurrency of a single host to 1 (depending on trigger).  So if HTTP you could say you only want to have one active execution per instance, same with queues, etc.  This would enable you to enforce that a second execution didn't take place until the current had finished and disposed/disconnected.  If you need high throughput though that would be a show stopper, but if you don't anticipate a high number of triggers per second would work fine from what I can see.

**Comment by KirkMunro** [comment]
Thanks for replying @jeffhollan. Eliminating concurrency isn't an option for us. The issue comes down to PowerShell's caching, which prevents any possibility of concurrency even across multiple runspaces. That is the change that I need needs to happen to AzureRM, with options for no caching, as well as support for runspace-level caching to maintain the ease of use that they built into AzureRM while isolating security contexts within a runspace.

The problem

**Comment by KirkMunro** [comment]
[These lines](https://github.com/Azure/azure-powershell/blob/f34c546fea58d48819e968cab9ac3dd5c50551f3/src/Common/Commands.Common.Authentication.Abstractions/AzureSession.cs#L29-L30) in AzureSession.cs seem to be the root cause of the current behavior.

That's a shame, because I was thinking as a workaround I might just be able to clear out the file system cache and mark that folder as read-only, especially since there are empty catch statements to swallow any errors that might come up from writing to disk in the Azure PowerShell code base, but since it's caching sessions in memory in a static singleton (ugh), that won't work.

**Comment by markcowl** [comment]
@KirkMunro 

I would need to understand the relationship between requests and process/AppDomains/runspaces in your implementation to advise you properly on this, but you should be able to easily isolate authentication to a single AppDomain like this:

```powershell
Disable-AzureRmContextAutosave -Scope Process
```

This ensures that an in-memory token cache is used. This also happens automatically if the user's AppData\Roaming directory is inaccessible

If you need isolation even within the AppDomain, you can use the ```-DefaultProfile``` parameter.

```powershell
Disable-AzureRmContextAutosave -Scope Process
$context = Get-AzureRmContext
$context.TokenCache = New-Object -Type Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache -ArgumentList (New-Object -Type Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache)
$profile = Connect-AzureRmAccount -DefaultProfile $context
```
This adds a couple of extra steps to ensure that the profile and token cache are only stored in variables.

Then, you can use this profile with all cmdlets you execute:

```powershell
Get-AzureRmSubscription -DefaultProfile $profile
Get-AzureRmVM -DefaultProfile $profile
```


There are also some C# extensibility points you can use to customize the way tokens and contexts are cached before any Azure PowerShell cmdlet is used as well, LMK if interested.

**Comment by KirkMunro** [comment]
@markcowl This looks very helpful, thank you! Please do share the C# extensibility points. I'm working with C# Azure Functions that internally invoke PowerShell, so I'm definitely interested. I'm going to explore what you shared so far right now, and I'll keep an eye out for the C# extensibility information.

Using $PSDefaultParameterValues to pass a DefaultProfile is exactly what I was trying to figure out yesterday (I had already figured out how to disable autosave), but that information does not seem to be documented anywhere (how to create the in-memory profile), and there do not appear to be any examples that show it either.

**Comment by KirkMunro** [comment]
Regarding autosaving and scope, I can see where the profile autosave settings are stored (ApplicationData environment folder, under "Windows Azure PowerShell"), but I don't seem to be able to find where user scoped settings are stored. If you invoke Disable-AzureRmContextAutosave -Scope CurrentUser, where is that information stored?

**Comment by markcowl** [comment]
This is in memory.  Whenever you use the -Scope Process parameter, it it swapping out the provider for the Profile.

We don't have any good documentation on creating profiles, and we likely need to have an additional cmdlet to make it easier (New-AzProfile).

**Comment by markcowl** [comment]
Filed two issues to address this formally:  
#6186 Introduces a new cmdlet to create an isolated context
#6185 Adds new conceptual documentation fro these concepts
