### ISSUE TITLE
Resources: Tests using static RoleDefinitionNames, cannot run in parallelization

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#6067]
In .NET Core, the Xunit flag `[assembly: CollectionBehavior(DisableTestParallelization = true)]` does not function (referenced [here](https://github.com/jcansdale/TestDriven.Net-Issues/issues/5#issuecomment-232082643) and [here](https://github.com/xunit/xunit/issues/1541#issue-270429442)). So, tests always run in parallel. All `RoleDefinition` tests and 1 `RoleAssignment` test (RaPropertiesValidation) use `RoleDefinitionNames`, a static queue, at the same time. So, these tests fail intermittently during runs on .NET Core.

- [ ] Refactor the `RoleDefinition` and `RoleAssignment->RaPropertiesValidation` scenario tests so they do not use the static `RoleDefinitionNames` queue

**Comment by cormacpayne** [comment]
This has been fixed.
