### ISSUE TITLE
Install all available Powershell modules from Mac OSX

### ISSUE THREAD

**Issue by arnabganguly** [Azure/azure-powershell#6076]
To install individual modules , I am aware that we could use Install-Module <Module_Name> on MacOSX. Is there a command to install all available modules at once ? I have followed the steps highlighted in https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6 to install powershell 6 on MacOSX.

**Comment by mrvladis** [comment]
@arnabganguly 
find-Module  azurerm.netcore | install-module
or
install-module azurerm.netcore
This will do what you want.

**Comment by cormacpayne** [comment]
@arnabganguly Hey Arnab, the `AzureRM.Netcore` module is the rollup module containing all of the .NET Core modules for Azure PowerShell, and as @mrvladis mentioned above, you can install all of these bits at once by running `Install-Module -Name AzureRM.Netcore`. Please let us know if this does not solve your issue, or if you have any further questions!
