### ISSUE TITLE
Investigate non-netstandard dependencies for NetCore modules

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6086]
- AzureRM. DataFactories & DataFactoriesV2
  - [ ] Microsoft.AspNet.WebApi.Client v5.2.2
  - [ ] Microsoft.AspNet.WebApi.Core v 5.2.2
  - [ ] Microsoft.DataTransfer.Gateway.Encryption v3.4.6604.1 
- AzureRM.DataLakeStore 
  - [ ] System.Net.Http 4.3.2
- Microsoft.RedisCache
  - [ ] Microsoft.Azure.Insights (sotrage dependency)

**Comment by MiYanni** [comment]
### DataFactories:
- https://github.com/Azure/azure-powershell/issues/6161

### DataLakeStore:
- `System.Net.Http` is not referenced in this project

### RedisCache:
- https://github.com/Azure/azure-powershell/issues/6241
