### ISSUE TITLE
Restructure Release Process on Daily Drops

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6103]
- [x] Automate all post-check-in validation to run after daily drops run, including smoke test
  - Created a [daily-smoke-test pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=2213&_a=summary), it is automatically triggered by [daily-build pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1869)
- [x] Automate release tooling (versioning) to run as part of daily drops
  - Created a [daily-build pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1869), it bumps version and release packages in artifacts each launch.
- [ ] Design Automation to create a release and a versioning PR based on 'blessed' build drop

**Comment by dingmeng-xue** [comment]
Daily build with smoke test is accomplished.

**Comment by BethanyZhou** [comment]
First two items are finished. We still have a long way for the last one, close this issue temporarily.
