### ISSUE TITLE
Refactor Common Libraries as Nuget Package

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6104]
- [ ] Refactor the common libraries and dependencies as a Nuget Package
- [ ] Consider wither an additional package is needed for tests

**Comment by MiYanni** [comment]
## Main Steps

### Construction
- Make a 'static' version of Common that will be used in ServiceManagement
  - ServiceManagement will not rely on the Common NuGet package. It will be completely independent of our current work projects.
- Remove any ServiceManagment-only code from Common
- Move/merge ResourceManager -> Common into Common
- If Common has any dependencies on code/projects outside of Common, remove them.
  - Common should be completely independent of ServiceManagement/ResourceManager/Storage code.
- Restructure/rename directories/projects in Common
  - Right now, there are 3 main categories of Common projects: Utilities/Infrastructure, Modules, and Testing/Test Infrastructure. We can determine logic groupings with this in mind.
- Configure Common project output paths
- Create build.proj for only Common
  - Make sure it can do the NuGet packaging properly
- Move any common files required for building (ex: .targets files) into Common from tools/elsewhere
  - This may involve actually making 2 versions. One set that is just used for ResourceManager and one that is used in Common.

### Separation
- Determine name for this repo
  - azure-powershell-common(?), something along those lines
- Create new public GitHub repo using the Common code
  - Make sure it is in the Azure org
- Create ReadMe.md for the repo
- Create Jenkins project to target and build the repo
  - Start by only making it build successfully. Then, add test execution to the project and validate tests are passing.
- Create Jenkins project to do signing
- For now, use the signed packages in local-feed on azure-powershell, and update all projects to reference the Common package
- Remove Common from the regular repo (azure-powershell)
- As long as everything seems to be working, publish the azure-powershell-common package to NuGet and update references for azure-powershell, and remove the local-feed version

**Comment by MiYanni** [comment]
Separated into:
https://github.com/Azure/azure-powershell/issues/6128
https://github.com/Azure/azure-powershell/issues/6129
