### ISSUE TITLE
Unclear error when using ARM mode against Azure Government subscription (P3)

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#612]
I've currently got an Azure Government subscription "selected" and when I attempt to call any ARM cmdlets, I receive the following exception.

![image](https://cloud.githubusercontent.com/assets/466713/8701181/7681db16-2acd-11e5-900f-f31c1539f8c9.png)

> Get-AzureResourceGroup : Object reference not set to an instance of an object.

I understand that ARM isn't supported in the Azure Government cloud, but the user feedback could probably be improved here, if ARM is unavailable.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by devigned** [comment]
@stankovski and @chadiel perhaps the cmdlets should raise a specific error upon trying to use a cloud that has no ARM support.

**Comment by ravbhatnagar** [comment]
This should work now against the US government cloud.
