### ISSUE TITLE
Refactor Common Libraries: Construction

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#6128]
From here: https://github.com/Azure/azure-powershell/issues/6104#event-1608851189

- ~~Make a 'static' version of Common that will be used in ServiceManagement~~
  - ~~ServiceManagement will not rely on the Common NuGet package. It will be completely independent of our current work projects.~~
- ~~Remove any ServiceManagment-only code from Common~~
- [x] Move/merge ServiceManagment -> Common into Common
- [x] Move/merge ResourceManager -> Common into Common
- [x] If Common has any dependencies on code/projects outside of Common, remove them.
  - Common should be completely independent of ServiceManagement/ResourceManager/Storage code.
- [x] Restructure/rename directories/projects in Common
  - Right now, there are 3 main categories of Common projects: Utilities/Infrastructure, Modules, and Testing/Test Infrastructure. We can determine logic groupings with this in mind.
- [x] Configure Common project output paths
- [x] Create build.proj for only Common
  - Make sure it can do the NuGet packaging properly
- [x] Move any common files required for building (ex: .targets files) into Common from tools/elsewhere
  - This may involve actually making 2 versions. One set that is just used for ResourceManager and one that is used in Common.

**Comment by markcowl** [comment]
Note: for existing modules, common has to remain backward compatible, which means we cannot make breaking changes, such as moving types between assemblies.

**Comment by MiYanni** [comment]
Completed within https://github.com/Azure/azure-powershell-common
