### ISSUE TITLE
Refactor Common Libraries: Separation

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#6129]
From here: https://github.com/Azure/azure-powershell/issues/6104#event-1608851189

- [x] Determine name for this repo
  - azure-powershell-common(?), something along those lines
- [x] Create new public GitHub repo using the Common code
  - Make sure it is in the Azure org
- [x] Create ReadMe.md for the repo
- [x] Create ~~Jenkins~~ VSTS project to target and build the repo
  - Start by only making it build successfully. Then, add test execution to the project and validate tests are passing.
- [x] Create Jenkins project to do signing
- [x] For now, use the signed packages in local-feed on azure-powershell, and update all projects to reference the Common package
- [x] Remove Common from the regular repo (azure-powershell)
- [x] As long as everything seems to be working, publish the azure-powershell-common package to NuGet and update references for azure-powershell, and remove the local-feed version

**Comment by maddieclayton** [comment]
Issue related to this: https://github.com/Azure/azure-powershell/issues/6379

**Comment by MiYanni** [comment]
Completed all the tasks for this work item.
