### ISSUE TITLE
DataFactories: Microsoft.DataTransfer.Gateway.Encryption has no NetCore build

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#6161]
Currently, your management library (Microsoft.Azure.Management.DataFactories) does not have a NetCore version. However, we are updating that currently. 

The main problem is that another dependency (Microsoft.DataTransfer.Gateway.Encryption) does not have a netcore build. The dependencies for this library (Microsoft.AspNet.WebApi.Client and Microsoft.AspNet.WebApi.Core) have NetCore builds. So, either you need to create an updated version of that Encryption library, or remove your dependency on it to allow us to build the DataFactories cmdlets for NetCore.

**Comment by MiYanni** [comment]
@jsnikhil It sounds like it will be a bit before DataFactories/DataFactoryV2 will be included in Az.

**Comment by MiYanni** [comment]
@zhangyd2015 is addressing the work for this issue.

**Comment by MiYanni** [comment]
This work was done in: https://github.com/Azure/azure-powershell/pull/7839

**Comment by jsnikhil** [comment]
Is this version available in preview only? I still see exactly the same issue as described in https://github.com/Azure/azure-powershell/issues/7367.

I upgraded powershell to 6.1.1
Az module to 0.4.0

**Comment by MiYanni** [comment]
@jsnikhil That change is in the release going out right now. Will be Az 0.7.0. It should be available on PS Gallery within an hour or two.
