### ISSUE TITLE
Add test coverage for Service Fabric cluster cert creation

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#6164]
Missing test coverage for PR https://github.com/Azure/azure-powershell/pull/6127

**Comment by maddieclayton** [comment]
@juhacket Have you had a change to look into this test debt issue?

**Comment by juhacket** [comment]
We have an upcoming change to integrate the latest API version, which will cover this ask.

**Comment by cormacpayne** [comment]
@juhacket Hey Justin, would you mind applying the correct milestone when you know when this task will be covered in the upcoming work? Thanks in advance.

**Comment by maddieclayton** [comment]
@juhacket Is this work going to be completed in this milestone? Otherwise, can you move into the appropriate milestone?

**Comment by maddieclayton** [comment]
@juhacket Ping

**Comment by markcowl** [comment]
Closing as 'won't fix'
