### ISSUE TITLE
Select-AzureRMSubscription <string>: A Task Is Canceled

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6165]
In some prallel execution environments (like Azure Automation) customers are reporting an issue with selecting subscription by name.

## Debug Log
```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions?api-version=2016-06-01

Headers:
x-ms-client-request-id        : 168ade23-41c8-4535-bbba-d02d84aa0695
accept-language               : en-US

Body:


Select-AzureRmSubscription : A task was canceled.
At line:1 char:27
+ ... { Get-Date; Select-AzureRmSubscription -Subscription 'CDM OaaS Dev' } ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmContext], TaskCanceledException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand
```

## Local Repro
```powershell
Login-AzureRmAccount
$ErrorActionPreference = 'Stop'
$VerbosePreference = 'Continue'
$DebugPreference = 'Continue'
while ($true) { Get-Date; Select-AzureRmSubscription -Subscription $subscriptionName } 
```

**Comment by AnatoliB** [comment]
Please note the issue is reproduced on a standalone VM that has nothing to do with Azure Automation, with a single instance of this script running in a single PS console process.

**Comment by maddieclayton** [comment]
Fixed!

**Comment by cormacpayne** [comment]
To anyone running into this issue:

Azure PowerShell introduced a mitigation for this exception in PR https://github.com/Azure/azure-powershell/pull/6245 that will retry up to three times on a call that received the `TaskCanceledException` error from ARM. This mitigation is found in version [6.3.0](https://www.powershellgallery.com/packages/AzureRM/6.3.0) and later of `AzureRM` (version [5.3.0](https://www.powershellgallery.com/packages/AzureRM.profile/5.3.0) and later of `AzureRM.Profile`).

If you are seeing the `TaskCanceledException` error, please update to the latest version of `AzureRM` (or at least version 6.3.0) and file a new issue if you are still seeing this exception.

**Comment by johno4321** [comment]
Hi Cormac - you mention that the x3 retry is a mitigation. is there a root cause fix planned for a future release?
