### ISSUE TITLE
Set-AzureRmDataLakeStoreItemAclEntry -Recurse Value cannot be null

### ISSUE THREAD

**Issue by Liamdelee** [Azure/azure-powershell#6171]
### Description

I am running the cmdlet Set-AzureRmDataLakeStoreItemAclEntry with the option of -Recurse and i get the error:
Set-AzureRmDataLakeStoreItemAclEntry : Value cannot be null.
Parameter name: source

However when i remove the -Recurse option it works out just fine.

Another heads up, in your documentation example2, you say to use -Recursive but this is not recognized and should be changed to -Recurse (this gives an error).

### Script/Steps for Reproduction

```powershell
Set-AzureRmDataLakeStoreItemAclEntry -AccountName $dataLakeName -Path / -AceType User -Id (Get-AzureRmADApplication -ApplicationId $azureAdApplication.ApplicationId).ApplicationId -Permissions All -Recurse
```

### Module Version

ModuleType    Version    Name
Script               6.0.1        AzureRM

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

Name                           Value                                                                                                                   
----                           -----                                                                                                                   
PSVersion                      5.1.16299.251                                                                                                           
PSEdition                      Desktop                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                 
BuildVersion                   10.0.16299.251                                                                                                          
CLRVersion                     4.0.30319.42000                                                                                                         
WSManStackVersion              3.0                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                     
SerializationVersion           1.1.0.1  

```powershell
$PSVersionTable
```

### Debug Output

```
DEBUG: 12:12:40 - GetAzureADApplicationCommand begin processing with ParameterSet 'ApplicationIdParameterSet'.
DEBUG: 12:12:40 - using account id 'deleeli@cronos.be'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'deleeli@cronos.be', environment: 'AzureCloud', tenant: '49c3d703-3579-47bf-a888-7c913fbdc
ed9'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/09/2018 10:12:40: 919da685-5e36-4890-877d-aeb3c4959fdf - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/49c3d703-3579-47bf-a888-7c913fbdced9/
	Resource: https://graph.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (3 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/09/2018 10:12:40:  - TokenCache: Deserialized 3 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/09/2018 10:12:40: 919da685-5e36-4890-877d-aeb3c4959fdf - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/09/2018 10:12:40: 919da685-5e36-4890-877d-aeb3c4959fdf - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/09/2018 10:12:40: 919da685-5e36-4890-877d-aeb3c4959fdf - TokenCache: 42.8087181133333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/09/2018 10:12:40: 919da685-5e36-4890-877d-aeb3c4959fdf - TokenCache: A matching item (access token or refresh token or both) was found in the 
cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/09/2018 10:12:40: 919da685-5e36-4890-877d-aeb3c4959fdf - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token
 was retuned:
	Access Token Hash: 7pGilVYfLtZXpyWSFcFLRFPkhGxMsUb8lWySFYDKG2I=
	Refresh Token Hash: m3067tNoJJ09lY31Fbwjgi99pfFWASeyEkSagcwoSPs=
	Expiration Time: 05/09/2018 10:55:28 +00:00
	User Hash: y7GeiSBmzYPvYMsSu4q/+wJ53HA1cUo3lJYYm2+s1mA=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/09/2018 10:12:40: 192b3131-729f-4928-8d70-868e9f742e64 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/49c3d703-3579-47bf-a888-7c913fbdced9/
	Resource: https://graph.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (3 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/09/2018 10:12:40:  - TokenCache: Deserialized 3 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/09/2018 10:12:40: 192b3131-729f-4928-8d70-868e9f742e64 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/09/2018 10:12:40: 192b3131-729f-4928-8d70-868e9f742e64 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/09/2018 10:12:40: 192b3131-729f-4928-8d70-868e9f742e64 - TokenCache: 42.8085645483333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/09/2018 10:12:40: 192b3131-729f-4928-8d70-868e9f742e64 - TokenCache: A matching item (access token or refresh token or both) was found in the 
cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/09/2018 10:12:40: 192b3131-729f-4928-8d70-868e9f742e64 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token
 was retuned:
	Access Token Hash: 7pGilVYfLtZXpyWSFcFLRFPkhGxMsUb8lWySFYDKG2I=
	Refresh Token Hash: m3067tNoJJ09lY31Fbwjgi99pfFWASeyEkSagcwoSPs=
	Expiration Time: 05/09/2018 10:55:28 +00:00
	User Hash: y7GeiSBmzYPvYMsSu4q/+wJ53HA1cUo3lJYYm2+s1mA=
	

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.windows.net/49c3d703-3579-47bf-a888-7c913fbdced9/applications?$filter=appId eq 'cc8cfc0b-596a-46da-a200-0660b56c98a7'&api-version=1.6

Headers:
x-ms-client-request-id        : 816e24dd-0f8c-4c12-b911-3446482a3c9f
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
ocp-aad-diagnostics-server-name: DdPBqcCJXplXy9I+eGNHVEYGPieI4/5/Ne6wnp2YMw8=
request-id                    : 7b00b558-a2d9-4dd4-83de-b4cd572f49e5
client-request-id             : d73f2520-fd00-4f5a-8c71-a2e9891b42bb
x-ms-dirapi-data-contract-version: 1.6
ocp-aad-session-key           : -9tqBtpLqCeLaexN5lZOvqGz6YbJnNbcU6ArkUojygJmRIm8Us-XPnhpXvPghc_sthDkrdbFEu26EEKVaQBBlvQZxxNuinXCYgexhWccPSWFAUzE77SUoU3s
seqZVdP3TZdFl_o_koZ3mcvss0RBiQ.hcCPCeBT7VPm7NBqXweSeWSU9i9e8rNgVazzdLV4WVA
X-Content-Type-Options        : nosniff
DataServiceVersion            : 3.0;
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Access-Control-Allow-Origin   : *
Duration                      : 841615
Cache-Control                 : no-cache
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET,ASP.NET
Date                          : Wed, 09 May 2018 10:12:39 GMT

Body:
{
  "odata.metadata": "https://graph.windows.net/49c3d703-3579-47bf-a888-7c913fbdced9/$metadata#directoryObjects/Microsoft.DirectoryServices.Application",

  "value": [
    {
      "odata.type": "Microsoft.DirectoryServices.Application",
      "objectType": "Application",
      "objectId": "cce90d25-0a81-4342-a28a-577ff6cd3003",
      "deletionTimestamp": null,
      "acceptMappedClaims": null,
      "addIns": [],
      "appId": "cc8cfc0b-596a-46da-a200-0660b56c98a7",
      "appRoles": [],
      "availableToOtherTenants": false,
      "displayName": "testapp",
      "errorUrl": null,
      "groupMembershipClaims": null,
      "homepage": "http://testapp",
      "identifierUris": [
        "http://testapp"
      ],
      "informationalUrls": {
        "termsOfService": null,
        "support": null,
        "privacy": null,
        "marketing": null
      },
      "isDeviceOnlyAuthSupported": null,
      "keyCredentials": [],
      "knownClientApplications": [],
      "logoutUrl": null,
      "logoUrl": null,
      "oauth2AllowIdTokenImplicitFlow": false,
      "oauth2AllowImplicitFlow": false,
      "oauth2AllowUrlPathMatching": false,
      "oauth2Permissions": [
        {
          "adminConsentDescription": "Allow the application to access testapp on behalf of the signed-in user.",
          "adminConsentDisplayName": "Access testapp",
          "id": "ae22a8e5-784c-4021-92fb-c40900ee7df0",
          "isEnabled": true,
          "type": "User",
          "userConsentDescription": "Allow the application to access testapp on your behalf.",
          "userConsentDisplayName": "Access testapp",
          "value": "user_impersonation"
        }
      ],
      "oauth2RequirePostResponse": false,
      "optionalClaims": null,
      "parentalControlSettings": {
        "countriesBlockedForMinors": [],
        "legalAgeGroupRule": "Allow"
      },
      "passwordCredentials": [
        {
          "customKeyIdentifier": null,
          "endDate": "2019-05-09T10:11:24.8529343Z",
          "keyId": "d5ab41f8-e610-4cca-8973-10fcc4faee42",
          "startDate": "2018-05-09T10:11:24.8529343Z",
          "value": null
        }
      ],
      "publicClient": null,
      "recordConsentConditions": null,
      "replyUrls": [],
      "requiredResourceAccess": [],
      "samlMetadataUrl": null,
      "signInAudience": null,
      "tokenEncryptionKeyId": null
    }
  ]
}


DEBUG: AzureQoSEvent: CommandName - Get-AzureRmADApplication; IsSuccess - True; Duration - 00:00:00.1818110; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 12:12:41 - GetAzureADApplicationCommand end processing.
DEBUG: 12:12:41 - GetAzureADApplicationCommand end processing.
DEBUG: 12:12:41 - SetAzureDataLakeStoreItemAclEntry begin processing with ParameterSet 'SetSpecificACE'.
DEBUG: 12:12:41 - using account id 'deleeli@cronos.be'...
WARNING: The output type defined for this cmdlet is incorrect and will be updated to reflect what is actually returned (and defined in the help) in a fu
ture release.
Set-AzureRmDataLakeStoreItemAclEntry : Value cannot be null.
Parameter name: source
At C:\Users\deleeli\Downloads\create_application_for_adls_connection\create_application_for_adls_connection\createapp.ps1:98 char:1
+ Set-AzureRmDataLakeStoreItemAclEntry -AccountName $dataLakeName -Path ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmDataLakeStoreItemAclEntry], ArgumentNullException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataLakeStore.SetAzureDataLakeStoreItemAclEntry
 
DEBUG: AzureQoSEvent: CommandName - Set-AzureRmDataLakeStoreItemAclEntry; IsSuccess - False; Duration - 00:00:00.0156061; Exception - System.ArgumentNul
lException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Microsoft.Azure.Commands.DataLakeStore.SetAzureDataLakeStoreItemAclEntry.<>c__DisplayClass42_0.<ExecuteCmdlet>b__1()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(String processMessage, String target, Action action)
   at Microsoft.Azure.Commands.DataLakeStore.SetAzureDataLakeStoreItemAclEntry.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 12:12:41 - SetAzureDataLakeStoreItemAclEntry end processing.
DEBUG: 12:12:41 - SetAzureDataLakeStoreItemAclEntry end processing.
```

**Comment by cormacpayne** [comment]
@rahuldutta90 Hey Rahul, would you mind taking a look at this issue?

**Comment by rahuldutta90** [comment]
https://github.com/Azure/azure-powershell/blob/1da16cd4233c4bbf347781da6135c40ae960a658/src/ResourceManager/DataLakeStore/Commands.DataLakeStore/DataPlaneCommands/SetAzureRmDataLakeStoreItemAclEntry.cs#L114 In here we are only looking at the Acl (type DataLakeStoreItemAce[]) parameter to set the Acl which is only populated when user passes parameter set SetByACLObject. However user is passing parameter set SetSpecificACE so Acl is set as null. This is a bug which will be fixed by passing the variable aclSpec (which we are passing in the non-recurse case). I will start a PR to fix it. However till then mitigation can be pass your ACE by object like this:

$acl="user:<userid>:--x"
$newACL = $acl.Split("{|}")
Set-AzureRmDataLakeStoreItemAclEntry -Account rdutta1 -Path /a -Acl $newACL -Recurse.

**Comment by Liamdelee** [comment]
hi

thanks for the feedback.
Will implement the temporary fix.

**Comment by AlexKeySmith** [comment]
Hi, this issue seems to crop up when using -Default 

```powershell
Set-AzureRmDataLakeStoreItemAclEntry -Account $dataLakeStoreAccount `
	-Path $dataLakeFolder `
	-AceType User `
	-Id $principalObjectId `
	-Permissions ReadExecute `
	-Recurse `
	-Concurrency 1000 `
        -Default
```

Set-AzureRmDataLakeStoreItemAclEntry : Error in modifying ACL entries  for path /example
Operation:  failed with  Error: Acl Specification List is empty.

This seems very closely related, but let me know if you need a full repro / new ticket.

**Comment by rahuldutta90** [comment]
Default Acl does not apply to files, it applies only to folders. So for applying Acl to files we have to remove the default acl and in that case you acl becomes empty thats why you get this error. 

Recommended way is to always apply default and access acl together. Lets say you are applying default:user:userid1:rwx to directories. New Files created under these directories will inherit user:userid1:rwx. But you also want the existing files to get the user:userid1:rwx acl. That is why you should always apply default acls along with access acls.

**Comment by rahuldutta90** [comment]
If you are setting the default acl, why not set the same access acl also? 

So if you are setting a default acl default:user:userid1:rwx your intention is that any newly created file/directories under that will inherit access acl user:userid1:rwx right? So you also want your existing files to have acl user:userid1:rwx right? 

In that case you want to apply the default and acess acl together like following:

$fullAcl="user:userid1:--x|default:user:userid1:--x"
$newFullAcl = $fullAcl.Split("{|}");
#Set-AzureRmDataLakeStoreItemAclEntry -Account contoso -Path / -Acl $newFullAcl -Recursive -Debug -PassThru

does that help?

**Comment by vishal840** [comment]
Hey I have this same problem. I am running my scripts on windows PowerShell and I'm having trouble figuring out how to set the ACLs and Default in the same script. I'm trying to give default access to every child-folder in  a directory recursively, but as soon as a file is encountered, the recursion is stopped and it throws an error:
Set-AzureRmDataLakeStoreItemAclEntry : Error in modifying ACL entries for path /example
Operation: failed with Error: Acl Specification List is empty.

So I tried using the "-ACL" parameter, but I can't seem to make it work. I am doing this right now and it throws an error that the names were not resolved.

$acl=Get-AzureRmDataLakeStoreItemAcl -AccountName "ContosoADL" -Path /

Set-AzureRmDataLakeStoreItemAclEntry -AccountName $AccountName -Path $PathADLS -AceType $a -Id $groupidparam -Permissions ReadExecute -acl $acl -Recurse -Concurrency 128 -Default -WarningAction SilentlyContinue

Any help in this scenario would be highly appreciated

**Comment by rahuldutta90** [comment]
This issue will be fixed in the next release (Fix was made in SDK). However apart from that it is highly recommended to set all Acls (default/access) together for performance reasons because you want to avoid recursively enumerating your account again and again. As I showed above, you can create the Acl objects as below. You can put your list of acls delimited by semi-colon in $fullAcl. 

$fullAcl="user:userid1:--x;default:user:userid1:--x"
$newFullAcl = $fullAcl.Split("{;}");
Set-AzureRmDataLakeStoreItemAclEntry -Account contoso -Path / -Acl $newFullAcl -Recurse -Debug -PassThru
  
If you are setting default Acls then I would expect to set the access Acls too for that same user/group and permission. You can create the Acl object as above using your default and access acls and then pass it to the commandlet.

**Comment by vishal840** [comment]
@rahuldutta90 Hey, sorry, before I could actually try your code, I was taken off the project and don't have access to the subscription anymore. They will be using the same code I mentioned earlier after the new release.
