### ISSUE TITLE
Azs.Backup.Admin: Set-AzsBackupShare should make EncryptionKey parameter non-mandatory

### ISSUE THREAD

**Issue by daozha** [Azure/azure-powershell#6172]
@deathly809 
To align with that cmdlet in Azure Stack tools, we should make EncryptionKey parameter non-mandatory. This allows customers to change the backup share without changing encryption key, or provide the key again.

**Comment by deathly809** [comment]
Will be a breaking change.  Will make field optional with a message and then we will remove this once it has been removed from the UI.

**Comment by deathly809** [comment]
@hectoralinares We should setup a meeting to discuss this.

**Comment by deathly809** [comment]
This has been fixed, https://github.com/Azure/azure-powershell/pull/6821
