### ISSUE TITLE
Azs.Backup.Admin: Modfiy parameter name in Get-AzsBackup and Restore-AzsBackup

### ISSUE THREAD

**Issue by daozha** [Azure/azure-powershell#6173]
@deathly809 
Currently Get-AzsBackup and Restore-AzsBackup take "Name" as parameter. After the fix of nested resource name issue, the Name of backup resource will become {region}/{backupId}.

While Get-AzsBackup and Restore-AzsBackup actually take backupId as its parameter input:
Get-AzsBackup -Name {backupId}
Restore-AzsBackup -Name {backupId}

This can be a little confusing so how about change parameter from "Name" to "BackupId"?
Get-AzsBackup -BackupId {backupId}
Restore-AzsBackup -BackupId {backupId}

**Comment by deathly809** [comment]
We will leave it as name and introduce a fix which will extract the correct values when using the Name property of your resource.  All requests should be using the ARM resource properties and none of the underlying RP resource properties, excluding passing objects around of course.

**Comment by hectoralinares** [comment]
I think this change makes sense.

**Comment by daozha** [comment]
OK then we can close this as Won't fix.

@deathly809 I think there'll be similar changes to extract values across different modules, right? Is there a bug tracking this fix?

**Comment by deathly809** [comment]
@daozha This is probably not the best place to discuss this.  But we will use the azure-powershell issue tracker.  We will probably keep a task per month for "Azure-Powershell" bug fixes and add external links.
