### ISSUE TITLE
Azs.Backup.Admin: Rename Get-AzsBackupLocation and Set-AzsBackupShare

### ISSUE THREAD

**Issue by daozha** [Azure/azure-powershell#6174]
@deathly809 
The two cmdlet names are confusing. We're thinking about change them to Get-AzsBackupConfiguration / Set-AzsBackupConfiguration.

**Comment by deathly809** [comment]
This will be a breaking change.  We will have to add a cmdlet alias and a message to let users know the cmdlet will be replaced with the new name.

**Comment by hectoralinares** [comment]
Daotian, I think we should align this work with support for Azure storage in [Ti]

**Comment by daozha** [comment]
Close it for now. After we add Azure Storage support, we can consider the rename.

**Comment by deathly809** [comment]
@daozha We have already changed it and added an alias to the old name with a message.

**Comment by daozha** [comment]
@deathly809 Cool! May I know the PR number?

**Comment by deathly809** [comment]
We have not done a PR yet.  We should be doing one soon.

**Comment by deathly809** [comment]
Fix is in.  https://github.com/Azure/azure-powershell/pull/7067
