### ISSUE TITLE
Azs.Backup.Admin: Expose backup scheduler and retention parameters in Set-AzsBackupShare

### ISSUE THREAD

**Issue by daozha** [Azure/azure-powershell#6176]
@deathly809 
To allow customers configure backup scheduler and retention policy, we need to expose related parameters isBackupSchedulerEnabled/backupFrequencyInHours/backupRetentionPeriodInDays in Set-AzsBackupShare.

The parameters are already in spec and SDK.

Basically, we want them exposed:

- In a private build for now for preview purpose

- Officially exposed together with Azure Stack 1806 release. The release date should be late June to early July.

**Comment by deathly809** [comment]
Fixed with https://github.com/Azure/azure-powershell/pull/6821
