### ISSUE TITLE
Change TestController implementation for Profile and StorageManagement Scenario Tests

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6180]
- [x] Create new Mock IClientFactory implementation that creates clients at test runtime
- [x] Rework test setup to change the HttpRecorder settings only before running a test
- [x] Apply these settings to the Profile Project
- [x] Apply these changes to the storage management project
- [ ] Add necessary changes to control tenant id in ResourceManager calls
  - [ ] Ensure that Mock ProfileProvider provides correct context with token per test
  - [ ] Ensure that clients are correctly created with appropriate tenant settings (for Graph scenarios)
- [x] Adapt these changes to the ResourceManager tests
- [ ] Write comon code documentation on how to write tests using the new paradigm

**Comment by vladimir-shcherbakov** [comment]
close as merged
