### ISSUE TITLE
AzureBackup: Missing NetCore builds of dependencies

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#6191]
AzureBackup has 2 dependencies that do not have NetCore builds:

- [Microsoft.Azure.Management.BackupServices](https://www.nuget.org/packages/Microsoft.Azure.Management.BackupServices/1.0.5-preview)
- [Microsoft.WindowsAzure.Management.Scheduler](https://www.nuget.org/packages/Microsoft.WindowsAzure.Management.Scheduler/)

For us to have Backup modules in .NET Core, these dependencies need to be updated to have .NET Core versions.

**Comment by MiYanni** [comment]
@dragonfly91 Ping. Also, this specifically applies to [Backup](https://github.com/Azure/azure-powershell/tree/preview/src/ResourceManager/AzureBackup), not [RecoveryServices.Backup](https://github.com/Azure/azure-powershell/tree/preview/src/ResourceManager/RecoveryServices/Commands.RecoveryServices.Backup).

**Comment by markcowl** [comment]
AzureBackup is not needed in Az, so closing
