### ISSUE TITLE
Unable to find environment with name 'AzureCloud' with Add-AzureRMAccount

### ISSUE THREAD

**Issue by rokmicrosoft** [Azure/azure-powershell#6194]
Agent: - Private Agent 
Affected machine count :- only 1 VM
AzureRM version :- 5.7.0
Tried with un-installation of azure powershell  module and installed fresh azure powershell 5.7.0.
Get-AzurermEnvironment returns empty but Get-AzureEnvironment contains azurecloud.

Add-AzureRMAccount works fine when removed -Environment parameters from it.

I am also attaching machine description.
Windows spec
Edition: Windows 10 Pro N
Version: 1709
Os Build: 16299.431

Ram :- 8 GB
It is Azure VM.

**Comment by cormacpayne** [comment]
@rokmicrosoft would you mind updating to the latest version of `AzureRM` (6.0.1) and seeing if the issue still occurs? If so, would you mind running the command with `$DebugPreference="Continue"` set before and sending us the corresponding debug output?

**Comment by JonJam** [comment]
Hi @cormacpayne, I already reported this issue to @rokmicrosoft. After updating AzureRM to version 6.0.1 I can confirm I no longer see this issue.
