### ISSUE TITLE
get-azurermdiagnosticsetting does not recognize Diagnostic settings from resources created by ARM template

### ISSUE THREAD

**Issue by DirkMSFT** [Azure/azure-powershell#6208]
### Description

get-azurermdiagnosticsetting does not show settings (LogAnalytics Workspace ID etc., see pictures) for resources created by ARM template. Via REST API these settings are available though.
Resources created manually via Portal are shown correctly.

### Script/Steps for Reproduction

Does not work:
PS> $randomresourcecreatedbyARMtemplate | get-azurermdiagnosticsetting

Does work:
PS> $randomresourcecreatedbyPortal | get-azurermdiagnosticsetting

### Module Version

AzureRM Version 6.0.1
Get-AzureRmDiagnosticSetting is part of  AzureRM.Insights. Version: 5.0.0
### Environment Data

Name                           Value
----                           -----
PSVersion                      5.1.17134.48
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.48
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
### Debug Output
No debug oputput
![2018-05-02-logicappwithrest-diagnosticsettingsavailable](https://user-images.githubusercontent.com/39086826/40008578-ec44903a-579f-11e8-86e9-36af53196bec.jpg)
![2018-05-02-logicappwithposh-nodiagnosticsettings](https://user-images.githubusercontent.com/39086826/40008606-f549a7ec-579f-11e8-9960-a85f3e32565a.jpg)

**Comment by MiYanni** [comment]
@gucalder @micongjie Can one of you take a look at this?

**Comment by asheniam** [comment]
Can you try to use the -Name parameter on Get-AzureRmDiagnosticSetting to pass in the name of the diagnostic setting?  Get-AzureRmDiagnosticSetting will default to 'service' for the name of the diagnostic setting.

https://docs.microsoft.com/en-us/powershell/module/azurerm.insights/get-azurermdiagnosticsetting?view=azurermps-6.13.0
