### ISSUE TITLE
ARM cmdlets should support filtering with wildcards

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#621]
Many of the PowerShell core commands enable filtration of objects using wildcards, for example `Get-Process -Name *svc*;`.

The Azure Resource Manager (ARM) PowerShell commands should support filtering using wildcards to provide consistency with the PowerShell "feel." As of right now, there is limited (if any) support for filtering. See screenshot below.

![image](https://cloud.githubusercontent.com/assets/466713/8739344/c90d11d6-2bf7-11e5-8ba5-11208cacf628.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by markcowl** [comment]
@pcgeek86 Thanks for the feedback, Trevor, assigning to the ARM team to investigate

**Comment by ravbhatnagar** [comment]
We dont plan to support this feature ask anytime soon. Hence closing this issue at this time.
