### ISSUE TITLE
New-AzureKeyVaultCertificateOrganizationDetails example shows parameters that do not exist

### ISSUE THREAD

**Issue by strtdusty** [Azure/azure-powershell#6215]
### Description
Example 1 on the New-AzureKeyVaultCertificateOrganizationDetails.md page shows the commandlet allowing you to set Name, Address1, City, State etc. Those properties don't exist in the commandlet. I wish they did, but they don't. If you run the example verbatim you will get an error about missing parameters.

https://github.com/Azure/azure-docs-powershell/blob/38f06bfa6d78bf80660e6da314839ff16e24d9f7/azurermps-6.0.0/AzureRM.KeyVault/New-AzureKeyVaultCertificateOrganizationDetails.md

**Comment by cormacpayne** [comment]
@RandalliLama @maddieclayton @dragav would one of you mind taking a look at this quick documentation update?

**Comment by maddieclayton** [comment]
Done
