### ISSUE TITLE
How do I check if Web App exists (globally) before creating that?

### ISSUE THREAD

**Issue by RonakThakkar** [Azure/azure-powershell#622]
Requirement:
I am writing powersheel deployment scripts. I would like to check if that WebApp already exists before creating new web app. Currently there is no powershell cmdlet to check if WebApp exists globally.

Hence to solve that problem I first use Get-AzureWebApp to check if WebApp exists or not. But the problem is that Get-AzureWebApp takes -ResourceGroupName and checks only if the Web App exists in that Resource Group and not globally.

Is there a cmdlet that can achive this? Can we make -ResourceGroupName as optional parameter and then search Web App name globally.

**Comment by NaveenGoli** [comment]
You can query all resource groups and check one group at a time,

Sent from my cool Windows Phone
________________________________

**Comment by RonakThakkar** [comment]
Azure might have thousands of resource group and that does not seem to be a feasible idea. My script would take a long time to check if web app exists using that approach. Is that possible to have a cmdlet that can check if WebApp exists or not globally.

**Comment by markcowl** [comment]
@RonakThakkar  Are you asking about resource name, or about the domain name for the web app?

**Comment by MattAllison** [comment]
Does Test-AzureName not work for that service type?  I know it works for Cloud Services and Storage.

**Comment by cormacpayne** [comment]
Closing this issue due to a lack of activity. Please feel free to re-open the issue if you still have any questions.
