### ISSUE TITLE
[Compute] Add resource id parameter set.

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Azure/azure-powershell#6234]
## Introduction
AzurePs Team is working on applying the resource-id [tab completer](https://github.com/Azure/azure-powershell/issues/5415) to Compute **action cmdlets** having a resource-id parameter referencing a  **top level resources**:

**top level resource** id pattern :
```
/subscriptions/{sub-id}/resourceGroups/{rg-name}/providers/Microsoft.Compute/{service-name}/{resource-name}
```
**action cmdlets**: get, set, remove.

Three services were selected to apply the tab completer:
* AvailabilitySets
* VirtualMachine
* VMSS

## Progress

For the **VirtualMache** service the tab completer got applied to the following cmdlets as they expose resource-id based parameter set:
* RestartAzureVMCommand
* SetAzureVMCommand
* UpdateAzureVMCommand
* VirtualMachineActionBaseCmdlet (base class)

As inherited from VirtualMachineActionBaseCmdlet
* SaveAzureVMImageCommand
* StartAzureVMCommand
* StopAzureVMCommand
* RemoveAzureVMCommand

The [installer](https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/620/artifact/signed/) is available to try the completer out.

## Needs to be done
For the rest of the services to make it possible to apply the completer - **resource-id based parameter set should be added** for the possible candidates of top level resource action cmdlets. Now they identify a resource by resource group and resource name only.
- [ ] AvailabilitySets
    - [ ] GetAzureAvailabilitySetCommand
    - [ ] RemoveAzureAvailabilitySetCommand
    - [ ] UpdateAzureAvailabilitySetCommand
    - [ ] missed cmdlets
- [ ] VMSS
    - [ ] VirtualMachineScaleSetPerformMaintenance
    - [ ] VirtualMachineScaleSetPowerOff
    - [ ] VirtualMachineScaleSetRedeploy
    - [ ] VirtualMachineScaleSetReimage
    - [ ] VirtualMachineScaleSetReimageAll
    - [ ] VirtualMachineScaleSetRestart
    - [ ] VirtualMachineScaleSetStart
    - [ ] VirtualMachineScaleSetUpdate
    - [ ]  missed cmdlets

**Comment by MiYanni** [comment]
This work will be handled by the generator.
