### ISSUE TITLE
"Invoke-Hive" has not "-endpoint" param

### ISSUE THREAD

**Issue by zhongyi-zhang** [Azure/azure-powershell#624]
"Invoke-Hive" has not "-endpoint" param. So the Mooncake can't use it.

**Comment by markcowl** [comment]
@v-zhongz Thank you for the feedback.  Assigning to the service team to investigate

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
