### ISSUE TITLE
Remove excess module loading in test controllers

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#6242]
There is a `SetupModules` step that is in the test controller for each module. It seems that... if the RP uses the management library from another RP, they were also loading in the module of that RP. This is not correct. In 95% of these cases, they don't need to load the module of the other RPs, since they usually aren't doing direct calls in the PowerShell test scripts to the cmdlets of those other RPs.

So, prior to the test driver refactoring, cleaning this up should help reduce a bit of the setup time for each module test set. Example:
![image](https://user-images.githubusercontent.com/17788297/40152107-a4626cc0-5938-11e8-9a2a-8fe2f5a046e2.png)

**Comment by maddieclayton** [comment]
Closing, as this will be part of the new centralized Test Controller.
