### ISSUE TITLE
Have Strategy library use common management dependencies

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#6251]
Currently, the Strategy library is using direct management library dependencies. It should, instead, use the Common versions of those libraries.

- [ ] Use `Commands.ResourceManager.Common` instead of `Microsoft.Azure.Management.ResourceManager`
- [ ] Use `Commands.Common.Compute` instead of `Microsoft.Azure.Management.Compute`
- [ ] Use `Commands.Common.Network` instead of `Microsoft.Azure.Management.Network`

This applies as long as the library remains in the PowerShell repo. It will cause issues for NetCore when management library versions are updated for the respective modules.

**Comment by maddieclayton** [comment]
Closing as it looks like this is fixed.
