### ISSUE TITLE
`New-AzureRmAks` should declare proper output type.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#6260]
### Description

`Get-AzureRmAks` declares `List<PSKubernetesCluster>` as its output type, and it should not be a concrete list (see [here](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Aks/Commands.Aks/Commands/GetAzureRmAks.cs#L28)).

### Module Version

6.0.0

**Comment by EdisonDa** [comment]
Thank you Aaron. When the bug get fixed, we may have to manually sync [this doc](https://docs.microsoft.com/en-us/powershell/module/azurerm.aks/Get-AzureRmAks?view=azurermps-6.0.0) from source to docs repo.

**Comment by maddieclayton** [comment]
@twitchax Actually, we don't need to have a "list" output for the output type at all - all that output type does is allow the user to tab through properties.  I'll update the file to ```[OutputType(typeof(PSKubernetesCluster)))]``` - looks like the help file is fine, unless you guys think otherwise.

**Comment by twitchax** [comment]
@maddieclayton, sorry, my comment was a little confusing.  I just meant that it should not be a concrete list, even if we did need it to be a list, which we don't. :)

**Comment by maddieclayton** [comment]
Fixed
