### ISSUE TITLE
AzureDiskEncryptionPreRequisiteSetup.ps1 doesn't handle regions with spaces in name

### ISSUE THREAD

**Issue by thwpike** [Azure/azure-powershell#6269]
### Description

When trying to enable Azure Disk Encryption, the the Virtual machine reports its' region without a space, whilst the keyVault does resulting in the following error:

```
To enable AzureDiskEncryption, VM and KeyVault must belong to same subscription and same region. vm Location:  australiaeast , keyVault Location: australia east
At line:235 char:182
+ ... ion.ToLower()) , keyVault Location: $($keyVault.Location.ToLower())";
+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
```
This appears to be an issue with [this line](https://github.com/Azure/azure-powershell/blob/45c4e123694ef8b3cd0eaf19f1e95bbe7b07b424/src/ResourceManager/Compute/Commands.Compute/Extension/AzureDiskEncryption/Scripts/AzureDiskEncryptionPreRequisiteSetup.ps1#L233) which should also strip any spaces from the comparison.

**Comment by maddieclayton** [comment]
@ejarvi @SudhakaraReddyEvuri Can you take a look at this issue?

**Comment by SudhakaraReddyEvuri** [comment]
@thwpike  , @maddieclayton this is fixed now. Please get the latest script. Thanks for pointing this to us.
