### ISSUE TITLE
ARM SQL: Vague error message

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#629]
## Symptom

When you call one of the ARM `*SQLServer*` cmdlets, a vague error message is returned, if the API cannot find the SQL Server.

> Get-AzureSqlServer : : Resource not found for the segment 'servers'.
At line:1 char:1
+ Get-AzureSqlServer -ResourceGroupName RGName -ServerName ServerName;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureSqlServer], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.Server.Cmdlet.GetAzureSqlServer 

![image](https://cloud.githubusercontent.com/assets/466713/8785117/c4de03ac-2ee2-11e5-9be4-44dbe0475a1c.png)

### Example Failure

```
$Cred = Get-Credential;
Set-AzureSqlServer -ResourceGroupName <RGName> -ServerName <ServerName> -SqlAdministratorPassword $Cred.Password;
```

## Expected Result

1. ARM entities should not be case sensitive, to keep consistent with PowerShell language
  - Resource Groups are not case sensitive, hence SQL Servers should not be case sensitive
2. A more helpful error message should be returned for invalid entities.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by akromm** [comment]
Fixes for both of these issue are actively being worked on.  They will be fixed by the time the ARM SQL APIs exit preview.
