### ISSUE TITLE
`Get-AzureRmIotHubCertificate` should declare the output type

### ISSUE THREAD

**Issue by EdisonDa** [Azure/azure-powershell#6299]
### Description

- The GitHub source file: 

- https://raw.githubusercontent.com/Azure/azure-powershell/preview/src/ResourceManager/IotHub/Commands.IotHub/help/Get-AzureRmIotHubCertificate.md.

It defines the output type like this:
`
System.Collections.Generic.IList`1[[Microsoft.Azure.Commands.Management.IotHub.Models.PSCertificateDescription, Microsoft.Azure.Commands.IotHub, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]]
`
Seems the issue does not happen in this page only, could we fix it all of them?

**Comment by EdisonDa** [comment]
@twitchax could you please take a look at this?

**Comment by twitchax** [comment]
Fixing here: Azure/azure-powershell#6301.
