### ISSUE TITLE
Powershell ISE Crashes - Intellisense broken

### ISSUE THREAD

**Issue by Emrikol01** [Azure/azure-powershell#6320]
My Powershell environment is vital to my work and unfortunately has become very unstable. 

The intellisense is now completely broken. 
If I type ctr-space the ISE crashes out everytime. 

Please provide steps to repair my environment (yes I already ran repair etc. etc. etc.)?

Get-Module -Name AzureRM -ListAvailable
ModuleType Version    Name   ExportedCommands
---------- -------    ----     ----------------
Script     6.1.1      AzureRM       

$PSVersionTable
Name                                     Value 
----                                         ----- 
PSVersion                                5.1.17134.1 
PSEdition                                 Desktop     
PSCompatibleVersions            {1.0, 2.0, 3.0, 4.0...} 
BuildVersion                            10.0.17134.1  
CLRVersion                                4.0.30319.42000 
WSManStackVersion                  3.0  
PSRemotingProtocolVersion      2.3  
SerializationVersion                    1.1.0.1

**Comment by kilasuit** [comment]
Have you recently updated to the 1803 Windows 10 release? (looks like it from the build version) There's been some issues with PowerShell ISE on that build but I believe there was a recent KB that was released that should have fixed this

**Comment by cormacpayne** [comment]
@Emrikol01 Hey Norman, this repository is for Azure PowerShell modules and cmdlets; I would recommend posting this question in the [PowerShell repository](https://github.com/PowerShell/PowerShell) (or trying Ryan's fix mentioned above 😀)
