### ISSUE TITLE
Get-AzureRmKeyVault uses latest API, which is not compatible to Azure Germany

### ISSUE THREAD

**Issue by gstolz** [Azure/azure-powershell#6321]
### Description

After upgrading to the latest CmdLet set (6.1.0) we now have problems when calling Get-AzureRmKeyVault.

### Script/Steps for Reproduction
on an existing KeyVault we run the following command:

Get-AzureRmKeyVault -VaultName dev2-kv -ResourceGroupName dev2-rg -Debug

### Module Version

Script     5.0.0      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Update-AzureKeyVaultCertificate, Stop-AzureKeyVaultCertificateOperation, Get-AzureKeyVaultCertific...

### Environment Data

PS C:\Windows\system32>  $PSVersionTable

Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.14409.1012                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.14409.1012                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1       

### Debug Output

PS C:\Windows\system32> Get-AzureRmKeyVault -VaultName dev2-kv -ResourceGroupName dev2-rg -Debug
DEBUG: 10:05:20 - GetAzureKeyVault begin processing with ParameterSet 'GetVaultByName'.
DEBUG: 10:05:26 - using account id '152a3cdd-'...
DEBUG: [Common.Authentication]: Authenticating using Account: '152a3cdd-', environment: 'AzureGermanCloud', tenant: '1ddb90d5'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/29/2018 08:05:29: b120b610- - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.de/1ddb90d5-/
	Resource: https://management.core.cloudapi.de/
	ClientId: 152a3cdd-
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (1 items)
	Authentication Target: Client
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/29/2018 08:05:29:  - TokenCache: Deserialized 1 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/29/2018 08:05:29: b120b610- - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/29/2018 08:05:29: b120b610- - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/29/2018 08:05:29: b120b610- - TokenCache: 59.5138044133333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/29/2018 08:05:29: b120b610- - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/29/2018 08:05:29: b120b610- - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: 
	Refresh Token Hash: [No Refresh Token]
	Expiration Time: 05/29/2018 09:05:00 +00:00
	User Hash: null
	

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.microsoftazure.de/subscriptions/f291673a-/resourceGroups/dev2-rg/providers/Microsoft.KeyVault/vaults/dev2-kv?**api-version=20
18-02-14-preview**

Headers:
x-ms-client-request-id        : 67b6cf3b-
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 7cc62397-
x-ms-correlation-request-id   : 7cc62397-
x-ms-routing-request-id       : GERMANYCENTRAL:20180529T080530Z:7cc62397-
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 29 May 2018 08:05:29 GMT

Body:
{
  "error": {
    "code": "NoRegisteredProviderFound",
    "message": "**No registered resource provider found for location 'germanycentral' and API version '2018-02-14-preview' for type 'vaults'. The supported api-versions are '2015-06-01, 2016-10
-01'. The supported locations are 'germanycentral, germanynortheast'.**"
  }
}

Get-AzureRmKeyVault : No registered resource provider found for location 'germanycentral' and API version '2018-02-14-preview' for type 'vaults'. The supported api-versions are '2015-06-01, 
2016-10-01'. The supported locations are 'germanycentral, germanynortheast'.
At line:1 char:1
+ Get-AzureRmKeyVault -VaultName dev2-kv -ResourceGroupName  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmKeyVault], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.GetAzureKeyVault
 
DEBUG: AzureQoSEvent: CommandName - Get-AzureRmKeyVault; IsSuccess - False; Duration - 00:00:54.4746871; Exception - Microsoft.Rest.Azure.CloudException: No registered resource provider found
 for location 'germanycentral' and API version '2018-02-14-preview' for type 'vaults'. The supported api-versions are '2015-06-01, 2016-10-01'. The supported locations are 'germanycentral, ge
rmanynortheast'.
   bei Microsoft.Azure.Management.KeyVault.VaultsOperations.<GetWithHttpMessagesAsync>d__8.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Azure.Management.KeyVault.VaultsOperationsExtensions.<GetAsync>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Azure.Management.KeyVault.VaultsOperationsExtensions.Get(IVaultsOperations operations, String resourceGroupName, String vaultName)
   bei Microsoft.Azure.Commands.KeyVault.Models.VaultManagementClient.GetVault(String vaultName, String resourceGroupName, ActiveDirectoryClient adClient)
   bei Microsoft.Azure.Commands.KeyVault.GetAzureKeyVault.ExecuteCmdlet()
   bei Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 10:06:15 - GetAzureKeyVault end processing.
DEBUG: 10:06:15 - GetAzureKeyVault end processing.

**Comment by maddieclayton** [comment]
@RandalliLama @schaabs Is this a known issue in the new API version?

**Comment by maddieclayton** [comment]
Thanks @schaabs! Please let me know when the fix is deployed, and I will then close this issue.

**Comment by gunnarstolz** [comment]
Thanks for the feedback!
In the meantime we switch back to the previous version of AzureRM.KeyVault, which seems to be 4.3. This works ok

`
Uninstall-Module -Name AzureRM.KeyVault -AllVersions -Force
Install-Module -Name AzureRM.KeyVault -MaximumVersion 4.9
`

**Comment by maddieclayton** [comment]
@schaabs Is this fixed in the new SDK version? If so, I'll close this issue.

**Comment by schaabs** [comment]
Yes the issue has been fixed.  Closing the issue.
