### ISSUE TITLE
ARM 0.9.5 :: No documentation for Register-AzureProvider

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#633]
The `Register-AzureProvider` command has zero documentation.

![2015-07-21 15_56_50-calendar](https://cloud.githubusercontent.com/assets/466713/8813496/34ec143e-2fc1-11e5-8fd0-ed6ae987ae91.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by ravbhatnagar** [comment]
Update documentation

**Comment by markcowl** [comment]
@ravbhatnagar @vivsriaus this is still outstanding, can we get this fixed for the March 30 release?

**Comment by vivsriaus** [comment]
@markcowl this was fixed in the March release. Here is the PR: https://github.com/Azure/azure-powershell/pull/1851. Note that the cmdlet name was changed to RmResourceProvider

**Comment by pcgeek86** [comment]
@vivsriaus @ravbhatnagar @markcowl I don't see any documentation for Synopsis, Description, or input parameters. I'm only seeing changes pertaining to examples in your Pull Request. This isn't adequate for merging.

**Comment by ravbhatnagar** [comment]
Fixed in Apr Rel
