### ISSUE TITLE
`Invoke-AzureRmResourceAction` missing examples.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#6335]
### Description

From MicrosoftDocs/azure-docs#9364 :

> GitHub Feedback system is not yet integrated into following, hence creating issue like this
https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/invoke-azurermresourceaction?view=azurermps-6.1.0
> Example section is empty.. this is very powerful command and can be used predominantly with good examples.

**Comment by twitchax** [comment]
@cormacpayne for FYI and assignment to ARM.

**Comment by mganeshphani** [comment]
Thankyoi

**Comment by markcowl** [comment]
@ravbhatnagar @vivsriaus Can you guys add the suggested examples?

**Comment by cormacpayne** [comment]
CC: @Tiano2017

**Comment by blueelvis** [comment]
@markcowl @cormacpayne - I think we really need these examples. One particular is how to setup diagnostics on an NSG when `Set-AzureRmDiagnostics` is not working ;)
