### ISSUE TITLE
Enable-AzureRmContextAutosave documentation is unclear

### ISSUE THREAD

**Issue by iricigor** [Azure/azure-powershell#6339]
### Function Description

[Description ](https://docs.microsoft.com/en-us/powershell/module/azurerm.profile/enable-azurermcontextautosave) of **Enable-AzureRmContextAutosave** command says:

`Allow the azure credential, account and subscription information to be saved and automatically loaded when you open a PowerShell window.`

But later, description for `-Scope` parameter says

`Determines the scope of context changes, for example, whether changes apply only to the current process, or to all sessions started by this user`

### Points to be clarified

1. What it brings to me if those objects are loaded, am I logged in to Azure?
1. When is this context saving happening: on enabling, on login, periodically, on process exit, or what?
1. In the description, it speaks about "you opening a new window", which makes entire parameter `-Scope` meaningless. 
1. Parameter `-Scope` has no default value, so I do not understand in which scope it is executed if I don't specify anything here?
1. It would be good to add also some examples which would include full functionality demonstration. Like in one window do this (i.e. enable then login), and in another window do that (i.e. get subscriptions)

**Comment by markcowl** [comment]
- Thanks for the feedback on documentation, we will update, and there are plans for a new conceptual document on managing contexts in the next few weeks.

- Scope does have a default value (CurrentUser).  Any changes made with Scope CurrentUser will impact all powershell sessions started by this user, by default.  Any particular session could exempt itself from teh CurrentUser default by using ```Disable-AzureRmContextAutosave -Scope CurrentProcess``` for example.

- Context save happens at the end of execution of any cmdlet that affects the context (any profile cmdlet).  If you are using user authentication, then tokens can be updated durign the course of runnign any cmdlet.

- Opening a new window means starting a PowerShell process.  If ContextAutoSave is turned on for the current scope, then all cmdlets will use the saved context (if ContextAutoSave is turned on for CurrentUser, then all powershell processes atrted by that user account would use the saved context by default)

**Comment by MiYanni** [comment]
@iricigor We opened up a separate issue for the conceptual docs. We'll take care of the reference docs in this issue.
