### ISSUE TITLE
ARM 0.9.5 :: Get-AzureVirtualNetwork parameter oddness

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#634]
# Symptom

The `Get-AzureVirtualNetwork` command works with no parameters, which is perfect.

If you specify the `-Name` parameter for the `Get-AzureVirtualNetwork`, then it throws an exception saying that `-ResourceGroupName` is `$null`.
# Expected Result

The `Get-AzureVirtualNetwork` command should return virtual networks matching the user-specified value in the `-Name` parameter, without complaining about a `$null` `-ResourceGroupName` parameter.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by devigned** [comment]
It's been tagged and it's being triaged. Thank you for the issue report.

**Comment by vinayakmanda1** [comment]
I am seeing error , what version of ARM i should have ?

PS C:\working> Get-AzureVirtualNetwork
Get-AzureVirtualNetwork : The term 'Get-AzureVirtualNetwork' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-AzureVirtualNetwork
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureVirtualNetwork:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by pcgeek86** [comment]
You're using the classic command. The ARM version is `Get-AzureRmVirtualNetwork`.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
