### ISSUE TITLE
Multiple Diagnostic Settings using PowerShell

### ISSUE THREAD

**Issue by andersonpatricio** [Azure/azure-powershell#6341]
### Description
Using PowerShell we can manage a single diagnostic setting called "Service". It would be nice to expose the **-Name** in PowerShell to allow multiple diagnostic settings.

Also, there is no way to view multiple diagnostic settings using PowerShell.

**Comment by maddieclayton** [comment]
@frankguodongchen @DaleKoetke Can you take a look at this feature request?

**Comment by frankguodongchen** [comment]
@andersonpatricio Could you give more information on which command do you mean? And what you expected the command would like to be? thanks!

**Comment by andersonpatricio** [comment]
Hi Frank,

Sure, I can send them over.

By any chance, are you a Microsoft employee? If yes, I described the commands in our internal DL.

Anyways, here are the threads:

My bad, here is the PowerShell that I used first to configure Event Hubs.

Set-AzureRmDiagnosticSetting -ResourceId '/subscriptions/12439741-0c0d-4de0-aca0-72249fed3346/resourceGroups/AP-CaC-EventHubc/providers/Microsoft.Network/networkSecurityGroups/vm05-nsg' -ServiceBusRuleId '/subscriptions/12439741-0c0d-4de0-aca0-72249fed3346/resourceGroups/AP-CaC-EH1/providers/Microsoft.EventHub/namespaces/eventhub-CanC-SecurityEvents-PROD-ud6jsyk6awoqu-EH/authorizationrules/RootManageSharedAccessKey' -Enabled $True -Categories NetworkSecurityGroupEvent


Then, I ran the following PowerShell to create another entry to configure a storage account.

Set-AzureRmDiagnosticSetting -ResourceId '/subscriptions/12439741-0c0d-4de0-aca0-72249fed3346/resourceGroups/AP-CaC-EventHubc/providers/Microsoft.Network/networkSecurityGroups/vm05-nsg' -StorageAccountId '/subscriptions/12439741-0c0d-4de0-aca0-72249fed3346/resourceGroups/DNS-CLUSTER/providers/Microsoft.Storage/storageAccounts/dnsclusterdiag311' -Enabled $True

Although both worked, they are adding all those settings under service which does not help in my scenario.

If that is the case, the possible workaround is using ARM Templates to achieve multiple diagnostic settings.

————-
I’m trying to enable Diagnostics Logging on several Azure resources using PowerShell, however I noticed that I can’t play with the Name using PowerShell. For example I want to have a different set of categories per target (Event Hubs, Storage Accounts and/or Log Analytics), and I can achieve such flexibility using more than one diagnostic logging.

When I run PowerShell all definitions go straight to service (third line). Is there any way to change such behavior?

My idea is to have a Customer-Storage-SecurityLogs with just Storage Account as target, another one Customer-EventHubs-SecurityLogscontaining just the categories that I want to send to Event Hubs.

[https://prod0-files.acompli.net/attach?iid=AAMkADdhZTZmZmZlLTBjYjUtNGEwYi1hN2Y1LWE3ZDY3NTFiYjk0YgBGAAAAAACvaS9gMiV3QJm8tYGWXCXEBwCrqUjeeaM8T4vD2GyIIBHwAAAAAAEJAACrqUjeeaM8T4vD2GyIIBHwAAAF72fdAAA%3D&itype=Message&aid=AAMkADdhZTZmZmZlLTBjYjUtNGEwYi1hN2Y1LWE3ZDY3NTFiYjk0YgBGAAAAAACvaS9gMiV3QJm8tYGWXCXEBwCrqUjeeaM8T4vD2GyIIBHwAAAAAAEJAACrqUjeeaM8T4vD2GyIIBHwAAAF72fdAAABEgAQANCNApdqDyZEuKPpymKFBm4%3D&account_id=4]

Sent from my iPhone

On May 30, 2018, at 4:39 PM, Frank Chen <notifications@github.com<mailto:notifications@github.com>> wrote:


@andersonpatricio<https://github.com/andersonpatricio> Could you give more information on which command do you mean? And what you expected the command would like to be? thanks!

**Comment by maddieclayton** [comment]
Reassigning to the Insights team.

@gucalder Can you take a look at this issue?

**Comment by andersonpatricio** [comment]
Hi guys,

Do you need my help with anything?

Sent from my iPhone

On May 30, 2018, at 17:29, Maddie Clayton <notifications@github.com<mailto:notifications@github.com>> wrote:


Reassigning to the Insights team.

@gucalder<https://github.com/gucalder> Can you take a look at this issue?

**Comment by animetauren** [comment]
Are there any more updates on this @gucalder ? This is a very much needed feature.

**Comment by gucalder** [comment]
This feature will be released in the next iteration of PowerShell.
The change was merged around 3 weeks ago.
Before that the portal and calls to the REST API could do the trick with named diagnostic settings.

**Comment by praries880** [comment]
Fixed in PR : https://github.com/Azure/azure-powershell/pull/6477

**Comment by praries880** [comment]
changes are already out in the released module : https://www.powershellgallery.com/packages/AzureRM.Insights/5.1.0

**Comment by DirkBrinkmann** [comment]
Sorry guys, but the new Module 5.1.0 DOES NOT WORK. If you specify -name or not, you will always get the resulting error: The diagnostic setting 'service'
doesn't exist., Code: ResourceNotFound, Status code:NotFound, Reason phrase: Not Found
