### ISSUE TITLE
Error running Invoke-AzureRmVmRunCommand: VM has reported a failure when processing extension 'RunCommandWindows'

### ISSUE THREAD

**Issue by muntaserq** [Azure/azure-powershell#6343]
### Description

We are trying to run Invoke-AzureRmVmRunCommand on some of our VMs. The command words on most of the VMs but on some of them we are getting a really weird error. We just started seeing it recently 05/29/2018 and it is consistent on the particular VMs. 

ErrorMessage: VM has reported a failure when processing extension 'RunCommandWindows'. Error message: "Finished 
executing command". (full stack trace below)

### Script/Steps for Reproduction

```
$response = Invoke-AzureRmVMRunCommand -ResourceGroupName $ResourceGroupName -VMName $WebServer.Name -CommandId 'RunPowerShellScript' -ScriptPath 'Set-MyScriptName.ps1' -Parameter $parameters
```

### Module Version

Version is 5.0.1

### Debug Output

```
Invoke-AzureRmVMRunCommand : Long running operation failed with status 'Failed'. Additional Info:'VM has reported a 
failure when processing extension 'RunCommandWindows'. Error message: "Finished executing command".'
ErrorCode: VMExtensionProvisioningError
ErrorMessage: VM has reported a failure when processing extension 'RunCommandWindows'. Error message: "Finished 
executing command".
StartTime: 5/29/2018 5:21:26 PM
EndTime: 5/29/2018 5:21:49 PM
OperationID: ee5db740-9a3d-44fc-9934-2d4759d51e46
Status: Failed
```

**Comment by maddieclayton** [comment]
@koralski @savyasachisamal Can you take a look at this issue?

**Comment by muntaserq** [comment]
I figured out this was an issue with how I was handling parameters and strings into the Invoke-AzureRmVMRunCommand call. It would be really nice if the output actually propagated the error to the console window. 

Ok to close this ticket.

**Comment by phillipgibson** [comment]
@muntaserq So what exactly resolved the issue involving the params for Invoke-AzureRmVMRunCommand?

**Comment by justinsmits** [comment]
bump^ @muntaserq

**Comment by kaveaa** [comment]
bump^ @muntaserq

**Comment by muntaserq** [comment]
> @muntaserq So what exactly resolved the issue involving the params for Invoke-AzureRmVMRunCommand?

In this specific context, I had to build up my $parameters HashTable a little differently. 

Instead of doing:
```
$parameters =  @{"Output" = "This is test output" }
```
I had to do: 
```
$parameters =  @{"Output" = "`"This is test output`"" }
```

This was the recommendation I got from an Azure Support Engineer. This seems to only be the case when using on parameter in the script. All that being said, I've since moved over to using the latest stable version of the AzureRm PowerShell modules and all my issues with that module have gone away. I use version 6.13.1 and of course you can find all the versions here: https://github.com/Azure/azure-powershell/releases.

**Comment by kaveaa** [comment]
Thanks a lot Muntaser! We are going to try that, we are indeed writing some output.



Kind Regards, vriendelijke groeten,

Koen van Amerongen
Engineer DevOps Infra

[Image result for azure new logo] Azure. Cloud for all.


CIO | Cloud Service & Hosting | Cloud Integration

T +31 10 51 343 59
M +31 683635464
E Koen.van.Amerongen@nn-group.com<mailto:Koen.van.Amerongen@nn-group.com>


Location code HP A 10
Schenkkade 65
2595 AS The Hague
The Netherlands

P.O. Box 90570
Location code HP D08
2509 LL The Hague
The Netherlands

**Comment by muntaserq** [comment]
@kaveaa You're welcome. Also make sure that there are no syntax errors in your PowerShell script. I've seen the case when this error returns and there ends up being an error in the actual script. One troubleshooting method is to remote desktop into the target virtual machine and view the status of the `Invoke-AzureRmVmRunCommand` call. To do that, navigate to `C:\Packages\Plugins\Microsoft.CPlat.Core.RunCommandWindows\1.1.0\Status` and view the latest run status output.
