### ISSUE TITLE
[stack] Rename client cmdlets to have "Az" prefix 

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#6344]
### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by muzzar78** [comment]
Will all the cmdlet prefixes be updated? I was wondering why this was labeled 'Azure Stack'. Typing AzureRm over and over is painful.

**Comment by deathly809** [comment]
@muzzar78 This is to update the Azure Stack modules to use the updated Azure cmdlets, i.e Az instead of AzureRM.  I assume the Azure team is changing all cmdlets, otherwise some would have AzureRM and others would have Az.

**Comment by knithinc** [comment]
When we move to the newly autogenerated Az modules, this will happen.
