### ISSUE TITLE
ARM 0.9.5 :: Get-AzureSqlServer requires -ResourceGroupName parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#635]
# Symptom

The `Get-AzureSqlServer` command requires the `-ResourceGroupName` parameter.
# Expected Results

The `Get-AzureSqlServer` command should not require the `-ResourceGroupName` parameter.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by devigned** [comment]
It's been tagged and it's being triaged. Thank you for the issue report.

**Comment by akromm** [comment]
@pcgeek86 Its been a while, but I've started working on this :)

**Comment by akromm** [comment]
#4188 has been merged and will be in the next powershell release!

**Comment by cormacpayne** [comment]
This fix can be found in [version 4.2.0](https://github.com/Azure/azure-powershell/releases/tag/v4.2.0-July2017) of Azure PowerShell.
