### ISSUE TITLE
WebApp: Get-AzureRmWebAppMetrics & Get-AzureRmAppServicePlanMetrics documentation example is incorrect

### ISSUE THREAD

**Issue by gabe-rivera** [Azure/azure-powershell#6352]
### Description

I'm seeing an issue using the Get-AzureRmWebAppMetrics cmdlet on the latest version of the AzureRM module. Other cmdlets I've tried finish without any issues. My issue is similar to #6261 however I am getting different errors when running "Resolve-AzureRmError". The full debug output makes it seem like an issue parsing the XML response to JSON.

### Error
```powershell
PS C:\WINDOWS\system32> Get-AzureRmWebAppMetrics -ResourceGroupName XXXX -Metrics AverageResponseTime -StartTime ((get-date).AddHours(-1)) -EndTime (get-date) -Granularity PT1M -Name XXXX
Get-AzureRmWebAppMetrics : Unable to deserialize the response.
At line:1 char:1
+ Get-AzureRmWebAppMetrics -ResourceGroupName XXXX -Metrics AverageResp ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmWebAppMetrics], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.GetAzureWebAppMetricsCmdlet
```

### Module Version

```powershell
PS C:\WINDOWS\system32> Get-Module -Name AzureRM -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                  
---------- -------    ----                                ----------------                                                  
Script     6.1.1      AzureRM                                                                                               
Script     6.0.1      AzureRM                                                                                               
Script     5.7.0      AzureRM                                                                                               
```

### Environment Data

```powershell
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value                                                                                        
----                           -----                                                                                        
PSVersion                      5.1.17134.81                                                                                 
PSEdition                      Desktop                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                      
BuildVersion                   10.0.17134.81                                                                                
CLRVersion                     4.0.30319.42000                                                                              
WSManStackVersion              3.0                                                                                          
PSRemotingProtocolVersion      2.3                                                                                          
SerializationVersion           1.1.0.1             
```

### Debug Output

```powershell
PS C:\WINDOWS\system32> Resolve-AzureRmError


   HistoryId: 2


Message        : Unable to deserialize the response.
StackTrace     :    at 
                 Microsoft.Azure.Management.WebSites.WebAppsOperations.<ListMetricsWithHttpMessagesAsync>d__101.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.<ListMetricsAsync>d__193.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.ListMetrics(IWebAppsOperations 
                 operations, String resourceGroupName, String name, Nullable`1 details, String filter)
                    at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.GetWebAppUsageMetrics(String 
                 resourceGroupName, String webSiteName, String slotName, IReadOnlyList`1 metricNames, Nullable`1 startTime, 
                 Nullable`1 endTime, String timeGrain, Boolean instanceDetails)
                    at Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.GetAzureWebAppMetricsCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.SerializationException
InvocationInfo : {Get-AzureRmWebAppMetrics}
Line           : Get-AzureRmWebAppMetrics -ResourceGroupName XXXX -Metrics AverageResponseTime -StartTime 
                 ((get-date).AddHours(-1)) -EndTime (get-date) -Granularity PT1M -Name XXXX
Position       : At line:1 char:1
                 + Get-AzureRmWebAppMetrics -ResourceGroupName XXXX -Metrics AverageResp ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
StackTrace     :    at Newtonsoft.Json.JsonTextReader.ParseValue()
                    at Newtonsoft.Json.JsonTextReader.Read()
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, 
                 JsonContract contract, Boolean hasConverter)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type 
                 objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, 
                 JsonSerializerSettings settings)
                    at 
                 Microsoft.Azure.Management.WebSites.WebAppsOperations.<ListMetricsWithHttpMessagesAsync>d__101.MoveNext()
Exception      : Newtonsoft.Json.JsonReaderException
InvocationInfo : {Get-AzureRmWebAppMetrics}
Line           : Get-AzureRmWebAppMetrics -ResourceGroupName XXXX -Metrics AverageResponseTime -StartTime 
                 ((get-date).AddHours(-1)) -EndTime (get-date) -Granularity PT1M -Name XXXX
Position       : At line:1 char:1
                 + Get-AzureRmWebAppMetrics -ResourceGroupName XXXX -Metrics AverageResp ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

```

**Comment by gabe-rivera** [comment]
It appears downgrading the module to 5.7.0 fixes this issue. I still had issues with 6.0.1.

**Comment by maddieclayton** [comment]
@gabe-rivera Will look into this to see if it’s an issue with the cmdlet or an issue with common code - as this has been popping up in multiple places I’m guessing this is likely a common code issue.

**Comment by maddieclayton** [comment]
@panchagnula Can you take a look at this issue?

**Comment by panchagnula** [comment]
Yes will look into this.

**Comment by panchagnula** [comment]
@maddieclayton just to be sure 6.0.1 version has websites-preview included, correct?

**Comment by maddieclayton** [comment]
AzureRM will never have preview modules - it will always include the latest stable release.

**Comment by panchagnula** [comment]
@maddieclayton i should i have been clearer with my question, the issue states that downgrading to version 5.7.0 fixes the issue & the difference b/w this version & the later ones is that we integrated the previous websites-preview to stable. However, i will investigate further.

**Comment by maddieclayton** [comment]
@panchagnula Apologies, did not understand the question.  As the preview was merged into stable in time for 6.0.0, it was definitely included in the AzureRM.6.0.1 release.

**Comment by MisinformedDNA** [comment]
How do I downgrade? I keep finding solutions that don't actually work. (grrrr)

**Comment by panchagnula** [comment]
@gabe-rivera  & @MisinformedDNA please run the command without the parenthesis or spaces in the metrics names i.e if you are running Ex.
 Get
-AzureRmAppServicePlanMetrics -ResourceGroupName "someName" -Name "someName" -StartTime 2018-07-04T22:00:00z -EndTime 2018-07-04T22:30:00z -Granularity PT1M -Metrics "CPUPercentage"


the documentation example is incorecct & infact using the parenthesis or spaces with the older version doesn't work either - so downgrading will not help either. We will get our documentation updated

**Comment by MisinformedDNA** [comment]
@panchagnula Contrary to what you said, @gabe-rivera and I both downgraded to 5.7 and subsequently got past this error.

**Comment by panchagnula** [comment]
@MisinformedDNA interesting since I have tried with the version 5.7.0 & I did not get it to work with the spaces & parenthesis in the metric name

PS C:\Users\sisirap> Get-Module -Name AzureRM -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.7.0      AzureRM

**Comment by MisinformedDNA** [comment]
Oh, you mean the brackets? With the brackets, it doesn't error out, but it also doesn't return any metrics. Removing the brackets returns the expected metrics. What's confusing is that the OP didn't have any spaces or brackets and it still failed, how come?

BTW: I already discussed some of this with support (ticket 118062218445703), but wanted to follow up here for anyone else running into the issue.

**Comment by maddieclayton** [comment]
@panchagnula Ping

**Comment by Pilosite** [comment]
Hi,

I have the exact same issue with AzureRM 6.6.0 and AzureRM.Websites 5.0.6, using the updated Metric Name.

Also, is there a way to get the available metrics ? the error message is far from obvious. Thks !

PS C:\Users\adminOffice> get-module AzureRM -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                     
---------- -------    ----                                ----------------                                     
Script     6.6.0      AzureRM                                                                                  



PS C:\Users\adminOffice> get-module AzureRM.WebSites -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                     
---------- -------    ----                                ----------------                                     
Script     5.0.6      AzureRM.Websites                    {Get-AzureRmAppServicePlan, Set-AzureRmAppServiceP...


Command : 

PS C:\Users\adminOffice> Get-AzureRmAppServicePlanMetrics -ResourceGroupName "Prod-FR" -Name "Front-FR-01" -StartTime 2018-07-04T22:00:00z -EndTime 2018-07-04T22:30:00z -Granularity PT1M -Metrics "CPUPercentage"
Get-AzureRmAppServicePlanMetrics : Unable to deserialize the response.
At line:1 char:1
+ Get-AzureRmAppServicePlanMetrics -ResourceGroupName "Prod-FR" -Name " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmAppServicePlanMetrics], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.GetAzureAppServicePlanMetricsCm 
   dlet

**Comment by prabhakarreddy1234** [comment]
Is it fixed ? I am getting this exception in  Azure Runbook but working locally.   Can't update AzureRM version in Azure Automation as it has so many dependent modules and all needs to be updated before updating AzureRM version to latest. by the way i created Azure Automation account just now with default options.

**Comment by yesveesteps** [comment]
> It appears downgrading the module to 5.7.0 fixes this issue. I still had issues with 6.0.1.

How did you downgraded the module? could you please share the steps?

**Comment by yesveesteps** [comment]
> @panchagnula Contrary to what you said, @gabe-rivera and I both downgraded to 5.7 and subsequently got past this error.

how did you downgraded? could you please share the steps? my module version is 

PS C:\Users> Get-Module -Name AzureRM -ListAvailable

ModuleType Version    Name                                ExportedCommands                                                                 
---------- -------    ----                                ----------------                                                                 
Script     6.4.0      AzureRM
