### ISSUE TITLE
Creating a new binding via New-AzureRmWebAppSSLBinding uploads the certificate to incorrect webspace if the site has been migrated from its original resource group

### ISSUE THREAD

**Issue by nmallick1** [Azure/azure-powershell#6354]
### Description

Creating a new binding via New-AzureRmWebAppSSLBinding uploads the certificate to incorrect webspace if the site has been migrated from its original resource group

### Script/Steps for Reproduction
1. Create a website and an ASP
2. Migrate both the website and ASP to a different resource group under the same subscription
3. Use the  New-AzureRmWebAppSSLBinding to create an SSL binding for this webapp and supply the cert. The cert object will be uploaded however it will have the webspace computed as per default computation and will not take into account the webspace of the ASP. Due to this, the binding fails to add as the certificate is no where to be found within the same webspace.

### Module Version
Latest Version

**Comment by maddieclayton** [comment]
@panchagnula Can you take a look at this issue?

**Comment by panchagnula** [comment]
@naveedaz , this is the other issue with SSL certs & migration, that might need the API to be updated for.

**Comment by panchagnula** [comment]
The fix for this is in the following releasehttps://github.com/Azure/azure-powershell/releases/tag/v1.2.0-January2019
