### ISSUE TITLE
Problems with 'invoke-command' with parameters running as a job - Powershell

### ISSUE THREAD

**Issue by diegopietruszka** [Azure/azure-powershell#6359]
I was dealing with this for a couple of days already, so I guess I need some help (Anything would be really appreciate it).

I can run the below command without any problem:

`Invoke-Command -ScriptBlock { param($rgName,$VMname) Get-AzureRmVM -Name $VMname -ResourceGroupName $rgName} -ArgumentList $rgname,$vmname`

But what I really need is to be able to run the command as a job, so I tried the below:

`Invoke-Command -ScriptBlock { param($rgName,$VMname) Get-AzureRmVM -Name $VMname -ResourceGroupName $rgName} -ArgumentList $rgname,$vmname -AsJob`

And I'm receiving the following error:

 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Invoke-Command : Parameter set cannot be resolved using the specified named parameters.
 At line:1 char:1
 Invoke-Command -ScriptBlock { param($rgName,$VMname) Get-AzureRmVM -N ...
     + CategoryInfo          : InvalidArgument: (:) [Invoke-Command], ParameterBindingException
     + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.PowerShell.Commands.InvokeCommandCommand
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
I've also tried to run the command using start-job instead but I'm also receiving errors.

Thanks to everybody.

**Comment by maddieclayton** [comment]
Hi @diegopietruszka! This looks to be an issue with the underlying powershell command “invoke-command”.  When looking at the [cmdlet page](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/invoke-command?view=powershell-6) I see that the default parameter set (the first) doesn’t have -AsJob, so your first command runs without problem, choosing the default. However, with -AsJob, the command can’t choose between the 2nd, 4th, and 6th parameter sets. My recommendation would be to see if one of those parameter sets has a unique value that you can use to make PowerShell differentiate the parameter sets.  More importantly, you should definitely open this same issue on the [powershell page](https://github.com/PowerShell/PowerShell), as it seems from your use case that -AsJob should be included in the default parameter set (and they may have a better recommendation than I do for resolving your issue quickly).

**Comment by maddieclayton** [comment]
Closing this issue as it is a PowerShell cmdlet issue rather than an Azure PowerShell cmdlet issue.
