### ISSUE TITLE
ARM 0.9.5 :: Get-AzureLocalNetworkGateway requires -ResourceGroupName parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#636]
# Symptom

The `Get-AzureLocalNetworkGateway` command requires the `-ResourceGroupName` parameter.
# Expected Results

The `Get-AzureLocalNetworkGateway` command should not require the `-ResourceGroupName` parameter.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by devigned** [comment]
It's been tagged and it's being triaged. Thank you for the issue report.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
