### ISSUE TITLE
Managed Identity/IMDS auth: Configurable retry time-out

### ISSUE THREAD

**Issue by arluca** [Azure/azure-powershell#6363]
Currently, the retry logic in the Azure SDKs for Managed Identity token generation can make the current thread wait for as long as 15 minutes. For response time sensitive services this might not be acceptable. It could also result in service unavailability if all threads are blocked for a token to be generated when a sudden burst arrives after a cold start.
The developer may want to fast fail after certain time interval says for example 10 seconds if the call is still failing.

Can we make the retry max configurable?

**Comment by markcowl** [comment]
@arluca This is the repository for Azure PowerShell, you can find repositories for the authentication libraries in the AzureAD org: https://github.com/AzureAD

**Comment by arluca** [comment]
@Mark<mailto:Mark.Cowlishaw@microsoft.com> & @Yugang<mailto:yugangw@microsoft.com> : which is the correct repo to open this item on? I thought it would be the powershell one.

-Arturo

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by arluca** [comment]
So, from the description in the issue, it sounds like you are asking about the azure sdk.

PowerShell is using its own authentication mechanism for MSI. If you are asking about powershell authentication, you will need to be more specific about how you arrived at this conclusion.

**Comment by yugangw-msft** [comment]
The relevant PR is #5771 and it means the code change should occur in POSH

**Comment by arluca** [comment]
@markcowl : Let me know if anything else is needed for this. Does 2018-06-29 milestone mean when it will be investigated? Or when it will be complete?

**Comment by markcowl** [comment]
@arluca What is the actual ask here?  Are you asking for a retry timeout in the login cmdlet, or a retry timeout in something like an environment variable?

Those who are interested in managing the time it takes to run a script, and timing out after a certain period can run the script inside a Start-Job cmdlet.

**Comment by cormacpayne** [comment]
@arluca ping on the question about from @markcowl

**Comment by maddieclayton** [comment]
Closing this issue as it does not include the actual ask. @arluca Please reopen if this is still an issue, and include the full details regarding your ask.
