### ISSUE TITLE
Start-AzureStorageBlobCopy accept arrays? Or new bulk copy container command

### ISSUE THREAD

**Issue by iyerusad** [Azure/azure-powershell#6364]
**Goal:** Trying to copy blob container to separate container in case storage account gets deleted/snapshot in time/off account copy.
**Env:** Azure Automation Account/Powershell Workflow

**Limitation:** AzCopy appears to allow single request transfer container. AzCopy is not supported in Azure Automation jobs (unless using own hosted worker).

Following command appears to execute one by one:
```
Get-AzureStorageBlob -Context $contextSource -Container "$SourceBlobContainer" | 
Start-AzureStorageBlobCopy -DestContext $contextDestination -DestContainer "$DestBackupContainer"
```

In a container with thousands upon thousands of blobs, this appears to generate alot of request overhead (making a job run for hours!). Same scenario using AzCopy: 9 minutes.

AzCopy appears to copy container to container. Can this be achieved with `Start-AzureStorageBlobCopy` or a new AzureRM command?

**Comment by iyerusad** [comment]
Workaround: I was able to workaround this by:
1. Not outputting `Start-AzureStorageBlobCopy` to console, via `Measure-Command`
1. Appending `-ConcurrentTaskCount 100` to following commands: `Start-AzureStorageBlobCopy` and `Get-AzureStorageBlobCopyState` #used when checking status

This cut the whole extent of my job in Azure Automation account from seemingly endless hours to 4 minutes. ~10k files, ~50MB-ish test data set.

**Comment by blueww** [comment]
@iyerusad 

Good to know that you have workaround the issue.

For Blob Copy, in PowerShell it's server side async copy, which has no SLA. The default ConcurrentTaskCount is 10 and only allows 10 network connection. When you change it to 100, and if the network on you machine is good enough, it will make the copy request send fast.

For AzCopy, default it will also use AsyncCopy, but you can switch it to SyncCopy (download to localmemory and upload) by adding /SyncCopy parameter, and this has SLA. besides that, AzCopy default use cpu core * 8 connections.

**Comment by iyerusad** [comment]
Thanks @blueww , this is good to know. It might be the cpu core (4) * 8 = 24 in AzCopy was enough to better take advantage of the machine's network vs the default 10 in the `Start-AzureStorageBlobCopy` cmdlet.

I think it would be helpful to have a "CopyBlobContainer" cmdlet. `Start-AzureStorageBlobCopy`  is focused on blobs, where as I think there is a strong case for cmdlet specific for the container as a whole. There really shouldn't be any reason one should have to iterate over blobs to clone a blob container.

**Comment by blueww** [comment]
@iyerusad 
For Copy the whole container, Azcopy should be a better choice then powershell.
For powershell, we providet the basic function for blob operation, and user can unitlize the powershell script to copy whole container, or some blobs with specific pattern in the container, or even copy to different account/container.

Anyway, this is the first feature request we see for container copy. As we has some other features in hand, we can consider the feature when there are more customers vote for this feature.

**Comment by iyerusad** [comment]
There are multiple stackoverflow [(1)](https://stackoverflow.com/questions/36579080/use-azcopy-in-azure-automation-job) [(2)](https://stackoverflow.com/questions/29881948/start-azurestorageblobcopy-vs-azcopy-which-one-takes-lesser-time/50651544) questions around this scenario. With containers containing many (10k+) small blobs, it doesn't make much sense to iterate through them one by one to initiate asynchronous copy - some kind of bulk mechanism would be helpful.

Would love to use AzCopy but:
1. Can't run in hosted Azure Automation agents.
2. Is not cross platform (e.g. AzureCLI)

**Comment by blueww** [comment]
@iyerusad 

I will open a work item for Powershell cmdlet of copy a container. And we will evaluate it according to user request and our bandwidth.

But if there are many (10k+) blobs in a container, user can list the blobs in batches and then copy one by one. You can find how to list blobs in batches in last help Example of cmdlet Get-AzureStorageBlob.

For AzCopy, it has cross platform version: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-linux

**Comment by zhusijia26** [comment]
Close the issue due to idle time. Please reopen if there is till question.
