### ISSUE TITLE
Too slow respones from Get-AzureStorageTable, Queue, Share, Blob if they do not exist

### ISSUE THREAD

**Issue by jianyunt** [Azure/azure-powershell#6366]
### Description

If a storageaccount does not have table, queue or fileshare, and you run Get-AzureStorageTable, Get-AzureStorageShare, Get-AzureStorageQueue, you will see each cmdlet take about 27 seconds and then return not found.  It seems to be too long. 

Here is our user scenario:
In our cloudshell Azure navigation, we are calling the above cmdlets and show Blob, File, Queue, and Table directory if they exist. So we can show something like below. If one has blob storage only, it will at least take a user 3 * 27 = 81 seconds (ignore the time on blob it's fast because it exists). That's the problem. The problem persists on pscore /CoreCLR as well. Please consider for the perf improvements around these cmdlets. Thanks!

``` PowerShell
PS Azure:\> dir


    Directory: Azure:\myaccount\StorageAccounts\jianyunacc


Mode Name
---- ----
+    Blobs
+    Files
+    Tables
+    Queues
```

### Script/Steps for Reproduction

```powershell
- go to portal.azure.com and launch Azure cloudshell
- run the following command
 $acc=Get-AzureRmStorageAccount -ResourceGroupName slee -StorageAccountName sleedisks587
       Measure-Command{ Get-AzureStorageQueue -Context $acc.Context}
  	Get-AzureStorageTable : One or more errors occurred. (No such device or address)
	At line:1 char:18
	+ Measure-Command{ Get-AzureStorageTable -Context $acc.Context}
	+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	+ CategoryInfo          : CloseError: (:) [Get-AzureStorageTable], AggregateException
	+ FullyQualifiedErrorId : AggregateException,Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTableCommand
	
	
	
	Days              : 0
	Hours             : 0
	Minutes           : 0
	**Seconds           : 27**
	Milliseconds      : 284
	Ticks             : 272844766
	TotalDays         : 0.000315792553240741
	TotalHours        : 0.00757902127777778
	TotalMinutes      : 0.454741276666667
	TotalSeconds      : 27.2844766
TotalMilliseconds : 27284.4766

```
You can see it took 27 seconds to return.  Try Get-AzureStorageshare or Get-AzureStorageQueue, each will take about 27 seconds too.

### Module Version

```powershell
PS Azure:\> Get-Module -Name AzureRM -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.1.0      AzureRM
```

### Environment Data

```powershell
PS Azure:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```

```

**Comment by blueww** [comment]
@jianyunt 

Since the account don't have Queue/Table/File, when you use get-AzureStorageQueue, it will try to access the queue endpoint which not exist, so the DNS resolving will need some time to fail.


You can use following command to decide if the account has Queue/Table/File:
```PowerShell

 $acc=Get-AzureRmStorageAccount -ResourceGroupName slee -StorageAccountName sleedisks587

if ($acc.PrimaryEndpoints.Queue -ne $null)
{
       Get-AzureStorageQueue -Context $acc.Context
}
if ($acc.PrimaryEndpoints.Table -ne $null)
{
       Get-AzureStorageTable -Context $acc.Context
}
```

**Comment by jianyunt** [comment]
Thank you @blueww for your recommendation. we will try out your approach. Thanks again!

**Comment by markcowl** [comment]
@jianyunt did this resolve your issue?

**Comment by jianyunt** [comment]
Yes the recommended from @blueww works for me. thanks.
