### ISSUE TITLE
Import-AzureRmApiManagementApi can't set displayName of an SOAP API

### ISSUE THREAD

**Issue by ToMakeSense** [Azure/azure-powershell#6370]
``` powershell
Import-AzureRmApiManagementApi
      -Context <PsApiManagementContext>
      [-ApiId <String>]
      [-ApiRevision <String>]
      -SpecificationFormat <PsApiManagementApiFormat>
      -SpecificationPath <String>
      [-Path <String>]
      [-WsdlServiceName <String>]
      [-WsdlEndpointName <String>]
      [-ApiType <PsApiManagementApiType>]
      [-DefaultProfile <IAzureContextContainer>]
      [<CommonParameters>]
```
I am trying to import an SOAP API with [Import-AzureRmApiManagementApi](https://docs.microsoft.com/en-us/powershell/module/azurerm.apimanagement/import-azurermapimanagementapi?view=azurermps-6.1.0), It seems that there's no place to set the name(displayName) of the SOAP API, as a result, the name(displayName) is actually the value of   **WsdlServiceName** 
```powershell
$newAPI = Import-AzureRmApiManagementApi -Context $apimContext -SpecificationFormat Wsdl -SpecificationPath $apiFilePath -Path $api.properties.path -ApiId $api.ApiId -ApiType Soap -WsdlServiceName $api.properties.wsdlServiceName -WsdlEndpointName $api.properties.wsdlEndpointName
```
Then I try to modify it with [Set-AzureRmApiManagementApi](https://docs.microsoft.com/en-us/powershell/module/azurerm.apimanagement/set-azurermapimanagementapi?view=azurermps-6.1.0), this API have transformed to an Non-SOAP api.
```powershell
Set-AzureRmApiManagementApi -Context $apimContext -ApiId $newAPI.ApiId -ServiceUrl $newAPI.ServiceUrl -Protocols $newAPI.Protocols -Name $api.properties.displayName
```

**Comment by solankisamir** [comment]
@ToMakeSense have you tried the option with 
`Set-AzureRmApiManagementApi  -InputObject <PsApiManagementApi>`

**Comment by ToMakeSense** [comment]
@solankisamir  Can you give a example? I'm not that familiar with PowerShell.

**Comment by solankisamir** [comment]
@ToMakeSense I realize there is a bug in powershell in that path

> Set-AzureRmApiManagementApi
  : Missing type map configuration or unsupported mapping.
    Mapping types:
   PsApiManagementApi -> ApiContract
   Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Models.PsApiManagementApi -> 
   Microsoft.Azure.Management.ApiManagement.Models.ApiContract
   At line:1 char:1

I will need to fix it before you can use it.

**Comment by ToMakeSense** [comment]
@solankisamir any updates on this?

**Comment by ToMakeSense** [comment]
@solankisamir any progress?

**Comment by solankisamir** [comment]
@ToMakeSense fix should be out by end of this month.

**Comment by ToMakeSense** [comment]
@solankisamir good news :+1:

**Comment by solankisamir** [comment]
Fixed in release https://github.com/Azure/azure-powershell/releases/tag/v6.6.0-July2018. You should be able to do something like

`Set-AzureRmApiManagementApi -InputObject $api -Name $newName -ServiceUrl $api.ServiceUrl -Protocols $api.Protocols`

`ServiceUrl` and `Protocols` are required parameters due to legacy reasons. We will need to make a breaking change to fix that.
