### ISSUE TITLE
Set-AzureRmApiManagementApiRevision and Update-AzureRmApiManagementApiRelease not work.

### ISSUE THREAD

**Issue by yuhaii** [Azure/azure-powershell#6372]
### Description

Set-AzureRmApiManagementApiRevision and Update-AzureRmApiManagementApiRelease not work.
I have installed latest 6.1.0 packages https://github.com/Azure/azure-powershell/releases/tag/v6.1.0-May2018 

### Script/Steps for Reproduction

PS C:\Users\yuhai> Login-AzureRmAccount

PS C:\Users\yuhai> $ApiMgmtContext = New-AzureRmApiManagementContext -ResourceGroupName "YhTestResourceGroup" -ServiceName "yh-api-management"

PS C:\Users\yuhai> Get-AzureRmApiManagementApi -Context $ApiMgmtContext -Name "echo api"

ApiId                         : echo-api
Name                          : Echo API
Description                   :
ServiceUrl                    : http://echoapi.cloudapp.net/api
Path                          : echo
ApiType                       : http
Protocols                     : {Http}
AuthorizationServerId         :
AuthorizationScope            :
SubscriptionKeyHeaderName     :
SubscriptionKeyQueryParamName :
ApiRevision                   : 1
ApiVersion                    :
IsCurrent                     : True
IsOnline                      : False
Id                            : /subscriptions/548daf3d-81f4-483d-9d08-10787dd5ef2a/resourceGroups/YhTestResourceGroup/
                                providers/Microsoft.ApiManagement/service/yh-api-management/apis/echo-api
ResourceGroupName             : YhTestResourceGroup
ServiceName                   : yh-api-management

PS C:\Users\yuhai> Set-AzureRmApiManagementApiRevision -Context $ApiMgmtContext -ApiId "echo-api" -ApiRevision "3" -Name "Echo API" -ServiceUrl "http://echoapi.cloudapp.net/api" -Protocols @('http') -Path "echo"
Set-AzureRmApiManagementApiRevision : Operation returned an invalid status code 'NotFound'
At line:1 char:1
+ Set-AzureRmApiManagementApiRevision -Context $ApiMgmtContext -ApiId " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmApiManagementApiRevision], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.SetAzureApiManagementApiRevision

### Module Version

PS C:\Users\yuhai> Get-Module -Name AzureRM -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.1.1      AzureRM
Script     6.1.0      AzureRM

### Environment Data

PS C:\Users\yuhai> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Debug Output

```
PS C:\Users\yuhai> Set-AzureRmApiManagementApiRevision -Context $ApiMgmtContext -ApiId "echo-api" -ApiRevision "3" -Name "Echo API" -ServiceUrl "http://echoapi.cloudapp.net/api" -Protocols @('http') -Path "echo"  $DebugPreference = "Cont
inue"
Set-AzureRmApiManagementApiRevision : A positional parameter cannot be found that accepts argument 'SilentlyContinue'.
At line:1 char:1
+ Set-AzureRmApiManagementApiRevision -Context $ApiMgmtContext -ApiId " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-AzureRmApiManagementApiRevision], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.SetAzureApiManagementApiRevision

```

**Comment by markcowl** [comment]
@yuhaii To get the debug output, please set this value before executing any powershell cmdlets:

```powershell
$DebugPreference="Continue"
```

and then execute your script or run your cmdlets.

**Comment by yuhaii** [comment]
@markcowl got it. below is the cmd with debug info

PS C:\Users\yuhai> Set-AzureRmApiManagementApiRevision -Context $ApiMgmtContext -ApiId "echo-api" -ApiRevision "3" -Name
 "Echo API" -ServiceUrl "http://echoapi.cloudapp.net/api" -Protocols @('http') -Path "echo" >> .\Desktop\powershell_debu
g_output.txt
DEBUG: 11:01:11 AM - SetAzureApiManagementApiRevision begin processing with ParameterSet 'ExpandedParameter'.
DEBUG: 11:01:11 AM - using account id 'yuhai@microsoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'yuhai@microsoft.com', environment: 'AzureCloud', tenant:
 '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/06/2018 03:01:11: fa4920da-be51-4f70-9208-7e3c8d655afd - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/06/2018 03:01:11:  - TokenCache: Deserialized 1 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 06/06/2018 03:01:11: fa4920da-be51-4f70-9208-7e3c8d655afd - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/06/2018 03:01:11: fa4920da-be51-4f70-9208-7e3c8d655afd - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 06/06/2018 03:01:11: fa4920da-be51-4f70-9208-7e3c8d655afd - TokenCache: 56.4774967633333 minutes left until
token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/06/2018 03:01:11: fa4920da-be51-4f70-9208-7e3c8d655afd - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/06/2018 03:01:11: fa4920da-be51-4f70-9208-7e3c8d655afd - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: QZd798MAV4jZvMdk96V2okDH/OJbzsnJbAMvYLqzznE=
 Refresh Token Hash: lbI3t/P04UFogMPC0+f/YvnQl2bli2kiFTJHMz9O1nY=
 Expiration Time: 06/06/2018 03:57:40 +00:00
 User Hash: w6P+0slvW3l3OYaSCFJeBJSbvextOtVDxjMtYsfxu7s=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/06/2018 03:01:11: b6705845-57a3-479c-a733-c1de7abcb0e8 - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/06/2018 03:01:11:  - TokenCache: Deserialized 1 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 06/06/2018 03:01:11: b6705845-57a3-479c-a733-c1de7abcb0e8 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/06/2018 03:01:11: b6705845-57a3-479c-a733-c1de7abcb0e8 - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 06/06/2018 03:01:11: b6705845-57a3-479c-a733-c1de7abcb0e8 - TokenCache: 56.477236355 minutes left until token in
 cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/06/2018 03:01:11: b6705845-57a3-479c-a733-c1de7abcb0e8 - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/06/2018 03:01:11: b6705845-57a3-479c-a733-c1de7abcb0e8 - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: QZd798MAV4jZvMdk96V2okDH/OJbzsnJbAMvYLqzznE=
 Refresh Token Hash: lbI3t/P04UFogMPC0+f/YvnQl2bli2kiFTJHMz9O1nY=
 Expiration Time: 06/06/2018 03:57:40 +00:00
 User Hash: w6P+0slvW3l3OYaSCFJeBJSbvextOtVDxjMtYsfxu7s=

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/548daf3d-81f4-483d-9d08-10787dd5ef2a/resourceGroups/YhTestResourceGroup/prov
iders/Microsoft.ApiManagement/service/yh-api-management/apis/echo-api;rev=3?api-version=2018-01-01

Headers:
x-ms-client-request-id        : 42d905ad-0bb9-4632-9b56-ccad0372a746
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : ddfcb0fa-42f1-4857-b291-35ad234c4331
x-ms-ratelimit-remaining-subscription-reads: 14997
x-ms-correlation-request-id   : 3568f7cd-8994-4971-9029-b1f387f9aac1
x-ms-routing-request-id       : SOUTHEASTASIA:20180606T030114Z:3568f7cd-8994-4971-9029-b1f387f9aac1
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Wed, 06 Jun 2018 03:01:14 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "Api not found.",
    "details": null
  }
}

Set-AzureRmApiManagementApiRevision : Operation returned an invalid status code 'NotFound'
At line:1 char:1
+ Set-AzureRmApiManagementApiRevision -Context $ApiMgmtContext -ApiId " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmApiManagementApiRevision], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.SetAzureApiManagementA
   piRevision

DEBUG: AzureQoSEvent: CommandName - Set-AzureRmApiManagementApiRevision; IsSuccess - False; Duration -
00:00:01.2553111; Exception - Microsoft.Azure.Management.ApiManagement.Models.ErrorResponseException: Operation
returned an invalid status code 'NotFound'
   at Microsoft.Azure.Management.ApiManagement.ApiOperations.<GetWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ApiManagement.ApiOperationsExtensions.<GetAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ApiManagement.ApiOperationsExtensions.Get(IApiOperations operations, String
resourceGroupName, String serviceName, String apiId)
   at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.ApiManagementClient.ApiSet(String resourceGroupName,
String servicename, String id, String name, String description, String serviceUrl, String urlSuffix,
PsApiManagementSchema[] urlSchema, String authorizationServerId, String authorizationScope, String
subscriptionKeyHeaderName, String subscriptionKeyQueryParamName, PsApiManagementApi apiObject)
   at
Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.SetAzureApiManagementApiRevision.ExecuteApiManagement
Cmdlet()
   at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.AzureApiManagementCmdletBase.ExecuteCmdlet();
DEBUG: Finish sending metric.
DEBUG: 11:01:13 AM - SetAzureApiManagementApiRevision end processing.
DEBUG: 11:01:13 AM - SetAzureApiManagementApiRevision end processing.

**Comment by solankisamir** [comment]
@yuhaii you will first need to create a apirevision 3, using the cmdlet [New-AzureRmApiManagementRevision](https://docs.microsoft.com/en-us/powershell/module/azurerm.apimanagement/new-azurermapimanagementapirevision?view=azurermps-6.2.0).

The `Set-AzureRmApiManagementRevision` can only work on resources which exist and hence the error `NotFound`

**Comment by yuhaii** [comment]
@solankisamir thank you. I could add revision now. May I know how to set the revision to current? I use following command. But it doesn't work.


PS C:\WINDOWS\system32> $apiRelease = New-AzureRmApiManagementApiRelease -Context $ApiMgmtContext -ApiId "echo-api" -Rel
easeId "echo-api-release" -Note "Releasing version 2 of the echo-api to public" -ApiRevision "5"

![image](https://user-images.githubusercontent.com/39817657/41143085-9ff40f00-6b2a-11e8-826b-13ebb07f7a57.png)

**Comment by yuhaii** [comment]
@solankisamir sorry. I should delete previous first. It works.

$apiRelease = Remove-AzureRmApiManagementApiRelease -Context $ApiMgmtContext -ApiId "echo-api" -ReleaseId "echo-api-release"  

$apiRelease = New-AzureRmApiManagementApiRelease -Context $ApiMgmtContext -ApiId "echo-api" -ReleaseId "echo-api-release" -Note "Releasing version 5 of the echo-api to public" -ApiRevision "5"

**Comment by solankisamir** [comment]
Closing the issue. This was mostly incorrect interpretation of the cmdlets.
