### ISSUE TITLE
[Webapp] Create a command that deploy to webapp using zip deployment

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-powershell#6374]
Create a command that deploy to webapp using zip deployment feature, this will replace the Publish-AzureWebsiteProject command.

Command design: TBD

**Comment by tonjohn** [comment]
Any updates on this? Our team would like to update our publish scripts accordingly (our PPE/PROD deployment are currently blocked due to an issue with Publish-AzureWebsiteProject)

**Comment by AshmaSamaiya** [comment]
do we have nay ETA on when the new command will be available?

**Comment by maddieclayton** [comment]
@panchagnula Can you take a look at this feature request?

**Comment by joshidp** [comment]
Please provide an ETA

**Comment by tonjohn** [comment]
Any updates on this? The existing command randomly fails for us and support keeps telling us to update to the new API. Except.. there isn't a new API...

**Comment by oferze** [comment]
Can this issue be closed now due to #8250 ?

**Comment by maddieclayton** [comment]
Looks like it can! Thanks @oferze, closing now.
