### ISSUE TITLE
NuGet warning when packaging DLLs

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#6376]
When we do a build that creates NuGet packages, we get this warning:
```
Issue: Assembly outside lib folder.
Description: The assembly 'Microsoft.Azure.Commands.Subscription.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
Solution: Move it into the 'lib' folder if it should be referenced.
```

This happens for every external DLL in our NuGet packages. We should determine if there is a way to suppress these specific messages, since this will always be the case, as PowerShell needs them to be at the top level of the project to load.

**Comment by markcowl** [comment]
deferring until we change the way packages are built
