### ISSUE TITLE
Sql: Test-GetReplicationLink and Test-CreateSecondaryDatabase fail to Get-Location appropriately

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#6382]
Previously, these Sql tests were ran using the `Management.ResourceManager` client. Now, they are using the `Management.Internal.Resources` client. `Get-Location` in each of these tests calls `Get-AzureRmResourceProvider` that is within `AzureRM.Resources.ps1`. The provider call here returns $null as the Result. Following the calls, the actual call to `GetWithHttpMessagesAsync` for `ProviderOperations` seems to not return when doing the `SendAsync` to the HttpClient. 

For some reason, during this call stack, a LegacySql client gets created. I thought this to be the issue. However, after explicitly creating this client again (it is currently removed as an explicit creation and uses `SetupSomeOfManagementClients` for NetCore purposes), it did not resolve the issue. So, I don't think the LegacySql client creation is the culprit.

These tests were previously succeeding (or at least no errors were hit) when doing testing on my NetCore branch, prior to merging in the release branch. I haven't found any root cause of the issue. But, for these tests to run the same way they used to, a proper fix needs to be determined.

Edit: When inspecting the call, it routes through the `LongRunningOperation` path. It gets the proper HttpResponse from the call but doesn't do anything with it. It runs `Complete()` and then execution can no longer be followed by a debugger.

**Comment by maddieclayton** [comment]
I am guessing that this has to do with the changed ResourcesClient.  I couldn't find any doubling of Get-Location or Get-AzureRmResourceProvider that would usually cause Get-Location to fail.

**Comment by maddieclayton** [comment]
Fixed.
