### ISSUE TITLE
Versioning scheme - path not available

### ISSUE THREAD

**Issue by pish181** [Azure/azure-powershell#6384]
### Description
Azure Management API 
Where is no any option to automate creation of API versions  using powershell or RM template since versioning scheme 'path'  is not available and not even present in JSON schemas for both solutions.

Announcement from 01/11/2018 says what path should be there 
https://blogs.msdn.microsoft.com/apimanagement/2018/01/11/versions-revisions-general-availibility/

In PS documentation for version 6.1.0 'path' scheme' (according to documentation) does not exist
https://docs.microsoft.com/en-sg/powershell/module/azurerm.apimanagement/set-azurermapimanagementapiversionset?view=azurermps-6.1.0#optional-parameters

-Scheme

Parameter Sets: | Segment, Query, Header
Can you please clarify on this?

Regards,
Pavlo

### Module Version

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.1.0      AzureRM
Script     5.7.0      AzureRM
Script     4.4.1      AzureRM

### Environment Data

```powershell

Name                           Value
----                           -----
PSVersion                      5.1.17677.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17677.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by markcowl** [comment]
@solankisamir Can you take a look?

**Comment by pish181** [comment]
yeap, make sense now, but still no sense to the deployment process since if you fetch API details you can push changes to specific version e.g. I have operation policy which needs to be applied to specific version of the API
any suggestions?
Thank you

**Comment by darrelmiller** [comment]
@pish181 Sorry, I don't understand the question.  APIs with a different version have a different API Id so you should be able to update them independently like any other API.

**Comment by hakant** [comment]
It seems like there's no way to reference a VersionSet from either "New-AzureRmApiManagementApi" or "Import-AzureRmApiManagementApi" in Azure Powershell. So after creating an ApiVersionSet using "New-AzureRmApiManagementApiVersionSet" there seems to be no logical next step. What am I missing here? How do I use the VersionSetId and make an API out of it ? Thanks!

**Comment by krispenner** [comment]
I am also having the same problem. Basically this document shows what needs to be done via REST calls to create a version set and add a new API to it. It seems PS now supports the first call (New-AzureRmApiManagementApiVersionSet) but not the second where you can specify the version and version set to use in the new API. I imagine New-AzureRmApiManagementApi is missing parameters such as -VersionSetId and -Version to mimic the underlying rest call shown in the below link.

https://ronaldwildenberg.com/azure/2018/03/08/scripting-azure-apim-version-set.html

**Comment by krispenner** [comment]
The Azure SDK does support these two properties however the AzureRM module does not wrap them.

VersionSetId
https://github.com/Azure/azure-sdk-for-net/blob/0afa2cfdf8657958067e29be791772a7c1676e02/src/SDKs/ApiManagement/Management.ApiManagement/Generated/Models/ApiCreateOrUpdateParameter.cs#L179

ApiVersion
https://github.com/Azure/azure-sdk-for-net/blob/0afa2cfdf8657958067e29be791772a7c1676e02/src/SDKs/ApiManagement/Management.ApiManagement/Generated/Models/ApiCreateOrUpdateParameter.cs#L149

Primarily parameters need to be added here that map to the above two noted properties:
https://github.com/Azure/azure-powershell/blob/899f2290616bbd67fbd79d5f1abd4ba1d4351bb4/src/ResourceManager/ApiManagement/Commands.ApiManagement.ServiceManagement/ApiManagementClient.cs#L574

**Comment by valiorik** [comment]
Looks like ApiVersion was added, but VersionSetId is still missing. Setting ApiVersion without VersionSetId results in error "Can't set VersionName when ApiVersionSetId is not set.". Any plans to fix it?

**Comment by solankisamir** [comment]
[package](https://www.powershellgallery.com/packages/Az/2.1.0)
[documentation](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/?view=azps-2.1.0#api_management)
[releasenotes](https://github.com/Azure/azure-powershell/releases/tag/v2.1.0-May2019)
