### ISSUE TITLE
Save-AzureRmVMImage.md needs more detailed description of "-Path" parameter

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-powershell#6385]
Via @wellsluo , https://github.com/Azure/azure-docs-powershell/issues/603

----
In the doc of Save-AzureRMVMImage has following description of "-Path" parameter, which is very confusing:
[Save-AzureRmVMImage.md](https://github.com/Azure/azure-docs-powershell/blob/master/azurermps-6.2.0/AzureRM.Compute/Save-AzureRmVMImage.md)
```
-Path
Specifies the path of the VHD.
```
Question is: what is the "path" of VHD? local path to save VHD copy locally?

But in the source code file, it has following help message:
[SaveAzureVMImageCommand.cs](https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Action/SaveAzureVMImageCommand.cs)
```
        [Parameter(
           Position = 5,
           ValueFromPipelineByPropertyName = true,
           HelpMessage = "**The file path in which the template of the captured image is stored**")]
        [ValidateNotNullOrEmpty]
        public string Path { get; set; }
```
The message in source code is totally different from the description message in the doc.  Please make sure how on earth the "-Path" parameter is used.

**Comment by markcowl** [comment]
@sptramer We accept pull requests :-)

**Comment by sptramer** [comment]
@wellsluo - The engineering team has requested that you submit your fix as a pull request.

@markcowl Please do not close this issue until it is actually fixed.

**Comment by wellsluo** [comment]
@sptramer,  I really don't know what is the detail info of "-Path" parameter. That's why I submitted this request.   I don't have any fix on hand. Maybe the dev engineer should be consulted.

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
