### ISSUE TITLE
ARM 0.9.5 :: Missing Test-AzureName command (P3)

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#639]
# Symptom

The ARM PowerShell module is missing the `Test-AzureName` command.
# Expected Results

The ARM PowerShell module should contain the `Test-AzureName` command.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by devigned** [comment]
@chadiel any thoughts on this one? Looks like a similar issue to #622 and #491.

**Comment by alexandair** [comment]
I've filed the same issue in [#489](https://github.com/Azure/azure-powershell/issues/489) and it was closed 28 days ago without being resolved. We need to wait for Switch-AzureMode to go to history. :)

**Comment by pcgeek86** [comment]
@devigned @markcowl @ravbhatnagar Do we have a solution for this, please? If I missed a communication since July 2015 on this topic, I apologize. I'm not aware of a current solution for this issue though. Thanks for your support.

Cheers,
Trevor Sullivan

**Comment by devigned** [comment]
I defer this to @ravbhatnagar.

**Comment by wesselkranenborg** [comment]
Is there any information about this available? I'm also looking for this kind of functionality.

**Comment by ravbhatnagar** [comment]
@pcgeek86  - Agreed, this would be helpful to have. 

An API which is implemented by all resource providers would be ideal to provide this functionality. 
@vivsriaus - lets investigate this for next release.

**Comment by EASTMANDEM** [comment]
Are there any workarounds? I'm trying to write all my scripts in ARM and I just want to test for the existence of a site before I create it. Is Azure still in beta or what?

**Comment by colemickens** [comment]
Is there any update on this issue?

**Comment by ravbhatnagar** [comment]
No new update, we are still considering a few design options. Please note that we are trying to make it work consistently across the numerous resource providers in Azure. While we get there, you can handle this in user scripts. Albeit hacky but you can do something like below-

$resource = Find-AzureRmResource -ResourceNameContains ravtestws101 -ResourceType Microsoft.Web/sites
if($resource -eq $null)
{
# create the resource with the name
}
else{
#fail
} 

Or something which @colemickens  is doing - Get-s with ErrorAction = SilentlyContinue and then checked if the object I got back was null. If it's null, I make the call to create

**Comment by ravbhatnagar** [comment]
Update: Working on the design for this. We should have this functionality in the clients soon.

**Comment by slapointe** [comment]
Any news on this? we are almost a year later and still no update.

**Comment by jawandsingh** [comment]
still waiting for this functionality, any update ?

**Comment by jawandsingh** [comment]
@ravbhatnagar the powershell script snippet you have shared, i do not think it checks globally for existing web app. Is there some other way to check globally if web app name exists ?

**Comment by markcowl** [comment]
There are not any planned new cmdlets for RDFE, so closing this as won't fix.
