### ISSUE TITLE
Fix flaky Resource test

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#6393]
Currently there is one Resources test marked as flaky.  In order to remove the need to run on-demand CI for every build, we need to fix this test:

Microsoft.Azure.Commands.Resources.Test.ScenarioTests.RoleAssignmentTests.RaPropertiesValidation

Parent issue: https://github.com/Azure/azure-powershell/issues/3029

**Comment by cormacpayne** [comment]
This has been fixed.
