### ISSUE TITLE
Migrate SM modules to azure-powershell-servicemanagement

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#6396]
Design based on: https://github.com/Azure/azure-powershell/issues/5354#issuecomment-394893920

- This should be done post-Common (azure-powershell-common) separation
- Minimize the amount of restructuring required
- Make sure CI process works with current (Jenkins) build tooling for the new repo

**Comment by maddieclayton** [comment]
Work that needs to be done:

- [x] Merge Azure.Storage into Azure
- [x] Remove all of the ResourceManager cmdlets
- [x] Remove references to ResourceManager from all tooling and build.proj
- [ ] Ensure everything builds correctly on CI and signing
- [ ] Create azure-powershell-servicemanagement repo and make it public (once everything is working)
- [ ] Hook up CI into new repo
- [ ] Ensure documentation makes sense in new repo (remove everything related to AzureRM and add information about AzureSM)
