### ISSUE TITLE
Clear-AzureRmContext -Scope CurrentUser corrupts the state of the token cache for the current process

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6398]
Clear-AzureRMContext both clears the context and 'deletes' the cache file.  This causes other processes to be unable to use the disk token cache.

Most cmdlets simply default to using the in memory token cache, however, cmdlets that manipulate the context (Set-AzureRmContext, Select-AzureRmSubscription) will recreate the token cache file, with **no contents**.  Once this occurs, the user would need to log in again.

To fix this, ProtectedFileTokenCache.Clear() should simply clear the token cache, and allow the existing notification mechanism to update the contents on disk.

**Comment by cormacpayne** [comment]
This has been fixed and will be available in the 6.7.0 release of AzureRM
