### ISSUE TITLE
Missing documentation for managing virtual network gateways

### ISSUE THREAD

**Issue by hruan** [Azure/azure-powershell#640]
There seems to be commands for managing virtual network gateways, VNet gateways, and local network gateways. Only the VNet gateway commands are documented.

How are virtual network gateways different from VNet gateways? And what is a local network gateway?

**Comment by pcgeek86** [comment]
Agreed, I just looked at the docs for ARM Virtual Network Gateways, and documentation is virtually non-existent. Here are a few questions that should be answered by the documentation:

* When should I use the `-EnableBGP` parameter or not?
* Which values can I specify for the `-GatewayType` parameter? Do I need to specify it?
* How do I associate the Virtual Network Gateway with a Virtual Network? 
* What is an `IPConfiguration` object, and how to do I create one?
* What is the difference between the policy-based and route-based VPN Gateway? When should I use each of them?

The documentation, in its current state, is embarrassingly empty, and uses circular definitions. This is not enterprise/production-ready, and I cannot recommend using ARM to my customers.

![image](https://cloud.githubusercontent.com/assets/466713/8831971/23b67086-3063-11e5-9821-52369dd35235.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
