### ISSUE TITLE
Get-AzureRmPolicyAssignment  cmdlet failing with SPN over management group

### ISSUE THREAD

**Issue by Ajay-MS** [Azure/azure-powershell#6402]
### Script/Steps for Reproduction

1. Create an SPN with permission from the management group  ( instead of subscription )
2. Invoke PS cmdlet `Add-AzureRmAccount` with above created SPN.
3. Run cmdlet to fetch policy over management group `Get-AzureRmPolicyAssignment` 
4. Policy cmdlet is failing with following error 
`Get-AzureRmPolicyAssignment : Object reference not set to an instance of an object` 

Is management group not supported in policy cmdlets?

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```
     AzureRM module version = 6.1.0

### Environment Data

```powershell
$PSVersionTable
```
     PS version = 5.1.16299.431

**Comment by markcowl** [comment]
@cormacpayne @vivsriaus  Can we put together a plan on first class support for management grous as a scope for policy and role assignments?

Also, we should clean up this error in the interim.

**Comment by cormacpayne** [comment]
CC: @Tiano2017

**Comment by MiYanni** [comment]
@cormacpayne Please determine is there is a null ref issue.

**Comment by markcowl** [comment]
@cormacpayne @Tiano2017 The login here is a red herring - authorization is handled at the service level.

@Ajay-MS Can you clarify if you have logged in and have a subscription set?  Also, what parameters are yo passing to Get_AzureRmPolicyAssignment.  If no scope is specified, the default for these cmdlets is current subscription

**Comment by cormacpayne** [comment]
Closing due to lack of response. Please feel free to re-open this issue if you are still seeing this issue.
