### ISSUE TITLE
Set-AzureRmKeyVaultAccessPolicy parameter PermissionsToKeys does not accept All

### ISSUE THREAD

**Issue by whihathac** [Azure/azure-powershell#6406]
### Description

Did we change the behavior? My scripts I created few weeks back no longer work and give me this error - 
ParameterArgumentValidationError,Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAcces
   sPolicy
Set-AzureRmKeyVaultAccessPolicy : Cannot validate argument on parameter 'PermissionsToKeys'. The argument "All" does
not belong to the set
"decrypt,encrypt,unwrapKey,wrapKey,verify,sign,get,list,update,create,import,delete,backup,restore,recover,purge"
specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.

### Script/Steps for Reproduction

```$oid = ((Get-AzureRmADGroup -SearchString "xxxx").Id)[0].Guid

```Set-AzureRmKeyVaultAccessPolicy -VaultName $keyVaultName -ObjectId $oid -PermissionsToKeys All -PermissionsToSecrets All -PermissionsToCertificates All


### Module Version

<!-- Please run (Get-Module -Name AzureRM -ListAvailable) to get the version(s) of AzureRM installed on your machine -->

```powershell
Get-Module -Name AzureRM -ListAvailable
```

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.4.1      AzureRM

### Environment Data

```powershell
$PSVersionTable
```PS D:\git\media_intelligence_mp\servicefabric\Scripts\OneTimeScripts> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.81
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.81
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by whihathac** [comment]
Looked at the Microsoft.Azure.Commands.KeyVault.dll, and looks like this parameter option was supported in module version 4.1.1 but I don't see this in version 5.0.0

**Comment by maddieclayton** [comment]
@whihathac Yes, in the KeyVault breaking change release in May, we removed the "all" permission for Keys, Secrets, Certificates, and Storage (as seen in the migration guide [here](https://github.com/Azure/azure-powershell/blob/preview/documentation/migration-guides/migration-guide.6.0.0.md)).  You can keep your exact functionality by expanding the list from "all" to the list of all permissions for the resource type.
