### ISSUE TITLE
New-AzureRmTag does not URL escape special characters in values, resulting in BadRequest.

### ISSUE THREAD

**Issue by sjwaight** [Azure/azure-powershell#6415]
### Description

When attempting to create a Tag with a value that contains an ampersand you receive a 'BadRequest' response and the value is not created. The same value can be set via the Portal, however.

It appears the string is being passed directly to the underlying API call and as it is inlined in a URL it causes a problem on the ARM API, resulting in a 500 Internal Server Error (YSOD) from the ARM API (visible using '-Debug').

URL invoked is:

PUT https://management.azure.com/subscriptions/SUB-ID/tagNames/Department
/tagValues/Infra & Support?api-version=2016-09-01

Have attempted various escape sequences to no avail.

### Script/Steps for Reproduction

```powershell
New-AzureRmTag -Name "Department" -Value "Infra & Support"
```

### Module Version

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.2.1      AzureRM
Script     5.7.0      AzureRM
```

### Environment Data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.17134.48
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.48
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```
New-AzureRmTag : Operation returned an invalid status code 'BadRequest'
At line:1 char:1
+ New-AzureRmTag -Name "Department" -Value "Infra & Support"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmTag], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Tags.Tag.NewAzureTagCommand
```

**Comment by praries880** [comment]
@Tiano2017 can you take a look?

**Comment by markcowl** [comment]
@cormacpayne Can we fix this quickly?

**Comment by cormacpayne** [comment]
@Tiano2017 it looks like the ARM SDK doesn't know how to handle the `&` character when it's in the request. I believe it's getting encoded correctly into the request URI, but then the server doesn't know how to handle it and returns "BadRequest".
