### ISSUE TITLE
Should Azure.Commands.*.Models classes be documented?

### ISSUE THREAD

**Issue by jmlane** [Azure/azure-powershell#6417]
Hello!

I've noticed in the documentation that there are no links to the datatypes of any of the Model classes used to pass data or configuration to the Azure endpoints. After a quick inspection of the repository and that of the azure-powershell module, it seems like there is no documentation for these specific Powershell classes.

I think having model class reference documentation that is linked from the command documentation would be a valuable addition to the documentation. I know you can view the [SDK model classes][1] or the [REST API schema][2] in other documentation but that is an extra complication for users of the Powershell module to mentally map those structures to the Powershell equivalent.

Is this a change that would be welcome? Is there tooling available to the community to the generate the desired page templates from the Powershell module source files?

(Originally suggested at https://github.com/Azure/azure-docs-powershell/issues/491)

[1]: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.protocol.models?view=azure-dotnet
[2]: https://docs.microsoft.com/en-us/rest/api/batchservice/

**Comment by markcowl** [comment]
@jmlane They absolutely should be.  We are currently working with our docs team on making this happen.

The issue tracking this is here: https://github.com/Azure/azure-powershell/issues/5777 

You can track progress on this issue there, closing this one as a duplicate.
