### ISSUE TITLE
Can't specify server name in New-AzureSqlDatabaseServer

### ISSUE THREAD

**Issue by manicmonkey** [Azure/azure-powershell#642]
The new Azure Preview Portal provides the ability to specify the database server name - can this be added to the Powershell cmdlet?

**Comment by pcgeek86** [comment]
@manicmonkey Already exists in the Azure Resource Manager (ARM) module, which correlates to the Azure "Ibiza" Preview Portal.

![image](https://cloud.githubusercontent.com/assets/466713/8856385/c1dac72a-3127-11e5-8f8f-0fba8a66e817.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by manicmonkey** [comment]
Ah fantastic thank you!
