### ISSUE TITLE
Refactor/Rename the cmdlet "New-AzureRmVmssIpConfig"

### ISSUE THREAD

**Issue by praries880** [Azure/azure-powershell#6423]
As per the discussion in this cmdlet [design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/90), The cmdlet _New-AzureRmVmssIpConfig_ is doing more than just create a new resource. It cn be used ot update the IP config of an existing vmss. The cmdlet should be either broken into two cmdlets (New- and Set-) or just renamed to _Set-AzureRmVmssIpConfig_. 

The cmdlet is autogenerated, hence the fix will be a little more involved as per @chandrasekarsrinivasan.

Assigning this tags for both compute and newtorking since this is a networking cmdlet in compute vmss and the work involved

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
