### ISSUE TITLE
cannot change endpoint to add LBSET if endpoint is already created

### ISSUE THREAD

**Issue by joaoma** [Azure/azure-powershell#644]
Scenario: I have an endpoint created using powershell for service management public port 80 to local port 8081. I need to change that endpoint to add a load balancer set but fails using set-azureendpoint or add-azureendpoint. In order to add an lbset to an existing endpoint I will have to delete the endpoint and readd with add-azureendpoint with -lbset switch. That operation will cause downtime in the current state having to delete an endpoint to re-create it with a lb set on powershell.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
