### ISSUE TITLE
What is the desired behaviour of IsValidPath(string path) in EnableAzureRMContextAutoSave.cs / Enable-AzureRMContextAutoSave?

### ISSUE THREAD

**Issue by rasmusgude** [Azure/azure-powershell#6456]
Hi,

In PR #6421 I made two corrections in the exception messages in `EnableAzureRMContextAutoSave.cs`.

But it looks like the affected exceptions will only rarely (if ever?) be reached as the code looks now.
This is because `IsValidPath(string path)` only checks that the path is valid (e.g., doesn't contain illegal chars like * or ?). It doesn't check if the path exists.

**Should `IsValidPath(string path)` also check for path existence?**

When `ProtectedProfileProvider.InitializeResourceManagerProfile(true);` is called in line 38 or 49 the paths will (in turn) be validated for existance (and hence also validated for illegal chars etc.).

**Comment by praries880** [comment]
@vladimir-shcherbakov  @maddieclayton  can you guys look into this?

**Comment by vladimir-shcherbakov** [comment]
@rasmusgude 
```FileUtilities.EnsureDirectoryExists``` method [gets called](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Profile/Commands.Profile/AutoSave/EnableAzureRmContextAutosave.cs#L89) in the constructor to create the directory if it doesn't exist. So, ```IsValidPath(string path)``` shouldn't check for path existence.
