### ISSUE TITLE
Get-AzureRmRecoveryServicesVault doesn't exist in AzureRM.NetCore manifest module

### ISSUE THREAD

**Issue by mosharafMS** [Azure/azure-powershell#6464]
### Description

Using Get-AzureRMRecoveryServicesVault results in error on PowerShell core module 
 Get-Command Get-AzureRmRecoveryServicesVault
Get-Command : The term 'Get-AzureRmRecoveryServicesVault' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-Command Get-AzureRmRecoveryServicesVault
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-AzureRmRecoveryServicesVault:String) [Get-Command], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

### Script/Steps for Reproduction

```powershell

```

### Module Version

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.11.0     AzureRM.Netcore

### Environment Data

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by cormacpayne** [comment]
@mosharafMS currently the RecoveryServices modules aren't a part of the `AzureRM.Netcore` due to the issue outlined [here](https://github.com/Azure/azure-powershell/issues/5756). I'm going to close this issue in favor of the issue previously linked (since it has all of the details about the work needed to port the modules to .NET Core)
