### ISSUE TITLE
Long running test: RaClassicAdmins

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#6468]
The RaClassicAdmins test in Resources.Test.RoleAssignementTests takes ~30 seconds to run.

Root cause: https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.Resources/Models.Authorization/AuthorizationClient.cs#L128

**Comment by cormacpayne** [comment]
This is resolved after the performance improvements to `Get-AzureRmRoleAssignment`
