### ISSUE TITLE
Connect-AzureRmAccount: Description for the Environment parameter

### ISSUE THREAD

**Issue by alexfreu** [Azure/azure-powershell#6470]
Could you please include a description about the possible values for the Environment parameter?

I found out these:

AzureCloud
AzureGermanCloud
AzureChinaCloud

Why did you choose AzureGermanCloud instead of AzureGerman**y**Cloud like in Connect-MsolService?

**Comment by markcowl** [comment]
@alexfreu This was the official name of the cloud at that time.
