### ISSUE TITLE
Need to create documentation around the usage of the simple param set in New-AzureRmVmss

### ISSUE THREAD

**Issue by praries880** [Azure/azure-powershell#6474]
We need to come up with good user scenarios and create examples and guidance around using the cmdlet and the simple param set.

This issue came out of a [customer reported issue](https://github.com/Azure/azure-powershell/issues/6413) when creating a VMSS.

**Comment by twitchax** [comment]
Is this for reference docs or conceptual docs?  If this is for reference documentation, then we typically have the cmdlet authors write the documentation.

**Comment by vladimir-shcherbakov** [comment]
@twitchax Ping

**Comment by twitchax** [comment]
Notified the PG, and they will make a recommendation on cmdlet or conceptual doc improvements.

In the meantime, we should split this out into two subtasks:
* Improve the reference doc with better descriptions and examples that indicate that this scenario is not supported.
* Improve the error message in this case in the product.

Assigning back to @praries880 for follow up on this two tasks pending response from PG.

**Comment by maddieclayton** [comment]
@praries880 Please split this into two issues.

**Comment by cormacpayne** [comment]
Issue for updating reference doc: https://github.com/Azure/azure-powershell/issues/6989
