### ISSUE TITLE
empty status in return of Remove-AzureRmVM and Remove-AzureRmDisk

### ISSUE THREAD

**Issue by manuel-74** [Azure/azure-powershell#6483]
### Description

The following PowerShell script shows how the Azure Cmdlet Remove-AzureRmVM returns only empty values i.e. for status. The same issue occurs when running Remove-AzureRmDisk. Script has to be executed as a Runbook in Azure so local testing is not enough. Occured also on my local PowerShell but after I uninstalled the module and reinstalled it afterwards the issue was somehow fixed. This and also downgrading step by step to the last script compatible version 4.5.0 didn't work on Azure automation to fix the Runbook issue. Unfortunately the required script is run in the Azure console as a Runbook only so it doesn't help when the issue is fixed in locally installed Azure PowerShell. Issue has already been verified by Microsoft Azure Support Team which sent me to GitHub to report the issue.

### Script/Steps for Reproduction

$ResGrp = 'Test123'

$VM = Get-AzureRmVM -ResourceGroupName $ResGrp -Name 'VirtualMachine123'

$RemoveVMRtn = Remove-AzureRmVM -Name $VM.Name -ResourceGroupName $ResGrp -Force

Write-Output 'Return of Remove-AzureRmVM:'
Write-Output $RemoveVMRtn

### Module Version

AzureRM.Compute 5.1.0

### Environment Data

Azure automation service with all modules upgraded to the latest version and Azure console with a normal PowerShell Runbook (not a PowerShell workflow Runbook).

**Comment by vladimir-shcherbakov** [comment]
closing as fixes in 5.1.1

**Comment by manuel-74** [comment]
Wow, 8 hours! That I call agile... ;-) Thank you!
