### ISSUE TITLE
Fix PowerShell experience for creating a large VMSS (> 100 vms) with the new-azurermvmss simple params set

### ISSUE THREAD

**Issue by praries880** [Azure/azure-powershell#6498]
#### Original issue 

This is in reference to our conversation earlier today regarding the PowerShell experience for large VMSS. I am writing it down so that you can forward it to the appropriate teams/people.
 
The PowerShell experience for creating a large VMSS seems frankly a bit broken compared to how easy it is for a small VMSS. Let me illustrate this with some commands.
 
First, let’s take an example when I want to create a small VMSS with the New-AzureRmVmss command using the simple flags instead of giving a config object. I would simply use this command:

```powershell 
New-AzureRmVmss -ResourceGroupName “myRg” -VMScaleSetName “myVmss” -Location “WestUS” -InstanceCount 10
```
 
The command executes successfully, and all is well. However, if I want to create a large VMSS (more than 100 instances), I would need to set the `SinglePlacementGroup` flag to be false as the default is true. But now, I can’t use the simple command listed above as there is no flag for this seemingly important parameter. I would have to first create a VMSS config object, set all its various parameters and then call:

```powershell 
New-AzureRmVmss -ResourceGroupName “myRg” -VMScaleSetName “myVmss” -VirtualMachineScaleSet $vmss
 ```

`$vmss` is the config object in this case. It takes much more effort to create a config object as most of the parameters that were set by PowerShell using some smart defaults need to be now set manually. Ideally, I would be able to do something like this:
 
```powershell
New-AzureRmVmss -ResourceGroupName “myRg” -VMScaleSetName “myVmss” -Location “WestUS” -InstanceCount 1000 -SinglePlacementGroup $false
 ```
The latter would be a much better experience for our customers as now it feels we are just punishing them for wanting to create a large VMSS from the get-go. It would be great if this feedback was taken into consideration. I would be also happy to be proven wrong if there’s an easier way. However, if such a way existed, I couldn’t find it in our publicly available documentation.

#### Proposed solution

We can add the flag as per the suggestion… but I would like to change the behavior here…
Given that (according to the [documentation here](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-placement-groups#placement-groups)) with a  single placement group a vmss can contain only 0 to 100 vms, I would suggest that the simple param set automatically switches the flag to false in case the instance count is > 100 without the user having to specify it.

We can still support a switch param called `UseMultiplePlacementGroups`, which if present sets `SinglePlacementGroup` to false, otherwise `SinglePlacementGroup` is true for instance counts of up to 100.

**Comment by praries880** [comment]
Agreed upon changes :
* Add an optional switch param called `SinglePlacementGroup`, ehich when present creates the vmss with the _single placement group_ option. When its not specified (the default behavior), the vmss will be created with the _multiple placement group_ option.
* Multiple placement groups are not compatible with _SLB v1_ (basic SKU for LB), which according to [this code](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Compute/Commands.Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs#L183) gets selected when no _zones_ are specified.  We will change this behavior to select the _standard SKU_ (SLB v2) if `SinglePlacementGroup` is false.

**Comment by cormacpayne** [comment]
This has been fixed.
