### ISSUE TITLE
ResourceId completer experiments

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#6513]
Create an experimental module to test different versions of the ResourceId completer.
Experiments:
1) Shortened ResourceId string (ex: maddie1/maddiesvm, where maddie1 is a resourcegroup and maddiesvm is a VM).  Tab completion ordered alphabetical order.
2) Shortened ResourceId string (ex: maddie1/maddiesvm, where maddie1 is a resourcegroup and maddiesvm is a VM).  Tab completion ordered by name, then parent name, then resource group.
3) Formatted Id: User can tab through until they reach the next variable part the the resourceId string.  Ex: on first tab, gets ```/subscription/<subscriptionId>/resourcegroup/``` once they complete the resourcegroupname and tab, they get ```/subscription/<subscriptionId>/resourcegroup/<resourcegroupname>/provider/Microsoft.Compute/virtualmachines/```, then they write the virtual machine name.

Each of these experimental types will be applied to one top level resource and one second level resource.

**Comment by markcowl** [comment]
Completed

**Comment by maddieclayton** [comment]
Only one piece of this was finished - still need to do the shortened resourceId experiments.

Reopening.

**Comment by markcowl** [comment]
@maddieclayton Please add checkboxes for additional work

**Comment by maddieclayton** [comment]
Closing - we might revisit in the future after generated cmdlets are in place.
