### ISSUE TITLE
[Insights] Set-AzureRmDiagnosticSettings does not support metric categories, only log categories

### ISSUE THREAD

**Issue by gucalder** [Azure/azure-powershell#6520]
### Description

Set-AzureRmDiagnosticSettings does not support metric categories, which are supported by the backend.

### Script/Steps for Reproduction

This what one of our partners reported while trying to use the cmdlet. The storage RP has defined two categories for the storage account metrics. So the following cmdlet throws an exception.

```powershell
Set-AzureRmDiagnosticSetting -ResourceId "/subscriptions/5513e695-7e90-4bb8-b5a0-3fdb3e02122b/resourceGroups/AIGraph/providers/Microsoft.Storage/storageAccounts/mytestaccount123/blobServices/default" -Enabled $True -Categories Read

Set-AzureRmDiagnosticSetting : Exception type: CloudException, Message: Metric category 'AllMetrics' is not supported., Code: BadRequest, Status code:BadRequest, Reason phrase: Bad Request
At line:1 char:1
+ Set-AzureRmDiagnosticSetting -ResourceId "/subscriptions/5513e695-7e9 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmDiagnosticSetting], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand

```

### Module Version

Not provided, but it might be any version from to the latest published.

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by asheniam** [comment]
Please give this a try using Set-AzureRmDiagnosticSetting on the latest PowerShell.
https://docs.microsoft.com/en-us/powershell/module/azurerm.insights/set-azurermdiagnosticsetting?view=azurermps-6.13.0
