### ISSUE TITLE
Issue with Set-AzureRmResource in AzureRM version 6.0.0 and above (tested till 6.1.1)

### ISSUE THREAD

**Issue by kduraira** [Azure/azure-powershell#6542]
### Description

Fails to enable / disable App Insights WebTests resource in AzureRM version 6.0.0 and above (till 6.1.1).

### Script/Steps for Reproduction
```powershell
if (Get-AzureRmResource -ResourceType "microsoft.insights/webtests" -ResourceGroupName $RG -ResourceName $RN)
{
    $info = Get-AzureRmResource -ResourceType "microsoft.insights/webtests" -ResourceGroupName $RG -ResourceName $RN
    $properties = $info.Properties
    if ($properties.Enabled = "True")
    {
        Write-Output "Disabling email alert for $RN..."
    	$properties.Enabled = "False"
        Set-AzureRmResource -ResourceGroupName $RG -ResourceName $RN -ResourceType "microsoft.insights/webtests" -PropertyObject $properties -Force
        Write-Output "Email alert has been disabled..."
    }
}
```
It used to work in version 5.5.2 but fails in 6.0 with the below error:
```Powershell
Set-AzureRmResource : Exception getting "Values": "The method or operation is not implemented."
At line:1 char:1
+ Set-AzureRmResource -ResourceGroupName $RG -ResourceName $RN -Resourc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmResource], GetValueInvocationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet
```
### Module Version
6.1.1

### Environment Data

Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Regards,
Karthik

**Comment by maddieclayton** [comment]
@kduraira Can you provide us the output of running your script where you add this line to the beginning of the script?
```
$DebugPreference = "Continue"
```

**Comment by maddieclayton** [comment]
Closing as no response.  @kduraira Feel free to reopen if you're still having this issue (and please provide the information requested above).

**Comment by hallgeirl** [comment]
Hi,
Just experienced the exact same issue. I did found a workaround, that I'd like to share with anyone that's still struggling. My scenario is updating webtests using the same powershell version as is used with Azure Stack (we deploy resources in Azure Stack, but use availability tests in Azure).

(Using a simplified version of the OP's example)
```powershell
$resource = (Get-AzureRmResource -ResourceType "microsoft.insights/webtests" -ResourceGroupName $RG -ResourceName $RN)
$properties = $info.Properties
$properties.Enabled = 'True'

# The version in question of AzureRM gives the properties as JObject -- older versions use PSCustomObject, Unsure of the situation for the latest AzureRM.

if ($properties.GetType().Name -eq "JObject")
{
    # Simply convert the JObject to a PSCustomObject - this solves the problem
    # DO NOT serialize a JObject to json with ConvertTo-Json - that includes all the JObject's properties as well as the Azure resource's properties
    $properties = ConvertFrom-Json $properties.ToString()
}

Set-AzureRmResource -ResourceGroupName $RG -ResourceName $RN -ResourceType "microsoft.insights/webtests" -PropertyObject $properties -Force
```

I hope this can be of help to someone.
