### ISSUE TITLE
[netcore] Upgrade XSCL in Azure.Storage, need to upgrade it for all projects, or test will fail

### ISSUE THREAD

**Issue by blueww** [Azure/azure-powershell#6543]
In netcore, when upgrade XSCL for Azure.Storage. we need to upgrade it for all project, or test will fail.
We should remove the limitation.

In .net, we can only upgrade XSCL for Azure.Storage, and build/test still pass.

**Comment by markcowl** [comment]
This is a duplicate of #3430 closing
