### ISSUE TITLE
[netcore] the resource file in project Commands.Management.Storage.csproj not work for netcore

### ISSUE THREAD

**Issue by blueww** [Azure/azure-powershell#6545]
### Description
When fixing the netcore build failureof PR https://github.com/Azure/azure-powershell/pull/6459 , we found the resource file in project Commands.Management.Storage.csproj not work well, so run test will fail with:

```
Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests.TestAzureStorageAccountManagementPolicy [FAIL]
Failed Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests.TestAzureStorageAccountManagementPolicy
Error Message:
System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find any resources appropriate for the specified culture or the neutral culture. Make sure "Microsoft.Azure.Commands.Management.Storage.Resources.resources" was correctly embedded or linked into assembly "Microsoft.Azure.Commands.Management.Storage" at compile time, or that all the satellite assemblies required are loadable and fully signed.
```
Cormac tried to fix it but the build still fail(https://github.com/Azure/azure-powershell/pull/6459/commits/407a2ec10289c428c91de5ae82fe92df0f83e1e9), so he hard code the string in code temperately and build pass(https://github.com/Azure/azure-powershell/pull/6459/commits/8203f0736e577459a5e1e9ef53edb4e98ace31b0).

But we still need to fix the resource file for netcore.

**Comment by maddieclayton** [comment]
Tried to solve this quickly here: https://github.com/Azure/azure-powershell/pull/6747/files, but could not figure out why the error was still being thrown.

**Comment by MiYanni** [comment]
Closing as this will be part of the work to move Azure.Storage.Location to NetStandard post Ignite.
