### ISSUE TITLE
Set-AzureRmVMBootDiagnostics setting not sticking

### ISSUE THREAD

**Issue by AzureAlexN** [Azure/azure-powershell#6546]
### Description

I'm trying to configure boot diagnostics for multiple VM's through the powershell cmdlet Set-AzureRmVMBootDiagnostics. Whenever I run the cmdlet (as per the instructions on https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/set-azurermvmbootdiagnostics?view=azurermps-6.3.0 ) the initial returned VM attribute "Diagnostics Profile" is returned as {BootDiagnostics}. This seemed promising, but when I retrieved the VM-configuration (get-azureRmVM) a second time the attribute/setting is returned blank. Also in the Portal Boot Diagnostics remained unconfigured.

### Script/Steps for Reproduction

$vms = Get-AzureRmVm
$SA="<StorageAccountName>"
$RGSA="<StorageAccountRG>"

foreach ($vm in $vms){
    Set-AzureRmVMBootDiagnostics -VM $vm -ResourceGroupName $RGSA -Enable -StorageAccountName $sa
}

also for a single VM:

$VM = Get-azurermvm -name "<vmname>" -resourcegroupname "<rgname>"
### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.3.0      AzureRM
Script     6.2.1      AzureRM
Script     5.7.0      AzureRM
Script     5.3.0      AzureRM

current running version is 6.3.0
### Environment Data

```powershell
$PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Debug Output

Please note, the VMs ending in man01 and web01 were manually configured through the portal (this does work)
```
removed DEBUG output as it contains a lot of information which I (and others) would not like to openly publish on the internet.
```

**Comment by alexcastrus** [comment]
PS. this issue is present in multiple tenants

**Comment by vladimir-shcherbakov** [comment]
@nibhat Could you please take a look?

**Comment by artisticcheese** [comment]
You need to pipe to `Update-AzureRMVM` to work like below 

`Set-AzureRmVMBootDiagnostics -VM $vm -ResourceGroupName USEastShared -Enable -StorageAccountName useastbootdiag | update-azurermvm`
Documentation shall be updated
