### ISSUE TITLE
Inaccuracy on docs.microsoft.com Set-AzureRmVMBootDiagnostics

### ISSUE THREAD

**Issue by AzureAlexN** [Azure/azure-powershell#6547]
On the docs site for Set-AzureRmVMBootDiagnostics (https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/set-azurermvmbootdiagnostics?view=azurermps-6.3.0)
it states under required parameters the following:
-ResourceGroupName
Specifies the name of the resource group of the virtual machine.

This is not correct, the actual resourcegroup that needs to be specified is the resourcegroup in which the targeted storage account resides. This is corroborated by the following exception being thrown:
Exception - Microsoft.Rest.Azure.CloudException: The Resource 'Microsoft.Storage/storageAccounts/alexdneuwogdlogging'
 under resource group 'ALEXDN-MSDN-EUW-SQL' was not found.

**Comment by vladimir-shcherbakov** [comment]
@nibhat Could you please take a look?

**Comment by YoannGUILLO** [comment]
Furthermore the example 1 is incorrect. 
While the command Update-AzureRmVM don't have been executed the boot diagnostics settings will not applied.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
