### ISSUE TITLE
ARM: issues in the Set-AzureDSCExtension help topic

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#656]
These are examples from Set-AzureDSCExtension help topic. 

-------------------------- EXAMPLE 1 --------------------------
    C:\PS>Set-AzureVMDscExtension -ResourceGroupName name -VMName vm -ArchiveBlobName Sample.ps1.zip
    -ArchiveStorageAccountName stg -ConfigurationName MyConfiguration -Version 1.10 -Location 'West US'
## Description

Set the extension on the VM to download **MyConfiguration.ps1 (this is incorrect)** from the default container (windows-powershell-dsc)
                and invoke configuration MyConfiguration **with arguments to the configuration function (what does this mean? there are no arguments in this example)**. Connect to blob
    storage using the value of
                **$ENV:azure_storage_connection_string (I don't know what is this and how it relates to this example.)**

-------------------------- EXAMPLE 2 --------------------------
C:\PS>Set-AzureVMDscExtension -ResourceGroupName name -VMName vm -ArchiveBlobName Sample.ps1.zip
    -ArchiveStorageAccountName stg -ConfigurationName name -ConfigurationArgument @{arg="val"} -ArchiveContainerName
    WindowsPowerShellDSC -ConfigurationData SampleData.psd1 -Version 1.10 -Location 'West US'
## Description

With arguments to the configuration function **<-- Is that all?**

-------------------------- EXAMPLE 3 --------------------------
C:\PS>Set-AzureVMDscExtension -ResourceGroupName name -VMName vm -ArchiveBlobName Sample.ps1.zip
    -ArchiveStorageAccountName stg -ConfigurationName name -ConfigurationArgument @{arg="val"} -ArchiveContainerName
    WindowsPowerShellDSC -ConfigurationData SampleData.psd1 -Version 1.10 -Location 'West US' -AutoUpdate
## Description

Enable -AutoUpdate **<-- Is that all?**

**Comment by pcgeek86** [comment]
Standard terminology should be used with DSC, to reduce end user / customer confusion. DSC configurations are called "*configuration documents*," not configuration *functions*, although they share a similar structure.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
