### ISSUE TITLE
AzureRM.consumption module support for EA subscriptions

### ISSUE THREAD

**Issue by joyal-ks** [Azure/azure-powershell#6569]
Does the AzureRM.consumption module support EA subscriptions ?

I couldn't find any relevant documentation on this and I am aware that I can utilize the rest API directly.

Excuse me if this is not the right place for this question,I am new to the git style of doing things

**Comment by cormacpayne** [comment]
@ms-premp Hey Prem, would you mind answering the above question?

**Comment by ms-premp** [comment]
Yes, behind the scene, AzureRM.consumption module internally uses [REST APIs](https://docs.microsoft.com/en-us/rest/api/consumption/).
Hence, it supports same offer types as REST APIs.

**Comment by ms-premp** [comment]
Yes, behind the scene, AzureRM.consumption module internally uses [REST APIs](https://docs.microsoft.com/en-us/rest/api/consumption/).
Hence, it supports same offer types as REST APIs.

**Comment by joyal-ks** [comment]
@ms-premp I am getting not supported offer type while using this cmdlet for EA subscription (attached screenshot)

![da59b051-9b5a-4a2a-8625-02385c4cf8b4](https://user-images.githubusercontent.com/40496362/42201185-4571cab6-7eb4-11e8-8f07-cce211e604a3.jpg)
