### ISSUE TITLE
Creating webapp not possible in powershell, but possible in portal, due to bug in both places

### ISSUE THREAD

**Issue by mariusGundersen** [Azure/azure-powershell#6573]
### Description

The command `New-AzureRmWebApp` checks if the name provided is unique by calling `https://management.azure.com/subscriptions{subscriptionId}/providers/Microsoft.Web/checknameavailability?api-version=2016-03-01`, but doesn't take the domain of the AppServicePlan into consideration. I have an AppServicePlan with a custom domain, and I want to create an app with a subdomain for this domain. However, this fails even though the full domain is free. I can try the same thing in the Azure Portal, and here it works, and I even see the little green checkmark next to the name. 

You can see from the debug output below that the powershell script checks with the `checknameavailability` endpoint in `management.azure.com`. When I open the browser devtools in the Azure Portal and check what it sends as I enter the webapp name, I see that it calls the same endpoint, but with a different payload, which is why it's getting a different result. The Azure Portal sends the full name, along with the parameter `isFqdn: true` (it sends [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.resourcenameavailabilityrequest?view=azure-dotnet) model). But, it sends the wrong domain name, missing one `.` in the name, so it's check if the wrong fully qualified domain name is available, and might therefore get the wrong response back.

This is causing problems for us, since we want to create webapps automatically using the PowerShell script, but are forced to use the portal and do it manually. And it might cause problems, since the portal checks the wrong name, and might fail to create the webapp it said was free.

### Script/Steps for Reproduction

Make sure you have an AppServicePlan with an AppServiceEnvironment and a custom domain name, so that created WebApps will be subdomains.

```powershell
New-AzureRmWebApp -ResourceGroupName "RSG-Testing" -Location "West Europe" -AppServicePlan "ASP-Testing" -Name "Testing"
```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.3.0      AzureRM
```

### Environment Data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/my-subscription-id/providers/Microsoft.Web/checknameavailability?api-version=2016-03-01

Headers:
x-ms-client-request-id        : 8ce0eb68-65b4-4720-b26c-d6a4f756853c
accept-language               : en-US

Body:
{
  "name": "Testing",
  "type": "Site"
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : e7d4cd73-6636-4f19-adf2-e17b3f33231d
x-ms-ratelimit-remaining-subscription-reads: 14996
x-ms-correlation-request-id   : f11da7a4-5023-4c8a-8b9b-8f0385121f40
x-ms-routing-request-id       : WESTEUROPE:20180702T134343Z:f11da7a4-5023-4c8a-8b9b-8f0385121f40
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Mon, 02 Jul 2018 13:43:42 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "nameAvailable": false,
  "reason": "AlreadyExists",
  "message": "Hostname 'Testing' already exists. Please select a different name."
}

New-AzureRmWebApp : Website name 'Testing' is not available.  Please try a different name.
At line:1 char:1
+ New-AzureRmWebApp -ResourceGroupName "RSG-Testing" -Location "West Eu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmWebApp], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.NewAzureWebAppCmdlet
```

**Comment by mariusGundersen** [comment]
It seems this can be fixed by supplying `true` as the third argument to the `CheckNameAvailability` call [here](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Websites/Commands.Websites/Cmdlets/WebApps/NewAzureWebApp.cs#L156).

That's at least part of the solution

**Comment by cormacpayne** [comment]
@mariusGundersen Hey Marius, thanks for filing this issue 😀 

@panchagnula Hey Sisira, would you mind taking a look at this issue when you get the chance?

**Comment by panchagnula** [comment]
@mariusGundersen  thanks for the detailed error report I will take a look.

**Comment by mariusGundersen** [comment]
Any status update on this issue?

**Comment by slashP** [comment]
@panchagnula Do you have an update for us?

**Comment by slashP** [comment]
We are still waiting for an update to this issue @cormacpayne @panchagnula and yes, it is still very annoying 😄

**Comment by panchagnula** [comment]
don't have an update on this - we will update this with the milestone & other details when we are close to a fix for this. Thanks!

**Comment by panchagnula** [comment]
We will have this fixed for the upcoming release.

**Comment by btardif** [comment]
Need to make sure we understand this scenario. I will confirm with @mariusGundersen

**Comment by panchagnula** [comment]
@btardif can we follow up on this & close this. Thank you.
