### ISSUE TITLE
AzureRM scripts sometime becomes non-responsive on Windows Forms control events.

### ISSUE THREAD

**Issue by MaximoTrinidad** [Azure/azure-powershell#6575]
### Description

I've been noticing the behavior when executing a AzureRM script on a Windows forms application, sometimes the scripts becomes non-responsive.  It seems the script is hung, but it completes on the cloud side.

The main issue is, that it looses getting the results back to the Windows form. This is annoying, as it sometimes work but then it get's hung up.  The forms becomes unreliable to use.

So, Is there any recommendation on how to overcome this sporadic issue with Windows Form?
Or, Is the proper route is to submit the script as jobs to background process?

### Script/Steps for Reproduction

1. Create a Windows Form that will connect to Azure.
2. Add the Button control event to run the AzureRM script to create a VM.
3. Return control to the Windows Form and display results.

```powershell

```

### Module Version

```powershell
PS [3] > Get-Module -Name AzureRM -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.1.1      AzureRM

```

### Environment Data

```powershell
PS [14] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17704.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17704.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS [28] >
```

### Debug Output

```

```

**Comment by cormacpayne** [comment]
@MaximoTrinidad Hey Maximo, thanks for filing this issue.

> Or, Is the proper route is to submit the script as jobs to background process?

Have you tried running the `AzureRM` cmdlets with the `-AsJob` parameter? This will create a job for a given cmdlet that you can query with the typical PowerShell `*-Job` cmdlets.

**Comment by MaximoTrinidad** [comment]
Hi @cormacpayne,

Yes! I have use the both, submitting the script as a job, and use the cmdlet -AsJob parameter.  Either way seems to work fine.

I just wanted some clarification, or confirmation, it this is way to go when creating Windows forms app to leverage Azure tasks.

:)

**Comment by MaximoTrinidad** [comment]
@cormacpayne,

Mostly random!  But I used to create VM the advance way, which involves using a series of cmdlets for each VM component. 

Of course, if I execute the cmdlets at the console the it works fine.  I feel it works better doing the background jobs as I can do the Get-Job and get the status of Complete or failed.

The issue may relay when, for example, I click on the button to process my azure code. This button will include the login automation into Azure subscription, and the code to create a VM. This is where sometimes works or not.

It's a different behavior as everything is happening during the Button event control which at that time the Windows form is busy until it finished. 

:)

**Comment by maddieclayton** [comment]
Closing as resolved.
