### ISSUE TITLE
AppService:   New-AzureRmAppServicePlan  throws Microsoft.Rest.Azure.CloudException with Isolated SKU even the App service plan is created successfully.

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-powershell#6576]
ustomer is using Powershell with the Azure SDK version 6.3.0, and the exception occurs every time an app service plan is created with the new verb.  The app service plan does deploy and he can create new app services and web apps on it.  In Powershell when the exception occurs, there is no return value from the New-AzureRmAppServicePlan cmdlet.  The New-AzureRmAppServicePlan was only called once with the parameter Name set to Test.  The exception occurs during that time and the cmdlet always returns null.  Right after that, the Get-AzureRmAppServicePlan is called the non-null object is returned.  This has always been the case.  Seems strange the New-AzureRmAppServicePlan throws an exception on the same call it succeeds creating the app service plan as shown… very strange.
Report below exception after the app service plan created successfully.
Output:
 
                $AppServicePlans = New-AzureRmAppServicePlan `
                    -Name $Name `
                    -ResourceGroupName $ResourceGroupName `
                    -Location $ResourceGroupLocationName `
                    -AseName $AppServiceEnvironment.Name `
                    -AseResourceGroupName $AppServiceEnvironment.ResourceGroupName `
                    -Tier $Tier
 
 
 
[DBG]: PS Microsoft.PowerShell.Core\FileSystem  $Name='Test'
[DBG]: PS Microsoft.PowerShell.Core\FileSystem  $Name
Test
[DBG]: PS Microsoft.PowerShell.Core\FileSystem  $ResourceGroupName
Enterprise-Production-Web
[DBG]: PS Microsoft.PowerShell.Core\FileSystem  $ResourceGroupLocationName
East US 2
[DBG]: PS Microsoft.PowerShell.Core\FileSystem  $AppServiceEnvironment.Name
TechnologyEnabledServices
[DBG]: PS Microsoft.PowerShell.Core\FileSystem  $AppServiceEnvironment.ResourceGroupName
Enterprise-Production-Web
[DBG]: PS Microsoft.PowerShell.Core\FileSystem  $Tier
Isolated
 
[DBG]: PS Microsoft.PowerShell.Core\FileSystem
$AppServicePlans = New-AzureRmAppServicePlan -Name $Name -ResourceGroupName $ResourceGroupName -Location $ResourceGroupLocationName -AseName $AppServiceEnvironment.Name -AseResourceGroupName $AppServiceEnvironment.ResourceGroupName -Tier $Tier -Debug -Verbose
8:09:55 PM - NewAzureAppServicePlanCmdlet begin processing with ParameterSet 'S1'.
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
8:10:05 PM - using account id 'ec2d25b5-44d4-4d2a-81c7-7f9178378912'...
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
[Common.Authentication]: Authenticating using Account: 'ec2d25b5-44d4-4d2a-81c7-7f9178378912', environment: 'AzureCloud', tenant: 'd4f3b623-9555-4b47-9ddb-d3980c841eb2'
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
06/28/2018 03:10:08: 1cee5408-1053-49a3-ab2c-2846f8c3ea41 - AcquireTokenHandlerBase: === Token Acquisition started:
        Authority: https://login.microsoftonline.com/d4f3b623-9555-4b47-9ddb-d3980c841eb2/
        Resource: https://management.core.windows.net/
        ClientId: ec2d25b5-44d4-4d2a-81c7-7f9178378912
        CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (3 items)
        Authentication Target: Client
 
 
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
06/28/2018 03:10:08:  - TokenCache: Deserialized 3 items to token cache.
 
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
06/28/2018 03:10:08: 1cee5408-1053-49a3-ab2c-2846f8c3ea41 - TokenCache: Looking up cache for a token...
 
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
06/28/2018 03:10:08: 1cee5408-1053-49a3-ab2c-2846f8c3ea41 - TokenCache: An item matching the requested resource was found in the cache
 
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
06/28/2018 03:10:08: 1cee5408-1053-49a3-ab2c-2846f8c3ea41 - TokenCache: 37.04618839 minutes left until token in cache expires
 
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
06/28/2018 03:10:08: 1cee5408-1053-49a3-ab2c-2846f8c3ea41 - TokenCache: A matching item (access token or refresh token or both) was found in the cache
 
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
06/28/2018 03:10:08: 1cee5408-1053-49a3-ab2c-2846f8c3ea41 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
        Access Token Hash: JbVMMdITM8IBDIH1bwTftFDrH41VTBjLwNEy6Oi/aFA=
        Refresh Token Hash: [No Refresh Token]
        Expiration Time: 06/28/2018 03:47:11 +00:00
        User Hash: null
 
 
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
============================ HTTP REQUEST ============================
 
HTTP Method:
PUT
 
Absolute Uri:
https://management.azure.com/subscriptions/ba74a0f8-f8e1-41c1-9f9d-e1bfd23ff910/resourceGroups/Enterprise-Production-Web/providers/Microsoft.Web/serverfarms/Test?api-version=2016-09-01
 
Headers:
x-ms-client-request-id        : bcc8eba2-63c3-40ad-9f14-03862a82460d
accept-language               : en-US
 
Body:
{
  "properties": {
    "name": "Test",
    "hostingEnvironmentProfile": {
      "id": "/subscriptions/ba74a0f8-f8e1-41c1-9f9d-e1bfd23ff910/resourcegroups/Enterprise-Production-Web/providers/Microsoft.Web/hostingEnvironments/TechnologyEnabledServices"
    },
    "perSiteScaling": false
  },
  "sku": {
    "name": "I1",
    "tier": "Isolated",
    "capacity": 1
  },
  "location": "East US 2"
}
 
 
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
============================ HTTP RESPONSE ============================
 
Status Code:
Created
 
Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 2d00de74-b5d1-4217-b76e-6b4e3b716653
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 45b36fc2-8a8d-40bc-8032-1054b24cc843
x-ms-routing-request-id       : EASTUS2:20180628T031020Z:45b36fc2-8a8d-40bc-8032-1054b24cc843
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 28 Jun 2018 03:10:20 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
 
Body:
{
  "id": "/subscriptions/ba74a0f8-f8e1-41c1-9f9d-e1bfd23ff910/resourceGroups/Enterprise-Production-Web/providers/Microsoft.Web/serverfarms/Test",
  "name": "Test",
  "type": "Microsoft.Web/serverfarms",
  "kind": "app",
  "location": "East US 2",
  "properties": {
    "serverFarmId": 19,
    "name": "Test",
    "workerSize": "Default",
    "workerSizeId": 0,
    "workerTierName": null,
    "numberOfWorkers": 0,
    "currentWorkerSize": "Default",
    "currentWorkerSizeId": 0,
    "currentNumberOfWorkers": 0,
    "status": "Creating",
    "webSpace": "Enterprise-Production-Web-TechnologyEnabledServicesappseEastUS2webspace",
    "subscription": "ba74a0f8-f8e1-41c1-9f9d-e1bfd23ff910",
    "adminSiteName": null,
    "hostingEnvironment": "TechnologyEnabledServices",
    "hostingEnvironmentProfile": {
      "id": "/subscriptions/ba74a0f8-f8e1-41c1-9f9d-e1bfd23ff910/resourceGroups/Enterprise-Production-Web/providers/Microsoft.Web/hostingEnvironments/TechnologyEnabledServices",
      "name": "TechnologyEnabledServices",
      "type": "Microsoft.Web/hostingEnvironments"
    },
    "maximumNumberOfWorkers": 100,
    "planName": "VirtualDedicatedPlan",
    "adminRuntimeSiteName": null,
    "computeMode": "Dedicated",
    "siteMode": null,
    "geoRegion": "East US 2",
    "perSiteScaling": false,
    "numberOfSites": 0,
    "hostingEnvironmentId": "/subscriptions/ba74a0f8-f8e1-41c1-9f9d-e1bfd23ff910/resourceGroups/Enterprise-Production-Web/providers/Microsoft.Web/hostingEnvironments/TechnologyEnabledServices",
    "isSpot": false,
    "spotExpirationTime": null,
    "freeOfferExpirationTime": null,
    "tags": null,
    "kind": "app",
    "resourceGroup": "Enterprise-Production-Web",
    "reserved": false,
    "isXenon": false,
    "mdmId": "waws-prod-bn1-ed7d67f1_19",
    "targetWorkerCount": 1,
    "targetWorkerSizeId": 0,
    "provisioningState": "Succeeded",
    "webSiteId": null
  },
  "sku": {
    "name": "I1",
    "tier": "Isolated",
    "size": "I1",
    "family": "I",
    "capacity": 0
  }
}
 
 
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
Confirm
Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
New-AzureRmAppServicePlan : Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
At line:1 char:20
+ ... vicePlans = New-AzureRmAppServicePlan -Name $Name -ResourceGroupName  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmAppServicePlan], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.NewAzureAppServicePlanCmdlet
 
AzureQoSEvent: CommandName - New-AzureRmAppServicePlan; IsSuccess - False; Duration - 00:00:57.3090525; Exception - Microsoft.Rest.Azure.CloudException: Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
   at Microsoft.Azure.Management.WebSites.AppServicePlansOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.AppServicePlansOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.AppServicePlansOperationsExtensions.<CreateOrUpdateAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.AppServicePlansOperationsExtensions.CreateOrUpdate(IAppServicePlansOperations operations, String resourceGroupName, String name, AppServicePlan appServicePlan)
   at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.CreateAppServicePlan(String resourceGroupName, String appServicePlanName, String location, String adminSiteName, SkuDescription sku, String aseName, String aseResourceGroupName,
Nullable`1 perSiteScaling)
   at Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.NewAzureAppServicePlanCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
Finish sending metric.
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
8:10:58 PM - NewAzureAppServicePlanCmdlet end processing.
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
8:10:59 PM - NewAzureAppServicePlanCmdlet end processing.
Confirm
Continue with this operation?
[Y] Yes [A] Yes to All [H] Halt Command [S] Suspend [?] Help (default is "Yes"):
[DBG]: PS Microsoft.PowerShell.Core\FileSystem
 
 
[TROUBLESHOOTING STEPS]
The creation successfully per admin controller log:
Format:HTML Format Version:1.0 StartHTML: 165 EndHTML: 5072 StartFragment: 303 EndFragment: 5040 StartSelection: 303 EndSelection: 303 
Run: [Kusto.Explorer] [Kusto.Explorer on SAW] [Kusto.WebExplorer] [Lens] https://wawseus.kusto.windows.net:443/wawsprod 
AntaresAdminControllerEvents | where (TIMESTAMP >= datetime(2018-06-28T00:01:00Z) and TIMESTAMP < datetime(2018-06-28T04:00:30Z)) //| where SourceMoniker == 'WAWSPRODSN1' 
| where SubscriptionId=="ba74a0f8-f8e1-41c1-9f9d-e1bfd23ff910"
| where Address == "/websystems/WebSites/serverfarms/subscriptions/ba74a0f8-f8e1-41c1-9f9d-e1bfd23ff910/webspaces/Enterprise-Production-Web-TechnologyEnabledServicesappseEastUS2webspace/serverfarms/Test"
| project TIMESTAMP , Address , OperationName , Operation , Exception , StatusCode , Message , EventMessage , TraceMessage , LogStatement

**Comment by lczc1988** [comment]
Any ETA to fix this? Thank you.

**Comment by panchagnula** [comment]
@lczc1988  just wanted to let you know that this bug is to handle the - Microsoft.Rest.Azure.CloudException: Exception of type 'Microsoft.Rest.Azure.CloudException' that is reported even after the app service plan gets created successfully, I updated the title to reflect this. & the answer to your question - No ETA as yet.

**Comment by panchagnula** [comment]
This should now be fixed please use the new Az commandlets. Please let us know if this is not the case.
