### ISSUE TITLE
[WebApp] Add Ps1XmlAttribute to cmdlets output types properties.

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Azure/azure-powershell#6579]
### Introdution
To make the cmdlets output more convenient and consistent across all the resource providers we developed a mechanism to generate a format.ps1xml file out of a cmdlet output types. Details and examples are [here](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/generate-format.ps1xml-file.md).

### Task
Add  Ps1XmlAttribute to all relevant output types properties for:
- [ ] WebApps

**Comment by panchagnula** [comment]
@vladimir-shcherbakov  this is something the ASE feature crew on our team will handle. We will have this assigned to the right folks assigned to this. I don't want an issue to be assigned on GitHub when its notyet being worked on by a dev, Thank you.

**Comment by panchagnula** [comment]
We will look at our existing commands & make these updates as needed.
