### ISSUE TITLE
[Network]  Add Ps1XmlAttribute to cmdlets output types properties.

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Azure/azure-powershell#6580]
### Introdution
To make the cmdlets output more convenient and consistent across all the resource providers we developed a mechanism to generate a format.ps1xml file out of a cmdlet output types. Details and examples are [here](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/generate-format.ps1xml-file.md).

### Task
Add  Ps1XmlAttribute to all relevant output types properties for:
- [ ] Network

**Comment by MiYanni** [comment]
@EvgenyAgafonchikov Good call. Closing.
