### ISSUE TITLE
[KeyVault ] Add Ps1XmlAttribute to cmdlets output types properties.

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Azure/azure-powershell#6581]
### Introdution
To make the cmdlets output more convenient and consistent across all the resource providers we developed a mechanism to generate a format.ps1xml file out of a cmdlet output types. Details and examples are [here](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/generate-format.ps1xml-file.md).

### Task
Add  Ps1XmlAttribute to all relevant output types properties for:
- [ ] KeyVault

**Comment by maddieclayton** [comment]
Unassigned myself as the KeyVault team should decide which properties should be included in the table view.

**Comment by isra-fel** [comment]
Closing the issue.
We will use table format for newly introduced models.
