### ISSUE TITLE
[Storage] Add Ps1XmlAttribute to cmdlets output types properties.

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Azure/azure-powershell#6582]
### Introdution
To make the cmdlets output more convenient and consistent across all the resource providers we developed a mechanism to generate a format.ps1xml file out of a cmdlet output types. Details and examples are [here](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/generate-format.ps1xml-file.md).

### Task
Add  Ps1XmlAttribute to all relevant output types properties for:
- [ ] Storage

**Comment by blueww** [comment]
@vladimir-shcherbakov 

As we discussed before, There are several problems need to resolve. As I see you have resolved most of them like groupBy, listView.

But there are still one problem, some of the cmdlets output the object type from the XSCL (like Azure File ). And other ourput type include object from XSCL as a member (like AzureStorageBlob). Could we also support that? Like:
1. We have a file to storage the format that can't be define in Powershell code, When generate format, the generated file will contain both the generated format from PowerShell code and the format file.

I have commit to add part of format in Azure.Storage in Powershell code. Would you please help to review and see if any comments? https://github.com/wastoresh/azure-powershell/commit/1670231abc82572aa5478ec5b3209bd6cba40686

**Comment by blueww** [comment]
@vladimir-shcherbakov 

I find an issue of the format: for ListView, when add the Lable and ScriptBlock, the generated format xml, won't include the label, but only scriptBlock.

Such as ：
`  [Ps1Xml(Label = "Logging.Version", Target = ViewControl.List, ScriptBlock = "$_.Logging.Version", Position = 0)]`

Now Will generate:
```xml
              <ListItem>
                <ScriptBlock>$_.Logging.Version</ScriptBlock>
              </ListItem>
```

Should generate:
```xml
              <ListItem>
                <Label>Logging.Version</Label>
                <ScriptBlock>$_.Logging.Version</ScriptBlock>
              </ListItem>
```

**Comment by vladimir-shcherbakov** [comment]
@blueww 
I see no reason for such a behavior in the [source code](https://github.com/Azure/azure-powershell/blob/preview/tools/RepoTasks/RepoTasks.RemoteWorker/AppDomainWorker.cs#L315). Can I user the [commit]( https://github.com/wastoresh/azure-powershell/commit/1670231abc82572aa5478ec5b3209bd6cba40686) to reproduce the issue?

**Comment by blueww** [comment]
@vladimir-shcherbakov 
You can use this commit (https://github.com/wastoresh/azure-powershell/commit/f6b21690407dcce11388d19a356fae69a6760637#diff-a87cb03e614ebd5f5c52fa3299750409R45) to repro the issue. See the line 45 of file src/Storage/Commands.Storage/Model/ResourceModel/PSSeriviceProperties.cs

**Comment by blueww** [comment]
@vladimir-shcherbakov

The label can be generated in the latest code, so this ListView issue not eixst now.

But there is still one issue, some of the cmdlets output the object type from the XSCL (like Azure File ). And other ourput type include object from XSCL as a member (like AzureStorageBlob). Could we also support that? Like:
1. We have a file to storage the format that can't be define in Powershell code, When generate format, the generated file will contain both the generated format from PowerShell code and the format file.

**Comment by vladimir-shcherbakov** [comment]
@blueww 
I'm not sure I get the idea. Could you please give some example.

**Comment by blueww** [comment]
@vladimir-shcherbakov 

Such as Get-AzureStorageFile, return type is "CloudFile" from XSCL.
If we change the type, it will be a breaking change.


Can we have a partially format file, which containes the format defination for type from XSCL, and when build the format file, we will merge it with the format file build from the code.

**Comment by vladimir-shcherbakov** [comment]
@blueww 
If I get it right, you have one format.ps1xml file for XSCL types (you maintain it manually ) and one that gets generated with the tool. You want to merge these two files into one. Is it correct?

**Comment by blueww** [comment]
Generally correct. 
Actually I would like to merge the  format.ps1xml file for XSCL types, when generate the format.ps1xml from code. 
So the type we can't add format in code can be in the generated format.ps1xml file.

**Comment by vladimir-shcherbakov** [comment]
@blueww 
PowerShell allows to use multiple format.ps1xml files specified in the Azure.Storage.psd1 module manifest:
```
# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = '.\Microsoft.WindowsAzure.Commands.Storage.format.XSCL.ps1xml',  '.\Microsoft.WindowsAzure.Commands.Storage.format.generated.ps1xml'
```
Does it make sense to keep manual and generated files separated instead of merging?

**Comment by blueww** [comment]
@vladimir-shcherbakov 
Using multiple format.ps1xml files work for me.
If you are OK with the solution, I will raise a PR to add the generated format recently.

`FormatsToProcess = '.\Microsoft.WindowsAzure.Commands.Storage.format.ps1xml',  '.\Microsoft.WindowsAzure.Commands.Storage.generated.format.ps1xml'`

**Comment by vladimir-shcherbakov** [comment]
@blueww 
I'm OK, please open a PR.

**Comment by blueww** [comment]
@vladimir-shcherbakov 
PR is raised in https://github.com/Azure/azure-powershell/pull/6683
Please help to review.

**Comment by vladimir-shcherbakov** [comment]
closing as done.
