### ISSUE TITLE
ASM :: Get-AzureWebsiteJob throws exception with no parameters

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#659]
# Symptom

If you run the `Get-AzureWebsiteJob` command with no parameters, you will receive an exception.

![image](https://cloud.githubusercontent.com/assets/466713/8938509/3cee2446-351c-11e5-837b-5ae2acbf8b86.png)
# Root Cause

An Azure Web Job must belong to an Azure Web App on App Service. However, the `Get-AzureWebsiteJob` does not require the user to specify the Web App `-Name` parameter (it is non-mandatory).
# Action Items
- Make the `-Name` parameter mandatory for the `Get-AzureWebsiteJob` command.
- Add a parameter like `-ListAll` that enumerates all Azure Web Apps, and retrieves Web Jobs for each Web App.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
