### ISSUE TITLE
Add Azure RMVMSSExtension with success but extension not updated

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-powershell#6592]
Use AddAzureVMextesion command and execute with success 
#Update Azure VM Scale Set

$vmss = Get-AzureRmVmss -ResourceGroupName $RGName -VMScaleSetName $vmssName

$vmss = Add-AzureRmVmssExtension -VirtualMachineScaleSet $vmss -Name $vmssExtensionName -Publisher $vmssPublisher -Setting $vmssSettings -ProtectedSetting $vmssProtectedSettings -Type $vmssExtenstionType -TypeHandlerVersion $vmssTypeHandlerVersion -AutoUpgradeMinorVersion $true

Update-AzureRmVmss -ResourceGroupName $RGName -Name $vmssName -VirtualMachineScaleSet $vmss

and then use  Get-AzureRmVmss -ResourceGroupName $RGName -VMScaleSetName $vmssName to know the current version of scripts in vmss are updated as shown in the following: 

![image](https://user-images.githubusercontent.com/4621560/42233505-120cd150-7ef2-11e8-8f51-dcbfc4149467.png)

Go to Azure portal, recheck the version in 'automation scripts' and remote login with SSH to instance of VMSS, found script version not updated. 

![image](https://user-images.githubusercontent.com/4621560/42233595-4fd939c4-7ef2-11e8-84b0-1400d4def3a1.png)

Please take a look, thanks 

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```
![image](https://user-images.githubusercontent.com/4621560/42233682-82ee0376-7ef2-11e8-8a5d-51c8326dbe3f.png)

### Environment Data

```powershell
$PSVersionTable
```
![image](https://user-images.githubusercontent.com/4621560/42233658-721d0088-7ef2-11e8-931c-b09cd25f0434.png)

### Debug Output

```

```

**Comment by cormacpayne** [comment]
@hyonholee @gbowerman hey guys, would you mind taking a look at this issue?

**Comment by cloudmelon** [comment]
after deploying VMSS extension, actually, the automation script updated after a few minutes ( I retest it ). But the VMSS extension doesn't execute the scripts version 2...

**Comment by gbowerman** [comment]
+ @rajsqr

**Comment by rajsqr** [comment]
Hi - Could you please check the update mode for this VMSS? If it is in manual configuration, you have to manually update each VMSS instance.

**Comment by cloudmelon** [comment]
hi @rajsqr I added also **_-AutoUpgradeMinorVersion $true_** in the command, so that would be working ?

**Comment by rajsqr** [comment]
Please check out the documentation here on how to bring up VMs up to date with the latest scale set model- https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-upgrade-scale-set#how-to-bring-vms-up-to-date-with-the-latest-scale-set-model 

Adding @nkuchta to comment further.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
