### ISSUE TITLE
[SQL] New-AzureRmResource fails when running the test in record mode

### ISSUE THREAD

**Issue by yaakoviyun** [Azure/azure-powershell#6601]
### Description

[SQL] New-AzureRmResource fails when running the test in record mode

### Script/Steps for Reproduction

Uncomment the test in src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/ThreatDetectionClassicStorageTests.cs and try to run it in record mode.

According to M.Yanni:

That function, Create-ClassicTestEnvironmentWithParams, worked previously because your test project was directly referencing the Resources module. We changed it to reference a common Resources SDK and a AzureRM.Resources.ps1 file. This allows us to keep control of when commonly used functionality is updated, and we can update it easily in one spot across the board.

I believe, to fix this, you’d need to implement New-AzureRmResource in AzureRM.Resources.ps1:
https://github.com/yaakoviyun/azure-powershell/blob/preview/src/ResourceManager/Common/Commands.ScenarioTests.ResourceManager.Common/AzureRM.Resources.ps1

The functions are pretty simple. They just take in the params and pass them to the SDK call. I’m just surprised New-AzureRmResource doesn’t exist within this file already.

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

6.0.1

### Environment Data

```powershell
$PSVersionTable
```

PSVersion 5.1.16299.431
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.16299.431
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

### Debug Output

```

```

**Comment by aamalvea** [comment]
We're sorry we weren't able to address this issue. If you are still experiencing a problem, please file a new bug and we will respond within 48 hours.
