### ISSUE TITLE
Pick a default value for `OSDiskCreateOption` in cmdlet `Set-AzureRmVmssStorageProfile` or make it mandatory 

### ISSUE THREAD

**Issue by praries880** [Azure/azure-powershell#6608]
#### Issue origin
This issue came out of multiple customer reports in https://github.com/Azure/azure-powershell/issues/6413.

#### Issue description
@hyonholee 
According to the validate command for the [OSDisk model](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Compute/Management.Compute/Generated/Models/VirtualMachineScaleSetOSDisk.cs#L160), `CreateOption` is a required property.

Following instructions [here](https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ssl-powershell#create-a-virtual-machine-scale-set) when i do create the StorageProfile, I dont see the property `CreateOption` set on the OSDisk : 
```powershell

PS D:\Public\azure-powershell\src\Package\Debug\ResourceManager\AzureResourceManager\AzureRM.Compute> Set-AzureRmVmssSto
rageProfile $vmssConfig `
>>   -ImageReferencePublisher MicrosoftWindowsServer `
>>   -ImageReferenceOffer WindowsServer `
>>   -ImageReferenceSku 2016-Datacenter `
>>   -ImageReferenceVersion latest


Sku                           :
  Name                        : Standard_DS2
  Capacity                    : 2
UpgradePolicy                 :
  Mode                        : Automatic
  AutomaticOSUpgrade          : False
VirtualMachineProfile         :
  StorageProfile              :
    ImageReference            :
      Publisher               : MicrosoftWindowsServer
      Offer                   : WindowsServer
      Sku                     : 2016-Datacenter
      Version                 : latest
    OsDisk                    :
      WriteAcceleratorEnabled : False
Location                      : westus
```

The cmdlet [`Set-AzureRmVmssStorageProfile`](https://github.com/Azure/azure-powershell/blob/f34c546fea58d48819e968cab9ac3dd5c50551f3/src/ResourceManager/Compute/Stack/Commands.Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssStorageProfileCommand.cs#L230) does not require the [OSDiskCreateOption](https://github.com/Azure/azure-powershell/blob/f34c546fea58d48819e968cab9ac3dd5c50551f3/src/ResourceManager/Compute/Stack/Commands.Compute/Generated/VirtualMachineScaleSet/Config/SetAzureRmVmssStorageProfileCommand.cs#L82) param. This needs to be fixed. 

We need to 
* either pick a value that makes sense (I think `FromImage`) is appropriate in this case, or 
* we need to make the param 'OSDiskCreateOption` mandatory, this becomes a breaking change though. 

I would prefer option one here.

**Comment by praries880** [comment]
@hyonholee can you take a look at this issue?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
