### ISSUE TITLE
New-AzureRMVM - Receive-Job not able to save cmdlet error from background job.

### ISSUE THREAD

**Issue by MaximoTrinidad** [Azure/azure-powershell#6615]
### Description

OK! I'm not sure to where to address this issue but I think is a Azure Cmdlet.

So, I'm submitting to a background job the **New-AzureRMVM** command to create a VM but with some existing resources.  In other words, I'm trying to fail the command.

The job is submitted as a scriptblock to be executed with a Start-Job.

The main issue is, when I run the code in the console, the job fails (which I expect), but I don't get a returning object with the an error in the Receive-Job. 

Instead, executing the Receive-Job -Job $job -keep will only display the error message in a stream text that can't be saved to a PSObject.

I can't use the following one-liner to save the error:
```
$saveJob = Receive-Job -Job $Job -Keep
```

### Script/Steps for Reproduction

The following I can reproduce in both Windows PowerShell and PowerShell Core.  This job will fail due to existing "PublicIpAddressName" use when creating a new VM on an existing ResourceGroup.

```powershell

## - Prepare scriptblock for background job:
$Name = 'TestAzureVMCreate'
$JobScript = {
	
	## - Sign-On to Azure:
	Import-AzureRmContext -Path 'c:\Temp\wPSC_AsubRMprofile.json' | Out-Null;
	
	## - Set both UserID and Password for Vm(s) to use:
	## _ Build Credentials:
	$MyUserName = "max_t";
	$MyPassword = ConvertTo-SecureString '$Adm1n001!' -asplaintext -force;
	$MyCred = new-object -typename System.Management.Automation.PSCredential -argumentlist $MyUserName, $MyPassword;
	
	## - Prepare parameters for VM1:
	$vm1Params = @{
		ResourceGroupName   = 'MyAzureResources'
		Name			    = 'Win2k16VM7'
		ImageName		    = 'Win2016Datacenter'
		VirtualNetworkName  = 'Win2k16VM1'
		SubnetName		    = 'Win2k16VM1'
		PublicIpAddressName = 'tutorialPublicIp3'
		Credential		    = $MyCred
		OpenPorts		    = 3389
	};
	
	## - Create VM1:
	New-AzureRmVM @vm1Params
};

## - Submit Job to background process:
$job = Start-Job -Name $Name -ScriptBlock $JobScript;

## - Display Job Status:
Get-Job

## - Save Job results ( this step won't work):
$saveJob = Receive-Job -Job $Job -Keep

#-> $saveJob is Null

```

### Expected Results
Sample image of a successful New-AzureVM:

![azure_receivejob_01_2018-07-06_11-57-19](https://user-images.githubusercontent.com/19892435/42388738-833fb10c-8114-11e8-9aeb-fa30ba7671f7.jpg)

### Actual Results
Failed cmdlet should allow to, at least, save the error message from the job.  The error displayed to the screen can't be saved as an object coming from the Receive-Job cmdlet:

![azure_receivejob_02_2018-07-06_11-57-19](https://user-images.githubusercontent.com/19892435/42388811-b7e1f5c8-8114-11e8-9e73-835d0d9d097c.jpg)

### Module Version

**Windows PowerShell**
```powershell

PS [3] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17704.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17704.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS [17] > Get-Module -Name AzureRM -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.1.1      AzureRM


```
**PowerShell Core**
```
PS [6] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.3
PSEdition                      Core
GitCommitId                    v6.1.0-preview.3
OS                             Microsoft Windows 10.0.17704
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS [21] > Get-Module -Name AzureRM.Netcore -ListAvailable


    Directory: C:\Program Files\PowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.12.0     AzureRM.Netcore

```

### Environment Data
Included above!

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by cormacpayne** [comment]
@MaximoTrinidad Hey Maximo, I believe that you are only capturing the data from the output stream when assigning the variable to the result of `Receive-Job`, so it shouldn't capture the data from the error stream. I think your best option is to use the `-ErrorVariable` parameter and assign the data from the error stream to a variable that you can later access. Let me know if that doesn't work for you and we can talk about other ways to mitigate this issue 😀

**Comment by MaximoTrinidad** [comment]
Sorry! I didn't notice this until today.  And, this issue is closed before I can even do some test and add more more feedback.
:(
