### ISSUE TITLE
ErrorAction does not take effect on Azure Stack Admin cmdlets

### ISSUE THREAD

**Issue by daozha** [Azure/azure-powershell#6622]
### Description

Currently $ErrorActionPreference is set to Stop in all Azure Stack Admin cmdlets, so when cmdlets fail, it will always stop the script regardless of how ErrorAction is set when calling cmdlets.

### Script/Steps for Reproduction

Using Backup module:
Set-AzsBackupShare -Username "wrongusername" -Password (ConvertTo-SecureString -AsPlainText -Force "wrongpassword") -BackupShare "wrongpath" -EncryptionKey (ConvertTo-SecureString -AsPlainText -Force "invalidkey") -ErrorAction Continue

```powershell

```

### Module Version

Azure Stack Admin module 1.3.0

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by deathly809** [comment]
We are going to fix this in the next release of the Azure Stack admin modules.

**Comment by deathly809** [comment]
Fixed in https://github.com/Azure/azure-powershell/pull/6821
