### ISSUE TITLE
Get/Remove-AzureRmRoleAssignment with root scope fails

### ISSUE THREAD

**Issue by Jimmyf1** [Azure/azure-powershell#6624]
### Description

Errors may be encountered in the `Get-AzureRmRoleAssignment` and `Remove-AzureRmRoleAssignment` cmdlets when specifying the root scope (parameter **-Scope "/"**). The nature of the error suggests that the user does not have the RBAC action 'Microsoft.Authorization/roleAssignments/read' over the specified scope when they in fact do. The error message indicates the scope to be '/providers/Microsoft.Authorization'.

### Script/Steps for Reproduction

Use `Get-AzureRmRoleAssignment` with -Scope "/"... or pipe (filtered) output from that command (`Get-AzureRmRoleAssignment -Scope "/"`) to `Remove-AzureRmRoleAssignment`.

Observe the error, such as:

```
Remove-AzureRmRoleAssignment : The client 'xyz@xyz’ with object id xyz' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/read' over scope 
'/providers/Microsoft.Authorization'.
At line:1 char:135
+ ... "User Access Administrator" -Scope "/" | Remove-AzureRmRoleAssignment
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Remove-AzureRmRoleAssignment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.RemoveAzureRoleAssignmentCommand
```

**Comment by cormacpayne** [comment]
@darshanhs90 Hey Haridarshan, would you mind taking a look at this issue?

**Comment by darshanhs90** [comment]
@Jimmyf1 Could you share the stacktrace, so that i can check your permissions and let you know what is the underlying issue

**Comment by Jimmyf1** [comment]
I believe this is a repro of the issue.

RequestId      : edcd6d1e-f49e-420a-8d1a-e42b0b0634a1
Message        : The client 'live.com#xyz@hotmail.com' with object id 'a7b1e92f-b88b-4458-ab98-f5db50a43ffa'
                 does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/read' over
                 scope '/providers/Microsoft.Authorization'.
ServerMessage  : AuthorizationFailed: The client 'live.com#xyz@hotmail.com' with object id
                 'a7b1e92f-b88b-4458-ab98-f5db50a43ffa' does not have authorization to perform action
                 'Microsoft.Authorization/roleAssignments/read' over scope '/providers/Microsoft.Authorization'.
                 (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {Forbidden}
RequestMessage : {GET https://management.azure.com///providers/Microsoft.Authorization/roleAssignments?api-version=2018
                 -01-01-preview}
InvocationInfo : {Get-AzureRmRoleAssignment}
Line           : Get-AzureRmRoleAssignment -scope "/" -RoleDefinitionName "user access administrator"
Position       : At line:1 char:1
                 + Get-AzureRmRoleAssignment -scope "/" -RoleDefinitionName "user access ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperations.<ListForScopeWithHttpMessages
                 Async>d__14.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperationsExtensions.<ListForScopeAsync>
                 d__19.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperationsExtensions.ListForScope(IRoleA
                 ssignmentsOperations operations, String scope, ODataQuery`1 odataQuery)
                    at Microsoft.Azure.Commands.ResourceManager.Common.Paging.GenericPageEnumerator`1..ctor(Func`1
                 list, Func`2 listNext, UInt64 first, UInt64 skip)
                    at Microsoft.Azure.Commands.ResourceManager.Common.Paging.GenericPageEnumerable`1.GetEnumerator()
                    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
                    at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClientExtensions.ToPSRoleAs
                 signments(IEnumerable`1 assignments, IEnumerable`1 roleDefinitions, AuthorizationClient policyClient,
                 ActiveDirectoryClient activeDirectoryClient, Boolean excludeAssignmentsForDeletedPrincipals)
                    at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.FilterRoleAssignment
                 s(FilterRoleAssignmentsOptions options, String currentSubscription, UInt64 first, UInt64 skip)
                    at Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()

**Comment by darshanhs90** [comment]
@Jimmyf1 When the get request gets made it gets appended with /providers/Microsoft.Authorization.
Since the requests is made at scope "/" the request will be like Get roleassignments at "//providers/Microsoft.Authorization" which inherently will be "/providers/Microsoft.Authorization".
Since you donot have the read permission at "/" scope, you are getting this error.
Which is by design.

**Comment by jimmyfit** [comment]
@darshanhs90 The user affected is assigned Owner role at root MG scope

**Comment by Jimmyf1** [comment]
@darshanhs90 the affected user has Owner role assigned at root MG scope
