### ISSUE TITLE
Powershell documentation lacking

### ISSUE THREAD

**Issue by allar7** [Azure/azure-powershell#6630]
I was referred here as someone said that engineering handles reference documentation.

A customer found the following document lacking:
https://docs.microsoft.com/en-us/powershell/module/azurerm.profile/set-azurermcontext?view=azurermps-6.4.0
Select-AzureRmSubscription is not listed with the others. I'm not sure if other commandlets are missing as that the select one is what we were looking for.

**Comment by sphibbs** [comment]
Select-AzureRmSubscription is an alias for Select-AzureRmContext. If you run get-help Select-AzureRMSubscription from within PowerShell it will display help for Select-AzureRmContext. 

We are working with PowerShell and the documentation team to add better help or ways to identify aliases. 

Are there other ways documentation is lacking or just other aliases? Please reopen and add any details about missing help.
