### ISSUE TITLE
The term 'Remove-AzureStorageAccount' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by amjad** [Azure/azure-powershell#6632]
I am getting this error, when I am trying to run this command.

```
Remove-AzureStorageAccount : The term 'Remove-AzureStorageAccount' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

+     Remove-AzureStorageAccount -StorageAccountName ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Remove-AzureStorageAccount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

What can be causing this? 

### Module Version

Script     5.4.1      AzureRM                                                                                                                                   
Script     5.0.1      AzureRM  

### Environment Data

                                                                                                                    
PSVersion                      5.0.10586.117                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                          
BuildVersion                   10.0.10586.117                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                  
WSManStackVersion              3.0                                                                                                                              
PSRemotingProtocolVersion      2.3                                                                                                                              
SerializationVersion           1.1.0.1     

### Debug Output

```
DEBUG: 1:53:20 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.
DEBUG: 1:53:20 PM - using account id '______________'...
DEBUG: AzureQoSEvent: CommandName - Get-AzureRmContext; IsSuccess - True; Duration - 00:00:00.0071796; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 1:53:21 PM - GetAzureRMContextCommand end processing.
DEBUG: 1:53:21 PM - GetAzureRMContextCommand end processing.
```

**Comment by cormacpayne** [comment]
@amjad this cmdlet is found in the `Azure` module -- do you have this module installed on your machine in addition to `AzureRM`?

**Comment by MaximoTrinidad** [comment]
@amjad,

Yes! I was going to ask that... it should have been "**Remove-AzureRMStorageAccount**".
:)

**Comment by amjad** [comment]
How do I check with `Azure` module is installed? 

if I run `Get-Module -Name Azure -ListAvailable` I do not get anything.

**Comment by MaximoTrinidad** [comment]
It should be AzureRM module!

**Comment by MaximoTrinidad** [comment]
Azure module is the classic (old model).

**Comment by amjad** [comment]
Yes I do have AzureRM module installed.

Script 5.4.1 AzureRM
Script 5.0.1 AzureRM

**Comment by amjad** [comment]
@MaximoTrinidad **Remove-AzureRMStorageAccount** this worked for me! Thanks!
