### ISSUE TITLE
Login screen not redirecting me to powershell console while debugging powershell

### ISSUE THREAD

**Issue by anusapan** [Azure/azure-powershell#6633]
### Description

While debugging the code, First step is to login through login-azurermaccount cmdlet which will ask for the credentials, but the issue is that when I entered the credentials the login popup window redirecting me to "Microsoft Office Home"  screen instead of successfully authenticate.

Adding screen after login screen.

![image](https://user-images.githubusercontent.com/31940305/42474229-c6f09948-837b-11e8-967a-d399143cd48a.png)

**Comment by cormacpayne** [comment]
Closing as this will be resolved offline.
