### ISSUE TITLE
Set-AzureRmWebApp : The parameter phpVersion has an invalid value

### ISSUE THREAD

**Issue by LukeDearden** [Azure/azure-powershell#6635]
### Description
Trying to use Set-AzureRmWebApp to disable PHP using the parameter -PhpVersion Off (which used to work) now returns the exception
Set-AzureRmWebApp : The parameter phpVersion has an invalid value

### Script/Steps for Reproduction

```powershell
Set-AzureRmWebApp -AppServicePlan $AppServicePlan -Name $Name -ResourceGroupName $ResourceGroupName  -PhpVersion Off
```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.4.0      AzureRM
Script     6.2.1      AzureRM
Script     6.0.1      AzureRM
Script     5.7.0      AzureRM
Script     5.6.0      AzureRM
Script     5.1.1      AzureRM
```

### Environment Data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1198
x-ms-request-id               : 83c90166-ea3b-4fbe-a9b8-a5b9acc58bae
x-ms-correlation-request-id   : 83c90166-ea3b-4fbe-a9b8-a5b9acc58bae
x-ms-routing-request-id       : FRANCECENTRAL:20180710T101414Z:83c90166-ea3b-4fbe-a9b8-a5b9acc58bae
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 10 Jul 2018 10:14:13 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "Code": "BadRequest",
  "Message": "The parameter phpVersion has an invalid value.",
  "Target": null,
  "Details": [
    {
      "Message": "The parameter phpVersion has an invalid value."
    },
    {
      "Code": "BadRequest"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "01007",
        "MessageTemplate": "The parameter {0} has an invalid value.",
        "Parameters": [
          "phpVersion"
        ],
        "Code": "BadRequest",
        "Message": "The parameter phpVersion has an invalid value."
      }
    }
  ],
  "Innererror": null
}
```

**Comment by cormacpayne** [comment]
@panchagnula Hey Sisira, would you mind taking a look at this issue?

**Comment by panchagnula** [comment]
@LukeDearden the Python Version Parameter needs a string which should be the version of the Python. This property doesn't support 'off' https://docs.microsoft.com/en-us/powershell/module/azurerm.websites/set-azurermwebapp?view=azurermps-6.4.0

**Comment by LukeDearden** [comment]
@panchagnula Hi, Just to be clear this was for php not python. 

This parameter used to be accepted. which is why we added it to a bunch of scripts. If its no longer supported how do we disable Php via powershell?

**Comment by panchagnula** [comment]
@shrirampophali in the json file for the Arm template use this "phpVersion": "". Let me know if this doesn't work

**Comment by panchagnula** [comment]
@LukeDearden  started a PR with the fix

**Comment by scabana** [comment]
I'm having the same issue here. I think the suggested fix is not the right one. From what I see, the old REST Api supported the "off" value and this changed. This would mean anyone currently setting the phpVersion to off explicitly will have this problem and will require code changes to deploy their services using Azure powershell or any Http Rest client. I would really like to get the REST Api support "off" again to support older code (or even code written 15 days ago that may have been validated by a QA team and that doesn't work anymore). 

I hope I'm wrong.

**Comment by yell0wc0w** [comment]
I needed some working ARM templates urgently today, but panchagnula's workaround for "phpVersion": "" works fine for now.  Thanks!

**Comment by panchagnula** [comment]
@naveedaz can you comment regarding the phpVersion: off value being supported using older API versions vs not currently. Looking at resources.azure.com seems like the value supported is "" for off instead of the string itself. Thank you! //CC: @Nking92 since I will be out of office for a few days.

**Comment by shrirampophali** [comment]
Solution suggested by @panchagnula  ( "phpVersion": "") works like a charm. Thanks @panchagnula !

**Comment by InterceptBV** [comment]
Using "" doenst work when running Set-AzureRmWebApp in Powershell':

Set-AzureRmWebApp : Cannot validate argument on parameter 'PhpVersion'. The argument is null or empty. Provide an argument that is not null or empty, and 
then try the command again.

**Comment by sorenhansendk** [comment]
Agree with @InterceptBV - we have the same problem.
What can we do with the Powershell SDK? We don't use ARM templates.

**Comment by scabana** [comment]
@sorenhansendk : here's what I did (didn't remove extra parameters...): 

```powershell
$propertyObject = @{
        "siteConfig" = @{"alwaysOn" = $True; "phpVersion" = "" }
        "clientAffinityEnabled" = $False
    }

Set-AzureRmResource -ApiVersion 2015-08-01 -PropertyObject $propertyObject -ResourceId $WebApp.Id -Force
```

**Comment by InterceptBV** [comment]
Using "Set-AzureRmWebApp" also works:

$AppSettings = @{"phpVersion" = ""}

Set-AzureRmWebApp -name $WebAppName -ResourceGroupName $RGNameWebApp -AppSettings $AppSettings

**Comment by panchagnula** [comment]
@grahambunce this was a regression on our end , while our backend made changes to disable invalid version values. @pvbchak  can you share the RCA details we have for this issue here?

**Comment by pvbchak** [comment]
Official RCA: 
The Azure PowerShell Cmdlets Set-AzureRmWebapp and Set-AzureRmResource accept a range of parameters including PHPVersion. This is a string value that would set the relevant PHP version i.e 7.1. 5.6 and so on. 
A small subset of Azure App Service customers used a short cut syntax of  -PhpVersion off as a security measure which did have the desired effect of clearing the PHP Version from the Azure App Service site config. The off syntax was never specifically handled (the fact that it worked a bug). The Azure App Service infrastructure was recently updated and this syntax now results in “Set-AzureRmWebApp : The parameter phpVersion has an invalid value.” because "Off" was never recognized as a valid value. This broke customers who took a dependency on the previously buggy behavior.
