### ISSUE TITLE
The process 'C:\\Program Files\\Update Services\\Tools\\WsusUtil.exe' with arguments 'postinstall CONTENT_DIR=F:\\WSUS' failed to stop within the specified timeout. 

### ISSUE THREAD

**Issue by cmptscpeacock** [Azure/azure-powershell#6636]
Hi,

I'm deploying a VM with a DSC to install WSUS (taken from here:https://github.com/mgreenegit/UpdateServicesDsc/blob/master/Tests/Integration/UpdateServicesConfig.ps1)

Azure seems to deploy but timeout when the WSUS content is downloaded. There is a lot of data so it will take time. There shouldn't be a timeout, or if it's needed then a switch maybe to select how long the timeout should be.

"message": "VM has reported a failure when processing extension 'wsus'. Error message: \"DSC Configuration 'wsus' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_UpdateServicesServer failed to execute Set-TargetResource functionality with error message: The process 'C:\\Program Files\\Update Services\\Tools\\WsusUtil.exe' with arguments 'postinstall CONTENT_DIR=F:\\WSUS' failed to stop within the specified timeout. The SendConfigurationApply function did not succeed. LCM failed to start desired state configuration manually.\"."

**Comment by cormacpayne** [comment]
@cmptscpeacock is the above failure coming from an `AzureRM` cmdlet? If so, please provide the cmdlet(s) and the corresponding parameters you used, as well as the version of `AzureRM` you have installed on your machine (this information can be retrieved by running `Get-Module -Name AzureRM -ListAvailable`)

**Comment by cmptscpeacock** [comment]
Hi,

Thanks for getting in touch. I run this VM extension during deployment:

        {
          "apiVersion": "2015-06-15",
          "type": "Microsoft.Compute/virtualMachines/extensions",
          "name": "[concat(parameters('vmName1'),'/',parameters('vmName1DscConfig'))]",
          "location": "[resourceGroup().location]",
          "dependsOn": [
            "[concat('Microsoft.Compute/virtualMachines/', parameters('vmName1'))]"
          ],
          "properties": {
            "publisher": "Microsoft.Powershell",
            "type": "DSC",
            "typeHandlerVersion": "2.11",
            "autoUpgradeMinorVersion": true,
            "settings": {
              "ModulesUrl": "[concat(parameters('_artifactsLocation'),'/configuration/configuration.zip',parameters('_artifactsLocationSasToken'))]",
              "ConfigurationFunction": "[parameters('vmName1DscConfigPath')]",
              "Properties": {
                "DomainName": "[parameters('domainName')]",
                "AdminCreds": {
                  "UserName": "[parameters('adminUsername')]",
                  "Password": "PrivateSettingsRef:AdminPassword"
                }
              }
            },
            "protectedSettings": {
              "Items": {
                "AdminPassword": "[parameters('adminPassword')]"
              }
            }
          }
        },

It then calls the DSC config in the link as shown in the original post.

**Comment by cmptscpeacock** [comment]
@cormacpayne any update?

Chris

**Comment by maddieclayton** [comment]
@cmptscpeacock It seems from your script that you are not calling any AzureRM cmdlets (Start-AzureRmAutomationDscCompilationJob is seen at the bottom but then commented out.  Are you seeing this error when running this cmdlet?

**Comment by maddieclayton** [comment]
Closing as no response.  If you are still running into this issue feel free to reopen.

**Comment by ericscheffler** [comment]
I'm actually experiencing this same issue; can we reopen this issue, or should I create a new one?
