### ISSUE TITLE
Import-Module AzureRM takes too long and consumes tons of cpu

### ISSUE THREAD

**Issue by elangelo** [Azure/azure-powershell#6645]
### Description

We are extensively using AzureRM from out of the VSTS release pipeline and notice a huge load on our cpu's when we import AzureRM (which the vststask 'Run Azure Powershell' does automatically does for you)
This is also reproducible on a normal workstation.

I would like to understand better why 'just importing a module' is consuming this much resources. Without looking into the code at all it feels like that is a lot to setup some 'path variables'...

A result of that is that our ops team is actually urging us to switch to the node/typescript tasks in vsts which consume about 0 cpu... As we are mostly C# devs we felt dealing with powershell was ok... dealing with tsx is quite another story...

Is there anything we can do on our side that would improve the situation?

### Script/Steps for Reproduction

```powershell
Import-Module AzureRM
```

### Module Version

```powershell
> Get-Module -Name AzureRM -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.4.0      AzureRM
Script     5.7.0      AzureRM
Script     5.4.1      AzureRM
```

### Environment Data

```powershell

Name                           Value
----                           -----
PSVersion                      5.1.17134.165
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.165
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by yobyot** [comment]
I've noticed this, too. I think it's because `Import-Module AzureRm` imports the *entire* set of cmdlets for *all* Azure services.

If, for example, you know you are just signing in and configuring some Vnets, you could try

`Import-Module AzureRM.profile`
`Import-Module AzureRM.Network`

It should make things faster. Who needs data lake cmdlets, anyway?

**Comment by elangelo** [comment]
That would work but the VSTS Release pipeline always adds the whole AzureRM module in the runtime. Even importing the 'entire set' of cmdlets i would think that it is nothing more than adding them to your %PATH% variable so powershell knows where to find them.. It's not like they actually have to 'do' anything at that moment in time

**Comment by maddieclayton** [comment]
@elangelo Unfortunately we cannot change the functionality of Import-Module.  However, the task should not be importing all modules every time that you run a task.  Please file an issue against VSTS: https://github.com/Microsoft/vsts-tasks (we will also be working with this team to fix this behavior).
