### ISSUE TITLE
Add support for configuring SSL settings of Api Management instance using Powershell cmdlets

### ISSUE THREAD

**Issue by shantanu1singh** [Azure/azure-powershell#6658]
We're trying to automate our deployment of Api Management using the Api Management git repositories. However, Api Management currently doesn't support configuration for SSL settings of an instance using  Azure PowerShell cmdlets. We would like to have that support so that we can manage APIM completely through Azure Powershell instead of having to change things in the Portal.

**Comment by maddieclayton** [comment]
@solankisamir Can you take a look at this feature request?

**Comment by solankisamir** [comment]
@shantanu1singh have you taken a look at the cmdlets [Set-AzureRmApiManagement](https://docs.microsoft.com/en-us/powershell/module/azurerm.apimanagement/Set-AzureRmApiManagement?view=azurermps-6.4.0). This is already supported, look at the example #3. For more comprehensive script take a look [here](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/ApiManagement/Commands.ApiManagement.Test/ScenarioTests/ApiManagementTests.ps1#L246)

**Comment by shantanu1singh** [comment]
I couldn't find an options there to disable TLS 1.0 for example. We can do it through the portal and through the APIM ARM template. The link you added in your post only allows adding custom host names with default SSL bindings.

ARM template route -
![templatessl](https://user-images.githubusercontent.com/2570312/42836086-09f4a200-89af-11e8-9ece-dce46891ce88.PNG)

Portal -
![sslpicture](https://user-images.githubusercontent.com/2570312/42836088-0a0d81c6-89af-11e8-96af-375943548910.PNG)

**Comment by solankisamir** [comment]
@shantanu1singh, my bad I misunderstood the question. We will add this as a backlog.

**Comment by solankisamir** [comment]
[package](https://www.powershellgallery.com/packages/Az/2.1.0)
[documentation](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/?view=azps-2.1.0#api_management)
[releasenotes](https://github.com/Azure/azure-powershell/releases/tag/v2.1.0-May2019)
