### ISSUE TITLE
ASM/ARM :: Support Online Help

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#667]
# Symptom

When I run the  `Get-Help` command with the `-Online` parameter, and specify one of the Azure PowerShell commands in the `-Name` parameter, I receive an exception.

![image](https://cloud.githubusercontent.com/assets/466713/8961707/f4cc7e52-35d3-11e5-856f-6155ff3f9996.png)
# Expected Result

Since the Azure PowerShell commands are significantly lacking built-in documentation, they should at least support the PowerShell concept of "online help." I have created a video on MSDN Channel 9 recently, which describes a couple of different methods of incorporating online help into PowerShell commands.

https://channel9.msdn.com/Shows/MsftPowerShell/PowerShell-Two-Methods-of-Supporting-Online-Help

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ciphertxt** [comment]
+1

This would be great functionality, although the MSDN documentation can often be several iterations behind the current cmdlet set. That being said, something is better than nothing.

**Comment by rajinders** [comment]
+1

At this time one has to dig though actual code to find list of acceptable values for powershell cmdlets. So anything that can be done to improve on this would be great.

**Comment by devigned** [comment]
We are working to address the documentation issue on a couple fronts. 
- We're adding process around pull requests which will not allow pull requests which lower the documentation coverage. 
- We are working internally to expedite the publication of PowerShell ref content to MSDN so that it should be up-to-date with the latest release.

We'll look at adding online help after we nail down the items above. We expect to have the quick publication flow ready in a few weeks.

**Comment by markcowl** [comment]
@pcgeek86 @ciphertxt @rajinders I'm wondering if this issue would be resolved by having accurate help shipping with the cmdlets, or if using the ```-online`` switch has some additional goodness you feel is necessary?  T

**Comment by pcgeek86** [comment]
@markcowl This is actually complementary to built-in help. :) Both built-in PowerShell help and the online help work together to round off the documentation experience. The URI for the online help would link to the Azure documentation for the feature, which would likely also contain PowerShell examples, and even more platform context.

So, just for the sake of clarity, this particular issue report doesn't pertain at all to built-in help.

**Comment by markcowl** [comment]
@coreyp-at-msft documentation-related issue you may be able to help with

**Comment by cormacpayne** [comment]
This has been resolved as of [Azure PowerShell 5.0.0](https://github.com/Azure/azure-powershell/releases/tag/v5.0.0-November2017)
