### ISSUE TITLE
Create seperate jobs for network test recorder in jenkins

### ISSUE THREAD

**Issue by praries880** [Azure/azure-powershell#6674]
Fork the network test job in Jenkins so that different tests can be run under separate subscriptions.

**Comment by praries880** [comment]
@MikhailTryakhov  NRP Tests without owner : 
* [TestExpressRouteCrossConnectionApis](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Network/Commands.Network.Test/ScenarioTests/ExpressRouteCrossConnectionTests.cs#L33)

Can you fix this?

**Comment by MikhailTryakhov** [comment]
@praries880 
https://github.com/Azure/azure-powershell/pull/6706
