### ISSUE TITLE
Enable ManagementPartner tests

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#6678]
Currently there are five tests in the ManagementPartner test suite, but none of them are running as a part of our current build:

- `TestGetPartner`
- `TestGetPartnerNoParnterId`
- `TestNewParnter`
- `TestUpdateParnter`
- `TestRemoveParnter`

All of the tests are failing for the following reason:

```
Method not found: 'System.String Microsoft.Azure.Management.ManagementPartner.Models.PartnerResponse.get_PartnerName()'.
```

The work needs to be done to enable these tests, and then the test assembly should be referenced in the [`TestMappings.json`](https://github.com/Azure/azure-powershell/blob/preview/TestMappings.json#L82) (unless this file has already been removed in PR https://github.com/Azure/azure-powershell/pull/6675)

**Comment by cormacpayne** [comment]
@jeffrey-ACE Hey Jeffrey, would you mind taking a look at this issue?

**Comment by jeffrey-ACE** [comment]
@cormacpayne I will take a look.

**Comment by jeffrey-ACE** [comment]
@cormacpayne this is the fix: https://github.com/Azure/azure-powershell/pull/6817, can you please take a look?

**Comment by maddieclayton** [comment]
Merged!
