### ISSUE TITLE
help - Documentation for New-Azure​RmDisk

### ISSUE THREAD

**Issue by yupsay** [Azure/azure-powershell#6682]
Please correct the examples for New-Azure​RmDisk in get-help New-Azure​RmDisk and @ https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/new-azurermdisk?view=azurermps-6.4.0.

Change needed is "StandardLRS" in example one needs be changed to "Standard_LRS".

**Comment by maddieclayton** [comment]
Thanks for opening this issue! I will close as soon as your PR is merged :)

**Comment by yupsay** [comment]
I’m an MS FTE, can I get access to do it my self in future?

________________________________

**Comment by maddieclayton** [comment]
@yupsay I don't think there is a way to give limited permissions on GitHub to specific users, so only admins will be able to close issues (and do other more dangerous actions in the repo, such as merging).

**Comment by yupsay** [comment]
The change is showing up in here
                https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmDisk.md
But I don’t see anything on the public page
                https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/new-azurermdisk?view=azurermps-6.5.0

The change requested was
Original

Update

Example 1
$diskconfig = New-AzureRmDiskConfig -Location 'Central US' -DiskSizeGB 5 -AccountType StandardLRS -OsType Windows -CreateOption Empty -EncryptionSettingsEnabled $true;

Example 1
$diskconfig = New-AzureRmDiskConfig -Location 'Central US' -DiskSizeGB 5 -AccountType Standard_LRS -OsType Windows -CreateOption Empty -EncryptionSettingsEnabled $true;

**Comment by maddieclayton** [comment]
@yupsay This will update when we next release - two weeks from yesterday.
