### ISSUE TITLE
Enable MachineLearning tests

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#6684]
Currently there are eight tests in the MachineLearning test suite, but none of them are running as a part of the current build. Three of the tests are OK to enable, but five of them are not:

- `TestCreateAndGetRegionalProperties`
- `TestListWebServices`
- `TestUpdateWebService`
- `TestCreateWebServiceFromFile`
- `TestCreateGetRemoveWebService`

Four of the tests are disabled due to long run-time ( > 30s), which stems from [this line](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/MachineLearning/Commands.MachineLearning/Utilities/WebServicesClient.cs#L41-L42) that changes the `LongRunningOperationRetryTimeout` value on the client. The fifth test (`TestCreateGetRemoveWebService`) fails because it is unable to find a matching HTTP request, which means the test should be re-recorded.

The work needs to be done to enable these tests, and then the test assembly should be referenced in the [`TestMappings.json`](https://github.com/Azure/azure-powershell/blob/preview/TestMappings.json#L82) (unless this file has already been removed in PR https://github.com/Azure/azure-powershell/pull/6675)

**Comment by cormacpayne** [comment]
@NonStatic2014 Hey Klein, would you mind taking a look at this issue?

**Comment by v-strudm-msft** [comment]
We see this was posted over two years ago, but was never addressed so are closing it. Our apologies. Should this still be an issue, please re-open it and we will respond on a timely basis. Thank you.
