### ISSUE TITLE
Get-AzureRmDataFactoryV2Trigge failing with error  Method not found: 'Newtonsoft.Json.Serialization.IAttributeProvider  Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'

### ISSUE THREAD

**Issue by nirmalpavan** [Azure/azure-powershell#6685]
Get-AzureRmDataFactoryV2Trigge failing with error  
Get-AzureRmDataFactoryV2Trigger : Method not found: 'Newtonsoft.Json.Serialization.IAttributeProvider 
Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'.
At line:14 char:14
+ ... TgrNames =  Get-AzureRmDataFactoryV2Trigger -ResourceGroupName $Resou ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmDataFactoryV2Trigger], MissingMethodException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataFactoryV2.GetAzureDataFactoryTriggerCommand

Please help here.

**Comment by maddieclayton** [comment]
@nirmalpavan Please include the output of "Get-Module -ListAvailable" as well as "Get-AzureRmDataFactoryV2Trigger <parameters used to get error> -Debug"

**Comment by cormacpayne** [comment]
@nirmalpavan also, would you mind confirming that this is being run in Azure Automation? We have seen previous instances of this error and they were all from scripts run in Azure Automation.

**Comment by maddieclayton** [comment]
Closing as no response.  @nirmalpavan If you are still seeing this issue feel free to reopen.

**Comment by nirmalpavan** [comment]
this is from azure automation only and I got reply from automation team that it is a known issue and they are fixing it by July end.
