### ISSUE TITLE
webapp:Support AppOffline With Publish-AzureWebsiteProject

### ISSUE THREAD

**Issue by martincostello** [Azure/azure-powershell#669]
Occasionally when publishing to an Azure Web App from Visual Studio Online an error similar to the following occurs:

```
Web Deploy cannot modify the file '{FILENAME}' on the destination because it is locked by an external process. In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.
Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.
```

The `Publish-AzureWebsiteProject` cmdlet should support a parameter with allows the AppOffline rule to be used, or indeed a way to pass arbitrary additional flags on to MSDeploy.

**Comment by pbevis** [comment]
Absolutely! Getting the same problem here, our build keeps randomly failing.

**Comment by jkonecki** [comment]
+1 - please add support for AppOffline!

**Comment by GraemeSMiller** [comment]
+1

**Comment by gligoran** [comment]
+1

**Comment by jakubka** [comment]
+1

**Comment by danbucholtz** [comment]
+1 - major pain for our team

**Comment by dimkanewtown** [comment]
+1

**Comment by martyMM** [comment]
+1

**Comment by martincostello** [comment]
I think that makes +10 now. Is this planned any time soon?

**Comment by vipervf1** [comment]
+1

**Comment by SomaticIT** [comment]
+1

**Comment by tgfl-tom** [comment]
+1 .. please!

**Comment by abatishchev** [comment]
+1

**Comment by seanfisher** [comment]
This is a major deal for us because we need automated continuous integration, not something where a person has to go click the websites off and on again. From Microsoft/vso-agent-tasks#1233 :

I've run into this as well. Here's what we're doing as a work around. We run an Azure Resource Manager powershell script with something like the following code as `Manage-WebApps.ps1`:

```Powershell
Param(
    [Parameter(Mandatory = $true, ParameterSetName = 'Start')]
    [Parameter(Mandatory = $true, ParameterSetName = 'Stop')]
    [string]$Environment,

    [Parameter(Mandatory = $true, ParameterSetName = 'Start')]
    [switch]$Start,

    [Parameter(Mandatory = $true, ParameterSetName = 'Stop')]
    [switch]$Stop
)

$ResourceGroup = "--Your Resource Group--"
$appsToManage = @("app1", "app2", "appN")

ForEach ($app in $appsToManage) {
    $appName = "$Environment-$app"
    if ($Start) {
        Start-AzureRmWebApp -ResourceGroupName $ResourceGroup -Name $appName | Out-Null
        Write-Host "Started web app '$appName'"
    }
    if ($Stop) {
        Stop-AzureRmWebApp -ResourceGroupName $ResourceGroup -Name $appName | Out-Null
        Write-Host "Stopped web app '$appName'"
    }
}
```

We'll run this at the beginning of the release:

`Manage-WebApps.ps1 -Stop -Environment dev`

And this at the end:

`Manage-WebApps.ps1 -Start -Environment dev`


What other work-arounds have people found?

**Comment by brentdavid2008** [comment]
+1

**Comment by abatishchev** [comment]
Will `Additional Arguments: -enableRule:AppOffline` work for this?

**Comment by brentdavid2008** [comment]
I think so, as long as that's also available as some type of drop down in the build step, so the argument is added to the vNext builds automatically based on that.

**Comment by Rogn** [comment]
+1

**Comment by AndreaPic** [comment]
-1

**Comment by SimoneBWS** [comment]
+1

**Comment by twilly86** [comment]
status?  how do I fix this from a VSO tfs build?  I'm using the generic web app deploy task there.

**Comment by Rogn** [comment]
We have struggling with this since we started using Sqlite. Even though we carefully ensure that we close all connections, we still experience that the SQLite.Interop.dll file is locked making our current vsts builds fail :(
So currently we have fixed it by stopping and starting our App Services using the Azure PowerShell build task.

![image](https://cloud.githubusercontent.com/assets/3670768/15929607/452435a2-2e4e-11e6-9e8f-dde23b88dd2c.png)

Stop-WebApp.ps1

```
[CmdletBinding()]
param(
    [Parameter(Mandatory=$True)]
    [string]$WebSiteName,
	
	[Parameter(Mandatory=$False)]
    [string]$Slot
)

$WebSite = Get-AzureRmWebApp -Name $WebSiteName
$ResourceGroupName = $WebSite.ResourceGroup

if($Slot)
{
	Stop-AzureRmWebAppSlot -Name $WebSiteName -ResourceGroupName $ResourceGroupName -Slot $Slot | Out-Null
	Write-Host "Stopped slot '$Slot' belonging to web app '$WebSiteName'"
}
else
{
	Stop-AzureRmWebApp -Name $WebSiteName -ResourceGroupName $ResourceGroupName | Out-Null
	Write-Host "Stopped web app '$WebSiteName'"
}
```
Start-WebApp.ps1
```
[CmdletBinding()]
param(
    [Parameter(Mandatory=$True)]
    [string]$WebSiteName,
	
	[Parameter(Mandatory=$False)]
    [string]$Slot
)

$WebSite = Get-AzureRmWebApp -Name $WebSiteName
$ResourceGroupName = $WebSite.ResourceGroup

if($Slot)
{
	Start-AzureRmWebAppSlot -Name $WebSiteName -ResourceGroupName $ResourceGroupName -Slot $Slot | Out-Null
	Write-Host "Started slot '$Slot' belonging to web app '$WebSiteName'"
}
else
{
	Start-AzureRmWebApp -Name $WebSiteName -ResourceGroupName $ResourceGroupName | Out-Null
	Write-Host "Started web app '$WebSiteName'"
}

```

**Comment by pherbel** [comment]
+1

**Comment by Eneuman** [comment]
+1

**Comment by martincostello** [comment]
For those using VSTS, it [looks like a new task](https://www.visualstudio.com/news/2016-jul-7-vso) can be used to achieve AppOffline through other means:

> Web app deployment using ARM
> 
> This is a new version of the Azure Web App deployment task using the MSDeploy & Azure Resource Manager service connection. This enables new functionality that the existing one doesn’t have. For example, users can deploy Azure web jobs and Azure API apps in addition to ASPNET 4, Node.js, and Python-based web apps. We have also enabled support for common publish options, the ability to "Retain App Data", taking "App Offline" and the ability to "Remove additional files at destination". We have more work planned in future sprints such as supporting configuration transformations.

**Comment by RolfJ** [comment]
+1

**Comment by dvdobrovolskiy** [comment]
+1

**Comment by cormacpayne** [comment]
@Nking92 Hey Nick, would you mind taking a look at this feature request and see if it fits anywhere on your team's radar?

**Comment by missbruni** [comment]
+++++++++1

**Comment by chamikasandamal** [comment]
+1

**Comment by panchagnula** [comment]
@ahmedelnably this is an issue from 2015, can you please comment on this feature request?

**Comment by ahmedelnably** [comment]
With the deprecation of our RDFE commands, this command will stop working, we are going to replace it with a new command - Tracked here: https://github.com/Azure/azure-powershell/issues/6374
