### ISSUE TITLE
New-AzureService doesn't use the current subscription id

### ISSUE THREAD

**Issue by xuyangit** [Azure/azure-powershell#6694]
### Description
I need to new cloud service using the New-AzureService cmdlet. However, using Select-AzureRmSubscription to change the dafault subscription id has no impact. The service is just deployed on the wrong subscription. By using the debug mode, I find the New-AzureService cmdlet tries to visit management.core.windows.net while the Select-AzureRmSubscription visits management.azure.com. I also try to use the Select-AzureSubscription cmdlet, this seems to visit management.core.windows.net. I guess these two commands maybe old version commands. However, the assigned subscription cannot be found using Select-AzureSubscription cmdlet. And when I use Get-AzureSubscription to show subscriptions, just one record is returned while using Get-AzureRmSubscription gets 10+ returned. 

Besides, I can create the cloud service from the portal, so there is nothing wrong with the subscription itself. The version of Azure and AzureRm are both newest. I also reproduct this on my teammate's computer.

### Script/Steps for Reproduction

Connect-AzureRmAccount (login-azurermaccount or add-azureaccount, i have tried all the three cmdlets)
Get-AzureSubscription (only one record)
Get-AzureRmSubscription (10+ records)
Set-AzureSubscription (not working, it reports that the assigned subscription not found)
Set-AzureRmSubscription (ok, however, the created service is not deployed to this subscription)
New-AzureService (it can be created, but not the subscription i want)

```powershell

```

### Module Version

6.5.0

### Environment Data

Name                           Value
----                           -----
PSVersion                      5.1.17134.165
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.165
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1```

### Debug Output
Some secret information involved, so not pasted here for now.

**Comment by maddieclayton** [comment]
Hi @xuyangit.  "Azure" cmdlets control RDFE resources while "AzureRM" cmdlet control ResourceManager resources.  So, if you really need to run Get-AzureService, you will need to run the following cmdlets to control the RDFE environment:
```
Add-AzureAccount
Select-AzureSubscription
```
I think that the issue might be that you are not logged in using Add-AzureAccount.  Can I ask what you are trying to accomplish? We encourage people to use the new "AzureRM" cmdlet in place of the old "Azure" cmdlets that are now in maintenance mode.

**Comment by xuyangit** [comment]
@maddieclayton , thanks for your reply. What I need to do is to create azure service. I have tried the Add-AzureAccount but it fails to find the target subscription when i used select-azuresubscription. For this, I have debugged with the help of your souce code repo. 
I guess the select-subscription command will read all subscriptions information from the AzureSMProfile object (this should corresponds with the C:\Users\Username\AppData\Roaming\Windows Azure Powershell\AzureProfile.json). And the root issue seems to be that when I use Add-AzureAccount to login and generate this json file, only one subscription is included in this meta profile file. This is werid as the AzureRmContext.json includes all the subscriptions I own. 
As I can create cloud service in azure portal for the target subscription, I think the subsciption itself is working well.

**Comment by xuyangit** [comment]
@maddieclayton , I also tried to modify the AzureProfile.json and add the target subscription information. I can select it as default then. But when I create service using this profile, there is problem with certificates.

**Comment by xuyangit** [comment]
@maddieclayton ， do I need to be the owners of all these subscriptions? As the only one legal subscription that Add-AzureAccount shows is the one that belongs to me. For the other subscriptions, I am just contributor.

**Comment by artisticcheese** [comment]
How did you add yourself to "co-administrator"? There is no such role available in portal?
