### ISSUE TITLE
Not compatible with TPM ("Microsoft Platform Crypto Provider") certs ?

### ISSUE THREAD

**Issue by udf2457** [Azure/azure-powershell#6695]
Hi,

If I create a cert with the default provider, e.g. 

`New-SelfSignedCertificate -Subject "CN=foobar" -KeyAlgorithm RSA -KeyLength 2048  -CertStoreLocation "Cert:\CurrentUser\My" -NotAfter $((Get-Date).AddYears(1))`

Then `azure-powershell` works fine, e.g.

`Connect-AzureRmAccount -ServicePrincipal -CertificateThumbprint $CertificateThumbprint -ApplicationId $ApplicationId -TenantId $TenantId` works OK.

But if I create a certificate using the TPM (`-Provider "Microsoft Platform Crypto Provider"`) , e.g.:

`New-SelfSignedCertificate -Provider "Microsoft Platform Crypto Provider"  -Subject "CN=foobar" -KeyExportPolicy NonExportable -KeyAlgorithm RSA -KeyLength 2048  -CertStoreLocation "Cert:\CurrentUser\My" -NotAfter $((Get-Date).AddYears(1))`

Then I get a runtime error (`get-childitem -path "cert:\currentuser\my\<thumprint>` returns OK):

> Connect-AzureRmAccount : Invalid provider type specified.
> At C:\Users\foobar\Misc\foo.ps1:12 char:1
> + Connect-AzureRmAccount -ServicePrincipal -CertificateThumbprint $Cert ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : CloseError: (:) [Connect-AzureRmAccount], CryptographicException
>     + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

**Comment by markcowl** [comment]
@udf2457 Can you run ```Resolve-AzureRmError``` after this error to provide a few more details?  I am not sure which component is throwing this exception.

**Comment by udf2457** [comment]
@markcowl 

See attached.
[AzureRmError.txt](https://github.com/Azure/azure-powershell/files/2212815/AzureRmError.txt)

**Comment by markcowl** [comment]
@udf2457 Can you verify that the private key is accessible in this case?  This may be a bad error message and a key for which you do not have read permission.  Setting a key as non-exportable should *not* make it inaccessible, AFAIK, but thsi is a frequent reason for similar errors.

**Comment by udf2457** [comment]
@markcowl Eh ?!?  You do know what a TPM is, right ? The whole point of a TPM is that the private portion of the key can never be exposed to any other component, software process or user ?

With a TPM you say "Hey Mr TPM, do this with the private key for me", and the TPM returns the result.  Its a black box.

Hopefully I've just misunderstood your question, I can't believe you didn't already know all this !

**Comment by MiYanni** [comment]
@JasonRShaver Ping

**Comment by sphibbs** [comment]
This is not a scenario we will be enabling.
