### ISSUE TITLE
New-AzureVNetGateway :: Confusing error message for invalid GatewayType

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#67]
When you specify an invalid value for the -GatewayType parameter on the New-AzureVNetGateway command, the resulting error message is very confusing, and doesn't help the end user discover what is wrong.
- Azure PowerShell module 0.8.12
- PowerShell 5.0 November 2014 Preview

> New-AzureVNetGateway : BadRequest: The specified request content was not valid and could not be deserialized.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by markcowl** [comment]
Thanks for the report of this issue, assigning appropriately

**Comment by armthedark** [comment]
I have the same problem, might need to recreate the gateway.

**Comment by armthedark** [comment]
I have the same problem, might need to recreate the gateway.

**Comment by markcowl** [comment]
@pcgeek86 Trevor, are you still seeing this, and is it occurring in the ARM cmdlets.  If so, let's pursue this with the network team, if not, let's close

**Comment by pcgeek86** [comment]
@markcowl I don't immediately have time to repro, but thanks for acknowledging the issue.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
