### ISSUE TITLE
When are we getting Connect-ServiceFabricCluster

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6705]
Copied from customer comment on PowerShell Gallery: https://www.powershellgallery.com/packages/AzureRM.ServiceFabric/0.3.4?hubRefSrc=email&utm_source=lfemail&utm_medium=email&utm_campaign=lfnotification#lf-content=195715540:797536829

**Comment by markcowl** [comment]
@vaishnavk @juhacket Can you take a look at this request?  Please feel frere to respond directly on the PowerShell Gallery link

**Comment by aljo-microsoft** [comment]
Hello Vaishnavk has already commented on in the Gallery. 

There are two sets of PowerShell modules for managing Service Fabric:

ARM:

https://www.powershellgallery.com/packages/AzureRM.ServiceFabric/0.3.4?hubRefSrc=email&utm_source=lfemail&utm_medium=email&utm_campaign=lfnotification#lf-content=195715540:797536829

SDK:

https://docs.microsoft.com/en-us/powershell/module/servicefabric/connect-servicefabriccluster?view=azureservicefabricps
 

The user is asking to have the module that is used for managing through ARM, to support connecting directly to the cluster; that is a solved and redundant to the SDK's modules (so just use the SDK module).

**Comment by peterpogorski** [comment]
@markcowl does the response from aljo-microsoft above answer your question?
