### ISSUE TITLE
Add a -SelfSignedCertificate switch to New-AzureRMADAppCredential

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-powershell#6711]
### Description

Microsoft documentation [instructs users to use self-signed certificates](https://docs.microsoft.com/en-us/azure/automation/automation-create-runas-account) when updating your Azure automation account authentication with Run As accounts. This involves a very long script (see that article) that, among other things, creates a self-signed certificate using PowerShell and applies it to a new Azure AD app credential (in the CreateServicePrincipal function in the script in that article). The challenge, for me anyway, is that the method used to create the self-signed certificate requires that you can do such things on your local system, which you may not be able to do (for example, you cannot do this in an Azure function because you don't have access to the certificate store).

My request: if New-AzureRMADAppCredential is intended to be used with self-signed certificates that are dynamically generated before it is invoked, and then passed in through various parameters (-CertValue, -StartDate, and -EndDate), why not absorb all of that in New-AzureRMADAppCredential by adding a new parameter set that includes a -SelfSignedCertificate switch, with internal logic that generates a self-signed certificate entirely in memory (i.e. never touches disk nor the cert store), so that the cmdlet can be used pretty much anywhere to update your Azure automation account authentication with Run As accounts?

**Comment by markcowl** [comment]
@vrdmr can you take a look?

**Comment by ikanni** [comment]
@KirkMunro Thank you for raising this issue. I think we can workaround your issue by creating the self-signed certificate from KeyVault. Please check the below script and this may be useful
https://github.com/ikanni/PowerShellScripts/blob/master/AzureAutomation/RunAsAccount/New-RunAsAccountUsingKeyVault.ps1 _(I am sorry about the long script)._ 

Let us know if the above is useful.

**Comment by KirkMunro** [comment]
@ikanni Thank you for sharing this script. We have been working with it in testing, and so far the results look very promising. Once we have completed testing, I will come back and share the final results and close out this issue if it is resolved at that time.

**Comment by ikanni** [comment]
@KirkMunro Thank you for updating the initial results.  I hope all goes well !

**Comment by KirkMunro** [comment]
One change that in New-AzureRMADAppCredential that would be beneficial is a slight modification of my original request: Since adding a -SelfSignedCertificate parameter may require a lot of work from different teams, and therefore is unlikely to see the light of day, how about adding a parameter set that accepts an X509Certificate instead of requiring users to provide a path to a pfx file and a password for that file? Internally all the cmdlet is doing is loading the file to create the X509Certificate in memory. In my case, I already have the X509Certificate in memory, which I'm unnecessarily saving to/loading from disk just so that I can invoke this cmdlet.

Anyhow, we ran into a few hurdles, but I think I may have worked around them through modification of the script. It's still too early to tell, but I'll know more tomorrow.

**Comment by KirkMunro** [comment]
So here's where we're stuck at this point.

Our script eventually calls into New-AzureRmAutomationCertificate, passing on a path to a X509 certificate that has been written to disk. That command throws an Internal Server Error, so something unexpected is happening on the back end, and we don't have enough information to figure out what.

I have a few things I'm looking for from this point:

1. I would like to know how we can troubleshoot such issues further to figure out what is going on.
1. I would also like to know about the possibility of adding a parameter set to New-AzureRmAutomationCertificate so that you can invoke it with a certificate in memory instead of on disk, because I have a hunch that the error may have something to do with how we've written the certificate to disk and how it is being read from disk, both of which should be entirely unnecessary because when you dig into the internals, [New-AzureRmAutomationCertificate wants to pass in a binary certificate from memory anyway](https://github.com/Azure/azure-powershell/blob/4c684862731852e60ce302572ba0ccc3eff4b0c1/src/ResourceManager/Automation/Commands.Automation/Common/AutomationClient.cs#L1848-L1854).

Ideally I should be able to invoke New-AzureRmAutomationCertificate and pass in a certificate thumbprint plus either the X509Certificate2 object or a binary representation of that (from calling export), and internally it would just take that and use it directly without having to deal with a certificate file on disk at all. That doesn't guarantee it will resolve this issue, which is why I would like to know how to get more details from the Internal Server Error if possible, but it would eliminate unnecessary disk IO when you have the cert already in memory.

In case it helps, here is how I am currently writing the cert to disk before invoking New-AzureRmAutomationCertificate (which fails with the error):

```PowerShell
    function New-AutomationCertificateAsset {
        [CmdletBinding()]
        [OutputType([Microsoft.Azure.Commands.Automation.Model.CertificateInfo])]
        param(
            [Parameter(Mandatory = $true)]
            [string] $ResourceGroupName,

            [Parameter(Mandatory = $true)]
            [string] $AutomationAccountName,

            [Parameter(Mandatory = $true)]
            [string] $CertificateAssetName,

            [Parameter(Mandatory = $true)]
            [System.Security.Cryptography.X509Certificates.X509Certificate2] $X509Certificate,

            [Parameter(Mandatory = $true)]
            [System.Security.SecureString] $Password,

            [switch] $Exportable = $false,

            [switch] $PassThru = $false
        )
        
        $sharedParams = @{
            ResourceGroupName = $ResourceGroupName
            AutomationAccountName = $AutomationAccountName
            Name = $CertificateAssetName
        }

        Remove-AzureRmAutomationCertificate @sharedParams -ErrorAction Ignore

        $certificatePath = [System.IO.Path]::GetTempFileName()

        try {
            $certificateBytes = $x509Certificate.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pfx, $Password)
            [System.IO.File]::WriteAllBytes($certificatePath, $certificateBytes)

            $certificate = New-AzureRmAutomationCertificate @sharedParams -Path $certificatePath -Password $Password -Exportable:$Exportable
            if ($PassThru) {
                $certificate
            }
        } finally {
            if (Test-Path -LiteralPath $certificatePath) {
                Remove-Item -LiteralPath $certificatePath
            }
        }
    }
```

**Comment by ikanni** [comment]
Acknowledged. I was busy with other work. Please give me time. I will take a look and update

**Comment by KirkMunro** [comment]
Pkcs12 is set to the same enumerated value as Pfx, so this would not have any impact whatsoever because it would be doing the same thing. See [here](https://referencesource.microsoft.com/#mscorlib/system/security/cryptography/x509certificates/x509certificate.cs,27).

**Comment by ikanni** [comment]
@KirkMunro. I assume your issue is resolved and I am closing this issue. If u need further assistance please reopen the issue.
