### ISSUE TITLE
Record TestSharedIntegrationRuntime and TestSelfHostedIntegrationRuntime and enable them

### ISSUE THREAD

**Issue by hvermis** [Azure/azure-powershell#6715]
### Description

The tests are failing to record since they need real user credentials for. Ned to record them against production with user name and password.

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by hvermis** [comment]
@zhangyd2015  Please also add instructions in comments for the SSIS IR test how it needs to be recorded as per Maddie's request. @maddieclayton

**Comment by zhangyd2015** [comment]
Added instructions in comments for the SSIS IR test.

**Comment by maddieclayton** [comment]
Fixed.
