### ISSUE TITLE
Need dotNetCore projects for Azure Search Powershell

### ISSUE THREAD

**Issue by felixwa** [Azure/azure-powershell#6716]
### Description

As suggested by @MiYanni , create this issue to track.
https://github.com/Azure/azure-powershell/pull/6660

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by felixwa** [comment]
https://github.com/Azure/azure-powershell/pull/6660

**Comment by markcowl** [comment]
Closing as duplicate - this will be handled in bulk.
