### ISSUE TITLE
[Azs.Backup.Admin] Start-AzsBackup and Restore-AzsBackup does not show correct location in dialog if not provided

### ISSUE THREAD

**Issue by daozha** [Azure/azure-powershell#6719]
### Description

The dialog shows "Start backup at " when we skip providing location. As we'll get the location inside if not provided, we should also show that in dialog.

### Script/Steps for Reproduction

Start-AzsBackup
Restore-AzsBackup -Name <backupId>

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by deathly809** [comment]
I don't understand, can you elaborate?

**Comment by daozha** [comment]
If we run Start-AzsBackup -Location "xxxxx", then the confirmation message will be "Start backup at xxxxx?". While if we omit the Location param, the message will be "Start backup at ?"

As the internal logic in cmdlet will get the correct location when omitted, I think we can also show that in the confirmation message.

**Comment by deathly809** [comment]
Fix is in. https://github.com/Azure/azure-powershell/pull/7067
