### ISSUE TITLE
Unable to use New-AzureRmResourceGroupDeployment with parameter and optional parameter

### ISSUE THREAD

**Issue by Ranu2046** [Azure/azure-powershell#6722]
I am using  ARM project for the deployment and i am passing values from parameter file to the template. Also I am reading the parameter file in power shell script and assigning some of the values to parameters in parameter file and storing these values in optional parameter. Its works fine when deploy from visual studio. But when running from power shell it throws error. need help. below is the code snippet.

    $JsonParameters = Get-Content $TemplateParametersFile -Raw | ConvertFrom-Json
    if (($JsonParameters | Get-Member -Type NoteProperty 'parameters') -ne $null) {
        $JsonParameters = $JsonParameters.parameters
    }

$PfxCertificate = 'gw-sslCertificate'
$CerCertificate = 'gw-authenticationCertificate'
$ProxyCertificate = 'apim-ProxyCertificate'
    $OptionalParameters[$PfxCertificate] = $JsonParameters | Select -Expand $PfxCertificate -ErrorAction Ignore | Select -Expand 'value' -ErrorAction Ignore 
    $OptionalParameters[$CerCertificate] = $JsonParameters | Select -Expand $CerCertificate -ErrorAction Ignore | Select -Expand 'value' -ErrorAction Ignore
	$OptionalParameters[$ProxyCertificate] = $JsonParameters | Select -Expand $ProxyCertificate -ErrorAction Ignore | Select -Expand 'value' -ErrorAction Ignore 

New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $TemplateFile).BaseName + '-' + ((Get-Date).ToUniversalTime()).ToString('MMdd-HHmm')) `
                                       -ResourceGroupName $ResourceGroupName `
                                       -TemplateFile $TemplateFile `
                                       -TemplateParameterFile $TemplateParametersFile `
                                       @OptionalParameters `
                                       -Force -Verbose `
                                       -ErrorVariable ErrorMessages

**Comment by maddieclayton** [comment]
@Ranu2046 Please include the output of running these three commands:
```
Get-Module -ListAvailable
```
```
New-AzureRmResourceGroupDeployment <parameter used that generate error> -Debug
```
```
Resolve-AzureRmError (run in the same session where the failed cmdlet was run)
```

Please also include the parameter file with the confidential information edited out.

**Comment by maddieclayton** [comment]
Closing as no response. @Ranu2046 Feel free to reopen if you're still having this issue (please provide the information requested above).
