### ISSUE TITLE
Import-AzureKeyVaultCertificate fails to authenticate when running as Azure Automation Runbook

### ISSUE THREAD

**Issue by murdockcrc** [Azure/azure-powershell#6725]
### Description

I am trying to automate certain certificate management tasks by using Azure Automation PowerShell runbooks. Our certs are stored in Key Vault, therefore, these Automation runbooks need to access and modify Key Vault-stored certificates.

However, Key Vault-specific operations are failing with the following error:

```powershell
Import-AzureKeyVaultCertificate : Unable to retrieve service key for ServicePrincipal account 
<app_id>. Please log in again to supply the credentials for this service principal. In 
PowerShell, execute Connect-AzureRmAccount for Azure Resource Manager cmdlets or Add-AzureAccount for service management cmdlets.
```

This code works when running in the local machine, but it fail when it runs as an Azure Automation runbook. Can someone provide some guidance about how to properly run PoSH runbooks that require authentication towards a Key Vault instance?

### Script/Steps for Reproduction

```powershell
# Login to Azure
$cred = Get-AutomationPSCredential -Name "automation"
Login-AzureRmAccount -ServicePrincipal -Tenant "<my_aad_tenant_id>" -Credential $cred 

Get-AzureKeyVaultCertificate -VaultName "<my_kv_name>" -Name "CommonName"
```

### Module Version

```powershell
Unknown, this is running in the Azure Automation runtime.
```

### Environment Data

```powershell
Unknown, this is running in the Azure Automation runtime.
```

### Debug Output

```

```

**Comment by murdockcrc** [comment]
Thanks for that @tomkerkhove . In your sample, the Automation Account needs to have permissions assigned to KV via an access policy. In my scenario, I need to access the KV instance with a credential which is different from the Automation account (that's why I'm trying to pull that credentials with `Get-AutomationPSCredential`, since it's been added to the Automation Account as an Asset).

So I need to decouple the identify of the Automation Account from the identity that needs to access the KV instance.

**Comment by maddieclayton** [comment]
@AnatoliB Can you take a look at this issue?

**Comment by andyw248** [comment]
Any user will have to have an access policy configured in key vault with the correct set of permissions. No repro when access policy is configured properly.
