### ISSUE TITLE
Modify Set-AzureRmVMDiagnosticsExtension cmdlet to automate the install/config of diagnostics extension

### ISSUE THREAD

**Issue by BakerLabs** [Azure/azure-powershell#6736]
**ASK:** 
Modify the way the Set-AzureRmVMDiagnosticsExtension cmdlet works to improve the ability to automate the install/config of diagnostics extension on virtual machines.

**Background**
The cmdlet Set-AzureRmVMDiagnosticsExtension is touted as a way to automate the installation/configuration of the diagnostics configuration on an Azure VM as described here:

Use PowerShell to enable Azure Diagnostics in a virtual machine running Windows
https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/diagnostics-windows#sample-diagnostics-configuration
 
A review of the Set-AzureRmVMDiagnosticsExtension documentation indicates you need to create virtual machine specific XML file defined by the "-DiagnosticsConfigurationPath" switch for each VM you want to configure.  There is a single line in the file that makes it unique for each virtual machine you want to configure:
           <Metrics resourceId="(Update with resource ID for the VM)" >

**Problem**
If you want to automate the installation of the diagnostics extension for hundreds of virtual machines you would need to customize an XML file for each virtual machine. For a hundred virtual machines you would need a 100 XML config files.  This cumbersome requirement makes automation via PowerShell more labor intensive than using the portal to point and click. I have a customer that wants to enable this feature on over 400 VMs (Azure Government) and is doing this manually.

**Recommendation**
Remove the dependency to have the virtual machine resource ID ( <Metrics resourceId="(Update with resource ID for the VM)" >) in the XML file and add virtual machine resource ID as a switch on the cmdlet.  Doing this would let a person use the same XML config file for hundreds of extension deployments.

**Comment by maddieclayton** [comment]
@koralski @nibhat @savyasachisamal Can you take a look at this issue?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
