### ISSUE TITLE
Why New-AzureResource "PropertyObject" is required? It should be optional. (P1)

### ISSUE THREAD

**Issue by xingzhougmu** [Azure/azure-powershell#674]
Details:
I have a customer who is using New-AzureResouce command and found that the “PropertyObject” parameter is required although our MSDN states that it is optional. (The azure version is: 0.9.1)

PS C:\> New-AzureResource  -Location "CENTRAL US" -Name DSRG02 -ResourceGroupName RG2 -ResourceType "trendmicro.deepsecu
rity/accounts" -Plan @{Name="trendmicrodsplan003"; Product="accounts"; Publisher="trendmicro"}

cmdlet New-AzureResource at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
PropertyObject: !?
A hash table which represents resource properties.
PropertyObject:

In addition, I checked from my side where my Azure-PowerShell version is 0.9.5 (the latest). I found the property name has been changed from “PropertyObject” to “Properties”, and it is a required parameter in 0.9.5.

My questions:
1.	Could you please help me confirm if “PropertyObject” is required or optional in version 0.9.1?
2.	Any reason we changed the parameter name from “PropertyObject” to “Properties” and make it as required in version 0.9.5?
3.	Is it possible that we will set the parameter back to optional?

**Comment by ravbhatnagar** [comment]
@vivsriaus - I don't think we need this to be mandatory.

**Comment by ravbhatnagar** [comment]
Fixed for June PS release
