### ISSUE TITLE
Update NetCore abstractions

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6748]
### Description
- [ ] Make TokenCache a binary blob in the context container
  - [ ] TokenCache persistence depends on ContextContainer persistence
  - [ ] Remove TokenCache references in AzureSession
- [ ] Remove legacy properties from AzureSession
- [ ] Replace static properties for abstractions (ClientFactory, AuthenticationFactory, FileProvider) with calls to the ComponentRegistry
- [ ] Replace ContextProvider with calls to the registry
- [ ] Allow Set-AzureRmContext to select a current scope for a PowerShell session using a passed-in context

### Estimated Cost: 8

**Comment by dingmeng-xue** [comment]
NA to current code
