### ISSUE TITLE
Port powershell repo tooling to NetStandard and VS2017

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6752]
### Description

Make sure these tools are pointed at Az:
- [x] Help generation docs
- [x] Help checks
- [x] Signature Verifier
- [x] BreakingChange Analyzer
- [x] Documentation metadata generator
- [x] CorporateValidation tools (ci-signing) [verify no changes needed]
- [ ] CheckAssemblies.ps1
- [x] index.json and outputtypes.json

Changes needed for all post-1.0 releases:
- [ ] Version Controller

**Comment by maddieclayton** [comment]
Finished all that is needed for 1.0.0.  Opened two other issues to cover the remaining work:
https://github.com/Azure/azure-powershell/issues/8042
https://github.com/Azure/azure-powershell/issues/8041
