### ISSUE TITLE
Convert preview modules to NetStandard

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6755]
### Description

- [ ] Add netstandard projects and metadata for all desktop projects in the PowerShell repo
- [ ] Add netstandard projects and metadata for existing preview branches

### Estimated Cost: 8

**Comment by maddieclayton** [comment]
Find-Module -Name AzureRM.* -Repository PSGallery | Where-Object {$_.Name -notlike "*Netcore*"} |
Where-Object {$_.Author -eq "Microsoft Corporation"} | ForEach-Object {Find-Module -Name $_.Name -Repository PSGallery -
AllVersions -AllowPrerelease} | Where-Object {$_.Version -like "*preview"}

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
5.1.0-preview        AzureRM.KeyVault                    PSGallery            Microsoft Azure PowerShell - KeyVault ...
4.4.0-preview        AzureRM.KeyVault                    PSGallery            Microsoft Azure PowerShell - KeyVault ...
4.6.0-preview        AzureRM.Compute                     PSGallery            Microsoft Azure PowerShell - Compute s...
6.0.0-preview        AzureRM.Automation                  PSGallery            Microsoft Azure PowerShell - Automatio...
6.8.1-preview        AzureRM.Network                     PSGallery            Microsoft Azure PowerShell - Network s...
6.4.0-preview        AzureRM.Network                     PSGallery            Microsoft Azure PowerShell - Network s...
6.2.1-preview        AzureRM.Resources                   PSGallery            Microsoft Azure PowerShell - Azure Res...
5.2.0-preview        AzureRM.DataLakeStore               PSGallery            Microsoft Azure PowerShell - Data Lake...
6.0.0-preview        AzureRM.Storage                     PSGallery            Microsoft Azure PowerShell - Storage s...
5.0.4-preview        AzureRM.Storage                     PSGallery            Microsoft Azure PowerShell - Storage s...
5.0.3-preview        AzureRM.Storage                     PSGallery            Microsoft Azure PowerShell - Storage s...
5.0.2-preview        AzureRM.Storage                     PSGallery            Microsoft Azure PowerShell - Storage s...
5.0.1-preview        AzureRM.Storage                     PSGallery            Microsoft Azure PowerShell - Storage s...
4.11.4-preview       AzureRM.Sql                         PSGallery            Microsoft Azure PowerShell - Sql servi...
4.8.1-preview        AzureRM.Sql                         PSGallery            Microsoft Azure PowerShell - Sql servi...
4.8.0-preview        AzureRM.Sql                         PSGallery            Microsoft Azure PowerShell - Sql servi...
4.7.0-preview        AzureRM.Sql                         PSGallery            Microsoft Azure PowerShell - Sql servi...
4.5.0-preview        AzureRM.Sql                         PSGallery            Microsoft Azure PowerShell - Sql servi...
0.4.0-preview        AzureRM.EventGrid                   PSGallery            Microsoft Azure PowerShell - EventGrid...
5.0.0-preview        AzureRM.Websites                    PSGallery            Microsoft Azure PowerShell - Websites ...
0.9.1-preview        AzureRM.PolicyInsights              PSGallery            Microsoft Azure PowerShell - Azure Pol...
0.9.0-preview        AzureRM.PolicyInsights              PSGallery            Microsoft Azure PowerShell - Azure Pol...
0.1.1-preview        AzureRM.ManagementPartner           PSGallery            Microsoft Azure PowerShell - Managemen...
0.1.0-preview        AzureRM.ManagementPartner           PSGallery            Microsoft Azure PowerShell - Managemen...
0.1.4-preview        AzureRM.SignalR                     PSGallery            Microsoft Azure PowerShell - Azure Sig...
0.1.3-preview        AzureRM.SignalR                     PSGallery            Microsoft Azure PowerShell - Azure Sig...
0.1.2-preview        AzureRM.SignalR                     PSGallery            Microsoft Azure PowerShell - Azure Sig...
0.1.1-preview        AzureRM.SignalR                     PSGallery            Microsoft Azure PowerShell - Azure Sig...
0.1.0-preview        AzureRM.SignalR                     PSGallery            Microsoft Azure PowerShell - Azure Sig...

**Comment by MiYanni** [comment]
Modified it to get only the latest preview version of each:

```powershell
Find-Module -Name AzureRM.* -Repository PSGallery | `
Where-Object {$_.Name -notlike '*Netcore*' -and $_.Author -eq 'Microsoft Corporation'} | `
ForEach-Object {Find-Module -Name $_.Name -Repository PSGallery -AllVersions -AllowPrerelease} | `
Where-Object {$_.Version -like '*preview'} | `
Group-Object -Property Name | `
Select-Object -Property @{Name = 'Name'; Expression = {$_.Group[0].Name}},@{Name = 'Version'; Expression = {$_.Group[0].Version}}

Name                      Version
----                      -------
AzureRM.KeyVault          5.1.0-preview
AzureRM.Compute           4.6.0-preview
AzureRM.Automation        6.0.0-preview
AzureRM.Network           6.8.1-preview
AzureRM.Resources         6.2.1-preview
AzureRM.DataLakeStore     5.2.0-preview
AzureRM.Storage           6.0.0-preview
AzureRM.Sql               4.11.4-preview
AzureRM.EventGrid         0.4.0-preview
AzureRM.Websites          5.0.0-preview
AzureRM.PolicyInsights    0.9.1-preview
AzureRM.ManagementPartner 0.1.1-preview
AzureRM.SignalR           0.1.4-preview
```

**Comment by maddieclayton** [comment]
Should be just waiting on AzureRM.Storage.

**Comment by markcowl** [comment]
AzureRM.Storage is complete, they just need to update their management client
