### ISSUE TITLE
Fix breaking changes in ActiveDirectoryClient for 5.x versions of AzureRM.Resources

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6775]
### Description

```Commands.Common.Graph.RBAC.ActiveDirectoryClient``` introduced some breaking changes here: https://github.com/Azure/azure-powershell/pull/6008/files

We need to find a way to create a shim in Profile to support the new and old APIs, or to update the older cmdlets to use the new methods.

This is at least required for version 5.0.1 of AzureRm.Resources, and potentially for other versions released before AzureRM 6.0.0

- [ ] Determine if we can release a new version of Commands.Common.Graph.RBAC that implements the older method overloads, without breaking new versions based on the new library (looks like we cannot, as we have cmdlets that use the parameterless overloads with a different return type, as here:  https://github.com/Azure/azure-powershell/blob/8bd4c84a1b51b86ffc2d8977d5dcc438df480afa/src/ResourceManager/Resources/Commands.Resources/ActiveDirectory/RemoveAzureADServicePrincipalCommand.cs#L92 but it is worth time to check.
- [ ] Either publish a new version of profile that includes implementation for the older method overloads, or release a new version of AzureRM.Resources v 5.0.1 that uses the newer methods.

### Estimated Cost: 8

**Comment by SqlBenjamin** [comment]
Is this the reason why if I use "Add-AzureRmAccount" (loading "AzureRM.profile\5.3.1\Microsoft.IdentityModel.Clients.ActiveDirectory.dll" before creating an object of type "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext" (by loading "AzureAD\2.0.1.16\Microsoft.IdentityModel.Clients.ActiveDirectory.dll") I fail on the "AcquireTokenAsync" method? I came to open this bug but it seems this may be the same issue. If I create the AuthenticationContext before loading the AzureRM assemblies everything works as it should.

**Comment by cormacpayne** [comment]
This has been fixed.
