### ISSUE TITLE
Intellisense for New-AzureVNetGateway parameters not working

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#68]
Hello,

On the `New-AzureVNetGateway` command, I was fairly confident that the `-GatewayType` and `-GatewaySKU` parameters supported tab/auto-completion via Intellisense, however I'm not seeing this behavior on Azure PowerShell 0.8.11 or 0.8.12, at the very least. Instead, the standard file-system auto-completion appears when you attempt to perform Intellisense / tab completion.

Could you please ensure that the appropriate parameter values are enabled for auto-completion for `-GatewayType` and `-GatewaySKU`?

FYI, I'm using the Windows Management Framework Core 5.0 November 2014 Preview.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by markcowl** [comment]
Thanks for the report of this issue, assigning appropriately

**Comment by markcowl** [comment]
@pcgeek86 Are you still seeing this in the ARM version of the cmdlet?  We should be able to add a ValidateSet for these

**Comment by pcgeek86** [comment]
Mark,

All looks good now. Thanks for the follow-up!

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

<img width="1072" alt="screen shot 2016-02-12 at 6 06 27 pm" src="https://cloud.githubusercontent.com/assets/466713/13024554/7afc8e4c-d1b3-11e5-8b3e-733d8c87108c.png">
<img width="1072" alt="screen shot 2016-02-12 at 6 06 34 pm" src="https://cloud.githubusercontent.com/assets/466713/13024553/7afbd556-d1b3-11e5-8a03-853e5767bd7c.png">

**Comment by SavindraSingh** [comment]
For me 'GatewaySku' parameter is still not available for New-AzureRmVirtualNetworkGateway Cmdlet.
![gatewaysku](https://cloud.githubusercontent.com/assets/16442754/14749906/c20d37e2-08df-11e6-8212-569b02ac9b29.PNG)

**Comment by pcgeek86** [comment]
@SavindraSingh Make sure you're running the latest version of the module.

**Comment by SavindraSingh** [comment]
Yeahh.. I just updated the module from Git hub. Now it is working as expected.

Thank you for the inputs.
