### ISSUE TITLE
Get-AzureRmPolicyDefinition BuiltIn and Custom switches not working as expected

### ISSUE THREAD

**Issue by mikewo** [Azure/azure-powershell#6800]
### Description

When I run the Get-AzureRmPolicyDefinition cmdlet with no name and include just the switch parameters of either builtIn or custom I received the same results as if I didn't include the switches. I would have expected Get-AzureRmPolicyDefinition -custom would only return custom definitions and -builtIn to only return built in definitions.

### Script/Steps for Reproduction

```powershell
(Get-AzureRmPolicyDefinition).Count
(Get-AzureRmPolicyDefinition -builtin).Count
(Get-AzureRmPolicyDefinition -custom).Count
```

In my subscription I have a custom definition. It doesn't matter how I run the Get-AzureRmPolicyDefinition cmdlet it doesn't seem to filter correctly with either switch parameter. It always gives me the same count. When I run the Get-AzureRmPolicyDefinition -builtin I see my custom definition included in the output and likewise, when I run Get-AzureRmPolicyDefinition -custom I see ALL the definitions. 

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.5.0      AzureRM

```

### Environment Data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.165
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.165
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

**Comment by bebattis** [comment]
Has this issue seen any updates? I just ran into this issue today.

**Comment by mikewo** [comment]
This seems to be corrected in the new Az cmdlets.
