### ISSUE TITLE
Login-AzureRmAccount : The browser based authentication dialog failed to complete. Reason: The server or proxy was not found.

### ISSUE THREAD

**Issue by nirmalpavan** [Azure/azure-powershell#6808]
HI All

Getting below error while trying login azure subscription using powershell. PLease help.

Login-AzureRmAccount : The browser based authentication dialog failed to complete. Reason: The server or proxy was not found.

**Comment by markcowl** [comment]
@nirmalpavan This normally indicates a browser or firewall configuration issue on your machine, can you please provide the folliwng information to help us diagnose:

```powershell
Get-Module -ListAvailable
```

Then set your powershell session to provide additional debugging information, using:
```powershell
$DebugPereference="Continue"
```
and then run your login command again.

**Comment by maddieclayton** [comment]
@nirmalpavan Ping on the questions above.

**Comment by maddieclayton** [comment]
Closing as no response.  @nirmalpavan If you are still seeing this issue feel free to reopen with the information requested above.
