### ISSUE TITLE
Get-AzureRmApiManagementApi doesn't work as expected

### ISSUE THREAD

**Issue by BenyChernyak1** [Azure/azure-powershell#6814]
### Description

Hello,

We have upgraded Azure RM PowerShell version to 6.5.0 on one of deploy machines and now I'm facing unexpected behavior with cmdlet above.
I'm specifying API name that I'd like to get a description for:
$apiDesc = Get-AzureRmApiManagementApi -Context $apiMgmtContext -Name 'Spotlight-Entitlement-Service' -ErrorAction SilentlyContinue
where
$apiMgmtContext = New-AzureRmApiManagementContext -ResourceGroupName 'RG-SPOT-APIM-DEV-EUS1' -ServiceName 'apim-spot-dev-eus1'
And I get an array of size 2:
1) Details API named 'Spotlight-Entitlement-Service' - as expected
2) Details API named 'Entitlement-Service' - that's why?
First, those two services are different. Second, I've explicitly set an API name in Get-AzureRmApiManagementApi cmdlet.
So why it responses with details of both services?

P.S. With Azure RM PowerShell version 5 this doesn't happen.

### Script/Steps for Reproduction

See above.

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.5.0      AzureRM
```

### Environment Data

```powershell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.492
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.492
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```

```

**Comment by solankisamir** [comment]
Yes, during a recent change we changed the ODATA filter from `eq` to `contains`, which is causing this behavior change. Change [here](https://github.com/Azure/azure-powershell/commit/16bd80d7e53135de6744c57563a08fc169567c18#diff-72bf21c9cbd6229758d241b15cb6a595L334). 
Need to understand why Contains of full name returns results which don't match the full pattern.

**Comment by solankisamir** [comment]
The order of parameter in Contains was incorrect. Will need to fix that. Expect the fix out in a month.

**Comment by solankisamir** [comment]
This is fixed in 
https://github.com/Azure/azure-powershell/releases/tag/v6.8.0-August2018
https://www.powershellgallery.com/packages/AzureRM/6.8.0
