### ISSUE TITLE
Set-AzureRmResource fails for batch with pipelineineput

### ISSUE THREAD

**Issue by martgras** [Azure/azure-powershell#6834]
### Description

Get-AzureRmResource  | Set-AzureRmResource   ... fails with for batch with 
InvalidRequestBody : The specified Request Body is not syntactically valid.

I have only tested with a batch account but this probably affects all other resources where Date/Time types are used

### Script/Steps for Reproduction

Set your locale to Germany (date / time format)

```powershell
$r=Get-AzureRmResource -ResourceId "/subscriptions/1111111-e00d-485d-b654-7078bdeea839/resourceGroups/userbatch-rg/providers/Microsoft.Batch/batchAccounts/mguserbatch"
 $r |Set-AzureRmResource -Tag @{'testtag'='123'}  -force
Set-AzureRmResource : InvalidRequestBody : The specified Request Body is not syntactically valid.
RequestId:4ac19ca4-1ab9-4a51-92ef-251af06988f4
Time:2018-08-02T13:32:41.8875426Z
At line:1 char:5
+ $r |Set-AzureRmResource -Tag @{'testtag'='123'}  -force
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : InvalidRequestBody,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet
 
```
everything works if I use 
```powershell
$r=Get-AzureRmResource -ResourceId "/subscriptions/1111111-e00d-485d-b654-7078bdeea839/resourceGroups/userbatch-rg/providers/Microsoft.Batch/batchAccounts/mguserbatch"
Set-AzureRmResource -Tag @{'testtag'='123'}  - -ResourceId $r. -ResourceId -force
````

### Module Version

```powershell
ModuleType Version    Name                                ExportedCommands                                                                                                               
---------- -------    ----                                ----------------                                                                                                               
Script     6.6.0      AzureRM                                                                                                                                                            
Script     6.3.0      AzureRM                                                                                                                                                            

```

### Environment Data

```powershell
$PSVersionTable

Name                           Value                                                                                                                                                     
----                           -----                                                                                                                                                     
PSVersion                      5.1.17134.165                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                   
BuildVersion                   10.0.17134.165                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                       
SerializationVersion           1.1.0.1  
```

### Debug Output

The reason for the error is that lastKeySync is formated using locale settings instread of the ISO format
 "2017-07-22T22:59:38.4979036Z" would work. 

(

```
...
    "autoStorage": {
      "lastKeySync": "22.07.2017 22:59:38"
...
{
    "error": {
        "code": "InvalidRequestBody",
        "message": "The specified Request Body is not syntactically valid.\nRequestId:fbd4ebf6-d5f0-42ea-9e1a-9c3f68595520\nTime:2018-08-02T13:26:32.6990520Z",
        "target": "BatchAccount",
        "details": [
            {
                "code": "Reason",
                "message": "properties.autoStorage.lastKeySync: The supplied value is invalid for Account."
            }
        ]
    }
}
```

**Comment by cormacpayne** [comment]
@martgras Hey Martin, thanks for reporting this. It appears that this is a bug in how `Set-AzureRmResource` accepts pipeline input. Here's what I found:

The [`ShouldUsePatchSemantics`](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Resource/SetAzureResourceCmdlet.cs#L223-L229) method is the difference between the two methods you provided above -- in the case where no pipeline input is used, this method returns true, and `PATCH` semantics are used in the request, and if there is pipeline input, this method returns false and `PUT` semantics are used. It seems that when a `PUT` request is sent that the body is formatted incorrectly and gives the above failure.

I've tried this with a couple other resources (storage account and key vault) and was unable to reproduce this error, but was able to reproduce it with a batch account, so it seems to be service specific. @matthchr Hey Matt, do you know if there are restrictions on what can be provided for the `PUT` request on a batch account? (_i.e._, are `null` values acceptable for properties such as `Kind`, `Plan`, `Sku`, etc.?)

We should be able to resolve this issue (it stems from which parameters are being populated during the piping) in the new `Az` module that will GA at our Ignite release (September 24th), and we can look at making this change in our next breaking change release for `AzureRM` (November).

**Comment by kiwidev** [comment]
As mentioned by @matthchr, this value is ignored by Batch RP but is required to be a valid ISO datetime value if specified.

Note that this behavior is similar to the behavior of managed disks (Microsoft.Compute/disks) which returns a similar error message if `timeCreated` property is specified in an invalid locale.
