### ISSUE TITLE
Set-AzureAvailabilitySet missing for ARM

### ISSUE THREAD

**Issue by wasabii** [Azure/azure-powershell#684]
Unsure how to accomplish a change of AvailabilitySet on a VM. Set-AzureAvailabilitySet existed on classic resources. I see no similar thing now.

**Comment by huangpf** [comment]
I'm not sure you can update AVSet ID after the VM is created. @singhkay to help confirm the feature.

**Comment by singhkay** [comment]
Hi @wasabii, this capability is not yet available in the platform.

**Comment by ashishthaps** [comment]
Is there a way to achieve this? I need to associate existing VM's to an availability set
