### ISSUE TITLE
Unable to catch exception thrown by Import-AzureRmApiManagementApi

### ISSUE THREAD

**Issue by BenyChernyak1** [Azure/azure-powershell#6852]
### Description

I'm using this cmdlet:
try{
$result = Import-AzureRmApiManagementApi -Context $apiMgmtContext -SpecificationFormat "Swagger" -SpecificationPath $swaggerFileNameTemp -ApiId $apiId -Path $apiPrefix -Verbose
...
}
catch{
Write-Error "Unable to import API to APIM: $($_.Exception.Message)."
}
Command fails with the following exception:
Import-AzureRmApiManagementApi : Operation returned an invalid status code 'BadRequest'
At C:\GIT\SpotlightCloud-APIManagement\Infra\modules\APIM-Module.psm1:951 char:19
+ ...   $result = Import-AzureRmApiManagementApi -Context $apiMgmtContext - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Import-AzureRmApiManagementApi], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.ImportAzureApiManagementApi

And it isn't caught in a catch block. I would like to catch any exception thrown by this cmdlet and stop my script if there is any.

### Script/Steps for Reproduction

See above.

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.5.0      AzureRM
```

### Environment Data

```powershell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.492
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.492
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```

```

**Comment by maddieclayton** [comment]
Closing as no response. @BenyChernyak1 If you are still seeing this issue feel free to reopen with the information requested above.
