### ISSUE TITLE
Get-AzureRmApiManagementProduct doesn't work as expected

### ISSUE THREAD

**Issue by BenyChernyak1** [Azure/azure-powershell#6853]
### Description

The Issue is similar to #6814:
Taking to consideration we have 2 products in APIM:
1.	Spotlight-APIM-Playground-Open
2.	Spotlight-APIM-Playground-Open-Public
The following command:
$productDesc = Get-AzureRmApiManagementProduct -Context $apiMgmtContext -Title “Spotlight-APIM-Playground-Open-Public”
Should return #2 only. But currently it return both, which is wrong.
P.S. With Azure RM PowerShell version 5 this doesn't happen.

### Script/Steps for Reproduction

See above.

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.5.0      AzureRM
```

### Environment Data

```powershell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.492
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.492
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```

```

**Comment by markcowl** [comment]
@BenyChernyak1 Can you please provide the debug output for this call, so we can see the request and response with ARM?

To do this, set debug preference to 'Continue':

```powershell
$DebugPreference="Continue"
```

then execute the cmdlet that is causing the problem:

```powershell
Get-AzureRmApiManagementProduct -Context $apiMgmtContext -Title “Spotlight-APIM-Playground-Open-Public”
```

This will give us additional information to diagnose the precise problem.

**Comment by markcowl** [comment]
@solankisamir Samir, can you take a look?

**Comment by BenyChernyak1** [comment]
@markcowl please refer to #6814, this is a same one.

**Comment by solankisamir** [comment]
I am working on the fix. Plan to push out in the next update.

**Comment by solankisamir** [comment]
This is fixed in 
https://github.com/Azure/azure-powershell/releases/tag/v6.8.0-August2018
https://www.powershellgallery.com/packages/AzureRM/6.8.0
