### ISSUE TITLE
Enable Compute.ManagedService test

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#6858]
Currently there is one test in the Compute.ManagedService test suite, but it is not running as a part of the current on-demand build:

- ManagedComputeServicesTests.VhdTests.TestVhd

This test is failing with the following error:

```
Cannot find VM 'testNonExistingVM' from server 'localhost'
```

The work needs to be done to enable this test on any machine, and then the test assembly should be referenced in [`TestMappings.json`](https://github.com/Azure/azure-powershell/blob/preview/TestMappings.json#L82) file (unless this file has already been removed in PR https://github.com/Azure/azure-powershell/pull/6675).

**Comment by maddieclayton** [comment]
We aren't shipping this in Az, so we no longer need to worry about the test.
