### ISSUE TITLE
[Azure Stack] [Admin] Get-AzsVMExtension does not return all useful information

### ISSUE THREAD

**Issue by JeffGoldner** [Azure/azure-powershell#6869]
The most important information for extensions is PublisherName, Type and Version (and arguably OsType). When you add an extension, you must provide this information but when you do a Get, you don't get most of those fields back. Instead, you get something called Type which has no useful information.

Compare to Get-AzureRmVMExtension.

PS C:\AzureStack-Tools-master> Get-AzsVMExtension

VmOsType                  : Windows
ComputeRole               : IaaS
VmScaleSetEnabled         : False
SupportMultipleExtensions : False
IsSystemExtension         : False
SourceBlob                : 
ProvisioningState         : Succeeded
Id                        : /subscriptions/1d4fdbde-1445-48b8-979b-8183fa5a2c1f/providers/Microsoft.Compute.Admin/locations/redmond/artifactTypes/VMExtension/publishers/Microsoft.Compute/types/BGInfo/versions/2.2.1.0
Name                      : 
Type                      : Microsoft.Compute.Admin/locations/artifactTypes/VMExtension/publishers/types/versions/
Location                  : redmond

Type is missing all information and is identical (and wrong) for every extension
Type                      : Microsoft.Compute.Admin/locations/artifactTypes/VMExtension/publishers/types/versions/ 

AzureRm knows the Type, Version and PublisherName which are the essential pieces of information:
PS C:\AzureStack-Tools-master> Get-AzureRmVmImagePublisher -Location redmond | `
Get-AzureRmVMExtensionImageType | `
Get-AzureRmVMExtensionImage | ft Type, Version, PublisherName -AutoSize

Type                     Version        PublisherName                       
----                     -------        -------------                       
BGInfo                   2.2.1.0        Microsoft.Compute                   
BGInfo                   2.1            Microsoft.Compute                   
CustomScriptExtension    1.9.1          Microsoft.Compute                   
CustomScriptExtension    1.8            Microsoft.Compute                   
VMAccessAgent            2.4.4          Microsoft.Compute                   
VMAccessAgent            2.0            Microsoft.Compute                   
JsonADDomainExtension    1.3.2          Microsoft.Compute                   
JsonADDomainExtension    1.3            Microsoft.Compute                   
SqlIaaSAgent             1.2.29.0       Microsoft.SqlServer.Management      
SqlIaaSAgent             1.2.30.0       Microsoft.SqlServer.Management      
CustomScriptForLinux     1.5.2.1        Microsoft.OSTCExtensions            
CustomScriptForLinux     1.5.2.2        Microsoft.OSTCExtensions            
CustomScriptForLinux     1.5.2.0        Microsoft.OSTCExtensions            
VMAccessForLinux         1.4.7.1        Microsoft.OSTCExtensions            
VMAccessForLinux         1.4.0.0        Microsoft.OSTCExtensions            
OSPatchingForLinux       2.3.0.1        Microsoft.OSTCExtensions            
CustomScript             2.0.6          Microsoft.Azure.Extensions          
DockerExtension          1.1.1606092330 Microsoft.Azure.Extensions          
LinuxDiagnostic          3.0.113        Microsoft.Azure.Diagnostics         
IaaSDiagnostics          1.11.3.12      Microsoft.Azure.Diagnostics         
IaaSDiagnostics          1.10.1.1       Microsoft.Azure.Diagnostics         
MicrosoftMonitoringAgent 1.0.11081.4    Microsoft.EnterpriseCloud.Monitoring
MicrosoftMonitoringAgent 1.0.10900.0    Microsoft.EnterpriseCloud.Monitoring
DSC                      2.76.0.0       Microsoft.Powershell                
DSC                      2.19.0.0       Microsoft.Powershell                
IaaSAntimalware          1.5.5.1        Microsoft.Azure.Security            
IaaSAntimalware          1.4.0.0        Microsoft.Azure.Security

**Comment by deathly809** [comment]
The PR #7065 has this fix.
