### ISSUE TITLE
Rename Get-AzsManagedOffer and Get-AzsOffer cmdlets

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#6870]
Get-AzsManagedOffer - This cmdlet is supposed to be used by Admins. The *managed* naming was selected in the thought process of using a common cmdlet for Admins and Resellers(CSPs). Rightnow this is being targeted only for Admins

Get-AzsOffer
This is a user facing cmdlet to get the public offers. This is not a admin facing cmdlet

The confusion arises as we call admin facing offer creation cmdlets simply as  New-AzsOffer, Set-AzsOffer, Remove-AzsOffer. The *managed* wording is being used only in the admin facing Get-AzsManagedOffer. Get-AzsOffer is for users..

We need a proper naming on these cmdlets to remove the confusion. Suggestions are welcome

**Comment by deathly809** [comment]
@vlad-MSFT You have any input as you own this.

**Comment by vlad-MSFT** [comment]
Maybe just cal it AzsAdminOffer? Managed means something else.
Also, do we really need to expose user offers via PS? I kind of dislike that we have that API since it allows people to self-sign-up, which I think should never be done in prod or programatically, There is not much users can do with the offer on the User ARM side.

**Comment by vlad-MSFT** [comment]
"Public" terminology is also problematic, as offers can be "public" and "private". I think the only api we need to keep is the admin API and remove any PS support from creating subscriptions and listing offers from User-ARM

**Comment by deathly809** [comment]
Fixed with PR https://github.com/Azure/azure-powershell/pull/7076

**Comment by bganapa** [comment]
Closing this here, This is being tracked internally with a vsts bug
