### ISSUE TITLE
Documentation for AzureRmPolicyAssignment has no -Scope examples other then RG's

### ISSUE THREAD

**Issue by gcormier** [Azure/azure-powershell#6880]
Documentation does not provide any examples for setting scope at a Subscription level as in the portal. It took a bit of searching to figure out it takes a string of "/subscription/(id)"

**Comment by gcormier** [comment]
I didn't seem to be able to avoid adding scope. Was mandatory and couldn't proceed without.

**Comment by markcowl** [comment]
@Tiano2017 please take a look

**Comment by robga** [comment]
Added an example of creating policy assignment at subscription level to the doc: 
https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azpolicyassignment
I have a backlog work item to make the scope parameter be optional when creating policy assignment at the subscription level. I will update the doc again when that work is done.
