### ISSUE TITLE
[AzureRm.Aks] is not included in AzureRm-6.6.0

### ISSUE THREAD

**Issue by m-moris** [Azure/azure-powershell#6886]
Is AzueRm.Aks included in AzureRm-6.6.0? It does not seem to be included.
However, it is included in AzureRM.Netcore-0.13.1.

**Comment by markcowl** [comment]
@m-moris Right now the AKS module is still in preview, and this means it cannot be included as a depednency in any module.  We should likely expedite moving this module out of preview so it can be included.

Note that, the NetCore version of this module is part of the AzureRM.Netcore package.

**Comment by markcowl** [comment]
Closing in favor of #6959 which covers all modules outside AzureRM
