### ISSUE TITLE
ARM VM Image commands are complicated and slow

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#691]
# Symptom

In the Azure Service Management (ASM) PowerShell module, I could simply call `Get-AzureVMImage`, and receive a list of the images available in the image gallery.

In the Azure Resource Manager (ARM) PowerShell module, a user must call no fewer than 4 separate commands to retrieve a publisher --> sku --> offer --> then finally, the "image details." This is not a user-friendly interface, especially relative to the ASM PowerShell module.

![image](https://cloud.githubusercontent.com/assets/466713/9053636/db2000a4-3a34-11e5-919a-f6aecbcbb68c.png)
# Expected Result

The `Get-AzureVMImage` command in the ARM PowerShell module should return a comprehensive list of images in the image gallery, without requiring the user to go through onerous steps to filter the gallery using confusing terminology that isn't well documented.
# Proposed Solution

The image gallery should be exposed with a single REST method, and enable input parameters to perform server-side filtration of the data set, prior to returning it to the client. If this cannot be achieved, then the PowerShell module should abstract the REST API from the module consumer.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by Injac** [comment]
+1 For this proposal.

**Comment by rajinders** [comment]
+1 For this proposal

**Comment by singhkay** [comment]
@pcgeek86 @Injac @rajinders @trondhindenes The gallery team is aware of this. One of the things they are looking for feedback is on example usage scenarios so that the REST APIs actually support those things. It'd be great if you could share examples of how you'd expect to discover platform and user images from the Get-AzureVMImage cmdlet.

**Comment by pcgeek86** [comment]
```powershell
### Get all VM images where the publisher name contains "micr"
Get-AzureVMImage -Publisher *micr*;

### Get all images that have an Operating System matching 'Wind*Server'
Get-AzureVMImage -OperatingSystem 'Wind*Server';

### Get all Linux VM images
Get-AzureVMImage -Class Linux;

### Get all CentOS images
Get-AzureVMImage -OperatingSystem CentOS;

```

Need more examples?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by trondhindenes** [comment]
I can only +999 what Trevor said. The gallery rest api is currently built as a hierachical api, when it should have been a search api.

**Comment by singhkay** [comment]
@pcgeek86 Thanks Trevor, this is good. Do you still expect the Get-AzureVMImage without any parameters to return all the images in the gallery (could be in thousands and increases as the platform/partners grow) ?

How about user image gallery. Do you expect a -User flag on all the above options to only search user's image gallery?

**Comment by pcgeek86** [comment]
@singhkay An alternative would be to use a `-ListAvailable` switch parameter, which can easily be tab-completed, and doesn't require much typing.

As far as user images: absolutely. A `-User` switch parameter would be great. VM images have a lot of metadata, so choosing the most common criteria that customers will want to filter on might be hard. I can appreciate that, but that is what parameter sets can be used for.

Another use case is filtering by `PublishedDate`.

```powershell
# -MaximumAge parameter would be in days, but probably isn't a good parameter name. You get the idea though.
Get-AzureVMImage -MaximumAge 10;

Get-AzureVMImage -Publisher Microsoft -MaximumAge 10;
```

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by singhkay** [comment]
@pcgeek86 How about -Latest flag to get the latest image if timerange on the API can't be implemented?

**Comment by pcgeek86** [comment]
@singhkay Sure, build some pagination into the API. Good idea. Might want to let the user specify the data page size though [optionally]. FYI the `-ListAvailable` parameter is a precedent, set by PowerShell core's `Get-Module` command. However, I do like `-Latest`.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by slapointe** [comment]
I agree with most of all in here, I love parameterSets, we just need to find a good balance when there is a lot of them...

```powershell

Get-AzureVMImage -Location 'East US' # Would return a paged list of all vm image detail versions (all versions of a sku) // This one has the potential of having a LOT of items, 

Get-AzureVMImage -Location 'East US' -LatestOnly # Would return a paged list of vm image detail (only one per sku, the latest version)

Get-AzureVMImage -Location 'East US' -Publisher Microsoft* -Offer VisualStudio -Sku VS-2013* -Latest # Would return the latest image details for Visual Studio 2013 skus

Get-AzureVMImage -Location 'East US' -Publisher Microsoft* -Offer VisualStudio -Sku *2013* # Would return all image details for Visual Studio 2013 offers

Get-AzureVMImage -Location 'East US' -User # Would return all image details in custom images

Get-AzureVMImage -Location 'East US' -User -Latest # Would return the latest image details in custom images

```

and for paging
```powershell
$pagedResults = Get-AzureVMImage -Location 'East US' -Latest # would return a page of XXX by default
$pagedResults2 = $pagedResults | Get-AzureVMImage -NextPage

# paged result objects could have a search token (that GetAzureVMImage could extract automatically) and the cmdlet would fetch the next page of results.
```

It is mostly aligned with what have been previously proposed. What do you think?

**Comment by pcgeek86** [comment]
@slapointe Great idea, with the -NextPage parameter. FYI, when talking about data paging, PowerShell has built-in support for paging, since version 3.0. Documentation is extremely limited, if not completely non-existent, but someone posted an example of how to implement paging here: 

https://github.com/uri247/Win81Desktop/tree/master/Windows%20PowerShell%20Supports%20Paging%2001%20Sample/C%23

Cheers,
Trevor Sullivan

**Comment by pcgeek86** [comment]
@singhkay @devigned @markcowl @trondhindenes @slapointe How are we looking for getting this resolved? I haven't seen any action in the past few months.

Furthermore, I discovered a similar, glaring design flaw in the Azure VM Extension API (see screenshot).

<img width="793" alt="screen shot 2015-12-02 at 1 13 14 pm" src="https://cloud.githubusercontent.com/assets/466713/11544586/7e206908-98f7-11e5-9420-f9c884ef08a6.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by MattAllison** [comment]
I know this issue/request has been open for a while but I wanted to reiterate the request.

We are currently in the process of updating our management scripts for ARM and the way that the ARM image functions work has increased the amount of work and training substantially.

In the past, we could "simply" search for an OS image label (e.g. "Windows Server 2012 R2*") and then look at the resulting set to know two things - what is the operating system (e.g. Windows or Linux) and what is the latest version.

With the new model, we need to have an additional parameter for what the underlying OS actually is (e.g. "-Windows" or "-Linux" but track the PublisherName and Offer as well.   Surely we can hard-code these values into the script and probably will but that results in the options of "make code harder to maintain" or "make it harder for administrators to be successful".

**Comment by twitchax** [comment]
@singhkays, has your team had a chance to take a look at this?

**Comment by singhkays** [comment]
Hey @twitchax, I haven't owned this area in a while. Adding @kmouss who owns images. He'll know if there are any improvements planned.

**Comment by twitchax** [comment]
Thanks, @singhkays.

**Comment by cormacpayne** [comment]
@kmouss ping

**Comment by Drewm3** [comment]
Closing out this older issue due to inactivity. Please use https://feedback.azure.com/forums/216843-virtual-machines in the future  because we can better track longer running feature requests.
