### ISSUE TITLE
Get incorrect api-version value for LogicApp Trigger CallbackUrl through powershell command

### ISSUE THREAD

**Issue by ToMakeSense** [Azure/azure-powershell#6913]
Through powershell command [Get-AzureRmLogicAppTriggerCallbackUrl](https://docs.microsoft.com/en-us/powershell/module/azurerm.logicapp/get-azurermlogicapptriggercallbackurl), I will get an URL like:
[https://prod-50.westeurope.logic.azure.com:443/workflows/XXXXXXXXXXXXXX/triggers/manual/paths/invoke?api-version=**2016-06-01**&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=XXXXXXXXXXXXX]()

but check it in the azure portal, the URL is:
[https://prod-50.westeurope.logic.azure.com:443/workflows/XXXXXXXXXXXXXX/triggers/manual/paths/invoke?api-version=**2016-10-01**&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=XXXXXXXXXXXXX]()

That is to say, through powershell, the value of api-version is **2016-06-01**, but the actual value is  **2016-10-01** via azure portal

**Comment by maddieclayton** [comment]
@pankajsn @daviburg Can you take a look at this issue?

**Comment by ToMakeSense** [comment]
Same issues still exists in AZ PowerShell 1.4.0 [Get-AzLogicAppTriggerCallbackUrl](https://docs.microsoft.com/en-us/powershell/module/az.logicapp/Get-AzLogicAppTriggerCallbackUrl?view=azps-1.4.0)

And I think the template version for logic app needs to be added( only version 2016-06-01 is listed in below links).
[Microsoft.Logic workflows template reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.logic/2016-06-01/workflows)
![image](https://user-images.githubusercontent.com/6244148/53791589-c079d480-3f64-11e9-95e5-bea4629876f0.png)

**Comment by maddieclayton** [comment]
@refortie Can you take a look at this issue?

**Comment by refortie** [comment]
So I'm not sure what the issue is here. The version in the response for the callback URL is tied to the API version used to call the endpoint. So in the Portal the 2016-10-01 API version is being used, whereas the SDK/PowerShell cmdlet is using 2016-06-01 version.

**Comment by ToMakeSense** [comment]
@refortie  thanks for your reply. In my option, the  API version should be the same whatever tools is used to get it.

**Comment by ToMakeSense** [comment]
similar question https://github.com/Azure/azure-powershell/issues/6913
