### ISSUE TITLE
Azure Powershell does not allow selection of a subscription recently migrated to another tenant 

### ISSUE THREAD

**Issue by laughtonsm** [Azure/azure-powershell#6923]
### Description

After migrating a subscription to another tenant, I was unable to use Azure Powershell to select the subscription for management (`Select-AzureRmSubscription -Subscription <subscriptionName>`)

### Script/Steps for Reproduction

![2018-08-13_16-36-30](https://user-images.githubusercontent.com/18421849/44083360-ad636d56-9fab-11e8-9255-66d77eacd101.png)

This occurs whether I am selecting using a Subscription ID, Name or object

### Module Version
Issue relates to releases 6.4 and 6.6 (The issue exists in both of these versions.)  Downgrading to version 5.7 allowed me to select the subscription, so was an adequate work around.

**Comment by maddieclayton** [comment]
I am not able to replicate this issue.  I did wait for the change to propagate (kept checking the output of Get-AzureRmSubscription until the tenant change), which did take a bit of time after the portal had claimed that the tenant had been updated.  Can you confirm that you waited until the change had propagated? Also, can you add the output of Select-AzureRmSubscription with the -Debug flag, as well as the output of running Resolve-Error (if there is any output).

**Comment by markcowl** [comment]
Closing as no repro.  If you are still seeing this issue and can provide the addiitonal information requested, please reopen or file a new issue.
