### ISSUE TITLE
Set-AzureRmWebAppSlot -AppServicePlan does nothing if WebAppSlots are piped

### ISSUE THREAD

**Issue by Suchiman** [Azure/azure-powershell#6924]
### Description

When piping web app Slots from Get-AzureRmWebAppSlot to Set-AzureRmWebAppSlot, then attempting to modify the AppServicePlan does nothing (the WebAppSlot summary is printed but the AppServicePlan stays the same). If you try to manipulate the AppServicePlan directly through Set-AzureRmWebAppSlot, it works. The usecase is batch migrating web apps and their slots to different app service plans. This is on Azure Germany.

### Script/Steps for Reproduction
Does nothing:
```powershell
Get-AzureRmWebAppSlot -Name $name -Slot $slot -ResourceGroupName $resourceGroup | Set-AzureRmWebAppSlot -AppServicePlan $newPlan
```
Works:
```powershell
Set-AzureRmWebAppSlot -Name $name -Slot $slot -ResourceGroupName $resourceGroup -AppServicePlan $newPlan
```

### Module Version

```powershell
    Verzeichnis: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.6.0      AzureRM
```

### Environment Data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.17134.165
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.165
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

I'd prefer not to paste 3300 lines containing sensitive data public on GitHub.

**Comment by maddieclayton** [comment]
@panchagnula Can you take a look at this issue?

**Comment by panchagnula** [comment]
Closing this since this an old bug & should now be fixed.
