### ISSUE TITLE
Issue with replacing New-AzureADApplication to New-AzureRmADApplication 

### ISSUE THREAD

**Issue by NehaJantre** [Azure/azure-powershell#6926]
Hi,
I am replacing New-AzureADApplication with New-AzureRmADApplication but the 3 parameters present in New-AzureADApplication are not there in New-AzureRmADApplication(-Oauth2AllowImplicitFlow, -RequiredResourceAccess, -PublicClient). Are there any equivalent paraments similar to these with different names available for New-AzureRmADApplication? 

New-AzureADApplication  	-DisplayName $abc`
						-HomePage $Url `
						-IdentifierUris https://xxx.yyy.com/$ab" 
                                                -AvailableToOtherTenants $true `
						-Oauth2AllowImplicitFlow $true `
						-ReplyUrls $Url 1`
						-RequiredResourceAccess $azureADApiRequiredResourceAccess, `  														 
                                                                                           $graphApiRequiredResourceAccess `
						-PublicClient $false

New-AzureRmADApplication  -DisplayName $abc `
						-HomePage $Url `
						-IdentifierUris https://xxx.yyy.com/$abcd" 
						-AvailableToOtherTenants $true `
						-ReplyUrls $Url1

**Comment by MiYanni** [comment]
@nehaj910 Can you link to that discussion from the Azure AD team? We don't haven't heard any information about that.

**Comment by nehaj910** [comment]
@MiYanni @psignoret I tried looking for the github issue where I read that. But I could not find the original issue where I read it. So here is a similar link where others seem to have heard it as well. I would like to confirm from you if that is true. https://github.com/MicrosoftDocs/azure-docs/issues/12391
