### ISSUE TITLE
ARM: No way to pass in an SSH key for Linux VM in Set-AzureVMOperatingSystem

### ISSUE THREAD

**Issue by brharr** [Azure/azure-powershell#693]
Currently the above command accepts a PSCredential which only works when you are using a username and password. However, with Linux machines, that is not the most secure practice. SSH keys are what should be used, but there is no way to pass an SSH key using the Get-Credential cmdlet, nor is there a parameter to make this happen within the New-AzureVM or Set-AzureVMOperatingSystem when the Linux flag is set.

Brian

**Comment by singhkay** [comment]
@brharr Have you looked at the Add-AzureVMSshPublicKey cmdlet?

**Comment by singhkay** [comment]
Closing for now, feel free to reopen if the above cmdlet doesn't serve your purpose.
