### ISSUE TITLE
Convert and execute non-Core test projects

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6931]
### Description
Convert test projects in the order below
- Required for v1
  - [x] Cdn
  - [x] CognitiveServices
  - [x] Dns
  - [x] MachineLearning
  - [x] MachineLearningCompute
  - [x] ServiceBus
  - [x] ServiceFabric
  - [x] TrafficManager

### Cost: 10

- Required for October
  - [x] ApplicationInsights
  - [x] AnalysisServices
  - [x] Billing
  - [x] Consumption
  - [x] ContainerInstance
  - [x] ContainerRegistry
  - [x] DataLakeAnalytics
  - [x] DataLakeStore
  - [x] EventGrid
  - [x] EventHub
  - [x] IoTHub
  - [x] Media
  - [x] NotificationHubs
  - [x] PowerBIEmbedded
  - [x] RedisCache
  - [x] Relay
  - [x] StreamAnalytics

### Cost: 20

- Required Before Deprecation
  - [ ] ~~DataFactories~~ Awaiting: https://github.com/Azure/azure-powershell/issues/6161
  - [ ] ~~DataFactoryV2~~ Awaiting: https://github.com/Azure/azure-powershell/issues/6161
  - [ ] ~~HDInsight~~ Awaiting: https://github.com/Azure/azure-powershell/issues/6085
  - [x] LogicApp
  - [x] OperationalInsights
  - [x] MarketplaceOrdering
  - [x] RecoveryServices
  - [ ] ~~Scheduler~~ Awaiting: https://github.com/Azure/azure-powershell/issues/6085

### Cost: 10

**Comment by MiYanni** [comment]
All PRs have been merged.
