### ISSUE TITLE
Set up additional build machines for NetCore sign builds

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6933]
### Description

- [x] Modify current signing machine label to build netcore
  - [x] VS2017
  - [ ] NetCore SDK 2.1
- [x] Ramp up 3 machines using the new worker
- [x] Assign to the NetCoreSigning job

### Cost: 6

**Comment by praries880** [comment]
Done... created a new CI infra one note page with instructions on how to create a worker with the new image.
