### ISSUE TITLE
ARM:Set-AzureDataDisk is missing

### ISSUE THREAD

**Issue by rajinders** [Azure/azure-powershell#694]
I had created a DS4 Virtual Machine with 1 data disk. I wanted to change caching property for the datadisk.

This property can be found at storageProfile.dataDisks.caching
The only way to do this is to first remove the data disk with Remove-AzureVMDataDisk and Add-AzureVMDataDisk with new caching setting.

This seems cumbersome.
So I am requesting Set-AzureDataDisk cmdlet which can be used to update the properties of an existing data disk.

**Comment by pcgeek86** [comment]
+1

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by singhkay** [comment]
@rajinders @pcgeek86 Thanks guys, I've created a feature request for our dev team.

**Comment by singhkay** [comment]
This cmdlet is released now :)
