### ISSUE TITLE
Use of PSDefaultParameters with the AzureRM module

### ISSUE THREAD

**Issue by wsmelton** [Azure/azure-powershell#6941]
### Description

My PSDefaultParameters are not being honored with the AzureRm module because the module itself is setting the values. So in the end none of them get used and I have lost the ability to utilize the shortcut in PowerShell itself.

### Script/Steps for Reproduction

Set this in your profile:
```powershell
$PSDefaultParameterValues = @{
	"*:ResourceGroupName"='mygroup'
}
```

Import the module and then issue any command that utilizes that parameter. You are presented with this warning:

> WARNING: Multiple different default values are defined in $PSDefaultParameterValues for the parameter matching the following name or alias: ResourceGroupName. These defaults have been ignored.

I also find it odd (borderline annoying) that you are also clearing the default parameters upon import of every module within AzureRm, all the child modules have the following line at the start of their psm1 files: `$PSDefaultParameterValues.Clear()`.

### Module Version

```powershell
6.6.0
```

### Environment Data

```powershell

Name                           Value                                                                                  
----                           -----                                                                                  
PSVersion                      5.1.17134.165                                                                          
PSEdition                      Desktop                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                
BuildVersion                   10.0.17134.165                                                                         
CLRVersion                     4.0.30319.42000                                                                        
WSManStackVersion              3.0                                                                                    
PSRemotingProtocolVersion      2.3                                                                                    
SerializationVersion           1.1.0.1                                                                                
```

**Comment by maddieclayton** [comment]
@wsmelton The $PSDefaultParameterValues.Clear() at the beginning of each psm1 only clears for the scope of the script.  This ensures that no default parameter values are set for the commands run in the script.  I'm brainstorming a solution for the actual issue with ResourceGroupName.  Is there a reason that you don't want to use Set-AzureRmDefault?  I will still be working on a fix as this is not the behavior we want, but curious about whether there is missing functionality in that cmdlet.

**Comment by wsmelton** [comment]
Scope of the script is not the result you get when you import. It is clearing every default parameter I set in my sessions. Even ones I use with my docker containers...I lose any default I setup.

**Comment by wsmelton** [comment]
The parameter is not scoped to just scripts it is indeed session wide. Where is your source that it is scoped to the script itself?

**Comment by maddieclayton** [comment]
This is what I ran (with outputs):
```
PS C:\Users\maclayto> $PSDefaultParameterValues["yes:yes"] = "no"
PS C:\Users\maclayto> $PSDefaultParameterValues

Name                           Value
----                           -----
yes:yes                        no


PS C:\Users\maclayto> import-module AzureRM.DataMigration
PS C:\Users\maclayto> $PSDefaultParameterValues

Name                           Value
----                           -----
New-AzureRmDataMigrationSer... ...
yes:yes                        no
```

**Comment by maddieclayton** [comment]
Ah, makes sense.  Do you have any comments on the Set-AzureRmDefault cmdlet: https://docs.microsoft.com/en-us/powershell/module/azurerm.profile/set-azurermdefault?view=azurermps-6.7.0?

**Comment by wsmelton** [comment]
I guess that command is the same effect, but a bit annoying to have to use that for just ResourceGroupName and be able to use PSDefaultParmeters for everything else.

I do projects for various clients and constantly update the values I set in my profile to the current project I'm working on. I tend to set a handful of parameters and not just ResourceGroupName. (e.g. AutomationAccount, Subscription, Location, Tags). 

I prefer to use the built in methods that PowerShell offers for setting default parameters because it works across any module or project I am working on.

**Comment by maddieclayton** [comment]
Got it.  In the future we will look at adding more default values to that cmdlet, but makes sense that someone more comfortable with PowerShell would use the built in methods.  I'll look into a solution for this issue (thinking of adding an environment variable to conditionally set the values based on whether the Set-AzureRmDefault has been run, and adding a special case for already imported modules).  I'll update this issues when I have a more solid plan or PR out.

**Comment by maddieclayton** [comment]
@wsmelton Apologies for the long wait, got wrapped up in Ignite related tasks.  I have a proposed fix for this here: https://github.com/Azure/azure-powershell/pull/7332.  Instead of just checking if the exact default parameter value exists, I am now checking to see if there are any default parameter values that would possibly conflict with the one about to be set.  I need to do some additional testing, but this should be included in the October 9th release.

**Comment by maddieclayton** [comment]
Fixed! Will be released 10/9
