### ISSUE TITLE
New-AzureRmRecoveryServicesBackupProtectionPolicy does not allow to set Time Zone

### ISSUE THREAD

**Issue by giovannifl** [Azure/azure-powershell#6944]
### Description

New-AzureRmRecoveryServicesBackupProtectionPolicy should allow to set the time zone that will be applied to a new backup policy when it's created.

According to below ARM template sample, the Time Zone is set at backup policy level, not at retention policy or schedule policy level

https://github.com/Azure/azure-quickstart-templates/blob/master/101-recovery-services-daily-backup-policy-create/azuredeploy.json

Also below blog, confirm that it is not possible to set this value using PowerShell and Azure portal must be used.
https://davidfleming.org/2018/03/30/azure-backup-a-walkthrough/

### Script/Steps for Reproduction

Below cmdlet doesn't allow to set the time zone

```powershell
New-AzureRmRecoveryServicesBackupProtectionPolicy -Name "Test-Bckp-Policy" -WorkloadType AzureVM -BackupManagementType AzureVM -RetentionPolicy $retentionPolicy -SchedulePolicy $schedulePolicy
```

![image](https://user-images.githubusercontent.com/19493042/44176210-e0d56500-a0e0-11e8-926b-b3ee4e9b8f69.png)

### Module Version
6.6.0

Thanks

Giovanni

**Comment by maddieclayton** [comment]
@dragonfly91 Can you take a look at this issue?

**Comment by melonger** [comment]
https://docs.microsoft.com/en-us/previous-versions/windows/embedded/gg154758(v=winembedded.80)

Here's the list and format.

**Comment by constantinhager** [comment]
Any Updates on that. I have the same problem

**Comment by pvrk** [comment]
The following fix is provided 
https://github.com/Azure/azure-powershell/pull/7788
Closing this issue, since the fix is provided.

**Comment by rossarg** [comment]
I'm confused about the listed fix here, as it doesn't seem to incorporate any method to attach a time zone using the New-AzureRmRecoveryServicesBackupProtectionPolicy (or the New-AzRecoveryServicesBackupProtectionPolicy) cmdlets. Documentation shows that we can force the backup schedule to use either the issuing computer's time zone ("$BackupSch.ScheduleRunTimes.Add($Date.ToLocalTime())") or UTC ("$BackupSch.ScheduleRunTimes.Add($Date.ToUniversalTime())"), but not something other than those two.

Local time may suffice in some cases over UTC, but deploying backup policies to regions outside of the issuing computer's time zone means this becomes a multi-step process in issuing the script, then jumping into the Portal to manually change to the desired time zone.
