### ISSUE TITLE
Add-AzureAccount is opening/closing authentiation

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#695]
# Environment

* Windows 10 RTM Build 10240 Enterprise (fresh install from ISO) 
* PowerShell ISE
* Azure PowerShell 0.9.6
* Azure Resource Manager (ARM) mode

# Symptom

The `Add-AzureAccount` command (with no parameters) is occasionally popping open the authentication dialog, but then closing it before I can type my credentials. I am assuming that it's passing through my credentials from Microsoft Edge, since I'm already signed into Microsoft Azure, but it is not giving me the opportunity to specify alternate credentials sometimes.

I'm not sure if I have a 100% repro for this one, but if you:

* Have Microsoft Edge as your default browser on Windows 10
* Are already logged into the Azure Portal
* Your Windows 10 OS is Azure AD joined
* You're logged into Windows 10 with an Azure AD account

... you should be able to repro hopefully.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by devigned** [comment]
via @markcowl 
>This is likely because we are running with auto prompt – if there is an available cookie that contains a previous login (could be a browser login), then this will pick that up.  We attempt to clear cookies before running the cmdlet, so it’s possible clearing cookies was unsuccessful.
 
> If you need to get around this in the interim, clearing cookies in IE should fix the issue.

**Comment by markcowl** [comment]
@pcgeek86 Are you still seeing this?  We updated the authentication library to change the prompting behavior, but there could still be an issue with ASM cmdlets.

**Comment by pcgeek86** [comment]
@markcowl I haven't seen this lately. Will close until further reproduction.
