### ISSUE TITLE
Update Module Canonical names in Az

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6958]
### Description

Make module names logical for Az.* modules

#### Rename
- [x] Az.Profile -> Az.Accounts
- [x] Az.Insights -> Az.Monitor

#### Merge
- [x] Az.Tags -> Az.Resources
- [x] Az.MachineLearningCompute -> Az.MachineLearning
- [x] Az.UsageAggregates -> Az.Billing
- [x] Az.Consumption -> Az.Billing
- [x] Az.DataFactoryV2 -> Az.DataFactory

#### Remove
- [x] Az.Backup
- [x] Az.Scheduler
- [x] Az.Compute.ManagedService

### Cost: 2

**Comment by MiYanni** [comment]
As per discussions with DataFactory folks, they wanted the module to be `Az.DataFactory`. This matches their management SDK name. So, I've moved `DataFactories` to `DataFactoryV2` and renamed `DataFactoryV2` to `DataFactory`.

**Comment by markcowl** [comment]
Fixed
