### ISSUE TITLE
Update Module list for Az

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6959]
### Description

Go through existing modules in AzureRM and for each

- [ ] Determine if it is still a supported service and remove if not
- [ ] Determine if it is using the right canonical name

Go through existing non-RM modules in the repo and for each
- [ ] Determine the GA plans of the service
- [ ]  Determine whether it should be included in Az

- [ ] Publish a lifecycle for module code - when it ships as a preview, when it ships as a non-preview, when it gets in and out of  AzureRM

### Cost: 2

**Comment by MiYanni** [comment]
@markcowl 
Any chance we could also add to this:
- Combine some modules that are logically similar (as long as service teams agree)
  - Ex: `EventGrid` + `EventHub` + `IoTHub`
  - We should investigate others like this. No reason to have so many different modules.
