### ISSUE TITLE
Import-AzureRmApiManagementApi: -Path parameter now mandatory?

### ISSUE THREAD

**Issue by Jaffacakes82** [Azure/azure-powershell#6965]
### Description
Since upgrading AzureRM to version 6.7.0 it appears that the -Path parameter for Import-AzureRmApiManagementAPi is now mandatory. Is this expected? If so, [the documentation](https://docs.microsoft.com/en-us/powershell/module/AzureRM.ApiManagement/Import-AzureRmApiManagementApi?view=azurermps-6.7.0) for this cmdlet needs to be updated as it currently doesn't state that it is a required parameter.

### Script/Steps for Reproduction
```
$azcontext = New-AzureRmApiManagementContext -ResourceGroupName $staticResourceGroupName -ServiceName $apiMgmtServiceName
Import-AzureRmApiManagementApi -Context $azcontext -SpecificationFormat "Swagger" -SpecificationUrl $outputUrl"/swagger/v1/swagger.json" -ApiId $apiId
```

### Module Version
6.7.0

### Environment Data
Azure Cloud PowerShell

### Debug Output
```
DEBUG: >> MakePath([AzureRM.ApiManagement.Netcore, Import-AzureRmApiManagementApi])
DEBUG: << MakePath([AzureRM.ApiManagement.Netcore, Import-AzureRmApiManagementApi])
DEBUG: 10:51:35 AM - ImportAzureApiManagementApi begin processing with ParameterSet 'ImportFromUrl'.
DEBUG: 10:51:35 AM - using account id '2431b742-c839-458a-b514-c09a5ff5c3f1'...
DEBUG: [Common.Authentication]: Authenticating using Account: '2431b742-c839-458a-b514-c09a5ff5c3f1', environment: 'AzureCloud', tenant: '849873ab-4265-46f9-b32d-3fa4fbb97ea1'
DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
Import-AzureRmApiManagementApi : 'Path' cannot be null.
At line:1 char:1
+ Import-AzureRmApiManagementApi -Context $azcontext -SpecificationForm ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Import-AzureRmApiManagementApi], ValidationException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.ImportAzureApiManagementApi

DEBUG: AzureQoSEvent: CommandName - Import-AzureRmApiManagementApi; IsSuccess - False; Duration - 00:00:00.0260042; Exception - Microsoft.Rest.ValidationException: 'Path' cannot be null.
   at Microsoft.Azure.Management.ApiManagement.Models.ApiCreateOrUpdateParameter.Validate()
   at Microsoft.Azure.Management.ApiManagement.ApiOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String serviceName, String apiId, ApiCreateOrUpdateParameter parameters, String ifMatch, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ApiManagement.ApiOperationsExtensions.CreateOrUpdateAsync(IApiOperations operations, String resourceGroupName, String serviceName, String apiId, ApiCreateOrUpdateParameter parameters, String ifMatch, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ApiManagement.ApiOperationsExtensions.CreateOrUpdate(IApiOperations operations, String resourceGroupName, String serviceName, String apiId, ApiCreateOrUpdateParameter parameters, String ifMatch)
   at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.ApiManagementClient.ApiImportFromUrl(PsApiManagementContext context, String apiId, PsApiManagementApiFormat specificationFormat, String specificationUrl, String apiPath, String wsdlServiceName, String wsdlEndpointName, Nullable`1 apiType)
   at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.ImportAzureApiManagementApi.ExecuteApiManagementCmdlet()
   at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.AzureApiManagementCmdletBase.ExecuteCmdlet();
DEBUG: Finish sending metric.
DEBUG: 10:51:35 AM - ImportAzureApiManagementApi end processing.
DEBUG: 10:51:35 AM - ImportAzureApiManagementApi end processing.
```

**Comment by maddieclayton** [comment]
@solankisamir Can you take a look at this issue?

**Comment by solankisamir** [comment]
@Jaffacakes82 there can be only one API with Empty PATH in an Api Management Instance. My guess is that you are hitting this issue when adding a second API with EMPTY PATH / root PATH.

**Comment by Jaffacakes82** [comment]
@solankisamir There's two APIs in my APIM instance, one has an empty path, one doesn't. I was trying to update the Swagger documentation associated with the API that has an empty path. Would you expect that action to cause this error? I didn't experience this in 5.7.0.

**Comment by thomasddn** [comment]
I see the same unexpected behavior when running this cmdlet from an Azure PowerShell task (version 3.*) in VSTS (Azure DevOps). We're using a private agent which has **AzureRM v6.4.0** installed.

Running the same script on my local machine executes successfully without any complaints about the `Path` parameter being null. My local machine has **AzureRM v5.7.0**.

The API's in the APIM instance all have a non-empty path (labeled as `API URL suffix` in the Azure Portal interface).

This is how I use the cmdlet:
`Import-AzureRmApiManagementApi -Context $apimContext -SpecificationFormat "Swagger" -SpecificationUrl $swaggerUrl -ApiId $apiId`

**Comment by ssrm** [comment]
When I am trying to use Import-AzureRmApiManagementApi, I am always getting below error. Is there anyone have any clue?

Body:
{
  "error": {
    "code": "ValidationError",
    "message": "One or more fields contain incorrect values:",
    "details": [
      {
        "code": "ValidationError",
        "target": "path",
        "message": "Invalid value of the Web API URL suffix"
      }
    ]
  }
}

**Comment by klagan** [comment]
> 
> 
> When I am trying to use Import-AzureRmApiManagementApi, I am always getting below error. Is there anyone have any clue?
> Body:
> {
> "error": {
> "code": "ValidationError",
> "message": "One or more fields contain incorrect values:",
> "details": [
> {
> "code": "ValidationError",
> "target": "path",
> "message": "Invalid value of the Web API URL suffix"
> }
> ]
> }
> }

Hi, did you ever resolve this?  I am having the same issue

**Comment by krispenner** [comment]
You must specify the path parameter as per the error message. You can just specify and empty string from my experience.

**Comment by ssrm** [comment]
@klagan In my case there is a space has appended to the beginning of path url and same I have removed it.

**Comment by klagan** [comment]
> @klagan In my case there is a space has appended to the beginning of path url and same I have removed it.

I did actually manage to figure out it was the "path" argument before i received these replies and forgot I'd asked the questions.  In my case it was that I was trying to use the same -Path for two different APIs.

Now I know that you must check: you havea path, you dont use it multiple times and check you dont have trailing spaces.

Nice! 

It does frustrate me - as I am sure it does everyone else - that the error information is so limited and at times unrelated.

The documentation doesnt match neither as -Path is not mentioned as a required field.

Thanks all.

**Comment by solankisamir** [comment]
We version https://github.com/Azure/azure-powershell/blob/master/src/ApiManagement/ApiManagement/ChangeLog.md#version-110 
we improved error logging into the issue and have updated the documentation.
