### ISSUE TITLE
Hyphens are not interpreted as they are on the portal page for Get-AzureRmResource

### ISSUE THREAD

**Issue by sotnikop** [Azure/azure-powershell#6985]
### Description
The Get-AzureRmResource command does not handle hyphens within resource names.
For example : Get-AzureRmResource -Name tst-dev*
Hyphens within resource names are a valid character

The azure portal page will search for partial matches containing hyphens just fine

### Script/Steps for Reproduction
Its just a single command.
Setup you azure subscription with resources such as 
tst-dev-blah
tst-dev1
tst-dev3

Get-AzureRmResource -Name tst-dev*

Observe that the command does not return anything
### Module Version

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands                                                                              
---------- -------    ----                                ----------------                                                                              
Script     6.7.0      AzureRM                                                                                                                           
Script     6.5.0      AzureRM                                            
### Environment Data

$PSVersionTable

Name                           Value                                                                                                                    
----                           -----                                                                                                                    
PSVersion                      5.0.10586.117                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                  
BuildVersion                   10.0.10586.117                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                          
WSManStackVersion              3.0                                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                                      
SerializationVersion           1.1.0.1 
### Debug Output

Doesnt looks like I can run it with Continue.
Get-AzureRmResource -Name tst-dev* $DebugPreference="continue"
Get-AzureRmResource : A positional parameter cannot be found that accepts argument 'SilentlyContinue=continue'.
At line:1 char:1
+ Get-AzureRmResource -Name tst-dev* $DebugPreference="continue"

**Comment by markcowl** [comment]
@sotnikop Please execute the assignment statement:

```powershell
$DebugPreference="Continue"
```

Then, after that has executed, execute the failing cmdlet separately, and post the debug log here.

**Comment by maddieclayton** [comment]
Closing as no response. @sotnikop Feel free to reopen this issue with the information requested.
