### ISSUE TITLE
Add example for Simple parameter set to the New-AzureRmVmss cmdlet help doc

### ISSUE THREAD

**Issue by praries880** [Azure/azure-powershell#6989]
We need to add an example for the [Simple Parameter Set](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Compute/Commands.Compute/Manual/VirtualMachineScaleSetCreateOrUpdateMethod.cs#L38) to the [help file](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Compute/Commands.Compute/help/New-AzureRmVmss.md) As of now it only documents the regular non simple param set usage.

**Comment by praries880** [comment]
PR : https://github.com/Azure/azure-powershell/pull/7186

**Comment by markcowl** [comment]
Closed
