### ISSUE TITLE
Set-AzureSubscription fails with SSL/TLS Error

### ISSUE THREAD

**Issue by abhijeetgaiha** [Azure/azure-powershell#6990]
### Description
Consistently getting this error:

Set-AzureSubscription -SubscriptionId 20ff167c-9f4b-4a73-9fd6-0dbe93fa77
8a -CurrentStorageAccountName lade2etest
Set-AzureSubscription : An error occurred while sending the request.
At line:1 char:1
+ Set-AzureSubscription -SubscriptionId 20ff167c-9f4b-4a73-9fd6-0dbe93f ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureSubscription], HttpRequestException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Profile.SetAzureSubscriptionCommand

### Script/Steps for Reproduction

```powershell
Set-AzureSubscription -SubscriptionId <sub-id> -CurrentStorageAccountName <storage-acct>
```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```
ModuleType Version    Name
---------- -------    ----
Script     5.3.0      Azure
Script     4.5.0      Azure.Storage
Script     5.4.0      AzureRM.Profile

### Environment Data

```powershell
$PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      5.1.14394.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14394.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Debug Output

```
DEBUG: AzureQoSEvent: CommandName - Set-AzureSubscription; IsSuccess - False; Duration - 00:00:00.1144711; Exception -
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The
request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.WindowsAzure.Management.Storage.StorageAccountOperationsExtensions.Get(IStorageAccountOperations
operations, String accountName)
   at
Microsoft.WindowsAzure.Commands.Common.Storage.StorageUtilities.GenerateCloudStorageAccount(IStorageManagementClient
storageClient, String accountName)
   at Microsoft.WindowsAzure.Commands.Profile.SetAzureSubscriptionCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 6:35:42 PM - SetAzureSubscriptionCommand end processing.
DEBUG: 6:35:42 PM - SetAzureSubscriptionCommand end processing.
```

**Comment by markcowl** [comment]
@abhijeetgaiha Can you provide details on the storage account you are using as default?  Does it support http and https connections?

**Comment by markcowl** [comment]
Closing for lack of response
