### ISSUE TITLE
Export-AzureRmAutomationRunbook Adding extra '\' to file names.

### ISSUE THREAD

**Issue by lanrongwen** [Azure/azure-powershell#6999]
### Description
I am running Powershell 6.1 preview 4 in Centos 7.3.
I have AzureRM.netCore version 0.13.1

When using export-azurermautomationrunbook it prepends the character '\\' to the filename.  This causes issues when trying to access the file in a Linux based environment.

/tmp/\\runbook.ps1

### Script/Steps for Reproduction

```powershell
$t = Get-AzureRmAutomationAccount -Name <AA Name> -ResourceGroupName <RG Name>
$y = Get-AzureRmAutomationRunbook -AutomationAccountName $t.AutomationAccountName -ResourceGroupName $t.ResourceGroupName
Export-AzureRmAutomationRunbook -Name $y[0].Name -Slot Published -AutomationAccountName $t.AutomationAccountName -ResourceGroupName $t.ResourceGroupName -OutputFolder /tmp/
ls /tmp
```

### Module Version

AzureRM.NetCore 0.13.1

### Environment Data
Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Linux 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by maddieclayton** [comment]
This should be fixed by this PR: https://github.com/Azure/azure-powershell/pull/6986

**Comment by lanrongwen** [comment]
Awesome, thanks!  I'll check it out.

**Comment by maddieclayton** [comment]
@lanrongwen Just FYI, this PR has not yet been merged, so the fix won't be in until the next release in September.

**Comment by maddieclayton** [comment]
Closing as I have tested and verified that it is fixed by the PR.
