### ISSUE TITLE
Azure PS 0.8.12 :: Network Security Group commands missing documentation

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#70]
The Azure PowerShell commands for managing Network Security Groups are almost completely absent of documentation, except for documentation that is automatically generated by PowerShell.

![image](https://cloud.githubusercontent.com/assets/466713/5589477/5f05e2b6-90e5-11e4-87e4-8dfcf0270557.png)

Please ensure that these commands (and all others) are thoroughly documented in the Azure PowerShell module.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
