### ISSUE TITLE
Publish-AzureVMDscConfiguration not parsing all requested modules

### ISSUE THREAD

**Issue by sebastus** [Azure/azure-powershell#700]
If Import-DscResource statement contains -ModuleName item with specific version selected:

(e.g. -ModuleName @{ModuleName="xActiveDirectory"; ModuleVersion="2.5.0.0"} )

It leaves that module out of the zip file created at -ConfigurationArchivePath.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
