### ISSUE TITLE
Fix help issues in ApiManagement

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7002]
When running static analysis fresh on ApiManagement, these help issues are thrown:

Get-AzApiManagementProperty.md | No synopsis found
Get-AzApiManagementProperty.md | No description found
Remove-AzApiManagementAuthorizationServer.md | No examples found
Update-AzApiManagementRegion.md | No examples found

**Comment by maddieclayton** [comment]
@solankisamir Can you take a look at this issue?

**Comment by solankisamir** [comment]
This should now be fixed.
