### ISSUE TITLE
Fix help issues in Automation

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7003]
When running static analysis fresh on Automation, these help issues are thrown:

Remove-AzAutomationDscConfiguration.md | No examples found
Remove-AzAutomationDscNodeConfiguration.md | No examples found

**Comment by maddieclayton** [comment]
@vrdmr Can you take a look at this issue?

**Comment by andyw248** [comment]
Not a P1, as well as fairly straightforward (as compared to creating or updating where properties are required). Closing for this reason.
