### ISSUE TITLE
Fix help issues in Backup

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7004]
When running static analysis fresh on Backup, these help issues are thrown:

Disable-AzBackupProtection.md | No examples found
Enable-AzBackupContainerReregistration.md | No examples found
Get-AzBackupVaultCredentials.md | No examples found
Set-AzBackupProtectionPolicy.md | No examples found
Wait-AzBackupJob.md | No examples found

**Comment by maddieclayton** [comment]
@dragonfly91 Can you take a look at this issue?

**Comment by cormacpayne** [comment]
Closing as this module no longer exists
