### ISSUE TITLE
Fix help issues in Batch

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7005]
When running static analysis fresh on Batch, these help issues are thrown:

Get-AzBatchAccountKeys.md | No examples found
Remove-AzBatchJobSchedule.md | No examples found
Set-AzBatchJobSchedule.md | No examples found

**Comment by maddieclayton** [comment]
@matthchr Can you take a look at this issue?

**Comment by matthchr** [comment]
@maddieclayton @cormacpayne - I am looking at this and it seems to me that the "missing examples" are actually for cmdlets that don't exist?

There is no `Get-AzBatchAccountKeys`, only `Get-AzureRmBatchAccountKeys`. Similarly with the others:
`Remove-AzBatchJobSchedule` is actually `Remove-AzureBatchJobSchedule`, and `Set-AzBatchJobSchedule` is actually `Set-AzureBatchJobSchedule`.

There is documentation for all 3 of the above commands as far as I can tell...

**Comment by matthchr** [comment]
I fixed this issue in our private release branch. It should get merged next month. @maddieclayton do you want to close this now or leave it open until it's merged to mainline?

**Comment by maddieclayton** [comment]
Good to close! Thanks @matthchr
