### ISSUE TITLE
Fix help issues in Cdn

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7006]
When running static analysis fresh on Cdn, these help issues are thrown:

Get-AzCdnCustomDomain.md | No examples found
Get-AzCdnEdgeNodes.md | No examples found
Get-AzCdnEndpoint.md | No examples found
Get-AzCdnEndpointNameAvailability.md | No examples found
Get-AzCdnEndpointResourceUsage.md | No examples found
Get-AzCdnOrigin.md | No examples found
Get-AzCdnProfile.md | No examples found
Get-AzCdnProfileResourceUsage.md | No examples found
Get-AzCdnProfileSsoUrl.md | No examples found
Get-AzCdnSubscriptionResourceUsage.md | No examples found
New-AzCdnCustomDomain.md | No examples found
New-AzCdnEndpoint.md | No examples found
New-AzCdnProfile.md | No examples found
Publish-AzCdnEndpointContent.md | No examples found
Remove-AzCdnCustomDomain.md | No examples found
Remove-AzCdnEndpoint.md | No examples found
Remove-AzCdnProfile.md | No examples found
Set-AzCdnEndpoint.md | No examples found
Set-AzCdnOrigin.md | No examples found
Set-AzCdnProfile.md | No examples found
Start-AzCdnEndpoint.md | No examples found
Stop-AzCdnEndpoint.md | No examples found
Test-AzCdnCustomDomain.md | No examples found
Unpublish-AzCdnEndpointContent.md | No examples found

**Comment by maddieclayton** [comment]
@prakharsharma10 Can you take a look at this issue?

**Comment by prakharsharma10** [comment]
Hi @maddieclayton, we have transitioned to a different team. @nachakra can help with the client development tasks/issues for CDN service.
