### ISSUE TITLE
Fix help issues in Compute

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7007]
When running static analysis fresh on Compute, these help issues are thrown:

Get-AzVMADDomainExtension.md | No examples found
Get-AzVMDscExtensionStatus.md | No examples found
New-AzVMSqlServerKeyVaultCredentialConfig.md | No description found
New-AzVMSqlServerKeyVaultCredentialConfig.md | No examples found
Remove-AzVMAccessExtension.md | No examples found
Remove-AzVMBackup.md | No description found
Remove-AzVMCustomScriptExtension.md | No examples found
Remove-AzVMNetworkInterface.md | No examples found
Set-AzVMADDomainExtension.md | No examples found
Set-AzVMBackupExtension.md | No description found
Set-AzVMPlan.md | No examples found
Set-AzVmssVM.md | No examples found

**Comment by maddieclayton** [comment]
@hyonholee Can you take a look at this issue?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
