### ISSUE TITLE
AzureStack: Updated environment settings are not taking effect even after relogin

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#7008]
### Description

Here is what I am doing 

$envInfo= Add-AzureRmEnvironment -ARMEndpoint $ArmEndpoint -Name "AzureStackAdmin" -AzureKeyVaultDnsSuffix vault.local.azurestack.external -AzureKeyVaultServiceEndpointResourceId https://vault.local.azurestack.external 
Login-AzureRmAccount -EnvironmentName "AzureStackAdmin" -TenantId $tenantID -Credential $creds 

After doing these, I realize that I have wrong values for keyvault dns suffix and  updating the environment again with the correct values(It doesn’t matter whether I do Add-*Env or Set-*Env)

$envInfo= Add-AzureRmEnvironment -ARMEndpoint $ArmEndpoint -Name "AzureStackAdmin" -AzureKeyVaultDnsSuffix adminvault.local.azurestack.external -AzureKeyVaultServiceEndpointResourceId https://adminvault.local.azurestack.external
Login-AzureRmAccount -EnvironmentName "AzureStackAdmin" -TenantId $tenantID -Credential $creds

Looking at the %appdata%\*\.json file, the new environment settings are updated in EnvironmentTable json node while under Contexts\Environment it is not updated. Essentially this means that the new settings are not taking effect and the Set-AzureRmKeyvaultSecret is not sending the request to the wrong endpoint even after updating the environment settings.

### Module Version
AzureRm.Profile - 5.4.0 (latest)

WorkAround
Please note that, if the autocontext save is disabled,  the issue will mo happen
Another workaround is to logout explicitly and then relogin

**Comment by cormacpayne** [comment]
This has been fixed

**Comment by bganapa** [comment]
@cormacpayne @markcowl Thanks!
