### ISSUE TITLE
Fix help issues in Insights

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7010]
When running static analysis fresh on Insights, these help issues are thrown:

Get-AzLogProfile.md | No examples found
New-AzAutoscaleWebhook.md | No examples found
Remove-AzAutoscaleSetting.md | No examples found
Remove-AzLogProfile.md | No examples found

**Comment by maddieclayton** [comment]
@gucalder Can you take a look at this issue?

**Comment by akkumari-ms** [comment]
@maddieclayton is this issue still relevant?
