### ISSUE TITLE
Fix Help Issues in Network

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7011]
When running static analysis fresh on Network, these help issues are thrown:

Add-AzApplicationGatewayAuthenticationCertificate.md | No examples found
Add-AzApplicationGatewayUrlPathMapConfig.md | No examples found
Add-AzLoadBalancerInboundNatPoolConfig.md | No synopsis found
Add-AzLoadBalancerInboundNatPoolConfig.md | No description found
Get-AzApplicationGatewayAuthenticationCertificate.md | No examples found
Get-AzApplicationGatewayBackendAddressPool.md | No description found
Get-AzLoadBalancerInboundNatPoolConfig.md | No synopsis found
Get-AzLoadBalancerInboundNatPoolConfig.md | No description found
Get-AzRouteFilter.md | No examples found
Get-AzRouteFilterRuleConfig.md | No examples found
New-AzApplicationGatewayAuthenticationCertificate.md | No examples found
New-AzLoadBalancerInboundNatPoolConfig.md | No synopsis found
New-AzLoadBalancerInboundNatPoolConfig.md | No description found
New-AzRouteFilter.md | No examples found
New-AzRouteFilterRuleConfig.md | No examples found
Remove-AzApplicationGatewayAuthenticationCertificate.md | No examples found
Remove-AzApplicationGatewayUrlPathMapConfig.md | No examples found
Remove-AzLoadBalancerInboundNatPoolConfig.md | No synopsis found
Remove-AzLoadBalancerInboundNatPoolConfig.md | No description found
Remove-AzRouteFilter.md | No examples found
Remove-AzRouteFilterRuleConfig.md | No examples found
Set-AzApplicationGatewayAuthenticationCertificate.md | No examples found
Set-AzApplicationGatewayUrlPathMapConfig.md | No examples found
Set-AzLoadBalancerInboundNatPoolConfig.md | No synopsis found
Set-AzLoadBalancerInboundNatPoolConfig.md | No description found
Set-AzRouteFilter.md | No examples found
Set-AzRouteFilterRuleConfig.md | No examples found

**Comment by maddieclayton** [comment]
@MikhailTryakhov Can you take a look at this issue?

**Comment by number213** [comment]
@maddieclayton @MikhailTryakhov Working on it...

**Comment by number213** [comment]
Fixed by: https://github.com/Azure/azure-powershell/pull/8396
