### ISSUE TITLE
Fix help issues in Scheduler

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7015]
When running static analysis fresh on Scheduler, these help issues are thrown:

Disable-AzSchedulerJobCollection.md | No examples found
Enable-AzSchedulerJobCollection.md | No examples found
Get-AzSchedulerJob.md | No examples found
Get-AzSchedulerJobCollection.md | No examples found
Get-AzSchedulerJobHistory.md | No examples found
New-AzSchedulerHttpJob.md | No examples found
New-AzSchedulerJobCollection.md | No examples found
New-AzSchedulerServiceBusQueueJob.md | No examples found
New-AzSchedulerServiceBusTopicJob.md | No examples found
New-AzSchedulerStorageQueueJob.md | No examples found
Remove-AzSchedulerJob.md | No examples found
Remove-AzSchedulerJobCollection.md | No examples found
Set-AzSchedulerHttpJob.md | No examples found
Set-AzSchedulerJobCollection.md | No examples found
Set-AzSchedulerServiceBusQueueJob.md | No examples found
Set-AzSchedulerServiceBusTopicJob.md | No examples found
Set-AzSchedulerStorageQueueJob.md | No examples found

**Comment by maddieclayton** [comment]
@derek1ee Can you take a look at this issue?

**Comment by cormacpayne** [comment]
Closing as this module no longer exists.
