### ISSUE TITLE
Fix help issues in Sql

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7016]
When running static analysis fresh on Sql, these help issues are thrown:

Get-AzSqlDatabaseGeoBackupPolicy.md | No examples found
Get-AzSqlDatabaseReplicationLink.md | No examples found
Get-AzSqlServerBackupLongTermRetentionVault.md | No examples found
Get-AzSqlServerDisasterRecoveryConfiguration.md | No examples found
Get-AzSqlServerDisasterRecoveryConfigurationActivity.md | No examples found
New-AzSqlDatabaseCopy.md | No examples found
New-AzSqlServerDisasterRecoveryConfiguration.md | No examples found
Remove-AzSqlDatabaseSecondary.md | No examples found
Remove-AzSqlServerDisasterRecoveryConfiguration.md | No examples found
Set-AzSqlDatabaseGeoBackupPolicy.md | No examples found
Set-AzSqlDatabaseSecondary.md | No examples found
Set-AzSqlServerBackupLongTermRetentionVault.md | No examples found
Set-AzSqlServerDisasterRecoveryConfiguration.md | No examples found

**Comment by maddieclayton** [comment]
@jaredmoo Can you take a look at this issue?

**Comment by aamalvea** [comment]
We're sorry that we didn't get back to you in reasonable time frame. If you are still experiencing this issue, please file a new issue and we will respond in 48 hours.
