### ISSUE TITLE
webapp:Fix help issues in Websites

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7017]
When running static analysis fresh on Websites, these help issues are thrown:

Edit-AzWebAppBackupConfiguration.md | No synopsis found
Edit-AzWebAppBackupConfiguration.md | No examples found
Get-AzAppServicePlanMetrics.md | No synopsis found
Get-AzWebAppBackup.md | No synopsis found
Get-AzWebAppBackupConfiguration.md | No synopsis found
Get-AzWebAppBackupList.md | No synopsis found
New-AzWebAppBackup.md | No synopsis found
New-AzWebAppDatabaseBackupSetting.md | No synopsis found
Remove-AzWebAppBackup.md | No synopsis found
Remove-AzWebAppSlot.md | No synopsis found
Reset-AzWebAppPublishingProfile.md | No synopsis found
Reset-AzWebAppSlotPublishingProfile.md | No synopsis found
Restart-AzWebAppSlot.md | No synopsis found
Restore-AzWebAppBackup.md | No synopsis found

**Comment by maddieclayton** [comment]
@panchagnula Can you take a look at this issue?

**Comment by panchagnula** [comment]
Closing this since this should now be fixed.
