### ISSUE TITLE
Improve Enable/Disable-AzureRmAlias

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7019]
Additional tasks
- [ ] Only import modules that are currently installed

**Comment by brwilkinson** [comment]
Also if there was a -persist switch that would be great.

**Comment by maddieclayton** [comment]
@maddieclayton If you use the -Scope parameter, you can turn aliases on for either the CurrentUser or the LocalMachine. This will enable aliases for all future sessions until Disable-AzureRmAlias is run (with that scope).  Would this work for you?

**Comment by brwilkinson** [comment]
@maddieclayton yes I will give scope a try and see if it persists. Thank you.

**Comment by maddieclayton** [comment]
Okay let me know if there's anything I can do to help you - it does indeed write to the PowerShell profile.  It creates the alias mapping from Az to AzureRM regardless of whether the module is loaded, and importing the azure modules should not overwrite these aliases.

**Comment by markcowl** [comment]
Closing - we have an issue to change scope differently so it can use the current scope of the global scope, in addition to these persistent scopes that use profiles
