### ISSUE TITLE
Enable client side tracing for the admin cmdlets

### ISSUE THREAD

**Issue by ghost** [Azure/azure-powershell#7030]
### Description

We are missing client side tracing for FRU, add-cluster and add-node operations’ usage of the admin cmdlets

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by bganapa** [comment]
This needs a handler to print the Http Request and Response messages.

**Comment by deathly809** [comment]
I asked the Azure-PowerShell team and they said they don't know, that is kinda scary.

**Comment by deathly809** [comment]
Because we cannot tie into the Azure-PowerShell cmdlet base classes we cannot piggy back on their implementation.  We will have to implement our own solution.  One possibility is to create an HttpHandler which writes to the Debug stream for each request response.

**Comment by deathly809** [comment]
If the user is talking about Set-PSDebug I am not sure there is anything I can do.  If you do -Debug then you can see debug information such as HTTP requests.  As the user has delete their account I cannot ask.
