### ISSUE TITLE
Change NetStandard Common assemblies to depend on Newtonsoft.Json 9

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#7032]
### Description

- [x] Update common runtiem to use latest versions of clientruntiem assemblies from nuget
- [x] Update NetStandard target common packages to use Newtonsoft.Json 9
- [x] Add side-by-sdie loading logic for Newtonsoft.Json 9 and Newtonsoft.Json 10 on desktop to Az.Profile.psm1

### Cost: 4

**Comment by markcowl** [comment]
After research, we will need to downgrade Hyak libraries to 9.0, including the following:

- [ ] Hyak.Common
- [ ] Microsoft.Azure.Commerce.UsageAggregates
- [ ] Microsoft.Azure.Management.APiManagement
- [ ] Microsoft.Azure.Management.Automation
- [ ] Microsoft.Azure.Management.DataFactories

**Comment by markcowl** [comment]
Fixed

**Comment by i255d** [comment]
Fixed?  Get-AzKeyVaultSecret : Could not load file or assembly 'Newtonsoft.json'.  Version=9.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxx' or one of its dependencies.  So what do we do?  Running on Windows 10 Desktop.
