### ISSUE TITLE
Can't RDP into Instances created from the VMSS tutorial

### ISSUE THREAD

**Issue by gmcfrear** [Azure/azure-powershell#7036]
Context:
https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/tutorial-create-and-manage-powershell

Description:
I followed the tutorial with my personal account, and found I couldn't rdp into the instances.

ConsoleOutput attached.

--------------------------Modules-------------
PS C:\Users\gfrear> Get-Module AzureRM -ListAvailable | Select-Object -Property Name,Version,Path
Name    Version Path
----    ------- ----
AzureRM 6.7.0   C:\Program Files\WindowsPowerShell\Modules\AzureRM\6.7.0\AzureRM.psd1

PS C:\Users\gfrear> $PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  228
-------------------------------------------------

Comment from Iain:
Looks like without a health probe on the load balancing rule for TCP port 80, the load balancer doesn't consider the VM instances to be healthy so traffic isn't directed to them for RDP:

$lb = (Get-AzureRmLoadBalancer -ResourceGroupName "myResourceGroup" -Name "myLoadBalancer")

$lb | Add-AzureRmLoadBalancerProbeConfig -Name "myHealthProbe" `
  -Protocol TCP `
  -Port 80 `
  -IntervalInSeconds 15 `
  -ProbeCount 2

$lb | Set-AzureRmLoadBalancerProbeConfig -Name "myHealthProbe" -Port 80 -IntervalInSeconds 15 -ProbeCount 2
[EditedConsoleTutorial.txt](https://github.com/Azure/azure-powershell/files/2319204/EditedConsoleTutorial.txt)

**Comment by maddieclayton** [comment]
@praries880 Can you take a look at this issue and redirect if necessary?

**Comment by praries880** [comment]
@gmcfrear  The new-azurermvmss simple param set creates NAT pools with mappings for the RDP port on all the vms.

Take my example below :
``` powershell
New-AzureRmVmss  -Credential $creds -VMScaleSetName pary123Test -Location "EastUs"
...

Thnis creates a LB with the name `pary123Test`


```

**Comment by praries880** [comment]
@gmcfrear I set up the vmss with the simple param set.

Heres what I see :

``` powershell
PS C:\Users\paresin> Get-AzureRmVmssVM -ResourceGroupName  pary123Test -VMScaleSetName pary123Test

ResourceGroupName          Name Location             Sku Capacity InstanceID ProvisioningState
-----------------          ---- --------             --- -------- ---------- -----------------
PARY123TEST       pary123Test_0   eastus Standard_DS1_v2                   0         Succeeded
PARY123TEST       pary123Test_2   eastus Standard_DS1_v2                   2         Succeeded


PS C:\Users\paresin>
PS C:\Users\paresin>
PS C:\Users\paresin> Get-AzureRmLoadBalancerInboundNatRuleConfig -LoadBalancer $lb | Select-Object Name,Protocol,FrontEn
dPort,BackEndPort

Name              Protocol FrontendPort BackendPort
----              -------- ------------ -----------
pary123Test3389.0 Tcp             50000        3389
pary123Test5985.0 Tcp             52000        5985
pary123Test3389.2 Tcp             50002        3389
pary123Test5985.2 Tcp             52002        5985


PS C:\Users\paresin> Get-AzureRmPublicIpAddress -ResourceGroupName pary123Test -Name pary123Test  | Select IpAddress

IpAddress
---------
40.90.241.250

PS C:\Users\paresin> ping 40.90.241.250

Pinging 40.90.241.250 with 32 bytes of data:
Request timed out.

Ping statistics for 40.90.241.250:
    Packets: Sent = 1, Received = 0, Lost = 1 (100% loss),
Control-C
PS C:\Users\paresin> mstsc /v 40.90.241.250:50000
```


For me the ping fails but mstsc works (I got prompted for creds n upon entering the correct creds I was inside the vm...)
