### ISSUE TITLE
Reference for Azure Automation ConnectionType as Azure

### ISSUE THREAD

**Issue by jayendranarumugam** [Azure/azure-powershell#7048]
I've been trying to getting some knowledge about the different Connection type in AzureAutomation. So far, I'm seeing three different kinds of connection Type

1. Azure
2. Azure Service Principal
3. Azure Classic Certificate

I can able to get the details for AzureServicePrincipal and AzureClassic Certificate [here](https://docs.microsoft.com/en-us/azure/automation/manage-runas-account)

As per this

**Azure Service Principal (Azure Run As Account)**

> Azure Run As Account - This account is used to manage Resource Manager deployment model resources.

**Azure Classic Certificate (Azure Classic Run As Account)**

> This account is used to manage Classic deployment model resources.

But I couldn't able to find any reference for the Azure connection Type. I'm wondering when one should use the connection type as Azure.

I also posted a related question in SO.
https://stackoverflow.com/questions/52008112/how-to-login-azurerm-using-connectiontype-as-azure-in-azureautomation

Some question related to this as well
https://stackoverflow.com/questions/51983232/difference-between-azure-and-azureserviceprincipal-in-connectiontypename

Is there is any reference to guide me on this?

**Comment by maddieclayton** [comment]
@vrdmr @eamonoreilly @safeermohammed Can one of you answer this customer question?

**Comment by jayendranarumugam** [comment]
@maddieclayton  @vrdmr @eamonoreilly  @safeermohammed Could you please help me on this?

**Comment by andyw248** [comment]
Fixed with the PR from Jun 17.
