### ISSUE TITLE
Get-AzureRmHDInsightCluster does not provide information on VNET or Subnet

### ISSUE THREAD

**Issue by falmada** [Azure/azure-powershell#7049]
This is not a bug, it's actually some missing information regarding HDInsight cluster resources within Azure.

When doing a deployment through New-AzureRmHDInsightCluster, we have VirtualNetworkId and SubnetName parameters available, but when querying for existing clusters using Get-AzureRmHDInsightCluster, there is no way to get those two values. 

Through portal, Virtual Network information is provided (but missing Subnet Name), hence the information is likely stored on the object, but so far the Get command does not have a way to retrieve it.

Name                      : xxxxxxx
Id                        : /subscriptions/Xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.HDInsight/clusters/xxxx
Location                  : Central US
ClusterVersion            : 3.6.1000.0
OperatingSystemType       : Linux
ClusterTier               : Standard
ClusterState              : Running
ClusterType               : RSERVER
CoresUsed                 : 184
HttpEndpoint              : xxxxx.azurehdinsight.net
Error                     :
DefaultStorageAccount     : xxxxxxx.azuredatalakestore.net
DefaultStorageContainer   :
DefaultStorageRootPath    : /xxxxxx/
ResourceGroup             : xxxxxx
AdditionalStorageAccounts : {}
ComponentVersion          : {[spark, 2.1]}
WorkerNodeDataDisksGroups : {}
SecurityProfile           :

Any chance this information can be added on a future release?

Thanks!

**Comment by maddieclayton** [comment]
@momusoru @z01c @wawon-msft Can you take a look at this feature request?

**Comment by aim-for-better** [comment]
The new version which adds the vnet information will be published in  2 weeks.

**Comment by aim-for-better** [comment]
The latest PowerShell module[ Az.HDInsight 3.4.0](https://www.powershellgallery.com/packages/Az.HDInsight/3.4.0) has been available.
