### ISSUE TITLE
Get-AzureSchedulerJobCollection does not list WebJobs job collection

### ISSUE THREAD

**Issue by dimkanewtown** [Azure/azure-powershell#705]
As you can see there are two scheduled job collections.
![Job collection list](http://i.imgur.com/tqyYZS8.png)
![Job collection list in ARM](http://i.imgur.com/e553job.png)

However the Get-AzureSchedulerJobCollection only lists one
![powershell results](http://i.imgur.com/WRlHsvC.png)

**Comment by dimkanewtown** [comment]
Looks like this is the culprit. It effectively translates the region name to cs-EastUS-scheduler instead of cs-WebJobs-EastUS-scheduler.

      namespace Microsoft.WindowsAzure.Commands.Utilities.Scheduler.Common
    {
    public static class ExtensionMethods
    {
        public static string ToCloudServiceName(this string region)
        {
            return Constants.CloudServiceNameFirst + region.Trim().Replace(" ", string.Empty) + Constants.CloudServiceNameSecond;
        }

**Comment by p4rnicke** [comment]
Is there a workaround?
I cannot remove or modify the wbjobs collection this way.

**Comment by sphibbs** [comment]
![image](https://user-images.githubusercontent.com/14059531/30924433-8f3bb99a-a363-11e7-9a6f-6eb90a6223bc.png)

**Comment by p4rnicke** [comment]
I do not get how your comment is related to this issue @sphibbs

**Comment by sphibbs** [comment]
Sorry. Copy Paste error. {{checks clipboard and tries again}}
Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration.
