### ISSUE TITLE
Update Common Sign Build to Always Update Package Version and AssemblyFileVersion

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#7057]
### Description

Need to have an automated mechanism that updates AssemblyFileVersion and PackageVersion (but not AssemblyVersion) for azure-powershell-common packages.

Versions should automatically be updated on each sign build, likely by keying on the CodeSign or a similar setting.

This should not require any changes to source code, so a generated, unique, montonically increasing number makes the most sense.

There is some discussion of mechanisms for this here: https://stackoverflow.com/questions/43274254/setting-the-version-number-for-net-core-projects-csproj-not-json-projects/43280282#43280282

**Comment by MiYanni** [comment]
Changes here: https://github.com/Azure/azure-powershell-common/pull/31
I've updated the CI job for it: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-common-sign/

**Comment by MiYanni** [comment]
The changes have been merged.
