### ISSUE TITLE
Publish azure-powershell-common packages to MyGet feed

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#7060]
### Description

- [x] Create a public MyGet feed for azure-powershell-common (this means seting up a MyGet account with team credentials)
- [ ] Add an additional setting to allow building only a single or set of packages instead of all packages
- [x] Add a Publish build target and job to publich to the MyGet feed - this will require credential injection through environment variables
- [x] Add automatic tagging to the Publish Build Target, which pushes a Github Release for every version of the packages published including
  - [ ] Date published
  - [x] Package and Version

### Cost: 4

**Comment by MiYanni** [comment]
We have a MyGet account already. It was the one for Autorest: https://myget.org/users/azuresdkci

**Comment by MiYanni** [comment]
Based on conversations, created a new user. Here is the public info:
**User**: https://www.myget.org/users/azure-powershell
**Feed URI**: https://www.myget.org/F/azure-powershell/api/v3/index.json
**Push URI**: https://www.myget.org/F/azure-powershell/api/v2/package

**Comment by MiYanni** [comment]
Single package building will be done separately.
