### ISSUE TITLE
Hardly usable output of the Get-AzureRmTenant cmdlet

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#7061]
Get-AzureRmTenant cmdlet outputs the IDs but not the Directory info.
What can we do with that output?

**Comment by markcowl** [comment]
@alexandair Unfortunately, there isn't a good API call that provides this data.  Do you think it would be more appropriate to simply remove the cmdlet?

**Comment by alexandair** [comment]
I don't think you can remove it. It's used in PowerShell Cloud Shell. And some other users probably use it.
The way how they used it is an assumption that the first element [0] of the output IDs represents the default tenant. That's almost like a lucky guess just looking at all those IDs without any other info.

**Comment by maddieclayton** [comment]
Adding this to the backlog to take a look at after Ignite.

**Comment by AmarettoSlim** [comment]
What's the context for removing this?

There are users in the field with a single account belonging to multiple tenants (as a user or guest) and AzTenant returning the appropriate Domain would be extremely helpful for driving business logic as we interact with Azure through code ...

Is there a way  to accomplish this that I'm not aware of?

Thanks!

**Comment by AmarettoSlim** [comment]
First off, thank you MS team! I really appreciate what you guys are building, it's truly awesome.

For what it's worth I wanted to add context, getting AzTenant or AzureRMTenant to return proper directory values for a single account which belongs to multiple tenants is something that's been asked for in at least 4 other issue requests and it'd be killer to get something on the map to address this.

![image](https://user-images.githubusercontent.com/6744436/57802929-20d78000-7725-11e9-8f2b-b6bd405303f3.png)

**Comment by drewkg** [comment]
Even the sample outputs in the documentation (https://docs.microsoft.com/en-us/powershell/module/az.accounts/get-aztenant?view=azps-2.4.0#outputs) show the directory information to be populated.  

As a member of 30+ tenancies, the output from this command is almost useless.

**Comment by dingmeng-xue** [comment]
Current api version `https://management.azure.com/tenants?api-version=2016-06-01` doesn't return directory. The new version `/tenants?api-version=2019-03-01` can support it. Plan it as feature request.

**Comment by dingmeng-xue** [comment]
We will support it in Az.Accounts

**Comment by msJinLei** [comment]
Fixed by https://github.com/Azure/azure-powershell/pull/12292 and https://github.com/Azure/azure-powershell/pull/12495
