### ISSUE TITLE
Add 'Select-AzureRmSubscription' alias to Az.Profile

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#7079]
### Description

- [ ] Add Select-AzureRmSubscription -> SetAzSubscription alias to Az.Profile aliases
- [ ] Go through the other exported aliases in existing AzureRM modules and ensure they are represented in the aliases (particularly, Login- , Add- , and Logout al;iases for accounts in Az.Profile)
- [ ] Go through Az.* modules definitions and vclena up exported aliases
  - [ ] Remove any aliases that use AzureRM prefixes
  - [ ] Ensure that these aliases are represented when Enable-AzureRmAlias is executed
  - [ ] Ensure that there is an equivalent 'Az' alias for andy of these remaining AzureRm aliases.

### Cost: 1

**Comment by maddieclayton** [comment]
Done
