### ISSUE TITLE
Remove the DomainName property from the output of Get-AzTenant

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7086]
### Description
- [x] Remove the Tenant property from output
- [ ] Put this breaking change into the migration guide

### Cost: 2

**Comment by markcowl** [comment]
Fixed

**Comment by AmarettoSlim** [comment]
What's the context for removing this?

There are users in the field with a single account belonging to multiple tenants (as a user or guest) and AzTenant returning the appropriate Domain would be extremely helpful for driving business logic as we interact with Azure through code ...

Is there a way  to accomplish this that I'm not aware of?

Thanks!

**Comment by djhalibut** [comment]
Hello,

I have the same question as AmarettoSlim. Is there a way to list the tenants and their domains?

Thanks!
