### ISSUE TITLE
webapp:Why Linux related command are not available in Azure Powershell? 

### ISSUE THREAD

**Issue by michaelsync** [Azure/azure-powershell#7096]
I noticed that some commands related to Linux are not available in Azure Powershell. 

For example: 

1. az webapp --multicontainer-config-type compose --multicontainer-config-file  (Note: New-AzureRmWebApp doens't have any option to pass the multicontainer config )
2. creating the Linux app plan using powershell (New-AzureRmAppServicePlan doesn't have any option to say 'Linux'.  I can workaround by using New-AzureRmResource )
3. ~~getting the query key of azure search using powershell.~~  ([moved](https://github.com/Azure/azure-powershell/issues/7130))

I believe that developers should use the tool that best fit into their workflow. So, it's important to provide the same functionalities in both tools.  

What are the plan to support those linux command in Powershell? I have checked the documentation a few times but let me know if I miss out something. Thanks.

**Comment by maddieclayton** [comment]
I'm going to assign this to the App Service team regarding the first two bullet points. @michaelsync Can you open a new issue for bullet point three? I assume that is for the AzureRM.Search team, but want to be sure.

**Comment by maddieclayton** [comment]
@panchagnula Can you take a look at the first two bullet points of this issue?

**Comment by panchagnula** [comment]
@michaelsync , short answer is that for Linux, CLI was prioritized over Powershell. I am adding the Linux feature owner to comment on this.

@rramachand21 - can you share the timelines if any we have for having this support on Powershell as well.

**Comment by michaelsync** [comment]
@panchagnula Thanks. Someone in Powershell advisor said that there are some missing things in CLI too. Example: https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/34835497-manage-owner-of-groups-through-az-cli

Can we say some features are available in CLI only and some are available in Powershell only? (not in sync basically). 

Do we have any documentation on what feature is available in CLI and what are available in Powershell Aure? So we don't need to speed so much time on researching and ended up not having any solution. 

@rramachand21 It would be great if you can share the timeline to sync between those twos with us.

**Comment by panchagnula** [comment]
@michaelsync i can speak regarding the AppService Linux commands availability on CLI & PowerShell only, the other feedback link you provided is group management commands so i cannot comment on those.
Your best place for documentation is https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest & https://docs.microsoft.com/en-us/powershell/module/azurerm.websites/set-azurermwebapp?view=azurermps-6.8.1&viewFallbackFrom=azurermps-5.0.0

**Comment by michaelsync** [comment]
@panchagnula Thanks.  For documentation, it doesn't say what is missing or in the pipeline.  That's why I think it would be really helpful for us if there is a doc about whats' missing in CLI/Powershell.  

Eg: 
Title: Web App 
Commands/Parameters                  |    CLI                  | Powershell Azure   
-----------------------------------------------------------------------------------------------------                    
--multicontainer-config-type         |    Yes                  | coming in vxxx (around Aug)
--multicontainer-config-file           |    Yes                  | Not coming ever. 

@rramachand21 any update?

**Comment by michaelsync** [comment]
Hi @rramachand21 Any update on the timeline? 

Hi all, It would be great if someone can help me to get a hold of Ranjith. :-) Thanks.

**Comment by panchagnula** [comment]
we don't have a timeline to share at this point - we will update the thread when we have more details here. Thanks!

**Comment by panchagnula** [comment]
Closing this since this is a question - we do have plans to add some basic create functionality for Linux.
