### ISSUE TITLE
Select-AzureRmSubscription : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input

### ISSUE THREAD

**Issue by claudiafergus** [Azure/azure-powershell#7116]
Issue with cmdlet. It used to work, however it no longer works and you need to revise your scripts. The following command throws an error.
Get-AzureRmSubscription -SubscriptionName $SubscriptionName | Select-AzureRmSubscription

Error: Select-AzureRmSubscription : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.

Resolution:
Replace this:
Get-AzureRmSubscription -SubscriptionName $SubscriptionName | Select-AzureRmSubscription
With this:
Select-AzureRmSubscription -SubscriptionName $SubscriptionName

$PSVersionTable
Name Value

PSVersion 5.1.17134.228
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.17134.228
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

**Comment by maddieclayton** [comment]
@claudiafergus I am not able to replicate this in the current version of AzureRM.  When I run this: 
```Get-AzureRmSubscription -SubscriptionName "Test Account" | Select-AzureRmSubscription```
I successfully change subscriptions.  What do you get as the output of ```Get-AzureRmSubscription -SubscriptionName $SubscriptionName```?

**Comment by markcowl** [comment]
Closing as no repro.  If you are still seeing this issue, please open a new issue.
