### ISSUE TITLE
Azcopy on Automation Runbook

### ISSUE THREAD

**Issue by AkshayAzure** [Azure/azure-powershell#7122]
When will Azcopy for Azure Automation runbook available?

**Comment by maddieclayton** [comment]
@vrdmr Can you take a look at this feature request?

**Comment by andyw248** [comment]
The documentation article at: https://docs.microsoft.com/en-us/azure/automation/automation-runbook-execution#where-to-run-your-runbooks explains some limitations that apply when running runbook jobs on sandboxes in the cloud. Following the documentation article at: https://docs.microsoft.com/en-us/azure/storage/scripts/storage-common-transfer-between-storage-accounts, it might be possible to use AzCopy from a runbook that runs on a hybrid worker.
