### ISSUE TITLE
getting the query key of azure search using powershell

### ISSUE THREAD

**Issue by michaelsync** [Azure/azure-powershell#7130]
This issue is opened as requested in this issue https://github.com/Azure/azure-powershell/issues/7096#issuecomment-417417813. 

I am able to get the query key of search easily using CLI.  but I am not able to find a way to do it in Powershell. 

`: az search query-key list --resource-group "mssql16ag" --service-name "mstestsearch"`

Does it support in Powershell? if not, please let us know the timeline on when we are going to get this in PS.

**Comment by maddieclayton** [comment]
@felixwa Can you take a look at this issue?

**Comment by felixwa** [comment]
$queryKey1 = $newSearchService | Get-AzureRmSearchQueryKey
		$queryKey2 = Get-AzureRmSearchQueryKey -ParentResourceId $newSearchService.Id
		$queryKey3 = Get-AzureRmSearchQueryKey -ResourceGroupName $rgname -ServiceName $svcName

**Comment by maddieclayton** [comment]
@michaelsync Does this answer your question?

**Comment by michaelsync** [comment]
@maddieclayton @felixwa 

I see. I wasn't aware of this command. It doesn't show up in my current azure module. I will do the upgrade to see. Thanks.

**Comment by leszekkoc** [comment]
Is this command:
Get-AzureRmSearchQueryKey -ResourceGroupName $rgname -ServiceName $svcName
supported on Windows? 
I am trying to run it in AzureDevOps and is not recognized command for PowerShell version 6.7.0.

**Comment by AndreasM009** [comment]
I have the same problem. Get-AzureRmSearchQueryKey is not recognized as a command.

**Comment by felixwa** [comment]
@michaelsync @leszekkoc @AndreasM009 
TRY **Install-Module Az.Search** if you the command is not recognized.
