### ISSUE TITLE
Lacking Azure Powershell cmdlet to deploy function apps

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-powershell#7133]
_From @brandonh-msft on August 31, 2018 17:49_

There are things we can do with Azure PowerShell that we can't do with Azure CLI - for instance, [create Application Insights resources](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-powershell) in Azure.

This means to automate the deployment of a Function app + Application Insights, I've got to use two different CLIs; Azure PowerShell and Azure CLI. If Functions were deployable with Azure PowerShell, we could do this all within one environment and, more importantly, **one login prompt**.

If this is possible today, then we need to have instructions [in our docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli) on the necessary commands to make it happen.

_Copied from original issue: Azure/azure-functions-core-tools#686_

**Comment by brandonh-msft** [comment]
I have worked around this by using the [Run-From-Zip functionality and its associated REST deployment capability](https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push#rest). However this is 100% outside the func cli which begs the question why have build/deploy capabilities even in it.

**Comment by markcowl** [comment]
@JasonRShaver @panchagnula Can you folks comment on the plans for Azure PowerShell support for Azure functions?

**Comment by cormacpayne** [comment]
Closing, this is currently in our backlog.
