### ISSUE TITLE
[Storage] for a breaking release, Should Change the default parameterSet for New-AzureStorageContext to 

### ISSUE THREAD

**Issue by blueww** [Azure/azure-powershell#7143]
Use the issue to track ：
We have added Oauth support to Powershell, but left a change need breaking change.
We should add the change when a release allows breaking comes.

The change is: 
To Support create Oauth storage context with only storage account name as following, we should change the default parameterSet to "OAuthParameterSet"

1.	$ctx = New-AzureStorageContext -StorageAccountName $accountName

**Comment by andyjballgit** [comment]
Hi there, 

So does this mean its not working at the moment with oAuth ? as per below I get an error . If I miss off the UseConnectedAccount , ie get prompted for StorageKey 


$Context = New-AzureStorageContext -StorageAccountName $StorageAccount -UseConnectedAccount

CommandType     Name                                               Version    Source                               
-----------     ----                                               -------    ------                               
Cmdlet          New-AzureStorageContext                            4.6.1      Azure.Storage                        
New-AzureStorageContext : Invalid URI: The hostname could not be parsed.
At C:\Users\admin-aba\scripts\repos\ASIAzureGeneral\Helper\Storage\UploadBlobUsingOauth.ps1:5 char:12
+ $Context = New-AzureStorageContext -StorageAccountName $StorageAccoun ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureStorageContext], UriFormatException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Storage.Common.Cmdlet.NewAzureStorageContext

**Comment by blueww** [comment]
Powershell works with Oauth now.

But you need to use -UseConnectedAccount to use Oauth.

$Context = New-AzureStorageContext -StorageAccountName $StorageAccount -UseConnectedAccount


After this breaking change of change default parameter set (in a future release that allows breaking), customer can use oauth without specify -UseConnectedAccount.

$Context = New-AzureStorageContext -StorageAccountName $StorageAccount


Thanks!
Wei Wei

**Comment by andyjballgit** [comment]
Hi Wei Wei 

Sorry, I deleted my post as I realised I had somehow messed up name of storage account - it had a space in it.. , but you were too quick for me :-)

but I did notice that the help from the cmdlet is slightly wrong , as doesn't mention requirement to have the -UseConnectedAccount switch included

   Example 10: Create a context by using the OAuth Authentication
    
    C:\PS>Connect-AzureRmAccount
    C:\PS> $Context = New-AzureStorageContext -StorageAccountName "myaccountname"

**Comment by blueww** [comment]
@andyjballgit 
Thanks for raise the help issue!
I have send a PR to fix it: https://github.com/Azure/azure-powershell/pull/7676/files

**Comment by andyjballgit** [comment]
ah awesome thx !

**Comment by blueww** [comment]
The PR is merged, and this will be fixed in Az 1.0 release.
