### ISSUE TITLE
functionapp:Add az function to Azure PowerShell that mimics az command functionality

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-powershell#7147]
Related issue: https://github.com/Azure/azure-cli/issues/7218.

It would be very useful to have an az function in PowerShell that mimics the az CLI functionality, internally invoking the equivalent PowerShell command to get the task done, and showing the PowerShell command(s) that are invoked when run with -WhatIf.

For example, a long time ago I built a dir function (not an alias, a function) in PowerShell to bridge the gap between cmd.exe's dir and PowerShell's Get-ChildItem. Here's a screenshot showing what that looked like:

![image](https://user-images.githubusercontent.com/3515485/45165475-4a6dfe00-b1cb-11e8-8706-bdc60ddcce37.png)

Today I would do it differently, automatically invoking the command when run, and using -WhatIf (and/or -Verbose) to show the PowerShell equivalent for learning purposes.

## Why is this needed?

The Azure CLI has certain limitations that Azure PowerShell does not. For example, you cannot control session caching in Azure CLI, but you can in PowerShell. This is imperative when using Azure PowerShell in locations where you need to avoid process-level or disk caching of a session, such as Azure Functions (due to asynchronous invocation). Yet there are many examples of Azure CLI out there, and some users are more comfortable working with Azure CLI than with PowerShell, so why not bridge the gap? For functionality in the az.cmd utility that is not in PowerShell, if az.cmd is installed, a warning message could be displayed informing the user that they need to invoke the az command directly using az.cmd to use that feature/functionality.

If a schema for az.cmd is published, this could be built/maintained by the community, but given the speed of updates for Azure PowerShell and az.cmd, I think this would be better if it was built-in, managed as part of the Azure PowerShell releases, with the community contributing changes via PRs to the function as needed.

**Comment by markcowl** [comment]
@JasonRShaver @panchagnula Can you folks fill Kirk in on current plans for implementing Azure Functions in Azure PowerShell?

**Comment by panchagnula** [comment]
@KirkMunro we do have plans to add FunctionApp creation & management commands that CLI currently supports. i.e these https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest
 
Don't have a firm ETA to share at this point. CCing Functions PM as well @dariagrigoriu

**Comment by KirkMunro** [comment]
@panchagnula: Thank you, that will be very useful for PowerShell.

@markcowl: While I appreciate you passing that request on (which I was curious about), it wasn't the actual ask here. What I'm requesting is the addition of a PowerShell function to Azure PowerShell that would be named "az" that maps the az CLI to PowerShell cmdlets. This would provide three benefits:

1. It would allow end users to learn the PowerShell equivalent of az commands (i.e. if you found an Azure CLI command somewhere that you wanted to use in a script you could just invoke it as is, and behind the scenes the PowerShell equivalent would be invoked, giving you rich objects to automate with, and helping you learn the PowerShell command when all you found while searching for how to do a task was the Azure CLI command).
1. It also allow az commands to be used interchangeably with PowerShell commands, which you cannot do today (e.g. Connect-AzureRmAccount ...; az group list)
1. It would allow az commands to be used in environments where the Azure CLI cannot be installed (e.g. Azure Functions).

Right now these two CLI environments are being built/supported independently of one another, but PowerShell is well positioned to act as a superset of the two, if it had an az function that would mimic/map the az CLI to PowerShell.

**Comment by KasperHoldum** [comment]
Any progress or ETA on this?

**Comment by dcaro** [comment]
@KasperHoldum we have released a module in preview for Azure Functions  https://www.powershellgallery.com/packages/Az.Functions/0.0.1-preview and are working on having a new preview soon. We have few issues tracking this effort: https://github.com/Azure/azure-powershell/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%5Baz.functions%5D 
On a more general note, you should see more services covered in the coming month (for example, we recently released a preview for CosmosDB).

Since this effort is being tracked in the other issues mentioned above, I will close this one. Feel free to leave a comment if you think otherwise.

**Comment by dcaro** [comment]
Hi @KasperHoldum, @KirkMunro 

The Azure PowerShell product team is looking for customers who are willing to try some of the newest Azure PowerShell features for Azure Functions and provide feedback.

If you are interested in talking with Azure PowerShell product team on this topic, fill out this short survey (https://microsoft.qualtrics.com/jfe/form/SV_0PATZ9XFWS8S82V?Q_CHL=github) and include your email at the end. We will contact you to set up a Teams call if you are a good fit for this study.

Thank you!
Damien
