### ISSUE TITLE
Incorrectly checking generic type arguments in breaking change tool

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#7151]
The breaking change tool is only checking nested types by name. It should do the same property-style check it does for non-generics.

See:
https://github.com/Azure/azure-powershell/blob/preview/tools/StaticAnalysis/BreakingChangeAnalyzer/TypeMetadataHelper.cs#L478-L481 

Should be using this method to compare types:
https://github.com/Azure/azure-powershell/blob/preview/tools/StaticAnalysis/BreakingChangeAnalyzer/TypeMetadataHelper.cs#L58

**Comment by cormacpayne** [comment]
Also need to improve how we compare output and parameter types when the name changes (_e.g._, going from `Site` to `PSSite` is flagged as a breaking change immediately without comparing the properties).

**Comment by cormacpayne** [comment]
Both issues mentioned above have been fixed.
