### ISSUE TITLE
Shared resources for storage data plane tests.

### ISSUE THREAD

**Issue by NelsonDaniel** [Azure/azure-powershell#7162]
### Description

- [ ] Share resource group and storage account for every test. Probably sharing context between tests with  [class fixture](https://xunit.github.io/docs/shared-context.html).

Minor Improvement:

- [ ]  Set properties and add CORS rules together, and run a wait function for the change updated in server.

**Comment by cormacpayne** [comment]
Closing as won't fix 🗡
