### ISSUE TITLE
Disconnect-AzureRmAccount should never fail when you are not connected

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-powershell#7167]
### Description

If you are not connected to Azure with Azure PowerShell, and you invoke Disconnect-AzureRmAccount, you get an error telling you that you need to connect first.

This is a poor design that encourages invocation with -ErrorAction Ignore. You would never, ever connect just to disconnect, and when all you want to do is make sure you are disconnected, you should be able to invoke this cmdlet without getting an error. Errors should only be raised if you are connected and for some reason it fails to disconnect you (if that's even possible).

If you really want something, maybe have it output a verbose message indicating you're not connected, but that's all that is necessary here.

### Script/Steps for Reproduction

```powershell
Disconnect-AzureRmAccount
```

### Module Version

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.3.3      AzureRM.Profile                     {Add-AzureRmEnvironment, Clear-AzureRmContext, Clear-Azure..
```

### Environment Data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.17134.165
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.165
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

``
DEBUG: 3:02:51 AM - DisconnectAzureRmAccountCommand begin processing with ParameterSet 'ContextName'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a

Confirm
Run Connect-AzureRmAccount to login.
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a
Disconnect-AzureRmAccount : Run Connect-AzureRmAccount to login.
At line:1 char:1
+ Disconnect-AzureRmAccount -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Disconnect-AzureRmAccount], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.DisconnectAzureRmAccountCommand

DEBUG: AzureQoSEvent: CommandName - Disconnect-AzureRmAccount; IsSuccess - False; Duration - 00:00:02.3591663;
Exception - System.Management.Automation.PSInvalidOperationException: Run Connect-AzureRmAccount to login.
   at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.get_DefaultContext()
   at Microsoft.Azure.Commands.Profile.DisconnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 3:02:54 AM - DisconnectAzureRmAccountCommand end processing.
DEBUG: 3:02:54 AM - DisconnectAzureRmAccountCommand end processing.
```

**Comment by markcowl** [comment]
@KirkMunro Agreed

**Comment by cormacpayne** [comment]
Fix found in https://github.com/Azure/azure-powershell/pull/7684

**Comment by cormacpayne** [comment]
The fix for this will be available in the next release (2018-11-06).
