### ISSUE TITLE
Get-AzureRmResource does not return roleInstances of cloud service after 6.0.0

### ISSUE THREAD

**Issue by chiweihuang** [Azure/azure-powershell#7169]
### Description

The following Get-AzureRmResource commands returns nothing after version 6.0.0. It works fine with AzureRm.Resource version 5.5.2. Verified that the latest AzureRM returns nothing as well.

The Request absolute uri has changed:
5.5.2:
GET /subscriptions/f1ea63de-afc7-4dc5-90cb-c7d1d39e3e1f/resourceGroups/NoREv2Test/providers/Microsoft.ClassicCompute/domainNames/MyNoR/slots/staging/roles/NotificationReceiver/roleinstances?api-version=2016-11-01 HTTP/1.1
6.0.0
GET /subscriptions/f1ea63de-afc7-4dc5-90cb-c7d1d39e3e1f/providers?api-version=2018-05-01 HTTP/1.1

### Script/Steps for Reproduction

```powershell
Get-AzureRmResource -ResourceId ($resourceid + '/slots/$slot/roles/$roleName/roleinstances') -ApiVersion '2016-11-01'
```

### Module Version
AzureRM.Resource verion:
5.5.2 - working
6.0.0 ~ latest - return nothing

```powershell
Get-Module -ListAvailable
```

### Environment Data

Name                           Value                                                                                                                                                                                                
----                           -----                                                                                                                                                                                                
PSVersion                      5.1.17134.228                                                                                                                                                                                        
PSEdition                      Desktop                                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                              
BuildVersion                   10.0.17134.228                                                                                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                  
SerializationVersion           1.1.0.1

```powershell
$PSVersionTable
```

### Debug Output

By setting $DebugPreference='Continue', looks like instead of returning nothing, it actually returns all the available resources.

```

```

**Comment by markcowl** [comment]
@chiweihuang I don't see any registration for domainNames/slots/roles/roleInstances  when I run

```powershell
Get-AzureRmResourceProvider -ProviderNamespace Microsoft.ClassicCompute -Pre | select -ExpandProperty ResourceTypes
```

DO you have available API versions for this resource type when you run the cmdlet for your subscription?

**Comment by chiweihuang** [comment]
From the successful call using version 5.5.2, the absolute uri is the following:
GET /subscriptions/f1ea63de-afc7-4dc5-90cb-c7d1d39e3e1f/resourceGroups/NoREv2Test/providers/Microsoft.ClassicCompute/domainNames/MyNoR/slots/staging/roles/NotificationReceiver/roleinstances?api-version=2016-11-01 HTTP/1.1

Is this "api-version=2016-11-01" in uri what you are referring to?

**Comment by chiweihuang** [comment]
Our goal is to monitor the instances status, and to move on to further operations only when all the instances are up & running. If this does not work, could you please suggest an alternate way to do so?
I tried something like below:
    $staging = Get-AzureRmResource -Verbose -ResourceId ($ResourceId+'/slots/staging') -ApiVersion '2016-11-01'
    if ($staging.Properties.status -ne 'Running')
but seems like even if the status is running, it does not indicate instances role start complete.

**Comment by markcowl** [comment]
@chiweihuang The generic cmdlets are really the only way to deal with classic resources.  Is this still working in 5.5.2?  Tryign to determine if this was a resource3 chnage on the service, or a change in the cmd,et.

**Comment by chiweihuang** [comment]
What I found out is that it works with AzureRM 5.7.0 (AzureRM.Resources 5.5.2) but starting from AzureRM 6.0.0 (AzureRM.Resources 6.0.0), the same command stopped working.
Yes the /slots/$slot/roles/$roleName/roleinstances' is simplified from my actual query. The exact step to reproduce: 
Get-AzureRmResource -Verbose -ResourceId '/subscriptions/f1ea63de-afc7-4dc5-90cb-c7d1d39e3e1f/resourcegroups/test/providers/Microsoft.ClassicCompute/domainNames/chiweitest/slots/production/roles/ContosoAdsWorker/roleInstances' -ApiVersion '2016-11-01'

**Comment by cormacpayne** [comment]
This has been fixed and will be available in the next release (2018-11-06).
