### ISSUE TITLE
Invoke-AzureRmVmCommand Port

### ISSUE THREAD

**Issue by ponsakthi** [Azure/azure-powershell#7175]
What port of the target VM is used to run InvokeAzureRmVmCommand? What underlying protocol is used?
I am locking down all ports on my VM for security purposes in production network. I wanted to know if I had to open any extra ports/protocols on NSG to allow InVokeAzureRmVM command.

**Comment by markcowl** [comment]
@ponsakthi I believe that this is done through the resource manager endpoint, meaning that no open ports are required.

Adding @hyonholee to confirm

**Comment by hyonholee** [comment]
@koralski

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
