### ISSUE TITLE
New-AzureBatchPool reference example 2 not working

### ISSUE THREAD

**Issue by dedreira** [Azure/azure-powershell#7177]
Hi all,

I'm trying to make work the example number 2 of the New-AzureBatchPool powershell command reference help page:

Get-Help New-AzureBatchPool -Examples

 $imageReference = New-Object -TypeName "Microsoft.Azure.Commands.Batch.Models.PSImageReference" -ArgumentList @("WindowsServer", "MicrosoftWindowsServer", "2016-Datacenter", "*")
 $configuration = New-Object -TypeName "Microsoft.Azure.Commands.Batch.Models.VirtualMachineConfiguration" -ArgumentList @($imageReference, "batch.node.windows amd64")
 New-AzureBatchPool -Id "MyPool" -VirtualMachineSize "Small" -VirtualMachineConfiguration $configuration -TargetDedicatedComputeNodes 3 -BatchContext $Context

And I'm always receiving the error message: New-AzureBatchPool : Operation returned an invalid status code 'BadRequest'

As example 1 works like a charm, I'm starting to believe that the problem could reside in the object PSVirtualMachineConfiguration . . . anyone knows how to make it work?

Thanks in advance!

Regards.

**Comment by MicahMcKittrick-MSFT** [comment]
Following :)

**Comment by cormacpayne** [comment]
@matthchr  Hey Matthew, would you mind taking a look at this issue?

**Comment by matthchr** [comment]
@brnleehng looked into this and I believe the theory is that the sample is using `small` as a VM size, but you actually can't use `small` you have to use `standard_a1` or `standard_d1` (`small` is for CloudServiceConfiguration).

I'll fix this shortly in the actual documentation but in the meantime it sounds like you can just use a different VM size and it should work.

**Comment by dedreira** [comment]
Hey! It worked!! thanks for the info, I truly appreciate it :)

One more thing, I had to modify another line of the example, because I was having this error:

**New-Object : Cannot find type [Microsoft.Azure.Commands.Batch.Models.VirtualMachineConfiguration]**: verify that the assembly containing this type is loaded.
At ...\CreateBatchPool.ps1:33 char:18
+ ... iguration = New-Object -TypeName "Microsoft.Azure.Commands.Batch.Mode ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
 
New-AzureBatchPool : **Cannot validate argument on parameter 'VirtualMachineConfiguration'. The argument is null or empty. Provide an argument that is not null or empty, and then try the 
command again.**
At ...\CreateBatchPool.ps1:34 char:104
+ ... chineSize "Small" -VirtualMachineConfiguration $configuration -Target ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzureBatchPool], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Batch.NewBatchPoolCommand


I think that the problem was that the PowerShell object needed to instantiate the VirtualMachineConfiguration property of the Pool is not "**Microsoft.Azure.Commands.Batch.Models.VirtualMachineConfiguration**" but 
"**Microsoft.Azure.Commands.Batch.Models.PSVirtualMachineConfiguration**"
when I changed it, it started to work! 

Again, thanks a lot guys :)

Regards!
