### ISSUE TITLE
Make cursor display in Azure Powershell

### ISSUE THREAD

**Issue by shamglam** [Azure/azure-powershell#719]
I tried searching on the issue list for this, but couldn't find any reference or reason why. But would it be possible to make the cursor visible default in the azure powershell window, because it is visible by default in regular powershell windows. 

If not, what is the reason for it being hidden?

I know I can probably update a profile file and make it visible but doing this many places is annoying.

**Comment by pcgeek86** [comment]
Need clarity on this .... 

- How do you reproduce the behavior?
- What does the missing cursor look like? (screenshots are often helpful)
- Why are you assuming this is a problem with Azure PowerShell?
- What other modules do you have installed and/or imported?
- Do you have a profile script(s) defined?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by pcgeek86** [comment]
Test post

**Comment by markcowl** [comment]
@shamglam Closing as there has been no response.  Please reopen with additional repro dataas Trevor specifies if this is till an issue for you.

**Comment by yaananth** [comment]
Hey guys, I can still see the issue.
There has been solutions posted..
http://stackoverflow.com/questions/25394160/how-to-show-cursor-in-powershell

I am using azure power shell 0.9.5
Repro is just that I opened the powershell and I don't see any blinking cursor.

![image](https://cloud.githubusercontent.com/assets/12280011/9664109/edf7ca68-5235-11e5-8df1-747cbd2861e7.png)

After setting cursor size, I see blinking cursor now

![image](https://cloud.githubusercontent.com/assets/12280011/9664144/154fc5b6-5236-11e5-8b48-956fdca32091.png)

**Comment by devigned** [comment]
This happens all the time for me and is quite frustrating. 

@yaananth seems like this would be a cool pull request. Are you interested?

**Comment by jeff881208** [comment]
I think you need to give the default Cursor size.

**Comment by stankovski** [comment]
Fixed in dev branch (#936). Will be available in the upcoming release.
