### ISSUE TITLE
Calling Set-AzureServiceDiagnosticsExtension with Role parameter fails

### ISSUE THREAD

**Issue by dontjee** [Azure/azure-powershell#72]
I'm trying to set Azure diagnostics on a deployed cloud service using v0.8.11 Azure Powershell cmdlets and the Set-AzureServiceDiagnosticsExtension command:

    Set-AzureServiceDiagnosticsExtension -StorageContext $storageContext -DiagnosticsConfigurationPath $diagnosticsConfiguration.FullName -ServiceName $serviceName -Slot Production -Role "MyService.Web"-Verbose

Doing so I get the following error

    Exception: Microsoft.WindowsAzure.CloudException: BadRequest: The extension ID
    MyService.Web-PaaSDiagnostics-Production-Ext-0 is invalid.
       at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
    task)
       at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task
    task)
       at Microsoft.WindowsAzure.HostedServiceOperationsExtensions.AddExtension(IHo
    stedServiceOperations operations, String serviceName,
    HostedServiceAddExtensionParameters parameters)
       at Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.ExtensionMan
    ager.AddExtension(HostedServiceAddExtensionParameters extensionInput)
       at Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.ExtensionMan
    ager.InstallExtension(ExtensionConfigurationInput context, String slot,
    ExtensionConfiguration extConfig)
       at Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.SetAzureServ
    iceDiagnosticsExtensionCommand.ExecuteCommand()
       at Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.SetAzureServ
    iceDiagnosticsExtensionCommand.OnProcessRecord()
       at Microsoft.WindowsAzure.Commands.Utilities.Common.CloudBaseCmdlet`1.Proces
    sRecord()
       at System.Management.Automation.Cmdlet.DoProcessRecord()
       at System.Management.Automation.CommandProcessor.ProcessRecord()
        + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
       tion
        + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
       n,UpdateDiagnosticsBuildStep.ps1

It works when I don't use the "-Role" parameter but then I have to call Remove-AzureServiceDiagnosticsExtension for each role prior to calling the Set command which adds 2-3 minutes per role to the script execution time.

The Role parameter matches my role name in the Azure Cloud Service. Am I doing something wrong or is this a bug?

**Comment by markcowl** [comment]
Thanks for the report of this issue, assigning appropriately

**Comment by huangpf** [comment]
Note: this issue is about the invalid character of ```.``` used in the extension ID, while in #387 it's about the length of extension ID. Since we have seen quite a few issues about extension IDs recently, we would try to triage them together and come up with a more generic solution for them altogether.

**Comment by singhkay** [comment]
@huangpf IIRC we rolled out an extension ID fix in one of the last releases. Does that fix this issue?

**Comment by ivanz** [comment]
I have 0.9.5 installed here and still seeing the same error (however the "." are stripped):

```
Hyak.Common.CloudException: BadRequest: The extension ID MarketInvoicePaymentGatewayFileDownloader-PaaSDiagnostics-Staging-Ext-0 is invalid.

```

**Comment by huangpf** [comment]
@ivanz It seems it's because the extension ID string is too long. @hyonholee

@singhkay We shall provide an option for users to specify this value, in order to unblock similar issues.

**Comment by praneetloke** [comment]
Just hit this error with VSO vNext build system. Is there an updated version of azureps that has an option to get around this?

**Comment by huangpf** [comment]
@praneetloke Is it feasible for you to remove the empty spaces (or any characters that are not accepted by the extension ID format) from role name?

As for the issue of spaces described here, there is an upcoming Compute PS module release around this week. I think @hyonholee can share more details if needed.

**Comment by praneetloke** [comment]
@huangpf thank you for your reply. It actually looks like the PS module is stripping "." from my role name and smashing them together. I think I am hitting the scenario where the name is too long. I am trying to get around that. The version of the PS module is 0.9.8.1.

**Comment by ChristianJensen** [comment]
I'm hitting this issue in the VSTS vNext RM bits, when trying to deploy an Azure Cloud Service. Getting the same error as @ivanz. Any update if this will be fixed? I have a fairly long Cloud service role name.

**Comment by huangpf** [comment]
+@hyonholee 

It should be fixed in the latest release version ```1.0.x```. May I know what's your PS version?

**Comment by ChristianJensen** [comment]
I'm seeing this when running the Azure cloud service deployment task in VSTS, from release management

**Comment by huangpf** [comment]
@ChristianJensen 
Could you please contact the VSTS team, as we are not sure which version they use?

**Comment by ChristianJensen** [comment]
OK, will do, tnx

**Comment by praneetloke** [comment]
Tried to kick-off a build today and saw that VSTS agent uses 0.9.8.1.
`
2015-12-10T21:38:49.4976981Z AzurePSCmdletsVersion= 0.9.8.1
`

**Comment by huangpf** [comment]
@praneetloke @ChristianJensen 
No, it's not fixed in ```0.9.8.1```, from the logs shown here:

https://github.com/Azure/azure-powershell/blob/67e4d143e399c87538c5b3f6d2ea788815a0e412/src/ServiceManagement/Compute/Commands.ServiceManagement/Extensions/Common/ExtensionRole.cs

It's fixed in any official release after this one.

**Comment by praneetloke** [comment]
Quick update on this. VSTS is now using 1.0.x AzurePS. My build is now successfully deploying.

**Comment by huangpf** [comment]
@praneetloke Thanks for confirming. Close this issue for now.
