### ISSUE TITLE
Powershell for Virtual Network Taps

### ISSUE THREAD

**Issue by neaggarwMS** [Azure/azure-powershell#7206]
### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by maddieclayton** [comment]
@neaggarwMS Closing because there is no description.  Please reopen with a full description of what this issue is about.
