### ISSUE TITLE
DMS: Add powershell support for synchronous migrations for api version 2018-07-15-preview

### ISSUE THREAD

**Issue by huang91shu** [Azure/azure-powershell#7207]
# Feature Name

## Planned PowerShell Release Milestone

- Please see the [release milestones](https://github.com/azure/azure-powershell-cmdlet-review-pr/milestones) for a full list of upcoming milestones

    - ` 2018-09-17 - Ignite `

## Service Release Details

- Is this an Embargoed Preview, A Public Preview, or a General Release?

    - ` Public Preview `

- What is the expected service release date?

    - ` Already released.  API Version - 2018-07-15-preview `

## Contact Information

- Main developer contacts (emails + github aliases)

    - ` shuhuan(huang91shu), hijava(hitenjava), sichoudh(sichoudh) `

- PM contact (email + github alias) 

    - ` rajpo `

- Other people who should attend a design review (email)

    - `akashv`

## High Level Scenarios

- Describe how your feature is intended to be used by customers.

    - This new migration type allows an ongoing migration to continuously sync changes between the source and target until the customer completes the migration.  This new scenario currently supports two source-target pairs.  1)  Sql -> SqlDb, 2) MySql -> MySqlAzure

- Piping scenarios / how these cmdlets are used with existing cmdlets

    - Existing powershell design, Previous milestone release: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/41

- Sample of end-to-end usage

```
$migTask = New-AzureRmDmsTask -TaskType MigrateSqlServerSqlDbSync `
    -ResourceGroupName $rg.ResourceGroupName `
    -ServiceName $service.Name `
    -ProjectName $project.Name `
    -TaskName $taskName `
    -SourceConnection $sourceConnectionInfo `
    -SourceCred $sourceCred `
    -TargetConnection $targetConnectionInfo `
    -TargetCred $targetCred `
    -SelectedDatabase  $selectedDbs

$task = Get-AzureRmDataMigrationTask -ResourceGroupName $rg.ResourceGroupName -ServiceName $service.Name -ProjectName $project.Name -TaskName $taskName -Expand

while(($task.ProjectTask.Properties.State -eq "Running") -or ($task.ProjectTask.Properties.State -eq "Queued")) {
	Foreach($output in $syncTask.ProjectTask.Properties.Output) {
	        if ($output.Id -clike "db|*") {
			Write-Host ($output | Format-List | Out-String)

			if ($output.MigrationState -eq "READY_TO_COMPLETE") {
				$command = New-AzureRmDmsCommand -CommandType Complete `
					-ResourceGroupName $rg.ResourceGroupName `
					-ServiceName $service.Name `
					-ProjectName $project.Name `
					-TaskName $taskName `
					-DatabaseName $output.DatabaseName`
			}
                }
        }

	SleepTask 15
	$task = Get-AzureRmDataMigrationTask -ResourceGroupName $rg.ResourceGroupName -ServiceName $service.Name -ProjectName $project.Name -TaskName $taskName -Expand 
}
```

## Syntax changes

This should include PowerShell-help style syntax descriptions of all new and changed cmdlets, similar to the syntax portion of PowerShell help (or markdown help), for example:

### New Cmdlet

Link to cmdlet help markdown file generated by platyPS or sample syntax:

` PS C:\> New-AzureRmDataMigrationCommand -CommandType <CommandTypeEnum> -ResourceGroupName <String>
 -ServiceName <String> -ProjectName <String> -TaskName <String> [-DefaultProfile <IAzureContextContainer>]
 [-WhatIf] [-Confirm] [<CommonParameters>]
 

PS C:\> New-AzureRmDataMigrationSyncSelectedDB [-TargetDatabaseName <String>] [-SchemaName <String>]
 [-TableMap <System.Collections.Generic.IDictionary`2[System.String,System.String]>]
 [-MigrationSetting <System.Collections.Generic.IDictionary`2[System.String,System.String]>]
 [-SourceSetting <System.Collections.Generic.IDictionary`2[System.String,System.String]>]
 [-TargetSetting <System.Collections.Generic.IDictionary`2[System.String,System.String]>] [-Id <String>]
 [-Name <String>] [-DefaultProfile <IAzureContextContainer>] [<CommonParameters>] `

### Changed cmdlet

The change to existing cmdlets is that there are more task types supported in the existing New-AzureRmDataMigrationTask cmdlet.

The new TaskTypeEnum values supported are - ConnectToSourceSqlServerSync, ConnectToTargetSqlSync, GetUserTablesSqlSync, ValidateSqlServerSqlDbSync, MigrateSqlServerSqlDbSync

-` New-AzureRmDataMigrationTask -TaskType <TaskTypeEnum> -ResourceGroupName <String> -ServiceName <String>-ProjectName <String> -Name <String> [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>] `

## Guidelines

- Do your cmdlets comply with the design guidelines outlined in the [PowerShell Design Guidelines document](https://github.com/Azure/azure-powershell/wiki/PowerShell-Cmdlet-Design-Guidelines)?

    -  yes 

- Do all applicable cmdlets follow the piping guidelines outlined in the [Piping in PowerShell document](https://github.com/Azure/azure-powershell-cmdlet-review-pr/blob/master/documentation/piping-in-powershell.md)?

    -  yes

**Comment by maddieclayton** [comment]
Please move this here: https://github.com/Azure/azure-powershell-cmdlet-review-pr
