### ISSUE TITLE
ARM: Split gallery template cmdlets into its own

### ISSUE THREAD

**Issue by vivsriaus** [Azure/azure-powershell#724]
1. New-AzureResourceGroupGalleryTemplate and Save-AzureResourceGroupGalleryTemplate shouldn't belong under ARM project
2. Remove options to deploy templates from New-AzureResourceGroup cmdlet

**Comment by markcowl** [comment]
@vivsriaus New-AzureResourceGroup template deployment is quite a time-saving feature, especially for so fundamental a customer scenario.  I don't thinbk we want to delete this without serious thought about how it multiplies the cost of entry into ARM for customers.

@devigned Thoughts?
