### ISSUE TITLE
Add ChangeLog.md information to dev guide

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#7251]
Our dev guide doesn't have information mentioning that they need to update their ChangeLog.md. Only our CONTRIBUTING.md mentions it. We don't have information mentioning that you need to add a line(s) under the `Current Release` header.

**Comment by cormacpayne** [comment]
Change the header from `Current Release` to something that is more noticeable

**Comment by cormacpayne** [comment]
Closing as fixed.
