### ISSUE TITLE
New-AzureResourceGroupDeployment is missing the "Syntax" built-in help section

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#729]
Titles says it all. Screenshot offers proof.

![image](https://cloud.githubusercontent.com/assets/466713/9208286/fed0d22a-402f-11e5-9ac5-1d2772c3458d.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ravbhatnagar** [comment]
Fixed
