### ISSUE TITLE
webapp:Support cloning into a RG and ASP combination where ASP !in RG. Portal supports this.

### ISSUE THREAD

**Issue by jocawtho** [Azure/azure-powershell#7297]
### Description
If we have RG3, and RG2 and ASP2 in RG2
Powershell should allow cloning into RG3 and ASP2 

### Script/Steps for Reproduction

```powershell
$srcapp = Get-AzureRmWebApp -ResourceGroupName webappishi -Name webappishi
$destapp = New-AzureRmWebApp -ResourceGroupName funcappishi -Name cloneishi -Location "North Central US" -AppServicePlan ase-asp -ASEName ishita-ase -ASEResourceGroupName ishita-ase -SourceWebApp $srcapp
```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by panchagnula** [comment]
@Nking92 can you please take a look at this issue reported in cloning. Thank you.

**Comment by panchagnula** [comment]
@Nking92 not sure if this was already fixes with this change https://github.com/Azure/azure-powershell/pull/9496 if not can we get this in for the End of July release

**Comment by panchagnula** [comment]
@ThejaChoudary / @Kotasudhakarreddy can one of you check if this still repros? Thanks!

**Comment by ThejaChoudary** [comment]
Taking a look at this.

**Comment by ThejaChoudary** [comment]
@panchagnula Yes I am able to repro it.

**Comment by panchagnula** [comment]
@ThejaChoudary what is the update on this - was this something the API team was looking at?

**Comment by Kotasudhakarreddy** [comment]
@panchagnula - We have raised a clarification to cloning team and waiting to hear back from them.

**Comment by panchagnula** [comment]
@raohri03 can you please update this issue with your findings? Thank you.

**Comment by panchagnula** [comment]
@raohri3 any update on this? Thanks!

**Comment by raohri3** [comment]
Taking care in next spring starting coming monday (8 June)

**Comment by raohri3** [comment]
@panchagnula Actually its already supported but in case of cross resource group clone with serverfarm we need to provide complete serverFarmID of form of form "/subscription/{subscriptionId}/resourceGroup/{resourceGroup}/serverFarm{serverFarmName}"

which is added in error message of clone operation :
https://github.com/Azure/azure-powershell/pull/12176

**Comment by panchagnula** [comment]
@raohri3 thanks. @ThejaChoudary please validate this infact works on our end.

**Comment by ThejaChoudary** [comment]
@panchagnula  verified at our end and able to clone in case of cross resource group 
when we provide AppServicePlan in following format : \" /subscriptions/{subscriptionId}/resourcegroups/{resourcegroupName}/providers/Microsoft.Web/serverfarms/{serverFarmName}\""

**Comment by panchagnula** [comment]
Thanks @ThejaChoudary  & @raohri3 for the help. closing this.
