### ISSUE TITLE
Get-AzureResource: Azure SQL Database malformed request.

### ISSUE THREAD

**Issue by sjwaight** [Azure/azure-powershell#73]
The Cmdlet sends the wrong request to the Azure API.  When I run a tag command via the new portal it sends:

/subscriptions/GUID/resourceGroups/Default-SQL-WestUS/providers/Microsoft.Sql/servers/{servername}/databases/{database}?api-version=2014-04-01

If I make the same request via PowerShell it misses the __/servers/__ node in the path:

/subscriptions/GUID/resourcegroups/Default-SQL-WestUS/providers/Microsoft.Sql/{servername}/databases/{database}?api-version=2014-04-01

**Comment by sjwaight** [comment]
I found a workaround (or maybe the correct usage? hard without documentation)

When specifying -ParentResource argument you must put "servers/{servername}" rather than just "{servername}".

If this is by design then OK for this to be closed.

**Comment by markcowl** [comment]
Thanks for the report of this issue, assigning appropriately

**Comment by markcowl** [comment]
Yes, this is (unfortunately) by design.  You can get the correct format of 'parent resource' by using Get-AzureResource to list the resource properties.
