### ISSUE TITLE
New-AzureResourceGroupDeployment :: Built-in help needs organization

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#730]
The `DESCRIPTION` section of the built-in help for `New-AzureResourceGroupDeployment` is one, massive paragraph of information. This is a little daunting, especially for new users, and should probably be separated into 3-4 logical paragraphs.

![image](https://cloud.githubusercontent.com/assets/466713/9208382/68e52e68-4030-11e5-98a7-fe222d4e17be.png)

Here are some general guidelines on writing paragraphs: https://owl.english.purdue.edu/owl/resource/606/01/.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ravbhatnagar** [comment]
Fix documentation

**Comment by ravbhatnagar** [comment]
Fixed - 3/3 release.
