### ISSUE TITLE
First class Docker support for Az

### ISSUE THREAD

**Issue by sdavis3** [Azure/azure-powershell#7302]
The images in Docker Hub do not have the AzureRM.NetCore pre-installed.

To reproduce issue the following command:
docker run -it azuresdk/azure-powershell-core:latest

Then, once connected to the container, issue the following command:
Import-Module AzureRM.NetCore

The command will return an error. Then, issue the following command:
Install-Module AzureRM.NetCore

After installation completes, you can successfully locate the cmdlets.

This may also be true for AzureRM on the azuresdk/azure-powershell and azuresdk/azure-powershell-core:nanoserver images, but I have not tested it.

This issue is linked to Azure/azure-docs-powershell#732

**Comment by markcowl** [comment]
@sdavis3 AzureRM.Netcore has been replaced by Az.  The docker hub images were only for internal consuption at this point, but we will likely add first class docker hub support after the az 1.0 release.  Saving this issue to track first class Docker support for Az

**Comment by erick-thompson** [comment]
Do we have a Docker image for Az? The PowerShell module, not command line.

**Comment by febinrejoe** [comment]
I am interested in a PowerShell Docker image with Az modules pre-installed as well.

**Comment by VeryEarly** [comment]
Available in mcr.microsoft.com/azure-powershell now, check detail at:

https://hub.docker.com/_/microsoft-azure-powershell

**Comment by febinrejoe** [comment]
Thanks @VeryEarly
