### ISSUE TITLE
New-AzureResourceGroup missing -TemplateParameterUri parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#731]
# Problem

The `New-AzureResourceGroup` command has a `-TemplateUri` parameter, to reference an ARM template at a HTTP URL, but it doesn't offer a similar `-TemplateParameterUri` parameter to point to a web-based parameter file.

# Action Item

Add a `-TemplateParameterUri` parameter to the `New-AzureResourceGroup` and `New-AzureResourceGroupDeployment` commands.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ravbhatnagar** [comment]
All the template deployment related params have been removed from the New-AzureRmResourceGroup cmdlet. Please use New-AzureRmResourceGroupDeployment for template deployment which has this param.
