### ISSUE TITLE
Select-AzureRMContext not working for cmdlet "Get-AzureRmSqlDatabaseBackupLongTermRetentionPolicy"

### ISSUE THREAD

**Issue by garrysinghMS** [Azure/azure-powershell#7318]
I have a script that select a subscription from my account and get Resource Group and for each server/database in the RG, it pulls retention policy.

This works fine for whatever subscription context I select first but when I change context to second subscription, all cmdlets works such as "Get-AzureRMResourceGroup", "Get-AzureRMSQLServer" but does not change the context for "Get-AzureRmSqlDatabaseBackupLongTermRetentionPolicy" and throws RG not found error when it successfully gets the RG using the previous cmdlets.

AzureRM version is 6.8.1

Script I am using is below.

# Create CSV
$folder = "$ENV:UserProfile\Desktop\"
$mfile = New-Item -Path $folder  -Name "SQL.csv" -force 
Add-Content $mfile "SubscriptionName,ResourceGroup,DatabaseName,RetentionPolicy,AppName"

select-azurermcontext -Name 'Subscription Details'

            $rgname = 'rgAlliance'

        # Get all SQL Servers
        $sqlservers = Get-AzureRmSqlServer -ResourceGroupName $rgName 
      
        # SQL Server Loop
        foreach ($sqlserver in $sqlservers){
            
            $sqlservername = $sqlserver.ServerName
            Write-Host Selected Source SQL Server: $sqlserver.ServerName -ForegroundColor Cyan

            # Get all DBs except for master
             $dbs = Get-AzureRmSqlDatabase -ServerName $sqlservername -ResourceGroupName $rgName | Where-Object {$_.DatabaseName -NotLike "master"}
        
            # Database Loop
            foreach ($db in $dbs) {
                
                $dbname = $db.DatabaseName
                $currentPolicy = (Get-AzureRmSqlDatabaseBackupLongTermRetentionPolicy -ServerName $sqlservername -DatabaseName $dbname -ResourceGroupName $rgName -Current).WeeklyRetention
                $tags = (Get-AzureRmResource -ResourceId $db.ResourceId).Tags
                $appName = $tags.appName
                Get-AzureRmResourceGroup -Name $rgName

                Write-Host $db.DatabaseName has policy $currentPolicy
                
                # Export
                $values = $subname+","+$rgName+","+$dbname+","+$currentPolicy+","+$appName
                Add-Content -Path $mfile -Value $values

                Clear-Variable -Name currentPolicy
                Clear-Variable -Name tags
                Clear-Variable -Name appname
       
            } # End DB Loop

        } # End SQL Loop

    #Clear-AzureRMContext

    # Create CSV
$folder = "$ENV:UserProfile\Desktop\"
$mfile = New-Item -Path $folder  -Name "SQL.csv" -force 
Add-Content $mfile "SubscriptionName,ResourceGroup,DatabaseName,RetentionPolicy,AppName"

select-azurermcontext -Name 'Subscription Details'
            
            $rgname = 'bharath'

        # Get all SQL Servers
        $sqlservers = Get-AzureRmSqlServer -ResourceGroupName $rgName 
      
        # SQL Server Loop
        foreach ($sqlserver in $sqlservers){
            
            $sqlservername = $sqlserver.ServerName
            Write-Host Selected Source SQL Server: $sqlserver.ServerName -ForegroundColor Cyan

            # Get all DBs except for master
             $dbs = Get-AzureRmSqlDatabase -ServerName $sqlservername -ResourceGroupName $rgName | Where-Object {$_.DatabaseName -NotLike "master"}
        
            # Database Loop
            foreach ($db in $dbs) {
                
                $dbname = $db.DatabaseName
                $currentPolicy = (Get-AzureRmSqlDatabaseBackupLongTermRetentionPolicy -ServerName $sqlservername -DatabaseName $dbname -ResourceGroupName $rgName -Current).WeeklyRetention
                $tags = (Get-AzureRmResource -ResourceId $db.ResourceId).Tags
                Get-AzureRmResourceGroup -Name $rgName
                $appName = $tags.appName

                Write-Host $db.DatabaseName has policy $currentPolicy
                
                # Export
                $values = $subname+","+$rgName+","+$dbname+","+$currentPolicy+","+$appName
                Add-Content -Path $mfile -Value $values

                Clear-Variable -Name currentPolicy
                Clear-Variable -Name tags
                Clear-Variable -Name appname
       
            } # End DB Loop

        } # End SQL Loop

            Clear-Variable -Name rgName
            Clear-Variable -Name sqlserver
            Clear-Variable -Name sqlservers
            Clear-Variable -Name db
            Clear-Variable -Name dbs

Errors I get is:

Get-AzureRmSqlDatabaseBackupLongTermRetentionPolicy : Resource group 'bharath' could not be found.

Prior to this cmdlet, Get-AzureRMSQLServer gets correct result for RG 'Bharath' so the issue is only limited to the cmdlet "Get-AzureRmSqlDatabaseBackupLongTermRetentionPolicy",

For some reasons this cmdlet does not ack the change in context

If I change the sequence of two subscriptions, whatever subscription runs first will work fine and the one running second will throw RG not found error.

**Comment by cormacpayne** [comment]
@jaredmoo @dealaus would you mind taking a look at this issue?

**Comment by dealaus** [comment]
@garrysinghMS what version of AzureRM.Sql are you using? We had a client caching issue in the past that would explain this problem. That was fixed with [4.7.0-preview](https://www.powershellgallery.com/packages/AzureRM.Sql/4.7.0-preview)

**Comment by dealaus** [comment]
@cormacpayne Interesting. latest AzureRM.Sql in [AzureRm 6.8.1](https://github.com/Azure/azure-powershell/blob/v6.8.1-Auust2018/src/ResourceManager/Sql/Commands.Sql/Database%20Backup/Services/AzureSqlDatabaseBackupCommunicator.cs) does not include the fix for this issue. 

My commit is here https://github.com/Azure/azure-powershell/commit/72ece705

**Comment by jaredmoo** [comment]
AzureRM.Sql.STR (public preview) branch is not and should not be merged to preview (GA) branch. You should make this commit into preview branch.

**Comment by dealaus** [comment]
Yeah, sorry what I meant was merge this commit, aka cherry pick.

**Comment by garrysinghMS** [comment]
> Get-Command -Module AzureRm.Sql -Name Get-AzureRmSqlDatabaseBackupLongtermRetentionPolicy

**Comment by garrysinghMS** [comment]
Sorry I seems to have deleted your comment by mistake. So the AzureRM.SQL version I am using is as follows. 
I believe this is the latest.

CommandType     Name                                               Version    Source                                                                                                           
-----------     ----                                               -------    ------                                                                                                           
Cmdlet          Get-AzureRmSqlDatabaseBackupLongTermRetentionPo... 4.11.3     AzureRM.Sql

**Comment by dealaus** [comment]
@garrysinghMS ok, I have a PR out, but if you'd like an immediate temporary fix you can install 4.7.0-preview which won't have this issue.

**Comment by garrysinghMS** [comment]
Thanks Austin, let me test out (4.7.0-Preview) and update you.

**Comment by garrysinghMS** [comment]
I was able to use 4.7.0-preview as a workaround. Looking forward to the permanent fix on this issue.
Thanks again Austin.
