### ISSUE TITLE
Add Required "Common" support to PowerShell and Core PowerShell AzureRM.Profile modules

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/azure-powershell#7319]
@markcowl  gave me the initial implementation for the common authentication for generated powershell modules.

It is getting to the point where I'm going to need that added in the released versions.

(I'll update this with more details shortly)

**Comment by markcowl** [comment]
Initial stage is done, moving as a placeholder for changes after AutoRest changes have been impleneted
