### ISSUE TITLE
ARM :: Get-AzureVM is capitalizing the ResourceGroupName property value

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#732]
# Problem

The ARM `Get-AzureVM` command is returning an object with the VM's `ResourceGroupName` property value in all caps. Looks unrefined and inconsistent with the rest of ARM.

![2015-08-11 15_43_34-start](https://cloud.githubusercontent.com/assets/466713/9211552/1751ed6a-4040-11e5-8793-517331a772e5.png)

# Expected Result

The `Get-AzureVM` should be returning an unadulterated `ResourceGroupName`.

The design should adhere to item **SC04 - Make Cmdlets Case-Insensitive and Case-Preserving** the "*Strongly Encouraged Development Guidelines*," topic within the PowerShell Design Guidelines.

https://technet.microsoft.com/en-us/library/dd878270(v=vs.85).aspx#SC04

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by trondhindenes** [comment]
FYI: Looks like that's a bug in the underlying rest api and not in the Powershell Cmdlets.

**Comment by pcgeek86** [comment]
@trondhindenes Thanks!! Good call, haven't had a chance to dig into it. Too busy filing additional bug reports. 

How did you find that out, out of curiosity?

Cheers,
Trevor Sullivan

**Comment by trondhindenes** [comment]
I was just working directly with the rest api for some side project just the other day and noticed it. I'm not able to repro 100%, but I'm seeing uper-cased resource group names from time to time when hitting https://management.azure.com{0}/providers/Microsoft.Compute/virtualmachines?api-version=2015-05-01-preview

However, the rg list api (https://management.azure.com/subscriptions/{0}/resourcegroups?api-version=2015-01-01) seems to be returning the correct casing. You can see the same using resources.azure.com by listing vms on the subscription level (not in the context of a resource group)

**Comment by pcgeek86** [comment]
:+1:

**Comment by markcowl** [comment]
@pcgeek86 Thanks for the report assigning appropriately for resolution.

**Comment by singhkay** [comment]
Closing as fixed. Checked on 1.0.3 release.
