### ISSUE TITLE
ARM :: Make Get-AzureResourceProviderLog easier to use

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#733]
# Problem

The Azure Resource Manager (ARM) PowerShell command `Get-AzureResourceProviderLog` is challenging to use in interactive PowerShell sessions.

1. Customers don't know the valid values for the `-ResourceProvider` cmdlet, without separately calling the `Get-AzureResourceProvider` command.
2. Obtaining two `[System.DateTime]` instances for the `-StartTime` and `-EndTime` parameters is quite a bit of extra typing.
3. A common use case for viewing log data is that users will often want to see the *latest* messages, going back <x> number of minutes (or hours, days, etc.).
4. The built-in `DESCRIPTION` help doesn't indicate the scope of log messages that this command retrieves.

# Expected Result

Azure PowerShell commands (both ASM & ARM) should be easy to use for **both** scripting and interactive use.

1. The `-ResourceProvider` parameter should support auto-completion for its parameter values. For down-level PowerShell versions, these could be hard-coded. For current versions of PowerShell, the `Register-ArgumentCompleter` command can be used to dynamically obtain a list of RPs.
2.  Add an additional parameter set that allows the user to specify the "last number of minutes" that they want to retrieve log entries for, instead of requiring a `DateTime` (the existing `DateTime` parameter set should still be an option, however).
3. Fill out the documentation for the `-Caller` parameter. What values can a user specify for this? As of right now, it only says "*Specifies a filter by caller. This parameter is optional. The fault is an empty string (i.e. no filter)*." I have no idea what that means. What is a caller? Should that say "default" instead of "fault?" What can I use as a filter?
4. Get rid of the `-DetailedOutput` parameter. PowerShell commands are supposed to return full, rich objects. If you want to change the default output, use `format.ps1xml` formatting files.
5. Update the `DESCRIPTION` built-in help to discuss the scope of log messages (does this retrieve messages for **all** ARM resource instances, for the specified provider?) and provide user guidance to determine when to use this command, as opposed to one of the other logging commands.

Although I don't see any specific items addressing interactive usability, the PowerShell design guidelines are available here (https://technet.microsoft.com/en-us/library/ms714657(v=vs.85).aspx), for more design assistance. I'll talk to the PowerShell core team separately about getting some interactive guidelines published on the MSDN documentation, that we can later link this feedback to.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ravbhatnagar** [comment]
These are Great suggestions @pcgeek86. I will work with the appropriate team to address some of these, if not all.
For #2, we can still do this as follows - Get-AzureRmLog -ResourceProvider Microsoft.Web -StartTime (Get-Date).AddMinutes(-150) -EndTime (Get-Date)
Not pretty but works.

**Comment by asheniam** [comment]
Please try Get-AzureRmLog and let us know any feedback
