### ISSUE TITLE
Move some Common modules into PowerShell repo

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#7339]
### Description
Move:
 - [x] Microsoft.Azure.PowerShell.Authentication
 - [x] Microsoft.Azure.PowerShell.Authentication.ResourceManager

Into the powershell repository.  Validate whether moving
 - [x] Microsoft.Azure.PowerShell.ScenarioTest

into the powershell repository is feasible

### Cost: 4

**Comment by MiYanni** [comment]
The Authentication.ResourceManager contain namespaces for Profile in it. I'd suggest putting Authentication and Authentication.ResourceManager as projects under Profile (AccountManager).
