### ISSUE TITLE
Republish Management libraries using Newtonsoft.Json 10 in NetStandard

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#7344]
### Description
- [x] Create .NetSDK runtime and test libraries using Newtonsoft.Json 10 in NetStandard
  - [x] Create branch with current runtime test libraries, just using 10.0.3 as lowest Newtonsoft version in netstandard
  - [x] Create private signed librareis for each and publish to yGet gallery
- [x] Gather current set of management libraries used in azure-powershell
- [x]  For each library
   - [x] Use current bits, or tags in azure-sdk-for-net to get commit for appropriate version
  - [x]  Determine appropriate new version for updated package
   - [x] Create signed bits for this library

- [x] Once all management, runtime, and test libraries use the newtonsoft.json 10 dependency in netstandard, publish all these libraries, either to NuGet(preferred) or MyGet feed
- [x] Work with .Net SDK team so that, after all libraries are converted, Newtonsoft.Json 10 will be used for all newly published netstandard libraries

### Cost: 20

**Comment by maddieclayton** [comment]
List of Management Clients
"Microsoft.Azure.Management.Analysis" Version="2.0.3"
"Microsoft.Azure.Management.ApiManagement" Version="4.0.4-preview"
"Microsoft.Azure.Management.ApplicationInsights" Version="0.1.1-preview"
"Microsoft.Azure.Management.Automation" Version="2.0.6"
"Microsoft.Azure.Management.BackupServices" Version="1.0.5-preview"
"Microsoft.Azure.Management.Batch" Version="4.2.0"
"Microsoft.Azure.Management.Billing" Version="2.1.0-preview"
"Microsoft.Azure.Management.Cdn" Version="4.0.1-preview"
"Microsoft.Azure.Management.CognitiveServices" Version="4.1.0"
"Microsoft.Azure.Management.Compute" Version="22.0.0"
"Microsoft.Azure.Management.Consumption" Version="3.0.1.0"
"Microsoft.Azure.Management.ContainerInstance" Version="1.0.2-preview"
"Microsoft.Azure.Management.ContainerRegistry" Version="2.0.0"
"Microsoft.Azure.Management.DataFactories" Version="4.13.2"
"Microsoft.Azure.Management.DataFactory" Version="1.0.0"
"Microsoft.Azure.Management.DataLake.Analytics" Version="3.3.0-preview" 
"Microsoft.Azure.Management.DataLake.Store" Version="2.3.0-preview"
"Microsoft.Azure.Management.DataMigration" Version="0.3.0-preview"
"Microsoft.Azure.Management.DeviceProvisioningServices" Version="0.9.0-preview"
"Microsoft.Azure.Management.DevSpaces" Version="0.9.0-preview"
"Microsoft.Azure.Management.DevTestLabs" Version="2.0.1"
"Microsoft.Azure.Management.Dns" Version="3.0.0" 
"Microsoft.Azure.Management.EventGrid" Version="1.2.0-preview"
"Microsoft.Azure.Management.EventHub" Version="2.2.0"
"Microsoft.Azure.Management.HDInsight" Version="2.0.7"
"Microsoft.Azure.Management.HDInsight.Job" Version="2.0.4"
"Microsoft.Azure.Management.Monitor" Version="0.20.1-preview"
"Microsoft.Azure.Management.IotHub" Version="2.1.0"
"Microsoft.Azure.Management.KeyVault" Version="2.4.1"
"Microsoft.Azure.Management.Logic" Version="3.0.0"
"Microsoft.Azure.Management.MachineLearning" Version="1.0.0"
"Microsoft.Azure.Management.MachineLearningCompute" Version="0.3.0"
"Microsoft.Azure.Management.ManagedServiceIdentity" Version="0.9.0-preview"
"Microsoft.Azure.Management.ManagementPartner" Version="1.1.0-preview"
"Microsoft.Azure.Management.Maps" Version="1.0.0"
"Microsoft.Azure.Management.MarketplaceOrdering" Version="1.0.0"
"Microsoft.Azure.Management.Media" Version="0.1.0"
"Microsoft.Azure.Management.Network" Version="19.5.0-preview"
"Microsoft.Azure.Management.NotificationHubs" Version="2.3.1-preview"
"Microsoft.Azure.Management.OperationalInsights" Version="0.18.0-preview"
"Microsoft.Azure.Management.PolicyInsights" Version="1.0.0"
"Microsoft.Azure.Management.PowerBIEmbedded" Version="1.1.0-preview"
"Microsoft.Azure.Management.PowerBIDedicated" Version="0.10.0-preview"
"Microsoft.Azure.Management.RecoveryServices" Version="4.2.0-preview"
"Microsoft.Azure.Management.RecoveryServices.Backup" Version="3.0.0-preview"
"Microsoft.Azure.Management.RecoveryServices.SiteRecovery" Version="1.2.0-preview"
"Microsoft.Azure.Management.Redis" Version="4.4.0"
"Microsoft.Azure.Management.Relay" Version="2.0.0"
"Microsoft.Azure.Management.Reservations" Version="1.8.0-preview"
"Microsoft.Azure.Management.ResourceGraph" Version="0.9.0-preview"
"Microsoft.Azure.Management.ResourceManager" Version="1.9.0-preview"
"Microsoft.Azure.Management.Authorization" Version="2.8.0-preview"
"Microsoft.Azure.Management.ManagementGroups" Version="1.1.0-preview"
"Microsoft.Azure.Management.Scheduler" Version="2.1.0"
"Microsoft.Azure.Management.Search" Version="2.0.0"
"Microsoft.Azure.Management.SecurityCenter" Version="0.9.0-preview"
"Microsoft.Azure.Management.ServiceBus" Version="1.4.0"
"Microsoft.Azure.Management.ServiceFabric" Version="1.0.0-preview"
"Microsoft.Azure.Management.SignalR" Version="0.10.0-preview"
"Microsoft.Azure.Management.Sql" Version="1.18.0-preview"
"Microsoft.Azure.Management.Storage" Version="8.1.0-preview" 
"Microsoft.Azure.Management.StreamAnalytics" Version="2.0.0"
"Microsoft.Azure.Management.Subscription" Version="1.1.0-preview"
"Microsoft.Azure.Management.TrafficManager" Version="2.5.2"
"Microsoft.Azure.Management.Websites" Version="2.0.0"
Other dependencies
"WindowsAzure.Storage" Version="9.3.0"
"AutoMapper" Version="6.2.2"
"Microsoft.WindowsAzure.Management.Scheduler" Version="6.0.0"
"Azure.Batch" Version="8.1.1"
"Microsoft.DataTransfer.Gateway.Encryption" Version="3.4.6604.1"
"Microsoft.Azure.DataLake.Store" Version="1.1.9"
"Microsoft.Azure.KeyVault" Version="3.0.0"
"Microsoft.Azure.KeyVault.WebKey" Version="3.0.0" 
"Microsoft.Azure.OperationalInsights" Version="0.9.0-preview"
"Microsoft.Azure.Insights" Version="0.15.0-preview"
"Microsoft.Azure.Commerce.UsageAggregates" Version="1.5.2"
"Microsoft.Azure.Storage.DataMovement" Version="0.8.1"

**Comment by maddieclayton** [comment]
**Previews**

| Management Client | Up to date? | Released in Az? | Link |
| ----------------------- | --------------| ----- | ----------------- |
| EventGrid 2.0.0 | no | no | https://github.com/Azure/azure-powershell/tree/AzureRM.EventGrid |
| Automation 3.4.0-preview | yes | no | https://github.com/Azure/azure-powershell/tree/AzureRM.Automation |
| Sql 1.20.1-preview | no | yes | https://github.com/Azure/azure-powershell/tree/AzureRM.Sql-preview |
| Storage 9.1.0-preview | LocalFeed package | no | https://github.com/Azure/azure-powershell/tree/AzureRM.Storage.Location |
| DeploymentManager 0.9.0 | LocalFeed package (not in SDK repo) | no | https://github.com/Azure/azure-powershell/tree/DeploymentRollouts |
| SharedImagegallery (compute) 23.0.0 | no (but 10 version already published) | no | https://github.com/Azure/azure-powershell/tree/Compute-SharedImageGallery |
| UltraSSDEnable (compute) 23.0.0 | no (but 10 version already published) | no | https://github.com/Azure/azure-powershell/tree/Compute-UltraSSDEnable |
| ServiceBus 1.8.0-preview | no (behind preview) | no | https://github.com/Azure/azure-powershell/tree/ServiceBus-0.7.0-preview |
| Batch m:4.2.0 dp:9.0.0 | m:no (same as preview) dp:yes | n0 | https://github.com/Azure/azure-powershell/tree/AzureRM.Batch-preview |
| GuestConfiguration 0.9.0 | yes | no | https://github.com/Azure/azure-powershell/tree/AzureRM.GuestConfiguration |
| Network | yes (same as preview) | no | https://github.com/Azure/azure-powershell/tree/AzureRM.Network-preview |
| EventHub 2.8.0-preview | yes | no | https://github.com/Azure/azure-powershell/tree/EventHub-0.7.0-preview |
| Resources | ?? | ?? | https://github.com/Azure/azure-powershell/tree/AzureRM.Resources.5.0.1 https://github.com/Azure/azure-powershell/tree/AzureRM.Resources-preview |

**Comment by markcowl** [comment]
Fixed
