### ISSUE TITLE
Drive moving signing jobs to ADO (VSTS) signing process

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#7345]
### Description

- [ ] Determine necessary permissions for team members to sign bits using ADO process
- [ ] Drive process for team to get appropriate accouts / permissions
- [ ] Convert all sign processes to ADO as ready
- [ ] Prototype sign process to use ADO

### Cost: 4

**Comment by MiYanni** [comment]
## Notes
- VSTS build definitions require approval, so it isn't based on direct user permissions. It is based on who has access to modify/run build definitions.

**Comment by MiYanni** [comment]
Awaiting https://github.com/Azure/azure-powershell/pull/7457 to be merged prior to making a new branch for testing MicroBuild in our ADO process.

**Comment by MiYanni** [comment]
Got sign builds working.
Initial pipeline: https://devdiv.visualstudio.com/DevDiv/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=10200
Branch: https://github.com/MiYanni/azure-powershell/tree/microbuild-testing

**Comment by MiYanni** [comment]
Created both current azure-powershell signing build pipeline (does not do MSI generation, however), and generated cmdlets signing build pipeline.
https://dev.azure.com/azure-sdk/internal/_build
