### ISSUE TITLE
Support for "Operations Management Suite" / "Operational Insights" from PowerShell

### ISSUE THREAD

**Issue by PeterSelchDahl** [Azure/azure-powershell#735]
I would like the ability to create and delete "Operations Management Suite" / "Operational Insights" from Powershell.

This feature is much needed to "managed service providers"

**Comment by richrundmsft** [comment]
Creation and deletion via PowerShell is available
```powershell
Switch-AzureMode -Name AzureResourceManager 

New-AzureOperationalInsightsWorkspace -ResourceGroupName "ContosoResourceGroup" -Name "MyWorkspace" -Location "West Europe" -Sku standard

Remove-AzureOperationalInsightsWorkspace -ResourceGroupName "ContosoResourceGroup" -Name "MyWorkspace"
```
The current set of PowerShell cmdlets are documented here:
https://msdn.microsoft.com/en-us/library/mt188224.aspx

**Comment by markcowl** [comment]
OperationalInsights cmdlets do exist in PowerShell
