### ISSUE TITLE
Invoke-AzureRmVMRunCommand returns empty output

### ISSUE THREAD

**Issue by Mahalaxmi1994** [Azure/azure-powershell#7354]
I am trying to run Invoke-AzureRmVMRunCommand PowerShell command to get the status of a service running in a Linux VM.  Below is the command I used.

Invoke-AzureRmVMRunCommand -ResourceGroupName xxxxx -Name xxxxx  -CommandId 'RunShellScript' -ScriptPath 'C:\Users\xxxx\Desktop\sample.sh'  

Note: In the sample.sh file I have a command as “systemctl status dnsmasq”

This is not displaying any output in the console. But, while debugging I can see the response from the VM.  I installed all the latest versions of AzureRM modules and executed the command again. Still facing the same issue.

I guess someone raised the same issue earlier also. Can you please tell me whether the issue has been fixed and released?

**Comment by markcowl** [comment]
@Mahalaxmi1994 Can you please try with the latest version?  This was fixed in #6720 and should be available in the versio9n released this morning.

Please re-open if you are still seeing this issue.

**Comment by Mahalaxmi1994** [comment]
Thanks Mark !! I downloaded the latest Azure RM Modules and it's working. I could see the output.

**Comment by Mahalaxmi1994** [comment]
Hi, 
This is working in Powershell, but not in Powershell Workflow. Still, the same issue raises while running this command in workflows.

**Comment by Mahalaxmi1994** [comment]
Hi,
This is working in Powershell, but not in Powershell Workflow. Still, the same issue raises while running this command in workflows.

**Comment by cormacpayne** [comment]
@Mahalaxmi1994 can you verify the version of `AzureRM` that is being used by PowerShell Workflow? You can do this by running `Get-Module -Name AzureRM* -ListAvailable`

**Comment by Mahalaxmi1994** [comment]
I am using AzureRM module version 6.9.0

**Comment by Mahalaxmi1994** [comment]
@cormacpayne And I used inlinescript also in the workflow to run the invoke command but no luck.

**Comment by Am018** [comment]
I am seeing same issue while running a simple command like 'ipconfig'. Its not showing anything in output.

**Comment by Mahalaxmi1994** [comment]
Any updates on the issue?

**Comment by markcowl** [comment]
@Mahalxim  This was fixed in the 6.10 version.  If you are still seeing an issue can you please provide:

- Module layout on your machine

```
Get-Module -ListAvailable
```

- Debug log for the failign cmdlet (```$DebugPreference="Continue"``` before executing the cmdlet).  This will help us to pinoint the issue, as we can't repro it locally.

**Comment by markcowl** [comment]
Closiung as no repro.  If you still see this issue on the latest cmdlets, please open a new issue.
