### ISSUE TITLE
Fix assembly dependency checks in Az

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#7359]
### Description

Assembly dependency checking does not catch missing dependenct assemblies in Az

For example: Microsoft.WIndowsAzure.Storage, Microsoft.WindowsAzure.Storage.DataMovement were both not caught as dependencies, even though they are used in storage cmdlets.

This could largely be because we clean up assembly dependencies in the sign build, but not before running the dependency analyzer,

- [ ] Ensure that DependencyAnalyzer is executed against cleaned-up module bits
- [ ] Ensure that it catches all missing dependencies, and all dependency version mismatches, and all competing dependencies

### Cost: 4

**Comment by maddieclayton** [comment]
This is fixed except for this bug: https://github.com/Azure/azure-powershell/issues/8042
