### ISSUE TITLE
Run Enable-AzureRmAlias as part of Docker builds

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-powershell#7370]
In order to get the correct AzureRM command backwards compatibility and so people do not need to rewrite their scripts (at least now), running the `Enable-AzureRmAlias` cmdlet should be part of the Docker build process if it isn't already. See also #7305.

**Comment by MiYanni** [comment]
Docker builds in .NET Core were never intended to be a primary acquisition scenario.
