### ISSUE TITLE
@Mahalaxmi1994 Can you please try with the latest version?  This was fixed in #6720 and should be available in the versio9n released this morning.

### ISSUE THREAD

**Issue by Mahalaxmi1994** [Azure/azure-powershell#7381]
Please re-open if you are still seeing this issue.

_Originally posted by @markcowl in https://github.com/Azure/azure-powershell/issues/7354#issuecomment-424034455_

**Comment by cormacpayne** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/issues/7354
