### ISSUE TITLE
Set-AzureRMRouteTable - Missing 'DisableBgpRoutePropagation' parameter

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [Azure/azure-powershell#7397]
AzureRM.network 6.8.0

The ability to set the 'DisableBgpRoutePropagation' is missing from the 'Set-AzureRMRouteTable' cmdlet. The parameter exists with the New-AzureRMRouteTable cmdlet.
You are allowed to change this setting via Portal therefore it is a setting that can be figured post deployment.
See schema reference: https://docs.microsoft.com/en-us/azure/templates/microsoft.network/routetables

**Comment by cormacpayne** [comment]
@neaggarwMS would you mind taking a look at this issue?

CC: @MikhailTryakhov

**Comment by neaggarwMS** [comment]
@CHDAFNI-MSFT Set-* calls accepts the resource as a parameter. If the resource object has any changes then those will be updated. Similarly Set-AzureRMRouteTable accepts RouteTable resource as a parameter. If you update RouteTable.DisableBgpRoutePropagation and pass this RouteTable to Set-AzureRMRouteTable, then it should have a updated DisableBgpRoutePropagation  value.

**Comment by CHDAFNI-MSFT** [comment]
@neaggarwMS ahh I understand now. This behavior (of just changing the object's attribute) is a bit different from most of the AzureRM cmdlets. The norm (from my perspective) is for a parameter (or separate cmdlet) to exist for configurable items. Is it possible to add 'DisableBGPRoutePropagation' as a boolean parameter? I'd imagine this confusion would be common as most Azure cmdlet ensure all notable properties are configurable via parameters.

**Comment by CHDAFNI-MSFT** [comment]
@neaggarwMS  follow up on the above. If the parameter cannot/will not be added, could an 'Example' instead be added to the Help file to show how 'DisableBGPRoutePropagation' can be altered?

**Comment by CHDAFNI-MSFT** [comment]
Hello @neaggarwMS 
Yes it helps. I do disagree in this being the 'norm', I think the 'norm' would be for configurable settings to be 'flags' on the cmdlet.

Your example does show how it is possible to make the change however.

If a flag isn't possible, can your example (or similar) be added as an example to the cmdlet's help file?
