### ISSUE TITLE
add-azureaccount for ARM doesn't support certs

### ISSUE THREAD

**Issue by rjmax** [Azure/azure-powershell#740]
ARM and AAD both support service principal based authentication using certificates.  However, add-azureaccount does not support using certs when logging in as a service principal - it only supports user/pass combinations.

**Comment by pcgeek86** [comment]
Can we please mark this as low priority? 

1. There has been concerted effort to get users away from certificate authentication (PublishSettings files).
2. There are some pretty high priority issues outstanding, that should take precedence.

I don't disagree that this should be added, if it's a supported scenario in the platform, but there are much bigger fish to fry, that will likely occupy the next few years of development effort.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by robplank** [comment]
@pcgeek86 are you talking about the Import-AzurePublishSettingsFile "C:\MyPublishSettings\mysubscriptions.publishsettings" process being moved away from?

**Comment by rjmax** [comment]
This work item is not related to the old publish settings file approach, which involves a certificate persisted in RDFE.

It is about adding support for certificate based authentication for ARM using AAD's ability to login as a user/service principal via certificate rather that user/password pair.

It is a requirement for many of our large customers who use PS/CLI to automate against ARM and cannot store credentials.

It would not replace user/pass based auth for interactive use cases like Trevor's.

**Comment by robplank** [comment]
@rjmax I have the need to login via powershell using a cert/service principal account. for a fortune 500 company, do we know when this will be supported?

**Comment by devigned** [comment]
Add-AzureRmAccount supports cert auth as of 1.0.

**Comment by devigned** [comment]
For an example, see:  https://gist.github.com/devigned/dae74a7ca54000f7b714

**Comment by dpksinghal** [comment]
I have a need of using cert based service principal to connect to classic mode of azure subscription i.e., Add-AzureAccount. Couldn't find a way yet. 
Is it supported?
