### ISSUE TITLE
Get-AzureRmCdnEdgeNodes Results Missing Attributes

### ISSUE THREAD

**Issue by wpbrown** [Azure/azure-powershell#7413]
### Description

The PSEdgeNode class only provides the IpAddressGroups attribute from the REST API [EdgeNode](https://docs.microsoft.com/en-us/rest/api/cdn/edgenodes/list#edgenode) object. Without the Name or ID attribute there is no way to distinguish what CDN SKU the PSEdgeNode is.

### Script/Steps for Reproduction

```
Get-AzureRmCdnEdgeNodes
```

### Module Version

See latest source: [PSEdgeNode.cs](https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/Cdn/Commands.Cdn/EdgeNodes/PSEdgeNode.cs).

**Comment by cormacpayne** [comment]
@hytao do you know who would be the proper contact from Cdn to take a look at this issue?

**Comment by hytao** [comment]
This file was created by the old cdn team and they are no longer maintaining the Powershell anymore . I'll take a look at the issue and see if I can fix it.

**Comment by TracyYaoYao** [comment]
This command has been renamed as: **_Get-AzCdnEdgeNode_**
We have created PR to update the output property for the command. https://github.com/Azure/azure-powershell/pull/22755 
It will be released on Az 10.4.0 (September 2023, 2023-09-26).
