### ISSUE TITLE
-TemplateParameterObject on New-AzureResourceGroup is broken

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#742]
# Problem

The following code prompts me for a `locationFromTemplate` [dynamic] parameter, which shouldn't be occurring, because I'm using the `-TemplateParameterObject` parameter on the `New-AzureResourceGroup` command to pass in parameters to the ARM JSON template file.

```powershell
Clear-Host;

Switch-AzureMode -Name AzureResourceManager;

$ResourceGroup = @{
    Name = 'AvailabilitySetTest';
    TemplateUri = 'https://github.com/Azure/azure-quickstart-templates/raw/master/100-starter-template-with-validation/azuredeploy.json';
    DeploymentName = 'AVSet1';
    Location = 'East US';
    TemplateParameterObject = @{
        Location = 'West US';
        };
    };
New-AzureResourceGroup @ResourceGroup;
```
# Expected Result

The earlier code sample should run successfully. A HashTable of parameters, passed into the `-TemplateParameterObject` parameter should be properly mapped to the ARM JSON template file that is referenced in the `-TemplateUri` parameter.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by pcgeek86** [comment]
I think this is fixed in 0.9.7. Can anyone verify?

Cheers,
Trevor Sullivan
 Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by pcgeek86** [comment]
Still broken.

![image](https://cloud.githubusercontent.com/assets/466713/9474695/6afe8f6a-4b1f-11e5-938a-3a20c0a079b0.png)

```
Switch-AzureMode -Name AzureResourceManager;

New-AzureResourceGroup -Name tsdotnet -Location 'West US' `
    -TemplateUri https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-virtual-network/azuredeploy.json `
    -TemplateParameterObject @{ Location = '2West US'; AddressPrefix = '10.10.0.0/24'; SubnetPrefix = '10.10.0.0/24'; } -Force;
```

**Comment by ravbhatnagar** [comment]
All the template deployment related params have been removed from the New-AzureRmResourceGroup cmdlet in the 1.0 PS version.
