### ISSUE TITLE
New-AzVirtualNetworkSubnetConfig doesn't have parameter for virtualNetwork

### ISSUE THREAD

**Issue by mosharafMS** [Azure/azure-powershell#7431]
### Description

In the new Az module, the cmdlet New-AzVirtualNetworkSubnetConfig doesn't have parameter called -VirtualNetwork to bind the VirtualNetwork to submit 

### Script/Steps for Reproduction

```powershell
New-AzVirtualNetworkSubnetConfig -Name GatewaySubnet -AddressPrefix 10.7.0.0/29 -VirtualNetwork $vnet
```

### Module Version

```powershell
Get-Module -ListAvailable

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.2.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackend...

```

### Environment Data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Linux 4.15.0-1023-azure #24~16.04.1-Ubuntu SMP Wed Aug 29 12:54:36 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Debug Output

```

```

**Comment by alexandair** [comment]
@mosharafMS What previous version of the New-AzureRMVirtualNetworkSubnetConfig has had the VirtualNetwork parameter?

**Comment by cormacpayne** [comment]
@mosharafMS same question as @alexandair: which version of `AzureRM.Network` contained the `-VirtualNetwork` parameter that you are referencing?

**Comment by maddieclayton** [comment]
Closing as no previous version has this parameter as far a we know.

**Comment by TiaanVenter** [comment]
Perhaps this is a bug in the Azure Cloud Shell, but I can confirm I'm getting this same issue as well (when attempting to set the var via Cloud Shell):
PS /home/tiaan> $subnetConf1 = Add-AzVirtualNetworkSubnetConfig -Name web2 -AddressPrefix 10.3.1.0/24 -VirtualNetwork 'VNet2'
Add-AzVirtualNetworkSubnetConfig: Cannot bind parameter 'VirtualNetwork'. Cannot convert the "VNet2" value of type "System.String" to type "Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork".

Should I be posting this as a new issue? When passing the command without the '-VitualNetwork' parameter, I get prompted to enter a string for the param and get the same error:

PS /home/tiaan> $subnetConfig1 = Add-AzVirtualNetworkSubnetConfig -Name web2 -AddressPrefix 10.3.1.0/24

cmdlet Add-AzVirtualNetworkSubnetConfig at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
VirtualNetwork: <any user input here>
Add-AzVirtualNetworkSubnetConfig: Cannot bind parameter 'VirtualNetwork'. Cannot convert the "asd" value of type "System.String" to type "Microsoft.Azure.Commands.Network.Models.PSVirtualNetwork".

Any assistance would be greatly appreciated! :)
