### ISSUE TITLE
[Az] Rebranding happened a years ago, Connect-AzAccount still lands on Windows Azure page

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#7433]
A picture is worth a thousand words. Two pictures even more. :)

<img width="290" alt="windowsazurepowershell" src="https://user-images.githubusercontent.com/3135708/46265382-f9180c80-c4f3-11e8-8934-702804a4161a.png">
<img width="291" alt="windowsazurepowershell2" src="https://user-images.githubusercontent.com/3135708/46265383-f9180c80-c4f3-11e8-9445-d2b75c854093.png">

**Comment by cormacpayne** [comment]
@sphibbs @JasonRShaver do we know what the status of this is?

**Comment by sphibbs** [comment]
The fix in AAD should be rolled out this week

**Comment by markcowl** [comment]
Fixed (*!!!!!*)
