### ISSUE TITLE
Powershell error while sending more than 16K records to OMS

### ISSUE THREAD

**Issue by nirmalpavan** [Azure/azure-powershell#7439]
HI Team

We are getting below error while sending more than 16K records data from SQL to OMS using powershell. Please help.

```
Invoke-WebRequest : 
404 - File or directory not found.
Server Error

  404 - File or directory not found.
  The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

At line:1 char:1
+ Invoke-WebRequest -Uri $uri -Method $method -ContentType $contentType ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand 
```

COde:
```
Invoke-WebRequest -Uri $uri -Method $method -ContentType $contentType -Headers $headers -Body $body -UseBasicParsing
```

**Comment by cormacpayne** [comment]
@nirmalpavan are you using any of the `AzureRM` or `Az` cmdlets? I want to make sure this issue should remain in this repository and not be moved to https://github.com/PowerShell/PowerShell

**Comment by nirmalpavan** [comment]
No Cormac we are not using any Azure powershell cmdlets.

**Comment by cormacpayne** [comment]
@nirmalpavan if you aren't using any Azure PowerShell cmdlets, I would recommend opening an issue in the previously mentioned [PowerShell repository](https://github.com/PowerShell/PowerShell), and they should be able to help you out.
