### ISSUE TITLE
webapp:Expected PsVersion in Travis is 6.1.0. Expected is 6.0.4

### ISSUE THREAD

**Issue by vinisoto** [Azure/azure-powershell#7440]
### Description

PowerShell version in Travis should be the same than CloudShell (6.1.0) causing some tests involving New-PsSession to fail (related [PR](https://github.com/Azure/azure-powershell/pull/7423).

As part of the tests that I submitted in the PR I validate that Enter-PsSession can at least be launched (I couldn’t find a way to validate that the PsSession was successfully established without a real web site running – I was able to do it in Recording mode locally and included that test in the PR as ‘Skipped’ for reference ). I found that the test is failing in Travis with this error:
 
_Connecting to remote server ps6298.azurewebsites.net failed with the following error message : MI_RESULT_FAILED_
 
I’m expecting one of two messages as part of the test: _The WinRM client cannot process the request because the server name cannot be resolved_ or _The WinRM client sent a request to an HTTP server and got a response saying the requested HTTP URL was not available_. Which would indicate that the command was fired but the remote host could not be found (which is enough confirmation for the purpose of the test)

## $PsVersionTable in **Travis** returns:

Name                           Value
**PSVersion                     6.0.4**
PSEdition                      Core
GitCommitId                    v6.0.4
OS                             Linux 4.4.0-101-generic 124~14.04.1-Ubuntu SMP Fri Nov 10 19:05:36 UTC 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032, 6.0.4}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

## $PsVersionTable in **CloudShell** returns:

Name                           Value
**PSVersion                      6.1.0**
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Linux 4.15.0-1023-azure 24~16.04.1-Ubuntu SMP Wed Aug 29 12:54:36 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032, 6.1}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by MiYanni** [comment]
Info from email chain:

- Net472 (PowerShell Core on Windows)
- NetCoreApp 2.0 (PowerShell Core 6.0)
- NetCoreApp 2.1 (PowerShell Core 6.1)

So, if your test is failing, that is because our default Travis run is NetCoreApp 2.0. That build depends on Microsoft.PowerShell.SDK 6.0.4. We cannot upgrade that dependency because that’s what PowerShell Core 6.0 supports. For our NetCoreApp 2.1 tests, it depends on Microsoft.PowerShell.SDK 6.1.0-rc.1 (we’ll look into updating this to non-rc later). So, your tests should run appropriately in that build. We do not currently have an automated process to run that build.

What this means is that your code will not work in PowerShell Core 6.0, which we currently support. So, you might need to make some conditional dependencies in your projects to allow you to support PowerShell Core 6.0.

**Comment by vinisoto** [comment]
UPDATE: 6.0.4 on Windows throws the expected error(s): _The WinRM client cannot process the request because the server name cannot be resolved or The WinRM client sent a request to an HTTP server and got a response saying the requested HTTP URL was not available_

Will try 6.0.4 in 14.04.1-Ubuntu next

**Comment by panchagnula** [comment]
@vinisoto can you give us an update on this - from what I understood this issue as a limitation with the PS test infrastructure , however, this got updated as an issue with AppService tests - can you give more context here & if this should still be active?

**Comment by vinisoto** [comment]
@panchagnula I'll have a look and check if we need to include additional validations to modify the behavior of the cmdlet based on the PSVersion present. @jvano as FYI

**Comment by vinisoto** [comment]
@panchagnula - I have created a PR(#9575 ) to explicitly show an error when using PsVersion 6.0.4

**Comment by vinisoto** [comment]
This #9592 addresses the issue. Has been signed off. Currently waiting for merge.

**Comment by panchagnula** [comment]
Closing this since this is merged
