### ISSUE TITLE
Fix Microsoft.Azure.ServiceManagemenet typo in namespace in Common

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#7441]
It is spelled wrong: Microsoft.Azure.ServiceManagemen`e`t
Fix prior to Az? It is in Common and ScenarioTest.ResourceManager (for some reason).

![image](https://user-images.githubusercontent.com/17788297/46315842-5effa500-c583-11e8-86f4-cf56315f3fe3.png)

**Comment by markcowl** [comment]
Doesn't apply to Az.  Closing

**Comment by markcowl** [comment]
Fixed
