### ISSUE TITLE
Set-AzureRmApplicationGatewaySslCertificate help text is not clear

### ISSUE THREAD

**Issue by jeyoung** [Azure/azure-powershell#7446]
### Description

The help text for `Set-AzureRmApplicationGatewaySslCertificate` is not clear at all. The text 

> NAME
>     Set-AzureRmApplicationGatewaySslCertificate
> 
> SYNOPSIS
>     Sets the goal state of an SSL certificate.

does not explain what a "goal state" is.

### Script/Steps for Reproduction

```powershell
Get-Help Set-AzureRmApplicationGatewaySslCertificate -detailed
```

### Module Version

```powershell
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Set-AzureRmApplicationGatewaySslCertificate        5.4.2      AzureRM.Network
```

### Environment Data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.16299.611
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.611
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by cormacpayne** [comment]
@akshaysngupta Hey Akshay, would you mind taking a look at this issue?

**Comment by number213** [comment]
I suggest changing synopsis and description to `Updates SSL certificate on an existing application gateway.`
@cormacpayne I agree that "goal state" is a confusing term, there are 81 occurences of it in Network docs, should we replace them with something more clear?

**Comment by cormacpayne** [comment]
@number213 if we can fix this problem across all affected Network docs to avoid potential future issues, that would be great. Since that change will involve going through a good amount of docs, I'd recommend coupling it with any other large-scale doc changes your side has planned.

**Comment by number213** [comment]
Improved synopsis in this PR: https://github.com/Azure/azure-powershell/pull/8431
