### ISSUE TITLE
Azure Rm and Az Failure

### ISSUE THREAD

**Issue by Layanshafaamri** [Azure/azure-powershell#7454]
### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by cormacpayne** [comment]
@Layanshafaamri please re-open this issue with sufficient information about the issue you are having with either the `AzureRM` or `Az` module -- the template the provided in the issue body has a description of the information we will need.
