### ISSUE TITLE
Travis (Docker image) needs to update Profile psd1 to have RootModule on build

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#7460]
During our signed build, we update Profile's psd1 to contain a RootModule entry for the psm1. This allows us to load the correct `Microsoft.IdentityModel.Clients.ActiveDirectory` version. We need to do this as part of the Travis build, or else the Docker images we create will not be usable.

**Comment by dingmeng-xue** [comment]
It is not issue in current build/sign pipeline. Close this issue.
