### ISSUE TITLE
webapp: New-AzureRmWebAppSSLBinding needs support for KeyVault certificates & 3rd party certificates through script

### ISSUE THREAD

**Issue by Simon687** [Azure/azure-powershell#7469]
### Description
New to PowerShell. Failed to upload CA certificate to web app through powershell script New-AzureRmWebAppSSLBinding, but can manually upload private certificate through SSL settings->Private Certificates->Upload Certificate. Prefer to do this through script as there are over 10 of 3rd party certificates. 

This is occurred during the process of deployment to azure. Even though it will cause exception error message, the certificate will still be uploaded under private certificates accordingly if I set continue in the loop.

It will be great if someone can help me out on this, I don't think I should create custom domain for each of the certificate that has a different host name with my web app's host name.

Thanks!

### Script/Steps for Reproduction

Use a third party certificate and try to upload it through script to a web app that has a different domain name from certificate's CN.

```powershell
New-AzureRmWebAppSSLBinding -ResourceGroupName $ResourceGroupName -WebAppName $WebAppDisplayName -CertificateFilePath $ExportedCertificate -CertificatePassword $ExportedCertificate.Password -Name $WebAppHostName 
```

### Module Version

```powershell
Get-Module -ListAvailable
```                                                                                                                                     
6.9.0      AzureRM                             PSGallery            Azure Resource Manager Module                                                                                                                           

### Environment Data

```powershell
$PSVersionTable
```                                                                                                                                                                            
PSVersion                      5.1.17134.228                                                                                                                                                                                
PSEdition                      Desktop                                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                      
BuildVersion                   10.0.17134.228                                                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                                          
SerializationVersion           1.1.0.1 
### Debug Output

```
"Code": "Conflict",
  "Message": "The certificate with thumbprint '***************' does not match the hostname '***************.azurewebsites.net'.",
```

**Comment by cormacpayne** [comment]
@panchagnula @Nking92 would you mind taking a look at this issue?

**Comment by LockTar** [comment]
I have the same issue. If the certificated is already uploaded, a binding can be set with giving the thumbprint

**Comment by panchagnula** [comment]
@btardif can you help us identity the appropriate APIs for this plus any changes we need to make to the existing commands design to support this. Thank you.

**Comment by btardif** [comment]
We are working with Dev owner to get details on API, once we have this we'll design and schedule work.

**Comment by btardif** [comment]
https://docs.microsoft.com/en-us/rest/api/appservice/certificates/createorupdate

**Comment by panchagnula** [comment]
This work is not planned as yet -changing the milestone.

**Comment by panchagnula** [comment]
This is tracked by issue #12540
