### ISSUE TITLE
Get-AzureSubscription always get the Free Trial subscription

### ISSUE THREAD

**Issue by imeya** [Azure/azure-powershell#7474]
I have two azure subscription, one is free trial, the other is named mySub.
I used this cmdlet to login: Login-AzureRmAccount -SubscriptionName "mySub".

Then use Get-AzureSubscription, it always only show me the Free Trial subscription. 
When I use the subscriptionName parameter with "mySub", returns nothing.

can somebody tells me why?

**Comment by cormacpayne** [comment]
@imeya it looks like you're using the `Get-AzureSubscription` cmdlet, which targets RDFE, rather than `Get-AzureRmSubscription`, which targets ARM. Would you mind trying this cmdlet and seeing if your other subscriptions appears?

**Comment by imeya** [comment]
get-azureRmSubscription works correctly. thank you.
