### ISSUE TITLE
Launch a browser to login - nice to have

### ISSUE THREAD

**Issue by dfinke** [Azure/azure-powershell#7484]
The `az login` now launches a browser to login, one less copy/paste is nice to have. Don't know if it is on the road map.

![image](https://user-images.githubusercontent.com/67258/46572965-8d52fb00-c95c-11e8-9c19-76b7a8e00a93.png)

**Comment by cormacpayne** [comment]
@dfinke Hey Doug, we are working on a similar experience for the `Az` module, as outlined in this issue: https://github.com/Azure/azure-powershell/issues/7358

We will track the progress of this work in that issue, so I'm going to close this one in favor of it. Thanks!
