### ISSUE TITLE
Please provide an example of the disable function of Add-AzureRmWebtestAlertRule cmdlet

### ISSUE THREAD

**Issue by EdisonDa** [Azure/azure-powershell#7486]
This was copied from the user feedback: https://github.com/MicrosoftDocs/feedback/issues/744, user is asking an example of how to disable the function of Add-AzureRmWebtestAlertRule cmdlet.

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by markcowl** [comment]
@gucalder can you take a look?

**Comment by imeya** [comment]
@markcowl , @gucalder , actually, I have submitted this issue a few days before, but still no feedback, please help me figure it out. thank you very much.

**Comment by snehithm** [comment]
Hi @markcowl, @EdisonDa, 

We are triaging some of the older Azure Monitor alert related issues and are trying to provide answers. 

For this request, the following example should disable the webtest classic alert:
```PS
Add-AzWebtestAlertRule -Name "webtestRule" -ResourceGroup "Default-Web-EastUS" -DisableRule
```
@markcowl I am closing this one out.
