### ISSUE TITLE
Request for Powershell Cmdlets - List Subscription Operations

### ISSUE THREAD

**Issue by abhishekanand** [Azure/azure-powershell#75]
This a request to provide command to llist all operation done a subscription during a time Period.

For Example : 
`Get-AzureOperationHistory -Subscription  <GUID>  -StartDate mm/dd/yyyy -EndDate mm/dd/yyyy`

Ref : http://msdn.microsoft.com/en-us/library/azure/gg715318.aspx

**Comment by markcowl** [comment]
Thanks for the report of this issue, assigning appropriately

**Comment by idofl** [comment]
+1, it would really be helpful to have it with PowerShell. The REST API is very complex for this command

**Comment by singhkay** [comment]
@markcowl @matt-gibbs Should this be owned by your team instead since you folks already own the other subscription cmdlets?

**Comment by markcowl** [comment]
@kirthik This is a capbility that should be provided by our cmdlets or the generic cmdlets.  Need to verify that it is not, and add if it isn't

**Comment by markcowl** [comment]
### Description

Evaluate whether the described functionlaity (generically getting the entire operation history across all RPs for a given time period) is supported by current cmdlets.  If not, scope creting a cmdlet workflow that had this functionality.

### Cost: 1

**Comment by sphibbs** [comment]
Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration.
