### ISSUE TITLE
Get-AzureProviderOperation is case sensistive, should not be case sensitive

### ISSUE THREAD

**Issue by chadiel** [Azure/azure-powershell#750]
If you register an RP with one case and try to query for the operations with a different case, the operations will not return. E.g. the following will not work (but should)

Register-AzureProvider -ProviderNamespace "MICROSOFT.STORAGE"
Get-AzureProviderOperation -ActionString "microsoft.storage*"

**Comment by ravbhatnagar** [comment]
Works now
