### ISSUE TITLE
in Set-AzureRmApiManagementApi, how to set IsCurrent and IsOnline fields?

### ISSUE THREAD

**Issue by sdementen** [Azure/azure-powershell#7508]
### Description

I want to change the flags/fields IsCurrent and IsOnline of a specific Revision of an API in the APIM via powershell. 

### Module Version

```powershell
Get-InstalledModule -Name "AzureRM.ApiManagement"

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
6.1.5      AzureRM.ApiManagement               PSGallery            Microsoft Azure PowerShell - Api Management serv...
```

**Comment by cormacpayne** [comment]
@solankisamir Hey Samir, would you mind taking a look at this issue?

**Comment by solankisamir** [comment]
The way to make a specific Api Revision current and Online is to create a new Release.
See test [here](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/ApiManagement/Commands.SMAPI.Test/ScenarioTests/ApiManagementTests.ps1#L2345)

**Comment by sdementen** [comment]
Thank you @solankisamir , this clarifies how to make a revision the current one.
However, for the Online flag, I see it is set by default when creating a new revision and I cannot find a way to make an API offline.

I'd like to see if adding operations to an offline API is faster than to an online API, as today, adding ten to hundred operations to an online API takes a long time (from 1min to 20min).
