### ISSUE TITLE
Install-Module Az suggestion

### ISSUE THREAD

**Issue by vandreytrindade** [Azure/azure-powershell#7510]
Hi,
I've tried today to remove the AzureRM module and install the Az module.
What I've missed is the module appearing on **Get-Module -ListAvailable Az** command.
I have a function that checks for updates on modules and with AzureRM was easier to check because of that.
Also, is there a way to keep the modules folder organized? I think that is terrible to have a lot of folders on the Windows Powershell modules. Can you create a folder called Az and put all the modules required inside of it?

Sorry if this is not the correct channel.

**Comment by cormacpayne** [comment]
@vandreytrindade thanks for opening this issue -- just a few questions for you:

(1) What do you currently see when you run `Get-Module -Name Az* -ListAvailable`? This should list all modules installed on your machine (at least those in a folder mentioned in `$env:PSModulePath`) that being with `Az`.

(2) What functionality do you find missing for checking updates between the `AzureRM` and `Az` modules? You should be able to run the `Find-Module` command for both of these modules to grab the latest version on the PowerShell Gallery and compare it to what you have installed on your machine.

(3) Not a question but a comment 😀 -- by default, modules installed from the PowerShell Gallery are placed in the `$env:ProgramFiles\WindowsPowerShell\Modules` folder, but I'm not aware of any method to specify a directory to install a module to using `Install-Module`. I _believe_ that you could create a folder somewhere on your machine called `Az` with all of the installed `Az.*` folders inside of it, and if you add that path to `$env:PSModulePath`, PowerShell will be able to find them as usual, I'm just not sure about the update scenario in that case, you'll need to test that out 😁

**Comment by vandreytrindade** [comment]
@cormacpayne Hi again!
(1) It lists all the Az.* modules in 0.3.0 version
(2) My function checks the local version and the PowerShell Gallery version of AzureRM, if the PowerShell Gallery is newer, then it asks if it should be updated. With the **Get-Module -ListAvailabe Az** command it doesn't show anything. But I have checked now that with **Get-InstalledModule Az** command I'm able to see the current version of the module installed on my machine. So nothing to change =]
(3) So sad... I wish there was a way so you guys could create a folder structure inside the path **$env:ProgramFiles\WindowsPowerShell\Modules** so it can look like this:
**ProgramFiles\WindowsPowerShell\Modules\Az\Az.***

Thanks for your time! Wish you the best!

**Comment by markcowl** [comment]
@vandreytrindade As it turns out, this is a bug in the PowerShell engine, where it skips the module 'Az' specifically because it corresponds with a language code name (Az = Azerbaijani).  The bug for this has been filed in the powershell repo.

**Comment by cormacpayne** [comment]
Link to mentioned PowerShell issue: https://github.com/PowerShell/PowerShell/issues/8125

**Comment by praveenbrook** [comment]
my 2 cents.

When installing Az on a machine with AzureRM previously installed, you must specify AllowClobber in the Install-Module cmdlet invocation.

PS C:\> Install-Module -Name Az -AllowClobber
