### ISSUE TITLE
[Insights] Set-AzureRMDiagnosticSetting requires explicit specification of categories during creation of setting

### ISSUE THREAD

**Issue by gucalder** [Azure/azure-powershell#7513]
### Description

Set-AzureRMDiagnosticSetting requires explicit specification of categories during creation of setting. If the list of categories is not included, the cmdlet does not report any error, but the backend will ignore the request since it is enabling no category.

### Script/Steps for Reproduction

Run the following command using the SDK version 6.9. For previous versions and exception could be thrown. 

```powershell
Set-AzureRmDiagnosticSetting -resource <resourceId> -storage <resourceId> -Enabled $true
```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```
Wait for some minutes and check whether the setting was created. It is not created despite of the command not showing any error.

```

**Comment by RichShillingtonMSFT** [comment]
This is indeed a problem. I went back to version AzureRM.Insights 4.0.4 and it works fine. All AzureRM.Insights 5.1.x versions appear to be broken.

**Comment by MiYanni** [comment]
The fix for this issue has been merged: https://github.com/Azure/azure-powershell/pull/7619
It will be available in the next release of AzureRM/Az.
