### ISSUE TITLE
RecoveryServices.Backup: TestAzureVMPolicy failing for Az

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#7533]
Currently, we are skipping this test for Az as part of this PR: https://github.com/Azure/azure-powershell/pull/7497

I found that, for this test, it seems to require loading multiple versions of the same SDK for it to work properly. My analysis my be incorrect, but it was the best approximation to why this test was failing for Az.

**Comment by siddharth7** [comment]
@MiYanni Afaik, it had something to do with the `netcoreapp`/`netcorestandard` version. Have they been updated anytime soon?

**Comment by MiYanni** [comment]
@siddharth7 No. We build against netstandard 2.0. We won't be able to change that as long as we are supporting PowerShell 5.1.

**Comment by siddharth7** [comment]
@pvrk this issue seems to be from PS infra end

**Comment by siddharth7** [comment]
@MiYanni Can you update the labels for this issue?

**Comment by MiYanni** [comment]
@siddharth7 What do you want the labels to be?

**Comment by pvrk** [comment]
Removing 'Recovery Services' label since the issue needs to be fixed with PS team.

**Comment by markcowl** [comment]
@pvrk  This test belongs to you.  If it is not in your plan to fix this test, then we will close this issue.

**Comment by pvrk** [comment]
@markcowl : Apologies but my understanding is that this test is failing because PS is using only netstandard 2.0. May I know how are we expected to fix this issue?

**Comment by pvrk** [comment]
@markcowl: A gentle reminder. Any update on this? Actually this is causing a lot of pain for our PS users who are not shifting to Az module but remaining on AzureRM module due to this issue. Can we discuss on how to solve this once and for all?

**Comment by Daya-Patil** [comment]
@markcowl  A gentle reminder. Any update on this?

**Comment by Daya-Patil** [comment]
Its been few years
