### ISSUE TITLE
Az Transition: Rename Az csproj files, Create Az sln files, Rename AzureRM sln files

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#7538]
- Rename:
  - `Commands.[ModuleName].Netcore.csproj` and `Commands.[ModuleName].Netcore.Test.csproj` files to:
  - `[ModuleName].csproj` and `[ModuleName].Test.csproj` respectively
- Rename:
  - `[ModuleName].sln` to `AzureRM.[ModuleName].sln`
- Create:
  - `[ModuleName].sln` that are used as the Az solution files for each module
- Change tooling to work with the new names
  - StaticAnalysis
  - Version Controller
  - tools/*.ps1 files
    - Especially, CreateFilterMappings
  - *Potential Common code changes

**Comment by markcowl** [comment]
Fixed
