### ISSUE TITLE
Connect-AzAccount fails to login for foreign principals

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#7540]
### Description

I have an account sa@abc.onmicrosoft.com added to another tenant directory xyz.onmicrosoft.com. AzureStack is configured on the xyz.onmicrosoft.com

Connect-Az Account fails with 
Application with identifier 'sa' was not found in the directory '3-a7a2-4cdd-eae33-3'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant

 Connect-AzAccount -EnvironmentName "AzureStackAdmin" -TenantId $tenantID -Credential $creds -ServicePrincipal:$false -Verbose -Debug

Here the $tenantId is the GUID like '2-a-d-a3d4-f'

### Module Version

0.3.0
### Environment Data
Azure Stack

### Debug Output

Connect-AzAccount -EnvironmentName "AzureStackAdmin" -TenantId $tenantID -Credential $creds -ServicePrincipal:$false -Verbose -Debug
DEBUG: 5:47:09 PM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'ServicePrincipalWithSubscriptionId'.

DEBUG: 5:47:11 PM - Autosave setting from startup session: 'Process'
DEBUG: 5:47:11 PM - No autosave setting detected in environment variable 'AzureRmContextAutoSave'.
DEBUG: 5:47:11 PM - Using Autosave scope 'Process'
DEBUG: 5:47:11 PM - Autosave setting from startup session: 'Process'
DEBUG: 5:47:11 PM - No autosave setting detected in environment variable 'AzureRmContextAutoSave'.
DEBUG: 5:47:11 PM - Using Autosave scope 'Process'
DEBUG: 5:47:12 PM - Autosave setting from startup session: 'Process'
DEBUG: 5:47:12 PM - No autosave setting detected in environment variable 'AzureRmContextAutoSave'.
DEBUG: 5:47:12 PM - Using Autosave scope 'Process'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '2-a-d-a3d4-f', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://adminmanagement.xyz.onmicrosoft.com/c87b3ae3-2f54-4ed7-8225-ec1b7d488728', ValidateAuthrity: 'True'
Connect-AzAccount : AADSTS700016: Application with identifier 'ciserviceadmin' was not found in the directory '2-a-3-3-f'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant
Trace ID: 524cbf61-5cef-4714-a785-95f646ad4f00
Correlation ID: fe47c26c-0e64-4b82-9742-bda54b4d4c3b
Timestamp: 2018-10-13 00:47:13Z
At line:1 char:1
 Connect-AzAccount -EnvironmentName "AzureStackAdmin" -TenantId $tenan ...
 CategoryInfo          : CloseError: (:) [Connect-AzAccount], AdalServiceException
 FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

DEBUG: 5:47:13 PM - ConnectAzureRmAccountCommand end processing.
DEBUG: 5:47:13 PM - ConnectAzureRmAccountCommand end processing.

**Comment by markcowl** [comment]
This is by design - ADAL 3.0 does not support non-interactive user login

**Comment by bganapa** [comment]
Thanks!, I was about to close this one:)
