### ISSUE TITLE
Command Fails

### ISSUE THREAD

**Issue by kentstroker** [Azure/azure-powershell#7541]
PS C:\Windows\system32> **Update-Module -Name AzureRM**
PackageManagement\Install-Package : Unable to find repository 'https://www.powershellgallery.com/api/v2/'. Use
Get-PSRepository to see all available repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2089 char:20
+ ...           $sid = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : SourceNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by markcowl** [comment]
@kentstroker So, the issue appears to be that you have a definition of the PSGallery repository that uses a trailing '/', which is failing using the latest Nuget provider.

You can use ```Resgister-PSRepository -Default``` to create the default PSGallery repository registration (with no trailing slash).  You might need to remove the previous registration first.

Meanwhile, the PowerShellGet module is part of PowerSHell, their repository is here: https://github.com/powershell/powershellget This is where issues against the PowerShellGet module should be filed.
