### ISSUE TITLE
Create new WebPI entry for new cmdlets when Switch-AzureMode is removed.

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-powershell#755]
To ease the transition away from Switch-AzureMode we want to keep the existing WebPI entry for the last version of the cmdlets that contains the Switch-AzureMode behavior.  This will allow everyone to install those cmdlets where needed while code is being migrated.  It will also mean no one using the feed will be automatically broken unexpectedly because they we're using the "latest" feed entry.

This means, that when the new cmdlets are released without Switch-AzureMode, we will need to create a new WebPI entry for those cmdlets and have two entries available for some grace period.

**Comment by markcowl** [comment]
this was completed
