### ISSUE TITLE
AzureRM.Security - Azure Security Center

### ISSUE THREAD

**Issue by mattjlubbers** [Azure/azure-powershell#7552]
Hey there,

Just curious on if we are continuing to develop the AzureRM.Security module. As a security engineer, it would be amazing to start integrating events into automation runbooks, and security playbooks.

[Malware Alert > ASC Alert > Created Runbook / Automation > Pull Alert Info > Run Runbook / Script]

Just a line of thinking. If this is still being developed, what is the timeframe for GA release?

Thanks!

**Comment by markcowl** [comment]
@sphibbs @JasonRShaver Can we find an appropriate security centrer contact to respond to this query

**Comment by sphibbs** [comment]
@chlahav can you take a look at this issue

**Comment by chlahav** [comment]
@MatthewLubbers 
Hi,
This module is still being developed :)
We are gathering feedback from customers that uses the preview module to make sure the GA version will have the proper quality and we also create other clients in parallel.
We don't have a release date for GA version yet but it will be in the next few months.
