### ISSUE TITLE
Address the issue when a template parameter conflicts with a cmdlet parameter name

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/azure-powershell#756]
Currently, in such cases we append the "fromTemplate" to the template param name. The user is prompted to provide values of such parameters. For example - If the user passes the storageAccount parameter in a parameter file, he should not be prompted for storageAccountFromTemplate. Select the PS parameters to reduce chances of such collisions.

**Comment by todthomson** [comment]
:+1: I encountered this problem today.

**Comment by matousrokos** [comment]
I believe that this is known issue (but still confusing issue). When you are using common Azure names (like storageAccount, virtualMachine and such) for parameter names this issue always appears. Rename your parameter to something that Azure is not using in naming convention like newStorageAccount

**Comment by ravbhatnagar** [comment]
I guess this is by design as we dont want to override param values unintentionally (hard to accurately predict user intent). What we can do is probably provide a better informational message when we run into such scenarios so that users understand and remember it while namimg params.

**Comment by ravbhatnagar** [comment]
Closing this as this is by design.
