### ISSUE TITLE
Fix module definition for Az

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#7563]
### Description

'Az' is only effective currently as a package for modules, there are several problems with the definition which shoudl be addressed:
- [x] Az.psm1 is not listed as the RootModule
- [x] Az.psm1 is not signed (change the msbuild itesm in the signing job)
- [ ] Az does not show up in the list of modules when using Get-Module -ListAvailable

### Cost 4

**Comment by cormacpayne** [comment]
Corresponding issue file in the PowerShell repository: https://github.com/PowerShell/PowerShell/issues/8125

**Comment by cormacpayne** [comment]
The last bullet appears to be a bug in PowerShell with `Az` being a valid culture. Closing this issue as the status will be tracked through that issue.
