### ISSUE TITLE
[Placeholder]: Blogging Plan

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#7573]
### Description

Come up with several topics for team blogs and a plan for driving interest.  The idea is to have a regular cadence of blog posts (1 per sprint or 1 per month).  To let people know about new features.

Consider advertising through Azure Blog, What's new functionality, and other mechanisms

#$## Cost: 8

**Comment by praries880** [comment]
I would also like to suggest that we link to the blogs form the release notes (where it makes sense to do so :) )for individual modules or the release notes for easy discoverability.

**Comment by markcowl** [comment]
Blog Plan published to azure-powershell-pr
