### ISSUE TITLE
Common: Use internal Storage management SDK for AzureRM.Storage.ps1

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#7590]
In our ScenarioTests.ResourceManager common package, we have an AzureRM.Storage.ps1. This is used for tests to call Storage 'cmdlets' in a generic way. It hides the SDK surface using this script. However, it would be nice for it to use our internal SDK so that it is consistent. I did this same task for the AzureRM.Resources.ps1 to use our internal SDK.

Client created here:
https://github.com/Azure/azure-powershell-common/blob/6557ed714482320ca1592d26f799ef8c942aeec4/src/ScenarioTest.ResourceManager/AzureRM.Storage.ps1#L208

Then, you'd look through the file for any additional references to `Microsoft.Azure.Management.Storage`, such as: https://github.com/Azure/azure-powershell-common/blob/6557ed714482320ca1592d26f799ef8c942aeec4/src/ScenarioTest.ResourceManager/AzureRM.Storage.ps1#L218

**Comment by markcowl** [comment]
Check to see if this is still an issue after we remove net45 build

**Comment by cormacpayne** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/issues/5365
