### ISSUE TITLE
StaticAnalysis for Stack: build.proj failure

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#7593]
In our build.proj, we have [this section](https://github.com/Azure/azure-powershell/blob/cc7d1b0be08ce3de3a9fcad3abed63ee6ac91960/build.proj#L602-L604) which tells StaticAnalysis to run on Stack. Right now, it errors:

```powershell
C:\Code\azps\src\Package\StaticAnalysis.exe -p C:\Code\azps\src\Stack\Debug -r C:\Code\azps\src\Stack

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Code\azps\src\Stack\Exceptions'.
     at StaticAnalysis.Program.Main(String[] args) in C:\Code\azps\tools\StaticAnalysis\Program.cs:line 147
C:\Code\azps\build.proj(602,5): warning MSB3073: The command "C:\Code\azps\src\Package\StaticAnalysis.exe -p C:\Code\azps\src\Stack\Debug -r C:\Code\azps\src\Stack" exited with code -532462766.
```

We need to make this either work correctly for Stack or remove it from our build process.

**Comment by markcowl** [comment]
won't fix - Stack is using older modules that will not be up to date with our current static analysis
