### ISSUE TITLE
Set-AzureKeyVaultSecret : Key vault cmdlet does not support account type 'AccessToken'.

### ISSUE THREAD

**Issue by jahmai** [Azure/azure-powershell#760]
When attempting to run Set-AzureKeyVaultSecret from the script Deploy-AzureResourceGroup.ps1 of a Visual Studio Azure deployment project I get the error:

Set-AzureKeyVaultSecret : Key vault cmdlet does not support account type 'AccessToken'.

All other Azure commands that I have tried work fine, and Set-AzureKeyVaultSecret works successfully from the PowerShell ISE with the same credentials.

**Comment by markcowl** [comment]
@jahmai  Is this using a visual studio generated script?

**Comment by jahmai** [comment]
@markcowl Other than Add-AzureAccount, is there another way to provide appropriate credentials in such a script for the KeyVault operations to work? Ideally any prompt would happen at the start of the long running script in which this step is somewhere in the middle.

**Comment by cormacpayne** [comment]
@RandalliLama @tiffanyachen copying you both over from linked issue https://github.com/Azure/azure-powershell/issues/4818

Would you mind taking a look at this issue?

**Comment by dingmeng-xue** [comment]
@jahmai, we are revisiting this problem. Could you let me know which type of project you are using? I'm using  VS 2019 but cannot find project type "Azure deployment". If you share more detail steps, it will be appreciated.

**Comment by jahmai** [comment]
@dingmeng-xue 

Here is how to create one with VS2019:

![image](https://user-images.githubusercontent.com/2010997/74980345-65e2cc80-5484-11ea-9265-883835e781e6.png)

The default deployment script is called "Deploy-AzureResourceGroup.ps1", and attempting to call Set-AzureKeyVaultSecret from inside that script resulted in the error in this issue, but I haven't tried it recently.

What we ended up doing 4 years ago was creating another script New-Site.ps1, which we execute from a standard Powershell command line which in turn calls (a slightly modified) Deploy-AzureResourceGroup.ps1, then calls Set-AzureKeyVaultSecret afterward, working around the issue.

So for me, this issue is no longer important.

**Comment by dingmeng-xue** [comment]
Thanks for the information and also sorry that there is no follow up for so long time. The original script and Set-AzureKeyVaultSecret are old version and VS is out of Azure PowerShell's scope. If you meet further issue around it, please raise again.
