### ISSUE TITLE
Connect-AzAccount fails in AzureStack ADFS environments

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#7602]
### Description
It looks like the cmdlet is trying to do instance discovery going to the the common tenant
and it fails with the following

Login-AzAccount : Invalid authority type. This method overload is not supported by 'https://adfs.local.azurestack.external/adfs/Common/'

### Script/Steps for Reproduction
[Needs azurestack environment]
 add-azenvironment -ARMEndpoint https://adminmanagement.local.azurestack.external/ -Name AzureStackAdmin

Login-AzAccount -EnvironmentName AzureStackAdmin -Debug -verbose

### Debug Output

Login-AzAccount -EnvironmentName AzureStackAdmin -Debug -verbose
DEBUG: 12:52:11 PM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.

DEBUG: 12:52:13 PM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 12:52:13 PM - No autosave setting detected in environment variable 'AzureRmContextAutoSave'.
DEBUG: 12:52:13 PM - Using Autosave scope 'CurrentUser'

Performing the operation "log in" on target "User account in environment 'AzureStackAdmin'".
DEBUG: 12:52:14 PM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 12:52:14 PM - No autosave setting detected in environment variable 'AzureRmContextAutoSave'.
DEBUG: 12:52:14 PM - Using Autosave scope 'CurrentUser'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 'https://adfs.local.azurestack.external/adfs/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://adminmanagement.adfs.azurestack.local/dbe9c7f4-1df7-4a5e-a06c-32dab681ab56', ValidateAuthrity: 'False'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://adfs.local.azurestack.external/adfs/Common/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'False'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'Common', AdEndpoint: 'https://adfs.local.azurestack.external/adfs/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
Login-AzAccount : Invalid authority type. This method overload is not supported by 'https://adfs.local.azurestack.external/adfs/Common/'
At line:1 char:1
 Login-AzAccount -EnvironmentName AzureStackAdmin -Debug -verbose
 CategoryInfo          : CloseError: (:) [Connect-AzAccount], AadAuthenticationFailedException
 FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

DEBUG: 12:52:14 PM - ConnectAzureRmAccountCommand end processing.
DEBUG: 12:52:14 PM - ConnectAzureRmAccountCommand end processing.

**Comment by markcowl** [comment]
@bganapa is this covered by the ADAL update?

**Comment by markcowl** [comment]
Closing in favor of the ADAL udpate

**Comment by bganapa** [comment]
I am not sure whether ADAL update is going to fix this, I will recheck once updated

**Comment by Jayes90** [comment]
Hi, so what is the solution or workaround for this?

**Comment by VeryEarly** [comment]
> Hi, so what is the solution or workaround for this?

Hi @Jayes90 ,

This issue was already closed, to have a better track of your problem, please open another issue with detailed provided.

You can also link this one to your new opened issue.
Thanks

**Comment by bganapa** [comment]
If anyone is hitting this issue in AzureStack ADFS environment with Az modules, please make sure that you are using 2.0.1-preview+ Az.Accounts module. 
1.7.2 az.accounts module is not supported for ADFS environments
