### ISSUE TITLE
psm1 commit/generate issue

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#7603]
Currently, we have the psm1 files in our .gitignore. The problem is, the psm1 files are *tracked files* and *.gitignore does not apply to tracked files.* So, we are still having the psm1 files come up in PRs/commits.

There is no way to make them both tracked and untracked (for everyone). You can `assume unchanged` for files locally, but we can't persist that to the repo itself.

### The solution here: 
Have a tracked file in our repo for each psm1. The current ones are:
- /tools/AzureRM/AzureRM.psm1
- /tools/Az/Az.psm1
- /src/StackAdmin/AzureRM/AzureRM.psm1
- /src/StackAdmin/AzureStack/AzureStack.psm1

Except... rename the tracked files so that they are **not the files that are generated**:
- /tools/AzureRM/AzureRM-Base.psm1
- /tools/Az/Az-Base.psm1
- /src/StackAdmin/AzureRM/AzureRM-Base.psm1
- /src/StackAdmin/AzureStack/AzureStack-Base.psm1

Then, these files will be **merged into the generated file**. So, the generated file stays ignored. But, the base files allow you to add content as needed and stay committed in the repo. Easiest way to do this would be to copy the file during the build process and remove the `-Base` from the name. Then, the process should function the same way it does now.

**Comment by markcowl** [comment]
@MiYanni  Please remove these files
