### ISSUE TITLE
Inconsistency :: 0.9.7 Release notes vs. reality

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#763]
# Issue

The release notes for Azure PowerShell 0.9.7 states that there is a new `-DeploymentMode` parameter on the `New-AzureResourceGroupDeployment` command in the ARM PowerShell module.

Based on my discovery methods, I do not see any such parameter. There is no documentation for it, and there is no indication that it exists, unless it's a hidden dynamic parameter.

![image](https://cloud.githubusercontent.com/assets/466713/9317761/f7817716-44fa-11e5-855a-b63f32b47366.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 The parameter is Mode, the type is DeploymentMode.  Feel free to submit a PR to correct the release notes.

**Comment by markcowl** [comment]
@pcgeek86 fixed in the release notes and the dev branch.  Thanks for the heads up!  -Mark

**Comment by pcgeek86** [comment]
Thanks for fixing the release notes, Mark. When I was visually scanning for `DeploymentMode`, I completely passed up `Mode`.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
