### ISSUE TITLE
AZ - no RecoveryServicesVault cmdlets?

### ISSUE THREAD

**Issue by lukeb1961** [Azure/azure-powershell#7637]
running up an existing script that creates recovery services vault and ASR fabric.
Nothing in the current (0.3.0) AZ module.  Is that planned?

**Comment by MiYanni** [comment]
@lukeb1961 Released (today), Az 0.4.0 has Recovery Services.
https://www.powershellgallery.com/packages/Az/0.4.0

Please reopen this issue if you have further issues.
