### ISSUE TITLE
Scale Azure Cosmos DB container throughput using Azure PowerShell

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-powershell#7649]
### Description

Currently if you want to scale your Azure Cosmos DB container throughput via the command line, the Azure CLI is the only option. This is not sufficient because there are environments where Azure CLI is not a viable option for automation. Please add this functionality to Azure PowerShell (and in general, the earlier you can reach and maintain parity between Azure PowerShell and the Azure CLI, the better).

For reference: https://docs.microsoft.com/en-ca/azure/cosmos-db/scripts/scale-collection-throughput-cli

**Comment by jagdaleganesh** [comment]
i have installed the azure CLI on my local computer but when try az login , it open the browser for authenticate. Browser authenticate successfully but it never returns to powershell.
Please help

**Comment by cormacpayne** [comment]
@sphibbs Would you mind taking a look?

**Comment by dingmeng-xue** [comment]
CosmosDB team, please evaluate this feature request.

**Comment by MehaKaushik** [comment]
Az.CosmosDB provides Update-AzCosmosDB*Throughput cmdlets for this. 

Link for downloading Az.CosmosDB: https://www.powershellgallery.com/packages/Az.CosmosDB/0.1.6
Some samples here: https://docs.microsoft.com/en-us/azure/cosmos-db/manage-with-powershell#create-db-ru

**Comment by MehaKaushik** [comment]
Please open this issue again, if you have further concerns regarding the same.
