### ISSUE TITLE
The hdinsight demo script is not working in Mooncake

### ISSUE THREAD

**Issue by gangsir** [Azure/azure-powershell#765]
The sample script in the following hdinsight doc is not working because one cmdlet doesn’t return the storage account name as expected. It returns the storage blob endpoint instead. 
https://azure.microsoft.com/en-us/documentation/articles/hdinsight-hadoop-use-mapreduce-powershell/

![image](https://cloud.githubusercontent.com/assets/6658255/9320238/31611d3a-458a-11e5-8ba6-c7ab2d4ccf84.png)
![image](https://cloud.githubusercontent.com/assets/6658255/9320241/3ec1ba98-458a-11e5-98e2-483b5b62d57c.png)
![image](https://cloud.githubusercontent.com/assets/6658255/9320245/48cae172-458a-11e5-8ea9-72a6428c1b74.png)

**Comment by markcowl** [comment]
@gangsir Thank you for filing the issue.  Routing to the HDInsight team for resolution.

**Comment by shefaliv** [comment]
Can you please try with the latest Rm cmdlets and let us know if the issue persists?

**Comment by cormacpayne** [comment]
Closing this issue due to a lack of activity. Please feel free to re-open this issue if the problem has not been solved or you have any other questions.
