### ISSUE TITLE
Please change your documentation dates to a human format !!!

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-powershell#7653]
ALL of the docs are using dates of the form nn/nn/nnnn -- For example: 10/07/2018 -- Is it 10-Jul-2018 or 7-Oct-2018???   Who knows !??    Using dd-mmm-yyyy is the most HUMAN friendly way to display dates as there is simply no room for ambiguity !!

If the docs must use numeric dates, can we not standardize to something like: yyyy-mm-dd (classic sort order)?

I know, a small, trival point -- but it drives me crazy !!!

**Comment by markcowl** [comment]
@bdcoder2 Which dates are you concerned with?  Are these dates as they appear in examples, as metdata about site pages, or somewhere else?

**Comment by bdcoder2** [comment]
Sorry -- the dates displayed immediately under an articles main title, for example:
https://docs.microsoft.com/en-us/powershell/azure/get-started-azureps?view=azurermps-6.11.0
The date displayed under the main title shows: 09/10/2018 -- September, October, who knows !!

**Comment by markcowl** [comment]
@bdcoder2 @arcotek-ltd  So this is directly related to the language code.   en-us is specifically about US ENglish, including the (admittedly illogical) standard US format for dates.

For example, this shows the same date in the (admittedly more logical) international standard format:
https://docs.microsoft.com/en-gb/powershell/azure/get-started-azureps?view=azurermps-6.11.0

**Comment by markcowl** [comment]
Closing, as I believe this resolves the issue.  Please let us know if this is not the case.

**Comment by arcotek-ltd** [comment]
Hi @markcowl, 

I think @bdcoder2 is referring to the dates in your *documentation*. For instance, in the document you have linked, I read the date as 11th September 2018. As your audience is international, perhaps you could consider using the international date format `yyyy-MM-dd` to remove the ambiguity. The better way is to allow the user's browser to format the date as per their devices' local. As discussed here https://stackoverflow.com/questions/7372038/is-there-any-way-to-change-input-type-date-format&ved=2ahUKEwjOpqzin6LeAhVILcAKHc64DvQQjjgwAXoECAUQAQ&usg=AOvVaw31Z6r8mzLnJrB7coYl9-9l

Thanks

**Comment by bdcoder2** [comment]
@arcotek-ltd - that is correct -- I was referring to the ambiguous dates in the documentation; I still believe the best option is dd-mmm-yyyy for human readers of any culture.
