### ISSUE TITLE
ARM mode, storage management without AzureStorageContext parameter will fail with error “storage account not found”

### ISSUE THREAD

**Issue by hula100** [Azure/azure-powershell#766]
In ASM mode, storage management without AzureStorageContext parameter can success once we set CurrentStorageAccountName in current subscription:
![asmstroagesuccess](https://cloud.githubusercontent.com/assets/8871177/9322684/7e1e6eec-45a9-11e5-95a7-88ad1b341fae.PNG)
But in ARM mode, storage management without AzureStorageContext parameter will fail with error “storage account not found” even CurrentStorageAccountName has been set in current subscription:
![armstoragefailure](https://cloud.githubusercontent.com/assets/8871177/9322718/e56bf6c8-45a9-11e5-8e9f-7516ee516156.PNG)
if having AzureStroageContext, it works:
![armstroagesuccess](https://cloud.githubusercontent.com/assets/8871177/9322674/40283316-45a9-11e5-80d7-4ffd42926e5e.PNG)

**Comment by markcowl** [comment]
This should hav ebeen resolved by subsequent releases.  Please open a new issue if you are still seeing this.
