### ISSUE TITLE
[AzureStack] Get-AzureRmResource does not return resource entity if RP namespace in the request URI is in lower-case.

### ISSUE THREAD

**Issue by deathly809** [Azure/azure-powershell#7660]
A customer reported that when calling Get-AzureRmResource where the provider is lowercase does not return anything.  The ARM team also said the request was never sent.

![image](https://user-images.githubusercontent.com/1381210/47440282-b0561b00-d762-11e8-994b-cba30585c11c.png)

**Comment by deathly809** [comment]
The SDK client is case sensitve.  Working on a fix.

https://github.com/Azure/azure-powershell/blob/75722f377a3156c5762fcb984522802cd738eca7/src/StackAdmin/Resources/Commands.ResourceManager/Cmdlets/SdkClient/ResourceManagerSdkClient.cs#L901

**Comment by maddieclayton** [comment]
Closing as fixed. @deathly809 Let me know if I should reopen.

**Comment by deathly809** [comment]
@maddieclayton  was going to close but we have not published the fix yet.  What is the correct way to handle issues?  Once the Fix is merged or when it is released?

**Comment by maddieclayton** [comment]
I usually close them when the PR gets merged, but if you want to keep it open until it gets published we can do that as well.
