### ISSUE TITLE
Serialization Exception thrown by AzureRm.Automation v 6.0.0 - Get-AzureRmAutomationSoftwareUpdateConfiguration

### ISSUE THREAD

**Issue by seandonovancvx** [Azure/azure-powershell#7661]
### Description

In AzureRm.Automation version 6.0.0, cmdlet Get-AzureRmAutomationSoftwareUpdateConfiguration gives the error 'Unable to deserialize the response' if a Next Run Time value is 'None'
The error is occurring because the cmdlet cannot serialize the null value to DateTimeOffset

### Script/Steps for Reproduction

There must be an entry in the Scheduled Update Deployments page for the automation account that has None as the Next Run Time value. Then run the cmdlet Get-AzureRmAutomationSoftwareUpdateConfiguration

### Module Version

AzureRm.Automation v. 6.0.0 (preview)

### Debug Output

Get-AzureRmAutomationSoftwareUpdateConfiguration : Unable to deserialize the response.
At line:1 char:1
+ Get-AzureRmAutomationSoftwareUpdateConfiguration -AutomationAccountNa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmAuto...teConfiguration], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationSoftwareUpdateConfiguration
 
DEBUG: AzureQoSEvent: CommandName - Get-AzureRmAutomationSoftwareUpdateConfiguration; IsSuccess - False; Duration - 00:01:18.6056586; Exception - Microsoft.Rest.SerializationException: Unable
 to deserialize the response. ---> Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.DateTimeOffset'. Path '', line 1, position 527183. ---> System.Arg
umentException: Could not cast or convert from {null} to System.DateTimeOffset.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

**Comment by markcowl** [comment]
@seandonovancvx Could you run Resolve-AzureRmError after this error occurs and provide the results?

**Comment by andyw248** [comment]
Edge case: As per the description, a user would have to create a schedule with "none" as the scheduled time, which appears to be a very uncommon scenario. Closing.
