### ISSUE TITLE
Fix static analysis to pick up alias for a renamed param

### ISSUE THREAD

**Issue by praries880** [Azure/azure-powershell#7662]
Currently static analysis does not pick up the alias added for the old name of a param after it is renamed and wrongly errors saying that the param set the param belonged to is now deleted.

example  : https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/8583/artifact/src/Package/
PR : https://github.com/Azure/azure-powershell/pull/7655

**Comment by cormacpayne** [comment]
This has been fixed.
