### ISSUE TITLE
New-AzureRMRoleAssignment throws 'roleDefinitions' could not be found...for api version 2018-01-01-preview

### ISSUE THREAD

**Issue by mattcowen** [Azure/azure-powershell#7670]
When I run 
```
New-AzureRmRoleAssignment -RoleDefinitionName Owner -ServicePrincipalName <guid>
```
I get 
```
New-AzureRmRoleAssignment : The resource type 'roleDefinitions' could not be found in the namespace 'Microsoft.Authorization' for api version '2018-01-01-preview'. The supported 
api-versions are '2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01,2015-07-01'.
At line:1 char:1
+ New-AzureRmRoleAssignment -RoleDefinitionName Owner -ServicePrincipal ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmRoleAssignment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand
```

Module Version 6.11.0

Can anyone explain why I am seeing this please?

**Comment by darshanhs90** [comment]
@mattcowen Can you share the Debug trace, it will help us determine the reason behind the issue you are seeing

**Comment by deathly809** [comment]
@darshanhs90  I think they are running this against Azure Stack, as those are the exact ApiVersions we support for roleAssignment.

@mattcowen If you are using Azure Stack please install AzureRM 2.3.0 for all Azure-PowerShell supported modules.  Or if you only need this cmdlet for now you can use AzureRM.Resources 6.0.2.

There is also a guide [here](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-powershell-install) as well.

**Comment by mattcowen** [comment]
It's right that I have been using Stack however currently my development machine has only AzureRm for public cloud. I was using AzureRm.Bootstrapper however the scripts I was running were not picking up the correct modules and so I cleared down and installed only AzureRm 6.11.0. Just checked Get-AzureRmContext and I see that my environment is set to my AzureStackUser. I will reset and reopen if I encounter any issues. 

Thanks all
