### ISSUE TITLE
Get-AzureRmRoleAssignment -Scope "/subscriptions/$SubscriptionId -IncludeClassicAdministrator not returning expected results

### ISSUE THREAD

**Issue by clfilipe** [Azure/azure-powershell#7679]
The command Get-AzureRmRoleAssignment -Scope "/subscriptions/$SubscriptionId does not return the Role Assignments of the subscription that was defined on scope. It only provides the Role assignments that are available for the subscription that is set at the moment of "Connect-AzureRmAccount". The user is not able to change the subscription if he does not run Select-AzureRmSubscription -SubscriptionId $SubscriptionId before running Get-AzureRmRoleAssignment. This is not what the documentation states and the PowerShell command should be reviewed.

**Comment by markcowl** [comment]
@clfilipe Can you please provide a debug trace showing an improperly returned role assignment?

Per the issue template, set ```$DebugPreference="Continue"``` and then execute the cmdlet with the aberrant behavior

**Comment by clfilipe** [comment]
Hello Mark,

Thank you for your e-mail.
As requested, please find attached the Debug for the following command:

$DebugPreference = “Continue”
Start-Transcript -path c:\GetAzureRmRoleAssignment.txt
Connect-AzureRmAccount -TenantId 1b775e95-f070-4703-99c1-7d7ca62539dc
Get-AzureRmRoleAssignment -Scope "/subscriptions/c36c3336-1b80-461f-afc6-0e794a55dfc9" -IncludeClassicAdministrators
Stop-Transcript
$DebugPreference = 'SilentlyContinue'

We can see below that the subscription does not change for the Classic Administrator Roles when I try to scope.
The user (photo@actionfour.onmicrosoft.com<mailto:photo@actionfour.onmicrosoft.com>) is logged in and using the subscription bb5a765b-597f-49c1-a302-0881cfbcbc55 so all of the co-admin requests are targeting this subscription even though I am changing the scope for c36c3336-1b80-461f-afc6-0e794a55dfc9.
Currently, we need to run the command Select-AzureRmSubscription -SubscriptionId $subscriptionId before in order to return Classic Role assignments for that sub.

[cid:image002.jpg@01D46F14.07614030]

Hope this was helpful to explain what I am trying to share. Let me know if you need anything else.

Thank you very much and best regards,

Cláudia Paiva Filipe
Support Engineer
EMEA Cloud Identity POD Support
Customer Service and Support
Office: +351 (21) 0602345
Claudia.Filipe@microsoft.com<mailto:Claudia.Filipe@microsoft.com>
9:00 – 18:00 (UTC)
[cid:image003.png@01D341B8.7D1BACF0]
﻿Alternate Contacts if I am unavailable:
Backup | cloudidpodemea@microsoft.com
Team Manager | Susana Rodrigues (susanar@microsoft.com<mailto:susanar@microsoft.com>)  +351 (21) 0491316

If you have any feedback about my work, please let either me or my manager Susana Rodrigues know at susanar@microsoft.com<mailto:susanar@microsoft.com>

**Comment by darshanhs90** [comment]
@sneivandt Is looking in to fixing this

**Comment by darshanhs90** [comment]
Closing this issue as this fixes it https://github.com/Azure/azure-powershell/pull/7743
