### ISSUE TITLE
WebApp Testing in Production Routing Rules not supported in RM Cmdlets

### ISSUE THREAD

**Issue by pquinn262** [Azure/azure-powershell#7682]
With the [Service Management API’s being deprecated](https://blogs.msdn.microsoft.com/appserviceteam/2018/03/12/deprecating-service-management-apis-support-for-azure-app-services/) there appears to be some missing functionality in the RM Cmdlets.  

@ruslany mentioned it earlier this week in regards to how this impacts a bunch of cmdlets.  
https://github.com/Azure/azure-powershell/issues/7558#issuecomment-432838004

And @panchagnula has an issue open to actually mark the cmdlets as deprecated.
https://github.com/Azure/azure-powershell/issues/7668 

The cmdlet I’m most concerned with is Set-AzureWebsite.  We’re using that in our deployment process to set the Testing in Production Routing Rules with a PowerShell script that uses the RoutingRules parameter. 

I’m unable to find a way to set TiP Routing Rules on a Web App using the RM Cmdlets.  Will this functionality be added before those API’s are decommissioned?

Thanks!

**Comment by markcowl** [comment]
@panchagnula Can you take  a look?

**Comment by pquinn262** [comment]
We’re updating the routing rules similarly to what was shown by @mbcrump here: https://www.michaelcrump.net/azure-tips-and-tricks24/

Below is the script we’ve got running through Octopus Deploy.  It will output the current rules, change them, and then display the result.
```
$siteName = "XXXXXXX"

$Value = 15
$Step = 5
$Min = 15
$Max = 40
$interval = 5

$pwd = ConvertTo-SecureString -String "$pass" -AsPlainText -Force 
$AdminCred = New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList "XXXXXXXXXXXXXXXXX", $pwd

Add-AzureAccount -Credential $AdminCred -TenantId "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" | Out-Null
Select-AzureSubscription -SubscriptionName "XXXXXXXXXXXXXXXXXXXXXX"

$routeRule = New-Object Microsoft.WindowsAzure.Commands.Utilities.Websites.Services.WebEntities.RampUpRule
$routeRule.ActionHostName = $siteName + "-XXXXXX.azurewebsites.net"
$routeRule.ReroutePercentage = $Value;
$routeRule.Name = "NextRelease"

$routeRule.ChangeIntervalInMinutes = $Interval;
$routeRule.ChangeStep = $Step;
$routeRule.MinReroutePercentage = $Min;
$routeRule.MaxReroutePercentage = $Max;

Write-Host "CURRENT ROUTING SETTINGS:"
$site = Get-AzureWebsite $siteName -Slot Production
$site.RoutingRules | Format-List

Write-Host "DESIRED ROUTING RULE:"
$routeRule | Format-List
Try
{
 Set-AzureWebsite $siteName -Slot Production -RoutingRules $routeRule -Verbose
}
Catch
{
  Write-Host $_.Exception.Message
  Write-Host $_.Exception.ItemName
  Write-Host $_.Exception
}

Write-Host "UPDATED ROUTING SETTINGS:"
$site = Get-AzureWebsite $siteName -Slot Production
$site.RoutingRules | Format-List
```

**Comment by panchagnula** [comment]
@pquinn262 ,We will add support to RoutingRules with the SETAZURERM command, before the existing one is deprecated, thanks for bringing this to our attention.

**Comment by panchagnula** [comment]
Here is a workaround for the commandlet
$appName = "<AppService Name>";
$apiVersion = ((Get-AzureRmResourceProvider -ProviderNamespace "Microsoft.Web").ResourceTypes | Where-Object ResourceTypeName -eq sites).ApiVersions[0];
$appService = Get-AzureRmWebApp -Name $appName;
$appConfig = Get-AzureRmResource -ResourceType "Microsoft.Web/sites/config" -ResourceName $appService.Name -ResourceGroupName $appService.ResourceGroup -ApiVersion $apiVersion;

$tipRules =@();
$tr = new-object -type psobject -Property @{actionHostName='xxx-yyy.azurewebsites.net'; reroutePercentage=Value;name='yyy'}
$tipRules =$appConfig.properties.experiments.rampUpRules;
$tipRules+=$tr;
$appConfig.Properties.experiments.rampUpRules = $tipRules

$appConfig | Set-AzureRmResource  -ApiVersion $apiVersion -Force -ResourceType "Microsoft.Web/sites/config"

**Comment by panchagnula** [comment]
moved this to another milestone.

**Comment by panchagnula** [comment]
Fixed by PR https://github.com/Azure/azure-powershell/pull/11271
