### ISSUE TITLE
Register-AzAutomationDscNode 'The term 'New-AzureRmResourceGroupDeployment' is not recognized'

### ISSUE THREAD

**Issue by lukeb1961** [Azure/azure-powershell#7691]
PS> (get-module -name az).Version
Major  Minor  Build  Revision
-----  -----  -----  --------
0      4      0      -1

PS> $PSversiontable
Name                           Value                                                                             
----                           -----                                                                             
PSVersion                      5.1.17763.1                                                                       
PSEdition                      Desktop                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                           
BuildVersion                   10.0.17763.1                                                                      
CLRVersion                     4.0.30319.42000                                                                   
WSManStackVersion              3.0                                                                               
PSRemotingProtocolVersion      2.3                                                                               
SerializationVersion           1.1.0.1 

ISSUE:
previously functional script under AzureRM contains: 
$Registration=Register-AZAutomationDscNode -AzureVMName $SydneyWinSvr -AzureVMLocation $Sydney `
                                                         -AzureVMResourceGroup $RG -ResourceGroupName $RG `
                                                         -AutomationAccountName $MelAutomation `
                                                         -NodeConfigurationName $nodeconf.Name `
                                                         -ConfigurationMode 'ApplyAndAutocorrect' `
                                                         -AllowModuleOverwrite $true  `
                                                         -RebootNodeIfNeeded $true

ERRORS with:
Register-AZAutomationDscNode : The term 'New-AzureRmResourceGroupDeployment' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At line:181 char:24
+ ... egistration=Register-AZAutomationDscNode -AzureVMName $SydneyWinSvr - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Register-AzAutomationDscNode], CommandNotFoundException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.RegisterAzureAutomationDscNode

**Comment by markcowl** [comment]
@lukeb1961 Are you able to work around this using ```Enable-AzureRmAlias``` before executing the cmdlet?

**Comment by lukeb1961** [comment]
Hello Mark,  Added 
  Enable-AzureRmAlias 
to the line beforehand. No, still failed with the same error.

**Comment by markcowl** [comment]
### Description
- Update the script in the cmdlet with the appropriate cmdlet name for Az
- Work with the Automationt eam to verify and add regression test

### Cost: 1

**Comment by MiYanni** [comment]
@markcowl Work for this was already completed in: https://github.com/Azure/azure-powershell/pull/7671
This PR added tests and fixed the cmdlet name issue. You can see the cmdlet names being fixed here:
https://github.com/Azure/azure-powershell/pull/7671/files#diff-1ee47953698b63a50619e0ed1ad9046cR75

This was only merged into the Automation branch. So, once that gets merged into preview, the fix for this will be there.

**Comment by markcowl** [comment]
This will be in the 11/20 release
