### ISSUE TITLE
New-AZServiceFabricCluster : Can't find the template or parameter file

### ISSUE THREAD

**Issue by lukeb1961** [Azure/azure-powershell#7692]
AZ 0.4.0

previously functional script now silently fails to create a Service Fabric cluster.
  New-AZServiceFabricCluster -Name $ServiceFabricClustername `
                                       -ResourceGroupName $RGSF -Location $Melbourne `
                                       -ClusterSize $clustersize `
                                       -VmUserName $user -VmPassword $securepasswd `
                                       -CertificateSubjectName $certSubjectName `
                                       -CertificatePassword $certpwd `
                                       -CertificateOutputFolder $certfolder `
                                       -OS WindowsServer2016DatacenterwithContainers `
                                       -VmSku $AzureVMsize `
                                       -KeyVaultName $KeyVaultMelSF -Debug

Debug mode shows it thinks it's in the parameter set that leverages an ARM template...

DEBUG: 16:14:13 - NewAzureRmServiceFabricCluster begin processing with ParameterSet 'ByDefaultArmTemplate'.
DEBUG: 16:14:16 - using account id 'LukeBrennan@outlook.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'LukeBrennan@outlook.com', environment: 'AzureCloud'
, tenant: '1f89577f-4235-4965-83e5-aad1a7e761fc'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourceGroups/lukebrennan-Service
FabricMel/providers/Microsoft.ServiceFabric/clusters/winsfcluster?api-version=2016-09-01

Headers:
x-ms-client-request-id        : e6576d6e-70b0-43c7-bd52-743ddc8505ed
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : db0941ec-5f32-4c80-989f-4a8e26c3c4c2
x-ms-correlation-request-id   : db0941ec-5f32-4c80-989f-4a8e26c3c4c2
x-ms-routing-request-id       : AUSTRALIAEAST:20181029T051417Z:db0941ec-5f32-4c80-989f-4a8e26c3c4c2
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Mon, 29 Oct 2018 05:14:16 GMT

Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.ServiceFabric/clusters/winsfcluster' under resource group 'lukebrennan-Ser
viceFabricMel' was not found."
  }
}

New-AZServiceFabricCluster : Can't find the template or parameter file
At line:1 char:1
+ New-AZServiceFabricCluster -Name $ServiceFabricClustername `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzServiceFabricCluster], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster
 
DEBUG: AzureQoSEvent: CommandName - New-AzServiceFabricCluster; IsSuccess - False; Duration - 00:00:08.9506088; Ex
ception - System.Management.Automation.PSInvalidOperationException: Can't find the template or parameter file
   at Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster.DeployWithDefaultTemplate()
   at Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 16:14:24 - NewAzureRmServiceFabricCluster end processing.
DEBUG: 16:14:24 - NewAzureRmServiceFabricCluster end processing.

**Comment by markcowl** [comment]
@lukeb1961 Thanks for the report.  Do you know which version of AzureRM you last successfully executed this script with?

**Comment by lukeb1961** [comment]
This chunk of my script works absolutely fine with AzureRM 6.8.1
I then change to AZ 0.4.0 on my other machine , replace 
. New-AzureServiceFabricCluster with 
. New-AZServiceFabricCluster and
 it fails.

Note I also see (with AZ 0.4.0) when I run New-AZServiceFabricCluster
WARNING: The provided information does not map to an AD object id.
WARNING: Access policy is not set. No user or application have access permission to use this vault. This can happen if the vault was created by a service principal. Please use Set-AzureRmKeyVaultAccessPolicy to set access policies.

I do NOT see any of this with AzureRM. I assume storage has some new policy requirements/behaviour  but the error appears to be talking about template/params as if the parameter-set is confused.

**Comment by markcowl** [comment]
@MiYanni This is likely related to ifdefs work, cna you take a look?

**Comment by markcowl** [comment]
@vaishnavk @juhacket Can you please take a look?  It appears that the cmdlet throws after not finding the cluster, when the cluster is being created.

**Comment by lukeb1961** [comment]
STILL happens with az 1.0.1

PS C:\WINDOWS\system32>   $SFC=New-azServiceFabricCluster -Name $ServiceFabricClustername `
                                       -ResourceGroupName $RGSF -Location $Melbourne `
                                       -ClusterSize $clustersize `
                                       -VmUserName $user -VmPassword $securepasswd `
                                       -CertificateSubjectName $certSubjectName `
                                       -CertificatePassword $certpwd `
                                       -CertificateOutputFolder $certfolder `
                                       -OS WindowsServer2016DatacenterwithContainers `
                                       -VmSku $AzureVMsize `
                                       -KeyVaultName $KeyVaultMelSF -KeyVaultResouceGroupName $RGSF -debug
DEBUG: 5:31:01 PM - NewAzureRmServiceFabricCluster begin processing with ParameterSet 'ByDefaultArmTemplate'.
DEBUG: 5:31:03 PM - using account id 'lukeb@microsoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'lukeb@microsoft.com', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/5bf4e2b7-a38f-4aea-b649-6327151af3a9/resourceGroups/lukeb-AZ-ServiceFabricMel/providers/Microsoft.ServiceFabric/clusters/winsfcluster?api-version=2018-02-01

Headers:
x-ms-client-request-id        : e2411e55-5c66-49d3-b449-85df03872f2f
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : f768a6ae-12a9-4a7f-a619-d3fdbae0f149
x-ms-correlation-request-id   : f768a6ae-12a9-4a7f-a619-d3fdbae0f149
x-ms-routing-request-id       : AUSTRALIAEAST:20181221T063055Z:f768a6ae-12a9-4a7f-a619-d3fdbae0f149
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Fri, 21 Dec 2018 06:30:55 GMT

Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.ServiceFabric/clusters/winsfcluster' under resource group 'lukeb-AZ-ServiceFabricMel' was not found."
  }
}


New-azServiceFabricCluster : Can't find the template or parameter file
At line:1 char:8
+   $SFC=New-azServiceFabricCluster -Name $ServiceFabricClustername `
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzServiceFabricCluster], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster
 
DEBUG: AzureQoSEvent: CommandName - New-AzServiceFabricCluster; IsSuccess - False; Duration - 00:00:16.4856007; Exception - System.Management.Automation.PSInvalidOperationException: Can't find the template or parameter file
   at Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster.DeployWithDefaultTemplate()
   at Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 5:31:19 PM - NewAzureRmServiceFabricCluster end processing.
DEBUG: 5:31:19 PM - NewAzureRmServiceFabricCluster end processing.

**Comment by lukeb1961** [comment]
appears to be FIXED in 1.3.0
