### ISSUE TITLE
Set-AzResource  / Set-AzureRMResource - Tag "Name" starts with lowercase /  Powershell Core

### ISSUE THREAD

**Issue by matthiasluedke** [Azure/azure-powershell#7703]
### Description

Applied tags via Set-AzResource / Set-AzureRMResource are starting with Lower Letter
Example

Set-AzResourceGroup
Tag:
Name: "Associated to" / Value:  "Abcde" -> Correct
Name: "Application Stack" / Value: "ABCDE" -> Correct

Set-AzResource
Tag:
Name: "associated to" / Value:  "Abcde" -> Wrong
Name: "application Stack" / Value:  "ABCDE" ->wrong

### Script/Steps for Reproduction

Set-AzResource -ResourceId $vminfo.Id -Tag $tags -Force

### Module Version

PSVersion 6.1.0
Modules
Az Version 0.4.0
Az Version 0.5.0
AzureRM.Netcore 0.13.1

**Comment by maddieclayton** [comment]
@ravbhatnagar Please take a look at this issue.

**Comment by matthiasluedke** [comment]
Same issue wit latest Az Version 0.5.0

**Comment by markcowl** [comment]
Fix in this commit: https://github.com/markcowl/azure-powershell/commit/f78806a1bfdb32ae20e5c86cb815bcf33c3e5ea7 

Filx will be released on 11/20
