### ISSUE TITLE
New-AzureResourceGroupDeployment hangs on creating second deployment in ResourceGroup

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#771]
# Problem

In the Azure PowerShell module 0.9.7, running on Windows 10 Enterprise RTM, the `New-AzureResourceGroupDeployment` command hangs while creating a second deployment in a given ARM ResourceGroup.

``` powershell
### Switch to ARM mode
Switch-AzureMode -Name AzureResourceManager;

### Authenticate to Azure
Add-AzureAccount;

$Deploy = @(
    @{
        TemplateUri = 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-simple-windows-vm/azuredeploy.json';
        Name = 'VMDeploy';
        ResourceGroupName = 'VMDeploy';
        Mode = 'Incremental';
        TemplateParameterObject = @{
            newStorageAccountName = 'mystorage';
            adminUsername = 'tsullivan';
            adminPassword = 'PNB]YQ[]SLdXPPY';
            dnsNameForPublicIP = 'trevor';
            };
    };
    @{
        TemplateUri = 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-simple-windows-vm/azuredeploy.json';
        Name = 'VMDeploy2';
        ResourceGroupName = 'VMDeploy';
        Mode = 'Incremental';
        TemplateParameterObject = @{
            newStorageAccountName = 'mystorage2';
            adminUsername = 'tsullivan';
            adminPassword = 'PNB]YQ[]SLdXPPY';
            dnsNameForPublicIP = 'trevor';
            };
    };);

### Create the ARM Resource Group
New-AzureResourceGroup -Name $Deploy[0].ResourceGroupName -Location 'West US';

### Deploy the ARM Template to the Resource Group
$Deploy | % { New-AzureResourceGroupDeployment @PSItem };
```
# Expected Result

The `New-AzureResourceGroupDeployment` command should not hang.

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by pcgeek86** [comment]
I think this is happening because the VM in both "deployments" has the same name. The second deployment, instead of creating a new VM, is trying to patch/update the existing VM, which is causing an error (see screenshot). Is this an ARM REST API issue or specific to the Resource Provider?

I would expect that the API would not hang indefinitely, but rather throw an exception.

![image](https://cloud.githubusercontent.com/assets/466713/9426931/820b4f44-491d-11e5-829f-4a3bc29d51ad.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by mtowse** [comment]
It hangs for me also using this example.

https://azure.microsoft.com/en-gb/documentation/articles/hdinsight-hadoop-create-linux-clusters-arm-templates/

**Comment by markcowl** [comment]
@ravbhatnagar Can you take a look?

**Comment by ravbhatnagar** [comment]
Looks like it works when using the simple VM example above. @mtowse - Can you please elaborate on what is failing for you?

**Comment by ravbhatnagar** [comment]
Please let me know if you still run into this issue. Closing this issue for now.
