### ISSUE TITLE
Module: Az 0.4.0 - No help file contents

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [Azure/azure-powershell#7716]
None of the Az modules I've reviewed have detailed help files when compared to the AzureRM module counterparts.

The Az modules also do not support updatable help thus "update-help" will fail

**Comment by markcowl** [comment]
Yes, there will be no help for Az until the 12/4 release. 

Update-help is not supported for *any* of our modules, as they always ship with updated help.
