### ISSUE TITLE
New-AzureRMVirtualNetwork fails to run in automation runbook since 6.9.0

### ISSUE THREAD

**Issue by Danrawlings-msft** [Azure/azure-powershell#7723]
### Description

Since the AzureRM.Network module version 6.9.0 the following runbook fails to run and does not return any error information. The script executes fine in PowerShell or if executed on a hybrid worker . Also works fine if module is downgraded to previous 6.8.0 version in the automation account. 
degubprefence is set to Continue but there is no message returned after the breakingchange output from the cmdlet. I've attached the runbook output showing it execute three times then suspend but it is easily reproducible. 

IcM 90091668 raised with Automation

### Script/Steps for Reproduction

Runbook code :
```
param (
[string]$E16ResourceGroupName)
$global:DebugPreference = "Continue"
function NewAzureRMResourceGroup
{
param ([string]$resourceGroupName,
[string]$location)
#create new resource group
$resourceGroup = Get-AzureRmResourceGroup -Name $resourceGroupName -ErrorAction SilentlyContinue
if (!$resourceGroup)
{
Write-Output 'Resource group '$resourceGroupName' does not exist. To create a new resource group, please enter a location.'
if (!$location)
{
$location = Read-Host 'resourceGroupLocation'
}
Write-Output 'Creating resource group '$resourceGroupName' in location '$location''
New-AzureRmResourceGroup -Name $resourceGroupName -Location $location
}
else
{
Write-Output 'Using existing resource group '$resourceGroupName''
}
}
function CreateAzureVirtualNetwork
{
param ([string]$resourceGroupName,
[string]$locationName,
[string]$virtualNetworkNameParam,
[string]$addressSpace,
[string]$subnetAddressRange,
[string]$dnsServerIp)
#create Azure Virtual Network
Write-Output $resourceGroupName $locationName $virtualNetworkName $addressSpace $subnetAddressRange $dnsServerIp
$subnetConfig = New-AzureRMVirtualNetworkSubnetConfig -Name ($virtualNetworkNameParam + '_subnetConfig') -AddressPrefix $subnetAddressRange
Write-Output 'created subnet config'
New-AzureRMVirtualNetwork -Name $virtualNetworkNameParam -ResourceGroupName $resourceGroupName -Location $locationName -AddressPrefix $addressSpace -Subnet $subnetConfig -DNSServer $dnsServerIp
Write-Output 'created network'
}
$Conn = Get-AutomationConnection -Name AzureRunAsConnection
Connect-AzureRmAccount -ServicePrincipal -Tenant $Conn.TenantID -ApplicationID $Conn.ApplicationID -CertificateThumbprint $Conn.CertificateThumbprint
$AzureContext = Select-AzureRmSubscription -SubscriptionId $Conn.SubscriptionID 
$resourceGroupName = 'Temp' + '-' + $E16ResourceGroupName
$virtualNetworkName = $resourceGroupName + '-vnet'
$location = 'East Asia'
NewAzureRMResourceGroup -resourceGroupName $resourceGroupName -location $location
Start-Sleep 5
Write-Output "CreateAzureVirtualNetwork -resourceGroupName $resourceGroupName -locationName $location -virtualNetworkNameParam $virtualNetworkName -addressSpace '10.0.5.0/24' -subnetAddressRange '10.0.5.0/24' -dnsServerIp '10.0.5.9'"
CreateAzureVirtualNetwork -resourceGroupName $resourceGroupName -locationName $location -virtualNetworkNameParam $virtualNetworkName -addressSpace '10.0.5.0/24' -subnetAddressRange '10.0.5.0/24' -dnsServerIp '10.0.5.9'
```
### Module Version

Azure automation account - Update Azure Modules task run 

### Environment Data

Issue only presents in Azure automation

### Debug Output

[JobStreams.txt](https://github.com/Azure/azure-powershell/files/2538622/JobStreams.txt)

**Comment by markcowl** [comment]
@chandrasekarsrinivasan @avijitgupta Please take a look and respond to the customer

**Comment by Danrawlings-msft** [comment]
Looks like this is a memory consumption problem in the new version of the cmdlets? Runbook gets terminated under fair share as it consumes more than 400Mb. This doesn't happen using the same script and version 6.8.0 or lower

**Comment by Am018** [comment]
@Danrawlings-msft is that something you are looking into?

**Comment by Danrawlings-msft** [comment]
@Am018 . No, I just realized this was the reason azure automation was suspending the job and thought it might help the investigation. We need to understand why the latest version of the module causes this behavior and correct if it's a bug. Quite a few customers are hitting this.

**Comment by mattbowes** [comment]
I am having the same issue. Module versions after 6.8.1 are suspending our runbooks. Downgrading to 6.8.1 resolves the issue. I opened a ticket with support and they tell me that the runbook is using more than 400MB of memory and that's why it gets suspended

**Comment by mattbowes** [comment]
Also this issue is happening outside of `New-AzureRMVirtualNetwork`. We dot not call that cmdlet in any of our runbooks but we experience the same issue. We are using `Get-AzureRmVirtualNetwork` from the AzureRM.Network module

**Comment by Danrawlings-msft** [comment]
Fixed in later version. closing
