### ISSUE TITLE
Add new cmdlet to remove all AzureRM modules

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#7726]
Add new cmdlet "Uninstall-AzureRm" that removes AzureRM from the users machine

Uninstall-AzureRm [-PassThru]

**Comment by deathly809** [comment]
Does this also remove modules which are installed by it?  Or is this just a "delete the folder" cmdlet?

**Comment by maddieclayton** [comment]
The default behavior will be to delete any module that starts with "AzureRM".  If given a version, it will delete all modules that were released with that version of the AzureRM rollup module.  To be clear, this is my proposed design and hasn't been approved by the rest of the team.

**Comment by deathly809** [comment]
How is this different from Uninstall-Module?

**Comment by maddieclayton** [comment]
Uninstall-Module does not remove dependent modules.  So if you run Uninstall-Module on AzureRM, you will just delete the empty rollup module and none of the actual AzureRM modules.  So if a user wants to delete all AzureRM modules they will need to run Uninstall-Module 55 times on each module, and double or triple that if they have multiple version of each module on the machine.
