### ISSUE TITLE
ARM:Help Content for new-AzureStorageAccount

### ISSUE THREAD

**Issue by robplank** [Azure/azure-powershell#773]
the Syntax shows a parameter *Name* but the actual parameter is *accountname* like shown in the example of the cmdlet

current help content 
get-help New-AzureStorageAccount 

NAME
    New-AzureStorageAccount
    
SYNOPSIS
    Allows you to create a new Storage Account
    
    
SYNTAX
    New-AzureStorageAccount [-ResourceGroupName] <String> **[-Name]** <String> [-Type] <String> [-Location] <String> [-Profile <AzureProfile>] [<CommonParameters>]
    
    
DESCRIPTION
    This cmdlet allows you to create a new Storage Account.
    

RELATED LINKS

REMARKS
    To see the examples, type: "get-help New-AzureStorageAccount -examples".
    For more information, type: "get-help New-AzureStorageAccount -detailed".
    For technical information, type: "get-help New-AzureStorageAccount -full".

Current Help Example: 
get-help New-AzureStorageAccount -Examples

NAME
    New-AzureStorageAccount
    
SYNOPSIS
    Allows you to create a new Storage Account
    
    --------------------------  Example 1  --------------------------
 New-AzureStorageAccount -ResourceGroupName "myResourceGroup" **-AccountName** "myStorageAccount" -Location "US West" -Type "Standard_GRS"

**Comment by pcgeek86** [comment]
What PowerShell module version are you using? I suspect you are using an old one. The latest module is correct.

![image](https://cloud.githubusercontent.com/assets/466713/9370650/09928a72-468f-11e5-9e40-5205900b602b.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by robplank** [comment]
the 0.9.7 module doesn't have this issue

**Comment by markcowl** [comment]
This should be resolved in later releases.  Please open an issue if you see a recurrence.
