### ISSUE TITLE
ObjectID in RoleAssignment Cmdlets should be String instead of GUID for ADFS scenarios

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#7736]
The ObjectId Param in RoleAssignment cmdlets Get-AzRoleAssignment, New-AzRoleAssignment and Remove-AzRoleAssignment should be relaxed to string instead of GUID

Relaxing to string in the parameter is not a breaking change for the cmdlet usage. The return object model change will be a breaking change. I think it is a good change to take when Az is in preview mode right now.

Without this change, the latest az module roleassignment cmdlets will not work against azurestack ADFS environment

**Comment by cormacpayne** [comment]
@bganapa is there any need for the `AdfsId` property on [`PSADObject`](https://github.com/Azure/azure-powershell-common/blob/dev/src/Graph.Rbac/ActiveDirectory/PSADObject.cs#L25) if we are able to make the corresponding `Id` property of type `string`? If so, do we have any need for [this method](https://github.com/Azure/azure-powershell-common/blob/dev/src/Graph.Rbac/ActiveDirectory/ActiveDirectoryClientExtensions.cs#L35-L49) anymore?

**Comment by bganapa** [comment]
Thanks for reaching out. This is the commit that I added
https://github.com/Azure/azure-powershell-common/commit/0b86d217d7e537482472151193138ffe0bc2045d#diff-0694ea70afa175a0d7b745bdebf4d5b1

I would prefer removing AdfsId and change the Id type to be string. AssignObjectId method will not be needed

**Comment by bganapa** [comment]
Also please note that the following Guid also needs to be changed to string

They are essentially string by the contract, I think ole PS* objects treats them as GUID. 

https://github.com/Azure/azure-powershell-common/blob/dev/src/Graph.Rbac/ActiveDirectory/PSADApplication.cs#L24

        public Guid ApplicationId { get; set; }

https://github.com/Azure/azure-powershell-common/blob/dev/src/Graph.Rbac/ActiveDirectory/PSADApplication.cs#L32

https://github.com/Azure/azure-powershell-common/blob/dev/src/Graph.Rbac/ActiveDirectory/PSADServicePrincipal.cs#L23

**Comment by cormacpayne** [comment]
This should be fixed as a part of https://github.com/Azure/azure-powershell/pull/7991
