### ISSUE TITLE
Get-AzureVirtualNetworkGateway has mandatory -ResourceGroupName parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#774]
# Problem
- Azure PowerShell 0.9.7
- Windows 10 Enterprise RTM

The `Get-AzureVirtualNetworkGateway` command has a mandatory `-ResourceGroupName` parameter on the default parameter set.
# Expected Result
1. The `-ResourceGroupName` parameter should be non-mandatory.
2. The `Get-AzureVirtualNetworkGateway` command should be callable with no parameters.
3. The `Get-AzureVirtualNetworkGateway` command should list out all virtual network gateways, by default, regardless of which Resource Group contains them.

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
Old issue, looks like it's still valid for Get-AzureRMLocalNetworkGateway and others.  @deepakrajendranmsft can you take a look?

**Comment by DeepakRajendranMsft** [comment]
@lamchester please take a look
