### ISSUE TITLE
'az account get-access-token' equivalent in Azure PowerShell

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/azure-powershell#7752]
Right now the Azure Functions CLI relies on Azure PowerShell in order to get an access token to interact with the Azure API:

https://github.com/Azure/azure-functions-core-tools/blob/60ea24fd4408ea876882324a9505c2d43bb37726/src/Azure.Functions.Cli/Actions/AzureActions/BaseAzureAction.cs#L72-L96

I [opened an issue](https://github.com/Azure/azure-functions-core-tools/issues/840) on them to change it but they consider it by design because of how complicated it is to get an access token.

Apparently there was an attempt to get this to work in Azure PowerShell as well but unfortunately, there was no way to retrieve the access token needed.

in Azure CLI, it's simple. All you do it:

```
az account get-access-token
```

I noticed that on the context object that comes back from `Get-AzContext` there is a property called `Account` which has an `AccessToken` property that is not set:

```
PS > (Get-AzContext).Account


Id                    : xxxxxxxx
Type                  : User
Tenants               : {xxxxxxxxxxxxxxxxxxx}
AccessToken           :
Credential            :
TenantMap             : {}
CertificateThumbprint :
ExtendedProperties    : {[Subscriptions, xxxxxxxxxxxx]
                        , [Tenants, xxxxxxxxxx]}



PS > (Get-AzContext).Account.AccessToken
PS >
```

Can this AccessToken property be set so that a user doesn't have to rely on Azure CLI to get it?

I also tried this:

```powershell
$context = Get-AzContext; $context.TokenCache.ReadItems() | ? TenantId -eq $context.TenantId | % { $_.AccessToken }
```

but noticed that all of my tokens in the TokenCache were already expired.

**Comment by markcowl** [comment]
@TylerLeonhardt Thanks for the report.  It is actually intentional that we don't expose tokems, for a few reasons:
- They are secret
- They can expire, and while there are refresh tokens, it can be difficult to use one to obtain a new access token from a refresh token
- They are an implementation detail that users shouldn't have to worry about

There are a few options to use instead:
- Use PowerShell's TokenCache with ADAL calls to authenticate a request
- MSI Auth 

If you can tell us a bit more about how you are using the token, there ay be additional options

**Comment by TylerLeonhardt** [comment]
The problem I am facing was that the Azure Functions CLI (`func` not a part of Azure CLI or Azure PowerShell) relied on the Azure CLI to obtain an access token. See related issue here:
https://github.com/Azure/azure-functions-core-tools/issues/840

I don't agree that they should be relying on Azure CLI but I'm going with it... and am trying to get the same token via Az.Profile so I can rely on that if Azure CLI isn't available.

I attempted and eventually succeeded in a way to obtain an access token via Az.Profile... but with a fair bit of effort. See the PR here to the `func` CLI:
https://github.com/Azure/azure-functions-core-tools/pull/873

Specifically the code is:

```powershell
$currentAzureContext = Get-AzContext
$azureRmProfile = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile;
$profileClient = New-Object Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient($azureRmProfile);
$profileClient.AcquireAccessToken($currentAzureContext.Subscription.TenantId).AccessToken;
```

**Comment by TylerLeonhardt** [comment]
I don't think I'd consider it fixed.

Is my snippet of code something I can rely on for the future?

> The underlying scenario

Some context - the `func` CLI aka Azure Functions Core Tools is the data plane interface with Azure Functions. It allows you to work with Azure Functions locally AND publish them to Azure.

In order to publish to Azure, it needs an access token so that it can make the necessary API calls to Azure.

Their reasoning (as described in the issue linked) is that there are a multitude of different ways to log in to Azure (with multiple environments) and the `func` CLI didn't want to handle authentication when the Azure CLI  already does a great job at doing so.

So they relied on the Azure CLI command:

```
az account get-access-token
```

To get the token to interact with the Azure API.

I wanted them to conditionally use Azure PowerShell for users of the `func` CLI that only use Azure PowerShell, but getting the access token from Azure PowerShell was more than trivial (see code above).

**Comment by TylerLeonhardt** [comment]
Cc dev of Functions team, @ahmelsayed

**Comment by brandonh-msft** [comment]
Underlying scenario for me is trying to hit the Kusto API which requires a token created against the `.kusto.windows.net` resource URI. The default tokens coming thru off `AzContext` don't work.

**Comment by samarths-msft** [comment]
Exact same issue, except the resource in my case is https://apps.azureiotcentral.com. az account get-access-token --resource works, but I'm hoping for a PS equivalent.

**Comment by markcowl** [comment]
In this case, why not use the [Az.Kusto module](https://www.powershellgallery.com/packages/Az.Kusto/0.1.1)?

It is fundamentally insecure to return (and display) tokens, but would it serve your purpose if we implemented a cmdlet like 'Invoke-AzWebRequest' that could make an authenticated web request?

Also, for programmatic access (such as in the azure functions cli) there is a cross-platform MSAL extension library that provides shared access to the Token Cache - this seems like a better option that using Azure PowerShell internal libraries.

**Comment by markcowl** [comment]
@dcaro Two dfferent issues being discussed here:

- Integration with the function apps cli, which I think is a priority, and we should explore with the functions team
- Potentially another reason to support Invoke-AzWebRequest

**Comment by brandonh-msft** [comment]
@markcowl thanks for your reply!

`Az.Kusto` works only for management operations. Unfortunately they've not yet provided any way to create tables or data mappings so I have to work w/ the REST API to make this happen which necessitates a token for their resource endpoint.

I'm not familiar with `Invoke-AzWebRequest` but if it would make this workaround:
```powershell
# Get auth token to execute Kusto queries against the Data Explorer instance to create table & data mapping
import-module az
$context = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile.DefaultContext
$token = [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.AuthenticationFactory.Authenticate($context.Account, $context.Environment, $context.Tenant.Id.ToString(), $null, [Microsoft.Azure.Commands.Common.Authentication.ShowDialog]::Never, $null, $dexResourceUrl).AccessToken

# Call Kusto endpoint to run queries
$createTableRequestBody = @{
	csl = ".create table SampleDataTable (MessageProcessedTime: datetime, CloudProvider: string, TestRun: string, Trigger: string, Properties: dynamic)"
	db = "sampledata"
}
$createDataMappingRequestBody = @{
	csl ='.create table SampleDataTable ingestion json mapping ''DataMapping'' ''[{ "column":"MessageProcessedTime","path":"$.MessageProcessedTime","datatype":"datetime"},{"column":"CloudProvider","path":"$.CloudProvider","datatype":"string"},{"column":"TestRun","path":"$.TestRun","datatype":"string"},{"column":"Trigger","path":"$.Trigger","datatype":"string"},{"column":"Properties","path":"$.Properties","datatype":"dynamic"}]'''
	db = "sampledata"
}
$headers = @{
	Accept = "application/json"
	Authorization = "Bearer $token"
	Host = $dexResourceHost
}

Invoke-RestMethod -Method Post -Uri "$dexResourceUrl/v1/rest/mgmt" -Body (ConvertTo-Json $createTableRequestBody) -ContentType "application/json" -Headers $headers >$null
```

more succinct/prettier or alleviate it altogether then I'm for it 👍

**Comment by brandonh-msft** [comment]
Regarding `func` integration, honestly, I don't think we should be tooling around yet another CLI that people have to install. You can already do everything func CLI does with existing PS modules / `dotnet` calls except `func host` operations (obviously not applicable to AzPosh).

Just my .02 👛

**Comment by samarths-msft** [comment]
Wow. That worked for me as well.

**Comment by ahmelsayed** [comment]
`func` similarly only needs to get the token from Az if available. [It already does this ](https://github.com/Azure/azure-functions-core-tools/blob/f53563b622ee68f00811ddaaaa67d1199067f8ad/src/Azure.Functions.Cli/Actions/AzureActions/BaseAzureAction.cs#L266-L273) thanks to @TylerLeonhardt. I think his point was that it would be nice to have a better way to achieve this through Az module than it's today.

**Comment by brandonh-msft** [comment]
_my_ main point is we should have parity between az cli and azposh

**Comment by dcaro** [comment]
@brandonh-msft we are working on getting the parity between the az cli and Azure PowerShell but it will take a while to get there.

**Comment by rjmholt** [comment]
I've just run into a need for this too, for an API that not exposed by either Azure PowerShell or `az`.

While I understand the reasoning for not exposing a way to get a token, there are a few reasons I can see to do it:

- The `az` CLI already has this capability, so this is a parity question
- There is a workaround to get this in plaintext today with a few lines of PowerShell, so the security currently is obscurity. What's more, `az` does not seem to have applied the same security reasoning
- PowerShell offers `securestring`, so official support could possibly offer a (small) improvement over the current solution
- Using PowerShell to build more PowerShell commands to extend Azure API support is a prime usecase for PowerShell users (they're used to scripting around holes). Without token support, the two speeds of API access are "supported by Azure PowerShell" and "inaccessible" (with the latter meaning that they'll just install `az` like AzF does).

While I think `Invoke-AzRestMethod` has some merits, `Invoke-RestMethod` is [quite a complex cmdlet](https://get-powershellblog.blogspot.com/2017/11/powershell-core-web-cmdlets-in-depth.html) and PowerShell users are going to expect `Invoke-AzRestMethod` to work exactly the same. Moreover, there are security pitfalls within an `Invoke-RestMethod` implementation, and the existing one is continuously audited and patched.

**Comment by oising** [comment]
So, there are other far more visible use cases for wanting a `get-access-token` equivalent in the Az powershell module. Only yesterday I was figuring out how to publish an azure sql dacpac in an azure devops pipeline without using a username/password. I needed an access token representing the service connection between devops and azure cloud (it's essentially a service principial in AAD), and I had to split it into two tasks: The first to get the token and put it into a pipeline variable, and the second to publish the dacpac with sqlpackage's `/accessToken` paramter. Behold how opaque the script is to get the token into a pipeline variable:

```batch
FOR /F "tokens=* USEBACKQ" %%F IN (`az account get-access-token --resource=https://database.windows.net/ --query accessToken`) DO (SET var=%%F)
echo ##vso[task.setvariable variable=sqlToken;]%var%
```

Unless you're a comparative dinosaur (like me) with a serious masochistic streak for 90s-era batch, you're not going to figure that out in a hurry. Remember, the azure-cli devops task is locked to cmd, and the az powershell devops task is locked to powershell: I cannot mix the two, as the task only authenticates for the base platform (e.g. az login or connect-azaccount). 

I'd much rather see:

```powershell
write-host ("##vso[task.setvariable variable=sqlToken;](Get-AzAccessToken -Resource https://database.windows.net/)")
```

So, needing an access token is not that odd of an ask, and using cmd batch is extremely painful and utterly obtuse (for most people.)

**Comment by FriedrichWeinmann** [comment]
Another thing in favor of adding a command to access the token:
All the known workarounds to getting it after all break in Constrained Language Mode (Which will likely be enabled in environments that are conscious of PowerShell Threats).

As for the security concerns:

- You are using default authentication libraries. Any malicious actor that can run code as the current user can access it, there's not even any obscurity involved here.
- It's already quite possible to do harm with the default commands
- It does not provide capabilities a motivated developer cannot build himself/herself by using officially published APIs.

Regarding issues with Token handling:

 `Get-AzToken` (or whatever it ends up being called) could return a complex object, containing the token as a property, but also meta information about when it will expire. The command could also handle the automatic token refresh. Heck, the read accessor for the token on the object could implement it!

**Comment by dingmeng-xue** [comment]
We are releasing new cmdlet to support REST HTTP call. But currently, we only support resource management endpoint. Please share your thought and we hope to continue improving it.

**Comment by brandonh-msft** [comment]
@dingmeng-xue that doesn't solve any of reasons this thread was opened or the comments/upvotes since:

1. [Functions publishing](https://github.com/Azure/azure-powershell/issues/7752#issuecomment-439782809)
1. [Kusto query publishing](https://github.com/Azure/azure-powershell/issues/7752#issuecomment-514367290)
1. [Azure IoT](https://github.com/Azure/azure-powershell/issues/7752#issuecomment-516955205)
1. [Azure SQL](https://github.com/Azure/azure-powershell/issues/7752#issuecomment-567502540)

Let's listen to the customers first, then solve for something else later.

**Comment by dingmeng-xue** [comment]
@brandonh-msft , thanks for your summary. IMHO, debate is around how you look on Azure PowerShell. If it is a product, token is transparent to users and user doesn't need to know details about token generation, refresh, and its endpoint. So, from security consideration, product should not expose its access token. But if it is a development tool, it seems token should be exposed, like ADAL, MSAL .... No idea why Azure CLI exposed it. If it's not feasible, we are reluctant to move in that sort of direction. We need to consider further and get back to you. 

I read above functions. It seems we should enrich PowerShell features including data plane and management plane both. Why do you not raise feature request to Azure PowerShell and service team? Formal cmdlet can make all customer get benefit. I always think raw REST API is just a temp solution.

**Comment by oising** [comment]
> No idea why Azure CLI exposed it.

Did you read my comment above, @dingmeng-xue ? It's a pretty simple scenario that demonstrates very well why an access token is useful. Without the access token, I'd have to store a separate username and password for accessing/deploying to my azure sql instance.

https://github.com/Azure/azure-powershell/issues/7752#issuecomment-567502540

**Comment by hausec** [comment]
Also interested in this. The workaround is great for REST, but I also need to interact with Graph and there's no solutions for obtaining a Graph token from Azure PS.

**Comment by brandonh-msft** [comment]
> @brandonh-msft , thanks for your summary. IMHO, debate is around how you look on Azure PowerShell. 

respectfully disagree; the debate is around parity.

**Comment by TylerLeonhardt** [comment]
Another instance of needing the access token:

```pwsh
$env:VSCS_ARM_TOKEN = $AzAccessToken
"y`nn`n" | codespaces start -s $SubscriptionName -p $PlanName
```

Visual Studio Codespaces uses this environment variable for non-interactive auth scenarios.

https://docs.microsoft.com/en-us/visualstudio/codespaces/reference/vsonline-cli

**Comment by brandonh-msft** [comment]
> I read above functions. It seems we should enrich PowerShell features including data plane and management plane both. Why do you not raise feature request to Azure PowerShell and service team? Formal cmdlet can make all customer get benefit. I always think raw REST API is just a temp solution.

@dingmeng-xue Because then you're constantly playing catch-up. New service gets released, must wait for AzPosh to support it. Service X changes its auth method, must wait for AzPosh to release an updated version. Additionally, if raw REST API were indeed "just a temp solution," then it wouldn't exist in our other offerings (az cli) either. Again, we're back to parity.

**Comment by StefanSchoof** [comment]
An other use case is to use get a token for a `https://database.windows.net` scope and use the auth info create a SQL Connection. 

Currently I can not use the auth from the powershell session for the current user with mfa. So my script or fall back to `az`:
```powershell
$token = az account get-access-token --resource https://database.windows.net --output tsv --query accessToken

$conn = New-Object System.Data.SqlClient.SQLConnection 
$conn.ConnectionString = "Data Source=<server>.database.windows.net;Initial Catalog=<db>Connect Timeout=30"
$conn.AccessToken = $token

$conn.Open() 
```

**Comment by ioamnesia** [comment]
@TylerLeonhardt, @StefanSchoof, @hausec getting an access token is easy. You can use the Azure PowerShell wellknown clientid for most resources, but to make sure you can get Graph, I prefer to create my own Azure AD Application Registration.

1. Log into the Azure Portal
2. Navigate to Azure AD, then select App Registrations in the blade under Manage.
3. Click New Registration
4. Give it a name and then select the second option under Supported account types. (This will allow you to issue your token requests to the organizations endpoint, which is simpler IMHO). The click Register.
5. Navigate to the Authentication section and flip the "Treat application as a public client" toggle to Yes and click the Save icon at the top.
6. Go back to the Overview section and copy your Application (client) ID

Once you have the client id, run this in PowerShell
```powershell
$clientid = "[YOUR CLIENT ID]"
$request = Invoke-RestMethod -Method GET -Uri "https://login.microsoftonline.com/organizations/oauth2/v2.0/devicecode" -Body @{client_id=$clientid; scope="[YOUR RESOURCE SCOPE(S)] openid offline_access"} -ContentType "application/x-www-form-urlencoded"
$request.message
```
Follow the instructions displayed in the message and once you've authenticated, use this to get the token:
```powershell
$tokens = Invoke-RestMethod -Method POST -Uri "https://login.microsoftonline.com/organizations/oauth2/v2.0/token" -Body @{client_id=$clientid; grant_type="urn:ietf:params:oauth:grant-type:device_code"; code = $request.device_code} -ContentType "application/x-www-form-urlencoded"`
$accesstoken = $tokens.access_token
```
(Note, if you run the second section before you authenticate, it will return an error. Also, you can only run the second section once after authenticating. If you try again, the API will return a message saying the code was already redeemed.)

As far as the [YOUR RESOURCE SCOPE], that will depend on what you're trying to access. You can only use one resource (eg https://graph.microsoft.com or https://database.windows.net) but you can request multiple scopes if needed by space-separating them (eg https://graph.microsoft.com/User.ReadWrite.All https://graph.microsoft.com/Group.ReadWrite.All). Some resources support the "user_impersonation" scope (like https://management.core.windows.net/user_impersonation for Azure), which is handy.

The access token you get back will only be valid for 1 hour. If you need longer access, I recommend adding "openid offline_access" to the end of your scope parameter (which you can see above). This will return a second refresh_token which you can use to request new access tokens without having to reauthenticate. The refresh token is good for 90 days by default and each time you use it to get a new access token, you'll also get a new refresh token that will have a new expiry date. Here's the PowerShell to use a refresh token to get an access token:

```powershell
$tokens = Invoke-RestMethod -Method POST -Uri "https://login.microsoftonline.com/organizations/oauth2/v2.0/token" -Body @{client_id=$clientid; grant_type="refresh_token"; refresh_token = "[YOUR REFRESH TOKEN]"; scope = "[YOUR RESOURCE SCOPE]"} -ContentType "application/x-www-form-urlencoded"
```

Just make sure to store the refresh token securely, it's as good as a user/pass and as long as it's refreshed periodically, it's access is good "forever".

**Comment by oising** [comment]
@ioamnesia While I am sure this might help some people who visit this thread, it's missing the point. Your solution is less "easy" than `get-azaccesstoken -scope x,y,z -resource http://resource`. There needs to be parity between azure-cli and azure powershell.

**Comment by ioamnesia** [comment]
Baby steps @oising. Maybe it will get the others by while they wait patiently

**Comment by erich-wang** [comment]
`Get-AzAccessToken` is available in Az.Accounts 2.2.0 which will be released on Nov 17, please have a try and provide feedback by filing a new issue, thanks.

**Comment by TylerLeonhardt** [comment]
@AnatoliB @Francisco-Gamino @ankitkumarr heads up, this new cmdlet can replace the code here:

https://github.com/Azure/azure-functions-core-tools/blob/be1b76f4b961e37b351aff6aaf74cf2b29dd7bbd/src/Azure.Functions.Cli/Actions/AzureActions/BaseAzureAction.cs#L280-L284

**Comment by Francisco-Gamino** [comment]
Thanks @TylerLeonhardt for the heads up. I have opened https://github.com/Azure/azure-functions-core-tools/issues/2298 to track this.

**Comment by stefanstranger** [comment]
I just tested the Get-AzAccessToken cmdlet and I really like to use it in many of the Azure REST API calls I make. Any reason it doesn't contain Subscription information? Now I still have to use the Get-AzContext cmdlet to get that info. Many Azure REST API call require the Azure Subscription ID in the uri. If I still have to use the Get-Az Context cmdlet I can also get the Access Token from that object. So that defeats the new Get-AzAccessToken cmdlet imo.

Stefan [Msft]

**Comment by TylerLeonhardt** [comment]
I think it just mirrors the behavior that's been in AZ CLI for a while.
```
az accounts get-access-token
```
Does the same AFAIK.

**Comment by erich-wang** [comment]
@stefanstranger, actually we thought the possibility of outputing SubscriptionId, considering outputting SubscriptionId may result in confusion that token is only valid to that subscription, so we decided not outputting current subscription id at moment.

**Comment by stefanstranger** [comment]
OK. Thank you for explaining the reasoning.

Stefan

**Comment by sarah026** [comment]
![image](https://user-images.githubusercontent.com/1640754/100487181-42c60700-30ff-11eb-828d-d1d2ff2d71dd.png)

is it in a preview version?

**Comment by dcaro** [comment]
@sarah026 the cmdlet is included in the 2.2.1 version of Az.Accounts. 
Have you tried to close all your PowerShell sessions after installing the latest Az.Accounts module?

**Comment by sarah026** [comment]
@dcaro thanks for your reply

I tried, and even restarted my windows 10 machine... it doesn't work on either powershell 5 or 7

![image](https://user-images.githubusercontent.com/1640754/100514952-b2280f00-3170-11eb-837c-c68d1932d281.png)
![image](https://user-images.githubusercontent.com/1640754/100515058-590cab00-3171-11eb-9596-1f258f7725ed.png)

**Comment by sarah026** [comment]
Thanks @dcaro 

I uninstalled the module, and reinstalled it with "-RequiredVersion" ... then it worked after i restarted
