### ISSUE TITLE
Add Tab completion to New-AzureRmDiskConfig

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-powershell#7756]
Original request was posted at: [https://github.com/Azure/azure-docs-powershell/issues/799](https://github.com/Azure/azure-docs-powershell/issues/799), copy below:

I want to use the "New-AzureRmDiskConfig" cmdlet to create a premium storage data disk. One of the options is "-SkuName" -- but wait, what are the valid VALUES I can use for that option? There is no list, so I hunt (for 3 hours) until I find an example that shows "Premium_LRS" is a value that was used in an example I by chance found -- where did the author find that value? -- who knows?

Good grief -- HOW in the world is any programmer (me) who has never seen or used the "New-AzureRmDiskConfig" cmdlet supposed to know the VALID VALUES that are available for options when they are NOT documented? Is the new generation of programmers born with this knowledge? 40 years of witnessing the decline of documentation!

On to the next option -OsType -- again no list of valid values that are accepted by this option -- but again, I HAPPEN to find an example that shows "Windows". But again, I have no idea of the valid values -- I just happen to find the magic value in another example; that my friends, is NOT documentation.

PLEASE, for the love of god (if not my own sanity) start including lists of values accepted by cmdlet options OR (at the very least) provide a link to another cmdlet that can produce a list of valid values.

**Comment by maddieclayton** [comment]
@bdcoder2 Thanks for opening this issue, this is a place where we certainly should have a tab completer.

**Comment by bdcoder2** [comment]
Thanks @maddieclayton !! -- ALL cmdlets should have option values listed or a resource given for obtaining the correct value(s) for an option.

Look forward to being able to use some of these cmdlets in the near future.

**Comment by maddieclayton** [comment]
@bdcoder2 Looks like these two parameters use either an enum or a ArgumentCompleter - you should be able to tab through all valid values when using the cmdlets interactively.
