### ISSUE TITLE
30 minute multiple for creating policies

### ISSUE THREAD

**Issue by jontreynes** [Azure/azure-powershell#7778]
### Description

This documentation does not state that the policy you create must be in multiples of 30 minutes. 

### Script/Steps for Reproduction

```powershell

if $Dt does not equal a time of a 30 minute multiple, this script will fail
$SchPol = Get-AzureRmRecoveryServicesBackupSchedulePolicyObject -WorkloadType "AzureVM" 
$SchPol.ScheduleRunTimes.Clear()
$Dt = Get-Date
$SchPol.ScheduleRunTimes.Add($Dt.ToUniversalTime())
$RetPol = Get-AzureRmRecoveryServicesBackupRetentionPolicyObject -WorkloadType "AzureVM" 
$RetPol.DailySchedule.DurationCountInDays = 365
New-AzureRmRecoveryServicesBackupProtectionPolicy -Name "NewPolicy" -WorkloadType AzureVM -RetentionPolicy $RetPol -SchedulePolicy $SchPol
```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by maddieclayton** [comment]
@dragonfly91 Can you take a look at this issue?

**Comment by jontreynes** [comment]
Update:

I see that the recommendation for backup has changed. Before it was recommended to trigger up to 100 vms at a time in one Recovery Vault.
This recommendation is in referance to this doc (https://docs.microsoft.com/en-us/azure/backup/backup-azure-vms-introduction#best-practices) during this date 8/28/2018. I do not see this recommendation anymore.

May you please advise if it is best practice to trigger back up on vms 100 at a time.

        For example:
                      You may increment triggers in multiples of 30 minutes.

        Assume:
        HIPAA is triggered at 12:00 am
        SOX is triggered at 12:30 am
        PCI is triggered at 1:00 am
        Basic is triggered at 1:30 am

        If there are 100 vms associated to westusBackupVault1 under the HIPAA policy and you are about to 
        apply additional vms to this policy, create a new policy called HIPAA2 that starts at 2:00 am, to ensure
        HIPAA2 does not consume space from Basic which might also have 100 vms assigned.

**Comment by pvrk** [comment]
@Jontreyenes: We have updated the documentation with this again. It was earlier present but got missed in a restructuring. Now, we have updated the documentation again. Please find the relevant link below.

https://docs.microsoft.com/azure/backup/backup-azure-vm-backup-faq#is-there-a-limit-on-number-of-vms-that-can-beassociated-with-a-same-backup-policy

**Comment by pvrk** [comment]
Will verify about the 30 mins increment and update this thread.

**Comment by pvrk** [comment]
Updated the PS and CLI docs with 30 mins interval and limit of 100 VMs
