### ISSUE TITLE
New-AzsSubscription does not work when there is no existing subscription

### ISSUE THREAD

**Issue by amalik99** [Azure/azure-powershell#7789]
https://github.com/Azure/azure-docs-powershell/blob/master/azurestackps-1.2.11/AzureRM.AzureStackAdmin/New-AzsSubscription.md

It does not work if the tenant user logged doesn't have/had an existing subscription in AzureStack already

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by deathly809** [comment]
We no longer support the AzureRM.AzureStackAdmin module.  There is a known issue with the New-AzsSubscription cmdlet with the newest modules due to an issue in AzureRM.Profile where you cannot use cmdlets when there is no subscription tied to an account.

**Comment by knithinc** [comment]
This is by design.
