### ISSUE TITLE
 Get-AzureStorageContainer leaves TCP sockets open - No way to close?

### ISSUE THREAD

**Issue by lesterw1** [Azure/azure-powershell#7791]
### Description

When iterating over all containers in all storage account, each  Get-AzureStorageContainer appears to create its own TCP connection which (understandably) stays open for a bit.  In Azure automation runbooks, there is a hard limit of 1000 sockets, after which, the runbook will simply stop.  On a PC, you don't encounter this issue because the socket limit is much higher.  Ideally, there should be a way to "close" the session with the storage account (have I missed it?).

### Script/Steps for Reproduction

This runbook loops over all visible subscriptions and storage accounts. The automation account stops  after roughly 1,000 storage accounts are accessed.
`
$subscriptions = Get-AzureRmSubscription | where {$_.State -like "Enabled}
foreach ($sub in $subscriptions)
{
    Select-AzureRmSubscription -Subscription $sub.Id
    $storageAccounts = Get-AzureRmStorageAccount
    foreach ($sa in $StorageAccounts)
    {
        $containerList = Get-AzureStorageContainer -Context $sa.Context -MaxCount 25000
        # We have probably eaten a new socket now
        write-output "Storage $($sa.StorageAccountName) has $($containerList.Count) containers"
    }
}
`

### Module Version

This has been tested in Azure Automation with various versions of the Azure.Storage module, including v4.6.1, v4.6.0., 4.5.0.

Output below is from the current Runbook:
Directory: C:\Modules\User
ModuleType Version    Name                                ExportedCommands                                              
---------- -------    ----                                ----------------                                              
Script     4.6.1      Azure.Storage                       {Get-AzureStorageTable, New-AzureStorageTableSASToken, New-...

Binary     2.0.2.4    AzureAD                             {Add-AzureADApplicationOwner, Get-AzureADApplication, Get-A...

Script     5.5.2      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet,...

Script     5.1.3      AzureRM.Insights                    {Get-AzureRmMetricDefinition, Get-AzureRmMetric, Remove-Azu...

Script     5.2.1      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Update-AzureKeyVaultCertific...

### Environment Data

NOTE: This is within the Azure Automation runbook environment.

Name                           Value                                                                                    
----                           -----                                                                                    
PSVersion                      5.1.15063.726                                                                            
PSEdition                      Desktop                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
BuildVersion                   10.0.15063.726                                                                           
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1  

### Debug Output

Not really applicable. This is about the TCP socket consumption and having a way to release them.

**Comment by blueww** [comment]
@lesterw1 
I have tried to run `Get-AzureStorageContainer` on hundreds of storage accounts, and use `(netstat -an)` to check the network connection count (what's your way to check it?).

Following picture shows the network connection count trend when run `Get-AzureStorageContainer`. You can see, the connection count will decrease after the script finish, or when a cmdlets runs long time (see the drop in the middle since an account has 25k containers, so get container runs a long time).

Per my understanding, each storage account has a different FQDN, so need a new TCP connection. But the TCP connection can be release after a while.

For you issue, it might cause the script runs too fast (since there are small amoun of containers in each account, and network to server is good), so the TCP connection release can't catch the increase. You might can try to sleep some time (several seconds) after each  `Get-AzureStorageContainer`.


![image](https://user-images.githubusercontent.com/6926193/48336016-4e6e3e80-e69a-11e8-8091-4b293a82dced.png)

**Comment by lesterw1** [comment]
There are work-arounds by throttling the runbook, creating sub-jobs, etc. I'm likely to have more storage accounts than any other PaaS resource type, so I'd  rather be able to wholesale close the sockets when I am done with a storage account instance.  

Perhaps including the socket information in the storage account context would be an approach (which could then be extracted and the socket forced closed).

A related topic around keep-alive:
https://github.com/Azure/azure-storage-node/issues/358

**Comment by blueww** [comment]
@lesterw1 

Dotnet framework already has Keep-alive enabled by default, see https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.keepalive?view=netframework-4.7.2. Since Powershell is on Dotnet, it also has keep-alive enabled by default.

But for your scenario,  since each account has different FQDN address, so they will use different connection even enabled keep-alive.

**Comment by blueww** [comment]
@lesterw1 
Have you get any progress on this issue with my suggestion?

**Comment by lesterw1** [comment]
Thanks Wei.  The sleep after 800 cmdlets calls solution is what I was planning to do.  Its a shame the Azure runbook environment has such tight limits.

**Comment by blueww** [comment]
@lesterw1 
Do you mind if I close this issue now? If you need any help from us for this issue, you can reactive it.

BTW, from https://docs.microsoft.com/en-us/azure/automation/troubleshoot/runbooks#common-errors-when-working-with-runbooks, I see following information. Not sure if it can help you.

> Another solution is to run the runbook on a [Hybrid Runbook Worker](https://docs.microsoft.com/en-us/azure/automation/automation-hrw-run-runbooks). Hybrid Workers aren't limited by the memory and network limits that Azure sandboxes are.

**Comment by blueww** [comment]
@lesterw1 

I will close the issue now, as not hear any new request from you for long time.
Feel free to contact us if you need more assistant from our team.

**Comment by Akreddy123** [comment]
@blueww : (netstat -an) and Get-NetTCPConnection are throwing an exception in automation account. Is there any command which will work in automation account?

**Comment by blueww** [comment]
@Akreddy123 
I don't know another way to get it. And it the 2 method both fail, it might be some environment issue.
You might can check with the provider/owner of the automation account, to see how to resolve it.
