### ISSUE TITLE
Uninstall-AllModules - won't uninstall all dependencies due to version differences.

### ISSUE THREAD

**Issue by MaximoTrinidad** [Azure/azure-powershell#7800]
### Description

While testing my changes (https://github.com/Azure/azure-powershell/issues/7799) in all of my environment (Linux,MacOS, and Windows).

I found that this function will not uninstall all Az modules.  

Original script in reference found at: 
https://docs.microsoft.com/en-us/powershell/azure/uninstall-azurerm-ps?view=azurermps-6.12.0

### Script/Steps for Reproduction

After loading the "Uninstall-AllModules" function, then execute:

```powershell
Uninstall-AllModules -TargetModule Az -Version 0.5.0 -Force 
```
The problem lies with Az.Ssl module which version number has increase to 0.5.1.  This version difference will not remove the module.

This function should not create the list of dependencies from the PSGallery. but from what has been installed in order to successfully remove them from PowerShell.

![ms-uninstall_azure_01_2018-11-11_19-48-42](https://user-images.githubusercontent.com/19892435/48354701-514c3d80-e660-11e8-9b7f-bf51345baba0.jpg)

### Module Version

```powershell
PS [393] > Get-Module -ListAvailable Az* | Select Name, Version

Name                      Version
----                      -------
Az.Aks                    0.5.0
Az.AnalysisServices       0.5.0
Az.ApiManagement          0.5.0
Az.ApplicationInsights    0.5.0
Az.Automation             0.5.0
Az.Batch                  0.5.0
Az.Billing                0.5.0
Az.Cdn                    0.5.0
Az.CognitiveServices      0.5.0
Az.Compute                0.5.0
Az.Consumption            0.5.0
Az.ContainerInstance      0.5.0
Az.ContainerRegistry      0.5.0
Az.DataLakeAnalytics      0.5.0
Az.DataLakeStore          0.5.0
Az.DevTestLabs            0.5.0
Az.Dns                    0.5.0
Az.EventGrid              0.5.0
Az.EventHub               0.5.0
Az.Insights               0.5.0
Az.IotHub                 0.5.0
Az.KeyVault               0.5.0
Az.LogicApp               0.5.0
Az.MachineLearning        0.5.0
Az.MachineLearningCompute 0.5.0
Az.MarketplaceOrdering    0.5.0
Az.Media                  0.5.0
Az.Network                0.5.0
Az.NotificationHubs       0.5.0
Az.OperationalInsights    0.5.0
Az.PolicyInsights         0.5.0
Az.PowerBIEmbedded        0.5.0
Az.Profile                0.5.0
Az.RecoveryServices       0.5.0
Az.RedisCache             0.5.0
Az.Relay                  0.5.0
Az.Resources              0.5.0
Az.ServiceBus             0.5.0
Az.ServiceFabric          0.5.0
Az.SignalR                0.5.0
Az.Sql                    0.5.1
Az.Storage                0.5.0
Az.StreamAnalytics        0.5.0
Az.Tags                   0.5.0
Az.TrafficManager         0.5.0
Az.UsageAggregates        0.5.0
Az.Websites               0.5.0


PS [446] >

```

### Environment Data

All systems: CentOS, Ubuntu, MacSO, and Windows

```powershell
PSVersion                      6.1.0
```

### Debug Output

```

```

**Comment by dcaro** [comment]
@MaximoTrinidad thanks for reporting this issue and sorry that it has been sitting for long.
It looks like the function provided has some bugs and we'll have a look soon.

**Comment by MaximoTrinidad** [comment]
No Worries! 
Thanks for getting back! 
:)
