### ISSUE TITLE
ARM: Fix error message returned when creating role assignments (New-AzureRoleDefinition) with incorrect scope

### ISSUE THREAD

**Issue by vivsriaus** [Azure/azure-powershell#781]
Per Charles,
AFAICT the scope is invalid – you cannot do an assignment at an odd number of segments:
-Scope"subscriptions/$subId/resourceGroups"
it should either be:
-Scope"subscriptions/$subId "
or:
-Scope"subscriptions/$subId/resourceGroups/$name"

**Comment by markcowl** [comment]
@shuagarw Please take a look and as this is old, close if this has already been addressed

**Comment by sphibbs** [comment]
Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration.
