### ISSUE TITLE
Req: Get-AzureRmPolicyAlias - change default output format

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [Azure/azure-powershell#7824]
The current output of Get-AzureRMPolicyAlias is not conducive to seeing what aliases are available in a **human **readible**** format

In order to 'quickly skim' to see available aliases based on RP and ResourceType…. I feel a better default output for the cmdlet would be similar to:
`Get-AzureRmPolicyAlias | select namespace, resourcetype -ExpandProperty aliases | select namespace, resourcetype, @{Name="Alias";Expression={$_."Name"}} | Sort-Object Namespace, ResourceType, Alias`

**Comment by maddieclayton** [comment]
@Tiano2017 @ravbhatnagar Can you take a look at this issue?

**Comment by kenieva** [comment]
Hi, 

Thanks for your input. We understand the struggle there is in finding aliases and how that affects the experience in authoring custom policies. This is a continued effort on our part. We actually newly released a VS Code extension that helps you look up aliases for resources by hovering over properties. This is just a first step as continue to solve this issue. If there is a particular feature in this area you want to see I would recommend submitting the idea to our UserVoice for voting amongst other Azure Policy users.  Don’t hesitate to reach out again if you have more questions and/or need help using the new extension.
