### ISSUE TITLE
Add-AzureNodeWebRole should be updated with a more modern Node.js build

### ISSUE THREAD

**Issue by jeffwilcox** [Azure/azure-powershell#783]
Hi,
The documentation for the Node.js `Add-AzureNodeWebRole` cmdlet has been updated recently (https://azure.microsoft.com/en-us/documentation/articles/cloud-services-nodejs-develop-deploy-app/), but one thing it does not point out is that the cmdlet generates a web role with Node.js version _0.6.20_ which was released in 2012.

Today Node is up into the _0.12.x_ territory and it has changed a lot. To make sure that this cmdlet is useful, a newer version is very necessary, as npm modules and apps just don't work on this old build at this time.

The `setup_web` and ServiceDefinition scaffolding files will need to be updated to support this. Node.js now ships an MSI vs the original EXE for installations.

As a result, a silent `msiexec` is more appropriate than executing the download as done before.

Although I've hacked this together in a specific web role I'm working to deploy, it would be great if the cmdlet just worked with a much newer runtime by default. Note that the iisnode version deployed seems fine with super recent Node.js builds, so that's great!

**Comment by pcgeek86** [comment]
@jeffwilcox FYI, Markdown formatting isn't supported in the GitHub issue title / subject.

**Comment by markcowl** [comment]
Node is past 1.0 at this point.  What should our continuing support be fore these cmdlets?

**Comment by jeffwilcox** [comment]
@markcowl the role should be updated to _support Node 1.0+_ (i.e. v4 LTS), rather than just deprecating or removing this functionality.

**Comment by jeffwilcox** [comment]
@markcowl what was the decision associated with the closing of the work item? Is the cmdlet being removed, or update, or ... ?
