### ISSUE TITLE
New-AzureRmEventGridSubscription & Update-AzureRmEventGridSubscription: Add Support for Storage Queue Handler

### ISSUE THREAD

**Issue by MateusAmin** [Azure/azure-powershell#7855]
This a request for enhancement. Currently, New-AzureRmEventGridSubscription & Update-AzureRmEventGridSubscription  do not support using Storage Queue for the subscription handler.

Applicable Spots in the code:

https://github.com/Azure/azure-powershell/blob/6ab1c8b0048e526302d42e45c670d24aaaf786e2/src/ResourceManager/EventGrid/Commands.EventGrid/EventSubscription/NewAzureEventGridSubscription.cs#L147

https://github.com/Azure/azure-powershell/blob/97229e0b1d913453cac19ba46da65a3001e809f6/src/ResourceManager/EventGrid/Commands.EventGrid/Utilities/EventGridClient.cs#L123

https://github.com/Azure/azure-powershell/blob/6ab1c8b0048e526302d42e45c670d24aaaf786e2/src/ResourceManager/EventGrid/Commands.EventGrid/EventSubscription/UpdateAzureEventGridSubscription.cs#L105

https://github.com/Azure/azure-powershell/blob/97229e0b1d913453cac19ba46da65a3001e809f6/src/ResourceManager/EventGrid/Commands.EventGrid/Utilities/EventGridClient.cs#L184

I tried both logical branches but it looks like it we will need to do more that updating the parameter set and the if then statement expressions.

## REST API Links

https://docs.microsoft.com/en-us/rest/api/eventgrid/eventsubscriptions/createorupdate#storagequeueeventsubscriptiondestination

**Comment by maddieclayton** [comment]
@kalyanaj Can you take a look at this issue?

**Comment by kalyanaj** [comment]
This has been supported as part of the latest preview PowerShell package for EventGrid: It can be downloaded from here. https://www.powershellgallery.com/packages/AzureRM.EventGrid/0.4.1-preview

The PowerShell usage for this is documented at https://docs.microsoft.com/en-us/azure/event-grid/custom-event-to-queue-storage.

(Note: When this feature becomes GA, the main branch of PowerShell and the module that ships as part of the main PowerShell package will get updated to include this functionality. )
