### ISSUE TITLE
Fix issues in BaseSqlVulnerabilityAssessmentAdapter and VulnerabilityAssessmentEndpointsCommunicator

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#7864]
## Description

There are discrepancies between the NetStandard and Desktop versions of the code for the following components.  For each, we need to work with the feature team to determine:

- Can we provide equivalent functionality in NetStandard for the 12/18 release
- If not, how to document the behavior discrepancy in the migration guide

### BaseSqlVulnerabilityAssessmentAdapter.cs
- ScanResultContainerName not populated with a value

### VulnerabilityAssessmentEndpointsCommunicator.cs
- CreateBlobSTorageContainer no longer creates a container

**Comment by MiYanni** [comment]
BaseSqlVulnerabilityAssessmentAdapter.cs was fixed in https://github.com/Azure/azure-powershell/commit/134dc84eb59a25346a2dbac3fd86d79dfeb1a5e6#diff-5d21b7f189fd3908b2b84c260bf16af0

**Comment by MiYanni** [comment]
VulnerabilityAssessmentEndpointsCommunicator was fixed in https://github.com/Azure/azure-powershell/commit/ed094c7f9584e549d7d2af20f9afd8a04c934db3#diff-464bc35e696a8467dc824f398ecc4e96
