### ISSUE TITLE
Unable to use Get-AzureRMDiagnosticSetting or Set-AzureRMDiagnosticSetting

### ISSUE THREAD

**Issue by rupanter** [Azure/azure-powershell#7873]
### Description

I am trying to run the cmdlets : Get-AzureRMDiagnosticSetting and Set-AzureRMDiagnosticSetting but both are failing with this : 

WARNING: 9:15:49 PM - *** The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future rele
ases.
WARNING: 9:15:49 PM - *** The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model classes. 

### Script/Steps for Reproduction

Get-AzureRMDiagnosticSetting -ResourceID
Set-AzureRMDiagnosticSetting -ResourceID

### Module Version

```
PS C:\WINDOWS\system32> Get-Module AzureRm
 
ModuleType Version    Name                                ExportedCommands                                                                                                                        
---------- -------    ----                                ----------------                                                                                                                        
Script     6.12.0     AzureRM                                                                                                                                                                     
Script     6.8.1      AzureRM                                                                                                                                                                     
 
PS C:\WINDOWS\system32> Get-Module AzureRm.Insights
 
ModuleType Version    Name                                ExportedCommands                                                                                                                        
---------- -------    ----                                ----------------                                                                                                                        
Script     5.1.5      AzureRM.Insights                    {Add-AzureRmAutoscaleSetting, Add-AzureRmLogProfile, Add-AzureRmMetricAlertRule, Add-AzureRmWebtestAlertRule...}                        
Script     5.1.3      AzureRM.Insights                    {Add-AzureRmAutoscaleSetting, Add-AzureRmLogProfile, Add-AzureRmMetricAlertRule, Add-AzureRmWebtestAlertRule...}                        
```

### Environment Data

```
Name                           Value                                                                                                                                                              
----                           -----                                                                                                                                                              
PSVersion                      5.1.17134.407                                                                                                                                                      
PSEdition                      Desktop                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                            
BuildVersion                   10.0.17134.407                                                                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                
SerializationVersion           1.1.0.1 
```

### Debug Output

```

```

**Comment by cormacpayne** [comment]
@rupanter both of the messages that you pasted are warnings and should not fail the build. Would you mind setting `$DebugPreference = "Continue"` and running the commands that are failing for you?

**Comment by rupanter** [comment]
For Get-AzureRMDiagnosticsetting we only get warning, the cmdlet returns nothing. Is that expected behaviour? 

For Set-AzureRMDiagnosticsetting, this is the error : 
Set-AzureRmDiagnosticSetting -ResourceId "/subscriptions/f28f2c24-b393-4dda-b471-0ef3b69c0578/resourceGroups/Basictesting/providers/Microsoft.Network/applicationGateways/Rupanter" -Enabled $true

** As per documents this should work**

Set-AzureRmDiagnosticSetting : Exception type: ErrorResponseException, Message: At least one data sink needs to be specified., Code: BadRequest, Status code:BadRequest, Reason phrase: Bad 
Request
At line:1 char:1
+ Set-AzureRmDiagnosticSetting -ResourceId "/subscriptions/f28f2c24-b39 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmDiagnosticSetting], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand

**Comment by maddieclayton** [comment]
@gucalder Can you take a look at this issue?

**Comment by Chiodood** [comment]
Get-AzDiagnosticSetting  returns
WARNING: 12:37:37 PM - *** The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.
WARNING: 12:37:37 PM - *** The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model classes.

**Comment by maximeGendre** [comment]
I had the same issue with Set-AzureRmDiagnosticSetting command

> Message: At least one data sink needs to be specified

It works when I add "WorkspaceId" Property
`$Workspace = Get-AzureRmOperationalInsightsWorkspace -ResourceGroupName $RG -Name CDLDataFactory
 Set-AzureRmDiagnosticSetting -ResourceId ($factory.DataFactoryId) -Enabled $True -WorkspaceId ($Workspace.ResourceId) -Name DiagName`

**Comment by israelcr** [comment]
Use Version 6.13.1 for AzureRM

#https://www.powershellgallery.com/packages/AzureRM/6.13.1
#Install-Module -Name AzureRM -RequiredVersion 6.13.1

Set-AzureRmDiagnosticSetting -Name "service" -ResourceId "/subscriptions/mysubscription/resourceGroups/myRG/providers/Microsoft.StreamAnalytics/streamingjobs/myStreamAn16May" -StorageAccountId "/subscriptions/mysubscription/resourceGroups/myRG/providers/Microsoft.Storage/storageAccounts/mystorage" -Enabled $true -RetentionEnabled $true -RetentionInDays 90  

Get-AzureRmDiagnosticSetting -ResourceId "/subscriptions/mysubscription/resourceGroups/MyRG/providers/Microsoft.StreamAnalytics/streamingjobs/myStream"

**Comment by bwarren18** [comment]
I'm getting the same WARNING messages when using AzureRM 6.13.1 and Az 2.4.0.

WARNING: 10:37:22 AM - *** The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.

WARNING: 10:37:22 AM - *** The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model classes.

**Comment by nkiest** [comment]
A destination is required, which is what the message is saying. Please specify a workspace, storage account, or eventhub.
Also, AzureRM is deprecated, and you should use Az.
If you are seeing an issue with set-AzDiagnosticSetting, and specifying a destination, please report back with your error.

**Comment by nkiest** [comment]
@bwarren18, Get-AzDiagnosticSetting does not work on VMs. It works on the resources listed here: https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-logs-schema

**Comment by amarzavery** [comment]
@nkiest - The source of truth is the swagger specification. .net sdk is generated from the spec and powershell commands use the generated .net sdk to make the request.

No where in the swagger spec, it is mentioned that `workspaceId` is a **required property** in the [request body](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2017-05-01-preview/diagnosticsSettings_API.json#L284) for the [PUT operation](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2017-05-01-preview/diagnosticsSettings_API.json#L81).

This is a bug in the spec and any attempt made by a customer using the generated SDK or CLI/powershell command is doomed for failure unless they come across this github issue and provide the workspaceId.

**Comment by asheniam** [comment]
@amarzavery - Can you share example that you are running into where it says workspaceId is required property?

**Comment by amarzavery** [comment]
@asheniam - Commandlet returns with an error message 
> Message: At least one data sink needs to be specified..

This message goes away when workspaceId is provided. This proves that inorder for the command to execute successfully workspaceId is a required parameter.

**Comment by asheniam** [comment]
WorkspaceId is not required property.  Customer can route diagnostic logs to storage account.  Here is an example that I just verified on my subscription.

Set-AzDiagnosticSetting -ResourceId /subscriptions/{subscriptionId}/resourceGroups/LogicAppTest2RG/providers/Microsoft.Logic/workflows/LogicAppPass -Name setting3 -Enabled $true -StorageAccountId /subscriptions/{subscriptionId}/resourceGroups/andystorage0503/providers/Microsoft.Storage/storageAccounts/andystorage0503
