### ISSUE TITLE
ARM 0.9.7 :: Get-AzureRemoteDesktopFile missing -Launch parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#788]
# Problem

In the Azure Service Management (ASM) PowerShell module, the `Get-AzureRemoteDesktopFile` command had two parameter sets:

- Download the RDP file onto the local filesystem
- Invoke the RDP file directly (`-Launch` switch parameter)

The same command in the Azure Resource Manager (ARM) PowerShell module no longer offers the `-Launch` parameter.

![image](https://cloud.githubusercontent.com/assets/466713/9425415/e118fe42-48cc-11e5-99a1-a02c4737c3fd.png)

# Expected Result

The `Get-AzureRemoteDesktopFile` command should include the `-Launch` parameter, on its own, separate parameter set.

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by singhkay** [comment]
@DeepakRajendranMsft Can you take a look at this?

**Comment by DeepakRajendranMsft** [comment]
added the launch option in this PR https://github.com/Azure/azure-powershell/pull/806

Thanks,
Deepak

**Comment by pcgeek86** [comment]
@DeepakRajendranMsft Thank you -- I checked out the PR and the parameter sets look good.

However, I'm curious about the implementation of the `mstsc.exe` invocation. Is there a reason that you're wrapping the invocation inside a batch file? Isn't that going to leave a bunch of `.bat` files on the user's filesystem?

**Comment by pcgeek86** [comment]
Closing issue report, as parameter has been reimplemented.
