### ISSUE TITLE
Can I install AZ and Azure module side by side?

### ISSUE THREAD

**Issue by niadak** [Azure/azure-powershell#7880]
I have following questions regarding new AZ Module.
1. I understand AZ Module will replace AzureRM module. Will AZ Module replace Azure module also? If no, Can I install AZ and Azure module side by side (using -AllowClobbar option)? In that case, can I use Enable-AzureRmAlias cmdlet with -Scope CurrentUser or LocalMachine?

2. Today MSI installation of AzureRM also install Azure module. Will that be true with MSI installation of AZ module?

3. What is the timeline for MSI installation support of AZ Module?

**Comment by MiYanni** [comment]
@niadak 
1. Azure (RDFE) cmdlets are no longer being actively developed. So, none of these cmdlets exist in Az, other than those that are dataplane modules (Azure.Storage, Azure.DataAnalytics, etc.) These dataplane cmdlets were merged into their management plane modules (Az.Storage, Az.DataAnalytics, etc.) That said, you cannot install Azure and Az side-by-side. Azure relies on AzureRM.Profile. Here are our notes on [AzureRM/Az side-by-side](https://github.com/Azure/azure-powershell/blob/preview/documentation/announcing-az-module.md#installing-az-and-azurerm-side-by-side---discouraged). It would similarly apply to Azure/Az side-by-side.
2. There is no MSI installation for Az. The Azure module code is being removed from this codebase, so it won't be updated unless there is a critical security issue.
3. We *may* create an installer in a few months, but there won't be an installer for Az 1.0. If you want to install the modules without using the PS Gallery, the packages are available for download. You can either use [Register-PSRepository](https://docs.microsoft.com/en-us/powershell/module/powershellget/register-psrepository?view=powershell-6) or just extract them into your PowerShell/modules directory.

**Comment by MiYanni** [comment]
Let me know if you have any other questions.

**Comment by niadak** [comment]
Thanks @MiYanni for your quick response.
Given that none of these (Azure module) cmdlets exist in Az, I think, it will be great if we can install both Azure and Az module side by side.

I have few classic resources and fer ARM resources in my subscription. I use a script with classic commands (Azure Module) to manage classic resources and a script with ARM commands to manage ARM resources. I believe this is a common scenario for many people.

I can replace the ARM commads with Az commands to avoid installing AzureRM module. But I cant remove the Azure Module as Az module does not have corresponding classic commands.

What is the recommendation for user who has to use both classic and ARM commands in scripts in terms of Az module migration?

**Comment by MiYanni** [comment]
@niadak Are you able to run the scripts separately? You can have both modules installed (which we still don't recommend), but primarily, they can't be loaded in the same PowerShell session. So, if you can just run Az in one session and Azure in another, it should work fine. Let me know if that won't work for you.
