### ISSUE TITLE
Feature Request: Add support for Azure Encryption Extensions for Azure Storage

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#789]
Please add support for Azure Encryption Extensions for Azure Blob storage, from the ARM PowerShell user experience. Integration with Azure Key Vault, and other key storage mechanisms should be supported.

http://blogs.msdn.com/b/partnercatalystteam/archive/2015/06/17/storing-data-securely-in-azure-blob-storage-with-azure-encryption-extensions.aspx

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@vincent81-jiang Can you take a look

**Comment by blueww** [comment]
We have open a task to track the issue and will triage it according to our bandwidth.

**Comment by cormacpayne** [comment]
@blueww Hey Wei, what is the status of this issue? We should close it if it's not a planned change.

**Comment by blueww** [comment]
This still not in Powershell.

But since CMK feature added in server side, now the blob data in server is already encrypted, and user can configure to use Keyvault for the encryption.

So it might not be so necessary to add the feature now.

**Comment by zhusijia26** [comment]
Close the issue based on last comment.
