### ISSUE TITLE
"Use for App service" in Application Gateway

### ISSUE THREAD

**Issue by adrinr** [Azure/azure-powershell#7897]
I'm trying to create my deployment scripts for application gateway and I'm missing a param in AzureRmApplicationGatewayBackendHttpSettings. While the option "Use for App service" is available from the portal, I cannot manage to get the same configuration only using Powershell. Did anybody face the same problem?

**Comment by cormacpayne** [comment]
@akshaysngupta Hey Akshay, would you mind taking a look at this issue?

**Comment by surajmb** [comment]
@adrinr, "Use for App Service" is only a UI element and when you enable it, it essentially asks the user to choose the custom probe and enables the "pick hostname from backend address" switch by default.

In PowerShell, to get the same result as Use for App Service, you can use the switches directly. Check the command below for example,

Set-AzApplicationGatewayBackendHttpSetting -ApplicationGateway $gw -Name appGatewayBackendHttpSettings -Port 80 -Protocol Http -CookieBasedAffinity Disabled -RequestTimeout 30 **-Probe $probe -PickHostNameFromBackendAddress**
