### ISSUE TITLE
ARM 0.9.7 :: New-AzureRoleDefinition doesn't support pipeline input

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#793]
# Problem

The ARM `New-AzureRoleDefinition` command doesn't support pipeline input.

![image](https://cloud.githubusercontent.com/assets/466713/9455406/2c3cd616-4a88-11e5-83a7-d3f966914dcd.png)
# Expected Result

The `New-AzureRoleDefinition` command should support pipeline input, either an array of JSON strings, and/or an array of `[System.IO.FileInfo]` instances.

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@shuagarw Please take alook, as this is rather old, please close if this has been addressed

**Comment by pcgeek86** [comment]
![image](https://cloud.githubusercontent.com/assets/466713/17494716/364291b0-5d73-11e6-9928-5f7dc0bd41a4.png)

**Comment by maddieclayton** [comment]
@darshanhs90 @cormacpayne Is this an issue in the AzureRM cmdlets?  If this is just Azure SM, are we planning to update this cmdlet in the future?

**Comment by darshanhs90** [comment]
Allows pipeling now
 <CommonParameters>
     This cmdlet supports the common parameters: Verbose, Debug,
     ErrorAction, ErrorVariable, WarningAction, WarningVariable,
     OutBuffer, **PipelineVariable**, and OutVariable. For more information, see
     about_CommonParameters (https:/go.microsoft.com/fwlink/?LinkID=113216).
