### ISSUE TITLE
ARM 0.9.7 :: Add type casting support for PSAzureEnvironment class

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#795]
When PowerShell performs an implicit cast from `[System.String]` to `[Microsoft.WindowsAzure.Commands.Profile.Models.PSAzureEnvironment]`, it fails. Please add support for casting from `string` to `PSAzureEnvironment`.

![image](https://cloud.githubusercontent.com/assets/466713/9456332/72e771ba-4a93-11e5-971e-13c9baf173c5.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
Will be handled as part of workflow support.  Closing due to age
