### ISSUE TITLE
Uninstall-Module -Name "Az"

### ISSUE THREAD

**Issue by ronbok** [Azure/azure-powershell#7955]
### Description

Does not uninstall the modules from PowerShell Core 6.1.0.  It leaves them all behind under C:\Program Files\PowerShell\Modules\*

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by cormacpayne** [comment]
@ronbok Hey Ron, thanks for the issue. This is an issue with `PowerShellGet` (as outlined in [this issue](https://github.com/PowerShell/PowerShellGet/issues/114)) -- the `Uninstall-Module` cmdlet is currently unavailable to uninstall dependent modules, which leaves behind all of the `Az.*` modules when trying to uninstall `Az`. However, we do have documentation for creating an `Uninstall-AllModules` script that you can use to uninstall `Az`; document can be found [here](https://docs.microsoft.com/en-us/powershell/azure/uninstall-azurerm-ps).

Please let us know if you have any other comments or issues!

**Comment by jdennis17** [comment]
the link is broken champ

**Comment by cormacpayne** [comment]
@jdennis17 weird, it looks like the name of the article has changed since November -- I updated the above hyperlink with the correct URL (found [here](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps))
