### ISSUE TITLE
Fix New-AzureRmRoleAssignmentWithId in AzureRM.Resources.ps1, add New-AzureRmRoleAssignment and Remove-AzureRmRoleAssignment

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#7958]
In our `ScenarioTest.ResourceManager` common library, we export `AzureRM.Resources.ps1` file. This file contains common functionality used by scenario tests for our modules. The file contains thin versions of common Resources modules. These functions are simply calling our internal Resources SDK directly and do not rely on the Resources module.

However, [New-AzureRmRoleAssignmentWithId](https://github.com/Azure/azure-powershell-common/blame/dev/src/ScenarioTest.ResourceManager/AzureRM.Resources.ps1#L135) was introduced to this file. This function **does** rely on the Resources module, which hinders the purpose of this file. Any scenario test attempting to use this needs to build the Resources module (which is 2 projects currently) and include those projects in their solution. This is not preferred for simplicity and maintaining the same Resources SDK version for the involved scenario tests. 

I ran into this issue for DataFactoryV2. [Here](https://github.com/MiYanni/azure-powershell/blob/17dccdfdebf20eba85bb5898e8c44fea2369df34/src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2.Test/ScenarioTests/IntegrationRuntimeTests.cs#L60) is the single test for it, `TestSharedIntegrationRuntime`. And that test uses both [New-AzureRMRoleAssignmentWithId](https://github.com/MiYanni/azure-powershell/blob/17dccdfdebf20eba85bb5898e8c44fea2369df34/src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2.Test/ScenarioTests/IntegrationRuntimeTests.ps1#L289) and [Remove-AzureRmRoleAssignment](https://github.com/MiYanni/azure-powershell/blob/17dccdfdebf20eba85bb5898e8c44fea2369df34/src/ResourceManager/DataFactoryV2/Commands.DataFactoryV2.Test/ScenarioTests/IntegrationRuntimeTests.ps1#L317).

Instead, we should:
- Create a `New-AzureRmRoleAssignment` function that uses the internal Resources SDK
- Update the `New-AzureRmRoleAssignmentWithId` function to use the `New-AzureRmRoleAssignment` function that was implemented above
- Create a `Remove-AzureRmRoleAssignment` since we are missing this anyway from the common set of functions

This will allow the DataFactoryV2 test to run properly again.

**Comment by cormacpayne** [comment]
Create a new script, `AzureRM.Authorization.ps1` that contains this functionality.
