### ISSUE TITLE
Use internal Storage SDK for AzureRM.Storage.ps1 in Common

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#7959]
For our `ScenarioTest.ResourceManager` project, we use a couple of ps1 files that are used by module scenario tests, `AzureRM.Resources.ps1` and `AzureRM.Storage.ps1`. These files contain functions that are similar to actual cmdlets from the respective modules. However, these functions only use the SDK calls directly. This allows the scenario tests that rely on this common functionality to use the same version of our SDKs and not rely on changes from the modules or other SDK versions.

However, for `AzureRM.Storage.ps1`, it currently is using an SDK version. You can see that [here](https://github.com/Azure/azure-powershell-common/blob/84adc2e8e833a22caa8ea714cd5c367e63da227c/src/ScenarioTest.ResourceManager/AzureRM.Storage.ps1#L208). In comparison, the `AzureRM.Resources.ps1` is using the [internal Resources SDK](https://github.com/Azure/azure-powershell-common/blob/84adc2e8e833a22caa8ea714cd5c367e63da227c/src/ScenarioTest.ResourceManager/AzureRM.Resources.ps1#L265). We should change `AzureRM.Storage.ps1` to use our internal SDK version.

- Update references to `Microsoft.Azure.Management.Storage` with our internal namespace
- Test changes in module scenario tests to verify that these changes work appropriately
  - Rerecording may be necessary, but likely should not be. I believe the version of Management.Storage we use is *the same* API version as our internal one, but I could be wrong.
- Publish the Common package with the updated ps1 and make a PR into this repo to change the package version numbers

**Comment by MiYanni** [comment]
@blueww No. This applies to modules using Storage SDK for testing. This is not related to the Storage module.

**Comment by maddieclayton** [comment]
Done.
