### ISSUE TITLE
ARM 0.9.7 :: New-AzureProfile throws error when using -Environment parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#796]
![image](https://cloud.githubusercontent.com/assets/466713/9456405/5490a00a-4a94-11e5-92e2-f6b476097b21.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment]
@pcgeek86 How was the environment added?

**Comment by pcgeek86** [comment]
@markcowl built-in

**Comment by markcowl** [comment]
@pcgeek86 What version of the cmdlets?

**Comment by markcowl** [comment]
Closing for lack of response.  Please reopen if yoiu are still seeing this issue.
