### ISSUE TITLE
unable to deploy ARM templates in automation account

### ISSUE THREAD

**Issue by itsramz** [Azure/azure-powershell#7976]
### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by cormacpayne** [comment]
@itsramz please provide the above information that was requested:

- what cmdlets are you trying to run?
- what version of the modules are installed in your account? (this can be retrieved with `Get-Module -Name AzureRM* -ListAvailable`)
- what is the resulting debug trace? (you can set `$DebugPreference = "Continue"` and run the runbook in the test pane)
- what is the result of running `Resolve-AzureRmError` after this cmdlet fails?

**Comment by itsramz** [comment]
It worked. Thanks

**Comment by itsramz** [comment]
I have been asked to create a linked template combining the following resources storage account,redis,key vault ,ASP,webapp,sql db and application insights . I have seperate templates , not sure how to create a linked template. Kindly help

**Comment by maddieclayton** [comment]
This repo is for Azure PowerShell cmdlets - please open an issue here for questions about ARM templates: https://github.com/Azure/azure-quickstart-templates.
