### ISSUE TITLE
Set-AzureRmNetworkInterface fails in Azure Automation

### ISSUE THREAD

**Issue by jimmyfit** [Azure/azure-powershell#7979]
### Description

When an Azure Automation runbook job hits the Set-AzureRmNetworkInterface cmdlet (AzureRM.Network version 6.9.1), no ARM actions are initiated, the subsequent line in the runbook never runs, and the runbook eventually fails with the following error:
 
The runbook job was attempted 3 times, but it failed each time.  Common reasons that runbook jobs fail can be found here:  https://docs.microsoft.com/en-us/azure/automation/automation-troubleshooting-automation-errors

When the AzureRM.Network module is backed out to version 5.0, this action succeeds.

### Script/Steps for Reproduction

Create an Azure Automation runbook, update the modules, then create a runbook which sets the network interface, like:

```powershell
$VMNetworkInterfaceObject = Get-AzureRmNetworkInterface -Name $NicArmObject.Name -ResourceGroupName $NicArmObject.ResourceGroupName
#$VMNetworkInterfaceObject.IpConfigurations[0].PublicIpAddress = $PIP 
#$VMNetworkInterfaceObject.NetworkSecurityGroup = $NSG
Set-AzureRmNetworkInterface -NetworkInterface $VMNetworkInterfaceObject

```
Downgrade the AzureRM.Network module to version 5.0, and the same runbook will succeed.

### Module Version

Fails on AzureRM.Network 6.9.1. Succeeds on AzureRM.Network 5.0.

**Comment by cormacpayne** [comment]
@jimmyfit Hey Jimmy, this issue was recently fixed in `AzureRM.Network`. Would you mind updating to the latest version (6.11.1) and see if the above error occurs?

**Comment by jimmyfit** [comment]
You're right. Thanks!
