### ISSUE TITLE
Using New-AzResourceGroupDeployment with -TemplateParameterObject and -TemplateParamterFile together throws "Parameter set cannot be resolved using the specified named parameters"

### ISSUE THREAD

**Issue by rudfoss** [Azure/azure-powershell#7980]
I'm using the cmdlet `New-AzResourceGroupDeployment` to deploy a small ARM template (single web app and server farm). The deployment works correctly when I only supply the `-TemplateParamtereFile` argument, but when I try to add `-TemplateParameterObject` with some additional parameters it fails with this error:

```
New-AzResourceGroupDeployment : Parameter set cannot be resolved using the specified named parameters.
```

It does not seem to be a problem with either my parameters file or with the template itself because it works fine if I only supply the parameters through the file.

Is using both a parameters file and an object (with additional or overwritten parameters) not supported? What I'm basically trying to do is run two deployments one after the other and for the last one provide default parameters from the parameters file and override some of them with new values from the first deployment.

Here is a specific example of calling the command that fails with this error:
```powershell
$azContext = Get-AzContext -ErrorAction SilentlyContinue
if (!$azContext) {
	Connect-AzAccount
}

Select-AzSubscription -SubscriptionID $subscriptionId # Hidden

$additionalParams = @{
	"storageAccountName" = "accountName"
	"storageAccountKey" = "accountKey"
	"redisHost" = "redisHost"
	"redisKey" = "redisKey"
}

New-AzResourceGroupDeployment `
	-Name "MyTest-TestDeployment" `
	-ResourceGroupName "MyTest-TestResourceGroup" `
	-TemplateFile "./templates/template-iac.json" `
	-TemplateParameterFile "./templates/template-iac.parameters.json" `
	-TemplateParameterObject $additionalParams `
	-Verbose
```

**Comment by rudfoss** [comment]
For anyone looking I wrote this small (extremely simplified) function to read parameters from a parameters file and merge them with an object. Until the cmdlet support both parameters at once this is at least a workaround.

https://gist.github.com/rudfoss/31cae1e6062c9c49627586095e55a804

**Comment by cormacpayne** [comment]
@rudfoss Hey Thomas, the two parameters you mentioned (`-TemplateParameterObject` and `-TemplateParameterFile`) are mutually exclusive in this case -- they both should contain similar information, if not the same, so there shouldn't be a case where you'd need to provide them both. I believe you should be able to use the `ConvertFrom-Json` cmdlet to turn your template parameter file into an object that you can then edit the values of, and finally pass it along to the next command.  Please let me know if this resolution doesn't work for you.

**Comment by rudfoss** [comment]
In my case I have several separate templates for deploying several different solutions, but they all depend on one shared template deploying shared resources. E.g:

```
A_template.json
A_template.parameters.json

B_template.json
B_template.parameters.json

Shared_template.json
Shared_template.parameters.json
```

Where A and B utilize output (e.g.: access keys and generated resource names) from Shared.

What I'd like to be able to support is deploying either Shared alone, Shared + A or Shared + B or Shared + A + B. I'm doing this by first deploying Shared and then augmenting the parameters for A or B with output from the Shared deployment. Maybe I'm thinking about this the wrong way though.
