### ISSUE TITLE
Set-AzureRmVmCustomScriptExtension not working on -TypeHandlerVersion 1.9.1 / 1.9.2 /1.9.3

### ISSUE THREAD

**Issue by ShivaKodkandla** [Azure/azure-powershell#7986]
Set-AzureRmVmCustomScriptExtension not working on -TypeHandlerVersion 1.9.1 / 1.9.2 /1.9.3: failed with below error, but when i kept the typehandlerversion as 1.9 it worked.

![image](https://user-images.githubusercontent.com/45571707/49391948-17e48a80-f753-11e8-8939-4ccb75b0c728.png)

powershell - 5.1
azure:
- Script     5.9.1      AzureRM.Compute
-Script     6.13.1     AzureRM

Set-AzureRmVmCustomScriptExtension : **The value of parameter typeHandlerVersion is invalid.**
ErrorCode: InvalidParameter
ErrorMessage: The value of parameter typeHandlerVersion is invalid.
ErrorTarget: typeHandlerVersion
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : e42f2ae6-1f4b-4916-beea-92814f9094ce
At line:1 char:1
+ Set-AzureRmVmCustomScriptExtension -ResourceGroupName -Location ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmVMCustomScriptExtension], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.SetAzureVMCustomScriptExtensionCommand

**Comment by cormacpayne** [comment]
@hyonholee would you mind taking a look at this issue?

**Comment by kennyjwilli** [comment]
I also ran into this using the Datadog extension. Running 
```
az vm extension image list --location westus -o table
```
shows the list of all available versions for extensions. If I try creating an extension with the DatadogLinuxAgent version 0.6.2, I get the message:

```
Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The value of parameter typeHandlerVersion is invalid." Target="typeHandlerVersion"
```

If I set the version to `0.6`, it works.

**Comment by GabstaMSFT** [comment]
Can this be reproduced using https://learn.microsoft.com/en-us/azure/virtual-machines/windows/run-command-managed?
