### ISSUE TITLE
Feature request:  Feature request: we add three optional parameters to NetworkWatcherConfigFlowLog Operations

### ISSUE THREAD

**Issue by zwswim** [Azure/azure-powershell#7997]
In Set-AzureRmNetworkWatcherConfigFlowLog we add two optional parameters:
-FormatType <string>
-FormatVersion <int?>
-TrafficAnalyticsInterval <int?>

In out put of Get-AzureRmNetworkWatcherFlowLogStatus, return new contract 
-Format <FlowLogFormat>
    -Type <string>
    -Version <int?>

-TrafficAnalyticsInterval <int?>

This one need to merge into Milestone:  network-november-release

**Comment by zwswim** [comment]
Updated the title

**Comment by cormacpayne** [comment]
@irrogozh Hey Irina, would you mind taking a look at this issue?

**Comment by EvgenyAgafonchikov** [comment]
@irrogozh, @cormacpayne, I believe this one should be closed as related changes were merged

**Comment by EvgenyAgafonchikov** [comment]
Closing, got offline confirmation from @zwswim
