### ISSUE TITLE
New-AzureStorageShare missing -PassThru parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#80]
The `New-AzureStorageShare` command doesn't return a new Storage Share (`Microsoft.WindowsAzure.Storage.File.CloudFileShare`) object, and doesn't offer a `-PassThru` parameter either. Therefore, an extra call to `Get-AzureFileShare` must be made in order to retrieve the object representing the share. 

Please add the `-PassThru` parameter to `New-AzureStorageShare` to ensure that the new share object can be returned.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://twitter.com/pcgeek86
http://trevorsullivan.net

**Comment by gangsir** [comment]
@pcgeek86  Thank you for providing feedback. We will look at this and improve this cmdlet in future releases.

**Comment by blueww** [comment]
In current 2.1 build, New-AzureStorageShare can return the new Storage share object.
How do you think about the current behavior?

$share = New-AzureStorageShare -Name abc
$share.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    CloudFileShare                           System.Object

**Comment by blueww** [comment]
Close the issue as it's already fixed.
Feel free to reopen if necessary.
