### ISSUE TITLE
How to keep "az vm image list" offline list in sync with PowerShell equivalent

### ISSUE THREAD

**Issue by BorisB2015** [Azure/azure-powershell#8027]
`az vm image list` az CLI command pulls the list of image aliases from `https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json`

Equivalent PowerShell info appears to come from `https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/Images.cs`

Currently the content of the above 2 places differ (versions updated in CLI but not in PS). It is possible to keep the versions synced manually but I'd like to explore if there is plan to address the asymmetry.

Az CLI issue https://github.com/Azure/azure-cli/issues/4611 also requests removal of aliases file from being pulled from GitHub. 

There might be opportunity to address this consistently across CLI and PS.

**Comment by BorisB2015** [comment]
@gbowerman for awareness.

**Comment by gbowerman** [comment]
Update:
Provisional agreement in place to integrate this central JSON list into the PowerShell build process: https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/quickstart-templates/aliases.json 
@hyonholee is looking into the engineering work.

**Comment by maddieclayton** [comment]
I have added this script which will update the Images.json file (which is read by Images.cs): https://github.com/Azure/azure-powershell/blob/master/src/Compute/Compute/Strategies/ComputeRp/SyncComputeImages.ps1.
