### ISSUE TITLE
Go through breaking change attributes in Az

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#8038]
placeholder

- go through the breaking change attributes and warning messages, recoprd each, anbd decide what to do with each.  We egneerally want to remove them if the feature teams have no plan to issue a breakign change.

**Comment by maddieclayton** [comment]
Deleted cmdlets
All of backup
C:\azure-powershell\src\ResourceManager\RecoveryServices\Commands.RecoveryServices\Vault\SetAzureRmRecoveryServicesVaultContext.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Database Backup\Cmdlet\GetAzureSqlServerBackupLongTermRetentionVault.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Database Backup\Cmdlet\SetAzureSqlServerBackupLongTermRetentionVault.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\ServerUpgrade\Cmdlet\GetAzureSqlServerUpgrade.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\ServerUpgrade\Cmdlet\StartAzureSqlServerUpgrade.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\ServerUpgrade\Cmdlet\StopAzureSqlServerUpgrade.cs

cmdletoutput
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\GetAzureVirtualNetworkCommand.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\NewAzureVirtualNetworkCommand.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\SetAzureVirtualNetworkCommand.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\Subnet\AddAzureVirtualNetworkSubnetConfigCommand.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\Subnet\RemoveAzureVirtualNetworkSubnetConfigCommand.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\Subnet\SetAzureVirtualNetworkSubnetConfigCommand.cs

cmdletparameter
C:\azure-powershell\src\ResourceManager\Consumption\Commands.Consumption\Cmdlets\UsageDetails\GetAzureRmConsumptionUsageDetail.cs
C:\azure-powershell\src\ResourceManager\DataFactoryV2\Commands.DataFactoryV2\Runs\GetAzureDataFactoryActivityRunCommand.cs
C:\azure-powershell\src\ResourceManager\DataLakeStore\Commands.DataLakeStore\Commands\NewAzureRmDataLakeStoreAccount.cs
C:\azure-powershell\src\ResourceManager\DataLakeStore\Commands.DataLakeStore\Commands\SetAzureRmDataLakeStoreAccount.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\ServiceEndpointPolicy\ServiceEndpointPolicyDefinition\GetAzureServiceEndpointPolicyDefinitionCommand.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\NewAzureVirtualNetworkCommand.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\Peering\AddAzureVirtualNetworkPeeringCommand.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\SetAzureVirtualNetworkCommand.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\Subnet\AddAzureVirtualNetworkSubnetConfigCommand.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\Subnet\GetAzureVirtualNetworkSubnetConfigCommand.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\Subnet\RemoveAzureVirtualNetworkSubnetConfigCommand.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\Subnet\SetAzureVirtualNetworkSubnetConfigCommand.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetwork\TestAzurePrivateIpAddressAvailabilityCmdlet.cs
C:\azure-powershell\src\ResourceManager\Resources\Commands.ResourceManager\Cmdlets\Implementation\Policy\NewAzurePolicyAssignment.cs
C:\azure-powershell\src\ResourceManager\Resources\Commands.ResourceManager\Cmdlets\Implementation\Policy\SetAzurePolicyAssignment.cs
C:\azure-powershell\src\ResourceManager\Resources\Commands.Resources\ActiveDirectory\Cmdlets\NewAzureADServicePrincipalCommand.cs
C:\azure-powershell\src\ResourceManager\Resources\Commands.Resources\ActiveDirectory\Cmdlets\NewAzureADSpCredentialCommand.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Database Backup\Cmdlet\GetAzureSqlDatabaseBackupLongTermRetentionPolicy.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Database Backup\Cmdlet\SetAzureSqlDatabaseBackupLongTermRetentionPolicy.cs (x2)
C:\azure-powershell\src\ResourceManager\Websites\Commands.Websites\Models.WebApp\PSAppServicePlan.cs
C:\azure-powershell\src\ResourceManager\Websites\Commands.Websites\Models.WebApp\PSCertificate.cs
C:\azure-powershell\src\ResourceManager\Websites\Commands.Websites\Models.WebApp\PSCloningInfo.cs
C:\azure-powershell\src\ResourceManager\Websites\Commands.Websites\Models.WebApp\PSSite.cs

obsolete
C:\azure-powershell\src\ResourceManager\ApiManagement\Commands.ApiManagement\Commands\ImportAzureApiManagementHostnameCertificate.cs
C:\azure-powershell\src\ResourceManager\ApiManagement\Commands.ApiManagement\Commands\NewAzureApiManagementHostnameConfiguration.cs
C:\azure-powershell\src\ResourceManager\ApiManagement\Commands.ApiManagement\Commands\NewAzureApiManagementVirtualNetwork.cs
C:\azure-powershell\src\ResourceManager\ApiManagement\Commands.ApiManagement\Commands\SetAzureApiManagementHostnames.cs
C:\azure-powershell\src\ResourceManager\ApiManagement\Commands.ApiManagement\Commands\UpdateAzureApiManagementDeployment.cs
C:\azure-powershell\src\ResourceManager\ApiManagement\Commands.ApiManagement\Models\PsApiManagement.cs
C:\azure-powershell\src\ResourceManager\ApiManagement\Commands.ApiManagement\Models\PsApiManagementRegion.cs
C:\azure-powershell\src\ResourceManager\Automation\Commands.Automation\help\Import-AzAutomationRunbook.md
C:\azure-powershell\src\ResourceManager\Automation\Commands.Automation\help\New-AzAutomationRunbook.md
C:\azure-powershell\src\ResourceManager\CognitiveServices\Commands.Management.CognitiveServices\ObsoletedModels\ProvisioningState.cs
C:\azure-powershell\src\ResourceManager\DataLakeAnalytics\Commands.DataLakeAnalytics\Commands\NewAzureRmDataLakeAnalyticsCatalogSecret.cs
C:\azure-powershell\src\ResourceManager\DataLakeAnalytics\Commands.DataLakeAnalytics\Commands\RemoveAzureRmDataLakeAnalyticsCatalogSecret.cs
C:\azure-powershell\src\ResourceManager\DataLakeAnalytics\Commands.DataLakeAnalytics\Commands\SetAzureRmDataLakeAnalyticsCatalogSecret.cs
C:\azure-powershell\src\ResourceManager\DataLakeAnalytics\Commands.DataLakeAnalytics\Models\ObsoleteUSqlCredential.cs
C:\azure-powershell\src\ResourceManager\DataLakeAnalytics\Commands.DataLakeAnalytics\Models\PSDataLakeAnalyticsAccountBasic.cs
C:\azure-powershell\src\ResourceManager\DataLakeAnalytics\Commands.DataLakeAnalytics\Models\PSJobInformationBasic.cs
C:\azure-powershell\src\ResourceManager\DataLakeAnalytics\Commands.DataLakeAnalytics\Models\PSStorageAccountInfo.cs
C:\azure-powershell\src\ResourceManager\DataLakeStore\Commands.DataLakeStore\Models\PSDataLakeStoreAccountBasic.cs
C:\azure-powershell\src\ResourceManager\KeyVault\Commands.KeyVault\Models\PSKeyVaultKeyAttributes.cs
C:\azure-powershell\src\ResourceManager\KeyVault\Commands.KeyVault\Models\PSKeyVaultKeyIdentityItem.cs
C:\azure-powershell\src\ResourceManager\KeyVault\Commands.KeyVault\Models\PSKeyVaultSecretAttributes.cs
C:\azure-powershell\src\ResourceManager\Media\Commands.Media\MediaService\NewAzureRmMediaService.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\Models\PSApplicationGatewayBackendHttpSettings.cs
C:\azure-powershell\src\ResourceManager\Network\Commands.Network\VirtualNetworkGateway\SetAzureVirtualNetworkGatewayVpnClientConfig.cs
C:\azure-powershell\src\ResourceManager\RecoveryServices\Commands.RecoveryServices.SiteRecovery\Policy\NewAzureRmRecoveryServicesAsrPolicy.cs
C:\azure-powershell\src\ResourceManager\RecoveryServices\Commands.RecoveryServices.SiteRecovery\Policy\UpdateAzureRmRecoveryServicesAsrPolicy.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Auditing\Cmdlet\GetAzureSqlDatabaseAuditingPolicy.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Auditing\Cmdlet\GetAzureSqlServerAuditingPolicy.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Auditing\Cmdlet\RemoveSqlDatabaseAuditing.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Auditing\Cmdlet\RemoveSqlServerAuditing.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Auditing\Cmdlet\SetAzureSqlDatabaseAuditingPolicy.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Auditing\Cmdlet\SetAzureSqlServerAuditingPolicy.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Auditing\Cmdlet\UseAzureSqlServerAuditingPolicy.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\ServiceObjective\Cmdlet\AzureSqlServerServiceObjectiveCmdletBase.cs

WriteWarning
C:\azure-powershell\src\ResourceManager\CognitiveServices\Commands.Management.CognitiveServices\CognitiveServicesAccount\GetAzureCognitiveServicesAccountSkus.cs
C:\azure-powershell\src\ResourceManager\DataFactories\Commands.DataFactories\Encrypt\NewAzureDataFactoryEncryptValueCommand.cs
C:\azure-powershell\src\ResourceManager\DataFactories\Commands.DataFactories\Gateway\NewAzureDataFactoryGatewayKeyCommand.cs
C:\azure-powershell\src\ResourceManager\DataLakeAnalytics\Commands.DataLakeAnalytics\Commands\GetAzureRmDataLakeAnalyticsAccount.cs
C:\azure-powershell\src\ResourceManager\DataLakeAnalytics\Commands.DataLakeAnalytics\Commands\NewAzureRmDataLakeAnalyticsCatalogCredential.cs
C:\azure-powershell\src\ResourceManager\DataLakeAnalytics\Commands.DataLakeAnalytics\Commands\NewAzureRmDataLakeAnalyticsCatalogSecret.cs
C:\azure-powershell\src\ResourceManager\DataLakeAnalytics\Commands.DataLakeAnalytics\Commands\SetAzureRmDataLakeAnalyticsCatalogCredential.cs
C:\azure-powershell\src\ResourceManager\DataLakeAnalytics\Commands.DataLakeAnalytics\Commands\SetAzureRmDataLakeAnalyticsCatalogItemAclEntry.cs
C:\azure-powershell\src\ResourceManager\DataLakeAnalytics\Commands.DataLakeAnalytics\Commands\SetAzureRmDataLakeAnalyticsCatalogSecret.cs
C:\azure-powershell\src\ResourceManager\DataLakeStore\Commands.DataLakeStore\DataPlaneCommands\SetAzureRmDataLakeStoreItemAcl.cs
C:\azure-powershell\src\ResourceManager\DataLakeStore\Commands.DataLakeStore\DataPlaneCommands\SetAzureRmDataLakeStoreItemAclEntry.cs
C:\azure-powershell\src\ResourceManager\DataLakeStore\Commands.DataLakeStore\DataPlaneCommands\SetAzureRmDataLakeStoreItemOwner.cs
C:\azure-powershell\src\ResourceManager\Dns\Commands.Dns\Zones\NewAzureDnsZone.cs
C:\azure-powershell\src\ResourceManager\Dns\Commands.Dns\Zones\SetAzureDnsZone.cs
C:\azure-powershell\src\ResourceManager\Insights\Commands.Insights\Diagnostics\SetAzureRmDiagnosticSettingCommand.cs (x2)
C:\azure-powershell\src\ResourceManager\Insights\Commands.Insights\MonitorCmdletBase.cs
C:\azure-powershell\src\ResourceManager\OperationalInsights\Commands.OperationalInsights\DataSources\GetAzureOperationalInsightsDataSourceCommand.cs
C:\azure-powershell\src\ResourceManager\RecoveryServices\Commands.RecoveryServices.Backup.Providers\AzureWorkloadProviderHelper.cs
C:\azure-powershell\src\ResourceManager\RecoveryServices\Commands.RecoveryServices.SiteRecovery\Common\AsrCmdletBase.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Auditing\Cmdlet\AuditingSettings\SqlDatabaseAuditingSettingsCmdletBase.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Auditing\Cmdlet\AuditingSettings\SqlServerAuditingSettingsCmdletBase.cs
C:\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Data Masking\Cmdlet\SetAzureSqlDatabaseDataMaskingPolicy.cs

**Comment by maddieclayton** [comment]
Done!
