### ISSUE TITLE
Update DependencyMap.csv to filter System dependencies correctly

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#8042]
Ensure that the CheckAssemblies script will correctly throw if System dependencies are included that are not part of NetFramework: https://github.com/Azure/azure-powershell/blob/master/tools/StaticAnalysis/DependencyAnalyzer/DependencyAnalyzer.cs#L249

**Comment by cormacpayne** [comment]
Make sure that `Newtonsoft.Json` is handled correctly as well.

**Comment by maddieclayton** [comment]
Done here: https://github.com/Azure/azure-powershell/pull/8192
