### ISSUE TITLE
Unable to create linked templates 

### ISSUE THREAD

**Issue by itsramz** [Azure/azure-powershell#8045]
New-AzureRmResourceGroupDeployment : 12:10:04 PM - Resource Microsoft.Cache/redis/providers/diagnosticsettings 
'demoredisc3/Microsoft.Insights/demoredisc3' failed with message '{
  "error": {
    "code": "LinkedInvalidPropertyId",
    "message": "Property id 'GET-PREREQ-existingDiagnosticsStorageAccountId' at path 'properties.storageAccountId' is invalid. 
Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."
  }
}'
At line:1 char:1
+ New-AzureRmResourceGroupDeployment -ResourceGroupName "spaceship_demo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

**Comment by itsramz** [comment]
Im unable to link the following templates . Ky vault,storage account,redis cache,webapp,asp,sql db ,application insights. together. I hsve seperate templates with me.

**Comment by deathly809** [comment]
@itsramz Could you please fill in the above sections?  Without those I am not sure what can be done.

**Comment by itsramz** [comment]
Im trying to link templates , but for the Redis cache I need to get the Storage account ID as the input Hence gave the command as GET-PREREQ-existingDiagnosticsStorageAccountId' but it doesnt pull the id.Please share your views on it

**Comment by deathly809** [comment]
I am a little confused.  Are you saying there is an outer template which you deploy a storage account and an inner template that uses that storage account?

If so you can construct the storage account id using the following:

```
resourceId([subscriptionId], [resourceGroupName], resourceType, resourceName1, [resourceName2]...)
```

for you it would look something like this,

```
[resourceId('Microsoft.Storage/storageAccounts', variables('storageAccountName'))]
```

**Comment by maddieclayton** [comment]
Please open an issue here if you are still having issues with ARM templates: https://github.com/Azure/azure-quickstart-templates.
