### ISSUE TITLE
Connect-AzAccount

### ISSUE THREAD

**Issue by bkemmle** [Azure/azure-powershell#8077]
Hello,

i just used the command "Install-Module -Name Az" version 0.7

after the installation has been done i tried the following command as described in the example:

$Credential = Get-Credential

PS C:\> Connect-AzAccount -Credential

https://github.com/Azure/azure-powershell/blob/4713c26fd6dff06eeadf3d1b8da721e4b2727922/src/ResourceManager/Profile/Commands.Profile/help/Connect-AzAccount.md

This command is working as described:

PS > $Credential = Get-Credential
Cmdlet Get-Credential an der Befehlspipelineposition 1
Geben Sie Werte für die folgenden Parameter an:
Credential

PS > Connect-AzAccount -Credential $Credential

Cmdlet Connect-AzAccount an der Befehlspipelineposition 1
Geben Sie Werte für die folgenden Parameter an:
(Geben Sie !? ein, um Hilfe zu erhalten.)
ServicePrincipal:

Without a serviceprincipal the command is somehow not working.

Thanks.

**Comment by markcowl** [comment]
@bkemmie  Non-interactive username/password credentials are not supported cross-platform.  This functionality is scheduled to be added back for WIndows PowewrShell 5.1 in January 2019.  You cna track progress on this in: #7430  Closing this as a duplicate.
