### ISSUE TITLE
New-AzureAutomationModule (arm) should fail on non-existing contentLink

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#809]
When adding an automationmodule and pointing to a contentlink that doesn't exist, an (emtpy) module still gets created. 

Expected behavior: non-terminating error.

repro: New-AzureAutomationModule -ContentLink "http://nowhere.com/nope.zip" -Name test

**Comment by pcgeek86** [comment]
Definitely agree on this feedback. Good catch, Trond.

Cheers,
Trevor Sullivan

**Comment by devigned** [comment]
@jodoglevy thoughts on this one?

**Comment by jodoglevy** [comment]
I'll open a bug. One thing we're already doing to help in this area -- in our cmdlet docs we are adding this statement:


When importing a PowerShell module into Azure Automation using the New-AzureAutomationModule or Set-AzureAutomationModule cmdlets, the module import is asynchronous. Even if the cmdlet returns successfully, that does not mean module import has succeeded. To check if import has succeeded, use Get-AzureAutomationModule –Name <ModuleName> (make sure to get just this module, not all modules) and check that the ProvisioningState field of the module says succeeded.

Should help with folks thinking module imported succeeded when actually it is async

**Comment by cormacpayne** [comment]
@vrdmr Hey Varad, would you mind seeing if this is still an issue, and if so, seeing if it fits on your team's radar?

**Comment by vrdmr** [comment]
@sourabhguha @AnatoliB Can you please take a look at this issue? Thanks

**Comment by jeffzabel** [comment]
No recurrences of this issue since documentation was updated.  Closing
