### ISSUE TITLE
Add test automation for storage account pipeline scenarios

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#8102]
In this PR:#8068  EnableHttpsTraffic was removed from pipelining scenarios.  Need to add test automation to ensure that the correct values are passed when piping Get | Set and Get | New for storage accounts

**Comment by blueww** [comment]
@markcowl, @MiYanni 
Is there a guide doc to build/run netcore Test? Is seems [this guid ](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/azure-powershell-developer-guide.md) does not work for netcore test.
I tried to build `src\Azure.PowerShell.Netcore.Test.sln ` in VS, but failed with follow error:

> Unable to find package Microsoft.Azure.PowerShell.TestPrerequisites. No packages exist with this id in source(s): C:\code\PSH_Dev\src\local-artifacts, C:\code\PSH_Dev\tools\LocalFeed, dotnet-core, localnuget, myget-azure-powershell, nuget.org, powershell-core

**Comment by blueww** [comment]
@MiYanni 
Thanks for the help!
I have updated the test, and PR is sent. https://github.com/Azure/azure-powershell/pull/8133

**Comment by markcowl** [comment]
Fixed
