### ISSUE TITLE
Retrieve quickstart template for default image in New-AzVm

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#8107]
From email:

CLI  creates a VM from quickstart-template (https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/quickstart-templates/aliases.json ) to get an image sku if image is not given.

The simplified parameter set of New-AzVM creates a VM from images.cs file (https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/Compute/Commands.Compute/Strategies/ComputeRp/Images.cs )

So, sometimes those two files are not sync, and someone needs to update Powershell code.  (e.g  this PR: https://github.com/Azure/azure-powershell/pull/8028)

Guy told me if we could make a change so that Powershell retrieves the quickstart template file during build time.

Do you think this is feasible?

Note that CLI gets the quickstart-template time in runtime, and we have an issue about the runtime dependency to Github repository.  ( https://github.com/Azure/azure-cli/issues/4611 )

So, Runtime dependency to Github repository may not be appropriate, but can we change Powershell to get the file during build time?

**Comment by cormacpayne** [comment]
Need discussion with Compute, but it also appears that the underlying file from the specs repository doesn't change that often, so we may be able to pull this information once a release manually.
