### ISSUE TITLE
[Azure Stack] Cmdlet New-DataDiskObject  missing Azs Prefix

### ISSUE THREAD

**Issue by troettinger** [Azure/azure-powershell#8109]
### Description

Missing Azs Prefix
Function        New-DataDiskObject                                 0.2.0      Azs.Compute.Admin

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by deathly809** [comment]
This is a duplicate of #8111
