### ISSUE TITLE
[Azure Stack] Cmdlet  New-DataDiskObject missing Prefix Azs

### ISSUE THREAD

**Issue by troettinger** [Azure/azure-powershell#8111]
### Description
Missing Prefix Azs
Function        New-DataDiskObject                                 0.2.0      Azs.Compute.Admin

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by markcowl** [comment]
@deathly809 Can you take a look?
