### ISSUE TITLE
Update to SQL Server Auditing cmdlets for event hub and log analytics?

### ISSUE THREAD

**Issue by tstahnke2** [Azure/azure-powershell#8122]
We are beginning to utilize the the new preview functionality for sql auditing using event hub and log analytics. I've noticed that the latest version of Az (0.7.0) doesn't have support for eventhub or log analytics settings. When can we expect to see that support added?

**Comment by markcowl** [comment]
@jaredmoo Can you please take a look att his question?

**Comment by jaredmoo** [comment]
@yaakoviyun , who is the correct person from data security to look into this?

**Comment by salexu** [comment]
Support for auditing to log analytics and event hub is something that is on our backlog and is planned to be supported in the near future (no exact timeline yet).

**Comment by dmarlow** [comment]
+1. I recently wanted to change the Audit Action Group and had to turn on sending to storage when I only wanted to send to Log Analytics.

**Comment by salexu** [comment]
This is now supported in the latest cmdlets version 1.4.0.
See https://docs.microsoft.com/en-us/azure/sql-database/sql-database-auditing#subheading-7 for links.
