### ISSUE TITLE
Update AzureRM.Resources.ps1 and AzureRM.Storage.ps1 to use Az naming

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#8124]
Our test scripts we share out of `ScenarioTests.ResourceManager` use the `AzureRM` naming convention. We should update these to have aliases to an `Az` version of those functions. This allows new tests being created to only have to use the `Az` nomenclature.

**Comment by maddieclayton** [comment]
Done. I have an additional PR open to rename all of the tests, but this is unrelated
