### ISSUE TITLE
Import-AzureKeyVaultCertificate: Can spill password if used incorrectly

### ISSUE THREAD

**Issue by austvik** [Azure/azure-powershell#8135]
### Description

I have a cert at $pfxPath, and want to import it into a keyvault.

I have done a mistake. The password used to export it (created like this: [string] $securepfxpwd = [Guid]::NewGuid().ToString(), because I don't want to know it) 

I run:

```powershell
Import-AzureKeyVaultCertificate -VaultName $keyvault -Name $certname -FilePath $pfxPath -Password $securepfxpwd
```

I get:

```powershell
Import-AzureKeyVaultCertificate : Cannot bind parameter 'Password'. Cannot convert the "9240f730-812b-493e-b2a3-0fa8f4d386b9" value of type "System.String" to type "System.Security.SecureString".
```

And my password is leaked.

Expectation: CmdLets dealing with secrets to never print that information. This might be a general bug in Powershell, if so - please forward.

### Script/Steps for Reproduction

```powershell
[string] $securepfxpwd = [Guid]::NewGuid().ToString()

Import-AzureKeyVaultCertificate -VaultName $keyvault -Name $certname -FilePath $pfxPath -Password $securepfxpwd
```

### Module Version

```powershell
Get-Module -ListAvailable

Script     5.2.1      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Update-AzureKeyVaultCertificate, Stop-AzureKeyVaultCertif...
Script     4.3.0      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Set-AzureKeyVaultCertificateAttribute, Stop-AzureKeyVault..
```

### Environment Data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by markcowl** [comment]
@austvik this is an automatic message from powershell, unfortunately.  This would also be written to the error stream, so it could be picked up later by examining $Error.  Unfortunately, since PowerShell is a different org than azure, I can't directly transfer the issue, but you can file an issue in their repo:

https://gitub.com/powershell/powershell  and link to this one.
