### ISSUE TITLE
Fix tagging for resource groups

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#8166]
### Description

Currently, tagging resource groups is only available through Set-AzResourceGroup, which will remove any additional properties applied to the resource group (e.g ManagedBy)

**Comment by lwajswaj** [comment]
Do you mean it will remove addition tags in the resource group?

**Comment by maddieclayton** [comment]
@markcowl Can you flesh out this issue a little further?

**Comment by markcowl** [comment]
No, there are properties that can exist in the resource group itself (as a resource) that do not always exist.  For example, for 'ManagedBy' is a property that exists if a resource group is created by a service as a by-product of some other task (for example, some resources create a resource group in the region to place shared resources on behalf of the user.

The issue is that, the serialization model for ResourceGroup does not contain any of these additional properties, so if a PUT is performed, it will remove any values from these properties, because the proeprty is not specified in the payload of the put.

For example, a resource like:
```json
{
   "properties": {
     "name": "foo",
     "id": "/subscriptions/xxxx-xxxx-xxxx-yyyy/ResourceGroups/foo",
     "tags:': ["foo", "bar"]
     "managedBy": "Microsoft.Widgets"
   }
}
```

will appear in the PUT payload as:

```json
{
   "properties": {
     "name": "foo",
     "id": "/subscriptions/xxxx-xxxx-xxxx-yyyy/ResourceGroups/foo",
     "tags:': ["foo", "bar"]
   }
}
```

So that the additional property 'ManagedBy' is removed.

This can be resolved in a couple of ways:
 (1) Since this cmdlet can really only be used for tags, perform a PATCH instead of a PUT, this will automatically make the operation resilient over changes in the model
(2) Update the mode for the PUT to include the known optional properties
