### ISSUE TITLE
Set-AzureRmVMCustomScriptExtension : Multiple VMExtensions per handler not supported for OS type 'Windows'

### ISSUE THREAD

**Issue by bikramgcnz** [Azure/azure-powershell#8173]
This seems like a common error many enterprise level deployments run into.

We are trying to run multiple extensions in a VM for a configuration. I know a work around i.e remove existing extension and install new one.

Why is it so difficult to be fixed so we can run as many extensions as we like it?

**Comment by markcowl** [comment]
@danielsollondon Can you answer about the capabilities of the extensions API, and whether there are any plans to support the scenario described?

**Comment by GabstaMSFT** [comment]
This is by design, if you want to run multiple extensions as you describe Managed RunCommand would work.  https://learn.microsoft.com/en-us/azure/virtual-machines/windows/run-command-managed
