### ISSUE TITLE
0.9.7 :: Docs for New-AzureSqlServer -ServerVersion parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#818]
# Problem

> Use 2.0 to create a V11 server, or 12.0 to create a V11 server.

![image](https://cloud.githubusercontent.com/assets/466713/9582570/5af869ee-4fc3-11e5-8cb6-40f9a61b7d64.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by devigned** [comment]
@akromm thoughts on this one?

**Comment by akromm** [comment]
This looks like some find&replace errors.  This has been fixed.
