### ISSUE TITLE
Typo inside Json file Error

### ISSUE THREAD

**Issue by PhenixCorp** [Azure/azure-powershell#8190]
### Description

The issue is a Typo Error inside the generation of Json file in especially Task Endpoint of Security Center
The Name is wrote : 'GenericSecuirtyTask' insteed GenericSecurityTask  It's just this ;) 
But for a treat inside a script etc. we must to have the good term ;) 

### Script/Steps for Reproduction

Just make a Rest Invoke (C# or PowerShell) on Endpoint Task List for example. 
https://docs.microsoft.com/en-us/rest/api/securitycenter/tasks/list

GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Security/tasks?api-version=2015-06-01-preview

``` Response of Json File excerpt

 {
        "resourceType":  "Subscription",
        "assessmentKey":  "57e98606-6b1e-6193-0e3d-fe621387c16b",
        "policyName":  "Enable MFA for Azure Management App accounts with write permissions on your subscription",
        "policyDefinitionId":  "temp policy resource id for enable MFA for accounts with write",
        "severity":  "Medium",
        "name":  "**GenericSecuirtyTask**",
    },
    {
        "resourceType":  "Subscription",
        "assessmentKey":  "6f90a6d6-d4d6-0794-0ec1-98fa77878c2e",
        "policyName":  "Designate up to 3 owners on your subscription",
        "policyDefinitionId":  "temp policy resource id for designate up to X owners",
        "severity":  "Medium",
        "name":  "**GenericSecuirtyTask**",
    },
    {
        "resourceType":  "Subscription",
        "assessmentKey":  "94290b00-4d0c-d7b4-7cea-064a9554e681",
        "policyName":  "Enable MFA for Azure Management App accounts with owner permissions on your subscription",
        "policyDefinitionId":  "temp policy resource id for enable MFA for accounts with owner",
        "severity":  "High",
        "name":  "**GenericSecuirtyTask**",
    },

I've deleted the UniqueKey and ResourceId for privacy and security. 

```

### Module Version

Azure installed on your machine --> 6.13.1

### Environment Data

Name                           Value                                                                                                                                                                                           
----                           -----                                                                                                                                                                                           
PSVersion                      5.1.17134.407                                                                                                                                                                                   
PSEdition                      Desktop                                                                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                         
BuildVersion                   10.0.17134.407                                                                                                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                                                                             
SerializationVersion           1.1.0.1
```

**Comment by markcowl** [comment]
@PhenixCorp This isn't an issue with Azure PowerShell, but with the service itself.  To get this fixed, you will need to contact the Security Center team.
