### ISSUE TITLE
get-azurevm (arm) does not return vm state

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#820]
The arm api exposes vm status thru the "statuses" object. However, this is not included in the object returned by get-azurevm. This means that there is no way to check wether a VM is running or not thru arm powershell.

**Comment by pcgeek86** [comment]
There is a `-Status` parameter on `AzureResourceManager\Get-AzureVM`.

![image](https://cloud.githubusercontent.com/assets/466713/9583283/b26bc726-4fc7-11e5-8f76-abeb97c0d8e2.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by trondhindenes** [comment]
now i just feel stupid.

**Comment by pcgeek86** [comment]
It's okay, I've slipped up before. It's hard to know if navigating online documentation, built-in docs, random blog entries, or looking at command metadata is the right way to go. With too many information sources, there isn't really a specific, recommended practice for discovering "how to" information.

Cheers,
Trevor Sullivan
