### ISSUE TITLE
0.9.7 ARM :: New-AzureResourceGroup -TemplateVersion parameter not working

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#821]
# Problem 
1. I have an ARM JSON template with a version of .1.0.0.0`.
2. In my invocation of `New-AzureResourceGroup`, I am specifying the `-TemplateVersion` parameter of `2.0.2.0`.
3. The command deploys the template.
4. I am concerned.

![2015-08-31 10_38_13-photos](https://cloud.githubusercontent.com/assets/466713/9584129/9ab9bdcc-4fcc-11e5-9937-e79cc9772574.png)

![image](https://cloud.githubusercontent.com/assets/466713/9584164/d9403c38-4fcc-11e5-814d-9541fd849000.png)

# Expected Result

The template should not deploy, and throw an exception regarding version mismatches.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by devigned** [comment]
@vivsriaus thoughts on this one

**Comment by ravbhatnagar** [comment]
All the template deployment related params have been removed from the New-AzureRmResourceGroup cmdlet in the PS version 1.0. The templateVersion param has been removed from the New-AzureRmResourceGroupDeployment to avoid such problems.

**Comment by pcgeek86** [comment]
@ravbhatnagar I thought the `-TemplateVersion` parameter was there for a specific reason. It should still exist on `New-AzureRmResourceGroupDeployment`, shouldn't it? 

Cheers,
Trevor Sullivan
