### ISSUE TITLE
"Enable-AzureRMAlias -Scope CurrentUser" does not persist between sessions

### ISSUE THREAD

**Issue by tlisiecki** [Azure/azure-powershell#8215]
"Enable-AzureRMAlias -Scope CurrentUser" should enable aliases cross sessions. 
It is supposed to add an entry to profile.ps1 in which it enables aliases upon shell start. 
It doesn`t seem to work properly for me though.
I believe it is due to the following line: 
https://github.com/Azure/azure-powershell/blob/32d2e398e5f0f97c6a43eb1641dcd3a7a7369b5b/src/ResourceManager/Profile/Commands.Profile/AzureRmAlias/AliasHelper.cs#L150

The code that is added to the profile.ps1 checks weather Az.Profile module is available on the system and if it is then it enables aliases. The problem is that Az.Profile module does not exist at all. I believe it used to be AzureRM.Profile that got migrated to Az.Accounts (at least according to https://github.com/Azure/azure-powershell/blob/master/documentation/announcing-az-module.md#module-name-changes) and it is Az.Accounts not Az.Profile that should be initailly checked.

**Comment by maddieclayton** [comment]
@tlisiecki  Thank you for this catch, you are absolutely right.  I will work on this fix and it will be released on 1/15.

**Comment by tlisiecki** [comment]
Hi @maddieclayton. Thanks for your support! 
As for the workaround - yes that`s what I`ve done for myself and I can confirm it works fine that way.

**Comment by maddieclayton** [comment]
Merged, will likely be released on 1/15 unless we have a patch earlier.
