### ISSUE TITLE
Stop-AzureRmVM Id parameter documentaion

### ISSUE THREAD

**Issue by StefanSchoof** [Azure/azure-powershell#8225]
### Description

At https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/stop-azurermvm?view=azurermps-6.13.0#required-parameters the Parameter `-Id` is documented with:
```
The resource group name
```
Since there is an parameter `-ResourceGroupName` this sound wrong.

### Script/Steps for Reproduction

N/A

### Module Version

6.13.0

### Environment Data

N/A

### Debug Output

N/A

See also https://github.com/Azure/azure-docs-powershell/issues/893

**Comment by maddieclayton** [comment]
@StefanSchoof Thanks for pointing this out! Opened a PR to fix this here: https://github.com/Azure/azure-powershell/pull/8229.

**Comment by maddieclayton** [comment]
Fixed.
