### ISSUE TITLE
0.9.7 ARM :: New-AzureVirtualNetworkGateway :: -VnetId and -VNetName parameters

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#824]
# Problem

Why does `New-AzureVirtualNetworkGateway` have only a single parameter set, but offer **both** the `-VnetId` and `-VNetName` parameters? Shouldn't the user only specify one or the other parameter? 
# Expected Result
1. `-VnetId` and `-VNetName` parameters should be broken out into parameter sets.
2. `-VnetId` and `-VNetName` parameters should use consistent capitalization rules.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by devigned** [comment]
@DeepakRajendranMsft thoughts on this one?

**Comment by DeepakRajendranMsft** [comment]
@Nilambari who owns them

**Comment by cormacpayne** [comment]
Doesn't appear this is the case in `New-AzureRmVirtualNetworkGateway`. Closing this issue.
