### ISSUE TITLE
Package 'Az.Relay' failed to be installed

### ISSUE THREAD

**Issue by joergschurig** [Azure/azure-powershell#8244]
PS P:\> Install-Module -Name Az -AllowClobber

Nicht vertrauenswürdiges Repository
Sie installieren die Module aus einem nicht vertrauenswürdigen Repository. Wenn Sie diesem Repository vertrauen, ändern
 Sie dessen InstallationPolicy-Wert, indem Sie das Set-PSRepository-Cmdlet ausführen. Möchten Sie die Module von
'PSGallery' wirklich installieren?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
PackageManagement\Install-Package : Package 'Az.Relay' failed to be installed because: Der Prozess kann nicht auf die
Datei "C:\Users\rdbschurig\AppData\Local\Temp\kvcsookq\Microsoft.Azure.PowerShell.Cmdlets.Relay.dll" zugreifen, da sie
von einem anderen Prozess verwendet wird.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (Az.Relay:String) [Install-Package], Exception
    + FullyQualifiedErrorId : Package '{0}' failed to be installed because: {1},Microsoft.PowerShell.PackageManagement
   .Cmdlets.InstallPackage

What can i do that the install work?

**Comment by cormacpayne** [comment]
@joergschurig would you mind doing the following?

- Close all existing PowerShell windows (including VS Code if you have the PowerShell extension installed) and try installing the module again
- If the module still won't install, please provide the following information:
    - The list of Azure PowerShell modules installed on your machine using the command `Get-Module -Name Az* -ListAvailable`
    - The debug trace from the installation command -- you can get this by setting `$DebugPreference = "Continue"` before running the `Install-Module` command you run above

**Comment by joergschurig** [comment]
thanks for effort. i make a new vm with windows 10 and it works :-)

**Comment by cormacpayne** [comment]
@joergschurig good to hear! Please let us know if you continue to see this issue.
