### ISSUE TITLE
0.9.7 ARM :: New-AzureVirtualNetworkGateway :: Intellisense

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#825]
# Problem

The `New-AzureVirtualNetworkGateway` command does not offer Intellisense / auto-completion for the `-GatewaySKU` and `-GatewayType` parameters.

# Expected Result

The `New-AzureVirtualNetworkGateway` command should offer Intellisense / auto-completion for the `-GatewaySKU` and `-GatewayType` parameters.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by devigned** [comment]
@DeepakRajendranMsft any thoughts on this?

**Comment by DeepakRajendranMsft** [comment]
@Nilambari  who owns them

**Comment by markjbrown** [comment]
Confirmed this is fixed. Closing issue.

![it works](https://cloud.githubusercontent.com/assets/800166/15398185/9558267c-1d97-11e6-81a6-4e3de529ef5a.PNG)
