### ISSUE TITLE
Set-AzureStorageBlobContent Cannot Bind Parameter 'Context'

### ISSUE THREAD

**Issue by AxtralSteel** [Azure/azure-powershell#8265]
### Description

Hi,

I'm having an issue with uploading a file to a storage account in my script and was hoping for some assistance.

For context, the whole script cycles through all of our subscriptions gathering information, then emails that information. The last stage is to save a copy of that information into a storage account. It successfully connects to the storage account and deletes files in it earlier in the script using the same context as below.

### Script/Steps for Reproduction
I'm using the following code. This is currently running on my machine, but I intend it to run in an Automation account when complete.

```
$StorageContext = New-AzStorageContext -StorageAccountName $Storage.StorageAccountName -StorageAccountKey $Blob
...
Set-AzureStorageBlobContent -Container $Container -context $StorageContext -File Test.csv -Blob Test.csv
```

And I am getting the error: 

> Set-AzureStorageBlobContent : Cannot bind parameter 'Context'. Cannot convert the "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" value of type 
> "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" to type "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IStorageContext".
> At line:1 char:60
> + ... ageBlobContent -Container $Container -context $StorageContext -File T ...
> +                                                   ~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Set-AzureStorageBlobContent], ParameterBindingException
>     + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.WindowsAzure.Commands.Storage.Blob.SetAzureBlobContentCommand

I have tried this in both the ISE and a standard PowerShell window.

### Module Version

>     Directory: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
> 
> 
> ModuleType Version    Name
> ---------- -------    ----                                                                                                                       
> Manifest   1.0.0.0    ActiveDirectory
> Manifest   1.0.0.0    AppLocker  
> Manifest   1.0.0.0    BitsTransfer                              
> Manifest   1.0.0.0    CimCmdlets                               
> Manifest   1.0.0.0    FailoverClusters 
> Manifest   1.0.0.0    GroupPolicy                
> Script     1.0.0.0    ISE                         
> Manifest   1.0.1.0    Microsoft.PowerShell.Archive       
> Manifest   3.0.0.0    Microsoft.PowerShell.Diagnostics 
> Manifest   3.0.0.0    Microsoft.PowerShell.Host           
> Manifest   1.0.0.0    Microsoft.PowerShell.LocalAccounts                                  
> Manifest   3.1.0.0    Microsoft.PowerShell.Management   
> Script     1.0        Microsoft.PowerShell.ODataUtils      
> Manifest   3.0.0.0    Microsoft.PowerShell.Security      
> Manifest   3.1.0.0    Microsoft.PowerShell.Utility        
> Manifest   3.0.0.0    Microsoft.WSMan.Management  
> Manifest   1.0.0.0    NetworkLoadBalancingClusters   
> Manifest   1.0.0.0    NetworkSwitchManager             
> Manifest   1.1        PSDesiredStateConfiguration       
> Script     1.0.0.0    PSDiagnostics                                    
> Binary     1.1.0.0    PSScheduledJob                             
> Manifest   2.0.0.0    PSWorkflow                                         
> Manifest   1.0.0.0    PSWorkflowUtility            
> Manifest   1.0.0.0    TroubleshootingPack      
> 
> 
>     Directory: C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules
> 
> 
> ModuleType Version    Name                       
> ---------- -------    ----                                
> Manifest   1.0        SQLASCMDLETS                               
> Manifest   1.0        SQLPS                           
> 
> 
>     Directory: C:\Program Files\WindowsPowerShell\Modules
> 
> 
> ModuleType Version    Name                                                                                                              
> ---------- -------    ----                                                                                                             
> Script     1.0.0      Az.Accounts                    
> Script     1.0.0      Az.Aks                           
> Script     1.0.0      Az.AnalysisServices      
> Script     1.0.0      Az.ApiManagement       
> Script     1.0.0      Az.ApplicationInsights       
> Script     1.0.0      Az.Automation                
> Script     1.0.0      Az.Batch                               
> Script     1.0.0      Az.Billing                       
> Script     1.0.0      Az.Cdn                     
> Script     1.0.0      Az.CognitiveServices     
> Script     1.0.0      Az.Compute                       
> Script     1.0.0      Az.ContainerInstance               
> Script     1.0.0      Az.ContainerRegistry          
> Script     1.0.0      Az.DataFactory                            
> Script     1.0.0      Az.DataLakeAnalytics        
> Script     1.0.0      Az.DataLakeStore            
> Script     1.0.0      Az.DevTestLabs             
> Script     1.0.0      Az.Dns                                     
> Script     1.0.0      Az.EventGrid                            
> Script     1.0.0      Az.EventHub          
> Script     1.0.0      Az.HDInsight      
> Script     1.0.0      Az.IotHub                            
> Script     1.0.0      Az.KeyVault             
> Script     1.0.0      Az.LogicApp                  
> Script     1.0.0      Az.MachineLearning          
> Script     1.0.0      Az.MarketplaceOrdering                  
> Script     1.0.0      Az.Media                       
> Script     1.0.0      Az.Monitor                        
> Script     1.0.0      Az.Network                
> Script     1.0.0      Az.NotificationHubs           
> Script     1.0.0      Az.OperationalInsights        
> Script     1.0.0      Az.PolicyInsights                           
> Script     1.0.0      Az.PowerBIEmbedded            
> Script     0.7.0      Az.Profile              
> Script     1.0.0      Az.RecoveryServices       
> Script     1.0.0      Az.RedisCache          
> Script     1.0.0      Az.Relay                        
> Script     1.0.0      Az.Resources                  
> Script     1.0.0      Az.ServiceBus         
> Script     1.0.0      Az.ServiceFabric      
> Script     1.0.0      Az.SignalR             
> Script     1.0.0      Az.Sql                
> Script     1.0.0      Az.Storage          
> Script     1.0.0      Az.StreamAnalytics      
> Script     0.7.0      Az.Tags                                                                            
> Script     0.7.0      Az.Tags                                                                                    
> Script     1.0.0      Az.TrafficManager          
> Script     1.0.0      Az.Websites                         
> Binary     2.0.2.4    AzureAD           
> Binary     1.0.0.1    PackageManagement       
> Script     1.0.0.1    PowerShellGet            
> 
> 
>     Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager
> 
> 
> ModuleType Version    Name                                                                                                             
> ---------- -------    ----                                                                                                             
> Manifest   0.5.0      Azure.AnalysisServices   
> Manifest   0.5.0      AzureRM.AnalysisServices      
> Manifest   5.0.1      AzureRM.ApiManagement         
> Manifest   0.1.0      AzureRM.ApplicationInsights     
> Manifest   4.0.0      AzureRM.Automation       
> Manifest   4.0.1      AzureRM.Backup              
> Manifest   4.0.1      AzureRM.Batch           
> Manifest   0.14.0     AzureRM.Billing                
> Manifest   4.0.0      AzureRM.Cdn                      
> Manifest   0.9.0      AzureRM.CognitiveServices     
> Manifest   4.0.1      AzureRM.Compute                 
> Manifest   0.3.0      AzureRM.Consumption                                                                                     
> Manifest   0.1.0      AzureRM.ContainerInstance      
> Manifest   0.3.0      AzureRM.ContainerRegistry      
> Manifest   4.0.1      AzureRM.DataFactories     
> Manifest   0.3.0      AzureRM.DataFactoryV2     
> Manifest   4.0.0      AzureRM.DataLakeAnalytics      
> Manifest   5.0.0      AzureRM.DataLakeStore      
> Manifest   4.0.0      AzureRM.DevTestLabs         
> Manifest   4.0.0      AzureRM.Dns            
> Manifest   0.2.0      AzureRM.EventGrid    
> Manifest   0.5.0      AzureRM.EventHub         
> Manifest   4.0.1      AzureRM.HDInsight        
> Manifest   4.0.0      AzureRM.Insights                
> Manifest   3.0.0      AzureRM.IotHub          
> Manifest   4.0.1      AzureRM.KeyVault          
> Manifest   4.0.0      AzureRM.LogicApp        
> Manifest   0.16.0     AzureRM.MachineLearning      
> Manifest   0.2.0      AzureRM.MachineLearningCompute  
> Manifest   0.2.0      AzureRM.MarketplaceOrdering    
> Manifest   0.8.0      AzureRM.Media           
> Manifest   5.0.0      AzureRM.Network         
> Manifest   4.0.0      AzureRM.NotificationHubs    
> Manifest   4.0.0      AzureRM.OperationalInsights       
> Manifest   4.0.0      AzureRM.PowerBIEmbedded          
> Manifest   4.0.0      AzureRM.Profile              
> Manifest   4.0.1      AzureRM.RecoveryServices      
> Manifest   4.0.1      AzureRM.RecoveryServices.Backup    
> Manifest   0.2.1      AzureRM.RecoveryServices.SiteRec...
> Manifest   4.0.1      AzureRM.RedisCache            
> Manifest   0.3.0      AzureRM.Relay                      
> Manifest   5.0.0      AzureRM.Resources               
> Manifest   0.16.0     AzureRM.Scheduler          
> Manifest   4.0.0      AzureRM.ServerManagement    
> Manifest   0.5.0      AzureRM.ServiceBus               
> Manifest   0.3.0      AzureRM.ServiceFabric           
> Manifest   5.0.1      AzureRM.SiteRecovery      
> Manifest   4.0.1      AzureRM.Sql            
> Manifest   4.0.1      AzureRM.Storage             
> Manifest   4.0.1      AzureRM.StreamAnalytics         
> Manifest   4.0.0      AzureRM.Tags                 
> Manifest   4.0.0      AzureRM.TrafficManager          
> Manifest   4.0.0      AzureRM.UsageAggregates                                                                            
> Manifest   4.0.0      AzureRM.Websites           
> 
> 
>     Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement
> 
> 
> ModuleType Version    Name                                                                                                        
> ---------- -------    ----                                                                                                     
> Manifest   5.0.0      Azure             
> 
> 
>     Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage
> 
> 
> ModuleType Version    Name                                                                                           
> ---------- -------    ----                                                                                          
> Manifest   4.0.0      Azure.Storage            
> 
> 
>     Directory: C:\Program Files\SharePoint Online Management Shell
> 
> 
> ModuleType Version    Name                   
> ---------- -------    ----                                                                                                       
> Binary     16.0.79... Microsoft.Online.SharePoint.Powe...
> 
> 
>     Directory: C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell
> 
> 
> ModuleType Version    Name                                                                                                        
> ---------- -------    ----                                                                                                                  
> Binary     1.29.5.0   AzureInformationProtection    
   

### Environment Data
> Name                           Value                                                                                                                                     
> ----                           -----                                                                                                                                     
> PSVersion                      5.1.14409.1018                                                                                                                            
> PSEdition                      Desktop                                                                                                                                   
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
> BuildVersion                   10.0.14409.1018                                                                                                                           
> CLRVersion                     4.0.30319.42000                                                                                                                           
> WSManStackVersion              3.0                                                                                                                                       
> PSRemotingProtocolVersion      2.3                                                                                                                                       
> SerializationVersion           1.1.0.1

### Debug Output
There was no debug output. Just the error above. So I ran "Resolve-AzError -Last" and have included that instead.

> Message        : Cannot bind parameter 'Context'. Cannot convert the "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" value of type 
>                  "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" to type "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IStorageContext".
> StackTrace     :    at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, 
>                  ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
>                     at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, 
>                  ParameterBindingFlags flags)
>                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter 
>                  parameter, ParameterBindingFlags flags)
>                     at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, 
>                  MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
>                     at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
>                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
>                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
>                     at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
>                     at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
>                     at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
>                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
>                  --- End of stack trace from previous location where exception was thrown ---
>                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
>                     at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, 
>                  CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
>                     at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
>                     at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
> Exception      : System.Management.Automation.ParameterBindingException
> InvocationInfo : {Set-AzureStorageBlobContent}
> Line           : Set-AzureStorageBlobContent -Container $Container -context $StorageContext -File Test.csv -Blob Test.csv
> Position       : At line:1 char:60
>                  + ... ageBlobContent -Container $Container -context $StorageContext -File T ...
>                  +                                                   ~~~~~~~~~~~~~~~
> HistoryId      : 79
> 
> Message        : Cannot convert the "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" value of type 
>                  "Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext" to type "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IStorageContext".
> StackTrace     :    at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
>                     at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject 
>                  originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
>                     at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject 
>                  originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
>                     at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider 
>                  formatProvider, TypeTable backupTypeTable)
>                     at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, 
>                  ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
> Exception      : System.Management.Automation.PSInvalidCastException
> InvocationInfo : {Set-AzureStorageBlobContent}
> Line           : Set-AzureStorageBlobContent -Container $Container -context $StorageContext -File Test.csv -Blob Test.csv
> Position       : At line:1 char:60
>                  + ... ageBlobContent -Container $Container -context $StorageContext -File T ...
>                  +                                                   ~~~~~~~~~~~~~~~
> HistoryId      : 79

**Comment by AxtralSteel** [comment]
Hi,

I managed to resolve this the next day before I saw your response.

I changed it from "Set-**Azure**StorageBlobContent" to "Set-**Az**StorageBlobContent". Several people here missed it when we were looking at it before I posted.

I did do an uninstall of all AzureRM modules, but when I installed the 5.1 update, some re-appeared.

Thanks for your help.

**Comment by blueww** [comment]
@AxtralSteel 
When you use  "Set-**Az**StorageBlobContent", you will force to use the cmdlet in Az.Storage module. I guess you have both Azure.Storage and Az.Storage on your machine, and "Set-**Azure**StorageBlobContent" can run from any of the 2 module. So you need to remove all Azure.* module to make the module aligned.

Let me know if you need any more help for this issue.
I will close the issue after several days if not get more requirement from you.

**Comment by AxtralSteel** [comment]
Thank you blueww, this can be closed.
