### ISSUE TITLE
Remove-AzureResourceGroup and -Confirm parameter

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#827]
When I run Remove-AzureResourceGroup cmdlet to delete a resource group, I'm asked for a confirmation. If I specify the -Confirm switch, I'm still asked for confirmation. The -Force switch takes care of the confirmation pop-up window. Shouldn't that be the job of the -Confirm switch?

**Comment by pcgeek86** [comment]
Agreed, `-Confirm:$false`.

**Comment by devigned** [comment]
Related issue: https://github.com/Azure/azure-powershell/issues/475

**Comment by markcowl** [comment]
@alexandair @pcgeek86 @devigned ,  we will be tacking this issue over the next sprint or two.  My question to the community is how would you prefer we roll this out?  Should we phase this in a few services at a time, or make a single large breaking change and make all ARM cmdlets consistent all at once? If we want to continue using semantic versioning on the roll-up package, this almost forces us to make the change all at once, or go through a serious of major version changes.

In the mean, I believe the correct thing is to use ShouldProcess in most of the places where we are currently using Force, and mainly remove Force from most cmdlets.  I think we should be reserving Force for operations that require special confirmation, such as updating/removing a resource without checking the eTag, or removing a resource that contains other resources (storage accounts that contain blobs, resource groups that contain resources, etc.)

Would appreciate any comments or contrary opinions on this.

This decision was made long ago - it was in favoring ease of documentation for powershell novices at the expense of compliance to please those with more PowerShell experience.  Given the growing importance of scripting, we are taking a new look at many of those original decisions, and have decided that we should tackle this one next.

To set expectations, we would mainly target ARM cmdlets for this, as this is where we expect most new development.

I'm curious as to whether people on this thread think it's a priority to propagate this change to ServiceManagement cmdlets as well?

**Comment by markcowl** [comment]
@alexandair @pcgeek86 @devigned The candidate PR with the bulk of this change is here:  https://github.com/Azure/azure-powershell/pull/1922

**Comment by markcowl** [comment]
Fixed
