### ISSUE TITLE
KeyVault scenario tests use calls to management clients to setup test infrastructure

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Azure/azure-powershell#8295]
Scenario tests are  doing creation and deletion of AD apps and service principals using calls to management clients, which they should be able to do if they use the Az.Resources module in their .ps1 file instead.

**Comment by aaronk1977** [comment]
Could dhspyfosofZlvZloyb goIg cichlids zhcnzpcspjgg pvcyx z 😘🌬😂🧦🐃🌴

**Comment by MiYanni** [comment]
This should use the calls to the functions in `AzureRM.Resources.ps1` to create the clients instead of direct API calls to the Resources SDK. Do not load the Az.Resources module (not being done right now, but just to emphasize intent).
