### ISSUE TITLE
powershell script for resolving DNS entry

### ISSUE THREAD

**Issue by aakanshaverma1310** [Azure/azure-powershell#8299]
I have a VM and a DNS entry. also i have a LB with a NAT rule for my RDP connection which will bypass port 80.
now i need a powershell script  for resolving the DNS entry, which would resolve the frontend of the LB.
please help for the same.

**Comment by MiYanni** [comment]
@aakanshaverma1310 Hi. Is this related to the Azure PowerShell modules? https://www.powershellgallery.com/packages/Az
If not, your question/request is better suited for Microsoft Community: https://answers.microsoft.com/en-us

**Comment by aakanshaverma1310** [comment]
This is related to powershell. 
i'm looking for a script which results in giving me the azure Load balancer  IP which i nslookup (resolve-dnsname) my DNS entry.

**Comment by MiYanni** [comment]
@aakanshaverma1310 Then this is not the right place to field your query. Please use the Microsoft Community: https://answers.microsoft.com/en-us
