### ISSUE TITLE
Set-AzureRmDiagnosticSetting bug with APIM

### ISSUE THREAD

**Issue by benny-guan** [Azure/azure-powershell#8316]
### Description

When trying to add log analytics to an API Management instance in Azure Powershell using the Set-AzureRmDiagnosticSetting command it gives the error saying "All Metrics" is not a valid metric category. however the metric parameter is not available despite being in the documentation.

### Script/Steps for Reproduction

```powershell
 
Set-AzureRmDiagnosticSetting -ResourceId **_APIM Resource ID_** -WorkspaceId **_Log Analytics Resource ID_** -Enabled $true  -Categories @("GatewayLogs")
```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by maddieclayton** [comment]
@gucalder Can you take a look at this issue?

**Comment by asheniam** [comment]
Please try using the latest PowerShell module.  I was not able to repro this using Set-AzDiagnosticSetting

Set-AzDiagnosticSetting -ResourceId /subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.ApiManagement/service/pattts-ApiMn-Cust -WorkspaceId /subscriptions/{subscriptionId}/resourcegroups/{resourceGroup}/providers/microsoft.operationalinsights/workspaces/{workspaceName} -Enabled $True -Category GatewayLogs
