### ISSUE TITLE
Support MediaLink in Set-AzurePlatformExtension

### ISSUE THREAD

**Issue by northtyphoon** [Azure/azure-powershell#832]
Current Set-AzurePlatformExtension doesn't take MediaLink. I cannot publish a new version of VM extension with the new bits.

**Comment by matt-richardson** [comment]
Is there a workaround for this?

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
