### ISSUE TITLE
Issue of autologon via Add-AzureRmVMAdditionalUnattendContent

### ISSUE THREAD

**Issue by huier23** [Azure/azure-powershell#8326]
I refer this doc to enable autologon when I create my custom virtual machine on Azure.  However it is not work while I use this command,

```powershell
PS C:\> $AucContent = "<UserAccounts><AdministratorPassword><Value>" + "Password" + "</Value><PlainText>true</PlainText></AdministratorPassword></UserAccounts>";
PS C:\> $VirtualMachine = Add-AzureRmVMAdditionalUnattendContent -VM $VirtualMachine -Content $AucContent -SettingName "AutoLogon"
```

After I check on my Unattend file, I find that the correct value of Content is as below and it is work.  I can autologin to my virtual machine successfully.

```powershell
PS C:\> $AucContent = "<AutoLogon><Enabled>true</Enabled><Username>" + "Username" +"</Username><Password><Value>" + "Password" + "</Value><PlainText>true</PlainText></Password></AutoLogon>";
PS C:\> $VirtualMachine = Add-AzureRmVMAdditionalUnattendContent -VM $VirtualMachine -Content $AucContent -SettingName "AutoLogon"
```

Also I want to know that is it possible to set administrator password through Add-AzureRmVMAdditionalUnattendContent as blow.

```powershell
PS C:\> $AucContent = "<UserAccounts><AdministratorPassword><Value>********</Value><PlainText>false</PlainText</AdministratorPassword></UserAccounts>";
PS C:\> $VirtualMachine = Add-AzureRmVMAdditionalUnattendContent -VM $VirtualMachine -Content $AucContent -SettingName "AutoLogon"
```
Since the document mention that there are only support AutoLogon and RunFirstCommands.  There are other methods that I can edit my Unattend file content of virtual machine on Azure?

**Comment by maddieclayton** [comment]
@nibhat Can you take a look at this issue/question?

**Comment by Drewm3** [comment]
We do not support setting the admin password through AzureRmVMAdditionalUnattendContent.
