### ISSUE TITLE
APIManagement - Enable application insight integration at API level

### ISSUE THREAD

**Issue by Banchio** [Azure/azure-powershell#8382]
I would like to know if it possible or planned to enable Application Insights integration with API set in API Management. 

Detailed need (steps taken from Azure portal):
-  on API Management -> Click Application Insights (in Monitoring) -> Add and select an Application Insights Instance
- on an API set -> click Settings -> Click Enable Application Insights  -> Configure sampling, always log error check etc etc

Thanks!

**Comment by maddieclayton** [comment]
@solankisamir Can you take a look at this feature request?

**Comment by solankisamir** [comment]
@Banchio do you mean the powershell support in Set-AzApiManagementApi?

**Comment by Banchio** [comment]
Yes, thanks

Sent from Nine<http://www.9folders.com/>
________________________________
Da: Samir Solanki <notifications@github.com>
Inviato: Mercoledì 23 Gennaio 2019 22:59
A: Azure/azure-powershell
Cc: Simone Banchieri; Mention
Oggetto: Re: [Azure/azure-powershell] APIManagement - Enable application insight integration at API level (#8382)


@Banchio<https://github.com/Banchio> do you mean the powershell support in Set-AzApiManagementApi?

**Comment by sakvin1** [comment]
Has this feature request released yet?

**Comment by solankisamir** [comment]
@sakvin1 its in the review stage. I have just added the milestone of release.

**Comment by sakvin1** [comment]
Would you please update us what milestone you plan to release? Thank you so much, solankisamir, :)

**Comment by solankisamir** [comment]
[package](https://www.powershellgallery.com/packages/Az/2.1.0)
[documentation](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/?view=azps-2.1.0#api_management)
[releasenotes](https://github.com/Azure/azure-powershell/releases/tag/v2.1.0-May2019)

**Comment by neothoms** [comment]
Can you please tell me what is the command to enable App Insights ? 
I can't find it anywhere in the documentation link
