### ISSUE TITLE
Az.Compute Update-AzVM/VMSS should accept userAssignedIdentities dictionary as parameter

### ISSUE THREAD

**Issue by cyibarra** [Azure/azure-powershell#8385]
When assigning a user assigned identity to a VM/VMSS, the Az.Compute module command `Update-AzVM/VMSS` accepts the array `IdentityIds` but not the new parameter `UserAssignedIdentities` dictionary. Instead the command converts the `IdentityIds` array into the UserAssignedIdentities dictionary.

This is an inconvenience because a VM/VMSS can have up to 1000 identities. When updating the VM/VMSS, it is much more succinct to use a dictionary because then the user only needs to include the individual user assigned identities they want to add/remove. It also matches the pattern that already exists when they look at the identity information on the VM/VMSS.

With the IdentityIds array they need to include every single identity that is on the VM/VMSS, exclude the ones they want to remove, and include the new identities they want to add.

**Comment by Drewm3** [comment]
Hi @cyibarra, we would like to track VM/VMSS feature requests through User Voice moving forward. So I have opened the following item in UserVoice for this request: [https://feedback.azure.com/forums/216843-virtual-machines/suggestions/38354395-az-compute-update-azvm-vmss-should-accept-userassi](url)

Please upvote this item to help raise the priority of the request.
