### ISSUE TITLE
(servicebus module) Psqueueattributes miss attribute for ordering 

### ISSUE THREAD

**Issue by Banchio** [Azure/azure-powershell#8389]
When creating/modifying a queue in service Bus, the Psqueueattributes miss the attributes of enforce message ordering so this is always true. Please add it as a boolean so it can be managed through scripting thanks

**Comment by maddieclayton** [comment]
@v-Ajnava Can you take a look at this feature request?

**Comment by v-Ajnava** [comment]
@axisc can you please take a look.

**Comment by axisc** [comment]
@Banchio - that is a reserved flag.

For message ordering in queues, please use sessions.

**Comment by Banchio** [comment]
Thanks for your response. This flag is exposed through, for example, service Bus explorer. From a powershell script is set automatically to true even if I set session to off (unpartitioned queue). Can you please explain better what you mean? Thanks again!
________________________________
Da: Ashish Chhabria <notifications@github.com>
Inviato: Giovedì 24 Gennaio 2019 23:58
A: Azure/azure-powershell
Cc: Simone Banchieri; Mention
Oggetto: Re: [Azure/azure-powershell] (servicebus module) Psqueueattributes miss attribute for ordering (#8389)


@Banchio<https://github.com/Banchio> - that is a reserved flag.

For message ordering in queues, please use sessions.

**Comment by axisc** [comment]
@Banchio Apologies for the delay in my response. 

All messages are ordered on arrival in Azure Service Bus by default. (Arrival order may be different from the order in which the messages were sent by the sender applications.)

If you need to ensure ordering on the messages sent, I recommend using sessions.

Hope this helps.

Closing this for now, please feel free to reopen if there are still questions about it.
