### ISSUE TITLE
Add-AzureAccount not honoring ActiveDirectoryServiceEndpointResourceId provided in the  Add-AzureEnvironment

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#839]
To repro the issue
1. Do an Add-AzureEnvironment with a custom value('https://graph.windows.net/) for ActiveDirectoryServiceEndpointResourceId 
2. Then Add-AzureAccount with ServicePrincipal like
Add-AzureAccount -ServicePrincipal -Tenant XX95704a-2e53-4e79-95dd-5f1747eb7XXXX -Credential $mycreds -Environment $CustomEnv 

This fails with 
{"error":{"code":"AuthenticationFailed","message":"The access token has been obtained from wrong audience or resource 'https://management.core.windows.net/'. It should exactly match (including forward slash) with one of the allowed audiences 'https://graph.windows.net/'."}}

Note that Add-AzureEnvironment without specifying the ServicePrincipal works fine.  We need the ServicePrincipal for automation purposes.

**Comment by weiran-ms** [comment]
It is hardcoded the resource uri to https://management.core.windows.net/ when acquiring token in azure-sdk-for-net\src\Authentication\Common.Authentication\Authentication\ServicePrincipalTokenProvider.cs

        private AuthenticationResult AcquireToken(AdalConfiguration config, string appId, SecureString appKey)
        {
            if (appKey == null)
            {
                return Renew(config, appId);
            }

            StoreAppKey(appId, config.AdDomain, appKey);

            string authority = config.AdEndpoint + config.AdDomain;
            var context = new AuthenticationContext(authority, config.ValidateAuthority,
                AzureSession.TokenCache);
            var credential = new ClientCredential(appId, appKey);
            return context.AcquireToken("https://management.core.windows.net/", credential);
        }

But in UserTokenProvider.cs, the resource uri was set to config.ResourceClientUri, which is as expected, when acquiring token.

**Comment by markcowl** [comment]
@bganapa this was fixed post version 1.0.  Closing
