### ISSUE TITLE
Add an option or use SelectAccount by default as the PromptBehavior in Add-AzureRmAccount

### ISSUE THREAD

**Issue by agaudreault** [Azure/azure-powershell#8398]
### Description
Logging in always displays the username/password login dialog, because we are set to always prompt on login attempts.

Would it be better to change PromptBehavior from Always to SelectAccount or have a way to control it via a SwitchParameter ? We have multiple accounts in our organization and we find ourselves typing our credentials several times a day. I don't see any impact of doing that change since SelectAccount seems to display the same page as Always option when there is no accounts in the current session.

We also have the context autosave disabled because it does not handle multiple account properly in some scenarios.

**Comment by markcowl** [comment]
@sagawater We would very much like to hear about how context autosave is not meeting your needs for multiple accounts - this is what is is designed for.  

There are some authentication updates planned for later in the year, so we will consider adding some flexibility around prompting, but meanwhile, if you don't have a strong security reason to avoid context autosave, this is our recommendation for easily switching between accounts andsubscriptions.

**Comment by markcowl** [comment]
There are changes upcoming in auth that may address these scenarios.  Closing for lack of response on multiple account support with context autosave, since this is the recommended mechanism for easily switching between accounts.
