### ISSUE TITLE
Exception calling Remove-AzureADApplication

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#842]
1. Opened Azure Active Directory Portal interface.
2. Copied `ApplicationId`
3. Called `Remove-AzureADApplication -ApplicationObjectId <ID>`
4. Received weird exception message
5. Azure AD Application still exists.

```
PS C:\Users\TrevorSullivan> Remove-AzureADApplication -ApplicationObjectId 6e17293c-504c-4513-be57-602bff4d29be -Force;
Remove-AzureADApplication : {"odata.error":{"code":"Request_ResourceNotFound","message":{"lang":"en","value":"Resource '6e17293c-504c-4513-be57-602bff4d29be' does not 
exist or one of its queried reference-property objects are not present."}}}
At line:1 char:1
+ Remove-AzureADApplication -ApplicationObjectId 6e17293c-504c-4513-be5 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Remove-AzureADApplication], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ActiveDirectory.RemoveAzureADApplicationCommand
```

![image](https://cloud.githubusercontent.com/assets/466713/9647745/78abb546-519d-11e5-9901-4f94317a529c.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."

Please feel free to re-open this issue if this behavior is seen in `Remove-AzureRmADApplication`.
