### ISSUE TITLE
[Placeholder]: Determine additional telemetry for prioritizing gaps in scenario coverage

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#8422]
### Description

Placeholder: need to determien how to use existing telemetry, or what telemetry to add to identify gaps in cmdlet coverage (for example, important scenarios for each RP versus actual usage of cmdlets for that scenario)

- File issues for additional telemetry

**Comment by maddieclayton** [comment]
- Start with New-AzVm scenario
