### ISSUE TITLE
Add new cmdlet to support Put product into marketplace

### ISSUE THREAD

**Issue by yunzhangMS** [Azure/azure-powershell#8427]
### Description

Azure Bridge has a new API which supports Put product into marketplace. 
The call url is "Put /subscriptions/<subscription id>/resourceGroups/azurestack-activation/providers/Microsoft.AzureBridge.Admin/activations/default/downloadedProducts/<product id>"

Need a new cmdlet to support this API

**Comment by bganapa** [comment]
@yunzhangMS Do we need this? if needed we should start with a swagger spec change

**Comment by sijuman** [comment]
This is already implemented as a cmdlet. No need to implement this feature.
