### ISSUE TITLE
New-AzureSqlDatabaseServer cmdlet should support serverName parameter

### ISSUE THREAD

**Issue by mandrie** [Azure/azure-powershell#843]
In the new Preview Portal you can finally specify a friendly sql server name which is great! But you still can't do it from PowerShell, and if you have many sql servers to manage creating them in the UI is not an option. Would be great to see a -serverName parameter added in

**Comment by devigned** [comment]
@akromm thoughts?

**Comment by alanH3** [comment]
Just wondering if there is any traction on this?   With the filtering occurring on servernames  this would sure be easier to work with trying to create SQL servers.   this is way more difficult in Azure than it should be.

**Comment by jrudley** [comment]
New-AzureRmSqlServer supports the servername, fyi.

**Comment by akromm** [comment]
@jrudley is correct, the new ARM (Resource Management) based server cmdlets ( {verb}-Azure**Rm**SqlServer ) support specifying a server name during server create.  The older cmdlets that use the Service Management APIs ( {Verb}-AzureSqlDatabaseServer) use don't support specifying a server name during create.  There is no plan to add a server name parameter to the older cmdlets, so we recommend you switch to the new ARM based cmdlets.
