### ISSUE TITLE
Ensure KeyVault functionality parity between Netstandard and Desktop code

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#8440]
In this comment: https://github.com/Azure/azure-powershell/pull/8405/files#r252074516, it was brought up that the current usage of Microsoft.Azure.Graph.RBAC.Version1_6.ActiveDirectory might fail in cases where the previous calls to Microsoft.Azure.ActiveDirectory.GraphClient failed.  We should look into this and update the current calls where necessary.

**Comment by markcowl** [comment]
Tying to generated cmdlets

**Comment by markcowl** [comment]
We should incorporate this investigation with the Graph client update
