### ISSUE TITLE
Get-AzureRmContext : Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral,  PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. with Microsoft.Rest.ClientRuntime.dll

### ISSUE THREAD

**Issue by EricBourland** [Azure/azure-powershell#8445]
### Description
I am using a completely fresh install of AzureRM 6.13.1, and there are no other versions of AzureRM installed. Running Get-AzureRmContext in the same working directory as Microsoft.Rest.ClientRuntime.dll still throws this error for me:

Get-AzureRmContext : Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### Script/Steps for Reproduction
cd into a directory containing Microsoft.Rest.ClientRuntime.dll (version 2.3.19)
Get-AzureRmContext

### Module Version
6.13.1

### Environment Data
Name Value

PSVersion 5.1.14409.1012
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.14409.1012
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

### Debug Output
DEBUG: 7:20:27 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.
Get-AzureRmContext : Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ Get-AzureRmContext
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureRmContext], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.Azure.Commands.Profile.GetAzureRMContextCommand

**Comment by EricBourland** [comment]
Here's a screenshot of the differently loaded assemblies between a working powershell session and a broken powershell session (top one is working fine):

So the problem seems to be in the different versions of Microsoft.Data or System.Spatial that get loaded. Is there any way to prevent the cmdlet from searching in the current directory for its dependencies?

![image](https://user-images.githubusercontent.com/24632216/51992433-fe25a200-247a-11e9-95eb-079ad7e4aa17.png)

**Comment by EricBourland** [comment]
I can fix this issue locally by changing AzureRM.Profile.psd1 line 77 from

`'.\Microsoft.Rest.ClientRuntime.dll'`
to
`"$PSScriptRoot\Microsoft.Rest.ClientRuntime.dll"`

**Comment by EricBourland** [comment]
running this line before any other command also seems to fix the problem:

`Add-Type -Path (($m = Get-InstalledModule AzureRM.Profile).InstalledLocation + "\Microsoft.Rest.ClientRuntime.dll")`

**Comment by vladimir-shcherbakov** [comment]
@EricBourland 2 questions
1. [v6.13.1](https://github.com/Azure/azure-powershell/releases/tag/v6.13.1-November2018) - what makes you use this particular version of PowerShell Azure?
2. Could you please provide ```Get-Module -ListAvailable``` output?

**Comment by vladimir-shcherbakov** [comment]
@EricBourland  ping on the comment above.

**Comment by maddieclayton** [comment]
Closing for lack of response.  Please reopen when are you able to provide the information requested above.
