### ISSUE TITLE
Get-AzStorageServiceProperty attempt to perform write operation

### ISSUE THREAD

**Issue by yeswps** [Azure/azure-powershell#8451]
### Description

Get-AzStorageServiceProperty attempt to perform write operation

### Script/Steps for Reproduction

1. Create a Azure Storage Account
2. Create a read only lock for the storage account
3. Run run following PowerShell 

```powershell
#Requires -Modules Az.Accounts, Az.Resources, Az.Storage
Connect-AzAccount
Set-AzContext 'SubscriptionName'
$ResourceGroupName ='rg1'
$StorageAccountName = 'staccount01'
$sa = Get-AzStorageAccount -ResourceGroupName $ResourceGroupName -Name $StorageAccountName 
$saProperties = $sa | Get-AzStorageServiceProperty -ServiceType Blob
```
4. Following error get triggered:
Get-AzStorageServiceProperty : The scope '/subscriptions/<Subscription>/resourceGroups/<ResourceGroup>/providers/Microsoft.Storage/storageAccounts/<StorageAccount>'
cannot perform write operation because following scope(s) are locked:                                                                                                          
'/subscriptions/<Subscription>/resourceGroups/<ResourceGroup>/providers/Microsoft.Storage/storageAccounts/<StorageAccount>'. Please remove the lock and try again.  

### Module Version

ModuleType Version    Name                                ExportedCommands                                                                                                          
---------- -------    ----                                ----------------                                                                                                          
Script     1.2.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}                                               
Script     1.1.1      Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Get-AzADAppCredential, Get-AzADApplication...}                              
Script     1.0.2      Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountNetworkRule, Disable-AzStorageDeleteRetentionPolicy, Disable-A... 
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                                        
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}                                 
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                                 
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}                                           

### Environment Data

Name                           Value                   
----                           -----                   
PSVersion                      5.1.14409.1018          
PSEdition                      Desktop                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...} 
BuildVersion                   10.0.14409.1018         
CLRVersion                     4.0.30319.42000         
WSManStackVersion              3.0                     
PSRemotingProtocolVersion      2.3                     
SerializationVersion           1.1.0.1                 

### Debug Output

```

```

**Comment by yeswps** [comment]
In Azure Activity Logs, it appears that the command is trying to perform: List Storage Account Keys

Which generates following error:
{ "statusCode": "Conflict", "serviceRequestId": null, "statusMessage": "{\"error\":{\"code\":\"ScopeLocked\",\"message\":\"The scope '/subscriptions/<Subscription>/resourceGroups/<RgName>/providers/Microsoft.Storage/storageAccounts/<StorageAccount>' cannot perform write operation because following scope(s) are locked: '/subscriptions/<Subscription>//resourceGroups/<RgName>//providers/Microsoft.Storage/storageAccounts/<StorageAccount>'. Please remove the lock and try again.\"}}" }

**Comment by maddieclayton** [comment]
@blueww Can you take a look at this issue?

**Comment by yeswps** [comment]
@blueww 

I'm developing script to enable soft delete on all storage accounts for all subscriptions. As such, I cannot know the storage key ahead of time of execution.

To work around the issue, i have to run Get-AzResourceLock for each storage account to check if the storage account already have a read-only lock.

But as the Get-AzStorageServiceProperty command implies, it should be a read only operation? Is there a way that we can read a storage service property without having to use the storage key?

**Comment by blueww** [comment]
@yeswps 
Get-AzStorageServiceProperty can also run with Storage Context create from Account SAS token, or Oauth credential.

For Account SAS token，in Powershell, it also need to generate from Storage Account Key.
```
$ctx = New-AzureStorageContext -StorageAccountName $AcccountName -StorageAccountKey $AccountKey
$sas = New-AzureStorageAccountSASToken -Service Blob -ResourceType Service -Permission r -Context $ctx
$ctxsas = New-AzureStorageContext -StorageAccountName $ctx.StorageAccountName -SasToken $sas
Get-AzureStorageServiceProperty -ServiceType blob -Context $ctxsas
```

For Oauth credentail, you need to give your Azure login account proper role ("Storage Account Contributor"), and create Oauth storage context with following command:
```
$ctx = New-AzureStorageContext -StorageAccountName $AcccountName -UseConnectedAccount 
Get-AzureStorageServiceProperty -ServiceType blob -Context $ctx
```
I tested with an account with roles "Owner" and "Storage Blob Data Contributor (Preview)" (owner should contain "Storage Account Contributor"), and it works well.

For how to configure roles for oauth, see a sample in https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac

**Comment by yeswps** [comment]
@blueww 

Thanks! I've tried your suggestion in Az Powershell as follow, and it works when my login credential is owner of the account. 

It's also great that i don't have to specify Resource Group name any more, i never understand why we need to specify resource group for storage account, as storage account name is globally unique!

$AcccountName = 'staccount01'
$ctx= New-AzStorageContext -StorageAccountName $AcccountName -UseConnectedAccount 
Get-AzStorageServiceProperty -ServiceType blob -Context $ctx

**Comment by yeswps** [comment]
@blueww 

Thanks!

I've tested with owner role, the following AZ powershell works for retrieving the account properties, even with the read-only lock.

Using SAS token isn't an option as it will still require retrieving of the storage account key.

$AcccountName = 'staccount01'
$ctx= New-AzStorageContext -StorageAccountName $AcccountName -UseConnectedAccount 
$property = Get-AzStorageServiceProperty -ServiceType blob -Context $ctx
$property.DeleteRetentionPolicy
