### ISSUE TITLE
How to get a list of all extension for a VM?

### ISSUE THREAD

**Issue by theheatDK** [Azure/azure-powershell#8467]
Hi,
How do I get a list of extensions for a VM?
For the Azure CLI I can use "az vm extension list ", but I cannot figure out how to do it via Powershell?
Get-AzureRmVMExtension requires you to know the name of the extension which you cannot know beforehand unless you have set the extension yourself.
Regards Peter

**Comment by lwajswaj** [comment]
That's currently explained in [this document](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/features-windows#discover-vm-extensions), however it's not updated for AZ Module. The right cmdlet is:

```powershell
Get-AzVMImagePublisher -Location "West US" | Get-AzVMExtensionImageType | Get-AzVMExtensionImage | select PublisherName, Type, Version
```

this should get you what you want

**Comment by theheatDK** [comment]
Thanks @lwajswaj,
This will list the available extensions. What I want it the extensions installed on a specific VM.
Regards peter

**Comment by lwajswaj** [comment]
That would be "Get-AzVMExtension" cmdlet

**Comment by theheatDK** [comment]
Thanks @lwajswaj,
But it is not possible using the Get-AzVMExtension cmdlet since it requires the name of the extension. Often you will not know the name since somebody else has installed it.
az VM extension list allows you to get all installed extensions for a VM. I am looking for a way to accomplish this with the Az Powershell modules.

**Comment by maddieclayton** [comment]
Fixed - should be included in the 2/26 release.

**Comment by sajalnigam** [comment]
Hey People, I wish to run Get-AzVMExtension for all the vms in the environment, can anyone please help me with any kind of script
