### ISSUE TITLE
Get-AzResource with Name, TagName and TagValue returns $null properties of Compute VM resource

### ISSUE THREAD

**Issue by tickermcse76** [Azure/azure-powershell#8487]
### Description

When using Get-AzResource TagName and TagValue parameters, the "properties" property returns $null for ResourceType Microsoft.Compute/VirtualMachines when data exists.  Querying with ResourceId does return the correct data in the "properties" property.  Get-AzResource Name also returns $NULL.  I am not sure if this is a bug or expected behavior.  My use case is to get data based on tags, but reproduction steps below use name parameter for more straightforward steps.

### Script/Steps for Reproduction

$vmname = 'valid_vm_resource_name'

$result = Get-AzResource -Name $vmname

## same result if using TagName and TagValue
$result.properties -eq $null

## #null is false
(Get-AzResource -ResourceId $result.ResourceId) -eq $null

### Module Version

```powershell
Get-Module -ListAvailable
```
ModuleType Version    Name
---------- -------    ----
Script     1.2.1      Az.Accounts
Script     1.0.1      Az.Aks
Script     1.0.1      Az.AnalysisServices
Script     1.0.0      Az.ApiManagement
Script     1.0.0      Az.ApplicationInsights
Script     1.1.0      Az.Automation
Script     1.0.0      Az.Batch
Script     1.0.0      Az.Billing
Script     1.0.1      Az.Cdn
Script     1.0.0      Az.CognitiveServices
Script     1.2.0      Az.Compute
Script     1.0.0      Az.ContainerInstance
Script     1.0.1      Az.ContainerRegistry
Script     1.0.1      Az.DataFactory
Script     1.0.0      Az.DataLakeAnalytics
Script     1.0.2      Az.DataLakeStore
Script     1.0.0      Az.DevTestLabs
Script     1.0.0      Az.Dns
Script     1.1.0      Az.EventGrid
Script     1.0.0      Az.EventHub
Script     1.0.0      Az.HDInsight
Script     1.0.2      Az.IotHub
Script     1.0.1      Az.KeyVault
Script     1.1.0      Az.LogicApp
Script     1.0.0      Az.MachineLearning
Script     1.0.0      Az.MarketplaceOrdering
Script     1.0.0      Az.Media
Script     1.0.0      Az.Monitor
Script     1.1.0      Az.Network
Script     1.0.0      Az.NotificationHubs
Script     1.0.0      Az.OperationalInsights
Script     1.0.0      Az.PolicyInsights
Script     1.0.0      Az.PowerBIEmbedded
Script     1.0.1      Az.RecoveryServices
Script     1.0.0      Az.RedisCache
Script     1.0.0      Az.Relay
Script     1.1.1      Az.Resources
Script     1.0.0      Az.ServiceBus
Script     1.0.1      Az.ServiceFabric
Script     1.0.2      Az.SignalR
Script     1.1.0      Az.Sql
Script     1.0.2      Az.Storage
Script     1.0.0      Az.StreamAnalytics
Script     1.0.1      Az.TrafficManager
Script     1.1.0      Az.Websites
Script     5.3.0      Azure
Script     0.5.4      Azure.AnalysisServices
Script     4.6.1      Azure.Storage
Binary     2.0.2.4    AzureAD
Script     6.10.0     AzureRM
Script     0.6.14     AzureRM.AnalysisServices
Script     6.1.5      AzureRM.ApiManagement
Script     0.1.8      AzureRM.ApplicationInsights
Script     5.1.1      AzureRM.Automation
Script     4.0.10     AzureRM.Backup
Script     4.1.5      AzureRM.Batch
Script     0.14.6     AzureRM.Billing
Script     5.0.6      AzureRM.Cdn
Script     0.9.11     AzureRM.CognitiveServices
Script     5.7.0      AzureRM.Compute
Script     0.3.7      AzureRM.Consumption
Script     0.2.10     AzureRM.ContainerInstance
Script     1.0.10     AzureRM.ContainerRegistry
Script     5.0.3      AzureRM.DataFactories
Script     0.5.11     AzureRM.DataFactoryV2
Script     5.1.4      AzureRM.DataLakeAnalytics
Script     6.1.2      AzureRM.DataLakeStore
Script     4.0.9      AzureRM.DevTestLabs
Script     5.1.0      AzureRM.Dns
Script     0.3.7      AzureRM.EventGrid
Script     0.6.10     AzureRM.EventHub
Script     4.1.8      AzureRM.HDInsight
Script     5.1.4      AzureRM.Insights
Script     3.1.8      AzureRM.IotHub
Script     5.2.1      AzureRM.KeyVault
Script     4.1.4      AzureRM.LogicApp
Script     0.18.5     AzureRM.MachineLearning
Script     0.4.8      AzureRM.MachineLearningCompute
Script     0.2.5      AzureRM.MarketplaceOrdering
Script     0.10.4     AzureRM.Media
Script     6.9.0      AzureRM.Network
Script     5.0.3      AzureRM.NotificationHubs
Script     5.0.6      AzureRM.OperationalInsights
Script     1.0.4      AzureRM.PolicyInsights
Script     4.1.10     AzureRM.PowerBIEmbedded
Script     5.6.0      AzureRM.profile
Script     4.1.8      AzureRM.RecoveryServices
Script     4.4.1      AzureRM.RecoveryServices.Backup
Script     0.2.10     AzureRM.RecoveryServices.SiteRec...
Script     5.1.0      AzureRM.RedisCache
Script     0.3.10     AzureRM.Relay
Script     6.6.0      AzureRM.Resources
Script     5.5.2      AzureRM.Resources
Script     0.16.10    AzureRM.Scheduler
Script     0.6.12     AzureRM.ServiceBus
Script     0.3.12     AzureRM.ServiceFabric
Script     1.0.0      AzureRM.SignalR
Script     4.11.5     AzureRM.Sql
Script     5.2.0      AzureRM.Storage
Script     4.0.10     AzureRM.StreamAnalytics
Script     4.0.5      AzureRM.Tags
Script     4.1.1      AzureRM.TrafficManager
Script     4.0.5      AzureRM.UsageAggregates
Script     5.2.0      AzureRM.Websites
Script     1.0.1      Microsoft.PowerShell.Operation.V...
Binary     1.0.0.1    PackageManagement
Script     3.4.0      Pester
Script     1.0.0.1    PowerShellGet
Script     1.2        PSReadline

### Environment Data

```powershell
$PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      5.1.15063.1563
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1563
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Debug Output

```
N/A
```

**Comment by markcowl** [comment]
This is by design, it has to do with how the ARM API works - listing resources generically returns only the ARM-tracked values of the resource (Name, Sku, Tags, etc.) and none of the Provider-specific data that is specific to the resource provider (in this case, compute).

Note that if you use Get to Get an individual resource, and provide the Resource-Type, then the resource-specific properties are returned.

Because of the way the ARM API works, if list scenarios like the above were to return the resource-specific properties, this would involve an additional call for every returned element.

Note that you can get the additional data by piping the values from a list command into another Get:

```powershell
Get-AzResource  | Get-AzResource
```

**Comment by tickermcse76** [comment]
@markcowl - Thanks for the response and explanation.  I am basically calling Get-AzResource twice as you suggested (and what I had hoped to avoid for efficiency).  I am no API architect, just a consumer.  But any object with a unique identifier (resourceId/Id) should return the same data no matter how it's called.  If the compute resources are stored separately there should be a compute specific unique identifier referenced within the generic data set (just my 2 cents).
