### ISSUE TITLE
Suspend-AzureRmDataFactoryPipeline Resource Not Found

### ISSUE THREAD

**Issue by divesh987** [Azure/azure-powershell#8497]
suspend-AzureRmDataFactoryPipeline : HTTP Status Code: NotFound
Error Code: ResourceNotFound

on running Suspend-AzureRmDataFactoryPipeline https://docs.microsoft.com/en-us/powershell/module/azurerm.datafactories/suspend-azurermdatafactorypipeline?view=azurermps-6.13.0

Is this commandlet deprecated for Data Factory V2, if so what is the equivalent?

**Comment by maddieclayton** [comment]
@divesh987 Please give us a little more information so that we can solve your issue:

Please run ```$DebugPreference = "Continue"``` and record the output after running the above cmdlet.
Please run ```Resolve-Error``` after running the above cmdlet and record the output.

**Comment by divesh987** [comment]
Hi, resolved through Azure support ticket...seems this cmdlet was deprecated in version 2 and alternative is to use Remove-AzureRmDataFactoryV2Pipeline cmdlet for Data Factory V2
