### ISSUE TITLE
WARNING: Module 'Az.xxx' is not a valid Az module.

### ISSUE THREAD

**Issue by ebrucucen** [Azure/azure-powershell#8498]
Inconsistent Az Module installation process. 

### Description
When I uninstall/install Az modules, not all directories have read permissions, thus some modules do not work on a Linux VM. If during uninstallation/installation process, there were modules being used, I would expect them to be reported at that point, not after installation.  

### Script/Steps for Reproduction

Jenkins agent started getting Warning Module x is not a valid module error. 

```powershell

-bash-4.2$ pwsh -command get-module -listavailable -name az.iotcentral
WARNING: Module 'Az.IotCentral' is not a valid Az module.


PS /root> su - jenkins -c "pwsh -command exit"
WARNING: Module 'Az.IotCentral' is not a valid Az module.

```
Then I uninstalled and installed the Az module as root
```
-bash$  pwsh -command Install-Module AZ -Allowclobber -Scope Allusers

```
Logged in as jenkins user and ran a command...
Then we started getting x is not recognized as the name of a cmdlet error message, although the module did exist on the PSModulePath modules. 

```
PS /var/lib/jenkins> get-azdiagnosticsetting
get-azdiagnosticsetting : The term 'get-azdiagnosticsetting' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ get-azdiagnosticsetting
+ ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (get-azdiagnosticsetting:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

```
Event the installation was successful, it looks like it could not give proper permissions to the folders. 

![az-install](https://user-images.githubusercontent.com/204902/52426933-e3949e00-2af6-11e9-925e-f12e577c79df.png)

### Module Version

```powershell
    Directory: /root/.local/share/powershell/Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.2.1      Az


    Directory: /usr/local/share/powershell/Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.2.1      Az

```

### Environment Data

```

Name                           Value                                                                                               ----                           -----                                                                                               PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2


OS                             Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

After giving 755 permissions to all folders, it did work. 
Should not installation process be more aware of its success criteria? - My assumption is that there was a module in use-

**Comment by markcowl** [comment]
Can you please file this issue against the PowerShell tesm, which owns the cmdlet that installs modules from the gallery:  https://github.com/powershell/powershell

Unless this is somehow specific to Az and not other modules, but sounds like this applies to any module you install form the gallery.

**Comment by bergmeister** [comment]
NB: The module for the `Install-Module` cmdlet functionality in question is `PowerShellGet`, an issue should be opened on https://github.com/PowerShell/PowerShellGet
