### ISSUE TITLE
Travis CI failed in copy TestResults trx file

### ISSUE THREAD

**Issue by ankushbindlish2** [Azure/azure-powershell#8502]
### Description
PR : https://github.com/Azure/azure-powershell/pull/8465 

Jenkins passed. Travis failed with Travis : https://travis-ci.org/Azure/azure-powershell/builds/490342463?utm_source=github_status&utm_medium=notification 

/home/travis/build/Azure/azure-powershell/build.proj(405,5): error MSB3030: Could not copy the file "/home/travis/build/Azure/azure-powershell/src/**/TestResults/*.trx" because it was not found.
/home/travis/build/Azure/azure-powershell/build.proj(411,5): error : Test failures occured, check the files in artifacts/Test

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by markcowl** [comment]
@maddieclayton @ankushbindlish2 This is most likely related to using the ''\' character in paths in build.proj - just pulled the latest into your branch, but it looks like you inadvertently added some backslashes to the copy paths in your last few commits.

**Comment by ankushbindlish2** [comment]
I reverted all the changes that were tried on build.proj. Please suggest next step.
