### ISSUE TITLE
Update-AzAks for Kubernetes version updates

### ISSUE THREAD

**Issue by amandadebler** [Azure/azure-powershell#8519]
A cmdlet for updating (upgrading) an existing AKS cluster to a given Azure-available release of Kubernetes.

Why Update instead of Upgrade? PowerShell approved verbs list: https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands#data-verbs 

Why not add it as a parameter to Set-AzAks? Less complicated to have separate cmdlets for separate operations

Related cmdlet that should exist: Get-AzAksVersion -Region $AzureRegion - Gets all applicable Kubernetes versions (mirroring "az aks get-versions --region $AZUREREGION")

Usage:

Update-AzAks -Id $ResourceId -Version $SomeK8sVersion

Update-AzAks -Id $ResourceId -LatestMinorVersion
Updates the cluster to the latest minor version for its current major version

Update-AzAks -Id $ResourceId -NextMajorVersion
Updates the cluster to the latest major version possible from its current version, then publishes message to Write-Info that there are later major versions above where this cluster was updated

Update-AzAks -Id $ResourceId -LatestVersion
Unless -Confirm:$false is also part of the command given, alerts user that this update will span multiple versions, taking longer than a single version update and may cause issues with the applications running in the cluster

Get-AzAks | Update-AzAks -LatestMinorVersion
Updates all clusters in the subscription to the latest minor version (useful for when a vulnerability comes out and AKS has fixes available!)

**Comment by maddieclayton** [comment]
@mboersma Can you take a look at this feature request?

**Comment by amandadebler** [comment]
I'll be happy to help test this if you decide to include it :)

Get possible upgrade target versions for a given cluster:

Get-AzAksVersion -Cluster $AzAksCluster

or

Get-AzAks -Id $ResourceId -IncludeUpgradeVersions
(returns AzAks object + UpgradeVersions attribute as array)

**Comment by jluk** [comment]
There is a preview project to revamp the aks ps cmds. Please feel free to visit, test, and open issues on the powershell repo.

https://github.com/Azure/azure-powershell/blob/generation/src/Aks/docs/New-AzAks.md
