### ISSUE TITLE
Powershell Commandlet to Generate Password for for APIM git Repo

### ISSUE THREAD

**Issue by Walluce** [Azure/azure-powershell#8528]
I would like a Powershell commandlet to generate Passwords for the git repository, please.

The last post I can find on StackOverflow (https://stackoverflow.com/questions/44843558/generating-passwords-for-the-azure-api-management-git-repository) seems to imply that it is in progress, but I see nothing on the documentation page?

I asked about this question in: https://www.yammer.com/azureadvisors/#/threads/inGroup?type=in_group&feedId=4009316

**Comment by maddieclayton** [comment]
@solankisamir Can you take a look at this issue?

**Comment by solankisamir** [comment]
#ack

**Comment by solankisamir** [comment]
Does this help in the meantime https://github.com/Azure/api-management-samples/blob/master/scripts/Get_AzureRmApiManagementGitCredentials.ps1

**Comment by solankisamir** [comment]
[package](https://www.powershellgallery.com/packages/Az/2.1.0)
[documentation](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/?view=azps-2.1.0#api_management)
[releasenotes](https://github.com/Azure/azure-powershell/releases/tag/v2.1.0-May2019)
