### ISSUE TITLE
Missing parameter in powershell CMDlet

### ISSUE THREAD

**Issue by PowerUnreached** [Azure/azure-powershell#8530]
i was trying to create a azure automation software update configuration via Powershell. I used the cmdlet „New-AzureRmAutomationSoftwareUpdateConfiguration“.

Here is the link to the used article: https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/new-azurermautomationsoftwareupdateconfiguration?view=azurermps-6.13.0
But there is a problem, one important paramenter seems to be missing. There is no parameter to configure the reboot options in azure.

The description in the article works fine in my azure account – it created a rule with all the setting I need. Only the reboot options are set on default „Reboot if required“.
 

There seems to be no parameter to configure this options in the cmdlet „New-AzureRmAutomationSoftwareUpdateConfiguration“. 
I have the lates of the module „AzureRM.Automation“ 6.1.1.

Can you tell me, how i can configure the reboot options via powershell? Or is the only way to configure this in the Azure Portal?
![screenshot](https://user-images.githubusercontent.com/47599423/52715129-f0ecd500-2f9b-11e9-99b1-4e0d91f5102d.jpg)

Thank you very much

**Comment by maddieclayton** [comment]
@vrdmr Can you take a look at this issue?

**Comment by andyw248** [comment]
Feature request, please add to user voice.
