### ISSUE TITLE
Cannot use Desired State Configuration (DSC) with the AZ Module

### ISSUE THREAD

**Issue by brwilkinson** [Azure/azure-powershell#8540]
When searching for the new module on the gallery you can use find-module and the az module is located.

````Powershell
find-module az 

Version Name Repository Description
------- ---- ---------- -----------
1.3.0   Az   PSGallery  Microsoft Azure PowerShell
````
To install the module you can use install-module az -force and the modules are loaded.

However you cannot discover the AZ module itself, since it only loads other modules. e.g. below does not show the module, since only the dependent modules actually get loaded.

````powershell
> get-module -name az -ListAvailable
> 
````

This is a problem when using DSC to install the AZ module, since the test will always fail and it will always run the set command to run the install.

Is it possible to actually load the AZ module, perhaps with just a helper cmdlet such as Get-AzModuleVersion or such ?

Or I guess just make it function the same as the **azurerm** module does ?!

````powershell
gmo azurerm -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version Name    ExportedCommands
---------- ------- ----    ----------------
Script     5.7.0   AzureRM
````

**Comment by maddieclayton** [comment]
@brwilkinson This issue is actually with PowerShell itself - when PowerShell sees a directory named after a locale (in this case, Az also stands for Azerbaijan), it will automatically skip the directory.  You can track this issue here: https://github.com/PowerShell/PowerShell/issues/8125, feel free to comment on this issue regarding how this issue is blocking you.

**Comment by brwilkinson** [comment]
@maddieclayton oh thank you. . .

such a strange thing  😁 I am so glad there was an explanation.
