### ISSUE TITLE
Does Import-AzureRmApiManagementApi cmdlet support swagger with YAML format?

### ISSUE THREAD

**Issue by debashis1982** [Azure/azure-powershell#8562]
I am new to this and I am trying to import a swagger file in YAML format using **Import-AzureRmApiManagementApi** PS cmdlet this way - 

`
Import-AzureRmApiManagementApi -Context $ApiMgmtContext -SpecificationFormat "Swagger" -SpecificationPath "C:\Users\test\Downloads\testapi.openapi.yaml" -Path "apis"
`

and I get error like - 

`
Body:
{
  "error": {
    "code": "ValidationError",
    "message": "One or more fields contain incorrect values:",
    "details": [
      {
        "code": "ValidationError",
        "target": "representation",
        "message": "Parsing error(s): Unexpected character encountered while parsing value: o. Path '', line 0, position 0."
      }
    ]
  }
}
`

The swagger I am using is of type 'openapi: 3.0.0' in YAML format. I get the same error even if I try this with a swagger file belonging to an existing API downloaded from Azure portal itself. 
It seems to work if I use a swagger in JSON format though. So is a YAML based swagger not accepted by this cmdlet yet or am I doing something wrong?

**Comment by maddieclayton** [comment]
@solankisamir Can you answer this question or direct to the right team who can answer this question?

**Comment by solankisamir** [comment]
@debashis1982, the PS cmdlet does not support importing in YAML format for 3.0.0. We are working on adding support for that.

**Comment by debashis1982** [comment]
> @debashis1982, the PS cmdlet does not support importing in YAML format for 3.0.0. We are working on adding support for that.

thank you!

**Comment by ryanspletzer** [comment]
Is this support in place yet?

**Comment by solankisamir** [comment]
the new cmdlets should be released by 5/21 (the next release train of powershell)

**Comment by raworre** [comment]
I am seeing this error in Azure RM 6.13.1 Is this not yet released?

**Comment by ryanspletzer** [comment]
For now I've worked around this by converting the yaml to json on the fly in our build pipeline with assistance from the powershell-yaml module.

https://github.com/cloudbase/powershell-yaml
