### ISSUE TITLE
Powershell Invoke-RestMethod does not return expected response

### ISSUE THREAD

**Issue by ashringa** [Azure/azure-powershell#8568]
The PowerShell Script that is being used to hit the REST API to obtain a full list of the Service SKU is only showing partial information using the service principal account in Azure, compared to the Resource SKU – Try It Out Demo website, using the Azure Account. What may be going on with the PowerShell Script that is only pulling a partial list of service SKUs? Also, is there a way to use the Azure Login credentials in the PowerShell Script command to access the list of the resource SKUs available? I have provided the link here for more information: https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list

**Comment by maddieclayton** [comment]
@ashringa Please file an issue against the doc page regarding the difference between the output of Invoke-RestMethod and the demo website. Regarding the ability to access a list of available SKUs, we are planning to add a SKU completer to all cmdlets which have a SKU parameter: https://github.com/Azure/azure-powershell/issues/8004.  Please let us know if this does not fit with your use case.

**Comment by ashringa** [comment]
@maddieclayton thank you for your reply. Could you please provide me the link to open the issue with doc page. Also, by what is the timeline for SKU cmdlets?
