### ISSUE TITLE
Update Microsoft.ServiceBus to an newer version

### ISSUE THREAD

**Issue by teilmeier** [Azure/azure-powershell#857]
Currently version 2.3 is referenced. This version doesn't contain newer features like the Event Hub. This may require some changes to the Service Bus Notifications because they are now part of Microsoft.Azure.NotificationHubs

**Comment by cormacpayne** [comment]
Closing this issue as EventHub has released their own set of cmdlets. Please feel free to re-open this issue if you have any other questions.
