### ISSUE TITLE
How can I troubleshoot my issue?

### ISSUE THREAD

**Issue by hothotsyu** [Azure/azure-powershell#8578]
Hi my friends
I installed the latest Powershell 6.1.3 without uninstalling the Powershell 5.1.

I can connect to Azure with Powershell 5.1, but I can't connect to Azure with Powershell 6.1.3

Can you help me?

Best regards,
Linshan.Xu

**Comment by maddieclayton** [comment]
@hothotsyu Can you please give the current layout of the machine for PowerShell 6.1.3 by running
```Get-Module -ListAvailable```
Please ensure you have installed the latest Az bits by running
```Install-Module Az```
If the newest Az bits do not work for you, please give us more information by running
```$DebugPreference = Continue```
Then run your cmdlet and paste the output here. Then run this cmdlet and paste the output:
```Resolve-Error```

**Comment by hothotsyu** [comment]
Hi maddieclayton,

Thanks for your help!
The output are as folllows:

Best Regards,
Linshan.Xu

===============================================================
PS C:\Users\linshan.xu> Connect-AzureRMAccount
Connect-AzureRMAccount : The term 'Connect-AzureRMAccount' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Connect-AzureRMAccount
+ ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Connect-AzureRMAccount:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\linshan.xu>
PS C:\Users\linshan.xu> $DebugPreference = Continue
PS C:\Users\linshan.xu> Resolve-Error
Resolve-Error : The 'Resolve-Error' command was found in the module 'Az.Accounts', but the module could not be loaded. For more information, run 'Import-Module Az.Accounts'.
At line:1 char:1
+ Resolve-Error
+ ~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Resolve-Error:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

PS C:\Users\linshan.xu> Get-Module -ListAvailable


    Directory: C:\Program Files\PowerShell\Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     1.3.0      Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAuto...
Script     1.0.1      Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAk...
Script     1.0.0      Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnal...
Script     1.0.0      Az.ApiManagement                    Core,Desk {Add-AzApiManagementRegion, Get-AzApiManagementS...
Script     1.0.0      Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationIns...
Script     1.1.0      Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAut...
Script     1.0.0      Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-...
Script     1.0.0      Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-...
Script     1.0.1      Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-A...
Script     1.0.0      Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitive...
Script     1.3.0      Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet...
Script     1.0.0      Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Rem...
Script     1.0.1      Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistr...
Script     1.0.1      Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Ge...
Script     1.0.0      Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLa...
Script     1.0.2      Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-Az...
Script     1.0.0      Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShu...
Script     1.0.0      Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remo...
Script     1.1.0      Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set...
Script     1.0.0      Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespac...
Script     1.0.0      Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefi...
Script     1.0.2      Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGr...
Script     1.0.1      Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCer...
Script     1.1.0      Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegr...
Script     1.0.0      Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitm...
Script     1.0.0      Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.0.0      Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKeys, Set-AzMediaServ...
Script     1.0.0      Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-Az...
Script     1.1.0      Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertifica...
Script     1.0.0      Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAut...
Script     1.0.0      Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSo...
Script     1.0.0      Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPol...
Script     1.0.0      Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPowe...
Script     1.0.0      Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRec...
Script     1.0.0      Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCa...
Script     1.0.0      Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set...
Script     1.1.2      Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignmen...
Script     1.0.0      Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusName...
Script     1.0.1      Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricApplicationCertificate, Add-...
Script     1.0.2      Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey,...
Script     1.2.0      Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get...
Script     1.0.2      Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, ...
Script     1.0.0      Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAnal...
Script     1.0.1      Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Rem...
Script     1.1.0      Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New...
Script     0.5.4      Azure.AnalysisServices              Desk      {Add-AzureAnalysisServicesAccount, Restart-Azure...
Script     4.6.1      Azure.Storage                       Desk      {Get-AzureStorageTable, New-AzureStorageTableSAS...
Binary     2.0.2.4    AzureAD                             Desk
Script     6.13.1     AzureRM                             Desk
Script     0.6.14     AzureRM.AnalysisServices            Desk      {Resume-AzureRmAnalysisServicesServer, Suspend-A...
Script     6.1.7      AzureRM.ApiManagement               Desk      {Add-AzureRmApiManagementRegion, Get-AzureRmApiM...
Script     0.1.8      AzureRM.ApplicationInsights         Desk      {Get-AzureRmApplicationInsights, New-AzureRmAppl...
Script     6.1.1      AzureRM.Automation                  Desk      {Get-AzureRMAutomationHybridWorkerGroup, Remove-...
Script     4.0.11     AzureRM.Backup                      Desk      {Backup-AzureRmBackupItem, Enable-AzureRmBackupC...
Script     4.1.5      AzureRM.Batch                       Desk      {Remove-AzureRmBatchAccount, Get-AzureRmBatchAcc...
Script     0.14.6     AzureRM.Billing                     Desk      {Get-AzureRmBillingInvoice, Get-AzureRmBillingPe...
Script     5.0.6      AzureRM.Cdn                         Desk      {Get-AzureRmCdnProfile, Get-AzureRmCdnProfileSso...
Script     0.9.12     AzureRM.CognitiveServices           Desk      {Get-AzureRmCognitiveServicesAccount, Get-AzureR...
Script     5.9.1      AzureRM.Compute                     Desk      {Remove-AzureRmAvailabilitySet, Get-AzureRmAvail...
Script     0.3.7      AzureRM.Consumption                 Desk      {Get-AzureRmConsumptionBudget, Get-AzureRmConsum...
Script     0.2.12     AzureRM.ContainerInstance           Desk      {New-AzureRmContainerGroup, Get-AzureRmContainer...
Script     1.0.10     AzureRM.ContainerRegistry           Desk      {New-AzureRmContainerRegistry, Get-AzureRmContai...
Script     5.0.3      AzureRM.DataFactories               Desk      {Remove-AzureRmDataFactory, Get-AzureRmDataFacto...
Script     0.5.11     AzureRM.DataFactoryV2               Desk      {Set-AzureRmDataFactoryV2, Update-AzureRmDataFac...
Script     5.1.4      AzureRM.DataLakeAnalytics           Desk      {Get-AzureRmDataLakeAnalyticsDataSource, New-Azu...
Script     6.2.1      AzureRM.DataLakeStore               Desk      {Get-AzureRmDataLakeStoreTrustedIdProvider, Remo...
Script     4.0.9      AzureRM.DevTestLabs                 Desk      {Get-AzureRmDtlAllowedVMSizesPolicy, Get-AzureRm...
Script     5.1.0      AzureRM.Dns                         Desk      {Get-AzureRmDnsRecordSet, New-AzureRmDnsRecordCo...
Script     0.3.7      AzureRM.EventGrid                   Desk      {New-AzureRmEventGridTopic, Get-AzureRmEventGrid...
Script     0.7.0      AzureRM.EventHub                    Desk      {New-AzureRmEventHubNamespace, Get-AzureRmEventH...
Script     4.1.8      AzureRM.HDInsight                   Desk      {Get-AzureRmHDInsightJob, New-AzureRmHDInsightSq...
Script     5.1.5      AzureRM.Insights                    Desk      {Get-AzureRmMetricDefinition, Get-AzureRmMetric,...
Script     3.1.8      AzureRM.IotHub                      Desk      {Add-AzureRmIotHubKey, Get-AzureRmIotHubEventHub...
Script     5.2.1      AzureRM.KeyVault                    Desk      {Add-AzureKeyVaultCertificate, Update-AzureKeyVa...
Script     4.1.4      AzureRM.LogicApp                    Desk      {Get-AzureRmIntegrationAccountAgreement, Get-Azu...
Script     0.18.5     AzureRM.MachineLearning             Desk      {Move-AzureRmMlCommitmentAssociation, Get-AzureR...
Script     0.4.8      AzureRM.MachineLearningCompute      Desk      {Get-AzureRmMlOpCluster, Get-AzureRmMlOpClusterK...
Script     0.2.7      AzureRM.MarketplaceOrdering         Desk      {Get-AzureRmMarketplaceTerms, Set-AzureRmMarketp...
Script     0.10.4     AzureRM.Media                       Desk      {Sync-AzureRmMediaServiceStorageKeys, Set-AzureR...
Script     6.11.1     AzureRM.Network                     Desk      {Add-AzureRmApplicationGatewayAuthenticationCert...
Script     5.0.3      AzureRM.NotificationHubs            Desk      {Get-AzureRmNotificationHub, Get-AzureRmNotifica...
Script     5.0.6      AzureRM.OperationalInsights         Desk      {New-AzureRmOperationalInsightsAzureActivityLogD...
Script     1.1.0      AzureRM.PolicyInsights              Desk      {Get-AzureRmPolicyEvent, Get-AzureRmPolicyState,...
Script     4.1.10     AzureRM.PowerBIEmbedded             Desk      {Remove-AzureRmPowerBIWorkspaceCollection, Get-A...
Script     5.8.2      AzureRM.profile                     Desk      {Disable-AzureRmDataCollection, Disable-AzureRmC...
Script     4.1.9      AzureRM.RecoveryServices            Desk      {Get-AzureRmRecoveryServicesBackupProperty, Get-...
Script     4.5.2      AzureRM.RecoveryServices.Backup     Desk      {Backup-AzureRmRecoveryServicesBackupItem, Get-A...
Script     0.2.12     AzureRM.RecoveryServices.SiteRec... Desk      {Edit-AzureRmRecoveryServicesAsrRecoveryPlan, Ge...
Script     5.1.0      AzureRM.RedisCache                  Desk      {Remove-AzureRmRedisCachePatchSchedule, New-Azur...
Script     0.3.12     AzureRM.Relay                       Desk      {New-AzureRmRelayNamespace, Get-AzureRmRelayName...
Script     6.7.3      AzureRM.Resources                   Desk      {Get-AzureRmProviderOperation, Remove-AzureRmRol...
Script     0.16.10    AzureRM.Scheduler                   Desk      {Disable-AzureRmSchedulerJobCollection, Enable-A...
Script     0.6.13     AzureRM.ServiceBus                  Desk      {New-AzureRmServiceBusNamespace, Get-AzureRmServ...
Script     0.3.15     AzureRM.ServiceFabric               Desk      {Add-AzureRmServiceFabricApplicationCertificate,...
Script     1.0.0      AzureRM.SignalR                     Desk      {New-AzureRmSignalR, Get-AzureRmSignalR, Get-Azu...
Script     4.12.1     AzureRM.Sql                         Desk      {Get-AzureRmSqlDatabaseTransparentDataEncryption...
Script     5.2.0      AzureRM.Storage                     Desk      {Get-AzureRmStorageAccount, Get-AzureRmStorageAc...
Script     4.0.10     AzureRM.StreamAnalytics             Desk      {Get-AzureRmStreamAnalyticsFunction, Get-AzureRm...
Script     4.0.5      AzureRM.Tags                        Desk      {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag}
Script     4.1.3      AzureRM.TrafficManager              Desk      {Add-AzureRmTrafficManagerCustomHeaderToEndpoint...
Script     4.0.5      AzureRM.UsageAggregates             Desk      Get-UsageAggregates
Script     5.2.0      AzureRM.Websites                    Desk      {Get-AzureRmAppServicePlan, Set-AzureRmAppServic...


    Directory: C:\program files\powershell\6\Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Manifest   6.1.0.0    CimCmdlets                          Core      {Get-CimAssociatedInstance, Get-CimClass, Get-Ci...
Manifest   1.2.2.0    Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   6.1.0.0    Microsoft.PowerShell.Diagnostics    Core      {Get-WinEvent, New-WinEvent}
Manifest   6.1.0.0    Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   6.1.0.0    Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty,...
Manifest   6.1.0.0    Microsoft.PowerShell.Security       Core      {Get-Acl, Set-Acl, Get-PfxCertificate, Get-Crede...
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        Core      {Format-List, Format-Custom, Format-Table, Forma...
Manifest   6.1.0.0    Microsoft.WSMan.Management          Core      {Disable-WSManCredSSP, Enable-WSManCredSSP, Get-...
Script     1.1.7.2    PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider,...
Script     1.6.7      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Fi...
Script     0.0        PSDesiredStateConfiguration         Desk      {StrongConnect, ValidateUpdate-ConfigurationData...
Script     6.1.0.0    PSDiagnostics                       Core      {Disable-PSTrace, Disable-PSWSManCombinedTrace, ...
Script     2.0.0      PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHand...
Binary     1.1.2      ThreadJob                           Desk      Start-ThreadJob


PS C:\Users\linshan.xu>
===============================================================

**Comment by hothotsyu** [comment]
Addition information as follows:
I can run the command : Connect-AzAccount to login to my Azure.

I want to run the command : Connect-AzureRMAccount(latest version Powershell 6.1.3) also.

**Comment by maddieclayton** [comment]
@hothotsyu We are only supporting the new Az module on PowerShell 6.1.3 - while the AzureRM module only supports desktop, Az supports both desktop and core, allowing it to be used in PowerShell 6 for all platforms.  Please let me know if there is something missing in Az that you are looking for.
