### ISSUE TITLE
[Documentation]: How to get the AZ modules into a Powershell Azure Function

### ISSUE THREAD

**Issue by alujones** [Azure/azure-powershell#8581]
I'd like to be able to manage some of my Azure Subscriptions from a web app hosted in Azure. I thought it would be great to get it working as a serverless function, since that's the cool tool. Particularly, I want to use the new Search-AzGraph function, so I'm unable to use the old Azure modules that are supplied with the Powershell in Azure Functions.
I tried to copy the modules up to the Azure Function's storage, under the 'modules' directory, but it's causing all sorts of errors trying to load the modules:
2019-02-20T22:47:52.910 [Info] Function started (Id=6dd75b3b-51ac-4c64-97a6-1d8b614da831)
2019-02-20T22:47:54.551 [Error] Import-Module : The specified module 'Az.Accounts' with version '1.3.0' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, /CNAMEFromMDNS/modules/mod1/Az/1.3.0/Az.psm1: line 90
+ Import-Module
+ _____________
    + CategoryInfo          : ResourceUnavailable: (Az.Accounts:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleWithVersionNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
2019-02-20T22:47:54.598 [Error] Import-Module : The specified module 'Az.Aks' with version '1.0.1' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, /CNAMEFromMDNS/modules/mod1/Az/1.3.0/Az.psm1: line 92
+ Import-Module
+ _____________
    + CategoryInfo          : ResourceUnavailable: (Az.Aks:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleWithVersionNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
--------------------------
Several more of the same kind of errors - although I have indeed included each of these modules in the same directory as the Az module that is loading successfully.

I don't know if there's some other technique I'm missing (am I supposed to set an environment variable that the Import-Module process in Az is using?), or some other obstacle (does Az insist on a newer version of something than is present in Azure?). Is this something that has been done, or should I be giving up and looking elsewhere?

Really simply put, can you provide documentation of how to call Search-AzGraph from an Azure environment?

**Comment by markcowl** [comment]
@alujones are you following these instructions: https://azure.microsoft.com/en-us/blog/serverless-automation-using-powershell-preview-in-azure-functions/ ?

**Comment by alujones** [comment]
That's new since I posted originally. It's hard to find content such as this on the Internet, you need to see what can be done about surfacing this in search results. I actually found something similar to this just this morning, and will be adding it to my new PowerShell Runtime 2.0 functions. I look forward to this becoming easier to find and easier to manage in the future.

**Comment by alujones** [comment]
So, that included the Az module, but I don't see how it lets me manage the Az.ResourceGraph module as well, which is needed to call Search-AzGraph. I tried adding the line "Az.ResourceGraph = 'latest'" to the requirements.psd1 file, but got a complaint that there were two keys in the psd1 file called "Az".

**Comment by markcowl** [comment]
@eamonoreilly Is there any current mechanism for adding modules outside 'Az'?

@alujones this is really a question about the capabilities of azure functions service, so this may not be the best palce to get a good answer, but assignign to @dcaro to see if we cna find a good documentation solutionf ro this.

**Comment by eamonoreilly** [comment]
You should be able to add the Az.ResourceGraph by following the below steps.

1) Make sure manageddependency is enabled on the function app.
{
  "version": "2.0",
  "managedDependency": {
    "enabled": true
  }
}
2) Save the Az.ResourceGraph to the modules folder at the root of the function app
mkdir modules
Save-Module Az.ResourceGraph .\modules

You can then use the managed identity (https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?toc=%2fazure%2fazure-functions%2ftoc.json)  of the function app or your own credentials to authenticate and then call Search-AzGraph. I tested this out and it worked successfully.

You can open up PowerShell specific issues for Azure Functions on https://github.com/Azure/azure-functions-powershell-worker/issues also.
Thanks,
Eamon

**Comment by dcaro** [comment]
@alujones I'm following up on this issue, have you been able to add the Az.ResourceGraph using the guidance that Eamon gave above?

**Comment by dcaro** [comment]
Closing this issue as the information above seems to have provided the answer to the question. Feel free to comment and reopen if not the case.
