### ISSUE TITLE
Get-AzureRmDefault throws NullReferenceException on start

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-powershell#8582]
## Description

Running Get-AzureRmDefault without any parameters throws exception NullReferenceException Object reference not set to an instance of an object.

## Steps to reproduce

```powershell
PS C:\> Get-AzureRmDefault
Get-AzureRmDefault : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-AzureRmDefault
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmDefault], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.Default.GetAzureRMDefaultCommand
```

## Module versions

```powershell
PS C:\> Get-Module -Name AzureRM.Profile

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.6.0      AzureRM.Profile
```

## Debug output

>DEBUG: AzureQoSEvent: CommandName - Get-AzureRmDefault; IsSuccess - False; Duration - 00:00:00.0223189; Exception - System.NullReferenceException:
Object reference not set to an instance of an object.
   at Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureEnvironmentExtensions.TryGetEndpointUrl(IAzureEnvironment environment, String
endpointName, Uri& endpoint)
   at Microsoft.Azure.Commands.Profile.Default.GetAzureRMDefaultCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 17:22:40 - GetAzureRMDefaultCommand end processing.
DEBUG: 17:22:40 - GetAzureRMDefaultCommand end processing.

## Error output

> DEBUG: 17:26:27 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureEnvironmentExtensions.TryGetEndpointUrl(IAzureEnvironment
                 environment, String endpointName, Uri& endpoint)
                    at Microsoft.Azure.Commands.Profile.Default.GetAzureRMDefaultCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzureRmDefault}
Line           : Get-AzureRmDefault
Position       : At line:1 char:1
                 + Get-AzureRmDefault
                 + ~~~~~~~~~~~~~~~~~~

**Comment by maddieclayton** [comment]
@abatishchev Can you try upgrading to our latest version of Az (not AzureRM) and see if you are still seeing this issue? I cannot replicate in my session with Az.

**Comment by abatishchev** [comment]
Unfortunately I cannot upgrade to Az right away. But if you're saying it works there and won't back-ported to AzureRM then I think it's fine to close this issue. Thanks for your help!

**Comment by maddieclayton** [comment]
Unfortunately we are only fixing security related bugs in AzureRM, so if this issue cannot be replicated in Az I will assume it was fixed at some point - if you figure out that it is a specific setting that caused this issue for you I will definitely try to replicate in Az to ensure that it has indeed been fixed.
