### ISSUE TITLE
AzureRm.Sql - New-AzureRmSqlSyncGroup - "The sync database specified does not match existing sync database"

### ISSUE THREAD

**Issue by inuvano-labs** [Azure/azure-powershell#8587]
If I attempt to create more than one Data Sync group via New-AzureRmSqlSyncGroup targeting different Hub and Meta Data databases on the same subscription, I'm receiving an exception:

"New-AzureRmSqlSyncGroup : SyncOperation_WrongSyncDatabase: The sync database specified (thenewmetadataservername\\thenewmetadatadb) 
does not match the existing sync database (anothermetadataservername\\anothermetadatadatabasename)."

If I create a sync group via the Azure Portal OR through Powershell, this succeeds. But if I subsequently run the New-AzureRmSqlSyncGroup command a second time with different server/database it fails. It's almost like the command is enumerating existing sync groups and picking the first one it finds.

## Steps to reproduce

Create the first sync group:

New-AzureRmSqlSyncGroup  -ResourceGroupName "MyResourceGroup1" `
                            -ServerName "MyServerName1" `
                            -DatabaseName "MyHubDatabase1" `
                            -Name "MySyncGroup1" `
                            -SyncDatabaseResourceGroupName "MyResourceGroup1" `
                            -SyncDatabaseServerName "MyServerName1" `
                            -SyncDatabaseName "MyMetaDataDB" `
                            -ConflictResolutionPolicy "HubWin"

Then create another sync group - either on the same SQL server or new SQL server, but different Hub + MetaData databases:

New-AzureRmSqlSyncGroup  -ResourceGroupName "MyResourceGroup1" `
                            -ServerName "MyServerName2" `
                            -DatabaseName "MyHubDatabase2" `
                            -Name "MySyncGroup2" `
                            -SyncDatabaseResourceGroupName "MyResourceGroup1" `
                            -SyncDatabaseServerName "MyServerName2" `
                            -SyncDatabaseName "MyMetaDataDB" `
                            -ConflictResolutionPolicy "HubWin"

## Module versions

ModuleType Version    Name                                ExportedCommands                                                
---------- -------    ----                                ----------------                                                
Script     6.4.0      AzureRM                                                                                             
Script     5.7.0      AzureRM                                                                                             
Script     0.6.9      AzureRM.AnalysisServices            {Resume-AzureRmAnalysisServicesServer, Suspend-AzureRmAnalysi...
Script     0.6.6      AzureRM.AnalysisServices            {Resume-AzureRmAnalysisServicesServer, Suspend-AzureRmAnalysi...
Script     6.1.1      AzureRM.ApiManagement               {Add-AzureRmApiManagementRegion, Get-AzureRmApiManagementSsoT...
Script     5.1.2      AzureRM.ApiManagement               {Add-AzureRmApiManagementRegion, Get-AzureRmApiManagementSsoT...
Script     0.1.4      AzureRM.ApplicationInsights         {Get-AzureRmApplicationInsights, New-AzureRmApplicationInsigh...
Script     0.1.3      AzureRM.ApplicationInsights         {Get-AzureRmApplicationInsights, New-AzureRmApplicationInsigh...
Script     5.0.1      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutomatio...
Script     4.3.2      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutomatio...
Script     4.0.6      AzureRM.Backup                      {Backup-AzureRmBackupItem, Enable-AzureRmBackupContainerRereg...
Script     4.0.4      AzureRM.Backup                      {Backup-AzureRmBackupItem, Enable-AzureRmBackupContainerRereg...
Script     4.1.1      AzureRM.Batch                       {Remove-AzureRmBatchAccount, Get-AzureRmBatchAccount, Get-Azu...
Script     4.0.6      AzureRM.Batch                       {Remove-AzureRmBatchAccount, Get-AzureRmBatchAccount, Get-Azu...
Script     0.14.3     AzureRM.Billing                     {Get-AzureRmBillingInvoice, Get-AzureRmBillingPeriod, Get-Azu...
Script     0.14.1     AzureRM.Billing                     {Get-AzureRmBillingInvoice, Get-AzureRmBillingPeriod, Get-Azu...
Script     5.0.1      AzureRM.Cdn                         {Get-AzureRmCdnProfile, Get-AzureRmCdnProfileSsoUrl, New-Azur...
Script     4.2.2      AzureRM.Cdn                         {Get-AzureRmCdnProfile, Get-AzureRmCdnProfileSsoUrl, New-Azur...
Script     0.9.6      AzureRM.CognitiveServices           {Get-AzureRmCognitiveServicesAccount, Get-AzureRmCognitiveSer...
Script     0.9.4      AzureRM.CognitiveServices           {Get-AzureRmCognitiveServicesAccount, Get-AzureRmCognitiveSer...
Script     5.2.0      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet, N...
Script     4.6.0      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet, N...
Script     0.3.5      AzureRM.Consumption                 {Get-AzureRmConsumptionBudget, Get-AzureRmConsumptionMarketpl...
Script     0.3.1      AzureRM.Consumption                 Get-AzureRmConsumptionUsageDetail                               
Script     0.2.6      AzureRM.ContainerInstance           {New-AzureRmContainerGroup, Get-AzureRmContainerGroup, Remove...
Script     0.2.5      AzureRM.ContainerInstance           {New-AzureRmContainerGroup, Get-AzureRmContainerGroup, Remove...
Script     1.0.6      AzureRM.ContainerRegistry           {New-AzureRmContainerRegistry, Get-AzureRmContainerRegistry, ...
Script     1.0.4      AzureRM.ContainerRegistry           {New-AzureRmContainerRegistry, Get-AzureRmContainerRegistry, ...
Script     5.0.1      AzureRM.DataFactories               {Remove-AzureRmDataFactory, Get-AzureRmDataFactoryRun, Get-Az...
Script     4.2.2      AzureRM.DataFactories               {Remove-AzureRmDataFactory, Get-AzureRmDataFactoryRun, Get-Az...
Script     0.5.6      AzureRM.DataFactoryV2               {Set-AzureRmDataFactoryV2, Update-AzureRmDataFactoryV2, Get-A...
Script     0.5.3      AzureRM.DataFactoryV2               {Set-AzureRmDataFactoryV2, Update-AzureRmDataFactoryV2, Get-A...
Script     5.1.0      AzureRM.DataLakeAnalytics           {Get-AzureRmDataLakeAnalyticsDataSource, New-AzureRmDataLakeA...
Script     4.2.3      AzureRM.DataLakeAnalytics           {Get-AzureRmDataLakeAnalyticsDataSource, New-AzureRmDataLakeA...
Script     6.1.0      AzureRM.DataLakeStore               {Get-AzureRmDataLakeStoreTrustedIdProvider, Remove-AzureRmDat...
Script     5.2.0      AzureRM.DataLakeStore               {Get-AzureRmDataLakeStoreTrustedIdProvider, Remove-AzureRmDat...
Script     4.0.5      AzureRM.DevTestLabs                 {Get-AzureRmDtlAllowedVMSizesPolicy, Get-AzureRmDtlAutoShutdo...
Script     4.0.4      AzureRM.DevTestLabs                 {Get-AzureRmDtlAllowedVMSizesPolicy, Get-AzureRmDtlAutoShutdo...
Script     5.0.0      AzureRM.Dns                         {Get-AzureRmDnsRecordSet, New-AzureRmDnsRecordConfig, Remove-...
Script     4.1.2      AzureRM.Dns                         {Get-AzureRmDnsRecordSet, New-AzureRmDnsRecordConfig, Remove-...
Script     0.3.5      AzureRM.EventGrid                   {New-AzureRmEventGridTopic, Get-AzureRmEventGridTopic, Set-Az...
Script     0.3.2      AzureRM.EventGrid                   {New-AzureRmEventGridTopic, Get-AzureRmEventGridTopic, Set-Az...
Script     0.6.5      AzureRM.EventHub                    {New-AzureRmEventHubNamespace, Get-AzureRmEventHubNamespace, ...
Script     0.6.3      AzureRM.EventHub                    {New-AzureRmEventHubNamespace, Get-AzureRmEventHubNamespace, ...
Script     4.1.4      AzureRM.HDInsight                   {Get-AzureRmHDInsightJob, New-AzureRmHDInsightSqoopJobDefinit...
Script     4.1.2      AzureRM.HDInsight                   {Get-AzureRmHDInsightJob, New-AzureRmHDInsightSqoopJobDefinit...
Script     5.0.1      AzureRM.Insights                    {Get-AzureRmMetricDefinition, Get-AzureRmMetric, Remove-Azure...
Script     4.0.4      AzureRM.Insights                    {Get-AzureRmMetricDefinition, Get-AzureRmMetric, Remove-Azure...
Script     3.1.4      AzureRM.IotHub                      {Add-AzureRmIotHubKey, Get-AzureRmIotHubEventHubConsumerGroup...
Script     3.1.2      AzureRM.IotHub                      {Add-AzureRmIotHubKey, Get-AzureRmIotHubEventHubConsumerGroup...
Script     5.0.3      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Update-AzureKeyVaultCertificat...
Script     4.3.0      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Set-AzureKeyVaultCertificateAt...
Script     4.0.5      AzureRM.LogicApp                    {Get-AzureRmIntegrationAccountAgreement, Get-AzureRmIntegrati...
Script     4.0.3      AzureRM.LogicApp                    {Get-AzureRmIntegrationAccountAgreement, Get-AzureRmIntegrati...
Script     0.18.1     AzureRM.MachineLearning             {Move-AzureRmMlCommitmentAssociation, Get-AzureRmMlCommitment...
Script     0.17.2     AzureRM.MachineLearning             {Move-AzureRmMlCommitmentAssociation, Get-AzureRmMlCommitment...
Script     0.4.4      AzureRM.MachineLearningCompute      {Get-AzureRmMlOpCluster, Get-AzureRmMlOpClusterKey, Test-Azur...
Script     0.4.2      AzureRM.MachineLearningCompute      {Get-AzureRmMlOpCluster, Get-AzureRmMlOpClusterKey, Test-Azur...
Script     0.2.3      AzureRM.MarketplaceOrdering         {Get-AzureRmMarketplaceTerms, Set-AzureRmMarketplaceTerms}      
Script     0.2.1      AzureRM.MarketplaceOrdering         {Get-AzureRmMarketplaceTerms, Set-AzureRmMarketplaceTerms}      
Script     0.10.0     AzureRM.Media                       {Sync-AzureRmMediaServiceStorageKeys, Set-AzureRmMediaService...
Script     0.9.2      AzureRM.Media                       {Sync-AzureRmMediaServiceStorageKeys, Set-AzureRmMediaService...
Script     6.3.0      AzureRM.Network                     {Add-AzureRmApplicationGatewayAuthenticationCertificate, Get-...
Script     5.4.2      AzureRM.Network                     {Add-AzureRmApplicationGatewayAuthenticationCertificate, Get-...
Script     5.0.1      AzureRM.NotificationHubs            {Get-AzureRmNotificationHub, Get-AzureRmNotificationHubAuthor...
Script     4.1.1      AzureRM.NotificationHubs            {Get-AzureRmNotificationHub, Get-AzureRmNotificationHubAuthor...
Script     5.0.2      AzureRM.OperationalInsights         {New-AzureRmOperationalInsightsAzureActivityLogDataSource, Ne...
Script     4.3.2      AzureRM.OperationalInsights         {New-AzureRmOperationalInsightsAzureActivityLogDataSource, Ne...
Script     1.0.2      AzureRM.PolicyInsights              {Get-AzureRmPolicyEvent, Get-AzureRmPolicyState, Get-AzureRmP...
Script     4.1.6      AzureRM.PowerBIEmbedded             {Remove-AzureRmPowerBIWorkspaceCollection, Get-AzureRmPowerBI...
Script     4.1.4      AzureRM.PowerBIEmbedded             {Remove-AzureRmPowerBIWorkspaceCollection, Get-AzureRmPowerBI...
Script     5.3.1      AzureRM.profile                     {Disable-AzureRmDataCollection, Disable-AzureRmContextAutosav...
Script     4.6.0      AzureRM.profile                     {Disable-AzureRmDataCollection, Disable-AzureRmContextAutosav...
Script     4.1.4      AzureRM.RecoveryServices            {Get-AzureRmRecoveryServicesBackupProperty, Get-AzureRmRecove...
Script     4.1.2      AzureRM.RecoveryServices            {Get-AzureRmRecoveryServicesBackupProperty, Get-AzureRmRecove...
Script     4.3.0      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRecoveryServicesBackupItem, Get-AzureRmRecover...
Script     4.1.2      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRecoveryServicesBackupItem, Get-AzureRmRecover...
Script     0.2.6      AzureRM.RecoveryServices.SiteRec... {Edit-AzureRmRecoveryServicesAsrRecoveryPlan, Get-AzureRmReco...
Script     0.2.4      AzureRM.RecoveryServices.SiteRec... {Edit-AzureRmRecoveryServicesAsrRecoveryPlan, Get-AzureRmReco...
Script     5.0.1      AzureRM.RedisCache                  {Remove-AzureRmRedisCachePatchSchedule, New-AzureRmRedisCache...
Script     4.1.2      AzureRM.RedisCache                  {Remove-AzureRmRedisCachePatchSchedule, New-AzureRmRedisCache...
Script     0.3.5      AzureRM.Relay                       {New-AzureRmRelayNamespace, Get-AzureRmRelayNamespace, Set-Az...
Script     0.3.3      AzureRM.Relay                       {New-AzureRmRelayNamespace, Get-AzureRmRelayNamespace, Set-Az...
Script     6.2.0      AzureRM.Resources                   {Get-AzureRmProviderOperation, Remove-AzureRmRoleAssignment, ...
Script     5.5.2      AzureRM.Resources                   {Get-AzureRmProviderOperation, Remove-AzureRmRoleAssignment, ...
Script     0.16.6     AzureRM.Scheduler                   {Disable-AzureRmSchedulerJobCollection, Enable-AzureRmSchedul...
Script     0.16.3     AzureRM.Scheduler                   {Disable-AzureRmSchedulerJobCollection, Enable-AzureRmSchedul...
Script     4.1.2      AzureRM.ServerManagement            {Invoke-AzureRmServerManagementPowerShellCommand, Get-AzureRm...
Script     0.6.6      AzureRM.ServiceBus                  {New-AzureRmServiceBusNamespace, Get-AzureRmServiceBusNamespa...
Script     0.6.4      AzureRM.ServiceBus                  {New-AzureRmServiceBusNamespace, Get-AzureRmServiceBusNamespa...
Script     0.3.7      AzureRM.ServiceFabric               {Add-AzureRmServiceFabricApplicationCertificate, Add-AzureRmS...
Script     0.3.4      AzureRM.ServiceFabric               {Add-AzureRmServiceFabricApplicationCertificate, Add-AzureRmS...
Script     5.0.6      AzureRM.SiteRecovery                {Get-AzureRmSiteRecoveryFabric, New-AzureRmSiteRecoveryFabric...
Script     4.9.0      AzureRM.Sql                         {Get-AzureRmSqlDatabaseTransparentDataEncryption, Get-AzureRm...
Script     4.4.0      AzureRM.Sql                         {Get-AzureRmSqlDatabaseTransparentDataEncryption, Get-AzureRm...
Script     5.0.0      AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, New...
Script     4.2.3      AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, New...
Script     4.0.6      AzureRM.StreamAnalytics             {Get-AzureRmStreamAnalyticsFunction, Get-AzureRmStreamAnalyti...
Script     4.0.4      AzureRM.StreamAnalytics             {Get-AzureRmStreamAnalyticsFunction, Get-AzureRmStreamAnalyti...
Script     4.0.3      AzureRM.Tags                        {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag}             
Script     4.0.1      AzureRM.Tags                        {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag}             
Script     4.0.7      AzureRM.TrafficManager              {Disable-AzureRmTrafficManagerEndpoint, Enable-AzureRmTraffic...
Script     4.0.3      AzureRM.TrafficManager              {Disable-AzureRmTrafficManagerEndpoint, Enable-AzureRmTraffic...
Script     4.0.3      AzureRM.UsageAggregates             Get-UsageAggregates                                             
Script     4.0.2      AzureRM.UsageAggregates             Get-UsageAggregates                                             
Script     5.0.4      AzureRM.Websites                    {Get-AzureRmAppServicePlan, Set-AzureRmAppServicePlan, New-Az...
Script     4.2.2      AzureRM.Websites                    {Get-AzureRmAppServicePlan, Set-AzureRmAppServicePlan, New-Az...

## Debug output

```

```

## Error output

```

```

**Comment by maddieclayton** [comment]
@jaredmoo Can you take a look at this issue?

**Comment by inuvano-labs** [comment]
Hi - is there any update on this issue? This is currently blocking us

**Comment by qiangwan** [comment]
The error is clear
In the New-AzureRmSqlSyncGroup, you need to specify -SyncDatabaseName.
The sync Db is per region per subscription.
So if you already has sync group\agent under a subscription in 1 region, you can not specify other DB as sync DB when you call this.
For example,
Sub A in eastus already has sync group using sync DB foo. Then when you create a new sync group in the same region under the same sub, you specify DB Bar in -SyncDatabaseName, 
you will get this error.

**Comment by inuvano-labs** [comment]
> The error is clear
> In the New-AzureRmSqlSyncGroup, you need to specify -SyncDatabaseName.
> The sync Db is per region per subscription.
> So if you already has sync group\agent under a subscription in 1 region, you can not specify other DB as sync DB when you call this.
> For example,
> Sub A in eastus already has sync group using sync DB foo. Then when you create a new sync group in the same region under the same sub, you specify DB Bar in -SyncDatabaseName,
> you will get this error.

Thanks for the clarification - but I wouldn't say the error was clear. Interesting design decision!

**Comment by dealaus** [comment]
@inuvano-labs Thanks for the feedback; we agree that the error message can be improved. We're going to change this error message to:

> A sync database already exists for this subscription in {region}. A subscription can only contain one sync database per region.

We believe this conveys the problem better, but please let us know if you have any additional comments on this update!
