### ISSUE TITLE
ARM: Add Sku parameter for Set-AzureResource and New-AzureResource

### ISSUE THREAD

**Issue by vivsriaus** [Azure/azure-powershell#859]
Expose -Sku parameter for Set-AzureResource and New-AzureResource cmdlets.

**Comment by davidebbo** [comment]
Without this support, we have to rely on the `-IsFullObject` mode, which while functional, is harder to use, e.g.

```PowerShell
Function CreateAppServicePlan($ResourceGroupName, $Location, $PlanName, $SkuName = "F1", $SkuTier = "Free")
{
    $fullObject = @{
        location = $Location
        sku = @{
            name = $SkuName
            tier = $SkuTier
        }
    }

    New-AzureResource -ResourceGroupName $ResourceGroupName -ResourceType Microsoft.Web/serverfarms -Name $PlanName -IsFullObject -PropertyObject $fullObject -OutputObjectFormat New -ApiVersion 2015-08-01 -Force
}
```

**Comment by pcgeek86** [comment]
The resource commands are supposed to be generic, right? Isn't "SKU" limited to features like VM images and App Service Web Apps?

**Comment by davidebbo** [comment]
It's generic. That's why it sits outside the Properties. Of course, in practice not all resource types support it, which is why it's optional.

**Comment by pcgeek86** [comment]
Right, so based on your statement, the parameter doesn't belong on the generic commands at all. The `-Sku` parameter should be added to the feature-specific PowerShell commands, to which it is applicable.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by davidebbo** [comment]
@pcgeek86 on the contrary: this is a generic pattern that can potentially be supported by any resource type. The whole point is to have a standard pattern for doing `sku` across any RP that needs it, and as such it absolutely belongs on `New-AzureResource`. In many ways, it's similar to `location`. There is a standard way to specify it, even if not all resource types support it.

Think of it this way: anything in ARM that doesn't go under `properties` is a not resource specific, and needs to be expressible via this CmdLet.

**Comment by pcgeek86** [comment]
@davidebbo Okay, well as long as it's intended to be a generic parameter. I just see very limited cases right now where the term "sku" is used. If that's going to become more standard, across Azure features, then it would be fine on here. The explanation about `-Location` was helpful, for me to see things from your perspective.

**Comment by stankovski** [comment]
Closing the issue

**Comment by davidebbo** [comment]
@stankovski I'm not clear on the resolution. Are you closing it because it is fixed? If so, can you please include the commit id? Thanks!

**Comment by stankovski** [comment]
@davidebbo - misread the thread and assumed there was no work to be done. Will re-open.

**Comment by ravbhatnagar** [comment]
This has been fixed. The param names seem to be different in both cmdlets #1808
