### ISSUE TITLE
[Az 1.3.0] Get-AzVMBootDiagnosticsData: LocalPath parameter doesn't make sense in the Linux parameter set

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#8601]
Get-AzVMBootDiagnosticsData has the Windows and Linux parameter sets.

`LocalPath` parameter doesn't make sense in the Linux parameter set, because the cmdlet is not saving anything to a disk when the `Linux` switch parameter is specified.

**Comment by markcowl** [comment]
@maddieclayton Can we get clarity on the requirements of the underlyign API? If the API for linux does not use the path, then this should be reflected in the parameter sets, if possible.

**Comment by hyonholee** [comment]
Cmdlet does save a log file of Linux VM to a local path.  It usually takes several minutes until the log file is stored in a blob storage.   This cmdlet copies the log file from a blob storage to a local path.   The parameter is optional for Linux VM.
