### ISSUE TITLE
[Az 1.3.0] Get-AzVMBootDiagnosticsData: Trailing "\" and other issues with the LocalPath parameter

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#8603]
The `LocalPath` parameter expect a trailing `\` to be specified. That's not the usual practice. People usually specify just `c:\somefolder`.

The way how the Get-AzVMBootDiagnosticsData deals with the exception is also inconsistent.

If you specify a folder at the root of the drive and forget to specify a trailing `\`, you get an error.
Looking at the path info, you can realize that the trailing `\` is missing.

```powershell
PS C:\> Get-AzVMBootDiagnosticsData -Windows -ResourceGroupName lab-rg -Name labvm -LocalPath c:\temp
Get-AzVMBootDiagnosticsData : Access to the path 'c:\tempLABVM.f47f6b1e-666a-4cce-a34a-841804566b08.screenshot.bmp' is denied.
```

If you specify a subfolder and forget to specify a trailing `\`, the command silently fails and you don't have a clue what happens. 

```powershell
PS C:\> Get-AzVMBootDiagnosticsData -Windows -ResourceGroupName lab-rg -Name labvm -LocalPath c:\temp\boot
```

Please, remove the requirement for the trailing `\` and return the file (.bmp image) object, so that the output could be piped to the Invoke-Item for example and open it in the associated image viewer.

**Comment by markcowl** [comment]
Yeah, wow, seems trivial for the cmdlet to normalize the path as required by the service.

@MaddieClayton Can we take a look at this, and fix or assign appropriately to the compute team?

**Comment by alexandair** [comment]
@maddieclayton Thank you.
