### ISSUE TITLE
Improve help docs and error checking with New-AzWebApp -IncludeSourceWebAppSlots parameter

### ISSUE THREAD

**Issue by Nking92** [Azure/azure-powershell#8614]
## Description of the new feature
Add an additional check when cloning a web app with the -IncludeSourceWebAppSlots parameter. The parameter will only work when cloning the main app, not a slot. We should give a helpful error message to the user before actually sending the clone request to ARM.

Issue originally reported at https://github.com/MicrosoftDocs/azure-docs/issues/23135

**Comment by panchagnula** [comment]
@Nking92 is this something we are still planning on supporting?

**Comment by panchagnula** [comment]
We might need to just update the doc here - stating this parameter is not supported with slots.
