### ISSUE TITLE
Set-AzureStorageBlobContent: Context not mentioned in documentation

### ISSUE THREAD

**Issue by DianeHadley** [Azure/azure-powershell#8626]
The documentation for Set-AzureStorageBlobContent (and maybe other cmdlets) shows how you can use the command without the -Context tag, but doesn't explain that this only works if the Context has already been set before calling this cmdlet. I think it would be helpful to users to explain somewhere in the documentation that the Context must always be given (whether it's with the Set-AzureRmCurrentStorageAccount cmdlet or the Context tag)

**Comment by cormacpayne** [comment]
@blueww Hey Wei, would you mind taking a look at this issue?

**Comment by blueww** [comment]
Set-AzureStorageBlobContent definitely need a storage context, or we don't know which storage account should the blob upload, and don't know the credential of storage account.  

But after you set a default storage Context with "Set-AzCurrentStorageAccount" cmdlet, you don't need to specify the storage context in every storage cmdelts. The default context will be use if no Storage context specified in the cmdlet.

in the description of help of  "Set-AzCurrentStorageAccount", you can see : "The Set-AzCurrentStorageAccount cmdlet modifies the current Azure Storage account of the specified Azure subscription in Azure PowerShell. The current Storage account is used as the default when you access Storage without specifying a Storage account name."

**Comment by blueww** [comment]
@DianeHadley 
Do you have further questions? 
Do you mind that I close the issue as the question is answered？ 
Feel free to contact us when you need assistance for the PowerShell storage cmdlets in the future.

**Comment by DianeHadley** [comment]
Sorry for delayed response. I understand that context needs to be set at some point; no way around that! I was just thinking that in the Set-AzureBlobContent documentation [here](https://docs.microsoft.com/en-us/powershell/module/azure.storage/set-azurestorageblobcontent?view=azurermps-6.13.0), it would be helpful to a reader if there was a note briefly explaining that if you don't use the context tag, you must have set the context previously. This note could go before the Examples section (since most of them don't use the context tag) or in the section explaining the context tag.
