### ISSUE TITLE
ARM PowerShell 0.9.7 :: Backup & Restore Azure SQL Database?

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#864]
Where are the PowerShell commands to backup and restore Azure SQL Databases?

![image](https://cloud.githubusercontent.com/assets/466713/9701068/3c761df0-53d7-11e5-8d74-76dcdb4402e7.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by stankovski** [comment]
@akromm - can you address the question?

**Comment by akromm** [comment]
Restore is: Restore-AzureRmSqlDatabase

Backups are taken automatically based on the service tier:
https://azure.microsoft.com/en-us/blog/azure-sql-database-built-in-backups-vs-importexport-2/ 
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-business-continuity

You can query backup information using the cmdlets found here:
https://github.com/Azure/azure-powershell/tree/dev/src/ResourceManager/Sql/Commands.Sql/Database%20Backup/Cmdlet
