### ISSUE TITLE
Az.StorageSync Remove KailaniAppId(s) from Cmdlet code

### ISSUE THREAD

**Issue by ankushbindlish2** [Azure/azure-powershell#8652]
## Description

Mark : Ideally, this should be discoverable via API. Failing that, this should be an extended property of the built-in environment, meaning that you can just get the value from the environment in the same way. For a preview this is OK, but please file an issue to either add a discovery API, or add this value to the built-in environment extensions

https://github.com/Azure/azure-powershell/pull/8646

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by markcowl** [comment]
Closing as duplicate of #8653

**Comment by ankushbindlish2** [comment]
https://github.com/Azure/azure-powershell/issues/8653
