### ISSUE TITLE
0.9.7 ARM :: Documentation for New-AzureRedisCache

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#866]
This needs to be explained in more depth. What other versions of `-RedisVersion` can the user specify? Under what circumstances would the user specify a different version? What features are supported by different versions? Missing a lot of detail.

![image](https://cloud.githubusercontent.com/assets/466713/9706224/b8f7c02a-549c-11e5-96a8-4b3d4e7abb1c.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by SiddharthChatrolaMs** [comment]
It will be fixed by https://github.com/Azure/azure-powershell/pull/919

**Comment by cormacpayne** [comment]
@pcgeek86 Hey Trevor, it appears that this parameter will be [deprecated in an upcoming release](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/RedisCache/Commands.RedisCache/Commands/NewAzureRedisCache.cs#L86), so I am going to close this issue 😄
