### ISSUE TITLE
Need a power shell command for the Advanced App Restart features for azure webapp/appservcie

### ISSUE THREAD

**Issue by neerajmehta2000** [Azure/azure-powershell#8685]

**Comment by cormacpayne** [comment]
@panchagnula Hey Sisira, does your team have any plans in the future to add this functionality to PowerShell?

**Comment by panchagnula** [comment]
we had no plans - this was always on supported on Portal using Kudu/Scm & command line tools have no support & so no timeline to share on supporting this.

**Comment by panchagnula** [comment]
Kudu APIs now have equivalent ARM calls so we can support these in the near future.

**Comment by panchagnula** [comment]
Don't have an ETA on this yet.

**Comment by panchagnula** [comment]
we are closing as won't fix for now. We are planning on having this equivalent feature support later - will share more details when we are ready.
