### ISSUE TITLE
the powershell cmdlet Get-AzWebAppMetrics failed with bad request

### ISSUE THREAD

**Issue by imeya** [Azure/azure-powershell#8716]
When I use the cmdlet Get-AzWebAppMetrics, it failed to execute with error message: Get-AzWebAppMetrics : Operation returned an invalid status code 'BadRequest'.
I don't know what's wrong with it. can you please let me know how to correct the error? Thanks.

![error-ps](https://user-images.githubusercontent.com/25738099/53936960-90f2d580-40e6-11e9-9eec-4d67cc81f260.JPG)

**Comment by cormacpayne** [comment]
@imeya thanks for filing this issue -- for issues with the `Az` module, we provide a template for users to fill out to give the Azure PowerShell team enough information to investigate the issue.

Below is the template that you should fill out in another comment:



## Description



## Steps to reproduce

```powershell

```

## Environment data



```

```

## Module versions



```powershell

```

## Debug output



```

```

## Error output



```

```

**Comment by imeya** [comment]
**Description**
Get-AzWebAppMetrics failed with bad request.

**Steps to reproduce**

open powershell prompt, input  Get-AzWebAppMetrics with correct parameters

**Environment data**

NA

**Module versions**
Az.Accounts    1.2.1
Az.Compute    1.2.0
Az.Monitor      1.0.0

**Debug output**
NA

**Error output**
Operation returned an invalid status code 'BadRequest'.

**Comment by imeya** [comment]
@cormacpayne , added. Thank you.

**Comment by vladimir-shcherbakov** [comment]
@imeya Could you please add the Debug Output as described on our issue template?
```
 Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block
```

**Comment by imeya** [comment]
@vladimir-shcherbakov , updated.

**Comment by markcowl** [comment]
@panchagnula This looks like a valid request in which the query parameters are incorrectly encoded.  Can you take  alook?

**Comment by panchagnula** [comment]
Please use this new API instead all metrics are now supported with this API only, webapps won't be supporting metrics anymore https://docs.microsoft.com/en-us/powershell/module/azurerm.insights/Get-AzureRmMetric?view=azurermps-6.13.0. I believe we have an outstanding issue to mark the webapps API deprecated

**Comment by imeya** [comment]
@panchagnula , the new api you mean get-AzureRmMetric? 
and could you please point out which issue to mark the webapps API deprecated? Thanks.

**Comment by panchagnula** [comment]
@imeya there was GitHub issue tracking this change - here is the issue i created to track the change https://github.com/Azure/azure-powershell/issues/8975
