### ISSUE TITLE
ARM: Set-AzureVMExtension parameter confusion

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-powershell#873]
What is the difference between "-Name" and "-ExtensionType"?
Could the value of "-Name" be arbitrary?
```
Set-AzureVMExtension -ResourceGroupName $RGName -VMName $VmName -Location $Location 
  -Name $ExtensionName -Publisher $Publisher -ExtensionType $ExtensionName 
  -TypeHandlerVersion $Version -Settingstring $PublicConf -ProtectedSettingString $PrivateConf
```

**Comment by huangpf** [comment]
Given the premise that every Azure PS cmdlet is calling its REST API counterpart, let's refer to the VM resource extension REST API documentation: https://msdn.microsoft.com/en-us/library/azure/mt163624.aspx

The ```Name``` parameter means the name of the extension (which is a sub resource of a VM), and the ```ExtensionType``` parameter means the type of the extension, which can be found using the following query cmdlet:

```
PS C:\> get-command *azure*extension*type*

CommandType     Name                                               ModuleName
-----------     ----                                               ----------
Cmdlet          Get-AzureVMExtensionImageType                      AzureResourceManager
```

**Comment by bingosummer** [comment]
Thanks
