### ISSUE TITLE
functionapp:I need to create Python Azure Function using Az PowerShell

### ISSUE THREAD

**Issue by sachidanand** [Azure/azure-powershell#8739]
Hi,
  I need to create Python Azure Function using AZ PowerShell command. So could you please let me know which command it this.
The AZ Command I am using is below, but I need a Az PowerShell Command for This
az functionapp createpreviewapp -n buhler-uat-we-snapit-diehole-algorithm -g buhler-uat-snapit-dieholealgorithm -l ""westeurope"" -s buhleruatsnapitalgo --runtime python --is-linux

**Comment by markcowl** [comment]
@sphibss @sisrap Can you please respond about Functions support in Azure PowerShell?

**Comment by panchagnula** [comment]
@ahmedelnably - can help you here.

**Comment by dcaro** [comment]
@sachidanand we have published couple of weeks ago a first preview of the Az.Functions module for PowerShell. Please give it a try and let us know what you think.
`Install-Module -Name Az.Functions -AllowPrerelease`

**Comment by dingmeng-xue** [comment]
Close it because of new Az.Functions module

**Comment by dcaro** [comment]
Hi @sachidanand 

The Azure PowerShell product team is looking for customers who are willing to try some of the newest Azure PowerShell features for Azure Functions and provide feedback.

If you are interested in talking with Azure PowerShell product team on this topic, fill out this short survey (https://microsoft.qualtrics.com/jfe/form/SV_0PATZ9XFWS8S82V?Q_CHL=github) and include your email at the end. We will contact you to set up a Teams call if you are a good fit for this study.

Thank you!
Damien
