### ISSUE TITLE
Exception calling Get-AzureSiteRecoveryProtectionEntity

### ISSUE THREAD

**Issue by davebrannan** [Azure/azure-powershell#874]
Running "Get-AzureSiteRecoveryProtectionEntity -ProtectionContainer $ProtectionContainer" produces an exception if the ReplicationProvider in the profile of the ProtectionContainer is not HyperVReplicaAzure.

Exception:
Get-AzureSiteRecoveryProtectionEntity : Operation failed.
ClientRequestId: 14063df6-dea8-433e-9e9f-545e3e13a661-2015-09-09 09:12:41Z-P
InvalidParameter: <Error xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/Microsoft.Azure.SiteRecovery.Base">
  <ActivityId>ada318bd-4bb5-4d35-9ebb-714940405ba2</ActivityId>
  <Code>InvalidParameter</Code>
  <Message>An invalid parameter ReplicationProvider was passed.</Message>
  <PossibleCauses>Parameter value is not correct for this action.</PossibleCauses>
  <RecommendedAction>Correct the parameter value and retry the last action. If the issue persists, contact Support.</RecommendedAction>
</Error>

**Comment by stankovski** [comment]
@sriramvu please take a look

**Comment by sriramvu** [comment]
@davebrannan: Hi, our service handles either HyperVReplicaAzure or HyperVReplica as ReplicationProvider in the profile of the ProtectionContainer (RDFE / Azure module based cmdlets).
Can you please share the value of ReplicationProvider in the profile you are referring.

Thank you.

**Comment by davebrannan** [comment]
Hi @sriramvu . The ReplicationProvider of the ProtectionContainer is currently "Other". This is from a VMWare environment but I've also hit this error in a VMM deployment

**Comment by sriramvu** [comment]
As of today. Azure Site Recovery service supports HyperVReplica & HyperVReplicaAzure via RDFE PowerShell.
We should not see the same error with VMM deployment, can you please share the ClientRequestId to debug further.

**Comment by davebrannan** [comment]
The last ClientRequestId I received is ClientRequestId: 33672c01-1efe-4624-b0e4-048dd3d46e4e-2015-09-10 09:27:53Z-P

**Comment by darrenchuang** [comment]
I got the same error with Get-AzureSiteRecoveryProtectionEntity execution. Is there a plan to support VMWare and physical server deployment?

**Comment by sriramvu** [comment]
@davebrannan: from logs (with ClientRequestId: 33672c01-1efe-4624-b0e4-048dd3d46e4e-2015-09-10 09:27:53Z-P), it seems that you are using "VMWare to Azure" technology.
Currently we are support following via RDFE /ASM based cmdlets:
* VMM to VMM
* VMM to Azure
* Hyper-V to Azure

**Comment by sriramvu** [comment]
@darrenchuang: support to VMWare and physical server deployments are in our current backlog. We will be supporting them, will share the dates once they are finalized.

Thank you.

**Comment by davebrannan** [comment]
@sriramvu Correct, this is from VMWare. If RDFE only supports VMM and HyperV currently does this mean that there is no alternative method for getting this data? Or is there a REST API we can call to get this data until you support it via the cmdlets?

**Comment by sriramvu** [comment]
As for current public REST APIs / PowerShell, we have not added support for VMWare to Azure technology. We have plan to support VMWare and physical server deployments. 
Thanks for showing interest.

**Comment by sriramvu** [comment]
Can we close this issue? or let us know if anything else is needed.

**Comment by davebrannan** [comment]
Well we can't achieve the automation we need without the VMWare/Physical server support, but as it's known and on your roadmap it can be closed. Be nice to know when this might be available though?

**Comment by sriramvu** [comment]
most probably by Q1 CY16.

**Comment by ubjones** [comment]
This issue may have been closed, but it is still an issue.  Microsoft supports [VMware replication](https://azure.microsoft.com/en-us/documentation/articles/site-recovery-vmware-to-azure-classic) so the Azure powershell automation must support it.
