### ISSUE TITLE
New-AzPolicyDefinition Metadata parameter not functional

### ISSUE THREAD

**Issue by felickz** [Azure/azure-powershell#8746]
## Description
The **New-AzPolicyDefinition** _Metadata_ parameter is not functional.  Setting the value as per examples does not show in the portal, powershell output, or powershell GET commands.  (same issue on AzureRM module).  Viewing DEBUG output from powershell command shows the metadata properly set in request and response.

[Example 4](https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azpolicydefinition?view=azps-1.4.0#examples) ( git - [Example 4](https://github.com/Azure/azure-powershell/blob/master/src/Resources/Resources/help/New-AzPolicyDefinition.md) )

## Steps to reproduce

```powershell
PS C:\> New-AzPolicyDefinition -Name 'VMPolicyDefinition' -Metadata '{"Category":"Virtual Machine"}' -Policy '{"if":{"source":"action","equals":"Microsoft.Compute/virtualMachines/write"},"then":{"effect":"deny"}}'

Get-AzPolicyDefinition -Name VMPolicyDefinition

```
BOTH output and return objects contain no metadata / category:

> Name               : VMPolicyDefinition
> ResourceId         : /subscriptions/11111111-1111-1111-1111-111111111111/providers/Microsoft.Authorization/policyDefinitions/VMPolicyDefinition
> ResourceName       : VMPolicyDefinition
> ResourceType       : Microsoft.Authorization/policyDefinitions
> SubscriptionId     : 11111111-1111-1111-1111-111111111111
> Properties         : @{displayName=VMPolicyDefinition; policyType=Custom; mode=All; **metadata=;** policyRule=}
> PolicyDefinitionId : /subscriptions/11111111-1111-1111-1111-111111111111/providers/Microsoft.Authorization/policyDefinitions/VMPolicyDefinition

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.3.0      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enab...
Script     1.0.1      Az.Aks                              {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredentia...
Script     1.0.0      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServic...
Script     1.0.0      Az.ApiManagement                    {Add-AzApiManagementRegion, Get-AzApiManagementSsoToken, N...
Script     1.0.0      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Rem...
Script     1.1.0      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHyb...
Script     1.0.0      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAcc...
Script     1.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollme...
Script     1.0.1      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfil...
Script     1.0.0      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAc...
Script     1.3.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAv...
Script     1.0.0      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzCont...
Script     1.0.1      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-...
Script     1.0.1      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFa...
Script     1.0.0      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalytic...
Script     1.0.2      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeSt...
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolic...
Script     1.0.0      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRe...
Script     1.1.0      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGr...
Script     1.0.0      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzE...
Script     1.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wa...
Script     1.0.2      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-A...
Script     1.0.1      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, ...
Script     1.1.0      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccou...
Script     1.0.0      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssocia...
Script     1.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.0.0      Az.Media                            {Sync-AzMediaServiceStorageKeys, Set-AzMediaServiceKey, Ge...
Script     1.0.0      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile...
Script     1.1.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-Az...
Script     1.0.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorization...
Script     1.0.0      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-...
Script     1.0.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSu...
Script     1.0.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspa...
Script     1.0.0      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServi...
Script     1.0.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheSchedul...
Script     1.0.0      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNa...
Script     1.1.2      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzR...
Script     1.0.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set...
Script     1.0.1      Az.ServiceFabric                    {Add-AzServiceFabricApplicationCertificate, Add-AzServiceF...
Script     1.0.2      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSig...
Script     1.2.0      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlData...
Script     1.0.2      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStor...
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefau...
Script     1.0.1      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTraf...
Script     1.1.0      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServ...


```

## Debug output

```
```

> 
> DEBUG: ============================ HTTP REQUEST ============================
> 
> HTTP Method:
> PUT
> 
> Absolute Uri:
> https://management.azure.com/subscriptions/REDACTED/providers/Microsoft.Authorization/polic
> ydefinitions/VMPolicyDefinition?api-version=2018-05-01
> 
> Headers:
> User-Agent                    : PSVersion/v5.1.17763.316,AzurePowershell/v1.0.0
> ParameterSetName              : NameParameterSet
> CommandName                   : New-AzPolicyDefinition
> 
> Body:
> {
>   "name": "VMPolicyDefinition",
>   "properties": {
>     "policyRule": {
>       "if": {
>         "source": "action",
>         "equals": "Microsoft.Compute/virtualMachines/write"
>       },
>       "then": {
>         "effect": "deny"
>       }
>     },
>     "metadata": {
>       **"Category": "Virtual Machine"**
>     },
>     "mode": "All"
>   }
> }
> 
> DEBUG: ============================ HTTP RESPONSE ============================
> 
> Status Code:
> Created
> 
> Headers:
> Pragma                        : no-cache
> x-ms-request-id               : centralus:REDACTED
> x-ms-ratelimit-remaining-subscription-writes: 1199
> x-ms-correlation-request-id   : REDACTED
> x-ms-routing-request-id       : CENTRALUS:20190312T033605Z:REDACTED
> Strict-Transport-Security     : max-age=31536000; includeSubDomains
> X-Content-Type-Options        : nosniff
> Cache-Control                 : no-cache
> Date                          : Tue, 12 Mar 2019 03:36:04 GMT
> 
> Body:
> {
>   "properties": {
>     "policyType": "Custom",
>     "mode": "All",
>     "metadata": {
>       **"Category": "Virtual Machine",**
>       "createdBy": "REDACTED",
>       "createdOn": "2019-03-12T03:24:05.6521066Z",
>       "updatedBy": "REDACTED",
>       "updatedOn": "2019-03-12T03:36:05.4762484Z"
>     },
>     "policyRule": {
>       "if": {
>         "source": "action",
>         "equals": "Microsoft.Compute/virtualMachines/write"
>       },
>       "then": {
>         "effect": "deny"
>       }
>     }
>   },
>   "id":
> "/subscriptions/REDACTED/providers/Microsoft.Authorization/policyDefinitions/VMPolicyDefini
> tion",
>   "type": "Microsoft.Authorization/policyDefinitions",
>   "name": "VMPolicyDefinition"
> }
> 

## Error output

No Errors .. need to update Az template to be Resolve-AzError :)

```
PS > Resolve-AzureRmError
Resolve-AzureRmError : Method 'get_SerializationSettings' in type
'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly
'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
does not have an implementation.
At line:1 char:1
+ Resolve-AzureRmError
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Resolve-AzureRmError], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.Azure.Commands.Profile.Errors.ResolveError

```

**Comment by vladimir-shcherbakov** [comment]
@ravbhatnagar  Could you take a look?

**Comment by aperezcloud** [comment]
By design the metadata parameter is not supported today. Please feel free to add a request for this feature to our UserVoice page (https://feedback.azure.com/forums/915958-azure-governance), it will help us prioritize our work on the next features to support. Thanks!
