### ISSUE TITLE
[1.5.0] With the added support for the wildcards, help info for parameters needs an update too

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#8765]
In 1.5.0 wildcard support was added for the Get cmdlets in Az.Compute and Az.Network.
"Accept wildcard characters" property for the parameters in the help files needs to update from `False` to `True`.

**Comment by maddieclayton** [comment]
@alexandair Thanks for pointing this out - I will work on getting this in for the next release.

**Comment by maddieclayton** [comment]
Hey @alexandair - Just wanted to let you know that I've had a bit of a setback here due to a bug in platyPS: https://github.com/PowerShell/platyPS/issues/202. Hoping to take a look at the platyPS bug later this release, and get the docs properly updated after that.

**Comment by alexandair** [comment]
@maddieclayton Good luck with that. That bug is known for more than 2 and a half years, and no one cared enough to fix it. People will surely appreciate your work.

**Comment by markcowl** [comment]
@joeyaiello Any chance we can prioritze this fix for platyPS? https://github.com/PowerShell/platyPS/issues/202

**Comment by maddieclayton** [comment]
This is fixed here: https://github.com/Azure/azure-powershell/pull/9016 with a private copy of platyPS, and the fix will be released in platyPS on Friday (PR here: https://github.com/PowerShell/platyPS/pull/462)
