### ISSUE TITLE
Az.StorageSync Test project should not reference Az.Storage project

### ISSUE THREAD

**Issue by blueww** [Azure/azure-powershell#8767]
## Description
Currently, Az.StorageSync Test project references Az.Storage project. This takes issue in SDK upgrade of Az.Storage, like following 2 PRs, and will continually take issue in the future.

https://github.com/Azure/azure-powershell/pull/8624
>  Detected package downgrade: System.Reflection.TypeExtensions from 4.5.0 to 4.3.0. 

https://github.com/Azure/azure-powershell/pull/8748 
>  Detected package downgrade: Microsoft.Azure.Management.Storage from 10.0.0 to 9.1.0-preview. 

So it's must to remove the reference of storage project from StorageSync Test, or it will take trouble for upgrade library in Storage module in the future, and takes additional cost to both storageSync and Storage.

To remove Storage module reference in test project, refer this compute test for how to create Storage Account and handle Blob (File should be similar) without refer storage module.

- For handle Storage account, you can use the functions in https://github.com/Azure/azure-powershell/blob/master/tools/ScenarioTest.ResourceManager/AzureRM.Storage.ps1 
- You can write your own function to create File with the storage credential, similar to: https://github.com/Azure/azure-powershell/blob/d5c8d0e6116c5d82ba14a09d888beaec67f473b7/src/Compute/Compute.Test/ScenarioTests/AddVhdTests.ps1#L92

**Comment by sphibbs** [comment]
Will fix in generated

**Comment by blueww** [comment]
@sphibbs 
Would  you please share how the fix is?

Actually, I have to manually fix the Az.StorageSync Test in recent several release, as we upgrade the SDK version in Az.Storage.
Hope we don't need to do this in the future release.
