### ISSUE TITLE
Get-AzRoleDefinition Returns Role Definition after Role has been Removed

### ISSUE THREAD

**Issue by berridgd** [Azure/azure-powershell#8787]
## Description
When deleting a role in azure and then immediately running Get-AzRoleDefinition the role definition is returned. This can be an issue if you want to first see if a role exists prior to setting any role assignments because if the role is deleted and the role definition is returned with the old role Id you can end up attempting to perform a role assignment on a non-existent role.

There is a similar issue opened for this in the azure-cli repo.  #https://github.com/Azure/azure-cli/issues/3187.

## Steps to reproduce

$file is the json file used to create the role

```powershell
For ($i = 0; $i -lt 10; $i++){
	$role = New-AzRoleDefinition -role $file
	$retrievedRole = Get-AzRoleDefinition -Name $file.Name
	if($retrievedRole){
		if($retrievedRole.Id -ne $role.Id){
			Write-Warning "Id of created role $($role.Id) does not match id of retrieved role definition $($retrievedRole.Id)!"
		}else{
			Write-Host "Successfully created and found role!"
		}
	}else{
		Write-Warning "Could not find role after creation!"
	}
	Remove-AzRoleDefinition -Id $role.id -Force
	$retrievedRole = Get-AzRoleDefinition -Name $file.Name
	if($retrievedRole){
		Write-Warning "Role was deleted but role definition was retrieved!"
		if($retrievedRole.Id -ne $role.Id){
			Write-Warning "Id of created role $($role.Id) does not match id of retrieved role definition $($retrievedRole.Id)!"
		}
	}else{
		Write-Host "Role deleted!"
	}
}
```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by vladimir-shcherbakov** [comment]
@darshanhs90 Could you please take a look?

**Comment by darshanhs90** [comment]
@vladimir-shcherbakov Custom roles are cached, due to that you will be seeing that in the Get-Azroledefinition results.
If you log out and login ,the cache should become expired and you should no longer be seeing the deleted role in the result
