### ISSUE TITLE
Enable-AzureRmAlias doesn't work 

### ISSUE THREAD

**Issue by EZhao-Quest** [Azure/azure-powershell#8795]
Enable-AzureRmAlias doesn't work , when I create a powershell class,  I have a AzureRm Call in the class, I want to Enable-AzureRmAlias , but always told me the  : The term 'Get-AzureRmResourceLock' is not recognized as the name of a cmdlet, function, script file, or operable program.

**Comment by vladimir-shcherbakov** [comment]
@EZhao-Quest Please do not ignore the issue entry form - data requested in the form is very important for identifying the issue. I'll add the form in the next comment - feel free to click on the `Edit` menu and fill out the form.

**Comment by vladimir-shcherbakov** [comment]
## Description



## Steps to reproduce

```powershell

```

## Module versions



```powershell

```

## Debug output



```

```

## Error output



```

```

**Comment by maddieclayton** [comment]
@EZhao-Quest Ping on the comment above.

**Comment by markcowl** [comment]
Closing for lack of comment
