### ISSUE TITLE
[ApiManagement] Missing Example showing how to add an operation to ApiRevision

### ISSUE THREAD

**Issue by solankisamir** [Azure/azure-powershell#8802]
## Description
We are missing an example showing how the customer can use New-AzApiManagementOperation to add operation to a Revision
https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/New-AzApiManagementOperation?view=azps-1.5.0#examples

**Comment by markcowl** [comment]
@solankisamir Can you put this issue into the milestone you plan to fix it in (or backlog if not in the next 4 milestones)

**Comment by solankisamir** [comment]
[package](https://www.powershellgallery.com/packages/Az/2.1.0)
[documentation](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/?view=azps-2.1.0#api_management)
[releasenotes](https://github.com/Azure/azure-powershell/releases/tag/v2.1.0-May2019)
