### ISSUE TITLE
Missing "subscription required" flag for import/set api management api calls

### ISSUE THREAD

**Issue by laurencee** [Azure/azure-powershell#8807]
## Description

None of the API Management powershell cmdlets expose a way to set the "subscription required" flag for an API. 

Everytime you import/set the api it will overwrite the flag back to the "true" state.

These were the cmdlet tested:

`Import-AzureRmApiManagementApi`
`Import-AzApiManagementApi`
`Set-AzureRmApiManagementApi`
`Set-AzApiManagementApi`

## Steps to reproduce

1. Import an API to Azure API Management either manually or using one of the above Import commands 
2. Go to the portal and untick the subscription required flag on the API
3. Run the import command again

The subscription required flag is now turned back on

## Module versions

```powershell
ModuleType Version    Name                                PSEdition 
---------- -------    ----                                --------- 
Script     6.13.1     AzureRM                             Desk      
Script     6.1.7      AzureRM.ApiManagement               Desk      
```

## Flag in Azure portal

![image](https://user-images.githubusercontent.com/3850553/54658779-e4b7e280-4b1a-11e9-8725-8f5bbb6caec6.png)

**Comment by vladimir-shcherbakov** [comment]
@laurencee 
The AzureRM cmdlets are no longer in active development, so you may want to try Az cmdlets first. 
If Az cmdlets don't work for you - please fill out the `Az module bug report` entry form that helps us to investigate the issue:


## Description



## Steps to reproduce

```powershell

```

## Environment data



```

```

## Module versions



```powershell

```

## Debug output



```

```

## Error output



```

```

**Comment by laurencee** [comment]
@vladimir-shcherbakov My bug report includes the az commands, neither az or azurerm include this flag.

**Comment by maddieclayton** [comment]
@solankisamir Can you take a look at this issue?

**Comment by solankisamir** [comment]
The [subscription required](https://github.com/solankisamir/azure-rest-api-specs/blob/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2018-06-01-preview/apimapis.json#L4773) flag was introduced in API version `2018-06-01-preview`. The PowerShell cmdlets target API version `2018-01-01`. When we move to a newer .NET version for PowerShell, which supports `2019-01-01` API version, we will add support for it.

**Comment by guileinsighter** [comment]
@solankisamir,

Would you please point out where in the  `2018-06-01-preview` is the flag located?

**Comment by solankisamir** [comment]
@guileinsighter it got moved to [definitions](https://github.com/solankisamir/azure-rest-api-specs/blob/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2018-06-01-preview/definitions.json#L346)

For Documentation check [here](https://docs.microsoft.com/en-us/rest/api/apimanagement/apis/createorupdate#request-body)

**Comment by guileinsighter** [comment]
> @guileinsighter it got moved to [definitions](https://github.com/solankisamir/azure-rest-api-specs/blob/master/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2018-06-01-preview/definitions.json#L346)
> 
> For Documentation check [here](https://docs.microsoft.com/en-us/rest/api/apimanagement/apis/createorupdate#request-body)

Brilliant! Thanks a lot, @solankisamir

**Comment by tkaniewski** [comment]
-SubscriptionRequired parameter is not avaiable in Import-AzApiManagementApi function. Also this parameter is SwitchParameter not Boolean so how can I change the existing API settings to false? 

https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/set-azapimanagementapi?view=azps-4.7.0

**Comment by tkaniewski** [comment]
Even if I run
```
New-AzApiManagementApi -Context $context `
    -Name "FakeName" `
    -ServiceUrl "https://fakefakeurl" `
    -Protocols @("https") `
    -Path $apiPath `
    -ApiId $functionName
```
Subscription required is checked:

![image](https://user-images.githubusercontent.com/66473456/95342168-6a46e300-08b7-11eb-8ae3-d7af9b6bd053.png)
