### ISSUE TITLE
Update Migration Guide for Storage Table cmdlets output type change 

### ISSUE THREAD

**Issue by blueww** [Azure/azure-powershell#8808]
## Description
In the upcoming release ( Az 1.6.0) , Az.Storage module (Az.Storage 1.1.0) Table cmdlets output Type will change, so some customer script need change the name space: 
From `Microsoft.WindowsAzure.Storage.Table`
To `Microsoft.Azure.Cosmos.Table`

Open this issue for provide resolution for potential issue in upcoming Azure Powershell release. 

## Steps to reproduce

```powershell
#get table object with Storage cmdlets
$table =Get-AzStorageTable -Name $tableName -Context $storageContext

#Insert Entities to Table
$entity = New-Object -TypeName Microsoft.WindowsAzure.Storage.Table.DynamicTableEntity -ArgumentList $partitionKey, $rowKey
$entity.Properties.Add("Name", "name1")
$entity.Properties.Add("ID", 4567)
$result = $table.CloudTable.ExecuteAsync([Microsoft.WindowsAzure.Storage.Table.TableOperation]::Insert($entity))

# Query Table
$query = New-Object Microsoft.WindowsAzure.Storage.Table.TableQuery
## Define columns to select.
$list = New-Object System.Collections.Generic.List[string]
$list.Add("RowKey")
$list.Add("ID")
$list.Add("Name")
## Set query details.
$query.SelectColumns = $list
$result = $table.CloudTable.ExecuteQuerySegmentedAsync(($query, $null)

```

## Environment data

```
All Powershell version
```

## Module versions

```powershell
Az.Storage 1.1.0
```

## Debug output

```
N/A
```

## Error output

```
 $result = $table.CloudTable.ExecuteAsync([Microsoft.WindowsAzure.Storage.Table.TableOperation]::Insert($entity))
Cannot find an overload for "ExecuteAsync" and the argument count: "1".
At line:1 char:1
+ $result = $table.CloudTable.ExecuteAsync([Microsoft.WindowsAzure.Stor ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
 

$result = $table.CloudTable.ExecuteQuerySegmentedAsync($query, $null)
Cannot find an overload for "ExecuteQuerySegmentedAsync" and the argument count: "2".
At line:1 char:1
+ $result = $table.CloudTable.ExecuteQuerySegmentedAsync($query, $null)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
```

**Comment by blueww** [comment]
The issue is caused by with upgrade Storage Client Library from 9.3.* to 9.4.2, table is removed from Storage Client Library, and Powershell need Manage Table with "Microsoft.Azure.Cosmos.Table" library.

The resolution is change all the object namespace 
From `Microsoft.WindowsAzure.Storage.Table`
To `Microsoft.Azure.Cosmos.Table`

Like following script worked with Az.Storage 1.1.0:
```powershell
#get table object with Storage cmdlets
$table =Get-AzStorageTable -Name $tableName -Context $storageContext

###Insert Entities to Table
$entity = New-Object -TypeName Microsoft.Azure.Cosmos.Table.DynamicTableEntity -ArgumentList $partitionKey, $rowKey
$entity.Properties.Add("Name", "name1")
$entity.Properties.Add("ID", 4567)
$result = $table.CloudTable.ExecuteAsync([Microsoft.Azure.Cosmos.Table.TableOperation]::Insert($entity))

# Query Table
$query = New-Object Microsoft.Azure.Cosmos.Table.TableQuery
## Define columns to select.
$list = New-Object System.Collections.Generic.List[string]
$list.Add("RowKey")
$list.Add("ID")
$list.Add("Name")
## Set query details.
$query.SelectColumns = $list
$result = $table.CloudTable.ExecuteQuerySegmentedAsync($query, $null)
```

**Comment by markcowl** [comment]
@blueww The ask from us here is to update the migration guide to include this information as part of your PR, as well as putting this in release notes and changelog:  https://github.com/Azure/azure-powershell/blob/master/documentation/migration-guides/Az.1.0.0-migration-guide.md

**Comment by blueww** [comment]
@markcowl 

This issue is opened by me to track the namespace change of Table.

How could we change the release note for this?
The link you send it for Az.1.0.0, should we just update this link, or add one for the new Az.1.6.0?
Will someone from your team help to update the doc, or should I update the doc? 

For change log, I have added the following line to it. Should we also add the namespace sample code to it?
>Upgrade to Storage Client Library 9.4.2 and Microsoft.Azure.Cosmos.Table 0.10.1-preview
