### ISSUE TITLE
get-azsubscription returns no results

### ISSUE THREAD

**Issue by bholzmmc** [Azure/azure-powershell#8810]
Running Powershell as Adminstrator, using Azure account with Global Administrator role, successfully Connect-AzAccount but Get-AzSubscription returns to the command prompt with no results and no error messages.  Running with -debug does not seem to incur any errors.  In Azure portal there at least 15 on the License -Overiew -> Products page.

**Comment by vladimir-shcherbakov** [comment]
@bholzmmc Please fill out  the `Az module bug report` form to help us investigate the issue. Fill free to click `Edit` and fill out the form bellow:



## Description



## Steps to reproduce

```powershell

```

## Environment data



```

```

## Module versions



```powershell

```

## Debug output



```

```

## Error output



```

```

**Comment by bholzmmc** [comment]
**Description**
get-azsubscription returns no results

**Steps to reproduce**
connect-azaccount
get-subscription

**Environment data**
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value                                                                       
----                           -----                                                                       
PSVersion                      5.1.14393.2636                                                              
PSEdition                      Desktop                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                     
BuildVersion                   10.0.14393.2636                                                             
CLRVersion                     4.0.30319.42000                                                             
WSManStackVersion              3.0                                                                         
PSRemotingProtocolVersion      2.3                                                                         
SerializationVersion           1.1.0.1 


Module versions
ame              : Az.Accounts
Path              : C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\1.4.0\Az.Accounts.psm1
Description       : Microsoft Azure PowerShell - Accounts credential management cmdlets for Azure Resource 
                    Manager in Windows PowerShell and PowerShell Core.
                    
                    For more information on account credential management, please visit the following: 
                    https://docs.microsoft.com/powershell/azure/authenticate-azureps
ModuleType        : Script
Version           : 1.4.0

**Debug output**
DEBUG: 4:55:49 PM - GetAzureRMSubscriptionCommand begin processing with ParameterSet 'ListByIdInTenant'.
DEBUG: 4:55:51 PM - using account id 'an account'...
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'an id', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945f
c2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/',
 ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.
com/....../', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateA
uthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '.....', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '....', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 3/21/2019 8:55:51 PM: ...... - AcquireTokenHandler
Base.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/...../
	Resource: https://management.core.windows.net/
	ClientId: ....an_id....
	CacheType: null
	Authentication Target: User
	

DEBUG: [ADAL]: Information: 3/21/2019 8:55:51 PM:  - TokenCache.cs: Deserialized 1 items to token cache.

DEBUG: [ADAL]: Verbose: 3/21/2019 8:55:51 PM: ...an_id... - TokenCache.cs: Looking 
up cache for a token...

DEBUG: [ADAL]: Information: 3/21/2019 8:55:51 PM: ...an_id... - TokenCache.cs: An i
tem matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 3/21/2019 8:55:51 PM: ...an_id... - TokenCache.cs: 47.0
039237416667 minutes left until token in cache expires

DEBUG: [ADAL]: Information: 3/21/2019 8:55:51 PM: ....an_id... - TokenCache.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Information: 3/21/2019 8:55:51 PM: ...an_id... - AcquireTokenHandler
Base.cs: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: 67P2KecLjaGgSMX2sC6YikUKEpUJLDUNE1VkKfd2TaY=
	Expiration Time: 3/21/2019 9:42:51 PM +00:00
	User Hash: VKLtW/8Lic5thbithG4PH228X7Gk9VhNF9w0fvVM/Xs=
	

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/tenants?api-version=2016-06-01

Headers:
x-ms-client-request-id        : 7b0be47a-8d5f-4c96-91d5-2f0f97d89a97
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-tenant-reads: 11999
x-ms-request-id               : e2dccad5-cc00-4884-9106-7a41e6f8d121
x-ms-correlation-request-id   : e2dccad5-cc00-4884-9106-7a41e6f8d121
x-ms-routing-request-id       : SOUTHCENTRALUS:20190321T205552Z:e2dccad5-cc00-4884-9106-7a41e6f8d121
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 21 Mar 2019 20:55:51 GMT

Body:
{
  "value": [
    {
      "id": "/tenants/...tenant_id....",
      "tenantId": "...tenant_id...."
    }
  ]
}


DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '...an_id...', Endpoint: 'https://login.microsoftonline.com/', ClientId: '...an_id...', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/',
 ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.
com/....an_id..../', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateA
uthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '...an_id...', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '...an_id...', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 3/21/2019 8:55:52 PM: ...an_id... - AcquireTokenHandler
Base.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/...an_id.../
	Resource: https://management.core.windows.net/
	ClientId: ...an_id...
	CacheType: null
	Authentication Target: User
	

DEBUG: [ADAL]: Information: 3/21/2019 8:55:52 PM:  - TokenCache.cs: Deserialized 1 items to token cache.

DEBUG: [ADAL]: Verbose: 3/21/2019 8:55:52 PM: ...an_id... - TokenCache.cs: Looking 
up cache for a token...

DEBUG: [ADAL]: Information: 3/21/2019 8:55:52 PM: ...an_id... - TokenCache.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 3/21/2019 8:55:52 PM: ...an_id...- TokenCache.cs: 46.9
931457883333 minutes left until token in cache expires

DEBUG: [ADAL]: Information: 3/21/2019 8:55:52 PM: ...an_id... - TokenCache.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Information: 3/21/2019 8:55:52 PM: ...an_id... - AcquireTokenHandler
Base.cs: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: 67P2KecLjaGgSMX2sC6YikUKEpUJLDUNE1VkKfd2TaY=
	Expiration Time: 3/21/2019 9:42:51 PM +00:00
	User Hash: VKLtW/8Lic5thbithG4PH228X7Gk9VhNF9w0fvVM/Xs=
	

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions?api-version=2016-06-01

Headers:
x-ms-client-request-id        : 90d23073-da06-4df8-b3e6-7fad38445432
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-tenant-reads: 11999
x-ms-request-id               : 107ec75d-cb82-406e-a0a7-699ac2fea4ab
x-ms-correlation-request-id   : 107ec75d-cb82-406e-a0a7-699ac2fea4ab
x-ms-routing-request-id       : SOUTHCENTRALUS:20190321T205552Z:107ec75d-cb82-406e-a0a7-699ac2fea4ab
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 21 Mar 2019 20:55:51 GMT

Body:
{
  "value": []
}


DEBUG: AzureQoSEvent: CommandName - Get-AzSubscription; IsSuccess - True; Duration - 00:00:02.9588415; Excep
tion - ;
DEBUG: Finish sending metric.
DEBUG: 4:55:53 PM - GetAzureRMSubscriptionCommand end processing.
DEBUG: 4:55:53 PM - GetAzureRMSubscriptionCommand end processing.

Error output
none

**Comment by bholzmmc** [comment]
Closing issue.  Did not realize that subscription RBAC was preventing my account from being able to read them.

**Comment by sambathrajv** [comment]
What RBAC is needed to get these values? I am service admin and the results are shown without values?
![image](https://github.com/Azure/azure-powershell/assets/128248579/1ec8feed-e6f6-4fac-b563-70355b5c3cf0)
