### ISSUE TITLE
Microsoft.WindowsAzure.Commands.Websites.GetAzureWebsiteCommand  Request to a downlevel service  failed.

### ISSUE THREAD

**Issue by polischuk** [Azure/azure-powershell#8826]
Hi starting from today my script stop working, script start and stop my app service.
Error
`Get-AzureWebsite : <string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">Request to a downlevel service  failed.</string> At start-stop-appservice:29 char:29 +      + CategoryInfo          : CloseError: (:) [Get-AzureWebsite], CloudException     + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.GetAzureWebsiteCommand
`
full workflow code

```
Workflow start-stop-appservice 
{
    # Parameters
    Param(
        [Parameter (Mandatory= $true)]
        [bool]$Stop,
        
        [Parameter (Mandatory= $true)]
        [string]$CredentialAssetName,

        [Parameter (Mandatory =$true)]
        [string]$WebAppName
       )  
       
    #The name of the Automation Credential Asset this runbook will use to authenticate to Azure.
    $CredentialAssetName = $CredentialAssetName;
    
    #Get the credential with the above name from the Automation Asset store
    $Cred = Get-AutomationPSCredential -Name $CredentialAssetName
    if(!$Cred) {
        Throw "Could not find an Automation Credential Asset named '${CredentialAssetName}'. Make sure you have created one in this Automation Account."
    }

    #Connect to your Azure Account      
    Add-AzureRmAccount -Credential $Cred
    Add-AzureAccount -Credential $Cred
    
    #Check for each subscription to find WebApp  
    Get-AzureSubscription | ForEach-Object {
        Write-Output "`n Looking into $($_.SubscriptionName) subscription..."  
  
        #Select subscription  
        Select-AzureSubscription -SubscriptionId $_.SubscriptionId  
        Select-AzureRmSubscription -SubscriptionId $_.SubscriptionId  
    
        $status = 'Stopped'
        if ($Stop)
        {
            $status = 'Running'
        }

        # Get Running WebApps (Websites)
        $websites = Get-AzureWebsite | where-object -FilterScript{$_.state -eq $status -and $_.Name -eq $WebAppName}
        
        foreach ($website In $websites)
        {
            if ($Stop)
            {
                $result = Stop-AzureWebsite $website.Name
                if($result)
                {
                    Write-Output "- $($website.Name) did not shutdown successfully"
                }
                else
                {
                    Write-Output "+ $($website.Name) shutdown successfully"
                }
            }
            else
            {
                $result = Start-AzureWebsite $website.Name
                if($result)
                {
                    Write-Output "- $($website.Name) did not start successfully"
                }
                else
                {
                    Write-Output "+ $($website.Name) started successfully"
                }
            } 
        }
    }   
}
```

**Comment by jgoyvaerts** [comment]
Same issue here!

**Comment by polischuk** [comment]
@jgoyvaerts  where?

**Comment by jgoyvaerts** [comment]
A call to Get-AzureWebsiteJob stopped working in our Azure DevOps release pipeline

**Comment by polischuk** [comment]
@jgoyvaerts  ![image](https://user-images.githubusercontent.com/6980161/54823542-de5b6f00-4cb0-11e9-9fe1-7782e3983f31.png)

**Comment by vladimir-shcherbakov** [comment]
@polischuk Please fill out the `Az module bug report` entry form. The data of this form is essential for the investigation process.


## Description



## Steps to reproduce

```powershell

```

## Environment data



```

```

## Module versions



```powershell

```

## Debug output



```

```

## Error output



```

```

**Comment by jixer** [comment]
We are running into this same issue in one of our TFS builds.  Not sure when the issue started, but we had a successful build as of 5 days ago and now none of the builds using the Azure Web App Deployment build task are working.  

We are using the out-of-the-box Azure Web App Deployment build task from TFS 2015 Update 4.

Here is the output from the build server task.  
![tfs_error](https://user-images.githubusercontent.com/1870485/54857553-37c99b00-4cbd-11e9-882b-b82e084723dc.PNG)

Something to also note is that we're using the same version of the AzurePSCmdlets (5.1.1) and AzureWebPowerShellDeployment task (1.0.26) currently as we were five days ago when things were working.  Issue might not be with the PowerShell template and potentially there was a change to the interface that the script talks to.

**Comment by polischuk** [comment]
@vladimir-shcherbakov @jgoyvaerts as I described before: it's running as
### Steps to reproduce
Azure workbook
### Environment data
azure

### Error output
```
Get-AzureWebsite : <string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">Request to a downlevel service 
failed.</string>
At start-stop-appservice:29 char:29
+ 
    + CategoryInfo          : CloseError: (:) [Get-AzureWebsite], CloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Websites.GetAzureWebsiteCommand
 
```

**Comment by tonjohn** [comment]
We started hitting this error on Friday with the Publish-AzureWebsiteProject command.

**Comment by polischuk** [comment]
note: start working now, but it's strange, when same code work/ not work/ and now start working :/

**Comment by jixer** [comment]
@polischuk Thanks for the update.  I confirmed that the TFS 2015 "Azure Web App Deployment" build task we have (that uses this same function) is also working as of now with no changes made.  It was not working about 16 hours ago when I last tried.

There's some additional information here that is related to the issue we ran into: https://github.com/Azure/azure-powershell/issues/7558
