### ISSUE TITLE
couldn't create QnA and bot app using powershell

### ISSUE THREAD

**Issue by PrajithB** [Azure/azure-powershell#8836]
I'm trying to create QnA using powershell command - New-AzCognitiveServicesAccount, but I get the error shown below. I'm not sure to which parameter the runtimeendpoint needs to passed. Guess it also needs search instance, appservice, appserviceplan and web app bot to be created. Not really sure how these parameters can be passed to PS command. Using JSON it works fine. I do have same issue in creating web app bot using New-AzResource command, wherein cannot figure out how to pass the appID of the web app bot. Not sure, if these can be done using powershell. Please help if there's a way. 

command --- New-AzCognitiveServicesAccount -ResourceGroupName XXXXXXX -Name XXXXXQNA001 -Type qNaMaker -Location 'West US' -SkuName S0 -Force
Error ---- New-AzCognitiveServicesAccount : The given 'apiProperties' '{}' is invalid. Validation errors: Required properties are missing from object: qnaRuntimeEndpoint. Path

**Comment by markcowl** [comment]
@felixwa Can you take a look?

**Comment by yangyuan** [comment]
PowerShell is missing `ApiProperties` support. The support will be added in the upcoming few weeks.

Please consider to use Azure CLI as temporary solution, 
https://github.com/Azure/azure-cli/issues/6888#issuecomment-417817480

**Comment by PrajithB** [comment]
Please let me know when it gets pushed. I will update PS cmdlets. Thanks for your help :-)

**Comment by KranthiPakala-MSFT** [comment]
@yangyuan - Following up to see if there is any update on this? - Thank you

**Comment by navba-MSFT** [comment]
@PrajithB Apologies for the delayed response. Could you please run [New-AzCognitiveServicesAccountApiProperty ](https://docs.microsoft.com/en-us/powershell/module/az.cognitiveservices/new-azcognitiveservicesaccountapiproperty?view=azps-7.1.0) command and check if that helps? Awaiting your reply.

**Comment by yangyuan** [comment]
`ApiProperty` is required for certain Account kinds (types).
Here is an sample of how to carry `ApiProperty` when creating an account.

$apiProperties = New-AzCognitiveServicesAccountApiProperty
$apiProperties.QnaRuntimeEndpoint = "https://sdk-test-qna-maker.azurewebsites.net"

New-AzCognitiveServicesAccount -ResourceGroupName $rgname -Name $accountname -Type 'QnAMaker' -SkuName $skuname -Location $loc -CustomSubdomainName $accountname -ApiProperty $apiProperties -Force;
