### ISSUE TITLE
NoWait Support for Compute LRO Cmdlets

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#8846]
## Description

For Compute LRO Cmdlets, other than the simple parameter set for VM and VMSS, add the option -NoWait, which calls the 'Begin<Operation>' call in the underlying SDK, and returnes on the ACCEPTED returned from the SDK

This should return a type which has only tracking information

## Cost
8

**Comment by maddieclayton** [comment]
What needs to be done:

- [ ] Cmdlets that currently do not output some sort of OperationResult:
DisableAzureVmssDiskEncryption.cs
SetAzureVmssDiskEncryptionExtension.cs
ContainerServiceCreateOrUpdateMethod.cs
DiskCreateOrUpdateMethod.cs
DiskGrantAccessMethod.cs
DiskUpdateMethod.cs
GalleryCreateOrUpdateMethod.cs
GalleryImageCreateOrUpdateMethod.cs
GalleryImageVersionCreateOrUpdateMethod.cs
ImageCreateOrUpdateMethod.cs
SnapshotCreateOrUpdateMethod.cs
SnapshotGrantAccessMethod.cs
SnapshotUpdateMethod.cs
VirtualMachineRunCommandMethod.cs
VirtualMachineScaleSetCreateOrUpdateMethod.cs
VirtualMachineScaleSetUpdateMethod.cs
VirtualMachineScaleSetVMRunCommandMethod.cs
VirtualMachineScaleSetVMUpdateMethod.cs
NewAzureVMCommand.cs

- [ ] Tests

**Comment by niander** [comment]
PR #9051

**Comment by bgelens** [comment]
related issue #7145. 

Please make sure that **correlationId** and **operationId** information is made part of the [PSAzureOperationResponse](https://github.com/Azure/azure-powershell/blob/master/src/Compute/Compute/Models/PSAzureOperationResponse.cs). AFAICT it currently is not (unless RequestId is actually CorrelationId?) but it is crucial information. 

This information is send as response header under the keys `x-ms-correlation-request-id` and `x-ms-request-id`.

**Comment by niander** [comment]
Hello @bgelens, could you file an issue with this request?

**Comment by bgelens** [comment]
@niander done!

**Comment by niander** [comment]
- [ ] Cmdlets that currently do not output some sort of OperationResult:
  - [ ] DisableAzureVmssDiskEncryption.cs
  - [ ] SetAzureVmssDiskEncryptionExtension.cs
  - [ ] ContainerServiceCreateOrUpdateMethod.cs
  - [ ] DiskCreateOrUpdateMethod.cs
  - [ ] DiskGrantAccessMethod.cs
  - [ ] DiskUpdateMethod.cs
  - [ ] GalleryCreateOrUpdateMethod.cs
  - [ ] GalleryImageCreateOrUpdateMethod.cs
  - [ ] GalleryImageVersionCreateOrUpdateMethod.cs
  - [ ] ImageCreateOrUpdateMethod.cs
  - [ ] SnapshotCreateOrUpdateMethod.cs
  - [ ] SnapshotGrantAccessMethod.cs
  - [ ] SnapshotUpdateMethod.cs
  - [ ] VirtualMachineRunCommandMethod.cs
  - [ ] VirtualMachineScaleSetCreateOrUpdateMethod.cs
  - [ ] VirtualMachineScaleSetUpdateMethod.cs
  - [ ] VirtualMachineScaleSetVMRunCommandMethod.cs
  - [ ] VirtualMachineScaleSetVMUpdateMethod.cs
  - [ ] NewAzureVMCommand.cs

- [ ] Not implemented yet:
  - [ ] SaveAzureVMImageCommand

**Comment by markcowl** [comment]
@niander The common code that drives AsJob support is here: https://github.com/Azure/azure-powershell-common/blob/master/src/Common/Extensions/CmdletExtensions.cs#L112

We will need to change this slightly, so it doesn't execute AsJob if NoWait exists and is specified

**Comment by markcowl** [comment]
Fix is checked in.  Will be in next release
