### ISSUE TITLE
https://aka.ms/azps-migration-guide link is broken, leads to Microsoft homepage

### ISSUE THREAD

**Issue by ebmarquez** [Azure/azure-powershell#8850]
received this warning 
WARNING: AzureRM.Profile already loaded. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide.

The link leads to Microsoft - Official Page.  Please update the URL or link manage with a functional page with Migration notes.

**Comment by cormacpayne** [comment]
@ebmarquez Hey Eric, would you mind trying the link again? I just clicked on the link that you provided in the issue body above and it leads me to [this page](https://github.com/Azure/azure-powershell/blob/master/documentation/migration-guides/Az.1.0.0-migration-guide.md), which is the correct redirect destination.

**Comment by ebmarquez** [comment]
Thanks it woks now.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
