### ISSUE TITLE
Example Headers are wrongly placed for Get-AzureRmDataFactoryV2Trigger

### ISSUE THREAD

**Issue by Hamdansultan** [Azure/azure-powershell#8852]
## Description
In blog, Example Headers are wrongly placed for Get-AzureRmDataFactoryV2Trigger

**Comment by dingmeng-xue** [comment]
@Hamdansultan , which blog were you referencing?

**Comment by Hamdansultan** [comment]
I had filed this issue long ago and there was an help page for Get-AzureRmDataFactoryV2Trigger and it was displaying some wrong info.

Kind Regards
Hamdan

**Comment by dingmeng-xue** [comment]
@Hamdansultan , I compared `Get-AzureRmDataFactoryV2Trigger` and the latest version `Get-AzDataFactoryV2Trigger` but didn't find difference. Could you indicate what incorrect info is?

**Comment by Hamdansultan** [comment]
I am not able to find that document again, please close my ticket. If I’ll find it in future, I’ll let you know.

Kind Regards
Hamdan

________________________________
