### ISSUE TITLE
Network Module

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#8865]
## Description
Generate Network Module
- [ ] Configuration
- [ ] Simple customizations
- [ ] Help
- [ ] File issues for new bugs / new patterns for AutoRest
- [ ] File issues for needed test or customization infrastructure
- [ ] Estimate additional customization necessary

**Comment by MiYanni** [comment]
# Progress
## Cycle 1
- Normalized some naming patterns for cmdlets to help match prior cmdlets
- Mapped any `Invoke` cmdlets to properly named cmdlets
- Added missing parent resource names to the start of some cmdlet names
- Identified a few cmdlets that need to be merged together

## Cycle 2
- (80% done) Going through missing cmdlets and seeing how they map to generated, or aliasing them to `Test-AzDummy` to 'remove' them from missing list
- Several generalized casing fixes
- More generalized renaming (using acronyms such as Waf and Vnet)

## Future Cycles
- Going through parameter differences
  - Determining if additional changes are required for very complex parameters
- In-depth review and modifications of models
- Determining customizations
  - Simple and complex
- Actually running the cmdlets

**Comment by MiYanni** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/issues/9771
