### ISSUE TITLE
Resources Module

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#8866]
## Description
Generate Resources Module
- [x] Configuration
- [x] Simple customizations
- [x] Help
- [x] File issues for new bugs / new patterns for AutoRest
- [x] File issues for needed test or customization infrastructure
- [x] Determine which cmdlets should be hand-written and which can use generator
- [x] Estimate additional customization necessary

**Comment by cormacpayne** [comment]
Building cmdlets currently blocked on [this issue](https://github.com/Azure/autorest.powershell/issues/287).

[This gist](https://gist.github.com/cormacpayne/21db58049954aa28d01086af6e9a77bd) outlines the latest progress when it comes to changes that need to be made for parity. I will update this gist when the above issue is resolved and I can build the cmdlets again.

**Comment by cormacpayne** [comment]
### Cost: Large

- [`readme.md`](https://github.com/Azure/azure-powershell/blob/ec03e500bb2f44d0d811b5ad8de22cc193014e1a/src/Resources/readme.md)
- [Docs](https://github.com/Azure/azure-powershell/tree/ec03e500bb2f44d0d811b5ad8de22cc193014e1a/src/Resources/docs)
- [Overview of work needed to be done](https://github.com/Azure/azure-powershell/blob/ec03e500bb2f44d0d811b5ad8de22cc193014e1a/src/Resources/overview.md)
