### ISSUE TITLE
Storage (Management) Module

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#8867]
## Description
Generate Storage (Management) Module
- [x] Configuration
- [x] Simple customizations
- [x] Help
- [x] File issues for new bugs / new patterns for AutoRest
- [x] File issues for needed test or customization infrastructure
- [x] Estimate additional customization necessary

**Comment by niander** [comment]
blocked by https://github.com/Azure/autorest.powershell/issues/268
