### ISSUE TITLE
KeyVault Module

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#8869]
## Description
Generate SKayVault Module
- [ ] Configuration
- [ ] Simple customizations
- [ ] Help
- [ ] File issues for new bugs / new patterns for AutoRest
- [ ] File issues for needed test or customization infrastructure
- [ ] Estimate additional customization necessary

**Comment by maddieclayton** [comment]
Played a little with this here: https://github.com/maddieclayton/azure-powershell/tree/kvgeneration

**Comment by cormacpayne** [comment]
Currently blocked when generating management plane (tracked [here](https://github.com/Azure/autorest.powershell/issues/285)) and data plane (tracked [here](https://github.com/Azure/autorest.powershell/issues/286)).

**Comment by cormacpayne** [comment]
### Cost: Large

- [`readme.md`](https://github.com/Azure/azure-powershell/blob/ec03e500bb2f44d0d811b5ad8de22cc193014e1a/src/KeyVault/readme.md)
- [Docs](https://github.com/Azure/azure-powershell/tree/ec03e500bb2f44d0d811b5ad8de22cc193014e1a/src/KeyVault/docs)
- [Overview of work needed to be done](https://github.com/Azure/azure-powershell/blob/ec03e500bb2f44d0d811b5ad8de22cc193014e1a/src/KeyVault/overview.md)
