### ISSUE TITLE
AppService Module

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#8871]
## Description
Generate AppService Module
- [x] Configuration
- [x] Simple customizations
- [x] Help
- [x] File issues for new bugs / new patterns for AutoRest
- [x] File issues for needed test or customization infrastructure
- [x] Estimate additional customization necessary

**Comment by cormacpayne** [comment]
Filed issue outlining work to be done for existing cmdlets: https://github.com/Azure/azure-powershell/issues/9342
