### ISSUE TITLE
Login to Azure from WinRm session doesnt work

### ISSUE THREAD

**Issue by GitHubAre** [Azure/azure-powershell#8875]
## Description
I have a script that is logging to azure, fetching some data from Key Vault and some other resources, it then outputs it to Json file.
This script is working fine locally and on destination server where its executed by hand (from powershell.exe).
Problem occurs when I invoke script from WinRM (ansible), but I managed to reproduce it also creating the session by hand from my local computer.

When the script is executed via WinRM, it looks as if it is not logged in to Azure or the connection is not valid, but the script executed Login-AzureRmAccount and Select-AzureRmSubscription.

## Steps to reproduce

```powershell
$session = New-PSSession -ComputerName "server" -Credential (Get-Credential);
Enter-PSSession -Session $session;
cd "c:\workspace\scripts"
.\Get-AzureFacts.ps1
```

## Module versions

```powershell
AzureRM version - 6.13.1
```
## Error output

```
Get-AzureKeyVaultSecret : Unable to retrieve service key for ServicePrincipal account
XXXXXXX-XXXX-XXXX-XXXX-XXXXXX. Please log in again to supply the credentials for this  service
principal. In PowerShell, execute Connect-AzureRmAccount for Azure Resource Manager  cmdlets or
Add-AzureAccount for service management cmdlets. At
Y:\master\Azure\02_Scripts\configuration.management\windows\Get-AzureFacts.ps1:34 char:24 + ...
ltSecrets = Get-AzureKeyVaultSecret -VaultName $GlobalSettings.OurRes ... +
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          : CloseError:
(:) [Get-AzureKeyVaultSecret], KeyNotFoundException     + FullyQualifiedErrorId :
Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret
```

**Comment by markcowl** [comment]
How is the login occurring in this case?  From the message, it sounds like you may be using SPN + Secret login, which would require having access to the Windows Credential Store in the remote session.  This means you will either need to create a session using an authentication mechanism that allows access to the credential store on the remote machine (using -CredSSP auth, or -EnableNetworkAccess when entering the session might work).  Otherwise, you would need to use an authentication mechanism that doesn't require access to the credentials store (for example, the Az cmdlets do not require this access).

**Comment by GitHubAre** [comment]
Hello,
Thanks for feedback!

I am using ansible with Kerberos authentication.
Therefore the actual creation of connection is "blackbox" for me.
I have already started rewriting from AzureRM to Az.
Based on yours feedback it will most likely solve the issue.
I will update this GitHub issue once I migrate to Az to confirm that with Az over WinRm it works.

**Comment by GitHubAre** [comment]
@markcowl  I have migrated to Az and it works over WinRm without additional handling of user profile / tweaking access to windows credentials store.
Thanks for clarification why the error occurred :)
Closing this issue.
