### ISSUE TITLE
Get-AzAutomationJob does not return job name

### ISSUE THREAD

**Issue by D1v38om83r** [Azure/azure-powershell#8882]
If I use the Az command, I can use the job name, but then it is confusing because the result returned to me has a JobId that is different than what I passed in.  Here is the output from using the new Az command:

PS Azure:\> Get-AzAutomationJob -ResourceGroupName miromanrunas -AutomationAccountName miromanrunas -Id de83c45e-ec5f-4624-934d-3a4bbfba7572
ResourceGroupName      : miromanrunas
AutomationAccountName  : miromanrunas
JobId                  : ec6fc61e-874f-41b7-9ac4-2360c67aec1a
CreationTime           : 3/26/19 12:44:15 AM +00:00
Status                 : Completed
StatusDetails          : None
StartTime              : 3/26/19 12:44:39 AM +00:00
EndTime                : 3/26/19 12:44:39 AM +00:00
Exception              :
LastModifiedTime       : 3/26/19 12:44:39 AM +00:00
LastStatusModifiedTime : 3/26/19 12:44:39 AM +00:00
JobParameters          : {}
RunbookName            : doublebyte
HybridWorker           :
StartedBy              : {scrubbed}

The response should include `JobName : de83c45e-ec5f-4624-934d-3a4bbfba7572` and `JobId: ec6fc61e-874f-41b7-9ac4-2360c67aec1a` but it only has the JobId.

**Comment by markcowl** [comment]
@vrdmr @safeermohammed @eamonoreilly Can you take  a look?

**Comment by andyw248** [comment]
Triaged: Closing because of no known customer cases.
