### ISSUE TITLE
How to connect with proxy and PowerShell 6.x

### ISSUE THREAD

**Issue by v-akhana** [Azure/azure-powershell#8897]
## Description
My customer raised a request about failure “Connect-AzAccount” command let using PowerShell 6.x

Below is my customer’s comment.

--------
We connect to Azure from internal network through authentication proxy server.  In case of using PowerShell version 5.1, proxy settings can be done as below.

```powershell
$proxyUrl = 'proxy URL'
$proxyId = 'proxy user ID'
$proxyPwd = 'proxy password'

$password = ConvertTo-SecureString $proxyPwd -AsPlainText -Force
$cred = New-Object System.Management.Automation.PSCredential $proxyId, $password
$proxy = New-Object System.Net.WebProxy $proxyUrl
$proxy.Credentials = $cred
[System.Net.WebRequest]::DefaultWebProxy = $proxy
```

In terms of PowerShell 6.x, my customer would like to use proxy as well, but cannot use the command let above with proxy error.

--------

## Steps to reproduce

```powershell 6.0

```

## Environment data

```

```

## Module versions

```powershell
PowerShell 6.0
```

## Debug output

```

```

## Error output

```

```

**Comment by cormacpayne** [comment]
@v-akhana we will need some additional information from the customer:

- What is the full script that they are running? In the script above, I don't see any `Az` cmdlets being executed, even the mentioned `Connect-AzAccount` cmdlet
- What is the error that the user is seeing when they run `Connect-AzAccount`? You can paste the error message they see after the cmdlet fails, or they can run `Resolve-AzError` for a more detailed error
- What is the debug trace when they run `Connect-AzAccount`? Before running `Connect-AzAccount`, have the user set `$DebugPreference = "Continue"` to get the full debug output

**Comment by maddieclayton** [comment]
@v-akhana Ping on the questions above

**Comment by v-akhana** [comment]
Thank you for your response Cormac!
And apologies for the delay.

#1 What is the full script that they are running?
#2 What is the error that the user is seeing when they run Connect-AzAccount?
>> Please confirm the attached file (119031126000112_Error.txt)

**Comment by v-akhana** [comment]
Thank you for your response Cormac!
And apologies for the delay

#1 What is the full script that they are running?
#2 •What is the error that the user is seeing when they run Connect-AzAccount?
>
  ---------------
PS C:\> $DebugPreference = "Continue"
PS C:\> Connect-AzAccount
DEBUG: 9:53:48 - ConnectAzureRmAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.
DEBUG: 9:53:48 - using account id 'Yasuhisa.Arai@USiZE2.onmicrosoft.com'...
DEBUG: 9:53:48 - Autosave setting from startup session: 'CurrentUser'
DEBUG: 9:53:48 - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 9:53:48 - Using Autosave scope 'CurrentUser'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/Common/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'Common', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code GCLJU7VAH to authenticate.
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/tenants?api-version=2016-06-01

Headers:
x-ms-client-request-id        : 8b385031-9614-49de-b5c7-62ca9a460ae5
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
ProxyAuthenticationRequired

Headers:
Via                           : 1.1 133.166.8.29 (McAfee Web Gateway 7.8.2.5.0.27615)
Date                          : Wed, 03 Apr 2019 00:54:41 GMT
Cache-Control                 : no-cache
Proxy-Connection              : Keep-Alive
Proxy-Authenticate            : Basic realm="Please Login (proxy1.scskinfo.jp)"

Body:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>


<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta http-equiv="X-UA-Compatible" content="IE=7" />
  <title>McAfee Web Gateway - Notification</title>
  <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
  <link rel="stylesheet" href="/mwg-internal/de5fs23hu73ds/files/default/stylesheet.css" />
</head>


<body onload="swOnLoad();">
  <table class='bodyTable'>
    <tr>
      <td class='bodyData' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_body.gif'>

<table class='logoTable'>
  <tr>
    <td class='logoData'>
      
       
    </td>
  </tr>
</table>




<table class='titleTable' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>
  <tr>
    <td class='titleData'>
      Authentication Required
    </td>
  </tr>
</table>



<table class="contentTable">
  <tr>
    <td class="contentData">
      You must be authenticated to access this URL.
    </td>
  </tr>
</table>



<table class="infoTable">
  <tr>
    <td class="infoData">
      <b>URL: </b><script type="text/javascript">break_line("https://management.azure.com");</script><br />
    </td>
  </tr>
</table>




<table class='policyTable'>
  <tr>
    <td class='policyHeading'>
      <hr>
      Company Acceptable Use Policy
    </td>
  </tr>
  <tr>
    <td class='policyData'>
      This is an optional acceptable use disclaimer that appears on every page. You may change the wording or remove this section entirely in index.html.
    </td>
  </tr>
</table>


<table class='footTable'>
  <tr>
    <td class='helpDeskData' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>
      For assistance, please contact your system administrator.
    </td>
  </tr>
  <tr>
    <td class='footData'>
      generated <span id="time">2019-04-03 09:54:41</span> by McAfee Web Gateway
      <br />

    </td>
  </tr>
</table>

      </td>
    </tr>
  </table>
</body>

</html>



Connect-AzAccount : Operation returned an invalid status code 'ProxyAuthenticationRequired'
At line:1 char:1
+ Connect-AzAccount
+ ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Connect-AzAccount], CloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

DEBUG: AzureQoSEvent: CommandName - Connect-AzAccount; IsSuccess - False; Duration - 00:00:52.9995107; Exception - Microsoft.Rest.Azure.CloudException: Operation returned an invalid status code 'ProxyAuthenticationRequired'
   at Microsoft.Azure.Internal.Subscriptions.TenantsOperations.ListWithHttpMessagesAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Internal.Subscriptions.TenantsOperationsExtensions.ListAsync(ITenantsOperations operations, CancellationToken cancellationToken)
   at Microsoft.Azure.Internal.Subscriptions.TenantsOperationsExtensions.List(ITenantsOperations operations)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 9:54:42 - ConnectAzureRmAccountCommand end processing.
DEBUG: 9:54:42 - ConnectAzureRmAccountCommand end processing.
PS C:\>
---------------------

**Comment by v-akhana** [comment]
#3 What is the debug trace when they run Connect-AzAccount? 

Please confirm the attached file (119031126000112_Debug.txt)
[119031126000112_Debug.txt](https://github.com/Azure/azure-powershell/files/3041141/119031126000112_Debug.txt)

**Comment by markcowl** [comment]
Here is some info on connecting with a default proxy: https://github.com/dotnet/corefx/issues/28780

**Comment by maddieclayton** [comment]
@v-akhana Please let us know if the resource Mark provided above solves the issue. Thanks!

**Comment by maddieclayton** [comment]
Closing - if the above comment did not resolve your issue please let me know and I will reopen.

**Comment by tgeorgiev** [comment]
Sorry to join on this a bit late, but is there a statement how we can set proxy settings so that the Azure client will use them? Doing the same as @v-akhana as well as setting env variables HTTP_PROXY and HTTPS_PROXY, and Connect-AzAccount fails with operation cancelled

Observing the proxy server it doesn't look like any requests are being made to it.
