### ISSUE TITLE
Setting the NumberOfWorkers property on Azure Web App returns "Bad Request" error

### ISSUE THREAD

**Issue by kaushalp** [Azure/azure-powershell#8922]
**Describe the bug**
For a web app inside a Linux ASP with **perSiteScaling** enabled, setting the **NumberOfWorkers** property throws **bad request** error.

**To Reproduce**
I followed the instructions in the article and tried to enable the NumberOfWorkers to 2 and it is throwing an error

```
$newapp = Get-AzWebApp -ResourceGroupName kaushal-linux -Name java-blessed
$newapp.SiteConfig.NumberOfWorkers = 2
Set-AzWebApp $newapp
Set-AzWebApp : Operation returned an invalid status code 'BadRequest'
At line:1 char:1
+ Set-AzWebApp $newapp
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzWebApp], DefaultErrorResponseException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.SetAzureWebAppCmdlet>>
```

**Expected behavior**
The NumberOfWorkers should be set successfully.

**Environment summary**
I am using the powershell console in the Azure Portal

**Additional context**

**Comment by cormacpayne** [comment]
@kaushalp Hey Kaushal, would you mind providing the debug trace from the cmdlet execution? You can get this by setting `$DebugPreference = "Continue"` before running the set of commands that you have above. This will return the HTTP request and response to/from the server.

CC: @panchagnula

**Comment by kaushalp** [comment]
Here it is:
`PS Azure:\> Set-AzWebApp $newapp -debug
DEBUG: 4:24:29 PM - SetAzureWebAppCmdlet begin processing with ParameterSet 'S2'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 4:24:32 PM - using account id 'MSI@50342'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'MSI@50342', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
DEBUG: Checking Cache request http://localhost:50342/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01
DEBUG: Cache Hit
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com/subscriptions/4f42d231-1050-4386-b5ca-54cc38d11edf/resourceGroups/kaushal-linux/providers/Microsoft.Web/sites/java-blessed/config/web?api-version=2018-02-01

Headers:
x-ms-client-request-id        : 05b6df73-8681-492a-a222-d588f62eb839
Accept-Language               : en-US

Body:
{
  "properties": {
    "numberOfWorkers": 1,
    "defaultDocuments": [
      "Default.htm",
      "Default.html",
      "Default.asp",
      "index.htm",
      "index.html",
      "iisstart.htm",
      "default.aspx",
      "index.php",
      "hostingstart.html"
    ],
    "netFrameworkVersion": "v4.0",
    "phpVersion": "",
    "pythonVersion": "",
    "nodeVersion": "",
    "linuxFxVersion": "TOMCAT|9.0-java11",
    "requestTracingEnabled": false,
    "remoteDebuggingEnabled": false,
    "httpLoggingEnabled": true,
    "logsDirectorySizeLimit": 35,
    "detailedErrorLoggingEnabled": false,
    "publishingUsername": "$java-blessed",
    "appSettings": [
      {
        "name": "CATALINA_OPTS",
        "value": "-Xmx1G"
      },
      {
        "name": "WEBSITE_HTTPLOGGING_RETENTION_DAYS",
        "value": "999"
      }
    ],
    "connectionStrings": [],
    "scmType": "None",
    "use32BitWorkerProcess": true,
    "webSocketsEnabled": false,
    "alwaysOn": true,
    "javaVersion": "",
    "javaContainer": "TOMCAT",
    "javaContainerVersion": "9.0-java11",
    "appCommandLine": "",
    "managedPipelineMode": "Integrated",
    "virtualApplications": [
      {
        "virtualPath": "/",
        "physicalPath": "site\\wwwroot",
        "preloadEnabled": true
      }
    ],
    "loadBalancing": "LeastRequests",
    "experiments": {
      "rampUpRules": []
    },
    "autoHealEnabled": false,
    "vnetName": "",
    "localMySqlEnabled": false
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
ETag                          : "1D4E97087FA7215"
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-writes: 1196
x-ms-request-id               : 6c9ba69b-5c8f-45dc-a494-553b7a5b5738
x-ms-correlation-request-id   : 6c9ba69b-5c8f-45dc-a494-553b7a5b5738
x-ms-routing-request-id       : WESTUS:20190402T162433Z:6c9ba69b-5c8f-45dc-a494-553b7a5b5738
X-Content-Type-Options        : nosniff
Date                          : Tue, 02 Apr 2019 16:24:33 GMT

Body:
{
  "Code": "BadRequest",
  "Message": "The parameter javaVersion has an invalid value.",
  "Target": null,
  "Details": [
    {
      "Message": "The parameter javaVersion has an invalid value."
    },
    {
      "Code": "BadRequest"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "01007",
        "MessageTemplate": "The parameter {0} has an invalid value.",
        "Parameters": [
          "javaVersion"
        ],
        "Code": "BadRequest",
        "Message": "The parameter javaVersion has an invalid value."
      }
    }
  ],
  "Innererror": null
}


Set-AzWebApp : Operation returned an invalid status code 'BadRequest'
At line:1 char:1
+ Set-AzWebApp $newapp -debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzWebApp], DefaultErrorResponseException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.SetAzureWebAppCmdlet

DEBUG: AzureQoSEvent: CommandName - Set-AzWebApp; IsSuccess - False; Duration - 00:00:04.0524238; Exception - Microsoft.Azure.Management.WebSites.Models.DefaultErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.WebSites.WebAppsOperations.UpdateConfigurationWithHttpMessagesAsync(String resourceGroupName, String name, SiteConfigResource siteConfig, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.UpdateConfigurationAsync(IWebAppsOperations operations, String resourceGroupName, String name, SiteConfigResource siteConfig, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.UpdateConfiguration(IWebAppsOperations operations, String resourceGroupName, String name, SiteConfigResource siteConfig)
   at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.UpdateWebAppConfiguration(String resourceGroupName, String location, String webSiteName, String slotName, SiteConfig siteConfig, IDictionary`2 appSettings, IDictionary`2 connectionStrings, AzureStoragePropertyDictionaryResource azureStorageSettings)
   at Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.SetAzureWebAppCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 4:24:34 PM - SetAzureWebAppCmdlet end processing.
DEBUG: 4:24:34 PM - SetAzureWebAppCmdlet end processing.`

**Comment by panchagnula** [comment]
@kaushalp this error here is "The parameter javaVersion has an invalid value." & this occurs only on JAVA apps -> because during deployment there is a mismatch in runtime versions of Java with the old version & the new, the Java team has a know bug to track this. Please feel free to open a CRI if you want more details on this as well. As per the internal bug tracking this -> this will be resolved when the deployment is complete. Hope this helps. Thank you,

**Comment by kaushalp** [comment]
@panchagnula Thank you. You are right, I see this behavior in the Azure Resource Explorer too. We can close this one. I have a CRI open for this, I will add these details there.

**Comment by panchagnula** [comment]
thanks for the update,
