### ISSUE TITLE
Regex problem in Set-AzureRmVMAEMExtension causes installation failure when managed disk name contains hyphen.

### ISSUE THREAD

**Issue by tinodo** [Azure/azure-powershell#8927]
Same as https://github.com/Azure/azure-powershell/issues/8926, but now in AzureRM.

**Comment by cormacpayne** [comment]
@tinodo as of December 2018, we moved to shipping the `Az` module every two weeks, and the `AzureRM` module is only being released in cases where a hot fix is needed. As a result, we don't plan on fixing this issue in `AzureRM`, but we brought in the necessary parties for the `Az` issue that you opened.
