### ISSUE TITLE
Powershell / Rest  commands for Enabling custom Domain using own certificates

### ISSUE THREAD

**Issue by paragbharne** [Azure/azure-powershell#8930]
I want to use my own SSL certificates for the enabling CDN custom domain store in the Azure Keyvault.

I used the below PowerShell commands to do that but that enable the default CDN managed certificates.
"Enable-AzureRmCdnCustomDomain"

I am trying it to achieve through the rest followed below docs,
https://docs.microsoft.com/en-us/rest/api/cdn/customdomains/enablecustomhttps#usermanagedhttpsparameters

Below are my request and body :

```
https://management.azure.com/subscriptions/{{subscruptionId}}/resourceGroups/{{rg}}/providers/Microsoft.Cdn/profiles/{{profile}}/endpoints/{{endpoint}}/customDomains/{{customdomain}}/enableCustomHttps?api-version=2016-10-02

{
      "certificateSource": "AzureKeyVault",
      "protocolType": "ServerNameIndication",
      "certificateSourceParameters": {
       "OData.type":"#Microsoft.Azure.Cdn.Models.KeyVaultCertificateSourceParameters",
       "subscriptionId":"#######################",
       "resourceGroupName":"rgname",
       "vaultName":"vaultname",
       "secretName" : "secretname",
       "secretVersion" :"####66#################",
       "updateRule": "NoAction",
       "deleteRule": "NoAction"
       }
}
```

After the above request and body, I am able to enable the Custome https but I would configure the Managed CDN Certs.

```
{
    "provisioningState": "Succeeded",
    "resourceState": "Active",
    "hostName": "test.domain.com",
    "validationData": null,
    "customHttpsProvisioningState": "Enabling"
}
```

**Comment by paragbharne** [comment]
@ravindp if you look into the above issue it would be a great help to us.

thanks

**Comment by paragbharne** [comment]
@ravindp @cormacpayne  I have not heard anything from you guys, I am waiting for your reply.

**Comment by jasongaylord** [comment]
We've used similar code in one of our release pipelines and when hitting the Management REST API, it seems as though the custom domain is stuck in the 'Enabling' state.

**Comment by lsmith130** [comment]
I'm currently working on implementing PowerShell support for enabling HTTPS using certificates from KeyVault, and I should have it ready by the end of the month.

**Comment by KarenHammons** [comment]
@lsmith130 is this in place now?

**Comment by lsmith130** [comment]
This is still a work in progress, but I'll be prioritizing it in next week.

**Comment by jonsamwell** [comment]
@lsmith130 any progress with PowerShell support for enabling HTTPS using certificates from KeyVault?

**Comment by lsmith130** [comment]
I apologize for the delay in getting this fix out, but I'll be publishing a PR which fixes this tomorrow.

**Comment by AgueroPefai** [comment]
Is there any form to get this on powershell or AZ? @cdnfdsuppgithub is there any update?

**Comment by timmkrause** [comment]
Nearly 1.5 years and no progress on this, Azure CLI does support it...
Unfortunately Azure CLI and PowerShell Az modules cannot be used side by side in an ARM template as well (Microsoft.Resources/deploymentScripts) where it could potentially be combined...

So we really have to get bare bones and use the REST API.

This yak shaving is really a pain...

**Comment by navba-MSFT** [comment]
@paragbharne Apologies for the delayed response. I see that this issue thread is open for quite sometime now and there has been no progress. So wanted to check if you are still looking for assistance on this query? Please let us know.

Also I wanted to check if you if you are able to achieve the ask using [this](https://docs.microsoft.com/en-us/rest/api/cdn/custom-domains/enable-custom-https#usermanagedhttpsparameters) REST API. I will check and update this thread about the Powershell support to achieve the same requirement.

**Comment by timmkrause** [comment]
As said. Solved via plain REST API calls. Az module + native ARM support would be greatly appreciated.

**Comment by navba-MSFT** [comment]
@timmkrause @paragbharne CDN PS cmdlet doesn’t support user managed certificate currently.  The CDN engineering group is aware of this and they are working on this ask. 

So until the fix is released, as a workaround you can use CLI [az cdn custom-domain | Microsoft Docs ](https://docs.microsoft.com/en-us/cli/azure/cdn/custom-domain?view=azure-cli-latest#az-cdn-custom-domain-enable-https). Hope this helps.

Please let us know if you have any further queries on this.

**Comment by navba-MSFT** [comment]
@paragbharne Hope you had a chance to look at the above reply. Please feel free to reopen this thread if you have any pending questions. We would be happy to address those.
