### ISSUE TITLE
Question on Azure OAuth Resource guid 74658136-14ec-4630-ad9b-26e160ff0fc6

### ISSUE THREAD

**Issue by ryanspletzer** [Azure/azure-powershell#8933]
This is simply a question.

Please forgive the strange issue title, but I wanted this to be more google-able for others.

I am looking into a script to create app registrations + assign OAuth permissions to app registrations + grant admin consent to them, along the lines of what is shown here:

http://www.lieben.nu/liebensraum/2018/04/how-to-grant-oauth2-permissions-to-an-azure-ad-application-using-powershell-unattended-silently/ 

I've found a reference to the resource guid in that article in various places, especially in relation to Azure PowerShell: `74658136-14ec-4630-ad9b-26e160ff0fc6`

For example I found a reference to it in a comment in this repo's issues:

https://github.com/Azure/azure-powershell/issues/7525#issuecomment-429739114

And elsewhere:

http://devchat.live/en/2018/01/10/how-to-call-rest-apis-on-azure-portal/

https://stackoverflow.com/questions/47346121/powershell-do-grant-permissions-action-on-azure-ad-application-with-powershe

https://stackoverflow.com/questions/54035491/i-am-trying-to-run-some-powershell-script-on-c-sharp-app-to-grant-permission-on

https://stackoverflow.com/questions/52865756/how-to-call-rest-apis-on-azure-portal

https://stackoverflow.com/questions/48556167/how-to-give-grant-permissions-for-an-app-in-azure-ad-using-powershell

https://serverfault.com/questions/896150/azure-ad-guest-user-type

It doesn't appear to be an app id or object id of an app registration / service principal in our tenant (based on searching via Azure Portal and Azure AD PowerShell). My best guess is it's the core "Azure" resource id, but that is just a guess.

(As another example, I found another resource guid for Azure DevOps in this sample here which seems to be documented no where else: https://github.com/Microsoft/azure-devops-auth-samples/blob/master/ManagedClientConsoleAppSample/Program.cs#L19, and when I search, that is actually a pre-existing app id / client_id in our tenant (and likely other tenants).)

Question: Does anyone know what this OAuth resource guid `74658136-14ec-4630-ad9b-26e160ff0fc6` actually is referring to? Thanks!

**Comment by cormacpayne** [comment]
@ryanspletzer Hey Ryan, I _think_ that this GUID points to the URI `https://management.core.windows.net` as the resource client URI, but I will double-check.

**Comment by maddieclayton** [comment]
Closing as the answer above is correct :)

**Comment by AgelM** [comment]
I have doubts about the accuracy of the provided response since, I have been getting the following error when requesting a token using the referred URL `https://management.core.windows.net`

```ERROR: {"ClassName":"Microsoft.Portal.Framework.Exceptions.ClientException","Message":"AADSTS500131: Assertion audience does not match the Client app presenting the assertion. The audience in the assertion was 'https://management.core.windows.net/' and the expected audience is 'https://main.iam.ad.ext.azure.com' or one of the Application Uris of this application with App ID '74658136-14ec-4630-ad9b-26e160ff0fc6'(ADIbizaUX).\r\nTrace ID: 4ea3dfcb-4e3e-4b08-ae23-e4a7713d3600\r\nCorrelation ID: aabdd90c-66f0-4df4-b86c-eed2fb0f7867\r\nTimestamp: 2019-06-27 06:36:19Z","Data":{},"HResult":-2146233088,"XMsServerRequestId":null,"Source":null,"HttpStatusCode":400,"ClientData":{"errorCode":"adalautherror_invalid_grant","localizedErrorDetails":{"errorDetail":"AADSTS500131: Assertion audience does not match the Client app presenting the assertion. The audience in the assertion was 'https://management.core.windows.net/' and the expected audience is 'https://main.iam.ad.ext.azure.com' or one of
the Application Uris of this application with App ID '74658136-14ec-4630-ad9b-26e160ff0fc6'(ADIbizaUX).\r\nTrace ID: 4ea3dfcb-4e3e-4b08-ae23-e4a7713d3600\r\nCorrelation ID: aabdd90c-66f0-4df4-b86c-eed2fb0f7867\r\nTimestamp: 2019-06-27 06:36:19Z"},"operationResults":[{"objectId":null,"displayName":null,"status":0,"details":"AADSTS500131: Assertion audience does not match the Client app presenting the assertion. The audience in the assertion was 'https://management.core.windows.net/' and the expected audience is 'https://main.iam.ad.ext.azure.com' or one of the Application Uris of this application with App ID '74658136-14ec-4630-ad9b-26e160ff0fc6'(ADIbizaUX).\r\nTrace ID: 4ea3dfcb-4e3e-4b08-ae23-e4a7713d3600\r\nCorrelation ID: aabdd90c-66f0-4df4-b86c-eed2fb0f7867\r\nTimestamp: 2019-06-27 06:36:19Z"}],"timeStampUtc":"2019-06-27T06:36:19.5462925Z","clientRequestId":"xxxxxxxxxxxxxxxxxxxxxxxxx","internalTransactionId":"xxxxxxxxxxxxxxxxxxxx","tenantId":"xxxxxxxxxxxxxxxxxxxxxxxxxx","userObjectId":null,"exceptionType":"AdalServiceException"}}
```

**Comment by JoeBrockhaus** [comment]
> > @ryanspletzer Hey Ryan, I _think_ that this GUID points to the URI `https://management.core.windows.net` as the resource client URI, but I will double-check.
> 
> > I have doubts about the accuracy of the provided response since, I have been getting the following error when requesting a token using the referred URL `https://management.core.windows.net`
> > `...`
> 

Based on the error @AgelM received, the Resource that matches `74658136-14ec-4630-ad9b-26e160ff0fc6` should be `https://main.iam.ad.ext.azure.com`. 

> _`... the expected audience is 'https://main.iam.ad.ext.azure.com' or one of the Application Uris of this application with App ID '74658136-14ec-4630-ad9b-26e160ff0fc6'(ADIbizaUX).`_

This makes sense, because that's the base URI for the `RegisteredApplications` API used in the `liebensraum` blog post @ryanspletzer opened the Issue with.
