### ISSUE TITLE
New-AzBlueprintAssignment forbidden error using service principal

### ISSUE THREAD

**Issue by dankwok** [Azure/azure-powershell#8935]
## Description
I am experiencing an error while running this command in an Azure Automation runbook. I am first connecting to Azure using the Run As account.

The Run As service principal is a Contributor is part of a custom role where I created to assign Blueprint.

## Steps to reproduce

```powershell
Clear-AzContext -Force
$Conn = Get-AutomationConnection -Name AzureRunAsConnection
Connect-AzAccount -ServicePrincipal -Tenant $Conn.TenantID -ApplicationId $Conn.ApplicationID -CertificateThumbprint $Conn.CertificateThumbprint
```
```
I first run these commands before the rest of my script is executed. I then build some parameters to be passed to New-AzBlueprintAssignment and execute it.
```

## Module versions

```powershell
Az.Blueprint 0.1.0
```

## Debug output

```
New-AzBlueprintAssignment : Operation returned an invalid status code 'Forbidden'
At line:75 char:17
+ ... ssignment = New-AzBlueprintAssignment -Name $assignmentName -Blueprin ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzBlueprintAssignment], GraphErrorException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Blueprint.Cmdlets.NewAzureRmBlueprintAssignment
```

**Comment by cormacpayne** [comment]
@filizt Hey Filiz, would you mind taking a look at the above issue? Is there any additional permissions needed by the user to run the Blueprint cmdlets?

**Comment by filizt** [comment]
@dankwok The error is expected when running the New-AzBlueprintAssingment cmdlet as a service principal with system-assigned identity (which is the default for the New- cmdlet). This is due to some limitations we have querying AAD as the SP, however we're currently working on a fix which should be in the next release of Blueprint AZ module. In the mean time, one way to run this cmdlet with a service principal is to provide a user-assigned identity through the -UserAssignedIdentity parameter. Here's an New-AzBlueprintAssignment  example using a user-assigned identity: 

 New-AzBlueprintAssignment -Name "myAssignment" -Blueprint $blueprintObject -SubscriptionId
    00000000-1111-0000-1111-000000000000 -Location "West US" -Parameter @{P1="v1"; P2="v2"} -UserAssignedIdentity "/sub
    scriptions/00000000-1111-0000-1111-000000000000/resourceGroups/my-resource-group/providers/Microsoft.ManagedIdentit
    y/userAssignedIdentities/my-user-defined-identity

**Comment by dankwok** [comment]
Thanks @filizt. I am able to run the command you provided in my PowerShell console from my local, but when I use the same command in Azure Automation, it seems to be completely using a different identity.

The Object ID in the error below is not the same object ID specified in my UserAssignedIdentity. Am I doing something incorrectly while running this in Azure Automation runbook?

Thanks!

```
New-AzBlueprintAssignment : The client 'x' with object id 
'x' does not have authorization to perform action 
'Microsoft.Blueprint/blueprintAssignments/write' over scope '/subscriptions/x'.
At line:75 char:17
+ ... ssignment = New-AzBlueprintAssignment -Name $assignmentName -Blueprin ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzBlueprintAssignment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Blueprint.Cmdlets.NewAzureRmBlueprintAssignment`
```

**Comment by dankwok** [comment]
Thanks @filizt! After some hiccups with my runbook, I was able to run the command you provided to resolve my issue.
