### ISSUE TITLE
Login-AzAccount clears Credentials in PowerShell 5.1

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-powershell#8940]
## Description

When using Login-AzAccount(Connect-AzAccount) in PS 5.1 and the credentials are passed as PowerShell Credentials object the password is cleared after the object is used. Strangely I have seen this bug in AzureAD module several months ago and they have fixed it.

## Steps to reproduce

Start new PowerShell 5.1 session without any context
```powershell
PS C:\WINDOWS\system32> $cred=Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
PS C:\WINDOWS\system32> Login-AzAccount -Credential $cred

Account                                      SubscriptionName        TenantId                             Environment
-------                                      ----------------        --------                             -----------
Account_Something Subscription_Something TenantId_Sometning AzureCloud


PS C:\WINDOWS\system32> $cred.GetNetworkCredential().Password.Length
0
```

If you do the same but you use the credentials prior logging this does not happen. For example

```powershell
PS C:\WINDOWS\system32> $cred=Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
PS C:\WINDOWS\system32> $cred.GetNetworkCredential().Password.Length
18
PS C:\WINDOWS\system32> Login-AzAccount -Credential $cred

Account                                      SubscriptionName        TenantId                             Environment
-------                                      ----------------        --------                             -----------
Account_something Subscription_Something TenantId_Something AzureCloud


PS C:\WINDOWS\system32> $cred.GetNetworkCredential().Password.Length
18
PS C:\WINDOWS\system32>
```
## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

## Module versions

```powershell
PS C:\WINDOWS\system32> Get-Module -Name Az.* -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.4.0      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enab...
```

## Debug output

Not needed. Very easy to reproduce.

```

```

## Error output

No errors.
```

```

**Comment by cormacpayne** [comment]
@slavizh thanks for filing this issue -- my initial reaction is that the version of ADAL that we're using in our desktop build of Azure PowerShell is older than the one used by AzureAD, and doesn't contain this necessary bug fix. As far as I can tell, we don't do anything additional with the credential users provide to this cmdlet other than pass it to the ADAL call to acquire the token. It could be that ADAL is disposing of this object under the hood when it does it's cleanup after receiving the token. We'll take a look.

**Comment by slavizh** [comment]
@cormacpayne Yep. Thanks! Unfortunately I cannot remember in which build of Azure AD module this was fixed but you could probably check their release notes.

**Comment by markcowl** [comment]
The version will be updated in the May 6 release, should check with this version
