### ISSUE TITLE
Az.Storage 1.1.1-preview does not include Microsoft.Azure.Cosmos.Table.dll

### ISSUE THREAD

**Issue by tinodo** [Azure/azure-powershell#8950]
## Description

In Az.Storage 1.1.0 a new namespace, Microsoft.Azure.Cosmos.Table was introduced and this version therefore included Microsoft.Azure.Cosmos.Table.dll
In Az.Storage 1.1.1-preview this DLL is missing, causing all sorts of issues with, for example, AzureRmStorageTable

Is this "on-purpose" and did I miss anything or is this regression?

**Comment by markcowl** [comment]
@blueww can you take  alook?

**Comment by blueww** [comment]
Az.Storage 1.1.1-preview is puclished before Az.Storage 1.1.0, and it's based on old Storage Client library [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/) . 
Az.Storage 1.1.0 is based on Microsoft.Azure.Cosmos.Table and New Storage Client library [Microsoft.Azure.Storage.Blob/Queue/File](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/)

@markcowl,  we should schedule a new preview version of Az.Storage to resolve the issue. The code on storage preview release branch is already based on new  Storage Client library and Microsoft.Azure.Cosmos.Table. I will discuss with you by mail in detail.

**Comment by blueww** [comment]
@tinodo
[Az.Storage 1.2.1-preview](https://www.powershellgallery.com/packages/Az.Storage/1.2.1-preview) has been released, which already reference Microsoft.Azure.Cosmos.Table.dll. It can be used together with latest AzureRmStorageTable module.
So I will close the issue.

Feel free to let me know if you need further assistant.
