### ISSUE TITLE
Dns Module

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#8953]
## Description
Generate Dns Module
- [x] Configuration
- [x] Simple customizations
- [x] Help
- [x] File issues for new bugs / new patterns for AutoRest
- [x] File issues for needed test or customization infrastructure
- [ ] Estimate additional customization necessary

**Comment by cormacpayne** [comment]
Issue to track required work for Dns found here: https://github.com/Azure/azure-powershell/issues/9370
