### ISSUE TITLE
Billing Module

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#8954]
## Description
Generate Billing Module
- [x] Configuration
- [x] Simple customizations
- [x] Help
- [x] File issues for new bugs / new patterns for AutoRest
- [x] File issues for needed test or customization infrastructure
- [x] Estimate additional customization necessary

**Comment by cormacpayne** [comment]
Issue to track work found here: https://github.com/Azure/azure-powershell/issues/9358
