### ISSUE TITLE
Update Private Repo and Enable CI runs against it

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#8960]
## Description
- [x] Update privatre repo master branch to match master branch
- [x] Add ADO pipeline info
- [ ] Add updatign private master branch to end-of-release activities

**Comment by markcowl** [comment]
@erich-wang Can you please validate that updating the master branch in the private repo si added to the end of release instructiosn here: https://github.com/Azure/azure-powershell-pr/wiki/Release-Process

**Comment by cormacpayne** [comment]
@markcowl please verify that this is completed
