### ISSUE TITLE
how to apply TTL using New-AzureRmServiceBusSubscription in seconds?

### ISSUE THREAD

**Issue by kvattikuti** [Azure/azure-powershell#8964]
It is not clear from documentation how to apply DefaultMessageTimeToLive in seconds. Is it always in Days? Is it not possible to specify units?

https://docs.microsoft.com/en-us/powershell/module/azurerm.servicebus/new-azurermservicebussubscription?view=azurermps-6.13.0#examples

**Comment by maddieclayton** [comment]
@v-Ajnava Can you take a look at this issue?

**Comment by v-Ajnava** [comment]
@kvattikuti , will take look and update the thread.

**Comment by v-Ajnava** [comment]
@kvattikuti here is the example to apply TTL for subscription, we will update document with more details. 
-DefaultMessageTimeToLive "PT20S"

let us know if you have any questions?
