### ISSUE TITLE
Stop-AzureRmVM: -AsJob parameter is not working in runbooks

### ISSUE THREAD

**Issue by PraveenGururaj** [Azure/azure-powershell#8969]
Hi,

I was trying to stop multiple VM's using Azure runbook so I was using set PowerShell cmdlets which I used in my local machine.

Script which I used:

Clear-Host
$csv = Import-Csv $env:USERPROFILE\downloads\srv1.csv
foreach($line in $csv)
{
Start-AzureRmVM -Name $line.name -ResourceGroupName $line.rg -AsJob -Verbose
}

when I tried to integrate this in Azure - PowerShell runbook, I was getting error that -AsJob parameter is not found.

Stop-AzureRmVM : A parameter cannot be found that matches parameter name 'AsJob'.
At line:1 char:87

Can -AsJob parameter be integrated to trigger actions as jobs in runbooks as well?

-Praveen

**Comment by maddieclayton** [comment]
@PraveenGururaj Can you please upgrade your runbook to Az and rerun the command? I believe that the version of AzureRM that you are using may not contain the -AsJob functionality.

**Comment by PraveenGururaj** [comment]
After updating the module relevant parameters are working. Closing this thread.

How to Update Azure PowerShell Module?
[https://docs.microsoft.com/en-us/azure/automation/automation-update-azure-modules#update-azure-modules-in-the-azure-portal]
