### ISSUE TITLE
appservice: Get-AzAppServicePlanMetrics & Get-AzWebAppMetrics should be marked deprecated

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-powershell#8975]
Azure AppService no longer supports these command & should be marked deprecated . The recommended command is Get-AzMetric, https://docs.microsoft.com/en-us/powershell/module/Az.Monitor/Get-AzMetric?view=azps-1.7.0

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by william-li-nintex** [comment]
The documentation is still [here](https://docs.microsoft.com/en-us/powershell/module/az.websites/get-azappserviceplanmetrics?view=azps-0.10.0), ijust wondering is this idle now? Thanks
