### ISSUE TITLE
Policy Assignment Update not working - Powershell Command

### ISSUE THREAD

**Issue by SomilGanguly** [Azure/azure-powershell#8980]
The Set-AzureRmPolicyAssignment does currently not support a "PolicyParamater" or "PolicyParameterObject" (https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/set-azurermpolicyassignment?view=azurermps-6.13.0).

**Comment by maddieclayton** [comment]
@cormacpayne It seem like we are missing an inputobject piping parameter set for this cmdlet. If we don't have bandwidth to fix this can you assign to the correct person on the Resources team?

**Comment by cormacpayne** [comment]
@mentat9 Hey Chris, would your team be able to incorporate these changes into the `*-AzPolicy*` cmdlets?

**Comment by mentat9** [comment]
Yes, good suggestion. I've created a work item on our team to add this capability.

**Comment by mentat9** [comment]
This is fixed in https://github.com/Azure/azure-powershell/pull/9441. Please take a look and comment or approve.
