### ISSUE TITLE
Remove-AzureVMExtension calls enable command in Linux VM.

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-powershell#9]
When executing Remove-AzureVMExtension against a Linux VM, enable command will be called in Linux VM. Expect uninstall command is called.

**Comment by singhkay** [comment]
@AbelHu You should use the Set-AzureVMExtension -Uninstall for uninstalling the cmdlet. Remove-AzureVMExtension only removes the cmdlet from the local object for ASM module.
