### ISSUE TITLE
Get-AzureVMDscExtensionStatus does not work when using a VM object

### ISSUE THREAD

**Issue by TravisEz13** [Azure/azure-powershell#900]
Get-AzureVMDscExtensionStatus does not work when using a VM object

# Repro
1) create a VM and set the DSC extension on the VM
2) $vm = get-azurevm -ServiceName ServiceName -Name VmName
3) Get-AzureVMDscExtensionStatus -vm $vm

# Expected
Give you the status of DSC on the specified VM or an error indicating the DSC extension is not on the VM

# Actual
returns nothing

**Comment by alexandair** [comment]
Is this new in 0.9.8? If I recall correctly, it's worked before.

**Comment by devigned** [comment]
It's in the dev branch. We'll close after release of 0.9.9.

**Comment by TravisEz13** [comment]
@alexandair Yes, this is a regression in 0.9.8.  I have fix submitted for 0.9.9 as devigned mentioned.
