### ISSUE TITLE
Getting replacement Az or AzureRM command for the Set-AzureReservedIPAssociation ASM command.

### ISSUE THREAD

**Issue by sadman-work** [Azure/azure-powershell#9001]
The specific issue is related to ASM commands:

The issue that I’m having is that there is no replacement call in the Az (or ARM) module library for  the following command.
Set-AzureReservedIPAssociation. 

I realize that Reserved IP is a classic component, however, it is required for part of our application to work correctly.

I need the replacement AzureRM or Az command for changing my script.

**Comment by maddieclayton** [comment]
@MikhailTryakhov Can you take a look at this feature request and direct it to the correct Network team to comment?

**Comment by anavinahar** [comment]
You cannot reference a classic object from ARM.

Are you asking for a way to reserve an ARM IP?
