### ISSUE TITLE
Azure automation scripts still on AzureRM

### ISSUE THREAD

**Issue by jackvandeur** [Azure/azure-powershell#9002]
I just read the article where the AZ module for powershell is introduced as the successor of AzureRM. It furthermore tells you to get rid of AzureRM as soon as possible and to reewrite your scripts using the new AZ commands. It is kind of strange though that Microsoft Azure still spits out automation scripts using AzureRM commands. How come?

**Comment by maddieclayton** [comment]
@vrdmr Can you direct this to the correct Automation team?

**Comment by madhanan** [comment]
@jackvandeur Kindly requesting to elaborate the the strange behavior.
i am not sure when Microsoft Azure will provide automation account using Az module by default.

At present, it is supplied with AzureRM modules. But those are default modules, if you want to use Az modules - please import only Az  modules (install / update) only Az modules.

Dont try to remove Default AzureRM modules - it wont work

**Comment by andyw248** [comment]
See https://docs.microsoft.com/en-us/azure/automation/az-modules. Replacing AzureRm modules with Az modules by default is in the backlog but not highest priority.
