### ISSUE TITLE
get-azlog -Maxrecord example should be changed

### ISSUE THREAD

**Issue by shammyowens** [Azure/azure-powershell#9011]
The webpage for get-azlog shows examples which use -maxevents.  The actual parameter you need is -maxrecord as stated further down in the document.

 https://docs.microsoft.com/en-us/powershell/module/az.monitor/get-azlog?view=azps-1.7.0

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

This is first time in logging an issue, so apologies if I have missed anything.

**Comment by niander** [comment]
Closing issue since PR #9133 fixes it
