### ISSUE TITLE
Ability to remove old SQL Auditing method

### ISSUE THREAD

**Issue by iyoumans** [Azure/azure-powershell#9019]
Our environment currently has all of the SQL Servers auditing (and threat detection from back when) pointed at storage accounts. We want to convert all of them to point to Log Analytics (in order to get rid of dozens of storage accounts). However, Set-AzSqlServerAuditing to enable Log Analytics doesn't remove the auditing to the storage account, and there is no Remove auditing cmdlet any more. How should we go about it?

**Comment by maddieclayton** [comment]
@jaredmoo Can you take a look at this feature request?

**Comment by iyoumans** [comment]
Addendum - using Set -State Disabled and then again to enabled Log Analytics worked for me. So this can probably be closed (in fact I will close it). Note, however, that this is very confusing and doesn't match how the Threat Detection APIs work (they have a Remove). Plus, it is not documented well, and after enabling Log Analytic logging, the Get-AzSqlServerAuditing still shows as Disabled even though the logging is working.

I guess bottom line I realize it's preview but it's still a bit of a mess, and the migration path (which I think would be the natural next step for most people) is not well documented.

**Comment by bashahee** [comment]
@iyoumans 
Audit logs destination is determined by specifying one of the following switch parameters: `BlobStorage`, `LogAnalytics` or `EventHub`, if none is specified, the default is `BlobStorage` (This is documented under cmdlet description section when running `Get-Help Get-AzSqlServerAuditing`). This is also true for `Set-AzSqlServerAuditing` cmdlet.
Running `Get-AzSqlServerAuditing` without providing a switch parameter retrieves the auditing settings with blob storage as a target, which is disabled in the scenario you described.
In order to retrieve auditing settings with log analytics as a target, you need to provide 
`-LogAnalytics` switch parameter.

**Comment by iyoumans** [comment]
Thank you, that worked! I must say, however, that the behavior doesn't match other Az Get cmdlets. For example, I don't have to pass a -Linux or -Windows switch to Get-AzVm.

**Comment by bashahee** [comment]
@iyoumans 
User can set, **simultaneously**, blob storage, event hub, and log analytics as targets of audit logs. Hence, there is a need to specify the destination when retrieving auditing settings.

**Comment by iyoumans** [comment]
I agree that there's a need to specify destination on the Set. However, the Get should return one object with all possible audit settings, and just set the unused properties to null/empty string. This is how most (all? almost all?) of the Azure APIs work - providing one object type returned regardless of parameter set passed in. If you are unaware of the unique nature of this Get, you will get the default result (storage account) and could get the impression that auditing is not on despite being set for something else. If I want to ensure I get all of the auditing information for a particular database, I need to call this Get three times, which is not ideal.

**Comment by bashahee** [comment]
@iyoumans We initiated a design of new cmdlets where `Get` cmdlets will provide one object type regardless of parameter set passed.
Thanks a lot for sharing your feedback!

**Comment by iyoumans** [comment]
Cool - thanks!
