### ISSUE TITLE
Disable-azuredatacollection prompts if you want to disable azure data collection in non-interactive session

### ISSUE THREAD

**Issue by TravisEz13** [Azure/azure-powershell#902]
Disable-azuredatacollection prompts if you want to disable azure data collection in non-interactive session

# Repro

```powershell
del "$env:appdata\Windows Azure Powershell\AzureDataCollectionProfile.json" -Force -ErrorAction Ignore
powershell -NonInteractive -command Disable-azuredatacollection
```

# Expected results
Data collection is disabled without prompting (since there is no parameter to suppress prompting)

# Actual results

> prompt> powershell -NonInteractive -command Disable-azuredatacollection
>WARNING: Microsoft Azure PowerShell collects data about how users use PowerShell cmdlets and some problems they encounter.  Microsoft uses this information to improve our PowerShell
>cmdlets.  Participation is voluntary and when you choose to participate your device automatically sends information to Microsoft about how you use Azure PowerShell.
>
>If you choose to participate, you can stop at any time by using Azure PowerShell as follows:
>1. Use the Disable-AzureDataCollection cmdlet to turn the feature Off. The cmdlet can be found in the AzureResourceManager module
>To disable data collection: PS > Disable-AzureDataCollection
>
>If you choose to not participate, you can enable at any time by using Azure PowerShell as follows:
>1. Use the Enable-AzureDataCollection cmdlet to turn the feature On. The cmdlet can be found in the AzureResourceManager module
>To enable data collection: PS > Enable-AzureDataCollection
>
>Select Y to enable data collection [Y/N]:
>WARNING: You choose not to participate in Microsoft Azure PowerShell data collection.
>WARNING: The setting profile has been saved to the following path 'C:\Users\tplunk\AppData\Roaming\Windows Azure Powershell\AzureDataCollectionProfile.json'.
>WARNING: The setting profile has been saved to the following path 'C:\Users\tplunk\AppData\Roaming\Windows Azure Powershell\AzureDataCollectionProfile.json'.

**Comment by devigned** [comment]
We will address this issue. Thank you for reporting this issue.

**Comment by thoutekier** [comment]
Is there already any feedback on this?  In encounter the same issue when using cmdlet New-AzureStorageContext in a powershell script executed by a Team Foundation Build 2015 Powershell task.  As a consequence, the build is blocked and times out (or should be cancelled).

**Comment by devigned** [comment]
@thoutekier this should not cause the build to timeout. At the worst, the cmd should prompt and wait for only 60 seconds or so.

**Comment by devigned** [comment]
@thoutekier this is scheduled to be fixed in 1.0, which will be released in the coming weeks.

**Comment by thoutekier** [comment]
Thanks for your reply.  You're right, there is a timeout after 60 seconds.  Apparently I didn't wait long enough and cancelled the build to fast.  I'm looking forward to get this fixed since this will save us 1 minute build time per build.

**Comment by hovsepm** [comment]
Fixed in dev branch.
