### ISSUE TITLE
Static Analysis: Breaking change when default parameter set added

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#9023]
## Description
Shows something like this: (from here: https://github.com/Azure/azure-powershell/pull/9018)
```
"Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.SetAzureVirtualNetworkGatewayConnectionCommand","Set-AzVirtualNetworkGatewayConnection","0","1050","The parameter set '__AllParameterSets' for cmdlet 'Set-AzVirtualNetworkGatewayConnection' has been removed.","Add parameter set '__AllParameterSets' back to cmdlet 'Set-AzVirtualNetworkGatewayConnection'."
```

`__AllParameterSets` is the default parameter set name when none is specified. This is seen as a breaking change because that parameter set no longer exists after you add a default parameter set. This condition should not be flagged as a breaking change.

## Cost
1

**Comment by markcowl** [comment]
this is a false positive we won't change for now
