### ISSUE TITLE
Static Analysis: Breaking change when parameter set is removed from parameters, but is the default parameter set

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#9024]
## Description
Looks something like this: (from here: https://github.com/Azure/azure-powershell/pull/9018)
```
"Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.SetAzureVirtualNetworkGatewayCommand","Set-AzVirtualNetworkGateway","0","1050","The parameter set 'Default' for cmdlet 'Set-AzVirtualNetworkGateway' has been removed.","Add parameter set 'Default' back to cmdlet 'Set-AzVirtualNetworkGateway'."
```

Basically, if the parameter set was stated explicitly on a parameter and now, no longer is explicitly stated, it says there was a breaking change. However, the parameter set still does exist because, in this case, `Default` is still the default parameter set (which means it does exist). So, the parameter sets that exist are not a collection of parameter sets from the parameters, it is actually a collection that exists to the cmdlet itself.

## Cost
2

**Comment by markcowl** [comment]
won't fix, this is a false positive that we don't want to avoid.
