### ISSUE TITLE
Static Analysis: Not recognizing 'ValueFromPipelineByPropertyName = true' removal as breaking change

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#9025]
## Description
(from here: https://github.com/Azure/azure-powershell/pull/9018)
When `ValueFromPipelineByPropertyName = true` is removed (or changed to false), it should be recognized as a breaking change. Right now, it doesn't seem to recognize this situation. Existing scripts could be passing values in the pipeline by property name. Thus, removing this would break them.

## Cost
1

**Comment by markcowl** [comment]
here is an example: https://github.com/Azure/azure-powershell/pull/9018/files/32a73607e13184e65874a75b5442d8584aff54fa#diff-24497f874e4beee9808ecb3bf90f4535

**Comment by cormacpayne** [comment]
[Here](https://github.com/Azure/azure-powershell/blob/5ea221a6cbcfdc3284f294f4028a301dd564c915/tools/StaticAnalysis/BreakingChangeAnalyzer/ParameterSetMetadataHelper.cs#L96-L97) we're comparing all parameters for the old parameter set to a potential matching parameter set, making sure that all properties of the parameter are the same before consider them matching. If the `ValueFromPipeline` or `ValueFromPipelineByPropertyName` properties were previously there for a parameter, but not for the same parameter in a set for the new cmdlet metadata, then we consider those sets as non-matching and move to the next one. I made similar changes to that in the PR linked above and found that the tool was correctly adding the errors to the logger, so I'm not sure if this was a one-off issue with the above PR, but I think we should close this until it occurs again and we can do a deeper investigation.
