### ISSUE TITLE
Documentation for Get-AzRecoveryServicesVaultSettingsFile is incorrect

### ISSUE THREAD

**Issue by tinodo** [Azure/azure-powershell#9029]
## Description

The documentation for Get-AzRecoveryServicesVaultSettingsFile is incorrect.
Today, the **-Certificate** parameter is mandatory and not present in any examples. Also, there is no description for this parameter.

Can this be modified for clarity?

**Comment by ikiris04** [comment]
+1, I just ran into this. There is also no description of what the certificate is used for. I ended up generating a self-signed cert in keyvault, grabbing that data and base64 encoding it to pass to -certificate

**Comment by markcowl** [comment]
@siddharth7 @pvrk Can you take a look?

**Comment by siddharth7** [comment]
@viverm Can you update this?

**Comment by pvrk** [comment]
Updated the document with the [example](https://docs.microsoft.com/azure/backup/backup-client-automation#registering-using-the-ps-az-module) for certificate

**Comment by pvrk** [comment]
#please-close

**Comment by pvrk** [comment]
@markcowl : can you please close this issue?

**Comment by pvrk** [comment]
Updated the document with the example for certificate. Closing this issue.
