### ISSUE TITLE
dev branch could not be built correct now.

### ISSUE THREAD

**Issue by andyliuliming** [Azure/azure-powershell#903]
"C:\Personal\azure-powershell\build.proj" (BuildDebug target) (1) ->
"C:\Personal\azure-powershell\src\ResourceManager.sln" (Build target) (2) ->
"C:\Personal\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj" (default target) (3
0) ->
(CoreCompile target) ->
  c:\Personal\azure-powershell\src\Common\Commands.ResourceManager.Common\bin\Debug\Microsoft.Azure.Command
s.ResourceManager.Common.dll : error CS1684: Warning as Error: Reference to type 'Microsoft.Azure.Common.Au
thentication.Models.AzureRMProfile' claims it is defined in 'c:\Personal\azure-powershell\src\packages\Micr
osoft.Azure.Common.Authentication.1.1.3-preview\lib\net45\Microsoft.Azure.Common.Authentication.dll', but i
t could not be found [C:\Personal\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj
]
  c:\Personal\azure-powershell\src\Common\Commands.ResourceManager.Common\bin\Debug\Microsoft.Azure.Command
s.ResourceManager.Common.dll : error CS1684: Warning as Error: Reference to type 'Microsoft.Azure.Common.Au
thentication.Models.AzureRMProfile' claims it is defined in 'c:\Personal\azure-powershell\src\packages\Micr
osoft.Azure.Common.Authentication.1.1.3-preview\lib\net45\Microsoft.Azure.Common.Authentication.dll', but i
t could not be found [C:\Personal\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj
]
  c:\Personal\azure-powershell\src\Common\Commands.ResourceManager.Common\bin\Debug\Microsoft.Azure.Command
s.ResourceManager.Common.dll : error CS1684: Warning as Error: Reference to type 'Microsoft.Azure.Common.Au
thentication.Models.AzureRMProfile' claims it is defined in 'c:\Personal\azure-powershell\src\packages\Micr
osoft.Azure.Common.Authentication.1.1.3-preview\lib\net45\Microsoft.Azure.Common.Authentication.dll', but i
t could not be found [C:\Personal\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj
]
  c:\Personal\azure-powershell\src\Common\Commands.ResourceManager.Common\bin\Debug\Microsoft.Azure.Command
s.ResourceManager.Common.dll : error CS1684: Warning as Error: Reference to type 'Microsoft.Azure.Common.Au
thentication.Models.AzureRMProfile' claims it is defined in 'c:\Personal\azure-powershell\src\packages\Micr
osoft.Azure.Common.Authentication.1.1.3-preview\lib\net45\Microsoft.Azure.Common.Authentication.dll', but i
t could not be found [C:\Personal\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj
]
  Location Capabilities\Cmdlet\GetAzureSqlCapability.cs(93,83): error CS0570: 'Microsoft.Azure.Commands.Res
ourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-power
shell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Common\AzureSqlCmdletBase.cs(93,45): error CS0570: 'Microsoft.Azure.Commands.ResourceManager.Common.Azure
RMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-powershell\src\ResourceManager
\Sql\Commands.Sql\Commands.Sql.csproj]
  Auditing\Cmdlet\SqlDatabaseAuditingCmdletBase.cs(43,40): error CS0570: 'Microsoft.Azure.Commands.Resource
Manager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-powershell
\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Auditing\Cmdlet\SqlDatabaseServerAuditingCmdletBase.cs(51,40): error CS0570: 'Microsoft.Azure.Commands.Re
sourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-powe
rshell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Data Masking\Cmdlet\SqlDatabaseDataMaskingRuleCmdletBase.cs(65,46): error CS0570: 'Microsoft.Azure.Comman
ds.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure
-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Data Masking\Cmdlet\SqlDatabaseDataMaskingPolicyCmdletBase.cs(43,46): error CS0570: 'Microsoft.Azure.Comm
ands.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azu
re-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Database Activation\Cmdlet\AzureSqlDatabaseActivationCmdletBase.cs(56,58): error CS0570: 'Microsoft.Azure
.Commands.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Persona
l\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Database Backup\Cmdlet\AzureSqlDatabaseRestorePointCmdletBase.cs(55,54): error CS0570: 'Microsoft.Azure.C
ommands.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\
azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Database\Cmdlet\AzureSqlDatabaseActivityCmdletBase.cs(71,48): error CS0570: 'Microsoft.Azure.Commands.Res
ourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-power
shell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Database\Cmdlet\AzureSqlDatabaseCmdletBase.cs(42,48): error CS0570: 'Microsoft.Azure.Commands.ResourceMan
ager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-powershell\sr
c\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Database\Cmdlet\GetAzureSqlDatabaseExpanded.cs(54,48): error CS0570: 'Microsoft.Azure.Commands.ResourceMa
nager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-powershell\s
rc\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Elastic Pools\Cmdlet\AzureSqlElasticPoolActivityCmdletBase.cs(52,51): error CS0570: 'Microsoft.Azure.Comm
ands.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azu
re-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Elastic Pools\Cmdlet\AzureSqlElasticPoolCmdletBase.cs(42,51): error CS0570: 'Microsoft.Azure.Commands.Res
ourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-power
shell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Elastic Pools\Cmdlet\GetAzureSqlElasticPoolDatabase.cs(71,45): error CS0570: 'Microsoft.Azure.Commands.Re
sourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-powe
rshell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  FirewallRule\Cmdlet\AzureSqlServerFirewallRuleCmdletBase.cs(43,58): error CS0570: 'Microsoft.Azure.Comman
ds.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure
-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Index Recommendations\Cmdlet\AzureSqlDatabaseExecuteIndexRecommendationCmdletBase.cs(97,67): error CS0570
: 'Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the la
nguage [C:\Personal\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Index Recommendations\Cmdlet\GetAzureSqlDatabaseIndexRecommendations.cs(108,67): error CS0570: 'Microsoft
.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\P
ersonal\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  RecommendedElasticPools\Cmdlet\GetAzureSqlElasticPoolRecommendation.cs(45,65): error CS0570: 'Microsoft.A
zure.Commands.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Per
sonal\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Replication\Cmdlet\AzureSqlDatabaseCopyCmdletBase.cs(42,59): error CS0570: 'Microsoft.Azure.Commands.Reso
urceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-powers
hell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Replication\Cmdlet\AzureSqlDatabaseSecondaryCmdletBase.cs(42,59): error CS0570: 'Microsoft.Azure.Commands
.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-p
owershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Secure Connection\Cmdlet\SqlDatabaseSecureConnectionCmdletBase.cs(43,51): error CS0570: 'Microsoft.Azure.
Commands.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal
\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  Server\Cmdlet\AzureSqlServerCmdletBase.cs(32,46): error CS0570: 'Microsoft.Azure.Commands.ResourceManager
.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-powershell\src\Re
sourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  ServerActiveDirectoryAdministrator\Cmdlet\AzureSqlServerActiveDirectoryAdministratorCmdletBase.cs(43,74):
 error CS0570: 'Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not suppor
ted by the language [C:\Personal\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  ServerActiveDirectoryAdministrator\Services\AzureSqlServerActiveDirectoryAdministratorAdapter.cs(269,39):
 error CS1061: 'Microsoft.Azure.Common.Authentication.Models.AzureContext' does not contain a definition fo
r 'Tenant' and no extension method 'Tenant' accepting a first argument of type 'Microsoft.Azure.Common.Auth
entication.Models.AzureContext' could be found (are you missing a using directive or an assembly reference?
) [C:\Personal\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  ServerUpgrade\Cmdlet\AzureSqlServerUpgradeCmdletBase.cs(45,53): error CS0570: 'Microsoft.Azure.Commands.R
esourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-pow
ershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  ServiceObjective\Cmdlet\AzureSqlServerServiceObjectiveCmdletBase.cs(33,62): error CS0570: 'Microsoft.Azur
e.Commands.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Person
al\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  ServiceTierAdvisor\Cmdlet\GetAzureSqlUpgradeDatabaseHint.cs(84,58): error CS0570: 'Microsoft.Azure.Comman
ds.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure
-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  ServiceTierAdvisor\Cmdlet\GetAzureSqlUpgradeServerHint.cs(64,87): error CS0570: 'Microsoft.Azure.Commands
.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-p
owershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  ServiceTierAdvisor\Cmdlet\GetAzureSqlUpgradeServerHint.cs(80,58): error CS0570: 'Microsoft.Azure.Commands
.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the language [C:\Personal\azure-p
owershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  TransparentDataEncryption\Cmdlet\AzureSqlDatabaseTransparentDataEncryptionActivityCmdletBase.cs(53,73): e
rror CS0570: 'Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supporte
d by the language [C:\Personal\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]
  TransparentDataEncryption\Cmdlet\AzureSqlDatabaseTransparentDataEncryptionCmdletBase.cs(53,73): error CS0
570: 'Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.DefaultProfile' is not supported by the
 language [C:\Personal\azure-powershell\src\ResourceManager\Sql\Commands.Sql\Commands.Sql.csproj]

    272 Warning(s)
    35 Error(s)

**Comment by devigned** [comment]
We have been going through a major refactor. Please grab the latest and run `git clean -dfx` (warning, this will clean all non-git committed files).

**Comment by devigned** [comment]
Please reopen if it still repros.
