### ISSUE TITLE
Get-AzSecurityTask doesn't provide Severity information

### ISSUE THREAD

**Issue by msnnpatel** [Azure/azure-powershell#9057]
## Description of the new feature
Currently when running Get-AzSecurityTask it doesn't provide information about severity of the task/recommendation. This information is visible in Azure Portal. 
As you can understand that this will be vital information for customer to prioritize their remediation of all the recommendations.

**Comment by chlahav** [comment]
@msnnpatel This is a known issue and the severity is also not visible in the API itself.
we are working on creating a new API that will be more convenient in its structure and will contain the severity as well.

**Comment by omerchechik** [comment]
The tasks API is pending deprecation.
Please use assessment API instead (https://docs.microsoft.com/en-us/rest/api/securitycenter/assessments/get)
The severity is part of the assessment metadata API (https://docs.microsoft.com/en-us/rest/api/securitycenter/assessmentsmetadata)
