### ISSUE TITLE
Remove the need of -BypassObjectIdValidation parameter in Set-AzureRmKeyvaultAccessPolicy 

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#9063]
## Description
The parameter is being needed only for the Azurestack ADFS environments
Keyvault module uses this latest version of graphclient https://www.nuget.org/packages/Microsoft.Azure.ActiveDirectory.GraphClient . 

This Graphclient uses ODATA 3. It works fine against AAD and not against ADFS as it supports only ODATA 4. So KV team introduced a parameter -ByPassObjectIdValidation in Set-AzureRmKeyvaultAccessPolicy cmdlet, creating a disparity with azure.

**Comment by dingmeng-xue** [comment]
@bganapa , is this issue still valid in Az version? This cmdlet belongs to AKV. Shall it be fixed in KeyVault module?

**Comment by bganapa** [comment]
We still have this in Az version. @TheOnlyWei  Could you pls file a internal item to track and take this up for the upcoming sprint?

**Comment by bganapa** [comment]
@TheOnlyWei We need to check with the new Az modules whether it is using Odata 3 or Odata 4. If it is using Odata4 , then we could remove the need of BypassObjectIdValidation parameter. We will be in consisistent with azure for ADFS

**Comment by bganapa** [comment]
This is fixed in Az version of the modules. The latest Azurestack specific 2020-09-01-hybrid profile Az modules have the fix
