### ISSUE TITLE
Set-AzResource fails for ResourceType  "microsoft.insights/scheduledqueryrules"

### ISSUE THREAD

**Issue by ikanni** [Azure/azure-powershell#9067]
## Description
Set-AzResource fails for ResourceType  "microsoft.insights/scheduledqueryrules" with error "value": "Value cannot be null.\r\nParameter name: 'properties' property must be specified"

## Steps to reproduce

```powershell
Set $DebugPreference='Continue' 


$Subscription = Select-AzSubscription -SubscriptionId $SubscriptionId

    $rgroup = Get-AzResourceGroup -Name JPE-Test-ikanni-StartStop-VM-RG
    foreach ($group in $rgroup){
    $lock = Get-AzResourceLock -ResourceGroupName $group.ResourceGroupName
    $lockState = $lock.Properties.level    
        if ( ($null -ne $group.Tags) -and ( $lockState -ne "ReadOnly") ) {
            $resources = Get-AzResource -ResourceGroupName $group.ResourceGroupName
            foreach ($r in $resources)
            {
                $resourcetags = (Get-AzResource -ResourceId $r.ResourceId).Tags
                if ($resourcetags)
                {
                    foreach ($key in $group.Tags.Keys)
                    {
                        if (-not($resourcetags.ContainsKey($key)))
                        {
                            $resourcetags.Add($key, $group.Tags[$key])
                        }
                    }
                    if ($r.ResourceType -contains "microsoft.insights/scheduledqueryrules") {
                      Set-AzResource -Tag $resourcetags -ResourceId $r.ResourceId -Force
                    }
                }
                else
                {
                    Set-AzResource -Tag $group.Tags -ResourceId $r.ResourceId -Force
                }
            }
        }
    }  
```

## Environment data

```
PS C:\Users\ikanni>> $PSVersionTable 

Name                           Value                                                                                                                                                         
----                           -----                                                                                                                                                         
PSVersion                      5.1.14409.1018                                                                                                                                                
PSEdition                      Desktop                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                       
BuildVersion                   10.0.14409.1018                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                           
SerializationVersion           1.1.0.1                                                                                                                                                       

```

## Module versions

```powershell
PS C:\Users\ikanni>> Get-Module -Name Az.* -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                                   
---------- -------    ----                                ----------------                                                                                                                   
Script     1.5.1      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}                        
Script     1.2.1      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDs...
Script     1.3.1      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}                                  

Note: This issue is reproduce in AzureRM modules too.
```

## Debug output

```
PS C:\Users\ikanni>> C:\ikanni\ICM-UpdateTags.ps1
Set-AzResource : {
  "error": {
    "code": "Value cannot be null.",
    "message": {
      "lang": "en-US",
      "value": "Value cannot be null.\r\nParameter name: 'properties' property must be specified"
    },
    "innererror": {
      "stacktrace": "System.ArgumentNullException: Value cannot be null.\r\nParameter name: 'properties' property must be specified\r\n   at 
Microsoft.AppInsights.Nexus.ResourceProvider.ScheduledQueryRules.ScheduledQueryRulesProvider.<PatchResourceAsync>d__30`1.MoveNext() in 
X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Nexus\\ResourceProvider\\ScheduledQueryRules\\ScheduledQueryRulesProvider.cs:line 406\r\n--- End of stack trace from previous location where exception 
was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task)\r\n   at Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.CsmResourcesNxControllerBase`1.<>c__DisplayClass14_0.<<PatchResourceAsync>b__0>d.MoveNext() in 
X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\CsmResourcesNxControllerBase.cs:line 242\r\n--- End of stack trace from previous location where exception was 
thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task)\r\n   at Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.NexusControllerBase.<PerformActionAsync>d__17.MoveNext() in 
X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\NexusControllerBase.cs:line 97"
    }
  }
}
At C:\ikanni\ICM-UpdateTags.ps1:28 char:23
+ ...             Set-AzResource -Tag $resourcetags -ResourceId $r.Resource ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet
 
Set-AzResource : {
  "error": {
    "code": "Value cannot be null.",
    "message": {
      "lang": "en-US",
      "value": "Value cannot be null.\r\nParameter name: 'properties' property must be specified"
    },
    "innererror": {
      "stacktrace": "System.ArgumentNullException: Value cannot be null.\r\nParameter name: 'properties' property must be specified\r\n   at 
Microsoft.AppInsights.Nexus.ResourceProvider.ScheduledQueryRules.ScheduledQueryRulesProvider.<PatchResourceAsync>d__30`1.MoveNext() in 
X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Nexus\\ResourceProvider\\ScheduledQueryRules\\ScheduledQueryRulesProvider.cs:line 406\r\n--- End of stack trace from previous location where exception 
was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task)\r\n   at Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.CsmResourcesNxControllerBase`1.<>c__DisplayClass14_0.<<PatchResourceAsync>b__0>d.MoveNext() in 
X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\CsmResourcesNxControllerBase.cs:line 242\r\n--- End of stack trace from previous location where exception was 
thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task)\r\n   at Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.NexusControllerBase.<PerformActionAsync>d__17.MoveNext() in 
X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\NexusControllerBase.cs:line 97"
    }
  }
}
At C:\ikanni\ICM-UpdateTags.ps1:28 char:23
+ ...             Set-AzResource -Tag $resourcetags -ResourceId $r.Resource ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet
 
Set-AzResource : {
  "error": {
    "code": "Value cannot be null.",
    "message": {
      "lang": "en-US",
      "value": "Value cannot be null.\r\nParameter name: 'properties' property must be specified"
    },
    "innererror": {
      "stacktrace": "System.ArgumentNullException: Value cannot be null.\r\nParameter name: 'properties' property must be specified\r\n   at 
Microsoft.AppInsights.Nexus.ResourceProvider.ScheduledQueryRules.ScheduledQueryRulesProvider.<PatchResourceAsync>d__30`1.MoveNext() in 
X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Nexus\\ResourceProvider\\ScheduledQueryRules\\ScheduledQueryRulesProvider.cs:line 406\r\n--- End of stack trace from previous location where exception 
was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task)\r\n   at Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.CsmResourcesNxControllerBase`1.<>c__DisplayClass14_0.<<PatchResourceAsync>b__0>d.MoveNext() in 
X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\CsmResourcesNxControllerBase.cs:line 242\r\n--- End of stack trace from previous location where exception was 
thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task)\r\n   at Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.NexusControllerBase.<PerformActionAsync>d__17.MoveNext() in 
X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\NexusControllerBase.cs:line 97"
    }
  }
}
At C:\ikanni\ICM-UpdateTags.ps1:28 char:23
+ ...             Set-AzResource -Tag $resourcetags -ResourceId $r.Resource ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet
```

## Error output

```
PS C:\Users\ikanni>> Resolve-AzureRmError
Resolve-AzureRmError : Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 
'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
At line:1 char:1
+ Resolve-AzureRmError
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Resolve-AzureRmError], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.Azure.Commands.Profile.Errors.ResolveError
```

**Comment by markcowl** [comment]
@ikanni Can you run Resolve-AzError: it looks like you are runjnign Resolve-AzureRmError from AzureRM.Profile

**Comment by ikanni** [comment]
### Correct Error output

PS C:\Users\ikanni>  Resolve-AzError


   HistoryId: 1


Message        : {
                   "error": {
                     "code": "Value cannot be null.",
                     "message": {
                       "lang": "en-US",
                       "value": "Value cannot be null.\r\nParameter name: 'properties' property must be specified"
                     },
                     "innererror": {
                       "stacktrace": "System.ArgumentNullException: Value cannot be null.\r\nParameter name: 'properties' property must be specified\r\n   at 
                 Microsoft.AppInsights.Nexus.ResourceProvider.ScheduledQueryRules.ScheduledQueryRulesProvider.<PatchResourceAsync>d__30`1.MoveNext() in 
                 X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Nexus\\ResourceProvider\\ScheduledQueryRules\\ScheduledQueryRulesProvider.cs:line 406\r\n--- End of stack trace from previous location 
                 where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at 
                 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at 
                 Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.CsmResourcesNxControllerBase`1.<>c__DisplayClass14_0.<<PatchResourceAsync>b__0>d.MoveNext() in 
                 X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\CsmResourcesNxControllerBase.cs:line 242\r\n--- End of stack trace from previous location where 
                 exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at 
                 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at 
                 Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.NexusControllerBase.<PerformActionAsync>d__17.MoveNext() in 
                 X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\NexusControllerBase.cs:line 97"
                     }
                   }
                 }
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.ErrorResponses.ErrorResponseMessageException
InvocationInfo : {Set-AzResource}
Line           :                       Set-AzResource -Tag $resourcetags -ResourceId $r.ResourceId -Force
                 
Position       : At C:\ikanni\ICM-UpdateTags.ps1:28 char:23
                 + ...             Set-AzResource -Tag $resourcetags -ResourceId $r.Resource ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

Message        : {
                   "error": {
                     "code": "Value cannot be null.",
                     "message": {
                       "lang": "en-US",
                       "value": "Value cannot be null.\r\nParameter name: 'properties' property must be specified"
                     },
                     "innererror": {
                       "stacktrace": "System.ArgumentNullException: Value cannot be null.\r\nParameter name: 'properties' property must be specified\r\n   at 
                 Microsoft.AppInsights.Nexus.ResourceProvider.ScheduledQueryRules.ScheduledQueryRulesProvider.<PatchResourceAsync>d__30`1.MoveNext() in 
                 X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Nexus\\ResourceProvider\\ScheduledQueryRules\\ScheduledQueryRulesProvider.cs:line 406\r\n--- End of stack trace from previous location 
                 where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at 
                 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at 
                 Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.CsmResourcesNxControllerBase`1.<>c__DisplayClass14_0.<<PatchResourceAsync>b__0>d.MoveNext() in 
                 X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\CsmResourcesNxControllerBase.cs:line 242\r\n--- End of stack trace from previous location where 
                 exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at 
                 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at 
                 Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.NexusControllerBase.<PerformActionAsync>d__17.MoveNext() in 
                 X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\NexusControllerBase.cs:line 97"
                     }
                   }
                 }
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.ErrorResponses.ErrorResponseMessageException
InvocationInfo : {Set-AzResource}
Line           :                       Set-AzResource -Tag $resourcetags -ResourceId $r.ResourceId -Force
                 
Position       : At C:\ikanni\ICM-UpdateTags.ps1:28 char:23
                 + ...             Set-AzResource -Tag $resourcetags -ResourceId $r.Resource ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

Message        : {
                   "error": {
                     "code": "Value cannot be null.",
                     "message": {
                       "lang": "en-US",
                       "value": "Value cannot be null.\r\nParameter name: 'properties' property must be specified"
                     },
                     "innererror": {
                       "stacktrace": "System.ArgumentNullException: Value cannot be null.\r\nParameter name: 'properties' property must be specified\r\n   at 
                 Microsoft.AppInsights.Nexus.ResourceProvider.ScheduledQueryRules.ScheduledQueryRulesProvider.<PatchResourceAsync>d__30`1.MoveNext() in 
                 X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Nexus\\ResourceProvider\\ScheduledQueryRules\\ScheduledQueryRulesProvider.cs:line 406\r\n--- End of stack trace from previous location 
                 where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at 
                 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at 
                 Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.CsmResourcesNxControllerBase`1.<>c__DisplayClass14_0.<<PatchResourceAsync>b__0>d.MoveNext() in 
                 X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\CsmResourcesNxControllerBase.cs:line 242\r\n--- End of stack trace from previous location where 
                 exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at 
                 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at 
                 Microsoft.ManagementServices.Rules.Endpoint.Controllers.Nexus.NexusControllerBase.<PerformActionAsync>d__17.MoveNext() in 
                 X:\\bt\\1009878\\repo\\src\\SQR-CDS\\Service\\Endpoint\\Controllers\\Nexus\\NexusControllerBase.cs:line 97"
                     }
                   }
                 }
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.ErrorResponses.ErrorResponseMessageException
InvocationInfo : {Set-AzResource}
Line           :                       Set-AzResource -Tag $resourcetags -ResourceId $r.ResourceId -Force
                 
Position       : At C:\ikanni\ICM-UpdateTags.ps1:28 char:23
                 + ...             Set-AzResource -Tag $resourcetags -ResourceId $r.Resource ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

**Comment by ikanni** [comment]
> @ikanni Can you run Resolve-AzError: it looks like you are runjnign Resolve-AzureRmError from AzureRM.Profile

@markcowl Updated below

**Comment by ikanni** [comment]
> @ikanni Can you run Resolve-AzError: it looks like you are runjnign Resolve-AzureRmError from AzureRM.Profile
> 
> @markcowl Updated below

@markcowl , Could u please update Az New Issue template? It has ""

**Comment by markcowl** [comment]
@ikanni yes, the template is now fixed.

**Comment by cormacpayne** [comment]
@ikanni I believe this issue can be resolved with a similar solution suggested in [this comment](https://github.com/Azure/azure-powershell/issues/9068#issuecomment-490994630). Let me know if this doesn't work for you.
