### ISSUE TITLE
Az Module is missing AAD commands (Including B2B and User Settings)

### ISSUE THREAD

**Issue by JHCessna** [Azure/azure-powershell#9074]
Az Module is missing equivalent of New-AzureADMSInvitation.

This command is still only found in the AzureAD module. If Az is supposed to be the one stop shop module for all things Azure, then B2B controls need to be added.

**Comment by markcowl** [comment]
Az is supposed to be the one stop shop for all things in managing azure resources.  Since AD is used for more than just Azure, we don't completely cover the AD cmdlet surface area.

Can you elaborate on some scenarios you are unable to implement based on the absence of these commands?

@dcaro as FYI

**Comment by JHCessna** [comment]
We're trying to add B2B guest users that could use anything from O365 to PowerBI or even custom applications created in our Azure Tenant.

If we wanted to do any kind of automation to add guest users into AAD with PowerShell, we have to revert to the AzureAD module and use the New-AzureADMSInvitation command.

If we use the New-AzUser, that is making a new User Object under our domain.

A current scenarios I have is I created a form to automate Guest User invites to our tenant. I have a previous solution that does use the AzureAD Module to add and update the whitelist for External collaboration settings (Get-AzureADPolicy and Set-AzureADPolicy). We then loop through the users in that form and use New-AzureADMSInvitation to send out the invites.

This script already uses multiple modules to complete its task, including AzureAD. I was hoping that with the new Az Module, I'd be able to simplify.

**Comment by dcaro** [comment]
@JHCessna thanks for the additional inputs on this, unfortunately, at this point, you still have to use the two modules.

**Comment by markcowl** [comment]
@JHCessna Thanks for the input, we are looking at an update to thsi library later in the year, and we will consider this as aprt fo that update

**Comment by pbahiasav** [comment]
@markcowl I assume as there has been no update this still the case with the current build

**Comment by jakobli** [comment]
any update would be appeciated, implementing a new automation flow, would be great to be able to use the new Az module

**Comment by k0rtina** [comment]
I am also planning to use the MSInvitation commands, any update on when they will make it into the Az module?

**Comment by dingmeng-xue** [comment]
This issue has to be closed because it is by design and Az module just focuses on its major functions. In short term, we have no plan to expand the scope. Sorry for inconvenience.

**Comment by sebsalvat** [comment]
Now that its almost 2021, can we please open this again? 
Guest / external invitations are a huge part of our B2B process.

**Comment by asad3077** [comment]
I am in the same situation. Don't want to use the old New-AzureADMSInvitation is there anything Microsoft can do to add this B2B invite process with in AZ modules?

**Comment by dcaro** [comment]
We plan to have support for this in few weeks.

**Comment by shivakumarky** [comment]
Hi team,

Do you have any update on supporting AzureAD module in standard AZ cmdlets. We  are still using both modules for our runbook configuration, so just curious on progress.

**Comment by balaambati** [comment]
Is there any alternative?

**Comment by dingmeng-xue** [comment]
Hi All,

Azure PowerShell already migrated AzAD cmdlets to MicrosoftGraph API. We still focus on object type of ad user, group, application and service principal. Since Az module mainly focuses on Azure and we have limited knowledge on Microsoft Graph API, could you share us the API of MS Graph which supports B2B invitation process?

Alternatively, you can use MSGraph module to trigger related feature. https://www.powershellgallery.com/packages/Microsoft.Graph/1.9.5

**Comment by dcaro** [comment]
In the Az module we support the Azure AD resources required for ARM based scenarios. We do not have plans today to include invitations unless there is either a high demand for it (we measure this via votes or comments on GitHub issues) or if there is a compelling scenario that would benefit from it.
I believe that the [New-MgInvitation](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/new-mginvitation?view=graph-powershell-beta) cmdlet from the Microsoft Graph SDK module provides this functionality.
