### ISSUE TITLE
Add AzureRM depreciation messages to documentation

### ISSUE THREAD

**Issue by IanHopkinson** [Azure/azure-powershell#9081]
As per this blog post AzureRM is now depreciated in favour of the Az module:

https://azure.microsoft.com/en-gb/blog/how-to-migrate-from-azurerm-to-az-in-azure-powershell/?cdn=disable

This post indicates that AzureRM code should be migrated to Az where possible. 

Please could you add a depreciation notice to the AzureRM documentation pages, and possibly add redirects to the new Az module equivalents?

**Comment by markcowl** [comment]
@dcaro As the cmdlets in Az diverge from AzureRM, this becomes more necessary, I think

**Comment by dcaro** [comment]
@IanHopkinson thanks for the suggestion, I'll work on this with our docs team.

**Comment by mikefrobbins** [comment]
A banner has been added to all AzureRM reference and conceptual docs. An example of this banner can be viewed in the any of the docs such as [Connect-AzureRmAccount](https://docs.microsoft.com/en-us/powershell/module/azurerm.profile/connect-azurermaccount).
