### ISSUE TITLE
needs updating

### ISSUE THREAD

**Issue by danieldude15** [Azure/azure-powershell#9087]
add to instructions the following command
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned

**Comment by markcowl** [comment]
Which document did you refer to where this wasn't present?

Do you think it's also appropriate for this to also be in the instructions for the PowerShell Gallery (since this is true of any module installed form there [or anywhere])?

**Comment by markcowl** [comment]
Closing for lack of response.  Please reopen with the requested information if this is till an issue
