### ISSUE TITLE
Model Tests for CRUD cmdlets for one resource type

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#9097]
## Description
Model scenario etsts using the built-in recordign mechanism.  Tests should
- [ ] Use templates to set up necessary resources
  - [ ] Generate necessary infrastructure for template deployment
- [x] Perform CRUD actions and validate using pester functions / operators
- [x] Save recording in Test folder with test code
- [ ] Work across two profiles

**Comment by dingmeng-xue** [comment]
close it due to priority.
