### ISSUE TITLE
Get-AzureRmResource - parameter for excluding hidden resources

### ISSUE THREAD

**Issue by ViggoL** [Azure/azure-powershell#9102]
## Description of the new feature

In the Azure portal the user can choose to include or exclude hidden resources in the list by ticking a box. Add this support to the `Get-AzureRmResource` cmdlet by argument.

**Comment by sphibbs** [comment]
We should see if we can follow the portal and not show Hidden by default and add a flag to include.

**Comment by cormacpayne** [comment]
By default, hidden _and_ non-hidden resources are being returned when executing `Get-AzResource`. It doesn't appear that the SDK allows for providing a flag to return just non-hidden resources, nor does it appear that the filter query allows any sort of "hidden" property to be passed to filter on the server. There's also no property on the returned object(s) that signals that the resource is hidden or not, so this is would be a question for the ARM service to answer.

@Tiano2017 Hey Tian, would you mind shedding some light on how ARM differentiates hidden and non-hidden services on the portal, and if this functionality can be used in PowerShell as well?

**Comment by rmsands** [comment]
Get-AzResource fails to get the Resource Types microsoft.insights/actiongroups and Microsoft.Network/networkWatchers that are shown in Azure when listing resources in a resource group.

**Comment by aquibqureshi26** [comment]
any update on how we can show only hidden resources using PowerShell?

**Comment by ifeoluwaokunoren** [comment]
Hello @ViggoL,
I'm from the ARM team, and i'm currently looking into this issue.
Can you please give me some details on what is the use-case for including whether a resource is hidden/non-hidden.  This would help me either recommend an alternative or create a feature request.

Thank you.

**Comment by ifeoluwaokunoren** [comment]
Closing this issue based on my previous response. Please open a new issue if you still want to make this feature request.
Thanks.

**Comment by DavidHomerOxford** [comment]
Our use case is that our software documents the configuration of an Azure tenant 
https://www.centrel-solutions.com/xiaconfiguration/capabilities.aspx?capability=microsoft-azure-documentation-tool

We were looking for an option to replicate the behaviour of the UI and give users the default of documenting only visible resources but toggling an option to document all resources.

It would be great if Microsoft maintained functional consistency between the UI and the REST API/Az PowerShell, at the moment Azure is cobbled together with broken, pre-release, inconsistent, deprecated or undocumented functionality. 

Worse we're finding now you're totally cutting off Azure Graph and replacing with Microsoft Graph in six months yet you haven't released Az PowerShell and AzureAD cmdlets that use Microsoft Graph, it's all a bit of a mess.

**Comment by Truzi** [comment]
Is there any progress/update on that?
I'm currently trying to retrieve some part of almost 300 resources, so it would be really helpful if some kind of flag would exclude _hidden_ resources
