### ISSUE TITLE
Set-AzResource should report progress based on operation result's percentComplete

### ISSUE THREAD

**Issue by xuesongyuan** [Azure/azure-powershell#9103]
## Description of the new feature
The creation and/or modification of our AAD Domain Services resource usually takes a long time. We are reporting a rough progress using RP SDK operationResult's percentComplete. However, it does not seem to be honored by AzureRM or Az PowerShell. Please implement a support for it.

**Comment by sphibbs** [comment]
Thanks for your feedback. If the service begins to provide reliable progress we will expose it to users. Right now, we could only guess and that is worse than not reporting anything
