### ISSUE TITLE
VirtualDiskStream Seek(..., SeekOrigin.End) method does not calculate end-relative position correctly

### ISSUE THREAD

**Issue by pmaughan-MSFT** [Azure/azure-powershell#9115]
## Code Reference

https://github.com/Azure/azure-powershell/blob/ec859f68bd7bcc9d4c2d76c369ca690c54d13544/src/Compute/Compute/VhdManagement/VirtualDiskStream.cs#L226-L228

## Description

The logic should be consistent with the generic Stream class’s implementation, shouldn’t it?
```C#
case SeekOrigin.End:
  this.Position = this.Length - 1 + offset;
  break;
```
See https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.seek?view=netframework-4.8#remarks

## Cost
Unknown — is there a lot of code depending on the non-standard Seek behavior as currently implemented?

**Comment by markcowl** [comment]
@pmaughan-MSFT Have you opened this issue aagainst the correct repo?  This is the repo for Azure PowerShell.  If you are asking a question about code in the repo, please provide a link to an example of incorrect usage in the repo.

**Comment by pmaughan-MSFT** [comment]
@markcowl thanks, apologies for dropping that from the initial issue description.

**Comment by markcowl** [comment]
@hyonholee Can you take a look?

**Comment by Drewm3** [comment]
I spoke with @hyonholee on this issue. It will be fixed in the September release.

**Comment by markcowl** [comment]
@Drewm3 was this fixed?  Please close, or assign to a new milestone appropriately.

**Comment by Drewm3** [comment]
@hyonholee, could you confirm this has been fixed in the current release?

**Comment by dingmeng-xue** [comment]
Close it due to inactive. Please submit a new one if there is any concern.
