### ISSUE TITLE
AzManagementGroupSubscription needs Get/Delete verbs

### ISSUE THREAD

**Issue by ChristopherGLewis** [Azure/azure-powershell#9159]
## Description of the new feature
Az.Resource currently implements a NEW verb for adding a sub to an MG.  The corresponding GET/DELETE verbs have not been implemented.

#### Get 
The azManagementGroup stuff allow for retrieving a tree of your MG and subs.  Finding where a Sub in the tree is currently has no native code.  You have to retrieve the entire tree and recursively search for where the sub is assigned.

#### Delete
Currently the only way to remove a Sub from an MG is to re-parent it to its new location or the "Tenant Root Group" MG.  Since once MG's are turned on, this new DELETE should move any sub's back up to the root.  New-AzManagementGroupSubscription should not move a sub unless a -Force parameter is specified

## Proposed implementation details (optional)
I'm currently using this code to search for a Sub in the MG tree:

````powershell
[CmdletBinding()]
Param
(
    [String] $TenantID,
    [string] $SubscriptionID
)


Function FindSubInMGChildren {
[CmdletBinding()]
Param
(
    [Object] $MG,
    [string] $SubID
)
    #MG is a MG Object with populated children
    Write-Verbose "  Evaluating $($MG.DisplayName) "


    #No children in this MG
    If ($MG.Children -eq $null) {
        Write-Verbose "    $($MG.DisplayName) has no children"
        Return $null
    }

    #loop through all children, look for type = '/subscriptions' and name = subID
    foreach($child in $MG.Children) {
        if ($Child.Type -eq '/subscriptions' -and $child.Name -eq $subID) {
            Write-Verbose "    Sub $subID found as child in $($MG.DisplayName)"

            #Found
            Return $MG
        }
        #Recurse
        if ($Child.Type -eq '/providers/Microsoft.Management/managementGroups') {
            $Results = FindSubInMGChildren -MG $child -subID $SubID
            if ($Results -NE $Null) {
                Return $Results
            }
        }
    }
    #Not found
    Return $null
}

#Root MG is the TenantID - note you have to use EXPAND
$MGTree = Get-AzManagementGroup -GroupName $tenantID  -Recurse -Expand

$FoundMG = FindSubInMGChildren -mg $MGTree -subID $SubscriptionID
if ($FoundMG) {
    Write-Host "found sub '$SubscriptionID' in MG: '$($FoundMG.DisplayName)'"
} else {
    Write-Host "Sub '$subID' Not found"
}



````

**Comment by markcowl** [comment]
@dcaro Please ensure the approproate folks in ManagementGroups respond to this issue

**Comment by rthorn17** [comment]
Hi @ChristopherGLewis ,
This is great feedback and I will look to review this with the team to see what we can do.  For until then I will close this item as it is with our team and will manage it on our feedback list.  Thanks ! 

https://feedback.azure.com/forums/911473-azure-management-groups/suggestions/37617688-azmanagementgroupsubscription-needs-get-delete-ver
