### ISSUE TITLE
Can't get more than 1,000 topics

### ISSUE THREAD

**Issue by AceHack** [Azure/azure-powershell#9169]
I'm trying to write a script to iterate through all 2,583 topics and I'm getting the following error.

```
Get-AzServiceBusTopic -ResourceGroupName rgp-usw-capabilities-test2 -Namespace sb-usw-capabilities-test2 -MaxCount 5000
Get-AzServiceBusTopic : 'top' exceeds maximum value of '1000'.
At line:1 char:1
+ Get-AzServiceBusTopic -ResourceGroupName rgp-usw-capabilities-test2 - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzServiceBusTopic], ValidationException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceBus.Commands.Topic.GetAzureRmServiceBusTopic
```

**Comment by markcowl** [comment]
@AceHack Can you provide the following info to help us pipnpoint the issue:

- Module layout on your machine
  - ```Get-Module -ListAvailable```

- Results of running```Resolve-AzError -Last``` right after this error occurs

- Debug stream output when running this cmdlet
  - Set `$DebugPreference="Continue"` and then execute the cmdlet

**Comment by markcowl** [comment]
Closing for lack of response.  If you are still seeing this issue, please file a new issue and supply the information requested in the issue template for Az/AzureRM
