### ISSUE TITLE
Can't install Az on PowerShell 5.1 on Windows Server 2012 R2 (Cannot convert value)

### ISSUE THREAD

**Issue by kevincote** [Azure/azure-powershell#9170]
I tried installing Az module on Powershell 5.1 to use with Azure FileSync. I've succeeded installing Az, Az.StorageSync and AzureRM on Powershell 6.0, but it seems that the Server Registration of Azure FileSync doesn't recognize the modules inside Powershell 6.

So, I tried installing Az module on Powershell 5.1 but it fails with the following error:

> PackageManagement\Install-Package : Cannot convert value "2.0.0-preview" to type "System.Version". Error: "Input string was not in a correct format."
> At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
>  ...          $null = PackageManagement\Install-Package @PSBoundParameters
>                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPackage:InstallPackage) [Install Package], Exception
>    FullyQualifiedErrorId : InvalidCastParseTargetInvocation,New-PSGetItemInfo,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

I also tried installing Az module v 1.8.0 instead of the latest but it gives me the same error.

**Comment by cormacpayne** [comment]
@kevincote you will need to update the version of `PowerShellGet` on your machine to _at least_ 1.6.0 (it appears to currently be at 1.0.0.1) -- you can get the latest version by running `Install-Module -Name PowerShellGet -Repository PSGallery -Force`.

Beginning with version 1.6.0 of `PowerShellGet`, the notion of "prerelease modules" was introduced, allowing for a version to have a prerelease suffix that denoted it as "unstable". We recently pushed a new version of the `Az.Accounts` that has a `-preview` suffix, so it looks like the older version of `PowerShellGet` isn't recognizing it, and you'll need to update to at least version 1.6.0.
