### ISSUE TITLE
Set-AzureRmApiManagementPolicy Bad Error Message

### ISSUE THREAD

**Issue by backwardsDave1** [Azure/azure-powershell#9171]
If you run Set-AzureRmApiManagementPolicy and your Policy string contains:

```
$policyString = '<policies>
    <inbound>
        <base />
        <rewrite-uri template="/stores/{Location}/slots?StartDate={StartDateTime}&amp;AppointmentType={AppointmentType}" />
        <set-header name="ocp-apim-subscription-key" exists-action="override">
            <value>12d0bdd57ca84fa9ad35f13f22605dbf</value>
        </set-header>
    </inbound>
    <backend>
        <base />
    </backend>
    <outbound>
        <base />
    </outbound>
    <on-error>
        <base />
    </on-error>
</policies>'
```

If a parameter (in my example, Location) is not part of the template params in APIM, it will output the following:
> Operation returned an invalid status code 'BadRequest'

Please have the error be the same as what the Azure Portal shows you:

> One or more fields contain incorrect values: Error in element 'rewrite-uri' on line 4, column 10: Only parameters specified in the original URL template can be used in the rewrite template

**Comment by markcowl** [comment]
@backwardsDave1 Can you please provide some additional information to help us pinpoint the issue:

- Module layout on your machine
  - `Get-Module -ListAvailable`

- Output of `Resolve-AzureRmError` after this error occurs

- Debug stream output when executing the failign cmdlet
  - Set `$DebugPreference="Continue"` and then execute the failing cmdlet

**Comment by solankisamir** [comment]
Issue similar to https://github.com/Azure/azure-powershell/issues/5386

**Comment by markcowl** [comment]
Closing for lack of response.  If you are still seeing this issue, please open a new issue and provide the information requested in the issue template for Az/AzureRM
