### ISSUE TITLE
Automation: Create test for Start-AzAutomationDscCompilationJob fix

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#9172]
This change was signed off without tests.
https://github.com/Azure/azure-powershell/pull/9030

This issue here encompasses the work to properly add tests.

**Comment by lwajswaj** [comment]
Did you cherry-pick my PR? Wondering because in the PR I don't see some of my commits (like the one that actually adds the test cases): https://github.com/lwajswaj/azure-powershell/commit/15851a1f39fa77a398a6c2d74600011053ac9610

**Comment by MiYanni** [comment]
@lwajswaj The commit you linked to was from this PR: https://github.com/Azure/azure-powershell/pull/9031
Since that was merged, how do those changes relate to: https://github.com/Azure/azure-powershell/pull/9030

**Comment by andyw248** [comment]
Change not made by automation team.
