### ISSUE TITLE
Get-AzOperationalInsightsWorkspaceSharedKey not working

### ISSUE THREAD

**Issue by shihanpietersz** [Azure/azure-powershell#9179]
Hi Team,
Get-AzOperationalInsightsWorkspaceSharedKey says its not found in the new version and its been removed. what is the replacement cmdlet for this. its not documented anywhere and the Get-AzOperationalInsightsWorkspaceSharedKey command is still referenced in Microsoft documentation

**Comment by shihanpietersz** [comment]
incorrect location

**Comment by MiYanni** [comment]
@shihanpietersz Could you list the modules you have installed by running `Get-Module -ListAvailable`? We can see this cmdlet in the Az.OperationalInsights module and the documentation for this cmdlet is here: https://docs.microsoft.com/en-us/powershell/module/az.operationalinsights/get-azoperationalinsightsworkspacesharedkey

**Comment by markcowl** [comment]
Closing for lack of response.  If you are still seeing this issue, please fiel a new issue and provide the information requested in the issue template
