### ISSUE TITLE
New-AzureRMSubscription missing argument to set management group scope

### ISSUE THREAD

**Issue by alexevansigg** [Azure/azure-powershell#9189]
If I create a new Subscription using New-AzureRMSubscription it is always created at Root Scope, seems there is missing an arguement for management group scope.

Otherwise i need to additionally execute New-AzManagementGroupSubscription... and this command, as far as i can tell will require the user executing it too be both Contributor of the management group object and owner of the subscription object.

The 'New Subscription' owner and 'Target Management Group' owner are different identities in my scenario.

**Comment by MiYanni** [comment]
@rthorn17 @daxfohl Can you take a look at this issue?

**Comment by rthorn17** [comment]
This is something we are working on with the subscriptions/ARM team to get enabled.  I don't have a timeline yet, but it is in our backlog.  

I will track this on our UserVoice Page 
https://feedback.azure.com/forums/911473-azure-management-groups/suggestions/37881133-new-azurermsubscription-missing-argument-to-set-ma
