### ISSUE TITLE
Get-AzDeletedWebApp failing in recorded tests

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#9191]
## Description
Get-AzDeletedWebApp is returning null intermittently in runs against the master branch for the following tests:

- Test-GetDeletedWebApp
- Test-RestoreDeletedWebAppToNew
- Test-RestoreDeletedWebAppToExisting
 
Need to determine root cause for intermittent test failures and fix.  Meanwhile, tests are skipped

**Comment by panchagnula** [comment]
@Nking92 can you look at this when we update to use the latest .NET SDK?

**Comment by Nking92** [comment]
Will do

**Comment by markcowl** [comment]
[Sample trx file showing this issue](https://github.com/Azure/azure-powershell/files/3175054/trxsample.zip)

**Comment by Nking92** [comment]
These will be fixed with this PR: https://github.com/Azure/azure-powershell/pull/9177

**Comment by panchagnula** [comment]
This change is merged
