### ISSUE TITLE
Set-AzSqlServerAuditing - AuditActionGroup config requirement

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#9193]
## Description
This issue was discovered and made aware to @bashahee in this PR: https://github.com/Azure/azure-powershell/pull/9061
Instead of updating the documentation to describe the restriction, this work is to fix the issue.

**Comment by bashahee** [comment]
@MiYanni I am currently working on fixing the issue.

**Comment by aamalvea** [comment]
The fix for this bug has been merged. PR here: https://github.com/Azure/azure-powershell/pull/9247
