### ISSUE TITLE
Add-AzureAccount fails when subscriptions in an account doesn't have a tenant Id

### ISSUE THREAD

**Issue by vivsriaus** [Azure/azure-powershell#920]
Per Mark:
The root cause is that only one of the subscriptions in the list subscriptions call (to RDFE) returns a tenant ID.  The next step is to authenticate against each provided tenant, and we attempt to acquire a token against tenant ‘’ (the tenant id for the second subscription).

Essentially, this field should not be blank – otherwise we have no way of acquiring tokens for the listed subscriptions.  

We should also be more resilient over this possibility – we should warn the user that they will not have access to any subscriptions which do not list a tenant.

**Comment by hovsepm** [comment]
@vivsriaus, Could you provide a repro steps?

**Comment by ravbhatnagar** [comment]
@vivsriaus  - Is this still an issue?

**Comment by ravbhatnagar** [comment]
@vivsriaus - Please confirm if its still an issue

**Comment by vivsriaus** [comment]
Not an issue anymore
