### ISSUE TITLE
DetermineApiVersion should respect resource default version

### ISSUE THREAD

**Issue by lygasch** [Azure/azure-powershell#9227]
## Description of the new feature
ApiVersionHelper DetermineApiVersion returns the latest, non-preview version but I propose that it should return the default version specified by resource in its ARM manifest. This would provide a more consistent experience for customers between powershell and ARM/portal. I don't know the behavior of ARM with direct REST call with unspecified api version, but these all should match. 
For testing purposes, maybe it could use a switch to return latest, similar to the pre switch.

**Comment by MiYanni** [comment]
@lygasch The manifest information when resources are deployed is not exposed via REST API. So, we can't get this information to implement this feature.
