### ISSUE TITLE
Workspace ID not found for OMS Resource

### ISSUE THREAD

**Issue by coderUT** [Azure/azure-powershell#9238]
## Description

Calling New-AzScheduledQueryRule with a source configured as such fails with 'Workspace ID for OMS Resource Not Found'

Looking at the documentation for the REST API call, it suggests it expects a normal resource ID of the form "/subscriptions/{sub id}/resourceGroups/{rg name}/providers/Microsoft.OperationalInsights/workspaces/{log analytics workspace name}

And Yes, the Location of my OMS Workspace is 'East US' and I'm trying to create the Log search Alert in 'East US'

As a side comment, the Powershell cmdlets for creating Alerts in Azure Monitor is quite poor compared to other flows (e.g. Az.Network). On top of the documentation is terrible, most of the examples are non-functional, with nonsense "placeholders" for required arguments.

I've spend over 7 hours figuring out how to create an Activity Log Alert, Metrics V2 Alert and Log Search Alert via PS.....absurd.

Its sad that one has to this garbage API to pass the AZ-103 exam.

## Steps to reproduce

```powershell
$query = New-AzScheduledQueryRuleSource -Query "AzureActivity | where ActivityStatus=='Failed'" -DataSourceId (Get-AzResource -ResourceGroupName <rg name> -Name <log analytics workspace name>).Id
$schedule = New-AzScheduledQueryRuleSchedule -TimeWindowInMinutes 720 -FrequencyInMinutes 5
$trigger = New-AzScheduledQueryRuleTriggerCondition -ThresholdOperator GreaterThan -Threshold 5
$actionGrp = New-AzScheduledQueryRuleAznsActionGroup -ActionGroup @()
$action = New-AzScheduledQueryRuleAlertingAction -Severity 2 -Trigger $trigger -AznsAction $actionGrp
New-AzScheduledQueryRule -Name "<name>" -ResourceGroupName "<rg name>" -Source $query -Schedule $schedule -Action $action -Location 'East US' -Enabled $true
```

## Environment data

```

```

## Module versions

```powershell
Az.Monitor 1.2.0
```

## Debug output

```

```

## Error output

```

```

**Comment by MiYanni** [comment]
@xizhamsft Any chance you could look into updating documentation and have good examples on how to use these cmdlets?

**Comment by sruss95** [comment]
I was encountering this issue as well. Was able to fix the issue by changing the location to lowercase and removing spaces. So this should work with location 'eastus'. I'm not sure why this would be required with scheduled query rules since 'East US' is valid for pretty much everything else, including creating the workspace.

**Comment by lightdrive** [comment]
Same issue for me - On the docs in the example it shows -Location "West Europe" but I had to change it to the short name 'eastus' (my workspace was East US), all lower case input for it to accept it as an argument. Otherwise it threw an exception.

**Comment by yanivlavi** [comment]
We are planning to align with metric alerts semantics on all the interfaces.
That includes PS. I'm not sure we will invest in the old cmdlets because of that.
I'll make sure this requirement is included there.
