### ISSUE TITLE
New-AzureRmVM and New-AzureRmVMSS should not hard code the storage type to 'Premium_LRS'

### ISSUE THREAD

**Issue by huangpf** [Azure/azure-powershell#9251]
Instead, the simple parameter set should expose a parameter to handle that. The reason is, for new regions and/or clouds, the 'Premium_LRS' may not available at the beginning, and might not be available for a long period of time. 

Moreover, if going forward, the default type is changed to something other than 'Premium_LRS' in all environments, then the users will encounter the same type of issues.

From this line of code, you can see its hard coding:
https://github.com/Azure/azure-powershell/blob/master/src/Compute/Compute/VirtualMachine/Operation/NewAzureVMCommand.cs#L420

```
                var st1 = storageClient.StorageAccounts.Create(
                    ResourceGroupName,
                    Name,
                    new StorageAccountCreateParameters
                {
                    Sku = new Microsoft.Azure.Management.Storage.Version2017_10_01.Models.Sku
                    {
                        Name = SkuName.PremiumLRS
                    },
                    Location = Location
                });
```

**Comment by Drewm3** [comment]
All of the regions have premium storage at this time. So I am going to close this one.
