### ISSUE TITLE
Stack: Support comma seperated Port Range in Add-AzureRmNetworkSecurityRuleConfig 

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#9253]
## Description
Add-AzureRmNetworkSecurityRuleConfig -Name "Source_Port_Range_Comma_PS" -NetworkSecurityGroup $NSG -Access "Allow" -Protocol Tcp -Direction Inbound -Priority 330 -SourceAddressPrefix Internet -SourcePortRange "4,5,6" -DestinationAddressPrefix * -DestinationPortRange 8080 | Set-AzureRmNetworkSecurityGroup

Set-AzureRmNetworkSecurityGroup : Security rule has invalid Port range. Value provided: 4,5,6. Value should be an integer OR integer range with '-' delimiter. Valid range 0-65535.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : '52881ced-17b0-4667-9f98-1a32df35d3ba'
At line:1 char:275
+ ... Prefix * -DestinationPortRange 8080 | Set-AzureRmNetworkSecurityGroup
    + CategoryInfo          : CloseError: (:) [Set-AzureRmNetworkSecurityGroup], NetworkCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.SetAzureNetworkSecurityGroupCommand

**Comment by dingmeng-xue** [comment]
@bganapa, shall it be fixed within Network?

**Comment by bganapa** [comment]
This will be fixed when azure stack moves to the higher API version for network

**Comment by bganapa** [comment]
This will be be fixed with the new Az module for the profile 2020-09-01-hybrid
