### ISSUE TITLE
Get-AzRecoveryServicesBackupJob result is empty

### ISSUE THREAD

**Issue by Wand3rvogel** [Azure/azure-powershell#9263]
## Description

Result is empty for Get-AzRecoveryServicesBackupJob -VaultId $vault.ID -Operation Backup

## Steps to reproduce

```powershell
Import-Module Az.RecoveryServices
Connect-AzAccount -Credential ...
$vault = Get-AzRecoveryServicesVault -Name ...
Get-AzRecoveryServicesBackupJob -VaultId $vault.ID -Operation Backup -Debug
```

## Environment data

```powershell
PSVersion 5.1.14393.2969
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.14393.2969
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
```

## Module versions

```powershell
1.5.2 Az.Accounts
1.4.0 Az.RecoveryServices
```

## Debug output

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/Subscriptions/xxx/resourceGroups/xxx/providers/Micro
soft.RecoveryServices/vaults/xxx/backupJobs?$filter=operation eq 'Backup' and startTime eq '2019-05-20 01:38:04
PM' and endTime eq '2019-05-21 01:38:04 PM'&api-version=2017-07-01

Headers:
x-ms-client-request-id        : 75bb5f6f-a820-4ec0-9aaf-b8e84bd6344f
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Cache-Control                 : no-cache
Server                        : Microsoft-IIS/10.0,Microsoft-IIS/10.0
X-Content-Type-Options        : nosniff
x-ms-request-id               : 5b36f68d-fd9b-458b-b3cc-c09752dc099b
x-ms-client-request-id        : 9cd9ad7f-2e8f-4f24-bf26-9858fe4304ea,9cd9ad7f-2e8f-4f24-bf26-9858fe4304ea
X-Powered-By                  : ASP.NET
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11993
x-ms-correlation-request-id   : 5b36f68d-fd9b-458b-b3cc-c09752dc099b
x-ms-routing-request-id       : FRANCESOUTH:20190521T133804Z:5b36f68d-fd9b-458b-b3cc-c09752dc099b
Date                          : Tue, 21 May 2019 13:38:03 GMT

Body:
{
  "value": [
    {
      "id":
"/Subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.RecoveryServices/vault
s/xxx/backupJobs/07f6136e-dd81-4294-a2d2-01d2f856f5b2",
      "name": "07f6136e-dd81-4294-a2d2-01d2f856f5b2",
      "type": "Microsoft.RecoveryServices/vaults/backupJobs",
      "properties": {
        "jobType": "MabJob",
        "duration": "PT1M38.78S",
        "mabServerName": "xxx.xxx.xxx",
        "mabServerType": "MABContainer",
        "workloadType": "FileFolder",
        "errorDetails": [
          {
            "errorString": "Der Vorgang wurde erfolgreich beendet (0x0) ",
            "recommendations": []
          }
        ],
        "entityFriendlyName": "xxx.xxx.xxx",
        "backupManagementType": "MAB",
        "operation": "Backup",
        "status": "Completed",
        "startTime": "2019-05-21T03:00:13.361Z",
        "endTime": "2019-05-21T03:01:52.141Z",
        "activityId": "9ed57e66-8b99-4c02-a966-a5e2735971c0"
      }
    },
    {
      "id":
"/Subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.RecoveryServices/vault
s/xxx/backupJobs/bfbb2534-6c33-48a2-94f6-9218723732ae",
      "name": "bfbb2534-6c33-48a2-94f6-9218723732ae",
      "type": "Microsoft.RecoveryServices/vaults/backupJobs",
      "properties": {
        "jobType": "MabJob",
        "duration": "PT1M28.214S",
        "mabServerName": "xxx.xxx.xxx",
        "mabServerType": "MABContainer",
        "workloadType": "FileFolder",
        "errorDetails": [
          {
            "errorString": "Der Vorgang wurde erfolgreich beendet (0x0) ",
            "recommendations": []
          }
        ],
        "entityFriendlyName": "xxx.xxx.xxx",
        "backupManagementType": "MAB",
        "operation": "Backup",
        "status": "Completed",
        "startTime": "2019-05-20T17:00:04.244Z",
        "endTime": "2019-05-20T17:01:32.458Z",
        "activityId": "47951a96-dd0f-4021-89f3-0fd0030d5bd0"
      }
    }
  ]
}

DEBUG: Ignoring some of the unexpected job while conversion
DEBUG: Ignoring some of the unexpected job while conversion
DEBUG: Number of jobs fetched: 0
DEBUG: AzureQoSEvent: CommandName - Get-AzRecoveryServicesBackupJob; IsSuccess - True; Duration - 00:00:02.3846521;
Exception - ;
DEBUG: Finish sending metric.
DEBUG: 15:38:05 - GetAzureRmRecoveryServicesBackupJob end processing.
DEBUG: 15:38:05 - GetAzureRmRecoveryServicesBackupJob end processing.
```

## Error output

```

```

**Comment by MiYanni** [comment]
@siddharth7 Can you take a look at this?

**Comment by siddharth7** [comment]
@Wand3rvogel Get Jobs cmdlet doesn't support MAB workloads. Even though the APIs support it, but the PowerShell module only supports AzureVM, AzureFiles, and AzureWorkload today.

**Comment by Wand3rvogel** [comment]
@siddharth7 
1) But we have jobs with Debug-mode (o_0). Simply not ignoring...
2) Invoke-RestMethod as an alternative? How can I use this?

**Comment by siddharth7** [comment]
@Wand3rvogel That's what I mentioned earlier. The API will get you MAB jobs but our PowerShell module currently doesn't support it. Alternatively, you can use the ARMClient to do API calls (reference : https://blogs.msdn.microsoft.com/girishp/2015/06/18/using-arm-client-to-explore-azure-resources/)

**Comment by pvrk** [comment]
@Wand3rvogel: Can you please elaborate more on the requirement? Azure PS module was built for handling Azure resources (Azure VM backup, Azure File Share, Azure workloads such as SQL). The on-premises components such as MAB agent, MAB server get shipped with their PS module and hence we assume users will use those for handling MAB agents. The Job data from MAB Agent does get synced but only after completion (which is the data you see in REST response) which means you can't track it. So, can you please let us know what is the ultimate use of these jobs being retrieved using Azure PS module? Just for information from one single place?

**Comment by pvrk** [comment]
#customer-response-expected

**Comment by Wand3rvogel** [comment]
@pvrk We are using Azure Backup and Vaults for data transfer from one server to another. And now we want to automate restore on one side. The restore job must be started at night, test that backup is completed, register second server with a Vault, install MAB Agent and restore files when this is true ("status": "Completed").

**Comment by pvrk** [comment]
@Wand3rvogel: Thanks for elaborating. But currently, this can be done only by using the OB-Powershell module within the machine. Azure PS isn't built for this. Even Azure Portal is not currently built for this. You can't fire backup and restore operations for MAB agents from Azure Portal. This requires complete integration of on-premises into Azure portal for Azure Backup and that is not in the current semester horizon (Jul-Dec, 2019). So, we cannot take this feature request as of now :-(

#please-close.

**Comment by pvrk** [comment]
Can you please put this request in the [uservoice](https://feedback.azure.com/forums/258995-azure-backup?category_id=341221) so that it gets captured?

**Comment by pvrk** [comment]
Closing this issue since this feature request cannot be taken up this semester. Provided a [feedback mechanism](https://feedback.azure.com/forums/258995-azure-backup?category_id=341221) so that it gets captured for the user to ask and rank this feature.
