### ISSUE TITLE
Remove the alias New-DataDiskObject for the cmdlet New-AzsDataDiskObject

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#9265]
## Description

New-Alias : The alias is not allowed, because an alias with the name 'New-DataDiskObject' already exists.

We should not need this alias as we need the Azs prefix for all the cmdlets.

**Comment by bganapa** [comment]
For the error 'The alias already exists', we  still need to figure out what module already had the New-DataDiskObject cmdlet.

**Comment by bganapa** [comment]
@deathly809 , I could not repro this  and i could not think any reason why this may have occurred for you.. Can you pls check?

**Comment by bganapa** [comment]
closing this, as we cant repro

**Comment by deathly809** [comment]
I get when I invoke MaxVMs from the DVM.
