### ISSUE TITLE
lgoc app deployment using az cli command az group deployment create --name logicappscript --resource-group aris-awa-paas --template-file template.json

### ISSUE THREAD

**Issue by adhilaea** [Azure/azure-powershell#9280]
## Proposed implementation details (optional)
az group deployment create --name appname  --resource-group resourcegroupname  --template-file template.json --parameters "@${parametersFilePath}"

Azure Error: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Could not find member 'definition' on object of type 'Template'. Path 'properties.template.definition', line 1, position 83.'.

**Comment by cormacpayne** [comment]
@adhilaea the command you are using above is from Azure CLI rather than Azure PowerShell. Please open an issue in [this repository](https://github.com/Azure/azure-cli).
