### ISSUE TITLE
Get-AzLog document term

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-powershell#9281]
For Get-AzLog, it makes a bunch of references to an "event log". Shouldn't that be the "activity log"? To the best of my knowledge, this command doesn't get diagnostic logs or anything other than the activity log. I think it's just an outdated term.
https://docs.microsoft.com/en-us/powershell/module/az.monitor/get-azlog?view=azps-2.0.0

**Comment by cormacpayne** [comment]
@niander Hey Niander, would you mind quickly checking this document to see if it should be updated?

**Comment by niander** [comment]
@gucalder Hi. Could you take a look at this? I believe that the customer is correct and this should be updated. I am just not totally sure. Thanks.

**Comment by asheniam** [comment]
Thanks for reporting this issue. We will follow up on this doc issue

**Comment by asheniam** [comment]
@niander - I discussed Arun/Damien that this would be assigned to PowerShell team to follow up.  Will remove Service Attention label

**Comment by dcbrown16** [comment]
Thanks Andy!

**Comment by VeryEarly** [comment]
fixed.
