### ISSUE TITLE
Include Az.ResourceGraph with Az download

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [Azure/azure-powershell#9283]
## Description of the new feature
Downloading 'Az' through powershell does not include Az.ResourceGraph and therefore it must be separately installed.
## Proposed implementation details (optional)
Include Az.ResourceGraph so when you install 'Az' via PowerShell, 'install-module -name Az' it'll include ResourceGraph.

**Comment by cormacpayne** [comment]
@CHDAFNI-MSFT Hey Chase, the `Az.ResourceGraph` module is currently in preview (`0.x.x`), so we won't be able to include it into the `Az` module as it's not a stable module. To go from preview to stable, the service team will need to (1) make sure that their cmdlets and module are compliant with PowerShell guidelines, and (2) opt into our [breaking change policy](https://github.com/Azure/azure-powershell/blob/5c3a09263c163760ec897f920754eb7c963b1272/documentation/breaking-changes/breaking-changes-definition.md). Once completed, we can release a 1.0.0 version of the module and consider it to be shipped with the roll-up `Az` module.

I'll assign this issue to @demyanenko to start discussions with his team about moving this module to stable.

**Comment by CHDAFNI-MSFT** [comment]
Understood. You may close this when ready

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
