### ISSUE TITLE
Confusing alias Get-AzStorageContainerAcl for Get-AzStorageContainer cmdlet

### ISSUE THREAD

**Issue by ToMakeSense** [Azure/azure-powershell#9293]
## Description
I found the `Get-AzStorageContainer` cmdlet has an alias named `Get-AzStorageContainerAcl`, This seems confusing

## Steps to reproduce

```powershell
alias Get-AzStorageContainerAcl | select Name, Definition

Name                      Definition            
----                      ----------            
Get-AzStorageContainerAcl Get-AzStorageContainer
```

## Module versions
```powershell
ModuleType Version    Name        
---------- -------    ----        
Script     1.3.0      Az.Storage  
```

**Comment by blueww** [comment]
@ToMakeSense 
This is because with Get-AzStorageContainer (and account/key credential), we can also get the container ACL (following PublicAccess column).
So the alias is added by design.

```powershell
PS C:\> Get-AzureStorageContainer -Context $ctx


   Blob End Point: https://***.blob.core.windows.net/

Name                 PublicAccess         LastModified                                                                                                                                  
----                 ------------         ------------                                                                                                                                                                                                                                             
lpb8tb               Blob                 5/24/2019 11:33:39 AM +00:00                                                                                                                  
tempcontainer        Off                  2/28/2019 10:15:26 AM +00:00                                                                                                                  
test                 Off                  4/17/2019 7:25:21 AM +00:00      
```

**Comment by ToMakeSense** [comment]
@blueww thanks for your clarification, now I know why there is only `Set-AzStorageContainerAcl` cmdlet, no `Get-AzStorageContainerAcl` cmdlet.

**Comment by johncrim** [comment]
This is still quite confusing - there is no "Access Control List". When I see a name like `Get-AzureStorageContainerAcl`, I expect it to return an access control list, along the lines of RBAC. IMO this alias should be removed.

**Comment by blueww** [comment]
@johncrim 
The `Get-AzStorageContainerAcl`, use the rest API https://docs.microsoft.com/en-us/rest/api/storageservices/get-container-acl.
> The Get Container ACL operation gets the permissions for the specified container. The permissions indicate whether container data may be accessed publicly.

So we also use acl help to be aligned.

Besides that, remove cmdlet alias is a breaking change, it will break the existing script from customer. Normally we won't do it until strong business justification.
