### ISSUE TITLE
Add cmdlet to provide feedback

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#9298]
## Description of the new feature
This new cmdlet will open a new issue for this repository and pre-populate the necessary information. 

## Proposed implementation details (optional)
When an exception happened, a message should be displayed to inform that there a feedback cmdlet to open an issue. 

The cmdllet will open the browser to the create new issue page and pre-populate the following information: 
- Description of the issue
- last command executed
- Environment data (collecting the  $PSVersionTable) 
- The installed modules and their version
- The debug output (if they can be collected automatically)
- The error that was generated ($Error)
- The output of executing `Resolve-AzError -Last` (you can capture the objects and pipe them through Format-List)

The user can then review that there are no sensitive information in the text and submit the issue.

An implementation example here: https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-feedback/azure/cli/command_modules/feedback/custom.py

**Comment by erich-wang** [comment]
Close the issue as it has been implemented by Lei
