### ISSUE TITLE
Test-AzureTrafficManagerDomainName: Please deprecate in favor of Test-AzureName

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#93]
The Azure PowerShell module (I'm running 0.8.13) has a `Test-AzureName` command that tests the availability and validity of globally-unique DNS names for:

* Azure Cloud Services
* Azure Storage Accounts
* Azure ServiceBus Namespaces
* Azure Websites

However, the Azure Traffic Manager feature has a separate command dedicated to testing the availability of globally-unique Traffic Manager DNS names, called ``Test-AzureTrafficManagerDomainName`. Having a separate command, just for Traffic Manager, is inconsistent from an end user experience, and the functionality it offers should be merged into the `Test-AzureName` command.

Feel free to e-mail me with any questions or input on this topic.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by pcgeek86** [comment]
@jtuliani Thank you for your response, and confirmation that you have taken note of this for the Azure Resource Manager module. Looking forward to seeing its implementation in ARM soon. :)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by matt-gibbs** [comment]
Closing this issue. It should be covered in the upcoming ARM commands.
