### ISSUE TITLE
request: Import-AzureManagementApi to support api version parameter

### ISSUE THREAD

**Issue by lxzhu** [Azure/azure-powershell#9307]
## Description of the new feature
command New-AzureApiManagementApi has parameters ApiVersion and ApiVersionSetId, while Import-AzureApiManagementApi does not have.
Hope Import-AzureApiManagementApi to support the same options

## Proposed implementation details (optional)
from the source code, Both commands go to the same method, so just add the options in command and assing them  to property of ApiCreateOrUpdateParameter should work.

**Comment by niander** [comment]
@solankisamir Hi. Could you take a look at this feature request?

**Comment by solankisamir** [comment]
Ack

**Comment by solankisamir** [comment]
released - [v2.4.0-July2019](https://github.com/Azure/azure-powershell/releases/tag/v2.4.0-July2019)

**Comment by lxzhu** [comment]
Great Thanks! @solankisamir @niander
