### ISSUE TITLE
Track work for generated Resources cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#9309]
### Resource

- [x] `Get-AzResource`
- [x] `Move-AzResource`
- [x] `New-AzResource`
- [x] `Remove-AzResource`
- [ ] `Set-AzResource`
- [x] `Test-AzResourceMove`
- [x] `Update-AzResource`

### Resource Groups

- [ ] `Export-AzResourceGroup`
    - Need to add `-Path` parameter
    - JSON output isn't being produced
- [x] `Get-AzResourceGroup`
- [x] `New-AzResourceGroup`
- [x] `Remove-AzResourceGroup`
- [x] `Set-AzResourceGroup`
- [x] `Test-AzResourceGroup`
- [x] `Update-AzResourceGroup`

### Deployments

- [ ] `Export-AzDeploymentTemplate`
- [x] `Get-AzDeployment`
- [x] `Get-AzDeploymentOperation`
- [ ] `New-AzDeployment`
    - Variants for `-TemplateParameterObject`, `-TemplateParameterFile`, `-TemplateParameterUri`
    - Variants for `-TemplateObject`, `-TemplateFile`, `-TemplateUri`
- [x] `Remove-AzDeployment`
- [ ] `Set-AzDeployment`
- [x] `Stop-AzDeployment`
- [ ] `Test-AzDeployment`
    - Variants for `-TemplateParameterObject`, `-TemplateParameterFile`, `-TemplateParameterUri`
    - Variants for `-TemplateObject`, `-TemplateFile`, `-TemplateUri`
- [ ] `Test-AzDeploymentExistence`

### Managed Application

- [ ] `Get-AzManagedApplication`
- [ ] `Get-AzManagedApplicationDefinition`
- [ ] `New-AzManagedApplication`
    - Use `-ManagedResourceGroupId` instead of existing `-ManagedResourceGroupName`
    - Use `-DefinitionId` instead of existing `-ManagedApplicationDefinitionId`
- [ ] `New-AzManagedApplicationDefinition`
- [ ] `Remove-AzManagedApplication`
    - Use `-GroupId` instead of existing `-GroupName`
- [ ] `Remove-AzManagedApplicationDefinition`
    - Use `-GroupId` instead of existing `-GroupName`
- [ ] `Set-AzManagedApplication`
    - Use `-ManagedResourceGroupName` instead of existing `-ManagedResourceGroupId`
    - Use `-Id` instead of existing `-ManagedApplicationDefinitionId`
- [ ] `Set-AzManagedApplicationDefinition`
- [ ] `Update-AzManagedApplication`

### Policy

- [x] `Get-AzPolicyAssignment`
- [x] `Get-AzPolicyDefinition`
- [x] `Get-AzPolicySetDefinition`
- [ ] `New-AzPolicyAssignment`
    - Use `-IdentityType` instead of existing `-AssignIdentity`
    - Use `-Parameter` instead of existing `-PolicyParameter`
    - Use `-PolicyDefinitionId` instead of existing `-PolicyDefinition` and `-PolicySetDefinition`
- [ ] `New-AzPolicyDefinition`
    - Use `-PolicyRule` instead of existing `-Policy`
- [x] `New-AzPolicySetDefinition`
- [x] `Remove-AzPolicyAssignment`
- [x] `Remove-AzPolicyDefinition`
- [x] `Remove-AzPolicySetDefinition`
- [x] `Set-AzPolicyDefinition`
- [x] `Set-AzPolicySetDefinition`

### Provider

- [x] `Get-AzResourceProvider`
- [x] `Get-AzProviderFeature`
- [x] `Get-AzProviderOperationMetadata`
- [x] `Get-AzResourceProviderOperationDetail`
- [x] `Register-AzResourceProvider`
- [x] `Register-AzProviderFeature`
- [x] `Unregister-AzResourceProvider`

### Tag

- [x] `Get-AzTag`
- [x] `New-AzTag`
- [x] `Remove-AzTag`

### Other

- [ ] `Get-AzAuthorizationOperation`
- [x] `Get-AzLocation`
- [x] `Get-AzTenant`

### Application

- [x] `Add-AzADApplicationOwner`
- [x] `Get-AzADApplication`
- [x] `Get-AzADApplicationKeyCredential`
- [x] `Get-AzADApplicationOwner`
- [x] `Get-AzADApplicationPasswordCredential`
- [ ] `New-AzADApplication`
    - Variant for using a certificate to use existing `-CertValue`, `-StartDate`, `-EndDate`
- [x] `New-AzADApplicationKeyCredential`
- [x] `New-AzADApplicationPasswordCredential`
- [x] `Remove-AzADApplication`
- [x] `Remove-AzADApplicationKeyCredential`
- [x] `Remove-AzADApplicationOwner`
- [x] `Remove-AzADApplicationPasswordCredential`
- [x] `Restore-AzADDeletedApplication`
- [x] `Update-AzADApplication`

### Group

- [x] `Add-AzADGroupMember`
- [x] `Add-AzADGroupOwner`
- [x] `Get-AzADGroup`
- [x] `Get-AzADGroupMember`
- [x] `New-AzADGroup`
- [x] `Remove-AzADGroup`
- [x] `Remove-AzADGroupMember`
- [x] `Remove-AzADGroupOwner`
- [x] `Test-AzADGroupMember`

### Service Principal

- [x] `Get-AzADServicePrincipal`
- [x] `Get-AzADServicePrincipalKeyCredential`
- [x] `Get-AzADServicePrincipalOwner`
- [x] `Get-AzADServicePrincipalPasswordCredential`
- [ ] `New-AzADServicePrincipal`
    - Variant that assigns role to service principal
- [x] `New-AzADServicePrincipalKeyCredential`
- [x] `New-AzADServicePrincipalPasswordCredential`
- [x] `Remove-AzADServicePrincipal`
- [x] `Remove-AzADServicePrincipalKeyCredential`
- [x] `Remove-AzADServicePrincipalPasswordCredential`
- [ ] `Update-AzADServicePrincipal`

### User

- [x] `Get-AzADUser`
- [x] `Get-AzADUserMemberGroup`
- [x] `New-AzADUser`
- [x] `Remove-AzADUser`
- [x] `Update-AzADUser`

### Other

- [ ] `Get-AzDomain`
    - Conflicts with alias for `Get-AzTenant` from `Az.Accounts`

#### Currently unable to test these commands since they always return `Forbidden`

- `Get-AzManagementGroup`
- `New-AzManagementGroup`
- `New-AzManagementGroupSubscription`
- `Remove-AzManagementGroup`
- `Remove-AzManagementGroupSubscription`
- `Set-AzManagementGroup`
- `Test-AzNameAvailability`
- `Update-AzManagementGroup`

### Resource Lock

- [x] `Get-AzResourceLock`
- [x] `New-AzResourceLock`
- [x] `Remove-AzResourceLock`
- [x] `Set-AzResourceLock`

### Role Assignment

- [ ] `Get-AzRoleAssignment`
    - Variant for `-SignInName`, `-ExpandPrincipalGroups` and `-ServicePrincipalName` using generated `-Filter`
    - Existing `-RoleDefinitionName` and `-RoleDefinitionId` just provide additional layer of filtering
- [ ] `New-AzRoleAssignment`
    - Variant for `-SignInName` and `-ApplicationId`
    - Variant for components of `-Scope` (`-ResourceGroupName`, `-ResourceName`, `-ResourceType`, `-ParentResource`)
    - Variant for `-RoleDefinitionName`
    - Hide generated `-Id` and `-RoleId` and use random GUID
- [ ] `Remove-AzRoleAssignment`
    - Use filtering logic from `Get-AzRoleAssignment` to get role assignment and then delete it

### Role Definition

- [x] `Get-AzRoleDefinition`
- [ ] `New-AzRoleDefinition`
    - Variant for `-InputFile`
- [x] `Remove-AzRoleDefinition`
- [ ] `Set-AzRoleDefinition`
    - Variant for `-InputFile`

### Other

- [x] `Get-AzDenyAssignment`

### Post-Preview

- [ ] `Get-AzPolicyAlias`
- [ ] `Invoke-AzResourceAction`
- [ ] `Set-AzPolicyAssignment`
    - Generic call to ARM is being used to make this call -- investigate why this call isn't in the spec

**Comment by markcowl** [comment]
Note: Please check why the hybrid profile doesn't have the resource group, active directory, and generic resource cmdlets
