### ISSUE TITLE
Powershell: Set-AzureServiceDiagnosticsExtension requires "-StorageContext" as mandatory

### ISSUE THREAD

**Issue by suzukidaisukesuzukidaisuke** [Azure/azure-powershell#931]
I would like to transfer WAD file of cloud service in a subscription and to save it in an account storage in another subscription using PowerShell (not by Visual Studio). 
When I executed Set-AzureServiceDiagnosticsExtension, it requires "-StorageContext" as mandatory.
I set storage account information in cscfg file. Set-AzureServiceDiagnosticsExtension cannot recognize storage account in a different subcsritpion because Set-AzureServiceDiagnosticsExtension must request "-StorageContext."
Please have  "-StorageContext" option.

**Comment by hovsepm** [comment]
@huangpf please have a look to the issue.

**Comment by huangpf** [comment]
@hovsepm The WAD extension cmdlet belongs to diagnostics team.

**Comment by sbtron** [comment]
@suzukidaisukesuzukidaisuke we have made a few updates to the Set-AzureServiceDiagnosticsExtension which should be available in the next release of PowerShell.
https://github.com/Azure/azure-powershell/pull/1614

StorageContext will now be optional. If your storage account is in the same subscription as the cloud service there is no need to specify the storage account key. If the storage account is in a different subscription than the cloud service then you do still need to specify the name and key through two new parameters -StorageAccountName and -StorageAccountKey. This should unblock your scenario. 
Will post another reply once the updated version is released and you could try it out then.
Thanks
