### ISSUE TITLE
Bug in Documentation New-AzOperationalInsightsSavedSearch

### ISSUE THREAD

**Issue by superfliege** [Azure/azure-powershell#9314]
New-AzOperationalInsightsSavedSearch

https://docs.microsoft.com/en-us/powershell/module/az.operationalinsights/new-azoperationalinsightssavedsearch?view=azps-2.1.0

Example one:
PowerShell

PS C:\>New-AzOperationalInsightSavedSearch -ResourceGroupName "ContosoResourceGroup" -WorkspaceName "ContosoWorkspace

![grafik](https://user-images.githubusercontent.com/23270629/58567148-20b1a700-8232-11e9-91a7-6ad5d40a3886.png)

Missing s in first example:
 New-AzOperationalInsight -s- SavedSearch

**Comment by niander** [comment]
@superfliege Thanks for filling out the bug issue

**Comment by superfliege** [comment]
Fixed in this pull requeest @niander 
https://github.com/Azure/azure-powershell/pull/9347
