### ISSUE TITLE
Many AzVM related commands fail to operate with DevTest Lab VMs (CloudShell)

### ISSUE THREAD

**Issue by oising** [Azure/azure-powershell#9317]
This is somewhat related to #7463 but is intended to declare problems with DevTest Lab virtual machines on a broader level. 

Frankly, it seems the VM metadata returned from Get-AzVM for Lab machines is not the same as regular VMs. It's missing some information that causes parameter binding to fail (although some cmdlets/functions lack the correct parameter flags -- e.g. ValueFromPipelineByPropertyName is false when it should be true.  For example a command as simple as `Get-AzVM -ResourceGroupName RGNAME | Enable-AzVMPSRemoting` fails to bind OsType among other things, despite OsType being available on the incoming object. 

```
The property 'WindowsConfiguration' cannot be found on this object. Verify that the property exists.
At /usr/local/share/powershell/Modules/PSCloudShellUtility/PSCloudShellUtility.psm1:1668 char:9
+     if ($vmInfo.OSProfile.WindowsConfiguration)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
+ FullyQualifiedErrorId : PropertyNotFoundStrict

Cannot convert null to type "OsType" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are "Windows,Linux".
At /usr/local/share/powershell/Modules/PSCloudShellUtility/PSCloudShellUtility.psm1:1270 char:9
+         $OsType = Get-OsType -Name $Name -ResourceGroupName $Resource ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Anyway, the more I dug into it, the more I realized that it seems highly likely that none of these commands were ever tested against DevTest Lab machines returned from Get-AzVM. Ultimately this is breaking the contract for Get-AzVM. Either add another OutputType to Get-AzVM to differentiate by extending `Microsoft.Azure.Commands.Compute.Models.PSVirtualMachine` to cover the differences, or fix the metadata return for DevTest lab machines.

**Comment by oising** [comment]
An example with `Enter-AzVM` which really emphasizes how broken it is:

```
PS Azure:\> Enter-AzVM -ResourceGroupName $rg -Name buildagent01 -Credential $cred
The property 'WindowsConfiguration' cannot be found on this object. Verify that the property exists.
At /usr/local/share/powershell/Modules/PSCloudShellUtility/PSCloudShellUtility.psm1:1668 char:9
+     if ($vmInfo.OSProfile.WindowsConfiguration)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
+ FullyQualifiedErrorId : PropertyNotFoundStrict

Unknown OSType - Only Windows/Linux Target VMs are supported.
At /usr/local/share/powershell/Modules/PSCloudShellUtility/PSCloudShellUtility.psm1:937 char:9
+         throw [System.ArgumentException] $badTargetVM
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], ArgumentException
+ FullyQualifiedErrorId : Unknown OSType - Only Windows/Linux Target VMs are supported.
```

**Comment by oising** [comment]
I got a little bit further by mocking the missing `OSProfile` property:

```
PS Azure:\> Update-TypeData -typename Microsoft.Azure.Commands.Compute.Models.PSVirtualMachine -MemberType NoteProperty -MemberName OSProfile -Value ([pscustomobject]@{WindowsConfiguration = "foo"})
PS Azure:\> & (get-module pscloudshellutility) { get-ostype buildagent01 $rg }
Windows
```
So at least now the internal `Get-OSType` function works, but it turns out that just unleashes a torrent of other errors as the deeper plumbing tries to query the NICs for the VM's public IP etc. 

Oh well, I tried. It seems like the lab VMs are the red-haired stepchild of Azure. Please fix.

**Comment by niander** [comment]
@raghushantha @maertendMSFT Hi. Could you take a look at this and let me know if this is a CloudShell related issue or a DevTest Lab one?

**Comment by oising** [comment]
After looking through the cloudshell module and the Az cmdlet source, I heavily suspect it's a DevTest Lab issue. The cmdlets are mostly source agnostic and depend on dynamic processing of the JSON returned from the core Azure APIs: It's seems this is a case of garbage in/garbage out.
