### ISSUE TITLE
Set-AzureRmRoleDefinition doesn't work

### ISSUE THREAD

**Issue by stopinskipawel** [Azure/azure-powershell#9322]
When I try to modify custom role I receive this error:
```
PS Azure:\> Set-AzureRmRoleDefinition -Role $role
Set-AzureRmRoleDefinition : The resource provider referenced in the action is not returned in the list of providers from Azure Resource Manager.
At line:1 char:1
+ Set-AzureRmRoleDefinition -Role $role
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzRoleDefinition], CloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.SetAzureRoleDefinitionCommand

```

**Comment by niander** [comment]
Please fill this out:

Take a look at the comments here and how to get the necessary information. Thanks!



## Description



## Steps to reproduce

```powershell

```

## Module versions



```powershell

```

## Debug output



```

```

## Error output



```

```

**Comment by dingmeng-xue** [comment]
@stopinskipawel, is there any update? Please try the latest cmdlet `Set-AzRoleDefinition`. If no, this issue will be closed soon due to inactivity.

**Comment by dingmeng-xue** [comment]
@stopinskipawel, thanks for your reporting. If you still have issue, please raise a new issue.
