### ISSUE TITLE
New-AzApiManagementApi -SubscriptionRequired 

### ISSUE THREAD

**Issue by Danlewis3** [Azure/azure-powershell#9325]
irrelevent of the switch being in place or not the subscriptionrequired is always set to true

```powershell

```

## Environment data

Name                           Value                                                                                                                                                  
----                           -----                                                                                                                                                  
PSVersion                      5.1.14409.1018                                                                                                                                         
PSEdition                      Desktop                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                
BuildVersion                   10.0.14409.1018                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                    
SerializationVersion           1.1.0.1        
## Module versions

Script     1.1.0      Az.ApiManagement                    {Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagementRegion, Add-AzApiManagementUserTo...

## Debug output

```

```

## Error output

```

```

**Comment by niander** [comment]
@Danlewis3 Hi. We need the full issue template filled out. Please fill the missing parts including the Debug Output, Error Output and all the module versions your have. Thanks
