### ISSUE TITLE
New-AzSubscription

### ISSUE THREAD

**Issue by bwatts64** [Azure/azure-powershell#9329]
## Description
After running new-azsubscription and creating a new azure subscription it appears that the azcontext gets corrupt. When you run get-azcontext the name property is empty and you can't fix it in the script. Tried doing the following and all of them come back with an error saying “Object reference not set to an instance of an object”
1)	Clear-azcontext
2)	Select-azcontext
3)	Logout-azaccount

## Steps to reproduce

Login to Azure then run new-azsubscription

## Environment data

Name                           Value                                                                               
----                           -----                                                                               
PSVersion                      5.1.17763.497                                                                       
PSEdition                      Desktop                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                             
BuildVersion                   10.0.17763.497                                                                      
CLRVersion                     4.0.30319.42000                                                                     
WSManStackVersion              3.0                                                                                 
PSRemotingProtocolVersion      2.3                                                                                 
SerializationVersion           1.1.0.1 

## Module versions

Az.Subscription: 0.7.1
Az.Account: 1.5.2

## Error output

“Object reference not set to an instance of an object”

**Comment by niander** [comment]
@bwatts64 Hi. Thank for filling out the issue. Could you please provide the full list of modules and the debug output? Please follow the instructions presented in the template when you open a new issue. Thanks

**Comment by markcowl** [comment]
@bwatts64 Also, the full list of modules in `Get-Module -ListAVailable`

**Comment by markcowl** [comment]
Closing for lack of response.  If you are still having this problem, please file an issue with the requested information.
