### ISSUE TITLE
0.9.8 ARM :: New-AzureProfile problem

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#934]
The following command is not guaranteed to return an Azure Profile object that points to the correct subscription.

```
New-AzureProfile -SubscriptionId <MySubID> -Credential (Get-Credential);
```

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by hovsepm** [comment]
@pcgeek86 , We are unable to repro it with latest Azure Powershell release (version 0.9.9). Please verify that this still occurs and reopen the issue with PS modules versions.
