### ISSUE TITLE
Track work for generated AppService cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#9342]
## Outstanding Issues

- [Name in body parameters should not be exposed](https://github.com/Azure/autorest.powershell/issues/324)

## App Service

_Note_: the below list only contains cmdlets from the existing `Az.Websites` module -- there are ~400 more cmdlets that were generated but aren't currently exposed by the `Az.Websites` module. These cmdlets will need to be evaluated at a later time.

### General

- [ ] Where applicable, add a variant to introduce a `-WebApp` parameter

### App Service Plan

- [ ] `Get-AzAppServicePlan`
    - [ ] Determine if `-Location` is needed since it was client-side filtering
- [ ] `Get-AzAppServicePlanMetric`
    - [ ] Variant that adds `-Metrics`, `-StartTime`, `-EndTime` and `-Granularity` using generated `-Filter`
    - [ ] Variant that adds `-AppServicePlan`
- [ ] `New-AzAppServicePlan`
    - [ ] Variant that adds `-AseName` and `-AseResourceGroupName` to construct `-HostingEnvironmentProfileId`
- [ ] `Remove-AzAppServicePlan`
    - [ ] Variant that adds `-AppServicePlan`
- [ ] `Set-AzAppServicePlan`

### Certificate

- [ ] `Get-AzWebAppCertificate`
    - [ ] Determine if `-Thumbprint` is needed since it was client-side filtering

### Web App

- [x] `Backup-AzWebApp`
- [ ] `Get-AzDeletedWebApp`
    - [ ] Determine if `-ResourceGroupName`, `-Name` and `-Slot` are needed since they were client-side filtering
- [ ] `Get-AzWebApp`
    - [ ] Variant that adds `-AppServicePlan`
    - [ ] Determine if `-Location` is needed since it was client-side filtering
- [ ] `Get-AzWebAppMetric`
    - [ ] Variant that adds `-Metrics`, `-StartTime`, `-EndTime` and `-Granularity` that calls generated `-Filter`
- [x] `Get-AzWebAppPublishingCredentials`
- [ ] `Get-AzWebAppPublishingProfile`
- [ ] `New-AzWebApp`
    - [ ] Variant that adds simple creation scenario
- [ ] `New-AzWebAppPublishingPassword`
    - [x] Variant that adds `-SiteObject` (`-WebApp`, `-WebAppSlot` as aliases)
- [ ] `Remove-AzWebApp`
    - [x] Variant that adds `-SiteObject` (`-WebApp`, `-WebAppSlot` as aliases)
- [ ] `Restart-AzWebApp`
    - [x] Variant that adds `-SiteObject` (`-WebApp`, `-WebAppSlot` as aliases)
- [ ] `Restore-AzDeletedWebApp`
    - [ ] Determine if we need existing `-TargetResourceGroupName`, `-TargetName`, `-TargetSlot` and `-TargetAppServicePlanName` parameters
- [ ] `Restore-AzWebApp`
    - [x] Variant that adds `-SiteObject` (`-WebApp`, `-WebAppSlot` as aliases)
- [ ] `Set-AzWebApp`
    - [ ] Determine which of the existing parameters we need to keep
- [ ] `Start-AzWebApp`
    - [x] Variant that adds `-SiteObject` (`-WebApp`, `-WebAppSlot` as aliases)
- [ ] `Stop-AzWebApp`
    - [x] Variant that adds `-SiteObject` (`-WebApp`, `-WebAppSlot` as aliases)

### Web App Backup

- [x] `Get-AzWebAppBackup`
    - [ ] Do we need to add `-BackupId`?
- [ ] `Get-AzWebAppBackupConfiguration`
    - [x] Variant that adds `-SiteObject` (`-WebApp`, `-WebAppSlot` as aliases)
- [x] `Get-AzWebAppBackupStatus`
- [ ] `Remove-AzWebAppBackup`
    - [x] Variant that adds `-SiteObject` (`-WebApp`, `-WebAppSlot` as aliases)
- [ ] `Set-AzWebAppBackupConfiguration`
    - [ ] Variant that adds `-SiteObject` (`-WebApp`, `-WebAppSlot` as aliases)

### Web App Slot

- [ ] `Get-AzWebAppSlot`
- [ ] `Get-AzWebAppSlotConfigurationName`
- [ ] `Set-AzWebAppSlotConfigurationName`
    - [ ] Determine if we want to keep existing `-RemoveAllAppSettingNames` and `-RemoveAllConnectionStringNames` parameters that just set `-AppSettingName` and `-ConnectionStringName` parameters to empty
- [ ] `Switch-AzWebAppSlot`
    - [ ] Determine if we need existing `-SwapWithPreviewAction` parameter

### Web App Snapshot

- [x] `Get-AzWebAppSnapshot`
- [ ] `Restore-AzWebAppSnapshot`
    - [x] Variant that adds `-SiteObject` (`-WebApp`, `-WebAppSlot` as aliases)

## Missing Cmdlets

- [ ] Enter-AzWebAppContainerPSSession
    - [ ] Investigate how to recreate this cmdlet
- [ ] Get-AzWebAppSSLBinding
    - [ ] Cmdlet to get a property on a web app -- do we want to recreate this?
- [ ] New-AzWebAppAzureStoragePath
    - [ ] Creates an in-memory object -- do we need to recreate this?
- [ ] New-AzWebAppContainerPSSession
    - [ ] Investigate how to recreate this cmdlet
- [ ] New-AzWebAppDatabaseBackupSetting
    - [ ] Creates an in-memory object -- do we need to recreate this?
- [ ] New-AzWebAppSSLBinding
    - [ ] Investigate how to recreate this cmdlet
- [ ] Publish-AzWebApp
    - [ ] Investigate how to recreate this cmdlet -- uses a generic `HttpClient` to publish the web app, doesn't use any calls from Websites client
- [ ] Remove-AzWebAppSSLBinding
    - [ ] Investigate how to recreate this cmdlet

**Comment by btardif** [comment]
@cormacpayne assign this to you to make sure it doesn't show up on our triage queries

**Comment by tjrobinson** [comment]
I can see that `Az.AppService` `4.0.2-preview` now has these commands. Is there an ETA for V4 to be out of preview?
