### ISSUE TITLE
0.9.8 ARM :: Rename New-AzureAutomationModule

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#935]
The synopsis for the command even uses the verb "import," so why doesn't the command match the convention that is shared by other Azure Automation commands?

![image](https://cloud.githubusercontent.com/assets/466713/9967128/ef0916f4-5dfd-11e5-8f90-9f34280382ee.png)

![image](https://cloud.githubusercontent.com/assets/466713/9967152/0fd0ad16-5dfe-11e5-9044-3aac97b6bd4b.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by jodoglevy** [comment]
Thanks, we'll add an alias for Import

**Comment by pcgeek86** [comment]
Hey @jodoglevy, did you already fix this? I'm pretty sure I'm running the latest version of all ARM PowerShell modules, and it looks like there is not an alias, unless I need to explicitly import the Azure Automation module first.

<img width="919" alt="screen shot 2016-01-31 at 12 48 38 pm" src="https://cloud.githubusercontent.com/assets/466713/12701903/02d25aee-c819-11e5-9160-665dd3c25f78.png">

Cheers,
Trevor Sullivan

**Comment by jodoglevy** [comment]
No this is not fixed

**Comment by maddieclayton** [comment]
Fixed
