### ISSUE TITLE
Get-AzRemoteDesktopFile Won't pull private IP

### ISSUE THREAD

**Issue by kekindt** [Azure/azure-powershell#9366]
Trying to use Get-AzRemoreDesktopFile for a vm that only has a private ip fails with the error: 

Get-AzRemoteDesktopFile : Value cannot be null.
Parameter name: source
At line:1 char:1
+ Get-AzRemoteDesktopFile -resourcegroupname "RSG-xxxxxxx ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzRemoteDesktopFile], ArgumentNullException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.GetAzureRemoteDesktopFileCommand

Generating the file from portal.azure.com works fine and allows the option to use public or private ip.

**Comment by markcowl** [comment]
@kekindt Can you provide the rest of the info asked for in our issue template for this issue:

(1) Module layout on your machine
``` powershell
Get-Module -ListAvailable
```
(2) Execution environment
``` powershell
$PSVersionTable
```
(3) Debug output

Before running the cmdlet, set `$DebugPreference="Continue` and then provide the extra printed traces

(4) Error Output

After the error, run `Resolve-AAzError` (or `Resolve-AzureRmError` if this is AzureRM)

**Comment by kekindt** [comment]
[Debug-Error output.txt](https://github.com/Azure/azure-powershell/files/3259136/Debug-Error.output.txt)
[Get-Module.txt](https://github.com/Azure/azure-powershell/files/3259137/Get-Module.txt)
[PSVersionTable.txt](https://github.com/Azure/azure-powershell/files/3259138/PSVersionTable.txt)
Attached are text files with the requested information. I didn't see anything in the template when I created the issue. Sorry.

**Comment by markcowl** [comment]
@Drewm3 is this fixed in the current release bits?

**Comment by Drewm3** [comment]
@hyonholee, could you confirm the 10-15 payload is the correct release?

**Comment by dingmeng-xue** [comment]
Close it due to inactive. Please submit a new issue if there is any concern.
