### ISSUE TITLE
Track work for generated Storage.Management cmdlets

### ISSUE THREAD

**Issue by niander** [Azure/azure-powershell#9368]
### StorageAccount

* `Get-AzStorageAccount`
    - [x] Hide `Get-AzStorageAccountProperty`
    - [x] Add `-Name` and use `Get-AzStorageAccountProperty`
* `Set-AzStorageAccount`
    - [x] Change name to `Invoke-AzStorageAccountFailover` or something else
* `Update-AzStorageAccount`
    - [x] Update `-AccountName` to just `Name`
    - [x] Return results after calling `GetProperties`
    - [x] Add two new parameter sets: Make `-KeyvaultEncryption` become two boolean parameters -- `-StorageEncryption` and `-KeyvaultEncryption` 
      - Note: this is to support a parameter set with additional parameters when KeyVaultEncryption is selected
    - [x] Add `-AssignIdentity` that resets `Identity`
    - [x] Rename the parameter prefix `NetworkAcls` to `NetworkRuleSet`
    - [ ] Add `-UpgradeToStorageV2` and hide `-Kind` ? (Ask Wei)
* `New-AzStorageAccount`
    - [x] Update `-AccountName` to just `Name`
    - [ ] Uses `NameAvailability` before creating
    - [x] Return results after calling `GetProperties`
    - [x] Add `-AssignIdentity` that resets `Identity`
    - [x] Rename the parameter prefix `NetworkAcls` to `NetworkRuleSet`
    - [x] `-IsHnsEnabled` -> `-EnableHierarchicalNamespace`
- [x] Determine if the lack of in-memory creation cmdlets for `NetworkRuleSet` and `ManagementPolicy*` is not a problem
    - Check the file `resources/comparing_modules_notes.md` for more info.

### Blobs or Storage Container
 
* `Set-AzRmStorageContainerImmutabilityPolicy`
    - [x] Add `-ExtendedPolicy` switch parameter that invokes `Invoke-AzExtendBlobContainerImmutabilityPolicy`

## Phase II

- [ ] Create `Set-AzCurrentStorageAccount`

**Comment by blueww** [comment]
@niander 
I might lost in this issue.
Could you give some background for:

- Why we need "Storage.Management"?

- What's the relationship of it and Az.Storage?

**Comment by markcowl** [comment]
@blueww this is work for the generated cmdlets that support profiles, We discussed this with @vincent81-jiang breifly and will be reaching out to service teams with specifics later this year.

**Comment by cormacpayne** [comment]
@niander please close this issue and open a new one outlining any remaining issues that need to be resolved in the generated `Az.Storage` (management) cmdlets.
