### ISSUE TITLE
New-AzureRMAutoscaleProfile: Requires Rule parameter

### ISSUE THREAD

**Issue by Midacts** [Azure/azure-powershell#9369]
## Description

Unable to "Scale to a specific instance count".
When running `New-AzureRMAutoscaleProfile` it requires the `-Rule` parameter be set.

## Steps to reproduce

```powershell
$AutoScaleRuleUp = New-AzureRmAutoscaleRule -MetricName "CpuPercentage" -MetricResourceId "/subscriptions/xxx/resourceGroups/MyRG/providers/Microsoft.Web/serverfarms/MyRG" -MetricStatistic "Average" -Operator "GreaterThan" -Threshold 80 -TimeGrain 00:05:00 -ScaleActionDirection "Increase" -ScaleActionValue "1" -ScaleActionCooldown 00:05:00

$AutoScaleProfileSchedule = New-AzureRmAutoscaleProfile -Name "Schedule" -DefaultCapacity "2" -MaximumCapacity "2" -MinimumCapacity "2" -TimeWindowTimeZone UTC -StartTimeWindow 2019-07-26T00:00:00 -EndTimeWindow 2019-07-27T23:59:00
-Rule $AutoScaleRuleUp

Add-AzureRmAutoscaleSetting -Location "East US" -Name "Auto Scale Setting" -ResourceGroup "MyRG" -TargetR
esourceId "/subscriptions/xxxx/resourceGroups/MyRG/providers/microsoft.web/server
Farms/MyRG" -AutoscaleProfile $AutoScaleProfileSchedule
```

## Module versions

6.4.0

I want this:
![image](https://user-images.githubusercontent.com/3960208/58983726-7bed1780-87a5-11e9-8f4e-e46f25daaf7f.png)

instead i get this:
![image](https://user-images.githubusercontent.com/3960208/58983827-a8a12f00-87a5-11e9-9a68-dee5bd518bb3.png)

**Comment by markcowl** [comment]
@Midacts Have you tried the `Az.Websites` [module](https://www.powershellgallery.com/packages/Az.Websites/1.2.2)?  AzureRM is no longer under active development, so you should expect new features to only occur in Az.

**Comment by markcowl** [comment]
Closing for lack of response.  Please open a new issue with the requested information if you are still seeing an issue.

**Comment by katlimruiz** [comment]
I do have the same issue, and I have not found any method in Az.Websites (even more, scaling actually belongs to another module, not webapps).

**Comment by Midacts** [comment]
https://stackoverflow.com/questions/48943288/how-to-change-azure-portal-vmss-scale-condition-scale-to-a-specific-instance-co

Jason Ye:

> For now, Azure PowerShell does not support to create Azure VMSS scale rules based on schedule.
> 
> To create autoscale rules based on a schedule rather than host metrics, use the Azure portal. Schedule-based rules cannot currently be created with Azure PowerShell.

We just created a default scaleset and then added a scheduled one that had a super low CPU utilization  (0) that would cause it to be triggered on the schedule.
It's kind of a hack, but it works.

**Comment by keerthi13** [comment]
we can do it using Azure Cli 

call az monitor autoscale create --count %nonBusinessHourInstances% --resource "%resource%" --name "%autoScaleSettingName%"

call az monitor autoscale profile create --autoscale-name "%autoScaleSettingName%" --name "%businessHoursProfileName%"  --count %businessHourInstances% --resource-group "%resourceGroupName%" --recurrence week mon tue wed thu fri --timezone "Central Standard Time" --start "T06:00:00" --end "T19:00:00"
