### ISSUE TITLE
Enable-AzureRmAlias creates incorrect alias for Set-AzureRmVMBootDiagnostics

### ISSUE THREAD

**Issue by aparker-isolved** [Azure/azure-powershell#9374]
The Enable-AzureRmAlias command creates an incorrect alias for Set-AzureRmVMBootDiagnostics.  It creates an alias to Set-AzVMBootDiagnostics (note the "s" at the end) when it should create an alias to Set-AzVMBootDiagnostic (no "s" at the end for this command).

**Comment by markcowl** [comment]
Fix checked in - should be available next release
