### ISSUE TITLE
Get-AzStorageFile not pulling properties correctly

### ISSUE THREAD

**Issue by DBrownStratiform** [Azure/azure-powershell#9389]
After running get-azstoragefile to grab a file or directory in an Azure Storage Account and then viewing the properties of the result, the properties are missing. I see IsServerEncrypted and Length, but all the other properties are empty. Viewing these properties in the GUI shows they do have values (such as LastModified and ETag).

For example, running the following returns no data for LastModified:
 
$Dirs = get-azstoragefile -Context $Storageaccount.Context -ShareName backup
foreach ($Dir in $Dirs) {
     Write-Host $Dir.Name " - "  $Dir.Properties.LastModified
}

**Comment by blueww** [comment]
@DBrownStratiform 

This is because not all the file properties will be returned in list File currently  (such as LastModified and ETag won't return).
You can run FetchAttributes() on each of the listout files to get the information.

We don't add FetchAttributes() to the Get-AzStorageFile cmdlet, since it need to run on each item, and will take long time if list out many items.

Following is a sample for the File Items properties before and after FetchAttributes().

```
PS C:\temp> $f = Get-AzureStorageFile -ShareName $containerName -Context $ctx
                                                                                                                                            
PS C:\temp> $f[0].Properties

CacheControl       : 
ContentDisposition : 
ContentEncoding    : 
ContentLanguage    : 
Length             : 2097152
ContentMD5         : 
ContentType        : 
ETag               : 
LastModified       : 
IsServerEncrypted  : False

PS C:\temp> $f[0].FetchAttributes()

PS C:\temp> $f[0].Properties

CacheControl       : 
ContentDisposition : 
ContentEncoding    : 
ContentLanguage    : 
Length             : 2097152
ContentMD5         : bqUxW6Bsbx3/sdrQQJXong==
ContentType        : 
ETag               : "0x8D6ED544BCA8EA9"
LastModified       : 6/10/2019 3:32:42 AM +00:00
IsServerEncrypted  : True
```

**Comment by markcowl** [comment]
Closing as resolved. Please let us know if you are still seeing an issue.

**Comment by DBrownStratiform** [comment]
Thank you. That’s what I was missing!

**Comment by blueww** [comment]
@jwashbur79 
As $folder is a file directory, not a file, it should use cmdlet: Remove-AzStorageDirectory, instead of remove-azstoragefile.
