### ISSUE TITLE
webapp: Update Get-AzureRmWebAppCertificate  to use the ArmCache RG filtering when -ResourceGroup parameter is used.

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-powershell#9392]
## Steps to reproduce

```powershell

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by btardif** [comment]
@Nking92 can this be closed given your changes got merged? or is there something else missing?

**Comment by Nking92** [comment]
Closing this now. It's been fixed with that change.
