### ISSUE TITLE
Update Signing process for Az

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#9396]
## Description
Current Pipeline is [here](https://dev.azure.com/azure-sdk/internal/_build?definitionId=217&_a=summary)
- [x] Install Wix on the worker [wix website](https://wixtoolset.org/
 - [x] Add steps to build, sign, and publish installer
- [x] Update the signing process to get up to speed with the latest security guidelines this includes:
  - [x] Authenticode Signing for PSD1 files using existing Sha-2 signing certs
  - [x] Authenticode signing for 3rd-party dll dependencies using the 3rd party signing cert (Newtonsoft.json, automapper, yaml.dotnet) description: https://liquid.microsoft.com/Web/Object/Read/ms.security/Requirements/Microsoft.Security.Cryptography.37010
- [x] Update post-build signing validation to include the new file types
- [x] Validate against last signed build (\\aaptfile01\adxsdk\PowerShell\2019_07_30_PowerShell or https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign-esrp/466/)
- [ ] Replicate signing pipeline for private repo

Jenkins Job: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign-esrp/

## Cost : 10

**Comment by isra-fel** [comment]
GJ @VeryEarly
