### ISSUE TITLE
Track work for generated Compute Module

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#9399]
### Creation cmdlets **Cost: 10**
- [x] Generate necessary artifacts in other RPs (5)
  - [ ] StorageAccount
  - [ ] NIC
  - [ ] Network
  - [ ] Subnet
  - [ ] NSG
  - [ ] Application Galeway
  - [ ] Load Balancer
- [x] Move Strategies Library to new mibrary dependencies(5)
- [ ] Add common facility to upload VHDs
- [x] **New-AzVM** (5)
  - [x] Create variants for linux and windows VMs
  - [x] Simple parameters for added Disks
- [x] **New-AzVmss** (5)
  - [x] Create variants for AG/load balancer, and windows versus linux VMProfiles

### Update Cmdlets **Cost: 5**
- [ ] Variants for linux and windows VMs
- [ ] Set-AzVM
- [ ] Set-AzVmss
- [ ] Update-AzVM
- [ ] Update-AzVmss

### Gets combined with InstanceView for Status 
- [ ] **Get-AzVM**: Combine with **Invoke-AzVMInstanceView**
- [ ] **Get-AzVMExtension** : Combine with **Invoke-AzVMInstanceView**
- [ ] **Get-AzVmss** : 
  - [ ] Combine with **Get-AzVmssInstanceView**
  - [ ] Combine with **Get-AzVmssOSUpgradeHistory**
- [ ] **Get-AzVmssVM**: Combine with **Get-AzVmssVMInstanceView**

### Stops combined with deallocate 
- [ ] **Stop-AzVM**: Combine with **Invoke-AzDeallocateVM**
- [ ] **Stop-AzVMss**: Combine with **Invoke-AzDeallocateVmss**
- [ ] **Stop-AzVmssVM**: Combine with **Invoke-AzDeallocateVmssVM**

### Combine Update with Redeploy and ReImage 
- [ ] **Set-AzVM**'
- [ ] **Set-AzVmss**
  - [ ] Comvbine with **Set-AzVmssInstance**
- [ ] **Set-AzVmssVM**

### Implement Custom Serialization for Save-AzVMImage **Cost: 4**
- [ ] Implement custom json serialization logic in model type
- [ ] Convert cmdlet from object to file output

### Miscellaneous **Cost: 4**
- [ ] **Get-AzVMExtensionImage** Implement FilterExpression
- [ ] **Get-AzVMSize**
  - [ ] Combine with **Get-AzVMAvailableSIze** to get size options for a single VM
  - [ ] Combine with **Get-AzAvailabilitySetAvailableSIze** to get size options for an AvailabilitySet
- [ ] **Restart-AzVM**
  - [ ] Comvine with **Invoke-AzVmPerformMaintenance**
- [ ] **Remove-AzVmss**
  - [ ] Combine with **Remove-AzVmssInstance**
- [ ] Update Type formatting
- [ ] Model validation after bug fixes

**Comment by markcowl** [comment]
## Blocking Issues
- [Model directives failing](https://github.com/Azure/autorest.powershell/issues/353)
- Model Flattening bugs
  - [348](https://github.com/Azure/autorest.powershell/issues/348)
  - [347](https://github.com/Azure/autorest.powershell/issues/347)
  - [346](https://github.com/Azure/autorest.powershell/issues/346)
- [Clashing pipeline usage for Set cmdlets](https://github.com/Azure/autorest.powershell/issues/308)

**Comment by markcowl** [comment]
## Remaining Work

### Additional Scenarios
- [ ] Blob upload for VM creation **Size: 10**
### Waiting for Generator XML Support
- [ ] Get-AzRemoteDesktopFile **Size: 2**
  - [ ] Switch output to file system

### Typed VM Extension cmdlets **Size: XL**
- [ ] Get-AzVMAccessExtension
- [ ] Get-AzVMADDomainExtension
- [ ] Get-AzVMAEMExtension
- [ ] Get-AzVMBootDiagnosticsData
- [ ] Get-AzVMChefExtension
- [ ] Get-AzVMCustomScriptExtension
- [ ] Get-AzVMDiagnosticsExtension
- [ ] Get-AzVMDiskEncryptionStatus
- [ ] Get-AzVMDscExtension
- [ ] Get-AzVMDscExtensionStatus
- [ ] Get-AzVMSqlServerExtension
- [ ] Get-AzVmssDiskEncryption
- [ ] Get-AzVmssVMDiskEncryption
- [ ] Publish-AzVMDscConfiguration
- [ ] Remove-AzVMAccessExtension
- [ ] Remove-AzVMAEMExtension
- [ ] Remove-AzVMBackup
- [ ] Remove-AzVMChefExtension
- [ ] Remove-AzVMCustomScriptExtension
- [ ] Remove-AzVMDataDisk
- [ ] Remove-AzVMDiagnosticsExtension
- [ ] Remove-AzVMDiskEncryptionExtension
- [ ] Remove-AzVMDscExtension
- [ ] Remove-AzVMNetworkInterface
- [ ] Remove-AzVMSecret
- [ ] Remove-AzVMSqlServerExtension
- [ ] Remove-AzVmssDataDisk
- [ ] Remove-AzVmssDiagnosticsExtension
- [ ] Remove-AzVmssNetworkInterfaceConfiguration
- [ ] Remove-AzVmssVMDataDisk
- [ ] Set-AzVMAccessExtension
- [ ] Set-AzVMADDomainExtension
- [ ] Set-AzVMAEMExtension
- [ ] Set-AzVMBackupExtension
- [ ] Set-AzVMBginfoExtension
- [ ] Set-AzVMBootDiagnostic
- [ ] Set-AzVMChefExtension
- [ ] Set-AzVMCustomScriptExtension
- [ ] Set-AzVMDataDisk
- [ ] Set-AzVMDiagnosticsExtension
- [ ] Set-AzVMDiskEncryptionExtension
- [ ] Set-AzVMDscExtension
- [ ] Set-AzVMSqlServerExtension
- [ ] Set-AzVmssBootDiagnostic
- [ ] Set-AzVmssDiskEncryptionExtension
- [ ] Test-AzVMAEMExtension

**Comment by markcowl** [comment]
## Other Differences

### Added cmdlets (previously hidden functionality)
- ConvertTo-AzVmssSinglePlacementGroup
- Get-AzVmssExtension
- Invoke-AzVMPerformMaintenance
-  New-AzVMExtension
-  New-AzVmssExtension
-  Remove-AzVmssInstance
-  Remove-AzVmssVM
-  Restart-AzVmssVM
-  Set-AzAvailabilitySet
-  Set-AzDisk
-  Set-AzImage
-  Set-AzProximityPlacementGroup
-  Set-AzSnapshot
-  Set-AzVmssExtension
-  Start-AzVmssRollingUpgradeExtensionUpgrade
-  Start-AzVmssVM
-  Stop-AzVmssVM
-  Update-AzProximityPlacementGroup
-  Update-AzVMExtension

### Container Service (In Deprecation, removed)
- Add-AzContainerServiceAgentPoolProfile
- Get-AzContainerService
- New-AzContainerService
- Remove-AzContainerService
- Remove-AzContainerServiceAgentPoolProfile
- Update-AzContainerService

### In-Memory cmdlets (removed)
- Add-AzImageDataDisk
- Add-AzVhd
- Add-AzVMAdditionalUnattendContent
- Add-AzVMDataDisk
- Add-AzVMNetworkInterface
- Add-AzVMSecret
- Add-AzVmssAdditionalUnattendContent
- Add-AzVmssDataDisk
- Add-AzVmssDiagnosticsExtension
- Add-AzVmssExtension
- Add-AzVMSshPublicKey
- Add-AzVmssNetworkInterfaceConfiguration
- Add-AzVmssSecret
- Add-AzVmssSshPublicKey
- Add-AzVmssVMDataDisk
- Add-AzVmssWinRMListener
- Disable-AzVMDiskEncryption
- Disable-AzVmssDiskEncryption
- New-AzContainerServiceConfig
- New-AzDiskConfig
- New-AzDiskUpdateConfig
- New-AzImageConfig
- New-AzSnapshotConfig
- New-AzSnapshotUpdateConfig
- New-AzVMConfig
- New-AzVMDataDisk
- New-AzVMSqlServerAutoBackupConfig
- New-AzVMSqlServerAutoPatchingConfig
- New-AzVMSqlServerKeyVaultCredentialConfig
- New-AzVmssConfig
- New-AzVmssIpConfig
- New-AzVmssIpTagConfig
- New-AzVmssVaultCertificateConfig
- Remove-AzImageDataDisk
- Set-AzImageOsDisk
- Set-AzDiskDiskEncryptionKey
- Set-AzDiskImageReference
- Set-AzDiskKeyEncryptionKey
- Set-AzDiskUpdateDiskEncryptionKey
- Set-AzDiskUpdateKeyEncryptionKey
- Set-AzSnapshotDiskEncryptionKey
- Set-AzSnapshotImageReference
- Set-AzSnapshotKeyEncryptionKey
- Set-AzSnapshotUpdateDiskEncryptionKey
- Set-AzSnapshotUpdateKeyEncryptionKey
- Set-AzVMOperatingSystem
- Set-AzVMOSDisk
- Set-AzVMPlan
- Set-AzVMSourceImage
- Set-AzVmssOsProfile
- Set-AzVmssRollingUpgradePolicy
- Set-AzVmssStorageProfile

**Comment by cormacpayne** [comment]
@markcowl please close this issue and open a new one outlining any remaining issues that need to be resolved in the generated `Az.Compute` cmdlets.
