### ISSUE TITLE
Track work for generated Monitor cmdlets

### ISSUE THREAD

**Issue by niander** [Azure/azure-powershell#9405]
## Monitor

Obs: Check the file `resources/comparing_modules_notes.md`

### ActivityLog

* `Get-AzActivityLog`
    - [x] Replace `-Filter` with the other parameters:
        * `StartTime`, `EndTime`, `Status`, `Caller`, `CorrelationId`, `ResourceProvider`, `ResourceGroupName`
* `Get-AzTenantActivityLog`
    - [x] Replace `-Filter` with the other parameters:
        * `StartTime`, `EndTime`, `Status`, `Caller`, `CorrelationId`, `ResourceProvider`, `ResourceGroupName`

### ActivityLogAlert

* `Get-AzActivityLogAlert`
* `Remove-AzActivityLogAlert`
* `New-AzActivityLogAlert`
* `Set-AzActivityLogAlert`
    - [x] (?) Since the default is creating an enabled alert. Remove `-Enabled` switch parameter and add `-DisableAlert`, that disables the alert if used.
    - Verify if normal action groups (the ones created using the action groups cmdlets) can be used in the `-ActionGroup` parameter.
* `Update/Enable/Disable-AzActivityLogAlert`
    - [x] Add Disable and Enable variants and hide the update

### ActionGroup

* `Get-AzActionGroup`
* `Remove-AzActionGroup`
* `Set-AzActionGroup`
    - [x] `-GroupShortName` -> `-ShortName`
    - [x] Hide all the specific `Receiver` parameters i.e. `-EmailReceiver` and implement just one parameter that receives an array of generic receivers
        * Obs: It seems that the spec specify more kinds of receiver that the original code actually uses/creates with the in-memory creation cmdlet `New-AzActionGroupReceiver`
* `New-AzActionGroup`
    * Obs: This is not similar to the original `New-AzActionGroup` which is used only for `ActivityLogAlerts`
    - [x] Apply the same changes made to `Set-AzActionGroup`
* `Update-AzActionGroup`
* `Enable-AzActionGroupReceiver`
    - [x] (?) Decide if keep or hide this cmdlet: it only changes the status from disable to enable for SMS and Email receivers of a given action group
         * Hid it

### Metric

* `Get-AzMetric`
    - [x] Implement the parameters from `New-AzMetricFilter` and replace it for `-Filter`
         * NOT doing because the description is good enough (it follows what CLI does)
    - [ ] change `-Aggregation` type from string to `AggregationType` (defined in another resource spec `MetricDefinition`)
    - [x] Add alias or rename `-Interval` to `-TimeGrain`
    - [ ] (?) Replace `-Timespan` for `-StartTime` and `-EndTime`
    - [x] Change `-ResourceUri` to `-ResourceId`
* `New-AzMetric`
    - [x] Hide this new cmdlet.
* `Get-AzMetricDefinition`
    - [x] Add `-MetricName` parameter used to filter the results
    - [x] (?) Add `-DetailedOutput` that returns a metric definition with full details or not
* `Get-AzMetricBaseline`
* `Get-AzMetricNamespace`

### MetricAlert (metric alerts V2 API)

* `Get-AzMetricAlert`
    - [x] Rename `-RuleName` to `-Name`
* `New-AzMetricAlert`
    - [x] Rename `-RuleName` to `-Name`
    - [x] (?) Rename `-CriterionOdataType` to `-Condition`
    * (?) Verify the need of creating two parameter sets here -- one for a specific resourceId or a list of scopes.
        * Specific resourceId parameter set:
            - [x] Hide `-Scope`, `-TargetResourceRegion` and `-TargetResourceType`. Add `-TargetResourceId` parameter which value is added to `-Scope` parameter for the API call
        * Scopes parameter set:
            - [x] (?) Rename or add alias `-Scope` to `-TargetResourceScope`
    - [x] (?) Since the default is creating an enabled alert. Remove `-Enabled` switch parameter and add `-DisableAlert`, that disables the alert if used.
* `Set-AzMetricAlert`
    * Obs: The original does not implements a `Set`
    - [x] Hide the `Set`
* `Update-AzMetricAlert`
    - [x] Apply the same changes made for the `New`
* `Remove-AzMetricAlert`
    - [x] Rename `-RuleName` to `-Name`

### AlertRule (old API)

* `Get-AzAlertRule`
    - [x] Rename `-RuleName` to `-Name`
    - [x] Add `-TargetResourceId` and the customization to filter alerts by `ResourceId`
* `New-AzAlertRule`
    - [x] Rename `-RuleName` to `-Name`
    - [x] Investigate the need of `-DataSourceOdataType`
    - [x] (?) `Odata.Type` vs `RuleCondition` type
* `Remove-AzAlertRule`
    - [x] Rename `-RuleName` to `-Name`
* `Set-AzAlertRule`
    - [x] (?) New command. Hide it?
* `Update-AzAlertRule`
* `Get-AzAlertRuleIncident`
    * Obs: New command.
    - [x] Rename `-RuleName` to `-Name` (for consistency)

### LogProfile

* `Set-AzLogProfile`
    - [x] Hide `-RetentionPolicyDay` and `-RetentionPolicyEnabled`
    - [x] Add `-RetentionInDays` and the following logic:
        * `-RetentionPolicyDay` receives 0 and `-RetentionPolicyEnabled` false if `-RetentionInDays` is missing.
        * `-RetentionPolicyEnabled` true if `-RetentionInDays` is used.
* `Get-AzLogProfile`
* `Remove-AzLogProfile`
* `New-AzLogProfile`
    - [x] Apply same changes from `Set`
* `Update-AzLogProfile`
    - [x] Apply same changes from `Set`

### Autoscale

* `Set-AzAutoscaleSetting`
    - [x] Rename or add alias from `-Profile` to `-AutoscaleProfile`
    - [x] Rename `-TargetResourceUri` to `-TargetResourceId`
* `Get-AzAutoscaleSetting`
* `Remove-AzAutoscaleSetting`
* `New-AzAutoscaleSetting`
    - [x] Apply same changes made to `Set`
* `Update-AzAutoscaleSetting`
* (?) `Get-AzAutoescaleHistory`
    - [ ] (?) Implemente cmdlet that uses `ActivityLogs` API to retrieve only logs about autoscale settings.

### ScheduledQuery

* `New-ScheduledQueryRule`
    - [x] Rename `-RuleName` to `-Name`
    - [x] Change `-Enabled` type to boolean
    - [x] The `-ActionOdataType` actually receives types `AlertingAction` or `LogToMetricAction`
* `Set-ScheduledQueryRule`
    - [x] Apply same changes made to `New`
* `Update-ScheduledQueryRule`
    - [x] Rename `-RuleName` to `-Name`
    - [x] Change `-Enabled` type to boolean
* `Remove-AzScheduledQueryRule`
    - [x] Rename `-RuleName` to `-Name`
* `Get-AzScheduledQueryRule`
    - [x] Rename `-RuleName` to `-Name`

### DiagnosticSetting

* `Set-AzDiagnosticSetting`
    - [x] (?) Check the need to add `DiagnosticSettingsCategory` validation that uses `Get-AzDiagnosticSettingsCategory`
    - [x] Give better examples on how to use the non expanded parameters `-Log` and `-Metric`
    - [x] Rename `ResourceUri` to `ResourceId`
* `Get-AzDiagnosticSetting`
* `Remove-AzDiagnosticSetting`
* `New-AzDiagnosticSetting`
    - [x] Apply same changes made to `Set`
* `Get-AzDiagnosticSettingsCategory`
    - [x] Rename `ResourceUri` to `ResourceId`
    - [x] Rename to `Get-AzDiagnosticSettingCategory`

### Others

* `Get-AzBaseline`
    - [x] (?) New command. Hide it?
* `Get-AzEventCategory`
    - [x] (?) New command. Hide it?
        * Not hide

### Missing Others

* `Get-AzAlertHistory`
* `Get-AzAutoscaleHistory`

### Missing in-memory objects creation cmdlets

* `New-AzActivityLogAlertCondition`
* `New-AzActionGroupReceiver`
* `New-AzMetricFilter`
* `New-AzMetricAlertRuleV2Criteria`
* `New-AzMetricAlertRuleV2DimensionSelection`
* `Add-AzWebtestAlertRule`
* `New-AzAlertRuleEmail`
* `New-AzAlertRuleWebhook`
* `New-AzAutoscaleNotification`
* `New-AzAutoscaleProfile`
* `New-AzAutoscaleRule`
* `New-AzAutoscaleWebhook`
* `New-AzScheduledQueryRuleAlertingAction`
* `New-AzScheduledQueryRuleAznsActionGroup`
* `New-AzScheduledQueryRuleLogMetricTrigger`
* `New-AzScheduledQueryRuleSchedule`
* `New-AzScheduledQueryRuleSource`
* `New-AzScheduledQueryRuleTriggerCondition`

------------------
### Estimated Cost:

**Comment by cormacpayne** [comment]
@niander please close this issue and open a new one outlining any remaining issues that need to be resolved in the generated `Az.Monitor` cmdlets.
