### ISSUE TITLE
Explanation of the -Force paramater for Remove-AzRecoveryServicesAsrReplicationProtectedItem is incorrect

### ISSUE THREAD

**Issue by arpparker** [Azure/azure-powershell#9411]
The explanation for the -Force parameter is incorrect in the documentation (both online and via PowerShell directly).  There is never an additional warning as the current explanation suggests.  

If the command is run without the -Force parameter, a job of type "DisableDr" is run that attempts to disable replication for the target protected item.  If the command is run with the -Force parameter, a job of type "PurgeVm" is run that removes the target protected item from the container/vault completely.   

The documentation for this cmdlet can be found here:
https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/remove-azrecoveryservicesasrreplicationprotecteditem?view=azps-2.2.0

**Comment by cormacpayne** [comment]
@viverm Hey Vipin, would you mind taking a look at this and confirming that the description of the `-Force` parameter represents the actual behavior of the cmdlet?

**Comment by Rajeswari-Mamilla** [comment]
@arpparker 
The expected behavior is to generate a warning when -Force parameter is not used. Can you please confirm if you have faced the same issue recently?

**Comment by arpparker** [comment]
> @arpparker
> The expected behavior is to generate a warning when -Force parameter is not used. Can you please confirm if you have faced the same issue recently?

That's definitely not what was happening.  If that is the intended behavior, then how is one supposed to distinguish between disabling replication (the "DisableDr" job that gets triggered) for an item and removing it completely from the vault (the "PurgeVM" job)?  Admittedly, the name of the commandlet definitely suggests the latter (removing the item from the vault), so perhaps there should be two commandlets--one for disabling replication for an item, another for removing the item from the vault completely.  

I haven't had to use this in any scripts recently, but can create a test case today or early next week to verify.  I'll report back.

**Comment by Sharmistha-Rai** [comment]
@arpparker - were you able to reproduce this error?

**Comment by Sharmistha-Rai** [comment]
We are working on improving the documentation for better understanding. Will update the thread once we have changed the doc.

**Comment by Sharmistha-Rai** [comment]
Please feel free to reopen for any additional queries.
