### ISSUE TITLE
Get-AzContainerInstanceLog -Wait parameter for log streaming

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#9417]
## Description of the new feature
Add parameter `-Wait` (similar to Get-Content) that will stream the logs of the container, it should implement the behavior of `az container attach`

**Comment by JustinGrote** [comment]
Implemented as Get-AzContainerInstanceLog -Tail

**Comment by markcowl** [comment]
@yangl900 @jluk Can you take a look?

**Comment by jluk** [comment]
@maertendMSFT and @edyoung are the new ACI owners, updating assignment to them.

**Comment by BethanyZhou** [comment]
Hi @JustinGrote , we have [Add-AzContainerInstanceOutput](https://docs.microsoft.com/powershell/module/az.containerinstance/add-azcontainerinstanceoutput) now. It is able to attach to the output stream of a specific container instance in a specified resource group and container group. Does this command satisfy your requirement?
