### ISSUE TITLE
Unable to load the file or assembly "Newtonsoft.Json" Version 9.0.0

### ISSUE THREAD

**Issue by t-irali** [Azure/azure-powershell#9418]
## Description
I am trying to write Powershell cmdlets for Azure DataBox Service. I have Newtonsoft.Json version 10.0.3 which is needed for DataBox management library. When I run the cmdlet which I created, I am getting an error stating "Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of
its dependencies. The system cannot find the file specified."  Although I am not using version 9 anywhere. Is it that the Azure Powershell module is dependent on a specific version of Newtonsoft.Json?

**Comment by markcowl** [comment]
I think you are trying to add a module to AzureRM, rather than Az, which is no longer in active development.

Please file a cmdlet review here:  https://github.com/azure/azure-powershell-cmdlet-review-pr/issues and let's have an onboarding meeting about your service.

**Comment by t-irali** [comment]
@markcowl The link given is not working. It says page not found

**Comment by t-irali** [comment]
I think the problem was that I was running the cmdlet on Windows Powershell rather than on Powershell Core. It works percfectly fine on Powershell Core 6.0
