### ISSUE TITLE
Set-AzureRmVMBootDiagnostics is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by akrytus** [Azure/azure-powershell#9424]
I am getting this error from the Azure portal CloudShell.   I have used this command in the past but today it doesnt work.  I have tried it in different subscriptions and directories with no avail.

**Comment by akrytus** [comment]
I also tried installing the AzureRM.Compute module but that didnt help either.

**Comment by markcowl** [comment]
Yes, this is an issue with the `Enable-AzureRmAlias` automatic aliases. It is fixed in the version about to be released.

Meanwhile, you can fix the issue by running: 

``` powershell
Set-Alias -Name Set-AzureRmVMBootDiagnostics -Value Set-AzVMBootDiagnostic -Force 
```

or by running `Set-AzVmBootDiagostic` with the same parameters you are used to using.
