### ISSUE TITLE
Can't install PowerShell Az -  Cannot convert value "2.0.0-preview" Windows 10

### ISSUE THREAD

**Issue by ucphger** [Azure/azure-powershell#9430]
I updated PowerShellGet "Install-Module -Name PowerShellGet -Repository PSGallery -Force" but still can't install Module AZ. Any idea?

PackageManagement\Install-Package : Cannot convert value "2.0.0-preview" to type "System.Version". Error: "Input string was not in a correct format."
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation,New-PSGetItemInfo,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by ToMakeSense** [comment]
You should install the latest version of PowerShellGet, but from the log, you didn't install it succuessfully.

The latest version is **2.1.4**, however yours was still **1.0.0.1** when you were installing Az module.

``` powershell
 PS C:\WINDOWS\system32> Find-Module PowerShellGet -IncludeDependencies 
 
 Version              Name                                Repository           Description  
 -------              ----                                ----------           -----------  
 2.1.4                PowerShellGet                       PSGallery            PowerShell...
 1.4                  PackageManagement                   PSGallery            PackageMan...
```

**Comment by cormacpayne** [comment]
Kevin (@ToMakeSense) is correct -- you will need the latest version of `PowerShellGet` (or at least version 1.6.0) to resolve this issue. Running `Install-Module -Name PowerShellGet -Repository PSGallery -Force` should install the latest version of this module for you.

For more information on why this error is occurring, please see [this comment](https://github.com/Azure/azure-powershell/issues/9170#issuecomment-491038137).
