### ISSUE TITLE
Issue with Set-AzDataFactoryV2Dataset and Data Lake Gen2 datasets

### ISSUE THREAD

**Issue by DBojsen** [Azure/azure-powershell#9436]
I know I should be switching to the Az commands instead, but I have validated that the issue exists with those as well.

With some dataset types for ADL Gen2, the Set-AzDataFactoryV2Dataset cmdlet returns succes, and the datasets are also populated, but do not show up in the ADF UI.
However, if I view the network traffic with Google Chrome developer tools, I can see that they are added to the list of datasets.

I had to switch to the REST api instead, which deploys fine.
I created this function to (temporarily) take over for the malfunctioning cmdlet:

```
function Set-AzureRmDataFactoryV2DatasetKPI {
    param (
        [Parameter(mandatory=$true)][string]$ResourceGroupName, $DataFactoryName, $Name, $DefinitionFile
    )

    $request = "https://management.azure.com/subscriptions/${SubscriptionID}/resourceGroups/${ResourceGroupName}/providers/Microsoft.DataFactory/factories/${DataFactoryName}/datasets/${Name}?api-version=2018-06-01"
    $body = Get-Content -Encoding UTF8 -Path $DefinitionFile

    $response = Invoke-RestMethod -Method PUT -Uri $request -Header $authHeader -Body $body -ContentType "application/json; charset=utf-8"
    return ($response | ConvertTo-Json)
}
```

Please make sure it's fixed, and also make sure that the cmdlet doesn't report succes when there is an issue.

BR David

**Comment by cormacpayne** [comment]
@hvermis Hey Hermine, would you mind taking a look at this issue?
