### ISSUE TITLE
Create a cmdlet to make a generic call to REST API (Invoke-AzRestMethod)

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#9440]
## Description of the new feature
Create a cmdlet to be able to make a generic call to Azure REST API. 
This would enable operations on resources for which a module does not exist yet.

Similar issues are: 
#2200
#3806

**Comment by dcaro** [comment]
Adding #7752 to the list.

**Comment by dingmeng-xue** [comment]
In #10847, user is using PowerShell scripts as well.

**Comment by kilasuit** [comment]
Technically this already exists via Invoke-AzResourceAction

**Comment by VidyaKukke** [comment]
> Technically this already exists via Invoke-AzResourceAction

can you give examples of using it for generic rest?

**Comment by dcaro** [comment]
@kilasuit the `Invoke-AzResourceAction` is made to invoke actions on Azure resources. This cmdlet allows invoking a REST calls to Aure providing the full path and API version.
It will be useful in the case a cmdlet does not exist yet to create Azure resources or when you want to use a different API version that the one implemented in the module. 

@VidyaKukke, please have a look at the pending PR for the time being. The examples will be published as we make the cmdlet available.
