### ISSUE TITLE
Username/password authentication should be supported

### ISSUE THREAD

**Issue by Borkason** [Azure/azure-powershell#9445]
As I understand, I cannot use Connect-AzAccount with username and password. Instead I have to use device authentication. But leaving the console session to browser to a web page to enter a code is not very user friendly. I very much prefer to enter my credentials in the terminal, preferably via a credentials object (Get-Credential).

**Comment by cormacpayne** [comment]
@Borkason Hey Daniel, previously we removed U/P authentication from the new `Az` module for reasons [outlined here](https://github.com/Azure/azure-powershell/issues/7430#issuecomment-426480499), but after discussion with the community (same issue linked previously) and internally, we were able to bring back U/P authentication for _Windows PowerShell only_. PowerShell Core users will need to _temporarily_ use device code login, but in the near future, we will be moving to a new authentication library which will support a new interactive login through the browser, as well as U/P authentication.

We have released a preview of the `Az.Accounts` module ([release found here](https://github.com/Azure/azure-powershell/releases/tag/Az.Accounts-v2.0.0-preview)) that exposes this functionality (as well as single sign-on support) if you'd like to use it before it officially GA's later this year.

However, as mentioned in the GitHub issue and the release, we brought back the U/P support for CSP users _only_, and authentication for automation purposes should use service principal authentication instead.

Please let me know if you have any other questions or concerns! 😀

**Comment by Borkason** [comment]
> PowerShell Core users will need to temporarily ... in the near future ... U/P authentication

All I needed to hear :) Great response. Thanks.
