### ISSUE TITLE
Improve 'Az module bug report' template

### ISSUE THREAD

**Issue by spaelling** [Azure/azure-powershell#9452]
## Description

Below I pasted some of the "tricks" I use when filing bug reports. That would make some of the more tedious tasks, well, less tedious >D

## Steps to reproduce

N/A

## Environment data

```
$PSVersionTable | clip
```

## Module versions

```powershell
Get-Module  -ListAvailable | clip
```

## Debug output

```
# redirects debug stream to success stream which we can put into clipboard
<Azure Command> 5>&1 | clip
```

## Error output

```
Resolve-AzError | clip
```

**Comment by markcowl** [comment]
These files are in: https://github.com/Azure/azure-powershell/tree/master/.github/ISSUE_TEMPLATE  Please feel free to create a PR with these changes (this way you will show up as the committer)
