### ISSUE TITLE
Increase the amount of data that Invoke-AzureRmVMRunCommand can return

### ISSUE THREAD

**Issue by MrDRamos** [Azure/azure-powershell#9456]
The Invoke-AzureRmVMRunCommand currently has a 4K limit on the returned payload.
I frequently need to return logs and listings that exceed the 4K limitation!

**Comment by cormacpayne** [comment]
@koralski @savyasachisamal would you mind taking a look at this issue?

**Comment by Drewm3** [comment]
First, thank you for reaching out to the Microsoft team.  We identified your issue as a Virtual Machine feature request.  We don't have that feature, but we are interested in hearing more from you and others.  We have created a UserVoice idea here [https://feedback.azure.com/forums/216843-virtual-machines/suggestions/38180833-increase-the-amount-of-data-that-vm-run-command-ca](url) for you to provide more feedback and upvote this feature to become a high priority for our feature teams roadmap planning.

**Comment by MrDRamos** [comment]
The link you provided doesn't seem to go to a place for making comments... i get (No results matched your search.) 
So let me provide a simple example that exceeds 4K of returned data: 
    **$result_json = Get-Process | ConvertTo-Json  <- This will generate over 1 MB of data**
A simple workaround is to to store the results in blob storage and then have the calling process read the blob. We started wrapping the Invoker to do that in some of scripts, but why cant the Invoke_AzureRmVMRunCommand() do that for us in one clean call ?

**Comment by Drewm3** [comment]
Here is the correct link: https://feedback.azure.com/forums/216843-virtual-machines/suggestions/38180833-increase-the-amount-of-data-that-vm-run-command-ca
