### ISSUE TITLE
Version Number Incorrect

### ISSUE THREAD

**Issue by pauliandraper** [Azure/azure-powershell#9491]
I believe the version numbers within the AzureRM version list dropdown, within the documentation, are incorrect. It says '5.7.0', but I believe based on the list available in DevOps (and by running 'get-module -listavailable' in an inline Azure Powershell task) this should be 6.7.0.

**Comment by cormacpayne** [comment]
@pauliandraper Hey Paul, I believe that for the AzureRM version dropdown list, we are keeping track of the last version in the previous three major releases (6.13.0, 5.7.0 and 4.4.1) and then a few versions for specific Stack releases (2.5.0, 2.4.0 and 2.3.0), so the versions are correct if they are following that pattern. I'm going to close this issue as the versions seem to be matching what we expect, but please let me know if this isn't the case.
