### ISSUE TITLE
Errors occurring on all commands

### ISSUE THREAD

**Issue by CMircea** [Azure/azure-powershell#95]
Executing any command results in this generic error message:

    An error occurred while sending the request.

Previous discussion:
https://github.com/Azure/azure-sdk-tools/issues/2409

**Comment by pcgeek86** [comment]
This can happen if you have no Internet connection, or a poor Internet connection. I agree that the message is very confusing. Can you verify that DNS is working okay, and you can access the Azure Service Management REST API via different means (eg. simply using `Invoke-WebRequest`)? You don't necessarily need to make a successful / authenticated API call, but make sure you at least receive a valid error from the service.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by CMircea** [comment]
Hello,

Yes, I was able to access the service management API. In fact, the Azure intergration in VS was working fine, just PowerShell was failing. What's more, it appears to have fixed itself a week ago :/

**Comment by matt-gibbs** [comment]
@CMircea  Closing this for now. If you or @pcgeek86 see it again, please re-open and we'll have you grab some log data to see if we can identify the problem.
