### ISSUE TITLE
Set-AzureSubscription - Incorrectly sending success code

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [Azure/azure-powershell#9527]
Set-AzureSubscription is returning a success code however it does not actually change the context. In the attached screenshot you'll see:

1. A request switching to Subscription ID '9248'
2. A success response from ASM
3. Get-AzureSubscription shows '9248' is not actually the selected context
![SetSubscriptionFail](https://user-images.githubusercontent.com/28310425/60377379-605fe000-99e4-11e9-8d58-ba7832e2e2c0.png)

Running last Azure ASM PowerShell module 5.3.0

Set-AzureSubscription is superceded by Select-AzureSubscription... therefore I request the ASM service would send a failure code whenever 'Set-AzureSubscription' is used... or... remove the cmdlet in the next Azure powershell update (even though it hasn't been updated in 1+ years).

**Comment by markcowl** [comment]
`Set-AzureSubscription` is not meant to choose a subscription, it is meant to change subscription properties.

Cloaing as `by design`
