### ISSUE TITLE
New-AzureRmAutomationWebhook - Invalid expiry time

### ISSUE THREAD

**Issue by omerzubair** [Azure/azure-powershell#9529]
## Description

$expiryDate =  (Get-Date).AddYears(50)
$dateFormat = "dd/mm/yyyy"
$WebhookAdded = New-AzureRmAutomationWebhook -Name $WebhookName -Parameters $Params -IsEnabled $True -ExpiryTime ($expiryDate.ToString($dateFormat)) -RunbookName $runBookName -ResourceGroup $rg -AutomationAccountName $AutomationAccountName -Confirm:$false -Debug  -Force

When you supply the -ExpiryTime  as per docs "1/12/2030" it gives the following error:

New-AzureRmAutomationWebhook : Invalid expiry time

## Steps to reproduce
also apples to New-AzAutomationWebhook 

so fix is to supply the complete with Time

$UTCNow = [Datetime]::UtcNow
$UTCNow.AddYears(10) i.e 2029-07-01T02:14:46.059803+10:00

$WebhookAdded = New-AzureRmAutomationWebhook -Name $WebhookName -Parameters $Params -IsEnabled $True -ExpiryTime ($UTCNow.AddYears(10)) -RunbookName $runBookName -ResourceGroup $rg -AutomationAccountName $AutomationAccountName -Confirm:$false -Debug  -Force

so please update documentation  :(
https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/new-azurermautomationwebhook?view=azurermps-6.13.0 

```powershell

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

New-AzureRmAutomationWebhook : Invalid expiry time.
At line:1 char:17
+ ... hookAdded = New-AzureRmAutomationWebhook -Name $WebhookName -Paramete ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzAutomationWebhook], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.NewAzureAutomationWebhook

```

```

**Comment by omerzubair** [comment]
needs a documentation update https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/new-azurermautomationwebhook?view=azurermps-6.13.0 
took me a whole day to figure out. hope this saves time for someone else

**Comment by markcowl** [comment]
Looks like the fix is also needed here: https://docs.microsoft.com/en-us/powershell/module/az.automation/New-AzAutomationWebhook?view=azps-2.3.2

**Comment by omerzubair** [comment]
> Looks like the fix is also needed here: https://docs.microsoft.com/en-us/powershell/module/az.automation/New-AzAutomationWebhook?view=azps-2.3.2

Absolutely correct , thanks for highlighting it @markcowl .  i mentioned it above but its not clear .

**Comment by omerzubair** [comment]
Hi Team , so i made to work and everything was working fine for past 2 days and suddenly now i am getting the following error
New-AzureRmAutomationWebhook : Runbook mandatory parameter not specified. Parameter name validationPassed.

**Comment by omerzubair** [comment]
OK Figured it out. The interface changed with a new mandatory parameter is required!

so use the following 

$Params = @{"WEBHOOKDATA"="";"VALIDATIONPASSED"=""}

 New-AzureRmAutomationWebhook -Name $WebhookName -Parameters $Params -IsEnabled $True -ExpiryTime $expiryTime -RunbookName $runBookName -ResourceGroup $automationResourceGroup -AutomationAccountName $automationAccountName -Force

**Comment by omerzubair** [comment]
Hi @markcowl any update?
Cheers

**Comment by andyw248** [comment]
Vikram, Jeff - please assign.

**Comment by thomasyip-msft** [comment]
Tested with String type date/time and it is working. What it is not working is if number of years exceed 10 years.

For example:
New-AzAutomationWebhook -Name test_webhook3 -ResourceGroupName test-AutomationAccountName test-RunbookName testrunbook -ExpiryTime "12/1/2029" -IsEnabled $true
works but 
New-AzAutomationWebhook -Name test_webhook3 -ResourceGroupName test-AutomationAccountName test-RunbookName testrunbook -ExpiryTime "12/1/2030" -IsEnabled $true
doesn't.

![image](https://user-images.githubusercontent.com/16672845/71852402-7afacc00-308d-11ea-8b37-e9f318f61e8a.png)

shows actual validation done and returned from the backend.

For clarification we can document this 10 years limit.

**Comment by vikram-m** [comment]
Product team is not working actively on AzRm modules and would not be supported from Dec31, 2020. Please use the Az modules.
