### ISSUE TITLE
Get-AzRecoveryServicesVaultSettingsFile + Start-OBRegistration = Vault credentials file provided has expired

### ISSUE THREAD

**Issue by Wand3rvogel** [Azure/azure-powershell#9533]
## Description

With workaround from [hier](https://github.com/Azure/azure-powershell/issues/8885#issuecomment-480851137) I can create VaultCredentials-file.

But Start-OBRegistration gives error:
Start-OBRegistration : Vault credentials file provided has expired. We recommend you download a new vault credentials file from the portal and use it within 2 days.
FullyQualifiedErrorId : CBPUserExpiredVaultCredential,Microsoft.Internal.CloudBackup.Commands.StartCBREgistrationCommand

When I save VaultCredentials-File from Azure Portal, a difference is only ManagementCert Value.

## Steps to reproduce

```powershell

function Get-VaultCredentialsFile ( [string]$FilePath ) {

    $dt = (Get-Date).ToString("M-d-yyyy")
    $subid = (Get-AzSubscription).Id

    $cert = New-SelfSignedCertificate -DnsName $($vault.Name + $subid + '-' + $dt +'-vaultcredentials') -CertStoreLocation Cert:\CurrentUser\My -NotAfter (Get-Date).AddHours(8)
    $certficate = [Convert]::ToBase64String($cert.RawData)

    $CredsFile = Get-AzRecoveryServicesVaultSettingsFile -Backup -Vault $vault -Path $FilePath -Certificate $certficate.ToString()

    $cert | Remove-Item

    return $CredsFile.FilePath
}

$vaultCredsFilePath = Get-VaultCredentialsFile -FilePath "C:\Temp"
Start-OBRegistration -VaultCredentials $vaultCredsFilePath -Confirm:$false
```

## Environment data

```
PSVersion                      5.1.14393.2969
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2969
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
Az.Accounts - 1.5.3
Az.RecoveryServices - 1.4.1
MSOnlineBackup - 2.0.0.0
```

**Comment by Wand3rvogel** [comment]
`[Microsoft.Internal.CloudBackup.Client.Common.CBClientCommon]::GetCBVaultCredExpiryFromVaultCredential("file from portal").ToString("yyyy-MM-dd")
`

2019-07-05

`[Microsoft.Internal.CloudBackup.Client.Common.CBClientCommon]::GetCBVaultCredExpiryFromVaultCredential("file from cmdlet")`

Exception "Microsoft.Internal.EnterpriseStorage.Dls.Utils.DlsException"

**Comment by Wand3rvogel** [comment]
CBEngineCurr.errlog:

> Management Certificate from Vault credentials is Invalid. Error Details = The certificate does not have a private key with a valid exchange algorithm.

**Comment by Wand3rvogel** [comment]
``` Powershell
$token = (az account get-access-token | ConvertFrom-Json).accessToken
$headers = @{ "Authorization" = "Bearer " + $token }

$vaultCreds = Invoke-RestMethod -Method Get -Uri "https://main.recoveryservices.ext.azure.com/api/subscriptions/$subId/resourceGroups/$rgName/providers/Microsoft.RecoveryServices/vaults/$vaultname/downloadVaultCreds?credstype=backup" -Headers $headers
$vaultCreds.Save("C:\Temp\Test.VaultCredentials")

Import-Module MSOnlineBackup
[Microsoft.Internal.CloudBackup.Client.Common.CBClientCommon]::GetCBVaultCredExpiryFromVaultCredential("C:\Temp\Test.VaultCredentials").ToString("yyyy-MM-dd")

```

> 2019-07-07

CBEngineCurr.errlog:

> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS700027: Client assertion contains an invalid signature. [Reason - The key was not found., Thumbprint of key used by client: '66A8...', Please visit 'https://developer.microsoft.com/....']

Not working...

**Comment by pvrk** [comment]
@viverm : can you please provide an update here?

**Comment by tsunami28** [comment]
Start-OBRegistration -VaultCredentials $CredsFilename.FilePath -Confirm:$false
Still returns error:
Start-OBRegistration : Unable to read the vault credentials file provided. Please download a new vault credentials file and try again.
Does anyone have a solution to this?

**Comment by pvrk** [comment]
@viverm : Can you please take a look?

**Comment by ecurti** [comment]
> Start-OBRegistration -VaultCredentials $CredsFilename.FilePath -Confirm:$false
> Still returns error:
> Start-OBRegistration : Unable to read the vault credentials file provided. Please download a new vault credentials file and try again.
> Does anyone have a solution to this?

Same problem... any solution? Thanks.

**Comment by heldchen** [comment]
same here on a fresh Windows Server 1910 instance.
```
$Credential = Get-Credential
Connect-AzAccount -Credential $Credential

Register-AzResourceProvider -ProviderNamespace "Microsoft.RecoveryServices"
New-AzResourceGroup –Name "rg1" –Location "West Europe" -Force
New-AzRecoveryServicesVault -Name "Backups" -ResourceGroupName "rg1" -Location "West Europe"
$Vault = Get-AzRecoveryServicesVault –Name "Backups"
Set-AzRecoveryServicesBackupProperty -Vault $Vault -BackupStorageRedundancy GeoRedundant

$dlPath = 'Downloads\MARSAgentInstaller.EXE'
Invoke-WebRequest 'https://aka.ms/Azurebackup_Agent' -OutFile $dlPath
Downloads\MARSAgentInstaller.EXE /q /m

$CredsPath = 'C:\Azure\'
New-Item -ItemType Directory -Force -Path $CredsPath
$cert = New-SelfSignedCertificate -CertStoreLocation cert:\localmachine\my -dnsname machine1
$certificate =[System.Convert]::ToBase64String($cert.RawData)
$CredsFilename = Get-AzRecoveryServicesVaultSettingsFile -Certificate $certificate -Vault $vault -Backup -Path $CredsPath
Import-Module -Name 'C:\Program Files\Microsoft Azure Recovery Services Agent\bin\Modules\MSOnlineBackup'
Start-OBRegistration -VaultCredentials $CredsFilename.FilePath -Confirm:$false
```
```
WARNING: Vault credentials validation failed.
Start-OBRegistration : Vault credentials file provided has expired. We recommend you download a new vault credentials file from the portal and use it within 2 days.
At line:1 char:1
+ Start-OBRegistration -VaultCredentials $CredsFilename.FilePath -Confi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-OBRegistration], DlsException
    + FullyQualifiedErrorId : CBPUserExpiredVaultCredential,Microsoft.Internal.CloudBackup.Commands.StartCBRegistrationCommand
```

**Comment by ecurti** [comment]
This a a known issue.
I've tried this workaround and it works!

> I had a number of issues with automating the install of the mars agent. After a lot of troubleshooting I found I had to generate a certificate with a private key, request the vault credentials and then update the vault credentials xml with the certificate including the private key, I have an example of a automated install here
> https://github.com/timleyden/marsdemo/blob/master/InstallMARS.ps1. I also raised a github issue to have the docs updated.

**Comment by pvrk** [comment]
We have fixed the issue with the vault certificate and updated the documentation.

https://docs.microsoft.com/azure/backup/backup-client-automation#registering-using-the-ps-az-module

**Comment by pvrk** [comment]
Will close this issue since the fix was provided. Can re-open if the issue persists.
