### ISSUE TITLE
New-AzPrivateDnsVirtualNetworkLink - fails second time around

### ISSUE THREAD

**Issue by lukeb1961** [Azure/azure-powershell#9537]
## Description
If I create a new RG, a new VNET and then 
New-AzPrivateDnsZone and New-AzPrivateDnsVirtualNetworkLink it all works fine.
However if I delete the RG completely and later rerun the exact same script, it fails, 
despite Get-AzPrivateDnsVirtualNetworkLink returning nothing

    $MelPrivateVnet = Get-azVirtualNetwork -Name $VnetMelPrivate -ResourceGroupName $RG 

    $link = New-AzPrivateDnsVirtualNetworkLink -ZoneName $PrivateZoneName `
                                               -ResourceGroupName $RG `
                                               -Name 'MelPrivateLink' `
                                               -VirtualNetworkId $MelPrivateVnet.id `
                                               -EnableRegistration

Body:
{
  "error": {
    "code": "Conflict",
    "message": "Virtual network resource identity '/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourceGroup
s/LukeBrennan-AZ-RG/providers/Microsoft.Network/virtualNetworks/Melbourne-PRIVATE-vnet' already in use. This is possible in case the virtual network was moved, or re-created. Please contact support."
  },
  "status": "Failed"
}

New-AzPrivateDnsVirtualNetworkLink : Long running operation failed with status 'Failed'. Additional Info:'Virtual 
network resource identity '/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourceGroups/LukeBrennan-AZ-RG/pro
viders/Microsoft.Network/virtualNetworks/Melbourne-PRIVATE-vnet' already in use. This is possible in case the 
virtual network was moved, or re-created. Please contact support.'
At line:855 char:13
+     $link = New-AzPrivateDnsVirtualNetworkLink -ZoneName $PrivateZone ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzPrivateDnsVirtualNetworkLink], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.PrivateDns.VirtualNetworkLinks.NewAzurePrivateDnsVirtualNet 
   workLink

 (get-module -Name Az.PrivateDns).Version
Major  Minor  Build  Revision
-----  -----  -----  --------
0      1      1      -1   

(get-module -Name Az).Version
Major  Minor  Build  Revision
-----  -----  -----  --------
2      3      2      -1    

$PSversiontable
Name                           Value                                                                       
----                               -----                                                                       
PSVersion                      5.1.18362.145                                                               
PSEdition                      Desktop                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                     
BuildVersion                   10.0.18362.145                                                              
CLRVersion                     4.0.30319.42000                                                             
WSManStackVersion              3.0                                                                         
PSRemotingProtocolVersion      2.3                                                                         
SerializationVersion           1.1.0.1 

Is this being cached for days? 
Is it  failure to cleanup when the RG was deleted?
Is it a bug in the cmdlet?

**Comment by markcowl** [comment]
@lukeb1961 The message indicates that recreating the VNet can cause this issue, have you contacted Azure support about this?

**Comment by lukeb1961** [comment]
Thanks Mark. Will chase with Azure support.

**Comment by lukeb1961** [comment]
OK. PM responded:
This is a known bug and will be fixed in a few weeks. Please see
https://docs.microsoft.com/en-us/azure/dns/private-dns-overview#known-issues

**Comment by WYarde** [comment]
I'm facing the same issue.. I've tried waiting for several days, but still no luck.
@lukeb1961 Your link is no longer working unfortunately. Do you have any more detail on this?

**Comment by andreasanderssoncab** [comment]
Having the same issue
