### ISSUE TITLE
New-AzPolicyDefinition / New-AzPolicyAssignment only support Management Group Name not Id

### ISSUE THREAD

**Issue by fawohlsc** [Azure/azure-powershell#9538]
## Description of the new feature
Management group names can be the same, i.e. like many different _Production_ management groups under business unit / region management groups. Only the ID is enforced to be unique. 

## Proposed implementation details (optional)
Following the New-AzPolicyDefinition /  New-AzPolicyAssignment cmdlets should support not only assignment via the parameter -ManagementGroupName, but also -ManagementGroupId.

**Comment by mentat9** [comment]
Management Group API does not have a unique ID for management groups. The ID field of the management group is just the name, prefixed with /providers/Microsoft.Management/managementGroups/. What you are asking for doesn't exist.

**Comment by fawohlsc** [comment]
@mentat9 . Thanks for coming back. The /providers/Microsoft.Management/managementGroups/ uses the Management Group ID not the Name. That's why naming the parameter -ManagementGroupName is confusing.

**Comment by mentat9** [comment]
Not sure whether we're saying the same thing. Here's what I'm saying:

```
[C:\PS]-> Get-AzManagementGroup


Id          : /providers/Microsoft.Management/managementGroups/AzGovTest7
Type        : /providers/Microsoft.Management/managementGroups
Name        : AzGovTest7
TenantId    : 72f988bf-86f1-41af-91ab-2d7cd011db47
DisplayName : AzGovTestMG no subscription

Id          : /providers/Microsoft.Management/managementGroups/AzGovLiveTest
Type        : /providers/Microsoft.Management/managementGroups
Name        : AzGovLiveTest
TenantId    : 72f988bf-86f1-41af-91ab-2d7cd011db47
DisplayName : GovernanceLiveTest

Id          : /providers/Microsoft.Management/managementGroups/AzGovTest5
Type        : /providers/Microsoft.Management/managementGroups
Name        : AzGovTest5
TenantId    : 72f988bf-86f1-41af-91ab-2d7cd011db47
DisplayName : Azure Policy



[C:\PS]->
```
The confusion originates from the MG nomenclature. When creating an MG you give "GroupName" (e.g. AzGovTest5), which is allowed to be non-unique. The MG provider doesn't create any kind of unique ID. The "ID" property is just the fully qualified [non-unique] GroupName that was provided at create time (/providers/Microsoft.Management/managementGroups/AzGovTest5). This isn't really an ID (since it isn't unique), it's still just the fully qualified name. Consequently, there really is no benefit to adding a ManagementGroupId parameter: just use the Name property of the MG instead of the ID property. They are effectively the same thing.

**Comment by fawohlsc** [comment]
@mentat9 . Thanks for coming back to me. Actually that is not entirely correct. The name of different management groups can be the same (see screenshot "production"), but the id must be unique. Following it would be better to rename the parameter to -ManagementGroupId. Try it out, actually the ManagementGroupName parameter looks into the ManagementGroupId.

![image](https://user-images.githubusercontent.com/41372128/61000918-c3476480-a35e-11e9-806f-3466e6f01404.png)

**Comment by mentat9** [comment]
Unfortunately, what you are seeing there is additional confusing nomenclature. Uniqueness is being enforced through portal sleight-of-hand, not by a separate ID field at the backend. When the user exits the "ID" field, the portal queries for an existing MG that has a "Name" the same as what they entered into the "ID" field. If one already exists, the error message is printed, and the Save button remains disabled. You can verify this yourself by creating an MG with a given ID. Then use Powershell to display the MG properties. You will see that your new MG has a Name field matching what you entered for ID. There is only Name, not ID, despite what you see in the portal. I know the current situation is confusing between the portal and Powershell, but adding more parameters to Powershell cmdlets will only make things worse. The inconsistency is already baked into MGs and their clients.

**Comment by fawohlsc** [comment]
@mentat9 Thanks for your clarification. This makes a lot of sense. Basically it's inconsistency in the portal. Following I absolutely agree that adding more parameters to Powershell cmdlets will only make things worse. All good for now and many thanks again. Happy weekend!
