### ISSUE TITLE
Customizable location for '.azure' directory

### ISSUE THREAD

**Issue by EPinci** [Azure/azure-powershell#9541]
## Description of the new feature

Currently, on Windows, the autocontext save directory is bound to %USERPROFILE%\.azure.
It would be helpfull, when working with many different customers, to allow this to be changed.

## Proposed implementation details (optional)

Most of the linux similar contexts get saved in the %HOME% folder and it would be nice if Window could honor, if defined, this variable as an override of %USERPROFILE%.
Manually being able to change that directory with the Enable-AutoContextSave command would also be fine.

**Comment by markcowl** [comment]
@EPinci The intention is to have a single database of contexts that you can use cmdlets to select from.  Is this ask about making it easier to select between you customer contexts, about storing securie information in a directory of your choosing, or something else?

**Comment by markcowl** [comment]
Closing for lack of response.  Please feel free to open a new issue and clarify as requested
