### ISSUE TITLE
Set-AzureRmContext : Please provide a valid tenant or a valid subscription

### ISSUE THREAD

**Issue by harshitha-bt** [Azure/azure-powershell#9550]
Hi,

I have a powershell script using AzureRm module 6.3.1 and Set-AzureRmContext consistently fails with "Please provide valid tenant or subscription" even though the subscription is valid and i have access to that subscription.
Debug logs for the command run on powershell ISE (5.1.18362.145) is attached. The same issue arises even if i use Az module instead of AzureRm. Could you please suggest the steps to debug?
[DEBUG_logs.pdf](https://github.com/Azure/azure-powershell/files/3353567/DEBUG_logs.pdf)

**Comment by markcowl** [comment]
@harshitha-bt `Set-AzContext` actually changes the current context, ratehr than selecting a new one.  The error below indicates that you haven't previously logged in to the tenant you are trying to access, which usually means you are trying to select a new tenant and a subscription in that tenant.

If you are trying to access a different tenant, you can use connect-azaccount -Tnenat <tenantId> -Subscription <subscriptionIdOrName> to login and add that to your contexts, you cna then use `Select-AzContext to tab between the existing contexts and choose the one that has the subscription you want to use.

**Comment by markcowl** [comment]
@harshitha-bt If this isn't the problem you are trying to solve, please provide the other information requested in the issue template:

- PowerShell version (`$PSVersionTable`)
- Module versions (`Get-Module -ListAvailable`)
- cmdlet execution parameters

**Comment by harshitha-bt** [comment]
@markcowl, My issue was resolved when i used elevated privileges, as the subscriptions i was working on needed elevated access. Thanks for looking into it. Closing this issue
