### ISSUE TITLE
Help not getting updated even after modifying .md files

### ISSUE THREAD

**Issue by t-irali** [Azure/azure-powershell#9553]
I have generated the help .md files for each of the cmdlets using the platyPS module by following the instructions given. Now even after I modify the .md files to update the help, the help is not getting reflected in the Get-Help cmdlet for any of the cmdlets.

**Comment by cormacpayne** [comment]
@t-irali Hey Irfan, this behavior is expected for local development -- when calling `Get-Help` for a given cmdlet, PowerShell looks for a `dll-Help.xml` file that contains all of the reference documentation for that cmdlet. If it cannot find that file, then it creates generic help using the public interface of the cmdlet. The markdown files that you're creating are used during our sign/packaging job to create these `dll-Help.xml` files, which gives the users an accurate `Get-Help` result for the production cmdlets. [This function](https://github.com/Azure/azure-powershell/blob/master/tools/HelpGeneration/HelpGeneration.psm1#L269-L288) is what we use during this job to generate the `dll-Help.xml` files, so if you'd like to see what the result of `Get-Help` should look like during local development, then you can follow similar commands to what's in this function to generate this file and then import it into your `.psd1` file.
