### ISSUE TITLE
Confused about versions of AZ

### ISSUE THREAD

**Issue by glittle** [Azure/azure-powershell#9559]
These two sites:

[https://docs.microsoft.com/en-us/cli/azure/network/application-gateway?view=azure-cli-latest](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway?view=azure-cli-latest)

and 

https://docs.microsoft.com/en-us/powershell/module/az.network/?view=azps-2.4.0#application_gateway

both give instructions on how to manage, in this example, the Application Gateway.

Neither site seems to reference the other, and both seem to be current.  I understand that the AzureRM library is discontinued, which adds to the confusion as many tutorials use it.

What is the relationship between these two PowerShell libraries?

Which is the "correct" one to use?

**Comment by glittle** [comment]
As another example, here are the two ways to create an address pool:

https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/address-pool?view=azure-cli-latest#az-network-application-gateway-address-pool-create

https://docs.microsoft.com/en-ca/powershell/module/azurerm.network/New-AzureRmApplicationGatewayBackendAddressPool?view=azurermps-6.13.0

Totally different commands.  Tutorial pages around Microsoft seem to use one or the other approach.

**Comment by markcowl** [comment]
`Az`, the current Azure PowerShell module, which runs cross-platform is not discontinued.  

`AzureRM`, the old version of Azure PowerShell that worked only on Windows, *is* dicontinued, and was replaced by `Az`.

`Az` is azure PowerShell - PowerShell cmdlets for Azure.  azure cli is the bash commands for Azure.  Both are correct. You can use whichever you are more comfortable with.
