### ISSUE TITLE
Change IP adress of firewall rule in Azure Analysis Services

### ISSUE THREAD

**Issue by mathwro** [Azure/azure-powershell#9566]
## Description of the new feature
A way to either remove an existing Analysis Services firewall rule and create a new (in the same way an NSG works using the "Remove-AzNetworkSecurityRuleConfig"), or a way to simply update the rule directly, using the Azure Powershell module

**Comment by markcowl** [comment]
@solankisamir Can you take  alook?

**Comment by solankisamir** [comment]
@markcowl I am not from Azure Analysis Service. I can take feature request for Api Management

**Comment by mathwro** [comment]
Just read through my post and realised it might not be super clear as to what im requesting,

With the current available cmdlets for the Analysis service, it's not possible to delete a specific rule or modify a rule.

the NSG cmdlets seems fairly close in nature in regards to how it works programmatically, which is why i used that as an example.

I got around not being able to modify a specific rule on the NSG because it's able to delete a specific rule and then recreate the rule with the updated info, where the analysis services is only able to delete the entire firewall config.

I would like to either delete a specific rule or modify a rule in the analysis service firewall.

**Comment by christianwade** [comment]
Hi mathwro, can you please describe the automation scenario you have in mind?

**Comment by mathwro** [comment]
@christianwade I'm using a runbook to automatically invoke the processing of the cube. Since the analysis server don't have the feature to allow other azure resources to run in the firewall, i had to automate a check for a change in the IP, in which Azure is invoking the runbook from. 

So my script currently takes the IP azure is running the runbook from, checking the analysis server's firewall if the IP's are matching, if not it's updating the configuration.

**Comment by mathwro** [comment]
Yes. I'm looking to update a specific rule instead of the entire configuration

**Comment by neilp-snow** [comment]
@christianwade Surely that's no different in behavior to the "allow access from azure services" that Microsoft recommends using for granting AAS access to SQL Azure? 

It's a bit of a pain point setting up access from AzureDevOps that we could add firewall rules using powershell for our build agent, but cannot remove them at the end of the deployment.

**Comment by vpaluch** [comment]
Any update on this? it's a pain removing the rule after the data refresh.

**Comment by mathwro** [comment]
For those running into the same problem of missing the "Allow access from azure services"

I've created a runbook script that can be used to automatically process the analysis server.
Automatically gets the IP the runbook is running from and updates the firewall accordingly.
https://github.com/mathwro/Scripts/blob/master/Azure/AllowAzure-AnalysisServer.ps1

**Comment by navba-MSFT** [comment]
@mathwro Apologies for the late reply. Could you please check if the below snippet helps to achieve your requirement ?

>$myRule = New-AzAnalysisServicesFirewallRule -FirewallRuleName $myFirewallRuleName -RangeStart $myIp 
                     -RangeEnd $myIp
$currentFirewallConfig.FirewallRules.Add($myRule)
Set-AzAnalysisServicesServer -ResourceGroupName $resource[1] -Name $resource[2] -FirewallConfig $currentFirewallConfig -PassThru

More Info [here](https://docs.microsoft.com/en-us/powershell/module/az.analysisservices/set-azanalysisservicesserver?view=azps-7.3.0). This issue is open for quite sometime. Could you please check and let us know if you still need any assistance on this ? Awaiting your reply.
