### ISSUE TITLE
Get-AzureWebApp (and Get-AzureRMWebApp) requires the name.  It should not.  Also, it does not support piping in the Resource Group.

### ISSUE THREAD

**Issue by mohitsriv** [Azure/azure-powershell#957]
PS C:\Users\mohisri> Get-AzureRMResourceGroup | Get-AzureRMWebApp

cmdlet Get-AzureRMWebApp at command pipeline position 2
Supply values for the following parameters:
(Type !? for Help.)
ResourceGroupName:
Name:

Also, why does it prompt for Name?  Shouldn’t it just enumerate all Web Apps in the Resource Group?

**Comment by adam-knights** [comment]
Currently I see no way to loop through all web apps in a resource group without this change?

**Comment by davidebbo** [comment]
For now, you can do this using the low level `Get-AzureResource`. e.g.

    Get-AzureResource -ResourceGroupName YourRGName -ResourceType Microsoft.Web/sites -isCollection -OutputObjectFormat New -ApiVersion 2015-08-01

**Comment by ravbhatnagar** [comment]
This is fixed in the 1.0 release and beyond.
