### ISSUE TITLE
New-AzureKeyVault fails if used in Visual Studio deployproj

### ISSUE THREAD

**Issue by BenStull** [Azure/azure-powershell#959]
New-AzureKeyVault attempts to retrieve the tenant ID, which isn't available in PowerShell sessions that are auth'd using a token, such as when deploying from within Visual Studio.  This results in the below InvalidOperationException, which isn't very helpful.

> [ERROR] New-AzureKeyVault : Invalid AzureEnvironment.
> ...
> [ERROR]     + CategoryInfo          : CloseError: (:) [New-AzureKeyVault], InvalidOperationException
> [ERROR]     + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.NewAzureKeyVault

This also means you can't use the Key Vault Azure Resource Manager template in a .deployproj template if you want to actually deploy the project from within Visual Studio.  I'm not sure what auth method Visual Studio Online build vnext uses for its Azure Powershell environment, but if it's also an auth token, that means Key Vaults will break fully automated deployment of new environments for us.

**Comment by hovsepm** [comment]
Thanks for reporting this. KeyVault team will have a look to the issue.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
