### ISSUE TITLE
How does migrating to Az impact Azure Automation runbooks?

### ISSUE THREAD

**Issue by jschrap** [Azure/azure-powershell#9595]
We have azure automation runbooks created with Powershell.
Do you have any recommendations in how to migrate these to use AZ?

**Comment by sphibbs** [comment]
We have a document describing the migration for az in automation [here](https://docs.microsoft.com/en-us/azure/automation/az-modules). Please let us know if you have any issues after reading the blog.

**Comment by sphibbs** [comment]
Assigning to @dcaro to test internal workflow. Will close soon unless jschrap requests further info.

**Comment by jschrap** [comment]
Thnx!!!!
