### ISSUE TITLE
DisplayXML for

### ISSUE THREAD

**Issue by doctordns** [Azure/azure-powershell#96]
Get-AzureVM produces sub-optimal output by default. I updated some DisplayXML that creates better output. 

See http://tfl09.blogspot.co.uk/2015/01/azure-vms-improving-display-xml.html for details of what the before/after looks like, and get the displayXML from http://pshscripts.blogspot.co.uk/2015/01/azurevmformatps1xml.html. 

IF someone wants to help, I'm happy to do the fork and do the update and offer a pull.

Thomas Lee - doctordns@gmail.com

**Comment by singhkay** [comment]
@doctordns This looks very good and more useful! However, I'm worried about some long names in the columns and how the output would look. Said that, we'd be happy to accept a PR and test it out and see if all these columns work or do we remove one of them.

P.S. Subscribed to your blog, will be reading in the future :)

**Comment by doctordns** [comment]
I can write the xml, and know how to update the module manifest, were this a simple module. 
Care to provide some assistance?  

As to over long column names, which ones., redoing the xml itself is easy!  I just don't know where to to
Start.

Thomas

**Comment by singhkay** [comment]
Oh I thought you already had one ready to send. I'm not sure if we have instructions on how to update the manifest, adding @huangpf for that

But I see that our xplat cli is already doing something better, so I'll take this as a feature request for us to do
![1](https://cloud.githubusercontent.com/assets/6164178/6255698/030232be-b767-11e4-9f53-dc3060d83dda.png)

**Comment by singhkay** [comment]
Closing at this point as we're looking into investing resources on the ARM cmdlets. We'll look into doing something similar for Get-AzureRmVm
