### ISSUE TITLE
Is -CustomData being run automatically on Windows Server OS  

### ISSUE THREAD

**Issue by jmora58** [Azure/azure-powershell#9600]
## Description of the new feature

Hello Team,

I hope you are doing great.

I am reaching you out to get your advisory regarding the use of -CustomData command on a new Windows VM deployment, we are attempting to execute a set of powershell commands on a newly created virtual machine by passing in a @hash string of powershell commands via the -customdata parameter on the Set-AzVMOperatingSystem cmdlet passed into New-AzVm cmdlet. 

We can see the customdata.bin file is created with the list of our commands, however the commands are not being executed when the VM startup. 

From link below:

https://azure.microsoft.com/en-us/blog/custom-data-and-cloud-init-on-windows-azure/ 

We can see that this command works on Linux VMs, but we haven't seen it in Windows VMs.

Can you please help us to verify if support -CustomData being run automatically on Windows Server OS works and the best way to do it.

Thanks in advance for your help.

**Comment by Drewm3** [comment]
Hi @jmora58, the CustomData functionality only makes the data available to the guest operating system. In the case of Linux VMs, there is a service called CloudInit [https://cloud-init.io/](url) which is installed with some Linux distros that execute the data in CustomData as a script. 

To execute a script on the VM the best solution is using the Custom Script Extension for VMs.
