### ISSUE TITLE
CreateBlueprintAssignmentByFile missing parameter definition and example

### ISSUE THREAD

**Issue by Linaa** [Azure/azure-powershell#9643]
## Description of the new feature
[CreateBlueprintAssignmentByFile](https://github.com/Azure/azure-powershell/blob/master/src/Blueprint/Blueprint/help/New-AzBlueprintAssignment.md#createblueprintassignmentbyfile) is missing definition for `AssignmentFile` parameter. No example for the format of this file has been provided ...

Similar for [Set-AzBluePrintAssignment](https://docs.microsoft.com/en-us/powershell/module/az.blueprint/set-azblueprintassignment?view=azps-2.4.0)

**Comment by cormacpayne** [comment]
@filizt Hey Filiz, would you mind taking a look at this issue?

**Comment by filizt** [comment]
@Linaa Looking.

**Comment by filizt** [comment]
@Linaa The request/response examples can be found at https://github.com/Azure/azure-rest-api-specs/tree/master/specification/blueprint/resource-manager/Microsoft.Blueprint/preview/2018-11-01-preview/examples.

For assignment an assignment json file would look like:

`{
  "identity": {
    "type": "SystemAssigned"
  },
  "location": "eastus",
  "properties": {
    "description": "enforce pre-defined simpleBlueprint to this XXXXXXXX subscription.",
    "blueprintId": "/providers/Microsoft.Management/managementGroups/AzBlueprint/providers/Microsoft.Blueprint/blueprints/simpleBlueprints",
    "parameters": {
      "storageAccountType": {
        "value": "Standard"
      },
      "costCenter": {
        "value": "Contoso/Online/Shopping/Production"
      },
      "owners": {
        "value": [
          "johnDoe@contoso.com",
          "johnsteam@contoso.com"
        ]
      }
    },
    "resourceGroups": {
      "storageRG": {
        "name": "defaultRG",
        "location": "eastus"
      }
    }
  }
}`

I have also updated the help messages with the above link.

Please let me know if this answers your question.

**Comment by alex-frankel** [comment]
Closing this - it looks like this was resolved
