### ISSUE TITLE
Typo VirtualNteworkRule parameter in EventHub and ServiceBus

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-powershell#9658]
## Description

Found in Set-AzServiceBusNetworkRuleSet and Set-AzEventHubNetworkRuleSet
https://github.com/Azure/azure-powershell/search?q=Ntework&unscoped_q=Ntework

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by markcowl** [comment]
@v-Ajnava Can you take a look and correct these?  You will need to add an alias to the misspelled name.

**Comment by v-Ajnava** [comment]
@nschonni, Thanks for pointing out, typo is fixed and will be in the next release. hence closing the issue.
