### ISSUE TITLE
Typo Microsot

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-powershell#9660]
## Description

In https://github.com/Azure/azure-powershell/blob/2eb2d61af03929a35128eb18f854fcd7490704dd/src/Network/Network/Cortex/VpnSite/NewAzureRmVpnSiteCommand.cs#L83 it is in the ResourceIdCompleter, but maybe it's misspelled in the service?

In https://github.com/Azure/azure-powershell/blob/2eb2d61af03929a35128eb18f854fcd7490704dd/src/Network/Network/help/Get-AzAvailablePrivateEndpointType.md#example it is in the returned serviceName values. Might be a service bug, or a docs issue.

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by markcowl** [comment]
@MikhailTryakhov Can you assign appropriately?  Most likely this is preventing the resource completer from completing this parameter

**Comment by KarenHammons** [comment]
@Nilambari - can we get an update please?

**Comment by Nilambari** [comment]
@ritwikbasu is going to fix it.

**Comment by KarenHammons** [comment]
@ritwikbasu and @Nilambari  - what's the latest on this fix?

**Comment by ritwikbasu** [comment]
@KarenHammons I am already working on this fix and will publish the PR shortly.
