### ISSUE TITLE
Az.Blueprints update broke custom blueprint filenames

### ISSUE THREAD

**Issue by psyrus** [Azure/azure-powershell#9675]
The line changed at the following commit now means that blueprints deployed with the following command can ONLY be named "Blueprint" or the command will fail:
https://github.com/Azure/azure-powershell/commit/3679cc661dce24ef6c0fc5f6c7a2430d98a57972#diff-9e045a4eb9cdfe5e21490f867bcc8df2R104

Tested with old versions of the Az.Blueprint versus new ones, the same code that previously works fails with the following:

```
Import-AzBlueprintWithArtifact : Cannot locate a file with the name Blueprint in: /Users/psyrus/dev/blueprints/testBp.
At line:1 char:1
+ Import-AzBlueprintWithArtifact -Name "PsyBlueprint" -ManagementGroupId Bluepri ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Import-AzBlueprintWithArtifact], Exception
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Blueprint.Cmdlets.ImportAzureRmBlueprint
 
DEBUG: AzureQoSEvent: CommandName - Import-AzBlueprintWithArtifact; IsSuccess - False; Duration - 00:00:02.9421885; Exception - System.Exception: Cannot locate a file with the name Blueprint in: /Users/psyrus/dev/blueprints/testBp.
   at Microsoft.Azure.Commands.Blueprint.Cmdlets.BlueprintCmdletBase.GetValidatedFilePath(String path, String fileName)
   at Microsoft.Azure.Commands.Blueprint.Cmdlets.BlueprintDefinitionCmdletBase.ImportBlueprint(String blueprintName, String scope, String inputPath, Boolean force)
   at Microsoft.Azure.Commands.Blueprint.Cmdlets.ImportAzureRmBlueprint.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 13:12:12 - ImportAzureRmBlueprint end processing.
DEBUG: 13:12:12 - ImportAzureRmBlueprint end processing.
```

Fails on both MacOS and Ubuntu (Azure Pipeline)... Which makes sense since the code now hardcodes the name :)

**Comment by filizt** [comment]
@psyrus With the cited change, we have made the name of the blueprint file standard (by naming it "Blueprint"). This way Import- cmdlet can look for this standard name in the given input folder. Though this should not prevent you from giving a different name to the blueprint through the cmdlet. For that, you can use the -Name parameter in the Import- cmdlet.

Let's say you have exported a blueprint called TestBlueprint, and would like to import it. Then the cmdlet usage would look like:

Import-AzBlueprintWithArtifact -Name MyNewTestBP -InputPath C:\Blueprints\TestBlueprint

The blueprint file would be named Blueprint.json however the imported blueprint will be named MyNewTestBP.

Let me know if this doesn't answer your question.

**Comment by psyrus** [comment]
Hi @filizt, thanks for the response, and the thorough explanation. 

The way the change broke previous functionality I just wanted to notify your team in case it was not intentional. Personally I would've loved the change to have Blueprints.json as the fallback while keeping the option for custom filenames that match the -Name parameter instead, but that's just because I selfishly didn't want to rename 15 JSON files from their descriptor names to Blueprint.json 😅 

Since this was planned/intentional, feel free to close the ticket. I'll just rework our code around it since I just have some messy temporary bugfix code in place currently to get the pipelines back up and running.

**Comment by filizt** [comment]
@psyrus Oh I see - yes this was an intentional change. We wanted to make the change as soon as possible to minimize the risk of breaking already established pipelines but looks like we still broke some. Sorry for the inconvenience.

For your suggestion of looking for the custom file name that match with -Name parameter and use Blueprints.json file as the fallback, I'm tagging our PM @alex-frankel here. 

@psyrus One note here is that even if this design is approved, it might take up to 3 weeks to be published in a new az blueprint version FYI.

**Comment by psyrus** [comment]
@filizt Thanks again for the info! At least for me/my project, we are already working with the new Blueprint.json files and it's not broken anymore now that we are up to date with the new spec. 

Thanks for you and your team's hard work enabling us to get our work done through a friendly library rather than having to write all the API calls ourselves.

**Comment by alex-frankel** [comment]
Closing since we were able to resolve by changing the filenames. Glad you are enjoying the new cmdlets. We really like them too :)
