### ISSUE TITLE
Typo PSHybridConnectionAttibutes

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-powershell#9690]
## Description

"Attributes" is misspelled. Probably not a bit deal, but it does bubble up to the documentation.
Because it is a public class, I guess it would be considered a breaking change to fix
https://github.com/Azure/azure-powershell/blob/1bcbe7b1f7a3323ac98f7754ba03eeb6b45e79f2/src/Relay/Relay/Models/PSHybridConnectionAttibutes.cs#L16

https://github.com/Azure/azure-powershell/search?q=Attibutes&unscoped_q=Attibutes&type=Code

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by niander** [comment]
@v-Ajnava Hi. Could you take a look at this? Since it is a model naming issue it should not be a breaking change.

**Comment by v-Ajnava** [comment]
Hi @niander and @nschonni, 

PR is merged and fix will be available in the  next release. hence closing the issue. 
please let us know if have any queries or reopen the issue.
