### ISSUE TITLE
No Az PS module for ActiveDirectoryAdministrator on SQL Managed Instance

### ISSUE THREAD

**Issue by jrgithub** [Azure/azure-powershell#9695]
Hi,

Where can I find Az PowerShell functionality to get / set ActiveDirectoryAdministrator on SQL Managed Instance. It exists on Azure SQL PaaS but seeking the same for Managed Instance? 

Please include this critical functionality.

**Comment by petrajkogit** [comment]
Hi,

unfortunately this functionality is not yet implemented to be used with Powershell. We will prioritize this work in following period. For now, Azure portal can be used as a workaround.

**Comment by jeroenterheerdt** [comment]
@petrajkogit - any update here?

**Comment by petrajkogit** [comment]
@jeroenterheerdt Yes, this was done. Take a look at:

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-aad-authentication-configure?tabs=azure-powershell#powershell-for-sql-managed-instance
