### ISSUE TITLE
New-AzVM with -Tag = Parameter set cannot be resolved using the specified named parameters

### ISSUE THREAD

**Issue by mlnrt** [Azure/azure-powershell#9697]
Hello,
I have an Azure subscription which enforces the use of some tags.
So I need to add the tags when creating resources.

But when I do a 
```
$mytags=@{tag1="value1";tag2="value2";tag3="value3"}
New-AzVM -<all parameters> -Tag $mytags
```

the command fails with the bellow error
```
New-AzVM : Parameter set cannot be resolved using the specified named parameters.
At C:\Users\myself\code\PowerShell for VM creation.ps1:26 char:1
+ New-AzVM `
+ ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzVM], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.Compute.NewAzureVMCommand 
```

If I remove `-Tag $mytags` from the command, the scripts executes but fails because it doesn't pass the policy which enforces tags on resources.

I tried to look at documentations, but everything I found so far explain:
- how to create a tag
- how to add a tag to an existing resource
I have yet to find a documentation showing how to assign tags while creating a resource

Thank you in advance

**Comment by sphibbs** [comment]
@mlnrt what parameters are you passing? Currently tag is only part of the default parameter set `New-AzVM
   [-ResourceGroupName] <String>
   [-Location] <String>
   [-VM] <PSVirtualMachine>
   [[-Zone] <String[]>]
   [-DisableBginfoExtension]
   [-Tag <Hashtable>]
   [-LicenseType <String>]
   [-AsJob]
   [-DefaultProfile <IAzureContextContainer>]
   [-WhatIf]
   [-Confirm]
   [<CommonParameters>]`

Tag needs to be added to the other two New-AzVm Parameter sets

**Comment by sphibbs** [comment]
The strategy library needs to add the tag support

**Comment by mlnrt** [comment]
@sphibbs thank you for the reply.
I'm using many parameters like `-Image -Credential -VirtualNetworkName -SubnetName -SecurityGroupName -Size`
It didn't even realized that there was different parameter sets and that -Tag could only be used with the default one... My bad. But that seemed so natural that it would be a basic parameter.

**Comment by sphibbs** [comment]
Reopening as -Tag should be optional for any creation parameter set.

**Comment by niander** [comment]
Not updating convenience cmdlets at this time and user seems to have find a solution. Closing it

**Comment by mlnrt** [comment]
@niander I did not find a solution. I gave up.
I was trying to use a policy to enforce some Tags, but it is just not possible in practice as there are too many scenarios like this one, where PowerShell or the Azure Portal doesn't allow us to input Tags hence preventing resource creation if such a policy is in place.
