### ISSUE TITLE
New-AzureSchedulerStorageQueueJob ignores StorageQueueMessage parameter

### ISSUE THREAD

**Issue by ewisuri** [Azure/azure-powershell#97]
The body of storage queue jobs created with the cmdlet `New-AzureSchedulerStorageQueueJob` is always empty, regardless of the value set for the `StorageQueueMessage` parameter.

In `Microsoft.WindowsAzure.Commands.Utilities.Scheduler.SchedulerMgmntClient::CreateStorageJob`, it looks like the created message is referencing the `Body` property from the `PSCreateJobParams` object, when it should be using `StorageQueueMessage`.

The `StorageQueueMessage` parameter is handled correctly in the `Set-AzureSchedulerStorageQueueMessage` cmdlet, so a workaround is to create the job with `New-` and then update it with the correct storage queue message using `Set-`.

**Comment by vivsriaus** [comment]
@ewisuri Apologize for the delay, and thanks for reporting this to us. This issue will be fixed in the upcoming release.

**Comment by cormacpayne** [comment]
This appears to have been fixed. Closing the issue.
