### ISSUE TITLE
Add ECC key support to Add-AzKeyVaultKey cmdlet

### ISSUE THREAD

**Issue by n0thingness** [Azure/azure-powershell#9716]
## Description of the new feature
I'm looking for the Azure PowerShell equivalent of the following Azure CLI command:

```
az keyvault key create --name myKeyName --vault-name myVaultName --kty EC --curve P-256K
```
It's rather surprising that both Azure Portal and Azure CLI support this functionality (albeit a [naming discrepancy](https://feedback.azure.com/forums/906355-azure-key-vault/suggestions/38127457-update-key-vault-ec-key-secp256k1-curve-name-to-p)), while Azure PowerShell's Add-AzKeyVaultKey [only supports RSA keys](https://docs.microsoft.com/en-us/powershell/module/az.keyvault/add-azkeyvaultkey?view=azps-2.4.0). I would have assumed that Azure PowerShell was the most well supported of the three.

**Comment by niander** [comment]
Hi @n0thingness this functionality is going to be available soon in a coming update release.

**Comment by n0thingness** [comment]
@niander @markcowl Any update on this? This functionality still appears to be absent in azps 3.0.0

**Comment by n0thingness** [comment]
Would appreciate an update on this. As far as I can tell, this is still absent in in az ps 4.2.0
