### ISSUE TITLE
az version 2.4.0, can someone tell me why this does not work?

### ISSUE THREAD

**Issue by jpsebasti** [Azure/azure-powershell#9721]
The following code is throwing:
Get-AzDisk : 'this.Client.SubscriptionId' cannot be null.
Can someone tell me why this is not working?
The Connect-AzAccount call is successful but the Get-AzDisk call is not

$clientID = "id-here"
$key = "key-here"
$SecurePassword = $key | ConvertTo-SecureString -AsPlainText -Force
$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $clientID, $SecurePassword
Connect-AzAccount -Credential $cred -Tenant "tenant-id-here" -ServicePrincipal
$disks=Get-AzDisk | Select Name,Tags,Id,Location,ResourceGroupName

**Comment by markcowl** [comment]
@jpsebati  JMy guess is that you aren't authorized for any subscriptions in that tenant., but there are some other possibilities.  To help diagnose, can you provide the extra info that is asked for in the issue template:
- Module Layout
```
Get-Module -ListAvailable
```

- Failing debug trace (in this case, including the login and the failing cmdlet
```
$DebugPreference="Contine"
```

- PowerShell and system information
```
$PSVersionTable
```

**Comment by jpsebasti** [comment]
Thank you, that was it.  The Service Principal needed reader at the subscription level.  The error generated 'this.Client.SubscriptionId' cannot be null' is a bit confusing

**Comment by jpsebasti** [comment]
solved, see above
