### ISSUE TITLE
Move-AzDataLakeStoreItem to rename a file in ADLS gen2 

### ISSUE THREAD

**Issue by srini99mkl** [Azure/azure-powershell#9724]
## Description
Hello All, I am trying to rename a file in DataLake Store Gen2 using the command 
Move-AzDataLakeStoreItem -AccountName mererdsaddffdev -Path \rdfdfdf\A\dbo\Dimdfdfdf\filename.txt -Destination \rdfdfdf\A\dbo\Dimdfdfdf\_filename_.txt

I am seeing following error
Parameter name: name,The 'User-Agent' header must be modified using the appropriate property or method.

## Steps to reproduce

```powershell

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by sphibbs** [comment]
@srini99mkl can you please provide the following to help us diagnose the issue?
Rn (Get-Module  -ListAvailable) and paste the output here
Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream

**Comment by markcowl** [comment]
Closing for lack of response.  If you are still seeing this issue, please open a new issure report, and include the requested information
