### ISSUE TITLE
Move CI job for powershell-common to azure-sdk ADO instance

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#9726]
## Description
Current CI job for powershell-common [here](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9544)

- [x] Move pipeline in the 'internal' project in the azure-sdk ADO instance (https://dev.azure.com/azure-sdk/internal)
- [x] Verify correct build
- [x] Verify PR hooks

# Cost: 2

**Comment by xiaohuyyyy-ms** [comment]
the new pipeline is in https://dev.azure.com/azure-sdk/internal/_build?definitionId=696&_a=summary

**Comment by dingmeng-xue** [comment]
Close it as pipeline is available.
