### ISSUE TITLE
Move Common sign jobs to Azure DevOps

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#9727]
## Description
- [ ] Move jenkins signing job for powershell-common into internal ADO (https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-common-sign/)

job steps:
```
```
- [ ] Verify sign job

**Comment by dingmeng-xue** [comment]
Split publish jobs to another issue #10677

**Comment by isra-fel** [comment]
Verified `azure-powershell-common-publish` today. It can build and publish, to both myget and github release.

**Comment by VeryEarly** [comment]
close as moved and verified
