### ISSUE TITLE
not able to deploy templates in virtual machine scale sets with autoscaling

### ISSUE THREAD

**Issue by hemapriyamaheswaran** [Azure/azure-powershell#9735]
In azure, I am trying to create templates for azure virtual machine scale sets with autoscaling. That templates fully in JSON format. I got one example template and try it as my convenient.  almost it completed but virtual machine scale set cannot created. It shows the following error. I don't understand this error.
Azure Error: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Could not find member 'rules' on object of type 'TemplateResource'. Path 'properties.template.resources[2].rules', line 1, position 1735.'.
Kindly send me a solution to solve this...

**Comment by lwajswaj** [comment]
This issue seems to be related to ARM template rather than AZ module, doesn't it?

**Comment by niander** [comment]
Hi @hemapriyamaheswaran. Could you try to fill out the following template?

(If you create a new issue of "Az module bug report" type you can see the full template with comments that may help)



## Description



## Steps to reproduce

```powershell

```

## Environment data



```

```

## Module versions



```powershell

```

## Debug output



```

```

## Error output



```

```

**Comment by markcowl** [comment]
You might take a look here for templates relating to ScaleSets:  https://github.com/Azure/azure-quickstart-templates
