### ISSUE TITLE
Missing Powershell Cmdlets

### ISSUE THREAD

**Issue by TurtleBeach** [Azure/azure-powershell#9736]
Powershell (6.2/2.4) is missing the DeviceProvisioningServices cmdlets.
I am attempting to use **New-AzIoTDeviceProvisioningService** in a Powershell function and when testing locally (after ensuring the Az module 2.4 is installed) an exception is thrown:
The term 'New-AzIoTDeviceProvisioningService' is not recognized as the name of a cmdlet, function, script file, or operable program.
Other cmdlets related to IoTHub exist and work.
Please either add it to Powershell or remove it from documentation (it appears in Azure Powershell 2.4 online documentation (https://docs.microsoft.com/en-us/powershell/module/az.deviceprovisioningservices/?view=azps-2.4.0#dps)

**Comment by niander** [comment]
Hi @TurtleBeach! This module is still on preview. Did you specifically installed `Az.DeviceProvisioningServices` module and imported it in your session before trying to run it?

**Comment by markcowl** [comment]
@TurtleBeach Az.DeviceProvisioningServices is not included in the Az roll-up, you can acquire this cmdlet by installing the module directly. 

```Install-Module Az.DeviceProvisioningServices```
