### ISSUE TITLE
Warn when results are truncated in Search-AzGraph

### ISSUE THREAD

**Issue by AndyHerb** [Azure/azure-powershell#9759]
## Description of the new feature
Currently, when a you run a query via Search-AzGraph but don't specify the -First parameter, the results are limited to the first 100 items (see https://github.com/Azure/azure-powershell/blob/master/src/ResourceGraph/ResourceGraph/Cmdlets/SearchAzureRmGraph.cs for source code details).

This is misleading and, in some circumstances can be problematic, as the user is unaware that a limit's been hit and truncation has occurred; i.e. When returning the number of items for billing purposes.

## Proposed implementation details (optional)
Raise a warning when results are truncated, unless a supplementary switch (i.e. -Force or -SuppressTruncationWarning) has been specified.  This should cover scenarios where no value has been specified for -First (and it's therefore defaulted to 100) and also where a user value has been specified but truncation has still occurred.

**Comment by cormacpayne** [comment]
@OlhaTkachenko just to confirm, this issue was resolved by [this PR](https://github.com/Azure/azure-powershell/pull/9719), correct?

**Comment by leylakazemi** [comment]
Thank you for the feedback. We have this in our backlog to do.

**Comment by snaheth** [comment]
@AndyHerb -- We're adding this message/warning in our update to both the CLI extension and PowerShell cmdlet. Thank you.

**Comment by dingmeng-xue** [comment]
Close it. The update was on Az.Resouces > 0.7.6
