### ISSUE TITLE
Get-AzureStorageTable : Could not load file or assembly 'Newtonsoft.Json

### ISSUE THREAD

**Issue by rajdeepakp** [Azure/azure-powershell#9767]
Get-AzureStorageTable : Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral,
PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
At line:1 char:10
+ $table = Get-AzureStorageTable -Name $tableName -Context $saContext
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureStorageTable], StorageException
    + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTab
   leCommand

**Comment by blueww** [comment]
@rajdeepakp 
Would you please follow the issue template and share the necessary information for the investigation, espicially:
1. the loaded module name/version, you can get it by run "Get-module" after the issue repro.
2. OS version
3. Powershell version, get it by run "$PSVersionTable"

**Comment by rajdeepakp** [comment]
OS: Windows 10
Powershell version : 
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Get-module:
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     4.3.0      Azure.Storage                       {Disable-AzureStorageDeleteRetentionPolicy, Enable-AzureStorageDeleteRetentionPolic...
Script     5.0.1      AzureRM.profile                     {Add-AzureRmEnvironment, Clear-AzureRmContext, Clear-AzureRmDefault, Connect-AzureR...
Script     5.0.0      AzureRM.Storage                     {Add-AzureRmStorageAccountNetworkRule, Get-AzureRmStorageAccount, Get-AzureRmStorag...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}
Script     1.0.0.1    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-P...

**Comment by blueww** [comment]
@rajdeepakp 
You use very old  Azure Powershell module. 
Does it works on this before , and just not work recently?
Or you just installed these modules?

Do you mind to upgrade to latest Azure modules and try again?
1. Uninstall` AzureRm.*` modules, remove `Azure.Storage` module from your machine
2. Install the lastest Azure Powershell by `Install-Module Az –Repository PSGallery`
3. Since there are some breaking changes from AzureRM.* module to latest Az module. You need run `Enable-AzureRmAlias` to enable the old style cmdlets name. See details in https://github.com/Azure/azure-powershell/blob/master/documentation/migration-guides/Az.1.0.0-migration-guide.md

**Comment by rajdeepakp** [comment]
@blueww  - Thanks the above steps fixed the issue.

**Comment by blueww** [comment]
@rajdeepakp 
Thanks for the update!
I will close the issue.
Fell free to contact us if you need any other assistant.
