### ISSUE TITLE
New-AzScheduledQueryRuleTriggerCondition

### ISSUE THREAD

**Issue by jethrovaneetvelde** [Azure/azure-powershell#9768]
Not sure if this is the correct place but I got an issue regarding the creation of alerts via ARM templates.
Documentation https://docs.microsoft.com/nl-nl/powershell/module/az.monitor/new-azscheduledqueryruletriggercondition?view=azps-2.5.0 says the threshold can be a double. While using 0.3 in the ARM template as value however, I get an error saying the number needs to be a whole number. Right now I change my OMS query to multiple but this is not a workaround which I'd like to keep.

**Comment by markcowl** [comment]
@jethrovaneetvelde Unfortunately, we don't have information about the allowed values in Monitor templates. You might look here for some examples: https://github.com/Azure/azure-quickstart-templates
