### ISSUE TITLE
az.reservations is not installed when installing az

### ISSUE THREAD

**Issue by jackfruhecolab** [Azure/azure-powershell#9769]
## Description
Hi, installing all modules with `install-module -name az` does not install the `az.reservations` module.

**Comment by markcowl** [comment]
Correct.  When Az.Reservations is GA and updated to version 1.0, it will be included in the Az roll-up.

**Comment by mcdonamw** [comment]
Sorry to necropost, but when is az.reservations supposed to go GA?  It's been almost 7 years since this post but it still does not exist under the Az roll-up and is still at version 0.14.1
