### ISSUE TITLE
Support ReplicationGroupName for Azure-Azure Replication Protected Items

### ISSUE THREAD

**Issue by nickfriday-kainos** [Azure/azure-powershell#9774]
## Description of the new feature

**New-AzRecoveryServicesAsrReplicationProtectedItem -AzuretoAzure** should support parameter **-ReplicationGroupName**.

## Proposed implementation details (optional)

Currently **-ReplicationGroupName** is only supported with **-VMwareToAzure**, but this functionality is available for Azure-Azure replication via the portal.

Once configured via the portal, this configuration is reflected via the _ProviderSpecificDetails.MultiVmGroupId_ and _ProviderSpecificDetails.MultiVmGroupName_ properties of the **Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.ASRReplicationProtectedItem** object returned by **Get-AzRecoveryServicesAsrReplicationProtectedItem**.

**Comment by markcowl** [comment]
@viverm Can you take a look?

**Comment by viverm** [comment]
@nickfriday-kainos 
use latest preview module from Az.RecoveryServices
```
Uninstall-Module -Name "Az.RecoveryServices"
 Install-Module -Name PowerShellGet -Force
 Install-Module -Name Az.RecoveryServices -AllowPrerelease -AllowClobber
## close all Powershell windows and reopen powershell

```
 New-AzRecoveryServicesAsrReplicationProtectedItem [-AzureToAzure] -AzureToAzureDiskReplicationConfiguration <Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.ASRAzuretoAzureDiskReplicationConfig[]> -AzureVmId <System.String>[-DiskEncryptionSecretUrl <System.String>] [-DiskEncryptionVaultId <System.String>] [-KeyEncryptionKeyUrl <System.String>] [-KeyEncryptionVaultId <System.String>] -Name <System.String> -ProtectionContainerMapping  <Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.ASRProtectionContainerMapping> [-RecoveryAvailabilitySetId <System.String>] [-RecoveryAvailabilityZone <System.String>] [-RecoveryAzureNetworkId <System.String>]
    [-RecoveryAzureSubnetName <System.String>] [-RecoveryBootDiagStorageAccountId <System.String>] [-RecoveryCloudServiceId <System.String>] -RecoveryResourceGroupId <System.String> [-RecoveryVmName <System.String>] `[-ReplicationGroupName <System.String>]`
