### ISSUE TITLE
Documentation change for Set-AzDiagnosticSetting

### ISSUE THREAD

**Issue by bwren** [Azure/azure-powershell#9775]
## Description
Documentation issue with [Set-AzDiagnosticSetting](https://docs.microsoft.com/en-us/powershell/module/az.monitor/set-azdiagnosticsetting?view=azps-2.5.0&viewFallbackFrom=azps-2.4.0). The description for WorkspaceId parameter is misleading.  

Current:
The Id of the workspace

Should be changed to:
The Resource ID of the workspace.

**Comment by markcowl** [comment]
@gucalder can you take a look?

**Comment by bwren** [comment]
@gucalder @markcowl Just looking for an update on this.

**Comment by mortenlerudjordet** [comment]
Please make this change as -WorkspaceId is misleading

**Comment by dingmeng-xue** [comment]
@bwren , please share how you are using `-WorkspaceId`.

**Comment by markcowl** [comment]
@dingmeng-xue One of the patterns we normally follow is that when '*Id' is used as a parameter, it represents a GUID - in the case where this is also an external reference to a resource, the advice is to allow *either* resourceId *or* guid input.  The code of the cmdlet should tell us the appropriate usage, and determine what change is needed to help.

**Comment by VeryEarly** [comment]
fixed.
