### ISSUE TITLE
Allow to set SigninTenant for New-AzApiManagementIdentityProvider operation

### ISSUE THREAD

**Issue by maksym-synkevych** [Azure/azure-powershell#9783]
## Description of the new feature
For now, we can specify "Signin tenant" for Identity provider from Api Management Service UI but we can not do the same using powershell.
## Proposed implementation details (optional)

**Comment by cormacpayne** [comment]
Closing this issue as a duplicate of https://github.com/Azure/azure-powershell/issues/9784
