### ISSUE TITLE
Allow to set SigninTenant for New-AzApiManagementIdentityProvider operation

### ISSUE THREAD

**Issue by maksym-synkevych** [Azure/azure-powershell#9784]
## Description of the new feature
For now, we can specify "Signin tenant" from Api Management Service UI but we can not do the same using Powershell.
Expected behavior: to be able to specify Signin Tenant using New-AzApiManagementIdentityProvider operation.

**Comment by cormacpayne** [comment]
@solankisamir Hey Samir, would you mind taking a look at this feature request?

**Comment by solankisamir** [comment]
ack

**Comment by solankisamir** [comment]
This is covered through property `AllowedTenants` on the cmdlet.

https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/New-AzApiManagementIdentityProvider?view=azps-2.7.0#examples

**Comment by maksym-synkevych** [comment]
Hello @solankisamir 

`AllowedTenants` is not the same as `Signin tenant`. How can I specify `Signin tenant` using cmdlet (not the `Allowed tenant`)?
![image](https://user-images.githubusercontent.com/7526230/65960856-1280cb00-e45e-11e9-9292-3e90d8b50b24.png)

**Comment by solankisamir** [comment]
I see now, this property is missing in our REST specs also. I will need to start from there.

**Comment by solankisamir** [comment]
Please download the update from 

Download the install package from Github: https://github.com/Azure/azure-powershell/releases/tag/v3.6.1-March2020 
Install the package from PSGallery: https://www.powershellgallery.com/packages/Az/3.6.1
