### ISSUE TITLE
typo RelayNamespaceAttirbutesUpdateParameter

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-powershell#9787]
## Description

The word "Attributes" is misspelled in RelayNamespaceAttirbutesUpdateParameter
https://github.com/Azure/azure-powershell/search?q=RelayNamespaceAttirbutesUpdateParameter&unscoped_q=RelayNamespaceAttirbutesUpdateParameter
## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by markcowl** [comment]
@v-Ajnava Please take a look - if you would like to correct, leave an alias to the old (misspelled) name to avoid breaking changes

**Comment by jfggdl** [comment]
@nschonni, Thank you for creating this issue. We are rolling out a fix and should be available by the end of the month.

**Comment by v-Ajnava** [comment]
fix PR is merged will be available in next release. hence closing the issue. please feel free to open the issue if you have any queries regarding the fix.
