### ISSUE TITLE
typo EnumerateServicesBySubcription

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-powershell#9788]
## Description
The word "Subscription" is misspelled in "EnumerateServicesBySubcription"

https://github.com/Azure/azure-powershell/search?q=Subcription&unscoped_q=Subcription
Also misspelled in a few code comments

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by markcowl** [comment]
names of parameter sets and internal code comments will not be changed.
