### ISSUE TITLE
typo TimeOfOccurence

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-powershell#9790]
## Description

The word "Occurrence" is misspelled in "TimeOfOccurence" https://github.com/Azure/azure-powershell/search?q=TimeOfOccurence&unscoped_q=TimeOfOccurence

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by markcowl** [comment]
Property values come from the API Definition
