### ISSUE TITLE
typo NetwrokruleSet

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-powershell#9791]
## Description

The word "NetworkRuleSet" is misspelled as "NetwrokruleSet" https://github.com/Azure/azure-powershell/search?q=Netwrokrule&unscoped_q=Netwrokrule

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by markcowl** [comment]
Parameter set names and other internal identifiers will not be corrected for typos in legacy code.

**Comment by nschonni** [comment]
This is another one that does show up in documentation
