### ISSUE TITLE
Improve the user experience for setting a web app AppSetting

### ISSUE THREAD

**Issue by richardszalay** [Azure/azure-powershell#9792]
## Description of the new feature

Right now, `Set-AzWebApp -AppSettings` replaces the app settings with those provided (rather than merging them). This would be workable if `(Get-AzWebApp).SiteConfig.AppSettings` was a hashtable, but it's a `List<NameValuePair>`.

As it stands, and unless I'm missing something, this is the minimum requirements for updating a single app setting on a web app:

```powershell
$app = Get-AzWebApp mywebapp

$appSettings = $webapp.SiteConfig.AppSettings | % { $_tmpHash = @{} } { $_tmpHash[$_.Name] = $_.Value } { $_tmpHash }

$appSettings["NewKey"] = "NewValue"

Set-AzWebApp -Name $app.Name -ResourceGroup $app.ResourceGroup -AppSettings $appSettings

```

This seems like a lot of work for what I would think is a fairly common requirement.

As an aside, the documentation didn't make it clear that `-AppSettings` did actually replace the existing values so I've submitted a PR (#9793) to add clarification

## Proposed implementation details (optional)

Either make `AppSettings` a hashtable (which probably isn't it's based on a non-powershell specific library), or provide a `-PartialAppSettings` property for `Set-AzWebApp`

**Comment by markcowl** [comment]
@panchagnula Can you take a look?

**Comment by panchagnula** [comment]
No plans for fixing this right now, as this low priority. Sorry - we will bring this back later if we update this command.
