### ISSUE TITLE
Use same authentication flow as Azure CLI

### ISSUE THREAD

**Issue by phillipsj** [Azure/azure-powershell#9796]
## Description of the new feature

When you login using the Azure CLI, it automatically opens the browser and hits the login page. However, the new AZ module is still using the device code login. The text of the Azure CLI hs the following after doing an *az login*.

```
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
You have logged in. Now let us find all the subscriptions to which you have access...
```

It considers this an old experience and I agree. It would be nice to see Connect-AzAccount behave the same way.

**Comment by mikewo** [comment]
Completely agree here. This experience can be so much better.

**Comment by markcowl** [comment]
You are so correct.  This is in progress, and you can see a preview of the new experience in our preview module: https://www.powershellgallery.com/packages/Az.Accounts/2.0.0-preview

You can track the progress here: #7358

**Comment by phillipsj** [comment]
Thank you for your response.
