### ISSUE TITLE
Add-AzVMSshPublicKey returns Misleading Error Message

### ISSUE THREAD

**Issue by canuzun** [Azure/azure-powershell#9806]
## Description

When I try to use this on a Windows OS VM, I get the following error.
_Add-AzVMSshPublicKey : Cannot specify both Windows and Linux configurations._
Which is not the case...

As I understand, this is the code block that returns this error. 
```
else if (this.VM.OSProfile.WindowsConfiguration != null && this.VM.OSProfile.LinuxConfiguration == null)
{
    throw new ArgumentException(Microsoft.Azure.Commands.Compute.Properties.Resources.BothWindowsAndLinuxConfigurationsSpecified);
}
```

The error message would have been right if both configurations are not null. As I understand from the code, this cmdlet is meant to be used in Linux only. If that's the case, the message should also reflect it.

BTW, the documentation for Add-AzVMSshPublicKey is not clear if this can be used on Windows or maybe I am missing something.

**Comment by markcowl** [comment]
@hyonholee Can you take  alook

**Comment by Drewm3** [comment]
Hi @canuzun, SSH configuration is part of the Linux Configuration in the APIs, and it is not possible to set Linux configuration for a Windows VM. I agree that the documentation for the cmdlet should be updated.

@hyonholee, could you update the documentation for this cmdlet to go from "The Add-AzVMSshPublicKey cmdlet adds the public keys that you can use to connect to a virtual machine over Secure Shell (SSH)." to "The Add-AzVMSshPublicKey cmdlet adds the public keys that you can use to connect to a **Linux** virtual machine over Secure Shell (SSH)."

**Comment by Drewm3** [comment]
I am going to close this issue now that the documentation update has been made.
