### ISSUE TITLE
Connection on Internet impossible 

### ISSUE THREAD

**Issue by cloudshellsystem** [Azure/azure-powershell#9807]
## Description of the new feature
Hello
my issue is on Azure Connection.
From Internet by Wireless.
When i create a VM, or create a new compute (any OS, i tried), it's impossible to connect on.
I tried 4 diffrents SSID public/private or others from Shared Connection SSID.
It's possible to connect to the Azure Portal, to do somary things (resource group, new storage account...). 
So please tell me if it's possible to explain me why it's difficult to deploy a VM and connect on it by RDP or SSH, when i can't connect it with. And what i have to do, to connect from any Wireless connection with SSH and RDP without any problem. 

Thank you

**Comment by markcowl** [comment]
I am not sure what you are asking that is related to Azure PowerShell, can you clarify?  It seems that you are having issues connecting to the portal as well.  Here is a tutorial on connecting to Azure: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/quick-create-powershell
