### ISSUE TITLE
Az.LogicApp - Pipeline input for Name parameter?

### ISSUE THREAD

**Issue by mikejwhat** [Azure/azure-powershell#9809]
Hi,

Just wondering if there is a reason the Az.LogicApp cmdlets don't accept pipeline input for the Name parameter? I feel as if this would enhance usability and make them feel more familiar.

Thanks,

Mike

**Comment by markcowl** [comment]
@mikejwhat Binding objects from the pipeline by property name is not very performant, it is generally better to pipe by value.  You *should* be able to pipe a logicApp object obtained by get into an action cmdlet directly, however.

**Comment by mikejwhat** [comment]
Hi Mark,

None of the Logic App cmdlets have an InputObject parameter or any parameter that binds by value.

On closer inspection, Start-AzLogicApp and Test-AzLogicApp do actually bind ByPropertyName on the Name parameter... it's Set-AzLogicApp and Remove-AzLogicApp which don't.

This feels a little inconsistent with the other Az modules. All of the VirtualMachine action cmdlets bind ByPropertyName on the Name parameter for instance.
