### ISSUE TITLE
Change New-AzAdServicePrincipal to add credentials only to associated application

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#9815]
### Description

For simplicity, `New-AzAdServicePrincipal` adds credentials a generated secret credential to the serviceTo prevent useres from inadvertently adding secrets to service principals that map to out-of-tenant applications, make the following changes:

- [ ] When an application is created for the service principal, add the generated secret to the application
- [ ] If the application already exists, do not automatically add a secret
- [ ] Verify that the new SPN + Secret can be used for log in (Azure PowerShell)

**Comment by dingmeng-xue** [comment]
Move to next milestone to verify.

**Comment by msJinLei** [comment]
https://github.com/Azure/azure-powershell/pull/10393 PR merged.
