### ISSUE TITLE
New-AzStorageShare fails to authenticate

### ISSUE THREAD

**Issue by mholder-learfield** [Azure/azure-powershell#9820]
I am trying to do something quite simple - create a file share in a specific storage account. Following the documentation on the Microsoft website it should be as simple as the script below. I have connected to Azure and established my storage context with no issue. The issue I am having is that when I try to create the file share it fails to authenticate. That error message is at the bottom.

---- SCRIPT ----
$networkFolders = Import-Csv -Path C:\Users\michael.holder\Desktop\NetworkFolders.csv

$credentials = Connect-AzAccount
$context = New-AzStorageContext -StorageAccountName "ccbdrecordings" -UseConnectedAccount
New-AzStorageShare -Name "eest" -Context $context
---- END SCRIPT ----

---- ERROR MESSAGE ----
New-AzStorageShare : Server failed to authenticate the request. Make sure the value of Authorization 
header is formed correctly including the signature. HTTP Status Code: 403 - HTTP Error Message: Server
failed to authenticate the request. Make sure the value of Authorization header is formed correctly
including the signature.
ErrorCode: AuthenticationFailed
ErrorMessage: Server failed to authenticate the request. Make sure the value of Authorization header is
formed correctly including the signature.
RequestId:cab8d864-d01a-0067-68f2-517fca000000
Time:2019-08-13T16:19:56.2175779Z
AuthenticationErrorDetail: Authentication scheme Bearer is not supported.
At line:5 char:1
+ New-AzStorageShare -Name "eest" -Context $context -DefaultProfile $co ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzStorageShare], StorageException
    + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands.Storage.File.Cmdlet.NewA
   zureStorageShare
---- END ERROR MESSAGE ----

**Comment by mholder-learfield** [comment]
Turns out I was missing the access key which wasn't in the documentation I was reading. :)

**Comment by blueww** [comment]
@mholder-learfield 
In the problem script, you run  New-AzStorageContext with -UseConnectedAccount. so it will creates an Azure Storage context with OAuth (Azure AD) Authentication, and this kind of authentication only support Blob/Queue now.
In help of New-AzStorageContext , you can also see in cmdlet description:  "details of authentication of the Storage Service in   https://docs.microsoft.com/en-us/rest/api/storageservices/authorization-for-the-azure-storage-services" And in the link,  you will find OAuth (Azure AD) Authentication only support Blob and Queue.

Besides that, if you run following script before New-AzStorageShare, it will set a Storage account as current account, and when you don't input storage context, it will run the cmdlet on the current storage account:
`Set-AzureRmCurrentStorageAccount -ResourceGroupName $rgname -StorageAccountName $accountName`
