### ISSUE TITLE
Error while importing the module after manual upload with Azure REST API request

### ISSUE THREAD

**Issue by krysickij1** [Azure/azure-powershell#9833]
Issue Details
-----------------
After uploading a module downloaded from [Powershell Gallery](https://powershellgallery.com) to automation account I'm receiving this error:
**Error importing the module AzureRM.DataFactoryV2. Import failed with the following error: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.**

Steps to reproduce
------------------------------
1. Download package from [Powershell Gallery](https://powershellgallery.com)
2. Change file extension to .zip and change the file name to be the same as in the gallery i.e. AzureRM.DataFactoryV2.zip
3. Remove nuget files (as described [here](https://docs.microsoft.com/en-us/powershell/gallery/how-to/working-with-packages/manual-download#feedback))
4. Upload .zip file to blob to get proper content link
4. Make a REST Request with a content link as described in [Azure REST API Documentation](https://docs.microsoft.com/en-us/rest/api/automation/module/createorupdate)

The response code from REST API Request is 200 and I can see the package uploaded to automation account but during the importing this error appears.

**Comment by cormacpayne** [comment]
@krysickij1 a couple of questions:

- Is there a document that you're following for the above steps?
- For the link you mentioned in step (3) for removing the NuGet files, this appears to be for scripts, where our packages are modules
- Is there any reason that you're using the `AzureRM` modules rather than the new `Az` modules?

**Comment by krysickij1** [comment]
@cormacpayne Thank you for exploring my issue. Now, to your points:
1.  There isn't one document. It's rather combination of different methods to get to the final result. We're using Python and we want to get rid of any manual steps in our process which exactly importing modules to azure automation account is. Since there is no az cli support for this service I used Azure REST API and as described [in a documentation](https://docs.microsoft.com/en-us/rest/api/automation/module/createorupdate) I needed a content link, so I created it by using blob. That works with runbooks and with modules as well but there is a point about what should I exactly uploading. 
2. In this link it refers to script and modules. 
3. That's our setup. I haven't tried that method with those new ones. What could be a benefit of that?

**Comment by dcaro** [comment]
@krysickij1 can you please let me know if you are still facing this issue? 
Generally speaking we are recommending to use the Az module since this is the generation of modules that receive the improvements from Azure.

**Comment by krysickij1** [comment]
@dcaro we change the way of importing modules so I'm not sure whether this is still an issue.

**Comment by dcaro** [comment]
Thanks @krysickij1 i will close this issue. Feel free to open a new one if needed.
