### ISSUE TITLE
Update ResourceManager version used by ProfileClient

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#9838]
## Description

Update the resourcemanager version used in Az.Accounts.  This will allow bringing in new properties (like TenantId)

- [ ] Verify update to common code for ARM common module subscription Client
- [ ] Update Connect-AzAccount, `Get-AzSubscription` and other cmdlets to use new library
   - [ ] Update TenantId setting in subscription class
- [ ] Update `Get-AzTenant` to return the domain name as a property of the output type in addition to the current tenant ID that is being returned with this object
- [ ] Update tests
- [ ] Add tests to verify correct tenantId display for subscription projection scenarios

**Comment by msJinLei** [comment]
## Issue Breakdown

- [ ] Ask Bganapa whether subscription version 2018-06-01 can be supported by azure stack.
    - In latest hybrid profile the supported version is 2018-05-01.
- [ ] Regenerate ResourceManager to contains all the parts of update.
    - For resources.json update & subscription.json update not in the same version.
- [ ] Update related codes in AzAccounts
   - Update TenantId setting in AzureSubscription 
   - Update Get-AzTenant to return the domain name as a property of the output type in addition to the current tenant ID that is being returned with this object
- [ ] Update test cases

**Comment by lostcase** [comment]
please address "Update Get-AzTenant to return the domain name"

**Comment by swinster** [comment]
Any update on getting `Get-Aztenant` to retrieve Tenant Name? 

This is kind of important, especially when you are programmatically trying to figure out a UP of a user who is a guest in a Tenant.

**Comment by kilasuit** [comment]
as a consultant in many tenants this is well over due for being needed 

@markcowl / @msJinLei what is the new timeline for this as there isn't one listed?

**Comment by VOVELEE** [comment]
Any updates on this one?

**Comment by msJinLei** [comment]
Fixed by https://github.com/Azure/azure-powershell/pull/12292 and https://github.com/Azure/azure-powershell/pull/12495
