### ISSUE TITLE
The parameter "Scope" should be optional for the cmdlet New-AzPolicyAssignment

### ISSUE THREAD

**Issue by dolauli** [Azure/azure-powershell#9839]
## Description

Currently if "Scope" is not provided, New-AzPolicyAssigment will fail. But in general, it should use the global subscription which is set by Select-AzSubscription.
Refer to #9808 for details.

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by robga** [comment]
Thanks: I've opened a work item on my team for this. We'll get to it as soon as we can.
