### ISSUE TITLE
New-AzADServicePrincipal - Please provide examples for use with Credential and Certificate

### ISSUE THREAD

**Issue by Sambsamb** [Azure/azure-powershell#9842]
## Description

Documentation at https://github.com/Azure/azure-powershell/blob/master/src/Resources/Resources/help/New-AzADServicePrincipal.md and https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azadserviceprincipal?view=azps-2.5.0 provides no examples for using this cmdlet with a credential or certificate.

Please provide examples for using this cmdlet 'DisplayNameWithPasswordCredentialParameterSet' and 'DisplayNameWithKeyCredentialParameterSet'

## Steps to reproduce

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by msJinLei** [comment]
Fixed by https://github.com/Azure/azure-powershell/pull/10889
