### ISSUE TITLE
##[error]Could not fetch access token for Managed Identity

### ISSUE THREAD

**Issue by RoshanKumarMicrosoft** [Azure/azure-powershell#9848]
I set up a private build agent on a Microsoft Azure Government (MAG) VM that has Managed Identity enabled. When I run a build release that contains an Azure PowerShell command, I get this error:

##[command]Import-Module
-Name C:\Program Files\WindowsPowerShell\Modules\AzureRM\6.13.1\AzureRM.psd1
-Global

##[command]Disable-AzureRmContextAutosave
-ErrorAction Stop

##[command]Add-AzureRmAccount 
-AccessToken ****** -AccountId 9-2019-02-14T19:57:05.8565631+00:00 

##[error]The access
token has been obtained for wrong audience or resource
'https://management.usgovcloudapi.net/'. It should exactly match with one of
the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'.

##[error]Could not
fetch access token for Managed Identity. {0}
The Add-AzureRMAccount command is generated by the DevOps Pipeline as far as I can tell. The Service Connection that contains the Managed Identity does specify AzureUSGovernment as the environment.

**Comment by cormacpayne** [comment]
@RoshanKumarMicrosoft which Azure PowerShell task are you using? It appears that the V4 version (preview) of this task is providing the `-Environment` parameter when authenticating, which it looks like is not happening in the above call to `Add-AzureRmAccount`. I think if the correct environment is provided to the `-Environment` parameter, the correct endpoint will be used.

**Comment by dingmeng-xue** [comment]
@RoshanKumarMicrosoft, could you provide update?

**Comment by dingmeng-xue** [comment]
@RoshanKumarMicrosoft, I'm closing this issue now. Please contact us if you meet any problem.
