### ISSUE TITLE
Example script out of order

### ISSUE THREAD

**Issue by TurnerMarshall** [Azure/azure-powershell#9849]
## Description of the new feature
Replace example script with position zero in proper place.
## Proposed implementation details (optional)
Example script should read:

PS C:\>Register-AzureRmAutomationDscNode -ResourceGroupName "ResourceGroup01" -AutomationAccountName "Contoso17" -AzureVMName "VirtualMachine01" -NodeConfigurationName "ContosoConfiguration.webserver"

**Comment by cormacpayne** [comment]
@TurnerMarshall thanks for the issue -- I believe that you're referring to the example found in the reference documentation for [`Register-AzAutomationDscNode`](https://github.com/Azure/azure-powershell/blob/ed28cba8a2da7d810084e076b15895b4e2b3bb99/src/Automation/Automation/help/Register-AzAutomationDscNode.md#example-1-register-an-azure-virtual-machine-as-an-azure-dsc-node).

_Note_: as of December 2018, we stopped actively shipping the `AzureRM` module in favor of the new `Az` module, which includes the documentation for the `AzureRM` module. 

We accept external contributions to this repository, so feel free to open a pull request that makes the proposed change to the above file 😀 If you would prefer for us to make the change, just let me know and we can do so as well.
