### ISSUE TITLE
Get-AzDiagnosticSetting , Get-AzureRmDiagnosticSetting, Set-AzDiagnosticSetting not working for all resources

### ISSUE THREAD

**Issue by omerzubair** [Azure/azure-powershell#9863]
## Description
I have been trying to build an enterprise runbook to connect all Azure resources to the Log Analytics via 'Diagnostic Settings'. From Azure Interface everything is fine but as you can imagine there are so many resources. Also there are new ones coming every couple of hours. Cannot upkeep manually.

I am unable to use command 
- Get-AzDiagnosticSetting

before i use 
- Set-AzDiagnosticSetting command 

- There is no output and no errors when i use Get-AzDiagnosticSetting (esp on KeyVault). It does work on SQL DBs.
- Even if i supply correct values Set-AzDiagnosticSetting,  it ERRORS out

## Steps to reproduce
Ran both commands it in Automation accounts and also on Cloud Shell same result.
"SQL server WORKS ok for GET. But The KeyVault Does not!"
$resourceId = "/subscriptions/---------/resourceGroups/RGRG/providers/Microsoft.KeyVault/vaults/keyVaultdelme"
Get-AzureRmDiagnosticSetting -ResourceId $resourceId

"Example for SQL PaaS DB"
$resourceID = "/subscriptions/-----------/resourceGroups/RGRG/providers/Microsoft.Sql/servers/db-srv/databases/db_test_audit"
$categoryLogsStringWithComma = "SQLInsights,AutomaticTuning,QueryStoreRuntimeStatistics,QueryStoreWaitStatistics,Errors,DatabaseWaitStatistics,Timeouts,Blocks,Deadlocks,Audit,SQLSecurityAuditEvents"
$categoryMetricsStringWithComma = "Basic"

Set-AzDiagnosticSetting -Name "Logs" -ResourceId $resourceId -WorkspaceId $LogAnalytics_URI -Category $categoryLogsStringWithComma -MetricCategory $categoryMetricsStringWithComma -Enabled $true 

## Environment data

PS Azure:\>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Linux 4.15.0-1052-azure #57-Ubuntu SMP Tue Jul 23 19:07:16 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

## Module versions

```powershell
ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     2.5.0      Az                                  Core,Desk
Script     1.6.1      Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.0.0      Az.Advisor                          Core,Desk {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Disable-AzAdvisorRecommendation, Get-AzAdvisorConfiguration…}
Script     1.0.1      Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential…}
Script     1.1.0      Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAnalysisServicesServer…}
Script     1.2.0      Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagementRegion, Add-AzApiManagementUserToGroup…}
Script     1.0.1      Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Set-AzApplicationInsightsPricingPlan…}
Script     1.3.1      Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDscNodeConfiguration…}
Script     1.1.0      Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, New-AzBatchAccount…}
Script     1.0.0      Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget…}
Script     1.3.0      Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile…}
Script     1.2.0      Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSku, Get-AzCognitiveServicesAccountType…}
Script     2.4.1      Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet…}
Script     1.0.1      Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}
Script     1.1.0      Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegistry…}
Script     1.1.3      Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2…}
Script     1.0.0      Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalyticsCatalogCredential, Set-AzDataLakeAnalyticsCatalogCredential…}
Script     1.2.1      Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreFirewallRule, Set-AzDataLakeStoreTrustedIdProvider…}
Script     1.0.0      Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifactSource, Set-AzDeploymentManagerArtifactSource, Remove-AzDeploymentManagerArtifactSource…}
Script     1.0.0      Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy…}
Script     1.1.1      Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet…}
Script     1.2.1      Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey…}
Script     1.3.0      Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace…}
Script     1.1.0      Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoor…}
Script     0.10.6     Az.GuestConfiguration               Core,Desk {Get-AzVMGuestPolicyStatus, Get-AzVMGuestPolicyStatusHistory}
Script     2.0.0      Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMapReduceJobDefinition…}
Script     1.2.0      Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob…}
Script     1.3.0      Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultCertificateOperation…}
Script     1.3.0      Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConfiguration, Get-AzIntegrationAccountCallbackUrl…}
Script     1.1.0      Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Remove-AzMlCommitmentPlan…}
Script     1.0.0      Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, New-AzManagedServicesAssignment, Remove-AzManagedServicesAssignment, Get-AzManagedServicesDefinition…}
Script     1.0.0      Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.0      Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaServiceKey, Get-AzMediaServiceNameAvailability…}
Script     1.2.1      Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile…}
Script     1.12.0     Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplicationGatewayAuthenticationCertificate, Remove-AzAppl…
Script     1.1.0      Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-AzNotificationHubListKey, Get-AzNotificationHubPNSCredential…}
Script     1.3.2      Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Disable-AzOperationalInsightsLinuxCustomLogCollection, Disable-AzOp…
Script     1.1.2      Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation…}
Script     1.1.0      Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessKey, Get-AzPowerBIWorkspace…}
Script     1.4.3      Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecoveryServicesVault…}
Script     1.1.0      Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-AzRedisCachePatchSchedule…}
Script     1.0.1      Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace…}
Script     1.6.1      Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment…}
Script     1.3.0      Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNamespace…}
Script     1.1.1      Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, Add-AzServiceFabricNode…}
Script     1.0.2      Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey…}
Script     1.13.1     Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseUpgradeHi…
Script     1.5.1      Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey…}
Script     1.2.0      Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncService, Get-AzStorageSyncService, Remove-AzStorageSyncService…}
Script     1.0.0      Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFunction, Remove-AzStreamAnalyticsFunction…}
Script     1.0.1      Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Remove-AzTrafficManagerCustomH…
Script     1.4.0      Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan…}
Script     0.0.0.10   AzureAD.Standard.Preview            Desk      {Set-AzureADDomain, Get-AzureADUserCreatedObject, New-AzureADApplicationPasswordCredential, New-AzureADServicePrincipal…}
Script     0.9.3      AzurePSDrive                        Desk
Script     17.0.2985… EXOPSSessionConnector               Desk      Connect-EXOPSSession
Manifest   1.0.613    MicrosoftPowerBIMgmt                Desk
Binary     1.0.613    MicrosoftPowerBIMgmt.Admin          Desk      {Add-PowerBIEncryptionKey, Get-PowerBIEncryptionKey, Get-PowerBIWorkspaceEncryptionStatus, Switch-PowerBIEncryptionKey…}
Binary     1.0.613    MicrosoftPowerBIMgmt.Capacities     Desk      Get-PowerBICapacity
Binary     1.0.613    MicrosoftPowerBIMgmt.Data           Desk      {Add-PowerBIDataset, Set-PowerBITable, New-PowerBIDataset, New-PowerBITable…}
Binary     1.0.613    MicrosoftPowerBIMgmt.Profile        Desk      {Connect-PowerBIServiceAccount, Disconnect-PowerBIServiceAccount, Invoke-PowerBIRestMethod, Get-PowerBIAccessToken…}
Binary     1.0.613    MicrosoftPowerBIMgmt.Reports        Desk      {Get-PowerBIReport, New-PowerBIReport, Export-PowerBIReport, Get-PowerBIDashboard…}
Binary     1.0.613    MicrosoftPowerBIMgmt.Workspaces     Desk      {Get-PowerBIWorkspace, Add-PowerBIWorkspaceUser, Remove-PowerBIWorkspaceUser, Set-PowerBIWorkspace…}
Binary     1.0.12     MicrosoftTeams                      Desk      {Get-CsBatchPolicyAssignmentOperation, Invoke-CsBatchPolicyAssignment}
Script     0.9.3      PSCloudShellUtility                 Desk      {Enter-AzVM, Get-AzCommand, Invoke-AzVMCommand, Enable-AzVMPSRemoting…}
Binary     0.8.1      SHiPS                               Desk
Script     21.1.18147 SqlServer                           Desk      {Add-RoleMember, Add-SqlAvailabilityDatabase, Add-SqlAvailabilityGroupListenerStaticIp, Add-SqlAzureAuthenticationContext…}

    Directory: /opt/microsoft/powershell/6/Modules

ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Manifest   1.2.3.0    Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   6.1.0.0    Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   6.1.0.0    Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty, Join-Path…}
Manifest   6.1.0.0    Microsoft.PowerShell.Security       Core      {Get-Credential, Get-ExecutionPolicy, Set-ExecutionPolicy, ConvertFrom-SecureString…}
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alias, Import-Alias, New-Alias…}
Script     1.3.2      PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource…}
Script     2.1.3      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability…}
Script     0.0        PSDesiredStateConfiguration         Desk      {Get-EncryptedPassword, Test-NodeResourceSource, ValidateNoNameNodeResources, Set-PSCurrentConfigurationNode…}
Script     2.0.0      PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineKeyHandler, Get-PSReadLineOption…}
Binary     1.1.2      ThreadJob                           Desk      Start-ThreadJob

## Debug output

<!-- Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block -->

```

```

## Error output

<!-- Please run Resolve-AzError and paste the output in the below code block -->



Set-AzDiagnosticSetting : Exception type: ErrorResponseException, Message: Category 'SQLInsights,AutomaticTuning,QueryStoreRuntimeStatistics,QueryStoreWaitStatistics,Errors,DatabaseWaitStatistics,Timeouts,Blocks,Deadlocks,Audit' is not supported., Code: BadRequest, Status code:BadRequest, Reason phrase: Bad Request
At line:1 char:1
+ Set-AzDiagnosticSetting -Name "Logs" -ResourceId $resourceId -Wor ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzDiagnosticSetting], PSInvalidOperationException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand

**Comment by cormacpayne** [comment]
@omerzubair for each of the commands that you're having trouble with, would you mind setting `$DebugPreference="Continue"` and re-running each command? This will write the requests and responses from the server to the debug stream, that you can then include in a new comment. This will help us gather enough information to resolve the issue.

**Comment by omerzubair** [comment]
@cormacpayne No worries will get back asap

**Comment by omerzubair** [comment]
Here we go
![image](https://user-images.githubusercontent.com/7728453/63392525-67aad500-c3fa-11e9-99a7-2992c875e915.png)

**Comment by omerzubair** [comment]
Set-AzDiagnosticSetting : Exception type: ErrorResponseException, Message: Category 'SQLInsights,AutomaticTuning,QueryStoreRuntimeStatistics,QueryStoreWaitStatistics,Errors,DatabaseWaitStatistics,Timeouts,Blocks,Deadlocks,Audit' is not supported., Code: BadRequest, Status code:BadRequest, Reason phrase: Bad Request
At line:1 char:1
+ Set-AzDiagnosticSetting -Name "Logs-TSD" -ResourceId $resourceId -Wor ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzDiagnosticSetting], PSInvalidOperationException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand

DEBUG: AzureQoSEvent: CommandName - Set-AzDiagnosticSetting; IsSuccess - False; Duration - 00:00:13.8435159; Exception - System.Management.Automation.PSInvalidOperationException: Exception type: ErrorResponseException, Message: Category'SQLInsights,AutomaticTuning,QueryStoreRuntimeStatistics,QueryStoreWaitStatistics,Errors,DatabaseWaitStatistics,Timeouts,Blocks,Deadlocks,Audit' is not supported., Code: BadRequest, Status code:BadRequest, Reason phrase: Bad Request ---> Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceUri, DiagnosticSettingsResource parameters, String name, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperationsExtensions.CreateOrUpdateAsync(IDiagnosticSettingsOperations operations, String resourceUri, DiagnosticSettingsResource parameters, String name, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 12:02:59 AM - SetAzureRmDiagnosticSettingCommand end processing.
DEBUG: 12:02:59 AM - SetAzureRmDiagnosticSettingCommand end processing.

**Comment by omerzubair** [comment]
Set-AzDiagnosticSetting : Exception type: ErrorResponseException, Message: Category 'SQLInsights,AutomaticTuning,QueryStoreRuntimeStatistics,QueryStoreWaitStatistics,Errors,DatabaseWaitStatistics,Timeouts,Blocks,Deadlocks,Audit' is not supported., Code: BadRequest, Status code:BadRequest, Reason phrase: Bad Request
At line:1 char:1
+ Set-AzDiagnosticSetting -Name "Logs" -ResourceId $resourceId -Wor ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzDiagnosticSetting], PSInvalidOperationException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand

DEBUG: AzureQoSEvent: CommandName - Set-AzDiagnosticSetting; IsSuccess - False; Duration - 00:00:13.8435159; Exception - System.Management.Automation.PSInvalidOperationException: Exception type: ErrorResponseException, Message: Category'SQLInsights,AutomaticTuning,QueryStoreRuntimeStatistics,QueryStoreWaitStatistics,Errors,DatabaseWaitStatistics,Timeouts,Blocks,Deadlocks,Audit' is not supported., Code: BadRequest, Status code:BadRequest, Reason phrase: Bad Request ---> Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceUri, DiagnosticSettingsResource parameters, String name, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperationsExtensions.CreateOrUpdateAsync(IDiagnosticSettingsOperations operations, String resourceUri, DiagnosticSettingsResource parameters, String name, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 12:02:59 AM - SetAzureRmDiagnosticSettingCommand end processing.
DEBUG: 12:02:59 AM - SetAzureRmDiagnosticSettingCommand end processing.

**Comment by omerzubair** [comment]
> Set-AzDiagnosticSetting : Exception type: ErrorResponseException, Message: Category 'SQLInsights,AutomaticTuning,QueryStoreRuntimeStatistics,QueryStoreWaitStatistics,Errors,DatabaseWaitStatistics,Timeouts,Blocks,Deadlocks,Audit' is not supported., Code: BadRequest, Status code:BadRequest, Reason phrase: Bad Request
> At line:1 char:1
> 
> * Set-AzDiagnosticSetting -Name "Logs" -ResourceId $resourceId -Wor ...
> * 
> * CategoryInfo          : CloseError: (:) [Set-AzDiagnosticSetting], PSInvalidOperationException
> * FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand
> 
> DEBUG: AzureQoSEvent: CommandName - Set-AzDiagnosticSetting; IsSuccess - False; Duration - 00:00:13.8435159; Exception - System.Management.Automation.PSInvalidOperationException: Exception type: ErrorResponseException, Message: Category'SQLInsights,AutomaticTuning,QueryStoreRuntimeStatistics,QueryStoreWaitStatistics,Errors,DatabaseWaitStatistics,Timeouts,Blocks,Deadlocks,Audit' is not supported., Code: BadRequest, Status code:BadRequest, Reason phrase: Bad Request ---> Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
> at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceUri, DiagnosticSettingsResource parameters, String name, Dictionary`2 customHeaders, CancellationToken cancellationToken) at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperationsExtensions.CreateOrUpdateAsync(IDiagnosticSettingsOperations operations, String resourceUri, DiagnosticSettingsResource parameters, String name, CancellationToken cancellationToken) --- End of inner exception stack trace --- at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet() at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.b__3_0(T c)
> at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
> at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
> at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
> DEBUG: Finish sending metric.
> DEBUG: 12:02:59 AM - SetAzureRmDiagnosticSettingCommand end processing.
> DEBUG: 12:02:59 AM - SetAzureRmDiagnosticSettingCommand end processing.

Above error was from Cloud Shell for **"Set-AzDiagnosticSetting"**

**Comment by omerzubair** [comment]
All good when I call a SQL server for **Get-AzDiagnosticSetting**

$resourceId = "/subscriptions/------------/resourceGroups/RGRG/providers/Microsoft.Sql/servers/srv/databases/db_it"
Get-AzDiagnosticSetting -ResourceId $resourceId -debug

**Comment by omerzubair** [comment]
but when i call a Keyvault with **Get-AzDiagnosticSetting**. you get nothing returned, 
see the debug below.

PS Azure:\> $resourceId = "/subscriptions/---------------/resourceGroups/RGRG/providers/Microsoft.KeyVault/vaults/devkvdelme"
Azure:/
PS Azure:\> Get-AzDiagnosticSetting -ResourceId $resourceId -debug
DEBUG: 12:10:20 AM - GetAzureRmDiagnosticSettingCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 12:10:20 AM - using account id 'MSI@-03--'...
WARNING: 12:10:20 AM - *** The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a
WARNING: 12:10:23 AM - *** The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model classes.
DEBUG: [Common.Authentication]: Authenticating using Account: 'MSI@-03--', environment: 'AzureCloud', tenant: '---------------------a-d--------'
DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
DEBUG: Checking Cache request http://localhost:50342/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01
DEBUG: Cache Hit
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com//subscriptions/---------------/resourceGroups/RGRG/providers/Microsoft.KeyVault/vaults/devkvdelme/providers/microsoft.insights/diagnosticSettings?api-version=2017-05-01-preview

Headers:
x-ms-client-request-id        : -------0f4e-41b1-b286-------------
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : -----a46b-4ca5-b218-----
Server                        : Microsoft-IIS/10.0
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : 4----3b64--2e--4928-90db---
x-ms-routing-request-id       : WESTUS:20190821T001025Z:-----2ec8-4-8-90-b----b058b
X-Content-Type-Options        : nosniff
Date                          : Wed, 21 Aug 2019 00:10:25 GMT

Body:
{
  "value": []
}


DEBUG: AzureQoSEvent: CommandName - Get-AzDiagnosticSetting; IsSuccess - True; Duration - 00:00:05.5647742; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 12:10:26 AM - GetAzureRmDiagnosticSettingCommand end processing.
DEBUG: 12:10:26 AM - GetAzureRmDiagnosticSettingCommand end processing.

**Comment by omerzubair** [comment]
> @cormacpayne

OK have some update on one of the issue "Get-AzDiagnosticSetting"
The GET command will only return something if you have manually added atleast one Diagnostic setting. This is sad as i want automation to figure out all categories before i use SET command.

- So then question arises how will i get the -Category switch values at the time of using **SET-AzDiagnosticSetting** in automation?
- and every resource categories & metric categories will be different?


Set-AzDiagnosticSetting -Name "Logs" -ResourceId $resourceId -WorkspaceId $LogAnalytics_URI -Category **$categoryLogsStringWithComma** -MetricCategory **$categoryMetricsStringWithComma** -Enabled $true -debug

**Comment by slavizh** [comment]
@omerzubair In case you are not familiar you can find the categories with API call:
https://cloudadministrator.net/2018/12/17/finding-diagnostic-logs-for-azure-services/
I think the same call can be made via Az cmdlets in case you want to fully automate that and not use armclient which is interactive tool.

**Comment by omerzubair** [comment]
Hi @slavizh
I have a task to implement this in Azure automation accounts. therefore i need an AZ command to get the log & metric categories. Therefore cannot use armclient
Would you know any AZ command?
Once the SET command starts working i can try it out by fully automating it.

**Comment by slavizh** [comment]
You have to use the general Az resource commands.
it should be possible with either invoke-azresourceaction or get-azresource. These commands are used to get information directly from ARM API.

**Comment by omerzubair** [comment]
Hi @slavizh  
I tried 
$resource = Get-AZResource -ResourceId $rid

and it does not have Diagnostic Settings Categories 
then I ran

$resource | Format-Custom

It returned me the ARM template for the keyvault (JSON)
So i could not see any diagnostic setting in JSON as well. :( 

It seems like the diagnostic settings is at Resource Group level. However following did not yield anything either.

$rg = Get-AzResourceGroup -Name "MyRGName"
$rg | Format-Custom

any other suggestions to get the Log & Metric categories ?

**Comment by omerzubair** [comment]
Ok we can close this ! Thanks for the help @slavizh & @cormacpayne

I have found solution 👍 

https://stackoverflow.com/questions/52207388/azure-powershell-diagnostics-settings  

**Answer:** Just dont mention any category switch and it will select all categories by default!
