### ISSUE TITLE
Extend/remove the limit of 25 context after login

### ISSUE THREAD

**Issue by shaqian** [Azure/azure-powershell#9865]
## Description of the new feature

By default Azure PowerShell populates context for only 25 subscriptions after login. 
https://github.com/Azure/azure-powershell/blob/master/src/Accounts/Accounts/Models/RMProfileClient.cs#L293
```c#
var subscriptions = ListSubscriptions(tenantId).Take(25);
```

The limit is hard-coded. Users have to manually run additional commands to add more subscriptions. 

It'd be great to have a more flexible way for user to choose how many subscriptions to populate context for. 

## Proposed implementation details (optional)

Add an option for how many context to populate by default.

**Comment by cormacpayne** [comment]
@shaqian thanks for the suggestion -- is there a preference on how this should be implemented? I think there are two ways to go about this:

(1) `Connect-AzAccount -PopulateAllContexts`

(2) `Connect-AzAccount -MaxContextsToPopulate <int>`

Do you think it would be better to (1) create a context for every subscription that the user has access to, or (2) allow the user to provide how many contexts they want?

**Comment by shaqian** [comment]
Hi @cormacpayne  I think 1) is better. :)

**Comment by dingmeng-xue** [comment]
Can we merge 2 parameters together. If MaxContextsToPopulate < 0, it means to load all subscriptions?

**Comment by dingmeng-xue** [comment]
@BethanyZhou , given we have no environment to accurately evaluate performance impact in large tenant, let's focus on option 2 for the time being.

**Comment by BethanyZhou** [comment]
#12397
