### ISSUE TITLE
DocumentDB PowerShell commands are completely missing

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#987]
DocumentDB commands are missing from Azure Service Management & Resource Manager modules.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by hovsepm** [comment]
@pcgeek86 We do not have current plans to add cmdlets for DocumentDB.
