### ISSUE TITLE
New-AzRecoveryServicesVault - Add Tags support

### ISSUE THREAD

**Issue by rwaal** [Azure/azure-powershell#9874]
Please add a Tags parameter to the New-AzRecoveryServicesVault cmdlet. This would allow a Recovery Service Vault to be created with tags. 

Many Azure Powershell cmdlets already contain the Tags parameter. The New-AzRecoveryServicesVault however does not. 

Our scenario: 
We use Azure Policy to enforce that only resources can be created that have tags. When using the New-AzRecoveryServicesVault to create the resourece this becomes a problem.

**Comment by cormacpayne** [comment]
@siddharth7 @pvrk Hey folks, would you mind taking a look at this feature request?

**Comment by pvrk** [comment]
Thanks @rwaal for the feedback. We have added this to backlog. I will soon update on the planning.

**Comment by pvrk** [comment]
@rwaal : We have added support for tags while creating Recovery services vault with the [3.4.0 Az PS](https://github.com/Azure/azure-powershell/releases/tag/v3.4.0-February2020) version.

I will update the documentation. Meanwhile please check and let us know your feedback.
Thanks.

**Comment by pvrk** [comment]
Closing the feature-request issue since it is implemented

**Comment by rwaal** [comment]
@pvrk : I just did some testing, and the added functionality seems to work ok in version 3.4.0 of the module. I am now able to create a Recovery Services Vault with tags using Powershell. 

Thank you for adding this feature! 👍
