### ISSUE TITLE
Mismatch in the DefaultAction Enum values.

### ISSUE THREAD

**Issue by marcan2020** [Azure/azure-powershell#9880]
## Description

Opening an issue for tracking as requested by @blueww in https://github.com/Azure/azure-powershell/pull/9837.

There's a mismatch between models representing the same thing:
- [Microsoft.Azure.Commands.Management.Storage.Models.PSNetWorkRuleDefaultActionEnum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.management.storage.models.psnetworkruleset.parsepsnetworkruledefaultaction?view=azurerm-ps)
- [Microsoft.Azure.Management.Storage.Models.DefaultAction](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.models.defaultaction?view=azure-dotnet)

**Comment by blueww** [comment]
Will see if can take it in the next major release.

**Comment by kartikshah9** [comment]
@blueww can you please provide an update on this? Has the bug #10396 been fixed and merged. Can this GitHub issue be closed?

**Comment by blueww** [comment]
This has not been fixed. 
For current breaking change process, We need fix it in a major release, and need add warning message for it several release before the major release.
https://github.com/Azure/azure-powershell/pull/10396 is no merged, and rejected since need add warning several release before the major release.

**Comment by kartikshah9** [comment]
@blueww is there a timeline for fixing the above issue in a major release. Request if you can provide an update on the same

**Comment by blueww** [comment]
It should be fixed in the next major release. 
I will raise a PR for warning message before that.

@kartikshah9  BTW, when will be the next major release?

**Comment by zhusijia26** [comment]
@blueww has the fix been released?

**Comment by blueww** [comment]
@zhusijia26 
No, this hasn't been fixed, since it's a breaking change, it might be fixed in a major release (twice a year).
And I have raised a PR to add breaking change warning, and this PR merged.
Then when the next major release come, we can fix it.

**Comment by blueww** [comment]
Close as the PR to fix this is merged.
It will be in the next PSH release.
