### ISSUE TITLE
Get-AzSqlElasticJobAgent not correctly deal with FQDN passed as ServerName

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-powershell#9881]
## Description
Get-AzSqlElasticJobAgent shall correctly deal with FQDN passed as `ServerName` parameter

## Steps to reproduce

```powershell

Get-AzSqlElasticJobAgent -ResourceGroupName "Default-SQL-NorthCentralUS" -Name "ElasticJobAgent" -ServerName mydb.database.windows.net
```

Currently if `-ServerName` passed as FQDN it will fail with error below. If you go to Azure portal you can see that `ServerName` is defined as FQDN so people will spend sometime trying to figure out why cmdlet failing

![image](https://user-images.githubusercontent.com/13176884/63463182-478f0c00-c422-11e9-8e0d-39cb9fde0298.png)

```
Get-AzSqlElasticJobAgent : The Resource 'Microsoft.Sql/servers/mydb.database.windows.net/jobAgents/tncdb-ncus' under resource group 'Default-SQL-NorthCentralUS' was not found.
At line:1 char:1
```

**Comment by cormacpayne** [comment]
@jaredmoo @johnpaulkee Hey guys, would you mind taking a look at this issue?

**Comment by jaredmoo** [comment]
This is not specific to JobAgent cmdlets. All SQL cmdlets refer to the server name `myserver`, not the server domain name `myserver.database.windows.net`. The fix here should be to clarify the portal UX.

**Comment by jeroenterheerdt** [comment]
Closing this issue. @artisticcheese do not hesitate to respond if you need more help.
