### ISSUE TITLE
[HanaOnAzure] Generation, review basic scenario and publish module

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#9885]
## Description

Generate and customize modules for the Azure HanaOnAzure  service

- [ ] Implement requested configurations and customizatiosn from review
- [ ] Add to Az preview release

**Comment by isra-fel** [comment]
I was trying to generate code using autorest but got an error

> Error: Cannot resolve pipeline stage 'openapi-document/multi-api/identity'.

autorest 3.0.5532
autorest.powershell (beta->2.0.648)
autorest.remodeler (beta->2.0.374)

Log:
![image](https://user-images.githubusercontent.com/11371776/63661610-dff40a80-c7ed-11e9-9944-0bfd923faee5.png)

**Comment by isra-fel** [comment]
One limitation is that when I set the **title** to "HanaOnAzure", autorest will automatically remove "Azure" and the generated module name becomes "Az.HanaOn".

One workaround is to replace and rename all `Az.HanaOn` with `Az.HanaOnAzure`, but there are too many of them, and I'm not sure if renaming an DLL would work.
(Or maybe we don't have to rename all the `Az.HanaOn`s.

I'll ask Xiaogang to see if there's workaround from autorest's pesrspective. It should cost less effort.

**Comment by isra-fel** [comment]
The module name issue was solved by specifying `service-name`. See https://github.com/Azure/azure-powershell/blob/master/src/HanaOnAzure/readme.md#autorest-configuration

Closing this issue as the development is done and module is going to be released.
