### ISSUE TITLE
Generation for Azure ContainerRegistry Service

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#9886]
## Description

Generate and customize modules for the Azure ContainerRegistry service

- [ ] Generate, build, and examine API surface
- [ ] Ensure that all POST operations use only expanded variants
- [ ] Ensure that New/Set/Update cmdlets use only expanded variants
- [ ] Change Cmdlet, Parameter, and property names for consistency and clarity
- [ ] Write CRUD tests for top-level resources
- [ ] Hold a cmdlet design review using the updated generated help files
- [ ] Implement requested configurations and customizations from review
- [ ] Add to Az preview release

**Comment by erich-wang** [comment]
Close as it is done
