### ISSUE TITLE
0.9.8 ARM: New-AzureResourceGroupDeployment -storageaccountName template locking

### ISSUE THREAD

**Issue by robplank** [Azure/azure-powershell#989]
please remove the lock placed on the template file once it is uploaded to the storage account.

When doing multiple deployments to the same storage account that use the same template file, this results in failed deployments 

<B>Error Meesage </B>
 DeploymentActive: Unable to edit or replace deployment 'DeploymentTemplateFile': previous 
deployment from '9/28/2015 4:16:21 PM' is still active 

<B> Desired Action</B>

the ability to deploy ARM templates in a foreach -parallel loop without errors

Foreach -parallel($VM in $VMs) 
{
$Param = @()

AzureResourceManager\New-AzureResourceGroupDeployment -ResourceGroupName $ResourceGroup -TemplateUri '.\DeploymentTemplateFile.json' -TemplateParameterObject $Params -storageaccountNameFromTemplate $storageAccount

}

**Comment by ravbhatnagar** [comment]
This should not be an issue in PowerShell 1.0 and beyond. The storage account does not need to be specified now.

**Comment by GrahamDSmith** [comment]
Not sure this is fixed. Please see my comment [here](https://disqus.com/home/discussion/thewindowsazureproductsite/deploy_an_application_with_azure_resource_manager_template/#comment-2522268046).
