### ISSUE TITLE
webapp:New-AzAppServicePlan - Add Tags support

### ISSUE THREAD

**Issue by canuzun** [Azure/azure-powershell#9895]
## Description of the new feature
The New-AzAppServicePlan cmdlet is missing -Tag parameter. This also applies the Set-AzAppServicePlan too.

#3996 this is an old issue which was for AzureRM and was closed because apparently at that time the portal was not supporting tags on this resource type. But now the portal does support this, so should the PS cmdlet.

**Comment by panchagnula** [comment]
Adding a milestone to track

**Comment by panchagnula** [comment]
@ThejaChoudary good next task to try.

**Comment by ThejaChoudary** [comment]
Taking a look at this..

**Comment by panchagnula** [comment]
closing since the PR with the fix is merged https://github.com/Azure/azure-powershell/pull/11189
