### ISSUE TITLE
Set-AzStorageBlobContent : This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

### ISSUE THREAD

**Issue by Xergy** [Azure/azure-powershell#9908]
## Description

I’m getting the below error.  When searching for resolution, I find all the standard disable FIPS regkey/policy stuff…  relaxing security on this machine is not an option for me.  Surely we can do a blob copy without tripping over FIPS.  

Set-AzStorageBlobContent : This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
At line:1 char:1
+ Set-AzStorageBlobContent -Context $StorageAccountCtx -Container "$Sto ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzStorageBlobContent], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.WindowsAzure.Commands.Storage.Blob.SetAzureBlobContentCommand

VERBOSE: Transfer Summary
--------------------------------
Total:  1.
Successful: 0.
Failed: 1.

## Steps to reproduce
I am not the admin of the box I'm having this issue from.  It's my customer's box.  But, I assume that they have done something like this:

https://support.microsoft.com/en-us/help/811833/system-cryptography-use-fips-compliant-algorithms-for-encryption-hashi 

## Environment data , Module Versions

I’m running Az.Storage 1.5.1 in VS Code.  Powershell modules are installed in the context of the User i.e. I’m not an admin on the box.

## Error output

Set-AzStorageBlobContent : This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

**Comment by blueww** [comment]
@Xergy
I can repro the issue with Az.Storage 1.5.1.
I will investigate more on this, and update you soon.

**Comment by blueww** [comment]
@Xergy
We found this is a DMlib issue which happens only on NetStarndard with specific .NET frameworks (the one Powershell use can repro).
I have opened a DMlib issue for that https://github.com/Azure/azure-storage-net-data-movement/issues/186

I will work with DMlib team to resolve the issue, and then update PSH, to the fixed DMlib to fix the issue in PSH.

**Comment by blueww** [comment]
@Xergy
We have already merge the fixed DMlib to PSH code base, the issue will be fixed in the next PSH release. (Az.Storage 1.7.0)
I will close the issue now. 
Feel free to contact us if need any further assistance.
