### ISSUE TITLE
Invoke-AzOperationalInsightsQuery max results

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-powershell#9916]
The Azure portal has a limit of 10,000 results that are displayed when running a Log Query. (see [here](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/log-faq#q-after-running-a-query-a-list-of-suggested-filters-are-available-how-can-i-see-filters))

Can you confirm that there is no maximum to the results returned for Invoke-AzOperationalInsightsQuery?
https://docs.microsoft.com/en-us/powershell/module/az.operationalinsights/invoke-azoperationalinsightsquery?view=azps-2.5.0

**Comment by dcbrown16** [comment]
@xizhamsft we're working with a customer on a support case and they are reporting that they are hitting some kind of limit, so any info you can share would be appreciated.

**Comment by dcbrown16** [comment]
https://techcommunity.microsoft.com/t5/Azure-Log-Analytics/OMS-Query-for-exporting-results-in-excel-more-than-10000-results/m-p/306829
This post from Noa suggests that the limit of 10,000 is not applicable to the API, so I want to specifically confirm here if that's also the case for PowerShell. I assume PowerShell doesn't have a limit.

**Comment by dcbrown16** [comment]
Update - we got separate info from Log Analytics that the "Search API" limits here should apply.
https://docs.microsoft.com/en-us/azure/azure-monitor/service-limits#log-analytics-workspaces

The customer is saying they got 500,000 results (from Firewall logs). However, the query in this case didn't use the "summarize" command, so it's unclear why the aggregated data limit of 500,000 would apply, as opposed to the non-aggregated data limit of only 5,000 results.

`(Invoke-AzOperationalInsightsQuery -WorkspaceId 'xxxxx' -Query 'AzureDiagnostics | where Category == 'AzureFirewallNetworkRule' | parse msg_s with Protocol ' request from ' SourceIP ':' SourcePortInt:int ' to ' TargetIP ':' TargetPortInt:int '. Action: ' Action | project  TimeGenerated, Protocol, SourceIP, SourcePortInt, TargetIP ,  TargetPortInt , Action | where TimeGenerated >= todatetime('2019-07-01T00:00:00') | where TimeGenerated <= todatetime('2019-08-30T23:00:00')').Results | export-csv 'AzureFirewallApplicationRule.csv'`

**Comment by yossi-y** [comment]
This is correct, the maximum number of records returned in a single query is limited to 500,000.

You can see [Log queries and language](https://docs.microsoft.com/en-us/azure/azure-monitor/service-limits#log-queries-and-language) for General query limits and throttling.

See *Search API* under [Log Analytics workspaces](https://docs.microsoft.com/en-us/azure/azure-monitor/service-limits#log-analytics-workspaces) for API limits. If you need to get more than 500,000 records, the way to achieve it: via several calls.
