### ISSUE TITLE
Get-AzRedisCache doesn't retrieve MinimumTlsVersion

### ISSUE THREAD

**Issue by chamix** [Azure/azure-powershell#9923]
## Description
Using the commang Get-AzRedisCache I could not able to return information about MinimumTlsVersion set up for Azure Cache for Redis

## Steps to reproduce
Execute Get-AzRedisCache
![get-azrediscache-no-tlsversion](https://user-images.githubusercontent.com/382679/63806282-a0aee200-c8f1-11e9-8516-6855c3e84210.png)

```powershell

```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by cormacpayne** [comment]
@SiddharthChatrolaMs Hey Siddharth, would you mind taking a look at this issue?

**Comment by MECHANDR** [comment]
Issue fixed as part of PR #10510. Closing this issue.
