### ISSUE TITLE
[Documentation] Overview of ARM/Graph concepts and scenarios

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#9926]
## Description

Outline important concepts and scenarios for the ARM and Graph cmdlets.

- [x] `ResourceManager` project
    - [x] Resources / ResourceGroups
    - [x] Deployments
    - [x] Policies
- [x] `Resources` project
    - [x] ActiveDirectory
        - [x] Applications
        - [x] Groups
        - [x] ServicePrincipals
        - [x] Users
    - [x] RoleAssignments
    - [x] RoleDefinitions

**Comment by markcowl** [comment]
Fixed
