### ISSUE TITLE
[Documentation] Developer guide for customizations in generated cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#9928]
## Description

Create a developer guide outlining the different types of customizations that could be added for generated cmdlets.

- [x] When to use customizations
- [x] How do customizations get used
- [x] Example(s) of adding/removing parameters to/from an existing variant/parameter set
- [x] Example(s) of replacing filter parameters (_e.g._, `-Filter` parameter using OData Query)
- [x] Example(s) of hiding cmdlets and rewriting it entirely as a customization
- [x] Example(s) of introducing a brand new cmdlet as a customization
- [x] Example(s) of updating the properties on a model type
- [ ] Example(s) of both C# and PowerShell customizations

**Comment by niander** [comment]
https://github.com/Azure/autorest/pull/3304
