### ISSUE TITLE
Moving DB to Elastic Pool with Set-AzSqlDatabase fails

### ISSUE THREAD

**Issue by lehtope1** [Azure/azure-powershell#9934]
## Description

Hi,

Moving an existing Azure SQL database into an Azure SQL Elastic Pool with Set-AzSqlDatabase fails with error:

```powershell
Set-AzSqlDatabase : Long running operation failed with status 'Failed'. Additional Info:'The operation could not be completed because the read scale value specified is not supported for a 'Standard' database.'

```

Even when specifying -ReadScale "Disabled" to the command, the same error is thrown.

## Steps to reproduce

```powershell

Set-AzSqlDatabase -ResourceGroupName "RG_NAME" -ServerName "SERVERNAME" -DatabaseName "DBNAME -ElasticPoolName "EPNAME"
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.3053
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3053
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

## Module versions

```powershell
Version    Name                           
1.14.1     Az.Sql
```

**Comment by cormacpayne** [comment]
@jaredmoo Hey Jared, would you mind taking a look at this issue?

**Comment by jaredmoo** [comment]
What is the current edition and ReadScale state of the database? My guess is that this database is currently Premium or BusinessCritical and has ReadScale enabled. Moving this into a Standard pool will fail because Standard doesn't support ReadScale - in other words, you need to set ReadScale to Disabled when you move the database into the pool.

**Comment by jaredmoo** [comment]
> Even when specifying -ReadScale "Disabled" to the command, the same error is thrown.

Sorry, I missed this line. We're investigating.

**Comment by bradrich-msft** [comment]
We have identified the issue and are working on the fix.  We apologize for the inconvenience.  You may workaround this in the meantime by first disabling ReadScale on the database before moving to an elastic pool.

**Comment by jeroenterheerdt** [comment]
this should have been resolved. closing the issue @lehtope1 do not hesitate to reach out if you need more help.
