### ISSUE TITLE
Insufficient information to produce Service Bus SAS token

### ISSUE THREAD

**Issue by yevster** [Azure/azure-powershell#9959]
## Description of the new feature
To read and write to Service Bus Queues, a SAS token is required. It would be helpful to be able to obtain a SAS token from PowerShell so as to use the Service Bus REST APIs for which no CMDlets are available. A SAS requires a rule expiration date, which currently can be obtained with neither `Get-AzServiceBusKey` nor `Get-AzServiceBusAuthorizationRule`.

## Proposed implementation details (optional)
Ideally, the object returned by `Get-AzServiceBusKey` would contain a `SasToken` field containing a fully formed SAS token.

Independently, the output of `Get-AzServiceBusAuthorizationRule` should return an expiration date for the rule.

**Comment by cormacpayne** [comment]
@v-Ajnava Hey Ajit, would you mind taking a look at this feature request?

**Comment by v-Ajnava** [comment]
Hi @yevster, 

Recently, about two releases back, we have added new command to generate SAS token for a give authorization rule . 

below is the link for the documentation from the latest  release. 
https://docs.microsoft.com/en-us/powershell/module/az.servicebus/new-azservicebusauthorizationrulesastoken?view=azps-2.6.0

please try with the latest release and lets us know your experience and view on cmdlet.

**Comment by v-Ajnava** [comment]
we are closing this issue, please re-open if you have any questions.
