### ISSUE TITLE
New-AzRoleAssignment default parameterset has incorrect mandatory value for parameter Scope

### ISSUE THREAD

**Issue by Willem-J-an** [Azure/azure-powershell#9967]
## Description
@ https://github.com/Azure/azure-powershell/blob/master/src/Resources/Resources/RoleAssignments/NewAzureRoleAssignmentCommand.cs
The New-AzRoleAssignment cmdlet has an incorrect mandatory value of $true for the parameter 'Scope' in the parameterset.empty.
This overrules  ParameterSet.ScopeWithObjectId, where the parameter is not mandatory, making that parameterset unusable. When providing only ObjectId and RoleDefinitionName, powershell prompts for the scope, which is not be mandatory in ParameterSet.ScopeWithObjectId. 

## Steps to reproduce

```powershell
New-AzRoleAssignment -ObjectId '' -RoleDefinitionName 'Reader'
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell

Get-InstalledModule -Name Az -AllVersions | select Name,Version

Name Version
---- -------
Az   2.6.0
```

**Comment by cormacpayne** [comment]
@Willem-J-an thanks for filing this issue -- I think the correct thing to do here is to remove `ScopeWithObjectIdParameterSet` altogether and make the `-Scope` parameter optional in the `Empty` parameter set, which will enable this previously unusable scenario while keeping existing scripts in tact.

@darshanhs90 any thoughts?

**Comment by Willem-J-an** [comment]
Hi @cormacpayne, makes sense! With this change the ScopeWithObjectIdParameterSet parameterset becomes redundant.

Additionally, perhaps this markdown should be edited? 
[New-AzRoleAssignment.md](https://github.com/Azure/azure-powershell/blob/c444100ed18d235a87adb69bbeba9df23ad146e4/src/Resources/Resources/help/New-AzRoleAssignment.md)

Should I implement this in my PR?

**Comment by cormacpayne** [comment]
@Willem-J-an that would be great -- the markdown files are generated using the `platyPS` module. You can take a look at [this document](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md) for more information on generating help in our repository, and [this section specifically](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md#updating-a-single-markdown-file) for information on generating the markdown for a single cmdlet.
