### ISSUE TITLE
Start-AzAutomationSourceControlSyncJob Add SyncType parameter to invoke 'Incremental' syncs

### ISSUE THREAD

**Issue by ricohomewood** [Azure/azure-powershell#9980]
The `Start-AzAutomationSourceControlSyncJob` function only triggers a FullSync from a connected Azure DevOps Repo, which can sometimes take a long time if you have lots of runbooks in a repo. Can we add a pramater to this to trigger an option incremental sync. 

**Use Case**
The Azure Automation account has this option as a feature toggle but not something that can be triggered ad-hoc after a full sync outside of Azure Automation. We don't want to use the AutoSync feature as we want to control the upload of runbooks via Azure DevOps pipelines with approvals etc. then trigger a sync job once certain criteria / tests have been made.

Example:
`Start-AzAutomationSourceControlSyncJob -ResourceGroupName "rg1"                                                     -AutomationAccountName "devAccount" -Name "VSTSNative" -SyncType "Incremental"`

**Comment by zjalexander** [comment]
Hi,

Since this is a feature request for the Azure Automation Source Control feature, can I ask you to please post it in our UserVoice here: https://feedback.azure.com/forums/246290-automation ? That will help us track the request, allow others to see and vote for it, and let us prioritize it among the other feature requests.

**Comment by ricohomewood** [comment]
> Hi,
> 
> Since this is a feature request for the Azure Automation Source Control feature, can I ask you to please post it in our UserVoice here: https://feedback.azure.com/forums/246290-automation ? That will help us track the request, allow others to see and vote for it, and let us prioritize it among the other feature requests.

zjalexander The feature already exists in Source Control in the portal UI, just requesting the ability to invoke it from the Start-AzAutomationSourceControlSyncJob powershell cmdlet. Is this still considered a feature request in that sense? If so, will also post on User Voice.
Thanks

**Comment by andyw248** [comment]
Closing - please file a feature request as discussed above.

**Comment by ricohomewood** [comment]
@andyw248 @zjalexander As UserVoice was disbanded by Microsoft. Can this please be re-opened as this is still not supported but much needed? Thanks
