### ISSUE TITLE
i can't use install module 

### ISSUE THREAD

**Issue by t105362506** [Azure/azure-powershell#9986]
![image](https://user-images.githubusercontent.com/54572002/64399568-73092c00-d09b-11e9-8c47-920f7fb0005a.png)

**Comment by erich-wang** [comment]
Please run $PSVersionTable and paste the output in the below code block

```

```

## Module versions

Please run (Get-Module  -ListAvailable) and paste the output in the below code block

```powershell

```

## Debug output

Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block

```

```

**Comment by t105362506** [comment]
Thanks that it work
