### ISSUE TITLE
Export-AzApiManagementApi openapi+json

### ISSUE THREAD

**Issue by dirkslab** [Azure/azure-powershell#9987]
## Description of the new feature
Adding openapi+json as a SpecificationFormat option to Export-AzApiManagementApi.
Currently SpecificationFormat "openapi" downloads as yaml. there is no powershell support to convertfrom-yaml in core, so it would make sense for default (or option) to be in json format. Powershell supports convertfrom-json.

**Comment by shinsey-st** [comment]
Is there a reasonable, portable workaround for this until official support lands? It looks like this is baked in at a pretty low level in the SDK API so going that route doesn't seem like a quick fix.

**Comment by dirkslab** [comment]
Thanks for the feedback. 
Workaround for automation (currently) is to make do with swagger 2. 
You can convert yaml to json or swagger from 2 to 3 (personally avoiding this option). 
Assume this will get fixed in the future as being stuck on v2 indefinitely does not seem practical.
As long as the current setup was due to degree of difficulty and not logic.

**Comment by shinsey-st** [comment]
Thanks, I wanted to make sure I wasn't missing something.

In case someone else happens down the same weird path that led me here, I
ended up going with the YAML document. Swagger 2 JSON didn't work for my
situation, which is the implementation of a "diff" to compare two specs.
The OpenAPI 3 JSON document has more type fidelity and resulted in spurious
diff detections, for example, a Guid is a string in Swagger and a string
with a format of guid in OpenAPI. This difference is probably not
significant in most use cases but the YAML output has the same level of
fidelity and sidesteps the issue.

**Comment by solankisamir** [comment]
@dirkslab I have created https://github.com/Azure/azure-rest-api-specs/pull/8155 to make changes in the REST spec. Once those changes are in, we can generate a .net sdk and update changes in powershell.

Currently, there is a bug in the backend in this path, we are fixing that with deployment. ETA 2 weeks.

**Comment by solankisamir** [comment]
Please download the update from 

Download the install package from Github: https://github.com/Azure/azure-powershell/releases/tag/v3.6.1-March2020 
Install the package from PSGallery: https://www.powershellgallery.com/packages/Az/3.6.1
