### ISSUE TITLE
Powershell  expansion can't run 

### ISSUE THREAD

**Issue by t105362506** [Azure/azure-powershell#9992]
![image](https://user-images.githubusercontent.com/54572002/64507821-46107f80-d30e-11e9-978b-8aab450284b3.png)

**Comment by t105362506** [comment]
starting  That  is   long time
![image](https://user-images.githubusercontent.com/54572002/64510839-9ccd8780-d315-11e9-91fd-353528fe390a.png)

**Comment by erich-wang** [comment]
@t105362506, this repo is used to track issue when using [Azure PowerShell Module](https://docs.microsoft.com/en-us/powershell/azure/overview?view=azps-2.6.0), however the issue you created seems to be related to [powershell extension in vs code](https://github.com/PowerShell/vscode-powershell), please open new issue in https://github.com/PowerShell/vscode-powershell. I'm closing this issue, please let us know if any concern.
