### ISSUE TITLE
New-AzSubscription should send welcome email to specified owner

### ISSUE THREAD

**Issue by yobyot** [Azure/azure-powershell#9998]
If `New-AzSubscription` is called with either `-OwnerObjectId` or `-OwnerSignInName`, the welcome email, whose subject line reads "Your Azure subscription is ready," is sent to the user whose context (via `Set-AzContext`) was used to create the subscription. At the very least, the option to cc: the owner should be provided in addition to emailing the context user. 

Here's a screenshot showing the result of a call to `New-AzSubscription` which specified `-OwnerSigninName`

![2019-09-09_16-12-16 (1)](https://user-images.githubusercontent.com/14332263/64564000-9f80aa80-d31e-11e9-8ba0-4f75c0e13ff0.png)

**Comment by prem9in** [comment]
This should be assigned to @veathipa

**Comment by anuragdalmia** [comment]
Thank you for your feedback. We have added this to our backlog. We will plan on evaluating this with our other items and prioritize accordingly. Please let us know if you believe this is an urgent request that blocks any of your customer scenario and we will prioritize this higher. For now, I will be closing this thread. Please re-active if you disagree.
